### ISSUE TITLE
[question] How to implement an installer package when cross-building?

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5004]
To help us debug your issue please explain:

Conan version 1.14.3
related PR: https://github.com/bincrafters/conan-flex/pull/4

Hi! 

When trying to help @madebr with Flex, I found an weird situation which requires your help!

All installer packages (e.g. bison_installer, protoc_installer) use the attributes `arch_build` and `os_build` only. We could add `compiler` too, but we remove it from the package id. To build any package, we run:

    conan create . bincrafters/testing

So far, so good. The binary will be built for my host os and arch which is x86_64.

However, I also need to distribute for x86, thus I run:

    conan create . bincrafters/testing -s arch_build=x86

Ops! When I check the generated binary is was compiler for x86_64! It occurs because my target arch is x86_64, since I didn't declared a specific value and my default profile is 64-bits. To solve this, I add the specific target arch:

    conan create . bincrafters/testing -s arch_build=x86 -s arch=x86

But again the generated binary is 64-bits. Since the recipe doesn't have `arch` in the settings, Conan won't customize cflags with -m32. To solve this, I can declare `arch` in the recipe's settings and remove it from package id

```python
settings = 'os_build', 'arch_build', 'compiler', 'arch'
    
def package_id(self):
    del self.info.settings.compiler
    del self.info.settings.arch
```

Now the previous commands works like charm ... But it's wrong, as I forced both `arch` and `arch_build` with same value and I need to use `tools.cross_building(self.settings)`, it will return `False`. To see the correct behavior, I need to use only target `arch`, but override my  `arch_build` value:

```python
settings = 'os_build', 'arch_build', 'compiler', 'arch'
    
def package_id(self):
    self.info.settings.arch_build = self.info.settings.arch
    del self.info.settings.compiler
    del self.info.settings.arch
```

    conan create . bincrafters/testing -s arch=x86

Now I have the expected behavior: I can cross compile my installer package AND it's detect by `tools.cross_building`.

As you can see, there are many pitfalls and to achieve the expected behavior I made many changes which polluted the recipe.

Now returning to the title: How to implement an installer package when cross-building? 

I don't see an easy way without breaking some behavior, since it seems be related to Conan design.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi, I think that is the general issue with the cross-build model we are facing.
The idea behind the new cross building model we are suggesting is not to have special settings like `os_build` or `arch_build` but to change the "context" of the setting when they are using as build requires.
So, the consumer will have 2 profiles, one for building and one for targetting, regular ones, with all the settings possibilities from the setting.yml.
The idea is that Conan can change the profile to the "build" one when a build_require (and all its requirements) are built.
If you want I can explain it to you a bit more in detail and show you some ideas. Ping me on slack. Would be nice if you can verify that this could solve the issue.

**Comment by lasote** [comment]
I have to say that your "workaround" is totally ok, we usually explain the "settings" variable as "the things that cause a package_id change", but it should be also "the inputs that the package needs to be built". 
It is very common that a header only library needs the compiler setting to build some tests and then discard it in the `package_info` method.
So, the only "new" or more tricky part is the `self.info.settings.arch_build = self.info.settings.arch` but it makes sense. That is part of the change of context that the new model should do automatically.

**Comment by memsharded** [comment]
Closing this ticket as outdated now there is a new cross-build and host/build context model.
