### ISSUE TITLE
Endpoint not implemented when my Artifactory uses a non-standard port (8081)

### ISSUE THREAD

**Issue by kwilliamszaf** [conan-io/conan#5007]
Hi

I'm trying to authenticate against a remote, to eventually upload a package.

`conan user -p mypassword -r <remote name> mytestuser`

With our company Artifactory: (`vt_artifactory1: http://artifactory1.xyz.co.za:8081 [Verify SSL: True]`) I get an error about an unimplemented endpoint.

If I try one of the community remotes, I get an error about unknown user/password etc. as expected.

Could someone please help?

Many thanks! Kevin

**Comment by memsharded** [comment]
Hi @kwilliamszaf 

It seems that you added the wrong URL, you added the server URL, not the repo URL. I guess that all attempts to "search", "get", "install", "inspect", etc, from that remote will fail.

Please check the "Set Me Up" helper in Artifactory, it will provide a more complete URL that points to the Conan local repo (you need to create it first).

Please tell me if this helps, thanks!

**Comment by kwilliamszaf** [comment]
Hi @memsharded 

Thanks for your reply!

Yes, indeed that seems to have been the problem.

I've just got a few authentication issues now with the actual Artifactory repo, but will chat to our admin guy about it. (I have got the API password etc., and a valid username on it.)

I am really enjoying this workflow.

Thanks again.

**Comment by memsharded** [comment]
Hi @kwilliamszaf 

Good to know, thanks for telling :).

And let us know if your IT can't sort it out. Cheers!
