### ISSUE TITLE
recipe found by search can't be found by install and inspect

### ISSUE THREAD

**Issue by bl4ck5un** [conan-io/conan#5008]
I'm following the [get started tutorial](https://docs.conan.io/en/latest/getting_started.html) up to step 6. At which, I got the following error:

```
$ conan install ..

ERROR: Recipe not found: 'zlib/1.2.11@conan/stable'
```

But `conan search` can find the recipe in question:

```
$  conan search 'zlib*'
Existing package recipes:
zlib/1.2.11@conan/stable
```

Although `conan inspect` gives the same error:

```
conan inspect zlib/1.2.11@conan/stable
ERROR: Recipe not found: 'zlib/1.2.11@conan/stable'
```

My gut feeling is that the cache might be somehow corrupted (I may have hit Crtl-C in the middle of the first install attempt). Browsing through the command line options didn't give off a way to clear the cache though.

-------

## Version and configuration

- Conan version 1.14.3
- OS version: Ubuntu 18.04.2 LTS
- Python 3.6.7

### default profile

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

```

-------

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @bl4ck5un 

Yes, it is possible that a Ctrl+C might leave the cache in inconsistent state. Conan has some guards against it, but might not be always possible.

I would try first to remove it:
```bash
$ conan remove "*" -f
```
If you don't want to remove other packages, maybe try ``conan remove "zlib*" -f``.

If that doesn't work, please try removing the cache at ``<userhome>/.conan``. That is a cache, it will recover next time you call conan. The only thing you might need to restore is the ``remotes`` if you have added some, or if you have customized the ``settings.yml`` or ``conan.conf`` files.

Please tell me if this helps, and if everything works, you can tell and close the issue. Thanks!

**Comment by njleon007** [comment]
I find the same issue, when conan install and inspect, I got logs from conan client:

DEBUG :rest_client_common.py[110]: REST: ping: http://192.168.2.21:9300/v1/ping [2021-12-15 14:49:07,672]
DEBUG :rest_client_common.py[136]: REST: get: http://192.168.2.21:9300/v1/conans/opencv/3.4.0/deepglint/stable/download_urls [2021-12-15 14:49:07,677]
DEBUG :rest_client_common.py[38]: REST ERROR: <class 'conans.errors.NotFoundException'> [2021-12-15 14:49:07,680]

**while conan_server logs：**
192.168.2.21 - - [15/Dec/2021:14:49:07 +0800] "GET /v1/ping HTTP/1.1" 200 0 "-" "Conan/1.16.1 (Python 2.7.12) python-requests/2.22.0"
192.168.2.21 - - [15/Dec/2021:14:49:07 +0800] "GET /v1/conans/opencv/3.4.0/deepglint/stable/download_urls HTTP/1.1" 404 49 "-" "Conan/1.16.1 (Python 2.7.12) python-requests/2.22.0"

**get url from website:**
http://192.168.2.21:9300/v1/conans/opencv/3.4.0/deepglint/stable/download_urls
Recipe not found: 'opencv/3.4.0@deepglint/stable'

@memsharded thanks

**Comment by memsharded** [comment]
Sorry @njleon007 this didn't get a response on time, sometimes happen when adding comments on existing issues.
Closing this ticket as inactive, please create new tickets if necessary.
