### ISSUE TITLE
conan test_package travis failure

### ISSUE THREAD

**Issue by theirix** [conan-io/conan#502]
I am trying to build a package http://github.com/theirix/conan-amqpcpp with a travis builder. Configuration is the same as with other conan-jsoncpp, conan-libevent etc except the deprecated `test/` path was changed to the `test_package/`. [Travis build](https://travis-ci.org/theirix/conan-amqpcpp/jobs/162128804) is continuously failed with the error
`ERROR: test folder 'test_package' not available, or it doesn't have a conanfile.py`

It's strange that the manual docker build with almost same command succeeded:
```
docker run --rm -v /tmp/conan-amqpcpp:/home/conan/project -v ~/.conan/data:/home/conan/.conan/data -it -e CONAN_CURRENT_PAGE=1 -e CONAN_TOTAL_PAGES=1 -e CONAN_BUILDER_ENCODED='{"username": "theirix", "builds": [[{"compiler.version": "4.9", "compiler.libcxx": "libstdc++", "arch": "x86", "build_type": "Debug", "compiler": "gcc"}, {"amqpcpp:shared": true}], [{"compiler.version": "4.9", "compiler.libcxx": "libstdc++", "arch": "x86", "build_type": "Release", "compiler": "gcc"}, {"amqpcpp:shared": true}], [{"compiler.version": "4.9", "compiler.libcxx": "libstdc++", "arch": "x86", "build_type": "Debug", "compiler": "gcc"}, {"amqpcpp:shared": false}], [{"compiler.version": "4.9", "compiler.libcxx": "libstdc++", "arch": "x86", "build_type": "Release", "compiler": "gcc"}, {"amqpcpp:shared": false}], [{"compiler.version": "4.9", "compiler.libcxx": "libstdc++", "arch": "x86_64", "build_type": "Debug", "compiler": "gcc"}, {"amqpcpp:shared": true}], [{"compiler.version": "4.9", "compiler.libcxx": "libstdc++", "arch": "x86_64", "build_type": "Release", "compiler": "gcc"}, {"amqpcpp:shared": true}], [{"compiler.version": "4.9", "compiler.libcxx": "libstdc++", "arch": "x86_64", "build_type": "Debug", "compiler": "gcc"}, {"amqpcpp:shared": false}], [{"compiler.version": "4.9", "compiler.libcxx": "libstdc++", "arch": "x86_64", "build_type": "Release", "compiler": "gcc"}, {"amqpcpp:shared": false}]], "args": "", "conan_pip_package": null, "channel": "ci", "docker_image": null}' -e CONAN_USERNAME=theirix -e CONAN_CHANNEL=ci lasote/conangcc49 /bin/sh -c "cd project && sudo pip install conan_package_tools --upgrade && sudo pip install conan --upgrade && conan_json_packager"
```

Seems it can be a problem with changing a current directory during a build execution.

**Comment by memsharded** [comment]
Well, your repo, in the ``dev`` branch (is that the one you are using now, rigth?) doesn't have a ``conanfile.py`` inside, which is what the error message is telling. Check: https://github.com/theirix/conan-amqpcpp/tree/dev/test_package

There must be a ``conanfile.py`` inside. In fact, the ``test_package`` functionality is basically a wrapper around a small project with its own conanfile inside such folder, and it just executes ``install`` & ``build`` and then the possible ``test()`` method in the ``test_package/conanfile.py`` file.

Please check it and tell me. Thanks for your feedback!

**Comment by theirix** [comment]
@memsharded thank you for pointing to the missing file. Somehow `test_package/conanfile.py` appeared in `.gitignore` so it was here locally and for docker builds, `git status` and `git ls-files` doesn't complaint and I didn't even realized it was missing :) Now it builds smoothly. Sorry for the false ararm!

**Comment by memsharded** [comment]
No worries, glad to help :)
Better to report a false alarm, that not reporting a real issue or bug, because of not wanting to bother. Please keep giving feedback!
