### ISSUE TITLE
Client migration misses s390x

### ISSUE THREAD

**Issue by Ignition** [conan-io/conan#5020]
It appears that `conans/client/migrations.py` and `conans/client/conf/__init__.py` are out of sync.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
The settings from `conans/client/migrations.py` correspond to the previous conan version settings, so conan can detect if they have changed and automatically migrate them or not.
