### ISSUE TITLE
Rebuild package with original references when using alias

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#5022]
This is a feature request to improve reproducability of building packages when using aliases.

# Current Situation
I'm having a component `CompA` that requires another component `CompB`, it uses an Alias to always use the latest version: `self.requires('CompB/LATEST@user/channel')`.

# Problem
1. In January I build `CompA/1.0.0@user/channel`, the alias resolves to `CompB/1.0.0@user/channel`.
1. In April both components matured a lot, when I build the newest version I create `CompA/5.0.0@user/channel` with `CompB/5.0.0@user/channel`. This is fine so far.
1. The problem arises when I need to rebuild `CompA/1.0.0`. It will use the alias which will resolve to `CompB/5.0.0`. There are a few cases where a rebuild is necessary (probably more):
    1. The original package got lost somehow. Migrating servers, someone removed the binaries by accident, ...
    1. We're changing/adding the profile that we originally built with (perhaps using a new compiler option or something similar)

# Workaround
Right now this is only solvable by checking what the alias resolved to during the original build, then changing the original requirements. Applying the workaround could be done in different ways:
* Changing the original recipe. Changing the source package, which smells a bit
* Creating local aliases that point to the right versions. This can be cumbersome with complex dependency trees and is a manual step (easy to make mistakes).

# Proposed solution A
I'd suggest adding a new parameter to trigger a rebuild with the already stored information.

It could look like the following:
* `conan install CompA/1.0.0@user/channel --keep-versions`
* `conan install CompA/1.0.0@user/channel --keep-versions -pr gcc8`

# Proposed solution B
Alternatively it could be possible, to automatically create local aliases out of a given reference to recreate a specific build environment. Something like `conan create-environment CompA/1.0.0@user/channel` will create a local alias for `CompB/1.0.0@user/channel`. Within that environment the user could then do `conan install CompA/1.0.0@user/channel` or even other commands like `conan create ...` and similar.

This solution does not change the existing commands and let's the user even do additional things like `conan create`. Could be useful for other usecases where a hotfix `CompA/1.0.1` is created and needs to be rebuilt with the old environment.

There are a few downsides though:
* Extra command necessary, I do not see how this could be integrated with the existing commands
* There are edge cases. What if the local cache already contains another environment?
* It's easy to overlook something for the user, as the process requires multiple steps to be performed in the right order

**Comment by monsdar** [comment]
My favorite is solution A, I added solution B to show that there could be other ways to solve this. For sure there's a better solution out there that I did not think of 🤷‍♂️

**Comment by lasote** [comment]
Hi Nils!
So, to guarantee the reproducibility we propose to use a lock file, @memsharded is working on it. This is in our roadmap but still early to know in which version it will be released. So after an install, you can store your lockfile. The lockfile will contain not the alias but the resolved dependencies (and of course the resolved binary packages). It will work also with the revisions mechanism so you will be able to guarantee the reproducibility. You can repeat the install applying the lock file and rebuilding A.

We think that is the correct approach and we are working hard on it, so we don't think we should workaround it with partial implementations right now.

**Comment by monsdar** [comment]
Lock file is a perfect solution. Consider this a +1 then :D

**Comment by lasote** [comment]
So I'm closing this. Any other think you need, just write! :+1:
