### ISSUE TITLE
Provide environment variables for Meson

### ISSUE THREAD

**Issue by Expander** [conan-io/conan#5031]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

## Background

Dear Conan developers,

I've created a [conan package](https://github.com/conan-hep/conan-tsil) for the [TSIL library](https://www.niu.edu/spmartin/TSIL/). The package uses the `pkg_config` generator in order for the user to be able to use the package with Meson.

## The issue

However, I've stumbled upon an issue when testing the package with travis (): The default travis configuration of [conan-package-tools](https://github.com/conan-io/conan-package-tools) runs the build in docker containers like so:
~~~
sudo -E docker run [...] conanio/gcc8 /bin/sh -c "cd project &&  run_create_in_docker"
~~~
If I understand correctly the command `run_create_in_docker` then runs meson as
~~~
meson src-dir build-dir
~~~
This last command fails with the [error message](https://travis-ci.org/conan-hep/conan-tsil/jobs/524433427#L772)
~~~
sh: 1: meson: not found
~~~
As far as I can see, the problem is that docker does not know the `meson` command and no information about it is transported to docker.

This issue does not arise when using `CMake`. I believe the reason is that the information about the `cmake` command is transported to docker via the environment variable `CONAN_CMAKE_PROGRAM`. If this variable is defined, then it defines the `cmake` command, see [here](https://github.com/conan-io/conan/blob/develop/conans/client/build/cmake.py#L50) and [here](https://github.com/conan-io/conan/blob/develop/conans/client/build/cmake.py#L205). There is no similar mechanism for the `meson` command, though.

## Feature request to solve the issue

To solve this issue I propose to introduce the new environment variables `CONAN_MESON_PROGRAM` and `CONAN_MESON_BACKEND`:

* The `CONAN_MESON_PROGRAM` variable is read in the [Meson class](https://github.com/conan-io/conan/blob/develop/conans/client/build/meson.py). If it is set, the content of the variable is interpreted as the `meson` command, which gets executed. Maybe like so:

      self._meson_program = os.getenv("CONAN_MESON_PROGRAM") or meson_program or "meson"

  Later `self._meson_program` is used to execute `meson`:

      command = '%s "%s" "%s" %s' % (self._meson_program, source_dir, self.build_dir, arg_list)

* The `CONAN_MESON_BACKEND` variable is used to define the meson backend (usually ninja), maybe like this:

      self.backend = os.getenv("CONAN_MESON_BACKEND") or backend or "ninja"

Finally, in a `.travis.yml` script the `CONAN_MESON_PROGRAM` and `CONAN_MESON_BACKEND` variables can be set to `meson` and `ninja`, respectively, to make the meson generator work properly in docker.

Best regards,
Alex

## Backup

In travis conan is installed via
~~~
pip install conan --upgrade
pip install conan_package_tools
~~~
which installs version 1.14.4. I configured travis to run the tests on an Ubuntu Xenial 16.04.

**Comment by jgsogo** [comment]
Hi @Expander! A quick answer before looking into this more deeply: I think that the first problem you are facing is that `meson` is not installed in the docker images (unlike `cmake` which is already installed), install it first and then we can think about what it is happening with variables, flags and so on...

Thanks!

**Comment by Expander** [comment]
Dear @jgsogo,

many thanks for your fast reply! You are of course right, an easy fix would be to install meson and ninja in the docker images.

So far I was using the docker images `conanio/gcc*`, which apparently don't ship with meson/ninja. I'd have to create new docker images then. Or are there images available at conanio which come with meson/ninja?

Best regards
Alex

**Comment by jgsogo** [comment]
No, right now we are not providing `meson` in those images (we probably will), so you have two options:
 * use [`meson_installer`](https://bintray.com/bincrafters/public-conan/meson_installer%3Abincrafters) as a build_require, it's already packaged. You can add it to build_requires in your `build.py` script or use `CONAN_BUILD_REQUIRES` env var, or even add it to your recipe
 * use [`CONAN_PIP_INSTALL`](https://github.com/conan-io/conan-package-tools) variable from conan-package-tools, it will trigger a `pip install meson` inside the docker.

Depending on the use case and the purpose of your package, I could recommend you one way over the other.

**Comment by Expander** [comment]
Dear @jgsogo,

that's perfect, many thanks! I've added
~~~
env:
   global:
     - CONAN_PIP_INSTALL: "meson"
~~~
to `.travis.yml` and now meson gets installed inside docker and is available for build.

Many thanks again and best regards,
Alex

**Comment by jgsogo** [comment]
Thanks, maybe once it is mature, you can consider submitting your recipe to `conan-center` 😉 

I'm closing the issue now, but feel free to open it if you need anything else related to this question.

Thanks again and _Happy Conan_!
