### ISSUE TITLE
call dependency deploy method in conan recipe  

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#5034]
Hello.

I'm using the deploy method to package my project **A** with its dependencies.
Now, I have another project **B** that needs A as a runtime dependencies, for that I need to call the deploy method of project A in the recipe of project B so that I can have A deployed in the build directory of project **B**.

Something like this:
<Build dir of project B>/bin/deploy_of_A

Is there a way to achieve this? 
Thanks.

**Comment by lasote** [comment]
You have to use the `imports()` method for that in "B": https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports

**Comment by memsharded** [comment]
``deploy()`` method has been removed in Conan 2.0, closing this ticket as outdated, thanks for the feedback!
