### ISSUE TITLE
[question] Suggested workflow to call dev tools from CMake

### ISSUE THREAD

**Issue by ltjax** [conan-io/conan#5036]
Hello!
I'm starting to migrate my codebases and have stumbled upon question. What is the recommended workflow to be able to call dev-tools, installed by conan, from within cmake?

I am usually building from within IDEs, i.e. VS with CMake or CLion. Without conan, I am currently executing the protobuf compiler (protoc) from within CMake, i.e. with `FindProtobuf` and the `protobuf_generate_cpp` function. 
I am trying to migrate that to conan (protoc_installer from bincrafters). [The documentation](https://docs.conan.io/en/latest/devtools/create_installer_packages.html?highlight=tools#using-the-tool-packages-in-your-system) hints that the way to use installed tools is to use python venvs, but it does not seem practical to activate from within CMake.
It seems that the parent folder to protoc is exposed via `CONAN_BIN_DIRS_PROTOC_INSTALLER` in `conanbuildinfo.cmake`. The actual executable is referenced in the conanbuildinfo.txt via `PROTOC_BIN`, under the` ENV_protoc_installer` section - but I do not know how to access that via the generator.

I hope this does not sound too confusing - I am just starting out with conan.

**Comment by lasote** [comment]
Well, [this](https://docs.conan.io/en/latest/devtools/create_installer_packages.html?highlight=tools#using-the-tool-packages-in-your-system) are not "python" virtual envs, just regular scripts that set the PATH and other env vars to point to your installer packages.
A recipe automatically inherits these env vars from the requirements, but if you want to run it from the IDE yes, you would need to activate it and then launch the IDE.

For the specific case of `protoc` and the bincrafters recipe, I asked the authors and the recipe is exporting the find modules, here you have an example of usage: https://github.com/bincrafters/conan-protoc_installer/blob/stable/3.6.1/test_package/CMakeLists.txt#L9

**Comment by ltjax** [comment]
Alright, that is a pretty good solution for protoc - thank you!
In the future, I would like to avoid `find_package` if possible, since it makes builds machine dependent  - e.g. builds will execute differently depending on what libraries are installed. Conan, OTH, excels at providing deterministic dependency setups, and the `TARGETS` option to `conan_basic_setup` is already wonderful for that - but only for libraries. It be really cool if there was a guideline or something on how to expose executables in a similar fashion and avoid the brittle find_package mechanism (at least optionally).

**Comment by lasote** [comment]
Thanks for the feedback, we are currently considering to improve the `cppinfo` model, and maybe we want to introduce information about the executables. For the `conan_basic_setup()` approach might be useful to have variables with the exes paths.

**Comment by memsharded** [comment]
Closing this as outdated, as the build system integrations and management of tools_requires have completely changed since then.
Please create new tickets if necessary against Conan 2.X, thanks for the feedback
