### ISSUE TITLE
cmake.test() for shared library on OS X

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#5039]
```python
    def build(self):
        cmake = self._configure_cmake()
        cmake.build()
        cmake.test()
```

Right now test method of a CMake helper does not provide `run_environment` parameter that would allow proper testing of a shared library on OS X. How to run it in such an environment? How to specify a path to a *.dylib library as there is no `imports()` stage before it?

**Comment by lasote** [comment]
You could use it wrapping the `cmake.test()` call:
https://docs.conan.io/en/latest/reference/build_helpers/run_environment.html
Could it work?

**Comment by memsharded** [comment]
Closing this ticket as outdated, there is a whole new environment management and CMake integrations in 1.X and 2.0
