### ISSUE TITLE
Runtime packages and repackaging example does not work

### ISSUE THREAD

**Issue by ebclark2** [conan-io/conan#5045]
conan 1.14.4, ubuntu 18

[conan_repackaging_example_output.txt](https://github.com/conan-io/conan/files/3122630/conan_repackaging_example_output.txt)
[conan_repackaging_hellorun_conanfile.py.txt](https://github.com/conan-io/conan/files/3122631/conan_repackaging_hellorun_conanfile.py.txt)

https://docs.conan.io/en/latest/devtools/running_packages.html#runtime-packages-and-re-packaging

We're using conan for all development and I'm hoping to soon start using it for deploying our application (or at least populating a docker image).  I'm having trouble getting the Runtime packages and re-packaging example to work.  The resulting package does not contain the greet executable.  All other example in this section are working for me as described.  I've attached the output of building both packages (Hello and HelloRun, which I called HelloDeploy), and the HelloRun conanfile.  Any help you can provide would be great.

Thanks!
Ed

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @ebclark2 

Please try with the following: 

```python
from conans import ConanFile

class HelloDeployConan(ConanFile):
    name = "HelloDeploy"
    version = "0.1"
    build_requires = "Hello/0.1@user/testing"
    keep_imports = True

    def imports(self):
        self.copy("*", src="bin", dst="bin")

    def package(self):
        self.copy("*", src="bin", dst="bin")

    def deploy(self):
        self.copy("*", dst="bin", src="bin")
```

Your recipe had a couple of issues:
- You are trying to import: ``self.copy("*.exe", dst="bin")``. That only works to import the "greet.exe" in Windows, but the file is not called like that in Linux. Sorry about that, the docs for this example were written in Windows, it seems.
- You can remove the trailing ";". If you read the output, the linter might warn you.

I have tried with the above changes and it worked, please let me know if this helps. Thanks!

**Comment by memsharded** [comment]
I have updated the docs: https://github.com/conan-io/docs/commit/96be3ecf21b61962688770e964a1443a9bbb2ab8

**Comment by ebclark2** [comment]
Thanks, that cleared things up!

**Comment by ebclark2** [comment]
This deploy business is fantastic btw!  Thanks again!
