### ISSUE TITLE
[Question] It's a bad idea to download Font-Awesome?

### ISSUE THREAD

**Issue by tt4g** [conan-io/conan#5047]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I'm trying to include Font-Awesome in C++ project that already uses conan.
The deliverable of the project is a GUI application, in which use Font-Awesome svg icon.

Font-Awesome also only uses some svg icons in the GUI, so I do not want to manage with git.

If create a new Font-Awesome conanfile.py (only resoruces package) and setting conanfile.txt like the one below, I will be able to include the Font-Awesome icon with the library as part of the release file.

```
[build_requires]
Font-Awesome/5.8.1@user/channel

[imports]
# Copy Font-Awesome icon svg.
., *.svg ->./resources/icons @ folder=True, ignore_case=True
., license* -> ./licenses @ folder=True, ignore_case=True, excludes=*.html *.jpeg
```

I know that `conan` is C/C++ package manager and already exist `npm` Font-Awesome package.
However, `npm` cann't be used, The project members are not familiar with `npm`.

My concern is that the idea of ​​using conan as a means of downloading materials as an alternative to `npm` is a bad idea.

Is this not a recommended use?

Thank you.

**Comment by memsharded** [comment]
Hi @tt4g 

No, it is not a bad idea. We know some users have  been using Conan successfully to manage packages that are not just code/binaries, but other kind of resources: data, images, text files, etc. You probably only need to make sure to manage the ``settings`` correctly (if there is only one resource package for different platforms, then you want to make sure to not use ``settings`` in the package).

Also, not only not a bad idea, but in cases where it is necessary to manage resources that could be different for different platforms, or in different configurations (for different products, for example), it is good idea, as it allows to manage those different configurations in a consistent way, and using the same infrastructure as other packages.

**Comment by tt4g** [comment]
@memsharded Thank you for response.

I felt relieved that my idea was not a big mistake.
I would like to proceed with the development while considering the package management.
