### ISSUE TITLE
Only upload binary package

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan#5048]
I use Jenkins to create conan package from source code and upload conan packages to artifactory. But `conan upload` will upload binary package and export source code. I only want to publish binary package and keep my source code private。Any help you can provide would be great.
![image](https://user-images.githubusercontent.com/14332136/56845208-10837080-68f0-11e9-9336-d82f3cfb5397.png)

Thanks!

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @xyz1001 

There are different ways to avoid uploading the sources to the Artifactory:
- If you put the package conanfile.py recipe in a different repo than the source code, and use the ``source()`` method to define the repo location, then, the source code will not be packaged in the conan package.
- If you want the package conanfile.py recipe in the same repo as the source code, then you are interested in using the [SCM component](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=scm#scm). This will store the "coordinates" of the source code (url, commit), to achieve reproducibility, but will not store the source code in the conan package either. In that case, you should not use the ``export`` feature, read an extended explanation of the cases here: https://docs.conan.io/en/latest/creating_packages/package_repo.html#package-repo


Please tell if this helps.

**Comment by xyz1001** [comment]
The second way is perfect. Thanks for your help.
