### ISSUE TITLE
Quoted defines are not correctly generated in Conan premake

### ISSUE THREAD

**Issue by crazyjul** [conan-io/conan#5050]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.14.4
macOs : 10.14.3

When including libraries or flags containing quote, the generated conanbuildinfo.premake.lua contains invalid data.

For example, if a recipe includes : 
```self.cpp_info.exelinkflags.extend([ '-framework "Chromium Embedded Framework"'])```
the following code is generated : 
```"-framework "Chromium Embedded Framework"" ```

I have a fix located at firefalcom/conan@01dd9849630fd9e8884ea15ff8e9c262514baa0d

It simply escapes the '''"''', generating 
```"-framework \"Chromium Embedded Framework\"" ```

I can make a pull request if the fix is ok for you

**Comment by memsharded** [comment]
Hi @crazyjul 

Yes, please, a PR with those changes would be welcome, as it already has a unittest, it looks good. Thanks for willing to contribute it.

**Comment by crazyjul** [comment]
Thanks for fast response and the great work!!
