### ISSUE TITLE
How to control the number of jobs (-j) when using conan build ..

### ISSUE THREAD

**Issue by nesc1** [conan-io/conan#5054]
How to control the number of jobs (-j) when using conan build .. ?

Thanks

**Comment by uilianries** [comment]
Hi @nesc1 !

You could set `CONAN_CPU_COUNT`, which will represent -j<cpu_count> during the build.

https://docs.conan.io/en/latest/reference/env_vars.html#conan-cpu-count

**Comment by nesc1** [comment]
Thanks for the (very) quick answer @uilianries  :)
