### ISSUE TITLE
Building dependency from source

### ISSUE THREAD

**Issue by rweickelt** [conan-io/conan#5058]
Let's assume I have a libary A that contains a conanfile.py and some other projects that depend on A and also using Conan. So far so good, everything works when I make releases of A and upload them to our internal artifactory server.

But what would the workflow be if a project wants to test a certain commit of A and build A from source? We are doing now the following:
- clone A and build a Conan package with an artificial version number "XXX", store it in the local cache
- modify the consumer project's conanfile to specify version XXX of A
- build the consumer project as normal

Is this how it is supposed to work?

**Comment by uilianries** [comment]
Hi @rweickelt !

Instead of re-creating library A, you could use Editable packages mode:

https://docs.conan.io/en/latest/developing_packages/editable_packages.html

**Comment by rweickelt** [comment]
@uilianries, thanks. I see how that could work. I am not sure if I like this being globally effective though.
