### ISSUE TITLE
Allow to specify system requirements in conanfile.txt

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#506]
At Qt project we use separate conanfile for each configuration, so there is no need to adjust package names. Proposed syntax:

```
[system_requirements]
pkgname1
pkkgname2
...
```

Though if desired it can be extended to more usual case with signle conanfile, possible syntax

```
[system_requirements:linux:ubuntu_12]
...
[system_requirements:linux:ubuntu_14]
...
[system_requirements:linux:ubuntu] # any other version
...
[system_requirements:linux:fedora] # any Fedora
...
[system_requirements:macos]
...
[system_requirements:freebsd]
...
```

**Comment by lasote** [comment]
I think we missed this issue a looooong time ago. Sorry. We really don't want to make the txt more complex, as transform it to a conanfile.py is not that hard. As it had't any feeback or upvotes of the community I'm closing it. Thanks!
