### ISSUE TITLE
pass virtualenv back to API user

### ISSUE THREAD

**Issue by afkews** [conan-io/conan#5060]
I'm using the conan API to install a conanfile and I am trying to retrieve the environment variables that end up in the virtualenv as a result of this call. I can't find a way to do this. I was able to do it only by changing conan API source code and was wondering if there is already a way to do this that I just didn't find.

The reason I need this is I want to do a script that 'installs' to updates some packages that contain binaries and them uses them right after so I need their paths.

**Comment by memsharded** [comment]
Hi @afkews 

That is true, the python API doesn't expose internal models or information, so this is not possible out of the box.

The generators, specifically the ``virtualenv`` family of generators were designed for this goal. Why not directly using them? I usually do in my pythons scripts something like ``os.system("activate.bat && mycommand")`` with those generated files.

**Comment by afkews** [comment]
Hi @memsharded! 

I guess if i do activate before every single command it works.

Thanks very much for the quick reply!

**Comment by memsharded** [comment]
Yes, I usually use a ``run()`` function anyway to abstract away running the commands, that makes it very easy to add stuff (for example, I always prefer launching an exception that failing silently and continuing):

```python
import os

def run(cmd, env=False):
    if env:
        cmd = "activate.bat && %s" % cmd
    ret = os.system(cmd)
    if ret != 0:
        raise Exception("Command failed: %s" % cmd)


run("conan install . -g=virtualenv")
run("mycommand", env=True)
```

Cheers!

**Comment by afkews** [comment]
I actually found a way to do what I initially wanted (somewhat)! Using the 'json' generator the environment is then easily accessible in the conanbuildinfo.json 'deps_env_info' entry, parsing this will then allow me to call subprocess.Popen with the correct 'env' parameter without constantly needing to 'source' the virtualenv.

**Comment by memsharded** [comment]
> I actually found a way to do what I initially wanted (somewhat)! Using the 'json' generator the environment is then easily accessible in the conanbuildinfo.json 'deps_env_info' entry, parsing this will then allow me to call subprocess.Popen with the correct 'env' parameter without constantly needing to 'source' the virtualenv.

I see, that is a valid approach. If you want to go an step further, you might also create your own custom generator that can directly output what you want in the format you want. But yes, I think the ``json`` generator might be good for this use case, thanks for sharing.
