### ISSUE TITLE
[Conan/Bintray] Install/search for a specific package fails

### ISSUE THREAD

**Issue by niosHD** [conan-io/conan#5062]
Conan Version: 1.14.4

I am currently playing around with packaging some python code and have the problem that I can not retrieve packages that I built and uploaded successfully in CI.

An example for such a package can be found [here](https://bintray.com/nioshd/conan/ConanTools%3Anioshd/0.1.1-post3%2Bg9f3b2812c7%3Atesting). I built it with this [Travis Job](https://travis-ci.org/niosHD/ConanTools/builds/525871675) using a freshly installed conan client. As you can see, both the package and the alias where created and uploaded without error and the package can also be inspected via bintray.

However, installing the package on my development machine fails in the following way:
~~~
$ conan install ConanTools/0.1.1-post3+g9f3b2812c7@nioshd/testing -r bintray_nioshd
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7.3
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ConanTools/0.1.1-post3+g9f3b2812c7@nioshd/testing: Retrieving from server 'bintray_nioshd' 
ConanTools/0.1.1-post3+g9f3b2812c7@nioshd/testing: Trying with 'bintray_nioshd'...
ERROR: ConanTools/0.1.1-post3+g9f3b2812c7@nioshd/testing was not found in remote 'bintray_nioshd'
~~~

Searching for the package with `conan search ConanTools/0.1.1-post3+g9f3b2812c7@nioshd/testing -r bintray_nioshd` is even worse and prints an error page in HTML code on the command line.

My best guess is currently that this is a bintray bug that is related to the (kind of exotic) version of the package (i.e., `0.1.1-post3+g9f3b2812c7`). However, to the best of my knowledge, the version is valid according to semantic versioning and is [expected to work with conan](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#version).

Any better idea on what is going on and how to debug this?

**Comment by uilianries** [comment]
Indeed I can reproduce the same error when running Conan 1.14.4

Seems like an error from Bintray, since I can download a package with the same name when running Conan Server.

To debug the error you can set the env var `CONAN_LOGGING_LEVEL=10`:

```
conan install 'ConanTools/0.1.1-post3+g9f3b2812c7@nioshd/testing' -r nioshd
DEBUG :conan_api.py   [203]: INIT: Using config '/home/uilian/.conan/conan.conf' [2019-04-30 11:26:10,774]
DEBUG :tracer.py      [151]: CONAN_API: install_reference(settings=None,options=None,env=None,remote_name=nioshd,verify=None,manifests=None,manifests_interactive=None,build=None,profile_names=None,update=False,generators=None,install_folder=None) [2019-04-30 11:26:10,778]
ConanTools/0.1.1-post3+g9f3b2812c7@nioshd/testing: Retrieving from server 'nioshd' 
ConanTools/0.1.1-post3+g9f3b2812c7@nioshd/testing: Trying with 'nioshd'...
DEBUG :rest_client_common.py[109]: REST: ping: https://api.bintray.com/conan/nioshd/conan/v1/ping [2019-04-30 11:26:10,815]
DEBUG :rest_client_common.py[135]: REST: get: https://api.bintray.com/conan/nioshd/conan/v2/conans/ConanTools/0.1.1-post3+g9f3b2812c7/nioshd/testing/latest [2019-04-30 11:26:11,548]
DEBUG :rest_client_common.py[37]: REST ERROR: <class 'conans.errors.NotFoundException'> [2019-04-30 11:26:11,753]
ERROR: ConanTools/0.1.1-post3+g9f3b2812c7@nioshd/testing was not found in remote 'nioshd'

```

**Comment by niosHD** [comment]
Thank you for confirming the problem and for the tip with `CONAN_LOGGING_LEVEL`, really helpful for these kind of situations.

Are guys that work on Bintray reading this bug tracker or do you know someone that we can tag?

**Comment by uilianries** [comment]
@jgsogo Could you help tagging as Bintray issue?

**Comment by jgsogo** [comment]
I think there is an issue already opened about this, isn't it? ... or I have heard about this same error before...

**Comment by niosHD** [comment]
@jgsogo Indeed, it seems like you reported the same issue in #4677 already and it should be fixed. However, as this issue and #5148 show, something is still wrong.

**Comment by danimtb** [comment]
This bug has been reproduced following the steps in here: https://github.com/conan-io/conan/issues/5148#issuecomment-496858638

It seems that the old issue #4677 has come back.

**Comment by danimtb** [comment]
Bintray team detected this issue as a regression after the implementation of API v2 comming with Conan revisions feature.

They have already deployed the fix to production and the installation and search are working again:

```
$ conan install png++/0.2.9-1@richard-vock/stable

png++/0.2.9-1@richard-vock/stable: Not found in local cache, looking in remotes...
png++/0.2.9-1@richard-vock/stable: Trying with 'hello'...
Downloading conanmanifest.txt
[==================================================] 58B/58B
Downloading conanfile.py
[==================================================] 1.8KB/1.8KB
png++/0.2.9-1@richard-vock/stable: Downloaded recipe revision 0
Installing package: png++/0.2.9-1@richard-vock/stable
Requirements
    png++/0.2.9-1@richard-vock/stable from 'hello' - Downloaded
Packages
    png++/0.2.9-1@richard-vock/stable:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Download

png++/0.2.9-1@richard-vock/stable: Retrieving package 6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 from remote 'hello'
Downloading conanmanifest.txt
[==================================================] 157B/157B
Downloading conaninfo.txt
[==================================================] 438B/438B
Downloading conan_package.tgz
[==================================================] 3.2KB/3.2KB
Decompressing conan_package.tgz: 100%|██████████| 3.16k/3.16k [00:00<00:00, 237kB/s]
png++/0.2.9-1@richard-vock/stable: Package installed 6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
png++/0.2.9-1@richard-vock/stable: Downloaded package revision 0
```
```
$ conan search png++/0.2.9-1@richard-vock/stable -r hello
Existing packages for recipe png++/0.2.9-1@richard-vock/stable:

Existing recipe in remote 'hello':

    Package_ID: 6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 15
            os: Windows
        Outdated from recipe: False
```
