### ISSUE TITLE
Warnings and other checks with symlinks

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5063]
- Compressing `tgz` files should warn if the file is not contained in the package.
- Compressing `tgz` files should convert a symlink to relative (as the file copier does) when a symlink is abs but contained in the package.
- Decompressing should warn when discarding a file: #4966 
- File copier should warn/info for each thing ignored or discarded or converted.

See this branch containing some tests and incomplete/preliminary implementation: https://github.com/lasote/conan/pull/new/feature/warnings_and_tests

**Comment by memsharded** [comment]
Closing together with https://github.com/conan-io/conan/pull/5377#issuecomment-1383742605
