### ISSUE TITLE
Add conan support to Bamboo Artifactory plugin

### ISSUE THREAD

**Issue by wdobbe** [conan-io/conan#5066]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

In Jenkins (with the Jenkins Artifactory plugin installed) you can use Conan functionality. For example in a pipeline script:
```
client = Artifactory.newConanClient()
def b = client.run(command: "install ..")
```
Unfortunately the Bamboo Artifactory plugin doesn't provide similar functionality yet to use Conan in Bamboo build plans.

It would be very nice it this could be implemented. Currently we tried with bash scripts, but because our Artifactory repositories are password protected this requires us to put the password in the build script, which is clearly not a good idea.

Bamboo Artifactory plugin affected: 2.6.2
Conan version 1.14.4 (but not really relevant to this issue)

**Comment by memsharded** [comment]
Hi @wdobbe 

To avoid putting the password in build scripts, you might be interested in using the environment variable instead. Check: https://docs.conan.io/en/latest/reference/env_vars.html#conan-password-conan-password-remote-name and https://docs.conan.io/en/latest/reference/env_vars.html#conan-login-username-conan-login-username-remote-name. These can be set-up in the machine or CI configuration.

About the integration, the plugin has its own repository. Have you already filed an issue in that repo https://github.com/jfrog/bamboo-artifactory-plugin?

**Comment by wdobbe** [comment]
Hi @memsharded ,

Thanks for the tip about the password.

I asked today at the Slack #conan channel whether to create the issue in the conan or Bamboo plugin project and user Ulian Ries advised me to create it in the Conan project (https://cpplang.slack.com/archives/C41CWV9HA/p1556619987160900).

Tomorrow I will create an issue in the bamboo-artifactory-plugin project as well.

**Comment by uilianries** [comment]
> About the integration, the plugin has its own repository. Have you already filed an issue in that repo jfrog/bamboo-artifactory-plugin?

Didn't know about that

**Comment by memsharded** [comment]
Great, thanks, lets follow conversation in https://github.com/jfrog/bamboo-artifactory-plugin/issues/72, as there is little we can do about it in this repository.
