### ISSUE TITLE
conan create: option to specify generator

### ISSUE THREAD

**Issue by e-i-n-s** [conan-io/conan#5076]
I've a question about the ``conan create`` command.

In the ``conan install`` command there is the option ``-g``:
``conan install [-h] [-g GENERATOR] ...``

For the ``conan create`` there's no option for the ``GENERATOR``. Is there a specific reason for the current implementation? I could take over the implementation of this additional parameter in ``conan create``.

The background of my question:
We are using the ``cmake_multi`` generator, which needs two ``conan install`` commands (``Release`` and``Debug``). On our CI system we want to use the conan package tools, which do not support ``*_multi`` generators. In the ``conanfile.py`` the ``cmake_multi`` generator is defined and it would be interesting to have the option to overwrite the generator in the ``conan create`` for the CI system.

Best regards,
Marco

**Comment by memsharded** [comment]
Hi @e-i-n-s 

The rationale is that the ``conan create`` command should work, basically irrespective of the command line options (which are "optional"), so it should never require to specify a generator to correctly build. Note that this approach will always fail if someone tries to consume that package building from sources with ``--build``, as generators aren't apply to all packages in the dependency graph, just to the consumer.

The recommended approach for this case would be:
- Have the ``cmake`` generator to build the package with ``conan create`` correctly, declared in the recipe.
- Consumers will use the ``conan install . -g cmake_multi`` approach.

In any case we are studying how to unify both ``cmake`` and ``cmake_multi`` generators in one, not sure if it will be possible, but that is the goal.

**Comment by Johnnyxy** [comment]
Hi there,
if you use the [CMake build helper](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html) in your recipe then you CAN set the environment variable [CONAN_CMAKE_GENERATOR](https://docs.conan.io/en/latest/reference/env_vars.html#conan-cmake-generator) to influence the CMake build helper. But this should not be used in a productive environment.

As @memsharded stated the recipe should be buildable by itself as you cannot modify its behaviour on transitive builds (build as dependency automatically on some other system).
If you are prebuilding packages with your CI system and you do not intend to make you recipe buildable anywhere else then you could do this with the environment variable.

**Comment by e-i-n-s** [comment]
@Johnnyxy
For the "conan generator" (!= "cmake generator") there's no environment variable (according to the current docs, version 1.14). 

@memsharded thanks a lot for answering my question!

**Comment by Johnnyxy** [comment]
Ouh, sorry I misread that. *shame on me*
