### ISSUE TITLE
OpenSSL broken on Windows

### ISSUE THREAD

**Issue by acgetchell** [conan-io/conan#5077]
OpenSSL broken on Windows:

~~~
C:\Users\appveyor\.conan\data\OpenSSL\1.0.2n\conan\stable\build\14214d5db1813d4f84ab3faaf7d4140f4f8f5c3b
ERROR: OpenSSL/1.0.2n@conan/stable: Error in build() method, line 120
	raise Exception("Unsupported operating system: %s" % self.settings.os)
	Exception: Unsupported operating system: Windows
~~~

Visual Studio 15:
https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/5yyxv5y6q370oo8f#L4828

Visual Studio 17:
https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/lssasvd7rdjg92t1#L4840

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.

Conan 1.14.5, Windows, clang 8.0.0, OpenSSL/1.0.2n@conan/stable

- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

On AppVeyor with:

https://github.com/acgetchell/CDT-plusplus/blob/develop/.appveyor.yml
https://github.com/acgetchell/CDT-plusplus/blob/develop/CMakeLists.txt

**Comment by jgsogo** [comment]
Hi, @acgetchell. Yes, it looks like that recipe is not prepared to build in **Windows** using **clang** (too many combinations 😅 ). The recipe has evolved for new releases of OpenSSL, maybe it works with new ones, have you tried it? or do you need v1.0.2.n?

Anyway I'm moving this issue to [`conan-community/community`](https://github.com/conan-community/community) where we handle issues related to packages, this repo is for Conan development.

Thanks

**Comment by acgetchell** [comment]
Thanks! I posted it here because I initially thought it was a Conan install issue, I then realized it was an OpenSSL issue.

**Comment by jgsogo** [comment]
I cannot move issues across organizations... can you open it there? Thanks

**Comment by acgetchell** [comment]
https://github.com/conan-community/community/issues/188

**Comment by acgetchell** [comment]
I'm not specifying OpenSSL v1.0.2.n, some other package is making that choice.
