### ISSUE TITLE
[Question] Packaging many libraries / recipe cache

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#5081]
Hi,

in our corporate environment we need to provide all dependencies internally, hence we're not reusing any of the bincrafters recipes.
Starting from scratch, we wrote a bunch of recipes for a bunch of libraries, which do of course have dependencies among each other.
We want to host all recipes in one repository, to be able to build all libraries on demand for a given profile.

```
packages
  <library>
    <mayor>.<minor>.<patch>
      conanfile.py
build.py
```

When I want to build everything from scratch (to start out), I have the script `build.py`, that uses the conan API to build packages. I will iterate over all recipes and try to build them piece by piece.
However, the first time I build, the conan cache will be empty. If I try to build `foo` which depends on `bar`, before building `bar`, then conan will error out.

This means I somehow have to create a dependency graph, to define a build order for my packages in build.py.

Is there some way to avoid this? Can I somehow specify other directories for conan to find recipes? All required recipes are in this one repository, but Conan does not know about them.

**Comment by Johnnyxy** [comment]
Hi there,
as I understand you are trying to replicate the functionality of conan.
Conan does build a dependency graph on invocation (e.g. conan install, conan create, ...).
You can output the dependencies for example with [conan info](https://docs.conan.io/en/latest/reference/commands/consumer/info.html#conan-info) or with the still experimental [json output](https://docs.conan.io/en/latest/reference/commands/output/info.html#info-output) functionality.

Dependencies are specified through the ```def requires(self)``` function in the recipe. This way conan already builds everything in the correct order.

What you could do is to [export](https://docs.conan.io/en/latest/reference/commands/creator/export.html#conan-export) all recipes and then issue a ```conan create ... --profile=YOUR_PROFILE_FILE``` on ```foo```.
This way conan does find all recipes in its repository and knows how and when to build required dependencies.

**Comment by KerstinKeller** [comment]
Yes, I am somehow replicating the functionality, though I do not want to.
I tried with `export` but I am running into the same problem. The first few recipes cannot get exported, because they have unresolved dependencies.

`Package mypackage/0.2.2 had unresolved dependencies`

What I *could* possibly do, is to iterate over the recipes over and over, trying to export them, until all of them are eventually exported.
Only afterwards can I start trying and build the packages. But that somehow seems wrong.

What would be convenient, if I could query all dependencies of a package even though they are not yet resolved, and this way build up a tree to invoke `cpm.export` and `cpm.create` in the correct order.

I wonder if my approach (trying to build everything from scratch) is even valid, or if I *should* add some logic / build all packages separately.

**Comment by Johnnyxy** [comment]
This is odd.
I just tried to export a recipe that ```requires``` and ```build_requires``` another recipe which is not available at export time and everything went fine (for the export; no building at this time).

Conan 1.14.5
[test.zip](https://github.com/conan-io/conan/files/3138939/test.zip)

Recipe BBB depends on recipe AAA. And I can export recipe BBB without recipe AAA being exported at all.

1. Recipe BBB export
```conan export D:\tmp\b\conanfile.py test/test```

2. Recipe AAA export
```conan export D:\tmp\a\conanfile.py test/test```

What command did you issue to export the recipe?

**Comment by KerstinKeller** [comment]
Hmhm Ok, it works as you suggested, and it also works using the python API
```
from conans.client.conan_api import ConanAPIV1 as ConanAPI

cpm, _, _ = ConanAPI.factory()
cpm.export('./b', name='bbb', version='0.1.0', user='test', channel='test')
cpm.export('./a', name='aaa', version='0.1.0', user='test', channel='test')
```

BUT the difference is, I do have a `python_requires` in my recipes.
If I modify the `bbb` package:

```
from conans import ConanFile, python_requires

python_requires(f'aaa/0.1@test/test')

class bbbConan(ConanFile):
    name            = "bbb"
    version         = "0.1.0"
    settings        = "os", "arch", "build_type", "compiler", "os_build", "arch_build"

    def requirements(self):
        self.requires(f'aaa/0.1.0@test/test')

    def build_requirements(self):
        self.build_requires(f'aaa/0.1.0@test/test')
```
it does throw the exception and does not export anything. But I guess that could be expected, because it (potentially) cannot parse the rest of the recipe?

(And one more question: using the python API, can conan somehow deduce the `name` and `version` parameters from the recipe when calling `cpm.export`?)

**Comment by KerstinKeller** [comment]
> (And one more question: using the python API, can conan somehow deduce the name and version parameters from the recipe when calling cpm.export?)

Ok, I seem to have figured that one out:
```
from conans.client.conan_api import ConanAPIV1 as ConanAPI

cpm, _, _ = ConanAPI.factory()

for package in ['./b', './a']:
  info = cpm.inspect(package, None)
  cpm.export(package, info['name'], info['version'], user='test', channel='test')
```

**Comment by Johnnyxy** [comment]
Sorry for the late answer,
yes, if you have a ```python_requires``` then the requested package have to be found in the repository.

But with your API approach it should work. But then you have to know the build order by yourself in the first place.

**Comment by lasote** [comment]
Hi! I wouldn't recommend using the python API because it is not documented, so it is not stable and can change at any moment. You are right about the `python_requires`, they are needed to export a recipe to the local cache. So you will have them somehow "hardcoded" in the script to export them first.
You can do all without using the conan python API, with the `conan export` you can export all the recipes and then you can call in a consumer project `conan info . --build-order aaa/0.1@test/test --json /path/to.json` being "aaa" package the one being modified and it will tell you the packages affected in the graph, so you will need to rebuild them in the order specified at the json file. https://docs.conan.io/en/latest/reference/commands/consumer/info.html

**Comment by Johnnyxy** [comment]
@lasote 
Yes the export of all recipes as first step was my advice too. But if any recipe needs another recipe through ```python_requires``` then "random-order-export" will not work as one has to export them at least in the build order of the ```python_requires``` dependencies.

**Comment by KerstinKeller** [comment]
Thanks for the help.
I will hardcode to build the Python recipe first, and then export / build the others as you suggested.

I noticed that there is no documentation on the Python API, so I figured it might not be stable.
However, are you planning on making it available for the future?
I do not know how others feel, but since I need to script the package creation anyways, i'd much rather do it in Python, than some bash logic.

**Comment by Johnnyxy** [comment]
You could still do it in Python. 
From there you can just execute plain command line Conan commands.
For that you could use the module "subprocess"  (Python 3+).

E.g.
- Python >=3.5: subprocess.run ([see here](https://docs.python.org/3/library/subprocess.html))
    ```python
        for subfolder in subfolders: # use some path walking/order logic
            subprocess.run('conan export "' + str(subfolder) + '" ...')
        subprocess.run('conan build ...')
    ```
- Python <3.5: subprocess.call ([see here](https://docs.python.org/3/library/subprocess.html#older-high-level-api))
- Python 2.7: os.system ([see here](https://docs.python.org/2.7/library/os.html#os.system))

**Comment by AbrilRBS** [comment]
Closing in Conan 2, where the Python API will (slowly) be documented and public to use for cases like these, where an export is needed before being able to run other commands.

Note that we have some custom command examples of API usage in https://github.com/conan-io/conan-extensions/blob/main/extensions/commands/cci/cmd_export_all_versions.py that users might find useful as a starting point
