### ISSUE TITLE
[question] Always deploy build_requires package?

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#5082]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
```
Conan version 1.14.3
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

Hi there, we are looking at adding conan support for our embedded toolchain.

We are looking to pull in the toolchain as a `build_requires` for our profiles that specifically are for cross compiling.

One of the special things about this toolchain is it needs to actually run an install script. (It has hardcoded absolute paths, fun)

We thought we could use the `deploy()` step to install the toolchain, but this only works on explicit install of that conan package. (`conan install Toolchain`)

We we're wondering if we can ALWAYS deploy a package.

Otherwise it's not very useful to have it as a build_requires() as the user would still have to call `conan install Toolchain`

We've played around with detecting the package as a `build_requires` in `build_requirements()` and calling the install explicitly and automatically, so it's deployed. However, we are unsure how to get the current list of `build_requires`, to grab the exact package name/version to `conan install Toolchain`.

So to reiterate:
1. Can we have a package always deploy
2. If not, can we get the package names of `build_requires` from within the conanfile.py so we can explicitly call `conan install X` as part of the build process, forcing a deploy.

**Comment by Johnnyxy** [comment]
hi there,
you could try to call conan directly from python. The conan api is accessible through python too. This means you could issue a deploy command from there. But this should be backed by some conan specialists :).

If you can modify the paths in the toolchain file you could try the following steps.

provide the toolchainfile
--------------------------
You can provide the toolchain file with your recipe/package. Have a look [here](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#exports) and [here](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#exports-sources).

retrieving the toolchainfile as conan package
----------------------------
1. create a conan package that contains your toolchain file (e.g. export, export_sources)
2. the package [user_info](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=user_info#user-info) should contain the name of the toolchainfile
```python
def package_info(self):
    self.user_info.toolchainfilename = "ACTUAL_TOOLCHAIN_FILENAME"
```
3. build_require this package in your lib/app recipe
4. in the ```def build(self)``` function you can access the toolchain by concatenating the package root_path with the toolchainfile
```python
def build(self):
    ...
    toolchainfile = os.path.join(self.dep_cpp_info["TOOLCHAINFILE_PKG_NAME"].root_path, self.deps_user_info["TOOLCHAINFILE_PKG_NAME"].toolchainfilename)
    ...
    # do something with this toolchain file
```

hardcoded paths
------------------------------
You say you have hardcoded paths in this toolchainfile. If they are not to complicated constructed you can modify those paths before using the toolchainfile. Have a look [here](https://docs.conan.io/en/latest/reference/tools.html#tools-replace-in-file) and [here](https://docs.conan.io/en/latest/reference/tools.html#tools-replace-path-in-file). Or just use plain python I/O commands.

In toolchain recipe:
```python
def build(self):
    tools.replace_path_in_file("toolchainfile.cmake", "the _bad_hardcoded_path", "new_fancy_path", ...)

def package(self):
    self.copy("*")
```


Can you elaborate a little bit more where those install script is located? Is it always the same path? Is it under a only-admin-access-path?

**Comment by danimtb** [comment]
Related to #5059

**Comment by Andre-Heil-Bose** [comment]
Just to provide an update on how we ended up tackling this problem; we are using a custom hook like so:

```python
def post_download_package(output, conanfile_path, reference, package_id, remote, **kwargs):

    # Toolchain deploy
    if reference.name == "Toolchain":
        # Install toolchain

```

So now we have a way to run something every time the toolchain is downloaded, which covers our use case. We realize that this is run for every single package that is downloaded, but will only run if the package that is downloaded is the "Toolchain" itself.

Of course this doesn't work if the "Toolchain" is being built rather than downloaded, but for our purposes, there's only a very small subset of people who actually need to build the toolchain.

Thanks @Johnnyxy for the suggestions, but we weren't able to change the hardcoded paths at build time because the new path is not known at build time. The new path is dependent on the computer that is actually pulling down the toolchain.

Will be closing this case now :smile:
