### ISSUE TITLE
Pipenv Generator

### ISSUE THREAD

**Issue by MBetters** [conan-io/conan#5084]
Hello, I'd like to use [pipenv](https://pipenv.readthedocs.io/en/latest/install/) as a generator [like this](https://docs.conan.io/en/latest/devtools/create_installer_packages.html#using-the-tool-packages-in-your-system), so that instead of...
```
[requires]
mingw_installer/1.0@conan/stable
cmake_installer/3.10.0@conan/stable

[generators]
virtualenv
```

... I could do this...
```
[requires]
mingw_installer/1.0@conan/stable
cmake_installer/3.10.0@conan/stable

[generators]
pipenv
```

Conan version: 1.14.4
OS: Ubuntu 16.04

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I would love to know which benefits it brings compared with the current `virtualenv`.
