### ISSUE TITLE
CMakeSettings.yml visual integration

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5089]
Look at:

https://www.reddit.com/r/cpp/comments/bjxtje/handling_debug_path_with_conan_cmake_visual/

It might be useful to consider a generator for that json? Investigate the usage of the json, also with vcpkg.

**Comment by ohanar** [comment]
I'm from the same company as the OP on the reddit post (@gusmd), for now we decided to add the following to our conanfile.py:
```py
def imports(self):
    for _, dep in self.deps_cpp_info.dependencies:
        for dll in glob.iglob(os.path.join(dep.rootpath, "**", "*.dll"), recursive=True):
           dst = os.path.join(self.build_folder, os.path.relpath(dll, dep.rootpath))
           os.makedirs(os.path.dirname(dst), exist_ok=True)
           if not os.path.exists(dst):
               # os.symlink doesn't respect developer mode until 3.8
               self.run(f'mklink "{dst}" "{dll}"')
```
Fundamentally our issue is that we have gigabytes of dlls that are prohibitively expensive to copy using `self.copy` inside of `imports`, which is why we have been developing by using modified environment variables. Having an extra keyword argument to `self.copy` that would symlink files instead of copying them would be a great alternative for us as well.

**Comment by lasote** [comment]
Thanks for the feedback! Sounds like a totally legit use case. I'll open a new issue for that.

**Comment by SSE4** [comment]
official doc: https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2019

**Comment by danimtb** [comment]
Having a look at this issue and playing with Visual Studio and CMake, I fail to see what @ohanar refers to when saying ``{ "conan_path": "C:\\path\\to\\my\\libs\\release" }``

Is this path talking about the location of the binary directories of all the dependencies for that project? Or just the libraries that consumer project is creating?

I guess you were talking about the first one.

-------

On the other hand, I find the usage of cmake-conan quite smooth with Visual Studio, however, there is still the well-known issue of locating the shared libraries when trying to debug or at least run the application.

While the visual studio plugin (`visual_studio` & `visual_studio_multi` generators) are injecting thoes paths via props files as automatically as described manually in here (https://stackoverflow.com/questions/2119539/how-do-i-set-the-path-to-a-dll-file-in-visual-studio)

To solve this issue for cmake, we could try the approach described in Reddit setting this if possible `set_target_properties(hello_world PROPERTIES VS_DEBUGGER_ENVIRONMENT"PATH=%PATH%;$<$<CONFIG:DEBUG>:${CONAN_BIN_DIRS_DEBUG}>; $<$<CONFIG:RELEASE>:${CONAN_BIN_DIRS_RELEASE}>")`

However, that `VS_DEBUGGER_ENVIRONMENT` only works with CMake's Visual Studio generators and not with `Ninja` which is the default generator Visual Studio IDE chooses when setting up a "pure CMake" based project

**Comment by ohanar** [comment]
The `VS_DEBUGGER_ENVIRONMENT` property will only work on quite recent versions of cmake (although there is no harm setting it on old versions of cmake, it just won't do anything). Moreover, it isn't really something that you can inject into downstream targets, so really the author of a given library has to do it manually, and I don't really think there is anything that conan can do here to automate it, other than document an example.

We are using Visual Studio in its CMake mode, and using the Ninja generator most of the time. Even if you used Visual Studio project files and set `VS_DEBUGGER_ENVIRONMENT`, Visual Studio does not read that field when launching the debugger while in CMake mode. The only real way to control the debugger environment is via `launch.vs.json`, which unfortunately exists in the source tree, and isn't configuration specific.

As I have mentioned, We are using symlinks to handle this for now, and that has worked reasonably well. The more up to date version of the code:
```python
def imports(self):
    symlinks = ((os.normpath(src), os.normpath(os.path.join(self.imports_folder, os.path.relpath(src, dep.rootpath))))
        for _, dep in self.deps_cpp_info.dependencies
        for src in glob.iglob(os.path.join(dep.rootpath, "**", "*.dll"), recursive=True)
    )

    cmd = ""
    for src, dst in symlinks:
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        if os.path.exists(dst):
            if os.path.samefile(src, dst):
                continue
            os.unlink(dst)
        if cmd:
            cmd += " && "
        cmd += 'mklink "{}" "{}"'.format(dst, src)
    if cmd:
        self.run(cmd)
```

**Comment by danimtb** [comment]
Thanks a lot for the feedback and insight about your approach @ohanar. I think it makes a lot of sense.

Continuing with the *CMakeSettings.yaml* file and the approach described in the Reddit post, I was wondering if you would find useful to have a generator inf Conan for that file. The generator will provide information on different directories as environment variables.

In that way, I think it could help to solve the issue with shared libraries for the execution of the application and will make the integration with Visual Studio CMake more smooth.

Are you using the *CMakeSettings.yaml* file? If so, do you know if that file is usually commited to the source code repo? Thanks!

**Comment by ohanar** [comment]
I don't think I would find it particularly useful to have a generated CMakeSettings.json file. Fundamentally, CMakeSettings.json is just encoding the environment and options that are passed to cmake when you configure (and to a lesser extent, when you build or install).

We are using the CMakeSettings.json, and it generally is not commited to the code repository, however, it is designed to be where a developer sets up their own individual cmake configurations. We do have sample copies of CMakeSettings.json committed into our repository, as a baseline for getting up and running for developing a given package.

For instance, not everyone on my team develops every package, so we use conan's editable mode. To control whether to consume a package in editable mode or not, we use options specified CMakeSettings.json, and since each developer is working on a different set of packages, each developer has their own customizations to CMakeSettings.json.

**Comment by danimtb** [comment]
Great, thanks a lot for the valuable feedback. I guess from your comments that you are actually managing everything well with the imports() using the symlinks, right?

Anyway, I will discuss for the team this topic a little bit further as I see value on having the binary paths set by a generator (without interfering to any configuration already set up)  to a *CMakeSettings.json* file.

Thanks!

**Comment by danimtb** [comment]
We have decided to stop this investigation as there is still room for improvement in the toolchain approach for generator. Also, we would have to consider this from the visual studio plugin perspective...

**Comment by memsharded** [comment]
The new ``CMakeToolchain`` integration is now generating ``CMakePresets.json`` files, which seem to be a more broad and accepted integration. Closing as not planned, it seems the integration with VS IDE is not following this path.
