### ISSUE TITLE
Plan generators changes for #5090

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5091]
Go over the generators and study how they should respond to the changes to be introduced at #5090.

Examples:

- `cmake`: Create variables for the exes (finding them in the paths (which?))
- `cmake`: Use the "intra" model of dependencies to better adjust the library orders both in global and targets approach, using system deps also.
- `cmake`: Create also targets for the subcomponents. 
- `cmake`: Create alias with the declared names in addition to "CONAN_PKG::"?
- `cmake_find_package_multi`: Targets with intra-dependencies models, names of components, names of targets, names of config files.
-  `cmake_find_package_multi`: Implement a smart response to the COMPONENTS argument?

**Comment by lasote** [comment]
Once the modifications are clear, create N issues with concrete features (this is a look into)

**Comment by lasote** [comment]
This will be part of the planification of 1.17.

**Comment by lasote** [comment]
None has been done in 1.17. It would need to wait for 1.18 to be planned.

**Comment by SSE4** [comment]
`pkg-config` - generate multiple pc files for each subcomponent

**Comment by lasote** [comment]
As #5090 has been postponed for technical reasons, I remove this from the milestone.
