### ISSUE TITLE
Failed installation due to PyYAML

### ISSUE THREAD

**Issue by sursu** [conan-io/conan#5094]
I have Ubuntu 18.04.
I have Anaconda 2019.03.

I used to have conan, but I experienced some issues after an uninspired deletion of the `.local` folder.

I have decided to install it again. However, after I run

`pip install conan`

I get the following error (last few lines):

```
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /opt/anaconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.7.0->conan) (1.24.1)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/anaconda3/lib/python3.7/site-packages (from packaging->deprecation<2.1,>=2.0->conan) (2.3.1)
Installing collected packages: PyYAML, conan, typed-ast
  Found existing installation: PyYAML 5.1
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
A similar issue is [Python 3.7 installation fails due to PyYAML 3.12](https://github.com/conan-io/conan/issues/3249), but I don't see a solution there.

What would you advise me to do?

---

**UPDATE**:

I tried to run:

`pip install conan --ignore-installed PyYAML`

And one of the errors I get there clarifies the issue for me:

`ERROR: conan 1.14.5 has requirement PyYAML<3.14.0,>=3.11, but you'll have pyyaml 5.1 which is incompatible.`

Still, what can I do?

---

OK, I've just run:

`/usr/bin/pip install conan`

to use the default python-pip rather the anaconda one and it seems that everything went alright.

**Comment by memsharded** [comment]
Hi @sursu 

In Conan 1.15 (will be released this week), we have raised the PyYaml restriction and from now it will be:
```
PyYAML>=3.11, <6.0
```
We hope that such minimizes the incompatibilities. 

As you could solve the issue above, and it was an incompatibility with a previously existing environment, I think it is better to leave it as-is, please let me know, thanks!

**Comment by sursu** [comment]
Everything is fine here. I just left it open for you to read and be aware of the issue.

Closing now.

**Comment by memsharded** [comment]
Cool, thanks!

**Comment by Monsieurvishal** [comment]
I use windows 10
active environment : base
    active env location : C:\Users\Vishal\Anaconda3\New
            shell level : 1
       user config file : C:\Users\Vishal\.condarc
 populated config files : C:\Users\Vishal\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=9.2
       base environment : C:\Users\Vishal\Anaconda3\New  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Vishal\Anaconda3\New\pkgs
                          C:\Users\Vishal\.conda\pkgs
                          C:\Users\Vishal\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Vishal\Anaconda3\New\envs
                          C:\Users\Vishal\.conda\envs
                          C:\Users\Vishal\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

ERROR:::::::
Installing collected packages: PyYAML
  Found existing installation: PyYAML 5.1.1
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by memsharded** [comment]
@Monsieurvishal which version of Conan are you installing and how?

**Comment by ZERO-KAMAL** [comment]
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
does anyone here to solve this problem . i'"m stuck at this point.

**Comment by ZERO-KAMAL** [comment]
conda remove PyYAML 
THis is the answer
