### ISSUE TITLE
Imports(): Copy function creating symlinks

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5098]
Read here: https://github.com/conan-io/conan/issues/5089#issuecomment-489156377
The `copy` function could have a new argument to only create symlinks, while it is clearly no-sense for the package copy, for the imports have sense, because sometimes you only want the `DLLs` available in the same dir, but not copying them all.

**Comment by memsharded** [comment]
Closing (check https://github.com/conan-io/conan/pull/5352)
