### ISSUE TITLE
Setting "UsesSemVer" to indicate that the package is using semantic versioning

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#510]
This in in preparation to #15, but can also be useful on its own.

The idea is to have a package option called UsesSemVer (or something similar) that indicates that the version number follows semantic versioning. This in itself is good to know - you can trust the package that a new patch-version will probably not break any interfaces of yours.

This will also be useful when some kind of advanced versioning mechanism like `1.*.*` is implemented - This mechanism only works with SemVer.

I thought about an approach that uses a regex or something similar to see if the version is in the correct format, but this does not indicate SemVer. I can always create a version string like 1.0.1 and break interfaces when increasing the latest version part. By setting this value explicitly to True I indicate that SemVer is used and I as a package author probably understand what SemVer is.

I would suggest that the default value for this is False.

I also would suggest to allow custom format after the first 3 version parts. This way it would be possible to have something like `1.0.0.abcdef` where a VCS hash/revision is attached.

```
class PocoTimerConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    requires = "Poco/1.7.3@lasote/stable" # comma separated list of requirements
    generators = "cmake", "gcc", "txt"
    default_options = "Poco:shared=True", "OpenSSL:shared=True"
    version = "1.0.0"
    usesSemVer = True
```

**Comment by memsharded** [comment]
I think support for this has improved over time, with version-ranges, improvements in the ``Version`` class, etc., and this might not be necessary, unless until an automated usage of such value is really demanded. So closing it by now, thanks!
