### ISSUE TITLE
[BUG] Conan Tools does not export detected_os

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5101]
To help us debug your issue please explain:

When I was updating cmake_installer, I just found that `detected_os` is not exported by conans.tools

Conan Version 1.15.0

```python
from conans import tools

if __name__ == "__main__":
	tools.detected_os()
```

**ERROR**: 
```
Traceback (most recent call last):
  File "conanfile.py", line 4, in <module>
    tools.detected_os()
AttributeError: module 'conans.tools' has no attribute 'detected_os'
```

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi!

I am missing something here. This is an internally, undocumented tool, I haven't found it in the docs. Why would it be a bug?

**Comment by uilianries** [comment]
maybe because `detected_architecture` is public. But, as you said it's internal, I would this issue should be moved to [feature request].

What is the real usage for this? When we need to detect the correct OS for Conan Package Tools, when creating the build list:

https://github.com/conan-community/conan-cmake-installer/blob/a3d3e089fcaa39fe75ccfeb3115b516f3783bcde/build.py#L24

As Conan uses names like "MacOS", `detected_os` is much better.

**Comment by SSE4** [comment]
yeah, please export this, otherwise we have to duplicate logic in recipes. it should be consistent with `detected_architecture`
