### ISSUE TITLE
Conan remote update command error in 1.15

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#5107]
With the Conan 1.15 release it is no longer possible to use the `conan remote update` command to ensure an existing remote is configured to be at the specified index. Reverting to Conan 1.14 sees the command work as expected.

    conan remote update ci-conan https://my-artifactory-instance.com/artifactory/api/conan/ci-conan --insert=0 
    ERROR: Remote 'ci-conan' already exists with same URL

**Comment by memsharded** [comment]
Reproduced, indeed a small regression. This case of update with the same URL and --insert was not properly covered. Will be fixed by #5110 and released soon in Conan 1.15.1

**Comment by memsharded** [comment]
Fixed by #5110
