### ISSUE TITLE
Conan install on linux fails to run

### ISSUE THREAD

**Issue by dragon512** [conan-io/conan#5108]
This might be related #5104. I am not sure at this moment. I was making a new setup and was installing cmake.

Steps I did in docker container running ubuntu ( with python installed)

```
rest# pipenv install conan --three
Creating a virtualenv for this project…
...
/test1# pipenv shell
(test1) /test1#

(test1) /test1# conan install cmake_installer/3.14.1@conan/stable -g virtualenv
Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)
Found gcc 7
gcc>=5, using the major as version

...
Default settings
        os=Linux
        os_build=Linux
        arch=x86_64
        arch_build=x86_64
        compiler=gcc
        compiler.version=7
        compiler.libcxx=libstdc++
        build_type=Release
*** You can change them in /root/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

cmake_installer/3.14.1@conan/stable: Not found in local cache, looking in remotes...
cmake_installer/3.14.1@conan/stable: Trying with 'conan-center'...
...
cmake_installer/3.14.1@conan/stable: Package installed be241241e9d4718e5bab4eb33935bbb69606bb0c
cmake_installer/3.14.1@conan/stable: Downloaded package revision 0
Generator txt created conanbuildinfo.txt
Generator virtualenv created activate.sh
Generator virtualenv created deactivate.sh

(test1) /test1# . activate.sh
(conanenv) (test1) /test1# cmake
bash: /root/.conan/data/cmake_installer/3.14.1/conan/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin/cmake: No such file or directory
```

This was working a two week ago when I ran the same commands. I am not sure what changed since I last ran this command

however 
```
ls /root/.conan/data/cmake_installer/3.14.1/conan/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin/ -al
total 50040
drwxr-xr-x 2 root root     4096 May  7 02:26 .
drwxr-xr-x 6 root root     4096 May  7 02:26 ..
-rwxr-xr-x 1 root root 11869800 May  7 02:26 ccmake
-rwxr-xr-x 1 root root 12752700 May  7 02:26 cmake
-rwxr-xr-x 1 root root 12821172 May  7 02:26 cpack
-rwxr-xr-x 1 root root 13780224 May  7 02:26 ctest
```

If I do this same logic on centos7 I get this error message:
`bash: /root/.conan/data/cmake_installer/3.13.0/conan/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin/cmake: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory`

**Comment by dragon512** [comment]
Just adding to the notes here... 

found an older VM I had with everything running. it had Conan 1.12 on it.

Made a backup of the working data I had downloaded. I then reinstalled it with that version of Conan. I found the layout is different on install with the same command, and that the binaries are different sizes.

The working copy was under:
.conan/stable/build/44fcf6b9a7fb86b2586303e3db40189d3b511830/cmake-3.13.0-Linux-x86_64/bin

and was ~11.7MB

The new one that was installed was the same as the above cases which have started with be2412 and is ~16MB in size. GIven this seem to be independent of Conan 1.15 or 1.12 is this something that would be on public Conan repo? or is there some odd configuration issues going on causing a bad package to be pulled?

**Comment by memsharded** [comment]
Hi @dragon512 

I think this is mostly related to some issues in the ``cmake_installer`` package recipe, please check https://github.com/conan-community/conan-cmake-installer/pull/21.

Could you please check with other packages? If everything works and is only the cmake-installer package, this issue could be closed here and follow discussion in the other repo (I will move the issue there).

**Comment by dragon512** [comment]
Thanks for the update. I think I might have a fundamental misunderstanding about something in conan. If I understand correctly the issue here is that the recipe change in conan/stable vs something as conan/test. because of this previous working packages had been replaced with bad packages. Is there any notion of a package release? so I could refer to an older version. or pin to a known entry that had worked.

Is there a way one can in conan for example point to a recipe in the git history and have that build locally? ideally with a set of simple commands vs making a conan.txt file

**Comment by memsharded** [comment]
Hi @dragon512 

That was a previous limitation of Conan, before package revisions. Now, every recipe changes produces an internal automatic version (the content hash), that avoid overwriting packages in the servers, even if they have exactly the same version, user and channel. It is possible later, to pin an exact revision, specifying it as ``pkg/version@user/channel:revision``. Unfortunately, Bintray packages haven't started to use revisions yet, so that won't be possible. Artifactory and conan_server already support package revisions, and we are working on making sure that the packages in Bintray are inmutable.

In this case, it seems that some update to the cmake_installer recipe indeed created and overwrote the packages. Some contributors are working on that recipe and packages, will be fixed as soon as possible.

**Comment by dragon512** [comment]
@memsharded I think this is an issue the recipe. if I add --build cmake_installer to my install command the resulting cmake works as expected.

I am unclear on a fundamental part of the problem here. As I understand it, Conan should be making a has based on the OS.... so binaries built wit Ubuntu should have a different has than those build with with Fedora or RHEL 7. From what I think was happening the has was based on the OS value of LINUX. I noticed I was getting the same hash on the install for Ubuntu or centos. I would have thought these values should have been different as the binaries build on Ubuntu vs centos should not be ABI compatible by default. Given the change in the recipe I am unclear on how those changes broke anything. It looks like a change in where the bit had been compiled that was the real issue that broke the cmake_installer

When for example I add the --build I get this for cmake that works:
`[root@ecf464e7678f build.our]# ls /root/.conan/data/cmake_installer/3.13.0/conan/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin/cmake -al
-rwxr-xr-x 1 root root 11654264 Nov 20 15:01 /root/.conan/data/cmake_installer/3.13.0/conan/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin/cmake`

however when I look at the case where it breaks I have the same hash and a binary that does not work:
`[root@ecf464e7678f build.our]# ls /root/.conan/data/cmake_installer/3.13.0/conan/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin/cmake -al
-rwxr-xr-x 1 root root 16028472 May  7 15:21 /root/.conan/data/cmake_installer/3.13.0/conan/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin/cmake`

I had expected Conan to deal with this part, however it seems to assume LINUX is the same

This suggests that Conan is broken here as it made different outputs but assumed that they are the same? Am I incorrect in the conclusion? Or is this the fault of the recipe for being to liberal on the platform requirements for the dependency hash

**Comment by memsharded** [comment]
> I am unclear on a fundamental part of the problem here. As I understand it, Conan should be making a has based on the OS.... so binaries built wit Ubuntu should have a different has than those build with with Fedora or RHEL 7. 

No, this is not the case for the OSS packages and the default settings, as it would be intractable to create all those binaries. Instead, only the more "mainstream" configurations are generated, which works well for a large number of users, but the distro is not taken into account in the package binary ID as default (conan-center).

Conan totally has the capability of doing so, you can read more about it here: https://docs.conan.io/en/latest/extending/custom_settings.html

**Comment by dragon512** [comment]
@memsharded Thanks for the clarification. This is then a recipe issues and what is done by default on the opensource conan bintray.

I am closing this issue as I am not blocked, and I believe this explains the runtime issues people may see when using this repo to get "binary" package for a build from this repo. 

Thanks again for you quick and informative response!

**Comment by memsharded** [comment]
Thanks to you for your understanding and all the feedback!
