### ISSUE TITLE
Ignore change of patch version

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan#5109]
I have A package, which depend B/1.0 package. B/1.0 is alias to thre lastest B/1.0.x. When B update version form 1.0.0 to 1.0.1, the package ID of A will changed. How to ignore the change of the patch version of dependency? Any help you can provide would be great.

Thanks

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @xyz1001 

Could you please make sure that the package ID of A is really changing? By default, Conan uses the "semver" compatibility, so what is hashed into the package ID of A will be ``B/1.X``, so the patches should never affect. Do you have a reproducible case, or could you try to define it? Many thanks!

**Comment by xyz1001** [comment]
I am sorry for my carelessness. Actually, I added another dependency for B when I update B/1.0 to B/1.1, which cause package ID changed. Thank for your reply.

**Comment by memsharded** [comment]
Hi @xyz1001 

No problem! Glad that you found the issue and solved it. Do not hesitate to create new issues for further questions, happy to help. Cheers.
