### ISSUE TITLE
Undocumented tools

### ISSUE THREAD

**Issue by mnowy** [conan-io/conan#511]
There is a lot of tools in https://github.com/conan-io/conan/blob/develop/conans/tools.py but I can't find any documentation for them. I.e. vcvars_command is nice tool to set up VS environment. Unfortunately to find out about that tool I had to dig to the edges of internet :)

Is it possible to add some documentation that tools like this even exists inside of conan?

**Comment by memsharded** [comment]
Transferred to docs repo: https://github.com/conan-io/docs/issues/75
