### ISSUE TITLE
Missing 8.3 version of gcc

### ISSUE THREAD

**Issue by dfleury2** [conan-io/conan#5111]
Hi,
[conan 1.15.0]
is this possible to add the 8.3 version of gcc into the default settings.yml generated ?

Regards,

**Comment by memsharded** [comment]
Sure, lets add it: https://github.com/conan-io/conan/pull/5112. Will be in next 1.16.

Just a reminder, that Conan by default uses the major versions of gcc only, as the minor is really a patch, and intended to be fully binary compatible. The 8.3 and 9.1 minor versions can be explicitly defined though, in profiles and in command line, but they will result in different binaries than other minor gcc versions as 8.2.

**Comment by dfleury2** [comment]
Yes, you are right.  I will certainly change the way I have configured my default profile (using only 8 instead of 8.3). The same for the linux version I add each time (debian.jessie, debian.strech and so on) instead of simply linux.
I think I have done this before I see all versions in the settings.yml, so it's probably useless to use 8.3 instead of 8 in my case.

**Comment by memsharded** [comment]
Yes, there are some cases in which some users might want to exactly use gcc 8.2 and only 8.2 and make sure that the binaries are with that patch only (maybe they are patching gcc themselves, too). For the majority of cases, following the gcc major should be ok.  In any case, the PR to add them is open, for those cases too.
