### ISSUE TITLE
[question] How to use zlib with GCC 4.3 as conan dependency?

### ISSUE THREAD

**Issue by evandrocoan** [conan-io/conan#5115]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
``` 
Conan version 1.14.5
```
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

1. Install gcc 4.3 or use Ubuntu 8.10 (Inteprid)
1. Edit the conan config file https://github.com/ovidiub13/conan/blob/fcfc7a9ab94d3420f2b7561cdd4cc113bee3b798/conans/client/conf/__init__.py#L32
    1. And add gcc `4.3` to the list
1. Create the following `conan` file:
```py
from conans import ConanFile, AutoToolsBuildEnvironment, CMake
from conans.tools import download, unzip, chdir

import os

class KhompAPI(ConanFile):
    name = "xxx"
    version = "xxx"
    url = "xxx"

    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = { 'shared': False }

    generators = "cmake", "txt", "cmake_paths"

    def requirements( self ):
        self.requires( "zlib/1.2.11@khomp/stable" )
``` 

1. Then, when running the script it will throw this error:
```
# calling configure for zlib
Compiler error reporting is too harsh for ../configure (perhaps remove -Werror).
```

**Comment by memsharded** [comment]
I think this doesn't look like a Conan issue, but sounds like the build of zlib which such and older compiler is difficult. We would need to know the details of the recipe ``zlib/1.2.11@khomp/stable`` to be able to reproduce. 

I guess you are calling something like ``conan install . --build``, and it is failing in the zlib package building? In that case, it would be much easier to do a ``conan create`` from the repo containing the zlib package recipe, instead of a consumer.

Please tell me about that, thanks.

**Comment by Johnnyxy** [comment]
Hi there,
I am building zlib as dependency of boost on multiple systems (Windows, Linux, QNX; GCC 4.4, 5; VS2010-2017) and I never encountered any problems with zlib itself as this library is pure C.

Have a look at the zlib recipe from conan-center/bintray ([here](https://bintray.com/conan-community/conan/download_file?file_path=conan%2Fzlib%2F1.2.11%2Fstable%2F0%2Fexport%2Fconanfile.py)).

If it is not building for your particular target then maybe something in the recipe is missing/wrong.
In general zlib is used by a huge count of users with many programs on many different targets.

If I had any problems I would first look at the build process (if it is a unusual target) and at my code :).

**Comment by evandrocoan** [comment]
Using the same scripts on other machines:
1. Using GCC 4.4 CentOS 6 
1. Using GCC. 4.1 CentOS 5.5

Everything works fine. I only got problems with the machine using `GCC 4.3`. Note, by default your conan file does not provide the `GCC 4.3`, that is why I edited the file and added it as explained on the first post: 
![image](https://user-images.githubusercontent.com/5332158/57392974-81e8dc00-7198-11e9-88f0-f3abc6111184.png)

> We would need to know the details of the recipe zlib/1.2.11@khomp/stable to be able to reproduce.

It is a private repository for zlib, but I replaced it with the public one https://github.com/conan-community/conan-zlib and everything worked!

I guess our local repository is broken somehow, but just for `GCC 4.3`.

This was the full command line output we got when it did not worked:
```
root@devserver:~/# conan install . --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=4.3
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

zlib/1.2.11@conan/stable: WARN: Package is corrupted, removing folder: /root/.conan/data/zlib/1.2.11/conan/stable/package/b66464285c1afa65c0bbab8652a71be97f160596
conanfile.py (api/3.4@None/None): Installing package
Requirements
    zlib/1.2.11@conan/stable from 'khomp' - Cache
Packages
    zlib/1.2.11@conan/stable:b66464285c1afa65c0bbab8652a71be97f160596 - Build

zlib/1.2.11@conan/stable: WARN: Build folder is dirty, removing it: /root/.conan/data/zlib/1.2.11/conan/stable/build/b66464285c1afa65c0bbab8652a71be97f160596
zlib/1.2.11@conan/stable: Copying sources to build folder
zlib/1.2.11@conan/stable: Building your package in /root/.conan/data/zlib/1.2.11/conan/stable/build/b66464285c1afa65c0bbab8652a71be97f160596
zlib/1.2.11@conan/stable: Generator cmake created conanbuildinfo.cmake
zlib/1.2.11@conan/stable: Calling build()
zlib/1.2.11@conan/stable: Calling:
 > ../configure '--prefix=/root/.conan/data/zlib/1.2.11/conan/stable/package/b66464285c1afa65c0bbab8652a71be97f160596' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' 
Checking for gcc...
Compiler error reporting is too harsh for ../configure (perhaps remove -Werror).
** ../configure aborting.
zlib/1.2.11@conan/stable: 
zlib/1.2.11@conan/stable: ERROR: Package 'b66464285c1afa65c0bbab8652a71be97f160596' build failed
zlib/1.2.11@conan/stable: WARN: Build folder /root/.conan/data/zlib/1.2.11/conan/stable/build/b66464285c1afa65c0bbab8652a71be97f160596
ERROR: zlib/1.2.11@conan/stable: Error in build() method, line 67
        env_build.configure("../", build=False, host=False, target=False)
        ConanException: Error 256 while executing ../configure '--prefix=/root/.conan/data/zlib/1.2.11/conan/stable/package/b66464285c1afa65c0bbab8652a71be97f160596' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' 
```

**Comment by uilianries** [comment]
Hi @evandrocoan !

Take a look at Khomp's Gitlab. 1 year I created a conan-config project with some profiles. You could update that project, adding your specific GCC version. Do not hesitate to ask me on Slack!

Best regards!

**Comment by evandrocoan** [comment]
Hi @uilianries, Afonso says Hi!

We managed to fix it by updating our copy of zlib with the latest updates from the GitHub project. The problem was some compilation flag which was removed recently on GitHub, but our copy of zlib did not have this update. Now we pulled the latest changes and everything is fixed.
