### ISSUE TITLE
Conan remove -p * doesn't work

### ISSUE THREAD

**Issue by acgetchell** [conan-io/conan#5116]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.

conan 1.14.4 macOS 10.14.4, ubuntu 18.04.2

- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

MacOS:
```
┌─[adam][hapkido][±][develop {2} ✓][~/CDT-plusplus]
└─▪ conan remove -p *
ERROR: Please specify a pattern to be removed ("*" for all)
┌─[adam][hapkido][±][develop {2} ✓][~/CDT-plusplus]
└─▪ conan remove -p=*
ERROR: Please specify a pattern to be removed ("*" for all)
```
Ubuntu 18.04:
```
┌─[adam][ubuntu][~/.conan/profiles]
└─▪ conan remove -p *
ERROR: Please specify a pattern to be removed ("*" for all)
┌─[adam][ubuntu][~/.conan/profiles]
└─▪ conan remove -p=*
ERROR: Please specify a pattern to be removed ("*" for all)
```

**Comment by memsharded** [comment]
This is an effect of argparse, the parser of arguments from python, and it is outside of our control. It interprets inputs in slightly different ways, and is greedy with arguments after optional ones, even if the auto-generated help seems to allow it. You need to use the syntax as described in the docs:

```bash
$ conan remove "*" -p # all package binaries 
$ conan remove "*" -p=pckage_id # just this one  
```
Please try that and tell me. Thanks!

**Comment by acgetchell** [comment]
Sorry, I missed that documentation. Where was it?

I looked at https://docs.conan.io/en/latest/reference/commands/misc/remove.html, but that didn't give this specific example.

The documentation does say `conan remove [-p] [pattern_or_reference]`, which implies the incorrect usage pattern I tried.

Thanks,

**Comment by memsharded** [comment]
Yes, that is exactly the issue, the help:

```
conan remove [-p] [pattern_or_reference]
```
Is automatically generated from argparse, we don't write it, and we don't know how to revert the order, so positional arguments come first.

In the first example you can see:

```bash
$ conan remove OpenSSL/* --packages
```

The "pattern" comes first, then the optional arguments. That is the same for all conan commands:

```bash
# better
$ conan create . user/testing --build missing
# worse
$ conan create --build missing . user/testing
```
