### ISSUE TITLE
virtualrunenv not appending path env var

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#5117]
Currently, the `virtualrunenv` is not appending the `PATH` variable the same way the `virtualenv` is. I don't believe this is the intended behavior, but could be wrong.  I have attached two recipes that reproduce the issue, and pasted a comparison of the bat scripts showing the issue below: 

activate.bat
```
@echo off
SET PROMPT=(conanenv) %PROMPT%
SET TESTVAR=TESTVAL
SET PATH=C:\tmp;%PATH%
```

activate_run.sh
```
@echo off
SET PROMPT=(conanrunenv) %PROMPT%
SET DYLD_LIBRARY_PATH=%DYLD_LIBRARY_PATH%
SET LD_LIBRARY_PATH=%LD_LIBRARY_PATH%
SET PATH=%PATH%
```

`activate` scripts have the modified PATH while `activate_run` scripts do not.  

The commands I ran to generate the files were: 
```
conan create virtualenv_upstream bug/bug
conan install virtualenv_downstream -g virtualenv -g virtualrunenv -if virtualenv_downstream
```

[virtualenv_repro.zip](https://github.com/conan-io/conan/files/3157957/virtualenv_repro.zip)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by solvingj** [comment]
Also of note, if any user-defined environment variables are set on the upstream recipe, they are not propagated to `virtualrunenv` scripts either... for example: 
```
self.env_info.TESTVAR = "TESTVAL"
```

**Comment by memsharded** [comment]
Yes, I think this is a bug and we should try to fix it if possible:

- Generated virtualxxxenvs by conan should not destroy existing values in the environment
- They should prepend (not append) their information, so it has higher priority (if a cmake from a build_require is there, it should be used instead of the system cmake that would be in the existing path).
- Profile environment variables should be also prepended, with higher priority than dependencies environment variables. (I'd like to have the feedback from @lasote for this one)

**Comment by lasote** [comment]
Yes. At first sight, I agree with everything.

**Comment by memsharded** [comment]
I am having a look at this issue. It seems that the generators are indeed pre-pending the path. Maybe there is a difference in what the generators do:

- The ``virtualenv`` adds the vars defined in the ``package_info()`` of the dependencies, in ``self.env_info``
- The ``virtualrunenv`` adds the paths of the ``bin`` folder of the dependencies, automatically if they exist.

If you wanted both, the original design is to use both and to compose them.

Could you please have a second look @solvingj and comment? Thanks

**Comment by solvingj** [comment]
Ok, I believe I understand what you are saying now. To re-state:

`virtualrunenv` will pre-pend dependency information to the `PATH` environment variable ... but ONLY partially.  `self.env_info.PATH.append()` is ignored by `virtualrunenv`.  It ONLY adds the `bindirs` directory to `PATH`, AND it does something no other generator does, which is to actually do a filesystem check to see if all listed `bin` directories exist, thereby skipping the default of `bin` on many recipes.  

This is indeed not what I expected, and I re-read the `virtualrunenv` documentation a few times before creating this issue.  I could not get past the fact that it wasn't pre-pending anything to the `PATH`, because I knew there was a default `bin` directory in `cpp_info`.  Also, I never considered the possibility of a "partial" use of the `package_info` information.  

Thanks for the clarification.
