### ISSUE TITLE
conan commands return 0 even on ERROR

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#5119]
I am trying to add a conan install step to an existing legacy build .bat file.

I'm finding that my script continues even when the conan install step failed, e.g.:

```
conan install !CONAN_GROUPS_PACKAGE! -e SHARED_LIB=!SHARED_LIB! -pr !CONAN_GROUPS_PROFILE!
  if %errorlevel% neq 0 (
    echo conan install failure errorlevel is %errorlevel%
    exit /b %errorlevel%
  ) else (
    echo conan install success errorlevel is %errorlevel%
  )
```
which produces output:

```
- Package ID: fa813013de77903d5f60c2c4001188ae4a72ea08

ERROR: Missing prebuilt package for 'mylib-cpp/1.8.2.11@PORT/stable'
Try to build it from sources with "--build mylib-cpp"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

conan install success errorlevel is 0
```

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.10.1, Windows Server 2012

**Comment by michaelmaguire** [comment]
I see https://github.com/conan-io/conan/issues/1542 "It is not possible to return error codes from a recipe" and  "https://github.com/conan-io/conan/pull/1605 "Custom user error code" were completed, but I just want a plain old non-zero error code returned in the case of any conan error encountered during operation.

If that can't be changed for fear of breaking existing (I would argue already broken) workflows, can we add an option --return-non-zero-on-error or something?

**Comment by memsharded** [comment]
I cannot reproduce it, I have been checking the source code and it seems ok (to return ERROR GENERAL=1), and if I try:

```bash
$ conan install zlib/1.2.11@conan/stable -s os=Windows -s compiler=clang -s compiler.version=8
...
ERROR: Missing prebuilt package for 'zlib/1.2.11@conan/stable'
...
$ echo %errorLevel%
1
```

I am not sure what could be the difference, I am trying in Windows 10, could be that the difference?

**Comment by michaelmaguire** [comment]
Note that I'm using the Conan exe install on Windows, not pip-installed python directory, so perhaps the error code is not being properly propagated through that?

Also, I'm using the standard Windows shell, it looks like you are using something nicer...

**Comment by memsharded** [comment]
Yes, I am usually using "cmder", it is a nice terminal for Windows, really recommended.
But I have also tried in the regular "cmd" prompt, and also with the Conan.exe installed with the Windows installer, still same result.

**Comment by michaelmaguire** [comment]
You are right, I'm wrong.  I'm sorry.

The difference seems to come from the interaction of SETLOCAL EnableExtensions and 'if' blocks.


I tried:

```
set BB_SHARED_LIB=E:\DevelopBp\mmaguir1\src\nx_sources\platform_trunk

conan install nxgroups/591@PORT/stable -e BB_SHARED_LIB=!BB_SHARED_LIB! -pr vs2015_14_v140_xp_Release
if %errorlevel% neq 0 (
  echo conan install failure errorlevel is %errorlevel%
  exit /b %errorlevel%
) else (
  echo conan install success errorlevel is %errorlevel%
)
```

and it worked:


> [...]
> - Package ID: fa813013de77903d5f60c2c4001188ae4a72ea08
> 
> ERROR: Missing prebuilt package for 'avro-cpp/1.8.2.11@PORT/stable'
> Try to build it from sources with "--build avro-cpp"
> Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
> 
> 
> E:\DevelopBp\mmaguir1\src\nx_sources\platform_trunk>if 1 NEQ 0 (
> echo conan install failure errorlevel is 1
>  exit /b 1
> )  else (echo conan install success errorlevel is 1 )
> conan install failure errorlevel is 1
> 
> E:\DevelopBp\mmaguir1\src\nx_sources\platform_trunk>echo Exit Code is %errorlevel%
> Exit Code is 1
> 

With an if block it also works:

```
if "%NXGROUPS_SOURCE%" == "CONAN" (

set BB_SHARED_LIB=E:\DevelopBp\mmaguir1\src\nx_sources\platform_trunk

conan install nxgroups/591@PORT/stable -e BB_SHARED_LIB=!BB_SHARED_LIB! -pr vs2015_14_v140_xp_Release
if %errorlevel% neq 0 (
  echo conan install failure errorlevel is %errorlevel%
  exit /b %errorlevel%
) else (
  echo conan install success errorlevel is %errorlevel%
)

)
```


> - Package ID: fa813013de77903d5f60c2c4001188ae4a72ea08
> 
> ERROR: Missing prebuilt package for 'avro-cpp/1.8.2.11@PORT/stable'
> Try to build it from sources with "--build avro-cpp"
> Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
> 
> conan install failure errorlevel is 1
> 

But prepend SETLOCAL EnableExtensions (which I did for if DEFINED support):

```
SETLOCAL EnableExtensions

if "%NXGROUPS_SOURCE%" == "CONAN" (

set BB_SHARED_LIB=E:\DevelopBp\mmaguir1\src\nx_sources\platform_trunk

conan install nxgroups/591@PORT/stable -e BB_SHARED_LIB=!BB_SHARED_LIB! -pr vs2015_14_v140_xp_Release
if %errorlevel% neq 0 (
  echo conan install failure errorlevel is %errorlevel%
  exit /b %errorlevel%
) else (
  echo conan install success errorlevel is %errorlevel%
)

)
```

and it fails to get the right error code:

> - Package ID: fa813013de77903d5f60c2c4001188ae4a72ea08
> 
> ERROR: Missing prebuilt package for 'avro-cpp/1.8.2.11@PORT/stable'
> Try to build it from sources with "--build avro-cpp"
> Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
> 
> conan install success errorlevel is 0
> 


This appears to be a lame DOS .bat issue, and not Conan-related.  Sorry for the noise.

**Comment by memsharded** [comment]
No problem! Happy to help, and glad to see that at least you identified the issue. 
This is one of the reasons I prefer to script in python myself, whenever possible, not in .bat. It bites you too often. Cheers!

**Comment by michaelmaguire** [comment]
https://stackoverflow.com/questions/4367930/errorlevel-inside-if
