### ISSUE TITLE
Outdated dep does not trigger rebuild

### ISSUE THREAD

**Issue by asleszyn** [conan-io/conan#5121]
conan ver: 1.15.0
os: Ubuntu 17.04 x86_64

I have a **myapp** (executable) pkg which requires a **mylib** (static lib) pkg.
1. **mylib** has a bug fixed. The pkg is exported to the local cache.
2. I `conan create` a **myapp** pkg with `-b outdated`.
3. The **mylib** is rebuilt properly as a dependency of **myapp** since there are new sources. The **mylib** pkg id does not change since there are no changes in the settings or options.
4. **myapp** is not rebuild since the dependency's id did not change. Conan says it's `Already installed!`.

I would expect that a rebuilt dependency would trigger a rebuild of any pkgs that depend upon it. Am I missing something?

I don't want to bump the version of the lib after each commit or trigger the rebuild of the app manually.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Johnnyxy** [comment]
hi there,
if only the code changes then Conan does not know that it has changed and does not initiate a rebuild.
If the recipe has changed then Conan does a rebuild.
If the calculated ```package_id``` of your recipe configuration does not exist Conan initiates a build.
The ```package_id``` is based on the provided settings and options of your recipe at invocation of Conan with your recipe ([see here](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-id)).

You can instruct Conan to rebuild a specific dependency with the ```build``` parameter.

```conan install --build=outdated --build=mylib ...```

**Comment by asleszyn** [comment]
> if only the code changes then Conan does not know that it has changed and does not initiate a rebuild.

This is not what I experience. I export the **mylib** pkg to the local cache with just code changes. I create a package that depends (with `-b outdated`) on it and it **gets rebuild**, which is correct in my opinion.

The thing is that the package that has its dependency rebuild **does not get rebuilt** - this, I think, is a bug.

**Comment by Johnnyxy** [comment]
Ah ok. I see.
If it is in the same repository this should already be the correct behaviour to rebuild depending packages.

You did not mention if you pull the ```mylib``` from the same or some remote repository.
But if you use some repository from a remote you then you can use the ```--update``` parameter on ```conan install``` as this checks the remote repositories if there are updates to the recipes/packages.

**Comment by asleszyn** [comment]
Let me clarify:
1. There is no conan server (remote) involved. Just the local cache.
2. **mylib/1.2.3@user/channel** -- a C++ static lib, packaged with conan.
3. **myapp/4.5.6@user/channel** -- a C++ application, packaged with conan, requires **mylib/1.2.3@user/channel**.

The issue:
1. I do **only** code changes to **mylib**.
2. I do `conan export <mylib-path> user/channel`. New source is moved to the local cache.
3. I want to rebuild **myapp** since the dependency changed.
4. I do `conan create <myapp-path> user/channel -b outdated`.
5. conan resolves the dependencies: notices that **mylib/1.2.3@user/channel** has new source. **mylib** gets rebuild -- this is what I expect.
6. After this conan declares that **myapp/4.5.6@user/channel** is **Already installed!** and does not build my application with the updated dependency. This means that the `conan create ...` from point 4. only rebuilds my dep but not the pkg that depends upon it. IMHO this is not correct

**Comment by lasote** [comment]
A change with a single comment in the recipe will make it outdated too, and it doesn't mean that the package of the application should be rebuilt. The same if the library is shared and no header has changed. To let Conan know that the application has to be rebuilt the `package_id` of the application has to change. 

Check [default_package_id_mode](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#changing-the-default-package-id-mode).

If you are not bumping the version probably you are interested in the [revisions](https://docs.conan.io/en/latest/mastering/revisions.html) feature. We are working [here](https://github.com/conan-io/conan/pull/4958) on a new mode that will change the package_id of the application even if the hash of the package of `mylib` changes.

We currently don't have a build policy meaning `build outdated and all the downstream nodes`. If you are interested in the automation of a CI process, we could provide some ideas. The `--json` output of the `conan info` could help, also the `--build-order` that will tell you which libraries would be affected by the rebuilding of the library.

**Comment by asleszyn** [comment]
Unfortunately neither of those solutions is good enough for me. I'm trying to automate a build system and I need to know when a rebuild is necessary.

Currently, we are bumping the version of the dependency with each commit but that is really annoying since we need to update the version of the dep and the required fields of all the pkgs that use it. It blows up really fast and requires a lot of manual intervention and it's easy to forget to update a version somewhere.

Can you suggest a way to solve this issue?

**Comment by lasote** [comment]
The way to solve it would be to implement a new [build policy](https://docs.conan.io/en/latest/mastering/policies.html) to build the nodes to build and all the downstream nodes.
I think this would be a very interesting thing to have. Thanks, we will try to move it forward.

**Comment by lasote** [comment]
Possible approach:

`--build=outdated --build=recursive` (or similar name), so if a node has to be build (because of whatever policy) if the new `--build=recursive` is specified, it will cause any node depending on another node built, to be built.

**Comment by asleszyn** [comment]
Thank you!
