### ISSUE TITLE
Metadata is lost when exporting package to nexus and installing it.

### ISSUE THREAD

**Issue by JigsawCorp** [conan-io/conan#5123]
Hello, this issue is also submitted to nexus-repository-conan: https://github.com/sonatype-nexus-community/nexus-repository-conan/issues/58

Conan version: 1.15.0
OS tried: Windows 10 and Ubuntu 18.04.2

* **What are you trying to do?**
I am trying to export a package I made with the recipe that goes with it to a nexus repo. Then, I am trying to install said package on a computer that doesn't have that package.
* **What feature or behavior is this required for?**
This is required to export packages to nexus and to install them on a client.
* **How could we solve this issue? (Not knowing is okay!)**
It seems like the metadata.json file doesn't get updated. Here's what I did to test it out:

1.  Create a recipe from pre-built binaries
`conan new PackageTest/1.0.0@myuser/testing --bare`

2. Export the package with the pre-built binaries
`conan export-pkg ../ PackageTest/1.0.0@myuser/testing --package-folder=.`

3. Upload the package and recipe to my nexus repo
`conan upload PackageTest/1.0.0@myuser/testing --all -r=my_private_repo`

4. Remove the package from my client
`conan remove PackageTest*`

5. Attempt to install the package I just uploaded to nexus
`conan install PackageTest/1.0.0@myuser/testing -r=my_private_repo`

Results from that command:
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Installing package: PackageTest/1.0.0@myuser/testing
Requirements
   PackageTest/1.0.0@myuser/testing from 'my_private_repo' - Cache
Packages
   PackageTest/1.0.0@myuser/testing:0ab9fcf606068d4347207cc29edd400ceccbc944 - Download

PackageTest/1.0.0@myuser/testing: Retrieving package 0ab9fcf606068d4347207cc29edd400ceccbc944 from remote 'my_private_repo' 
ERROR: Binary package not found: 'PackageTest/1.0.0@myuser/testing0ab9fcf606068d4347207cc29edd400ceccbc944'

```

However, from looking at my nexus, the package is indeed there and the manifest specifies the right configuration. 

The most important thing to note is that before removing the package from my client, the metadata.json pointed to the right package. However, when I removed it and installed the one from my nexus repo, it goes back to this:

`{"recipe": {"revision": "0", "remote": "my_private_repo", "properties": {}}, "packages": {}}`

These are similar issues: https://github.com/conan-io/conan/issues/5027 - https://github.com/sonatype-nexus-community/nexus-repository-conan/issues/56 - https://github.com/conan-io/conan/issues/4833

* **Anything else?**
I also tried going to version 1.13.3 and I kept getting this error when simply running `conan`:
`ERROR: Conan storage path has to be an absolute path`

I tried all steps above on Windows 10 and Ubuntu 18.04.2

**Comment by lasote** [comment]
If the binary package eventually is not installed, is normal if the `metadata` doesn't contain the `package_id`, what I don't understand is in which point it fails to download it, looks like it finds it but then it fails:

```
Packages
   PackageTest/1.0.0@myuser/testing:0ab9fcf606068d4347207cc29edd400ceccbc944 - Download

PackageTest/1.0.0@myuser/testing: Retrieving package 0ab9fcf606068d4347207cc29edd400ceccbc944 from remote 'my_private_repo' 
```

Is a regular repository or proxy? To be honest I haven't used Nexus so far.

**Comment by JigsawCorp** [comment]
@lasote 
Hi!

I've been doing some tests and took a peek at the source from conan and nexus-conan-repository for 2 days. I've sort of pinpointed what fails. 

Firstly, our nexus repo is a not a conan proxy, it's a self-hosted repo. Secondly, I found that the binaries get properly uploaded to the repo. I noticed that what actually fails only on our conan repo is this request:

```
{"_action": "REST_API_CALL", "duration": 0.019165992736816406, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.15.0 (Python 3.7.3) python-requests/2.21.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "username"}, "method": "GET", "time": 1557746668.4039876, "url": "[OUR_URL]/v1/conans/package_test/1.0.0/conan/stable/packages/63da998e3642b50bee33f4449826b2d623661505"}
{"_action": "EXCEPTION", "class": "PackageNotFoundException", "message": "Binary package not found: 'package_test/1.0.0@conan/stable:63da998e3642b50bee33f4449826b2d623661505'", "time": 1557746668.405988}
```

Everything goes smooth until it tries to do a get to /packages/sha. I tried running this on a repo I made on bintray and had no problem. 

Also, we are using the latest Conan release. I am thinking that the latest release of Conan could be incompatible with the latest release of conan-neux-repository, which is quite old. I did my best to look at what you guys changed in the latest Conan release, but I can't pinpoint what conflicts with conan-nexus-repository. 

What I've been trying to see if it's actually a problem with the latest version of Conan is to install an earlier version of Conan. The problem is that I am not able to. When I install like this:

`pip install conan==1.13.3`

I get this error when entering any Conan command:

`conan --version`
`ERROR: Conan storage path has to be an absolute path`

I would really like to be able to test on earlier versions of Conan so we can actually find this problem, but I have no idea what causes issues with installing an earlier version of Conan. Do you have any idea what this could be?

**Comment by JigsawCorp** [comment]
@lasote 

Alright, good news if we can call it that. I finally managed to install Conan 1.13.3. If anyone else stumbles upon this trying to install earlier versions and are getting `ERROR: Conan storage path has to be an absolute path`, you must simply go to your `.conan/conan.conf` and change your path variable to whatever you want, but follow the path instructions in the comment of that file. That variable should be on line 59. 

Anyways, so version 1.13.3 works just fine. That means that Conan 1.15.0 is not compatible with nexus-conan-repository. Seems like there is a problem with the http request I indicated in the above comment. I'll do my best to do my own digging and report back if I can find it. However, you should know that almost everything is not working for me on Conan 1.15.0. Searching, deleting packages, installing packages, etc. are all not working. This seems like it could be problematic as I think many users use nexus and conan. I guess I am the first one to report this as conan 1.15.0 just came out. 

Anyways, thanks for maintaining this project! I'll do my best to help you guys out find the issue, but my knowledge is limited with your code base.

**Comment by JigsawCorp** [comment]
Alright, I found what seems to be the problem. To find the issue, I tried installing a package from my nexus repo with 1.13.3 and log what happens. Then, I deleted the package from my local cache, changed to version 1.14.0, attempted to install the same package, and logged. From diffing both log files, I can see that the requests have changed.  I have uploaded the logs from 1.13.3 and 1.14.0

What the problem seems to be is that in 1.13.3, we make a get on [OUR_URL]/v1/conans/package_test/1.0.0/conan/stable/packages/63da998e3642b50bee33f4449826b2d623661505/download_urls

On 1.14.0, we make a get on [OUR_URL]/v1/conans/package_test/1.0.0/conan/stable/packages/63da998e3642b50bee33f4449826b2d623661505

It seems that by not getting on /downloads_url first, we get a problem. On 1.14.0, we just do a get directly on packages/sha, which throws a  `PackageNotFoundException`. It does not return a 404, so it seems that the endpoint is indeed implemented on the server. It just seems like the actual logic is broken on the server or on conan-nexus-repository.

[classified_conan_trace_1.13.3.log](https://github.com/conan-io/conan/files/3172965/classified_conan_trace_1.13.3.log)
[classified_conan_trace_1.14.0.log](https://github.com/conan-io/conan/files/3172966/classified_conan_trace_1.14.0.log)

**Comment by JigsawCorp** [comment]
Closing. This is 100% a problem with nexus-repository-conan. They haven't implemented the routes for the new routes that Conan 1.14.0 added.

**Comment by lasote** [comment]
Just a note, these routes are not new! the v1 protocol hasn't changed!

**Comment by JigsawCorp** [comment]
@lasote 

Really? Because from the two log files I attached, the calls are not the same from what I am seeing.

**Comment by lasote** [comment]
The calls could be different from the client but the server has exactly the same API endpoints and the behavior of the protocol is the same

**Comment by JigsawCorp** [comment]
@lasote 

I cannot seem to find a call to `[OUR_URL]/v1/conans/package_test/1.0.0/conan/stable/packages/63da998e3642b50bee33f4449826b2d623661505` in versions 1.13.3 and less made from the client. Has Conan client ever made this call in a version prior to 1.14.0? From my logs, 1.14.0 makes that call and it fails because conan-nexus-repository doesn't have the endpoint for it implemented. I can only imagine they never implemented it because that call was never made before.

**Comment by lasote** [comment]
I'm not sure, but if the endpoint is responding now, the endpoint was there from the beginning, the JFrog Artifactory Conan v1 hasn't changed since `Artifactory 5.1.2, Released: March 8, 2017`. That version keeps working with Conan. I cannot tell you what is implemented or not in Nexus, from what you say, I deduce probably the server implementation was not complete.
