### ISSUE TITLE
Cannot remove package from nexus repository; creates a 404 error.

### ISSUE THREAD

**Issue by JigsawCorp** [conan-io/conan#5124]
Hello, this issue has also been submitted to the nexus-repository-conan Github: https://github.com/sonatype-nexus-community/nexus-repository-conan/issues/59

OS tried: Windows 10 and Ubuntu 18.04.2
Conan version: 1.15.0

I am not able to remove a recipe and its associated binaries from a nexus repo. 

`conan remove PackageTest/1.0.0@myuser/testing -r=my_private_repo` outputs:
`ERROR: 404 Not found. [Remote: facilis]`

I have a feeling this is somehow related to the search function not working on nexus repositories.

**Comment by memsharded** [comment]
Hi @JigsawCorp 

Yes, it seems this is something related to the server side, I am afraid we can't do anything here, in this repo, that is client side app.
 
So many thanks for linking the main issue. I think we can close this one and follow conversation there.

**Comment by JigsawCorp** [comment]
Thanks for responding quickly!
