### ISSUE TITLE
How to force conan to initialize the default profile?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#5129]
For CI scripts I need to set `compiler.libcxx=libstdc++11` for the default profile after installing/upgrading conan but before doing anything else. How to force conan to create `~/.conan/profiles/default` (and `~/.conan/settings.yml`)? `conan user` is not enough for that.

**Comment by lasote** [comment]
```
conan profile new default --detect
conan profile update settings.compiler.libcxx=libstdc++11 default
```

**Comment by db4** [comment]
Great, thanks a lot!
