### ISSUE TITLE
[workspaces] Cannot run apps which depend on editable shared libs

### ISSUE THREAD

**Issue by joaquin-herrero** [conan-io/conan#5132]
##### Context:
Working in a workspace with several shared libs on editable mode and a consumer App as root of the depedency graph. 

##### Problem:
I can't run or debug from the IDE due to missing dll files. 

##### Example:
Having a workspace with an App which depends on shared libs libA, libB and libC. App and libA on editable mode, when I call:

```conan workspace install ../workspace.yml -pr=debug```
```cmake -G "Visual Studio 14 2015 Win64 -DCMAKE_BUILD_TYPE=Debug ...```

I can compile all targets from the IDE but I can't run the app or debug it because libA.dll binary isn't in the binary path of App. Both CMakeLists.txt of App and libA uses the link helper:

```conan_target_link_libraries``` 

One related issue is [#4739](https://github.com/conan-io/conan/issues/4739). But this is not a real solution.

I also tried to use a 'virtualrunenv' to add all binary paths of my dependencies to the PATH but when I launch Visual Studio from the virtualrunenv I get lots of Visual Studio related errors, so I discard this approach. In addition, this is not a multi configuration solution since the second call to:

```conan workspace install ../workspace.yml -pr=release ...```

Overrides the previous activate/deactivate.bat files.

A possible workarround could be add a post build action to copy all editable shared libs to root binary dir. But this should be done from the workspace's CMakeLists.txt to avoid modifying packages CMakeLists.txt and following the CMake reference [here](https://cmake.org/cmake/help/v3.13/command/add_custom_command.html) 

>  The <target> must be defined in the current directory; targets defined in other directories may not be specified.

##### Configuration:
Windows 10
Visual Studio 2015 
CMake 3.13
Conan 1.15

**Comment by lasote** [comment]
Yeah, I faced something similar even without editables/workspaces. My final project depends on `opencv` package, and to run the app (face detector) I need some assets with the `xml`s. 
I want to run the app from `clion`, so, how to run some imports/deploy files? I could (a bit artificially) create a workspace for my consumer project and then the workspace might be able to do something for me. 
But of course, your case is even more important, because the shared libraries need, as you said, to be updated with the change of configuration, my assets are always the same.
We need to think about this.

**Comment by joaquin-herrero** [comment]
Thank you @lasote for your fast answer! I'll stay tuned

**Comment by jgsogo** [comment]
I've added some notes here with possible actions to make it work: https://github.com/conan-io/conan/pull/4879#issuecomment-492160819

**Comment by joaquin-herrero** [comment]
I think I can do something creating a custom generator like the one did by @boussaffawalid on [#4705](https://github.com/conan-io/conan/issues/4705).

Basically I need to modify the IDE run command to execute a activate.bat like the one which generates virtualrunenv but a multi configuration one to avoid override with Debug/Release installations... 

Also I have to avoid appending the previous PATH recursively, so I need to save it to a file on activate/deactivate file generation.

I think working this way I won't have issues with RPATHS on osx too. Have to check it.

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
