### ISSUE TITLE
don't pass -T (toolset) for generators other than Visual Studio and Xcode

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#5133]
reported: https://github.com/bincrafters/community/issues/788

conan shouldn't be using `-T` for generators other than Visual Studio and Xcode, like Ninja.
https://cmake.org/cmake/help/v3.14/variable/CMAKE_GENERATOR_TOOLSET.html#variable:CMAKE_GENERATOR_TOOLSET

```
Toolset specification is supported only on specific generators:

Visual Studio Generators for VS 2010 and above
The Xcode generator for Xcode 3.0 and above
The Green Hills MULTI generator
```

/cc @Mirko-von-Leipzig 

To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Is this still happening?

```
def get_toolset(settings):
    if settings.get_safe("compiler") == "Visual Studio":
        subs_toolset = settings.get_safe("compiler.toolset")
        if subs_toolset:
            return subs_toolset
    return None
```
@SSE4  can you confirm and open a PR to solve it if needed?

**Comment by SSE4** [comment]
@lasote okay, opened it: https://github.com/conan-io/conan/pull/5201
