### ISSUE TITLE
Deploy generator clobbers file permissions, including executable bit

### ISSUE THREAD

**Issue by tmwa** [conan-io/conan#5135]
Deploying a binary file from a package using the deploy generator will discard executable bits, making any executables shipped with the package unusable out of the box.

Example using ninja:
```sh
$ conan install ninja_installer/1.9.0@bincrafters/stable -g deploy
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Installing package: ninja_installer/1.9.0@bincrafters/stable
Requirements
    ninja_installer/1.9.0@bincrafters/stable from 'conan-center' - Cache
Packages
    ninja_installer/1.9.0@bincrafters/stable:44fcf6b9a7fb86b2586303e3db40189d3b511830 - Cache

ninja_installer/1.9.0@bincrafters/stable: Already installed!
Generator deploy created deploy_manifest.txt
Generator txt created conanbuildinfo.txt
```

Output files are not executable:
```sh
$ ls -l ninja_installer/bin 
total 4372
-rw-rw-r-- 1 me me 4473408 May 13 17:58 ninja
```

This is probably due to `shutils`: https://github.com/conan-io/conan/blob/a21899a3cded38650cf5c83d3177d1cdd5665114/conans/client/generators/deploy.py#L45

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
Hi @tmwa and thanks for the report!

Yes, this seems an issue for executable files. In fact, the fix seems quite easy.
