### ISSUE TITLE
How to print dependency tree?

### ISSUE THREAD

**Issue by Jochen0x90h** [conan-io/conan#5137]
How do I print the dependency tree of a project recursively? I have conan 1.14.3.

Thanks!

**Comment by Johnnyxy** [comment]
Hi there,
what do you mean with "recursively"?

If you want to get informations from a recipe you have a look at ```conan info``` ([see here](https://docs.conan.io/en/latest/reference/commands/consumer/info.html#conan-info)).
To get json output have a look [here](https://docs.conan.io/en/latest/reference/commands/output/info.html#info-output).

**Comment by jgsogo** [comment]
And you will find really useful the argument ``--graph=<file>`` (take into account the extension you give to ``file`` 😉 )

**Comment by xahon** [comment]
Does `conan info` support recursive printing of all dependencies in the form of a list? When i run `conan info something -pr profile -db` it prints what i wanted at the beginning but then it prints too verbose output below and i need to scroll up a lot. I didn't find any option that can do that in stdout (and even in a file)

**Comment by memsharded** [comment]
@xahon

```
conan info poco/1.9.4@ --only=None
```

Also the --json output of ``conan info --json=file.json``, then parsing the json file. It is always better to use structured file formats than parsing stdout.


Also, for automated tasks, like deciding what needs to be built, the recommended approach is using lockfiles and ``conan lock build-order``.

**Comment by xahon** [comment]
@memsharded I'm trying to trace which packages are missing in my own remote and which ones need to be uploaded. Parsing json file would take extra commands when doing a simple job. With raw output it could be easily `sed`ed and piped to another function or redirected to file if needed using `bash` and then piped to another handler. I did `conan info ... -db` and then searched for patterns "ERROR:" and "There are no" to find out which packages are missing in specific remote
It would be good as an option if someone needs that

**Comment by solvingj** [comment]
@Jochen0x90h may we close this issue?
