### ISSUE TITLE
Conan keeps forcing build when I am exporting a package with only binaries.

### ISSUE THREAD

**Issue by JigsawCorp** [conan-io/conan#5138]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi, I am trying to export a package that only contains binaries to my remote. The problem is that Conan always builds my sources when I don't want to. 

Here's what I am doing:

conan create PackageTest/1.0.0 --bare
conan export-pkg ../ PackageTest/1.0.0@myuser/test --package-folder=.

When running the export-pkg command, I am in the folder of my binaries and in the parent folder I have the conanfile.py. 

I then get `WARN: Forced build from source`

How can I avoid this? This is causing issues because I am losing some folders and getting new compiled folders when I do not want to.

*Edit* This has been tried with Conan 1.13.3 and 1.15.0 and tried on Windows 10 and Ubuntu 18.04.2

**Comment by Johnnyxy** [comment]
hi there,
why do you issue a ```conan export-pkg```?
If you use the ```conan create``` command, you do not need an additional Conan command. The built package has been exported already.
If you are using the ```conan build``` separately then you have to ```conan export-pkg``` if you want the built package to be available in the Conan repository.

**Comment by JigsawCorp** [comment]
Thank you for your reply @Johnnyxy ,

I personally followed the Conan guide as to packaging existing binaries: https://docs.conan.io/en/latest/creating_packages/existing_binaries.html

We basically have some pre-compiled libraries and we also might have some non-compiled code that we want to put on Conan without getting built. Either way, the forced build just on the pre-compiled binaries might have some unexpected results that we wan't to avoid. 

I tried using create, but it still tries to build.

**Comment by jgsogo** [comment]
Hi! Yes, the `conan create` command will always call the `build` step, nevertheless, for your use case you don't need to _create_ the package, you just need to `export-pkg`. Anyway, if your recipe doesn't have a `build()` step or the function is empty, it should run and do nothing.

The steps you have to follow are:
 1. You need a recipe for the package, a handy way to create one is using
    ```
    conan new pkg/1.0.0 --bare 
    ```
    it will create a very basic recipe without `source()` or `build()` methods (you don't need them as you already has the binaries). Depending on the layout of your binaries, the implemented logic in the methods `package()` and `package_info()` will be enough or you should write your own.

 2. Create your package. You can run `conan create` although it will do nothing for the _source_ and _build_ steps, so you can directly run `conan export-pkg`.

Now you should have your package available in the local Conan cache.

**Comment by Johnnyxy** [comment]
@JigsawCorp 
I am packaging some binaries too like proprocessors etc. and I am using the ```conan create``` command as I have to fetch the prebuilt binaries before packaging.

If you have to do more than copying files to create your package I would go for the ```conan create``` command as @jgsogo described as this ensures that you can modify your recipe later and you do not have to adapt your build-/toolchain to call conan in some other way.

**Comment by JigsawCorp** [comment]
@jgsogo 

Hi, the problem is that I am doing the exact steps you just said and it still forces the build.

**Comment by JigsawCorp** [comment]
@Johnnyxy 

Yeah, I am doing exactly like he did. All I want is to copy exactly what I have in my folder full of binaries. I am doing everything like it is indicated in the tutorial and what he says, but it still gives the same warning and tries to build. I don't think that I am doing something wrong, I am more starting to think that this is a bug.

**Comment by Johnnyxy** [comment]
Can you provide a minimal example? Strip down your recipe that it copies only some/one file and place it in a similar folder structure that it could be executed out of the box?

**Comment by JigsawCorp** [comment]
@Johnnyxy 

Alright, so I made a very basic example using only one .txt file and it still does it.

1) Create the recipe:
`C:\test> conan new TestPackage/1.0.0 --bare`

2) Create the binaries folder:
`C:\test> mkdir lib`

3) I then create a test.txt file in the lib folder.

4) Go to lib folder:
`C:\test> cd lib`

5) Export the package
`C:\test> conan export-pkg ../ TestPackage/1.0.0@myuser/testing --package-folder=.`

6) Output:
```
Exporting package recipe
TestPackage/1.0.0@myuser/testing: A new conanfile.py version was exported
TestPackage/1.0.0@myuser/testing: Folder: C:\Users\username\.conan\data\TestPackage\1.0.0\myuser\testing\export
TestPackage/1.0.0@myuser/testing: WARN: Forced build from source
Packaging to c32596dcd26b8c708dc3d19cb73738d2b48f12a8
TestPackage/1.0.0@myuser/testing: Exporting to cache existing package from user folder
TestPackage/1.0.0@myuser/testing: Package folder C:\Users\username\.conan\data\TestPackage\1.0.0\myuser\testing\package\c32596dcd26b8c708dc3d19cb73738d2b48f12a8
TestPackage/1.0.0@myuser/testing: Packaged 1 '.txt' file: test.txt
TestPackage/1.0.0@myuser/testing: Package 'c32596dcd26b8c708dc3d19cb73738d2b48f12a8' created
```

So as we can tell from the output, it tried to build the sources again.

**Comment by jgsogo** [comment]
@JigsawCorp, ok, the issue you are reporting is just related to the message in the log. Conan detects that there are no binaries associated with this package in the cache and records that it has to build them from sources (although the `build` step is not executed because the `conan export-pkg` triggers no build).

Everything is working as expected, although that WARN message could be confusing, we'll try to get rid of it and ensure it is only printed if it is going to be a subsequent `build()`.

You can safely ignore it. Thanks for reporting. 👍

**Comment by JigsawCorp** [comment]
@jgsogo Thank you for the quick reply, but that is unfortunately not the case. The reason I brought this issue up is that I was adding a C++ library and when I diffed the package created and the actual folder I want to package, some new folders were added and some deleted. No actual file was changed, but I still had like a vs folder that was created. For this library in particular it wasn't a problem, but I can still tell that Conan tried to build it. My problem is that we are planning to add much more to our Conan repo, but there are some things that we specifically do not want to be compiled as some of our scripts for the project that uses that library as a dependency will build it itself with some custom actions. We specifically want these non-compiled files to stay that way.

**Comment by jgsogo** [comment]
If I run `conan export-pkg` no `source()` and `build()` steps are executed, this is the output from my log:

```
⇒  conan export-pkg . issue/testing --force
Exporting package recipe
pkg/1.0.0@issue/testing: The stored package has not changed
pkg/1.0.0@issue/testing: WARN: Forced build from source
Packaging to f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2
pkg/1.0.0@issue/testing: Generating the package
pkg/1.0.0@issue/testing: Package folder /Users/jgsogo/.conan/data/pkg/1.0.0/issue/testing/package/f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2
pkg/1.0.0@issue/testing: Calling package()
pkg/1.0.0@issue/testing package(): Packaged 1 '.py' file: conanfile.py
pkg/1.0.0@issue/testing: Package 'f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2' created
```

If I run `conan create`, then the `source()` and `build()` steps are performed, but nothing is done as those functions are empty/default:

```
⇒  conan create . issue/testing
Exporting package recipe
pkg/1.0.0@issue/testing: The stored package has not changed
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

pkg/1.0.0@issue/testing: WARN: Forced build from source
Installing package: pkg/1.0.0@issue/testing
Requirements
    pkg/1.0.0@issue/testing from local cache - Cache
Packages
    pkg/1.0.0@issue/testing:f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2 - Build

pkg/1.0.0@issue/testing: Copying sources to build folder
pkg/1.0.0@issue/testing: Building your package in /Users/jgsogo/.conan/data/pkg/1.0.0/issue/testing/build/f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2
pkg/1.0.0@issue/testing: Generator txt created conanbuildinfo.txt
pkg/1.0.0@issue/testing: Calling build()
pkg/1.0.0@issue/testing: WARN: This conanfile has no build step
pkg/1.0.0@issue/testing: Package 'f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2' built
pkg/1.0.0@issue/testing: Build folder /Users/jgsogo/.conan/data/pkg/1.0.0/issue/testing/build/f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2
pkg/1.0.0@issue/testing: Generated conaninfo.txt
pkg/1.0.0@issue/testing: Generated conanbuildinfo.txt
pkg/1.0.0@issue/testing: Generating the package
pkg/1.0.0@issue/testing: Package folder /Users/jgsogo/.conan/data/pkg/1.0.0/issue/testing/package/f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2
pkg/1.0.0@issue/testing: Calling package()
pkg/1.0.0@issue/testing package(): Packaged 1 '.txt' file: conanbuildinfo.txt
pkg/1.0.0@issue/testing: Package 'f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2' created
```

Note the lines:

```
pkg/1.0.0@issue/testing: Calling build()
pkg/1.0.0@issue/testing: WARN: This conanfile has no build step
```

But the most important thing is that it produces the same result using `create` or `export-pkg`, same files are copied, and same package_id is computed:

```
pkg/1.0.0@issue/testing package(): Packaged 1 '.txt' file: conanbuildinfo.txt
pkg/1.0.0@issue/testing: Package 'f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2' created
```

----

Conan doesn't try to build just because there is a VS solution or any makefile in the directory, Conan only executes the code that is written in the `build()` function, there is no magic here. Then it performs the code in `package()` which for a _bare_ recipe is `self.copy("*")` (it should copy everything in the local folder, I think we are not excluding nothing here).

There is something I'm not understanding, maybe you can share with us more data, the recipe you are using and which files are in that directory (feel free to reach us in Cpplang Slack too, write to us [a private message](https://cpplang.slack.com/messages/@U65C2QYF3), or send a mail to info@conan.io)

**Comment by JigsawCorp** [comment]
@jgsogo I apologize for making you waste your time. I diffed again and the reason I believed there was some sort of build happening is because some empty folders were not carried with. I know this is intended behavior, but I guess I was a little bit too obsessed by the warning I saw. 

So, everything is actually all right. There is no issue. Closed.

**Comment by jgsogo** [comment]
Don't worry, and thanks for your time. I've opened an issue to get rid of that warning for the `export-pkg` command, as it is not correct for this workflow (https://github.com/conan-io/conan/issues/5146). 

We will be very pleased to help you integrate Conan in your current projects.
