### ISSUE TITLE
using conan for executable binary distribution without the dependencies

### ISSUE THREAD

**Issue by Prinkesh** [conan-io/conan#515]
I am creating packages for executables and uploading it to a local conan server, but now the consumers who need this executable package , either has to install it using 

conan install package_reference --all (/package-id)

this installs the package in local store 
However, i need some option to specify where to import the package files from local store to some user directory

This is doable by using conanfile.txt , but that starts looking for dependencies of the package as well which is what i want to skip and only show the dependencies in the info but don't download them .

**Comment by memsharded** [comment]
Hi!

Some ideas:

- I am not sure why you are using ``conan install --all``, that retrieves ALL the binary packages for all OSs, compilers, and settings in general. If they are executables, you should be fine by installing the one that matches your OS
- You can do that by using the ``conan_info()`` method, and removing there from ``self.info`` the settings that you don't want to generate different binaries
- It is true that ``conan install`` without the ``--all`` does things transitively. You might want to use the ``private`` requirements, which basically does that: retrieves the dependencies meta-info (conanfile.py), but do not retrieve the dependencies binaries if they are not needed, that is, if there is already a binary for the package and it doesn't have to be built.
- I suggest to have a look to conan virtualenvs and the virtualenv generator, if you haven't done it yest. Using it for tools is very convenient, as different versions of the tools can be handled very easily.

Please tell me if these make sense for your needs. Thanks!

**Comment by Prinkesh** [comment]
* I was using that as i had only one package
* So , if i make the all the dependencies private will the dependencies show up in package info, as i need that . Just the dependencies doesn't needs to be downloaded

**Comment by memsharded** [comment]
Yes, that is the idea. But please not that the dependencies meta-information (that is, the package recipes, or conanfile.py) will be downloaded. This is not an issue, they are very small and download is fast, but they are needed to process the package info. So yes, try making all your dependencies private.

**Comment by Prinkesh** [comment]
ok, but i don't have the dependencies packages on my local conan server , and i don't want to upload it either as i am using this server to deploy executable to production servers and only these packages reside on the server . the dependencies ( libraries ) resides on other server which is for developers to push the libraries

**Comment by memsharded** [comment]
I see. It seems that you are pushing conan towards deploys in a very specific workflow. Without the dependencies it is not possible to have the full meta-information, though a large part is accessible via the generated ``conaninfo.txt`` file. 

Please consider for example the case in which the executable depends on shared libraries, those packages containing that shared libraries would actually need to be depended on by conan, and retrieved in the conan install. So the "one size fits all" solution is not possible, and currently conan is much more focused on the developers workflows than on deploys.

On the other hand, conan is actually very flexible, so I think it might be possible to write recipes that would help in this task. But we have to think a bit more about this use case.

**Comment by memsharded** [comment]
This has been improved in recent conan releases, with environments, the ``deploy()`` method, re-packaging approaches, etc. See the dedicated docs page: http://docs.conan.io/en/latest/packaging/running_packages.html

So I think this can be closed now, but please comment or re-open if necessary. Thanks!

**Comment by vkotovv** [comment]
@memsharded Your link is not working now, correct one should be http://docs.conan.io/en/latest/devtools/running_packages.html

**Comment by memsharded** [comment]
Uhm, the link looks the same, and both of them are working. Is it possible that the docs were down for a while? Could you please check? Thanks

**Comment by vkotovv** [comment]
@memsharded Your comment was edited by pvicente 4 hours ago:
![edit](https://user-images.githubusercontent.com/1636249/35808364-9121d57e-0a96-11e8-8c31-73a77de3d754.png)
He changed the link.

**Comment by memsharded** [comment]
You are right, sorry I didn't see it!
