### ISSUE TITLE
[suggestion] [workspaces] Support yaml list as workspace root

### ISSUE THREAD

**Issue by birgerbr** [conan-io/conan#5155]
Using yaml list for setting the workspace root variable makes it easier to manage the yaml file, when the workspace has multiple roots.

I would like to contribute to this feature.

**Comment by jgsogo** [comment]
Oh! It looks like pretty straightforward and the proper way to implement a list in a yaml file  🤦‍♂ . Let's move to the PR, thank you so much for your contribution!
