### ISSUE TITLE
Request for delayed resolution of python_requires

### ISSUE THREAD

**Issue by AKhranovskiy** [conan-io/conan#5160]
I have recipe A that shares some python code. I want to test it, so I have test_package for it.
I run test with `conan create . user/channel`.
The test package loads main recipe with `python_requires` that demands full reference with exact version. So it is manual work to keep that reference up to date with main recipe.

Next problem is that `python_requires` is resolved *before* main recipe is published to local cache. So it is impossible to load the latest version of main recipe that has been published just now.

I would like to be able to load package with `python_requires` at later step when the package is already in cache, and test recipe knowns the reference of main recipe.

Conan 1.14.3
macos

To help us debug your issue please explain:

- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [*] I've specified the Conan version, operating system version and any tool that can be relevant.
- [*] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi, thanks for raising the issue.

About the full reference of the `python_requires`, yes, it is a limitation. You might try to load the version from a file as described [here](https://docs.conan.io/en/latest/howtos/capture_version.html#how-to-capture-package-version-from-text-or-build-files) I didn't try it but it might work.

About the second part, I cannot reproduce the issue. If I change the recipe of the python require, and then I run the `conan create` the test_package is using the latest changes. I uploaded here the example: https://github.com/lasote/issue_5160. Please check and tell me if I'm missing something (probably I am).

**Comment by AKhranovskiy** [comment]
Hi,
I found a solution for first problem.
Conan loads a recipe that should be tested from cache. So it is somewhere in list of loaded modules. Test recipe has requirement to recipe that is tested. This requirement has location of sources in cache. So we have location of sources, and module that is loaded from there. Let's just find it in the list, check that it has all required names (just in case) and use it.
Not ideal, but works well.

The latter problem I cannot reproduce anymore, any cases I had before works fine. I suppose there was problem with my recipes.

I think the issue may be closed.
