### ISSUE TITLE
[bug] changelog documentation

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#5161]
hi there,
I have found a real severe bug :).

On the current [ChangeLog site](https://docs.conan.io/en/latest/changelog.html) it states:

> 1.15.1 (16-Mayo-2019)

[image](https://user-images.githubusercontent.com/8578342/57926594-fbc14980-78ab-11e9-8db9-ddf2ffcb4714.png)

**Comment by lasote** [comment]
hehehe, Thanks for reporting. It is pushed now.
