### ISSUE TITLE
Return errorcode 6 when settings are constrained to not support the current environment

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#5163]
There are two approaches to restrict the environment a recipe is working for: [Constrain Settings and Options](https://docs.conan.io/en/latest/mastering/conditional.html?highlight=conaninvalidconfiguration#constrain-settings-and-options)

When using the first approach and raising a `ConanInvalidConfiguration` Conan returns with errorcode 6. This could be further processed by scripts/CI perfectly. However the second approach with constraining the settings does not return with errorcode 6, but results in an [error](http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting) and errorcode 1 instead.

Is there a reason why both return with different behaviour? It would be perfect if both would return with errorcode 6, so developers could use both methods and scripts/CI can react on that in the same way.

**Comment by lasote** [comment]
I think you are right, make sense to return 6 too. Do you agree @memsharded ?
I've open a PR with the fix and assigned to the release.

**Comment by fourbft** [comment]
Conan version 1.6.1 handles constrained settings correctly now, when calling "create" (returns error code 6 on unsupported environments), but "info" still returns error code 1 in such a case.

**Comment by monsdar** [comment]
@lasote or @memsharded: Could you reopen the issue? It seems that it's only partially implemented, at least `conan info` is missing this return code.

**Comment by monsdar** [comment]
I did a PR which right now only tests for the issue...
