### ISSUE TITLE
[Question] Have a single package support multiple settings (i.e. Have one package be compatible with multiple compiler versions)

### ISSUE THREAD

**Issue by JigsawCorp** [conan-io/conan#5169]
To help us debug your issue please explain:

Hi,

I would like to know if there is a way to create a package that supports multiple settings **for pre-built binaries**. What I mean by that is it it possible to have one package be the same for VS 2013, 2015, and 2017? Is there a way to instead of giving a single value for a setting to give an array? Can we for example create a package that has an array of compiler versions instead of having to create one package for each version even if they have the same binaries? 

My use case is that I have some pre-packaged binaries that are compatible for VS 2013, 2015 and 2017, but not 2019. I would like to have one package that supports compiler versions 2013, 2015 and 2017 and then another package just for VS 2019. When doing `conan export-pkg`, there doesn't seem to be a way to list multiple values for a single setting. Is this something that is currently supported or not?

Thanks!

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, this is totally doable, via the ``package_id()`` function: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html

The idea is that you still have one input setting, with a given value. But the package_id() can produce the same binary package ID as other compilers would, then reducing the binary space with your custom logic. This can apply to the compilers you wont. The ``package_id()`` logic is irrespective of the creation command, it could be either ``create`` or ``export-pkg``.

Please have a look to that link and tell me if it helps. Thanks.

**Comment by JigsawCorp** [comment]
@memsharded 

Thanks for the reply! 

What you provided does answer my question!
