### ISSUE TITLE
Proxy settings are not correctly processed

### ISSUE THREAD

**Issue by trulede** [conan-io/conan#5170]
I've noticed that proxy handing is not working, system supplied proxy settings are being replaced by a call to `urllib.request.getproxies()` which returns proxy settings with modified names into `self.proxies` (i.e. "no_proxy" becomes "no"). This causes later code to break because it assumes that `self.proxies` is holding conan.conf settings, rather than modified system settings, and then proceeds to remove the valid system proxy settings from the environment. 

I will submit some changes for review.

To help us debug your issue please explain:

- [ X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi, I took a look at the PR and I think it makes sense. Our big comments about the usage `urllib.request.getproxies()` helps. I expected this issue to raise eventually.

**Comment by memsharded** [comment]
This has been fixed by https://github.com/conan-io/conan/issues/5170, is that correct @trulede ?
