### ISSUE TITLE
[question] Reusing sources from another package

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5172]
To help us debug your issue please explain:

Conan 1.15.1

Hi!

I've started to look into [gcc](https://github.com/gcc-mirror/gcc) project which contains a bunch of libraries. To provide a GCC package in the future, we could create a modular project, like Manu Sanchez made for LLVM.

However, gcc is big, just the tar.gz is 100MB and downloading the same source to build small libraries I think is not a good approach.

So I have some ideas:
- Separate gcc sources in small tar files and upload them to Bintray (e.g. bzip2)
- Create a package which contains gcc source files. We could skip source() step, reusing source files from the package
- Use development flow and share the source folder among the packages.

But I'm not sure ... Is there any good idea which could help saving time and disk?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Johnnyxy** [comment]
Hi there,
I have/had a similar challenge in a project. I have to build different libraries. Each library defines several interfaces (classes). All interfaces are generated code from IDL files. 
The bodies of the classes/function in these libraries share a common code base with a SDK. The SDK has CMake scripts, header files, etc. which are used to generate the libraries. The libraries themselves have almost no Python/CMake/... code.
This way I can build libraries with different classes but use the same code for common functionalities.
Now the SDK is a separate recipe that is defined as ```self.info.header_only()```. To use the SDK all libraries ```self.build_requires``` it. 
With this approach I can access the header files (as source code) in other projects.

This is similar to your second idea. I would go with that as with this you could benefit from the fact that it is a package and later if it is necessary you could even prebuilt something or do some other logic that prepares the source.

**Comment by lasote** [comment]
> Separate gcc sources in small tar files and upload them to Bintray (e.g. bzip2)

But these should be independent packages, actually, bzip2 exists already.

> Create a package which contains gcc source files. We could skip source() step, reusing source files from the package.

But eventually, you are downloading the sources the same way.

> Use development flow and share the source folder among the packages.

Sure, for the package development many things can be done to improve.

I won't focus on package gcc right now, to be honest.

**Comment by memsharded** [comment]
Closing this as outdated and not planned anything specific for this.
Conan already has some alternatives to improve this:

- A dedicated file cache, shared even among different caches, not only different packages, it will only download once
- Still, if sources want to be put inside a Conan package, it is also possible. Probably not worth the complexity, but possible.
-
