### ISSUE TITLE
issue inheriting 'scm' attribute with python requires

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#5181]
Conan version 1.14.4

I want to use python_requires to share the setting of the scm attribute across several recipes.

**pkg recipe:**
```
from conans import ConanFile, python_requires, tools

baseline = "Base/1.0.0@my-baselines/test"

# recipe inherits properties from the conanfile defined in the baseline
class ModuleConan(python_requires(baseline).get_conanfile()):
    name = "module_name"
    version = "1.0.0"
```

**base file:**
```
def get_conanfile():
    
    class BaseConanFile(ConanFile):
        scm = {
            "type": "git", 
            "url": "auto",
            "revision": "auto"
        }
    
    return BaseConanFile

class Baseline(ConanFile):
    name = "Base"
    version = "1.0.0"
```

When running `conan create . <ref>` on the pkg recipe, conan returns:
ERROR: The conanfile.py defines more than one class level 'scm' attribute

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Yes. I confirmed the bug. I'm trying to open a PR and assign to next release.
