### ISSUE TITLE
How to configure a remote Artifactory conan repository?

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#5182]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

So, based on [this](https://www.jfrog.com/confluence/display/RTF/Conan+Repositories) blog post Artifactory 6.10 has implemented the remote/virtual repositories for conan however I cannot make it work. 

I have Artifactory Pro, version 6.10, installed on server A, then on server B I have installed the C++ CE edition, version 6.10 as well. I can create a remote conan repository on instance B which points to my conan repo on instance A. The test button seem to work and I can even browse the packages on A though the web service on B but all packages have this message:

![image](https://user-images.githubusercontent.com/4864412/58023411-b8e6b800-7add-11e9-8b66-3b6cfdc1e408.png)

Which seems ok, I am expecting them to be cached as soon as instance B receives the request for that package, right?

However when I add a new conan remote on my machine which points to remote conan repo, on instance B, it does not want to find the package and returns

    Unable to find 'package_name` in remotes

In the blog they have mentioned this (which seems very odd but whatever):

![image](https://user-images.githubusercontent.com/4864412/58023196-352ccb80-7add-11e9-95fa-8f2785f5dec2.png)

So naturally I created a new virtual conan repo, on instance B, and aggregated the remote conan repo. Then added the new virtual repo as a new remote on my machine but it still cannot find the packages.

So, my question is what am I missing? How can I make Artifactory on instance B to proxy requests to server A and also cache the results?

BTW, this is my current settings for the remote conan repo on instance B:

![image](https://user-images.githubusercontent.com/4864412/58023619-36122d00-7ade-11e9-8ccd-3a54ff4926cb.png)

**Comment by lasote** [comment]
Have you activated the [revisions mechanism](https://docs.conan.io/en/latest/mastering/revisions.html#how-to-activate-the-revisions) at the Conan client?
The remotes and virtuals work only with the Artifactory Rest API v2 that will be used only with the revisions activated.

**Comment by AliAskari** [comment]
Yes, I had to. I was getting the following error:

    ERROR: The remote at 'http://address-instance-B/artifactory/api/conan/conan-virtual' only works with revisions enabled. Set CONAN_REVISIONS_ENABLED=1 or set 'general.revisions_enabled

**Comment by lasote** [comment]
Ok. I'm going to try to reproduce the issue.

**Comment by lasote** [comment]
Cannot reproduce the issue. I created a remote in the CE and a local one at a PRO. I can resolve the package perfectly.

**Comment by AliAskari** [comment]
Hmmm, interesting! Just for testing, I created a remote on the CE edition and pointed it to bincrafters: https://dl.bintray.com/bincrafters/public-conan.

These are the packages I see in my Artifactory instance:

![image](https://user-images.githubusercontent.com/4864412/58031700-edaf3b00-7aee-11e9-8433-b1b41651ac96.png)

I add the conan remote and then tried to install abseil

    conan remote add bintray-remote http://private-address/artifactory/api/conan/bintray-remote

then tried to install abseil:

    conan remote search abseil/*@bincrafters/stable  # returns not found
    conan install abseil/20180600@bincrafters/stable -r=bintray-remote

 but it fails:

![image](https://user-images.githubusercontent.com/4864412/58033294-39171880-7af2-11e9-8a05-960405975473.png)

What am I missing here?

**Comment by lasote** [comment]
I just tried and it is working, the URL you are using is wrong, click on the "setmeup": https://api.bintray.com/conan/bincrafters/public-conan 
It is very slow (don't know why) but it is workiing

**Comment by AliAskari** [comment]
Everything seemed to work after restarting the server community edition server, not sure what was going wrong. Thanks!
