### ISSUE TITLE
[question] No progress bar in Git bash (Windows)

### ISSUE THREAD

**Issue by jokram** [conan-io/conan#5186]
When running the command `conan download tdm-gcc/5.1.0@dev1/testing -r dev1_snap` from a Git Bash on Windows there are no progress bars:
```
Downloading conanmanifest.txt

Downloading conanfile.py

tdm-gcc/5.1.0@dev1/testing: Getting the complete package list from 'tdm-gcc/5.1.0@dev1/testing#0'...
tdm-gcc/5.1.0@dev1/testing: Downloading tdm-gcc/5.1.0@dev1/testing:456f15897172eef340fcbac8a70811f2beb26a93
tdm-gcc/5.1.0@dev1/testing: Retrieving package 456f15897172eef340fcbac8a70811f2beb26a93 from remote 'dev1_snap' 
Downloading conanmanifest.txt

Downloading conaninfo.txt

Downloading conan_package.tgz

....
tdm-gcc/5.1.0@dev1/testing: Package installed 456f15897172eef340fcbac8a70811f2beb26a93
```

When running the same command from a DOS prompt then the progress bars are displayed:
```
Downloading conanmanifest.txt
[==================================================] 58B/58B
Downloading conanfile.py
[==================================================] 635B/635B
tdm-gcc/5.1.0@dev1/testing: Getting the complete package list from 'tdm-gcc/5.1.0@dev1/testing#0'...
tdm-gcc/5.1.0@dev1/testing: Downloading tdm-gcc/5.1.0@dev1/testing:456f15897172eef340fcbac8a70811f2beb26a93
tdm-gcc/5.1.0@dev1/testing: Retrieving package 456f15897172eef340fcbac8a70811f2beb26a93 from remote 'dev1_snap'
Downloading conanmanifest.txt
[==================================================] 395.4KB/395.4KB
Downloading conaninfo.txt
[==================================================] 234B/234B
Downloading conan_package.tgz
[==================================================] 129.0MB/129.0MB
Decompressing conan_package.tgz: 100%|¦¦¦¦¦¦¦¦¦¦| 123M/123M [00:09<00:00, 13.1MB/s]
tdm-gcc/5.1.0@dev1/testing: Package installed 456f15897172eef340fcbac8a70811f2beb26a93
```
==> Is there a way to get the progress bars also in Git Bash?

Conan version: 1.15.0
OS: Windows 10 Enterprise
OS Version: 1709
Python: 3.7.2
Git: 2.20.1.windows.1

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I've no idea. When calling `os.system(...)` probably it is detecting no tty and not printing some things. About the win git, we would need to check.

**Comment by jokram** [comment]
I've just had a look in the source code:
https://github.com/conan-io/conan/blob/0b7b3cab7361cc45c212d8a21333b7f5e19de093/conans/util/progress_bar.py#L21-L24

This confirms your assumption. But it's not clear why Git Bash is identified as non-terminal.

**Comment by jokram** [comment]
One correction: Calling the command from Python via `os.system(...)` also prints the progress bar if the script is called from a DOS prompt => I'll fix that in the original description.

**Comment by SSE4** [comment]
@jokram seems to be a limitation of pythons `isatty` implementation, which needs a patch:
https://github.com/msys2/MINGW-packages/pull/2675/files

**Comment by memsharded** [comment]
Progress bars have been removed in Conan 2.0 because of problematic and adding too much complexity to code. Closing this as not planned.
