### ISSUE TITLE
[editable] mode not working with workspaces

### ISSUE THREAD

**Issue by joaquin-herrero** [conan-io/conan#5191]
Using some editable packages on a workspace with cmake_multi generator results on "Library ${_LIBRARY_NAME} not found in package, might be system one", not adding the editable package abs path to CONAN_FULLPATH_LIBS. Since CONAN_LIB_DIRS is also empty when calling link_directories on conan_global_flags macro it is impossible to link with editable packages.

I'm using global variable approach and conan_target_link_libraries macro. CMakeLists.txt is including the conanbuildinfo_multi.cmake.

I think CONAN_LIB_DIRS on conan_global_flags may use a generator expression with both CONAN_LIB_DIRS_DEBUG and CONAN_LIB_DIRS_RELEASE directories. The conan_find_libraries_abs_path should manage whether a library is not built yet due to editable mode too.

My configuration is:
Conan 1.15.1
CMake 3.14.4
Visual Studio 2019 / XCode
Windows 10 / OSX 10.14

**Comment by joaquin-herrero** [comment]
I created a custom generator which is a copy of the conan's cmake_multi with the fixed cmake_common.py file to get the job done.

You can have a look [here](https://github.com/joaquin-herrero/conan-custom-cmake_multi-generator)

I have tested it on Windows/OSX, should also work on Linux too. If you want I can create a PR with the fix.

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
