### ISSUE TITLE
conan new template recipes

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5192]
A use case where a team is creating many packages for their own libraries, and the recipes are very similar, it is useful to have the possibility to use a pre-defined template for the ``conan new`` command.

**Comment by uilianries** [comment]
Very useful! Bincrafters has [conan-templates](https://github.com/bincrafters/conan-templates) which is a collection of recipes.

This new feature could be used with conan config, like installing company/team templates in ~/.conan/templates.
