### ISSUE TITLE
Conan is slow to run

### ISSUE THREAD

**Issue by mplatings** [conan-io/conan#5198]
Each invocation of conan takes over a third of a second. In our CI system we need to make many calls to conan, so this adds up to be a noticeable portion of the overall build time.

A little digging reveals that the time is almost entirely taken up by imports. On Ubuntu 16.04 with Conan 1.15.1 in a Python 3.7 virtual environment, on a fearsomely powerful machine:

```bash
time python -c 'import conans'
python -c 'import conans'  0.36s user 0.04s system 100% cpu 0.396 total
```

Python 3.7 allows easy profiling of import time (https://bugs.python.org/issue31415). Running `python3.7 -X importtime -c 'import conans' 2>&1 | less` doesn't identify any one culprit, although the requests module is a significant contributor to the overall time.

I have no idea if this is a reasonable suggestion, but maybe the Python code could do imports more lazily?

e.g. instead of:
```python
import requests
def func():
    requests.something()
```
do
```python
def func():
    import requests
    requests.something()
```

Thanks for an otherwise awesome tool :)

----

To help us debug your issue please explain:

- [✓] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [✓] I've specified the Conan version, operating system version and any tool that can be relevant.
- [✓] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @mplatings 

The truth is that we tried that approach in the past, but the speed up was almost negligible, and the code was dirtier, so we reverted to normal imports. Also, the conan call itself might take 0.3 secs just for the imports, but the real time-consumer is loading the dependency graph and all the recipes, which is an operation that most commands will do. This might take a bigger chunk of time, like a few seconds for graphs with one hundreds nodes. Most of the time is used to load from disk the package recipes and parse them, so nothing that can be vastly improved.

If requests is indeed a big contributor, then, it might be possible to encapsulate it and have some improvements. I am labeling this as "look into" to research this.

> Thanks for an otherwise awesome tool :)

You are very welcome :) :) :) Thanks for the feedback

**Comment by mplatings** [comment]
Thanks @memsharded. As a workaround, instead of using conan as a separate process, would if be reasonable to call conans.client.command.main() repeatedly from a Python script, so we only pay the import cost once?

**Comment by memsharded** [comment]
Hi @mplatings 

Yes, that is possible, I see no problem with that.

Actually, there is a python api in ``conan_api.py`` which could be more convenient to call it directly from python in a programmatic way. The only thing is that it is still not released as stable, so it might change. It is not that we change it wildly, but still suffers some minor breaking changes from time to time. So depends on your trade-offs you might want to give it a try or use ``command.main()`` as entry point.

**Comment by mplatings** [comment]
Using the API worked well, but I discovered a performance bug in Artifactory.
Using Conan's logging facility I found that accessing the `latest` REST endpoint took over half a second for each dependency. Here's the line from the log file:
`{"_action": "REST_API_CALL", "duration": 0.5114703178405762, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.15.1 (Python 3.7.3) python-requests/2.22.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1559059613.903459, "url": "http://localhost:8081/artifactory/api/conan/conan/v2/conans/myproject/0.0.0-3/armcompiler-generated/testing/latest"}`
I've reported this to service@jfrog.com - I'll be impressed if they're as responsive as you are :)

**Comment by memsharded** [comment]
Hi @mplatings 

Thanks for the kind words :)

Great that you reported, I think it is also worth to file a JIRA ticket https://www.jfrog.com/jira/projects/RTFACT/issues, easier to track.

**Comment by mplatings** [comment]
Done, thanks for the suggestion: https://www.jfrog.com/jira/browse/RTFACT-19290

**Comment by aleksa2808** [comment]
Reached this problem as well with a CCI-like repository of recipes. A common operation there is to go through all recipes/versions and export them, create lockfiles, etc. For around 30-40 packages (some with multiple versions), exporting + locking all by calling conan from the command line took around a minute on my machine. Then I tried using `conan_api` directly and the whole thing took less than 10s🤔🤔.

**Comment by memsharded** [comment]
Conan 2.0 will do 2 things to improve these things:

- Commands and api will be modularized, that should reduce the python imports
- We will document and stabilize the python api (maybe the stabilization would be done in 2.1, 2.2, not directly in Conan 2.0, as it is not critical for 2.0 launch)

**Comment by memsharded** [comment]
Conan 2.0 is now in beta, it includes a Python API, that would solve this issue. Keep tuned to https://docs.conan.io/en/2.0/index.html for updates in the documentation of this API

**Comment by haferburg** [comment]
Fixed link: https://docs.conan.io/2/index.html
https://docs.conan.io/2/whatsnew.html#new-public-python-api
