### ISSUE TITLE
[hooks] Provide a post_remove hook

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#5199]
In issues like #5187 and #2593, Conan fails to remove folders in Windows.

Some users (@tonka3000) suggested the idea of using a PowerShell command in Windows which could work but seems a bit fragile.

As a way to implement this feature, I think it could be useful to create a ``post_remove()`` entry point for Hooks and create a hook that performs that PowerShell call.

**Comment by memsharded** [comment]
Sounds more like a hacky workaround to an underlying issue. Hooks shouldn't be used that way, and the original issue should be improved if possible. I am fine with the ``post_remove()`` entry point, but I think that an "official" hook that does a remove of the package shouldn't be a thing.

**Comment by danimtb** [comment]
Mostly a duplicate of #3760
