### ISSUE TITLE
Build command path problems

### ISSUE THREAD

**Issue by mnowy** [conan-io/conan#520]
I think that "conan build" should allow to pass -s and -o arguments like "conan install" does.

How can I build my project with "conan build" in Debug mode if I can't pass "-s build_type=Debug" argument to "build" command?

Of course I can modify [settings_defaults] in conan.conf every time I wanna change build_type but I think it isn't designed for this purpose.

**Comment by memsharded** [comment]
It doesn't work that way. The settings affect all the dependencies, you can't just build without installing dependencies for those settings. The actual ``conan build`` command is very simple, it just call the ``build()`` method but does nothing else. It takes all the configuration from the current ``conaninfo.txt`` generated by the install. 

So the workflow is always:
```bash
$ conan install -s build_type=Debug
$ conan build
$ conan install -s build_type=Release
$ conan build
```

You can't just change the settings for your current project, because the dependencies won't match and they will typically won't link against your project binaries.

**Comment by mnowy** [comment]
Ok that makes sense.

But now I have another problem. True commands to use with VS are
$ conan install -s build_type=Debug -s compiler="Visual Studio" -s compiler.runtime="MDd"
$ conan build
$ conan install -s build_type=Release -s compiler="Visual Studio" -s compiler.runtime="MD"
$ conan build

It's a little bit too much writing every time I want to change build from Release to Debug.

I tried to create build-debug and build-release folders to run "conan install -s ..." command only once so I can build my poject like this "conan build .." from myproject/build-release or myproject/build-debug.
But then I fall into another problem. My build function is inconsistent with build and test_package commands. Inside of my build function there is something like: "msbuild myproj.sln". And now when I try to do: "conan build .." msbuild throws "MSBUILD : error MSB1009: Project file does not exist." and "conan test_package .." works just fine. 

Do you have any idea how can I workaround that problem?

**Comment by memsharded** [comment]
Yes, a couple of things here. The first one is there is a feature request #405, #271, #489 for creating profiles, that are basically a name for a set of settings, that would reduce the writing.

The second one, it is not completely clear to me, I think it should be a paths issue. In theory it is possible to do that. It would be nice to be able to debug it, do you have a setup I can try? Is it public?

**Comment by mnowy** [comment]
Simplest way to reproduce my second problem is to install i.e hello project. 
```conan install Hello/0.1@memsharded/testing --build```
Then go to folder ```cd %userprofile%/.conan\data\Hello\0.1\memsharded\testing\build\908a20ec6c6293206044e5b119cc87e0c3c491e8\hello``` folder and invoke:
```conan build ..```
It won't build because of path error.

Then try to do:
```cd .. && conan build```
Project will build successfuly.

I think that this is inconsistent with all other conan commands which are independent from your current  folder.

Basically when you invoke ```conan build pathToConanFileFolder``` you should be able to run it from any path and as long as pathToConanFileFolder leads to proper conanfile.py it should build your project.

**Comment by memsharded** [comment]
Ok, I see, will try when possible, thanks for the feedback!

**Comment by mnowy** [comment]
You're welcome. Shall I close this issue and open different one with ```conan build ...``` case?

**Comment by memsharded** [comment]
Not necessary, I just renamed the issue. Thanks!

**Comment by memsharded** [comment]
The issue to track progress of profiles is: https://github.com/conan-io/conan/issues/524

**Comment by memsharded** [comment]
I think that I might know what is happening.
The "hello" example is very simple and naive, and it is not prepared for an out-of-cache build. It uses the following code to build:
```python
def build(self):
       cmake = CMake(self.settings)
       self.run('cd hello && cmake . %s' % cmake.command_line)
       self.run("cd hello && cmake --build . %s" % cmake.build_config)
```

The actual recommendation for the build code, as described in the docs would be more like:
````python
def build(self):
      cmake = CMake(self.settings)
      self.run('cmake "%s" %s' % (self.conanfile_directory, cmake.command_line))
      self.run('cmake --build . %s' % cmake.build_config)
```

You can see the difference is that the second one is using ``self.conanfile_directory`` which points to the folder containing the ``conanfile``, and thus allowing building from any path. Please, try the second approach in your package and tell if it it works. Thank you!

**Comment by mnowy** [comment]
Yes it works. Didn't know about ```self.conanfile_directory```. Thank you.

**Comment by memsharded** [comment]
Great, thanks for telling and closing the issue!
