### ISSUE TITLE
[bug] access denied to file

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#5205]
Hi there,
I have some reicpes which happen to fail occasionally with an error.

> PermissionError: [WinError 5] ...

All these recipes have in common that they are downloading one or more files (mostly one) from a FTP server, unzip the downloaded files and then deleting them. After that sometimes an extracted subfolder gets renamed (like "zlib-1.2.11" -> "src").

The recipe code in question:
```python
    def source(self):
        ...
        tools.unzip(str(source_filename))
        os.unlink(str(source_filename))
        os.rename('somepath', 'some_other_path') # ERROR here
```

This happens with the official zlib recipe from bintray too (required when building boost as libs).

Workaround: restarting building the recipe

I am using:
- Conan 1.15.1
- Windows 7 x64
- Python 3.7.2

EDIT:
On the machine I am using there is a firewall and virus scanner running. It _could_ be that this could interfere with the instantaneously folder rename.

**Comment by jgsogo** [comment]
Which is the command that fails?  Is it a `conan create/install...` running in the cache or running local commands?

**Comment by Johnnyxy** [comment]
The recipes are built as dependencies when using ```conan install```. I do not recall if this happened with ```conan create``` too as the recipes are dependency builds.

It runs in the cache.

**Comment by jgsogo** [comment]
This is going to be a hard error to debug or even to reproduce consistently. I would not have expected it in the cache because Conan is removing the source folder before calling the `source()` method (the folder doesn't exist or is marked as dirty and removed).

I find many issues like this one on the internet, but not a silver bullet 😕

**Comment by Johnnyxy** [comment]
In general I think the problem is related to the unzipping of the downloaded archive.
```python
tools.unzip(str(source_filename))
```
After that an extracted subfolder will be renamed. But this failes sporadically.
This is usually because some process still has a handle open somewhere in the the subfolder tree.

I did not look into the code that extracts the archive if there could be a hint what is going on.

It really could be a problem with a virus scanner. It maybe is still processing the extracted files. But as this happens with the official zlib recipe too and zlib sources are not that big it is strange.

As the problem pops up sporadically but reliably often I will test this with the good old ```sleep``` directly before the renaming. :)

**Comment by SpaceIm** [comment]
> As the problem pops up sporadically but reliably often I will test this with the good old sleep directly before the renaming. :)

It always happen on my corporate windows 10 computer (with invasive McAfee) for big packages, and randomly for medium packages. Indeed, I solve this issue by adding `time.sleep(<few seconds>)` in export/conanfile.py

**Comment by Johnnyxy** [comment]
@SpaceIm 
Exactly the same here. I am using 3 seconds.

**Comment by SpaceIm** [comment]
I've just realized that indexing was enabled in my user directory. Seems to work fine if .conan directory is excluded from indexing.

**Comment by Johnnyxy** [comment]
Do you mean Windows Search Indexing?

**Comment by SpaceIm** [comment]
Yes

**Comment by Johnnyxy** [comment]
This service is completly deactivated on my dev machine :). But at the moment I cannot say if this was done lately or some time ago (cause of group policy rules).
As I am using the 3 seconds delay for some time now and the service is deactivated I would have to test this explicitly again without delay.

**Comment by jgsogo** [comment]
Wow! Thanks for the investigation. I think that the best we can do then is to rename the issue so it will be more descriptive and easy to find if someone looks for something similar... but IMHO we shouldn't add the _sleep_ to Conan itself, so we can close this issue, don't you think so?

**Comment by Johnnyxy** [comment]
I saw something related already serval times. That people advised to disable the Search Indexing or at least make some exclusions to the Conan folders.

I also do not think that a general _sleep_ would be adviseable as this is **never** the right way to go with synchronization problems.

We can close this and if someone has further insights or additional informations he/she can comment on this.
