### ISSUE TITLE
Error in package_info() when installing opencv

### ISSUE THREAD

**Issue by skatzl** [conan-io/conan#5208]
Hello everybody,

I'm getting an error when trying to install opencv with conan from conan-center with the following settings:

Conan profile:

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

Conanfile.txt:
```
[requires]
opencv/3.4.5@conan/stable

[generators]
cmake 
```

Output from console (error only, the full output is attatched in 
[conanOpencvError_consoleOutput.log](https://github.com/conan-io/conan/files/3211904/conanOpencvError_consoleOutput.log)
):
```
opencv/3.4.5@conan/stable: Downloaded package revision 0
ERROR: opencv/3.4.5@conan/stable: Error in package_info() method, line 257
        self.add_libraries_from_pc('gtk+-3.0')
while calling 'add_libraries_from_pc', line 227
        libs = [lib[2:] for lib in pkg_config.libs_only_l]  # cut -l prefix
        ConanException: pkg-config command ['pkg-config', '--libs-only-l', 'gtk+-3.0', '--print-errors'] failed with error: Command 'pkg-config --libs-only-l gtk+-3.0 --print-errors' returned non-zero exit status 1.
```
Same error for other versions of opencv available via conan-center.
Seems to me to be a bug. Or are there any other suggestions?

Cheers, katzl

**Comment by skatzl** [comment]
Forgot to say: Same error for other versions of opencv available via conan-center.

**Comment by Johnnyxy** [comment]
As this is a package from conan-center there is a seperate bug tracker for this ([have a look here](https://github.com/conan-community/community/issues)).

This bug tracker here is only for Conan related issues not for Conan recipes/packages problems.

**Comment by skatzl** [comment]
Alright. I opened an issue in link you suggested.
Thanx! Katzl
