### ISSUE TITLE
Better tool management

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5210]
Idea from https://github.com/bincrafters/conan-fmt/pull/20/files

```python
    def build_requirements(self):
       if not tools.which("cmake"):
           self.build_requires("cmake_installer/[>3.1]@conan/stable")
```

It is nice, but it would be better if cmake >3.1 could be checked in the system, as right now, with a cmake 2.8, that approach will fail. The idea would be something like:

- Recipes can declare "build_tools", like ``cmake/[>3.1]``
- Those are validated against system-installed tools (can be a tools.conf file in the conan cache)
- Conan will resolve build_tools to system tools defined in tools.conf, or alternatively to conan packages, that it will manage to install (also configurable at tools.conf), otherwise it will error with a clear message.

Just some quick ideas, to spark discussion

**Comment by DodoMomo** [comment]
I'm not sure i understand you correctly, will the user have to manually create a list with all of the build tools and their versions?

**Comment by memsharded** [comment]
Closing this as outdated.

Conan 2.0 implemented ``[system_tools]`` for this purpose.
