### ISSUE TITLE
Is there a conan wrapper?

### ISSUE THREAD

**Issue by stefaneicher** [conan-io/conan#5211]
Hi,

**Short:**
doe a "conan-wrapper" exist similar to "maven-wrapper?

**Longer:**

I am coming back to the C/C++ programming language after a long time working in Java.

in Java-World the most popular build tool is maven and there exists maven wrapper.
See:
https://www.baeldung.com/maven-wrapper
https://github.com/takari/maven-wrapper

This allows that the build tool ( in this case does not need to be installed on the computer) and thus automation and reproducibility is very nicely achievable.

The question is if there exists such wrapper conan?

Regards Stefan

**Comment by memsharded** [comment]
Hi @stefaneicher 

Conan is not a build tool, it is a package manager, and it is decoupled from the build system, which you should be installing in your system anyway.

There is a cmake wrapper for conan, to call conan from CMake, check https://github.com/conan-io/cmake-conan

Conan mostly manage your dependencies, and integrates (orthogonally) to build-systems. It has the concept of ``build_requires`` too, and it can contain packages for tools, like already existing ones for cmake or mingw. But not to bootstrap the whole development toolchain. Using Conan is a huge improvement regarding dependency and package management, but for C++ you still need to manage the rest of the ecosystem, specifically the build-system and compilers...

Does this answer your question?

**Comment by stefaneicher** [comment]
Hi @memshared,

Perfect yes, thanks very much. 
I will gain more experience with conan and would followup if it needed.
Regard Stefan

**Comment by memsharded** [comment]
Hi @stefaneicher 

Thanks for following up! I am closing this issue at the moment, but do not hesitate to comment or open new issues for further questions. Cheers!
