### ISSUE TITLE
conaninfo, conanbuildinfo, graph_info shouldn't be needed

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5213]
These files shouldn't be used anymore in Conan 2.0 and with `conan.lock` file.

**Comment by JigsawCorp** [comment]
It would be cool if there was a way to specify if you want it our not. I personnaly never took the time to figure out what these files were for, so I guess maybe they are not needed. I ended up having to make a script to manually delete them, which isn't ideal.

**Comment by memsharded** [comment]
Files already removed in ``develop2``. Only ``conan.lock`` remains, and that will also be revisited.
