### ISSUE TITLE
Cmake build helper + Intel Fortran

### ISSUE THREAD

**Issue by kylemacfarlan** [conan-io/conan#5216]
This is similar to #2747, but there isn't as elegant a workaround, so I thought it was worth opening an issue. 

Intel fortran doesn't understand the verbosity command, and it causes the build to fail. 
The workaround I came up with is this:

        cmake = CMake(self, parallel=False)
        command_line = cmake.command_line
        command_line.replace("/verbosity:%s" % cmake.msbuild_verbosity, "", 1)
        self.run('cmake "%s" %s' % (self.source_folder, command_line))
        self.run('cmake --build . %s' % cmake.build_config)`

Unlike #2747, no value that I pass to the msbuild_verbosity argument in the CMake constructor will prevent the command from being issued. It would be nice if there was some way to just remove the "/verbosity: ... " command from being issued at all.

**Comment by lasote** [comment]
Let's try to fix it for the next release.

**Comment by memsharded** [comment]
Fixed, now ``CMake(...., msbuild_verbosity=None)`` will completely remove the flag.

Will be released next Conan 1.16, thanks for reporting.
