### ISSUE TITLE
Conan remove --force is not graceful

### ISSUE THREAD

**Issue by rweickelt** [conan-io/conan#5226]
conan remove --force REFERENCE fails with an error message "ERROR: Recipe not found:" if REFERENCE does not exist in the cache. Conan should IMO behave similar to rm -f FILE and exit gracefully even if no matching package exists. Otherwise I need to query first whether the package exists. This used to work in older versions of Conan (1.6).

Note that the current behavior is inconsistent.
- `conan remove -f PACKAGE/VERSION`still only prints the warning, but runs successfully
- `conan remove -f PACKAGE/VERSION@NAMESPACE/CHANNEL`  results in an error

**Comment by memsharded** [comment]
This could be considered breaking, as some users would consider this a mechanism to prevent against typos and other errors, when doing operations, specially in programmed CI.

We need to make more uniform all the command line arguments and UI, but this should probably wait until Conan 2.0, when we can introduce these changes in the current behavior.

**Comment by rweickelt** [comment]
It was graceful some **minor** versions back, at least in conan 1.6.

**Comment by memsharded** [comment]
Yes, that is true, sorry. I have verified, in Conan 1.6 it wasn't an error, it was printing 

```
(conanpip) λ conan --version
Conan version 1.6.1

(conanpip) λ conan remove hello/0.1@user/testing -f
WARN: No package recipe matches 'hello/0.1@user/testing'
````

Removing the 2.0 milestone, so it might be changed before 2.0.

**Comment by rweickelt** [comment]
Maybe related to #5297 ?

**Comment by rweickelt** [comment]
@memsharded , I think this should rather be treated as a bug than a feature request because it used to work and the current behavior is inconsistent.

**Comment by AbrilRBS** [comment]
Closing as solved in v2, which now has a consistent UX across its commands. Unless an internal assertion is broken, the command won't return an error, but the contents of what was removed can be programatically checked
