### ISSUE TITLE
Don't pass ConanFileReference object to conan_api, pass string

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5233]
https://github.com/conan-io/conan/pull/5176/files introduces a ConanFileReference via the conan_api, please fix.

**Comment by uilianries** [comment]
Why not accepting both? I know the API is unstable, but this will break some scripts from Bincrafters.

**Comment by memsharded** [comment]
Keep it simple and with the same interface, at least for now, until we properly discuss and design the api.

This shoudn't break anything it was just a new thing added in: https://github.com/conan-io/conan/pull/5176/files. The rest of the conan_api hasn't changed.

**Comment by uilianries** [comment]
Thanks! I have to agree, string is much simpler :smile:
