### ISSUE TITLE
Profiles for settings and compiler path

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#524]
Opening this issue to centralize the development of this feature requested in: #405, #489, #271 

It would be, probably in conan.conf, the definitions of profiles as a set of settings/options, plus maybe compiler paths to be automatically passed as CC/CXX variables.

**Comment by monsdar** [comment]
I would prefer the profiles to be configured in separate files. This way it is easier to e.g. share them between CI runners or what not. If they're defined in conan.conf it would be needed to edit that file to change it.

The default profile could be configured in conan.conf.

There could be a profiles directory where each file is placed into:

```
.conan
  - conan.conf   <- Here the default profile is defined
  - profiles
    - vs1532.profile
    - vs1564.profile
```

Usage: `conan install Foo/1.0.0@user/testing --profile vs1564`

**Comment by memsharded** [comment]
Yes, definitely good idea, they will be in separate files.
