### ISSUE TITLE
Question: attribute for the update option

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#5240]
Hello,

**Short question:** 
is there a way to know if there user has specified the option --update when running conan install ... inside conanfile.py ? 

**Long question:**
my import method looks like this:

```
def imports(self):
        tools.mkdir('my_deps_deploy_dir')
        with tools.chdir('my_deps_deploy_dir'):
            self.run('conan install my_deps/1.0.0@me/stable -s build_type=Release --update')
```

Note:
- my_deps is a runtime dependencies, it is not needed to compile my project.
- my_deps package have a deploy method, so running conan install will deploy my_deps to my_deps_deploy_dir

Now, I want to optimize this, as calling conan install with  --update option is heavy, basically I want to check if the user specified the option  --update when running conan install and pass it to my_deps's install command.

Thanks

**Comment by danimtb** [comment]
Hi @boussaffawalid,

**Short answer:**
There is no attribute in recipes to indicate the ``--update`` flag in a ``conan install`` command. That is a flag to update package a recipe by definition does not need this flag to create packages. Moreover, this could lead to irreproducible cases depending on the state of your cache, your remotes and if the --update flag was set or not.

**Long answer:**
Looking at your use case, I think you just want to get some resources from a dependency just for runtime. This is a common use case when building a final application. In this case, using normal dependencies as build_requires and the runtime ones as requires could be enough. Use the imports method to get the runtime files from the dependency or just use the information propagate through ``deps_cpp_info``.

Hope that makes sense! Thanks

**Comment by boussaffawalid** [comment]
I always wants to use the release config of my_deps even if I’m building debug, if there a way to do that?

**Comment by danimtb** [comment]
Alhought that is not a common flow supported by Conan, you can still achieve that from the command line with a setting flag specific to that package:

```
$ conan install . -s my_deps:build_type=Release
```

More information here: https://docs.conan.io/en/latest/reference/commands/consumer/install.html#settings

**Comment by boussaffawalid** [comment]
Thank you :)

**Comment by danimtb** [comment]
you are welcome! 😄
