### ISSUE TITLE
Options of a build requirement are not visible in a recipe

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#5243]
Consider the following 3 recipes: (copy to your terminal to execute)
```
cat >parent.py <<EOF
from conans import ConanFile
class ParentRecipe(ConanFile):
    name = "parent"
    version = "1.0"
    options={"opt1":[True, False], "opt2":[True, False],}
    default_options={"opt1":True, "opt2": True,}
EOF
cat >child_requires.py <<EOF
from conans import ConanFile
class ChildRequiresRecipe(ConanFile):
    name = "child_requires"
    version = "1.0"
    requires = "parent/1.0@user/channel",
    def build(self):
        self.output.warn("opt1 = {}, opt2 = {}".format(self.options["parent"].opt1, self.options["parent"].opt2))
EOF
cat >child_buildrequires.py <<EOF
from conans import ConanFile
class ChildBuildRequiresRecipe(ConanFile):
    name = "child_buildrequires"
    version = "1.0"
    build_requires = "parent/1.0@user/channel",
    def build(self):
        self.output.warn("opt1 = {}, opt2 = {}".format(self.options["parent"].opt1, self.options["parent"].opt2))
EOF
conan create parent.py user/channel -tf None
conan create child_requires.py user/channel -tf None
conan create child_buildrequires.py user/channel -tf None
```

I would expect the `child_buildrequires` recipe to have access to the options of the parent, but is has not. Its values are `None`.

Relevant output of `conan create child_requires.py`:
```
child_requires/1.0@user/channel: WARN: opt1 = True, opt2 = True
```

Relevant output of `conan create child_buildrequires.py`:
```
child_buildrequires/1.0@user/channel: WARN: opt1 = None, opt2 = None
```

**Comment by Johnnyxy** [comment]
Hi there,
I think what you are describing relates to my "issue" that I posted here: https://github.com/conan-io/conan/issues/4784

In a nutshell: You can access the options of all requirements but not of build_requirements.
@memsharded explained the reason behind this in a post in the linked [issue](https://github.com/conan-io/conan/issues/4784#issuecomment-487424384).

**Comment by jgsogo** [comment]
@madebr , if you don't mind, I will close this issue and we can move to the one pointed above. Thanks!
