### ISSUE TITLE
Mac: virtualrunenv should set DYLD_FRAMEWORK_PATH

### ISSUE THREAD

**Issue by Artalus** [conan-io/conan#5245]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] `Conan version 1.15.0`
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

We have a Qt4 package being built as a full-scale MacOS Framework instead of simply several `.dylib`s. We have a test binary linked against it and some other libraries, having dependencies like this:
```
$ otool -L test1.app/Contents/MacOS/test1
test1.app/Contents/MacOS/test1:
        @rpath/kek.framework/Versions/C/kek
        libjsoncpp.19.dylib
        QtGui.framework/Versions/4/QtGui
        QtCore.framework/Versions/4/QtCore
        /usr/lib/libc++.1.dylib
        /usr/lib/libSystem.B.dylib
```

If we run it from the "naked" shell, it causes expected errors about `.dylib`s not found:
```
$ ./test1.app/Contents/MacOS/test1
dyld: Library not loaded: libjsoncpp.19.dylib
  Referenced from: /private/tmp/ex/build/./test1.app/Contents/MacOS/test1
  Reason: image not found
Abort trap: 6
```

However once we activate `virtualrunenv`, `libjsoncpp.so` is found OK, but we still get problems with Qt:
```
(conanrunenv) $ ./test1.app/Contents/MacOS/test1
dyld: Library not loaded: QtGui.framework/Versions/4/QtGui
  Referenced from: /private/tmp/ex/build/./test1.app/Contents/MacOS/test1
  Reason: image not found
Abort trap: 6
```

Setting `DYLD_FRAMEWORK_PATH=${DYLD_LIBRARY_PATH}` fixes the problem and the app runs smoothly.

We are no Mac experts, especially regarding Conan libraries and the whole Framework system. Our Qt4 package is also heavily based on @ericLemanissier's [Qt5 package](https://github.com/bincrafters/conan-qt), so we might've missed something during the build. It seems to me that the `virtualrunenv` generator should set `DYLD_FRAMEWORK_PATH` as well as `DYLD_LIBRARY_PATH`, but I would be very glad for any MacOS experts to clarify if we aren't missing anything here :)

**Comment by danimtb** [comment]
Thanks for the suggestion @Artalus,

I think it sounds reasonable but I am not a MacOS expert at all so...
I have one doubt though: Is that Qt4 already a Conan package or is it installed in the system?

I am wondering why it is behaving differently from the other ones and why setting the DYLD_LIBRARY_PATH is not enough

**Comment by Artalus** [comment]
This Qt4 is packaged by us. Apparently in original conanfile there were
```
  elif self.settings.os == "Macos":
  args += ["-no-framework"]
```
that we missed, so I believe Qt on Mac is built as framework by default.

**Comment by danimtb** [comment]
I am not sure if I am getting it. Are you saying then that it was the fault of your recipe missing the ``-no-framework`` and thus the ``DYLD_FRAMEWORK_PATH`` is not needed?

**Comment by Artalus** [comment]
Not quite.

I am saying that if the library is built as a framework, then paths to those will not be propagated to `virtualrunenv`. Qt is the first library in my experience that does it, and it can be built the "usual way" - so in this specific case we specifically can use this "workaround".

But I assume there might be other libraries building as frameworks, and there might not always be an option to build as `.dylib` instead of `.framework`. I also assume some people might need to package pre-built `.framework`s.

So while the initial problem we had was solved on our side without any impact on Conan, there might be other cases where people would care about `DYLD_FRAMEWORK_PATH`.

**Comment by danimtb** [comment]
Understood. Thanks a lot for the clarification. This feedback makes Conan be better each release!
