### ISSUE TITLE
Conan create with missing build_require

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5247]
Given a simple graph where a recipe (`app`) _build requires_ a `tool` to be built, and starting with the following scenario: `app` binaries are already available in the cache, but `tool` aren't (you have removed them):

 * Running `conan create .` on `app` will tell that there is a package missing: `tool` is not available and you should use `--build tool`, then
 * Running `conan create . --build tool` will do nothing because `app` is already available in the cache and there is nothing to build (worst: it prints an error because `tool` is not in the graph)

When using `conan create`, should we always force building the root package?

**Comment by memsharded** [comment]
The first ``conan create .`` on app won't try to install the build_requires binaries from the server? I don't fully understand

**Comment by jgsogo** [comment]
There aren't remotes in my use case.

**Comment by jgsogo** [comment]
This is something that frustrated me for a moment, in order to make it to work you need to run `conan create . --build tool --build app`...

**Comment by memsharded** [comment]
Yes, exactly. The moment you add ``--build`` then you need to specify the ``--build=app`` too. This is an open issue for Conan 2.0, we will reconsider if changing this behavior. In some cases it can be useful that the package is not built if it is not necessary.

**Comment by memsharded** [comment]
This is not changing in 2.0, we are keeping the current behavior:
- There is a use case in which we don't want to build a new binary if it already exists one
- If the ``--build=current_pkg`` is always enforced, then achieving the above cannot be specified, there is no syntax for it.
