### ISSUE TITLE
Better error messages for conan package

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#525]
"conan package" command could print more precise error messages. Here is scenario I've used and didn't understand what am I doing wrong:

1. Create conanfile.py
2. Execute conan export user/testing
Messgage: "A new conanfile.py version was exported." - this message is ok
3. Execute conan package libname@0.1/user/testing
Message: "ERROR: 'conan package': Please specify --all or a package ID" - this message leads me to use --all parameter because I don't have any package ID in the beginning
4. Execute conan package libname@0.1/user/testing --all
Message: "ERROR: libname/0.1@user/testing does not exist" - this message in my opinion is not very helpful. Maybe it should say something like: "ERROR: libname/0.1@user/testing package does not exist, please create it using conan install <Full package reference> --build or conan test_package command"

**Comment by lasote** [comment]
"libname@0.1/user/testing" or "libname/0.1@user/testing"

**Comment by mnowy** [comment]
My mistake. It should be: "libname/0.1@user/testing".
But this leads to another problem.
I guess that ```conan package libname@0.1/user/testing --all``` should show syntax error and  ```conan package libname/0.1@user/testing --all``` should tell you how to create your package for the first time.

**Comment by memsharded** [comment]
Yes, ``$ conan package libname@0.1/user/testing --all`` already shows an error about the package reference being invalid. 
Agree on the the second one has to show better error messages

**Comment by memsharded** [comment]
Implemented in #570, will be released in next 0.14
