### ISSUE TITLE
conan download "-p" deprecation

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5250]
The same with `get` and `upload`, deprecate the `-p` in favor of full ref.

**Comment by jgsogo** [comment]
(Just for reference) Deprecation of `-p` in `upload` command: https://github.com/conan-io/conan/pull/5224

**Comment by DodoMomo** [comment]
I would like work on this issue.
I think It requires making 
```python
       try:
            pref = PackageReference.loads(args.pattern_or_reference, validate=True)
            reference = pref.ref.full_repr()
            package_id = pref.id
        except ConanException:
            reference = args.pattern_or_reference
            package_id = args.package
            if package_id:
                self._user_io.out.warn("Usage of `--package` argument is deprecated."
                                       " Use a full reference instead: "
                                       "`conan upload [...] {}:{}`".format(reference, package_id))
        else:
            if args.package:
                raise ConanException("Use a full package reference (preferred) or the `--package`"
```
into a function, what do you think?

**Comment by memsharded** [comment]
Yes, it would make sense to factorize out that common code to be used by the different methods. Thanks!

**Comment by DodoMomo** [comment]
Hello, I have noticed that `conan download` can actually receive multiple arguments for the `package`
parameter, and it seems that there's no way to do the same thing with full reference at the moment. 
What should I do in that regard?

**Comment by memsharded** [comment]
Uhmmm, good point.

there is the alternative:

```bash
$ conan download pkg/version@user/channel:package_id1
$ conan download pkg/version@user/channel:package_id2
$ ...
```

I think this would be a marginal use case, typically you want to do operations on all binaries, or just on one binary. Doing them on some binaries but not all should be pretty unusual.

cc/ @lasote for feedback about this UI

**Comment by lasote** [comment]
Yes. We deprecate the "multiple" in the same command. Simpler is better.
