### ISSUE TITLE
CONAN_ENV_XXX_XXX vs profiles

### ISSUE THREAD

**Issue by db4** [conan-io/conan#5269]
Suppose I need to override the default `compiler.libcxx` value via `CONAN_ENV_COMPILER_LIBCXX`. For the default profile
```shell
export CONAN_ENV_COMPILER_LIBCXX=libstdc++11
```
works well. But if I create another profile
```
include(default)
[options]
...
```
and use it as `conan -pr my_profile ...`, `CONAN_ENV_COMPILER_LIBCXX` value is just ignored. I understand why, but this is somewhat unexpected behavior, isn't it?

**Comment by memsharded** [comment]
These env-vars are a bit weird, I have just filed an issue to remove them in Conan 2.0: https://github.com/conan-io/conan/issues/5270, I don't think they have a real use case.

**Comment by memsharded** [comment]
At least it is correctly documented in the docs: https://docs.conan.io/en/latest/reference/env_vars.html#conan-env-xxxx-yyyy It is clear they apply only to the default profile.

What were you trying to achieve defining such env-var. I think it is tricky, hidden and problematic, that is why I suggest removing it. Could you please tell what is the problem you are trying to solve with them?  Thanks!

**Comment by db4** [comment]
> What were you trying to achieve defining such env-var. I think it is tricky, hidden and problematic, that is why I suggest removing it. Could you please tell what is the problem you are trying to solve with them? Thanks!

I can describe it but I now think I can solve it without 
CONAN_ENV_XXX_XXX variables. Removing them is OK for me. Closing the issue.

**Comment by memsharded** [comment]
Good to know, thanks for telling.
Yes, I think they will be removed in Conan 2.0, it is important to keep things as simple as possible.
