### ISSUE TITLE
-e var=val is not applied when conanfile is initialized

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#5272]
It seems that the environment variables passed with `-e` are not applied to the `conanfile` when it is initialized.  They do seem to be applied by the time the `configure` method is run.  It's not terribly difficult to work around, but at the very least, it violates the principle of least astonishment. 

```
from conans import ConanFile
import os

class BugDemoConan(ConanFile):
    name = "bug_demo"
    version = "0.1.0"
    
    _code_sign_file = os.getenv("CODE_SIGN_FILE")
    
    def configure(self):
        self.output.info(f"self._code_sign_file = {self._code_sign_file}")
        code_sign_file = os.getenv("CODE_SIGN_FILE")
        self.output.info(f"code_sign_file = {code_sign_file}")
```
`conan create . bug/bug -e CODE_SIGN_FILE=SOMEVALUE`
```
bug_demo/0.1.0@bug/bug: self._code_sign_file = None
bug_demo/0.1.0@bug/bug: code_sign_file = SOMEVALUE
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, it seems that the profile env-vars might need to be activated if we would like to see this behavior, lets consider this and see if it is possible and what would be the complexity.

However, this might not be the best practice, to initialize things loaded from env-vars at the class level. Remember that if possible it is better to avoid global state in recipes.  Using ``os.getenv("CODE_SIGN_FILE")`` inside recipe methods will work always, even if we want to have CODE_SIGN_FILE defined by a dependency ``package_info()`` method, but if we try to initialize it at class level, then it will only work with what is defined in the system, ignoring upstream definitions.

**Comment by jgsogo** [comment]
IMO this kind of global variables should not take into account _environment variables_ associated with the reference. That code is executed as soon as the recipe file is loaded (before instantiating an object), so I think it should only rely on the global environment. From my POV that is the expected Python behavior 🤷‍♂

**Comment by solvingj** [comment]
I think i agree with this statement.

**Comment by solvingj** [comment]
When a user passes `-e var=val`, they expect the variable to override global environment variables in the context of their conanfile.  This includes the whole conanfile, at all points of execution, from instantiation of the Conanfile class, and even in the context of code listed above the `class MyConan(conanfile)` declaration. 

Actually, my example only demonstrates the case where there was no variable, but now you've actually highlighted the bigger issue, that env vars passed via CLI will not override globals (again, only in the context of instantiation of the Conan class). 

`-e var=val` is an extremely convenient way to set environment variables for the process in a first-class cross-platform way in Conan (and Docker as well).  It's extremely unintuitive to say that: when passing environment variables this way, `os.getenv("var")` will return one value when called inside the functions of `conanfile.py`, but a different value (either `None` or something else) when called in the declaration of a `Conanfile` attribute.

**Comment by SSE4** [comment]
okay, the documentation actually says:
```
  -e ENV, --env ENV     Environment variables that will be set during the
                        package build, -e CXX=/usr/bin/clang++
```
so, it seems like environment variables are only guaranteed to be available within the `build()` method, right?
that probably means making them available on conanfile load time is an enhancement, WDYT @solvingj @memsharded ?

**Comment by solvingj** [comment]
Yes, if that has always been the designed behavior and what has been documented, then I guess it’s just an incorrect assumption on my part based on using docker. It would be an enhancement, but I’ll withdraw it since it would almost certainly be a breaking change.  We will use set/export variables instead.
