### ISSUE TITLE
Need to improve GCC OLD ABI COMPATIBILITY message

### ISSUE THREAD

**Issue by Ignition** [conan-io/conan#5273]
A simple usability and quality of life improvement. It is better to copy and paste a command given to you, rather than manual editing of a file. [see patch](/Ignition/conan/commit/45a57617610abd3a5b4bfc76a5596468cbab23e0)

**Comment by memsharded** [comment]
Yes, totally agree. The patch looks good, would you like to submit a PR with it? Thanks!

**Comment by memsharded** [comment]
Closed by #5275 will be released in 1.17
