### ISSUE TITLE
Uploading new versions of my package has made it disappear... I think

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#528]
Hello,

My package, small3d v1.0.5 seems to have disappeared from conan after my latest builds & uploads. For example this build:

https://ci.appveyor.com/project/coding3d/small3d/build/job/xjrtihf5hp0xygof

does not lead to the package appearing on the website, even though I relaunched it just to make sure.

(Btw, the latest version in my repository has uploads switched off, but the particular commit that corresponds to the above mentioned version has them on, and the log shows that it did try to upload  a package)

Is there anything we can do to solve this?

Thanks!

**Comment by memsharded** [comment]
I think we are having some problems with the indexing of the packages, that is why they don't appear on the web site. You should be able to retrieve them with conan install, though. Investigating it.

**Comment by dimi309** [comment]
That's true! I've just made a test and, indeed, the latest version is retrievable with "conan install".

**Comment by memsharded** [comment]
Indexer fixed, packages should appear in web search now, can you please check? Thanks!

**Comment by dimi309** [comment]
They are there indeed. I've noticed a few minutes ago. 👍

**Comment by dimi309** [comment]
So for me this is all fine. Unless you need it open, I suppose this issue can be closed.

**Comment by memsharded** [comment]
Yes, thanks for telling!
