### ISSUE TITLE
ERROR: No remote 'conan-local' defined

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#5281]
When deleting and re-adding a remote under a new name, all the packages which were downloaded from that remote become broken with this error. 

`ERROR: No remote 'conan-local' defined`

Perhaps there's a documented way to handle this error, but I didn't find it.  I remove all the packages in my local cache and they all re-download from the remote under it's new name.  

I remember seeing a lot of discussion last year about pinning packages to the remotes they came from.  It looks to me that this was implemented as an implicit feature, and this error is a negative side effect. Is there a first-class way to handle this issue?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Thanks for reporting Jerry.

Yes, it seems like a bug, lets try to fix it.

**Comment by memsharded** [comment]
I am having a look at this, and cannot reproduce. Find test (passing) here: https://github.com/memsharded/conan/commit/372e9a578e08d0c491a6b67502b2a43343e70b5b

I am trying it with the develop branch, but also works in Conan 1.15.2. which version are you using.

To inspect that it is failing, the shortest way would be:
- Have a package tracking a remote (either downloaded/installed or uploaded to it)
- Remove that remove
- Check that no remote related metadata is in the package ``metadata.json`` in the local cache folder.

Please tell about the version, and if you could try the above, it will help. Thanks!

**Comment by solvingj** [comment]
I'm on 1.15.0. 

The remote is still listed in metadata.json

I'm going to guess that I edited the remotes.json manually and that's not supported, because `conan remote rename` goes through all the `metadata.json` files it owns and updates them.  Is that correct?

```json
{
   "recipe":{
      "revision":"f3a19d0ea3965eb720afd514812949a0",
      "remote":"conan-local",
      "properties":{

      }
   },
   "packages":{
      "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9":{
         "revision":"ac6f3b18ec4eee1f63195b56a0e72044",
         "recipe_revision":"f3a19d0ea3965eb720afd514812949a0",
         "remote":null,
         "properties":{

         }
      }
   }
}
```
