### ISSUE TITLE
Conan Server not able to return packageIds

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#5290]
When doing a search like this: `conan search Boost* -r myRemote` we get the expected result (a list of packages starting with the name `Boost`. However when searching for a full reference: `conan search Boost/1.0.0@user/channel -r myRemote` we get the following error:

```
ERROR: Not found: http://conan-server:9300/v1/files/Boost/ALIAS/user/thirdparty/export/conanmanifest.txt?signature=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZV9wYXRoIjoiQm9vc3QvQUxJQVMvcmRlL3RoaXJkcGFydHkvZXhwb3J0L2NvbmFubWFuaWZlc3QudHh0IiwiZXhwIjoxNTU5NjM3NTIxLCJmaWxlc2l6ZSI6bnVsbCwidXNlcm5hbWUiOm51bGx9.TBdy9fgATC6a2XgwHupb--rAuI4qqUx5gLkgyxrVhNE. [Remote: myRemote]
```

This happens with every package. It just occurs on a single developer machine, all others work well.

System specs:
* OpenSuse 13.1
* Tested with different Python versions:
    * Python 3.6.5
    * Python 2.7.14
* Tested with different Conan versions:
    * Conan 1.14.5
    * Conan 1.13.0
* Conan remote is a conan server running with v1.3.3

This also fails commands like `conan create ...` or `conan install ...`, the error message then is something along the lines of `Cannot find dependency Boost...` .

```
[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = 50                  # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
default_profile = default
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True               # environment CONAN_SYSREQUIRES_SUDO
request_timeout = 60                  # environment CONAN_REQUEST_TIMEOUT (seconds)
revisions_enabled = 1

[storage]
path = ~/.conan/data

[proxies]
no_proxy_match = conan-server, .localdomain.com

[hooks]
attribute_checker
```

Is this a known issue or do you have an idea? We're collecting more information about the specific system in order to find where something could work differently... But so far I'm out of ideas...

**Comment by monsdar** [comment]
Our remote is an internal Conan server, we're behind a company proxy.

We found that the issue does not occur when we have no environment variables `HTTP_PROXY` and `HTTPS_PROXY` defined. This happens regardless of how we configure the proxy section in `conan.conf`:
* No proxy section at all
* Proxy section with just the `[proxies]` header
* Proxy section configured to correctly use our company proxy with all the details

Is it possible that some part of Conan does not use the proxy-configuration in conan.conf and instead goes for the environment variables - why other parts respect the conan.conf?

**Comment by memsharded** [comment]
Sorry this was not responded back them, I guess this has been solved, otherwise please open a new ticket, closing as inactive.
