### ISSUE TITLE
version ranges not including .0 prereleases

### ISSUE THREAD

**Issue by sct2010** [conan-io/conan#5302]
Hi

I have a package with the following version:
```
foo/0.3.0-beta2@user/channel
```

In a second package I use it
```
"foo/[~0.3, include_prerelease=True]@user/channel"
```

 Conan quits with the following error:
```
ERROR: Version range '~0.3.0, include_prerelease=True' from requirement
'foo/[~0.3.0, include_prerelease=True]@user/channel' required by
'conanfile.py (bar/9999@None/None)' could not be resolved
```

I expected this to select foo/0.3.0-beta2@user/channel.
If I do the same with `foo/0.3.1-beta2@user/channel` it works fine.

It seams to be an issue of the node-semver. Here is some code to demonstrate the behavior:
```python
Python 3.7.2
Type "help", "copyright", "credits" or "license" for more information.
>>> from semver import max_satisfying
>>> versions = ['0.3.0-beta1', '0.3.0-beta2', '0.3.0-beta3']
>>> range_ = '~0.3'
>>> max_satisfying(versions, range_, loose=True, include_prerelease=True)
>>> max_satisfying(versions, range_, loose=True, include_prerelease=False)
>>>
```

```python
Python 3.7.2
Type "help", "copyright", "credits" or "license" for more information.
>>> from semver import max_satisfying
>>> versions = ['0.3.1-beta1', '0.3.1-beta2', '0.3.1-beta3']
>>> range_ = '~0.3'
>>> max_satisfying(versions, range_, loose=True, include_prerelease=True)
'0.3.1-beta3'
>>> max_satisfying(versions, range_, loose=True, include_prerelease=False)
```

conan version: 1.15.1
OS: Win10 64bit

**Comment by jgsogo** [comment]
It is not an issue, the symbol `~` is looking for any version **greater**, and `0.3` is greater than any `0.3.0-xxx`, so it won't find your beta releases because they are previous ones.

You can use `~0.3.0-alpha`, for example, and it will match `0.3.0-beta3`.

**Comment by jgsogo** [comment]
btw, thanks a lot for the code samples ❤️ , it makes much more easy to reproduce the behavior.

**Comment by sct2010** [comment]
Thanks for the clearification. I thought with the option include_prerelease=True, it should also consider the beta versions. Using `~0.3.0-alpha` instead of `~0.3` is fine for me.
