### ISSUE TITLE
conan info not showing anything when specifying a reference

### ISSUE THREAD

**Issue by rweickelt** [conan-io/conan#5304]
When I run `conan info -o option=value -n requires .` in a folder containing a conanfile.py, it prints the output as expected.

Now I want to display the build requirements of a specific Conan package. The package is located on artifactory:

```
conan download package/version@user/channel
conan info -o option=value -n requires package/version@user/channel
```
But all what conan info prints is a single line with the package reference.

Is this a bug or expected behavior?

conan version 1.14.3

**Comment by jgsogo** [comment]
In your command you are given some arguments:
 * `-n requires`: it will print only the requirements
 * `-o option=value`: the recipe will take into account this option to load and return the output

So, maybe your `package/version@user/channel` recipe does not have requirements at all or it hasn't requirements for the given option `option=value`. In that case, only the reference will be printed, but nothing else.

Can you check the contents of your recipe file? Just write `conan get package/version@user/channel`

**Comment by rweickelt** [comment]
``conan get package/version@user/channel`` prints the package recipe which defines a method "build_requirements". I thought that would be part of `requires` in conan info.

``conan info -n requires -o option=value .`` produces:

```
WARN: Settings, options, env or profile specified. GraphInfo found from previous install won't be used: /project
Don't pass settings, options or profile arguments if you want to reuse the installed graph-info file.
arm-none-eabi-gcc/7.2.1@library/ga
iarcodegen/8.30.1.114@library/ga
...
conanfile.py (rflib/None@None/None)
    Build Requires:
        iarcodegen/8.30.1.114@library/ga
        ...
```
This is a mess, but at least, it contains the expected data.

When I do the same with a package reference, it prints only the reference.

**Comment by jgsogo** [comment]
Hi! The behavior is the same with a reference (Conan will look for it in the cache) or with a `conanfile.py/conanfile.txt`, the output contains the reference of all the requirements and the details about the consumer package:

```
⇒  conan info spdlog/1.3.1@bincrafters/stable -n requires
fmt/5.3.0@bincrafters/stable
spdlog/1.3.1@bincrafters/stable
    Requires:
        fmt/5.3.0@bincrafters/stable
```

As you are using `.` with a local package, it won't have `user/channel` defined and, in your case, it has no `version` too.

About the `WARN` message it is because you have already run `conan install ` on that consumer and Conan already knows the settings, options an env variables you used, as you are passing a `-o option=value` it warns you that Conan won't use the data from previous installation.

If you think we can enhance the output, please let us know, we try to do our best to give meaninful information to the users.

Thanks!

**Comment by rweickelt** [comment]
> As you are using . with a local package, it won't have user/channel defined and, in your case, it has no version too.

No, as I have written above, I am running ``conan info -o option=value -n requires package/version@user/channel`` (without the .) with a reference to a package in the Conan cache. 
- the package is in the cache together with the conanfile.py
- the package doesn't have requirements, but only "build requirements"
- the output contains the expected information when running with ``.`` instead of the reference in a folder thast contains the conanfile.py

``
If you think we can enhance the output, please let us know, we try to do our best to give meaninful information to the users.
``

Yes, absolutely:

- The command should be more generic. E.g. it should be able to print ANY property of a Conan recipe, regardless whether it is user-defined or built-in
- it should be possible to print only the specified property(ies) and nothing else. That makes it possible to use the output in shell scripts directly. The JSON output is a nice add-on, but in most cases, you want to process the output in a shell script.
- it is IMO totally irrelevant to print by which packages the queried package is used. This should not be printed by default, but only upon explicit request.
- build requirements and "normal" requirements should not be mixed in the output
- the output should be always identical, no matter whether conan info it is called on an explicit reference or a conanfile
- the tool should not try to resolve the full dependency graph by default. It might be optional though.

**Comment by memsharded** [comment]
> the tool should not try to resolve the full dependency graph by default. It might be optional though.

The ``conan info`` tool, by definition, construct the dependency graph and show information of that dependency graph with that given configuration. If the dependency graph is not computed, there are many things that cannot be shown, as they cannot be computed, starting with the ``package_id``, the binary identifier, and thus, the paths, settings, options, requirements, required-by cannot be shown either as they are specific for a binary configuration.

For inspecting the properties of a recipe, without constructing the graph, the command ``conan inspect`` is the way to go. It operates on the recipe only, not on the graph.

**Comment by rweickelt** [comment]
Thanks for your reply.

> The conan info command, by definition, constructs the dependency graph and show information of that dependency graph with that given configuration.

Ok, I buy that.

> If the dependency graph is not computed, there are many things that cannot be shown, as they cannot be computed, starting with the package_id, the binary identifier, and thus, the paths, settings, options, requirements, required-by cannot be shown either as they are specific for a binary configuration

I think you got me wrong. I am only interested in directly reachable depedencies, not transitive dependencies. A dependency graph, by definition, contains *all* dependencies, even transitive ones. 

Or do you want to say that the computation of the package_id requires to computing the whole dependency graph (> depth 1)? That can't be the case because conan install computes package id's of dependencies without even having them in the cache and with only the package reference and configuration options.

> For inspecting the properties of a recipe, without constructing the graph, the command conan inspect is the way to go. It operates on the recipe only, not on the graph.

But inspect doesn't tell me about the immediate dependencies and doesn't take configuration options.

I think it would be sensitive and beneficial to have a tool that does what I have described above. conan inspect and info should be merged for that purpose. It would be easier to understand and to use.

**Comment by memsharded** [comment]
> Or do you want to say that the computation of the package_id requires to computing the whole dependency graph (> depth 1)? 

Yes, totally, the computation of a package_id requires the whole graph, including transitive dependencies. In many cases, it will only be affected by its direct dependencies, but any other mode than the default requires the transitive dependencies as well.

**Comment by memsharded** [comment]
Closing as outdated, Conan 2.0 changed this command and behavior
