### ISSUE TITLE
Change in --target build flag in Android builds since conan 1.16.0

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#5308]
If I build a lib for Android and then use it to build an Android app, I get a linker error when using Conan 1.16.0, but it works fine with Conan 1.15.2.

Full error output is available here:
https://gitlab.com/ssrobins/stackblox/-/jobs/226164403

I noticed that the --target build flag is set to this in Conan 1.16.0:
--target=aarch64-none-linux-android28

While in Conan 1.15.2 it is set to:
--target=aarch64-none-linux-android21

21 is the minimum api level defined for arm64-v8a ABI by the CMake toolchain included in Android NDK.  28 is what I set os.api_level to in the conan create command.

My program still uses 21 so the mismatch caused the linker error.

I've been setting os.api_level to match the targetSdkVersion that I'm using for my apk.  Should I be considering os.api_level to be the minSdkVersion value instead?  It's not clear to me based on the Conan documentation.

Full reproduction steps below:

Environment
Conan 1.16.0
CMake 3.14.5
Android NDK r20
macOS 10.14.4

~/.bash_profile:
export ANDROID_HOME=/Users/steve/Code/android
export android_sdk_version=28
export android_ndk_version=r20

$ANDROID_HOME contains Android NDK

Run these commands:
conan remote add conan https://api.bintray.com/conan/stever/conan
git clone https://gitlab.com/ssrobins/conan-gtest.git
cd conan-gtest
./build_android-v8a.sh

git clone https://gitlab.com/ssrobins/stackblox.git
cd stackblox
./build_android-v8a.sh

(linker happens error here)

**Comment by lasote** [comment]
Thanks for reporting. We will take a look and if confirmed the bug we will open a patch version to fix it.

**Comment by SSE4** [comment]
hi @ssrobins 
thanks for the reporting. conan's `os.api_level` matches `minSdkVersion` property, not `targetSdkVersion`. it's translated into the `ANDROID_PLATFORM` CMake variable, which works as documented at https://developer.android.com/ndk/guides/cmake.
previously, conan ignored `os.api_level` setting for the CMake, which was a bug.
so, please set `os.api_level = 21` into your conan profile.

**Comment by ssrobins** [comment]
Ok, thanks, works great!  I'd recommend putting your comments into the documentation to help others.

**Comment by shelper** [comment]
@SSE4 

> conan's os.api_level matches minSdkVersion property, not targetSdkVersion. it's translated into the ANDROID_PLATFORM CMake variable

I have my profile with `os.api_level=21`, but my compiling log still complains:
`-- ANDROID_PLATFORM not set. Defaulting to minimum supported version 16`

I am using conan 1.27.1, tried on both windows and linux

**Comment by SSE4** [comment]
@shelper please create new issue. I need more details, e.g. your conan full profile to replicate it.
