### ISSUE TITLE
Conan's progress indication take too much space in text logs

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#531]
Looks like that currenctly Conan does not detect if it's output is directed to interactive terminal or not. When output is written to file instead of terminal, it looks like this:

http://testresults.qt.io/coin/api/results/provisioning/qtci-windows-10-x86-ee306c/provision.txt.gz

"Unzipping" is especially noisy here.

I'm not sure what is the right thing to do, but on POSIX-like systems `isatty` needs to be used. Command line programs like `curl` usually detect when they are not writing to TTY and disable progressbar in this case. As an example of different behavior, `ninja` replaces "animated" progressbar with line-by-line output with each compilation command printed. If you choose to make some output make sure it's not too noisy.

**Comment by memsharded** [comment]
Agree. Conan is already using ``isatty`` for enabling/disabling color output, I guess that it can be used to improve output to files.

**Comment by memsharded** [comment]
This has been implemented in #532, will be released in next conan 0.14.

**Comment by annulen** [comment]
Thanks!

**Comment by memsharded** [comment]
You are welcome!
