### ISSUE TITLE
"private" flag not working in requires

### ISSUE THREAD

**Issue by danielroedl** [conan-io/conan#5311]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan: 1.16.0

Hi,
I try to use the "private" flag for dependencies but it don't work as described in the documentation.

Recipe is:
```yaml
from conans import ConanFile

class HelloConan(ConanFile):
    name = "hello"
    version = "1.0.0"
    settings = "os", "build_type"

    requires = (("opencv/4.0.1@conan/stable", "private"))
```
Now the creation ends with an error:
```bash
$ conan create . user/testing
#...
ERROR: /home/user/.conan/data/hello/1.0.0/user/testing/export/conanfile.py: Error while initializing requirements. Wrong package recipe reference private
Write something like OpenCV/1.0.6@user/stable
```

Did I something wrong or is this a bug?

**Comment by lasote** [comment]
Hi, that is a python typical (and annoying) error, if you specify `(something)` it consider it an expression, but if you write (`something`, ), note the comma at the end, that is a tuple. So Conan is really reading a list with two elements, `"opencv/4.0.1@conan/stable"` and `"private"`.

Change it to ``requires = (("opencv/4.0.1@conan/stable", "private"), )`` or even a list should be more clear to disambiguate: ``requires = [("opencv/4.0.1@conan/stable", "private") ]``

**Comment by danielroedl** [comment]
Thanks, `requires = (("opencv/4.0.1@conan/stable", "private"), )` is working well.

The list is not working.
```
ERROR: /home/user/.conan/data/hello/1.0.0/user/testing/export/conanfile.py: Error while initializing requirements.
```

I think it would be nice to annotate this in the documentation. Because there are just examples with more than one dependency.
https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=private#requires

**Comment by lasote** [comment]
Opened issue in the docs repo: https://github.com/conan-io/docs/issues/1318
Opened issue to try to allow a list, in that case we should change the docs examples to use a ref.
