### ISSUE TITLE
[Regression] Two dots in lib filename 

### ISSUE THREAD

**Issue by cubimon** [conan-io/conan#5316]
I use conan 1.16.0 on windows 10 and I have a package that has a lib file named `GTEngine.v12.lib`. If I run `conan install` which uses the `visual_studio_multi` generator, it adds the lib filename _without extension_ in `conanbuildinfo_debug_x64_v120.props` (I use x64/msvc2013 which is irrelevant). Version 1.15.0 keeps the `.lib` suffix in the property sheet, but 1.16.0 somehow removes it which results in a build error.

Thanks in advance

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Hi @cubimon, we need to check it (probably related to https://github.com/conan-io/conan/issues/5316), it could be a regression. I'll keep you updated.

**Comment by uilianries** [comment]
@jgsogo the related issue is a loop.

**Comment by jgsogo** [comment]
Ups! It was #5303 (I'll edit my message too)

**Comment by cubimon** [comment]
So I should update and remove the extension? and probably close this issue because it is a duplicate?

**Comment by jgsogo** [comment]
No, leave it open. I think it is a regression and we should fix it. Probably the bug was introduced here https://github.com/conan-io/conan/pull/5254/files. If it was working for you in the previous version, it should work now.

**Comment by memsharded** [comment]
Merged, will be in Conan 1.16.1 to be released asap. Thanks!
