### ISSUE TITLE
VS 2017 in combination with v140 toolset does not work any longer

### ISSUE THREAD

**Issue by Aalmann** [conan-io/conan#5318]
Hi @lasote, @memsharded and @jgsogo ,

at least since Conan 1.15 the combination Visual Studio 2017 and toolset v140 does not work any longer. But it worked in older versions (like 1.11.2) and sadly we need exactly this combination due to many, many, many ... existing v140 packages and VS2017 installations in our company.

It can be easily fixed by changing conans/client/generators/cmake_common.py at lines 356-357 to the following:
```
            # 1900-1919 = VS 15.0 (v140 and v141 toolsets)
            (CONAN_COMPILER_VERSION STREQUAL "15" AND NOT((MSVC_VERSION GREATER_EQUAL  1900) AND (MSVC_VERSION LESS 1920))) OR
```
Our used profile:
```
[build_requires]
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=15
compiler.toolset=v140
build_type=Release
arch_build=x86_64
os_build=Windows
[options]
[env]
```

Thanks in advance.
Best Aalmann

Edit: compiler.version fixed

**Comment by lasote** [comment]
Hi Aalman! In your profile you wrote `compiler.version=14` is that correct?

**Comment by Aalmann** [comment]
Ups. Copy&Paste issue with a test profile.
I will edit the original post. It is definitely Version 15

**Comment by memsharded** [comment]
Hi @Aalmann 

This has been fixed in https://github.com/conan-io/conan/pull/5321, and it will be released asap in Conan 1.16.1. Please tell if it would be necessary to backport this fix to Conan 1.15.X too, and we will do it.
Thanks!

**Comment by Aalmann** [comment]
Hi @memsharded,

Many thanks for the fix. Would be nice to get it in 1.15.x too. 

Best
Aalmann

**Comment by lasote** [comment]
1.15.3 has been released.
It will be also at 1.16.1 soon.

**Comment by Aalmann** [comment]
Many thanks. :+1:

**Comment by Aalmann** [comment]
@PiJ82
fyi

**Comment by lasote** [comment]
1.15.3 was buggy (failure in the deployment process). 1.15.4 has been released.
