### ISSUE TITLE
How can I import different package to different folder?

### ISSUE THREAD

**Issue by ghking1** [conan-io/conan#5323]
```
[requires]
zlib/1.2.11@conan/stable
bzip2/1.0.6@conan/stable

[imports]
include, *.h -> ./external/include/zlib
lib, *.lib -> ./external/lib
```

the above config will copy all "zlib" and "bzip" include files to "./external/include/zlib", but I want they copy to "./external/include/zlib" and "./external/include/bzip" seperately. How can I do it?

**Comment by ghking1** [comment]
oh, I think I have got it. you can realize it just like following.
```
[requires]
zlib/1.2.11@conan/stable
bzip2/1.0.6@conan/stable

[imports]
include, *.h -> ./external/include/zlib @ root_package=zlib
lib, *.lib -> ./external/lib @ root_package=zlib
include, *.h -> ./external/include/bzip2 @ root_package=bzip2
lib, *.lib -> ./external/lib @ root_package=bzip
```

**Comment by memsharded** [comment]
The ``self.copy`` of the ``imports()`` method can use the ``folder=True`` argument to automatically copy to different folders. So in the conanfile.txt syntax you can use something like:

```
[imports]
include, *.h -> ./external/include @ folder=True
```

Without needing to add it for every dependency. Please tell me if this works, thanks!

**Comment by ghking1** [comment]
> The `self.copy` of the `imports()` method can use the `folder=True` argument to automatically copy to different folders. So in the conanfile.txt syntax you can use something like:
> 
> ```
> [imports]
> include, *.h -> ./external/include @ folder=True
> ```
> 
> Without needing to add it for every dependency. Please tell me if this works, thanks!

Thank you, It works very will !
