### ISSUE TITLE
how to manage multiple-level folder structure both in conanfile.py and conanfile.txt

### ISSUE THREAD

**Issue by SailorLou** [conan-io/conan#5325]
Dear James,
suppose my package structure is:
```
-Include
       -ModularA
-lib
---debug
       -ModularA
         ----aD.lib
         ----bD.lib
         ----so many libraries
    - ModularB
---release
      -ModularA
         ----a.lib
         ----b.lib
         ----so many libraries
    -ModularB

- conanfile.py
```
 
So in conanfile.py:
```
class TestConan(ConanFile):
    name = ""
    version = "1.0.0"
    license = ""
    author = ""
    url = ""
    description = ""
    topics = ("test", "")
    settings = "os", "compiler", "build_type", "arch"
    description = ""
         
    def package(self):
        self.copy("*")
 
    def package_info(self):
             self.cpp_info.includedirs=['include/ModularA']
             self.cpp_info.release.libdirs=['lib/release/ModularA']  
             self.cpp_info.debug.libdirs=['lib/debug/ModularA']   
            self.cpp_info.libs = ['manually list all libraries?']   // any convenient method to list all libraries in a folder as cmake?
 
```
 is my conanfile,py right?
if i use cmake to generate visual studio project.
how to add these multiple-level folder structure into the property column separately in VS project? additionally it can distinguish debug and release mode.
 
Thanks a lot
Best Regards
Sailor

**Comment by SailorLou** [comment]
thanks

**Comment by memsharded** [comment]
Hi @SailorLou 

First, you need to decide if you want to go with the single-configuration packages (Debug/Release in different binaries) or with the multi-configuration packages (Debug/Release in same package).

Conan uses and recommends by default the single-configuration packages. Are you sure you want to use the multi-config ones? What would be your use case?


Then, you need to clarify about ModularB and B libraries. I see you have the ``b.lib`` library inside ModularA folder and that is extremely confusing, so I cannot say. Please clarify, thanks!

**Comment by SailorLou** [comment]
Dear James，
Thanks a lot for your reply.
Let’s take an example,suppose we are developing one project which will dependency several third-party libraries,so we wan to create one package for all libraries ,the folder structue looks like:
-package folder
——-include
————-LibraryA
—————-header files for libraryA
————-LibraryB
—————-header files for libraryB
——-lib
————-libraryA
——————static lib files for libraryA
————-libraryB
——————static lib files for libraryB.

Then I don’t know how to write connanfile.py to manage such folder structure,

Don’t you recommend us to do like this?



Thanks a lot

Sailor Lou




| |
Sailor
|
|
邮箱：loufuyi@163.com
|

Signature is customized by Netease Mail Master

On 06/10/2019 20:44, James wrote:

Hi @SailorLou

First, you need to decide if you want to go with the single-configuration packages (Debug/Release in different binaries) or with the multi-configuration packages (Debug/Release in same package).

Conan uses and recommends by default the single-configuration packages. Are you sure you want to use the multi-config ones? What would be your use case?

Then, you need to clarify about ModularB and B libraries. I see you have the b.lib library inside ModularA folder and that is extremely confusing, so I cannot say. Please clarify, thanks!

**Comment by memsharded** [comment]
Yes, sure.

One of the greatest things of Conan is that using python, it allows easy scripting and implementing the behavior you want. In this case putting this ``conanfile.py`` in the root of that structure:

```python
from conans import ConanFile

class MyPkg(ConanFile):
    def package(self):
        self.copy("*.h", src="include/%s" % self.name, dst="include")
        self.copy("*.lib", src="lib/%s" % self.name, dst="lib")
```

And then:
```bash
$ conan export-pkg . LibraryA/0.1@user/channel
$ conan export-pkg . LibraryB/0.1@user/channel
```
Will make it.

Note that you probably need more things, like adding ``settings`` to the recipe if you want to model different binary configurations, etc.

**Comment by SailorLou** [comment]
OK，James，thanks，you are so nice.





| |
Sailor
|
|
邮箱：loufuyi@163.com
|

Signature is customized by Netease Mail Master

On 06/12/2019 00:34, James wrote:

Yes, sure.

One of the greatest things of Conan is that using python, it allows easy scripting and implementing the behavior you want. In this case putting this conanfile.py in the root of that structure:

from conans import ConanFile

classMyPkg(ConanFile):
    defpackage(self):
        self.copy("*.h", src="include/%s"%self.name, dst="include")
        self.copy("*.lib", src="lib/%s"%self.name, dst="lib")

And then:

$ conan export-pkg . LibraryA/0.1@user/channel
$ conan export-pkg . LibraryB/0.1@user/channel

Will make it.

Note that you probably need more things, like adding settings to the recipe if you want to model different binary configurations, etc.

**Comment by memsharded** [comment]
Great @SailorLou 

So, have you tried it and it works? If so, please tell, and close this issue, to consider it resolved. Otherwise, please try and report. Thanks!

**Comment by SailorLou** [comment]
OK，I will try in this weekend,thanks for your reminder




| |
Sailor
|
|
邮箱：loufuyi@163.com
|

Signature is customized by Netease Mail Master

On 06/13/2019 02:29, James wrote:

Great @SailorLou

So, have you tried it and it works? If so, please tell, and close this issue, to consider it resolved. Otherwise, please try and report. Thanks!

**Comment by memsharded** [comment]
Closing this ticket as inactive.

Also, since then, Conan has learned many new capabilities, like the ``layout()`` method to represent different projects folder structures, including sub-projects, etc.
