### ISSUE TITLE
Add support for XCode 11 (apple_clang: 11.0)

### ISSUE THREAD

**Issue by dBagrat** [conan-io/conan#5328]
Would be nice to have `apple_clang: version: "11.0"` in default `settings.yml`

**Comment by memsharded** [comment]
Hi @dBagrat 

Is this a release version, or still in beta (it seems so)?
No problem to add it to settings.yml for next release, I think.

**Comment by memsharded** [comment]
Also, it would be nice to know if the default ``"apple-clang": "gnu98"`` C++ standard is going to keep exactly the same, or it will change in the 11.0 release?

**Comment by dBagrat** [comment]
> Is this a release version, or still in beta (it seems so)?
It is beta, and will stay beta for a few months, but iOS developers often use it for the production too, for example: making their apps compatible with the latest beta OS's.

> No problem to add it to settings.yml for next release, I think.
Thank you! :)

//btw, at this moment, everything builds with only (manually added) "11.0" "apple-clang" value.

**Comment by prsolucoes** [comment]
Hi,

We have installed command lines tool on macos mojave now and the compiler already is version 11 and now we are locked due to its limitation.

```
> clang --version

Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

```

The conan created profile

```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

```

The conan error message:

`Possible values are ['10.0', '5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0', '9.1’]`

Thanks.
