### ISSUE TITLE
[bug] SCM retrieve sources with long filenames (>255 chars)

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#5330]
hi there,
I have a problem with the SCM retrieving sources from a local path (CI System calls create in an already git checked out path).

The problem is that it can happen that the files are in a final path with a length longer than the Windows path limit. This has been discussed already serval times but I did not see a solution that involved something else than a workaround with ```short paths```.

In Windows (I do not know at the moment since when) one can open files with a path longer than 260 chars: https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation

Could this be a feasible solution to implement in Conan's usage of the python API as Python already supports this (when using unicode paths)?

EDIT:

details
-----------------
In detail the error happens here:
>File "C:\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:

For the complete traceback have a look in the attachment:
[conan_longpath_ex.txt](https://github.com/conan-io/conan/files/3275352/conan_longpath_ex.txt)

I suppose that the ```file``` argument of the ```open``` function uses a path given by the Conan API. This in turn means that one could pass a modified unicode path string with the prefix ```\\?\``` to the Python/Windows API to get long filenames support.

There are some limitations one has to consider ([see the provided MS docs link](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation)). E.g. only absolut paths are allowed, path has to be a unicode string (Py2: u"PATH"; Py3: "PATH").

MS Docs cite:
>They indicate that the path should be passed to the system with minimal modification, which means that you cannot use forward slashes to represent path separators, or a period to represent the current directory, or double dots to represent the parent directory. Because you cannot use the "\\\\?\\" prefix with a relative path, relative paths are always limited to a total of MAX_PATH characters.

I found additional informations on Python/Unicode filenames here: https://mail.python.org/pipermail/python-bugs-list/2007-March/037810.html

**Comment by memsharded** [comment]
Hi @Johnnyxy 

> Could this be a feasible solution to implement in Conan's usage of the python API as Python already supports this (when using unicode paths)?

I wish it could be a solution. We tried it in the past, to leverage on the Py3.6 and Windows 10, enabling such long paths, and we had to revert it. The issue was that many other things were failing, in the build systems, the compilers, other tools... It seems many of those things might still be using the old APIs, and thus fail when paths >260 chars are managed.  See for example: https://github.com/msys2/MINGW-packages/issues/3139. It seems it

So we had to revert that, and keep using the ``short_paths`` workaround.

Maybe it is worth giving it another try, or at least an opt-in, wdyt @lasote? If with Conan 2.0 we are going with Py3.6 as minimum, it might make sense to try it, and maybe leave the short_paths workaround as opt-in.

**Comment by Johnnyxy** [comment]
If other dependencies have problems with that then it would we unfavourable. So in case of dependencies it is still a dangeling problem.

But concerning your mentioned issue https://github.com/msys2/MINGW-packages/issues/3139, the code there used for long path testing is wrong considering what I meant.

The code did not honour the rules from the [MS docs](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation). The prefix ```\\\\?\\``` is missing. Luckily there is an ```os.path.abspath``` api call so the forward-slashes are already converted to backward-slashes.

To fix the code one has to add the line:
```python
path = "\\\\?\\" + path
````

what in turn results in:
```python
import os

path = os.path.abspath("abcdefghijklmnop0123456789/" * 20);
path = "\\\\?\\" + path
print("path:", path)
print("length:", len(path))

try:
    print("makedirs(path)")
    os.makedirs(path)
    print("ok")
except Exception as error:
    print("failed:", error)
```

conclusion
-----------
Maybe some other things do not support long filenames this has nothing to do with Conan itself. Conan could support long filenames if one is given. If some other software cannot work with long filenames then it is their problem to fix it in their piece of software.

Conan could support long filesnames now out-of-the-box if the dependencies Conan relies on support it too.
If this does not work for someone in a special case then there is still the possibility to revert the behaviour back to short filenames ([use_always_short_paths](https://docs.conan.io/en/latest/reference/config_files/conan.conf.html#conan-conf)).

corner cases
------------
What could be a problem is specific functionality Conan has. Like ```tools.unzip``` etc. I did not dig into the code or test long filenames with that but maybe there could be some caveats. But as I see it Conan is heavily unittest-backed. So most problems should emerge right away :).

**Comment by memsharded** [comment]
It has been a while from this issue, this is the current status:
- ``short_paths`` has been removed in 2.0, in favor of a new cache with much shorter paths
- Conan 2.0 does nothing regarding to paths, it will be mostly an issue for the tools (but it will be still an issue for many of these tools)
- We have heard from users activating long paths in the Windows OS level, and being able to manage long paths for their setups.

So we don't plan to do anything else regarding path management in Windows at the moment, closing this, thanks!
