### ISSUE TITLE
Copy packages shared libraries in custom command

### ISSUE THREAD

**Issue by SebastianMosiej** [conan-io/conan#5332]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
  - OS: Windows 
  - Conan version 1.15.1
  - CMake 3.14.3

- conan file with `cmake` as generator
- install ie. protobuf/3.6.1@bincrafters/stable and protoc_installer/3.6.1@bincrafters/stable with shared=True
- integrated conan in CMake with
```
#Project dependecies
if(EXISTS ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup(TARGETS )
else()
    message(WARNING "The file conanbuildinfo.cmake doesn't exist, you have to run conan install first")
endif()
```
- attempt to copy dlls after complete build to app binary dir
```
    add_custom_command(
      TARGET ${PROJECT_NAME} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:Qt5::Gui> $<TARGET_FILE_DIR:${PROJECT_NAME}>
            COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:Qt5::Widgets> $<TARGET_FILE_DIR:${PROJECT_NAME}>
            COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:Qt5::Core> $<TARGET_FILE_DIR:${PROJECT_NAME}>
            COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:Qt5::Test> $<TARGET_FILE_DIR:${PROJECT_NAME}>
            COMMAND ${CMAKE_COMMAND} -E copy ${CONAN_BIN_DIRS_C-ARES}/libcares.dll $<TARGET_FILE_DIR:${PROJECT_NAME}>
            COMMAND ${CMAKE_COMMAND} -E copy ${CONAN_BIN_DIRS_PROTOBUF}/libprotobufd.dll $<TARGET_FILE_DIR:${PROJECT_NAME}>
            COMMAND ${CMAKE_COMMAND} -E copy ${CONAN_BIN_DIRS_PROTOBUF}/libprotobufd.dll $<TARGET_FILE_DIR:${PROJECT_NAME}>
    COMMAND ${CMAKE_COMMAND} -E make_directory $<TARGET_FILE_DIR:${PROJECT_NAME}>/logs
    )
```
`CONAN_LIB::c-ares_cares.dll` copies `libcares.dll.a`  which isn't dynamic library.
`CONAN_PKG::c-ares` refuse to execute as it lacks binary/executable file.

I don't like providing hardcoded path to libraries.  Qt libraries targets works fine.
How can I generically copy shared libraries? 
What is general rule to install dynamic libraries in project?

**Comment by memsharded** [comment]
Hi @SebastianMosiej 

Quick question: haven't you considered using conanfile ``imports`` feature? This seems the use case, it is useful for copying things from the packages to the current app binary folder, to be ready for execution.

If using a conanfile.txt, you could have a look to: https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#imports

If using a conanfile.py, the equivalent is: https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports

Please tell if this makes sense. Thanks!

**Comment by memsharded** [comment]
Hi @SebastianMosiej 

Any feedback on the closure of this issue? Were the above links enough to clarify? Thanks

**Comment by KUGA2** [comment]
If you come across this issue in 2025:

A) There is now [TARGET_RUNTIME_DLL_DIRS](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_RUNTIME_DLL_DIRS) in CMake. This will help here.
B) I would not copy them but set PATH/LD_LIBRARY_PATH (via cmake -P env --modify)
C) If you got those libs in `tool_requires`, the paths should be automatically added via conan buildenv. (untested!)

PS:

Since this cost my quite some headache, i will leave this snippet here for future readers.
It is pretty hard to use this correctly within cmake custom command:

```
set(SHARED_LIB_SEARCH_DIR_ENV_VAR "PATH") # or LD_LIBRARY_PATH
set(PREPEND_WITH $<TARGET_RUNTIME_DLL_DIRS:mytarget>) # Empty in Linux

add_custom_command(
   OUTPUT ...
                              # Add dummy, in case we got an empty PREPEND_WITH list
   COMMAND ${CMAKE_COMMAND} -E env DUMMY=dummy "$<LIST:TRANSFORM,${PREPEND_WITH},PREPEND,--modify;${SHARED_LIB_SEARCH_DIR_ENV_VAR}=path_list_prepend:>"
      -- "$<TARGET_FILE:mytarget>"
   COMMAND_EXPAND_LISTS
   DEPENDS mytarget
   VERBATIM
)

```
