### ISSUE TITLE
VS 2019 with older toolsets broken since 1.15.0

### ISSUE THREAD

**Issue by MarcelRaad** [conan-io/conan#5343]
This is the same as https://github.com/conan-io/conan/issues/5318, but for Visual Studio 2019.

With Visual Studio 2019 (16.0), you can also install the Visual Studio 2017 (v141) and 2015 (v140) build tools. This broke with https://github.com/conan-io/conan/commit/6d3282fad34365eeee530e3b69e4eb91ec3e9338, as only the v142 toolset can be used now if you don't have older IDEs installed.

**Comment by lasote** [comment]
I agree the check is totally broken with the `compiler.toolset` usage. I see two options, or we check the toolset setting instead of the compiler version or we avoid the check if a toolset is specified.

**Comment by memsharded** [comment]
Fixed in #5348, will be released in 1.16.1 soon

**Comment by MarcelRaad** [comment]
Wow, that was fast. Thanks a lot!
