### ISSUE TITLE
PROFILE_DIR with forward slashes

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#5349]
hi there,
I want to use the ```PROFILE_DIR``` variable in my profiles to access a path relative to the value of that variable. Now I do cross-compiling with a compiler that cannot parse backslashes.

An example yaml like this:
```yaml
[env]
ABC=$PROFILE_DIR/path/abc
```
will result in a malformed path as the compiler tries to interpret the slashes as excape characters:
compiler parsed: ... C:UsersNAME.conanprofiles/path/abc ...

Would it be possible to provide an POSIX style path (like PROFILE_DIR_POSIX)?

**Comment by lasote** [comment]
Hi! thanks for reporting.
Yes, I think we should try to convert the `$PROFILE_DIR` to `/`. I prefer it rather than maintaining two vars. It shouldn't break to any other user, but if it happens we will think what to do.
