### ISSUE TITLE
Since 0.12.0 "conan search -r" returns error

### ISSUE THREAD

**Issue by osechet** [conan-io/conan#535]
I run my own server (with `conan_server`). Until version 0.11.0, the search command returns the list of package on the server. Since version 0.12.0, a call to `conan search -r <server>` displays:
```
ERROR: 'results'
```

When calling `conan search -r conan.io` everything works fine. 
My server is running latest version of conan: 0.13.1.

**Comment by memsharded** [comment]
I have just done a quick check, both client and server. Are you sure you fully restarted the server?

**Comment by memsharded** [comment]
Hi @osechet , 
Did you checked this? We are about to release a minor version for 0.13.1 (0.13.2), to fix one thing, so I would love to know if you managed to make this work.

**Comment by osechet** [comment]
I just checked. Sorry, it was my mistake. My service script was using the wrong pythonpath. Everything works well now.

**Comment by memsharded** [comment]
No problem! As I always say, I much prefer a "false positive" issue or bug report, than one real issue not being detected because it is not reported. Thanks again!
