### ISSUE TITLE
make conan config get return the real configuration to be used

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5351]
From 
- https://github.com/conan-io/conan/pull/5350 
- https://github.com/conan-io/conan/issues/5338

``conan config get`` returns the raw values from the conan.conf file. This might be totally useless, or even wrong, because if there are env-vars defined, as CONAN_STORAGE_PATH, then the value returned by ``conan config get storage.path`` will be the one in the file, but not the one really applied in the configuration when running conan. 

https://github.com/conan-io/conan/pull/5350 fixes this for ``storage.path`` only:

- Check if this should be extended for other fields, like ``cacert_path``, or ``non_interactive``
- Investigate what makes sense for ``conan config set``. Probably it should warn (at least) if the env-var is set, because the value set won't be used either.
- Investigate what to do with sections: ``conan config get storage`` will return ``path = ./data``, without resolving the data as ``conan config get storage.path``

**Comment by AbrilRBS** [comment]
Closing, as Conan 2.0 does not provide `conan config get`
