### ISSUE TITLE
[feature] Pass a list of patterns for inclusion in `copy`

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan#5354]
## Enhancement Request

It would be useful to be able to pass a list of include patterns to the `copy` function, or, alternatively, a function to the `exclude` parameter.

Use case:

I generate a list of runtime dependencies from a packaged executable using `ldd`. I wish to use this list to filter the list of pakaged dlls included in a deployment. I can do the following:

```.py
required dependencies = {'foo.dll', 'bar.dll'}
for dep in required_dependencies:
  self.copy(dep)
```

But it is rather inefficient. Alternatively I can copy *all* the dependencies (including those that are not actually required by the executable) and then remove those that are not required, but this raises an error because the deployment manifest is then incorrect.

I would like to be able to do:

```.py
required dependencies = {'foo.dll', 'bar.dll'}
self.copy(required_dependencies)
```

or alternatively

```.py
required dependencies = {'foo.dll', 'bar.dll'}
self.copy('*.dll', exclude=lambda dll: dll not in required_dependencies)
```

**Comment by memsharded** [comment]
quick question for feedback: Do you have the pathname to the file, or only the filename? Because if you have the path, then it is possible to do it directly with python, something like (assuming you are using imports?):

```python
def imports(self):
     for dep in [pathlib1, pathlib2, ...]:
          shutil.copy2(os.path.join(self.package_folder, dep), dep)
```

**Comment by planetmarshall** [comment]
Actually this doesn't solve my problem as `ldd` in Windows only reports required dlls if it can find them in the first place (ie, they've already been copied to the destination folder). What I actually need to do is update the manifest after I have removed superfluous files from the deployment. I can 'hack' this with

```.py
def deploy(self):
  ...
  superfluous_files = {...}
  self.copy_deps.copied_files.difference_update(superfluous_files)
```

But that requires internal knowledge of conan.

**Comment by memsharded** [comment]
Ok, I get it now.

Passing a list of patterns seems not very productive, as internally it will still need to iterate with the patterns, for every dependency (I guess your inefficiencies come because you have a bunch of .dlls dependencies, and also the graph is big. Otherwise, it shouldn't be a problem, how long is it taking in your case?).

So the best approach would be the ``excludes`` one, I think it is relatively easy to do, to allow passing a callable and use it internally.

Thanks for the feedback!

**Comment by memsharded** [comment]
Hi @planetmarshall 

Any update about the inefficiencies? Could you please provide some order of magnitude of the number of dlls, and the time that is taking with the ``for dep in required_dependencies: self.copy(dep)`` approach? That would help to consider the alternatives and prioritizing. Thanks!

**Comment by memsharded** [comment]
``self.copy`` was replaced by ``copy()`` in 1.X and removed in 2.0.

Closing this as outdated.
