### ISSUE TITLE
how to manager package on cross-platform

### ISSUE THREAD

**Issue by SailorLou** [conan-io/conan#5355]
Dear James,
there is one usage case on cross-platform：
    one third-part library will be built separately in linux and windows and package them to Arifactory with same package name but its conanfile.py has a litte difference for OS,arch and compiler definition,let's take an example.
 
Suppose in Windows I create one package LibraryA/1.0.1@sailor/testing for a third-party library and upload to Artifactory, 
in the conanfile.py , I will define detail OS , Arch and Compiler info.

In linux, I build the third-party library again and package it to Artifactory with the same package name LibraryA/1.0.1@sailor/testing.
the difference is the definition of conanfile.py for OS , Arch and Compiler definition.

My first question is :
  What I am doing above in two OS will create one package or two packages?

When we develop a cross-platform application, we just want to write same conanfile.txt so that we can improve code portability .
so we want the package name is same.

My second question is:
   Is there any way to only write one conanfile.txt when facing different operation system?
   In the other word, how to manage package on cross-platform? 
  
Additionally, I once encounter a problem about connanfile.py in which I define arch is x86,
When I run command “conan export-pkg . LibraryA/1.0.1@sailor/testing -all ” -,it always prompt x86 is not valid.
But in conan setting file , the x86 exists apparently. It is so strange.

Thanks a lot
Best Regards
Sailor Lou

**Comment by cubimon** [comment]
I would suggest you to read [package approaches](https://docs.conan.io/en/latest/creating_packages/package_approaches.html) and read some existing conanfiles, e.g. from [bincrafters](https://github.com/bincrafters). The documentation is great btw.

first question:
You will probably create two packages from one recipe, unless you have ABI compatibility?

second question:
You can read the current os in `conanfile.py` and create `if settings.os == "Windows"` branches if that is necessary. Usually build systems are cross platform so there is no need for these checks.

third:
How do you define your arch in your conanfile.py? That is usually done is you create the package, e.g. using `conan create ... -s arch=x86 `

**Comment by jgsogo** [comment]
Thanks @cubimon for taking the time of answering the question.

We also have a repository with examples (https://github.com/conan-io/examples), all of them are built in Windows, Linux and Mac. You can check the `conanfile.py` they use and also the scripts that we run to test that they work: each folder has a `build.sh` and `build.bat` with the commands that are being run in the CI.

Let me know if you have more questions.

**Comment by SailorLou** [comment]
Dear expert,


i define  conanfile.py as below for arch info.







thanks a lot
Best Regards
Sailor Lou


At 2019-06-14 16:05:18, "cubimon" <notifications@github.com> wrote:


I would suggest you to read package approaches and read some existing conanfiles, e.g. from bincrafters. The documentation is great btw.

first question:
You will probably create two packages from one recipe, unless you have ABI compatibility?

second question:
You can read the current os in conanfile.py and create if settings.os == "Windows" branches if that is necessary. Usually build systems are cross platform so there is no need for these checks.

third:
How do you define your arch in your conanfile.py? That is usually done is you create the package, e.g. using conan create ... -s arch=x86

**Comment by memsharded** [comment]
Closing as inactive, please create new tickets if necessary, thanks.
