### ISSUE TITLE
[feature] Remote audit

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5360]
To help us debug your issue please explain:

Sometimes I want to know how many recipes and packages are available on my remote, but to do that, I need to run `conan search` and execute some extra commands like `wc` and `awk`.

Why do I need such feature? 
To expose what I have stored on my remote. That information could be used to demonstrate a timeline of recipes included. Or during a talk when people ask how many recipes are available in Conan center, most of time I can't say exactly, because I don't have a tool.

I would suggest a new sub-command like `audit` to retrieve information from remote, or maybe adding new arguments to `search`.

For instance:

```
conan audit -r conan-center # or conan search --audit -r conan-center
Total Projects: 203
Total Recipes: 809
Total packages: 129440
Last Upload: 2019-06-16 10:25:31 UTC
```

```
conan audit -r conan-center boost
Total Versions: 7
Versions: ["1.64.0", "1.65.1", "1.66.0", "1.67.0", "1.68.0", "1.69.0", "1.70.0"]
Total Packages: 1120
Last Upload: 2019-05-28 09:41:28 UTC
```

```
conan audit -r conan-center boost -q os=Windows
Total Versions: 7
Versions: ["1.64.0", "1.65.1", "1.66.0", "1.67.0", "1.68.0", "1.69.0", "1.70.0"]
Total Packages: 240
Last Upload: 2019-05-28 09:41:28 UTC
```

I know most of these information can be retrieved by Artifactory web interface, but when using Conan client we have no power.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
This would be solved with a better UI for the central repository. It would require a lot of work because it would require new endpoints in the server api, conan server, artifactory, bintray, even nexus and soon gitlab.... all these would need to implement it.
Do you have examples of other package managers with similar command?

**Comment by uilianries** [comment]
Using Conda it's not possible using the client:

https://stackoverflow.com/questions/56651098/how-can-i-list-the-number-of-packages-in-a-remote-channel?noredirect=1#comment99875510_56651098

I'll investigate other package managers

**Comment by uilianries** [comment]
**nuget** doesn't offer such feature, only package search
**buckaroo** doesn't offer such feature because you can install a package using any repo, including github.
**hunter** doesn't offer such feature because it uses a CMake file as the client
**pip** doesn't offer such feature, only package search

Well, it seems that no package manager offers this feature...

Or we implement it or just give and continue asking to the server by API.

**Comment by lasote** [comment]
I think these kind of data belongs to the server interface/api. I'm closing this.
