### ISSUE TITLE
CMake generates should use `target_link_libraries` to express dependencies between targets

### ISSUE THREAD

**Issue by thejohnfreeman** [conan-io/conan#5364]
I'm opening this issue on behalf of PR #5356. Consider when Conan package B depends on Conan package A, and Conan package C depends on B. When installing for C with the `cmake_find_package` generator, it will generate targets for B and A, and then copy properties from target A into target B. The recommended, conventional best practice is to just express that B depends on A by adding A to the `INTERFACE_LINK_LIBRARIES` property of B.

- CMake documentation says ["Dependencies between binary targets are expressed using the target_link_libraries() command"](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#binary-targets) and that [`target_link_libraries` controls the propagation of transitive usage requirements](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#transitive-usage-requirements)
- The community is recommending linking targets with `target_link_libraries`:
  - [Daniel Pfeifer, "Effective CMake"](https://youtu.be/bsXLMQ6WgIk?t=1389)
  - [Mathieu Ropert, "Using Modern CMake Patterns to Enforce a Good Modular Design"](https://youtu.be/eC9-iRN2b04?t=1401)
  - [Pablo Arias, "It's Time To Do CMake Right"](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/#model-dependencies-with-target_link_libraries)
  - [Craig Scott, "CMake targets with detailed dependencies"](https://crascit.com/2015/02/02/cmake-target-dependencies/)
  - [unclejimbo, "Modern CMake for Library Developers"](https://unclejimbo.github.io/2018/06/08/Modern-CMake-for-Library-Developers/#Handle-3rd-Party-Dependencies)
  - [cliutils, Modern CMake, "Introduction to the basics"](https://cliutils.gitlab.io/modern-cmake/chapters/basics.html#targets-are-your-friend)
   - [Manuel Binna, "Effective Modern CMake"](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#use-exported-targets-of-external-packages)

I don't mean to beat a dead horse, just to demonstrate that it is a generally accepted best practice.

**Comment by memsharded** [comment]
Closing as outdated, referred to legacy ``cmake_find_package`` integration, removed in 2.0
