### ISSUE TITLE
Packager warns if there are no files in expected scenarios

### ISSUE THREAD

**Issue by thejohnfreeman** [conan-io/conan#5365]
Following on #1582, what was implemented exactly? These days I'm getting several warnings when I set `no_copy_source=True` while omitting `build()` and `package()` definitions:

```
WARN: This conanfile has no build step
WARN: This conanfile has no package step
package(): WARN: No files in this package!
```

**Comment by lasote** [comment]
So, have your package some file or not? Looking at the code, the `package(): WARN: No files in this package!` is printed when the package is really empty.
AFAIK what was implemented at https://github.com/conan-io/conan/issues/1582 was to avoid false warnings when files were really copied to the package.

**Comment by thejohnfreeman** [comment]
The package is just the source. Should I just call `self.copy(*)`?

**Comment by thejohnfreeman** [comment]
What if the package exists just for `python_requires`? Does `python_requires` import from the `package_folder` or from the `source_folder`?

**Comment by lasote** [comment]
> The package is just the source. Should I just call self.copy(*)?

Then you can ignore the warning. We don't have a mechanism to say "this is ok".

> What if the package exists just for python_requires? Does python_requires import from the package_folder or from the source_folder?

They are only "recipes" there are no binary packages for python requires.

**Comment by memsharded** [comment]
``python_requires`` no longer create package binaries in 2.0, so this warning will not happen. Closing as outdated.
