### ISSUE TITLE
Semantic Versioning - 4 digits [question]

### ISSUE THREAD

**Issue by ericjameszimmerman** [conan-io/conan#5366]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I am using Conan version 1.14.0 presently

We have been doing some testing trying to figure out where to put our Jenkins build number when automatically building packages.

- I found that this was asked once before and closed: [Please add support for version values with four elements](https://github.com/conan-io/conan/issues/4070)
- Starting with version 0.4.0 of node-semver, 4-digits were supported
- By setting loose=True in the requirement, it appears to successfully pull in the a package with 4 digits
- However, the requirement string cannot include a 4-digit version (e.g. cannot specify ```>=1.2.3.4, loose=True```)

The purpose of this post is to:
1. Inquire about the status of 4-digit support in conan
2. Identify whether the 4-digit package version that I successfully tested, but lack of 'requires' support is on purpose.
3. Find out where people typically put rolling build #'s

Best regards,
Eric

**Comment by jgsogo** [comment]
Hi, @ericjameszimmerman !

I've just checked with `node-semver==0.6.1` and it looks like the library accepts 4-digit version for versions (`SemVer('1.2.3.4', loose=True)`), but it doesn't for version ranges expresions (`Range('>=1.2.3.4', loose=True)`).

And it looks like also that the function `max_satisfying` doesn't take into account more than 3-digit to make the comparison. In fact, those [`micro_versions`](https://github.com/podhmo/python-semver/blob/46d81c5d70ee716c48c7a8d44f9fefc6b86be33c/semver/__init__.py#L314) are not taken into account in [`compare` functions](https://github.com/podhmo/python-semver/blob/46d81c5d70ee716c48c7a8d44f9fefc6b86be33c/semver/__init__.py#L390) (not in `compare_main` function neither in `compare_pre` one).

So I think we are not blocking these 4-digit and it won't be easy to add them, also as they are not considered in the [SemVer docs](https://semver.org/) probably it is better for you to find a _workaround_.

----

I think that the best options are to use the prerelease for the build number or use the `patch` component.... but let's see if someone come across with a better idea.

**Comment by ericjameszimmerman** [comment]
**Side question:** 
How does meta-data within the package version factor into the comparison?
I was doing some testing to try to figure it out, and it seems like perhaps the latest package creation date is used when two packages are equal... is that true?

_Sequence:_
- package: `version = "0.1.10+12"`; `conan create`
- package: `version = "0.1.10+111"`; `conan create`
- consumer: `conan install .` resolved to `0.1.10+111`
- package: `version = "0.1.10+1"`; `conan create`
- consumer: `conan install .` resolved to `0.1.10+1`

Could someone provide a more detailed description?

**Comment by jgsogo** [comment]
Hi, @ericjameszimmerman , according to [SemVer](https://semver.org/): _"Build metadata SHOULD be ignored when determining version precedence."_, so yes, any of those versions could be returned as the _greater_ one (it only happens to be the last one).

**Comment by ericjameszimmerman** [comment]
When I did the prior sequence, it created `0.1.10+1`, `0.1.10+12` and `0.1.10+111` directories within my local cache `.conan/data/<package name>`.

I cannot claim to know the internals of conan, but I imagine that the SemVer library that conan uses returns all three directories to conan of equal precedence. How does conan then choose the winner? I was guessing that the creation date factored into it..

The last comment made me feel like it is could be random, which would be concerning... Please clarify.

**Comment by jgsogo** [comment]
Yes, @ericjameszimmerman, I'm also concerned about that, I think we should investigate it, I've opened an issue here: https://github.com/conan-io/conan/issues/5391

Right now Conan calls the SemVer library and that library returns the winner, we are not doing anything on top of it.

**Comment by memsharded** [comment]
Conan 2.0 implemented its own version library, extending semver to any number of digits and letters, for any field (pre and build too).
Closing this as fixed.
