### ISSUE TITLE
export version of dependency for reuse

### ISSUE THREAD

**Issue by drozel** [conan-io/conan#5369]
I have a library depending on qt. qt is my own package and i was thinking about how i call the correct qmake executable in the build() of my conanfile. My solution is to use the python_requires to export (by qt package) the method searching bin path in the requirement:
```
def get_qt():
    class QT():
        qtVersion = None
        conan = None
        qmakeExe = None

        def __init__(self, conanfile):
            self.conan = conanfile
            
            qtVer = self.conan.requires['qt'].ref.version
            if qtVer == None:
                self.output.error("couldn't find QT version. Do you have qt in you dependencies?")
                raise ValueError()
            self.qtVersion = qtVer

            # search for qmake in bin folders of qt
            for bin_path in self.conan.deps_cpp_info["qt"].bin_paths:
                qmakePath = os.path.join(bin_path, "qmake")
                if os.path.isfile(qmakePath):
                    self.qmakeExe = qmakePath
                    break

        def qmake(self, args):
            if self.qtVersion == None:
                self.output.error("try to run qmake on the wrong initialized class")
                raise ValueError()

            self.conan.run(self.qmakeExe + ' ' + args)

    return QT 
```
So i can use this class in "myLib" and call qmake() to call qmake from qt package.

The next problem - "myLib" getting dependency of my "project". I don't want to also add qt as dependency there - i just want to use qt came from "myLib".
Unfortunately, conan can't go trough dependencies tree and find qt version used by one of dependencies..
There is another solution to "share" dependency for all consumers?

**Comment by jgsogo** [comment]
Hi!

I think that this is a use case for a `build_require` declared in a profile, so every node of your graph can get advantage of it. You can achieve this behavior using a profile like the following one (so you don't need to add the `build_require` to the recipes):

```ini
[settings]
...

[build_requires]
tool/version@user/channel
```

Then you will call your build using `conan create your_project.py user/channel --profile=that-profile`.

In this example, the package `tool/version@user/channel` contains the `tool` executable and adds it to the PATH environment variable, then Conan will make it available for all the packages consuming this `build_require` (you can check the `cmake_installer` recipe, for example).

This is just an introduction and some guidelines, but let me know if you need more details.

Cheers!

**Comment by drozel** [comment]
> Hi!
> 
> I think that this is a use case for a `build_require` declared in a profile, so every node of your graph can get advantage of it. You can achieve this behavior using a profile like the following one (so you don't need to add the `build_require` to the recipes):
> 
> ```ini
> [settings]
> ...
> 
> [build_requires]
> tool/version@user/channel
> ```
> 
> Then you will call your build using `conan create your_project.py user/channel --profile=that-profile`.
> 
> In this example, the package `tool/version@user/channel` contains the `tool` executable and adds it to the PATH environment variable, then Conan will make it available for all the packages consuming this `build_require` (you can check the `cmake_installer` recipe, for example).
> 
> This is just an introduction and some guidelines, but let me know if you need more details.
> 
> Cheers!
thank you!
mm.. yeah, this is a nice solutions, but it also means that i can't change qt version in myLib and have to update profiles on every build-server..
Can i then at least export this information about with which qt the package was built to the parameters to ensure conan only takes any library built with the same QT version as project depending on?

**Comment by jgsogo** [comment]
About your last question, as you want to identify the binaries with the Qt version it has to be encoded in the `settings` or `options` as those are the elements that go into the package ID (for a default package ID mode), so you can get the `qmake` version and populate an option in your recipe with the version.

Nevertheless, I want to reproduce your scenario to check how the environment PATH variable works with transitive dependencies, and if it is possible (and makes sense) to propagate this path down in the dependency graph. It is an interesting use case for Qt, where a library and a tool are in the same package.

**Comment by drozel** [comment]
My idea was to be independent on the environment variables and to ignore any installed QT versions in OS.
The problem seems to be solved: conan just packages qmake with the script above, so i can call my concrete qt from dependencies and build with it. If i can to export the QT version (maybe also full package ID of the QT package) as you said, i could control all my packages in dependencies are built with required QT version or rebuilt them automatically.
It where nice to make an universal solution to be able to select "global" requirement/profile without the editing some files on the built machine, but i have also no idea, how implement it

**Comment by memsharded** [comment]
Just to make sure I understood it correctly:

- Qt will always be as s normal dependency (a regular ``requires = "qt/..."`` of the packages that need it.
- Those packages will want to use qmake (or other executable) that is already packaged in that dependency, in their own ``build()`` method.

Is this the case?

If it is the case, probably we don't want to add an extra declaration of a build_requires, as it is already a require, the information is there. It seems that the original approach is close to it.

I am wondering, why not delegate the responsibility to the qt package itself. Packages can add their own path to their executables, something like:

```python
def package_info(self):
    self.env_info.PATH = [os.path.join(self.package_folder, "bin")]
```

This means that the packages requiring it, will automatically get injected the location of the exes of the package in their PATH, so for them:

```python
def build(self):
      self.run("qmake ...") 
```
will use the qmake from the dependency (the above prepends its path, to the existing, so it gets higher priority).

Could this help? Did I understand it correctly?

**Comment by drozel** [comment]
memsharded, thank you

yes/no.
So, for the case i have QT in each library in the dependency is the problem almost solved. But i agree with you: just to add qmake in the path and to call it simplier than my solution. I just didn't know, that conan can edit the environment without using of the Virtualenv generator.. 
Have i understood you correctly, if package "qt" changes PATH in it's package_info(), it will be automatically patched at the moment of building another package with "qt" in dependencies?
If PATH already has another Qt path i would like to add conan's QT at the beginning. Is it possible?

But my (other) question was, if i can call QT binaries from sub dependency without adding QT in each package in the tree. Example: qt -> myLib -> myProgram
My program also needs QT for building but i would just take the qt version from myLib to prevent using various QT versions for myLib and myProgram and the solution from jgsogo is what i need, but with difference that i have only chance to change qt version by changing profile on each machine building my project

**Comment by jgsogo** [comment]
The way to go is like @memsharded says, and it is what the [recipe for Qt that bincrafters maintain is doing](https://github.com/bincrafters/conan-qt/blob/52580cb888a03f07b905075c1c7e6dae6e8edce4/conanfile.py#L571). Conan is doing exactly what you want: it is modifying the PATH, adding the path to `qt-folder/bin` at the very beginning so any dependency with a `self.run("qmake...")` will use the version you are requiring.

My only concern is the one I said before (no time to test it today, sorry):

> Nevertheless, I want to reproduce your scenario to check how the environment PATH variable works with transitive dependencies, and if it is possible (and makes sense) to propagate this path down in the dependency graph. It is an interesting use case for Qt, where a library and a tool are in the same package.

**Comment by memsharded** [comment]
yes, the PATH env var should propagate down the dependency graph to all packages that have Qt as a transitive dependency. So if the Qt package maintained by bincrafters already implement it, should be very straightforward, basically qmake should already be in the path.

**Comment by jgsogo** [comment]
Yes, I can confirm that transitive requirements (also `private` ones) propagate down the environment variables. Note: this is for `requires`, `build_requires` only affects the node that is declaring the relationship.

**Comment by drozel** [comment]
So, it works without any hacks at all now! As @memsharded said, i just have to export the QT path to the PATH and it is automatically accessible from every dependency in the tree.
Thank you all

**Comment by memsharded** [comment]
Great to know thanks for telling!
