### ISSUE TITLE
conan updates all my software installed with yum

### ISSUE THREAD

**Issue by SirLemyDanger** [conan-io/conan#5370]
Hi,

my system:
CentOs7, conan 1.16.0, packet manager yum

```python
installer = SystemPackageTool()
installer.update()
```
The above code will instuct conan to update ALL installed packets in the system. It was introduced here: https://github.com/conan-io/conan/pull/3181

This contradicts with the docu that states:

> update(): Updates the system package manager database. It’s called automatically from the install() method by default.

This would be achieved with `yum check-update` instead of `yum update`.
In my opinion conan should not touch any installed packets, unless expicitly instructed to do so. So I would like to see the old behavior back, like it is discribed in the docu.

Cheers

**Comment by Minimonium** [comment]
Indeed it's an unfortunate default. You can change the behaviour for sysrequirements with a config variable `sysrequires_mode`:
https://docs.conan.io/en/latest/reference/config_files/conan.conf.html#conan-conf
Maybe Conan should change the default in order to not break the userspace?

**Comment by uilianries** [comment]
Indeed it's a bug I think. For APT, SystemPackageTool uses `apt update` which means update only the local cache, but doesn't upgrade any package.
