### ISSUE TITLE
config install with a git repository fails when the temporary directory is not empty

### ISSUE THREAD

**Issue by AlexandreBossard** [conan-io/conan#5376]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

with conan 1.16.0, I sometimes get the following messages on our ci server:

```
conan config install git@repos.local:Conan/conan-config.git
Trying to clone repo: git@repos.local:Conan/conan-config.git
ERROR: Can't clone repo: The destination folder '/Users/Jenkins/Library/Caches/conan/1.16.0/.conan/tmp_config_install' is not empty, specify a branch to checkout (not a tag or commit) or specify a 'subfolder' attribute in the 'scm'
```

This happen when one of our devs cancelled (even if they have been told not to) a previous ci job while conan is running, leaving the directory.

I would suggest to use a random generated temporary directory, or to simply overwrite the directory content.

**Comment by danimtb** [comment]
Seems like an easy fix. I don't know why it is not using a random temp folder to do the clone...

Thanks for reporting!
