### ISSUE TITLE
"Recipe not found" on manual package copy to cache from conan server

### ISSUE THREAD

**Issue by ashlander** [conan-io/conan#5383]
Local conan server is used to store the packages, currently it is not possible to access it, so cant pull from it. But it was possible to access its file system directly. Copying selected packages into local computer conan cache results in: **search** is successful and **inspect** or **install** outputs "Recipe not found"

Is some cache rebuild  needed ?

Source:
Conan server version: v0.12.13
Conan version 1.2.3
Linux x64

Destination:
Conan version 1.15.1
Linux x64

**Comment by lasote** [comment]
Hi, the server and the local cache don't use exactly the same layout so you cannot just copy the contents.
I suggest copying the contents to a local conan server. If you have some incompatibility issues you can run a server of v0.12.13 and download everything from there.

**Comment by ashlander** [comment]
Thank you @lasote for your quick answer
The format difference explains it all. Will do exactly like you said.
Thank you for advice.
