### ISSUE TITLE
Editable layout: skip build_folder if package has no build step

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#5389]
I have tried to add a header-only package to my workspace. 

conan workspace install has failed because the layout file for my workspace contains:
`
[build_folder]
cmake-build-{{settings.build_type}}-{{settings.compiler}}
`

Which results in 
`
ERROR: Error parsing layout file '/home/losquonzia/workspace/layout_cmake' (for reference 'entt/3.0.0@skypjack/stable')
'settings.build_type' doesn't exist
'settings' possible configurations are none
`

Since the header-only package removes these settings.

I believe it should be valid to skip calculation of `build_folder` if the recipe does not have a build step so that is my suggestion to fix this.

My initial idea was to skip it for packages that declare themselves header only, but I guess those packages might actually have a build step, so that might be invalid.

**Comment by lasote** [comment]
You can use:

```
[build_folder] 
cmake-build-{{settings.get_safe("build_type")}}-{{settings.compiler}}
```

Or:
```
[build_folder] 
cmake-build-{{settings.get_safe("build_type") or ""}}-{{settings.compiler}}
```

**Comment by Lawrencemm** [comment]
OK. It kind of looks like a code smell because it's overly verbose for what is basically a config file.

Of course, there is a simpler solution that was under my nose, and that's just to define a specific layout in the workspace for the header-only package in the workspace yaml file.

This, however, is a little inconvenient as well, since I'm then forced to maintain a separate layout file just for header-only packages.

I'm maintaining at this point that I think my original suggestion is actually a good change, I can't think of a reason otherwise.

**Comment by lasote** [comment]
I don't think that is a good idea. It is very likely that another user wants exactly the opposite, you cannot just guess that a recipe without a `build_type` should compute silently to an empty space in the layout file, it could hide bugs. The code could be ugly, but it is explicit.
