### ISSUE TITLE
Ensure order for version_ranges with metadata

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5391]
According to [SemVer](https://semver.org/): _"Build metadata SHOULD be ignored when determining version precedence."_, given our implementation in the source code we are not doing anything outside the `node-semver` calls so the value returned for that kind of versions could be _random_ (need to check `max_satisfying` implementation) and this is a problem for reproducibility. We should investigate it and try to be deterministic.

**Comment by lasote** [comment]
> We should investigate it and try to be deterministic.

The question is, what conan should do? if the build metadata should be ignored, should be ignored, the three versions are the same, so... I don't think we should/can.

- Should we introduce additional logic in export/whatever to control how many recipes with the same build metadata we allow? I don't think so, more when following semver is optional.
- Should we just recommend use lockfiles to guarantee the lack of reproducibility? 
- ?

**Comment by jgsogo** [comment]
Now that we have lockfiles there is a completely different history, the user has a way to ensure determinism and we can push them to this solution: Conan doesn't ensure reproducibility unless you use _lockfiles_. Otherwise, I would consider this a high priority (lexicographic order for micro_versions, metadata,...).
