### ISSUE TITLE
Upload all packages but one(with a specific name) from the local cache

### ISSUE THREAD

**Issue by chreniuc** [conan-io/conan#5393]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.15.1

I searched through the documentation and through the issues, but I couldn't find any reference to this thing.
Let's say I have these packages in my local cache:

```bash
math/1.0.0@user/stable
zlib/1.2.11@user/stable
xerces/3.2.2@user/stable
libcurl/7.65.1@user/stable
```

How can I upload all packages,without uploading `libcurl`.

Is there a pattern that can be passed to `conan upload`?

Uploading all packages can be done with: `conan upload "*" --all -r remote_name -c`. How can we restrict it a little, something like this: `upload all packages that do not have the name libcurl`? Is this possible? We tried using the `--query` parameter, but you can only  restrict options and settings.

Thanks.

**Comment by lasote** [comment]
No, it is not currently possible.

**Comment by chreniuc** [comment]
Would this be a feature that you would like conan to have? Or you do not see a use case that would be usefull to other users?

If you do not think this should be a feature added to conan, you can close this issue :smile: .

Thanks :+1:

**Comment by lasote** [comment]
I don't think this is a very usual feature for a client tool, probably too specific. Conan is a quite big project already, with thousands of features so we try to keep it under control (very hard task). Thanks for your understanding! :smiley:
