### ISSUE TITLE
Save conan install command in a file

### ISSUE THREAD

**Issue by chreniuc** [conan-io/conan#5395]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: `1.15.1`

We've been using conan for almost 2 years now and we encountered a problem very often: There are a lot of times when we forgot what parameters(`options` and `settings`) did we pass to the `conan install` command.

We are using profiles a lot, but there are alot of times when we try to make something to work(compile) quickly(without using a profile) and after a while we forgot the `conan install` command(the `options` and `settings`).

Wouldn't it be a nice/useful feature to save the `conan install` command in a file when it's ran? Or as a comment in the `conaninfo.txt` file?

Thanks.

**Comment by lasote** [comment]
I think you are probably talking about `lock-files`. These are being developed right now at: https://github.com/conan-io/conan/pull/5035

The idea is to be able to capture the exact dependency graph in a conan install, including settings, options and package revisions.

**Comment by chreniuc** [comment]
Yeah, that's it!

Thanks.
