### ISSUE TITLE
add upstream dependencies to build_order or create a similar command to do that.

### ISSUE THREAD

**Issue by tru** [conan-io/conan#540]
Let's say I have the following dependency chain:

`zlib` -> `OpenSSL` -> `CMake`

Currently If I ask for build_order for `OpenSSL` I get `OpenSSL` and `CMake` listed. But I would need to know that before I build `OpenSSL` `zlib` needs to be built as well. So I would love an option to build_order or something similar that would tell me to build `zlib, openssl` and `cmake`.

**Comment by lasote** [comment]
I don't understand the dependency chain.

`zlib` -> `OpenSSL` -> `CMake`  Means that OpenSSL needs CMake to be built and zlib needs OpenSSL ¿?

Maybe  `OpenSSL` -> `CMake`
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -> `zlib` 
?

**Comment by jgsogo** [comment]
This issue should we covered with the `build_order (-bo)` argument in `conan info` ([link to docs](https://docs.conan.io/en/latest/reference/commands/consumer/info.html?highlight=conan%20info#conan-info))
