### ISSUE TITLE
Import targets from a Conan package built via CMake into another Conan+CMake project

### ISSUE THREAD

**Issue by HunterZ** [conan-io/conan#5405]
I've got a CMake super-build project "A" that generates a set of libraries and headers, and recently created a Conan recipe for packaging it. Some of the subprojects export their targets to `.cmake` files via `install(EXPORT)` commands in their CMakeLists.txt files.

I also have another CMake super-build project "B" that needs to use the headers and libraries in project "A". It also has a Conan recipe, which besides packaging also brings in Boost from our Artifactory as a dependency. Project "B" uses the cmake-conan wrapper and CMake's own `find_package(Boost)` to get the Boost headers and libraries into the build environment.

My question is, **how do I go about bringing project "A"'s headers and libraries into project "B"'s build environment**, the way it's doing with Boost?

I've looked over the Conan docs but am not finding clear guidance, so if it's there then it's not very accessible. I also tried looking at the Conan recipe for our internal Boost package, but I don't see any special sauce in there that tells it how to generate the CMake stuff that Conan is generating.

I do see that Conan is generating a `conanbuildinfo.cmake` file in project "B"'s build directory with CMake variables that point to my Conan package cache directories for Boost and project "A" packages, but the variables all start with `CONAN_`. I want to avoid explicitly depending on Conan in my CMakeLists.txt; currently all I have is a single `conan_cmake_run(...)` call, and Boost works fine.

**Comment by memsharded** [comment]
Maybe this example here could help: https://github.com/conan-io/examples/tree/master/features/cmake/find_package/exported_targets_multiconfig

**Comment by HunterZ** [comment]
Thanks, I didn't look at that one because I'm not interested in multi-config, but it seems to be the one that also covers some secret sauce that I was missing:
- Creating and deploying an `xyzConfig.cmake` in project "A"'s `lib/cmake` directory
- Using the `cmake_paths` generator in project "B"'s Conan recipe, and pointing CMake at the generated `cmake_paths.cmake` file

If `conan_cmake_run()` doesn't support the `cmake_paths` generator, then it's kind of moot, though. I've got things set up so that people can build the CMake project "B" completely from an IDE without needing the IDE to know anything about Conan, and I want to keep it that way.

Maybe I could do something like `include(conan_paths.cmake OPTIONAL)` after `conan_cmake_run()` as a workaround?

**Comment by HunterZ** [comment]
I don't see how the example would work as currently implemented.

The hello CMake project deploys `helloConfig.cmake` to `lib/cmake/hello/` under the install prefix.

The bye Conan recipe generates a conan_paths.cmake in the build folder that adds to `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` the _root directory_ of the hello install in the Conan package cache.

The bye CMake project calls `find_package(hello CONFIG)`.

This won't work, because CMake will only search the root directory of the hello install in the package cache, and not the `lib/cmake` directory where `helloConfig.cmake` actually resides.

I see the following options to make this work:
1. Deploy my `ProjectAConfig.cmake` file to the Project "A" install root instead of to `lib/cmake`, and modify its `include(...)` commands to include a `lib/cmake` prefix before the module names
2. Add `PATH SUFFIXES "lib/cmake"` to the `find_package(ProjectA CONFIG)` call

Option 2 sounds silly, because it's encoding extra knowledge of the Project "A" package structure into Project "B", which is what we're trying to avoid with all this tooling in the first place.

I'll therefore pursue Option 1.

P.S. Regarding `conan_paths.cmake` and `conan_cmake_run()`: Using the `cmake_paths` generator isn't buying me anything, because `conan_cmake_run()` appears to be adding the Conan package folders to the CMake search paths even when I just use the regular `cmake` generator. This makes `conan_paths.cmake` generated by the `cmake_paths` generator totally redundant, to the point that calling `include()` on it results in the paths being added twice!

**Comment by memsharded** [comment]
Hi @HunterZ 

Not sure if I understood your claim:

> I don't see how the example would work as currently implemented.

The example contains build scripts and is tested in CI in Windows and Linux, so it definitely should work.

**Comment by HunterZ** [comment]
I'm not saying it's broken, I'm saying I can't figure out how everything is supposed to fit together. What points `find_package(hello CONFIG)` at `<conan_package_location>/lib/cmake/hello/helloConfig.cmake` instead of just `<conan_package_location>/helloConfig.cmake`?

**Comment by HunterZ** [comment]
Update: I can confirm that putting my `xyzConfig.cmake` in the Conan package root (`.../package/<hash>/xyzConfig.cmake`) and having it load the target import modules from `${CMAKE_CURRENT_LIST_DIR}/lib/cmake/xyz-targets.cmake` works regardless of which generator Conan uses for project "B".

This differs from the example you linked, where the CMake `find_package(hello CONFIG)` is somehow able to find `helloConfig.cmake` under `.../package/<hash>/lib/cmake`. I can't see how to make that happen in my projects, so I'll just stick with the above solution for now.

**Comment by memsharded** [comment]
This ticket was using the old generators (legacy in 1.X, removed in 2.0), that have been superseded some time ago by new ones. Closing as outdated, please check the new ones and don't hesitate to open new tickets as necessary for any further question.
