### ISSUE TITLE
Context Manager catch_deprecation_warning cathces a UserWarning instead of a DeprecationWarning

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#5411]
When trying to catch a deprecation warning in the unit tests, I tried to use `with ``catch_deprecation_warning(self):`` however, the assert was failing.

Seems ``catch_deprecation_warning`` catches a UserWarning instead of a ``DeprecationWarning``. This is useful when trying to catch the deprecation warning for the command line but does not work with unit testing.

We will need an additional context manager to differentiate this.

**Comment by jgsogo** [comment]
Yes, you are right, it catches the result of the default `warnings.warn` messages. Maybe it is enough if we rename it to `catch_warning` and use it to catch both, `DeprecationWarning` and `UserWarning`.

**Comment by danimtb** [comment]
I am ok with that in case we don't want to differentiate it 👍
