### ISSUE TITLE
different dependency versions for each visual studio configuration

### ISSUE THREAD

**Issue by deepbluev7** [conan-io/conan#5416]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hello everyone.

I have a question, because I'd like to use Conan at work to simplify our builds and dependency management, but I don't really know, how to use Conan in our case. Since I tried to find a solution on and off for a few months now, I think maybe it's time to ask someone else.

## Our situation

We are developing plugin-like extensions for a different product, adapted to the needs of multiple different customers. Because of this, we have the following situation:

- We have many different projects, that require some shared functionality (so we don't want a solution, that needs much special configuration)
- The result of a build is usually a DLL for synchronous plugins. Some projects are asynchronous extensions, which are built as executables. All of those use Windows and different versions of Visual Studio.
- Almost every project supports different versions of the product were extending. To do that, we need to link with different libraries. Those libraries are usually binary compatible in the minor version, but always binary incompatible between major versions, and sometimes functionality is only available since in a specific version.
- Since we have to link with libraries we can't control, there are some requirements on which Visual Studio version to build with, altough that got a lot better, since newer VS versions are usually compatible with each other and so the recent releases of those libraries are all compatible with VS2015.
- Since only maybe 1% of the codebases are version specific, we just have one Visual Studio project to build the project, with different configurations for each major version of the extended product.
- Of course if we use our helper libraries, they have to link to the same product libraries as the main plugin

## My question

We basically need to link with different versions of the plugin-libraries of the product we are extending. How can we inject the correct version of those libraries into dependency graph for each Visual Studio configuration (so that it applies to all requirements in the conanfile.txt).

Some approaches I looked at:
- Having profiles for each minor version: Those are a lot of profiles, that we need to distribute, every week when a new version is released (or we only support certain version and distribute them only once a month). Also I don't really like it, if you can build a project with only one profile and you have to know how to configure it. I'd prefer it, if I could just install the requirements for the current configuration.
- Having an option on each package for each minor version: This is also a combinatorial explosion of options I need to add to every middleware package. I also need to know how to set that option correctly for each configuration, which is still effort, that I don't want to deal with every time I check out a project (since each project is quite small and I usually work on multiple projects each week and need to test compatibility with every version).
- Having magic dependencies depending on the Visual Studio version. This worked in the past, when each major VS version was binary incompatible, but now everything is compatible with VS2015, so this doesn't work anymore (and was a hack anyway).

## Probably my ideal solution

I think the ideal solution would be, if I were able to specify one or two special dependencies (or the version of one or two dependencies) in the Visual Studio configuration itself, that would then force this version on every requirement, that also requires this dependency. Then I could just use the (shiny, new) Conan VisualStudio Extension to install the requirements of the current configuration and I would be ready to go.

But maybe there is an entirely different solution on how to solve that issue for me. Or I can do that already, but I just couldn't figure it out. https://github.com/birsoyo/conan-visualstudio from #1338 looks to be almost a solution, but it is probably to powerful for my needs (I didn't try it yet).

Thank you in advance for your help,
Nico

**Comment by lasote** [comment]
Hi! It is difficult to answer that question, a lot of information and at the same time probably many different approaches.

I'll try to shed some light about what Conan can do:

- About the libraries you are extending, you can create Conan packages for them, even being just binaries. See the [export-pkg](https://docs.conan.io/en/latest/reference/commands/creator/export-pkg.html) command. 
- The rest of the libraries you are developing could depend on these Conan packages.
- The main idea of Conan is to have 1 recipe => N configs. But you can have full control of the `package_id`. That means that you can define your own "compatibility" mode to not generate more packages (different package_id) for the same recipe if it is not needed. Take a look at [Defining Package ABI Compatibility](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html)
- You can define a different `settings.yml` to have a different settings model if you need it. 
Read more about the custom settings [here](https://docs.conan.io/en/latest/extending/custom_settings.html)
Then you can share it in the whole team (the same for profile and any other Conan configuration) with the [conan config install](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install)

Hope it helps

**Comment by deepbluev7** [comment]
Hey! Thank you for your response.

I'm sorry that the question is a bit long, but I thought it may be better to provide more context.

I agree, the packaging the libraries, that are extended, makes sense, and would lead to a proper dependency graph. My issue is, that if you have a build configuration for version 5.x of the application, you also need to link with the libraries of version 5.x. I haven't found a way to Conan from a consuming visual studio configuration, that it targets the libraries of version 5.x. While settings can do that, we would need quite a lot of different settings values (a few thousand) and also deploy those settings again every week, so I would prefer it, if I could provide the information in a different way, that is easier to distribute, either with packages or in the repository, that needs the version.

You have however given me an idea. I could make every plugin a package by itself, as it also provides one build file with multiple configs. I could then have the package have a same version dependency on the libraries or have a package option, that specifies which libraries to use. That wouldn't be that easy to use, especially from visual studio, but it doesn't seem like there currently is a simple way to specify a library version from a visual studio configuration.

Thank you for your help, it provided my some perspective of what Conan can do. I think, I have to look at the rest myself.

**Comment by memsharded** [comment]
Hi @deepbluev7 
 
> My issue is, that if you have a build configuration for version 5.x of the application, you also need to link with the libraries of version 5.x. I haven't found a way to Conan from a consuming visual studio configuration, that it targets the libraries of version 5.x. 

I don't know if this could help but just in case. You can parameterize your requirements based on your current values, for example:

```python
class Pkg(ConanFile):
     def requirements(self):
          self.requires("library/%s@user/channel" % self.version)
```

When you do:
```bash
$ conan create . myapp/3.1@user/channel
```

It will create a package for myapp that will be requiring the dependency ``library/3.1``.


Please do not hesitate to ask further questions if you need to.
