### ISSUE TITLE
This conanfile has no build step

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/conan#5420]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

When trying to run CMake from Conan. I consistently get the following error:

```sh
$ conan install . --install-folder build
$ conan build . --build-folder build
conanfile.py: Running build()
conanfile.py: WARN: This conanfile has no build step
```

The content of `conanfile.py` is as follows:

```py
from conans import ConanFile, CMake

class LibConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    requires = "gflags/2.2.2@bincrafters/stable", "qt/5.13.0@bincrafters/stable", "zlib/1.2.11@conan/stable"
    generators = "cmake"
    default_options = {"qt:opengl": "desktop", "qt:with_mysql": False}

def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
```

I'm using Conan 1.16.1 on Fedora 30.

**Comment by uilianries** [comment]
Hi @wouterbeek 

There is a bad indention there. `def build` is part of `LibConan`, you need add one level:

```
from conans import ConanFile, CMake

class LibConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    requires = "gflags/2.2.2@bincrafters/stable", "qt/5.13.0@bincrafters/stable", "zlib/1.2.11@conan/stable"
    generators = "cmake"
    default_options = {"qt:opengl": "desktop", "qt:with_mysql": False}

	def build(self):
	    cmake = CMake(self)
	    cmake.configure()
	    cmake.build()
```

**Comment by wouterbeek** [comment]
Thanks for the fix!
