### ISSUE TITLE
build_requirements is ignored

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan#5425]
I have A package, which build_requires B package. And C package requires A, build_requires B. When I execute "conan install" for C, conan will skip B. If I remove requires A, conan will not skip B. What I want is conan will install A and B. Any help you can provide would be great.

Thanks

To help us debug your issue please explain:

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @xyz1001 

I am trying to reproduce your case, but so far no success. Please check the following test, that is passing:

```python
class BuildRequiresTest(unittest.TestCase):
    def test_consumer(self):
        # https://github.com/conan-io/conan/issues/5425
        t = TestClient()
        t.save({"conanfile.py": str(TestConanFile("ToolB", "0.1"))})
        t.run("create . ToolB/0.1@user/testing")
        t.save({"conanfile.py": str(TestConanFile("LibA", "0.1",
                                                  build_requires=["ToolB/0.1@user/testing"]))})
        t.run("create . LibA/0.1@user/testing")
        t.save({"conanfile.py": str(TestConanFile("LibC", "0.1",
                                                  requires=["LibA/0.1@user/testing"],
                                                  build_requires=["ToolB/0.1@user/testing"]))})
        t.run("install .")
        self.assertIn("ToolB/0.1@user/testing from local cache", t.out)
```
As you can see, the build require to ToolB is not being skipped. Could you please double check it? Maybe a more complete and reproducible case would help. Thanks!

**Comment by xyz1001** [comment]
I am sorry, LibA is private_requires ToolB. I modified the test case:
```
class BuildRequiresTest(unittest.TestCase):
    def test_consumer(self):
        # https://github.com/conan-io/conan/issues/5425
        t = TestClient()
        t.save({"conanfile.py": str(TestConanFile("ToolB", "0.1"))})
        t.run("create . ToolB/0.1@user/testing")
        t.save({"conanfile.py": str(TestConanFile("LibA", "0.1",
                                                  private_requires=[("ToolB/0.1@user/testing")]))})
        t.run("create . LibA/0.1@user/testing")
        t.save({"conanfile.py": str(TestConanFile("LibC", "0.1",
                                                  requires=[
                                                      "LibA/0.1@user/testing"],
                                                  build_requires=["ToolB/0.1@user/testing"]))})
        t.run("install .")
        self.assertIn("ToolB/0.1@user/testing from local cache", t.out)
```
I try the test case and it is passed. However, In my project `XXX`, it did print `ToolB/0.1@user/testing from local cache`, but the conanbuildinfo.txt has not any info about the `ToolB`. Here is the `conan install` output:
```
conanfile.py (MaxhubAirReceiverSDK/None@None/None): Installing package
Requirements
    catch2/2.4.2@bincrafters/stable from 'conan-local' - Cache
    fmt/5.2.1@bincrafters/stable from 'conan-local' - Cache
    xxx_logger/1.2.13@screenshare/stable from 'conan-local' - Cache
    spdlog/1.2.1@bincrafters/stable from 'conan-local' - Cache
Packages
    catch2/2.4.2@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Skip
    fmt/5.2.1@bincrafters/stable:038f8796e196b3dba76fcc5fd4ef5d3d9c6866ec - Cache
    xxx_logger/1.2.13@screenshare/stable:aa971e8736e335273eb99282f27319bdaa20df9d - Cache
    spdlog/1.2.1@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
Build requirements
    catch2/2.4.2@bincrafters/stable from 'conan-local' - Cache
Build requirements packages
    catch2/2.4.2@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Skip

fmt/5.2.1@bincrafters/stable: Already installed!
spdlog/1.2.1@bincrafters/stable: Already installed!
xxx_logger/1.2.13@screenshare/stable: Already installed!
``` 
catch2 -> ToolB
xxx_logger -> LibA
XXX -> LibC

here is the conanbuildinfo.txt.
```
[includedirs]
/home/xyz1001/.conan/data/xxx_logger/1.2.13/screenshare/stable/package/aa971e8736e335273eb99282f27319bdaa20df9d/include
/home/xyz1001/.conan/data/spdlog/1.2.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
/home/xyz1001/.conan/data/fmt/5.2.1/bincrafters/stable/package/038f8796e196b3dba76fcc5fd4ef5d3d9c6866ec/include

[libdirs]
/home/xyz1001/.conan/data/xxx_logger/1.2.13/screenshare/stable/package/aa971e8736e335273eb99282f27319bdaa20df9d/lib
/home/xyz1001/.conan/data/spdlog/1.2.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib
/home/xyz1001/.conan/data/fmt/5.2.1/bincrafters/stable/package/038f8796e196b3dba76fcc5fd4ef5d3d9c6866ec/lib

[bindirs]


[resdirs]


[builddirs]
/home/xyz1001/.conan/data/xxx_logger/1.2.13/screenshare/stable/package/aa971e8736e335273eb99282f27319bdaa20df9d/
/home/xyz1001/.conan/data/spdlog/1.2.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/
/home/xyz1001/.conan/data/fmt/5.2.1/bincrafters/stable/package/038f8796e196b3dba76fcc5fd4ef5d3d9c6866ec/

[libs]
xxx_logger
pthread
fmtd

[defines]
SPDLOG_FMT_EXTERNAL

[cppflags]


[cxxflags]


[cflags]


[sharedlinkflags]


[exelinkflags]


[sysroot]



[includedirs_xxx_logger]
/home/xyz1001/.conan/data/xxx_logger/1.2.13/screenshare/stable/package/aa971e8736e335273eb99282f27319bdaa20df9d/include

[libdirs_xxx_logger]
/home/xyz1001/.conan/data/xxx_logger/1.2.13/screenshare/stable/package/aa971e8736e335273eb99282f27319bdaa20df9d/lib

[bindirs_xxx_logger]


[resdirs_xxx_logger]


[builddirs_xxx_logger]
/home/xyz1001/.conan/data/xxx_logger/1.2.13/screenshare/stable/package/aa971e8736e335273eb99282f27319bdaa20df9d/

[libs_xxx_logger]
xxx_logger
pthread

[defines_xxx_logger]


[cppflags_xxx_logger]


[cxxflags_xxx_logger]


[cflags_xxx_logger]


[sharedlinkflags_xxx_logger]


[exelinkflags_xxx_logger]


[sysroot_xxx_logger]


[rootpath_xxx_logger]
/home/xyz1001/.conan/data/xxx_logger/1.2.13/screenshare/stable/package/aa971e8736e335273eb99282f27319bdaa20df9d


[includedirs_spdlog]
/home/xyz1001/.conan/data/spdlog/1.2.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include

[libdirs_spdlog]
/home/xyz1001/.conan/data/spdlog/1.2.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib

[bindirs_spdlog]


[resdirs_spdlog]


[builddirs_spdlog]
/home/xyz1001/.conan/data/spdlog/1.2.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/

[libs_spdlog]
pthread

[defines_spdlog]
SPDLOG_FMT_EXTERNAL

[cppflags_spdlog]


[cxxflags_spdlog]


[cflags_spdlog]


[sharedlinkflags_spdlog]


[exelinkflags_spdlog]


[sysroot_spdlog]


[rootpath_spdlog]
/home/xyz1001/.conan/data/spdlog/1.2.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9


[includedirs_fmt]
/home/xyz1001/.conan/data/fmt/5.2.1/bincrafters/stable/package/038f8796e196b3dba76fcc5fd4ef5d3d9c6866ec/include

[libdirs_fmt]
/home/xyz1001/.conan/data/fmt/5.2.1/bincrafters/stable/package/038f8796e196b3dba76fcc5fd4ef5d3d9c6866ec/lib

[bindirs_fmt]


[resdirs_fmt]


[builddirs_fmt]
/home/xyz1001/.conan/data/fmt/5.2.1/bincrafters/stable/package/038f8796e196b3dba76fcc5fd4ef5d3d9c6866ec/

[libs_fmt]
fmtd

[defines_fmt]


[cppflags_fmt]


[cxxflags_fmt]


[cflags_fmt]


[sharedlinkflags_fmt]


[exelinkflags_fmt]


[sysroot_fmt]


[rootpath_fmt]
/home/xyz1001/.conan/data/fmt/5.2.1/bincrafters/stable/package/038f8796e196b3dba76fcc5fd4ef5d3d9c6866ec


[USER_xxx_logger]
[USER_spdlog]
[USER_fmt]
[ENV_xxx_logger]
[ENV_spdlog]
[ENV_fmt]

```

**Comment by memsharded** [comment]
Confirmed this is an unfortunate bug, coming from a mixture of build-requirements and private requirements. It seems not trivial, it would take some time to fix.

In the meanwhile, I would strongly suggest to reconsider the usage of ``private`` requirements. We are discouraging its use (as you can see they are barely documented), should be only for some extreme cases, like needing to wrap 2 different versions of the same library. What would be the case of ``private`` requirement of ``catch`` library?

**Comment by xyz1001** [comment]
I use private or build_requires to prevent a chained dependency。These is some libraries which is only used when building, such as header only library, or static library when build shared library I don't want to make them exposed. Because it will cause a slower installation, even a confliction. For example, LibA depend LibC with some options, LibB depend LibA and LibC with other options, then conflict. The way I solve this problem is makng LibA a shared library and making LibC is a build requirement of LibA.

**Comment by memsharded** [comment]
Thanks @xyz1001 for the feedback.

I understand your use case, but please let me clarify the purpose of those type of requirements:

- build_requires is used for tools that do not affect at all the final binary that is packaged. That is basically tools (cmake, etc) and testing libraries (catch, gtest, etc). Using it for other things might be problematic, as the package binary IDs do not take those into account.

- private requirements were mostly intended for extreme cases of having to deal with multiple versions of the same library, in context like you said, isolated by a shared library embedded a static library. This is not the typical use case, as the most recommended approach is to use the same static library version, otherwise there are lots of things that can go wrong with the ABI if something that is not a very primitive type pass through the APIs.

We have been lately discussing a lot and thinking about other types of requirements, like the "do not propagate downstream", but this is a very complex subject and it will require time. 

In the meantime, I would strongly recommend to try to use the regular ``requires`` as much as possible. They might have some overhead (slower installation). Specifically, for the above case, I still don't fully understand why would you ``private`` require the catch testing library, and not ``build-require`` it.

**Comment by xyz1001** [comment]
Thank you for your reply. Now I have a deeper understanding of different requirement. And I realize that making `catch` as a private require is a misuse. Build requirement is a better way.
One reason that I do not use build requirements is there is some problem in this situation. LibA/1.0 is one build requirement of LibB/1,0,0. LibA/1.0.1 and LibB/1.0.0 is build requirements of LibC. LibA/1.0 is the alias of lastest LibA/1.0.x. Then `conan install`  failed for LibC. Here is the output:
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

LibB/1.0.0@xyz1001/stable: Not found in local cache, looking in remotes...
LibB/1.0.0@xyz1001/stable: Trying with 'conan-local'...
Downloading conanmanifest.txt
[==================================================] 5.9KB/5.9KB
Downloading conanfile.py
[==================================================] 1.9KB/1.9KB
LibB/1.0.0@xyz1001/stable: Downloaded recipe revision 0
ERROR: Conflict in LibB/1.0.0@xyz1001/stable
    Requirement LibA/1.0@xyz1001/stable conflicts with already defined LibA/1.0.1@xyz1001/stable
    To change it, override it in your base requirements
```
I tried conan v1.9, v1.10, v1.13 and v1.16. It is OK with conan v1.9 or v1.10, but conan 1.13 and 1.16 has this problem. Thus I give up build requirement.
