### ISSUE TITLE
#RREV in conanfile.txt

### ISSUE THREAD

**Issue by PotapovAlexandr** [conan-io/conan#5427]
Hello!

I try to pin revision for some recipes in conanfile.txt.
Conan 1.16.1

What i do:
I've added hashtag and number of revision like https://docs.conan.io/en/latest/mastering/revisions.html#package-revisions. 

[requires]
gtest/1.8.1@bincrafters/stable#0

But # - is a comment symbol and "#0" is ignored by Conan.
 
Help please and tell me what i do wrong.

PS: on command line it is works  normal.
conan install gtest/1.8.1@bincrafters/stable#0

**Comment by memsharded** [comment]
Verified, this is a bug, can reproduce.

I am proposing a fix in https://github.com/conan-io/conan/pull/5435, but it has a small risk of breaking users that do not use spaces before the beginning of a comment. I think that could be considered bad syntax, lets see what @lasote thinks.

**Comment by lasote** [comment]
Yes, I think it is better to take the risk so I've merged the PR and will be available in the next 1.17 release. Thanks for reporting!
