### ISSUE TITLE
Conan CMake generator does not support use of CMake TARGETS when GCC linker scripts when INPUT "redirects" are used

### ISSUE THREAD

**Issue by brentd42** [conan-io/conan#5428]
Intel makes binary versions of Intel® Threading Building Blocks (TBB) packages available at https://github.com/intel/tbb/releases.

For the Linux packages (e.g., https://github.com/intel/tbb/releases/download/2019_U8/tbb2019_20190605oss_lin.tgz), Intel uses GCC linker script files to "redirect" non-numeric suffixed .so file names to numeric suffixed couterparts. For example, the 'libtbb.so' file (in tbb2019_20190605oss/lib/intel64/gcc4.4) contains:

`INPUT (libtbb.so.2)`

This essentially works like a symbolic link, telling the linker to obtain the actual link object from a file named 'libtbb.so.2'.

Unfortunately, the Intel-provided linker scripts don't work well with the Conan CMake generator and _conan_basic_setup(TARGETS)_.  When TARGETS is used, as expected, Conan includes the fully-qualified 'libtbb.so' name as an object to be linked, however the GCC linker is unable to locate 'libtbb.so.2' since the library path containing this file is not specified via the -L option (via CMake _link_directories()_).

For example, CMakeLists.txt containing ...

```
cmake_minimum_required(VERSION 2.8.12)
project(PackageTest CXX)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_executable(Fibonacci Fibonacci.cpp)
target_link_libraries(Fibonacci CONAN_PKG::tbb)
```

... results in ...

```
/usr/bin/c++    -m64 -O2 -DNDEBUG   CMakeFiles/Fibonacci.dir/Fibonacci.cpp.o  -o bin/Fibonacci -rdynamic /home/bdavis/.conan/data/tbb/1.0.0/bdavis/testing/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/lib/libtbb.so -Wl,-rpath,/home/bdavis/.conan/data/tbb/1.0.0/bdavis/testing/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/lib
/usr/bin/ld: cannot find libtbb.so.2
collect2: ld returned 1 exit status
```

Use of linker flags in this fashion (instead of symbolic links) does seem to be a bit unconventional, however Intel has done this for years.  It would be nice if Conan would better support it.  We'd like to use the TBB binary distributions exactly as provided by Intel.  Also, it would be better to not require consumers of TBB on Linux to know about this quirk and have to specify _link_directories()_ commands themselves.

To fix this, it seems feasible that the Conan CMake generator would simply need to also include _link_directories()_ commands for package library targets. 
 
Attached are some simple example recipes and CMakeLists.txt to reproduce.  The test_package uses the Fibonacci.cpp example provided by Intel in examples/test_all/fibonacci.

This issue occurred using Conan 1.15.4 on CentOS Linux 6.10 w/ GCC 4.4.

[tbb_with_linker_scripts.zip](https://github.com/conan-io/conan/files/3350180/tbb_with_linker_scripts.zip)

**Comment by memsharded** [comment]
Hi @brentd42 

I am having a look at this, and so far I cannot figure out what would be the solution.
The thing is that cmake ``link_directories()`` is a global configuration, not recommended, the way to go is to use cmake targets and their properties. 

> To fix this, it seems feasible that the Conan CMake generator would simply need to also include link_directories() commands for package library targets.

I am afraid not possible, adding directories with libraries to this global configuration could easily break other conan users. 

If you know the real library that is going to be linked, why not directly coding that in the recipe?:

```python
    def package_info(self):
        self.cpp_info.libs = ['libtbb.so.2']
```

**Comment by brentd42** [comment]
Now there's a thinking outside the box idea!  It appears the `self.cpp_info.libs` approach works for non-targets usage as well (CMake `target_link_libraries(Foo "libtbb.so.2")` seems to correctly infer and specify `-ltbb` and not something like `-ltbb.so.2`)

Thanks for your help identifying a solution for this!

**Comment by memsharded** [comment]
Happy to know that it is working for you, thanks for telling!

**Comment by ed-alertedh** [comment]
I was getting issues with CMake linking libs in the wrong order when one of my Conan packages uses libpthread and libdl. I was trying to work out how to specify a package dependency on a system library and stumbled on this thread. The approach that solved this issue also seems to work for me! Thought I would make note of it here in case it helps someone else fix link order with CMake:

```
def package_info(self):
        self.cpp_info.libs = ['libdl.so','libpthread.so']
```
