### ISSUE TITLE
Possibly undocumented special semantic for a "test" sub-directory in a package

### ISSUE THREAD

**Issue by jegabe** [conan-io/conan#5429]
When using conan 1.16.1 under Windows, the following "magic" happens:

When having a sub-directory named "test" with another conanfile.py and CMakeLists.txt contained (along with the usual conanfile.py and CMakeLists.txt in the root folder of my working copy), conan tries to build something inside the "test" folder as well. When the folder is renamed to "tests" (adding an 's'), this behavior changes.

I'm not sure if it is a leftover of the "test_package" development, wanted (probably undocumented) behavior or a bug.

Here is the folder structure of my project

root folder
 |
+ - conanfile.py
+ - CMakeLists.txt
+ - test
      |
     + - conanfile.py
     + - CMakeLists.txt

**Comment by memsharded** [comment]
Hi @jegabe 

You are totally right, the behavior changes. This is some legacy, as originally the ``test_package`` folder was called ``test`` folder. We introduced the new name and un-documented the previous one, but didn't remove the behavior to not unnecessarily break users.

I think it deserves a note in the docs by now, and that it should be completely removed in conan 2.0

Thanks for reporting!

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/12752 is dropping the ``test`` name as a Conan ``test_package`` folder, for 2.0

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/12752 will be in beta7
