### ISSUE TITLE
Visual Studio with older toolsets still broken with cmake_multi generator

### ISSUE THREAD

**Issue by MarcelRaad** [conan-io/conan#5430]
In Conan 1.16.1, https://github.com/conan-io/conan/issues/5343 was fixed when using the cmake generator by explicitly setting `CMAKE_BUILD_TYPE`. However, the same issue still exists when using the cmake_multi generator by omitting `CMAKE_BUILD_TYPE`. I'm using https://github.com/conan-io/cmake-conan to call Conan from CMake.

Building from the VS 2019 command prompt with the v141 toolset results in:
```
CMake Error at conanbuildinfo_multi.cmake:1507 (message):
  Incorrect 'Visual Studio' version 'compiler.version=15' is not the one
  detected by CMake: 'MSVC=19.22'
Call Stack (most recent call first):
  conanbuildinfo_multi.cmake:1565 (conan_error_compiler_version)
  conanbuildinfo_multi.cmake:1667 (check_compiler_version)
  conanbuildinfo_multi.cmake:1350 (conan_check_compiler)
  conan.cmake:503 (conan_basic_setup)
```

**Comment by memsharded** [comment]
Hi @MarcelRaad 

The conanbuildinfo.cmake got a check like this:

```cmake
if(DEFINED CONAN_SETTINGS_COMPILER_TOOLSET)
       conan_message(STATUS "Conan: Skipping compiler check: Declared 'compiler.toolset'")
       return()
endif()
```
So in theory, defining ``compiler.toolset`` should result in this check being skipped and not raised. Could you please make sure that you have this setting defined by cmake-conan? Otherwise, it is a cmake-conan issue, not a conan one, and this should be moved to it.

**Comment by MarcelRaad** [comment]
Sorry, the info about using cmake-conan is actually irrelevant and only useful for confusion. What it does is effectively `conan install`, and I get the same behavior without cmake-conan.

I have a profile containing `compiler=Visual Studio` and `compiler.toolset=v141`.
`conan install --profile=[...] -g cmake` generates a conanbuildinfo.cmake which contains `CONAN_SETTINGS_*`.
`conan install --profile=[...] -g cmake_multi` generates a conanbuildinfo_multi.cmake plus a conanbuildinfo_debug.cmake and conanbuilinfo_release.cmake, neither of which contains `CONAN_SETTINGS_*`.

**Comment by memsharded** [comment]
I see, thanks for the report, we will further investigate it.

In the meantime, you might want to define CONAN_DISABLE_CHECK_COMPILER cmake variable to skip the compiler check.

**Comment by memsharded** [comment]
``cmake_multi`` deprecated in 1.X in favor of ``CMakeDeps``, removed in 2.0. Closing this as outdated.
