### ISSUE TITLE
Conan producing corrupted package .tar.gz archives

### ISSUE THREAD

**Issue by HunterZ** [conan-io/conan#5436]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I'm using Conan version 1.9.2 on RHEL 7.6 to create a package and upload it to an internal Artifactory repo. This includes a shell script, a Linux binary, a large pile of Linux libraries, and a large pile of XML files.

Some of the library files (the ones built via GNU autotools) include symbolic links that are aliases of those libraries (e.g. `libactivemq-cpp.so -> libactivemq-cpp.so.19.0.4`).

The `conan_package.tgz` file created by the `conan upload` command is corrupted, such that when I run `tar tzvf` on it, I get a `tar: Skipping to next header` message after each symbolic link is encountered. When it reaches the end, I get the following errors:
```
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Is Conan not capable of packaging symbolic links properly in a .tar.gz archive? That would be rather awful.

Note that this is happening at time of archive creation, not during the upload, as I am also looking at the `conan_package.tgz` file created in my local package cache before the upload takes place.

**Comment by HunterZ** [comment]
Looks like this may be a duplicate of #4050

**Comment by memsharded** [comment]
In theory, the #4050 was fixed in 1.14.5. Could you please try to upgrade and check again?

**Comment by HunterZ** [comment]
Yeah, I've requested that we upgrade. Not sure when it will happen, but if/when it does I'll try to report back.

**Comment by memsharded** [comment]
Ok, as in theory it has been fixed, I am closing it by now, but looking forward to your feedback, please comment and we will re-open if necessary. Thanks!
