### ISSUE TITLE
Add -e argument to commands other than create/install/info

### ISSUE THREAD

**Issue by dribeas** [conan-io/conan#5439]
I am trying to build generic recipes that can build multiple different repositories that follow the same guidelines/build system.  When the recipe for a particular library is exported, I need to be able to save some additional information, which I am currently passing as environment variables (not finding a better alternative).

Being able to pass those through the command line rather than actually setting them in the environment would be useful.

Conan version 1.16.0
OS: currently testing macos, but I want this cross-platform linux/macos/windows

**Comment by dribeas** [comment]
It seems that a naive approach of having the `conan` command itself consume the `-e` arguments and setting the environment before calling on the specific commands would provide a quick solution to this problem, assuming that `-e` is not a valid argument to any of the other conan commands.

**Comment by lasote** [comment]
Hi! we would need a more specific use case. Which command/s are you thinking about?
Take into account that the local commands like `conan source`, `conan build`, `conan package` will take the "status" of the install from the generated files (`conaninfo.txt` etc) so the environment will be retrieved from there.

**Comment by dribeas** [comment]
At this point, it would be most useful in the `conan export` command.

**Comment by lasote** [comment]
I understand. It doesn't feel very clean for conan either. How about writing a file with the info and reading it from the recipe? The implementation in the recipe could be to [this](https://docs.conan.io/en/latest/howtos/capture_version.html#how-to-capture-package-version-from-scm-git) but for the `exports` attribute and reading a file instead of getting information from the SCM.

**Comment by memsharded** [comment]
> At this point, it would be most useful in the conan export command. The purpose is to be able to drive what the recipe does/exports from the command line to repackage the contents of a larger binary recipe:

quick feedback here please @dribeas : If you are repackaging binary contents, why not using ``export-pkg`` instead, which will put the binaries directly in the cache, without duplicating them in the "source" folders? Plus, ``export-pkg`` does use profiles and environment variables.

**Comment by dribeas** [comment]
@memsharded : My understanding of the `export-pkg` is that it depends on the binaries existing in the filesystem.  In my case I want conan to build for me, and then repackage that:

`repo -> repo-all package -> [ part1-package, part2-package, ... ]`

I would prefer the recipe to be present in conan as this allows the uploading of the recipes without having to prebuild all of the potential target OS/options.

Currently I have a recipe that goes from repo -> large package, and then another recipe that is run multiple times, one per part.  After uploading the recipes, I can have a client depend on `part1-package` and if there are no binaries that will run the build for the `repo-all package` and then the extraction of the binaries into `part1-package`

**Comment by memsharded** [comment]
Hi @dribeas 

Ok, understood, yes that is an approach that can make sense. 

When re-packaging from another repo, typically it is not necessary to export further files into the "parts" packages, this is why I was confused about the usage.

But now I see how this is connected to: https://github.com/conan-io/conan/issues/5410#issuecomment-507849285, and I agree, we might want to bring back https://github.com/conan-io/conan/issues/2456

**Comment by memsharded** [comment]
So I would say that actually, a possible ``export()`` method in recipe would be a better approach than using env-vars to be able to define those exports with some workarounds in the recipe, wouldn't it?

**Comment by lasote** [comment]
If the information is in the `self.name` (as commented here: https://github.com/conan-io/conan/issues/5410#issuecomment-507849285)  or any other instance field, yes, if it is input from elsewhere you would have the same issue.

**Comment by memsharded** [comment]
Conan 2 has dropped this ``-e`` var, and the ``[env]`` section of the profiles in favor of the ``[buildenv]`` and ``[runenv]`` sections, closing this ticket as outdated.
