### ISSUE TITLE
automatic providing of the dynamic libraries  

### ISSUE THREAD

**Issue by drozel** [conan-io/conan#5442]
Hi,

conan works perfectly with the static libs and adds them automatically on the linkage of any depending project.
I've expected that the dynamic libraries (obviously needed not at the building but by user of the built project) are being provided by conan automatically and can be all accessed in the depending project for the export.

So, i though:

- lib1 exports lib1.so
- lib2 exports lib2.so and lib21.so

MyProj having both libs in dependencies have to package *.so to be able to be started. So, i expected, i write:
`
 def package(self):
        # packege server's files (binaries, configs etc.)
        self.copy_deps_expected_method("libs")
`

and get all lib1.so, lib2.so, lib21.so under libs automatically.

But i see no possibility to do that. Only option i found is to use `imports()` method, but:

1. i have to give all library names explicitly (and update them every time, when dependencies getting new outputs)
2. conan tries to search them everywhere, in each dependency. It's not a big problem, but each .so belongs to a concrete library, it makes no sense to try to search them
3. conan gets no error when lib is not found. I could theoretically have any lib 2 times: in a direct dependency and somewhere deep in the dependency tree: .so will be overwritten without any warning

So, my main idea is: all *.a from dependencies are automatically passed to the linker of any depending packet. Similarly, every dynamic library must be transferred to end-user for installing. Is this logic wrong?

There is another solution i missed?

**Comment by danimtb** [comment]
Hi @drozel,

Conan is mostly focused on the development cycle and not in deployment, however, there are some things you can use to get the runtime dependencies resolved when running an app. For example, as you said, the imports method is one of those in this situation. Yes, it is kind of a "bulk" copy but normally the output dirs do not change so much.

Other thing you could do is use the deploy() method, although the `self.copy_deps` is the same copy done in the `imports()`, so not exactly what you want.

As an alternative, Conan exposes the graph model through `self.deps_cpp_info` attribute https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-cpp-info so you can iterate each dependency looking in `self.deps_cpp_info.bin_paths`. Something similar to (not tested, just to get the idea):

```
for dep_name, dep in self.deps_cpp_info.dependencies:
     shutil.copy2(dep.bin_paths, self.package_folder)
```

Maybe you are already doing something like this. I think this could be the best approach with your case and the conditions you exposed.

**Comment by memsharded** [comment]
Hi @drozel 

It is not clear to me if you are asking about the "re-packaging" approach described here: https://docs.conan.io/en/latest/devtools/running_packages.html#runtime-packages-and-re-packaging

This is mostly intended for distribution outside of Conan, or for very specific use cases. I don't think that every package should re-package the shared libraries of its dependencies, is that what you are suggesting?


I don't fully understand:

>  every dynamic library must be transferred to end-user for installing. 

The shared libraries are only required by the end consumer, and that consumer can decide which approach they want to be able to run their executables:
- To do a copy of the shared libraries within conan packages with ``imports`` or ``deploy``, to a known location in user space (not the local conan cache) besides the executable or the like
- To configure the environment, with variables like LD_LIBRARY_PATH, PATH, which could be automated with virtualenv generators like conan ``virtualrunenv`` generator.

If you could please clarify your comment, that would help. Thanks very much for your feedback!

**Comment by drozel** [comment]
@memsharded sorry, i didn't clarified my usecase..
Yes, in normal case you starts your executable on the machine, where it has been built. In this case conan has automatic mechanism with exporting LD_LIBRARY_PATH and everything works.
In my case i have to pack all needed .so to the package for delivering to consumer and i expected, that conan also can built the full libraries list as it can compile all lib paths for adding to LD_LIBRARY_PATH.

  @danimtb yes, i think, it is what i need.. Has `deps_cpp_info.dependencies` all dependencies from tree (i mean also indirect dependencies of dependencies)?

**Comment by danimtb** [comment]
>  Has deps_cpp_info.dependencies all dependencies from tree (i mean also indirect dependencies of dependencies)?

Yes, all the direct an transitive dependencies will be there.

**Comment by danimtb** [comment]
@drozel was the issue solved? Was `deps_cpp_info.dependencies` and the information there useful for your case? Thanks!

**Comment by drozel** [comment]
@danimtb
Hi. I was wrong with my wish to get the list of dynamic libs - they are already (transparent) in the LD_LIBRARY_PATH and can be passed to end user with the environment generator.
They are also automatically activated in the build process, so, if you want to run some bins from your library during building, they will find all required .so's

My use case is a bit specific, we copy all dynamic libs to the end user and replace them with the custom loader to be able to start our binary on each Linux distribution independent on the Linux of the build server. Conan don't have to do something for that, that is the next step and I was confused with that

**Comment by danimtb** [comment]
Thanks a lot for sharing the info. I understand it better know and glad you finally fixed the issue! 😄
