### ISSUE TITLE
Conan user survey [Please feedback]

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5446]
https://www.surveymonkey.com/r/ConanCommunity

Dear Conan User, 

As you may know, Conan Package Manager is fully OpenSource, we do not capture any kind of information on your usage. As a result, it is sometimes difficult to estimate the importance of some feature requests, the impact of bugs or regressions, or how to prioritize development in general. We’d like to measure the impact of Conan, its growth, and how to size our resources accordingly across different areas, including development, support, etc.

Please click on the link above to take our 2 min survey. This survey is exclusively for the internal use of Conan team at JFrog to provide and evolve Conan to better suit your needs. 

We look forward to hearing your opinion. 

Thanks, 
The Conan Team @ JFrog

**Comment by uilianries** [comment]
Maybe adding it to conan.io as a box when opening the website. Also we could put it in README file

**Comment by memsharded** [comment]
Yes, adding it to conan.io (actually to the docs, that is where more users go) is planned.

What do you mean to put in README file? In the repo? I am not sure, it is totally intended for existing and active users, I don't think they go to the README that much.

**Comment by uilianries** [comment]
> What do you mean to put in README file? In the repo?

Yes, in this repo. 

>  I am not sure, it is totally intended for existing and active users, I don't think they go to the README that much.

Indeed.

Maybe we can try directly some companies associated to Conan.
