### ISSUE TITLE
Question: How to test changes dependencies in CI 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#5449]
Dear conan team,

Do you recommend any approach for testing dependencies changes in CI without editing the conanfile.py

Our current appach: 

1. Update a dependency, create a testing package
2. Update conanfile.py in main project to use the testing package
3. Make sure everything works as expected 
4. Merge changes of the dependency
5. Revert back main project conanfile.py

As you can see this is a long process.

Is there a better approach that I'm not aware of? 

Thanks

**Comment by lasote** [comment]
Hi! You might want to take a look at the [revisions feature](https://docs.conan.io/en/latest/mastering/revisions.html). The idea is, during the development of the dependency, you don't need to bump the versions in the conanfile.py and Conan will resolve always the latest one automatically. The revisions feature guarantee immutability of your recipes/packages.

So, the CI process can resolve automatically the latest revisions of a conanfile without editing any file.
We are currently working hard with the just merged lock files feature (to be released tomorrow) and working to define a flow for CI. Hopefully, in the following weeks, we can get some initial guide or recommendations etc.
The idea with the lock files could be, once you get a green build of your project, you can store the lock file to guarantee the reproducibility.

Let me know if it can help.

**Comment by memsharded** [comment]
Closed as inactive
