### ISSUE TITLE
conanbuildinfo.txt being created in local directory when doing conan install

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#545]
When doing `conan install MyComp/... --build MyComp` Conan generates a `conanbuildinfo.txt` in the directory where I run this command from. Is this intended?

My workflow is often to do something like this (short version):

* `git clone MyComp`
* `cd MyComp`
* `conan export monsdar`
* `conan install MyComp/... --build MyComp`
* `conan upload -r conan.io MyComp/... --all`

By doing this the git repo gets filled with a file that is generated during build and should not be added to version control.

Is there a reason behind this? Or is it just a case of a relative path being used where it shouldn't?

**Comment by memsharded** [comment]
You are right, maybe the command ``conan install <reference>`` shouldn't generate any file. Will check if possible not to add it.

**Comment by memsharded** [comment]
Implemented in #562, will be released in 0.14
