### ISSUE TITLE
Cannot `conan install` a specific package id or package revision

### ISSUE THREAD

**Issue by tmwa** [conan-io/conan#5451]
I would like to be able to install a specific package revision using `conan install`. Currently the revision syntax `#RREV:ID#PREV` is not supported (There was a reference made to this being intentional in https://github.com/conan-io/conan/issues/5368).

I would suggest the following behaviour:

Get the latest RREV and PREV for the package id determined from the settings and options (I think this is the current behaviour):
`conan install package/version@user/channel -pr settings` 

Get the latest PREV for the specific RREV, with the package id determined from the settings and options (I think this is the current behaviour):
`conan install package/version@user/channel#RREV -pr settings`

Get the latest PREV for the specific RREV and specific package ID given (user can not provide any settings or options):
`conan install package/version@user/channel#RREV:PackageID`

Get the specific PREV for the specific RREV and package id (user can not provide any settings or options):
`conan install package/version@user/channel#RREV:PackageID#PREV`

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
Hi @tmwa,

I mostly agree with the comments on letting users chose the package revision to use (currently not supported), but I fail to see the use case. Why would you like to get a specific package revision?

As I understand, the recipe revision is what really makes a difference, while the package revision is there to track binary changes for completeness (timestamps changing inside binaries, environment variables...). It might be hard to compare two binaries and spot the difference to know why the binary hash is different.

In the case of installing a specific package ID I don't see a necessity here the install command, as "install" means for Conan "install suitable packages for my configuration. For that case, you may use `conan download` although that command won't trigger the generators...

Could you clarify a little bit the use case you are facing? Why would you find important to chose a specific package revision? Why would you like to force the install of a specific package ID?

Thanks 😄

**Comment by tmwa** [comment]
> Why would you like to get a specific package revision?

Tracking down issues. If my tests start failing and the recipe hasn't changed (RREV) and the platform/configuration hasn't changed (package id) but I have one PREV that is broken and one that isn't, I would like to be able to download them both to my local machine and start debugging what has changed.

(I actually came across this limitation because I was trying to reproduce a bug in conan, related to package revisions already in cache. But once I had cleared the cache and it was working again, I couldn't find any way to restore it to the previous state!)

> "install" means for Conan "install suitable packages for my configuration. For that case, you may use conan download although that command won't trigger the generators...

I think this is part of a general problem that the conan commands are very confusing.

* `conan install X -g deploy` is usually what I use to get a specific package; it supports RREV but not ID or PREV.
* `conan download` seems to download all versions of the package, supports RREV, but doesn't support ID or PREV and doesn't support `deploy`.
* `conan get` also looks promising, it supports `RREV:ID:PREV`, but you have to manually specify `--raw conan_package.tgz` and pipe the output to file.

So maybe `conan download` is the correct place to add this functionality? But what I really want is the exact package revision dumped to the current directory to work with. Not put in the cache.

**Comment by danimtb** [comment]
Thanks for the answer.

I definitely see the need to be able to get the specific PREV of a package. Currently, there is no way to do that and I see it would be useful in the scenario you described.

``conan download`` is able to specify the package ID, and I think you can also write the PREV to download there too.

For the case of the install, it would be impossible to specify a package ID. ``conan install`` also downloads transitive dependencies that wouldn't be downloaded without providing the profile information as input. This is important to know optional requirements or specific options that affect transitive dependencies.

Related to this, I think you might find useful the lockfile feature described in #5412

**Comment by tmwa** [comment]
> `conan download` is able to specify the package ID, and I think you can also write the PREV to download there too.

Thanks, you are right. I missed it because it is inconsistent with the `reference#RREV:ID#PREV` syntax and is not documented:
```
conan download mypackage/1.0.0@user/stable#RREV -p ID:PREV
```

**Comment by danimtb** [comment]
yes, it is already changed for the new 1.17 release 😄

**Comment by danimtb** [comment]
Hi @tmwa,

Just a quick reminder that the lockfiles feature has already been released in Conan 1.17. Please give it a go, I think it solves what you are requesting in this issue https://docs.conan.io/en/latest/versioning/lockfiles.html

**Comment by danimtb** [comment]
I am closing this in favor of the lockfile feature as I think it covers the use case and it is  designed to reproduce a dependency graph and track issues in a build. Thanks!
