### ISSUE TITLE
Guard targets in conanbuildinfo_x.cmake

### ISSUE THREAD

**Issue by p-groarke** [conan-io/conan#5454]
Using cmake, it is very rare, but sometimes one may use `add_subdirectory` to add a sub project that uses the same conan libraries than the parent project. For example, gtest.

In that case, cmake will fail, as conan tries to redefine targets that were already set in the parent project. For example :

```
CMake Error at C:/blee/build/conanbuildinfo_multi.cmake:159 (add_library):
  add_library cannot create imported target "CONAN_LIB::gtest_gtestrelease"
  because another target with the same name already exists.
```

In this case, you cannot let the child subproject create the target, as the variables wont bubble up to the parent project.

You could easily fix this issue by guarding your target creation commands :
```cmake
if (NOT TARGET CONAN_PKG::gtest)
    # a bunch of set_property calls
endif() 
```

I'm unsure if you can have sub projects calling `add_library` with the same name (the error doesn't seem to mention that). If you can, then creating unique target names per project would probably be more robust. It would deal with version issues.

Note that the problem is not multiple dependencies in the library hierarchy, it is an issue with subdirectories that have multiple projects, some of which use the same libraries. Like multiple gtest executables or example executables.

**Comment by lasote** [comment]
Hi! Could you help us to understand why are you including a `CMakeLists.txt` that already includes a `conanbuildinfo.cmake`? Are you trying to develop several packages locally like the [workspaces](https://docs.conan.io/en/latest/developing_packages/workspaces.html) feature?

**Comment by p-groarke** [comment]
Sure. It is a standalone library, but is also used by another out-of-source project. I guess the setup resembles workspaces, though I don't use those.

**Comment by p-groarke** [comment]
Yes you understand exactly what the layout looks like. I agree the versioning may be problematic as well. If cmake lets you set unique target names (but identical library names), then that would fix the concern. 

Maybe you can simply check if the targets are defined and undefine them in the subproject. I believe that wouldn't trickle down to `PARENT_SCOPE`?

Or, maybe you could explicitly state to use `PARENT_SCOPE` versions when running `conan_basic_setup`.

In a way though, using different library versions in different sub projects *should* be pretty undefined (or even break).

**Comment by memsharded** [comment]
> In a way though, using different library versions in different sub projects should be pretty undefined (or even break).

Yes, exactly and as such it should be avoided. Such undefinitions or breakages will end in more reported issues and support. 

Are the different subprojects related? Do some of them use/consume the others as libraries? Or are they totally independent, and the fact that they are using the same package is a coincidence? If it is the former, then there is a big problem of missing information. There is a dependency graph with some parts that are not being modeled/managed by anyone, and that will always be a source of errors and require careful manual management. My question here is why not having just a common conanfile in the root project, that gets the dependencies and create just one set of targets? Then all the projects in the subdirectories will have access to those targets and will be able to link with the targets they need.

I am trying to understand how cmake deals with that, but so far it doesn't seem possible to play with the scope of the targets.

**Comment by p-groarke** [comment]
So, the main project ("project" in your example hierarchy) consumes liba. However, that is not the problem.

The problem is, liba can be used as an independent library. So liba has an executable, liba_tests which consumes gtest through conan. The main project "project" also has a test executable, which also consumes gtest through conan. BANG! dead.

Conan cmake macros don't support this scenario, where libraries are used in various ways. Note that this is completely safe and OK. The same may happen with accompanying examples, which might need boost for example. But what if "project" also requires boost? BANG! But it shouldn't, because there is no conflict.

So the issue really is, conan can't deal with sub projects that use the same dependencies, even though those dependencies *aren't part of the libraries*. Does that clear things up a bit? 

project.exe
project_tests.exe <- gtest
    libraryA
    libraryA_tests.exe <- gtest

**Comment by p-groarke** [comment]
This is a simple problem with a simple fix. What is the hold up?

**Comment by lasote** [comment]
Because it is not that simple. As @memsharded commented [here](https://github.com/conan-io/conan/pull/5475#issuecomment-510550032) that fix could be hiding other issues.

**Comment by grifcj** [comment]
I think CMake faces a similar issue with its target exports, but the scope is generally single package, not several like the Conan include.

If all targets are defined, it returns, as the assumption is that this is result of multiple inclusion. If partial set of the targets are already defined, then generates a fatal error, which is a way to detect erroneous configuration.

This is taken from GTestTargets.cmake, but any target export file contains this block.

```cmake
# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget GTest::gtest GTest::gtest_main GTest::gmock GTest::gmock_main)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)
```

I separately had opened an issue about include guard for conan_paths.cmake #5975. 

I think there's a distinction between multiple definition resulting from multiple inclusion (which seems like it should be safe like including C header multiple times or importing python module twice) and multiple definition because project added another target with same name either before or after including conan file. The latter should generate a config error.

**Comment by p-groarke** [comment]
This is fixed by using `cmake_find_package_multi`.
