### ISSUE TITLE
Linter warnings     WARN: Linter. Line 1: Unused tools imported from conans

### ISSUE THREAD

**Issue by amiya-elear** [conan-io/conan#5455]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi i am new to conan, i want to know that while exporting package to my local cache why i am getting WARN: Linter. Line 1: Unused tools imported from conans .and how to resolve this issue.

Thanks.

**Comment by lasote** [comment]
Hi! You can just remove the "tools" from the imports statement. It is not needed if you are not going to use. But anyway the linter is just to help you keep the recipes clean, not very important.

**Comment by amiya-elear** [comment]
but when i am building with normal build process i am getting warning warning: ‘end’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    &key, end - c, need_unescape, parser->flags & UCL_PARSER_KEY_LOWERCASE, but while i am building with conan i am not getting any warning , is there any way to get those warning while building with conan

**Comment by lasote** [comment]
That is a different question, right? Conan doesn't interfere (or do anything) with the warning of your compiler, they should be appearing the same way.

**Comment by danimtb** [comment]
I think this can be closed and continue the conversation about the second issue here #5465
Thanks!
