### ISSUE TITLE
cpu_count() does not work in a Docker environment

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#5464]
Issue: Our CI is using Docker containers to perform the builds. By default our containers are limited to 2 CPUs. The system has 22 CPUs available, so we can run 10 jobs in parallel (2 CPUs are left for the host system).

Our conanfile.py uses the CMake build helper with `parallel=True`. This relies on `tools.cpu_count()`, which in turn uses `multiprocessing.cpu_count()` to get the correct CPU count.
* https://docs.conan.io/en/latest/reference/build_helpers/cmake.html
* https://docs.conan.io/en/latest/reference/tools.html#tools-cpu-count

Within Docker environments `multiprocessing.cpu_count()` does not return the number of CPUs per container, but the overall number of CPUs (22 in our case). This freezes our build machine, as  10 jobs are run with 22 cores each.

Some info I found:
* https://bugs.python.org/issue36054
* https://github.com/tomMoral/loky/issues/111

Workaround: Right now we're setting the `CONAN_CPU_COUNT` for the runner, so this limits the CPU usage. An automatic discovery would be better though, as the number of CPUs being used could change.

This issue is about implementing a better way to count the available CPUs.

**Comment by uilianries** [comment]
>  This freezes our build machine, as 10 jobs are run with 22 cores each.

![conan is evil sometimes](https://media.giphy.com/media/xl5QdxfNonh3q/giphy.gif)

Probably we will need to detect if Conan is running in Docker as this case is very specific.
