### ISSUE TITLE
warning not showing while building with conan but with normal build its showing

### ISSUE THREAD

**Issue by amiya-elear** [conan-io/conan#5465]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi i am facing one issue with conan build , when i am building with normal build process i am getting warning warning: ‘end’ may be used uninitialized in this function [-Wmaybe-uninitialized]
&key, end - c, need_unescape, parser->flags & UCL_PARSER_KEY_LOWERCASE, but while i am building with conan i am not getting any warning , is there any way to get those warning while building with conan

**Comment by danimtb** [comment]
Hi @amiya-elear,

The CMake output should be displayed while you build any project with Conan. Could you please provide me with more information about your issue? I would need the Conan version you are using and the build system and if you are using any of the build helpers.

Thanks!

**Comment by danimtb** [comment]
ping @amiya-elear

**Comment by danimtb** [comment]
Closing this as we don't have enough information to reproduce the issue.
