### ISSUE TITLE
Option to treat lint errors as failure

### ISSUE THREAD

**Issue by martinm82** [conan-io/conan#5469]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

When calling `conan create ..` conan itself runs pylint to validate the recipe. In case there are some issues it is just printing some warning messages and continuing the build.

It would be great to have an option to treat linter warnings as errors and stop immediately the run.

```
Exporting package recipe
Linter warnings
    WARN: Linter. Line 10: Unused import testing from wildcard import
```

I checked the documentation but couldn't find anything about this topic (https://docs.conan.io/en/latest/integrations/linting/recipe.html)

I am using Conan 1.16.1 on macOS 10.14

**Comment by martinm82** [comment]
Ok, apparently there is an option in Conan to treat warnings as errors:

```
CONAN_PYLINT_WERR=1
```

**Comment by danimtb** [comment]
Hi @martinm82,

Currently, the pylint checks are built-in and there is no option to turn Conan warnings (Related to #4632) (there could be many minor warnings for different reasons).

However, we have considered in #4454 to move the linting functionality out of the Conan codebase and implement that king of things via [hooks](https://docs.conan.io/en/latest/extending/hooks.html).

In that sense, I think it would be better to control the linting warnings or error in a custom hook and this could be valid to make additional syntax checks.

**Comment by danimtb** [comment]
oh, I see. You are right, the variable is not documented. Thanks for pointing that out!

**Comment by martinm82** [comment]
Hm, I guess controling linting from hooks might be problematic as you most likely want to implement the linting part by yourself and instead re-use eg. pylint, right? Since you would depend on a pip package how would that look like on user side? Does the user need to care about installing the dependency? Or should it be done when installing the hook via `conan config install`?

**Comment by danimtb** [comment]
As Hooks are considered extensions of Conan, you will have to manage any python dependency they may have and install it in your environment. There are some open discussions about how to add configuration parameters or the python dependencies. If you have any idea or feedback, do not hesitate to share it on https://github.com/conan-io/hooks

**Comment by danimtb** [comment]
Documentation for this variable has been merged and will be available soon. Thanks! https://github.com/conan-io/docs/pull/1388
