### ISSUE TITLE
[question] Is it possible to append to remotes with `conan config install`

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#5471]
While developing our CI stack, we rely on different test environments, or even temporary environment on developers' machines.

All our conan environments are currently setup in an unified manner relying on `conan config install` pointed to a git repo. (By the way, great functionality!). 

One issue we are facing at the moment is that, on some environments, we don't necessarily want to point a subset of the remotes to the endoints we are using in production. Yet, [per the documentation](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install), calling `conan config install` again with a different `item` would overwrite the remotes entirely.

Is there a way to have an `item` only containing the specific remotes for a given environment, and use it to just complete/update the existing remotes?

**Comment by Minimonium** [comment]
It overwrites everything, yes. It's not possible to append/insert via config install. 
The thing is that the remote set and its order is important, recipes bind to remotes and the remote to bind is picked according to the order of remotes. Not overwriting would produce non-reproducible environments. 
Personally, I think that installing config should be a tool to provide a compatible Conan environment for users (usually for workshops as in your case).

**Comment by memsharded** [comment]
This would be the feature request in https://github.com/conan-io/conan/issues/13821, in the 2.X roadmap. I am closing this ticket as duplicated, lets follow in the other one, thanks.
