### ISSUE TITLE
Versioning the format of the lockfile?

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5473]
@memsharded 
I think we should add a field to a generated lockfile with the version, for example "0.1". 
I'm not thinking about making Conan compatible with older lockfiles necessarily, but it might be useful to:

 - Fail accordingly if the format is not supported.
 - Maybe other tools (I'm thinking about jfrog-cli and build-info, if maybe it could leverage from the lockfiles for a better build-info), but they will need to know the input format-version. (Very preliminary thoughts)
 
This is pretty speculative but I think it is real enough and cheap to introduce just a field. WDYT?

**Comment by memsharded** [comment]
You mean, something like https://github.com/conan-io/conan/pull/5490?

Just dumps the version number, and reads it. Until there is a use case how to use it, I won't add it to the model or anything like that.

**Comment by lasote** [comment]
Yes, that is enough and exactly what I mean.
