### ISSUE TITLE
conan create slow-down since 1.14

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#5477]
there is major slow-down running `conan create` command since conan 1.14.
for me, it used to take 30 minutes in conan <1.14, and now it takes 40 minutes for conan >=1.14. so, there is 10 minutes slow down between conan 1.13 and conan 1.14, which appears to be a regression issue for me.
benchmark is available in my repository: https://github.com/SSE4/conan-speed-test (simply runs `conan create` for dummy recipe - methods `sources`, `build`, `package`, `package_info` are empty)

local test results:
```
1.17.0
10.50user 2.02system 41:08.86elapsed 0%CPU (0avgtext+0avgdata 64212maxresident)k
12952inputs+298704outputs (45major+63448minor)pagefaults 0swaps

1.16.0
10.08user 2.09system 40:38.68elapsed 0%CPU (0avgtext+0avgdata 63916maxresident)k
344inputs+298704outputs (0major+62881minor)pagefaults 0swaps

1.15.0
10.87user 2.26system 41:02.47elapsed 0%CPU (0avgtext+0avgdata 63908maxresident)k
176inputs+298704outputs (1major+62746minor)pagefaults 0swaps

1.14.0
11.09user 1.91system 39:33.81elapsed 0%CPU (0avgtext+0avgdata 63656maxresident)k
2400inputs+299344outputs (24major+62302minor)pagefaults 0swaps

10.55user 1.67system 40:30.37elapsed 0%CPU (0avgtext+0avgdata 63484maxresident)k
16inputs+299344outputs (0major+61795minor)pagefaults 0swaps

10.38user 1.77system 40:15.47elapsed 0%CPU (0avgtext+0avgdata 63680maxresident)k
1720inputs+299344outputs (19major+62299minor)pagefaults 0swaps

10.84user 1.50system 39:56.88elapsed 0%CPU (0avgtext+0avgdata 63436maxresident)k
160inputs+299344outputs (5major+62286minor)pagefaults 0swaps

1.13.0
0.02user 1.74system 31:03.03elapsed 0%CPU (0avgtext+0avgdata 63464maxresident)k
15952inputs+299408outputs (64major+63260minor)pagefaults 0swaps

9.91user 1.51system 31:02.41elapsed 0%CPU (0avgtext+0avgdata 63400maxresident)k
40inputs+299408outputs (0major+62854minor)pagefaults 0swaps

9.49user 1.77system 30:41.90elapsed 0%CPU (0avgtext+0avgdata 63424maxresident)k
16inputs+299408outputs (1major+63179minor)pagefaults 0swaps

9.91user 1.78system 30:45.69elapsed 0%CPU (0avgtext+0avgdata 63512maxresident)k
17240inputs+299408outputs (70major+62782minor)pagefaults 0swaps

1.12.0
9.82user 1.78system 30:44.64elapsed 0%CPU (0avgtext+0avgdata 56936maxresident)k
32inputs+299344outputs (0major+54573minor)pagefaults 0swaps

1.11.0
10.45user 1.75system 30:18.53elapsed 0%CPU (0avgtext+0avgdata 56920maxresident)k
224inputs+299344outputs (7major+54504minor)pagefaults 0swaps

1.10.0
0.26user 1.87system 30:14.65elapsed 0%CPU (0avgtext+0avgdata 56744maxresident)k
320inputs+299344outputs (11major+54681minor)pagefaults 0swaps
```
running on travis confirms local results:
https://travis-ci.com/SSE4/conan-speed-test/builds/118853983

/cc @uilianries

To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by uilianries** [comment]
From my side (local machine):

```
1.17.0
17.98user 2.39system 44:10.17elapsed 0%CPU (0avgtext+0avgdata 63904maxresident)k
2904inputs+298704outputs (0major+63758minor)pagefaults 0swaps
```

**Comment by lasote** [comment]
Thanks for the investigation. I'll dig on it to see where the time went.

**Comment by lasote** [comment]
Some conclusions:
The time for downloading recipes and packages are HUGE with bintray. A regular `conan install` of the example takes forever. Given the huge amount of time spent on networking, the times for processing the graph are not relevant.
Probably (to confirm, if I don't die in the attempt) the different between Conan < 1.14 and newer are some additional remote checks at some point we introduced.
I'm trying to move recipes and binaries to a local repository and see what happen with the times.

**Comment by lasote** [comment]
With local Artifactory cached packages:

**Conan 1.17**

         11485696 function calls (11427945 primitive calls) in 13.712 seconds
         
          ncalls  tottime  percall  cumtime  percall filename:lineno(function)
          1550    4.058    0.003    4.058    0.003 {method 'recv_into' of '_socket.socket' objects}
            781    1.277    0.002    1.277    0.002 {method 'poll' of 'select.poll' objects}

**Conan 1.13**

         10114212 function calls (10015612 primitive calls) in 12.171 seconds

          ncalls  tottime  percall  cumtime  percall filename:lineno(function)
          1134    3.459    0.003    3.459    0.003 {method 'recv_into' of '_socket.socket' objects}
            713    1.214    0.002    1.214    0.002 {method 'poll' of 'select.poll' objects}


So, yes, Conan 1.13 is faster, but in your case the issue is Bintray, that takes a huge amount of time to do any operation if you reduce the network times to something "local" the difference on networking is half a second for networking and another second for something else.

So it is not that Conan has decreased the speed of 30% in general, probably only for the network operations. Now we do some more to simplify the flow and keep a more similar code between revisions and no revisions.
