### ISSUE TITLE
Trying to create a new package for a library with Meson build system.

### ISSUE THREAD

**Issue by squidfarts** [conan-io/conan#5478]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I wrote a new library for generic collection and I was trying to create a new package.
Assuming this command:  `conan create . retro-squid-colletions/0.1.0@squidfarts/testing`.

I am using Conan version 1.17.0 on MacOs with Meson build system.

```console
Last login: Thu Jul 11 11:30:49 on ttys001
Michaels-MacBook-Pro:~ shnitzel$ cd Developer/github/squidfarts/retro-squid-colletions/
Michaels-MacBook-Pro:retro-squid-colletions shnitzel$ conan create . retro-squid-colletions/0.1.0@squidfarts/testing
Exporting package recipe
Linter warnings
    WARN: Linter. Line 44: Unused tools imported from conans
retro-squid-colletions/0.1.0@squidfarts/testing: A new conanfile.py version was exported
retro-squid-colletions/0.1.0@squidfarts/testing: Folder: /Users/shnitzel/.conan/data/retro-squid-colletions/0.1.0/squidfarts/testing/export
retro-squid-colletions/0.1.0@squidfarts/testing: Exported revision: 68e083eb35f064bd0134af48032f881f
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

retro-squid-colletions/0.1.0@squidfarts/testing: Forced build from source
Installing package: retro-squid-colletions/0.1.0@squidfarts/testing
Requirements
    retro-squid-colletions/0.1.0@squidfarts/testing from local cache - Cache
Packages
    retro-squid-colletions/0.1.0@squidfarts/testing:bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583 - Build

retro-squid-colletions/0.1.0@squidfarts/testing: Configuring sources in /Users/shnitzel/.conan/data/retro-squid-colletions/0.1.0/squidfarts/testing/source
retro-squid-colletions/0.1.0@squidfarts/testing: Copying sources to build folder
retro-squid-colletions/0.1.0@squidfarts/testing: Building your package in /Users/shnitzel/.conan/data/retro-squid-colletions/0.1.0/squidfarts/testing/build/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583
retro-squid-colletions/0.1.0@squidfarts/testing: Calling build()

ERROR: Source and build directories must not be the same. Create a pristine build directory.
retro-squid-colletions/0.1.0@squidfarts/testing: 
retro-squid-colletions/0.1.0@squidfarts/testing: ERROR: Package 'bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583' build failed
retro-squid-colletions/0.1.0@squidfarts/testing: WARN: Build folder /Users/shnitzel/.conan/data/retro-squid-colletions/0.1.0/squidfarts/testing/build/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583
ERROR: retro-squid-colletions/0.1.0@squidfarts/testing: Error in build() method, line 66
	meson.configure()
	ConanException: Error 256 while executing meson "/Users/shnitzel/.conan/data/retro-squid-colletions/0.1.0/squidfarts/testing/build/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583" "/Users/shnitzel/.conan/data/retro-squid-colletions/0.1.0/squidfarts/testing/build/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583" --backend=ninja -Dprefix="/Users/shnitzel/.conan/data/retro-squid-colletions/0.1.0/squidfarts/testing/package/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583" -Dlibdir="lib" -Dbindir="bin" -Dsbindir="bin" -Dlibexecdir="bin" -Dincludedir="include" -Dcpp_std="none" -Ddefault_library="static" --buildtype=release
Michaels-MacBook-Pro:retro-squid-colletions shnitzel$ 
```

**Comment by memsharded** [comment]
Hi @squidfarts 

The key is the error message, it is an error that it is being raised by Meson, and Conan is just stopping the build of the package:

```
ERROR: Source and build directories must not be the same. Create a pristine build directory.
```

Meson does not allow in-source builds. The default behavior of Conan is to copy all sources to a ``build/<binary_ID>`` folder, and then build there. This is done this way as default to guarantee that the sources are always clean, because there are some builds that alter the sources. You can try different alternatives:

- If you are 100% sure that the build does not change the sources, you can define ``no_copy_source=True`` in your recipe: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#no-copy-source. This will have a double effect, will make the build and source folder different, and will optimize a bit the package creating avoiding an extra copy
- If that doesn't work or not possible, you need to make sure to put the sources inside a "source" folder, and the build in a "build" sibling folder, in the conan cache the layout would be like:

```
    <package>
             export
                   conanfile.py
             source
                   ...
             build/<id1>
                   src
                        //sources here
                   build
                        // build here
             package/<id1>
```
Depending on how you are working with the recipe inside the repo or outside the source repo, you might achieve that final layout in different ways, like using exports, doing a move to a "src" subfolder in the ``source()`` method, etc.

Please let me know if this helps.

**Comment by squidfarts** [comment]
Would that work for [Retro-Squid Colletions](https://github.com/squidfarts/retro-squid-colletions)?

**Comment by memsharded** [comment]
Yes, I think so. You are missing to export the sources to the package, try this:

```diff
diff --git a/conanfile.py b/conanfile.py
index b7b47f5..75bd9d1 100755
--- a/conanfile.py
+++ b/conanfile.py
@@ -60,6 +60,8 @@ class PackageConan(ConanFile):
     options = {"shared": [True, False]}
     default_options = "shared=False"
     generators = "pkg_config"
+    no_copy_source = True
+    exports_sources = "*"

     def build(self):
         meson = Meson(self)
diff --git a/meson.build b/meson.build
index 8000414..7df0e22 100755
--- a/meson.build
+++ b/meson.build
@@ -113,7 +113,7 @@ if cc.get_id() == 'msvc'
         '/wd4146', # unary minus on unsigned (beware INT_MIN)
         '/wd4244', # lossy type conversion (e.g. double -> int)
         '/wd4305', # truncating type conversion (e.g. double -> float)
-        mesno.get_supported_arguments(['/utf-8']), language: args_for_langs)
+        meson.get_supported_arguments(['/utf-8']), language: args_for_langs)
 endif
```

Note you have a typo in the meson.build file. Also, I couldn't fully build it because I don't have meson 0.51, and the package is not there yet, I'd suggest opening an issue in https://github.com/bincrafters/conan-meson_installer to get support for that latest Meson, it seems it is in testing but not uploaded yet.

Please let me know if it works, thanks!

**Comment by squidfarts** [comment]
No such luck.  But on the good side there is this new error message, maybe getting closer to resolving this issue.
  
I'm not sure why this should be posable since the `conanfile.py` is in the same directory.  
```console
meson.build:139:0: ERROR: File conanfile.py does not exist.
```

**Comment by memsharded** [comment]
I moved a bit further doing these changes:

```diff
diff --git a/meson.build b/meson.build
index 8000414..dc9ef14 100755
--- a/meson.build
+++ b/meson.build
@@ -113,7 +113,7 @@ if cc.get_id() == 'msvc'
         '/wd4146', # unary minus on unsigned (beware INT_MIN)
         '/wd4244', # lossy type conversion (e.g. double -> int)
         '/wd4305', # truncating type conversion (e.g. double -> float)
-        mesno.get_supported_arguments(['/utf-8']), language: args_for_langs)
+         language: args_for_langs)
 endif


@@ -137,5 +137,4 @@ install_data(
     install_dir: join_paths(get_option('datadir'), meson.project_name()))

 install_data(
-    sources: 'conanfile.py',
     install_dir: meson.source_root())
```

Basically:
- removed the mesno.get_supported_arguments(['/utf-8']), first the typo **mesno** was still there, and there it was not recognized the ``get_supported_arguments``.
- No idea what is the intention about the conanfile.py, but the conanfile.py it is not in the build folder. The conanfile.py is common to all the binaries, and it is not copied to the temporary build folder, so when meson was trying to get it it was failing. It is in the same user directory, but the package is not created there. I suggest going to the cache and inspect it , it would be in ``<userhome>/.conan/data/pkg/version/user/channel``.  This section of the docs might help: https://docs.conan.io/en/latest/creating_packages/understand_packaging.html

Moved past that point, I am getting compiler syntax errors like:
```bash
[1/4] Compiling C object lib/src/retro-squid/colletions/699eee6@@retro-squid-cllection@sta/queue.c.obj.
FAILED: lib/src/retro-squid/colletions/699eee6@@retro-squid-cllection@sta/queue.c.obj
cl @lib/src/retro-squid/colletions/699eee6@@retro-squid-cllection@sta/queue.c.obj.rsp
..\\..\\source\\lib\\./include\retro-squid/utils/common.h(56): error C2061: syntax error: identifier 'isEmpty'
..\\..\\source\\lib\\./include\retro-squid/utils/common.h(56): error C2059: syntax error: ';'
```
I am using VS2017, could be that?

So at this point, I would say those are more related to the specifics of the build system, not that related to conan. I'd suggest to keep it as simple as possible, remove all those things, and make sure it even compiles without conan at all (it doesn't have dependencies, if it had dependencies then it would be a different story). Please let me know if this helps, thanks!

**Comment by squidfarts** [comment]
Thanks for the help got things to work with your suggestions.

**Comment by memsharded** [comment]
Great! Thanks for telling. Do not hesitate to reach and submit new issues if you have further questions,  cheers.
