### ISSUE TITLE
conan builds package instead of download

### ISSUE THREAD

**Issue by drozel** [conan-io/conan#5488]
Hi, i get strange behavior from conan:
i have build qt package ind uploaded it to artifactory:
![image](https://user-images.githubusercontent.com/6229397/61176901-22101680-a5c9-11e9-81b9-9f84d0489d38.png)
but on `conan install --build=missing` of dependent package i get:
`    qt/5.12.4@bincrafters/stable:b3272c8a8ab0eea327ebad36854f2c010e221f22 - Build`
and then build the package again.

Package id of package on artifactory and built package are the same.
What is wrong? 

Conan 1.17.0
Python 3.6.9

To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Minimonium** [comment]
Hi, can you check please what's the remote qt is bound to? 
For example:
```
$ conan remote list_ref
...
qt/5.12.4@bincrafters/stable: bincrafters
...
```
Projects are bound to remotes and can't pull artefacts from different ones.

**Comment by drozel** [comment]
> Projects are bound to remotes and can't pull artefacts from different ones.
does it mean, it's impossible to upload bincrafter's binaries to my local artifactory?

**Comment by Johnnyxy** [comment]
If you have multiple remotes in your remote list and you want to upload to a specific remote then you can specify the remote as parameter with the ```upload``` command ([see docs](https://docs.conan.io/en/latest/reference/commands/creator/upload.html#conan-upload)).

```
conan upload RECIPE-REFERENCE -r=REMOTE_NAME
```

**Comment by drozel** [comment]
@Johnnyxy,
That's what I do. My problem is that Conan don't use my remote I uploaded to and build the qt package according to recipe from bincrafters again

**Comment by Minimonium** [comment]
@drozel you need to rebound your qt package, yes. 
```
$ conan remote update_ref OpenSSL/1.0.2i@conan/stable local-remote
```
https://docs.conan.io/en/latest/reference/commands/misc/remote.html

**Comment by drozel** [comment]
@minimonium,
Package bounding seems to be local info. My problem is I building in clean docker container every time and I don't know which packages exist on my local artifactory. The package can be built there and can only be on bincrafters.
Would it help if I have my remote in the first place and then bincrafters? Conan should first try with my remote and only if qt is not known, go to bincrafters?
Sorry,I can't try this right now, I am not on pc

**Comment by Minimonium** [comment]
@drozel ah, yes, that's too!
Conan looks up remotes in the order they're listed. You should insert your remote first to make it look it up vendored packages there first. 
```
$ conan remote add remote_name remote_url --insert
```

**Comment by drozel** [comment]
@minimonium
Yeah, then it will help me.
I expected Conan go further through the remotes list searching for binary even if recipe was found on bincrafters remote instead of building it immediately

**Comment by Minimonium** [comment]
Well, _well_. The idea currently is that one can have their own patched/verificated versions of stuff and they want to use them, so they insert their remote first. If Conan would walk over every remote ignoring the patched version because of no binaries it would be a very frustrating behaviour. There are a lot of configurations so it's not always possible to prebuild every one of them. Also it's non-trivial to compare to recipes I guess in different remotes.

**Comment by drozel** [comment]
@Minimonium
Ok,I understand.
My current usecase is completely covered by current functionality.
Thank you for explanations!

**Comment by memsharded** [comment]
It is true that the remote binding rules are not always that evident. Thanks for the feedback, it shows that maybe that could be improved, I created #5489 for it.
