### ISSUE TITLE
Editable packages interfere (fail) with remote registry commands

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5491]
Working with current conan `develop` branch

Having a package in editable mode:

```
⇒  conan editable list
header/1.0@user/channel
    Path: /..../header
    Layout: /..../header/layout
```

and trying to remove a remote:

```
⇒  conan remote remove conan-center
Traceback (most recent call last):
  File "..../conans/client/command.py", line 1762, in run
    method(args[0][1:])
  File "..../conans/client/command.py", line 1411, in remote
    return self._conan.remote_remove(remote_name)
  File "..../conans/client/conan_api.py", line 76, in wrapper
    return f(*args, **kwargs)
  File "..../conans/client/conan_api.py", line 885, in remote_remove
    return self._cache.registry.remove(remote_name)
  File "..../conans/client/cache/remote_registry.py", line 300, in remove
    with self._cache.package_layout(ref).update_metadata() as metadata:
AttributeError: 'PackageEditableLayout' object has no attribute 'update_metadata'

ERROR: 'PackageEditableLayout' object has no attribute 'update_metadata'

```

In the file `conans/client/cache/remote_registry.py` there are several places where we are calling the `update_metadata` function:

```python
        for ref in self._cache.all_refs():
            with self._cache.package_layout(ref).update_metadata() as metadata:
```

----

**Proposed solution**: add a context manager to empty the editable package list before calling these functions related to remotes, so we get the actual layout instead of the PackageEditable one. My understanding is that we want to work with the metadata of the underlying package, it doesn't matter if it is in editable mode or not for these commands.

**Comment by lasote** [comment]
Duplicated of https://github.com/conan-io/conan/issues/5424 / https://github.com/conan-io/conan/pull/5461?

**Comment by jgsogo** [comment]
btw, nice to see the same approach for the solution 😄
