### ISSUE TITLE
`conan upload` with exact reference uploads all packages

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#5494]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

`Conan version 1.17.0`
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

When using a direct reference to a `conan upload` command, it is still uploading all references.

Here is an example, where I'm trying to compress before I run the actual upload.
Notice that even though an exact reference (`27f50b1bf6c6a1273065af170f00a1132f9e5732`) is passed, it still runs for all packages `Uploading package 1/6`

Unsure this is because of use of `-all`, but I thought that was just for actually uploading the packages rather than just the recipe.

```
00:22:05.670  conan upload PackageName/1.1.16+ga0826c6@user/channel:27f50b1bf6c6a1273065af170f00a1132f9e5732 --all -r remoteName -c --check --skip-upload
00:22:05.975  Uploading to remote 'remoteName':
00:22:05.975  Uploading PackageName/1.1.16+ga0826c6@user/channel to remote 'remoteName'
00:22:05.975  Uploading package 1/6: 216dcbf61526c7e0676548b3d0b2b94251a389e9 to 'remoteName'
00:22:06.279  
Checking package integrity...                                         
Package integrity OK!                                                 
00:22:06.279  Uploading package 2/6: 27f50b1bf6c6a1273065af170f00a1132f9e5732 to 'remoteName'
```

**Comment by Mark-Hatch-Bose** [comment]
Another example with a simple upload
```
00:30:38.409  + conan upload PackageName/2.6.21+g8b51524@user/channel:fe6871afd0d404545fdebba09926f3b513b6a586 --all -r remoteName -c
00:30:38.714  Uploading to remote 'remoteName':
00:30:38.714  Uploading PackageName/2.6.21+g8b51524@user/channel to remote 'remoteName'
00:30:39.787  Recipe is up to date, upload skipped
00:30:39.787  Uploading package 1/6: fe6871afd0d404545fdebba09926f3b513b6a586 to 'remoteName'
00:30:40.863  Package is up to date, upload skipped
00:30:40.863  Uploading package 2/6: 2f0b667b2c3557be4818a6efcd99bd830f9a9172 to 'remoteName'
00:30:41.938  Package is up to date, upload skipped
00:30:41.938  Uploading package 3/6: 44ba15f44cdf1960070b1506d1261a56028e888f to 'remoteName'
00:30:43.085  Package is up to date, upload skipped
00:30:43.085  Uploading package 4/6: 67150b747f7da1537c212fe2a9de4d0c53481e9a to 'remoteName'
00:30:44.161  Package is up to date, upload skipped
00:30:44.467  Uploading package 5/6: ebb0a2e0acf755ac06499a5379b00174bf752c2a to 'remoteName'
00:30:45.541  Package is up to date, upload skipped
00:30:45.541  Uploading package 6/6: 2ceab66eebaf038997530c1f0ae3142a2498eea5 to 'remoteName'
00:30:46.618  Package is up to date, upload skipped
```

**Comment by memsharded** [comment]
Hi @Mark-Hatch-Bose 

You are just providing the recipe reference, with revision, but the recipe reference and then saying to upload all ``--all`` binaries. So it seems that it is working fine.

Try uploading providing the full package reference: ``pkg/version@user/channel#rrev:binaryID#prev``
I think that you might skip the #prev and it will work too. 

Let me know if this helps, please. Thanks!

**Comment by Mark-Hatch-Bose** [comment]
Thanks for the help.

I had misunderstood `--all`.
I had thought it was for both upload packages and recipes. Since without it, it was only uploading a receipe.
Since I'm passing a specific package_id, you don't need `--all` to upload the package.

Fixed my issue, closing this.

**Comment by memsharded** [comment]
Happy to help!
