### ISSUE TITLE
 Missing clear documentation to use conan_api.upload with a package id 

### ISSUE THREAD

**Issue by Siron777** [conan-io/conan#5501]
Hi,

I am trying to upload a package using the upload method of conan_api.py as I would do with the following working command: 
`
conan upload -r=ai zlib/1.2.11@AI/extern:811010fc454bb85ee1e902a530feb1ec906ff80f --force --all`

And it was very difficult for me to determine that the following call was not correct:
`conan.upload(pattern="zlib/1.2.11@AI/extern:811010fc454bb85ee1e902a530feb1ec906ff80f", package=True, policy="force-upload")`

Instead the correct call is:
`conan.upload(pattern="zlib/1.2.11@AI/extern#811010fc454bb85ee1e902a530feb1ec906ff80f", policy="force-upload")`

Would it be possible to have some sort of documentation on those tricky differences or to improve the error messages? The error messages given are not very helpfull:

- **conans.errors.ConanException: Binary package zlib/1.2.11@AI/extern:True not found** for package=True
- **conans.errors.NotFoundException: No packages found matching pattern 'zlib/1.2.11@AI/extern:811010fc454bb85ee1e902a530feb1ec906ff80f'** for the wrong separator
- **conans.errors.ConanException: -p parameter only allowed with a valid recipe reference, not with a pattern** for both

I have conan 1.17.0 with python 3.7.4 in x64. I am under windows 7.

**Comment by jgsogo** [comment]
Hi, @Siron777 

The class and the methods in `conan_api.py` are not documented and it is not a public interface to use Conan. At least before Conan `v2.0` we cannot provide any commitment about those methods, their parameters and the data or errors returned by them. I'm sorry, but we cannot make a commitment about stability at that programmatically level yet.

**Comment by Siron777** [comment]
Hi jgsogo,

I am amazed to find that API in python, and I totally understand the need to wait for conan V2.0 to have the stable API. Meanwhile, I will continue using the V1 API at my own risk.

Thank you for your work.

**Comment by jgsogo** [comment]
Thanks for your comprehension, @Siron777 . Although we try to maintain that class as stable as possible (we use it ourselves for conan-package-tools), from time to time it may suffer important changes, like https://github.com/conan-io/conan/pull/5517/files

I'm closing this issue.... at least until Conan v2.0 ;D
