### ISSUE TITLE
`graph lock` with `-b outdated` - always rebuilds top level

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#5503]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

```
Conan version 1.17.0

Distributor ID:    Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:    16.04
Codename:    xenial
```

**1. What is the difference of passing `-b outdated -u` to `conan graph lock` vs. `conan create -l conan.lock`** 
  - Should you even pass `-b` at all to `conan graph lock`?
  - Example below, should I be using `-b oudated` in the graph lock

**2. Top level project is always built, even if doesn't need to build.**
`conan graph lock . -pr <profile> -u`
`conan create . user/channel -l conan.lock -b outdated`
This always causes the top level conan project to be `Build` as part of `conan create`, even if it is up to date with the remote.

First conan create using lockfile:
`conan create . user/channel -l conan.lock -b outdated`
```
Package/2.25.1-6+gcbf7b2f@user/channel: Revision deduced by 'auto': cbf7b2f72105aa55d18946da5281d42baa4d7fbe
Package/2.25.1-6+gcbf7b2f@user/channel: The stored package has not changed
Package/2.25.1-6+gcbf7b2f@user/channel: Using the exported files summary hash as the recipe revision: 680210e2cc10f38a4cddfb98fb8e7f1d 
Package/2.25.1-6+gcbf7b2f@user/channel: Exported revision: 680210e2cc10f38a4cddfb98fb8e7f1d
```
Second create using lockfile, notice still builds top level package:
`conan create . user/channel -l conan.lock -b outdated`
```
    Package/2.25.1-6+gcbf7b2f@user/channel:acc431b28203657af0242f304083b07adf825c4a - Build
```
Conan create without using lockfile, demonstrating it realizes it is already up to date 
`conan create . user/channel --pr <profile> -b outdated `
```
 Package/2.25.1-6+gcbf7b2f@user/channel:acc431b28203657af0242f304083b07adf825c4a - Cache
```

**3. Mismatch between lock and graph randomly**
I need to debug this more, not clear what is causing this mismatch currently. Let me know if I can provide any logs to help gather more information. Same flow as above, generate lockfile, then create using lockfile
```
ERROR: Mistmatch between lock and graph:
Lock:  DependencyB/2.0.3+gb91132d@BoseCorp/master#0:24be08b384125dd90d34413d92eaae085825c84e
Graph: DependencyB/2.0.3+gb91132d@BoseCorp/master#0:24be08b384125dd90d34413d92eaae085825c84e#030919383cf9097ba7ed8ca63233f188
```

**Comment by jgsogo** [comment]
HI @Mark-Hatch-Bose, I'm not very experienced with the new graph lock feature and maybe that is the reason why I'm not understanding all your doubts.

1. I agree with you, I think that `-b` argument doesn't make sense for the `conan graph lock` command as it is not going to trigger any build action, just create the lock file.

3. I'm also getting that mismatch after running these commands:
   * `conan graph lock .`: it creates the `conan.lock` without revisions for the main package and with user/channel=None/None
   * `conan create . issue/testing -l conan.lock -b outdated`: ERROR with the mismatch on the package revision. It surprises me that it shows user/channel in the lock line although that data is not in the `conan.lock`.
   * `conan create . issue/testing -l conan.lock`: it successfully build main package and modifies the `conan.lock` file adding user/channel, recipe revision and package revision.

2. I'm not able to reproduce the behavior you describe: if I type `conan create . user/channel -l conan.lock -b outdated` after the `conan graph lock .` I'm always getting the mismatch error.

**Comment by memsharded** [comment]
Yes, it makes sense to pass --build to graph lock, because the package IDs that are stored in the graph lock, depends on what binary is being used, and that might change if you are building some of the packages in the graph, so the lockfile will know it.

**Comment by jgsogo** [comment]
Yes, you are right, given the new mode for the [package revisions](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html) (`package_revision_mode()`), the package_id can depend on the package revision of its dependencies 👌  So this argument is needed. Thanks for the comment.

**Comment by Mark-Hatch-Bose** [comment]
Thanks! I will pass `-b outdated` to the graph lock command.
NOTE: I have not explicitly enabled revisions.

I have come up with a reliable way to cause "mismatch error".
```
conan remove <old package> -f
conan graph lock . -b outdated -u
conan create . $USER/local -l conan.lock -b outdated
conan graph lock . -b outdated -u
conan create . $USER/local -l conan.lock -b outdated
```

**Comment by jgsogo** [comment]
Thanks a lot, @Mark-Hatch-Bose, for taking the time to investigate it and provide the set of commands to reproduce the issue. I've tried it myself (with `general.revisions_enabled=0`) and it is failing, probably it is something we need to fix, but I need @memsharded to confirm.

**Comment by Mark-Hatch-Bose** [comment]
Just some context for the above.

I’m investigating using lock files to try and lock versions of common packages between conan create calls (for different profiles built sequentially). First I try and lock all the builds just to make the “window” of dependencies updates  to be as small as possible, then I plan on checking the lock files for inconsistencies. You can imagine that downstream packages are being exported all the time, but I want to grab the same version for a particular  set of  sequential builds that include different profiles (“x86_64”, “x86” etc.). I don’t want the recipe uploaded unless all profiles pass their builds, and I want them to be consistent in terms of downstream dependency versions. Currently if I use -u for each sequential create call, we could grab newer dependencies in the next profile.

**Comment by memsharded** [comment]
``-b outdated`` no longer exist with revisions (long time ago), removed in 2.0
