### ISSUE TITLE
Question: Visual Studio 2019 installation: build compiler version 15 & 16

### ISSUE THREAD

**Issue by nesc1** [conan-io/conan#5508]
Hi don't know if this is the best place to put this question, but if it not sorry :)

I've uninstalled visual studio 2017 and tried visual studio 2019, and i want to compile my conan packages for both compiler versions 16 and 15 using profiles.
When i try to compile conan packages for 15 (compiler.version=15) i found the following problem:
```
ERROR: zlib/1.2.11@conan/stable: Error in build() method, line 107
        cmake.configure(build_dir=".")
        ConanException: VS non-existing installation: Visual Studio 15
```

I've installed along vs2019 both platform toolsets (Visual Studio 2017 (v141) and Visual Studio 2019 (v142)) and with vs IDE i can change from one to another.

My question is: do i need to reinstall vs2017 in order to fix my problem or i'm missing some configuration on vs2019?!

Thansk for your help
Nuno

**Comment by jgsogo** [comment]
In order to use the MSBuild 15 you need the build tools for that version. If you have uninstalled everything related to VS2017 then you no longer have that version of the build tools (VS2019 uses v16). I'm not sure if you can install only the build tools without installing vs2017.

**Comment by nesc1** [comment]
hi @jgsogo thanks for your reply.... yes i did a full uninstall of vs2017 and unfortanally and strangelly I can not find the build tools only for vs2017, it seems that i need to reinstall the vs2017... so stupid...

**Comment by jgsogo** [comment]
Take a look at this StackOverflow answer: https://stackoverflow.com/a/52729945/837816. Please, if you finally install just the build tools, let me know if Conan is able to find the compiler. Thanks!

**Comment by nesc1** [comment]
Thanks @jgsogo that did the work :) the problem is that I was already there, but i did not see the downloads because my subscription does not allow me, then I use a free subscription and then I was able to download build tools for 2017 and that did the work, I now can compile conan packages for vs compiler 15 and 16 only by changing the profile and only have one ide installed.
