### ISSUE TITLE
How to make sure libcxx setting is correct?

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#551]
I created a [recipe](https://github.com/sourcedelica/conan-recipes/tree/master/caf) for an open source library that we use and built the binary libraries on Linux, but when I ran `test_package` I got link errors.  I tracked it down to a GCC ABI incompatibility.  The package was built with the new C++ ABI but the `test_package` was using the old ABI.  When I use `conan test_package -s compiler.libcxx=libstdc++11` it fixed the problem.   I did not use `-s compiler.libcxx` to build the library package.  Actually I didn't touch the package's CMake configuration at all.  The only integration with Conan was done through `conanfile.py`.

How can I force the library package to be built with `-s compiler.libcxx=libstdc++11` so that metadata is in the Conan repo and clients will have to build with `-s compiler.libcxx=libstdc++11` in order to pick up the right package?  

#217 is similar and this might be a duplicate.

**Comment by sourcedelica** [comment]
Forgot to add, I was using Ubuntu 16.04 with GCC 5.4.0.

**Comment by lasote** [comment]
Yes, it's similar to #217. If you don't want to allow compiling the library with libstdc++ because it won't work without it, you can raise an exception in your conanfile recipe.

**Comment by sourcedelica** [comment]
Sounds good. Do you know of a way to check if the current system uses libstdc++11 by default, short of compiling and running a test program that returns the value of the `_GLIBCXX_USE_CXX11_ABI` macro?

**Comment by lasote** [comment]
In gcc > 5 the default ABI is libstdc++11. Maybe the test program is the best choice to ensure it.

**Comment by sourcedelica** [comment]
I've got a first cut at an ABI checker here: https://github.com/sourcedelica/conan-recipes/blob/master/caf/conanfile.py#L24.  I'll close this.

**Comment by sourcedelica** [comment]
In the docs for `test_package` it says:

> This is intended to do a test of the package, not to run unit or integrations tests

What would a test of the package typically consist of?   I'm assuming a smoke test that makes sure all of headers and libraries are in place, so the test program would need to include calls into all the relevant APIs.  In that case a very small subset of unit tests might be applicable?
