### ISSUE TITLE
[feature request] support testing conan package without the need for exporting it

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#5512]
This idea was first discussed in issue #5498 [in this comment](https://github.com/conan-io/conan/issues/5498#issuecomment-512525224).

Basically, the conan package development flow is to test each conan recipe step with dedicated commands, such as `conan install`, `conan build` and `conan package`. Each of these commands have flags that can point the step to the folder containing the results of the previous step, such as `--install-folder`, `--build-folder` and `--package-folder`.

However, `conan test` is missing support for those flags and requires that package under test is always exported into the conan cache. This is not always convenient, as is the case on CI server where same conan cache is shared between multiple executors and it is not desired to export the package into the local cache until the test confirms that the package works.

Therefore, I suggest that `conan test` should also learn to support `--package-folder`. The command should then perform the test of the conan package given in the folder pointed to with the `--package-folder` parameter. During the development of the packages and during the testing of the package on the CI, thus the cycle would be complete: you would first call the `conan install` to install the package into the specific (probably temporary) folder, then `conan build` to test the building of the package, then `conan package` to test that packaging works and finally the `conan test` to test that the package created with `conan package` can be consumed.

Also, in order to ease up the development, I also suggest that `conan package` should somewhere output the calculated package ID (either as its stdout output or into some file given by the parameter). That would make debugging of the implementation of the `package_id` method much much easier (and possibly testable on the CI).

**Comment by jgsogo** [comment]
Hi, @DoDoENT. The aim of testing the package is to actually test the package, and this is something we need to do using the package from the cache. The local folder may contain more files so the test could give false positives.

I'm not saying this is not a useful feature, I will add it to the backlog, but it cannot get a high priority and it is going to be quite complex. Unless more users request it, I'm afraid it is not going to be addressed soon.

**Comment by DoDoENT** [comment]
> The aim of testing the package is to actually test the package ...

Exactly my point.

> ... and this is something we need to do using the package from the cache

Why? Isn't the point of `conan package` to produce the exact files into given local folder as it would produce into the local cache? So why not giving the possibility to test the package as produced by the `conan package` command?

> The local folder may contain more files so the test could give false positives

I think the same argument could also be given for `conan build` and `conan package`. Technically, the installation folder given to `conan build` via `--install-folder` could also contain more files and even cause build errors. The same holds for `conan package` - if folder given by `--build-folder` contains more or fewer files than actually expected, the result would be incorrect. Yet, both `conan build` and `conan package` are part of the [conan package development flow](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html#).

I am just suggesting that the `conan export-pkg` should come **after** `conan test` in the package development workflow, as you generally do not want to export the package for which test fails.

Also, I don't understand why you tagged this issue with _complex: high_. I'm not very familiar with the conan codebase, but this change looks quite simple to me, as an outsider. Generally, if `--package-folder` is given to the `conan test` command, use that folder instead of calculating the path in the local cache using the settings and options. Is there something else I am not aware of, which increases the complexity of the issue?

**Comment by jgsogo** [comment]
Conan builds a _special_ graph to test a package: we add the testing `conanfile.py` as the root node and put a requirement to the package to be tested. It works out-of-the-box if the package is already in the cache (although the implementation is not as straightforward).

After sleeping on it, maybe it is not so hard as I initially thought. To achieve this new behavior we could do something similar to the editable packages, but temporary: add a redirection in the cache to the local package folder. This is a naïve proposal, I'm afraid it is not going to be so easy (local commands are always complicated).

**Comment by KerstinKeller** [comment]
I think this is a very good idea. I would also consider a build of a package as successfull, if also the tests have passed. I wouldn't want this package to be available for anybody else at that point.

We're currently trying to figure out a good CI strategy for our builds, and this is generally a paint point. If you build and consume the same packages on the same machine, they do share the same cache. And I really want to avoid that libB picks up on any not successfully tested packages of libA.

However, right now we consider only ever building on a `testing` channel and afterwards promoting to `stable`.

**Comment by memsharded** [comment]
Closing this as inactive and not planned, multi-level cache would be extremely challenging for the provided value.

Conan 2.0 have other possible ways:
- ``conan create`` works in ``editable`` mode if necessary, not creating package in the cache at all
- ``conan cache save/restore`` allows to move packages around without uploading to the server
- The server repo->repo promotion mechanism is recommended for building things in CI, have binaries available for other jobs, but not making the binaries available for other developers or other jobs
- Lockfiles are much easier to manage in 2.0, recommended to guarantee that only desired dependencies are used
- Channels are no longer recommended for package variability/maturity stages
