### ISSUE TITLE
Question: How to use env var through commande line to specify name and version ?

### ISSUE THREAD

**Issue by Bawen34** [conan-io/conan#5516]
Hello everybody,

I am using Conan 1.17 and I am trying to pass environment variables through command line like:
`conan install conanfile.py --profile myProfile -s build_type=Release  --env myName=Name --env myVersion=1.0`

But, I am not able to retrieve them in my conan recipe with this code:
```
def get_name():
    try:
        return self.env_info.myName
    except Exception as e:
        return None

def get_version():
    try:
        return self.env_info.myVersion
    except Exception as e:
        return None
		
class ClassConan(ConanFile):
    settings = "os", "build_type", "arch"
    generators = "cmake", "txt"
    url = "None"
    license = "None"
    name = get_name()
    version = get_version()

    def package(self):
        self.copy("*.h", dst="include", src="inc/common", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = `tools.collect_libs(self)
```

I get the following error when trying to export the package:
`ERROR:` Value provided for package name, 'None' (type NoneType), is not a string`

**Comment by Johnnyxy** [comment]
Hi there,
I think you misinterpreted the use of ```env_info```. This attribute of a ```ConanFile``` is only available in the ```package_info(self)``` function ([see here](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#env-info)). This is used to provide environment variables to recipe consumers, like setting the PATH environment variable. The ```env_info``` attribute and ```-e / --env``` parameter are unrelated.

You cannot pass the name/verision/user/channel (reference) of a recipe as parameters via command line with the [install command](https://docs.conan.io/en/latest/reference/commands/consumer/install.html#conan-install). The docs state: 

>Environment variables that will be set during the package build.

This means while building a package ([build step](https://docs.conan.io/en/latest/reference/conanfile/methods.html#build)) those environment variables are set not before.

Could you elaborate a little bit your use case why are you passing those informations via command line which normally belong in a recipe?

If you really do it that way you could use real environment variables (but this is not recommended):
```batch
set myName=myName
set myVersion=1.0
conan install conanfile.py --profile myProfile -s build_type=Release
```

```python
import os

def get_name():
    return os.environ.get('myName', None)

def get_version():
    return os.environ.get('myVersion', None)
		
class ClassConan(ConanFile):
    settings = "os", "build_type", "arch"
    generators = "cmake", "txt"
    url = "None"
    license = "None"
    name = get_name()
    version = get_version()

    def package(self):
        self.copy("*.h", dst="include", src="inc/common", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

**Comment by lasote** [comment]
The `conan install` command accepts the reference as a second argument after the `path` to the conanfile:

```
positional arguments:
  path_or_reference     Path to a folder containing a recipe (conanfile.py or
                        conanfile.txt) or to a recipe file. e.g.,
                        ./my_project/conanfile.txt. It could also be a
                        reference
  reference             Reference for the conanfile path of the first
                        argument: user/channel, version@user/channel or
                        pkg/version@user/channel(if name or version declared
                        in conanfile.py, they should match)
```

So you can run `conan install . lib/1.0@conan/stable` for a local conanfile.
