### ISSUE TITLE
ConfigureEnvironment is not adding defines from dependencies to CFLAGS

### ISSUE THREAD

**Issue by tru** [conan-io/conan#553]
I noticed that I had to add `WITH_GZFILEOP` to zlib - but packages using that will not pick up the defines and add it to the CFLAG environment using ConfigureEnvironment. I had a look and it seems like there is no code for adding this. Is this intentional?

**Comment by memsharded** [comment]
No, it is not intentional. Rewriting ``ConfigureEnvironment`` is the thing we are currently doing, as it is broken for some Windows configurations. So it should be a bug, lets try to fix it in the rewriting and ship in the next minor.

**Comment by memsharded** [comment]
They have been implemented in PR https://github.com/conan-io/conan/pull/547/files, in case you want to run from source and try it. It is not fully polished yet, but already passing CI, and  it has more comprenhensive testing of ConfigureEnvironment, so it should work. Thanks!

**Comment by memsharded** [comment]
Just released 0.13.3: http://docs.conan.io/en/latest/changelog.html
Please try it to confirm this issue is fixed. Thanks!

**Comment by tru** [comment]
Yeah confirmed that it works! Thanks!
