### ISSUE TITLE
Use of dependencies' binary in conanfile.py

### ISSUE THREAD

**Issue by madduci** [conan-io/conan#5536]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I'm running the latest conan (1.17.1) on a Linux machine (Manjaro x86_64) and I'd like to use the binaries shipped by another external library, listed as "required" (for instance, I'd like to use to binary ´flex´ and ´yacc´ shipped with flex and bison packages - see here: https://github.com/madduci/conan-gsoap/blob/master/conanfile.py)

Is there a way to specify that I want to use those tools, avoiding to install them on my machine with the System package manager?

**Comment by memsharded** [comment]
Hi @madduci 

Could you please clarify what is your goal? It is not fully clear. How do you want to use those tools without installing them? They are not installed with the system package manager, they are other conan packages, provided by bincrafters, aren't they? 
Maybe you want to run ``conan install flex/version@.... -g=deploy`` or something like that? Please tell, many thanks!

**Comment by madduci** [comment]
Hi @memsharded,

thanks for the feedback. I've expressed poorly my problem: the build script of `gsoap` internally uses some command line tools which come from `flex` and `bison` packages.
Now, to achieve the full build, I had to install those libraries as system libraries (using pacman on ArchLinux/Manjaro, but it is equivalent to apt-get).

My question is: how can I use those tools from the conan packages listed as **requirements** in my conanfile.py, during the build phase?

I hope it's more clear now, I couldn't find anything about it in conan docs (or I missed it)

**Comment by SSE4** [comment]
I think you may just add them to the profile, like:
```
[build_requires]
bison_installer/3.3.2@bincrafters/stable
flex_installer/2.6.4@bincrafters/stable
```
alternatively, you may try to put them on command line:
```
conan install ... -br bison_installer/3.3.2@bincrafters/stable -br flex_installer/2.6.4@bincrafters/stable
```

**Comment by madduci** [comment]
Can I do it in the conanfile.py directly?

Another example of this could be OpenSSL, where perl is required to build it

**Comment by SSE4** [comment]
yes:
```
def build_requirements(self):
    if not tools.which("bison"):
        self.build_requires("bison_installer/3.3.2@bincrafters/stable")
    if not tools.which("flex"):
        self.build_requires("flex_installer/2.6.4@bincrafters/stable")
    if not tools.which("perl"):
        self.build_requires("strawberryperl/5.30.0.1@conan/stable")
```

**Comment by madduci** [comment]
Ok, it means, I can then directly use `flex`. `yacc` or `perl` during the build() phase, right?

Thanks for the help @SSE4

**Comment by SSE4** [comment]
yes

**Comment by memsharded** [comment]
@SSE4 thanks!

I am afraid that build-requires in the command line doesn't exist :)

Also, if you want to force the usage of the conan package executables, for consistent reproducibility and versions in different machines, skip the if:

```python
build_requires = "bison_installer/3.3.2@bincrafters/stable", ..
```

@madduci please try that and let us know.

**Comment by madduci** [comment]
Yes, it definitively helped during the build phase.

I can call the executable during the build phase.

Thanks to everyone for the clarification
