### ISSUE TITLE
Add  an attribute to set the CONAN_USER_HOME_SHORT on the newConanClient construction

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5541]
Request extracted from https://github.com/conan-io/conan/issues/2690#issuecomment-515409747 (moved here to keep track of it).

**Comment by jgsogo** [comment]
Even though short paths are deterministic (https://github.com/conan-io/conan/pull/4238), several caches can share the same short path directories without collisions, otherwise the problem might be in the Conan implementation but not in the plugin side.

I think this is a nice-to-have feature but it is not needed to fix an existing issue

**Comment by jgsogo** [comment]
IMHO, we shouldn't add any configuration argument to the `Artifactory.newConanClient()`, instead we should provide a way to manage the configuration if the current one is not good enough. Right now we can:
 * use the corresponding environment variable `CONAN_USER_HOME_SHORT`, or
 * call `client.run(command: "config set general.user_home_short=/my/custom/path")`

Why do you think it is more convenient to be able to set it in the builder than in a call to `client.run(command: "conan config set ...")`? It was needed for the ConanUserHome to have a way to set its value without the need of using environment variables, but after the Conan home is known everything can be handled using Conan commands.

This is just an opinion of someone who has played with the plugin for a couple of days, so I'm sure you have a better knowledge of what is needed or not, but I'd love to keep the interface as clean as possible 👨‍🎓

**Comment by jgsogo** [comment]
Hi, @michaelmaguire. I'd like to know if you feel like this is an actual issue. IMO it is better to go with the environment variable or the config one. Maybe I'm missing something. Thanks!

**Comment by michaelmaguire** [comment]
> call client.run(command: "config set general.user_home_short=/my/custom/path")

> after the Conan home is known everything can be handled using Conan commands.

OK, fair enough.  Hadn't thought about this approach.
