### ISSUE TITLE
Alternative output files folder, or omitting them

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5545]
The ``conan install .`` command creates conaninfo.txt, conanbuildinfo.txt, graph_info.json, conan.lock files. 

Is it possible to avoid creating these files? Maybe using a command line option?

**Comment by uilianries** [comment]
What about new arguments?


Alternative output files folder:

    conan install . --output-folder=./output

Omitting them:

    conan install . --no-output-files

Error:

    conan install . --output-folder=./output --no-output-files

**Comment by rweickelt** [comment]
I like this feature request. Conan spills a lot of files by default.

> Alternative output files folder: conan install . --output-folder=./output

Please, no. That is already covered by `--install-folder`

> Omitting them: conan install . `--no-output-files`

Output-files is an overly generic term. Please not another term and folder. Aren't these files technically created by built-in generators? I'd rather vote for an option to explicitly switch off these generators. Give them proper names if they don't have them yet. A switch `--no-generator` could do the opposite of `--generator`. That is:
- switching off an implicitly chosen generator (conaninfo, conanbuildinfo, lockfile, graph_info)
- switching off a generator explicitly chosen in the conanfile.py

**Comment by memsharded** [comment]
Solved by 2.0
