### ISSUE TITLE
Is there a way to undo a package upload or go back to an older revision?

### ISSUE THREAD

**Issue by JigsawCorp** [conan-io/conan#5549]
To help us debug your issue please explain:

Hi, I made a mistake and uploaded a new version of a package to my remote. This new version that I uploaded is all wrong and I would like to cancel or go back to the last version that I uploaded. Is there a way to do this?

To clarify, I already had a package that I uploaded a month ago to my remote. Accidently, I uploaded a package that I didn't want to put on my remote which now updated the version of the package. So, I can't reach the old version.

Thanks

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
No, I don't think you can do it. I would recommend using the [package revisions](https://docs.conan.io/en/latest/versioning/revisions.html) feature to guarantee the immutability of the contents. Also, configuring a good permission model with Artifactory and some flows it is also recommended, usually, only a CI can write to a "release" repository.

**Comment by JigsawCorp** [comment]
@lasote Yeah, I was reading the revision section and I am regretful for not using it  earlier. I guess I'll use it now to avoid this.

**Comment by lasote** [comment]
Feel free to write again if you need anything.
