### ISSUE TITLE
Conan Training Workshop 15 September @ CppCon, Denver

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5556]
The Conan team is planning a Conan full day training workshop at CppCon, the major C++ conference in Colorado, USA, the 15th of September

https://cppcon.org/class-2019-conan/

It is a great opportunity to learn quickly about Conan, from zero to advanced features, in 1 day, directly from the Conan creators. It will be full hands-on training, plenty of exercises and examples. If you need to train people in your team, the combo Conan training + CppCon would be a great experience.

![conan-workshop-colorado-09-2019](https://user-images.githubusercontent.com/15367152/62121199-6e46a080-b2c3-11e9-8e03-e44ce8bfd63d.jpg)

**Comment by uilianries** [comment]
As this workshop requires sponsorship from companies, I would say it should be shared on Linkedin, where companies have more visibility.

Also, we could open a thread on reddit, since it's easy to spread the word there.

**Comment by memsharded** [comment]
Done :)
Find the code and slides here: https://github.com/conan-io/training
