### ISSUE TITLE
Migration to new conan server swaps version and module information in recipe

### ISSUE THREAD

**Issue by biere7** [conan-io/conan#5560]
I migrated all conan packages from version:

- Artifactory Professional 5.4.6 rev 50406900 (Windows Server 2012 R2)

to version:

- Artifactory Professional 6.11.3 rev 61103900 (Windows Server 2016 Standard)

We tested with conan commandline client in version 1.13.XX to 1.17.XX on linux and windows.

If we execute the search request against the older artifactory instance on any package we get following expected output:

```
conan search zlib* -r rt5.4.6

Existing package recipes:

zlib/1.2.11@conan/stable
zlib/1.2.11@conan/testing
```

we can install packages regarding the outputted format:

```
conan install zlib/1.2.11@conan/stable -s os=Windows -s compiler="Visual Studio" -s compiler.version=15 -s arch=x86 -s build_type=Debug -r rt5.4.6
```

if we run the search command against the newer version of artifactory we get following output, which I think is not intended. At least I can not find any documentation:

```
conan search zlib* -r rt6.11.3

Existing package recipes:

1.2.11/conan@zlib/stable
1.2.11/conan@zlib/testing
```
:warning: mind the swap between version and module!
therefore we had to change all our buildscripts to execute following install command:

```
conan install 1.2.11/conan@zlib/stable -s os=Windows -s compiler="Visual Studio" -s compiler.version=15 -s arch=x86 -s build_type=Debug -r rt5.4.6
```

Because of this issue we will have to run and maintain two conan server instances to be able to build old releases of our software, because we can not easily change the released tagged buildscripts.

**Comment by jgsogo** [comment]
Hi @biere7 . That format for a conanfile reference is not expected at all, and I'm very surprised it works with the `conan install`.

Need to ask you some questions:
 * how did you migrate the packages from one server to the other?
 * inside the UI of Artifactory, is the tree view on the left for your repository also different?
 * after installing the _wrong_ reference `1.2.11/conan@zlib/stable`, what is the output of `conan search`, is there a new reference (the right one) in the list?

**Comment by biere7** [comment]
Sure,

0. this is the tree view on the instance I exported the conan repository from (Artifactory Pro 5.4.6 rev 50406900):

![treeFromServer](https://user-images.githubusercontent.com/53508270/62210544-b259a400-b39c-11e9-95fc-4ace09542dcf.png)


1. I exported the single conan repository with name "conan_retail" via the UI from the old instance running on port 8082 (5.4.6 rev 50406900) and saved it under "D:\bk".

![exportFrom](https://user-images.githubusercontent.com/53508270/62210361-424b1e00-b39c-11e9-9ef0-ccbb7a55bfb5.PNG)

2. The metadata in d:\bk seems fine, have a look

![metadatabackup](https://user-images.githubusercontent.com/53508270/62211630-580e1280-b39f-11e9-852b-84dcf5629e52.png)


3. for tests we installed another Artifactory CE Server on the same host on another port 8083 (5.10.0 rev 51000900). ⚠️ With this old version the wrong behaviour is exactly the same as with Artifactory 6.11 in the original issue.

4. On this test instance I imported the "conan_retail" repository via UI like this:

![importToServer](https://user-images.githubusercontent.com/53508270/62211711-8c81ce80-b39f-11e9-8c12-ae1be01aa889.PNG)

5. Now the tree on the new instance looks exactly the same, have a look:

![treeToServer](https://user-images.githubusercontent.com/53508270/62210703-154b3b00-b39d-11e9-9d69-8da9ee452958.png)

6. Now I tested with client version 1.11.0 and 1.17 (latest) and threw my .conan folder away each time to make sure it creates me a new one. The results were the same:

![failedNormalFormCE](https://user-images.githubusercontent.com/53508270/62211050-dc5f9600-b39d-11e9-90b7-9e8027ece9e1.png)

7. Then I make the call with the wrong format and it succeedes:

![successWrongFormCE](https://user-images.githubusercontent.com/53508270/62211132-0e70f800-b39e-11e9-89be-fbafb27c51ba.png)

8. I looked for exactly this package in the tree view in our test instance and it can be found:

![packagefound](https://user-images.githubusercontent.com/53508270/62211187-29436c80-b39e-11e9-9a1c-123f8e38aa2f.png)

9. then as you requested I run the search command locally again and the package can only be found in the new wrongfully format:

![localSearchWrongFormat](https://user-images.githubusercontent.com/53508270/62211269-555eed80-b39e-11e9-9fab-585380bf7b29.png)

my conclusion: since we tested the import on Artifactory Pro 6.11 and Artifactory 5.10 I can imagine there is something wrong with the export feature in version Artifactory Pro 5.4.6 rev 50406900.

Is there another way to export/import data other than the UI from artifactory? Maybe that would be helpful in this case.

**Comment by MohamadJfrog** [comment]
Hi @biere7,

From Artifactory 6.9 the layout was changed, Artifactory trigger migration from V1 to V2 as part of an upgrade, however, you choose to migrate the artifacts using export/import mechanism not upgrade, in this case, you need to force the migration, for this to be done please follow these steps:

**Import data into target Artifactory where the Conan V2 packages are managed.
Connect to target artifactory database.
Run this query: 'delete from CONFIGS where CONFIG_NAME = 'artifactory.migration.conan.v2';'
Restart Artifactory**

The above steps will fix the layout and make it compatible with "user/name/version/channel" and calculate a default revision for the packages.
More information can be found [here](https://www.jfrog.com/confluence/display/RTF/Conan+Repositories#ConanRepositories-ConanPackageV1BackwardCompatibility).

The delete query will not delete any configuration or data, it's just a flag that shows if Conan migration has been done or not.

After performing the above suggestion share with us the Conan search results.

**Comment by biere7** [comment]
This makes sense for artifactory version 6.9 with the new layout and api version, but we did the test on an instance with the same layout and api as the source artifactory version (from 5.4.6 to 5.10.0). We considered the layout change to be a possible issue here. In the end we get the same weird behaviour.

The question is what layout are we talking about. Artifactory offers a layout for the UI-tree, which (from my view) is seperated from that what conan-server uses internally.

the source instance (5.4.6) has folllowing default layout and doesn't feature conan api version 2:

 ```[module]/[baseRev]/[org]/[channel<[^/]+>][remainder<(?:.*)>]``` 

the test target instance  (5.10.0) has following default layout and also doesn't feature conan api version 2:

````[module]/[baseRev]/[org]/[channel<[^/]+>][remainder<(?:.*)>]````

the results differ nevertheless:

(5.4.6) 
````
Existing package recipes:

zlib/1.2.11@conan/stable
zlib/1.2.11@conan/testing
````

(5.10.0)
````
Existing package recipes:

1.2.11/conan@zlib/stable
1.2.11/conan@zlib/testing
````

If we additionally upload the packages manually via the client in version 1.17.X, the  search command will have the expected result and the packages will be there twice but in another format:

(5.4.6) 
mind that the channel is not in part of the root path but a subfolder in the UI
````
conan_retail/libicu/4.4.2/conan/
             [module]/[baseRev]/[org]/ -> layout

search result: libicu/4.4.2@conan/stable
````

import via artifactory UI to (5.10.0):

````
conan_retail/libicu/4.4.2/conan/
            [module]/[baseRev]/[org]/ -> layout

search result: 4.4.2/conan@libicu/stable
````

manual upload via conan-client  to artifactory version 5.10.0:
mind that the channel is there a part of the root path in the UI and that the layout differs:

````
conan_retail/conan/libicu/4.4.2/stable/
            [org]/[module]/[baseRev]/[channel] -> where comes this information when not from layout?

search result: libicu/4.4.2@conan/stable
````


So what has the artifactory layout really to do with what happens when the client uploads one package?

**Comment by MohamadJfrog** [comment]
Hi @biere7,

After further investigation, we could reproduce this behavior on our end.
Here is the JIRA ticket for more information: https://www.jfrog.com/jira/browse/RTFACT-19840
IT seems like a bug, we are discussing this internally, we will keep you updated

**Comment by memsharded** [comment]
This issue is outdated, those Artifactory versions are now long time ago,  all migrations should have already happened, closing this ticket.
