### ISSUE TITLE
VS generator not exporting for <Lib> tag in vcxproj

### ISSUE THREAD

**Issue by kucerad** [conan-io/conan#5561]
Need to add Conan-handled lib to be referenced in .vcxproj in <Lib> tags. Conan VS-generator is exporting only in <Link> tag.

**Comment by jgsogo** [comment]
Hi, @kucerad 

I need you to provide an example or more information on this issue, I don't know what you mean by `tags` in relation to `.vcxproj` files.

Thanks

**Comment by kucerad** [comment]
In .vcxproj targeted to produce static lib, you have the ability to set the properties in the Librarian group. One of those is the AditionalLibraryDirectories. But you're not able to inject those from conan-generated props files. In the props files from conan - only the group <Link> is defined. Not the <Lib>, which is accessible from the Librarian property group. 
I think you'll get the idea from the related pull-request my colleague made in the meantime : https://github.com/conan-io/conan/pull/5564

**Comment by jgsogo** [comment]
Ok. I think it will be better if we move the conversation to that PR, probably with that example everything will be easier to understand. Thanks!
