### ISSUE TITLE
Credentials for remote are not removed with the remote

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5562]
Credentials for a remote (`conan user ...`) are associated with the remote URL and aren't removed if the remote is removed, so something like this works:

```bash
conan remote add name http://url.com
conan user -p <password> -r name <username>
conan upload <ref> -r name

conan remote remove name

conan remote add othername http://url.com   # Same URL
conan upload <ref2> -r name                  # User is authenticated (credentials were associated with the URL)
```

IMHO the credentials should be removed if the remote is removed. I'm not sure what to do if the URL or the name of the remote changes... 

Assigning to 2.0, not a big issue, but it could be used [in CI as a workaround](https://github.com/conan-io/conan/issues/5510#issuecomment-516388706) to bypass the restrictions of current `client.remote.add(server, repo_name)` implementation in the Artifactory plugin.

**Comment by memsharded** [comment]
This was solved in 2.0, already available in beta.
