### ISSUE TITLE
Wrong remote URL (repo_name) results in misleading error

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5563]
When we `conan remote add` a wrong repository URL (wrong repo name) for an Artifactory instance, the error returned by Conan is not helpful.

Assume we have a working repository at `http://localhost:8081/artifactory/api/conan/conan-local`, then:

(**revisions disabled**)
```bash
⇒  conan remote add art-bad http://localhost:8081/artifactory/api/conan/conan-local2222
⇒  conan user -p password -r art-bad admin                
ERROR: The remote at 'http://localhost:8081/artifactory/api/conan/conan-local2222'
only works with revisions enabled. Set CONAN_REVISIONS_ENABLED=1 or set
'general.revisions_enabled = 1' at the 'conan.conf'. [Remote: art-bad]
```

The error is misleading.

---

The behavior is even worse if the **revisions are enabled**:

```bash
⇒  conan config set general.revisions_enabled=1
⇒  conan remote add -f art-bad http://localhost:8081/artifactory/api/conan/conan-local2222
⇒  conan user -p password -r art-bad admin                                                
Changed user of remote 'art-bad' from 'None' (anonymous) to 'admin'
```
it doesn't fail until there is some interaction:

```bash
⇒  conan upload zstd/1.3.5@bincrafters/stable -r art-bad --force
Uploading to remote 'art-bad':
Uploading zstd/1.3.5@bincrafters/stable to remote 'art-bad'
ERROR: 400: Unsupported Conan v2 repository request for 'conan-local2222'. [Remote: art-bad]
```

Again, the error is misleading

**Comment by uilianries** [comment]
The problem is that Conan uses `urlparse` to validate the URl:
https://github.com/conan-io/conan/blob/develop/conans/client/cache/remote_registry.py#L263

The address `http://localhost:8081/artifactory/api/conan/conan-local2222` sounds wrong, but technically it is correct. We could impose some rule to check the suffix, but it could create false-positive from few cases.

**Comment by jgsogo** [comment]
We cannot know in advance that the repository name is invalid, we should work with the error code returned by the server to give a meaningful error to the user. The ideal message would be something like _"the repository ''repo-name'' does not exists in the server ''http://localhost:8081/artifactory''"_.

**Comment by jgsogo** [comment]
Current `develop` branch raises a different error. Now I'm not getting any error during `conan user` command, but:

If revisions are enabled:

```bash
⇒  conan config set general.revisions_enabled=1
⇒  conan search zstd -r art-bad
ERROR: 400: Unsupported Conan v2 repository request for 'conan-local3333'. [Remote: art-bad]
```

With revisions disabled:

```bash
⇒  conan config set general.revisions_enabled=0
⇒  conan search zstd -r art-bad
ERROR: The remote at 'http://localhost:8081/artifactory/api/conan/conan-local3333' only works with revisions enabled. Set CONAN_REVISIONS_ENABLED=1 or set 'general.revisions_enabled = 1' at the 'conan.conf'. [Remote: art-bad]
```

**Comment by jgsogo** [comment]
There is a first issue here:
 * Server capabilities (Artifactory) when using an invalid _repository name_ returns `only_v2` too. If revisions are disabled [here](https://github.com/conan-io/conan/blob/df44fea73fa7610a5de3634d7354105a12b69d10/conans/client/rest/rest_client.py#L38) we are raising the exception.

   Is this expected behavior? Should Artifactory return different capabilities depending on the repository? Should it return capabilities at all if the repository doesn't exist?

   Bintray returns `['complex_search', 'checksum_deploy', 'revisions']` always, but same question: should it succeed if the repository doesn't exist?

---

If we fix the previous behavior, then the error returned usng a wrong repository URL (wrong repository name):
 * Bintray returns a meaningful error that is printed by Conan:
    ```
    ERROR: {"message":"Repo 'conan-packages2222' was not found"}. [Remote: jgsogo-wrong]
    ```
 * Artifactory: the message returned by the server is not helpful, it is a 400 saying that _"Unsupported Conan v2 repository request for 'conan-local3333'"_ (it says "v1" if revisions are disabled). Conan output:

   ```
   ERROR: 400: Unsupported Conan v1 repository request for 'conan-local3333'. [Remote: art-bad]
   ```
    Something saying that the repository does not exist would be better.

**Comment by Or-Geva** [comment]
> * **Artifactory**: the message returned by the server is not helpful, it is a 400 saying that _"Unsupported Conan v2 repository request for 'conan-local3333'"_ (it says "v1" if revisions are disabled). Conan output:
>   ```
>   ERROR: 400: Unsupported Conan v1 repository request for 'conan-local3333'. [Remote: art-bad]
>   ```   
>   Something saying that the repository does not exist would be better.
> 
> Issues opened in Artifactory JIRA: [RTFACT-20090](https://www.jfrog.com/jira/browse/RTFACT-20090) and [RTFACT-20091](https://www.jfrog.com/jira/browse/RTFACT-20091)

I do agree with @jgsogo, this error message is not helping much.

**Comment by ghost** [comment]
I am getting these errors during installion of conan package. I guess its cause of server issue and API problem. The issue may creates due to override the same method in a file folder also. So, make sure just having not more than one programming files 
-------------------------------------------------------------------------------------------------------------------------------------------

ERROR: Error loading conanfile at 'C:\Users\aksha\project\conan\cura\conanfile.py': The remote at 'https://ultimaker.jfrog.io/artifactory/api/conan/cura-internal' only works with revisions enabled. Set CONAN_REVISIONS_ENABLED=1 or set 'general.revisions_enabled = 1' at the 'conan.conf'. [Remote: cura]

**Comment by memsharded** [comment]
@akshayams94 this doesn't seem a Conan issue. It is just that server is using/requiring the activation of one Conan feature called "revisions". The Conan client should enable the revisions as instructed by those instructions.
