### ISSUE TITLE
Add a command to retrieve the Conan home directory

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5572]
A command to know where the `conan.conf` is (we call it Conan home) which is evaluated using the `CONAN_USER_HOME` env variable or defaulted to `~/.conan` would be useful.

Proposals:
 * `conan config home`
 * `conan home`
 * `...`

**Comment by uilianries** [comment]
Amazing, I would say this feature is relevant, for many times I saw users asking it on Slack, "where is conan home directory?".

When someone want to know where is Conan home dir you need to guess: look for env vars CONAN_USER_HOME and CONAN_USER_HOME_SHORT, or try ~/.conan or %USERPROFILE%/.conan

I would suggest `conan config get home`

**Comment by memsharded** [comment]
The small problem I see with ``conan config get home`` is that you cannot do ``conan config set home``, so it is not symmetric.

**Comment by uilianries** [comment]
I didn't think about it, good catch. Even if `conan config set home` was able to set CONAN_USER_HOME, it sounds wrong.

What about a new config sub-command? 
- `conan config system home`
- `conan config global home`
- `conan config info home`

Or maybe follow Javier's suggestion: `conan home`

I think `conan config` is better for updates, if we need to add more new properties in the future, but I can't think about any other right now, only home is global, any other can be retrieved by conan.conf or env var

**Comment by memsharded** [comment]
I think we should go with ``conan config home``, until we have further evidence that a new subcommand like ``system`` or ``global`` make sense, I cannot think of anything that is not in the conan.conf, as the only thing that is necessary to define the location of conan.conf is the HOME.
