### ISSUE TITLE
[Question] conan install dependency injection

### ISSUE THREAD

**Issue by wizardsd** [conan-io/conan#5573]
I'm trying to use conan on Multibranch Jenkins pipeline in the following way:
1. Jenkins builds a shared library from feature branch, produces and uploads package `shared_tool/1.1.11@company/feature_1` to the Artifactory.
2. Next, Jenkins builds a project that depends on `shared_tool/[>=1.0]@company/stable`.

I want to overwrite package reference for the project from `shared_tool/[>=1.0]@company/stable` (stable branch) to `shared_tool/1.1.11@company/feature_1`

1. How can I address this problem?
2. Is it possible to do that without patching `conanfile.py` of the project?
3. Is it right to overload `requirements` function in `conanfile.py` to achieve this?

**Comment by Minimonium** [comment]
Hi, currently the only way is to use the `override` dependency in the requires of the consumer recipe.
See:
https://docs.conan.io/en/latest/reference/conanfile/attributes.html#requires

The topic of injecting overrides was brought here too: #5067 .

**Comment by wizardsd** [comment]
Yes, duplicates #5067
