### ISSUE TITLE
[question] How to set arbitrary virtualenv environment variables?

### ISSUE THREAD

**Issue by tribayf** [conan-io/conan#5574]
I am trying to get a minimal example working, but am unsure if I have misunderstood something.

### Efforts so far
I have a conanfile.py with:
```python
import sys
from conans import ConanFile

class MyRecipe(ConanFile):
  name    = 'testpkg'
  version = '0.0.1'
  def package_info(self):
    print('called package_info', file=sys.stderr)
    self.env_info.MY_ENV_VAR = "potato"
```

And am invoking conan from my build directory with:

```
conan install .. -g virtualenv
```

This produces `activate.sh`/ `deactivate.sh` as expected, but they do not include `MY_ENV_VAR`.  As far as I've been able to tell, `package_info`  is not called either. It only seems to be called when invoking `conan create`, but without emitting `activate.sh`/ `deactivate.sh`.

Pages/discussions I've read:
- https://docs.conan.io/en/latest/mastering/virtualenv.html
- https://docs.conan.io/en/latest/reference/generators/virtualenv.html
- https://github.com/conan-io/conan/issues/2037
- https://github.com/conan-io/conan/issues/4493
- https://github.com/conan-io/conan/issues/4493 [<- related?]

### Motivation
I am working with Vulkan and ultimately wish to programmatically set the `VULKAN_SDK`, `VK_ICD_FILENAMES`, and `VK_LAYER_PATH` environment variables during development, based on where conan is caching the Vulkan SDK (using [@madebr's recipe](https://github.com/madebr/conan-vulkan_lunarg)).

### System
I'm using Conan 1.18.0/Python 3.7.4 and have tried my code on
  - macOS 10.12.6
  - Ubuntu 19.04

### Contributing prereqs.
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Minimonium** [comment]
Hi, yes #4493 is the one that explains your case.
> Yes, package_info() is called, but only in the dependency packages, not for the package I want to work with.
> conan create . <REF_OF_A> && conan install <REF_OF_A> should work

**Comment by tribayf** [comment]
Thanks @Minimonium, that answers my question (:

> conan create . <REF_OF_A> && conan install <REF_OF_A> should work

This did work for me, but I'm wondering whether the need for `<REF_OF_A>` is by design? It would be nice not to have to create a top-level package until it is needed. For my use case, I have Conan managing project dependencies, but am not yet considering creating or distributing a package.

**Comment by Minimonium** [comment]
It's by design that it's a part of the package interface and generators only work on them. I guess there could be an additional tool to support build-time environment information for this use case (to support both local and in-cache building).

**Comment by tribayf** [comment]
Thanks for answering my questions!

I think I'm going to go with the custom generator approach.
