### ISSUE TITLE
[Question] Offline usage without remote

### ISSUE THREAD

**Issue by madduci** [conan-io/conan#5575]
I've a question about the offline usage of Conan.
In an offline environment, where no remote server is available and customer recipes have been developed (with local respository for source files, e.g. OpenSSL), is there a way to point to some dependency's recipe with a command line option?

E.g. Project X requires OpenSSL/VERSION@custom/channel. 
How can I perform the installation of Project X with a local recipe, without a artifactory/Conan server available?

`conan install ProjectX/VERSION@custom/channel --build=missing`

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Environment: Conan 1.17, all conan-supported OSes

**Comment by Minimonium** [comment]
Hi, in an offline environment I would suggest copying local cache from the one installed when online. 
Or else, you would need to export all recipes manually and also make sure that their sources are available too (via `exports_sources` for example).

**Comment by memsharded** [comment]
Yes, that is a good point, recipes like OpenSSL are downloading the sources from the internet. So even if you have the source code for the recipe, you will not be able to create the package locally, because you will not be able to retrieve the sources. For other recipes that do not require other stuff from the internet, it is enough to do ``conan export``, to put them in the cache and make them usable for other packages.

**Comment by madduci** [comment]
Assuming that I have a conan recipe for OpenSSL that uses a local source zip package and another recipe that uses this one, how can I just point the downstream recipe to the upstream one?

Should I just do `conan export . OpenSSL/VERSION@custom/channel` and the let the downstream recipe use it as `self.build_requires(OpenSSL/VERSION@custom/channel)`?

**Comment by memsharded** [comment]
Yes, ``conan export . OpenSSL...`` and the the downstream ``requires = "OpenSSL/...`` (notes: weird to have OpenSSL as build-requires, it will not be a build require but a normal one. Also, you don't need the ``self.requires()`` mode in ``requirements()`` method, unless you are doing some conditional requirements.

**Comment by memsharded** [comment]
Closing this as responded (and inactive)
