### ISSUE TITLE
conan server authenticatiion

### ISSUE THREAD

**Issue by deekshith-elear** [conan-io/conan#5576]
Hi, Can we add authentication of github or own developed oauth apllication to conan server??
If yes then how can we add.

**Comment by memsharded** [comment]
There are some docs here: https://docs.conan.io/en/latest/uploading_packages/running_your_server.html#create-your-own-custom-authenticator, about how to write your own auth in conan_server. Have you considered using ArtifactoryCE? Is there any reason you will not use it instead conan_server? It scales better, have a web UI, better permissions management, etc.

**Comment by deekshith-elear** [comment]
I have seen artifactory ce but in kubernetes it is so complicated to deploy and maintain. I have gone through documentation, didn't understand creating new .py for custom authenticator. Can you provide any base example .py file
