### ISSUE TITLE
Better condition to call vcvars

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5580]
Related to https://github.com/conan-io/conan-vs-extension/issues/153

Conan, from inside the VS extension, is not able to find tools like `ml64`, `nmake`,... the error reported by Conan looks like (taken from the linked issue):

```
...
7/29/2019 12:49:07 PM: 'nmake' is not recognized as an internal or external command,
7/29/2019 12:49:07 PM: operable program or batch file.
7/29/2019 12:49:07 PM: OpenSSL/1.0.2o@conan/stable: 
7/29/2019 12:49:07 PM: OpenSSL/1.0.2o@conan/stable: ERROR: Package '6acf24cd4adf2df742e006cc0e5f0329e3b6e60b' build failed
7/29/2019 12:49:07 PM: OpenSSL/1.0.2o@conan/stable: WARN: Build folder C:\github\.conan\data\OpenSSL\1.0.2o\conan\stable\build\6acf24cd4adf2df742e006cc0e5f0329e3b6e60b
7/29/2019 12:49:07 PM: ERROR: OpenSSL/1.0.2o@conan/stable: Error in build() method, line 120
7/29/2019 12:49:07 PM: 	self.visual_build(config_options_string)
7/29/2019 12:49:07 PM: while calling 'visual_build', line 310
7/29/2019 12:49:07 PM: 	self.run_in_src(make_command)
7/29/2019 12:49:07 PM: while calling 'run_in_src', line 134
7/29/2019 12:49:07 PM: 	self.run(command)
7/29/2019 12:49:07 PM: 	ConanException: Error 1 while executing nmake -f ms\nt.mak 
7/29/2019 12:49:08 PM: Conan has returned exit code '1' while processing configuration 'Architecture: x86_64, build type: Debug, compiler toolset: v142, compiler version: 16;, runtime library: MDd'. Please check file 'C:\github\jdee\ConanExtensionExample\x64\Debug\.conan\conan_a07ee162-5dbe-49bc-bc62-c12a9ae62704.log' for details.
```

---

Currently we are using [these conditions](https://github.com/conan-io/conan/blob/0e8187a118ffa50dcacc385dcdae0c47b5c86484/conans/client/tools/win.py#L349) to decide if we need to run `vcvars` or not:

```python
    existing_version = os.environ.get("VisualStudioVersion")

    if existing_version:
        command = ["echo Conan:vcvars already set"]
        ...
    else:
        vs_path = vs_installation_path(str(compiler_version))
        ...
```

but this is not the right solution when we are running Conan from Visual Studio itself (like we do for the [VS Extension](https://marketplace.visualstudio.com/items?itemName=conan-io.conan-vs-extension)). Running from inside, the variable `VisualStudioVersion` is set but there are many things not in the environ that would be after running `vcvars`.

This is the diff between regular output (Conan run from the terminal) and output from VS Extension (there are also different values for important variables like `PATH`): 

```diff
diff --git a/terminal.vars.txt b/visual_studio.vars.txt
index c94326e..60ec5ed 100644
--- a/terminal.vars.txt
+++ b/visual_studio.vars.txt
@@ -1,37 +1,27 @@
-Namespace(file='terminal.txt')
+Namespace(file='visual_studio.txt')
 ALLUSERSPROFILE
 APPDATA
-COMMANDPROMPTTYPE
 COMMONPROGRAMFILES
 COMMONPROGRAMFILES(X86)
 COMMONPROGRAMW6432
 COMPUTERNAME
 COMSPEC
-DEVENVDIR
 DRIVERDATA
-EXTENSIONSDKDIR
+ENABLE_XAML_DIAGNOSTICS_SOURCE_INFO
 FPS_BROWSER_APP_PROFILE_STRING
 FPS_BROWSER_USER_PROFILE_STRING
-FRAMEWORK40VERSION
-FRAMEWORKDIR
-FRAMEWORKDIR64
-FRAMEWORKVERSION
-FRAMEWORKVERSION64
 HOMEDRIVE
 HOMEPATH
-INCLUDE
-LIB
-LIBPATH
 LOCALAPPDATA
 LOGONSERVER
-NETFXSDKDIR
+MSBUILDLOADMICROSOFTTARGETSREADONLY
 NUMBER_OF_PROCESSORS
 ONEDRIVE
 ONEDRIVECONSUMER
 OS
 PATH
 PATHEXT
-PLATFORM
+PKGDEFAPPLICATIONCONFIGFILE
 PROCESSOR_ARCHITECTURE
 PROCESSOR_LEVEL
 PROCESSOR_REVISION
@@ -39,46 +29,29 @@ PROGRAMDATA
 PROGRAMFILES
 PROGRAMFILES(X86)
 PROGRAMW6432
-PROMPT
 PSMODULEPATH
 PUBLIC
 SESSIONNAME
 SYSTEMDRIVE
 SYSTEMROOT
 TEMP
+THREADEDWAITDIALOGDPICONTEXT
 TMP
-UCRTVERSION
-UNIVERSALCRTSDKDIR
 USERDOMAIN
 USERDOMAIN_ROAMINGPROFILE
 USERNAME
 USERPROFILE
-VCIDEINSTALLDIR
-VCINSTALLDIR
-VCTOOLSINSTALLDIR
-VCTOOLSREDISTDIR
-VCTOOLSVERSION
+VISUALSTUDIODIR
+VISUALSTUDIOEDITION
 VISUALSTUDIOVERSION
 VS140COMNTOOLS
-VS160COMNTOOLS
-VSCMD_ARG_APP_PLAT
-VSCMD_ARG_HOST_ARCH
-VSCMD_ARG_TGT_ARCH
-VSCMD_VER
-VSINSTALLDIR
-VSSDK150INSTALL
+VSAPPIDDIR
+VSAPPIDNAME
+VSLANG
+VSROOTSUFFIX
+VSSKUEDITION
 WINDIR
-WINDOWSLIBPATH
-WINDOWSSDKBINPATH
-WINDOWSSDKDIR
-WINDOWSSDKLIBVERSION
-WINDOWSSDKVERBINPATH
-WINDOWSSDKVERSION
-WINDOWSSDK_EXECUTABLEPATH_X64
-WINDOWSSDK_EXECUTABLEPATH_X86
-__DOTNET_ADD_64BIT
-__DOTNET_PREFERRED_BITNESS
-__VSCMD_PREINIT_PATH
+_NO_DEBUG_HEAP
 CONAN_LOG_RUN_TO_OUTPUT
 CONAN_LOG_RUN_TO_FILE
 CONAN_LOGGING_LEVEL

```

**Comment by jgsogo** [comment]
We need a smarter condition (check for actual running tools, choose another environment variable,...), or maybe we can call the `vcvars` unconditionally.

**Comment by jgsogo** [comment]
Recommended reading: https://github.com/conan-io/conan/issues/3673

**Comment by SSE4** [comment]
there is script called `VsDevCmd.bat`, and it has `no_ext` parameter.
if you call `VsDevCmd.bat no_ext` then it will skip vcvars but set `VisualStudioVersion` which we are using for detection
otherwise (default) it will set up correct vcvars.
so, `VisualStudioVersion` isn't a reliable thing to rely on.

**Comment by SSE4** [comment]
seems to be affecting only extension
calling `conan install OpenSSL/1.1.1c@conan/stable --build OpenSSL` as a PreBuild command of Visual Studio project doesn't have an issue
calling the same from the `cmake-conan` from generated Visual Studio project also doesn't have an issue.

**Comment by jgsogo** [comment]
Probably we should question why we are not running `VsDevCmd.bat` unconditionally, does it have undesirable side-effects?

**Comment by SSE4** [comment]
need to check, it might be the case that `VsDevCmd.bat` isn't available in older Visual Studio versions. it also sets up additional things besides just vcvars.

**Comment by memsharded** [comment]
The main reason why vcvars is not run unconditionally is because running it twice, specially with different configurations will have undefined behavior. So far it has been relatively robust, I am open to improvements, but please double-check that it will not run into problems for those re-definitions.
