### ISSUE TITLE
Conan search doesn't find existing package - only recipe

### ISSUE THREAD

**Issue by sneik555** [conan-io/conan#5581]
Steps I've done: 

- add new remote:

> conan remote add test https://api.bintray.com/conan/sneik123/3rdparties

- add my user:
>conan user -p **** -r test username

- upload package:
>conan upload tinyxml2/6.2.0@test/stable --all -r test

- try to find uploaded package:

> conan search tinyxml2/6.2.0@test/stable -r test

And here there is no packages found:
![conan_search](https://user-images.githubusercontent.com/8473399/62470402-a99d0f80-b79a-11e9-80f4-470d75efd6d0.PNG)

Conan version: 1.16.0

Did I missed something during package creation that I cannot search it?
Package is uploaded to [bintray.](https://bintray.com/sneik123/3rdparties/tinyxml2%3Atest#files/test/tinyxml2/6.2.0/stable/0)

**Comment by memsharded** [comment]
Hi @sneik555 

Yes, you are right, it seems there is some bug in Bintray.
I would suggest first to try to re-upload. Remove the bintray package, and upload it again. Please paste here the full output of the upload command, to double-check everything is ok. 
If it keeps failing, and it was not a temporary glitch, I will be reporting the issue to the Bintray team.

Also, for hosting your own packages, you could try running your own Artifactory CE. It is free, even for commercial purposes, so if you have some server you could run it on it, the setup is not difficult, and you will enjoy your own private server (you could also host private packages there, and control permissions).

**Comment by sneik555** [comment]
Hi, 
I re-uploaded package and searching problem still exist.
Here is conan upload execution status:
![conan_exec](https://user-images.githubusercontent.com/8473399/62614447-b0975f80-b90b-11e9-9f18-5d92678522a2.PNG)

and logs:
[logs.txt](https://github.com/conan-io/conan/files/3476425/logs.txt)

And thanks in advance with Artifactory CE - I will try it.

**Comment by czoido** [comment]
Hi @sneik555 
I've been trying to reproduce the issue following the same steps with Conan 1.16.0 in my Bintray using Windows and MacOs and it works for me:

<img width="818" alt="Screenshot 2019-08-08 at 10 01 10" src="https://user-images.githubusercontent.com/5045666/62685743-8acd9180-b9c3-11e9-93c0-8980f93dde80.png">

Does it happen for all packages that you upload to your Bintray ?
We will report this issue to Bintray team because it could be a some bug there.

**Comment by sneik555** [comment]
Hi @czoido 
I built 7 different packages - 4 for visual studio and 3 for android (cross-building) and upload it to bintray.
![upload](https://user-images.githubusercontent.com/8473399/62859587-df437a80-bcfd-11e9-9ecd-d3d8a5a6b0ba.PNG)

Then I try to search them. I could search only android packages - it gives mi the clue that maybe there is some bug in builds for visual studio... And I found it..
Problem is with my profiles for VS. One of my profile is: 

>[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
compiler.toolset=v141,version=14.14,cuda=10.0,host=x64
build_type=Release
[options]
shared=False
[build_requires]
[env]

> 

I assume that compiler.toolset is problem here, but I think that I need the same toolset for my 3rdparties as for my project (yes, unfortunatelly I had to change settings.yml under ~/.conan/)

**Comment by sneik555** [comment]
Hi all, 

Now I found solution for my problem. In profile I set

> compiler.toolset=v141

> 
And I call CMake with proper toolset

> CMake(self, build_type="Debug",
                toolset="v141,version=14.14,cuda=10.0,host=x64")

> 

with those settings I have proper package and I can search it on bintray. We can close this issue now.
