### ISSUE TITLE
[Question] Can we use system msys2 environment instead of installing msys2_installer?

### ISSUE THREAD

**Issue by akemimadoka** [conan-io/conan#5585]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.18 on Windows

I have already installed latest msys2, but when a package requires msys2 environment, it will install msys2 by depending on msys2_installer, so there will be multiple msys2.

Sorry for opening issue here, but I cannot open issue in https://github.com/bincrafters/conan-msys2_installer

**Comment by SSE4** [comment]
hi @akemimadoka 
usually, recipes check for [CONAN_BASH_PATH](https://docs.conan.io/en/latest/reference/env_vars.html#conan-bash-path) environment variable, and install `msys2_installer` only if it's not available.
so, if you set `CONAN_BASH_PATH` into your profile, installation of `msys2_installer` will be skipped and recipe will use existing MSYS2 instance available on your machine.
if there is a recipe which doesn't check that, please lemme know, so we can fix it.

**Comment by akemimadoka** [comment]
It works, thank you!
