### ISSUE TITLE
[Question|Help] CMake find_path cannot find file from dependency

### ISSUE THREAD

**Issue by IceflowRE** [conan-io/conan#5589]
I try to create a package for a third-party library (https://github.com/IceflowRE/conan-Simple-WebSocket-Server)

The problem:
https://gitlab.com/eidheim/Simple-WebSocket-Server/blob/master/CMakeLists.txt#L28
`find_path(ASIO_PATH asio.hpp)`  which fails, is there any way to pass the include path, so it can be found or do i have to patch the CMakelist and use another approach?

**Comment by danimtb** [comment]
Hi @IceflowRE!

It seems there where some things missing from the recipe. I have open a PR with the fix https://github.com/IceflowRE/conan-Simple-WebSocket-Server/pull/1 and some comments to calrify.

Hope you find it useful and you make the recipe work 😄 Do not hesitate to make any other question and close this issue when you are done. Thanks a lot!

**Comment by IceflowRE** [comment]
Thank you very much! 
``` 
generators = "cmake"
exports_sources = "CMakeLists.txt"
```
That was what i missed... I found the cmake generator actually, but the wrapper around the conan stuff... thanks!

**Comment by danimtb** [comment]
Glad to hear that!! you are welcome 😄
