### ISSUE TITLE
Question: copy_deps from multi-configuration debug/release package 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#5593]
copy_deps is handy function to import/deploy dlls.

We do have some multi-configuration debug/release package. (one package that contains both debug and release files)

Something like:

```
def package_info(self):
    self.cpp_info.release.libs = ["mylibrary"]
    self.cpp_info.debug.libs = ["mylibrary_d"]
```

As a consumer when, I use copy_deps to import dlls, it import both debug and release dlls.

Is there a way to define each build_type required dlls(in package_info for example),  so that when I use copy_deps it only copy relevant dlls.

Thanks.

**Comment by jgsogo** [comment]
Hi, @boussaffawalid! This is probably a nice feature to request. Currently, the `build_type` is not taken into account for the operations you mention (`import`, `deploy`,...) but it is to populate the variables in _multi-generators_ as it is documented [here](https://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-package). 

You can workaround this issue by writing yourself the logic on top of the `self.deps_cpp_info` from the consumer package. You can access your debug configuration like `self.deps_cpp_info["your_package"].configs["debug"]...`

**Comment by memsharded** [comment]
Why not using a pattern?

```python
def deploy(self):
    if self.settings.build_type == "Debug":
        self.copy_deps("*_d.dll", ....)
   else:
        ...
```

The thing is that the system is not designed to discriminate, you packaged both things in the same package is because you will fetch both things (you cannot download just some libs, but all debug and release), and ``imports`` and ``deploy`` do not take into account the ``cpp_info`` at all, it would be a quite challenging thing.

**Comment by boussaffawalid** [comment]
Some library does not follow the convention suffix _d for debug. 

So my idea was, maybe each package can define it is debug/release/relWithDebInfo dlls and copy_deps will magically know what to copy.

**Comment by memsharded** [comment]
``copy_deps`` removed in 2.0, closing as outdated
