### ISSUE TITLE
tools.SVN does not use provided credentials

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#5599]
The implementation of `tools.Git` operates on the URL retrieved via `get_url_with_credentials()` which includes the configured username/password. `tools.SVN` on the other hand never calls `get_url_with_credentials()` and thus operates on the URL without credentials. They are also not injected into the `svn` client commands via `--username` and `--password` arguments.

**Comment by jasal82** [comment]
AFAIK credentials in URL are not supported in SVN, so the only option is to add `--username=x` and `--password=y` to every command. I just did a quick test with these modifications in the `scm.py` in my site-packages and SVN checkout works fine.

**Comment by jgsogo** [comment]
Thanks a lot for taking the time to investigate the issue, and submit a PR. Thanks!
