### ISSUE TITLE
What is the default dict returned from conan_server api snapshot and digest endpoints?

### ISSUE THREAD

**Issue by steve-abrams** [conan-io/conan#5614]
I'm working on implementing a [registry system on GitLab](https://gitlab.com/gitlab-org/gitlab-ee/issues/8248) to be used as a conan remote and am using the [v1 conan server endpoints](https://github.com/conan-io/conan/tree/develop/conans/server/rest/controller/v1) as my guide. I'm not a python developer and am having trouble understanding what is returned in the dicts when a new package is being uploaded?

For example, the `/:pkg_name/:version/:username/:channel/digest` endpoint returns a dict of `{ filename: url }`. From my testing, it seems that returning an empty dict `{}` is not valid with the conan client. What does the client expect in return when the package and recipe do not yet exist on the remote?

I would likely ask the same for the snapshot endpoint `/:pkg_name/:version/:username/:channel`, the download_urls endpoint `/:pkg_name/:version/:username/:channel/download_urls`, and the similar package endpoints `/:pkg_name/:version/:username/:channel/packages/:package_id/digest`.

Any help would be much appreciated.

**Comment by memsharded** [comment]
Hi @steve-abrams 

Maybe the most important bit to understand here are the historical reasons for this API, developed long time ago when our server side was very different. All transfers were redirected to S3, so the API v1 is always returning download/upload signed URLs for the clients to execute those transfers. This is not used anymore, and API v2 drops this behavior, doing transfers in 1 direct step.

Asking for the digest (=manifest) of a package is done only once the package is known that is there, but when asked it is expected to get it or fail. Also, what is obtained in this API is the URL to do the transfer of the actual manifest file (which contains the list of file names and MD5 hashes of the recipe or package, previous to creating the xxx.tgz file). Both the "manifest" and "snapshot" endpoints are used for package uploads only, you can find a good explanation of how the upload is processed here:

https://github.com/conan-io/conan/blob/2dfadb17a66218226a5ace24d15267b0a3f3bee9/conans/client/cmd/uploader.py#L31

The way to know that is there exist a package in the server is different for uploads and downloads.

- For uploads, the first thing is to ask for the "snapshot" (the list of files actually stored in the server, here you will find the conan_package.tgz with its hash, but not the contents of headers and libs inside the tgz). This snapshot can be empty, this was used to make the diff and upload only the minimum files. This was to deal with interrupted uploads of big packages, minimizing impact.

- For downloads, the server ``download_urls`` method will throw a 404 if the recipe is not there:

```python
    def get_conanfile_download_urls(self, ref, files_subset=None):
        self._authorizer.check_read_conan(self._auth_user, ref)
        latest_ref = self._get_latest_ref(ref)
        urls = self._server_store.get_download_conanfile_urls(latest_ref,
                                                              files_subset, self._auth_user)
        if not urls:
            raise RecipeNotFoundException(latest_ref)  # 404!!!
        return urls
```

Please let me know if this helps and if you have any further question.

**Comment by steve-abrams** [comment]
Thank you @memsharded this explanation is extremely helpful! I think the problem was I did not realize that sometimes the remote should return errors. I had made the incorrect assumption that if the conan command is successful, every api request it makes should also be successful. 

Perhaps you could validate my current understanding: if the conan package is completely new and the remote does not have any record of it, the remote will return a 404 when requesting the manifest (`/digest`). Then a request for `/upload_urls` is made with something like 
```json
{"conanfile.py": 1762, "conanmanifest.txt": 58}
```
which will return the urls that the client will use to upload the initial manifest, something like:
```json
        {
          "conanfile.py":      "https://my-remote/v1/files/Hello/1.0/user/channel/0/export/conanfile.py?signature=*****",
          "conanmanifest.txt": "https://my-remote/v1/files/Hello/0.2/user/channel/0/export/conanmanifest.txt?signature=*****"
        }
```
And the client will upload the files to those urls. A similar process is followed for the package files.

**Comment by memsharded** [comment]
Yes, that is right. The request for upload_urls is done with the size of the files to be uploaded:

```python
 def _upload_recipe(self, ref, files_to_upload, retry, retry_wait):
        # Get the upload urls and then upload files
        url = self.router.recipe_upload_urls(ref)
        file_sizes = {filename.replace("\\", "/"): os.stat(abs_path).st_size
                      for filename, abs_path in files_to_upload.items()}
```
In case that is useful to the server to estimate the transfer and decide accordingly (maybe redirect if the file is too big, for example)

And yes, the server will return the real URLs that can be used to execute the transfer. Not only the manifest, but all the manifest, the recipe itself, and maybe a couple of .tgz will be uploaded. There is no flow that will upload just the manifest to the server.

Yes, the process is also similar for the package files, is practically the same.

When the issue is clear enough, please consider closing it. You can always open more issues for further new questions. Thanks!

**Comment by steve-abrams** [comment]
I appreciate your help, I believe I have a good path forward now. Closing the issue 🙂
