### ISSUE TITLE
[question] Best practice for building for android?

### ISSUE THREAD

**Issue by akemimadoka** [conan-io/conan#5615]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Using Conan 1.18.1

When I try building with profile

> NDK_PATH=D:/Android/Sdk/ndk-bundle
> 
> [settings]
> os=Android
> os.api_level=26
> os_build=Windows
> arch=armv8
> arch_build=x86_64
> compiler=clang
> compiler.version=8
> compiler.libcxx=libc++
> build_type=Release
> [options]
> [build_requires]
> [env]
> CONAN_CMAKE_GENERATOR=Ninja
> CONAN_CMAKE_ANDROID_NDK=$NDK_PATH

the compiler can be found but not the linker, so I got errors:

> -- Android: Targeting API '26' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
> -- Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain ''
> -- The C compiler identification is Clang 8.0.7
> -- The CXX compiler identification is Clang 8.0.7
> -- Check for working C compiler: D:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
> -- Check for working C compiler: D:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
> CMake Error at D:/Scoop/apps/cmake/3.15.2/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
>   The C compiler
> 
>     "D:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: D:/Conan/.conan/data/zlib/1.2.11/conan/stable/build/a481b5492e7f13aac736199f4ad3a6dd21f975bb/source_subfolder/_build/CMakeFiles/CMakeTmp
> 
>     Run Build Command(s):D:/msys64/mingw64/bin/mingw32-make.exe cmTC_ce1d1/fast && D:/msys64/mingw64/bin/mingw32-make.exe -f CMakeFiles\cmTC_ce1d1.dir\build.make CMakeFiles/cmTC_ce1d1.dir/build
>     mingw32-make.exe[1]: Entering directory 'D:/Conan/.conan/data/zlib/1.2.11/conan/stable/build/a481b5492e7f13aac736199f4ad3a6dd21f975bb/source_subfolder/_build/CMakeFiles/CMakeTmp'
>     Building C object CMakeFiles/cmTC_ce1d1.dir/testCCompiler.c.o
>     D:\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=aarch64-none-linux-android --gcc-toolchain=D:/Android/Sdk/ndk-bundle/toolchains//prebuilt/windows-x86_64 --sysroot=D:/Android/Sdk/ndk-bundle/sysroot  -isystem D:\Android\Sdk\ndk-bundle\sysroot\usr\include -isystem D:\Android\Sdk\ndk-bundle\sysroot\usr\include\aarch64-linux-android  -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=26 -fexceptions  -g -fPIE   -o CMakeFiles\cmTC_ce1d1.dir\testCCompiler.c.o   -c D:\Conan\.conan\data\zlib\1.2.11\conan\stable\build\a481b5492e7f13aac736199f4ad3a6dd21f975bb\source_subfolder\_build\CMakeFiles\CMakeTmp\testCCompiler.c
>     Linking C executable cmTC_ce1d1
>     D:\Scoop\apps\cmake\3.15.2\bin\cmake.exe -E cmake_link_script CMakeFiles\cmTC_ce1d1.dir\link.txt --verbose=1            D:\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=aarch64-none-linux-android --gcc-toolchain=D:/Android/Sdk/ndk-bundle/toolchains//prebuilt/windows-x86_64 --sysroot=D:/Android/Sdk/ndk-bundle/platforms/android-26/arch-arm64 -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=26 -fexceptions  -g  -Wl,--gc-sections  CMakeFiles/cmTC_ce1d1.dir/testCCompiler.c.o  -o cmTC_ce1d1
>     D:\msys64\mingw64\bin\ld.exe: 无法辨认的仿真模式: aarch64linux
>     支持的仿真： i386pep i386pe
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
>     mingw32-make.exe[1]: *** [CMakeFiles\cmTC_ce1d1.dir\build.make:86: cmTC_ce1d1] Error 1
>     mingw32-make.exe[1]: Leaving directory 'D:/Conan/.conan/data/zlib/1.2.11/conan/stable/build/a481b5492e7f13aac736199f4ad3a6dd21f975bb/source_subfolder/_build/CMakeFiles/CMakeTmp'
>     mingw32-make.exe: *** [Makefile:120: cmTC_ce1d1/fast] Error 2
> 
> 
> 
> 
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:2 (project)
> 
> 
> -- Configuring incomplete, errors occurred!

I can set environment variable to specify the linker path, but the path of linker is concerned to settings.arch, I think this is not a good idea to hard-code it.

So I try building with profile

> NDK_PATH=D:/Android/Sdk/ndk-bundle
> 
> [settings]
> os=Android
> os.api_level=26
> os_build=Windows
> arch=armv8
> arch_build=x86_64
> compiler=clang
> compiler.version=8
> compiler.libcxx=libc++
> build_type=Release
> [options]
> [build_requires]
> [env]
> CONAN_CMAKE_GENERATOR=Ninja
> CONAN_CMAKE_ANDROID_NDK=$NDK_PATH
> CONAN_CMAKE_TOOLCHAIN_FILE=$NDK_PATH/build/cmake/android.toolchain.cmake

With specifying CONAN_CMAKE_TOOLCHAIN_FILE I can build successfully now, but I noticed that the settings about abi does not work, because in file https://github.com/conan-io/conan/blob/f6b3e34a71a699ec12ff947824db33bfc6ac1593/conans/client/build/cmake_flags.py#L187 when CONAN_CMAKE_TOOLCHAIN_FILE was found, it will return early so os.api_level and arch will not be applied.

So I wonder if this is best practice that build for android that I missed, thanks!

**Comment by SSE4** [comment]
hi @akemimadoka 
the best practice is described in CMake [docs](https://cmake.org/cmake/help/v3.15/manual/cmake-toolchains.7.html#cross-compiling-for-android), with all variables needed to be specified
for me personally, the easiest way so far, is to use [android_ndk_installer](https://github.com/bincrafters/conan-android_ndk_installer) package within your conan profile:
```
include(default)
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=26
[build_requires]
android_ndk_installer/r20@bincrafters/stable
[options]
[env]
```
`android_ndk_installer` package will take care of setting up all requires cmake and environment variables needed for you.
otherwise, if you prefer to use an existing system NDK installation (for instance, from the `Android Studio`), you may use the following conan profile:
```
include(default)
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=7.0
os=Android
os.api_level=26
[build_requires]
[options]
[env]
ANDROID_NDK_ROOT=/home/conan/android-ndk-r18b
```
this should be enough for CMake/conan to automatically deduce all the settings.
for instance:
```
-- Android: Targeting API '26' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain 'aarch64-linux-android-4.9'
```
if you prefer to use CMake toolchain file supplied with Android SDK/NDK instead of CMake built-in Android support, then you may use the following profile:
```
include(default)
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=26
[build_requires]
[options]
[env]
CONAN_CMAKE_TOOLCHAIN_FILE=/home/conan/my_android_toolchain.cmake
```
and use the following toolchain file (arguments are [documented](https://developer.android.com/ndk/guides/cmake)):
```
set(ANDROID_PLATFORM 26)
set(ANDROID_ABI arm64-v8a)
include(/Users/sse4/Library/Android/sdk/ndk/20.0.5594570/build/cmake/android.toolchain.cmake)
```
the reason to wrap the standard toolchain file, is that if conan sees `CONAN_CMAKE_TOOLCHAIN_FILE`, it doesn't try to be very smart, and  it doesn't try to override things defined it your toolchain, otherwise, it would be breaking behaviour for many users.

P.S. I am also going to update our conan docs to make it more clear

**Comment by akemimadoka** [comment]
Thank you!

**Comment by akemimadoka** [comment]
The second solution seems not working with ndk r20 in my environment... I will try using toolchain file, thanks for your help!
