### ISSUE TITLE
report both conflicting packages

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#5617]
if conan package has two conflicting dependencies, it outputs the following error message:
```
ERROR: Conflict in pcre/8.41@bincrafters/stable
    Requirement bzip2/1.0.8@conan/stable conflicts with already defined bzip2/1.0.6@conan/stable
    To change it, override it in your base requirements
```

in this case, the one is `pcre/8.41@bincrafters/stable`, which is using up-to-date version `bzip2/1.0.8@conan/stable`, but it's unclear which package is trying to use old version `bzip2/1.0.6@conan/stable`. it would be nice to output both conflicting package, otherwise it's hard to trace that error.
for the record, `conan info` doesn't work - it produces the same error message.

conan 1.18

/cc @jgsogo 

To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by SylEze** [comment]
Any news?

**Comment by jgsogo** [comment]
This is being implemented in https://github.com/conan-io/conan/pull/5684, have a look at the proposed solution and comment there if you feel like the implementation is good enough, it needs more changes,.... 

Thanks @SylEze
