### ISSUE TITLE
[suggestion] Creation date should be considered when multiple compatible pkgs are available on artifactory

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#5618]
As far as I could see in `range_resolver.py`, the creation date of the package is not considered when matching requirements if multiple compatible packages are available on artifactory. 

Say we have the following versions on artifactory:
1.0.0+meta1 (created 01:00)
1.0.0+meta2 (created 02:00)
1.0.0+meta3 (created 03:00)

and a semver expression to request a simple range version:
\>1.0.0

Since we are 'max_satisfying', I would expect the newest available version (1.0.0+meta3) to be returned as the result, but it seems this is not the case.

**Comment by jgsogo** [comment]
Hi, @GordonJess, this is a limitation of the `semver` approach: metadata (`meta1`, `meta2`, `meta3`) is not taken into account to resolve version precedence, and we cannot rely on the datetime returned by the server: promotion of packages, copies, order in a batch upload,... it is not easy to handle.

Nevertheless, you can explore package revisions (instead of version metadata) as they do have the notion of _latest_. Docs are here: https://docs.conan.io/en/latest/versioning/revisions.html

Let me know if package revisions could be a solution for your use case. Thanks!

**Comment by GordonJess** [comment]
@jgsogo, thanks for your reply!

I'm testing out the package revisions feature and seems to work well!  I'm successfully able to pull the most recent package using a ~=1.0.0 expression.

However, when I try to check the revisions using `conan search --rev pkg/1.0.0@user/channel`, conan doesn't find any packages.  It seems it is the build metadata tag in the semver which is causing the issue.  I'd expect metadata to be ignored while searching for revisions.

What do you think?

**Comment by jgsogo** [comment]
Nice you find it useful 😊 

`conan search --revisions <reference>` only list the revisions for the reference, use a full reference (with revision) to list the packages associated with it: `conan search <reference>#<revision>` (same idea to list the revisions of a `package-id` and the information of a `package-id#package-revision`)

I'm not sure if this is the issue, but if it is, and it is a problem of the docs that are not clear enough, tell us so we can improve them.

**Comment by GordonJess** [comment]
Sorry, I think I wasn't so clear in the last comment.

Basically I would expect `conan search --revisions <pkg>/1.0.0@<user>/<channel>` to return all revisions of version 1.0.0[+metadata] regardless of the metadata tag.

On second thought, perhaps something which follows the normal 'pattern' reference would be better:  `conan search --revisions <pkg>/1.0.0*@<user>/<channel>`.

I just don't want to have to know metadata in advance, nor repeat the command for each.

**Comment by jgsogo** [comment]
Oh! I see, currently the `search` command result is a list with elements of the same category that have a common ancestor: references in the cache, packages per reference, revisions for a reference, packages per reference#revision, package revisions per reference#revision:package_id,... and I think it is convenient and easier to keep it this way. Calling several times to the command to go deeper into the tree structure shouldn't be a big deal.

**Comment by GordonJess** [comment]
> revisions for a reference
Exactly, I'd like revisions for a reference.  I just don't want to have to write the metadata in the version of the reference.  Metadata should always be ignored.

**Comment by jgsogo** [comment]
I know what you mean, but the _full version string_ (with the matadata too) belongs to the _Conan reference_. That is something we cannot change now without breaking many existing references (not everyone is using semantic version scheme)

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, which has improved compatibility for version ranges (Plus the simplificatin of the `conan list` command to list elements in the cache with an unified pattern syntax) Thanks!
