### ISSUE TITLE
How to set an option in conanfile.py based on the contents of a file

### ISSUE THREAD

**Issue by HunterZ** [conan-io/conan#5620]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Using Conan 1.9.2 on RHEL 7.6 (Linux), I've got options `file_name` and `file_version` that should factor into the package hash.

`file_name` happens to contain a value that I want to use to populate `file_version`. I know how to extract this using Python. The problem is that I can't _find_ the file this early, because it seems that there is no point in conanfile.py at which self.build_folder is populated before the package hash has been calculated, such that I could open the file, extract the version number, and set the `file_version` option.

Is there any way to do this? Am I really forced to maintain a duplicate, hard-coded copy of the file version in conanfile.py? This would be a major maintenance concern.

**Comment by HunterZ** [comment]
Maybe this will work: https://github.com/conan-io/conan/issues/5445#issuecomment-508570851

**Comment by memsharded** [comment]
Hi @HunterZ 

Could you please explain a bit more about that ``file_name`` and ``file_version``? Are they options with ANY values? How are they used later in the resulting binary? are those files exported with the recipe? How they will be loaded later when the conanfile is in the cache?

If you had some more complete recipe, something in a repo or an example that we could play with, to understand better the use case, that would help. Thanks!

**Comment by HunterZ** [comment]
Unfortunately I can't share it, but basically I'm building a library that - among other things - includes code and API that is generated from the contents of an XML file.

I have created multiple packaging repos to build different flavors of the library that each use different XML files, and dependent projects need to be able to select a specific variant.

To achieve this, both the filename and a version string for the XML file are captured as `file_name` and `file_version` Conan package options, respectively (in case someone varies one but not the other, as we're not in control of that). Dependent projects then use Conan profiles specifying desired `file_name` and `file_version` option values to select the correct package variant based on their needs.

This worked well for the case that I was using XML files whose version numbers were hard-coded in `conanfile.py`. However, I now want to instead extract a version string from an attribute of the root node of the XML file and use that as the `file_version` option value for the Conan package. This obviously needs to occur early enough to actually get encoded in the package properties and affect the package hash.

Unfortunately this seems impossible to achieve within `conanfile.py` itself, as there is no way to programmatically derive a path to the XML file (relative to `conanfile.py` probably) - and subsequently set the `file_version` option - early enough to accomplish the above goal:
-  While initializing the member variables of my `ConanFile`-derived class, the `ConanFile` superclass member variables are not yet available/initialized.
- `configure()`/`config_options()` methods are apparently called at a weird time/place, where `__file__` points to a `conanfile.py` copy from the Conan cache that does not (yet?) have exported files anywhere nearby.
- `source()` appears to be called *after* the package hash is calculated, which is too late.
- I did not think to try `imports()`.

My current workaround is to provide a separate Python script with the logic to extract the XML version string, then have our Jenkins tooling and/or users invoke conan with `-o` parameters to manually specify the `file_name` and `file_version` option values. This seems to be working fine, but is a little cumbersome.

**Comment by danimtb** [comment]
Hi @HunterZ,

Reading your use case it seems you only want to save the `file_version` automatically extracted from the file you are indicating. I think the only important thing here is to actually save that information in the package ID so it can be retrieved later.

I am thinking about just having the option `file_name` and saving the `file_version` in the package ID.

For example:

```
def package_id(self):
    self.info.options.file_version = self._get_file_version(self.options.file_name)
```

I have not tried if that is possible but maybe it fits. The drawback I see with this is that the `file_version` will not be reflected in the metadata of the package, but the IDs should be different for different file versions and name and you will get different packages whenever those values change.

Please give it a try and let me know what you think.

**Comment by danimtb** [comment]
ping @HunterZ 
Do you need more assistance on this?

**Comment by HunterZ** [comment]
> ping @HunterZ
> Do you need more assistance on this?

Unfortunately I'm not able to try your suggestion at this time. My workaround of using externally-supplied parameters seems to be "good enough" for now.

**Comment by danimtb** [comment]
ok, thanks for the answer. Please do not hesitate to open anew issue in the future if you need so. Thanks!
