### ISSUE TITLE
AttributeError: Object has no attribute "build_requires" during "conan build"

### ISSUE THREAD

**Issue by fourbft** [conan-io/conan#5625]
To reproduce, you can use this conanfile.py:
```
from conans import ConanFile

class SpecificConanfile(ConanFile):
    name = "CB"
    description = "CB test component for self.build_requires bug."
    url = "http://CB.html"
    version = "2.0.0"


    def build_requirements( self):
        self.build_requires( "CA/1.0.0@user/testing")

    def requirements( self):
        pass

    def build( self):
        my_var = self.build_requires
```
with any component CA (e. g. one that is just as trivial as the above one, only without the build() function) or you can even remove the build_requirements() function altogether and the bug shows, too.

When you now do a "conan create . user/testing" with the above conanfile.py, all is well. If you create a build directory and issue "conan install <path-to-conanfile>" and then "conan build <path-to-conanfile>" you'll get the following error:
```
$ conan build ../CB
Using lockfile: 'CB_build/conan.lock'
Using cached profile from lockfile
conanfile.py (CB/2.0.0): Running build()
ERROR: conanfile.py (CB/2.0.0): Error in build() method, line 17
        my_var = self.build_requires
        AttributeError: 'SpecificConanfile' object has no attribute 'build_requires'
```

This happens with Conan version 1.18.1. Seems to be a regression as we have not seen this error at least with 1.16.1. (With 1.17.0 we ran into another issue (https://github.com/conan-io/conan/issues/5529) which might have hidden this one, so I am not sure, if it existed there, too.)

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
Hi @fourbft,

Thanks for reporting the issue.
Having a look at your conanfile I am not sure what you are trying to do in the build method. `self.build_requires` should only be used in the ``build_requirements()`` method.

If you would like to access any information about the requirements, it would be better to use the graph information through ``self.deps_cpp_info``: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-cpp-info

Please have a look at the link above and provide me with more information about the ``build()`` method in your recipe so we can have a look at your use case.

**Comment by fourbft** [comment]
Hi @danimtb,
in the real world code, we are using the attribute in the build method to pass the information to CMake where it is currently used for documentation purposes only. (A „make doc“ generates among others a section listing the build dependencies.)
```
cmake.definitions["BUILD_DEPS"] = self.build_requires
```
Even though this is not absolutely necessary, we still wondered why this suddenly stopped working.
(Hmm, thinking about it, I am not really sure anymore, if it really stopped working or if simply nobody tried a "conan build" since we introduced that build_requires documentation feature...)
And we were not aware, that this attribute is only available in build_requirements(). The Conan docs are actually not very clear about when and where the attributes are available for reading and when not.
And of course for an outside user, it is peculiar, that the attribute is available in the build-method during a "conan create" and not during a "conan build".

I think, `self.deps_cpp_info` is not an alternative for us here, as this does not include the build_requires, does it?

**Comment by danimtb** [comment]
You are right. I don't think there is currently a way to get the direct build requires out of deps_cpp_info object right now. This might be something interesting to add in the future.

However, I don't think this approach was possible before, as conditional requirements in ``build_requires()`` are not always (in all commands) evaluated. Probably that worked when you used the plain attribute.

I agree the documentation should be improved regarding this kind of issues

**Comment by fourbft** [comment]
Ok, we can work around this issue.
And about this being a regression: I no longer think it is. I guess the reason why this did not turn up earlier is, that nobody tried a "conan build" with one of those packages since we have been using this "feature" - and in "conan create" it works.

**Comment by memsharded** [comment]
Issue very outdated, now in Conan 2.0 the ``build_requires`` are available at ``conan build``
