### ISSUE TITLE
Conan always thinks it's cross-compiling on Solaris

### ISSUE THREAD

**Issue by datalogics-robb** [conan-io/conan#5629]
In conan versions 1.18.2 and before, Conan attempts to figure out what architecture it is building on, with the caveat that 32-bit builds can be done on 64-bit systems, the code gets complicated.  Unfortunately the logic doesn't behave correctly on Solaris, where platform.machine() will return "sun4v", "sun4u", "i86pc" (and probably others).

Running on Solaris 11 SPARC with Python 3.7.4 / gcc

WARN: Unknown 'sun4v' machine, Conan doesn't know how to translate it to the GNU triplet, please report at  https://github.com/conan-io/conan/issues

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ x ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ X ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Closed via https://github.com/conan-io/conan/pull/5630
