### ISSUE TITLE
[question] Best way of implementing documentation or other auxiliary builds

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#5632]
Most of our components come with their documentation versioned in the source code repository. There is also a bunch of other metadata like manifests. When building a consumer application from these components we'd like to run other, separate build processes that must merge the data of all components in the dependency graph. A documentation overview page is generated that references the sub-documentations from the components. Something similar is done with the manifests which are basically XML files that must be merged and then transformed into some other format. We even generate documentation from these manifests automatically which is then combined with the rest of the docs.

I'm not really sure how to implement this with Conan in the most natural way. We have existing build scripts currently operating on the (manually checked out) source trees so the most efficient way for us would be to export the required files in the binary packages and retrieve them from the install cache somehow. That would minimize the required changes to the existing build system. However, as far as I know there is no way of selectively deploying files from binary packages which is what would be needed here. We could deploy everything but then we'd also copy the binary artifacts and headers. It's also unclear to me if the deploy generator can be used in combination with the cmake generator. Setting environment variables pointing to the required files/paths in the cache using a virtualenv generator is not flexible enough in my opinion and pollutes the environment. Another idea would be something like named deploy groups with different sets of files that could be retrieved independently.

I'd still prefer something like a custom generator for the documentation build and another one for the manifest merging process. That would require major changes to our existing build scripts and the implementation of new generators but the solution feels more natural to me. An open question here is how to make the generator determine if it needs to operate on a given dependency because only certain dependencies must be integrated into the documentation (i.e. the ones that follow our component model). If there are transitive third-party dependencies we don't want to and can't include them in our documentation artifact because it's in another foreign format or location or it isn't relevant to the end user because it's only used internally.

Is there another option that I'm missing? What do you think how use-cases like this should be tackled?

**Comment by danimtb** [comment]
Hi @jasal82 and thanks for sharing your use-case. Yes, I think your use case is useful enough to be tackled by Conan and might not only be applicable to documentation but to other build flags for final end consumer application deployment.

I think I don't have the full solution to your problem but I can point you to some resources of information that could help with that.

First of all, you can use the ``deploy()`` method in your final application. It allows you to filter and get the only bits you need from the package dependencies of your consumer application https://docs.conan.io/en/latest/devtools/running_packages.html#deployable-packages

In the same way, as you pointed, you can use a custom deploy-like generator similar to our ``deploy`` one. You can have a custom one per consumer application and there you can filter the specific dependencies that you don't want to include in the final result.

Another option is to have a ``with_documentation`` option in all your packages and activate that flag in a final deploy of the consumer app with a profile like:

*deploy_with_docs_profile*
```
[options]
depA:with_documentation=True
depB:with_documentation=True
#skipping depC
depD:with_documentation=True
```

and: ``conan install consumer_app/1.0@user/channell --profile deploy_with_docs_profile``

Hope I understood the use-case well enough and that you find the information useful!

**Comment by jasal82** [comment]
Hi @danimtb. Thank you for the explanation and useful directions. I like the idea of using the `deploy()` method but I'm struggling with the implementation. Our conanfiles are typically committed in the source code repository. I understood that `deploy()` is called only if the package is installed from a reference. How would I trigger it from a working copy?

Let me explain in more detail. What we have is a bunch of components, I'll call them `LibX`. Then we have a consumer application `App` with a `conanfile.txt` containing something like

```
[requires]
LibA/[*]@sick/dev
LibB/[*]@sick/dev

[generators]
cmake
```

We run a build of `App` on the CI server by checking out a working copy, installing the dependencies and then triggering CMake through `conan build`:

```
git clone https://repo/App.git
cd App
mkdir build && cd build
conan install .. -pr /opt/profiles/arm11
conan build ..
```

That will build the executable. Now after that we want to build documentation for the application. First of all we will need to merge the manifests of all component-like dependencies. To do that I need the manifest.mf.xml files from each of the `LibX` components. These are fed into a tool which merges and filters them according to some specification that is stored in a file in the application repo. The result of that merging process must then be integrated into the documentation which is generated from Asciidoc *sources* from each of the components.

I need a way of obtaining these intermediate artifacts from the dependencies at that specific stage with the exact versions resolved from the dependency graph in the install step. Maybe I just don't see the connections but it's still unclear to me how the `deploy()` function could be integrated here.

**Comment by danimtb** [comment]
For this use-case (using a conanfile.txt) deploy() is not available.

However, looking at your approach I think it would be better to have the manifests packaged in each one of the dependencies and make the documentation generation par of the build process of your application.

You can have the logic in the conanfile.py recipe of the consumer application using ``self.deps_cpp_info`` information and skipping the nodes that are not involved.

If you don't want the documentation process to be triggered every time, you can add an option to the recipe as described in my previous comment.

I think this would be the best approach as you would have everything tracked in the recipe and thee final package of the consumer app can be also created and stored for future distribution in Artifactory.

**Comment by jasal82** [comment]
That sounds like a viable solution. Thank you very much! In the long run I'd probably want to have the logic implemented outside of the recipe because it's used from all our consumer applications but for now it'll do fine.

**Comment by danimtb** [comment]
probably you could share the bits of the python code ina python_require and reuse it in the different recipes or stick to the generator approach that might be more customizable actually.

Glad you find the recommendations useful! Please close this issue whenever you feel it is solved or ask any further question down below. Thanks a lot! 😄
