### ISSUE TITLE
Settings for packages are overpopulated with values not defined in their conanfile

### ISSUE THREAD

**Issue by SebastianMosiej** [conan-io/conan#5633]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

- Conan 1.18
- Debian 10

I'm using conan to download grpc package. It requires at least 4 other packages (OpenSSL, Protobuf, c-ares and zlib). My problem is that when I build grpc and ie. protobuf - protobuf settings list contain additional **compiler.libcxx=libstdc++11** or **compiler.exception=seh**. 
At the end my profile looks like this 
```
[settings]
grpc:compiler=gcc
grpc:compiler.exception=seh
grpc:compiler.threads=posix
grpc:compiler.libcxx=libstdc++11

gtest:compiler=gcc
gtest:compiler.libcxx=libstdc++11

protobuf:compiler=gcc
protobuf:compiler.libcxx=libstdc++11

os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
build_type=Debug
[options]
```

I was expecting that common part - one without any package prefixes would be propagated to specific packages configuration, something like this:

```
[settings]
grpc:compiler.exception=seh
grpc:compiler.threads=posix
grpc:compiler.libcxx=libstdc++11
gtest:compiler.libcxx=libstdc++11
protobuf:compiler.libcxx=libstdc++11

os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
build_type=Debug
[options]
```

In above example zlib and c-ares were installed without any notifications.

**Comment by danimtb** [comment]
Hi @SebastianMosiej,

Yes, the settings that are not specifically indicated with a package name prefix should be applied to all dependencies in the graph for that configuration.

Is this not working for you? Could you try with a reduced example?

In theory, the ``compiler.exception`` and ``compiler.threads`` are only needed for Windows MinGW which does not seem to be your case looking at the profile configuration. but maybe I don't fully understand your problem.

Please try with a reduced example and provide me with more feedback so we can reach a solution here. Thanks! 😄

**Comment by SebastianMosiej** [comment]
Example - profile
[conan_linux_gcc_8_debug.txt](https://github.com/conan-io/conan/files/3510651/conan_linux_gcc_8_debug.txt)
Installing c-ares from conan-center
```
conan install c-ares/1.14.0@conan/stable -pr conan_linux_gcc_8_debug.txt -r conan-center
....
c-ares/1.14.0@conan/stable: WARN: Can't find a 'c-ares/1.14.0@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Debug, compiler=gcc, compiler.exception=seh, compiler.threads=posix, compiler.version=8, os=Linux
- Options: fPIC=True, shared=False                                                   
- Dependencies: 
- Package ID: a24136479abac4525baf7bba0ef51b2e314eb707 
```

`conan inspect c-ares/1.14.0@conan/stable | grep settings`
Shows that c-ares uses only:
`settings: ('os', 'compiler', 'build_type', 'arch')`

Obviously, conan took compiler **compiler.exception=seh**, **compiler.libcxx=libstdc++1** and  **compiler.threads=posix** into settings list to generate different Package ID.
When I commented this 3 lines in profile - conan generated other Package ID - one already existing in conan-center repository and downloaded it.

I need to keep **compiler.exception=seh**, **compiler.libcxx=libstdc++1** and  **compiler.threads=posix** as they are part of our custom **gRPC** recipe for Windows which we use in project (it would need further investigation).

Yet, main problem remain - in my opinion - if c-ares, zlib or OpenSSL has only 4 settings as needed - then all available shouldn't be taken as package ID.

**Comment by danimtb** [comment]
What about using a profile like this?

*conan_linux_gcc_8_debug*
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
grpc:compiler.exception=seh
grpc:compiler.threads=posix
```

I used that without issues to install c-ares and I think it should work when installing grpc:

```
$ conan install c-ares/1.14.0@conan/stable -pr conan_linux_gcc_8_debug

Installing package: c-ares/1.14.0@conan/stable
Requirements
    c-ares/1.14.0@conan/stable from 'conan-center' - Cache
Packages
    c-ares/1.14.0@conan/stable:761432f3453a17c960259b5b2605153e3bcffd7d - Download

c-ares/1.14.0@conan/stable: Retrieving package 761432f3453a17c960259b5b2605153e3bcffd7d from remote 'conan-center'
Downloading conanmanifest.txt: 100%|##########| 846/846 [00:00<00:00, 106kB/s]
Downloading conaninfo.txt: 100%|##########| 388/388 [00:00<00:00, 64.5kB/s]
Downloading conan_package.tgz: 100%|##########| 498k/498k [00:00<00:00, 1.13MB/s]
Decompressing conan_package.tgz: 100%|##########| 498k/498k [00:00<00:00, 3.59MB/s]
c-ares/1.14.0@conan/stable: Package installed 761432f3453a17c960259b5b2605153e3bcffd7d
c-ares/1.14.0@conan/stable: Downloaded package revision 0
```

**Comment by danimtb** [comment]
Any update using the profile proposed above @SebastianMosiej? Did you solve the issue?
