### ISSUE TITLE
Add warning against non-string option values

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#5634]
Here are some of the options for the bincrafters wxwidgets package.  

```               
               "zlib": [None, "system", "zlib"],
               "png": [None, "system", "libpng"],
               "jpeg": [None, "system", "libjpeg", "libjpeg-turbo", "mozjpeg"],
               "tiff": [None, "system", "libtiff"],
               "expat": [None, "system", "expat"],
```
Here are the defaults:
```
               "zlib": "zlib",
               "png": "libpng",
               "jpeg": "libjpeg",
               "tiff": "libtiff",
               "expat": "expat",
```
In summary, the use of the literal python `None` as a non-default option here actually renders the `None` case/option/branch unreachable.  The python literal `None` can only ever work as a default option, making it special, awkward, and this ticket suggests adding a warning against it. 

The fundamental problem is that the command-line interface of Conan means users can only ever pass the string `None`.  Of course, strings can be converted to other types behind the scenes, but such implicit magic is generally hard for users to predict without reading documentation, and both unexpected and undesirable in this kind of case. The unfortunate consequence in the case of the wxwidgets recipe was that the following function to act on these options has been subtly and silently broken since it's inception: 
```
        def option_value(option):
            return 'OFF' if option is None else 'sys'
```
In this case, option always had a value (even when users pass the string `None`), so the condition was never `True` and this function always returned `sys`. 

There are at least 5 different ways Conan team could choose to approach this problem.  This includes: 
* supporting an empty-value syntax for None:  `-o mypackage:myoption=`
* supporting a "special" syntax for None:  `-o mypackage:myoption=_None_`
* adding automatic coercion behavior from `None` string to literal `None` 
* adding an environment variables to let users opt into one of the above behaviors
* doing nothing at all, because "authors should just know this is how python works"
* adding a warning, and avoiding the pattern in future conan-center packages

I've thought about them for a bit, and am choosing to suggest inserting a lexer warning and potentially mentioning as a best practice in the documentation: "Always make all possible option values strings, because that's the only thing that users can pass at the CLI". 

One might point out that the literal `None` works just fine as a default value, and this strategy is used in a number of packages.  The problem is that `None` is just different than strings, and simply by being different it leads to unexpected behavior in corner cases. 

For example, there are the occasional cases where package authors want to change the default value of an option in a recipe.  Perhaps `None` was the default before and working fine, and the author wants to simply change the default value.  Well, in this case, the author has to realize on their own that `None` literal won't ever be reachable if it's not default. They'll have to understand the subtle nuance, that passing `-o:myoption=None` doesn't actually result in `myoption` being `None` literal, because there's currently no error.  Conditionals which check the option simply return `True` rather than `False`. Once the user does catch on, then they'll have to refactor their recipe to use the `None` string.  I'm almost certain this is how it happened with `wxwidgets`, and it's easy to imagine this happening to others. 

Another real example are corner cases where enterprise packagers make use of a common non-boolean option across many recipes and rely on the wildcarding convention. For example, `optimization`.  Users might want to pass the following to build with all packages using a single optimization level, but with one-or-more exceptions:

`-o *:optimization=O2 -o some_special_library:optimization=None`

This is simply not possible of the `optimization` option used the python literal `None` as a potential value (even if it's the default). 

In summary, string values for Conan options are immune to all such caveats and unexpected consequences when compared to special values like python's `None` literal. In all cases where `None` has been used, the string of `"None"`, `"default"`, or any other sentinel string value would have worked just as well, and it's simply unfortunate that this pattern of using `None` has propagated as far as it has.  

It's also worth noting that for new Conan settings we regularly suggest listing `None` as a possible value because it allows new settings to work with existing packages.  And, it's possible for users to override a setting on a per-package basis just like the options example above:  

`-s build_type=Debug -s mypackage:build_type=Release`

Indeed, such settings with `None` values are unreachable with this syntax and that is unfortunate. 
 However, I think the use of `None` is necessary pattern for Conan settings for the backwards compatibility case, and do not suggest any change here.  Also, I believe that it's far less common for users to want to override "None-containing" settings on a per-package basis. 

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by solvingj** [comment]
As usual, this post subject to being invalidated by some documentation or feature of Conan that I was unaware of.

**Comment by solvingj** [comment]
Another point to mention is that boolean type options which feature `True` and `False` literals in the recipe accept options at the cli via the string values of `-o mypackage:myoption=True`.  The string value is automatically converted to the boolean type.

**Comment by solvingj** [comment]
Ok, this is perhaps the most un-intuitive characteristic: 

If we define an option like this...
```
    options = {"myoption": [None, "choice1", "choice2"]}
    default_options = {"myoption": "choice1"}
```
And pass this at the CLI:
`-o mypackage:myoption=None`

Conan currently accepts the string `None` as a valid choice, even though the string `None` is not listed as one of the valid choices. 

The value of `myoption` throughout the rest of the recipe will be the string `None`, however when you look up at the `options` list, it seems very clear that you must surely have a `None` type, and so of course the obvious thing to do to test for this value is: 

`if myoption is None:`

It's completely un-intuitive to think to test with:

`if myoption == "None":`

The fundamental breakdown here is accepting `None` as a valid option type in the definition, but storing the value of `None` as a string.

**Comment by danimtb** [comment]
This problematic is exposed also here: #3620
I am pretty sure we will have to address this to improve the usability of options and I would like to have it reviewed for Conan 2.0

Meanwhile, we can make recommendations or explicitly tell with value conversions are done from the command line to the python types.

**Comment by SSE4** [comment]
do int options work as expected? I am asking, case few recipes (e.g. OpenCV), use integer option values (`gtk = [None, 2, 3]`).

**Comment by SSE4** [comment]
maybe we need some more strict syntax, something like [cmake](https://cmake.org/cmake/help/v3.0/manual/cmake.1.html) currently has:
```
D <var>:<type>=<value>
```
this way one may write something like `-o opencv:gtk=3{int}` instead of just `-o opencv:gtk=3` (ambiguous, will I have string "3" or just integer 3, or maybe even float)? these implicit types are sources of errors, and it's very JavaScript-like, we need something strict for sure.

**Comment by memsharded** [comment]
This has improved in 2.0 in the following way:

- All options values are always strings internally, except the ``None`` Python value which means "not defined", "no need to define it"
-  ``options = {"myoption": [None, 1, 2, True]}`` Means that ``myoption`` might not be defined. 
- Not defined options also evaluate to ``False`` if used as booleans
- options comparisons are converted to strings, so for the above both ``self.options.myoption == 1`` and ``self.options.myoption == "1"`` work fine and evaluate to True
- Literal ``"None"`` as string is now valid and completely different than Python builtin ``None``.

This, together with the missing bug solved in https://github.com/conan-io/conan/pull/12761, will be the approach in 2.0, closing this issue as solved.
