### ISSUE TITLE
Support for using git repo like "https://github.com/user/conan_package.git:master" to specify a requirement.

### ISSUE THREAD

**Issue by limbolily** [conan-io/conan#5635]
Now we must specify a requirement by using "package/version@username/channel" format, then conan will find the requirement from conan-center and any other remotes.

Is it any chance to support use format like "https://github.com/user/conan_package.git:master" to specify a requirement? I think that's a more flexible way to use recipes without gathering all recipes you need to your local cache or remote conan server.

**Comment by danimtb** [comment]
Hi @limbolily and thanks for reaching us with your proposal.

Currently, there is no possibility to specify requirements by git url and I doubt something like this will be implemented in the future.

Having the packages specified by URL could lead to important inconsistencies in the dependency graph for your application, such as the impossibility to detect a conflict, untracked changes in the git repository, removed github repositories... But the most important point is that URL couples the "remote" the recipe comes from (github) with the "reference" of the package (the whole URL): What if I want to store the recipe elsewhere in other remote? Do I have to change the URL in all of the recipes that have this as a requirement?

Not to say that doing that will make Conan tightly coupled to git which may be something totally unwanted for some users.

On the other hand, having the recipes in your local cache is a safe step. It is made to guarantee that the recipe you got works at least for the configuration you just used. It also provides the mechanisms to create packages in a repeatable way for different configurations.

Addressing dependencies by the reference is the model implemented in Conan and is done on purpose. Conan creates packages with binaries that are associated to a source code (of course!) but packages are not stored in git repos which are made for source code, but in binary repositories such as Artifactory.

So I would say that Conan will keep using the current model of specifying requirements by reference and having them decoupled from the remote they are stored in for the reasons explained above.

**Comment by limbolily** [comment]
Hi @danimtb.

I think the "git repo" way to specify requirement is just the extension to "reference" format,they are just the same.When user specify a "git repo" as a requirement,Conan can download the repo,checkout the branch or commit then compute the hash value,just like the "reference" way.The "git repo" way just the beginning,it can easily extend to "svn repo","hg repo","local path"...

The "reference" or "git repo" just the way to specify recipe,I don't think it's related to the binaries,"git repo" just the place store the recipe.In my practice, I gather a lot of recipe from "conan-community github repo" and "bincrafters github repo".It's just boring clone the repo and then export to my local cache or upload to my conan server remote.

**Comment by danimtb** [comment]
As I mentioned above, there are some important reasons not to consider a git repo URL as the reference of a package.

Also, doing just the clone of a git/hg/svn... before a conan create shouldn't be that big or a deal and it would be quite a lot of work to maintain and integrate the commands inside Conan. Just a simple script could repeat the steps for your specific SCM tool.

**Comment by memsharded** [comment]
> I think that's a more flexible way to use recipes without gathering all recipes you need to your local cache or remote conan server.

Initially it seems so, but if we also have a look to other languages, what we have learned from Java is that using packages (not source origins) has been working very well, while others, like golang using git urls like the one you propose doesn't really work and now they are moving to packages (modules) too. So given all the above described complexities, it is not something that will be worth such a big investment.

**Comment by danimtb** [comment]
Closing this as there is no work planned in this direction to support defining depenencies as git URLs. Thanks for the feedback! 😄
