### ISSUE TITLE
Persist settings.yml.new warning until it has been removed

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#5636]
I spent quite a while trying to fix a problem after I upgraded conan to a new version.

Turns out I had missed the initial warning about not migrating settings because mine had already been modified.

I think it is quite easy to miss some output of a single command, especially if it's a command with long output, like a conan install with lots of packages or a conan workspace install.

In my opinion the warning about the settings not being migrated should be output from every command until the settings.yml.new file has been deleted.

**Comment by danimtb** [comment]
we have had this reported in the past actually and I agree we should make it more evident.

BTW, was your settings.yml really customized? I sometimes feel that the check is a bit conservative in that sense

**Comment by Lawrencemm** [comment]
I do not recall having touched the settings.yml, no.

**Comment by danimtb** [comment]
Thanks for the answer. I suspect that the check for changes could be improved and this issue will have less importance. Still, we will have to check the impact for including that warning as it could be too annoying in every output. Thanks!

**Comment by lasote** [comment]
It would be definitely too much annoying.

**Comment by Lawrencemm** [comment]
In what scenario should the settings conflict not be dealt with promptly?

Isn't it the purpose of warnings to annoy the user until they resolve the
situation?

**Comment by danimtb** [comment]
I think this issue should focus on detecting if the migration to settings is done correctly as there are some cases where the *settings.yml.new* file is created even without having a modified *settings.yml*

**Comment by memsharded** [comment]
All the ``settings.yml`` migration has changed in 2.0, closing this ticket as outdated.
