### ISSUE TITLE
Please consider relaxing restriction on the "future" python dependency

### ISSUE THREAD

**Issue by testworksau** [conan-io/conan#5637]
We install `pefile` which does not have an upper limit set for the `future` dependency.

Conan does, which means we see the below issue sometimes depending on the order the dependencies are installed in our venv. 

```
pkg_resources.ContextualVersionConflict: (future 0.17.1 (c:\buildagent\work\762cb4f7a7a648c2\.venv\lib\site-packages), Requirement.parse('future==0.16.0'), {'conan'})
```

This dep was added in commit 86b33376756ca38c0a365c5a2143c00ef699bb9a

There are other commits that have relaxed other dependencies:
https://github.com/conan-io/conan/pull/1345

The latest version of future is 0.17.1, released October 2018. It doesn't change too frequently.

**Comment by danimtb** [comment]
ok, we could try to relax the requirements but we will have to check if windows pyinstaller still works after that

**Comment by memsharded** [comment]
If you want @testworksau consider submitting a pull request that relax this dependency, to kick CI, so at least we will know if something breaks with this modification. Remember to add ``@pyvers: py27, py34, py35, py36`` so this correctly fires all python versions testing.

**Comment by testworksau** [comment]
All done @memsharded - hopefully I did it correctly 👍
