### ISSUE TITLE
Wrong default libcxx written to ~/.conan/conan.conf for Ubuntu 16.04.1, GCC 5.4

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#564]
Ubuntu 16.04.1, GCC 5.4, the default `compiler.libcxx` written to `conan.conf` is `libstdc++`.  The actual default on that machine is `libstdc++11`.   This was the root cause of my concern in #551.

I've found the most straightforward way to check the default ABI is checking the output of `gcc --version -v` for `--with-default-libstdcxx-abi=new`.

For example:

        output = StringIO()
        self.run("g++ --version -v", output)
        contents = output.getvalue()
        use_libcxx11 = '--with-default-libstdcxx-abi=new' in contents
        libcxx = 'libstdc++11' if use_libcxx11 else 'libstdc++'

Let me know if you'd like a PR for it.

Another couple of things I ran into while mulling the problem of getting the Conan package ABI setting to match what the library builds itself with, and then getting the `test_package` to match its parent's setting:

1. You can access the options set by requirements (`self.options['caf'].blah`), but you can't access the requirements' settings.   In `test_package` I'd like to access the parent's `version` and `libcxx`.
2. In the `test_package` `conanfile.py`, if you set `self.settings.compiler.libcxx` in `config*()`, it gets overwritten with the `conan.conf` value before it gets to `build()`.   It would better IMO to read `conan.conf` before the `config` methods are called.
3. There is no way to check what settings are passed on the command line.

For now I'm inclined to go with the flow and not worry about these things, but they're something to think about for the future (or maybe some of them are as designed).  Fixing the `conan.conf` GCC ABI generation would have the most positive impact for me.

Thanks,

**Comment by memsharded** [comment]
Actually, this is on purpose. ``libstdc++`` is the common denominator, so a library/package built in latest ubuntu with gcc>5.1 can be used in ubuntu 14.04 with the same gcc version. And this latter one is an extremely common setup, while it is also common to generate packages with conan-package-tools, which use docker images with lattest ubuntu. 

So, changing the default to be ``libstdc++11`` would actually affect the build of many packages that are using such backwards compatible ``libstdc++`` for consumers in older distros.

About your other questions:

1. The settings are always the same, for all the packages in the dependency graph. There is a feature request to allow different settings for different packages in the same dependency graph, but still has not been implemented. So the settings are the same. If you want the parents (we usually call them dependencies, or upstream packages), you might access them with ``self.requires``
2. As previously discussed, a setting is not something you can set in your conanfile, it is a property of the system, and can only be defined as an input to the conanfile. What the conanfile can do is err (raise Exception) for those settings not support by that package recipe.
3. Not sure if I understand, you mean that a recipe should know if a setting came from the command line or not? What would be the use case for that? 

Changing the default ``libcxx`` to ``libstdc++11`` is a trivial thing, just modify it in conan.conf. If this is something very inconvenient, what would you suggest to do, taking into account that we cannot break the package creation for other users? Thanks very much again for your feedback!

**Comment by sourcedelica** [comment]
Ok - that sounds reasonable.   I didn't get it before that it's not intended that you should be able to set a setting in a Conanfile.  You can technically, though it's not documented, now I know why :)  Re: the question about the command line setting, I wanted to set the value to `libstdc++11`, but only if it was not passed on the command line.  But if you're not supposed to set it at all in the Conanfile then it makes that question moot.

**Comment by memsharded** [comment]
Ok, thanks very much for your understanding. Many times I'd love to go for the solution I would want, in this case, I'd definitely want to detect ``libstdc++11`` and use it by default. But consumers and community have to be considered and tradeoffs have to be made. Cheers!
