### ISSUE TITLE
how to use conan pkg for local development in codeblock

### ISSUE THREAD

**Issue by amiya-elear** [conan-io/conan#5641]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.16.0
os ubuntu 16.04

i want to use conan pkg for my local development in codeblock without  copying manually in lib and include folder any automated way to install and uninstall pkg in my local system

**Comment by czoido** [comment]
Hi @amiya-elear,

What you could try to is to creating a `CMake` project, and use the [CMake CodeBlocks generator](https://cmake.org/cmake/help/latest/generator/CodeBlocks.html)
You have to include the `conanbuildinfo.cmake` in your CMakeLists.txt:

```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```

and link with the libraries that you specified in the `conanfile.txt`:

`target_link_libraries(exe_name ${CONAN_LIBS})`

Very similar to the [getting started example](https://docs.conan.io/en/latest/getting_started.html) but changing the `CMake` generator to the use `CodeBlocks` one.

Hope this helps :)

**Comment by amiya-elear** [comment]
what actually i want i created a pkg new-pkg with function a() and i want create new-pkg-b using function a () so i need install new-pkg to my uer local lib and include so that when i use function a () it dosnt fail for other repo

**Comment by czoido** [comment]
I think that you should create a package for the library that contains function `a()`. 
All the information is in the [creating packages](https://docs.conan.io/en/latest/creating_packages/getting_started.html) section of the docs.
Then you could install this dependency to the local cache and consume it from your `new-pkg-b` project.
Please let me know if that helps or you need further information. Thanks a lot.

**Comment by amiya-elear** [comment]
i need to use those pkg for my local development or testing so how can i consume it from your new-pkg-b project. because those are have some dependency and those are show use by code block so how can i specify all path in code block

**Comment by czoido** [comment]
From what I can understand maybe the editable feature could help here. Please check the new Conan 2.0 docs about how to develop packages locally: https://docs.conan.io/2/tutorial/developing_packages.html
Also, the new Conan 2.0 tutorial gives a hands-on introduction to Conan.
Closing this as this should be covered by docs, but please feel free to reopen if you have any more questions.
