### ISSUE TITLE
Unable to do a conan create without user & channel

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#5643]
While I was writing a test for Conan, I created a recipe without name and without version. Then I wanted to create a package using that recipe but without user and channel, but found that the command line does not support it.

```
$ conan create . name/version
ERROR: conanfile didn't specify name
```

As we used to expect ``<user>/<channel>`` by default (and detected the whole reference by the ``@`` char), now specifying the ``<name>/<version>`` only does not work.

I don't know if we can do something to improve this or we will have to wait until 2.0 to change the command line syntax

**Comment by lasote** [comment]
`conan create . name/version@`

**Comment by danimtb** [comment]
Ok, that works. But I feel the syntax is a bit strange....
