### ISSUE TITLE
Build requirement update breaking a build

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#5651]
We are using Conan to build a project alongside its dependencies. One of them is a custom libcurl recipe:

    requires = (("OpenSSL/1.1.1b@com/stable"), ....)

The build itself requires CMake, taken from the main public repository:

    build_requires = "cmake_installer/[>3.12]@conan/stable"

Everything was working fine, until the latest update to CMake (v3.15.2), and it now fails with:

>     Requirement OpenSSL/1.0.2s@conan/stable conflicts with already defined OpenSSL/1.1.1b@com/stable
>     To change it, override it in your base requirements

This behaviour seems strange, because a build requirement (something our project will never link against) is now breaking our own build. Is this normal behaviour? 
If so, can we prevent it from happening in the future?

**Comment by Adnn** [comment]
Actually, there was already successful builds with this exact version of CMake (3.15.2) Since the recipe did not change either since those successful builds, the situation seems very bizarre.

**Comment by Croydon** [comment]
Please note for the future that this is the wrong issue tracker as it isn't a Conan bug.

For packages of the conan-community the correct issue tracker is https://github.com/conan-community/community/issues

**Comment by Adnn** [comment]
Sorry for the inconvenience, I did not realize there was an update to the base recipe itself
