### ISSUE TITLE
conan inspect --raw prints status messages

### ISSUE THREAD

**Issue by thk1** [conan-io/conan#5656]
The documentation of `conan inspect --raw` states: "Print just the value of the requested attribute". However, the command prints not only the requested attribute but also status and warning messages like "WARN: Migration: Updating settings.yml" or "my_python_required/0.1@user/channel: Not found in local cache, looking in remotes...". This makes it difficult to use `conan inspect` in automation scripts.

Steps to reproduce (variant A):
```
~/my_package  » conan --version
Conan version 1.18.1
~/my_package » pip3 install conan==1.17.0
~/my_package » conan inspect . --raw name
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: ...
WARN: ****************************************
my_package
```

Steps to reproduce (variant B):
```
~ » conan download -r bincrafters boost_any/1.69.0@bincrafters/stable 
~ » conan remove -f boost_base/1.69.0@bincrafters/stable
~ » conan inspect -r bincrafters --raw name boost_any/1.69.0@bincrafters/stable
boost_base/1.69.0@bincrafters/stable: Retrieving from server 'bincrafters' 
boost_base/1.69.0@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt: 100%|##########| 103/103 [00:00<00:00, 60.9kB/s]
Downloading conanfile.py: 100%|##########| 10.1k/10.1k [00:00<00:00, 6.13MB/s]
Downloading conan_export.tgz: 100%|##########| 758/758 [00:00<00:00, 616kB/s]
Decompressing conan_export.tgz: 100%|##########| 758/758 [00:00<00:00, 141kB/s]
boost_base/1.69.0@bincrafters/stable: Downloaded recipe revision 0
boost_any
```

Conan version: 1.18.1
Operating system: Ubuntu 18.04.3

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Thanks for reporting it. We need to honor `raw` argument.
