### ISSUE TITLE
Add --dumpersion to main Conan command

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#5666]
We expect to need to detect the Conan version in the CLion plugin at some point, it would be nice to have an option for the version to be dumped similar to gcc/clang's `-dumpversion` option so that we don't have to parse the output.

**Comment by memsharded** [comment]
This would probably be part of the conan command line improvements, can't be done in isolation. There are many commands that would output different formats, and for example the ``--raw`` argument is already being used in other commands to provide outputs that do not need parsing.

**Comment by memsharded** [comment]
Not planned at the moment, for automated, not-regex necessary, Conan 2.0 provides a ``conan version --format=json`` output.
