### ISSUE TITLE
Installing and keeping Conan up to date on devs machines in an enterprise

### ISSUE THREAD

**Issue by mfronczyk** [conan-io/conan#5669]
Right now we're using a custom build and packaging system (a bunch of batch, Python and ant/ivy scripts) that every developer checks out from a version control repository. The scripts are written in a way that they try to update themselves from the newest revision in the repository. We work in a controlled environment, with limited access to the Internet and permissions to install custom apps on the machines. The project team consists of about 50 developers. We're thinking about incorporating Conan and have few questions:

1) Is there a standalone version of Conan that every developer can just copy to a folder and run it from there? If it could be installed this way, than we could automatically provide devs with updates by asking them to check it out from a version control system.
2) If installer is the only standalone option and we ask developers to install the version provided by us, is there any way to update it automatically for every developer afterwards? I'm worried that asking people to install a new version manually won't work well and people will be getting back to us with issues only due to not having the most recent version of Conan installed.
3) Does Conan support something like MIN_VERSION, so we could set it in our recipes and developers would get an error if they try to use a recipe intended for a newer version of Conan? That should help with point 2 because then they'll know that stuff doesn't work due to using an old version of Conan.
4) What's the recommended way to make sure that all developers have Conan config installed and up to date with any changes? Is there a way to tell Conan to execute "conan config install" every time it's executed?

**Comment by lasote** [comment]
> Is there a standalone version of Conan that every developer can just copy to a folder and run it from there? If it could be installed this way, than we could automatically provide devs with updates by asking them to check it out from a version control system.

We provide installers on https://conan.io. Also, it is possible to generate executables (with the python interpreter embedded) using pyinstaller.

> If installer is the only standalone option and we ask developers to install the version provided by us, is there any way to update it automatically for every developer afterwards? I'm worried that asking people to install a new version manually won't work well and people will be getting back to us with issues only due to not having the most recent version of Conan installed.

No. We don't provide any other mechanism rather than `pip install --upgrade`, but it depends, if you are using some system package manager (like apt or whatever) you could put a `conan.deb` in a company `debian` repository (or any other format) and update like that.
In general, the same as any other tool.

> Does Conan support something like MIN_VERSION, so we could set it in our recipes and developers would get an error if they try to use a recipe intended for a newer version of Conan? That should help with point 2 because then they'll know that stuff doesn't work due to using an old version of Conan.

Not out of the box, but it could be implemented using [hooks](https://docs.conan.io/en/latest/extending/hooks.html)

> What's the recommended way to make sure that all developers have Conan config installed and up to date with any changes? Is there a way to tell Conan to execute "conan config install" every time it's executed?

No, there is no official way to do that, but you could install a wrapper script for Conan. Or maybe on startup is enough?

**Comment by mfronczyk** [comment]
Thanks, seems like having something similar to bazelisk which downloads standalone Conan (or uses the installer if possible) would be the way to go.

**Comment by lasote** [comment]
Thanks for your answer. I'm closing this issue if you have any other question or comment we can re-open it if needed.
