### ISSUE TITLE
output is not saved when using self.run() with win_bash=True

### ISSUE THREAD

**Issue by zlalanne** [conan-io/conan#5670]
To help us debug your issue please explain:

Using Conan version 1.18.1 on Windows. Running conan from the git bash shell that comes with the Windows git installation.

I'm packaging up some tools to use in our Conan infrastructure. As part of our test_package I like to run the tool to just verify the tool was added to the PATH correctly and can be run. One test I do is run a tool with `--version` to check that the version packaged was the one intended.

What I'm having trouble with is conan doesn't seem to capture STDOUT when callign tools using `self.run()` when `win_bash=True`).

So something like this doesn't actually work:

```python

buffer = StringIO()
self.run("ls --version", output=buffer, win_bash=True)

# This does not print anything. STDOUT was not captured.
print("My output was:")
print(buffer.getvalue())

```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
You are right, it is actually written in the sources as a `FIXME` 😓 

https://github.com/conan-io/conan/blob/c15779cb336fd208758832263f4ef176ce60b856/conans/model/conan_file.py#L260

**Comment by nicememory** [comment]
That's interesting. I'll invetigate on this FIXME.

**Comment by jgsogo** [comment]
Thanks @nicememory, if you need any help, just tell us. And fee free to reach us in slack too 😊

**Comment by nicememory** [comment]
I haven't used slack, how to use it?

**Comment by jgsogo** [comment]
Slack is an application like the old IRC, there is one C++ community with people all over the world (http://cpplang.slack.com) with many channels to talk about different C++ topics. There is one channel dedicated to `#conan` where you can share your experience, ask for help,... See you there! ;D

**Comment by nicememory** [comment]
Could you invite me to the cpplang workspace? My email is nicememory@gmail.com

**Comment by memsharded** [comment]
Closing this ticket as outdated, the output system has been fully revamped in Conan 2.0, please create new tickets if necessary, thanks!
