### ISSUE TITLE
`conan build --build` not working with custom `build_folder` in configure.

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#5678]
I am creating multi-config packages and have a `build` method such as this one:
```
    def build(self):
        for build_type in ["Debug", "Release"]:
            cmake = CMake(self, build_type=build_type)
            cmake.definitions["CMAKE_DEBUG_POSTFIX"] = "d"
            cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = "../conan_paths.cmake"
            cmake.configure(build_folder=self.build_folder + "/" + build_type)
            cmake.build()
            cmake.test()
            cmake.install()
```

If now I am running `conan build --build ..`, the configure method of the CMake build helper is not executed, and conan wrongly assumes that the build folder for CMake will be `self.build_folder`.
I thus get the error
``` 
Error: could not load cache
Error: conanfile.py .... Error in build() mehtod, line xx
  cmake.build()
  ConanException: Error 1 while executing cmake --build '/path/to/build/folder' '--' '-j8'
```

What I can do now:
- Always call `conan --configure --build ..`, `conan --configure --test ..`, etc.
- Always specify the `build_dir` in the `cmake.build()` invokation.

What would be nicer:
- If the CMake build helper took `build_folder` argument in the constructor. 
- If when calling configure, even though no `--configure` is specified,  the function could not return immediately, but still save the arguments, as they are relevant for the `build()` function invokations.
https://github.com/conan-io/conan/blob/c15779cb336fd208758832263f4ef176ce60b856/conans/client/build/cmake.py#L185-196
If the return statement was put after l.196, the behavior was "consistent", because the `configure()` function has the side effect of setting `self.build_dir`.

What do you think would be the best / most consistent usage? It's unintuitive to have the side effect in the `configure()` method, then I'd rather set it in the constructor or I have to specify it on every function call.
This was observed with Conan 18.1.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi, yes, At first sight, delay the return in the `configure` a couple of lines could make sense.

**Comment by memsharded** [comment]
Closing this ticket as outdated with newer CMake integrations and ``layout()``
