### ISSUE TITLE
[suggestion] `cmake.test()` option / environment variable to continue on failure

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#5679]
I am developing a package and calling the unit tests in the process calling `cmake.test()`. However, if any of the unit tests fail, conan does not continue with the packaging process, but exits with an error message.

It would be great if you could disable that conan errors out after the failed tests. Either by an option to the `test` function or by an environment variable, just like the `output_on_failure` argument.

I am using Conan 1.18.1.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
> It would be great if you could disable that conan errors out after the failed tests. Either by an option to the test function or by an environment variable, just like the output_on_failure argument.

Using an option is probably not the way to go, as options by definition produce a different binary.

It doesn't seem that it would be a very common use case, and I think it can be directly implemented in recipes, something like:

```python
def build(self):
     ...
     try:
          cmake.test()
     except:
          if os.getenv("CONAN_CONTINUE_PACKAGE"):
               self.output.warn("There was an error running tests")
         else:
              raise
```

Still seems a bit weird to me. I would definitely not want to have packages created that didn't pass the tests, and this kind of warnings easily pass unnoticed in CI and by developers. So in my opinion Conan should not provide a built-in, explicit way to do so. Please let me know what you think.

**Comment by KerstinKeller** [comment]
> Using an option is probably not the way to go, as options by definition produce a different binary.

Sorry I didn't mean option, but function parameter to the `test()` function.

Yes, I agree that a release build should have all unit tests passing, and I wouldn't want to release a package where the unit tests are not passing.

But as for the development flow to use conan, if you're on a branch, you might want to see if the rest (packaging / consumption / etc. )  works, even if some unit tests are still failing.

This is why I would avoid having the code that you proposed in any of our recipes. Instead rather define an environment variable to tolerate failing unit tests, if not doing release builds.
Also when migrating projects that do have failing unit tests (yes, unfortunately the case here), I'd rather accept failing unit tests then have developers remove the test cases.

However, thinking about it again, I can also create different stages for our build jobs. One can be `test`, running `conan build --test`. Even if that is failing, I can still afterwards run `conan build --install`.
An actual `conan create` will fail, but that's ok.

**Comment by memsharded** [comment]
Closing as outdated
