### ISSUE TITLE
'python_requires' does not retrieve the latest revision

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#5681]
I have multiple revisions ('scm' revisions) of a 'python_requires' package on Artifactory:

```
base_recipe/1.0.0+meta.build1@user/channel
base_recipe/1.0.0+meta.build2@user/channel
base_recipe/1.0.0+meta.build3@user/channel
```

and I am using a semver range expression to find a compatible package:

`base = python_requires("base_recipe/[~=1.0.0]@user/channel")`

According to the 'revisions' documentation, conan should retrieve the latest version.  But this does not seem to be working for 'python_requires' packages.  Even with `--update` it seems I simply receive first on the Artifactory list (build1).

**Comment by memsharded** [comment]
Hi @GordonJess 

Those are not revisions, that is semver build meta-information, that as defined by the semver specification is ignored.

The revisions that are resolved to latest are the Conan revisions. They are in the form ``pkg/version@user/channel#revision``. Please check again https://docs.conan.io/en/latest/versioning/revisions.html. Thanks!

**Comment by GordonJess** [comment]
Hi @memsharded ,

>Those are not revisions, that is semver build meta-information

Yes, I'm just showing that I have metadata in my `version`.  The version number is unchanged (say, since it is only documentation that was changed - no logical change in the code), but each of these packages was built from a different git commit is thus a different revision.

My understanding is that the semver expression will find the most recent compatible **version**, and omitting the `#revision` will tell conan to get the most recent **revision**.

But now I am beginning to understand that I cannot use metadata and revisions together, is that right?

**Comment by memsharded** [comment]
The metadata can be there, it will simply be ignored. But if those packages were created with revisions, and uploaded to a server that support revisions, then the latest one in time should be the one retrieved and otherwise it is probably a bug. But semver is not involved there, it is the last one as indexed by the remote server. 

Could you please check and share what you have in your remote index? Also do a print of the revisions of that package in the remote from the conan command line?

**Comment by GordonJess** [comment]
Sure, in what kind of format is best?  This is how I see it in Artifactory:

- tools
    - base_recipe
        - 1.0.0+9ffa41e.build7/master_testing
            - 9ffa41e946b364d35dd907e51a25f9c9f626f4c1
        - 1.0.0+aed22c1.build13/master_testing
            - aed22c1fdc0034749f4e8d975a41c6e6da446e52

`git log` outputs:

```
commit aed22c1fdc0034749f4e8d975a41c6e6da446e52
Author: Gordon Jess
Date:   Tue Aug 27 15:18:01 2019 +0200

    commit msg

commit 9ffa41e946b364d35dd907e51a25f9c9f626f4c1
Author: Gordon Jess
Date:   Mon Aug 26 17:37:28 2019 +0200

    commit msg

```
<br />

and when I try retrieve dependencies...

```
conan install . --update
base_recipe/1.0.0+9ffa41e.build7@tools/master_testing: Downloaded recipe revision 9ffa41e946b364d35dd907e51a25f9c9f626f4c1
```

<br />
<br />

> Also do a print of the revisions of that package in the remote from the conan command line

I cannot search revisions on the command line as `conan search -rev` only takes full package reference **including** metadata.

**Comment by memsharded** [comment]
Yes, please, download and share the ``index.json`` file that you should see in Artifactory, it should contain something of the form:

```json
{
  "reference" : "hello/0.1@user/testing",
  "revisions" : [ {
    "revision" : "0",
    "time" : "2019-08-06T14:43:30.928+0200"
  } ]
}
```

**Comment by GordonJess** [comment]
Hi @memsharded,

It seems there is one `index.json` for each package reference.  It is basically the same as the example you posted - there is only one revision listed.  Could it be that Artifactory does not recognise that this is the same version due to the metadata in the package reference?  I know it is supposed to be ignored, but I see no other reason for the packages to be listed in this way.

- base_recipe
  - 1.0.0+9ffa41e.build7/master_testing
    - 9ffa41e946b364d35dd907e51a25f9c9f626f4c1
    - index.json
  - 1.0.0+aed22c1.build13/master_testing
    - aed22c1fdc0034749f4e8d975a41c6e6da446e52
    - index.json
  - 1.0.0+aed22c1.build13/master_testing
    - db9a9faad4679f388d6a599a4c796675ab0ec79a
    - index.json

**Comment by memsharded** [comment]
Hi @GordonJess 

Oh, yes, I think now I understand the issue.

Yes, for Conan, every different full package reference, as string, including the full version, is a different package. If something is named different, it is something different, and stored in a different folder.

A different thing is the resolution of dependencies. When a version range in ``pkg/[version-range]@user/channel`` is used, it will go and get all package references matching that pkg-user-channel, and then evaluate the versions following the semver specification (as implemented by node-semver python library, we didn't implement it). Such version resolution will lead to a full package reference. The ``+build.metadata`` part in the version is discarded by semver, so the version range will match any of them. ``+build.metadata`` cannot be relied by definition to retrieve the last one.

> Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

Once a full package reference is obtained,  the "revision" mechanism is used. By default, the latest revision in the server is the one that is fetched, but that revision will be for a given package reference (including the ``+build.metadata`` part).

I think I would aim for a versioning scheme without trying to rely on that build metadata. Did you know that you can have the revisions to use the hash of the recipe or the git commit of the repo? I would say that you are using it, as it seems the revision matches your build metadata and I suspect it would be using the git commit. Maybe you are fine completely dropping the build metadata?

**Comment by GordonJess** [comment]
Hi @memsharded.

I think you are right that I can get by without my current metadata (as you mentioned, I can set the revision to the git hash, and get the build id from the buildinfo pushed by the artifactory plugin). 
But others might not be so lucky.  Since the version metadata field should always be ignored according to the semver specification, I would expect it to be safe to put anything I want there without consequence.

I hope you might take this into consideration while 'revisions' is still an experimental feature :-) Thx!

**Comment by memsharded** [comment]
Conan 2.0 new semver and version ranges implementation takes into account the ``+build``, and is able to sort them in the same way as other versions or pre-releases. It was better behavior than just ignoring it and letting any random order to be returned.

Then, it is not possible to use that build version field for adding random information. The recommended way to add information would be:
- Adding things to ``conandata.yml``
- Adding properties in the server side like Artifactory properties

Closing this ticket, please open new ones if necessary, thanks!
