### ISSUE TITLE
[improvement] Interaction with CMake

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#5691]
I'd like to kind of reopen the issue https://github.com/conan-io/conan/issues/2119 which discussed the question if Conan could generate a CMake toolchain file. This was closed as it was not considered interesting anymore.

Currently the integration with CMake works by generating a `conanbuildinfo.cmake` file during the `conan install` phase which is then included in the `CMakeLists.txt` of the project. This includes all the information about the dependencies **but no information about the toolchain used to build these dependencies**. There are several disadvantages to that approach:

* If you want to call CMake manually via `cmake <sourceDir>` we must still add the parameters describing the exact same build parameters as used for the installed dependencies; here are a few examples:
  * Windows: `cmake .. -G "Visual Studio 2015" -A x64`
  * Linux with embedded toolchains: `CC=/opt/arm11/bin/arm11-gcc CXX=/opt/arm11/bin/arm11-g++ cmake .. -DCMAKE_BUILD_TYPE=Debug`
* If the parameters specified here do not match the ones used to build the installed dependencies, compilation/linking will fail later
* All of the information is already there because we usually use profiles during the `conan install` command but it is not used in the build process unless we run it through Conan

There should be a generic way of injecting **all** information required for a specific build into CMake which is **not** dependent on the way how Conan is used in the workflow. That could be a toolchain file for example.

The `CMAKE_TOOLCHAIN_FILE` parameter allows the injection of all relevant toolchain information so it should be used by Conan. We still need a way of pulling the dependencies in, but in my opinion - contrary to what was discussed in the issue referenced above - that is clearly **not** in the scope of the toolchain file. My proposal would thus be to make Conan generate a toolchain file **and** a `conanbuildinfo.cmake`. The toolchain file contains the information about the compiler, sysroots, Visual Studio version, architecture, whatever, matching the parameters that were used for compiling the dependencies. The conanbuildinfo file on the other hand contains the locations of the libraries, alias targets, etc.

That way we could have the following workflow:

```bash
mkdir build && cd build
conan install .. -pr /opt/myprofile
cmake .. -DCMAKE_TOOLCHAIN_FILE=conantoolchain.cmake
make
```

**Comment by KerstinKeller** [comment]
@jasal82, I totally agree with you. I would also like to have a complete toolchain file.

However, the problem I see with this approach (at least, unfortunately for Windows / VS) is that you need to specify a VS generator, which also matches your applied profile. (It doesn't help if the default VS generator is VS 2019 but you invoked Conan with a VS2015 profile :disappointed: ). 

As described [here](https://github.com/conan-io/conan/issues/5610#issuecomment-522473743) the following works well for us:

```
cd build && mkdir build
conan install .. --pr=XXXX ..
conan build --configure ..
```

It still leaves the build invokation up to Conan, but everything after is up to the user.

**Comment by jasal82** [comment]
@KerstinKeller That's right, the VS generator cannot be set from the toolchain file. Everything else can be configured, including the platform toolset, but not the generator. No idea why they won't add that possibility.

The approach that you describe works fine for the single-package development use-case. I use that approach in my workflow as well. Where it doesn't fit is when using workspaces. Our developers must be able to work on several packages in parallel, testing integration in a consumer application. I thought to use the experimental workspace feature for that but the problem is that you can't run `conan build` there because it doesn't have a recipe. Either we need a `conan workspace build` command or some other way of injecting the toolchain parameters into the CMake build.

**Comment by lasote** [comment]
@jasal82 Yes, we totally agree. It is in our roadmap and a priority. Some ideas:
- The generators will contain only information about the deps
- There will be a different file (that could potentially include the one from the generator) containing the toolchain.
- The recipe might adjust some details (definitions, other flags, default changes...) in addition to just the base settings and that information will be also in the toolchain file. That might require a new method in the recipe.

You can read some ideas and ongoing work in the assigned projects. It is very related also with the "developer" experience and the conan local methods, workspace, etc.

**Comment by peter-moran** [comment]
https://github.com/conan-io/conan/issues/2956 also discusses generating cmake toolchain files via conan.

In particular resulted in a [custom generator for toolchain files](https://github.com/pepe82sh/ConanCmakeToolchainGenerator) which I have personally used for deploying to embedded targets with much success. It basically captures the cmake variables generated by the cmake generator and puts them in a toolchain file. This way you are not required to build your project via conan.

**Comment by memsharded** [comment]
Closing this ticket as outdated, it is referring to the legacy integrations, removed in 2.0
