### ISSUE TITLE
Dissambiguate conan install ref/path

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5693]
Now, without user and channel it is possible to do:

```bash
conan install cmake/3.14@
```

It requires the @ to dissambiguate with a path where a conanfile is. It would be nice to have a command line where the @ is not required, but we can't rely on differentiating if it is path or a reference anymore.

**Comment by lasote** [comment]
The reason goes further than the "cmake/3.14@" ugly syntax. The UX and code are confusing (ref_or_path), also with the search where the Ref can be a pattern. We should disambiguate all the parameters that could mean more than one thing, even if the command is more verbose.

**Comment by jgsogo** [comment]
@fulara suggested in https://github.com/conan-io/conan/issues/6464#issue-559558561:

Currently if you are dealing with packages that have user and channel empty (`_`)  you have to use this slightly off syntax:
```
conan install mylibrary/1.0.0@
```

If conan had an alternative --ref flag it would look as follows:
```
conan install --ref mylibrary/1.0.0
```

Right now we have to hack in our scripts to detect if user provided '@' in their names, if he didnt we are adding '@' to conan invocation.


Also I think having multiple positional arguments that have different meaning is very confusing from my perspective.

**Comment by memsharded** [comment]
Done, 2.0-alpha.4
