### ISSUE TITLE
Project wide profiles

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#5696]
Consider next situation:
I've made a project and uploaded it into github to allow my friend to push updates. My main requirement is to use `clang` for compilation or some specific settings. I need to create a global profile and make my friend to create it file too. My project unexpectedly became large and big and I already have over 9000 contributors and not all of them will follow my rules because it is unmaintainable with such large count of contributors. Does conan provide me ability to define default project's settings without making deal with global configurations/profiles?
Or just to overwrite global profile settings I need in `conanfile.txt`

So even in docs (https://docs.conan.io/en/latest/reference/profiles.html#package-settings-and-env-vars) implies to force programmers create global profiles themselves instead of making a single project-related profile once

**Comment by memsharded** [comment]
Hi @xahon 

I am not sure if I understand your question.
Profiles defining your configurations can be put in many different places:
- You can have them in your project git repo, and use a relative path to them
- You can have them in a dedicated repo, clone it where you want and use a path to them.
- You can install profiles in your conan home with ``conan config install``. This command can install profiles from git repos, or zip files served via http. This command also allows to configure custom settings.yml, remotes, and other files in the conan user home. https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install

Please let me know if this helps.

**Comment by Minimonium** [comment]
At our company, for projects that require a very specific configuration (or just default ones we fully support), we provide them with the project (but can be done via submodule, remote repo and such as was already mentioned). And we provide a `configure.sh` - a script that automatically runs install on all of these configurations into different builds. You could consider such a way too. :slightly_smiling_face:

**Comment by memsharded** [comment]
Hi @xahon 

Were those answers good to your question? In short, you can put the profiles you support directly in your repo too, so it will make straightforward to your users to use them, while making explicit the configurations you support, and it can be more than 1 (settings them on the conanfile will not allow to define more than 1 configuration).

I think that would be the best approach, so I am closing this question, but please do not hesitate to re-open or file a new issue if you have further questions. Thanks!
