### ISSUE TITLE
Conan website requires additional password when logging in from GitHub

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#57]
Hi,

Many thanks for your work on conan. I just tried logging in to conan with my GitHub profile but it requested an additional password. I may be getting confused, but I was sure this was not a requirement for biicode. Is there any reason for this? Many of the services around GitHub do not require an additional password such as Travis and AppVeyor; it adds a (minor) stumbling block to people who would otherwise log in to the system.

Cheers

Marco

**Comment by lasote** [comment]
In biicode it was exactly the same, you need a password to use the client to upload packages.
If you won't upload packages you don't need to signup in conan at all
In similar platforms like dockerhub, you need a password to upload your docker images.
Its really important/anoying to set a password?  What will be your desired behaviour?

**Comment by mcraveiro** [comment]
Ah I see, apologies - I imagined the login was "read only", for example for starring packages or some such. It makes sense then, I guess. Cheers.
