### ISSUE TITLE
[question] Stability of the SCM experimental feature

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [conan-io/conan#5704]
We have been using tags to link our git source code to specific package versions, i.e. using something like

_def source(self):
    self.run("git clone URL/foo.git")
    self.run("cd foo")
    self.run("git checkout tags/" + self.version)_

It would be nice to move to using the SCM feature, but I am worried about what happens if the feature changes.

What happens to recipes which use this feature, when the feature breaks/changes? Do the recipes then become broken and not useable?

**Comment by danimtb** [comment]
Yes, the feature is still experimental but it has been in place for a long time and I personally think that all the time and effort invested is not going to be deprecated AFAIK.

Maybe you find useful this thread about a very similar question: https://github.com/conan-io/conan/issues/4578

**Comment by Mirko-von-Leipzig** [comment]
Thanks for the info!
