### ISSUE TITLE
Private dependencies does not build/install their own dependencies

### ISSUE THREAD

**Issue by abuszta** [conan-io/conan#571]
May be similar to #183.

I have changed all my dependencies in one package to private (because they are all contained in shared library). After that one of this packages does not build their own dependencies. E.g.

foo/0.1.0@abuszta/testing dependes on bar/0.1.0@abuszta/testing

I had in PROJECT:

```
requires = ("foo/0.1.0@abuszta/testing", ...)
```

And conan builds and installs first bar and then foo.

I changed to:

```
requires = (("foo/0.1.0@abuszta/testing", "private"), ...)
```

And conan tries to install foo only. bar is no longer build/installed.

Even worse adding bar explicitly does not change that, i.e.:

```
requires = (("bar/0.1.0@abuszta/testing", "private"), ("foo/0.1.0@abuszta/testing", "private"), ...)
```

still does not cause bar to be build... Is this expected? Should private dependencies be "self contained"?

**Comment by memsharded** [comment]
Could be a bug, will check it asap.

On the other hand, please be aware of the "private" limitations. Not only that they are contained in a shared library, but they must be internal, i.e. not exposed through the library public headers, and with a compatible functionality with other versions. 
Example: you have 2 shared libs, one packages LibA/1.0 and the other one packages LibA/2.0. LibA implements some binary protocol, and 1.0 is incompatible with 2.0. If both shared libraries will be used and byte streams (could be just char[], or std::string) are passed from one shared lib to the other, it will crash.

So the general recommendation is going for normal dependencies, unless it is very strictly required to mix in the same dependency tree different versions of the same package, and always that they meet the requirements to be really private.

Thanks for reporting this issue!

**Comment by memsharded** [comment]
Just a quick question, does it fails when using from project like: ``conan install``? Or are you exporting and using it, maybe with ``conan test_package``? If not, could you try to write a ``test_package`` for your recipe and run it? I keep investigating, thanks!

**Comment by abuszta** [comment]
I'm using "conan install path_to_directory_with_conanfile -s... --build missing"

**Comment by memsharded** [comment]
I have done a couple of tests and seems to work here. 
Just to be clear:

- Private dependencies are not built if their dependent package has a binary. As it is private and there is a binary, a binary for the upstream package is not required, we don't need to retrieve nor build it. 
- The private dependencies and their transitive dependencies are listed in the conan install, it is just that the binaries are skipped if not necessary.

Maybe, if you have a minimal setup project that fails or something more detailed I can have a look, that would help to sort out the problems. Thanks!

**Comment by abuszta** [comment]
Hmm, so maybe this problem is more complex than I thought. My bar package was delivering only some common *.cmake file and not building at all. Something like this:

```
class Bar(ConanFile):
    name = "bar"
    version = "0.1.0"
    exports = "*"

    def build(self):
        pass

    def package(self):
        self.copy("*.cmake")
```

Also worth noticing there are no settings for this package as it is totally platform/os/compiler independent.

From foo package I was using this cmake files by injecting them into foo's CMakeLists.txt (I got path to bar files using os.path.join(self.deps_cpp_info['bar'].rootpath, "somefile.cmake")).

My current workaround is defining explicitly bar as public like this:

```
requires = ("bar/0.1.0@abuszta/testing", ("foo/0.1.0@abuszta/testing", "private"), ...)
```

I will try to create minimal reproduction scenario recipes.

**Comment by memsharded** [comment]
Well, even if it is delivering some cmake scripts, they will not be needed to build Foo if it is already built, right? Yes, a minimal reproducible project would be great, thank you.

**Comment by abuszta** [comment]
Ok, I think I got it. Problem is when multiple packages depend on bar.

Foo and NotFoo (only class name and name attribute differs):
```
class Foo(ConanFile):
    name = "foo"
    version = "0.1.0"
    settings = "os", "compiler", "build_type", "arch"
    exports = "*"
    requires = "bar/0.1.0/abuszta/testing"

    def build(self):
        pass

    def package(self):
        pass
```

Bar:
```
from conans import ConanFile

class Bar(ConanFile):
    name = "bar"
    version = "0.1.0"
    exports = "*"

    def build(self):
        pass

    def package(self):
        pass
```

PROJECT:
```
class Project(ConanFile):
    name = "project"
    version = "0.1.0"
    settings = "os", "compiler", "build_type", "arch"
    requires = (("foo/0.1.0@abuszta/testing", "private"), ("notfoo/0.1.0@abuszta/testing", "private"))
```

After exporting all of them:
conan install ../project_dir --build missing:

```
Requirements
    bar/0.1.0@abuszta/testing from local
    foo/0.1.0@abuszta/testing from local
    notfoo/0.1.0@abuszta/testing from local
Packages
    bar/0.1.0@abuszta/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    foo/0.1.0@abuszta/testing:1433d85d36713664e822d9308dcc89479ef266a7
    notfoo/0.1.0@abuszta/testing:1433d85d36713664e822d9308dcc89479ef266a7

foo/0.1.0@abuszta/testing: Installing package 1433d85d36713664e822d9308dcc89479ef266a7
foo/0.1.0@abuszta/testing: WARN: Package doesn't have a remote defined. Probably created locally and not uploaded
foo/0.1.0@abuszta/testing: Building your package in /Users/abusz/.conan/data/foo/0.1.0/abuszta/testing/build/1433d85d36713664e822d9308dcc89479ef266a7
foo/0.1.0@abuszta/testing: Configuring sources in /Users/abusz/.conan/data/foo/0.1.0/abuszta/testing/source
foo/0.1.0@abuszta/testing: Copying sources to build folder
foo/0.1.0@abuszta/testing: Generated txt created conanbuildinfo.txt

foo/0.1.0@abuszta/testing: Package '1433d85d36713664e822d9308dcc89479ef266a7' built
foo/0.1.0@abuszta/testing: Build folder /Users/abusz/.conan/data/foo/0.1.0/abuszta/testing/build/1433d85d36713664e822d9308dcc89479ef266a7
foo/0.1.0@abuszta/testing: Generated conaninfo.txt
foo/0.1.0@abuszta/testing: Generated conanbuildinfo.txt
foo/0.1.0@abuszta/testing: Generating the package
foo/0.1.0@abuszta/testing: Package folder /Users/abusz/.conan/data/foo/0.1.0/abuszta/testing/package/1433d85d36713664e822d9308dcc89479ef266a7
foo/0.1.0@abuszta/testing package(): WARN: No files copied!
foo/0.1.0@abuszta/testing: Package '1433d85d36713664e822d9308dcc89479ef266a7' created
notfoo/0.1.0@abuszta/testing: Installing package 1433d85d36713664e822d9308dcc89479ef266a7
notfoo/0.1.0@abuszta/testing: WARN: Package doesn't have a remote defined. Probably created locally and not uploaded
notfoo/0.1.0@abuszta/testing: Building your package in /Users/abusz/.conan/data/notfoo/0.1.0/abuszta/testing/build/1433d85d36713664e822d9308dcc89479ef266a7
notfoo/0.1.0@abuszta/testing: Configuring sources in /Users/abusz/.conan/data/notfoo/0.1.0/abuszta/testing/source
notfoo/0.1.0@abuszta/testing: Copying sources to build folder
notfoo/0.1.0@abuszta/testing: Generated txt created conanbuildinfo.txt

notfoo/0.1.0@abuszta/testing: Package '1433d85d36713664e822d9308dcc89479ef266a7' built
notfoo/0.1.0@abuszta/testing: Build folder /Users/abusz/.conan/data/notfoo/0.1.0/abuszta/testing/build/1433d85d36713664e822d9308dcc89479ef266a7
notfoo/0.1.0@abuszta/testing: Generated conaninfo.txt
notfoo/0.1.0@abuszta/testing: Generated conanbuildinfo.txt
notfoo/0.1.0@abuszta/testing: Generating the package
notfoo/0.1.0@abuszta/testing: Package folder /Users/abusz/.conan/data/notfoo/0.1.0/abuszta/testing/package/1433d85d36713664e822d9308dcc89479ef266a7
notfoo/0.1.0@abuszta/testing package(): WARN: No files copied!
notfoo/0.1.0@abuszta/testing: Package '1433d85d36713664e822d9308dcc89479ef266a7' created
PROJECT: Generated txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
```

The bug here is that bar is not build when foo and notfoo are private.

**Comment by memsharded** [comment]
I see, good report, I will try to write a test to reproduce it, thanks!

**Comment by memsharded** [comment]
Able to reproduce, working on a fix.
