### ISSUE TITLE
Conan search/remove patterns pick up local file names

### ISSUE THREAD

**Issue by DavidSpickett** [conan-io/conan#5710]
When running the Conan "search" or "remove" commands you can provide a package reference or a pattern. I found that if the pattern matches a local file name, it will use that name as the search term. (or at least appears to, perhaps the error is misleading)

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
$ conan --version
Conan version 1.18.2
```

To reproduce:
```bash
/tmp$ mkdir conantest && cd conantest
$ touch some_long_file_name
$ conan search not_a_file*
There are no packages matching the 'not_a_file*' pattern
$ conan search some_long_file*
There are no packages matching the 'some_long_file_name' pattern
```

When the pattern matches a file in the local directory it uses that name instead of searching with the pattern in the local cache. This also applies to remove:
```bash
$ conan remove not_a_file*
WARN: No package recipe matches 'not_a_file*'
$ conan remove some_long_file*
WARN: No package recipe matches 'some_long_file_name'
```

Is this expected behavior? I thought perhaps it was for searching using a recipe file but that didn't seem to make a difference.

My use case is that I have two packages with the same starting name. Let's say "packagesupport" and "package". I wanted to remove both of those from my cache, but there is was a binary "package-test" in the build folder that was my cwd. So "conan remove package*" used "package-test" and didn't find anything to remove.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by DavidSpickett** [comment]
Doh! I just realised my shell is expanding the name for me. Putting quotes around the name works as expected.

Sorry for the false alarm.

**Comment by memsharded** [comment]
Yeah, shell expansion works differently in different OS and shells. We should try to put quotes every place in the docs too, if it is not there in some place, please feel free to point it, or even directly submitting a pull request to fix it. Thanks!
