### ISSUE TITLE
If package in workspace doesn't have settings then accessing {{ settings.build_type }} in layout file blows up

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#5712]
Conan 1.18.1

I wanted to test my new generator as editable package with workspaces feature, so all of packages had `build_type` except for one, which was pure python without any settings.

When I specified layout at top level conan failed with:
```
ERROR: Error parsing layout file '/home/default/ws/layout_waf' (for reference 'ConanWafGen/0.12@user/channel')
'settings.build_type' doesn't exist
'settings' possible configurations are none
```

Trying Jinja trick like `{{ settings.build_type|lower if settings.build_type }}` didn't work either because Conan raises error immediately instead of returning an undefined value.

I also tried to "unspecify" layout for just one package by adding `layout: none` for this particular package but this effectively meant "fallback to workspace layout". Seems it should be possible to have some empty file or specify layout for all packages but one, but would be nice to have a better solution out of the box.

To reproduce you may take a workspace at https://github.com/conan-io/examples/blob/master/features/workspace/cmake and change one package (or add a new one) without `settings` (maybe the one from python_requires should work).

**Comment by jgsogo** [comment]
Hi!

Have you tried some other Jinja2 syntax like: `{% if settings.build_type %}{{ settings.build_type|lower }}{% endif %}` or `{{ settings.build_type|default="" }}`? Jinja2 is almost a programming language, and inside `{% ... %}` tags you can run _any_ python code (i.e.: `settings.get_safe("build_type")`)

**Comment by ytimenkov** [comment]
Tried just now. Same effect.
I remember writing this in my code:
```
    if not os.path.isfile(path):
        # This function is used in Jinja template and handling exceptions is
        # not easy there.
        return Undefined(path)
```
:|

**Comment by ytimenkov** [comment]
I wonder if throwing `AttributeError` in this case would make a difference and how it will affect Conan and recipes...

**Comment by jgsogo** [comment]
You can use something like this, it will work ([`settings.get_safe`](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#settings)):

```jinja2
{{ settings.get_safe("build_type")|default("value-if-not-build_type") }}
```

**Comment by ytimenkov** [comment]
That could also work.
Do you think this "know-how" should be mentioned somewhere or this ticket is enough?

Please close it if you don't think any further wok is needed.

**Comment by jgsogo** [comment]
Added here (https://github.com/conan-io/docs/issues/1406), we will mention it in the docs.

Thanks
