### ISSUE TITLE
`conan graph lock` only works with current directory as path

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#5714]
**Conan version**: 1.18.2
**OS**: Ubuntu 19.04

---

## Steps to reproduce

Create a directory structure like this:

```
+-- foo-project
  +-- pkgA/conanfile.py 
```

then,

```
$ cd foo-project
$ conan graph lock pkgA
```

## Actual behavior

I get the following error:

```
ERROR: Missing lockfile in: /full/path/to/foo-project
```

On the other hand, if I do

```
$ cd pkgA
$ conan graph lock .
```

it works (and generates the lockfile in that directory)

## Expected behavior

I expected that the command would generate the lockfile in the current directory even if the path passed as a parameter is not the current directory.

The documentation for `conan graph lock` states that it takes a `path_or_reference` which is similar to a number of other commands, and those commands work with paths that are different.

---

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by sztomi** [comment]
Actually, this seems to be more prevalent: calling `conan info` with a concrete `--lockfile` path also yields the same error unless the lockfile is in the current directory.

**Comment by lasote** [comment]
Weird, I'm trying the same and the behavior is correct. I can run `conan graph lock folder` and it generates the lockfile in the current directory for the recipe contained in the `folder`.

**Comment by sztomi** [comment]
Hmm, I'll try to create a minimal repro then. It's possible that my build script had a bug.

**Comment by memsharded** [comment]
Hi @sztomi!

I think this was fixed in Conan 1.19. I have checked and seems ok. Could you please check on your side too? Thanks!

**Comment by jaques-sam** [comment]
I also run into this issue, even with the latest Conan 1.21.
I could fix this by removing the `graph_info.json` file!

![image](https://user-images.githubusercontent.com/42445148/70631872-1e42f780-1c2e-11ea-8ed7-6dadcf3f35ff.png)

**Comment by memsharded** [comment]
Closing as outdated
