### ISSUE TITLE
Running conan create without copying source

### ISSUE THREAD

**Issue by Absurd-Mind** [conan-io/conan#5718]
Hi,

i'm currently converting an old software project to conan+cmake. The source is ~400MB big and contains ~46k files. Building the whole package with conan create takes more than 15 minutes. Calling the steps separately (install, build, package) only 24 seconds.

The cmake file is already a clean out of source build. no_copy_source did not solve the problem as there was at least one copy happening or the files weren't found. Therefore I'm not willing to invest 14.5 minutes on the CI server for a clean build.

So I have these questions:
 1) Is it fine to use the 'package development workflow' in a 'productive CI' environment? The documentation sounds more like that this workflow is supposed to only be used while working on the conanfile and not on the source
 2) Would it make sense to add an additional argument to `conan create` so that absolutely no source is copied? `conan create . mypackage/1.0@user/stable --source=sourcefolder/` or `conan create . mypackage/1.0@user/stable --source-next-to-conanfile`

I also asked on stackoverflow which raised my first question above: https://stackoverflow.com/q/57767607/562363

my conanfile looks like this:
```
class MyConan(ConanFile):
    generators = "cmake"
    no_copy_source = True

    def build(self):
        cmake = CMake(self)
        # What do I need to pass so that it works?
        # cmake.configure(source_dir="D:/git/mysources/") would work
        cmake.configure()
        cmake.build()

    def package(self):
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
```

Thank you for your support!

To help us debug your issue please explain:
- conan version: 1.18.2
- OS: Windows 10
- python: 3.7.2
- git bash: 2.20.1.vfs.1.1.104.g2ab7360
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi! thanks for reporting. 
I understand the issue. Is the checkout to `D:/git/mysources/` performed by the CI? 

Maybe it could be interesting if you try to copy the sources with the operating system directly and measure how long does it take. Why? We have some related issues where users report slow copy operations with python and suggested maybe a plugins system where the copy could be replaced with calls to the operating system. Would be nice to know if that is the case or if it takes long even copying directly.

About your questions:

> Is it fine to use the 'package development workflow' in a 'productive CI' environment? The documentation sounds more like that this workflow is supposed to only be used while working on the conanfile and not on the source

I think it is ok, it is not the canonical way but it might have a sense for you. This is interesting feedback because we have been discussed how the local commands should be for Conan 2.0 and if they should even exist.

> Would it make sense to add an additional argument to conan create so that absolutely no source is copied? conan create . mypackage/1.0@user/stable --source=sourcefolder/ or conan create . mypackage/1.0@user/stable --source-next-to-conanfile

Maybe yes. We have some ideas where we should be able to replicate a "conan create" with local directories. Still very preliminary ideas, but they could go in that direction. The bad news, we are still thinking about how it should be so it will take time. 

Thanks a lot for the feedback, I think this will help us to design a better flow.

**Comment by Absurd-Mind** [comment]
happy to help :)

> Is the checkout to D:/git/mysources/ performed by the CI?

Yes, and the developers working on the sources (see below). For me it makes sense to have the conanfile and the source in one repository. Otherwise I could checkout the source without having the conanfile, but then cmake could not work correctly because of the missing conan setup. Maybe I'm missing a crucial bit here.

> Maybe it could be interesting if you try to copy the sources with the operating system directly and measure how long does it take. Why? We have some related issues where users report slow copy operations with python and suggested maybe a plugins system where the copy could be replaced with calls to the operating system. Would be nice to know if that is the case or if it takes long even copying directly.

Copying directly in explorer also takes a lot of time. Didn't measure it but it would be in the same ballpark ~10-15 minutes.

> Maybe yes. We have some ideas where we should be able to replicate a "conan create" with local directories. Still very preliminary ideas, but they could go in that direction. The bad news, we are still thinking about how it should be so it will take time.

I have another insight in that direction: We have roughly 200 C++ Developers that we would need to train on working with conan. I personally believe that the concept of copying and caching the source code might create some problems for a small amount of developers. Even if it is just 10% it means there would be 2 teams that struggle with using this build tool.

This is another reason why I would like a local switch for create, I could easily tell the developers "if your build is slow try `conan create . --local mypackage`" instead of "try these 2-4 commands in a specific order with correct parameters"

Waiting until 2.0 for this is not a deal breaker for me, as we are currently checking if conan is a solution for our problems (looks good so far!). Hope this helps.

**Comment by lasote** [comment]
I was wondering how are the files in your repository organized and how necessary are all of them. I mean, is there (or it could be) a/several subfolder/s with the needed files for the compilation only or do you really need the whole ~46k files to build the project? In that case, maybe we could think about some optimization in that direction also. 

Your first idea was about using the `scm` feature or using `export_sources`?

Thanks again for your feedback.

**Comment by Absurd-Mind** [comment]
This project is only a very small part of the whole system (20 million LOC, ~80 GB). We are exploring ways to split this all up. I personally have no insight in the source code, but the files we need are spread over multiple folders. Writing intelligent copy rules would be very painful and error prone. Furthermore this is a burden I don't want to put on further subprojects. In short: It might work for this one subproject, but is not a general solution for the whole system.

I decided to go with the recipe and source in the same repo for two reasons
 1) cmake references conan, therefore the repository without the conan recipe makes no sense to me. When checking out the source I want to be able to directly work with it, without having to check out further files.
 2) At the moment we have a department with the sole purpose to manage the build of the complete system. We want to shift the power of building a subproject to the teams. Having a central repo with all recipes is counter productive in this regard.

From these two points follows that the developer/CI Server knows the source repo. Therefore I don't use the scm feature. I used exports_sources where needed, but tried to keep it simple which results mostly in exporting the source root directory: `exports_sources = [ 'src/*' ]`

I'm coming from a Java+maven background, so there is fair chance I'm looking at this in a wrong way...

**Comment by lasote** [comment]
> I'm coming from a Java+maven background, so there is fair chance I'm looking at this in a wrong way...

No, I think you are focused correctly. I also see more natural in this case to have the recipe within the source code repository.

> From these two points follows that the developer/CI Server knows the source repo. Therefore I don't use the scm feature. 

It is not an issue because if the CI do a checkout of the source code, Conan has a local optimization, see the note box [here](https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm) when doing a conan create to not checkout again the source code from the origin but copying it from the local sources. But that is also you want to avoid because of the size of the project. I think it might be better for you to not use the `exports_sources` and avoid the big package. But let me know if you see other drawbacks.

So ok, the approach of "selecting" the files is not the way to go for you, understood.

I think we can only think about the ongoing work (conan 2.0) to improve the "layout" of the packages to reference local folders in a similar way it's done in the local cache.

**Comment by solvingj** [comment]
This topic has come up in a broader context in discussions of workflows involving full folder copies repeated multiple times typically with small incremental changes to only a few files.  There's probably not that many ways to improve a first-time folder copy.  However, there are certainly ways to improve performance on subsequent copies.  Conan's current strategy focuses primarily on safety, and thus destroys the destination and re-creates it to guarantee the state.  This is understandable, but if it were possible to achieve substantially better performance without losing any safety, it would positively affect a great many people. 

For the vast numbers of in-source recipes using `exports_sources` in enterprise codebases today, this capability could actually make `conan create` a viable option for a "local development flow".  So far we're talking about the capability to streamline the subsequent `exports_sources` processes, but it could also optimize the the copy from `source` to `build` directory, and then also the `build` to `package` directory. 

It seems to be worth exploring the possibility of Conan having a faster uni-directional and even bi-directional "folder sync" capability when both directories have files.  There are numerous ways to approach this capability.  For example, hashing the file and comparing hashing similar to GIT, or even the less reliable timestamp comparison of Make.  Perhaps even creating our own strategy, but in any case, it seems such a feature could have much broader value than suggested originally.

**Comment by memsharded** [comment]
Local development has massively improved since then, I think this shouldn't be an issue anymore, so closing the ticket. But please create new tickets as necessary if you have any further questions
