### ISSUE TITLE
Get information/build outdated binary packages

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#572]
Feature approved (still open to discuss the implementation/user interface). Related to #555, #500 and #447 
The objective is detect the outdated packages (a new recipe has been exported without regenerate the binary packages) and provide a way to regenerate them.
- A file `recipe_hash.txt` will be generated in the export directory and will contain a hash computed from exported files.
- This hash will be created normalizing (in memory, not changing the real files) the exported files, to prevent git or text editors mess with line separators in different OSs. The timestamp won't be computed, just the files contents.
- In each package, the `conaninfo.txt` file will contain the `recipe hash` to be able to check oudated packages.
- Command `conan install --build outdated` will build missing or not sync packages.
- Command `conan search REFERENCE` will show information about the packages recipe_hash and if it is updated or not:

```
conan search bzip2/1.0.6@lasote/stable -r conan.io
Existing packages for recipe bzip2/1.0.6@lasote/stable:

    Package_ID: 0000193ac313953e78a4f8e82528100030ca70ee
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: gcc
            compiler.version: 4.9
            os: Linux
        recipe_hash: 4f45345EA2334F4545 (outdated!)
```

**Comment by memsharded** [comment]
This was released in 0.15, right? With some fix in the hash computation in 0.16.

Will close it, please re-open if necessary.
