### ISSUE TITLE
[suggestion] `conan config install` automatic update

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#5721]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi there,

We are trying to roll out Conan for lots of developers.
For several reasons, we want to keep everyone's Conan configuration up-to-date.

We usually call `conan config install <github URL>` to have people update the configs.
However, if people don't do this regularly -  they can be out-of-date.
Also we are adding a custom sub-`setting` for `compiler` that will be updated potentially every could of weeks.
This means we want people running the latest, so they can match the compiler settings.

A suggestion would be to have `conan` automatically check if it's config is out of date.
Or maybe even points to a `conan package` of a config, and we can use version ranges to grab the latest.

Or would there be a simple way to do this now?

Also might be worth having a mechanism for disabling updating - or handling an offline workflow where you may not be able to grab it.

Thanks!

**Comment by Minimonium** [comment]
I wonder would it be possible to plug in with a [hook](https://docs.conan.io/en/latest/extending/hooks.html) to auto-update config (or at least check for latest?).

**Comment by memsharded** [comment]
Hooks right now are oriented to pre-post recipe actions, and this would apply mostly to whole commands.

We haven't added this functionality so far, for some reasons:

- There is no mechanism yet for processing updates. Everything is a processed a new install, copying files around, etc., which is highly inefficient. First a mechanism to know that there are remote changes should be deployed.
- Then, what would be the frequency? Should it check the remote every command? Every hour? If there are many developers eventually some will hit the issue of having an outdated configuration anyway.

Having them in a package makes it a chicken-and-egg problem, or if it is not a dependency, it would be still necessary to fire the install anyway. So this approach doesn't seem to solve the issue.

I think this could be more difficult that it seems at first sight, we can discuss about it, but I'd say this will take time. Any ideas or suggestions welcome.

**Comment by memsharded** [comment]
This was also commented here: https://github.com/conan-io/conan/issues/5669

**Comment by Mark-Hatch-Bose** [comment]
> There is no mechanism yet for processing updates. Everything is a processed a new install, copying files around, etc., which is highly inefficient. First a mechanism to know that there are remote changes should be deployed.

Could maybe do a quick check if the git hash has changed since the last one you got? If you can't access the repo, print a warning and move on?

>Then, what would be the frequency? Should it check the remote every command? Every hour? If there are many developers eventually some will hit the issue of having an outdated configuration anyway.

I think if we had a mechanism like I suggested above, run on each `conan install` or `conan create` that'd probably be a decent solution for the short term. Probably could make it more complex with configuration, but a short term solution would be nice.

**Comment by memsharded** [comment]
``conan config install`` had automatic updates in Conan 1.X, with a periodic configuration, and "passive" (required conan execution). It has been removed in Conan 2.0, it was too problematic. And also still something that didn't feel to really belong to Conan, but the general provisoning/IT/setup/tooling. It is not expected to add this to Conan 2.0 at the moment, and explicit ``conan config install`` by developers or CI would be necessary, I am closing this as not planned
