### ISSUE TITLE
Options from a lockfile are not displayed when building via `conan create`

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#5728]
If I build a package via `conan create --lockfile` the configuration displayed:

```
Configuration:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=5.0
os=Linux
[options]
[build_requires]
[env]
CC=...
```

does not match what is captured in the lockfile. In my case, options are captured in the lockfile, but they are not displayed in the output. The options are in fact, applied, so this is just a display error.

---

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @sztomi !

I have tried to reproduce this issue, but so far it seems it works ok. I am seeing options there:

```
client2.run("create . PkgD/0.1@user/channel --lockfile")
...
[settings]
[options]
PkgD:myoption=2
[build_requires]
[env]
```

Could you please check again, just in case? And if confirmed, any further hint to reproduce it? Thanks!

**Comment by memsharded** [comment]
Lockfiles in 2.0 shouldn't have this issue, closing
