### ISSUE TITLE
Store checksum of downloaded (and uploaded) packages

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5734]
Store in the ``metadata.json`` the checksum of the files actually downloaded or uploaded to the servers. We need this data to generate the _build information_ without querying the server again. For Artifactory, the required properties would be ``actual_md5`` and ``actual_sha1``.

**Comment by lasote** [comment]
Consider that the `metadata.yml` might not be the best place to introduce that, review the infrastructure, maybe this is not part of the metadata model but something more related to the downloads cache?
