### ISSUE TITLE
Latest version of Conan not available from website/Bintray

### ISSUE THREAD

**Issue by madduci** [conan-io/conan#5741]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Version: 1.18.3 and 1.18.4
OS: Windows, Linux
Description: The deb and exe installers links are broken on the website, because the packages are not uploaded on Bintray
Steps to reproduce the issue: Go to [conan download page](https://conan.io/downloads.html) and try to download the installer for Windows or Ubuntu. The link is broken

**Comment by uilianries** [comment]
Indeed both are absent there.

**Comment by lasote** [comment]
Fixed!!! Sorry and thanks for opening the issue
