### ISSUE TITLE
Creating locks while ignoring dependencies that raise ConanInvalidConfiguration

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#5742]
I'm working on locking a `conanfile.txt` in the following way:

Input:
```
[requires]
CompA/LATEST@user/channel
CompB/LATEST@user/channel
CompC/LATEST@user/channel #this ref raises ConanInvalidConfiguration on some profiles
```

I perform the following steps:
1. Resolve any aliases
2. Check if the ref is buildable with my current profile (Checking for returncode 6, `ConanInvalidConfiguration`)
3. Find all indirect dependencies for the remaining refs

The result looks like the following:
```
[requires]
### Direct deps:
CompA/1.0.0@user/channel
CompB/2.5.0@user/channel
# CompC/1.2.0@user/channel #not compatible with profile VS2015_Release

### Indirect deps:
CompZ/2.1.0@user/channel
CompX/13.0.0@user/channel
```

To do this right now I parse the input file and check for all references that I find. For each reference I do the following:
1. Resolve the alias by using `conan inspect ... -a alias ...`
2. Find indirect dependencies and check for ConanInvalidConfiguration using `conan info ...`
3. In the end gather all direct and indirect refs and sort them to write the output file

For now this is a very slow process. I need to do this for every single reference. `conan inspect` works faster than expected, but `conan info` creates the entire dep graph and usually takes a few seconds. With a few hundred references in the input files and ~3 seconds per ref the whole process takes a few dozen minutes.

My question would be if there's a way to accelerate this.
* `conan graph` for the whole `conanfile.txt` could be used, but it'd need a new parameter to ignore any refs that are raising `ConanInvalidConfiguration`. Something like `conan graph --skip-invalid-configuration`
* Perhaps something like that could be done server-sided? Reducing the number of calls between client and server.
* I have limited experience with `conan graph`. Is something like that already possible with some parameters/workflow I don't know about?
* Any other ideas?

**Comment by jgsogo** [comment]
Hi, @monsdar. Right now there is nothing you can do to avoid the ConanInvalidConfiguration exception 😞  Can you tell us what are you trying to achieve with the final ``conanfile.txt`` file? Maybe we can approach the problem in a different way.

Thanks!

**Comment by memsharded** [comment]
Closing as inactive and outdated
