### ISSUE TITLE
Please rename range-v3 package

### ISSUE THREAD

**Issue by ericniebler** [conan-io/conan#575]
I see from https://conan.io/source/range-v3/0.0.0-1/lasote/vcpkg that range-v3 is pointing to Microsoft/vcpkg, which itself is pointing to Microsoft/Range-v3-2015, instead of ericniebler/range-v3. That means when people take a dependence on "range-v3" from Conan, they are getting a horribly out-of-date, patched version of range-v3 maintained by Microsoft, and not the up-to-date version maintained by me.

Please do two things:
1. Rename the existing range-v3 to Range-v3-VS2015
2. (Optional) Add a range-v3 package that points to github.com/ericniebler/range-v3

**Comment by memsharded** [comment]
Hi Eric!

Thanks for your feedback. With regards to that package, it is a special package we automatically created from the new MSFT tool called Vcpkg so called "port" files, which are cmake scripts. We do nothing but load the Vcpkg ports and convert them automatically to conan packages, creating some binaries for different VS versions. You can read more about it here (will be the next blog post): https://github.com/conan-io/conan-io.github.io/blob/develop/_posts/2016-10-17-Using-Vcpkg-ports-as-Conan-packages.markdown

There are two options:
- Do a PR to Microsoft Vcpkg repo to fix and update the port file
- Create ourselves a conan recipe for the latest stable ranges library. If it is a header-only (it was last time I checked it), it should be a matter of minutes.

**Comment by ericniebler** [comment]
@memsharded Thanks for the speedy response. range-v3 is indeed header-only. If there's anything that needs to be done on my end to play well with Conan, I would be happy to accept a pull request, or a recipe to follow.

**Comment by memsharded** [comment]
Yes, I see there are no tags/releases in the github repo. For package management it is extremely useful to be able to refer to any specific version in time, using always latest from github is also possible, but for repeatibility using releases or tags is preferred. Do you have elsewhere some kind of releases, tarballs, tags? Thanks!

**Comment by ericniebler** [comment]
I haven't done official releases. I keep `master` stable. I can see why for a package manager, users would want to say *which* version of range-v3 they depend on without having to resort to SHA's or dates, but given my development work flow, every commit to `master` is a legit release. What is the best way to proceed in your opinion?

**Comment by ras0219-msft** [comment]
Timestamps work well as a versioning option (something like YYYYMMDDHHMM) if you want to keep things as simple as "the version is defined as when the code hits the master branch" on your side.

**Comment by memsharded** [comment]
I have created a package with version=master. Find the conan recipe here: https://github.com/memsharded/conan-range-v3. You can see the package recipe, for header_only is fairly simple: https://github.com/memsharded/conan-range-v3/blob/master/conanfile.py

It sets build_policy=always, so it will get the updated source code at every ``conan install``

The conan package can be found in conan.io as https://www.conan.io/source/rangev3/master/memsharded/testing

The main issue with this approach is the inability for dependent packages to track changes, when do they need to rebuild, etc. By default conan follows semver, it will rebuild a package if some of its dependencies upgrade its major version, otheerwise it assumes the binary keeps valid. This can be configured also in ``conan_info()`` recipe method. But for ``master`` version you should basically adopt the same policy for your downstream dependencies, and re-build them at every install.

**Comment by ericniebler** [comment]
Forgive me for not taking the time to learn Conan before bothering you. I guess I'm a little confused. Is the conanfile.py something that I would need to put in my range-v3 repo? If I wanted to add range-v3 to conan.io properly (where users could take a dependence on range-v3/XXX@ericniebler/YYY), what do I do? And what are XXX and YYY? Feel free to answer by pointing me to the appropriate resource. I'm sure it's all documented somewhere.

> The main issue with this approach is the inability for dependent packages to track changes, when do they need to rebuild, etc.

With range-v3, the right answer is: rebuild after every commit. There is no source or binary compatibility expressed or implied.

> But for `master` version you should basically adopt the same policy for your downstream dependencies, and re-build them at every install.

Who is "you"? Me? Range-v3? Some user of range-v3? What downstream dependencies?

**Comment by lasote** [comment]
Hi @ericniebler 

> I guess I'm a little confused. Is the conanfile.py something that I would need to put in my range-v3 repo? 
 
You can have it in your repo or in a different repo, it's your choice. You can read about it [here](http://docs.conan.io/en/latest/packaging.html) in the "Packaging from the source project" and in the "Packaging from external sources". In the first approach you export your sources to the package, and in the second you use the `source` method to retrieve your source code.

> If I wanted to add range-v3 to conan.io properly (where users could take a dependence on range-v3/XXX@ericniebler/YYY), what do I do? 

You need to create a conanfile.py (same docs section) and publish it to conan.io. If your range-v3 is header only it is very easy, you can generate a skeleton conanfile.py with `conan new  range-v3/XXX@ericniebler/YYY -i`` and then modify some parameters.

> And what are XXX and YYY? Feel free to answer by pointing me to the appropriate resource. I'm sure it's all documented somewhere.

The XXX is your library version, if you don't have it, well, I would recommend you to version it, but of course it is your choice. You can use "latest" or "master" as version.

The YYY is the channel, if you are pushing to "develop" with non-release changes you could publish a conan package `range-v3/latest@ericniebler/alpha` otherwise upload to `range-v3/latest@ericniebler/master` etc. 

The channel is intended to allow users to ease the replacement of a dependency, for example, changing from **zlib/1.2.8@lasote/testing** to **zlib/1.2.8@lasote/stable** do not affect to any configuration or the configured options to require zlib, because it's the same library, with different channel. The same way, the user namespace (lasote) allows to change a requirement to another user's, maybe a fork.

Hope it helps!

**Comment by memsharded** [comment]
> Who is "you"? Me? Range-v3? Some user of range-v3? What downstream dependencies?

I meant, any other package consuming range-v3, they should adopt the same policy of continuous re-building, as basically they do not use a fixed snapshot of range-v3. We usually call upstream to the dependencies a project or package depends on (including transitive dependencies), and downstream the packages or projects that depend on a given package (also transitively).

Regarding the versioning policy, I think that even if the master branch is stable regarding to quality, it might not be regarding to the API. In your case you clearly state that it is subject to breaking changes without regarding backwards compatibility. In that case, I find it very useful to tag minors versions (0.x), with 0 considered non-stable by semver (even tagging every release to master), for early adopters. I try to do so when such early adopters begin to use my code for something bigger than pet projects.
