### ISSUE TITLE
Conan API is missing 'get' command

### ISSUE THREAD

**Issue by sct2010** [conan-io/conan#5752]
Hi

I try to get the `conaninfo.txt` content trough the conan_api. There is no `get` function in the api. What is the correct function call or is this not implemented yet?

The corresponding command line command is:
`conan get zlib/1.2.11@conan/stable:2144f833c251030c3cfd61c4354ae0e38607a909`

conan version: 1.18.4
OS: Win10 64bit

**Comment by jgsogo** [comment]
Hi, @sct2010 

⚠️ **First of all a warning**: the `conan_api` is not public yet, we may change it without previous notice.

All the commands ``conan get ...`` enter through the ``get_path`` function. Probably that is what you are looking for.

**Comment by sct2010** [comment]
Hi @jgsogo 
Thanks for your fast response. I am aware of that the api is not stable and public. It is just for a test script.
The get_path is working fine for reading the `conaninfo.txt`.


If I am using it to get the `conan_export.tgz`, I can't read the zip file. This is my code section:
```
tgzStr = conan.get_path(Pkg, path='conan_export.tgz')[0]
file_like_object = io.BytesIO(tgzStr.encode())
tar = tarfile.open(fileobj=file_like_object, mode='r:gz')
```
The tgzStr starts with `\x1f\x08\x08\x00\x00\x00\x00\x02conan_export.tgz`. according to Wikipedia the file signature is `1F 8B`. Do you have an example to get a file from the tgz file?

**Comment by jgsogo** [comment]
That's not something I've tried before, it is quite uncommon to use the ``get`` command to retrieve binaries. Maybe if I understand better what you are trying to test I can help you better.

Thanks

**Comment by sct2010** [comment]
In our CI pipeline a changelog file is created and packed into the conan package with `exports = "changelog.json"`. Later on, I am collection the changelog files from different packages and concatenating them to upload to a deployment server.

Thats the reason why i have to get the binary file.
The changelog.json exporting is not fixed. I am open for some other solution.

**Comment by jgsogo** [comment]
Oh! That's interesting. Let me link this issue with one related to [quality artifacts](https://github.com/conan-io/conan/issues/4694), people could find both of them together useful.

As you have your changelog files already packaged you can use the [deploy generator](https://docs.conan.io/en/latest/reference/generators/deploy.html) to retrieve all the binaries from your graph: 

```
conan install <your-app-reference> -g deploy --install-folder tmp-folder
```

All your ``changelog.json`` files should be there, organized per package, now you need a simpler script to harvest them all and build a unique ``changelog``. Would it work for you?

**Comment by sct2010** [comment]
The changelog.json contains only the incremental change. For example only the change between `pkg/1.0.0-alpha1` and `pkg/1.0.0-alpha2` is stored in the `pkg/1.0.0-alpha2`. To get the complete end-user changelog of `pkg/1.0.0`, I have to collect them from more then one conan package (pkg/1.0.0-alpha1 ... pkg/1.0.0-beta1 ... pkg/1.0.0).

Your approach could be a solution, but I have to adjust the changelog generation and move the logic '_what will be included in the release_' into the conan package creation.

**Comment by jgsogo** [comment]
Hi, did you manage to find a way to collect all the changelogs? Is there anything we should take care about?

**Comment by sct2010** [comment]
Hi @jgsogo 
As I described above, I need do collect changelogs from different versions of a package. Therefore 
`conan install <your-app-reference> -g deploy --install-folder tmp-folder` is not an option for me. Since the `get_path` is not working for binary files, I have to download the package into the local chache and get the extracted file. To do so, I am using a 

```
conan.download('conan get pkg/v1@channel', remote_name='remote', recipe=True)
changelog = conan.get_path('conan get pkg/v1@channel', path='changelog.json')
```

It would be great if the API call `get_path` would also work correctly for binary files. To download the whole package takes a while.

**Comment by jgsogo** [comment]
With the ``deploy`` generator all those packages are downloaded and extracted into the ``installfolder``, you should be able to find your changelog file in your local drive, at ``<installfolder>/pkg/.../changelog.json``.

A different issue is to get all the micro-changelogs of the prereleases into one changelog file, and another different issue is to get a file inside a package using ``conan get`` (this is more a feature request that will require some changes in the command line).

**Comment by sct2010** [comment]
Let me describe my aproach a bit more in detail:

Lets start with a simple project with the following structure:
```
App
 - LibA
 - LibB
```
In the example I want to generate the changelog of App/V2.0.0.
```
Current release:         Last release:
App / V2.0.0              App / V1.3.0
 - LibA / V3.2.1           - LibA / V3.2.0
 - LibB / V5.0.0           - LibB / V4.8.0
```
The script executes the following:
1. get the id of App / V2.0.0
2. get the conaninfo.txt
3. extract the `full_requires` list
4. do step 1-3 for App / V1.3.0
5. iterate over all pkgs (App, LibA and LibB)
  5.1 get a list of all App versions  (V1.0.0 ... V1.3.0 ... V2.0.0-alpha1 ... V2.0.0) 
  5.2 iterate over all versions
  5.3 if version > V1.3.0 and <= V1.2.0 extract changelog.json and append it to a list

With the deploy generator I get only all pkg of the two dependency trees, but will miss all the steps between. Even if I am getting all the trees for all the App versions between, it isn't guaranteed, that I catch all the changes in the libA and libB. Therefore, the deploy approach is nothing I would consider.

In my script everything works so far apart from to get the changelog.json I have to download the package and get the file from the local cache. My initial thought was to get the `conan_export.tgz` directly without to download the whole package to my local conan cache and get it from there.

To get the script running, I have only one bugfix request:
make the `get_path` work with binary files, so I can directly get the `conan_export.tgz`  instead of downloading the package to the local cache. 


This feature request would be perfect, but is in my opinion nice to have:
> another different issue is to get a file inside a package using conan get (this is more a feature request that will require some changes in the command line).


I have already a solution for:
> A different issue is to get all the micro-changelogs of the prereleases into one changelog file

I think we should open a new issue to fix the `get_path` for binary files and close this one as answerd. Should we also open an issue to implement the _get a file inside a package_?
What do you think?

**Comment by jgsogo** [comment]
Yes, please, a new issue will be better. If you feel like we can help you with the _workaround_ for the Conan current version (1.18.x) keep this one open, otherwise we can close it.

Thanks!

**Comment by sct2010** [comment]
Tanks for the support!
