### ISSUE TITLE
Deploy only requirements and not build_requirements

### ISSUE THREAD

**Issue by ngrodzitski** [conan-io/conan#5753]
Is it possible to run deploy ( -g deploy) command so that it will gather only libs mentioned in requirements and not in build_requirements?

What I'm trying to do is to provide my library to another team which doesn't use conan and so we agreed on a include-lib-bin structured directory with all the stuff so that it would be possible to setup necessary paths and libs in Visual Studio project and it would just work. I want to use deploy command to get all publicly necessary 3rd-parties for my lib, But currently I get all the dependencies. It is not a big deal to script the things and exclude non-publicly required libs, but it is bad for further maintenance as I might add more deps (either requirements or build_requirements) and would have to change the script accordingly each time. 

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.

Conan version 1.18.4
Windows.

**Comment by jgsogo** [comment]
Hi!

The deploy generator (``conan install <app> -g deploy``) should retrieve only the files corresponding to the ``requirements`` (not build_requirements). It will also generate the structure with the include-lib-bin folders. 

So, is the issue that it will retrieve _private_ ``requirements`` too?

BTW, we are working on a plugin for Visual Studio, it is under development, but it would allow to integrate transparently a VS project consuming Conan dependencies. There is still a lot of work ahead, but any feedback would be appreciated ([repo](https://github.com/conan-io/conan-vs-extension), [marketplace](https://marketplace.visualstudio.com/items?itemName=conan-io.conan-vs-extension))

**Comment by ngrodzitski** [comment]
> The deploy generator (conan install <app> -g deploy) should retrieve only the files corresponding to the requirements (not build_requirements). It will also generate the structure with the include-lib-bin folders.

Is this statement about current behavior Conan has? Because, I observe another behavior. Having this file:
```python
from conans import ConanFile, CMake, tools

class MyLib(ConanFile):
    name = "MyLib"
    version = "1.0.0"
    topics = ("repro", "deploy")
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake", "cmake_paths"
    build_policy = "missing"

    def requirements(self):
        self.requires.add("fmt/5.3.0@bincrafters/stable")

    def build_requirements(self):
        self.build_requires("gtest/1.8.1@bincrafters/stable")
```

And running `conan install -g deploy --install-folder ./3rd-party .` I get gtest  in "3rd-party" directory. And the thing I would like to have is an option to install only libs (and its transitives) listed in `requirements` and not in `build_requirements`.

**Comment by jgsogo** [comment]
Hi, @ngrodzitski. Oh! I see

When you run ``conan install ... <path>`` the package in ``<path>`` is not retrieved from the cache and it is considered to be built. If you use ``conan install ... MyLib/1.0.0`` instead, the package will be retrieved from the cache and Conan won't expand the ``build_requires`` (if binaries are available). And the **``deploy`` generator dumps all the libraries en the graph**, so in the first scenario it will dump the build requires too, while in the second it won't.:

```bash
conan create . [--profile]  # if you haven't generated it yet
conan install <reference> -g deploy
```

Let me know if this works for you. Thanks!

**Comment by ngrodzitski** [comment]
That looks reasonable. It would be nice to get only public deps even in such scenario.
On CI the target project is built with CMake passing various flags (several sets of those) and then CTest is performed and etc. So will need to revise the process for using Conan controlled build.

**Comment by jgsogo** [comment]
memsharded is working on improving the graph model, the current model lends itself to some confusion between requires-private, requires and build_requires... and there are some packages that doesn't fit well like cross-compilers, test-libraries,... once the projects get complex and bigger, a lot of unexpected use-cases arise, but we are here to improve the ecosystem every day.

Thanks for your feedback
