### ISSUE TITLE
ConfigureEnvironment not working on Windows with gcc

### ISSUE THREAD

**Issue by osechet** [conan-io/conan#576]
ConfigureEnvironment is not working on Windows when using gcc. Calling env.command_line gives the following error:
```
local variable 'command' referenced before assignment
```
Checking the code, it looks like the class has been changed recently ([Oct 13th](https://github.com/conan-io/conan/commit/14dcc1f83cf2dfd1033a3f32305380ab2124522f)) and the test for gcc on Windows has been removed.

**Comment by lasote** [comment]
I confirm the error: https://ci.appveyor.com/project/lasote/conan-zlib/build/1.0.60/job/dpmi0ibean1ynmts

**Comment by memsharded** [comment]
I am going to fix it and include it in the release (hopefully today). In any case, I strongly suggest moving to the new ``env.command_line_env`` which solved many of the issues that ``env.command_line`` had. Thanks for reporting.

**Comment by memsharded** [comment]
Hi @osechet, this has been fixed and merged in #577, will be released in next conan 0.14. We have added some more tests too, and tested with some packages, but if you tell me which package was failing in your case, I could check it too. Thanks!

**Comment by osechet** [comment]
Hi @memsharded, I was trying to port https://github.com/Vitallium/conan-icu to mingw and I also got the error with `mingw_installer` and `cmake_installer` when testing what is said on this [doc page](http://conanio.readthedocs.io/en/latest/howtos/create_installer_packages.html).

**Comment by memsharded** [comment]
I have tested both mingw and cmake installers, now they seem to work fine. Tried the conan-icu recipe, but still using VS, so couldn't really try it. I changed to use the ``build_with_configure``, but it obviously failed (in the build, no chmod, but didn't crash inside ``ConfigureEnvironment`` due to that bug)
