### ISSUE TITLE
Working with python_semantic_release

### ISSUE THREAD

**Issue by orshefi** [conan-io/conan#5769]
Hi guys,

Wanted to consult with you on a matter, I am currently trying to start working with semantic release with conan.

For whom of you that aren't familiar with the project, semantic release uses git commit format in order to decide for the developer what is the proper version bump : 
[https://github.com/semantic-release/npm](https://github.com/semantic-release/npm)

There is also the python wrapper that allows usage for python application with semantic release: 
[https://github.com/relekang/python-semantic-release](https://github.com/relekang/python-semantic-release)

There is a conflict with installing both conan and semantic release, the package I believe thats in conflict is semver (python semantic release dep) and node-semver (conan dep)

Any Idea on what should I do to solve this issue?

**Comment by jgsogo** [comment]
Hi, can you copy/paste here the error and which python version you are using?

I've just installed both of them and I get no conflicts (Macos + python 3.7.4):

```
⇒  pip freeze
asn1crypto==0.24.0
astroid==2.2.5
bleach==3.1.0
bottle==0.12.17
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
colorama==0.4.1
conan==1.18.4
cryptography==2.3.1
deprecation==2.0.7
distro==1.1.0
docutils==0.15.2
fasteners==0.15
future==0.16.0
gitdb2==2.0.5
GitPython==2.1.14
idna==2.6
invoke==0.11.1
isort==4.3.21
Jinja2==2.10.1
lazy-object-proxy==1.4.2
MarkupSafe==1.1.1
mccabe==0.6.1
monotonic==1.5
ndebug==0.1.0
node-semver==0.6.1
packaging==19.2
patch==1.16
pkginfo==1.5.0.1
pluginbase==0.7
pycparser==2.19
Pygments==2.4.2
PyJWT==1.7.1
pylint==2.3.1
pyOpenSSL==18.0.0
pyparsing==2.4.2
python-dateutil==2.8.0
python-gitlab==1.10.0
python-semantic-release==4.3.0
PyYAML==5.1.2
readme-renderer==24.0
requests==2.22.0
requests-toolbelt==0.9.1
semver==2.8.1
six==1.12.0
smmap2==2.0.5
toml==0.10.0
tqdm==4.36.1
twine==1.15.0
typed-ast==1.4.0
urllib3==1.25.3
webencodings==0.5.1
wrapt==1.11.2
```

Thanks

**Comment by orshefi** [comment]
Hi, 

The conflict is not in the installation, I'll elaborate a bit more.

I'm working with python 3.6.8, there are two packages of interest that I narrowed down to result in the issue.

The first is node-semver that installed when installing conan, this one gets installed in /usr/local/lib/python3.5/dist-package/semver/__init__.py

After conan installation when running `import semver` from python3 the __path__ of the imported package is /usr/local/lib/python3.5/dist-package/semver/__init__.py

The later package needed by python_semantic_release is semver, it gets insatlled in /usr/local/lib/python3.5/dist-package/semver.py

After installation when running `import semver` from python3 the __path__ of the imported package is still the path to node-semver, which obviously does not contain the required attributes needed by python_semantic_release to operate.

When uninstalling node-semver the semver package required by python_semantic_release gets imported properly.

Any Ideas?

**Comment by jgsogo** [comment]
I see. Those are two different packages:
 * Conan requires https://pypi.org/project/node-semver/
 * ``python_semantic_release`` requires https://pypi.org/project/semver/

I'm not aware of anything that can be done to fix this conflict other than using a different virtualenv for each application. Otherwise, one of us should change the requirement or vendor the dependency. Can you install each application in a different virtualenv? Do you have any feedback from Python-Semantic-Release team?

**Comment by memsharded** [comment]
node-semver removed in 2.0, this shouldn't be an issue anymore
