### ISSUE TITLE
settings.arch armv5te support

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#5773]
Please add support/allow armv5te as an architecture option.

Thanks

**Comment by danimtb** [comment]
Could you please provide us with more information about this architecture? Is this a convention name?

**Comment by radonish** [comment]
Hello @danimtb - sorry for the delayed response. Thank you for moving it to the correct place. The armv5te name references a microarchitecture used by a group of ARM9 processor cores. I'm specifically using it with the Atmel AT91SAM9G45 microprocessor (https://www.microchip.com/wwwproducts/en/AT91sam9g45). The armv5te name was also used as the "architecture" naming convention by the Embedded Linux Development Kit (ELDK).

**Comment by danimtb** [comment]
Thanks for the information. I see it is a pretty standard option.

I would like to know what is the difference with armv5el and armv5hf as I am not an expert on the area.

Additionally and apart from adding that to the settings.yml, did you have to do any other modification to Conan? Any additional flags in recipes for this armv5te? Thanks

**Comment by danimtb** [comment]
@radonish any advice for the above questions?

**Comment by AbrilRBS** [comment]
Closing as stale. Note that in Conan 2, users can add their custom settings to [`settings_user.yml`](https://docs.conan.io/2/examples/config_files/settings/settings_user.html#examples-config-files-settings-user) - if the Conan integrations need to learn about extra flags for specific configurations, we'll be happy to review :)
