### ISSUE TITLE
Symbolic links cause trouble on Windows (and AppVeyor)

### ISSUE THREAD

**Issue by reneme** [conan-io/conan#5774]
When trying to fix the build of [bincrafters/conan-depot_tools_installer](https://github.com/bincrafters/conan-depot_tools_installer) we found that conan (or Python itself) cannot deal with symlinks on Windows 10. We found [a workaround](https://github.com/bincrafters/conan-depot_tools_installer/pull/4) that simply copies the symlinked files in-lieu of the symlinks. This might be something worth "fixing" in conan itself, though.

This bug ticket in bincrafters/community should provide enough details to reproduce the problem: https://github.com/bincrafters/community/issues/943

Conan version: 1.18.4
Windows version: 10 - 1904
Python version: 3.7.4

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by czoido** [comment]
Hi @reneme,
I'm not currently under Windows, but I'll try to reproduce the issue as soon as I am.
Thanks a lot for the feedback! :)

**Comment by czoido** [comment]
I think we can consider this closed, https://github.com/conan-io/conan-center-index/tree/master/recipes/depot_tools is already in Conan Center Index and working without issues and Conan 2.0 also has a new set of tools to manipulate symlinks: https://docs.conan.io/2.0/reference/tools/files/symlinks.html 
Also check: https://docs.conan.io/2.0/tutorial/creating_packages/package_method.html#managing-symlinks-in-the-package-method
