### ISSUE TITLE
system_requirements not reliable for ":all" and native-arch packages (using APT).

### ISSUE THREAD

**Issue by MichalMaruska-TomTom** [conan-io/conan#5776]
I work on amd64 system (Debian SID), and I verified the issue on 1.18.4.

Let's assume I need the following system packages for my conan package:
    x11proto-xf86dga-dev and libxinerama-dev.

So for start let's remove them on my system:
sudo apt remove x11proto-xf86dga-dev libxinerama-dev libxinerama-dev:i386

So I have code in my conanfile.py  like this:
        packages = ["libxinerama-dev",                 "x11proto-xf86dga-dev"]
        installer = SystemPackageTool(conanfile=self)
        for pack_name in packages:
            installer.install(pack_name)

now if I try to build, let's say first for an i386 profile  "-p linux_x86", then 
libxinerama-dev:i386 will be installed, but then installation of
"x11proto-xf86dga-dev:i386" will fail, since it does not exist, there is only 
x11proto-xf86dga-dev:all.

(2nd issue:)
Let's forget about that "x11proto-xf86dga-dev", and proceed to building for my native architecture, the default profile.
That will fail, because libxinerama-dev:amd64 is not installed: -- 
Conan tries to avoid asking to install an already installed package, and the query used by conan:
  dpkg-query -W -f='${Status}' libxinerama-dev  | grep -q installed
will report true, because the pattern matches "libxinerama-dev:i386" installed package.

**Comment by mmaruska** [comment]
a possible fix  https://github.com/conan-io/conan/pull/5782

**Comment by czoido** [comment]
Hi @mmaruska,

While we have a look at it maybe you could use this workaround for the installation of the `:all` package issue:

```
    def system_requirements(self):
        installer = SystemPackageTool(conanfile=self)
        installer.install("libtool-bin")
        self.run("sudo apt-get install x11proto-xf86dga-dev:all -y")	
```
Thanks a lot for the feedback! :)

**Comment by memsharded** [comment]
this integration was replaced by a new on in ``from conan.tools.system`` some time ago in 1.X, and removed in 2.0, closing this as outdated.
