### ISSUE TITLE
Proper error message using conan remote disable/enable if remote doesn't exist

### ISSUE THREAD

**Issue by czoido** [conan-io/conan#5778]
Using Conan 1.19 you will be able to enable or disable remotes with `conan remote enable/disable remote_name`. If the remote does not exist there is no error message. There should be one error message in this case.

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Minimonium** [comment]
Should there also be an error on enabling remotes that are already enabled?

**Comment by memsharded** [comment]
> Should there also be an error on enabling remotes that are already enabled?

Probably just a warning? The final result will be that the remote is enabled, that is what the user wants with the command.

**Comment by Minimonium** [comment]
It's kinda wacky to put a warning because it needs to behave differently depending on the wildcard case and not. I'm not sure, how much do we want a warning here? 😃

**Comment by memsharded** [comment]
> It's kinda wacky to put a warning because it needs to behave differently depending on the wildcard case and not. I'm not sure, how much do we want a warning here?

Yes, that is true. But that would apply for ``conan remote enable *`` too to throw an error message. What about just displaying a summary of what has been done:

```
$ conan remote enable *
Remote "xxxxx" enabled
Remote "yyyyy" enabled

or 
$ conan remote enable *
No remote was enabled
```

**Comment by Minimonium** [comment]
Note that in the current implementation the wildcard case does not throw an error if nothing was picked. 🙂 

About the output, the `Remote` class doesn't have the `output` as an attribute. Is the right approach to pass it down as a function parameter? Wouldn't it be too much? Or returning an output? Again, a bit wacky.
