### ISSUE TITLE
Promotion of big packages results on corruption in Artifactory

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#5779]
From https://github.com/conan-io/conan/issues/2415#issuecomment-532586662

From @GordonJess:

> I have moved some packages to another channel using the Artifactory UI, but the client cannot resolve them:
> 
> ```
> PS C:\my_repo> conan search -r my-repo
> Existing package recipes:
> 
> my-dependency/1.0.0@user/channel
> my-dependency/1.0.0@user/new_channel
> 
> PS C:\my_repo> conan create . user/channel
> ERROR: Error loading conanfile at 'C:\my_repo\conanfile.py': Version range '~=1.0.0' from requirement 'my-dependency/[~=1.0.0]@user/new_channel' required by 'python_require' could not be resolved
> ```
> 
> It works fine if I do `conan copy` and upload again.

> During the copy I did get error messages for some of the larger packages, about the timeout of a file lock or something (sorry I don't have a screenshot on hand). The packages looked ok after, but maybe something got corrupt..!

------------

I tested myself with small packages but it worked fine using the Artifactory UI as the user reported. We will have to test with bigger packages.

**Comment by danimtb** [comment]
@GordonJess could you specify more ore less the size of the packages or the number of files? Something similar to boost or opencv?

**Comment by lasote** [comment]
We have experienced that error also. It is reported and prioritized in the Artifactory side.

**Comment by danimtb** [comment]
Thanks @lasote.

I think the related issues are the following:
- https://www.jfrog.com/jira/browse/RTFACT-20086
- https://www.jfrog.com/jira/browse/RTFACT-19586

**Comment by memsharded** [comment]
Closing as outdated, no longer seem an issue.
