### ISSUE TITLE
Conan requesting conan-center credentials for downloading package

### ISSUE THREAD

**Issue by ruipires** [conan-io/conan#5784]
I seem to be experiencing the same issue as #3046 

OS: Debian 9
Python: 3.5.3
Conan: 1.18.4

**conanfile.txt**

    [requires]
    cpprestsdk/2.10.14@bincrafters/stable
    spdlog/1.3.1@bincrafters/stable
    fmt/5.3.0@bincrafters/stable
    Catch2/2.9.2@catchorg/stable
    
    [generators]
    cmake

**Remotes:**

    conan remote list
    conan-center: https://conan.bintray.com [Verify SSL: True]
    bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]

Running conan install results in:

    > conan install ..
    Configuration:
    [settings]
    arch=x86_64
    arch_build=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++11
    compiler.version=6
    os=Linux
    os_build=Linux
    [options]
    [build_requires]
    [env]
    
    cpprestsdk/2.10.14@bincrafters/stable: Not found in local cache, looking in remotes...
    cpprestsdk/2.10.14@bincrafters/stable: Trying with 'conan-center'...
    cpprestsdk/2.10.14@bincrafters/stable: Trying with 'bincrafters'...
    Downloading conanmanifest.txt: 100%|##########| 166/166 [00:00<00:00, 10.6kB/s]
    Downloading conanfile.py: 100%|##########| 9.57k/9.57k [00:00<00:00, 7.23MB/s]
    Downloading conan_export.tgz: 100%|##########| 761/761 [00:00<00:00, 939kB/s]
    Decompressing conan_export.tgz: 2.23kB [00:00, 420kB/s]
    cpprestsdk/2.10.14@bincrafters/stable: Downloaded recipe revision 0
    OpenSSL/1.1.1c@conan/stable: Not found in local cache, looking in remotes...
    OpenSSL/1.1.1c@conan/stable: Trying with 'conan-center'...
    Downloading conanmanifest.txt: 100%|##########| 58.0/58.0 [00:00<00:00, 21.5kB/s]
    Downloading conanfile.py: 100%|##########| 28.7k/28.7k [00:00<00:00, 975kB/s]
    OpenSSL/1.1.1c@conan/stable: Downloaded recipe revision 0
    zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
    zlib/1.2.11@conan/stable: Trying with 'conan-center'...
    Downloading conanmanifest.txt: 100%|##########| 296/296 [00:00<00:00, 272kB/s]
    Downloading conanfile.py: 100%|##########| 8.74k/8.74k [00:00<00:00, 9.90MB/s]
    Downloading conan_export.tgz: 100%|##########| 766/766 [00:00<00:00, 953kB/s]
    Decompressing conan_export.tgz: 2.24kB [00:00, 990kB/s]
    zlib/1.2.11@conan/stable: Downloaded recipe revision 0
    websocketpp/0.8.1@bincrafters/stable: Not found in local cache, looking in remotes...
    websocketpp/0.8.1@bincrafters/stable: Trying with 'conan-center'...
    websocketpp/0.8.1@bincrafters/stable: Trying with 'bincrafters'...
    Downloading conanmanifest.txt: 100%|##########| 121/121 [00:00<00:00, 84.9kB/s]
    Downloading conanfile.py: 100%|##########| 2.36k/2.36k [00:00<00:00, 2.74MB/s]
    websocketpp/0.8.1@bincrafters/stable: Downloaded recipe revision 0
    boost/1.69.0@conan/stable: Not found in local cache, looking in remotes...
    boost/1.69.0@conan/stable: Trying with 'conan-center'...
    Downloading conanmanifest.txt: 100%|##########| 303/303 [00:00<00:00, 219kB/s]
    Downloading conanfile.py: 100%|##########| 37.3k/37.3k [00:00<00:00, 24.2MB/s]
    boost/1.69.0@conan/stable: Downloaded recipe revision 0
    boost/1.69.0@conan/stable: WARN: Setting 'cppstd' is deprecated in favor of 'compiler.cppstd', please update your recipe.
    bzip2/1.0.6@conan/stable: Not found in local cache, looking in remotes...
    bzip2/1.0.6@conan/stable: Trying with 'conan-center'...
    Downloading conanmanifest.txt: 100%|##########| 163/163 [00:00<00:00, 136kB/s]
    Downloading conanfile.py: 100%|##########| 2.21k/2.21k [00:00<00:00, 2.12MB/s]
    Downloading conan_export.tgz: 100%|##########| 766/766 [00:00<00:00, 992kB/s]
    Decompressing conan_export.tgz: 2.24kB [00:00, 1.18MB/s]
    bzip2/1.0.6@conan/stable: Downloaded recipe revision 0
    spdlog/1.3.1@bincrafters/stable: Not found in local cache, looking in remotes...
    spdlog/1.3.1@bincrafters/stable: Trying with 'conan-center'...
    Downloading conanmanifest.txt: 100%|##########| 166/166 [00:00<00:00, 201kB/s]
    Downloading conanfile.py: 100%|##########| 1.93k/1.93k [00:00<00:00, 2.11MB/s]
    Downloading conan_export.tgz: 100%|##########| 764/764 [00:00<00:00, 935kB/s]
    Decompressing conan_export.tgz: 2.24kB [00:00, 1.02MB/s]
    spdlog/1.3.1@bincrafters/stable: Downloaded recipe revision 0
    fmt/5.3.0@bincrafters/stable: Not found in local cache, looking in remotes...
    fmt/5.3.0@bincrafters/stable: Trying with 'conan-center'...
    Downloading conanmanifest.txt: 100%|##########| 166/166 [00:00<00:00, 164kB/s]
    Downloading conanfile.py: 100%|##########| 2.99k/2.99k [00:00<00:00, 1.43MB/s]
    Downloading conan_export.tgz: 100%|##########| 758/758 [00:00<00:00, 986kB/s]
    Decompressing conan_export.tgz: 2.22kB [00:00, 937kB/s]
    fmt/5.3.0@bincrafters/stable: Downloaded recipe revision 0
    Catch2/2.9.2@catchorg/stable: Not found in local cache, looking in remotes...
    Catch2/2.9.2@catchorg/stable: Trying with 'conan-center'...
    Downloading conanmanifest.txt: 100%|##########| 1.36k/1.36k [00:00<00:00, 105kB/s]
    Downloading conanfile.py: 100%|##########| 909/909 [00:00<00:00, 688kB/s]
    Downloading conan_export.tgz: 100%|##########| 891/891 [00:00<00:00, 746kB/s]
    Decompressing conan_export.tgz: 2.61kB [00:00, 154kB/s]
    Catch2/2.9.2@catchorg/stable: Downloaded recipe revision 0
    conanfile.txt: Installing package
    Requirements
        Catch2/2.9.2@catchorg/stable from 'conan-center' - Downloaded
        OpenSSL/1.1.1c@conan/stable from 'conan-center' - Downloaded
        boost/1.69.0@conan/stable from 'conan-center' - Downloaded
        bzip2/1.0.6@conan/stable from 'conan-center' - Downloaded
        cpprestsdk/2.10.14@bincrafters/stable from 'bincrafters' - Downloaded
        fmt/5.3.0@bincrafters/stable from 'conan-center' - Downloaded
        spdlog/1.3.1@bincrafters/stable from 'conan-center' - Downloaded
        websocketpp/0.8.1@bincrafters/stable from 'bincrafters' - Downloaded
        zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
    Packages
        Catch2/2.9.2@catchorg/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
        OpenSSL/1.1.1c@conan/stable:008f1a2b119556f550c1109663570e0f5040c13f - Download
        boost/1.69.0@conan/stable:16227604e1a14c8dcad4488915fe62fb570c8dd7 - Download
        bzip2/1.0.6@conan/stable:09e3a4c43285997784a5fcaefa367cb780af2032 - Download
        cpprestsdk/2.10.14@bincrafters/stable:906e5335b4b1221491fb35bd98e53195c6bb47be - Missing
        fmt/5.3.0@bincrafters/stable:d0ec62fc032e5a10524fa454546aa1bdbb22baf8 - Download
        spdlog/1.3.1@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
        websocketpp/0.8.1@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
        zlib/1.2.11@conan/stable:f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb - Download
    
    Catch2/2.9.2@catchorg/stable: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'conan-center'
    Downloading conanmanifest.txt: 100%|##########| 0.98k/0.98k [00:00<00:00, 828kB/s]
    Downloading conaninfo.txt: 100%|##########| 150/150 [00:00<00:00, 166kB/s]
    Downloading conan_package.tgz: 100%|##########| 127k/127k [00:00<00:00, 2.93MB/s]
    Decompressing conan_package.tgz: 143kB [00:00, 4.33MB/s]
    Catch2/2.9.2@catchorg/stable: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    Catch2/2.9.2@catchorg/stable: Downloaded package revision 0
    bzip2/1.0.6@conan/stable: Retrieving package 09e3a4c43285997784a5fcaefa367cb780af2032 from remote 'conan-center'
    Downloading conanmanifest.txt: 100%|##########| 395/395 [00:00<00:00, 445kB/s]
    Downloading conaninfo.txt: 100%|##########| 444/444 [00:00<00:00, 446kB/s]
    Downloading conan_package.tgz: 100%|##########| 98.1k/98.1k [00:00<00:00, 4.48MB/s]
    Decompressing conan_package.tgz: 114kB [00:00, 2.80MB/s]
    bzip2/1.0.6@conan/stable: Package installed 09e3a4c43285997784a5fcaefa367cb780af2032
    bzip2/1.0.6@conan/stable: Downloaded package revision 0
    fmt/5.3.0@bincrafters/stable: Retrieving package d0ec62fc032e5a10524fa454546aa1bdbb22baf8 from remote 'conan-center'
    Downloading conanmanifest.txt: 100%|##########| 1.07k/1.07k [00:00<00:00, 499kB/s]
    Downloading conaninfo.txt: 100%|##########| 525/525 [00:00<00:00, 218kB/s]
    Downloading conan_package.tgz: 100%|##########| 150k/150k [00:00<00:00, 4.69MB/s]
    Decompressing conan_package.tgz: 166kB [00:00, 1.75MB/s]
    fmt/5.3.0@bincrafters/stable: Package installed d0ec62fc032e5a10524fa454546aa1bdbb22baf8
    fmt/5.3.0@bincrafters/stable: Downloaded package revision 0
    zlib/1.2.11@conan/stable: Retrieving package f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb from remote 'conan-center'
    Downloading conanmanifest.txt: 100%|##########| 352/352 [00:00<00:00, 393kB/s]
    Downloading conaninfo.txt: 100%|##########| 428/428 [00:00<00:00, 506kB/s]
    Downloading conan_package.tgz: 100%|##########| 92.0k/92.0k [00:00<00:00, 26.4MB/s]
    Decompressing conan_package.tgz: 108kB [00:00, 14.5MB/s]
    zlib/1.2.11@conan/stable: Package installed f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb
    zlib/1.2.11@conan/stable: Downloaded package revision 0
    OpenSSL/1.1.1c@conan/stable: Retrieving package 008f1a2b119556f550c1109663570e0f5040c13f from remote 'conan-center'
    Downloading conanmanifest.txt: 100%|##########| 6.22k/6.22k [00:00<00:00, 3.71MB/s]
    Downloading conaninfo.txt: 100%|##########| 1.27k/1.27k [00:00<00:00, 1.22MB/s]
    Please log in to "conan-center" to perform this action. Execute "conan user" command.
    If you don't have an account sign up here: https://bintray.com/signup/oss
    Remote 'conan-center' username: ^CYou pressed Ctrl+C!
    OpenSSL/1.1.1c@conan/stable: ERROR: Exception while getting package: 008f1a2b119556f550c1109663570e0f5040c13f
    OpenSSL/1.1.1c@conan/stable: ERROR: Exception: <class 'SystemExit'> 3
    OpenSSL/1.1.1c@conan/stable: WARN: Trying to remove package folder: /home/thanos/.conan/data/OpenSSL/1.1.1c/conan/stable/package/008f1a2b119556f550c1109663570e0f5040c13f
    ERROR: Exiting with code: 3
    
    > conan --version
    Conan version 1.18.4

**Comment by lasote** [comment]
Same issue being investigated here: #5780

**Comment by danimtb** [comment]
Please @ruipires continue the conversation there so we don't duplicate the information. Thanks!
