### ISSUE TITLE
Add gcc 9.2 to default list of compilers

### ISSUE THREAD

**Issue by torfinnberset** [conan-io/conan#5787]
gcc 9.2 is released, so we can add it to the default list of compilers that conan recognizes. Checked vs. conan v1.18.2 on macOS 10.14.6

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by czoido** [comment]
Hi @torfinnberset  
Thanks a lot for telling!
