### ISSUE TITLE
Updating conan config files tends to cause breakages

### ISSUE THREAD

**Issue by drussel** [conan-io/conan#5788]
We get breakages when multiple versions of conan are used on the same system (eg in CI testing) and conan updates its config files. This most recently this appeared to occurred between 1.18.4 and 1.18.1.

It would be helpful if
- such changes were more clearly marked in the release notes (as they break rollbacks). I can't find docs of this one.
- they were kept to major releases as they are pretty disruptive
- effort was made to preserve compatibility with old versions (eg leave the old config files behind), add version numbers to config files that change or something

We use conan via a python virtual env so we can ensure that it is installed everywhere and has a consistent version and that is a version that works with the checked out version of our code. One result of this is that we then end up switching between conan versions (eg on test machines when building old versions of our software). 

We could blow away the .conan folder as part of testing, but this would require re downloading packages, which would be a quite significant increase to our build times.

Perhaps there is some better way to set things up so that we can
- make sure the conan versions are specified as part of our git repo
- preserve conan caches across builds

Thanks.

**Comment by drussel** [comment]
I think it is a misdiagnosis in this case caused by bincrafters issues. (see 5780). The general issue does occur, but I'll close it for now.

**Comment by memsharded** [comment]
Hi @drussel 

We try to keep patch releases to be as small as possible, only for bugfixes, and not introducing any change in conf files. I think in 1.18.1->1.18.4 nothing changed in those conf files, but let me know if not the case.

But in any case, yes, I understand the issue, we never have considered retro-compatibility and rolling back to previous versions in the client in our releases, focusing in forward compatibility is already very challenging. I don't think we could implement something that is robust enough and that is not too much of overhead for us. I'd say that the only possibility is indeed to remove the cache when rolling back to previous versions. It is not only the conf files that can change, but also the packages themselves might have broken things, like the metadata inside them. 

> make sure the conan versions are specified as part of our git repo

Yes, this is definitely something that many of our users are doing in production. Not installing the last Conan version always, but having a fixed (and typically parameterizable) version of Conan. To check if something breaks, they would run a build with the new Conan version in a branch, in an staging environment not sharing with the others.
