### ISSUE TITLE
Recipe not found after successful upload to conan server

### ISSUE THREAD

**Issue by ashlander** [conan-io/conan#5789]
Local conan server is used to store the packages, works in docker. Package was uploaded successfully. But search/inspect/download from the client can't find the package. 

> networker/0.1.1060@bsw/beta: Retrieving from server 'conan-local' 
> networker/0.1.1060@bsw/beta: Trying with 'conan-local'...
> ERROR: networker/0.1.1060@bsw/beta was not found in remote 'conan-local'

Reuploading from CI shows

> Uploading to remote 'conan-local':
> Uploading networker/0.1.1060@bsw/beta to remote 'conan-local'
> Recipe is up to date, upload skipped
> Uploading package 1/4: 79b5aedbedfbff981a7bbc312aebaca14502644f to 'conan-local'
> Compressing package...
> [==================================================]
> Package is up to date, upload skipped
> Uploading package 2/4: 023c32ce61afd6ccac71e4df016b6cbc62866d9c to 'conan-local'
> Compressing package...
> [==================================================]
> Package is up to date, upload skipped
> Uploading package 3/4: 2311317dc538f6938381219feb333f9b4575344f to 'conan-local'
> Compressing package...
> [==================================================]
> Package is up to date, upload skipped
> Uploading package 4/4: 31d200350ef865eb56a52db1c9ef3f4ff53db2b3 to 'conan-local'
> Compressing package...
> [==================================================]
> Package is up to date, upload skipped 

In order to check conan-server was updated and packages were migrated without any problems to version 1.18.4 (conanio/conan_server:latest)

Old packages however can be found, up to version 0.1.777 always, before and after migration.

> conan search -r conan-internal | grep networker | grep beta
> networker/0.1.477@bsw/beta
> networker/0.1.481@bsw/beta
> networker/0.1.484@bsw/beta
> networker/0.1.488@bsw/beta
> networker/0.1.492@bsw/beta
> networker/0.1.554@bsw/beta
> networker/0.1.563@bsw/beta
> networker/0.1.650@bsw/beta

I checked https://semver.org/ for possible version limitations, but the only limitation i found is 255 version length

Are there any conan server limitations, like number of package versions stored (summary i have 143 different packages visible) ? Or some force rebuild needed ?

Server:
Conan server version: v0.12.13
Conan version 1.2.3
Linux x64

Migrated to Server (conanio/conan_server:latest):
Conan version: v1.18.4
Linux x64

Client:
Conan version 1.15.1
Linux x64

**Comment by memsharded** [comment]
> Are there any conan server limitations, like number of package versions stored (summary i have 143 different packages visible) ? Or some force rebuild needed ?

No, the conan_server does not have any limitations in the number of package versions.

I am not sure, you said you were running a Conan server 0.12.13? Is there a typo there, or was it really a 0.12 server? The only version that is in our changelog is: 0.12.0 (13-September-2016), from 3 years ago. It is possible that something is broken from that versions, migrations are really only intended to work after 1.0 versions.

Just to make sure I understood the issue. After the migration, if you upload a new package to the Conan 1.18 server, with a Conan 1.15 client, it is uploaded, but it is not seen by the client with any search/inspect/install operation?

**Comment by ashlander** [comment]
Previous server version is indeed 0.12.13, I double checked it

To make it more clear i looked into all the versions and having new information

### Actors:
OldServer (0.12.13)
NewServer(1.18.4)
CIRunner (conan 1.13.2 from docker image conanio/clang60)
Client1 (conan 1.15)
Client2 (conan 1.18.4)  installed from the scratch on other computer
 
### Sequence:
1. **CIRunner** builds package, sends to **OldServer** without any problems, at some point old packages (up to v 0.1.777) are found with search/inspect/download from **Client1**, but the new ones are not.
2. To solve the problem **OldServer** is upgraded to **NewServer** with package migration - Success (whatever it meant)
3. Result is the same as before, from **Client1** older packages are seen, could be inspected and downloaded, new one are not, even after **CIRunner** rerun and successful upload
4. New **Client2** is set, and all packages are visible and downloadable (!!!). But when I return back to **Client1** new packages are still missing (?!)

**Comment by lasote** [comment]
I tried to upload packages with `1.15.1` and then use them/search them with `1.18.4` and it works correctly. Probably something changed before Conan 1 that make your older packages to fail somehow.
I would recommend to use `conan download` iterating the references (you can maybe extract it from a `conan search --json`) command with `Client2` and upload them all to a new fresh instance of the `conan server`.

**Comment by ashlander** [comment]
Shame on me :man_facepalming: No problem ever existed.

It appears Client1 used internal conan server from localhost, from the days main server failed. No surprise newest packages were missing...

Well good thing, 0.12 server if upgradable, now we know it, and all clients using latest conan version. :nerd_face:
