### ISSUE TITLE
`yum` removed from Fedora 31, breaks package manager installations from conan

### ISSUE THREAD

**Issue by ShadowMitia** [conan-io/conan#5790]
The `yum` tool has been completely [removed](https://fedoraproject.org/wiki/Changes/Retire_YUM_3) from Fedora 31.

This means that when installing dependencies that would trigger installations of packages through yum, conan exists with an error. 

`yum` needs to be replaced with `dnf` at least for Fedora.

As a workaround you can install the packages manually, since the missing package will be shown in the error.

Steps to reproduce (on completely new installation of Fedora) :
- create a project with `CMake` and `cmake-conan`
- Install conan
- Try to build with `cmake -s . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=yes`

Conan version : 1.18.4
OS : Fedora 31 Beta

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by uilianries** [comment]
Hi Dimitri! What is the new tool used by Fedora?

**Comment by ShadowMitia** [comment]
It's not exactly new, but it's the `dnf` package manager. It was introduced a while back while `yum` was obsoleted and now it fully replaces it in the next release of Fedora.

**Comment by uilianries** [comment]
Nice! Thanks! :D

**Comment by ShadowMitia** [comment]
I believe that my pull request is working but I can't make the unit tests work.

When I run `tox` I get 11 errors, and I can't make heads or tails from them.

Complete logs are [here](https://gist.github.com/ShadowMitia/3ae0d18a6c96ce9f0dbc5cde14801691)

Any hints would be welcome. I get the same errors when getting the latest develop branch without my changes, so I'm guessing I'm doing something wrong but I have no idea what.

**Comment by lasote** [comment]
Merged, to be released at 1.20
