### ISSUE TITLE
[Workspaces] Workspaces should allow multiple applications (roots???)

### ISSUE THREAD

**Issue by bredej** [conan-io/conan#5793]
I didn't want to hijack existing issues about workspaces with my limited experience, but I will try to give some feedback here.

Our typical repo consists of a library, a unit test application and one or more demo/example applications dependent on the library.  Not an uncommon way to organize a repo on Github. 

My goal is to make this setup developer friendly to continue work on the library.
So I create a Conan workspace and a batch file that generates a VS solution with three projects.
The problem is that it is not possible to have more than one "root" project in a workspace yml file.
I also find it confusing to call the final project 'root'.  To me the library is the root.  Unit test and other applications are leafs.

I don't know if it's my lack of understanding or it's a limitation in the current workspace implementation, but hopefully there's a way :-)

Conan version 1.18.4
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Lawrencemm** [comment]
I'm currently using multiple roots like this:
```
conanws.yml

editables:
    - ...

root:
    - something
    - some_other_thing
```
Are you able to add multiple roots with this YAML list way?

**Comment by bredej** [comment]
Yes, it works and it is documented.
Thanks!
