### ISSUE TITLE
Lockfiles of packages without user/channel have _

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5799]
The lockfile contains:

```
"graph_lock": {
  "nodes": {
   "3e78db6e-de3d-11e9-bfb7-84fdd15e6b30": {
    "pref": "test4/0.1@_/_:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", 
    "options": ""
   }
  }
 ```

Should it drop the user/channel with _? Should that be used exclusively for paths and folders?

Right now it seems there is no support for something that is able to dump ``PackageReference`` including the revisions but dropping None user/channel.

**Comment by lasote** [comment]
Yes. It should be dropped.
