### ISSUE TITLE
Request for packaging of libxml2

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#58]
Hi,

I have managed to setup my project to use conan and build on windows[1] - thanks very much for the packages you already support, which made it possible. However, one minor stumbling block was lack of support for libxml2. I worked around this problem by installing it from Nuget and then getting CMake to see it. Its not pretty, but it works. 

Would it be possible to package libxml2 directly in conan?

Cheers

Marco

[1] Work on a green build is still ongoing, but all dependencies are now located correctly. See https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.11

**Comment by lasote** [comment]
Hi!
I will try it tomorrow morning, Should not be hard. 

Enjoy conan!

**Comment by mcraveiro** [comment]
thanks!

**Comment by lasote** [comment]
You can try the linux packages in your CI system? There are packages available for gcc 4.6-5.2

libxml2/2.9.3@lasote/stable

I'm going to take a look to windows, but it looks a little more tricky!
I hope you have enough fun with this for this morning ;)

**Comment by lasote** [comment]
Packages for windows (VS12-14-15) are also uploaded.

I close the issue, if you have any issue with the library please, write here:

https://github.com/lasote/conan-libxml2/issues

**Comment by mcraveiro** [comment]
thanks very much for your prompt work! I was away from the PC so only actioned this now, waiting on CI build. Will report back.

Cheers
