### ISSUE TITLE
Drop Python 3.4 support

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5819]
There are several deps of Conan like `urllib3` and `ast` that have dropped or are dropping the support for `python 3.4`. Especially for Windows it is becoming a maintenance problem for the project, so we are going to stop the python 3.4 testings.

**Comment by lasote** [comment]
Removed from CI

**Comment by uilianries** [comment]
Maybe add a warning message? Python 2.x has a good message.

Also, update the docs: https://docs.conan.io/en/latest/installation.html#install-with-pip-recommended

**Comment by uilianries** [comment]
Now I found a commit there related to this issue: https://github.com/conan-io/docs/commit/aeaafa2ca656cb062dee57c5d68bbadaad76da44

**Comment by memsharded** [comment]
> Maybe add a warning message? Python 2.x has a good message.

I agree, a explicit message saying it is deprecated might be useful

**Comment by lasote** [comment]
@uilianries create an issue with the warn and submit PR for the 1.9
