### ISSUE TITLE
Refactor virtualenv generators

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5821]
Objectives:
 * Decouple the script to apply the variables from the file declaring them
   + the script should be exactly the same for any environment (only dependant on the cmd platform: ps1, sh, cmd)
   + all the variables should be contained into a ``.env`` file (some usage examples: [docker](https://docs.docker.com/compose/env-file/), [npm dotenv](https://www.npmjs.com/package/dotenv), [heroku](https://devcenter.heroku.com/articles/heroku-local#set-up-your-local-environment-variables),...).
 * It should help to simplify the code

It is also **needed for the plugins**, they need to read environment variables from some file in order to apply them before calling some Conan commands or CMake itself.

--- 

Other things to consider (not the first iteration):
 * Should ``scripts`` be generated or contained in the Conan codebase (and updated with new versions)? It would allow activation like:
   + ``$> conan_env <path/to/file.env>``, is it possible to use a Conan command for it? Can be created a _stack_ of activated virtualenvs and help the user with it? 
    + ``$> my_local.sh``, it will be implemented like ``<path/to/conan/activate.sh>  <path/to/local/file.env>``

**Comment by jgsogo** [comment]
Testing approach suggested here by @ytimenkov should probably be considered first: https://github.com/conan-io/conan/pull/4291

**Comment by memsharded** [comment]
Yes, I agree, that has been a long standing open issue, we couldn't move forward it properly (sorry @ytimenkov), if we are doing this, I agree that recovering that effort for better testing the environments would be a great thing.
