### ISSUE TITLE
Determine package name from conanfile.py

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#5842]
I am trying to find a way to determine the package name from a conanfile.py while `self.channel` is used in the `requirements()` method to add a dependency to package with the same channel.
Thus `conan info .` does not work (`self.channel` not set and `CONAN_CHANNEL` is deprecated so i want to avoid using it).
Is there any other way?

thx,
Peter

Conan 1.8.2 under Windows

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi Peter!

Not clear, you meant the package name, like with ``conan inspect . -a name``?
Thanks!

**Comment by petermbauer** [comment]
:man_facepalming: yes, totally missed that, sorry for the noise.
BTW, as it is still "experimental", which kind of breaking changes should be expected in the future?

**Comment by memsharded** [comment]
>  yes, totally missed that, sorry for the noise.

No problem 😄 

It is likely that we will change the command line arguments to make them more uniform with other commands, regarding the output (json, raw, etc), and also the output might change. In any case, we will try not to do that until Conan 2.0, and I don't see the command being removed, so in any case should be relatively easy to upgrade.
