### ISSUE TITLE
[question] Integrating packages with existing ones

### ISSUE THREAD

**Issue by thegwydd** [conan-io/conan#5847]
Hello people.

Suppose I'm the user "foo" and I have created a package on my bintray/conan_server/whatever, and I have built it on my local machine mach1 with VS2019 and then uploaded as bar/1.0.0@foo/stable.

Then, one day, I use machine mach2 where I have only VS2017 and I want to build the package and upload new build to the existing bar/1.0.0@foo/stable on my server.

Later I have access to a third machine mach3 with Ubuntu and gcc and I want to do the same, build and upload packages to the same bar/1.0.0@foo/stable.

At the end my bar/1.0.0@foo/stable will have a lot of different binaries for all of my machines.

How can I achieve that?

**Comment by uilianries** [comment]
Hi @thegwydd !

Just follow the regular flow to build your package and upload them normally. All binary packages are uploaded separated, according the package id.

To build your package you can follow these steps:
https://docs.conan.io/en/latest/creating_packages/getting_started.html

To upload your package you can follow these steps:
https://docs.conan.io/en/latest/uploading_packages/uploading_to_remotes.html

**Comment by thegwydd** [comment]
Hi @uilianries,

so you mean that the package on the server is not substituted with the one build and uploaded from each machine because the server **merges** all packages with different configuration?

I mean, at the end of the builds I should find a situation like the following:
- bar/1.0.0@foo/stable
   - <win32 VS2019 settings hash> - binaries/libs/headers/etc...
   - <win64 VS2019 settings hash> - binaries/libs/headers/etc..
   - <win32 VS2017 settings hash> - binaries/libs/headers/etc..
   - <win64 VS2017 settings hash> - binaries/libs/headers/etc..
   - <gcc vXX.YY settings hash> - binaries/libs/headers/etc..
   - <gcc vRR.ZZ settings hash> - binaries/libs/headers/etc..
   - <other settings hash> - binaries/libs/headers/etc..

Am I right?

**Comment by uilianries** [comment]
> so you mean that the package on the server is not substituted with the one build and uploaded from each machine because the server merges all packages with different configuration?

The server does not merge any package. All Binary packages are stored separated according the reference and the package id. The ONLY replace the package if the package id the same AND the revision feature is disabled.

For further information, please read:
https://blog.conan.io/2019/09/27/package-id-modes.html
https://docs.conan.io/en/latest/versioning/revisions.html
https://docs.conan.io/en/latest/introduction.html#binary-management
https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html
https://docs.conan.io/en/latest/creating_packages/understand_packaging.html

**Comment by memsharded** [comment]
> so you mean that the package on the server is not substituted with the one build and uploaded from each machine because the server merges all packages with different configuration?

The only thing I would recommend to be careful is the CRLF of the git checkout of the repository (I'd always use the same LF in all platforms). Because if the process in every platform is:

```bash
$ git clone <url>/repo & cd repo
$ conan create . user/channel -pr=myprofile
```
Then, if the git clone converts the conanfiles in the repo to have different CRLF in different platforms, then, technically the recipe has changes, it is a different recipe, and might internally have a different revision. You really want to make sure that the same revision is used for the same commit in the repo.

Besides that, yes, exactly, you are totally right, conan will manage to store each different configuration in a different package-ID, so they will not overwrite or collide.
