### ISSUE TITLE
[question] How to not include some libs in conanbuildinfo.props

### ISSUE THREAD

**Issue by petebannister** [conan-io/conan#5848]
Conan version 1.19.0

I have a dependency on boost (boost/1.71.0@conan/stable).

I'm using the visual_studio generator with VS2017

This adds *all* of the boost libs to conanbuildinfo.props which causes my build to fail.  I don't completely understand why this used to be OK with 1.68 and now fails with that too after moving my cache to a different drive (perhaps it was due to installing vs2019 alongside vs2017). 

But regardless it would be good if I could either cherrypick which libs to include or remove specific ones from the list.

For example I don't want to include any of the stacktrace libs which result in duplicate symbols.

I can't figure out how to do it.  If I specify any of the 'without_xxx' options then it rebuilds the whole of the boost dependency which I would rather avoid - I just want to control which libs it puts in the vs props file!

I was trying to see if there was some place I could remove them from deps_cpp_info but it doesn't look like there is a place to put that (i.e. an event just before the generators are run).

Perhaps overriding the generator could do the trick but it seems like that would be a bit of a sledgehammer and not all that clean.

**Comment by memsharded** [comment]
Hi @petebannister 

This would be a duplicated of: https://github.com/conan-io/conan/issues/5844

We have already prepared a patch to fix this regression, and will release it asap in 1.19.1. 

Thanks for reporting!

**Comment by petebannister** [comment]
@memsharded Thank you for the quick reply!  I think it might also be useful to control which libs actually end up in deps_cpp_info?  If there was a ConanFile method called before the generators step then that would be possible there at least even if there might be a nicer higher-level option such as an ignore_libs attribute?

**Comment by memsharded** [comment]
I think there are 2 different things here. One is the thing that I suspect has been broken, which is the regression linked above. The other is the possibility of selecting individual libraries from a package that contain multiple libraries like boost. Right now this is not possible in conanfiles, when using cmake is possible in the CMakeLists.txt, like:

```cmake
include(... /conanbuildinfo.cmake)
# Filter here CONAN_LIBS or CONAN_BOOST_LIBS variable to contain only those that you want
conan_basic_setup()
```

If using ``visual_studio``, which is your case, it is not possible at the moment. We are right now improving the way that these files are generated, and will be creating methods for that. If you want, you can follow this conversion here: https://github.com/conan-io/conan/issues/5737 (this current issue will be closed if the PR is merged, and hopefully your build with be green again)

**Comment by petebannister** [comment]
@memsharded Thank you - using conan 1.18.0 fixes it for the time being!

**Comment by danimtb** [comment]
Conan 1.19.1 was released with the fix. Thanks!
