### ISSUE TITLE
[suggestion] Search package by profiles

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5850]
Hi!

The command [search](https://docs.conan.io/en/latest/reference/commands/consumer/search.html) is able to filter the results by the argument `--query`, but let's say I want to search my current profile, to check if the binary package is available. I could use `--query` with multiple tokens, but it would be nice if Conan was able to read my profile and parse it directly:

    conan search -r conan-center -q profile=default boost/1.71.0@conan/stable
    OR

    conan search -r conan-center -p default boost/1.71.0@conan/stable

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
> , to check if the binary package is available

But usually when you are looking for a missing package is because the profile didn't resolve  anything, probably because a custom package id or an intermediate package changing options.

**Comment by uilianries** [comment]
exactly, if I looking for a missing package when installing, but there is another scenario:

- If I have the package exported on my local cache, but I don't have it built, so I would like to investigate if that package is available in another remote.

- Let's say my company uses the same configuration for distribution and my says that a specific is not available on Artifactory, but I'm it's there. I could confirm easily using the shared profile. 

- Sometimes the CI fails and only few packages are uploaded. I can read the logs to check, but also I can use Conan search for a quick validation.

**Comment by lasote** [comment]
In all these situations, at some point, I think you have the missing package_id. You can directly search for it.

**Comment by uilianries** [comment]
True! I totally forgot it! I think the radiation is killing my brain!

**Comment by district10** [comment]
> In all these situations, at some point, I think you have the missing package_id. You can directly search for it.

Sorry I don't understand.

I have a package `boost/1.71.0@conan/stable` and a profile `default`, I can generate a package id? like `1089748a7479fc38ea786206ddb749e55f84dc60`? And I can search across certain remotes to check if its downloable?

I just need to check if suitable remote package already exists before pushing the one I just built (pushing a new one may fail according to conan server configuration).

Related: https://github.com/conan-io/conan/issues/6842

**Comment by district10** [comment]
For now I'm using:

```
conan remove <my_package> -f
conan install <my_package> --profile default || conan upload --all -r=<remote> <my_package>
```

**Comment by memsharded** [comment]
> I just need to check if suitable remote package already exists before pushing the one I just built (pushing a new one may fail according to conan server configuration).

Not really. With revisions enabled (totally recommended, as they will be activated always in 2.0, which is already in alpha stage), new changes get new revisions, and do not overwrite things in the server. Uploading something that already exists in server is a no-op, nothing is actually uploaded. 

What should be avoided is earlier, not building a package if it already exists in the server. The ``--build=missing`` policy is what can help here.
