### ISSUE TITLE
Proper cross-compilation support

### ISSUE THREAD

**Issue by Lyberta** [conan-io/conan#5851]
It looks like new cross-compilation system is scheduled for 2.0, here are my suggestions:

* Split `.conan/profiles` into `.conan/build_profiles` and `.conan/host_profiles`.
* Remove `arch_build` and `os_build` settings as they are no longer needed.
* Split `settings.yml` into `settings_build.yml` and `settings_host.yml`.
* Add ability to specify packages in build profile in both `conanfile.txt` and `conanfile.py`.

I personally find current terminology very confusing. I'd prefer "host" for build system and "target" for... uh, target system.

**Comment by Minimonium** [comment]
Hi @Lyberta 
Most of it is a part of the planned cross-compilation model. @jgsogo works on it.
The initial draft with many good comments is here https://github.com/conan-io/conan/pull/5202, but it's too big to merge right away so it's worked upon incrementally:
https://github.com/conan-io/conan/pull/5592
https://github.com/conan-io/conan/pull/5594

**Comment by memsharded** [comment]
> I personally find current terminology very confusing. I'd prefer "host" for build system and "target" for... uh, target system.

The terminology we are using we didn't decide, it is the standard gnu terminology for cross-building.

**Comment by jgsogo** [comment]
Hi, @Lyberta , we are adding a new feature to Conan 1.24, it allows to define a `profile_host` and a `profile_build`, both of them using the same settings file.

I think we should close this issue with https://github.com/conan-io/conan/pull/5594 and we will be pleased to receive your feedback on top of that feature.

Thanks!

**Comment by Lyberta** [comment]
LGTM so far.
