### ISSUE TITLE
Conan uploading invalid packages to Artifactory

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#5852]
Recently we noticed that corrupted packages started appearing in our Artifactory server. This happens when compressing of package fails and later attempt of uploading the same package sees that .tgz already exists (although broken) and uploads it.

The compression of package can fail due to multiple reasons, such as power failure during compression or due to a CI job being killed.

However, with conan v1.18 (we currently use 1.18.5, still haven't updated to v1.19.0), we also noticed following errors during compression that apparently happen at random:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/conans/client/command.py", line 1859, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.7/site-packages/conans/client/command.py", line 1370, in upload
    retry_wait=args.retry_wait, integrity_check=args.check)
  File "/usr/local/lib/python3.7/site-packages/conans/client/conan_api.py", line 78, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/conans/client/conan_api.py", line 918, in upload
    retry, retry_wait, integrity_check, policy, query=query)
  File "/usr/local/lib/python3.7/site-packages/conans/client/cmd/uploader.py", line 89, in upload
    integrity_check, policy, remote, upload_recorder, remotes)
  File "/usr/local/lib/python3.7/site-packages/conans/client/cmd/uploader.py", line 202, in _upload_ref
    integrity_check, policy, p_remote)
  File "/usr/local/lib/python3.7/site-packages/conans/client/cmd/uploader.py", line 268, in _upload_package
    files_to_upload, deleted = self._package_files_to_upload(pref, policy, the_files, p_remote)
  File "/usr/local/lib/python3.7/site-packages/conans/client/cmd/uploader.py", line 382, in _package_files_to_upload
    local_manifest = FileTreeManifest.loads(load(the_files["conanmanifest.txt"]))
  File "/usr/local/lib/python3.7/site-packages/conans/model/manifest.py", line 77, in loads
    the_time = int(tokens[0])
ValueError: invalid literal for int() with base 10: ''

ERROR: invalid literal for int() with base 10: ''
```

**Comment by danimtb** [comment]
Hi @DoDoENT!

Thanks for reporting a sorry for the trouble.

I have been looking at the code regarding the integrity check we do and we are only comparing the manifests, so you might be in the right direction regarding the corrupted *.tgz*. We could check the integrity of the tar file but not sure if there is a way of doing that without decompressing all the content.

Regarding the manifest issue, this could probably be an error produced by the same issue of a corrupted package. The manifest might be incomplete and Conan fails to read it. We can improve this check also to mark the package as ill-formed.

**Comment by DoDoENT** [comment]
Regarding the check of the tgz, you could do it the same way you check whether a package build directory is dirty - with a lock file. So, if tgz does not exist, create a lockfile, create a tgz and remove the lockfile. If tgz exists and lockfile exists, you know that tgz was not created completely (process somehow died), so start anew.

**Comment by danimtb** [comment]
Having a closer look at the code, I see that the "dirty" status is already implemented. In case of having that file, Conan should error with "Package is corrupted, aborting upload."

So I don't see how are you getting those corrupted tgz files uploaded. Do you have any way to reproduce it?

**Comment by danimtb** [comment]
I have tested if this could be an issue in the Artifactory side but worked well for me as well 😕

**Comment by DoDoENT** [comment]
Actually, neither can I reproduce this on my machine. However, the fact is that somehow corrupted packages did appear on our Arfifactory (even when manually downloading the conan_package.tgz I couldn't decompress it) and we traced that to upload job that happened after power failure in our server room.

Also, the fact is that during I got the above mentioned stack trace on our CI machines while performing compression before upload. However, I didn't check if .tgz.dirty was there after the crash - I needed to clean the conan cache and manually remove the packages from the Artifactory in order for our other teams to be able to work.

Unfortunately, I don't have a way to deterministically reproduce this issue (if I had a way, I would definitely describe it in the initial report).

**Comment by danimtb** [comment]
@DoDoENT did you experienced this issue again? As we are not able to reproduce it, it will be difficult to fix anything here 😕 As I commented previously, the code looks good in the client side

**Comment by DoDoENT** [comment]
No, but only because we made a workaround on our CI. The upload of packages is now forbidden unless the packages are built in the same job. So now, if power failure happens again, we will build all required packages in a clean cache, without taking a risk that some packages are left corrupted from previous builds.

This currently works for us, and since neither you nor I (on my laptop) could reproduce the error, I guess it's OK to close this issue - but be aware of it if something similar happens in the future.

**Comment by danimtb** [comment]
Thanks a lot for sharing your experience. I hope no one faces a similar issue like this. Otherwise, we will investigate this further for sure. Thanks!
