### ISSUE TITLE
[Feature] Add support of the `--table` option for all installed packages (`conan search` without a reference).

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#5865]
The common usage of the `--table` option is:
```bash
$ conan search

$ conan search ref --table=output.html
```
which is annoying because you have to select the one of the ref strings and then re-type the command.
It would be useful just to type `conan search --table` and get the generated `packages.html` page opened in the default browser. The generated page may have a sort of an index at the beginning.

**Comment by lasote** [comment]
In general, the `conan search` search for recipe references and `conan search <ref>` search binary packages for a recipe. So it wouldn't the most consistent if `conan search --table` generates a page with all the binaries for all the recipes.
Is this command something you frequently need to execute? why? 
Thanks

**Comment by DmitrySokolov** [comment]
OK, then I think it should has another name.
I use it to detect what packages were built (and uploaded) correctly during a build round.

**Comment by memsharded** [comment]
Implemented in 2.0. Be aware that getting all binaries from all packages might take a lot of time (many minutes) if the repo contains many packages. Still recommended to restrict to few packages.
