### ISSUE TITLE
Inconsistent output of `conan search ref --table` command.

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#5866]
For Visual Studio you can get the following output

&nbsp; | x86_64 Debug | x86_64 Release
-- | -- | --
Windows Visual Studio 15 (MD) |   |  X
Windows Visual Studio 15 (MDd) |  X |

but you can't get `MDd Release` or `MD Debug` configurations. So such output is inconsistent.

It would be better to output:

&nbsp; | x86_64 Debug | x86_64 Release
-- | -- | --
Windows Visual Studio 15 (Dynamic: MD, MDd) | X | X
Windows Visual Studio 15 (Static: MT, MTd) | X | X

**Comment by lasote** [comment]
> but you can't get MDd Release or MD Debug configurations

Actually I think you can. `MDd/MD` is about the runtime, not the `build_type`, but probably you can force it and I would say it could build. Anyway, the table is representing the settings model, that differentiates the runtime and the build_type. So I think it is correct.

**Comment by DmitrySokolov** [comment]
Technically you can, but practically, you can not. I think it just clutters the output.

**Comment by lasote** [comment]
I prefer the table representing the settings model as it is.

**Comment by DmitrySokolov** [comment]
> Actually I think you can

There is the warning specially for this case:
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4098?view=vs-2019

Besides:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019

>To build a debug version of your application, the _DEBUG flag must be defined and the application must be linked with a debug version of one of these libraries. For more information about using the debug versions of the library files

Also:
https://docs.microsoft.com/en-us/visualstudio/debugger/debug-versions-of-heap-allocation-functions?view=vs-2019

Debug libraries use special version of memory allocation functions. And mixing them with release version is not a good idea.

So, I would say, that the current VS runtime config axis is wrong and confusing.

**Comment by memsharded** [comment]
Table format changed in 2.0, closing this as outdated.
