### ISSUE TITLE
Most conan_basic_setup defaults violate known best practices

### ISSUE THREAD

**Issue by jeremyong** [conan-io/conan#5868]
Apologies if this isn't the best channel for this, but I wanted to raise this because `conan_basic_setup` is actively harmful and making it difficult for me to recommend conan to colleagues.

1. Massive state modification which *is not guaranteed* as conan updates. I find the integration itself immediately overly intrusive and makes me paranoid about ever updating conan when maintaining a large or complicated build tree
2. Preference for globals over targets. No modern project should use the former.
3. Setting the CXX standard globally. If a single project invokes this macro, the variable is now affecting all downstream targets that correctly use `target_compile_features` to define the standard expected.

I'm aware that these can be overridden, but I've already seen many cases in the wild that make their projects untenable to integrate without needing to introduce fixes upstream. Further, I believe these practices are actually poisoning the pool of cmake projects that rely on conan.

**Comment by memsharded** [comment]
Hi @jeremyong 

Yes, we are aware of this issues, and are working to improve the situation. There are a few reasons why this was the original approach followed by Conan, including necessary backwards compatibility to CMake 2.8.12, still used by quite a few Conan users. We know that global configuration shouldn't be use, but there are many Conan users out there trapped in gcc<4.5 and cmake 2.8.12, and we need to provide them alternatives. Our getting started tries to be something that works for most users, including those with older tools.

We are soon starting to recommend the new ``cmake_find_package`` generators, once we are able to provide an alternative to some of the existing functionality (it will be done in cmake toolchain files, generated by Conan). If you haven't yet, please check and try the new ``cmake_find_package_multi`` generator. Beware of some of its limitation, for example, it will NOT set the Visual Studio runtime (MT, MD, etc) based on the project settings, which is necessary to maintain a correct ABI, and practically no project out there provides configuration for it (this is one of the reasons why it is very convenient the ``conan_basic_setup()`` doing this job).

**Comment by madduci** [comment]
i guess it's time for a `conan_basic_usage(modern_cmake)` or something similar that uses more modern behavior and best practice

**Comment by KerstinKeller** [comment]
Hi @jeremyong,
if you're working exclusively with CMake, and if you're packages are using modern CMake (e.g. they are providing `<Package>Config.cmake` files, try using the `cmake_paths` generator that Conan provides. It's non intrusive, we're using it exclusively and it works nicely for us. Basically nothing it set from Conan except the `CMAKE_PREFIX_PATH` and `CMAKE_MODULE_PATH`, and even these are set from the outside, so no need to modify your CMakeLists.txt files.

**Comment by lasote** [comment]
> i guess it's time for a conan_basic_usage(modern_cmake) or something similar that uses more modern behavior and best practice

There is a `conan_basic_setup(TARGETS)` to activate the modern CMake already.
I agree probably we should change the demos/docs and stop showing the old cmake way, I'm willing to start recommending the `cmake_find_package_multi` usage but first, we need to do this: https://github.com/conan-io/conan/issues/5737 

Thanks all for your comments, it is very important for us to know your opinion.

**Comment by lasote** [comment]
I'm going to discuss with the team if in the meantime we should stop using the global approach in the "conan new" generated files and the most important, in the `docs` and demos.

**Comment by jeremyong** [comment]
Thanks all I appreciate the response to the feedback and look forward to what you all come up with

**Comment by memsharded** [comment]
We have already started to annotate in https://github.com/conan-io/conan/pull/6490 things that will change behavior in Conan 2.0. Certainly Conan 2.0 will change the defaults to the above recommendations, and using modern best practices, but need to wait, because changing defaults now would be breaking for existing users.

Most recommendations would already have specific issues in https://github.com/conan-io/conan/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3A2.0, so I am closing this one at the moment. Otherwise comments can be done in https://github.com/conan-io/conan/pull/6490 or open a specific new one for 2.0.
