### ISSUE TITLE
[workspaces] workspace imports

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#5869]
I want to copy files into the workspace install folder from non-editable dependencies.
```
conanws.yml

imports:
  - pattern: some_regex
    dst: some_folder
    src: some_folder
    ... etc for other arguments to conanfile "copy" method 
```
This should work similarly to the `imports` section of a conanfile- I'm not sure it's as simple as this but hopefully you could just forward each element of this list as a kwargs dict to the `copy` function that's used in the imports section of conanfile.py.

I believe it would be complicated to support this being able to get stuff from editable packages in the workspace. I'm not asking for that; this can just work for non-editable packages.

**Comment by lasote** [comment]
Which kind of files do you want to copy? (I want to learn about it) Are we talking about runtime (shared libs, exec, assets)? or other things?

**Comment by Lawrencemm** [comment]
At the moment, I wanna copy DLLs. Doing that plus building all my workspace packages to the workspace build directory solves shared library problems on windows in a pretty easy way.

**Comment by lasote** [comment]
Thanks. Yes, there is a pain there with the runtime. I don't know if is there a workaround for that, maybe @jgsogo can help us.

**Comment by Lawrencemm** [comment]
As an aside, this might be useful for "workspace packages" which would be packages just containing stuff you want to use in workspaces eg. useful CMake scripts to reuse.

**Comment by memsharded** [comment]
Imports were dropped in 2.0 (replacement for them using ``generate()`` already possible in 1.X)

Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
