### ISSUE TITLE
improve tools.cross_building to consider x86_64 -> x86 cross-compilation use-case

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#5870]
often, `x86_64` -> `x86` cross-compilation could be considered the special case (if operation system is the same, of-course). it's because `x86_64` systems may run `x86` binaries, and usually there are so-called `multilib` compilers are available, so special preparations for cross-compilation aren't needed.
(NOTE: the opposite use-case `x86` -> `x86_64` isn't special, as `x86` systems can't run `x86_64` binaries)
there are many recipes which had to apply workarounds over `tools.cross_building` in order to satisfy their needs, e.g.:
https://github.com/conan-io/conan-center-index/blob/314ed91c6ecdbb6c21bba0eb3c438a6f3812060b/recipes/openssl/ALL/conanfile.py#L533
https://github.com/conan-io/conan-center-index/blob/9fd59cdef011bcbdcbcc3543cef9fa74714cb7e3/recipes/icu/all/conanfile.py#L145
https://github.com/bincrafters/conan-qt/blob/5093f8dc85ee01cb8b6d1baac2698c4b276cc9ce/conanfile.py#L518
it would be nice to provide an additional argument for `tools.cross_building` to return `False` for the the `x86_64` -> `x86` use-case (same OS)
proposal:
```
tools.cross_building(self.settings, native_x86=True)
```

To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Hopobcn** [comment]
Couldn't conan detect that the compiler is `multilib` to not require an extra paramter in `tools.cross_building`?

**Comment by SSE4** [comment]
@Hopobcn probably, it's also possible, as part of https://github.com/conan-io/conan/pull/5740
