### ISSUE TITLE
package graph info best practices

### ISSUE THREAD

**Issue by luke-elwood** [conan-io/conan#5871]
We have been trying to start using conan for a couple of months now and are having trouble with best practices for knowing which dependency versions are being used in our projects and libraries. Do we need to manually copy a conan.lock file and or a conanbuildinfo.txt file into our own file server everytime we build a new release? Does conan not have a way to see the graph info of a built artifact once it has been uploaded to the artifactory? Our internal libraries all depend on eachother and they are all under active development with regular released updates so it would be helpful if there was a fast way to query the dependency graph of an old package.

**Comment by memsharded** [comment]
Hi @luke-elwood 

It depends on what is exactly what you want. If I understood correctly, it seems that you want an exact capture of the dependencies that were used at the time when a package was built and uploaded. This can be only achieved with lockfiles, as with the rest of the approaches the information is evaluated, and a new dependency graph is computed. If anything changed, then a new dependency graph might result. 

Also, the repositories and dependencies do not contain a unique relation of binaries. It is totally possible that a package binary is compatible with 2 different versions of its dependencies, and it might use either of them in a dependency graph. Then, there is no 1:1 relation between a package and its dependency.

So, yes, with lockfiles, some suggestions:

- Every build can have a lockfile per configuration/profile. As the dependency graph can actually be different, lockfiles might be locking different things. One lockfile per configuration.
- Lockfiles are typically defined at the product/project level, not at the package level. Then a package can be built using that lockfile, to guarantee some consistency and reproducibility of that build for that product.
- If you want to be able to reproduce builds after some time, yes, the practice would be to store the lockfiles for that build somewhere. We typically use a generic repo in Artifactory, and store the lockfiles in folder matching the CI (unique) build number, for example.
- we have discussed to embed these lockfiles inside the packages, but we are not doing that yet, unless until the lockfiles are stabilized (they were released very recently, still experimental). So need to store them externally. However, managing them externally is in any case necessary in the CI process. Check the example in: https://docs.conan.io/en/latest/versioning/lockfiles.html#how-to-use-lockfiles-in-ci if you still haven't.

Please let me know if this helps. Thanks!

**Comment by luke-elwood** [comment]
Thanks memsharded. It sounds like the answer to our problem is to set up some CI to build our conan packages and to save the lockfile.

**Comment by memsharded** [comment]
Closing this question as responded
