### ISSUE TITLE
Remotes do not work in docker images

### ISSUE THREAD

**Issue by squarebracket** [conan-io/conan#5872]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

-----

Conan image: conanio/gcc7 (62851d828ec7)

When using the conanio/gcc7 docker image, it seems a remote that is based on the docker host cannot work for installing packages:

```
conan@28424003844d:~$ conan remote add chuck http://chuck.qa.vantrix.com:9300/
conan@28424003844d:~$ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
chuck: http://chuck.qa.vantrix.com:9300/ [Verify SSL: True]
conan@28424003844d:~$ conan install expat/2.2.9@demo/testing
...
ERROR: Error downloading file http://localhost:9300/v1/files/expat/2.2.9/demo/testing/0/export/conanmanifest.txt?signature=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZV9wYXRoIjoiZXhwYXQvMi4yLjkvZGVtby90ZXN0aW5nLzAvZXhwb3J0L2NvbmFubWFuaWZlc3QudHh0IiwidXNlcm5hbWUiOm51bGwsImZpbGVzaXplIjpudWxsLCJleHAiOjE1NzA0ODIxODZ9.EyRV-uOhrmyrlKwIl9WoEp01p_O_0BbwCFrTlkT-oP0: 'HTTPConnectionPool(host='localhost', port=9300): Max retries exceeded with url: /v1/files/expat/2.2.9/demo/testing/0/export/conanmanifest.txt?signature=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZV9wYXRoIjoiZXhwYXQvMi4yLjkvZGVtby90ZXN0aW5nLzAvZXhwb3J0L2NvbmFubWFuaWZlc3QudHh0IiwidXNlcm5hbWUiOm51bGwsImZpbGVzaXplIjpudWxsLCJleHAiOjE1NzA0ODIxODZ9.EyRV-uOhrmyrlKwIl9WoEp01p_O_0BbwCFrTlkT-oP0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd79e4b0128>: Failed to establish a new connection: [Errno 111] Connection refused'))'. [Remote: chuck]
```
As you can see above, it seems to think my remote is at `localhost`, even though my remote clearly is not.

Interestingly, the remote does seem to work for other operations, in that I can find packages I uploaded to it:
```
conan@28424003844d:~$ conan search '*expat*' -r=chuck
Existing package recipes:

expat/2.2.9@demo/testing
```

Clearly, something is wrong here.

To reproduce:
- start a `conan_server`
- upload a package to it
- launch the docker container (`docker run --rm -i -t conanio/gcc7 /bin/bash`)
- add the remote (obviously using the correct ip/hostname for your docker host)
- try to install the package you just uploaded to it

**Comment by memsharded** [comment]
Hi @squarebracket 

I think this might be an issue in the configuration of the server. I would try:

- Configure the ``host_name`` in server.conf before launching conan_server, as described here: https://docs.conan.io/en/latest/uploading_packages/running_your_server.html#server-parameters

- If that fail, try using an Artifactory CE (it is free, and more powerful than conan_server, very recommended). Even if there is a docker image, I would try first with the bare zip, to not introduce other configuration issues.

Please let me if the above works. Thanks!

**Comment by squarebracket** [comment]
Looks like you're right. I'd wondered if maybe it was the server being dumb and redirecting me to a `localhost` hostname, but didn't see any `30x`s in its logs.

**Comment by memsharded** [comment]
Good, if this is solved, I am going to close the issue now, reopen or post a new one as necessary!
Also, in any case I'd still recommend using Artifactory CE, it is also very easy to run and will scale better than the conan_server (and it has a WebUI and other things), while totally free to use.

Cheers!

**Comment by squarebracket** [comment]
I took a look at the source, and did a hardcode of `host='0.0.0.0'` for the `bottle.run` call. It still redirected me to `localhost`. Is this an underlying problem with bottle, or one of the plugins in use? I've never had this kind of problem with flask, so I'm kind of surprised such a thing would occur with bottle.

**Comment by memsharded** [comment]
> I took a look at the source, and did a hardcode of host='0.0.0.0' for the bottle.run call. It still redirected me to localhost. Is this an underlying problem with bottle, or one of the plugins in use? I've never had this kind of problem with flask, so I'm kind of surprised such a thing would occur with bottle.

Because is not that kind of redirect. It is the information that Conan uses to assemble the download/upload signed URLs. Which is 2 step process that comes when Conan was directly used against AWS S3 to fetch packages. You should not be changing only the bottle host, but also the Conan code that returns the signed URLs. Of course I recommend to change the ``server.conf`` file ``hostname`` instead :)
