### ISSUE TITLE
Artifactory returns error on first login attemp

### ISSUE THREAD

**Issue by czoido** [conan-io/conan#5878]
In MacOS Mojave 10.14.6
Using Conan 1.19.1 and Artifactory CE 6.12.2:
To reproduce:

remove user and tokens

`conan user -c `   

Do anything with artifactory that requires login

`conan upload * --all --force -c -r local`

Enter user and password as requested, after that this error will appear:

`ERROR: 400: Unsupported Conan v1 repository request for 'conan'. [Remote: local]`

The second time trying to upload will work.

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Merged and ready to be released at 1.19.2
