### ISSUE TITLE
Conan search does not return versions numerically ordered 

### ISSUE THREAD

**Issue by drodriguez9192** [conan-io/conan#5879]
To help us debug your issue please explain:

Conan version:           1.17.1
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299

When running the below Conan command:
conan search -r *remote_name* *package_name*

The returned list does not output in the correct version order. Instead of using the whole number (i.e. 9.0, 10.0, 11.0, etc.) it uses only the first digit in the version number so you get this instead:

test-model/1.0@xyz/master
test-model/10.0@xyz/master
test-model/11.0@xyz/master
test-model/2.0@xyz/master
test-model/2.1@xyz/master
test-model/3.0@xyz/master
test-model/4.0@xyz/master
test-model/5.0@xyz/master
test-model/6.0@xyz/master
test-model/7.0@xyz/master
test-model/8.0@xyz/master
test-model/9.0@xyz/master

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Agree that it would be nicer if this list would be ordered by version. A few guidelines:

- Consider cases where version is not purely numeric like OpenSSL/1.0.2a
- This should be done in the ``conan_api.py``, not internally, no need to always return an ordered list for other purposes
- It is probably a good chance to clear the ``SearchRecorder``, it is not providing too much value and it is messy, at least for just the recipes. This is to be discussed.
- This is a low priority, if it requires many changes, might not be worth the risk, at least until Conan 2.0

**Comment by memsharded** [comment]
``conan list`` (in Conan 2.0) returns versions and revisions in order, closing this.
