### ISSUE TITLE
Latest Debian download link wrong

### ISSUE THREAD

**Issue by bilke** [conan-io/conan#588]
`http://downloads.conan.io/latest_debian` resolves to -->

`https://github.com/conan-io/conan/releases/download/0.14.0/conan-ubuntu-64_0_14_1.deb`

But should be:

`https://github.com/conan-io/conan/releases/download/0.14.1/conan-ubuntu-64_0_14_1.deb`

**Comment by lasote** [comment]
Fixed! thanks for report.
