### ISSUE TITLE
Short paths related error when using command line environment variables

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#5883]
I'm seeing error:

> ERROR: Does not exist E:\DevelopBp\mmaguir1\.conan\bde-monolith\3.10.0.0\PORT\stable\package\d5817f13e39c3c4195e51ee5243d672b6c26d94b\conaninfo.txt

But `E:\DevelopBp\mmaguir1\src\mmaguir1\dtl-standalone>conan search` shows:

```
bde-monolith/3.10.0.0@PORT/stable
```

Instead in the relevant directory I have a .conan_link file:

```
E:\DevelopBp\mmaguir1\.conan\bde-monolith\3.10.0.0\PORT\stable\package\d5817f13e39c3c4195e51ee5243d672b6c26d94b>dir
 Volume in drive E is MAGUIRE-E
 Volume Serial Number is 4E18-3B5E

 Directory of E:\DevelopBp\mmaguir1\.conan\bde-monolith\3.10.0.0\PORT\stable\package\d5817f13e39c3c4195e51ee5243d672b6c26d94b

10/08/2019  12:34 PM    <DIR>          .
10/08/2019  12:34 PM    <DIR>          ..
10/08/2019  12:34 PM                32 .conan_link
               1 File(s)             32 bytes
               2 Dir(s)  171,674,419,200 bytes free
```

which has contents:

```
E:\DevelopBp\mmaguir1\.conan\bde-monolith\3.10.0.0\PORT\stable\package\d5817f13e39c3c4195e51ee5243d672b6c26d94b>cat .conan_link
E:\DevelopBp\mam\.conan\585c40\1
```

I do see the conaninfo.txt in the linked directory

```
E:\DevelopBp\mam\.conan\585c40\1>dir
 Volume in drive E is MAGUIRE-E
 Volume Serial Number is 4E18-3B5E

 Directory of E:\DevelopBp\mam\.conan\585c40\1

10/08/2019  12:34 PM    <DIR>          .
10/08/2019  12:34 PM    <DIR>          ..
10/08/2019  12:34 PM               462 conaninfo.txt
10/08/2019  12:34 PM           135,414 conanmanifest.txt
10/08/2019  12:34 PM    <DIR>          include
10/08/2019  12:34 PM    <DIR>          lib
               2 File(s)        135,876 bytes
               4 Dir(s)  171,674,615,808 bytes free
```

I am attempting to override some  settings using the environment variables:

```
E:\DevelopBp\mmaguir1\src\mmaguir1\dtl-standalone>set | grep CONAN
CONAN_USER_HOME=C:\Users\mmaguir1
CONAN_USER_HOME_SHORT=E:\DevelopBp\mam\.conan
```

It is almost as though at some point conan was asked to use `CONAN_USE_ALWAYS_SHORT_PATHS`, started doing so, but then in the context of a rebuild that was forgotten?

Conan version 1.16.1 on Windows Server 2012 R2

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by michaelmaguire** [comment]
This worked when I also `set CONAN_USE_ALWAYS_SHORT_PATHS=True` in my command line environment variables.

So it seems like it was set previously, conan started using Windows short path support and created `.conan_link` files, but when `CONAN_USE_ALWAYS_SHORT_PATHS` was subsequently not set, Conan wasn't willing to recognize that it needed to follow `.conan_link` anymore.

That seems unexpected to me.

**Comment by danimtb** [comment]
Hi @michaelmaguire,

I have done a test reproducing your issue. Unfortunately, this is something expected, as the cache cannot be recalculated everytime the config `use_always_short_paths` is changed. I think this was done by design, as it will be too much effort to keep the cache updated with the changes.

I'd suggest keeping the cache consistent by using the same Conan configuration as much as possible.
Are you currently changing this config in your CI system?

**Comment by michaelmaguire** [comment]
Our CI system has CONAN_USE_ALWAYS_SHORT_PATHS=True and does not have any problems.

My problem comes when I try to use some of our scripts used in our CI system coupled with local development of a particular library I want to customize.  Running the CI script that sets CONAN_USE_ALWAYS_SHORT_PATHS=True and then populates my local cache then going back and in a different window trying to perform other Conan tasks, I run into this issue.

**Comment by danimtb** [comment]
As commented previously this is the expected behavior and a compromise in the short paths feature. We advise you to use the same cache and configuration across the Conan client. Thanks

**Comment by michaelmaguire** [comment]
Is there anything simple you can add to provide a warning when such a switch is detected?

**Comment by danimtb** [comment]
We don't have a warning for that case and I guess it will be difficult to detect when manually editing the *conan.conf* file

**Comment by michaelmaguire** [comment]
OIC.  So there's no way to leave behind a marker that shows one mode was used previously but a different mode is being requested now.

**Comment by danimtb** [comment]
Implementing something like a history state of the Conan configuration could be a way to do it, however it is something we have not considered due to the huge amount of work it will require just to print some warnings.

If you are really interested in this feature please open a new issue with the feature request in order to have it tracked. Hope it makes sense, thanks! 😄
