### ISSUE TITLE
remove option syntax different from help info

### ISSUE THREAD

**Issue by wdobbe** [conan-io/conan#5889]
To help us debug your issue please explain:

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

conan version 1.19.1
os: openSuse Linux 15.1

`conan help remove` shows:
```
usage: conan remove [-h] [-b [BUILDS [BUILDS ...]]] [-f] [-l] [-o]
                    [-p [PACKAGES [PACKAGES ...]]] [-q QUERY] [-r REMOTE] [-s]
                    [-t]
                    [pattern_or_reference]
```

but command
`conan remove -p 1d877a3df840030e6a8abb74c5ffb9088d08b47a zlib/1.2.11@conan/stable`
gives error message:
`ERROR: Please specify a pattern to be removed ("*" for all)`

When I supply the -p option after the package reference :
`conan remove zlib/1.2.11@conan/stable -p 1d877a3df840030e6a8abb74c5ffb9088d08b47a`
the command works correctly.

**Comment by czoido** [comment]
Hi @wdobbe,
You are right, the order could be misleading, but this is an issue of the python argument parser that returns the arguments in that order when requesting help, anyway latter in the help output the positional and optional arguments are listed separately.
Thanks a lot for the feedback.

**Comment by memsharded** [comment]
We have removed multi-value args in Conan 2.0 CLI arguments, so this can be closed as solved.
