### ISSUE TITLE
Support gcc 7.4 in settings.yml

### ISSUE THREAD

**Issue by niosHD** [conan-io/conan#5890]
Conan: 1.19.1

gcc 7.4 is the current system compiler on [Ubuntu 18.04 Bionic](https://packages.ubuntu.com/bionic/gcc) but is not "supported" by conan at the moment out of the box. Considering that Bionic is even a LTS versions I think it is important to add this gcc versions to conan's default `settings.yml`.

For reference, gcc 7.4 was apparently already (released in [December 2018](https://gcc.gnu.org/gcc-7/)). 

Best,
Mario

**Comment by lasote** [comment]
To be released at 1.20
