### ISSUE TITLE
Add conan env variable to conaninfo.txt

### ISSUE THREAD

**Issue by JFreitas9** [conan-io/conan#5892]
- I have read https://docs.conan.io/en/latest/reference/conanfile.html however could not find or interpret something well, so I did not found the solution 

-  Conan version: 1.15.1
- Microsoft Windows 10

I am uploading some files (binaries, documentation, tests results) to artifactory using conan. Basically my recipe, the conanfile.py file, just has the config_options(), configure() and package() methods. The files were generated a long time ago, so they are not built in this conanfile.py
I have them on my pc.

I want to store these old releases files in artifactory (conan repository), and I am able to create the package and upload it. However, adding to that, I would like to add an conan.env.* variable to the packages that I am uploading. (e.g. conan.env.FAMILY=WAYNE?

In artifactory these properties are visible in each conaninfo.txt file inside the packages. Locally I can see them, on the folder where my packages are created.

I can add this porperty manually on artifactory, but I would like to do it locally on my conanfile.py, and once I uploaded the package, this value will also be visible on artifactory.

Is there a way to do this?

**Comment by danimtb** [comment]
Could you explain how do you plan to use the environment variables? Is it for consumers of that package? Or, do you want to reflect in Artifactory that that package was created with that env var?

**Comment by JFreitas9** [comment]
Thanks for the fast answer!
It is for consumers of those packages.

**Comment by danimtb** [comment]
In that case, you have to declare it the `package_info()` with `self.env_info.<var-name>`. That will propagate the env var to consumers when the package is installed

**Comment by JFreitas9** [comment]
Ok, but that does not add the  <var-name> to the conaninfo.txt
How can I get that?

**Comment by danimtb** [comment]
Those are different things. The *conaninfo.txt* file stores the information about the creation of the package, not the information that the package will propagate to consumers

**Comment by JFreitas9** [comment]
Ok! That is what I want. 
Is that possible to do on my case? Like I said I just have the package() method because I am uploading old release files

**Comment by danimtb** [comment]
You can still put that information in the `package_info()` method of your recipe as shown here: https://docs.conan.io/en/latest/reference/conanfile/methods.html#env-info

**Comment by danimtb** [comment]
After no more activity on this issue, I consider the question was answered and closing it. Thank you!
