### ISSUE TITLE
Looking for Azure Pipeline experience

### ISSUE THREAD

**Issue by mathiasi** [conan-io/conan#5906]
Hi,

I've been trying to setup a CI pipeline in Azure Pipeline but I'm struggling a little bit and was looking to see if anyone has gotten a setup up and running. I've seen several CI example with Jenkins but it seems that Jenkins is more suitable for this as the flow can be scripted. It seems to be that the Azure Pipeline is too "static" and the flow can't be altered very much at "runtime".
Our current setup is a mono repository with all of our Conan modules inside and I would like to build only what is necessary depending on the commit and it seems that this is a bit tricky to achieve.
Any experience and suggestions are welcome!

**Comment by memsharded** [comment]
Hi @mathiasi 

I think there two different and separate issues here. One is the usage of Azure pipelines, which might be a bit out of scope in this repo. Yes, I think Jenkins is more powerful than Azure, and allow to do more things. Maybe @uilianries can provide some pointers, or maybe the community in the CppLang slack "conan" channel could help with this.

Another very different question is the usage of Conan in a monorepo, and build what is necessary depending on the commit. I don't have enough context, but I would suggest something in the line:
- For every commit you want to build, you can run a diff, and see what packages changed.
- Do a ``conan export <pkg-folder>`` for each one of the modified ones. You need to define a versioning scheme, if you are using version ranges or package revisions, etc.
- Go to your project/application/root folder, and do ``conan install . --build=missing`` there.
- If you need to parallelize and send packages to build to different slaves, you need to go with the ``conan graph lock`` and ``conan graph build-order`` commands.
- You might want do tune your recipes ``package_id()`` methods, or define a global ``default_package_id_mode`` to define the "re-build" behavior of the downstream packages (when you do a change of one package, do you need the consumers to rebuild for every change? just when the minor or the major version changes?)
- Regarding the source information capture, using exports-sources would make it easier, as packages will capture the sources for later, while the SCM component captures the commit/revision of the whole repo, and will change with every commit if you rebuild the package.

There might not be a single silver bullet, but the flow might depend on the details you want to achieve, how do you want to version your packages, when do you want to rebuild, the scale of your projects, etc. We are working on more examples and use cases, similar to the one described in https://docs.conan.io/en/latest/versioning/lockfiles.html#how-to-use-lockfiles-in-ci, maybe the "monorepo" story is another use case to take into account and try to come up with an example.

**Comment by mathiasi** [comment]
Hi @memsharded 

Agree, this is kinda out of scope for this repo but I figured this might be the best place to get in touch with someone who has experience with this. 

I actually have something working to detect changes. It is based on Git tags and it seems to work OK for now (inspired by https://github.com/jayway/monorepo-azure-pipeline ). Combing that with a Python script that integrates the Conan Python API I'm able to build the ones that has changed in a commit and upload them to Artifactory. However, I realized that I'm missing the whole "cascading build" aspect (e.g. if a header file is changed and it upstream projects needs to be recompiled). I think I can integrate something similar into my Python script but then I quickly looses the parallel-building benefit because everything has to run in the same job, as I'm not able to "spawn" new jobs.

I have experimented with having some yaml definitions generated in the first step and then "injecting" them to be executed in a later stage but it failed. 

I think the mono-repo use-case is definitely worth keeping in mind. We're currently in the early stages of a project, where the goal is to convert a monolith to a modular design and we tried with one repo for each component but it just gave to much headache for the developers. I know there are many opinions on this approach but for now, this is what we have.

**Comment by memsharded** [comment]
> Agree, this is kinda out of scope for this repo but I figured this might be the best place to get in touch with someone who has experience with this.

Yes, totally. Do not hesitate to ask anything here. It is just that we don't use Azure pipelines, so we cannot help much there, this is why I pinged @uilianries too.

> However, I realized that I'm missing the whole "cascading build" aspect (e.g. if a header file is changed and it upstream projects needs to be recompiled). I think I can integrate something similar into my Python script but then I quickly looses the parallel-building benefit because everything has to run in the same job, as I'm not able to "spawn" new jobs.

> I think the mono-repo use-case is definitely worth keeping in mind. We're currently in the early stages of a project, where the goal is to convert a monolith to a modular design and we tried with one repo for each component but it just gave to much headache for the developers. I know there are many opinions on this approach but for now, this is what we have.

Ok, good, understood. We will try to publish some examples that implement this "cascade" re-building for this use case with a monolithic repo. Keep tuned!

**Comment by Adnn** [comment]
We are in the process of evaluating Azure pipeline for our CI needs (hoping to move away from Jenkins and the burden of maintaining all the build node containers ourselves).

@mathiasi are you facing any problem that is specific to the use of **Azure pipelines**? You are mentioning the difficulties of detecting the "cascading effect" on downstream(s), but is not this complication orthogonal to the actual CI system to be used?

**Comment by memsharded** [comment]
Closing this ticket as staled.

We have learned since then that there are Conan users using all major CI systems with success, without much specific challenges of the specific CI platform. Setting a CI for C++ and Conan is challenging, but not because of the platform. Conan 2.0 has got major improvements to help with this, we will be documenting more thoroughly them shortly.
