### ISSUE TITLE
Complete the CMake variables for cpp_info.frameworks

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#5909]
While integrating new changes in #5582, I realized some general variables are missing for frameworks.

Currently, only the `CONAN_FRAMEWORK_<framework>` variable is generated, but there is no variable to iterate the global frameworks or the package's ones. These variables could be useful and should be added for completeness and consistency.

- `CONAN_FRAMEWORKS`: GLobal variable with all the frameworks on the dependency graph.
- `CONAN_FRAMEWORKS_<PKG-NAME>`: All frameworks of the package

Additionally, check the tests that are checking the `CONAN_LIBS_<PKG-NAME>`, as this variable should only contain the package libraries but not the frameworks one. For example: https://github.com/conan-io/conan/pull/5582/files#diff-b50c3899bc268f45979432c9903b5539R343

**Comment by lasote** [comment]
About why are we doing a previous find_library for frameworks: https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
Summary: 
CMake needs to know if "foundation" is a library or a framework, and the only way to achieve it is to do a find_library that will resolve to an absolute path that cmake now knows to recognize as a framework.
