### ISSUE TITLE
[bug] proxy configuration doesn't work according to the docummentation

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#5917]
this issue is mainly a follow up on #4678

conan [documentation](https://docs.conan.io/en/latest/reference/config_files/conan.conf.html) says about proxy configuration:
```
[proxies]
# Empty section will try to use system proxies.
# If don't want proxy at all, remove section [proxies]
```
this is not true (as for conan 1.19.2).
first off, by system proxies, I think we mean proxies specified in Windows Registry or System Preferences:
<img width="780" alt="Screenshot 2019-10-14 at 21 06 11" src="https://user-images.githubusercontent.com/870236/66918247-983c7300-f027-11e9-8cdc-280adc1173bf.png">
![proxy_win](https://user-images.githubusercontent.com/870236/66918260-9c689080-f027-11e9-94f6-e159f51e8b73.png)

conan doc says if you remove the section, no proxies at all would be used, but an empty section will result in the usage of system proxies. it's not accurate, both things have the same behavior in conan right now. I wrote two small tests to illustrate that:
https://github.com/conan-io/conan/compare/develop...SSE4:disable_system_proxy?expand=1#diff-0a53a4e1b8896ffb5724afa52a065b22R36

in both cases, system proxies are used. also, if some environment variables are set (e.g. `HTTP_PROXY`) they are used as well in both cases, and environment variables have a priority over system proxies). such environment variables aren't listed in the [reference](https://docs.conan.io/en/latest/reference/env_vars.html).

the code reading proxies from the config:
https://github.com/conan-io/conan/blob/1.19.1/conans/client/conf/__init__.py#L432
```
        try:  # optional field, might not exist
            proxies = self.get_conf("proxies")
        except Exception:
            return None
        result = {}
        ... # parsing here
        return result
```
it may return `None` (for no section) or an `empty dict` (for the empty section), however, the actual usage of this method makes no difference between them:
https://github.com/conan-io/conan/blob/1.19.1/conans/client/rest/conan_requester.py#L33
```
self.proxies = config.proxies or {}
```

also, from the UX perspective, it doesn't look good - why an empty section and no section have to result in a different behavior? it sounds confusing.

however, below the [documentation](https://docs.conan.io/en/latest/reference/config_files/conan.conf.html#proxies) states a bit different behavior:
```
If you are not using proxies at all, or you want to use the proxies specified by the operating system, just remove the [proxies] section completely. You can run conan config rm proxies.

If you leave the [proxies] section blank, conan will copy the system configured proxies
```
the first sentence appears to be matching to the current design (of both empty section and no section behaviors). also, environment variables affecting proxy settings are mentioned briefly here.

anyway, we have to change either documentation or implementation, or both (?)

/cc @uilianries @jgsogo @czoido @memsharded @lasote @danimtb 

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by danimtb** [comment]
I think first of all we should improve the documentation with the current behavior. Otherwise, this will be misleading to users. The examples you include will be useful to ensure this is the expected behavior.

Regarding the implementation, if I understand it well, there is no difference in the behavior with `[proxies]` empty section and without it, right?

**Comment by SSE4** [comment]
okay, if you can move the issue, would be nice

**Comment by danimtb** [comment]
I think we can keep this one open and contribute the tests you linked to the conan test suite and also add a PR to the docs with the fix. WDYT?

**Comment by SSE4** [comment]
no objections, works for me :)
