### ISSUE TITLE
Add option to CMake helper to avoid CONAN_ variables

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#5921]
From the [documentation](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#definitions), the CMake build helper used in Python recipe set several custom CMake variables.

Now, we are using Conan recipes to build projects whose CMake scripts have no knowledge of Conan (and here is a great feature of Conan: it can be used to build and manage package without any invasion of the existing build system).
Thus, when the `build()` method is executed by Conan, CMake issues the following warning:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
    CONAN_COMPILER
    CONAN_COMPILER_VERSION
    CONAN_CXX_FLAGS
    CONAN_C_FLAGS
    CONAN_EXPORTED
    CONAN_IN_LOCAL_CACHE
    CONAN_LIBCXX
    CONAN_SHARED_LINKER_FLAGS
```
In our situation, these definitions do not seem necessary.
Are we missing something about the best-practice to build such package? Or is there a way to turn these custom definitions off? (without manually removing them from the dictionary one by one ;)

**Comment by Adnn** [comment]
Hi @jgsogo,

  Thank you for your answer, so we are not doing anything wrong when we are calling the CMake build helper on our "Conan un-aware" CMake scripts.
  
> r. Conan won't be able to know which ones are used or not, so we cannot add an option to remove only the variables that aren't going to be used.

That makes a lot of sense indeed. Maybe that could raise another question: one could assume that the vast majority of CMake base projects using Conan will fall in either one of those categories:
* CMake scripts are aware of Conan **and** are using `conan_basic_setup()`
* CMake scripts are not-aware of Conan at all

If that assumption seems about correct, maybe the CMake helpers could have a parameter to **not** define any non-standard CMake variable (essentially, variables starting with `CONAN_`). This way, the recipe implementer could have the possibility, in the recipe, to indicate that the CMake scripts are not aware of Conan, and thus the helper should not define those variables that will end-up unused.

Does that make any sort of sense?

**Comment by jgsogo** [comment]
Yes, it could be a possibility, to add an argument to run a _naked_ CMake helper. 

I can add this as a feature request, but it is not going to take high priority because it is about removing a warning when you are using Conan without using Conan 😅  

Nevertheless, the next step related to this topic should be to use toolchain files (https://github.com/conan-io/conan/issues/5737) that will always take into account `CONAN_` variables (no more warnings, it will be like using always the `conan_basic_setup`).

**Comment by memsharded** [comment]
Closing this ticket as outdated (legacy ``CMake`` generator, removed in 2.0)
