### ISSUE TITLE
[bug] Conan install failing on cross compiling with CentOS

### ISSUE THREAD

**Issue by mohsalxedflix** [conan-io/conan#5923]
I'm trying to cross compile a C++ application on Linux to Windows in a CentOS machine. I have installed gcc, g++, mingw-gcc and mingw-g++. I have attached the log below. However, the issue does not occur when I try to run conan install command in Ubuntu 18.04 with gcc 7.3 and mingw gcc 7.3.
Any help is much appreciated.

### Environment Details (include every applicable attribute)
  * Operating System+version: CentOS 7.7.1908
  * Compiler+version: gcc 4.8.5, g++ 4.8.5, x86_64-w64-mingw32-gcc 4.9.3, x86_64-w64-mingw32-g++ 4.9.3
  * Conan version: 1.19.1
  * Python version: 3.6.8

#### Contents of conanfile.txt:
[requires]
libcurl/7.66.0@bincrafters/stable
OpenSSL/1.1.1c@conan/stable
zlib/1.2.11@conan/stable

[generators]
cmake

#### Contents of linux_to_win64 profile file:
toolchain=/usr/bin/x86_64-w64-mingw32 # Adjust this path
target_host=x86_64-w64-mingw32
cc_compiler=gcc
cxx_compiler=g++

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$toolchain
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
STRIP=$target_host-strip
RC=$target_host-windres

[settings]
os_build=Linux
arch_build=x86_64

os=Windows
arch=x86_64
compiler=gcc

compiler.version=4.9.3
compiler.libcxx=libstdc++11
build_type=Release

#### Command to install
conan install --build="missing" ./conanfile.txt --profile ./linux_to_win64

### Logs (Executed commands with output) (Include/Attach if Applicable)
Current target is windows
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=4.9.3
os=Windows
os_build=Linux
[options]
OpenSSL:shared=False
libcurl:with_openssl=False
[build_requires]
[env]
AR=x86_64-w64-mingw32-ar
AS=x86_64-w64-mingw32-as
CC=x86_64-w64-mingw32-gcc
CHOST=x86_64-w64-mingw32
CONAN_CMAKE_FIND_ROOT_PATH=/usr/bin/x86_64-w64-mingw32 # Adjust this path
CXX=x86_64-w64-mingw32-g++
RANLIB=x86_64-w64-mingw32-ranlib
RC=x86_64-w64-mingw32-windres
STRIP=x86_64-w64-mingw32-strip
zlib/1.2.11@conan/stable: WARN: Package is corrupted, removing folder: /home/saleem/.conan/data/zlib/1.2.11/conan/stable/package/5c347208c5660a7fa0cba07a93e141caf713c3bd
conanfile.txt: Installing package
Requirements
    OpenSSL/1.1.1c@conan/stable from 'conan-center' - Cache
    libcurl/7.66.0@bincrafters/stable from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    OpenSSL/1.1.1c@conan/stable:333bcb280187ae83ca23e6c83367d9dd69098fa1 - Build
    libcurl/7.66.0@bincrafters/stable:333bcb280187ae83ca23e6c83367d9dd69098fa1 - Build
    zlib/1.2.11@conan/stable:5c347208c5660a7fa0cba07a93e141caf713c3bd - Build

Cross-build from 'Linux:x86_64' to 'Windows:x86_64'
zlib/1.2.11@conan/stable: WARN: Build folder is dirty, removing it: /home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd
zlib/1.2.11@conan/stable: Copying sources to build folder
zlib/1.2.11@conan/stable: Building your package in /home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd
zlib/1.2.11@conan/stable: Generator cmake created conanbuildinfo.cmake
zlib/1.2.11@conan/stable: Calling build()
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc -- broken
CMake Error at /usr/local/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/bin/x86_64-w64-mingw32-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd/source_subfolder/_build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/gmake" "cmTC_507ed/fast"
    /usr/bin/gmake -f CMakeFiles/cmTC_507ed.dir/build.make CMakeFiles/cmTC_507ed.dir/build
    gmake[1]: Entering directory `/home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd/source_subfolder/_build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_507ed.dir/testCCompiler.c.obj
    /usr/bin/x86_64-w64-mingw32-gcc --sysroot="/usr/bin/x86_64-w64-mingw32 # Adjust this path"    -o CMakeFiles/cmTC_507ed.dir/testCCompiler.c.obj   -c /home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd/source_subfolder/_build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_507ed.exe
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_507ed.dir/link.txt --verbose=1
    /usr/local/bin/cmake -E remove -f CMakeFiles/cmTC_507ed.dir/objects.a
    /usr/bin/x86_64-w64-mingw32-ar cr CMakeFiles/cmTC_507ed.dir/objects.a @CMakeFiles/cmTC_507ed.dir/objects1.rsp
    /usr/bin/x86_64-w64-mingw32-gcc --sysroot="/usr/bin/x86_64-w64-mingw32 # Adjust this path"      -Wl,--whole-archive CMakeFiles/cmTC_507ed.dir/objects.a -Wl,--no-whole-archive  -o cmTC_507ed.exe -Wl,--out-implib,libcmTC_507ed.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/cmTC_507ed.dir/linklibs.rsp
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find crt2.o: No such file or directory
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find crtbegin.o: No such file or directory
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lkernel32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -luser32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgdi32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lwinspool
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lshell32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lole32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -loleaut32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -luuid
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lcomdlg32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -ladvapi32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmingw32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmoldname
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmingwex
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmsvcrt
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lpthread
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -ladvapi32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lshell32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -luser32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lkernel32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmingw32
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmoldname
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmingwex
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmsvcrt
    /usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find crtend.o: No such file or directory
    collect2: error: ld returned 1 exit status
    gmake[1]: *** [cmTC_507ed.exe] Error 1
    gmake[1]: Leaving directory `/home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd/source_subfolder/_build/CMakeFiles/CMakeTmp'
    gmake: *** [cmTC_507ed/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd/source_subfolder/_build/CMakeFiles/CMakeOutput.log".
See also "/home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd/source_subfolder/_build/CMakeFiles/CMakeError.log".
zlib/1.2.11@conan/stable: 
zlib/1.2.11@conan/stable: ERROR: Package '5c347208c5660a7fa0cba07a93e141caf713c3bd' build failed
zlib/1.2.11@conan/stable: WARN: Build folder /home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd
ERROR: zlib/1.2.11@conan/stable: Error in build() method, line 59
        self._build_zlib()
while calling '_build_zlib', line 110
        self._build_zlib_cmake()
while calling '_build_zlib_cmake', line 85
        cmake.configure(build_dir=".")
        ConanException: Error 1 while executing cd '.' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_SYSTEM_NAME="Windows" -DCONAN_CMAKE_FIND_ROOT_PATH="/usr/bin/x86_64-w64-mingw32 # Adjust this path" -DCMAKE_SYSROOT="/usr/bin/x86_64-w64-mingw32 # Adjust this path" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="4.9.3" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/home/saleem/.conan/data/zlib/1.2.11/conan/stable/package/5c347208c5660a7fa0cba07a93e141caf713c3bd" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev '/home/saleem/.conan/data/zlib/1.2.11/conan/stable/build/5c347208c5660a7fa0cba07a93e141caf713c3bd'

**Comment by jgsogo** [comment]
The error comes from CMake when testing the C compiler. CMake tries to compile a simple application (check it here  https://github.com/Kitware/CMake/blob/master/Modules/CMakeTestCCompiler.cmake#L32) but it fails... That step is executed after the `project(...)` call in your CMakeLists.txt, and it should be before Conan applies any adjustment if you are using `cmake` generator and `conan_basic_setup` (after the `project()`).

Have you tried to compile anything in that machine without using Conan with those compilers, does it work?

Thanks

**Comment by mohsalxedflix** [comment]
Hello Javier, thanks for the response. I'm yet to test that. I'll test and
come back to you. The normal linux application is able to compile without
issues though. This arises only when I'm cross compiling for windows.

**Comment by jgsogo** [comment]
Did you try anything else?

**Comment by mohsalxedflix** [comment]
I tried to cross compile to windows without conan and it works without
issues. This issue still persists when conan cross compiles this package
for windows in CentOS.

**Comment by memsharded** [comment]
Closing as outdated. Everything has changed since then:
- New recipes in ConanCenter
- New cross-build model
- New Conan 2, with new build system integrations and generators.
Please report new tickets against Conan 2 if necessary, thanks for your feedback.
