### ISSUE TITLE
[bug] Minor fixes to virtualenv generators

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5924]
Although there is a major refactor related to Conan virtualenvs (https://github.com/conan-io/conan/issues/5821) there are some minor issues that can be addressed in advance, **they have been marked with a `FIXME` keyword in https://github.com/conan-io/conan/pull/5828/files**

 1. `PS1` is not properly handled in MacOS: https://github.com/conan-io/conan/blob/4217bb326e02e14c8168b080ef1e7a07c18795c8/conans/test/functional/generators/virtualenv_test.py#L188

 2. Trailing blanks with lists: https://github.com/conan-io/conan/blob/4217bb326e02e14c8168b080ef1e7a07c18795c8/conans/test/functional/generators/virtualenv_test.py#L220

 3. Extra separator for list of paths in Windows: https://github.com/conan-io/conan/blob/4217bb326e02e14c8168b080ef1e7a07c18795c8/conans/test/functional/generators/virtualenv_test.py#L245

All of them should be easy to fix and there are tests already available to check they work properly.   **Better if they are fixed in different PRs**.

**Comment by tamarbuta** [comment]
I'd like to give #1 -- PS1 is not properly handled in MacOS -- a try.

**Comment by jgsogo** [comment]
Hi, thanks for your interest. Did you try anything related to this issue?

**Comment by nicememory** [comment]
I'll give a try to 3.
