### ISSUE TITLE
[bug] [windows] Path added to virtualenv is not considered when looking for a program 

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5925]
Although there is a major refactor related to Conan virtualenvs (https://github.com/conan-io/conan/issues/5821) this issue can be addressed first:

 1. Something wrong with the path for CMD: https://github.com/conan-io/conan/blob/4217bb326e02e14c8168b080ef1e7a07c18795c8/conans/test/functional/generators/virtualenv_test.py#L263

**Comment by nicememory** [comment]
I'll take a look.

**Comment by nicememory** [comment]
It is caused since 'where' on Windows returns multiple matched results in priority order.
