### ISSUE TITLE
[bug] Overriding a dependency not present in the graph, gets ignored when installing.

### ISSUE THREAD

**Issue by NokiDev** [conan-io/conan#5929]
### Bug Description

When using "override" feature with a requirement that is not part of the package's graph, the requirement is ignored, and no information related to the ignored requirement is given to the user.
The requirement is not included in the graph either.

It could be great to add a log, or include the requirement even if it's doesn't override anything.

Actual : 
*  conan install runs fine, and is simply ignoring the requirement.

Expected : 
* either a log / error indicating the requirement has been ignored and is present OR include the requirement to the graph as if override wasn't specified.

### Environment Details (include every applicable attribute)
  * Operating System+version:  N/A
  * Compiler+version:  N/A
  * Conan version: 1.19.2
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)

* create a basic conanfile
* add a requirement like : ("Poco/1.9.2@pocoproject/stable", "override")
* run conan install 
* check generated conaninfo file and look for something related to Poco
* check logs of conan install, look for something related to Poco
* Find nothing.

**Comment by jgsogo** [comment]
The way to go is to add a log message, the `override` keyword shouldn't add a dependency.

Nevertheless, it could be more complicated than it looks like because of the way the graph is evaluated: information is passed from one level of the graph to the next one, and it may be hard to know if the _override_ has been consumed or not.

Thanks for submitting the issue.

**Comment by memsharded** [comment]
> Expected : ... OR include the requirement to the graph as if override wasn't specified.

To be clear, that is exactly the opposite of the meaning/design of this feature. It means: "if this dependency is found upstream in the dependency graph, then use better this other version", without needing to worry if it is a conditional dependency and without altering the graph structure.

So I am ok with showing a warning message (if possible, might be a bit too complicated for the value), saying that such an override has not been used upstream, but I don't think it is possible to really add the requirement (to which package, to the declaring one? Then why not defining it without "override", it will override the upstream anyway)

**Comment by memsharded** [comment]
Closing this ticket as outdated. Conan 2 already reports a summary of overrides in the graph
