### ISSUE TITLE
[feature] using conan offline - normaly handle existent file in tools.download (uploader_downloader.py)

### ISSUE THREAD

**Issue by hoxnox** [conan-io/conan#5938]
There are situations where the "conanized" project have to be built offline. In such cases call to `tools.download` inside dependency's recipe will fail. For now there is no way to solve this issue without modifying the recipe. But what if we could just put needed file somewhere in the package directory manualy (for example in `source`) and uploader_downloader will not fail or overwrite it. Offline builds will be possible, if only FileDownloder will use existent file.

For now my team have to modify all recipes to use retrive (https://github.com/hoxnox/conan-nxtools/blob/master/nx_conan_file.py) function instead of tools.download:
```py
    def retrieve(self, sha256, locations, saveas):
        vendor_dir = os.getenv("VENDOR_DIR", "~/.vendor")
        for location in locations:
            try:
                if location[:4] == "http":
                    tools.download(location, saveas)
                elif location[:9] == "vendor://":
                    location = '{vendor_dir}/{location}'.format(location=location[9:],
                                                                vendor_dir=vendor_dir)
                    copy(location, saveas)
                else:
                    copy(location, saveas)
                tools.check_sha256(saveas, sha256)
                self.retrieved_files = (self.retrieved_files, saveas)
                break
            except:
                self.output.warn("Failed to retrieve " + location)
                continue
        if not self.retrieved_files:
            raise ConanException("Error retrieving file. All sources failed.")
```

**Comment by memsharded** [comment]
Related: https://github.com/conan-io/conan/issues/5164

**Comment by lasote** [comment]
Issue #5164 is more related to cache conan packages, not downloaded external files with tools.
It is more related to https://github.com/conan-io/conan/issues/4668
I suggest commenting there and upvoting. @hoxnox That way we can improve the priority of the issue. Thanks!
