### ISSUE TITLE
[question] Shared code and workspaces

### ISSUE THREAD

**Issue by jfischer1** [conan-io/conan#5939]
I have a library A that also exports some headers/cpp (mainly (google) mocks from some interfaces) files as resources for consumers. These public files are installed into resources directory _after_ building. Consumers have to import these files into their cmake binary directory (otherwise, paths tend to get too long for cmake to handle). This worked fine, until I've tried out workspaces with A and a consumer B:
1. 'conan workspace ...' calls install() on A and B. A has not yet been built, therefore, no shared files have been copied to resources directory. Then B tries to import() everything from A's empty resource directory.
2. When building, B's test suite compilation fails due to missing files.

Questions:
I'm a bit reluctant to split A into two packages A and A_mocks because then number of dependencies increase by factor of two and versions can happen to mismatch (e.g., version A gets upgraded, but not the A_mock version in test-suites dependencies). But the sharing process I've described above also seems quite complex and fragile to me. Do you know any 'conanian' way to solve this more elegantly?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Lawrencemm** [comment]
Shouldn't library A be sending those files through `exports_sources`?

**Comment by jfischer1** [comment]
@Lawrencemm: Thank you for your suggestion. As far as I understand it, the export sources mechanism is used to provide the source code for compiling and testing the whole package (=code + regression test code + mock code). There are also mocks that are used only package-internally (i.e., not suitable for re-use). Therefore I want package to export an additional subset of these sources (== only the re-usable mocks). If I would rely on the export sources mechanism, each client would need to sift through all sources and select the mocks.

**Comment by lasote** [comment]
Yes, for the consumers, you would need anyway to package these mocks, so the issue would remain the same. Building first A is not a possibility?

**Comment by jfischer1** [comment]
Yes, building A would definitely solve it. I've done so when I used lib A as editable. But in the context this would mean a change 'workspace  install'. Currently, 'workspace install' calls 'conan install' for all packages of workspace in order of their dependency graph. If we would require dependencies to be built first, then 'workspace install' would need to call 'conan install && conan build' for all packages of workspace. You might skip conan build for root packages.

**Comment by lasote** [comment]
Yes, you are right. I tagged the issue and added to the workspace "project", the workspace feature definitely needs to improve.

**Comment by jfischer1** [comment]
Thank you. Workspaces are a good concept and my colleagues and I definitely need them.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/issues/15992 is centralizing feedback and effort for Conan 2 workspaces, lets close this one and track progress there.

**Comment by memsharded** [comment]
The new Conan 2 ``Workspace`` feature is already out there. Please give it a try, and create new tickets for any question, issue or suggestion.

It is in incubating: https://docs.conan.io/2/incubating.html, so please give your feedback in https://github.com/conan-io/conan/issues/18263 even if everything works smoothly and you have no other comments. Thanks for your feedback!

**Comment by fischjo3SICKAG** [comment]
@memsharded Thank you, I'll try out this feature soon.
