### ISSUE TITLE
[feature] Search for consumers of a package

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#5942]
As a package maintainer there are different scenarios where I'm interested to see who's using my package. Releasing breaking changes for example, checking which platforms I need to support, deprecating a package etc pp.

Within the scope of a Conan Server this information is readily available. A very simple way to get this info would be to scan all available packages for the desired dependency and return that as a JSON list. Though there are certainly better ways to get this information or display the results.

This feature request is about providing a mechanism to show this information to the user. I'm not sure if this is a server feature (and how this could be realized then) or if it's better done within the client.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by monsdar** [comment]
In the past we had a extra service that was scanning our repos and parsing the conanfiles. This was not very maintainable and easy to break though. Not sure if a more sophisticated solution could be used for this task.

I'm curious if this'd be a good native Conan feature though.

**Comment by czoido** [comment]
Hi @monsdar, 
Thanks a lot for the suggestion, although right now it seems to be a little bit outside the scope of Conan it could be an interesting feature for the future but probably more on the server-side.
We'll give it a thought :)

**Comment by monsdar** [comment]
I think this feature could be created by providing a ConanServer-Proxy. Essentially this would be a proxy-remote that sits between the real remote and all the Conan clients. Clients will upload, download etc from that remote which will route everything forward to the real remote.

In the basic version it will just route everything through. But people could extend it with certain functionalities like caching the dependency information of the packages. This info could be made available through a separate API or via an internal webserver. This would fit this issue and provide the desired functionality.

There are many other usecases of such an extension point. Like triggering CI/CD systems whenever someone uploads a package, caching packages from the internet, keeping otherwise incompatible client/server versions backward compatible, etc pp. Just what pops into my head right now. It would not mess with the actual client/server code though, Open/Closed principle fulfilled :)

The basic version could be maintained by the Conan project, thus guaranteeing it to be compatible with the latest Conan releases, quality tested etc. Extensions could be either part of the Conan project or developed by thirdparties.

What do you think?

**Comment by DukeOfKirkcaldy** [comment]
This is also important in CI builds to be able to dynamically determine the root-node that a package will integrate into.

The [how-to docs](https://github.com/conan-io/conan/issues/5942) assume that the _App_ pkg ref is already known when creating the dependency graph lockfile.  The current workaround from @jgsogo  is to [store dependent projects in a file](https://github.com/demo-ci-conan/libA/blob/master/Jenkinsfile#L22), but this is troublesome to maintain as the dependency of the root-node can change during development and might even drop the dependency entirely.  Modifying or updating this `dependent-projects.txt` file then must change the PREV.  This is not desirable as this information does not have any affect on the built package at all.

**Comment by memsharded** [comment]
I am closing this ticket as not planned at the moment. The complexities of tracking the consumers of a package in systems as distributed in Conan, when packages often belongs to different servers are almost untractable, and in any case this would belong to server side, and such feature doesn't even belong in other language package managers that are simpler than conan and have existed for way longer.

Furthermore, we have learned these years that the "consumers of this package" information is not good for CI at all, because of the combinatoric explosion down the dependency graph, and the only CI approach that scales is the bottom-up one, what we call the "products" approach, and is the one being recommended and documented, and we will write more extensive CI documentation for it soon for Conan 2.0
