### ISSUE TITLE
[feature] JSON output for `conan config home`

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#5943]
The command `conan config home` returns the directory where the config resides. Within our CI we use this to clean up before doing `conan config install ...`. Right now we parse the output of that command, but this could be errorprone as outputs sometimes change or are extended with additional information.

This feature request ist about adding a `--json` parameter like all the other commands have.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by theag3nt** [comment]
I'd like to work on this.

**Comment by monsdar** [comment]
Cool! It's enough to just have the path in a JSON file. Same as the output.

István Gazsi <notifications@github.com> schrieb am Sa., 19. Okt. 2019,
23:38:
