### ISSUE TITLE
Missing prebuilt package when using package_revision_mode

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#5949]
Hello,

I'm using Conan v1.9.2 on Debian 10 amd64.

After adding the following line in my `conan.conf`:
>default_package_id_mode = package_revision_mode

I get a `missing prebuilt package error` on a package that is in my cache. Rerunning the **exact same** command works fine.

Here is a minimal reproducible example: 
[package_revision_mode_bug.zip](https://github.com/conan-io/conan/files/3751075/package_revision_mode_bug.zip)

I get no error when `recipe_revision_mode` is used.

**Comment by danimtb** [comment]
Thanks for the information and the minimal example. Indeed, this is a known issue described in #5709. A PR has already been merged for Conan 1.20 release

**Comment by danimtb** [comment]
I have run the script provided with the Conan 1.20 branch and confirmed it is fixed for the next release. Thanks!
