### ISSUE TITLE
[feature] Add option to turn off txt generator

### ISSUE THREAD

**Issue by noverby** [conan-io/conan#5956]
I have created a `tools` generator to install executable tools. 

By calling the following command with the `tools` generator, the `txt` generator  is also activated:
```
conan install ccls/0.20190823.3@username/stable -g tools -if ~/.local/bin
```
Which results in `conanbuildinfo.txt` being installed to the `bin` directory.

It would be nice if there was an option to turn off the `txt` generator.

**Comment by danimtb** [comment]
I think this makes sense and IMO we have been using the txt generator to solve other issues. I think this makes sense but don't know it could be implemented as a opt-out.

Anyway, I am sure we could disable it by default ina future conan 2.0

**Comment by memsharded** [comment]
Certainly, the txt generator will go away in Conan 2.0. At the moment, an option to not generate it seems a bit too much, I'd suggest to remove the file manually as a workaround in the meantime, and we will  take care of this in Conan 2.0.

**Comment by nicememory** [comment]
I review the code and why we add txt generator by default when -g is not empty?

**Comment by memsharded** [comment]
Because the txt generated file is used by other commands (build, package) to recover part of the state. So we injected the txt generator, so the file is always there for those commands to work. This will be cleaned up in 2.0, but at the moment this is difficult to change without breaking.

**Comment by memsharded** [comment]
``txt`` generator completely removed in 2.0, this can be closed.
