### ISSUE TITLE
[feature] Consider generating SOURCELINK files 

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5964]
It seems that it is possible to define https://docs.microsoft.com/en-us/cpp/build/reference/sourcelink?view=vs-2019 this file in the executables to find the sources.

Maybe it could be generated by its own generator, or by the ``visual_studio`` generators (will it work somehow in CMake too?)

cc / @solvingj

**Comment by solvingj** [comment]
When i first read about the feature, I was hoping it would allow us an effective way to point to local directories for sources, either `source` or `build` or `exports`, or even the local file tree if `editable` is being used.  currently, this feature supports only https links. It is extremely short sighted and narrow to implement it this way.  Its a very new feature, so I think it could be worth it to do a feature request to the Microsoft to add the ability to define local file paths.

**Comment by memsharded** [comment]
Never got traction, closing as not planned
