### ISSUE TITLE
[Question] New Conan plugin for TeamCity

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#5968]
I had a need this week for something more complex than a simple `conan create . foo/bar` on our CI server, and I decided it was finally time to learn how to write a TeamCity plugin.

So, here it is! https://github.com/DavidZemon/TeamCity.ConanPlugin

There's still lots more work to do (said work list is only in my head and not documented anywhere... I'll get it documented someday), but it's at least at a _functional_ stage, and worth sharing with you guys and JetBrains.

What I'd like to come from this ticket is that either JetBrains or JFrog take over ownership of the plugin and roll with it. I think (hope) it has strong potential for more than just my organization.

Anyway, please have a look and let me know what you think.

**Comment by czoido** [comment]
Hi @DavidZemon
This is an amazing work, thank you so much!
We will talk to the Ecosystem team about it and let you know 🙂

**Comment by DavidZemon** [comment]
Glad to hear it!

**Comment by DavidZemon** [comment]
I've updated the original description with a new link - this time to my personal GitHub space instead of my (previous) company's space.
And since I no longer work at said company, I'm afraid to say that it's not too likely that I'll be making any more changes to the plugin. I'm more than happy to answer any questions and aid in the transition to the next owner, and if someone would like to start _using_ the plugin then I could probably make some enhancements/bug fixes, but I don't use it for any personal projects and it will therefore sit and rot in my GitHub space until someone else decides to do something with it.

**Comment by memsharded** [comment]
Please @solvingj have a look at this when possible.

**Comment by DavidZemon** [comment]
@solvingj, I'm still happy to answer any questions you may have. I just noticed a few typos in the README (including the fact that the image links were broken) and fixed all of that. That's not to say I'm about to pick up the code and start enhancing it again, but do please feel free to reach out if you need anything.

**Comment by solvingj** [comment]
Thanks @DavidZemon , sorry for the delay. I hope to put my thoughts together about this tonight or tomorrow and get back to you.

**Comment by linkmonitor** [comment]
Has there been any movement on this?

**Comment by dzemon-chwy** [comment]
Not that I'm aware of, but I am still around if anyone needs anything or finds a bug.

**Comment by DavidZemon** [comment]
Not that I'm aware of, but I am still around if anyone needs anything or finds a bug.

**Comment by memsharded** [comment]
I am afraid this never got enough traction, closing this as not planned.

Also, other CI plugins like the Artifactory-Jenkins plugin are being deprecated. Calling ``conan xxx`` commands directly from the CI scripts is typically easier and more convenient, less layers to learn and manage (and fight bugs with), so the value of the plugins was little compared with the effort. Specially now with Conan 2.0, that contains custom commands to automate things at the Conan level, and also a more complete json output for more commands.
