### ISSUE TITLE
[question] How do I extract/edit conan file details from given path to the conan_file.py

### ISSUE THREAD

**Issue by ranifisch** [conan-io/conan#5977]
I am using the conan_api.py to do conan operations to build/create/remove/upload artifacts.
as part of my code, I need to extract and edit a conan file from a given path(without creating the Conan object)
Is this possbile using the current API?

**Comment by memsharded** [comment]
Hi @ranifisch 

The conan_api.py is basically a python equivalent to the command line, but it doesn't provide any deep internal details. Not sure if you mean editing the file just on memory, or you want to edit the file on disk. In any case Conan does not provide any utility for that (the closest thing would be ``conan inspect`` to see attributes of a recipe, but not what you want). 

I would suggest going to a template engine like jinja and some python scripts that would manipulate/create conanfiles before feeding them to conan.

**Comment by ranifisch** [comment]
Hi @memsharded 

Thank you for the reply!

Seems like I'll have to manipulate them before feeding them, like you said ;)
