### ISSUE TITLE
[feature] CMake build helper should allow selection of host=x64 toolset option

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#5979]
When building with CMake and the Visual Studio generator it is necessary to pass the toolset option `host=x64` to CMake so that Visual Studio uses the 64bit compiler/linker executables. It is not an implicit choice by VS, it always selects the 32bit executables if not instructed otherwise. Currently we have to configure that in the recipes because Conan does not support this setting in the toolset attribute:

```
cmake = CMake(self)
args = None
if self.settings.os == "Windows":
  args = ["-T", "host=x64"]
cmake.configure(args=args)
```

This should be a separate selectable option on the build helper and the default for x86_64 hosts.

### Environment Details (include every applicable attribute)
  * Windows 10
  * Visual Studio 2015
  * Conan version: 1.19.2
  * Python version: 3.7.2

**Comment by lasote** [comment]
The executables are x86 even if the Generator is `Visual Studio 14 2015 Win64`?

**Comment by jasal82** [comment]
No, it's not about the executables that are being built. The `host=x64` option selects the 64bit linker and compiler executables to be used for building.

**Comment by jasal82** [comment]
See also https://cmake.org/cmake/help/v3.8/generator/Visual%20Studio%2015%202017.html

**Comment by memsharded** [comment]
Hi @jasal82 

I am not sure that is a but, as stated in the linked docs:

> By default Visual Studio chooses the 32-bit variant even on a 64-bit host. One may request use of the 64-bit host tools by adding host=x64 to the toolset specification:

Then I would not consider that a bug, but consistent with the tooling defaults. I wouldn't mind to have an option in the ``CMake`` helper that adds it if it applies, but I think I wouldn't call this a bug, but a feature request. Did I understand it correctly?

**Comment by lasote** [comment]
> It's not about the executables that are being built. The host=x64 option selects the 64bit linker and compiler binaries to be used for building. Otherwise, it uses the 32bit ones even if the generator is set to 64bit.

In that case, I totally agree with @memsharded. Conan defaulting to x86 tools matches with the default of CMake/VS, and also, changing the default would be breaking behavior. I agree we could improve the interface of the `CMake` build helper for that.

**Comment by jasal82** [comment]
I agree, it's probably not a bug. There should still be a way of selecting the host tool architecture from the profile. So that would be the feature request then.

**Comment by aleksandrkolesnikov** [comment]
Hello. If I am not mistaken you can choose host like this
`cmake = CMake(self, toolset = f"{self.settings.compiler.toolset},host=x64")`

**Comment by cedriclaplace** [comment]
Hello,

Is there something new about this feature request ?

We are looking to use the 64b version of VS compiler/linker. We are using the CMakeToolchain and CMakeDeps generators with the CMake wrapper from conan.tools.cmake. It seems we cannot configure the toolset as specified in the CMake documentation from Conanto invoke the 64b compiler/linker. We tried different things but the generated CMAKE_GENERATOR_TOOLSET value remains unchanged without the host parameter. I have read the CMakeToolchain code and haven't seen anything usefull, maybe I read it wrong or miss something.

It would be appreciated to be able to set this information from the profile used when building, with a parameter like compiler.toolset.host or something.

As a workaround, we set the environment variable PreferredToolArchitecture before building but we don't think it is the best approach.

Thank you for your answer.

**Comment by memsharded** [comment]
Hi @cedriclaplace 

As your comments have different base from the above, as they are using the new build system integrations, I think it is best if you posted a new issue with this. Also, I would strongly recommend to try to reproduce starting with the ``conan new hello/0.1 --template=cmake_lib``. There might be something missing to opt-in/out into which compiler and linker you invoke, irrespective of the ``settings`` one (the host architecture), so I would also recommend to use the ``--profile:build`` to specify the architecture of the host, as by default it would make sense to use it. If not enough, then that might mean that we need to add a conf to be able to select this.

**Comment by memsharded** [comment]
Closing as outdated (referring to the legacy and removed in 2.0 ``CMake`` integration). For new integration, please open new tickets as necessary.
