### ISSUE TITLE
[feature] Disable system proxies from Conan

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5980]
This PR kind of solve it but it is pretty hacky and as it is commented in the PR, it could have side effects.
https://github.com/conan-io/conan/pull/5922

I don't see this done unless we have a better and clear interface from the requests library to achieve it. I think that exceeds the Conan competences.

**Comment by AbrilRBS** [comment]
After the Conan 2 release, requests is still not providing a way to handle this from their public api cleanly, so it's better not to risk the breaking behaviours mentioned here and in the linked PR, closing as wont-do

**Comment by memsharded** [comment]
The ``trust_env`` is now documented, if this issue comes back again, we can define a ``conf`` that allows setting the ``Session.trust_env`` variable.
