### ISSUE TITLE
[question] How to update package to latest RREV from remote

### ISSUE THREAD

**Issue by Crejan** [conan-io/conan#5990]
Hi,
i currently faced a strange behavior when working together with others.
I have an old package, recipe and source export on artifactory and i fixed a bug by uploading a new version of this package with a fixed source file. The version gets deployed as expected, but the users that already got a downloaded version of the old version do not get the updated one. 
I expected that `conan install ref --update` should check the remotes for the latest revision and download the new source, but it keeps the old one in the cache. The only think that helped was to purge the packet from the conan cache manually for every user.

How am i supposed to get the latest revision with the latest source if there is already one in the cache?

I also tried it with conan version 1.19.2

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Crejan** [comment]
yes, its about a new revision. the revision is existing in artifactory.
I think the problem occured, because the client was first configured with `enable_revisions=0` in conan.conf, but then enabled the revision feature after the cache was already populated.

**Comment by lasote** [comment]
Yes, it could happen. When the revisions mechanism is not enabled all the revisions from/to the server are "0" even if in the server are stored correctly.
So, enabling the revisions solved the issue?

**Comment by Crejan** [comment]
I did not see the described issue any more after switching to revisions enabled.
Thanks!
