### ISSUE TITLE
default user_home_short missing '~'

### ISSUE THREAD

**Issue by grimgort** [conan-io/conan#5992]
hello.

line 62 from windows.py : default CONAN_USER_HOME_SHORT path is ".conan". need to write "~/.conan".

thanks

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by memsharded** [comment]
Hi @grimgort 

Could you please specify the details, like the Conan version you are using, and what would be the steps to reproduce the bug?

**Comment by grimgort** [comment]
I'm sorry about that request. I simply changed "user_home_short = None" in "~/.conan/conan.conf".  
you can close this request.

**Comment by memsharded** [comment]
Good, thanks for following up and reporting!
