### ISSUE TITLE
[feature] Allow different cpp_info.name depending on the generator

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#5993]
Something similar to `self.cpp_info.name['my_generator']` should work.
Make it compatible with `cpp_info.name = 'name'` syntax

Related to #5984

**Comment by ledocc** [comment]
I'm on it

**Comment by lasote** [comment]
@ledocc if you finally start implementing this, please unlock your branch so we can help. That is a core conan so it is no easy to understand how deep has to be tested or implemented.

**Comment by lasote** [comment]
To simplify the implementation we propose to keep the `name` and introduce `names` as the dict for the generators. Otherwise, getting the `str` from the `cppinfo.name` it is very problematic and requires ugly code. The `names` is much more pragmatic.

**Comment by ledocc** [comment]
How to handle package that produce one pkg-config/config.cmake by library ?
icu create icu-i18n.pc, icu-io.pc and icu-uc.pc

**Comment by memsharded** [comment]
@ledocc Managing internal details within a package would be part of the ``components`` feature. There was a PR open for this, but it was a bit risky and was put on hold at the moment. We would eventually resume work on the ``components`` feature, but not a priority at the moment.
