### ISSUE TITLE
Explicitly installing same package for both host and target

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#5998]
Lets assume that the same project is being both compiled natively for x86_64 Linux, and cross-compiled for aarch64 Linux on x86_64 Linux host.

Further, lets say the project's build depends on a package DepPackage. Both target and host versions are needed for successful build (host for included binaries, used as part of compilation).

Is it possible to force the install of both host and target versions of DepPackage from conanfile.py, and reference them separately?

**Comment by memsharded** [comment]
Hi @w3sip 

I am not sure what you mean. Typically you cannot have 2 binaries of the same package in the same dependency graph with a different architecture, unless one of them is a ``build_require`` and intended to be run exclusively in the build machine during the build process, but not in the host system.

What Conan can do perfectly is to manage binaries for different architectures. You can have your App package depending on your DepPackage. Both of them can be created with a different architecture and when you are creating the package for "App", it will automatically and correctly use the right binary of "DepPackage" that matches the architecture you are using, without any kind of conflict. "DepPackage" can have any number of different binaries for different configurations installed at the same time in the same Conan package cache.

**Comment by w3sip** [comment]
What if both of them are `build_require`? The dependency package in question is CUDA, and needed both for target (libcudart_static etc), and for the host (nvcc/ptxas binaries).

**Comment by memsharded** [comment]
Just in case, to make sure I understand correctly, we are using the GNU triplet naming:

-build: the machine we are building
-host: the machine that will run the code
-target: the machine that will be targeted by the code running in the host (applies mostly to compilers)

Do you mean that you need the host libraries (a static lib)? That is not a build-require. A build-require is mostly for tooling that do not affect the binary that is being produced (e.g. cmake). The other (nvcc) looks like for the build machine, and yes, that could be a build-require.

While in theory it is possible to use exactly the same package for both contexts (build and host), there are a few rough corners for that so we are trying to improve that use case.

In the meantime, I think the best approach is to package the compilers and the libraries separately. Create a Conan package called ``nvcc``or the like, for the compiler, that you can build-require, and another one with the libraries, like ``cuda``, for a normal require.

**Comment by w3sip** [comment]
Okay -- was hoping to avoid duplicating the package under different aliases, but I guess there isn't currently a way to do it differently.

**Comment by memsharded** [comment]
The new ``self.tool_requires("pkg/<host_version>")`` syntax allows to define the same version dependency for an already existing requires in the "host" context of the form ``self.requires("pkg/1.2.3")`` (or even a version-range), and then the ``tool-requires`` will resolve to the same version of the ``requires``, and there will be 2 dependencies of the same package, but one in the build context and the other in the host context.

I think we can close this ticket as solved.
