### ISSUE TITLE
Add more information to generators, for each dependency

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6]
Include variables/data for project dependencies, as:

- Each dependency root folder, so it can be used for FindXXX.cmake
- ...

**Comment by Manu343726** [comment]
I would consider an output JSON with all the conanfile.py variables. That JSON can be simply parsed at the cmake side (Or any other tool). This could also be a first step on IDE integration, by exporting all package information (Path, libs, deps, source files, etc; all the info conan is actually using internally to process the package) in a format (JSON) any tool can easily work with.

**Comment by memsharded** [comment]
Ok, I think it is a good idea to generate json output for third-party tools. What I do not understand is what you said about JSON can be simply parsed at cmake side. Why generate json to be parsed by CMake? There is already a "cmake" generator that generates native cmake variables, no need to parse anything. Is there something I am missing about this point?

**Comment by Manu343726** [comment]
Nope, you are right, I just meant that if conan had such a generic JSON interface, maintianing cmake generators would not be needed, since you would be able to parse the JSON output from cmake to get the info.

**Comment by memsharded** [comment]
I still don't get it. Parsing JSON and generating the required cmake variables using cmake is not an obvious issue, or is it? Generating the CMake file is really straightforward. Why should the .cmake generator be removed and provide a .json generator, making the task more difficult to cmake users?

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/commit/6bd43f440a79c0337e5700d18ab22ac9d63cb8ce defines a new variable SET(CONAN_{dep}_ROOT) pointing to the package root.

**Comment by memsharded** [comment]
The information has been added, I think this issue can be closed. @Manu343726 if you really want a JSON generator, please open a new issue with that name specifying a bit the use case, thanks!
