### ISSUE TITLE
[Question] How are dependencies handled when using "--build '*'"

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#6005]
Let's imagine the following:

Project A has no dependencies and has been released twice: 1.0 and 2.0.
Project B depends on A/1.0 and has been released once: 1.0.
Project C depends on A/2.0 and B/1.0.

If I run `conan install path/to/project/c --build '*'`, obviously A and B will be built, and specifically A's version will be 2.0 (because C override's B's dependency on A/1.0). But the question I want confirmation on is this: when B gets built, will it build against A/1.0 or A/2.0? I would hope A/2.0, but would appreciate confirmation on that.

**Comment by jgsogo** [comment]
Hi! When Conan builds the graph of dependencies there is only one node per library name, so in your example there will be only one `A` (if not, we should investigate it and it is much likely a bug, please report if you see something different).

Feel free to suggest a place in the docs where you've expected to find this information.

Thanks!

Extra ball.- This limitation (only one version per reference-name) lead to [this workaround](https://github.com/conan-io/conan-center-index/blob/master/recipes/7zip/19.00/conanfile.py#L33) in `7zip` recipe, where we'd need an older version to generate the new one
Extra ball.- The new crossbuilding model will create two nodes in the graph if the library is requested from different contexts (build_machine and host_machine, if different), so Conan will generate/use two different binaries.

**Comment by DavidZemon** [comment]
I'm VERY glad to hear about the crossbuilding model. This is something that bit us a while ago and the work around wasn't as pretty as we'd hoped.

You've answer the question nicely. I may get around to doing some explicit tests in the future, but this is all I needed to at least move forward with my plan. Thanks.
