### ISSUE TITLE
[feature] Get information about rebuild-candidates

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#6016]
When building a complex component there often are multiple versions of indirect dependencies involved. Ex: Boost uses bzip2/1.0.0 while Protobuf uses bzip/1.0.1. When I want to use Boost and Protobuf within my component, Conan notices the version difference and overwrites one with the other (oftentimes recompiling the dependencies in that process).

Within a CI environment I would like to know about these inconsistencies so I could trigger a rebuild myself. Or do certain things before letting Conan rebuild everything.

Conan already prints warnings whenever dependencies get overwritten by other packages. This feature request is about providing a way to know beforehand which parts of the build-order are not fitting with the rest of the dependency tree and would need to get rebuilt.

I'm not sure about a good implementation. It could be additional info within the `conan graph lock` JSON output or an entirely new command within `conan graph`.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @monsdar 

For triggering re-builds the current approach would be a combination of:

- Defining the ``default_package_id_mode`` that you want. You can force re-builds of packages when the dependencies change the minor, the patch or even the revision. This will force the rebuild of the component that gets a different version than the one that it was built with. Please check https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#changing-the-default-package-id-mode
- ``conan graph lock --build=xxxx`` will let you capture a lockfile that will be ok for the build argument
- ``conan graph build-order . --build=xxxxx`` will give the things to be rebuilt, according to the ``--build`` argument and the ``default_package_id_mode``

The two last commands need to have the same ``--build`` arguments, but it is likely that we will try to improve that in the future releases.

**Comment by monsdar** [comment]
I'm not sure if I fully understood.

Say I'm having a package dependency tree like this:

* `zlib/1.0.0` <- `boost/1.1.1` <- `CompA/1.0.0`
* `zlib/1.0.0` <- `CompB/1.0.0`

I'm using `default_package_id_mode=full_version_mode`. Now I create a conanfile.txt like the following:

```
[requires]
CompA/1.0.0
CompB/1.0.0
boost/1.1.2
```

I'm changing `boost` and I'd like to know which packages need to get rebuilt (CompA in this case). This is not working out with the approach you listed, is it?

Conan knows about the dependencies that get overwritten. There are warning like "Warn: Dep of CompA/1.0.0 boost/1.1.1 is overwritten by your conanfile to boost/1.1.2" (or something similar). I think it should be possible to get that information out via an extra command.

**Comment by memsharded** [comment]
> I'm changing boost and I'd like to know which packages need to get rebuilt (CompA in this case). This is not working out with the approach you listed, is it?

Yes, that is exactly the idea of the package id modes.
If you enable ``full_version_mode``, when you build CompA/1.0.0 linking with boost/1.1.1 you get a PackageID1 for CompA. If the dependency graph changes for any reason, and now CompA/1.0.0 is linking with boost/1.1.2, you will get a different PackageID2, and a binary will not exists. Using the ``conan graph build-order . --build=missing`` it will tell you that you need to build CompA/1.0.0.

Please tell me if this makes sense. Thanks!

**Comment by monsdar** [comment]
Yes, this totally makes sense. Sounds like exactly what I'm looking for. We'll switch over to Conan 1.20 soon, then put in `conan graph` into the system. 👍

**Comment by monsdar** [comment]
Ok, just trying out a few things today and I did not get the results I was expecting. Here's what I did:

* Set `default_package_id_mode = full_version_mode` in conan.conf
* I'm having a package for **CompA**, like the following:

```
Boost/1.69.0+abcdefgh.GL11@user/release
^
MyDep/1.0.0+abcdefg.GL99999@user/stable
^
CompA/1.0.0+abcdefgh.GL99999@user/release
^
CompA/LATEST-master@user/release (alias)
```

* And there's a package for **CompZ** like the following:

```
Boost/1.69.0+abcdefgh.GL11@user/release
^
MyDep/1.0.0+abcdefg.GL11@user/stable
^
CompA/1.0.0+abcdefgh.GL11@user/release
^
CompB/1.0.0+abcdefgh.GL11@user/release
^
CompZ/1.0.0+abcdefgh.GL11@user/release
^
CompZ/LATEST-master@user/release
```

* I have the following conanfile.txt:

```
[requires]
CompA/LATEST-master@user/release
CompZ/LATEST-master@user/release
```

* Now I want to know what'd need to be rebuilt within conanfile.txt. I'm expecting CompB and CompZ, as CompA/LATEST-master is aliasing to CompA/1.0.0+abcdefgh.GL99999.
* I'm doing `conan graph lock --build=missing -pr vs2013_64_Release conanfile.txt -l graph.lock`
* Followed by `conan graph build-order --build=missing graph.lock --json graph_order.json`
* However I get the following unexpected output. It contains The whole CompA build tree (including CompA with the aliased version) and the additional stuff from CompB and CompZ that I'd have expected:

```
Boost/1.69.0+abcdefgh.GL11@user/release
^
MyDep/1.0.0+abcdefg.GL99999@user/stable
^
CompA/1.0.0+abcdefgh.GL99999@user/release
^
CompB/1.0.0+abcdefgh.GL11@user/release
^
CompZ/1.0.0+abcdefgh.GL11@user/release
```

I'm having a few questions:
* Did I understand something wrong, or is there something I've overlooked?
* I thought about the versions only differing in metadata, with the same SemVer for every package. But as my conanfile.txt contains the Alias for CompA/...9999 I'd say it should use the correct version, shouldn't it?

**Comment by AbrilRBS** [comment]
Sorry for not following up in this issue, we should have communicated better. For anyone seeing this issue in the future, I'll just drop some notes:
- The general approach shown above is correct in Conan 1.
- Conan 2 simplifies this a bit, you can call `conan graph info ... --format=json` and check for `"binary": "build"`, those are the packages that would need to get built
- `conan graph build-order` works the same, but [now it's much more powerfull](https://docs.conan.io/2/reference/commands/graph/build_order.html#conan-graph-build-order) and will correctly return the expected result in all situations 

Again, sorry we didn't get back earlier, we should have communicated a bit better :)
