### ISSUE TITLE
"conan user" is broken in 1.20.0

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#6023]
17:52:59 alex@Totem:/ $ conan user -c
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: /Users/alex/.conan/settings.yml.new
WARN: ****************************************
17:53:04 alex@Totem:/ $ conan user -r REMOTE -p PASS USER
ERROR: {
  "errors" : [ {
    "status" : 401,
    "message" : "Authentication is required"
  } ]
}. [Remote: REMOTE]

The exact same commands succeed after downgrading to 1.19.3.

**Comment by memsharded** [comment]
Yes, sorry about that, we have introduced a bug in 1.20. Prepared this fix here: https://github.com/conan-io/conan/pull/6022, and will be released asap in Conan 1.20.1

Thanks very much for reporting.

**Comment by lasote** [comment]
1.20.1 has been released
