### ISSUE TITLE
[feature] Support ConfigVersion.cmake files

### ISSUE THREAD

**Issue by liarokapisv** [conan-io/conan#6025]
We are extensively using CMakePackageConfigHelpers's [write_basic_package_version_file](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#command:write_basic_package_version_file) in our codebase as an extra verification step for our dependencies. We are following some sort of semantic versioning where version numbers provide info about backwards compatibility. It is a nice way to lock down versions and guard against incorrect dependency version upgrades. 

The CCI currently bans all configuration files which prevents one from using the `find_package(Lib VERSION X)` syntax since there are no version files available. I consider this jinxing the normal CMake usage as it is. Banning the Config.cmake files is not that problematic since with the upcoming `cmake_find_package_multi` generator the generic problem should be solved but unfortunately the generator does not seem to support these version files so there is currently so solution for using the `VERSION` syntax in the roadmap. 

I think there are two solutions here. One is to unban `ConfigVersion.cmake` files from the CCI. The ban was mostly due to the `Config.cmake` files making the job of conan as a package manager harder. I don't think this is the case with the `ConfigVersion.cmake` files. Another is to support generating such files via the `cmake_find_package_multi` generator. This has the advantage of being able to use semantic version control for non-cmake packages. But I think that in this case we should be able to at least support `CMakePackageConfigHelper`'s functionality. Not sure how to support custom version files but I think these are rare as it is.

**Comment by liarokapisv** [comment]
This is similar to #5888 in scope, should I close this one?

**Comment by memsharded** [comment]
Hi @liarokapisv 

Thanks for the report. Yes, it makes sense to improve that, and your suggestions are good. Can't say right now if it is better to generate them or to allow them, I would say that sounds better to generate them to integrate other build systems better.

Yes, I think this would be covered in the other issue, lets follow conversation there, better centralize discussion in one place. Thanks!
