### ISSUE TITLE
[bug] Astroid requires six 1.12

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#6029]
Hi!

The current list of requirements has a conflict, due six version installed by Conan and what is required by Astroid package.

Conan installs the latest six version, 1.13.0, however, Astroid requires 1.12.0 as fixed version.

I opened a PR to Astroid project to update six version. It should be enough for our case: https://github.com/PyCQA/astroid/pull/719

### Environment Details (include every applicable attribute)
  * Operating System+version: Any
  * Compiler+version:
  * Conan version: 1.20.1
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
- pip install conan

### Logs (Executed commands with output) (Include/Attach if Applicable)

https://ci.appveyor.com/project/bincrafters/conan-gettext/build/job/nhmo4vndueux6x31>

**Comment by lasote** [comment]
Released Conan 1.20.2
Pending to backport to previous Conan versions during the day.

**Comment by ericLemanissier** [comment]
Does that mean conan 1.20.2 (and all backports you will do) will break as soon as https://github.com/PyCQA/astroid/pull/719 is merged and released ?

**Comment by lasote** [comment]
> Does that mean conan 1.20.2 (and all backports you will do) will break as soon as PyCQA/astroid#719 is merged and released ?

Hope not! Why would it?

Released `1.7.6`, `1.8.5`, `1.9.3`, `1.10.3`, `1.11.3`, `1.12.4`, `1.13.4`, `1.14.6`, `1.15.5`, `1.16.2`, `1.17.3`, `1.18.6` and `1.19.4`

**Comment by ericLemanissier** [comment]
because then [astroid will require six==1.13](https://github.com/PyCQA/astroid/pull/719/files#diff-1e8a54c814195e2e0b781b5c41b2bf58R26) and [conan six==1.12.0](https://github.com/conan-io/conan/commit/476032e4f54edec6c64acc285a03e90905cbe4a7#diff-37885be8e16baf1d68f08f4273221d7bR8)
