### ISSUE TITLE
deps_env_info not available from source method

### ISSUE THREAD

**Issue by abuszta** [conan-io/conan#603]
I just noticed that deps_env_info is not available from conanfile.py source method. This causes that python code reuse implemented in #474 (which is really neat and useful feature!) will unfortunately not work. Is it possible to implement this somehow?

E.g. this will not work right now:
```
def source(self):
    with tools.pythonpath(self):
        from my_package import downloader
        downloader.get("protocol://my_fancy_url")
```

**Comment by memsharded** [comment]
I have extended one existing test, and this works:

```python
from conans import ConanFile, tools

class ToolsTest(ConanFile):
    name = "Consumer"
    version = "0.1"
    requires = "conantool/1.0@lasote/stable"
    generators = "virtualenv", "env"

    def source(self):
        with tools.pythonpath(self):
            import mytest
            mytest.baz(self.output)

    def build(self):
        with tools.pythonpath(self):
            import mytest
            mytest.foo(self.output)

    def package(self):
        with tools.pythonpath(self):
            import mytest
            mytest.boom(self.output)

    def package_info(self):
        with tools.pythonpath(self):
            import mytest
            mytest.bar(self.output)
```

The main problem could be that ``source()`` is not callable in a user space project. If this is the case, that would be issue #604, and this one could be closed.

**Comment by abuszta** [comment]
It works when you install with Consumer/0.1 as dependency, but I think it will not work when you execute "conan source Consumer/0.1@abuszta/testing"...

But anyway, I agree that this issue is coupled with #604, so we can close this one and continue discussion there to keep it clean.

Thanks for being so helpful! You are doing great job here :)

**Comment by memsharded** [comment]
Thanks to you, you are giving good feedback, complete and detailed reports, and helping a lot in the process. Being a maintainer of such a project is not always easy, because it is very hard to do a generic tool that perfectly fits all people and all workflows, so compromises and trade-offs have to be continually made. But interactions like yours are great, so lets keep working together to improve conan :)
