### ISSUE TITLE
[bug] apple frameworks broken with cmake

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#6035]
When trying to build static version of conan-glib/2.58.3@bincrafters/stable on macos, the test recipe fails to link because [it uses link flags](https://travis-ci.com/bincrafters/conan-glib/jobs/253077883#L5712) `-framework Foundation -framework Foundation -framework Foundation` instead of `-framework Foundation -framework CoreServices -framework CoreFoundation` [as specified in conanfile.py](https://github.com/bincrafters/conan-glib/blob/stable/2.58.3/conanfile.py#L138)

### Environment Details (include every applicable attribute)
  * Operating System+version: Mac OS X 10.14.4
  * Compiler+version: apple clang 10.0
  * Conan version:1.20.2
  * Python version:

### Logs (Executed commands with output) (Include/Attach if Applicable)

[conan 1.19.1: success](https://gist.github.com/ericLemanissier/5a2fcca7faf51f7c4ef69cec0c92eabb)
[conan 1.20.2: failure](https://gist.github.com/ericLemanissier/116fe4d43d642470cdd141508b4ac033)

**Comment by danimtb** [comment]
Looks like this could be a issue related to latest refactor about frameworks with the CMake macro `conan_find_apple_framworks()`

**Comment by jgsogo** [comment]
https://github.com/conan-io/conan/pull/6042 has been released in 1.20.3 and it is already available in pypi (type `pip install -U conan`). It should fix this issue.

Thanks for noticing it.
