### ISSUE TITLE
[question] Specifying options via command line

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#6038]
I have a package that defines several options and provides default values. When I specify a value for 1 option via command line (within an install or create command, for example) I get an error about the other options until I include them on the command line as well.

Is that the expected/desired behavior? It would be nice to be able to specify a value for a single option via command line, allowing defaults within the package's conanfile.py to be used for others.

Thanks

**Comment by jgsogo** [comment]
Hi, @radonish. I cannot reproduce the issue you are reporting, can you provide an example?

If I have:

```python
from conans import ConanFile, CMake

class HelloConan(ConanFile):
    name = "hello"
    ...
    options = {"shared": [True, False], "option2": [True, False]}
    default_options = "shared=False","option2=False"

```

and run

```bash
conan create <path/to/conanfile.py> <reference> -o name:shared=False
```

it works...

**Comment by radonish** [comment]
Hello, @jgsogo - thank you for the quick response. I figured out that my problem is related to the test package (I glossed over the error message too quickly previously and missed it was unhappy about the test package). 

My structure is as follows:

mylib/src
mylib/include
mylib/unit_tests
mylib/conan_package (contains conanfile.py)
mylib/conan_package/test_package (contains test conanfile.py)

Error looks something like this:
`conan create /path/to/mylib/conan_package mylib/1.0.0 -o myoption=test`
...
```
ERROR: /path/to/mylib/conan_package/test_package/conanfile.py: 'options.myoption' doesn't exist
Possible options are ['shared', 'fPIC']
```

mylib/conan_package/conanfile.py contains:
```
    options = {"shared": [True, False], "fPIC": [True, False], "myoption": "ANY"}
    default_options = {"shared": True, "fPIC": True, "myoption": "test"}

```
mylib/conan_package/test_package/conanfile.py contains:
`options = {"shared": [True, False], "fPIC": [True, False]}`

The test_package options appear to be the problem. Even if I add "myoption" option to it, Conan is unhappy until I specify every option in the command line. I started with the bincrafter's template for test_package that has no options specified in the test package's conanfile.py - I reverted to that and it fails as well, complaining that no options exist.

**Comment by jgsogo** [comment]
Yes, this is a known problem, and it's not so easy to fix 😓 . I think that the best issue to track it is this one: https://github.com/conan-io/conan/issues/2406

When there is a `test_package` that _testing recipe_ is the root of the graph and options without scope are applied to it. If you want your options to be applied to the package itself you need to run :

```
conan create /path/to/mylib/conan_package mylib/1.0.0 -o mylib:myoption="test"
```

otherwise, it will look for `myoption` in the `test_package/cnanfile.py` and it will complain that one is not an available option.

I'd suggest you move any further comment to that issue, the more attention it gets the higher the priority 😉

**Comment by radonish** [comment]
I appreciate the information - I'll follow/contribute to #2406. 

Thanks!
