### ISSUE TITLE
[feature] Edit settings file 

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#6043]
Hi!

Conan provides the [config](https://docs.conan.io/en/latest/reference/commands/consumer/config.html) command, which is able to edit and read the configuration file. Also, it provides the install feature, which can download new files and replace the current settings, hooks, configuration ...

However, when I want to edit my settings file, adding a new compiler, arch or cpp standard, I need to edit directly into the file. Unfortunately, sometimes I break the YAML format, so I need to re-generate the default settings. Of course, I should have created a backup before editing, but you know ...

A safer way to avoid this kind of situation, just like when editing the config file, is using the `conan config` command, which is able to handle any file safely.

For instance:

    # I want to add gnu++2a for gcc
    conan config get --settings compiler.gcc.cppstd
    [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20]

    conan config set --settings compiler.gcc.cppstd=gnu++2a

    conan config get -s compiler.gcc.cppstd
    [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20, gnu++2a]

Just like when adding a new hook to the configuration file, the `set` option is able to append a new standard in cppstd list.
  
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I wouldn't mind something that easily displayed the current settings. 

But besides that, I think it doesn't make sense to invent a whole new command line syntax to avoid editing a yaml file, which will be far more complicated than editing the conan.conf file. It is necessary something to add values, to add dicts, to add vector of values... too complicated (plus future maintenance, docs, etc) for the value.

**Comment by jgsogo** [comment]
I don't think it is too complicated if we limit the scope to add/remove values from the final nodes of the YAML file (not to the structure itself), those nodes are `lists` and it'd probably cover 99% of the use cases.... but I'm not aware of anyone requesting it until now, so let's see if it gets some traction.

---

Maybe we can improve the error when we have an invalid `settings.yml` file, right now we get an ugly traceback -> https://github.com/conan-io/conan/issues/6044
