### ISSUE TITLE
[workspaces] conanworkspace.cmake not generated if install step builds something

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#6046]
To reproduce this, just clear your build folder then run `conan workspace install` with a `--build` argument of one of the dependencies.

The `conanworkspace.cmake` isn't output to the build folder.

This seems to occurr any time the workspace install command has to build anything from sources.

Running the workspace install a second time without building anything then outputs the conanworkspace.cmake correctly.

**Comment by czoido** [comment]
Hi @Lawrencemm,
I couldn't reproduce the issue, please could you give us some more information on what version of Conan you are using, the OS and how is your project structure?
Thanks a lot!

**Comment by Lawrencemm** [comment]
Oh ok, looks like it's just my project.

Currently using conan 1.20.3. I've seen this issue for a long time, maybe since 1.17 or something.

Please follow these steps:

* clone this project: :https://github.com/LM-Engine/workspace
* run `init.py`
* run `conan config install conan/common`
* run `mkdir build && conan workspace install . -if build --build missing`
* `conanworkspace.cmake` will be missing from the `build` directory.

**Comment by czoido** [comment]
Hi @Lawrencemm,
Thanks a lot for the information :) 
I could reproduce the issue with your steps and have a look at the issue.
