### ISSUE TITLE
[bug] Overriding a requires() with a build_requires() in a downstream does not work anymore

### ISSUE THREAD

**Issue by fourbft** [conan-io/conan#6047]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux, but should not matter
  * Compiler+version: None
  * Conan version: 1.19.2 and 1.20.2 are affected, 1.18.1 is not
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
I have three packages: CA, CB and CC. CB uses CA as requires(). CC uses CB as requires() and CA as build_requires() but in a different version. When I then create the package CC, I get the following error message:

```
ERROR: Conflict in CC/3.0.0@user/testing
    Requirement CA/1.0.1@user/testing conflicts with already defined CA/1.0.0@user/testing
    To change it, override it in your base requirements
```

To reproduce, you can use the following three conanfiles:
CA/conanfile.py:
```
from conans import ConanFile

class SpecificConanfile(ConanFile):
    name = "CA"
    description = "CA test component."
    url = "http://CA.html"
    version = "1.0.0"
```
Create the package via `conan create . user/testing`. Then update the version number to 1.0.1 and create another version of this package.

Then create CB via this conanfile.py:
```
from conans import ConanFile

class SpecificConanfile(ConanFile):
    name = "CB"
    description = "CB test component."
    url = "http://CB.html"
    version = "2.0.0"

    def requirements( self):
        self.requires( "CA/1.0.0@user/testing")
```
Then create CC via this conanfile.py:
```
from conans import ConanFile

class SpecificConanfile(ConanFile):
    name = "CC"
    description = "CC test component."
    url = "http://CC.html"
    version = "3.0.0"


    def build_requirements( self):
        self.build_requires( "CA/1.0.1@user/testing")


    def requirements( self):
        self.requires( "CB/2.0.0@user/testing")
```
The creation of CC will fail with the above error message.

Yes, it is questionable, if it makes sense to use CA as requires() in one package and as build_requires() in a downstream package. But as people here are often not too familiar with conan and with the difference between requires() and build_requires() and because we used to have problems with alias packages in build_requires(), we currently have quite a good mix of both. And the above situation used to work until conan 1.18.1. So it might be some sort of regression.

We'll work around this by making the use of build_requires() consistent for all packages (i. e. if a package is build_requires() somewhere, we make it build_requires() in all of its consumers - or if it is not really a valid candidate for build_requires() we'll make it requires() everywhere). That cleanup is certainly a good idea, anyway, but I still wanted to let you know about this bug/regression/problem.

**Comment by lasote** [comment]
I would say, in this case the actual behavior is the correct one. CA could propagate a header or any other thing in both cases that will end up in a real conflict in CC.
Could I ask what is CC and what is suppose to propagate to CB (as a require) and to CC (as a build require?) I mean, this is a tool, a library, both, how they link.. etc. Maybe there is a better approach for this situation and I would love to learn your usage.

**Comment by fourbft** [comment]
In one concrete case, CA was some CMake related stuff (some convenience *.cmake files containing CMake macros). But we have the same situation with CA being googletest and/or googlemock. Of course, these should be build_requires() in CB, too. As I said, for several reasons, our use of build_requires() and requires() for these packages is not very consistent. We fixed this in our components, now.
But the behavior of conan 1.18 was different here. It allowed to override a requires() in an upstream (CB) with a build_requires() in the downstream (CC) (with the usual warning about overriding).
In Conan 1.19 and 1.20 this situations now results in an error. And at least the error message is misleading here. It sais: `To change it, override it in your base requirements` - but that's exactly what caused the error. The base requirement is the one in CC, isn't it. And that tried to override it - with a build_requires() however. If CC overrode CA with a requires() statement, then it would work. Also overriding works, if CA is a build_requires() in CB. Only the mix of build_requires (in a downstream) and requires (in an upstream) does not work anymore in Conan versions 1.19 and up.

**Comment by memsharded** [comment]
Closing as outdated. Conan 2 completely changed the dependency graph resolution, including overrides, conflicts, etc.
Please create new tickets against Conan 2 if necessary, thanks for the feedback.
