### ISSUE TITLE
[question] Wildcards for when the ABI doesn't matter

### ISSUE THREAD

**Issue by brianthelion** [conan-io/conan#6049]
For certain binary artifacts -- firmware, bootloaders, device trees, etc. -- the ABI is largely irrelevant.  Nonetheless, we want to distribute conan recipes for these artifacts. Unfortunately, it seems that the `build()`-time `settings` and `options` are rolled into the `package_id`, preventing the pull of the binary artifacts into mismatched environments at `install()` time. Given the ABI-agnostic nature of the artifacts, forcing a rebuild is nonsensical.

What seems appropriate here is wildcard syntax for scrubbing anything that may adversely impact the `package_id` in these scenarios. Under the hood, the wildcards would simply be stripped from `self.info.{settings,options}` before calculating the `package_id`.

1. Is there already a best practice for handling the scenario of ABI-agnostic recipes?
2. If not, is there any reason that wildcards are a bad idea?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by brianthelion** [comment]
Note this this is a somewhat different than the [1 build -> N packages](https://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-build-n-packages) problem, though I do appreciate the use of "Any" thereabouts.

**Comment by puetzk** [comment]
Either remove items that don't matter to you from your package's settings = "os", "compiler", ... line,
or, if you want to know at build time but they don't affect the produced binary package (perhaps you use it for tests, or to fill in environment variables, or some such), you can strip information in the package_id function before it is hashed.

There's no wildcard syntax, but you can do anything you'd like in python logic, and simply saying
del self.info.settings.compiler isn't much longer than somehow saying compiler = "*", while allowing pretty much any flexibility you can think up.

https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=package_id#defining-package-abi-compatibility
