### ISSUE TITLE
The 'conan info' command is a little slow

### ISSUE THREAD

**Issue by guestliu** [conan-io/conan#6050]
The 'conan info' command is a little slow, just like the following, it will take about 0.6s every time
There are many modules in my project and I check the conan packages every time( if it has been built, don't build it any more). The check action takes about several minutes
In this case, 1.5 minutes.
I can't find any way to speed up. 
Why 'conan info' is a second-level action?

**Comment by lasote** [comment]
In the first scenario, every conan command (try the same with `--help`) take about half a second to run, this is because of python mostly, all the imports are followed and it takes time. This is very hard to improve. 

About the `conan info`, it is almost doing the same as the `conan install` but at recipe level (without binaries). The reason is, you need all the recipes, build the graph and propagate all the information. Also, for each computed binary package, the server is ping to check the `conaninfo.txt` and inform about if the binary is missing, has to be downloaded etc.

I would like to understand better why/when are you doing that check. Could you describe what is your   development flow? Thanks

**Comment by guestliu** [comment]
The package we can trust will only be built on the build machines (it's a remote publishing action not local build) and the git revision will put onto to the channel. The package name just like this: 
zip/1.0@master/r-1239dfdf

So, the conanfile.py will change constantly. We use another file to describe the dependencies and generate the conanfile.py dynamicly, our self-defined module files doesn't include the revision.
Just like logic view(our self-defined config) VS  physical view(conan)

But, it's not friendly to cmake users for the cmake cache variables, if we alwalys changed the package folder position , we often have to remove the whole build folder that will take us many time to rebuild the whole project.

Out team split the develeping action into two types, one for dev another for publishing and integration.In dev mode, all package name is username/dev, just like:
zip/1.0@guest.liu/dev

We should check if it's on the remote or local cache(copy it to channel 'dev') or build from the source(we use google repo to manager the all modules' code, if user 'repo sync amod bmod', so amod bmod should be built instead of use conan package, but conan can't understand it)

It's difficult to execute a single command "connan install" to achive these goals.

**Comment by lasote** [comment]
Thanks for the explanation. Have you considered using [revisions feature](https://docs.conan.io/en/latest/versioning/revisions.html) to avoid the reference changes?

> We should check if it's on the remote or local cache(copy it to channel 'dev') or build from the source(we use google repo to manager the all modules' code, if user 'repo sync amod bmod', so amod bmod should be built from code instead of use conan packages. But conan can't understand it)

I don't fully understand this part :( could you elaborate a bit more?

**Comment by guestliu** [comment]
If you are familiar with 'google repo', I think it will be easy to understand.
A brief introduction: 'Google repo' use a manifest.xml to define multiple git projects (with git repo branch and reivision), use 'repo sync' to clone all the codes, 'repo start' to start a change on multiple projects and 'repo upload' to upload all the diff.

Our build system works on the whole repo, a whole-repo version consists of multiple git project with its branch and reivsion. Developers use the latest ok version of the whole repo, not a latest version of a module.There must be a specific; revision in the connanfile.py 'requereis' section, in this condition, "the 'revision feature' to avoid the changes" doesn't make sense.

**Comment by lasote** [comment]
Interesting, thanks. How about the lockfiles? Might it make sense to use them to keep the modules evolving separately? (https://docs.conan.io/en/latest/versioning/lockfiles.html)[docs lockfiles]

**Comment by guestliu** [comment]
I just read it carefully and I have a question.

In the document, lockfile is create by the command 'connan install ' in the beginning.
The dependencies are on conan-server waiting to download in this time.

But in my case, in the beginning there aren't any modules on conan-server. I generate the whole build tree graph from the repo code, how can I get a lockfile without conan-server in the beginning?

**Comment by lasote** [comment]
If you have a local cache populated it should work too. To generate "the first" lockfile you can use `conan graph lock` command.

**Comment by memsharded** [comment]
Closing this as stale, please create new tickets if necessary.
