### ISSUE TITLE
[question] mingw_installer  best practice?

### ISSUE THREAD

**Issue by davidtazy** [conan-io/conan#6055]
should build_requirement of mingw_installer should be defined in profile or in component recipe?

for example, 
openssl-recipe in conan-center_index, mingw_installer is no in recipe
icu in bincrafters , mingw_installer is defined in recipe

thx

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
It is a good question. I would say, in general, the recipes shouldn't force something like a compiler unless its usage is very very unusual, like OpenSSL is (or was) doing with NASM in Windows. I prefer the profiles to declare the environment.
