### ISSUE TITLE
[feature] `deploy`  generator - add option to deploy package without dependencies

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#6056]
The deploy generator was largely born out of the following feature request: 

https://github.com/conan-io/conan/issues/3280

The generator achieves most of the request.  However, it still looks like one part of the feature request was unfulfilled, and we still want it, so re-filing it in the context of the generator. 

In short, the current behavior deploys the entire dependency tree.  There are of course use cases for this, however in our simple case we just want the contents of `package_folder` for the project we're deploying.  

I currently do not see any way to achieve this.  Generators don't take parameters so there's no way to achieve it via parameters.  Thus, the only way I can think of to achieve this is with an environment variable... something like: 

`CONAN_GENERATOR_DEPLOY_DEPENDENCIES=False` 
or
`CONAN_GENERATOR_DEPLOY_INCLUDE_DEPENDENCIES=False` 
or whatever. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
I think we approached the deploy generator as a generic solution to the deployment issue, meaning that we didn't want to be too restrictive or intrusive in the final deployment layout. Finally we end up with just a bulk copy of the package folder contents, leaving the responsibility of "post-processing" those contents to the final users.

So here I see two alternatives:

- Pros process the contents of the deploy generator and leave only the project you want.
- Write a custom generator that only deploys the last node of the dependency graph.

**Comment by danimtb** [comment]
ping @solvingj

**Comment by solvingj** [comment]
Sorry for delay.  We can close as "unsupported".
