### ISSUE TITLE
[bug] virtualenv sh generator should re-root absolute paths

### ISSUE THREAD

**Issue by rweickelt** [conan-io/conan#6061]
Environment
  * Operating System+version: Windows 10
  * Conan version: 1.19.1
  * Python version: 3.7.3
  * Git Bash (Msys2-based)

When running ``conan install . -g virtualenv`` from within a msys2-based shell,
- absolute paths have a wrong root
- path separators are not sanitized

Especially the ``PATH`` variable is important:
```
PATH="C:/Users/xxxx/.conan/data/xxx/bin":"C:\Users\xxxx\.conan\data\yyy\bin"${PATH+:$PATH}
export PATH
```

Above line breaks the ``PATH`` environment variable entirely.

This has been discussed here in #2568, but the suggested implementation has not made it into upstream. Instead, #3376 has been chosen which does not respect above aspects.

It was suggested by @niosHD in  #2568 to use a config option for the re-rooting behavior. I would second this. The current implementation makes conan unusable for us in GIT Bash on Windows.

Is there a better solution?

Here is my current workaround:

```py
from conans.client.generators import VirtualEnvGenerator
import platform

class Msys2VirtualEnvGenerator(VirtualEnvGenerator):
    @property
    def content(self):
        files_content = super(Msys2VirtualEnvGenerator, self).content

        if platform.system() != "Windows":
            return files_content

        replacements = [
            ('C:\\', '/c/'),
            ('c:\\', '/c/'),
            ('c:/', '/c/'),
            ('C:/', '/c/'),
            ('\\', '/')
        ]

        files_content = super(Msys2VirtualEnvGenerator, self).content
        for file_name, file_content in files_content.items():
            if not file_name.endswith('.sh'):
                continue

            for r in replacements:
                file_content = file_content.replace(*r)

            files_content[file_name] = file_content

        return files_content
```

**Comment by danimtb** [comment]
We are working on the refactor of virtualenv generators in #5989 that will probably improve the current state.
