### ISSUE TITLE
[question] Binary packages and recipes in separate locations

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan#6062]
We have the following situation:

We build an application with a large number of dependencies with custom options and settings. We cache the binary packages for these dependencies on a local Artifactory instance for the following reasons:

1. Speed of build. Binary packages often do not exist on conan-central for the specific options we have, and CI builds everything from scratch using a Docker image.

2. Network issues. Often when running on CI, there are network problems when downloading remote packages so we need our own package cache.

For this to work, we have our remotes set so that our local Artifactory is always searched first.

The problem we have, is that by doing this we have no way of knowing if the corresponding package on conan-central has become outdated, which often results in hard to debug errors caused by outdated recipes.

We 'solve' this problem by periodically refreshing our Artifactory cache.

The question:

*Is it possible to have a recipe and binaries on different remotes?* I think our problem would be solved by always checking conan-central for the latest recipe, but using our local remote for the binary package if the recipe has not become outdated.

**Comment by memsharded** [comment]
Hi @planetmarshall !

> Is it possible to have a recipe and binaries on different remotes? I think our problem would be solved by always checking conan-central for the latest recipe, but using our local remote for the binary package if the recipe has not become outdated.

There could be different approaches to your issue:

- With package revisions, yes, the recipe and the binary can come from different remotes. This will likely become the default in Conan 2.0, but in the meantime, it is an opt-in, you should explicitly activate revisions in the client. But binary packages are bounded to an exact recipe revision if using revisions, so recipes in the different repositories should be in-sync (you cannot mix binaries from different recipe revisions). I would recommend having a look to resolve those issues to virtual and remote Artifactory repositories directly in the server (they also require package-revisions activated)

- If you depend on your binaries in production, I think I would really try to keep on-sync with the recipes in conan-center, by forking the recipes repos (the new conan-center-index?), and having your own CI build your binaries from the updated recipes. It is the best way to be sure what is being built, to achieve better reproducibility and traceability. Specially if for some recipes you do your own changes.

Please tell me what you think. Thanks!

**Comment by planetmarshall** [comment]
The second approach is what we're *almost* doing but we may not be doing it consistently which is where we're running into dependency issues. We've also recently run into problems where a lot of package maintainers have started using the optional `user/channel` syntax

The first approach sounds interesting but needs a bit more investigation on our part. I think in the immediate term we'll stick with the first approach and I'll let you know how we get on. I may share some of our CI scripts so you can see what we're doing and if we're doing anything that could cause issues.

Thanks for your help.

**Comment by AbrilRBS** [comment]
Cleaning old issues, closing as we didn't hear back from you since then :)
