### ISSUE TITLE
[feature] Allow conan to provide cookie to repository

### ISSUE THREAD

**Issue by timbrown5** [conan-io/conan#6066]
We have an Artifactory instance which behind an Oauth2 reverse proxy and so doesn't understand basic auth. As such we are finding it impractical to download packages from it.

It would be nice to be able to provide a parameter, e.g. `--cookie "token=xxx"`, to Conan which would be used on all HTTP requests. This would allow us to get through the proxy using a cookie.

**Comment by danimtb** [comment]
Hi @timbrown5 and thanks for the suggestion.

Conan should work well with an Artifactory instance behind a reverse proxy. Is the Artifactory instance behind a reverse proxy or just the Oauth2 service? Which version of Artifactory are you using?

**Comment by timbrown5** [comment]
Hi,
Sorry for my late reply.
Out Artifactory instance is behind a reverse proxy which relies on OAuth2 for authentication. If a user isn't logged in they cannot see the Artifactory page or API.
I have tried registering my OAuth2 user with the Conan remote and get:
```
ERROR: 403: Forbidden. [Remote: conan-remote]
```
I guess I assumed this is due to OAuth2 not allowing Basic Authentication, but maybe I'm wrong.
I am using Artifactory 6.13.1 and Conan  1.20.3

**Comment by timbrown5** [comment]
I have just updated by conan through `pip` (now on 1.20.4) and same issue. I did find the wiki page for logging to a file so here is the log output:
```
{"_action": "COMMAND", "name": "authenticate", "parameters": {"password": "**********", "remote_name": "conan-remote", "skip_auth": false}, "time": 1574932440.229296}
{"_action": "COMMAND", "name": "get_remote_by_name", "parameters": {}, "time": 1574932440.232291}
{"_action": "REST_API_CALL", "duration": 0.09271788597106934, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.20.4 (Python 2.7.15rc1) python-requests/2.22.0", "X-Client-Anonymous-Id": "**********"}, "method": "GET", "time": 1574932440.326668, "url": "https://artifactory.sourcevertex.net/api/conan/conan-remote/v1/ping"}
{"_action": "EXCEPTION", "class": "ForbiddenException", "message": "403: Forbidden. [Remote: conan-remote]", "time": 1574932440.327473}****
```
I can navigate to `https://artifactory.sourcevertex.net/api/conan/conan-remote/v1/ping` in my browser, but only once I am logged in to OAuth2.

**Comment by danimtb** [comment]
Having a closer look at the code, the recommended way to do this in python is using `requests-oauth` https://github.com/requests/requests-oauthlib

But we are not using this library to handle OAuth requests. This will probably be a point for a plugin architecture in Conan so you can eventually use a custom python requester here https://github.com/conan-io/conan/blob/master/conans/client/rest/conan_requester.py#L27 and using the `OAuth1Session` from the library above.

So I'd say Conan is currently not prepared to handle Oauth2 with Artifactory AFAIK

**Comment by timbrown5** [comment]
Thanks for having a look at this. Do you have an idea when either Conan
might support this or support plugins/extensions? Or support providing a
cookie?

**Comment by danimtb** [comment]
@timbrown5 it will have to be planned for a release and we still don't know if it will require any change in the Artifactory side, so we have to evaluate it first and then plan.

Meanwhile, you can use Access Tokens in Artifactory. Those are supported in Conan and can be expired and managed in a similar fashion. Thanks

**Comment by timbrown5** [comment]
Hi Daniel,
Thanks for the response. I will see if access tokens suit our needs.
Kind regards
Tim

**Comment by danimtb** [comment]
Finally, this feature will require the correct management of oauth with Conan API in the Artifactory side. Maybe the same procedure used for Access Tokens

**Comment by danimtb** [comment]
@timbrown5 just for clarification, when you said Oauth2, you meant that you have the Oauth2 configured in Artifactory as described in here https://www.jfrog.com/confluence/display/RTF/OAuth+Integration ?

**Comment by timbrown5** [comment]
We have a reverse proxy which handles login and passes the user name to
Artifactory. The only configuration we added was adding an Nginx reverse
proxy config to HTTP Settings.

The only way I see authorisation tokens working is for us to us to tell the
proxy to all anyone to try to access the repo urls but to use token as the
method of authorisation.

**Comment by danimtb** [comment]
I haven't tried a similar setup myself so I am not sure if that should work out-of-the-box with Conan

**Comment by timbrown5** [comment]
I was looking at this again and wondering how Conan tries to authenticate with the Artifactory server, is it with Basic Auth? If so we were thinking we can allow Basic Auth request through the proxy to Artifactory which would allow us to use Conan.

**Comment by danimtb** [comment]
Yes, it uses Basic Auth. You can check the details in the code https://github.com/conan-io/conan/blob/a872fad79ac2ae2df282ba1f81b17fead726b820/conans/client/rest/rest_client.py#L110

**Comment by timbrown5** [comment]
Sorry to keep asking questions, but does Conan use Authentication for **all** requests (if there is a user for a given remote)?
I ask because I am having problems adding a user - I get a 403 when it tries to access `<my-server>/api/conan/conan-local/v1/ping`. I was thinking it could be because conan is trying to access that location without including Basic Auth (or specifically it seems our proxy isn';t seeing an `Authorization` header).

To test this I tried doing a curl to the location that conan seems to be accessing. When I did a curl to `<my-server>/api/conan/conan-local/v1/ping`:
 - without credentials I get a 403 (same as I see with `conan user add` command).
 - with invalid credentials I get a 401.
 - with connect credentials I get a 200.

I'm not 100% that not providing Basic Auth is the only reason we would get a 403, but if it was bad credentials I believe conan should be failing with 401 (same as curl)?

**Comment by timbrown5** [comment]
Sorry, answered my own question by using the trace log:
```
{"_action": "COMMAND", "name": "authenticate", "parameters": {"password": "**********", "remote_name": "conan-local", "skip_auth": false}, "time": 1576147060.920432}
{"_action": "COMMAND", "name": "get_remote_by_name", "parameters": {}, "time": 1576147060.923322}
{"_action": "REST_API_CALL", "duration": 0.08773016929626465, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.20.4 (Python 2.7.15rc1) python-requests/2.22.0", "X-Client-Anonymous-Id": "**********"}, "method": "GET", "time": 1576147061.012792, "url": "https://artifactory.dev.sourcevertex.net/api/conan/conan-local/v1/ping"}
{"_action": "EXCEPTION", "class": "ForbiddenException", "message": "403: Forbidden. [Remote: conan-local]", "time": 1576147061.013645}
```
It seems to be using an `Authorization` header. Guess I need to do some digging.

**Comment by timbrown5** [comment]
Ok, after a little more debugging it appears that maybe this is a bug in conan.
Steps:
1) Run local http server on machine using proxy:
`python -m SimpleHTTPServer`
2) Run tcpdump on local machine and use it r print out headers:
`sudo tcpdump -vvv -A -i lo0  port 8000`
3) Run a conan user command and check the headers in the output of `tcpdump` (from 2).
`conan user -p test -r local-repo user`

Doing this we see that `tcpdump` receives these headers:
```
Host: localhost:8000
User-Agent: Conan/1.16.1 (Python 3.7.0) python-requests/2.22.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
```
Note there is not `Authorisation` header. Here is the trace log for the came command:
```
{"_action": "COMMAND", "name": "authenticate", "parameters": {"password": "**********", "remote_name": "local-repo"}, "time": 1576150601.185415}
{"_action": "COMMAND", "name": "get_remote_by_name", "parameters": {}, "time": 1576150601.1887949}
{"_action": "REST_API_CALL", "duration": 0.008514165878295898, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.16.1 (Python 3.7.0) python-requests/2.22.0", "X-Client-Anonymous-Id": "**********"}, "method": "GET", "time": 1576150601.1996539, "url": "http://localhost:8000/v1/ping"}
{"_action": "EXCEPTION", "class": "NotFoundException", "message": "Not implemented endpoint. [Remote: local-repo]", "time": 1576150601.2005131}
```
It claims to be adding the `Authorization` header.

To check the method we also ran a curl request (providing a user):
`curl -L -u test:user http://localhost:8000`

The curl request shows it actually sends the `Authorization` header:
```
Host: localhost:8000
Authorization: Basic dGVzdDp1c2Vy
User-Agent: curl/7.54.0
Accept: */*
```

**Comment by memsharded** [comment]
Hi @timbrown5 

I think there were a couple of things fixed in latest Conan versions related to the authorization headers. Could you please try the same with latest Conan too? Thanks.

**Comment by timbrown5** [comment]
Hi @memsharded,
I re-ran this test with Conan version 1.21.0 and found similar behaviour. The headers for this version were:
```
Host: localhost:8000
User-Agent: Conan/1.21.0 (Python 3.7.0) python-requests/2.22.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
X-Client-Anonymous-Id: 1845e9be746b413149615eba87602fce7f30fdb5
X-Client-Id: 
```

**Comment by timbrown5** [comment]
Sorry I have forgotten to comment. We are using Conan 1.22.2 and this is fixed. Also tring 1.27.1 and we are still able to authenticate with Artifactory, so I am closng this.
