### ISSUE TITLE
[bug] scm Attribute fails to clone commit

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#6068]
I feel like this is very related to https://github.com/conan-io/conan/issues/5587 "scm Attribute fails to clone tag" but in our case we are using version 1.19.2. which according to the note in #5587 "Conan 1.18.1 has been released with the fix for this issue!" should contain the fix.

Our old conanfile that worked in v1.16.1 did:

```
    scm = {"type": "git",
           "url": url,  # location of source to build
           "revision": commitAtVersion}
```

But now after upgrading to v1.19.2 it failed to check out any sources on our build servers.  But if we comment out the `scm` section and add:

```
    # Testing: don't use scm in case it's broken https://github.com/conan-io/conan/issues/5587
    def source(self):
        git = tools.Git()
        os.remove("debian/changelog")
        #git.clone(self.url, branch=self.commitAtVersion)
        git.clone(self.url, branch="master")
        git.checkout(self.commitAtVersion)
```

then it works also in v1.19.2

Our commitAtVersion was a git commit string of the form e.g. `8aa1740b` 

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows Server 2012 R2
  * Compiler+version: VS2015
  * Conan version: 1.19.2
  * Python version: N/A conan exe installer

### Steps to reproduce (Include if Applicable)

Update code from 1.16 to 1.19 and rebuild an existing recipe that uses the scm plugin while requesting a specific git commit.

### Logs (Executed commands with output) (Include/Attach if Applicable)

(Sadly) silent fail of the git clone to actually check out any files, build fails shortly afterwards as it can't find required .sln file to build:

```
pal/1.41.0@PORT/stable: Configuring sources in E:\nX\nX_nightlybuild\workspace\Conan_pipeline\.co\14e36c\1
pal/1.41.0@PORT/stable: Getting sources from url: 'git@bbgithub.dev.bloomberg.com:nx/pal.git'
[...]
The following files were specified on the command line:
	vstudio/pal/pal.sln
These files could not be found and will not be loaded.Microsoft (R) Build Engine version 14.0.25420.1
```

**Comment by michaelmaguire** [comment]
Brainstorming: in the above example I show the line:

```
        os.remove("debian/changelog")
```

This was needed because in our `base = python_requires` class we `exports` that file:

```
class conan_shared_python_requires(ConanFile):
    name = "conan_shared_python_requires"
    version = "0.0.8"
    exports = "debian/changelog" 
```

If I did not delete that, `git.clone` failed because of the presence of a file with the name "debian/changelog" already in the source directory where it wanted to perform the checkout.

Is it possible that scm was failing for the same reason?  If so, since we haven't changed that `exports` behaviour and it was working in v1.16, could something have changed in the behaviour of `exports` that broke this?

**Comment by lasote** [comment]
Yes, might be related. I'm going to try to reproduce. Could you confirm if it still fails in Conan 1.20? Can you reproduce it easily?

**Comment by michaelmaguire** [comment]
We reverted to 1.16.1 on our Jenkins server, and the same recipes now succeed again.

We only seem to see the problem under Jenkins.

>  Could you confirm if it still fails in Conan 1.20? Can you reproduce it easily?

There is an SRE ticket involved to a different team in order to update our build server.  Can you give me a specific change I can point them at to justify the cost?

**Comment by lasote** [comment]
I cannot. Just wondering if you could help to confirm the bug persist. I cannot reproduce the issue, and I cannot understand how the git clone (or any other git command) can fail without Conan failing. :(

**Comment by lasote** [comment]
Might be related to the git version installed in the Jenkins machine? Could you check?

**Comment by michaelmaguire** [comment]
I will report back with the specific git version we are using.  To reiterate, the problem is reproducible on our Jenkins server with Conan v1.19.2, it does not occur with v1.16.1.

**Comment by michaelmaguire** [comment]
We are using MSYS2 git version 2.16.2

**Comment by lasote** [comment]
If I prepare a custom Conan package from v1.19.2 and another from v1.16.1, both printing information about the git commands run, outputs etc, would you be able to run to compare the output in your CI failing machine/s? I'm not able to reproduce it.

**Comment by michaelmaguire** [comment]
@lasote that would be great!

**Comment by michaelmaguire** [comment]
After trying suggestions @lasote sent, I can confirm we've been broken by new `scm` `"Shallow"=True"` default. ( https://github.com/conan-io/conan/pull/5514/ )

If I add  `"Shallow"=False"` to a recipe, the `scm` checkout works in our Jenkins servers again.  I do not know why this problem only shows up on our Jenkins server jobs.

Our package versioning is documented in https://github.com/conan-io/conan/issues/4139 -- we try to read package version from debian/changelog version and checkout exactly the commit specified that went into that version.  

So if the most recent entry in our `debian/change` is:

```
coollib (0.0.10.4) unstable; urgency=low

  * 7b84a69 awesome feature3
  * 23d7f40 awesome feature2
  * 84b4d2b awesome feature1

 -- Michael Maguire <dontusemyemail@youspammers.net>  Tue, 11 Dec 2018 07:02:18 -0500
```

We would set Conan package version to "0.0.10.4" and try to check out at commit `7b84a69`.

Note that the last commit in the repo, however, will usually be commit that added that last `changelog` entry itself -- I don't know if this is what causes `--depth 1` to run into problems.

Is it too late to ask that the default behaviour be changed back to  `"Shallow"=False"` ?

**Comment by lasote** [comment]
Thanks. No, it is not too late. We need first to understand where is the error and make sure why the shallow if that is the case we will revert it to be opt-in.

**Comment by lasote** [comment]
@michaelmaguire Conan 1.20.4 has been released adding log traces to the git commands and the output. Could you try to run and send me the output to understand why the shallow is failing? Thanks. You would need to adjust `CONAN_LOGGING_LEVEL=20` or `conan config set log.level=20`

**Comment by michaelmaguire** [comment]
If I promise to help by manually switching between "Shallow"=False" and "Shallow"=True", with tracing on and sending you the results ;-), would it be possible to ask for a 1.20.5 that has default "Shallow"=False"?

It will be easier for me to sell if there's only one package I have to ask my SREs to create and deploy across our farm.

**Comment by lasote** [comment]
Thanks! Looking forward to the results.

>  would it be possible to ask for a 1.20.5 that has default "Shallow"=False" restored?

We need to understand first the error. Then if we change the default we will need to discuss in which version.

**Comment by michaelmaguire** [comment]
OK, I'll just beg one more time:

I only just asked my SREs to package and deploy 1.19.2 so we could upgrade from 1.16.1 to get lockfile support.

It broke.

Now I'll be asking them to do the same for 1.20.4, which will be only helpful as a diagnostic, but won't fix our existing recipes.

Can I please, please, pretty please ask for a 1.20.5 with "Shallow"=False" as default that at least restores us to a working state -- I will still send all the log output you need to get the root of the problem...

Otherwise I'm asking them to do this exercise 3 times in the last 2 weeks.
