### ISSUE TITLE
[bug] SCM and not using "--ignore_dirty" copies wrong folder to source / build folder

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#6070]
### Environment Details (include every applicable attribute)
  * Operating System+version: Win10
  * Compiler+version: VC15
  * Conan version: 1.20.3 vs 1.19.2
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)
I have a `conanfile.py` located in a subfolder `test/main` of my git repository. The repository is in `dirty` state.

When I use 'conan create ....` with changes in my repository with Conan 1.19.2 all files (starting from repository root) are copied to the source / build folder of the local cache. **Ok**

When I use 'conan create .... --ignore_dirty` with changes in my repository with Conan 1.20.3 all files (starting from repository root) are copied to the source / build folder of the local cache. **Ok**

When I use 'conan create .... ` with changes in my repository with Conan 1.20.3 only files loacated in 'test/main' are copied to the source / build folder of the local cache. The following build process fails, because the files are in other location. **Failed**

Should conan try to copy the files from the same root as the git repository, when `--ignore_dirty` is not selected?

**Comment by jgsogo** [comment]
Thanks a lot for submitting the issue, indeed it looks like a bug. We'll try to fix it asap.

Without `--ignore-dirty` only files located in the `conanfile.py` directory are copied to the `scm_source` folder in the cache.

**Comment by lasote** [comment]
1.20.4 released
