### ISSUE TITLE
[question] scm  stability

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan#6071]
There is a [warning](https://docs.conan.io/en/latest/creating_packages/external_repo.html?highlight=scm) about scm:

> This is an experimental feature subject to breaking changes in future releases.

I want to know more about this and when will this be stable?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @xyz1001. Sometimes when we introduce a new feature we need to receive feedback from the users to know if it covers all the use cases or we need to add something more, or we mismatch expectations,... during this process some experimental features may be removed, the implementation may change or the interface may evolve breaking the initial one. We need to add the experimental notice just in case.

Nevertheless, even with the experimental ones, we try to keep compatibility as much as possible for all the Conan v1.x series, we will break only if there is a bug or we were completely wrong in the implementation.

Said that, **the SCM feature is quite stable right now**, it's been there for long and many people are using it. I think that it won't be modified, I'm pretty sure it will become stable as it is now for Conan v2.0.

See also: https://github.com/conan-io/conan/issues/5704

**Comment by xyz1001** [comment]
Thank you for your reply.
