### ISSUE TITLE
[feature] Ability to use some Conan commands from an invalid directory

### ISSUE THREAD

**Issue by Morwenn** [conan-io/conan#6075]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

It's a bit of a niche issue, but it actually happened to me quite a lot lately as I was looking in `~/.conan/data` directories while tinkering with Conan packages: it is impossible to use any Conan command in a terminal when the current directory doesn't exist.

For example if I try to use `conan -h` I get the following error (I replaced home information with `~` by otherwise the message is valid):

```
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 11, in <module>
    load_entry_point('conan==1.16.0', 'console_scripts', 'conan')()
  File "~/.local/lib/python3.6/site-packages/conans/conan.py", line 7, in run
    main(sys.argv[1:])
  File "~/.local/lib/python3.6/site-packages/conans/client/command.py", line 2046, in main
    current_dir = get_cwd()
FileNotFoundError: [Errno 2] No such file or directory
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 67, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 11, in <module>
    load_entry_point('conan==1.16.0', 'console_scripts', 'conan')()
  File "~/.local/lib/python3.6/site-packages/conans/conan.py", line 7, in run
    main(sys.argv[1:])
  File "~/.local/lib/python3.6/site-packages/conans/client/command.py", line 2046, in main
    current_dir = get_cwd()
FileNotFoundError: [Errno 2] No such file or directory
('[powerline-bash] ', 'Your current directory is invalid. Lowest valid directory: [...]')
```

It's really a minor issue an totally fine if you don't feel like doing anything about it though. It mostly happens to me when I'm trying to perform `conan search` from an invalid directory.

**Conan version: 1.20.3** (and I just triggered it again while trying to fetch the version number, yay x)

**Comment by jgsogo** [comment]
Thanks a lot for pointing it out. As you say we cannot tag it with high priority, but I agree that some commands might not need a working directory and could work without it. Let me add it to the queue, low priority, but low complexity too (we can target one command at a time) and see if we (or someone) wants to contribute and improve the tool.

Thanks!
