### ISSUE TITLE
Attempted 'conan remove' of non-existent package from Artifactory appears to succeed

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#6076]
conan remove of a non-existent package from Artifactory  issues a yes/no query and appears to succeed.

I would expect it to instead produce the same warning it produces when I try to remove a non-existent package from the local cache.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows Server 2012 R2
  * Compiler+version: VS2015
  * Conan version: 1.19.2
  * Python version: N/A (exe install)

### Steps to reproduce (Include if Applicable)

Try to remove a non-existent package from Artifactory.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
E:\DevelopBp\mmaguir1\src\conan\conan-bde-classic>conan --version
Conan version 1.19.2

E:\DevelopBp\mmaguir1\src\conan\conan-bde-classic>conan remove bde-tools/3.11.0.1/mmaguir1_test_bde_only
WARN: No package recipe matches 'bde-tools/3.11.0.1/mmaguir1_test_bde_only'

E:\DevelopBp\mmaguir1\src\conan\conan-bde-classic>conan remove bpaosidaposidapsodaposdiapsodide-tools/3.31.0.9@mmaguir1/test -r=bloomberg_artifactory
Are you sure you want to delete from 'bpaosidaposidapsodaposdiapsodide-tools/3.31.0.9@mmaguir1/test' (yes/no): yes
```

```

**Comment by jgsogo** [comment]
I'm quite sure Artifactory returns a different _status_code_ from the API call, so we should be able to add a message like you suggest.

Thanks!

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2:

For an empty repository, the current output is:
```
$ conan list "*" -r=arti-test
Found 0 pkg/version recipes matching * in arti-test
arti-test
  WARN: There are no matching recipe references
$ conan remove "*" -r=arti-test
Found 0 pkg/version recipes matching * in arti-test
Remove summary:
arti-test
$ conan remove "foo/1.2.3" -r=arti-test
ERROR: 404: Not Found. [Remote: arti-test]
```
