### ISSUE TITLE
[bug] Output of 'conan search <ref> --revisions --raw' failure for single result

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6077]
### Environment Details (include every applicable attribute)
  * Conan version: Conan version 1.20.3
  * Python version: py 3

### Steps to reproduce (Include if Applicable)

Raw argument of `conan search --raw` is not honoured if there is a `@` in the reference.

More than one package in the cache:
```
⇒  conan search dep/0.1 --revisions --raw
dep/0.1#f732ec8d19fb3190c01f3df44f48b0e8
dep/0.1@issue/testing#f732ec8d19fb3190c01f3df44f48b0e8
```

Asking for a specific one (`--raw` is not honoured):

```
⇒  conan search dep/0.1@ --revisions --raw
Revisions for 'dep/0.1':
f732ec8d19fb3190c01f3df44f48b0e8 (No time)

⇒  conan search dep/0.1@issue/testing --revisions --raw
Revisions for 'dep/0.1@issue/testing':
f732ec8d19fb3190c01f3df44f48b0e8 (No time)
```

If there is only one in the cache (wihtout user/channel) it works:
```
⇒  conan search dep/0.1 --revisions --raw             
dep/0.1#f732ec8d19fb3190c01f3df44f48b0e8
```

If there is only one in the cache (with user/chanel) it fails:

```
⇒  conan search dep/0.1 --revisions --raw
dep/0.1@issue/testing#f732ec8d19fb3190c01f3df44f48b0e8

⇒  conan search dep/0.1@issue/testing --revisions --raw
Revisions for 'dep/0.1@issue/testing':
f732ec8d19fb3190c01f3df44f48b0e8 (No time)
```

 * Something doesn't behave the same when there is a `@` in the query.
 * And have a look to the JSON output too

**Comment by czoido** [comment]
> If there is only one in the cache (with user/chanel) it fails:
> 
> ```
> ⇒  conan search dep/0.1 --revisions --raw
> dep/0.1@issue/testing#f732ec8d19fb3190c01f3df44f48b0e8
> 
> ⇒  conan search dep/0.1@issue/testing --revisions --raw
> Revisions for 'dep/0.1@issue/testing':
> f732ec8d19fb3190c01f3df44f48b0e8 (No time)
> ```

I think that for this example the first one is the expected output as it seems that Conan interprets a partial search for the recipe as if there was an asterisk after that string, so: `conan search dep/0.1 --revisions --raw` seems to be interpreted the same as `conan search dep/0.1* --revisions --raw`

The second is clearly a bug because it's ignoring the `--raw` argument. So the bug seems to be that the `--raw` argument is ignored when searching for a specific reference with or without `--revisions` regardless if there's `user/channel` present or not

**Comment by jgsogo** [comment]
Whenever there is a `@` in the query you get:

```
Revisions for '<reference>':
<revision>
```

but, if there is no `@` the output is the expected one:

```
<reference>#revision
```

**Comment by czoido** [comment]
I think that the expected with the `@` is just the revision number and date of the revision, and without the `@` then it lists all of the references with that name with the revisions.

**Comment by jgsogo** [comment]
I would expect the same output always, something like `<reference>#revision (time)`. Output easy to parse, no need to parse the input to know how to parse the output 🤖
