### ISSUE TITLE
[feature] Start using scheduled LTS releases

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#6078]
I love the speed at which Conan is being developed. Few things make me happier than seeing a project I use be actively updated, fixed, and worked on. But that inevitably means there are some "breaking" changes that get shoved in once in a while (as in, breaks my workflow, not necessarily breaks your public API.... as in, I might be relying on some part of Conan that I shouldn't be).

The last time I ran into this was the switch from remotes.txt to remotes.json... I had to change a lot of CI build configs to deal with that, and it took quite a while.

It would be _really awesome_ if the Conan team could start doing long term support (LTS) releases. The idea being that my team and I would not upgrade to any version which isn't an LTS, and the Conan team would fix bugs in the LTS long after version LTS + n came out.

The most recent reason for me asking for this is because I _just_ upgraded my team to 1.19.2 (for a bugfix in revisions support), after _just_ finishing the upgrade them to 1.16.1 (for revisions support). Now that we're all on the same version again, and I'm ready to start using lockfiles, I find out about #5499.... time to upgrade _again_ and potentially deal with more "breaking" changes.

I've read through the release notes very carefully, and it looks none of the changes between 1.19.2 and 1.20.3 will affect our workflow, so it _shouldn't_ be a big deal to do this upgrade. But I'd be a lot more confident about that if 1.19 happened to be an LTS release that was continuously getting bug fixes only, and we could just upgrade to the latest 1.19 release instead of jumping to 1.20.

Given the young age of Conan overall, and the rapid speed of development, I don't think you need or should try to do 5-year LTS's like Canonical with Ubuntu. Even 6-months would be a big step forward. I don't think there even needs to be any overlap between LTS releases (yet). But it would be really nice if the Conan team could release a version that received bug fixes for longer than a month.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Hi, thanks for the suggestion. I think this might be a good idea, not sure if at the right moment. We have a very long queue of things we want to change (break) for 2.0. For sure, we will keep a 1.X version as an LTS and will backport/introduce bugfixes there. 
But anyway, if you are missing a bugfix in a 1.X version, we can try to backport it and release it, but we cannot compromise to do it in all cases.

**Comment by memsharded** [comment]
Yes, I think this would have been a thing like last year, since early versions of 1.X, but right now, 2 years later than 1.0 we are starting to face the final part of 1.X and starting to focus on 2.0, so starting LTS versions right now seems not possible, but we will be thinking about it for Conan 2.0 (maybe will be a nice topic to discuss in conandays.conan.io).

**Comment by DavidZemon** [comment]
Yep... definitely would have been good to do 6 months to a year ago. But oh well.
I do like @lasote's point of starting a 1.x LTS before moving on to 2.0 - that would be a very kind thing to do for your users.
And then, maybe start some scheduled LTSs after that :)

**Comment by AbrilRBS** [comment]
Closing as no-go in Conan 2 (The same policy still applied to Conan 1, but after Conan 2, we seem to have decided to keep as-is)
As per https://docs.conan.io/2/introduction.html#stable:

> - Moving forward to following minor versions 2.1, 2.2, …, 2.X should never break existing recipes, packages or command line flows
> - If something is breaking, it will be considered a regression and reverted.
> - Bug fixes will not be considered breaking, recipes and packages relying on the incorrect behavior of such bugs will be considered already broken.
> - Only documented features in https://docs.conan.io/ are considered part of the public interface of Conan. Private implementation details, and everything not included in the documentation is subject to change.
> - The compatibility is always considered forward. New APIs, tools, methods, helpers can be added in following 2.X versions. Recipes and packages created with these features will be backwards incompatible with earlier Conan versions.
> - Only the latest released patch (major.minor.patch) of every minor version is supported and stable.

So our commitment to stability is forward-looking. This is the way which we feel best leverages our efforts vs the value we provide to the users, hope it's understandable :)
