### ISSUE TITLE
[bug] Package recipe wasn't updated in local cache

### ISSUE THREAD

**Issue by flexferrum** [conan-io/conan#6084]
### Environment Details (include every applicable attribute)
  * OS: Windows 10 Home x64, rev 1903:
  * Conan version: 1.20.3
  * Python version: 3.7.1

### Steps to reproduce
I made the cross-platform CMake project with some conan dependencies which include dependency from `boost/1.71.0`. I used `conan_find_package` generator for this project.
I tested it in Windows environment, and everything worked fine. Then I moved it to the clean Linux environment with fresh conan installation, and got the build error. The problem was in the reference to the `boost` target. Initial version was:
```cmake
#...
find_package(boost)
#...
target_link_libraries(boost::boost)
```

and on Linux cmake failed to find `boost::boost` target. After some investigation I found that on Linux conan `boost` package got different name: `Boost` instead of `boost`, and thus the correct reference should be:
```cmake
#...
find_package(Boost)
#...
target_link_libraries(Boost::Boost)
```

Then I asked @jgsogo what could went wrong and he offered me to check the `boost` package recipes on Windows and Linux systems. I checked it and found that recipes are different. 

Significant difference between my Win and Lin development environments is that on Windows I downloaded `boost/1.71.0` some time ago (let's say a week ago or so), but Linux has got fresh recipes for all packages. And looks like when `boost` package recipe was changed,  `conan` didn't download it automatically on Windows. Forced download of this recipe solved the initial problem and I got the same package naming on Windows and Linux. Is it normal behavior of `conan`? Should it automatically update recipes in local cache or not?

### Logs (Executed commands with output)
Conan was executed on Windows with this command:
```console
conan install . -s arch=x86_64 -s build_type=Debug -s compiler=Visual Studio -s compiler.version=16 -s compiler.runtime=MDd -g=cmake_find_package -g=cmake --build=missing
```

Configuration:
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

Unfortunately, I can't provide the log of the first `conan` run after the package update - I didn't save it.

**Comment by Minimonium** [comment]
Hi. Conan isn't automatically updating recipes in the local cache unless you pass the `--update` parameter to a command.

**Comment by flexferrum** [comment]
> Hi. Conan isn't automatically updating recipes in the local cache unless you pass the --update parameter to a command.

Ok. I see. But there is still a question: is it expected (from user point of view) behavior or not?

**Comment by Minimonium** [comment]
Yes. The model is similar to the git/native package managers. Users don't expect Conan to automatically mutate the state of their build tree.

**Comment by jgsogo** [comment]
Even though the recipe version (`boost/1.71.0`) is the same, the [recipe revision](https://docs.conan.io/en/latest/versioning/revisions.html) has changed. The only way to ensure that the recipe is exactly the same from one machine/system/... to another is to check it.
