### ISSUE TITLE
[feature] Remove exports_sources for Conan 2.0

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6089]
exports_sources is very problematic, because it doesn't exists many times, leading to confusing errors.

Suggestion:

- Remove it for Conan 2.0
- Use SCM in the general case, exports as the fallback if SCM not possible.

**Comment by markgalpin** [comment]
For packages in Conan Center, we need a fall back for air-gapped or highly firewalled instances.  The idea is that a customer should be able to perform all actions that they can perform on the internet pointing only to the artifactory (and build from source is a pretty important capability of Conan).   This can be achieved either via a current mechanism such as exporting sources, or by using artifactory's built in git-remote capability to cache tip tarballs (But then we would need to figure out how to make that workflow smooth).  In general fixing this sort of behavior of other package managers is one of the first requests enterprise customers make when we implement a new technology that's not self-contained.

**Comment by puetzk** [comment]
Perhaps consider supporting things like `git bundle` (and perhaps `svnadmin dump` or `svn export`) formats, staged in the file download cache as an alternate source to satisfy scm = references? git clone sourced from a bundle works quite transparently, `svnadmin load` a bit less so but not terrible.

**Comment by puetzk** [comment]
Ideally with some variation of `conan source --freeze` or similar that would itself create the bundle/dump files which need to be staged present for an air-gapped build to succeed.

**Comment by FnGyula** [comment]
`exports_sources` is very handy to use when there are local files to bundle along with the source code (like patches). What would be the replacement for that?

Also, what would be the workflow for 'in-source' conanfiles? Conan's `exports_sources` provided a way of dealing properly snapshot the source, which would be now unavailable and we have to produce external recipes?

**Comment by memsharded** [comment]
> exports_sources is very handy to use when there are local files to bundle along with the source code (like patches). What would be the replacement for that?

The natural replacement is the ``SCM`` feature, capturing the commit of the repo instead of the actual contents. The flow would still be the same, the sources needs to be there, of course, in a repo, but you already had them in git available, otherwise you wouldn't have been able to build the package in first instance. Is there some reason in your case not to consider SCM instead?

**Comment by FnGyula** [comment]
It's the chicken and egg issue really.

I have a library sitting in Perforce (we aren't using git). When I build or package the library up with conan, the conanfile is sitting in the source repository to begin with. With this change, the developer must commit, submit, push back to the origin repository to use commands like `conan create .` which would be pretty awkward.

**Comment by memsharded** [comment]
> I have a library sitting in Perforce (we aren't using git). When I build or package the library up with conan, the conanfile is sitting in the source repository to begin with. With this change, the developer must commit, submit, push back to the origin repository to use commands like conan create . which would be pretty awkward.

Not really. ``conan create`` with ``scm revision=auto`` doesn't get the sources from the repo. It gets the sources from the local folder, very much as the ``export_sources`` do, but using the ``.gitignore`` as pattern to exclude files. Only if the repo is dirty it will block the upload. The capturing of the commit is for later. If the package is going to be built in the local cache as a dependency, it will not have the sources embedded, but it will need to get them from the scm server, and it will use the captured revision to get to that specific commit. 

It is true that SCM doesn't support perforce. In any case the other alternative proposed is to use ``exports`` instead of ``exports_sources``. It has the inconvenience that the sources are always retrieved with the recipe, so it is less efficient, but functionality wise would be identical (exports_sources is basically just an optimization over exports).

Thanks for the feedback, keep it coming. This is not an approved feature yet, but a place for discussion. Your inputs are very useful.

**Comment by verbatom** [comment]
> [...] exports_sources is very handy to use when there are local files to bundle along with the source code (like patches). [...]

I think so too, especially about the patches use case.


> [...] What would be the replacement for that? [...]

@FnGyula, as @memsharded already suggested, you could consider using [exports](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#exports) instead of [exports_sources](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#exports-sources).


> [...] the sources needs to be there, of course, in a repo, but you already had them in git available, otherwise you wouldn't have been able to build the package in first instance [...]

What about package recipes where the package recipe author is not the author of the packaged library and therefore has no write access for the actual package source code repository? For such a use case `exports` then seems to be the only remaining practical option.


I just checked with our project which depends on Conan packages of which we are not the package authors: 6/15 recipes use `exports` and 2/15 use `exports_sources` (which would then of course need to be adapted). They are mainly build helpers, some of them are actual patches for either the sources or the underlying build systems. In fact, some of the `exports` should have actually been declared as `exports_sources` as they are not used by Conan directly (but implicitly - distinction explained in the docs linked above and in memsharded's comment).


@memsharded, since you are suggesting to use `exports` instead, I hope you are not considering to deprecate it too, are you?

**Comment by memsharded** [comment]
> What about package recipes where the package recipe author is not the author of the packaged library and therefore has no write access for the actual package source code repository? For such a use case exports then seems to be the only remaining practical option.

Those are typically resolved with a ``source()`` method doing the fetch/download/clone of the sources. I am not sure what is the case for ``exports`` there that you refer to.

> @memsharded, since you are suggesting to use exports instead, I hope you are not considering to deprecate it too, are you?

For sure ``exports`` will not be deprecated.

Maybe ``exports_sources`` will not either. We need to get all the feedback and use cases, check alternatives, etc. This is more an open discussion that set on stone, I have labeled it accordingly.

**Comment by verbatom** [comment]
> [...] I am not sure what is the case for exports there that you refer to [...]

use case:
1. package recipe + accompanying patch files listed in the recipe in `exports` and therefore hosted on bintray after calling `conan upload [...]` thereby ensuring that the recipe matches the hosted patches
2. package sources (actual thirdparty library to be built and packaged) is stored in a different, read-only repository
3. recipe source step fetches sources from the aforementioned repository, applies the patches (which are tightly coupled with the recipe as a result of calling `conan upload [...]`), builds and packages the library

**Comment by memsharded** [comment]
Ah, ok, thanks, yes using ``exports/exports_sources`` to add patches or other aux files, while the main source si retrieved with ``source()`` from a different repo, is a common usage, thanks for clarifying.

**Comment by memsharded** [comment]
Update:

- ``export_sources`` is maintained in 2.0. There are good use cases, users happily using it, doesn't seem right to remove it
- ``scm`` has been made more explicit and flexible, but even though, still not enough for some cases
- The problem that exported sources cannot be found if disconnected from remote will be slightly reduced thanks to usage of revisions, and dropping the hardwired relationship between recipes and their remotes. But might eventually happen if removing remotes and sources were not downloaded. But it is ok, we can live with that and there is no better option.
