### ISSUE TITLE
[question] build dependency without cpp_info

### ISSUE THREAD

**Issue by Crejan** [conan-io/conan#6090]
### Question
How can i use a package as a pure build time dependency.

### Example
4 different packages:
- Boost
- libA: a process communication library which provides some shared libs for runtime usage as well as code generators. The code generators also make use of the libraries. Depends on Boost (shared)
- libB: Uses A to create some code during build and compiles some code. Does not have any runtime dependency to A. 
- libC: Does use A for process communication.

My current approach was to use libA as a build_requirement but then libB also gets boost as a dependency. how can i only use A as a pure build time dependency?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
>  but then libB also gets boost as a dependency

If `A` is `build_require` of `B` and B needs to be built, of course it will fetch Boost. As `B` requires boost on runtime, it cannot `build_require` boost.

Maybe it could improve to split libA into the "static" code and the other with runtime dependency on boost.

Hope it helps!

**Comment by Crejan** [comment]
>  `A` is `build_require` of `B` and B needs to be built, of course it will fetch Boost. As `B` requires boost on runtime, it cannot `build_require` boost.

yes, thats' not the problem, the problem is that `B` gets all the compiler and linker flags of `boost` from the `deps_cpp_info` even though `boost` is only needed as a runtime dependency for `A`.

> Maybe it could improve to split libA into the "static" code and the other with runtime dependency on boost.

Its not possible to split A up because the code generation part of A also needs boost as a runtime dependency. 

I it somehow possible to use boost as a runtime dependency for `A` such that it is only added to the `LD_LIBRARY_FLAGS` but not to the `cpp_info`?

**Comment by lasote** [comment]
In this case, probably the only choice would be, package A with a build_require to Boost, but importing the needed libraries to "repackage" them into the A binary package. That way the boost cppinfo won't be propagated.

We are aware of these limitations and we have some ideas to improve the requirements model but will take time.

**Comment by memsharded** [comment]
Conan 2 was released 1 year ago, and the graph capabilities can most likely help with this.
I am closing this as outdated, please create new tickets as necessary referring to the new Conan 2 graph model. Thanks!
