### ISSUE TITLE
[feature] conan search should not require a remote specifier

### ISSUE THREAD

**Issue by WesternStar** [conan-io/conan#6093]
So I was trying out conan for the first time and I was noticing that finding any libraries require you to first specify a remote AFAICT. There doesn't seem to be an obvious way to say anytime you search search these remotes (in this order) without me telling you to. It seems odd that the default behavior when you search is to not search in any remotes and thus not find any libraries.

**Comment by Minimonium** [comment]
Hi. It's, unfortunately, an old behaviour touching which would be a breaking change. 
Possibly, for Conan 2.0 we could make the search in remotes the default.

**Comment by lasote** [comment]
It searches by default the local cache, that it is really a thing in Conan.
Could you improve the docs maybe? That behavior is not going to change, not even in Conan 2.0 probably, it will be even more confusing for the already Conan users.

**Comment by WesternStar** [comment]
I can totally buy it being a behavior that you want for whatever reason. But why isn't a behavior I can change? Maybe local caches should be searched first but can't we at least have an option to then search remotes?

About the docs, Sure no problem. I'm not sure what I'll say exactly but I'll give it a whirl.

**Comment by memsharded** [comment]
We have already started to design and implement the new CLI for Conan 2.0. The ``search`` command will search by default in remotes, and in all of them, and use ``--cache`` to search in the cache. Track the progress on Conan 2.0, assigning this to that milestone.

**Comment by memsharded** [comment]
This is already implemented (and released) in 2.0.0-alpha1, this will be the behavior in 2.0, so this can be closed.
