### ISSUE TITLE
[feature] Add reference clone support to scm object

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#6097]
Hello,

Currently we use the scm object to get the source code as described here https://docs.conan.io/en/latest/reference/conanfile/attributes.html#scm-attribute

When dealing the large repositories, the git checkout fail so ofter with timeout, specially in CI.
it would be very useful if the scm object support reference clone as well.

Some references:
https://git-scm.com/docs/git-clone
https://randyfay.com/content/reference-cache-repositories-speed-clones-git-clone-reference

Thanks,
Walid 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Hi Walid and thanks for the proposal.

I didn't know about this feature in `git`! As I understand is cover your use case by indicating another repository to use as a reference.

Could you please explain a little bit more how it would help to you? Do you have the repo cloned elsewhere or do you want to avoid multiple clones?

**Comment by boussaffawalid** [comment]
A reference repository is a local bare repository (a local mirror of the remote repository). When
doing a git clone using a reference repo, object will be copied from the local reference first and only deltas will be fetched from remote repository. (only object that does not exist in the local mirror will be fetched from remote)

This has a lot of advantages:

- It is more much faster because clone creates pointers to the reference repository, instead of copying from the remote repository.
- It reduces the network I/O and reduces load on the remote Git server by not transferring content which is already in the reference repository.
- It saves local disk space by creating pointers from the project repository to the reference repository instead of creating a new copy.

This is very practical especially when dealing with large repos or when building a lot of repos in CI system.


How to create a reference repository ?
`git clone --mirror git@github.com:my-user/my-repository.git /var/git/my-repository.git
`

How to use a reference repo?
`git clone --reference  /var/git/my-repository.git  git@github.com:my-user/my-repository.git 
`

> If the reference repo is up to date, git won't need fetch anything from the remote server at all.

**Comment by memsharded** [comment]
``scm`` removed in 2.0, closing this issue as outdated.
