### ISSUE TITLE
Feature: Add "configure" helper available in build

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#61]
It's very common to prepare some env variables before configure, because libraries configure usually don't allow enough parameters for handle the location of their deps headers and libraries. 
So the way to do it is settings env variables before calling ./configure
Maybe we could develop a simple helper like the CMake one but for setting those variables.

Now i'm doing:

    def generic_env_configure_vars(self):
        """Reusable in any lib with configure!!"""
        libs = 'LIBS="%s"' % " ".join(["-l%s" % lib for lib in self.deps_cpp_info.libs])
        ldflags = 'LDFLAGS="%s"' % " ".join(["-L%s" % lib for lib in self.deps_cpp_info.lib_paths]) 
        archflag = "-m32" if self.settings.arch == "x86" else ""
        cflags = 'CFLAGS="%s %s"' % (archflag, " ".join(self.deps_cpp_info.cflags))
        cpp_flags = 'CPPFLAGS="%s %s"' % (archflag, " ".join(self.deps_cpp_info.cppflags))
        return "%s %s %s %s" % (libs, ldflags, cflags, cpp_flags)

    self.run("env %s ./configure" % generic_env_configure_vars())

To the community:
What do you think? Could be useful?

**Comment by memsharded** [comment]
I'd say that a dict is a little more pythonic and readable:

```python
env["LIBS"] = " ".join(...)
env["OTHER_ENV_VAR"] = "my_var_value"
```

Not sure about the multiplatform approach, does even the "env" command works in win? If not, what would be the approach. Also it is important to define the scope, I guess that they are just per-command, so if using some other approach in win, make sure that it restores the env to its previous state.

**Comment by lasote** [comment]
Forget win. I'm talking about clasic configure and make.

**Comment by memsharded** [comment]
Ok, I misunderstood the scope of the issue. I'd create a Env helper, similar to the CMake one, that receives a deps_cpp_info object in its constructor.

**Comment by lasote** [comment]
For windows support maybe: 

https://msdn.microsoft.com/en-us/library/6y6t9esh(v=vs.110).aspx

**Comment by lasote** [comment]
Finally it seems to work:

    def generic_env_configure_vars(self):
        """Reusable in any lib with configure!!"""
        if self.settings.os == "Linux" or self.settings.os == "Macos":
            libs = 'LIBS="%s"' % " ".join(["-l%s" % lib for lib in self.deps_cpp_info.libs])
            ldflags = 'LDFLAGS="%s"' % " ".join(["-L%s" % lib for lib in self.deps_cpp_info.lib_paths]) 
            archflag = "-m32" if self.settings.arch == "x86" else ""
            cflags = 'CFLAGS="%s %s"' % (archflag, " ".join(self.deps_cpp_info.cflags))
            cpp_flags = 'CPPFLAGS="%s %s"' % (archflag, " ".join(self.deps_cpp_info.cppflags))
            command = "env %s %s %s %s" % (libs, ldflags, cflags, cpp_flags)
        elif self.settings.os == "Windows" and self.settings.compiler == "Visual Studio":
            cl_args = " ".join(['/I"%s"' % lib for lib in self.deps_cpp_info.include_paths])
            lib_paths= ";".join(['"%s"' % lib for lib in self.deps_cpp_info.lib_paths])
            command = "SET LIB=%%LIB%%;%s && SET CL=%s" % (lib_paths, cl_args)

Maybe are missing link and compiler options, but I hadn't and I couldn´t test them.

**Comment by lasote** [comment]
ConfigureEnvironment(deps_cpp_info)
