### ISSUE TITLE
Submit your talk to ConanDays, 19-20 March, Madrid.

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6100]
If you’re using Conan, then you should submit a talk and share your experience with the community! Our [Call for Speakers is open](https://sessionize.com/conandays-2020/). 

[ConanDays](https://conandays.conan.io) is a technical event, bringing together all worldwide Conan users to share their experiences and contribute to the future of Conan. It will take place in Madrid, Spain, on March 19-20, 2020. Read more about it [here](https://blog.conan.io/2019/11/05/ConanDays-Madrid-2020-international-community-gathering-Conan-package-manager.html). 

Come to share your experiences with the community, and become a [speaker in the first Conan international event](https://sessionize.com/conandays-2020/).

**Comment by uilianries** [comment]
Hey @madebr! Any change having a talk there?! You have been involved with Conan and Bincrafters for a long time, it would be great having you there! The Call for Papers is still open ;)
