### ISSUE TITLE
[question] Override requirement only if version is in valid range

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#6101]
I use Gerrit for my code reviews.  When Gerrit has a new change, I override the requirements in my `conanfile.py`.

Let's say I have the following projects:
`LibA/1.0@main/stable`
`LibB/1.0@main/stable` (requires `LibA/[^1.0]@main/stable`)
`ProjC` (requires `LibB/[^1.0]@main/stable`)

Now I build a new major release of LibA and the new temporary package name from Gerrit would be:
`LibA/2.0@review/123`

Now I want to build `ProjC`, which has no direct dependency to `LibA`.
At the moment I just use the following override requirement:
```
self.requires("LibA/2.0@review/123", "override" 
```
inside `ProjC`.
Now conan uses for `ProjC` version `LibA/2.0@review/123`. This would violate against the version range requirement of `LibB`: `LibA/[^1.0]@main/stable`. I would like to use in `ProjC` still `LibA/1.0@main/stable` instead of `LibA/2.0@review/123`.

Is there a possibility to check, if the version range is in range, before overriding the requirement (inside the `def requirements(self)` function? 

I thought about an override with check version range, something like "override_check_version_range".

**Comment by danimtb** [comment]
Hi @climblinne,

If I understood it correctly, you are overriding ProjC's `libA` requirement with the new version explicitly. In Conan, what is declared downstream takes precedence to what it is declared upstream. In this case you are defining a new requirement in ProjC and you get the expected behavior.

I have never used Gerrit, so it is difficult for me to understand the flow so not sure if this can be achieved in another way.

In an effort to try a workaround, have you tried to add `libA` requirement in ProjC without `"override"`? Maybe that triggers the incompatibility

**Comment by climblinne** [comment]
Hi @danimtb,

may be a small story about our usage of Gerrit. We have round about 50 libraries (including unittests) and may be 10 projects, which are depending on the libraries. Now the simplest case is, that I change something in library A. This is just a "review" changeset (so it is not commited into the "master" branch) - like an "pull request" in Github.
Now Jenkins is coming in Action. Jenkins get a trigger from Gerrit, that there is a changeset for `Library A`.  First Jenkins builds `Library A` with the changeset. Afterwards Jenkins knows all dependant projects and libraries and tries to build them. These should now use the build of the `Library A`, which is under review (changeset).

There are now two ways to go:
1. When `library A` is a direct dependency of my project/library, I just change the requirement in the `conanfile.py` to the actual build of `Library A`.
2. When `library A` is a non direct dependency of my project/library, I add an override requirement to my 'conanfile.py` in the project.

At (1) I can test myself, if the version range would fit into my "review/changeset" library.
At (2) I just override the "review/changeset" library, but until now, I don't know how to check the version range before.

**Comment by climblinne** [comment]
Hi  @danimtb, do you need some more informations?

**Comment by danimtb** [comment]
Thanks for the story. I think this is very related to lockfiles as a way to achieve a way to pick the right versions in the node of your graph. You can check https://docs.conan.io/en/latest/versioning/lockfiles.html?highlight=lockfiles#using-lockfiles and the how-to at the end of the page.

I am not sure if it would work, but you can try making the override with a version range with a "fixed" version like this `self.requires("LibA/[2.0]@review/123", "override")`

**Comment by danimtb** [comment]
After no more activity on this issue, I consider the question was answered and closing it. Thank you!
