### ISSUE TITLE
[question] Which remote is picked up by conan install --update

### ISSUE THREAD

**Issue by AlexandreBossard** [conan-io/conan#6104]
We use fmt/6.0.0@_/_. We have a (older) version of this recipe on our local conan server with all the prebuilt packages we need for our CI. The CI server configurations declares our conan server as a remote first and then conan-center, bincrafters, etc.. Finally, they use `conan install path/to/file --update --build never --profile gcc8-release`.

This sometimes failed because conan complains about `fmt` missing its prebuilt package. It appears that conan have updated the `fmt` recipe and picked the one from conan-center and NOT the one on our server. I'm not sure it's happen for every build and/or on every CI servers. So my question is,  how `--update` pick-up a remote to update the recipe from ?

I believe the solution would be to remove the extra remotes, use `--remote`, or 'just' use the lock graph feature.

**Comment by danimtb** [comment]
I think `--update` uses the remote where the recipe was originally retrieved from. That information is stored in the cache registry metadata. I will have to verify this information with a test though

**Comment by AlexandreBossard** [comment]
The `fmt` recipe is retrieved from our server. I don't know about the update.

**Comment by danimtb** [comment]
I have written a test here to test the behavior of `conan install --update` https://github.com/conan-io/conan/pull/6109

Does it resemble your scenario?

**Comment by AlexandreBossard** [comment]
At first glance yes. I'am crawling through our ci log if I can make sense of it.

**Comment by danimtb** [comment]
Take into account that the test is not using revisions. With revisions enabled, the behavior is different.

**Comment by AlexandreBossard** [comment]
Ah! we do revisions though. That's one of the reason we use our conan-server.

**Comment by danimtb** [comment]
I have enabled revisions in the PR. Will make the needed changes there to test the real behavior.

**Comment by danimtb** [comment]
The test also worked with revisions activated, so the behavior should be similar

**Comment by AlexandreBossard** [comment]
So here some extract from our ci logs
```
[2019-11-14 10:23:35] :: conan install /theproject --profile macos-release --update
// chop chop
Requirements
 fmt/6.0.0 from 'godzilla' - Cache
Packages
fmt/6.0.0:597ffa6804e8ac3d53e5063eeeaf34f5fcff19d2
```
This is fine and expected.
Then
```
[2019-11-14 16:30:06] :: conan install tanker/dev@tanker/dev --update --profile gcc8-release 
fmt/6.0.0: Retrieving from remote 'conan-center'...
fmt/6.0.0: Retrieving from server 'conan-center' 
fmt/6.0.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
..
Downloading conanfile.py
..
Downloading conan_export.tgz
..
....
fmt/6.0.0: Downloaded recipe revision 2e3637288df409955ed253beae014078
Requirements
  fmt/6.0.0 from 'conan-center' - Updated
Packages
  fmt/6.0.0:56e0cf6d16ee57367a0661ab743f4e43b29223f8 - Download
```
On this occurrence conan found a suitable package on conan-center on the job did proceed, but we have other profiles (eg: macos,ios,android) where it did not found one (the fmt package is marked as missing). So most of our job after that update failed.

So i'am pretty sure conan tries to fetch a recipe update on any available remotes that have the matching recipe reference.

So as a fix/workaround, we should remove the conan-center remote and fork the few recipes we have there on our local conan-server.
Or specify the remote explicitly on every `conan install` invocation, if it work.

I would also request that `conan install --update` only fetches an update only from the original recipe's remote.

**Comment by danimtb** [comment]
This is the expected behavior with revisions activated.

The logic here comes with the recipe revision being the same in both remotes but package timestamps differences, being the one in conan-center more recent than the one in your server.

The reason for this is that with the recipe revision, Conan is sure that the recipe is the same and packages will be compatible, so it can take packages from other remotes and "mix" them to update your cache.

The best option here will be to indicate the remote you want to update from.

**Comment by AlexandreBossard** [comment]
I'm pretty sure the recipe revision are not the same. The one on conan-center is 'newer' yes, even if the only part that change are the author and tags.
