### ISSUE TITLE
[bug] Unneeded environment variables when using MSVC can get too long and cause problems.

### ISSUE THREAD

**Issue by BumblingCoder** [conan-io/conan#6108]
When using the `virtualbuildenv` generator and using MSVC for the compiler the `CL` and `LIB` variables are set to add the include and lib path of every library that the project depends on. This is not needed for most build systems, and is causing problems at my workplace where we have about 60 dependencies in total. On running activate_build.bat we get an error that the command line is too long for these variables, and we have seen our build scripts failing due to this error coming from `cmd.exe`. Either not having these set to include all of the libraries or at least having the ability to turn off this behaviour would be helpful.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows (all)
  * Compiler+version: MSVC
  * Conan version: 1.19.3
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)
1. Create a project with a large number (60 in our case) of dependencies
2. Ensure that the conanfile specifies that the virtualbuildenv generator is created.
3. Run `conan install`
4. Attempt to run `activate.bat` and `activate_build.bat`
5. Observe that there is an error about the command line being too long

**Comment by memsharded** [comment]
Hi @BumblingCoder 

Thanks for your report.
Indeed this seems an issue, though I don't know well what could be done. The thing is that:

> This is not needed for most build systems,

The reality is that there are conan users that rely on this functionality, and it cannot simply be removed. 

We are now starting the next big iteration on the build systems integrations, and will be doing work to decouple the build systems toolchains, the dependencies informations, and the environments. But this will take some time.

What are you using the ``virtualbuildenv`` if it is not for the dependencies information? Maybe try not using it and getting the dependencies information from the properties ``.props`` file? A bit more of knowledge of the bigger picture would be useful.

**Comment by BumblingCoder** [comment]
We are using `virtualbuildenv` for its wrapping of `vcvars` based on the profile. As a workaround we are probably going to just call vcvars directly, but having it be called by conan made it far easier to ensure that the compiler was uniform everywhere.

**Comment by memsharded** [comment]
These generator was superseded by ``VirtualBuildEnv``, closing this ticket as outdated.
