### ISSUE TITLE
[feature] Simple way to get package paths from command line

### ISSUE THREAD

**Issue by smokris** [conan-io/conan#6111]
Example:  I'm trying to debug failing Conan package build on Travis CI.  The `./configure` script fails, and I want to examine `config.log` to get the details.  Currently I can add this to my `.travis.yml` script:
```
after_script:
    - cat $(conan info packagename/version@owner/channel --paths --package-filter 'packagename*' | grep build_folder | cut -d':' -f2)/config.log
```
…but that part in the sub-shell is kinda verbose and fragile.

It would be nice to have a more direct way to get just the build folder, perhaps with a syntax like this:

    conan info packagename/version@owner/channel --only build_folder --one

That is, I'm proposing these changes:

   1. Add `--one` flag, which shows only the specified package (without its dependencies), and omits the package output line and the key prefix.  
      E.g., without `--one`:

          packagename/version@owner/channel
              build_folder: /Users/me/.conan/data/packagename/version/owner/channel/build/…
          anotherpackage/version@owner/channel
              build_folder: /Users/me/.conan/data/anotherpackage/version/owner/channel/build/…

      With `--one`:

          /Users/me/.conan/data/packagename/version/owner/channel/build/…

   2. When specifying `--only build_folder` (or other `--only` arguments which are paths), implicitly add the `--paths` flag.  (Currently it fails with `ERROR: Invalid --only value` if I specify `--only build_folder` without `--paths`.)

If the maintainers agree with this direction, I could attempt a pull request.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Hi @smokris !

Did you try `--json` argument? It's not exactly what you want, but it can help for filtering. 

    $ conan info foo/0.1.0@ --paths --package-filter "foo*" --json info.json
    $ jq .[0].build_folder info.json
    "/home/uilian/.conan/data/foo/0.1.0/_/_/build/2a30b7d6ea2202e5393ebda51c8729dd2162b9f8"

**Comment by smokris** [comment]
> Did you try --json argument?

Thanks — yes, that provides the output I'm looking for.  (But that requires installing another package on the build host, and still has a somewhat unwieldy syntax.)

**Comment by memsharded** [comment]
Conan 2.0 ``conan cache path`` command does exactly this, closing as solved.
