### ISSUE TITLE
[bug]  copy(ignore_case=False) under Windows

### ISSUE THREAD

**Issue by db4** [conan-io/conan#6116]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Conan version: 1.20.4
  * Python version: 3.7.1

I would say `copy(ignore_case=False)` methods behavior under Windows is at least inconsistent with docs:
> - **ignore_case** (Optional, Defaulted to False): If enabled, it will do a case-insensitive pattern matching.

actually files case is effectively ignored regardless `ignore_case` value.

That's due to
https://github.com/conan-io/conan/blob/e5d142e61e9913b246c034a46d21c2d183ba0d35/conans/client/file_copier.py#L155
`fnmatch.filter` uses `fnmatch.fnmatch` that in turn involves `os.path.normcase()` doing case-insensitive filtering under Windows.

What about
```python
files_to_copy = [n for n in filenames if fnmatch.fnmatchcase(n, pattern)]
```
and replacing `fnmatch.fnmatch` with `fnmatch.fnmatchcase` everywhere?

**Comment by czoido** [comment]
Hi @db4,
You are right, It seems that currently `ignore_case` argument has no effect under Windows and it should be fixed.
Thanks a lot for reporting.

**Comment by ericLemanissier** [comment]
I've just been bitten by this. @db4  Did you make a pull-request with `fnmatch.fnmatchcase` ?

**Comment by db4** [comment]
> Did you make a pull-request with `fnmatch.fnmatchcase` ?

No, I just reported the bug. If Conan developers think my method of fixing it is OK, I can create a PR. But this definitely requires some tests? I'm not very familiar with the Conan testing framework.
