### ISSUE TITLE
[question] A way to detect os_build and arch_build

### ISSUE THREAD

**Issue by asleszyn** [conan-io/conan#6118]
Is there a way for conan to detect the os_build and arch_build settings of the system it's being run on?

Right now I need to have separate profiles for each platform I build on. The only difference are the build settings. If I omit them, packages like installers complain that these values are not set, e.g.:

`ERROR: ninja_installer/1.8.2@bincrafters/stable: 'settings.arch_build' value not defined`

I want a profile which requires ninja. Why do I have to have separate profiles for mac and linux?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Hi!

You can mix `arch` and `arch_build` at same profile, it should be enough for your case.

```
# gcc9 profile
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

Filtering if settings has os_build or not will increase your complexity for an unnecessary problem.

**Comment by asleszyn** [comment]
I don't know if I was clear enough but this doesn't answer my question at all.

I have an application, which requires ninja to be built. I want to build it on mac and linux. I must have 2 profiles which do the same thing:
```
[build_requires]
ninja_installer/1.8.2@bincrafters/stable
[settings]
os_build=Linux
arch_build=x86_64
```
```
[build_requires]
ninja_installer/1.8.2@bincrafters/stable
[settings]
os_build=Macos
arch_build=x86_64
```
Why can't I have just this and let conan detect the build settings:
```
[build_requires]
ninja_installer/1.8.2@bincrafters/stable
```

**Comment by uilianries** [comment]
Sorry, I didn't understand your case yet. 

Why can't you declare both os and os_build, and arch/arch_build in your profile? 

When Conan installs ninja_installer, it will look your profile, the default one if not specified, and read both os_build and arch_build. If your custom profile does not have both settings, Conan will not magically detect it. If your custom profile is only an extension, you can [include](https://docs.conan.io/en/latest/reference/profiles.html#profile-includes) the default one.

**Comment by asleszyn** [comment]
Conan is able to detect os_build and arch_build. There's no magic there. It does precisely that when it generates a native profile i.e.: `conan profile new --detect <name>`.

Now I don't understand why this has to be put explicitly in the profile. If a pkg requires this setting but it's not present in the profile, why don't we assume it's for the current machine?

**Comment by uilianries** [comment]
Because you can cross-compile installers the package them using another arch, so when installing Conan will check arch_build anyway. Also explicit variables keeps a deterministic environment.

**Comment by asleszyn** [comment]
> Because you can cross-compile installers the package them using another arch, so when installing Conan will check arch_build anyway.

I'm sorry but I don't understand what you're trying to say.

**Comment by uilianries** [comment]
> Now I don't understand why this has to be put explicitly in the profile. 

Because you can cross-compile installers as any other package. So when installing ninja_installer, for instance, Conan will need to check arch_build anyway.

Again, if you want to create a small profile file, you can extend it from the default profile.

**Comment by jgsogo** [comment]
Hi, @asleszyn 

I think that the approach @uilianries suggested can be applicable to your use case. Conan detects a `default` profile and writes it to a file, so your profile can be (if it is enough):

```ini
include(default)

[build_requires]
ninja_installer/1.8.2@bincrafters/stable
```

and it will take a different `default` profile in your MacOS and in your Linux, with the proper values of `os_build` and `arch_build`.

**Comment by asleszyn** [comment]
This will work but I consider it a workaround. I still don't understand why os_build and arch_build cannot be detected automatically.

**Comment by jgsogo** [comment]
They are, but not in the same step. Autodetection is very tricky, it depends on many things and we prefer to keep it separated from the actual building job. 

IMO, it is easy to always run `conan profile new --detect` before `conan create` if you really want to always run the autodetection before.

**Comment by asleszyn** [comment]
I maintain profiles for different machines (developer machines, build bots) that target different devices. No, it is not easy to have a manual step on each of those devices. Especially since the detected profile is not enough for our uses.

I don't see how detection is tricky during building but fine during generating a default profile.

**Comment by jgsogo** [comment]
Hi, @asleszyn. Before building, we recommend using `conan config install <git-url>` to install configuration shared in a developer team or company (settings, profiles, hooks, remotes,...), it should make it easier to maintain different profiles.

**You don't need a manual step**, you can run your `conan create` using a command like:

```bash
conan profile new --detect default && conan create <conanfile> --profile=<your-profile>
```

and your profile for each job (`--profile=<your-profile>`) only need to extend or modify the default profile:

```ini
include(default)

[settings]
.... override your settings

[build_requires]
... add build requires
```

With this configuration, you don't need any extra step or manual step, and you are writing everything explicitly.

**Comment by asleszyn** [comment]
Not ideal but it'll work. Thank you.

**Comment by jgsogo** [comment]
You are welcome. I'm closing this issue, but feel free to open it again if you need anything related to it.

Thanks!
