### ISSUE TITLE
[bug] 'Broken' Symlinks not being copied in source export

### ISSUE THREAD

**Issue by Josh-Grauman-Bose** [conan-io/conan#6120]
When running 'conan create,' several symlinks that I have in my folder structure are not being copied as expected. The implementation is odd, but they are source controlled _broken_ symlinks which will point to valid locations post build. There is a desire to have these symlinks source controlled rather than generated post-build. 

I've done a quick search for issues relating to symlinks, and #5080 sounds like it at least touched on similar behaviors, but I didn't see anything that lines up exactly with what I am seeing.

I've verified the following:
- The symlinks are exported via a git clone from the command line outside of Conan
- The symlinks do not appear anywhere in the sandbox created for 'conan create'
- Running "git status" in any of the various source directories in the sandbox shows my symlinks as having been deleted
- The symlinks should not be getting filtered by any line in the ".gitignore" file

I've attempted to remedy this issue by:
- Running `export CONAN_SKIP_BROKEN_SYMLINKS_CHECK=11` prior to executing the 'conan create' command
- Adding "skip_broken_symlinks_check=True" to my conan.conf file
- Explicitly adding those files to self.copy calls in the imports() function in conanfile.py

My assumption is that those files should be getting copied normally, rather than being skipped. 

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16.04.1 LTS
  * Compiler+version: gcc 5.5.0
  * Conan version: 1.20.3
  * Python version: 3.5.2

### Steps to reproduce (Include if Applicable)
- Create a repo with a committed, broken symlink, or create a symlink in a local checkout of a repo
- Run 'conan create' in that repo
- Check the sandbox to confirm that the symlinks were not properly copied

### Logs (Executed commands with output) (Include/Attach if Applicable)
Confirming that environment variable is set:
```
$ env | grep CONAN
CONAN_SKIP_BROKEN_SYMLINKS_CHECK=1
CONAN_USER_HOME=/scratch/conan
```

State of "source" folder in conan cache after a conan create (with paths sanitized):
```
/test/test/source$ git status
On branch ConanUpdates
Your branch is up-to-date with 'origin/ConanUpdates'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    Path/To/Broken/DirectorySymlink
	deleted:    Path/To/Broken/FileSymlink
	deleted:    conanfile.py

no changes added to commit (use "git add" and/or "git commit -a")
```

State of "scm_source" folder in conan cache after a conan create (with paths sanitized):
```
test/test/scm_source$ git status
On branch ConanUpdates
Your branch is up-to-date with 'origin/ConanUpdates'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    Path/To/Broken/DirectorySymlink
	deleted:    Path/To/Broken/FileSymlink
	deleted:    conanfile.py

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by jgsogo** [comment]
Hi, @Josh-Grauman-Bose , thanks a lot for taking the time to investigate your issue. I really appreciate it.

There is a PR we are afraid of because it will modify existing behavior, but it should enter into Conan 2.0: https://github.com/conan-io/conan/pull/5377 In that PR I tried to cover all the use-cases related to symlinks and make them work the proper way, I've also added some comments to the lines that might break existing behavior.

Your use-case I think it is related to this comment:

> FileCopier: the helper class used inside recipes self.copy(...):
>   * warns about broken symlinks and symlinks outside the source folder
>   * do not copy broken symlinks and those outside the source folder

According to the documentation, using `CONAN_SKIP_BROKEN_SYMLINKS_CHECK` should prevent the check and those files should be copied. I think we can implement this fix without breaking, so let's add it to the backlog.

Thanks for your patience.

**Comment by Josh-Grauman-Bose** [comment]
Hi, @jgsogo thanks for the reply. Good to hear that a fix has already been proposed! 

Is there any estimate yet of a timeline for inclusion of that fix, or is that still being determined? We're currently looking into workarounds on our end to resolve our problems short term, but would obviously prefer a built-in fix.

**Comment by jgsogo** [comment]
Let's add it to the next release 😉

**Comment by Josh-Grauman-Bose** [comment]
That would be perfect. Thanks a ton for the speedy response and quick deployment!

**Comment by memsharded** [comment]
Solved in https://github.com/conan-io/conan/pull/13137 for 2.0 (beta.10 today)
