### ISSUE TITLE
[bug] cmake_multi needs CMAKE_BUILD_TYPE on macos/linux

### ISSUE THREAD

**Issue by p-groarke** [conan-io/conan#6121]
Hey, I'm having issues building unit tests on travis. Gtest doesn't seem to export its include paths both on macos and linux. I am unsure if it's a user error, but appveyor is running fine.

I am using `TARGETS` with `cmake_multi` setup. I've tested both the old bincrafters gtest package and the new official one, so it doesn't seem to be a recipe problem.

```
	include(${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake)
	conan_basic_setup(TARGETS)

	output_file(${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake)
	output_file(${CMAKE_BINARY_DIR}/conanbuildinfo_release.cmake)
	output_file(${CMAKE_BINARY_DIR}/conanbuildinfo_debug.cmake)

	# ...

	message("conan include dirs : ${CONAN_INCLUDE_DIRS}")
	target_link_libraries(${TEST_NAME} PRIVATE ${PROJECT_NAME} CONAN_PKG::GTest)
```

In the logs, `CONAN_INCLUDE_DIRS` is empty. I've output the content of the following files to help debugging.
${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake
${CMAKE_BINARY_DIR}/conanbuildinfo_release.cmake
${CMAKE_BINARY_DIR}/conanbuildinfo_debug.cmake

https://travis-ci.org/p-groarke/fea_unsigned_map?utm_source=github_status
https://travis-ci.org/p-groarke/fea_unsigned_map/jobs/616035998?utm_source=github_status
https://travis-ci.org/p-groarke/fea_unsigned_map/jobs/616036000?utm_source=github_status

From: https://github.com/p-groarke/fea_unsigned_map/tree/ci

Unfortunately, I don't have a unix to test on, so it is difficult to figure out whether the problem is travis or just my setup on those OSes. Everything is fine on Windows.

Thx for any help/pointers,
cheers

### Environment Details (include every applicable attribute)
  * Operating System+version: macos/linux bionic (details can be found in travis.yml)
  * Compiler+version: apple-clang 11.2, gcc 7 & 8
  * Conan version: latest
  * Python version: 3.7.1

### Steps to reproduce (Include if Applicable)
Launch a ci build.

### Logs (Executed commands with output) (Include/Attach if Applicable)
See above.

**Comment by memsharded** [comment]
It seems to be fine here, in a Linux VirtualBox machine (highly recommended to debug things).
I get some linking errors, but they are past the include error.

I think the issue could be that you are not passing the config in the cmake configuration step. This is necessary, especially if using the cmake_multi generator:

```bash
$ cmake .. -DBUILD_TESTING=On -DCMAKE_BUILD_TYPE=Release
# and, typically in another "build-debug" folder
$ cmake .. --DBUILD_TESTING=On -DCMAKE_BUILD_TYPE=Debug
```
Please try that in your CI.
You might also try to go with the ``cmake`` generator instead for Linux, as the multi generator only makes sense for multi-config environments like Visual Studio. I would recommend it.

**Comment by p-groarke** [comment]
@memsharded I thought cmake_multi was created so we don't have to generate different solutions for debug/release? I will try that though, thx.

**Comment by p-groarke** [comment]
Well would you look at that, it works and links :) So, I guess I'll rename the issue, unless you changed what `cmake_multi` is for? Or am I missing something?

**Comment by p-groarke** [comment]
OK so the doc mentions this is just for IDEs. Would it be possible to support makefiles with `cmake_multi`?

**Comment by memsharded** [comment]
The link error might be something with the compiler, that I am using other (older) compiler version, or maybe the libstdc++11 that I didn't adjust.

> OK so the doc mentions this is just for IDEs. Would it be possible to support makefiles with cmake_multi?

That is the point, no. Makefiles are by definition single-config build environment. You really need to generate build files (folders) for different configurations. Then, the ``cmake_multi`` is basically pointless. You might use it with just 1 configuration, but you still need the 2 separate build folders, and you need to install both configurations in each folder, so it is a bit extra unnecessary work. So it is not a feature, because it is not possible, we can't do anything regarding this, it is just how Makefiles (and other build systems) works.

Also, take into account that we are moving forward with the ``cmake_find_package_multi`` generator for the future, it will (or a variant) become the default recommended one.

**Comment by p-groarke** [comment]
Alright no problem, thx for clarifying and for the help. I use `cmake_find_package_multi` in some of my more complex projects. It works great so it's not a problem for me. Have a great end of weekend :)

**Comment by memsharded** [comment]
Great, you too! :)
