### ISSUE TITLE
[question] Add arbitrary data to package id?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#6122]
I have `LibA` DLL that depends on `LibB` static library via build_require. And I need `LibB` version to affect `LibA` package id.  I'm thinking of appending something like `sha1("LibB=1.2.3')` to self.info in my package_id(). Is it possible?

**Comment by memsharded** [comment]
Hi @db4 

Right now it is impossible, there is no way to make a build_require affect the packageID, because the packageID is computed before it. The evaluation is:

- The dependency graph of "libraries" (requires) is resolved.
- The ``package_id()`` of each package is computed.
- With the package_id of each package, and the build policies (missing, etc), it is decided if packages are to be built, downloaded or are missing.
- For packages to be built, the ``build_requires`` are evaluated, retrieved and added to the dependency graph.

If you need that dependency to affect the package_id, you really need to use ``requires`` instead.

The good news is that we are aware of this issue, and we know that there is something missing in the graph model. Not top priority right now, because there are other even more important things in the backlog, but this will get higher priority, maybe after Conan 2.0 or after ConanDays, it the community feedback points in that direction.

**Comment by db4** [comment]
Hi @memsharded 

> Right now it is impossible, there is no way to make a build_require affect the packageID, because the packageID is computed before it.

I know that. My idea was to manually change packageID, something like that:

```python
def package_id(self):
    self.info.append_data("LibB=1.2.3")
```
Hypothetical `append_data()` would just append arbitrary user-provided data to the string that is later used to calculate SHA for packageID.

> If you need that dependency to affect the package_id, you really need to use `requires` instead.

I tried requires/private (it's sort of deprecated, right?), but ran into a weird problem. Here my simplified dependency graph:

LibA static lib -> requires boost 1.66
DllB dll -> requires (private) LibA
DllC dll -> requires DllB, requires boost 1.68

Doing so I get a conflict with boost 1.66/1.68 while creating DllC. Is it expected?

**Comment by memsharded** [comment]
Ok, in that case I think you can either use some new setting, or option, depending if you want to apply to all packages or just some:

- Add a extra setting in the settings.yml file, at the root level, allowing ``[None, "ANY"]`` values
- You can set that in the ``package_id()`` method (maybe also in the ``configure()`` method)
- It will modify the packageID. Value ``None`` is provided to allow not specifying it, and not affecting existing packages.

It is kind of a workaround, but it might do the trick.

Yes, the ``private`` requires are not really recommended for normal usage, only for very extreme cases (like having to wrap 2 different versions of the same static library in respective shared libraries).

With respect to your conflict, I cannot reproduce it, I have tried the following test:

```python
    def test_transitive_private2(self):
        # https://github.com/conan-io/conan/issues/6122
        client = TestClient()
        client.save({"conanfile.py": GenConanfile()})
        client.run("create . boost/1.66@")
        client.run("create . boost/1.68@")
        client.save({"conanfile.py": GenConanfile().with_require_plain("boost/1.66")})
        client.run("create . pkgA/0.1@")
        conanfile = textwrap.dedent("""
            from conans import ConanFile
            class PkgA(ConanFile):
                requires = ("pkgA/0.1", "private"),
            """)
        client.save({"conanfile.py": conanfile})
        client.run("create . pkgB/0.1@")
        client.save({"conanfile.py": GenConanfile().with_require_plain("pkgB/0.1")
                                                   .with_require_plain("boost/1.68")})
        client.run("install .")
```
It passes without conflict.

**Comment by db4** [comment]
@memsharded 
> Ok, in that case I think you can either use some new setting, or option, depending if you want to apply to all packages or just some:

Unfortunately, I need a package version that's neither setting nor option. So I propose to add  `self.info.append_data()` that doesn't break existing package ABI and allows package developers to do anything they like with packageID.

> With respect to your conflict, I cannot reproduce it, I have tried the following test:

So the conflict is considered a bug. Well, I'll try to create a reproducible test case and submit a separate issue.

**Comment by memsharded** [comment]
> Unfortunately, I need a package version that's neither setting nor option. So I propose to add self.info.append_data() that doesn't break existing package ABI and allows package developers to do anything they like with packageID.

But if the variability injected to the package ID is creating different package IDs for different things based on other data, without being setteable from the consumer, then I am missing something, like some packages cannot be reached. We would need to understand better the use case for modifying the packageID in that way. Could you please elaborate further the reasons, how those packages are being consumed, etc? Thanks.

**Comment by db4** [comment]
> But if the variability injected to the package ID is creating different package IDs for different things based on other data, without being setteable from the consumer, then I am missing something, like some packages cannot be reached

Thinking over it once again I should say that I you are right. So I'm closing the issue. Thank you very much for the clarification!

**Comment by memsharded** [comment]
Glad to help! Do not hesitate to ask if there are further questions.
