### ISSUE TITLE
build_modules : refactor to support multiple build systems

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#6125]
This API...

`self.cpp_info.build_modules = []`

...should be re-implemented. Probably something like this: 

`self.cpp_info.build_modules['cmake'] = []`

This would then allow modules to be passed to any build system, not just cmake:

`self.cpp_info.build_modules['visual_studio'] = []`

The need for this seems obvious (every other member of `cpp_info` is build-system-agnostic, etc), and this re-implementation could be done without being a breaking change. 

Obviously, there are design questions to be answered, for example: 
- How to associate the members with the generators? 
    - Exact match?
    - Starts With?
    - Regex?
    - Something more robust

"exact match" seems intuitive, but is probably naive because we have several cases of competing generators for a given build system.  For cmake, it would be annoying to have to define the same `build_module` file three times (once for each cmake generator). 

"starts with" captures the current CMake implementation which could be described as "all three generators which start with the word `cmake` will include this module". It also captures the second prominent case of multiple generators for a single build system: `visual_studio` and `visual_studio_multi`.  

Of course, corner cases are likely, where someone wants a module to only be included in `visual_studio_multi` for example but not `visual_studio`.  This would be supported by a "starts with" strategy. Unfortunately, the converse would not (including a module in the `visual_studio` generator but not `visual_studio_multi`).

"regex" would support both cases... but regex just seems terrible for this API. 

Feel free to do something more robust, but it will certainly be more complex if you actually want to support highly flexible user-defined-mappings of `build_modules` to generators.  I would probably just do starts-with on the next iteration.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This could make sense in the same way that the ``cpp_info.name`` made sense. That one, we are fixing it with a ``cpp_info.names`` field, but this one, I am not sure what the approach would be without breaking. The docs doesn't say this field is experimental, but it should have been labeled as such.  What do you think @danimtb ?

But I still have a question. What is the use case for ``visual_studio`` generators? For ``cmake`` ones, it is more or less clear, the provided modules are injected and made available to the consumer CMakeLists.txt. Typical use case is a macro or function with some utility that helps consuming the package itself.

What would be an example use case for visual studio? How should them be injected to the consumers?

**Comment by solvingj** [comment]
All build systems have the same need.  `.props` files can hold macros and functions exactly like `.cmake` files.

**Comment by danimtb** [comment]
We are currently not filtering the information in the cpp_info model per generator. We just include the module files per file extension and each generator uses the build modules they want. Maybe checking the extension of the file is weak? It could be, but the implementation is cleaner as we don't have to check fields for multiple generator names.

Anyway, if we are going to follow this path with `cpp_info.names["<generator-name>"]` that might be okay. Take into account that this should also work with custom generators.

**Comment by solvingj** [comment]
file extension is indeed too weak.  there are multiple build systems which use same file format.  case in point is `premake` and `xmake` both use `.lua`

**Comment by danimtb** [comment]
Related to #5408 and https://github.com/conan-io/conan/issues/5993

**Comment by memsharded** [comment]
Outdated by ``cpp_info.set_properties()``, closing
