### ISSUE TITLE
Problem when working with mingw

### ISSUE THREAD

**Issue by osechet** [conan-io/conan#614]
I'm trying to adapt the [ICU package](https://github.com/Vitallium/conan-icu) to MinGW but I have issues. When working directly in a command tool, I'm able to build the library (directly calling configure and make). But as soon as I ask Conan to run the same commands, the build fails.
My work is available in my [fork](https://github.com/osechet/conan-icu) of the ICU package. To test it, I open a Windows command tool with a MinGW gcc 4.8 in the path. I call `conan test_package -s compiler=gcc -s compiler.version=4.8`. The `configure` step works fine but the `make` step fails. During the build the library generates executables and libraries that are then used to generate more files. The build fails when calling one of these executables (`genrb.exe`). It tries to load a dynamic library generated during the build but fails to do so. When using the 'not-conan' generated library, the same executable works.
So it seems using conan leads to a problem in the generation of the dynamic lib but I cannot find what is it. I don't know if it means something but the wrong file is always 1 byte bigger than the good one.
I compared the build logs from the 2 builds and I don't see major differences. I suspect an environment difference I compared the result of the `env` command and I don't see any differences.

Do you have an idea of what is happening?

Are there good practices to work with MinGW and Conan?

**Comment by memsharded** [comment]
I have had a look to your conanfile.py and it is strange that it fails. Your lines:

```python
self.run("wget -q -O icu/source/config.guess http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD")
self.run("wget -q -O icu/source/config.sub http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD")
self.run("copy icu\\source\\config\\mh-mingw icu\\source\\config\\mh-unknown")

self.run("bash -c './icu/source/runConfigureICU MinGW --prefix=%s --enable-shared=yes --enable-tests=no --enable-samples=no'" % self._mingw_path(self.package_folder))
self.run("make")
self.run("make install")
```
Are you sure exactly those lines work without conan in your project? Because the ``ConfigureEnvironment`` is not being used at all, so the effect of those lines would be the same as running them on the terminal, there is no reason they shouldn't work.

As a side issue, is there some reason that the first lines cannot be run in the ``source()`` method? They look like retrieval of files, maybe could be done just once there, then copied for each build, instead of wget. Furthermore, if using ``tools.download`` would be more portable than calling ``wget``, so that might work for MinGW in the regular *cmd* terminal.

**Comment by annulen** [comment]
FYI, I've prepared MinGW 5.3 package: https://www.conan.io/source/icu/57.1/annulen/stable

I'm using MSYS environment with MinGW compiler provided by Qt SDK, it works for me without updating config.guess and config.sub

**Comment by osechet** [comment]
@memsharded Yes, I'm sure I run the exact same commands (except the prefix value). I removes the ConfigureEnvironment for this reason, to ensure the environment was the same.
I agree, the first steps should be done in the `source()` method but I'm still trying to make it works so I didn't tidy up the code yet since I'm not sure these lines are needed.

@annulen Thanks, I'll have a look to your code. Is is working for Visual Studio and Linux as well?

**Comment by annulen** [comment]
Yes, and it also should work on macOS. Feel free to submit pull requests to https://github.com/Vitallium/conan-icu

**Comment by osechet** [comment]
@annulen When using your package in a Msys console, I got an error message saying it cannot detect my configuration. I tried in a msys-mingw console and it worked. 
I tried my own package in a msys-mingw console and it works. I can even remove the config.guess update. 

It confirms my guess about an environment problem but I still don't understand.
However it seems Vitallium is updating its original package for MinGW. I will just wait for its modifications.

**Comment by annulen** [comment]
Vitallium actually merged my changes https://github.com/Vitallium/conan-icu/pull/2

I have no idea about config.guess failure, I remember having the same problem a while ago but it didn't reproduce for me now

**Comment by osechet** [comment]
@annulen To start an msys console, I can choose between 2 executables: one for a 'pure' msys and one for a mingw console. I compared both environment and there are several differences and `uname` does not return the same values. I'm pretty sure it's the reason why `configure` does not recognize the 'pure' msys environment. To configure its environment msys uses the `MSYSTEM` env var and set others variables in the `/etc/profile` file.
It's interesting to know the difference, however it's a kind of problem since it forces people to open a specific environment to be able to build the package or any package that requires it.

**Comment by annulen** [comment]
Yes, I'm using "MinGW-w64 Win32 Shell" console
