### ISSUE TITLE
[bug] conan_build_info `--skip-env` flag behaves counterintuitively

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#6144]
The [`--skip-env` flag is True by default](https://github.com/conan-io/conan/blob/d42ec055d459489c184b160cafbd3f200ceb6d41/conans/build_info/command.py#L83).  This means the `--skip-env` arg must be added to **not** skip the capturing of env vars.

I think either the default value or the name of the arg should be changed to avoid confusion.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: n/a
  * Conan version: 1.20.4
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
run `conan_build_info --v2 create buildinfo.json --lockfile=conan.lock` 
and env info is **not** captured.

run `conan_build_info --v2 create buildinfo.json --skip-env --lockfile=conan.lock` 
and env info is captured

**Comment by czoido** [comment]
Hi @GordonJess,
You are right, it's counterintuitive, we'll fix it for the next release.
Thanks a lot for reporting.

**Comment by lasote** [comment]
We have removed the `--skip-env` argument and `--multi-module`. We want to simplify the build info generation until we prove it is useful and working, so capturing the environment is not the main use case and probably will be covered by the jenkins/artifactory plugin.
To be released today at 1.20.5
