### ISSUE TITLE
[feature] Allow custom generators to create executable files

### ISSUE THREAD

**Issue by Morwenn** [conan-io/conan#6155]
When creating a custom generator, could it be possible to specify the permissions of the files that will be created?

Context below.

---

As part of my efforts to simplify people's life at work I created a custom generator that produces a launcher script as follows (as well as other scripts, hence the dictionary in `content`, stripped down for the example):

```python
class launcher(Generator):
    """
    This class creates files to automate the building and launching steps
    of projects depending on our framework. In order to work correctly
    they require that the project also uses the generator "virtualenv".

    They basically wrap the meaningful build instructions into calls to
    activate_run.sh and deactivate_run.sh.
    """
    @staticmethod
    def __strip(text):
        """
        Function to properly format a script.
        """
        return '\n'.join(line.strip() for line in text.split('\n') if len(line.strip()))

    @property
    def filename(self):
        pass

    @property
    def content(self):
        return {
            # Create a script to launch an executable
            "launch.sh": self.__strip("""
                #!/bin/bash
                source `dirname ${BASH_SOURCE[0]}`/activate_run.sh
                # ... export more env variables ...
                $1
                source `dirname ${BASH_SOURCE[0]}`/deactivate_run.sh
            """)
        }
```

In our documentation I tell them to run the script as follows:

```sh
source build/launch.sh build/bin/executable_name
```

However we sometimes need to launch said script as `sudo` (but only sometimes, we don't want it to happen all the time), and the use of the `source` command makes it awkward. Ideally, I wish that users of the launch script could just type the following command when they need to use `sudo`:

```sh
sudo ./build/launch.sh build/bin/executable_name
```

However that doesn't work because as far as I know Conan doesn't allow to create such a script with executable permissions, and I have to teach them to use `chmod u+x ./build/launch.sh` and to not use `source` if they want to run the executable with `sudo`. So, assuming that I don't have an XY problem and that Conan doesn't offer a better solution for what I'm trying to achieve (I might have missed something), would it be possible to add a way for custom generators to create executable files if needed?

Thanks!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Right now, not even our generators that create scripts are creating them with `u+x` permissions... but it should be useful too. I'm not sure which one should be the syntaxis, or maybe there is some reason not to do it, but let's have a look into it.

Thanks for the suggestion

**Comment by Morwenn** [comment]
Syntax-wise it looks difficult to cram into `content` so the logical step to keep the current design would probably be to add a `permissions` property that would either return the permissions in the format used by `os.chmod` or a dictionary of such permissions whose keys should match those in `content`.

**Comment by Morwenn** [comment]
If needed I've got a simple prototype implementation here: https://github.com/Morwenn/conan/commit/94d16c9c781d21b4f9577fb3bd335fafdd061d31

**Comment by seanmlyons22** [comment]
@jgsogo, this would be incredibly helpful for us at my company too. Any thoughts on @Morwenn 's implementation?

**Comment by memsharded** [comment]
I think this escapes the scope of generators, and enters the territory of toolchains and automation.
Generators are intended to generate files that gather information about the dependencies, so those files can be used by others. In this case, the sentence:

> In order to work correctly they require that the project also uses the generator "virtualenv".

Is an indicator that it is more than a generator, or at least different. A generator that will not work unless you use also another generator sounds a bit fragile or weak.

Not saying that I don't want to consider this utility or possible automation, but maybe the approach is different, we need to think about it.

**Comment by seanmlyons22** [comment]
@memsharded I don't disagree that perhaps generators shouldn't depend on another generator.

> Generators are intended to generate files that gather information about the dependencies, so those files can be used by others.

Agreed. Currently, we're only using `conanfile.deps_env_info`, though we have a different use case than @Morwenn .
We're generating a `.sh` file that can be run by consumers like `./script.sh`.

**Comment by Morwenn** [comment]
Conan itself generates  `activate_run.sh` and friends, so even if my example is not the best one it might still be a desirable feature.

**Comment by seanmlyons22** [comment]
@Morwenn I completely agree. @memsharded any thoughts?

**Comment by naggerx** [comment]
We would like to see that feature too.
We are also generating .sh files, to be called by the user.

**Comment by memsharded** [comment]
Hi all,

Conan has evolved a lot since this feature request:

- Now there is the ``generate()`` method in recipes, that can be used to generate and tune the build, without needing to explicitly write a generator. 
- Modern generators like ``CMakeDeps`` are customizable in ``generate()``.
- Generators should no longer extend from ``Generator`` class, they can be any form, just put it in a ``python_require`` to reuse the functionality, and then be called in the ``generate()`` method. But they can write files and execute any user action, including changing permissions over files.
- For user CLI invocation via ``-g`` the generator should be a class, take ``conanfile`` in the constructor and implement a ``generate()`` method. This method can do anything, writing files, and changing permissions of the file.
- The new ``VirtualBuildEnv`` and ``VirtualRunEnv`` generate sh/bat files, so far it hasn't been required to specify +x permissions, but if any generator needs to do it, it could be customizable too.

So I'd say with the new features this issue could be considered resolved? Please have a look and tell, thanks!

**Comment by Morwenn** [comment]
I haven't used Conan for big projects in some time. I originally opened that issue to solve an actual problem we had at work, but I haven't worked there for well over a year, so I won't be able to evaluate how much the current state of things improves on my old problem.

If the new generators `generate()` method can indeed execute any code, then it should be plenty enough. I do remember that users explicitly required the `launcher` generator from the `conanfile.txt` - if that use case still works too, then I believe that my old issue is solved.

Thanks for the hard work 😄

**Comment by memsharded** [comment]
> Thanks for the hard work 

Many thanks @Morwenn !


So @seanmlyons22 @naggerx I am closing this issue as solved, please feel free to open a new ticket if you have any other issue with the above proposed solutions. Thanks!

**Comment by memsharded** [comment]
I am closing this at 1.40, the ``generate()`` method has been available for a while, but some of the above details, like ``VirtualBuildEnv`` is more recent, so just to make sure.
