### ISSUE TITLE
[bug] Concurrency issue - scm `auto` - multiple simultaneous creates

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#6158]
I'm attempting to build multiple `profiles` in parallel on a single machine.
The `export` folder doesn't seem to be locked by concurrent processes.
When I run two `conan create` at the same time regardless of using same or multiple profiles, one of them usually fails with files related to `exports` or `export_source`. I've seen several different errors.

`ERROR: Unable to create folder /home/mh70023/.conan/data/PackageA/1.0.0/_/_/export_source
[Errno 17] File exists: '/home/mh70023/.conan/data/PackageA/1.0.0/_/_/export_source'`

`FileNotFoundError: [Errno 2] No such file or directory: '/home/mh70023/.conan/data/PackageA/1.0.0/_/_/export/conanfile.py'`

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16.04.6 LTS
  * Compiler+version: N/A
  * Conan version: 1.20.4
  * Python version: 3.5.2
  * revisions is enabled

### Steps to reproduce (Include if Applicable)
Same sample repo I used to reproduce the issue:
https://github.com/Mark-Hatch-Bose/ConanPackageA
* Run multiple `conan create . & conan create .` with same or different `profiles`
* Observe Error

### Logs (Executed commands with output) (Include/Attach if Applicable)

Note that one of the `create` fails with `FileNotFoundError: [Errno 2] No such file or directory: '/home/mh70023/.conan/data/PackageA/1.0.0/_/_/export/conanfile.py'`
```
mh70023@mh70023-vm:/scratch/ConanPackageA$ conan create . & conan create .
[1] 28096
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
Linter warnings
    WARN: Linter. Line 2: Unused import os.path
Linter warnings
    WARN: Linter. Line 2: Unused import os.path
PackageA/1.0.0: PackageA/1.0.0 is locked by another concurrent conan process, wait...
PackageA/1.0.0: If not the case, quit, and do 'conan remove --locks'
PackageA/1.0.0: Revision deduced by 'auto': 0ed6fb4315d89ea329ea9d0787f29aceb8ba9567
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 1938, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 359, in create
    lockfile=args.lockfile, ignore_dirty=args.ignore_dirty)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 81, in wrapper
    return f(api, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 342, in create
    ignore_dirty=ignore_dirty)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/cmd/export.py", line 128, in cmd_export
    ignore_dirty)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/cmd/export.py", line 243, in _capture_scm_auto_fields
    _replace_scm_data_in_conanfile(os.path.join(destination_folder, "conanfile.py"), scm_data)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/cmd/export.py", line 250, in _replace_scm_data_in_conanfile
    content = load(conanfile_path)
  File "/usr/local/lib/python3.5/dist-packages/conans/util/files.py", line 214, in load
    with open(path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mh70023/.conan/data/PackageA/1.0.0/_/_/export/conanfile.py'

ERROR: [Errno 2] No such file or directory: '/home/mh70023/.conan/data/PackageA/1.0.0/_/_/export/conanfile.py'
mh70023@mh70023-vm:/scratch/ConanPackageA$ PackageA/1.0.0: Revision deduced by 'auto': 0ed6fb4315d89ea329ea9d0787f29aceb8ba9567
PackageA/1.0.0: SCM: Getting sources from folder: /scratch/ConanPackageA
PackageA/1.0.0: A new conanfile.py version was exported
PackageA/1.0.0: Folder: /home/mh70023/.conan/data/PackageA/1.0.0/_/_/export
PackageA/1.0.0: Using the exported files summary hash as the recipe revision: 98f1e5b9f2b0e45b4acd9545912d728c 
PackageA/1.0.0: Package recipe modified in export, forcing source folder removal
PackageA/1.0.0: Use the --keep-source, -k option to skip it
PackageA/1.0.0: Exported revision: 98f1e5b9f2b0e45b4acd9545912d728c
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=5
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CONAN_BUILD=True
CONAN_RUN_TESTS=False
DONT_TAR=1
PackageA/1.0.0: Forced build from source
Installing package: PackageA/1.0.0
Requirements
    PackageA/1.0.0 from local cache - Cache
Packages
    PackageA/1.0.0:3d8c85c54f7fd2f6b48e52cc88af1bf81a02a93d - Build

PackageA/1.0.0: Configuring sources in /home/mh70023/.conan/data/PackageA/1.0.0/_/_/source
PackageA/1.0.0: Copying previously cached scm sources
PackageA/1.0.0: Copying sources to build folder
PackageA/1.0.0: Building your package in /home/mh70023/.conan/data/PackageA/1.0.0/_/_/build/3d8c85c54f7fd2f6b48e52cc88af1bf81a02a93d
PackageA/1.0.0: Generator txt created conanbuildinfo.txt
PackageA/1.0.0: Calling build()
PackageA/1.0.0: WARN: This conanfile has no build step
PackageA/1.0.0: Package '3d8c85c54f7fd2f6b48e52cc88af1bf81a02a93d' built
PackageA/1.0.0: Build folder /home/mh70023/.conan/data/PackageA/1.0.0/_/_/build/3d8c85c54f7fd2f6b48e52cc88af1bf81a02a93d
PackageA/1.0.0: Generated conaninfo.txt
PackageA/1.0.0: Generated conanbuildinfo.txt
PackageA/1.0.0: Generating the package
PackageA/1.0.0: Package folder /home/mh70023/.conan/data/PackageA/1.0.0/_/_/package/3d8c85c54f7fd2f6b48e52cc88af1bf81a02a93d
PackageA/1.0.0: Calling package()
PackageA/1.0.0 package(): Packaged 1 '.txt' file: conanbuildinfo.txt
PackageA/1.0.0: Package '3d8c85c54f7fd2f6b48e52cc88af1bf81a02a93d' created
PackageA/1.0.0: Created package revision 8492e7a85eba0eec9a3dbf114de4ffe6
```

**Comment by jgsogo** [comment]
Hi, @Mark-Hatch-Bose 

Currently, Conan doesn't support concurrency, two clients running in parallel cannot share the same cache safely.

Maybe we could lock properly the `export` and `export_sources` directories to avoid the race condition you see here, but there is still a big risk that would require blocking the whole cache for each run: if a package is using requirements, it is consuming header files and libraries from many different places in the cache belonging to different references. If another job runs at the same time it might install different revisions of the references the first job was consuming and... 💣  then the best thing would be a failure, a missing file, an incompatible header failing at compile time...

We are thinking about how to support this in the future, but right now there is no workaround for it.

**Comment by Mark-Hatch-Bose** [comment]
> If another job runs at the same time it might install different revisions of the references the first job was consuming and... 
Yes - that makes sense. Should the entire cache be locked then until such a feature is supported?
This case can be closed either way. Thanks!

**Comment by memsharded** [comment]
I would recommend the following:

- Do ``conan export`` first, not concurrently
- Fire ``conan create --no-export`` concurrently (or something like ``conan install <pkg-ref> --build=pkg``, concurrently.)

That might help to avoid that concurrency issue. Let me know how it goes.

The Conan cache supports some level of concurrency, there are some locks in some places, for example for concurrent installs (as they happen in CLion, for example, not easy to avoid). The export doesn't have that mechanism, but a lock for concurrent creates might be doable. The thing is that a concurrent ``conan create`` will be exporting many times the recipe to the cache, capturing the SCM data, copying the sources... Even if there are locks, this is not avoidable with a ``create``.

**Comment by Mark-Hatch-Bose** [comment]
I did attempt the above of using `export` and `-ne` but it appeared that the cache would lock anyway between the builds - causing it to still be serialized. By using multiple caches - I was able to parallelize the `conan create` and see the expected parallelization benefit!

>The thing is that a concurrent conan create will be exporting many times the recipe to the cache, capturing the SCM data, copying the sources... Even if there are locks, this is not avoidable with a create.

Yes - that is understood. However I think the benefits on certain build servers and codebases greatly outweighs the cost of the copying.

This was more of a stepping stone - as I move towards a build cluster running each `profile` build individually in a docker container in parallel. So it is not that important.

Should I go ahead and close this ticket? I still feel that the cache should lock for export and serialize the builds if this is not supported - but let me know your thoughts.

**Comment by memsharded** [comment]
Yes, I think this ticket can be closed at the moment, it doesn't look like that we will be able to focus on this on the short term. The line of work will be doing download in parallel and other features that will improve the speed of installing things in a new cache, so using different caches for parallel jobs will be the recommended approach.
