### ISSUE TITLE
[question] build and package functions are not called in workspace build

### ISSUE THREAD

**Issue by guestliu** [conan-io/conan#6163]
I found the 'build' and 'package' functions are not called in workspace build. How does it work?

I just clone the code in
https://github.com/conan-io/examples.git
to test the workspace
![image](https://user-images.githubusercontent.com/29087704/69928680-614aef80-14f7-11ea-980e-1dca997b41c3.png)
It works perfectly

So, I changed some code
![image](https://user-images.githubusercontent.com/29087704/69928763-9fe0aa00-14f7-11ea-9b1f-f12838e4184f.png)
It works perfectly too!!!

I can't understand why it works.

**Comment by memsharded** [comment]
Sorry this question was never responded, it fell through the cracks.

Conan 2.0 editables support calling the ``build()`` method with ``--build=editable``.

Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this as outdated.
