### ISSUE TITLE
[bug] Cannot apply patch via tools.patch()

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#6164]
### Environment Details (include every applicable attribute)
  * Operating System+version:ubuntu 18.04
  * Compiler+version: clang8
  * Conan version: 1.20.3
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)

1.
Download patch from here:
https://codereview.qt-project.org/c/qt/qtdeclarative/+/82078
Click on the download button
2.
Download source code from Qt 5.12.4
3.
Conan code:
```
tools.patch("qt5/qtdeclarative", "0c695fc.diff", strip = 1)
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
qt/5.12.4@company/patched: Configuring sources in /lhome/user/.conan/data/qt/5.12.4/mbition/patched/source
WARN: 0c695fc.diff: source/target file does not exist:
  --- b'quick/items/qquickitemview.cpp'
  +++ b'quick/items/qquickitemview.cpp'
```

When using manually in the console:
```
patch -p1 < 0c695fc.diff
```
it worked.

**Comment by nolange** [comment]
with the patch from #5320, t seems that the patch functionality will strip away an additional layer for new files (atleast).
ie. instead of file `utils/cmake/Makefile.am`, an file `cmake/Makefile.am` wil be created.

(id really recommend using the patch tool directly if available...)

**Comment by memsharded** [comment]
``tools.patch`` was removed in 2.0, closing as outdated
