### ISSUE TITLE
Support options in profile

### ISSUE THREAD

**Issue by NingyuShi** [conan-io/conan#617]
Seems like options is left out in the profile, some times it's useful to have a global option setting applied across package.

**Comment by memsharded** [comment]
Agree. Shouldn't be too difficult to implement (just in case someone wants to make a try and contribute a PR)

**Comment by piponazo** [comment]
Me and my team are also interested in this functionality. 

Some people want to use different options than the default ones for some recipes. Without this feature, they need to change the main conanfile.py of the project and be careful to not commit those changes.

**Comment by memsharded** [comment]
Yes, I agree, this totally makes sense. Would like to be able to add it to next 0.20, but it is already huge, so planned for next 0.21.

**Comment by memsharded** [comment]
Hi @NingyuShi, @piponazo 

Just released in 0.21 you can use options in profiles. Please test it and report if necessary. Thanks!
