### ISSUE TITLE
[bug] Conan CI fails inspect command

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#6172]
Hi! 

When a new PR is created, Conan starts a new CI build in Jenkins, however, one of those steps is failing:

https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanTestSuite/detail/PR-5997/30/pipeline/138#step-169-log-1277

As you can see, `conan inspect` fails, but there is no error report about.

**Comment by danimtb** [comment]
Sorry, the link is not working or pointing to anywhere from my side. Could you be more explicit about the issue?

**Comment by danimtb** [comment]
ping
