### ISSUE TITLE
[bug] UNC paths are not supported with Python 3.8

### ISSUE THREAD

**Issue by ngerke** [conan-io/conan#6173]
Python 3.8 has a new os.path.realpath behavior:
```
Python 3.8.0b4 (tags/v3.8.0b4:d93605d, Aug 29 2019, 23:21:28) [MSC v.1916 64 bit (AMD64)] on win32
>>> import sys, os
>>> sys.executable
'X:\\Python38\\python.exe'
>>> os.path.realpath(sys.executable)
'\\\\SERVER\\Programs\\Python38\\python.exe'
```

```
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
>>> import sys, os
>>> sys.executable
'X:\\Python37\\python.exe'
>>> os.path.realpath(sys.executable)
'X:\\Python37\\python.exe'
```
https://bugs.python.org/issue37993

We need to subst our workspaces on jenkins slaves to avoid the 260 char path limit on windows, with Python 3.8, conan can't resolve the path correctlly:

```
conan config install --verify-ssl False https://****:****@.../conan_settings.git
Trying to clone repo: https://****:****@.../conan_settings.git
'\\localhost\c$\j\ws\...\cache\.conan\tmp_config_install'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
fatal: destination path '.' already exists and is not an empty directory.
ERROR: Can't clone repo: Command 'git clone "https://****:****@.../conan_settings.git" .  ' returned non-zero exit status 128.
```

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: -
  * Conan version: 1.12.3
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)

Build a Project on a subst or net use drive with Python 3.8

**Comment by memsharded** [comment]
Hi @mietzen 

Thanks for your report.

There are several things we need to fix this:

1. Configure and activate Python3.8 builds in our CI. So far Conan is developed and tested up to 3.7 only
2. Reproduce the failure with a test
3. Analyze the impact of this behavior. Even if the python bug report was closed, this is clearly changing behavior in Python, so need to consider alternatives. Then re-evaluate scope and complexity of this issue.

**Comment by memsharded** [comment]
quick question in the meantime:

- Have you tried activating the long path management in Windows? From python 3.7 it is possible to do it
- Have you tried the conan built-in ``short_paths`` workaround?

Please let me know, and what was your experience with these approaches.

**Comment by mietzen** [comment]
Long path is activated and we are also using conans short_paths. 

Here is way it doesn't work for us:

- short_paths: Some legacy projects are still so messy that they exceed the 260 char limit even with the short path
- long path management in windows: we are using msbuild vc141 which has it's own max_path: https://github.com/microsoft/msbuild/issues/53#issuecomment-459062618, this will eventually be removed in the next msbuild version

For now were fine with a rollback to Python 3.7.x.

**Comment by memsharded** [comment]
Hi @mietzen 

We have done some progress here. We also have 3.8 in our CI, and we have green builds of our develop branch. Indeed python 3.8 did some breaking changes that forced us to fix some things.

I am having a look to your issue with the paths, and so far, couldn't reproduce. What I have tried:

```bash
$ subst X: C:\Users\memsharded\cache_unit
$ set CONAN_USER_HOME=X:/myhome
$ conan install zlib/1.2.11@ # Installing works
$ conan config install https://github.com/bincrafters/bincrafters-config.git  # works
```

All files are correctly installed in C:\Users\memsharded\cache_unit\myhome\.conan

Could you please provide some further details to help reproducing this issue?

**Comment by mietzen** [comment]
@memsharded I'm currently not at work, I'll test it the week after next.

**Comment by jgsogo** [comment]
@mietzen did you managed to give it another look?

**Comment by memsharded** [comment]
Hi @mietzen 

Conan is now tested in CI with Python 3.8, everything is looking good but this ticket. It would be great to be able to close it, but we would need some help to try to reproduce it.

I have also tried a subst folder that contains both the conan home and the python virtualenv. Everything seems to work fine.

**Comment by memsharded** [comment]
Closing 1.23 soon, so this has been moved forward. Looking forward to getting your feedback to reproduce it, so far, we couldn't. Thanks!

**Comment by ngerke** [comment]
Hi I tested it again with conan 1.22.2 and Python 3.8.2, The Probleme seems to be resolved.

**Comment by memsharded** [comment]
Ok, thanks! 

Then we consider Python 3.8 fully supported with this from 1.23. Do not hesitate to open a new ticket if further issues, thanks!
