### ISSUE TITLE
[feature] Virtualenvs should create a sandbox

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6175]
Taken from this comment: https://github.com/conan-io/conan/pull/5989#pullrequestreview-326075695

For Conan v2.0 we want the virtualenvs to restore the environment to the state it was before activating it (same variables, same values). So, anything modified inside the virtualenv will be discarded after deactivating it.

**Comment by CDSRV** [comment]
https://github.com/cea-hpc/modules

**Comment by AbrilRBS** [comment]
After discussing it, we have come to the conclusion that this is not the place for Conan to interfere. If anyone wants this functionality, tools such as the linked one can be used independently of Conan. (Note that Python's virtualenvs also do not create a sandbox, so it's nothing that a user would find weird) We're closing this, but if anyone has any reminding issues with this, we're happy to hear your suggestions so feel free to reopen/open a new issue :)
