### ISSUE TITLE
[question] Recommandations to properly address the CXX Standard (11, 14, ...)

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#6176]
We came to realize that our repositories are not handling the CXX standard in a way compatible with Conan's approach: usually, our root `CMakeLists.txt` is explicitly setting it with:

    set(CMAKE_CXX_STANDARD xy)

Effectively replacing any value that could have been set from `CONAN_CMAKE_CXX_STANDARD`

---

This problem might be because this setting is conceptually a bit different from the other settings and options:

* If we consider an usual setting like `build_type` (or the `shared` option), it is common for the project to be able to build with the different values.
* Yet, the CXX standard is more deeply coupled with the actual code: if we write C++14 in the repository, this is such a strong requirement that one might feel compelled to hardcode it directly in the CMake scripts, otherwise the code will not build when doing a default cmake configure and generate.

Now, we are wondering how we should actually handle that:

* Hardcoding makes for an erroneous recipe. The recipe will pretend to build against the provided conan setting `compiler.cppstd` because it will accept the value without complaining, but it is actually lying.
* On the other hand, if we make no provision at all in the `CMakeLists.txt`, then when someone is building the repository out of Conan (which is a very common case for developers in our organization) it becomes their responsibility to provide the `CMAKE_CXX_STANDARD` variable explicitly when initially calling `cmake`. This is also problematic, because it is yet another thing to remember for developers, plus it put the pressure on them to "know" the actual CXX standard for each project (when it really feels like the repository itself should know the CXX standard it is using).

Are there any best practices/recommendations to address this issue?

Thank you for reading!

**Comment by memsharded** [comment]
Related: https://github.com/conan-io/conan/issues/6157

**Comment by memsharded** [comment]
This has changed a lot since then:

- Conan 2.0 strongly recommends to pass ``compiler.cppstd`` in the profiles. Many recipes can raise if not defined
- CMakeToolchain converts this setting to the corresponding CMake syntax
- The ``validate()`` methods report and raise in case the provided cppstd is not enough for some package.

I think we can close this ticket now, but if you have any question about the new solutions, please report a new ticket
