### ISSUE TITLE
[feature] Use Bottle's AutoServer instead of the default WSGIRefServer

### ISSUE THREAD

**Issue by odormond** [conan-io/conan#6181]
Hello!

Currently the conan server can only handle a single request at a time due to the fact it uses Bottle's WSGIRefServer (the default). However Bottle support other servers, some of them supporting multi-threaded processing. It even includes an AutoServer which can detect a large list of installed server library and use one instead.

By switching the default server to `auto`, this would allow to easily enables multi-threaded request processing simply by installing, for example, `paste`.

Here is a sample patch that implements this feature:
```diff
--- a/conans/server/rest/server.py      2019-12-04 15:54:26.466681443 +0100
+++ b/conans/server/rest/server.py      2019-12-04 15:31:42.759189071 +0100
@@ -42,5 +42,5 @@
         port = kwargs.pop("port", self.run_port)
         debug_set = kwargs.pop("debug", False)
         host = kwargs.pop("host", "localhost")
-        bottle.Bottle.run(self.root_app, host=host,
+        bottle.Bottle.run(self.root_app, server="auto", host=host,
                           port=port, debug=debug_set, reloader=False)
```

If none is found it falls back to the default WSGIRefServer so it should be backward compatible.

Cheers,

Olivier

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry @odormond this was not handled back then.

I am closing this ticket as inactive, if you are still interested in this, I'd suggest submitting a PR.
In any case, if performance is important, I'd recommend the free ArtifactoryCE server, that can be downloaded from our downloads page. Thanks!
