### ISSUE TITLE
[question] How to upgrade from (quite) old conan_server to newest?

### ISSUE THREAD

**Issue by sibebo** [conan-io/conan#6182]
Thanks for a very nice package manager 👍 

**What will be the proper way of upgrading Conan - and making sure data is migrated correctly?**

I am trying to update our *conan_server* from version ```0.25.1``` to the current, ```1.20.5```. The server is running Ubuntu Server 16.04.

So far, I have...
* backed up the entire data storage
* pulled from the git repo, checked out tag ```1.20.5```
* changed to python3
* run the python requirements scripts
* started the service (so far from command prompt)

The service runs. From client I can search and see all our packages - *But* I am not able to do e.g.:  
```conan install my_package/2.1.0@my_repo/release```  
I get the error: ```ERROR: Unable to find 'my_package/2.1.0@my_company/release' in remotes```.

I have tried running ```conan_server --migrate``` as suggested by the service. Apparently, it had no effect.

I hope you can point me in the direction of a migration/update guide or give me a hint on how I can make it run again.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @sibebo 

> Thanks for a very nice package manager 

thanks!! 😄 

I think in your case the best approach would be a client-based one. 0.25.1 is too old. Have you been upgrading the Conan client? I would try:

- Download everything with the latest Conan client that works with that server. The ``conan download`` command, paired with a script using ``conan search`` result might do the work.
- Upload everything again to the new server.

I would also recommend trying the Artifactory CE. It is totally free, it has a WebUI, better permissions, generic repositories, and the most important is way more performant that conan_server, it will scale much better and with better concurrency and robustness.

Please let me know if the above works.

**Comment by sibebo** [comment]
Hi @memsharded 

Thanks for the prompt reply.

I managed to roll back to the old version `0.25.1` and download all packages to my local machine.  

I'll keep you updated when everything is running in the updated version. Right now, considering the jump to Artifactory CE. Sounds tempting 😃.

Best regards, Simon

**Comment by memsharded** [comment]
Thanks @sibebo for telling.

As it seems we have no immediate action from our side, I am going to close this issue, but please report when you are done, or if you have any further question or need help. Thanks!
