### ISSUE TITLE
[feature] proposing a "install" folder different from the "package" folder

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6183]
The conan cache will be:

pkg-ref
   source
   build/shaXXX
   package/shaXXX
   install/shaXXX

- The manifest is computed always from package/shaXXX which is immutable
- The install folder is initially an exact copy of the package folder
- Recipes ``install()`` methods can do local changes to the packages.
- Read Only Mode only in install, by default. That is never packaged again.
- Packages are uploaded only from the package folder
- The conan_package.tgz can be cached always without a problem in the package folder, for efficiency (now we are removing it)
- Things never moved back from install folder to package folder
- Generators always refer to the install folder
- This allow for multiple, custom "install" folders. Do you want to have a local, flat folder in your project, with everything copied there? Doable.

This will help with a couple of long standing use cases:

- Users wanting to do local modifications to packages, that can only be done **post-install**. Like frameworks that need to re-wire things to the OS absolute paths, RPATHs, etc. And that only works with some code in the target machine after installation.
- The ReadOnly case right now is a bit of a pain, because it modifies the bits, then if you re-upload, it will change the .tgz hashes, and it is not possible to restore the permissions, because if something was already RO, you will change that too.
- There have been complains that conan needs to re-compress the ``conan_package.tgz`` thas has just been downloaded/installed, and this is slow and inefficient
- The possibility of having your own copy of the dependencies locally in your user folder. This has been traditionally workarounded with imports(), deploy() and the deploy generator, but all of these have the issue that the generators no longer refer to that information.

There are a couple of things to take into account as possible disadvantages:
- There might be an extra copy of files in package/install folders, taking double the space.
- The extra copy will take some time. Doing a full copy with ``shutil.copy_tree`` will be faster than packaging (pattern matching based copy), but for big packages, it will still be something.
- The ``--update`` behaviors might need to do an extra check and will also involve this extra step.

**Comment by lasote** [comment]
Document the use cases.

**Comment by memsharded** [comment]
Implemented with the ``deployers`` approach
