### ISSUE TITLE
[conan package creating for several os-build]

### ISSUE THREAD

**Issue by AleksandrFOF** [conan-io/conan#6189]
Hello Team, 
I would like to ask you is there is a way to create one conan package with one recipe but for two os_build in one command? 
Using multiple settings does not work (i.g. conan create . **-s os_build**="Windows" -s **os_build**="Linux"

As the result it should be one conan package applicable for both os_build.
Please advise me how can I proceed here.

Thank you in advance.

- [ YES ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @AleksandrFOF 

to create (different) packages for different settings, you need 2 separate commands:
```bash
$ conan create . -s os_build="Windows"
$ conan create . -s os_build="Linux"
``` 

But if I understood correctly, you want just 1 package that will be ok for both systems. In that case, depending on what exactly you want you could:

- Just do NOT declare the ``os_build`` setting in your recipe. If the recipe does not declare the ``os_build``, the package will be valid for any ``os_build``.
- If you still need to have different packages for other OSs, like OSX, then you can model that in your package_id() method:

```python
def package_id(self):
     if self.settings.os_build == "Windows" or self.settings.os_build == "Linux":
             self.info.settings.os_build = "WinOrLinux" # Note it is self.INFO.settings
```

You could read more about it in https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#defining-a-custom-package-id.

Please tell me if the above helps. Thanks!

**Comment by memsharded** [comment]
This was stale for a long time, and seems the above response still holds, so this can be closed, but please @AleksandrFOF tell otherwise, thanks.
