### ISSUE TITLE
[question] Is there a preferred method of consuming a header-only library?

### ISSUE THREAD

**Issue by gazzatav** [conan-io/conan#6190]
I am inexperienced with Conan but I packaged a header-only library, successfully, I think!  There is a package with a folder inside with all the include files.  To test whether I could consume the package I added a #include to md5.cpp in the poco project example and added a require to the conanfile.txt.  In a clean build folder I ran conan install and cmake but when running make the included file was not found.
Looking at the CMakeLists.txt for  md5.cpp I saw that it has target_link_libraries set to CONAN_LIBS but no target_include_directories.
Looking at conanbuildinfo.cmake I saw that the only variables set with the package directory are CONAN_TUT_ROOT, CONAN_BUILD_DIRS_TUT and CONAN_CMAKE_MODULE_PATH.  None of these seem like the variable for the job, I would have expected it to be set in CONAN_INCLUDE_DIRS or CONAN_INCLUDE_DIR_TUT.  This leads me to wonder if my recipe is incorrect.  The tut library contains some examples to build which is why I have left settings etc in the recipe:

```
from conans import ConanFile, CMake, tools


class TutConan(ConanFile):
    name = "tut"
    version = "1.0.0"
    license = "Custom - retain copy of licence"
    author = ""
    url = ""
    description = "A template based header only unit testing library"
    topics = ("tut", "template", "testing")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=False"
    generators = "cmake"

    def source(self):
        self.run("git clone https://github.com/mrzechonek/tut-framework.git tut")
        # This small hack might be useful to guarantee proper /MT /MD linkage
        # in MSVC if the packaged project doesn't have variables to set it
        # properly


#    def build(self):        
    #     cmake = CMake(self)
    #     cmake.configure(source_folder="tut")
    #     cmake.build()

        # Explicit way:
        # self.run('cmake %s/hello %s'
        #          % (self.source_folder, cmake.command_line))
        # self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self.copy("*.h", dst="./", src="tut/include/")
        self.copy("*.hpp", dst="./", src="tut/include/")        
        self.copy("*tut.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_id(self):
        self.info.header_only()
```

So, is there a preferred way of consuming a header only library?

**Comment by uilianries** [comment]
Hi @gazzatav !

To know how to package a header-only library, you can follow the [docs](https://docs.conan.io/en/latest/howtos/header_only.html#how-to-package-header-only-libraries). Also, you can take a look in some examples, like [picojson](https://github.com/conan-io/conan-center-index/blob/7a34d7b321de8455b1697c803a38086b208674e5/recipes/picojson/all/conanfile.py)

A header-only package should be consumed as any other package, there is no special option.

The package_id [header-only](https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-info-header-only) only should be applied you are creating a header-only package, otherwise, it should not be used. It works to fit your package ID according your settings, not for consuming.

Also, as you are using the [cmake generator](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_generator.html#cmake-generator), you will need to invoke the `conan_basic_setup()` in a cmake wrapper file, or injecting in the author's CMakeLists.txt. You can take [gflags](https://github.com/conan-io/conan-center-index/blob/7a34d7b321de8455b1697c803a38086b208674e5/recipes/gflags/all/CMakeLists.txt) as an example. That recipe has a CMakeLists.txt which calls `conan_basic_setup()` and include the author's cmake file by calling `add_subdirectory`.

> Looking at the CMakeLists.txt for md5.cpp I saw that it has target_link_libraries set to CONAN_LIBS but no target_include_directories.

The `target_include_directories` will be solved automatically when calling `conan_basic_setup`.

Regards!

**Comment by gazzatav** [comment]
Thanks but the Poco md5 example from the docs does use conan_basic_setup
and the include path is NOT resolved. I did read the header only docs but
it's about packaging not consuming.  I am packaging this in this context as
header-only, I don't understand why I shouldn't use the package_id part.
The package is in my local cache and required by the project, please could
you address the issue of which variable to use in
target_include_directories or tell me if I should use a different cmake
macro/function.

**Comment by uilianries** [comment]
Hi @gazzatav !

Is your project available on Github or in any other public repo? I can take look  and help you.

**Comment by gazzatav** [comment]
Hi @uilianries 
No I don't have this as a project on Github but you have the recipe there, just export it and install it.  Then create a .cpp file and include it or use the poco example like I did.
I have no problem getting this to work, the question is **Is there a preferred method of consuming a header-only library?**
I was confused by the CMakeLists.txt for md5.cpp at [](https://docs.conan.io/en/latest/getting_started.html).  It uses CONAN_LIBS in target_link_libraries.  I believe that the whole point of conan_basic_setup is to set variables such as CMAKE_INCLUDE_PATH so that Conan does not become part of the build system.  I am currently using target_include_directories(md5 CMAKE_INCLUDE_PATH) and the header is found.
I would appreciate if someone could check my package function.  I have since changed it to:
<self.copy("*.hpp", dst="include/tut/", src="tut/include/tut/")>
Is there something special for Conan in the destination include directory?  Even though the dst is set as include/tut/, I use #include tut/tut.hpp and it works just like I want.

**Comment by uilianries** [comment]
> I have no problem getting this to work, the question is Is there a preferred method of consuming a header-only library?

Again, no it should be consumed as any other package.

> I was confused by the CMakeLists.txt for md5.cpp at . It uses CONAN_LIBS in target_link_libraries

Yes, because md5.cpp uses a pre-built library, so `CONAN_LIBS` will contain Poco libraries names. 

As you are creating a header-only, there is no need for CONAN_LIBS, but you can use CONAN_PKG::tut if you want (by conan_basic_setup(TARGETS)).

Anyway, take a look here: https://github.com/uilianries/conan-tut

This recipe is working, just run `conan create .`

**Comment by gazzatav** [comment]
@uilianries 
Thank you for your help but I am learning nothing from this.  I have looked at how you packaged the library but it is completely different from how I did it by cloning,  I don't understand the changes you made to my recipe - it's completely different.  I have no answers to my questions about packaging. If I take out the line target_include_directories(md5 CMAKE_INCLUDE_PATH) the build fails.

I cloned your repo from git and ran conan create . as you said and I got this:

 2019-12-06 23:05:58  vostro in ~/Projects/builds/newtut
± |master ✓| → conan create .
usage: conan create [-h] [-j JSON] [-k] [-kb] [-ne] [-tbf TEST_BUILD_FOLDER]
                    [-tf TEST_FOLDER] [-m [MANIFESTS]]
                    [-mi [MANIFESTS_INTERACTIVE]] [-v [VERIFY]] [-b [BUILD]]
                    [-e ENV] [-o OPTIONS] [-pr PROFILE] [-r REMOTE]
                    [-s SETTINGS] [-u] [-l [LOCKFILE]]
                    path reference
conan create: error: the following arguments are required: reference
ERROR: Exiting with code: 2

**Comment by gazzatav** [comment]
Hi @uilianries
Of course next I tried conan create .  gazzatav/stable and it built fine.  I can see that you changed the git clone to a homepage and some extract method but that's a bit too much python for me.  I went back to my original poco example and removed the target_include_directories(md5 ${CMAKE_INCLUDE_PATH} and it still worked.  I can only conclude that this is because I got the packaging function right in my later attempts.  I can find no documentation on the dst and src fields that explains the magic namespacing that is obviously occurring.  I do not understand at all how your package function works in the example you gave.  You use the same self.copy patterns for the *.hpp and *.h even though they are at different levels and yet they end up in the correct places.  Where is the documentation of this behaviour?

**Comment by memsharded** [comment]
Please have a look at https://docs.conan.io/en/latest/reference/conanfile/methods.html#package

If it didn't work with ``conan create .`` and you were forced to use ``conan create . user/channel``, then maybe you are using an older version of Conan. Please use latest version of Conan, or at least report which version you are using.

The best to get help for these cases is to put the thing in a Github repo, in your case I would recommend a Github repo with:
- A folder "tut" with the conanfile.py to package the "tut" library (header-only)
- A folder "consumer" with the effort you did so far to try to consume the "tut" folder.
- A Readme with the steps followed (1. conan create tut ... 2. cd consumer 3. conan install ....)

Then it will be much easier for the community to help. Thanks!

**Comment by gazzatav** [comment]
Hi James
Thanks for your reply. The project works fine. I think the original reason
it didn't was that I didn't understand how the package function worked. I
think I shall put in a suggestion that the package function documentation
is improved. There's a lot of stuff relating to it that is mentioned
incidentally all over the place like default directories, keep path. I
looked at the definition in conan_file.py the comments there were possibly
incorrect as well, giving examples like dst=includes.  It seems you have to
be quite knowledgeable about python. I don't know if the copy function is
core, whether it's recursive etc.
Anyway, it seems that the point of the question has been missed and I shall
have one last go at getting an answer that isn't about making the example
work and maybe generate some debate and contemplation!
What i.want to know is best practice not just do this easy thing and it'll
work.
Cheers
Gary

**Comment by gazzatav** [comment]
@memsharded 
I am using Conan version 1.17.0.  I did recently try to update pip on Ubuntu 18.04 and ended up with pip not working at all - not a python expert - followed some advice to purge python3 and ended up with no gnome session, no desktop and a world of pain!
@uilianries 
By 'preferred' I mean best practice rather than easy or simple.
In a presentation by Diego Rodriguez-Losada in Sydney that I watched last night he answered a question saying if you want better control, just leave out conan_basic_setup and use the variables from conanbuildinfo.cmake directly.  Coincidentally I already tried the direct approach with variables like the ones I mentioned above. 
Modern Cmake, according to Daniel Pfeiffer, Matthieu Ropert et al is all about targets, access specifiers and the avoidance of global or directory-wide variables.  In the Conan docs about [generators](https://docs.conan.io/en/latest/integrations/build_system/cmake cmake_generator.html) there is another way of using conan_basic_setup that uses targets. 
My original question was about consuming a header-only library but it seems now the answer would apply to consuming all libraries.  I tried the conan_basic_setup(TARGETS) macro in the example CMakeLists.txt below.  It worked and as a bonus, rtags was able to index the header.

```
cmake_minimum_required(VERSION 3.1.2)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)

conan_basic_setup(TARGETS)

add_executable(md5 md5.cpp)

target_link_libraries(md5 PRIVATE CONAN_PKG::Poco CONAN_PKG::tut)
```

From the modern cmake perspective it feels like this should be the 'preferred' way or best practice.  What do you think?

Cheers
Gary

**Comment by memsharded** [comment]
Hi Gary!

> From the modern cmake perspective it feels like this should be the 'preferred' way or best practice. What do you think?

Yes, that makes sense, this is better and more aligned with modern CMake practices.

We haven't changed our documentation yet to use this for 2 reasons:

- We had a bunch of users stuck in Cmake 2.8.12, requiring the global method.
- We are improving the integration with CMake, and providing better generators like ``cmake_find_package_multi``, which allow to use the ``find_package()`` cmake syntax.

It is in our roadmap to stabilize the integration with CMake and changing the defaults, one of our goals for 2020. Thanks for your feedback, yet another indication that this is needed.

Cheers!
