### ISSUE TITLE
How to handle dependencies which different APIs depending on autotools configuration?

### ISSUE THREAD

**Issue by Xeverous** [conan-io/conan#6192]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I want to build the [elements library](https://github.com/cycfi/elements) which requires **cairo**. Now, the problem is, that saying "lib X needs lib Y version a.b.c" is not enough in the case of some autotools-based libraries, one of which is cairo.

**cairo (and many other autotools-based libraries) have a `./configure` script that changes the public API of the library, depending on the command line options. Some of the library code is generated during the build and the amount of possible header contents grows exponentially with the amount of configure switches. Different build configurations result in different, incompatible APIs.**

Example `./configure` output:

```
cairo (version 1.16.0 [release]) will be compiled with:

The following surface backends:
  Image:         yes (always builtin)
  Recording:     yes (always builtin)
  Observer:      yes (always builtin)
  Mime:          yes (always builtin)
  Tee:           no (disabled, use --enable-tee to enable)
  XML:           no (disabled, use --enable-xml to enable)
  Xlib:          no (requires X development libraries)
  Xlib Xrender:  no (requires --enable-xlib)
  Qt:            no (disabled, use --enable-qt to enable)
  Quartz:        no (requires CoreGraphics framework)
  Quartz-image:  no (disabled, use --enable-quartz-image to enable)
  XCB:           no (requires xcb >= 1.6 xcb-render >= 1.6 https://xcb.freedesktop.org)
  Win32:         yes
  OS2:           no (disabled, use --enable-os2 to enable)
  CairoScript:   yes
  PostScript:    yes
  PDF:           yes
  SVG:           yes
  OpenGL:        no (disabled, use --enable-gl to enable)
  OpenGL ES 2.0: no (disabled, use --enable-glesv2 to enable)
  OpenGL ES 3.0: no (disabled, use --enable-glesv3 to enable)
  BeOS:          no (disabled, use --enable-beos to enable)
  DirectFB:      no (disabled, use --enable-directfb to enable)
  OpenVG:        no (disabled, use --enable-vg to enable)
  DRM:           no (disabled, use --enable-drm to enable)
  Cogl:          no (disabled, use --enable-cogl to enable)

The following font backends:
  User:          yes (always builtin)
  FreeType:      no (disabled, use --enable-ft to enable)
  Fontconfig:    no (disabled, use --enable-ft to enable)
  Win32:         yes
  Quartz:        no (requires CoreGraphics framework)

The following functions:
  PNG functions:   yes
  GLX functions:   no (not required by any backend)
  WGL functions:   no (not required by any backend)
  EGL functions:   no (not required by any backend)
  X11-xcb functions: no (disabled, use --enable-xlib-xcb to enable)
  XCB-shm functions: no (requires --enable-xcb)

The following features and utilities:
  cairo-trace:                no (requires dynamic linker and zlib and real pthreads)
  cairo-script-interpreter:   yes

And the following internal features:
  pthread:       yes
  gtk-doc:       no
  gcov support:  no
  symbol-lookup: no (requires bfd)
  test surfaces: no (disabled, use --enable-test-surfaces to enable)
  ps testing:    no (requires libspectre)
  pdf testing:   no (requires poppler-glib >= 0.17.4)
  svg testing:   no (requires librsvg-2.0 >= 2.35.0)
  win32 printing testing:    no (requires ghostscript)
```

The problems are:

- Cairo leaks its implementation switches and the build configuration to the public API. Any change in cairo's build configuration can break projects which depend on it (including elements).
- Cairo's dependencies are different depending on the `./configure` options.
- Multiple of cairo's dependencies (pixman, freetype, fontconfig, libpng) have exactly the same problem. Cairo can break due to incompatible build configuration of any of them.

My questions:

- How can I specify that a project depends on specific configuration of cairo (and any other such library)? Cairo's configuration is stored as `config.h` with 60 `#defines` which depend on the configure, compiler, system and more.
- Cairo is currently not available in conan-center. I want to build it by myself, but I need its dependencies built with specific configuration ... the problem recurses untill it hits dependency on the C standard library.
- Currently there is no way to inspect package build configuration, am I right? There is a `fontconfig/2.13.91@conan/stable` package available but I need to know whether it was build with `FT_WITH_BZIP2`, `FT_WITH_PNG`, `FT_WITH_ZLIB`.

**Comment by memsharded** [comment]
Hi @Xeverous 

Yes, the first important piece is that the Cairo package is still not in Conan-center. The way to go is to provide its dependencies first, then the Cairo package. That can be a big amount of work, so I'd suggest to start filing libraries requests as Github issues in https://github.com/conan-io/conan-center-index, so the community might also help with some of those.

Then, the way to represent that variability of libraries configurations are the **options**. There are some other packages in Conan-center that already have a bunch of these options. Check for example https://github.com/conan-io/conan-center-index/blob/95f6184905907bfbcebc278092a1c88a6dd81e0b/recipes/boost/all/conanfile.py#L36

Then, one thing is to model those options, but for Conan-center it is also important to use a good default configuration, something that plays well with the rest of the packages already existing in Conan-center, otherwise the combinatoric explosion would be intractable. Conan-center-index will build binaries for those default configurations, but users wanting to use other options, can always build from sources (and store their binaries in their own servers).

Yes, there are some ways to inspect the build configurations, for example ``conan search fontconfig/2.13.91@conan/stable -r=remote-name``. Try having a look to center.conan.io too.

Please let me know if this clarifies it a bit. Thanks.

**Comment by Xeverous** [comment]
> That can be a big amount of work, so I'd suggest to start filing libraries requests as Github issues in https://github.com/conan-io/conan-center-index, so the community might also help with some of those.

I'm actually amazed that you are basically writing build scripts from scratch for every library that does not support CMake (or anything more stable). Some of the stuff I wanted to build had so convoluted autotools scripts that it felt close to impossible to get them right in any other build system, especially considering they do some codegen during the build.

> users wanting to use other options, can always build from sources (and store their binaries in their own servers).

Has anyone considered forwarding these build scripts to original repos? Chances are that for some libraries it's easier to build some libraries by asking conan to do it locally than to use library's original build system.

> Then, the way to represent that variability of libraries configurations are the options.

Ok, so cairo does support options and the `inspect` does exactly what I wanted to check.

> Then, one thing is to model those options, but for Conan-center it is also important to use a good default configuration, something that plays well with the rest of the packages already existing in Conan-center, otherwise the combinatoric explosion would be intractable

Hmm enable everything possible? Most the autools projects I have encountered simply extend their API when configured to use more dependencies.

**Comment by memsharded** [comment]
> I'm actually amazed that you are basically writing build scripts from scratch for every library that does not support CMake (or anything more stable). Some of the stuff I wanted to build had so convoluted autotools scripts that it felt close to impossible to get them right in any other build system, especially considering they do some codegen during the build.

We totally understand the pain, we actually envisioned Conan at the beginning too like an automated script to replace the repositories complex READMEs telling how to compile the code.

> Has anyone considered forwarding these build scripts to original repos? Chances are that for some libraries it's easier to build some libraries by asking conan to do it locally than to use library's original build system.

Totally. The previous way to contribute packages to Conan-center was from either the library repo or from an external repo (not managed by Conan), and creating the binaries in Bintray, then doing an "inclusion-request" from there. But that was too much work and caused friction in library authors, didn't want to put extra stuff on their repos. So we have prioritized the convenience of the package maintainers (not library authors) that now can contribute with PR to conan-center-index central repo, and Conan will build the binaries automatically, do the checks for quality in the automated pipeline, etc, streamlining the contribution process. And this will also be a major improvement for consumers of packages, that will find more packages and more updated, with latest compiler versions, etc. From there we will probably more slowly go back to library authors repo to include recipes there to simplify their usage, but surely that will go slower.

> Hmm enable everything possible? Most the autools projects I have encountered simply extend their API when configured to use more dependencies.

Yes, that is a good default. Optional dependencies make more sense when it is very complicated and time-consuming to get them. If they are already available in the package manager, then it is no longer an issue, and it is good enough to enable everything. If some users later want to use less footprint or something they can opt-out them.

**Comment by Xeverous** [comment]
I don't have more questions then, wish you good luck so that one day I can download what I need without pain.

**Comment by memsharded** [comment]
> I don't have more questions then, wish you good luck so that one day I can download what I need without pain.

Sure, keep an eye on conan-center and conan-center index, the community is contributing a lot and things are evolving fast, and we are still in EAP, so things are looking good. Thanks for the feedback.
