### ISSUE TITLE
[feature] Conan CLI should implement an end-of-args sentinel

### ISSUE THREAD

**Issue by brianthelion** [conan-io/conan#6195]
Conan provides nice integration mechanisms (see [hooks](https://docs.conan.io/en/latest/reference/hooks.html) and [custom generators](https://docs.conan.io/en/1.12/howtos/custom_generators.html)) but does not provide an obvious method for driving the behavior of integrations from the command line.

It is tempting to want to solve this using the package `-o` options, `-s` settings, or `-e` environment, but so-doing may have unintended consequences. General-purpose command line options that do *not* affect the the package hash are distinctly missing.

One possible solution is for the `conan` CLI to accept (but not consume) command line arguments after a sentinel sequence. [Historically](https://unix.stackexchange.com/questions/147143/when-and-how-was-the-double-dash-introduced-as-an-end-of-options-delimiter), the sentinel sequence on *nix systems is a lone double-dash (`--`). Support for the double-dash sentinel is idiomatic, widely implemented, and well-supported by Python tooling. It would be a very welcome addition to the `conan` CLI.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @brianthelion 

Sorry, I don't understand this feature proposal. What would be the extra arguments for? Who would be consuming them? How is that related to the package hash (package ID)? The env-vars do NOT affect the package ID, only the settings and the options.

**Comment by brianthelion** [comment]
@memsharded Thanks for fielding this.

We are building an application that uses Conan under the hood. We rely on the Conan API to build and cache a particular kind of binary, and our code takes several complex actions from there. We integrate with Conan at three levels:

1. Hook -- We provide a custom hook that is triggered at `conan install` time.
2. Generator -- We provide a custom generator that is triggered at `conan install` time.
3. `conanfile.py` -- We provide an overloaded `conans.ConanFile` class that enforces the expectations of both the hook and the generator.

This all works quite well, and we've only needed to provide a small amount of glue code on top of your `@api_method`s.

The main issue is that we need to pass some arguments to our integrations that are *entirely orthogonal* to any and all processing by `conans.client.conan_api.Conan.install_reference(...)`. There does not appear to be a way to do this, outside of the below.

As a simple example, we'd like to be able to set the output path for our custom generator at run time. Right now, we use the following implementation:

```python
import os
from conans.models import Generator

class CustomGenerator(Generator):
    @property
    def filename(self):
        default_path = os.path.join(os.getcwd(), "custom.yml")
        return os.environ.get("GEN_OUTPUT_PATH", default_path)
    ...
```

This appears to be the best we can do without de/re-constructing the top-level client `@api_method` call. IMHO, this is an abuse of environment variables; the kind of hack that has never panned out for me in the long run.

What we're asking for with this feature request is a method of communicating with our integrations that has incrementally more precision than the above. Obviously, a Python interface would be ideal but, based on my review of the Conan source, my guess is implementing such an interface would involve a lot of refactoring for you.

By providing an end-of-args sentinel for the CLI, you open a communication channel between the calling user and any custom integrations that doesn't require much refactoring at all. This seems like a nice stop-gap that would encourage rich custom hooks and generators without having to build an explicit interface thereto.

**Comment by memsharded** [comment]
Hi @brianthelion 

Now I start to understand the use case. The only thing is that I see that interface too narrow for the wide number of applications that might be running under Conan. Note that for a "create" or "install --build", it is likely that a few apps will be running (git, cmake, VS or Make almost for sure, plus occasionally protoc, perl, nasm, etc. etc), and also a bunch of other Conan custom extensions (hooks, python_requires, generators). We certainly cannot forward those arguments to all those things, it will certainly not work.

But regarding generators, the truth is that we almost added parameters to generators, and we didn't very last minute. The feature has been recently gaining more traction, I understand you would be happy being able to forward arguments to generators, am I right?

**Comment by brianthelion** [comment]
@memsharded Glad I was able to clarify.

In addition to the generator, we're also using `os.environ` to support similar kinds of simple "business logic" in both our hook and custom `ConanFile` class. Throughout, the `os.environ` logic is orthogonal to Conan's core functionality, but we don't have a better way to make it work.

So to answer your question directly, yes, we are interested in being able to forward arguments to generators. But per the above, that's not sufficient to cover our use-case. We also need to be able to forward arguments to hooks and `conanfile`s as well.

The fact is that without a more complete plugin system, `conan install . -- --gen-output-path=...` is not appreciably different than `GEN_OUTPUT_PATH=... conan install .` They are both ad-hoc interfaces. The difference is that implementing the CLI version would get the community talking about what a complete plugin interface should look like. For this reason, I think it's an appropriate baby-step.

**Comment by brianthelion** [comment]
@memsharded Any additional thoughts on this? Happy to discuss in detail on the slack channel if that would be helpful.

**Comment by memsharded** [comment]
Hi @brianthelion 

Yes, this seems to be too open to be introduced now, that we already have so many other things ongoing.

It is not a baby step, propagating arbitrary arguments to many internal places is not that obvious change, and it is necessary to carefully think about the interface, and many different consequences it might have. A redesign of the command line is necessary anyway, we will be discussing it soon while facing Conan 2.0, (will probably be kicked off in ConanDays in 2 months), so let's bring this conversation there.

**Comment by memsharded** [comment]
Many things have changed since this was discussed:

- Latest Conan 1.56 already implements a new ``conf`` mechanism, that allows for arbitrary and structured configuration items, that any recipe can selectively capture and process.
- It is an structured way, as it allows multiple types (booleans, strings, lists, dicts, etc)
- It allows composition and multiple origins, can be defined in profile ``[conf]`` sections, command line arguments, and direct tool_requires
- Via ``conanfile.conf`` it is available at recipes, hooks, and other extensions.
- It is also possible to make the desired ``conf`` items be part of the ``package_id`` (Conan 2.0).

This will be the recommended way to pass generic information from user side and commands to recipes, hooks and others, so I think this can be closed.
