### ISSUE TITLE
How to completely change remote?

### ISSUE THREAD

**Issue by itJunky** [conan-io/conan#6199]
My remote for conan changed ip address and task with conan install just fail everytime after that.

In documentation i found two commands **remote add** and **remote remove**. After try it, i see new ip in file registry.json. But when i run conan install . --update, i see error with my old IP.

How can i completely change ip for my remote?

Conan version is 1.12.0

**Comment by itJunky** [comment]
It's apply after some magic dances with some combinations of commands:
conan remote clean
conan remote add NAME URL VSSL
conan install . --update -s compiler.version=12

And i'm really don't know what is really help me. Why i can't just change remote by add/remove commands? Why i need magic dances with it?

**Comment by memsharded** [comment]
Hi @itJunky 

There are 2 possibilities you might want to try:

To update an existing remote:

```bash
$ conan remote update <name> <url>
```

To add or update an existing remote:
To update an existing remote:

```bash
$ conan remote add <name> <url> --force
```

I think either might solve your issue without ``remote clean`` or ``remote remove``. Please have a look and tell me if it helps.

**Comment by itJunky** [comment]
All two variants doesn't work for me. I see changes in registry.json, but if i try to do conan install, i see error with old IP address...

**Comment by memsharded** [comment]
That is very weird, maybe it is due to the cached credentials. Could you please try again with those two variants, but running ``conan user --clean`` too first? 
If you could paste here the error logs, that would also help.

**Comment by memsharded** [comment]
Closing as outdated and staled.

Conan 2.0 doesn't track remote origin anymore, just the credentials per remote name, so this shouldnt be an issue
