### ISSUE TITLE
Same hash generated for release and debug

### ISSUE THREAD

**Issue by pvaddina** [conan-io/conan#6200]
I want to create one package containing two artifacts: one for release and the other for debug. I setup my conanfile such that the SHA is generated based on the following settings (as the documentation says): 

    settings = "os", "arch", "build_type", "compiler"

And I am executing the following conan create command (The variables within the braces are to be replaced by a python dictionary):

conan create . {package_name}/{version}@integration/{channel_name} -s build_type={build_type} -s arch={arch} -s compiler={compiler} -s compiler.version={compiler_version} -s os={os} -o {package_name}:shared=False

But I notice that for both release and debug configurations, the same hash is generated and as a result the artifact generated first (debug) one is being overwritted with the one generated later (release), so effectively having only the release artifact. 

Debug Configuration
> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Debug
> compiler=Visual Studio
> compiler.runtime=MDd
> compiler.version=12
> os=Windows
> os_build=Windows
> [options]
> yaml-cpp:shared=False
> [build_requires]
> [env]
> 
> yaml-cpp/0.6.2.10@integration/win: WARN: Forced build from source
> yaml-cpp/0.6.2.10@integration/win (test package): Installing C:\repos\conan-yaml-cpp\test_package\conanfile.py
> Requirements
>     yaml-cpp/0.6.2.10@integration/win from 'rs_MRT-ART-BASE-private' - Cache
> Packages
>     yaml-cpp/0.6.2.10@integration/win:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
> 
> yaml-cpp/0.6.2.10@integration/win: Building your package in C:\Users\vaddina\.conan\data\yaml-cpp\0.6.2.10\integration\win\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

Release configuration

> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Release
> compiler=Visual Studio
> compiler.runtime=MD
> compiler.version=12
> os=Windows
> os_build=Windows
> [options]
> yaml-cpp:shared=False
> [build_requires]
> [env]
> 
> yaml-cpp/0.6.2.10@integration/win: WARN: Forced build from source
> yaml-cpp/0.6.2.10@integration/win (test package): Installing C:\repos\conan-yaml-cpp\test_package\conanfile.py
> Requirements
>     yaml-cpp/0.6.2.10@integration/win from 'rs_MRT-ART-BASE-private' - Cache
> Packages
>     yaml-cpp/0.6.2.10@integration/win:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
> 
> yaml-cpp/0.6.2.10@integration/win: Building your package in C:\Users\vaddina\.conan\data\yaml-cpp\0.6.2.10\integration\win\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

What am I doing wrong ? Thank you all for your time !!!

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Hi @pvaddina !

The package id could be affected if your recipe has a custom setting or package id. Could you paste you Conan recipe here?

**Comment by pvaddina** [comment]
Thank you for your super quick reply. Indeed I had a package_id method implemented. After removing it, this issue is resolved. I am not really sure I need this method. I was just experimenting due to the issue #2407 

I wish there was better documentation

**Comment by pvaddina** [comment]
Posted a bit too early ... 
Anyway, just wanted to indicate that #2407 is my original issue to which I still have no work around.

**Comment by uilianries** [comment]
@pvaddina You can learn more about package id here: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#defining-a-custom-package-id

BTW, did you try the yaml-cpp version in Conan Center Index? 
The recipe is here: https://github.com/conan-io/conan-center-index/blob/master/recipes/yaml-cpp/all/conanfile.py
You can install that package by running `conan install -r conan-center yaml-cpp/0.6.3@`
