### ISSUE TITLE
[bug] Unable to connect to conan-center=https://conan.bintray.com

### ISSUE THREAD

**Issue by adriendu-cae** [conan-io/conan#6212]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16.04 container in Docker 2.0.0.3
  * Compiler+version: GCC 5.4.0
  * Conan version: 1.18.4
  * Python version: 2.7.12

### Steps to reproduce (Include if Applicable)
I used the new Visual Code Remote Container extension to attach to my Ubuntu Container and I open the folder from the container where my whole Visual Studio project is.
When "configuring" the CMake project, I see the Conan output (see below).
However, the compilation is fine and done properly.
The problem I was having is that Intellisense was not working properly until I added the following in c_cpp_properties.json Visual Code configuration file :

            "browse": {
                "path": [
                    "/home/cae/.conan",
                    "${workspaceFolder}/"
                ],
                "limitSymbolsToIncludedHeaders": true
            }

This problem doesn't appear with Visual Studio 2017 so this seems related to Visual Code.

Here is how we install / setup Conan in our Dockerfile:

RUN mkdir /home/cae/conanvenv
RUN python3 -m venv /home/cae/conanvenv/
RUN . /home/cae/conanvenv/bin/activate && pip install --upgrade pip
RUN . /home/cae/conanvenv/bin/activate && pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org 'conan==1.18.4' \
 && conan remote add conan-center https://conan.bintray.com False -f \
 && conan profile new default --detect \
 && conan profile update settings.compiler.libcxx=libstdc++11 default \
 && conan install jsonformoderncpp/3.6.1@vthiery/stable \
 && conan install boost/1.71.0@conan/stable \
 && conan install libpq/11.5@bincrafters/stable \
 && conan install eigen/3.3.7@conan/stable

I also tried to update the cerfificates with apt update && apt install ca-certificate but no luck.

### Logs (Executed commands with output) (Include/Attach if Applicable)

[cmake] boost/1.71.0@conan/stable: Not found in local cache, looking in remotes...
[cmake] boost/1.71.0@conan/stable: Trying with 'conan-center'...
[cmake] ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
[cmake] Unable to connect to conan-center=https://conan.bintray.com

**Comment by memsharded** [comment]
A quick hint:
- Doing several ``conan install`` consecutively is problematic. It can lead to inconsistents graphs, with conflicting dependencies, without noticing. You need to put your dependencies in a conanfile (.txt for simplicity) and do a single ``conan install``

Also, you are explicitly disabling SSL for conan-center with ``conan remote add conan-center https://conan.bintray.com False``. Why? You should use SSL to connect to conan-center.

**Comment by adriendu-cae** [comment]
For the multiple `conan install`, I'll fix that.

As for the disabling of SSL, it is needed because my company uses Digital Guardian that spoofes SSL certificates ...

**Comment by memsharded** [comment]
I have no idea how Digital Guardian works, but it is a bit suspicious that the connection is throwing a ``(Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed`` error. So a couple of questions:
- Is Conan working correctly in other native systems in your company that runs on the same Digital Guardian software? Like running Conan directly on Windows, or on a Linux machine?
- Have you considered other topologies? It is a good practice for other package managers with Artifactory to NOT access directly the central repos, in this case conan-center from the clients, but to set up a remote repo in Artifactory that proxies and caches things from Conan-center. This way you are protected from network and Conan-center outages, and your builds, etc will be much faster.

**Comment by adriendu-cae** [comment]
It is the same thing for native systems I'm afraid.
As for another topology, I'll see with the right people in our company.
Thanks !

**Comment by memsharded** [comment]
> It is the same thing for native systems I'm afraid.

If you are sure about this, then I suspect that it is related to the Digital Guardian software. If maybe you could try to temporarily disable the Guardian and use Conan-center with the standard SSL enabled, just to rule out other reasons, that would be great. Maybe you can ask support from your company IT to do this test?

**Comment by adriendu-cae** [comment]
I will try to see what they say ! I'll you know what I'm able to do, thank you !

**Comment by memsharded** [comment]
Closing as inactive. Also ConanCenter moved to center.conan.io
