### ISSUE TITLE
[bug] Inspect shows version as None when using `set_version()`

### ISSUE THREAD

**Issue by AshleighAdams** [conan-io/conan#6213]
When using `set_version()` to version the package, `conan inspect` doesn't run the function, and as a result, prints "None". I would expect it to execute the function and include the version in the result out.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 7
  * Compiler+version:
  * Conan version: 1.21.0
  * Python version: (via Conan Windows installer)

### Steps to reproduce (Include if Applicable)
Create a new conanfile.py, replacing the version with:

```py
 def set_version(self)
    self.version = "1.0"
```
Then run `conan inspect . --attribute version`.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan inspect . --attribute version
version: None
```

**Comment by memsharded** [comment]
Hi @AshleighAdams 

Thanks for reporting. You are right, it is not working as expected. I have submitted a PR https://github.com/conan-io/conan/pull/6214 to fix it, assigned for next 1.22 release.
