### ISSUE TITLE
valid vs invalid overrides

### ISSUE THREAD

**Issue by Martin581** [conan-io/conan#6215]
Dear contributors,

We would like to distinguish between invalid and valid overrides. We are unsure whether the feature exists, or rather what kind of features exit in that regard.

To explain the two terms, consider PkgA & PkgB, both including PkgC; where hierarchy between PkgA and PkgB shall be irrelevant; and where PkgB may require a particular version of C, respectively.

A valid override would be:
PkgA/1.0.0: requirement PkgC/[~=1 >=1.2] overridden by PkgB/1.0.0 to PkgC/1.3.0

An invalid override would be
PkgA/1.0.0: requirement PkgC/[~=1 >=1.2] overridden by PkgB/1.0.0 to PkgC/1.1.0

Now, we would like to throw errors for invalid overrides only. 
However, with the variable CONAN_ERROR_ON_OVERRIDE we would receive an error in either way.

In another regard on that subject, we understand that "Dependency Hell" is an informatics term that describes the NP-hard problem of determining within a set of N interdependent packages of at most k versions each whether a feasible N-tuple of non-conflicting versions for each tuple exists. Would Conan.io try the k^N possible tuples, in order to find a feasible installation? If not, since the problem naturally exists, which rules does Conan.io apply for determination of the particular tuple that it proposes? That information could help us for understanding of how to design requirement ranges.

**Comment by jgsogo** [comment]
Hi, @Martin581

I'm running your example with the last Conan version available, and it raises the error related to the conflict when `pkg` requires `pkgC/1.1.0`:

![image](https://user-images.githubusercontent.com/1406456/70705783-fbb7e980-1cd4-11ea-9f72-649a38b35064.png)

It is true that the version range resolution in Conan can be improved, I'm not sure if we can do it without entering the NP problem as you mention. Right now Conan resolves the version-ranges one by one starting from the root of the graph: when a version range is found, Conan looks for the matching version in the cache and passes it to the requirements (like an override). A conflict is only raised when two different versions coming from different branches reach a node (a diamond in the graph). This is what happens with the graph in the first image, but if I change it to something like the following one there won't be any error:

![image](https://user-images.githubusercontent.com/1406456/70706368-0fb01b00-1cd6-11ea-8352-ec6622ff54ac.png)

The problem we are facing when we try to resolve all the graph together is that choosing a different version of a library may change the topology of the graph itself (it may have different requires, build requires, python requires,...) so it requires downloading more recipes and building more graphs. For small graphs it can be done, but for bigger ones it may take too much time.

**Comment by Martin581** [comment]
Hi @jgsogo ,

Thank you very much for your replies and thoughts.

I learned from your reply that the hierachy of A and B cannot be made irrelevant because conan.io determines its proposed version-tuple based on exactly that hierarchy.

Yet, regardless of the way of proposing (implying overrides), is there a way to distinguish whether the conducted proposal/override is valid or invalid?
The following demonstrates our problem:

We set CONAN_ERROR_ON_OVERRIDE=true, so to ensure that an error is thrown when invalid overrides take place. However, the following error was thrown when an intended (and valid) override took place.

ERROR: RootsolversPackage/2.6.0: requirement FinitediffPackage/[~=1 >=1.2] overridden by MinimizersPackage/2.2.3 to FinitediffPackage/1.2.0

We could benefit if errors were thrown on invalid overrides only. Is there a way for achieving this?

In case that is a bug.
conan version: 1.20.3
project: https://github.com/Martin581/ConanExtendedExample
plattform: windows 10 enterprise (invisible version), x64

**Comment by jgsogo** [comment]
No, there is nothing built-in that could help to differentiate between those valid and invalid overrides.

The key would be not to consider your example as an override but a version_range resolution which is exactly what it is happening there: someone downstream in the graph is forcing the version resolution to a specific version which is valid in the version_range. IMO it shouldn't be a warning or an error, it is a valid resolution for the version range.

This fix doesn't require to tackle the dependency-hell problem and it should be enough for your use case, don't you think so?

**Comment by Martin581** [comment]
Thank you.

As from your replies, I would specify the version tuple in the project (i.e., the conanfile.py of the highest node in the dependency graph determines all versions of all packages via requirements). Tuple proposal by user is reasonable because otherwise hard.

If I understand my supervisor correctly, the package manager would be supposed to install the packages as specified by the tuple, and respond with errors whenever a dependency range is violated (i.e. invalid override) by any package requirement of any package. Dependency ranges that are met are supposed to do nothing (i.e. no error on valid override). Now the question for me is just whether this can be realized with conan. As I interpret* from your reply, it can.

>> The key would be not to consider your example as an override but a version_range resolution which is exactly what it is happening there.

I understand from this, that the solution is to avoid errors on valid overrides by setting conan up so that it recognizes these (what I called) "valid overrides" as (what you identified as) "version_range resolution". 

So I assume that in the conan.conf the variable ERROR_ON_OVERRIDE must be false and that instead there is then another variable like ERROR_ON_INVALID_VERSION_RANGE_RESOLUTION that must be set true?
Otherwise, since I have been unable to find a way to set up conan in a way that achieves the described distinction in the last three days, I would be thankful for your help on doing so. *) If the interpretation was wrong <=> there is no according setup then I would close this subject and propose it as feature.

**Comment by Martin581** [comment]
Here is a pseudo-code to describe what we search for:

versionTuple x = conan.generate_version_tuple_proposal(myDependencyTree); // be it in whatever way: solve dependency hell, override bfs or dfs, use fancy heuristic.
bool feasible = conan.check_version_validity(myDependencyTree,x); // here conan checks for every node in the depencency tree whether x contains a version of a required package that lives outside the specified range of that depencency. If so, return false. Otherwise, return true.
if(!feasible){conan.stop_compilation(); conan.error_msg("tried versions "+x+" violates requirements of package <pkgname>");}

**Comment by AbrilRBS** [comment]
Closed as solved in Conan 2, where recipes that have hard requirements over the version of their dependencies can implement logic in their `validate()` method that ensures the expected library is within a range, such as

```
def validate(self):
   if Version(self.dependencies["mydep"].ref.version) >= "3.2":
      raise ConanInvalidConfiguration("mydep >= 3.2 not supported")
```
