### ISSUE TITLE
export-pkg --profile does not support [requires] section

### ISSUE THREAD

**Issue by DexterMagnific** [conan-io/conan#6216]
Hi,

I'm issuing an export package command like this:

```
conan export-pkg conanfile.py User/unstable \
                       --profile conaninfo.txt
```

with the following profile:

```
[settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++11
    compiler.version=9
    os=Linux

[requires]
    DspConversionFn/a082b1c

...
```

and I get the following error:

```
ERROR: Error reading 'conaninfo.txt' profile: ConfigParser: Unrecognized field 'requires'
```

removing the `requires` section works but is not correct.

Is there something I'm missing ?

Thanks

**Comment by jgsogo** [comment]
Hi, @DexterMagnific 

As the error says, `requires` is not a valid field inside a profile. A profile can contain `settings`, `options`, `env` (environment variables) and `build_requires`. Regular requirements have to be declared inside the recipe.

Profiles are usually stored in `<your-user-home>/profiles/` and the name `conanfile.txt` is usually reserved for simple recipes (more complex ones need a `conanfile.py`). So, probably, you should use a different file for the value of your `--profile` argument.

**Comment by DexterMagnific** [comment]
Hi, Thank you for your reply.

Let me go back to the origins.

I have a CMake based project which I export using export-pkg. This project itself requires some dependencies that I retrieve using conan-cmake.

I have a kind of chikken-egg problem, since conan-cmake will generate a conaninfo.txt for the project. 

The problem with this auto generated conaninfo.txt is that it does not contain options/settings specific to the project. It contains the correct dependencies though for exporting.

If I were to move the deps to conanfile.py, I will end up specifying the deps in two locations:
- in conanfile.py used for the export-package. In addition, a custom conanfile.txt has to be written that contains settings/options/env (the profile).
- in my CMakeLists.txt so that conan-cmake will retrieve them when building. this will generate a default conanfile.txt that does not contain export env/options.

What do you suggest me to not duplicate the deps inside the CMakeLists.txt and the conanfile.py ?
Is there some variable exported by conan_cmake_run() that contains the list of deps. I can use it to make replacements a conanfile.py.in using configure_file().

Thanks

**Comment by jgsogo** [comment]
Oh! Sorry, my fault, I read `conanfile.txt` where it was written `conaninfo.txt` 😓 

I think that now I understand your problem. You need the profile to use it in the `conan export-pkg` command so the package gets associated with the proper settings, right? I haven't used conan-cmake myself and it would be indeed a problem if you cannot get the profile in a file.

Let me invoke my colleague @czoido who knows much more about conan-cmake project, I'm sure he will be able to help you.

Thanks for your patience

**Comment by memsharded** [comment]
The ``cmake-conan`` integration has been completely changed in Conan 2.0, using the new CMake dependency providers and implementing a fully transparent integration that does not require to change the ``CMakeLists.txt``, and that defines dependencies in a ``conanfile``.

Closing this issue as outdated, but please create a new one if necessary, thanks!
