### ISSUE TITLE
[question] Package names that differ only by case vs Windows

### ISSUE THREAD

**Issue by db4** [conan-io/conan#6218]
`conan-center` repo contains both `OpenSSL` and `openssl` packages. I used to require `OpenSSL` in my projects, but now I need newer `openssl`. But I cannot install it into the local cache without removing `OpenSSL` first:
```
C:\Work>conan install openssl/1.1.1d@_/_
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: Requested 'openssl/1.1.1d' but found case incompatible 'OpenSSL'
Case insensitive filesystem can't manage this
```
What is the best way to work around this? Upgrading each and every package (including 3rd party ones) seems to be not an option.

**Comment by jgsogo** [comment]
Hi, @db4. Yes, we have introduced a new policy and now all the packages in `conan-center` will be lowercase (and also they won't have `user/channel`). One of the reasons was to avoid that kind of errors and make the search easier.

The best option I can recommend to you is to migrate all your projects to the new set of packages. About the transition, the Conan cache in the local machine should be considered like any cache as temporary storage, so it is safe to delete it all (remove the folder `~/.conan/data`).

One more thing, even though the name of the Conan package is lowercase, the targets and variables you consume in CMake should be the same as before (trying to match already existing modules from CMake where it is possible)

**Comment by db4** [comment]
> The best option I can recommend to you is to migrate all your projects to the new set of packages. 

Yes, it the long term it would the right choice.  But I can't do that immediately for everything just because something needs new `openssl`. Why `OpenSSL` and `openssl` cannot coexist in the local cache provided their versions are different? If I have `OpenSSL/1.0.2n@conan/stable` installed into `D:\.conan\data\OpenSSL\1.0.2n\conan\stable` why not to allow `openssl/1.1.1d` to install into `D:\.conan\data\OpenSSL\1.1.1d\_\_`? Directories `OpenSSL` and `openssl` are the same from Windows' point of view, just relax the check...

**Comment by jgsogo** [comment]
You can configure Windows to be case sensitive (I cannot know how many people use it, but if the added feature someone should have requested it), so we cannot assume that `OpenSSL` and `openssl` are the same directory. And, on the other hand, we cannot consider them to be different if the filesystem is not case sensitive. So, the safest assumption is to disallow having packages just with different casing. I think this is something we cannot change unless we have strong evidence that it is necessary.

**Comment by Blubbz0r** [comment]
Related: https://github.com/conan-io/conan/issues/1557

I'm actually having to go through the "change all openssl references in all of your packages" for the second time 😞. It is a huge pain. I'm also still not sure if it wouldn't be easier for everyone to just handle the filesystem case-insensitive on Windows (maybe all OS) at all times. Are there really people for whom it is important that 'OpenSSL/1.x' is a different package than 'openssl/1.x'?

**Comment by jgsogo** [comment]
Hi! On top of these issue there has been a problem with the CMake generators and casing for packages in `conan-center-index` and for Conan itself.  You can read about it starting in this comment https://github.com/conan-io/conan/issues/6269#issuecomment-570182130, but let me summarize it to you here too:

 * Behavior in the cache won't be modified: Conan will consider that `OpenSSL` and `openssl` are different packages and it will raise if you try to install a package and one with a different casing is already in the cache.
 * In `conan-center-index` all the package names will be lowercase (we are enforcing it with a hook)
 * Conan introduced several ways to change the name that is exposed to the consumer in the files generated by the [generators](https://docs.conan.io/en/latest/reference/generators.html):
   + `cpp_info.name`: it defines a different name that will be used **for all generators**, it affects the name of the files (i.e.: `FindXXXX.cmake`) and also the name of the variables in these files.
   + `cpp_info.names["<generator_id>"]`: same as above, but affecting only one generator.

   We are using these features in `conan-center-index` to match the expected filename and variables for CMake, for example. Depending on your Conan version, some of these features are already available or not, so these fields will be taken into account or not with the Conan you are running.


Maybe, your issues are not related to my previous dissertation, but I wanted you to know about it, it can be related and it is good to know the problems we are actually having and how we are dealing with them.

**Comment by jgsogo** [comment]
As the main issue regarding packages in Conan Center is already fixed, and the casing issue is better to centralize it in a single place (probably this issue https://github.com/conan-io/conan/issues/1557 that is targeted to 2.0), I'm closing this one, feel free to move any comment there.

Thanks
