### ISSUE TITLE
[bug] pkg_config generator has wrong casing in the requires section

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#6222]
coming from https://github.com/conan-io/conan-center-index/pull/471#issuecomment-565057342

Seems that there is a missing conditional to make the default name `.lower()` here:

https://github.com/conan-io/conan/blob/5336a31744bb114f419ad91310bc3e50dc2eb1cd/conans/client/generators/pkg_config.py#L90

As it was done previously for the file name here:
https://github.com/conan-io/conan/blob/5336a31744bb114f419ad91310bc3e50dc2eb1cd/conans/client/generators/pkg_config.py#L43

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/6223, will be released in 1.21.1
