### ISSUE TITLE
[bug] Concurrent conan config install with Git fails

### ISSUE THREAD

**Issue by datalogics-kam** [conan-io/conan#6233]
### Environment Details (include every applicable attribute)
  * Operating System+version: 10.14.6
  * Compiler+version: n/a
  * Conan version: 1.21.0
  * Python version: 2.7.17

### Steps to reproduce (Include if Applicable)

Execute more than one `conan config install` concurrently. This happens in our CI builders that are currently sharing a local cache, but I simulate it with this command:

```
conan config install git@octocat.dlogics.com:datalogics/conan-config.git --args '--branch artifactory-virtual-repos' & conan config install git@octocat.dlogics.com:datalogics/conan-config.git --args '--branch artifactory-virtual-repos'
```

(substitute your favorite Git source and branch as necessary)

The two executions collide over the `tmp_config_install` directory.

- Is concurrency supported for `conan config install`?
- Should there be a lock to prevent collisions in `conan config install`?
- Should the Git support for `conan config install` not use a fixed temporary directory name?

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan config install git@octocat.dlogics.com:datalogics/conan-config.git --args '--branch artifactory-virtual-repos' & conan config install git@octocat.dlogics.com:datalogics/conan-config.git --args '--branch artifactory-virtual-repos'
[1] 30719
Trying to clone repo: git@octocat.dlogics.com:datalogics/conan-config.git
Trying to clone repo: git@octocat.dlogics.com:datalogics/conan-config.git
Traceback (most recent call last):
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/lib/python2.7/site-packages/conans/client/command.py", line 1947, in run
    method(args[0][1:])
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/lib/python2.7/site-packages/conans/client/command.py", line 574, in config
    target_folder=args.target_folder)
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/lib/python2.7/site-packages/conans/client/conan_api.py", line 81, in wrapper
    return f(api, *args, **kwargs)
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/lib/python2.7/site-packages/conans/client/conan_api.py", line 596, in config_install
    source_folder=source_folder, target_folder=target_folder)
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/lib/python2.7/site-packages/conans/client/conf/config_installer.py", line 236, in configuration_install
    _process_config(config, cache, output, requester)
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/lib/python2.7/site-packages/conans/client/conf/config_installer.py", line 185, in _process_config
    _process_git_repo(config, cache, output)
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/lib/python2.7/site-packages/conans/client/conf/config_installer.py", line 50, in _process_git_repo
    with tmp_config_install_folder(cache) as tmp_folder:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/lib/python2.7/site-packages/conans/client/conf/config_installer.py", line 41, in tmp_config_install_folder
    mkdir(tmp_folder)
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/lib/python2.7/site-packages/conans/util/files.py", line 271, in mkdir
    os.makedirs(path)
  File "/Users/kam/.virtualenvs/conan-qr_code_generator-gGkB1lQl/bin/../lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/kam/.conan/tmp_config_install'

ERROR: [Errno 17] File exists: '/Users/kam/.conan/tmp_config_install'
Repo cloned!                                                                                                                                                                            
Skip README.md
Copying file .gitignore to /Users/kam/.conan/.
Copying file .gitattributes to /Users/kam/.conan/.
Copying file version.txt to /Users/kam/.conan/.
Defining remotes from remotes.txt
Installing settings.yml
Processing conan.conf
Copying file gcc-8-aix-71 to /Users/kam/.conan/profiles
Copying file apple-clang-10.0-macos-10.9 to /Users/kam/.conan/profiles
Copying file gcc-7-redhat to /Users/kam/.conan/profiles
Copying file aix-xlc16-ppc to /Users/kam/.conan/profiles
Copying file apple-clang-9.1-macos-10.7 to /Users/kam/.conan/profiles
Copying file aix-xlc13-ppc to /Users/kam/.conan/profiles
Copying file visual-studio-16 to /Users/kam/.conan/profiles
Copying file visual-studio-16-llvm to /Users/kam/.conan/profiles
Copying file apple-clang-10.0 to /Users/kam/.conan/profiles
Copying file devtoolset-7 to /Users/kam/.conan/profiles
Copying file gcc-8-intel-solaris to /Users/kam/.conan/profiles
Copying file gcc-9-aix-71 to /Users/kam/.conan/profiles
Copying file gcc-8-sparc-solaris to /Users/kam/.conan/profiles
Copying file visual-studio-15-llvm to /Users/kam/.conan/profiles
Copying file llvm-toolset-7 to /Users/kam/.conan/profiles
Copying file build_tools to /Users/kam/.conan/profiles
Copying file apple-clang-9.1 to /Users/kam/.conan/profiles
Copying file visual-studio-14 to /Users/kam/.conan/profiles
Copying file visual-studio-12 to /Users/kam/.conan/profiles
Copying file visual-studio-15 to /Users/kam/.conan/profiles

[1]  + 30719 done       conan config install git@octocat.dlogics.com:datalogics/conan-config.git
```

**Comment by memsharded** [comment]
> Is concurrency supported for conan config install

No, not supported. In the general case, the conan cache is not concurrent. There are some protections in place to try to minimize the most frequent cases, but as a rule of thumb, the conan cache is not designed for concurrent access.

> Should there be a lock to prevent collisions in conan config install?

Good question, I would say no, there is no point. It seems that the pipeline should do just 1 ``conan config install`` way before launching the parallel jobs. Isn't that possible in your pipeline?

> Should the Git support for conan config install not use a fixed temporary directory name?

Yes, this seems that would be a low hanging fruit. I would just make sure to locate it in the conan cache, not in random tmp folders (so if the cache is deleted, you are sure that is deleted too, configuration might contain sensitive data). Still, this might be hiding the real problem, so I'd probably try to fix the pipeline first if possible.  Please let me know if this would be possible.

**Comment by datalogics-kam** [comment]
> Good question, I would say no, there is no point. It seems that the pipeline should do just 1 conan config install way before launching the parallel jobs. Isn't that possible in your pipeline?

This is older code here, and it's so complicated, we're not on pipelines, and the jobs aren't connected other than that they're on a machine and sharing a user account's Conan cache. They sometimes go at the same time when they run as a nightly (we can stagger that), or via a GitHub CI trigger (we don't want to introduce delays).

We have a `conan config install` as part of the "bootstrapping" part of the the build, before it does the `conan install`. We put this into the build sequence so we don't have unexpected misconfigurations due to not getting an updated profile, or not getting a newly created profile.

I think for now, I'm going to continue with my suggestion that each Jenkins builder put the Conan cache in the workspace.

> Yes, this seems that would be a low hanging fruit. I would just make sure to locate it in the conan cache, not in random tmp folders (so if the cache is deleted, you are sure that is deleted too, configuration might contain sensitive data). Still, this might be hiding the real problem, so I'd probably try to fix the pipeline first if possible. Please let me know if this would be possible.

I'm going to recommend that our build team use separate caches for now.

A randomly named temporary folder in the Conan cache makes sense, because sometimes Git hiccups if something goes wrong and the temporary folder hasn't been removed. I agree about the location to allow deleting sensitive data.

I think for the long term, it might be worth considering a lock to serialize the config install. It may benefit other users, but it's not urgent.

Thanks for the reply; at least for our case, I think we have a solution: use separate caches via CONAN_USER_HOME.

**Comment by memsharded** [comment]
Ok, good I will label this as "low priority" and "feature" at the moment, and it actually contains 2 things:

- Implementing a random folder for git clones (very easy)
- Implementing locks over ``conan config install`` (A global lock for the whole command should be enough and i probably is not that difficult)

**Comment by memsharded** [comment]
Labeling this for Hacktoberfest: The first point only ("Implementing a random folder for git clones") might be good enough for a contribution. Both are desirable, but second not strictly necessary if unexpected complications arise.

**Comment by sourcedelica** [comment]
We just started running into this as well, though with http zip file config installs.  Clashing over `tmp_config_install`.  In this case it's multiple Bamboo plans that are completely separate from each other.

**Comment by earonesty** [comment]
i've found that if you put this command just before you run conan config in ci-scripts, it seems to reduce the likelihood of a race by a bit

`mkdir -p ~/.conan/tmp_config_install`

**Comment by memsharded** [comment]
Closing in favor of https://github.com/conan-io/conan/issues/15840 where the Conan 2 cache concurrency future progress will be reported.
