### ISSUE TITLE
[question] How do I pass options upstream/calculate dependencies from conanfile.py?

### ISSUE THREAD

**Issue by gazzatav** [conan-io/conan#6234]
Version: Conan 1.21
Background: I packaged a 3rd party library which I call here serialio with options to build static and shared libraries.  Good so far.  I ran:

`conan test test_package/  -o shared=False -o serialio:shared=False serialio/1.0.0@gazzatav/testing
`
and
`conan test test_package/  -o shared=True -o serialio:shared=True serialio/1.0.0@gazzatav/testing
`

Everything worked as expected with the tests consuming the correct package and linking to the correct library.

The conanfile.py in the test_package only has the 'shared' option so I assume the serialio:shared option is used to either calculate the package id of the dependency or is passed on to the upstream recipe to calculate its id.  I believe that here the 'shared' option is only being used to create the consuming package's id.

Question: I would like to be able to just set one option, say, 'link-static' and have the same effect as on the command line.  How do I do this in the consuming package's conanfile;py?

I have tried using the requirements method and the configure method but nothing I've tried has worked.  I'm not sure about how options are passed on to become upstream requirements.

Grateful for any help.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by gazzatav** [comment]
So after hours of trying stuff out I ask the question.  An hour later I find the answer in [mastering conan](https://docs.conan.io/en/latest/mastering/conanfile_py.html).  At least it's in the advanced section!

Easy as this:

    `default_options = {"serialio:shared": True}`

LOL

**Comment by memsharded** [comment]
Hi @gazzatav 

Great that you found the answer! Yeah, sorry didn't see your question earlier, during weekends we might be slower to respond.

Just a quick question, typically  the ``test_package`` runs automatically when you do a ``conan create``. Probably you are using ``conan test`` because you are packaging existing binaries with ``conan export-pkg``? If not, please let us know your use case. Thanks for the feedback

**Comment by gazzatav** [comment]
Hi @memsharded 

While Iearning Conan I'm using 'plumbing' commands to reinforce what's going on.  So I'm using new -t, export, install, test.  Create works fine.
Just to be clear, my comment about answering my own question after an hour was not meant as a criticism.  Conan is a great tool and I really appreciate the trouble you take to answer questions. There is plenty of documentation, the webinars you've done on YT and all the presentations at cppcon ( I love the 'Why not' lightning talks!). it just takes a while to absorb it all!

Cheers

**Comment by memsharded** [comment]
> Just to be clear, my comment about answering my own question after an hour was not meant as a criticism. Conan is a great tool and I really appreciate the trouble you take to answer questions. There is plenty of documentation, the webinars you've done on YT and all the presentations at cppcon ( I love the 'Why not' lightning talks!). it just takes a while to absorb it all!

Thanks for letting us know! :) :) :)
Appreciate your understanding, it is very difficult to keep the pace to all incoming issues, feature requests, questions, conversations... we really try our best, but even though it is becoming challenging, Conan community is already very big and keeps growing very fast. Keep the feedback coming!
