### ISSUE TITLE
CONAN_LINK_RUNTIME_MULTI is not used in the codebase

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6238]
There is a CMake definition, `CONAN_LINK_RUNTIME_MULTI` mentioned in:
 * docs: [Package approaches](https://docs.conan.io/en/latest/creating_packages/package_approaches.html?highlight=conan_link_runtime#n-configs-1-package)
 * examples: [multi-config examples](https://github.com/conan-io/examples/blob/master/features/multi_config/conanfile.py#L33)

...but it is not used in the codebase.

**Comment by memsharded** [comment]
It seems it is OK.

- It is not that conan does anything with that variable. The docs try to explain that the way to do it is you implement a variable yourself (CONAN_LINK_RUNTIME_MULTI is just a proposed name)
- Then later, you use that variable in your CMakeLists.txt to do the thing yourself, manually. This is the commented code in https://github.com/conan-io/examples/blob/master/features/multi_config/CMakeLists.txt#L7

Probably poor writing/explanation.

**Comment by jgsogo** [comment]
Probably it was me, I didn't read the `"uncomment section in CMakeLists.txt"` written in the commented out section of the `conanfile.py`. I'm not sure if we can do something to make it clear. I'm closing this, if someone asks about it again, we might do something, otherwise, I've learned the lesson.
