### ISSUE TITLE
[feature] find dependants of a package on remotes

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#6243]
I've been looking at [how to use lockfiles in CI](https://docs.conan.io/en/latest/versioning/lockfiles.html#how-to-use-lockfiles-in-ci) to build a new version of a package and rebuild all of it's dependants down to the final app.

For this to work it means that every package's CI job needs to have knowledge of the package(s) that it is being integrated into, and this info must be kept up to date with the requirements of the dependant's conanfiles. This seems like it could become a lot to keep track of and maintain.

Ideally I'd like to be able to search my remotes for all dependants of the package to then be able to trigger their rebuild.

Also related, if there was an attribute such as `ci_url` for storing the CI job's url, it would be much easier to trigger the builds and would also provide a useful link to the CI job from artifactory.

**Comment by Hopobcn** [comment]
Similar to #5942 ?

**Comment by jgsogo** [comment]
Hi, @GordonJess .

For the first part of your question, I think that we should move any conversation to the issue linked by @Hopobcn. I know the pain and I've suffered it when demoing some CI with Conan (you can [check my workaround in this _Jenkinsfile_](https://github.com/demo-ci-conan/libA/blob/master/Jenkinsfile#L22)).

About the `ci_url` I don't understand what is your intention. You can add any attribute to a Conan recipe (follow [the policy in the "Important notice"](https://docs.conan.io/en/latest/reference/conanfile.html) to be sure that we will never use the attribute you choose), nevertheless, take into account that if you modify the value of this attribute in the CI, the recipe itself will be modified and, depending on your workflow, you should commit it, export the recipe again,... but **if you are using Atifactory and the Jenkins plugin** you can track that information through the build info and I think it is the way to go:

![image](https://user-images.githubusercontent.com/1406456/71102544-fa952980-21b8-11ea-96ea-0815f8153a12.png)

I know that conan-build-info v2 is not implemented in the Artifactory-Jenkins plugin yet, but we will, for sure.

**Comment by GordonJess** [comment]
Hi @jgsogo,

Thanks I'll keep an eye on that issue!

Regarding `ci_url`, the intention was to simplify rebuilding affected dependants using their respective Jenkin's job.  After the build order is computed, the url to trigger could be retrieved with `conan inspect --raw ci_url <path_or_reference>`.  But thinking about it again this might not be a normal use case and, as you say, I could add a "protected" attribute for this.

**Comment by jgsogo** [comment]
I'm closing this issue, let's move any further about dependants to #5942. 

Thanks!
