### ISSUE TITLE
[feature] Supporting mirrors in tools.get

### ISSUE THREAD

**Issue by Morwenn** [conan-io/conan#6246]
It would be handy if `tools.get()` could support mirrors to have fallback locations to try to download a file from if the first one fails.

### Problem

My main use case for such a feature is currently linked to conan-center-index: the way to retrieve the sources today is to put link to the compressed sources in `conandata.yml`, and the `source()` method of the corresponding recipe generally consumes the data from the file as follows:

```cpp
tools.get(**self.conan_data["sources"][self.version])
```

However today I need to build `sqlite3` with a specific configuration, but www.sqlite.org is down, which means that Conan fails to retrieve the sources and my whole build is kind of blocked. If `tools.get` supported mirrors it would be possible to add a list of mirrors to the `conandata.yml` to have other locations to retrieve the sources from when the first one fails.

### Solution

While it would be possible to have `tools.get()` accept a list of URLs in `filename`, I believe that it might get users confused and think that it can retrieve a list of files from the given URLs, so it would probably more sensible to add a `mirrors` parameter accepting a list of URLs. Since YAML accept lists it means that a full list of mirrors could be forwarded directly from the `conandata.yml` file too.

If `tools.get()` gets a `mirrors=` parameter, then it makes sense to mirror the feature and add it to `tools.download()` too.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I am not sure what to think about this feature. I understand the idea, but I am not sure of the real value in practice:

- How often is www.sqlite.org down, or other equivalent source origins? From our experience packaging things in Conan-center, this is extremely unusual. Builds fail for other reasons, but not this
- How often, when a site is down, there are reliable and trusted mirrors? What are the download URLs for sqlite.org from the mirrors?

If I am building from sources sqlite packages for my company, the first thing I would most likely do is to do a copy of those sources to my own private location (a generic repo in Artifactory, typically), so I don't have a problem. This was the original intention of ``conandata.yml``, to have a place where you can easily change this source origin without even needing to edit the recipe.

So, while the feature per-se is fine, and I wouldn't oppose to this functionality, seems a bit on the edge, I am lacking some evidence about the magnitude of the pain to solve.

**Comment by Morwenn** [comment]
All good points. Concerning the official mirrors I was thinking about the number of projects that host their source control and downloads on their own servers but have official mirrors on GitHub or GitLab, I don't know whether there might be other use cases for CCI (I think that we already use such mirrors there rather than their upstream repositories, and if GitHub itself is down I've got to admit that chances are that some other dependency might not build).

**Comment by memsharded** [comment]
Yes, exactly, if Github is down, anything else will fail anyway, and the number of cases where a solid mirror is found are very limited. I think we can wait until we have more evidence of failing builds that a mirror solution would be consistently better.
