### ISSUE TITLE
[bug] Getting started example fails

### ISSUE THREAD

**Issue by a4z** [conan-io/conan#6249]
I am new to conan, want to go through the tutorial, 
follow this https://docs.conan.io/en/latest/getting_started.html
but I run into an issue and the getting_started example does not work 

### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Catalina 10.15.2
  * Compiler+version: Apple clang version 11.0.0 (clang-1100.0.33.16)
  * Conan version: 1.21.0 (via homebrew)
  * Python version: 3.7.5

### Steps to reproduce (Include if Applicable)

```
git clone https://github.com/conan-io/examples.git && cd examples/libraries/poco/md5
./build.sh
```
### Logs (Executed commands with output) (Include/Attach if Applicable)

```
+ rm -rf build
+ mkdir build
+ pushd build
~/tmp/conanplay/examples/libraries/poco/md5/build ~/tmp/conanplay/examples/libraries/poco/md5
+ conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

ERROR: Failed requirement 'OpenSSL/1.0.2o@conan/stable' from 'Poco/1.9.0@pocoproject/stable'
ERROR: Requested 'OpenSSL/1.0.2o@conan/stable' but found case incompatible 'openssl'
Case insensitive filesystem can't manage this
```

**Comment by a4z** [comment]
PS:  the problem might be on the side of poco, and I reported the problem also there
https://github.com/pocoproject/conan-poco/issues/59

but I would suggest to use a tutorial with libraries from conan-center, or bincrafters, to avoid such 3rd party dependencies that ruin the beginner user experiance

**Comment by memsharded** [comment]
Hi @a4z 

Is it possible that you did some previous installation of ``openssl/xxx`` (lowercase) package? This is in theory what could cause the problem.

We are having a look at the docs and examples repo and will update it asap to fix the issues. Thanks very much for reporting.

**Comment by memsharded** [comment]
BTW, it also seems that the scripts there build.bat, build.sh are mainly intended for CI, not for users. They might contain env-vars and other stuff that need to be defined to work properly. Better not use them, but follow the docs instead.

**Comment by a4z** [comment]
the build command does what the tutorial says (+ removing build folder if it exists, it was just shorter to write in this bug report)

yes, I have some openssl lower case in my cache (is it a cache?) 
I desperate searching my history to see how it could have landed there, but can not find it, 
but I did a lot today so possible I did something ..... :-) 
```
conan search
Existing package recipes:

Hello/0.1@demo/testing
Poco/1.9.0@pocoproject/stable
Poco/1.9.3@pocoproject/stable
Poco/1.9.4@pocoproject/stable
openssl/1.1.1d
```

is there a way to get rid of this? 


interesting is also that I do not really have poco packages (tried to install different versions bun all have the lower case problem), but conan says they exist ....

**Comment by uilianries** [comment]
> yes, I have some openssl lower case in my cache (is it a cache?)

Yes, it's a [cache](https://docs.conan.io/en/latest/mastering/custom_cache.html)

> is there a way to get rid of this?

Remove the openssl/1.1.1d package:

    conan remove -f openssl/1.1.1d

> interesting is also that I do not really have poco packages (tried to install different versions bun all have the lower case problem), but conan says they exist ....

Conan divides its [packages](https://docs.conan.io/en/latest/introduction.html#binary-management) in recipe and binary. If you [installed](https://docs.conan.io/en/latest/getting_started.html#installing-dependencies) any of them (e.g. Poco/1.9.3@pocoproject/stable), but it's not built, it will appear in your search list because you have its recipe in your cache.

**Comment by a4z** [comment]
thanks , that changed something 
cd build 
```
 conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

OpenSSL/1.0.2o@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.0.2o@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.06k]
Downloading conanfile.py completed [19.58k]
OpenSSL/1.0.2o@conan/stable: Downloaded recipe revision 0
zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.29k]
Downloading conanfile.py completed [8.74k]
Downloading conan_export.tgz completed [0.75k]
Decompressing conan_export.tgz completed [0.00k]
zlib/1.2.11@conan/stable: Downloaded recipe revision 0
conanfile.txt: Installing package
Requirements
    OpenSSL/1.0.2o@conan/stable from 'conan-center' - Downloaded
    Poco/1.9.0@pocoproject/stable from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
Packages
    OpenSSL/1.0.2o@conan/stable:00b0251895cb7b863c82dea26eecb19f1e3f627c - Missing
    Poco/1.9.0@pocoproject/stable:2da35b39f1d9de81652453b9e64bc9392ce05a25 - Missing
    zlib/1.2.11@conan/stable:f74366f76f700cc6e991285892ad7a23c30e6d47 - Download

zlib/1.2.11@conan/stable: Retrieving package f74366f76f700cc6e991285892ad7a23c30e6d47 from remote 'conan-center'
Downloading conanmanifest.txt completed [0.34k]
Downloading conaninfo.txt completed [0.44k]
Downloading conan_package.tgz completed [83.46k]
Decompressing conan_package.tgz completed [0.00k]
zlib/1.2.11@conan/stable: Package installed f74366f76f700cc6e991285892ad7a23c30e6d47
zlib/1.2.11@conan/stable: Downloaded package revision 0
OpenSSL/1.0.2o@conan/stable: WARN: Can't find a 'OpenSSL/1.0.2o@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.version=11.0, os=Macos
- Options: 386=False, no_asm=False, no_bf=False, no_cast=False, no_des=False, no_dh=False, no_dsa=False, no_hmac=False, no_md2=False, no_md5=False, no_mdc2=False, no_rc2=False, no_rc4=False, no_rc5=False, no_rsa=False, no_sha=False, no_sse2=False, no_threads=False, no_zlib=False, shared=False, zlib:fPIC=True, zlib:minizip=False, zlib:shared=False
- Dependencies: zlib/1.2.11@conan/stable
- Package ID: 00b0251895cb7b863c82dea26eecb19f1e3f627c

ERROR: Missing prebuilt package for 'OpenSSL/1.0.2o@conan/stable'
Try to build it from sources with "--build OpenSSL"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

```

so I am currently running 
` conan install .. --build missing`

this seems to work, but building does not make use all CPUs I have , so it takes time ....

**Comment by a4z** [comment]
I think, since this works now, and the existence of openssl  was somehow self created , I can close this issue.
Thanks again for the help!

**Comment by uilianries** [comment]
Hi @a4z ! We gonna provide both packages for apple clang 11! 

Regards!
