### ISSUE TITLE
[feature] Associate CMake target with specific libs

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#6250]
Hi!

Some packages requires multiple targets, because they have more than one library or configuration. For instance: https://github.com/conan-io/conan-center-index/pull/486/files#diff-e5f7472687ce110b2ecd373150bb38c0

As you can see, OpenSSL contains 2 targets, OpenSSL::Crypto and OpenSSL::SSL.

We could manage cpp_info to provide such feature:

```python
def cpp_info(self):
    self.cpp_info.names["cmake"].targets["Crypto"].libs = ["crypto"]
    self.cpp_info.names["cmake"].targets["SSL"].libs = ["ssl"]
    if self.options.shared:
        self.cpp_info.names["cmake"].targets["SSL"].defines = ["SSL_SHARED"]
```

related issue: https://github.com/conan-io/conan/issues/6069

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Is this a duplicate of the ``components`` feature? https://github.com/conan-io/conan/issues/5090

It was tried some time ago, there was a PR from @danimtb,  but was put on hold because some risks and not a huge priority.

**Comment by danimtb** [comment]
It looks very similar to the proposal in #5090 indeed. @gocarlos @uilianries are we missing something here?

**Comment by uilianries** [comment]
Indeed, #5090 sounds be the saint graal of cpp_info!
