### ISSUE TITLE
Different behavior of conan install command

### ISSUE THREAD

**Issue by jakuborava** [conan-io/conan#6253]
Is there a different behavior if `conan install` runs on conanfile.py or a reference from remote?

If I run `conan install myPkg/1.0@user/channel -r=myrepo` the `imports()` is not called.
If instead of this I first download conanfile and then run `conan install` on downloaded conanfile, `imports()` run, i.e.:
`conan get myPkg/1.0@user/channel -r=myrepo >> conanfile.py`
`conan install .`

Is this behavior different on purpose?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @jakuborava 

Yes, both commands have completely different meanings:
 * `conan install <ref>`: it will install the package (using the provided settings/options) in your local cache
 * `conan install <conanfile.py>` will grab the requirements of that `conanfile.py` from the cache (it will download them if not available, it will ask you to build from sources if binaries are not available,...) and will write into your local directory (`--install-folder`) the files generated by the generators declared in the `conanfile.py`. These files will typically be the ones that your build system is going to consume. It will also call the `imports()` function.

---

Note.- The command `conan get` might be handy to see the contents of a recipe, but never use it like `conan get <reference> >> conanfile.py && conan install .` as it won't download other files that should go together with the recipe.

**Comment by jakuborava** [comment]
Hi @jgsogo,

thank you for the detailed answer and also for the hint, I will change that.
