### ISSUE TITLE
[question] cmake_find_package generator and absolute path

### ISSUE THREAD

**Issue by arthurbiancarelli** [conan-io/conan#6258]
I noticed that cmake_find_package generator generates Findxxx.cmake with abolute paths in it. 

Is it possible to generate theses files with relative paths to a variable that could be overridden later ?

My project uses `find_package `for its dependencies. I'd like my colleagues to use those generated .cmake files. 

Sorry if this question was already asked or if I misread the doc

Many thanks,

Conan 1.21

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Hi!

The `cmake_find_package` runs in the consumer so it is safe to point to the absolute paths in your Conan cache. You are not sharing your cache with your colleagues, so if they want to build the package, they will need to install the requirement to their cache and they will run Conan to generate the `FindXXXX.cmake` files with the proper content for their machines.

I'm sure I'm missing something, so please, can I ask you why your colleagues will need the `.cmake` files that Conan has generated in your machine?

Thanks for your patience

**Comment by arthurbiancarelli** [comment]
In short It's a case where my colleagues don't have access to Conan but they can download the dependencies from a internal server.

More precisely, we have a shared dependency folder for reproducible builds. To create/update this "snapshot" I was considering using Conan to download and handle the dependencies.  My colleagues just have then to clone this snapshot. 

I understand that sharing the cache is not something wanted. I'll investigate other solutions and/or make them install Conan.

Thanks for your response, I was just making sure I wasn't missing something out in the documentation

**Comment by jgsogo** [comment]
You can write your own generator on top of ours (see [docs here](https://docs.conan.io/en/latest/howtos/custom_generators.html)), your generator can inherit our `CMakeFindPackageGenerator`, override the function-attribute `content` returned by it and modify the text substituting the absolute path to your cache with whatever you want. 

Right now, I'm not sure if you can substitute the path with a variable `DEP_DIR` and CMake will use its value when calling `find_package()` or maybe you will need to provide a full path (absolute or relative) that is suitable for your colleagues.

Try it, but

> make them install Conan

It is the best alternative, for sure 😉

**Comment by arthurbiancarelli** [comment]
Ability to create its own generator is great, thank you so much for your response.

**Comment by jgsogo** [comment]
I'm closing this issue, then, but feel free to open it again if you need help with it.

Thanks!
