### ISSUE TITLE
Appveyor: ImportError: No module named conan.packager

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#626]
Hi everyone
I'm getting this error on [appveyor](https://ci.appveyor.com/project/coding3d/conan-glew/build/job/hvnnxth27aa17il2):

```
WARN: Remotes registry file missing, creating default one in C:\Users\appveyor\.conan\registry.txt
Current 'conan.io' user: None (anonymous)
C:\Python27-x64\python build.py
Traceback (most recent call last):
  File "build.py", line 1, in <module>
    from conan.packager import ConanMultiPackager
ImportError: No module named conan.packager
```

Is it normal? Did something change? It seems to still be working on travis...

Thanks!

**Comment by dimi309** [comment]
Actually I've just noticed some problems on the mac builds of travis too:

https://travis-ci.org/dimi309/conan-glew/builds/173177129

But maybe these are one-off glitches...

**Comment by lasote** [comment]
The travis issue seem one-off glitches, relaunch them and will see.
About the appveyor issue, I can't reproduce it... I force the zlib package build and seems to be ok: https://ci.appveyor.com/project/lasote/conan-zlib/build/job/c4mfpdo23tyw5bjl

Could you relaunch it and see what happen? Sorry for not having another fix than the classic "try to reboot" XD

**Comment by dimi309** [comment]
Yes, it's probably the case about travis, since the other builds have completed. 

About the other problem I don't mind restarting it at all :) but it's still [crashing](https://ci.appveyor.com/project/coding3d/conan-glew/build/job/ab87te5spg1o2ibn)... I'll check tonight to see if I did something wrong, but I haven't changed much for this commit and it was working before... I'm just thinking, could it be that there is a problem on the 64-bit python environment? I am using the [64-bit python deployment](https://github.com/dimi309/conan-glew/blob/master/appveyor.yml) here and I've noticed you have the [32-bit version of python](https://github.com/lasote/conan-zlib/blob/master/appveyor.yml) for zlib.

**Comment by dimi309** [comment]
I switched to 32-bit python and it didn't work again. I have launched a rebuild of another package that I haven't touched for a long time and it has the same problem:

https://ci.appveyor.com/project/coding3d/conan-ogg/build/job/elvyf729bi0sgjp2

It's strange because I cannot find any significant differences between my packages and zlib...

**Comment by dimi309** [comment]
Got it! I had forgotten to switch to the 32-bit python directory in build.py. It works now:

https://ci.appveyor.com/project/coding3d/conan-glew/build/job/pq7qlek3jgw9mkkn

I am closing this issue because I can fix my packages and I don't know if you officially support the 64-bit installation of python. At least now you know, so you can fix it if you do support it :)
