### ISSUE TITLE
[question] How can I have Conan copy CMakeLists.txt into a source tree for building?

### ISSUE THREAD

**Issue by jmatzen** [conan-io/conan#6260]
I want Conan to check out and build a source tree from a git repo.  The caveat is that the git repo doesn't include a CMakeLists.txt, so I've created one and I want to keep it with the Conan recipe and not include it in the source repo.  How can I have Conan copy the CMakeLists.txt into the source tree after it's pulled it?

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jmatzen 

Yes, it is easy:
- You put your CMakeLists.txt besides your conanfile.py (not in the source repo, still a repo for the recipe + files like this one is recommended).
- You use ``exports = "CMakeLists.txt"`` (or ``exports_sources = ...``, but for a single text file you are fine with exports) in your ``conanfile.py``.
- The file will end in your source folder and later in your build folder together with the code that you retrieved from git.

Please give it a try and let us know. Thanks!

**Comment by Minimonium** [comment]
An example of such a package:
https://github.com/conan-io/conan-center-index/blob/master/recipes/bzip2/1.0.8

**Comment by jmatzen** [comment]
Thank you this seems to work great.
