### ISSUE TITLE
[feature] Package Documentation

### ISSUE THREAD

**Issue by KepptnKool** [conan-io/conan#6267]
This issue is related to [Doxygen support](https://github.com/conan-io/conan/issues/5097) but goes a bit further.

When developing with external libraries it is always useful to have access to the libraries documentation. In the C/C++ world this usually is Doxygen. When pulling a dedendency with Conan I need to look up the documentation and need to watch out to refer to the current version.
It is mostly not possible in an offline environment.
Some package maintainers already put their Doxygen documentation to the package which has some drawbacks:
* the build time is significantly increased
* it might create documentation for headers that are not packaged

Documentation has some differences to normal source code or artifacts:
* It doesn't need to be copied to the build folder
* It doesn't need to be rebuilt for other settings (no effect on package ID)

That's why I propose to add the following changes:
* add a *build_doc()* and *package_doc()* function that is only called when the package is created
  * build_doc() should be called after package()
  * package doc should be called after build_doc()
  * package_doc() might copy/download some additional info if needed and filter the doc created by build_doc
* add a *conan doc* command that displays the documentation of a package with the systems default browser
  * if download time and package size is an issue we could mitigate that by only downloading the documentation when this command is called and not for conan install.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @KepptnKool,

Thanks a lot for the feedback. This looks like a feature that maybe could be approached using hooks, did you have a [look at this feature ](https://docs.conan.io/en/latest/extending/hooks.html)or had a thought about generating the documentation using a hook? 
Maybe you can add the `build_doc()` as `post_package()` hook and open the browser from the hook, then you don't have it decoupled from Conan and you can activate or deactivate the hook depending on you are on CI or developing in your computer.

**Comment by KepptnKool** [comment]
Hi @czoido,

Thank you for your reply. I intended to visit Conan Days anyway already. I look forward to discuss such matters.
I fully understand that you have a full backlog and won't be able to add new features immediately.

See you in Madrid!

**Comment by jgsogo** [comment]
Related to https://github.com/conan-io/conan/issues/4694, something to be considered/read when thinking about the solution

**Comment by czoido** [comment]
Conan 2.0 offers [several points of extension](https://docs.conan.io/2/reference/extensions.html).
Closing this as now you can have the possibility of implementing your own conan doc command using the [custom commands feature](https://docs.conan.io/2/reference/extensions/custom_commands.html).
Please, also check the [conan-extensions](https://github.com/conan-io/conan-extensions) repo with more examples.

**Comment by KUGA2** [comment]
> ... Closing this as now you can have the possibility of implementing your own conan doc command ...

It is a pity this is closed. As long as it is not mainlined, public packages (conan center) can not use such a feature, therefore it OPs "vision" of all packages having it can not be fulfilled.
