### ISSUE TITLE
[bug] conan install asks for user password

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#6268]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 (also Ubuntu 19.10)
  * Compiler+version: n/a
  * Conan version: 1.21.0 (client), 1.16.1 (server)
  * Python version: 3.8.0

### Steps to reproduce (Include if Applicable)

Since conan 1.21.0 (or maybe 1.20), ``conan install`` sometimes asks for a password when it should download packages from our internal conan server. It never did that before in older conan versions and most of the time it still does not ask for a password.

If it asks and I cancel the process (Ctrl-C) and do the exact same call again, it usually works.

The problem looks like this (embedded in a CMake run):

	-- cotire 1.8.0 loaded.
	-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
	-- Conan: checking conan executable in path
	-- Conan: Found program C:/Python38/Scripts/conan.exe
	-- Conan: Version found Conan version 1.21.0

	-- Conan: Adding vsdk remote repositoy (https://conan.videosdk.bosch.com/)
	-- Conan: Using cmake-multi generator
	-- Conan: Automatic detection of conan settings from cmake
	-- Conan: Detected VS runtime: MD
	-- Conan: Settings= -s;arch=x86_64;-s;build_type=Release;-s;compiler=Visual Studio;-s;compiler.version=16;-s;compiler.runtime=MD
	-- Conan executing: conan install C:/devel/TRS/conanfile.py -s arch=x86_64 -s build_type=Release -s compiler=Visual Studio -s compiler.version=16 -s compiler.runtime=MD -g=cmake_multi --update
	Configuration:
	[settings]
	arch=x86_64
	arch_build=x86_64
	build_type=Release
	compiler=Visual Studio
	compiler.runtime=MD
	compiler.version=16
	os=Windows
	os_build=Windows
	[options]
	[build_requires]
	[env]

	Please enter a password for "fschoenm" account:

### Logs (Executed commands with output) (Include/Attach if Applicable)

I don't have any more logs right now. The conan server does not seem to log anything.

**Comment by fschoenm** [comment]
I found issue #5962, which might be related. I have the following Python packages, if it helps:

    Package         Version
    --------------- ----------
    bottle          0.12.18
    certifi         2019.11.28
    chardet         3.0.4
    colorama        0.4.3
    conan           1.21.0
    deprecation     2.0.7
    distro          1.1.0
    fasteners       0.15
    future          0.18.2
    idna            2.8
    Jinja2          2.10.3
    MarkupSafe      1.1.1
    monotonic       1.5
    node-semver     0.6.1
    packaging       19.2
    patch-ng        1.17.2
    pip             19.2.3
    pluginbase      0.7
    Pygments        2.5.2
    PyJWT           1.7.1
    pyparsing       2.4.5
    python-dateutil 2.8.1
    PyYAML          5.2
    requests        2.22.0
    setuptools      41.2.0
    six             1.12.0
    tqdm            4.40.2
    urllib3         1.25.7

**Comment by memsharded** [comment]
Hi @fschoenm 

The issue https://github.com/conan-io/conan/issues/5962 could be related to some issues in Bintray Conan-center exclusively. It might be gone (I'll check again in that thread).

In your case it seems it is your internal server. In your case it seems a conan_server, which is weird, because it doesn't share any common technology with Bintray.

Are you doing any kind of operation like adding and removing remotes, using ``conan user`` command, using the auth env-vars? This is difficult to reproduce, any hint might help.

**Comment by fschoenm** [comment]
@memsharded 

Unfortunately, I cannot reproduce it myself, because it only happens once in a while (but I would guess every few days since one of the last conan client updates).

Here's what I do know about my setup:
- We use a conan server running in Docker (with the official Docker image from conan-docker-tools) behind an Nginx reverse proxy.
- Conan server is version 1.16.1 since that was the latest version at the time I set it up. It ran fine since then.
- I removed all default remotes from my conan configuration and only added one remote with our own server.
- We use the CMake wrapper for conan to call ``conan install --update`` and also set the remote if it is not yet set. I guess this would perhaps set the remote every time but the configuration values don't change.
- I don't use ``conan user``. I guess I set my username once when first uploading packages but when I upload a package now and then it asks me for a password everytime (cached for a few minutes). For downloading it never asked me for a password (and in fact some users don't even have accounts on our internal conan server).
- No additional environment variables as far as I know.

**Comment by memsharded** [comment]
Maybe any kind of concurrency is used to launch CMake, that would be in turn launching ``conan install`` concurrently? Or just single process running?

Also I see Python 3.8, which we haven't added testing in CI for it yet. Have you upgraded to Python 3.8 recently, maybe close to the conan update to 1.21?

**Comment by fschoenm** [comment]
@memsharded 

On Windows, I'm not sure when I updated but Ubuntu still has Python 3.7.5, so that does not seem to be the problem.

On Ubuntu, conan might indeed be run concurrently (in CLion with multiple active toolchains) though that hasn't changed for the last 1+ year and has not been a problem before. On Windows I don't think it is run concurrently.

**Comment by fschoenm** [comment]
Any progress here? I still have this problem from time to time with the latest conan version (1.25.2).

**Comment by skoslowski** [comment]
I am getting the same unnecessary user/password requests when I run `conan install --update ...`
* clients run conan v1.27.1 on ubuntu, fedora, centos and Windows
  * all of them experience this from time to time
  * there are no concurrent conan processes
* server: my only remote is an internal conan server 1.19.1 behind nginx 

This started with an client update from v1.16.0 to v1.27.1

**Comment by fschoenm** [comment]
Is anyone still investigating this issue? This happens quite regularly now and can also break our continuous integration pipeline if it happens during the automatic build run.

**Comment by czoido** [comment]
Hi @fschoenm, @skoslowski 
I'll try to reproduce the issue, could you please detail, step by step the series of operations you are doing when you are initialising everything in the CI? especially the ones that add the remote and the next operation after that? Also which of those operations are performed in parallel if any.

**Comment by czoido** [comment]
Also another question @fschoenm, @skoslowski which CI tool are you using and how are you invoking conan commands?

**Comment by skoslowski** [comment]
We include a single-file conan executable created with pyinstaller along with its config in the build vm images. Conan is run through shell scripts driven by Jenkins CI. The only command executed is `conan install --update ../`, right before (or during) cmake. Basically the same as our developers do on their machines.

**Comment by fschoenm** [comment]
In our case, nothing runs in parallel. We add the conan remote before by calling ``conan remote add``. Then we usually use the conan.cmake integration and have in our CMakeLists.txt:

    conan_check(VERSION 1.12.0 REQUIRED)
    conan_cmake_run(CONANFILE conanfile.py BASIC_SETUP CMAKE_TARGETS KEEP_RPATHS)

But I think the problem can also occur when just calling ``conan install ..`` in the build directory.

The weird thing is just aborting the password prompt and running the exact same command again usually (always?) runs the command without asking for credentials again. That makes the issue very difficult to reproduce.

**Comment by czoido** [comment]
Hi @fschoenm,
Is the call to `conan remote add` made directly doing `sh` in Jenkins? And right after that you are invoking CMake with `cmake-conan`? If that is the case, would it be possible for you to try to use [conan_add_remote](https://github.com/conan-io/cmake-conan#conan_add_remote) in the CMakelist to see if that changes anything?

**Comment by fschoenm** [comment]
@czoido We used ``conan_add_remote`` in another project with the same problems. I don't think it is related to that.

Most of the time (outside of CI), the remote is already added long before running the build so I don't really understand why you want to focus on that aspect?

**Comment by aberegovoy** [comment]
Just guess: would calling `conan user --clean` before `conan install` fix this?

I manually uploaded a recipe with admin password, hibernated, then did `conan install` next day and was asked a password again.

**Comment by fschoenm** [comment]
This hasn't happened in a very long time now, so it's probably fixed.
