### ISSUE TITLE
Meta: Have easy to implement features labelled as "GoodFirstIssue" or "BeginnerFriendly" in the issue tracker

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#627]
I've seen the label "GoodFirstIssue" or "BeginnerFriendly" in other projects to indicate issues that are easy to implement. The intention is to show issues to new collaborators that they could implement to "get warm" with the project.

A good example would be #617, where @memsharded noted that it'll be easy to implement. If there is a potential collaborator he will not see this until he opens the issue.

Perhaps this is something that would help getting more people onboard.

**Comment by memsharded** [comment]
Very good idea, just created it and applied to: https://github.com/conan-io/conan/issues/629 and https://github.com/conan-io/conan/issues/617
