### ISSUE TITLE
[feature] Option to set the git url for a required recipe.

### ISSUE THREAD

**Issue by GavinNL** [conan-io/conan#6272]
I'm not sure if this feature is already available, I looked around the documentation but could not find anything.

Whenever I'm using Conan, I pretty much exclusively use libraries from conan-center or bincrafters. But sometimes I require a library that is not in either of these repositories. A quick google search sometimes finds a conan recipe that is usable. But the problem is if I list that library in my conanfile.txt, anyone that goes to download my source code will have to download that recipe which adds an unnecessary extra step in the build process.

It would be great if we could do something like this in the conanfile.txt 

```
[requires]
lua/5.3.5@GavinNL/testing[https://github.com/helmesjo/conan-lua]
```

Then when you run conan install, it would perform the following equivalent operations:

```
cd SOME_TEMP_FOLDER && cd SOME_TEMP_FOLDER
git clone https://github.com/helmesjo/conan-lua
cd conan-lua
conan create . GavinNL/testing
```

Now that the conan recipe is in the users repo, it's business as usual.

A feature like this would allow developers to get packages from many more locations.

The above is just a base example, for more robust features it should:
- be able to specify which branch/tag in the recipe's repo to check out
- optionally the url could be a url to an archive (zip/tar), in which case it would download/extract the recipe

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Hi @GavinNL,

Yes, this question has been asked before here #https://github.com/conan-io/conan/issues/5635

We see serious drawbacks to this feature request and we believe the way to go is using binary repositories even for recipes.

Additionally to the answers in that issue, if you see that there is no recipe available in the central repository you have the possibility to include it yourself even if it is working just for few settings. Tale a look at the Conan Center Index repo: https://github.com/conan/conan-center-index

**Comment by GavinNL** [comment]
Thanks for the info. I guess I'll make some pull requests to have the libraries I need included.

**Comment by danimtb** [comment]
Thanks for your understanding. Any PR to the index will be more than welcome 😄
