### ISSUE TITLE
[bug] Short path validation incorrectly raises error

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#6273]
Hi,

The changes introduced by #5864 don't seem to work correctly when `CONAN_USER_HOME_SHORT` is set to a path that _contains_ the value of the Conan cache path, but is not a subdirectory of it. I'd suggest the root cause of the problem is the reliance on the `os.path.commonprefix` function, which misleadingly looks for string prefixes instead of path prefixes.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows
  * Conan version: 1.21
  * Python version: 3.6

### Steps to reproduce (Include if Applicable)
Set the following environment variables (substitute drive letter as appropriate):
`CONAN_USER_HOME=Z:\` (which creates the cache at `Z:\.conan`)
`CONAN_USER_HOME_SHORT=Z:\.conans`

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
iressconanutils\conan.py:10: in __init__
    self.conan_api = ConanAPIV1()
.venv\lib\site-packages\conans\client\conan_api.py:223: in __init__
    migrator = ClientMigrator(self.cache_folder, Version(client_version), self.out)
.venv\lib\site-packages\conans\client\migrations.py:26: in __init__
    self.cache = ClientCache(cache_folder, out)
.venv\lib\site-packages\conans\client\cache\cache.py:75: in __init__
    self.config.short_paths_home
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <conans.client.conf.ConanClientConfigParser object at 0x000001B20680BC50>

    @property
    def short_paths_home(self):
        short_paths_home = get_env("CONAN_USER_HOME_SHORT")
        if short_paths_home:
            current_dir = os.path.dirname(self.filename)
            if current_dir == os.path.commonprefix([current_dir, short_paths_home]):
                raise ConanException("Short path home '{}' (defined by conan.conf variable "
                                     "'user_home_short', or environment variable "
                                     "'CONAN_USER_HOME_SHORT') cannot be a subdirectory of "
>                                    "the conan cache '{}'.".format(short_paths_home, current_dir))
E               conans.errors.ConanException: Short path home 'Z:\.conans' (defined by conan.conf variable 'user_home_short', or environment variable 'CONAN_USER_HOME_SHORT') cannot be a subdirectory of the conan cache 'Z:\.conan'.

.venv\lib\site-packages\conans\client\conf\__init__.py:424: ConanException
```

**Comment by danimtb** [comment]
I see @santhonisz. Thanks for the report. Would you like to contribute the fix? Otherwise we will take a look. Thanks! 😄

**Comment by santhonisz** [comment]
PR raised!

**Comment by memsharded** [comment]
Closed in #6303 will be released next 1.21.1. thanks!

**Comment by memsharded** [comment]
@santhonisz now appears in the commit log of branch release/1.21.1, so it will be properly acknowledged as contributor once it is merged. Thanks!

**Comment by santhonisz** [comment]
Many thanks for sorting this out guys, I've been on leave the last week so only just saw the recent comments.

**Comment by memsharded** [comment]
> Many thanks for sorting this out guys, I've been on leave the last week so only just saw the recent comments.

No worries @santhonisz, thanks for contributing it in the first place!
