### ISSUE TITLE
[question] conditional settings

### ISSUE THREAD

**Issue by drozel** [conan-io/conan#6279]
I have a project with ~15 direct dependencies which cause ~100 conan packages (10 are mine and the rest from bincrafters and conan).
Today i got new problem: i updated linux in docker container i build in and my compiler version changed from 9.1.0 to 9.2.0.
All packages in my local remote (artifactory) got out-of-date since the compiler version is not match anymore, so, conan started to build everything again. Not a big deal, I though, but some libs i have been able to build 6 months ago can't be built anymore: they download sources from developers sites and they only hold the last 3 versions, so, my version is gone.
I understand, that it's not conan's problem, but i was thinking about it and realized, that i don't want to rebuild everything every time i update the compiler or even linux version: i would like to use my build libs till they get unsupported anymore because i already realize this nightmare with third-party libs from the 42-th level deps of my dependencies..

How can i perform the conditional settings: e.g. ignore compiler version or take the newest if present without build the package with my exact compiler version? I can't define it in packages since i also have 3-rd party ones.

**Comment by Hopobcn** [comment]
If packages stop building from sources that's a bug in the package. Could you list the ones that fail?

I suppose you changed from `gcc` 9.1.0 to 9.2.0.
Remember you can override the compiler version defined in the default profile using `-s compiler=gcc -s compiler.version=9.1` or using [profiles](https://docs.conan.io/en/latest/using_packages/using_profiles.html)

**Comment by memsharded** [comment]
> If packages stop building from sources that's a bug in the package. Could you list the ones that fail?

Yes, please, also consider using the new packages from conan-center-index (the ones without user/channel), or if they are not there yet, try to request or contribute them with a Pull Request. It would be better to do the effort directly in the conan-center-index built packages than in the older ones.

@drozel regarding your question, the different approaches to manage settings that way are:

- If you are really sure about binary compatibility between minor versions of compilers, then basically you don't want to use the 9.1 or 9.2 version setting, but just the 9 (to represent all 9.X versions series). 
You can find these settings already represented in the default settings for gcc and clang, and the build helpers will also manage them properly.
- Explicitly define per-package settings, you can use ``-s mypkg:compiler.version=9.1 -s compiler.version=9.2``. This works relatively well if that is only for very few packages, not a lot of them. You can put that in profiles too, and patterns are also valid.
- Define compatibility rules in ``package_id()``. This is only possible for your own packages, but not for third-parties. I see it is a common practice to fork the recipes from conan-center to customize them for custom logic. If you can write ``package_id()``, the ``compatible_packages`` feature basically allows to define "fallback" settings that will be used if the binary for the main settings is not found. https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#compatible-packages

In your case, I think that you should probably use the first one.

**Comment by drozel** [comment]
> If packages stop building from sources that's a bug in the package. Could you list the ones that fail?
Yes, it was libsodium 1.0.16 as dependency of **zmq/4.3.1@bincrafters/stable**. It was there in summer as i built everything for GCC 9.1. Only compiler update (to 9.2) broken complete build.

> 5078 ERROR: libsodium/1.0.16@bincrafters/stable: Error in source() method, line 33
> 5079 	tools.get(source_url, sha256=sha256)
> 5080 	NotFoundException: Not found: > https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz

I agree, it is the lib's problem, but i can't rely on the hosters of 100 dependencies: once built all packages i don't want to maintain them on every minor compiler update..On the other hand you are right, compilers could be not binary compatible sometimes and it makes sense to rebuild everything..

@memsharded thanks, this is what i was looking for. Is it about packages deploy, isn't? I mean, than changing compiler version to 9 in the profiles won't accept binaries build for, e.g., 9.1, only packages built after that change for 9 will be accepted, or will it work backward?

**Comment by memsharded** [comment]
> @memsharded thanks, this is what i was looking for. Is it about packages deploy, isn't? I mean, than changing compiler version to 9 in the profiles won't accept binaries build for, e.g., 9.1, only packages built after that change for 9 will be accepted, or will it work backward?

Yes, binaries built with ``compiler.version=9.1`` will not be accepted for ``compiler.version=9``, there is no backward compat there. I guess some logic could be written in the recipes using the new ``compatible_packages`` feature, but at the moment this seems too overkill for the community maintained packages, as the version=9 policy seems to be working pretty well.

**Comment by memsharded** [comment]
Conan 2.0 has introduced a new ``compatibility.py`` plugin that allows to dynamically define compatibility rules for all packages, without haveing to modify each package ``package_id()`` method.

I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
