### ISSUE TITLE
[bug] Bumpy experience with the Qt package and the cmake multi generator.

### ISSUE THREAD

**Issue by Knitschi** [conan-io/conan#6289]
This is more a feedback then a real bug, but you do not have a feedback label.

I decided to try out conan and use it to get the Qt package for my cmake based toy project. I use Visual Studio 2019 and the project used to import the Qt-targets via the Qt-provided .cmake config files. In order to copy the dlls of the imported targets into the build-tree, my cmake code recursively searches through the dependency tree of the imported targets. 

Now here is what happened.

First I used the normal cmake generator. I hit the first problems when using the `CONAN_PKG::qt` target. The `INTERFACE_LINK_LIBRARIES` property of the target contains empty generator expressions like `$<$<CONFIG:Release>:>`. This caused the first problem with my dependency tree lookup code which could not handle generator expressions. Although I guess that in general generator expressions are required in the `INTERFACE_LINK_LIBRARIES` property, you could consider to not add them if they are empty.

As my cmake code failed when using the `CONAN_PKG::qt` target, I decided to use the qt-provided targets instead. This worked for this package as long as I only compiled in release mode because the cmake generator only provides packages in one configuration. This raised my awareness for the cmake_multi generator and I decided to use it instead. But sadly with the cmake_multi generator I could no longer use the Qt provided targets, because conan keeps different configurations in different install-trees, while the usual behavior of cmake packages is to have one install-tree with all configurations where the binaries have some configuration dependent post-fix to keep them apart.
So I was forced to switch back to linking with `CONAN_PKG::qt` which by the way forces you to link with all targets in the package which may not be desirable as others have mentioned here. This forced me to change my cmake code to handle the generator expressions in the `INTERFACE_LINK_LIBRARIES` property. A side effect is, that the code that gets the targets in the dependency tree is now significantly slower because the tree contains each target in each configuration. 
Also there is a real bug in the package because consumers can not use the `qt5_wrap_ui()` macro which is normaly provided by the packages cmake config files.

So don't get me wrong, this is not a rant on the conan package manager. I know that the Qt package is one of the more complicated packages out there and the other two package managers that I tried (hunter, vcpck) also had problems with qt. I just felt, that you should be informed that the experience of this use-case is not optimal yet.

Maybe the cmake_multi generator should not create one target for each configuration, but rather use the config dependent properties on the targets like `IMPORTED_LOCATION_<CONFIG>` to point to the correct location in your different install directories.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.21.0
  * Python version: 3.6.6

**Comment by czoido** [comment]
Hi @Knitschi,
Thanks a lot for this valuable information on your user experience. As you know we are planning which kinds of things have to be improved for Conan 2.0 and this kind of feedback is very useful.

**Comment by memsharded** [comment]
``cmake_multi`` deprecated in 1.X in favor of ``CMakeDeps``, removed in 2.0. Closing this as outdated.
