### ISSUE TITLE
conan.conf file with wrong line ending on windows

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#629]
I just noticed an small issue on Windows.

I opened the _conan/conan.conf_ file with the **notepad** application and all the content was shown in a single line. If I open the file with notepad++ or vim the content is shown in multiple lines. I guess that this is the common problem with different line endings on different platforms.

![conanwindowsissue](https://cloud.githubusercontent.com/assets/102645/20007529/f994ec26-a29c-11e6-91d3-f18c2295bb47.png)

**Comment by annulen** [comment]
Well, it may be seen as a notepad bug that does not understand one true line breaks :) For example, even WordPad handles LF properly

**Comment by memsharded** [comment]
Indeed :)
In any case, conan is already normalizing (CRLF for Win) other generated files. Applying the same for the conan.conf file generation would be very easy. 

As it is really not very necessary, I prefer to keep this open and labeled as "Easy" so some new contributor can join and implement it.

**Comment by memsharded** [comment]
Fixed, will be released in 0.17
