### ISSUE TITLE
[question] Purpose of "config_options"

### ISSUE THREAD

**Issue by DavidSpickett** [conan-io/conan#6311]
Conan Version: 1.19.2
OS: Ubuntu 16.04.6 LTS

I'm trying to remove an option from a package when on a certain OS. I read https://docs.conan.io/en/latest/mastering/conditional.html#constrain-settings-and-options and decided to try the "config_options" route.

I also referenced this docstring in the Conan source, which contains a similar example:
https://github.com/conan-io/conan/blob/9e348424d85fa22b41c93cec4b0a113f25fef24d/conans/model/conan_file.py#L211

I have a minimal recipe where I unconditionally remove the "shared" option in "config_options":
```
from conans import ConanFile

class HelloConan(ConanFile):
    name = "Hello"
    options = {"shared": [True, False]}

    def config_options(self):
        del self.options.shared

    def build(self):
        self.options.shared
```

My expectation was that deleting the "shared" option would mean that the user will get an error if they try to conan install with "--options shared=True". This is not the case.

```
$ conan install example.py Hello/0@abc/testing --options shared=True
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
shared=True
[build_requires]
[env]
<...>
example.py (Hello/0@abc/testing): Generated graphinfo
```

I would expect something like:
```
$ conan install example.py Hello/0@abc/testing --options foo=bar
<...>
ERROR: /tmp/example.py: 'options.shared' doesn't exist
Possible options are []
```

If I run the build step (which tries to read the shared option) I do get an error. So the option was removed at some point, but perhaps this is after the command line was validated.

```
$ conan build example.py 
Using lockfile: '/tmp/conan.lock'
Using cached profile from lockfile
example.py (Hello/0@abc/testing): Running build()
ERROR: 
	ConanException: 'options.shared' doesn't exist
Possible options are []
```

Am I misunderstanding what config_options is intended for and if so is what I'm seeing the intended behavior?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Hi @DavidSpickett:

The config_options() step configures the option to build the package of that recipe, not the options of the dependencies.

In the case of the `conan install` command, you are telling conan that you wanth packages from the requirement `Hello/0@abc/testing` with `shared=True`. This does not mean that you are going to build your library in shared mode.

However, when you try to really build the library of the recipe you get the right message:

```
ERROR: hello/1.0: Error in build() method, line 11
        self.options.shared
        ConanException: 'options.shared' doesn't exist
Possible options are []
```

As a clarification, the section https://docs.conan.io/en/latest/mastering/conditional.html#constrain-settings-and-options is talking about restriction for your package, not restrictions for requirements.

Hope that helps

**Comment by DavidSpickett** [comment]
So when I "conan install", "shared" is a valid option as "config_options" hasn't run.
When I "conan build", config_options is run and removes the option as expected.

Do I have that right?

In that case I think config_options isn't what I'm looking for.

I have this option "shared" that should be True/False on Macos/Win, but only ever False on Linux as its not supported. Ideally it wouldn't be an option at all, not sure if that's possible.

The default for "shared" in the real project is True. So if we just modified it in the recipe to always be False for Linux we'd silently be allowing shared=True which isn't ideal.

Our other idea was to use a default of None and apply the real default manually. Like this:
```
from conans import ConanFile

class HelloConan(ConanFile):
    name = "Hello"
    settings = ["os"]
    options = {"shared": [None, True, False]}
    # Default set later depending on OS
    default_options = {"shared": None}

    def configure(self):
        if self.settings.os == "Linux" and self.options.shared:
            raise RuntimeError("Shared lib build not supported on Linux.")

        if self.options.shared is None:
            # False for Lin, True for everything else
            self.options.shared = self.settings.os != "Linux"

    def build(self):
        print(self.options.shared)
```

This means the default is False for Linux and True for anyone else. With the slight drawback that "None" is listed as a potential value for shared. A platform specific default you could call it.

Is there a way to set defaults in a method, so we could avoid this None workaround? I don't see one, at least in a quick look at https://github.com/conan-io/conan/blob/9e348424d85fa22b41c93cec4b0a113f25fef24d/conans/model/conan_file.py#L17

Or are we taking the wrong approach entirely?

**Comment by DavidSpickett** [comment]
I'm essentially trying to do what is given as an example here:
https://docs.conan.io/en/latest/reference/conanfile/methods.html#configure-config-options

(see "For example, let’s suppose that a certain package library cannot be built as shared library in Windows, it can be done:")

**Comment by danimtb** [comment]
As said before, the options affect the package of the recipe you are creating. That way, when doing a `conan create` the option can be removed for the non-supported platforms.

In your case, I would use `options = {"shared": [True, False]}` with the default you want. Then, you can raise an invalid configuration in `configure()` method:

```
from conans import ConanFile
from conans.errors import ConanInvalidConfiguration

class Conan(ConanFile):
    ...
    options = {"shared": [True, False]}
    default_options = {"shared": [False]}

    def configure(self):
        if self.settings.os == "Linux" and self.options.shared:
            raise ConanInvalidConfiguration("Shared build type library not supported in Linux")
```

Check that here https://docs.conan.io/en/latest/reference/conanfile/methods.html#invalid-configuration

**Comment by DavidSpickett** [comment]
Ok, makes a lot more sense now. I'll try that route, thanks!

**Comment by danimtb** [comment]
Cool! Let me know if you have any other question 😄
