### ISSUE TITLE
[bug] authentication error is handled incorrectly in client.rest.uploader_downloader.FileDownloader

### ISSUE THREAD

**Issue by grisumbras** [conan-io/conan#6316]
When installing a Conan package I've got this error message:
```
tools.get(**self.conan_data["sources"][self.version])
AttributeError: 'NoneType' object has no attribute 'token'
```
Obviously, the message isn't very helpful as it implies that there's a problem with the package recipe (there wasn't).

After some investigation I found out that the error ultimately happens in `client.rest.uploader_downloader.FileDownloader` when the download fails with a 403.
The method does the following check: `auth.token is None`. The issue is, `auth` is an optional parameter. Also it is effectively allowed to be a tuple according to documentation for `tools.get`. So, I assume the check should have been `not auth or not hasattr(auth, "token") or auth.token is None`.

Conan version: 1.21.0

**Comment by jgsogo** [comment]
Fixed, it will be released soon in Conan 1.21.1
