### ISSUE TITLE
Test installing in cmd and activating environment in shell

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6328]
From https://github.com/conan-io/conan/pull/6320, running everything in a shell environment in Windows should work, and that test is checking it. 

But is expected that some users will use Conan in the Windows cmd and then activate some bash and try to activate the environment.sh generated by ``virtualenv`` Conan generators.

It would be good to test this behavior, up to what point this is working or failing.

**Comment by jgsogo** [comment]
TODO:
 * Virtualenv generators' files
 * CMake-based generators
 * Update issue https://github.com/conan-io/conan/issues/5663
