### ISSUE TITLE
[suggestion] pyproject.toml for  PEP 518 conanfile configuration

### ISSUE THREAD

**Issue by Behemyth** [conan-io/conan#6337]
pyproject.toml can be used to declare a python build system (#5577), but it can also be used as a central location for tool settings ([PEP518 Tool Table](https://www.python.org/dev/peps/pep-0518/#tool-table)). 
The features within conanfile.txt could also be applied from within a pyproject.toml. Following the conanfile.txt example, a simple table might look like this:
```
[tool.conan.requires]
Poco = "1.9.0@pocoproject/stable"
zlib = "1.2.11@conan/stable"
```

An an interface via pyproject.toml would cater to users who use python beyond conan in their project.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @Behemyth . I don't understand what is the purpose of this suggestion, probably because I'm not familiar at all with the `pyproject.toml` or the PEP518. Can you elaborate a little bit more on this? Maybe an example scenario? What will be the benefits from the users perspective?

Thanks!

**Comment by Behemyth** [comment]
Thanks for the feedback. The primary purpose of `pyproject.toml` is to replace `setup.py` and `setup.cfg` which has been discussed in #5577, but it also has additional purposes which are not dependent on the replacement of `setup.py` and `setup.cfg`. It can serve as a store for other configuration files. Instead of each tool managing its own `.ini`, `.yaml`, or `conanfile.txt` for user configuration, they would all have their own table inside `pyproject.toml`.

`pyproject.toml` would be a third way to interface with Conan from within a users project to complement the `conanfile.py/txt` recipe files. 

For using Conan alongside a python project there is an organizational benefit and clear understanding of what `pyproject.toml` provides as it becomes more pervasive. Additionally, there is the chosen standardized `toml` formatting for all tool configurations.

Example python tools which use `pyproject.toml` for configuration are: 
- [Flit](https://flit.readthedocs.io/en/latest/pyproject_toml.html)
- [Poetry](https://python-poetry.org/docs/pyproject/): Uses `pyproject.toml` to list python package dependencies as well.
- [Black](https://black.readthedocs.io/en/stable/pyproject_toml.html)
- [flake8](https://gitlab.com/pycqa/flake8/issues/428): The tool is considering the switch.

Understandable, not all Conan users want to maintain a python project foremost and `pyproject.toml` would have no place in their repository. The information present inside `pyproject.toml` would have to be extracted into an intermediate recipe for packaging.

Conan targets a great deal more than Python programmers, but for the python programmers who do use Conan `pyproject.toml` integration would be a step towards standardized configuration.

**Comment by memsharded** [comment]
We have a problem here, the adoption of conanfile.txt is already massive, so there is no way we can deprecate it anytime soon. Adding a new format will add extra maintenance, testing, documentation burden, and I think we already have too many moving pieces to introduce a new one. 

So far the syntax of conanfile.txt hasn't been an issue. There is no real big pain problem to solve here, or at least a real pain that would be solved by changing the file format. 

As much as I understand the potential of converging ecosystems, it is too far away at the moment for the community, so I would wait until Conan 2.0 is out and stabilized to reconsider again the status of the ecosystems. At this moment ce certainly cannot take this extra burden, we are already too over-capacity, and we really need to focus on more critical things and higher priorities. Thanks for the feedback!
