### ISSUE TITLE
[question] Understanding Jenkins package ID generation

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#6339]
Conan Version: 1.21.0
Artifactory Version: 6.16.0
Jenkins Version: 2.164
Jenkins Artifactory Plugin Version: 3.4.1

I'm trying to understand the package ID generation happening across Jenkins nodes. A master node is determining the build order of an app and tasking child nodes to go build required packages. 

The child node successfully builds/uploads the package to Artifactory, but the package ID does not seem to satisfy what the lock/build-order desired. When the first round of builds complete, and the master re-runs 'conan graph build-order' on the lock, it thinks the packages that just successfully built on child nodes (and were uploaded successfully to Artifactory) still need to be built. It becomes an endless loop.

In a simple command line test case using a single machine things work as I'd expect.

Details follow below. What am I missing?

Thanks

---------------------------------------

Git Repo Organization:
libA/
libB/
libC/
appX/

Timeline:

JenkinsServerMaster:
conan export libA/ libA/1.0.0@company/develop
conan export libB/ libB/1.0.0@company/develop
conan export libC/ libC/1.0.0@company/develop
conan export appX/ appX/1.0.0@company/develop
conan graph lock appX --build missing --lockfile appX.lock -pr profile-x86_64-rhel
conan graph build-order --build missing appX.lock
_[Initial build order is to build libC and libB]_

JenkinsServerChild1:
conan create libC/ libC/1.0.0@company/develop -pr profile-x86_64-rhel
conan upload libC/1.0.0 --remote ### --all --confirm

JenkinsServerChild2:
conan create libB/ libB/1.0.0@company/develop -pr profile-x86_64-rhel
conan upload libB/1.0.0 --remote ### --all --confirm

JenkinsServerMaster:
conan graph build-order --build missing appX.lock
_[Build order is **still** build libC and libB]_

**Comment by radonish** [comment]
To add, from JenkinsServerMaster I see this in the log when it's listing appX's package dependencies:
libC/1.0.0@company/develop:ae04f01b09e06f13cbc22ab140de08afc729389d - Build

On JenkinsServerChild1, however, I see the following after the `conan create` command starts running:
libC/1.0.0@company/develop:07f5bc7c7a8d77b44e2b75d65fd1d6f3be2623dc - Build

Note, the recipe revisions match between the master and child Jenkins servers. Only the package IDs are coming up different even though the same git branch/commit and profile are being used.

**Comment by memsharded** [comment]
Hi @radonish 

I am missing there the update of the lockfiles. When you are sending the lockfiles to the builder nodes, they build the node, that will be modifying the lockfile to reflect the new data of the recently created package. That modified lockfile should be sent back to the orchestrator node, that will run a ``conan graph update-lock`` command to integrate those changes into the main lockfile of the build. Is it possible that you are missing this part?

**Comment by radonish** [comment]
Hello @memsharded, that's exactly it: we are **not** doing the `conan graph update-lock` at the builder nodes. 

For some reason I was convinced we did not need to do the lock update since we are exporting all packages when the build begins. Since the latest source code is available at that time, I was assuming the package ID generated (which maybe I incorrectly assumed would include the source code since we are exporting it with the package?) would match what the builder would come up with.

I was further thrown off by the simple test case I generated that was "working".

Is there any sample pipeline code available where folks pass lock files back and forth?

Thank you!

**Comment by memsharded** [comment]
Hi!

> Since the latest source code is available at that time, I was assuming the package ID generated (which maybe I incorrectly assumed would include the source code in the hash since we are exporting it with the package?) would match what the builder would come up with

Well, it depends, for example with ``package_revision_mode`` the actual IDs are "Unkwnown", and they really need to be recomputed when the upstream dependencies get their new package IDs. There is actually an interesting thing: re-running ``conan graph build-order`` everytime a node reports back it has finished, can achieve an even better concurrency (some tracking of ongoing jobs is necessary).

Regarding the examples, we only have this https://github.com/conan-io/examples/blob/master/features/lockfiles/ci/build.py so far. We are working on more examples, but due to too much things, this has been a bit delayed. Hopefully we can resume the documentation of these pipelines better soon.

**Comment by radonish** [comment]
@memsharded, OK, thank you for all your help.
