### ISSUE TITLE
[bug] compiler.base.runtime is not set based on build_type when using Visual Studio as the base compiler

### ISSUE THREAD

**Issue by LBHawk** [conan-io/conan#6343]
Currently, `compiler.runtime` is implicitly set based on the `build_type` being used.  When using `compiler=Intel` and Visual Studio for a base compiler, we expect `compiler.base.runtime` to be set based on the build_type as well.  This is not the case, though, and it needs to be set explicitly on the command line or conditionally set directly in the recipe (which I do not think is recommended).  There are easy workarounds to this, but it makes using the Intel compiler settings not as straight forward.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Conan version: 1.21.0
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
Start from a new bare recipe
`conan new test/1.2.3 -b`

Create a package from this bare recipe with `compiler=Intel`, `compiler.base="Visual Studio"`, `build_type`, and compiler version settings
`conan create . -s compiler=intel -s compiler.version=19 -s compiler.base="Visual Studio" -s compiler.base.version=15 -s build_type=Release`

The following error is received
`ERROR: test/1.2.3: 'settings.compiler.base.runtime' value not defined`

Meanwhile running with `Visual_Studio` as the compiler implicitly sets the runtime and succeeds
`conan create . -s compiler="Visual Studio" -s compiler.version=15 -s build_type=Release`

> [settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15

**Comment by memsharded** [comment]
Yes, this might make sense. The implementation would be to complete the ``_fill_runtime()`` function of ``settings_preprocessor`` to apply also to the ``base`` compiler.

Lets give it a try.
