### ISSUE TITLE
[question] use copy_deps in package method

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#6353]
Hello,

According to the documentation, `copy_deps` is only available within the `deploy` method https://docs.conan.io/en/latest/reference/conanfile/methods.html#deploy

Is there a way/workaround to use this function in the package method? 

Use case: I want to add my dependencies changelog as part of my package.

Something like this:
```
self.copy_deps('changelog.txt', dst="docs", src="docs", folder=True, keep_path=True)
``` 

Thanks,
Walid

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @boussaffawalid 

yes, there is a way. The ``copy_deps()`` is like a proxy for the ``imports()`` functionality. If you use ``imports()`` in your recipe, and then ``keep_imports=True``, you are able to re-package what you want from your dependencies. 

You can see an example here: https://docs.conan.io/en/latest/devtools/running_packages.html#runtime-packages-and-re-packaging

**Comment by boussaffawalid** [comment]
@memsharded that did the trick. thanks

**Comment by memsharded** [comment]
good, closing this as resolved, as there is a built-in way to achieve this. Thanks for telling!
