### ISSUE TITLE
Boost shared iOS build linker --start-group problem

### ISSUE THREAD

**Issue by morfinPL** [conan-io/conan#6354]
I tried to compile boost 1.71.0 with conan-center recipe. I use the following command:

`conan create . test/test -p ios_shared -o zlib=False -o bzip2=False`

My profile ios_shared is

`[settings]
os=iOS
os_build=Macos
arch=armv8
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
os.version=12.0
[options]
shared=True
[env]
CONAN_CMAKE_GENERATOR="Xcode"`

I get the following linker error:

`-Wl,--start-group -Wl,-Bstatic  -Wl,-Bdynamic -lrt -Wl,--end-group -fPIC -pthread -fvisibility=hidden -fvisibility-inlines-hidden
ld: unknown option: --start-group`

From my point of view location of **--start-group** token is really wrong, but I don't add it manually, moreover **-Wl,-Bstatic  -Wl,-Bdynamic** seems to be also wrong.

Could you please take a look on that?

**Comment by memsharded** [comment]
Hi @morfinPL 

Which recipe?

The updated recipes in ConanCenter we recommend now are the ones without user/channel, that you can find in https://github.com/conan-io/conan-center-index

@SSE4 might help here too

**Comment by SSE4** [comment]
AFAIK we're not using `--start-group` within our boost recipe, so it looks weird.

**Comment by morfinPL** [comment]
Hi guys,
@memsharded I use old recipes, I saw these new ones, but I download boost from conan-center with this old recipe and I decide to use this one, which was in boost package.

@SSE4 exactly.

**Comment by memsharded** [comment]
But which boost? The one that is called ``Boost/1.71.0@conan/stable``, or ``boost/1.71.0``? They are different recipes, the later one the more modern one, created with conan-center-index, and the one that should be reported and modified in case it had a problem. I totally recommend trying to start with ``boost/1.71.0``.

The pattern ``--start-group`` cannot be found in the Conan codebase, I am not sure where it is coming from.

**Comment by morfinPL** [comment]
Ok I will try with boost/1.71.0

**Comment by morfinPL** [comment]
Ok, I download recipe from [https://github.com/conan-io/conan-center-index](https://github.com/conan-io/conan-center-index) and run conan create command with the same result as before. Unfortunately I still have the same problem. 

Any ideas?

**Comment by SSE4** [comment]
@morfinPL do you have a full log?

**Comment by morfinPL** [comment]
Yes, I have.
[boost_ios_shared.log](https://github.com/conan-io/conan/files/4069965/boost_ios_shared.log)

**Comment by SSE4** [comment]
I see now. you're trying to build shared libraries for iOS, which is not supported.
```
The iOS SDK supports the creation of native applications that appear on the device’s Home screen only. It does not support the creation of other types of code, such as drivers, frameworks, or dynamic libraries. If you want to integrate code from a framework or dynamic library into your application, you should link that code statically into your application’s executable file when building your project.
```

**Comment by memsharded** [comment]
> I see now. you're trying to build shared libraries for iOS, which is not supported.

Just to make sure. This is an iOS constraint, not a limitation imposed by Conan or the boost package recipe, isn't it?

**Comment by SSE4** [comment]
yes, that's an Apple (App Store) and iOS SDK restriction

**Comment by memsharded** [comment]
Ok, great, thanks.

Then I think this issue can be closed, nothing to do on our side. Please @morfinPL confirm and close the issue. Thanks!

**Comment by morfinPL** [comment]
It's partially true. It's true, that App Store rejects apps with dynamic linked libraries, but in technically it is possible to make and run such an application. My problem is that I need this dynamic linking. For example, it is possible to make dynamically linked application with OpenCV. Maybe boost building system is not able to build this configuration. :(

Off course, It's nothing to do on your side, but maybe there should be some warning, that for iOS building your recipe with shared=True is not supported? I think that this save some time for other people.

Thank you for help and your time!

**Comment by morfinPL** [comment]
Just for other persons, which will try to build dynamically linked boost for iOS. This is possible, the trick is that you must use OS name **darwin**, not **iphone**. I checked this with the following user-config.jam:

```
using clang : 10.0 : clang++ -isysroot {PATH_TO_SDK} -arch arm64 : 
<compileflags>-v
<compileflags>-fembed-bitcode\n"
<cxxflags>-std=c++17
<cxxflags>-stdlib=libc++
<linkflags>-fembed-bitcode
<linkflags>-stdlib=libc++
<linkflags>-v
;


option.set keep-going : false ;
```
I run simple app linked with this boost on iPad Pro 11, it works.
