### ISSUE TITLE
[feature] Skip unknown settings in comparisons, not raising an error.

### ISSUE THREAD

**Issue by drozel** [conan-io/conan#6359]
I just updated conan to the version 1.21.7 and tried to build my library having `openssl/1.0.2s` in dependencies. It stops with an error:

`ERROR: openssl/1.0.2s: Error in build() method, line 529
	self._make()
while calling '_make', line 474
	args = " ".join(self._configure_args)
while calling '_configure_args', line 365
	if self.settings.os == "Neutrino":
	ConanException: Invalid setting 'Neutrino' is not a valid 'settings.os' value.
Possible values are ['Android', 'Arduino', 'Emscripten', 'FreeBSD', 'Linux', 'Macos', 'SunOS', 'Windows', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
`
Conan obviously got new OS, that i don't have in my profile created by the older version of conan.
Wouldn't it be better if conan would just ignore unknown settings values? Why should the user care about having all settings it's profile, when he don't use them?
I guess there is a reason why it is implemented this way, but i can't realize it..

**Comment by memsharded** [comment]
Yes, there is a reason. If a user had in their ``settings.yml``, something like ``neutrino``, or ``qnx``, etc., it will be silently skipped as non-matching, causing errors and confusion. We have learned that it is much robust and way less error prone to have strict checking of settings and options, especially when it extends to so many settings, subsettings, like ``compiler.version``, etc.

They key here is that if you updated Conan, settings.yml should be updated by default, unless you had your own local modifications, in which case, the priority is not to destroy your modifications.

**Comment by memsharded** [comment]
Hi @drozel 

I hope the rationale of the current behavior was clear, I am going to close the issue, but let me know if you have any further question. Thanks!
