### ISSUE TITLE
Ability to install packages directly to a destination folder in install command

### ISSUE THREAD

**Issue by Prinkesh** [conan-io/conan#636]
Some functionality like 
`conan install conan_reference --package_id {package_id} --dest="." `

can be added . Users will then be able to copy the package files directly to a folder 
This will be helpful in case when package contains executables then the user could directly run the above command and skip the step of making a conanfile.py to import the files

 conan can then be used easily for deployment of executables as well

I have added the code for doing this in my local repo . let me know if this feature is inline with conan design, will send a PR for the same

**Comment by memsharded** [comment]
Just a couple of questions to fully understand this feature request:

- It will install just the ``conan_reference`` package in the destination folder, and the other packages (transitive dependencies) in the local conan cache
- It is expected that the possible generated files, as ``conanbuildinfo.cmake``, etc, will use the destination folder?
- You mention that it is useful for executables, but such command will also most likely copy also headers, static and shared libs, and other artifacts, unless the package is just for an executable.
- How this feature relates to the ``imports`` feature? The ``imports`` is specifically used to copy files from the local cache to the user space, typically for copying executables and shared libraries.
- Is the ``--package_id`` really important? Shouldn't it work automatically, with the current settings, without requiring to specify such package_id?

These are some doubts, but overall I agree that any feature to help in deployment is interesting, your idea and approach sounds good, and if you have already implemented it locally, that could help.  Just that I want to make sure of the use case and possible implications with other conan features and flows. Thanks very much for your feedback!

**Comment by memsharded** [comment]
The ``deploy`` feature will be released in 0.28, I think it implements the desired behavior.

**Comment by memsharded** [comment]
Please check: http://docs.conan.io/en/latest/reference/conanfile/methods.html#deploy
And:
http://docs.conan.io/en/latest/packaging/running_packages.html
