### ISSUE TITLE
[question/feature suggestion] Modern C++ Component: an end-to-end process

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#6361]
We have been using Conan for a bit more than a year now, and we are convinced together with CMake they form a power-couple able to take C++ out of the dark-ages of _"dependencies are a mess, stay away"_.

This may of course still require some effort to be widely acceptable, and as trivial as in some other languages. In particular, while tackling the different problems to use such tools in production, one major issue we faced was the lack of a complete and documented process allowing to provide and then consume C++ packages.

It has been around our head for some time, so we decided to write down the process we are now using with some degree of satisfaction (and major observed benefits, compared to the manual development method that was in place before):

https://adnn.github.io/ModernCppComponent

In particular, the distribution section is trying to cover the Conan related part: https://adnn.github.io/ModernCppComponent/#_distribution_conan

_NB_: It is still looking for a good name, {Sonat} is a place holder ; )

---

It raises different points as _friction points_, where we feel a better approach could ease adoption. Notably [forwarding settings to the CMake build helper without `conan_basic_setup`](https://adnn.github.io/ModernCppComponent/#_conan_basic_setup_alternative)

* Is this document of any interest to the developer and the community? If so, we are eager to get feedbacks and update the process accordingly!
* Would you like to further discuss some of the points? If so, should the discussion take place in separate issues?

**Comment by jgsogo** [comment]
> take C++ out of the dark-ages of _"dependencies are a mess, stay away"_.

❤️ ❤️ ❤️ 

I'm tagging this issue as `Feedback please!` so it is easy for anyone of our community to find it and provide feedback. I find the proposal very congruent and aligned with Conan, so I'm sure we can walk in the same direction.

About the discussion, I think that it would be best to move it to your repo, and then, when there is a proposal (not the full workflow, but for every small point), translate it to Conan as a feature request (or bug). Here in this repo there are too many issues and they can get lost into the backlog, but in your repo it can be better organized and more focused.

We would love to contribute and you can always mention us in any of your issues

**Comment by memsharded** [comment]
I am closing this ticket as outdated, with Conan 2 things have taken another big step forward, including the above friction points.
Thanks for the feeback!
