### ISSUE TITLE
[feature] better diagnostic with regards to conflicts

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6362]
While building some packages I have this result:
```
    Requirement zlib/1.2.11@conan/stable conflicts with already defined zlib/1.2.11
    To change it, override it in your base requirements
```

Okay it tells me there is a conflict with zlib somewhere.
I want to then learn the offending libraries.. since above message does not tell anything on how to learn the rootcause but rather than that it suggest 'overriding' base requirements which by the way I consider probably worst thing in my scenario ( where I am managing multiple recipes ).

Then I thought to myself maybe graph will help here!
Graph:
```
    $ conan info . -g graph
ERROR: Conflict in OpenSSL/1.0.2o@conan/stable
    Requirement zlib/1.2.11@conan/stable conflicts with already defined zlib/1.2.11
    To change it, override it in your base requirements
```

It does not event chart anything, so there is no way for me to ask conan - conan help me diagnosing this issue.  
I have to go to all dependencies one by one and find the libraries which have problems.

There should be a way to add --verbose or something that would say:
zlib@XXX is depended on by X library while zlib is depended on by Y library. 

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @fulara , which Conan version are you using?

**Comment by fulara** [comment]
@jgsogo Probably 1.21.0 but there is small chance that I had 1.20.2 in my path at the time.
If this matters which one of those I can try to reproduce the scenario.

**Comment by jgsogo** [comment]
Oh, sorry, I thought it was already merged, but the PR is still open: https://github.com/conan-io/conan/pull/5684  (I'm getting old... my memory... 👴 )

I think that this issue is also covered by that PR

**Comment by fulara** [comment]
Yep, it does.

Closing as duplicate of #5617
