### ISSUE TITLE
Use 'PAX_FORMAT' in TarFile.taropen

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6370]
Changes in Python 3.8 forced us to set explicitly the tar format in https://github.com/conan-io/conan/pull/6355, for Conan v2.0 it would be nice to change the format (**it needs to be explicit so it behaves the same for all python versions**) to the recommended one (`PAX_FORMAT`) for new Python versions (https://github.com/python/cpython/pull/12355)

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12899 for 2.0-beta.9
