### ISSUE TITLE
[bug] run_in_windows_bash fails to propagate exit code

### ISSUE THREAD

**Issue by djeverett** [conan-io/conan#6372]
### Environment Details
  * Operating System+version: Windows Server 2016 + cygwin 2.9.0
  * Compiler+version: N/A
  * Conan version: 1.21.0
  * Python version: 3.6.6

### Steps to reproduce
Create a file _build_:
```
#!/bin/bash

exit 1
```
Create a file _conanfile.py_
```
from conans import ConanFile, tools

class MyConanFile(ConanFile):
    name = 'MyProduct'
    version = '1.0'

    def build(self):
        if tools.os_info.is_windows:
            tools.run_in_windows_bash(self, './build')
        else:
            self.run('./build')
```
In Cygwin shell, execute:
```
chmod +x build
conan install .
conan build .
echo $?
```
**Expected behaviour:** the exit code is 1
**Actual behaviour:** the exit code is 0

Note: if you use the same conanfile on Linux, you do get the expected error.

**Comment by jgsogo** [comment]
Thanks for reporting the issue.

It looks like that this tool needs additional arguments like `conanfile.run` does, at least `ignore_errors=False`. Depending on that value the  `self.run` is raising or not:

https://github.com/conan-io/conan/blob/6d574958fe7f830d98e1a879f43952790225f74c/conans/model/conan_file.py#L263

**Comment by EugenMayer** [comment]
This is really needed since this makes `tools.run_in_windows_bash` useless in a CI context - i guess we cannot hotfix / workarround this issue right now?

**Comment by jgsogo** [comment]
Hi! We don't have enough bandwidth to attend all the requests that arrive at the repository 😞  ... but we always welcome PRs so if you feel like it, your contribution will be more than welcome. Anyway, I'm going to share this one with the team and ask someone running Windows to have a look at it.

**Comment by EugenMayer** [comment]
For anybody in need of this, you can workaround using

```
self.run('bash -l -c \"your command\"')

# or when you need the path
self.run("bash -l -c \"your command '%s'\"" % tools.unix_path(self.build_folder)))
```

so using `bash -l -c "command"` - you should, if you pass on a folder, using `tools.unix_path` to convert it

**Comment by memsharded** [comment]
I am closing this ticket as outdated.
I'd say that the ``win_bash = True`` is already managing this automatically in Conan 2, but please create a new ticket if this is not the case.
