### ISSUE TITLE
[question] Simultaneous development on multiple sources

### ISSUE THREAD

**Issue by mafes** [conan-io/conan#6377]
Hello,
we would like to use conan as our dependency management tool. How packages are created and used is clear.
What is not clear to me is how conan supports our developers in developing our products.

For example, how is it possible to work simultaneously on the sources of ProjectA with the library LibB on a feature branch?
Is it possible to load the project and its dependencies in a shared working directory (independent of local cache and other directories)?

working_dir_current_feat:
    - ProjectA (Source)
    - LibB (Source)
    - LibC (Header only)
    - LibD (binary)
    
working_dir_other_feat:
    - ProjectA (Source)
    - LibB (binary)
    - LibC (Header only)
    - LibD (binary)
    
Are there examples of this workflow?

Thanks for the support!

**Comment by uilianries** [comment]
Hi @mafes !

> For example, how is it possible to work simultaneously on the sources of ProjectA with the library LibB on a feature branch?

I can say you are looking for Conan [workspaces](https://docs.conan.io/en/latest/developing_packages/workspaces.html).

> Is it possible to load the project and its dependencies in a shared working directory (independent of local cache and other directories)?

If you want to put all together in the same place, because you need to find it when building, I can say you are looking for Conan [editable packages](https://docs.conan.io/en/latest/developing_packages/editable_packages.html).

**Comment by mafes** [comment]
Hi @uilianries,
thanks for your answer!
I have roughly understood the concept of workspaces. But how do I get the connection between the feature branch and the channel? Is the branch name also the Channel name?
Where does Conan get the sources in this workflow?

**Comment by Lawrencemm** [comment]
Conan doesn't grab the sources, you do that yourself, then you use the conanworkspace.yml file or the editable commands to point to the source for a particular reference eg. `my_lib/1.1@blah/stable` -> `some_path_on_your_filesystem`.

Here's an example of how this can be used: https://github.com/LM-Engine/workspace

**Comment by mafes** [comment]
Thank you @Lawrencemm ! Now it makes sense. 👍
