### ISSUE TITLE
ERROR: Codepoint U+003F at position 4 of 'com?' not allowed. [Remote: <remote name>]

### ISSUE THREAD

**Issue by psvvardhan** [conan-io/conan#6378]
Hi,

I am trying to add an artifactory repository in my VM. When I run the "conan user" command, I keep getting the error

**ERROR: Codepoint U+003F at position 4 of 'com?' not allowed. [Remote: <remote name>]**

But this works OK when I run it on windows. I assumed somehow files in .conan folder might have gotten corrupted, so tried using new ".conan" folder, but outcome didn't change. I also have latest conan installed in VM.

Any ideas how to fix this? Please let me know if you need any more information.

**Comment by memsharded** [comment]
Hi @psvvardhan 

Is there something special in your Artifactory URL? I guess you do ``conan remote add`` first, then ``conan user`` to log into that remote. With these two steps in an empty ".conan" cache folder it fails?

It might have to do with the encoding of the system, what is the guest OS that is failing in that VM? What encoding is it using? Is the VM using some kind of shared cache (maybe better avoid it) with the host system?

**Comment by psvvardhan** [comment]
Hi @memsharded 

There is nothing special in the artifactory URL. Yes, I am doing `conan remote add` first and `conan user` next.

The guest OS is Ubuntu 16.04. The strange thing is, for the same artifactory URL, both `conan remote` and `conan user` work OK on Windows. As far as I remember, there is no shared cache and encoding is Unicode UTF-8.

**Comment by memsharded** [comment]
Hi @psvvardhan 

A few more questions: Which Conan version are you using? How did you installed the Conan version in the machine?
Does it happen for example if you launch the embedded simple conan_server inside the VM, and then you try to add the remote and ``conan user`` into it?

Is there someway you could provide access to something that we can try to reproduce the issue?
Many thanks for the feedback!

**Comment by memsharded** [comment]
Closing as stale, please create new ticket if necessary
