### ISSUE TITLE
[bug] tools.collect_libs() doesn't find .lib files when package marked "editable" 

### ISSUE THREAD

**Issue by jmoutray** [conan-io/conan#6385]
When my package is marked "editable," and I `conan install` a package that requires the "editable" package, the .lib filename does not get added to cpp_info.libs if the editable package uses `tools.collect_libs(self)` in `def package_info(self)`.

I am using a layout when making the package "editable" in order to define the libdir since the .lib file is generated under `$(SolutionDir)$(Configuration)\`, which is the default location assigned by Visual Studio, and one I'd prefer not to change.  This location is not the same as where the recipe puts the .lib file, which is under the "lib" folder.

Layouts file:
```
[libdirs]
{{settings.build_type}}
```

I would expect `collect_libs` to search the libdir defined in the layout in this case.

I can easily workaround this by specifying the lib name, rather than use the utility function.

### Environment Details (include every applicable attribute)
  * Windows 10 Version 1809
  * Microsoft Visual Studio 2017 Version 15.9.17
  * Conan version 1.21.1
  * Python 3.7.0

**Comment by memsharded** [comment]
Hi @jmoutray 

The ``editables`` have been fully revamped long time ago with the new ``layout()`` method, that solved most of these issues, so closing this ticket as outdated, but please open a new one if still have issues with the new ``layout()`` method (in any case, ``collect_libs()`` is not very recommended anymore, but explicit definition of libs preferred).

**Comment by technic** [comment]
with conan 1.66 and using layout() method the self.package_folder is empty in the package_info() method and collect_libs() does not work

**Comment by memsharded** [comment]
Hi @technic 

``self.package_folder`` shouldn't be empty (you mean ``None``) in ``package_info()``. Even in Conan 1.66. It might be worth opening a new ticket if you have any further question, as this is an old closed ticket (still, even if it is a bug, it is unlikely to get fixed in Conan 1.X anymore, but responding questions maybe can help)
