### ISSUE TITLE
[question] Using conan for packaging libraries with multiple configurations

### ISSUE THREAD

**Issue by nangalvivek** [conan-io/conan#6387]
I am working on a cross-platform C++ project, exploring if we can use Conan to manage our library dependencies. Each library is pre-built and has the following folder structure.
```
MyLib/
├── Lib
│   ├── Mac
│   │   ├── Debug
│   │   │   └── x86_64
│   │   │       └── MyLib.a
│   │   └── Release
│   │       └── x86_64
│   │           └── MyLib.a
│   └── Win
│       ├── Debug
│       │   ├── Win32
│       │   │   └── MyLib.lib
│       │   └── x86_64
│       │       └── MyLib.lib
│       └── Release
│           ├── Win32
│           │   └── MyLib.lib
│           └── x86_64
│               └── MyLib.lib
└── include
    └── *.h
```
We have multiple Xcode and Visual Studio projects (not generated using CMake) that consume these libraries. 
What is the best way to package these libraries such that I can switch between the Debug/Release or Win32/X64 configurations in Xcode/Visual Studio without having to run Conan again?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @nangalvivek 

You can package those binaries as independent binaries, one package binary for each configuration. Easily done with ``conan export-pkg`` command (https://docs.conan.io/en/latest/reference/commands/creator/export-pkg.html). 

Then, for consuming them later, you can try to use the ``visual_studio_multi`` generator, check the example in https://docs.conan.io/en/latest/reference/generators/visualstudiomulti.html, is managing those 4 configurations. The XCode generator does not have a "_multi" equivalent, but I think the IDE allows to add 2 different files, for Release and Debug, so you could use the ``xcode`` generator called several times for the configs you need.

You might try to build a single package with all binaries, and adapt a bit on the consumer side, but I think I would try first with the approach above. Please have a look to those links, and let me know if you have further questions. Thanks!

**Comment by nangalvivek** [comment]
@memsharded Thanks for the detailed response. It took some time to get conan repositories supported on our corporate artifactory instance. I have successfully uploaded the packages in the different configurations to the repo and am able to successfully fetch them on `conan install ..`. 
When using xcode as a generator, is it possible to modify the name of the xcconfig file based on the build_type, eg- release.xcconfig and debug.xcconfig? Currently `-if` switch only accepts a folder name.

**Comment by memsharded** [comment]
Hi @nangalvivek 

> When using xcode as a generator, is it possible to modify the name of the xcconfig file based on the build_type, eg- release.xcconfig or debug.xcconfig? Currently -if switch only accepts a folder name.

Yes, at this moment it only accepts a folder, it is not possible a file. We have been considering ways to parameterize generators to be able to do these things, but at the moment you need to use folders, or rename them after ``conan install`` if you really need them as files.

**Comment by nangalvivek** [comment]
@memsharded I ended up using different folders for debug and release build types.  

I set up most of the xcode projects to use the xcconfig(s) generated by conan. It is working pretty well so far, though I have a few queries -
1. What is the correct way to handle libraries that don't have a `lib` prefix? I had to add the absolute path of the library to `self.cpp_info.sharedlinkflags` to make it work.
2. Paths of all the packages are added to `FRAMEWORK_SEARCH_PATHS` in the generated `xcconfig`. Is this expected?

On Windows, I am trying to use the Visual Studio multi generator as you suggested. We have some projects that have non-standard build configurations (eg - Release_yyy, Release_xxx). These are essentially the Release configuration with different preprocessor flags. Currently, conan throws an invalid-setting error if I use such a configuration for the `build_type` setting. One solution could be to have a different target for each configuration, but it would be tedious to modify all the projects.
Is there another way to handle this scenario?

Thanks a lot for your help!

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

Now this is a bit outdated, Conan 2 has new build system integrations like a new ``MSBuildDeps`` generator that allows custom configurations too.

I am closing this as outdated, but please check the latest integrations (this is necessary anyway to move to Conan 2, which is extremely recommended), and open new tickets for any further question or comment, thanks for your feedback!
