### ISSUE TITLE
New feature for detecting packages to compile/update

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#639]
Hi guys. This feature request came after a discussion I had with you on Twitter.

## Scenario

I am trying to write a script that I will run in a Continuous Integration (CI) system. The objective is to determine the missing packages in the machine running the script, compile them and later upload them to our a conan server (a local server in our private network). 

The **conan install** command accepts the argument "--build=missing" to compile the dependencies that are not present in the system. However the command **conan upload** command does not have something similar to upload all the packages that need to be updated.

## Example

Let's imagine this situation. My CI handles the build and tests execution for every platform (Windows, Linux & Mac). I just started to use conan.io to handle the dependencies of my project and I want to integrate the minimum amount of work to show off this migration. I decided to pick the **gtests** dependency for the first experiment. I do the necessary steps on my project (on a separated branch), I installed conan in all the CI nodes, and I setup the conan_server in my network. 

The first time that I run the _script_ for compiling the conan dependencies in the CI environment I would expect this:

- Detect the missing dependency with conan.
- Compile the missing dependency.
- Upload the dependency just compiled to the conan server.

The next times that this _script_ is run we should not compile anything (Either gtests is on the CI node, or we fetch it from the conan_server). 

## Possible solutions

Let's discuss here to decide what would be a nice solution to implement for solving this case.

**Comment by lasote** [comment]
The `conan upload` command checks that the uploaded files are different from the local to not upload again a package/recipe, so it doesn't take too long. Is it only a time problem or am I missing something? Sorry, I didn't read the twitter conversation.

**Comment by memsharded** [comment]
I think this will be solved with: https://github.com/conan-io/conan/issues/1895

- The creation commands will return which packages have been built
- The upload will be able to use that information to only upload built packages.
