### ISSUE TITLE
[question] tools.collect_lib(self) collecting only name of "*.dll.lib" filenames.

### ISSUE THREAD

**Issue by drotat** [conan-io/conan#6392]
Hi,
Building webrtc is producing "webrtc_unity_plugin.dll.lib" file and when I'm using `tools.collect_libs(self)` in conanfile it collects the file name only, in this case it seems that we will get "webrtc_unity_plugin" but I think it should get the name with the first extension "webrtc_unity_plugin.dll".
The problem occurs when I'm trying to link the test_package. I'm using cmake files generated by Conan.

Output from cmd : LINK : fatal error LNK1181: cannot open input file 'webrtc_unity_plugin.lib'.
I'm using Conan version 1.21.0 on windows 10.

Is this an expected behaviour?

Thanks in advance.

**Comment by Minimonium** [comment]
`webrtc_unity_plugin.dll.lib` sounds a bit unusual, they're usually named like the dll - `webrtc_unity_plugin.lib`. That could be why this use-case wasn't noticed before. :slightly_smiling_face: 

The logic for the `collect_libs` is here:
https://github.com/conan-io/conan/blob/develop/conans/client/tools/files.py#L307

To me, it looks like it should already produce a `webrtc_unity_plugin.dll`. Example:
```python
import os
os.path.splitext("webrtc_unity_plugin.dll.lib")
('webrtc_unity_plugin.dll', '.lib')
```
:thinking:

**Comment by drotat** [comment]
Yes I tested it again and it works. I missed something I guess. Sorry for your time. 😉
I will close this now.
Thanks a lot anyways.
