### ISSUE TITLE
[bug] Alias resolution bug in diamond shaped dependency tree. Order matters.

### ISSUE THREAD

**Issue by fourbft** [conan-io/conan#6393]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux and Windows
  * Conan version: Tested on 1.19, 1.20 and 1.21
  * Python version: 3

### Steps to reproduce (Include if Applicable)
               CA
      (alias) /  \ 1.0.1
            CB    CC
              \  /
               CD

In a dependency tree as shown above (CB requires CA via an alias that points to version 1.0.1, CC requires CA with a concrete version 1.0.1 and CD requires CC and CB (in that order), then trying to create CD results in the error message:
```
ERROR: Conflict in CB/0.0.2@user/testing
    Requirement CA/ALIAS@user/testing conflicts with already defined CA/1.0.1@user/testing
    To change it, override it in your base requirements
```
When reversing the order of the require statements in CD, i. e. it requires CB (with the alias to CA) first and CC second, then everything works.

I attached a tarball that contains the four conanfiles of CA through CD in subdirectories and two scripts: `build_CA_through_CD.sh` and `cleanup.sh`. To reproduce the bug, unpack the tarball and run `build_CA_through_CD.sh` which will show the above error message when it tries to create CD.

[20200120-conan_alias_non_alias_in_upstream_bug_demo.tar.gz](https://github.com/conan-io/conan/files/4086516/20200120-conan_alias_non_alias_in_upstream_bug_demo.tar.gz)

Another finding in this context which is maybe related:
There also seems to be a bug, when writing a conanfile.py which requires one component twice (in this example CA): once via the alias and once with the concrete version. 

```
from conans import ConanFile

class SpecificConanfile(ConanFile):
    name = "CE"
    description = "CE test component for evaluation of conan alias bug."
    url = "http://CE.html"
    version = "1.0.0"

    def requirements( self):
        self.requires( "CA/1.0.1@user/testing")
        self.requires( "CA/ALIAS@user/testing")
```

When doing a `conan create` on that conanfile.py, conan gives the following error message:
```
ERROR: CE/1.0.0@user/testing: Error in requirements() method, line 12
        self.requires( "CA/ALIAS@user/testing")
        ConanException: Duplicated requirement CA/1.0.1@user/testing != CA/ALIAS@user/testing
```
In this case, the order of the `self.requires`-statements 
does not matter.

The tarball also includes a CE directory with the above conanfile. So after running `build_CA_through_CD.sh` you can change into the CE directory and do a 'conan create . user/testing' there to see the "Duplicated requirement" error message.

**Comment by Minimonium** [comment]
Hi, thanks a lot for the detailed investigation! 🙂 

I've tried reproducing the case and found out the it's already been fixed in the dev branch via a similar issue: https://github.com/conan-io/conan/issues/5468

**Comment by fourbft** [comment]
Hi, thanks for looking into this issue and great, that it has already been fixed.

**Comment by memsharded** [comment]
This issue seems was fixed some time ago, so I am going to close it.

In any case https://github.com/conan-io/conan/pull/9217 introduced for 1.39 a new syntax for alias ``pkg/(alias)`` that would be more aggressive in alias resolution and could help with these alias related issues, if necessary please try it and report.
