### ISSUE TITLE
[bug] CONAN_LIBS is overwritten when running conan_basic_setup()

### ISSUE THREAD

**Issue by ostjean** [conan-io/conan#6396]
We have a very specific setup where we specify platform dependencies in the cmake toolchain file included in the platform's toolchain.

Essentially, we do `set(CONAN_LIBS ${CONAN_LIBS} ourDependency)` to pre-populates the variable with our dependency. Our CMakeLists.txt proceeds normally and calls `conan_basic_setup()` (using global variables).

This used to work properly in 1.19.2, however we noticed in 1.20+ that our dependency completely disappears from `CONAN_LIBS`.

I noticed these peculiar line in our `conanbuildinfo.cmake`:
```
...
# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND "${CONAN_FRAMEWORKS}")
# Append to aggregated values variable
set(CONAN_LIBS ${CONAN_PKG_LIBS} ${CONAN_SYSTEM_LIBS} ${CONAN_FRAMEWORKS_FOUND})


###  Definition of macros and functions ###

macro(conan_define_targets)
...
```

It looks like the `CONAN_LIBS` variable is getting completely overwritten. It works for any package defined in our `conanfile.txt`, however any values appended manually before the include of `conanbuildinfo.cmake` are lost.

According to the comment, it is supposed to append to the aggregated values, not to overwrite them.

When I look at [this PR](https://github.com/conan-io/conan/pull/6003/files#diff-4ace401e8414c1a6556986dc05a638d8R117), this seems to have been introduced in 1.20.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version:
  * Conan version: 1.21.1
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)

- Create an example project using conan and cmake (using the [global variable approach](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_generator.html#global-variables-approach))
- Add `set(CONAN_LIBS ${CONAN_LIBS} phtread)` (or any other system library) right after `cmake_minimum_required(...)`
- Add `message("CONAN_LIBS = ${CONAN_LIBS}")` after `conan_basic_setup()`.
- Run cmake configure (I don't think there should be a difference between running `cmake ..` and using the helper). You should notice that pthread (or whatever library) is not printed, meaning the variable has been completely replaced (and thus the library will be missing in `target_link_libraries`)

**Comment by memsharded** [comment]
Thanks for the detailed report @ostjean 

Yes, it seems this might be a regression, please @danimtb, confirm when possible. In that case we should be adding CONAN_LIBS in that line too.

**Comment by memsharded** [comment]
Closed by #6433, will be released in 1.21.2

**Comment by ostjean** [comment]
Everything seems to work correctly now with 1.21.2. Thanks!

**Comment by memsharded** [comment]
Thanks for trying and following up!
