### ISSUE TITLE
[question] conanbuildinfo.pri are not read by the subdirs' .pro files.

### ISSUE THREAD

**Issue by yssource** [conan-io/conan#6397]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

``` txt
[requires]
xxx/1.2.3@

[generators]
qmake

```

- base.pro file
``` qmake
TEMPLATE = subdirs
CONFIG += ordered
CONFIG += console
CONFIG -= qt

CONFIG += conan_basic_setup
include(conanbuildinfo.pri)
SUBDIRS = apple banana

```
- apple/apple.pro
``` qmake
TEMPLATE = app
CONFIG += console
CONFIG -= qt
message($$CONAN_INCLUDEPATH_XXX)
```

Result:
There is nothing with CONAN_INCLUDEPATH_XXX output.

**Comment by Minimonium** [comment]
Does the `CONAN_INCLUDEPATH_XXX` exist in the `base.pro` file? Can you message it from there?

**Comment by yssource** [comment]
Yes, CONAN_INCLUDEPATH_XXX works in base.pro, but no output in subdirs' pro files.

**Comment by Minimonium** [comment]
It seems like a limitation of variables scope of `qmake` build system.

Possible solutions:
1. Include the file in each subproject separately:
https://www.qtcentre.org/threads/36743-Shared-Global-Inherited-Variables-between-projects
2. Create a `qmake.conf` file and include the file there:
https://forum.qt.io/topic/87500/how-do-i-make-a-global-define-variable/3

**Comment by yssource** [comment]
Thank you.
`include(conanbuildinfo.pri)` in there subdirs' pro file works for me. 
There is CONAN_INCLUDEPATH_XXX output in subdirs' pro files, if `include(conanbuildinfo.pri)` manually **add it again** in the subdirs' pro files as well.

**Comment by yssource** [comment]
For this problem, I think it better to update the docs.
`include(conanbuildinfo.pri)` in the subdirs' pro file, instead of in the base.pro, if it is a subdir project.
