### ISSUE TITLE
[bug] Conan 1.21.1 doe not start on debian bullseye

### ISSUE THREAD

**Issue by nolange** [conan-io/conan#6399]
/usr/bin/libpython3.6m.so.1.0

### Environment Details (include every applicable attribute)
  * Operating System+version: Debian Bullseye x64_64
  * Compiler+version: gcc-9
  * Conan version: 1.21.1
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)

just start conan, it will fail immediately. Version 1.21.0 does not have this issue

```
[1080397] Error loading Python lib '/usr/bin/libpython3.6m.so.1.0': dlopen: /usr/bin/libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by uilianries** [comment]
Hi @nolange !

You need to install `libpython3.6` package by APT, however, the Python 3 distributed in Debian Bullseye is 3.7, not 3.6.

If you are building Python from sources, you need to pass the argument `--enable-shared` to `./configure` and ensure that libpython3.6m.so will be available in your LD_LIBRARY_PATH.

If you opted by using the distro's version (which I think is better), you only need to install `python3`:

    sudo apt-get install python3

Regards!

**Comment by nolange** [comment]
> Hi @nolange !
> 
> You need to install `libpython3.6` package by APT, however, the Python 3 distributed in Debian Bullseye is 3.7, not 3.6.

As in Buster (current stable). 

> 
> If you are building Python from sources, you need to pass the argument `--enable-shared` to `./configure` and ensure that libpython3.6m.so will be available in your LD_LIBRARY_PATH.

I use your release debs.

> 
> If you opted by using the distro's version (which I think is better), you only need to install `python3`:
> 
> ```
> sudo apt-get install python3
> ```

conan is not in debian repositories.

To be more explicit:

- I used the conan-ubuntu-64_1_21_1.deb archive from the releases page
- This one comes with its own libpython3.6m.so
- The previous conan-ubuntu-64_1_21_0.deb uses its own libpython3.6m.so **and works**
- debian does not have libpython3.6 anywhere (and if your .deb archive would need it, it should depend on it)

the issue is that you try to load from a weird absolute path (`/usr/bin/libpython3.6m.so.1.0`), something got messed up in your packaging.

**Comment by uilianries** [comment]
@nolange Now is more clear! I'll try to reproduce your error.

**Comment by uilianries** [comment]
I can confirm the bug! :bug: 

Both Conan 1.21.0 and 1.21.1 have the same number of files in the .deb package, something occurred during the .deb generation (I guess).

I've attached the logs which list the files in each .deb file:
[conan-210-2.log](https://github.com/conan-io/conan/files/4097515/conan-210-2.log)
[conan-211-2.log](https://github.com/conan-io/conan/files/4097516/conan-211-2.log)

#### Steps to reproduce:

- 1.21.0

    docker run --rm -t debian:bullseye /bin/bash -c "apt-get update; apt-get install -y wget; wget --no-check-certificate https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_21_0.deb; dpkg -i conan-ubuntu-64_1_21_0.deb; conan --version"

- 1.21.1

    docker run --rm -t debian:bullseye /bin/bash -c "apt-get update; apt-get install -y wget; wget --no-check-certificate https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_21_1.deb; dpkg -i conan-ubuntu-64_1_21_1.deb; conan --version"

We should add a test for .deb generator to avoid this same error in the future.

/cc @czoido

**Comment by memsharded** [comment]
I acknowledge that this patch release we generated the installers a bit differently.
Sorry for the trouble, we will have a look, and see if it is just generating and overwriting 1.21.1 installer .deb binary, or we need to release 1.21.2 to fix it.

**Comment by czoido** [comment]
Hi @nolange,
Thanks a lot for reporting. After exploring the issue it seems that the last version of the `pyinstaller` generated incorrect links for our binaries. It seems that is solved now.
We have updated the deb packages in **bintray** and **github**, could you please check if they work for you?

**Comment by nolange** [comment]
Yes, works now. Thanks
