### ISSUE TITLE
[question] How to switch off parallel builds globally?

### ISSUE THREAD

**Issue by Defvyb** [conan-io/conan#6401]
Conan version 1.21.1
SunOS 11.3 sun4v sparc

The problem:
"make" in our system can not process -jN flag. 

``make: Warning: Ignoring DistributedMake -j option``
``make: Fatal error: No dmake max jobs argument after -j flag``

Every build with CMake passes -jN, even if cpu_count in conan.conf = 1. (it passes -j1)
``ERROR: gtest/1.8.0@bincrafters/stable: Error in build() method, line 45 ``
       `` cmake.build()``
        ``ConanException: Error 1 while executing cmake --build ``
``'/u/builder/.conan/data/gtest/1.8.0/bincrafters/stable/build/ff8683bb44626e120b297aafa385c64572ed3839' '--' '-j1'``

We solved this with passing parallel=False in to CMake build helper constructor.

Is it possible to set parallel option to False globally? Or set it to false if cpu_count option in conan.conf =1. ?

**Comment by Defvyb** [comment]
It is also affect  AutoToolsBuildEnvironment helper

**Comment by memsharded** [comment]
Sorry this ticket was not responded back then.

Conan now has the new ``conf`` system that includes ``tools.build:jobs`` configuration that affects all build system integrations.
Closing this ticket as solved, please open new ones if necessary, many thanks!
