### ISSUE TITLE
[bug] Revision not picked up when building conan package.

### ISSUE THREAD

**Issue by timbrown5** [conan-io/conan#6406]
I am trying to get Conan to upload package with a revision (instead of `0`). I have enabled
`revision_mode = "scm"` in my Conan package, and set environment variable `CONAN_REVISIONS_ENABLED=1`. I am calling `conan export-pkg -bf ../build` from a git path, but the build_folder (`../build`) is outside of the git path.]].
The output I get is:
```
foo/1.2.3@bar/stable: A new conanfile.py version was exported
foo/1.2.3@bar/stable: Folder: /root/.conan/data/foo/1.2.3/bar/stable/export
foo/1.2.3@bar/stable: Using the exported files summary hash as the recipe revision: beff782b7a47867473c6cea2ed9eb9bc 
foo/1.2.3@bar/stable: Forced build from source
Packaging to 9bfdcfa2bb925892ecf42e2a018a3f3529826676
foo/1.2.3@bar/stable: Generating the package
foo/1.2.3@bar/stable: Package folder /root/.conan/data/foo/1.2.3/bar/stable/package/9bfdcfa2bb925892ecf42e2a018a3f3529826676
foo/1.2.3@bar/stable: Calling package()
foo/1.2.3@bar/stable package(): Packaged 144 '.h' files
foo/1.2.3@bar/stable package(): Packaged 17 files
foo/1.2.3@bar/stable package(): Packaged 1 '.cmake' file: Findfoo.cmake
foo/1.2.3@bar/stable package(): Packaged 22 '.a' files
foo/1.2.3@bar/stable package(): Packaged 2 '.inc' files: strict_cpp_re.inc, cpp_re.inc
foo/1.2.3@bar/stable package(): Packaged 13179 '.hpp' files
foo/1.2.3@bar/stable package(): Packaged 232 '.ipp' files
foo/1.2.3@bar/stable: Package '9bfdcfa2bb925892ecf42e2a018a3f3529826676' created
Package revision d77e034c7a7862af6841603c5a288147
```
My issues:
- This output shows `Package revision` is found but the package isn't uploaded with this.
- Also this revision is not the git hash of my repo, so I don't think `revision_mode = "scm"` is working.

I'm probably doing something wrong but have gone through the docs and am at a loss https://docs.conan.io/en/latest/versioning/revisions.html.

Thanks,
Tim

**Comment by timbrown5** [comment]
Update:
`Conan version 1.16.2`

**Comment by timbrown5** [comment]
I tried with Conan `1.21.1` and have the same issue.

**Comment by timbrown5** [comment]
Updating issue name.

**Comment by timbrown5** [comment]
Hi,
Is there any feedback on this?

**Comment by memsharded** [comment]
Hi @timbrown5 

Sorry for the delay, we are trying to release 1.22, and been busy.

Please note first that there are 2 revisions. The last one: ``Package revision d77e034c7a7862af6841603c5a288147`` is the binary package revision, which is always the hash of the binary contents.

The recipe revision, the one configured with ``revision_mode = "scm"`` is the first one ``recipe revision: beff782b7a47867473c6cea2ed9eb9bc ``. Is that your SCM commit?

**Comment by timbrown5** [comment]
Hi James,
I don't believe so, just checked our git repo and don't see that commit. I
think it is the hash of the conanfile.py, because it's the same between
commits to that repo.
I can check when I get in work tomorrow, what hashing algorithm is used for
hashing the conanfile (looks too long for md5?), sha1?
Thanks,
Tim

**Comment by memsharded** [comment]
Indeed this is weird. 
I am running this test in the test suite:
```python
    def test_revision_mode_scm(self):
        path, rev = create_local_git_repo(
            files={'conanfile.py': self.conanfile.format(revision_mode="scm")})
        print("REV ", rev)
        t = TestClient(current_folder=path)

        ref = ConanFileReference.loads("name/version@user/channel")
        t.run("export . {}".format(ref))
        meta = t.cache.package_layout(ref, short_paths=False).load_metadata()
        self.assertEqual(meta.recipe.revision, rev)
```

It shows a 40 characters revision, which is the git commit, and it works. In your case, it is clearly saying:
>  Using the exported files summary hash as the recipe revision: beff782b7a47867473c6cea2ed9eb9bc

Will check now if the ``export-pkg`` instead of the ``export`` could be related

**Comment by memsharded** [comment]
The test:

```python
    def test_revision_mode_scm(self):
        conanfile = textwrap.dedent("""
            from conans import ConanFile

            class Lib(ConanFile):
                revision_mode = "scm"
        """)
        path, rev = create_local_git_repo(files={'conanfile.py': conanfile})
        t = TestClient(current_folder=path)

        ref = ConanFileReference.loads("name/version@user/channel")
        folder = temp_folder()
        t.run('export-pkg . {} -bf="{}"'.format(ref, folder))

        meta = t.cache.package_layout(ref, short_paths=False).load_metadata()
        self.assertEqual(meta.recipe.revision, rev)
```
Seems to work too.

Not sure what could I try next. Is there something special in your recipe regarding the ``revision_mode``?

**Comment by timbrown5** [comment]
Hi James,
Looking at the most recent build it seems like the recipe revision is the git hash (still not sure what `beff782b7a47867473c6cea2ed9eb9bc` is the revision of).

That said we don't see the recipe revision listed in Artifactory (I believe it should be in the name of the folder under `stable`, which is `0`):
![Screenshot 2020-02-06 at 08 30 36](https://user-images.githubusercontent.com/4447764/73919252-15cc0d80-48bb-11ea-8505-f005cfa1a542.png)
Also when I list the revisions from the Artifactory repo I get this:
```
conan search boost/1.70.0@foo/stable -r foo-conan --revisions
Revisions for 'boost/1.70.0@foo/stable' at remote 'foo-conan':
0 (2020-01-27 16:58:14 UTC)
```
Our Artifactory version is 6.16.0.

**Comment by memsharded** [comment]
Hi @timbrown5 

Yes, it seems that the upload is not using revisions. The package can be created locally with revisions, but if the server or the protocol doesn't support it, it will upload it without (using "0") revisions.

Do you have the output of the upload? Enabling the CONAN_TRACE_FILE to log the api calls to the server will really help too.

**Comment by timbrown5** [comment]
Hi James,
Looks like I was correct above:
>I'm probably doing something wrong but have gone through the docs and am at a loss >https://docs.conan.io/en/latest/versioning/revisions.html.
I was setting `` for the package, but not for the upload 😳. With this set Conan is uploading with the expected RREV.
Sorry for the noise.
Tim

**Comment by memsharded** [comment]
Hi @timbrown5 

No problem, happy to help and see that there is no issue here :) 
Thanks for following up and keep reporting!
