### ISSUE TITLE
[question] Hardlocked options and diamonds

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#6408]
Related to https://github.com/conan-io/conan/issues/3524, https://github.com/conan-io/conan/issues/5530

It's explicitly allowed to hardcode dependencies' options [in the documentation](https://docs.conan.io/en/latest/mastering/conditional.html?highlight=default_options#conditional-settings-options-and-requirements).

Alternatively, it's encouraged to use `default_options`. But it becomes a problem comically fast as this test shows:
https://github.com/conan-io/conan/blob/develop/conans/test/unittests/model/transitive_reqs_test.py#L1063

@Morwenn has provided us in the Slack with a great minimal example of a conflict of hardlocked options in subgraphs:
```python
from conans import ConanFile

class LibFirstConan(ConanFile):
    name = "zero"
    version = "1.0.0"
    description = "Zero library"
```
```python
from conans import ConanFile

class LibFirstConan(ConanFile):
    name = "first"
    version = "1.0.0"
    description = "First library"

    options = {"with_zero": [True, False]}
    default_options = {"with_zero": True}

    def requirements(self):
        if self.options.with_zero:
            self.requires("zero/1.0.0@")
```
```python
from conans import ConanFile

class LibSecondConan(ConanFile):
    name = "second"
    version = "1.0.0"
    description = "Second library"

    options = {"with_first": [True, False]}
    default_options = {"with_first": False}

    def configure(self):
        if self.options.with_first:
            self.options["first"].with_zero = False

    def requirements(self):
        if self.options.with_first:
            self.requires("first/1.0.0@")
```
```python
from conans import ConanFile

class LibThirdConan(ConanFile):
    name = "third"
    version = "1.0.0"
    description = "Third library"

    def configure(self):
        self.options["second"].with_first = True

    def requirements(self):
        self.requires("first/1.0.0@")
        self.requires("second/1.0.0@")
```
```bash
conan export zero
conan export first
conan export second
conan create third
```
Depending on the order of requirements in the `third/1.0.0@` we get the diamond error, although in the whole graph we do have only one set of hardlocked options, which in this case was unexpected for the user.

It highlights issues with the runtime graph construction and in-recipe external configuration modifications _and_ preferences (not only settings but external options too). It's practically impossible to dynamically alter other subgraphs from a parallel subgraph and in a sequential solution, we'd have an unreliable build. 

The question is - what should we do with recommendations for that in the documentation?

**Comment by memsharded** [comment]
Sorry this was not responded back then @Minimonium 

I am closing this as outdated, Conan 2 already changed how options are managed, including new ``important!`` options definitions, not conflicting by default, etc.

Please open new tickets if necessary, thanks for the feedback!
