### ISSUE TITLE
[feature] Add a way to not apply a build requirement to other build requirements

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#6411]
Hello,

After making some changes to a cross-build toolchain of mine, I wanted to try compiling the whole dependency graph locally, before pushing the changes upstream.

Therefore I went to the top-level directory and ran `conan install -pr myprofile --build`.
The problem is that the cross-build toolchain exposes environment flags such as `CXXFLAGS`.

It does work as expected for `requirements`, but it fails with other `build requirements`!

For instance, `boost/1.71` from CCI build requires `b2/4.0`, and passing `--build` triggers a build of `b2`, which is being built with the `CXXFLAGS` exposed in the cross-build toolchain...

After browsing the docs about build requirements declared in profiles, it seems there is no way to express the following:

> Apply this package to all consumers *BUT* other build requirements

And I think it should be added 😄 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Minimonium** [comment]
Wouldn't it be better related to the https://github.com/conan-io/conan/projects/4 ?

**Comment by theodelrieu** [comment]
I guess, but it's a long road from now

**Comment by jgsogo** [comment]
PRs related to xbuild are getting traction again 😉 

https://github.com/conan-io/conan/pull/5592

**Comment by AbrilRBS** [comment]
Marking as solved in Conan 2, where [you can define a `tool_requires` only for the host profile](https://docs.conan.io/2/reference/config_files/profiles.html#tool-requires), which won't be propagated to the build one :)
