### ISSUE TITLE
[bug] VirtualEnv generator broken for (Git) Bash under Windows

### ISSUE THREAD

**Issue by AshleighAdams** [conan-io/conan#6412]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: n/a
  * Conan version: 1.21
  * Python version: Bundled with installer

### Steps to reproduce (Include if Applicable)

Create a test binary that is packaged into "bin",

```python
# ...
	def package(self):
		self.copy(pattern="test", src="bin", dst="bin")

	def package_info(self):
		self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))
```

Create the conan package, then install it under Git Bash with `-g virtualenv`. When you activate the enviroment, the executable `test` won't be found, as the backslashes aren't escaped. That said, the path separator is also present due the drive letter. I'm not sure if this can be fixed.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ashleigh.adams@LAP00016 MINGW64 ~/tmp
$ conan install -r inseinc -g virtualenv test/test@dev/null && . activate.sh
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MT
compiler.toolset=v100
compiler.version=10
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Installing package: test/test@dev/null
Requirements
    test/test@dev/null from local cache - Cache
Packages
    test/test@dev/null:11e6a84a7894f41df553e7c92534c3bf26896802 - Cache

Cross-build from 'Windows:x86_64' to 'Windows:x86'
test/test@dev/null: Already installed!
Generator txt created conanbuildinfo.txt
Generator virtualenv created activate.bat
Generator virtualenv created deactivate.bat
Generator virtualenv created environment.bat.env
Generator virtualenv created activate.ps1
Generator virtualenv created deactivate.ps1
Generator virtualenv created environment.ps1.env
Generator virtualenv created activate.sh
Generator virtualenv created deactivate.sh
Generator virtualenv created environment.sh.env
(conanenv)
ashleigh.adams@LAP00016 MINGW64 ~/tmp
(conanenv)
ashleigh.adams@LAP00016 MINGW64 ~/tmp
$ echo $PATH
C:.conan36b3b21binwin32: ....
```

**Comment by memsharded** [comment]
Hi @AshleighAdams 

I think this bug was fixed in minor 1.21.1 (https://docs.conan.io/en/latest/changelog.html).

Please try to update and let me know if you can confirm this is fixed. Thanks!

**Comment by AshleighAdams** [comment]
I tested it against 1.21.1, and though the backslashes are fixed, sadly the path it produces isn't.

The path gets turned into "C:\SomeDir\.conan\...\bin:/usr/bin:/c/WINDOWS", which Bash interprets as `C`, `\SomeDir\.conan\...\bin`, `/usr/bin`, and `/c/WINDOWS`.

I'm not sure if the virtualenv should translate Windows style paths in `$PATH` to the Unix equivalent (such as `C:\A` to `/c/A`), but it *could* detect if it's running in Cygwin/Msys2 by the presence of `cygpath`, then passing each path thru `cygpath` before writing the results to `environment.sh.env`. The question then becomes, is `$PATH` a special case? Should it be done for all colon delimited lists in the paths?

**Comment by AshleighAdams** [comment]
@memsharded I took a shot at fixing it, instead of using `cygpath`, I attempt to detect a Windows letter path (thankfully they're very limited), then use the already existing `unix_path()`.

I tested it in WSL and Git Bash, with them both producing different correctly normalized paths (`/mnt/c/...` and `/c/...`).

**Comment by jgsogo** [comment]
Hi! I'm having a look at this issue and the PR related to it. This same scenario is what we are currently running in the `VirtualenvWindowsBashTestCase` and it is working in our CI (I'm just trying to spot the difference to understand what is happening in your use case):
 * We create a package with an `executable.exe` in the `bin` folder
 * The path to `package_folder/bin` is added to the `env_info.PATH`
 * We look for (and run) the `executable.exe` after activating the environment

(Check the test [here](https://github.com/conan-io/conan/blob/44a09bc15a33449c1ab5435bc9630f816cec8a90/conans/test/functional/generators/virtualenv_windows_bash_test.py#L82))

Indeed, I'm checking the `PATH` variable after activating the environment and I see that the path introduced by the Conan environment starts with `C:` (as expected, we are not substituting it):

```
C:\Users\jgsog\AppData\Local\Temp\tmp_id3kme3conans\pathwithoutspaces\.conan\data\name\version\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin:/c/Users/jgsog/dev/py3/Scripts:/c/Users/jgsog/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/jgsog/bin:/c/Users/jgsog/dev/py3/Scripts:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/cmd:/c/Program Files/CMake/bin:/c/Users/jgsog/AppData/Local/Programs/Python/Python38/Scripts:/c/Users/jgsog/AppData/Local/Programs/Python/Python38:/c/Users/jgsog/AppData/Local/Microsoft/WindowsApps:/c/Users/jgsog/AppData/Local/Programs/Microsoft VS Code/bin:/usr/bin/vendor_perl:/usr/bin/core_perl
```

but, in this/my/CI case, it doesn't interpret it as a separator but as the actual Windows unit. 🤷‍♂  

Digging into this issue I've found this page in the MinGW docs, http://mingw.org/wiki/Posix_path_conversion, it says:

> Arguments starting with a drive specifier (eg C:) are considered to be Windows paths and are not converted.

@AshleighAdams , did you see any other difference between the testcase we already have in our test suite and your use case?

Thanks!

**Comment by AshleighAdams** [comment]
Hey @jgsogo,

I took a look again with 1.21.1, and I'm no longer able to replicate it. I remember upgrading Conan to 1.21.1 and the backslashes correctly being output, but still not finding the executable. I'm thinking I must have typo'd the executable name.

I'll close the issue & PR. If I do manage to encounter it again, I'll try and figure out what changed and reopen this issue.

Thanks.

**Comment by jgsogo** [comment]
Thanks! Thanks for checking it again. I agree that there are too many edge cases related to different shells and mixing windows+shell can lead to problems we haven't think about. So, thanks a lot for reporting, it also helps us to understand better these systems.
