### ISSUE TITLE
[feature] use short_paths during build, normal paths during packaging

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#6414]
Some packages need `short_paths` enabled during build, but once built can be stored normally in a package folder in `CONAN_HOME`.
For example https://github.com/conan-io/conan-center-index/pull/725,
this package needs `short_paths` enabled during `build()` but can have a *normal* path during `package()`.

Essentially, it would be nice if `self.build_folder` can be a short path but `self.package_folder` a normal path.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The ``short_paths`` feature is a bit of a mess, complicated and fragile. I am proposing in https://github.com/conan-io/conan/pull/6415/files some possibility to try to improve it.

This feature request makes sense, but I am a bit afraid of adding more complexity and fragility into the code, for something that doesn't seem critical, but a nice to have. I would delay this to see if https://github.com/conan-io/conan/pull/6415/files moves forward, and come back later to analyze if makes sense or not. A possibility could be allowing defining ``short_paths = "build"``, and ``short_paths = "build", "package"`` or something like that.

**Comment by uilianries** [comment]
> A possibility could be allowing defining short_paths = "build", and short_paths = "build", "package"

It sounds good, any user will be able to decide what they want.

**Comment by madebr** [comment]
A possibility could be allowing defining short_paths = "build", and short_paths = "build", "package" or something like that.

This would be nice.
Also, I think adding `source` as an option would be interesting. This might benefit `no_copy_source = True` builds.

**Comment by memsharded** [comment]
``short_paths`` removed in Conan 2.0, closing this ticket as outdated.
