### ISSUE TITLE
[question] How to omit this log?

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#6418]
Hi,

In my travis build a lot of log is generated by conan, resulting in travis fail. Example:
https://travis-ci.com/ezored/ezored/jobs/279971073?utm_medium=notification&utm_source=email

How to let show only warn/error/fatal logs?

I tried this lines without success:
```
- export CONAN_LOGGING_LEVEL=40
- export VERBOSE=0
```

I want remove compilation line log. Example:
```
/Applications/Xcode-11.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -I. -Icrypto/include -Iinclude -fPIC -isysroot /Applications/Xcode-11.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -fno-common -isysroot/Applications/Xcode-11.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -mios-version-min=9.0 -fembed-bitcode -arch armv7s -O3 --sysroot=/Applications/Xcode-11.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -isysroot/Applications/Xcode-11.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -mios-version-min=9.0 -fembed-bitcode -arch armv7s -fPIC -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/travis/.conan/data/openssl/1.1.1c/_/_/package/d2e063db0086092333d8cc1eccadd12dfb9f37d3/res\"" -DENGINESDIR="\"/Users/travis/.conan/data/openssl/1.1.1c/_/_/package/d2e063db0086092333d8cc1eccadd12dfb9f37d3/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DNDEBUG -I/Users/travis/.conan/data/zlib/1.2.11/_/_/package/f84f4772109ffc4865b67cb9548c5f9f7586d9c9/include -isysroot/Applications/Xcode-11.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -mios-version-min=9.0 -fembed-bitcode -arch armv7s -MMD -MF crypto/evp/e_seed.d.tmp -MT crypto/evp/e_seed.o -c -o crypto/evp/e_seed.o crypto/evp/e_seed.c
```
      

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @prsolucoes 

Those affect to the output of Conan itself (things printed by Conan code), but that long output is the build output. Conan doesn't have general control to what different build systems decides to output, so any custom output control should be defined in the recipes.

I see that you are using the ``CMake()`` build helper in https://github.com/ezored/ezored/pull/21/files#diff-413b3cd2e446bfd4660afcbf39011b84.
Maybe you can instruct CMake to be less verbose, using the ``args`` argument of ``cmake.build()``, that will pass arguments to the underlying cmake invocation?
