### ISSUE TITLE
[question] Conan + Artifactory + Azure DevOps

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan#6419]
We are moving our CI/CD to Azure DevOps. To store our artifacts we are planning  to use Artifactory Cloud.  I've read the [Conan documentation](https://docs.conan.io/en/latest/integrations/ci/azure_devops.html)  and it seems possible. 
> To use the Conan support provided by the JFrog Artifactory Extension you must configure a **self-hosted agent** that will enable Conan builds for your Azure Pipelines  environment.

But we want to use only **Microsoft-hosted agents**.

1. Maybe is it possible to use Microsoft-hosted agents after all?
2. If not, can I upload Conan packages to Nexus or Azure artifacts generic repo?
3. If not, maybe you have other suggestions?

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @dmn-star 

Are you looking for the Artifactory Pro on Azure? https://azuremarketplace.microsoft.com/en-us/marketplace/apps/jfrog.artifactoryprox?tab=Overview. As all other Artifactory Pro versions, it also includes support for Conan.

**Comment by dmn-star** [comment]
@memsharded  Yes, we want to use the Artifactory Pro on Azure tougher with  JFrog Artifactory Extension for Azure DevOps and TFS https://jfrog.com/integration/azure-devops-and-tfs-artifactory . My problem is the need for **self-hosted** build agents in this case.

**Comment by cyan21** [comment]
@dmn-star It is possible to use Conan on Microsoft-hosted agents but you'll have to add a task to install the conan client before using conan tasks. If you're installing Conan via pip, make sure to set the python version to 3.* via this [task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops)

**Comment by memsharded** [comment]
Closing this ticket as old and inactive
