### ISSUE TITLE
Appveyor: '_conan_env.bat' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#642]
Hello,

I'll explain this with references, I think it will be more clear :)

I got this error:

```
'_conan_env.bat' is not recognized as an internal or external command,
operable program or batch file.
```
on [this build](https://ci.appveyor.com/project/coding3d/conan-ogg/build/1.0.90/job/b96rbx8qyv1equbq) on Appveyor.

As it happens many times with conan, it is not a serious problem. I just needed to remove my environment setting command because, anyway, for this package, I can sort of understand there might no be much for it to do (it's a package with no dependencies). These are the commits that fixed it:

- https://github.com/dimi309/conan-ogg/commit/6fb7189a3aa86270d916b31681b167a1d8e21dab
- https://github.com/dimi309/conan-ogg/commit/5c3e4ffa8d19bbbd06a450d3199c90b236907849

Nonetheless, it seems that an environment command line was generated by conan, calling a _conan_env.bat file that should exist somewhere but does not (maybe it does not get generated if there is nothing to put into it or something... I'm just guessing here). So I am mentioning in case this helps improve conan :smile:

**Comment by memsharded** [comment]
Could you try running the ``env_line`` the first in your command? It is run second here:
```python
self.run("%s && %s && devenv %s /upgrade" % (cd_build, env_line, vs_project))
```
As you are moving in the first command from the folder, that could be the reason it is not finding the file.

**Comment by dimi309** [comment]
My mistake :) I thought _conan_env.bat just wasn't there. Indeed, after changing the sequence of the calls, [it's working](https://ci.appveyor.com/project/coding3d/conan-ogg/build/job/ug5vih0wo48movsp).

**Comment by memsharded** [comment]
Great, glad it worked, thanks for telling!
