### ISSUE TITLE
[feature] manifestation/freeze of all dependencies for deterministic builds

### ISSUE THREAD

**Issue by Viatorus** [conan-io/conan#6420]
To have deterministic builds I would like to have an option to get all used dependencies with there explicit version. With this information (maybe as output file), I could force my next build process to exactly use these dependencies and versions again and ignoring any semantic version ranges.

It should be similar like npm's [package-lock](https://docs.npmjs.com/files/package-lock.json.html). 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Minimonium** [comment]
Hi, check out the https://docs.conan.io/en/latest/versioning/lockfiles.html

**Comment by Viatorus** [comment]
Thank you!
