### ISSUE TITLE
[feature] conanfile.py to load generic `.yml` file - instead of only support of conandata.yml

### ISSUE THREAD

**Issue by MaciejPatro** [conan-io/conan#6421]
Having a big project with different tools around it creates a need for a place that could be "single source of truth" for configuration related data to the project/product. `conandata.yml` seems to be a perfect way to provide such information to conan. Unfortunately the name of the file quite tightly couples it with conan itself (It feels bad to provide `conandata.yml` to any other tool that doesn't even know about conan existence). 

It would be great to be able to provide just generic `*.yml` file to the recipe `conanfile.py`. 

One way would be to provide it as commandline parameter?

**Comment by memsharded** [comment]
Hi @MaciejPatro 

The problem with this is that this file is loaded for every package in the dependency graph. If you provide a command line parameter, the filename should be the same for all the conanfiles in the graph, which will not be true. Note that this file name should be exactly the same and respected in all Conan commands (export, create, install, export-pkg, etc. this means adding an extra argument to all conan commands) for all packages in the graph. It is almost impossible that this works consistently (you create/export a package with a given name, then you are forced to use that name for all packages and all commands later on, if you forget to provide it or change it, it will break). So basically, seems not to be a good UX.

Furthermore, this file is also being used by the SCM component to store url and commit of the scm. This can be done if the file is a conan-managed/related file (and conandata.yml helps identifying this issue), but writing to a random user file is definitely not possible. 

The ``conandata.yml`` is really a small functionality. If you want to have your own files with other data is easy to do: 
- Define your file as you wish
- Make sure to ``exports`` that file
- Load that file when you need it.

That means 2 extra lines in your recipe (which will hardcode the name of the file, as commented above, is the only way to keep consistency and not break very easily), I'd recommend this approach.

**Comment by MaciejPatro** [comment]
Hi @memsharded  

Thanks for the explanation and suggestion!

**Comment by memsharded** [comment]
Glad to help :)

Let us know how it goes, and if there is any further question, do not hesitate to re-open or file a new issue. Thanks!
