### ISSUE TITLE
[bug] Detect misspelling settings

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#6431]
Related issue: https://github.com/conan-io/hooks/issues/149

When removing unknown settings, Conan doesn't raise nothing. Take a look on the issue above the understand a real example.

### Environment Details (include every applicable attribute)
  * Operating System+version: Any
  * Compiler+version: Any
  * Conan version: 1.21.1
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)

Steps can find on the issue commented above.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Logs can find on the issue commented above.

**Comment by memsharded** [comment]
This would be very risky, likely breaking.

It is likely that people are relying on this behavior to do unconditional:

```python
def configure(self):
     del self.settings.compiler.libcxx
```

For all OS and compilers.

An example in our docs here: https://docs.conan.io/en/latest/reference/conanfile/methods.html#configure-config-options

**Comment by memsharded** [comment]
Can be considered again for 2.0, but not now.

**Comment by memsharded** [comment]
Possible test:

```python
def remove_wrong_setting_test(self):
        # https://github.com/conan-io/conan/issues/6431
        client = TestClient()

        conanfile = textwrap.dedent("""
            from conans import ConanFile
            class ConanLib(ConanFile):
                settings = "compiler",

                def configure(self):
                    del self.settings.compiler.unexisting
            """)
        client.save({"conanfile.py": conanfile})
        client.run("install .", assert_error=True)
```

**Comment by uilianries** [comment]
@memsharded what about moving it to Conan Center hooks (again)? The idea is avoiding wrong settings in official Conan recipes.

**Comment by memsharded** [comment]
Lets keep this here, I think it deserves to improve this in Conan 2.0. 
If want to improve this now in hooks, please create a new issue there.

**Comment by memsharded** [comment]
We already made ``del self.settings.compiler.libcxx```fail in conan 2.0. But that also means that we had to introduce a ``self.settings.rm_safe()``, because it was too annoying for users to have to check for existence of a setting in the different platforms.

So seems we are done here, nothing new to do for 2.0
