### ISSUE TITLE
[question] How to prepend path to the MSYS2 PATH variable

### ISSUE THREAD

**Issue by githubuser0xFFFF** [conan-io/conan#6435]
Hi,

when building OpenSLL for MinGW I run into the following issue:

https://github.com/conan-io/conan-center-index/issues/722

The problem can be solved, by prepending the path of my local MinGW installation to the MSYS2 path:

```bash
export PATH=/c/CodingXP/mingw730_32/bin/:$PATH
```

If this is not prepended to the MSYS2 path, then the build fails. The question is, is there any option or possibility (i.e. via a profile) to prepend the path to the MinGW compiler to the MSYS2 path.

Using this in my profile

```
[build_requires]
mingw_installer/1.0@conan/stable
```

is not an option because of this problem:

https://github.com/conan-community/community/issues/311

The environment variable `MSYS2_PATH_TYPE=inherit` is also no solution, because it appends the path. So at the moment it is not possible to successfully build OpenSSL shared library with MinGW because of this problem.

**Comment by danimtb** [comment]
Have you tried setting the path in your profile? https://docs.conan.io/en/latest/reference/profiles.html#package-settings-and-env-vars

Maybe something like this could work:

```
[env]
PATH=[/c/CodingXP/mingw730_32/bin/]
```

This should be applied right before any other path from the dependency is appended, but have not tried it by myself.

**Comment by githubuser0xFFFF** [comment]
Wow, Bingo!!!

That was the solution. Great!!

A really big thank you for your help. Now finally OpenSSL builds without errors :o)

**Comment by danimtb** [comment]
Gald it finally worked! 😄 closing the issue as solved. FOr any other question please open a new one. Than you 👐

**Comment by githubuser0xFFFF** [comment]
Thank you
