### ISSUE TITLE
[bug] PKG Config approach 5 not working

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#6440]
### Environment Details (include every applicable attribute)
  * Ubuntu 18.04
  * gcc7.0:
  * 1.20.0:
  * 3.6:

### Steps to reproduce (Include if Applicable)
make a test package
add the `generators = "pkg_config"`
print out the enironment variable.
The PKG_CONFIG_PATH has not added the build folder of the package
see here:
https://docs.conan.io/en/latest/integrations/build_system/pkg_config_pc_files.html#approach-5-use-the-pkg-config-generator
> # When using the pkg_config generator, self.build_folder will be added to PKG_CONFIG_PATH
>         # so pkg_config will be able to locate the generated pc files from the requires (LIB_A)
Please provide a workarround.

**Comment by danimtb** [comment]
Hi @derived-coder,

I have checked the source code and the `PKG_CONFIG_PATH` variable is being set in the environment with the value of the `self.install_folder` when you are using either the Meson or the Autotools build helper.

We should update the documentation to fix that `self.build_folder`, but it should work the same way if you are using the `conan create` command or any other one that builds the package in the Conan cache.

-----------------------
For reference:
- Meson: https://github.com/conan-io/conan/blob/master/conans/client/build/meson.py#L156
- Autotools: https://github.com/conan-io/conan/blob/master/conans/client/build/autotools_environment.py#L156

**Comment by derived-coder** [comment]
please, set the path also when using cmake tools helper

**Comment by memsharded** [comment]
It is already being set by default:

```python
        if pkg_config_paths:
            pkg_env = {"PKG_CONFIG_PATH":
                       os.pathsep.join(get_abs_path(f, self._conanfile.install_folder)
                                       for f in pkg_config_paths)}
        else:
            # If we are using pkg_config generator automate the pcs location, otherwise it could
            # read wrong files
            set_env = "pkg_config" in self._conanfile.generators \
                      and "PKG_CONFIG_PATH" not in os.environ
            pkg_env = {"PKG_CONFIG_PATH": self._conanfile.install_folder} if set_env else None
```

The only thing is that it is being set to the install_folder, same as others helpers, the code is basically the same as in autootols helper. Why is it not working?

**Comment by derived-coder** [comment]
Hi, @ericLemanissier said something, that when the path is already set, it will not be appended anymore. Which is wrong IMHO. Do you have some test recipes I can use for that? 
But it means the workaround is wrong, I have to use: `cmake.configure(pkg_config_paths=[self.install_folder])` ?

**Comment by ericLemanissier** [comment]
To summarize, @derived-coder is surprised by the fact that if the `pkg_config_paths` argument is not used, _**AND if the `PKG_CONFIG_PATH` environment variable is already set**_ before invoking cmake/meson/autotools build helper, then conan does not add install_folder to the PKG_CONFIG_PATH. This is a legitimate surprise, because this is not documented. however, the workaround is quite simple (using `pkg_config_paths=[self.build_folder]` argument)

**Comment by danimtb** [comment]
I would say it was done this way to not make any mess with the environment set on purpose by users. I think it is a good check and there is already a way to workaround it in an eventual case. They only thing I miss is an update to the documentation

**Comment by derived-coder** [comment]
But this means, everybody has to write this piece of code here
```
cmake.configure(pkg_config_paths=[self.install_folder])
```
Doesn't it validate DRY?

**Comment by danimtb** [comment]
Yes, that would be the case when the `PKG_CONFIG_PATH` env var is already defined. I don't know why it was implemented this way but changing the behavior might be considered as a breaking change 😕 WDYT @memsharded?

**Comment by derived-coder** [comment]
Here also wrong in the documentation: https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#configure

> pkg_config_paths (Optional, Defaulted to None): Specify folders (in a list) of relative paths to the install folder or absolute ones where to find *.pc files (by using the env var PKG_CONFIG_PATH). If None is specified but the conanfile is using the pkg_config generator, the self.install_folder will be added to the PKG_CONFIG_PATH in order to locate the pc files of the requirements of the conanfile.

Please adjust the documentation but I would prefer to fix the behavior

**Comment by memsharded** [comment]
Closing this ticket as outdated, that generator was removed time ago. 
Please create new tickets against latest Conan 2.X if necessary, thanks for your feedback.
