### ISSUE TITLE
Missed CMake variables for default settings values

### ISSUE THREAD

**Issue by 3galki** [conan-io/conan#6455]
If you don't set some value in your profile seems that conan use first value from allowed values list (~/.conan/settings.yml) as default. But no proper cmake variable will be added.

So you can get two different compilations with same package hash value.

In my case I have used CONAN_SETTINGS_COMPILER_SANITIZER value to customize some compilation options and have missed it in my conan profile. So to get it work I have to write following condition in my CMakeList.txt to protect my coworkers from getting unexpected build:

`if (NOT DEFINED CONAN_SETTINGS_COMPILER_SANITIZER OR "${CONAN_SETTINGS_COMPILER_SANITIZER}" STREQUAL "None")`
instead of 
`if ("${CONAN_SETTINGS_COMPILER_SANITIZER}" STREQUAL "None")`

**Comment by memsharded** [comment]
Hi @3galki 

Sorry this was not responded back then, sometimes some issues might fall through the cracks.

This ticket is outdated now, as it talks about the legacy ``CMake`` integration, removed in 2.0 (and deprecated in 1.X too)

Please open new tickets for any issue with the new integrations, thanks!
