### ISSUE TITLE
change dependency on node-semver to be >= rather than ==

### ISSUE THREAD

**Issue by weatherhead99** [conan-io/conan#6459]
Hi, 
would it be possible to change the required dependency on node-semver to be >= 0.6.1 rather than ==0.6.1 or would this break things?

I have done quick but not exhaustive tests on a local build and can't see any problems.
Keeping this as is is something of an annoyance for distro packagers because they have to maintain a separate node-semver package just for conan. The same is true of patch-ng though I did get some errors when trying to unpin that so it may not be possible.

Thanks

**Comment by memsharded** [comment]
Conan 2.0 has dropped the dependency on node-semver, closing this as outdated, thanks!
