### ISSUE TITLE
ConfigureEnvironment does not define LIBS for MinGW

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#646]
For non-Windows systems `LIBS` is set to `" ".join(["-l%s" % lib for lib in self.deps_cpp_info.libs])`. Without this variable it's not possible to build package with dependencies installed by conan if it uses autotools for building, as respective compilation tests fail on linking stage.

**Comment by memsharded** [comment]
We implemented it as ``ConfigureEnvironment.compile_flags``, as we didn't manage to have Windows systems (mingw) honor the ``LIBS`` as environment variable, so we pass it as compile flag. Are you sure it works when passed as environment variable? Will re-check.

**Comment by annulen** [comment]
Yes, this conanfile works for me with MinGW (see `build_with_configure_mingw`):
https://www.conan.io/source/libxml2/2.9.4/annulen/stable

Without LIBS it does not work

**Comment by lasote** [comment]
@memsharded I think it is not for MinGW but for autotools. In this case of autotools in windows (with msys) it's possible that command_line_env should append the same as regular gcc configuration in linux. We should try it.

**Comment by memsharded** [comment]
Same as https://github.com/conan-io/conan/issues/647#issuecomment-283496853, please check.
