### ISSUE TITLE
[bug] Top-level recipe is left out of build-order

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#6460]
### Environment Details (include every applicable attribute)
  * Operating System+version: Debian 10
  * Conan version: develop (commit ebcfe5839b37955bd411d9122cfbfb3bc60e9a83)
  * Python version: 3.7.6

### Steps to reproduce (Include if Applicable)

The STR are in the zip file (note that installing `path.py` and `cli_ui` is an additional requirement)

### Logs (Executed commands with output) (Include/Attach if Applicable)

Note the line 876 of attached log:

>[[('2', 'sqlcipher/4.2.0#c8d883dc3485544775b48fe577fd7fed:0cb0e7660695e4448219e90b31c01821ab150113')]]

I'd expect the build-order to also contain the top-level recipe.
[log.txt](https://github.com/conan-io/conan/files/4148208/log.txt)

**Comment by theodelrieu** [comment]
Here is the lockfile I have: 
[conan.lock.txt](https://github.com/conan-io/conan/files/4148340/conan.lock.txt)

I don't have the issue when using the examples mentioned in the doc, I'll try to dig down further.

**Comment by theodelrieu** [comment]
The difference I get is linked to the line 316 of `client/graph/graph_binaries.py`.

In my use-case, the top-level `node.recipe` is "Consumer", whereas in the conan-io/examples repo, it is `"Cache"`

**Comment by jgsogo** [comment]
Yes, the top-level/root-node of the lockfile is problematic. Thanks a lot for investigating it. 

I'll ask the graph-expert to have a look into it. These flaws are sometimes really hard to tackle (Pareto principle), but we need to fix them too to make the lockfile ready.
