### ISSUE TITLE
[feature] provide alternative way to specify reference in commands such as 'conan install'

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6464]
Currently if you are dealing with packages that have user and channel empty (`_`)  you have to use this slightly off syntax:
```
conan install mylibrary/1.0.0@
```

If conan had an alternative --ref flag it would look as follows:
```
conan install --ref mylibrary/1.0.0
```

Right now we have to hack in our scripts to detect if user provided '@' in their names, if he didnt we are adding '@' to conan invocation.

Also I think having multiple positional arguments that have different meaning is very confusing from my perspective.

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @fulara. This is something needed, and we need it to be congruent for all the interface. Probably, we can't afford such a change before Conan 2. 

There is a little bit said about this in https://github.com/conan-io/conan/issues/5693

**Comment by jgsogo** [comment]
I think that we can merge these two tickets together, would you mind if I copy your suggestion to the other one and close this one?

**Comment by fulara** [comment]
Hello @jgsogo 
Sure, you can copy and close - sorry, my search didnt find that one.

Can I get some insight why do you think this change would be breaking into 1.x?
Seemingly these two could live together, and probably would error out if the user specified mismatching values in those.
Unless you dont agree on the convention this would take?


And Looking at issue you linked - I would like to emphasize that the biggest issue for us is that our scripts have to basically scan versions and add the '@' :(

**Comment by jgsogo** [comment]
Hi! Implementing the `--ref <...>` won't break anything, for sure, it would act as an opt-in, but there are too many things and I feel like we won't be able to address this issue before starting to think about Conan 2 (in fact, we will seriously think about it during [Hearing the tribes session](https://conandays.conan.io/) next month). 

I think this suggestion is worth considering in the other issue. And, if we agree on something for Conan 2.0 that we can backport to 1.x, then it would be better to backport that one as an opt-in than to have one more alternative to pass the reference.

Hope it makes sense

**Comment by fulara** [comment]
Thats unfortuante for my use case - but yep it does makes sense.

**Comment by jgsogo** [comment]
Yes, I'm sorry, but keep an eye on the other issue, maybe the decision is quick and clear and backporting it is easier than we think 😉

**Comment by jgsogo** [comment]
I'm closing this one, let's move the discussion to https://github.com/conan-io/conan/issues/5693, let's see if we can find something that works for Conan 2.0 too
