### ISSUE TITLE
build_policy attribute ignored in conan test packages

### ISSUE THREAD

**Issue by rweickelt** [conan-io/conan#6466]
### Environment Details
  * Conan version: 1.21.2

### Steps to reproduce

In a conanfile.py of a test package
- add a dependency to a package that does not have prebuilt binaries
- define ``build_policy = "missing"`` in the conanfile.py
- invoke ``conan test``

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: Missing prebuilt package for 'xxx'
```

It works with ``conan test --build=missing``.

**Comment by memsharded** [comment]
Hi @rweickelt 

Quick check: are you writing the ``define build_policy = "missing" in which conanfile.py? Are you writing it in the ``test_package/conanfile.py``? The policy only applies to the package recipe itself, not to the test one.

**Comment by rweickelt** [comment]
I am writing this in the `test_package/conanfile.py`. Why does the policy not apply there? It's a (special) package and might have dependencies.

**Comment by memsharded** [comment]
> I am writing this in the test_package/conanfile.py. Why does the policy not apply there? It's a (special) package and might have dependencies.

The ``build_policy`` applies strictly to the declaring recipe, not transitively. 

The ``test_package/conanfile.py`` is NOT the package recipe, that is not the package that is missing. The ``test_package/conanfile.py`` is a consumer conanfile, yes it can have other dependencies, for example, but it is not creating a package itself, only consuming, and that one it is always being built from sources, it doesn't need a build_policy.

**Comment by rweickelt** [comment]
@memshared, thanks, I think I misunderstood this. I thought it applies to the dependencies of a recipe and is equivalent to the --build flag on command line.

**Comment by memsharded** [comment]
Not equivalent, no. It shouldn't be used for most cases, but just for some exceptional packages that for example might be forced to built in the consumers locally, and you want users of the package to be able to do a ``conan install`` and only the package that declares the ``build_policy`` will be affected by that. 

The overall principle is that build_policy and even ``--build`` flag shouldn't be used that much. Binaries should be there by default, and if they are not, they should be created first. The problem with ``--build`` is that it might be hiding failures in the pipeline or in the CI.

If clarified the scope, I think this issue can be closed.

**Comment by rweickelt** [comment]
@memsharded , yes the issue might be closed.

> The overall principle is that build_policy and even --build flag shouldn't be used that much. Binaries should be there by default, and if they are not, they should be created first. The problem with --build is that it might be hiding failures in the pipeline or in the CI.

We are (ab-)using it for meta packages that do not contain own content, but pull in a bunch of requirements needed by several packages.
