### ISSUE TITLE
[bug] Download cache should handle v1 and v2 clients simultaneously

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6467]
Download cache uses URLs for caching things in api V2, which works well for revisioned things, because the revision is a hash. But this fails if clients using v1 keep re-uploading the revision "0", which shouldn't be cached. 
To do:

- Implement return of checksums in Api V2 (@jgsogo). The api is prepared for that.
- Skip the caching of revision "0" artifacts in Api V2.

**Comment by jgsogo** [comment]
What do you mean with...?
> Implement return of checksums in Api V2

**Comment by memsharded** [comment]
```python

class RestV2Methods(RestCommonMethods):

    def _get_file_list_json(self, url):
        data = self.get_json(url)
        # Discarding (.keys()) still empty metadata for files
        data["files"] = list(data["files"].keys())
        return data
```

The api is prepared so data can be retrieved when asked for files in the server. We should return here the checksum of the files, as it is done in the "snapshot" methods of api V1, and propagate those checksums. The first necessary change is to implement that in the server side.
