### ISSUE TITLE
[feature] Expose package versions to build systems

### ISSUE THREAD

**Issue by kdsx** [conan-io/conan#6469]
Sometimes it is useful to know the package version from the build system. E.g. when it should alternate its behavior according to a certain dependency version. Another example is generation of a human-readable list of the used dependencies.

For CMake generator conan would simply set one more variable: `CONAN_<PACKAGE>_VERSION`.

**Comment by memsharded** [comment]
The generators and build helpers are ongoing some efforts of improvements. I suggest to take this into account for the 2.0 efforts in this area.

**Comment by memsharded** [comment]
Conan 2.0 allows this:
- ``self.dependencies["mydep"].ref.version`` gives the dependency version
- This can be used in ``generate()`` method to define whatever information in the current build system.

Both things are already available in conan 1.49 too.
