### ISSUE TITLE
ConfigureEnvironment compatibility between Windows and other systems

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#647]
ConfigureEnvironment works differently on Windows than on other OSes, and this causes troubles when trying to use the same code for configure-driven build on all systems.

* Windows uses separate environment file, so now I have to append " &&" to command_line_env to make commands like "%s sh ./configure" work on all platforms
* Typical tarballs have "framing" directory inside, e.g. for `libxml-2.9.4.tar.gz` this is `libxml-2.9.4`. This leads to following code for running ./configure inside source root:

    env = ConfigureEnvironment(self.deps_cpp_info, self.settings)
    self.run("cd %s && %s ./configure ..." % (self.src_dir, env.command_line_env, ...)

On Windows this cannot work as `command_line_env` depends on `_conan_env.bat` which is located in a top-level directory. OTOH it's not possible to have `command_line_env` first as this will break non-Windows platforms where it is defined as `env VAR=VALUE ...` so environment will affect only `cd`

One possible way to work around all these issues at once is to allow using `/bin/sh` as `self.run` shell and use the same definition of `command_line_env` as on non-Windows.

P.S. It's possible to work around `cd` issue by running configure right in the root directory as `%s/configure`, but it has following limitations:
* There is a lot of software using autotools that doesn't support out-of-tree builds
* This won't work in case `autogen.sh` must be invoked instead of `configure`, e.g. when building from git - it must be run in real source root, not arbitrary directory

**Comment by memsharded** [comment]
Yes, it is very likely. We have had tons of trouble with the Win environment, the way it handles environment variables, concatenating commands and handling expressions, different in the command line and in ``.bat`` files. A total nightmare. You can check some tests about it (not really unit tests, but something we have to play with) in: https://github.com/conan-io/conan/blob/develop/conans/test/integration/vcvars_env_test.py

Finally, the unique solution we managed to provide was with the use of such ``_conan_env.bat`` file, no possible with command line only. Sure it can have problems. About the ``/bin/sh`` shell, it might be possible to add something to ``self.run()`` in conanfile, but adding a shell path in the conanfiles would made them highly non-portable to other machines, don't you think?

Will have a detailed read at your feedback and consider possible solutions when possible, thanks very much.

BTW: I recommend passing ``self``, i.e. a conanfile object to ``ConfigureEnvironment``, it has some better functionalities as using dependencies ``env_info``, or using the same output as the conanfile (scoped, colored)

**Comment by annulen** [comment]
Actually, it would be much more convenient if `self.run` accepted environment as a separate argument, so it won't be required to do shell dances with it and take into account to what directory `_conan_env.bat` is written. Unix provides `execve` (and a few convenience wrappers around it) allowing to run subprocess in modified environment, there may not be direct replacement on Windows however it would be great if Conan emulated it transparently to user

**Comment by annulen** [comment]
>About the /bin/sh shell, it might be possible to add something to self.run() in conanfile, but adding a shell path in the conanfiles would made them highly non-portable to other machines, don't you think?

I see it as an option to `self.run` that sets if we should use cmd as a shell for execution of command passed to `self.run` (default on Windows, current behavior), or use POSIX-like shell (detect if there is `sh` present in current PATH and use it transparantly)

Of course it's possible to run any command with `sh -c` inside `self.run` but that adds a layer of quotes that makes command potentially fragile or require well-thought escaping

**Comment by lasote** [comment]
@annulen But the _conan_env.bat do more things than only adjust environment variables, for example, it call the vcvarsall.bat to set the right Visual Studio envrionment. 

We introduced a new tool http://docs.conan.io/en/latest/reference/tools.html#environment-append to easy call your python code setting env variables if you want to do it manually.

**Comment by annulen** [comment]
environment_append won't help with using ConfigureEnvironment in builds using autotools or make

**Comment by lasote** [comment]
That's why I said "if you want to do it manually."

**Comment by memsharded** [comment]
``ConfigureEnvironment`` has been deprecated in conan 0.20 in favor of new ``AutotoolsBuildEnvironment`` and ``VisualStudioBuildEnvironment`` and much better handling of environment variables. So this issue can be closed, please open a new one for the new helpers if necessary. Thanks!
