### ISSUE TITLE
[feature] ignore .git dir in conan profiles

### ISSUE THREAD

**Issue by a4z** [conan-io/conan#6471]
I am used to put configs into git, and so I do with conan profiles
my `.conan/profiles` directory is under version control

now when I run `conan profile list` , the list starts with 

```
 conan profile list
.git/COMMIT_EDITMSG
.git/HEAD
.git/config
.git/description
.git/hooks/applypatch-msg.sample
.git/hooks/commit-msg.sample
.git/hooks/fsmonitor-watchman.sample
.git/hooks/post-update.sample
.git/hooks/pre-applypatch.sample
.git/hooks/pre-commit.sample
.git/hooks/pre-merge-commit.sample
.git/hooks/pre-push.sample
.git/hooks/pre-rebase.sample
.git/hooks/pre-receive.sample
.git/hooks/prepare-commit-msg.sample
.git/hooks/update.sample
.git/index
.git/info/exclude
.git/logs/HEAD
.git/logs/refs/heads/master
.git/logs/refs/remotes/origin/master
.git/objects/01/f30a01adc5cadf094436f743d23963ba7b3e84
.git/objects/0c/b2c81aa6a456d8914aca032ffa6ccc2e49b907
.git/objects/15/f48801bc396e1843806959600983c1a7ec8689
.git/objects/2b/7d00d6ff81e6118ed6ce0810aa58db12eb52d0
.git/objects/2c/4cdd757f8ba92f298200353c1494810fc3d2b4
.git/objects/3c/005c450e7c778ef1dde21526930c6847f0f427
.git/objects/4c/6ff5cb2341668b5ac36a595f5ed247031e94a0
.git/objects/99/42c202da83e3e4e3993a8f30d7b71429810a07
.git/objects/9a/7982eab2abe80b3c9cd2608d38ff6c551e80d5
.git/objects/aa/c3c5be73856af338c2ff01e7e73425c5447c41
.git/objects/b7/7a8463d8ee500aec35afd1d5b6a68f7ba4a187
.git/objects/be/836eb1216ad3f9456755180c180ed90ce1302a
.git/objects/d2/ff407765b0711d34e85660956f0a7d0b5392aa
.git/refs/heads/master
.git/refs/remotes/origin/master
```
 I wonder if this .git dir could be ignored  by conan profile command ? 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Minimonium** [comment]
Just a small FYI - you can have a git directory with configuration and install it directly with `conan config install url`

**Comment by memsharded** [comment]
The idea is that besides profile,s you can also have other customization: custom remotes to be used, custom settings, custom hooks, even a custom *conan.conf* file. The idea is that all of it can be managed with ``conan config install``, even from multiple origins.

**Comment by a4z** [comment]
thanks for the info! 
this is for sure very useful once my development of packages and profiles has progressed so far that I can release it to others! 
I was already thinking about how to distribute remotes and profile.

For my situation right now, I need to think and check if this will help me during local development also, or add additional steps (or longer command line parameters if the profile is on a different location than the default one).

**Comment by a4z** [comment]
Update:
I have started using `conan config` and this is great!
have the parts I configure/working on in an extra directory, which is under version control
and since updating my local folder is just one command, I have now I deleted .conan/profiles/.git
this is much better, so I think this ticket is not relevant anymore, except maybe for other newbies like me, but they should also learn about `conan config`
Therefore I close this ticket now, hope this is OK
