### ISSUE TITLE
[bug] Automatic user/channel deduction doesn't work for packages just in local cache

### ISSUE THREAD

**Issue by chris-se** [conan-io/conan#6478]
Conan introduced the ability to automatically deduce the user/channel for requires/build_requires a while back, and conan-center packages have been making use of that, having just `self.requires.add("package/version")` instead of `self.requires.add("package/version@user/channel")`. This typically works great, but there is a corner case when this doesn't work, namely if there is no active remote that contains the package.

(The following uses two packages in conan-center-index as an example, but the same issue applies when creating any packages locally with a dependency.)

### Environment Details
  * Operating System+version:  Debian 10 (up to date), x86_64 (shouldn't matter though)
  * Compiler+version: GCC 8 (with Debian), but doesn't matter
  * Conan version: 1.22-dev (git from yesterday, but also happens with earlier versions)
  * Python version: 3.7.3 (from Debian 10)

### Steps to reproduce

 * Download the zlib and libpng package recipies from conan-center-index (as an example, you can use any other packages where you B depends on A)
 * Set a temporary empty CONAN_USER_HOME
 * Disable the conan-center remote
 * Export both recipies (but not the packages)
 * Install zlib
 * Try to install libpng
 * Alternatively: don't install zlib but just install libpng with --build=missing

### Logs (Executed commands with output)

    $ find .
    zlib
    zlib/conanfile.py
    zlib/CMakeLists.txt
    zlib/CMakeLists_minizip.txt
    zlib/conandata.yml
    zlib/minizip.patch
    libpng
    libpng/conanfile.py
    libpng/conandata.yml
    libpng/CMakeLists.txt
    libpng/patches
    libpng/patches/CMakeLists-zlib.patch
    $ mkdir home
    $ export CONAN_USER_HOME=$PWD/home
    $ conan remote disable conan-center
    $ cd zlib
    $ conan export . zlib/1.2.11@dummy/something
    [ ... works correctly ... ]
    $ cd ../libpng
    $ conan export . libpng/1.6.37@dummy/something
    [ ... works correctly ... ]
    $ cd ..
    $ conan install zlib/1.2.11@dummy/something
    [ ... works correctly ... ]
    $ conan install libpng/1.6.37@dummy/something
    ERROR: Failed requirement 'zlib/1.2.11' from 'libpng/1.6.37@dummy/something'
    ERROR: No remote defined
    $ cd libpng
    $ $EDITOR conanfile.py
       [ replace "zlib/1.2.11" with "zlib/1.2.11@dummy/something" ]
    $ conan export . libpng/1.6.37@dummy/something
    $ cd ..
    $ conan install libpng/1.6.37@dummy/something
    [ ... works correctly ... ]

**Comment by danimtb** [comment]
Hi @chris-se and thanks for the report.

This is something that is expected and Conan is correctly reporting that cannot find the `zlib/1.2.11` package because you don't have it installed and you don't have any remote enabled.

Exporting a recipe to a different reference (in this case, with user and channel) does not mean that the recipes containing explicit requires to the reference without user and channel will now use the new reference. If you want this to work you would have to explicitly change the references in the recipes.

Maybe we did not explain it correctly or there is a misleading part in our documentation, but this is not considered a bug and we should improve the explanation for it.

**Comment by chris-se** [comment]
Ah, now I see it, I completely misunderstood what was going on. I thought that having requires = "pkg/version" would just fill the user/channel with the user and channel of the recipie that has the requires, but now I see that it just uses an empty value for user/channel instead, so it actually means "pkg/version@". I just tested it, and exporting zlib as zlib/1.2.11@ instead of zlib/1.2.11@user/channel does indeed work.

I'm closing this, as it clearly isn't a bug - and sorry for the noise.

**Comment by danimtb** [comment]
Glad you made it work! Anyway, thanks a lot for reporting. It is the only way to keep improving Conan 😄
