### ISSUE TITLE
[bug] conan upload fails on 1.22.0

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#6482]
### Summary
A Jenkins job that builds a package and uploads it to Artifactory was working with Conan 1.21.2 but is now failing to upload the package with Conan 1.22.0. 

No errors are displayed in the Jenkins log (see below); I see the recipe successfully uploaded to Artifactory but the package itself does not end up there. What then happens is that the next `build order` thinks the package needs to get built (because it did not end up on Artifactory) and we end up in an endless loop of Jenkins trying to build the package.

All packages are using the same Jenkins code to build (see the 'steps to reproduce' section below to see what the Jenkins pipeline code essentially does). All packages - except for the application - are uploading successfully, making this even more bizarre. The only significance here is that the application package is what the `build order` was generated for.

I reverted back to 1.21.2 and the upload/process in general works again.

### Environment Details
  * Operating System+version: Red Hat Enterprise Linux 7.4
  * Compiler+version: gcc4,gcc7
  * Conan version: 1.22.0
  * Python version: 3.7
  * Jenkins version: 2.164
  * Jenkins Artifactory plugin version: 3.5.0 

### Steps to reproduce
The Jenkins job is essentially doing the following:

1. `conan config install`
2. `conan create`
3. `conan upload`

Pipeline stage:
```
            stage("Upload Artifactory"){
                steps {
                    script {
                        String command = "upload ${params.name_version} --remote ${serverName} --all --confirm"
                        buildInfo = client.run(command: command)
                        buildInfo.env.collect()
                        server.publishBuildInfo buildInfo
                    }
                }
            }
```

### Logs
Jenkins:
13:01:44  [appX_conan_1.22.0_test] $ sh -c "conan upload appX/1.0.0 --remote 2c88c345-e261-4017-8b7a-8602054ed1a4 --all --confirm "
13:01:46  Uploading to remote '2c88c345-e261-4017-8b7a-8602054ed1a4':
13:01:46  
Uploading appX/1.0.0@user/conan_1.22.0_test to remote '2c88c345-e261-4017-8b7a-8602054ed1a4'
13:01:46  Compressing recipe sources...
13:01:51  Uploading conan_sources.tgz -> appX/1.0.0@user/conan_1.22.0_test
13:01:51  Uploading conanfile.py -> appX/1.0.0@user/conan_1.22.0_test
13:01:51  Uploading conanmanifest.txt -> appX/1.0.0@user/conan_1.22.0_test
13:01:51  
Uploaded conan recipe 'appX/1.0.0@user/conan_1.22.0_test' to '2c88c345-e261-4017-8b7a-8602054ed1a4': http://XXXX/artifactory/api/conan/conan-local
13:01:51  
Uploading package 1/1: b198f5cd74d7ad0b383f92c66ed997ce6f0531a1 to '2c88c345-e261-4017-8b7a-8602054ed1a4'
13:01:51  Compressing package...
13:03:44  [appX_conan_1.22.0_test] $ sh -c "conan_build_info /scratchnobackup/devops_jenkins/workspace/appX_conan_1.22.0_test/conan_home/conan_log.log --output /scratchnobackup/devops_jenkins/workspace/appX_conan_1.22.0_test@tmp/artifactory/conan8339048503017901616build-info "
[Pipeline] collectEnv
[Pipeline] publishBuildInfo
13:03:47  Deploying build info to: http://XXXX/artifactory/api/build
13:03:47  Deploying build descriptor to: http://XXXX/artifactory/api/build
13:03:48  Build successfully deployed. Browse it in Artifactory under http://XXXX/artifactory/webapp/builds/appX%20::%20conan_1.22.0_test/2

**Comment by radonish** [comment]
Let me add that I tried the final package build - the application itself - in command line, and the upload worked as expected.

**Comment by memsharded** [comment]
Hi @radonish 

To make sure: you mean that those steps, inside Jenkins, fail, but those exact same steps, without Jenkins, work as expected? Up to my knowledge, nothing changed in 1.22 that would affect uploads, and no idea why Jenkins would interact in that way, breaking the upload. So weird...

**Comment by memsharded** [comment]
Related to https://github.com/conan-io/conan/issues/6330?

**Comment by radonish** [comment]
@memsharded, correct, after I saw the endless loop in Jenkins I stopped the build and then within the command line did essentially the same thing that the Jenkins job was doing:

1. `conan create` (appX/1.0.0)
Because all of the dependencies had successfully uploaded, it downloaded them all from Artifactory and went right into building package appX.

2. `conan upload` (appX/1.0.0)
This was successful command line with 1.22.0. What I found interesting is that it uploaded a different recipe version. I would have expected the same recipe ID since I was building appX from the same exact git commit.

Interesting, I didn't see any output related to the package being dirty, but #6330 sounds related.

**Comment by radonish** [comment]
For what it's worth, we're using package_revision_mode:

default_package_id_mode = package_revision_mode
revisions_enabled = 1

**Comment by KerstinKeller** [comment]
@radonish 

> conan upload (appX/1.0.0)
This was successful command line with 1.22.0. What I found interesting is that it uploaded a different recipe version. I would have expected the same recipe ID since I was building appX from the same exact git commit.

In this case, do you have the same .git settings on your local and build machine? Just a few days ago I ran into the issue of EOL settings for the `conanfile.py`. (Windows with `cr lf` and linux `lf` only). So maybe then could cause a different recipe ID? Just a thought.

**Comment by radonish** [comment]
@KerstinKeller, ah, you bring up a good point. I did the command line test as myself, not the account that Jenkins uses so there is a chance that the .git settings were different. I'll temporarily go back to 1.22.0 and try as the Jenkins user to see if the recipe ID matches.

Thanks!

**Comment by KerstinKeller** [comment]
So what I seemed to find out:
When the recipe has changed, but the binaries haven't, it seems that they are not uploaded again.
E.g. some error handling logic in conanfile.py was added.

**Comment by memsharded** [comment]
I am also doing some progress analyzing the changes in the latest releases, that are connected to the parallel upload with ``--parallel``, that in theory shouldn't affect.... but it seems that they do.

Sorry for the trouble, we will be releasing 1.22.1 with fixes, maybe even backporting to 1.21.

Thanks for all the feedback, please stay tuned, we might need a bit more help 😅

**Comment by radonish** [comment]
@KerstinKeller - you were right in regards to the different recipe ID quirk! 

I did the command line test again as the same user account as the Jenkins job and I got the same recipe ID as Jenkins. Looking into the git configuration options I see that I had "core.autocrlf=input" while the Jenkins user account did not. I'll be creating a common git configuration for the team/Jenkins account to use moving forward.

Thanks!

**Comment by radonish** [comment]
@memsharded, thanks for the update. Glad you're making some progress. I appreciate your quick feedback and investigation. Let me know if I can test anything to help.

Thank you!

**Comment by memsharded** [comment]
I am fixing some things related to the upload in this PR: https://github.com/conan-io/conan/pull/6486

If any of you (cc /@sztomi) can run that branch from source, that would be very useful feedback too.

**Comment by memsharded** [comment]
Hi all,

I also wanted to ask how many of you had defined **hooks** that could be raising errors if some condition of the upload is not met. It is possible that hooks exceptions are being ignored too, with unexpected effects. Concurrency is hard .... :(

**Comment by KerstinKeller** [comment]
So we are currently not using hooks.
But what I realized is that upload only fails on CI, but not when being
executed locally. I have to verify again the version, but everything should
be on 1.22.0.

Parallel upload is not enabled, but revisions are.

When running locally I get very detailed output about the compression
status, not in CI.

I am not sure how to test from sources in the CI easily. This is why I
tried testing locally and realized that the problem does not seem to occur
locally.

James <notifications@github.com> schrieb am Fr., 7. Feb. 2020, 11:29:

**Comment by czoido** [comment]
Hi @KerstinKeller,
Maybe you can try to install that conan version using: `pip install git+git://github.com/memsharded/conan.git@hotfix/broken_parallel_uploads`
That's what I sometimes do to test versions in CI, maybe it helps.

**Comment by radonish** [comment]
@czoido, thank you for that pip command - I was unfamiliar with using pip to install from a git repo.

I'm running a test Jenkins build now with that version of the Conan source.

**Comment by radonish** [comment]
@memsharded, we are not using hooks.

**Comment by radonish** [comment]
@memsharded, my build test failed in a different way now during upload; here is the Jenkins log:

[Pipeline] stage
[Pipeline] { (Upload Artifactory)
[Pipeline] script
[Pipeline] {
[Pipeline] newBuildInfo
[Pipeline] runConanCommand
06:57:50  [appX_conan_1.22.1_test] $ sh -c "conan upload appX/1.0.0 --remote 6fffb717-00f4-4574-b060-672d19e526d2 --all --confirm "
06:57:52  Uploading to remote '6fffb717-00f4-4574-b060-672d19e526d2':
06:57:52  
Uploading appX/1.0.0@cra/conan_1.22.1_test to remote '6fffb717-00f4-4574-b060-672d19e526d2'
06:57:52  Compressing recipe sources...
06:57:58  Recipe is up to date, upload skipped
06:57:58  
Uploading package 1/1: 2e26fc8fa01938782a579d6541ff18e63e2de332 to '6fffb717-00f4-4574-b060-672d19e526d2'
06:57:58  Compressing package...
06:58:34  ERROR: appX/1.0.0@cra/conan_1.22.1_test:2e26fc8fa01938782a579d6541ff18e63e2de332: Upload package failed: write() got an unexpected keyword argument 'file'
06:58:34  ERROR: Errors uploading some packages
[Pipeline] }
[Pipeline] // script
[Pipeline] }

**Comment by KerstinKeller** [comment]
For me, it's the exact same error message:

```
15:05:43  
Uploading package 1/2: 964cba37adb5d2352f2e8e7a977f4b69d69c2e61 to 'artifactory-test'    
15:05:46  Compressing package...
15:06:18  
Uploading package 2/2: caa445deac6f2f357801d240079788bf3f962b1f to 'artifactory-test'    
15:06:18  Compressing package...
15:06:51  WARN: qt/5.11.1@user/stable:964cba37adb5d2352f2e8e7a977f4b69d69c2e61: Removing conan_package.tgz, marked as dirty
15:06:51  WARN: qt/5.11.1@user/stable:caa445deac6f2f357801d240079788bf3f962b1f: Removing conan_package.tgz, marked as dirty
15:06:51  ERROR: qt/5.11.1@user/stable:964cba37adb5d2352f2e8e7a977f4b69d69c2e61: Upload package to 'artifactory-test' failed: write() got an unexpected keyword argument 'file'
15:06:51  ERROR: qt/5.11.1@user/stable:caa445deac6f2f357801d240079788bf3f962b1f: Upload package to 'artifactory-test' failed: write() got an unexpected keyword argument 'file'
15:06:51  ERROR: Errors uploading some packages
```

Two things which I find strange:
Even though I have not enabled parrallel uploads, the order of the printed outputs suggests that at least something is going on in parallel here.

**Comment by memsharded** [comment]
That error is very surprising, but good point to investigate. Thanks @KerstinKeller and @radonish!

> Even though I have not enabled parrallel uploads, the order of the printed outputs suggests that at least something is going on in parallel here.

The code is shared, if not parallel argument is passed, it is just using a ThreadPool of 1 thread, so in practice it is sequential.

I will have a look to that error, thanks again!

**Comment by KerstinKeller** [comment]
> The code is shared, if not parallel argument is passed, it is just using a ThreadPool of 1 thread, so in practice it is sequential.

But then why do I get the output printed in a mixed way:
```
Uploading package 1/2:
Compressing package...
Uploading package 2/2:
Compressing package...
WARN: Removing conan_package.tgz, marked as dirty
WARN: Removing conan_package.tgz, marked as dirty
ERROR: Upload package to 'artifactory-test' failed: write() got an unexpected keyword argument 'file'
ERROR: Upload package to 'artifactory-test' failed: write() got an unexpected keyword argument 'file'
ERROR: Errors uploading some packages
```

Instead I would expect:
```
Uploading package 1/2:
Compressing package...
WARN: Removing conan_package.tgz, marked as dirty
ERROR: Upload package to 'artifactory-test' failed: write() got an unexpected keyword argument 'file'
Uploading package 2/2:
Compressing package...
WARN: Removing conan_package.tgz, marked as dirty
ERROR: Upload package to 'artifactory-test' failed: write() got an unexpected keyword argument 'file'
ERROR: Errors uploading some packages
```

**Comment by memsharded** [comment]
I am really surprised by the `` write() got an unexpected keyword argument 'file'`` and honestly I have no idea where it could come from. I have introduced traces in the PR, so if you could please re-run the same, from the same branch updated, it should show more information. Really appreciate your help and feedback in this!

**Comment by memsharded** [comment]
We have (hopefully) found the bug! . I will be updating my PR accordingly. Seems difficult to cover by tests, but lets try it so this doesnt happen again.

**Comment by memsharded** [comment]
PR https://github.com/conan-io/conan/pull/6486 updated with the fixes :) :) :) 

Please give it a try when possible, and we will try to release 1.22.1 asap. Thanks!

**Comment by Minimonium** [comment]
@memsharded Users have reported the `write() got an unexpected keyword argument 'file'`, I confirmed it locally. 
The problem is that it's hard to make a unit test for it since the tick timeout is 30 seconds by a const variable inside the Progress Bar file, so we have no means of changing it in tests. 
Additionally, tests with the `compress_files` are never using the `output` argument, so this branch is never able to run at all.

**Comment by KerstinKeller** [comment]
I will run the branch first thing Monday morning and try the fixes.

**Comment by radonish** [comment]
@memsharded - I tried PR #6486 and it worked! Thanks for all the effort.

**Comment by memsharded** [comment]
> The problem is that it's hard to make a unit test for it since the tick timeout is 30 seconds by a const variable inside the Progress Bar file, so we have no means of changing it in tests.

I have been able to write a test patching that variable (python can be magic for these things 😄 ). It seems this was also causing https://github.com/conan-io/conan/issues/6330 issues reported by @KerstinKeller, as very lengthy compressions will also crash due to this bug leaving the ``conan_package.tgz.dirty`` state, so the new test covers both uploads and compression, hopefully both bugs are gone now.

**Comment by memsharded** [comment]
Will wait for @KerstinKeller confirmation, but meanwhile merging this to 1.22.1, to pass CI and have the release ready.
