### ISSUE TITLE
[bug] conan export-pkg doesn't fail when exporting a package folder that does not exist

### ISSUE THREAD

**Issue by blastrock** [conan-io/conan#6489]
### Environment Details
  * Operating System+version: Debian unstable
  * Compiler+version: N/A
  * Conan version: 1.22.0
  * Python version: 3.7.5

### Steps to reproduce

- Assuming you have a conan repository with a conanfile.py in ~/myproject
- Run `conan export-pkg --force --package-folder /this/folder/does/not/exist ~/myproject`
- conan will just warn `WARN: No files in this package!` and exit successfully

It is ok to export an empty package, but I would have expected conan to show an error since the folder doesn't exist at all.

### Logs

```
$ conan export-pkg --package-folder /this/folder/does/not/exist ~/work/tanker/conan/cppcodec 
Exporting package recipe
cppcodec/edf46ab: A new conanfile.py version was exported
cppcodec/edf46ab: Folder: /home/philippe/.conan/data/cppcodec/edf46ab/_/_/export
cppcodec/edf46ab: Using the exported files summary hash as the recipe revision: b068bd011732194d966f09f269d94124 
cppcodec/edf46ab: Exported revision: b068bd011732194d966f09f269d94124
cppcodec/edf46ab: Forced build from source
Packaging to 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
cppcodec/edf46ab: Exporting to cache existing package from user folder
cppcodec/edf46ab: Package folder /home/philippe/.conan/data/cppcodec/edf46ab/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
cppcodec/edf46ab: WARN: No files in this package!
cppcodec/edf46ab: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
cppcodec/edf46ab: Created package revision 62acfcc1c48ee02e1a4300df700347a4
```

**Comment by czoido** [comment]
Hi @blastrock,
I have reproduced the issue, and I also think that an error should rise if the folder does not exist.
Thanks a lot for reporting!
