### ISSUE TITLE
[feature] conan install summary should include RREV and PREV in addition to PACKAGE_ID

### ISSUE THREAD

**Issue by blastrock** [conan-io/conan#6491]
Currently, during conan install, we have something similar to this in the logs:

```
Packages
    Boost/1.68.0@tanker/testing:40c0d16e15f77978f412145b089ffefd945f1b63 - Cache
    LibreSSL/2.6.3@tanker/testing:56e0cf6d16ee57367a0661ab743f4e43b29223f8 - Cache
    cppcodec/edf46ab@tanker/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
```

We are now trying to use a package that was built 6 months ago, we need this to test that we didn't break compatibility between the different versions of our product.
We have a project that depends on ourpackage/1.0 which itself depends on Boost/1.68's package from 6 month ago. Running `conan install` in that project fails to find that specific Boost package because now have new revisions and we don't know which one was used at the time.

I suggest that `conan install` should also log the recipe revision and package revision used for the build so that we have a better chance of reproducing the build and being able to reuse and old package.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @blastrock,
The best way you can get reproducibility is by using [lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles.html) so after you build everything if you do a 
`conan graph lock ourpackage/1.0`
you are going to get a `conan.lock` that has all the information on the specific revisions you used to build this package. I think that will give you the information you want to get in the command line output.
Hope this helps

**Comment by blastrock** [comment]
Hi @czoido,

Thank you for your answer! This is indeed the information I need, and this file is even generated by `conan install`. We will print it in the logs for the next time.

It would still have been nice if conan showed that information by default, or maybe even store the lockfile on the conan server when the package is uploaded to be able to reuse it.

Moreover, this information should be printed more often, for example in the "missing prebuilt package" error, conan only gives you the package id:

```
sqlpp11-connector-sqlite3/0.29@tanker/testing: WARN: Can't find a 'sqlpp11-connector-sqlite3/0.29@tanker/testing' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++11, compiler.version=8, os=Linux
- Options: fPIC=True, shared=False, with_cipher=True, LibreSSL:fPIC=True, LibreSSL:shared=False, sqlcipher:fPIC=True, sqlcipher:shared=False
- Dependencies: sqlpp11/0.57@tanker/testing, date/2.4.1@tanker/testing, sqlcipher/4.2.0@tanker/testing
- Package ID: 8d5fd0515c65da04f0c4deca79f6442de00a20fa

ERROR: Missing prebuilt package for 'sqlpp11-connector-sqlite3/0.29@tanker/testing'
Try to build it from sources with "--build sqlpp11-connector-sqlite3"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

I know there *is* a prebuilt package for that package id, but the recipe revision does not match and conan doesn't show that.

**Comment by memsharded** [comment]
Conan 2.0 provide full revision information in the output, both in text and json, closing this ticket as solved.
