### ISSUE TITLE
[bug] Premake generator missing system_libs

### ISSUE THREAD

**Issue by Enhex** [conan-io/conan#6494]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Conan version: 1.22.0

### Steps to reproduce (Include if Applicable)
the generator is missing handling of system_libs, so recipes that use it like `boost/1.72.0` fail to link `pthread`.

**Comment by memsharded** [comment]
Closed by #6495, will be released in 1.22.1
