### ISSUE TITLE
[question] Heavy quantity of log and problem with Travis

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#6497]
Hi,

My project with conan is generating a lot of logs. I tried a lot of things. If i send to /dev/null i get other problem with 10min without log.

I don't know what to do more.

My repository:
https://travis-ci.com/ezored/ezored/jobs/285060835

Can anyone help me?

Thanks.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! I see that your job is compiling a lot of libraries from sources, even 3rd parties. One thing you can do is to compile them once (`openssl`, `Poco`,... are libraries you are not going to modify) and upload them to your bintray repo, then this job will just compile your libraries.

**Comment by dmn-star** [comment]
You can set CONAN_LOG_RUN_TO_OUTPUT to 0 to prevent write  to stdout and/or write the conan outputs to log files by setting CONAN_TRACE_FILE and CONAN_LOG_RUN_TO_FILE.

**Comment by jgsogo** [comment]
Hi. @prsolucoes , were you able to reduce the amount of log?

If not, there are some open issues about `verbosity` of Conan commands that I need to link to this issue too: https://github.com/conan-io/conan/issues/5765
