### ISSUE TITLE
[feature] Run minimal tests in Travis and AppVeyor (autodetection)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6505]
In order to check the autodetection feature in different environments we could connect this repo to Travis and Appveyor (others?) to run some minimal tests: autodetect a profile and verify that the compiler and version found is the one expected.

**Comment by memsharded** [comment]
We moved away from Travis and Appveyor because they were a bottleneck, and also a bit fragile. I wouldn't like to bind again every PR to them. I am fine to configure them to run nightly or something, performing some extra platform tests.
