### ISSUE TITLE
[feature] Update python six requirement to 1.14.0

### ISSUE THREAD

**Issue by AndWass** [conan-io/conan#6506]
Python six has been released for almost a month and for instance openSUSE tumbleweed provides this via the package manager since some system utilities depends on it. The current six requirement makes it impossible to upgrade conan to the latest version via pip on openSUSE tumbleweed.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
I saw a similar case when running on Linux Manjaro 18

**Comment by memsharded** [comment]
Fixed in #6507
