### ISSUE TITLE
[feature] --deploy-generator option : deploy single package only

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#6508]
Hello all.  Apologies for re-opening this topic for the 4th(?) time.  I feel compelled to dig this back up because we're about to go through another major refactor of our internal workflows, and this one hole in the conan api STILL exists, and is going to cause a LOT of engineering code and creativity to workaround yet AGAIN.  

> Edit:  Crucially, I should leave room here for the possibility that I'm misunderstanding something.  Everything here is "as far as I understand it".  I would be delighted to learn that my case is supported by something I am just unaware of. 

Here's some background.... 

https://github.com/conan-io/conan/issues/4847

- I originally pushed for the `deploy` feature and it got implemented despite pushback that the need ~"wasn't clear or proven or strong enough"
    - _Note:  Lots of enterprise users make use of this feature now, as evidenced in slack chat_
- I then continued to push for the `default deploy` feature which was not originally supported, again, because the need ~"wasn't clear or proven or strong enough"
- This FINALLY got implemented as the `deploy generator`, which was a creative compromise and acceptable
    - _Note:  Again, lots of enterprise users make use of this feature now, as evidenced in slack chat_

Nonetheless, somehow, against all odds and despite many peoples efforts, the specific deploy feature my company actually needs remains unsupported.  It was repeatedly technically blocked, left out of scope, or just refused because the need "~wasn't clear or proven or strong enough".  With all the development and discussion that went into these features, it's ABSURD that there is still no way to just copy the contents of the package directory into user space without modifying the recipe.

**Pause:**  
I truly appreciate all the work done by everyone who touched these features, and those who compromised in implementing these features even though they could not see the business case clearly.  I think everybody was operating on good principles the whole time.  However, when considered objectively with hindsight glasses on, hopefully everyone can now agree that continued blockage of this feature doesn't pass the "nonsense test" TM.  

**The Problem:**  
The deploy generator copies the entire dependency tree to the destination folder.  The standard guidance is: "If you only want one file, deploy everything, then delete what you don't need".   To put it bluntly, this is an absurd default behavior.  Enterprise application dependency trees can be massive.  In our case, this means that `conan` would un-necessarily would have to copy tens of thousands of files just to give me a copy of a single `executable` or `runtime library` I want.  I understand "why this seemed like the only way" to implement it at the time (constraints). 

**Moving Forward:**  
The constraints haven't really changed, so any implementation of this feature will require some sort of compromise.  However, I can see two ways to approach implementation of this feature in the current codebase.  Neither breaks backward compatibility.  The first is less elegant but doesn't break rules, the second is more elegant but breaks a "kind-of-rule" that generators don't take parameters or environment variables.  

- Implement a new generator just for this purpose: eg. `--generator deploy_single_package`
- Implement a simple environment variable: eg.  `CONAN_DEPLOY_ALL_DEPS=False`

Any other suggestions which are better would be welcome. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by solvingj** [comment]
Update:  In doing some experimentation, I just got tripped up yet again on another frustrating hole in the API which collides with this problem.  That hole is documented here: 

https://github.com/conan-io/conan/issues/4498

In summary, I wanted to try to deploy the whole tree with the current `deploy generator` and just delete what I don't need until there's a better solution:

`conan install <path_to_conanfile> --generator deploy --install-folder <install_folder>` 

I then discover that this only installs the dependencies to the `<install_folder>` because I specified a `path` rather than a `reference`.   In order to get the actual binaries for the project defined in the `conanfile.py` I am installing to be deployed to `<install_folder>`, I have to provide a full conan reference:

`conan install myproject/version@user/channeldeploy --install-folder <install_folder>` 

So, now, yet again, I need to engineer a cross-platform wrapper solution which derives a full conan reference from a `path_to_conanfile` and a partial reference: `user/channel`

**Comment by Chrismarsh** [comment]
Just noting I would also find `deploy_single_package` to be useful.

**Comment by Pro** [comment]
@solvingj unfortunately this issue was closed without any specific solution.

Did you find a good way to create a single package out of a main conan package and its dependencies?

We have the exact same requirement as you describe above.

**Comment by memsharded** [comment]
Hi @Pro 

It is not clear what you mean, because if you want to ``create a single package out of a main conan package and its dependencies``, then the case is not the same as exposed in this issue. For the ``repackage`` concept, it might be more useful the ``imports()`` approach, to write a recipe that ``imports()`` what it wants from its dependencies (or from that main package, plus dependencies), and then ``package()`` it. Using ``build_requires`` might help to "isolate" the dependencies and do not need them while only consuming. Could you please clarify a bit what is your use case, what do you want to achieve?

**Comment by Pro** [comment]
Thanks for the follow up!
So our main use case is that we are developing a bigger conan software package which is dependent on many other subpackages (external and internal).

At some point we need to deploy the whole software to the customer, i.e., having some kind of installer or similar, which is just installing the application and all its required shared libs and various configuration files coming from subpackages. That installer should then also be able to update a previously installed version.

Similar to the initial post in here, this dependency tree can be very large, and we would like to avoid installing unnecessary files.

So at the end we would like to have some kind of single folder which contains the main binary/executable and all its required shared libraries and config files of all subpackages.
This single folder could then be packaged via makeself or so.

If I check the [documentation of the deploy generator](https://docs.conan.io/en/latest/reference/generators/deploy.html), it also copies a lot of unnecessary files, such as header files or cmake configs, which are not required when solely running the executable on a customer PC.

**Comment by memsharded** [comment]
Thanks @Pro for the clarification. I thought you wanted to "repackage" as another Conan package, but as that is not the case, I would recommend:

- To write a single ``conanfile.py`` recipe, with the ``requires`` and an ``imports()`` method. 
- This method specifies exactly what you want to import (typically only .dlls, license files, and exes)
- executing a ``conan install .`` will just copy everything you specified, and not more, into your local folder, ready for you to package.

Please have a look to https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports, give it a try, and let us know.

**Comment by dscole** [comment]
The proposed solution still doesn't solve the issue of having the entire dependency copied to the deployed host and then only a small number of files would be copied when the `conan install .` would be run. 

My requirement is that I'm deploying to a host and I only want to download the binaries of a specific package, without any of its dependencies, to that host.

**Comment by OleksandrKvl** [comment]
@memsharded in the presence of #10507, is it possible to support installation without dependencies in a given directory?
I have a runtime package, I use `imports()` to bring all the binaries from deps into my package and then I `package()` only them and binaries built by my package so at the end it contains only the runtime part (which is exactly what I need for deploy). It's very unfortunate that now I cannot download this package as is into a directory I want. Such a simple operation should not require any tricks or new conanfiles. `-g deploy` downloads the whole dependency tree. `conan download` is a strange beast, it doesn't allow you to specify target directory and other settings such as `build_type`. Also looks like it downloads only binaries. I also tried repackaging approach and it does the same: pulls dependency tree even though now it comes from `tool_requires`.

**Comment by memsharded** [comment]
Yes, please track the #10507, and give feedback there, this one is closed.
If you see latest changes in #10507, the ``deploy()`` function will be external, defined in a ``deploy.py`` file somewhere. You will be able to specify there any logic you want. We will implement a couple of typical "deployers", but the key point here is that users can write their own ones if they need (and manage them as profiles, or other files, with ``conan config install``) 

Lets continue conversation there, it seems the new "deploy" approach will be much better.
