### ISSUE TITLE
[feature] Conan remove --dryrun

### ISSUE THREAD

**Issue by dakimaz** [conan-io/conan#6512]
Hello.

We would like to request the possibility to add a `--dryrun` flag to `conan remove -f` to see if uninstallation of a package will be successful. 

Right now `conan remove -f` can leave a package in a corrupt state, because it deletes everything it can and skips open files and folders.

In our setup it would be very nice to see if `conan remove -f` would be successful or not and then handle this outcome appropriately, so we don't leave broken packages.

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I don't know if this is accepted here, but thank you for making conan so awesome and robust. It is so robust, we're actually able to use it as a MATLAB package manager!

**Comment by memsharded** [comment]
Hi @dakimaz 

> We would like to request the possibility to add a --dryrun flag to conan remove -f to see if uninstallation of a package will be successful. Right now conan remove -f can leave a package in a corrupt state, because it deletes everything it can and skips open files and folders.

The main problem we have with this, and the reason that some packages might not be completely removed, is that it is basically impossible to know in advance. Conan tries to remove things, and sometimes, the OS, or the antivirus or some other running process (Windows, looking at you), will not allow to remove some specific files. But nothing a ``--dryrun`` could detect, or know. 

Does it happen to you in all OSs, that packages will not be correctly removed from cache?

Conan already tries to change permissions if necessary too, so that is typically not an issue. Some other workarounds have been proposed, like re-trying the removal, but so far they seem too much of a workaround to be implemented as built-in behavior. 



> I don't know if this is accepted here, but thank you for making conan so awesome and robust. It is so robust, we're actually able to use it as a MATLAB package manager!

What? This is amazing! We would like to know more about it, if possible it would be great if you could share something (maybe a blog post, could be invited as guest in Conan blog?)

**Comment by dakimaz** [comment]
> Conan tries to remove things, and sometimes, the OS, or the antivirus or some other running process (Windows, looking at you), will not allow to remove some specific files.

I was afraid of this. We were using MATLABs built-in `rmdir()`, but it has the same issue. It deletes everything it can and leaves the rest.

> Does it happen to you in all OSs, that packages will not be correctly removed from cache?

It is actually tied to us using Conan as a MATLAB package manager. MATLAB itself is usually the culprit, we are currently at a pretty decent place, where most of the time everything goes fine. But a `--dryrun` would have been great for those few instances where it does not go alright.

In any event `conan remove package/* -f` provides a much better error message than `rmdir()`, so you can close this request if you want.

> What? This is amazing! We would like to know more about it, if possible it would be great if you could share something (maybe a blog post, could be invited as guest in Conan blog?)

I would love to! But I have to consult with my manager about permissions, and also with my co-worker who I worked with this past half year in developing it. I will return when I know more tomorrow!

**Comment by memsharded** [comment]
> I was afraid of this. We were using MATLABs built-in rmdir(), but it has the same issue. It deletes everything it can and leaves the rest.

Yes, I guess it is a intrinsic issue, more related to apps interacting with the OS (at a somewhat dangerous level the OS might try to protect) than to any specific app like Conan itself.

My only suggestion here, specially for CI pipelines and automation, is that you can try to run a ``conan search`` just after a ``conan remove`` to check, or maybe just 2 removes one after the other spaced by a small time, and that would probably remove many CI issues. Just in case, we have realized that is is also very important to configure antivirus to exclude the Conan cache and in case of Windows to exclude the cache from indexing. Those 2 things accounted for most of the cases we have seen this.

> In any event conan remove package/* -f provides a much better error message than rmdir(), so you can close this request if you want.

Ok, great, so I will close this issue by now, please reopen or create a new one for further questions or feedback. Many thanks!

**Comment by joeced** [comment]
@memsharded Just a follow-up on  @dakimaz comment

> > What? This is amazing! We would like to know more about it, if possible it would be great if you could share something (maybe a blog post, could be invited as guest in Conan blog?)
> 
> I would love to! But I have to consult with my manager about permissions, and also with my co-worker who I worked with this past half year in developing it. I will return when I know more tomorrow!

I'm the co-worker @dakimaz is referring to, and I have a "go" from our manager to write a blog post. How would we go about this?

**Comment by memsharded** [comment]
Hi @joeced 

> I'm the co-worker @dakimaz is referring to, and I have a "go" from our manager to write a blog post. How would we go about this?

Excellent! :) :) :) 

First, it depends where you want to write this post, if you would like to do it somewhere on your site (company policy, branding, etc), we could just help reviewing, commenting (and at the same time giving feedback, maybe hints of things that could be further improved). If you don't have a blog site, then you are also very welcome to submit to our blog as an invited guest, which is open source too!: https://github.com/conan-io/conan-io.github.io. It is the typical Github jekyll site, written in Markdown, so a Pull Request is the way to go, we will review it and merge it to publish when ready.

Of course, if you prefer to iterate it first in a google doc, please share it to info@conan.io, and we can follow up there.

**Comment by joeced** [comment]
I started writing the blog post as a guest post on your blog. I'll share it with you, once it's ready for comments.
