### ISSUE TITLE
[bug] AutotooldBuildEnvironment with debug build_type needs /FS flag

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#6514]
When building an autotools project using Visual Studio and `Debug` build_type,
an error occurs because multiple processes are writhing to the pdb file.

See https://docs.microsoft.com/en-us/cpp/build/reference/fs-force-synchronous-pdb-writes?view=vs-2019

The `AutotoolsBuildEnvironment` currently does not add this flag so the following error (might) occur:
```
C:/users/maarten/.conan/data/libmodbus/3.1.6/_/_/build/8cf01e2f50fcd6b63525e70584df0326550364e1/source_subfolder/src/modbus-tcp.c: fatal error C1041: cannot open program database 'C:\users\maarten\.conan\data\libmodbus\3.1.6\_\_\build\8cf01e2f50fcd6b63525e70584df0326550364e1\src\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
```

I can fix it by adding `-FS` to the `flags` attribute of the `AutotooldBuildEnvironment` object.
The flag must be added when `build_type` is `Debug` or `RelWithDebInfo`.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2017
  * Conan version: 1.22.0
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
1. Use Windows, Visual Studio, Debug build_type
2. Build a autotools package with the -j flag (e.g. `make -j9`)
I encountered this problem while packaging libmodbus: https://github.com/conan-io/conan-center-index/pull/821
3. Error

**Comment by memsharded** [comment]
``AutotooldBuildEnvironment`` deprecated time ago, removed in 2.0, closing as outdated

**Comment by valgur** [comment]
This still applies to `AutotoolsToolchain` in Conan 2.0, though. It is a [common issue on CCI](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+extra_c+-FS&type=code). The worst part is that this causes build failure only intermittently, which can result in PRs getting merged but binary creation and publishing failing after the fact.

Tbh, I'm not sure Conan should be responsible for fixing this. It should really be a default for MSVC or CMake Debug flags.

**Comment by memsharded** [comment]
Then, it would make sense to create an updated feature request for ``AutotoolsToolchain``. Having those cases in ConanCenter is also useful, I think it could be added to ``AutotoolsToolchain``
