### ISSUE TITLE
conan user:pass for a remote conan_server is forgotten  (Windows)

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#652]
Hi,

I am having some issues from time to time in my CI system (jenkins) when I try to upload packages to my personal conan server. The problem is happening always in the same jenkins-node (a windows 10 machine). Basically when the script tries to upload a package to the conan_server it gets stuck asking for loging

```
14:16:25 Uploading OpenMesh/4.1.1@piponazo/testing
14:16:25 Please log in to "conan-server" to perform this action. Execute "conan user" command.

Jenkins gets stuck here ...
```

However I am sure that I configured previously the user & password for that particular machine with this command:

```
conan user myUser -r myServer -p userPassword
```

Do you know about cases in which conan forgets that configuration ? It only happens some times. When I see this, I go to the remote machine, I configure again the user:pass and then it continues working for some time.

**Comment by memsharded** [comment]
Could it be the expiration of the token? Passwords are not stored, tokens are, but they expire as defined by the server configuration ``jwt_expire_minutes: 120``. By default is 2hrs, is it possible that you set the password and then 2 hours later is the upload?

**Comment by piponazo** [comment]
It must be that. Thanks! I will confirm it tomorrow ;)

**Comment by monsdar** [comment]
The way we solved that is by calling `conan user ...` before we're automatically uploading to the conan server.

**Comment by memsharded** [comment]
Hi @piponazo , did you check this? Was it the token expiring?

**Comment by piponazo** [comment]
Yes, sorry, I forgot to report. After I configured the _jwt_expire_minutes_ in my conan_server I did not have the issue anymore.

**Comment by memsharded** [comment]
Great, thank you!
