### ISSUE TITLE
[question] Is this possible?  conan install + custom_generator + package ref 

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#6522]
Is it possible to do this somehow? 

`conan install --generator <some_custom_generator> <package_reference>`

The specific part here is the combination of it being a `custom_generator` and a `package_reference` (which does not use or know anything about `custom_generator`)

I don't think it's possible, because I don't see a way to get `custom_generator/ver@user/channel` into the dependency tree, so custom_generator will not be knowable to conan.

Of note, I tried adding the generator package into the profile as a `build_requires` but it didn't have any effect.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Minimonium** [comment]
It doesn't work with a reference even if the package knows about the `custom_generator` via the `build_requires` explicit. Only with an in-recipe generator definition.

**Comment by danimtb** [comment]
I think this works if the generator is declared as build require in your profile, but have not tried it

**Comment by Minimonium** [comment]
It works with build requires only if you use a path instead of a reference.

**Comment by danimtb** [comment]
Can be something to consider for the command line changes expected for Conan 2.0
