### ISSUE TITLE
First-time upload works on artifactory local server but fails on remote server

### ISSUE THREAD

**Issue by denny-sun** [conan-io/conan#6531]
These are logs from conan command, it tries to get some file from the path below, this always fails because it's first time upload, but my local server can move forward and succeeds in uploading, remote artifactory server always fails. This sounds strange to me, the only difference between these two logs is that remote server seems only_v2. The error returned from server is status 400 bad request.

```
DEBUG :rest_client_common.py[186]: REST: get: http://<hostname>/artifactory/api/conan/ProjCode-local/v2/conans/ProjCode/0.1/admin/stable/revisions/2f26efbf335842838307c17751ba9fec/files 
```

**Upload to artifactory local server**
```
conan upload ProjCode/0.1@admin/stable --all --force  -r local
DEBUG :conan_api.py   [163]: INIT: Using config 'C:\Users\bruce\.conan\conan.conf' [2020-02-11 16:28:46,415]
DEBUG :tracer.py      [155]: CONAN_API: upload(pattern=ProjCode/0.1@admin/stable,package=None,query=None,remote_name=local,all_packages=True,policy=force-upload,confirm=False,retry=None,retry_wait=None,integrity_check=False,parallel_upload=False) [2020-02-11 16:28:46,421]
Uploading to remote 'local':
Uploading ProjCode/0.1@admin/stable to remote 'local'
DEBUG :rest_client_common.py[161]: REST: ping: http://localhost:8081/artifactory/api/conan/ProjCode-local/v1/ping [2020-02-11 16:28:46,466]
DEBUG :rest_client.py [56]: REST: **Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions']** [2020-02-11 16:28:46,505]
DEBUG :rest_client_common.py[153]: REST: Check credentials: http://localhost:8081/artifactory/api/conan/ProjCode-local/v2/users/check_credentials [2020-02-11 16:28:46,505]
DEBUG :rest_client_common.py[186]: REST: get: http://localhost:8081/artifactory/api/conan/ProjCode-local/v2/conans/ProjCode/0.1/admin/stable/revisions/2f26efbf335842838307c17751ba9fec/files [2020-02-11 16:28:46,511]
DEBUG :rest_client_common.py[36]: REST ERROR: <class 'conans.errors.NotFoundException'> [2020-02-11 16:28:46,517]
DEBUG :rest_client_v2.py[199]:
                               UPLOAD: All uploaded! Total time: 0.05983924865722656
                                [2020-02-11 16:28:46,578]
Uploaded conan recipe 'ProjCode/0.1@admin/stable' to 'local': http://localhost:8081/artifactory/api/conan/ProjCode-local
Uploading package 1/1: 3fb49604f9c2f729b85ba3115852006824e72cab to 'local'
DEBUG :uploader.py    [412]: UPLOAD: Time remote_manager build_files_set : 0.007978 [2020-02-11 16:28:46,590]
DEBUG :rest_client_common.py[153]: REST: Check credentials: http://localhost:8081/artifactory/api/conan/ProjCode-local/v2/users/check_credentials [2020-02-11 16:28:46,630]
**DEBUG :rest_client_common.py[186]: REST: get: http://localhost:8081/artifactory/api/conan/ProjCode-local/v2/conans/ProjCode/0.1/admin/stable/revisions/2f26efbf335842838307c17751ba9fec/packages/3fb49604f9c2f729b85ba3115852006824e72cab/revisions/cb7f048dcaec2231b4e05992e94a70e6/files [2020-02-11 16:28:46,636]
DEBUG :rest_client_common.py[36]: REST ERROR: <class 'conans.errors.NotFoundException'> [2020-02-11 16:28:46,643]**
DEBUG :rest_client_v2.py[199]:
                               UPLOAD: All uploaded! Total time: 0.10272502899169922
                                [2020-02-11 16:28:46,747]
DEBUG :uploader.py    [351]: UPLOAD: Time upload package: 0.166554 [2020-02-11 16:28:46,749]
DEBUG :uploader.py    [360]: UPLOAD: Time uploader upload_package: 0.191487 [2020-02-11 16:28:46,774]
DEBUG :uploader.py    [114]: UPLOAD: Time manager upload: 0.421871 [2020-02-11 16:28:46,848]
```
**********************************************************

**upload on remote server**

```
conan upload ProjCode/0.1@admin/stable --all --force  -r artifactory
DEBUG :conan_api.py   [163]: INIT: Using config 'C:\Users\bruce\.conan\conan.conf' [2020-02-11 16:14:30,532]
DEBUG :tracer.py      [155]: CONAN_API: upload(pattern=ProjCode/0.1@admin/stable,package=None,query=None,remote_name=artifactory,all_packages=True,policy=force-upload,confirm=False,retry=None,retry_wait=None,integrity_check=False,parallel_upload=False) [2020-02-11 16:14:30,539]
Uploading to remote 'artifactory':
Uploading ProjCode/0.1@admin/stable to remote 'artifactory'
DEBUG :rest_client_common.py[161]: REST: ping: http://Projcode-packages.eastus.cloudapp.azure.com:8081/artifactory/api/conan/ProjCode-package/v1/ping [2020-02-11 16:14:30,580]
DEBUG :rest_client.py [56]: REST: Cached capabilities for the remote: **['complex_search', 'checksum_deploy', 'revisions', 'only_v2']** [2020-02-11 16:14:30,832]
DEBUG :rest_client_common.py[153]: REST: Check credentials: http://Projcode-packages.eastus.cloudapp.azure.com:8081/artifactory/api/conan/ProjCode-package/v2/users/check_credentials [2020-02-11 16:14:30,833]
**DEBUG :rest_client_common.py[186]: REST: get: http://Projcode-packages.eastus.cloudapp.azure.com:8081/artifactory/api/conan/ProjCode-package/v2/conans/ProjCode/0.1/admin/stable/revisions/2f26efbf335842838307c17751ba9fec/files [2020-02-11 16:14:30,917]
DEBUG :rest_client_common.py[36]: REST ERROR: <class 'conans.errors.NotFoundException'> [2020-02-11 16:14:57,604]**
ERROR:
Error uploading file: conanfile.py, '**400: Cannot deploy to a remote repository**'
ERROR:
Error uploading file: conanmanifest.txt, '400: Cannot deploy to a remote repository'
ERROR: Execute upload again to retry upload the failed files: conanfile.py, conanmanifest.txt. [Remote: artifactory]
ERROR: Errors uploading some packages
```

**Comment by danimtb** [comment]
Hi @denny-sun,

Please indicate the Conan version you are using and the Artifactory version as well. Looking at your logs, Conan is using API v2 so I guess you have revisions enabled, right? Thanks

**Comment by denny-sun** [comment]
My Conan is updated to 1.22.1. Yes I enabled revision feature. I did some test just now, with the exact same conanfile.py, upload works on local server(windows) but always fails on remote server(linux), I use artifactory C/C++ CE. The remote server returns 400 which seems like bad request, meaning that the server thinks the package is invalid, I just changed conanfile.py to a very simple one with only package name and version without any methods, still same issue.

**Comment by denny-sun** [comment]
I’m trying to change log level of remote artifactory to see if I can get some clue from system log. Is there anything else you want to suggest me to do?

**Comment by memsharded** [comment]
Up to my knowledge, you cannot upload to a remote repository. A remote repository is proxying another one (like ConanCenter). If you want to upload packages it can be done to a Local repository only, or to a Virtual one that has a local repository configured as default upload target.

**Comment by danimtb** [comment]
ok, I think the error comes from trying to upload a package to a remote repository. A remote repository in Artifactory means that it is a "proxy" repository that caches packages coming from another one. For example, you can have a remote repository in Artifactory pointing to ConanCenter central repository hosted in Bintray. This means that by concept, remote repositories cannot be used to upload packages but only to consume them (download).

In case you want to achieve this, you can create a virtual repository that gathers your local repository (to upload packages to) and the remote repository (to consume packages from).

**Comment by denny-sun** [comment]
Do you mean we cannot use Conan upload to directly upload package to a remote artifactory repository? I don’t want to open source my code at this moment so can I still use Conan center? Can you please point me to some document about this proxy repository concept?

**Comment by danimtb** [comment]
No, that is totally fine. you can upload your own private packages to your Artifactory instance in Azure VM.

The issue here is that having a look at the traces, you are using a "remote repository" type: https://jfrog.com/knowledge-base/what-is-a-remote-repository-and-how-does-it-work/ and you should instead just a normal "local repository" one.

These terms might be confusing at first sight but when you learn about the features in Artifactory it totally makes sense. Please try creating a "local" Conan repository in your Artifactory C/C++ community edition hosted in Azure and try to upload the Conan packages there. That should work just as expected 😄

**Comment by denny-sun** [comment]
Thanks Daniel, now it works, yes I agree this is very confusing to a new user, it took me the whole day to diagnose until you pointed me to local repository.

**Comment by danimtb** [comment]
Glad you finally got it. I hope it works as expected now. If you have any other question we will be happy to help anytime. Thanks!
