### ISSUE TITLE
[question] how to cross-compile with cmake_paths generator

### ISSUE THREAD

**Issue by sct2010** [conan-io/conan#6535]
Hello

I am using conan with the cmake_paths generator for a while now and so far it works great. The conan file looks like:
```
class pkgConan(ConanFile):
    ...
    generators = "cmake_paths"

    def configure_cmake(self):
        cmake = CMake(self)
        cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = "conan_paths.cmake"
        cmake.configure()
        return cmake

    def build(self):
        cmake = self.configure_cmake()
        cmake.build()
```

Now I have to cross compile our stack, therefore I setup a toolchain and sysroot conan package and modified the profile.
toolchain conanfile:
```
class ToolchainConan(ConanFile):
    ...
    
    def package_id(self):
        self.info.include_build_settings()
    
    def package_info(self):
        self.env_info.path.append(os.path.join(self.package_folder, "bin"))
        self.env_info.CC = os.path.join(self.package_folder, "bin", "arm-linux-gnueabihf-gcc").replace("\\", "/")
        self.env_info.CXX = os.path.join(self.package_folder, "bin", "arm-linux-gnueabihf-g++").replace("\\", "/")
        self.env_info.AR = os.path.join(self.package_folder, "bin", "arm-linux-gnueabihf-ar").replace("\\", "/")
        self.env_info.RANLIB = os.path.join(self.package_folder, "bin", "arm-linux-gnueabihf-ranlib").replace("\\", "/")
        self.env_info.STRIP = os.path.join(self.package_folder, "bin", "arm-linux-gnueabihf-strip").replace("\\", "/")
```
sysroot conanfile:
```
class SysrootConan(ConanFile):
    ....
    def package_id(self):
        self.info.include_build_settings()
    
    def package_info(self):        
        self.env_info.SYSROOT = self.package_folder
        self.env_info.CMAKE_SYSROOT = self.package_folder
        self.env_info.CMAKE_FIND_ROOT_PATH = self.package_folder
        self.env_info.CMAKE_FIND_ROOT_PATH_MODE_PROGRAM = "NEVER"
        self.env_info.CONAN_CMAKE_FIND_ROOT_PATH = self.package_folder
        self.env_info.CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM = "NEVER"
```
profile:
```
include(default)

[settings]
os=Linux
arch=armv7hf
build_type=Debug
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
compiler.cppstd=17
[options]
[build_requires]
toolchain/1.0@tools/testing
sysroot/1.0@tools/testing
[env]
```

The cross compilation is not working. It doesn't find the system header files. After a quick debugging, I found a workaround:

```
class pkgConan(ConanFile):
    ...
    generators = "cmake_paths"

    def configure_cmake(self):
        cmake = CMake(self)
        cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = "conan_paths.cmake"
        cmake.definitions["CMAKE_SYSROOT"] = os.getenv("SYSROOT", "")
        if os.getenv("SYSROOT"):
            cmake.definitions["CMAKE_FIND_ROOT_PATH_MODE_PROGRAM"] = "NEVER"
        cmake.configure()
        return cmake

    def build(self):
        cmake = self.configure_cmake()
        cmake.build()
```

According to the conan documentation, the CONAN_CMAKE_FIND_ROOT_PATH and CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM variables should automatically applied.
As far I can see, these is only true if the cmake generator is used and not the cmake_paths generator.
> There are some Conan environment variables that will set the equivalent CMake variable using the cmake generator and the CMake build tool

Is there a solution without adjusting all the conan packages and still use the cmake_path generator?

My suggesstion is to extend the conan_paths.cmake file with a similar content as the macro(conan_set_find_paths) in the conanbuildinfo.cmake file of the cmake generator.

```
set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_PREFIX_PATH})
set(CMAKE_FIND_ROOT_PATH ${CONAN_CMAKE_FIND_ROOT_PATH} ${CMAKE_FIND_ROOT_PATH})
if(CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM)
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ${CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM})
endif()
if(CONAN_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${CONAN_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
endif()
if(CONAN_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${CONAN_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
endif()
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
This is one of a number of limitations that the `cmake_paths` generator has over the `cmake`. In fact, `cmake_paths` does not set almost any variable and relies on the cmake file present in your packages. If those files do not provide the information you need or you have to do something else, you will have to do it on the consumer side with the macro you posted.

If you use the `CMake()` build helper you will have the variables like `CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM` injected to the cmake from the environment but you would still have to manage them and apply their values at CMakelists.txt level as you described above.

**Comment by sct2010** [comment]
Let me explain a bit more the setup:
My cmake scripts are designed to work in the conventional way:
```
$ cmake .
$ make
$ make install
```
There is not a single sign o f conan in the cmake files. Everything is handled with the cmake tools like `add_executable, find_package, install(TARGETS` and so an. If im am installing all libraries in the system, the whole stack would build without conan. I use conan only for the local development. So i don't have to compile and install all dependencies in the system prior to start building the main application. 
Thats the reason why I like to use the cmake_path generator over the cmake one. Keep the stack clean and simple:

```
conan -> cmake -> make -> gcc
```
`make` doesn't know anything about cmake and cmake doesnt know anything about conan.

If I have already conan to modify the envirement for cmake, why not using it to do the cross compilation. It would be nice to do a cross compilation of the whole stack by just adding `--profile crossbuild` without modifing the cmake scripts.

Conan already adjusts the `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH`. Why aren't you not modifing the `CMAKE_FIND_ROOT_PATH*` to support crosscompilation. The generator is called cmake_paths and these are PATH variables? I do understand that it is a limited generator and this is fine. I do not need more then adjusting the paths. Setting the compiler is handled by the ENV in the profile and setting the paths by the cmake_path generator. Nothing else is required to handle the crosscompilation.

What do you think about this? Is this the right approach? If so, I would like to open an issue.

**Comment by sct2010** [comment]
During my investigation, I found also a bug in conan. #6546

**Comment by memsharded** [comment]
``cmake_paths`` generator has been superseded in 1.X and removed in 2.0, closing this ticket as outdated.
Please check ``CMakeToolchain`` and report any questions if necessary, thanks.
