### ISSUE TITLE
[question] why must pkg be rebuilt when dependency's package ID hasn't changed?

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#6536]
I am having trouble understanding package ID modes and the build-order output of `conan graph`, and would be grateful for some clarification.

Using the default `semver_direct_mode`, I expected that building a new minor version of a package would have no affect on consumers' package ID meaning it is not required to rebuild the dependants in order to propagate the change.

However, the build order indicates otherwise.  It tells me that the package ID of the consumer has changed and must be rebuilt.

What is going on here?

### Environment Details (include every applicable attribute)
  * Operating System+version:  Windows 10 64-bit
  * Compiler+version: n/a
  * Conan version: 1.21.2
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
```
# compute a different package ID when the major component of the version changes
conan config set general.default_package_id_mode=semver_direct_mode

# create some initial packages
cd my_pkg_a && conan create . my_pkg_a/0.1@user/testing
cd my_pkg_b && conan create . my_pkg_b/0.1@user/testing
cd my_app && conan create . my_app/0.1@user/testing

# freeze app depends in lockfile
conan graph lock my_app/0.1@user/testing --lockfile=release --build

# build new MINOR version of my_pkg_a (won't affect my_pkg_b package ID)
cd my_pkg_a && conan create . my_pkg_a/0.2@user/testing --lockfile=../release

# compute build order of packages that need to be rebuilt
conan graph build-order ./release --json=bo.json --build=missing
```

The initial lockfile for my_app:
```
{
 "profile_host": "[settings]\nadk=[>=4.0.0]\narch=tricore\narch_build=x86_64\nbuild_type=Release\ncompiler=tasking-tricore\ncompiler.flavor=ctc\ncompiler.version=v6.2r2p2\nos_build=Windows\n[options]\n[build_requires]\n[env]\n",
 "graph_lock": {
  "nodes": {
   "1": {
    "pref": "my_app/0.1@user/testing#f5768475aa3b5d3db7352d04e7d35e29:ef6d4f849c7f73e946f391c240d0ddd233fe69a7",
    "options": "",
    "requires": {
     "my_pkg_b/0.1@user/testing#85bba1d218bd570a6cc0bd4a3378d3ab": "2"
    }
   },
   "2": {
    "pref": "my_pkg_b/0.1@user/testing#85bba1d218bd570a6cc0bd4a3378d3ab:4ffeda942b95135e9919386e528ea529e0f3e55f",
    "options": "",
    "requires": {
     "my_pkg_a/0.1@user/testing#df2d7989848a6cfb5b55f2a212eeec94": "3"
    }
   },
   "3": {
    "pref": "my_pkg_a/0.1@user/testing#df2d7989848a6cfb5b55f2a212eeec94:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "options": ""
   }
  }
 },
 "version": "0.2"
}
```

The lockfile after a new minor version of `my_pkg_a` is build, and the build order is computed:
```
{
 "profile_host": "[settings]\nadk=[>=4.0.0]\narch=tricore\narch_build=x86_64\nbuild_type=Release\ncompiler=tasking-tricore\ncompiler.flavor=ctc\ncompiler.version=v6.2r2p2\nos_build=Windows\n[options]\n[build_requires]\n[env]\n",
 "graph_lock": {
  "nodes": {
   "1": {
    "pref": "my_app/0.1@user/testing#f5768475aa3b5d3db7352d04e7d35e29:ef6d4f849c7f73e946f391c240d0ddd233fe69a7#84935620d1675891b9a40d893eab1ac8",
    "options": "",
    "requires": {
     "my_pkg_b/0.1@user/testing#85bba1d218bd570a6cc0bd4a3378d3ab": "2"
    }
   },
   "2": {
    "pref": "my_pkg_b/0.1@user/testing#85bba1d218bd570a6cc0bd4a3378d3ab:b635d5dfc703b976892f7ff229f196d9d8906c51",
    "options": "",
    "requires": {
     "my_pkg_a/0.1@user/testing#df2d7989848a6cfb5b55f2a212eeec94": "3"
    }
   },
   "3": {
    "pref": "my_pkg_a/0.2@user/testing#df2d7989848a6cfb5b55f2a212eeec94:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9#faa23cf4f9ef348c395555b38ebdbc1f",
    "options": "",
    "modified": "Build"
   }
  }
 },
 "version": "0.2"
}
```

It shows the package ID of `my_pkg_b` has changed and the build-order output indicates it must be rebuilt:
``` 
('2', 'my_pkg_b/0.1@user/testing#85bba1d218bd570a6cc0bd4a3378d3ab:b635d5dfc703b976892f7ff229f196d9d8906c51')
```

files to reproduce:
[test_pkg_id_mode_bo.zip](https://github.com/conan-io/conan/files/4192158/test_pkg_id_mode_bo.zip)

**Comment by GordonJess** [comment]
Also, I'd like to know the reasoning behind 'build_requires' not affecting the package ID.

Basically, I want to propagate changes downstream to all the 'build_requires' in order to verify that there are no integration issues before allowing the package to be promoted.

In my mind, if the sources to build a package change then of course the binary must be rebuilt.

**Comment by czoido** [comment]
Hi @GordonJess,
I think that this is related to the fact that in semver `0.Y.Z` versions are not considered stable.
For that reason the package id's generated for each of those versions will be different. If you try the same example with `1.Y.Z` versions it will work as you expect.
It's documented in the [versioning table](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=semver_direct_mode#versioning-schema) but I think that maybe we should add a note to clear it up.

**Comment by GordonJess** [comment]
@czoido,

Ah, got it!  I didn't notice that.  Indeed 1.Y.Z versions work as expected!  Thanks!

...and do you know if there is any plan to have `build_requires` affect the package ID?  I have many build requirements which will affect the binary (such as configs for code generators) and it feels too many to try model with settings.

**Comment by czoido** [comment]
Hi @GordonJess,
We are currently investigating how we can solve this kind of issue and hopefully have some answers soon. I expect that after ConanDays and with the help of the community we have figured this and many more things out.

**Comment by memsharded** [comment]
``package_id`` has changed a lot in Conan 2.0, I am closing this as outdated, please open new tickets as necessary related to new behavior, thanks!
