### ISSUE TITLE
[bug] "conan install" detects the wrong compiler version with gcc 10 and fails

### ISSUE THREAD

**Issue by tjwrona1992** [conan-io/conan#6539]
I am trying to upgrade one of my projects to use gcc 10 so I can use some C++20 features, but I ran into some issues with Conan not wanting to cooperate with the newer gcc version.

See this question for my initial findings: https://github.com/conan-io/conan/issues/6538

It turns out that even after I add "10" as a valid compiler version in "~/.conan/settings.yml" the "conan install" command still looks for the wrong version and fails saying that "1" is not a valid version.

As a temporary workaround I am able to add "1" to the list of versions in "~/.conan/settings.yml" but there's definitely something wrong going on here. Once I add "1" it works.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 19.1.0
  * Compiler+version: gcc 10.0.1
  * Conan version: 1.22.1
  * Python version: 2.7.17

### Steps to reproduce (Include if Applicable)

1. Try to use Conan with a project that uses gcc 10 as the compiler. (currently to use gcc 10 it must be built from source here https://github.com/gcc-mirror/gcc)
2. Add version "10" as a valid compiler in "~/.conan/settings.yml"
3. Attempt to do "conan install" for the project (it will fail saying version "1" is not valid)

```
ERROR: Invalid setting '1' is not a valid 'settings.compiler.version' value.
Possible values are ['10', '4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '7', '7.1', '7.2', '7.3', '7.4', '8', '8.1', '8.2', '8.3', '9', '9.1', '9.2']
```

4. Add version "1" to the list (even though this seems totally wrong)
5. Try again -- "conan install" will work.

**Comment by memsharded** [comment]
Gcc is still not released https://gcc.gnu.org/releases.html. We typically don't add versions to defaults settings until they are released. 

Besides adding 10 to the settings.yml, you probably need to fix the auto-detection of the default profile. Try to run:

```
$ conan profile update settings.compiler.version=10  default
```

Then try again.

**Comment by tjwrona1992** [comment]
Okay I'll remove "1" as a valid version in the yml file when I get home tonight and try running that command and see if that clears it up.

**Comment by tjwrona1992** [comment]
Interestingly enough after I got it to work once I was able to remove "1" as a valid version and it seems to keep working now... not sure why. I may need to do a fresh install of conan to reproduce the issue.

**Comment by tjwrona1992** [comment]
@memsharded I fully uninstalled Conan to reproduce the issue, and was able to make the error occur again.

Your suggestion to set the default compiler worked!

Still confused as to why it thought the version was "1" though until I set the default to "10"

**Comment by memsharded** [comment]
Merged fix, will be released in next Conan 1.23. Thanks for reporting!

**Comment by tjwrona1992** [comment]
Awesome thanks! As it turns out I actually won't be requiring gcc 10 because moving calculations to compile time didn't improve performance as much as I had hoped... Glad I could help find an issue though!

**Comment by memsharded** [comment]
No problem, that way it is fixed when gcc 10 is actually officially released, and more people start to use it! Thanks!
