### ISSUE TITLE
[bug] don't set CMAKE_OSX_DEPLOYMENT_TARGET when build library for iOS

### ISSUE THREAD

**Issue by nguoithichkhampha** [conan-io/conan#6542]
### Environment Details (include every applicable attribute)
  * Operating System+version: MacOS 10.15
  * Compiler+version: clang 11.0
  * Conan version: 1.21.0
  * Python version: 3.7

I'm trying to build a library for iOS with cmake genarator. 
As my testing conan does not set cmake param "CMAKE_OSX_DEPLOYMENT_TARGET" when build for iOS platform.
I also have a question. I created a custom profile to build iOS
`[settings]
arch=arm64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=iOS
os.version=11.0
os_build=Macos`
the meaning is this profile build library run on iOS and build from host = MacOS. So, my understanding about os and os_build is correct ?

- os: the location where library will run

- os_build: the location where library was built

**Comment by jgsogo** [comment]
Hi!

The meaning of the settings is as follows:
 * `os` is related to the _host_, so it is the place where the library will run
 * `os_build` is related to the _build_, so it is the place where the compilation runs

Nevertheless, I have to say that we are working on a new model for cross-building, you can find some PRs opened about it, but we don't have the final model prepared yet. With the current model you may find some limitations (we would really like to hear about them so the new model is as much complete as possible).

Regarding the `CMAKE_OSX_DEPLOYMENT_TARGET`, the logic that adds (or not) it to the flags fro CMake is contained [around these lines](https://github.com/conan-io/conan/blob/af8d48000ea6f968f4605660e86cc6e985a71b04/conans/client/build/cmake_flags.py#L202), indeed, that variable will only be set if `os.version` is provided (✔️ ) and `os` is equal to `Macos`.

According to [CMake docs](https://cmake.org/cmake/help/v3.11/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html) it looks like it should be set for `iOS` too:
> Specify the minimum version of the target platform (e.g. macOS or iOS) on which the target binaries are to be deployed

Thanks for pointing it out

**Comment by nguoithichkhampha** [comment]
yay, thanks for your quick support :)
