### ISSUE TITLE
[feature] `check_min_cppstd` should specifically report on an unknown compiler

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#6547]
The `check_min_cppstd` works, or is intended to work, with default compilers. But it should handle unknown compilers that could be added by users.

Right now it doesn't handle the `None` value returned by the `deduced_cppstd` and proceeds to compare it. Should probably throw a specialized error?
https://github.com/conan-io/conan/blob/develop/conans/client/tools/settings.py#L51

**Comment by uilianries** [comment]
Yes, indeed. When a compiler is not specified, it should throw an error.

About supporting different compiler, I would prefer adding them directly to Conan code base, so we can re-use for other cases.

**Comment by Minimonium** [comment]
I meant that we should let users an ability to handle that use case since it's not necessarily a hard error.
Right now it doesn't do it. `Handle` here means throwing an appropriate error which is not an InvalidConfiguration. :slightly_smiling_face:

**Comment by uilianries** [comment]
That's why we have `valid_min_cppstd`, which does not raise an exception. The user is able to decide what to do.

**Comment by Minimonium** [comment]
You misunderstood. The situation when the tool itself doesn't know about a compiler is a different outcome from a situation if the cppstd if not valid.

**Comment by Minimonium** [comment]
Forgot to mention, this specified exception is required to correctly handle the standard version as described here: https://github.com/conan-io/conan-center-index/issues/54#issuecomment-586006591

**Comment by Minimonium** [comment]
Oh, snap. Sorry folks, but I think I've missed a very important moment:
https://github.com/uilianries/conan/blob/3fe411a8908c8c62241230061c9c439ed79b95fc/conans/client/tools/settings.py#L52
https://github.com/uilianries/conan/blob/3fe411a8908c8c62241230061c9c439ed79b95fc/conans/client/tools/settings.py#L61

These two places raise the same exception. Meaning that there is no way to distinguish these two situations. It effectively blocks _all_ new compiler versions until they and their logic are added into the Conan repository. 

The use case: https://github.com/conan-io/conan-center-index/blob/master/recipes/abseil/all/conanfile.py#L51

**Comment by Minimonium** [comment]
I've made a slight extension of `cppstd` operations capability in https://github.com/conan-io/conan/pull/6713 , to solve my concern in this issue and in related ones.
