### ISSUE TITLE
Autodetection of gcc- and clang-like compiler settings based on environment where conan runs

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#655]
Right now Conan autodetects compiler on first run and writes all settings to conan.conf. However, at least for gcc-like compilers, this approach is error-prone.

It's normal to have more than one of gcc installation on the same host in different prefixes, and compiler is chosen by setting `PATH` variable or even by switching symlinks (e.g. Gentoo's `gcc-config`). This can easily lead to running conan with wrong assumption about compiler settings, installing wrong packages or building packages with incorrect meta information.

I think it would be better to have just compiler="gcc" in conan.conf and automatically determine gcc settings when conan is launched, based on gcc found in PATH

**Comment by lasote** [comment]
> I think it would be better to have just compiler="gcc" in conan.conf and automatically determine gcc settings when conan is launched, based on gcc found in PATH

It sounds tricky. The settings have to be determined by the user by using "-s" command options or using the defaults. If we alter the settings by reading system things like CC or the PATH I'm sure it will be a mess, less deterministic, less "debuggable"...etc. 

I recommend you to use ["profiles"](http://conanio.readthedocs.io/en/latest/conanfile_py.html?highlight=profile#profiles), one per gcc version you have, with the CC and CXX variable defined. I think the user should be responsible to set the settings, this way we ease the multiple "-s" definition with a unique "--profile"

**Comment by annulen** [comment]
>If we alter the settings by reading system things like CC or the PATH I'm sure it will be a mess, less deterministic, less "debuggable"...etc. 

What I had in mind is that if I only have specified `-s compiler="gcc"` conan could fill properly values of `compiler.version` and `compiler.libcxx` in case

"profiles" feature seems to be useful, thanks. Though it won't help if I upgrade installed gcc without changing its path, in that case version needs to be updated in profile manually. I think such behavior is not very "debuggable" either

**Comment by lasote** [comment]
Compiler version could be detected, in fact if you are using CMake it will raise an error if specified setting version doesn't match the real version. But I still think that could be more problematic than keeping the current behavior. 
But conan should not determine libcxx, it's a user choice to use one stdlib or another.

The most we could make is to add a conan warning message when compiler.version mismatch, but not change it.

**Comment by annulen** [comment]
>The most we could make is to add a conan warning message when compiler.version mismatch

That would be useful

>but not change it

I never proposed changing setting, only filling it if it is not set

**Comment by annulen** [comment]
Another case: now conan does not enforce usage of `exception` and `threads` settings for packages built with MinGW, however skipping them is probably a bad practice. So it would be better if conan filled them based on what compiler is being used, again if they are not defined in conan.conf, profile, or command line arguments

**Comment by sourcedelica** [comment]
I would expect Conan to autodetect msys2 and set os.subsystem=msys2 in the default profile, along with gcc, etc.

**Comment by lasote** [comment]
@sourcedelica I think that is a different issue, **please** create a new one to have it present!! Thanks

About the main issue, we encourage the usage of profiles and `conan config install` feature to avoid trusting in the detection. On the other hand, after two years we didn't receive many issues related to this, the detection has been improved and it is working quite good. I'm closing this issue. Thanks all!
