### ISSUE TITLE
[question] How to get the exported recipe reference for further commands?

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#6554]
This question somehow relates to #1746, and is currently appearing as we implement some CI workflows:

Let's imagine we have a recipe file which contains `name` and `version` members. When we export this recipe, we only provide the `user` and `channel`, and `conan export` is able to create a complete recipe reference by assembling the in-recipe members with the command-line parameters. The complete recipe reference ends-up being the usual **name/version@user/channel**

Yet, if we now want to use further commands in the pipeline, some commands will require a complete recipe reference, such as `conan upload`. What would be the recommended way to find such recipe reference?

(We are currently parsing the standard output of `conan export`, but that feels very brittle)

**Comment by jgsogo** [comment]
Hi! I think that the way to go is to provide a `--json` output for `export` command

**Comment by memsharded** [comment]
The command ``conan inspect . --raw=name`` and ``conan inspect . --raw=version`` would help too to get the name and version of any recipe to assemble the full reference by the CI. The ``inspect`` command also has json output if preferred.

**Comment by Adnn** [comment]
Thank you @jsgogo and @memsharded for your quick reponses!

We will be using `conan inspect` in our pipelines, the simple interface is what we need to assemble the final recipe references on the different agents.

**Comment by Adnn** [comment]
@memsharded Actually, found some behaviour that might be considered a bug with this `conan inspect . --raw=name`:

When it is the first command run on an agent, it might first output some loosely related warning:
> WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json

Which appears to be less than desirable, in particular with the `--raw` argument provided.

**Comment by memsharded** [comment]
Another bug while trying to replicate this:

```
$ rm -rf .conan\remotes.json

$ conan inspect zlib/1.2.11@ --raw=version
Traceback (most recent call last):
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\command.py", line 1969, in run
    method(args[0][1:])
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\command.py", line 255, in inspect
    result = self._conan.inspect(args.path_or_reference, attributes, args.remote, quiet=quiet)
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\conan_api.py", line 81, in wrapper
    return f(api, *args, **kwargs)
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\conan_api.py", line 260, in inspect
    remotes = self.app.load_remotes(remote_name=remote_name)
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\conan_api.py", line 198, in load_remotes
    remotes = self.cache.registry.load_remotes()
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\cache\remote_registry.py", line 313, in load_remotes
    "creating default one in %s" % self._filename)
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\output.py", line 121, in warn
    self.writeln("WARN: {}".format(data), Color.BRIGHT_YELLOW, error=True)
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\output.py", line 74, in writeln
    self.write(data, front, back, newline=True, error=error)
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\output.py", line 99, in write
    self._write_err(data, newline)
  File "c:\users\memsharded\envs\conanpip37\lib\site-packages\conans\client\output.py", line 84, in _write_err
    self._stream_err.write(data)
AttributeError: 'bool' object has no attribute 'write'

ERROR: 'bool' object has no attribute 'write'
```

**Comment by memsharded** [comment]
The PR https://github.com/conan-io/conan/pull/6559 removes the WARN.
I am leaving this issue open, we might want to make ``conan export`` to return structured (json?) output containing the recipe reference, even with revision.

**Comment by igor-sadchenko** [comment]
@memsharded 
Conan version **1.24.0**
This warning
`WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json`
also appears when use command:
`conan remote add Conan-index https://artifactory.net/artifactory/api/conan/conan --force --insert 0` for the first time.
When I use `--force` I do not expect any useless warnings.

**Comment by memsharded** [comment]
Conan 2.0 has provided ``--format=json`` output that solves this, closing this ticket as solved
