### ISSUE TITLE
[question] Strategic support to integrate conan into existing VS build environment

### ISSUE THREAD

**Issue by fg68** [conan-io/conan#6557]
I am new to conan and currently evaluating it for usage in our build environment. It should help mainly for creating and using prebuilt packages to minimize build time and maybe hinder a relaxed kind of changing headers and interfaces of base libraries on the root of the dependency tree.

We already have a complex and huge (>10GB) build structure with multiple hundreds of own related packages (see below) and use this structure in different working spaces at the developer site. Therefore we like to avoid the need of copying to and building in conan's data cache, additionally as it may be possible that one has to change a unit of package A in workspace1 and change another unit of same package A in workspace2 and we expect the source code changes to interfere within conan's data cache.

But maybe this fear is unfounded due to a substantial misunderstanding of the conan process.
If not, I guess we would have to use the export-pkg approach but this is kind of manual work due to gathering and specifying build and path informations for the recipe/command.

So I am currently asking for a hint how to setup the conan complementary structure in our build structure and what conan process seems recommandable. - Therefore I provide some basic workspace layout below. 
Thanks for any guideline in advance. 

![image](https://user-images.githubusercontent.com/61189047/74738557-73673f00-5257-11ea-8d2d-ed7d131cdaec.png)
[BuildDirLayout.txt](https://github.com/conan-io/conan/files/4219428/BuildDirLayout.txt)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
What is exactly your goal? What is the pain point you are trying to solve using Conan?

There are lots of different things there. For example, you have a 3rdPartyLibs folder there. Do you want to use Conan to manage the third party libraries? Then in that case, if you want Conan to manage your third party libraries, you should let Conan manage your third party libraries. The process I'd recommend would be:

- Start small. Pick just 1 third party library. Do not aim to fully modularize everything at once.
- Create a Conan package around that third party library, build the binaries for your configurations, put them in your Artifactory.
- Replace that third party library from your project, defining a ``conanfile.txt`` that declares that dependency to that new package you created, and calling ``conan install`` for that ``conanfile.txt``.
- Calling ``conan install`` will put the third party dependency binaries in the Conan cache, not in a copy in your current project. It is not necessary to have them in your project, being in the cache means that it is more efficient, you can safely have different versions, and different binary configurations without colliding, and it can even be reused by other projects in the same machine.
- Use one of the built-in generators, in your case, it seems the ``visual_studio`` or ``visual_studio_multi`` is what you need. It will generate a ``.props`` file for you with the information needed about that dependency.
- Use that ``.props`` file in your other projects that consume that third party library.

I wouldn't change anything else in that layout, or use ``conan export-pkg`` to create packages for your own things, until the above process is well understood, and it is clear the value, what problems does Conan solves, and what problems it does not solve. Specifically, if you want to keep a large monolithic build of your project, a package manager is not what you are looking for. Using a package manager means componentizing/modularizing your code base, and work in smaller units.

I hope this helps.

**Comment by fg68** [comment]
The goal is to version our own internal libraries one by one (and later on during library change/extension), put it into the store/cache and retrieve it from there during build. The pain point is build time. If I checkout a branch from RCS into another local directory I need to compile all internal stuff again. That's where conan should come in using the install command and inject headers, import lib and binaries into the build structure via .props files we already use heavily.

The 3rd party libraries are already prebuilt. For convenient access for our global development team they were put into the workspace though they should have placed separately on a central server. Of course it is an option to move them into conan, but it is not the pain point.

We do not specifically want to keep a large monolithic build. It is just that thereby we can control project dependencies. Each library/package is a component in the system but relies on different other packages hierarchically.

Doing it one by one:
One specific problem with export-pkg I encountered is that I cannot guide conan from wkspc1/sources/contextfolder/projectfolder/conanfile.py to get the lib from wkspc1/build_type arch/temp/projectfolder and put it into a lib folder within the conan package though specifying self.cpp_info.libdirs.

Hopefully this clarifies the aim.

**Comment by memsharded** [comment]
> The 3rd party libraries are already prebuilt. For convenient access for our global development team they were put into the workspace though they should have placed separately on a central server. Of course it is an option to move them into conan, but it is not the pain point.

Understood. But I would still recommend starting here. It is not a big pain point, but it is an isolated thing, very stable, so no new versions come up everyday. And are usually more decouple one from the others. Your own packages/libraries will be typically more inter-connected, requiring more work to migrate.

You might be able to use the ``-g deploy`` generator, and get a local copy in your workspace from the local cache, though I would encourage to use the artifacts directly from the cache, and with the ``.props`` files that Conan automatically generates during installation.

This will allow you to get used to the flows with much lower risk. Then your own packages:

> The goal is to version our own internal libraries one by one (and later on during library change/extension), put it into the store/cache and retrieve it from there during build. The pain point is build time. If I checkout a branch from RCS into another local directory I need to compile all internal stuff again. That's where conan should come in using the install command and inject headers, import lib and binaries into the build structure via .props files we already use heavily.

The same principles apply. You better reuse your own packages directly from the cache, there is actually no need to make yet another extra copy of the artifacts, especially if they are heavy to copy them from the local cache to your workspace folder. If you still want to do that, you can use the ``-g deploy`` generator or the ``imports`` feature. For copied artifacts, you need to provide your own ``.props`` files, as the Conan generated ones will be pointing to the local cache. But you will likely miss things, specially if in the future the packages change.

> We do not specifically want to keep a large monolithic build. It is just that thereby we can control project dependencies. Each library/package is a component in the system but relies on different other packages hierarchically.

The key, is that they depend on other packages hiearchically, but that should be a link/build dependency. It is not intended for doing changes to the source code of multiples packages at the same time, but each package is an independent unit of development, in fact it has its own version, so it can evolve independently to other components.

> One specific problem with export-pkg I encountered is that I cannot guide conan from wkspc1/sources/contextfolder/projectfolder/conanfile.py to get the lib from wkspc1/build_type arch/temp/projectfolder and put it into a lib folder within the conan package though specifying self.cpp_info.libdirs.

There are 2 parts here:
1) First the copy of the artifacts, which can be defined with command line arguments.
   - The ``conan export-pkg`` can assume the layout of the final package is done, then use ``--package-folder`` argument. Everything, including the headers, libs, dlls, everything should be in one folder, and that folder will be copied. The ``package()`` method is not called,  This is not your case, as you have the sources in a different folder than the binaries
   - To specify a splitted layout, you need to specify the source and build folders. You need to provide the ``--source-folder`` to indicate the sources, if your conanfile.py is in the source folder, you can skip this one, as it will get the current conanfile.py folder. Your build folder could be something like ``--build-folder=wspc1/build_type arch/temp/projectfolder``, or you could try to distribute the responsibility and write ``--build-folder=wspc1`` and then write something like this in your ``package()`` (not tested, just an idea):

```python
def package(self):
     build_folder = "%s %s" % (self.settings.build_type, self.settings.arch)
     self.copy("*", src=build_folder)
```

That is the package side of the story. What you are commenting for ``self.cpp_info.libdirs`` is from the ``package_info()``, which is information for the consumers of the package. It is not involved at all in the ``conan export-pkg``, it is only used when it is installed as a dependency, and the information in there will be use for the automatically generated files, like ``conanbuildinfo.props``. If you are using your own .props file probably you don't need it.

Please try the above and let me know if it helps. If not, I think the best to try the above is to set up a github repo, put fake files there emulating the above layout, and be able to run and test, so we could actually collaborate there.

**Comment by fg68** [comment]
Thanks a lot so far.
I will have to go through all those recommendations/ideas and figure out which will do at best or just do at all. On stumbling over specific problems the github fake repo might be a good choice.

**Comment by memsharded** [comment]
> Thanks a lot so far.
I will have to go through all those recommendations/ideas and figure out which will do at best or just do at all. On stumbling over specific problems the github fake repo might be a good choice.

Sounds good.
As this doesn't require action from us at the moment, I am going to close it at the moment. Feel free to comment, reopen it, or ask a new question if it is different enough when you need it. Thanks!

**Comment by fg68** [comment]
So I managed to create something for the export-pfg/install workflow. As well I tried my conanfile.py with the VS extension and got a different result with .props files.
So for now I am going to reevaluate the way with the build approach and would like to keep things separated from the upper approach.

Can I specify a second class within the conanfile.py and redirect conan commands to it or do I have to rename my old conanfile.py and introduce a new one?

**Comment by memsharded** [comment]
Yes, Conan recipes are python scripts. You can import other files, inherit, etc. For the recipe to work correctly, you need to make sure to ``exports`` all files with it, so the files are in the cache.

You can also "formally" reuse python code among recipes, with python_requires: https://docs.conan.io/en/latest/extending/python_requires.html But I wouldn't use those for your case yet.

In your case, I would wait before doing that, and go directly with 2 different conanfile.py. Yes, there will be some repetition, but it is usually manageable, and it also keeps things separated and allow to do changes more easily until stabilizing.
