### ISSUE TITLE
[question] Get recipe revision

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#6564]
Quick question. is there a conan command that returns a given recipe revision? Something like 
`conan info path-to/conanfile.py`

Thanks.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @ericriff,
If you want the revision of a package, you can use the `search `command with the `--revisions` argument. You can also output the result to a `json` file:

`conan search mpfr/4.0.2@ --revisions --json revision.json`

If you have the path to the conan file as an input you could first get the `name` and `version` from the conanfile, then after that doing the search with revisions:

```
conan inspect . -j version.json -a version
conan inspect . -j name.json -a name
```

Hope this helps.

**Comment by ericriff** [comment]
`Conan search` with the `--revisions` argument was exactly what I was looking for. Thanks a lot.
