### ISSUE TITLE
[question] Bintray is down

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#6567]
Hi!

I'm reporting it due more people complained about the same thing, and also if someone looks for some reference about this event.

Bintray is down, it's not possible to download Conan package from Conan Center:

```
Trying with 'conan-center'...
DEBUG :rest_client_common.py[156]: REST: ping: https://conan.bintray.com/v1/ping [2020-02-19 18:49:18,804]
DEBUG :rest_client_common.py[33]: REST ERROR: 500 [2020-02-19 18:49:19,580]
```

According isitdownrightnow.com, Bintray.com is down too.

/cc @markgalpin 

![Screenshot_2020-02-19 Bintray com Down or Just Me ](https://user-images.githubusercontent.com/4870173/74866158-222b7e00-5331-11ea-931a-f7a604aa8a8a.png)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Bintray just updated its status:

https://status.bintray.com/incidents/z3qp5gjzmz3g

**Comment by memsharded** [comment]
Seems bintray recovered. Conan install from conan-center seems to be working now.

**Comment by uilianries** [comment]
Indeed. It's working now. I'm closing this issue.
