### ISSUE TITLE
[feature] Add __main__.py somewere to allow starting conan using python -m conans.XXX

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#6575]
For some public projects, I use conan to provide the dependencies.
For online CI services, such as appveyor and travis, we need to install conan using pip.
By default, these do not have the script paths included in their PATH environment variable.
A warning indicating that is printed while install conan.
It would of course be possible to add these paths to the PATH,
but this causes unreadable code on appveyor which allows multiple os'es: linux, macos and windows. Because we would need to add specific code for all three.

It would be easier if a `__main__.py` file is put somewhere which allows conan to run as a module.
This would allow conan te be run as
```bash
python -m conans
```
or
```bash
python -m conans.client
```

**Comment by jgsogo** [comment]
What about running `python -m conans.conan`?

**Comment by madebr** [comment]
Haha, that works perfect! Thanks!
