### ISSUE TITLE
[question] How to build third-party static libs with -fPIC

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#6578]
I'm trying to inject the ``-fPIC`` setting into a third-party lib based on CMake. I followed the steps described in the [Bincrafters documentation](https://bincrafters.readthedocs.io/en/latest/howtos/add_fpic_option_to_recipe.html) but it didn't work like that.

The documentation claims that internally something like this happens:

> cmake.definitions['CMAKE_POSITION_INDEPENDENT_CODE'] = self.options.fPIC

However, this doesn't seem to be true.

I noticed that only the ``CONAN_CMAKE_POSITION_INDEPENDENT_CODE`` variable is set in the CMake definitions. The CMake run itself states that this variable is set but was not used by the project. The conan source seems to define a CMake macro called ``conan_set_fpic``, that should handle this variable but nobody is calling that macro. In the end, nobody sets the ``CMAKE_POSITION_INDEPENDENT_CODE`` variable.

What's the idea behind all this and how can I solve it?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @fschoenm,

That macro should be called from `conan_basic_setup()`. Did you include something `conanbuildinfo.cmake` and a call to `conan_basic_setup()` in the _CMakeLists.txt_?

```
cmake_minimum_required(VERSION 2.8)
project(MyHello CXX)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_library(hello hello.cpp)
```
As you are using a third party library maybe you can put that in the library's _CMakeLists_ with tools.replace:

```
        tools.replace_in_file("hello/CMakeLists.txt", "PROJECT(MyHello)",
                              '''PROJECT(MyHello)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()''')
```
or create a new _CMakelists.txt_ that wraps the other 3rd party library's one:

```
cmake_minimum_required(VERSION 2.8.12)
project(cmake_wrapper)
include(conanbuildinfo.cmake)
conan_basic_setup()
add_subdirectory("source_subfolder")
```

Also, you have to declare the `fPIC` option in the conanfile.py

```
options = {"shared": [True, False], "fPIC": [True, False]}
default_options = "shared=False", "fPIC=True"    
```

Please, tell me if this helps.

**Comment by fschoenm** [comment]
The third-party lib does not do anything with conan. That's why I tried to inject the behavior. I was hoping to do so without relying on patching its build system.

If I manually set ``cmake.definitions['CMAKE_POSITION_INDEPENDENT_CODE']`` the ``-fPIC`` flag is added as expected, which makes me believe that CMake supports setting this from outside. The Bincrafters docu made me hope that the CMake build helper can do that automatically but as I understand this is not correct if you don't make changes to the CMake list file?

**Comment by memsharded** [comment]
Hi @fschoenm 

I am not sure if I fully understood. The ``cmake.definitions['CONAN_CMAKE_POSITION_INDEPENDENT_CODE ']`` only affects at the current package, the one which conanfile.py contains that line. Adding that thing to your recipe does not inject in any way such flag to the upstream dependencies.

To define fPIC in one of your dependencies, you need to sets its option ``fPIC=True`` (you can set per-package with ``mydep:fPIC=True``, or even to all deps with ``*:fPIC=True``. If that package had defined the option, then it will propagate that value to its build system (cmake or other), if the package recipe is well defined (it might have bugs or omissions, and eventually fail to pass the fPIC option to the build system, but that is a problem of the package conanfile.py recipe)

**Comment by czoido** [comment]
Hi @fschoenm,
So if I did not misunderstand, you don't have a conan package for that third-party lib?
But you have a conan package that depends on that library?
Could you please detail your use case a little bit more?
Thanks.

**Comment by fschoenm** [comment]
We want to use a third-party lib in our own software. We include all third-party libraries via conan but because this third-party lib does not provide a conan package, we have to write our own. Preferably, we don't want to patch the third-party code/build system if we don't have to.

Unfortunately, the third-party lib does not have an option to build a static lib with ``-fPIC`` support. This can, however, be "injected" into their build system by setting the ``CMAKE_POSITION_INDEPENDENT_CODE`` define. This can be done manually in our own conanfile.py for the third-party lib.

My understanding was that the CMake build helper should do that automatically. Alas, it does not. 

I hope I could make the issue more clear. I don't know if my problem is a typical use case but we do indeed often have third-party dependencies that do not provide their own conan packages. In those cases, it is sometimes a little fiddly to make them behave well in a conan context and this is one of those cases.

**Comment by memsharded** [comment]
> My understanding was that the CMake build helper should do that automatically. Alas, it does not.

The CMake build helper will do it automatically if:

- Declared a package option called ``fPIC``.
- Injecting the conan logic (``include(..../conanbuildinfo.cmake)`` and ``conan_basic_setup()`` or at least ``conan_set_fpic()``) into the package CMakeLists.txt. This might be done relatively transparently if using a root CMakeLists.txt that adds those two lines, then proceed to the library CMakeLists.txt

> I hope I could make the issue more clear. I don't know if my problem is a typical use case but we do indeed often have third-party dependencies that do not provide their own conan packages. In those cases, it is sometimes a little fiddly to make them behave well in a conan context and this is one of those cases.

Yes, I agree that the interface to the build systems could be improved, and this is high in our priorities, we already started working on this.

**Comment by fschoenm** [comment]
> The CMake build helper will do it automatically if: [...]

That's my understanding now as well.

The [Bincrafters documentation](https://bincrafters.readthedocs.io/en/latest/howtos/add_fpic_option_to_recipe.html) made it sound like it should work even if the CMake project is not setup for it. It even works if you copy the code from the documentation that sets ``CMAKE_POSITION_INDEPENDENT_CODE`` manually. So my confusion came from the fact that it doesn't do that automatically.

Thanks for the clarification, anyway.

**Comment by czoido** [comment]
Thanks, @fschoenm, as it seems to be clear I will close the issue, please feel free to reopen if you have further questions.
