### ISSUE TITLE
[question] conan_basic_setup breaks find_package

### ISSUE THREAD

**Issue by jroddev** [conan-io/conan#6579]
I have a project that is using conan to install gtest and boost. I am now trying to add [CppKafka](https://github.com/mfontanini/cppkafka) which doesn't have a Conan Recipe (to my knowledge). I am adding CppKafka  using find_package, but I am getting the following linker error:
```
undefined reference to `cppkafka::ConfigurationOption::ConfigurationOption(std::string const&, char const*)'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I comment out `conan_basic_setup()` then CppKafka links fine. 
Am I able to use both conan libraries and non-conan libraries?
Is there some other way I should be handling Conan or CppKafka?

      

```
cmake_minimum_required(VERSION 3.15)
project(kafka_test)
set(CMAKE_CXX_STANDARD 17)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

find_package(CppKafka REQUIRED)

add_executable(kafka_test main.cpp)
target_link_libraries(kafka_test CppKafka::cppkafka)
```

```
[requires]
gtest/1.8.1@bincrafters/stable
boost/1.71.0@conan/stable

[generators]
cmake
```
   

> - Clion 2019.3.4
> - CMake 3.16.3
> - Conan 1.21.1
> - Clang++ 9.0.1
> - Arch Linux

- I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jroddev 

It is possible that Conan is configuring some settings that might be affecting your build and causing the link error.

If you check the ``conan install`` output you would see some configuration, coming from your ``default`` profile. You can also show it with ``conan profile show default``. 

The ``conan_basic_setup()`` will use those and for example can activate the ``libstdc++`` library to link with, but your CppKafka might have been linked with ``libstdc++11``. 

You could try:
- Modify your ``default`` profile (it is a text file, and you also have conan commands to change it if you prefer), to match your desired configuration, including the ``compiler.libcxx`` that you want
- If you are using C++17 to build ,you might want to also set the ``compiler.cppstd=17`` to make sure the binaries for all packages are built with exactly the same standard. Though many times it is possible to link with binaries built with other standards, it is still not 100% guaranteed.
- Depending on the critically of your application you will be good with the default, or you might want to ensure all dependencies use C++17 to build
- If you decide to go for ``compiler.cppstd=17``, there will not be pre-existing binaries in ConanCenter. You can build them from sources with ``--build``, then upload them to your Artifactory (the CE is totally free), so you can use them later easily without rebuilding.

Please let me know if this clarifies it a bit. Thanks!

**Comment by jroddev** [comment]
Hi @memsharded 

Thank you for your help. I'm not sure exactly what fixed it because I was trying a lot of things. 
I think it was:

1. Regenerate conan profile using detect

1. Rebuild and Install CppKafka

1. Rebuild my project


My new profile for reference
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

```

I had a theory that this could have been related to CppKafka linking with Boost on my system and Conan linking to its project scoped version of boost. This turned out to be fine (both Boost versions are 1.71.0)

**Comment by memsharded** [comment]
> I had a theory that this could have been related to CppKafka linking with Boost on my system and Conan linking to its project scoped version of boost. This turned out to be fine (both Boost versions are 1.71.0)

Yes, this could be. A huge problem of the find_xxx.cmake modules that come with CMake and/or different libraries is that they are uncontrollable, some might find some dependencies directly in the system. CMakeLists.txt of libraries might download and build transitive dependencies too, which is another problem. All the CMake ecosystem does not have a clean way to provide information of dependencies and to force it to use those, and not look for them in the system, for example.

This is one of the reasons why we provide the ``cmake_find_package`` generators, because those find_xxx.cmake files generated by Conan contain the right information to find the dependencies and transitive dependencies from Conan correctly.

As this seems to be solved, I am going to close it, but do not hesitate to re-open or create a new issue if you have any further issue. Thanks!
