### ISSUE TITLE
[bug] flatc not compiling on Windows

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [conan-io/conan#6580]
### Environment Details (include every applicable attribute)
  * Windows 10
  * Conan version 1.22.2
  * Python 3.8.1

### Steps to reproduce (Include if Applicable)
conan install flatc/1.11.0@ --build flatc

### Initial work-around
The conanfile specifies a source folder, but this is not used when calling CMake configure. CMake then cannot find the CMakeLists file and aborts.
The build succeeds if I change line 38 from
`cmake.configure(build_folder=self._build_subfolder)`
to
`cmake.configure(build_folder=self._build_subfolder, source_folder=self._source_subfolder)`

### Logs (Executed commands with output) (Include/Attach if Applicable)> conan install flatc/1.11.0@ --build flatc
Configuration:
[settings]
arch=x86
arch_build=x86
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.toolset=v141
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

flatc/1.11.0: Forced build from source
Installing package: flatc/1.11.0
Requirements
    flatc/1.11.0 from 'vt_artifactory1' - Cache
Packages
    flatc/1.11.0:b2fcbc60b3bee75023a4f7934cadb723eec550bd - Build

flatc/1.11.0: Configuring sources in C:\Users\mirko.vonleipzig\.conan\data\flatc\1.11.0\_\_\source
Downloading v1.11.0.tar.gz completed [873.97k]

flatc/1.11.0: Copying sources to build folder
flatc/1.11.0: Building your package in C:\Users\mirko.vonleipzig\.conan\data\flatc\1.11.0\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd
flatc/1.11.0: Generator cmake created conanbuildinfo.cmake
flatc/1.11.0: Calling build()
flatc/1.11.0: WARN: CMake generator could not be deduced from settings
CMake Error: The source directory "C:/Users/mirko.vonleipzig/.conan/data/flatc/1.11.0/_/_/build/b2fcbc60b3bee75023a4f7934cadb723eec550bd" does not appear to contain CMakeLists.txt.

**Comment by memsharded** [comment]
Hi @Mirko-von-Leipzig 

I am trying this. In Windows, it works, but with my default config (Release, x86_64, etc). I am going to check if changing the configuration affects the recipe.

**Comment by memsharded** [comment]
```
(python38) λ conan install flatc/1.11.0@ --build flatc -s arch=x86 -s build_type=Debug -s arch_build=x86 -s compiler.toolset=v141          
Configuration:                                                                                                                             
[settings]                                                                                                                                 
arch=x86                                                                                                                                   
arch_build=x86                                                                                                                             
build_type=Debug                                                                                                                           
compiler=Visual Studio                                                                                                                     
compiler.runtime=MDd                                                                                                                       
compiler.toolset=v141                                                                                                                      
compiler.version=15                                                                                                                        
os=Windows                                                                                                                                 
os_build=Windows                                                                                                                           
[options]                                                                                                                                  
[build_requires]                                                                                                                           
[env]                                                                                                                                      
```
works fine too.                

Can you please run ``conan remove * -f`` before, just in case, then build again?

**Comment by Mirko-von-Leipzig** [comment]
Sorry, ended up being user error. Someone uploaded a custom flatc to our private artifactory which was broken.

**Comment by memsharded** [comment]
No problem, thanks for following up.

Just as a side note for other readers. It is generally a good practice:

- Users cannot upload directly with their user accounts to main artifactory repositories (the ones used by the team to develop), only CI can
- Users can upload to other private Artifactory repos, to share with team, etc., but typically they are not configured by default, or if they are, at least with less priority.
