### ISSUE TITLE
[feature] Remove self.develop attribute in Conan 2.0

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6584]
I think this attribute is problematic and being abused for things that will cause problems later. The behavior should be the same for the recipe, no matter if doing a ``conan install``, or a ``conan create`` or a ``conan build``.

There is the ``self.in_local_cache`` variable, that might be enough.

The only case I can think of that would be ok is to do extra stuff while building, for example, running tests is desired only when directly creating the package, but not while building for consumption. That might probably better managed with something like ``should_test`` already existing in the ``conan build`` command.

To be discussed and analyzed.

**Comment by mkacher** [comment]
I looked into using `self.develop` and decide against it. I agree it could have unintended effects. However seeing this issue I thought it would be good to post a use case for when for when I would want to create the package differently during development:

The recipe for packaging libfoo is out-of-source in libfoo-pkg. I am developing in libfoo. I would like to verify the package builds before I commit and push my changes to libfoo.

Test my changes to libfoo from libfoo-pkg:
$ ~/work/libfoo-pkg/build$ LL_DEV=1 conan create .. libfoo/v0.1.0@mike/dev -pr ../profile1 

Within libfoo-pkg:
```
    def source(self):
        git=tools.Git()
        if getenv('LL_DEV'):
            print('** LL_DEV local libfoo source **')
            self.run('cp -r /home/user/work/libfoo/* .')
        else:
            _branch="master"
            _repo="https://githost.com/libfoo.git"
            git.clone(_repo, _branch)
```

I am completely fine with doing it this way, but it does represent a time that one would execute the recipe differently during development.

**Comment by memsharded** [comment]
Thanks for the feedback @mkacher 

Probably the way to go in Conan 2.0 will be to use more extensively the new [conf] mechanism, that will also be enabled in the command line. That will enable user and Conan built-in switches for recipes, that can be easily controlled independently.

**Comment by memsharded** [comment]
self.develop removed in 2.0.

The recommend way for such a testing flow, is to do a local build, then use ``conan export-pkg``, or to use user ``conf`` for controlling behavior.
