### ISSUE TITLE
[bug] tools.unzip() doesn't preserve symlinks

### ISSUE THREAD

**Issue by carobins** [conan-io/conan#6588]
### Environment Details (include every applicable attribute)
  * Operating System+version: Centos 7.4
  * Compiler+version: 
  * Conan version: 1.22.2
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)
Create a zip file containing symlinks and attempt to extract it with the tools.unzip() method in a conan recipe.

**In recipe:**
def source(self):
    zip_name = "somezipfile.zip"
    unzip(zip_name)

**From shell**
conan source .

In doing this I observe the symlinks are broken.

**Comment by carobins** [comment]
In experimenting with a workaround for this I found the following:

1) os.system("unzip file.zip") - DID NOT WORK
2) import zipfile... extractall() - DID NOT WORK
3) subprocess.call["unzip", "-q", file.zip] - WORKED

Not sure what Conan relies on for extraction, but if it's either of the above two then I don't think these will work.

**Comment by jgsogo** [comment]
Hi! We are using the library `zipfile`: https://github.com/conan-io/conan/blob/bd5920a40d9707001b31966adb0dfa7d6af00eea/conans/client/tools/files.py#L104

After a quick search on the internet, I see that it is not part of the ZIP format and storing symlinks is only available in some implementations. The alternative is to store the target file instead of the symlink.  Can you modify the way that `zip` file is generated? maybe change to another compression format that does support symlinks?

**Comment by SSE4** [comment]
linking #7760. it demonstrates how to successfully zip/unzip symbolic links (all platforms are supported).

**Comment by daravi** [comment]
@jgsogo Is this still in triage? I think it might not be very practical try to patch / update every upstream recipe that packages their source code in ZIP with symlinks. I am not sure how common this is but we also have this issue with the latest version of a third-party package that we have a Conan recipe for. (LibMultisense)

**Comment by DoDoENT** [comment]
I've now stumbled upon this while making conan package for new [Linux version of NDK r23](https://dl.google.com/android/repository/android-ndk-r23-linux.zip) - it's a zip that contains symbolic links. After `tools.unzip` the symbolic links are not preserved and this results with broken conan package.

**Comment by DoDoENT** [comment]
@carobins , `self.run('unzip file.zip')` worked correctly for me (it's much simpler than using `subprocess.call`

**Comment by memsharded** [comment]
Closing this as not planned as not supported by Python and some system tools, so recipes needing to do special unzips of certain zips with symlinks will have to provide their own custom unzip logic.
