### ISSUE TITLE
Add a better way to handle dual compilers.

### ISSUE THREAD

**Issue by tru** [conan-io/conan#659]
On windows it's not uncommon to have a requirement for multiple compilers in large applications. Some OpenSource components (I am looking at you ffmpeg) can not be built reasonable with Visual Studio and require mingw.

Currently to handle this in Conan you need to "fake" that you are using one compiler. I.e. building mingw applications and making sure that the compiler id is set to visual studio. Which requires quite a bit of workarounds to be usable.

In the ideal world you should be able to tell conan that you can use more than one compiler for a project.

**Comment by lasote** [comment]
I understand the need. What are the workarounds to make it usable if you fake the compiler (or ignore the setting) in the mingw library? Just to understand better the problem. Thanks

**Comment by tru** [comment]
We had problems with the compiler check in conanbuildinfo.cmake and the cmake.command_line was using wrong options so we would had to write our own cmake command line and duplicate some code.

**Comment by lasote** [comment]
So, you are linking mingw libs with visual studio libs/exes?

**Comment by tru** [comment]
Yes our main application is a visual studio binary (the devs prefer to work with Visual Studio and the debugger there - I don't blame them), that binary then depends on both mingw C libraries (ffmpeg and a few more) and Visual Studio C++ libraries (since the ABI is not compatible we need to make sure all C++ libs are compiled with VS).

We usually try to get it to work with VS - if it's really hard (autoconf / automake only stuff) and not C++ we build it with mingw. It's not ideal, but we don't want to spend years re-implementing every build-system known to man.

Ideally you could let conan know that VS compiler is compatible with non-C++ dependencies.

**Comment by memsharded** [comment]
This has been addressed by https://github.com/conan-io/conan/pull/689

That PR allows to set individual settings for each package. They can be set in the command line, or in profiles.

Will be released in 0.16.

**Comment by memsharded** [comment]
Released in 0.16
