### ISSUE TITLE
[question] Interactive console for debug purpose

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#6592]
While developing a recipe, sometimes it can be interesting to pause a build and inspect the current file tree or manually try out some things.

Is it possible to start a debug console (cmd.exe or bash) inside a `build()` method?

Adding 
```
        self.run("cmd.exe")
```
Does not work satisfactory because echo-ing does not work as expected.

**Comment by memsharded** [comment]
Have you tried ``os.system("cmd.exe")``?

**Comment by madebr** [comment]
Thanks, that worked fabulous!

I suppose the equivalent for bash on Windows, Linux and Macos is:
```
os.system("cmd.exe")
```
