### ISSUE TITLE
[bug] package not invoked on source directory if using custom `build_id` in combination with `scm` attribute

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#6593]
### Environment Details (include every applicable attribute)
  * Operating System+version: MacOS 10.15.3
  * Compiler+version: Xcode clang 11.0.0
  * Conan version: 1.22.2
  * Python version: 3.7.4

### Steps to reproduce (Include if Applicable)
[conan-missing-headers.zip](https://github.com/conan-io/conan/files/4262204/conan-missing-headers.zip)
Reproducible sample attached. Simple invoke like this:

```
[dodo@knight-rider: conan-missing-headers (master)]$ conan create . -o something=False --ignore-dirty
Exporting package recipe
test/1.0.0: Repo origin deduced by 'auto': bla@bla.bla
test/1.0.0: Revision deduced by 'auto': 54b54c5b92b091f51c9e5eed6b9674d8b4e0abe3
test/1.0.0: SCM: Getting sources from folder: /Users/dodo/conan-missing-headers
test/1.0.0: A new conanfile.py version was exported
test/1.0.0: Folder: /Users/dodo/.conan/data/test/1.0.0/_/_/export
test/1.0.0: Exported revision: b037634fdd4e720307e8aac50ed042c3
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0.0
os=Macos
os_build=Macos
[options]
something=False
[build_requires]
[env]

test/1.0.0: Forced build from source
Installing package: test/1.0.0
Requirements
    test/1.0.0 from local cache - Cache
Packages
    test/1.0.0:a536c34bba1747e269127e75ec63bd8c5413843e - Build

test/1.0.0: Configuring sources in /Users/dodo/.conan/data/test/1.0.0/_/_/source
test/1.0.0: Copying previously cached scm sources
test/1.0.0: Building your package in /Users/dodo/.conan/data/test/1.0.0/_/_/build/a536c34bba1747e269127e75ec63bd8c5413843e
test/1.0.0: Generator cmake created conanbuildinfo.cmake
test/1.0.0: Calling build()
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
    CONAN_COMPILER
    CONAN_COMPILER_VERSION
    CONAN_CXX_FLAGS
    CONAN_C_FLAGS
    CONAN_EXPORTED
    CONAN_IN_LOCAL_CACHE
    CONAN_LIBCXX
    CONAN_SHARED_LINKER_FLAGS


-- Build files have been written to: /Users/dodo/.conan/data/test/1.0.0/_/_/build/a536c34bba1747e269127e75ec63bd8c5413843e
[1/2 ?/sec] Building CXX object CMakeFiles/hello.dir/src/test.cpp.o
[2/2 75.7/sec] Linking CXX static library libhello.a
test/1.0.0: Package 'a536c34bba1747e269127e75ec63bd8c5413843e' built
test/1.0.0: Build folder /Users/dodo/.conan/data/test/1.0.0/_/_/build/a536c34bba1747e269127e75ec63bd8c5413843e
test/1.0.0: Generated conaninfo.txt
test/1.0.0: Generated conanbuildinfo.txt
test/1.0.0: Generating the package
test/1.0.0: Package folder /Users/dodo/.conan/data/test/1.0.0/_/_/package/a536c34bba1747e269127e75ec63bd8c5413843e
test/1.0.0: Calling package()
test/1.0.0 package(): Packaged 1 '.hpp' file: test.hpp
test/1.0.0 package(): Packaged 1 '.a' file: libhello.a
test/1.0.0: Package 'a536c34bba1747e269127e75ec63bd8c5413843e' created
test/1.0.0: Created package revision e981f5231c3bb873ac7775b13dfdf618
[dodo@knight-rider: conan-missing-headers (master)]$ conan create . -o something=True --ignore-dirty
Exporting package recipe
test/1.0.0: Repo origin deduced by 'auto': bla@bla.bla
test/1.0.0: Revision deduced by 'auto': 54b54c5b92b091f51c9e5eed6b9674d8b4e0abe3
test/1.0.0: SCM: Getting sources from folder: /Users/dodo/conan-missing-headers
test/1.0.0: A new conanfile.py version was exported
test/1.0.0: Folder: /Users/dodo/.conan/data/test/1.0.0/_/_/export
test/1.0.0: Package recipe modified in export, forcing source folder removal
test/1.0.0: Use the --keep-source, -k option to skip it
test/1.0.0: Exported revision: b037634fdd4e720307e8aac50ed042c3
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0.0
os=Macos
os_build=Macos
[options]
something=True
[build_requires]
[env]

test/1.0.0: Forced build from source
Installing package: test/1.0.0
Requirements
    test/1.0.0 from local cache - Cache
Packages
    test/1.0.0:3167e7ca4753eaf3a100d067fffe4554038b0cc3 - Build

test/1.0.0: Won't be built, using previous build folder as defined in build_id()
test/1.0.0: Building your package in /Users/dodo/.conan/data/test/1.0.0/_/_/build/a536c34bba1747e269127e75ec63bd8c5413843e
test/1.0.0: Generated conaninfo.txt
test/1.0.0: Generated conanbuildinfo.txt
test/1.0.0: Generating the package
test/1.0.0: Package folder /Users/dodo/.conan/data/test/1.0.0/_/_/package/3167e7ca4753eaf3a100d067fffe4554038b0cc3
test/1.0.0: Calling package()
test/1.0.0 package(): Packaged 1 '.a' file: libhello.a
test/1.0.0: Package '3167e7ca4753eaf3a100d067fffe4554038b0cc3' created
test/1.0.0: Created package revision 7a99dd58b96370284737a5b0abf80cd0
[dodo@knight-rider: conan-missing-headers (master)]$ 
```

Note that first invocation is OK and packages both header and library into the package (as can be seen from the log). However, when the second invocation concludes that _Won't be built, using previous build folder as defined in build_id()_, it invokes `package` only on build folder, but not on source folder. Therefore, the header doesn't get packaged in.

I've managed to reproduce this back to conan v1.18.5 (I didn't try with earlier versions).

If `export_soruces` is used instead of `scm` attribute, the bug is not triggered.

**Comment by DoDoENT** [comment]
It can be also reproduced without `--ignore-dirty` flag.

**Comment by DoDoENT** [comment]
Even more interesting is that the bug is not triggered if you first invoke `conan create . -o something=True` and then `conan create . -o something=False` because conan decides to build the package again, even though build directory with matching build ID exists (maybe a different bug?).

However, if you first invoke `conan create . -o something=False` and then `conan create . -o something=True`, then it's triggered.

**Comment by jgsogo** [comment]
Hi! 

The failure is related to the `no_copy_source=True` (with SCM feature). If I use `no_copy_source=False` it works as expected. I've created a test showing this behavior: https://github.com/conan-io/conan/pull/6594

---

Also related, there is an unfortunate side-effect when you use in your `build_id()` method `del self.info_build.options.something` (instead of the expected [by us] `self.info_build.options.something = "Any"`). It computes the same value for the build folder as the one with option `something=False` and then, each time you run `conan create .... -o something=False` Conan deletes the build folder and the feature doesn't work, the build is run again. Yes, this is a different issue, I'll investigate it too.

**Comment by jgsogo** [comment]
And the issue with the options equal to `False` is in this line: https://github.com/conan-io/conan/blob/bd5920a40d9707001b31966adb0dfa7d6af00eea/conans/model/options.py#L159

it should be `if value is not None`, so the `False` value would be taken into account. This is something we cannot change in Conan v1.x because it will break all existing package IDs, but something to consider for Conan v2.x. I'll open an issue (if there isn't one already).

**Comment by DoDoENT** [comment]
OK, I understand the part with deleting the property: the non-existing property is treated the same as a boolean property set to `False`. If I recall correctly, @memsharded somewhere mentioned that this is actually a feature: it helps in cases when you have a package with no options and then you introduce a boolean option, where `False` means the behaviour as it was before introducing the option. Hence, the same package ID must be calculated in order to avoid rebuilding packages downstream if no breaking change occurred. This then mandates using `self.info_build.options.something = "Any"`, as you expect. Maybe this is something that would be good to have in documentation as a note.

Of course, another option would be to treat `False` and `None` differently.

Regarding the `no_copy_source`, this is indeed a bug - for CMake-based projects, there is no reason to copy the source to the build directory.

**Comment by memsharded** [comment]
``scm`` object removed in 2.0, closing this as outdated.
