### ISSUE TITLE
[question] Is there a way to use full lib path instead of `-lname`?

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#6598]
When I add
```python
self.cpp_info.libs = ["name"]
```
then on macOS it is transformed to the option `-lname`.

All works fine except when I use a dylib with non standard name scheme ("`name`.plugin" instead of "lib`name`.dylib"). Then I get the error "can not find ...".

I know that there is `-l:name` option but Apple binutils does not understand it.

CMake just generates the full lib path instead of `-lname`. So it can utilize it.

Is there a way to generate the full lib path in `conanbuildinfo.xxx` file?

**Comment by Minimonium** [comment]
Hi, Dmitry! 
Conan generates the `cpp_info` on installation, so it should be possible for you to workaround it like this:
```
def package_info(self):
        self.cpp_info.libs = [os.path.join(
            self.package_folder, "lib", "name.plugin")]
```

**Comment by DmitrySokolov** [comment]
Hi,

Thank you for the suggestion. I've tried it, but it didn't work. The error is "Can not find library for -l/Path/to/name.plugin".

However, when I manually remove `-l` prefix in the generated Makefile, it works.

Is there a way to generate the full lib path **without `-l`** prefix in `conanbuildinfo.xxx` file?

**Comment by Minimonium** [comment]
Ah, yes, you're correct. The `-l%s` is hardcoded in generators and in the autotools environment. So we have three ways to solve it:
* Rename the binary files so it'd work with `-l%s`
* Create a custom generator that would check for absolute path
* Make a PR that would special case this situation. 😅

**Comment by memsharded** [comment]
I am a bit confused here. Conan does not generate ``-lxxx`` in the cmake generators. I guess this is talking about the other generators.

**Comment by DmitrySokolov** [comment]
@memsharded 
I mean that CMake itself generates full lib paths instead of `-lname` on macOS, so it is possible to use libs with non standard name scheme.

**Comment by jgsogo** [comment]
Hi, @DmitrySokolov . 

I see that we are using the approach @Minimonium says above (`-l%s`) for some of our generators, at least `compiler_args`, `gcc`, `xcode`, `pkg_config`, `qmake` and also for the `AutoToolsBuildEnvironment`. Currently there is no workaround as it is hardcoded in the sources, so any of the three alternatives enumerated by @Minimonium are the way to go.

Which generator are you using in order to prioritize it?

---

Probably the most conservative solution would be to provide the full path and make the generators detect it.

**Comment by jgsogo** [comment]
Oh, I've just seen the PR https://github.com/conan-io/conan/pull/6600

**Comment by memsharded** [comment]
Closing ticket as referencing the legacy integrations like ``conanbuildinfo.xxx`` that have been removed in Conan 2.
