### ISSUE TITLE
[bug] export-pkg does not propagate profile env vars to conaninfo.txt

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#6603]
### Environment Details (include every applicable attribute)
  * Conan version: 1.23.0 (dev)
  * Python version: 3.7.6

### Steps to reproduce (Include if Applicable)

* Add an env var to some profile (`[env]` section)
* `conan create` some package, look at the `conaninfo.txt`, env var should be there
* `conan export-pkg` the same package, the `conaninfo.txt` does not contain the env var

### Logs (Executed commands with output) (Include/Attach if Applicable)

A bit of context:

I'm using lockfiles with `package_revision_mode`, I have a `build` CI stage that builds a recipe, and all its reverse dependencies. Then, it uploads all the built packages, and the associated lockfiles, as artifacts (i.e. not via `conan upload`, but via GitLab CI).

The next CI stage then run `conan export-pkg` on those packages, and builds the root project.
This ensures that everything builds/runs correctly before uploading the modified packages to the Conan remote, making them available to devs.

The problem is that `conan export-pkg` fails with the following error:

>ERROR: Mismatch between lock and graph:
Lock:  libressl/3.0.2#efcd8746035205fc00f50460c3a9e7b9:1d877a3df840030e6a8abb74c5ffb9088d08b47a#79ddf96dcbc19108783a417e0a9d2723
Graph: libressl/3.0.2#efcd8746035205fc00f50460c3a9e7b9:1d877a3df840030e6a8abb74c5ffb9088d08b47a#14cae2db399de7f1cf37613145d0aae0

The `libressl` PREV has changed! While I could simply pass `--lockfile` to `export-pkg`, it does not seem right to modify revisions and package IDs when the packages are left unchanged.

After digging a bit, this is caused by the `conanmanifest.txt`, and more specifically by the generated `conaninfo.txt` which does not include profile env vars.

In my `gcc8-release` profile, I have the following `[env]` section:

```ini
[env]
CC=gcc-8
CXX=g++-8
```

Those two vars are only present in the `conaninfo.txt` when using `conan create`, not `conan export-pkg`.

Digging even more, I came across the following code in `conans/client/installer.py`, line 495:

```python
        # Update the info but filtering the package values that not apply to the subtree
        # of this current node and its dependencies.
        subtree_libnames = [node.ref.name for node in node_order]
        for package_name, env_vars in conan_file._conan_env_values.data.items():
            for name, value in env_vars.items():
                if not package_name or package_name in subtree_libnames or \
                   package_name == conan_file.name:
                    conan_file.info.env_values.add(name, value, package_name)
```

Printing the `conan_file._conan_env_values` shows the `CC`/`CXX` env vars.
So I've tried to add the same thing to `conans/client/cmd/export_pkg.py`, line 28:

```python
    for package_name, env_vars in conanfile._conan_env_values.data.items():
        for name, value in env_vars.items():
            conanfile.info.env_values.add(name, value, package_name)
```

And it does work! The env vars correctly appear in the `conaninfo.txt`.

I'm sure there is more subtlety required than in my proposed patch though...

**Comment by memsharded** [comment]
Fixed, will be released in 1.23
