### ISSUE TITLE
[question] conan install with version range only checks local cache, never remote

### ISSUE THREAD

**Issue by gunnwo** [conan-io/conan#6604]
- running Conan version 1.22.2.
- remote artifactory has several packages with sematic versioning, local cache is emtpy

checking existing packages in remote artifactory:
```
conan search "compA/1.0*@me/stable" -r all
compA/1.0.40-901@me/stable
compA/1.0.40-903@me/stable
compA/1.0.40-906@me/stable

```
my recipe conanfile.txt:
```
[requires]
compA/[>=1.0]@me/stable

[generators]
cmake
visual_studio
```

Now I run a "conan install... --remote all --update" (with or without --update).
This command returns with an error message that it cannot be resolved via local cache. It seems that no single remote repo was checked.
But: documentation says it searches first in local cache, then in remotes:
"If no matching version is locally found, it starts to search in the remotes, in order. If some remote is specified with -r=remote, then only that remote will be used."

What is the proposed workaround here? Please consider that I want to start the build in a later step once I'm more familiar with conan.

note: the build machines are automatically created from a docker image, the cache is always emtpy.

**Comment by jgsogo** [comment]
Hi! According to the documented behavior, the `-r all` is not available for all the commands, `conan search .... -r all` will look in all the remotes, but `conan install ... -r all` will look **only in the remote called `all`**. If there is no remote called `all` it will fail:

```bash
> conan install . --update -r all
ERROR: No remote 'all' defined in remotes
```

(You can check your list of remotes with `conan remote list`)

Maybe this is something to take into account when working in a new CLI definition (cc/ @czoido )

---

Regarding your issue, if I use a valid remote with a requires like `cmake/[>=3]` I get:

```bash
> conan install . --update -r conan-center
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

cmake/3.16.4: Retrieving from server 'conan-center'
cmake/3.16.4: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.17k]
Downloading conanfile.py completed [3.10k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
cmake/3.16.4: Downloaded recipe revision 0
....
```
