### ISSUE TITLE
[feature] Add ability to ignore specific submodules in `scm` attribute

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#6606]
This might seem similar to #6605, but is in fact quite different.

The idea is to be able to specify that when initializing submodules, some submodules should be ignored. It is often the case that test data is put into git submodule of the project and that data may sometimes contain large files, which we do not want to clone when the package is being built by dependency.

For example, a proposed syntax would look something like this:

```python

class MyPackage(ConanFile):
    ...
    scm = {
        "type": "git",
        "url": "auto",
        "revision": "auto",
        "submodule": {
            "type": "recursive",
            "ignore": [ "test-data/some-data", "test-data/some-more-data", ... ]
    }
```

The current limitation to either clone all submodules or no submodules require that you either put test data into a conan package and depend on it only during development or to put all your dependencies into conan packages. The latter is definitely ideal, but can be quite a PITA during transition period or fore some specific dependencies that you may need only for testing and never for production.

**Comment by memsharded** [comment]
So, if I understood this correctly, this is an optimization to avoid cloning some submodules that are actually not needed for the package while others are still needed. 

I think it is a bit too much added complexity for a transition period. I would suggest to do the opposite:

- Use ``submodule=False``
- Add the ``git submodule`` logic that you want in your ``source()`` method

**Comment by DoDoENT** [comment]
> I think it is a bit too much added complexity for a transition period. I would suggest to do the opposite:
>
> -Use submodule=False
> -Add the git submodule logic that you want in your source() method

Thank you. I'll try that. I didn't think it's legal to combine both `scm` attribute and `source` function. I guess that in that case `source` is executed after cloning the repository by using information from the `scm` attribute...

**Comment by jgsogo** [comment]
Yes, `source()` is executed after cloning the repo from SCM.

**Comment by DoDoENT** [comment]
Well, in that case, this is not an issue 😃
