### ISSUE TITLE
Improvements to the search command for checking for outdated packages

### ISSUE THREAD

**Issue by tru** [conan-io/conan#661]
In 0.15.0 the ability to search for a package and see if the remote package is outdated or not was added. This is great but have some drawbacks.

1) You can search for `compiler`, `arch`, `os` and `build_type` but there is no way to search for `compiler.version` and `compiler.libcxx` as far as I could find. This is going to be needed to make sure that we don't consider a package up-to-date if the compiler or libcxx changes.
2) I would really really like a way to just get the outdated version output in a better way to parse from a script. something like: `conan search -q "arch=xx and ...." zlib/1.2.8@plex/stable --outdated` would output `[packageid]=yes/no` or something similar instead of having to parse the output with a lot of text.

**Comment by lasote** [comment]
About 1) It works, you can query like that. Doesn't work for you?

`conan search Boost/1.60.0@lasote/stable -q "compiler.version=4.8"`

**Comment by tru** [comment]
Oh yeah it does. Sorry I must have been drunk when I tested it or something. I could not get it to work earlier. Consider that closed. Part two would still be really nice.

**Comment by memsharded** [comment]
Also to be implemented in https://github.com/conan-io/conan/issues/1895
