### ISSUE TITLE
[bug] During conan export-pkg, TXTGenerator.loads and cmake.patch_config_paths fail with system_libs

### ISSUE THREAD

**Issue by rddesmond** [conan-io/conan#6610]
I'm a huge fan of Conan, thank you for all the hard work!  I added a package as a dependency to my build and was working off of the latest documentation.  I didn't notice that it was my first inclusion of cpp_info.system_libs.

I found that this caused an issue where the package command was taking several hours to complete.  I determined that the problem was the confluence of several things.  The fundamental issue is that TXTGenerator cannot handle `cpp_info` keys with underscores (such as `system_libs`, `framework_paths`, and `build_modules`).  The commentary below shows some other places where exceptions would help with debugging.  It's a little complex because there are a lot of pieces that mesh together.

### Debugging `patch_config_paths`
I traced the extra time in packaging down to a call to `self.cmake.patch_config_paths()`, where it iterates through each dependencies and replaces the root path with a variable:

```cpp
for dep in self._conanfile.deps_cpp_info.deps:
    from_str = self._conanfile.deps_cpp_info[dep].rootpath
    dep_str = "${CONAN_%s_ROOT}" % dep.upper()
    ret = tools.replace_path_in_file(path, from_str, dep_str, strict=False, output=_null_out)
```

In the pdb debugger, I determined that `self._conanfile.deps_cpp_info.dep` had the following keys after I added by OpenJPEG dependency:

```cpp
(Pdb) p self._conanfile.deps_cpp_info.deps
odict_keys([..., 'OpenJPEG', ..., 'libs_OpenJPEG', ..., 'libs'])
```

Since `libs` and `libs_OpenJPEG` are false dependencies, they have no `rootpath`. This results in searching for an empty string and puts the replacement between every letter in every cmake file.

```cpp
tools.replace_path_in_file(path, '', '${CONAN_LIBS_ROOT}', strict=False, output=_null_out)
tools.replace_path_in_file(path, '', '${CONAN_LIBS_OPENJPEG_ROOT}', strict=False, output=_null_out)
```

### Debugging `TXTGenerator.loads`

When I dug deeper, I determined that the problem was in the generation and loading of the `conanbuildinfo.txt` for the main project, which was made during `conan install`.  The section for the `OpenJPEG` dependency is (some line breaks removed for brevity):

```
[includedirs_OpenJPEG]
/root/.conan/data/OpenJPEG/2.3.1/deepcore/third_party/package/3785743fd7969b5cbadf34ba604dba781192af94/include

[libdirs_OpenJPEG]
/root/.conan/data/OpenJPEG/2.3.1/deepcore/third_party/package/3785743fd7969b5cbadf34ba604dba781192af94/lib

[bindirs_OpenJPEG]
[resdirs_OpenJPEG]
[builddirs_OpenJPEG]
/root/.conan/data/OpenJPEG/2.3.1/deepcore/third_party/package/3785743fd7969b5cbadf34ba604dba781192af94/

[libs_OpenJPEG]
openjp2

[system_libs_OpenJPEG]
pthread
m

[defines_OpenJPEG]
OPJ_STATIC

[cppflags_OpenJPEG]
[cxxflags_OpenJPEG]
[cflags_OpenJPEG]
[sharedlinkflags_OpenJPEG]
[exelinkflags_OpenJPEG]
[sysroot_OpenJPEG]
[frameworks_OpenJPEG]
[framework_paths_OpenJPEG]

[rootpath_OpenJPEG]
/root/.conan/data/OpenJPEG/2.3.1/deepcore/third_party/package/3785743fd7969b5cbadf34ba604dba781192af94
```

This was generated by `conan install`, based on the package_info in `OpenJpeg` conanfile.py, which sets system_libs on linux.
```
class OpenJPEGConan(ConanFile):
    name = "OpenJPEG"
    version = "2.3.1"

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
        if not self.options.shared:
            self.cpp_info.defines.append('OPJ_STATIC')
        if self.settings.os == "Linux":
            self.cpp_info.system_libs = ["pthread", "m"]
```

When the conanbuildinfo.txt is read back in `TXTGenerator.loads()`, the dep and field are split in the `[...]` headers by there _first_ underscore, which breaks `system_libs` apart.

```
    @staticmethod
    def _loads_cpp_info(text):
        ...
        try:
                ...
                tokens = var_name.split("_", 1)
                field = tokens[0]
                dep = tokens[1] if len(tokens) == 2 else None
```

### Environment Details (include every applicable attribute)
  * Conan version: 1.22.1 (also tested with 1.21.1)
  * Python version: 3.5.2

### Steps to reproduce
 * Create a conan dependency which defines a cpp_info.system_libs dependency in it's `package_info()` method.
 * Create a master project which depends on it, and has `self.cmake.patch_config_paths()` in it's `package()` method.
 * Create a conanbuildinfo .txt with `conan install `/path/to/master`
 * Build the package by some means (or pretend that it's already built, it isn't important for this test).
 * Create a package with `conan export-pkg `/path/to/master ...`

(Note: the install and export-pkg are split, because just calling `conan create` won't read the "conanpackageinfo.txt")

It finishes after a long time and also corrupts all of the cmake files.

**Comment by jgsogo** [comment]
Hi, @rddesmond! First of all, thanks a lot for your kind words, and extra-thanks your detailed report, it makes it really easy to reproduce the issue.

There is indeed a bug in the implementation of the TXTGenerator.load related with `system_libs` or any other variable with `_` in it. And the fix is a little bit harder to implement because requirement names can include underscores in them too.

So we have, for example:

```ini
            [system_libs]
            main
            
            [system_libs_requirement]
            requirement

            [system_libs_requirement_other]
            requirement_other
```

This has to be fixed first, then we can check that `patch_config_paths` is fixed too.

**Comment by jgsogo** [comment]
the issue related to `frameworks_paths` is already fixed here: https://github.com/conan-io/conan/pull/6533 (probably not intentional as it says nothing related to the underscore).
