### ISSUE TITLE
[suggestion] Allow multiple pattern argument of tools.unzip()

### ISSUE THREAD

**Issue by tt4g** [conan-io/conan#6611]
I encountered an issue where expanding the archive file failed when `tools.unzip()` was called via `tools.get()`.

see this pull request https://github.com/conan-io/conan-center-index/pull/1011#issuecomment-593324993.

I get the following error:

```
ERROR: fruit/3.4.0: Error in source() method, line 59
	tools.get(**self.conan_data["sources"][self.version])
	OSError: [Errno 22] Invalid argument: '.\\fruit-3.4.0\\extras\\bazel_root\\third_party\\fruit\\build'
```

Since the archive file contained files `fruit-3.4.0/extras/bazel_root/third_party/fruit/build` and `fruit-3.4.0/extras/bazel_root/third_party/fruit/BUILD`, it seems that the file name conflicts on a case-insensitive file system and the extraction failed.

I looked for an API to exclude some files when extracting files, but couldn't find them in conans.
I circumvented the problem by adding a function to extract only files from the archive that do not match the pattern.
This is almost a copy of `tools.unzip()`.

If can specify multiple patterns in the `pattern` argument of `tools.unzip() `, we can exclude specific files from the archive.

Can this feature be added?

Example:

```
foo
├─config
│  ├─build   
│  ├─BUILD
│  └─configure
│
├──src
└──tests
```

```python
# Extract only config/configure.
tools.unzip("foo.tar.gz", pattern=["src/*", "config/configure"]);
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by tt4g** [comment]
This case is very rare.

**Comment by memsharded** [comment]
Hi @tt4g 

I am not sure if I understood, did you say that ``tools.unzip("foo.tar.gz", pattern=["src/*", "config/configure"])`` is good for you? Then, you could do:

```python
def source(self):
     tools.download(**self.conan_data["sources"][self.version])
     tools.unzip("foo.tar.gz", pattern=["src/*", "config/configure"])
```

In any case, I think this is something that should also be reported in the origin, having such a zipped file with both "build" and "BUILD" folders is basically broken by definition (at least in Windows), and it seems wrong to me, I would probably do a copy myself and fix it (and host it in my own generic repo) if the upstream is not fixed.

Please let me know if this makes sense.

**Comment by tt4g** [comment]
Yes, your idea makes sense.

I should report the archive problem.

Thank you for advice me.

**Comment by memsharded** [comment]
Thanks for the feedback and following up!
