### ISSUE TITLE
[bug] Content-Type Header "content-type: application/json; charset=utf-8" is not accepted

### ISSUE THREAD

**Issue by SeWieland** [conan-io/conan#6613]
This bug happened to me while trying to search for packages on a Artifactory remote repository.
The issue is linked to #4317 (closes #3985)

### Environment Details
  * Conan version: 1.22.2
  * Python version: 3.7.3
  * Artifactory version: 6.17.0

### Steps to reproduce
1. Set up a working example-remote repository using standard settings
1. Add example-remote in conan
1. Search for any package on this remote

### Logs
ERROR: {
  "results" : [ ]
}

Response from remote is not json, but 'application/json; charset=utf-8'. [Remote: example-remote]

**Comment by memsharded** [comment]
Hi @SeWieland 

I am trying to reproduce this issue, but seems to be working fine here. I am not sure what could be happening in your side, some quick questions:

- Search is with ``conan search "*" -r=artifactory``?
- Is this something that worked in the past, and now is broken?
- Do you have your Artifactory behind a proxy or some configuration that could be failing?
- Which Artifactory edition?
- Which operating system in your client?
- Can you please enable a trace file for the API calls? This is setting an environment variable ``CONAN_TRACE_FILE`` pointing to a file absolute path, and calling the ``conan search`` again.

Thanks for the feedback!

**Comment by SeWieland** [comment]
Thanks for looking into it!
The problem was resolved (with a workaround): We are running the Artifactory instance behind Nginx. So we can just modify the Content-Type Header accordingly for the location in question.

Some info you requested:
  * `conan search "*" -r artifactory` produces this error (does not matter as the answer is not evaluated)
  * No, this is a inital setup
  * Yes, proxy + Nginx as reverse proxy for the artifactory (However, other remotes work)
  * Professional
  * Windows

I have no trace file, as the problem was already resolved by some quick admins...

Neverthless I think the "charset=utf-8" addition **must not break the functionality**.

I think that https://github.com/conan-io/conan/blob/a746e364000b6be09717bbaa5b331cdf4655bb12/conans/client/rest/rest_client_common.py#L194 is the problem here.

**Comment by memsharded** [comment]
Hi!

Having a look to the code, so that code is in a ``get_json()`` function, that expects by the Conan protocol to receive a json object. Not receiving a json object is a failure. Notice that the lines after that one are:

```python
        try:  # This can fail, if some proxy returns 200 and an html message
            result = json.loads(content)
        except Exception:
            raise ConanException("Remote responded with broken json: %s" % content)
```

So even if we accept there ``charset=utf-8``, then, if it is not json, it will raise anyway. Besides, the servers are already returning ``'application/json'``, so it works, I am not sure where are you getting that ``utf-8`` from? What am I missing here? Thanks!

**Comment by SeWieland** [comment]
Yes you are absolutely right!
As I already mentionend, we resolved the problem by changing the the header back to `'application/json'` -> This worked, so the objects are valid json.

I currently do not know where the `'charset=utf-8'` addition came from, however it is a pretty common and (as far as I know) **valid** additon, even if redundant and not needed.

**Comment by memsharded** [comment]
> I currently do not know where the 'charset=utf-8' addition came from, however it is a pretty common and (as far as I know) valid additon, even if redundant and not needed.

I have been checking the Conan source code, and up to my knowledge, Conan servers are not adding anywhere the ``charset=utf-8`` header. 

Yes, it would conceptually be a valid addition, and the client side should be able to parse it correctly, if that is what receives from the servers. But the thing is that servers could actually decide to define ``charset=utf-16`` (yes, highly improbable that we would do that 😄 ). So accepting ``charset=utf-8`` right now doesn't seem the right thing to do unless it was defined in the servers.

Let me know what you think, please. If agreed, that means we could close this issue, as there is no action to be taken. Thanks for your feedback!

**Comment by SeWieland** [comment]
Yes, I'm closing this issue again. It was most likely caused by some custom reverse proxy settings.
I was not aware that this is not the standard behaviour of the current Artifactory release and thus a bit confused by the funny error message 😄 

Thanks anyway!
