### ISSUE TITLE
Depending on the toolchain creates some strange problems

### ISSUE THREAD

**Issue by tru** [conan-io/conan#662]
As described before we build our compilers as a conan package and we download msys as well. Unfortunately this leads to the toolchain being brought forward to things that depend on that. We can use the `private` keyword, but that doesn't seem to do what I want: i.e. installing the toolchain for a package that doesn't explicitly depends on it. It also created a lot of imports (duplicate versions of the toolchain) when several packages depend on it. This only seems to happen when it's marked as private.

I think it was floated before that we could have some kind of "tool_requirement" or "build_requirement" but it was put on ice when I got informed about `private`. But this doesn't fully seem to solve my problems.

**Comment by memsharded** [comment]
Closing as inactive
