### ISSUE TITLE
[bug] Conan does not find zlib library

### ISSUE THREAD

**Issue by nguoithichkhampha** [conan-io/conan#6621]
* Operating System+version: MacOS 10.15
  * Compiler+version: clang 11.0
  * Conan version: 1.22.2
  * Python version: 3.8

I have a zlib conan package library and another project depends on it.
when generate with cmake generator, seems conan does not list it as an dependency

[includedirs]
/Users/Emotiv/.conan/data/brotli/1.0.7/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/include
/Users/Emotiv/.conan/data/double-conversion/3.1.4/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/include
/Users/Emotiv/.conan/data/rapidjson/2648a732/common/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
/Users/Emotiv/.conan/data/snappy/1.1.7/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/include
/Users/Emotiv/.conan/data/thrift/0.12.0/ios/stable/package/d0245508ee1a5499a84a582dba63db32ce2078b0/include
/Users/Emotiv/.conan/data/openssl/1.1.1b/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/include
/Users/Emotiv/.conan/data/zlib/1.2.11/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/include
/Users/Emotiv/.conan/data/boost/1.69.0/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/include

[libdirs]
/Users/Emotiv/.conan/data/brotli/1.0.7/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/lib
/Users/Emotiv/.conan/data/double-conversion/3.1.4/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/lib
/Users/Emotiv/.conan/data/snappy/1.1.7/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/lib
/Users/Emotiv/.conan/data/thrift/0.12.0/ios/stable/package/d0245508ee1a5499a84a582dba63db32ce2078b0/lib
/Users/Emotiv/.conan/data/openssl/1.1.1b/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/lib
/Users/Emotiv/.conan/data/zlib/1.2.11/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/lib
/Users/Emotiv/.conan/data/boost/1.69.0/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/lib

[bindirs]
/Users/Emotiv/.conan/data/thrift/0.12.0/ios/stable/package/d0245508ee1a5499a84a582dba63db32ce2078b0/bin

[resdirs]

[builddirs]
/Users/Emotiv/.conan/data/brotli/1.0.7/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/
/Users/Emotiv/.conan/data/double-conversion/3.1.4/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/
/Users/Emotiv/.conan/data/rapidjson/2648a732/common/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/
/Users/Emotiv/.conan/data/snappy/1.1.7/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/
/Users/Emotiv/.conan/data/thrift/0.12.0/ios/stable/package/d0245508ee1a5499a84a582dba63db32ce2078b0/
/Users/Emotiv/.conan/data/openssl/1.1.1b/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/
/Users/Emotiv/.conan/data/zlib/1.2.11/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/
/Users/Emotiv/.conan/data/boost/1.69.0/ios/stable/package/b8447bd26ae00043fa76eb58e89e4c5f803a660d/

[libs]
brotlicommon-static
brotlidec-static
brotlienc-static
double-conversion
snappy
thrift
thriftz
crypto
ssl
boost_filesystem
boost_regex
boost_system

**Comment by memsharded** [comment]
Hi @nguoithichkhampha 

We would need to see the ``conanfile.py`` of the consumer project, and a way to reproduce this. With the current information it is not possible to know what is happening. Thanks!

**Comment by nguoithichkhampha** [comment]
yes, I attached the conan file of project and file to build zlib package also.
[conanfile.py](https://drive.google.com/open?id=1eRjamDZx52W9Rm-ambDMB7Ok4U7kOzfX)

**Comment by nguoithichkhampha** [comment]
maybe the lib name is too short ? only symbol "z". I tried to set library name in conanfile.py and conan reported invalid name.

**Comment by memsharded** [comment]
Quick feeback. It seems that you are using Conan in a non usual way:

- Do not hardcode the configuration in ``build()``. Not like this:

```python
       cmake.definitions["CMAKE_SYSTEM_NAME"] = "iOS"
        cmake.definitions["CMAKE_OSX_ARCHITECTURES"] = "arm64"
        cmake.definitions["CMAKE_OSX_DEPLOYMENT_TARGET"] = "11.0"
```
You should probably have something like this (not exactly, just a rough idea):
```python
       cmake.definitions["CMAKE_SYSTEM_NAME"] = self.settings.os
        cmake.definitions["CMAKE_OSX_ARCHITECTURES"] = self.settings.arch
        cmake.definitions["CMAKE_OSX_DEPLOYMENT_TARGET"] = self.settings.os.version
```
Or maybe using conditionals: ``if self.settings.os == "iOS": ``
The idea is that the same recipe works for all different platforms and systems, not just for one.

In the same line, you do not name your packages like ``zlib/1.2.11@ios/stable``. The user name is for your user name (company name, team name), but not for the platform. Exactly the same recipe with the same reference will be valid for different OS, platforms, Android, Windows... etc. Conan will manage internally the different binaries correctly for you.

Regarding your error, yes, "z" only is not a valid name. You need to have at least 2 letters. Still what you are providing is not enough for reproduce. If you could send just 2 very simple files, with the exact commands you are using to reproduce the issue, that would be great. Thanks!

**Comment by nguoithichkhampha** [comment]
@memsharded thanks for your feedback, I just tried with conan a few weeks ago and still learn to know its feature.
for your question I'm not clear about it. just set my project depends on the zlib library and cmake generated file from conan does not set it.
`conan install . --install-folder=test -pr my_custome_profile`

[conanbuildinfo.cmake](https://drive.google.com/file/d/1su9L2oiziJsIhSXPfyZi7aKgga6cCQ5d/view?usp=sharing)
you can see the different of openssl library and zlib
set(CONAN_LIBS_ZLIB )
set(CONAN_PKG_LIBS_ZLIB )
and 
set(CONAN_LIBS_OPENSSL crypto ssl)
set(CONAN_PKG_LIBS_OPENSSL crypto ssl)

**Comment by danimtb** [comment]
@nguoithichkhampha Having a look at the attached conanfiles, I see you are creating your own recipe for zlib. However, in the zlib recipe you have not declared the information for consumers (you don't have a package_info() method).

You should add something like:

```
def package_info(self):
    self.cpp_info.libs = ["zlib"]
```

That way, you should see that the information is later filled by the generators and your conanbuildinfo.cmake file should have the `set(CONAN_LIBS_ZLIB zlib)` as expected.

Please give it a go and read more information about the package_id() method here https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-info

**Comment by memsharded** [comment]
Also, I'd recommend working, at least starting from the recipes in https://github.com/conan-io/conan-center-index, they are the recipes that are used to populate https://conan.io/center/

**Comment by nguoithichkhampha** [comment]
ah, I see. I missed this function in conanfile.py when build zlib library. thanks for your support

**Comment by danimtb** [comment]
@nguoithichkhampha no problem. Please feel free to write to us if you have any other question and we will be happy to help 😄
