### ISSUE TITLE
tools.vs_installation_path doesn't find VS2017 installation, while tools.vswhere does

### ISSUE THREAD

**Issue by ParvusM** [conan-io/conan#6623]
I'm new to Conan and I'm trying to create my first package with Conan version 1.22.2 and VS2017.

I'm getting the error: ConanException: VS non-existing installation: Visual Studio 15

After searching a bit, I see the error in: https://github.com/conan-io/conan/blob/develop/conans/client/tools/win.py when vs_installation_path can't find the path.

Inside the vs_installation_path function I see:
`all_products = vswhere(products=["*"])`

Now I debugged the simple python script below and I saw that `tools.vswhere(all_=True)` is correctly finding the path for my VS2017 professional installation, but `tools.vswhere(products=["*"])` is returning an empty array.

Am I doing something wrong here, or is this an actual bug in Conan? 

As a workaround, I locally changed the line `all_products = vswhere(products=["*"])` into `all_products = vswhere(all_=True)` and now it works for me.

`import os

from conans import tools

def test():
    vsWhereAll = tools.vswhere(all_=True)
    vsWhereAsterisk = tools.vswhere(products=["*"])
    vs_path14 = tools.vs_comntools("14")
    vs_path15 = tools.vs_comntools("15")
    vs_path_2017 = tools.vs_installation_path("15", preference=["Community", "BuildTools", "Professional", "Enterprise"])
    latestVS = tools.latest_vs_version_installed()
    #what = os.environ.get("VisualStudioVersion")
    print("hello")

test()`

**Comment by danimtb** [comment]
Hi @ParvusM,

The `tools.vswhere()` is just a wrapper over the `vswhere` tool, an the `all` parameter is used to locate all kind of visual installation _even not working ones_ (see [all_](https://docs.conan.io/en/latest/reference/tools.html#tools-vswhere) description).

In your case, a normal `vswhere` call should be able to locate the visual 15 installation. So please make sure you have a fully working installation.

It sounds quite weird, so I am not sure how you could debug this. Maybe the best way is just executing vswhere externally and verifying the results. In my case, I get the following output:

```
$ vswhere
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 2811b7fd
installDate: 10/16/2018 11:26:40 AM
installationName: VisualStudio/15.8.7+28010.2046
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
installationVersion: 15.8.28010.2046
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
isPrerelease: 0
displayName: Visual Studio Community 2017
description: Free, fully-featured IDE for students, open-source and individual developers
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.8.7
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2018-10-16T09:26:40.0660665Z
catalog_buildBranch: d15.8
catalog_buildVersion: 15.8.28010.2046
catalog_id: VisualStudio/15.8.7+28010.2046
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.8.7
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 7
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.8.7+28010.2046
catalog_requiredEngineVersion: 1.17.1230.42073
properties_campaignId: 7141385.1539681808
properties_channelManifestId: VisualStudio.15.Release/15.8.7+28010.2046
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
```

**Comment by ParvusM** [comment]
@danimtb Thanks for the simple suggestion of running vswhere externally.
I've tried that and it shows that something fishy is going on with my vswhere. Running it with no arguments only printed:
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008]
Copyright (C) Microsoft Corporation. All rights reserved.

Running it with the -all param did find my vs2017 version. I've searched for vswhere not working and it seems more people have had that problem. I've send them the logs to try to find out what could have been the issue with my vswhere. After updating vs2017, the vswhere is now running correctly again.

So it isn't a Conan bug and I'll close this issue. :)

**Comment by danimtb** [comment]
@ParvusM glad you figured that out!! Indeed, it was really weird that vswhere was not locating the installation by default and you have to use the -all parameter.

Thanks a lot for your response and do not hesitate to make any other question while you are learning about Conan 😄
