### ISSUE TITLE
[bug] deploy generator doesn't preserve symlinks

### ISSUE THREAD

**Issue by michaelplatingsarm** [conan-io/conan#6628]
The [deploy generator](https://docs.conan.io/en/latest/reference/generators/deploy.html) uses [shutil.copy](https://docs.python.org/3/library/shutil.html#shutil.copy) to copy files. By default, shutil.copy follows symlinks rather than preserving them.
This means that e.g. libstdc++.so is deployed as a copy of libstdc++.so.6 rather than a symlink to it.
Since Python 3.3 shutil.copy can take a follow_symlinks argument. Therefore the fix could be:
```diff
diff --git a/conans/client/generators/deploy.py b/conans/client/generators/deploy.py
index 44bcf74..5aa2640 100644
--- a/conans/client/generators/deploy.py
+++ b/conans/client/generators/deploy.py
@@ -41,6 +41,6 @@ class DeployGenerator(Generator):
                                        os.path.relpath(root, rootpath), f)
                     dst = os.path.normpath(dst)
                     mkdir(os.path.dirname(dst))
-                    shutil.copy(src, dst)
+                    shutil.copy(src, dst, follow_symlinks=False)
                     copied_files.append(dst)
         return self.deploy_manifest_content(copied_files)
```
I'd submit a pull request but getting my head around the tests was taking more time than I can spare, sorry.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16.04
  * Conan version: 1.21.2
  * Python version: 3.5.2

**Comment by jgsogo** [comment]
Hi, @michaelplatingsarm 

We would really appreciate it if you can submit the PR. A good place for the test would be the file `conans/test/functional/generators/deploy_test.py` (you can use `os.symlink` to create symlinks in Python).

Right now the test suite runs also for Python 2.7 so we need a fallback. The best thing would be to recreate the symlink for Python 2.7 (detect it is a symlink, know where the target file is being copied and create the symlink to it), but it'd be ok if, as a first step, pythong2.7 keeps the previous behavior and we get the bugfix for Python 3.

Thanks!

**Comment by memsharded** [comment]
> Right now the test suite runs also for Python 2.7 so we need a fallback. The best thing would be to recreate the symlink for Python 2.7 (detect it is a symlink, know where the target file is being copied and create the symlink to it), but it'd be ok if, as a first step, pythong2.7 keeps the previous behavior and we get the bugfix for Python 3.

Yeah,  lets keep it simple, lets fix the bug for Python 3 only
