### ISSUE TITLE
package development flow command not compatible with create command (due to possible different working directories)

### ISSUE THREAD

**Issue by a4z** [conan-io/conan#6629]
### Environment Details (include every applicable attribute)
  * Operating System+version: Any
  * Compiler+version: Any
  * Conan version: 1.20 and above
  * Python version: 3.7.6

### Steps to reproduce (Include if Applicable)

Use the package development flow for developing a package.
https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html

if you do something like this
```
 conan source ${pkg} --source-folder ${source_folder}        
 conan install ${pkg} --install-folder ${build_folder} --profile ${profile}
 conan build ${pkg} -i -c -b --build-folder ${build_folder}  --source-folder ${source_folder}
```

you need to `cd` for the `build` and `package` method into the `self.source_folder`
(interestingly, not for downloading/ getting the source, in the `source` method.)

recipes that do not do that, basically all in the index center, will not work using this way.
This is a big pain when using the development flow for developing packages for the index center

this can be verified by adding a `with tools.chdir(self.source_folder):` into the build and the package method of recipes form the index center, and all the sudden they will also work with the developer flow.

for example, please have a look at this discussion
https://github.com/conan-io/conan-center-index/pull/1048#discussion_r388312230

and this is a recipe that does not need to change the directory in the build and package method

Possible solutions:

* make the working directory for the build method and the package method to the self.source_directory

or

* remove the package development flow from the manual, and maybe also the commands, since it will lead to frustration 

there might be of course some other solution, but I can not think about that right now

**Comment by uilianries** [comment]
@a4z please take a look: https://github.com/conan-io/conan/issues/5165

**Comment by a4z** [comment]
I guess, I can close his one, since a solution for #5165 would also solve this one?

**Comment by jgsogo** [comment]
I'm closing this one then. We know we need to work in the _local development flow_ 👷 

Thanks!
