### ISSUE TITLE
[bug] conan remove leaves index.json file

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#6630]
When I issue a `conan remove` command to erase a given library from my own remotes, it removes all the packages but it leaves behind a file called `index.json`.

I tried this with Artifactory Community Edition for C/C++ 6.15.0 rev 61500900, which is what I'm using for development but the same happens if you use the regular version of Artifactory (I don't know how to call it, the PRO version?).

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16.04
  * Compiler+version: -
  * Conan version: 1.21.1
  * Python version: 2.7.12 / 3.5.2

### Steps to reproduce (Include if Applicable)
- Upload a bunch of artifacts to a remote, i.e. gtest.
- Issue a conan remove gtest -r some-remote
- Go to your artifactory repo and you'll see that the gtest packages are gone but you can still see that `index.json` is still there on `repo/user/gtest/libversion/channel/index.json`. 

--

**Comment by memsharded** [comment]
Reproduced it with Artifactory 6.11.

Tried with Artifactory 6.16, it works. 

For previous versions, it seems it is not a real operational problem, as the actual contents of the file (the existing revisions) are cleared:
```
{
  "reference" : "openssl/1.0.2t@_/_",
  "revisions" : [ ]
}
```

I would recommend upgrading Artifactory to 6.16 at least. Thanks for reporting! (I think we can close the issue, as this fix should be enough, and nothing to do on Conan client side).
