### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by crimsonalucard** [conan-io/conan#6639]
For the following code:

```
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <stdio.h>

int main() {
    // start GL context and O/S window using the GLFW helper library
    if (!glfwInit()) {
        fprintf(stderr, "ERROR: could not start GLFW3\n");
        return 1;
    }
    // uncomment these lines if on Apple OS X
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    GLFWwindow *window = glfwCreateWindow(640, 480, "Hello Triangle", NULL, NULL);
    if (!window) {
        fprintf(stderr, "ERROR: could not open window with GLFW3\n");
        glfwTerminate();
        return 1;
    }
    glfwMakeContextCurrent(window);
    // start GLEW extension handler
    glewExperimental = GL_TRUE;
    glewInit();
    // get version info
    const GLubyte *renderer = glGetString(GL_RENDERER);
    const GLubyte *version = glGetString(GL_VERSION);
    printf("Renderer: %s\n", renderer);
    printf("OpenGL version supported %s\n", version);
    // tell GL to only draw onto a pixel if the shape is closer to the viewer
    glEnable(GL_DEPTH_TEST); // enable depth-testing
    glDepthFunc(GL_LESS); // depth-testing interprets a smaller value as "closer"
    /* OTHER STUFF GOES HERE NEXT */
    // close GL context and any other GLFW resources
    glfwTerminate();
    return 0;
}
```

And the following conanfile:

```
[requires]
glew/2.1.0@bincrafters/stable
glfw/3.3@bincrafters/stable

[generators]
cmake
```

And following the tutorial for running conan on CLion, when I debug it executes the following command:

`"/Users/brianyeh/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/192.7142.39/CLion.app/Contents/bin/cmake/mac/bin/cmake" --build /Users/brianyeh/CLionProjects/glfw_template/cmake-build-debug --target glfw_template -- -j 4`

which generates the following error:

```
Scanning dependencies of target glfw_template
[ 50%] Building CXX object CMakeFiles/glfw_template.dir/main.cpp.o
[100%] Linking CXX executable bin/glfw_template
Undefined symbols for architecture x86_64:
  "_glewExperimental", referenced from:
      _main in main.cpp.o
  "_glewInit", referenced from:
      _main in main.cpp.o
  "_glfwCreateWindow", referenced from:
      _main in main.cpp.o
  "_glfwInit", referenced from:
      _main in main.cpp.o
  "_glfwMakeContextCurrent", referenced from:
      _main in main.cpp.o
  "_glfwTerminate", referenced from:
      _main in main.cpp.o
  "_glfwWindowHint", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/glfw_template] Error 1
make[2]: *** [CMakeFiles/glfw_template.dir/all] Error 2
make[1]: *** [CMakeFiles/glfw_template.dir/rule] Error 2
make: *** [glfw_template] Error 2
```

Am I doing something wrong or is this an issue with conan or the libraries?  Also I'm running this on OSX.

**Comment by Minimonium** [comment]
What's your Conan profile? It could be that you've installed binaries with the wrong architecture than you want.

**Comment by crimsonalucard** [comment]
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by Minimonium** [comment]
It's a linking issue, profile seems alright. Have you tried the https://github.com/lasote/clion-conan-consumer?
I also noticed that the tutorial doesn't mention this line: https://github.com/lasote/clion-conan-consumer/blob/master/CMakeLists.txt#L13
Please make sure you have it in your CMakeLists.

**Comment by crimsonalucard** [comment]
https://github.com/lasote/clion-conan-consumer/blob/master/CMakeLists.txt#L13

That line was it. If you could spare the time, could you explain what it
does and why it worked? I replaced the "example_png" with project name.

Also I wanted to say thank you for helping me. I really appreciate it.

**Comment by Minimonium** [comment]
You're welcome! 

When you call the `conan_basic_setup()` in CMake it pulls the information about dependencies into CMake variables (there are alternative integrations defined in the documentation too). 

Conan follows modern CMake guidelines so it doesn't pollute the global linking list as it could do with a `link_libraries`. It means that to actually link your dependencies you need to specify them with `target_link_libraries(your_target ...)` for each of your targets. 

So in this tutorial - the basic CMake integration is suggested: https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_generator.html#global-variables-approach which requires to use the `${CONAN_LIBS}` variable which is a list of your dependencies.

**Comment by jgsogo** [comment]
Thanks a lot, @Minimonium, for attending this issue ❤️ 

I think it's been resolved, but feel free to open it again if needed.

Thanks!
