### ISSUE TITLE
Documentation for conan_server configuration is a bit misleading.

### ISSUE THREAD

**Issue by tru** [conan-io/conan#664]
We just productized our conan server and we ran into some strange wording in the documentation that made the configuration progress much more complicated.

Our setup is nginx->gunicorn->conan_server. The biggest problem we ran into was that the explanation of `host_name` was not obvious. That it needs to match whatever the client is connecting to. The second problem was that the SSL directive was marked as deprecated but we needed it to get it to work.

I think that the most frustrating thing was that the client's error diagnostic just came down to "error uploading" and nothing extra. I think printing the URL it tried for uploading should have been logged or something similar like that. I am hoping that this can be improved.

**Comment by memsharded** [comment]
The request about the URL printing is basically the same as https://github.com/conan-io/conan/issues/645. 
As the docs issue is already addressed in https://github.com/conan-io/docs/issues/92 in the docs repo, I suggest closing this one, and following conversation about the upload error diagnostics in #645.
