### ISSUE TITLE
cmake_paths generator creates variables which are inconsistent with cmake.patch_config_paths 

### ISSUE THREAD

**Issue by peter-lehner** [conan-io/conan#6643]
Conan version: 1.22.2

The code in the cmake_paths generator generates the "CONAN_{}_ROOT" variable based on dep_cpp_info.get_name("cmake_paths"):

https://github.com/conan-io/conan/blob/4e3df5fc30bdb63936ab8f196ab8fb56068c511a/conans/client/generators/cmake_paths.py#L17-L19

which I can influence in my concrete example with the self.cpp_info.name variable as specified in:
https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=cpp_info#cpp-info)

This change in name seems not to be respected by the patch_config_paths function in the cmake module:

https://github.com/conan-io/conan/blob/048da960470217b51d28dd876d724ecca10dfd81/conans/client/build/cmake.py#L396

as it constructs the "CONAN_{}_ROOT" variable with simply the name attribute of the conanfile.

I think for effective use of the cmake_paths generator and the cmake.patch_config_paths functions, the exported variables should result in the same name, no?

**Comment by peter-lehner** [comment]
From what I can understand the same issue is probably also true for the dependency paths, patched in patch_config_paths:
https://github.com/conan-io/conan/blob/048da960470217b51d28dd876d724ecca10dfd81/conans/client/build/cmake.py#L413-L415

**Comment by memsharded** [comment]
There is one problem here. Different generators can have different names, to generate different targets  names, etc. So by definition, it is impossible to apply just 1 replacement in the package itself that would be valid for all generators, and that is the reason why this ``patch_config_paths`` the best it can do is just use the conanfile name (well, it could use the ``info.name``, but in no case it could apply the generator-specific ones, that are the ones that are recommended right now).

The underlying issue is having in the packages cmake files that contain absolute paths. ``patch_config_paths`` just tries to be a workaround, but that will always be just a workaround, and will have issues like this one. Not sure what else could be done here.

**Comment by peter-lehner** [comment]
> There is one problem here. Different generators can have different names, to generate different targets names, etc. So by definition, it is impossible to apply just 1 replacement in the package itself that would be valid for all generators, and that is the reason why this `patch_config_paths` the best it can do is just use the conanfile name (well, it could use the `info.name`, but in no case it could apply the generator-specific ones, that are the ones that are recommended right now).

Yes, I think you are correct: when the user specifies a specific name for a generator, he can't expect `patch_config_paths` to work. But I think it would be nice to support the `cpp_info.name` as it is considered by all 'official' cmake generators, if I'm not mistaken?

> The underlying issue is having in the packages cmake files that contain absolute paths. `patch_config_paths` just tries to be a workaround, but that will always be just a workaround, and will have issues like this one. Not sure what else could be done here.

Yes, I agree. Sadly there are many packages with absolute paths in their cmake configs, and I really appreciate the `patch_config_paths` functionality.

**Comment by memsharded** [comment]
Ok, lets do that, lets use the ``cpp_info.name`` if existing, I think that would be a bit more consistent.
Should be a relatively easy feature, would you like to try to contribute it?

**Comment by memsharded** [comment]
This ticket was using the old generators (legacy in 1.X, removed in 2.0), that have been superseded some time ago by new ones. Closing as outdated, please check the new ones and don't hesitate to open new tickets as necessary for any further question.
