### ISSUE TITLE
[question] What's the preferred way of passing configuration header files via conan profiles to individual conan packages

### ISSUE THREAD

**Issue by jegabe** [conan-io/conan#6646]
I'm working at a company where we are starting a new software platform targeted to linux devices as well as FreeRTOS (and probably other RTOS) devices. In the field of RTOS development, it is quite common that a device project has some configuration switches, like the infamous FreeRTOSConfig.h file (https://www.freertos.org/a00110.html).

We want that the user of the software platform can customize that switches, so it would be a good thing if the config header file is logically located near the device code. Now, when we want to package the FreeRTOS scheduler into a conan package, we want to pass/inject the configuration switches to the FreeRTOS conan package.

The current way of doing that is packaging the configuration file, for example FreeRTOSConfig.h, into a separate conan package. Since we are cross-building for the target platform, we have conan profiles that describe the compiler switches and so forth. Each user of the platform can create its own profile file. At this point, we add environment variables that link to the conan package that contains the switches:

MyDeviceProfile.profile:

[settings]
os_build=Windows
os=Generic
arch=armv7e
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Debug
[build_requires]
myToolChain/0.1.0@someUser/someChannel
[env]
CONFIG_HEADER_CONAN_PACKAGE_NAME=myConfigHeaderPackageName
CONFIG_HEADER_CONAN_PACKAGE_PATH=[*]@someUser/someChannel

The two environment variables CONFIG_HEADER_CONAN_PACKAGE_NAME and CONFIG_HEADER_CONAN_PACKAGE_PATH describe what package contains the compiler switches.

Now, in the conanfile.py for the FreeRTOS scheduler, we query the environment variable and if it is set, we add the package as extra dependency:

from conans import ConanFile, CMake, tools

class FreeRTOS(ConanFile):
    name = "freertos"
    version = "0.1.0"
    license = ""
    url = ""
    description = ""
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake", "virtualenv", "cmake_toolchain"
    exports_sources = "src*", "CMakeLists.txt"
    no_copy_source = True

    # Pull-in the configuration headers conan file as additional requirement:
    def requirements(self):
        config_header_package_name = tools.get_env(env_key="CONFIG_HEADER_CONAN_PACKAGE_NAME", default="")
        config_header_package_path = tools.get_env(env_key="CONFIG_HEADER_CONAN_PACKAGE_PATH", default="")
        if (config_header_package_name != ""): # When a config header is set by the conan profile in use:
            self.requires("%s/%s" % (config_header_package_name, config_header_package_path))

That way, when the profile sets the environment variables, extra requirements are pulled-in by the conan file so the build process of the package can access the include path to the package containing the config switches and the C/C++ sources can #include the files as needed. The switches are decoupled from the FreeRTOS package and each new device using the FreeRTOS package can set its custom switches, resulting in a different output for the FreeRTOS package, which is nice.

We tried to use the [option] field of the profile to set the package name, but that lead to problems (See issue https://github.com/conan-io/conan/issues/6644).

This approach of adding additional dependencies works for us now, but we'd like to know if this is the way to go or if there are other, better alternatives.

**Comment by memsharded** [comment]
Hi @jegabe 

Thanks for your detailed description of the issue. 
It seems a complicated one. At first sight what I would try is to have a mapping between the settings and those config headers. What is the logic between them? Does it makes sense to add some setting maybe to complete the model? The thing is that it is clear that such requirement has a high potential to affect the binaries and the binaries compatibility. While the requirements can also modify the package ID and the binary compatibility, it is way more direct and intuitive to do so using settings.

If possible, I would aim to define the ``requires()`` to that package as a pure function of the settings. Does this make sense? would it be possible?

**Comment by jegabe** [comment]
Hi @memsharded, thanks for the quick response. I totally agree with you that this would be the cleanest thing to do. But the possible number of combination of switches in a header file is so big that it would be really a challenge to generate conan settings for them.

One thing we already thought of was kind of similar what you suggested: Introducing a kind of identifier for the device type as a new setting and depending on the setting, require the correct conan package for the header files. But this would mean that the new setting needs to be deployed into settings.yml and not only the setting but also all possible values for the settings. When a new device would get started development, the setting.yml would need to be updated for each developer machine.

Plus FreeRTOS is not the only package that needs configuration headers, it is also lwip and maybe others as well that complicate that even further. Best of course would be if the RTOS world would go away from the config header file hell...

**Comment by jegabe** [comment]
Hi @memsharded, what I forgot to mention is that we are aware that this affects binary compatibility. That's why we were thinking of a model where the combination of switches is encoded into a unique conan package name and version that's related to the device project. That way, different binaries are built for different settings and they should be compatible

**Comment by memsharded** [comment]
> Hi @memsharded, what I forgot to mention is that we are aware that this affects binary compatibility. That's why we were thinking of a model where the combination of switches is encoded into a unique conan package name and version that's related to the device project. That way, different binaries are built for different settings and they should be compatible

That was my thought. If the combination of switches can be summarized in one unique conan package name and version, you can probably use that as a setting (or a subsetting of the FreeRTOS ``os`` setting?) as well, and avoid using the environment variables. Settings are more thoroughly checked and map more directly to package ID.

**Comment by jasal82** [comment]
We already thought about encoding the package name as value of an option. Using a setting is another possibility. However, it feels very unnatural. Maybe this is better modeled as another type of requirements that can be injected on profile level?

**Comment by jegabe** [comment]
Hi @memsharded, thanks, that's a good idea. Then it would be also nice to have some "ANY" wildcard for settings, as it is already available for the options, so we wouldn't need to add each new combination to settings.yml. Do you think that would be meaningful? Or is that already possible?

**Comment by jegabe** [comment]
@jasal82: That would also be nice. It's really something related to config-header intensive projects like small RTOS devices where everything is linked into one firmware image and everything depends on compile-time switches.

**Comment by memsharded** [comment]
> We already thought about encoding the package name as value of an option. Using a setting is another possibility. However, it feels very unnatural. 

Options would be a bit worse, because they need to be defined in each package. While, depending on the use case, of course, it seems to me that a mapping to a subsetting could be actually quite intuitive and easy to understand. There are different FreeRTOSConfig.h files, because we are targeting different platforms, each one will have its own binaries, then it makes sense that it is setting?

Adding another type of requirements is a bit scary for me. Right now, the dependency graph model is probably the biggest challenge in Conan. And we only have "requires" and "build-requires" (and "private", but that is not very recommended). I am very hesitant to add new types of requirements until we are able to improve the graph model with what we already know for sure. Then I would recommend the settings approach if possible, because that tries to keep as decoupled as possible the "configuration" (profile) and "definition" (recipes) of our dependency graph.

**Comment by jegabe** [comment]
> > We already thought about encoding the package name as value of an option. Using a setting is another possibility. However, it feels very unnatural.
> 
> Options would be a bit worse, because they need to be defined in each package. While, depending on the use case, of course, it seems to me that a mapping to a subsetting could be actually quite intuitive and easy to understand. There are different FreeRTOSConfig.h files, because we are targeting different platforms, each one will have its own binaries, then it makes sense that it is setting?
> 
> Adding another type of requirements is a bit scary for me. Right now, the dependency graph model is probably the biggest challenge in Conan. And we only have "requires" and "build-requires" (and "private", but that is not very recommended). I am very hesitant to add new types of requirements until we are able to improve the graph model with what we already know for sure. Then I would recommend the settings approach if possible, because that tries to keep as decoupled as possible the "configuration" (profile) and "definition" (recipes) of our dependency graph.

@memsharded Do you think that allowing "ANY" for settings makes sense then? That would simplify it when we would go for a new (sub)setting.

**Comment by jegabe** [comment]
So to summarize the discussion about config headers until now:

- Is it good to package config header files independently and individually: yes
- The sum of all switches should be encoded into a package name/version
- The package should be selected by introducing a new setting. If setting is not possible or hard to maintain: Use (global) options instead
- Avoid using environment variables to transport that information

Is that OK?

**Comment by memsharded** [comment]
> Is that OK?

Yes, I think if the mapping can be done reasonably well, this is OK

> @memsharded Do you think that allowing "ANY" for settings makes sense then? That would simplify it when we would go for a new (sub)setting.

Yes, it is fine. The only thing is that ANY value are not validated, any thing is valid. In this case, if they are going to have a close map to packages containing the headers, then it might be ok, typically the recipes will raise if they cannot do that mapping.

**Comment by jegabe** [comment]
Thanks @memsharded for your kind support. That really helped.
