### ISSUE TITLE
[bug] No CMAKE_CXX_COMPILER could be found.  when building OpenSSL with conan

### ISSUE THREAD

**Issue by panthersdude2001** [conan-io/conan#6648]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 1909 18362
  * Compiler+version: Visual Studio 2019 16.4.5
  * Conan version: 1.22.3
  * Python version: Python 3.7

### Steps to reproduce (Include if Applicable)
Install OpenSSL with this command
conan install OpenSSL/1.0.2l@conan/stable -s compiler="Visual Studio" -s compiler.version=9 -s arch=x86_64 --build=missing
, using visual studio command line tool and c++, clang, and latest binaries, and when it gets to calling build, it says the error.
### Logs (Executed commands with output) (Include/Attach if Applicable)
conan install OpenSSL/1.0.2l@conan/stable -s compiler="Visual Studio" -s compiler.version=9 -s arch=x86_64 --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=9
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Installing package: OpenSSL/1.0.2l@conan/stable
Requirements
    OpenSSL/1.0.2l@conan/stable from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    OpenSSL/1.0.2l@conan/stable:6cd8ea6465551274055d5bccec8ac6562b0a92d4 - Build
    zlib/1.2.11@conan/stable:4ec89ae26843442f955ab6e99b99fc8465076558 - Build
Build requirements
    strawberryperl/5.26.0@conan/stable from 'conan-center' - Cache
Build requirements packages
    strawberryperl/5.26.0@conan/stable:456f15897172eef340fcbac8a70811f2beb26a93 - Cache

strawberryperl/5.26.0@conan/stable: Already installed!
zlib/1.2.11@conan/stable: Copying sources to build folder
zlib/1.2.11@conan/stable: Building your package in C:\Users\snowc\.conan\data\zlib\1.2.11\conan\stable\build\4ec89ae26843442f955ab6e99b99fc8465076558
zlib/1.2.11@conan/stable: Generator cmake created conanbuildinfo.cmake
zlib/1.2.11@conan/stable: Calling build()
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/Users/snowc/.conan/data/zlib/1.2.11/conan/stable/build/4ec89ae26843442f955ab6e99b99fc8465076558/source_subfolder/_build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/snowc/.conan/data/zlib/1.2.11/conan/stable/build/4ec89ae26843442f955ab6e99b99fc8465076558/source_subfolder/_build/CMakeFiles/CMakeError.log".
zlib/1.2.11@conan/stable:
zlib/1.2.11@conan/stable: ERROR: Package '4ec89ae26843442f955ab6e99b99fc8465076558' build failed
zlib/1.2.11@conan/stable: WARN: Build folder C:\Users\snowc\.conan\data\zlib\1.2.11\conan\stable\build\4ec89ae26843442f955ab6e99b99fc8465076558
ERROR: zlib/1.2.11@conan/stable: Error in build() method, line 59
        self._build_zlib()
while calling '_build_zlib', line 110
        self._build_zlib_cmake()
while calling '_build_zlib_cmake', line 85
        cmake.configure(build_dir=".")
        ConanException: Error 1 while executing cd . && cmake -G "Visual Studio 9 2008 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="9" -DCONAN_CXX_FLAGS="/MP4" -DCONAN_C_FLAGS="/MP4" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\snowc\.conan\data\zlib\1.2.11\conan\stable\package\4ec89ae26843442f955ab6e99b99fc8465076558" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -Wno-dev C:\Users\snowc\.conan\data\zlib\1.2.11\conan\stable\build\4ec89ae26843442f955ab6e99b99fc8465076558

**Comment by panthersdude2001** [comment]
Ok, I was able to build after changing the compiler from 9 to 16. Closing

**Comment by memsharded** [comment]
Hi @panthersdude2001 

In any case, I would recommend using the new packages from ConanCenter, those are the ones without user/channel (i.e. ``openssl/version``, not ``OpenSSL/version@user/channel``). Also note new packages are all lowercase too. These new packages are more updated and maintained than the one with ``conan/stable``, and more likely to have updated binaries, etc.

**Comment by panthersdude2001** [comment]
I got it fine, thanks for noticing.I was able to change the release to 16 instead of 9 for the compiler.
