### ISSUE TITLE
[question] how to get deps_cpp_info.system_libs in post_package hook

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#6649]
Hello,

I'm trying to write a `post_packag` hook that tests whether a recipe hasn't forgotten to add some system library to `self.cpp_info.system_libs` using some heuristics.
This work is done in the `post_package`, instead of `post_package_info`, because the system_libs can be different for shared or static libraries. It extract the system libraries from the conanfile using a regex.

- It will only work on recipes packaging shared libraries as these should know what system libraries are needed. (these can be fetched using various tools, e.g. `objdump -p libXXX.so`)
- The missing system libraries are calculated as:
`missing = set(required) - set(cpp_info.system_libs) - set(deps_cpp_info.ssytem_libs)`

But `conanfile.deps_cpp_info` is `None` in the `post_package_hook` function.

My question is now how it is possible to the system libraries from the dependencies in the post_package hook. Wouldn't it be useful to set it in the `package` method?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
I think what you are requesting is done on purpose. ``self.deps_cpp_info`` is not available in the package method because there should be no logic there to make package contents conditional to any information coming from dependencies.

However, in a `post_package_info()` hook you should be able to reach the settings via the `conanfile` object. Have you tried that approach? Maybe the moment of detection is not as convenient as in post_package() but at least you could fail the command.

**Comment by madebr** [comment]
> However, in a `post_package_info()` hook you should be able to reach the settings via the `conanfile` object. Have you tried that approach? Maybe the moment of detection is not as convenient as in post_package() but at least you could fail the command.

That was my first approach (and did work).
But I moved it to `post_package` because I felt it should only warn while creating the package, not while using the package. To avoid printing too much in the cli.

Guess I'll have to move it to `post_package_info` again..

**Comment by madebr** [comment]
When I move it to `post_package_info`, I do not have access anymore to the `conanfile_path`.
I need the path of the export folder in order to read `conanfile.py`.

**Comment by madebr** [comment]
@danimtb I think I was wrong and was testing something wrong.
`self.deps_cpp_info` is available after all in the `post_package` hook.

If you think about it:
If it was not available, our CCI recipes would not work anymore since they are calling `self._configure_cmake` in the `package()` method.

**Comment by danimtb** [comment]
@madebr you are right. Glad to make it work. Sorry for my misleading answer
