### ISSUE TITLE
Windows installer problem with pywintypes27.dll

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#666]
In a windows 10 machine where I had installed conan 0.14.1 I had the following issue.

I tried to install a newer conan version (0.15.0) and then I got the error pop-up that I have attached. After that I aborted the installation and I uninstalled the conan software using the windows "Programs and Features" utility. The application was uninstalled successfully but the folder was still there and it was only containing the **pywintypes27.dll**. Then I tried to delete that file manually and I could not do it.

Has anybody else experienced this problem?
![conaninstallationissue](https://cloud.githubusercontent.com/assets/102645/20309208/642189a2-ab47-11e6-8aa4-690be626737c.jpg)

**Comment by lasote** [comment]
I suppose a python process is still running or hang. Try to reboot and remove again.

**Comment by piponazo** [comment]
It should be that. I tried to reproduce it in my personal machine and I was not able to do it. I will close this issue now and if I experience the same problem in the future I will reopen it. Thanks!
