### ISSUE TITLE
[question] CLion: Automatic Conan package export

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#6661]
**Use Case:**
appX depends on libA. appX and libA are within the same Git repo.

1. Developer opens their CLion project for libA
2. Developer does a `conan install` via CLion Conan plugin
3. Developer writes some new code for libA
4. Developer builds libA within CLion
5. Developer opens their CLion project for appX
6. Developer does a `conan install`, intending to pull in the updated libA but gets the old version

**Findings/Questions:**
I found the `conan export-pkg` command in the Conan documentation. I experimented with something like this:
```
add_custom_command(TARGET libA
                   POST_BUILD
                   COMMAND /full/path/to/conan export-pkg . --build-folder ${CMAKE_CURRENT_BINARY_DIR} --force
                   WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
```
This accomplished my desire of having the `conan export-pkg` happen automatically, as a result of a successful libA build with a couple issues:
1. I did not see a way to access my Conan profile so I could pass the `--profile <profile>` parameter to conan.
2. I did not see a way to access the Conan plugin's conan install path configuration property so I had to duplicate the full path in the CMakeLists.txt snippet above.
3. I don't want the `conan export-pkg` to happen outside of CLion (for example, when a CI Jenkins build is calling `conan create`).

Has anyone tackled any of these issues? The goal is to make it easy for developers to initially develop locally before pushing code (which would then trigger full CI Jenkins builds).

Thanks!

**Comment by jgsogo** [comment]
Hi, @radonish. 

There a couple of Conan features that could help you with this (although they still need some effort and dedication, but we don't have enough bandwith for all of it): [editables ](https://docs.conan.io/en/latest/developing_packages/editable_packages.html?highlight=editable) and [workspaces](https://docs.conan.io/en/latest/developing_packages/workspaces.html), they are exactly intended to develop several packages at once.

Editables generates a link from the Conan cache to your working directory for a package, so for example: you can develop `libA` locally, you put that package in editable mode and `appX` will consume the binaries from the working directory of `libA`, no need to export it to the Conan cache. Once the developer is happy with the changes, they can commit and/or create/export the package.

Workspaces is an evolution. With workspaces Conan creates a single project with independent packages (only CMake), it is quite challenging when you have packages between the ones added to the workspace and you need to compile them for each change in one upstream... so it has some bugs we haven't resolved yet 😞 

Let me know if one of this solutions serve your purpose. Workspaces might work for you, but editables is more mature and the only caveat is that your developers need to open one CLion per each library and they will be responsible of building libraries in order.

**Comment by memsharded** [comment]
Closing this question as inactive.

The recommendation is to use ``editables`` (not workspaces, they have been removed in 2.0)
