### ISSUE TITLE
[bug] cross_building() returns True for 32-bit on 64-bit machines (except for x86)

### ISSUE THREAD

**Issue by datalogics-robb** [conan-io/conan#6665]
### Environment Details (include every applicable attribute)
  * Operating System+version:  AIX/PowerPC and Solaris/SPARC (any version)
  * Compiler+version: any
  * Conan version: all / 1.21.3
  * Python version: 3.7 (tested)

### Steps to reproduce

Any profile that specifies a 32-bit build when the OS supports 64-bit architectures fails to build many projects because it incorrectly determines it is cross compiling.

### Patch needed:
```
diff --git a/conans/client/tools/oss.py b/conans/client/tools/oss.py
index be3d22e0..e0ad50e2 100644
--- a/conans/client/tools/oss.py
+++ b/conans/client/tools/oss.py
@@ -428,6 +428,10 @@ def cross_building(settings, self_os=None, self_arch=None, skip_x64_x86=False):
     if host_os is not None and (build_os != host_os):
         return True
     if host_arch is not None and (build_arch != host_arch):
+        if host_arch == 'ppc32' and build_arch == 'ppc64':
+            return False
+        elif host_arch == 'sparc' and build_arch == 'sparcv9':
+            return False
         return True
 
     return False
```

**Comment by datalogics-robb** [comment]
https://github.com/conan-io/conan/pull/6666

**Comment by danimtb** [comment]
I think it makes sense to have this fixed as we did with the x86 case

**Comment by danimtb** [comment]
Closing this as per https://github.com/conan-io/conan/pull/6666#issuecomment-763099143. Thank you
