### ISSUE TITLE
[feature] Add CONAN_XXXX_REFERENCE (and/or parts) to 'cmake' generator

### ISSUE THREAD

**Issue by johschmitz** [conan-io/conan#6669]
Conan generates a conanbuildinfo.cmake which contains CMake variables for each dependency.
What is missing is the information about the VERSION and CHANNEL of the dependencies.
This is important to ship an automatically conanfile.txt as part of the package.

Usecase is an example that uses virtualenv and virtualrunenv generators to set the environment variables.

My suggestion is to add variables in the form

    CONAN_<packagename>_VERSION
    CONAN_<packagename>_CHANNEL

alongside

    CONAN_<packagename>_ROOT

There seems to be no sensible workaround for this issue.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! I need to know more about your use case in order to understand your need. What is that automatic `conanfile.txt` used for? What do you try to do with the _virtualxxx_ generators (they wouldn't include the variables your are proposing for the CMake file)?

Thanks!

**Comment by johschmitz** [comment]
Hello,
so here is an example
Package 
abc/1.2.0@corp/testing
depends on
xyz/2.6.1@corp/testing

Now in package abc there is an example that needs binaries from abc and xyz from the conan cache during runtime. So we use a conanfile.txt with virtualrunenv for that and then a simple shell script that run conan install, sources the environment and launches the executables on the user/customer machine.

During development of that particular version we would like to generate(configure_file) the conanfile.txt into the example folder with CMake (based on a conanfile.txt.in) and it should contain the version from the testing channel.
The conanfile.txt.in could look similar to this
```
[requires]
abc/@CONAN_ABC_VERSION@@corp/@CONAN_ABC_CHANNEL@
xyz/@CONAN_XYZ_VERSION@@corp/@CONAN_XYZ_CHANNEL@
```
At the point of release into the stable channel CMake should automatically update the conanfile.txt based on the packages conanfile.py which always knows the correct version and channel of the dependency. That means we can automatically switch between versions and channels, especially between testing and stable.
So the information about VERSION and CHANNEL of each dependency just has to be handed over from Conan to CMake which is currently not the case and gives us a big headache because the developers always have to manually change the file.

**Comment by jgsogo** [comment]
First of all, I have to advice you not to use the `user/channel` of the Conan reference to provide information about the maturity of the package (`testing`, `stable`, `rc`): from the POV of Conan those will be different packages (packageID might be different depending on the `package_id_mode`) and the promotion mechanism in Artifactory won't work.

Related to your issue, we try to limit the information wrote by the generators, and those intended for build-helpers usually contain only information needed to build. If you are using a `conanfile.py` you can always pass that information from the recipe to CMake yourself:

```python
class Recipe(ConanFile):
    def build(self):
        cmake = CMake()
        cmake.definitions["CONAN_ABC_VERSION"] = "1.2.3"
        ...
```

**Comment by johschmitz** [comment]
I get your point of view. This is unfortunate.
What about people that want to have information about the dependency
version in CMake? Where do they get it from?
What is the right place than to put the information about maturity? We need
this information to publish to the correct Repo.

Javier G. Sogo <notifications@github.com> schrieb am Do., 12. März 2020,
19:01:

**Comment by jgsogo** [comment]
From the Conan recipe you can pass all the information needed to CMake, that's not a problem and it is really easy as I saw you before; bin order for Conan to provide that information by default through all the generators requires a strong use-case. 

Regarding the maturity the recommendation is to have several different repositories and promote packages from one to another: there can be a repository for every build, if all the test pass (and the PR is merged) the artifacts would be merged into a `develop` repository, then to a `release_candidate`, the QA or other department can run further tests and promote the artifacts to another repository targetting deployments... for sure this workflow will be different in each company, but the important thing is inmutability of the artifacts in order to achieve traceability and changing the Conan reference during this process will make things much harder.

**Comment by johschmitz** [comment]
Somehow what you say doesn't match what is written here:
https://docs.conan.io/en/latest/faq/using.html#faq-recommendation-user-channel
It says you may use the channel to distinguish testing and stable. That's
exactly what we do. I just want to have that information on the CMake
layer.

Javier G. Sogo <notifications@github.com> schrieb am Fr., 13. März 2020,
09:27:

**Comment by jgsogo** [comment]
Yes, you can use the `channel` to tell about the status of the package, that's ok, what I was trying to warn you about (and maybe I'm not explaining myself well) is that the same package shouldn't be promoted just by changing the value of the `channel` in the Conan reference. It is ok, to name the pakcage `xxxx/1.2.3@mycompany/develop` while it is in under development, but once you have a stable version you shouldn't `copy`, rename or `alias` the package, you should create it again with the new reference.

About having that information in the CMake layer, you can do it yourself right now the way I told you, it is just a couple of lines in your recipe.

ATM Conan is not considered a deployment tool and it is not supposed to run in the final machine to retrieve during runtime more binaries. This could be an interesting use-case, but it is not something we have think about.

Coming back to your request, I see that the `cmake` generator is indeed populating a `CONAN_XXX_ROOT` variable, but that's all, nothing related to the Conan reference (the `name` could be different given the `cpp_info.names` capabilities)... and other generators that are preferred like `cmake_find_package` create only the typical CMake variables. So, I see that your request would be more like a `CONAN_XXXX_REFERENCE` with the value of the actual reference used for the package (then we can also provide a function to parse its different components), right?

**Comment by johschmitz** [comment]
A CONAN_XXXX_REFERENCE would be great and would solve our current problem.
Not sure if it would be better to split it into its components or not. For
example people might want to just use the version number for some
conditional statements in CMake. However, those issues could probably be
solved in the Conan layer.
So for us, exposing the CONAN_XXXX_REFERENCE in CMake would be sufficient
at the moment. Two thumbs up if you can make it happen :-)

Regarding Conan as a deployment tool I can tell that it works already quite
well. The scenario is a developer team to developer team(s) deployment
though.

Javier G. Sogo <notifications@github.com> schrieb am Fr., 13. März 2020,
11:19:

**Comment by memsharded** [comment]
This issue was reporting the legacy CMake integration, which has been superseded by the new one in Conan 1.X https://docs.conan.io/1/reference/conanfile/tools.html, and removed in Conan 2.0: https://docs.conan.io/2/reference/tools/cmake.html. Closing this ticket as outdated.

Please update to use the modern CMake integration, and please don't hesitate to open new tickets as necessary. Thanks!
