### ISSUE TITLE
[bug] cmake_find_package generated file doesnt honor CONAN_CMAKE_SILENT_OUTPUT

### ISSUE THREAD

**Issue by rasjani** [conan-io/conan#6671]
### Environment Details (include every applicable attribute)
  * Operating System+version: not applicable 
  * Compiler+version: not applicable 
  * Conan version: everything released
  * Python version: not applicable 

### Steps to reproduce (Include if Applicable)

with cmake-conan  at least when issuing following command:

`cmake -GNinja -DCONAN_CMAKE_SILENT_OUTPUT $buildpath` 

and having cmake_find_package generator enabled in conanfile or passed in to conan_cmake_run(), generated Find$package.cmake has a single message() call.  Since the bug is essentially here:

https://github.com/conan-io/conan/blob/develop/conans/client/generators/cmake_find_package.py#L9

Same will most likely happen with calling `conan install` too..

When cmake 3.17 or never, these could be removed by filtering on the log level but that is not option for everybody.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Excessive output like this will be shown when generating build scripts:

```-- Conan: Using autogenerated FindXXX.cmake
-- Conan: Using autogenerated FindYYY.cmake
-- Conan: Using autogenerated FindZZZ.cmake
```

**Comment by jgsogo** [comment]
Hi, @rasjani  Thanks for reporting and thanks for submitting the PR, I agree with you that all the output generated by Conan should be silenced by `CONAN_CMAKE_SILENT_OUTPUT` variable.
