### ISSUE TITLE
[question] Conan and http:// Artifactory remotes

### ISSUE THREAD

**Issue by floriansimon1** [conan-io/conan#6682]
- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I tried to upload to a HTTP Artifactory remote, against which I can authenticate just fine. When uploading, however, Artifactory complains that the checksum of the file it receives and the checksum Conan provides in the HTTP request are different.

To debug that, I had to modify the Conan code to display HTTP errors, and I noticed that the actual checksum was always the same, whatever the file I was trying to upload was (conandata.yml, conanfile.py...).

My question is: is there maybe a redirect that Conan does not do? Or is it possible to have an option to show HTTP error message to make errors like these easier to debug?

**Comment by memsharded** [comment]
Hi @floriansimon1 

Can you clarify what do you mean with "HTTP Artifactory remote"? Have you setup an Artifactory local repository of type "Conan"? Using ``CONAN_TRACE_FILE`` env var or conan.conf, the rest API calls that conan is doing can be logged, that could help to reproduce. Which Artifactory are you using, the Artifactory CE? Artifactory PRO? Which version? Which version of Conan?

I always try to setup a simple environment, local, to debug these things: Download the Artifactory CE from the conan download page, launch it, set a Conan local repo... That helps to isolate and reproduce issues.

**Comment by floriansimon1** [comment]
Hi @memsharded!

By HTTP remote, I mean a remote that has a URL with the http:// scheme instead of https://.

The Artifactory repository has been setup by my organization, I didn't set it up. I guess it's a PRO version of Artifactory, number 6.12.2. The version of Conan I tested with were 1.22.3 and 1.23.0.\

I'm glad CONAN_TRACE_FILE exists, and that's basically all I wanted to know. Is it in the docs somewhere? I'm guessing that if there's a doc page, it's probably a gold mine of information and I'd love to read it.

**Comment by memsharded** [comment]
Hi @floriansimon1 

Yes, it is documented in https://docs.conan.io/en/latest/reference/env_vars.html#conan-trace-file

The integrated search is not superb, so I recommend to have a look at the reference, howtos, etc in the docs, they might give some interesting ideas. Improving the docs is something that we keep doing all the time, but it is a never-ending never-enough effort 😅 

Is the issue solved then? Did you manage to figure out what was happening with the trace file?

**Comment by floriansimon1** [comment]
Thank you!

I consider this solved. I'm guessing it's a proxy thing or something like that. I don't really know the details, but it does not matter all that much to me. Does Artifactory run Conan servers? Is this how it works? If so, then I guess conan-server has an issue, because it 500s on me when I talk to it via plain HTTP, instead of returning a 400 or something like that. If it's just an Artifactory issue, I guess I'll just close this thread forever and maybe report to Artifactory people.

Thanks for your time!

**Comment by memsharded** [comment]
Artifactory natively implements the Conan protocol, fully implementing its api, but it doesn't reuse code from Conan itself. We always recommend Artifactory as server, it is more complete and robust.

Before reporting to Artifactory, I would strongly recommend the above: to setup a simple environment, local, to debug these things: Download the Artifactory CE from the conan download page, launch it, set a Conan local repo. This takes around 5 mins max, and it really helps to isolate problems. Most of the times it is configuration, proxies, or something in the server setup, so it is good to know if locally it works.
