### ISSUE TITLE
[question] [suggestion] dynamic install_folder

### ISSUE THREAD

**Issue by AGreat1** [conan-io/conan#6691]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Hi!

In my application project I'm trying to use conan to manage my dependencies. This project should be able to support multiple configurations (e.g. Windows, WinXP, Linux...). My plan is/was to create a profile for each configuration that contains the options and settings for that configuration. I'm going to use cmake_paths generator and wire visual studio to use the cmake file generated as a toolchain.

Here's my problem: When I (and especially colleagues) use conan, I would like to have a single conanfile and to only have so specify the profile/configuration. If I do not vary the install_folder per configuration (per profile in my reckoning), then my build will fail very late in case someone forgets to install the proper dependencies - in the linking phase. I want it to fail earlier, like when cmake can't find the toolchain.

My idea was that the profile could set the install_folder with a relative path to cwd. I do not see this is possible, so I tried this: I turned my conanfile.txt into a conanfile.py, and tried dynamically setting the install_folder. Something like this:

```
import os
from conans import ConanFile

class Example(ConanFile):
	name = "example"
	version = "latest"
	settings = "os", "compiler", "build_type", "arch"
	options = {"profile": ["Win", "WinXP", "Linux"]}
	default_options = {"profile": "Win"}
	generators = "cmake_find_package", "cmake_paths"
	install_folder = os.getcwd()
	
	def configure(self):
		if self.options.profile == "Win":
			self.install_folder = os.path.join(self.install_folder, "conan", "win")
		elif self.options.profile == "WinXP":
			self.install_folder = os.path.join(self.install_folder, "conan", "winxp")
		elif self.options.profile == "Linux":
			self.install_folder = os.path.join(self.install_folder, "conan", "linux")
	
	def requirements(self):
		self.requires("libcurl/7.66.0")
		self.requires("libxml2/2.9.9")
		self.requires("gtest/1.10.0")
```

conan seems to ignore this, so we are left with having to specify both a profile **and** an install_folder when installing dependencies. This is an error-prone solution, especially because the install_folder would also not be arbitrary, but specified in a VS settings file.

So my suggestion is to allow setting the install_folder through a profile and/or through the conanfile. What do you think? Is there an alternative way that already exists with which I can achieve my goal?

**Comment by memsharded** [comment]
Hi @AGreat1 

I would need to understand better your use case, I don't fully get it.
It seems that you are managing different profiles. Profiles are typically managed as text files, and can be updated from a central location, so all devs and CI use the same profiles with ``conan config install`` command.

The ``settings.os`` already encodes the operating system, the option ``options = {"profile": ["Win", "WinXP", "Linux"]}`` reads as redundant to me.

Not sure what you mean with the ``install_folder``. Conan packages are installed in the Conan cache, and they will follow the cache layout. Different binary packages for different OSs will be in different packageID folders, identified by the packageID.

If you want to extract files from the cache and do a local copy, then the ``imports()``, ``deploy()`` methods might be what you are looking for, or maybe the ``-g deploy`` generator. Those do a copy of artifacts to user folders from the cache. Note however that the generators information is relative to the Conan cache.

**Comment by AGreat1** [comment]
I'm interested only in the output of the generators right now. That goes next to the `conanfile` by default, and I can use the command-line `install_folder` to tell conan to put this output to a different folder. (I understand those are references to contents of the conan cache, and I'm satisfied with how the cache works).

### Currently

* I install dependencies for my project: for x86 Win (I conveniently have a profile for this).
 * cmake_paths.cmake file and
 * findXXX.cmake are created next to the conanfile.
* I work on my project
* When I come back later, I try building my project for x86 Linux.
 * project builds
 * linker fails because 3rd-parties pointed to by the toolchain/cmake_paths are for Windows
 * Between winXP and more modern windows I might not even encounter an error until runtime.
* I realize I forgot to install x86 Linux dependencies
* Install x86 Linux dependencies and think about the time I lost with the previous steps

### My wish
* I install dependencies for my project for x86 Win
 * cmake_pahts.cmake file and
 * findXXX.cmake are created in an install_folder e.g. "x86_win"
* I work on my project
* When I come back later, I try building my project for x86 Linux
 * CMake throws an error before building starts e.g. "Cannot find toolchain file 'x86_linux/cmake_paths.cmake'"
* I realize I forgot to install x86 Linux dependencies
* Install x86 Linux dependencies and skip waiting for my project to build.

I have a profile for build types that needs to be specified anyway, so it would be convenient for the profile to specify the install_folder also. This would work well with an IDE that can look for the CMake toolchain file in a different location depending on the configuration. It'd be equally convenient if I could dynamically override install_folder in the conanfile.py. I am open to some solution that is readily available though.

**Comment by Minimonium** [comment]
Related to https://github.com/conan-io/conan/issues/2888

**Comment by memsharded** [comment]
Ok, now I understand better the use case, thanks for the detailed explanation.
Currently, it is not possible to define the install folder in that way, you need to either chdir before the command, or to use the ``conan install . --install-folder=xxxx```command.

We have already started some efforts in trying to be able to define these things in the recipes. It is called the "layouts", and there is some preliminary work here: https://github.com/conan-io/conan/pull/6261. It is a very complex issue, and it will take time, but if you would like to see this feature, the best would be to comment there (if this question is solved and the feature request can be tracked there, could this issue be closed?). Thanks!

**Comment by AGreat1** [comment]
I'm not familiar with the internals of conan. I've only started using it recently. I looked into the PR you mentioned and a bit of the code-base and it definitely seems like the layout would solve my problem. I guess I'll put a mention to this issue in the PR where I *think* it's being solved.

Waiting for the layout feature to be rolled out then :) Thanks for the help!
