### ISSUE TITLE
[question] Command line generated by CMake build helper

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#6692]
Hi Conan team,

I already asked this on slack, but I'd like to get some official feedback from the Conan team.

I am using the CMake build helper in my recipes:
```python
cmake = CMake(self)
#print out the command line
print(cmake.command_line)
cmake.configure()
```

The build helper passes a lot of variables to the CMake build (documented [here](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#definitions)), some of them are official CMake variables like:
```
CMAKE_BUILD_TYPE
CMAKE_SYSTEM_NAME
CMAKE_INSTALL_PREFIX
CMAKE_INSTALL_INCLUDEDIR
BUILD_SHARED_LIBS
```
But other variables are prefixed with `CONAN_`. You have to call `conan_basic_setup()` to translate them to the "proper" variables, that CMake recognized.
For example:
```
CONAN_CMAKE_CXX_STANDARD   -> CMAKE_CXX_STANDARD
CONAN_CMAKE_CXX_EXTENSIONS -> CMAKE_CXX_EXTENSIONS
CONAN_C_FLAGS              -> CMAKE_C_FLAGS
CONAN_CXX_FLAGS            -> CMAKE_CXX_FLAGS
```

**Now the problem:**
I am using the `cmake_paths` generator, so I am not calling basic setup. 
How can I get the CMake build helper, to directly set the cmake relevant variables, instead of the conan ones?
Especially I am intested to propagate the `CMAKE_CXX_STANDARD` variable to be propagated from the information I set in the profile.
Is this possible?

It would be nice, if I can trigger the behavior in the constructor:
```python
cmake = CMake(self, native_cmake_variables=True)
```

Originally, I thought
```python
cmake = CMake(self, set_cmake_flags=True)
```
would do the trick, but it seems to have no influence on the definitions / command line output whatsoever.

**Comment by Minimonium** [comment]
Having a direct build system configuration would be great. One problem would be that we'd have different behaviour for in-cache builds and local builds.

**Comment by memsharded** [comment]
Hi @KerstinKeller 

This issue is somehow considered in the toolchains. We really want to stop passing variables in the command line, both conan and cmake variables, and do generate a toolchain file instead.

Ongoing WIP: https://github.com/conan-io/conan/pull/5919

This will not be fast, it is a complex feature. But our efforts will be focused on this approach. I would suggest track that PR, comment there, and start giving feedback as soon as we start to release it experimentally.

**Comment by KerstinKeller** [comment]
Hi @memsharded,

sure, I am happy to track the PR and try out the new toolchains.
Will they work with the `cmake_paths` generator? That's the most important point for us.

As for the `set_cmake_flags` argument: 
It seems to do as I thought, though only for the `FLAGS` variables. 
https://github.com/conan-io/conan/blob/995c50cf7ae988583b3f6df116c4181b16d4d7f3/conans/client/build/cmake_flags.py#L307-L314

I will work around this with a custom function to forward / append the correct variables manually by referencing the Conan ones.

Though one remark if you're reworking it anyways:
```
CONAN_CMAKE_CXX_EXTENSIONS -> CMAKE_CXX_EXTENSIONS
CONAN_C_FLAGS              -> CMAKE_C_FLAGS
```
One still has the `CMAKE` in the name, the other doesn't. Would be good to follow a consistent naming scheme here 😉

**Comment by memsharded** [comment]
This ticket was using the old generators (legacy in 1.X, removed in 2.0), that have been superseded some time ago by new ones. Closing as outdated, please check the new ones and don't hesitate to open new tickets as necessary for any further question.
