### ISSUE TITLE
[question] conandata.yml types

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6697]
Okay, so this is a little bit controversial topic maybe.
but I just stumbled across a somewhat surprising behavior that took me a bit to figure out what the hell is happening.

so i happily copied a conandata.yml from one of your project lets say I copied this one:
https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html

However versions in my project had only major and minor so.. for example `1.0`.
so my conandata.yml looks like so: 
```
patches:
  4.13:
    - patch_file: "patches/weak_ptr_factory.patch"
```
You probably know where I am going with this now .. but this code did not work:
```
        if self.version in self.conan_data["patches"]:
            for patch in self.conan_data["patches"][self.version]:
                tools.patch(**patch)
``` 
Because oh well - python and it was comparing apples and oranges oops i mean floats and strings. 
In the end as a quick hack i did:
```
ver = float(self.version)
```
and that allowed me to move on :) 
Now I know that i can put this in 'quotes' and it will treat this as strings.
Anyway - very confusing and not initially obvious behavior, probably worth adding a doc on this on the conandata.yml file or even considering having a stringly schema in yml if thats even possible.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I think this is wrong, at the very least https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html should be fixed to add quotes, and some warnings explicitly about this. 

As the conandata is actually completely agnostic of contents (it is just a dict for Conan), I don't think we can add any further check in the code.

**Comment by jgsogo** [comment]
Yes, totally. We need to update that part of the docs. And I will submit this check to the conan-center hook.

**Comment by jgsogo** [comment]
We have added a note to the docs here https://github.com/conan-io/docs/pull/1608 and probably this is the best thing we can do about it. 

The only place where Conan itself is writing to this file the SCMData object and [here](https://github.com/conan-io/conan/blob/develop/conans/model/scm.py#L41) we are checking member type. We allow the revision to be an integer (SVN revisions are integers), but it shouldn't be a problem to write and read afterward. Also, there are tests using that revision as an integer (and I'm [adding one more](https://github.com/conan-io/conan/pull/6706) with booleans).

**Comment by jgsogo** [comment]
I'm closing this one, but if I'm missing something, please open it again.

Thanks!
