### ISSUE TITLE
[bug] misplaced os.api_level in html table generated by conan

### ISSUE THREAD

**Issue by apolon81** [conan-io/conan#6699]
Currently conan search --table generates weird layout when Android builds are present. Surely os.api_level property belongs in the same place as os? First table is what we are getting right now (note api level 29 placement). Second is what I think is the right way to visualize API level, which is to further characterize os.

|                                | 29 x86 Release | 29 x86_64 Release | x86_64 Debug | x86_64 Release |
|--------------------------------|----------------|-------------------|--------------|----------------|
| Android clang 9 (libc++)       |        x       |         x         |              |                |
| Linux gcc 8 (libstdc++)        |                |                   |       x      |        x       |
| Windows Visual Studio 15 (MT)  |                |                   |              |        x       |
| Windows Visual Studio 15 (MTd) |                |                   |       x      |                |

|                                | x86 Release | x86_64 Debug | x86_64 Release |
|--------------------------------|-------------|--------------|----------------|
| Android 29 clang 9 (libc++)    |      x      |              |        x       |
| Linux gcc 8 (libstdc++)        |             |       x      |        x       |
| Windows Visual Studio 15 (MT)  |             |              |        x       |
| Windows Visual Studio 15 (MTd) |             |       x      |                |

**Comment by jgsogo** [comment]
Hi, @apolon81. Thanks for pointing this out. We are redesigning the CLI and for sure we will have a look to the outputs too. This table is something we need to revisit.

**Comment by memsharded** [comment]
This table was full revamped in Conan 2.0, closing as outdated, please report in new tickets against new table
