### ISSUE TITLE
[question] Using `conan graph` to get the build-order of a subgraph

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#6709]
We are trying to develop a custom tool that will allow us to ease development environment setups:

* A repository is cloned 
* All its dependencies are installed via Conan
* For some well identified dependencies (other repositories from our organization), they are installed as local repositories, for developer to modify

To address this last point, we need to get the build-order for a subgraph. Let's imagine this simple complete graph:
`C -> B -> A`

We obtained the complete lockfile via: `conan graph lock -pr myprofile C/conan/`

We can obtain the complete build order with: `conan graph build-order conan.lock`

Yet, at some point we need the build-order only for the subgraph 
`B -> A`
 how can we achieve that?

----

Side note: we tried to control with the `--build` option.
In particular`conan graph build-order -b=never conan.lock`, yet it is still outputting the same complete build order (apparently because the recipes have the "missing" build policy in them)

**Comment by memsharded** [comment]
Hi @Adnn 

I am checking, but it seems it is not possible right now. 
Could you please describe a bit more the flow that you want to achieve? Because in the CI/CD flows that we are trying to define, when building an intermediate node, only that node should be built, and thus a ``conan create`` or ``conan install`` is enough. Only the build-order is necessary when we want to check that complete products are integrating successfully changes in some upstream dependency.

**Comment by Adnn** [comment]
Hi @memsharded ,

Thank you for taking the time to look into that.

>Could you please describe a bit more the flow that you want to achieve? Because in the CI/CD flows...

Let's try to give some more details. Actually, Conan is already used in our CI/CD workflow, but we need to leverga/extend it to now work with our product development workflow.

Basically, our development model is based on several repositories of varying granularity (I tried to write some comprehensive guide about our approach, it notably provides a description of the repository model: https://adnn.github.io/ModernCppComponent/#_the_process)

Let's extend a bit the naïve graph above:

```
C -> B -> A
     | -> Ext
```

So, `C`, `B` and `A` are internal repositories, and `Ext` is an external dependency.  `C` would list `B` as a `requires`, while `B` would list `A` and `Ext`. This works perfectly fine in CI out of the box.

Now, our development workflow is very adaptative. Some developer might only need to edit `C`, in which case it is easy enough for them to satisfy all dependencies with Conan, and be done [note: we later found out it was not totally trivial though, because it was still necessary to forward the same profile/configuration to `C`]

But, other developers will be interested to edit `C`, `B`, and even `A`, all at the same time. (For example, deeply reworking `A` API might require to edit those 3 repositories at the same time).
This is a situation we always had a hard time addressing with Conan, to such an extent that most our developers never use Conan locally: they build all dependencies manually and manually configure CMake by explicitly providing variables (`B_dir`, `A_dir`, `Ext_dir`, etc.).

This is a shame : Conan is a great tool to resolve dependency graphs, retrieve and build dependencies, and can even configure and generate build-files/projects with CMake. Yet, as far as we know, it does not allow to use a dependency taken from a "local repository clone".

So we are currently implementing a simple tool bridging this gap:
1. The tool takes a list of upstreams (`B` and `A`) that must be locally edited (by opposition of providing them from the Conan cache)
2. I generates the lockfile for the downstream project (`C`)
3. It  `conan install` and `conan build` all upstreams and downstreamn in the local development folder, *making sure to use the lockfile* (so we leverage Conan graph reconcialiation)

**Comment by memsharded** [comment]
> But, other developers will be interested to edit C, B, and even A, all at the same time. (For example, deeply reworking A API might require to edit those 3 repositories at the same time).
This is a situation we always had a hard time addressing with Conan, to such an extent that most our developers never use Conan locally: they build all dependencies manually and manually configure CMake by explicitly providing variables (B_dir, A_dir, Ext_dir, etc.).

> This is a shame : Conan is a great tool to resolve dependency graphs, retrieve and build dependencies, and can even configure and generate build-files/projects with CMake. Yet, as far as we know, it does not allow to use a dependency taken from a "local repository clone".

Yes, this is the balance of the monolithic vs componentized development approaches. In theory when you go for a componentized approach, every component is an isolated unit of work, and by definition it has its own versioning and release cycle. 
In a componentized world, ``deeply reworking A API might require to edit those 3 repositories at the same time`` should be necessary. Component A can be reworked in complete isolation, develop and test its new API, and then be released with a new version. This new version will not be automatically be used by consumers, so everything keep working. When the downstream consumers (e.g B) are moving forward to use the new A API, they will adapt their code accordingly and release a new version as well (that might be downstream compatible or incompatible, depending on the isolation).
If modifying 2 packages at the same time is that necessary so often, maybe they are not separate components, but just one.

Although we think that this is how it should be, we for sure know that the reality is often a bit more complicated. We know that the editables and specially the "workspace" Conan features that would improve this experience, are not fully baked and they need work (BTW, I guess you tried them, but they didn't work? Were you aware of them?). It is in our to-do list, just it didn't get the higher priority yet.

Even if you don't fully leverage the workspace feature, I think it could provide you the information you need. It can create ``conanbuildinfo.cmake`` files, or whatever other generators you specify, in each local package, and that will contain also the information of the dependencies. Have you considered this approach?

**Comment by Adnn** [comment]
Thank you @memsharded for your detailed answer, and for introducing `conan workspace`. We were not aware of this feature.

From [this documentation](https://docs.conan.io/en/latest/developing_packages/workspaces.html), this feature seems promising, and align with several aspect of our requirements. We were finally able to give it a try today

~~after setting up our workspace YAML and layout INI, we were interrupted by a conan error on an external dependency (`boost/1.72.0`) dependency (`bzip2/1.8.0`):~~

>bzip2/1.0.8: Downloaded package revision 0
>ERROR: bzip2/1.0.8: Error in package_info() method, line 56
>        self.cpp_info.names["cmake_find_package"] = "BZip2"
>        TypeError: '_CppInfo' object does not support item assignment

~~Does it mean the bzip2 recipe is somehow not compatible with the workspace feature? (We can compile all our dependencies on this environment with the usual `conan install`)~~

~~Sadly, if this error is actually out of our hands, we won't be able to use `conan workspace` feature. (Most of our projects directly or indirectly rely on `Boost`).~~

**EDIT:** Updating from Conan 1.20 to 1.24 seems to fix this issue

---

Regarding the initial question raised in this issue, it seems the ability to get the build order for subgraphs might still be a reasonable feature, what are your thoughts? Even if later on we can use the workspace feature, some other use cases might be able to leverage such feature, which could be a good addition to a generic graph analysis command.

On the other hand, we were able to complete a first version of the tool we designed before being aware of `conan workspace`: https://github.com/Adnn/anyrepo

In the absence of the subgraph build order, we give each repositories the path to all other repositories (they will only use the paths corresponding to actual dependencies).

**Comment by AbrilRBS** [comment]
Hi, sorry that we didn't answer back at that time. I'll close this one after giving some extra details if anyone ever finds themselves with the same question:

Note that with [`conan graph build-order ... --lockfile-out=conan.lock`](https://docs.conan.io/2/reference/commands/graph/build_order.html) you can generate a lockfile for the dependency graph, and then if you run the same `conan graph build-order` but for one of your transitive dependencies in the graph while also passing `--lockfile=conan.lock` (If named conan.lock Conan will use the lockfile by default!), you can ensure the same subgraph order is generated. Hope this helps someone, if anyone has questions regarding this, feel free to create a new issue, we're always happy to help :)
