### ISSUE TITLE
[feature] Componets: Expose components to consumers

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#6717]
Coming from #5090 

On #6653 components were introduced at the definition level but cannot be used by a generator.

Implementing this feature should allow fine-grained components access to consumers via `self.deps_cpp_info` object.

Components should be accessible for each recipe like:

```
self.deps_cpp_info["dep1"].components
```

We should consider adding helper methods to get all the components in the right link order as requested in #6716

**Comment by jgsogo** [comment]
Alternative notation could be `self.deps_cpp_info["dep1::cmp1"]`

**Comment by memsharded** [comment]
Already documented.

**Comment by iiknd** [comment]
Hi, I can see this one closed along with [6716](https://github.com/conan-io/conan/issues/6716).
The documentation says it's still experimental feature? Is the current components feature still subject to small/big changes?

**Comment by jgsogo** [comment]
Hi, @unzap. Although everything is subject to change in the next major release if it is really needed, one of the main efforts would be dedicated to **keeping recipes compatible for Conan v1 and Conan v2**. We are already using components exhaustively in [`conan-center-index`](https://github.com/conan-io/conan-center-index), you can use it as a proxy to know which features are well tested and _won't_ likely be modified, it would break all ConanCenter (which is something we really don't want to do).

**Comment by iiknd** [comment]
Thanks for the info, I will have a look in there.
