### ISSUE TITLE
msbuild build helper should support adding resource compiler include paths

### ISSUE THREAD

**Issue by gdray-dev** [conan-io/conan#6726]
The msbuild build helper mostly relies on environment variables to provide paths to dependency header files and libraries.  When the msbuild helper is used on a solution where the resource compiler requires header files from a dependency, the environment does not appear to be set up to provide the needed paths.  The resource compiler documentation indicates that it will look at the INCLUDE environment variable.  I was unable to determine if the msbuild helper sets this environment variable correctly during the resource compile build. It appears not since dependency paths are not found.  It also concerns me that using the INCLUDE environment variable might mix header directories with the C/C++ compiles.
As a possible alternate solution, the conan_build.props file could be modified to include:

    <ResourceCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ResourceCompile>
  </ItemDefinitionGroup>

I have attached a patch file demonstrating this change.  It has been tested with a very simple case.

[changes-patch.txt](https://github.com/conan-io/conan/files/4376169/changes-patch.txt)

**Comment by memsharded** [comment]
Hi @gdray-dev 

> The msbuild build helper mostly relies on environment variables to provide paths to dependency header files and libraries.

I think there might be some misunderstanding here. The information for VS projects for dependencies headers and libs comes from the ``visual_studio`` or ``visual_studio_multi`` generators. These generators will be creating a ``conanbuildinfo.props`` file, with all the relevant information: include paths, library paths, etc. The VS solution has to include this file to get information about dependencies.

There is a complete how-to, including some Github repositories with example code in:
https://docs.conan.io/en/latest/howtos/visual_studio_packages.html

I suggest having a look to the project files in the repos, for example: https://github.com/memsharded/chat_vs/blob/master/build/ChatLib/ChatLib.vcxproj

Please, have a look to these resources and let us know if you have any question.

**Comment by gdray-dev** [comment]
Hi @memsharded 

I'm looking at supporting two customer sets.  The SCM and CI customers will use MSBuild() to rapidly go through and build a very large group of projects.  Individual developers will use the visual_studio generators to produce props files that will allow them to develop in the VS IDE.

The problem appears to be that MSBuild() does not rely on the visual_studio generator as you suggest.  The documentation here:

https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html#msbuild

States:

<<
Internally the MSBuild build helper uses VisualStudioBuildEnvironment to adjust the LIB and CL environment variables with all the information from the requirements: include directories, library names, flags etc. and then calls MSBuild.
<<

This is unfortunate because now my SCM/CI crowd build with a different infrastructure than my developers.  As noted by this issue, the visual_studio generator will generate a prop file that will support adding dependency resdirs to the IDE build but then when CI runs using the same package and builds with MSBuild(), the environment variables are not set in the same way and we get a build error.

While I submitted a patch that simply resolves the resource compiler issue, I think the bigger problem is that the two methods for building fundamentally use different approaches that Conan has to continue to keep "in-sync".  I would love to see both methods rely on a common generation of a prop and just abandon the environment approach all together.  Or perhaps deprecate it with possible future removal.

**Comment by memsharded** [comment]
> While I submitted a patch that simply resolves the resource compiler issue, I think the bigger problem is that the two methods for building fundamentally use different approaches that Conan has to continue to keep "in-sync". I would love to see both methods rely on a common generation of a prop and just abandon the environment approach all together. Or perhaps deprecate it with possible future removal.

Yes, this is exactly our intention. This is very challenging to be removed now without breaking users that might rely on it. But most likely Conan 2.0 will remove the environment approach. Not only for this, but for other generators and build helpers. The idea is that build-helpers will be just a convenient way to call the build systems, but will have less logic. Part of this logic will be moved to toolchain, environment files and the dependencies information in its own file.

**Comment by memsharded** [comment]
Closing this ticket as outdated, referring to legacy Conan 1.X build-system integrations that have been removed and replaced b new ones in Conan 2 years ago.

Please create new tickets as necessary to report against the new integrations, thanks!
