### ISSUE TITLE
[question] conan info|install skips cache and tries to find package from remote instead?

### ISSUE THREAD

**Issue by starsoup** [conan-io/conan#6727]
Using conan 1.22.1 @ Ubuntu 16.x

Hi all!

I've gone through the documentation and I should have basic knowledge about the basic work flow.
But now I'm stuck at something I don't understand, most probably I'm doing something wrong....

I've exported a package to my local cache successfully. I've disabled the default remote because I want to work locally.
I can 'conan search' the package, it can be found from the cache, conan prints it on the screen.
But if I try to 'conan info' or 'conan install ... --build=<package>' it will fail immediately:
> ERROR: Remote 'conan-center' is disabled

As the package I want to use is in my own conan cache shouldn't it use it from there? Why it insists having a remote connection?

**Comment by danimtb** [comment]
Hi @starsoup,

In theory that should not be happening but check your consumer recipe or the one that you exported as it may have some kind of requirement that it is not in your cache. If that is the case, Conan will try to fetch it from a remote.

Another thing that could be happening that is indeed a bit confusing:

When you install binary packages, the recipe and the binary that matches your profile are downloaded but the sources of the package are not. In case you *go offline* and want to build from sources, Conan tries to fetch the sources from the same remote the recipe was originally downloaded from. In your case, I see you typed ``conan install .. --build``, which means building everything in your dependency graph from sources (``--build`` means build all). That could be triggering the behavior described above.

Maybe you would like to try just building the recipe you exported to the cache. You can do that specifying the name of that recipe with ``--build <name>``.

Please try that and let me know

**Comment by starsoup** [comment]
Hi @danimtb and thank you for the reply!

I have module_1 and module_2 (names mangled) and the module_1 depends on module_2, there are no other conan dependencies in "requires" sections.

In my working area both packages contain the conanfile.py and source code.

I made sure the packages were in my conan cache by exporting those again
```
$ cd <module_1>
$ conan export . module_1/1.0@test/test
...
$  module_1/1.0@test/test: The stored package has not changed
$ module_1/1.0@test/test: Exported revision: 56ead494015a7e2fee0dc997c57e40e6
...
$ cd <module_2>
$ conan export . module_2/1.0@test/test
...
$  module_2/1.0@test/test: The stored package has not changed
$ module_2/1.0@test/test: Exported revision: 7879d5a3097bed771c205d1589b872ae
```

Looking into the cache I can see that "export/" contains the conanfile.py and "export_source/" contains the matching source code. This looks correct for both module_1 and module_2.

> Maybe you would like to try just building the recipe you exported to the cache. You can do that specifying the name of that recipe with --build <name>.
> 
> Please try that and let me know

```
$ cd <module_1>  # has dependency to module_2
$ conan install . --build=module_2
...
$ ERROR: Remote 'conan-server' is disabled
```

alternative:

```
$ cd <module_1>  # has dependency to module_2
$ conan install module_2/1.0@test/test --build=module_2
...
$ ERROR: Remote 'conan-server' is disabled
```

Oddly if I enable the conan-server (which does not contain my test conan packages) it success building the packages.

Hmm, is there anything else I could debug? I can go down the route to checkout conan source code and add debug if needed :)

**Comment by danimtb** [comment]
Thanks a lot for the details. I am not sure what could be happening here. Please try again the same commands making sure you delete those packages from the cache first, use https://docs.conan.io/en/latest/reference/env_vars.html#conan-trace-file and paste the traces here (mangle the names if needed). I hope that give us enough hints 🤞

**Comment by starsoup** [comment]
The issue went away after I cleared everything. It was odd because conan printed that the recipe was not changed (conan export) but after deleting the cache and re-starting everything it works like expected.

**Comment by danimtb** [comment]
Thanks for coming back with your feedback. I'm glad you made it work but please do not hesitate to report if you are stuck in this situation again. Than you 😄
