### ISSUE TITLE
[suggestion] Definition of [multiple] export targets for a package

### ISSUE THREAD

**Issue by NightNord** [conan-io/conan#6729]
Hello,

I am trying to use conan as third-party package provider for game development and I am facing two separate and yet similar issues

1. There is no way to get/generate a cmake target for an installed "tool"/executable package.

Right now the only way to "export" an executable is to provide `PATH` change, which doesn't work if you need multiple versions of a package with executable named same way

Example:
- using both python2 and python3. You can't use just "python"
- using code generators like protobuf's `protoc` for different versions. Same, you can't just call a `protoc` - there are multiple versions of it

2. There are packages (like protobuf, dxc, glslang) that provide code-generators/compiler and otherwise tools that are bound to the libraries built by the same package. Those tools and libraries are usually tightly coupled and it makes no sense to split them into multiple packages 

AFAIK, the way to solve those both problems (sorta) is demonstrated by https://github.com/bincrafters/conan-protobuf - an intricate dance with two package definitions in the same package, configurations and custom build scripts, all of which rely on already existing protobuf's cmake integration that is also patched during build.

And for packages that do not provide existing cmake integration (that is - almost all of the third-party used in games) out of the box, you'll have to write one yourself, at which point you can also just pack it up and put it on the remote server, skipping the whole conan thing all-together - at least in game development cross-package dependency is not such a big deal, as your set of third-parties is well-defined and stable.

But considering that conan already supports cmake targets, maybe it would be possible to provide a way to export multiple "subtargets" in a similar `package_info` way as it's done now. Those subtargets will get transformed into `CONAN_PKG::MyPackage::MyTarget` cmake target - which would allow to make them more detailed/differentiate their types and specify the sole "executable" property of a target that will bind target to an executable

**Comment by memsharded** [comment]
Hi @NightNord 

I think you are talking about the "components" feature, which just started its development. The first part (basic model) just was merged, and will be in next 1.24:
- https://github.com/conan-io/conan/pull/6653

After that, there are planned further developments, like automatically resolving the internal order (https://github.com/conan-io/conan/issues/6716) and extend the model to be used by consumers:
- https://github.com/conan-io/conan/issues/6717

Please have a look, and if this is the feature you are interested in, you could close this issue and follow up there. Thanks for the suggestion!

**Comment by NightNord** [comment]
That is indeed (together with the exe part) what I wanted. Sorry for mislooking it - I searching by targets and modules and forgot it's called components in cmake. I'll close the issue then. Thank you for the link!
