### ISSUE TITLE
[question] How to install conan package on a embedded device?

### ISSUE THREAD

**Issue by niecore** [conan-io/conan#6736]
How to install conan package on a embedded device?

I want to use conda to deploy binaries on a embedded target which has no python environment.
What would be the best way to install the packages on the embedded device?

Is installing via SSH possible or is there a ~~conda~~ conan client which has low disk footprint and can run for instance on armv7?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @niecore 

Conan cannot deploy remotely (as a built-in feature). Conan is mostly intended as a package manager for development, not for deployment. It has features like the ``imports()``, ``deploy()`` and generator ``-g deploy`` to help getting things from the Conan cache and copy them to user folder or other destinations. Maybe the ``deploy()`` method you can run there a ``self.run("ssh ...`` or ``scp``, at the end of the day it is running python.

> Is installing via SSH possible or is there a conda client which has low disk footprint and can run for instance on armv7?

I guess you mean Conan and not conda. If there is no python in the target, you could try creating a Conan self contained executable with the ``pyinstaller.py`` file in the root of the repo. But probably it is easier to try some of the above ideas.

**Comment by niecore** [comment]
Thank you :)
