### ISSUE TITLE
[bug] Range resolver stops after first remote

### ISSUE THREAD

**Issue by tirolerstefan** [conan-io/conan#6743]
* Operating System+version: Ubuntu 18.04
  * Conan version: 1.24.0-dev
  * Python version: 3.6.9

I have a problem when using `conan export-pkg` with more than 1 remote.

Here is my situation:

- Package A requires B with following line:
`self.requires("B/[>=6.1.0 <7.0.0, include_prerelease=True]@user/stable")`
- Remote[0] "PRE" repo has packages B of version 7.x.x and upwards
- Remote[1] "RELEASE" repo has packages B of version 6.x.x and 7.x.x

Executing export-pkg now tries to resolve the requirements.
I analysed the code and checked behaviour with prints.

1) class RangeResolver::_search_remotes is executed with the "remotes" as argument
2) The remotes are iterated
3) For the first remote PRE, this method is executed:  
```
_remote_manager.search_recipes(remote, search_ref.name, ignorecase=False)
```
4) Because remote 0 (PRE) has packages of "search_ref.name" = B, it will return some packages. But of course, the packages for the required range are not contained.
5) Check for a valid search_result is true
6) _search_remotes returns the search result of remote 0, remote 1 is never asked, again.
7) The resolver exits with error "ERROR: Version range '>=6.1.0 <7.0.0, include_prerelease=True' from requirement ...could not be resolved in remote"

Wished behaviour:

Please check all remotes for all packages of required name ("B"), accumulate to list "search_result" and get the correct package from the correct remote.
The problem is that currently a tuple of (search_result, remote.name) is returned. I thought of changing this to a dict(remote.name->search_result), looping this dict in the resolver.

**Comment by tirolerstefan** [comment]
added a quick fix for above issue, please review.

**Comment by memsharded** [comment]
Hi @tirolerstefan 

As a first, quick feedback, this is the current behavior of Conan, and attempting to change this will probably be breaking other users. Conan range-resolving is not designed to be resolving ranges in different remotes, and going down this way could probably result in more undefined behavior. For example, why if a requirements ``pkg/[>1.0 <2.0]`` resolves to ``pkg/1.1`` in remote A, when there is a more modern ``pkg/1.2`` in remote B? Attempts to resolve this will probably result in much slower dependency resolution, which can be a blocker for many Conan users having very large dependency graphs.

So it seems the current logic needs to be maintained: When range-resolution is resolving dependencies for package ``pkg`` it will iterate remotes for it. If ``pkg`` is found, that remote will be used as the origin for package ``pkg``.

What I would suggest as a possibility, if you have different versions of the same package in different remotes, is to not translate that complexity into clients. You might try to use a virtual repository in Artifactory that aggregates the different repositories containing the versions.

**Comment by tirolerstefan** [comment]
The problem for virtual repositories with Artifactory - this needs conan revisions enabled. And this is still an experimental feature and there is only little support in Artifactory, yet.

**Comment by jgsogo** [comment]
_Revisions_ is indeed an experimental feature, but it's been for long in Conan without changes and there are many users using it in production. We are quite happy with the implementation and I'm sure we will do our best to not break it.

The way version ranges are resolved right now is the same way `conan install` works (or the last revision is retrieved) and we cannot change this behavior without really breaking. This is something we can consider for Conan v2.x, but not before that.

**Comment by tirolerstefan** [comment]
Thanks for your quick answer!

> As a first, quick feedback, this is the current behavior of Conan, and attempting to change this will probably be breaking other users. Conan range-resolving is not designed to be resolving ranges in different remotes, and going down this way could probably result in more undefined behavior. For example, why if a requirements `pkg/[>1.0 <2.0]` resolves to `pkg/1.1` in remote A, when there is a more modern `pkg/1.2` in remote B? Attempts to resolve this will probably result in much slower dependency resolution, which can be a blocker for many Conan users having very large dependency graphs.

Ok, I understand. You think about performance issues in dep. resolution.

To respond to your example above. In my humble view, there is only a pool of packages out there, defined by some remotes. So, I thought, dependency resolution is just collecting packages over n remotes, throwing them into one pool and doing some operations on it. 
In your example above and in my opinion, the requirement must be resolved to `pkg/1.2`, because it is in the pool of available packages the one with the highest version.

If you consider performance issues, you could give my change a chance and check the performance. I think, module semver is highly optimized for that.

**Comment by tirolerstefan** [comment]
Another solution could be to provide remotes to the `conan export-pkg` commands. So, one can decide to use `-r all` or not.
Another another :-) possibility is to completely ignore requirements for `conan export-pkg`. We are just packaging data others use. So, why do I (as producer) need to resolve requirements during packaging?

**Comment by memsharded** [comment]
> Another solution could be to provide remotes to the conan export-pkg command. So, one can decide to use -r all or not.

If the package you are creating has dependencies, in order to build it locally, it will need those dependencies. When you do ``conan install`` to get its dependencies, you can already specify the remotes if you want. Then, the ``export-pkg`` will use things as found in the cache, things will be resolved there.

> Another another :-) possibility is to completely ignore requirements for conan export-pkg. We are just packaging data others use. So, why do I (as producer) need to resolve requirements during packaging?

Because you need to compute the package-ID of the binary you are creating. The package-ID depends on settings, options, and also requirements. Depending on a different version of a dependency can result in a different package-ID. So for ``export-pkg`` it is necessary to compute the full dependency graph of the dependencies, to be able to compute that package-ID.

**Comment by tirolerstefan** [comment]
I see. So in my case the only possibility would be:
* `conan install --no-import .`
* create my binaries
* `conan export-pkg ...`

**Comment by memsharded** [comment]
Conan 2.0 range-resolution with ``--update`` will iterate all remotes looking for the very latest among all of them.

Closing this ticket as solved.
