### ISSUE TITLE
[suggestion] download and unzip bundle like tools.get for exports_sources

### ISSUE THREAD

**Issue by Prhmma** [conan-io/conan#6747]
Hi there,
I did a quick look at the code and find out there might be a little feature gap.
unlike `tools.get` which perform as a higher-level handler for `download` to perform `unzip` after downloading packages.
I think such a feature is needed with the `exports_sources` option, so after `conan install` for packages that bundled with `export_sources` option, it can be unzipped properly.
if there is an existing workaround for this, it would be great if you guide me through that, and if there is no such thing, I will be more than happy to contribute.
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @Prhmma 

I don't get what you mean. Files matched by the `exports_sources` attribute are zipped and uploaded to the server together with the recipe. Can you share with us a detailed example to illustrate your suggestion? Thanks!

**Comment by Prhmma** [comment]
Hi, @jgsogo 
When you use `tools.get`, downloading and unzipping done sequentially without any problem,  but when using `exports_sources` zipped packages will not unzip automatically, just downloaded and remain as zip file.

**Comment by jgsogo** [comment]
...but the files declared in the `exports_sources` and the `tar.gz` file are handled automatically by Conan and the user doesn't need to do anything with them. Conan copies them to the cache, Conan zip them and upload them, Conan knows how to retrieve them and Conan unzip them if needed.

What are you trying to do/doing with the `exports_sources`? Can you share with us some code to have a look at it?

**Comment by Prhmma** [comment]
I have a directory like this:
```
dir-
    |_somePackage.rar
    |_conanfile.py
```
in my conanfile i have configured `exports_sources="*"`
my export path in artifactory will look like this:
```
export-
     |_conan_source.tgz-
         |_somePackage.rar
         |_conanfile.py
```
`conan install` will unzip `conan_source.tgz` not `somePackage.rar`.
I think since it does extra zipping in the upload process, may need another extra unzipping to end up with desired result

**Comment by jgsogo** [comment]
Given your project, Conan is working the same as it would work with any other recipe: Conan creates a `tgz` to upload the `exports_sources` and Conan untars the `tgz` after downloading the files from Artifactory, so your recipe can work with those sources whatever the format they have.

The files in the Artifactory repository should be accessed using only the Conan protocol with a Conan client. They are not intended for any other kind of manipulation.

Maybe, it would be easier if you can tell us what you are trying to achieve, how your recipe looks like and why are you inspecting the files in Artifactory. Is it possible? If there is any sensible data, you can write to us to info@conan.io too.

Thanks!

**Comment by memsharded** [comment]
Closing this as not followed up by the OP, please re-open or create a new ticket if necessary for any further comment. Thanks for your feedback.
