### ISSUE TITLE
[question] Conan home using Cygwin

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6751]
I'm copying my comment here https://github.com/conan-io/conan/issues/6660#issuecomment-604964507

1. Using _Cygwin - Conan_ inside Cygwin (**installed with the Cygwin python**):
   * By default Conan uses home as `/home/<user>` and will put the `short_home` in the user home like `/home/<user>/.conan_short`. 💚 
   * If the user is forcing Conan to use the same cache as the Windows one, the user needs to set `CONAN_USER_HOME=/cygdrive/c/Users/<user>` and Conan will use the same short_home as the Windows one: `/cygdrive/c/.conan`. 💚 
   * If using `CONAN_USER_HOME=C:/Users/<user>`, Conan fails (see note (1) below) 🔴 

2. Using _Windows - Conan_ inside Cygwin (**installed with the _native_ Windows python**):
   * By default, Conan will use `C:\cygwin64\home\<user>\.conan` as Conan home (see note (3) below) and Conan will place the short_paths into `C:\.conan` 💛  
   * If using `CONAN_USER_HOME=/cygdrive/c/Users/<user>`, it fails (see note (2) below) 🔴 
   * If using ` CONAN_USER_HOME=C:/Users/<user>` it works, Conan will use `C:/.conan` for short_paths 💚 

Using `CONAN_USER_HOME_SHORT` environment variable, Conan skips a lot of logic, we can expect bugs/issues associated with it, probably we cannot cover all the casuistics.

---

Note.- 
 1. Conan-Cygwin running in Cygwin: using `CONAN_USER_HOME=C:/Users/<user>` fails because Conan requires an absolute path and it isn't from the unix perspective.

 2. Conan-Windows running in Cygwin:  using  `CONAN_USER_HOME=/cygdrive/c/Users/<user>` fails because Conan will compute the home like `C:\cygdrive\c\Users\<user>\.conan` and it is not a valid path.

 3. Conan-Windows running in Cygwin: it will detect the Conan user home like `C:\cygwin64\home\<user>\.conan` which is `/home/<user>`. Is it expected? Should it return the path to `C:/Users/<user>`?
    IMO, if it uses the Unix-home, it should use the `/home/<user/.conan_short` too. But, I'd prefer it if Conan uses the Windows-home.

**Comment by jgsogo** [comment]
According to Cygwin this is expected: https://cygwin.com/cygwin-ug-net/using.html

> The Cygwin DLL supports both POSIX- and Win32-style paths. Directory delimiters may be either forward slashes or backslashes. Paths using backslashes or starting with a drive letter are always handled as Win32 paths. POSIX paths must only use forward slashes as delimiter, otherwise they are treated as Win32 paths and file access might fail in surprising ways.

although it is strongly discouraged:

> Although the Cygwin DLL supports Win32 paths, not all Cygwin applications support them. Moreover, the usage of Win32 paths circumvents important internal path handling mechanisms. This usage is therefore strongly deprecated and may be removed in a future release of Cygwin. See the section called “Using native Win32 paths” and the section called “Using the Win32 file API in Cygwin applications” for more information.

**Comment by memsharded** [comment]
These scenarios no longer seem an issue, so closing this.

If you still have issues with Conan and Cygwin, please open a new ticket.
