### ISSUE TITLE
[bug] Issue with propagation of options in build_requirements

### ISSUE THREAD

**Issue by hebaishi** [conan-io/conan#6759]
### Environment Details (include every applicable attribute)
  * Ubuntu 16.04
  * GCC 7.2
  * 1.23.0
  * Python version: 3.5.2

### Steps to reproduce (Include if Applicable)
When a `conanfile.py` contains the following `build_requirements` method:
```python
def build_requirements(self):
  self.build_requires('foo/1.1.0')
  self.options['foo'].shared = False
```
The recipe incorrectly depends on a version of `foo` with the default `shared` option. So in the `foo` recipe, if the default option is `True`, the options line doesn't work, and the recipe depends on `foo` with `shared=True`. Since there is no `build_options` property, I would assume that setting options using `self.options` should affect both `requirements` AND `build_requirements`. Is that not the case?

Just as a side note, replacing the block above with the following works fine:

```python
def requirements(self):
  self.requires('foo/1.1.0')
  self.options['foo'].shared = False
```
i.e. The recipe depends on `foo` with `shared=False`
### Logs (Executed commands with output) (Include/Attach if Applicable)

Not applicable.

**Comment by memsharded** [comment]
The options values should not be defined in the ``requirements()`` or ``build_requirements()`` methods. Have you tried setting the value in the ``configure()`` method instead?

**Comment by hebaishi** [comment]
Yes that works perfectly. Thank you so much.
Does the latest version of conan print a warning when the user tries to do this?
Something along the lines of: setting options outside the configure method is wrong
Do you think it would be sensible to add that to conan if not?

**Comment by memsharded** [comment]
> Does the latest version of conan print a warning when the user tries to do this?

We are starting to add errors under the new CONAN_V2_MODE env-var, but no, this is still not there. It is a good addition for it @jgsogo

**Comment by jgsogo** [comment]
Yes, this is something we should take care of in `CONAN_V2_MODE`  (I've added it here: https://github.com/conan-io/conan/issues/6664#issuecomment-606075799). Not sure which could be the best way to implement it: access to `options` is required, only modification is forbidden (I need a `const`!!)

**Comment by memsharded** [comment]
Yes, protecting only the setters might be more difficult, indeed. Don't overengineer, only if it is relatively straightforward.

**Comment by jgsogo** [comment]
I'm closing this issue, nothing to change in Conan itself.

Shall we improve the docs with this feedback?

**Comment by memsharded** [comment]
> Shall we improve the docs with this feedback?

A couple of lines would be nice, but not critical, maybe can be improved in Conan 2.0.
