### ISSUE TITLE
[feature] On-the-fly configuration for 2.0

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#6761]
Following the discussions in Slack, I'd like to propose an optional extra configuration file for conan that can be stored per-repo. 

## Rationale

As explained by @memsharded, Conan 2.0 will try to get rid of most environment variables and move all configuration to conan.conf instead. Getting rid of environment variables without an alternative would make our lives a tad more difficult. We are by no means an "enterprise", but our use-case is typically what is referred to as "the enterprise use-case" of conan:

  * We have a monorepo of recipes that we implemented ourselves
  * We have full control over the installation of conan
  * We can assume that all recipes behave well (in the sense that they don't break each other in any way)

We have a bootstrap script that installs conan into a user-level directory and creates a wrapper script in the current build directory to run this installation. Along with some environment variables that it sets. The conan version and these environment variables vary from repo-to-repo in our organization. So for us, a user level config is global. 

Technically, we could call `conan config get` to capture the current values, and then `conan config set` to apply the repo-level config (which is in the environment currently), and then once again `conan config set` to restore at the end of the conan run. But there are some problems with this approach:

  * `conan config` is really quite slow and doesn't scale well for multiple settings. The above workaround would need three `conan config` calls per setting per conan run.
  * Lots of implementation complexity in a wrapper that we would prefer to simplify instead of adding to it.

## Proposal

Add an environment variable `CONAN_EXTRA_CONFIG` which takes a filename. Apply any configuration from that file on top of the current configuration, on-the-fly, right after the configuration was loaded. These settings should not be saved, only applied at runtime. This basically mimics the above workaround, but with substantially less overhead and complexity.

## Concerns

Reflecting on the Slack discussion, I'd like to address some possible concerns as well.

### Recipe portability

Since we control all settings in the repo, we can make sure that we only set configuration on-the-fly that keeps our recipes portable. 

### Some recipe setting CONAN_EXTRA_CONFIG on its own

We control all our recipes so we can ensure that they won't do that. But I'm also proposing to only read this environment at the start of the conan run, so theoretically a recipe should not be able to cause any trouble like that. There could be an value in the configuration to opt-in to the on-the-fly configration feature, so OSS use-cases could assume it's disabled.

--- 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this was followed up back then.

I am gathering requirements of the "workspace 2.0" feature in https://github.com/conan-io/conan/issues/15992, I think this will mostly be a "workspace" feature, better controlled by workspace file than an env-var.

I am closing this one, please lets follow up on https://github.com/conan-io/conan/issues/15992

**Comment by memsharded** [comment]
The new Conan 2 ``Workspace`` feature is already out there. Please give it a try, and create new tickets for any question, issue or suggestion.

It is in incubating: https://docs.conan.io/2/incubating.html, so please give your feedback in https://github.com/conan-io/conan/issues/18263 even if everything works smoothly and you have no other comments. Thanks for your feedback!
