### ISSUE TITLE
Running conan with Windows SYSTEM account

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#677]
Run into some trouble today while updating my clients and server to 0.15.0 and thought I would share the experience. Maybe it results in some update to documentation or behavior improvements (even though I can't come up with something for the latter).

I'm running conan on our buildserver. It is invoked by the Windows SYSTEM account. The central problem is that this user is not storing its profile in C:\Users, but in C:\Windows\SysWOW64\config\systemprofile for 32-bit applications or C:\Windows\System32\config\systemprofile for 64-bit applications. The last versions of conan all seem to have been 32-bit builds and the conan data was stored in SysWOW64. Due to this, all of my builds were running properly. However, the latest conan version seems to be a 64-bit build, since conan now uses the System32 folder. This change caused all my builds to break with compile errors stating that include files from conan packages could not be found, even though the proper path was in the projects include path (the System32 one). I'm not 100% certain about the reason, but my guess is that the tools on the build server are all 32-bit, including Visual Studio, and when a 32-bit application accesses C:\Windows\System32 it is automatically redirected to C:\Windows\SysWOW64.

I have fixed this in my setup by simply changing the storage path in conan.conf to C:\conan_data. Not sure if there is any better way to fix this.

**Comment by lasote** [comment]
@Blubbz0r thanks for reporting. It seems to be the same issue reported by @annulen #654 . I will try to see what is happening. It's very rare because the installers are always generated with the same environment.

**Comment by lasote** [comment]
@Blubbz0r I've regenerated the installer: https://github.com/conan-io/conan/releases/download/0.15.0/conan-win_0_15_0.exe 
Please try now and tell me if it still fails. Thank you very much

**Comment by digitalcircuit** [comment]
It's possible regenerating the installer caused some other issues.  I've filed [issue #706](https://github.com/conan-io/conan/issues/706 ) to document this.

**Comment by claudiusaiz** [comment]
I can confirm this is happening in Conan 2.0 as well.

The takeaway is that if you're running Windows 32-bit builds as the SYSTEM user, make sure to set the `core.cache:storage_path` option in `C:\Windows\System32\config\systemprofile\.conan2\global.conf` to a custom path that is not inside `C:\Windows\System32`

**Comment by memsharded** [comment]
Actually, the best approach would be to set the ``CONAN_HOME`` env-var, to point the whole Conan home to a folder outside ``C:\Windows\System32``
