### ISSUE TITLE
[bug] cpp_info.exelinkflags and cpp_info.sharedlinkflags are both included regardless of target type for CMake

### ISSUE THREAD

**Issue by hardsetting** [conan-io/conan#6779]
I'm trying to add a transitive linker flag to my conan package, but wanted to restrict this only to executables. I stumbled upon the [cpp_info.exelinkflags attribute](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info) and reading the documentation I was under the assumption that it did exactly that.

In my conanfile.py:
```
def package_info():
    self.cpp_info.exelinkflags.extend(['-Wl,--unresolved-symbols=ignore-in-shared-libs'])
    # ...
```
But inspecting the generated `conanbuildinfo.cmake` for a consumer using the CMake generator, i noticed that this was the result:

```
# Property INTERFACE_LINK_FLAGS do not work, necessary to add to INTERFACE_LINK_LIBRARIES
set_property(TARGET CONAN_PKG::embedded-shared PROPERTY INTERFACE_LINK_LIBRARIES
${CONAN_PACKAGE_TARGETS_EMBEDDED-SHARED}
${_CONAN_PKG_LIBS_EMBEDDED-SHARED_DEPENDENCIES}
${CONAN_SHARED_LINKER_FLAGS_EMBEDDED-SHARED_LIST}
${CONAN_EXE_LINKER_FLAGS_EMBEDDED-SHARED_LIST}
...
)  
```
Effectively, both exelinkflags and sharedlinkflags are included transitively, regardless of the target type.

As a test, by manually changing the conanbuildinfo.cmake section to:
```
set_property(TARGET CONAN_PKG::embedded-shared PROPERTY INTERFACE_LINK_LIBRARIES
${CONAN_PACKAGE_TARGETS_EMBEDDED-SHARED}
${_CONAN_PKG_LIBS_EMBEDDED-SHARED_DEPENDENCIES}
$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${CONAN_SHARED_LINKER_FLAGS_EMBEDDED-SHARED_LIST}>
$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${CONAN_EXE_LINKER_FLAGS_EMBEDDED-SHARED_LIST}>
``` 
I got the behavior that I expected.

Am I misunderstanding the purpose of those flags? If not, would my solution be a viable one?

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: gcc 7.5
  * Conan version: 1.20
  * Python version: 3.6

### Steps to reproduce (Include if Applicable)
In the `package_info()` step of a conanfile.py, add the following line:
```
self.cpp_info.exelinkflags.extend(['-Wl,--unresolved-symbols=ignore-in-shared-libs'])
```
When consuming the package with a CMake generator, the flag '-Wl,--unresolved-symbols=ignore-in-shared-libs' will be added also to libraries.

**Comment by jgsogo** [comment]
Hi, @hardsetting 

Really nice catch and nice fix! 😃 Do you want to submit a PR? Probably this is something to add not only to the `cmake` generator, but also to the `cmake_find_package` one (and the `_multi` versions). Yes, source code around those classes is a bit.... well, we need to refactor it.

Thanks!

**Comment by hardsetting** [comment]
Hi @jgsogo, sure. I've created a small PR that addresses this. Not sure how to handle the other generators you've mentioned but I can take a look later.
