### ISSUE TITLE
Error handling guideline for conanfile.py and customized class

### ISSUE THREAD

**Issue by NingyuShi** [conan-io/conan#678]
I'm writing some customized command line generator for bazel, and need to do some error handling. What's the recommended way to do this? Customized exception handling? How do we do an error out in one of these source/build funciton?

**Comment by lasote** [comment]
Hi @NingyuShi you can raise a normal Exception("message you want") in the source/build function. 
Conan will capture the error and will print the error line in your conanfile.py and then will stop the execution.
Does it work for you?

**Comment by memsharded** [comment]
Besides raising Exceptions, you also have access to ``self.output`` which can be used for ``info, success, warn, error`` and even ``werror``, that will raise if the ``--werror`` argument is passed in the command line.

Have you progressed in your customized generator? Any specific suggestion or feature request we could do to help?
