### ISSUE TITLE
[feature] Separate build profiles for different packages

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#6783]
Suppose I have Conan packages `cmake` and `clang`. Now when building other code I want to use package `cmake` built in debug mode while using package `clang` built in release mode.

That would require using different build profiles for different `build_requires` which, looks like, is not possible as of Conan 1.24.

As a bonus feature, what about default build profiles? If package or profile `build_requires` package `foo`, check if profile `default_build_foo` exists and use it for that package. This will allow people to create profiles `default_build_cmake`, `default_build_gcc`, `default_build_clang`, etc to have global control of the configuration of their build tools.

**Comment by Minimonium** [comment]
I see that you have a very specific problem - using different settings for different requirements. 

With the old model, we can overwrite specific settings for specific requirements with, for example, a `-s foo:build_type=Debug`. 

With the new model, we can do the same with appropriate arguments, for example, like `-s:b foo:build_type=Debug`.

Adding a client-machine dependent feature seems like a hack, honestly.

**Comment by jgsogo** [comment]
Hi! Honestly this is something I haven't tried yet 😞 

Are you going to try it? Can you report if those settings are properly assigned to the packages? It should work using the CLI as @Minimonium suggested, but the same syntax should work [inside a profile file to assign settings per package](https://docs.conan.io/en/latest/reference/profiles.html?highlight=profiles#package-settings-and-env-vars).

Thanks!

**Comment by AbrilRBS** [comment]
Closing as won't do - The feature you're looking is the one proposed by Alexandr, where in the _same_ profile, you have scoped settings for each package, i.e:
```
[settings]
foo:build_type=Debug
```

Thanks a lot everyone for your input :)
