### ISSUE TITLE
conan support of "llvm" and "ClangCL" toolchains for Visual Studio  

### ISSUE THREAD

**Issue by aegis-dev** [conan-io/conan#6789]
Hello,

I am trying to compile one of my projects with llvm toolchain and I got blocked by conan. I was trying to pre-build missing conan dependencies with such profile:

```
[build_requires]
[settings]
    os=Windows
    os_build=Windows
    arch=x86_64
    arch_build=x86_64
    compiler=Visual Studio
    compiler.version=15
    compiler.cppstd=14
    compiler.toolset=llvm
    build_type=Debug
[options]
[env]
```

However, results are like that:
```
conan install boost/1.69.0@conan/stable --build=missing --profile=vs_llvm
ERROR: Invalid setting 'llvm' is not a valid 'settings.compiler.toolset' value.
Possible values are ['LLVM-vs2012', 'LLVM-vs2012_xp', 'LLVM-vs2013', 'LLVM-vs2013_xp', 'LLVM-vs2014', 'LLVM-vs2014_xp', 'LLVM-vs2017', 'LLVM-vs2017_xp', 'None', 'v100', 'v110', 'v110_xp', 'v120', 'v120_xp', 'v140', 'v140_clang_c2', 'v140_xp', 'v141', 'v141_clang_c2', 'v141_xp', 'v142', 'v90']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

As I understand these valid toolchain values are pre-hardcoded somewhere in the conan and could be expanded with "llvm" and "ClangCL".

"llvm" comes from https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain and is supported in VS17.
"ClangCL" comes from official VS19 clang support.

Thanks in advance!

Best regards

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

The new build system integrations and settings did a better, more explicit modeling of Windows-clang, see for example https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html

Closing this ticket as outdated, please create new tickets as necessary, thanks for your feedback.
