### ISSUE TITLE
[feature] Raise ConanInvalidConfiguration from recipes constraining settings

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6802]
From here: https://github.com/conan-io/conan/issues/6534

When a recipe is constraining the settings, it should raise a `ConanInvalidConfiguration` if the value provided doesn't satisfy the values allowed by the recipe:

```python
class Recipes(ConanFile):
    ...
    settings = {"os" : ["Windows"]}
```

Right now the output is a regular error that is pointing to a misleading Q&A

```
ERROR: Error while initializing settings. Invalid setting 'Macos' is not a valid 'settings.os' value.
Possible values are ['Windows']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

**Comment by jgsogo** [comment]
Conan is capturing and raising again the exception as `ConanInvalidConfiguration` 🎉 

https://github.com/conan-io/conan/blob/cf4cab6f9fc95ada3b69796f6de615b4d79ed1ff/conans/model/conan_file.py#L71

Here only the message with the link is misleading.

**Comment by memsharded** [comment]
> Here only the message with the link is misleading.

I think the problem is that this message is common also for the case when settings are initialized with wrong values from dowsntream (profiles), so might not be straightforward to change that message, but the exception to be captured in Settings class.

**Comment by jgsogo** [comment]
It should be easy to update the message in the linked line just to say that the recipe is constraining the settings, it is not something in the `settings.yml` file. Or maybe it is enough to update the docs Q&A section to tell about this situation causing this error. Anyway, if we add this issue to a release, it should be quite straightforward to improve the message and/or docs.

**Comment by sdmg15** [comment]
Hello @memsharded  and @jgsogo  I would like to work on this issue :)

**Comment by jgsogo** [comment]
You are welcome, @sdmg15 ! Waiting for the pull-request, let us know if you need any help.

Thanks!
