### ISSUE TITLE
VS runtime: 'static' and 'shared' instead of 'MTd'/'MT'/'MD'/'MDd'

### ISSUE THREAD

**Issue by a-teammate** [conan-io/conan#681]
This is a problem already discussed in #475:

If you specify `-s build_type=Debug` (switching from Release) you remain with the runtime 'MT' (instead of the appropriate debug runtime) which will almost certainly result in incompatibility issues and linker issues.

There is a proposed generic solution for this in #271.
It feels like a workaround though, since the solution would be to straightforwardly switch between the 2 options you need: "static" vs "shared" runtime linkage. Theres nothing else.

Internally we would need to do the switch ofc between the debug and release version of those runtimes.

This may hide the fact that VS internally gives them different names.   
Furthermore it will probably break compatibility of a lot of existing packages which check for "MT" as runtime, but the question is whether waiting to introduce this fix will better anything.  
Plus my impression is that the conan community is pretty flexible at solving shit, so I think if it gets communicated well enough this can still be fixed (since the community isn't nearly as big as it will be in 1-2 years. looking at PMs of other languages/distros growth has initially often been exponential. So if we fix it, we need to do it now).

**Comment by memsharded** [comment]
While it is true that in many cases using the wrong runtime will lead to link errors (or even worse, runtime errors), I am not sure that conan should restrict that. Microsoft or even Visual Studio don't restrict choosing the wrong runtime, so there might be some use cases for that, even if rare. Conan tries its best not to have to decide or force the user to something by being "too smart".

Plus as you said, changing that setting will basically break all existing Windows packages, unless we internally did some trick/hack in the computation of the hash.

I'd say that conan provides some mechanism to avoid that right now: profiles. With profiles you can define your "Debug" profile, to make sure it uses the right "MTd" runtime, so you don't forget to set it. And same for release.

I wouldn't be opposed to add extra check and raise warnings to the user, even "werror" warnings that could be raised as errors if the user wants to check for them.

What do you think? I'd also appreciate the feedback of @lasote here if possible.

**Comment by lasote** [comment]
Warnings are welcomed, but I think we shouldn't change the runtime automatically. Maybe profiles can help you to control better the settings.

**Comment by a-teammate** [comment]
Yes, it seems reasonable not to be too smart in this area.

My problem is more that I'd like to hide that complexity from the regular dev who isn't aware of most of the build-system (and especially not this runtime linkage stuff).
(And why tell everyone to execute some particular steps if you can just remove the necessity of them)

So a solution for me could be to simply create some scripts for the different stuff (build_debug.bat/create_vs_debug_project.bat) or to share some profile-files the people need to install to their conan-directory.  
But since most conan VS-users will run into this particular error **a lot** I thought it may be better to solve it here.

I don't think distributing profile-files with conan is a solution either though..

I haven't yet had time to invest the use-case of where one want to link against the debug runtime in a release build (and how to make that work, since it normally wouldn't build).

**Comment by sixten-hilborn** [comment]
If you want to hide conan details from "the regular dev" you could have a look at [conan.cmake](https://github.com/conan-io/cmake-conan) in case you are using CMake. It will detect VS runtime flags from CMake and forward them to Conan.

**Comment by lasote** [comment]
I think this issue could be closed. We introduced (many many versions ago) a feature where if no runtime is specified, conan will automatically use the one accordingly to the build_type. Sorry for not reporting sooner!
