### ISSUE TITLE
[bug] zlib override doesn't work

### ISSUE THREAD

**Issue by sinall** [conan-io/conan#6812]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows10
  * Compiler+version: MSVC-2019
  * Conan version: 1.24.0
  * Python version: 3.7.0

### Steps to reproduce (Include if Applicable)
profile:
```
[settings]
arch=x86
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=14
os=Windows
os_build=Windows
arch_build=x86
```

conanfile.py
```
from conans import ConanFile

class MyConan(ConanFile):
	settings = "os", "compiler", "build_type", "arch"

	requires = (
		"openssl/1.1.1d",
		"boost/1.71.0@conan/stable",
		"cpprestsdk/2.10.14@bincrafters/stable",
		"libzip/1.5.2@bincrafters/stable",
		"bzip2/1.0.8@conan/stable",
		("zlib/1.2.11@conan/stable", "override"),
		"gsl_microsoft/2.0.0@bincrafters/stable",
		"tesseract/3.05.01@bincrafters/stable",
		"sqlcipher/4.3.0", # Caused by this line
	)

	generators = "visual_studio"

	default_options = (
		"libzip:shared=True",
	)

	def imports(self):
		self.copy("*.dll", "..\\..\\" + str(self.settings.build_type), "bin")

```

### Logs (Executed commands with output) (Include/Attach if Applicable)

> WARN: openssl/1.1.1d: requirement zlib/1.2.11 overridden by your conanfile to zlib/1.2.11@conan/stable
> WARN: cpprestsdk/2.10.14@bincrafters/stable: requirement zlib/1.2.11 overridden by your conanfile to zlib/1.2.11@conan/stable
> WARN: cpprestsdk/2.10.14@bincrafters/stable: requirement boost/1.71.0 overridden by your conanfile to boost/1.71.0@conan/stable
> WARN: websocketpp/0.8.1@bincrafters/stable: requirement zlib/1.2.11 overridden by cpprestsdk/2.10.14@bincrafters/stable to zlib/1.2.11@conan/stable
> WARN: websocketpp/0.8.1@bincrafters/stable: requirement boost/1.71.0 overridden by cpprestsdk/2.10.14@bincrafters/stable to boost/1.71.0@conan/stable
> WARN: libzip/1.5.2@bincrafters/stable: requirement zlib/1.2.11 overridden by your conanfile to zlib/1.2.11@conan/stable 
> WARN: libzip/1.5.2@bincrafters/stable: requirement bzip2/1.0.8 overridden by your conanfile to bzip2/1.0.8@conan/stable 
> WARN: libzip/1.5.2@bincrafters/stable: requirement openssl/1.0.2t overridden by your conanfile to openssl/1.1.1d
> ERROR: Conflict in tcl/8.6.10:
>     'tcl/8.6.10' requires 'zlib/1.2.11' while 'leptonica/1.76.0@bincrafters/stable' requires 'zlib/1.2.11@conan/stable'.
>     To fix this conflict you need to override the package 'zlib' in your root package.
> Exit code: 1
> An error occurred when executing task 'ConanInstall'.
> Error: 发生一个或多个错误。
>         conan install exception

**Comment by uilianries** [comment]
@sinall Please, use the packages from [Conan Center Index](https://github.com/conan-io/conan-center-index). Some packages listed in your recipe are totally deprecated. Use the follow packages instead:

- [zlib/1.2.11](https://conan.io/center/zlib/1.2.11)
- [boost/1.71.0](https://conan.io/center/boost/1.71.0)
- [libzip/1.5.2](https://conan.io/center/libzip/1.5.2)
- [bzip2/1.0.8](https://conan.io/center/bzip2/1.0.8)
- [ms-gsl/2.0.0](https://conan.io/center/ms-gsl/2.0.0)
- [tesseract/4.0.0](https://conan.io/center/tesseract/4.0.0)

**Comment by sinall** [comment]
@uilianries Conan center index doesn't provide x86 binaries. My application still depends on those x86 binaries.

**Comment by uilianries** [comment]
You could build those packages and run a local Artifactory to keep them. Users which requires ARM, for instance, they need to build all packages, as there aren't pre-built packages for ARM.

**Comment by sinall** [comment]
I know, but those existing packages conbination is well tested. For instance tesseract/4.0.0 has some bugs so we can not use it. I failed to build boost last time, and it took a huge time. Do you have plan to migrated those legacy packages into conan-center-index?

**Comment by uilianries** [comment]
> For instance tesseract/4.0.0 has some bugs so we can not use it.

If you need the early version, you could open an issue request such version, or just a PR updating the conandata.yml and config.yml with the new version.

> I failed to build boost last time, and it took a huge time

If the package is broken, you can open an issue reporting about.

Besides that, only CPP Rest SDK is pending, but we have a WIP: https://github.com/conan-io/conan-center-index/pull/1191

**Comment by sinall** [comment]
I forgot to mention: the error happens after I added "sqlcipher/4.3.0".

**Comment by sinall** [comment]
Just let you know, after I change `zlib/1.2.11@conan/stable` to `zlib/1.2.11`, It works now.
Don't know if `override` is only applicatable for center. Here's the working config:
```
from conans import ConanFile

class MyConan(ConanFile):
	settings = "os", "compiler", "build_type", "arch"

	requires = (
		"openssl/1.1.1d",
		"boost/1.71.0@conan/stable",
		"cpprestsdk/2.10.14@bincrafters/stable",
		"sqlcipher/4.3.0",
		"libzip/1.5.2@bincrafters/stable",
		"bzip2/1.0.8@conan/stable",
		"zlib/1.2.11",
		"gsl_microsoft/2.0.0@bincrafters/stable",
		"ths-client/2.1.0@sinall/stable",
		"tesseract/3.05.01@bincrafters/stable",
	)

	generators = "visual_studio"

	default_options = (
		"libzip:shared=True",
	)

	def imports(self):
		self.copy("*.dll", "..\\..\\" + str(self.settings.build_type), "bin")

```

**Comment by memsharded** [comment]
Hi @sinall 

Yes, the explanation of the error message:
```bash
ERROR: Conflict in tcl/8.6.10:
'tcl/8.6.10' requires 'zlib/1.2.11' while 'leptonica/1.76.0@bincrafters/stable' requires 'zlib/1.2.11@conan/stable'.
To fix this conflict you need to override the package 'zlib' in your root package.
```

Is that there are different packages using different "zlib" packages. On one branch of the dependency graph, someone is still using the old ``zlib/1.2.11@conan/stable``, while some other more modern dependency is using the newer ``zlib/1.2.11``, and that is a conflict. Specifying which of the two ones you want, the conflict is resolved. Please try to use the modern packages wherever possible.

> Do you have plan to migrated those legacy packages into conan-center-index?

Yes, the migration is happening since the new flow through https://github.com/conan-io/conan-center-index/ was established a few months ago. The old packages will eventually be gone, but in the meantime the community is working really hard to move all those previous packages to the new flow. 

I am happy to see that the issue has been solved now, it was not a bug in the Conan client, but working as expected raising a conflict, just a consequence of using conflicting old and new dependencies from ConanCenter. So I think this ticket can be closed now, thanks for reporting!

**Comment by sinall** [comment]
@memsharded Please consider the original configuration. Should it be supported?

**Comment by memsharded** [comment]
Hi @sinall 

Actually the ``arch_build=x86`` was dropped. Initially was there, but it was taking too many resources of our CI (doubling the number of binaries we build on Windows, which is the slowest one in our CI), and in practice, the usage (number of downloads) of those packages was absolutely negligible, just a very very tiny fraction compared with the ``x86_64`` ones.

If you are using Conan in production, using your own Artifactory server is still an extremely recommended practice, you will be able to put there your own binaries for your own configurations for your production system.

**Comment by sinall** [comment]
@memsharded I mean the conflict in my original post. Do you still consider it is a valid configuration and the conflict is a bug?

**Comment by memsharded** [comment]
> @memsharded I mean the conflict in my original post. Do you still consider it is a valid configuration and the conflict is a bug?

Ah, no, not a bug. It is a "defect" in the dependency graph, not in the Conan tool, or in the dependency graph algorithm. The dependencies you are using are somehow incompatible between each other, because you are mixing "old" and "new" packages from ConanCenter. If you use all dependencies without the ``@user/channel`` part, then that will not happen, because all packages will depend on ``zlib/1.2.11``. If still a conflict, then yes, that should be reported to the ConanCenter to fix the packages there. But still not a bug in the Conan tool.

**Comment by sinall** [comment]
@memsharded I'm confused by the `override` feature. I thought `override` is designed for such case, isn't it? So it only works when I use all packages from ConanCenter?

**Comment by memsharded** [comment]
> @memsharded I'm confused by the override feature. I thought override is designed for such case, isn't it? So it only works when I use all packages from ConanCenter?

The ``override`` is designed to not alter the topology of the dependency graph. In practice, it typically doesn't affect, but sure, you can specify the ``"override"`` qualifier to the ``zlib/1.2.11`` requirement declaration, the result is the same. It is not strictly for ConanCenter, but for any case when there is a conflict of dependencies, irrespective of the conflict. You can also generate a conflict of versions dependencies if you depend on your own "pkg/1.2" by some packages and on your "pkg/1.3" by some other of your own packages.

The thing is that if the packages from ConanCenter, you use only those that do not have ``@user/channel``, then it is way less likely that you will have this specific conflict of depending on different packages, some with user/channel and some without user/channel

**Comment by sinall** [comment]
@memsharded So "zlib/1.2.11@conan/stable" and "zlib/1.2.11" are different packages in Conan concept. I thought they are the same package. Maybe the document about `override` could clarify this in case people get confused.

**Comment by memsharded** [comment]
> @memsharded So "zlib/1.2.11@conan/stable" and "zlib/1.2.11" are different packages in Conan concept. I thought they are the same package. Maybe the document about override could clarify this in case people get confused.

Yes, exactly, they are completely different packages, in the same way ``zlib/1.2.8``is a different package too. They can contain different files. The idea is that you can use user/channel to create your own package, lets say for ``boost/1.72.0@mycompany/stable``, and it can contain different files, built differently, to suit your specific needs. And that package is a different one, that do not collide with the ConanCenter ``boost/1.72.0``. You could even install both, and use them in different projects to compare.

**Comment by sinall** [comment]
@memsharded Thanks for your explanation, it is much clear now. Cheers.
