### ISSUE TITLE
[feature] Alert final user if include_path (and other cpp_info directories) are not directories

### ISSUE THREAD

**Issue by vhuber** [conan-io/conan#6813]
I wrote a recipe using a requires.
The required dependancy was misconfigured and the ` self.deps_cpp_info['required'].include_paths` was set to `[]`.

An alert indicating that the dependancy was misconfigured and its `include_path` was incorrect would be time saving.

More precisely, in `build_info.py` , in `_filter_path` we call `os.isdir.path(p)` and a warning here could be more than appreciated !

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Yes, we can check that all the paths are not files, and, as the data is cached it shouldn't be a performance issue. This error will raise for the consumer, but also for the recipe creator if there is a `test_package` (highly recommended).

Thanks for the suggestion!

btw, it is also an easy pull-request if you feel like to ;D

**Comment by anubhabsen** [comment]
Hello! I would like to take this up if that's ok.
If I understand this correctly, 
```
abs_paths = [os.path.join(self.rootpath, p)
                     if not os.path.isabs(p) else p for p in paths]
```
In the above piece of code, a check needs to be performed if p is a directory, and if it's not, issue an alert with ```conan_v2_behavior()```?

**Comment by jgsogo** [comment]
Hi, @anubhabsen 

It is enough to raise a `ConanException` if any of the paths correspond to a file. We cannot check the other way around, if the path is not a folder, because the path might not exist.

Thanks! If you send the PR we can include it in the next release 1.26 👍

**Comment by memsharded** [comment]
Closing as outdated and not planned (include_paths isn't used any more either, now it is ``includedirs``). There are cases where having the paths to non existing folders is necessary, as ``editables`` too, so this wouldn't be nice for all cases.
