### ISSUE TITLE
[feature] Make the Dot Graph more readeable

### ISSUE THREAD

**Issue by alacasta** [conan-io/conan#6814]
_**As a** user, **i want to** have a clear and simple manner for reading the dependencies of a given project **to** detect misalignments in the architecture faster._

## Baground
`Conan` has two different formats for generating the output of the dependencies graph 
- `html`: providing an interactive HTML graph
- `dot`: provinging a `Graphviz-DOT` file describing the dependencies. This file is, at the same time, exportable to several formats like `png` or `svg` using `dot (graphviz`)

So far, the `dot` graph generated for conan is simple: it contains the nodes labeled as the reference package states (i.e. `pkgB/1.9.8@org/testing`). While for many use cases, the output is good enough, when the dependency graph becomes harder, the output may result also less readeable (see for instance the diagram displayed at #3267)

![image](https://user-images.githubusercontent.com/1688725/78685776-84950980-78f2-11ea-938b-8c3d4b1ab9a4.png)

There, several problems can be observed
- The graph is optimized to be as compact as possible, having 'curved' edges and many crossings at the same time
- Some edges are replicated because respecting the _real_ depndency occurency (see for instance `match` --> `concept`)

Moreover, the output can be also nicer (like the one generated in `html` for those situations where such diagram is embedded in some documentation (i.e. colorizing).

A good exampled of how i imagine the output improved was shown in the latest `1.24.0` release where _build context_ was introduced (https://docs.conan.io/en/latest/devtools/build_requires.html?highlight=build%20context#build-and-host-contexts)

![image](https://user-images.githubusercontent.com/1688725/78686748-b195ec00-78f3-11ea-943f-b46cc048f736.png)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by alacasta** [comment]
A proposal of changes to cover this feature is addressed at #6815

**Comment by memsharded** [comment]
Conan 2 improved a lot the html graph, and the ``dot`` one is still possible to use user defined templates.
Closing this as unplanned, at the moment it is not expected to improve the dot graphs, only improvements to the interactive html. Thanks for the feedback!
