### ISSUE TITLE
can you please help me to install cmake  in  windows for opencv module.

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#6817]
python setup.py bdist_wheel
Version:  4.2.0+d608d69
setup.py:85: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
  ['python/cv2[^/]*%(ext)s' % {'ext': re.escape(sysconfig.get_config_var('SO'))}],

.........................

scikit-build could not get a working generator for your system. Aborting build.

Building windows wheels for Python 3.8 requires Microsoft Visual Studio 2017.
Get it with "Visual Studio 2017":

  https://visualstudio.microsoft.com/vs/

this is the error message  iam getting. please replay asap

**Comment by memsharded** [comment]
Hi sorry, this issue report doesn't make sense at all. Please specify the Conan version you are using and the Conan commands to reproduce. I don't know how scikit-build is related to Conan at all. Closing this at the moment, can be reopened later if it is necessary.
