### ISSUE TITLE
Linker errors when linking against libcurl

### ISSUE THREAD

**Issue by AbhilashSunkad** [conan-io/conan#6818]
Trying to build  libcurl for my android environment

Compiling and linking on MAC OS
I have properly linked the following libraries.
/platform/android/openssl/libssl-android-x86_64/lib/libssl.a 
/platform/android/openssl/libssl-android-x86_64/lib/libcrypto.a 
/platform/android/curl/libcurl-android-x86_64/lib/libcurl.a 

Below are the logs .

/Users/Desktop/Projects/Android_Metrics//platform/android/curl/libcurl-android-x86_64/lib/libcurl.a(libcurl_la-md5.o):md5.c:function Curl_md5it: error: undefined reference to 'MD5_Init'
/Users/Desktop/Projects/Android_Metrics/platform/android/curl/libcurl-android-x86_64/lib/libcurl.a(libcurl_la-md5.o):md5.c:function Curl_md5it: error: undefined reference to 'MD5_Update'
/Users//Desktop/Projects/Android_Metrics/platform/android/curl/libcurl-android-x86_64/lib/libcurl.a(libcurl_la-md5.o):md5.c:function Curl_md5it: error: undefined reference to 'MD5_Final'
/Users/Desktop/Projects/Android_Metrics/platform/android/curl/libcurl-android-x86_64/lib/libcurl.a(libcurl_la-md5.o):md5.c:Curl_DIGEST_MD5: error: undefined reference to 'MD5_Init'
/User/Desktop/Projects/Android_Metrics/platform/android/curl/libcurl-android-x86_64/lib/libcurl.a(libcurl_la-md5.o):md5.c:Curl_DIGEST_MD5: error: undefined reference to 'MD5_Update'
/Users/Desktop/Projects/Android_Metrics/platform/android/curl/libcurl-android-x86_64/lib/libcurl.a(libcurl_la-md5.o):md5.c:Curl_DIGEST_MD5: error: undefined reference to 'MD5_Final'
/Users/Desktop/Projects/Android_Metrics/platform/android/curl/libcurl-android-x86_64/lib/libcurl.a(libcurl_la-md5.o):md5.c:Curl_HMAC_MD5: error: undefined reference to 'MD5_Init'
/Users/Desktop/Projects/Android_Metrics/platform/android/curl/libcurl-android-x86_64/lib/libcurl.a(libcurl_la-md5.o):md5.c:Curl_HMAC_MD5: error: undefined reference to 'MD5_Update'

**Comment by jgsogo** [comment]
Hi, @AbhilashSunkad 

If you are using `libcurl` from Conan Center (https://conan.io/center/libcurl/7.69.1/), it is better to open this issue in the `conan-center-index` repository (https://github.com/conan-io/conan-center-index). It is the place where these recipes are being maintained. I'm sure there someone will help you to improve the existing recipe.

Thanks!
