### ISSUE TITLE
[feature] access `deps_cpp_info.src_paths` in package() method

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#6823]
Until something like #4289 is implemented, I want to be able to repackage the sources of my dependencies so that I can view them while debugging the binaries of the application package.  However, it seems that the `src_paths` attribute of `self.deps_cpp_info["dep"]` is empty when called from the package method.  

Can this be made available?  

(I know that I can workaround this by first using the imports method to fetch them into the local workspace before packaging, but I was hoping to avoid this unnecessary step..)

**Comment by solvingj** [comment]
There is currently planning around features related to sources, including for debugging purposes.  I will gather tickets and link them here.

**Comment by memsharded** [comment]
Closing as outdated.
To access dependencies information the ``self.dependencies`` interface is to be used, not ``deps_cpp_info`` (deprecated in 1.X, removed in 2.0)
