### ISSUE TITLE
[question] short references are not recognized as references but patterns

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6828]
I  stumbled on this by mistake.. not really an issue for me. 

It seems that short references not recognized as references even with the `@` sign example:

```
$ conan search abc/1@
There are no packages matching the 'abc/1@' pattern
$ conan search abc/1a@
ERROR: Recipe not found: 'abc/1a'
```

```
conan --version
Conan version 1.23.0-dev
```

is this intentional?

**Comment by memsharded** [comment]
Yes, it is an annoying issue of the current command line, if it is not a reference (and 1 char versions or names are not accepted as references), it is a pattern, and it searches for recipes, not for binaries.

The new command line we are already designing will completely disambiguate this. It is already in the design for Conan 2.0.

**Comment by memsharded** [comment]
Conan 2.0 has made explicit ``conan install <path>`` and ``conan install --requires=<ref>``
Already in beta: https://docs.conan.io/en/2.0/index.html
