### ISSUE TITLE
[question] How to prevent conan-imports from copying cygwin dlls

### ISSUE THREAD

**Issue by sinall** [conan-io/conan#6829]
profile:
```
[settings]
arch=x86
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=14
os=Windows
os_build=Windows
arch_build=x86

[build_requires]
cygwin_installer/2.9.0@bincrafters/stable

```

conanfile.py
```
from conans import ConanFile

class MyConan(ConanFile):
	settings = "os", "compiler", "build_type", "arch"

	requires = (
		"openssl/1.1.1d",
		"boost/1.71.0@conan/stable",
		"cpprestsdk/2.10.14@bincrafters/stable",
		"sqlcipher/4.3.0",
		"libzip/1.5.2@bincrafters/stable",
		"bzip2/1.0.8@conan/stable",
		"zlib/1.2.11",
		"gsl_microsoft/2.0.0@bincrafters/stable",
		"tesseract/3.05.01@bincrafters/stable",
	)

	generators = "visual_studio"

	default_options = (
		"libzip:shared=True",
	)

	def imports(self):
		self.copy("*.dll", "..\\..\\" + str(self.settings.build_type), "bin")

```

`conan imports`

> conanfile.py imports(): Copied 72 '.dll' files

It copys about 70 cygwin dlls, is there a way to prevent this?

**Comment by jgsogo** [comment]
HI, @sinall 

The method `imports` in a conanfile traverse all the dependencies copying those files, but there are two scenarios with different behaviors:
 * If  your use just one profile in the `conan install` command (no profile at all, argument `--profile` or `--profile:host`) which is the _default_ way to use Conan, then all the `requires` and `build_requires` are in the same context and Conan will import all the DLLs, also the ones belonging to `cygwin` in your build_requires. There is nothing you can do to avoid that.
 * If you are already using the **new graph model in Conan v1.24 with the [`host` and the `build` profiles](https://docs.conan.io/en/latest/devtools/build_requires.html#build-and-host-contexts)** and then the `imports()` will just copy the DLLs that belong to your host context, only the DLLs your requirements and not those form the build_requirements. To use this new behavior you have to opt-in using two profiles in the CLI: `--profile:host=profile_host --profile:build=profile_build`

**Comment by memsharded** [comment]
Closing this as inactive.

Also, ``imports()`` have been removed in Conan 2.0, and more explicit ``copy()`` calls in deployers or ``generate()`` will provide more control to achieve the desired behavior.
