### ISSUE TITLE
[question] combine libraries into one

### ISSUE THREAD

**Issue by NukeBird** [conan-io/conan#6830]
Let's say I'm developing library A with dependencies B, C, D which were provided by conan (cmake approach)

And I have android project on Visual Studio which will use my library A 

But I can't just link against A since it is highly tied with B, C, D. What can I do with it?

**Comment by memsharded** [comment]
Hi @NukeBird 

I think your question is related to https://docs.conan.io/en/latest/devtools/running_packages.html, you could use the ``imports`` or ``deploy`` functionality, to get artifacts from the Conan cache and put them where you want other tools to find them. Please tell if this helps, thanks!

**Comment by NukeBird** [comment]
yes, I managed to get all the libs via

```python
    def imports(self):
        self.copy("*", src="@libdirs", dst="lib")
```
as well as with
```
conan install .. --build=missing -g deploy
```

but... how to combine them into one lib?

**Comment by memsharded** [comment]
Hi @NukeBird 

Sorry this was not followed up back then.

"Combining libraries into one lib" is not really a thing. You might link different static libraries into a shared library. It might be possible to archive kind of re-package into a static library multiple static libraries. But this is extremely unusual, I have very rarely seen this. In any case, this wouldn't be really a Conan question, but a "C/C++ libraries question", as Conan is not a build system, but a package manager.

I am closing this ticket as outdated, but please re-open or create a new ticket if you have any further question or issue. Thanks for the feedback.
