### ISSUE TITLE
[feature] conan to understand PUBLIC things exposed by underlying generators e.g cmake.

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6837]
I am sure this probably has been raised in the past and discussed about - however I couldnt find any such thread.

Usually there is a lot of logic inside the original cmakes that we are aligning to conan usage.

One has to spend literally hours sometimes analyzing what these cmakes export and in what configuration.
Which makes migrating to new versions very risky - will someone check the cmake whether it has changed etc etc?

Well - cmake exposes PUBLIC thing for a reason - maybe cmake generator should be able to extract information out of that rather than people rewriting these in the `package_info`?

If its not clear what I am thinking about - I can link few examples from `conan-center-index`.

How would this be achieved?
obviously this is tough topic but the easiest thing that comes to mind is.
in package_info you would do something like.
`cmake.inherit_publics(targets...)`

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @fulura. This is something @SSE4 suggested time ago for pkg-config, I'm sure he remembers the issue and there we can find more meaningful comments.

This has some drawbacks: this would be at runtime, we'd need to build the libraries or to retrieve the sources, or even run `cmake.install` to get the actual files generated by the CMake process so we can read/parse/api-access them. There is no longer a recipe+binaries, these recipes would need more.

Alternative: store that information somewhere else (why not `conanfile::package_info`?) or in files we are removing from packages in ConanCenter (we remove all the `share` folder with the CMake stuff).

---

I'd totally upvote an external script to make this work (also pkg-config one) and make it easier to discover the values to fill the `cpp_info` object with (we can also implement a hook to check that the values match). This could be a huge benefit, but probably not something built-in into Conan. I know @maikelvdh was thinking about something related too, more from the toolchain perspective, but maybe useful here too.

**Comment by fulara** [comment]
Hello, @jgsogo - not sure what exactly you mean by conanfile::package_info.. but I've always missed actually this sort of data to be exposed in the conaninfo.txt ( or conanmanifest  i always get confused between these two. ).

For me its never clear what particular package exposes as: 
* libraries
* include paths
* variables

Whenever we have an issue, linking error etc - its always a guessing game for us - what sort of mistake have we made while building the package?

That would actually be nice if it would be stored there - but I do understand this may go against current principle.

Edit:
Actually now that I've thought about this - this would be severely limiting over current conan aproach. becuase in current conan aproach everything is dynamic. 
So a path like this would come with its consequences, and would limit the functionality - yes this is a functionality that scarcely even uses probably but still.

**Comment by memsharded** [comment]
There are different things discussed here:

- Getting information from cmake (cache, parsing CMakeLists, etc) to "populate" the ``package_info()`` automatically seems a bit too complicated and fragile to me. From my experience is a big investment that brings a ton of new issues and corner cases that deserves further maintenance and features. something as simple as the ``tools.collect_libs()`` had already got several iterations, changes, fixes and still doesn't satisfy everyone.

- A different thing is the modeling of propagation of usage requirements, that is something that lays on the graph model. We have had discussions about the "private" requirements things, when things should propagate downstream and when not, and there are plans to consider this in the future graph model. In theory, at an abstract level, and then the generators will realize them in their syntax when possible.

**Comment by fulara** [comment]
got duplicated by #7479 and is there is also a nice conversation there, @memsharded feel free to close this one if you wish.
