### ISSUE TITLE
[question] Tons of "WARN: A: requirement Z overridden by B to Z".

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#6839]
In the log I've got 1.5k+ warnings like:
```
WARN: package_A/1.0@my/stable: requirement package_Z/1.0@my/stable overridden by package_B/1.0@my/stable to package_Z/1.0@my/stable
```
Such amount of warnings is almost useless, I need a script to analyze them.
There is no sense in these warnings due to the version of `package_Z` was not changed.

Questions:
1. Is it a bug? (Z was overridden by Z)
2. If not, is there a way to suppress these warnings.

Besides, there is a list
```
Version ranges solved
    Version range ... resolved to ...
```
3. Is there a way to suppress it also?

**Comment by memsharded** [comment]
Messages no longer happening in 2.0, closing as solved
