### ISSUE TITLE
[question] Influence of options of dependencies on consumer's package ID.

### ISSUE THREAD

**Issue by awgil** [conan-io/conan#6840]
As far as I understand, package_id() builds hash of a package based on settings, its own options and identifiers of dependencies (depending on package id mode, it could include name/version/user/channel/package-id/revisions).

Consider app -> lib -> sublib dependency graph. Let 'lib' be a compiled library (static or shared, doesn't matter), and 'sublib' be header-only library.

Assume sublib can work in different modes, selected by preprocessor definition. Natural (only?) way to expose it to conan would be defining an option in sublib recipe (say, sublib:mode), and use option's value to add compile flag in sublib's package_info() method.

Assume lib is built with default sublib:mode, generating package with hash L1 (calculated from lib's options, settings and some ID of sublib). Now assume app selects non-default sublib:mode. How to ensure that it would use a different package L2 for lib (since L1 uses different, potentially non-compatible, mode of sublib)?

1. Should sublib generate different packages with different hashes depending on 'mode' option? I think the expected answer is 'no': for example, standard helper ConanInfo.header_only() removes all options from structure used for package_id calculation. It is also the way many recipes in conan-center work. If we did not call this header_only helper, we would generate two different packages that would be fully identical (after all, the only difference is how package_info() would fill its structures when evaluated while building consumers).
2. If we do generate different packages for sublib, to make sure that new hash of lib is created, it would need to use at least full_package_mode. Is there any situation where compiled library would use any other package mode? Why isn't it a default option?
3. It seems that this situation wouldn't even appear if cpp_info.options included options of all dependencies, yet in the ConanInfo.create() there is an explicit options.clear_indirect() call. What is the reason?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Maybe this is related https://github.com/conan-io/conan/issues/6855?

**Comment by awgil** [comment]
It seems to be a different situation. The problem here is essentially following. Suppose we have a header-only library (with no dependencies) that supports different configurations, selected by preprocessor definition. The package supports selecting one or the other configuration by defining an option, and using value of that option in package_info() method to set appropriate cpp_info.defines. Should the value of that option impact package_id()?
1. If the answer is "yes", then we're essentially generating multiple packages with different hashes that have identical content.
2. If the answer is "no", then we get the problem described in the initial post.

Note that the provided utility self.cpp_info.header_only() removes all options from the package_id calculation, making me think that intended answer is "no".

**Comment by memsharded** [comment]
This should be solved in Conan 2, with the separation of ``self.options`` and ``self.info.options``.
