### ISSUE TITLE
[feature] Add SCM info to conanbuildinfo.cmake

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#6843]
It would be very awesome if conanbuildinfo.cmake can include scm info as well:

```
    revision: 58b4cc6cd02345646cf286e1004adf23518d0c
    branch: my-new-stuff
    type: git
    url: https://github.com/...
```

**Comment by boussaffawalid** [comment]
https://github.com/conan-io/conan/issues/5234

**Comment by boussaffawalid** [comment]
similar to #5234

**Comment by wdobbe** [comment]
Yes, there should be a way to get the SCM revision also for packages that use 'export_sources'. In many packages the compiler needs to export the SCM revision to the source code via a -DREVISION=xxxx define.

At the moment users need to implement their own way of storing the SCM revision (Git commit hash in my case) in the export() method of the conanfile class.

**Comment by memsharded** [comment]
Both ``scm`` and legacy ``conanbuildinfo.cmake`` deprecated time ago, and removed in 2.0, closing as outdated.
