### ISSUE TITLE
Missing Build Info for Transitive dependencies when building missing

### ISSUE THREAD

**Issue by tylerholzer** [conan-io/conan#6846]
We've recently encountered what we believe is a bug where the conan build info for transitive dependencies is missing from dependencies that are being built as part of a missing packages build.

Simple Example:
A depends on B depends on C depends on D.

In the simple example above, we run `conan install` to install the dependencies of A. During `conan install`, B needs to be rebuilt from source because of version changes in its dependencies. While building B, the build info ends up not including any information about D, and the build for B fails. This does not occur with every project, and if you build B from source normally, it succeeds without issue. The dependency trees we've encountered this issue in are more complex, however the above example helps show they symptoms we are seeing. We normally run conan 1.18.5 as we're currently restricted to python 3.4, however we saw the same behavior even when we tried updating to the newest version.

We've tried to reproduce this failure with the same dependency chain and generic code, however we've been unable to do so. We know this isn't ideal but wanted to create this issue in case this had been encountered before (I tried searching for similar issues). We do have a reproducer internally if there are suggestions for additional debugging steps. I tried setting CONAN_LOGGING_LEVEL to debug, but didn't see any relevant information.

**Comment by memsharded** [comment]
Hi @tylerholzer 

Do you mean the ``build-info`` as built by the ``conan_build_info`` command? Are you aware about the ``--v2`` argument to it? That argument will implement some improvements and fixes. It builds completely differerently, from lockfiles instead of on the fly. And it can aggregate information from different configurations (different lockfiles) in a single build-info.

If you mean that, it would be useful to have something that we could test and reproduce, with the commands used to reproduce.

**Comment by tylerholzer** [comment]
The build info I'm referring to is the build info object available to generators. Our conanfiles use both the  default txt generator and a custom generator. The output file from the txt generator, conanbuildinfo.txt, and our custom generator don't include the transitive dependencies. 

The generators are being run as part of a `conan install` command, where a dependency needs to be rebuilt due to a missing prebuilt package.

As I mentioned, we've tried and failed to create a reproducer so far, although we plan to keep playing with it. I filed the issue in case this rang any bells or if there were additional debugging steps we could run locally to help trace what's going on.

**Comment by memsharded** [comment]
Ok got it. 

Then, at first sight, I cannot think of something that would be causing this. Maybe you are using ``build_requires`` instead somewhere? Or ``private`` requires? (btw ``private`` requirements are discourage for most cases, just in case).

Looking forward to hearing from you, thanks!

**Comment by tylerholzer** [comment]
the only build_requires should be the generators and build tools. There are no private requirements.

**Comment by tylerholzer** [comment]
actually looking deeper in the dependency tree I see to have missed a few build_requires that seem to be causing the issue. I'm going to close this. thanks for looking into it
