### ISSUE TITLE
[bug] conan search behaves oddly with  empty storage.path

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6848]
After breaking storage.path due to scripting mistake on my side, I stumbled across this.

So.. usually `conan search` without any arguments returns either:
* list of packages in your storage
* `There are no packages` output.

However when one breaks the storage.path and sets it to.. an empty string :) example:
```
conan config set storage.path=~/.conan/data
$ conan search
Existing package recipes:
...
$ conan config set storage.path=
$ conan search
ERROR: Specify the 'user' and the 'channel' or neither of them
```
Few interesting things happen  when one sets it to a '/' by mistake see this:
```
$ conan config set storage.path=/
$ conan search
ERROR: Value provided for channel, '\x2fsnd\x2fby-path\x2fpci-0000:02:02.0' (type str), is an invalid name. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
```

:) 

### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu
  * Conan version: 1.23.0
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)
Included in the description.

### Logs (Executed commands with output) (Include/Attach if Applicable)
Included in the description.

**Comment by memsharded** [comment]
Closing as outdated in 2.0
