### ISSUE TITLE
[question] What to do when a package isn't found

### ISSUE THREAD

**Issue by parrothouse** [conan-io/conan#6849]
Hi conan community,

I'm a new user of conan and it has been great so far. I would like to use a library I found on github, [cxxopts](https://github.com/jarro2783/cxxopts.git). I tried searching for this by:
`conan search cxxopts --remote=conan-center`
(along with bincrafters) but the search returns no packages.

What are my options when something like this happens? I'm trying to make a simple game to distribute with colleagues (and would like them to show them the pain-free way of handling dependencies with conan) so I can't custom create a package just for my machine, and can't utilise a work server or anything like that.

How do I handle a missing package from a remote?
Can I / How do I suggest a library become a package?

Thanks for the support.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @fletcher-blight 

For searching the ConanCenter, is way better to do in the web UI: https://conan.io/center/
If the dependencies you need are Open Source, and still not in ConanCenter (the new process of adding libs there is quite new), you can request them or even better try to contribute them in: https://github.com/conan-io/conan-center-index/wiki
