### ISSUE TITLE
[bug] `conan frogarian` does not work in VSCode terminal

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#6853]
Expected (as in MacOS terminal):
![image](https://user-images.githubusercontent.com/158844/79229395-4011ec80-7e63-11ea-92c8-497b50e5856c.png)

Actual:

![image](https://user-images.githubusercontent.com/158844/79229334-1fe22d80-7e63-11ea-9cd4-4545800feef8.png)

**Comment by uilianries** [comment]
It depends the size of the window. that command is not dynamic, you need to shrink your window.

**Comment by danimtb** [comment]
It works fine on VSCode terminal using PowerShell in my case

**Comment by DoDoENT** [comment]
> It depends the size of the window. that command is not dynamic, you need to shrink your window.

For MacOS terminal I didn't need to shrink window. It works correctly even with full-width window.

**Comment by rbrich** [comment]
It's also broken in [iTerm2](https://www.iterm2.com/).

**Comment by memsharded** [comment]
Frogarian removed in 2.0, closing this ticket.
