### ISSUE TITLE
[bug] apt package not installed on cached ~/.conan usage

### ISSUE THREAD

**Issue by treaves** [conan-io/conan#6860]
### Environment Details (include every applicable attribute)
  * Operating System+version:
Ubuntu latet docker image with conan installed
  * Compiler+version:
clang 6.0
  * Conan version:
conan-ubuntu-64_1_24_0.deb

### Steps to reproduce (Include if Applicable)
I have a Bitbucket pipeline setup to build a simple C++ app that uses libusb.  This works fine, until I enable the ~/.conan directory to be cached between builds.

When the cache is not present, conan can not find libusb, so downloads it.  But it also installed via apt the libudev-dev package.

When the cache is enabled, libusb is found, so the libudev-dev package is not installed.  This causes my app to fail at the lick stage, `/usr/bin/ld: cannot find -ludev`

I'm guessing the libusb conan config specifies the dependency on the apt install; but when the libusb is found, conan doesn't check the dependency.  As the ~/.conan directory can live across images, this seems a defect in conan.

**Comment by memsharded** [comment]
Hi @treaves 

Yes, the libusb likely has ``system_requirements()`` method. As the cache stores when this system requirements have been installed, if you attempt to reuse the cache between builds, it will think that the system requirements (apt) are already installed.

There are a few options:
- Do not reuse the cache, but try to configure a new "download cache" for download speed only
- You can explicitly call ``conan remove "*" --system-reqs`` to clean that state, and then it will install the system requirements.

Please try that and tell if that helps.

**Comment by memsharded** [comment]
There is completely new tools for installing system packages, no longer being cached in the Conan cache.

Closing this as inactive.
