### ISSUE TITLE
No connectivity between CONAN_SETTINGS_COMPILER_RUNTIME and CONAN_LINK_RUNTIME.

### ISSUE THREAD

**Issue by KunalSharmaa** [conan-io/conan#6867]
OS and VERSION: Windows 10
Python Version: 3.8
Conan Version: 1.23
Compiler and Version: MSVC 19

I believe there should be some relationship between CONAN_SETTINGS_COMPILER_RUNTIME and CONAN_LINK_RUNTIME. Everytime I specify `-s compiler.runtime=MDd` it gets set but doesn't really do its job since VS shows MD as runtime library. The CONAN_LINK_RUNTIME can be seen set as MDd in the CMakeCache.txt but it doesn't set the CMAKE_MSVC_RUNTIME that it is supposed to do as per the conanbuildinfo.cmake.

Please let me know if I'm doing something wrong here.

**Comment by KunalSharmaa** [comment]
OS and VERSION: Windows 10
Python Version: 3.8
Conan Version: 1.23
Compiler and Version: MSVC 19

I believe there should be some relationship between CONAN_SETTINGS_COMPILER_RUNTIME and CONAN_LINK_RUNTIME. Everytime I specify `-s compiler.runtime=MDd ` it gets set but doesn't really do its job. The CONAN_LINK_RUNTIME can be seen as set as MDd in the CMake cache but it doesn't set the CMAKE_MSVC_RUNTIME that it is supposed to do as per the conanbuildinfo.cmake.

Please let me know if I'm doing something wrong here.

**Comment by memsharded** [comment]
Hi @KunalSharmaa 

I am sorry, I don't fully understand the issue. Could you please clarify what generator are you using? Could you please specify the steps/commands you are using? A example package we could try? Are you using the ``conan_basic_setup()``?

**Comment by KunalSharmaa** [comment]
Hi @memsharded 

Yes, I am using the `conan_basic_setup()` inside my CMake wrapper. I am trying to build a debug version of my library 'trial' but it doesn't really get the runtime library set as `MDd` inside visual studio as specified by Conan with compiler.runtime. Instead it shows the usual `MD` option. Could you please help me here as to why the CONAN_LINK_RUNTIME is not able to set the CMAKE_MSVC_RUNTIME_LIBRARY as per specified in the conanbuildinfo.cmake.

Here's the conan recipe that I have been using,

```
from conans import ConanFile, CMake, tools

class TrialConan(ConanFile):
    name = "trial"
    version = "1.0.0"
    requires = ("gtest/1.8.1@bincrafters/stable","pugixml/1.10@bincrafters/stable")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False],"testing":[True, False]}
    default_options = {"shared": False,"testing":False}
    generators = "cmake", "cmake_paths"
    exports_sources = "../trial*", "CMakeLists.txt"
    
    def configure_cmake(self):
        cmake = CMake(self)
        cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = "conan_paths.cmake"
        cmake.configure()
        return cmake
    
    def build(self):
        cmake = self.configure_cmake()
        cmake.build()

    def package(self):
        self.copy("*.h", dst="include", src="include")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["trial"]
```

Also here's my CMake wrapper,

```
cmake_minimum_required(VERSION 3.15)
cmake_policy(SET CMP0091 NEW)
project(cmake_wrapper)

cmake_policy(GET CMP0091 status_wrapper)
message("CMP0091 :${status_wrapper}")

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_subdirectory(trial)
```

Finally my directory structure just to give some understanding,

--conan
------CMakeLists.txt (CMake wrapper)
------conanfile.py
--trial
------CMakeLists.txt (main CMake)
------source files

**Comment by memsharded** [comment]
This refers to the legacy ``cmake`` generator, deprecated in 1.X and removed in 2.0.
Closing the ticket as outdated.
