### ISSUE TITLE
[question] source() method not called in test_package conanfile.py

### ISSUE THREAD

**Issue by joeysmart** [conan-io/conan#6869]
it seems the source() method of test_package conanfile.py is not called

**Comment by uilianries** [comment]
Hi @joeysmart Why do you need it?

Test package is used for verifying the created package.

Please, take a look on docs: 

https://docs.conan.io/en/latest/creating_packages/getting_started.html#the-test-package-folder

**Comment by jgsogo** [comment]
Please, @joeysmart, let us know what is your use case. The `test_package` should be as simple as possible, just to check that the package has been built and can be consumed (headers are available and can be linked).
