### ISSUE TITLE
[bug] conan upload should be a transaction

### ISSUE THREAD

**Issue by Paultergeist** [conan-io/conan#6870]
### Environment Details (include every applicable attribute)
  * Conan version: 1.24.0
  * Python version: 3.7

### Steps to reproduce
Have project `bar` that depends on `foo`.
Have `self.requries("foo/[~=42]@user/channel")` in `bar/conanfile.py`.

`foo` has finished building on CI and CI is running `conan upload foo/42.9000@user/channel`. It has already uploaded the recipe itself, but not the packages.
At the same time, `bar` is building on CI. `conan install` tries to resolve dependencies and it sees that `foo/42.9000` is the latest version that matches `foo/[~=42]`. It tries to fetch the package for the specific profile and fails (because the package corresponding to that profile is not yet uploaded).

### Expected result
`conan install` will only try to install `foo/42.9000@user/channel` when `conan upload` has finished uploading all packages.

**Comment by jgsogo** [comment]
Hi, @Paultergeist 

Indeed, this can be a problem in a CI environment, different jobs are building the same package for different configurations, each job uploads its package as soon as it finishes, so the recipe is in the server before all the binaries are available.

A different Conan client is running on each of those jobs, so it is not possible for the client to know that there are other binaries being built. This is not something that can be implemented in the client.

There are different approaches to this problem:
 * Move the upload to the last stage, collect all the binaries and upload all of them in that single step. Still the concurrency issue can happen, but it is not so likely.
 * Do the same as before, but lock a resource during the upload (Jenkins has this feature), that way no one will be able to download while another job is uploading packages.
 * In Artifactory you can use different repositories to upload packages and to consume them. Once everything is uploaded you move the packages to the other repository, Artifactory won't copy anything (it is checksum-based), it only has to update some pointers and entries in the database (quick operation, recipe and binaries will be available at the same time).

**Comment by Paultergeist** [comment]
> so it is not possible for the client to know that there are other binaries being built. This is not something that can be implemented in the client.

I think this may be implemented on the server (and client). Client may start upload transaction with the server and until the transaction is completed the server will not tell other clients about the new package existence.

**Comment by jgsogo** [comment]
I'm going to label this as something to look into related to Artifactory. If this server implements these features, others will follow, are other server implementing this behavior for other clients? We will try to push it.

Thanks for the suggestion

**Comment by Paultergeist** [comment]
Thanks. Should probably add `component: server` label also.

**Comment by blackliner** [comment]
Hey everyone, what is the current state of transactional uploads? We regularly have corrupt packages stored on Artifactory, because the upload gets interrupted by Jenkins when another pipeline fails.

**Comment by memsharded** [comment]
Closing this in favor of https://github.com/conan-io/conan/issues/16703, please follow that ticket instead.
