### ISSUE TITLE
[bug] adding to settings had no effect

### ISSUE THREAD

**Issue by refactorTractor** [conan-io/conan#6872]
### Environment Details (include every applicable attribute)
  * Operating System+version: Win10 x64
  * Compiler+version: Visual Studio 16
  * Conan version: 1.23.0
  * Python version: only bundled in Winx64 installer

### Steps to reproduce (Include if Applicable)
Modify settings.yml by appending value "11" for compiler -> Visual Studio -> cppstd
```
compiler:
Visual Studio: &visual_studio
        runtime: [MD, MT, MTd, MDd]
        version: ["8", "9", "10", "11", "12", "14", "15", "16"]
        toolset: [None, v90, v100, v110, v110_xp, v120, v120_xp,
                  v140, v140_xp, v140_clang_c2, LLVM-vs2012, LLVM-vs2012_xp,
                  LLVM-vs2013, LLVM-vs2013_xp, LLVM-vs2014, LLVM-vs2014_xp,
                  LLVM-vs2017, LLVM-vs2017_xp, v141, v141_xp, v141_clang_c2, v142]
        cppstd: [None, 14, 17, 20, 11]
```
Use this setting in profile
```
[settings]
os=Windows
arch=x86
build_type=Debug
compiler=Visual Studio
compiler.version=16
compiler.runtime=MDd
compiler.cppstd=11
```
try using profile to install
```
[requires]
libcurl/7.68.0
libxml2/2.9.9
gtest/1.10.0

[build_requires]
doxygen_installer/1.8.17@bincrafters/stable

[options]
libcurl:shared=False
# without libiconv support for these: http://xmlsoft.org/encoding.html#Default is enough for now.
libxml2:iconv=False
zlib:minizip=True

[generators]
cmake_find_package
cmake_paths
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
conan install . -pr win32d -if win32\Debug --build missing
ERROR: The specified 'compiler.cppstd=11' is not available for 'Visual Studio 16'. Possible values are ['14', '17', '20']'
```

**Comment by memsharded** [comment]
But the problem is that that standard does not exist in Visual Studio 16, according to. https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2019

**Comment by memsharded** [comment]
Hi @AGreat1 

Have you had the chance to see the above comment and link? Any feedback here?

**Comment by refactorTractor** [comment]
This does indeed seem to be a misunderstanding from my part. The error message isn't actually coming from the settings validation then, but from deeper within conan, when it tries to assign an invalid value to this option.

**Comment by memsharded** [comment]
> This does indeed seem to be a misunderstanding from my part. The error message isn't actually coming from the settings validation then, but from deeper within conan, when it tries to assign an invalid value to this option.

Yes, it actually has 2 levels, in this case, if you avoid the first one, and add it to the settings.yml, then the internal check of known compilers will be fired and tell you. 

Thanks for following up and closing!
