### ISSUE TITLE
[feature] Silent conan install

### ISSUE THREAD

**Issue by ofiriluz** [conan-io/conan#6874]
Hi, 

As part of our CI/CD, we are trying to use parallel download feature (also using parallel upload), however this is causing a mess log-wise
Is there any plans to add a toggling to disable the progress bars? or any other prints which are not part of the actual conan logs i.e summary of what will be downloaded and so on

Thanks <3

**Comment by danimtb** [comment]
Hi @ofiriluz,

This is something that has been discussed for the future redesign of the command line in Conan 2.0 to have common output format flags. Currently, I don't know y any of the environment variables will reduce the output in the downloads. Maybe @czoido can help you with this

**Comment by memsharded** [comment]
Yeah, sorry, the output of the parallel download has not been addressed yet.
We wanted to prioritize releasing the feature soon so users could try it and report on the performance improvements. Could you please provide some data about the gains in your use case?

We will try to improve this when possible, maybe disabling the progress bars is an easier first step, and the concurrent progress bars could be addressed later.

**Comment by memsharded** [comment]
We have finally removed the progress bars in Conan 2.0, they were too messy and fragile too.
I think we can close this ticket now as solved.
