### ISSUE TITLE
Can't have spaces in VENV path on Linux

### ISSUE THREAD

**Issue by carobins** [conan-io/conan#6875]
Conan VERSION **1.22.2**

I've discovered an issue in which some users have spaces in their venv path. When this happens you can activate the venv, but you can't issue any conan commands:
![image](https://user-images.githubusercontent.com/60359120/79610687-04775c80-80c7-11ea-8d18-2b8c49e84a27.png)
Furthermore, I also cannot directly call the conan executable (without using venv). I get the same error.

I also tested this on Windows, which didn't have an issue with spaces. 

I did some searching and didn't see any existing reports of this. 

Thanks!

**Comment by memsharded** [comment]
Hi @carobins 

There have been a few fixes in the virtualenv generators in the last releases. Could you please do a quick check with latest Conan 1.24? Thanks!

**Comment by memsharded** [comment]
It seems that this ticket got staled or likely outdated, as it referred to the old environment generators.
Closing it as outdated, please create new tickets if necessary, thanks!
