### ISSUE TITLE
[feature] conan install - mark packages to be skipped explicitly

### ISSUE THREAD

**Issue by ofiriluz** [conan-io/conan#6877]
Hi,

So im not sure if theres such a feature besides marking a package private, but we have a pretty comprehensive dependency tree, along with many platforms to support, and for some cases, given package A that consumes another package B which consumes other packages C,D,E,..., we would like to not download some of the packages C,D,E, since we do not need them in package A, but C,D,E shouldnt be private for other packages that consume B
Now, the real issue is that C,D,E cost alot of time to download, which prolongs our CI/CD, especially in platforms such as AIX

What i would like to be able to do, is to filter out packages to download on package A, since we do not need them at all.

Thanks <3

**Comment by memsharded** [comment]
Hi @ofiriluz 

At the moment, it is not possible to skip the download of transitive packages. We will be working in the dependency graph model for Conan 2.0, trying to improve the capabilities.

In the meantime, have you tried the file download cache? That might help avoiding a lot of downloads, specially designed for CI: https://docs.conan.io/en/latest/configuration/download_cache.html

**Comment by ofiriluz** [comment]
Hey!

yes i have tried it along with the download threads
The parallelism helped increasing build time of one component from about 24 minutes to 21, which is awesome

And as for the download cache, we have a set of components (somewhat of a complex graph of components that needs to be built in some fashion), and we use the download cache there along with a shared conan folder between all of those components, on each platform

For example a nightly build that builds about 30 components for our products, takes about 3 hours, the download cache did increase it by about 10-15 minutes, which is awesome! 

But i am still looking for more ways to improve the CI/CD, most of it is c++ (along with c#, java and some nodejs, we use node / maven / gradle / nuget for those)

Thanks <3

**Comment by memsharded** [comment]
> The parallelism helped increasing build time of one component from about 24 minutes to 21, which is awesome

I guess you wanted to say ``decreasing``? 

> And as for the download cache, we have a set of components (somewhat of a complex graph of components that needs to be built in some fashion), and we use the download cache there along with a shared conan folder between all of those components, on each platform

Are you sharing the file download cache between different machines? It is intended to provide multi-process and multi-thread locking, but haven't think about shared network folder between different machines, probably different OSs. Keep an eye on it, in case there is some concurrency issues.

> For example a nightly build that builds about 30 components for our products, takes about 3 hours, the download cache did increase it by about 10-15 minutes, which is awesome!

Again ``decrease``? Did you mean from 3hrs => 10-15 mins? 😅

**Comment by ofiriluz** [comment]
Hah, 

Was abit busy while writing it, ofc i meant decreasing <3
And right now we are sharing cache on a single machine, between different jenkins jobs, however we do want in the future to share it between different machines

Thanks <3

**Comment by memsharded** [comment]
> And right now we are sharing cache on a single machine, between different jenkins jobs, however we do want in the future to share it between different machines

Ok, so please take the above feedback into consideration, it might fail to correctly lock files, and race conditions might happen for network access from different OSs. You might need to provide some kind of locking yourself.

**Comment by memsharded** [comment]
Conan 2.0 has implemented a new graph model that is more powerful and know how to skip many binaries automatically. For example, every static library required by an executable or by a shared library will be skipped by default. So a regular ``conan install`` will be as efficient as possible, downloading strictly the necessary packages, skipping the rest.

For more custom functionality, the custom commands using the python api will be the recommended solution. It will be possible to construct a dependency graph, and before installing the binaries visit the graph, marking ``node.binary = BINARY_SKIP`` the desired packages in the graph. This of course will be quite fragile, if removing packages need by other packages or by consumers, things will break. This is the reason why this feature will not be built-in, it seems too custom and very fragile, difficult to maintain and document, specially taking into account that the default behavior has been heavily optimized.

So lets closed this issue as addressed by 2.0, thanks!
