### ISSUE TITLE
[feature] conan should be able to allow circular dependencies if they are build_requires.

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6881]
Sometimes they are packages that depend on themselves in order to be build.
For example some compilers out there require themselves to be build but in older version ( for example gcc. )

It seems reasonable that conan should allow circular dependency like:
when building `cmake` you may depend on `cmake` but in the `build` phase only. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! This is something allowed by the new xbuild feature (need [this PR](https://github.com/conan-io/conan/pull/6769) because of the _ancestors_ related stuff). I've tested it with GCC using GCC as build_requires declared in the profile_host 🎉

**Comment by fulara** [comment]
Nice, awaiting docs PR so I can fully comprehend how to use this.
