### ISSUE TITLE
[question] Requirements of non-conan packaged 3rd party libraries.

### ISSUE THREAD

**Issue by MRocholl** [conan-io/conan#6883]
- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Hi,
I've been wondering if there is a recommended way on how to handle dependencies of 3rd party libraries. I.e. say I want to package 3rd party library "libA" with a dependency to "libB".
Both `libA` and `libB` do not have conan packages until now. 
libB would, as far as I have understood the documentation right now, be specified as  a `requirement` in the conanfile of `libA`. Would it suffice to wrap `libB` as conan package and specify it in the conanfile of libA?  Or would I need to do some string substitution in the CmakeLists of `libA`, so that it finds the right package `libB`?
Is there a way that handles this case gracefully right now? 

Thank you in advance for your answer.

**Comment by memsharded** [comment]
Hi @MRocholl 

There is a mechanism in Conan that can help somehow to install system requirements (like form apt, chocolatey, etc) from recipes: https://docs.conan.io/en/latest/reference/conanfile/methods.html#system-requirements

But if you want to model them as Conan packages, then the approach is to start with the "leaf" packages, those that do not have other transitive dependencies. In your case if you have:

conanfile -(requires)-> libA -(requires)-> libB

then yes, the natural flow is to start creating a recipe for libB. It can have its own ``test_package`` functionality to help creating the package for libB without errors. Then when you are done, you add a ``requires = "libB/version@myuser/channel"`` in your ``LibA`` conanfile.py, and it will implement the transitive dependencies.

The changes you need in your CMakeLists.txt depend on generator you are using. If using the ``cmake`` one, then your ``LibA`` CMakeLists.txt will contain something like the one you use to consume it (https://docs.conan.io/en/latest/getting_started.html):

```cmake
...
 include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
 conan_basic_setup()

 add_executable(md5 md5.cpp)
 target_link_libraries(md5 ${CONAN_LIBS})
```

(this has several variants, you can use more modern CMake targets with `` conan_basic_setup(TARGETS)``.

Please tell if this helps.

**Comment by MRocholl** [comment]
Thank you for the quick reply.
I had not seen the systems-requirements section. It will probably solve most of my problems.

Regarding the changes required to Cmake. I guess that the `cmake_find_generator` would be the way to go for 3rd party packages that require other packages via `find_package`.  Or am I missing something here?

**Comment by memsharded** [comment]
> Regarding the changes required to Cmake. I guess that the cmake_find_generator would be the way to go for 3rd party packages that require other packages via find_package. Or am I missing something here?

Yes, the ``cmake_find_package`` (probably the ``cmake_find_package_multi`` better) generators will probably become the defaults and recommended in future versions of Conan. However, they lack one important thing, the configuration of toolchain things. The ``cmake`` generator, via ``conan_basic_setup()`` is able to set correctly things like the runtime (MD, MT), the standard library, etc., to match the provided input Conan settings. If you are not using that, you should be careful to be consistent with the configuration or set it yourself.

Also take into account that the current ``cmake_find_package`` generators still don't provide all functionalities, like the ``find_package(... COMPONENTS)``, is still not implemented, so it might not be 100% identical to the cmake or library provided ones. On the plus side, the good thing is that the  Conan automatically generated scripts correctly handle transitivity, which is something that the others don't do.

**Comment by MRocholl** [comment]
Awesome. Thanks for the explanation. That solves my issue.
