### ISSUE TITLE
[bug] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#6886]
What could cause this? It started happening on my CI build, but only on one server (it always works on all other servers, even though all server run conan operations using exactly same docker image).

Stack trace:
```
+ conan remote remove conan-center
Traceback (most recent call last):
  File "/opt/backup/android-arm64-RF8M3193H2K/root/E0/b/venv/lib/python3.8/site-packages/conans/client/command.py", line 2002, in run
    method(args[0][1:])
  File "/opt/backup/android-arm64-RF8M3193H2K/root/E0/b/venv/lib/python3.8/site-packages/conans/client/command.py", line 1530, in remote
    return self._conan.remote_remove(remote_name)
  File "/opt/backup/android-arm64-RF8M3193H2K/root/E0/b/venv/lib/python3.8/site-packages/conans/client/conan_api.py", line 89, in wrapper
    return f(api, *args, **kwargs)
  File "/opt/backup/android-arm64-RF8M3193H2K/root/E0/b/venv/lib/python3.8/site-packages/conans/client/conan_api.py", line 912, in remote_remove
    return self.app.cache.registry.remove(remote_name)
  File "/opt/backup/android-arm64-RF8M3193H2K/root/E0/b/venv/lib/python3.8/site-packages/conans/client/cache/remote_registry.py", line 358, in remove
    with self._cache.package_layout(ref).update_metadata() as metadata:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/backup/android-arm64-RF8M3193H2K/root/E0/b/venv/lib/python3.8/site-packages/conans/paths/package_layouts/package_cache_layout.py", line 186, in update_metadata
    metadata = self.load_metadata()
  File "/opt/backup/android-arm64-RF8M3193H2K/root/E0/b/venv/lib/python3.8/site-packages/conans/paths/package_layouts/package_cache_layout.py", line 172, in load_metadata
    return PackageMetadata.loads(text)
  File "/opt/backup/android-arm64-RF8M3193H2K/root/E0/b/venv/lib/python3.8/site-packages/conans/model/package_metadata.py", line 95, in loads
    data = json.loads(content)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR: Expecting value: line 1 column 1 (char 0)
script returned exit code 1
```

### Environment Details (include every applicable attribute)
  * Operating System+version: 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  * Conan version: 1.24.0
  * Python version: 3.8

Docker image being used: [microblinkdev/clang-devenv:10.0.0](https://hub.docker.com/r/microblinkdev/clang-devenv)

### Steps to reproduce (Include if Applicable)

Also happens on `conan config install https://myserver/path/to/config.zip` on the exact same server (but I don't have the trace there, even though `CONAN_VERBOSE_TRACEBACK` environment variable is set to `1` - I only get this output:

```
+ conan config install https://jenkins.microblink.com/jenkins/job/microblink/job/conan-toolchains/job/master/lastSuccessfulBuild/artifact/android.zip --verify-ssl=false
Trying to download  https://jenkins.microblink.com/jenkins/job/microblink/job/conan-toolchains/job/master/lastSuccessfulBuild/artifact/android.zip
Unzipping 10.7KB
Defining remotes from remotes.txt
ERROR: Error while installing config from https://jenkins.microblink.com/jenkins/job/microblink/job/conan-toolchains/job/master/lastSuccessfulBuild/artifact/android.zip
Expecting value: line 1 column 1 (char 0)
script returned exit code 1
```

Any idea how to debug this further? When I log in to that server and run those commands in the same docker, they work as expected.
Normally, I would say this is a concurrency issue, but within the docker container at the time of the crash, nothing else is being executed.

**Comment by memsharded** [comment]
I have been having a look, and honestly no idea how this can fail at that point.
The only possible thing I can think of would be user/permissions. Is it possible that the user or the permissions used while running that docker are slightly different to the one in different machines? Sharing any folder to the docker with other configuration? I would try to explore that line of investigation.

**Comment by DoDoENT** [comment]
Thank you for your insight. 

> Is it possible that the user or the permissions used while running that docker are slightly different to the one in different machines?

I think it's possible - probably some stray job used the same conan cache from different docker container or even natively.

We will clean the conan home completely and let it download the entire cache anew. If the issue appears again, I'll let you know.

**Comment by vishalmchavan** [comment]
Hi,

Could you please let me know if any solution was found for this?

I am trying to search a string from Json file.

Code where I am facing problem : data1 = json.load(f1)
I am using 
Pygments==2.6.1
httpie==2.2.0
requests==2.24.0
chardet==3.0.4
certifi==2020.6.20

Python 3.8.4

It works when I run code from docker container running on local Centos VM.

But if I run from Gitlab runner , code fails with following traceback

Traceback (most recent call last):
   File "./SetEnv.py", line 202, in <module>
     a.set_da_properties(
   File "./SetEnv.py", line 53, in set_da_properties
     app_uuid = self.set_app_uuid(app_name)
   File "./SetEnv.py", line 22, in set_app_uuid
     data1 = json.load(f1)
   File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
     return loads(fp.read(),
   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
     return _default_decoder.decode(s)
   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
     raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by memsharded** [comment]
Hi @vishalmchavan 

Are you using Conan? Which version? I don't see how your comment is related to this issue.

**Comment by vishalmchavan** [comment]
@memsharded 
Hi,
This is not related to Conan. I am getting this while calling json.load from Alpine based container run from Gitlab runner

I came through this thread. So thought may be similar exception

Thanks

**Comment by davyx8** [comment]
hi 
im not sure this is the same issue but i had a similar problem in ubuntu when trying to do anything with the remotes list.

my problem was an empty json file in the user profile dir. simply removing it like this: 

`rm -rf  /home/david/.conan/remotes.json
`

resolved it

**Comment by frkami123** [comment]
> hi
> im not sure this is the same issue but i had a similar problem in ubuntu when trying to do anything with the remotes list.
> 
> my problem was an empty json file in the user profile dir. simply removing it like this:
> 
> `rm -rf /home/david/.conan/remotes.json `
> 
> resolved it

i also had this issue because of a power outage. my json file was filled with some zero bytes. also resolved the issue by remove it, thank to you,

**Comment by memsharded** [comment]
Thanks all for following up and reporting.

As a general rule, what is in the Conan cache folder could be removed, its intent is that it is a pure cache, and can be removed and re-populated easily. It is possible (and with enough usage it will eventually happen) that some process is interrupted, some file is corrupted due to a crash or power outage, etc. In those cases being able to confidently remove the complete cache and start fresh could be a very easy recovery procedure.

Any configuration items: custom settings.yml, profiles, conan.conf, remotes list, is better defined in a separate repo or zip file, that can be quickly installed with ``conan config install``

**Comment by sgoth** [comment]
We also see this sometimes but only in a single specific usecase:
**Parallel** installation of a big dependency chain with -sbuild_type=Debug and -sbuild_type=Release into an empty conan cache.
Could it be a race on the creation of the packagename/version/ directories or something related? I don't know too much about the details of conans cache locking but i only ever saw messages based on lock files inside the package directory.

**Comment by memsharded** [comment]
Closing this ticket as outdated, Conan 2.0 no longer has those json files in the cache, so this shouldn't be an issue anymore.
