### ISSUE TITLE
[feature] allow editing build_requires by conan profile update

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6887]
invoking:
`conan profile update build_requires.autoconf=x.y.z default`
results in:
`ERROR: Edit  the profile manually to change the build_requires`

Why I need this?
I just wanted to quickly change this from console because I know this particular project wont build on machine I am on, and to follow-in with your iwki guidance i dont want to put it into the conanfile.py.

I was forced to sed the profile.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
I don't know why this was not allowed. Maybe it has some historic reasons but it sounds quite reasonable for me

**Comment by Bbox123** [comment]
Me and my group are UMICH students that want to contribute to this project. We want to contribute by implementing this feature.

**Comment by memsharded** [comment]
> Me and my group are UMICH students that want to contribute to this project. We want to contribute by implementing this feature.

Thanks for the offer @Bbox123 

But I am afraid this ticket is outdated. It refers to Conan 1, which was superseded by Conan 2 more than 1 year ago. The command ``conan profile update`` no longer exist in Conan 2, so it doesn't make sense to add this functionality now to Conan 1.

Thanks very much for your offer anyway, I am closing this ticket as outdated (there is still a lot of house keeping we need to do on old tickets and close many of them). If you want to contribute, the best would be to check open tickets from the 2.X milestones, or propose improvements that come up while using the tool.
