### ISSUE TITLE
[bug] CONAN_LIBS_xxx is reset in editable mode

### ISSUE THREAD

**Issue by JD31** [conan-io/conan#6889]
When setting a package as editable (call it say) then the consumers reset the associated CONAN_LIBS_SAY in conanbuildinfo.cmake.

Example of file **conanbuildinfo.cmake** on consumer side :

No editable mode for OsgEarth:
```
...
set(CONAN_LIBS_OSGEARTH osgEarthAnnotationrd osgEarthFeaturesrd osgEarthSplatrd osgEarthSymbologyrd osgEarthUtilrd osgEarthrd)
...
```
If editable mode for OsgEarth:
```
...
set(CONAN_LIBS_OSGEARTH )
...
```

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: MSVC 2019 64bits
  * Conan version: 1.24.1
  * Python version: 3.8.0

**Comment by jgsogo** [comment]
Hi, @JD31, can you share the recipe file for `OsgEarth`? At least, we need to know what the `package_info` method looks like. 

Thanks!

**Comment by jgsogo** [comment]
For example, if you are using `tools.collecct_libs()` you need the libraries to be in the paths Conan is using to look for them, otherwise the list will be empty. The path if different when the package is in editable mode.

**Comment by JD31** [comment]
Yes i am using tools.collecct_libs()
How can i proceed ?

**Comment by jgsogo** [comment]
Just list the libraries your package is generating:

```python
def package_info(self):
    self.cpp_info.libs = ["lib1", "lib2"]
```

**Comment by JD31** [comment]
I confirm it works

**Comment by jgsogo** [comment]
Yes, this is one of the reasons I usually recommended listing the libraries over `collect_libs()`. I understand it is a handy tool, but it needs the libraries to be already generated, otherwise.... well, it will find nothing 🤷

**Comment by jgsogo** [comment]
Shall we close this issue? Do you think this is something to add as a warning/note to the Conan docs about `collect_libs`?

**Comment by JD31** [comment]
I think that the documentation about "editable package" must be updated to precise this.
One last thing the libs name may change according to the build mode (according to <CONFIG>_POSTFIX). It could be interessing to have a method to automatically transform a given lib name by the final name (and to allow this treatment for a whole array would be nice).
It would allow something like

> self.cpp_info.libs = makeFinalLibNames(["lib1", "lib2"])

**Comment by jgsogo** [comment]
About the final lib names: many recipes have some _helper function_ to adapt the name of the library based on options, but it is not something we can provide as a tool in Conan, each library have its own convention for the final library names.

**Comment by jgsogo** [comment]
We have added a note to the documentation about editable packages: https://github.com/conan-io/docs/pull/1721

Thanks!
