### ISSUE TITLE
[bug] conan does not work with Visual Studio 2017 Desktop Express

### ISSUE THREAD

**Issue by bylee20** [conan-io/conan#6892]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 64bit
  * Compiler+version: Visual Studio 2017 Desktop Express
  * Conan version: 1.24.0
  * Python version: none(executable from official website)

### Steps to reproduce (Include if Applicable)

First of all, With Visual Studio 2017 Desktop Express, tools.vcvars family does not work.

https://github.com/conan-io/conan/blob/b8b30709386a782e7e4a854af23ab141446c5bbd/conans/client/tools/win.py#L182

Here, default preference list does not contain path for express.
2017 Express will be installed into WDExpress, so for now, I can workaround with
```
os.environ["CONAN_VS_INSTALLATION_PREFERENCE"] = "Enterprise, Professional, Community, BuildTools, WDExpress"
```

 Second of all, Visual Studio 2017 Express does not ship x64 native compiler. Instead, it provides cross compiler to compile x64 binary in x86 and its env name is `x86_x64`.

https://github.com/conan-io/conan/blob/b8b30709386a782e7e4a854af23ab141446c5bbd/conans/client/tools/win.py#L378-L381
Again, here, dictionary to select `vcvars_arch` does not contain x86_x64.

**Comment by danimtb** [comment]
Hi @xylosper and thanks a lot for the information! I didn't know about this version of visual studio.

I see we could add that to the preference list.

Regarding the vcvars_arch, I see it will be difficult to differentiate that. Have you tried setting ``arch_build=x86`` and ``arch=x86_64`` in your profile? I am not sure if that would work regarding this https://github.com/conan-io/conan/blob/b8b30709386a782e7e4a854af23ab141446c5bbd/conans/client/tools/win.py#L382

Could you check if ``x86_amd64`` name works? Thank you

**Comment by gddl** [comment]
A solution for VS Express Editions would be really great. I stumbled over this when building openssl which uses `vcvars(...)`. The best approach would probably be to determine the available toolsets and not to rely on `arch_build`.
Couldn't `PreferredToolArchitecture='x86'` be implemented as workaround to enforce the use of the x86 toolset for `arch=='x86_64'`? Just like `PreferredToolArchitecture='x64'` is used to enforce the x64 toolset for `arch=='x86'`.

**Comment by memsharded** [comment]
Closing this ticket as outdated
