### ISSUE TITLE
MsBuild .props file property expansion

### ISSUE THREAD

**Issue by Belpaire** [conan-io/conan#6894]
On conan version 1.24.1:
When I generate an msbuild file the generated file for includes (and linking dependencies suffers the same thing, but I will keep it for includedirectories only now). The generated file contains something like 
<ConanIncludeDirectories>$(USERPROFILE)\.conan\data\path\to\package\include;</ConanIncludeDirectories>
and sometime later the line: 
<AdditionalIncludeDirectories>$(ConanIncludeDirectories)%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>.

This works fine if you are only importing exactly 1 conanbuildinfo.props, however if you import multiple conanbuildinfo files than the $(ConanIncludeDirectories) property will keep being overwritten by the last conanbuildinfo.props and the AdditionalIncludeDirectories value will be incorrect. This is due to MSBuild considering all properties in a global namespace, so the last one seen is the one that sticks. The solution would be to just have the ConanIncludeDirectories being expanded immediately so that AddtionalIncludes contains the expanded value of ConanIncludeDirectories. I wasn't sure whether to flag this as an issue, so I made it a question, because I am not sure whether this is truly a bug, or just a design decision on your part.

**Comment by jgsogo** [comment]
Hi! 

I see the issue, but I wonder why are you using several `.props` files generated by Conan. This is a new scenario for us and we would like to understand why and what are the advantages or what are we missing so you need to use several `conanbuildinfo.props` files.

Thanks for the feedback.

**Comment by Belpaire** [comment]
Hi,

To me it has multiple benefits. 

1. The project is large enough, that I would not be able to maintain it if I had a conanfile in every subproject, meaning I would have to generate all of them (not that that would be very hard, but I feel that you would lose maintainability by generating them instead of declaring them by hand).

2.I do not want every subproject to link to all the libraries we use, nor do I want them to include all of the headers, so one global conanfile is not what I am looking for. 
One solution would be to have every subproject have their own conanfile, but this is not satisfactory to me, as it would mean: Most projects that are related, use the same thirdparty libraries, thus a lot of unnecessary conan installs and if I wanted to do a build, even when the cache is already there it would take a lot of calls, slowing the build down as there are many subprojects.

3.I could calculate which libraries are needed for the combination of subprojects I wanted to build, and generate the conanfile from this so I only have one conanbuildinfo.props, but this seems like it wouldn't be worth it to me as it is also a generated conanfile (which seems like bad practice to me).

4.By making it so that every thirdparty library has its own conanfile, I can generate the conanbuildinfo.props of a single library, and each subproject can include the files of the thirdparty libraries it needs. This is a good solution for me because:
    -it is clear which version is being used, there is only one place the version of a library is declared
      so I am sure there is not some subproject trying to use an old version
   -there is no script needed to generate the conanfiles (still need one to make sure you call conan 
     install on everything of course, but that's quite trivial).
   -it only needs to do the bare minimum of conan install calls (once for each library you use).

These are the reasons I see, but I could of course be wrong in my analysis. So advice/suggestions as to how to best use conan are also appreciated.

**Comment by Belpaire** [comment]
Hi,

I tried out your new msbuild generator, and so far it seems that the global variable problems are solved with this generator. If there are any specific other issues, I'll report them. Thanks for keeping up the good work!.

kind regards.

**Comment by memsharded** [comment]
Thanks @Belpaire for following up, trying the new msbuild generator and reporting!

Looking forward to getting further feedback if something fail, as we intend to convert this new generator to the recommended and default one.
