### ISSUE TITLE
conan.exe should have an argument to suppress prompts

### ISSUE THREAD

**Issue by gprosch** [conan-io/conan#6898]
The current implementation requires that I set an environment variable (CONAN_NON_INTERACTIVE = 1) or add a setting to conan.conf (non_interactive = True) to suppress interactive prompts.

This is a less than ideal implementation because it assumes that I will always want to run conan one way or the other.  I may actually want to run it interactive sometimes and non-interactive at other times. 

Note: I also filed a bug indicating that conan does not observe the interactive settings for lock issues.

**Comment by czoido** [comment]
Hi @gprosch,
We don't have in mind adding another argument to all the commands for this but could you please detail more your use case so we can understand it better?

**Comment by gprosch** [comment]
I certainly understand the reluctance of adding additional arguments.  Could I politely suggest that many of the options in the conan.conf file would be useful to have as options available via the command line interface.  Adding them all explicitly would certainly be ill advised.  However, you could provide a means by which I could reference an alternate conan.conf file or you could have an argument that allows me to pass one of more of them via a concatenated string.  I believe this would significantly increase the flexibility and usability of the conan.exe.

As for use case examples, development and diagnostics are the ones that come to mind.  During the process of developing new conan recipes, adding dependencies to new projects, setting up new systems, etc., I would very much want to see the messages as I am diagnosing problems but I would also want to be able to ignore them at times as I am testing the flow.  Perhaps the best example though is diagnosis of production build issues.  In a production environment I would want to have conan running in non-interactive mode but if something goes wrong, I may want to run conan interactively as I diagnose the issue.  I would not want to have to change the configuration because that would adversely affect my production environment during the diagnostic process.

Thank you for your time and consideration of this request.  Conan is the best solution of its type and I appreciate your efforts to develop it.

**Comment by czoido** [comment]
Thank you so much for your kind words! :)
As you know we are designing Conan v2 right now, so this kind of feedback is very valuable for taking into consideration features that are helpful for users in the future.
Anyway, I don't know if this helps but maybe using `conan config install` to install the configuration from a file or repository that won't change and `conan config set` to modify the settings you need could be useful for you.

**Comment by gprosch** [comment]
That's a good idea.  I will try that.  Thank you!

**Comment by memsharded** [comment]
Closing this ticket as inactive.
