### ISSUE TITLE
[bug] Cannot install from conan-center on windows

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#6899]
### Environment Details (include every applicable attribute)
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
python=3.7.7

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

### Steps to reproduce (Include if Applicable)
`git clone https://github.com/conan-io/examples.git && cd examples/libraries/poco/md5`
`mkdir build && cd build`
`conan install ..` 
got error:
> C:\Users\Username\Develop\examples\libraries\poco\md5\build>conan install ..
> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Release
> compiler=Visual Studio
> compiler.runtime=MD
> compiler.version=16
> os=Windows
> os_build=Windows
> [options]
> [build_requires]
> [env]
> 
> poco/1.9.4: Not found in local cache, looking in remotes...
> poco/1.9.4: Trying with 'conan-center'...
> ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
> 
> Unable to connect to conan-center=https://conan.bintray.com
> 1. Make sure the remote is reachable or,
> 2. Disable it by using conan remote disable,
> Then try again.

tried to remove re-add, disable enable the conan-center, non works. 
Tried the same thing in linux, everything is fine.

**Comment by memsharded** [comment]
Hi @shelper 

It seems there might be something wrong with your system ssl (or the python ssl) in Windows. Which Conan installation did you use? The python-pip one? In a virtualenv?

Is it possible that you have some VPN or proxy configuration in your Windows machine?

**Comment by shelper** [comment]
i installed anaconda 3 2020.2(Latest) from the anaconda website.
i dont have VPN, the linux in the WSL in the same windows environment works
i used `conda install -c conda-forge conan`

**Comment by shelper** [comment]
after installed conan by pip, same error happens

**Comment by uilianries** [comment]
@shelper Take a look on this: https://github.com/conda/conda/issues/4930

You can disable ssl verification for Conda, as workaround, it should be enough:

    conda config --set ssl_verify False

As full solution, you need to check your certificate files, probably you need to set a correct one or update them (described on that same issue).

**Comment by shelper** [comment]
Tried to set ssl off but still fails.
also tried updating the ca, etc. pretty much everything i can find online...
anyway, i will try more and will update here. not sure if others have met the same issue though...

**Comment by memsharded** [comment]
> anyway, i will try more and will update here. not sure if others have met the same issue though...

We have found some issues with SSL in Mac but not many in Windows. Have you tried the Windows installer instead? That bundles a python interpreter, might be useful to try to isolate the issue.

**Comment by shelper** [comment]
Tried reinstall python, and install conan by pip,  also tried install the conan binary standalone, still the same error
```
poco/1.9.4: Not found in local cache, looking in remotes...
poco/1.9.4: Trying with 'conan-center'...
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

**Comment by shelper** [comment]
I tried again using windows sandbox, basically a VM in windows, everything is the same, and in the sandbox Conan install works.....
I dont know what is missing in my host window :(

**Comment by shelper** [comment]
So more test here. 
1. on my windows system, after i set verify_ssl to false in remote.json file, then no error happens, 
but in my windows sandbox system, no error even with verify_ssl = true.
2. I found people saying this may due to my shell is using TLS1.0, while conan-center uses TLS1.2, so i did confirm conan-center uses TLS1.2, then on my windows system, i modified the TLS version by the [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
but still the same error.
3. I run `requests.get(https://conan.bintray.com)` in python shell in my windows system, I got the same error. 

I then compared the certificates from the windows and windows_sandbox, by run `Get-Childitem cert:\LocalMachine\root |format-list` in powershell, and found the one fails has every certificates the other has,  :(, so it should not due to missing certificates.

**Comment by shelper** [comment]
hum... i tried on another computer with windows 10 and everything is fine.
Now it seems to me there  must be some settings in windows messed up....

**Comment by shelper** [comment]
I am gonna close this one as it turned out to be my company's firewall causing this issue.

**Comment by memsharded** [comment]
Hi @shelper 

Happy to hear that you identified the issue :)

From our experience, this kind of error, most times it is some corporate VPN, proxy or similar tool, controlling accesses in some way. ConanCenter gets millions of downloads per month, it might eventually have some service issue, but that we get aware relatively quickly. 

Thanks very much for keeping the efforts and following up, reporting your findings! Cheers!

**Comment by pbaret** [comment]
@memsharded Hye, got the same issue but I can't figure out how to make it work with my company's proxy in the loop ? I set up the http and https variables in conan.conf but it does not work....

**Comment by memsharded** [comment]
Hi @pbaret 

At some point you might need to talk to your IT, and sort this out with them. The company proxy might completely forbid this possibility. What I would do before reaching to them, is to make sure that everything works locally:

- You can setup an ArtifactoryCE (free, just get the zip, unzip and execute) in your local machine, configure it and use it to see you can successfully make it work, both client and server, in the same machine.
- Try to do the same setup, but using a server in your team/office LAN (if you have two devices or something), to rule out internal network issues.
- Make sure that you can make it work outside of the company proxy (try outside of the VPN too if there is one, etc).

With this, we can be more confident it is indeed the proxy, and you might be more successful with company IT support.
