### ISSUE TITLE
LibXml for windows fails to download

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#69]
Hi guys,

Further to your work on adding libxml support, I'm afraid it fails to install for my project in appveyor [1]. It installs a few of the dependencies such as zlib, but then fails on iconv:

```
Conan winiconv/1.14.0@lasote/stable not found, retrieving from server
WARN: Unable to connect to local=http://localhost:9300
ERROR: All remotes failed
Command exited with code 1
```

Thanks for your time.

Marco

[1] https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.27

**Comment by lasote** [comment]
Hi Marco,

I think I forgot to upload my winiconv package. Give me some minutes.

Thanks!

**Comment by mcraveiro** [comment]
Cool, thanks a lot! I'll trigger the build when done. Cheers

**Comment by lasote** [comment]
Ready!

**Comment by mcraveiro** [comment]
Thanks. I've re-triggered the build[1] and will post the results. cheers

[1] https://ci.appveyor.com/project/mcraveiro/dogen

**Comment by mcraveiro** [comment]
Excellent, worked well. Now I just need to sort out the paths:

```
-- WIN32 OR WIN64
-- iconv not found
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibXml2 (missing: LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindLibXml2.cmake:69 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:89 (find_package)
``` 
 
Presumably this will be as per the Linux ticket so I guess we can close this one.

Cheers

Marco
