### ISSUE TITLE
Search with query should return packages with settings set to Any

### ISSUE THREAD

**Issue by tru** [conan-io/conan#690]
I am trying to use `conan search` to detect the `outdated from recipe` to determine when to build a package or not - so I am invoking search as follows: 

`conan search plexconantool/1.0@plex/stable -r plex -q "os=Linux and arch=x86_64 and compiler=gcc and compiler.version=6.2 and compiler.libcxx=libstdc++11 and build_type=Release"`

Where the query match the current building settings. This narrows it down to what packages that needs to be built for this current set of settings. The problem with this is that it excludes packages that have settings set to `Any` in `conan_info` (like python packages). They should ideally be included in the search results here. Alternatively I need to figure out if a current package have a specific setting set to Any and then modify my query.

**Comment by lasote** [comment]
Yes, it's a current limitation of our search. "ANY" values or even worst, not present setting won't match the query. 
In addition to this, we don't support the OR operation in querys.

**Comment by tru** [comment]
Is this limitation something that you guys are planning to address or will it be "sometime"? Just wonder if I need some kind of workaround. Is there a way I could find out if the current local package settings? I.e. I want to find out if the current one sets anything to Any and then handle that by searching broader and parsing the output (I really don't want that though).

**Comment by lasote** [comment]
@tru In the short term we need to find a workaround. Maybe doing two different searches? We can add search options to output better "machine readable" contents.

**Comment by tru** [comment]
Yeah I see some options for workarounds:

Here is what my program currently does:
* runs `conan info --build_order=ALL`
* iterates over the output from that and runs `conan search <package> -q "<all settings>"`
* runs `test_package` and `upload` on the packages that that are not up-to-date

If I could run some kind of command before search to know what settings that needs to be included in the query that's one solution. Another solution is to make it easier to parse the output of search so that I don't need to call with query at all and instead do that matching on the client side. More code for me though.

**Comment by lasote** [comment]
This one could be closed since we have the search json output, right? Feel free to write if anything is still missing. As you know we are trying to improve every release something related to the automation/json.
