### ISSUE TITLE
[bug] unix_path forces always lowercase - even on Linux where casing matters.

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6900]
conan version: 1.23.0
conan build with pyinstaller, windows was nowhere near the build process.
OS: Redhat 6/7. 

code:
`raise Exception(tools.unix_path("HAI"))`
results in:
`Exception: hai`

On Linux. 
isnt that undesired?
See problem I've encountered here:
https://github.com/conan-io/conan-center-index/issues/1435#issuecomment-618686445

**Comment by jgsogo** [comment]
Hi!

This tool is intended for Linux subsystems in Windows, not for native Unix. The implementation depends on the subsystem flavor and it has been working for a while (we use it inside other tools using windows subsystems). As you can see in the source code, it is taking into account different casing scenarios depending on the subsystem: https://github.com/conan-io/conan/blob/e17f052820b9d6e2fe60bd4e9cbd398bdd9e8534/conans/client/tools/win.py#L546

Do you think there is a problem in the implementation or is it about the name of the tool itself?

**Comment by fulara** [comment]
@jgsogo 
Is it possible to expand the implementation so that it has a check for whether are are on native linux? 

It seems that if anyone wants to use this tool, that person will have to wrap it with an if statement:
Like madebr has done there:
https://github.com/conan-io/conan-center-index/pull/807/files

I think the problem here is with the implementation - it should be noop in linux, i can see an argument for 'the user should decide'...
if we were changing the impl then something like:
if not tools.os_info.is_windows {
    return path
} 
would probably work. but I am not sure if this will be always desirable scenario.

**Comment by fulara** [comment]
@jgsogo  I have done search:
https://github.com/conan-io/conan-center-index/search?q=unix_path&unscoped_q=unix_path
All recipes that use unix_path without if statement checking for windows are *broken*! 
and its just that in most cases you wouldnt have capital letters in their names.. so its not that common.

**Comment by jgsogo** [comment]
Yes, probably it is worth to follow your suggestion and make this tool a noop for `not OSInfo.is_windows`, wdyt @memsharded  @SSE4 ?


>  I am not sure if this will be always desirable scenario.

Can you think about any breaking scenario (given current documented behavior)?

**Comment by fulara** [comment]
@jgsogo  not enough knowledge of how it happens. but what I am thinking of is cross compiling.
if someone compiles from windows to linux -> would this work as expected:
```
if not tools.os_info.is_windows
``` 
(Expectation here is that target os matters not source os. )

**Comment by jgsogo** [comment]
But this tool should be used mostly in the `build()` step (configuring the build system and so on), at that moment Conan is running in the `build` machine (Windows) and not in the `host`. So, if we are cross-compiling we are running in "Windows"

**Comment by fulara** [comment]
Okay. its too hard to asses then whether the scenario will be correct or not :)

**Comment by SSE4** [comment]
actually, this is more like a file-system requirement, not an OS requirement. so the proper fix maybe not that simple... e.g. on OSX, you may now format case-sensitive or case-insensitive OS, as well as on Windows there are ways to make the system case-sensitive.
in general, there might be more places which suffer from similar issue(s).

**Comment by jgsogo** [comment]
But regarding this tool, as it is intended for "Windows paths --> subsystem ones" it should do nothing for Unix and it will help to simplify some of the recipes that appear in the query search provided by fulara.

Maybe we should think about a better name for this tool, or maybe Conan should provide the paths (cpp_info.rootpath, libdirs, includirs,....) already converted to the OS system/subsystem where the build is running. This is something we can think about for the next Conan major, it is time to come up with these crazy ideas.

**Comment by SSE4** [comment]
I agree, `unix_path` should be no-op on Unix-like systems
for Windows, however, there probably should be more logic around the `lower()` call, but that's another story
