### ISSUE TITLE
Symantec Malware WS.Reputation.1 detection in release 1.24.0

### ISSUE THREAD

**Issue by RReymann** [conan-io/conan#6902]
Hi guys,

While trying to install the latest release of conan for Windows, Symantec has detected the following malware ; WS.Reputation.1

Are you already aware about that ?

Cheers
Renaud R,

**Comment by uilianries** [comment]
Hi @RReymann thanks for reporting us.

Could you please share more details? Do you have a log containing such message?

It's possible solving it by sending a false-positive report to https://symsubmit.symantec.com/

**Comment by RReymann** [comment]
Hi,

Please find  the corresponding log msgs:: 

`"conan-1.24.1-x64.exe","WS.Reputation.1","Log only","Insight Network Threat","Auto-Protect scan","c:\Users\garcial\downloads\","DEVPC028310","GarciaL","Log only","c:\Users\garcial\downloads\","Leave alone (log only)","Leave alone (log only)","The file was left unchanged.","4/23/2020 4:25:55 PM"`

If you confirm that release 1.24.1 doesn t contain any malwares, I will contact Symantec Support as suggested.

Cheers
Renaud

**Comment by uilianries** [comment]
~~Which installer did you use?~~

It's described in your log ..

**Comment by uilianries** [comment]
I can't identify any malware: https://www.virustotal.com/gui/file/f5e96db4c9631ae480b814a4d84e039842f97bed2c21790d472b0f385e80f691/detection

I think is because it's an installer from an unknown provider.

Anyway, the recommended installation form is using pip, even on Windows. Please, consider pip as you default conan installer form.

**Comment by czoido** [comment]
Hi @RReymann,
Could you please check if other versions of the installer give the same problem?
Like:
https://dl.bintray.com/conan/installers/conan-win-64_1_23_0.exe
https://dl.bintray.com/conan/installers/conan-win-64_1_22_0.exe
https://dl.bintray.com/conan/installers/conan-win-64_1_21_0.exe
Thanks a lot!

**Comment by RReymann** [comment]
Hi 

I used this one:
https://dl.bintray.com/conan/installers/conan-win-64_1_24_1.exe

I did not notice any Symantec Alert with 
https://dl.bintray.com/conan/installers/conan-win-64_1_23_0.exe

Cheers
Renaud

**Comment by RReymann** [comment]
Hi,

Please find below Symantec actions ;

> Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:

    File name: conan_win_64_1_24_1.exe
    MD5: 8095FAF3409517308E4DACA857863692
    SHA256: F5E96DB4C9631AE480B814A4D84E039842F97BED2C21790D472B0F385E80F691
    Note: Whitelisting may take up to 24 hours to take effect via Live Update

If detection persists, please contact support:
* Norton: https://support.norton.com/sp/en/us/home/current/info
* SEP: https://support.symantec.com/en_US/endpoint-protection.54619.html

Decisions made by Symantec are subject to change if alterations to the Software are made over time or as classification criteria and/or the policy employed by Symantec changes over time to address the evolving landscape.

For more information on best practices to reduce false positives:
https://www.symantec.com/content/en/us/enterprise/white_papers/b-to_increase_downloads-instill_trust_first_WP.en-us.pdf


Sincerely,
Symantec Security Response

**Comment by czoido** [comment]
Hi @RReymann,
Thanks a lot! I'll close the issue then.
