### ISSUE TITLE
[question] How to add includepath for c++ intellisense in vscode

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#6904]
For `vcpkg`, you can add the following include path to the `c_cpp_properties.json` file so that the intellisense in vscode will work  

```
"includePath": [
                "${vcpkgRoot}/installed/x64-linux/include/**",
                "${vcpkgRoot}/installed/x86-linux/include/**"
]
```
For `conan`, is there a similar approach? I couldn't find it in the documentation..

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by shelper** [comment]
Well, i am just trying to answer my own question
a solution is to use cmake-tools plugin for vscode and change the c++ configuration provide to cmake. This will let the intellisense find the includes based on cmake,

I am gonna close this one

**Comment by memsharded** [comment]
Hi @shelper 

Yes, that should work. As a reference, for other build systems, it might be possible to extract the information about headers from several Conan generators, as the ``txt`` one, or the ``json`` one, that would be relatively easy to parse. It is also possible to write a custom generator that will output information directly for VScode format (this is already what the ``ycm`` generator is doing for YouCompleteMe)

**Comment by iosifzota** [comment]
> Well, i am just trying to answer my own question a solution is to use cmake-tools plugin for vscode and change the c++ configuration provide to cmake. This will let the intellisense find the includes based on cmake,
> 
> I am gonna close this one

It's possible to use compile_commands.json for include paths as well. I guess this is what you meant. Here's how:
https://stackoverflow.com/a/70616885/13819534
