### ISSUE TITLE
[bug] Store full path to the conanfile for editable packages

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6905]
From https://github.com/conan-io/conan/issues/6896

The information stored in the `editable_packages.json` in the Conan cache contains only the path to the folder where the recipe is. As a consequence, if the file is not called `conanfile.py`, Conan will fail to locate the recipe.

**Comment by meggamind** [comment]
I would like to pick this up

**Comment by jgsogo** [comment]
Sure! Waiting for your PR then 👍 

if you need help with the implementation, or to write tests, don't hesitate to ask.

Thanks!
