### ISSUE TITLE
[question] Conan cross compilation MacOS to RaspberryPi

### ISSUE THREAD

**Issue by ryan-WORK** [conan-io/conan#6907]
Hello,

I have 2 questions for you.

Does Conan support cross compilation from MacOS to Raspberry Pi? 

Is there example code for the talk **Continuous Integration of C/C++ Apps for IoT Devices** by Diego Rodriguez-Losada & Daniel Manzaneque in 2018?

I have read through the examples that are listed on the cross compile portion of the website and I do not see anything about MacOS targeting Raspberry Pi, Linux, or Windows.

I want to recreate the cross compilation example that was presented at the **Continuous Integration of C/C++ Apps for IoT Devices** by Diego Rodriguez-Losada & Daniel Manzaneque in 2018, but use MacOS instead of Windows.

- [ X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @ryan-WORK .

Let's ping @danimtb , he will know for sure where the sources of that example can be found.

About cross-compiling: Following the examples in the documentation you can see that most of them are populating the environment with the variables needed to cross-build: the path to the compiler, path to other tools, sysroot,... and Conan will run using those tools and associate the binary to the `settings` provided in the profile. 

Some tools and build helpers we provide will take into account those environment variables and use them to run the build steps, so the recipe is the same and, depending on the inputs, the output will bee binaries for different _host_ architectures.

If you need more help related to the cross build, we would need to know the cross-compiler you are using and the profile with the environment variables you are using, so we an investigate it and help you with the solution.

Thanks!

**Comment by danimtb** [comment]
Hi @ryan-WORK,

The repository we used for that talk can be found here: https://github.com/danimtb/ci_iot

There you can check the cross-building profile called ``win_to_rpi``. For that example we used windows, but you can customize the profile for your own cross-building toolchain.

**Comment by ryan-WORK** [comment]
@jgsogo & @danimtb Thank you so much. I will take a look and see if I can follow the example. 

I really appreciate you answering my questions about this.

**Comment by jgsogo** [comment]
Let us know if it works, and, if you have a successful example compiling from Macos we will be pleased to add it to our docs and/or examples repositories (maybe a blogpost). Also, if you need help, write here too, we'll try to help. We all can learn.
Thanks!
