### ISSUE TITLE
[bug] cmake_find_package_multi set the PACKAGE_VERSION to None for a package created with None built_type

### ISSUE THREAD

**Issue by Siron777** [conan-io/conan#6908]
Hi,

I am building a package with a recipe containing
`settings = "os", "compiler", "build_type", "arch"`

but the build type is set to None (-s built_type None) in the create command. This is because the recipe behaves like that:

- A multi config -> one package if the build_type is None

- A one config -> one package if the build_type is not None.

So far, so good, it works quite well if i use the _compatible package feature_. However, I found a small issue with the cmake_find_package_multi generator. In the file XXXConfigVersion.cmake generated for the package, the package version variable is set to "None":
```
set(PACKAGE_VERSION "None")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()

  if("None" MATCHES "^([0-9]+)\\.")
    set(CVF_VERSION_MAJOR "${CMAKE_MATCH_1}")
  else()
    set(CVF_VERSION_MAJOR "None")
  endif()
```

Because it works well with recipe not listing the built_type in their settings. I guess this is related to the code in the generator not considering package with a built_type existing but set to None, somewhere in the code:
```
        build_type_suffix = "_{}".format(build_type.upper()) if build_type else ""
        for _, cpp_info in self.deps_build_info.dependencies:
            # If any config matches the build_type one, add it to the cpp_info
```

I can understand that what I am doing with the build_type is maybe not the nominal case, or even a hack. But anyway, since the XXXConfigVersion.cmake file is common to all build type, do you think it could be worth supporting my corner case ?

Best regards,
Simon

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: MSVC 2019 16.4
  * Conan version: 1.24.0
  * Python version: 3.7

**Comment by memsharded** [comment]
Hi @Siron777 

You are right, this seems a small bug. Just submitted a fix, lets see if it can be released in next 1.25
