### ISSUE TITLE
[question] Is there ways for building C++ python extensions using conan?

### ISSUE THREAD

**Issue by synacker** [conan-io/conan#6909]
I have Qt based project - [Daggy - Data Aggregation Utility](https://github.com/synacker/daggy) - and [devel classes](https://github.com/synacker/daggy/tree/master/src/DaggyCore).
I want to port these classes into python as pip package.
Project dependencies are building using conan.

Is there ways to create python C++ extension using conan? 
Is there any examples?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @synacker 

You might be interested in this read: https://docs.conan.io/en/latest/howtos/other_languages_package_manager/python.html
It might be a bit outdated, we haven't revisited it in a while. But you will be able to see there that it is possible. Creating a pip package might require a bit of work in the pip/setuptools side, but it seems possible (at least I recall some other users doing something like that)

**Comment by synacker** [comment]
@memsharded Thank you for attention!
Looks, like an unexplored way )
Let us know about examples please, if you will meet them )
Thank you!

**Comment by memsharded** [comment]
I think the original question about creating python extensions is addressed by those examples in the documentation. In this case, we could close this issue as resolved.

A different issue is how to create pip (or other) python packages that uses Conan under the hood to build extensions that resolve dependencies internally with Conan. This case is not documented in our docs, and if we got more information, it seems that it would be more a documentation thing, nothing to be done in the Conan client that I could think of. I vote for closing this issue as non-actionable at the moment, for sure if we learn about some users something that we could share, we will add it to our docs :)

Thanks for the feedback!
