### ISSUE TITLE
Is there a way to fetch only CMake compatible packages from the conan-center?

### ISSUE THREAD

**Issue by KunalSharmaa** [conan-io/conan#6913]
I am trying to have a strong CMake + Conan integration and would only like the CMake compatible packages. I tried to look at the `conan search` command for some help but it doesn't really have any CMake specific commands. So can you help me here?

**Comment by memsharded** [comment]
Hi @KunalSharmaa 

There is not such a thing in Conan. If package recipes are written correctly, they should be able to be consumed from other build systems and not only cmake.

If you want to know what packages are build with cmake, you can clone https://github.com/conan-io/conan-center-index and grep for ``CMake``

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you in a while - if anyone has any other question or request, please feel free to create a new issue, we're always happy to help! :)
