### ISSUE TITLE
[bug] package_folder shown in conan info don't change if options changes when using build_id.

### ISSUE THREAD

**Issue by NokiDev** [conan-io/conan#6915]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows
  * Compiler+version: Visual Studio
  * Conan version: 1.24
  * Python version: 3.6

### Steps to reproduce (Include if Applicable)

Create a package recipe, with a boolean option and with override build_id method to set 
self.info_build.options.myOption to 'Any'.
Create two packages, one with and the other without the option.
Call conan info -o myOption=True --paths --package-filter YourPackage/* PackageReference
Call conan info -o myOption=False --paths --package-filter YourPackage/* PackageReference

Compare package_folder line, it should be identical whether or not we pass a different value to myOption.

Reference Repo : https://github.com/NokiDev/conan_info_package_folder_bug

I'm using short_paths, but same behaviour occur without.

Have a nice day.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Not specially applicable.

**Comment by memsharded** [comment]
You are right. Submitted a PR https://github.com/conan-io/conan/pull/6917 to fix it, for next Conan 1.25
