### ISSUE TITLE
[feature] support gcc 10

### ISSUE THREAD

**Issue by rea-yseop** [conan-io/conan#6920]
Hello,

since gcc10 is out, would it be possible to add it to the list ?

For now i am manually modifying `~/.conan/settings.yml` as suggested here https://github.com/conan-io/conan/issues/6538

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, adding it in next release to the default settings.
