### ISSUE TITLE
[feature] Merge multiple packages contents into a single folder

### ISSUE THREAD

**Issue by bog-dan-ro** [conan-io/conan#6921]
I faced problems when I worked with projects which had lots of dependencies, this way the include & libs paths gets very big.

Such a feature it's needed for at least the following reasons:
 -  to workaround window max path limitation.
 -  to speedup the build, for the compiler it's faster to search one folder than multiple.
 - package & test big projects like KDE frameworks. Here the biggest problem it's running some tests which expects that the dependencies data it's in one folder.

What will really help it's a way to combine multiple packages into a single location and create a `sysroot`, with all the headers in `sysroot/include`, libs in `sysroot/libs`, data in `sysroot/share`, etc.

Of course it won't work for recipes that are not setting the `self.cpp_info` stuff correctly, or if they are using strange layouts, or when different dependencies requires different incompatible versions of the same package. Or if the same file it's in more than one package?

**Comment by memsharded** [comment]
Hi @bog-dan-ro 

I am not sure what you mean. You have the ``imports`` functionality that can get everything you want, with the layout you want in your folder. Have you had a look at it?

**Comment by bog-dan-ro** [comment]
I mean that if my package depends on libA, libB, libC, etc. I wan't to merge libA, libB, libC, etc. package folders into a single folder with a single `include`, `lib`, etc folder for all packages.

**Comment by memsharded** [comment]
> I mean that if my package depends on libA, libB, libC, etc. I wan't to merge libA, libB, libC, etc. package folders into a single folder with a single include, lib, etc folder for all packages.

Yes, you can do with the ``imports`` feature. You are responsible that some headers or other files will not collide by name, but otherwise it does exactly what you want.

**Comment by bog-dan-ro** [comment]
@memsharded Thanks a lot, I was looking to   https://docs.conan.io/en/latest/reference/commands/misc/imports.html not to 
 https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports :).

Sorry for the noise.

**Comment by memsharded** [comment]
No problem, glad to help!

You have ``imports`` both at the recipe level (as method, as you pointed), and also at the ``conanfile.txt`` simple text consumer, as ``[imports]`` section too, in case you need it.
