### ISSUE TITLE
[bug] conan create fails to check on remote (.conan.db)

### ISSUE THREAD

**Issue by gpioloco** [conan-io/conan#6923]
### My Problem
To explain my issue i have to tell you what my setup looks like:
My problem involves 2 computers my _workstation_ and a _buildmachine_. And additionally i got two packages _A_ and _B_. Note that package _B_ is being required by package _A_. Package _B_ is located on a remote  _MyRemote_ and the _buildmachine_ tries to build package _A_ using _conan create_ like this 
`conan create conanfile.py 1.2.1-200428072532+e63fd83@gipi/testing --profile Win32VS10D`
I can also build package _A_ on my _workstation_ using the exact same command.

Now there these two situations where conan behaves not like expected:
When i call the _conan create_ command from above to build package _A_ with no packages installed in my local cache ( c:/Users/xyz/.conan) the following thing happens :
![image](https://user-images.githubusercontent.com/48447458/80568073-98fe8a80-89f6-11ea-8496-8208dd9a718b.png)
- conan does not find  package _B_ in my local cache
- conan searches on remote _MyRemote_
- conan downloads the missing package _B_

Now lets look at what happens on the buildmachine:
On a new build jenkins creates a build folder for package _A_. Within this build folder an empty conan home (no installed packages) and conan config folder is being created. The structure looks like this:
-Buildmachine
-- C:
--- BuildFolderForPackageA
---- conanhome
-----...
---- conanconfig
-----...
---- source
-----...
---- include
-----...
---- conanfile.py
Now the exact same _conan create_ command from above gets called and the following happens:
![image](https://user-images.githubusercontent.com/48447458/80569411-2a6efc00-89f9-11ea-93b5-12c614d32aad.png)
- conan does not find  package _B_ in my local cache
- conan returns an error

Since conan does not look on _MyRemote_ for the missing package i checked if the remote is configured which it is.

### What did i try to fix / debug it
First thing i did i copied the entire buildfolder including the conan home and config from the _buildmachine_ to my _workstation_. To make sure the conan home from the _buildmachine_ gets used i changed the according environment variables. When i now ran the _conan create_ command from above the same thing happens like on the buildmachine.
That lead me to the conclusion that something in the conan config or home is different on both my machines that causes this different behaviour. Using winmerge i now merged the config and home folder file by file until i found the file which causes the different behaviour.
I found out that when i use the _.conan.db_ file from my _workstation_ conan checks on the _MyRemote_ for the missing package _B_. If i use the _.conan.db_ from the _buildmachine_ i get the error that the package _B_ is missing. If i delete the _.conan.db_ file it gets generated automatically but i still get the error.

### My questions now are 
- Why / How does this _.conan.db_ file influence the "looking on remotes" behaviour ?
- Is any confidential data stored in this file ? (if not i can share the "good"  and "bad" file here)

### Environment Details (include every applicable attribute) (_workstation_ / _buildmachine_)
  * Operating System+version: Windows Enterprise 1803
  * Compiler+version: VisualStudio2010
  * Conan version: 1.22.2
  * Python version: 3.8.1

**Comment by memsharded** [comment]
>Why / How does this .conan.db file influence the "looking on remotes" behaviour ?

It contains the cached user and token (not passwords) to connect to that remote, to avoid having to enter the user/password for every remote api call

> Is any confidential data stored in this file ? (if not i can share the "good" and "bad" file here)

Yes, the token contains authorization to the server. In general it should be temporary and expire, so way more secure than a password, but still you shouldn't be reusing or sharing this conan.db file

You should be interactively authenticating in every machine (or use ``conan user`` command, or use login/password environment variables, typical in CI).

Please tell me if this helps, thanks!

**Comment by gpioloco** [comment]
So the influence of this .conan.db file on the behaviour related to remotes is that i use a different user. So maybe i got different permissions on my buildmachine and my workstation. I will try to check the users and permission and experiment a little i will write back if i know something new. Thanks for the fast response

**Comment by gpioloco** [comment]
As suspected there was a permissions issue on my side that i have resolved. Now everything works fine. Thanks for you help
Kind Regards

**Comment by memsharded** [comment]
Glad that the issue is resolved now
Thanks @gpioloco for following up and reporting!
