### ISSUE TITLE
[question] Why are private requires not recommended?

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [conan-io/conan#6924]
Title. Sorry if this question has been asked before; I did try a few searches 

We use CMake with static libs and sometimes we have libraries which have a completely hidden/private dependency. In cmake we usually achieve this using `target_link_libraries(target_lib PRIVATE private_dep)`. This does not get translated back out to other conan packages relying on `target_lib`. Using conan requires with the private flag should emulate this behaviour I think? But I see that using it is not recommended.

Is this a good use case for it? And why is it not recommended?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SSE4** [comment]
private requirements may lead to ODR violations, for instance:
**A** (private)-> **libjpeg/9c**
**B** (private) -> **libjpeg/9d**
**C** -> **A**, **B**
in this case you have both **libjpeg/9c** and **libjpeg/9d** within a dependency graph simultaneously. this might work in some cases (if you're careful and understand what are you doing), but on other hand, it may lead to runtime errors hard to debug.

**Comment by Mirko-von-Leipzig** [comment]
Could you elaborate on '(if you're careful and understand what are you doing)'?

Is ensuring that no private headers get exposed enough? Or is far more complicated?

**Comment by memsharded** [comment]
> Is ensuring that no private headers get exposed enough? Or is far more complicated?

Yes, I would say it is more complicated, it is possible to have duplicated symbols while linking A, B, for example. And that would be the good case. easy to detect, and possible to workaround (I have seen solutions based on adding an extra namespace to differentiate both, but that requires patching and hacking). But it is possible to get very weird ODR violations resulting in internal binary incompatibilities in structures, memory, very challenging to debug.

So I would leave this as a very, very last resort, when there is nothing else I could do, and being very careful about the exposed interfaces in A, B, and the information that flows between 2 components, and only with the correct linking (shared DLLs A, B in windows with a private dependency to a static library might be ok).

**Comment by Mirko-von-Leipzig** [comment]
Okay thank you :)
