### ISSUE TITLE
[question] enforcing a pre-promotion buildall concept for new version of package

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#6930]
This is a request for a clarification of a question made some time back via email.  Previously I asked:

> I work with a group of 30 developers who must coordinate check-ins to a collection of about 20 libraries.  Is there a dependency query I can make that will allow me to try a minimal rebuild of all libraries that might be affected by a change before I allow promotion? Maintain a list of libraries and check "requires" recursively to build up a list of affected libraries, and try a rebuild of them?

In our toolchain at work we call that kind of pre-promotion validation a `buildall` step.

The answer Diego helpfully provided was:

```
$ conan info . -bo zlib/1.2.11@conan/stable
[zlib/1.2.11@conan/stable], [OpenSSL/1.0.2l@conan/stable], [Boost/1.60.0@lasote/stable, Poco/1.7.8p3@pocoproject/stable]
```

> Two inputs are necessary:
> 
> - The "root", consumer of the project. In this case is the current conanfile.py/.txtin the user space
> - The "modified" package, in this case zlib/1.2.11@conan/stable.
> 
> The result is the list of list, meaning that first it is necessary to build zlib, then OpenSSL, and after it finishes, Boost and Poco can be built in parallel.
> 

I'm finally getting around to trying to incorporate this built promotion "gating" validation in our system, and ran into an issue:

If I run this on the current conanfile e.g. in my `pract` project, I am told what needs to be build for an *existing* version of the library `dtl-standalone/2.12.2`:

```
16:55:10 E:\DevelopBp\mmaguir1\src\PORT\pract>conan info . --build-order  dtl-standalone/2.12.2@PORT/stable -j output.json

{"groups": [["dtl-standalone/2.12.2@PORT/stable"], ["rstack/0.1.79@PORT/stable"], ["pfe/0.4.98@PORT/stable"]]}
```

Question: how would I check for a *proposed*, future version of dtl-standalone 

```
16:58:18 E:\DevelopBp\mmaguir1\src\PORT\pract>conan info . --build-order  dtl-standalone/2.18.3@PORT/stable -j output.json

{"groups": []}
```

(imagine that `dtl-standalone/2.18.3` doesn't exist yet)

Do I need to first create `dtl-standalone/2.18.3` and have it available "somewhere" before I can then re-run the `conan info . --build-order  dtl-standalone/2.18.3` command against it?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @michaelmaguire 

First of all, we are encouraging people to use `lockfiles` and the `conan graph` command to get a snapshot of a dependency graph and then `conan graph build-order` to compute the packages that are missing. The output is the same as the one from your command: a list of lists with the packages to build.

The inputs needed to run generate a lockfiles are:
 * the root of the graph: typically the project/product/appliaction, better to use a reference than to use a local `conanfile.py` file.
 * a profile: settings and options, the graph can be different depending on it.
 * the context for the command: as you already know, Conan looks for references and packages first in the cache and then in the listed remotes.

This is more or less the same as the `conan info` argument, but lockfiles have other advantages, let's see how to use them ⬇️ 

When a developer modifies the sources of a package and creates a pull-request to the upstream branch, you can implement the following workflow:
 1. Check that the unittests related to the library work, that the code is _"mergeable"_.
 2. Upload the generated recipe (`dtl-standalone`) and binary to a temporary repository in Artifactory (let's call it `conan-tmp`), this repository will contain a new revision of the recipe and the binary package.
 3. Trigger a job for your consumer application using `conan-tmp` as your first remote. This job will:
    1. Compute the lockfile for your application: it will take from `conan-tmp` the new revision of your `dtl-standalone` application and from your other remotes the rest of dependencies.
        * if it is a new revision, it will satisfy the same requirements and it will be used in this graph
        * if it was a new version, depending on your `requires` (version-ranges) this new version will be used or not in your application. **If it is not used and you want to force your consumer application to use it** then you need to change something downstream (probably the requirement to use a different version) and it would be a pull-request to your consumer application (read note below 🔖 ).
    2. Conan will compute the graph of dependencies and create the `lockfile`
    3. Run `conan graph build-order` using the `lockfile` from the previous step. It will tell you the libraries to build, those that are affected by the new `dtl-standalone` revision.
    4. Build the dependencies that have been modified (those listed in the build-order) (you can trigger different jobs for it, you can also parallelize some of them based on the build-order information) and upload those packages to the same `conan-tmp` repository (you don't want to make them available for the team yet, you don't know if the PR is going to be merged or not).
        * use the `lockfile` you generated in the previous step to build these dependencies, this way you ensure that they are using the same profile and the same set of options as if they were being built together with the project.
    5. Build the application. Run tests
 4. If everything goes fine, you can show a green check in the PR that the developer did to `dtl-standalone` repository. Now you know if those changes would break your existing consumer application or not.
 5. Next action related to the pull-request:
    * If the pull-request is closed, just remove the `conan-tmp` repo (yes, you should have a different repository per pull-request, or identify the binaries to remove somehow).
    * If the pull-request is merged, you can trigger the CI for your _master_ branch and generate the binaries needed (if it is a merge by fast-forward, then you can promote the binaries)

This is a brief introduction to the workflow we try to explain in our CI/CD training, we are running this training online and there will be more sessions in the future. If you want to attend, please write to conandays@jfrog.com and they will keep you updated about the next sessions.

---

**Note.-** If the pull-request is creating a new `dtl-standalone` version (modifying the reference from `2.12.2` to `2.18.3`) and you want your consumer application to use it (this new version doesn't satisfy version-ranges in the consumer requirements) you need to force Conan to usee it overriding the requirement:
 * you can modify the consumer application's recipe on the fly to use the new version
 * you can create a temporary `conanfile.txt` file that requires your consumer application and the proposed new reference `dtl-standalone/2.18.3`, and run the previous workflow using this `conanfile.txt` as the root of the graph. 

---

I know this is too much information and poorly explained, probably there are some typos and errors as this is not a working scenario I can test and run right now (we are working on these examples trying to make them available as running examples using a working CI, but it will take some time). **Please, ask anything related to these steps or the ones you consider that would be more suitable for your scenario, I'll try to elaborate on them and give more detailed commands if needed**.

Thanks!

**Comment by michaelmaguire** [comment]
> If the pull-request is closed, just remove the conan-tmp repo (yes, you should have a different repository per pull-request, or identify the binaries to remove somehow).

Sadly, our team is quite separate from the team that maintains Artifactory in our company, and creating an Artifactory repo `conan-tmp` programmatically on the fly requires Artifactory Admin privileges which my team won't have:


> From: support@jfrog.com At: 02/21/19 16:07:05
> Subject: Re: [#98866] Conan repository API Access
> 
> Hello Michael,
> 
> Thank you for your reply.
> With regards to your repository creation request as you mentioned this process requires admin privileges, currently, only Artifactory admin users can create repositories you may want to use this REST API to create the repository via the CI server with an admin user as part of the build.
> We hope this answer your question. Please feel free to contact us for any further assistance or inquiry.
> 
> Best regards,
> JFrog Support
> 

Do you have you suggestions for how to do this "identify" mechanism without access to the admin account that would have the ability to create Artifactory repos on the fly?


One related thought:   I see you mentioned parallelization of the build of individual package components in the build tree for the requested promotion.  I see how that can work.  But what about parallelization of completely separate promotion requests?  It feels like only one promotion request can be handled at a time, otherwise we risk doing a promotion check against a dependency graph rendered out-of-date by success of a preceding promotion request.  If it's the case that separate promotion requests must be sequentialized (which might be a bit sad from a speed point of view...) then perhaps we can get by with a single static `conan-tmp` Artifactory repo that we use per promotion check?

**Comment by jgsogo** [comment]
Identify packages that belong to a PR

You can programmatically **assign a property to the Artifactory folder** or to individual files, the property can identify the maturity of the package, maybe include the id of the PR itself (maybe you need more than one property). Then using JFrog CLI you can query for all the artifacts identified by a property `key=value` and remove those artifacts (you can build the reference from the path or get the Conan reference from another property and use `conan remove ... -r remote`, although it will be easier to use JFrog CLI to remove them).

I know we did something similar in the [Conan CI training](https://github.com/conan-io/training-ci). You can get some ideas from the "[Lab 7] Download App based on properties", if you need help with `jfrog rt` or to build the query we can ask someone with more experience with it.

---

Parallelization

I mentioned, related to parallelization, that the `build-order` from the lockfiles provide a list of lists, all the packages included in the inner lists can be built in parallel because they do not depend on each other. If you are using lockfiles you can be sure that Conan will choose the proper version, recipe revision and package revisions from your requirements.

But yes, **if you are creating a lockfile** and new packages become available in the remotes because of a promotion, there can be a _concurrency_ issue and you might include in the lockfile some new packages as they arrive.

If it is about Artifactory promotions, I really can say nothing, I'd need help from some JFrog colleague, I'm not familiarized with them.

**Comment by michaelmaguire** [comment]
Dear, @jgsogo, could we ask you to update https://github.com/conan-io/conan/issues/6930#issuecomment-621737594 with the new commands that should be used now that `conan graph` has been deprecated?

I guess it would be:

```
C:\dev\src\conan\testlibB1>conan lock create ./conanfile.py
Requirements
    testlibA1/0.1@conan/stable from 'bloomberg_artifactory_nx_stable' - Cache
    testlibA2/0.1@conan/stable from 'bloomberg_artifactory_nx_stable' - Cache
Packages
    testlibA1/0.1@conan/stable:c32596dcd26b8c708dc3d19cb73738d2b48f12a8 - Missing
    testlibA2/0.1@conan/stable:c32596dcd26b8c708dc3d19cb73738d2b48f12a8 - Missing
Build requirements
    cmake/3.18.2@bloomberg/stable from 'bloomberg_artifactory_nx_stable' - Cache
    strawberryperl/5.30.0.1@bloomberg/stable from 'bloomberg_artifactory_nx_stable' - Cache
Build requirements packages
    cmake/3.18.2@bloomberg/stable:ca33edce272a279b24f87dc0d4cf5bbdcffbc187 - Cache
    strawberryperl/5.30.0.1@bloomberg/stable:456f15897172eef340fcbac8a70811f2beb26a93 - Cache

Generated lockfile: C:\dev\src\conan\testlibB1\conan.lock
```

then:

```
C:\dev\src\conan\testlibB1>conan lock build-order conan.lock
[[('testlibA1/0.1@conan/stable#37dee71907e767edb392a3b9cbcd4afb', 'c32596dcd26b8c708dc3d19cb73738d2b48f12a8', 'host', '1'), ('testlibA2/0.1@conan/stable#df571f0550ff5eecd4485e49b6feb2e0', 'c32596dcd26b8c708dc3d19cb73738d2b48f12a8', 'host', '2')]]
```

**Comment by michaelmaguire** [comment]
> if it is a new revision, it will satisfy the same requirements and it will be used in this graph

Do you mean recipe or binary revision?

**Comment by jgsogo** [comment]
> > if it is a new revision, it will satisfy the same requirements and it will be used in this graph
> 
> Do you mean recipe or binary revision?

I mean _recipe revision_. If it is a new _recipe revision_ the Conan reference is the same and it will be used by the consumers (unless they are hardcoding the full reference including the recipe revision). When computing the new graph, Conan will resolve to the same reference, Conan will retrieve the new recipe revision from the `conan-tmp` repository.

**Comment by michaelmaguire** [comment]
UPDATE: Thanks to @memsharded, we see that updated docs on this can be found at https://docs.conan.io/en/latest/versioning/lockfiles/ci.html
