### ISSUE TITLE
[feature] Lockfiles - ability to 'specify' requirements version to be generated on command line.

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6936]
This is a follow to my story described here: https://github.com/conan-io/conan/issues/6707#issuecomment-601443704

What I would like to request, is that you consider an ability to build `lockfile` with a specific requirements from user, based on existing lockfile.

Whats the use case:
We want freedom and full control of the depencies.
We achieve this right now by loading a version file dynamically in conanfiles.py 
that work very well - but unfortunatelly is not compatible with lockfiles, and only lockfiles bind to package revisions. 

Our workflow today is:
Install this app with boost/1.71.0 - if the application is build with boost/1.71.0 it will fetch it from artifactory and its done. 

The ideal situation for me would be:
conan install my-app/2.3.2 --lockfile-override boost/1.71.0 --lockfile-override zlib/71.0 . This will generate a lockfile with a graph of dependencies thats compatible with zlib and boost. 

And if i want to se a different library i would do: 
conan install my-app/2.3.2 --lockfile-override boost/3.0 --lockfile-override zlib/2.0
and this would generate yet another lockfile.

This should override the requires of particular libraries, yes. on top of that this would of course be compatible with versioning_schema exposed by my-app and its dependencies.

related: 
https://github.com/conan-io/conan/issues/5067#issuecomment-614321844
but its about 'during create' i would like it to be available during both create and install, but install would be a good step forward.

Because our solution works - which rewrites requires dynamically on installation - i think this request fits into the current conan flow.

**Comment by memsharded** [comment]
This is outdated, Conan 2.0 lockfiles have changed, they now even support the ``conan lockfile add`` command, so this is most likely solved. Please create new tickets if necessary.
