### ISSUE TITLE
[bug] GCC9.3 not supported

### ISSUE THREAD

**Issue by 0x8000-0000** [conan-io/conan#6938]
### Environment Details (include every applicable attribute)
  * Operating System+version:
Ubuntu 18.04
  * Compiler+version:
GCC9.3 (and GCC10 pre-release)
  * Conan version:
1.24.1
  * Python version:
Python 3.6.9

### Steps to reproduce (Include if Applicable)

```
$ conan profile show gcc10rel
Configuration for profile gcc10rel:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=/opt/gcc10-for-tng/bin/gcc-10
CXX=/opt/gcc10-for-tng/bin/g++-10
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan install ../tng -pr=gcc10rel
ERROR: Invalid setting '10' is not a valid 'settings.compiler.version' value.
Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '7', '7.1', '7.2', '7.3', '7.4', '8', '8.1', '8.2', '8.3', '9', '9.1', '9.2']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

I presume I will have the same problem with GCC9.3 since I don't see it in the list above.

**Comment by 0x8000-0000** [comment]
NVM, now I have read the last line of the error message.

**Comment by memsharded** [comment]
Hi @0x8000-0000 

Also, gcc 9.3 is already in the default settings. You should be getting it in a clean installation of Conan, or if you are upgrading Conan and didn't modify the settings yourself. Note the warning messages when you upgrade the Conan version about possible migrations/upgrade issues.
