### ISSUE TITLE
[feature] Access to command-line version in set_version()

### ISSUE THREAD

**Issue by djeverett** [conan-io/conan#6939]
In `set_version()` we wish to only set `self.version` if it has not been explicitly set on the command-line.  However, there seems to get no way of accessing the value supplied on the command-line using Conan.  This would be useful to have.

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Submitted a quick https://github.com/conan-io/conan/pull/6940 PR to check if everything else break if we change the order of evaluation of set_name() and set_version() to allow this.

**Comment by memsharded** [comment]
Merged, this will be released in 1.26. Thanks for the suggestion!
