### ISSUE TITLE
[feature] Support exports() and exports_sources() as methods

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#6943]
All dependency properties of a package (requires/requirements) support being declared as attributes and/or methods. This provides flexibility to authors which is absolutely necessary in many cases.  Similarly, it would provide very valuable flexibility if the same were true for `exports` and `exports_sources` attributes.  

One prime example of how this could be valuable is for out-of-source recipes which wish to cache sources in the recipe package just like `exports_sources` does today.  There have been requests for this in the past. Will try to find and link them here in time. 

- bzip2 broken because certificate expired : https://github.com/conan-community/community/issues/64
- janson broken because source site down : https://github.com/conan-io/conan-center-index/issues/1399

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Minimonium** [comment]
Related to https://github.com/conan-io/conan/issues/6474
