### ISSUE TITLE
[question] Remove source and build folder without triggering --build missing

### ISSUE THREAD

**Issue by Cscotttaakan** [conan-io/conan#6949]
I'm trying to remove the source and build folder for a conan package to reduce a docker image size. Removing the contents of the folders causes them to be rebuilt when calling `--build missing`. What required conan specific cache files are needed prevent a `build` command from being called?

Is it having the same hash in `build/$HASH`?

**Comment by memsharded** [comment]
Hi @Cscotttaakan 

Not sure what you mean. As long as the binary package is there, you don't need them, and ``--build missing`` shouldn't be doing anything. So it is possible to ``conan remove * -s -b`` without firing rebuilds later.

Can you please elaborate, and provide some example recipe, with the necessary steps to reproduce this?

**Comment by Cscotttaakan** [comment]
This is what I was looking for thanks. I was manually removing the build and source folders.
