### ISSUE TITLE
Running build not from root directory

### ISSUE THREAD

**Issue by opilar** [conan-io/conan#695]
I've written some conanfile. It loads a file, check it, unzip and remove:
```
class IconvConan(ConanFile):
    name = "iconv"
    version = "1.14"
    generators = "cmake"
    settings = "os", "arch", "compiler", "build_type"
    folder_name = "lib" + name + "-" + version

        zip_name = self.folder_name + ".tar.gz"
        download("http://ftp.gnu.org/pub/gnu/libiconv/" + zip_name, zip_name)
        check_md5(zip_name, "e34509b1623cec449dfeb73d7ce9c6c6")
        unzip(zip_name)
        os.unlink(zip_name)
```
You can see it unzipping it in separate directory `folder_name`. 
When I want to build, I should configure the library in that directory.
```
    def build(self):
        env = ConfigureEnvironment(self.deps_cpp_info, self.settings)

        self.run(env.command_line + " ./configure --disable-shared --with-pic", cwd=self.folder_name)
        self.run(env.command_line + " make", cwd=self.folder_name)
```
Everything's fine but windows because ConfigureEnvironment creates bat file which I should execute.
Finally I get the error:
```
iconv/1.14@sbis/stable: WARN: Build folder C:\Users\ma.rybakov\.conan\data\iconv\1.14\sbis\stable\build\367de09a2d03464b27a9f07e2d4bb18479455580
ERROR: iconv: Error 1 while executing call _conan_env.bat ./configure --disable-shared --with-pic
```
What should I do?

**Comment by memsharded** [comment]
I would suggest trying:

- Remove the cwd=self.folder_name
- Change dir after the env.command_line:

Something like:
```
self.run(env.command_line + "cd %s &&  ./configure --disable-shared --with-pic" % self.folder_name)
```
The issue is that Windows is problematic for setting environment variables conditionally, and appending, so that has to be done in a .bat file, which is generated in the root folder. If you execute the command in the ``folder_name`` folder, it will not find that .bat file.

Please try that and tell me, thanks!

**Comment by opilar** [comment]
I've failed with:
```
self.run(env.command_line + " && cd %s &&  ./configure --disable-shared --with-pic" % self.folder_name)
```
but you helped me. First `&&` is unnecessary. Thanks a lot!

**Comment by memsharded** [comment]
You are right, I should have used the initial && too! Don't know why my code works! Damn Win command line syntax! LOL

A small suggestion, you can pass a conanfile to ConfigureEnvironment():

```
env = ConfigureEnvironment(self)
```
Shorter, and it also handles some extra cases.

**Comment by opilar** [comment]
@memsharded we should update the ConfigureEnvironment example [here](http://conanio.readthedocs.io/en/latest/conanfile_py.html#autotools-configure-make) then.

**Comment by memsharded** [comment]
Sure, fixed!

**Comment by opilar** [comment]
For cross-platform solution we need to execute `sh` process.
```
self.run(env.command_line + " && cd %s && sh ./configure --disable-shared --with-pic" % self.folder_name)
```
It's needed for mingw + msys.

**Comment by memsharded** [comment]
Great, I think it is a good tip to include in the docs, opened an issue for it, thanks!
