### ISSUE TITLE
[bug] conan profile new --detect does not return error exit code when compiler was not found

### ISSUE THREAD

**Issue by Marcin-Radecki** [conan-io/conan#6954]
Hi, I've observed that  `conan profile new --detect` does return 0 exit code in case it was unable to detect a compiler. I'd expect that command to fail in this scenario. 

### Environment Details (include every applicable attribute)
  * Operating System+version: rh7 
  * Compiler+version: any GCC version
  * Conan version: 1.24.0
  * Python version: 3.7.4, (also reproducible on 2.7.8)

### Steps to reproduce (Include if Applicable)

CC and CXX points to non-existing binaries.

```
$ echo $CC
/opt/rh/devtoolset-7/root/usr/bin/gcc
$ echo $CXX
/opt/rh/devtoolset-7/root/usr/bin/g++
$ conan profile new --detect path_to_new_profile && echo "Command returned success"
CC and CXX: /opt/rh/devtoolset-7/root/usr/bin/gcc, /opt/rh/devtoolset-7/root/usr/bin/g++ 
ERROR: Unable to find a working compiler
Profile created with detected settings: /home/<user>/git/conan-standalone/deploy/.conan/profiles/path_to_new_profile
Command returned success
```

Please note unexpected `Command returned success`  in the output above.

**Comment by memsharded** [comment]
Hi @Marcin-Radecki 

I would say this is not a bug, but designed to do that. The thing is that this is a detection mechanism for the whole profile: OS, architecture, and yes, compiler. But not only compiler. It is possible to have default profiles that do not have a compiler (for example only os and arch, to install just executable packages without compiler setting). So we considered that not detecting a compiler was not an error per-se, but a normal flow situation.

I am labeling this to get further feedback, I wouldn't have a problem to change my mind if the team things the opposite.

In any case, as a reminder, please take into account that we don't recommend to use auto-detected Conan profiles in production, but to explicitly define your profiles with the configuration you want.

**Comment by Marcin-Radecki** [comment]
Thanks for explanation, having a second thought on it, we will change our approach to no longer auto detect compiler settings, rather than we'll use explicit profiles as suggested.

As a matter of feedback on the error logging, in my opinion it is a slightly confusing behavior that a command prints to std error upper case `ERROR` string, but eventually does return zero exit code.

Please feel free to close this ticket.

**Comment by memsharded** [comment]
I agree with that, the message ``output.error("Unable to find a working compiler")`` should better be a warning not an error (our real errors are Exceptions raised, that are captured and always return an error code). It seems we changed them to be displayed in red as they were not catching enough user attention, but that means that probably we should improve the UX of our warnings mechanism, so they are more evident and useful.

Lets use that as a feedback for @czoido and the design of command line 2.0.

Thanks for the feedback!
