### ISSUE TITLE
[feature] Accept list for SystemPackageTool

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#6961]
The [SystemPackageTool](https://docs.conan.io/en/latest/reference/conanfile/methods.html#systempackagetool) class offers the method `install` which only supports a string with all packages to be installed. However, even a list of packages must be passed as a string, it's a bit confuse, and get worst if you need to check if it's installed or not before: https://github.com/conan-io/conan/issues/6960#issuecomment-624620287

It would be great accepting both string (backward) and list:

```
installer = SystemPackageTool()
installer.install(["pkg1", "pkg2", "pkg3"])
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
The documentation states it can use a list (in a single string) and the implementation tries to work with a list too:

```python
    def install(self, packages, update=True, force=False, arch_names=None):
        """ Get the system package tool install command.

        :param packages: String with all package to be installed e.g. "libusb-dev libfoobar-dev"
        
        """
        packages = [packages] if isinstance(packages, str) else list(packages)
```

Probably this is not a feature, but a bug as it is not working as expected (and it has already the ability to work with a list/string-list). Here we need to fix a couple of things and probably fixing them will cover this feature.

I'm closing this one in favor of https://github.com/conan-io/conan/issues/6960

**Comment by uilianries** [comment]
The documentation says :

> Note: This list of packages is intended for providing alternative names for the same package, to account for small variations of the name for the same package in different distros. To install different packages, one call to install() per package is necessary.

This feature request is about installing different packages at same time: e.g. 

```python
def system_requirements(self):
    installer = tools.SystemPackageTool()
    installer.install(["curl", "vim", "cowsay"])
```

Using this code, with the current implementation, Conan install will Curl, and end the execution.


However, if we pass to accept a list of packages, we would break the current behavior, so we need an alternative, maybe a new parameter:

```python
def system_requirements(self):
    installer = tools.SystemPackageTool(all=True)
    installer.install(["curl", "vim", "cowsay"])
```

The parameter `all` represents, install all packages listed, they are not alternatives.
