### ISSUE TITLE
[feature] Add export/export_source to deps_cpp_info

### ISSUE THREAD

**Issue by cguldner** [conan-io/conan#6963]
This would be a very useful feature particularly for packages that just export source instead of providing binaries (packages you'd specify in `build_requires`). Currently I'm having to do this just to get to the export directory

```python
"{}/../../export".format(self.deps_cpp_info["dep_name"].rootpath)
```

Not a huge deal, but also seems like it'd be an easy thing to implement

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Minimonium** [comment]
That's a _very_ unsupported usage, mind you. The exact layout of the Conan cache is an implementation detail. Moreover, Conan's graphs operate on packages and recipes, not export (and especially not export_source) directories. 
Why not packaging sources themselves?

**Comment by Minimonium** [comment]
Related to https://github.com/conan-io/conan/issues/6944

**Comment by cguldner** [comment]
@Minimonium I thought that was how packages had to be exported if you weren't creating binaries, but I suppose I could just define a blank build step and copy all of the source in the package step, if that's what you mean

**Comment by Minimonium** [comment]
Yes, that's exactly what I mean. There could be different use cases obviously but see the linked issue above that intends to solve some related things in that direction.
