### ISSUE TITLE
Simplify settings migration

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6973]
The current internal mechanism to upgrade or not upgrade the settings.yml file in the cache requires maintenance on our side for every release that has changes in the default settings. I suggest the following feature, that achieves the same without needing maintenance:

- Everytime Conan saves the file ``settings.yml`` it also stores a backup, like ``.settings.yml.original``
- This should not apply for ``conan config install`` updates of ``settings.yml``
- When the settings are to be migrated, instead of comparing with the settings in the Conan codebase, the ``settings.yml`` is compared against ``.settings.yml.original``. If it is equal, the file can be overwritten with the new one from Conan (the user did not do custom changes). If different, the user did custom changes we don't want to destroy, so we keep their file and save a copy for the user reference

**Comment by KerstinKeller** [comment]
Actually, maybe you could even attempt a 3-way merge like git does: The original file for the users release is the base, the setting in use is one way, and the setting of the new release the other way 😄 
So maybe even in cases of user changes, a diff tool (there must be some python package available) could possibly merge for you...

**Comment by memsharded** [comment]
> Actually, maybe you could even attempt a 3-way merge like git does: The original file for the users release is the base, the setting in use is one way, and the setting of the new release the other way 😄
So maybe even in cases of user changes, a diff tool (there must be some python package available) could possibly merge for you...

Yes, we have had a look to this merge, but maybe it should be a yaml merge, not a line by line merge, to achieve some robustness. We need to be careful, the impact of a bad merge will probably be worse than leaving it untouched. 

I suggest trying it for Conan 2.0 (now it might be unexpected for some users, who don't want their settings.yml be messed with).

**Comment by memsharded** [comment]
I have had a look to the internals, to see if the first phase could be done now. The problem is that all past versions didnt store the ".original" settings, so we would need to maintain the old mechanism, together with the new one, and it is probably not worth as we will start working on Conan 2.0 soon. Lets wait for this for 2.0 then.

**Comment by memsharded** [comment]
Merging yaml files has finally been discarded at the moment. Maybe we will reconsider in 2.X, but not now.

The settings migration has been simplified, made explicit (with a comment at the beginning of the file, that can be removed)
