### ISSUE TITLE
Include guard for `conanbuildinfo.cmake`

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#6980]
Sometimes `conanbuildinfo.cmake` has to be imported from several directories in a project depending on how it is being built. For example please see https://github.com/mpusz/units where developer can run CMake either from top or `src` directory and both of them have to import this file. 

Right now including the file twice crashes CMake because of duplicated definitions. Could you please add the CMake include guard (https://cmake.org/cmake/help/latest/command/include_guard.html) to the top of generated file so it is often imported only once?

**Comment by memsharded** [comment]
We cannot include this guard, it is only from CMake 3.10, and we need to support older CMake versions.

**Comment by mpusz** [comment]
In such a case you can do something like this:

```
if(__CURRENT_FILE_VAR__)
  return()
endif()
set(__CURRENT_FILE_VAR__ TRUE)
```

**Comment by memsharded** [comment]
Closing as outdated, ``cmake`` legacy generator
