### ISSUE TITLE
Looking for recommendation on project directory structure

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#6985]
In general we try to layout our CMake projects alog the lines of : https://cliutils.gitlab.io/modern-cmake/chapters/basics/structure.html

So we have dir structure that look like:
- CMakeLists.txt
- docs
- src
  - CMakeLists.txt
  - fred.cpp
  - sue.f90    (Yes we still use FORTRAN)
- test
  - CMakeLists.txt
  - gtest_main.cpp
  - my_test.cpp

I will likely be using VSCode and Vscode-cmake-tools for interacting with the projects (both win/*nix) ... and the final builds will happen using a Jenkins CI instance.

So the questions are:

1.  I have been using the cmake-conan tools, to embed everything into the CmakeLists.txt file. Is this still a good way, or should I use the conanfile.py approach.

2. Where does the insertion of conan belong? In the top level, the leaf level .... where should it go?

Thanks and regards...

**Comment by memsharded** [comment]
>1. I have been using the cmake-conan tools, to embed everything into the CmakeLists.txt file. Is this still a good way, or should I use the conanfile.py approach.

Well, it is not possible to use only cmake-conan if you are creating packages too with this repo. Is it for consuming existing packages only?

> 2. Where does the insertion of conan belong? In the top level, the leaf level .... where should it go?

Yes, typically the root of the project is a good place. It might be put in a subfolder, but as a rule of thumb, it will be a bit more convoluted.

**Comment by ShamanTcler** [comment]
Yes this is for package consumers only. Geared towards the model of a "main_app" built on top of a local built library, plus 3'rd party libs supplied by Conan.

We have an Artifactory CE instance running  to store 3'rd party and in house developed packages.  So trying to make this as Phd (push here dummy) as possible .... 

Many people like the directory segregation that above link provides.

**Comment by memsharded** [comment]
Closing this ticket as outdated:

- Conan got long time ago the ``layout()`` feature to implement and define project directory structure
- The Conan 2 new ``cmake-conan`` integration based on CMake new dependency providers is a new paradigm, completely different to the previous legacy 1.X one

Please create new tickets if necessary for any further question
