### ISSUE TITLE
[bug] gcc-10 not supported by settings.yml

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#6986]
Now as we have a gcc-10 released and even a Conan docker image for it, we really need gcc-10 on the list in settings.yml. Otherwise, we end up with errors like here: https://travis-ci.com/github/mpusz/units/jobs/330767961.

**Comment by memsharded** [comment]
Gcc 10 is already in the default settings: https://github.com/conan-io/conan/blob/50f205953f520981ce817c90bb3b6e379b3e0674/conans/client/conf/__init__.py#L63

We will explicitly add 10.1 for those who want to control the minor version too, but it should work now.

**Comment by mpusz** [comment]
Thanks. I see now that the issue is fixed in 1.25.0 but that conan-package-tools downgraded the version to 1.24.1 (https://travis-ci.com/github/mpusz/units/jobs/330767961#L460) that does not have this setting yet :-( Hopefully, conan-package-tools will catch up soon...

**Comment by memsharded** [comment]
I guess conan-package-tools will update relatively soon, and if not, it is not an issue, it is enough to ``pip install conan==1.25.0 --upgrade`` after installing conan-package tools, to get the latest conan. So I think this can be closed now, thanks for reporting!

**Comment by uilianries** [comment]
I made a mistake when updating the latest version for CPT. It will be fixed ASAP.

**Comment by mpusz** [comment]
Thanks!

**Comment by czoido** [comment]
Hi @mpusz, we have just released conan package tools 0.32.4 with that fix.
