### ISSUE TITLE
[feature] full_build_requires in conaninfo.txt

### ISSUE THREAD

**Issue by barmaglot27** [conan-io/conan#6989]
I am trying to implement promotion of a packages as move of package and **ALL** of its dependencies from develop to release channel and placing an alias for redirection. When we build final product that needs to be packaged into RPM we often have conflicting requirements that cannot be resolved because of semver:
binB/1.0.0@company/develop -> libA/**1.0.0**@company/develop
binC/1.0.0@company/develop -> libA/**2.0.0**@company/develop

So, when we build binB and binC - we specify all requires as build_requires and package libA with each one, and later have special packaging project: rpm/1.0.0@company/develop that depends on binB and binC. Everything works but I am having problem locating all dependencies using conan produced artifacts. conaninfo.txt of both binB and binC is empty - it lists only requires (patterns used for package id sha) and full_requires. In our case they are empty. build_requires is not there.

How breaking this feature would be? I could find few places in model/info.py, client/conan_api.py and build_info/conan_build_info.py where full_requires are referenced. I guess adding full_build_requires with resolved package ids/revs should be in the same places. What do you think of a complexity of such feature? Am I missing something?

**Comment by memsharded** [comment]
Hi @barmaglot27 

> I am trying to implement promotion of a packages as move of package and ALL of its dependencies from develop to release channel and placing an alias for redirection.

Let me suggest: we are not recommending anymore doing promotions based in channel. Packages should be completely immutable (this is a general devops accepted good practice), and modifying channels have some implications regarding the binaries for example. We recommend instead doing promotions based on repositories. With Artifactory (also with the CE free edition) you can have multiple repositories and copy packages efficiently from one to the other (they don't use extra storage space).

Also, we recommend that such promotions would be based on the Artifactory BuildInfo. This still is a bit unstable, but it is definitely the way to go. The BuildInfo can be computed from different lockfiles, so using lockfiles is definitely the suggested way of doing this. A:

```bash
$ conan graph lock <...> --build
```
Will capture a complete reference of all packages in your graph, plus all the build requires. Including down to the recipe and package revisions (also recommended, they will become the default in Conan 2.0). With this lockfile, you will be able to run these promotions between repositories. It is likely that the lockfiles will be stored inside the packages in the future, in a similar way to the ``conaninfo.txt``


> How breaking this feature would be? I could find few places in model/info.py, client/conan_api.py and build_info/conan_build_info.py where full_requires are referenced. I guess adding full_build_requires with resolved package ids/revs should be in the same places. What do you think of a complexity of such feature? Am I missing something?

Yes, this will probably require a big effort, which we cannot afford now. And given that, based on the experience acquired from many different users, we are starting to recommend this approach, I'd suggest having a look. Please do not hesitate to ask if you have any question.

**Comment by barmaglot27** [comment]
I spent a week researching revisions. We are indeed going to enable them and re-bootstrap all packages that we had in our Artifactory. The feature seams to add more clarity in package to recipe relationship. However, conaninfo.txt does not capture dependency revisions and without generated conan.lock cannot be used for any reference.
Was surprised that conan.lock is not automatically packaged along with conaninfo.txt and conanmanifest.txt. I think it is easy to implement or should I meanwhile package it myself?

**Comment by memsharded** [comment]
Conan 2.0 made possible to make packages binaries and ``package_id`` to depend on ``tool_requires`` versions. In recipes and also globally via ``conf``.

> Was surprised that conan.lock is not automatically packaged along with conaninfo.txt and conanmanifest.txt. I think it is easy to implement or should I meanwhile package it myself?

You might want to track https://github.com/conan-io/conan/pull/10261 for this feature. Lockfiles are not packaged by default in binaries, as binaries are resolved after the full dependency graph is resolved, so when the binary ``package_id`` can be computed, it is simply too late to be able to use the lockfile information. 

I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
