### ISSUE TITLE
[bug] deploy generator broken with 1.25.0

### ISSUE THREAD

**Issue by chhitz** [conan-io/conan#6992]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: any
  * Conan version: 1.25.0
  * Python version: 3.8.2

### Steps to reproduce (Include if Applicable)
* mkdir /tmp/conan-paho-mqtt
* conan install  paho-mqtt-cpp/1.1@ -g deploy -o *:shared=True

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
*:shared=True
[build_requires]
[env]

Installing package: paho-mqtt-cpp/1.1
Requirements
    paho-mqtt-c/1.3.1 from 'conan-center' - Cache
    paho-mqtt-cpp/1.1 from 'conan-center' - Cache
Packages
    paho-mqtt-c/1.3.1:bf0adb9a727594d902b6dc22b23c800d7707b38a - Cache
    paho-mqtt-cpp/1.1:698833d5e29368eb40ad7c3fd09f712da2722f78 - Cache

Installing (downloading, building) binaries...
paho-mqtt-c/1.3.1: Already installed!
paho-mqtt-cpp/1.1: Already installed!
ERROR: Generator deploy(file:deploy_manifest.txt) failed
[Errno 2] No such file or directory: '/tmp/conan-paho-mqtt/paho-mqtt-cpp/lib/libpaho-mqttpp3.so.1'
ERROR: [Errno 2] No such file or directory: '/tmp/conan-paho-mqtt/paho-mqtt-cpp/lib/libpaho-mqttpp3.so.1'
```

**Comment by memsharded** [comment]
Hi @chhitz 

I was able to reproduce.

Seems an effect of https://github.com/conan-io/conan/pull/6922

Could you please @uilianries have a look, and check if it is a regression? Thanks!

**Comment by uilianries** [comment]
@memsharded I can confirm that's a regression. However, the PR #6994 is able to fix it, I've validated it.
