### ISSUE TITLE
cmake find_package fails when using conanbuildinfo_multi.cmake

### ISSUE THREAD

**Issue by xoorath** [conan-io/conan#6998]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 
  * Compiler+version: cmake generator for visual studio 2019
  * Conan version: 1.24.0

### Steps to reproduce (Include if Applicable)
1. Create a conanfile requiring protobuf/3.9.1@bincrafters/stable. Also set the cmake and cmake_multi generators (only cmake_multi is relevant, but both are used in my description here)
2. run conan install
3. in your cmakelists.txt include conanbuildinfo_multi.cmake
4. in your cmakelists.txt run conan_basic_setup
5. in your cmakelists.txt try to run find_package(Protobuf REQUIRED)

Notice protobuf cannot be found. Switching to conanbuildinfo.cmake will allow protobuf to be found.

If I take note of Protobuf_LIBRARIES and Protobuf_INCLUDE_DIR from the working case (with conanbuildinfo.cmake) I can hard code  that manually and conanbuildinfo_multi.cmake will begin to work. Obviously not an ideal work around, but hopefully useful info.

### Example cases

All cases use the following project structure:
```
/cmakelists.txt
/conanfile.txt
/subdir/
/subdir/cmakelists.txt
/Bin/
```

Notes: 
1. Bin is where cmake and conan install are run from, both being passed `..`
2. `/conanfile.txt` does not change through the following cases, the contents are as follows.
3. Each case I delete the Bin directory and run conan install. Each run of conan install indicates the dependencies are already installed.

`/conanfile.txt`
```
[build_requires]
protoc_installer/3.9.1@bincrafters/stable
[requires]
protobuf/3.9.1@bincrafters/stable
[options]
[generators]
cmake
cmake_multi
```

## Case 1) conanbuildinfo_multi
`/cmakelists.txt`
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake)
conan_basic_setup(TARGETS)
```
`/subdir/cmakelists.txt`
```
find_package(Protobuf REQUIRED)

message("Protobuf_LIBRARIES is ${Protobuf_LIBRARIES}")
message("Protobuf_INCLUDE_DIR is ${Protobuf_INCLUDE_DIR}")
```

output from cmake:
```
-- Current conanbuildinfo.cmake directory: C:/Users/jathomso/Documents/redacted/Bin
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindProtobuf.cmake:626 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  redacted/CMakeLists.txt:52 (find_package)
```

## Case 2) conanbuildinfo
`/cmakelists.txt`
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
```
`/subdir/cmakelists.txt`
```
find_package(Protobuf REQUIRED)

message("Protobuf_LIBRARIES is ${Protobuf_LIBRARIES}")
message("Protobuf_INCLUDE_DIR is ${Protobuf_INCLUDE_DIR}")
```

output from cmake:
```
-- Found Protobuf: C:/.conan/c5c49a/1/lib/libprotobuf.lib (found version "3.9.1")
Protobuf_LIBRARIES is C:/.conan/c5c49a/1/lib/libprotobuf.lib
Protobuf_INCLUDE_DIR is C:/.conan/c5c49a/1/include
```

## Case 3) conanbuildinfo_multi with hard-coded path
`/cmakelists.txt`
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake)
conan_basic_setup(TARGETS)
```
`/subdir/cmakelists.txt`
```
set(Protobuf_LIBRARIES C:/.conan/c5c49a/1/lib/libprotobuf.lib)
set(Protobuf_INCLUDE_DIR C:/.conan/c5c49a/1/include)

find_package(Protobuf REQUIRED)

message("Protobuf_LIBRARIES is ${Protobuf_LIBRARIES}")
message("Protobuf_INCLUDE_DIR is ${Protobuf_INCLUDE_DIR}")
```

output from cmake:
```
-- Found Protobuf: C:/.conan/c5c49a/1/lib/libprotobuf.lib (found version "3.9.1")
Protobuf_LIBRARIES is C:/.conan/c5c49a/1/lib/libprotobuf.lib
Protobuf_INCLUDE_DIR is C:/.conan/c5c49a/1/include
```

Note: in case 3 here I still can't compile correctly. I need to run case 2, then case 1 - and then I can compile. The protobuf custom build steps fail to find the protobuf compiler if I go just with case 3.

**Comment by memsharded** [comment]
Hi @xoorath 

I think you are mixing different concepts. If you are using the ``cmake_find_package`` generators, most of the ``cmake`` generator stuff shouldn't be necessary. Definitely not defining ``TARGETS`` as you aim to use ``find_package()``. The only thing that the ``cmake`` generators will do in this case is set-up some build configuration, like the RPATH or MD /MT runtime. You can skip that part at the moment to make it simpler to try.

Then, the ``cmake_find_package`` generators will put one .cmake file per dependency in your "conan install" folder. You need to point cmake CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH to that folder so they are found. You could try something like:

```cmake
set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR} ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR} ${CMAKE_PREFIX_PATH})

find_package(Boost REQUIRED)
find_package(Poco REQUIRED)

add_executable(timer timer.cpp)
target_link_libraries(timer Poco::Poco Boost::Boost)
```

**Comment by xoorath** [comment]
Hey @memsharded thanks for getting back to me quickly.

My goal is actually to not use find_package, but it was the only way I could seem to get the function `protobuf_generate_cpp` working.

Is there another way to get the functions and macros from a package in conan working inside my cmake files?

Unrelated to that question, but are you suggesting that if I use find_package and name my dependancies normally (rather than using CONAN_PKG::libname) that this will use conan libaries properly? Is there an advantage to using conanbuildinfo*.cmake and conan_basic_setup, with CONAN_PKG::libname (or similar) versus doing what you mention in your reply?

---

edit: I'm updating my understanding. Please bear with me :) I see what you mean that cmake_find_package is it's own generator that I can use if I need to use find_package. I've modified my project to use cmake_find_package, find_package each dependancy, and reference them normally when linking. I'm still finding that protobuf_generate_cpp is not found, however. I'm not sure why find_package manages to provide me that method but it doesn't when I'm using cmake_find_package.

**Comment by memsharded** [comment]
Well, the truth is that we are likely going to move to ``find_package()`` in cmake as the way to get dependencies, as it is the idiomatic way in cmake. We will move the "build" related things to a toolchain file. Probably in Conan 2.0 using find_package will be the canonical way to use dependencies in CMake. 

> Is there another way to get the functions and macros from a package in conan working inside my cmake files?

Yes, please do inspect the generated ``conanbuildinfo.cmake`` file. You will have variables for everything, including the BUILD_DIRS of the protobuf package, so you can ``include()`` the files packaged there that will contain the macros. Or add the directories to CMAKE_MODULE_PATH and do the ``include()`` without the path, could work too.

> Unrelated to that question, but are you suggesting that if I use find_package and name my dependancies normally (rather than using CONAN_PKG::libname) that this will use conan libaries properly? 

Yes, if you use the ``xxxxx.cmake`` files created by the Conan ``cmake_find_package`` generators, they will also use correctly the Conan packages.

Is there an advantage to using conanbuildinfo*.cmake and conan_basic_setup, with CONAN_PKG::libname (or similar) versus doing what you mention in your reply?

At the moment, yes, they are doing some setup of build things (like setting the Visual MT/MD runtime correctly, or handling RPATH removal, or checking the compiler and compiler version) that are quite useful. They are not strictly necessary and the CMakeLists.txt could handle them too, but are convenient.

> I'm still finding that protobuf_generate_cpp is not found, however. I'm not sure why find_package manages to provide me that method but it doesn't when I'm using cmake_find_package.

This could be an issue with the current protobuf package, not Conan itself. The recipes need to declare which cmake files are exposed to consumers. Which package are you using? Maybe it deserves an issue in the conan-center-index repo.

**Comment by xoorath** [comment]
Thanks @memsharded . I'll try to recap again so you can correct me.

1) Using find_package is preferred in the sense that it's more cmake style.

2) Using find_package wont give me the convenience that conanbuildinfo*.cmake offers, such as selecting the right debug/optimized variant of the dependancies, or setting the BUILD_DIRS and other package settings.

I'm a bit confused about your last point. Isn't it strange that when using cmake_multi and cmake_find_package the function is not available but when running the cmake generator it is? Or do packages specify what to set per generator?

Today I'll try switching back to cmake_multi, as I think it has everything I want unless there really is a bug there. I think I just need to use the BUILD_DIRS like you're saying.

The package is protobuf/3.9.1, by the way.

**Comment by xoorath** [comment]
Hey @memsharded - I've got it working now. TL-DR I just needed to use include which I could get the path for using BUILD_DIRS like you said. The rest of this post is for other future readers.

Thanks!

--- 
For the benefit of anyone else who comes across this:
1) I switched to use the `cmake_multi` generator in my conanfile.txt. 
2) I included `protoc-config.cmake` using the `BUILD_DIRS` like James suggested here. That looks like: `include(${CONAN_BUILD_DIRS_PROTOC_INSTALLER_RELEASE}cmake/protoc-config.cmake)`
3) the macro `PROTOBUF_GENERATE_CPP` and function of the same name in lowercase were available, but only if I set `protobuf_MODULE_COMPATIBLE` to **ON**. **I did not do this**, because there were issues with visual studio expecting the generated source files to be in a different spot than they were actually being generated; causing the custom build step to succeed but compilation to fail.
4) Instead I used the new syntax:
```(cmake)
protobuf_generate(
 LANGUAGE cpp
 TARGET MyTargetNameHere
 PROTOS ${MyProtoFileSourcesHere})
```
This had to be added below my target in order to work.

5) After this I just had to fix my include directories to make sure the path I wanted to use in my source could find the generated code, and the generated code could find itself (since it doesn't use relative paths). For me this looked like:
```(cmake)
# For my code to be able to use <The/Path> instead of <Include/The/Path>
target_include_directories(MyTargetNameHere PUBLIC ${CMAKE_BINARY_DIR}/MyTargetNameHere /Include)
# for generated code to be able to use "Include/The/Path"
target_include_directories(MyTargetNameHere PUBLIC ${CMAKE_BINARY_DIR}/MyTargetNameHere )
```
This last step is entirely based on how I setup my project and structures. Just mentioning that something like this will need to be done and not to expect it to be automatic.
