### ISSUE TITLE
[question] search across all local defined remotes

### ISSUE THREAD

**Issue by ailisp** [conan-io/conan#7000]
Is it possible to search all local saved remotes, for example I have:
```
conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
bintray: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]
```
It would be great if I can make "search all remotes", show search result and what remote it belongs to, and made this default as i do conan search. How to do that? Thank you! (I got #7000 btw :smiley: ) 
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Nice 7K issues already in conan :)

Yes, it is possible to use the ``-r=all`` or ``--remote=all`` shortcut, and it will iterate all remotes. Please try that and tell if that helped.

**Comment by ailisp** [comment]
Thanks, it works!
