### ISSUE TITLE
[question] Execute Unittests in build section cross-toolchain?

### ISSUE THREAD

**Issue by steinerthomas** [conan-io/conan#7001]
As we have learnt in the conan advanced training, the best way to run unittests is in the build section of a conan recipe. See: [ConanTrainingAdvanced.pdf](https://github.com/conan-io/training/blob/master/ConanTrainingAdvanced.pdf) - Exercise 19 – Unit tests with gtest

How does this actually work, when the build-server is building a package with a toolchain for another architecture? You won't be able to run the unittests on the build-server then. How would you suggest to handle this?

**Comment by memsharded** [comment]
Hi @steinerthomas 

When cross-building, you can't run the unit test in the build architecture (unless you have some kind of remote environment, is this the case?). So the typical flow is to skip the tests. You can see it for example in the ``test()`` function of the ``test_package/conanfile.py`` automatically generated with ``conan new``:

```python
    def test(self):
        if not tools.cross_building(self):
            os.chdir("bin")
            self.run(".%sexample" % os.sep)
```
So in your case, something like:

```python
    def build(self):
        cmake = CMake(self)
        cmake.configure(...)
        cmake.build(...)
        if not tools.cross_building(self):
            cmake.test()
            # or
            self.run("myunittest ....")
```

Please let us know if this works.

**Comment by steinerthomas** [comment]
Hi @memsharded 

Thanks for the quick reply.

We have a remote environment where we run the tests. Now we are building both, unit and integration tests in a separate conan package and execute them on this environment. (btw: we also collect the code coverage from both tests in our CI pipelines)

Running the unittests remote in the build section would make the conan recipe really complex I think. Or is there a easy way to do this? (I'm asking because you mentioned the remote environment)

If there is no easy way, we will keep it as we have it now.

**Comment by memsharded** [comment]
> Running the unittests remote in the build section would make the conan recipe really complex I think. Or is there a easy way to do this? (I'm asking because you mentioned the remote environment)

No, there is no easy way, unless you have setup some infra that allows this to run remotely, something like:

```python
def build(self):
      cmake = CMake(self)
      ...
      cmake.build()
      if tools.cross_build(self):
            if self.settings.os == "Linux" and self.settings.arch == "armv7":
                  self.run("scp MyRemoteArmv7env copy tests executables")
                  self.run("ssh MyRemoteArmv7env execute remotely those tests")
```

I think that in general this might be difficult, so probably the best is to keep them separately.
