### ISSUE TITLE
[bug] Failled to upload conan packafge to JFrog-Artifactory-Cpp-CE Server. 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by dovydas-girdvainis** [conan-io/conan#7005]
Hello everyone!

I am not sure that this issue belongs here, it is possible it should go to [Jfrog](https://bintray.com/jfrog), but I do not know how to report issues for them. 

My problem comes from conan uploading packages to a private Artifactory repository.  I followed all of the steps documented in [Artifactory Community Edition for C/C++](https://docs.conan.io/en/latest/uploading_packages/artifactory_ce.html) as well as within our Artifactory server web UI, and once I tried to upload a package I ran into the error `500 Server Error: Internal Server Error`. After a bit of digging within Artifactory logs it became clear, that local Checksum and the one that Artifactory calculates are different, thus rejecting the package. 

Is there any know solution for this?

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux Debian 10
  * Compiler+version: gcc8
  * Conan version: Conan version 1.25.0
  * Python version: 3.7.3
  *  JFrog-Artifactory-Cpp-CE : 7.4.3
 
### Steps to reproduce (Include if Applicable)
For clean setup:

```bash
sudo apt install python3.6
pip3 install conan
conan remote update artifactory https://[URL_TO_REPO] False
conan user -p testy_pwd -r artifactory testy
mkdir tmp
cd tmp
conan new hello/0.1 –t
conan create .
conan upload hello -r=artifactory 
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
Client side error (when calling `conan upload hello -r=artifactory `)
```
Uploading to remote 'artifactory':
Uploading hello/0.1 to remote 'artifactory'                                           
Uploading conanfile.py completed [1.72k]                                                 
ERROR: 500 Server Error: Internal Server Error for url: [URL_TO_REPO]/artifactory/api/conan/[REPO_NAME]/v1/files/_/hello/0.1/_/0/export/conanfile.py
Waiting 5 seconds to retry...
Uploading conanfile.py completed [1.72k]                                                 
ERROR: 
Error uploading file: conanfile.py, '500 Server Error: Internal Server Error for url: [URL_TO_REPO]/artifactory/api/conan/[REPO_NAME]/v1/files/_/hello/0.1/_/0/export/conanfile.py'
Uploading conanmanifest.txt completed [0.06k]                                            
ERROR: 500 Server Error: Internal Server Error for url: [URL_TO_REPO]/artifactory/api/conan/[REPO_NAME]/v1/files/_/hello/0.1/_/0/export/conanmanifest.txt
Waiting 5 seconds to retry...
Uploading conanmanifest.txt completed [0.06k]                                            
ERROR: 
Error uploading file: conanmanifest.txt, '500 Server Error: Internal Server Error for url: [URL_TO_REPO]/artifactory/api/conan/[REPO_NAME]/v1/files/_/hello/0.1/_/0/export/conanmanifest.txt'
ERROR: Execute upload again to retry upload the failed files: conanfile.py, conanmanifest.txt. [Remote: artifactory]
ERROR: Errors uploading some packages
```

I had to mask the sensitive information with *[URL_TO_REPO]* and *[REPO_NAME]*, otherwise the error message is unchanged

Server side error: 

```
2020-05-12T13:32:13.558Z ESC[1;32m[jfrt ]ESC[0;39m ESC[31m[WARN ]ESC[0;39m [645b9b24b4c0a876] [.r.ArtifactoryResponseBase:125] [http-nio-8081-exec-5] - Sending HTTP error code 409: Checksum policy 'LocalRepoChecksumPolicy: CLIENT' rejected the artifact '[REPO_NAME]:_/hello/0.1/_/0/export/conanmanifest.txt'. Checksums info: ChecksumsInfo{checksums={SHA-1=ChecksumInfo{type=SHA-1, original='50e01c65fa2e9b6a2dc109cb124fe8abeee99808', actual='da39a3ee5e6b4b0d3255bfef95601890afd80709'}, MD5=ChecksumInfo{type=MD5, original='null', actual='d41d8cd98f00b204e9800998ecf8427e'}, SHA-256=ChecksumInfo{type=SHA-256, original='null', actual='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'}}}
```

same as before, had to mask some information with *[REPO_NAME]*

**Comment by memsharded** [comment]
Hi @saukijan 

Thanks for your detailed report. I wanted to ask first if your Artifactory is running behind some infra, proxy, front like Apache/Nginx, that could be doing something different. A good quick check is to get an Artifactory CE (https://conan.io/downloads.html) locally in your computer, unzip, execute, (it will take about 3-5 minutes) and test locally. That will help to rule out if it is a pure server error, or could be in the Conan client. Could you please try that?

**Comment by dovydas-girdvainis** [comment]
@memsharded thanks for the quick response, Yes you are right about the Artifactory server running behind some infrastructure, however I am not sure of the details surrounding it at this moment.

I did as you suggested and installed Artifactory CE locally on my Linux Debian 10. It seems to be running perfectly, however it is an older version, it is 6.19 and not 7.4.3. 

I am not certain, but I think my installation came from [bintray](https://bintray.com/jfrog/product/JFrog-Artifactory-Cpp-CE/view) and not from [conan.io](https://conan.io/downloads.html)

Could that be the problem?

**Comment by memsharded** [comment]
> I am not certain, but I think my installation came from bintray and not from conan.io

conan.io/downloads are links to bintray, the installers are hosted in bintray

You can get latest Artifactory CE in https://bintray.com/beta/#/jfrog/product/JFrog-Artifactory-Cpp-CE?tab=packages too, just in case it is a version issue (but probably not)

> , Yes you are right about the Artifactory server running behind some infrastructure, however I am not sure of the details surrounding it at this moment.

Ok, please ask there to your IT or Devops team, ask about details and provide them with this issue, as well as the comparison to your local Artifactory, and let us know, lets see if we can help from our side. Thanks!

**Comment by dovydas-girdvainis** [comment]
I tried installing [bitnray 7.4.3](https://bintray.com/jfrog/product/JFrog-Artifactory-Cpp-CE/view) version locally as well, however it seems to fail setting it's ownership to **artifactory:artifactory** during the installation: 
```bash
Selecting previously unselected package jfrog-artifactory-cpp-ce.
(Reading database ... 203511 files and directories currently installed.)
Preparing to unpack jfrog-artifactory-cpp-ce-7.4.3.deb ...
Checking if artifactory data directory exists
Removing tomcat work directory
Unpacking jfrog-artifactory-cpp-ce (7.4.3) ...
Setting up jfrog-artifactory-cpp-ce (7.4.3) ...
Resolved artifactory.user (artifactory) from /opt/jfrog/artifactory/var/etc/system.yaml
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
chown: invalid user: ‘artifactory:artifactory’
Adding the artifactory service to auto-start... DONE

************ SUCCESS ****************
The Installation of Artifactory has completed successfully.

NOTE: It is highly recommended to use Artifactory with an external database (MySQL, Oracle, Microsoft SQL Server, PostgreSQL, MariaDB).
      For details about how to configure the database, refer to https://service.jfrog.org/installer/Configuring+the+Database

Start Artifactory with:
> systemctl start artifactory.service

Check Artifactory status with:
> systemctl status artifactory.service


Installation directory was set to /opt/jfrog/artifactory
You can find more information in the log directory /opt/jfrog/artifactory/var/log
System configuration templates can be found under /opt/jfrog/artifactory/var/etc
Copy any configuration you want to modify from the template to /opt/jfrog/artifactory/var/etc/system.yaml

Triggering migration script, this will migrate if needed ...
chown: invalid user: ‘artifactory:artifactory’
[WARN] Could not set owner of [/opt/jfrog/artifactory/var/etc] to [artifactory:artifactory]
Processing triggers for systemd (241-7~deb10u2) ...

```
Once the installation is finished dameon fails with: 

```bash
● artifactory.service - Artifactory service
   Loaded: loaded (/lib/systemd/system/artifactory.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-05-12 19:16:38 CEST; 20s ago
  Process: 801 ExecStart=/opt/jfrog/artifactory/app/bin/artifactoryManage.sh start (code=exited, status=1/FAILURE)
```

Probably the easiest answer is to reinstall Artifactory CE with 6.19, however I am a bit curious as to why 7.4.3 would fail in such a way. Is it not the latest stable release?

**Comment by memsharded** [comment]
Hi @saukijan 

yes, I wouldn't expect it, which installer were you trying? The debian installer, the docker installer?

There are extended installation instructions here: https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory

There are a couple of notes there that might help, like:
> OS User Permissions

> When running Artifactory as a service, the installation script creates a user called artifactory which must have run and execute permissions on the installation directory.

> It is recommended to extract the Artifactory download file into a directory that gives run and execute permissions to all users such as /opt.

**Comment by dovydas-girdvainis** [comment]
I used a .deb package here is a [link](https://bintray.com/jfrog/artifactory-debs/download_file?file_path=pool%2Fjfrog-artifactory-cpp-ce%2Fjfrog-artifactory-cpp-ce-7.4.3.deb) to it. 

I installed it with `dpkg -i jfrog-artifactory-cpp-ce-7.4.3.deb` 

I had all of the dependencies previously from 6.19 so it just installed. (I used a similar procedure for 6.19 except I had to run `sudo apt install -f` to get the dependencies as well)

**Comment by dovydas-girdvainis** [comment]
Also I got the details for our setup, we are using Nginx as a reverse proxy with this configuration: 

```bash
 server {
  listen       *:443 ssl;

  server_name  server.privat server;

  ssl_certificate           /etc/ssl/private/server.privat.crt;
  ssl_certificate_key       /etc/ssl/private/server.key;
  ssl_session_cache         shared:SSL:10m;
  ssl_session_timeout       5m;
  ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers               ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS;
  ssl_prefer_server_ciphers on;

  index  index.html index.htm index.php;

  access_log            /var/log/nginx/server.privat_HTTPS.access.log combined;
  error_log             /var/log/nginx/server_HTTPS.error.log;

  location / {
    proxy_pass            http://127.0.0.1:8082;
    proxy_read_timeout    90s;
    proxy_connect_timeout 90s;
    proxy_send_timeout    90s;
    proxy_set_header      Host $host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header      Proxy "";
  }
}
```

**Comment by dovydas-girdvainis** [comment]
So I tried a clean install of 7.4.3 today (I purged all of the config files and unused dependencies). 

I installed the DEB package as a root and not with sudo just to make sure that all of the permissions are set correctly and it installed properly. 

After setting up the Artifactory I uploaded a hello package and it works as expected. 

I am guessing something is wrong with our NGinx setup and SSL, because I can not use SSL certification as a client

**Comment by memsharded** [comment]
Thanks @saukijan for following up and reporting. Glad to know that locally all works fine with different Artifactory versions.

What I think is that even if the Nginx has some configuration that is not working, still Artifactory 500 Internal Server Error is something worth investigating and reporting. I understand that your Artifactory hosted is not an Artifactory CE, but a full Artifactory PRO, because if they set it up with Nginx and everything, it might be working for other package types. Did I understand it correctly?
If it is Artifactory PRO, maybe you could also file an issue to customer support in JIRA: https://www.jfrog.com/jira/projects/RTFACT/issues/RTFACT-22121?filter=allopenissues (if you do so, please link the issue here too). I have asked for help too, because I don't know much about this Nginx setup.

**Comment by dovydas-girdvainis** [comment]
hi @memsharded, I just confirmed with IT that we are using Artifacory CE 7.4.3, the one I tested locally and NGinx was used to make it accessible via internal network

**Comment by memsharded** [comment]
> hi @memsharded, I just confirmed with IT that we are using Artifacory CE 7.4.3, the one I tested locally and NGinx was used to make it accessible via internal network

Thanks for the info. Then, there is some context that I am missing. Artifactory CE is for Conan packages, but it seems that your Artifactory CE installation is not properly setup. Was it ever working? Is it a new installation, that you are testing for the first time? I (maybe wrongly) assumed, that it was a working installation that was failing just now for the Conan use case.

**Comment by dovydas-girdvainis** [comment]
> Then, there is some context that I am missing.

Sorry for not being clear about that. It is the first time we are setting up Artifactory CE, so it never worked. 

> Artifactory CE is for Conan packages

We are currently trying to use it for our conan packages only, but as I see it is possible to upload artifacts to it through the REST API thought I have not tested that.  Am I wrong in think that way? 

> it seems that your Artifactory CE installation is not properly setup

I do not know how it was set up, but I can ask. Is there anything in particular that I should ask about the it? Also do you mean the setup via Artifactory Web UI for Admins or the [YAML Configuration File](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-ProductConfiguration) on the server itself?

**Comment by memsharded** [comment]
> We are currently trying to use it for our conan packages only, but as I see it is possible to upload artifacts to it through the REST API thought I have not tested that. Am I wrong in think that way?

No, Conan packages are uploaded directly with the Conan client. There is extra logic associated to it, not possible via the REST API only

The CE can also have generic repositories. For them, of course you can use the REST API and/or the JFrog CLI to upload and download files.

> I do not know how it was set up, but I can ask. Is there anything in particular that I should ask about the it? Also do you mean the setup via Artifactory Web UI for Admins or the YAML Configuration File on the server itself?

That is the thing, it might be difficult to help with that. We are not that experts in this configuration with Nginx, and not having the IT in this thread might make it not very efficient. Yes, I guess both, all the configuration of the YAML, the server. Can't you pull them into this thread to get their direct feedback?

**Comment by markgalpin** [comment]
Whenever we have a 500 error from artifactory, the key questions are: 1.) in the [artifactory-request.log](https://www.jfrog.com/confluence/display/JFROG/Logging#Logging-RequestLog.1) do you see the request with a 500 in it (7th field)?  If the answer is yes, look at the same timestamp in the [artifactory-service.log](https://www.jfrog.com/confluence/display/JFROG/Logging#Logging-ServiceLog.1) for the error (500 responses should never happen -- and generally represent a bug of some sort).  If the answer is NO, and the artifactory-service.log isn't just solid errors, then generally speaking something happened in between at a proxy level in the interim.  Given the behaviors here it sounds like an issue with the NGINX, though I don't see anything that obviously won't work.  Our [recommended NGINX configuration for SSL is here](https://www.jfrog.com/confluence/display/JFROG/Configuring+NGINX).

**Comment by dovydas-girdvainis** [comment]
Hey @markgalpin, thanks for your input and sorry for the long delay! 

I checked our *artifactory-request.log* and there seems to be only Responses with code 200 (for reference: [artifactory-request.log](https://github.com/conan-io/conan/files/4656973/artifactory-request.log))

Here is our [artifactory-service.log](https://github.com/conan-io/conan/files/4656992/artifactory-service.log) log file as well, naturally, some information is `[MASKED]` 

Also, after our IT applied the changes documented [here](https://www.jfrog.com/confluence/display/JFROG/Configuring+NGINX) our repository links got and extra `:` marker as shown in pictures bellow: 

![weird_link_1](https://user-images.githubusercontent.com/15049512/82450017-681ced00-9aac-11ea-9116-47cd0436e081.png)
 
![weird_link_2](https://user-images.githubusercontent.com/15049512/82450035-70752800-9aac-11ea-8e80-fd9387a577c2.png)

This extra colon causes:
```
Upload recipe to 'artifactory' failed: 400: Expected scheme name at index 0: '://[MASKED]/artifactory/api/conan/Artifactory-Conan/v1/files/'.. [Remote: artifactory]
```

Is it expected or something went wrong on our end?

I know that it would be best that our IT join this thread and explain things directly, however they are unable to do that at this time.

**Comment by markgalpin** [comment]
Something is wrong.  Try setting the base URL in the [general settings](https://www.jfrog.com/confluence/display/JFROG/General+System+Settings) including the protocol (e.g. http:// or https://)  Usually also the reverse proxy contains a line with the base URL: 

> proxy_set_header    X-JFrog-Override-Base-Url $http_x_forwarded_proto://$host:$server_port;

**Comment by dovydas-girdvainis** [comment]
Hello everyone, 

Sorry to have kept this issue unresolved for so long, our IT put this issue on the back burner for a while, but now it has been resolved. 

It seems something was messed up during the initial installation of Conan CE Artifactory, not sure what thought... 
After our IT did a clean install and used the provided NGinx configuration everything worked as expected! 

Anyways thank you all for your help with this issue!

**Comment by memsharded** [comment]
Hi @saukijan 

Thanks very much for following up and letting us know, very happy to know that everything is working now. Cheers!
