### ISSUE TITLE
Missing conan new (to create new project with basic directory and file layout)

### ISSUE THREAD

**Issue by netroby** [conan-io/conan#701]
By using Rustlang Cargo build tools ,we can easily using cargo new to quick start a new project. But we have none in conan. so if we can add a conan new command , to quick start a new project with CMakeLists.txt and conanfiles, it will be more easily to get things done.

**Comment by memsharded** [comment]
Are you sure? :) Please check it! 

```bash
$ conan --help
$ conan new Pkg/version@user/channel -t
```
