### ISSUE TITLE
[bug] Conan profiles cannot expand variables

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#7011]
When creating an environment variable in a profile, you cannot reuse this variables to expand to other variables.

### Environment Details (include every applicable attribute)
  * Operating System+version: linux ubuntu 18.04
  * Compiler+version: clang8
  * Conan version: 1.25.0
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)

following profile will not work, while trying to reuse `CLANG_DIR`
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CLANG_DIR=/lhome/user/Downloads/clang+llvm-8.0.1-x86_64-linux-gnu-ubuntu-14.04
PATH=[$CLANG_DIR/bin]
LD_LIBRARY_PATH=[$CLANG_DIR/lib]
CC=$CLANG_DIR/bin/clang
CXX=$CLANG_DIR/bin/clang++
LLVM_VERSION=8.0
CMAKE_C_COMPILER=$CLANG_DIR/bin/clang
CMAKE_CXX_COMPILER=$CLANG_DIR/clang++
```

However, this works, while make everything to an absolute path:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CLANG_DIR=/lhome/user/Downloads/clang+llvm-8.0.1-x86_64-linux-gnu-ubuntu-14.04
PATH=[/lhome/user/Downloads/clang+llvm-8.0.1-x86_64-linux-gnu-ubuntu-14.04/bin]
LD_LIBRARY_PATH=[/lhome/user/Downloads/clang+llvm-8.0.1-x86_64-linux-gnu-ubuntu-14.04/lib]
CC=/lhome/user/Downloads/clang+llvm-8.0.1-x86_64-linux-gnu-ubuntu-14.04/bin/clang
CXX=/lhome/user/Downloads/clang+llvm-8.0.1-x86_64-linux-gnu-ubuntu-14.04/bin/clang++
LLVM_VERSION=8.0
CMAKE_C_COMPILER=/lhome/user/Downloads/clang+llvm-8.0.1-x86_64-linux-gnu-ubuntu-14.04/bin/clang
CMAKE_CXX_COMPILER=/lhome/user/Downloads/clang+llvm-8.0.1-x86_64-linux-gnu-ubuntu-14.04/clang++

```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
example/1.0.0@mbition/stable: Calling build()
CMake Error at /lhome/user/builds/cmake-nightly-build/share/cmake-3.16/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  $CLANG_DIR/bin/clang.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
```

**Comment by memsharded** [comment]
From the docs https://docs.conan.io/en/latest/reference/profiles.html:

> In a profile you can declare variables that will be replaced automatically by Conan before the profile is applied. **The variables have to be declared at the top of the file, after the include() statements.**

**Comment by derived-coder** [comment]
@memsharded 
This works, nice. 
However, when I want to test this. I use a `virtualbuildenv`
I generate and source it `source activate_build.sh`, however, nothing is in my path. What is wrong?

**Comment by memsharded** [comment]
Ok, that would be a new, unrelated issue, please close this one and open a new one. 
Please explain what problem you are trying to solve. ``virtualbuildenv`` is an environment created with information from the dependencies packages (like build_requires) for:

```
 ret = {"CPPFLAGS": cpp_flags,
               "CXXFLAGS": cxx_flags,
               "CFLAGS": c_flags,
               "LDFLAGS": ld_flags,
               "LIBS": libs
```

but does not use the information from the profile.

**Comment by derived-coder** [comment]
https://github.com/conan-io/conan/issues/7014
