### ISSUE TITLE
[question] How to consume deployable package?

### ISSUE THREAD

**Issue by saimusdev** [conan-io/conan#7013]
**How can a required deployable package be automatically deployed if specified as a direct requirement?**

- **Conan version: 1.25.0**

### Sample use case

Given two packages `deployable-package` and `deploy-consumer-package` as follows:
```
├── deployable-package
|   ├── conanfile.py
|   └── resources
|       └── foo.txt
└── deploy-consumer-package
    └── conanfile.py
```
Bare in mind, it's just an example to illustrate the issue.

#### `deployable-package`

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from conans import ConanFile, tools

class DeployablePackage(ConanFile):
    name = "deployable-package"
    version = "2.0.0"
    description = """Just contains some files"""
    exports_sources = "resources/*"

    @property
    def default_user(self):
        return "developer"

    @property
    def default_channel(self):
        return "testing"

    @property
    def deploy_path (self):
        return "/tmp/some/path"

    def package_id(self):
        # This package will only contain some build-agnostic files
        self.info.settings.clear()
        self.info.options.clear()

    def package(self):
        self.copy("*", src="resources", dst="", keep_path=True)

    def deploy(self):
        # Verify that exists and create if it doesn't (automatically done by tools.mkdir())
        tools.mkdir(self.deploy_path)
        self.copy("*", src="", dst=self.deploy_path, keep_path=True)
```

#### `deploy-consumer-package`

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from conans import ConanFile
from os import path

class DeployConsumerPackage(ConanFile):
    name = "deploy-consumer-package"
    version = "2.1.0"  # major defined by deployable-package
    description = """Something is built"""
    exports_sources = "*"

    @property
    def default_user(self):
        return "developer"

    @property
    def default_channel(self):
        return "testing"

    @property
    def build_assets(self):
        return "/tmp/some/path"

    def requirements(self):
        self.requires("deployable-package/{}.0.0@developer/testing".format(self.version.split(".")[0]))

    # NOT IDEAL AT ALL
    # def imports(self):
    #     self.copy("*", root_package="deployable-package", dst="", keep_path=True)

    def build(self):
        # Once this is executed I'm sure, my dependency is installed in the system
        self.run("ls -l {}".format(self.build_assets))
        self.run("cat {}".format(path.join(self.build_assets, "*.txt")))
```

I want to know how to install `deploy-consumer-package`, so that tranparently and automatically, `deployable-package` is not only downloaded, but (built if necessary and) stored in the local Conan cache and also most importantly **installed into the system** (calling its `deploy()` function) **before the `consumer-package` is even built**.

I've tried with: `conan install` (with and without the `-g deploy` generator):
```
$ conan install deploy-consumer-package -g deploy

Configuration:
[settings]
[options]
[build_requires]
[env]

conanfile.py (deploy-consumer-package/2.1.0): Installing package
Requirements
    deployable-package/2.0.0@developer/testing from local cache - Cache
Packages
    deployable-package/2.0.0@developer/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
deployable-package/2.0.0@developer/testing: Already installed!
conanfile.py (deploy-consumer-package/2.1.0): Generator txt created conanbuildinfo.txt
conanfile.py (deploy-consumer-package/2.1.0): Generator deploy created deploy_manifest.txt
conanfile.py (deploy-consumer-package/2.1.0): Generated conaninfo.txt
conanfile.py (deploy-consumer-package/2.1.0): Generated graphinfo
# Deploy not actually performed ?!
```

### what am I missing?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by saimusdev** [comment]
Update: I know that a possibility for this is to use a `imports()` function in the `deploy-consumer-package`. 
But, what I want, is to install into a fixed path in the system, not a directory relative to my consumer `conanfile.py`

**Comment by saimusdev** [comment]
Update 2: I see now a note in your [`deploy()` documentation](https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-deploy) about this, but to me it's then unclear how to solve this use case:
> The deploy() method is designed to work on a package that is installed directly from its reference [...] All other packages and dependencies, even transitive dependencies will not be deployed, it is the responsibility of the installed package to deploy what it needs from its dependencies.

**Comment by danimtb** [comment]
@saimusdev have your tried using the [`deploy` generator](https://docs.conan.io/en/latest/reference/generators/deploy.html)?

It can be used as a regular ``genrator = "deploy"` in your recipe as well. That will allow you to get the package contents of `deployable-package` (similar to the `imports()`) to the installation folder of `consumer-package` and perform any required operation right before the build (like copying the contents to the system or whatever you want).

I have not tried and I don't know what you are trying yo achieve but that might work.

Another way of using the package contents without using "deploy", is getting the absolute routes from [self.deps_cpp_info](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-cpp-info) and using them at your wish in the build() method of the `consumer-package` recipe.

**Comment by saimusdev** [comment]
@danimtb that's more or less what I did, but instead of using the deploy generator and moving files (with `os` or `shutil` as sadly there are no `conan.tools.copy()` to move around files in the system, outside of the recipe / conan folder context) in the `build()` function, I did it in the `imports()`:
This is what I came up with:
```python
def imports(self):
    self.copy("*", src="resources", root_package="deployable-package", dst="build_resources/", keep_path=True)
    tools.mkdir(self.build_assets)
    with tools.chdir(self.imports_folder):
        for build_resource in glob.iglob("build_resources/*", recursive=True):
            # Grab install path
            dest = os.path.join(self.build_assets, build_resource)

            # Delete file if already exists (from previous build)
            if os.path.exists(dest):
                os.remove(dest)

            # Create remote path if not already exists
            tools.mkdir(os.path.dirname(dest))

            # Copy resource to system
            shutil.copy(src=build_resource, dst=dest)
```

What do you think? any better suggestions, obviously a part from using the `deploy` generator for the pure `import` part.

FYI - The concrete use case of what I'm trying to achieve is to have some asset files for the execution of some unit & component tests built during the `CMake` build available in the native system before the `build()` is started.

**Comment by memsharded** [comment]
It seems that this might be outdated with Conan 2, with things like the new ``deployers`` that even relocate some ``generators`` scripts making them relative to the deployed folder: https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html

Also, ``imports()`` was removed in Conan 2.

So I am closing this ticket as outdated, please open new tickets against Conan 2.X if necessary, thanks for your feedback.
