### ISSUE TITLE
[bug] How to virtual run a profile?

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#7014]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: clang8.0
  * Conan version:1.25.0
  * Python version:3.6.9

### Steps to reproduce (Include if Applicable)

my profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CLANG_DIR=/lhome/user/Downloads/clang+llvm-8.0.1-x86_64-linux-gnu-ubuntu-14.04
PATH=[$CLANG_DIR/bin]
LD_LIBRARY_PATH=[$CLANG_DIR/lib]
CC=$CLANG_DIR/bin/clang
CXX=$CLANG_DIR/bin/clang++
LLVM_VERSION=8.0
CMAKE_C_COMPILER=$CLANG_DIR/bin/clang
CMAKE_CXX_COMPILER=$CLANG_DIR/clang++
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
after generate a `virtualbuildenv` for my recipe and doing a `source activate_build.sh`
```
which clang
```
returns an error. Because it is not in my environment....

Please make it somehow possible that the profile can be sourced too.

**Comment by jgsogo** [comment]
Hi, @derived-coder .

Right now the logic is that the profile is used to generate/retrieve the binaries and the `virtualxxxenv` generator populates the environment with the variables **from the packages**. Changing this wouldn't be possible without breaking existing behavior and I don't think it would be a better approach.

Usually, you use the virtualenv generators to populate the PATH with applications that are packaged with Conan, so in your use-case, you could create a package for Clang (it can be an empty package) that populates the environment, that package can look for the clang installed in your system and add it to the PATH variable.

**Comment by derived-coder** [comment]
okay, that is a workaround. 
@jgsogo 
So you do not see a reason in order to implement this feature?

**Comment by jgsogo** [comment]
Maybe this is an important use case for you. If you try to explain it and gather some traction from the community this is something that we can consider for Conan 2.0.

**Comment by memsharded** [comment]
Closing this as staled.
