### ISSUE TITLE
optional or multiple toolchain for cross compiling building

### ISSUE THREAD

**Issue by georgevlad91** [conan-io/conan#7018]
Hello, 

I was trying to create a conan recipe which has the cross compilation optional, and the option can be set from cmd.
As I couldn't find something like that in documantation i improvised and i added an option flag "with_toolchain":
`options = {"with_toolchain": [True, False]}`
and added it as condition for build_requirements:
```
def build_requirements(self):
        if self.options.with_toolchain and self.settings.os == "Linux":
            self.build_requires("toolchain-linux-x86_64-glibc-2.17-gcc/5.5.0@_/_")
```
and as condition for sysroot flag:
```
        if self.options.with_toolchain and self.settings.os == "Linux":
            sysroot = os.environ.get("SYSROOT")
            extra_flags += " --sysroot=%s" % sysroot
```
From cmd i can issue` conan create . -o with_toolchain=True` and it works.

My questions are: 
1. Is there a better way to do that? I feel like I did not used the most elegant method to do it.
2. If I have two toolchains and i want to choose from cmd which one to use, and give my choice as a parameter from cmd (the path or something), how can I do that?

Thank you.

**Comment by jgsogo** [comment]
One approach would be to dynamically add the build_requires in your profiles. You can have one profile for each of your toolchains:

```
include(profile_for_linux_gcc5)

[settings]
some_custom_setting=glibc-2.17

[build_requires]
toolchain-linux-x86_64-glibc-2.17-gcc/5.5.0

[env]
SYSROOT=¿? <-- this can also be a variable populated by the build_requires recipe
```

When using one of these profiles, `build_requires` are _injected_ to all the packages in your `host` graph and you don't need to hardcode them in the recipe or to add any option to your recipes (you still need to handle the `sysroot`).

Let me know if you think this is improving your situation, and if you want to share with us some example recipes maybe we can give you more detailed information.

Thanks!

**Comment by georgevlad91** [comment]
This was very helpful. Don't know why I haven't thought about this option before. Thank you very much.

**Comment by jgsogo** [comment]
I'm closing this issue, if anything else is needed, feel free to open it again.

Thanks!
