### ISSUE TITLE
[feature] Print git commands when print_run_commands = True

### ISSUE THREAD

**Issue by cguldner** [conan-io/conan#7029]
It would be nice to have `git` commands from the `tools.Git` helper be printed out if the `print_run_commands` variable is set to `True`. Could even be a new configuration option if desired

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! 

Yes, probably it makes sense for commands using `Git` or `SVN` helpers, as we do for other helpers like `CMake`. Nevertheless I feel like it should output only the commands that are explicit in the recipes, but not other usages that Conan is doing in the internals (those commands could be using a git library instead of the command line).

wdyt? Should we print every usage of the command line or just those commands written in the recipes?

**Comment by cguldner** [comment]
@jgsogo I think it might make the most sense to have a new config option, maybe `print_git_commands`. This would be really nice so that it is more clear what is happening, especially when debugging issues in CI

**Comment by jgsogo** [comment]
I prefer not to add so many config options, it becomes harder to maintain and to understand. If the log output is good enough (probably something to improve) a `grep` over the lines should be enough to retrieve only those you are interested in.

My question was if you think that the output should contain only the commands that the user is running in the `conanfile.py` or also commands that Conan runs behind the scenes (like cloning the repository defined in the `scm` attribute)

**Comment by cguldner** [comment]
@jgsogo Oh I understand now. I'm thinking just the commands that are explicit in the conanfile. Otherwise the user might get confused. Maybe the commands that Conan executes behind the scenes could be logged if the trace level is debug?

**Comment by cguldner** [comment]
@jgsogo But I think the more important feature to implement for now is just the explicit logging of commands that the user runs

**Comment by memsharded** [comment]
Closed as solved in Conan 2.0

**Comment by memsharded** [comment]
Update: it will be in next 2.1
