### ISSUE TITLE
[question] Is there any automatic way to obtain package_info?

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7034]
When project automatically generated the pc files, in theory, one can use the info giving by pkg-config to automatically generate the cpp_info. currently I have to glob inside the package/pkgconfig directory to find the pc file list. Then loop through it to call the tools.PkgConfig() to obtain all info. I wonder is there any built-in tools can automatically generate this info?

So far, if I do not do this in package_info(), with cmake_find_package or cmake_paths generator, it gives me empty target, which has no library/flag at all.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @braindevices 

No, right now there is no way to automatically deduce the ``cpp_info`` in the ``package_info()`` method from cmake data. It is necessary to manually fill the ``package_info()`` method. So far, it has not been a big issue:

- The ``package_info()`` is usually not very long, it requires a few lines, that are written just once and not very difficult to write. And it is easy to understand and maintain in the long run.
- The process is the same for every build system, in case of big projects with heterogenous build systems, or in case of build system migrations or changes, it works very well to have things defined in ``package_info()`` in recipes.
- Parsing cmake files or caches will be a complicated task. To extract robust data from them it would require a huge amount of time, and even with that effort it will never be perfect. And not being very robust will require more time. ``PkgConfig`` is way more structured and simpler.

**Comment by braindevices** [comment]
For projects like gstreamer which create many libs/targets and the number of libs change when settings are different, automated package_info() will be very useful. For pure cmake projects which doe not create pc file normally export their targets. In this case it can be used simply expose the `package/lib/cmake` folder into current project. Patching their cmake script to automatic generate pc files is also feasible.

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

It is indeed possible to use the xxx-config.cmake files inside packages, as documented here: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html

However, this works only for CMake, for compatibility with other build-systems, it is necessary to fill the ``package_info()``, it is impossible to deduce the information from other sources robustly. Closing this ticket as resolved, but please re-open or create new tickets as necessary.
