### ISSUE TITLE
[bug] deploy generator cannot overwrite the symlinks

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7037]
When deploy to previously installed location with libs which contain symlink, it will fail with error:
```
ERROR: Generator deploy(file:deploy_manifest.txt) failed
[Errno 17] File exists
```
We should keep the behaviour consistent with libs which do NOT contain symlink: overwrite the destination.

### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 19.10, 20.04, Fedora30, 31
  * Compiler+version:
  * Conan version: develop
  * Python version: 3.7.5

### Steps to reproduce (Include if Applicable)
```
conan install <some package has symlinks> -if <some location previously installed to> -g deploy

conan install <some package has symlinks> -if <some location previously installed to> -g deploy
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: Generator deploy(file:deploy_manifest.txt) failed
[Errno 17] File exists
```

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/7044, will be in 1.25.2.
