### ISSUE TITLE
[question] Why conan cannot find my required package

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7038]
I have a package relies on opencv, so i put
```
class MypckConan(ConanFile):
    requires = "opencv/4.1.1"...
```
and i have "opencv/4.1.1@conan/stable" in local cache, and based on the documentation,

>  If you don’t add the @, Conan will interpret the argument as a pattern search and return all the packages that match the pattern .

this should allow conan to find opencv for mypkg, however, i got error:
```
opencv/4.1.1: Not found in local cache, looking in remotes...
```
but if i change to below, everything works, local cache found.
```
class MypckConan(ConanFile):
    requires = "opencv/4.1.1@conan/stable"...
```

Also my second question is, if i remove my local cache of `opencv-4.1.1` and use the former requires of `opencv/4.1.1`, i cannot even find it in remote:
> opencv/4.1.1: Trying with 'conan-center'...
> opencv/4.1.1: Trying with 'bincrafters'...
> opencv/4.1.1: Trying with 'conan-community'...
> ERROR: Failed requirement 'opencv/4.1.1' from 'conanfile.py'
> ERROR: Unable to find 'opencv/4.1.1' in remotes
> 
 but if if and use `opencv/4.1.1@conan/stable`, i found it in remote `conan-center`. This still does not comply with 
>  If you don’t add the @, Conan will interpret the argument as a pattern search and return all the packages that match the pattern .

**Comment by memsharded** [comment]
Hi @shelper 

When you define your requirements, you need to put them explicitly. If you have in your cache or in your server ``opencv/4.1.1@conan/stable``, you need to put in your recipe:

```python
class MypckConan(ConanFile):
    requires = "opencv/4.1.1@conan/stable"
```

The ``opencv/4.11@`` syntax is for command-line only, to differentiate it from a path, as the ``conan install`` command accepts either a path or a reference (we are changing this in Conan 2.0 new command line)

> If you don’t add the @, Conan will interpret the argument as a pattern search and return all the packages that match the pattern .

This only applies to the ``conan search`` command but not for recipes.

Please let me know if this helps.

**Comment by shelper** [comment]
that is clear, thanks!
