### ISSUE TITLE
[bug] conan search with recipe reference, does not work with artifactory

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#7040]
Conan search does not work as expected, especially with the table mode

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: gcc8
  * Conan version: 1.25.0
  * Python version: 3.6.9
  * Artifactory Version 6.18.1

### Steps to reproduce (Include if Applicable)
 Here see all my commands and output
```
conan install zlib/1.2.11@company/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Installing package: zlib/1.2.11@company/stable
Requirements
    zlib/1.2.11@company/stable from 'public-abc' - Cache
Packages
    zlib/1.2.11@company/stable:d50a0d523d98c15bb147b18fa7d203887c38be8b - Cache

Installing (downloading, building) binaries...
zlib/1.2.11@company/stable: Already installed!
 user@home  ~/Downloads  conan search zlib/1.2.11@               
ERROR: Recipe not found: 'zlib/1.2.11'
 user@home  ~/Downloads  conan search zlib/1.2.11@ -r public-abc 
ERROR: Recipe not found: _/zlib/1.2.11/_. [Remote: public-abc]
 user@home  ~/Downloads  conan search "zlib/*" -r public-abc    
Existing package recipes:

zlib/1.2.11@company/stable
```

Why is `conan search zlib/1.2.11@ -r public-abc ` not working?

**Comment by memsharded** [comment]
You are using an erroneous search pattern. The ``conan search zlib/1.2.11@`` means, look for all binaries of the recipe reference ``zlib/1.2.11`` without user/channel. You want to do ``conan search zlib* -r=remote`` or ``conan search zlib/1.2.11* -r=remote``

**Comment by derived-coder** [comment]
@memsharded 
This does not work either, you have to use quotes for `*` search
```
 user@home  ~/sources/conan  conan search zlib* -r=public-abc
zsh: no matches found: zlib*
 user@home  ~/sources/conan  conan search "zlib*" -r=public-abc
Existing package recipes:

zlib/1.2.11@company/stable
```

Please compare also with the documentation: https://docs.conan.io/en/latest/reference/commands/consumer/search.html#tabular-output

My commands are correct. When I execute all this commands with conan-center, it will work.
There is a bug with the artifactory used I guess. That why I have added the artifactory version.

**Comment by memsharded** [comment]
Depending on the terminal you need to add quotes, it is not related to Artifactory vs ConanCenter. In Windows it can work without quotes, but in Linux you typically need to quote arguments with "*" otherwise they expand to the local folder before being processed by Conan (this is why the one complaining is ``zsh``, not Conan).

Please post here the result of 
```bash
$ conan search "zlib*" -r=public-abc
$ conan search "zlib*" -r=conan-center
```

**Comment by derived-coder** [comment]
@memsharded 
this worked.

```
 user@home  ~  conan search "zlib*" -r=public-abc                     
Existing package recipes:

zlib/1.2.11@company/stable
 user@home  ~  conan search "zlib*" -r=conan-center
Existing package recipes:

zlib/1.2.8
zlib/1.2.8@conan/stable
zlib/1.2.9@conan/stable
zlib/1.2.11
zlib/1.2.11@conan/stable
```

**Comment by memsharded** [comment]
Ok, thanks for the info @derived-coder 

Then, it is not an issue, it is working correctly. Can we close this issue?

**Comment by derived-coder** [comment]
@memsharded 
no, I still have the issue:
```
conan search "zlib/1.2.11@" -r public-abc
ERROR: Recipe not found: _/zlib/1.2.11/_. [Remote: public-abc]

conan search zlib/1.2.11@ -r public-swf  
ERROR: Recipe not found: _/zlib/1.2.11/_. [Remote: public-abc]
```

doesn't matter, wheter I quote or not quote.

**Comment by memsharded** [comment]
If you specify ``"zlib/1.2.11@"`` you are specifying the FULL reference, it is not searching for recipes, it is looking for binaries belonging to ``"zlib/1.2.11`` conan-center package. You do NOT have that package in your remote, it seems you only have ``zlib/1.2.11@company/stable`` in your remote:

- Don't use a full reference to search for recipes
- Use a full reference to search for binaries

**Comment by memsharded** [comment]
Doesn't seem a bug, working as expected, can be closed.
