### ISSUE TITLE
[question] deps_cpp_info empty in test_package recipe

### ISSUE THREAD

**Issue by Manu343726** [conan-io/conan#7042]
As part of the `test_package` of my tinyrefl package I'm trying to `build_require` its codegen tool, which is packaged as `tinyrefl-tool`. I'm also changing all the recipes to make them version and channel agnostic, to make packaging easier (Version is read from git tag info). My `test_package` recipe is as follows:

``` python
class TinyreflTestPackage(ConanFile):
    generators = 'cmake'

    def build_requirements(self):
        self.build_requires('tinyrefl-tool/{}'.format(self.deps_cpp_info['tinyrefl'].version))
```

But recipe processing fails because there's no ' "tinyrefl"'  entry in `deps_cpp_info`, even if the dependency exists (The dependency between a `test_package` and its tested package is real but implicit, right? At least it exists in generators output).

Maybe this dep info is missing? Maybe it's using another key?

Thank you.
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Manu343726 

You are trying to use a downstream information only in the upstream process. The ``deps_cpp_info`` is only fully available when you are building or packaging, but not when you are computing the dependency graph, and ``build_requirements()`` is in this case. 

We are introducing the CONAN_V2_MODE variable, to start trying running things and prepare for Conan 2.0. Conan 2.0 will raise when you access an "unavailable" attribute in one method that doesn't have access to that info.

**Comment by memsharded** [comment]
Maybe you can try checking the ``self.requires`` instead.

**Comment by Manu343726** [comment]
Hi, checking `self.requires` worked, thank you.
