### ISSUE TITLE
[question] Why are armv7ve and armv7-a not defined?

### ISSUE THREAD

**Issue by saimusdev** [conan-io/conan#7045]
### Doubts & concerns

- Is there a reason why the ARMv7ve architecture is non-existent in the settings YAML?
- Are binaries built for `armv7ve` and `armv7-a` (which I assume you defined as `armv7`, correct me if I'm wrong) ABI compatible? I would assume that code built for `armv7-a` could run without any issues in a `armv7ve` processor, but is the opposite also right? What about if [Virtualization Extensions](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0438d/CHDCHAED.html) are used when building a binary with `settings.arch.armv7ve` and run into a `armv7-a` processor?

 ### Motivation
The doubt arised, once I found that `gcc` does indeed define `-march=armv7ve` as well as `-march=armv7-a` flags and I would like to assume that `settings.arch` values have a one-to-one relationship with those flags in GCC.

### Request
If this is really missing, please add all required ARM architectures varinats that would yield ABI incompatible binaries (for armv7, armv8,...) 

Thanks for your prompt reply.

**Comment by jgsogo** [comment]
Hi, @saimusdev 

We provide in the default `settings.yml` a set of settings that are commonly used by our users and  we try to do our best on the helpers (CMake, Autotools,...) to take into account those settings and transform them into the proper flags to the build system.

You can always modify the `settings.yml` file to add more architectures or whatever you want, you can even store that file and share it with the facilities of `conan config install` command. Also, you can write your own build helpers, include them into a `python_requires` and use them in your recipes.

We aren't experts regarding every C++ field, there is a myriad of architectures, compilers and build systems out there, and we cannot cover all of them. I really don't know if those architectures are ABI compatible or not, and I'm not sure if we should add all the ARM architectures variants if we are not able to support them.

If you want a specific architecture to be included, we would need to investigate it and see how Conan settings should be translated to it. It would be really appreciated to have a minimum reproducible example (a docker image?) we can work with and check the issues you mention in your comment. Can you help us to walk this path?

**Comment by saimusdev** [comment]
Ok, I understand.

As we've recently learnt that those variants might have e.g. ARM VFP4 vs VFP3 instruction sets,
https://embeddedartistry.com/blog/2017/10/11/demystifying-arm-floating-point-compiler-options
, which might lead to non bijective ABI compatibility across the different processor platforms, we've adopted your proposal of **adding those architecture variants to our `settings.yml`**, thus having a "proprietary" `settings.yml`, instead of using your standard one.

Thanks for your insights.

Regarding providing a dockerized environment to test, it's not something we have somewhere available that we can provide for you to test.

Thanks again, feel free to close the issue.

**Comment by jgsogo** [comment]
Thanks for your comprehension. We would love to add all these settings, but it would be too much burden for the Conan client and for us to maintain all of them.
