### ISSUE TITLE
[feature] Add config option to scm to not auto checkout the repo

### ISSUE THREAD

**Issue by cguldner** [conan-io/conan#7049]
There are times where I don't want the source of the repository to automatically be checked out just by having the `scm` object in the conanfile.py. I know I could just use my own custom attribute for that, but I want to use the `scm` object because it is documented and forces consistency

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The ``scm`` attribute doesn't checkout anything, only when it needs to build from source, and only if you are not running ``conan create``. You would need to be more specific, provide the conanfile you are using, the commands you are running and what would be the expected behavior.

**Comment by cguldner** [comment]
@memsharded Yeah I forgot there are multiple ways to build a package!

I'm running `conan create`. Here's a simplified version of my conanfile

```python
from conans import ConanFile

class Conan(ConanFile):
    name = "conan"
    version = "1.0"
    scm = {
        ...
    }
```
I would just like an option to turn off getting the source from the `scm` object automatically when I run `conan create`. This is useful when I'm planning on checking out the code in the `source` function, particularly when I'm running through CI and want to change behavior based on the branch I'm merging to

**Comment by memsharded** [comment]
``scm`` deprecated in 1.X, removed in 2.0, closing this ticket as outdated.
