### ISSUE TITLE
[feature] Set version to git hash when conanfile in different repo from source

### ISSUE THREAD

**Issue by cguldner** [conan-io/conan#7050]
This is related to #6896. I have the same directory structure as described in that issue.

I'm wondering if it is possible to have the source from `scm` fetched before the `set_version` function is called, so that `self.source_folder` could be available in that function. That way, since my source is in a different repo, I could still dynamically get the git information of the source repo.

 If this isn't possible, do you have any suggestions for how I might accomplish the goal in a similar way? The other way I can think of accomplishing this would be to just check out the repo myself inside of the `set_version`, but then the repo would be getting checked out twice (unless #7049 is implemented)

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi!

I think this is not going to be possible, other people would request to know the `self.version` before checking out the sources... and I feel like this is much more common use case: you checkout a different tag based on the version of your package.

---

So, let's try to understand what you are trying to achieve: you want to have the recipe files in a different repository from the sources, and you want to read the version from some file among those sources.... then I assume you are checking out the HEAD of some branch on your sources repo, right?

In this scenario I would say that your recipe should use as a reference `name/<branch>@...` and explicit `name/<version>@...` whenever you are using a tag in your repository. "Recipe revisions" will help you to identify the sources for every `name/<branch>@...` package, even though the branch is the same, Conan has a built-in mechanism (https://docs.conan.io/en/latest/versioning/revisions.html?highlight=revisions) so those packages won't be overridden.

This way:
 * `conan create <path/to/recipe.py> name/master@...` will clone the branch `master` (HEAD)
 * `conan create <path/to/recipe.py> name/1.0.0@...` will checkout tag `1.0.0` from the repo

This logic is something you can easily implement in the `source()` method or even add to the `scm` attribute.

Does it make sense?

**Comment by cguldner** [comment]
@jgsogo What I ended up implementing is a function in my base conanfile that gets the latest commit from the `revision` in the `scm` attribute. I then call this function in `set_version`
```python
@staticmethod
def get_git_hash(conanfile):
    """ Gets the git hash of the repository specified in the scm attribute """
    version = ""
    checkout_folder = "temp/{}".format(conanfile.scm["subfolder"])
    conanfile.run("rm -rf {0} && mkdir -p {0}".format(checkout_folder))
    git = tools.Git(folder=checkout_folder, verify_ssl=False)
    with tools.chdir(checkout_folder):
        git.clone(conanfile.scm["url"], branch=conanfile.scm["revision"], shallow=True)
        version = git.run("rev-parse HEAD")
    conanfile.run("rm -rf temp")
    return version
```
This is partially because our Artifactory instance is currently too old to support Conan package revisions. My use case is also more application development, where some sort of version tag doesn't make sense (in my case), so a git hash for the version makes more sense.

I do think your suggestion for being able to specify a hash that doesn't exist in a package uploaded to Artifactory is a good one, and I think I will implement that as well. It's unclear to me how I would implement that alongside my current `set_version` function. Since I have a `set_version`, I've explicitly set the `version` attribute to `None`. So how would I fetch the revision if it is supplied from the `conan create` command?

**Comment by cguldner** [comment]
@jgsogo I am using a build script, so the first idea that comes to mind is adding an argument to specify a revision to the build script, and then setting an environment variable that conan could then read. But I'm wondering if there is a more Conan-like way of doing that

**Comment by jgsogo** [comment]
If you cannot use revisions, then as your only option is to use the `version` to identify the commit, it would be much easier using revisions, but... update your Artifactory 😉 

I don't know what you mean when you say _"I do think your suggestion for being able to specify a hash that doesn't exist in a package uploaded to Artifactory is a good one,"_.

Probably if you already have this workaround to get the commit sha1 from the repository and assign it to the package you are creating, then you don't need to pass anything to Conan from the command line, unless you want to create a package from an specific commit... If that is the case you will be able to rely on this PR (https://github.com/conan-io/conan/pull/6940 https://github.com/conan-io/conan/issues/6939), it will allow you to get the value from the command line inside `set_version` so you can choose whether to use the value provided from the CLI or compute it in your function.

**Comment by cguldner** [comment]
@jgsogo 

> If you cannot use revisions, then as your only option is to use the `version` to identify the commit, it would be much easier using revisions, but... update your Artifactory 😉

Based on my reading, I thought that with my recipe structure, package revisions wouldn't work since the revision is based on the repo that the recipe is in, and since my recipe isn't stored with the source, this wouldn't work?

> I don't know what you mean when you say _"I do think your suggestion for being able to specify a hash that doesn't exist in a package uploaded to Artifactory is a good one,"_.

_unless you want to create a package from an specific commit_, - this is what I meant

> Probably if you already have this workaround to get the commit sha1 from the repository and assign it to the package you are creating, then you don't need to pass anything to Conan from the command line, unless you want to create a package from an specific commit... If that is the case you will be able to rely on this PR (#6940 #6939), it will allow you to get the value from the command line inside `set_version` so you can choose whether to use the value provided from the CLI or compute it in your function.

Ah, that PR is helpful, I'll be waiting for release 1.26!

**Comment by jgsogo** [comment]
The [**recipe revision**](https://docs.conan.io/en/latest/versioning/revisions.html) can be the commit of the repository or the hash of everything exported together with the recipe... let's think about the second alternative:

If the recipe is in a different repository and you want to capture the commit of the sources-repository you would need to write it somewhere (for example to [`conandata.yml`](https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html), this is where we store the information of the SCM when we don't write it to the recipe itself) and export it together with the recipe (it is automatic, as said in the docs): any different commit from the sources repo will modify the contents of the `conandata.yml` and Conan will compute a different hash and a different recipe revision.

**Comment by cguldner** [comment]
@jgsogo On the conandata.yml page it says
> This file is specific to each recipe conanfile.py and it should be placed next to it

How would that work with having multiple recipe files in the same directory? It seems like there would need to be a way to specify the name of the conandata file

**Comment by jgsogo** [comment]
Uhmm... interesting. Maybe this is a use case for the implementation of this PR (https://github.com/conan-io/conan/pull/6945, description of the PR doesn't match current implementation).

wdyt, @memsharded , can we write on-the-fly some content to `conandata.yml` in the `export` function? Probably as it is implemented now it is not possible, but does it make sense? Something to support?

**Comment by jgsogo** [comment]
I can confirm that the `export()` (#6945) will let you modify the `conandata.yml` file, so it is a place where you can add information and it will be available when using the recipe: https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html

Can we close this issue? It is probably mixing some different topics. If you feel like there is something we should talk about, maybe it is better to open a new one.

Thanks!
