### ISSUE TITLE
[bug] conan info --paths on conan editable pkgs

### ISSUE THREAD

**Issue by saimusdev** [conan-io/conan#7054]
## conan info --paths on conan editable packages does not work
Conan version: `1.25.0`

I've seen you already have [a card in-progress regarding this issue](https://github.com/conan-io/conan/projects/1#card-15858545), so I assume you're already familiar with this and don't need a long explanation.

CC/ @lasote 

### Motivation
Pretty standard use case, I think: 
I have a requirement to ask Conan about the `source_folder` and `build_folder` of a binary package, to gather the `compile_commands.json` to run static analysis with: `clang-tidy`, `iwyu`, etc.

### Environment Details
  * Operating System+version: Linux
  * Compiler+version: gcc64 (irrelevant though)
  * Conan version: 1.25.0
  * Python version: 3.5.2

### Steps to reproduce
1. Put a package in editable mode:
2. Install the package onto the local cache
3. Try to gather paths with `conan info --paths`

### Workarounds?
Is there a way to gather the `build_folder` and `source_folder` from a python script using some conan api, instead of the Conan CLI?

**Comment by jgsogo** [comment]
Hi! Thanks for bringing this up.

Actually, I don't think you can use any workaround to bypass this error, the exception won't be in the command line implementation, but in the library, so behind any Python API you can call.

This can be really easy to fix, maybe just catching and exception or doing an if/else before gathering those paths.

Thanks!

**Comment by saimusdev** [comment]
Yeah, I understand than an exception will be thrown, the thing is I would like to get the `build_folder` (and less importantly the `source_folder`) even if the package is in `editable` mode. 
Even if I capture the exception, thrown by the `conan info`, the result is: I have no information about the `build_folder` location in the cache.

Are you saying this can be fixed in conan API?

Thanks for your quick help ;)

**Comment by jgsogo** [comment]
Hi! I was having a look at this issue and I've found that getting `--paths` from an editable package is something not permitted, not an unhandled exception:

```
ERROR: Operation not allowed on a package installed as editable
```

It shouldn't be considered a bug, but a feature request... 

Are you getting an unhandled exception? Can you share the steps you are typing?

Thanks!

**Comment by jsteinhofff** [comment]
I would like to support this feature-request. If conan info --paths is the right way to get access to all packages in the dependency graph for additional tooling, then it would be reasonable to also have it work with editable packages.

I dont get an exception, just as soon as there is any editable package in the hierarchy, i get the 
```
ERROR: Operation not allowed on a package installed as editable
```
message. Am i missing something obvious why this is "not permitted"?

**Comment by steerlink** [comment]
I'm interested in this feature-request

**Comment by blastrock** [comment]
We have a similar case here, we have a script that needs to build an editable package before building the current package that depends on it. It would be nice to have `conan info --paths` to work on editable packages so that I can call `conan build` on it. Is this feature still planned?

**Comment by memsharded** [comment]
Doing https://github.com/conan-io/conan/pull/9944, at least to avoid the exception and get some values. The root of the editable is available in the ``export_folder``. PR for 1.43

**Comment by memsharded** [comment]
``conan info --paths`` no longer exists in 2.0, closing as outdated
