### ISSUE TITLE
revision_mode for scm not creating versions for packages

### ISSUE THREAD

**Issue by Prasaddiwalkar** [conan-io/conan#7057]
I am using `revision_mode` as following in my conan recipe.

Even if I execute same commands through GitLab CD-CD pipeline push does not create multiple versions in artofactory

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 64bit
  * Compiler+version:
  * Conan version: 1.25.1
  * Python version: 3.8.1 

### Steps to reproduce (Include if Applicable)
```python
revision_mode = "scm"
scm = {
        "type": "git",
        "url": "auto",
        "revision": "auto"
     }
```

Command to generate package
>```python
> $ conan export-pkg . pkgName/version@user/release -f
>```

Command to upload package
>```python
> $ conan upload pkgName/version@user/release --all -r <REMOTE> --force
>```

![image](https://user-images.githubusercontent.com/41470880/82452637-2a7c8c00-9acd-11ea-8d19-6c73a92d8e16.png)

My expectation from this functionality is it should generate new schecksum as per gitlab commit in pipeline.

Even after multiple run it shows same checksum as shown in screen shot

**Comment by memsharded** [comment]
Hi @Prasaddiwalkar 

To use revisions there are 2 important things:

- You need to enabled them, they are disabled by default. In ``conan.conf``. Make sure all your clients have revisions enabled.
- It seems that you are using an old Artifactory. Which version are you running? You would need to update to a more modern one with support for revisions.

**Comment by Prasaddiwalkar** [comment]
Hi @memsharded 

I am using Artifactory Community Edition for C/C++ - 6.4.1 rev 60401900

I have modified conan.conf with following before running the revisioning on conan client host

```
[general]
default_profile = default
revisions_enabled = True 
```



Which version of Jfrog supports revisioning_mode for conan?
In my organization we have production environment of `Artifactory Enterprise 6.18.1 rev 61801900`
Does this version of Artifactory supports Revisioning?

**Comment by Prasaddiwalkar** [comment]
as per document https://blog.conan.io/2019/04/01/New-conan-release-1-14.html

revisioning is supported in version  `6.9 version of Artifactory ` But I dont find 6.9 version to download any where on jfrog site

**Comment by memsharded** [comment]
If you are upgrading you should probably not upgrade to the minimum version that supports it, but to the latest one. There might be bugfixes that were done after the first release of Artifactory with support for revisions.

- You have links to Artifactory CE 6.19 in our download page: https://conan.io/downloads.html

- Latest 7.4, the recommended one is in: https://bintray.com/beta/#/jfrog/product/JFrog-Artifactory-Cpp-CE?tab=packages

- And to navigate all past versions: https://bintray.com/beta/#/jfrog/reg2/jfrog:artifactory-cpp-ce?tab=overview
