### ISSUE TITLE
[Windows] [AppVeyor] v0.15.0-regen - packages fail to install with no error

### ISSUE THREAD

**Issue by digitalcircuit** [conan-io/conan#706]
## In short
* Conan ```0.15.0``` stopped installing packages sometime after Windows installer regenerated
  * All ```conan install``` commands fail to install, yet give no error message
  * Tracing with [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor ) shows calls to Conan.io, but no further operations in project folder
  * ```0.15.0``` had worked in the past
* Conan ```0.14.1``` still works, as a temporary measure

## Details
Conan is used to download and install OpenSSL for Windows as part of the [Fuzzball MUCK Windows AppVeyor CI setup][fuzzball-appveyor].  As the build system uses NMake from Visual Studio, [```conanfile.txt```](https://github.com/fuzzball-muck/fuzzball/blob/master/conanfile.txt ) redirects the OpenSSL binaries and build files to local folders (*this will be cleaned up in the future*).

Conan ```0.15.0``` originally worked with no errors, as shown below in *Examples*.  Packages installed and the build succeeded as expected.

However, sometime later (*between 2016-11-12 and 2016-11-26*), ```conan install ...``` stopped installing the packages, giving no error message.

Strangely enough, Conan ```0.14.1``` continues to work fine, and I've [opened a pull request for Fuzzball MUCK](https://github.com/fuzzball-muck/fuzzball/pull/38 ) to revert to this version to fix build failures until the issue can be resolved.  You can find some more details in the pull request.

This might be related to the regenerated ```0.15.0``` Windows installers, noted in [this comment on conan-io issue #677](https://github.com/conan-io/conan/issues/677#issuecomment-261904425 ).

## Test case
Reliably reproduced with the [Fuzzball MUCK AppVeyor setup][fuzzball-appveyor] as of 2016-11-27, [commit ```f6c5785```](https://github.com/fuzzball-muck/fuzzball/commit/f6c57855a5d3f7038b3df2b4baad3f2c29e7f9fe).

[Enabling RDP in AppVeyor](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/ ) and manually running ```conan install [package name]``` without any options also fails on ```0.15.0```, and works on ```0.14.1```.

### Conan ```0.15.0-regen``` failed
*Conan package manager ```0.15.0```,* **after** *the regenerated installer date; [see full log here](https://ci.appveyor.com/project/fuzzball-muck/fuzzball/build/221 )*
```
Conan version 0.15.0
[...]
OpenSSL/1.0.2g@lasote/stable: Not found, looking in remotes...
WARN: Remotes registry file missing, creating default one in C:\Users\appveyor\.conan\registry.txt
OpenSSL/1.0.2g@lasote/stable: Trying with 'conan.io'...
```
*No future messages from Conan, process just exits*

### Conan ```0.15.0-original``` success
*Conan package manager ```0.15.0```,* **before** *the regenerated installer date; [see full log here](https://ci.appveyor.com/project/fuzzball-muck/fuzzball/build/214 )*
```
Conan version 0.15.0
[...]
OpenSSL/1.0.2g@lasote/stable: Not found, looking in remotes...
WARN: Remotes registry file missing, creating default one in C:\Users\appveyor\.conan\registry.txt
OpenSSL/1.0.2g@lasote/stable: Trying with 'conan.io'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
[...]
OpenSSL/1.0.2g@lasote/stable: Package installed 69fd75ba69997a0c92961d5fc7c55034001ba6e4
PROJECT: Generated conaninfo.txt
PROJECT imports(): Copied 101 '.h' files
PROJECT imports(): Copied 2 '.dll' files: libeay32.dll, ssleay32.dll
PROJECT imports(): Copied 3 '.lib' files: libeay32MD.lib, ssleay32MD.lib, zlibstatic.lib
```

### Conan ```0.14.1``` success
*Conan package manager ```0.14.1```, after the release of ```0.15.0```; [see full log here](https://ci.appveyor.com/project/fuzzball-muck/fuzzball/build/220 )*
```
Conan version 0.14.1
[...]
OpenSSL/1.0.2j@lasote/stable: Not found, looking in remotes...
WARN: Remotes registry file missing, creating default one in C:\Users\appveyor\.conan\registry.txt
OpenSSL/1.0.2j@lasote/stable: Trying with 'conan.io'...
WARN: A new conan version (v0.15.0) is available in current remote. Please, upgrade conan client to avoid deprecation.
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
[...]
OpenSSL/1.0.2j@lasote/stable: Package installed 69fd75ba69997a0c92961d5fc7c55034001ba6e4
PROJECT: Generated conaninfo.txt
PROJECT imports(): Copied 101 '.h' files
PROJECT imports(): Copied 2 '.dll' files: libeay32.dll, ssleay32.dll
PROJECT imports(): Copied 3 '.lib' files: libeay32MD.lib, ssleay32MD.lib, zlibstatic.lib
```

[fuzzball-appveyor]: https://github.com/fuzzball-muck/fuzzball/blob/master/appveyor.yml

**Comment by memsharded** [comment]
Hi Shane,

Thanks very much for your detailed and accurate report. Certainly, the machine that generates the installer did something and it was mis-configured, and the installer is broken.
Conan 0.16 will be released tomorrow, with this (hopefully) fixed.

In any case, we strongly suggest using the python-pip package instead of the Win installer, it has less issues, and works fine in more setups. Plus is more convenient to update/maintain and integrate with other python scripts (conan-package-tools, etc). Please consider moving to the python pip package instead of the Win installer. Installing it in appveyor should be simple:

```
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
````

**Comment by digitalcircuit** [comment]
Hello James,

I appreciate the quick response!  After switching to ```python-pip```, the issues went away.  I went ahead and [submitted a pull request to conan-io/docs](https://github.com/conan-io/docs/pull/102 ) to update the documentation, too, so others won't make the same mistake.

Thank you for the quick response!

This issue can be left open until 0.16 is confirmed to fix it, or you can close it now if you prefer.

**Comment by memsharded** [comment]
You are welcome :)

Great, thanks for your fix to the docs!

I have ran a few tests with the 0.16 win installer, everything seems good, so closing this issue, but please re-open if necessary. Cheers
