### ISSUE TITLE
[feature] expose msvc_toolset

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#7061]
from https://github.com/conan-io/conan-center-index/pull/719#discussion_r398650536
some recipes are using private API `from conans.client.tools.win import msvs_toolset`
it would be nice to expose it 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SSE4** [comment]
appears to be already exposed from the `tools.msvs_toolset`, only docs are needed.

**Comment by jgsogo** [comment]
I think it is not available in the `conans.tools` module. I agree that file is a mess and we need to make something to improve that implementation, but we really don't know how to deal with those global objects.

**Comment by jgsogo** [comment]
@SSE4 , Another important point. We are trying to provide more uniformity for all the tools, the idea is that all of them take the conanfile object as the first argument, so the exposed interface for this tool should be `tools.msvc_toolset(conanfile=self)` when used in a recipe.

This is totally needed for some tools/build-helpers, and for others it makes it easier to get access to `conanfile.output` if they need to output something.

**Comment by SSE4** [comment]
@jgsogo  while I like uniformity, don't you feel it's too much to pass conanfile if it only requires settings? it sounds a bit like a unfortunate design for me, e.g. passing **jungle** if you only need **bananas**.

**Comment by jgsogo** [comment]
I agree with that principle, but from the user POV I think it would be easier if all the tools and build helpers just receive `self` as the first argument, no need to think, no need to check docs,... in this case I prefer uniformity over correctness.

I asked memsharded to open an issue to talk about this: https://github.com/conan-io/conan/issues/7105.

**Comment by SSE4** [comment]
@jgsogo I've been thinking a bit more about it. I can imagine cases where I don't have an access to the conanfile (self) instance, e.g. global function, static method, etc. in that case I would need to construct synthetic conanfile object just to pass settings. that may lead to very ambiguous and excessive code.

**Comment by jgsogo** [comment]
I'd like to see an example. This is a tool, and tools are always used in the context of a recipe.

**Comment by SSE4** [comment]
@jgsogo okay, something like that:
```
    @staticmethod
    def allowed_toolsets():
        settings = Settings({"compiler": {"Visual Studio": {"version" : ["16"]}}})
        settings.compiler = "Visual Studio"
        settings.compiler.version = "16"
        return [tools.msvs_toolset(settings)]
        
    def build(self):
        if self.settings.compiler.toolset not in ZlibConan.allowed_toolsets():
            raise Exception("invalid toolset!")
```
if I would need to construct ConanFile here, it would be much more complicated

**Comment by SSE4** [comment]
seems like it wasn't actually exposed, so I've added PR
(I was confused by this usage: https://github.com/conan-io/conan/blob/30f006d6c2e5f5139f8b885335b3ec0ad5bf8992/conans/test/unittests/util/msvs_toolset_test.py#L29)
