### ISSUE TITLE
[feature] Both conanfile.txt and conanfile.py

### ISSUE THREAD

**Issue by aminya** [conan-io/conan#7068]
It would be awesome if we could use conanfile.txt, which has a simple clean interface, to define the static dependencies, and then use conanfile.py for the dynamic dependencies.

Having both allows having the bests of both worlds. 

Using the only conanfile.py is not desirable all the time because of its more complex architecture.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Not sure if I understand this issue. You can have both files if you want, and use the one you want explicitly with ``conan install conanfile.txt`` or ``conan install conanfile.py``.

**Comment by aminya** [comment]
> Not sure if I understand this issue. You can have both files if you want, and use the one you want explicitly with `conan install conanfile.txt` or `conan install conanfile.py`.

I want to use **both** in a single `conan install` command. First, installing static deps using conanfile.txt then dynamic deps using conanfile.py

**Comment by sourcedelica** [comment]
Related to https://github.com/conan-io/conan/issues/6177

**Comment by memsharded** [comment]
> I want to use both in a single conan install command. First, installing static deps using conanfile.txt then dynamic deps using conanfile.py

What is the advantage of this? Why not using just a single ``conanfile.py``? I don't see the advantage of having both and using one after the other. In fact it will be source of hidden complexities:
- What if conanfile.py has the same dep but other version that conanfile.txt? Is it a conflict or should it be overriden silently?
- What about options and build requires conflicts?
- What when a package is created from that conanfile.py? It will be missing the deps from the conanfile.txt.

I have seen these "features" many times, and they are more painful that the problem they are supposed to alleviate. Is having this:

```python
from conans import ConanFile

class Pkg(ConanFile):
     settings = "os"
     requires = "pkg/1.0@user/channel", "other/2.0@user/channel"
     def requirements(self):
         if self.settings.os == "Windows":
                 self.requires("windep/3.0@user/channel")
```

really a problem?

**Comment by aminya** [comment]
It makes it possible to separate the declarative/static part of the package management from the dynamic part of it. In addition to being easier to maintain, it allows using some tools.
For example, if a bumper tool existed, we could use that to bump the versions in conanfile.txt. But this is impossible in conanfile.py

**Comment by memsharded** [comment]
```python
from conans import ConanFile

class Pkg(ConanFile):
     settings = "os"

     # declarative part
     requires = "pkg/1.0@user/channel", "other/2.0@user/channel"

     # dynamic part
     def requirements(self):
         if self.settings.os == "Windows":
                 self.requires("windep/3.0@user/channel")
```

If you want to have a file with declarative requirements, you can do it as well, even without increasing the line count! (assuming that you have a file there called "myreqs.txt" with the requirements:

```python
from conans import ConanFile, load

class Pkg(ConanFile):
     settings = "os"

     requires = load("myreqs.txt").splitlines()
```
I have just tested this, works great, if this is what you want to do with your bumper tool. 

There migth be other ways to do it, for example, use the ``conandata.yml``, which is an "official" file to store data about the recipe in a declarative way, and that is automatically loaded, and use the data from it directly in the ``requirements()`` method. It is yml, so it structured, and good for automation as well.

**Comment by Minimonium** [comment]
I think it's better to look in the direction of uplifting "best practices" from `conanfile.py` usage into a conventional syntax in the `conanfile.txt`. Reducing the amount of boilerplate should be a long-term priority. 

We could even have some basic conditional requirement like this https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies

**Comment by memsharded** [comment]
Summarizing this issue:

- Conanfile.py allows a structured way of adding structured requirements in a file (txt, json...) and it also includes a builtin mechanism for it, ``conandata.yml``.
- Conanfile.py allows a standard, well known syntax for adding conditional requirements, with any level of conditionality over multiple factors, including custom user settings and options.
- The conditional syntax is standard python language, which is already known by a majority of users (as opposed to other custom, invented DSL over the conanfile.txt that everyone should learn).

For these reasons, I am still convinced that the extra efforts to implement and maintain an invented new syntax on conanfile.txt for this is not worth, both for maintainers but specially also for users, it will be less effort and less problematic to write those conditions in Python (you can even do print() in it and debug possible issues). So I am closing this issue, thanks for all the feedback.
