### ISSUE TITLE
[question] is settings.compiler.version manadatory

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#7077]
Hi there,
I am using Conan 1.24.1. And I encountered an issue where I want to use the GNU Make system to build but Conan throws an error that ```settings.compiler.version``` has not been specified.

The conan recipe does not need the compiler version the make system is going to use. But when I use a profile that does not set ```settings.compiler.version``` and a recipe that sets the following line:
```python
settings        = "os_build", "arch_build", "compiler"
```
Conan is going to error out with:
```
ERROR: recipe_name/0.0.0@test/testing: 'settings.compiler.version' value not defined
```

I have tested this with an empty recipe (all methods ```pass```) so no usage of ```settings.compiler.version``` in the recipe itself.

**Comment by memsharded** [comment]
Yeah, I am getting:

> ERROR: : 'settings.compiler.libcxx' value not defined

instead of the version. 

Quick question: Which values are you passing in your profile? And: is it possible to have a compiler that doesn't have a compiler version? It seems it isn't. What are you trying to achieve?

**Comment by Johnnyxy** [comment]
The scenario is that I am building [Vortex OpenSplice](https://github.com/ADLINK-IST/opensplice) that uses GNU Make. 
The project uses many makefiles for different targets. But for GCC there is a [generic makefile](https://github.com/ADLINK-IST/opensplice/blob/master/setup/x86_64.linux-default.mak) out-of-the-box.

For crosscompiling reasons I am providing additional makefiles which specify a certain GCC version to compile with. Thus I can select a specific compiler version to build with.
In this case I use the provided ```settings.compiler.version``` and everything runs fine.

The makefile name (what is the target name) that I have to provide as argument to the make system is concatenated from ```{arch}.{os}_{compiler}{compiler_version}-...``` e.g. ```x86_64.linux_gcc7-debug```. In the makefiles the specific compiler binary is specified ```aarch64-linux-gnu-gcc-g++-7```.

On current linux systems one has a ```g++``` which is normally a link to a more specific name like ```x86_64-linux-gnu-g++-7```.

My problem was or is that I have an older system (openSUSE 13.1) which does not have the nowadays common symbolic links to with different specific names for the GCC. It just has the plain ```g++```. So my idea was to omit the ```settings.compiler.version``` to not-select-a-GCC-version and use a generic makefile which just compiles with the compiler that is available.

This led to the error with a missing setting. My solution now was to provide the same makefiles just for the GCC 4.8 version and make symbolic links with the expected compiler names to solve that.

It was a merly general question if a compiler version has to be specified. :)

**Comment by memsharded** [comment]
> It was a merly general question if a compiler version has to be specified. :)

Yes, in the general case, if you don't specify otherwise, subsettings that doesn't have a ``None`` possible value are necessary. But you can always skip that in your recipes, like:

```python
from conans import ConanFile, load

class Pkg(ConanFile):
     settings = "os_build", "arch_build", "compiler"

     def configure(self):
          del self.settings.compiler.version
          del self.settings.compiler.libcxx
```
This doesn't fail. Does it help for your case? Of course you can make the ``del`` conditional to the OS or compiler.

**Comment by Johnnyxy** [comment]
Hm, I do not think that this would help. As the recipe does not decide if it uses a compiler version or not. It does rely on the setting ```settings.compiler.version```.

The profile I or some user specifies can provide a version number or not.
The slogan for the recipe is: If there is a version, use it. If there is no version, no problem "generic".

The background with the profiles here is that we can setup specific settings (company wide) in certain profiles and a user can specify the target he wants to build without having any knowledge of the settings provided in the profile. If someone has a problem with Conan and his build I can always reproduce it with the exact same settings.

Anyway, thanks for your time :).

**Comment by Johnnyxy** [comment]
I was thinking a little bit more.
In general it could be fatal in some or many cases if Conan would not have a compiler version at hand to calculate an appropriate package id. This could lead to a GCC version 9 linking an stoneage library from GCC 4.

**Comment by memsharded** [comment]
Then you could be doing something like:

```python
from conans import ConanFile

class Pkg(ConanFile):
     settings = "os_build", "arch_build", "compiler"

     def configure(self):
          if not self.settings.get_safe("compiler.version"):
                del self.settings.compiler.version
```
I think this will achieve what you want, you can pass the compiler version and it will use it, or you can ignore it if not provided.

You could also add ``None`` to the ``compiler.version`` field in the ``settings.yml`` file, and you will achieve the same result: be able to specify a compiler version, but do not fail if it is not provided.

But yeah, I think the key is here:

>  If there is no version, no problem "generic".

It is really unlikely that the compiler doesn't have a version. It might be an internal one, or the checksum of the tgz or something, but it has some version. Another thing is that you are not providing its information to Conan in a profile. As you said, this is a bit risky, it means Conan will really not care at all about the compiler version at all, and there is a risk that you can have incompatible binaries because of different gcc versions.

**Comment by Johnnyxy** [comment]
Yes, the compiler always has a version. What I tried was to use what ever version is there without knowing it beforehand. Some way to execute just a plain "g++". But Conan still needs the version so I would have to detect the version in my recipe to set the correct version in the settings on configure. But Conan would not be able to know the compiler binary as the makfiles have them exclusivley specified.

Ah ... it would be a mess to do any of that. So ... creating explicit makefiles for  a specific GCC version and additionally creating the symbolic links if needed is less overhead :).
