### ISSUE TITLE
[bug] conan 1.25.2 breaks `init` method

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#7083]
Consider this example: 
[conan-issue.zip](https://github.com/conan-io/conan/files/4677731/conan-issue.zip)

Basically it boils down to this:

```python
class MyBase(object):
    settings = "os", "compiler", "build_type", "arch"
    options = {
        "base_option": [True, False]
    }
    default_options = {
        "base_option": False
    }

class BaseConanFile(ConanFile):
    name = "base"
    version = "1.0.0"
```

and this:

```python
class DerivedConan(ConanFile):
    name = "derived"
    version = "1.0.0"
    settings = "os", "compiler", "build_type", "arch"

    python_requires = 'base/1.0.0@user/testing'
    python_requires_extend = 'base.MyBase'

    options = {
        "derived_option": [True, False]
    }
    default_options = {
        "derived_option": False
    }

    def init(self):
        base = self.python_requires['base'].module.MyBase
        self.options.update(base.options)
        self.default_options.update(base.default_options)
```

With `conan 1.25.2` the following command fails:

```
conan create . user/testing -o base_option=True
```

The error is:

```
ERROR: derived/1.0.0@user/testing: 'options.base_option' doesn't exist
Possible options are ['derived_option']
```

With conan 1.25.1 this works as expected.

**Comment by memsharded** [comment]
I have tried the code and also reproduce from your snippet, and it seems it doesn't fail: https://github.com/conan-io/conan/pull/7087. Can you please check it, and check the test?

**Comment by DoDoENT** [comment]
I don't get it. Yesterday it didn't work so I downgraded to 1.25.1. Today I upgraded back to 1.25.2 and now it works.

Sorry for the inconvenience. At least the new test in your CI is a good value.

I'm closing this in a fog of deep confusion...

**Comment by memsharded** [comment]
> Sorry for the inconvenience. At least the new test in your CI is a good value.

No problem, thanks for reporting! Better to have things reported and checked in tests that unreported bugs.
