### ISSUE TITLE
[bug] tools.unzip() does not put following output on a new line

### ISSUE THREAD

**Issue by artem-ogre** [conan-io/conan#7090]
When calling `tools.unzip()` output is not moved to a new line causing subsequent output to start at the same line as `Unzipping 100 % `-message. Breaks command prompt if `tools.unzip()` was last command called (cosmetic annoyance).
Only happens with `.zip` archives.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: not relevant
  * Conan version: 1.25.0
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
```python
from conans import tools
tools.unzip("some_archive.zip", "some/destination/folder")
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```bash
Unzipping 100 %                                                       [output continues here (same line)]
```

**Comment by jgsogo** [comment]
Hi! I've opened a quick PR. The newline was being printed only for the `99%`->`100%' step, now it is printed when it finishes unzipping all files.

This change shouldn't break anything else, it is just a cosmetic one.
