### ISSUE TITLE
[question] Getting recipe revision (scm) & package_id in build()-function

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#7100]
I would like to put the "package_id" and the "recipe revision" into my application during build. 
Is it possible to pick the values of both during build()-function? 
The idea is to put the both values to CMake to generate there a version file, which includes the "version", "recipe revision" (git hash) and the "package_id" (to know exactly, which combination of libraries where used to build the package).

I looked also into the hook section, but was not sure, if this would be the right way ("pre_build"-hook).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The ``package_id`` can be obtained as:

```python
    def build(self):
        package_id = self.info.package_id()
        print("package_id %s" % package_id)
```

Right now there is not direct way of obtaining the self recipe revision.

That is to capture the ``self`` package_id. It seems that you want to capture that information but from the dependencies?

**Comment by climblinne** [comment]
@memsharded : Thanks for the package id.  

I don't want to capture the information from the dependencies. For the information about the dependencies I would use the package_id.

Until now I got the following version scheme in our workflow:

```
2.2.0-dev.10+master.g12b80e2
```
 [major.minor. patch, (dev,rc, release + build) + information about branch & git commit id)

Now I want to change my CI/CD workflow following your ideas from the CI/CD workshop.
Then my version number would be reduced to 

```
2.2.0-dev
```
The git commit id & the branch would be missing.

As the git commit id could be the same as the '''recipe revision''', I would like to get the information also at build time, so that my application will still show the old version number scheme. I would also add the package id, to know exactly, which combination of libraries where used to build the application:
```
2.2.0-dev+g12b80e2.p1a34567
```

Is it also possible to pickup the "channel" at build time?

Is there an indirect way to pickup the scm revision / recipe revision?

Thanks Jan

**Comment by climblinne** [comment]
> The `package_id` can be obtained as:
> 
> ```python
>     def build(self):
>         package_id = self.info.package_id()
>         print("package_id %s" % package_id)
> ```
> 
> Right now there is not direct way of obtaining the self recipe revision.
> 
> That is to capture the `self` package_id. It seems that you want to capture that information but from the dependencies?

@memsharded  Could you give any hint how to do it indirect?

**Comment by markovandooren** [comment]
I use the following code. The 'semantic_version' attribute contains a version like 1.2.3 and this code appends the git hash. The recipe_folder is available only in set_version and set_name so I set the branch and revision attribute to also be able to use it in other places in the script.

```
    def set_version(self):
        self.branch = "unknown"
        self.revision = "unknown"
        if (os.path.exists(".git")):
            git = tools.Git(folder=self.recipe_folder)
            self.branch = git.get_branch()
            self.revision = git.get_revision()
        self.version = "%s.%s" % (self.semantic_version, self.revision)
```

**Comment by climblinne** [comment]
@markovandooren 
Thanks for the reply. The problem is, that I don't want to put the revision number into the version field, because this would define new packages. I want to use recipe revision (git revision) and keep the version only to semantic versioning. But still I need to access the git revision from CMake.

**Comment by markovandooren** [comment]
I see. You don't have to change the revision in set_revision. You can use it to put the revision in an attribute and then in the source() method write `"#define REVISION " + revision` to e.g. a revision.h file that you include in your build.

**Comment by Ambrase** [comment]
Why self.info doesn't exist when I run "conan build ." instead of "conan create ."?

**Comment by EddyXorb** [comment]
I had a similar issue  and solved it like that:
In the conanfile.py in set_version I write into a file "version.txt" which I put into my .gitignore file and exported it with exports_sources into my local cache. In code:

```python
   #conanfile
   exports_sources = "version.txt"
   def set_version(self):
        self.writeVersionTxt()
        self.version = "exampleversion"

    def writeVersionTxt(self):  #Write version.txt
        includeVersion = tools.Git().run("describe --tags --always") #whatever command you want to execute on your local repo (not local cache)!
        with open("version.txt", 'w') as file:
            file.write("\"" + includeVersion + "\"")

        print('Wrote version.txt containing ' + includeVersion + ' to ./version.txt')
```

This version.txt file is then consumed by my c++ project as follows (you have to assure that you put the "version.txt" in the root folder of the consuming project):
```cpp
auto get_version() -> std::string
{
    return
#include "version.txt"
        ;
}
```
For me it was **not** obvious at the beginning that only set_version has access to my local recipe folder, but the other methods not. Maybe it should be mentioned in the documentation. This wouldn't be an issue if the copied sources in the local cache would contain a working git repo, which is not the case for me (I think one cannot simply copy a .git folder?).

**Comment by Ajay-Khambadkone-Bose** [comment]
> The `package_id` can be obtained as:
> 
> ```python
>     def build(self):
>         package_id = self.info.package_id()
>         print("package_id %s" % package_id)
> ```
> 
> Right now there is not direct way of obtaining the self recipe revision.
> 
> That is to capture the `self` package_id. It seems that you want to capture that information but from the dependencies?

I am not able to get this working, do you know if this is supported in some version of conan?
I have "Conan version 1.25.0"
and the conan build step gives an error " object has no attribute 'info' "
@memsharded help appreciated.

**Comment by climblinne** [comment]
@Ajay-Khambadkone-Bose 
For me it is working for all Conan packages. But `self.info` it's not defined for an `test_package`

**Comment by tarc** [comment]
> That is to capture the self package_id. It seems that you want to capture that information but from the dependencies?

@memsharded 

BTW, is it possible to get the package ids of the dependencies from a custom generator?

**Comment by RolfBippus** [comment]
@Ajay-Khambadkone-Bose 
@memsharded 
I also definitely have problems accessing self.info using the development commands (conan 1.43)
```
> conan install .
> conan build .
...
'Project' has no attribute 'info'
```
BTW, during install, there is no problem accessing self.conanfile.info.package_id() in the Generator.

**Comment by memsharded** [comment]
Closing this ticket as outdated, Conan 2 changes many things here, for example ``conan build`` now computes the full dependency graph, having full information of dependencies via ``self.dependencies`` and it can access the ``self.info.package_id()`` too.

Please create new tickets against Conan 2.X if necessary, thanks for the feedback.
