### ISSUE TITLE
[question] export_sources wildcards

### ISSUE THREAD

**Issue by gnac** [conan-io/conan#7102]
I am trying to create conan packages for some legacy software that has an extremely convoluted source folder hierarchy. I have gotten conan to use cmake files to "install" and "build" the project and its dependencies, but I cannot get conan "create" to work. I currently need to use conan 1.19.1, 

When exporting my sources, I can use 

    exports_sources =  "../../CMakeLists.txt", "../../src*"

but I don't actually want everything under ../../src to be exported. I just want the *.cc files from src, and a few of the subdirectories.

I have tried
    exports_sources =  "../../CMakeLists.txt", "../../src/*.cc"
but that still exports everything under src.

if I then try 

    exports_sources =  "../../CMakeLists.txt", "../../src/*.cc", "../../src/OtherDirectory"

I get permission errors when trying to copy files from OtherDirectory into src, because they have already been copied there.

Am I misunderstanding the syntax of export_sources? How can I be more exact in selecting which files to export?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @gnac 

We are adding full ``export()`` and ``export_sources()`` methods to the recipes in this release: https://github.com/conan-io/conan/pull/6945

You will be able to model with them the directories bases with the ``self.copy("*.cc", src="../../src")``

The problem with the attribute model is that for folders above the current one, there is no way to differentiate between the pattern and the base folder.

**Comment by memsharded** [comment]
The methods #6945 PR have been merged ,will be available in 1.26 early next week, please do try them and report if they solve your issue. Thanks!
