### ISSUE TITLE
Example for editable feature not working under Linux

### ISSUE THREAD

**Issue by BrianBloemendal** [conan-io/conan#7103]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubunto 20.04 LTS (Windows Subsystem for Linux)
  * Compiler+version: gcc version 9
  * Conan version: 1.25.2
  * Python version: 3.7.0
  * CMake version: 3.16.3

### Steps to reproduce (Include if Applicable)

I'm following the example on https://docs.conan.io/en/latest/developing_packages/editable_packages.html
Especially the section "Using a package in editable mode"

1. Clone examples repo: "git clone https://github.com/conan-io/examples.git"
2. Edit build.sh and comment the line containing "conan editable remove ..."
3. Run ./build.sh -> prints "Release: Hello!"
4. Modify say.cpp (.e.g. std::cout << "Release message: " << msg <<std::endl;)
5. cd say/build/Release && make
6. cd ../../../hello/build && make
7. bin/hello -> prints "Release: Hello!", however, "Release message: Hello!" is expected.

### Logs (Executed commands with output) (Include/Attach if Applicable)

- When running "make clean && make" in step 6, then the updated library libsay.a is linked.
- I've tried on different Linux systems, all with the same result
- I've tried the visual studio version (build.bat) as well, this one works (using Visual Studio 2015, CMake version 3.14.5, Conan 1.22.3.

**Comment by jgsogo** [comment]
Hi!

I think that the issue is that you are not linking the `hello` application with the modified `say` library. As it is a static library you need to link with it again. 

Try to clean the build system files before compiling again:

```
6. cd ../../../hello/build && make clean && make
```

Let me know if it works this way, maybe we should add this notice to the docs, but if this is the issue, there is nothing we can force on the Conan side.

Thanks!

**Comment by BrianBloemendal** [comment]
Hi Jgsogo,

Thank you. Indeed, make clean && make works. 
I would have expected / hoped that make would automatically discover that libsay.a is updated (this works on Windows). Now you also have te recompile the sources in the hello project.

Is there a way to force only re-linking, or make make automatically discover the updated libsay.a?

Thanks!

**Comment by jgsogo** [comment]
I'd expect it too. I suppose you can edit the Makefiles and add that dependency, but I think it is something to improve on the CMake side, it should generate the files with all the proper dependencies.

**Comment by BrianBloemendal** [comment]
> it is something to improve on the CMake side, it should generate the files with all the proper dependencies.

Should this then be converted into a feature request?

**Comment by jgsogo** [comment]
Probably yes, but it should be a feature request for CMake 😄  (even a bug if it already works for other generators)

**Comment by jgsogo** [comment]
I think we can close this issue, any other comment related to this?

**Comment by BrianBloemendal** [comment]
No other comment from my side, thank you for helping.
