### ISSUE TITLE
Reorganize tools

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#7105]
The current tools approach has some issues:

- Internal code ugliness, due to global objects (output, requester, being globally managed: https://github.com/conan-io/conan/issues/4933)
- No clear import and usage pattern. Some are ``from conans import CMake, load``, but ``save`` is ``from conans.tools import save``.

There are few alternatives:

- Use a conanfile attribute object:
```python

def build(self):
     self.tools.files.save("myfile.txt", "mycontent")
     cmake = self.tools.CMake(...) 
```

- Import an object (hacking a bit the import system)

```python
from conans import tools  # tools is an object we control

def build(self):
     tools.files.save("myfile.txt", "mycontent")
     cmake = tools.CMake(...) 
```

- All tools use a ``conafile/ self`` argument as the first argument. Access/inject what is necessary via a ``conanfile`` private reference to collaborators (output, requester, config

```python
from conans.tools.files import load, save
from conans.tools.build import CMake

def build(self):
     save(self, "myfile.txt", "mycontent")  # A bit ugly, but uniform.
     cmake = CMake(...) 
```

Related:
- https://github.com/conan-io/conan/issues/4933

**Comment by TheQwertiest** [comment]
My (zero-weighted) vote: solution 2.
Solution 1 and Solution 3 are not good for the same reason: some tools do not require `ConanFile` at all, so it doesn't make much sense to drag `ConanFile` object or definition in places where it's not needed at all (e.g. `tools.files.save()`).

**Comment by jgsogo** [comment]
I'm not sure if adding scope to the tools is something we should do, it would make it difficult to find the tools. I mean, from the user POV, I prefer `tools.save` over `tools.files.save`.... so I don't need to check the documentation every time I want to use a tool.

About the main issue here, I like option (2), but I'm not sure if it will require too much monkey-patching (keep in mind that it cannot block eventual parallelism in Conan)

**Comment by memsharded** [comment]
> so it doesn't make much sense to drag ConanFile object or definition in places where it's not needed at all (e.g. tools.files.save()).

Until you want ``save()`` to be able to emit a warning because it is overwriting an existing file, for example, that looks like:

```bash
pkg/0.1@user/testing: warn: save() method is overwriting "myfile.txt"
```
Then you really need the ``save()`` method to have access to the ``conanfile`` to get the ``pkg/0.1@user/testing``. 

I agree, I don't love it. I don't love any of the alternatives, because they are either a bit ugly on the UI side, or quite ugly on the codebase side.

**Comment by TheQwertiest** [comment]
> Until you want save() to be able to emit a warning because it is overwriting an existing file, for example, that looks like

There goes my ideal world... >_<

> I prefer tools.save over tools.files.save.... so I don't need to check the documentation every time I want to use a tool.

Well, `load` is a kinda ambiguous name and might be needed in the future for other purposes, so, IMO, it should be either namespaced or prefixed/suffixed: `file.load`, `file_load` or `load_file` or maybe even `read_file`. But I don't think that this is the main point of this issue =)

**Comment by memsharded** [comment]
> There goes my ideal world... >_<

yeah, that is the thing, I don't like it either, but it is pragmatic and future safe proof.

Agree, the prefix is a different conversation, we can discuss that later.

**Comment by uilianries** [comment]
Hello everyone! There are 3 PRs, each one related to an idea from this issue:

* Use a conanfile attribute object: #7396 
* Import an object (hacking a bit the import system): #7397
* All tools use a conafile/ self argument as the first argument: #7420

All pros and cons are listed in each PR.

**Comment by memsharded** [comment]
A new request coming from https://github.com/conan-io/conan/issues/7576#issuecomment-678820137:

- Enable/disable access to certain tools based on context. E.g. the ``CMake()`` tool can only be used in ``build()`` and ``package()`` methods, but nowhere else.

**Comment by memsharded** [comment]
Adding a new proposal in https://github.com/conan-io/conan/pull/7623:

- Using a real module that is generated programmatically, to fully control variables injection while avoiding global vars.

This is a new approach, better delay this decision (1.30) until we have a look at the new one. To be honest, I am not fully convinced about either of the 3 existing ones, this one could be the good one.

**Comment by jgsogo** [comment]
Still we have three alternatives, this last one is an alternative implementation of the _"[tools] import tools as object #7397"_ . First we were going to decide the UX we want, then look for blockers in the implementation.

We need to choose [one of the three alternatives](https://github.com/conan-io/conan/issues/7105#issuecomment-671321124) (or look for a fourth one):
 * Use a conanfile attribute object: #7396
 * Import an object (hacking a bit the import system): #7397
 * All tools use a conafile/ self argument as the first argument: #7420

**Comment by memsharded** [comment]
> Still we have three alternatives, this last one is an alternative implementation of the "[tools] import tools as object #7397" . First we were going to decide the UX we want, then look for blockers in the implementation.

No it is not. One of the drawbacks of "[tools] import tools as object #7397" is that you cannot further import things inside the global tools object, and then, it will be more breaking to introduce. As you said, the UX is different with this approach, and allows for example to ``from conans.tools import download``. If we want we could update and replace #7397 with this one, but it is not the same.

**Comment by memsharded** [comment]
A decision has been taken: 

Anything that is done via inheritance, import system, objects that get injected collaborators will NOT work for user code (via python_requires, for example). As we see this is a very common approach in users codebases, better have a explicit approach, without any magic: to pass anything necessary via conanfile.xxxx members.

**Comment by memsharded** [comment]
This is the organization of imports that we will use from now for new things that can be imported in recipes, like tools:

```python
#Core model
from conan import ConanFile
from conan.errors import ConanException, ConanInvalidConfiguration
#Tools
from conan.tools.files load, save, mkdir, download, get, ftp_download
from conan.tools.scm import Git, SVN
from conan.tools.version import Version
from conan.tools.config import check_min_cppstd, valid_min_cppstd, cross_building
from conan.tools.env cpu_count, environment_append, run_in_windows_bash, no_op
from conan.tools.cmake import CMakeGenerator, CMake, CMakeToolchain
from conan.tools.microsoft import MSBuildGenerator, MSBuildToolchain, MSBuild, vswhere, vc_vars, vs_installation_path
from conan.tools.gnu import get_gnu_triplet, AutoToolsToolchain, MakefileGenerator, PkgConfigGenerator
from conan.tools.meson import MesonToolchain
from conan.tools.apple import apple_sdk_name
from conan.tools.intel import vc_vars
```

NOTE: Note it is a new ``from conan`` and not ``from conans``. This needs to be fully validated, to check the app doesn't break in pip packages, installer packages, etc.

Rules:
- Besides core ConanFile and exceptions (conan model), every other thing that a recipe can import belongs to “conan.tools”
- All tools are classified by 1 scope, mainly classified by usage pattern (documentation driven). When we document the integration with CMake, the 3 important things (CMakeGenerator, CMake build helper, CMakeToolchain) will be explained together, not in different places of the documentation, and they all will import from the same scope.
- Scopes should be unambiguous. If something that can be imported could belong to 2 different scopes, that would be inconsistent.
- The Conan codebase (except testing) should never explicitly import from “conan.tools”, only recipes can.
- “conan.tools” is only for recipes, no other uses (hooks, python_api, external consumers of Conan like CPT)
- “conan.tools” should not import outside “conan.tools” (there might be some exceptional cases, like “environment_append”, that will be discussed later. In some cases it is probably better to have some repetition, like tools.files will have its own “load/save”, and conan codebase will use other load/save implementations)

Migration plan:
- Do NOT move everything automatically. Every single item should be refactored/improved/analyzed before moving to the new scope, to make sure they become really stable (before stabilizing in 2.0)
- The new scopes will be experimental until 2.0
- We need to make sure the “conan.tools” work and doesn’t have any issue

**Comment by memsharded** [comment]
Reorganization of tools is already in place in ``develop2`` branch. Still to migrate and modernize some tools, but the re-organization is already defined, so this can be closed.
