### ISSUE TITLE
[question] is there any way to generate required system package list?

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7106]
Can I get a list of required system packages from a conanfile.txt with out build/install, which have a set of required conan packages requiring system packages, for certain setting?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
No. System requirements are under system_requirements method only, there is no external way.

As Conan does not recommend system requirements because it's hard to track, follow the same behavior, and created a lot of problems in the past, probably this feature will create more problems than helping.

**Comment by jgsogo** [comment]
Is this about `system_requirements` or the list of libraries listed in `cpp_info.system_libs`?

**Comment by braindevices** [comment]
@jgsogo `system_requirements()`. But I have no idea what is system_libs, where should I use it? Should I set the system_libs manually?

**Comment by jgsogo** [comment]
`cpp_info.system_libs` are those low-level libraries from the system you need to link to compile your application, like `m` or `pthread`. You can see that there are many recipes in ConanCenter that require them ([link](https://github.com/conan-io/conan-center-index/search?q=cpp_info.system_libs&unscoped_q=cpp_info.system_libs)).

`system_requirements` is more for libraries you install using other package manager (`apt`, `yum`,...), but better that using them in the recipe, I would recommend to add a proxy/virtual recipe with them, so they will appear in the graph of dependencies and consumers might be able to override it once the Conan package is available. You can have a look to the one we are preparing for X11 https://github.com/conan-io/conan-center-index/pull/1605

**Comment by memsharded** [comment]
In Conan 2.0, the system-package requirements are listed in the ``--format=json`` output of ``conan install`` and ``create`` commands. Closing this as solved.
