### ISSUE TITLE
Test layout error with template test package

### ISSUE THREAD

**Issue by opilar** [conan-io/conan#711]
After reading the good [Conan at work](http://blog.conan.io/2016/10/24/conan-at-work.html) article I've created some template test conanfile class:
```python
from conans import ConanFile, CMake
import os


username = os.getenv("CONAN_USERNAME", "sbis")
channel = os.getenv("CONAN_CHANNEL", "stable")


class TestTemplateConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"

    def requirements(self):
        self.requires(self.library + "@%s/%s" % (username, channel))
    
    def build(self):
        with open(os.path.join(self.conanfile_directory, "CMakeLists.txt"), "w") as f:
            f.write("""cmake_minimum_required(VERSION 2.8.11)

project(test_exec)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(test_exec main.cpp)
target_link_libraries(test_exec ${CONAN_LIBS})
""")

        cmake = CMake(self.settings)
        command_line = cmake.command_line
        
        # Workaround with cmake + msys: https://github.com/conan-io/conan/issues/625
        if self.settings.os == "Windows" and self.settings.compiler == "gcc":
            command_line += ' -G "Unix Makefiles"'

        self.run('cmake "%s" %s' % (self.conanfile_directory, command_line))
        self.run("cmake --build . %s" % cmake.build_config)

    def test(self):
        self.run(os.path.join("bin", "test_exec"))
```
And my test package conanfile has a nice implementation:
```python
import sys
sys.path.insert(0, '..')
from template import TestTemplateConan


class TestConan(TestTemplateConan):
    library = "iconv/1.14"
```
But with `conan test_package` I'm getting that error:
```
******* conan test command layout has changed *******

In your "%s" folder 'conanfile.py' you should use the
path to the conanfile_directory, something like:

    self.run('cmake %%s %%s' %% (self.conanfile_directory, cmake.command_line))
```
Seems to be [_test_check](https://github.com/conan-io/conan/blob/7dcabb7f03a28b2f11b963b5d66c7fe1eb6e7e30/conans/client/command.py#L147) fails with [the first check](https://github.com/conan-io/conan/blob/7dcabb7f03a28b2f11b963b5d66c7fe1eb6e7e30/conans/client/command.py#L155).

**Comment by lasote** [comment]
Yes, we are looking at "conanfile_directory" the main test conanfile.py, in your case it is in the included file, so we are not able to detect it. It's just a warn message, that we will remove anytime, so by now you can ignore it or maybe dirty hack it writing a comment with #.conanfile_directory in your main test conanfile :package:

**Comment by opilar** [comment]
I don't like dirty hacks. It's a warn message and it should be gone in one of next releases. I'll wait for it.

**Comment by memsharded** [comment]
Hi @opilar,

This error message has been removed now (conan 0.21), you don't need the hack anymore, so I think this issue can be closed. Please try and tell, or reopen the issue if necessary.
