### ISSUE TITLE
[question] why there is no requires field in cpp_info?

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7110]
In pc file, we can define requires field. I want to put this in pc file generated by pkg-config generator. But there is no such field. The Requires field seems only get filled by the required conan package. So far the work around is to add them to libs. But why not give user freedom to add the Requires? Some of them might from system packages.
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @braindevices!

I'm not very familiar with pkg_config files, but I would expect the `Requires` field in the file generated by Conan to list the dependencies, is it not the case? Why do you want to add to that field?

If you want to add other dependencies that are not Conan packages, there are other approaches: you can create a proxy recipe that doesn't compile or package the library, that recipe will only check that the library is available somewhere and populate the `cpp_info` field, Conan will generate files for any generator you want. You can have a look to this recipe here: https://github.com/conan-io/conan-center-index/pull/1535

Another alternative, is to override the behavior of the `pkg_config` config generator, but I think the first approach is more flexible.

**Comment by braindevices** [comment]
@jgsogo Thanks a lot for the tips. I looked into the recipe you mentioned. But I only see you add the libs to system_libs. I did not see any code actually propagate the Cflags, include dirs. Is it some how automatically handled? Can you point me a direction?

**Comment by jgsogo** [comment]
For that concrete recipe, let's invoke @SSE4 , he can tell you why or why not that information is needed in `cpp_info`. 

But you can use the same approach and add all the information needed for your package.

**Comment by SSE4** [comment]
yes, I think it's more reliable and portable to propagate everything (include dirs, c flags, etc.) to `cpp_info`. it's working right now with just `system_libs` on selected Linux distros, but it might not be enough for all systems.
right now it works because on majority of distros OpenGL is installed to well-known locations (e.g. `/usr/include`) which are automatically added by the compiler itself. but nobody prevents you from installing OpenGL into non-standard location.

**Comment by memsharded** [comment]
Closing as outdated, ``cpp_info.requires`` exists from a long time, also ``cpp_info.component[].requires``. Please create new tickets if necessary.
