### ISSUE TITLE
[question] Any way to skip dependency install

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan#7111]
Is there any way to skip install dependencies of a conan library? For example, my app depends libA/1.0.0(shared), and libA/1.0.0 depends libB/1.0.0(static). There is no need to install libB, and sometimes the depends chains is very long, which take lots of time to install(especially some huge lib such as boost).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! No, there is no current way to do it. This is something I would like to consider for Conan v2 with an improved graph model, but right now Conan retrieves the full graph of dependencies with the packages matching your configuration.
