### ISSUE TITLE
[question] CMake variables without calling conan build

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [conan-io/conan#7112]
We use the CMake generator with targets i.e.
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
```
We keep our `conan build` as bare bones as possible i.e.
```
    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```
This allows us to utilise our IDE's CMake support during development i.e. we can
1. conan install
2. use the IDE to re-build / integrate intellisense etc

This works great.
Otherwise we need to call `conan build` each time, which recompiles and is therefore slow.

We now have a situation where we need to pass optional variables to CMake depending on the configuration. So 
```
    def build(self):
        cmake = CMake(self)
        if condition:
             cmake.definitions["XXX"] = "YYY"
        cmake.configure()
        cmake.build()
```
but then the logic isn't available for the IDE development work-flow.

Is there an appropriate work-around? I was considering appending the variable to the `conanbuildinfo.cmake` but I'm not entirely sure there is a post conan install method  to do that?

One can obviously do it manually each time, but that's not great.

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Mirko-von-Leipzig 

We are aiming to introduce this as experimental for next release: https://github.com/conan-io/conan/pull/7076/files

It is the "toolchain()" feature. It will allow to generate a toolchain file with your variables for better build-system native integration

**Comment by Mirko-von-Leipzig** [comment]
Ah great, thank you!

**Comment by memsharded** [comment]
Looking forward to hearing your feedback when it is released :)
