### ISSUE TITLE
[question] how to specify a custom generator?

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7119]
The default ones are registered with short names. The custom one seems always use the class fullname. Should we let the custom one registered by the name member?
```
class ABCDGenerator(Generator):
    name = 'abcd'
```

Another question is: is it possible to use custom generator with conan command line `-g=`? It seems there is no way to require/import the generator at command line without the conanfile.txt

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
> Should we let the custom one registered by the name member?

As described in the documentation, it uses the class name by default. You should use the attribute `name` only if you want to rename:

https://docs.conan.io/en/latest/reference/generators/custom.html

Your example uses `ABCDGenerator`, but you renamed to `abcd`. There is no problem renaming to a shorter name if it helps and fits the generator objective.

> Another question is: is it possible to use custom generator with conan command line -g=? It seems there is no way to require/import the generator at command line without the conanfile.txt

No. It must be used as a conan package, only the official generators embedded in Conan client are able to be used with `-g` argument. You can take a look in an excellent example in the documentation:

https://docs.conan.io/en/latest/howtos/custom_generators.html

**Comment by braindevices** [comment]
@uilianries Thanks a lot. But at least in conan 1.25.2, the `name` has no effect.

**Comment by jgsogo** [comment]
The doc says that the name will be taken literally from the class name, that's the only restriction. Besides that you can list that generator in the recipe itself (`generators = "MyGenerator"`) or use it from the command line with the argument `--generator/-g MyGenerator`.

Up to now, all the use-cases so far have been a recipe defining the generator it is going to use, so using the name of the class was not a big issue (it was hardcoded in the recipe itself, no UX concerns). 

Let's add this as a feature request, it requires an easy change here https://github.com/conan-io/conan/blob/ed6b33681d1cf25e486518400d0bd845bf5c9aa1/conans/client/loader.py#L306

**Comment by memsharded** [comment]
Closing as outdated, Conan 2 has changed custom generators a lot, using python-requires or global cache generators.
