### ISSUE TITLE
[question] Passing cmake variables from recipe consuming tool package

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#7123]
Hi guys,
I'm trying to provide a tool for our build system using conan.

In the recipe that builds that tool, I'm adding the binary to the PATH:
```
 def package_info(self):
        self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))
        self.env_info.TOOL = os.path.normpath(os.path.join(self.package_folder, "bin", tool))
```
On my consuming app we have a very basic conanfile that looks like this:
```
class Conan(ConanFile):
   name = "App"
   version = "1.0.0"
   settings = "arch"
   generators = "cmake_find_package"

   def build_requirements(self):
        self.build_requires("tool/version")

   def equirements(self):
        self.requires("libA/version")
        self.requires("libB/version")

```
And we're running `conan_cmake_run` from our base `CMakeLists.txt.

I would need to run that tool from cmake, using `add_custom_command()`. Is there a way to create a cmake variable that points to the binary from within our consuming conanfile? To clarify what I need is access to self.env_info.TOOL from cmake. 

Because if I understand correctly, the variables that I set in env_info are only available inside source(), build(), package() and imports() in the consuming conanfile.

Thanks!
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this was not responded back then.
Closing it as outdated, it is referring to legacy 1.X and removed features as ``env_info``.
Please create new tickets reporting against Conan 2.X if necessary, thanks!
