### ISSUE TITLE
[feature] Allow customizing install prefix in the Meson helper

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#7125]
Currently, the Meson build helper hardcodes the install prefix to `self.package_folder`. This is not always desirable, e.g. in our case we want to do some post-processing on the files after the build, but before `package()`. My attempts at resolving this:

##### 1. Attempting to customize the install prefix as I would on the meson command line:

```py
    meson.configure(args=["--prefix", "install"])
```

Will cause

```
ERROR: Got argument prefix as both -Dprefix and --prefix. Pick one.
```

If I set it in the `defs` param, it simply gets [overwritten](https://github.com/conan-io/conan/blob/develop/conans/client/build/meson.py#L133) in conan code here:

```py
        # overwrite default values with user's inputs
        self.options.update(defs)
```

(note that the comment says user's inputs, but this value is not set by the user).

##### 2. Attempting to set DESTDIR for ninja: 

```py
    os.environ["DESTDIR"] = "./install"
    meson.install()
```

This will prepend whatever is set in the environment dir to the package path, so in this case it becomes `./install/home/....long path....`. Not sure why this is, probably ninja behavior.

##### 3. Overwriting `options` in the meson helper

```py
    meson = Meson(self)
    inst_dir = Path("install").resolve()
    inst_dir.mkdir(parents=True)
    meson.options["prefix"] = str(inst_dir)
```

This _works_, but it's not great: it's undocumented and manipulates internal data of the helper. I think it would be best if there was an `install_folder` parameter to the configure method that allows setting this. 

**Do note that all other values set in `options` in the constructor are similarly hardcoded** from the user's point of view because of the same line I linked above.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by TheQwertiest** [comment]
`configure(..., defs={'prefix': 'my_custom_prefix'})` will do the trick.

**Comment by sztomi** [comment]
@TheQwertiest nope, as I mentioned I tried that, too. The reason is the [line](https://github.com/conan-io/conan/blob/develop/conans/client/build/meson.py#L134) I linked. Well, more precisely, prefix is hardcoded [here](https://github.com/conan-io/conan/blob/develop/conans/client/build/meson.py#L39):

```py
        if self._conanfile.package_folder:
            self.options['prefix'] = self._conanfile.package_folder
```

So no matter what you set there, it will be overwritten.

**Comment by TheQwertiest** [comment]
Uhm, but that's exactly why it *will* work =)
```
configure(... defs={'prefix': 'my_custom_prefix'}):
    ...
    # self.options['prefix'] == self._conanfile.package_folder

    self.options.update(defs) # Per Python docs: `Update the dictionary with the key/value pairs from other, overwriting existing keys`
    # self.options['prefix'] == 'my_custom_prefix'
    ...
    arg_list = join_arguments([
            ...
            self.flags, # Converts `self.options` to string
        ])
```

**Comment by sztomi** [comment]
oh! you must be right. I could swear I tried that and it didn't work, but I'll check again. Thanks for pointing that out

**Comment by TheQwertiest** [comment]
Haha, no problem, happens to the best of us =)
The current Meson integration interface is confusing and redundant: the thing is, if you pass some arguments via `args` kwarg they will be ignored, but they will work if you pass them via `defs` kwarg (which should've been named `options`).

**Comment by sztomi** [comment]
@TheQwertiest yeah, that worked fine. I think I set `-Dprefix` as the key originally and then looked for an explanation in the source, but totally overlooked that the update was happening in the other direction. Sorry for the noise.
