### ISSUE TITLE
Conan SLL problems on Windows Server 2016

### ISSUE THREAD

**Issue by bilke** [conan-io/conan#713]
I have a clean install of Windows Server 2016 Standard and Conan 0.15.0. When I try to `conan info` or `conan install` I get a Windows error message that *conan.exe has stopped working*. When I debug this in Visual Studio I see that the call stack where the exception occurs is at `_ssl.pyd`. The exception occurs after Conan prints `Trying with 'conan.io'`. Do you know what is causing this?

**Comment by memsharded** [comment]
Could you please try with the latest 0.16?
Also, which installation where you using? We are now recommending the Pypi/pip one.

**Comment by bilke** [comment]
Alright, everything is working as expected with Conan 0.16 installed via `pip`. Thanks!

**Comment by memsharded** [comment]
Great, thanks for telling!
