### ISSUE TITLE
[feature] Add support of `install()` in CMake generator.

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#7139]
CMake provides the command https://cmake.org/cmake/help/v3.17/command/install.html

It would be useful to support a method to install files from a package using CMake's `install` command.

**Comment by uilianries** [comment]
@DmitrySokolov This feature is already available for the CMake helper.

Please, read the documentation:

https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#install

**Comment by DmitrySokolov** [comment]
It is not what I mean.

**Comment by DmitrySokolov** [comment]
I need a stuff in a `conanbuildinfo.cmake` that I can put/call/whatever into `install()` in my app.

**Comment by DmitrySokolov** [comment]
To date, I have to locate each lib file mentioned in `CONAN_LIBS` and put in into `install()`.

**Comment by uilianries** [comment]
If you want to collect each artifact generated in the package, I recommend using the [deploy generator](https://docs.conan.io/en/latest/reference/generators/deploy.html) instead.

**Comment by DmitrySokolov** [comment]
It does not what actually CMake's `install()` do. In the end I expect to get

```
app
  |- bin
      |- app.exe
      |- openssl.dll
      |- zlib.dll
```

not 
```
app
  |- bin
      |- app.exe
      |- openssl
          |- LICENSE
          |- include/*
          |- lib/*
      |- zlib
          |- zlib stuff
```

**Comment by memsharded** [comment]
It seems you want to declare an ``imports`` in your conanfile, to retrieve all *.dll:

- in conanfile.txt: https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports
- in conanfile.py: https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports

**Comment by DmitrySokolov** [comment]
Yes, it's can be used, but:

1. a package can contain .dll that is not intended to be deployed, for instance - Qt has a lot of tools near the DLLs;
2. the same as 1, and cross-platform dev, so file masks in `[import]` section should distinct target OS.

And in the end you've got another script in `conanfile.txt`.

**Comment by DmitrySokolov** [comment]
And besides, you need to re-install packages each time you clean up the stage dir.

**Comment by memsharded** [comment]
For advanced functionality not available in conanfile.txt, like conditionals based on platform, you should be using a ``conanfile.py`` and the ``imports()`` method instead of the ``[import]`` from conanfile.txt.

> a package can contain .dll that is not intended to be deployed, for instance - Qt has a lot of tools near the DLLs;

You can use any pattern to select the ones that you want, and the ``self.copy()`` can also provide ``excludes`` patterns too: https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports

> And besides, you need to re-install packages each time you clean up the stage dir.

I don't understand what you mean.

A couple of things to be noted:
- When getting packages from the Conan cache, and doing a copy to the local user folder, nothing related to the build systems or the ``build()`` method of those recipes can be used. Most times, a pre-compiled binary is the thing that it is installed, and build folders, build scripts are not even there at all. The sources and the CMakeLists.txt might not be at all at the cache.
- Things need to work in all build systems. Any build system can be used interchangeably in the depedencies and the consumers.

**Comment by DmitrySokolov** [comment]
> I don't understand what you mean.

```
root
 |- build
 |
 |- install
 |   |- bin
 |   |- doc
 |   |- share
 |
 |- src
```
When you want to build from the scratch, you delete `build` and `install` dirs. Since you need to install packages again to fill in `install/bin` dir.

Another drawback of having `import()` in conanfile.py is that you tie the end user to the certain dir tree structure. While having this stuff in conanbuildinfo.cmake does not.

**Comment by memsharded** [comment]
For your info: ``conanbuildinfo.cmake`` from the ``cmake`` generator is most likely going to be removed in Conan 2.0. The current direction is:

- Using ``cmake_find_package`` generators for a transparent integration of dependencies via ``find_package`` cmake native feature
- Using toolchain files, to implement the conversion of Conan settings to CMake configuraiton, in the CMake way.

So it doesn't seem possible to add more stuff to ``conanbuildinfo.cmake`` at the moment, sorry. If you want some cmake code that does operation over dependencies, then probably the way to go is a custom generator: https://docs.conan.io/en/latest/integrations/custom.html#create-your-own-generator

**Comment by DmitrySokolov** [comment]
Hmm, there are 50+ packages in out project
```cmake
include(${CMAKE_BINARY_DIR}/conan_paths.cmake)
find_package(Lib01)
find_package(Lib02)
find_package(Lib03)
find_package(Lib04)
find_package(Lib05)
...
find_package(Lib50)

if(TARGET Lib01::Lib01)
   target_link_libraries(${PROJECT_NAME} Lib01::Lib01)
endif()
if(TARGET Lib02::Lib02)
   target_link_libraries(${PROJECT_NAME} Lib02::Lib02)
endif()
if(TARGET Lib03::Lib03)
   target_link_libraries(${PROJECT_NAME} Lib01::Lib03)
endif()
if(TARGET Lib04::Lib04)
   target_link_libraries(${PROJECT_NAME} Lib04::Lib04)
endif()
if(TARGET Lib06::Lib06)
   target_link_libraries(${PROJECT_NAME} Lib01::Lib06)
endif()
...
if(TARGET Lib50::Lib50)
   target_link_libraries(${PROJECT_NAME} Lib50::Lib50)
endif()
```
instead of
```cmake
include(conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
target_link_libraries(${PROJECT_NAME} PRIVATE ${CONAN_TARGETS})
```

Is it really necessary to type so much boilerplate code?

**Comment by memsharded** [comment]
> Hmm, there are 50+ packages in out project

50 independent packages? Only direct dependencies should be used, and transitive dependencies should be managed by them. The ``cmake_find_package_multi`` generator does this. The new ``msbuild`` generator (introducing it now in 1.26) does this.

> Is it really necessary to type so much boilerplate code?

This is the result of massive push from the community and users towards a more transparent integration with cmake. This is the CMake way, I don't love it, but it is the way it is, and what the rest of the users want. I'd like if CMake had a standard way to define dependencies more easily and directly, but there isn't. So for Conan 2.0, we will be promoting this as the default way to integrate with cmake. If there is need for that, then, we might end adding yet another generated file that can be included and define all targets, but internally it will be calling ``find_package()`` for each one of the direct ones. This is what we did for ``msbuild`` new generator. There is a ``conan_zlib.props``, ``conan_poco.props`` file per dependency, but also a ``conan_deps.props`` that gathers all dependencies and can be included directly.

**Comment by DmitrySokolov** [comment]
> 50 independent packages?

Yes. Total package count is 400+.

**Comment by jgsogo** [comment]
The CMake way to add dependencies is with the `find_package(....)` call, for every dependency. If you want to get rid of all these calls in your project you can write a custom generator (maybe 10 python lines) to create a file doing that work for you.

The generator will create this file automatically (a for-loop in Python):

**mycustom_generator.cmake**
```cmake 
include(${CMAKE_BINARY_DIR}/conan_paths.cmake)

# for package in dependencies
find_package(package)

if(TARGET package::package)
   target_link_libraries(${PROJECT_NAME} package::package)
endif()

...
# endfor
```

and you can include it in your CMake script:

**CMakeLists.txt**
```cmake
cmake_minimum_required(VERSION 3.16)
project(my_project)

include(${CMAKE_BINARY_DIR}/mycustom_generator.cmake)

...
```

Will this work? If you think this approach might fit your needs, I can help you to write that custom generator.

Thanks!

**Comment by DmitrySokolov** [comment]
Thank you, I see a lot of methods to fix it. In the context of discussion of version 2.0 I think that it would be nice to elaborate a handy solution.

I expect (and I think it's reasonable) that when I create `conanfile.txt` recipe for a project it should be enough to
```cmake
include(conanbuildinfo.cmake)
target_link_libraries(${PROJECT_NAME} ${CONAN_TARGETS})
```
I see no reason to type a boilerplate code to add each package that I've already added into the recipe to the project dependencies.

**Comment by jgsogo** [comment]
Yes, we surely will keep providing a straightforward CMake integration like the one you suggest. `find_package` will be prioritized, but some plug-and-play solution must be available too (like the current `cmake` generator but without the toolchain part).

Thanks!

**Comment by memsharded** [comment]
This ticket is outdated, closing it.
``cmake_find_package`` and ``cmake`` integrations were replaced by ``CMakeDeps`` (and removed in 2.0). 
Only CMake idiomatic ``find_package()`` is supported.
For the case of installing dependencies binaries, Conan 2.0 offers the  new deployers, which can be custom code by the user to do exactly the deploy that they expect.
