### ISSUE TITLE
[bug] recursive copies of .git folder in the conan short path dir

### ISSUE THREAD

**Issue by lukastvrdy** [conan-io/conan#7140]
### Environment Details (include every applicable attribute)
  * Operating System+version: Win10 1903
  * Compiler+version: MSVC2015
  * Conan version: 1.24.0
  * Python version: 3.8.3

### Steps to reproduce (Include if Applicable)
TBA  as I don't know them exactly yet

Setup environment variable settings:
CONAN_USER_HOME=E:\conan
CONAN_USER_HOME_SHORT=E:\conan_short
CONAN_USE_ALWAYS_SHORT_PATHS=1 

1. build the package from the source directory 
conan create ...
2. search for ".git" in $CONAN_USER_HOME_SHORT path E:\conan_short in my case

Sometimes I experience that after building the package using conan from source directory, 
some content is recursively copied to the conan package folder. 
![image](https://user-images.githubusercontent.com/11041952/83613199-fd22ea00-a572-11ea-9b5e-8f2a882764b4.png)

### Logs (Executed commands with output) (Include/Attach if Applicable)
TBA

**Comment by memsharded** [comment]
Hi @lukastvrdy 

I have tried to reproduce with ``conan create``, but not possible so far. I would need a recipe and the creation steps, the actual commands that you are using, in what order, and how many times. Thanks!

**Comment by memsharded** [comment]
conan short_paths removed in 2.0, closing as outdated
