### ISSUE TITLE
Simplify sh.exe removal for CMake with MinGW

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#7142]
in the past, I have found it here: https://stackoverflow.com/questions/41333215/mingw-sh-exe-must-not-be-in-your-path
it adds a cache entry for the `CMAKE_SH`, which is going to be used by `find_program(sh)`.
reading the [doc](https://cmake.org/cmake/help/latest/command/find_program.html), there are few parts to make it work:
```
If nothing is found, the result will be <VAR>-NOTFOUND
```

```
the search will not be repeated unless the variable is cleared
```

_Originally posted by @SSE4 in https://github.com/conan-io/conan/pull/7076_

**Comment by jgsogo** [comment]
Let's read all the CMake docs about it:

> This command is used to find a program. A cache entry named by `<VAR>` is created to store the result of this command. If the program is found the result is stored in the variable and the search will not be repeated unless the variable is cleared. If nothing is found, the result will be `<VAR>-NOTFOUND`, and the search will be attempted again the next time find_program is invoked with the same variable.

If `sh` is found, it won't be searched again, if it is not found (`<VAR>-NOTFOUND`) the search will be attempted again for the next `find_program`. 

So, first time CMake executes a `find_program(CMAKE_SH sh.exe )` it will run the search and, if `sh` is in the PATH, it will find `sh` and fail as it would fail without it. IMO, the only way for it to work is to effectively remove `sh` from the PATH before running CMake configure.

What am I missing here?
