### ISSUE TITLE
[question/feature] Get package name from command line

### ISSUE THREAD

**Issue by TheQwertiest** [conan-io/conan#7143]
Is there any way to get package name from recipe from command line?

This is needed to make a generic script that builds and publishes (to repo) packages knowing only the directory that contains a recipe. Thus it needs the name of the package as to publish only the package that was built and not any others.

I've thought that `conan info --only=name` would work, but for some reason `name` is not in the list of allowed options: https://github.com/conan-io/conan/blob/0f1bd5a75fcc40b73e09a19797094b9ee3a3c234/conans/client/command.py#L606

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Have you tried ``conan inspect .``?

**Comment by TheQwertiest** [comment]
Now I did, thanks!
