### ISSUE TITLE
[feature] discard recipe from a set of versions

### ISSUE THREAD

**Issue by flashdagger** [conan-io/conan#7145]
Requirements can be specified with version ranges allowing for multiple versions to be considered.
Conan uses node-semver to determine the highest version within the set. Versions that differ only by metadata (e.g. 0.1+tag) are considered equal, so the most recent is used. When the chosen version is not compatible with the build settings an error can be thrown (e.g. _ConanInvalidConfiguration_).

Imagine I need to have two different recipes with the same version each supporting only one OS because the logic would be too complex to handle in one recipe. I name them **libA/0.1+windows** and **libA/0.1+linux**. 

I specify my requirement as **libA/[0.1]**. At the moment conan would chose only one of them which would work only for one OS. Could there be a mechanism in the recipe to tell conan that it should discard the version and try the next candidate from the set of versions?

Maybe this could be done by throwing a special exception in the  _configure()_ method...

**Comment by jgsogo** [comment]
Hi, @flashdagger 

From the POV of semver, both versions `0.1+windows` and `0.1+linux` are indistinct, there is no order between them and both match exactly the same patterns. Conan only chooses the most recent by chance, but it is not guaranteed. 

You should probably approach the problem from a different perspective. Recipes for `libA/0.1+windows` and `libA/0.1+linux` should be the same `conanfile.py` file and based on the OS you can implement different logic, you can run different build script, declare different difference and you can even retrieve different sources if necessary.

I'm sure you've already considered this alternative and I wonder why it didn't work for your use case. I'd love to know.

Thanks!

**Comment by KerstinKeller** [comment]
> You should probably approach the problem from a different perspective. Recipes for libA/0.1+windows and libA/0.1+linux should be the same conanfile.py file and based on the OS you can implement different logic, you can run different build script, declare different difference and you can even retrieve different sources if necessary.

Personally, I have tried this, and it leads to messy and hard to maintain recipes, if you do completely different things on different OS's. 

One way to avoid the mess, is to kind of use a pattern to keep all logic in one recipe but distribute over different Implementations (don't know how this pattern is called from a software point of view)

```
#Implementation Linux
class SomeLibConanSystem:   
    def __init__(self):
        pass
        
    @classmethod
    def is_suitable_system_version(cls, conanfile):
        return ....
      
    def configure(self, conanfile):
        # throw if not supported

    def source(self, conanfile):
        pass

    def build(self, conanfile):
        pass
       
    def package(self, conanfile):
        pass    
 
    def system_requirements(self, conanfile):
        self.system_version_resolver.install_system_version(conanfile)

#Implementation Windows
class SomeLibConanPrebuildWindows:
    def __init__(self):
        pass

    def configure(self, conanfile):
        meta.raise_on_invalid_version(conanfile)

    def source(self, conanfile):
        pass
        
    def build(self, conanfile):
        # do the build aka download

    def package(self, conanfile):
        # do the packaging
    
    def system_requirements(self, conanfile):
        pass

# Generic Implementation
class SomeLibConan(ConanFile):
    name = "somelib"
 
    def configure(self):
        if self.settings.os == "Windows":
            self.implementation = SomeLibConanPrebuildWindows()
            self.implementation.configure(self)
        elif SomeLibConanSystem.is_suitable_system_version(self):
            self.implementation = SomeLibConanSystem()
            self.implementation.configure(self)                   
        else:
            raise ConanInvalidConfiguration("Platform / version not supported")       

    def source(self):
        self.implementation.source(self)

    def build(self):
        self.implementation.build(self)

    def package(self):
        self.implementation.package(self)
        
    def system_requirements(self):
        self.implementation.system_requirements(self)
```

Problem here is, that the actual implementations here do not inherit from `ConanFile`, as there can be only one `ConanFile` per recipe. That's why I prefer the proxy recipe method.

```
class SomeLibConan(ConanFile):
    name = "somelib"
    settings = "os", "compiler", "arch"

    def requirements(self):
        if self.settings.os == "Windows":
            self.requires.add("somelib-prebuilt-windows/{}@user/stable".format(self.version))
        if self.settings.os == "Linux":
            self.requires.add("somelib-system-linux/{}@user/stable".format(self.version))
```
E.g. the idea is, that the library recipe is only a proxy recipe, directing to the actual recipes, depending on the platforms. You could also add options, e.g. `system` vs `source-build`, and direct the requirements based on those options.

It leads to cleaner and more easy to read recipes, but I have not tried how well it scales in production regarding the dependency resolution.

@flashdagger, I hope this helps and gives you some hints on other approaches to solve the problem.

**Comment by jgsogo** [comment]
That's another approach, **using different library names** (do not try different versions with different semver-metadata), from the POV of Conan they will be different references. As @KerstinKeller  shows, you can use that kind of _proxy recipe_ to delegate to the proper one based on the `os` setting.

---

Note.- @KerstinKeller , `self.requires.add` works but it is not documented, you should use `self.requires(...)`

**Comment by flashdagger** [comment]
Thanks for the feedback. Anyway, the correct approach would be to provide one recipe for all platforms and configurations. In our company we usually start with one implementation and later provide ports further platforms. This means rewriting the recipe which leads to unwanted rebuilds and deployments for platforms that are already working.
Another approach would be to let the consumer conditionally specify the correct recipe:
```
if self.settings.os == "Windows":
    self.requires("libA/0.1+windows@")
elif self.settings.os == "Linux":
    self.requires("libA/0.1+linux@")
...
```

**Comment by jgsogo** [comment]
There are different alternatives and all of them have some pros and cons. It depends on the concrete use-case. Some will make the recipe too complex, others won't work with version ranges,... anything else related to this issue?

**Comment by flashdagger** [comment]
Just wanted to have clarification on this issue for myself and as a rationale for my colleagues.
As conan tackles a very complex domain, it is interesting to see all the different views on possible solutions. They are often not straight forward nor obvious, but the community here tries to discuss them in an open and sensible way. Thank you.
