### ISSUE TITLE
Improve docs for '--update'  argument in commands

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#7146]
I got the following problem:
In my project, I normally build my packages with `conan create`.
Now I wanted to use `conan graph lock` to pickup up a previous build from Artifactory.

Now there is a different behavior between both commands.
I use semver versioning and also the `include_prerelease` option. 
Unluckily I still got a library, which require a library without `include_prerelease`.

So I got:

**ProjA** require **LibB** & **LibC**
**LibB** require **LibC**.

**ProjA** has the following requirement for **LibC**: `>=1.6.5-dev <2.0.0-dev, include_prerelease=True`
**LibB** this one for **LibC**: `^1.3.0-dev`

**LibC** exits on the Artifactory in two versions:
 * `LibC/1.6.6+master.g34a1cfb@demo/testing` -> stable version
 * `LibC/1.6.7-dev.0+master.g1fea313@demo/testing` -> prerelease version

With  `conan create` is uses:
  * `LibC/1.6.7-dev.0+master.g1fea313@demo/testing` -> prerelease version 

and with `conan graph lock`:
  * `LibC/1.6.6+master.g34a1cfb@demo/testing` -> stable version

It's the question, what is the correct result. 
Anyway it should be for both commands the same. 

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu LTS 18.04 and Win10
  * Compiler+version: GCC8
  * Conan version: 1.25.2
  * Python version: 3.6.9 and 3.7.5

**Comment by jgsogo** [comment]
Having a look at this issue, I've created a repo here (https://github.com/jgsogo/issue-7146) to reproduce the scenario with a minimal recipes.

First of all, as it is described, I get an error:

```bash
⇒  conan create projA.py
...
ERROR: Version range '^1.3.0-dev' required by 'LibB/1.0@demo/testing' not valid for downstream requirement 'LibC/1.6.7-dev.0+master.g1fea313@demo/testing'
```


```bash
⇒  conan graph lock projA.py
...
ERROR: Version range '^1.3.0-dev' required by 'LibB/1.0@demo/testing' not valid for downstream requirement 'LibC/1.6.7-dev.0+master.g1fea313@demo/testing'
```

--- 

I've modified `LibB` to include prereleases:

```
requires = "LibC/[^1.3.0-dev, include_prerelease=True]@demo/testing"
```

then:

```bash
⇒  conan create projA.py
...
WARN: LibB/1.0@demo/testing: requirement LibC/[^1.3.0-dev, include_prerelease=True]@demo/testing overridden by ProjA/1.0 to LibC/1.6.7-dev.0+master.g1fea313@demo/testing 
...
Version ranges solved
    Version range '>=1.6.5-dev <2.0.0-dev, include_prerelease=True' required by 'ProjA/1.0' resolved to 'LibC/1.6.7-dev.0+master.g1fea313@demo/testing' in local cache
    Version range '^1.3.0-dev, include_prerelease=True' required by 'LibB/1.0@demo/testing' valid for downstream requirement 'LibC/1.6.7-dev.0+master.g1fea313@demo/testing'

Installing package: ProjA/1.0
Requirements
    LibB/1.0@demo/testing from local cache - Cache
    LibC/1.6.7-dev.0+master.g1fea313@demo/testing from local cache - Cache
    ProjA/1.0 from local cache - Cache
Packages
    LibB/1.0@demo/testing:f065f71c9f26013ecf404d3b8a378899272d5edf - Missing
    LibC/1.6.7-dev.0+master.g1fea313@demo/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    ProjA/1.0:48b788393343665082ca528370945905800b2c44 - Build
```

and 

```bash
⇒  conan graph lock projA.py
{'1.6.6+master.g34a1cfb': LibC/1.6.6+master.g34a1cfb@demo/testing, '1.6.7-dev.0+master.g1fea313': LibC/1.6.7-dev.0+master.g1fea313@demo/testing}
1.6.7-dev.0+master.g1fea313
WARN: LibB/1.0@demo/testing: requirement LibC/[^1.3.0-dev, include_prerelease=True]@demo/testing overridden by ProjA/1.0 to LibC/1.6.7-dev.0+master.g1fea313@demo/testing 
Version ranges solved
    Version range '>=1.6.5-dev <2.0.0-dev, include_prerelease=True' required by 'projA.py (ProjA/1.0)' resolved to 'LibC/1.6.7-dev.0+master.g1fea313@demo/testing' in local cache
    Version range '^1.3.0-dev, include_prerelease=True' required by 'LibB/1.0@demo/testing' valid for downstream requirement 'LibC/1.6.7-dev.0+master.g1fea313@demo/testing'

Requirements
    LibB/1.0@demo/testing from local cache - Cache
    LibC/1.6.7-dev.0+master.g1fea313@demo/testing from local cache - Cache
Packages
    LibB/1.0@demo/testing:f065f71c9f26013ecf404d3b8a378899272d5edf - Missing
    LibC/1.6.7-dev.0+master.g1fea313@demo/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
```

--- 

I'm getting the same version using any of the commands. Can you try recipes from the repo? Do you get the same output? Is there any difference that should be taken into account to reproduce your scenario?

About resolution order, Conan should always build the graph in the same order, but when there is a diamond Conan resolves the branch that is computed first and then checks that the requirements satisfy restrictions coming from the different branches (if not, raises an error)

**Comment by climblinne** [comment]
Ok, sorry for the hassle. But it was again the update (this time at `conan graph lock` , see #6294) where I stumbled.
After removing the conan cache everything works fine. 
May be the documentation of the misleading "update" should be optimized?

**Comment by jgsogo** [comment]
I agree `--update` is confusing. Let's improve the docs and keep the other issue for Conan v2.0 if a new behavior is needed.

Do you have any suggestion for the help string?

Thanks!

**Comment by climblinne** [comment]
"Check updates exist for the current `path_or_reference` from upstream remotes. 
It's not checking for updates its dependencies! Clean your local cache instead, when you want to update also the dependencies."
