### ISSUE TITLE
[bug] Incorrect compiler detection for `clang` with `--gcc-toolchain={}` option

### ISSUE THREAD

**Issue by nburles** [conan-io/conan#7150]
When setting e.g.
```
CC="clang-9 --gcc-toolchain=/usr/lib/gcc/x86_64-linux-gnu/9"
CXX="clang++-9 --gcc-toolchain=/usr/lib/gcc/x86_64-linux-gnu/9"
```
Conan will autodetect `gcc` as the compiler because of this line: https://github.com/conan-io/conan/blob/0eea418adf86a93ad3a9547be6e16a3c980ffc4b/conans/client/conf/detect.py#L78

**Comment by nburles** [comment]
Maybe the `CC` / `CXX` variables should be processed somewhat, to ignore short-form / long-form arguments before checking for `gcc` / `clang` / etc?

**Comment by memsharded** [comment]
Good point, thanks for reporting, indeed seems a bug.

In any case, I would like to recall that for production we recommend using profiles, that will properly define ``settings.compiler=clang``, and there will be no confusion.

**Comment by nburles** [comment]
Absolutely, and that's what I've changed our system to do (once I worked out how on earth it was getting confused :-)... setting up more specific profiles based on the build targets (previously we **just** set `CC` and `CXX` in the environment for each of the cross-compilers we are using - we will continue doing that of course).

**Comment by uilianries** [comment]
Implemented by #9198

**Comment by memsharded** [comment]
Can we consider this closed then @uilianries ?

**Comment by uilianries** [comment]
@memsharded  YEs!
