### ISSUE TITLE
[bug] incorrect architecture for iOS (CMake) 

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#7156]
from https://github.com/conan-io/conan-center-index/issues/1806
given the profile:
```
Configuration for profile ios_armv7:

[settings]
os=iOS
os_build=Macos
arch=armv7
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
os.version=7.0
[options]
[build_requires]
[env]
```
and building the sqlite3 as:
```
conan create . sqlite3/3.29.0@ -pr ios_armv7 -o sqlite3:build_executable=False
```
the resulting library has incorrect architecture:
```
lipo -info /Users/sse4/.conan/data/sqlite3/3.29.0/_/_/package/a281bf9414dc8d2cef9c827e2aa0d98a10930163/lib/libsqlite3.a
Non-fat file: /Users/sse4/.conan/data/sqlite3/3.29.0/_/_/package/a281bf9414dc8d2cef9c827e2aa0d98a10930163/lib/libsqlite3.a is architecture: x86_64
```
(notice **x86_64**)
expected output:
```
lipo -info /Users/sse4/.conan/data/sqlite3/3.29.0/_/_/package/a281bf9414dc8d2cef9c827e2aa0d98a10930163/lib/libsqlite3.a
Non-fat file: /Users/sse4/.conan/data/sqlite3/3.29.0/_/_/package/a281bf9414dc8d2cef9c827e2aa0d98a10930163/lib/libsqlite3.a is architecture: armv7
```
the same applies to all CMake-based projects, e.g. BZip2 has the same problem.

### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 10.15
  * Compiler+version: Apple Clang 11.0
  * Conan version: 1.27.0
  * Python version: 2.7.16

**Comment by perseoGI** [comment]
I'm closing this issue as it was solved in https://github.com/conan-io/conan/pull/7164
