### ISSUE TITLE
[question] make generator does not set CONAN_CXXFLAGS as expected

### ISSUE THREAD

**Issue by vajdaz** [conan-io/conan#7159]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

When running ```conan install . -s arch=x86``` on an x86_64 System, I expect a compiler option like ```CONAN_CXXFLAGS=-m32``` in the generated ```conanbuildinfo.mak``` file, but there is no such an option.

First, the contents of the ```conanfile.txt```:

```
[requires]
mylib/1.0@demo/dev

[generators]
make
```
Here is the output of the ```conan install`` command (cmake has special treatment, because it is only a tool, so the 64 Bit version is ok):
```
$ conan install . -s cmake:arch=x86_64  -s arch=x86
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
cmake:arch=x86_64
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    mylib/1.0@demo/dev from local cache - Cache
Packages
    mylib/1.0@demo/dev:eb79ce42f6e6b4359bd7d0a65a238a4dae953257 - Cache
'''
Cross-build from 'Linux:x86_64' to 'Linux:x86'
Installing (downloading, building) binaries...
mylib/1.0@demo/dev: Already installed!
conanfile.txt: Generator make created conanbuildinfo.mak
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
```
The generated makfe file looks like this:
```
#-------------------------------------------------------------------#
#             Makefile variables from Conan Dependencies            #
#-------------------------------------------------------------------#

CONAN_ROOT_MYLIB ?=  \
/home/username/.conan/data/mylib/1.0/demo/dev/package/eb79ce42f6e6b4359bd7d0a65a238a4dae953257

CONAN_SYSROOT_MYLIB ?=  \


CONAN_INCLUDE_DIRS_MYLIB +=  \
/home/username/.conan/data/mylib/1.0/demo/dev/package/eb79ce42f6e6b4359bd7d0a65a238a4dae953257/include

CONAN_LIB_DIRS_MYLIB +=  \
/home/username/.conan/data/mylib/1.0/demo/dev/package/eb79ce42f6e6b4359bd7d0a65a238a4dae953257/lib

CONAN_BIN_DIRS_MYLIB +=  \


CONAN_BUILD_DIRS_MYLIB +=  \
/home/username/.conan/data/mylib/1.0/demo/dev/package/eb79ce42f6e6b4359bd7d0a65a238a4dae953257/

CONAN_RES_DIRS_MYLIB +=  \


CONAN_LIBS_MYLIB +=  \
mylib

CONAN_SYSTEM_LIBS_MYLIB +=  \


CONAN_DEFINES_MYLIB +=  \


CONAN_CFLAGS_MYLIB +=  \


CONAN_CXXFLAGS_MYLIB +=  \


CONAN_SHAREDLINKFLAGS_MYLIB +=  \


CONAN_EXELINKFLAGS_MYLIB +=  \


CONAN_FRAMEWORKS_MYLIB +=  \


CONAN_FRAMEWORK_PATHS_MYLIB +=  \


CONAN_ROOTPATH +=  \
$(CONAN_ROOTPATH_MYLIB)

CONAN_SYSROOT +=  \
$(CONAN_SYSROOT_MYLIB)

CONAN_INCLUDE_DIRS +=  \
$(CONAN_INCLUDE_DIRS_MYLIB)

CONAN_LIB_DIRS +=  \
$(CONAN_LIB_DIRS_MYLIB)

CONAN_BIN_DIRS +=  \
$(CONAN_BIN_DIRS_MYLIB)

CONAN_BUILD_DIRS +=  \
$(CONAN_BUILD_DIRS_MYLIB)

CONAN_RES_DIRS +=  \
$(CONAN_RES_DIRS_MYLIB)

CONAN_LIBS +=  \
$(CONAN_LIBS_MYLIB)

CONAN_DEFINES +=  \
$(CONAN_DEFINES_MYLIB)

CONAN_CFLAGS +=  \
$(CONAN_CFLAGS_MYLIB)

CONAN_CXXFLAGS +=  \
$(CONAN_CXXFLAGS_MYLIB)

CONAN_SHAREDLINKFLAGS +=  \
$(CONAN_SHAREDLINKFLAGS_MYLIB)

CONAN_EXELINKFLAGS +=  \
$(CONAN_EXELINKFLAGS_MYLIB)

CONAN_FRAMEWORKS +=  \
$(CONAN_FRAMEWORKS_MYLIB)

CONAN_FRAMEWORK_PATHS +=  \
$(CONAN_FRAMEWORK_PATHS_MYLIB)

CONAN_SYSTEM_LIBS +=  \
$(CONAN_SYSTEM_LIBS_MYLIB)
#-------------------------------------------------------------------#
```
Conan knows, that this is a cross-build, it knows the compiler, it builds mylib with 32 bitness (or takes the 32 bit binaries, if found in the repo). So it should be obvious, that my app needs to be compiled with -m32. But this is not visible in any of the CONAN_xxx make variables.

Why is my expectation wrong?

**Comment by vajdaz** [comment]
I have found the solution myself. If a ```conanfile.py``` is used with the autotools/make helper instead of the simple ```conanfile.txt```, then it is possible to build the app with ```conan build .```, and conan sets all compiler options and defines correctly. Here is an example of such a consumer receipt:
```
from conans import ConanFile, AutoToolsBuildEnvironment
from conans import tools

class AppConan(ConanFile):
    name = "mayapp"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    requires = "mylib/1.0@demo/dev"
    generators = "make", "virtualrunenv"

    def build(self):
        atools = AutoToolsBuildEnvironment(self)
        atools.make()
```

**Comment by memsharded** [comment]
Hi @vajdaz 

An important concept about generators: They output files with information from dependencies. If the package ``mylib`` contained something like:

```python
def package_info(self):
    self.cpp_info.cxx_flags = "some cxx flags"
```
Then in your generated ``conanbuildinfo.mak`` will contain ``CONAN_CXX_FLAGS`` with that ``some cxx flags`` value.

A very different thing is the "build helper", in this case, the ``AutotoolsBuildEnvironment``, is a tool to help translating the Conan inputs, like settings, into build system commands, typically the command line. This is why unless you call it with ``conan build``, it doesn't work.  

We are introducing in next release 1.26 the concept of toolchains: https://github.com/conan-io/conan/pull/7076. This means that ``conan install`` will also generate files for the current package settings, not only from dependencies, so it is possible to directly call the build system without ``conan build``. Initially it has support for CMake, but other build systems will follow.

If this explains it a bit better, and you managed to make it work, please close the issue as responded. Thanks!
