### ISSUE TITLE
[question] Remove packages on Artifactory

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#7161]
I would like to remove packages on the Artifactory Conan repository. Up to now, I do this by using the following dummy code

```
query = "(arch=x86_64 AND compiler=clang) or (compiler=gcc)"
search ="*/*@review/*"
conan search -r remote "search"
for each package in ...:
  conan search -r remote -q query "package"
  conan remove -r remote --force -q query "package"
```

I would like to do this directly on the Artifactory server. Could you give an example, how to do it?
Thanks!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
I belive you could do something similat with the jfrog CLI and delete items in a recursive way https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-DeletingFiles

**Comment by danimtb** [comment]
After no more activity in this issue, I consider the question was answered. Thanks you!
