### ISSUE TITLE
[feature] Environment variables for download_cache path in conan.conf

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#7165]
In case the download cache folder is not located in the same path on different CI agents (e.g. Windows vs. Linux) there should be a way to maintain a common `conan.conf` by using environment variables (e.g. `$HOME`) to specify parts of the `download_cache` path or fully override it (`CONAN_DOWNLOAD_CACHE`).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @petermbauer,
Thanks a lot for the feedback. I agree that there should be a way of specifying that folder for multiple platforms, maybe using relative paths to the cache or using `~` to specify the `download_cache` folder.
We'll take this into account for next releases.

**Comment by memsharded** [comment]
Closing as outdated/solved.

``conan.conf`` was replaced by ``global.conf`` and profiles, and both allow jinja syntax, which allows environment variables usage.

If there are any questions or issues, please open a new ticket against Conan 2, thanks for your feedback.
