### ISSUE TITLE
[question] Is there a way to force an update from a Conan remote to local cache?

### ISSUE THREAD

**Issue by senorpr** [conan-io/conan#7168]
I just learned that when doing something like:
`conan install . -r conan-local --update`

It does not actually force an update, it will only compare the local cache against what's in the remote Conan repo and say:
`WARN: Current package is newer than remote upstream one`

So basically if the local cache has been updated, but it has not yet been uploaded to Artifactory, I could get this warning. This is the case where one user are doing development but the changes have not yet been officially integrated to the system. The package from that user could be exported to local cache. Then another user could get that package in local cache into their compile (via conan install) as opposed to the official copy in the remote repo.

**Background:**
We are using Jenkins and are prototyping using Conan to do our builds. We were thinking of having different users use the same local cache under the Jenkins user home area. Is this NOT recommended? Should I be using a brand new CONAN_USER_HOME for every Jenkins job I run?

Or, is there a way I can use the same Jenkins CONAN_USER_HOME and update the local cache with the remote (official) copy, as needed?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by sourcedelica** [comment]
Related question - is there a way to simply get a list of all local packages that aren't in a remote (based on a `conanfile`)?

**Comment by senorpr** [comment]
Is there a way to force an update from a Conan remote to local cache?

**Comment by Johnnyxy** [comment]
I think you have to remove the package from your local repository first.
I never saw a option otherwise than removing the package until now.
You can only ensure that a local older recipe gets updated via "--update" ([docs here](https://docs.conan.io/en/latest/reference/commands/consumer/install.html#conan-install)).

**Comment by danimtb** [comment]
> Is there a way to force an update from a Conan remote to local cache?

As replied earlier, the only way to force this right now is to remove the package in the local cache and install from remote again. We are considering this for a reimplementation in the new Conan 2.0 CLI.

> is there a way to simply get a list of all local packages that aren't in a remote (based on a conanfile)?

I am not sure about what you mean with "based on a conanfile", but I think there is no way to check  if the exact same packages are already uploaded to a remote. I think it will be something nice to have in a 2.0 version as well

**Comment by senorpr** [comment]
Thanks. I recently found out that because I'm using this in the context of Jenkins, due to the concurrency issue, I have to use a [new CONAN_USER_HOME for each job](https://stackoverflow.com/questions/62288299/conan-local-cache-when-using-with-jenkins). That in turn would mean a clean new local cache area, and update would not be necessary.

**Comment by sourcedelica** [comment]
@danimtb - I mean, not for every package that is in my local cache, just the packages that are listed in a conanfile, like the way `conan install` and `conan info` work.

**Comment by senorpr** [comment]
Most of our questions have been answered. I will be closing this issue. Thanks.
