### ISSUE TITLE
[feature] New generator which sources all virtualenv's

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#7173]
I would like to have a generator which sources under the hood all virtualev's, at least `activate.sh` and `activate_run.sh`

So I do not have to do:
```
source activate.sh
source activate_run.sh
```

I found this guide here: https://docs.conan.io/en/latest/howtos/custom_generators.html
However, I would like to avoid creating the virtualenv generators again. DRY.
So I need to derive from the existing ones or invoke them.

Is it possible that someone creates such a generator? Or give me some tip how to write it.

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Why do you need to use both generators at the same time? Could you give us more background please?

**Comment by derived-coder** [comment]
I have a package for a Qt application created. This package needs the `LD_LIBARY_PATH` & `PATH` env and additional some Qt environment variables: `QML2_IMPORT_PATH` & `QT_PLUGIN_PATH`

`QML2_IMPORT_PATH` & `QT_PLUGIN_PATH` are available in the activate.sh
 `LD_LIBARY_PATH` & `PATH` are available in the activate_run.sh

**Comment by danimtb** [comment]
Ok, now I understand the need. Writing a custom generator with inheritance from the `virtualenv` and `virtualrunenv` should be very straightforward. Otherwise I am not how could we fix this. Maybe merging all virtualenv generators into the same one?

**Comment by derived-coder** [comment]
This issue is not about fixing anything. This is a feature request. So are you going to implement a new generator which does this?
I unfortunately don't know how to do this. Would be could to have an example which derives from an existing one. So this example would be good in the docs. Or implement the new generator

**Comment by danimtb** [comment]
You can see an example here https://github.com/conan-io/conan/blob/develop/conans/client/generators/virtualrunenv.py although inheritance is not mandatory, you could instantiate both `VirtualRunEnvGenerator` and` VirtualEnvGenerator` and merge their contents into a single file

**Comment by memsharded** [comment]
Closing as solved and outdated, new VirtualXXXEnv generators already generate aggregator scripts that launch all the other ones.
