### ISSUE TITLE
[feature] Add Conan package name and version to visual studio generator prop file

### ISSUE THREAD

**Issue by Hbkhan** [conan-io/conan#7177]
Can we get the feature to add `CONAN_PACKAGE_NAME` and `CONAN_PACKAGE_VERSION` to the visual studio generator prop file? Currently, Conan does support adding package name and version through CMake generator. The feature I am talking about is mentioned [here](https://github.com/conan-io/conan/blob/c923c692fb14dd3ad0a66bab308b4a59f6a037dc/conans/client/generators/cmake_common.py#L71-L73) for CMake generator

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @Hbkhan 

Can you share a little bit more about your need? I see that this `name` and `version` could only be the one from the final consumer (and there is not always a consumer, e.g. `conan install <ref> -g <generator>`)... so depending on how you use Conan, these fields will be empty and they actually take a `None` value.

Maybe with more context and knowing the scenario we can think about a better approach.

Thanks

**Comment by puetzk** [comment]
To keep consistency, we want to have the project version defined in only one place and flow it down from there the various places that need to embed it (cmake configure_file, MSBuild WriteLinesToFile or `<PreprocessorDefinitions>`). The top-level ConanFile seemed like a good place for this to come in from, flowing out through the generator(s) and into the build. We have 

I agree that these can sometimes be `None` if there isn't one set (a conanfile.txt, or conanfile.py without `version` or `set_version(self)`).

We have some CMake projects already doing this with `project(... VERSION ${CONAN_PACKAGE_VERSION}` to bring it in via conanbuildinfo.cmake, but just tried to do similar things with a .NET core project which uses .csproj files instead, and found out that the info was not included by the "visualstudio" generator as it is by the "cmake" one. Which seemed a little surprising, so I told @Hbkhan to ask if there was a reason, or if it could be added.

**Comment by jgsogo** [comment]
Yes, this is something useful. Thinking about the next Conan version, we will promote the approach with a toolchain-like file separated from the information of the consumers. In the CMake work it is the `cmake_find_package[_multi]` generator plus the CMake toolchain we've just introduced in `1.26.0` release (it will require some refinement before it is ready for production environment). We are investigating how a toolchain-like file will look like for the `visual studio` generator, and other build_systems, I hope these _custom variables_ can be added to all of them.

In this approach, it totally makes sense to add the `name` and `version` to that toolchain-like file, that file is generated only when there is a root project and it belongs to that root project.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/7645 implemented this, will be in 1.32.

Please @Hbkhan take into account that the recommended generator and moving forward will be the ``msbuild`` generator, not the ``visual_studio`` one.
