### ISSUE TITLE
[bug] options after --install-folder are ignored if it conatins a space

### ISSUE THREAD

**Issue by lieser** [conan-io/conan#7179]
If `conan install` is called with an `--install-folder` argument that contains a space, the options after `--install-folder` seem to be ignored.

1. `conan install . -g visual_studio --install-folder "foo\" -s arch=x86`
    - `arch=x86` is used as expected
2. `conan install . -g visual_studio -s arch=x86 --install-folder "foo bar\"`
    - `arch=x86` is used as expected
3.  `conan install . -g visual_studio --install-folder "foo bar\" -s arch=x86`
    - `arch=x86_64` from default profile is incorrectly used

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 (1809)
  * Compiler+version:
  * Conan version: Conan version 1.26.0
  * Python version: Python 3.8.3

### Steps to reproduce (Include if Applicable)
Default profile:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

1. Call  `conan install . -g visual_studio --install-folder "foo bar\" -s arch=x86`
2. Configuration used incorrectly contains `arch=x86_64` instead of `arch=x86`

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
> conan install . -g visual_studio --install-folder "foo bar\" -s arch=x86
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

**Comment by lieser** [comment]
On further tests, the behavior seems related to the `\` at the end of the folder name. I thought that in the windows command line, `\` is not used as an escape character. But according to https://ss64.com/nt/syntax-esc.html, a trailing backslash can still cause problems.

Strange thing is why the backslash is only causing problems if there a space in the folder name?

Note that I found now a workaround by removing the backslash at the end, so fixing this has low priority for me. Also feel free to close this bug, if you consider this expected behavior.

**Comment by jgsogo** [comment]
From your link, I read:

> The \ escape can cause problems with quoted directory paths that contain a trailing backslash because the closing quote " at the end of the line will be escaped \".

> To save a directory path with a trailing backslash (\) requires adding a second backslash to 'escape the escape'
so for example instead of "C:\My Docs\" use "C:\My Docs\\"

I'll add this one to the backlog with a low priority. It is something we can take a look at at some point in time.

**Comment by memsharded** [comment]
``--install-folder`` has been removed in 2.0, closing this as outdated/can't be fixed.
This might keep happening for other arguments that include paths, Conan can do little with it and it requires quoting at the terminal, because that parsing happens before Conan receives the arguments. The recommendation would be to use those arguments the last ones in the command line.
