### ISSUE TITLE
[bug] Interrupted install leaves locks in bad state

### ISSUE THREAD

**Issue by cguldner** [conan-io/conan#7181]
I am running Conan in a docker container, and while a package is installing, if I `docker stop` the container that Conan is running in, then try running the Conan container again, I get the

```
<name>/<version>@<channel> is locked by another concurrent conan process, wait...

If not the case, quit, and do 'conan remove <name>/<version>@<channel> -f
```

Even running `conan remove --locks` directly before running the command doesn't help. I have to force remove the package before it starts working again.

Continuation of #2071, since that issue was closed.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Conan version: 1.25.2
  * Python version: Python 3.5

**Comment by jgsogo** [comment]
We need to revisit the locking mechanism we are currently using for the Conan cache, and for sure we want to use a library/mechanism that doesn't block after this kind of failure.

I'll add it this one to backlog, but probably changing the lock implementation need to wait until the next major version we are already planning.

**Comment by floriansimon1** [comment]
I faced an issue where my CI builds would be blocked to locks not being released. When I looked up the lock count files in `~/.conan/data/thepackage`, it said `-1`, which makes me think there might be a bug in Conan. Have you heard of this by any chance?

**Comment by kutschkem** [comment]
@floriansimon1 -1 simply indicates a write lock.

https://github.com/conan-io/conan/blob/f230bf104842c160be6ea377497151fe1ea64c38/conans/util/locks.py#L90-L100

**Comment by floriansimon1** [comment]
Thanks for the info!

**Comment by memsharded** [comment]
The ticket to track Conan 2 concurrent cache effort is https://github.com/conan-io/conan/issues/7181, closing this one, lets follow up on the other, thanks.
