### ISSUE TITLE
[bug] A multi build type -> 1 package cannot depend on package relying itself on the build type

### ISSUE THREAD

**Issue by Siron777** [conan-io/conan#7186]
Hi,

When a package C depends on a package S, and both are build in a _N build type-> 1 package_ mode:

- the _create_ command for the package C will not install the multiple build type necessary of S to compile C. It will only install the default build_type or the one specified with _-s build_type_. 
- And according to the question https://github.com/conan-io/conan/issues/5341, if the package S is not a _N build type-> 1 package_, it will also only download the package S with the default build_type or the one specified with _-s build_type_.

I am missing something or Conan is lacking a mechanism to specify which build type of S the package C will really need ?

Simon

**Comment by jgsogo** [comment]
Duplicated https://github.com/conan-io/conan/issues/7184
