### ISSUE TITLE
Ability to add dependency sources

### ISSUE THREAD

**Issue by trevex** [conan-io/conan#719]
I recently had a second look at conan and it seems to tick all the boxes. I ran into
an edge case though, that is at least as far as I can see not handled by conan.

Some dependencies don't include a build system. This is specifically relevant to micro-libraries,
where you are supposed to simply include their sources into your build system.

Examples would be:
https://github.com/ocornut/imgui
https://github.com/recastnavigation/recastnavigation

It would be nice to have the ability to add dependency sources and possibly even patch them.
E.g. a project depending on imgui, that patches the imconfig.h to suit their needs.

**Comment by opilar** [comment]
> Some dependencies don't include a build system. This is specifically relevant to micro-libraries,
> where you are supposed to simply include their sources into your build system.
If you build it in a static library it would be the same. 

With your feature you can create an "universal" package. But it will compile in your library anyway. 
I think it's better to compile and package it in the first place just like any other library.

With appropriate conan recipe and feature `conan install --build=missing` you can use your libraries even if there are micro.

**Comment by memsharded** [comment]
Certainly is possible. Consider Golang, in which everything are sources, and they are just imported into the building projects in user space. Check it here: http://docs.conan.io/en/latest/examples/go.html The same can be done to C/C++ packages and other packages. 

Patching to sources can be done at ``source()`` time, as other packages. The main difference would be that the resulting "binary" packages won't have binary artifacts, but source code, which the consuming project can build.

It might be also possible to build them without copying (importing) them into user space, just by using the package paths. Please have a look and tell me if this is suitable for your use case.

**Comment by trevex** [comment]
Thank you very much, 
I was unaware of these features 👍
