### ISSUE TITLE
[bug] conanfile.install_folder is not set in workspaces

### ISSUE THREAD

**Issue by flashdagger** [conan-io/conan#7190]
I have a custom generator which uses the `self.conanfile.install_folder` property.
However when it is used within an editable package via the workspace feature it is set to None.

Since the install_folder exists also for editable packages I would expect to access it in this scenario as well. There even exists and `CustomGeneratorTest.install_folder_test()` in conans test suite.

**Comment by flashdagger** [comment]
Addition:
I discovered that `generator.output_path` is set before the content property is queried. This seems to work all cases. Since is it not documented I wonder if I could use it as part of the generator API.

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
