### ISSUE TITLE
Misleading error message: ConanException: Not a valid 'svn' repository

### ISSUE THREAD

**Issue by pbarrio** [conan-io/conan#7191]
In a project I usually build without issues, I started getting this exception.

After a while trying to figure out what was wrong with the repository, I realized I didn't have SVN in my path since I was working in a different environment. Once I added the path to SVN, it all worked.

Full error message:
while calling 'source', line 91
        tools.SVN(self.folder).update()
        ConanException: Not a valid 'svn' repository

Would it be possible to check for SVN and report a different error message?

**Comment by memsharded** [comment]
Thanks for reporting this.
As this would be a very occasional error, I think just improving the message as proposed in https://github.com/conan-io/conan/pull/7194/files would be enough. What do you think?

**Comment by pbarrio** [comment]
Thank you for fixing! The new message looks good; it says enough to remind
me next time that I forgot to set up my environment properly ;)
