### ISSUE TITLE
[question] minimal conanfile.py created by new command could include requires packages

### ISSUE THREAD

**Issue by ncouronne** [conan-io/conan#7204]
Hi all,

- conan version 1.26

In my company, we are starting using conan to manage dependencies with our proper libraries and external third party libraries.
For internal reason we choose to use conan as it:
- For one internal library A, we define requires in a conanfile.txt to install internal and external dependencies as a consumer
- internal build tool
- Then for the same lib, as a producer, use new and then export-pkg command.
We use the --bare option to generate a minimal conanfile.py which is very helpfull ! But it miss the requires part. As a consequence, the next internal lib which wants to consume A will not grab the dependencies of it.

I've tried to suppress bare option, and use our own minimal conanfile.py but the new command erase it with a demo conanfile.py which has no link to the A lib.

Could it be possible that the bare option use conanfile.txt to grab requires part and include it into conanfile.py? or take it as an option ?
Or is there a way to use the new/export-pkg commands with a custom  conanfile.py ?

For internal reason, we don't want to use conanfile.py for consumer and producer step, mostly for the build part.

Thanks in advance

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! The command `conan new` is just a convenient way to create a minimal example and it is out-of-scope to pass arguments to it (besides the reference) and implement logic based on this arguments (yes, we might remove some of the `-ci` arguments in the next Conan v2).

Nevertheless this command has a `--template` argument that will stay. With this argument you can provide your own template for the `conanfile.py` file and this template can implement any logic, for example it can read the requirements from a `conanfile.txt` file (I need to advise you to use the same `conanfile.py` to create and consume the package), for example:


**<conan-cache>/templates/mytemplate.py**
```python
class {{package_name}}Conan(ConanFile):
    name = "{{name}}"
    version = "{{version}}"
    exports = "conanfile.txt"

    def requirements(self):
        # Use configparser to get the `requirements` section
        requires = [...]
        for it in requires:
            self.requires(it)
```

```
$ conan new --template mytemplate.py
```

Not tested, maybe I'm missing some paths or there are typos in the template, but if this can solve your issue I can help you with the concrete implementation.

Thanks!

**Comment by ncouronne** [comment]
Hi,
Thanks for your answer.
After posting i was  studying the template argument and yes it is a quite good option to solve my issue.
Thanks for your suggestion of parsing the conanfile.txt, it will avoid to store dependencies in two separate location, i will try this !

Thanks again for your advice but as far as i understand using conanfile.py to create and consume package will force us to use the build method of conan.
In term of usage, we would like to keep someyhing like this:
- use conan to locate and install dependences (conan install stuff)
- build with customs scripts as many internal operation are needed not related to conan or cmake
- use conan to create and export-pkg from the install directory after build in step 2 

Is there a way to do this ?

**Comment by ncouronne** [comment]
To complete your template suggestion with the templates/parsing conanfile.txt trick, that's what it looks like:

```python   
class {{package_name}}Conan(ConanFile):
    name = "{{name}}"
    version = "{{version}}" 
    exports = 'conanfile.txt'

    # parse required package from conanfile.txt
    def requirements(self):
        config = configparser.ConfigParser(allow_no_value=True) # by default configparser disallow key without values
        config.optionxform = str # necessary to perserve the letter case of values returned
        config.read('conanfile.txt')
        for req in config['requires']:
            self.requires(req)

**Comment by jgsogo** [comment]
Thanks for sharing the snippet 👍 

---

> Thanks again for your advice but as far as i understand using conanfile.py to create and consume package will force us to use the build method of conan.

That's not needed. The `build()` method can be empty or **it can call your custom scripts**... but anyway, you can use the `conanfile.py` the same way you are using the `conanfile.txt`, you are not forced to run `conan create ...`, you can still run `conan install <path/to/conanfile.py>`, build the library using your own scripts and then `conan export-pkg`.
