### ISSUE TITLE
[feature] Capture the "shared" state of dependencies with shared_library_package_id

### ISSUE THREAD

**Issue by rddesmond** [conan-io/conan#7208]
I just noticed the addition of `shared_library_package_id`!  I love it,  it scratches an itch I was beginning to notice way better than I had thought of (I was just worried about capturing the shared state.. but this is way better).

One addition: have an option to capture the state of the `shared` option for all of the dependencies if the package being built is shared, to make the change from `?:shared=True` to `?:shared=False` obvious.  I think it would build correctly (because the absence of options would imply the dependency was built with `?:shared=True`), but it would be useful to have this in the `full_options` to make this clear.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! I think I'm not understanding your suggestion... can you explain it a little bit more?

Trying to add some info to my answer: you can get the list of your dependencies with [`self.deps_cpp_info.deps`](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-cpp-info) and you can iterate them to get the actual value of the options with `self.options["<depname>"].sahred`.

**Comment by rddesmond** [comment]
Good afternoon!

My apologies, I misunderstood how `shared_library_package_id` works slightly, so I worded my question confusingly.  I thought it caused the options of transitive dependencies to be included (e.g. add `self.options = self.full_options['dep']` for all static dependencies).  Since it sets the package_id instead, it's even better than I thought.  *I'm going to close the issue because the topic isn't really relevant.*

The issue was that shared libraries get no positive attribute (e.g. it's the absence of a `package_id`) to show the dependencies that are shared at build time.  I was worried that that absence information was unsuitable to say that it was compiled against a shared thing, but since the `package_id` is dynamically created, that isn't actually a problem.

## Procedure

1. Create a dependency and build it with with an option that creates incompatible output (e.g. shared on and off)
   ```bash
   mkdir base && cd base
   conan new base/0.1@user/testing
   conan create . -obase:shared=True
   conan create . -obase:shared=False
   ```
1. Create a library (the default for `conan new`) which additionally has a requirement on the dependency and uses `shared_library_package_id`)
   ```bash
   mkdir ../lib && cd ../lib/
   conan new lib/0.1@user/testing
   echo """
       requires = 'base/0.1@user/testing'
    
       def package_id(self):
          self.info.shared_library_package_id()
   """ >> conanfile.py

   conan create . -olib:shared=True -obase:shared=True
   conan create . -olib:shared=True -obase:shared=False
   ```
1. _Notice that components of the conaninfo.txt for lib the `base:shared` only has the fact that it was shared by the absence of base's `package_id`.  There isn't any attribute that positively captures it._

    ```
    conan@vm:~/test/lib$ find ~/.conan -name conaninfo.txt -path *lib/0.1/user/testing/package* | xargs grep -e '\[requires\]' -e '\[full_options\]' -A2

    /home/conan/.conan/data/lib/0.1/user/testing/package/66c49f19274f34c70de832d0f4dbd0526b9d68eb/conaninfo.txt:[requires]
    /home/conan/.conan/data/lib/0.1/user/testing/package/66c49f19274f34c70de832d0f4dbd0526b9d68eb/conaninfo.txt-    base/0.1
    /home/conan/.conan/data/lib/0.1/user/testing/package/66c49f19274f34c70de832d0f4dbd0526b9d68eb/conaninfo.txt-
    --
    /home/conan/.conan/data/lib/0.1/user/testing/package/66c49f19274f34c70de832d0f4dbd0526b9d68eb/conaninfo.txt:[full_options]
    /home/conan/.conan/data/lib/0.1/user/testing/package/66c49f19274f34c70de832d0f4dbd0526b9d68eb/conaninfo.txt-    shared=True
    /home/conan/.conan/data/lib/0.1/user/testing/package/66c49f19274f34c70de832d0f4dbd0526b9d68eb/conaninfo.txt-    base:shared=True
    --
    /home/conan/.conan/data/lib/0.1/user/testing/package/8dbcc21208a8dc6e2d781de25b5e9b0db465d09b/conaninfo.txt:[requires]
    /home/conan/.conan/data/lib/0.1/user/testing/package/8dbcc21208a8dc6e2d781de25b5e9b0db465d09b/conaninfo.txt-    base/0.1@user/testing#4f243017ac6a39ae25c727b924b6af23:57547fe65fffc300f05aa42ee64b3b02eeabb6d7#1f9b6a5c63da3b1f75e5739be26d0dc9
    /home/conan/.conan/data/lib/0.1/user/testing/package/8dbcc21208a8dc6e2d781de25b5e9b0db465d09b/conaninfo.txt-
    --
    /home/conan/.conan/data/lib/0.1/user/testing/package/8dbcc21208a8dc6e2d781de25b5e9b0db465d09b/conaninfo.txt:[full_options]
    /home/conan/.conan/data/lib/0.1/user/testing/package/8dbcc21208a8dc6e2d781de25b5e9b0db465d09b/conaninfo.txt-    shared=True
    /home/conan/.conan/data/lib/0.1/user/testing/package/8dbcc21208a8dc6e2d781de25b5e9b0db465d09b/conaninfo.txt-    base:shared=False
    ```
