### ISSUE TITLE
[question] During cross-compilation, how should build requirements in individual packages depend on other build requirements specified in the host profile? 

### ISSUE THREAD

**Issue by josh-stoddard-tanium** [conan-io/conan#7214]
- conan 1.26.0

Hi,

I'm trying to cross-compile using build and host profiles as described [here](https://docs.conan.io/en/latest/devtools/build_requires.html#build-and-host-contexts). I have a `MyInstaller` package whose `package_info` populates `env_info` with some values that need to be present to build all of my dependencies in the host context, as described [here](https://docs.conan.io/en/latest/reference/conanfile/methods.html#env-info). My host profile includes `MyInstaller` under `build_requires`, and this guarantees that all of my dependencies are build with `MyInstaller`'s `env_info` values applied, as desired.

One of my dependencies, `MyLib`, has its own build requirement, `MyTool`, that has to build using the build profile. `MyInstaller` is not a build requirement in the build profile, so I would expect that its `env_info` would not be applied when building `MyTool` using the build profile. However, I observed that building `MyTool` fails because `env_info` from `MyInstaller` is present.

You can find a minimal repro of this behavior [here](https://github.com/josh-stoddard-tanium/conan-test).

So my question is this: Is this a bug? ie. `env_info` values set by build requirements in a profile **should** only apply to packages built using that profile?  
If not, is there a way to specify that `env_info` from a build requirement applies only to a specific profile?

Thanks in advance

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by josh-stoddard-tanium** [comment]
BTW, I was able to work around the problem by moving all of my build dependencies into the host profile.  Evidently, build requirements in the same profile don't interfere with each other.  This is not an ideal solution, but it unblocks me for the time being.

**Comment by jgsogo** [comment]
I think this issue is the same one we are fixing here: https://github.com/conan-io/conan/pull/7169 cc/ @danimtb

**Comment by jgsogo** [comment]
`1.26.1` has been released with changes from PR https://github.com/conan-io/conan/pull/7169, please check it fixes your issue.

Thanks!
