### ISSUE TITLE
[question] [xbuild] It it reasonable for a package to `build_require` itself?

### ISSUE THREAD

**Issue by josh-stoddard-tanium** [conan-io/conan#7218]
- conan 1.26

For example, [`protobuf`](https://github.com/bincrafters/conan-protobuf)'s recipe builds a runtime library and a corresponding compiler executable `protoc`. Suppose I want to cross compile `protobuf` to [`Emscripten`](https://github.com/bincrafters/conan-emsdk_installer), I would want the runtime lib built for `profile:host` and the compiler built for `profile:build`. Would it make sense for `protobuf` to `build_requires` itself?

something like:
```py
def build_requires(self):
    if self.settings.os == "Emscripten":
        self.build_requires(<myself>)
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi!

It makes sense for a compiler that `gcc`. You need `gcc` to build `gcc`. Probably not as a build_requirement listed in the recipe itself, but something to add in the profile dynamically (under `[build_requires]` section in the `--profile:host`).

For `protobuf`, it is not `protobuf` the one which needs the protoc compiler, it is the consumer. So the natural workflow will be to add `protobuf` as a requirement and as a build-reuqirmeent to your library:

```python
class Conanfile:
    name = "my-pkg"

    requires = "protobuf/..."
    build_requires = "protobuf/..."
````

This will ensure that the protoc executable that is available in the environment will be the one from the _build_ context (the one coming from the build_requires) and, when using `emscripten` (probably it should also be a dynamic build_requires into the `--profile:host`, not something hardcoded), protoc will come exactly from the same package and all the packages in the _host_ context will have EMSDK as build-requires.

Does it make sense?
