### ISSUE TITLE
Rollback for "conan imports"

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#722]
We are using `conan imports` as a part of installation procedure (`make install`). It works great, but `make uninstall` counterpart is still lacking. I think there should be an option in `imports` (or separate conan command) that removed all files that would be created if `conan imports` was run with all the same other parameters.

Another possible solution is that `conan imports` could print paths for all files that it installs, so that list could be appended/prepended to the `install_manifest.txt` produced by cmake. Of course it does not help with other build systems (though still useful to see paths to installed files in the log instead of just `PROJECT imports(): Copied 5 '.dll' files` or something like that.

**Comment by memsharded** [comment]
Yes, make sense. Both things, first the install manifest. I think that it totally makes sense that the imports of files to the user space created an install_manifest.txt (or conan_imports_manifest.txt, or something like that). Not by cmake, but directly by conan itself. That file could be easily used to undo the imports.

**Comment by memsharded** [comment]
This has been implemented and released in 0.17
