### ISSUE TITLE
[feature] Validate arguments to conanbuildinfo.cmake macros

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#7221]
I spent some hours tracking down an unexpected behavior where I did:
`conan_basic_setup(NO_OUTPUT_DIRS,KEEP_RPATHS)`
rather than:
`conan_basic_setup(NO_OUTPUT_DIRS KEEP_RPATHS)`

it would have been useful if the macro validated the passed arguments were valid options, and reported an error about the mistake.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Closing as outdated, this was about legacy ``cmake`` generator
