### ISSUE TITLE
[feature] add the possibility to remove `message` function call in qmake generator

### ISSUE THREAD

**Issue by Forbinn** [conan-io/conan#7222]
Hi, I have notice that currently the `qmake` generator, generates a `conanbuildinfo.pri` which contains a call to the `message` function to tell the developer / package manager, that the current build is in `Release` or `Debug` mode.

The problem is that the function calls are hard-coded [here](https://github.com/conan-io/conan/blob/develop/conans/client/generators/qmake.py#L82) and [here](https://github.com/conan-io/conan/blob/develop/conans/client/generators/qmake.py#L89). If you use the QtCreator IDE each time the `conanbuildinfo.pri` is recreated, a window pops-up to display the message 'Release config' or 'Debug config' and this can be very annoying after a while.

Is there any possibility to remove those messages ?

**Comment by memsharded** [comment]
I am suggesting to remove the messages in https://github.com/conan-io/conan/pull/7228, I don't think they bring much value.
