### ISSUE TITLE
[feature] Support for clang 11 

### ISSUE THREAD

**Issue by anagno** [conan-io/conan#7223]
Hello Everyone,

Is it possible to add in the default settings list the clang 11 (https://clang.llvm.org/docs/ReleaseNotes.html) ?

The compiler is already being actively used from the https://conan.io/center/emsdk_installer/1.39.13 and for the moment I have to manually adapt my settings.yml

~~I think it used to work, but probably some changes with clang-apple removed the version ?! (no idea to be frank. I first noticed it a couple of weeks ago, when a ci job in one of my projects started failing)~~ (I think it is not valid. I notice in the logs that I was still using clang 10)

Probably also related  to:
* https://github.com/conan-io/conan/issues/6910

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, we try to add new versions of the compiler as soon as they are available. Adding some versions is not as easy as adding them to the default `settings.yml` file, but they require to check some flags and defaults that might have changed. We need to monitor webpages with the new releases, to get a push request once they are released.

Does clang11 have a release date? will it include stable c++20?

Maybe we can wait for Conan `1.28` (July) before adding this new release

**Comment by TheQwertiest** [comment]
IMO, it doesn't make much sense adding support for pre-prelease versions of compilers. 
- dev-branch compilers are not guaranteed to be ABI compatible (or stable), which might result in incompatible packages.
- version number might be even changed on release compared to the pre-release (like they did with msvc one time)

**Comment by anagno** [comment]
@jgsogo Unfortunately,  I do not know when the official release date is and what it will include.
The argument of @TheQwertiest is valid and I had not consider all the implications of adding the new compiler :) 

Maybe it is better to wait for the official release :) Dunno

**Comment by memsharded** [comment]
An example that a pre-release can change something relevant regarding the binary compatibility, like the C++ standard default: https://www.reddit.com/r/cpp/comments/hgjjcz/gcc_11_change_the_default_dialect_to_c17/

**Comment by memsharded** [comment]
Now https://clang.llvm.org/docs/ReleaseNotes.html points to Clang 12, while Clang 11 has not been officially released...

It seems that the right approach is to wait until official versions are released as stable. 
Adding them to ``settings.yml`` too early without compiler stability guarantees might introduce more issues than it fixes, and users can locally modify ``settings.yml`` if they want.

**Comment by anagno** [comment]
Should I close this issue then?

**Comment by uilianries** [comment]
@anagno Not necessary, let's wait for Clang 11 to become stable.

**Comment by damageboy** [comment]
Bumping this as clang-11 is basically at RC2 now...

Does this make sense to go for this now?

**Comment by aminya** [comment]
It is RC4 now: https://github.com/llvm/llvm-project/releases

**Comment by memsharded** [comment]
Released now https://releases.llvm.org/11.0.0/tools/clang/docs/ReleaseNotes.html

Lets include it for next Conan 1.30.2

**Comment by memsharded** [comment]
@uilianries could you please do a PR to the ``release/1.30`` branch?

Please remember to check, besides the settings, the default cppstd and similar stuff.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/7871, will be in 1.30.2

**Comment by aminya** [comment]
In my profile, I am trying to set the `compiler.version=11`, but it fails with this error:

```ps1
❯ conan install .. --build=missing
ERROR: Invalid setting '11' is not a valid 'settings.compiler.version' value.
Possible values are ['10', '3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '4.0', '5.0', '6.0', '7.0', '7.1', '8', '9']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

and when I try to build something:
```ps1
CMake Error at conanbuildinfo.cmake:401 (message):
  Detected a mismatch for the compiler version between your conan profile
  settings and CMake:

  Compiler version specified in your conan profile: 10

  Compiler version detected in CMake: 11.0
```

Have you really added support for clang 11? I am using Conan 1.33.1

**Comment by memsharded** [comment]
Hi @aminya 

Yes, it has been added, you can check: https://github.com/conan-io/conan/blob/edc269b2edcae72c0cc056e95ec2ffe9b1d8fa3b/conans/client/conf/__init__.py#L95

What is possible is that you had some changes in your cache ``settings.yml`` and when upgrading Conan to latest version, it didn't migrate the ``settings.yml``. If you remove that file from your Conan cache, it will be regenerated to match the latest settings, please try and let us know.

**Comment by aminya** [comment]
Yes, removing the file manually fixed the issue.

**Comment by koxu1996** [comment]
File removal:
```
$ rm ~/.conan/settings.yml
```
