### ISSUE TITLE
[question] Help understanding correct usage of self.cpp_info.build_modules

### ISSUE THREAD

**Issue by craigaiken** [conan-io/conan#7225]
I have two conan packages that I am developing.  Let's just call them A and B.  Package A produces a cmake module that I export.  So I have something that looks like this in A's conanfile.py:

```
def package(self):
    self.copy("foo.cmake", dst="cmake_modules")
def package_info(self):
    self.cpp_info.build_modules = ["cmake_modules"]
```

Then I want to use foo.cmake in B.  B defines requires AND build_requires for A in its conanfile.py.  Then in B's CMakeLists.txt:

```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
include(foo)
```
But I see a cmake error during conan create:
```
CMake Error at CMakeLists.txt:9 (include)
  include could not find load file:
  foo
```
Examining the generated conanbuildinfo.cmake, I'm not seeing any reference to the cmake_modules path that I had added into A's cpp_info.build_modules.   Is my understanding and usage correct here?

I'm using conan version 1.25.2 on Linux.

**Comment by danimtb** [comment]
Hi @craigaiken,

`self.cpp_info.build_modules` should contain the relative paths to the files you want to include.
Something like:

```
def package(self):
    self.copy("foo.cmake", dst="cmake_modules")
def package_info(self):
    self.cpp_info.build_modules.append(os.path.join("cmake_modules", "foo.cmake"))
```

That should make it work. Please give it a go and let me know 😄

**Comment by craigaiken** [comment]
Hi @danimtb,

This explains how it works a bit better.  This wasn't fully clear in the documentation.  Now I see that I can do this and I don't need to do the "include(foo)" line in B's CMakeLists.txt.  It looks like foo.cmake gets automatically included just by doing the initial conan_basic_setup().  Thanks for clarifying this for me.
