### ISSUE TITLE
[bug] conan install fails for conan center packages with new naming convention

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#7227]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 64-bit
  * Compiler+version: n/a
  * Conan version: 1.26.0
  * Python version: 3.7.2

### Steps to reproduce (Include if Applicable)
1. conan install glm/0.9.9.5@g-truc/stable ...works
2. conan install glm/0.9.9.8
   * ERROR: Conanfile not found at C:\..\..\current_dir\glm\0.9.9.8

**Comment by memsharded** [comment]
Hi @rconde01 

This is not a bug, this is expected. The only way it was possible to introduce in the command line packages without user/channel, and not be confused with a path, is terminating the package with:

```bash
$ conan install glm/0.9.9.8@
```

This will be changed in the new command line for Conan 2.0, but at the moment it is necessary.

**Comment by rconde01** [comment]
ok - thanks
