### ISSUE TITLE
[question] What does cmake.configure do exactly?

### ISSUE THREAD

**Issue by anthonypan08** [conan-io/conan#7229]
So the project that I am working on compiles fine when I just make it ordinarily. However, I would get a compilation error if I try to make it with  `conan create .` It seem to be due to the -Werror flag is turned on as the "error" was just supposed to be a warning. 

Upon closer inspection, it seemed cmake.configure method was doing something to the repo. I tried to assert false right after cmake.configure() and it would start throwing an error if I go into the repo and make it on terminal. **My question is: What is cmake.configure doing? Is it turning on the -Werror flag? Is there anyway to turn the flag off?** 

I have attached the build method of my conanfile.py below
![image](https://user-images.githubusercontent.com/20074651/85238010-04624880-b3f9-11ea-9066-0475e0922c94.png)

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
``cmake.configure()`` is calling the cmake project generation, equivalent to ``cmake <path-to-src> -G "<Generator>`` plus some other flags, depending on the operating system, compiler, and other settings and options.

Enabling ``log.print_run_commands`` conf, you can see the actual commands that are being issued by Conan, no need to print() them.

Said that, It seems ``werror`` is not found in Conan codebase, so it might come from elsewhere, maybe the ``CMakeLists.txt``? Do you have something reproducible?

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
