### ISSUE TITLE
support windows without Visual Studio

### ISSUE THREAD

**Issue by s-trooper** [conan-io/conan#723]
Hi,  i am on Windows 7 64 Bit without a Visual Studio. I have trying conan [Getting started](http://docs.conan.io/en/latest/getting_started.html) but i am failed, can any one help me?

When i replace <code>cmake .. -G "Visual Studio 14 Win64"</code> with <code>cmake -G "MinGW Makefiles</code> or <code>cmake -G Ninja</code>, both works in my cmake setup, i will get:

> Incorrect  'Visual Studio', is not the one detected by CMake: 'GNU'

**Comment by memsharded** [comment]
Hi!

The settings you use to build have to match the settings used for installing your dependencies. Your install command should look like:

```bash
$ conan install -s compiler=gcc -s compiler.version=4.9 ...
```
Please copy here your install command output and if possible your settings defaults (should be the same that are stored in your ``<userfolder>/.conan/conan.conf``

A note of warning: Some packages in conan.io mainly provide binaries and support for Visual Studio, it is possible that they will not have binaries and fail to build (with ``--build`` install option) when you try to install them. Any especial constraint not to use VS in Win, especially now that it is free?

**Comment by s-trooper** [comment]
Yes, you're right it's seems the Poco package does not support my setup:
```
> conan install .. -s compiler=gcc -s compiler.version=6.2
> ERROR: Poco/1.7.3@lasote/stable: 'settings.compiler.libcxx' value not defined
```

To the question why i don't use VC++, why should I? I don't have any problem with MinGW so far, and when conan/packaging don't work so  be it.

Thank you for help!

**Comment by memsharded** [comment]
Try to provide the flags:

```bash
$ conan install .. -s compiler=gcc -s compiler.version=6.2 -s compiler.libcxx=libstdc++ --build=missing
```

I don't think the recipes are prepared to handle that setup, but you can try.

Regarding the support for MinGW, there are two different things here. Conan supports MinGW in Windows,  it is tested in the automatic test suite, we run locally and in CI (appveyor). 

But, on the other hand, MinGW has a relatively small market share, so many package creators just don't support it on their recipes, they don't create binaries for it, and they not test if it builds either, which usually don't.

We know some users using conan with MinGW regularly, but they use in-house conan_server and maintain their own private packages for their projects. So conan seems to be prepared for MinGW. It would be very nice if more MinGW developers contributed to public package recipes in conan.io to support MinGW builds.

**Comment by s-trooper** [comment]
i don't have the access to my windows box for a week, but i will test the command. 
i am curious regarding:
> I don't think the recipes are prepared to handle that setup ...

i don't understand yet: it will be always the case, in c++ wold that a reciptes for a setup are missing. What is the conan way to handle such cases? private servers with cusoms builds/recipes? collaborate with package maintainer, but then, not all of them will have time/effort for such pull requests?

Is it a way to create "recept" per project? so conan can handle all the package/dependency managment up to compile step and then apply this local "recipt"?

**Comment by memsharded** [comment]
Conan is the package manager, it provide the tools to handle package recipes and package binaries.

There are two wildly different use cases. 

- Conan.io provide a free, public repository of package recipes and binaries for free software, mainly OSS. Uploading packages to conan.io is free, not moderated. Anyone can upload their own recipes and binaries at any time, and no guarantees are made that they will work. Similar to github, you can upload code there at anytime, but that code might not build or run at all. The code in github might build and work for some operating system or compiler, but might not work at all for other settings. It is up to the developer. But it is a model that so far seems to work very well. It is exactly the same for package creators in conan.io. Same flows, same tools, similar community. Actually the typical way to collaborate on a conan package recipe is to submit a PR to a github repository containing the code for the package recipe. Most package creators will love to get feedback and fixes to their packages, others might not have time, or maybe they don't use that library anymore and don't care.

- conan_server provides a free private server that can be easily hosted in a company, in-house. This is actually the current approach of most conan users. Note that C/C++ are very industrial, corporate languages, and the nature of these companies is to have their own private development infraestructure. They will not use the binaries from conan.io. They might fork the package recipes for some OSS packages they might be using, but they maintain those recipes themselves, privately. They might strip support for the recipes for different settings that they are not using.

About creating packages for existing libraries/projects, it is not a difficult process if you already know how to properly build such library/project. Creating a package for a header-only library is done in minutes. The fact is that some OSS projects are quite difficult to build, specially multi-platform, even if not using conan. Creating a package for a typical library with CMake support, can be done in short time (10-20 min per OS) if you know very well how to build and use it. I have sometimes spent days to be able to build and use some libraries I didn't know, so conan will not improve over this time, no magic :)

**Comment by s-trooper** [comment]
I really appreciate that you took so much time to help me, now i understand the way i can use conan in my setup. I going to close this issue as there are no feature to request :)

**Comment by memsharded** [comment]
No worries, glad that I could help :)
Don't hesitate to open new issues, or contact us by email/twitter if you have any further question or feature request, thanks!
