### ISSUE TITLE
[bug] Better default separation in conan graph

### ISSUE THREAD

**Issue by cguldner** [conan-io/conan#7234]
When using hashes as the version of my packages, the default conan graph looks pretty bad:

![conan_graph](https://user-images.githubusercontent.com/2721458/85305804-2dbfba80-b473-11ea-9cf6-15f867770c16.png)

Is it possible to increase the default node separation of the graph if the title is long?

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu
  * Conan version: 1.25.2
  * Python version: 3.5

**Comment by jgsogo** [comment]
Hi, @cguldner 

Starting with `1.27`, the template for the `conan info --graph` output can be overridden by the user (https://github.com/conan-io/conan/pull/7176). This can motivate other people to share their templates that will be much better than ours and, if allowed, we can improve our default ones inspired by those contributions.

I'll add this issue to the queue, not a high priority given other features we need to implement, but I really expect users to contribute to these templates (there's already some interest: https://github.com/conan-io/conan/pull/6815)

**Comment by alacasta** [comment]
Hello @cguldner 

I've tested the feature mentioned by @jgsogo and looks pretty easy to create your customized templates and actually interesting for everybody probably to use your/others suggested templates to display the Dep. Graph.

Take a look to https://github.com/alacasta/beautified-conan-info-dot-template where i've translated the proposal i made to enrich the default DOT output to this template-based output. 

I hope it helps you!

**Comment by cguldner** [comment]
@alacasta That is helpful, thank you!

**Comment by jgsogo** [comment]
Nice to hear it is useful (and used!) 😊
