### ISSUE TITLE
[question] How to get the full id of the exported package?

### ISSUE THREAD

**Issue by gsemet** [conan-io/conan#7239]
Hello

I try to automatize on our CI the publication of the packages, it works fine but I had to develop a small python script to read an information I cannot guess: the exported package id (from the json generated by `conan export-pkg --json`)
`conan inspect` does not seem to be able to read it. 

But that annoys me since this script would need to be available into every projects I intend to switch to conan... Do you have a better idea?

Use case:
```bash
$ mkdir build/
$ cd build
$ conan build ..
$ conan export-pkg --force --json conan-export-info.json ..

# => now, if I want to upload I need the id in conan-export-info.json, 
# which contains already the right user/channel

$ EXPORTED_CONAN_PACKAGE=$(./scripts/get_exported_info \
        --input build/conan-export-info.json
        --get id)
$ conan upload -r ${CONAN_PUSH_REMOTE_NAME} \
        --all --confirm \
        --json conan-upload-info.json \
        ${EXPORTED_CONAN_PACKAGE}
```

Many thanks for your help

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi @gsemet 

The package-ID information is available in the generated output:

```
conan new -b name/version@user/channel
conan export-pkg . --json=out.tmp --force
⇒  cat out.tmp 
{"error": false, "installed": [{"recipe": {"id": "name/version#f272c9de17e436b6e6f2ab871d6192da", "downloaded": false, "exported": true, "error": null, "remote": null, "time": "2020-06-25T08:50:08.646694", "dependency": false, "name": "name", "version": "version", "user": null, "channel": null}, "packages": [{"id": "103f6067a947f366ef91fc1b7da351c588d1827f", "downloaded": false, "exported": true, "error": null, "remote": null, "time": "2020-06-25T08:50:08.653303", "built": false}]}]}
```

The JSON contains the generated package-ID: `103f6067a947f366ef91fc1b7da351c588d1827f`

Am I missing something?

**Comment by gsemet** [comment]
Yes, that's what I use. But I need to write a small python script to extract this value, and that's not very convenient. Any easier way to tell to `conan upload` to just upload what has been exported directly?

**Comment by jgsogo** [comment]
Right now there is no other way to do it, but...

We are working on a new command-line implementation. We will try to introduce some output that will let to pipe outputs to commands.

**Comment by sourcedelica** [comment]
Check out [jq](https://stedolan.github.io/jq/)

**Comment by gsemet** [comment]
Sûre, but I am not sure it is installed on the machine. Anyway this ticket is intended especially NOT having to rely on jq for that.

I use the python package jello, at least if Conan is installed, I am sure a pure python code can work in every environment of my CI.

**Comment by AbrilRBS** [comment]
Closing as solved in v2. The [pkglist](https://docs.conan.io/2/examples/commands/pkglists.html) feature allows for exactly this usecase. Thanks a lot for your question! :)
