### ISSUE TITLE
[bug] deps_user_info empty when using new -pr:h/-pr:b parameters

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#7247]
I just noticed that when running conan install with the new `-pr:h`/`-pr:b` parameters the `deps_user_info` is completely empty although there should be several items inside which are set by direct requirements and build requirement packages. Once I roll back to `-pr` only it works as intended.

**Comment by memsharded** [comment]
The code in ``installer.py`` is:

```python
            if not using_build_profile:  # Do not touch anything
                conan_file.deps_user_info[n.ref.name] = n.conanfile.user_info
                conan_file.deps_cpp_info.update(n.conanfile._conan_dep_cpp_info, n.ref.name)
                conan_file.deps_env_info.update(n.conanfile.env_info, n.ref.name)
            else:
                if n in transitive or n in br_host:
                    conan_file.deps_cpp_info.update(n.conanfile._conan_dep_cpp_info, n.ref.name)
                else:
                    env_info = EnvInfo()
                    env_info._values_ = n.conanfile.env_info._values_.copy()
                    # Add cpp_info.bin_paths/lib_paths to env_info (it is needed for runtime)
                    env_info.DYLD_LIBRARY_PATH.extend(n.conanfile._conan_dep_cpp_info.lib_paths)
                    env_info.DYLD_LIBRARY_PATH.extend(n.conanfile._conan_dep_cpp_info.framework_paths)
                    env_info.LD_LIBRARY_PATH.extend(n.conanfile._conan_dep_cpp_info.lib_paths)
                    env_info.PATH.extend(n.conanfile._conan_dep_cpp_info.bin_paths)
                    conan_file.deps_env_info.update(env_info, n.ref.name)
```

So this is something that is missing with the new profile_build. Needs to be addressed, thanks for reporting.

**Comment by jgsogo** [comment]
Hi @jasal82 

This was a conscious decision. We really wanted to know what are people using this `user_info` for. The main problem is here is how to identify the `user_info` coming from the _build_ context and the one coming from the _host_ context because the same package can be present in both contexts (think about package `protobuf`: the library belongs to the _host_ context while the executable belongs to the _build_ context, both provide `user_info`...).

Can you share with us more information about your use-case?

I'm trying to gather all of it into this issue (https://github.com/conan-io/conan/issues/7120) so we can see the big picture and offer the best solution for all the scenarios.

Thanks!

**Comment by jasal82** [comment]
I'd suggest to announce important changes like this in the changelog before users stumble across it. I was under the impression that the new host/build profile model is an already stable feature and now it turns out it is not. This breaks a lot of things here and I have to roll out workarounds now.

Anyway, our first use-case for `user_info` is as follows:

- We have several components that expose a manifest (XML file)
- The manifest is packaged alongside the binary artifacts for each component
- The attribute `user_info.manifest_file` is set to the path of the manifest file
- Consumer builds must merge manifests of components to create an overall manifest
- This is done in a separate python script because developers must be able to run it outside of the Conan build process
- In order to find the components with a manifest and the manifest itself the python script parses conanbuildinfo.json, traverses the `deps_user_info` and looks for the `manifest_file` attribute

Another use-case, related to the one above:

- The merge tool for merging the manifests is written in Java and distributed as standalone JAR
- In order to resolve the correct version of that tool we repackage it as Conan package and set it as build requirement in the consumer
- For the consumer to be able to find the JAR file and execute it a `user_info` attribute is used to store the path to the JAR file in the package folder

**Comment by jasal82** [comment]
Why not simply generate two different trees of `user_info`, one for the host and one for the build context? That's better than not generating anything. The interface is broken anyway.

**Comment by jasal82** [comment]
And we need at least an intermediate fix in the next minor release, otherwise we're doomed because the host/build profile model is now already rolled out to all of our components. This cannot wait until 2.0!

**Comment by jgsogo** [comment]
No, this is not something that should wait for 2.0, but `1.27` is almost complete and we need to start merging the PRs that are already opened and there are still some issues pending. For sure this is something for the 1.x series, but we need to think a little bit more about it.

We need to decide if every build-requires expands an isolated graph or not (I'm not really sure if dependencies from different build-requires should conflict or not), based on that there will be a `user_info` tree for the _host_ context and another for the _build_ context, or each build-requires should have its own:

```python
class Recipe:
    build_requires = "pkgA/...", "pkgB/..."

    def build(self):
        # Information from the host context tree:
        self.deps_cpps_info
        self.deps_user_info
        self.deps_env_info  # also the environment from build-requires? all the environment? only the PATH related one?

        # Information from the build context: per BR-graph? does it make sense to aggregate all the build-requires together?
        self.build_cpp_info["pkgA"]  # needed or just for completness?
        self.build_user_info["pkgA"]  # Probably needed
        self.build_env_info["pkgA"]  # needed or just for completness?
```

**Comment by jgsogo** [comment]
Hi, @jasal82 

We've merged PR https://github.com/conan-io/conan/pull/7266 for the next 1.27 (to be released this week). It adds the information from the `user_info` requirements in the _host_ context to `deps_user_info` (as it is done when using one profile), and the information from the build_requirements will be available in the field `user_info_build`.

I hope this helps with your integration.

Thanks!

**Comment by jasal82** [comment]
@jgsogo  It seems that the new `user_info_build` data is unfortunately not included in the `conanbuildinfo.json` which is where we are trying to read it from in our auxiliary build scripts... Do we need a new issue for that?

**Comment by jasal82** [comment]
@jgsogo @memsharded This should be reopened. I'm trying with Conan 1.28.0 and there's no `self.user_info_build` available in the `build()` method of the consumer project. It's also not in the generated build info files as I've already mentioned above. I cannot fix our manifest and documentation toolchain when these attributes are not forwarded.

**Comment by jgsogo** [comment]
Hi! The member `user_info_build` will be available only if there is a build-require for the `build` context and you are providing two profiles to Conan. We added this test to the codebase which should reproduce that behavior: https://github.com/conan-io/conan/blob/develop/conans/test/functional/cross_building/user_info_test.py

How is yours different?

**Comment by jasal82** [comment]
It's the same. Except for the requires method. We're using the attribute instead of the `build_requirements()` function. Checking with the other method.

**Comment by jasal82** [comment]
Doesn't help. I don't understand it.

**Comment by jasal82** [comment]
@jgsogo I found the issue. It's working only in the create workflow. When I run install/build separately the `user_info_build` member is not there.

**Comment by jgsogo** [comment]
> @jgsogo I found the issue. It's working only in the create workflow. When I run install/build separately the `user_info_build` member is not there.

I'm going to check and reproduce it with a test. Thanks for the investigation!

**Comment by jgsogo** [comment]
I'm reproducing it here (https://github.com/conan-io/conan/pull/7488), probably deserves having a look to your other issue too (https://github.com/conan-io/conan/issues/7448) in this same PR

**Comment by jasal82** [comment]
Just verified that it's not a follow-up error. The `user_info_build` is not in the generated json even when using the create workflow.

**Comment by jgsogo** [comment]
https://github.com/conan-io/conan/pull/7488 merged, it fixes the `user_info_build` propagation for the local development commands (conan v1.28.1)
