### ISSUE TITLE
[question] Using different versions of packages in build_requires as settings in conanfile.py

### ISSUE THREAD

**Issue by craigaiken** [conan-io/conan#7255]
We use a thirdparty tool for generating code (basically an IDL compiler) that I've created a devtool conan package for.  This tool does get updated somewhat frequently.  Now in our code for pulling in the tool, I've defined something like this:

```
class FooConan(Conanfile):
   ...
   ...
   build_requires[("tool/1.2.3")]
```
But really I'd like to have that tool as one of the settings in the package, so that I can rebuild the package without changing the recipe.  Something like:

```
class FooConan(Conanfile):
   ...
   ...
   settings = "os", "compiler", "build_type", "arch", "tool_version"
   build_requires[("tool/<tool_version>")]
```

I have a lot of packages that will use this tool, and I don't want to have to bump the tool version for every package each time I update the tool.  I'd prefer to just update the build setting.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @craigaiken 

You can write:

```python
class Recipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch", "tool_version"

    def build_requirements(self):
        self.build_requires("tool/{}".format(self.settings.tool_version))
```
