### ISSUE TITLE
[feature] Support for new OSX arm binaries

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#7256]
Thanks to @jcar87

Env:
```
DEVELOPER_DIR=/path/to/Xcode12.0.app
MACOSX_DEPLOYMENT_TARGET=11.0
CMAKE_OSX_ARCHITECTURES=arm64
SDKROOT=/path/to/Xcode12.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
```

In settings.yml:
- add Macos version 11.0
- add apple-clang version 12.0
- Use ``armv8`` as arch

Pass ``-arch arm64`` to the compiler.
If cmake scripts evaluate CMAKE_SYSTEM_PROCESSOR, it is necessary to define it in toolchain, otherwise it thinks it is Intel.

https://gitlab.kitware.com/cmake/cmake/-/issues/20863

**Comment by AbrilRBS** [comment]
Closing as solved - this has been supported for a while now
