### ISSUE TITLE
[bug] dependency  version incompatibilities | venv

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#7265]
### Environment Details (include every applicable attribute)
  * Operating System+version: W10 WLS2 with 4.19.104-microsoft-standard SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux | Kali Linux container
  * Compiler+version: n/a
  * Conan version: 1.26.1
  * Python version: 3.8.3

### Steps to reproduce (Include if Applicable)
update below dependencies via `pip3 install -U`

### Logs (Executed commands with output) (Include/Attach if Applicable)

**ERROR: conan 1.26.1 has requirement deprecation<2.1,>=2.0, but you'll have deprecation 2.1.0 which is incompatible.
ERROR: conan 1.26.1 has requirement distro<1.2.0,>=1.0.2, but you'll have distro 1.5.0 which is incompatible.
ERROR: conan 1.26.1 has requirement node-semver==0.6.1, but you'll have node-semver 0.8.0 which is incompatible.
ERROR: conan 1.26.1 has requirement pluginbase<1.0,>=0.5, but you'll have pluginbase 1.0.0 which is incompatible.
ERROR: conan 1.26.1 has requirement six<=1.14.0,>=1.10.0, but you'll have six 1.15.0 which is incompatible.**
___
Alternatively tried the `venv` approach but contrary to https://docs.python.org/3/library/venv.html#creating-virtual-environments

>all scripts installed in a virtual environment should be runnable without activating it, and run with the virtual environment’s Python automatically.

that is not working since *conan* gets installed into the `venv` path that is unknown to the OS's known binary paths.
___
Wondering whether those printed errors are merely cosmetic or whether *conan* is indeed incompatible with those updated dependencies?

**Comment by memsharded** [comment]
Yes, some of those dependencies are indeed incompatible. As a quick example ``node-semver=0.8.0`` is changing the behavior, so it would be changing how Conan version ranges are evaluated and would be breaking for some Conan users.

We should have a look to the venv path. Even if Conan still runs with Python 2.7 (needs virtualenvwrapper) we should be compliant with venv recommended practices.

**Comment by ghost** [comment]
There is likely nothing wrong with *conan*'s venv path since it container the “shebang” line which points to the virtual environment’s Python interpreter.

The issue is rather that `python3 -m venv` does not add the `venv` path variable to PATH and PATHEXT variables for the Python installation. Maybe that expectation is a misconception on my part or a bug in py.
