### ISSUE TITLE
[feature] Allow setting description and URL dynamically

### ISSUE THREAD

**Issue by wdobbe** [conan-io/conan#7268]
Issue #5881 made it possible to set the package name and version after they are read from for example an external file.

In our company we use this to prevent that we have to specify the project name and version in both the CMakeLists.txt and the conanfile.py. I created a ConanFile derived class that reads this information from the 'project()' cmake command (see https://github.com/wdobbe/conan-extra/tree/master/cmake_conan).

The cmake project() command also allows to specify the description and URL. They are then used as default for for example the (RPM) package metadata fields.
Although not super important, it would be nice if the ConanFile class also had set_description() and set_url() functions, analog to the set_name() and set_version() functions. This would prevent that we have to specify the description and URL in both the cmake and conan files.

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! This is an interesting feature request, not only for the `description` or `URL` but also for other fields like the `license`. In the case of the license there are packages that have different licenses depending on an option (activating some GPL modules, commercial or not like Qt,...) and assigning the proper value in some initialization step would be really useful.

Up to know this is something that can be done in the `configure()` function, where Conan already has populated the proper options, there you can assign values to your fields: 

```python
def configure(self):
    data = read_data_from_somewhere(...)
    self.description = data["description"]
    self.url = data["URL"]
    self.license = "GPL" if self.options.gpl else "MIT"
````

I haven't tried it myself, but it should work. But we need to think if there is a better way to do this kind of initialization, if we want to provide a dedicated function,... and confirm it works with commands like `conan info ...`.

**Comment by wdobbe** [comment]
Hi Javier,

Thanks for that tip. It is indeed possible to set the description, url and homepage attributes from the configure  function.
Previously I tried to do that from the setname() function, but that doesn't work.

However I encounter a problem with that solution:

I read the CMakeLists.txt with command 
`tools.load(os.path.join(self.recipe_folder, "CMakeLists.txt"))`. 
However in the configure function, the recipe_folder attribute doesn't exist yet:
`AttributeError: 'EtsiTS103097Conan' object has no attribute 'recipe_folder'`

Note: as described in the issue description, I created a ConanFile derived class CMakeConanFile. If I add a configure function to that class and the actual recipe has a configure() function itself, the configure function of CMakeConanFile is not called anymore. You have to remember to call the parent class configure() function with:
`super(<class name>, self).configure()`

**Comment by jgsogo** [comment]
> 
> I read the CMakeLists.txt with command
> `tools.load(os.path.join(self.recipe_folder, "CMakeLists.txt"))`.
> However in the configure function, the recipe_folder attribute doesn't exist yet:
> `AttributeError: 'EtsiTS103097Conan' object has no attribute 'recipe_folder'`
> 

Yes, this is most likely the issue with this feature request. Unless the file you are reading is side by side with the recipe it can be challenging and might stop working if it is not documented behavior. Another alternative you can consider is to use the `conandata.yml` to store that information and then pass that info from Conan to CMake. 

> Note: as described in the issue description, I created a ConanFile derived class CMakeConanFile. If I add a configure function to that class and the actual recipe has a configure() function itself, the configure function of CMakeConanFile is not called anymore. You have to remember to call the parent class configure() function with:
> `super(<class name>, self).configure()`

Calling `super` when you inherit from another class and want to add more statements to a function is very common in Python. I understand it is something else to remember, but it is how the language work and I think we shouldn't propose a different behavior. The only alternative that would require doing nothing is adding that info to the `conandata.yml`, that file is loaded by default and the data can be retrieved in the attribute `self.conan_data`

**Comment by wdobbe** [comment]
> Unless the file you are reading is side by side with the recipe it can be challenging and might stop working if it is not documented behavior.

Actually the CMakeLists.txt is in the same directory as the conanfile.py. But still I cannot read it without supplying the recipe folder path:
```
self._content = tools.load("CMakeLists.txt")
        FileNotFoundError: [Errno 2] No such file or directory: 'CMakeLists.txt'
```

> Calling super when you inherit from another class and want to add more statements to a function is very common in Python. I understand it is something else to remember, but it is how the language work and I think we shouldn't propose a different behavior. 

No problem, calling the parent class configure() function is fine for me. The advantage of the set_name() and set_version() functions is that they work 'invisible' even to derived classes. So instead of several set_xxxx() functions maybe we could have a set_metadata() function where you can set self.description and other metadata attributes.

**Comment by jgsogo** [comment]
For the usage you want (you don't need settings or options there) the [function `init()`](https://docs.conan.io/en/latest/reference/conanfile/methods.html#init) can be the best candidate. For other attributes that might require options values (like the `license` example) we need something else.

If you want to read the `CMakeLists.txt` from the recipe file, you need to export it together with the recipe (attribute `exports`) not only as source code. The recipe doesn't retrieve the sources if the binary is available.

**Comment by memsharded** [comment]
``self.recipe_folder`` will be available in Conan 1.28 (#7314 merged)

#7404 propose the ``init()`` method (adding tests) for the requested feature.

**Comment by memsharded** [comment]
Merged. We will add docs in Conan 1.28 to suggest the ``init()`` method for unconditional values (available at ``conan inspect``) and ``configure()`` for conditional values (not available at ``conan inspect``, necessary evaluation with ``conan info``)

**Comment by wdobbe** [comment]
Thank you!
