### ISSUE TITLE
[bug] custom generator usable from conanfile.txt but not conanfile.py

### ISSUE THREAD

**Issue by LeonFretter** [conan-io/conan#7274]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Conan version: 1.25.2 **edit:** still applicable in version 1.26.1
  * Python version: 3.6.9

### Steps to reproduce
* Load a custom generator into your conan-cache.
* Create a **conanfile.txt** with the custom generator included like this:
```
[generators]
<CustomGeneratorNameHere>
```
 under attribute `[generators]`
-> on calling install, the generator is used (as expected)
* Create a **conanfile.py** and inside the class that extends from ConanFile, include the custom generator like this:
```
generators = "<CustomGeneratorNameHere>"
```
-> on calling install, the following error-message is generated:

> ERROR: Invalid generator 'CustomGeneratorNameHere'. Available types: txt, gcc, compiler_args, cmake, cmake_multi, cmake_paths, cmake_find_package, cmake_find_package_multi, qmake, qbs, scons, visual_studio, visual_studio_multi, visual_studio_legacy, xcode, ycm, virtualenv, virtualenv_python, virtualbuildenv, virtualrunenv, boost-build, pkg_config, json, b2, premake, make, deploy, markdown

(only the default generators are listed, and the custom generator is not resolved.)

**Comment by LeonFretter** [comment]
sorry, guys, in my **conanfile.py** i forgot to require the package that contains the custom generator.

**Comment by memsharded** [comment]
Hi @LeonFretter 

No problem, thanks for following up and letting us know. Happy you found the issue!
