### ISSUE TITLE
Meson in all the nodes of the CI

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#7275]
If we want to start testing some integration with Meson, we need to add the application to the CI nodes. We don't install `meson` in our release tests (https://github.com/conan-io/test), and it is not available in the venv.

**This issue should be closed only after some tests actually use Meson application.** https://github.com/conan-io/conan/pull/7273

Need for https://github.com/conan-io/conan/pull/7155

**Comment by AbrilRBS** [comment]
Closing, has been available for a while now
