### ISSUE TITLE
[question] ERROR: Build-require 'b2' cannot be found in lockfile

### ISSUE THREAD

**Issue by AndreasHK** [conan-io/conan#7279]
I am currently transitioning our build scripts from _conan info --build-order_ to the recommended _conan graph build-order_ and experience issues with build_requires. I have a couple of libraries and some of them depend on boost. And boost has a [build_require set to b2](https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py#L143).

In my minimal [conan-recipe](https://github.com/conan-io/conan/files/4850404/conanfile.txt) I require boost with certain settings (the same as in the real consumer conan recipe).

I create a lockfile via (supplying all profiles, see attached [bo.txt](https://github.com/conan-io/conan/files/4850406/bo.txt))
`conan graph lock -s arch=x86 bo.lock version/Base/conanfile.py`

which works fine, but when I try to get the build-order via
`conan graph build-order bo.lock --build --json=bo.json`
it fails with the error-message: 
**ERROR: Build-require 'b2' cannot be found in lockfile**

Using `conan info --build-order ALL -s arch=x86 version/Base/conanfile.py` complains that is deprecated, but deliveres the expected result.
```
conan info --build-order ALL -s arch=x86 version/Base/conanfile.py
WARN: Usage of '--build-order' argument is deprecated and can return wrong results. Use 'conan graph build-order ...' instead.`
[b2/4.2.0], [boost/1.73.0]
```
**Conan-Version** I use is **1.25.1** and I am working within the Debian WSL.

Is this a known limitation or am I missing something?

**Comment by memsharded** [comment]
The next iteration of lockfiles in https://github.com/conan-io/conan/pull/7243 will be improving this (it won't be necessary to specify the --build in ``build-order``)

It is necessary to pass ``--build`` at the ``conan graph lock`` command, otherwise, the lockfile will not contain the build requires.

**Comment by AndreasHK** [comment]
@memsharded Thank you for your fast reply, this resolves my question.

**Comment by memsharded** [comment]
Ok, then I think we can close this question.

Please stay tuned for Conan 1.28 (not this week release, but next month), that will include some great improvements for lockfiles, hopefully they will make the feature more powerful and also easier to understand the behaviors.
