### ISSUE TITLE
Toolchain next steps

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#7280]
Toolchain was introduced, but still very early stage. Need to keep working on them. Some important points to be addressed:

For Conan 1.28:

- After https://github.com/conan-io/conan/pull/7160, check if all variables don't need to be defined in the CMake cache, as the toolchain is loaded every time

- Do a first iteration over the MSBuild and Makefiles toolchains

For later release:

- After the learnings of the MSBuild and Makefiles initial work, discuss about what to do with the environment.

**Comment by Minimonium** [comment]
Related to #5737

**Comment by memsharded** [comment]
Progress on toolchains until 1.32

Added CMake, MSBuild, Make and Meson experimental toolchains

Need to keep working in:

- Cross-building scenarios: Androd, iOS
- Using different build systems: Ninja, MinGW
- Custom configurations: ReleaseShared, etc
- User extensibility
- User interface, what things can be configured.
- Consider injection of generic CXXFLAGS?

**Comment by SSE4** [comment]
how about unification of toolchain and build helpers interfaces?
right now they are completely independent classes, but more or less interface is the same.
e.g. build helper usually provides:
- configure
- build
- install
- test

and toolchain usually provides:
- generate / write_toolchain_files

**Comment by memsharded** [comment]
To clarify @SSE4 

- Toolchain are classes oriented to generate files that support the command line invocation by users, and that can be passed to the build system, e.g: ``-DCMAKE_TOOLCHAIN_FILE=conantoolchain.cmake``. These shouldn't have configure(), build() or anything like that.

- Build helpers will be pure command line wrappers, with as little logic as possible, just a mapping from python calls to cli. This will have the configure(), build(), etc, as long as the build system support those command line commands

That is, they have different goals, different logic, different purpose. A consumer only might not need at all the build helper, and only the toolchain. I see no benefit of unifying them, they will be low cohesion. They are also used in different methods in most cases.

**Comment by SSE4** [comment]
> To clarify @SSE4
> 

probably there is misunderstanding :) I mean unify build helpers such as Meson, MSBuild, CMake to inherit from the IBuildHelper. same for MesonToolchain, MSBuildToolchain and CMakeToolchain to inherit from IToolchain. I don't propose to unify build helpers with toolchains.

**Comment by memsharded** [comment]
> probably there is misunderstanding :) I mean unify build helpers such as Meson, MSBuild, CMake to inherit from the IBuildHelper. same for MesonToolchain, MSBuildToolchain and CMakeToolchain to inherit from IToolchain. I don't propose to unify build helpers with toolchains.

I don't think so. Speculative inheritance, I don't see any value, build helpers are greatly simplified when using toolchains.

**Comment by memsharded** [comment]
Toolchains are moving forward, I think we no longer need this general issue, but specific ones that can be directly assigned and implemented.
