### ISSUE TITLE
[feature] push (simulated via polling?) of config updates

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#7282]
It is frequently a problem in our corporate environment that conan config settings change, for example recently our internal Artifactory admins changed the URLs we should use to find our internal repos.

Our team of 50 developers all used:

```
conan config install git@<internalrepo>/conan_common_config_install.git --type git
```

To get their settings.

It would be very helpful if conan would remember the last conan config install location, and from time to time (e.g. every 20th interactive conan invocation)  check the previous location for updates, and log a suggestion e.g. at log level WARN.

```
WARNING: Config changes noted, run `conan config install git@<internalrepo>/conan_common_config_install.git --type git` to refresh.
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @michaelmaguire 

Both are already available features:

- Conan memorize the previous ``conan config install`` commands, so calling ``conan config install`` without arguments will call in order the list of previous installs.

- There is a new ``conan config install`` auto-update feature, that will call this command (without arguments) periodically. Given that the configuration for this feature is also in ``conan.conf``, the first ``conan config install`` with args can also schedule a given interval for auto-updates. Check https://docs.conan.io/en/latest/reference/config_files/conan.conf.html (``config_install_interval``)

**Comment by michaelmaguire** [comment]
Wow, that's psychic levels of service!  Awesome.  Thanks.

**Comment by memsharded** [comment]
And today 1.27 release will include ``conan.conf`` configuration to validate also the current running Conan client version, so it is possible to force developers to update their clients :)

**Comment by michaelmaguire** [comment]
I think I just ran into a bug with this.

I've raised it as: https://github.com/conan-io/conan/issues/7297 "[bug] Automated config update exception needed for conan config install commands to prevent catch-22"
