### ISSUE TITLE
[question] is it possible to override user selected profile in conanfile.py?

### ISSUE THREAD

**Issue by IvanRomanovski** [conan-io/conan#7288]
I am cross building a library which generates config header file "config.h" by executing Autotools configure. The issue is that I am trying to cross compile to Emscripten (https://docs.conan.io/en/latest/integrations/cross_platform/emscripten.html) and one of the tests configure script performs is whether compiler can create executables, which Emscripten cannot. 

Is is possible to perform Autotools configure below using default profile instead of Emscripten profile?

```
def build(self):
    autotools = AutoToolsBuildEnvironment(self)
    with tools.chdir(self._source_subfolder):
        with tools.environment_append(autotools.vars):
            self.run("./autogen.sh")
            autotools.configure()
    cmake = CMake(self)
    cmake.verbose = True
    cmake.configure()
    cmake.build()
```

**Comment by memsharded** [comment]
Hi @IvanRomanovski 

It is not clear the problem you are trying to solve. Why not providing the profile that you want with the configuration you want in the command line with ``--profile=myemscriptenprofile``? If you are building for Emscripten you should be passing a Emscripten profile? Please let us know a bit more (there are some people like @theodelrieu or @jgsogo that might help with emscripten issues)

**Comment by IvanRomanovski** [comment]
@memsharded Thank you for your quick reply. In retrospect it wasn't a good question (and wrong approach). Sorry.
