### ISSUE TITLE
[bug] same build requirement added twice to the lockfile

### ISSUE THREAD

**Issue by sduerr** [conan-io/conan#7290]
Build requirements are duplicated in lockfiles, if multiple packages in the graph depend on them. Furthermore, the build profile is not applied when installing a packages referencing a lockfile.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04.4 LTS
  * Compiler+version: gcc-linaro
  * Conan version: 1.26.1
  * Python version: 3.7

#### Initial situation
- We have pkgA, pkgB, which are simple CMake libraries
- pkgA requires pkgB
- There is a gcc-linaro package containing a cross compiler for ARMv8. As the compiler only runs on Linux, the settings are restricted to `os=Linux, arch=x86_64`
- There is a build_profile which sets `os=Linux, arch = x86_64`
- There is a host_profile with:
```
[settings]
os=Linux
arch=armv8
compiler=gcc
compiler.version=7.5
compiler.libcxx=libstdc++11
build_type=Release

[build_requires]
gcc-linaro/7.3-2018.05@user/channel
```

Then, I did the following steps:
1. export all recipes to conan cache (`conan export ... user/channel`)
2. install dependencies of recipeA (`conan install recipeA/conanfile.py user/channel --build=missing -pr:h profile_host -pr:b profile_build`)
3. create packageA (`conan install recipeA/0.1@user/channel --lockfile`

#### Outcome
step 2 creates a lockfile, in which there is (simplified):
```
0 -> pkgA
    requires: 1
    build-requires: 3
1 -> pkgB
   build_requires: 2
2 -> gcc-linaro/0.1@user/channel#rrev:pkgID#prev
3 -> gcc-linaro/0.1@user/channel#rrev:pkgID
```
Why does gcc-linaro appear twice in the lockfile? Shouldn't conan detect that they are the same (the rrev and pkgID are the same)?

Step 3 fails with the error:
```
ERROR: Error while initializing settings. Invalid setting 'armv8' is not a valid 'settings.arch' value.
Possible values are ['x86_64']
```
Conan tries to build gcc-linaro again (due to the duplicate entry in the lockfile), and doesn't apply the build profile any more.

**Comment by memsharded** [comment]
Thanks for reporting this issue @sduerr 

We are working right now in some improvements to the lockfiles in https://github.com/conan-io/conan/pull/7243, next iteration (1.28) will most likely include fixes for this.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/7243 is proposing a whole new approach and command line for lockfiles for Conan 1.28. 

Now when a package with a given ID is built, all the other repeated nodes in the graph with same ``package_id`` are updated, so this should fix your issue. Please keep tuned to the release and documentation updates, and let us know if it works.
