### ISSUE TITLE
[question] compiler.libcxx value with musl's libc.so?

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#7298]
- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Maybe I missed it in the [documentation](https://docs.conan.io/en/latest/reference/config_files/settings.yml.html?highlight=compiler%20libcxxettings.yml.html?highlight=compiler%20libcxx#c-standard-libraries-aka-compiler-libcxx)  but could not find a reference  whether/how `compiler.libcxx` would support musl's libc.so, e.g. something like:

*  `compiler.libcxx = libc`, or
*  `compiler.libcxx = musl`

?

**Comment by jgsogo** [comment]
Hi @n8v8R ! 

Conan settings are like coordinates to locate packages, the settings in `settings.yml` are the framework where concrete values provided in the profiles or command line must fit. Those concrete values are translated into actual compiler and linker flags by the build helpers.

Currently, Conan default configuration doesn't allow (neither understand) a value `musl` for the setting `compiler.libcxx`. You can add it yourself to your `settings.yml` file and Conan will learn that new coordinate, will compute the package-id of your packages taking into account that value... BUT, it doesn't mean that a built-in build_helper will understand that new value (probably they will raise an error saying that `musl` is not a valid/expected value for that coordinate). We would need to implement this behavior in the build_helpers or you would need to provide the build_helper yourself to the recipes or use plain calls to the compiler/linker:

```python
from conans import CMake  ##! This build_helper doesn't know how to translate 'musl'

class YourRecipe(ConanFile):
    def build(self):
        # cmake = CMake(self)
        # cmake.configure()  ##!! built-in build helper doesn't understand 'compiler.libcxx=musl'
        self.run("cmake <path/to/CMakeListst.txt> -G <generator> -D.... all-cli-definitions", run_environment=True)
        self.run("cmake --build .")
```

Another approach would be to package the musl-gcc (like any other compiler), use it as a build_requires and provide settings accordingly. I'm thinking it should be that hard, I'm surprised noone has submitted that recipe to [ConanCenter](https://github.com/conan-io/conan-center-index/tree/master/recipes) yet.

**Comment by ghost** [comment]
Thank you for the extensive feedback, though surprising that *conan* does not support musl's libc natively.
