### ISSUE TITLE
[question] Override settings for specific dependencies in recipe

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7308]
I am integrating libraries from a 3rd-party supplier into an app and want to share the binaries with them to support their own debugging.  To protect some sensitive IP, I want to only pull the `build_type=Release` packages for some of our internal requirements to prevent the debug symbols being visible in the final binary.

I know this is currently possible in [profiles](https://docs.conan.io/en/latest/reference/profiles.html#package-settings-and-env-vars), but I'd like to have an option for this type of package (e.g. `options = {"supplier": [True, False]}`) and so I think I need to be able to set it in the recipe.  Is there currently any way to do this?

**Comment by memsharded** [comment]
Hi @GordonJess 

I am afraid it is not possible. One package cannot set the settings values of its dependencies. It shouldn't even define its own values. Settings values need to come always from a profile or command line.

We know from the experience with the ``options``, that recipes defining the options of their dependencies is a complicated thing (just in case you were asking for this, it is possible to do this, in ``default_options = {"mydep:option": "value"}``, that causes lots of issues, conflicts, etc. that are quite difficult to debug and understand what is happening.

I am not sure if I fully understood the approach, so I would like to make sure: Are you providing your supplier with a Conan repository with Conan packages, so they can do a ``conan install`` from it? In that case, you should provide them with a set of profiles with the available configurations anyway, so it shouldn't be an issue to define that in the profiles.

**Comment by DukeOfKirkcaldy** [comment]
Currently suppliers find packages through `buildInfo` links in Jenkins, and they download them directly from the artifactory web UI.

The reason I was looking for an `options` solution is that we also need this same package to be built with all debug symbols for our own internal debugging:

`-o supplier=True`  (no debug symbols for internal libraries)
`-o supplier=False`  (all debug symbols)

and I'd have liked to been able to easily distinguish between the two when searching, installing, etc. from the conan client.  It doesn't seem possible to search with a certain profile.  Using separate profiles, like so:

_profiles/default_
```
[settings]
build_type=Debug
```

_profiles/supplier_
```
[settings]
build_type=Debug
*@my_company/*:build_type=Release

```

the only way I can see for me to later find these 'supplier' packages is to trace through the CI logs to see which `packageID` was produced from the 'supplier' profile.

**Comment by memsharded** [comment]
Hi @DukeOfKirkcaldy 

I am closing this ticket as outdated/solved.

Conan 2 has added many things that seems to solve this issue.
For example it is possible to list existing packages with ``conan list`` and provide profile/settings arguments to the command to list those matching a specific configuration. And of course all ``conan install/graph/create/lock`` operations admit profiles too as inputs.

Please open new tickets for any further question or issues, many thanks for your feedback.
