### ISSUE TITLE
[feature] Fetch host information in build_requires recipes

### ISSUE THREAD

**Issue by akemimadoka** [conan-io/conan#7317]
build_requires recipes which setting up the building environment should be able to fetch host information.

Like https://github.com/bincrafters/conan-android_ndk_installer, if use command like

> conan install zlib/1.2.11@\_/\_ -pr:b=default -pr:h=android --build missing

profile "android" is

> [settings]
> os=Android
> os.api_level=26
> os_build=Linux
> arch=armv8
> arch_build=x86_64
> compiler=clang
> compiler.version=9
> compiler.libcxx=c++_static
> build_type=Release
> [options]
> [build_requires]
> android_ndk_installer/r21d@bincrafters/stable
> [env]

I got:

> ERROR: Error while initializing settings. Invalid setting 'Linux' is not a valid 'settings.os' value.
> Possible values are ['Android']
> Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @akemimadoka .

This is an issue with the recipe you are linking, not with Conan itself. That recipe declares that the only valid value for `os` is `Android`, and you have Linux in your profile for the _build_ context (`-pr:b=default`).

I have to say that your understanding of how to use the two profiles is good, and adding the build_requires to the _host_ profile is definitively the way to go,... but you/bincrafters need to fix that recipe. I recommend to open an issue in the repo of that recipe, but also to request this package in [conan-center-index](https://github.com/conan-io/conan-center-index/issues), hopefully someone has the time to migrate that recipe to the new ConanCenter.

Thanks!

**Comment by akemimadoka** [comment]
Thank you! I think the key is android_ndk_installer cannot get information of host, because it's a build requirement, not only the fault of the recipe. So I'm thinking whether here is a mechanism to make a build requirement have ability to get host information or not.

**Comment by jgsogo** [comment]
What information do you need in the _build_ context from the _host_ environment?

**Comment by akemimadoka** [comment]
Like settings.os.api_level, and settings.compiler.libcxx, they are provided as build profile.

**Comment by jgsogo** [comment]
Via `self.settings_target` from the recipes that are build_requires of the _host_ context you can get the settings you are using in the _host_ context.

**Comment by akemimadoka** [comment]
Thank you!
