### ISSUE TITLE
[feature] Recipe settings populated by default

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#7318]
It looks like most recipes (if not everyone) are finally adding all the first-level settings to the `settings` declaration inside the conanfile: header-only topically need it (https://github.com/conan-io/conan-center-index/issues/1957) at least to check the C++ standard, _installers_ need them as long as they need to be compiled,... 

The default for a ConanFile would be to take all the first-level settings (default `settings.yml` for Conan will likely contain only `os`, `arch`, `compiler` and `build_type`,... all the others, cppstd, xxx_target, yyy_build should be deprecated) and, if a recipe doesn't need them (because it is downloading already available binaries) it has to declare explicitly the list of settings to use.

What if the user has a `settings.yml` file that adds an extra first-level setting? It will be added automatically to the recipe too... probably it is the reason why the user is adding that new setting at the first level, to take it always into account. With this new approach no modification to existing recipes would be needed... unless the intention is not to add the new setting to old recipes (the main problem is that they will compute a missing package-id)

**Comment by Minimonium** [comment]
> What if the user has a settings.yml file that adds an extra first-level setting? It will be added automatically to the recipe too...

The issue with automatic addition of top-level settings is that existing recipes don't know how to remove these from the package_id? Is it even an issue if we can say that, generally, a top-level setting will _always_ produce a separate hash for external recipes?

**Comment by memsharded** [comment]
I am afraid this is not happening, this doesn't have a clear migration path from 1.X->2.0. Closing.
