### ISSUE TITLE
graph --table=file.html does not show outdated packages

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#7328]
They were previously shown in colors. I guess adding a column "outdated" will resolve this issue.

**Comment by jgsogo** [comment]
It is only about adding it to the requested headers in this snippet, as documented here: https://docs.conan.io/en/latest/extending/template_system/search_table.html

```html
<thead>
    <tr>
        {%- set headers = results.get_headers(keys=['remote', 'package_id']) %}
        {%- for header in headers.row(n_rows=1) %}
        <th>{{ header }}</th>
        {%- endfor %}
    </tr>
</thead>
```

Users can add their own template if they want to.
