### ISSUE TITLE
[bug] Conan install failed.

### ISSUE THREAD

**Issue by artzers** [conan-io/conan#7329]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: VS 2017
  * Conan version: 1.27.0
  * Python version: python 3.7.3

### Steps to reproduce (Include if Applicable)
I want to install debug and release version of hdf5.
1. I deleted the hdf5 package in conan package directory and run "conan install hdf5/1.12.0/@ -r=conan-center -s build_type=Debug -s Pkg:build_type=Release" but failed, showing "ERROR: Conanfile not found at D:\C++\conan-test\hdf5\1.12.0".

2. Then I run "conan search hdf5 -r=conan-center", showing:
Existing package recipes:
hdf5/1.8.21
hdf5/1.10.5
hdf5/1.10.6
hdf5/1.12.0

And I run "conan install hdf5/1.12.0/@ -r=conan-center". The same error ocurred "ERROR: Conanfile not found at D:\C++\conan-test\hdf5\1.12.0".

3. I have re-installed conan and removed the configuration directory ".conan". But now I cannot install any packages, all showing "ERROR: Conanfile not found at ...". The installation command is "conan install [package] -r=conan-center". For example,  "conan install libsvm/324/@ --remote=conan-center" and "conan install libsvm/324/ --remote=conan-center"

**Comment by uilianries** [comment]
Hi @artzers !

There is a little typo in your command, the correct package reference is `hdf5/1.12.0@`. There are extra slashes in your command.

Please, take a look on the [getting started](https://docs.conan.io/en/latest/getting_started.html) documentation for further reference.

**Comment by artzers** [comment]
@uilianries  It's my carelessness. Thank you.

**Comment by memsharded** [comment]
> @uilianries It's my carelessness. Thank you.

Well, not that much your fault, there is some ambiguity in the CLI that doesn't help, and the error messages are not that evident. We have already started working in the new CLI for Conan 2.0, that will solve this issues.
