### ISSUE TITLE
[feature] Add components to 'pkg_config'  generator

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#7330]
This PR (https://github.com/conan-io/conan-center-index/pull/1782) is adding components to OpenSSL and overriding the name of those components for `pkg_config` generator:

```python
        self.cpp_info.components["crypto"].names["cmake_find_package"] = "Crypto"
        self.cpp_info.components["crypto"].names["cmake_find_package_multi"] = "Crypto"
        self.cpp_info.components["crypto"].names['pkg_config'] = 'libcrypto'
        self.cpp_info.components["ssl"].names["cmake_find_package"] = "SSL"
        self.cpp_info.components["ssl"].names["cmake_find_package_multi"] = "SSL"
        self.cpp_info.components["ssl"].names['pkg_config'] = 'libssl'
```

How do components work with `pkg_config`?

**Comment by SSE4** [comment]
IMO they should generate one pkg-config file per component

**Comment by jgsogo** [comment]
Taken from https://github.com/conan-io/conan-center-index/pull/1782#discussion_r451820928

```
./lib/pkgconfig/openssl.pc
./lib/pkgconfig/libssl.pc
./lib/pkgconfig/libcrypto.pc
```

https://fedora.pkgs.org/30/fedora-x86_64/openssl-devel-1.1.1b-3.fc30.x86_64.rpm.html
