### ISSUE TITLE
[bug] Misleading/wrong "--update" handling for conan graph lock

### ISSUE THREAD

**Issue by spoofedex** [conan-io/conan#7333]
Hi all,

It seems to me that the "conan graph lock" handles the "--update" parameter incorrectly; or, alternatively, that the documentation is misleading.

When running a "conan graph lock" with the "--update" parameters, the packages are not updated from the remote. If the local cache has an outdated version, and a remote has a later version (at least a later package revision, I'm not sure if this is true if the versions differ), then the resulting lockfile will still use the cached, older version. This does not match what I would expect from the documentation.

This is caused by conan_api.py, create_lock. Here, the "update" parameter is passed to load_graph's check_updates parameter, while load_graph's update parameter is always set to False. This results in ConanProxy's _get_recipe to trigger the code path with status RECIPE_UPDATEABLE, instead of RECIPE_UPDATED. Finally, this causes the lockfile to contain the older package revisions.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: N/A
  * Conan version: 1.25.2/1.27.0
  * Python version: 3.8.3

### Steps to reproduce (Include if Applicable)
 - Enable package revisions
 - Make a package A/1.0.0 depend on B/1.0.0, where B/1.0.0 is uploaded to a remote (artifactory)
 - Have a locally cached version of B/1.0.0
 - Change B/1.0.0 (keeping the version) and upload it to the remote (artifactory), without changing the local cache (e.g. on another system)
 - Run "conan graph lock A/1.0.0@\_/\_ --update --build missing --build outdated --build cascade --lockfile ."
 - Open the lockfile and see the version of B/1.0.0 being used; this is the version of the local cache, rather than the update from the remote

Best regards,
SpoofedEx

**Comment by TheQwertiest** [comment]
Related issue/possible duplicate: https://github.com/conan-io/conan/issues/7146

**Comment by memsharded** [comment]
Hi @spoofedex 

Thanks for reporting this and providing the necessary information to reproduce.

Confirmed there is a bug, it is not updating correctly. I have included a test and a fix in https://github.com/conan-io/conan/pull/7243, which is the next iteration of lockfiles intended for Conan 1.28, contains many other changes, but this will now be properly covered with tests.
