### ISSUE TITLE
[feature] add '-o' support for conan build

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7334]
sometimes, i think people want to build a package with different option defined in the recipe file without change the recipe file 

it would be useful to add support of `-o` for `conan build` just like `conan create` or `conan install`

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @shelper . This is intended, options cannot be modified after the `conan install`, they might be choosing which requirements are available, if you change them in `conan build` there can be missing requirements and things won't work.

**Comment by jgsogo** [comment]
Thanks! I'm closing the issue, but feel free to open it again or comment if you need further information.
