### ISSUE TITLE
[bug] ERROR: Recipe not found: 'boost_filesystem/1.69.0@bincrafters/stable'

### ISSUE THREAD

**Issue by KSBilodeau** [conan-io/conan#7340]
After accidentally terminating what I thought was an infinite loop of trying to find 'recipe revision 0' for boost_filesystem/1.69.0@bincrafters/stable, I have been unable to install boost_filesystem/1.69.0@bincrafters/stable.

### Environment Details (include every applicable attribute)
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

System Software Overview:
  System Version:	macOS 10.15.5 (19F101)
  Kernel Version:	Darwin 19.5.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	Keegan’s MacBook Pro
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled

System Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,2
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

### Steps to reproduce (Include if Applicable)
1) Attempt to install 'boost_filesystem/1.69.0@bincrafters/stable' through either conan install . or conan install boost_filesystem/1.69.0@bincrafters/stable
2) Terminate the installation prematurely using CTRL-C, twice I believe
3) Attempt the install once again

#### CONAN VERSION ####
 conan -v
Conan version 1.27.1

#### CONAN INSTALL . #####
conan install .
WARN: Migration: Updating settings.yml
Migration: Settings already up to date
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

WARN: sdl2_ttf/2.0.15@bincrafters/stable: requirement sdl2/2.0.9@bincrafters/stable overridden by your conanfile to sdl2/2.0.12@bincrafters/stable 
WARN: freetype/2.9.1@bincrafters/stable: requirement libpng/1.6.37@bincrafters/stable overridden by sdl2_ttf/2.0.15@bincrafters/stable to libpng/1.6.37 
WARN: freetype/2.9.1@bincrafters/stable: requirement zlib/1.2.11@conan/stable overridden by sdl2_ttf/2.0.15@bincrafters/stable to zlib/1.2.11 
WARN: freetype/2.9.1@bincrafters/stable: requirement bzip2/1.0.6@conan/stable overridden by sdl2_ttf/2.0.15@bincrafters/stable to bzip2/1.0.8 
WARN: sdl2_image/2.0.5@bincrafters/stable: requirement sdl2/2.0.10@bincrafters/stable overridden by your conanfile to sdl2/2.0.12@bincrafters/stable 
WARN: libtiff/4.0.9: requirement libjpeg/9d overridden by sdl2_image/2.0.5@bincrafters/stable to libjpeg/9c 
WARN: boost_cycle_group_c/1.69.0@bincrafters/stable: requirement bzip2/1.0.6@conan/stable overridden by your conanfile to bzip2/1.0.8 
WARN: boost_cycle_group_c/1.69.0@bincrafters/stable: requirement zlib/1.2.11@conan/stable overridden by your conanfile to zlib/1.2.11 
ERROR: Failed requirement 'boost_filesystem/1.69.0@bincrafters/stable' from 'boost_cycle_group_c/1.69.0@bincrafters/stable'
ERROR: Recipe not found: 'boost_filesystem/1.69.0@bincrafters/stable'

#### CONAN GET ####
conan get boost_filesystem/1.69.0@bincrafters/stable
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from conans import python_requires

base = python_requires("boost_base/1.69.0@bincrafters/stable")

class BoostFilesystemConan(base.BoostBaseConan):
    name = "boost_filesystem"
    version = "1.69.0"
    url = "https://github.com/bincrafters/conan-boost_filesystem"
    lib_short_names = ["filesystem"]
    options = {"shared": [True, False]}
    default_options = "shared=False"
    b2_requires = [
        "boost_assert",
        "boost_config",
        "boost_container_hash",
        "boost_core",
        "boost_detail",
        "boost_io",
        "boost_iterator",
        "boost_smart_ptr",
        "boost_static_assert",
        "boost_system",
        "boost_type_traits"
    ]

#### CONAN REMOTE LIST ####
conan remote list 
conan-center: https://conan.bintray.com [Verify SSL: True]
bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]

#### CONAN INSTALL DIRECTLY ####
conan install boost_filesystem/1.69.0@bincrafters/stable

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

ERROR: Recipe not found: 'boost_filesystem/1.69.0@bincrafters/stable'

#### CONAN SEARCH ####
conan search boost_filesystem -r=bincrafters
Existing package recipes:

boost_filesystem/1.65.1@bincrafters/stable
boost_filesystem/1.65.1@bincrafters/testing
boost_filesystem/1.66.0@bincrafters/stable
boost_filesystem/1.66.0@bincrafters/testing
boost_filesystem/1.67.0@bincrafters/stable
boost_filesystem/1.67.0@bincrafters/testing
boost_filesystem/1.68.0@bincrafters/stable
boost_filesystem/1.68.0@bincrafters/testing
boost_filesystem/1.69.0@bincrafters/stable
boost_filesystem/1.69.0@bincrafters/testing

**Comment by memsharded** [comment]
This is a weird issue, lets try to debug it step by step. Lets try the following:

```bash
$ rm -rf ~/.conan
$ conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
$ conan install boost_filesystem/1.69.0@bincrafters/stable
```

This should work, I have just tried here and works fine.

**Comment by KSBilodeau** [comment]
@memsharded Besides adding --build=missing to build boost_system, this seems to have fixed the issue, so that is pretty good.  I can't help but wonder what caused it though.

**Comment by memsharded** [comment]
It would be very complicated to know. As it is not fully clear, I am going to close this one now, but if it happens again, please open a new ticket and we will check.

Let me give a couple of hints:
- Public packages in ConanCenter are now being created with a build service from recipes in https://github.com/conan-io/conan-center-index
- Packages in ConanCenter can be searched in https://conan.io/center/
- New packages, more maintained by the community are those without user/channel, like ``freetype/2.10.2`` in https://conan.io/center/freetype/2.10.2/
- During the transition process, you might find some conflicts between the old and the new. It is recommend to try always the new ones, and if they are missing ask for them in https://github.com/conan-io/conan-center-index.
