### ISSUE TITLE
[bug] Cannot install pre-release packages with 'include_prerelease=True'

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#7343]
When I use a semantic version name such as "hello/1.0.0-pre.1" for a package that I upload to a repository, I am unable to install this package as a dependency in another project even when I specify  'include_prerelease=True' in the version requirements.

### Environment Details (include every applicable attribute)
  * Operating System: Windows 10 Version 10.0.19041 Build 19041
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.27.1
  * Python version: 3.8.3

### Steps to reproduce (Include if Applicable)
1. Create a new project: 
`conan new hello/1.0.0-pre.1 -t`
`conan create .`

2. Upload project to repository
`conan upload hello/1.0.0-pre.1 -r <REMOTE>`

3. Create a new project with conanfile.txt:
```
[requires]
hello/[~1.0, include_prerelease=True]
 
[generators]
cmake
```

4. Attempt to install requirements
` conan install .. -r <REMOTE>`

5. This error will be displayed:
`ERROR: Version range '~1.0, include_prerelease=True' from requirement 'hello/[~1.0, include_prerelease=True]' required by 'conanfile.txt' could not be resolved in remote '<REMOTE>`

**Comment by memsharded** [comment]
Hi @gsg-thuan 

This is not a bug, but within the specification of the version ranges and semver.

- The ``~1.0`` is a range equivalent to ``>=1.0.0 <1.1.0``
- The ``1.0.0-pre.1`` is something *previous* to the 1.0.0. It happens before, and it is not included in the range. It is kind of equivalent to ``0.9.99``

This is the reason why ``1.1.0-pre`` is resolved positively for the range ``~1.0``.

**Comment by memsharded** [comment]
Submitted a PR that explicitly covers this case too.

**Comment by memsharded** [comment]
The tests confirming this behavior have been merged in https://github.com/conan-io/conan/pull/7345, so this issue was closed, but please do not hesitate to comment or submit new questions as new issues if necessary. Thanks!
