### ISSUE TITLE
[question] How to exclude a indirectly imported package

### ISSUE THREAD

**Issue by neverchanje** [conan-io/conan#7344]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- Conan version: Conan version 1.27.1
- OS version: Ubuntu 18.04

Hi, I'm new to conan. I've searched docs for a while but can't find a solution.

I set up a conanfile.txt for my project with cmake as a dependency. However, CMake indirectly imported openssl, which I do not want to use, because there will be some linking errors if I use the openssl binary from conan-center. I tend to use the system package.

```ini
[build_requires]
cmake/[>=3.14]

[generators]
cmake
virtualenv
```

```
cmake/3.17.3
    ID: e72a00c968aff99bd71f77af14ecc27d88a6dc2f
    BuildID: None
    Remote: conan-center=https://conan.bintray.com
    URL: https://github.com/conan-io/conan-center-index
    Homepage: https://github.com/Kitware/CMake
    License: BSD-3-Clause
    Description: Conan installer for CMake
    Topics: conan, cmake, build, installer
    Recipe: Cache
    Binary: Cache
    Binary remote: conan-center
    Creation date: 2020-06-16 04:28:50
    Required by:
        conanfile.txt
    Build Requires:
        openssl/1.1.1g
```

As I look into my generated `conanbuildinfo.cmake`, I found openssl in `CMAKE_PREFIX_PATH`. I tried to work around by excluding `CONAN_OPENSSL_ROOT` from `CMAKE_PREFIX_PATH` in my CMakeLists.txt. But it didn't' work.

```
set(CONAN_CMAKE_MODULE_PATH "/home/wutao1/.conan/data/cmake/3.17.3/_/_/package/e72a00c968aff99bd71f77af14ecc27d88a6dc2f/"
			"/home/wutao1/.conan/data/rapidjson/1.1.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/"
			"/home/wutao1/.conan/data/gtest/1.8.1/_/_/package/a4062ec0208a59375ac653551e662b6cc469fe58/"
			"/home/wutao1/.conan/data/concurrentqueue/1.0.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/"
			"/home/wutao1/.conan/data/nlohmann_json/3.8.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/"
			"/home/wutao1/.conan/data/boost/1.69.0/_/_/package/06918ada0ff2e41e82ae56485f355483166c6ffa/"
			"/home/wutao1/.conan/data/openssl/1.1.1g/_/_/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/" ${CONAN_CMAKE_MODULE_PATH})

macro(conan_set_find_paths)
    # CMAKE_MODULE_PATH does not have Debug/Release config, but there are variables
    # CONAN_CMAKE_MODULE_PATH_DEBUG to be used by the consumer
    # CMake can find findXXX.cmake files in the root of packages
    set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_MODULE_PATH})

    # Make find_package() to work
    set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_PREFIX_PATH})
```

As we can see here, Conan also links openssl by default

```
set(CONAN_LIB_DIRS "/home/wutao1/.conan/data/gtest/1.8.1/_/_/package/a4062ec0208a59375ac653551e662b6cc469fe58/lib"
			"/home/wutao1/.conan/data/boost/1.69.0/_/_/package/06918ada0ff2e41e82ae56485f355483166c6ffa/lib"
			"/home/wutao1/.conan/data/openssl/1.1.1g/_/_/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/lib" ${CONAN_LIB_DIRS})

link_directories(${CONAN_LIB_DIRS})
```

Is there any method to exclude/hide openssl from my dependencies? I found a related issue https://github.com/conan-io/conan/issues/1797. But no progress since 2017.

**Comment by memsharded** [comment]
There are a couple of alternatives.

- If you are using Conan and that ``conanfile.txt`` to just install cmake, you might do first the ``conan install``, then activate the generated environment (``virtualrunenv`` should work ok too), and then run ``cmake`` in that environment. But not using the ``cmake`` information here, just the runtime environment. This is a pattern known to be used by some Conan users, they use a conanfile to declare their tools, install it, and then use it to develop, or to further run Conan within that environment, that will find the installed tools

- If you want to use ``cmake`` as ``build_requires`` in the same dependency graph as other dependencies, I think you are interested in the new "contexts" features. If you provide 2 profiles, like:

```bash
$ conan install . --profile:host=default --profile:build=default
```

Then there will be a "build" context with cmake, and the transitive "openssl" will not be linked with. If you were cross-building you would be using 2 different profiles in the host and in the build context. This feature is quite new, so the documentation (https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#cross-building-with-conan) might be a bit confusing sometimes with the old and new way of handling this, but please have a look and let us know.

**Comment by neverchanje** [comment]
Thanks for your help. But I'm afraid that "context" couldn't solve my problem. I would like to install cmake using pip. It's simpler and faster.

Btw, I troubled with the download speed of when I tried to adapt conan into my open-source project, especially when I downloaded the source tarball of boost (90MB. Because we are open-sourced and I don't want to host a public conan-server for our own, I have to give up with conan. It's frustrating. IMO conan is the future solution.

**Comment by memsharded** [comment]
> Btw, I troubled with the download speed of when I tried to adapt conan into my open-source project, especially when I downloaded the source tarball of boost (90MB. Because we are open-sourced and I don't want to host a public conan-server for our own, I have to give up with conan. It's frustrating. IMO conan is the future solution.

The download speed of the sources of boost does not have anything to do with Conan. You will have the same problem with any other solution, check the implementation of the boost recipe: https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conandata.yml

```
sources:
  1.66.0:
    url: [
      "https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2",
      "https://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.bz2",
    ]
    sha256: "5721818253e6a0989583192f96782c4a98eb6204965316df9f5ad75819225ca9"
  1.67.0:
    url: [
      "https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2",
      "https://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.bz2",
    ]
```
The sources are retrieved directly from the official site, not from Conan or ConanCenter. You will not get rid of this issue by not using Conan, and in a lot of cases that there are pre-compiled binaries in ConanCenter you will be saving a lot of time of building.

In any case, I understand, if you only need CMake (or just some other dep), it can be simpler to get it from pip. By the way, it doesn't mean that you couldn't use some other packages from Conan if you need and CMake from pip. 

If you consider using Conan again in the future, please do not hesitate to ask here any further question you have. Thanks!

**Comment by memsharded** [comment]
I forgot, if it is for an open source project, you could also try to apply for a free server in https://jfrog.com/artifactory/saas-gcp/

**Comment by neverchanje** [comment]
> The sources are retrieved directly from the official site, not from Conan or ConanCenter. You will not get rid of this issue by not using Conan, and in a lot of cases that there are pre-compiled binaries in ConanCenter you will be saving a lot of time of building.

Many thanks for your explaination! I was about to use CMake `ExternalProject_Add` to manage my 3rdparties. My deps are currently hosted on the alibabacloud OSS service. It's faster than the official link most of the time.

I think I could upload my recipe with the download URL linked to my OSS. Your guys are so helpful!

> I forgot, if it is for an open source project, you could also try to apply for a free server in https://jfrog.com/artifactory/saas-gcp/

God, it's awesome! We're an apache incubating project. I will take a try if necessary. Thank you!
