### ISSUE TITLE
[feature] Stop forcing User-Agent, or change it to not include "requests"

### ISSUE THREAD

**Issue by noizex** [conan-io/conan#7349]
While making a recipe for one of the libraries, I ran into interesting issue where Conan's downloader (`tools.get` used to download the zipped package of source code) would fail to download the file with status 406 - wget or any other client would download it without a problem. I digged a bit and figured out that "User-Agent" is the culprit - the server seems to not like the "requests" string, which is understandable as many scrapers / scripts will use this if someone doesn't bother to change it. Unfortunately Conan implements it in a way that prevents easy overriding it - it always forces "User-Agent" header to be `Conan/x.x.x (Python x.x.x) python-requests/x.x.x`.

There are a couple workarounds, I just went for passing immutable dictionary as headers to `get` method, which prevented Conan from modifying my "User-Agent" header, but I think it would be good if Conan would use just "Conan/ver" as a User-Agent, and drop the requests legacy, as it can cause problems like the one I have, and it's really not something you want to fight against. I think Conan is widely known now and using it as a user agent would be justified, and enforcing information about Python version or that it uses requests library does nothing really, except for giving headaches like the one I had. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @noizex 

Thanks for reporting this issue. A couple of quick questions:

- Is the server throwing the 406 available so we could use it to try and test things?
- Is the server returning some other diagnostic message? It seems the User-Agent is compliant with https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent, so if we are going to modify it, it would be good to make sure that the new one is fully compliant.

The truth is that so far this information has been useful for stats gathered in some of our servers, as the different Python versions and different requests library versions behave differently. At least the Python version has been extremely useful to plan deprecations and track community progress in upgrading Python. We need to think, maybe it is simpler to provide just an easy opt-out for that header for those (fortunately very few) problematic servers.

**Comment by noizex** [comment]
1) Yes it's available, sample file: https://www.angelcode.com/angelscript/sdk/files/angelscript_2.34.0.zip

Normally it returns 200 but once you pass the header that Conan uses it returns 406:
```
 wget https://www.angelcode.com/angelscript/sdk/files/angelscript_2.34.0.zip -U "Conan/x.x.x (Python x.x.x) python-requests/x.x.x"
--2020-07-14 01:20:04--  https://www.angelcode.com/angelscript/sdk/files/angelscript_2.34.0.zip
Resolving www.angelcode.com (www.angelcode.com)... 173.254.30.154
Connecting to www.angelcode.com (www.angelcode.com)|173.254.30.154|:443... connected.
HTTP request sent, awaiting response... 406 Not Acceptable
2020-07-14 01:20:05 ERROR 406: Not Acceptable.
```
2) Server just returns 406, my assumption is they use some filtering rules that forbid "python-requests". I doubt this is something that the owner did on his own, so must be some part of a ruleset that blocks requests - it's first time I see this, and I was surprised, but it does happen and with the fixed User-Agent of Conan it makes it harder to make recipes that download such files - in this case I do not have a GitHub repo available so wanted to use these zipfiles.

I too think the User-Agent used by Conan is fully compliant, but unfortunately it seems that having "python-requests" in the User-Agent makes it more likely to be blocked - I assume this appeared on some less thought through blacklists because it's default agent for Python HTTP module, so various scrapers used to announce themselves like this. Whether this is justified is another thing, but it does happen as you can see on the above example.

I see at least two simple options, not sure which is better:
1) remove "python-requests" part from the User-Agent, which makes it less likely to be blocked (I doubt anyone blocks "*conan*" or "*python*")
2) allow overriding User-Agent, as right now it will always force the one coming from Conan (unless you do the trick like I did with passing immutable headers dictionary) - it could be as simple as:
```
if "headers" in kwargs and "User-Agent" not in kwargs["headers"]:
    kwargs["headers"]["User-Agent"] = "Conan/x.x.x (Python x.x.x) python-requests/x.x.x" 
```
so it only sets UA if user did not provide own.

By the way, to whoever may be in similar situation and wants to bypass this problem, I used this solution as it was quickest thing I could come up with:

```
class silently_immutable_dict(dict):
    def __hash__(self):
        return id(self)

    def _silently_immutable(self, *args, **kws):
        pass

    __setitem__ = _silently_immutable
    __delitem__ = _silently_immutable
    clear       = _silently_immutable
    update      = _silently_immutable
    setdefault  = _silently_immutable
    pop         = _silently_immutable
    popitem     = _silently_immutable
```

then:

```
tools.get(URL, headers=silently_immutable_dict({"User-Agent": "Conan/{}".format(client_version)}))
```

Not sure if this has some unforseen drawbacks but worked so far :) I checked the code and `headers` dict was only modified to force the User-Agent so everything else should work fine, as long as you only use this class to wrap the immediate argument for headers to HTTP method calls on tools.

**Comment by memsharded** [comment]
To be honest, I think your solution 2) could almost be considered a bug, and fixed irrespectively of the possible removal of the ``requests`` in the header (I will need a bit more time to analyze its overall usage and utility)

As you already proposed the solution, if you want to contribute it directly with a PR, that will be welcome and we can merge it and release in next 1.28. If you can't dont worry, we will manage. Thanks!

**Comment by noizex** [comment]
Sure, I'll gladly make a PR - I considered starting with it but wasn't sure if this functionality would be desired. I suppose whoever decided to do this wanted to force a "Conan stamp" on each request made via conan tools, and while it's probably good to have a solid default, forcing it with no way of override causes situations like my to be a bigger pain than it could/should be :)

I will prepare this and link it in this thread once it's ready.

**Comment by memsharded** [comment]
Hi @noizex 

If this is to be included in Conan 1.28, it would be great to have it during this week (starting tomorrow). Let us know if you will manage to submit a PR, otherwise we will try to contribute it ourselves. Thanks!

**Comment by noizex** [comment]
@memsharded,
Ah, sorry, I got the change done but was stuck on thinking if I should add any tests - I couldn't find any particular tests for this area of ConanRequester. I had couple of busy days then and totally forgot to submit the thing. Do you think I could open PR and continue discussion on the possible tests etc there?

**Comment by memsharded** [comment]
Sure, submit the PR, and we will check about the tests

**Comment by noizex** [comment]
@memsharded so here is the PR:  #7390 
I didn't yet create documentation and the tests are missing - I think something around two paths: default provided User-Agent & User-Agent provided by user and not overriden, would be good to have...

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/7390
