### ISSUE TITLE
[bug] inconsistency in user/channel representation in filesystem and hooks code.

### ISSUE THREAD

**Issue by rasjani** [conan-io/conan#7350]
### Environment Details 
  * Conan version: any

### Steps to reproduce:

First off, my steps aren't "vanilla" conan but i hope you get the gist of the actual issue and the issue is more about "convention over configuration"-type of a thing. Something that your users dont even realize is a good thing but find it lacking when noticing ;) 

* build a conan package with ConanMultiPackager() without passing user and channel to constructor and environment variables to set those are not defined either.
* Expect and see that package/build/source/etc foldel have been created into `$root/$PackageName/$Version/_/_/**` 
* Have conan hooks configured that has passeds keyword arg reference into it. In my usecase this was `pre_export`-hook.

expected:

kwargs["reference"]'s list of values would match what gets into filesystem. eg, items 2 and 3 should be available as litral `_` 

actual:

kwargs["reference"][2:3] are both either not defined or they are passed in is None. I didnt check if they where in the list/tuple but f-string representation showed user/channel as None/None. 

usecase:

I was expecting that `kwargs["reference][0:3]` can be used to construct package location within the filesystem *and* provide information to metadata.json  .. This is ofcourse possible but i did have to replace `None` values or undefined list elements with `_` .

**Comment by memsharded** [comment]
Hi @rasjani 

It is true that the documentation is not very exhaustive about the ``reference`` field, all it says is:

> reference: Named tuple with attributes name, version, user, and channel. Its representation will be a reference like: box2d/2.1.0@user/channel

So the idea is that it is a representation of a reference, something as it is used in recipes, in the command line and in the terminal output. In all those cases it will be ``pkg/version``, and not ``pkg/version@_/_``. The ``_/_`` is just an artifact in the filesystem to represent the empty user and channel.

So it seems what is missing is some mapping between the reference representation and the filesystem one. This is already builtin in conan ``reference.dir_repr()`` will give the path, and ``ConanFileReference.load_dir_repr(path)`` will give a reference based on a path. You might use the first one at your own risk while we decide the approach, but it seems that this representation seems ok, it will be more common to be checking it as references, not as paths. Actually, if you are trying to construct the path to the actual package, this might be a different feature request that could make sense to be provided in the kwargs.

**Comment by jgsogo** [comment]
Hi, @rasjani .

I would like to know what are you implementing in the hook (you said it was `pre_export`) and what path you need. Hooks provide the `conanfile_path` and it's been enough so far, the path to the package folder won't be so straightforward, it contains at least the package_id and it can be totally obfuscated if it is using short_paths.

**Comment by rasjani** [comment]
Unrelated code stripped ..

```python
def pre_export(output, conanfile, conanfile_path, *args, **kwargs):
    ref = kwargs["reference"]
    json_data["full_package_reference"] = f"{ref[0]}/{ref[1]}@{ref[2]}/{ref[3]}"
```
and what gets into the json `"full_package_reference": "PackageName/1.0.0@None/None"`

**Comment by memsharded** [comment]
Just to clarify, because there might be some naming issues, we call:

- ``reference``, ``ref``, recipe reference, to the ``pkg/version@user/channel`` (with recipe revision it will have ``#rrev``)
- package reference, ``pref``, to the ``pkg/version@user/channel:package_id`` (with revisions it will also be  ``pkg/version@user/channel#rrev:package_id#prev`` (``prev``=package revision)

What you are doing is just the ``str()`` (without revisions) or ``repr()`` of the ``reference``: 

```
json_data["reference"] = repr(ref)
```
It will not print the ``None/None``.

**Comment by rasjani** [comment]
The point in general was that i was expecting user/channel to be set to `_/_`. Using repr() doesn't solve that either.  

However, this is not not a huge issue, just something that i was expecting (without reading the docs obviously) that it could be used to make some assumptions of about filesystem layout  where/how things are placed. 

For now, i'll just provide the those on my hook.

**Comment by memsharded** [comment]
Ok, good to know. So to summarize:

- ``reference`` is a reference, and when user/channel are not defined, they are ``None``.
- ``reference.dir_repr()`` would be the correct way to get a path representation (though not documented yet)

If you are going with the hook, then good, I think this issue can be closed at the moment. But seems like trying to map from references to folders in the cache manually seems fragile (the cache layout could change), so please, if you have a solid use case for a hook that needs some paths, please let us know, as it might be possible to add some paths like ``package_folder`` or ``build_folder`` to some of the hooks if it makes sense. Thanks!
