### ISSUE TITLE
[feature] Extending the Graph Info Template API

### ISSUE THREAD

**Issue by alacasta** [conan-io/conan#7354]
I've playing aroung the new feature provided at https://github.com/conan-io/conan/pull/7176 in https://github.com/alacasta/beautified-conan-info-dot-template and I miss some fields that can be really useful when building the dep. graph:
- Each (node) field separated (please, consider user/channel only in case they won't be deprecated soon)
  - name
  - version
  - channel
  - user
- Root node
- build require context

At least these were missing when trying to adapt https://github.com/conan-io/conan/pull/6815 to the template previously cited. and i consider them useful fields which can enrich the information provided in these kind of diagraphs. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2 - The `graph info` command returns the whole serialized dependency graph to the formatters, which can in turn use those as needed
