### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.spawn'

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#7362]
This worked in Conan 1.26, fails in 1.27.1

 Running the recipe from: https://github.com/kenfred/conan-qwt

### Environment Details (include every applicable attribute)
  * Win 10
  * MSVS 2017
  * 1.27
  * python --version:    Python 3.6.5 :: Anaconda, Inc.Python version:

### Steps to reproduce (Include if Applicable)
CD into dir then:
```
conan source .
ERROR: Error loading conanfile at 'C:\Users\xxxx\github\conan-qwt-kenfred\conanfile.py': Unable to load conanfile in C:\Users\210008258\github\conan-qwt-kenfred\conanfile.py
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\210008258\github\conan-qwt-kenfred\conanfile.py", line 6, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'
```

**Comment by memsharded** [comment]
I have tried to reproduce this:

- Win 10
- Conan 1.27.1
- Clean virtualenv with ``pip install conan==1.27.1``.
- Both in Python 3.6 and Python 3.7

Seems to be working fine. Is it possible that your Anaconda installation has changed something?

**Comment by ShamanTcler** [comment]
On thing I did not cover was it was a download of the Win 10 x64 conan. Not  a pip install

**Comment by memsharded** [comment]
It seems the ``conan-win-64_1_27_1.exe`` is working fine, while the ``conan-win-32_1_27_1.exe`` is failing. Are you sure you installed the 64bits one?

**Comment by memsharded** [comment]
It seems that I get the same error in ``conan-win-32_1_26_1.exe``, so it doesnt seem a regression from 1.26 to 1.27, but that the 32 bits package doesnt include ``distutils.spawn`` (we don't do anything special there, it is possible that the ``pyinstaller`` is excluding this because some 32bits support issue)

**Comment by ShamanTcler** [comment]
Yup you nailed it 32 vs 64  ... I checked my downloads and somehow I got some 32 bit downloads.... so I went back to the site and downloaded again.

I swear upon page reload , just hitting download when 64 bit text label was displayed I got the 32 bit exe. So then I went back and selected 64 bit and then I got the correct 64 bit ( or in other words 64 bit was displayed but the default download version was 32 ... if that is any more clear)

Anyways running the 64 bit version works like a champion. And chalk it up to a stupid user for not checking conan-win-64_1_27_1  vs conan-win-32_1_27_1  .... I should have seen that, but just to accustomed to clicking on through. (Yes if you slipped into the update process rights to my first born, I probably would have happily clicked on through)

You guys do a nice job, thanks

Carl

**Comment by memsharded** [comment]
> Anyways running the 64 bit version works like a champion. And chalk it up to a stupid user for not checking conan-win-64_1_27_1 vs conan-win-32_1_27_1 .... I should have seen that, but just to accustomed to clicking on through. (Yes if you slipped into the update process rights to my first born, I probably would have happily clicked on through)

No problem, these things happens to all of us all the time :) And the pyinstaller.py executables work in most of the cases brilliantly, but at some points they have these small differences that can indeed generate confusion

> You guys do a nice job, thanks

You are very welcome, just keep the feedback and support coming, and we will keep trying to do our best!
