### ISSUE TITLE
[feature] Show Conan version in HTML files

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#7365]
When Conan generates a HTML file (`search --table`, `info --graph`), the version which generated that file is not assigned there.

It can be useful for the follow cases:

* When a new feature is present and the result is different from the previous, so people can distinguish that is outdated
* When comparing HTML (e.g. 1.24 output x 1.25). Well we have JSON output for it, but let's say you and your co-worker are reading the HTML at same time
* When CI provides a table to indicate the current packages (like internal scripts).

Some possible preview (the version is before the table):

![Screenshot_2020-07-15 Conan boost 1 71 0](https://user-images.githubusercontent.com/4870173/87563284-6d09b180-c695-11ea-908a-5d9094fe3bd0.png)

- [ X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Totally agree. At the bottom of all these templates (graph and search) we can include a footer in small letters, something like:

```
Conan vX.Y.Z ©️ <YEAR> JFrog LTD. https://conan.io
```

wdyt @memsharded ?

**Comment by memsharded** [comment]
Totally agree! Lets do it.
