### ISSUE TITLE
[feature] Improvements in CLI 2.0 search

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#7367]
```
optional arguments:
  -h, --help            show this help message and exit
  -o {cli,json}, --output {cli,json}
                        Select the output format: cli, json. 'cli' is the default output.
  -r REMOTE, --remote REMOTE
                        Remote to search. Accepts wildcards. To search in all remotes use *
  -c, --cache           Search in the local cache
```

Some things to be considered:
1. I would use the ``--format, -f`` for the output format, the ``-o`` will conflict with the options
2. ``--remote`` should explicitly say that multiple remotes can be provided ``--remote=remote1 --remote=remote2``?
3. ``--cache`` probably don't need to be exclusive to remotes, if the output is multiple.
4. The default output format is the first in the list, but the input is a dict, which order is not defined. This needs to be fixed somehow.

A thing to discuss:

Probably the default formatter needs to be defined in its own argument, maybe some commands the default output is not ``cli`` but other format?

**Comment by czoido** [comment]
Closing as Conan 2.0 is already out and all these issues have been already adressed.
