### ISSUE TITLE
Improve '.editorconfig' file

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#7369]
![image](https://user-images.githubusercontent.com/1406456/87693965-e08eea00-c78d-11ea-9c86-6a116aaf471f.png)

**Comment by artorias111** [comment]
Hey! could you give some more insight into this? I'd like to make my first contribution. Can I work on this?

**Comment by jgsogo** [comment]
Sure, more than welcome. Thanks!

Consider modifying first the `.editorconfig` file in a PR and then we will eventually modify (step by step) all the files using it, do not make a PR modifying 2000 files 😄 

Thanks!

**Comment by artorias111** [comment]
Yeah got it, thanks a lot!

**Comment by artorias111** [comment]
Okay, so I need to put the line(s?)mentioned by @memsharded into the .editorconfig file and the make a pull request?

**Comment by memsharded** [comment]
Yes @artorias111 

The key here is to know what lines is necessary to put in .editorconfig that defines what to do with the multiple line indentation, I don't know if it is even possible.

I don't love the output of "black" formatter, but I am starting to consider it a possibility for Conan 2.0 codebase.

**Comment by artorias111** [comment]
Hey!
I found this: 
https://github.com/editorconfig/editorconfig/issues/412
This seems to be a _continuation_indent_size_ related issue. 
it appears the _continuation_indent_size_ property is "domain-specific"(i.e. specific only to some languages, hence not implemented by the .editorconfig file), as stated here in the EditorConfig wiki: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

**Comment by memsharded** [comment]
Hi @artorias111 

I have been playing with Pycharm, and it doesn't seem to support that editorconfig configuration.
Then, I think we should just define some convention and try to attach to it.

I vote for using the default Pycharm one, which is extra indent the code, like:

```python
if (something and 
        otherthing):
    do_something()
```

But lets use what the majority of maintainers want.

**Comment by CypherpunkSamurai** [comment]
Hello Everyone, Is this issue still active?

This issue looks beginner friendly, I'd like to contribute to this issue :)

**Comment by memsharded** [comment]
I think this is no longer active. It seems that we might considering using black after the migration to 2.0 ends, and we are no longer merging 1.X branches into 2.0.
