### ISSUE TITLE
[question] imported libraries (via imports()) get deleted during build, cannot be packaged later

### ISSUE THREAD

**Issue by AndreasHK** [conan-io/conan#7371]
Hi,

I'm somehow stuck at a very simple issue and I'm sure I'm overlooking something. I've got a shared library (let's call it MyLib) and an executable (let's call it MyExe) depending on it.

In the MyLib I have following package & package_info:

        def package(self):
            self.copy("*.h", dst="include", src="include")
            self.copy("lib*.so", dst="lib", src="lib")
    
        def package_info(self): 
            self.cpp_info.libs = ["MyLib"]
            self.cpp_info.includedirs = ["include"]

In the MyExe I have the following imports and package:

        def imports(self):
           self.copy("*.so", dst="lib", src="lib")
     
        def package(self):
            self.copy("MyExe", dst="bin", src="bin")
            self.copy("*.so", dst="bin", src="lib")

My issue is, that during `conan create` of MyExe, the MyLib-shared object is imported, but it is not put into the package folder. Furthermore it is gone from the build folder too (after the build of MyExe is finished). If I interrupt it directly after import, the shared object resides in the location I expected (.../build/12347/lib/).

The excerpt of the console output during a conan create is:
`MyExe/0.0.0@user/testing imports(): Copied 1 '.so' file: libMyLib.so`
and near the end:
`MyExe/0.0.0@user/testing package(): Packaged 1 file: MyExe`

I've attached both sample projects ([MyLib.zip](https://github.com/conan-io/conan/files/4936173/MyLib.zip) and [MyExe.zip](https://github.com/conan-io/conan/files/4936174/MyExe.zip)) for reproduction.

My understanding is that during the package-step of the MyExe, not only the executable, but also the shared object should be packaged. But this is not the case and I'm wondering why.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @AndreasHK ,
If you want to package the `so` files with `MyExe` you have to set the `keep_imports=True` in your conanfile, otherwise the imported files will be removed after building. You can check the [documentation about this](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=keep_imports#keep-imports).

**Comment by AndreasHK** [comment]
@czoido thank you so much for your input. It is embarrassing that I overlooked that...
