### ISSUE TITLE
[bug] conan install fails expecting `USERNAME` and `USERDOMAIN`

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan#7379]
### Environment Details (include every applicable attribute)
  * Windows 10
  * Conan 1.27.1
  * Python 3.8.3

### Steps to reproduce (Include if Applicable)

`conan install <conanfile>`

Will try and get a minimal working example if I can.

### Logs (Executed commands with output) (Include/Attach if Applicable)
[conan.log](https://github.com/conan-io/conan/files/4938978/conan.log)

**Comment by uilianries** [comment]
Your error comes from https://github.com/conan-io/conan/blob/1.27.1/conans/util/windows.py#L88

That's uncommon, because %USERNAME% is a default env var in Windows.

**Comment by memsharded** [comment]
Yes, can you verify you don't have such env-var in your environment?

We can try to relax that requirement, it is not necessary for many cases, you can read the whole functionality:

```python
    # Workaround for short_home living in NTFS file systems. Give full control permission
    # to current user to avoid
    # access problems in cygwin/msys2 windows subsystems when using short_home folder
    try:
        userdomain, username = os.getenv("USERDOMAIN"), os.environ["USERNAME"]
        domainname = "%s\%s" % (userdomain, username) if userdomain else username
        cmd = r'cacls %s /E /G "%s":F' % (short_home, domainname)
        subprocess.check_output(cmd, stderr=subprocess.STDOUT)  # Ignoring any returned output, quiet
    except (subprocess.CalledProcessError, EnvironmentError):
        # cmd can fail if trying to set ACL in non NTFS drives, ignoring it.
        pass
```

But still surprising that you don't have the USERNAME env-var defined.

**Comment by uilianries** [comment]
@memsharded Windows provides [whoami](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/whoami), which could be used when USERNAME is not available. Not sure if whoami consumes %USERNAME% too

**Comment by planetmarshall** [comment]
Closing as have been unable to reproduce (possibly Windows was in some intermediate state). Will reopen if it happens again and I can reproduce the exact circumstances.

**Comment by memsharded** [comment]
Thanks for following up @planetmarshall and letting us know.
