### ISSUE TITLE
[feature] Make it possible to extend virtualenv-generator environment-variables from within a consumer

### ISSUE THREAD

**Issue by LeonFretter** [conan-io/conan#7381]
Let's say i have a **provider-package** that in its `package_info` defines some **environment-variables**.
I also have a **consumer-package** which uses the `virtualenv`-generator, wants to use the virtual environment created by the provider-package, 
but wants to set some environment-variables itself, so that the **union** of the environment-variables from the provider and the consumer all land in *environment.sh.env*,
and a call to `source activate.sh` is all that a lazy developer has to do to use the resulting virtual environment.

It seems to me that it is currently not possible to extend a virtualenv from within the  consumer-package.
If it is, then i am sorry to have wasted your time (a small hint at how it is possible would be very kind)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @LeonFretter 

This is an interesting feature request, and will most likely be provided, but not by the ``generators``, but by the toolchains: https://docs.conan.io/en/latest/creating_packages/toolchains.html

The idea is that the ``toolchain()`` is whatever a recipe does to build itself. There is right now preliminary experimental support for CMake, but support for others, and also for environment is planned. The ``generators`` will keep being focused on information from the dependencies exclusively.

**Comment by LeonFretter** [comment]
Hi @memsharded ,
sounds reasonable to keep these concerns separated like this!
Im looking forward to a virtualenv-toolchain, and in the meantime, will have a look at existing toolchains. Thank you :)

**Comment by memsharded** [comment]
Hi @LeonFretter 

Sorry it took a while to follow on this.

Conan 2 added new generators (backported to Conan 1 too), like ``VirtualBuildEnv``, that allows customization and addition of variables, plus many other things (appending, pre-pending, managing vars that are lists of paths, etc).

I am closing this ticket as solved, but please create new tickets if you have any further question or issue about the new environment generators. Thanks for the feedback!
