### ISSUE TITLE
[feature] Define namespaces for generated entities, such as exported CMake targets

### ISSUE THREAD

**Issue by TimSimpson** [conan-io/conan#7385]
It is sometimes desired to change the namespace used for the targets created by the various CMake generators so they can match the targets created by naming schemes outside of Conan (such as the built in find modules or system installed packages). 

One way to tackle this problem would be to use the [filename attribute](https://github.com/conan-io/conan/issues/7254) to control the name given to the fine module, and then change the `names` attribute to be whatever the namespace needs to be. 

However to emulate related packages which may share a namespace for targets generated amongst themselves it becomes necessary to share the value for `cppinfo.names` attribute between packages. Because that value is then no longer unique, it's necessary to use the `filename` attribtue to represent a "more unique" value which can be used for generated variables (see the implementation of [this PR](https://github.com/conan-io/conan/pull/7320) where the global variables had to incorporate the filename to work with this [recreate](https://github.com/TimSimpson/conan-pkgs-with-shared-cmake-namespace-recreate) which contains multiple packages that share a namespace). 

It could simplify things to introduce a seperate attribute explicitly tied to the concept of a namespace in generated entities. This could then be used by the cmake generators.

As an example of how this attribute might be used, consider two packages from a theoretical modularized Boost:

```python
def package_info(self):
    self.cpp_info.namespaces["cmake_find_package"] = "boost"
    self.cpp_info.components["coroutine"].names = "coroutine"
```

```python
def package_info(self):
    self.cpp_info.namespaces["cmake_find_package"] = "boost"
    self.cpp_info.components["asio"].names = "asio"
```
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Thanks for the proposal!

I think that `namespaces` could be a more easy to understand word, however, the use case you are proposing can already be achieved with something like:

```
def package_info(self):
    self.cpp_info.names["cmake_find_package"] = "boost"
    self.cpp_info.components["coroutine"].names["cmake_find_package"] = "coroutine"
```
and
```
def package_info(self):
    self.cpp_info.names["cmake_find_package"] = "boost"
    self.cpp_info.components["asio"].names["cmake_find_package"]  = "asio"
```

the only thing missing IMO to achieve full integration is https://github.com/conan-io/conan/issues/7254, so I'd rather have that first and then evaluate if a namespace attribute is really needed in case it makes things easier 😄

**Comment by TimSimpson** [comment]
@danimtb After [some more thinking](https://github.com/conan-io/conan/pull/7320#issuecomment-661027328) I agree that either approach is acceptable.

**Comment by jgsogo** [comment]
Feature for `filenames` has been merged, this is no longer needed: https://github.com/conan-io/conan/pull/7320

Thanks!
