### ISSUE TITLE
Active Directory authorization

### ISSUE THREAD

**Issue by nitro44x** [conan-io/conan#739]
I like the idea of using conan internally at my company, however the plaintext passwords is a bit of a showstopper. How hard would it be to authenticate users on a Windows network using Active Directory?

Thanks

**Comment by lasote** [comment]
Hi @nitro44x, 

We know very little about Active Directory, but we are working in the integration with JFrog Artifactory, and they [support Active Directory](https://www.jfrog.com/confluence/display/RTF/Managing+Security+with+Active+Directory).

**Comment by memsharded** [comment]
Hi @nitro44x,

How has this evolved? Have you had a look to Artifactory?
Now conan_server also support auth plugins: http://docs.conan.io/en/latest/server.html#overriding-the-base-authentication

So I guess (having no idea about how AD works), that one plugin using https://zakird.com/pyad/pyad.html shouldn't be too difficult to implement.
