### ISSUE TITLE
[question] Consuming package with incompatible setting (build_type)

### ISSUE THREAD

**Issue by stewe26** [conan-io/conan#7392]
Hello,

I am in the process of getting to know conan and try to consume the first packages. My colleagues from another department are already using conan and provide some packages. So I tried to consume such a package - which we used to consume by "copy deployment" - using conan.
The binary files for component and its dependencies are not available for the settings of my default profile (which, by the way, maps to Visual Studio version 16 aka 2019), so I install them using the option `--build missing`:
`conan install <component> -r <remote> --build missing`

However, when it comes to building one of the dependencies, I get the following error:
```
ERROR: <subcomponent>: Error in build_requirements() method, line 30
        if self.settings.build_type == "Unicode":
        ConanException: Invalid setting 'Unicode' is not a valid 'settings.build_type' value.
Possible values are ['Debug', 'MinSizeRel', 'None', 'RelWithDebInfo', 'Release']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```
Obviously, my colleagues decided to extend the setting `build_type` with additional values to distinguish whether they build with/without unicode support. I am using the "default" settings.yml (of conan version 1.24.1) which does not include the `Unicode` value for `build_type`. I am not even trying to use this value, but because it is referenced in the recipe of the dependent package, the install/build fails.

I already figured out following possible solutions for my problem:
- I could extend my settings.yml with the new values
  - I do not like the idea of adding values in `build_type`. And the question whether my component provides unicode support is independent from the question whether my component builds as release or debug target. Personally, I would rather use a conan option to configure the unicode support, but I am not the owner/maintainer of that component.
- I can ask my co-workers to provide pre-built packages with the settings I am interested in and upload those in Artifactory.

Is there any other good way to get around this incompatibility? Can I tell conan to "ignore" (or don't check or map to `false` or something like that) these additional values when building? 

Just for completeness: I am trying to install with my default profile wich is
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @stewe26 

> I do not like the idea of adding values in build_type. And the question whether my component provides unicode support is independent from the question whether my component builds as release or debug target. Personally, I would rather use a conan option to configure the unicode support, but I am not the owner/maintainer of that component.

I think you are totally right. It seems your colleagues abused the ``settings.build_type``. That ``settings.build_type`` could be customized, but I think that it only would make sense to something like ``ReleaseWithSomeExtraOptimization`` or the like.

Unicode support totally sounds like either another setting or as an option:

- If the whole project can be configured to have Unicode support or not, maybe it can be a top level setting in the settings.yml, like ``unicode: [True, False]`` (tip, the value ``None`` is very convenient to also allow not defined the value). This approach requires recipes to explicitly add ``settings = "os", .... "unicode"``.
- If it is something that applies only to some platforms, maybe it could be a sub-setting of ``settings.os``, or if it is a compiler thing, maybe ``settings.compiler``.  This doesn't require recipes to change and add another ``settings`` explicitly
- If it is something that only applies to some packages, and it could have different values for different packages, then it sounds like an option. Packages define it and use it.

For the custom settings, yes, it is necessary to sync and update your ``settings.yml`` to use the definitions from the other team (I suggest using the ``conan config install`` functionality, I guess the other team might have it already available in a repo or .zip.


So I would suggest the following:

- First thing I would try is to talk with the other team. We can help there, talk with them, discuss the use case... the thing is that I think this abuse will come back to bite them easily. I would like to help them to build something more robust if possible.

- If that is impossible, i am afraid the only way is to add the ``Unicode`` as ``build_type`` in your ``settings.yml`` and follow their conventions.

Probably creating packages that do not depend or check the ``Unicode`` at all is very difficult, it seems that is already coded in their recipes.

Let us know if this help and if we can help talking with the other team. Thanks!

**Comment by stewe26** [comment]
Hi @memsharded 

Thanks for this really quick response. I am already in contact with the other team, they know that I opened this issue to clarify it there is some way around the troubles that came with extending the value range of `build_type`.

> We can help there, talk with them, discuss the use case... the thing is that I think this abuse will come back to bite them easily. I would like to help them to build something more robust if possible.

> Let us know if this help and if we can help talking with the other team. Thanks!

As far as I know, they already see that as a problem and want to get rid of the custom values (in fact it is not only one 'Unicode' like value). Having a (internal) customer that consumes their packages might be a driving force. On the other hand, they told me they currently don't have the manpower to look deeply at the package creation and improve it. I will definitely forward your offer for help - I can't tell if (and when) they will use it.

For now, I will discuss our options with them and try to find a way to consume the package. With some luck, this can be done without syncing the mentioned `settings.yml` values. 

My lesson learned from that is that one must be _very_ careful when it comes to extending the `settings.yml`.

Thank you for your help.
Best regards.

**Comment by memsharded** [comment]
> My lesson learned from that is that one must be very careful when it comes to extending the settings.yml.

Yes, totally, when you are changing the ``settings.yml``, it is assumed that other users using packages generated with those settings, need to keep them in sync. It is also generally speaking less disruptive to add sub-settings than adding first level settings, because that requires to explicitly add them to recipes.

As it seems there is no immediate action needed from us at the moment, I am going to close this issue now, but please re-open it if necessary or submit a new issue to discuss any further question. Cheers!
