### ISSUE TITLE
`--build=missing`, but only for some packages

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan#7393]
Is it possible to apply `--build=missing` only for some packages
i.e. `--build=missing:packageA:packageB:packageC`?

My use case: 
I have both small packages that can be re-built (if missing) and really big packages what i do not want to re-built ever ( https://github.com/blockspacer/llvm_tools )

I can not find anything similar in docs https://docs.conan.io/en/latest/mastering/policies.html

**Comment by memsharded** [comment]
Hi @blockspacer 

So isn't the ``build = "missing"`` policy in the recipes a good alternative? You could put that in the recipes that can be built from source quickly, and forget about needing to specify in the command line.

In any case, it seems that for the Conan CLI 2.0, we might want to dfferentiate explicitly the policies from package names. Something like:

```bash
--build-missing # build all missing
--build-missing=pkga # building pkga only if missing
--build=pkga # force the build of pkga in any case
--build-missing --build-never=pkgb  # build all that missing except pkgb
```

Just an idea, but @czoido maybe something we want to take into account for CLI 2.0

**Comment by memsharded** [comment]
Conan 2.0 introduced ``--build=missing:tool*`` syntax, it is possible now.

I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
