### ISSUE TITLE
[question] How to set preprocessor definitions in conan recipe

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7403]
So I am trying to setup a recipe for cross platform building. e.g. with the switch below:
(I am just using ANDROID as an example, as i find out ANDROID is already in the preprocessor definitions automatically. )

```
#ifdef ANDROID
		__android_log_write(ANDROID_LOG_ERROR, "error message.");
#else
		std::cerr << "error message." << std::endl;
#endif
```
How can I config the recipe so that this is taken care of automatically with my profile file?

I was thinking something like below using preprocessor definition, but since the preprocessor definition is just a definition without value, am i using it correctly by using the None value? 
```
    def build(self):
        cmake = CMake(self, build_type="Debug")
        if self.settings.os == "Android":
            print("predefine ANDROID for building Android packages")
            cmake.definitions["ANDROID"] = None
        cmake.configure()
        cmake.build()
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @shelper 

It is not possible to pass directly preprocessor definitions transparently through the CMake build system:

- definitions can be passed to CMake, always with a value (can be False or None, but need a value, in CMake will be a string). But these are CMake definitions, not preprocessor definitions.
- CMake can define preprocessor directives in some different ways, like ``add_compile_definitions()`` https://cmake.org/cmake/help/latest/command/add_compile_definitions.html

So it is necessary to do in the CMakeLists.txt something like:

```cmake
if (DEFINED ANDROID)
       add_compile_definitions(ANDROID)
endif()
```

**Comment by memsharded** [comment]
BTW, the ``CMake`` build helper will try to set the environment, so it is possible that ``definitions["CMAKE_SYSTEM_NAME"] == "Android"`` will already be defined, so you could use that in your CMakeLists.txt directly, without needing to specify anything else in the ``conanfile.py``.
