### ISSUE TITLE
[question] Dynamic selection of generator based on settings

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#7406]
Is it possible to dynamically select the generator from inside of a conanfile.py file based on the selected settings?

We currently use premake for most of our builds but need to use cmake to build for android. I think I have both premake and cmake working as I need and can select from the command line using the -g flag or just specify both in the conanfile, but it seems like it could be useful to have my conanfile.py select the correct generator based on the settings. That way I'm not generating files extra unnecessary files and I don't have to think about which generator to use.

**Comment by memsharded** [comment]
Hi @nichmj01 

Yes, we are suggesting for conditional configuration, including generators, to use the ``configure()`` method. It is possible to do:

```python
def configure(self):
    if self.settings.os == "Windows":
        self.generators = "premake"
    else:
        self.generators = "cmake"
```

Please give it a try and let us know.

**Comment by nichmj01** [comment]
Hi @memsharded 

I had to make a small adjustment to put the generator in a list:
```python
def configure(self):
    if self.settings.os == "Windows":
        self.generators = ["ojpremake"]
    else:
        self.generators = ["cmake"]
```
With that it works!

I also tested appending to the list so it will still accept the -g flag and that seems to work.

Thanks!

**Comment by nichmj01** [comment]
Possible interesting note: 
`self.generators` comes in already containing the 'txt' generator which I remove/replace with my snippet above. However, the txt generator still gets called later as I can see it listed in the on-screen log and conanbuildinfo.txt is generated. Maybe appending to the list in general is safer? I was looking at only specifying the "default" if the list was empty but I can check that it only contains the txt generator.

Update: Looks like trying to specify a "default" generator when none is specified using -g this way doesn't work. Seems like the -g generator is added later. Not important for what I need though.

**Comment by memsharded** [comment]
Hi @nichmj01 

Good catch. While evaluating the ``configure()`` the generators is already a list, so needs to be managed as a list.
The ``txt`` generator is both initialized and also added later after user definitions, no problem you can keep declaring your generators that way. It is a legacy thing that will be removed in Conan 2.0.
