### ISSUE TITLE
[feature] Conan virtualenv on Linux and Mac should generate powershell script as well shell script

### ISSUE THREAD

**Issue by mjvankampen** [conan-io/conan#7407]
We use Powershell 7 quite a bit under Linux and Windows as it is a way to do some cross platform scripting (and most are devs are on Windows). It would be nice if activate.ps1 is also generated on Linux and Mac so those are useable from Powershell 7.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Closed by https://github.com/conan-io/conan/pull/7408. This will be released in Conan 1.28! Thank you! 😄
