### ISSUE TITLE
[feature] Option/String field to declare WHY a minimum require is defined

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#7410]
Very often, a recipe author will realize: 
- Hey, i'm using new feature XYZ, in order for this recipe to work, users will need at least this feature

That's the most common and well-understood use-case for this feature.   It would be VERY helpful for the user to be able to annotate the REASON for the requirement. That reason could print out during failure.  it would be very helpful for users trying to make use of the feature suggested here:  https://github.com/conan-io/conan/issues/7409

Also, it might help people trying to adapt the recipe to work on older versions to know what they need to change.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Thinking about it, seems a bit too much of a feature for something that could easily be a comment:

```python
# This recipe use components
required_conan_version = ">=1.27
```

Being realistic, I think that users will not use either, and for the very few ones that would like to annotate, a comment will be enough information for collaborators contributing on the recipe.

Also, there would be 2 ways to implement this:

- As another variable:
```python
required_conan_version = ">=1.27"
required_conan_version_reason = "using components"
```
- As something to parse:
```python
required_conan_version = ">=1.27 # using components"
```

I do not love any of those, a bit better the second one, but still I don't see users really responsibly annotating recipes.

**Comment by solvingj** [comment]
lol, k
