### ISSUE TITLE
[question] HowTo propagate includedirs for pkg consumers

### ISSUE THREAD

**Issue by saimusdev** [conan-io/conan#7411]
# How to publish include dirs in some package and consume them in another?

I'd like to know how **SPECIFICALLY** to define the attributes of `self.cpp_info.*` so that they're correctly propagated to the command line interface and correctly parsed by the compiler e.g. gcc.

We've tried to set the following as follows, with no luck:
```python
def package_info(self):
  # if cross-building, we use a sysrooted file-system with some libs
  if tools.cross_building(self):
    self.cpp_info.includedirs = [
      "/usr/include/some/path",
      "/usr/include/some/path"
    ]
```
Other tests:
```python
def package_info(self):
  # if cross-building, we use a sysrooted file-system with some libs
  if tools.cross_building(self):
    self.cpp_info.includedirs = "-I=/usr/include/some/path", "-I=/usr/include/some/path"
```
another:
```python
def package_info(self):
  # if cross-building, we use a sysrooted file-system with some libs
  if tools.cross_building(self):
    self.cpp_info.includedirs = "-I=/usr/include/some/path -I=/usr/include/some/path"
```

The problem is, that those flags go into the CLI with escaped quotes (by what I assume is the `CMake` generator) than is fed to the compiler, like:

```
gcc -foo -bar "-I=/usr/include/some/path -I=/usr/include/some/path"
```
and obviously the compiler complains about those arguments with quotes.

Related Q: what would be best, to utilize `self.cpp_info.includedirs` with a list of includes or `self.cpp_info.cxxflags` with `-I=` prefixes?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by saimusdev** [comment]
> Hi,
sorry if I missed it in the docs somewhere but is it possible to add include dirs, e.g. to a sysroot subdir, into the cpp_info?
Currently we're building our binary with  `-I =/opt/foo/bar` but I have not found a way to transport this information to the consumers of the package.
Conan seems to translate all includedir paths into absolutes. When I put these instructions into the cxxflags they get quoted `arm-g++ "-I /opt/foo/bar" <http://main.cc|main.cc>` when generating for CMake and then g++ can not resolve them.

Posted originally by Christoph Schlosser on Slack:

<sub>[View in Slack](https://cpplang.slack.com/archives/C41CWV9HA/p1595512623308200)</sub>

**Comment by saimusdev** [comment]
> Hmm, it seems that in `client/generators/cmake.py:52` the flags are appended in the following manner...
```self.cxxflags = join_flags(" ", cpp_info.cxxflags)```
But then... in `client/generators/cmake.py:22`  replaces `"` with `\"`  and this obviously passes through to the CLI...
Maybe if you use single quotes instead of double quotes in the definition of those strings?
<sub>[View in Slack](https://cpplang.slack.com/archives/C41CWV9HA/p1595518286315500)</sub>

**Comment by saimusdev** [comment]
I did some minor investigation, but still unsure if the issue is with the double quotes, with the array declaration, with the missuse of this functionality,...

The fact of the matter is: if some library is using some include prefixes to build, (I'd like to know about those), as a consumer, so that they're automatically fed into the CLI and everything works out-of-the-box. Obviously, manually setting those prefixes in the package consumer's recipe or CMake toolchain is not a viable option...

**Comment by saimusdev** [comment]
Hello, could someone please post some information?

**Comment by lasote** [comment]
Hi, the first approach should work:

```
def package_info(self):
  # if cross-building, we use a sysrooted file-system with some libs
  if tools.cross_building(self):
    self.cpp_info.includedirs = [
      "/usr/include/some/path",
      "/usr/include/some/path"
    ]
```

What is the issue in that case?

**Comment by saimusdev** [comment]
As I said, that is not properly passed thru to the compiler, the quotes `"` are still there e.g.
```
gcc -foo -bar "-I=/usr/include/some/path -I=/usr/include/some/path"
```

**Comment by memsharded** [comment]
Hi @saimusdev 

We are missing some information. This works, with the current built-in generators, the functionality is well tested, so there might be something else somewhere in your recipe or build scripts:

- The recommended way is a list of paths in ``self.cpp_info.includedirs``. Not to add them in cxxflags or elsewhere.
- If those path are absolute, they will be respected, otherwise they will be appended to the current package path
- The generator that you are using should be creating some files. If ``cmake`` generator, you can check the INCLUDE_DIRS variables inside ``conanbuildinfo.cmake``.
- We would need to see your ``CMakeLists.txt``, and your consumer recipe or script, to check how you are consuming the generated file, there might be something there causing the issue.

Could you please share that missing information so we could reproduce the issue? Many thanks!

**Comment by cschlosser** [comment]
Let's assume:

* We have a sysroot installed (different for each developer) in `/home/$USER/xc/sysroot`, `/workspace/xc/sysroot` or where ever.
* There are "native" binaries for the additional functionality from third parties that are always installed into `/opt/3rd-party`

Using a conanfile like this:

```python
import conans

class Lib_Conanfile(conans.ConanFile):
    name = "Lib"
    version = "0.1.0"
    settings = "arch", "build_type", "compiler", "os"
    exports_sources = "*.cc", "*.h", "../*.cmake", "CMakeLists.txt"
    generators = "cmake"

    def _cmake(self):
        cmake = conans.CMake(self)
        if conans.tools.cross_building(self.settings):
            cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = "foo-toolchain.cmake"
        cmake.verbose = True
        cmake.configure()
        return cmake

    def build(self):
        cmake = self._cmake()
        cmake.build()
        
    def package(self):
        cmake = self._cmake()
        cmake.install()

    def _xc_paths(self):
        return [ "-I$SYSROOT/usr/include/foo/bar" ]
    
    def package_info(self):
        self.cpp_info.libs = ["lib"]
        if conans.tools.cross_building(self.settings):
            # Doesn't work: It seems to look for /usr/include/foo/bar in the host system where it doesn't exist and then drops it
            self.cpp_info.includedirs = [ "include", "/usr/include/foo/bar" ]
            # Doesn't work either: It seems to look for /conan/package/path/=/usr/include/foo/bar where it doesn't exist and then drops it
            self.cpp_info.includedirs = [ "include", "=/usr/include/foo/bar" ]
            # works as expected
            self.cpp_info.cxxflags = self._xc_paths()
        else:
            # Works because /opt/3rd-party/foo/bar is available on the host
            self.cpp_info.includedirs = [ "include", "/opt/3rd-party/include/foo/bar" ]
```

Maybe cpp_info needs an additional attribute like `sysroot_includedirs`?

```python
def package_info(self):
        self.cpp_info.libs = ["lib"]
        if conans.tools.cross_building(self.settings):
            self.cpp_info.sysroot_includedirs = [ "/usr/include/foo/bar" ]
        else:
            # Works because /opt/3rd-party/foo/bar is available on the host
            self.cpp_info.includedirs = [ "include", "/opt/3rd-party/foo/bar" ]
```

This could then generate `-iwithsysroot /usr/include/foo/bar` for clang and `-isystem $SYSROOT/usr/include/foo/bar` for gcc.

**Comment by saimusdev** [comment]
Hey @memsharded,

any inputs on how to deal with this?

Thanks!

**Comment by memsharded** [comment]
I am closing this ticket as outdated. 
It was referring to integrations that were deprecated in Conan 1 time ago, and were fully removed in Conan 2.
The issues reported above shouldn't happen with the new integrations.

If necessary please create new tickets for any further question or issue, thanks for the feedback.
