### ISSUE TITLE
[bug] Setting MSBuild.build toolset argument does not change the PlatformToolset MSBuild will use.

### ISSUE THREAD

**Issue by ajmetal** [conan-io/conan#7419]
I have multiple versions of Visual Studio installed on my machine, and I need to build a .dll in Visual Studio 2015.

When I call 

> msbuild.build("solutionFile.sln", None, False, "Release", "x86", True, False, None, None, "v140")`

I get an error because it tries to link against another lib that was built with an older compiler. The error message outputs:

```
conanfile.py (myDLL/0.1): Error in build() method, line 41
        msbuild.build("solutionFile.sln", None, False, "Release", "x86", True, False, None, None, False)
        ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Auxiliary/Build/vcvarsall.bat" x86 && msbuild "solutionFile.sln" /p:Configuration="Release" /p:UseEnv=false /p:Platform="x86" /m:8 /p:PlatformToolset="v142" /verbosity:minimal /p:ForceImportBeforeCppTargets="path\to\conan_build.props"
```

So its using the incorrect Visual Studio version (2019), and ignoring the toolset I passed in.

This is my conaninfo.txt: 

```
[settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=14
    compiler.toolset=v140
    os=Windows

[requires]


[options]


[full_settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=14
    compiler.toolset=v140
    os=Windows

[full_requires]


[full_options]


[recipe_hash]


[env]
```

AFAIK I'm not intentionally indicating anywhere that I want conan to use VS 2019. I specified "v140" for the toolset because I want it to use VS 2015.

**Comment by memsharded** [comment]
Hi @ajmetal 

There are a couple of discrepancies in the above output, I think it would be good to know more about.

The ``PlatformToolset="v142"`` in the command output is not the same as the one in the ``conaninfo.txt``.  Could you please tell:

- What is the input profile you are using, and what is the output of the ``conan create`` command (that will include the effective profile too).
- I would also like to understand your intended arguments, if I assign the keys:

```python
msbuild.build(project_file="solutionFile.sln", targets=None, upgrade_project=False, build_type="Release", arch="x86", parallel=True, force_vcvars=False, toolset=None, platforms=None, use_env="v140")
```
See the method from the docs:
```
def build(self, project_file, targets=None, upgrade_project=True, build_type=None, arch=None,
          parallel=True, force_vcvars=False, toolset=None, platforms=None, use_env=True,
          vcvars_ver=None, winsdk_version=None, properties=None, output_binary_log=None,
          property_file_name=None, verbosity=None, definitions=None,
          user_property_file_name=None)
```

So it seems the ``v140`` you are passing in the command is incorrect, at the wrong place.

Also is it possible that you are already in a VS 2019 prompt? The ``msbuild`` activates the ``vcvars`` environment, but it would conflict if an incompatible one is already active (the ``force_vcvars=True`` will try to force them anyway, though the behavior might be a bit undefined)

**Comment by ajmetal** [comment]
Thank you! I had the arguments wrong, I'm using:
`msbuild.build(project_file="solutionFile.sln", upgrade_project=False, build_type="Release", arch="x86", toolset="v140")`

and  the output I get is:

```
ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Auxiliary/Build/vcvarsall.bat" x86 && msbuild "solutionFile.sln" /p:Configuration="Release" /p:UseEnv=true /p:Platform="x86" /m:8 /p:PlatformToolset="v140" /verbosity:minimal /p:ForceImportBeforeCppTargets="C:\Users\johannes.spaulding\Documents\VisualStudio2015\Projects\project\conan_build.props"
```
So the PlatformToolset is correct, but it still looks like its calling VS 2019?

When I run conan create I get:

```
MSBUILD : error MSB1009: Project file does not exist.
Switch: solutionFile.sln
myDLL/0.1: 
myDLL/0.1: ERROR: Package '3fb49604f9c2f729b85ba3115852006824e72cab' build failed
myDLL/0.1: WARN: Build folder C:\Users\johannes.spaulding\.conan\data\myDLL\0.1\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab
```

Im running all these commands in a powershell window from the directory where my conan files are.

**Comment by memsharded** [comment]
Hi @ajmetal 

What is the whole output before the ConanException showing that error? It would be interesting to know the "effective" profile that is being used. Also, the ``conanfile.py`` needs to have defined the ``settings = "os", "compiler", "build_type", "architecture"``, in order to receive correctly the settings from the profile.

Then, it might be possible that you are not exporting the project .sln and other files, and that is why the ``conan create`` is failing to find the .sln.

Maybe this howto can help: https://docs.conan.io/en/latest/howtos/visual_studio_packages.html. It contains links 2 repos that can be cloned and used to create and consume packages, so this could be used as a reference.

**Comment by memsharded** [comment]
Closing this ticket as outdated, referring to the old and legacy ``MSBuild`` integration, not the new ones.

Please create new tickets as necessary reporting against latest Conan 2.X integration, thanks!
