### ISSUE TITLE
[bug] conan install .  failed

### ISSUE THREAD

**Issue by DaveCage** [conan-io/conan#7427]
When i cmd the command conan install . ,it report an error report 
### Environment Details (include every applicable attribute)
  * Operating System+version:windows10
  * Compiler+version:Visual stuido
  * Conan version:1.27.0
  * Python version:3.7.0

more details:
    name = "CameraTestTool"
    version = "0.0.1"
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of CameraTestTool here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}
    exports_sources = "*"
    no_copy_source = True
    #self.settings.compiler == "Visual Studio"

    generators = "visual_studio"

    requires="TeamLibrary/VS2017_develop_20200724.4@TeamLibrary/stage"

### Logs (Executed commands with output) (Include/Attach if Applicable)

ERROR: 'settings.compiler.libcxx' doesn't exist for 'Visual Studio'
'settings.compiler' possible configurations are ['cppstd', 'runtime', 'toolset', 'version']

thanks for your help.i havent find a same problem like mine via internet.

**Comment by DaveCage** [comment]
i did find settings.yml and settings.yml.new those two files in my document ,and i deleted them .it changes nothing ,i got the same error

**Comment by memsharded** [comment]
Hi @DaveCage 

It seems your ``conanfile.py`` is checking ``self.settings.compiler.libcxx`` at some point, but you are trying to instantiate it with Visual Studio compiler, that doesn't have such configuration. Sounds like a bug in your recipe, and you probably want to fix it, doing a ``self.settings.get_safe("compiler.libcxx")``, for example: https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=get_safe

Please share your ``conanfile.py`` if you want, so we can have a look.

**Comment by DaveCage** [comment]
```
``from conans import ConanFile, MSBuild, tools
 
class CameraTestToolConan(ConanFile):
    name = "CameraTestTool"
    version = "0.0.1"
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of CameraTestTool here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}
    exports_sources = "*"
    no_copy_source = True
    generators = "visual_studio"
    requires="TeamLibrary/VS2017_develop_20200724.4@TeamLibrary/stage"

    
    def build(self):
        print(self.settings.compiler)
        msbuild = MSBuild(self)
        msbuild.build("XiaoMiCameraTestTool.sln")
 
    def package(self):
        self.copy("*.h", dst="include", src="hello")
        self.copy("*hello.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)
 
    def package_info(self):
        self.cpp_info.libs = ["hello"]
```

**Comment by memsharded** [comment]
Uhm, interesting, that shouldn't fail.

Can you please share the full error output trace, the one containing:

> ERROR: 'settings.compiler.libcxx' doesn't exist for 'Visual Studio'
'settings.compiler' possible configurations are ['cppstd', 'runtime', 'toolset', 'version']

Maybe is it possible that the error is in the dependency, in ``TeamLibrary/VS2017_develop_20200724.4@TeamLibrary/stage``, not in your recipe. You could try doing:

```
conan install TeamLibrary/VS2017_develop_20200724.4@TeamLibrary/stage
```

**Comment by ll01** [comment]
Go to the file ` C:\Users\<your user name>\.conan\profiles\default` and delete the line that says `compiler.libcxx=libstdc++11`

**Comment by memsharded** [comment]
This issue is 2 years old, and the OP never followed up providing the full traces, so it was difficult to triage this.

Closing this issue, if @DaveCage wants to reopen or create a new one, we will have another look, thanks
