### ISSUE TITLE
[feature] Allow user-defined generators to be used with conan install -g

### ISSUE THREAD

**Issue by kralicky** [conan-io/conan#7432]
The ability to "mix in" generators when installing a package reference is a unique feature that I think could be improved by allowing the use of user-defined generators.

The motivation for this comes from wanting to write a custom generator which would take any existing package and generate new file(s) from it at install time, similar to some of the built-in generators. Since this is restricted to built-in generators only, a new recipe would need to be created, maintained, and kept around for every package I wanted to use my custom generator with.

I have a very simple implementation of this feature [here](https://github.com/cobalt77/conan/commit/e1947d58a7f9da78d6ddf24cdd81dca911cb2170). I added a new folder in the client cache called 'generators' which can contain user-defined generators. These can be installed using 'conan config install'. When 'conan install' is invoked with a package reference, user-defined generators from the generators folder are loaded and available to use with -g.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I agree with this. There is some pending improvements and discussions to be done around generators, see https://github.com/conan-io/conan/issues/6790

Having generators as config in the conan cache would make sense. Although a bit earlier than expected, if you want please do a PR with your implementation and lets discuss about it in next Conan 1.29, we need to think about other implications so no guarantee that could be merged, but lets look into it. Thanks!

**Comment by jgsogo** [comment]
I have the same concern as stated [here](https://github.com/conan-io/conan/issues/6790#issuecomment-647960865) by @maikelvdh: how to handle it properly? how to record the version used? (reproducibility and traceability)

A feature I think about from time to time (but never too seriously) is adding `python_requires` to the profiles, Conan would add those python-requires to every package, functions would be available, **generators would be registered**, other tools like build-helpers or toolchains classes,... and that information would be recorded in the lockfile.

**Comment by kralicky** [comment]
@jgsogo The main motivation for this comes from wanting to using generators at install time to deploy packages in specific ways without the packages themselves needing to know about the generator. For instance, my company's use case is to use a generator to transform a conan package into an RPM. Managing dozens of in-house libraries using individual RPMs is a **nightmare** (I cannot stress this enough), but with Conan packages it is trivial. The missing piece is being able to convert any of our conan packages into an RPM when necessary.

My implementation has the effect of profile python_requires for generators only. these generators would be internal - created by a developer for their team to integrate the package with their own environment, just like profiles. The generators are not versioned and have no recipe (just like the builtin ones); when using them at install time, the generator simply interacts with the package using a virtual recipe and the package does not need to know about it or be able to reproduce the installation.

This design allows for a single package to be deployed in any number of ways by different generators. You could set up generators to transform a package into a variety of formats which could make deploying artifacts a lot less tedious.

I don't think this is a perfect solution, but it is a solid starting point for a feature that does not have a good workaround as of now. I have some ideas on how this can be improved further (but would require non-trivial refactoring). The end goal in my mind would be to separate generators into two categories - those which a _package uses_, and those which _use packages_.

**Comment by jgsogo** [comment]
Yes, I totally understand your motivation, and I really like your last statement:

> The end goal in my mind would be to separate generators into two categories - those which a package uses, and those which use packages.

💯 🙌 

As this is a "look into", it is good to consider all the alternatives and think about the mid-term and the final approach we want. In my opinion, I agree with you, Conan would benefit from the introduction of another category of items that _use packages_ (some current generators could be moved to that category, like `virtualxxxenv`, `deploy` or `markdown`). The main objective os these classes is to extract data/binaries from Conan and make it available to external tools, and Conan no longer consumes this information. I agree this kind of _generators_ doesn't need to be versioned.

Do these _generators_ make sense only when running `conan install <reference> -xxx <new-generator>`? Will they ever be used inside a recipe to interact with the requirements?

**Comment by kralicky** [comment]
I think they make the most sense when separated from the recipes themselves, however the recipes should be able to provide as much abstract information as possible to allow usage with many different \<new category> generators. This information might be things like installation folders, functions to run on pre/post install, etc.
