### ISSUE TITLE
[feature] Allow generators to delegate file creation to an external tool 

### ISSUE THREAD

**Issue by kralicky** [conan-io/conan#7433]
When writing a generator to integrate with an existing tool, it may be useful to invoke the tool directly and return its output file. However, some tools write their own files and don't support writing the data to stdout instead. Custom generators require contents() to return a value, but a generator could instead indicate that it has indirectly created the file using an external tool, and it need not be created again from the return value of contents(). Conan should still print "Generator x created y" to the terminal, but not write the file itself. 

I have an implementation of this feature [here](https://github.com/cobalt77/conan/commit/e65bfbdb4911dc6d431f4e1407c7d4edc7bca7ec). A custom sentinel 'Delegated' can be returned from contents() or as the value in a dict entry to skip writing the file with the corresponding filename. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @cobalt77 

I am not sure about the proposed approach. Wouldn't it be enough to return an empty dict in ``contents()``, and let the generator print directly whatever it wants to print?

**Comment by kralicky** [comment]
Thanks for the response @memsharded!
I think it might be useful (for potential future improvements) for conan to to continue to be able to know about all files that are created by generators, and which generators created which files. Conan could aggregate this information currently because it writes all the files itself, but if a generator can return an empty dict, conan would not be able to know which files were created by that generator.

**Comment by memsharded** [comment]
yes, indeed, connecting this issue to with #6790 

I think the implementation could actually be that the path to the written files is returned, not just a "flag". My suggestion above was a way to be able to do that approach today, (without the output report), because it seems that we want to consider this feedback in the next iteration over the generators management, because it should be jointly considered with the whole UX of generators.

**Comment by kralicky** [comment]
Agree, could do something like this for the next iteration:
```python
def SomeGenerator(Generator):
    def generate(self):
        tools.save("file1.txt", ...)
        tools.save("file2.txt", ...)
        subprocess.run(<external tool>) # generates file3.txt
        return ["file1.txt", "file2.txt", "file3.txt"]
```
Additionally, conan could verify that the files the generator claims to have created actually exist. 

If conan stores a list of generated files, that might enable being able to do something like this:
```python
copy("*", excludes="@generated")
copy("*", excludes="@generated(generator_name)")
```

**Comment by memsharded** [comment]
latest Conan 1.X versions have already moved to this explicit ``generate()`` method, which will be the default in 2.0. Not even necessary to report the generated files, the ``build()`` utils will use these file accordingly.
