### ISSUE TITLE
[feature] Make checking remotes for updates an opt-in behaviour through conan.conf

### ISSUE THREAD

**Issue by maikelvdh** [conan-io/conan#7439]
Currently you need as an user to always declare `--update` in order to check remotes if there are any updates to a package. It would be nice to make this also a configurable option within the `conan.conf` configuration to do this check always in case you have opted-in for this behaviour.

This behavior would for example greatly help if you are relying on revisions and would like to guarantee that everyone is having the latest version installed in their cache.

**Comment by memsharded** [comment]
Closing this as not planned at the moment. An ``--update`` by default will quite inconvenient devs, because it makes dependency resolution much slower, while optin-in is just a ``-u`` to add.
