### ISSUE TITLE
[question] required pluginbase version

### ISSUE THREAD

**Issue by stkw0** [conan-io/conan#7440]
Seems that conan depends on pluginbase<1.0. Are there some plans to make it compatible with pluginbase-1.0?

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pluginbase 1.0.0 (/usr/lib/python3.7/site-packages), Requirement.parse('pluginbase<1.0,>=0.5'), {'conan'})

```
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @stkw0 

This requirement is pretty old (git blame says 2017), and is used only in the ``conan_server``, not the client.

It might be possible to relax the requirement, nothing against it if it works without problems. I would suggest sending a PR relaxing the *requirements.txt* to include the 1.0, see if it passes CI. If not, try to fix the incompatibilities if any. If necessary to exclude versions <1.0, then we probably need to think about it twice. 

Do you want to send that PR?

**Comment by stkw0** [comment]
Yeah why not, I will do it :) Seems that pluginbase is only used in one little file, I guess in case of incompatibilities it should be easy to fix.

Thanks

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/7441
