### ISSUE TITLE
[question] How to remove /update the username and password for a remote server

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7445]
So i have added a remote package repo setup in artifactory, that needs username and password,
So I input the wrong user name and password and thus got rejected. 
then i removed the remote server by `conan remote remove remote-name`, then add it back, and connected to it again, what i expected is conan will ask for username and password as it is newly added, but what happened is conan still uses the old username and password, thus got rejected.

I tried `conan remote clean`, and then add it back, still does the same thing: using old username and password!..

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Try:

```
conan user --clean
```
