### ISSUE TITLE
[bug] Data from user_info_build not forwarded in generators

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#7448]
Unfortunately I cannot find the data from `user_info_build` in `conanbuildinfo.json` for example. My assumption is that the appropriate handling is simply missing in the generators. See #7247 and PR #7266 for history.

**Comment by jgsogo** [comment]
This is to be implemented on top of https://github.com/conan-io/conan/pull/7488 when `1.28.1` is merged to `develop` branch.
