### ISSUE TITLE
[question] Setting options for your dependencies

### ISSUE THREAD

**Issue by skgbanga** [conan-io/conan#7452]
Hello,

I think my question is similar to #5726, but not exactly same. 

Consider a base package `Base` which exposes an option `fPIC`. 

I am the author of a project called `MyProject` which depends on `Base`. So my conaninfo.txt looks like this:

```
[requires]
Base...

[options]
Base:fPIC = True

[generators]
cmake
```

Everything works correctly so far.
Now, I make a conan package for my project `MyProject` and expose `fPIC` option as well. 

My clients want to use my package now, and their conaninfo.txt looks like this:

```
[requires]
MyPackage...
SomeOther...

[options]
MyPackage:fPIC = True

[generators]
cmake
```

However, this will result in an error since my clients also have to specify `Base:fPIC = True`. The solution suggested in #5726 is to use *, but my client could be depending on a lot of libraries and I don't want them to enable fPIC for all of them. I only want that "if my library is given fPIC, my dependants should be passed that options as well" without clients knowing what all dependencies do I depend on. 

Does my question make sense? (I tried looking at https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#options to see if I can get some info, but couldn't find anything). Let me know if something is not clear.

**Comment by memsharded** [comment]
Hi @skgbanga 

Sorry for the late reply, it has been busy trying to release Conan 1.28.

I think what you might be looking for is the following:

```python
class MyProject(ConanFile):
     requires = "Base/...."
     options = {"fPIC": [True, False]}
     ...
     def configure(self):
          self.options["Base"].fPIC = self.options.fPIC
```
This will propagate transitively the current fPIC value to the upstream "Base" dependency. Be aware that this is a strong definitions, and if other package that depends on "Base" tries to define the ``fPIC`` option to a different value, that will be a conflict and it will raise an error, and would require fixing the conflict.

Please let me know if this helps. Thanks!

**Comment by skgbanga** [comment]
@memsharded I will try this solution and let you know. I am closing the issue for now. (will reopen if it doesn't work)
