### ISSUE TITLE
[feature] Update package remote when uploading

### ISSUE THREAD

**Issue by puetzk** [conan-io/conan#7456]
To control our dependencies, we keep the conan-center usually disabled in our conan config, and copy recipes which we intend to use (and binaries built with the desired profiles) onto our own enterprise artifactory instance. However, after doing this, the instance that did the builds will still have the recipe in its cache with the remote set to conan-center.

This can be changed with `conan remote update_ref`, but that makes it into a two step process, and it is somewhat easy to forget.

I would like to ask for the `conan upload -r <remote>` to get an `--update_ref` option, which would update the ref of the just-uploaded binaries to now consider the location they were just uploaded to as the upstream remote. `conan upload` already sets set the remote if there isn't one: https://github.com/conan-io/conan/blob/d67545c1cff4853c44f8c979eeb6bf4819614f34/conans/client/cmd/uploader.py#L327-L329 
so this is not entirely novel behavior. I would just like an (optional, off-by-default) way to tell it to overwrite it even if already set, for this use case of internalizing recipes we have rebuilt. I look at this as being somewhat analogous to `git push --set-upstream`. It's something you can already do (in both cases), but doing it in two separate commands means you have to specify the reference(s) twice, and offers the chance to mismatch them (or other mistakes, e.g. do update_ref even if the upload failed) that leave the cache out of sync with reality. Combining it would be convenient and slightly less mistake-prone.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @puetzk 

Let me understand a couple of things:

- Why are you concerned about defining this value? Are you using it for later --updates?
- Wouldn't it be good to do the updates explicitly, specifying ``--remote``?
- Are you using revisions already?
- Are you reusing the cache of the job that uploads the package to your Artifactory? If you used clean caches in those jobs, then it wouldn't be an issue, would it?

We are probably going to remove the usage of remote information in Conan 2.0, and updates will be remote independent. I would like to understand better the pain to start thinking in the right direction for Conan 2.0.

Regarding the feature request, it doesn't seem difficult but it seems a bit too ad-hoc, if possible I would like to do a step towards something as close as the Conan 2.0 behavior as possible.

**Comment by puetzk** [comment]
> Why are you concerned about defining this value?

Only because I do not want it to remain pointing to conan-center - I want to pull in updates from there only explicitly. When I do use --update against our internal artifactory, and I don't want that to go pull a bunch of conan-center stuff because I forgot where things were pointed. 

Also, I generally keep conan-center disabled unless intentionally downloading updates. If the package in my local cache (that I uploaded into our artifactory) still points back to conan-center, it gets disabled too when I do that, even though it's on our artifactory (and since it's already in my cache, conan won't even go looking, it just errors out on the disabled package). Then I have to remember this issue, and go look up the fairly exotic `remote update_ref` in the docs to fix it. 

So this is pretty much purely about CLI ergonomics, and a paper cut annoyance that I had hit enough times that I decided to ask :-)

> Wouldn't it be good to do the updates explicitly

Absolutely.

> Are you reusing the cache of the job that uploads the package to your Artifactory?

Usually I do the process of `conan remote enable conan-center; conan download --recipe foo` (review new recipe) `conan upload -r artifactory foo; conan disable conan-center` manually , and then let CI talk only to our artifactory. So its my (or another human's) local cache that has a stale remote association.

> We are probably going to remove the usage of remote information in Conan 2.0, and updates will be remote independent

That would be an entirely satisfactory solution to the problem. It's the stale association that I want to be rid of. If there was no association stored at all, there would be nothing that needed updating; when the conan-center remote was disabled what I built in my cache (and uploaded) would remain usable, and --update would presumably search (all of?) the enabled remotes.

**Comment by puetzk** [comment]
Closing this since it's not going to change in 1.x and isn't relevant to 2.x
