### ISSUE TITLE
[feature] Don't Force Cache of Source Folder

### ISSUE THREAD

**Issue by jaredkeithwhite** [conan-io/conan#7457]
I feel that we need a configuration option that will always fetch sources during package create, if the user desires the source files to be updated.  Right now I may resort to something like:

`    def configure(self):
        source_dir = os.path.join(os.environ["HOME"], ".conan", "data", self.name, self.version, self.user, self.channel, "source")
        tools.rmdir(source_dir)
`

To ensure that the source() function is invoked, in the event that my conan recipe hasn't changed.  It seems counterintuitive to me that the defining edge of when we re-invoke source() is the fact that my conan recipe has changed, particularly since we are admonished to avoid altering source() in our conan recipe at all costs!

Further, I think the default should be cache=False, with the ability to turn it on as needed. 

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jaredkeithwhite 

For this use case, the recommendation is to use the ``build()`` method. That will make sure you get a clean download everytime. The ``source()`` mechanism is just an optimization when you want exactly this caching behavior of the sources, that must be common to all builds.

Please let me know if this makes sense. Thanks!

**Comment by jaredkeithwhite** [comment]
Ah!  Very nice, that is what I was looking for.  Thank you.

**Comment by memsharded** [comment]
Great to know. Yes, the idea is that every new package creation or build from source, will completely wipe the "build" folder in the Conan cache, and call the ``build()`` method again, for that configuration. On the other hand, the ``source()`` method is only called if the "source" folder (common to all different packages) does not exist. Hope this clarifies the issue, I think it is resolved now, closing it, but do not hesitate to re-open or post a new issue if you have any further question. Thanks!
