### ISSUE TITLE
[feature] provide optimization or alternative to conan export command

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#7466]
In summary, for monorepo use cases in which users are developing multiple components/packages at once, users often want a single top-level command or script which will re-build all the change components/packages with conan.  

This is currently possible.  Unfortunately, it has a performance drawback which is increasingly prohibitive with the scale of the codebase.  That flow is simply to run `conan export` on every component/package in the tree and then run `conan create` with `--build outdated`.   However, the downside is that `conan export` unconditionally performs a file copy of all sources and exports, even those which have not changed.  This file copy is what is prohibitive with scale. 

There are multiple ways to improve the situation.  The two suggested here are: 
1. add a flag to conan export which only copies changed files
2. provide a new command which simply returns 0 or 1 depending on whether or not sources changed. Don't do the copy.  This should be relatively easy to implement safely since I'm pretty sure exports and exports sources start by creating a list of the files it will copy before it copies them.  If so, then that list could be used to simply hash the files in place and determine if that's checksum represents a new revision or not. Should be the same result as running the checksum calculation over the files in cache after a copy. So, decouple into two functions and expose the "list" and "hash-in-place" step via a new command .

Conceptually, there's a very clear overlap here with what build systems are designed to do: detect changed sources, and only rebuild the minimum.  Just worth noting. 

I would probably favor the first option.  Then users can just do `conan export` with the new flag and then do `conan create --outdated` and conan would use it's existing mechanism to only build the things that were needed.  With the second option, users have to perform the comparison and run conan create command themselves. Would still work. 

Note:
@memsharded is already aware of this concept and the need.  Per our discussion, it's not necessarily a priority at this time, but I'm making a feature request issue so that other people can upvote if it's relevant to them.  

Alternatives (workspaces):
Local developer workflows still have challenges. We're continuing to work on and plan for several major features to improve these flows but they're taking longer than expected (workspaces, editable, layouts, etc.).  When those features are mature, they will solve this problem in a more holistic way.  However, in the meantime, users still have to engineer local workflows with the features that are stable. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Anything that requires a "diff" or the comparing something local against something in the cache might be impossible, specially if using revisions:

A recipe revision is based on the hash of the contents that is there. If there are local changes, that will generate a new revision. The new revision is not known until all files have been exported and hashed. 

In the best case, this would still be extremely slow.


I'd say there could be a third approach, and the one I would try to investigate: The scm approach: do not export anything into to local cache, only the coordinates of the SCM to be able to reproduce later if necessary. I know this also has challenges, like the SCM changing value even if the given subfolder or package didn't change. Don't know how to solve it, just saying that this is an idea that we should have a look too.
