### ISSUE TITLE
[bug] PKG_CONFIG_PATH from AutoToolsBuildEnvironment is not winbash compatible

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7469]
Currently, when using the pkg_conf generator with the AutoToolsBuildEnvironment,
windows paths are used in the PKG_CONFIG_PATH environment variable.

When using the `pkg_conf` generator, this causes `PKG_CONFIG_PATH` to be defined as:
`PKG_CONFIG_PATH='C:\Users\maarten\.conan\data\libusb-compat\0.1.7\_\_\build\ec6e396fb18bc2299d9ae033be6cad9af083007d:/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig'` (extracted from `config.log`)

Note the backward Windows slashes in the first path.
It should replace all backward slashes with forward slashes, or use a unix_path.

As a workaround, I currently run autotools.configure as:
```python
pkg_config_paths = [tools.unix_path(self.install_folder.replace("\\", "/"))]
self._autotools.configure(..., configure_dir=self._source_subfolder, pkg_config_paths=pkg_config_paths)
```

Code reference:

https://github.com/conan-io/conan/blob/770602e142e3fd15eb25f5eff8ba3832be7bcd44/conans/client/build/autotools_environment.py#L163:L171

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2017 
  * Conan version: 1.27.1
  * Python version: 3.8.5

**Comment by memsharded** [comment]
Sorry this was not responded back then @madebr 
Now this ticket is a bit outdated, AutotoolsBuildEnvironment does not exist anymore, deprecated in Conan 1, removed in Conan 2. Closing as outdated, please create new tickets if necessary.
