### ISSUE TITLE
[question]  How to use conan components with cmake?

### ISSUE THREAD

**Issue by 0x4d0x4b** [conan-io/conan#7476]
I have tried to use conan components with `cmake` generator, but `conanbuildinfo.cmake` did not contain any targets or references pointing to components.
After browsing conan's source code I came into conclusion that `cmake_find_package` genrator has to be used to make components work.
Is it correct and expected behaviour? Are there any plans to expand component functionality for a plain `cmake` generator?
I apprciate it is an experimental feature, but I was not able to find anything in documentation that would suggest only speific generators are supported.
```
Conan version 1.28.0
cmake version 3.18.0
```

For a specific example and a bit more context on my use case, please refer to my other question https://github.com/conan-io/conan/issues/7475

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Hi @kajdam ! 

Yes, you are correct, `cmake_find_package` and `cmake_find_package_multi` are used with components. About `cmake` package, it can be used together to other generators, they are different things, so there is not reason for including it cmake.

If you check Conan Center Index, it's a common approach. For instance: https://github.com/conan-io/conan-center-index/blob/master/recipes/openssl/1.x.x/conanfile.py#L714

**Comment by 0x4d0x4b** [comment]
@uilianries Thanks for clarifying that `cmake_find_package` and `cmake_find_package_multi` are the way to go with components.

I did not quite get the part about plain `cmake` generator though.
Could you elaborate more why it is not supporting components at the moment, please?

For example if I were to use an `openssl` you linked in your reply in my consumer's package `conanfile.py` I would be forced to use
```
generators = "cmake_find_package"
```
followed by
```
find_package(OpenSSL)
```
in my `CMakeLists.txt`

Why use of
```
generators = "cmake"
```
with
```
include(${CMAKE_CURRENT_BINARY_DIR}/conanbuildinfo.cmake)
```
in `CMakeLists.txt` is not supported?

It would be just a matter of changing implementation of plain `cmake` generator to generate targets for components in `conanbuildinfo.cmake`
Why would that be an issue?

**Comment by uilianries** [comment]
>  Could you elaborate more why it is not supporting components at the moment, please?

https://github.com/conan-io/conan/issues/6718#issuecomment-637447985

> in CMakeLists.txt is not supported?

No. When you use ONLY `cmake` generator, CMake will consume the FindOpenSSL.cmake from your system. But again you can use both `cmake` and `cmake_find_package` together, not because the Find file, but set all correct settings according your Conan profile.

Please, read the issue https://github.com/conan-io/conan-center-index/issues/787 which contains more details about.

**Comment by 0x4d0x4b** [comment]
Thanks @uilianries 
https://github.com/conan-io/conan/issues/6718#issuecomment-637447985 clarifies it all i.e. that `cmake_find_package/_multi` and `find_packages()` are they way forward which I am happy with, but wanted to have clarity on that.
I would suggest to update the documentation to clearly state that those generators are correct way to work with components using cmake

**Comment by memsharded** [comment]
This ticket is about legacy (removed in 2.0) generators like ``cmake`` and ``cmake_find_package``. Closing as outdated, please create new tickets to report against ``CMakeDeps`` and ``CMakeToolchain``. Thanks!
