### ISSUE TITLE
[question] When are conan components expected to become part of official, stable API?

### ISSUE THREAD

**Issue by 0x4d0x4b** [conan-io/conan#7477]
I am really keen on using conan as **the** package manager for my team's production code.
However, I am not a big fun of linking all libraries from multi-library dependencies (this can cause problems described https://github.com/conan-io/conan/issues/7475)
Because of that I welcomed introduction of components into conan, but I have been wondering when it is expected for them to become a part of an official API as at the moment they have got an experimental status.

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @kajdam 

Well, the ``components`` feature is pretty new, it is still getting support in the ``generators``, not all generators have learned to support components yet. So it seems it will take a while, I don't expect them to be declared stabled soon.

The good news, is that the most important piece, which is the declaration of components in the ``package_info()`` method will become de-facto stable quite soon, as it has happened with other features. Widespread adoption, and becoming very popular in recipes in ConanCenter will make very difficult to break that syntax in the feature, and breaking changes will be drastically minimized, if any. We might declare stable that declaration only, as we did with the recent stabilization of the SCM feature, but only when it is using the ``scm_to_conandata`` approach. Experimental things don't break that often, only when we are really convinced that the benefit outweighs the inconvenience (like with the Conan 1.28 lockfiles). I think it is relatively safe to start using components now, I cannot guarantee, but I don't think they will get a big and painful breaking change.

**Comment by 0x4d0x4b** [comment]
Thanks @memsharded 
Adoption of `components` in ConanCenter recipes is reassuring.
We might start using `components` API too, once we know how to deal with a problem described in #7475 i.e use of individual `components` in non-components package.
