### ISSUE TITLE
[question] create only shared or static library

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7478]
I have a recipe for a library called PCL that i set the option.shared to be False then built it, but still get shared libs. 
This also happens for a widely used library called flann. When i run `conan install flann/version@ -o flann:shared=False` it still creates both .so and .a libs. i check the recipe and could not figure out why. 

I 've enclosed the pcl lib recipe here: 
[conanfile.py.txt](https://github.com/conan-io/conan/files/5012523/conanfile.py.txt)
and the flann lib recipe here:
[conanfile.py.txt](https://github.com/conan-io/conan/files/5012527/conanfile.py.txt)

is there another hidden parameter that controls the created lib format?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @shelper 

I see in the PCL recipe that the shared libs is hardcoded:

```python
    def build(self):
        cmake = CMake(self)

        cmake.definitions["PCL_SHARED_LIBS"] = "ON"
```

Conan manages to set ``BUILD_SHARED_LIBS``, which is the standard CMake variable, to the right value. But if the PCL ``CMakeLists.txt`` doesn't follow the convention, then you need to adapt. Probably something like:

```python
    def build(self):
        cmake = CMake(self)

        cmake.definitions["PCL_SHARED_LIBS"] = "ON" if self.options.shared else "OFF
```

**Comment by shelper** [comment]
awesome, thanks!
