### ISSUE TITLE
[question] How to inject ANDROID_ABI, and use the NDK and toolchain file provided by Android?

### ISSUE THREAD

**Issue by kheaactua** [conan-io/conan#7484]
I see that in [!4538](https://github.com/conan-io/conan/pull/4538), [cmake_flags.py](https://github.com/bincrafters/conan-android_ndk_installer/blob/4c98a5c87f76feaa1be9693064d72a61cc562278/conanfile.py#L183) was augmented to set the `ANDROID_ABI` definition in CMake.  But code only applies this if a toolchain file is not provided.

My problem is that I'm using the CMake toolchain file provided in the NDK (and using a per-existing NDK), however it requires `ANDROID_ABI` to be set externally (before it).  Thus, I have no way to supply `ANDROID_ABI` to the toolchain file, and then it just assumed armv7.

Is there a different way to inject `ANDROID_ABI`?  Or can`cmake_flags.py` be modified to set the `ANDROID_ABI` definition before checking if there's a toolchain file?  Because the one from the NDK - if given `ANDROID_ABI` does a lot of the heavy lifting.  I could drop using the NDK supplied toolchain file in favour of relying on conan to get the values right, but (no criticism of conan here) it feels like depending on Android for the NDK toolchain file is more sustainable.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
In https://github.com/conan-io/conan/pull/8749, merged and ready for Conan 1.36, the integration will define the path of the NDK and the CMake toolchain from it will be automatically used. Variables like ANDROID_ABI will be defined by the ``conan_toolchain.cmake`` that defines these variables, then includes the Android NDK Cmake toolchain. The ``CMakeToolchain`` Android block will have the configurability to control these variables too.

So I think this issue can be considered solved by that PR. Keep tuned for the release and the documentation, thanks.
