### ISSUE TITLE
[bug] Cmake targets glue C and CXX flags

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#7499]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04 in docker
  * Compiler+version: GCC 9.3 and GCC 9.2 cross for arm
  * Conan version: 1.28.0
  * Python version:  3.8.2

### Steps to reproduce (Include if Applicable)
  1. Make package with CXX specific flags, eg. -fno-exceptions, -fno-rtti
  2. Use cmake generator with target aproach and link that package to your target.
  3. Enable languages: C and C++ and add one .c and one .cpp file
  4. Compile using cmake

### Logs (Executed commands with output) (Include/Attach if Applicable)
`[build] cc1: warning: command line option '-fno-rtti' is valid for C++/D/ObjC++ but not for C`

### Possible solution:
There are lines for every target in conanbuildinfo.cmake:
```
set_property(TARGET CONAN_PKG::PACKAGE_NAME PROPERTY INTERFACE_COMPILE_OPTIONS ${CONAN_C_FLAGS_PACKAGE_NAME_LIST} ${CONAN_CXX_FLAGS_PACKAGE_NAME_LIST}
                                                                  $<$<CONFIG:Release>:${CONAN_C_FLAGS_PACKAGE_NAME_RELEASE_LIST} ${CONAN_CXX_FLAGS_PACKAGE_NAME_RELEASE_LIST}>
                                                                  $<$<CONFIG:RelWithDebInfo>:${CONAN_C_FLAGS_PACKAGE_NAME_RELWITHDEBINFO_LIST} ${CONAN_CXX_FLAGS_PACKAGE_NAME_RELWITHDEBINFO_LIST}>
                                                                  $<$<CONFIG:MinSizeRel>:${CONAN_C_FLAGS_PACKAGE_NAME_MINSIZEREL_LIST} ${CONAN_CXX_FLAGS_PACKAGE_NAME_MINSIZEREL_LIST}>
                                                                  $<$<CONFIG:Debug>:${CONAN_C_FLAGS_PACKAGE_NAME_DEBUG_LIST}  ${CONAN_CXX_FLAGS_PACKAGE_NAME_DEBUG_LIST}>)
```

Those lines should be changed to use additinal generator expression: `<$<COMPILE_LANGUAGE:(CXX|C)>`, eg.

```
set_property(TARGET CONAN_PKG::PACKAGE_NAME PROPERTY INTERFACE_COMPILE_OPTIONS (
    $<$<COMPILE_LANGUAGE:C>:${CONAN_C_FLAGS_PACKAGE_NAME_LIST}> 
    $<$<COMPILE_LANGUAGE:CXX>:${CONAN_CXX_FLAGS_PACKAGE_NAME_LIST}>
    $<$<CONFIG:Release>:
        $<$<COMPILE_LANGUAGE:C>:${CONAN_C_FLAGS_PACKAGE_NAME_RELEASE_LIST}> 
        $<$<COMPILE_LANGUAGE:CXX>:${CONAN_CXX_FLAGS_PACKAGE_NAME_RELEASE_LIST}>>
    $<$<CONFIG:RelWithDebInfo>:
        $<$<COMPILE_LANGUAGE:C>:${CONAN_C_FLAGS_PACKAGE_NAME_RELWITHDEBINFO_LIST}> 
        $<$<COMPILE_LANGUAGE:CXX>:${CONAN_CXX_FLAGS_PACKAGE_NAME_RELWITHDEBINFO_LIST}>>
    $<$<CONFIG:MinSizeRel>:
        $<$<COMPILE_LANGUAGE:C>:${CONAN_C_FLAGS_PACKAGE_NAME_MINSIZEREL_LIST}> 
        $<$<COMPILE_LANGUAGE:CXX>:${CONAN_CXX_FLAGS_PACKAGE_NAME_MINSIZEREL_LIST}>>
    $<$<CONFIG:Debug>:
        $<$<COMPILE_LANGUAGE:C>:${CONAN_C_FLAGS_PACKAGE_NAME_DEBUG_LIST}>  
        $<$<COMPILE_LANGUAGE:CXX>:${CONAN_CXX_FLAGS_PACKAGE_NAME_DEBUG_LIST}>>)
```

I haven't check it yet but I use this expression to set rtti flags in cmake project and it works correctly:
```
   add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>)
   add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>)
```

**Comment by memsharded** [comment]
Hi @pgorgon-hem 

Thanks for reporting this issue.
Just to understand the severity of the issue, what is the typical effect, just that warning, but the flag is safely ignored by the compilers? Does it fail in some scenarios?

This might need to be changed in other generators as well. As it seems this code section is getting some complexity and would be error prone, I wonder if this could be templatized.

**Comment by ghost** [comment]
Hi,
The typical effect is just warning and flag is safety ignored by gcc, but I've tested it only with gcc 9 and -fno-rtti and -fno-exception flags. I don't know how it behaves with other compilers and other flags. But I can imagine that some build parameters for c and c++ objects might be different and can't link when flags set wrongly. Eg. I have external library packaged with conan. This library is also distributed for embedded targets (compiled without RTTI) and when I link that library to my executable it can't find typeinfo for objects from library, so I need to add -fno-rtti to my executable compilation to link it properly. Because I'm always traying to achive no warnings in compilation I added these flags manually in my cmake (for whole project).

This fragment of cmake code is from [conan/conans/client/generators/cmake_common.py:203](https://github.com/conan-io/conan/blob/74548ddf0a3eabf87cdc7f1e9e38a238ed16667a/conans/client/generators/cmake_common.py#L203). This file is included in every cmake generator, but it is used in generate_targets_section method which is used in CMakeGenerator and CMakeMultiGenerator, so I think it have influence on cmake and cmake-multi generators only. 

I thought about making fix of that by myself but I have only little experience in conan so I can't predict all effects of changes.

**Comment by danimtb** [comment]
After some tries to improve this issue here https://github.com/conan-io/conan/pull/7600, we have come to the conclusion that the generator expression to inject C or CXX flags correctly is not supported on Visual Studio generators as CMake is still not able to set a compile language per compilation unit. I have also tried to set the flags depending on the project language declared by the consumer but it is a workaround and fragile fix.

The only thing we can do at this point is to separate the flags into two variables and let the consumers apply them at their wish. I will update the PR with the changes

**Comment by memsharded** [comment]
Hi @pgorgon-hem 

https://github.com/conan-io/conan/pull/7600 has decoupled the cflags and cxxflags into 2 different variables, but they are still applied in the same way, due to CMake bug as commented here: https://github.com/conan-io/conan/pull/7600#issuecomment-682027143. When CMake addresses this thing we might reconsider, but at the moment it is not a viable solution, so we cannot do more regarding this issue.
