### ISSUE TITLE
Extend iOS version in settings.yml

### ISSUE THREAD

**Issue by sneik555** [conan-io/conan#7503]
Hi, 

could you please update settings for iOS? The newest version in settings.yml for iOS is 13.1. From [here](https://en.wikipedia.org/wiki/IOS_version_history) you can see that there are newer versions. I have to use 13.2 and this is not problem to edit locally my settings.yml, but if I do it all my clients have to do the same work.

Br,
Tomasz

**Comment by memsharded** [comment]
Yes, sure we can no problem. Also if you want to contribute that change yourself (might require a change in a migration file too), feel free.

**Comment by memsharded** [comment]
> I have to use 13.2 and this is not problem to edit locally my settings.yml, but if I do it all my clients have to do the same work.

Regarding this, if you have custom settings.yml, you can easily share them and make all your clients use them (together with profiles, remotes, conan.conf), with ``conan config install``, please have a look at it: https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install

**Comment by memsharded** [comment]
Merged #7507 this will be available next Conan 1.29
