### ISSUE TITLE
[question] Forcing generators to be executed on deploy without using command-line-argument

### ISSUE THREAD

**Issue by fredericbloch** [conan-io/conan#7505]
Hey guys!

i'm trying to implement some packages, where I need some generator to create/edit some files/dirs within the deploy-stage. The problem is: I'd really like the generator to only be executed during the deploy on the client on which the package is installed on. So as far as I know adding a "generators = [testGenerator, <...>]" as an attribute won't do that. Which will do the trick is adding it to the install command as "conan install <...> -g testGenerator". But therefore I have to know what the generator is called like, even though I might not have looked into the recipe at that point (or do not remember the name).

So what I'd like to do is add something like this within the conanfile.py:
```
    def requirements(self):
        self.requires("testGenerator/<>@<>/<>") # make sure its in the requirements
    
    <...> # do stuff
            
    def deploy(self):
        self.generators("testGenerator") # execute generator right here
```

I couldn't find anything similiar within the docs. The particular reason for this method is: I would have e.g. 50 pkgs which are all supposed to use the generator on install/deploy. So just copying the code into deploy() for each recipe is obviously quite unhandy.

Also: The same goes for the virtualenv/virtualrunenv generators, which I need to add to my cmd. So it gets pretty long e.g. "conan install <...> -if <install-folder> -g virtualenv -g virtualrunenv -g <...>". You see where I'm going with this. I've seen things like, which I could not get to work properly:

```
from conans.client.generators.virtualenv import VirtualEnvGenerator
VirtualEnvGenerator(self.conanfile)
```

Any ideas on calling those standard-generators from inside the recipe as well?

Thank you for any tips or ideas you might have! :)

**Comment by jgsogo** [comment]
Hi! I'm, not sure if I'm understanding your use-case, but let me comment a couple of approaches, see if they are somehow useful and we can keep working with you.

---

We are working on a new step for the `conan install` command, it will copy the package downloaded to the server to a different folder in the cache where a `deploy()/package_install()` function would be able to modify those files in the consumer machine. It is still a PR, a concept, but it is worth considering (https://github.com/conan-io/conan/pull/7313).

---

Another approach could be to add all those packages to a `conanfile.txt` and list the extra generators you need:

```ini
[requires]
pkg1/...
pkg2/...

[generators]
testGenerator/...
otherGenerator/...
```

and then run `conan install conanfile.txt`, it will use those generators for all the requirements.

---

If the pain is about modifying all the recipes to add a `deploy(self)...` function, maybe you can inherit all the recipes from the same base python class. You can achieve this easily [using `python_requires`](https://docs.conan.io/en/latest/extending/python_requires.html#python-requires) (there is one example about inheritance).

--- 

Do some of these approaches work for your use-case?

Thanks!

**Comment by fredericbloch** [comment]
Hey Javier!

thanks for the quick answer. I'd been thinking about using the python_requires for this. The issue is - I would not retrieve e.g. all 50 packages at once and run the generator -  but I would use only one of them at a time. So I would use the conan install on a single package with the command-line-generator-argument attached.

Your suggestion would make I'd have to create/edit the conanfile.txt for each project and do a conan install on top of it additionally. So even though that is kind of a solution, I won't try that.

The new feature is pretty nice though! 👍 (I gotta stick to Conan 1.16 though for quite some time)

The idea using python_requires would fit my use-case pretty well. I've used this is extend my recipes with methods that I'd use on a regular basis. But I'm not quite sure if I could use that whilest not changing the generator I designed. So since you brought it up, I tried it and it's not pretty, but it seems to work:

```
gen1 = python_requires("test_generator/version@user/testing")

class testPkgConan(ConanFile):
    <...>
    
    def package(self):
        pass
            
    def package_info(self):
        # running in pkg_info()
        gen = gen1.testGen(self) # could run it here
        gen.content

   def deploy(self):
        # running in deploy()
        gen = gen1.testGen(self) # or here
        gen.content
```
With the generator being like this:
```
class testGen(Generator):
    def __init__(self, conanfile):
        self.conanfile = conanfile
    
    @property
    def filename(self):
        pass
    
    def generatorContent(self):
        <doing stuff>
    
    @property
    def content(self):
            <doing stuff here>
            self.generatorContent()
            <doing more stuff here>
        
        result = {} # generator needs result in content
        return result
    
class testGeneratorConan(ConanFile):
    <...>
```

So I might proceed into this direction. As far as I can tell, calling the class with self instead of ConanFile even makes it possible to go through dependencies within the generator. So that's pretty nice, even though I'm not sure, if I might overlook something, so that the Generator-Functionalities might not work. The very cool thing is - this way I can use the generator both ways, without adapting it.

Just to clarify my use-case again: Essentially it's just adding the generator-execution to the recipe to

1. not having to type in the command-line-option everytime and therefore knowing what the generator is called like
2. being able to set up the ordner of execution of multiple generators like this (because of the stuff I do, it might be necessary to do this in future projects)

So in case you see me doing anything harmful, please give me hint. Otherwise thanks for the input and giving me the hint to use python_requires.

**Comment by jgsogo** [comment]
Hi! Even if this works for you... I feel like you are walking the edge as you are abusing some principles.

First of all, quick comment, those python_requires are deprecated in favor of the new ones, I know you are in `1.16`, but new ones have many advantages (and new Conan versions have new cool features 🙄 ). I strongly suggest you upgrade Conan... if we can help, let us know.

Generators are intended to create files with information from the requirements (not from the recipe itself). You can see it when you run `conan install <path/to/conanfile.py>` that it creates files only for the requirements and, when you run `conan install <reference>` then the reference is the requirement itself and it is the reason why Conan generators create the files for it.

In your example you are not using a generator the way we think about them, in fact you are just creating an object from a class that derives from `Generator` and calling the method/property `content`. It might be convenient for you, but you can get the same results without deriving from `Generator`, even using a plain function and it will be safer (and cleaner):

Your python_requires could be like this, if you are running that source always from a method in the recipes:

```python

def testGen(conanfile):
    <do your stuff>
    result = {...}
    return result
```

Where to run that method? It depends on what you are trying to achieve, I would need more details to know if `deploy()` method is ok, or you would need future `package_install()` one. I still don¡t understand the type of files you are trying to generate and what do you use them for.

**Comment by memsharded** [comment]
Hi @blockontherocks 

Let me summarize our current way of thinking and the direction Conan is heading regarding generating files:

- Conan generators will manage exclusively information from dependencies: includedirs, libdirs, library names, etc. Generators create files like ``FindXXX.cmake``, to be used by build systems to locate and use deps.

- The ``toolchain()`` feature is intended to create files with information of the build of the current package, typically taking information from Conan settings like compiler and architecture, and creating toolchain files, that can be used like cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake. This will not model information from dependencies. Thisis already available: https://docs.conan.io/en/latest/creating_packages/toolchains.html

- The ``package_install()`` will be a place to do post-processing of installed packages. Some libraries and tools have complicated post-setup steps that can be local to the current machine, and need to update things using absolute paths in the current machine. This is just an idea, not available yet.

Learning a bit more about the file that you want to generate (as it doesn't seem a conventional generator of information from dependencies) would be helpful to understand better your use case. Many thanks!

**Comment by fredericbloch** [comment]
Well let me clear this up right up front - yes, it is absolutely walking the edges and abusing some priciples. I am aware of that. Also: I wish I could upgrade, but sadly that will take some time due to some restrictions. Hopefully that will happen pretty soon though.

So what I'm doing within the generator is not anything you designed generators for: The issue are two tools, that have to work with each other, but one of them does not allow files outside of its own absolute file-system. So I have to automate the insertion of the tool into the other, due to path-restrictions. I automate that by running a python script. So thats kind of setting up a dev-environment, and these tools are also delivered as conan-packages. So I could just call the python script manually, within the package_info() or in the deploy(). I was doing the last thing, because it made the most sense to me. Obviously I would have to call a method/script directly and hand all conan-related-info to it. So to avoid that, I would just design a generator (which would have all the related informations) and run basically the same thing as in a script/method, but without having the specify the method inside of the recipe - which would made me having to maintain these lines of code - which I do not want to do.

Now: As these tools are set up with each other, I would give even more packages with actual data to them (thing of is as data, paremeters, traces, ...). These packages would not contain any binaries/libs whatsoever, but you might see them as "resource packages" with would only deliver data to get a fully-configured dev-system. I would do similar things with another generator (or method/script) to get those into this dev-system.

So far so good, everythings works pretty nicely this way. Every package can be completely independed from each other, I could declare pretty cool stuff within the package_info() with user_info and env_info to keep the generator running - even if anything changes within the generator. Also I would not have to change version or the build of these "tooling-recipes" - but only in the generators (which would be used on numerous of those "resource packages").

Writing this, I see that you guys must be going absolutely nuts, since Conan is not designed to do this. But - it works pretty darn good. The issue I was having, was that with multiple of these generators, I would have to attach all of them to the conan-install-command. Conan would just run any of them in any order - without "respecting" the order within the command. (e.g. conan install <...> -g gen1 -g gen2 --> conan would randomly run one of those generators first at almost 50/50 chance, the other second. So that was what made me try to specify to running order of these generators, because logically to my use-case - I have to do certain things first, other things second.

I hope this clears up what I'm doing. I know this is not a way you designed generators to work - especially since I am not even creating files - but only manipulating some and make some copy/move/edit stuff. I could achieve the same thing, doing this within each package_info() or better deploy() but for some tasks it's been handy to move this logic to another package. Due to maintenance the decision was to "abusing generators" for this.

The new "package_install()" might be the exacty thing I will need in future versions of conan and I will definately use it as soon as it gets released and I'm able to upgrade. If you've got any more question, feel free to ask me. It is a very special use case and at absolutely no point I would expect you to cover it - I just wanted you to understand the intention of my question here.

**Comment by jgsogo** [comment]
Hi, thanks for taking the time to explain your use-case. As you say, it is very specific and we can only try to help you with your workaround and advice about how the features should be used. The main problem, and you are aware of it, is that, even if future releases of Conan keep the same philosophy, your workaround might break and you could need to implement it from scratch again abusing other principles.

If the `package_install` feature will work for you, you should adopt it asap, no one wants to be locked in version `1.16` while a new version `2.0` is being planned for the near future 😸 

I'm not sure if there is anything else to do in this issue, any action to take, bug, concrete issue or new feature to implement. Otherwise I'd close this issue.

Thanks!

**Comment by memsharded** [comment]
Closing as outdated. With Conan 2 there are several new tools, like user custom commands, deployers, custom generators in the cache, a new ``deploy()`` method, etc. 

Please create new updated tickets if necessary, thanks for your feedback.
