### ISSUE TITLE
Problems with uploading python-only-resued packages.

### ISSUE THREAD

**Issue by tru** [conan-io/conan#751]
I see this a lot: `ERROR: Cannot upload corrupted package 'plexconantool/1.0@plex/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9'` on our package that is reusable python code for other packages.

My theory is:
* Package is installed and checksum is calculated
* Package is used by other package which creates .pyc files
* User asks to upload package - checksum is calculated again and .pyc files are included
* Checksums mismatch and upload fails.

We should avoid including the .pyc files in the checksum calculation.

**Comment by memsharded** [comment]
Yes, the theory is fully correct. I will first add some failing test. Then the way to go should be to remove the .pyc before uploading the package, though this might have some side effects if by chance someone packaged .pyc (by accident, or on purpose). Maybe checking against the manifest.

**Comment by sourcedelica** [comment]
Should this fix be in 0.17.2?  I'm getting it for one flavor of a package (shared=True) on Linux.  I uploaded the same flavor on Macos and it worked ok.  Same Conan version in both places.

It's this one: https://www.conan.io/source/Protobuf/3.0.2/sourcedelica/testing.

**Comment by lasote** [comment]
@sourcedelica but Macos and Linux packages are different, so should not be related. I can't reproduce the error, could you paste some output and the error? If you don't upload the Macos version it fails too in Linux?

**Comment by memsharded** [comment]
Hi Eric, yes, this should be fixed so we'd need more feedback. Mainly the output of the error, but also if it is happening always, or just happened once (a single run) in Linux, did you retry after the error? Thanks!

**Comment by sourcedelica** [comment]
Yes - it happened after retries as well.  I got it to work by removing all
other flavors of that package from my local repo except the one I wanted to
upload.


-- Eric

**Comment by memsharded** [comment]
Yes, that is really weird, and seems no related at all with this issue, no idea of what could be happening. If you are able to reproduce it again, please try to save as much of state as possible, the output, even the local cache (``.conan/data/Pkg...``), before fixing it, so we can try debugging it. Thanks
