### ISSUE TITLE
[bug] Conan 1.28 seems to break qt/5.14.2@bincrafters/stable recipe

### ISSUE THREAD

**Issue by chubei-oppen** [conan-io/conan#7514]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04.4
  * Compiler+version: gcc 8.4.0
  * Conan version: 1.28.0
  * Python version: 3.7.7

### Steps to reproduce (Include if Applicable)
conan install qt/5.14.2@bincrafters/stable -b qt

### Logs (Executed commands with output) (Include/Attach if Applicable)
stdout:
[conan_qt.log](https://github.com/conan-io/conan/files/5033821/conan_qt.log)

stderr:
qt/5.14.2@bincrafters/stable: ERROR: Package 'c3f3f20c45e3079cce7c13faf8ee7065a09801b5' build failed
qt/5.14.2@bincrafters/stable: WARN: Build folder /home/chubei/.conan/data/qt/5.14.2/bincrafters/stable/build/c3f3f20c45e3079cce7c13faf8ee7065a09801b5
ERROR: qt/5.14.2@bincrafters/stable: Error in build() method, line 571
	args.append("\"%s_LIBS=%s\"" % (var, " ".join(self._gather_libs(package))))
while calling '_gather_libs', line 720
	libs += self._gather_libs(dep)
while calling '_gather_libs', line 715
	libs = ["-l" + i for i in self.deps_cpp_info[p].libs + self.deps_cpp_info[p].system_libs]
	KeyError: 'pgcommon'

**Comment by ericLemanissier** [comment]
this is https://github.com/conan-io/conan/issues/7474, it will be fixed with conan 1.28.1

**Comment by chubei-oppen** [comment]
Thanks for your quick response. Closing now.

**Comment by memsharded** [comment]
Everything is merged into 1.28.1, we will try to release asap, maybe today.
