### ISSUE TITLE
[bug] 'PackageOptionValues' object does not support item assignment

### ISSUE THREAD

**Issue by Yuri6037** [conan-io/conan#7518]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04 GitHub Actions
  * Compiler+version: GCC 4.9
  * Conan version: No idea
  * Python version: No idea

### Steps to reproduce (Include if Applicable)
```
    def configure(self):
        lst = ["jack", "sndio", "nas", "esd", "arts", "wayland", "directfb"]
        for v in lst: #Attempt at passing options
            self.options["sdl2-sys-require"][v] = self.options[v]
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
WARN: Remotes registry file missing, creating default one in /home/conan/.conan/remotes.json
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.7/lib/python3.6/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/opt/pyenv/versions/3.6.7/lib/python3.6/site-packages/conans/client/conanfile/configure.py", line 30, in run_configure_method
    conanfile.configure()
  File "/home/conan/.conan/data/sdl2/2.0.12/bp3d/stable/export/conanfile.py", line 112, in configure
    self.options["sdl2-sys-require"][v] = self.options[v]
TypeError: 'PackageOptionValues' object does not support item assignment
```

**Comment by Yuri6037** [comment]
In the mean time I will create one package per option

**Comment by lasote** [comment]
Hi @Yuri6037, the `option` object is a bit more complex, you could try something like this:

```
 def configure(self):
        lst = ["jack", "sndio", "nas", "esd", "arts", "wayland", "directfb"]
        for v in lst: #Attempt at passing options
            setattr(self.options["sdl2-sys-require"], v, self.options[v])
```

I wouldn't say this is a bug, the access to options and settings works that way.

**Comment by Yuri6037** [comment]
Why do you have to make things more complicated? And why cannot this be specified in the documentation?
Thanks anyways, but it's too late I already just expanded into 5 different packages for system requirements

**Comment by lasote** [comment]
> Why do you have to make things more complicated?

There is always a reason, as I told you, the options object is much complicated than a simple dict. Obviously we don't have any secret intention to do it more complicated (on purpose)

> And why cannot this be specified in the documentation?

Well, "bulk" assigning options of your dependencies in that way is not so common, typically you just `self.options["sdl2-sys-require"].myoption = 2`

We cannot cover every detail in the docs, but of course, the repo is also open source and open to contributions.

> Thanks anyways, but it's too late I already just expanded into 5 different packages for system requirements

Happy to hear you make it work!
