### ISSUE TITLE
[bug] module 'six.moves' has no attribute 'collections_abc'

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#7520]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows
  * Compiler+version: Visual Studio
  * Conan version: 1.28.0
  * Python version: 3.6.3

We got the error somewhere during `conan install`. I found `six.moves.collections_abc` in  https://github.com/conan-io/conan/blob/1.28.0/conans/util/misc.py. `collections_abc` was added to six in version 1.13 but conan currently depends on six >=1.5.

**Comment by lasote** [comment]
Hi! Thanks for reporting.
Yes, it looks like `collections_abc` was introduced in `six 1.13` but Conan requires `six>=1.10.0,<=1.14.0` not `>=1.5`, right?
Anyway it looks like we should adjust the range.

**Comment by memsharded** [comment]
Or we could replace:

```python
if isinstance(value, six.moves.collections_abc.Iterable):
#for something like
if isinstance(value, (list, tuple, set)):
```
It is not that critical to support any abstraction of Iterable for this case

**Comment by DoDoENT** [comment]
I've just got the same error with conan 1.28.1

**Comment by DoDoENT** [comment]
By manually upgrading `astroid` to 2.4.0 and six to 1.13, the problem got away.

**Comment by memsharded** [comment]
Does it make sense to backport #7545 to Conan 1.28.2, @jgsogo ?
