### ISSUE TITLE
[question] Building different conan packages on one machine 

### ISSUE THREAD

**Issue by sneik555** [conan-io/conan#7521]
Hi, 

I have question regarding building and using conan packages on one machine.

I have dedicated machine to run CI stuff on it and I have there downloaded conan packages which work with our master code.
Now, sometimes I have to change conan recipe, rebuild package, check if all tests on master works with this package and then upload this package to conan repository (and then I can use this package with my master CI jobs).

Problem is that during rebuilding packages someone can run CI job which:
- can brake master if package was wrongly rebuilded
- stuck on conan executing because package is rebuilding

I've tried to create virtualenv to manage two different environments, but unfortunately  as far as I see ~/.conan/conan.conf is common for all conan executables. 

**So, is it possible to have two(multiple) different conan storages on one machine and manage those storages parallel?**

I hope you understand my description :)

Br,
Tomasz

**Comment by lasote** [comment]
Hi @sneik555 

You can have different `conan caches` adjusting the environment variable [CONAN_USER_HOME](https://docs.conan.io/en/latest/reference/env_vars.html?highlight=conan_user_home#conan-user-home). Also if you are using Artifactory (the [CE](https://conan.io/downloads.html) is free and works like a charm) you can have multiple remote repositories, maybe one for development and one for staging/production etc, so yeah, you should be able to isolate your flow easily.

**Comment by sneik555** [comment]
Hi @lasote 

Thanks for quick response! I already managed virtualenv with CONAN_USER_HOME env variable.
Thanks for help.

Br,
Tomasz
