### ISSUE TITLE
[question] output of deps_cpp_info libdirs differs between 'conan create' and 'conan build'

### ISSUE THREAD

**Issue by pasrom** [conan-io/conan#7529]
I am facing a different behaviour, when following conanfile is executed with `conan create . test/testing` and `conan install . && conan build .` using conan version 1.27 and 1.28.
```
from conans import ConanFile

class testApp(ConanFile):
    name = 'test-app'
    version = "0.0.0"
    description = 'test app'
    license = "none"
    url = "none"

    def build_requirements(self):
        self.build_requires("zlib/1.2.11@conan/stable")

    def build(self):
        print("zlib libdirs" + str(self.deps_cpp_info["zlib"].libdirs))
```

1. With conan version <= 1.27 and `conan create . test/testing`  the output of the print is:
```zlib libdirs['lib']```
2. With conan version 1.28 and `conan create . test/testing`  the output of the print is:
```zlib libdirs['lib']```
3. With conan version <= 1.27 and `conan install . && conan build .` the output of the print is:
```zlib libdirs['/home/<user>/.conan/data/zlib/1.2.11/conan/stable/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/lib']```
4. With conan version 1.28 and `conan install . && conan build .` the output of the print is:
```zlib libdirs['lib']```

Which behaviour is the right one?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @pasrom,

Thanks for reporting.
I think the wrong behaviour there is for local methods before 1.28.0 but seems solved now.
Having a look at the [docs](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=deps_cpp_info#deps-cpp-info) `self.deps_cpp_info["zlib"].libdirs` should return the value as it was assigned in the recipe of the dependency in the `package_info` method, if you want the absolute path pointing to the cache you have to use `lib_paths`: `self.deps_cpp_info[“zlib”].lib_paths`
Hope this helps.

**Comment by pasrom** [comment]
Hi @czoido,

thank you for your quick respond and to point me to the right direction. I will close this issue.

Best regards,
pasrom
