### ISSUE TITLE
Build botan on Windows with msvc

### ISSUE THREAD

**Issue by dix75** [conan-io/conan#7531]
I am using botan 2.15 library with default settings.
MSVC Profile
```
[settings]
    os=Windows
    arch=x86_64
    compiler=Visual Studio
    compiler.version=16
    build_type=Release
[options]
[build_requires]
[env]
```

Botan builds into static library.
Using in cmake file 
```
include(build/conanbuildinfo.cmake)
conan_basic_setup(NO_OUTPUT_DIRS TARGETS)

target_link_libraries(${EXECUTABLE_NAME} {LIBS}
    Qt5::Widgets
    Qt5::Core
    Qt5::Gui
    CONAN_PKG::botan
)
```
Botan library compiles, but application always crashes. In my opinion, due to ABI incompatibility.
What am I doing wrong?

p.s. On Linux with gcc works fine.

**Comment by czoido** [comment]
Hi @dix75,

Can you provide more information on how it crashes? 
Are you using the precompiled package from conan-center?

**Comment by czoido** [comment]
Closing, please feel free to reopen if this is still an issue.
