### ISSUE TITLE
[feature] Use new semver 2.10.2

### ISSUE THREAD

**Issue by forry** [conan-io/conan#7532]
Hi,
would it be possible to use a new semver as a backend for the tools.Version in conan? Since I would like to use it separately for git tag parsing and version incrementing. Getting a new version (uninstalling old and installing new) broke the conans tools.
Also, it would be helpful to combine the two together for use in CI/CD pipelines since the original conan tool has implemented the loose parsing but one could not bump any version up (or am I wrong?).

Thanks
forry

**Comment by czoido** [comment]
Hi @forry,
Currently Conan is not using https://pypi.org/project/semver/ but https://pypi.org/project/node-semver/ under the hood for `tools.Version` so maybe that's why it broke?
Could you please explain further your use case and the need for semver 2.10.2?

**Comment by forry** [comment]
@czoido 
Ok, I didn't know that. In your doc you have:

> This is a helper class to work with semantic versions, built on top of semver.SemVer class with loose parsing.

So I went to google python semver. My bad. But sadly the import name is the same.
My use-case is simply the need for automatically bumping up the version number after the successful merge to our release branch (done by the pipeline). So the idea is to get the latest version tag, parse it and increment the version. Since I knew the conan is using some version tool (and we are using conan) I looked it up, but it can't bump the version automatically and another example on some blog suggested using the semver python package. I thought they were the same so I tried to just update it. I don't use python regularly so when pip said it updated it but I still couldn't get the functionality I uninstalled it (and then cleaned up manually) and installed it (the other semver) again not knowing that they are two different packages with the same source file name.

So now it's probably up to me to google how to use two packages with the same import name on one python installation. Or do you have any other suggestions? This isn't really my territory.

**Comment by czoido** [comment]
Hi @forry,

Although currently `tools.Version` does not offer a function to bump the version I think you could make this function using the `major`, `minor` and `patch` properties you have access to (check [docs](https://docs.conan.io/en/latest/reference/tools.html#tools-version)).

So, if I understand correctly, after the merge to the release branch you want to automatically bump the version in the conanfile using the latest tag from the branch? If that is the case you could set the `version` attribute in the [init](https://docs.conan.io/en/latest/reference/conanfile/methods.html#init) method using your custom bump function. Here is a snippet that may help you if that's in fact your use case:

```python
from conans import ConanFile, CMake, tools


class MylibConan(ConanFile):
    name = "mylib"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}
    generators = "cmake"
    exports_sources = "src/*"

    def _get_latest_tag(self):
        # retreive the latest tag from release branch
        return "1.0.4"

    def _bump_patch(self, version):
        return tools.Version("{}.{}.{}".format(version.major, version.minor,
                                               int(version.patch) + 1))

    def _bump_minor(self, version):
        return tools.Version("{}.{}.{}".format(version.major, int(version.minor) + 1, 0))                        

    def _bump_major(self, version):
        return tools.Version("{}.{}.{}".format(int(version.major) + 1, 0, 0))

    def init(self):
        latest_tag = self._get_latest_tag()
        version = tools.Version(latest_tag)
        new_version = self._bump_minor(version)
        self.version = str(new_version)

    ...
```

Also, please check the [python requires](https://docs.conan.io/en/latest/howtos/python_code_reuse.html) section in the docs to see how you can reuse all that Python code across your recipes.

We have a section in the documentation dedicated to [versioning](https://docs.conan.io/en/latest/versioning/introduction.html). Please, have a look, maybe using revisions could also fit your use case. Using revisions with a [package_id_mode](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html) such as `recipe_revision_mode` where recipe revisions change the package id downstream you can get some kind of automatic versioning without the need of bumping the version of your libraries (just using the latest revisions).

Please tell me if this helps and that's the way you'd like to set the version for your packages.

**Comment by forry** [comment]
Thanks for the idea. But my problem lies a little bit elsewhere, but this solution could be used, even though it has some problems with pre-release and build parsing.
I mainly wanted to use this outside of conan (in the CI/CD pipeline scripts to automatically generate and push git tags). But ofc in some cases you also want to automatically change the recipe version. In the CI/CD we could use the semver package but the import name is the same as node-semver and since we are using conan in the pipeline that seems to be the main problem. Also, it seems that the semver doesn't implement loose parsing, so the best would be to use them both somehow :(.
Regarding your example, I suppose that the automatic recipe changing could be done by the use of templates.

**Comment by czoido** [comment]
> Regarding your example, I suppose that the automatic recipe changing could be done by the use of templates.

What I meant is that when you have changes in your package source code or recipe using revisions a new revision of the package will be generated but the package version will stay the same. It can be useful depending on your versioning model, if you have to bump the version to integrate the changes of the library in its consumers, maybe instead of bumping the version of the library you could consume the latest revision of the same version. But in the end all will depend on how you want to version (this is also a great source of information for this topics: https://blog.conan.io/2019/09/27/package-id-modes.html).

**Comment by forry** [comment]
After some poking in the node-semver source I have found the inc() method which can be accessed via the _semver object in the tools.Version. So this would be probably the best approach for now (not so clean but it will do).
Just for clarification. I'm not changing the packages now. I'm just deploying the app that uses conan internally to solve its 3rd parties. The conan deps were just kind of in the way of me using python semver package (both using the same import name). Which is not a problem of conan as you pointed out.
Also, the conan seems to be working fine with the new node-semver 0.8.0.
Thanks for your insight and time. You can close this issue or consider changing the conans.tools.Version to expose more functionality so we didn't need to either write what is already written or depending on (somewhat non-public) _semver object.

P.S. We have looked into revisions, but there was something (I would need to look again to know exactly what, it was couple month ago) that made us decide not to use them for now.

**Comment by czoido** [comment]
Ok, I'll close the issue then. Feel free to reopen if you have more questions regarding this.

Thanks for the feedback!
