### ISSUE TITLE
[question] How to pack up an existing lib for conan

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7533]
So if I have a software package that is prebuilt, i have the source code and the lib files, since the building itself is tricky, i dont wand to rebuild it, 
so is there a way to packup the prebuild lib and upload to repo artifactory with out building it?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @shelper,

Thanks for your question. I think the `export-pkg `command can help you: https://docs.conan.io/en/latest/reference/commands/creator/export-pkg.html
This command will let you create a package from those prebuilt lib files, and after you create the package you can upload it to Artifactory.
Please tell us if this helps.
