### ISSUE TITLE
[bug] Conan info --paths returns wrong information

### ISSUE THREAD

**Issue by maingig** [conan-io/conan#7540]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16.04
  * Compiler+version: gcc 5.4
  * Conan version: 1.24.1
  * Python version:3.7.8

### Steps to reproduce (Include if Applicable)

Run conan info --paths "package"

The package path is incorrect - I get a different hash than what is in the local cache.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
capicxx-core-tools/3.1.12.4@yoda/stable
    ID: 90ee443cae5dd5c1b4861766ac14dc6fae231a92
    BuildID: None
    export_folder: /root/.conan/data/capicxx-core-tools/3.1.12.4/yoda/stable/export
    source_folder: /root/.conan/data/capicxx-core-tools/3.1.12.4/yoda/stable/source
    build_folder: /root/.conan/data/capicxx-core-tools/3.1.12.4/yoda/stable/build/90ee443cae5dd5c1b4861766ac14dc6fae231a92
    package_folder: /root/.conan/data/capicxx-core-tools/3.1.12.4/yoda/stable/package/90ee443cae5dd5c1b4861766ac14dc6fae231a92
    Remote: nio-skywalker=https://artifactory.nevint.com/artifactory/api/conan/dc-skywalker-conan-local
    URL: None
    License: None
    Author: None
    Description: Core tools built with maven
    Recipe: Cache
    Revision: a6816836b3a8a2ca13f85d4170a15bb4
    Binary: Missing
    Binary remote: nio-skywalker
    Creation date: 2020-08-06 22:07:51


root@fmalouf-linux:/opt/build/build-linux#  cd /root/.conan/data/capicxx-core-tools/
root@fmalouf-linux:~/.conan/data/capicxx-core-tools# ls
3.1.12.4
root@fmalouf-linux:~/.conan/data/capicxx-core-tools# cd 3.1.12.4/yoda/stable
root@fmalouf-linux:~/.conan/data/capicxx-core-tools/3.1.12.4/yoda/stable# ls
export  locks  metadata.json  metadata.json.lock  package
root@fmalouf-linux:~/.conan/data/capicxx-core-tools/3.1.12.4/yoda/stable# cd package/
root@fmalouf-linux:~/.conan/data/capicxx-core-tools/3.1.12.4/yoda/stable/package# ls
c023db9fc677d4d0b3bd0c20f71385e4cf8a1220
```

**Comment by danimtb** [comment]
I am seeing wrong paths from my side as well, might be a bug. Thanks for reporting, I will look a little bit more into it

**Comment by danimtb** [comment]
After some initial testing I found that the command `conan info` uses the default profile if one is not provided, so you might see a different reference depending on the profile used.

However, the bug in the information showed is still there as it is displaying a package that does not exist because the information is still present in the metadata.json

```
$ conan info capicxx-core-tools/3.1.12.4@ --paths -pr profile-build
capicxx-core-tools/3.1.12.4
    ID: 9bfdcfa2bb925892ecf42e2a018a3f3529826676
    BuildID: None
    export_folder: C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\export
    source_folder: C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\source
    build_folder: C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\build\9bfdcfa2bb925892ecf42e2a018a3f3529826676
    package_folder: C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\package\9bfdcfa2bb925892ecf42e2a018a3f3529826676
    Remote: None
    Recipe: Cache
    Revision: a2adcca861fde034653545b7d0e50214
    Binary: Cache
    Binary remote: None
    Creation date: 2020-08-12 16:44:30

$ conan info capicxx-core-tools/3.1.12.4@ --paths
capicxx-core-tools/3.1.12.4: WARN: The package capicxx-core-tools/3.1.12.4:3fb49604f9c2f729b85ba3115852006824e72cab doesn't belong to the installed recipe revision, removing folder
capicxx-core-tools/3.1.12.4
    ID: 3fb49604f9c2f729b85ba3115852006824e72cab
    BuildID: None
    export_folder: C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\export
    source_folder: C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\source
    build_folder: C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab
    package_folder: C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab
    Remote: None
    Recipe: Cache
    Revision: a2adcca861fde034653545b7d0e50214
    Binary: Missing
    Binary remote: None
    Creation date: 2020-08-12 16:44:30


$ ls C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\package
9bfdcfa2bb925892ecf42e2a018a3f3529826676/

$ cat C:\Users\danimtb\.conan\data\capicxx-core-tools\3.1.12.4\_\_\metadata.json
{"recipe": {"revision": "a2adcca861fde034653545b7d0e50214", "remote": null, "properties": {}, "checksums": {}}, "packages": {"3fb49604f9c2f729b85ba3115852006824e72cab": {"revision": "e25d0f5682332ec3a5318784d2a1a4f3", "recipe_revision": "f64381ec3accbc1bd7773772de8b15ed", "remote": null, "properties": {}, "checksums": {}}, "9bfdcfa2bb925892ecf42e2a018a3f3529826676": {"revision": "6a72f68a021f8d1b6dc549728de2f239", "recipe_revision": "a2adcca861fde034653545b7d0e50214", "remote": null, "properties": {}, "checksums": {}}}}
```

This behavior might be a consequence of using revisions and profile-build for cross-building.

**Comment by maingig** [comment]
What was also puzzling to me is that it worked fine in a local build, but broke in a docker build.  I'm guessing the revision was created when I uploaded the package to artifactory since the docker is pulling from there.

**Comment by jgsogo** [comment]
Hi!

I'm not sure if this is a bug. Conan returns the paths for the given configuration, even if the package is not in the cache. Given different profiles, it returns different paths as expected (if they compute different package-ID, of course).

@maingig , can you check the configuration you are using?
 * When you don't provide any configuration, Conan uses the default, check the default profile, please.
 * Use `conan search <ref>` to see the configuration associated with the packages you have already created.

If both configurations return a different package-ID then Conan has to return different paths for them.

**Comment by maingig** [comment]
I have changed the default profile so that the configuration does not include os or arch, but rather os_build and arch_build.  I think revisions were being created when I modified the recipe or the configuration did not match.  I don't know that I can reproduce the exact case anymore.  I was expecting that the path actually exists, however you're saying that it might not, depending on the configuration.  While you might be right, producing a local path which doesn't exist seems wrong.

**Comment by jgsogo** [comment]
This is something we can discuss for Conan 2.0, if `conan info --paths` should return information only about existing packages already in the cache. But this is something we cannot change in 1.x, I'm sure we'll break someone's workflow.

Maybe if you can explain what you are trying to achieve and why you come across this issue, I can understand why returning paths from non-existing packages can be misleading. From my POV, I would use `conan search <ref>` if I want to check for package existence.

**Comment by memsharded** [comment]
> While you might be right, producing a local path which doesn't exist seems wrong.

I think this was actually requested by some users. Following the same logic, the ``conan info`` should not be displaying the package-id for a binary that does not exist yet? I think that would be very unexpected.

The underlying issue is, in my opinion, users accessing the cache folders directly. This sounds like an anti-pattern to me, that should be avoided if possible, I would say that we need to discuss this for Conan 2.0, maybe bring it to the Conan 2.0 Tribe.

**Comment by maingig** [comment]
Background: I was originally trying to use a conan built tool recipe and ran into difficulty there - https://github.com/conan-io/conan/issues/7539.  I finally resolved that issue but in the meantime thought I could use a combination of conan search and conan info --paths.  Little did I know :-)

**Comment by rob-baily** [comment]
> The underlying issue is, in my opinion, users accessing the cache folders directly. This sounds like an anti-pattern to me, that should be avoided if possible.

@memsharded In regards to this an example I have is that for some embedded SW we are using an Eclipse cross-compiler build where conan is not supported.  In this case during setup we are pulling the source from the conan repo and copying that into an Eclipse project to be included in a workspace.  We have a conanfile.txt which specifies the required libraries and then we use the **conan info --paths** command in a script to find the files and copy them. Perhaps there is a better way to support this but I am not sure.  Would like not to pull from git since we are already using conan for packages and this is a nice consistent path to pull things into projects.  I have seen a couple threads about Eclipse integration but have not seen anything truly useful to pull conan packages into an Eclipse CDT build.

**Comment by memsharded** [comment]
I have been checking this for 2.0:

- The ``conan graph info`` command now displays the folders as ``None``. The folders that are not used or do not exist are ``None``, and as ``conan graph info`` do not use source, build or package folder (it works only over recipes), it will print ``None.
- There is a new ``conan cache path <ref>`` that gives the path in the cache for a given recipe or package. Useful for debugging
- The recommended approach to extract files from the Conan cache and automate tasks is the new ``deployers``, that allow to do that easily in a ``--deploy=mydeploy`` script, that can be easily shared with ``conan config install`` too. Using the output of ``graph info`` to automate over paths and file extraction from packages will be documented as an anti-pattern.

So I think we can close this ticket now, thanks!
