### ISSUE TITLE
[question] Revision ID as 0 when conan upload duplicated packages

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7542]
So I have two computer that builds the same package (b2, for example) with same recipe and source code. I have revision_mode enabled. and then i uploaed to my artifactory-cpp-ce repository, 
What i found is that I got two package stored on artifactory, one with revision ID as 0 for both PREV and RREV.

Is that expected behavior? I thought everything should be the same, Or did i miss anything here? And what would make revision ID to be 0?

See the cropped package info below on my artifactory:
![b2](https://user-images.githubusercontent.com/546163/89966791-ec02f300-dc1d-11ea-9151-3c7cf1789a91.png)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Have you tried this with a clear Artifactory repo? Recipe revision 0 is set on Artifactory if you upload from a Conan client without revisions enabled.

In your case, uploading the same thing from different machines should not lead to this behavior. Please make sure you have revisions enabled in both machines as well.

**Comment by shelper** [comment]
ok... maybe i compiled the packages on a pc with the revision disabled and then turned the revision on and lost track of it. 
thanks for point that out, i am closing this.

**Comment by danimtb** [comment]
No problem, thank you for writing!
