### ISSUE TITLE
conan package content changed, hash stays the same

### ISSUE THREAD

**Issue by danielhalati** [conan-io/conan#7543]
Hello. Please clarify something to me. I have created a bunch of Conan packages weeks ago and now it came the time that I had to update the content of the packages with license information. My approach is that I am using Conan to pack an existing folder to pack libraries. Now the content of the package has changed with an additional folder called 'licenses', but on locally on the machines, this is not detected because the hash is the same (local package is the same with the remote package), but the remote package has an additional folder.

How can I retrieve the updated packages now?

**Comment by uilianries** [comment]
The package ID (hash), by default (semver_direct_mode) is affected only by `settings`, `options` and `requires`. The attribute `license` is not part of the package ID:

https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html

> How can I retrieve the updated packages now?

Add the "update" subcommand to install command: `conan install ... -u`

https://docs.conan.io/en/latest/reference/commands/consumer/install.html

**Comment by danimtb** [comment]
just in case you meant "packaging a license folder" in the packages, that will be the same thing as the Package ID is not affected.

You should use `conan install --update` in order to retrieve the new packages from the sever if you have an old package ID installed locally

**Comment by danielhalati** [comment]
i think that will do the trick
