### ISSUE TITLE
[bug] self.options object in test_package recipe behaves different then object in main recipe

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7548]
The `self.options` object inside a main recipe has `.get_safe` attribute to get the value of a option or a default value if it does not exist.
But in a test package conanfile.py, this does not exist.

I believe options object in the main and test recipe should have the same options.

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux+Windows
  * Conan version: 1.28.1
  * Python version: python 3.7.7

### Steps to reproduce (Include if Applicable)

Create `rec1` and `rec2` recipe + test of rec2 using:

```sh
cat >rec1.py <<EOF
from conans import ConanFile
class Rec1Conan(ConanFile):
    name = "rec1"
    version = "1.0"
    options = {
        "opt": [True, False],
    }
    default_options = {
        "opt": True,
    }
EOF

cat >rec2.py <<EOF
from conans import ConanFile
class Rec2Conan(ConanFile):
    name = "rec2"
    version = "1.0"
    requires = "rec1/1.0"
EOF

mkdir tp_rec2

cat >tp_rec2/conanfile.py <<EOF
from conans import ConanFile
class TestRec2Conan(ConanFile):
    def build(self):
        self.output.info("rec1.opt={}".format(self.options["rec1"].get_safe("opt")))
EOF
```

Run the following commands:
```sh
conan remove -f rec1
conan remove -f rec2
conan create rec1.py rec1/1.0@ -tf None
conan create rec2.py rec2/1.0@ -tf tp_rec2
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```sh
rec2/1.0 (test package): Calling build()
ERROR: Traceback (most recent call last):
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method
    conanfile.build()
  File "/tmp/poc2/tp_rec2/conanfile.py", line 6, in build
    self.output.info("rec1.opt={}".format(self.options["rec1"].get_safe("opt")))
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/model/options.py", line 75, in __getattr__
    raise ConanException(option_not_exist_msg(attr, list(self._dict.keys())))
conans.errors.ConanException: option 'get_safe' doesn't exist
Possible options are ['opt']
```

**Comment by jgsogo** [comment]
Hi, I'm not sure if the issue is relate to the recipe itself and test_package, or to the `self.options` and `self.options["req"]`, but I agree that both should provide the same interface **to access the values**, because some actions like deleting options from a requirement should be forbidden.

**Comment by madebr** [comment]
@jgsogo 
Yes this is different from #7547. This is about access, not modification.

**Comment by memsharded** [comment]
The new ``self.dependencies["mydep"].options`` access model is now the recommended one for getting always the right values of dependencies options (see https://github.com/conan-io/conan/pull/9776#pullrequestreview-786699483). I think we can mark this issue as solved now, but please comment otherwise.
