### ISSUE TITLE
How to deal with spaces in paths ?

### ISSUE THREAD

**Issue by dkgs** [conan-io/conan#755]
Hello,

I'm new to conan  and python and I'm actually experimenting and I stumbled upon some white spaces in some of my folders. That caused some commands to not work as expected. Like for example : 
`self.run("cmake %s %s" % (self.conanfile_directory, cmake.command_line))`

If `self.conanfile_directory` is containing spaces, the command to be executed will be ill-formed.

I wonder how to deal with this case : 
- shoud I add the quotes manually ? like this : `self.run('cmake "%s" %s' % (self.conanfile_directory, cmake.command_line))`
- I read there is a function in python that is `pipes.quote()` that could do it, but it apparently changes in python 3
- can the `self.run()` function take, instead of a string, a list of arguments and automatically deal with the problem ?

Any recommendation on this ?

**Comment by lasote** [comment]
Hi @dkgs . I usually add the quotes manually, explicit and simple. :wink:

**Comment by memsharded** [comment]
Yes, I usually do your first option too. That is, the more it looks like the real command typed on the terminal, the easier to understand, at least for me.

**Comment by dkgs** [comment]
Thank you for your feedbacks, in fact the first solution is more explicit than the others. But on the other hand, I consider it bug-latent as someone will discover error in its command line only when he will actually have a space in some of his paths.

As my personal example, everything was working fine until I go on another PC and tried to run my conanfiles in a different folder that was containing spaces, hence my question. But that kind of errors are pretty straightforward to correct, but I would prefer not to fall in this case again because a quoting is so quickly forgotten. Nevertheless, I just wanted to highlight the problem & I will stick to my first option.

**Comment by memsharded** [comment]
Actually @Manu343726 might be proposing some enhancements to the ``CMake`` helper class, that would wrap common commands like this one, then potentially helping with this issue.
