### ISSUE TITLE
[feature] Allow passing options to conan build

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#7552]
I'm using `conan build` as a part of build process which doesn't produce conan package as a result. Instead it's used as a convenient wrapper for conan install + cmake + ninja which ensures correct environment variables on all stages. 

It would be very useful if `conan build` allowed passing `-o` arguments like other conan commands like `conan install`. Right now I configure conanfile behavior via environment variables, however using options would be more natural.

**Comment by jgsogo** [comment]
Hi! That's not possible, `conan build` has to use the same graph computed by `conan install` so it has to use exactly the same settings and options (same profile), otherwise the _build_ might not be congruent with the _install_ step.

**Comment by annulen** [comment]
Thanks! I didn't realize that I can specify any package options on install step (even unrelated to installation of requirements) and they will be visible on build step, so passing options to build step separately would actually be superfluous.

**Comment by jgsogo** [comment]
If this works for you, can we close the issue? Thanks!
