### ISSUE TITLE
[feature] Export compilervars in conans.tools

### ISSUE THREAD

**Issue by ohanar** [conan-io/conan#7554]
Current compilervars is not exposed via `conans.tools` which means that only conanfiles that make use of the CMake and vcproj build helpers can reasonably use the Intel compiler. Please export compilervars and the _dict and _command variants in the `conans.tools` module.

Blocker for https://github.com/conan-io/conan-center-index/pull/2499.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Yes, this is something we have to do in order to complete the integration

**Comment by jgsogo** [comment]
This should easy to do. Feel free to open a PR with the changes needed
