### ISSUE TITLE
How to link against  to specific packageid.

### ISSUE THREAD

**Issue by ppatoria** [conan-io/conan#7555]
I have a package with 2 binaries. The binaries only differ by a single option.

The package is a library. How can now link this package to specific package that I require?
How

**Comment by memsharded** [comment]
Hi @ppatoria 

When you do the install/create, specify the option that you want to use:

```bash
$ conan install . -o mypkg:myoption=myvalue
```
That will install the right binary and generate (depending on the Conan generators) the ``conanbuildinfo.cmake`` or whatever other files with the right locations to those binaries.
Change the option and install the new binaries, and the generated files will be pointing to the path of the other binary. Both can coexist at the same time in the Conan cache without being re-installed.

**Comment by memsharded** [comment]
Hi @ppatoria 

Please let me know if the above response clarified your question (and you can close the issue too if the question was correctly addressed). Thanks!

**Comment by memsharded** [comment]
Hi @ppatoria 

I am closing this issue, but do not hesitate to comment here or open a new issue if you have any further question. Thanks!
