### ISSUE TITLE
[bug] 'lock create' does not accept a path to a folder containing a conanfile.py

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7557]
[conan_api.py#L1318](https://github.com/conan-io/conan/blob/770602e142e3fd15eb25f5eff8ba3832be7bcd44/conans/client/conan_api.py#L1318)

I'd expect the path argument to be the same as in other commands and allow me to provide a path to a folder without specifiying the filename.

The error message:

> ERROR: Conanfile does not exist in C:\Jenkins\workspace\liba

is confusing since a Conanfile does in fact exist there,

### Environment Details (include every applicable attribute)
  * Operating System+version:  Windows 10
  * Conan version: 1.28.1
  * Python version: 3.7.7

### Steps to reproduce (Include if Applicable)
`conan lock create <path to a folder containing a conanfile.py>`

**Comment by danimtb** [comment]
As this was introduced as a new command, I think we tried to start introducing new changes for a future command line in Conan 2.0

I am pinging here @czoido for confirmation

**Comment by memsharded** [comment]
Hi @GordonJess 

To clarify: the CLI in Conan 2.0 will be way more explicit than the current one. For example it will require to type ``conan install conanfile.txt``, and ``conan install .`` will no longer be possible (that will search for conanfile.txt first, then for conanfile.py if not found, and this kind of behavior is always causing confusion to some users, so everything is going to be way more explicit and non ambiguous).

As we were changing the command and creating a new ``conan lock`` command, we wanted to directly use the new CLI 2.0 guidelines, so maybe that cli command is not broken in Conan 2.0.

**Comment by DukeOfKirkcaldy** [comment]
Hi,

Ah okay!  Understood! Thanks!

**Comment by memsharded** [comment]
Fixed in Conan 2.0
