### ISSUE TITLE
[question] why is unaffected package marked as "modified":true in lockfile?

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7562]
I am following the example for [Lockfiles in CI](https://docs.conan.io/en/latest/versioning/lockfiles/ci.html#lockfiles-in-continuous-integration) and computing the build order needed to build product `app1` after a change in `libb`.

I am confused as to why `liba` in the final `app1` lockfile is marked as `"modified":true`.  since it was used from the cache and was not rebuilt.

```
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "libb/0.2@user/testing",
    "options": "",
    "package_id": "39b0b5fad32aaf2a462d27d4282d12c08bd6c818",
    "prev": "0",
    "modified": true,
    "requires": [
     "1"
    ],
    "context": "host"
   },
   "1": {
    "ref": "liba/0.1@user/testing",
    "options": "",
    "package_id": "4024617540c4f240a6a5e8911b0de9ef38a11a72",
    "prev": "0",
    "modified": true,
    "context": "host"
   },
   "3": {
    "ref": "app1/0.1@user/testing",
    "options": "",
    "package_id": "15d2c695ed8d421c0d8932501fc654c8083e6582",
    "prev": "0",
    "modified": true,
    "requires": [
     "4"
    ],
    "context": "host"
   },
   "4": {
    "ref": "libd/0.1@user/testing",
    "options": "",
    "package_id": "b03c813b34cfab7a095fd903f7e8df2114e2b858",
    "prev": "0",
    "modified": true,
    "requires": [
     "0",
     "5"
    ],
    "context": "host"
   },
   "5": {
    "ref": "libc/0.1@user/testing",
    "options": "",
    "package_id": "39b0b5fad32aaf2a462d27d4282d12c08bd6c818",
    "prev": "0",
    "modified": true,
    "requires": [
     "1"
    ],
    "context": "host"
   }
  },
  "revisions_enabled": false
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Release\nos=Windows\nos_build=Windows\n[options]\n[build_requires]\n[env]\n"
}
```

The 'modified' flags are useful for me to collect the packages which have changed to upload them to Artifactory.

I guess they are also important for generating build info.

**Comment by memsharded** [comment]
Yes, the ``modified`` flag is exclusively used for the ``BuildInfo`` (please be aware the BuildInfo has some current limitations to be used for Conan packages, we are working to improve that).
Still, this seems a bug. Most likely it was incorrectly marked as modified when creating a full lockfile from a base one. I think it should be relatively easy to fix this, if possible, I will try to submit a PR for 1.29 next week, if not possible, I will delay it for 1.30.

Thanks for reporting.

**Comment by DukeOfKirkcaldy** [comment]
@memsharded,

Thanks, much appreciated!!

**Comment by DukeOfKirkcaldy** [comment]
Hi @memsharded,

I think I have discovered another issue with the modified flags in the example.

Seems that the `conan create` command does not update the given lockfile to show the node has been modified.

In the example, you can see that both `libb_deps_debug.lock` and `libb_deps_release.lock` do not have the flag set.
