### ISSUE TITLE
[question] graph is not a conan command (conan 1.28.1) - fix documenation

### ISSUE THREAD

**Issue by AndreasHK** [conan-io/conan#7569]
So since a while when using `conan info -bo` I get the warning that this is deprecated and I should use `conan graph.` So I did with conan 1.25.1 but when upgrading to 1.28.1 (because of another [issue](https://github.com/conan-io/conan-center-index/issues/2591)), `conan graph` is gone. The current [documentation for conan info](https://docs.conan.io/en/1.28/reference/commands/consumer/info.html) still says you should use `conan graph` though.

I suggest fixing the documentation and guiding to `conan lock ... ` instead of `conan graph ...`

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Thanks for pointing it out! I'm submitting a PR right away 👍
