### ISSUE TITLE
[bug] getting started poco project build failed -- sqlite3/3.31.1 pack_info() 

### ISSUE THREAD

**Issue by hongyx11** [conan-io/conan#7575]
I met the problem when I install conan example project.
The build report the error,
ERROR: sqlite3/3.31.1: Error in package_info() method, line 116
self.cpp_info.filenames["cmake_find_package"] = "SQLite3"
TypeError: '_CppInfo' object does not support item assignment

where did this error happen? how to solve this?

Thanks!
-->

### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 16
  * Compiler+version: g++8
  * Conan version: 1.27.1
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)
follow exactly the same steps described in https://docs.conan.io/en/latest/getting_started.html. 

### Logs (Executed commands with output) (Include/Attach if Applicable)

hongy0a@jasmine:~/gitrepo/examples/libraries/poco/md5/build$ conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

poco/1.10.0: Not found in local cache, looking in remotes...
poco/1.10.0: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.80k]
Downloading conanfile.py completed [10.58k]
Downloading conan_export.tgz completed [0.31k]
Decompressing conan_export.tgz completed [0.00k]
poco/1.10.0: Downloaded recipe revision 0
conanfile.txt: Installing package
Requirements
    bzip2/1.0.8 from 'conan-center' - Cache
    expat/2.2.9 from 'conan-center' - Cache
    openssl/1.1.1g from 'conan-center' - Cache
    pcre/8.41 from 'conan-center' - Cache
    poco/1.10.0 from 'conan-center' - Downloaded
    sqlite3/3.31.1 from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    bzip2/1.0.8:a5875aed3fc7ae8dd0488f7e5e99acbc480d721d - Cache
    expat/2.2.9:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Cache
    openssl/1.1.1g:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Cache
    pcre/8.41:dafd5c98708bf1a1a158ba2cfe6bd76b921d5f35 - Cache
    poco/1.10.0:8439951960f1277907ccf6535ca4e8bdb34bfe97 - Download
    sqlite3/3.31.1:5840d0ed3c1de62f1130f4d884d2083129209657 - Cache
    zlib/1.2.11:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Cache

Installing (downloading, building) binaries...
poco/1.10.0: Retrieving package 8439951960f1277907ccf6535ca4e8bdb34bfe97 from remote 'conan-center'
Downloading conanmanifest.txt completed [51.00k]
Downloading conaninfo.txt completed [3.44k]
Downloading conan_package.tgz completed [5749.99k]
Decompressing conan_package.tgz completed [0.00k]
poco/1.10.0: Package installed 8439951960f1277907ccf6535ca4e8bdb34bfe97
poco/1.10.0: Downloaded package revision 0
bzip2/1.0.8: Already installed!
expat/2.2.9: Already installed!
openssl/1.1.1g: Already installed!
sqlite3/3.31.1: Already installed!
ERROR: sqlite3/3.31.1: Error in package_info() method, line 116
	self.cpp_info.filenames["cmake_find_package"] = "SQLite3"
	TypeError: '_CppInfo' object does not support item assignment

**Comment by jgsogo** [comment]
Hi, @hongyx11 .

Recipes in ConanCenter are tested only with the lastest Conan version (typically ~10 days after the release is public). As you can see, that `sqlite3` recipe contains a [line like `required_conan_version = ">=1.28.0"`](https://github.com/conan-io/conan-center-index/blob/master/recipes/sqlite3/all/conanfile.py#L4). This recipe is using a feature from `1.28` Conan release.

That _special line_ in the recipe header will raise a nicer message starting from `1.28.0` (https://github.com/conan-io/conan/pull/7360), but `1.27.1` didn't include that feature.

So, you need to update your Conan version in order to use latest `sqlite3` recipe, or you can use an older recipe revision (use `conan search sqlite3/x.x.x@ --revisions --remote=conan-center` to get a list of revisions).

Thanks

**Comment by hongyx11** [comment]
Hi @jgsogo .

I appreciate your quick response. And it solved the question!

Thanks,
Yuxi
