### ISSUE TITLE
[feature] Overcome Windows system PATH length limitation

### ISSUE THREAD

**Issue by db4** [conan-io/conan#7587]
Our internally developed software consists of many dynamic libraries, each of them placed into a single Conan package.
So on Windows Conan modifies run environment adding to system PATH something like
```
c:\Users\ContainerAdministrator\.conan\data\package-name\1.0.0\company-name\testing\package\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\bin (about 140 chars)
```
This is done for every package. But PATH on Windows has a very strict limitation: its length cannot exceed 8192 characters. Once it's reached, `cmd.exe` will fail to create a new process. About 2500 of them takes Visual Studio Developer Command Prompt; it leaves less than 6000 chars for a user (if he/she doesn't have any 3rd-party application installed), or about 40 Conan packages if `short_paths=True` is not used. I think it makes Windows development using Conan very problematic. What about another approach: place .dll/.exe symlinks into a single bin directory or even use [shim generator](https://github.com/chocolatey/shimgen) as Chocolatey does?

**Comment by jgsogo** [comment]
Hi, @db4 

For other reason (but with the same effect) I'm proposing to add wrappers around the executables that are provided by packages (https://github.com/conan-io/conan/pull/7324). As a side effect, only the path to the wrappers would be added to PATH and probably they should be all together closer to the working directory.

We need to keep working on that approach.

**Comment by db4** [comment]
Hi @jgsogo! 

> For other reason (but with the same effect) I'm proposing to add wrappers around the executables that are provided by packages (#7324)

That's great, but what about DLLs, provided by packages? They also should be in PATH. Why symlinking .exe/.dll into a single bin directory is not an option?

**Comment by memsharded** [comment]
Closing this ticket as outdated, Conan 2.0 cache new layout will avoid too long paths
