### ISSUE TITLE
[bug] 'conan lock update' does not complete missing 'package_id' fields

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7588]
When using `package_revision_mode`, the `package_id` of packages in the next build levels are not computed in the build order.

_bo_release.json_:
[ci.zip](https://github.com/conan-io/conan/files/5122255/ci.zip)

```
[
 [
  [
   "libd/0.1@user/testing",
   "209fa52ca24d97c9635e13d126d5c14a72030c1a",
   "host",
   "4"
  ]
 ],
 [
  [
   "app1/0.1@user/testing",
   "Package_ID_unknown",
   "host",
   "3"
  ]
 ]
]
```

They are added to the updated lockfile after they are built.

_locks/app1_release_updated.lock_:
```
   "3": {
    "ref": "app1/0.1@user/testing",
    "options": "",
    "package_id": "99d1718d3b7569f208fb05ea765a95bfb4c57e65",
    "prev": "0",
    "modified": true,
    "requires": [
     "4"
    ],
```

But this information is not integrated into the old lockfile by the `conan lock update` command.

_locks/app1_release.lock_:
```
   "3": {
    "ref": "app1/0.1@user/testing",
    "options": "",
    "package_id": "Package_ID_unknown",
    "prev": "0",
    "modified": true,
    "requires": [
     "4"
    ],
 ```

This information is important since this is the lockfile that is pushed to Artifactory for downstream jobs and reproducing packages in the future.

### Environment Details (include every applicable attribute)
  * Operating System+version:  Windows 10 64-bit
  * Compiler+version:
  * Conan version: 1.28.1
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
See modified example `ci.zip` attached.

**Comment by memsharded** [comment]
Thanks for the report, confirmed and proposed a fix in #7592 for Conan 1.29.
