### ISSUE TITLE
Error while initializing settings. Invalid setting '16' is not a valid 'version' value

### ISSUE THREAD

**Issue by tbikash62** [conan-io/conan#7590]
![image](https://user-images.githubusercontent.com/58831041/91164804-fae2ae80-e6cf-11ea-843b-e49ecbc637e4.png)

![image](https://user-images.githubusercontent.com/58831041/91164869-1352c900-e6d0-11ea-8d9e-de5bbbd81aa8.png)

The above two contains my terminal and the conanfile.py screenshots, 

It always ask to pass the values, which is already defined in the settings. And it is not detecting the setting. 

It is not detecting even if it is defined in the settings.yml.

Need your help. 

Regards

**Comment by uilianries** [comment]
It seems like Conan didn't detect your compiler. Please, paste the output of:

    conan profile new --detect foobar && conan profile show foobar

Please, add the entire information. Also, which Conan version, OS and compiler are you using?

You can update your profile manually, adding your compiler and its version: https://docs.conan.io/en/latest/reference/commands/misc/profile.html

    conan profile update settings.compiler='Visual Studio' default

**Comment by memsharded** [comment]
Also, the way you are constraining the ``settings`` in the recipe itself is no longer recommended. If you really want to block some specific platform, use the ``configure()`` method and raise ``ConanInvalidConfiguration`` exception.

**Comment by AbrilRBS** [comment]
Closing as answered as we didn't hear back from you in a while, thanks a lot for your question! Feel free to reopen/open a new issue if needed, thanks!
