### ISSUE TITLE
[feature] Method to be run after the graph is resolved

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#7591]
There are some checks that are needed and cannot be run in the `configure()` method:
 * values from options of the requirements
 * actual version of the requirements (if using version-ranges or overriding).

**Motivation**

Right now, these checks are moved to the `build()` method, which is the only (the first) method were all these values are available. Recipe can check for options values and it can use `deps_cpp_info["xxx"].version` to check the actual version of the requirements.

The big issue is that this method is executed only if the package is going to be built, but if the package is already available we won't notice the error until it is too late (runtime error). Depending on the `package_id_mode`, the consumer will get a different package-id **or not** for the given scenarios above. So in the general use-case, this new method is something needed.

**Proposal**

Let's add a new method to run these checks:

```python

class Recipe(ConanFile):
   def validate(self):
      if self.options["req1"].shared == True:
          raise ConanInvalidConfiguration("req1 needs to be statically linked")

      if self.<requirements>["req1"].version >= 7.0:
         raise ConanInvalidConfiguration(f"{self.name} requires 'req1<7.0'") 
```

This method will run after the graph is built for the same Conan commands `configure()` is running right now.

**Comment by uilianries** [comment]
For hooks I think we can use `pre_build`, but for regular validation this new feature looks interesting.

**Comment by SpaceIm** [comment]
It would be nice if conan was able to report a summary of options/requirements violations, instead of just raise at the first error. Otherwise, consumers may fall in a "die and retry" or "read your 100 conanfiles" to figure out what to do to solve those issues.

**Comment by jgsogo** [comment]
> It would be nice if conan was able to report a summary of options/requirements violations, instead of just raise at the first error. Otherwise, consumers may fall in a "die and retry" or "read your 100 conanfiles" to figure out what to do to solve those issues.

Yes, this is something to take into account for the graph model in Conan 2.0, but I want to limit the expectations a little bit: requirements are conditional to options and settings, so as soon as we find a conflict we cannot go ahead in that branch of the graph (it might not be the right branch once the conflict is solved), but I agree we can inspect other branches and report errors that are not affected by existing ones. 👍
