### ISSUE TITLE
[bug] SystemPackageTool installing multiple does not work if one package is already installed

### ISSUE THREAD

**Issue by sigmunjr** [conan-io/conan#7594]
Created pull-request #7593

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: gcc 7.5.0
  * Conan version: 1.23.0
  * Python version: python3.6

### Steps to reproduce (Include if Applicable)
install *one* package, e.g.:

    sudo apt install libgstreamer-plugins-base1.0-dev
```PYTHON
    def system_requirements(self):
        installer = SystemPackageTool()

        run_update = True
        with_force = False

        if self.options.camera_gst:
            installer.install(
                [
                    'libgstreamer-plugins-base1.0-dev',
                    'libgstreamer-plugins-good1.0-dev',
                    'gstreamer1.0-plugins-bad',
                    'gstreamer1.0-plugins-ugly'
                ],
                run_update,
                with_force
            )
```

**Comment by memsharded** [comment]
Please check the docs in: https://docs.conan.io/en/latest/reference/conanfile/methods.html#systempackagetool

>Note: This list of packages is intended for providing alternative names for the same package, to account for small variations of the name for the same package in different distros. To install different packages, one call to install() per package is necessary.

For different packages you need to do different ``.install()`` calls. We will probably change this interface in Conan 2.0 as it is confusing, but it is documented as such.

**Comment by uilianries** [comment]
Interesting, the [documentation](https://docs.conan.io/en/latest/reference/conanfile/methods.html#systempackagetool) says: 

> The packages won’t be installed if they are already installed at least of force parameter is set to True

So you should use Force in your case. Did you try with `force=True`?

**Comment by sigmunjr** [comment]
:+1:
