### ISSUE TITLE
[bug] Package ID independent of build type doesn't work on windows

### ISSUE THREAD

**Issue by Timen** [conan-io/conan#7603]
* os: Windows 10:
  * compiler: Visual studio 2019:
  * conan: 1.28.1:
  * python: 3.8:

Removing build_type from conanfile settings or even hard coding a build_type in the package_id will still result in a different package id hash when specifying a different build type during package creation. I found that the compiler settings would still change the final hash even when only changing build type. Simply put if one wants to create a package hash independent on build type on windows he or she will also need to hardcode the compiler settings to a predefined string. This problem does not exist on osx.

**Comment by memsharded** [comment]
Hi @Timen 

This shouldn't be the case. I guess there might be something else failing, could you please provide a reproducible case so we can try it? Maybe you are changing ``self.settings.build_type`` in the ``package_id()`` method and not ``self.info.settings.build_type``? I also don't fully understand the connection between the issue title and the content, if you could please clarify a bit more, that would help. Thanks.

**Comment by Timen** [comment]
@memsharded Sorry Updated the title. 

So I have a conan package (LLVM) that I want to compile one time in Release mode and reuse this package for the Debug and RelWithDebInfo (as it only used for compilation not in the actual code). On osx and linux simply removing the build_type from the settings in the top of the conanfile makes the package hash independent of the build_type. However this method didn't seem to work on Windows. In the end I traced it down to something in the self.settings.compiler changing when I switch build_types. I wasn't able / didn't have time to look into exactly which part of the Settings object was different but for me modifying the compiler in the package_id like so:
```
def package_id(self):
        if self.info.settings.os in ["Windows","WindowsStore"]:
            self.info.settings.compiler = "Visual Studio"
```

Would ensure the package hash was independent of build_type on windows. So something in the compiler Settings object is changed when I switch build_types. 

I made sure to only change the build type not the compiler while creating a package by adding:
`-s build_type=Release` or `-s build_type=Debug` to the end of the conan create command.

**Comment by memsharded** [comment]
Oh, I see now @Timen thanks for clarifying.

Check the output in both cases. In the debug one you will see in the configuration:
```
compiler.runtime=MDd
```
And in the release one:
```
compiler.runtime=MD
```

My suggestion here would be:

- Do not remove the input settings. If you need to build this from sources, the build needs to know both the build_type and the  Visual runtime to link with. You will be passing this information to build the package from the profile.
- Remove the information in the ``package_id()`` to force using only 1 binary, something like:

```python
def package_id(self):
     if self.settings.os == "Windows" and self.settings.compiler == "Visual Studio":
          del self.info.settings.build_type
          del self.info.settings.compiler.runtime
```

Also, in case you want something a bit more future-proof, the ``compatible_packages`` feature, allows you to define this compatibility, while also allowing you to generate the new binaries in the future and using them without needing to modify the recipe.

I am adding a test in https://github.com/conan-io/conan/pull/7605 to check this behavior works. Maybe worth adding it to the docs somewhere?

**Comment by Timen** [comment]
Done!

PR open here:  https://github.com/conan-io/docs/pull/1821
