### ISSUE TITLE
Conan 1.28 breaking change (model/options.py/class PackageOptionValues) : Add config variable (conan.conf/environment variable) to select old/new behavior ?

### ISSUE THREAD

**Issue by PatrickSoulardThales** [conan-io/conan#7609]
Conan 1.28

We've existing packages in production having some code in conanfile.py which assumes that missing options have "None" value (maybe not a good practice but ...).

Since 1.28, `model/options.py/PackageOptionValues.__getattr__() `raises an exception instead of returning "None" and therefore "conan install ..." fails with some of our packages.

Is it possible to have a config variable to select the old/new behavior, like for example `general.skip_broken_symlinks_check / CONAN_SKIP_BROKEN_SYMLINKS_CHECK` => `general.skip_missing_options_check / CONAN_SKIP_MISSING_OPTIONS_CHECK`?

**Comment by memsharded** [comment]
Hi @PatrickSoulardThales 

I guess the error you are seeing is when using ``self.info.options.missing_option``, isn't it?

This was changed in https://github.com/conan-io/conan/pull/7303, it was declared a bug, both because the documented behavior for ``self.settings``, ``self.options`` when missing values is to raise exceptions, so ``self.info.options`` should necessarily follow the same behavior. It was a dangerous bug too, as typos like ``self.info.options.sahred`` would be silently skipped and only realized much later in the process.

If you want to upgrade to Conan 1.28 I would suggest to fix your recipes, it should be a quick fix (a try-except, or a ``if "option" in self.info.options``) and backwards compatible (the fix will still work with Conan < 1.28). How many recipes are you managing? Please let me know, I would like to understand better the pain. The thing is that adding a config variable just for keeping a declared bug active seems a bit overkill, and in any case we are very quickly approaching the development of Conan 2.0, which would enforce this change anyway.

**Comment by PatrickSoulardThales** [comment]
Hi,

Thanks for your answer.

Our current conanfile.py recipe files already have such a "missing option check" but of course not the older ones stored in our Artifactory server.
We have tens of such "old" conanfile.py and are now considering to modify them (dirty workaround being to explicitly pass the "missing options" with value "None").

Best regards

**Comment by memsharded** [comment]
> We have tens of such "old" conanfile.py and are now considering to modify them (dirty workaround being to explicitly pass the "missing options" with value "None").

But this raises mostly when the option itself is not defined, not when it doesn't have a value. I am not sure your workound is going to work but let me know.

Another option, depending how you deploy your Conan client, is to generate a patched version that could help in the transition while things are fixed. I could help with that, how are you installing Conan in your developer and CI machines? Which platforms do you need Conan running on?

**Comment by PatrickSoulardThales** [comment]
Thanks for your help.

We can manage patching ourselves Conan 1.28+ python code (we’re using both Windows and Linux platforms for dev and CI).
For the moment we’re using 1.27 and will identify and modify all old recipes before upgrading Conan

Best regards.

-----------------------------------------------------------------------
patrick.soulard@thalesgroup.com<mailto:patrick.soulard@thalesgroup.com>
Tel : +33 (0)1 69 88 52 33
Thales Revenue Collection Systems France
Rue de la Mare aux Joncs - Z.I. des Bordes - BP 57 - 91229 Le-Plessis-Pâté Cedex
-----------------------------------------------------------------------

De : James [mailto:notifications@github.com]
Envoyé : vendredi 28 août 2020 15:50
À : conan-io/conan
Cc : SOULARD Patrick; Mention
Objet : Re: [conan-io/conan] Conan 1.28 breaking change (model/options.py/class PackageOptionValues) : Add config variable (conan.conf/environment variable) to select old/new behavior ? (#7609)


We have tens of such "old" conanfile.py and are now considering to modify them (dirty workaround being to explicitly pass the "missing options" with value "None").

But this raises mostly when the option itself is not defined, not when it doesn't have a value. I am not sure your workound is going to work but let me know.

Another option, depending how you deploy your Conan client, is to generate a patched version that could help in the transition while things are fixed. I could help with that, how are you installing Conan in your developer and CI machines? Which platforms do you need Conan running on?

**Comment by TimoNussbaumer** [comment]
Hi @memsharded,

we experienced the exception ([options.py line 75](https://github.com/conan-io/conan/blame/1.33.0/conans/model/options.py#L75)) when we were migrating from 1.27.1 to 1.31.0 (change in 1.28.0) as some of our packages refer to options of (build_)required packages. We have code like this:
if self.options["some_required_package_of_this_package"].the_option_of_the_required_package:
    do_something
The dictionaries seam to be empty, but not if we define the option explicitly in the profiles. To us this behavior seams to be inconsistent. The option is there if I specify it explicitly in the profile or if I just use the default of the conanfile.py. Please clarify.

Thanks a lot.

Best regards,
Timo.

**Comment by memsharded** [comment]
Hi @TimoNussbaumer 

Can you give a bit more context how are you using that code?
```python
if self.options["some_required_package_of_this_package"].the_option_of_the_required_package:
do_something
```
Because this might be possible only in ``build()`` method. Options of dependencies cannot be checked while the graph is expanding (``configure()`` method), because the dependency does not even exist yet. When defining the value is a request to define it in the dependency, but the actual value of a dependency cannot be obtained in ``configure()``, it is physically impossible, the dependency conanfile.py is still in the server... If the code is for actually validating some configuration, you might be interested in the new ``validate()`` method.

**Comment by TimoNussbaumer** [comment]
Hi @memsharded,

thanks for the quick response. I'm sorry here some more context/example of usage:
`conanfile.py` of the package that requries `some_required_package_of_this_package_A`:
```
def build_requirements(self):
    super().build_requirements()
    self.build_requires(deps["some_required_package_of_this_package_A"])

def requirements(self):
    super().requirements()
    if self.options["some_required_package_of_this_package_A"].the_option_of_the_required_package:
        del deps["some_required_package_of_this_package_B"]
        self.requires(deps["some_required_package_of_this_package_C"])
```
`deps` is a from a yaml file loaded dictionary were we store the Artifactory references to the packages.
We experienced the exception during a Conan create call. A colleague of mine did a test/check with the option(s) being defined in the conan profile and he did not experience the exception. As soon as we delete the option from the profile the exception appears again.
`conanfile.py` of the package `some_required_package_of_this_package_A`:
```
class some_required_package_of_this_package_A(ConanFile):
...
    options = {
        "the_option_of_the_required_package": [True, False]
    }

    default_options = {
        "the_option_of_the_required_package": False
    }
```
I'm not very experienced with Conan but the `conanfile.py` of `some_required_package_of_this_package_A` was already downloaded when the exception occurred. If I got you right the dependencies and therefore the order how the packages are downloaded is not given by the requirements specification order and therefore not known to the Conan system at this very moment?

Thanks.

**Comment by memsharded** [comment]
Hi @TimoNussbaumer 

Now it is clear. Please note your pattern:

```python
def requirements(self):
    super().requirements()
    if self.options["some_required_package_of_this_package_A"].the_option_of_the_required_package:
```

``requirements()`` is evaluated when you are analyzing the conanfile.py, to try to know what are your dependencies. When that is resolved, it will be necessary to fetch them, evaluate them as well. It is totally impossible that you can know the actual values of your dependencies even before resolving them. In the case of ``build_requires`` is even more critical: build_requires might not be at all in the graph, even after expansion, if it is not necessary to build it from sources.

The fact that you are seeing that dependency already downloaded:

> but the conanfile.py of some_required_package_of_this_package_A was already downloaded when the exception occurred

means nothing. It could be downloaded as a build_requires or require of other package of the graph, but have other options. Specially build_requires, you can have the same package as a dependency of multiple packages, but each one is an independent, private node in the graph, that can have different option values. In other words, the same "conanfile.py" in the cache, can translate to multiple different nodes in the dependency graph, with different configuration as options. What is important is that the option value of your actual dependency is unknown at ``requirements()`` or ``configure()`` time, and it is a physical limitation, not a lack of a feature. There is nothing Conan can do to know it. Not even pre-fetching it, note that the resolution of that dependency is not only a local function, it depends on the overrides from downstream, which might induce a different version, which could have a different option default.

It still seems that change in 1.28 was a correct bug fix, and it is just uncovering some "undefined behavior" in your graph definition. I hope this clarify the issue a bit, please let me know.

**Comment by TimoNussbaumer** [comment]
Hi @memsharded,

thank you very much for clarification, I guess I got it. Last question as mentioned above. We did not see the exception when the option was part of the used Conan profile. This is an inconsistency within the actual Conan implementation, right?

Regards,

Timo.

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

This is now outdated with Conan 2, I am closing the ticket as outdated, please don't hesitate to create new tickets for any further question, thanks!
