### ISSUE TITLE
[question] Is there a way to update/modify the variable in the profile

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7612]
i have a profile file like below:
```
ANDROID_NDK_ROOT=/needs/to/be/updated
[settings]
os=Android
arch=armv8
arch_build=x86_64
...

```

is there a way to update the variable `ANDROID_NDK_PATH` through commands like ` conan profile update ...`?
it seems to me this update command only works for variables in certain section, like [settings]

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @shelper 

I am afraid it is not possible, only structured information like settings can be modified from the command line.

You had this feature request open: https://github.com/conan-io/conan/issues/7465, which is under consideration (or having python profiles), which I guess is very related

**Comment by shelper** [comment]
sounds good, closing this, thx!
