### ISSUE TITLE
[question] conan hangs on linux

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7614]
I was able to run conan install on windows, but on linux it failed to connect to my artifactory
same conan version 1.27.1, same artifactory server, same profile used, linux can ping the artifactory server, so no connection issue.
output from windows:
![windows](https://user-images.githubusercontent.com/546163/91627235-17a70c80-e984-11ea-9d2f-7a83d3380180.png)

output from linux:
![linux](https://user-images.githubusercontent.com/546163/91627239-1aa1fd00-e984-11ea-8226-f423dbba4be9.png)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @shelper 

This error is very weird. Let's try to do a quick check to rule out other possible connection issues: Enter the web UI of Artifactory, from the Linux machine, and try to download some files from those packages, like the ``conanfile.py``, or the ``conanmanifest.txt``, directly from the UI. Then I would probably try next (if that works), to install an ArtifactoryCE in that Linux machine, and try to use it, to rule out other network issues.

Please let me know how it goes, thanks!

**Comment by shelper** [comment]
i am using linux without UI, so i cannot download in browser.
but i did try curl, and the same command using curl works with windows but got time out error in linux. 

I wonder if this is due to the artifactory settings, i am using artifactory CE.

but i was able to download previously in linux, and i am sure i didn't touch artifactory in any means...

**Comment by shelper** [comment]
i was able to download using another linux computer... so i think this is not due to conan or anything, there must be something on my linux that is messed up ... i am closing this now. 
thanks anyway,

**Comment by memsharded** [comment]
Hi @shelper 

Yes, exactly the web UI gives a link that can be used with curl to download a file too. 
Happy to hear that from other Linux box it is working, yeah, I would try to review the network configuration, firewall, hosts, etc in that failing linux box, it might have something misconfigured.  Thanks for following up, and let us know if you need further help.

**Comment by shelper** [comment]
try to give some feedback on this issue.
I am running `conan install zlib/1.2.11@ -r remote-name` or direct curl package from artifactory server.
if I am on wsl2 in a windows pc. and here is what happened:
> works if remote-name == conan-center
> failed if remote-name == my-own-artifactory-server, and the failure is the same as shown in above screen shot, basically it connects, and it also says: `downloading conanmanifest completed`, but then stuck and says `Caused by ReadTimeoutError("HTTPConnectionPool(host='...', port=8081)`

I first thought there is something messed up in my wsl2 container , so i started another new wsl2 container , and the same issue happened..

my artifactory server is basd on `docker.bintray.io/jfrog/artifactory-cpp-ce:latest`, i tried to rerun artifactory docker container, issue remains...

Now i switched to another account with write access, and uploaded a package to artifactory in wsl2
then i do `conan user --clean`, and then download again using the old read only account, everything works again!

now i suspect that there must be a bug in artifactory-ce....

**Comment by memsharded** [comment]
Hi @shelper 

Thanks for added report.

Uhm, it sounds it could be a network/permission docker thing, or an interaction between containerized applications or something like that.

 I would try to debug the issue trying to eliminate that factor first. Sounds unlikely that the bug would be in ArtifactoryCE, it is serving thousands of teams, I think this issue would have appeared already:
- What happens if you run a barebones ArtifactoryCE server instead of the dockerized one? 
- Are you running directly ``docker.bintray.io/jfrog/artifactory-cpp-ce:latest``, or your own image based on that one?
- If running your own, what happens if you run the base docker image?

**Comment by shelper** [comment]
i am running directly `docker.bintray.io/jfrog/artifactory-cpp-ce:latest`

the following steps solve my problem:
delete a package on artifactory manually in browser. 
upload the package,(i cannot upload package without delete the existing one), and then i can download packages....

but after a while, it resets and i have to repeat the above steps again....
