### ISSUE TITLE
[bug] gsl-lite: Error when installing

### ISSUE THREAD

**Issue by redpandamonium** [conan-io/conan#7616]
### Environment Details (include every applicable attribute)
  * Operating System+version: Manjaro Linux
  * Compiler+version: clang 10.0.1
  * Conan version: 1.24.1
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)
Include gsl-lite/0.37.0 or gsl-lite/0.36.0 into the conanfile and install. 

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan install --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
conanfile.txt: Installing package
Requirements
    gsl-lite/0.37.0 from 'conan-center' - Cache
Packages
    gsl-lite/0.37.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
gsl-lite/0.37.0: Already installed!
ERROR: gsl-lite/0.37.0: Error in package_info() method, line 55
        self.cpp_info.filenames["cmake_find_package"] = "gsl-lite"
        TypeError: '_CppInfo' object does not support item assignment
```

**Comment by memsharded** [comment]
Hi @redpandamonium 

I guess (and for reference for other users reading this issue) that it was that you were using an older Conan version (1.24). The feature of ``self.cpp_info.filenames`` is newer and then it fails, expectedly. As stated in the docs, packages from ConanCenter should be using latest Conan version. We have introduced ``required_conan_version`` in latest release, so at some point it is likely that these failures will be more intuitive, telling users of those recipes to update.
