### ISSUE TITLE
[question] Add build requirement on previous version of package of same name

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7618]
Hello!

I'm trying to package [golang/1.15](https://github.com/madebr/conan-center-index/tree/pr_golang/recipes/golang).
Golang requires a previous go version to build itself, that's why I also added golang 1.4.3.

But when adding the build requirement `golang/1.4.3` to `golang/1.15`, the following error appears:

```
ERROR: Loop detected in context host: 'golang/1.15' requires 'golang/1.4.3' which is an ancestor too
```

How can this be allowed?

**Comment by kralicky** [comment]
Doesn't look like it is possible for a package to depend on a previous version of itself at the moment. The graph builder will fail if the same package _name_ appears in its own ancestors, even if the version is different. [Relevant code here](https://github.com/conan-io/conan/blob/develop/conans/client/graph/graph_builder.py#L193).  

You could name the 1.4 package something different like golang-bootstrap. Then you can have the golang package require golang-bootstrap to build, which will work.

**Comment by madebr** [comment]
To the conan developers,
are there plans to allow this use case?
I guess it is sensible to allow packages with the same names, as long as they are not used in the same *context* (requirement/build requirement).

**Comment by jgsogo** [comment]
Hi! Using the two-profiles approach (which will likely be the default for Conan 2.0) this is totally possible. The build-requires package will belong to the _build_ context while the other will belong to the _host_ one. The uniqueness will be name-context (not only name) and two packages with the same name and different versions can coexist in the same graph (give each one belongs to a different context).

I've written a couple of days ago about this in this issue related to `cmake`: https://github.com/conan-io/conan/issues/7607#issuecomment-682370857

**Comment by memsharded** [comment]
This kind of bootstrapping, depending on a previous version, is now possible in Conan 2.

Closing this as solved, please create new tickets if necessary against last Conan, thanks for your feedback.
