### ISSUE TITLE
[feature] Add documentation for min_conan_version

### ISSUE THREAD

**Issue by MaciejKucia** [conan-io/conan#7620]
I am a bit confused about the new attribute. This is how I use it:

```
class Lib(ConanFile):
    min_conan_version = "1.26"
```
But I have also seen:
```
min_conan_version = "1.26"

class Lib(ConanFile):
    pass
```

Is the first option valid? Would be cool to have this in https://docs.conan.io/en/latest/

- [✔] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @MaciejKucia 

It seems the documentation is there, was added in: https://github.com/conan-io/docs/pull/1788/files

You can find it live here: https://docs.conan.io/en/latest/reference/conanfile/other.html#requiring-a-conan-version-for-the-recipe

Where did you see such syntax? It is actually ``required_conan_version`` and not ``min_conan_version``, and it is an expression, not a value.

**Comment by MaciejKucia** [comment]
Thanks! Now it all makes sense and I can find all related announcements and documentation.

As a side note, the name `required_conan_version` is not very good as it implies specific version rather than range.

**Comment by memsharded** [comment]
> As a side note, the name required_conan_version is not very good as it implies specific version rather than range.

It was named after the same ``required_conan_version`` in conan.conf, it didn't seem bad to have ``required_conan_version >= 1.28``.
