### ISSUE TITLE
[bug] Review upload protocol to avoid missing recipes in remote

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#7628]
We have seen some issues in Conan Center where packages were uploaded to Artifactory and the conanfile.py was missing.
Some of these issues can be caused by several retries on a poor connection or maybe parallel uploads producing race conditions.

In the specific case we faced, the conanmanifest.txt was uploaded while the conanfile.py was not. This produced that the next package uploads that uploaded the conanfile.py said: "recipe up to date, skipping upload".

We should review the upload protocol so that the manifest file is always the latest file to be uploaded in order to mitigate this kind of issue.

**Comment by memsharded** [comment]
I am checking this issue. The ``conanmanifest.txt`` is already the latest file to be uploaded, in both V1 and V2 apis, so the race condition should be elsewhere, not in the order of file upload.

**Comment by memsharded** [comment]
Conan 2.0 has developed completely new logic to upload packages, based on revisions, that hopefully will reduce these issues.
