### ISSUE TITLE
[question] How to use Development flow with conadata.yml?

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#7629]
Hi!

As you know, the [package development flow](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html) is useful when creating complex recipes which take many minutes to be built, so we can split step-by-step during the process.

However, with the introduction of [conandata.yml](https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html) we can not follow the same steps as described in the docs. For instance, the command `conan source` does not accept reference anymore, so we can't use a generic recipe:

    # a recipe using conandata.yml
    $ conan source . -sf=/tmp/source 
    ERROR: conanfile.py (foo/None): Error in source() method, line 14
	tools.get(**self.conan_data["sources"][self.version])
	KeyError: None

Of course, we can run `conan install` first and generate `conan.lock`:

    $ conan install . 0.1.0@user/channel
    conanfile.py (foo/0.1.0): Generator txt created conanbuildinfo.txt
    conanfile.py (foo/0.1.0): Generated conaninfo.txt
    conanfile.py (foo/0.1.0): Generated graphinfo
    $ conan source . -sf=/tmp/source 
    Using lockfile: 'conan.lock'
    Using cached profile from lockfile
    conanfile.py (foo/0.1.0): Configuring sources in /tmp/source
    conanfile.py (foo/0.1.0): Executing exports to: /tmp/source
    conanfile.py (foo/0.1.0) exports: File 'conandata.yml' found. Exporting it...

So, or we can update the docs, adding how to use the development flow and conandata.yml, running conan install before as workaround, or we can update `conan source` command to support conandata.yml.

- [ X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
the `conan_data` attribute is loaded with the `ConanFile` class, so it should be available at every method and command that loads the python class. See test at https://github.com/conan-io/conan/pull/7652

I think the error above comes from the `version` attribute being `None`.

**Comment by memsharded** [comment]
PR #7652 proves it is not a conandata issue, just a version=None issue

The UX improvement that is possible here (Conan 2.0 in any case) is creating a wrapper so ``self.version`` raises with a better message if it is ``None``.

**Comment by uilianries** [comment]
Thanks for all explanation, so we can update Conan docs. WDYT?

**Comment by memsharded** [comment]
Closed by #7652, please @uilianries open a short PR updating the docs if you think it is worth it. Thanks!
