### ISSUE TITLE
Conan.io web CSS problems in Chrome/Linux

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#763]
https://twitter.com/bjorn_fahller/status/808755267148087296

"Only problem in Chrome (linux) I realise. Looks good in firefox. jfrog/conan logo is huge&blocky. Text and menues flush left."

cc/ @rollbear

**Comment by memsharded** [comment]
Tested Chrome, Firefox, Edge in Win, everything OK.
Firefox in Linux VM, also OK. Problems installing chrome in Linux, so couldn't reproduce

**Comment by lasote** [comment]
I use Chrome in Linux, everything ok.

**Comment by rollbear** [comment]
I'm about as far from being a web developer as you can get, so take my observations for what they are.

Using the Inspection functionality of Chrome, I see some errors shown:

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css Failed to load resource: net::ERR_INSECURE_RESPONSE

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css Failed to load resource: net::ERR_INSECURE_RESPONSE

https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css Failed to load resource: net::ERR_INSECURE_RESPONSE

I assume this has something to do with it.

**Comment by rollbear** [comment]
For what it's worth:

Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.10 (64-bit)

**Comment by lasote** [comment]
I have almost same version: Version 53.0.2785.113 (64-bit) in a debian linux, also tested in ubuntu. 
You are right about the errors, they are the cause. But not sure why the insecure response, I've checked the certificates from maxcdn.bootstrapcdn.com and looks good.

**Comment by rollbear** [comment]
Just checked from work, and there it works nicely. It too runs Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

The difference being Ubuntu 16.04 at work, where it's fine, and 16.10 at home, where it fails.

Seems to me like the version is a red herring, though.

**Comment by Mikayex** [comment]
I'm on Ubuntu 16.04 / Chrome 55.0.2883.87 (64-bit) and I have another website related issue (BTW, I did't have the same problem as @rollbear)

It seems the description field have all its spaces stripped : 
![image](https://cloud.githubusercontent.com/assets/6607623/21188727/97f886cc-c21c-11e6-900a-a844ce1a59f7.png)

(page of screenshot https://conan.io/source/nasm/2.12.02/Mikayex/stable)

**Comment by lasote** [comment]
@Mikayex Description stripped problem has been fixed now. Thanks for reporting.

**Comment by rollbear** [comment]
I now see other sites malfunction for the same reason when using Chromium, but not other browsers. I can only assume the problem is on my end and not conan.io, so I propose closing this issue.

**Comment by memsharded** [comment]
Yes, thanks very much for your feedback and help in any case. Cheers!
