### ISSUE TITLE
[question] cmake_find_package generator: version file

### ISSUE THREAD

**Issue by joxoby** [conan-io/conan#7631]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**The problem**

I have been investigating the idea of adding the [Ignition Robotics](gnitionrobotics.org) [projects](https://github.com/ignitionrobotics) to Conan. I have succeeded in creating a recipe for [ign-math](https://github.com/ignitionrobotics/ign-math) but I have encountered a problem making the [ign-msgs](https://github.com/ignitionrobotics/ign-msgs) one (the latter depends on the former). You can see in its `CMakeLists.txt` that `ign-msgs` includes `ign-math` [here](https://github.com/ignitionrobotics/ign-msgs/blob/268ddcc824836766975f3d4f43e1473b80b31c18/CMakeLists.txt#L68). After searching, it tries to get the major version of `ign-math` by doing:
```cmake
set(IGN_MATH_VER ${ignition-math6_VERSION_MAJOR})
```
The cmake variable `<packageName>_VERSION_MAJOR` will only be set during `find_package()` if there's a [version file](https://cmake.org/cmake/help/latest/command/find_package.html#version-selection) next to the `Find<packageName>.cmake` file.

**The question / discussion is**: Should Conan have the option to produce version files when using the `cmake_find_package` generator?

**Comment by memsharded** [comment]
Hi @joxoby 

Have you tried the ``cmake_find_package_multi`` generator? this is an evolution of the former that adds version files, together with the capacity to manage multi-configuration (Release/Debug) for environments like Visual Studio. This is the one that will probably become the main one in Conan 2.0.

**Comment by joxoby** [comment]
@memsharded `cmake_find_package_multi` is exactly what I needed. Thank you very much for the help.

**Comment by memsharded** [comment]
Excellent! Let's close this issue now, do not hesitate to open a new one if you have any further question!
