### ISSUE TITLE
[bug] CLI command install with full reference

### ISSUE THREAD

**Issue by AbdDevP** [conan-io/conan#7637]
### Environment Details (include every applicable attribute)
  * Operating System+version: OSX 10.15.4
  * Compiler+version: apple-clang 11.0
  * Conan version: 1.28.2
  * Python version: 2.7.16

### Steps to reproduce (Include if Applicable)
Any package install like 
`lib/1.0@conan/stable#RREV:PACKAGE_ID`
Or
`lib/1.0@conan/stable#RREV:PACKAGE_ID#PREV`

### Logs (Executed commands with output) (Include/Attach if Applicable)

ERROR: Conanfile not found at .....

**Comment by memsharded** [comment]
Hi @abdennourmiage 

This is not a bug.

You cannot install a package defining the package-id. You can only provide the reference as ``lib/version@user/channel``. You might include the ``RREV`` if you enabled revisions.

**Comment by AbdDevP** [comment]
Hi @memsharded.

Maybe the documentation(see below) is no longer up to date?  

I would like to use conan on my production server and be able to provide it with a unique reference of a binary with its dependencies so that it just fetch it and not reinterpret the version ranges. Like this `conan install hello/1.0@user/stable#RREV:PACKAGE_ID#PREV -g virtualrunenv`

I know that I can use dependency locking but with the constraint of transferring the file by ftp to the production server. And does that not duplicate as long as conan guarantees the immutability of a revision?

Thx.


> <img width="779" alt="screenshot docs conan io:en:latest:versioning:revisions" src="https://user-images.githubusercontent.com/9390757/91904887-f6a52b00-eca5-11ea-9e3d-891f51f7a33b.png">

**Comment by memsharded** [comment]
Hi @abdennourmiage 

That is just a poorly written or expressed sentence. The ``You can specify the references in the following formats`` is a separate paragraph of the previous one, it doesn't mean that those things can be passed to the ``conan install`` command. You will not find an example of this in the docs, please refer to the ``conan install`` reference and examples to check this.

> I would like to use conan on my production server and be able to provide it with a unique reference of a binary with its dependencies so that it just fetch it and not reinterpret the version ranges. Like this conan install hello/1.0@user/stable#RREV:PACKAGE_ID#PREV -g virtualrunenv

Revisions can be used in that way, no problem. But the package_id cannot be forced to be installed with ``conan install``, as the package_id is a function (a hash) of settings, options and dependencies. You need to provide a profile, or the settings, options that you want, and Conan will be computing not only the package_id of the required package, but also the transitive dependencies, including the package_id of the transitive dependencies.

Maybe what you are looking for is the ``conan download`` command? With that you might specify the thing you want to download with that syntax. Be aware that ``conan download`` downloads only that package, and not any of the transitive dependencies. It doesn't use generators or generate any file to be used by a build system, as it lacks the necessary information to reconstruct the whole dependency graph.

Please let me know if this clarifies the issue.

**Comment by AbdDevP** [comment]
Yes, I understand Thank you.

The "download" function is not a solution for me because I want to use the virtual environment generator.
The advantage of this solution is that the production server only pulls the updated packages and I am therefore not obliged for each micro delivery to repackage all the dependencies with for example the deployment generation function (-g deploy)

My concern is always to ensure that the version installed in production is exactly the same as the one I built on my build server (which is identical to the production server)

The solution with a lock file is disabling because a physical transfer must take place with the production server and then the question of versionning of the lock file arises because it is generated after construction of the package and given that my revision uses the SHA of the GIT commit. the revision SHA will never be able to contain the lock file.
I would always have two different commits. One which is the revision of the package and another which will contain the lock file from the previous commit. Not TOP!

Do you see a possible solution to answer this problem?

It seems to me that conan generates a lock file when using package_revision_mode. In the end, if conan install with the full revision id on a package using package_revision_mode, could Conan not default to the lock file present in the package?

**Comment by memsharded** [comment]
> The solution with a lock file is disabling because a physical transfer must take place with the production server and then the question of versionning of the lock file arises because it is generated after construction of the package and given that my revision uses the SHA of the GIT commit. the revision SHA will never be able to contain the lock file.
I would always have two different commits. One which is the revision of the package and another which will contain the lock file from the previous commit. Not TOP!

> Do you see a possible solution to answer this problem?

Yes, in the CI flows that we are at the moment considering, the lockfiles are not stored in version control. Instead, we use a generic Artifactory repo to store lockfiles, associated with the CI job. Typically we create there a path that is a combination of the CI job unique ID, and could also include some information about the PullRequest or Branch identifiers. This allows to manage and reproduce any build, because builds are also larger than single packages, builds affect multiple packages and possibly multiple final products. 

Lets say that you have ProductA -> LibB -> LibC ->LibD, and also ProductB -> LibC ->LibD. 
Now there are some changes in LibC, then you want to rebuild LibB, ProductA, ProductB, but not LibD. You can capture 2 lockfiles (xN configurations), one for each product. You store all these lockfiles in the Artifactory repo folder, not in a specific package version control.

Does it make sense?

**Comment by AbdDevP** [comment]
I find it a lot of constraint.

Would not systematically generating a lock file each time a product package is created and integrating it into the Conan package be a better solution?

When a consumer wishes to pull a product via the install command, he could request that the attached lock file be used (or default behavior).
Thus, the packages could be reproduced identically without the need to version the lock file on Git.

**Comment by abdennourmiage** [comment]
> > The solution with a lock file is disabling because a physical transfer must take place with the production server and then the question of versionning of the lock file arises because it is generated after construction of the package and given that my revision uses the SHA of the GIT commit. the revision SHA will never be able to contain the lock file.
> > I would always have two different commits. One which is the revision of the package and another which will contain the lock file from the previous commit. Not TOP!
> 
> > Do you see a possible solution to answer this problem?
> 
> Yes, in the CI flows that we are at the moment considering, the lockfiles are not stored in version control. Instead, we use a generic Artifactory repo to store lockfiles, associated with the CI job. Typically we create there a path that is a combination of the CI job unique ID, and could also include some information about the PullRequest or Branch identifiers. This allows to manage and reproduce any build, because builds are also larger than single packages, builds affect multiple packages and possibly multiple final products.
> 
> Lets say that you have ProductA -> LibB -> LibC ->LibD, and also ProductB -> LibC ->LibD.
> Now there are some changes in LibC, then you want to rebuild LibB, ProductA, ProductB, but not LibD. You can capture 2 lockfiles (xN configurations), one for each product. You store all these lockfiles in the Artifactory repo folder, not in a specific package version control.
> 
> Does it make sense?
