### ISSUE TITLE
how to specify visual studio version

### ISSUE THREAD

**Issue by xiedeacc** [conan-io/conan#7640]
I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md)

I have vs2019 and vs2017 in my system, conan with cmake use vs2019 default, but I need vs2017 for I've use qt5.14.2 in my project,
how to specify vs version? thanks a lot

**Comment by memsharded** [comment]
When you install do:

```bash
$ conan install -s compiler="Visual Studio" -s compiler.version=15
```

You can also make this change permanent by edition your default profile (check the docs, you can either edit the ``<userhome>/.conan/profiles/default`` or use the ``conan profile`` command).

**Comment by xiedeacc** [comment]
> When you install do:
> 
> ```shell
> $ conan install -s compiler="Visual Studio" -s compiler.version=15
> ```
> 
> You can also make this change permanent by edition your default profile (check the docs, you can either edit the `<userhome>/.conan/profiles/default` or use the `conan profile` command).

it seems can implement Cmake classs in conanfile.py 
https://docs.conan.io/en/latest/reference/build_helpers/cmake.html

**Comment by memsharded** [comment]
Hi @xiedeacc 

> it seems can implement Cmake classs in conanfile.py

No idea what you mean, please clarify

**Comment by xiedeacc** [comment]
> Hi @xiedeacc
> 
> > it seems can implement Cmake classs in conanfile.py
> 
> No idea what you mean, please clarify

your answer is right

**Comment by xiedeacc** [comment]
thanks a lot
