### ISSUE TITLE
[question] conan create uses option also for test which might not exist

### ISSUE THREAD

**Issue by sturmf** [conan-io/conan#7642]
I just tried to run a conan create on the gtest packge in conan-center-index but it won't work since the specified options for the main packge do not fully exist for the test package and therefore it stops. Is this intended? This would render the conan create command useless in this case I think.

```
X:\USER\git\conan-center-index>conan create recipes/gtest/all gtest/1.10.0@user/stable -o shared=False -s arch=x86_64 -s compiler.version=15 -s build_type=Debug -s compiler.runtime=MDd
Exporting package recipe
gtest/1.10.0@user/stable exports: File 'conandata.yml' found. Exporting it...
gtest/1.10.0@user/stable exports: Copied 1 '.yml' file: conandata.yml
gtest/1.10.0@user/stable exports_sources: Copied 1 '.txt' file: CMakeLists.txt
gtest/1.10.0@user/stable exports_sources: Copied 3 '.patch' files: gtest-1.10.0-override.patch, gtest-1.10.0.patch, gtest-1.8.1.patch
gtest/1.10.0@user/stable: The stored package has not changed
gtest/1.10.0@user/stable: Exported revision: b9246e76ad77bd76ff366505578e360d
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=15
os=Windows
os_build=Windows
[options]
shared=False
[build_requires]
[env]

ERROR: X:\USER\git\conan-center-index\recipes\gtest\all\test_package\conanfile.py: option 'shared' doesn't exist
Possible options are []
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Hi @sturmf!

As described in the [documentation](https://docs.conan.io/en/latest/creating_packages/getting_started.html#creating-and-testing-packages), you should add the package name to the option argument. Your command have to be updated:

    conan create recipes/gtest/all gtest/1.10.0@user/stable -o gtest:shared=False -s arch=x86_64 -s compiler.version=15 -s build_type=Debug -s compiler.runtime=MDd

As you can see, the correct argument is `-o gtest:shared=False`. If you want not only GTest as static, but force all dependencies too, you can use `-o *:shared=False`.

BTW static library is the default option for 95% of recipes in CCI, so if you don't pass anything, it will be static anyway. 

Regards.

**Comment by sturmf** [comment]
Hi @uilianries 

that makes sense of course! So from my point of view this topic is done.
The reason why I don't use the default is that I want to do kind of a a matrix type build whith e.g. "Debug,Release", "shared,static" etc...

Kind regards,
Fabian
