### ISSUE TITLE
[bug] Auto-configuration of fPIC seems to be faulty with new checks for fPIC option

### ISSUE THREAD

**Issue by foundry-markf** [conan-io/conan#7643]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10/macOSX 10.13
  * Compiler+version: VS2017/Xcode 10
  * Conan version: 1.28.1
  * Python version: Python 3.7.7

### Steps to reproduce (Include if Applicable)
We recently moved from Conan 1.24 to 1.28, and have V2 mode enabled, to watch for potential issues. And I noticed this bit of code introduced in 1.26, was raising exceptions on Windows (for fPIC present) and macOSX (for fPIC and shared present and True).

https://github.com/conan-io/conan/blob/develop/conans/client/conanfile/configure.py#L48-L67
```
def _validate_fpic(conanfile):
    v2_mode = get_env(CONAN_V2_MODE_ENVVAR, False)
    toolchain = hasattr(conanfile, "toolchain")

    if not (toolchain or v2_mode):
        return
    fpic = conanfile.options.get_safe("fPIC")
    if fpic is None:
        return
    os_ = conanfile.settings.get_safe("os")
    if os_ and "Windows" in os_:
        if v2_mode:
            raise ConanInvalidConfiguration("fPIC option defined for Windows")
        conanfile.output.error("fPIC option defined for Windows")
        return
    shared = conanfile.options.get_safe("shared")
    if shared:
        if v2_mode:
            raise ConanInvalidConfiguration("fPIC option defined for a shared library")
        conanfile.output.error("fPIC option defined for a shared library")
```

We had previously been using the behaviour in AutoToolsBuildEnvironment and the CMake utility to automatically set the fPIC relevant states on those classes when the fPIC option was available.

But we've noted that if we delete the fPIC option to satisfy when shared=True check in _validate_fpic, then 

https://github.com/conan-io/conan/blob/develop/conans/client/build/autotools_environment.py#L79-L84
```
    def _configure_fpic(self):
        if not str(self._os).startswith("Windows"):
            fpic = self._conanfile.options.get_safe("fPIC")
            if fpic is not None:
                shared = self._conanfile.options.get_safe("shared")
                return True if (fpic or shared) else None
```

and

https://github.com/conan-io/conan/blob/develop/conans/client/toolchain/cmake.py#L253-L266
```
    def _deduce_fpic(self):
        fpic = self._conanfile.options.get_safe("fPIC")
        if fpic is None:
            return None
        os_ = self._conanfile.settings.get_safe("os")
        if os_ and "Windows" in os_:
            self._conanfile.output.warn("Toolchain: Ignoring fPIC option defined for Windows")
            return None
        shared = self._conanfile.options.get_safe("shared")
        if shared:
            self._conanfile.output.warn("Toolchain: Ignoring fPIC option defined "
                                        "for a shared library")
            return None
        return fpic
```

will both early out and return None, so autotools and cmake are no longer configured as expected.

The behaviour we were expecting was that if fPIC is not available, the value of shared (if available) would be returned for use.

**Comment by memsharded** [comment]
Hi @foundry-markf 

To clarify, ``CONAN_V2_MODE`` is possibly something you don't want to have enabled for production. It is great if you run some job and report to us, that is really useful, but having it set in production might unexpectedly break your build as we start to introduce V2 changes.

I need to understand a bit better.

> We had previously been using the behaviour in AutoToolsBuildEnvironment and the CMake utility to automatically set the fPIC relevant states on those classes when the fPIC option was available.

Does it mean that in ``autotools`` it is always necessary to define ``'-fPIC'``, even if it is a shared library? I thought it was not necessary, as basically it is a nonsense, isn't it? What am I missing here? At least in the new CMake toolchain it should work, because the value is mostly intended for CMake, and CMake will do the right thing internally even if not defined explicitly for shared libraries?

Thanks very much for your detailed report!

**Comment by foundry-markf** [comment]
Hi,
First of all, apologies for a tardy reply.

So yes, I've only got CONAN_V2_MODE enabled locally. We haven't got in production. I just wanted to keep abreast of any breaking points.

Agreed that it should be nonsense to _have_ to manually enable fPIC when building shared libraries, so my observation initially is that it seemed to be contradictory (fPIC wasn't defined at all, were autotools/CMake support handling this appropriately).

I wrote a test case to exercise lacking the fPIC option in a conan recipe with both CMake and autotools build scripts., The autoconf scripts are a bit rough around the edges as it was my first endeavour writing them from scratch, but it did show something (agreeing with what you said).
I first ran them on Ubuntu 18, and was confused because I couldn't see a mechanism for not always having fPIC enabled.
Then I ran it on CentOS 7 (our go-to distro in the office), and it behaved as expected - fPIC enabled for shared libs without having to specify it manually, fPIC disabled for static libs.
Turns out that GCC on Ubuntu is compiled with --enable-default-pie, so -fPIC is implied on all builds. (You can disable with -fno-PIC though, but yuck.)
We also believe that this is also the case with Apple's clang - so all builds are -fPIC enabled by default. (Not confirmed that since llvm-config wasn't available, but a test suggested it.)

The test if you're interested is attached. Rough instructions:
> I usually put it into an empty git repo, so I can clean it after each run.
There are scripts inside to do each type of build, e.g.
git clean -x -d -f && ./conan_cmake_shared.sh
Auto tools requires another step (and autoconf and libtool packages installed):
git clean -x -d -f && ./bootstrap.sh && ./conan_autotools_shared.sh
In each case, the compilation will fail on a #error, indicating whether fPIC was detected or not.

[fpic_test.zip](https://github.com/conan-io/conan/files/5201561/fpic_test.zip)

The only confusing this is that one of my peers saw different behaviour to this, after removing the fPIC option, he had to manually enable fPIC in an autotools build for a shared library build. We've not got to the bottom of that yet.

Overall, I believe I was mistaken in how I thought Conan's autotools/cmake support was handling it, so sorry about the red herring. There are definitely a few external factors that can influence it though.

Regards,
Mark
