### ISSUE TITLE
[bug] Deploy generator does not copy symbolic links to directories

### ISSUE THREAD

**Issue by hifabian** [conan-io/conan#7647]
Symbolic links to directories are not copied by the `deploy` command.
For example, the following structure will be mising `root/current/`:
```
root/
 | 1.0/
 - | file.txt
 | 1.2/
 - | file.txt
 | current/ -> 1.0/
 | file.txt -> current/file.txt
```
Since `root/current/` is not copied, it will break the other symbolic links such as `root/file.txt`.

Similar issue to #6628 but for symbolic links to directories instead of files.

A simple solution would be to just add symbolic links to directories to the files copied, but you cannot add them to the copied files list. So essentially something like this:
```diff
...
            rootpath = self.conanfile.deps_cpp_info[dep_name].rootpath
-            for root, _, files in os.walk(os.path.normpath(rootpath)):
+            for root, dirs, files in os.walk(os.path.normpath(rootpath)):
+               files += [d for d in dirs if os.path.islink(os.path.join(root, d))]
                for f in files:

...

                        shutil.copy(src, dst)
-                    copied_files.append(dst)
+                    if f not in dirs:
+                       copied_files.append(dst)
        return self.deploy_manifest_content(copied_files)
```
I have not tested this extensively so I will not open a pull request. It might also be a good idea to add this case to the `DeployGeneratorSymbolicLinkTest`.

### Environment Details
  * Operating System+version: Ubuntu 20.04 / 18.04
  * Conan version: 1.30.0-dev
  * Python version: 3.8.2

### Steps to reproduce

Deploy for example `icu`:
`conan install icu/64.2@bincrafters/stable -g deploy`

### Logs (Executed commands with output)

```
...
ERROR: Generator deploy(file:deploy_manifest.txt) failed
[Errno 2] No such file or directory: 'somewhere/icu/lib/icu/pkgdata.inc'
ERROR: [Errno 2] No such file or directory: 'somwhere/icu/lib/icu/pkgdata.inc'
```

**Comment by danimtb** [comment]
Hi, thanks for the detailed report and the proposal.

I see this could be an easy fix so if you are willing to contribute the changes we can help you with the tests  😄

**Comment by hifabian** [comment]
Hi @danimtb, as you can see I did open now a pull request. The changes are exactly what I wrote above (still excluding tests). I did test it locally somewhat crudely but it worked as expect.

_(I actually opened two pull requests because, as I wrote in the PR, initially my github account had no email attached which meant I could not accept the CLA)_
