### ISSUE TITLE
[question] Using multiple conanfile.txt in one project

### ISSUE THREAD

**Issue by hdnn** [conan-io/conan#7649]
OS: Windows 10
IDE: Visual Studio (2017\2019)

I have next configuration: conan **1.18.5** and some number of conanfiles, for example:
```
//conanfile_openssl.txt
[requires]
OpenSSL/1.0.2t@hdnn/proto
zlib/1.2.11@hdnn/proto

[generators]
visual_studio_multi

[imports]
bin, *.dll -> .
```
and
```
//conanfile_grpc.txt
[requires]
grpc/1.23.0@hdnn/stable

[generators]
visual_studio_multi
```
When I generate `.props` files for Visual Studio by using `conan install ...` command, conan versions >=1.18.5 generate for me `.props` with tags filled with package paths:
```
<AdditionalIncludeDirectories>$(USERPROFILE)\.conan\data\OpenSSL\1.0.2t\hdnn\proto\package\ae39335471abb73fe6263cf7a8aa7d83dfe2b9cf\include;$(USERPROFILE)\.conan\data\zlib\1.2.11\hdnn\proto\package\42aa8cf3b4ce5d1dd14cf0ed0b1ea3a1e677b0ac\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
```
And if I want to use `OpenSSL` and `grpc` in one project I can just import two `.props` files and will have merged `<AdditionalIncludeDirectories>` with `OpenSSL`, `zlib` and `grpc` include paths.

BUT NOW, in versions 1.19.0+`.props` files looks like that:
```
<ConanIncludeDirectories>$(USERPROFILE)\.conan\data\OpenSSL\1.0.2t\hdnn\proto\package\ae39335471abb73fe6263cf7a8aa7d83dfe2b9cf\include;$(USERPROFILE)\.conan\data\zlib\1.2.11\hdnn\proto\package\42aa8cf3b4ce5d1dd14cf0ed0b1ea3a1e677b0ac\include;</ConanIncludeDirectories>
<AdditionalIncludeDirectories>$(ConanIncludeDirectories)%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
```
and for the same case with two `.props` in one project, Visual Studio will unwrap $(ConanIncludeDirectories) as `OpenSSL`+`zlib` or just `grpc` paths - depends on props order in Property Browser.

So, how I can resolve it?

PS: use only one `conanfile.txt` is bad suggestion for my case.

**Comment by danimtb** [comment]
Hi,

I think this was changed to get a more uniform generation of files on the Conan client side and this use case was not contemplated.

However, we are shifting towards generating one prop file for each requirement in your conanfile, so we introduced a new generator `msbuild` https://docs.conan.io/en/latest/reference/generators/msbuild.html that does exactly what you request.

It is still experimental as we have to develop it further but I think it covers your use case completely.

Another thing I'd like to know is, why do you want to mix props files coming from different `conan install` invocations? Beware that it could be dangerous as Conan calculates 2 different graphs for each install and could lead to potential requirements collision or even mixing incompatible packages.

**Comment by hdnn** [comment]
@danimtb, thanks, it helped!

This is the way it happened historically). I have Solution with 200+ projects, most part of them used `.props` generated from `conanfile_common.txt`(it contain `boost`, `xml`, `ini` libraries). But some part of project also need rarely used libraries(like `grpc`), that I don't want to include into all projects

**Comment by danimtb** [comment]
Thanks for shraing and glad it helped. Just keep in mind the downsides of my comment above in case you experience some graph issues or collisions with dependencies. But it seems you know what you are doing! 👍
