### ISSUE TITLE
how to set msvc compile flag?

### ISSUE THREAD

**Issue by xiedeacc** [conan-io/conan#7650]
msvc support utf-8 not very well, when file was saved with utf8 and code or commentmay contain chinese character, may cause compile error, fix solution in vs studio was use /utf-8 or /source-charset:utf-8 flag, how can I set msvc compile option in conan?

**Comment by danimtb** [comment]
Hi! If you are using the `MSBuild()` helper in your recipes you can use [`get_command()`](https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html#get-command) and append the needed flag at the end. 

Try something like:

```
msbuild = MSBuild(self)
cmd = msbuild.get_command(...) + "/utf-8"
self.run(cmd)
```

**Comment by memsharded** [comment]
Problem with that approach is that it is missing a lot of stuff that ``MSBuild()`` helper is doing.
The ``properties`` argument can only set ``/p:property=value``, it seems like we need here a similar ``args`` argument that can add these arbitrary command line arguments. This would be more a feature request than a question, wouldn't it @danimtb ?

**Comment by danimtb** [comment]
Agree that an argument value with custom flags will be much better in this case. We are already doing that in other helpers

**Comment by danimtb** [comment]
I have opened a feature request here https://github.com/conan-io/conan/issues/7653. The alternative proposed above is still possible although it will require a little bit more code.

**Comment by memsharded** [comment]
For the reason described in https://github.com/conan-io/conan/issues/7653#issuecomment-686541278, the above recommended approach to add it to the command line might not work (that is the command line for the msbuild, not for the compiler). The current workaround is to add it to the Visual project itself (in .vcxproj files). The feature request might be able in the future to inject compiler options, but it seems to me that it is still desired that these options would be integrated in the visual project files.

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, where we added some confs to be able to pass flags to the compiler from the CLI/profiles, see `tools.build:cxxflags` and related confs [here](https://docs.conan.io/2/reference/commands/config.html)
