### ISSUE TITLE
[feature] MSBuild: Provide an argument to add custom flags for the compiler

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#7653]
Coming from #7650.

The `MSBuild()` should provide a way to inject custom flags for the compiler.

List of compiler options that can be used: https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=vs-2019

This is something to consider for a MSBuild or MSVC toolchain helper.

**Comment by memsharded** [comment]
There is a problem here. I thought it was an MSBuild command line option, but it seems I was wrong.

To pass this to the compiler, this might not be an easy issue at all, but requires to possibly modify the generated .props file (in the future it will be part of the MSBuildToolchain, when it is implemented).

**Comment by danimtb** [comment]
I am correcting the description after evaluating again the argument flags. Finally related more to the toolchain discussion here https://github.com/conan-io/conan/issues/7280

**Comment by memsharded** [comment]
MSBuildToolchain accepts ``tools.build:cxxflags`` to inject flags, closing as solved.
