### ISSUE TITLE
[feature] Create a helper class/function/object to calculate compiler flags

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7656]
We are currently able to get the information of a depdency's `cpp_info` through `self.deps_cpp_info`.
The build helpers use the information to create targets that contain all information of all dependencies.
I think it would be useful to also have this information in the `conanfile.py` itself.

My use case is a autotools `configure` script.
I need to pass the link flags required for a dependency.
But that dependency has also some requirements, so I need to walk its requirements.
I think this should be made available through some conan api.
Using the default `autotools.libs` is not a solution, as that will contain all dependencies.
Some components are unwanted and need to be left out.

What I want is something as follows:is the following:

```python
flag_helper = FlagHelper(self)
# create a object that will contain all information about the 'comp' component of dependency 'dep'
# The 'full' argument will make the helper flatten the dependency tree
dep_comp_info = flag_helper.info(dependency="dep", component="comp", full=True)
# dep_comp_info will contain all compiler flags: cppflags/cflags/cxxflags/libs/ldflags/...
conf_args = [
    "DEP_COMP_LIBS={}".format(dep_comp_info.libs),
]
autotools = AutotoolsBuildEnvironment(self)
autotools.libs = []
autotools.configure(args=conf_args)
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Ahajha** [comment]
Curious about this one, there's still a TODO about this in the CPython recipe, is this possible now?

**Comment by memsharded** [comment]
I think this is outdated, at least refers to legacy integrations.
In theory the new ``PkgConfigDeps`` and ``AutotoolsDeps`` would be the recommended integrations to define flags from dependencies.

Also, it is not clear the need for bringing only the flags from 1 dependency in isolation, so this should be discussed a bit more in depth.

I am closing the ticket as outdated, if there is some new use that the new mentioned integrations are not handling, please create a new ticket referring to them. Many thanks!
