### ISSUE TITLE
How to correctly install a package from a local conan server ?

### ISSUE THREAD

**Issue by orgicus** [conan-io/conan#7657]
I'm running a test conan server using `gunicorn`.
I've placed a test pacakge in `.conan_server/data` and `search` seems to find it, but `install` fails.
I'm using conan 1.29.0 installed via `pip`

Here is the search output:
```bash
conan search "magic_enum/*" -r=all
Existing package recipes:
Remote 'conan':
magic_enum/0.6.6@d3/stable
Remote 'conan-center':
magic_enum/0.6.5
magic_enum/0.6.6
```

However the install output is not what I expect:
```bash
conan install "magic_enum/0.6.6@d3/stable" -r=conan
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=12
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
magic_enum/0.6.6@d3/stable: Retrieving from server 'conan'
magic_enum/0.6.6@d3/stable: Trying with 'conan'...
ERROR: magic_enum/0.6.6@d3/stable was not found in remote 'conan'
```

I've double checked the local network `conan` remote

```bash
conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
conan-transit: https://conan-transit.bintray.com [Verify SSL: True]
conan: http://10.105.1.69:9300/ [Verify SSL: True]
```

(I've tried removing it and adding again with Verify SSL disabled: that didn't make a difference in behaviour)

I've tried removing the package before install:
`conan remove -f magic_enum/0.6.6@d3/stable`

Since it wasn't in the local cache I've got: `ERROR: Recipe not found: magic_enum/0.6.6@d3/stable`

I’ve tried removing it from the conan remote and initially that didn’t work, then changed write permisions and restarted conan server then that worked. Restored the package on remote, tried again: made no difference.

I’ve also setup the `CONAN_TRACE_FILE` env. variable to see what’s going on.
It’s confusing that a GET on http://10.105.1.69:9300/v1/conans/search?q=magic_enum%2F%2A returns 
```JSON
{"results": ["magic_enum/0.6.6@d3/stable"]}
```
while http://10.105.1.69:9300/v1/conans/magic_enum/0.6.6/d3/stable/download_urls  returns 
```
Recipe not found: 'magic_enum/0.6.6@d3/stable'
```

Can you please point me in the right direction to debug why is the recipe not found and how to check/fix the package if it’s corrupted ?

Thank you,
George

**Comment by memsharded** [comment]
Hi @orgicus 

A couple of quick questions:

> I've placed a test pacakge in .conan_server/data and search seems to find it, but install fails.

I guess that you have uploaded it with the ``conan upload`` command, did you? Can you please share the trace?

Lets try to do the following, please include the whole output:
```
conan new hello/0.1 -s
conan create . george/stable
conan upload hello* -r=conan --all --confirm
conan remove hello* -f
conan install hello/0.1@george/stable -r=conan
```

It is possible that there is some configuration thing in the conan_server side (conan.conf). Pasting the traces from the server for the upload might help.
I would also recommend to use the ArtifactoryCE, you can get it in our downloads page and it is completely free. It has a WebUI, better permission control, can host multiple repositories in the same place, including generic repos, and scale the load better.

**Comment by orgicus** [comment]
Hi @memsharded 

Apologies for the delayed response and thank you for being quick assistance.

I realised I didn't have CMake in `%PATH%`, now that's sorted.

`conan new` worked, create did as well after the `%PATH%` update:

```batch
 conan create . george/stable
Exporting package recipe
hello/0.1@george/stable exports_sources: Copied 1 '.txt' file: CMakeLists.txt
hello/0.1@george/stable exports_sources: Copied 1 '.cpp' file: hello.cpp
hello/0.1@george/stable exports_sources: Copied 1 '.h' file: hello.h
hello/0.1@george/stable: The stored package has not changed
hello/0.1@george/stable: Exported revision: 522678c66d3315f8d3b296d1d60ccd2f
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=12
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

hello/0.1@george/stable: Forced build from source
Installing package: hello/0.1@george/stable
Requirements
    hello/0.1@george/stable from local cache - Cache
Packages
    hello/0.1@george/stable:e0a02d496bbb652b6295152dfce0d3937acc0b56 - Build

Installing (downloading, building) binaries...
hello/0.1@george/stable: WARN: Build folder is dirty, removing it: C:\.conan\data\hello\0.1\george\stable\build\e0a02d496bbb652b6295152dfce0d3937acc0b56
hello/0.1@george/stable: Copying sources to build folder
hello/0.1@george/stable: Building your package in C:\.conan\data\hello\0.1\george\stable\build\e0a02d496bbb652b6295152dfce0d3937acc0b56
hello/0.1@george/stable: Generator cmake created conanbuildinfo.cmake
hello/0.1@george/stable: Calling build()
-- The CXX compiler identification is MSVC 18.0.31101.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR


-- Build files have been written to: C:/.conan/data/hello/0.1/george/stable/build/e0a02d496bbb652b6295152dfce0d3937acc0b56
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/.conan/data/hello/0.1/george/stable/build/e0a02d496bbb652b6295152dfce0d3937acc0b56/src/CMakeLists.txt
  hello.cpp
  hello.vcxproj -> C:\.conan\data\hello\0.1\george\stable\build\e0a02d496bbb652b6295152dfce0d3937acc0b56\lib\hello.lib
  Building Custom Rule C:/.conan/data/hello/0.1/george/stable/build/e0a02d496bbb652b6295152dfce0d3937acc0b56/src/CMakeLists.txt
hello/0.1@george/stable: Package 'e0a02d496bbb652b6295152dfce0d3937acc0b56' built
hello/0.1@george/stable: Build folder C:\.conan\data\hello\0.1\george\stable\build\e0a02d496bbb652b6295152dfce0d3937acc0b56
hello/0.1@george/stable: Generated conaninfo.txt
hello/0.1@george/stable: Generated conanbuildinfo.txt
hello/0.1@george/stable: Generating the package
hello/0.1@george/stable: Package folder C:\.conan\data\hello\0.1\george\stable\package\e0a02d496bbb652b6295152dfce0d3937acc0b56
hello/0.1@george/stable: Calling package()
hello/0.1@george/stable package(): Packaged 1 '.h' file: hello.h
hello/0.1@george/stable package(): Packaged 1 '.lib' file: hello.lib
hello/0.1@george/stable: Package 'e0a02d496bbb652b6295152dfce0d3937acc0b56' created
hello/0.1@george/stable: Created package revision b10eb240623d250771922bf2337bc9a5
```

conan upload initially failed:

```batch
 conan upload hello* -r=conan --all --confirm
Uploading to remote 'conan':
Uploading hello/0.1@george/stable to remote 'conan'
Compressing conan_sources.tgz completed [3 files]
Please enter a password for "demo" account:
ERROR: hello/0.1@george/stable: Upload recipe to 'conan' failed: Permission denied for user: 'demo'. [Remote: conan]

ERROR: Errors uploading some packages

```
Then I enabled write permissions and restarted conan and moved a bit further:

```batch
conan upload hello* -r=conan --all --confirm
Uploading to remote 'conan':
Uploading hello/0.1@george/stable to remote 'conan'
Uploading conan_sources.tgz :   0%|          | 0.00/487 [00:00<?, ?B/s]ERROR: HTTPConnectionPool(host='localhost', port=9300): Max retries exceeded with url: /v1/files/hello/0.1/george/stable/0/export/conan_sources.tgz?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZV9wYXRoIjoiaGVsbG8vMC4xL2dlb3JnZS9zdGFibGUvMC9leHBvcnQvY29uYW5fc291cmNlcy50Z3oiLCJleHAiOjE1OTkxNjkwMjIsInVzZXJuYW1lIjoiZGVtbyIsImZpbGVzaXplIjo0ODd9.tvRNHxKpN5P4h4e9HpRsb1O3Xb7NC9Bu0HMZmPdc8Ps (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002987BBDBB38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Waiting 5 seconds to retry...
```

This is where it's stuck. Something is preventing upload. Currently I'm on running conan server on a VM.
I might try to run it on the same machine, getting read of one layer that could go wrong ?

Where could I find the traces from the server ?

Many thanks,
George

**Comment by memsharded** [comment]
Hi George,

The most common misconiguration in the server is in https://docs.conan.io/en/latest/uploading_packages/running_your_server.html#server-parameters, the ``host_name`` and ``public_port``, when running in dockers, virtual machines, etc. Please carefully read the docs, and check those values.

This is the process I would try to use to validate everything is running fine:

- Run an ArtifactoryCE in the same machine. It is typically as easy as downloading the .zip, unzipping, launching the launcher in the "bin" folder, and from there accessing http://localhost:8081 and following instructions. The conan docs also explain the basics for this.
- After familiarizing a bit with it, I would try to run it on the network, somewhere else, to make sure the network has access, etc.
- After that works, I would try to run it in the production environment, a VM or elsewhere (probably a VM is a bit inefficient, ArtifactoryCE is also released in a docker image, maybe that helps).

If you would still like to go with the conan_server, I would still follow the same process, start locally, then network, then in the production env.

The conan_server logs is stdout, wherever you are running it, you can probably redirect the stdout to somewhere like a file.

Please let me know how it goes. Thanks!

**Comment by AbrilRBS** [comment]
Closing as we didn't hear back from you in a while, feel free to reopen/create a new isse should anyone find a similar issue, thanks!
