### ISSUE TITLE
[feature] Expose information about dependencies versions into the build system

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#7669]
Sometimes a package may need to apply a specific workaround for a specific version of dependency package, but also be compatible with other versions of the same package, especially if downstream can override ti.

To simplify, let's consider that B depends on A. When B/1.0.0 was developed, only A/1.0.0 existed and B was developed against it.

Later, someone creates A/2.0.0, with breaking changes, so B/1.0.0 no longer compiles against A/2.0.0. After that, we can make B/1.0.1 which will fix its implementation to use A/2.0.0 API, but we also want for B/1.0.1 to also work with A/1.0.0, in case someone downstream overrides A to either 1.0.0 or 2.0.0 (or if there are multiple downstream which for whatever reasons need to use A/1.0.0 or A/2.0.0).

Currently, it's possible to check the version of A in the recipe of B, which is OK if B's build is invoked only via `conan build` and using conan helpers, as it gives the possibility to inform build system about the A's version (e.g. cmake variable).

However, during the development of B, this information is not available, i.e. in cmake case, there is no cmake variable `CONAN_PACKAGE_A_VERSION` which contains the version of A used. If such a feature is added, then a build system could take care about specific needs of compiling B against A/1.0.0 or A/2.0.0 (for example, maybe some different flags are needed).

Do you think it may be a good idea to expose package information to the build system? I guess other build systems could also benefit from that, not only CMake.

**Comment by SpaceIm** [comment]
I don't know for others generators, but at least `cmake_find_package_multi` exposes `Lib_VERSION` variable in CMake config file.

**Comment by memsharded** [comment]
CMakeDeps generated files define ``set({{ file_name }}_VERSION_STRING "{{ version }}")`` for each package, that would be enough for CMake.
For other build systems, it doesn't seem a relevant use case so far.
Closing the ticket as solved in CMakeDeps
