### ISSUE TITLE
[bug] Conan 1.28.2/1.29.0 deb package is not functional on Debian

### ISSUE THREAD

**Issue by aloubiex38** [conan-io/conan#7670]
### Environment Details (include every applicable attribute)
  * Operating System+version: Debian 10 buster
  * Compiler+version: NA
  * Conan version: 1.28.2/1.29.0
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)
Install debian .deb conan package
Launch conan comand

**Comment by aloubiex38** [comment]
This bug is basically the same as https://github.com/conan-io/conan/issues/6399

The .deb package is broken since conan 1.28.2

error:
[20399] Error loading Python lib '/usr/bin/libpython3.6m.so.1.0': dlopen: /usr/bin/libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

**Comment by czoido** [comment]
Hi @aloubiex38,
Thanks a lot for reporting. I reproduced the issues.
For the last releases we had to update `pyinstaller` version to generate the deb packages so that is what could be causing the issue (https://github.com/conan-io/conan/issues/6399#issuecomment-578841644).
We'll try to fix as soon as possible.

**Comment by czoido** [comment]
Hi @aloubiex38,
We have updated the deb packages for `1.28.2` and `1.29.0` and they seem to be working fine now. Also added some tests for this in the release process.
Please, could you confirm that they are working fine for you so we can close the issue?
Thanks!

**Comment by aloubiex38** [comment]
Hi,

Just tried the 1.29.0 and it works well.

Thank you for the quick resolve. 
You can close the issue.
