### ISSUE TITLE
[bug] ITK recipe fails to find and apply patches

### ISSUE THREAD

**Issue by akalali** [conan-io/conan#7671]
### Environment Details
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 2017**
  * Conan version: **1.29.0**
  * Python version: **3.8.2**

### Steps to reproduce
Simple conanfile.txt
```
[requires]
itk/5.1.0

[generators]
cmake
```

Package installed with `conan install --build=itk`

### Logs

itk/5.1.0: Configuring sources in .conan\44644c\1
Downloading InsightToolkit-5.1.0.tar.gz completed [20209.31k]

itk/5.1.0: Copying sources to build folder
itk/5.1.0: Building your package in .conan\b3e9e7\1
itk/5.1.0: Generator cmake_find_package created FindDCMTK.cmake
itk/5.1.0: Generator cmake_find_package created Finddouble-conversion.cmake
itk/5.1.0: Generator cmake_find_package created FindEigen3.cmake
itk/5.1.0: Generator cmake_find_package created FindEXPAT.cmake
itk/5.1.0: Generator cmake_find_package created FindFFTW3.cmake
itk/5.1.0: Generator cmake_find_package created FindHDF5.cmake
itk/5.1.0: Generator cmake_find_package created FindICU.cmake
itk/5.1.0: Generator cmake_find_package created FindOpenJPEG.cmake
itk/5.1.0: Generator cmake_find_package created FindLibXml2.cmake
itk/5.1.0: Generator cmake_find_package created FindOpenSSL.cmake
itk/5.1.0: Generator cmake_find_package created FindPNG.cmake
itk/5.1.0: Generator cmake_find_package created FindTIFF.cmake
itk/5.1.0: Generator cmake_find_package created FindJPEG.cmake
itk/5.1.0: Generator cmake_find_package created FindIconv.cmake
itk/5.1.0: Generator cmake_find_package created FindZLIB.cmake
itk/5.1.0: Generator cmake_find_package created FindLibLZMA.cmake
itk/5.1.0: Generator cmake_find_package created Findjbig.cmake
itk/5.1.0: Generator cmake_find_package created Findzstd.cmake
itk/5.1.0: Generator cmake_find_package created FindWebP.cmake
itk/5.1.0: Generator cmake created conanbuildinfo.cmake
itk/5.1.0: Calling build()
itk/5.1.0:
itk/5.1.0: ERROR: Package '4f81a53d7645feec3590983d0480dd611864e48a' build failed
itk/5.1.0: WARN: Build folder .conan\b3e9e7\1
ERROR: itk/5.1.0: Error in build() method, line 217
        self._patch_sources()
while calling '_patch_sources', line 75
        tools.patch(**patch)
        FileNotFoundError: [Errno 2] No such file or directory: 'patches/0001-find-conan-packages.patch'

---
The reason why I tried this simple ITK install was that I had problems with a custom DCMTK (non-default options) and ITK, depending on DCMTK.

**Comment by jgsogo** [comment]
Hi @akalali 

Thanks a lot for pointing this issue. Indeed there was an unnoticed error in the CI related to this issue https://github.com/conan-io/conan/issues/7628 (ConanCenter will use a workaround starting this week)

Please, try again. Thanks!

**Comment by akalali** [comment]
Hi @jgsogo 

Thank you, it's working now. Could you please specify, what was missing? I got a different error than the one mentioned in the issue. Was the problem similar, but instead of the Python-recipe the patch-file was not uploaded?
