### ISSUE TITLE
[bug] Two issues with rolling back changes in remote; changes not propagating

### ISSUE THREAD

**Issue by spoofedex** [conan-io/conan#7675]
Hi all,

I have two issues with rolling back changes.

First, imagine the following scenario, when using recipe revisions in Artifactory:
- User pushes code; the CI system exports/uploads the package.
- User pushes a change to the code; the CI system exports/uploads the package.
- User rolls back the changes in the repo. Here, the CI system will trigger, but the recipe revision will be identical (by default) to the first one. Uploading the package will fail, because it already exists on the remote. So the latest version will still be the one with the incorrect changes.

Here, the remote's state does not accurately represent the latest changes.

We managed to workaround this by removing the package from the remote before uploading it; however, I don't think this is desirable. I believe this use case is common (and easily missed in testing, potentially causing significant issues!). Perhaps uploading should simply update the timestamp on the remote.

This issue is even worse when rolling back a promotion (made with "conan copy"). The use case is the same, except that the change of the package is a "conan copy" of the same package in another channel. In this case, the rollback of the change will cause the CI system to copy an older package again, and upload that to the remote (after removing the original, as workaround).

The timestamp of the resulting package is correctly updated, and it does again become the latest version. However, the conanmanifest.txt timestamp is also copied from the original. This means that, if a user has checked out the version before the rollback (which has a later timestamp), the updated version has an older timestamp, so the local cache's version will still be used. (At least, this is my interpretation of what happens. I have not done a very thorough analysis; see below for reproduction)

There does not seem to be a workaround to fix this issue. Users have to remove the package from the local cache, but this requires knowledge about what was rolled back, which is very hard in a CI system.

I believe this issue could be solved - for me - by making a copy of the conanmanifest.txt have an updated timestamp (to the current time, at the time of copying), but I don't know if this is desirable.

What are your thoughts on this? Any ideas for workaround are welcome as well!

Thanks in advance!

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: N/A
  * Conan version: 1.29.0
  * Python version: 3.7.3

### Steps to reproduce
For the first issue:
- Export/upload a package.
- Make a change.
- Export/upload the package again.
- Revert the change.
- Export/upload the package again. The package will not be uploaded, as it already exists.

For the second issue:
- System A: Have two packages in a remote, "test/0.1@test/dev#RREV-1" and "test/0.1@test/dev#RREV-2", where "RREV-1" and "RREV-2" are recipe revisions.
- System A: Remove "test" locally. Then download "test/0.1@test/dev#RREV-1", run "conan copy test/0.1@test/dev#RREV-1 test/beta", and "conan upload test/0.1@test/beta#RREV-1".
- System A: Perform the previous step again, but with "RREV-1" replaced with "RREV-2".
- System B: Run "conan install test/0.1@test/beta --update --build missing". Result: test/0.1@test/dev#RREV-2 is correctly installed.
- System A: Again remove "test" locally. Then, again, download "test/0.1@test/dev#RREV-1", run "conan copy test/0.1@test/dev#RREV-1 test/beta". Now, run "conan remove -f --remote [REMOTE] test/0.1@test/beta#RREV-1" and "conan upload test/0.1@test/beta#RREV-1".
- System B: Run "conan install test/0.1@test/beta --update --build missing --build outdated". Result: this does not rebuild anything, but instead uses the version before the rollback, i.e. "test/0.1@test/beta#RREV-2", instead of the expected "test/0.1@test/beta#RREV-1".

The logging of the last step is:
```
DEBUG :conan_api.py   [177]: INIT: Using config 'C:\Users\UserName\.conan\conan.conf' [2020-09-08 14:27:43,657]
DEBUG :tracer.py      [157]: CONAN_API: install_reference(settings=None,options=None,env=None,profile_names=None,profile_build=ProfileData(profiles=None, settings=None, options=None, env=None),remote_name=None,verify=None,manifests=None,manifests_interactive=None,build=['missing'],update=True,generators=None,install_folder=None,lockfile=None,lockfile_out=None) [2020-09-08 14:27:43,661]
DEBUG :profile_loader.py[116]: PROFILE LOAD: C:\Users\UserName\.conan\profiles\default [2020-09-08 14:27:43,667]
INFO  :settings_preprocessor.py[57]: Setting 'compiler.runtime' not declared, automatically adjusted to 'MDd' [2020-09-08 14:27:43,731]
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=14
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

DEBUG :rest_client_common.py[156]: REST: ping: http://remote-name/artifactory/api/conan/repo-name/v1/ping [2020-09-08 14:27:43,770]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions'] [2020-09-08 14:27:43,942]
DEBUG :rest_client_common.py[183]: REST: get: http://remote-name/artifactory/api/conan/repo-name/v2/conans/test/0.1/test/beta/latest [2020-09-08 14:27:43,942]
DEBUG :file_downloader.py[111]: DOWNLOAD: http://remote-name/artifactory/api/conan/repo-name/v2/conans/test/0.1/test/beta/revisions/e9909755c19f67d0e0c7a024d7ab38eb/files/conanmanifest.txt [2020-09-08 14:27:44,097]
DEBUG :graph_builder.py[415]: GRAPH: new_node: test/0.1@test/beta [2020-09-08 14:27:44,102]
DEBUG :graph_builder.py[68]: GRAPH: Time to load deps 0.36750292778015137 [2020-09-08 14:27:44,104]
DEBUG :rest_client_common.py[183]: REST: get: http://remote-name/artifactory/api/conan/repo-name/v2/conans/test/0.1/test/beta/revisions/ad250c1a32a8c228d7d21f169c3a7160/packages/c32596dcd26b8c708dc3d19cb73738d2b48f12a8/latest [2020-09-08 14:27:44,112]
DEBUG :rest_client_common.py[29]: REST ERROR: <class 'conans.errors.NotFoundException'> [2020-09-08 14:27:44,134]
test/0.1@test/beta: WARN: Can't update, no package in remote
Installing package: test/0.1@test/beta
Requirements
    test/0.1@test/beta from 'repo-name' - Newer
Packages
    test/0.1@test/beta:c32596dcd26b8c708dc3d19cb73738d2b48f12a8 - Cache

Installing (downloading, building) binaries...
test/0.1@test/beta: Already installed!
test/0.1@test/beta deploy(): Copied 1 '.exe' file: test.exe
```

Note: the URL http://remote-name/artifactory/api/conan/repo-name/v2/conans/test/0.1/test/beta/latest does show "RREV-1", but is not used.

**Comment by memsharded** [comment]
Hi @spoofedex 

Could this be a duplicate of https://github.com/conan-io/conan/issues/7331? Basically uploading a revision again should make it the latest one, isn't it?

We are currently investigating how this could be addressed, it is indeed not simple, specially as the server is involved.

> This issue is even worse when rolling back a promotion (made with "conan copy"). The use case is the same, except that the change of the package is a "conan copy" of the same package in another channel. In this case, the rollback of the change will cause the CI system to copy an older package again, and upload that to the remote (after removing the original, as workaround).

Just a suggestion: we are recently not encouraging doing promotions based on user/channel (conan copy), but using different remotes instead. It is better to have packages immutability, and user/channel promotions basically break this principle.

**Comment by spoofedex** [comment]
Hi memsharded,

Thanks for your answer!
The first issue seems to be #7331, indeed. The second issue is not, although I expect it to be resolved when implementing what you state in that issue:
> I am considering removing timestamps in manifests for Conan 2.0. Now that revisions will be the default, everything is content or hash based, and timestamps only make sense for defining the latest one. As revisions "latest" is defined by server time, the manifests timestamps will probably be useless.

Furthermore, I don't expect the same issue will occur when having promotion through remotes rather than channel.

I will close this issue as duplicate.

> Just a suggestion: we are recently not encouraging doing promotions based on user/channel (conan copy), but using different remotes instead. It is better to have packages immutability, and user/channel promotions basically break this principle.

That actually makes a lot of sense, thanks for the information!

Thanks!
