### ISSUE TITLE
[question] how to detect if build from source package?

### ISSUE THREAD

**Issue by gsemet** [conan-io/conan#7678]
Hello,

In my `set_version` function, I would like to detect if I am in a source package or in the source tree. I compute the version somehow, but I do not need to it if I already have a package (ex: when my dependency is forced compiled by `conan install --build mydependencyname`) ?

Is there an easy way to do so? My current solution is to export a file named "version.txt" and if this file exists I simply return it, but I would like something simpler. Like

```python
    def set_version(self):
       if self.version:
          # already have a version, return
          return
       return computer_version_somehow()
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
@gsemet take a look: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#develop

**Comment by gsemet** [comment]
Thanks a lot !
