### ISSUE TITLE
[question] conan config install from git using specific branch

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7679]
when i try to install conan config from a remote git repo i run
`conan config install url_to_git_repo --type=git ` but seems there is no option to specify the branch.
is there a way to  specify the branch to install the config?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @shelper 

The ``conan config install`` command admits a generic ``--args`` argument, and its value will be forwarded to git. So something like:

```bash
$ conan config install --args="-b other_branch"
```

Please try and let me know if it works. Thanks!

**Comment by shelper** [comment]
well, it seems this   --args thing does not work...
what i run is `conan config install {repo_url} -t=git -sf=conan_settings -a="-b dev"'`
and it still checks from the master....
