### ISSUE TITLE
[question] Creating conan deb package

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#7681]
Hi guys, 

I've been trying to switch my Conan install from the pip based one to the deb package. I know that is not the recommended install method but the deb package is easier to distribute as part of a SDK.
Anyways, if I install Conan using pip everything works perfectly. If I install the deb package, I get this weird error on a post_package_download() hook:

`ERROR: [HOOK - postDownload.py] post_download_package(): name 'output' is not defined`

This is on Ubuntu 18.04 by the way.

I tried running `python3 pyinstaller.py`, and that creates a package that does work for me, but it is huge (I don't remember exactly how much but over 1GB).

Are the scripts that you use to build the deb packages public? I would like to test them locally. I have zero experience creating deb packages so any help is welcome.

Thanks for the amazing work.,

Eric.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by ericriff** [comment]
Alo?

**Comment by czoido** [comment]
Hi @ericriff,
Sorry for the delay in the response.
The scripts we are using for the generation of the deb package are not public at this point. I checked to see if I could give you some hints but right now the process is a little bit coupled with other things so It was not so obvious. We are in the process of refactoring all the conan release process so when we can review the deb package generation I'll try to provide you some updated info about that.

**Comment by ericriff** [comment]
Sure, no problem!

**Comment by nolange** [comment]
@ericriff have a look at #11608

**Comment by ericriff** [comment]
I no longer need this. We ended up running our c++ builds in python virtualenvs to handle some other deps, so I moved conan there. We no longer use the deb package. I'm still interested anyways.

**Comment by memsharded** [comment]
If OP of this (@ericriff) no longer need this, I am closing this (thanks Eric for following up) and leaving https://github.com/conan-io/conan/issues/11608 for the request.
