### ISSUE TITLE
[question] settings:os_build is used for package ID generation for some packages although it is not in recipe settings attribute

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7682]
I tried two packages: gtest/1.10.0@ and zlib/1.2.11@
i cross built them for android on windows and linux
the  profile i used on both platform is almost the same except that on windows i have `settings:os_build=Windows` and on linux `settings:os_build=Linux`, then i found the package ID generated for gtest are different due to this `settings:os_build` option is different between windows and linux, but for zlib the package ID is the same between windows and linux. 

But when i change the profile on windows by setting `settings:os_build=Linux`, the gtest package ID becomes the same as on linux. so i think it means this setting does change the package ID. 

However, In both gtest and zlib recipe i have the same line for settings below which does not include os_build
`settings = "os", "arch", "compiler", "build_type"`

I don't understanding what happened here ...

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Hi @shelper !

The `os_build` and `arch_build`  have been removed from most of recipes in [Conan Center Index](https://github.com/conan-io/conan-center-index) in favor of [build context](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer).

There is an extra information in [Conan's blog](https://blog.conan.io/2020/04/06/New-conan-release-1-24.html).

Regards.

**Comment by shelper** [comment]
hi, @uilianries 
thanks for the info but i am still confused on why os_build affects the package ID of gtest when it is not in the settings attribute in recipe file 

I am using conan 1.27 which is > 1.24

**Comment by memsharded** [comment]
``os_build`` cross-build setting was deprecated in Conan 1.X in favor of the 2 profiles approach, and it has been completely removed in 2.0. Closing this ticket as outdated.
