### ISSUE TITLE
[feature] Support custom dependency information

### ISSUE THREAD

**Issue by markovandooren** [conan-io/conan#7685]
Summary
----------
1. Instead of just a deps_cpp_info it would be more flexible to have a deps_info dictionary to which objects for custom languages and tools can be added.

2. To make the dependency info available for tools that need to run after the build step, I would like the dependency information to always be created by executing the package_info() method of the recipe instead of sometimes parsing it from the buildinfo.txt file (conan build, conan package).

Use case
---------
1. I have added support for C# and C++/CLI to our Conan file that is shared via Python_requires. To do this, I add an additional cs_info attribute to the cpp_info object when executing package_info() such that the C# generator has access to that information. It works, but it depends on the internal working of Conan (the dynamic attribute dictionary).

2. For generators, the current mechanism works because when running 'conan install' and 'conan create', the Python code of the dependencies is executed such their package_info() methods can add the .cs_info attributes. For passing information for other tools, such as source indexing, that are run after building, this does not always work. For source indexing, we add a source_indexing_info attribute. It works when we run 'conan create', but when we run 'conan build' or 'conan package' then that attribute is missing because then the package_info() method of the dependencies is not executed. Instead, the buildinfo file is parsed. It is not clear to me why these individual steps use a different (and less flexible) mechanism. As a result, we can't use them for debugging packages.  
  The ability to add custom Python objects is more flexible because it allows us to define a programmatic interface between packages instead of communicating via strings and numbers. E.g I would like to call a mapping(pdbstream) method on the source_indexing_info object to get the source indexing mapping without having to know how to compute it. The sources might come from a single repository, or maybe from different repositories of different types. It could even add support for a new version control system to the PDB stream. The ability to customize Conan by overriding methods in Python is what makes Conan so great.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @markovandooren 

Thanks very much for the feedback.

> Instead of just a deps_cpp_info it would be more flexible to have a deps_info dictionary to which objects for custom languages and tools can be added.

Have you checked the ``user_info`` and ``deps_user_info`` dictionaries? They are intended for this purpose, a dictionary with values for consumers, without the need of hacking the python code.

> To make the dependency info available for tools that need to run after the build step, I would like the dependency information to always be created by executing the package_info() method of the recipe instead of sometimes parsing it from the buildinfo.txt file (conan build, conan package).

I cannot agree more. This is already planned to be fixed, the only thing is that it would be quite breaking, so it is planned for Conan 2.0

**Comment by markovandooren** [comment]
Hi @memsharded ,

Thank you very much! I had initially skipped over user_info because I somehow thought it was about the user that produces the package (the user/channel thing). I have now switched to user_info such that we don't have to worry when upgrading Conan. That solves part 1.

Part 2 will then automatically be solved in Conan 2.0. Then I can put the source indexing object in the user_info dictionary and directly call methods on it in the consuming recipe without having to know how to deserialize it.

**Comment by memsharded** [comment]
Closing this ticket as outdated, Conan 2.0 has removed ``user_info`` in favor of ``conf`` (added time ago to 1.X too). Thanks!
