### ISSUE TITLE
[bug] tools.remove_files_by_mask not available in tools

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7699]
Documentation
https://docs.conan.io/en/latest/reference/tools.html#tools-remove-files-by-mask

`tools.remove_files_by_mask` is not available in `conans.tools`

It is only available in `conans.client.tools.files`,
but that's an internal conan module and prone to  breakage.

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: gcc
  * Conan version: 1.29.0
  * Python version: 3.7.7

### Steps to reproduce (Include if Applicable)
```python
import conans.tools
conans.tools.remove_files_by_mask("*.tmp", "/tmp")
```

==>
```
AttributeError: module 'conans.tools' has no attribute 'remove_files_by_mask'
```

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/7700, will be released in 1.29.1 soon
