### ISSUE TITLE
[bug] pkg_config keeps non-existent include directories

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7701]
The `pkg_config` generator adds a `includedir` section to the generated pc files,
even when no includedirs are added.

This causes using them in CMake to fail with the following error:
```
CMake Error in CMakeLists.txt:
  Imported target "PkgConfig::LibAwesome" includes non-existent path

    "/home/maarten/.conan/data/package_no_headers/0.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "PkgConfig::LibAwesome" includes non-existent path

    "/home/maarten/.conan/data/package_no_headers/0.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

### Environment Details (include every applicable attribute)
  * Conan version: 1.29.0
  * Python version: 3.7.7

### Steps to reproduce (Include if Applicable)

The following mini recipe reproduces the error.

```sh
rm -rf conanfile.py test_package

mkdir test_package

cat >conanfile.py <<EOF
from conans import ConanFile

class C(ConanFile):
    name = "package_no_headers"
    version = "0.1"

    def package_info(self):
        self.cpp_info.names["pkg_config"] = "libawesome"
EOF

cat >test_package/conanfile.py <<EOF
from conans import ConanFile, CMake

class T(ConanFile):
    settings = "os", "arch", "compiler", "build_type"
    generators = "cmake", "pkg_config"

    def build_requirements(self):
        self.build_requires("pkgconf/1.7.3")

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
EOF

cat >test_package/test.c <<EOF
int main()
{
return 0;
}
EOF

cat >test_package/CMakeLists.txt <<EOF
cmake_minimum_required(VERSION 3.1)
project(test)

include("\${CMAKE_BINARY_DIR}/conanbuildinfo.cmake")
conan_basic_setup(TARGETS)

include(FindPkgConfig)
pkg_check_modules(LibAwesome REQUIRED IMPORTED_TARGET libawesome)

add_executable(test test.c)
target_link_libraries(test PRIVATE PkgConfig::LibAwesome)
EOF
```

The generated `.pc` file is the following:
```
prefix=/home/maarten/.conan/data/package_no_headers/0.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libawesome
Description: Conan package: libawesome
Version: 0.1
Libs: -L${libdir} -Wl,-rpath="${libdir}"
Cflags: -I${includedir}
```
Note how it contains a `includedir`, even though the package is empty:
```
tree /home/maarten/.conan/data/package_no_headers/0.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
/home/maarten/.conan/data/package_no_headers/0.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
├── conaninfo.txt
└── conanmanifest.txt

```

**Comment by memsharded** [comment]
Just checked it, it seems that it is a bug.  Sending PR https://github.com/conan-io/conan/pull/7703 to fix it. I would like to make sure that neither the ``include`` nor the ``lib`` dirs should be there in the .pc files if those folders are empty. Could you please have a look to the PR? Thanks

**Comment by madebr** [comment]
@memsharded 
The pr is indeed fixing the problem. Thanks!

My example was bad btw, because `FindPkgConfig.cmake` will only create an imported target if some of the properties is non-empty. Adding e.g. a `self.cpp_info.system_libs = ["m"]` fixed that.

**Comment by ericLemanissier** [comment]
isn't the problem here that `[self.cpp_info.includedirs` is prepopulated by conan as `['include']` `self.cpp_info.libdirs` as `['lib']`](https://docs.conan.io/en/latest/reference/conanfile/methods.html#cpp-info) ?
would the issues be fixed by doing `self.cpp_info.includedirs = []` and/or `self.cpp_info.libdirs = []` in `package_info()` ?

**Comment by memsharded** [comment]
Hi @ericLemanissier 

Yes, it is likely that in Conan 2.0 we will remove the ``filter_empy``, but this has been working in Conan 1.X and needs to keep working. All the other generators remove from their output empty folders, but the pkg_config one, which had a bug (using includedirs, the source value, instead of ``include_paths`` the absolute path values that have been filtered)

**Comment by ericLemanissier** [comment]
I was thinking of correcting the recipe's `package_info`, conan's behaviour is fine.
BTW, what is `filter_empy` ?

**Comment by memsharded** [comment]
Well, if you are checking the tests that changed, the goal of those tests is to validate the output of the pkg_config generator, for a typical package. Using empty folders in the test will test nothing.

``filter_empty`` is a ``self.cpp_info.filter_empty`` boolean flag that can be used to disable (default is ``True``), and let Conan put those folders in generated files even if they are empty. At the moment is a private, not documented flag.

**Comment by ItsBasi** [comment]
#10032 CMakeDeps seems to exhibit a similar problem.

**Comment by memsharded** [comment]
``pkg_config`` generator is being superseded by ``PkgConfigDeps``. Lets target bug reports and other issues to that generator, please, unless there are regressions we will not do changes in legacy generators. 

We'll have a look to #10032, thanks @ItsBasi
