### ISSUE TITLE
[feature] Add version of dependencies to the Make variables exported in conanbuildinfo.mak

### ISSUE THREAD

**Issue by f18m** [conan-io/conan#7705]
For my use case, but I think it could be useful to everybody, it is required to know, inside my GNU make makefiles, the exact version of each package specified inside "conanfile.txt".

In version 1.29 of Conan if I put in "conanfile.txt" the "make" generator, I obtain a  conanbuildinfo.mak containing all sort of folders (e.g. CONAN_ROOT_nameOfDependency), but no variable like "CONAN_VERSION_nameOfDependency".
That information is instead stored in the "conanbuildinfo.txt" file in a section named like "[version_nameOfDependency]".

Currently my workaround involves reading version of dependencies from conanbuildinfo.txt using "crudini" from my GNU makefiles.
I think it would be much more elegant and simple to just have them automatically exported in conanbuildinfo.mak

If you agree on this change I can have a look at Conan source code (would be my first time) and propose a PR...

**Comment by memsharded** [comment]
Hi @f18m 

In theory this effort should be done in parallel with other generators as cmake, msbuild, etc. On the other hand, some generators, like the ``cmake_find_package`` one, seems to be already using it.

So if this is a relatively urgent need for you, yes, I'd suggest to give it a try, and lets see if it can be merged without any problem. Seems modifying ``MakeGenerator`` should be enough (besides some tests, it would be necessary to add at least 1 new test. Do not hesitate to ask for help or guidance if you need it).

Thanks very much!

**Comment by memsharded** [comment]
This generator was removed in 2.0, closing this issue as outdated.
