### ISSUE TITLE
[question] How to reset --package-folder value in "conan build" to undefined?

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#7708]
I'd like to prevent `conan build` from altering installation paths, i.e. avoid conan from taking `if self._conanfile.package_folder` branch in `conans/client/build/cmake_flags.py`. However, `conan build` sets default value `{build_folder}/package` if `-pf` is not specified. Is there any way to prevent conan from messing with `CMAKE_INSTALL_` variables?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @annulen 

I am having a look at the source code, it doesn't look like possible. The ``package_folder`` is always defined, it could be the package folder in the cache, or it could be the local folder when doing the ``conan build`` flow.

What you are trying to achieve? What would be the use case?

**Comment by annulen** [comment]
I'm using `conan build` as a convenient wrapper for cmake and ninja which ensures correct environment variables on all stages. At the final step I don't want to build package but install into local system, so I'd like CMAKE_INSTALL_ * variables to be left alone in their default state. It can be done by deleteing entries from `cmake.definitions` dictionary, however I hoped there might be solution which doesn't involve hardcoded list of keys

**Comment by memsharded** [comment]
This ``--package-folder`` argument disappeared in Conan 2, closing as outdated.
