### ISSUE TITLE
[bug] gitlab integration - fail to install community package

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#7709]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04.1 LTS
  * Compiler+version: GNU Make 4.2.1
  * Conan version: 1.29.0
  * Python version: 3.7.6

conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]
conan-community: https://api.bintray.com/conan/conan-community/conan [Verify SSL: True]
artifactory: https://reactivereality.jfrog.io/artifactory/api/conan/conan [Verify SSL: True]
gitlab: https://gitlab.com/api/v4/packages/conan [Verify SSL: True]

Configuration for profile default:

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.cppstd=14
compiler.version=9
os=Linux
os_build=Linux
[options]
*:shared=False
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
1) Add gitlab private package repository (protected by a token)
2) conan install qt/5.15.1@bincrafters/stable

### Logs (Executed commands with output) (Include/Attach if Applicable)

$ conan install qt/5.15.1@bincrafters/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
*:shared=False
[build_requires]
[env]

ERROR: Permission denied for user: 'AndreiMalashkin'. [Remote: gitlab]

**PS**
conan search qt/5.15.1@bincrafters/stable -r all
returns a correct answer.

**Comment by memsharded** [comment]
Hi @AndreyMlashkin 

I am afraid that we have no control over the Gitlab integration, seems it is a server side issue, not a client one, so this issue should be probably reported in Gitlab repo instead. Have you reported this issue there?

**Comment by AndreyMlashkin** [comment]
Yes, I have also reported this bug there
https://gitlab.com/gitlab-org/gitlab/-/issues/249134

If you have any possibility to put prio or provide some information there, you are welcome

**Comment by memsharded** [comment]
Some quick hints about our remotes:

- Conan-community is no longer maintained. Almost all packages there are already included in ConanCenter, and you can find more modern versions for them without user/channel part. Almost sure you can drop this remote without any issue.
- Using the packages without user/channel is the recommended approach in ConanCenter
- Something similar happens with bincrafters, more and more packages are being added to ConanCenter (via the conan-center-index repo, which is the new way of adding packages to ConanCenter: https://github.com/conan-io/conan-center-index).

**Comment by memsharded** [comment]
What is the output of ``conan user`` command?

**Comment by AndreyMlashkin** [comment]
Current user of remote 'conan-center' set to: 'None' (anonymous)
Current user of remote 'bincrafters' set to: 'None' (anonymous)
Current user of remote 'conan-community' set to: 'None' (anonymous)
Current user of remote 'artifactory' set to: 'andrei.malashkin' [Authenticated]
Current user of remote 'gitlab' set to: 'AndreiMalashkin'

**Comment by memsharded** [comment]
Ok, thanks for the feedback. Totally seems something related to the server side, nothing to do at the moment in the client side. I am closing this one, lets follow conversation in https://gitlab.com/gitlab-org/gitlab/-/issues/249134, if necessary we can reopen.
