### ISSUE TITLE
does/should conan's bintray API have rate limits similar to those listed in bintray's documentation

### ISSUE THREAD

**Issue by steve-thousand** [conan-io/conan#7712]
I have been doing some research on conan's enforced limitations, and it seems that the conan client simply calls a bintray API that appears to be owned by conan (ie. https://conan.bintray.com/v1/conans/search?q=bzip2 to search for "bzip2"). If I go to https://bintray.com there is a link at the top to [API documentation](https://www.jfrog.com/confluence/display/BT/Bintray+REST+API) which says there should be rate limit headers, example below, which indicate how many remaining queries are allowed:
```
X-RateLimit-Limit: 1440
X-RateLimit-Remaining: 257
```
But it appears that the calls made by the conan-client don't return any rate limit headers, at least they don't if I call https://conan.bintray.com/v1/conans/search?q=bzip2 from a rest client. Does conan's bintray API have similar rate limits?

**Comment by jgsogo** [comment]
Hi, @steve-thousand 

Conan client uses the by default a remote we call ConanCenter, you can check it running this command in a fresh installation:

```
⇒  conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
```

Those packages have been created using the recipes in https://github.com/conan-io/conan-center-index and you can also use a web interface to browse them here: https://conan.io/center/

Every Conan client uses that remote by default, without authentication, so the number of calls is virtually unlimited, those calls are not identified, so they have no rate limits.

You can add other remotes, for example you can create an account in Bintray and that remote repository will have rate limits (depending on your account), you can add other remotes too if you are running some Artifactory instance locally or using a cloud version of the JFrog platform, or any other remote that supports Conan protocol.

**Comment by memsharded** [comment]
Bintray disappeared time ago, closing
