### ISSUE TITLE
[bug] Can not run poco example in Windows 10, visual studio 2017 or 2019

### ISSUE THREAD

**Issue by atomixnmc** [conan-io/conan#7714]
I Can not run poco example: 
https://docs.conan.io/en/latest/getting_started.html#an-md5-hash-calculator-using-the-poco-libraries
 in Windows 10, visual studio 2017 or 2019

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 
  * Compiler+version: Visual Studio 
  * Conan version: 1.21.0
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
- Do as poco example in:  https://docs.conan.io/en/latest/getting_started.html#an-md5-hash-calculator-using-the-poco-libraries
- git clone https://github.com/conan-io/examples.git && cd examples/libraries/poco/md5 
- $ mkdir build && cd build
- $ conan install ..
- Log shown as below

### Logs (Executed commands with output) (Include/Attach if Applicable)
$ conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: poco/1.9.4: Error in configure() method, line 111
        if self.options.get_safe("enable_data_postgresql", False):
        TypeError: get_safe() takes 2 positional arguments but 3 were given

**Comment by memsharded** [comment]
Hi @atomixnmc 

You need to upgrade to latest Conan version.
As explained in the introduction (https://docs.conan.io/en/latest/introduction.html#stable), public packages in ConanCenter requires being updated, because contributors may use features released in more modern Conan versions:

> This means that public repositories, like ConanCenter assume the use of the latest version of the Conan client, and using an older version may result in failure of packages and recipes created with a newer version of the client.

**Comment by memsharded** [comment]
Hi @atomixnmc 

Did you manage to make it work by updating to latest Conan?

**Comment by shizhaojingszj** [comment]
I came across this issue today for first-time usage of conan.

Conan version 1.21.0

then ----->

Conan version 1.37.0-dev

then ----> It worked!

**Comment by memsharded** [comment]
Hi @shizhaojingszj 

Yes, as explained above in https://github.com/conan-io/conan/issues/7714#issuecomment-694058752, and in the docs, it is necessary to use the latest Conan to consume the public packages in ConanCenter, as the community that contribute them keeps upgrading.

I think this question is addressed, and can be closed, thanks!
