### ISSUE TITLE
[bug] self.copy(symlinks=True) has no effect

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#7723]
### Environment Details (include every applicable attribute)
  * Operating System+version: Macos  (Linux is affected as well)
  * Compiler+version:
  * Conan version: 1.23.0
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
Use symlinks=True during package stage

For example:
        self.copy("libglib*", dst="glib-2.0/lib", src=self.kWorkfolder+"/lib/aarch64-linux-gnu", symlinks=True)
Contents of the source folder:
$ ls -la /Volumes/nvidia/usr/lib/aarch64-linux-gnu/libglib*
-r--r--r--  1 root  wheel  1986314 Jul  3  2019 /Volumes/nvidia/usr/lib/aarch64-linux-gnu/libglib-2.0.a
lr-xr-xr-x  1 root  wheel       23 Jul  3  2019 /Volumes/nvidia/usr/lib/aarch64-linux-gnu/libglib-2.0.so -> libglib-2.0.so.0.5600.4
lr-xr-xr-x  1 root  wheel       23 Jul  3  2019 /Volumes/nvidia/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0 -> libglib-2.0.so.0.5600.4
-r--r--r--  1 root  wheel  1035584 Jul  3  2019 /Volumes/nvidia/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0.5600.4
lr-xr-xr-x  1 root  wheel       22 Apr  1  2018 /Volumes/nvidia/usr/lib/aarch64-linux-gnu/libglibmm-2.4.so.1 -> libglibmm-2.4.so.1.3.0
-r--r--r--  1 root  wheel   542696 Apr  1  2018 /Volumes/nvidia/usr/lib/aarch64-linux-gnu/libglibmm-2.4.so.1.3.0
lr-xr-xr-x  1 root  wheel       42 Apr  1  2018 /Volumes/nvidia/usr/lib/aarch64-linux-gnu/libglibmm_generate_extra_defs-2.4.so.1 -> libglibmm_generate_extra_defs-2.4.so.1.3.0
-r--r--r--  1 root  wheel   162752 Apr  1  2018 /Volumes/nvidia/usr/lib/aarch64-linux-gnu/libglibmm_generate_extra_defs-2.4.so.1.3.0

Contents of package/glib-2.0/lib after executing the package step:
$ ls -la package/glib-2.0/lib/
total 7320
drwxr-xr-x  10 alex  staff      320 Sep 18 10:09 .
drwxr-xr-x   6 alex  staff      192 Sep 18 10:09 ..
-rw-r--r--   1 alex  staff  1986314 Sep 17 21:52 libglib-2.0.a
-rw-r--r--   1 alex  staff       23 Sep 17 21:52 libglib-2.0.so
-rw-r--r--   1 alex  staff       23 Sep 17 21:52 libglib-2.0.so.0
-rw-r--r--   1 alex  staff  1035584 Sep 17 21:52 libglib-2.0.so.0.5600.4
-rw-r--r--   1 alex  staff       22 Sep 17 21:52 libglibmm-2.4.so.1
-rw-r--r--   1 alex  staff   542696 Sep 17 21:52 libglibmm-2.4.so.1.3.0
-rw-r--r--   1 alex  staff       42 Sep 17 21:52 libglibmm_generate_extra_defs-2.4.so.1
-rw-r--r--   1 alex  staff   162752 Sep 17 21:52 libglibmm_generate_extra_defs-2.4.so.1.3.0

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

``self.copy()`` was removed in Conan 2.0, closing this ticket as outdated. 
Please create new tickets against Conan 2.X as necessary, thanks!
