### ISSUE TITLE
[question] Installing directories and files to GNUInstallDirs SYSCONFDIR

### ISSUE THREAD

**Issue by colin-pm** [conan-io/conan#7724]
I am trying to use CMake's install(...) command with CMAKE_INSTALL_SYSCONFDIR to install a necessary directory and system configuration files to /etc. CMAKE_INSTALL_SYSCONFDIR does not have a default value.  Reading #3594 it seems like there is some support for GNU standard installation directories.  However,  CMAKE_INSTALL_SYSCONFDIR and some of the other values are not defined with default values.

I tried just specifying the path without using CMAKE_INSTALL_SYSCONFDIR, which is gross, but I wanted to see if it worked. When I run conan create it tries to install the directory on my host system and fails because I don't have permission to create a directory in /etc.  This could probably be fixed by running conan create as root, but I really only want the directory to be installed by a consumer and not a creator.

I'm curious what is the best practice to install configuration files on a target machine with Conan and CMake?

- [Y] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by intelligide** [comment]
I strongly advise against installing files outside the package folder `self.package_folder`. 
- This can damage system files without rollback.
- Files outside the package folder are not packaged and not distributed.

It is however possible to define environment variables to define configuration file paths.

**Comment by colin-pm** [comment]
I think I have a solution working to address this issue.  I have found that conan and CMake seem to work fine with installing a configuration file with the path specified without the leading slash.

For example let's say I have my_application and need to install /etc/my_application.conf.  To do this with conan and CMake, I would add the following line in my root CMakeLists.txt...

`install(FILES ${CMAKE_CURRENT_BINARY_DIR}/conf/my_application.conf
        DESTINATION etc)`

Then ensuring I have package defined as such below in my conanfile.py, the configuration will be properly installed on my target system.

```
def package(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.install()
```

The issue I mentioned above is if I specify the DESTINATION as /etc, it'll try to install the configuration file to my host machine when running conan create.

I think this current solution is good enough for me so I am comfortable closing this issue.
