### ISSUE TITLE
[question] How to add sbin directory to virtualrunenv's PATH?

### ISSUE THREAD

**Issue by 0x4d0x4b** [conan-io/conan#7725]
Hi,

I have got a `conanfile.py` recipe that builds C source code from a tarball into executable using autotools. The final executable is located in package's `sbin` directory.
I have defined following `package_info` in the recipe
```
    def package_info(self):
        self.env_info.path.append(os.path.join(self.package_folder, "sbin"))
```
When I set `virtualrunenv` up for my consuming package, it is not able to see required executable because dependency's `sbin` directory is not added to the `PATH`.
Thanks to `package_info` definition it works for `virtualenv` generator, but not for `virtualrunenv`.

Is this behavior intended?
Is it possible to add `sbin` dirs of dependencies to the PATH of `virtualrunenv` in a similar way as it is done automaticaly for `bin` dirs?

Thanks

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @kajdam 

The ``virtualrunenv`` should work for every binary directory declared in the package_info(), so something like:

```python
def package_info(self):
    self.cpp_info.bindirs = ["bin", "sbin"]
    # same as this because the default is already ["bin"]
    self.cpp_info.bindirs.append("sbin")  
```
Do you have that declared in your recipe?

**Comment by 0x4d0x4b** [comment]
Thanks @memsharded 
I had not added `self.cpp_info.bindirs.append("sbin")` as I thought that `self.env_info.path.append(os.path.join(self.package_folder, "sbin"))` would take precedence and set the `PATH` for both `virtualenv` and `virtualrunenv` (as well as including it in bindirs for other generators).
I have modified my `conanfile.py` as advised and it is working as expected.
Thanks again.

**Comment by memsharded** [comment]
Hi @kajdam 

Those are different mechanisms, the ``env_info.path`` manage env-vars and define a virtualenv of env-vars. But the ``virtualrunenv`` is defined for those packages that do not define env-vars, but you still want to get the PATH or LD_LIBRARY_PATH to those packages easily, from the definition of the package itself (``bindirs``).

Thanks for following up, reporting and closing!
