### ISSUE TITLE
[feature] apple_clang: 12.0 (XCode 12) in default settings

### ISSUE THREAD

**Issue by dBagrat** [conan-io/conan#7726]
Would be nice to have apple_clang: version: "12.0" in default settings
//recently released XCode 12
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @dBagrat 

Yes, this was merged yesterday in https://github.com/conan-io/conan/pull/7722
Will be released in Conan 1.29.2 as soon as possible (likely this monday).

Thanks for reporting!
