### ISSUE TITLE
Use deps_user_info in requirements or build_requirements method

### ISSUE THREAD

**Issue by mhanitaw** [conan-io/conan#7731]
I need to use deps_user_info in build_requirements or in requirements method.
The use case is the following:
I need to pass the versions of some tools in the uploader package in user_info. In the consumer package, I want to require these tools with the versions filled in deps_user_info.

Any suggestions about how to do this will be very much appreciated. Thanks in advance

**Comment by memsharded** [comment]
Hi @mhanitaw 

I am afraid it is not possible to access that information:

- ``requirements()`` and ``build_requirements()`` methods are evaluated when the graph is being expanded (upstream). When these methods are being processed, the dependencies are not there, maybe not even in the cache, but in the server. 
- the ``self.deps_cpp_info``, ``self.deps_user_info`` are information from the dependencies, defined in their ``package_info()`` method. This information is only available when the graph has been fully resolved and evaluated.

It seems you are trying to resolve a chicken-and-egg problem, and use some data that lives in the dependency to define which dependency to use, and this is not possible. You probably want to use configuration like ``settings``, ``options`` or environment variables to define what you want, and that can be defined and reuse robustly in ``profile`` files, which can also be shared with the team and CI servers with ``conan config install`` command.
