### ISSUE TITLE
[question] applying a patch to a package from conan-central

### ISSUE THREAD

**Issue by pcapdump** [conan-io/conan#7732]
We use several 3rd party binary packages from conan-central in our project through the CMake wrapper (https://github.com/conan-io/cmake-conan).
We found out that one package contains a bug.
We need a quick solution, thus we want to tell conan we want the buggy package source to be fetched, our patch to be applied and then the package to be built and used.
Other 3rd party packages should be continued to be used regularly as binary.

Similar process exists at FreeBSD ports or Gentoo portage.

I wasn't able to google out the feature of Conan.
Is it possible at all with Conan?

Thanks in advance.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @pcapdump 

If you want to change what a recipe does, in this case, to apply some patches, you need to fork that recipe, do the changes, and ``conan create`` it locally. There is no standard way to inject any arbitrary patch into any arbitrary package.

What ConanCenter recipes have now, is an "external", ``conandata.yml`` file besides the recipe, that defines sources and possible patches. For a recipe that already have patches in the ``conandata.yml``, it might be possible to simple add what you want in the ``conandata.yml``.

I would strongly recommend submitting a patch to https://github.com/conan-io/conan-center-index, we are streamlining the process there, adding reviewers from the community so pull requests will get automatically merged faster than before (which was working quite fast already, much faster than the old inclusion process). At least reporting which is the affected package and with which bug would be very helpful.

**Comment by memsharded** [comment]
This response seems correct and still holds, so I think this question can be closed as responded. Thanks!

**Comment by rurban** [comment]
So you insist on using the very same version number for locally patched remotes?
ERROR: Package recipe with version 3.0.0!=3.0.0.1

E.g. I'm using my-remote pkg 3.0.0 and need to patch it to 3.0.0.1, because remote needs a month to bump it.
In your scheme I either have use 3.0.0 even with my local patches, or wait for the remote to patch it.

client/loader.py:139

**Comment by memsharded** [comment]
Hi @rurban 

It is not very clear what your question or issue is. If you could provide more details, that would be useful. If you bump the version, aren't you bumping the ``version = xxx`` field and the ``conandata.yml`` data?
