### ISSUE TITLE
[bug] Artifactory returns 200 when user without permissions removes packages

### ISSUE THREAD

**Issue by czoido** [conan-io/conan#7733]
The issue happens when using Artifactory API v1 (revisions disabled). Some user without DELETE permissions in an Artifactory repo tries to remove packages, no error message is thrown and a 200 response code is returned by Artifactory.

 * Conan version: 1.29.2
 * Artifactory version: 7.7.3 pro

### Steps to reproduce (Include if Applicable)

Create an user in Artifactory without DELETE permissions on a repo. Configure that repo in Conan.

```
$ conan new pkg/1.0 && conan create .
$ conan upload pkg/1.0 -r artifactory -c --all
$ conan config set general.revisions_enabled=0
$ conan remove "pkg/1.0" -r artifactory -f
Nothing happens
$ conan config set general.revisions_enabled=1
$ conan remove "pkg/1.0" -r artifactory -f
ERROR: Permission denied for user: 'carlos'. [Remote: artifactory]
```

**Comment by czoido** [comment]
Opened a JIRA for this issue on Artifactory side: https://www.jfrog.com/jira/browse/RTFACT-23390

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2:
```
$ conan remove "zlib/*" -c -r=test
Found 2 pkg/version recipes matching zlib/* in test
ERROR: Permission denied for user: 'user-with-no-delete-creds': {
  "errors" : [ {
    "status" : 403,
    "message" : "Forbidden"
  } ]
}. [Remote: test]
```
