### ISSUE TITLE
Different conan packages based on different CMake toolchain files

### ISSUE THREAD

**Issue by danielhalati** [conan-io/conan#7743]
Hello. I have the following scenario: there is a need at the development level that the same library is compiled with different compiler flags (different CMake toolchain file). We just pack existing binaries (conan is not used to build). At this point, there's just one conan recipe file as template which is filled every time a package has to be created (name, version, settings).

![image](https://user-images.githubusercontent.com/16553732/93978882-4d71c200-fd85-11ea-827f-d4a5af3c0525.png)
 
These are the settings and options used at the moment. Is there a possibility by introducing a new option/setting to make a difference based on the toolchain file that was used to compile? And how does this affect conanfile.txt file?

**Comment by memsharded** [comment]
Hi @danielhalati 

Yes, the binary model can be extended either with settings and/or options:

- Use options, if the toolchain only affects one specific package, and if different packages could have different values
- Use settings if the toolchain applies to all, or many packages, and will use the same value for all of them

I would say that in your case, you want to do the second one. Have a look to: https://docs.conan.io/en/latest/extending/custom_settings.html. Basically:

- Edit the ``settings.yml`` to add your custom configuration.
- I would considering adding the ``toolchain`` at the first level, or as a subsetting of the ``compiler``:
```
compiler:
        toolchain: [toolchain1, toolchain2....]
```
- Pass the toolchain as command line argument ``-s compiler.toolchain=toolchain1``, or put it in the profiles (using profiles is recommended)
- Use the value in the recipe if you need (it doesn't seem the case, if you are building outside of Conan and only packaging with Conan)
- You can use ``conan config install`` feature to share your configuration, both ``settings.yml``, profiles, etc

Please let me know if this help, or you have any further question.

**Comment by danielhalati** [comment]
Actually, I think this is what  need: https://docs.conan.io/en/latest/versioning/revisions.html

The toolchain files are kept inside a GIT repository. Whenever some toolchain file changes it means we have a new package. Am I Right?

**Comment by memsharded** [comment]
@danielhalati revisions is an internal, automatic versioning. As such it is not valid at all for managing variability of different configurations of the toolchain, only to track the historic evolution of 1 given configuration. And that you should put the toolchain itself inside a Conan package, and make your packages depend on it. If this is what you want, to produce different packages in the consumers when you change the source of the toolchain, then you should:

- Enable revisions (they are disabled by default, though this will change in Conan 2.0, that will always use revisions)
- Configure a package_id_mode to ``recipe_revision_mode``, that means that when a dependency change its revision, it will force a new package_id and then a different binary, that needs to be built.
- Although "build_requires" seems to fit well the use of a toolchain package, at the moment ``build_requires`` do not affect the package_id, so it is necessary to use regular ``requires``

Though I am not sure if this is what you want, from the above comments, it looked like you already manage the toolchain in your system (not with Conan), and it was more a modeling issue (adding settings or options), than a packaging issue for the toolchain.

**Comment by danielhalati** [comment]
In my approach, I use Conan to create packages from preexisting compiled binaries by using this: 

`conan export-pkg _Sandbox_BUILD genicam/3.1.0@channel/stable -s os=Linux -s arch=x86_64 -s build_type=Release -o shared=True -pf /home/user/workspace/_Sandbox_BUILD/genicam/stage --force --profile /home/user/workspace/toolchain/scripts/../conan/profiles/x86_64-Linux`

Introducing a new setting sounded interesting at first, but it's not enough that I store the toolchain name as setting since the content of the file can change over time (compiler, compiler flags, etc.).

@memsharded can you have a look?

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

Conan 2.0 has added some extra capabilities to customize the ``package_id``:

- The ``conf`` allows to inject things to recipes, like a toolchain file with ``-c tools.cmake.cmaketoolchain:user_toolchain=...`
- The ``conf`` can be automatically made part of the ``package_id`` if we want to with another ``conf``
- It is possible to put the toolchain in a Conan package, and use it as ``tool_requires``
- Make the package to automatically affect the ``package_id`` of the consumers by defining an attribute in the recipe like ``build_mode = "minor_mode"``, so you can perfectly control when do you want your changes to the toolchain file to affect the consumers, for example if you are only adding some comments/docstring, you can avoid bumping the version, and consumers will not need to re-build

Still, it might be recommended in many cases to define a custom, abstract and high level model of binaries via custom settings and options. 

I am closing this ticket as inactive, it would be great to open a new ticket, updated for Conan 2.0, if necessary if you have any further question about the above.
