### ISSUE TITLE
Pre Recipe Check Hook

### ISSUE THREAD

**Issue by markovandooren** [conan-io/conan#7748]
Summary
======
I would be helpful if there was a hook that was called before Conan checks if it can find the recipes. Editable mode make it easy to work with multiple package without a constant commit-push-build-download cycle, but if you then push all of your packages to their repositories, a build server may try to use a recipe that was not yet uploaded to the Conan repository.

Use Case
======
In the set_version() method, we automatically insert the revision into the Conan package version such that we have repeatable builds and can always see from which revision a package was made.

I have a number of packages in editable mode (which is a fantastic feature) and when I am done I commit everything, update the requirements and push the packages to their git repositories. Each package has its own git repository.

Recipes are uploaded only to the Conan repository after a successful build on the build server. We do not want recipes in the repository of which it is known that they do not build anyway. That would make it cumbersome for a developer who needs to use a package.

Problem
======
The build servers watch the git repositories and trigger a build when a new commit is made. Suppose that we have the following situation. Package A/1.0.0.revision1 depends on package B/1.0.0.revision1. I have edited and push both of them, so now package A/1.0.0.revision2 depends on package B/1.0.0.revision2. 

If a build server first builds package B/1.0.0.revision2, then everything works fine. If it is successful it uploads the recipe and the package. If the build fails, then the build of A/1.0.0.revision2 will also fail, as it should.

However, if a build server first checks the repository of package A, and wants to build A/1.0.0.revision2, then it will look for the recipe of B/1.0.0.revision2. That recipe was not built yet, and it therefore not in the package repository or the local cache. The build fails. 

Even if we would duplicate the Conan dependencies in the build server configuration (which would be a nightmare) it still wouldn't know which revisions of A depends on which revision of B. Only Conan knows that.

Workaround
========
Currently I abuse the set_version() method to work around this. This method was chosen because

1. It is called before conan checks the recipes.
2. It has access to the recipe_folder. Not the most important reason, but very handy.

In set_version() I go over the requirements and check if Conan can find them. If not, then I download the recipe from the git server based on the name (which must match the repository name) and the revision. I demand that conanfile.py is in the root of the repository. I create a directory named self.recipe_folder + "ensure_that_recipes_are_in_local_cache" and put the script there. Then I 'conan export' that script to the local cache. This recursively triggers the mechanism and if there are indirect recipes that have not yet been built, they will be exported too. Afterwards, I delete self.recipe_folder + "ensure_that_recipes_are_in_local_cache". Having access to self.recipe_folder make this recursion trivial since I do not have to worry about conflicting directory names. Because the downloaded recipe is inside the "ensure_that_recipes_are_in_local_cache" subdirectory, it will download any missing recipes one level deeper and so on. 

Having a hook that is called before Conan checks the recipes would avoid the need for hacking into the set_version() method. In this case access to self.recipe_folder is handy, but if I use an environment variable then I could use that instead to create recursively nested directories. I don't really like environment variables, but it still seems cleaner than expanding the scope of recipe_folder.

In general, I think more users that want to avoid uploading bad recipes will run into this problem. Editable mode makes it convenient to short-circuit the commit-push-build-download cycle, but if there is no upload step before build, it creates problems. Given that many people will have a different setup, dedicated feature does not seem feasible, but an additional hook seems like a good solution.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this was not responded back then @markovandooren 
Sometimes it happens, and some tickets fall through the cracks.

It has been a long time, now there are different recommendations for the above described issues:

- It would be better to use ``lockfiles`` rather than explicit revisions in recipes. Lockfiles allow full reproducibility in build servers
- There are new learnings about how to do CI with packages, see https://docs.conan.io/2/ci_tutorial/tutorial.html
- A way to manage and automate editables, in a more powerful way, would be the new Conan 2.X "incubating feature" workspaces: https://docs.conan.io/2/incubating.html

I am closing this ticket as outdated, but please create new tickets as necessary for any further question or issue. Thanks for the feedback.
