### ISSUE TITLE
Private server, publicly accessible, with authentication

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#775]
I'm interested in creating a private conan.io server. The docs talk about doing so behind a firewall, but I would like to be able to access the server outside the private network without using VPN. Is there a way to authenticate using Apache (or alternative mechanism) similar to what you would do with subversion? If not, is this something that might be possible in the (hopefully near) future?

**Comment by memsharded** [comment]
Hi @rconde01 !

Thanks for your question. Running a ``conan_server``, of course the best is to run it behind the firewall, to ensure that everything is safe, but there is nothing in ``conan_server`` to do that. If you run it under a public IP, you will get a public server. The authentication against external services is not built in conan_server, maybe you can put it behind some Nginx (recommended for serious production), and do authentication with Nginx, routing requests to the conan_server, which users could have no password.

Probably you might be interested in checking also Artifactory, please read if you haven't do so: http://blog.conan.io/2016/11/17/conan-leaps-forward-and-joins-JFrog.html, and https://www.jfrog.com/blog/conan-joins-jfrog/

**Comment by rconde01** [comment]
Interesting...wouldn't conan still need an enhancement to grab the creds from the command line and/or a cache to send to the conan server?

**Comment by yinonavraham** [comment]
Hi @rconde01 ,

If I understand your need correctly, I think you already have everything you need in Artifactory (starting version 4.15.0) and the conan CLI.
Artifactory provides several options to manage users, groups & permissions (see links below).
In conan you can use the `conan user` command to authenticate in a remote (which is the local repository in Artifactory).

For more details, please take a look in the following JFrog Artifactory User Guide pages:
[Conan Repositories](https://www.jfrog.com/confluence/display/RTF/Conan+Repositories)
[Configuring Security](https://www.jfrog.com/confluence/display/RTF/Configuring+Security)
[Managing Users](https://www.jfrog.com/confluence/display/RTF/Managing+Users)
[Managing Permissions](https://www.jfrog.com/confluence/display/RTF/Managing+Permissions)

HTH,
Yinon

**Comment by rconde01** [comment]
Hi @yinonavraham 

I guess I'm a bit confused at the use case of Artifactory vs Bintray. I thought maybe all I needed to do something like my use case was Bintray. Looking at Artifactory it seems a bit overkill for us as we just need authentication on top of conan. Our team is not relatively big.

**Comment by yinonavraham** [comment]
Hi @rconde01 ,

You are correct, even though Bintray might have been more suitable for your needs (but I'm not fully aware of your use case), it does not yet support Conan repositories.
You can also consider [Artifactory Cloud](https://www.jfrog.com/artifactory/versions/#Cloud) (the SaaS solution) if you don't like to manage the Artifactory server on your own.

In short about Bintray and Artifactory - 
First, they both are universal binary repository managers. The main difference lies in their goal.
[Artifactory](https://www.jfrog.com/artifactory/) is a universal binary repository manager, capable of managing a vast collection of package types, and its goal is to be a major part of the build process, managing your software's lifecycle. It has great integration with many CI servers, enables managing builds and modules, dependencies, and much more.
[Bintray](https://bintray.com) is a DaaS (Distribution as a Service) solution, as such it has features relevant for distribution to end-users/bots, such as CDN, EULAs, managing packages, versions, products, business units, organizations, and much more.

HTH,
Yinon

**Comment by db4** [comment]
Hi @yinonavraham,

Do you know if Artifactory OSS supports Conan repositories or it's Pro-only feature? I cannot find a clear answer in their docs.

**Comment by memsharded** [comment]
Hi!

There have been some improvements since latest reports:
- Bintray support conan repos, and you can create your free, public repos in bintray for conan.
- Conan-server got some improved auth methods and a plugin mechanism to provide your own.
- The documentation has improved to clarify about remote servers.

So I'd say this issue can be closed. But please re-open or comment if necessary. Thanks!
