### ISSUE TITLE
[feature] make `source_folder` available to set_name() and set_version()

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7751]
I want to set the version using the value extracted from a file within my repository.

While this is possible using the 'package development flow' commands using `self.recipe_folder`, since the source can be located relative to the recipe, this is not true when building in the cache.  I'd need the `source_folder` to be able to locate my version files, but this is currently not available from the `set_version()` method:

```
AttributeError: 'ConanRecipe' object has no attribute 'source_folder'
```

**Comment by DukeOfKirkcaldy** [comment]
Sorry I found elsewhere in the documentation that this method is run only when the recipe is in a user folder.

**Comment by memsharded** [comment]
Yes, note the difference from the ``self.source_folder`` which is where the source lives, and could be different to the current one, the one containing the recipe, for example if the recipe contains a ``source()`` method that downloads source code from the internet. The ``set_name()`` and ``set_version()`` works at "export" time, where the "source" folder doesn't exist yet.
