### ISSUE TITLE
[question] Windows and CMake, Ninja not picked by conan?

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#7752]
- Conan 1.29
- Windows MSVC2019
- CMake 3.17.1
- Ninja 1.10.0

The main projects CMakeLists.txt uses conan_cmake_run() to build the dependencies needed by the project.

> cmake -GNinja -DCMAKE_BUILD_TYPE=Release ......
> cmake --buiild .

The Ninja is picked correctly on Mac and Linux to build the dependency (conan_cmake_run()) but on Windows is has no effect?
On Windows it seems to always reference 'vcxproj'?

// no effect
> $ conan config set general.cmake_generator=Ninja

// no effect
> set CONAN_CMAKE_GENERATOR=Ninja

Then I found this: https://github.com/conan-io/conan/issues/5312

But as suggested the vcvars.bat had no effect.

I had to edit the recipe of the module (built by the conan_cmake_run()) as follows:

    def build(self):
        args = [cmake_tool, "-GNinja", "-DCMAKE_INSTALL_PREFIX=" + install_dir, os.getcwd()]
        self.run(" ".join(args))

With this change I was able to get it working on Windows, but I would not like to hard code the Ninja usage in the recipe.

How to make it pick the Ninja correctly on Windows?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by intelligide** [comment]
`CONAN_CMAKE_GENERATOR` and `general.cmake_generator` are used by cmake build helper(https://docs.conan.io/en/latest/reference/build_helpers/cmake.html) and cmake toolchain (https://docs.conan.io/en/latest/creating_packages/toolchains/cmake.html). Conan can't set the generator if you use manually cmake with `self.run`.

**Comment by huweiATgithub** [comment]
Maybe you can try the new conan cmake tool: https://github.com/conan-io/conan/issues/10404

**Comment by memsharded** [comment]
Closing this ticket as outdated, as it refers to legacy integrations and legacy way of configuration (instead of new ``conf`` system). Please open new tickets if necessary, thanks!
