### ISSUE TITLE
[question] Creating a "test_package" that will work cross platform with multiple compilers/configurations

### ISSUE THREAD

**Issue by tjwrona** [conan-io/conan#7759]
I'm working on packaging and testing a library that I wrote and everything seems to work fine but when I wrote the `test_package` for the library I followed the example in the documentation and it was failing because the binary file was not being placed in a `bin` folder, but instead MSVC decided to put it in a `Release` folder.

Here is my working `conanfile.py` for the `test_package` of my library.

```python
import os

from conans import ConanFile, CMake, tools

class TestPackage(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake_paths"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def test(self):
        if not tools.cross_building(self):

            # MSVC doesn't put the output in "bin", it is putting it in "Release" instead
            #os.chdir("bin")
            os.chdir("Release")

            self.run(".%test_package_exe" % os.sep)
```

The issue is that this is a multi-configuration project and I also want it to be cross platform compatible. If I try to create a package from a debug build the executable would be in a `Debug` folder instead and the test package would fail. Also if I tried to use gcc instead of 
MSVC the executable would be in the `bin` folder like the example in the documentation.

What is the proper way to make the test package work in all cases without having to modify the conanfile every time I change configurations or compilers?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by intelligide** [comment]
In the `package` method, you can move your executable/library from `Release` (or `Debug`, check the value of `self.settings.build_type`) to `bin` ;)

Do you use CMake or another build system ?

**Comment by tjwrona** [comment]
Yes I use CMake, but wouldn't that approach still require knowing what folders the specific compiler uses for release and debug builds? Depending on the compiler the folders it puts things in may not always be `Release` or `Debug` so it may not work in all cases.

**Comment by intelligide** [comment]
You can use the cmake helper (https://docs.conan.io/en/latest/reference/build_helpers/cmake.html). It sets cmake install variables (`CMAKE_INSTALL_BINDIR`, `CMAKE_INSTALL_INCLUDEDIR`, `CMAKE_INSTALL_LIBDIR`, etc...) to the package folder. 

If you use cmake install command like this:
```cmake
install(TARGETS mylib RUNTIME LIBRARY RUNTIME)
```
The output files are redirected to the package folder.

**Comment by tjwrona** [comment]
The `test_package` executable never gets "installed" though. It just builds locally and then runs it straight out of where it gets built to verify the test.

There is no "packaging" or "installing" in the `test_package` examples in the documentation.

**Comment by intelligide** [comment]
`test_package` isn't a package. It's a conanfile for simulating consumer environment. Look at some [CCI recipes](https://github.com/conan-io/conan-center-index). They are often identical and generic.

The package must provide all the information about its structure needed by consumers. The consumer (or `test_package`) isn't responsible to deduce the information. 

If your project provides librairies or executables in a non-standard folder (like `Release`), the conanfile of your package (not the `test_folder` one) must define paths during [`package_info`](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-info) inside [`self.cpp_info`](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info-attributes-reference) attribute.

**Comment by tjwrona** [comment]
Ohh I think there may be a slight misunderstanding here. The library that I am testing is built and installed properly and has no issue with the `Release` or `Debug` folder because it just goes to the standard install location. The issue is not with finding my library, it is with finding the `test_package_exe` executable itself.

The `test_package` has its own CMake file that consumes my library and builds `test_package_exe`. Then it runs this executable locally without installing it just to verify that it works. Since this executable does not get installed (and probably should not get installed) it just ends up in the default output location for whatever compiler is used. This happens to be in a `Release` folder when building with MSVC.

Since `test_package_exe` ends up in a `Release` folder I need to hardcode the path in the `test` method to reference the `Release` folder so it finds the executable, but if I switch compilers that means the `test` method will break since a different compiler won't put `test_package_exe` in the same location.

**Comment by intelligide** [comment]
Try using this conanfile for `test_package`:
```python
from conans import ConanFile, CMake, tools
import os


class TestPackageConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def test(self):
        if not tools.cross_building(self.settings):
            bin_path = os.path.join("bin", "test_package")
            self.run(bin_path, run_environment=True)
```

and this CMakeLists.txt for `test_package` (replace `test_package.cpp` or rename your source file):
```cmake
cmake_minimum_required(VERSION 3.1)
project(test_package)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(${PROJECT_NAME} test_package.cpp)
target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```
Tip: Keep it simple. test_package should only test if your package correctly link to a consumer artifact, not if it works as expected (this is the unit test job).

It should work properly. (It works for [bullet3 from CCI](https://github.com/conan-io/conan-center-index/tree/master/recipes/bullet3/all/test_package)).

**Comment by tjwrona** [comment]
I tried using that exact conanfile with only one slight difference (the difference should have no impact on this issue though):

```python
from conans import ConanFile, CMake, tools
import os

class TestPackageConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"

    # One slight difference
    generators = "cmake_paths"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def test(self):
        if not tools.cross_building(self.settings):
            bin_path = os.path.join("bin", "test_package")
            self.run(bin_path, run_environment=True)
```

The only difference is using the "cmake_paths" generator when consuming my library because my library requires some specific compiler flags and using "cmake_paths" allows me to use the actual "CMake" target for my library and pull in the right compiler flags automatically.

The `CMakeLists.txt` file for the `test_package` looks like this:

```cmake
cmake_minimum_required(VERSION 3.11.4)
project(test_package LANGUAGES CXX)

include(${CMAKE_BINARY_DIR}/conan_paths.cmake)
find_package(cpp-dsp REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} tnt::dsp)
```

It finds my library fine and compiles the `test_package` executable fine, but when it tries to run the `test_package` executable I get the error:

```
cpp-dsp/0.0.0 (test package): Running test()
The system cannot find the path specified.
ERROR: cpp-dsp/0.0.0 (test package): Error in test() method, line 17
        self.run(bin_path, run_environment=True)
        ConanException: Error 1 while executing bin\test_package
```

Looking at the output as it compiles it I can see that it is throwing the `test_package` executable in a `Release` folder instead of a `bin` folder:

`test_package.vcxproj -> C:\Users\tjwro\Documents\GitHub\cpp-dsp\test_package\build\ecbfb49a4e2ea8618319be5f9e02c8e0621391fb\Release\test_package.exe`

**Comment by intelligide** [comment]
Your problem come from `conan_paths` generator. This generator doesn't define `CMAKE_RUNTIME_OUTPUT_DIRECTORY`, unlike the `cmake` generator ([See here](https://github.com/conan-io/conan/blob/bd0da4de60b892eb1ea46a0809216a41db085c97/conans/client/generators/cmake_common.py#L390)). 

There 2 solutions:
- Define these yourself paths in the `test_package/CMakeLists.txt`:
```cmake
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
```
- or use both `cmake` and `cmake_paths`:
```python
from conans import ConanFile, CMake, tools
import os


class TestPackageConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake", "cmake_paths"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def test(self):
        if not tools.cross_building(self.settings):
            bin_path = os.path.join("bin", "test_package")
            self.run(bin_path, run_environment=True)
```
and
```cmake
cmake_minimum_required(VERSION 3.11.4)
project(test_package LANGUAGES CXX)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

include(${CMAKE_BINARY_DIR}/conan_paths.cmake)
find_package(cpp-dsp REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} tnt::dsp)
```
It would seem that `conan` generator already defined the paths of `conan_paths`.


Tip: you can also use components to make your package compatible with `cmake_find_package` generator.
```python
self.cpp_info.filenames["cmake_find_package"] = "cpp-dsp"
self.cpp_info.filenames["cmake_find_package_multi"] = "cpp-dsp"
self.cpp_info.names["cmake_find_package"] = "tnt"
self.cpp_info.names["cmake_find_package_multi"] = "tnt"
self.cpp_info.components["dsp"].names["cmake_find_package"] = "dsp"
self.cpp_info.components["dsp"].names["cmake_find_package_multi"] = "dsp"
self.cpp_info.components["dsp"].libs = tools.collect_libs(self)
```
If you defines these variables, conan (with the `cmake_find_package`) generates a file `cpp-dspConfig.cmake` and a target `tnt::dsp`. So it should work without `cmake_paths`. [Example with Sqlite3](https://github.com/conan-io/conan-center-index/blob/48ec19f400b5d47cf07079060f76cb99f01eb2cb/recipes/sqlite3/all/conanfile.py#L127).

**Comment by tjwrona** [comment]
Thanks, using both generators and adding this to the `test_package` CMakeLists file worked!

```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```

The other things you mentioned are very interesting though so I'll definitely have to look deeper into that and see if I can get it to work that way!

**Comment by tjwrona** [comment]
@intelligide regarding the approach you mentioned above: Does conan generate and install a new target `tnt::dsp` that gets consumed by the `test_package`, or does it install the existing `tnt::dsp` target that is defined within the `CMakeLists.txt` file of the library itself?

This is important because inside the `CMakeLists.txt` file for the `tnt::dsp` library I defined `target_compile_features` and set a `PUBLIC` compiler flag that automatically gets passed to consumers of the library if they use `find_package` and consume the CMake target. If Conan generates its own target and doesn't use the same one that is defined in `CMakeLists.txt` that compiler flag would be missing.

I could define that specific compiler flag in the `cpp_info` section but then I'm specifying it in two places (in the `CmakeLists.txt` file and again in `conanfile.py`) and I am trying to avoid that.

**Comment by intelligide** [comment]
> regarding the approach you mentioned above: Does conan generate and install a new target `tnt::dsp` that gets consumed by the `test_package`, or does it install the existing `tnt::dsp` target that is defined within the `CMakeLists.txt` file of the library itself?

Conan always generate new targets. It can't use author cmake config files without `cmake_paths`.

> This is important because inside the `CMakeLists.txt` file for the `tnt::dsp` library I defined `target_compile_features` and set a `PUBLIC` compiler flag that automatically gets passed to consumers of the library if they use `find_package` and consume the CMake target. If Conan generates its own target and doesn't use the same one that is defined in `CMakeLists.txt` that compiler flag would be missing.
> 
> I could define that specific compiler flag in the `cpp_info` section but then I'm specifying it in two places (in the `CmakeLists.txt` file and again in `conanfile.py`) and I am trying to avoid that.

I know it's not very clean right now to duplicate definitions in the `CMakeLists.txt` and in the `cpp_info` section but this allows the consumer not to be dependent on a particular generator / build system. If the user uses another build system than `cmake`, he will not be able to use your package. I don't know and I don't think that conan will be able to solve this problem in the future without being strongly linked to the build system of the package.

**Comment by tjwrona** [comment]
Okay thank you that answers all of my questions. I am personally okay with this library being dependent on CMake because that is the only way I plan on consuming it so I will proceed with "cmake_paths" but it is good to know what all of my options are and how this all works. With this information I might update it in the future to be more generic that way it can be consumed by other build systems.

It would be really cool if Conan could automatically extract that info from the CMake target somehow and use it to generate its own target but I'm not sure that is even possible.

**Comment by tjwrona** [comment]
I'm closing this question since it was suitably answered. As for Conan being able to propagate compiler flags from CMake targets there is an issue here that I opened a while back that has more info:

https://github.com/conan-io/conan/issues/7479

Since that issue hasn't been closed I assume it is something they are at least looking into. :)

**Comment by intelligide** [comment]
I looked at the [cmake file api](https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html). I think it is possible to integrate it with conan with the `configure` method of the cmake build helper and extract some target info from cmake. I will create a new request to propose this feature. 😉

**Comment by tjwrona** [comment]
That would be awesome, thanks!

**Comment by tjwrona** [comment]
@intelligide Also having a way to extract the package version info from CMake and use that with conan would be very useful! It looks like that may also be possible.
