### ISSUE TITLE
[question] Remote recipe is newer than local recipe?

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#7761]
We have a conanfile.py that can be used on Windows and Linux that hasn't really changed for a while. I'm just trying to create a pre-built package for a new compiler version. But when I rebuilt it with a new compiler version on Linux and tried to upload it to our remote (with already existing packages for Windows and older compilers), I got the following error message:

	Uploading to remote 'vsdk':
	Uploading tinyxml2/8.0.0@vsdk/stable to remote 'vsdk'

	----------------------------------------
	Remote manifest:
	Time: 2020-08-21 11:58:22
	conanfile.py, MD5: 00ac8534c12d9998282be57d1e66e21f

	Local manifest:
	Time: 2020-06-03 13:58:34
	conanfile.py, MD5: 7ebebdbc23fb581e9f6083b778d08e23

	Local 'conanfile.py' using '\n' line-ends
	Remote 'conanfile.py' using '\r\n' line-ends

	----------------------------------------
	ERROR: tinyxml2/8.0.0@vsdk/stable: Upload recipe to 'vsdk' failed: Remote recipe is newer than local recipe:
	 Remote date: 1598011102
	 Local date: 1591192714

	ERROR: Errors uploading some packages

Can anybody explain to me what might be the issue here and how I can resolve it?

Is the only issue maybe that on Windows, the conanfile.py was checked-out with Windows line endings? In that case, is there any constraints on how you are allowed to handle that (e.g. only check out with original line endings on Windows) because I've never read about that anywhere.

(Also maybe it would be useful to not print the Unix timestamp as a large integer but as a readable time in all cases.)

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @fschoenm 

Translating the date to human:
- Remote, server timestamp: August 21, 2020 11:58:22 AM
- Local cache package timestamp:  June 3, 2020 1:58:34 PM

For some reason, your package in local cache is older, and this check doesn't allow to overwrite newer packages. Is it possible that the package in that cache has been there since June?

There are several approaches for this:

- You could try ``conan upload --force`` to force the remote overwrite.
- You can clean the local cache with ``conan remove "*" -f`` (or only the offending package), and then create the package again locally, then re-upload.

**Comment by fschoenm** [comment]
> For some reason, your package in local cache is older, and this check doesn't allow to overwrite newer packages. Is it possible that the package in that cache has been there since June?

As far as I understand, the conanfile.py has not been changed. So in August, a colleague built and uploaded a package and today I built and tried to upload another package with a new OS/compiler combination. So the packages I want to upload don't even exist on the conan server.

1. Can the line endings be a problem here? They lead to different MD5 hashes for the conanfile.py on Windows and Linux. How does conan recognize that both are still the same conanfile.py?
2. Maybe the problem is that some old packages, which should already exist on the server, prevent the complete upload, i.e. also the upload of the newly built packages?

**Comment by fschoenm** [comment]
This was probably due to line endings.
