### ISSUE TITLE
VTK 9.0.1 (hdf5) with apple-clang 12

### ISSUE THREAD

**Issue by divergentscott** [conan-io/conan#7767]
Something about the cmake.configure() method prevents VTK9 from properly compiling with apple-clang 12. This seems more like a cmake configuration error than a conan bug, but I can only reproduce it with conan.

Building VTK 9.0.1 with apple-clang 12 using conan package fails with a surprising definition inclusion error.
https://github.com/divergentscott/conan-vtk/blob/master/conanfile.py

Essentially the same VTK recipe worked with apple-clang 11.
I can build VTK 9.0.1 with apple-clang 12 using their default cmake.
I can build VTK 9.0.1 on linux with gcc and that same conan recipe.
I can even build VTK 8.2.0 (which has similar hdf5 structure) with apple-clang 12 and the same conan recipe with the version swapped out.

Specifically VTK 9 + conan + apple-clang 12 appears to have include errors when building hdf5

### Environment Details 
  * Operating System+version: OSX 10.15.6
  * Compiler+version: apple-clang 12
  * Conan version: 1.29
  * Python version: 3.7.7

### Steps to reproduce (Include if Applicable)

On recipe:

https://github.com/divergentscott/conan-vtk/blob/master/conanfile.py

conan create 
using apple-clang 12

This results in a linking or inclusion error with hdf5:
`
VTK9/ThirdParty/hdf5/vtkhdf5/src/H5Fsuper.c:1397:16: error: implicit declaration of function 'vtkhdf5_H5O__fsinfo_set_version' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]
            if(H5O__fsinfo_set_version(f, &fsinfo) < 0)
               ^
VTK9/ThirdParty/hdf5/vtkhdf5/src/vtk_hdf5_mangle.h:1882:33: note: expanded from macro 'H5O__fsinfo_set_version'
#define H5O__fsinfo_set_version vtkhdf5_H5O__fsinfo_set_version

`

Any ideas about what could be going on?

**Comment by memsharded** [comment]
Sorry this was not followed up back then @divergentscott 

Now this ticket is outdated, from the recipe in ConanCenter to Conan itself, everything has change since then. Closing as outdated, but please don't hesitate to re-open or create new tickets if necessary. Thanks for your feedback.

**Comment by valgur** [comment]
See also: https://github.com/conan-io/conan-center-index/pull/24808
