### ISSUE TITLE
[bug] Settings affect hashes of downstream packages even if they themselves dont have such settings.

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#7768]
### Steps to reproduce (Include if Applicable)
Have package 'binary' with such settings:
    settings = "os", "compiler", "build_type", "arch",

Have a custom settings into your tree:
we have 'os.version' and os.version is either rh6 or rh7.

Now we build packages in in amtrix for both rh6 and rh7, but some of the packages are 'config only packages' hence no binaries so we wanted to pus following settings in there:

Have package 'config' with such settings:
NO SETTINGS WHATSOVER.

We have build a binary in a configuration:
rh6 and rh7.

We have build a config with a configuration of:
rh7. (which to build has downloaded rh7 pacakge. )

What we expected:
We expected that config package without settings which had only 1 build variant (rh7 ) would bode well with both rh7 and rh6 packages. however this turned out not to be the case:

```
Packages
    loadbalancer/0.1.0:f5993055690b241915af85adda4887bd435b090f - Missing
    nginx/1.19.2:de59f23c0368712834df65490d45e46ee798e354 - Download
    xxxx/2.26.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    zzz/3.30.0:f947ce01b8eb4fa4f75c2f45eccdb3693580b93a - Download

Installing (downloading, building) binaries...
ERROR: Missing binary: loadbalancer/0.1.0:f5993055690b241915af85adda4887bd435b090f

loadbalancer/0.1.0: WARN: Can't find a 'loadbalancer/0.1.0' package for the specified settings, options and dependencies:
- Settings:
- Options: xxxx:env=None
- Dependencies: nginx/1.19.2, xxxx/3.30.0
- Requirements: nginx/1.19.2:de59f23c0368712834df65490d45e46ee798e354, runtime-variables-base/None, runtime-variables-pricing/None
- Package ID: f5993055690b241915af85adda4887bd435b090f

ERROR: Missing prebuilt package for 'loadbalancer/0.1.0'
Try to build from sources with "--build=loadbalancer"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

Installation of conan has failed, see above output for detailed info about failure.
```

What we had to do is to build a config package without any settings for both rh6 and rh7.

Also, I have been complaining about this many times, but the build missing investigation is just... very frustrating.

**Comment by memsharded** [comment]
Hi @fulara 

This doesn't seem a bug. The ``package_id`` of each package is a combination (hash) of settings + options + dependencies. Even if the package has no settings, if it has dependencies, you need to discard them. It is totally possible that the configuration package could build a different configuration for each different set of dependencies versions. If your config package is totally independent, then do (in the "config" package:

```python
def package_id(self):
     self.info.requires.unrelated_mode()
```

Please try it and let me know.

Regarding:

> Also, I have been complaining about this many times, but the build missing investigation is just... very frustrating.

Did you use the ``conan search --table`` functionality? It seems in the case above, the output table would just contain values in the ``requires`` column, and entering there in the filter box the requirements that were displayed in the error message (``nginx/1.19.2:de59f23c0368712834df65490d45e46ee798e354``), should make visible that there is no binary available for such dependency, and that the existing binaries are for a different configuration of dependencies.

**Comment by fulara** [comment]
Hello @memsharded 

Yes you are right, I seem to again locked myself in thought minima.

Whether the conan search would help:
![image](https://user-images.githubusercontent.com/5104907/94659289-58d46880-0304-11eb-9b28-cb95f8546fbf.png)

I dont think so, it doesnt point anything. (on top of that there is no package ids for the deps here. )
You know me - I am complaining about the build missing probably since 2nd week i've encountered conan :).

Anyway closing
