### ISSUE TITLE
Can't compile after update to conan 1.29.2 and Xcode 12

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#7770]
Hi,

After uninstall conan and install a fresh version, conan 1.29.2 was installed.

But when i try compile it give me the same error before update:

```
Successfully installed conan-1.29.2
[INFO] Running "conan" on target "ios_framework"...
[INFO] Building for: armv7/Debug...
ERROR: Invalid setting '12.0' is not a valid 'settings.compiler.version' value.
Possible values are ['10.0', '11.0', '5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0', '9.1']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

I need change something after update?

**Comment by paulocoutinhox** [comment]
Hi,

Thanks @uilianries for the help.

Only need remove old settings file:
```
rm -rf ~/.conan/settings.yml 
```

Thanks.

**Comment by memsharded** [comment]
Hi @prsolucoes 

In theory the older ``settings.yml`` file should have been updated when 1.29.2 ran the first time. It checks if the file has been modified by the user, if there are local modifications, it tries to keep it, so maybe that is what happened. Indeed removing the ``settings.yml`` will force regenerating it, so happy to hear that you managed to find the solution.
