### ISSUE TITLE
[bug] conan search comman stuck/infinity

### ISSUE THREAD

**Issue by VladAdGad** [conan-io/conan#7774]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows
  * Compiler+version: gcc 8.1
  * Conan version: 1.29.2
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
Open cmd/PowerShell/Conan and write **conan search "boost/*" -r all

Nothing happen, command just stuck and Ctrl+C reacts after 10-20 seconds
But I can do conan --version and conan install ..

**Comment by uilianries** [comment]
Hi @VladAdGad ! Thanks for your report, indeed is a known issue. Please take a look: https://github.com/conan-io/conan/issues/7573 and https://github.com/conan-io/conan-center-index/issues/950

**Comment by AbrilRBS** [comment]
Closing as solved, new versions of Artifactory (And Conan v2) do not suffer from these timeouts anymore :)
