### ISSUE TITLE
[feature] Add --recipe-only flag to conan export command

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#7787]
When using in-source recipes and the total size of the exported sources is very large, the conan export command takes a long time, and this can be highly problematic is some development workflows (such as mono-repo for example). This problem could be solved by adding a flag to conan export such as `--recipe-only`, which simply copies only the conanfile to the local cache.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
I see two possible problems here:
 * the recipe revision depends on the exported files, if they are not exported we cannot compute the revision
 * after exporting a recipe, it can be uploaded to a remote. If we export without everything required we might end up with broken recipes in a server.

**Comment by solvingj** [comment]
This is a good point and might point to a deficiency that we should improve anyway. 

Do we have any protections in place today to prevent corrupt uploads?  For example, if a `conan export` throws an exception while exporting, or if a `conan create` throws an exception at the end of a `package()` method?  I don't think we do, but long-term maybe we should.  I know we have a "dirty" mechanism related to sources, but I think that's used for something unrelated. Still, it seems a relevant concept here. 

It seems reasonable to implement a similar sentinel file mechanism which `conan upload` looks for before uploading. Conan can create a file at the start of export which indicates that an export has started but is incomplete, and then remove that file after all export operations complete successfully.  Conan upload command can then fail immediately if this file exists, citing an incomplete export operation.  The same strategy could be used for the `package()` method and `conan upload` when binaries are involved.

**Comment by memsharded** [comment]
> the recipe revision depends on the exported files, if they are not exported we cannot compute the revision

Yes, I think that now consistency is a priority. I would prefer not to introduce another source of potential inconsistency (which breaks reproducibility). I would say there are several mechanisms so exports are efficient:

- Export only what is needed, even in monorepo, one single package will export only what it wants, which a performance similar to a multi-repo single repo export.
- Use SCM feature to capture coordinates of the sources.

As we are not moving forward the idea of downloading things at export time for reproducibility (we are proposing another backend mechanism instead), I think this feature will not be necessary at this moment.

**Comment by jgsogo** [comment]
Agree, IMHO this is related to the mechanism of exporting/capturing sources together with the recipe (inside the Conan package). If we decide to follow that path, this requirement will arise again for sure, if not I think this feature is not needed at all. 

Are we missing other scenarios, @solvingj ? If not, I would prefer to close this issue until there is a need for this.

**Comment by solvingj** [comment]
I'm probably the one missing something (that's usually the case). Thanks for your patience in helping me understand things. 

@jgsogo 
In enterprise usage, in-source recipes (which capture sources inside the conan package) is the de-facto standard configuration for private packages.  So, when you say "if we decide to follow that path", it's a bit confusing.  My best guess it that you're probably thinking about Conan Center and potential source-caching, and not the existing world of in-source recipe use-cases.  Can you please confirm or clarify what you were talking about for posterity? (in any case, this ticket was based on real-world enterprise-use case and not Conan Center).

@memsharded 
You have said "I think this feature will not be necessary at this moment".  Since the feature request only intended to provide a performance improvement on an existing feature under certain conditions, I would agree that it is not necessary.  So, to clarify, the estimated negative impact of the current performance is not substantial enough to warrant us working on an improvement.  Is that accurate?  

Also, as you said, one factor was that this could "introduce another source of potential inconsistency" (without the proposed fix).  But, we should clarify that even if this potential inconsistency was eliminated, we still would not support the development of this feature. Is that also correct?

In any case, feel free to close the ticket with comments.

**Comment by memsharded** [comment]
> So, to clarify, the estimated negative impact of the current performance is not substantial enough to warrant us working on an improvement. Is that accurate?

Yes, accurate

> But, we should clarify that even if this potential inconsistency was eliminated, we still would not support the development of this feature. Is that also correct?

It is not very evident to me how this inconsistency could be eliminated. But yes, I don't perceive a big pain in this. We can close by now, and we can always check with the Tribe 2.0 once is launched.
