### ISSUE TITLE
Add conan get command with wildcard

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#779]
Download all packages from a specified remote matching a given pattern to the local cache. This would be useful for a few things:

- if your branches depend on different versions of a package, you can get all the packages you might need if you don't have connectivity to the conan server
- if you want to make a local mirror/backup of a package server

**Comment by memsharded** [comment]
I think that using that for mirror/backup would be extremely inefficient and lack robustness. I'd certainly go for an rsync or some other mechanism intended for that.

Right now, the ``--all`` is already available for ``conan install`` that allows to install all binaries for a given package, but it is not very used, just convenient for a few rare cases, like promoting already compiled binaries from one channel to another or to a different username.

Regarding the offline case, I am not sure that is a real use case. I am not aware of any other package manager that allows to install a copy of all packages locally. In the conan (C/C++) case, it could be even worse, as packages are usually huge compared with other package managers. Just all the binaries for a common library can be many many GBs in disk. Trying to install a copy of all packages of a few tenths of libraries locally can require a huge disk.

**Comment by rconde01** [comment]
I agree it doesn't make much sense for a public server, but more a private server which is the use case I was thinking of. Still it might be nice to be able to get a library into the local cache without installing it to a particular directory. You can delete the directory afterward of course but it's just a bit sloppy.

**Comment by memsharded** [comment]
Yes, actually my main concern is someone (probably not being bad, just by mistake) issuing ``get * -r=conan.io``, which could saturate our servers easily, so we would have to put some limits on conan.io.

For your info, for your private server, it might be quite simple to implement it client side, just a very simple python script would do it: issue a ``conan search``, then parse the output in lines, for each one, issue a ``conan install --all``. I am not worried about that because the search in conan.io is already truncated.

Could you please clarify this sentence?
> to get a library into the local cache without installing it to a particular directory

Not sure what you mean, conan installed packages will go to the conan local cache, but that cache can be easily defined (so you also can have different caches for different projects), with the environment variable ``CONAN_USER_HOME``. Is that variable what you need? Thanks for your feedback

**Comment by rconde01** [comment]
Maybe I'm misunderstanding something. If I do "conan install package_ref" and the package has imports, won't they get copied to the current directory? If I'm just trying to get the package for later use, this would be undesired. I guess a skip-imports option for install would be equivalent to what I was suggesting.

**Comment by memsharded** [comment]
Yes, ``imports()`` works relatively to the current directory so:

- It is possible to import files in a recipe that is being built in the local cache, so if you need some file (lets say an executable of a package you depend on, to generate source code) from a dependency, it gets copied to the local folder. But after that it will be removed, as you don't want to re-package in your current package. These imported files don't leave the conan local cache.
- You can import files to user space (project) only by defining ``imports()`` in the consuming recipe (conanfile.txt or conanfile.py), living also in user space.
- There already exists a ``--no-imports`` argument to install, to skip the imports step: http://conanio.readthedocs.io/en/latest/reference/commands.html?highlight=--no-imports#conan-imports

**Comment by rconde01** [comment]
Ah - that would be sufficient then. Although, the fact that --no-imports doesn't show in the "install" documentation line seems like a documentation bug.

**Comment by rconde01** [comment]
Looks like I was also confused though...as the 'imports' I was thinking of is in the consuming recipe. Sorry.

**Comment by rconde01** [comment]
We can close this. The workaround of a wrapper script would be sufficient.

**Comment by memsharded** [comment]
Thanks for telling and closing!
