### ISSUE TITLE
[question] consumer package overrides to version lower than required by another dependency?

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#7790]
I have 2 libraries and an application: libsystem, libcore, and myapp such that:
- libsystem: no dependencies
- libcore --> libsystem
- myapp --> libcore & libsystem

myapp requires specific versions: 
- libcore/1.0.1
- libsystem/1.0.0 

I'm explicitly calling out libsystem as I want to ensure a specific version in myapp

libcore/1.0.1 uses a range for libsystem where the minimum version is a prerelease version later than 1.0.0 
- libsystem/[>=1.1.0-dev.1.2, include_prerelease=True] 

as there was a feature added to the prerelease version of libsystem that is required by libcore/1.0.1

That version range resolves to libsystem/1.1.0, which is the official release that includes the feature libcore needs.

When I run conan info/install on myapp I get a warning that the libsystem requirement specified by libcore/1.0.1 is overridden down to libsystem/1.0.0 such that the dependencies installed are libcore/1.0.1 and libsystem/1.0.0

This seems strange to me. I would have expected conan to yell at me that libsystem/1.0.0 is incompatible with libcore/1.0.1? Am I missing something?

Even if I take it that I specified libsystem/1.0.0 so conan is letting me shoot myself in the foot, the warning is the same for when conan overrides to a higher version, so it's easy to overlook the downgrade. Or maybe a way to tell conan to terminate if this happens seems like it would be useful?

I'm using conan 1.29.2.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> This seems strange to me. I would have expected conan to yell at me that libsystem/1.0.0 is incompatible with libcore/1.0.1? Am I missing something?

No, you are not missing anything. One rule of thumb in Conan is that the downstream consumer always has precedence and defines what is needed. If the downstream ``App`` package says that it will depend on libsystem/1.0.0, then, that exact version will be used, overriding whatever is found upstream. 

There is a configuration ``general.error_on_override`` that you can activate in your conan.conf, to avoid overrides, this will force exact matching, but I think this might not be enough, because the override will still happen and raise an error. Maybe you want to define a version range in ``App`` too?

**Comment by nichmj01** [comment]
The error_on_override as implemented right now doesn't work since it will error for every override; even compatible overrides.
 
For example, if I set `App ` to depend on `libsystem/1.1.0` I still get the error even though `libsystem/1.1.0` is compatible based on the requirements specified by `libcore/1.0.1`.

I'm not sure a version range in `App` will solve my root care about.

I want to lock `App` to a specific set of dependency versions as those versions that were vetted at some point. If at some point I realize I need to upgrade a dependency I'd like the other dependencies to stay the same unless they are incompatible with the one that is being changed. 

Maybe I can use lockfiles in some way?

In my example, it seems like conan is assuming I want to downgrade to `libsystem/1.0.0` and is letting me do so even though `libsystem/1.0.0` is incompatible with `libcore/1.0.1`.  In my mind, I'm trying to upgrade to `libcore/1.0.1` and I'd like conan tell me that `libsystem` also needs to upgrade and that the minimum version available that will work is `libsystem/1.1.0`. 

I could remove `libsystem` as a dependency but based on the current version ranges, `libsystem` could go to a version 2, which could also break `App`.

I can understand why the downstream consumer takes precedence and don't disagree with it. However, it seems like conan is currently not taking the version ranges of dependencies into account. The current behavior seems to be: if `App` requires a `libsystem` version different than the version `libcore` resolved to print a warning. That's great. I would also like conan to print a different warning when the version of `libsystem` that `App` specifies is outside the range that `libcore` requires. Maybe something like: 
`WARN: myapp/1.0.0 override to libsystem/1.0.0 is incompatible with libcore/1.0.1-dev.1.0 requirement libsystem/[>=1.1.0-dev.1.2, include_prerelease=True]`

And also provide a way to make that warning an error which can be overridden with the `override` keyword.

It's be great if it could tell me the minimum version like I mentioned above, but if all I can get is the warning/error I think that would be fine as I can see the version range in the warning/error and probably figure out the minimum version.

**Comment by nichmj01** [comment]
As an addition, this is not for a CI process as I've read some stuff about lockfiles wrt to CI. The use case is that the company I work for writes software we deliver to customers. For the final application, we provide the source to the customer which they take ownership of and build in house. When we deliver the final release, I would like to have all the versions specified to the versions we have tested against.

**Comment by nichmj01** [comment]
Any additional thoughts on this? Seems like the functionality I'm looking for doesn't exist right now. Does what I'm looking for make sense? If so, maybe it's something that could be added in the future?

**Comment by memsharded** [comment]
Conan 2 completely changed how overrides work, including not overriding by default and always conflicting except if ``override/force=True`` is explicit.
It also changed how version ranges and fixed versions are processed when found in the same graph.
Closing this ticket as outdated, please create new tickets for any further question or issue, thanks for your feedback.
