### ISSUE TITLE
[feature] 'conan info' to return the package revision

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#7796]
Currently, the `conan info` command returns the recipe revision, but information about package revision is not available:

```json
{
        "revision": "a9d892fd37101b88578f17fbc04b9d60",
        "reference": "boost/1.70.0",
        "is_ref": true,
        "display_name": "boost/1.70.0",
        "id": "d45e2a7cc75163518ffbbda3fa886038ecaa8f54",
        "build_id": null,
        "remote": {
            "name": "conan-center",
            "url": "https://conan.bintray.com"
        },
        "url": "https://github.com/conan-io/conan-center-index",
        "homepage": "https://www.boost.org",
        "license": [
            "BSL-1.0"
        ],
        "description": "Boost provides free peer-reviewed portable C++ source libraries",
        "topics": [
            "conan",
            "boost",
            "libraries",
            "cpp"
        ],
        "recipe": "Cache",
        "binary": "Cache",
        "binary_remote": "conan-center",
        "creation_date": "2020-08-31 13:15:59",
        "requires": [
            "zlib/1.2.11",
            "bzip2/1.0.8"
        ]
    },
```

It should be easy to add and more convenient than running `conan search <ref>#<rrev>:<pid> --revisions` afterward.

**Comment by uilianries** [comment]
I would say `-rev` and `--revisions`, because `conan search` offers the same.

**Comment by jgsogo** [comment]
I think it doesn't require an extra argument: if revisions are enabled that information would be in the JSON output, otherwise it won't

**Comment by uilianries** [comment]
Ah yes, totally agree.

**Comment by sdmg15** [comment]
Hello @jgsogo I'll work on this issue :)

**Comment by jgsogo** [comment]
> Hello @jgsogo I'll work on this issue :)

Cool! Let us know if you have any doubts about how to implement it.

Thanks!

**Comment by sdmg15** [comment]
https://docs.conan.io/en/latest/versioning/revisions.html#how-it-works
As per this doc a package can have multiple package revisions (PREV) so I was thinking of adding an additional property `package_revisions`

```
{
....
"package_revisions": [
"4d220773f957e44a93a9a780f652e7c3",
"4e220773f957e44a93a9a780f652e7c3",
],
....
}
```

is that correct ?

**Comment by jgsogo** [comment]
`conan info` returns information for a single package, by default the one in the Conan cache. In the Conan cache there is only one package revision at a time (and only one recipe revision), so there is only one value for the `package_revision`.

The information is stored in the `metadata.json` file in the cache, you can use `self._cache.package_layout(ref).load_metadata()` to access that information. Then you have to store it in the `data` dictionary returned by method `_grab_info_data` in `CommandOutputer` (have a look at this method and how the `remote` and `revision` values are returned) and print it in the method `print_info` of `Printer` class.

These are not the best pieces of code, they contain a lot of legacy, so feel free to open a PR with a draft and we can help you with it.

Thanks!
