### ISSUE TITLE
Accessing conan trough a proxy

### ISSUE THREAD

**Issue by bachp** [conan-io/conan#78]
In corperate environments it is frequently the case that internet connection must go trough a proxy server, sometimes even with authentication required.

It would be good if conan would at least support the following proxy scenarios:

1. Access the internet trough a HTTP/HTTPS proxy without authentication
2. Access the internet trough a HTTP/HTTPS proxy with authentication required
3. Access the internet trough a SOCKSv5 proxy (this allows using SSH tunnels)

**Comment by memsharded** [comment]
Conan is using the python "requests" library. From the docs: http://docs.python-requests.org/en/latest/user/advanced/#proxies

It should be possible to define environment variables like:

```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

or using user/pass urls in the form "http://user:pass@10.10.1.10:3128/"

I suggest doing a first try with environment variables to check if it works, as a temporary workaround while a proper solution is developed.

**Comment by bachp** [comment]
Indeed it is working with the solution proposed above.

I also got it working on windows using the following:

```
> set HTTP_PROXY=http://10.10.1.10:3128
> set HTTPS_PROXY=http://10.10.1.10:1080
```

Note  that you must not put `"` around the proxy otherwise it won't work.

I think it is worth to add this to the documentation.

**Comment by lasote** [comment]
great! I'm creating a new issue in conan docs repository to update it with this information.

Thanks

**Comment by memsharded** [comment]
Hi @bachp 

Proxy configuration has been included in 0.7 release in the conan.conf file, with the following syntax:

```
[proxies]
# Empty section will try to use system proxies.
# If don't want proxy at all, remove section [proxies]
# As documented in http://docs.python-requests.org/en/latest/user/advanced/#proxies
# http: http://user:pass@10.10.1.10:3128/
# http: http://10.10.1.10:3128
# https: http://10.10.1.10:1080
```
Just in case you prefer to use it instead of environment variables. Cheers.

**Comment by bachp** [comment]
Thanks for the update

**Comment by SC-One** [comment]
It's not possible to add socks5 to Conan ?! (it's just http, https)

**Comment by akukhta** [comment]
Hello. For those who are stuck with conan 2 and proxy server, and came here as first page google links to, here is how to specify proxy server in conan2:

- Go to ~/.conan2/

- Add this lines to global.conf file ("http" and "https" should be in lower case) and replace PROTOCOL, IP and PORT with your settings
`core.net.http:proxies={"http" : "PROTOCOL://IP:PORT/", "https" : "PROTOCOL://IP:PORT/"}`

Yes, i realize that this information should be known for those who have worked with Request python library, but since Conan is C and C++ package manager, not all developers may be aware of that

Thanks!

**Comment by memsharded** [comment]
Thanks for the feedback @akukhta !

We have a pending task in https://github.com/conan-io/docs/issues/3410, to add this to our docs, but unfortunately too many things on our plate, we haven't managed to catch up on this one. I will add a link there to your comment
