### ISSUE TITLE
[question] Legacy packages from conan channel

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#7801]
One of our recipes references 7z:

self.build_requires("7z_installer/1.0@conan/stable")

This package is no longer available. Seems like it has been relocated to a new remote. How do I reference that remote?

self.build_requires("7zip/19.00@conan-center/stable") doesn't work.
Nor does self.build_requires("7zip/19.00"). 

Is there another way to specify conan-center remote without adding it? And if we do have to add it, how will it co-exist with our private remote?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by intelligide** [comment]
`self.build_requires("7zip/19.00")` should work. Check your remotes list with `conan remote list` if a remote with the url `https://conan.bintray.com` is present. if not, `conan remote add conan-center https://conan.bintray.com`.

**Comment by memsharded** [comment]
Why the build requires would fail? How does it fail? If you are sure it fails, can you try to run:

```bash
conan install 7zip/19.00@ -r=conan-center
```
That should install successfully the package in your cache.

> Is there another way to specify conan-center remote without adding it? And if we do have to add it, how will it co-exist with our private remote?

You have several alternatives:
- Adding the remote after your own one will give priority to your own repository. When installing it will check first in your own repository, then if the package is not found there, it will check in ConanCenter.
- You can add the remote, get the packages you want, and upload a copy to your own private repository. Then ``conan remote remove`` or ``conan remote disable`` that remote, to guarantee that you are getting everything from your own private repository.
- You can have Artifactory to setup a remote repository to proxy ConanCenter (and it also caches packages from ConanCenter, making it more robust against failures)

**Comment by w3sip** [comment]
Thanks!  I guess the biggest difference was that with the older versions conan/stable could be addressed from conanfile.py without adding another remote explicitly. With the current setup, adding conan-center remote is required.

The info in James' response is super useful: having it in the docs in some shape would be beneficial.

Thanks again!
