### ISSUE TITLE
[feature] Settings constraints using predicates

### ISSUE THREAD

**Issue by kralicky** [conan-io/conan#7808]
Because there are a lot of built-in settings, adding settings restrictions in a recipe can be cumbersome/error prone when dealing with long lists of many values. Furthermore, restricting settings is not future-proof for some settings such as compiler version.
I propose the ability to filter the default settings using a predicate. This will have the benefit of making some settings future proof, making the intent of the restriction more clear, and making it easier for developers to implement settings restrictions.

Example: Your package needs C++14, so you want to restrict the allowed compiler versions to those which support C++14: gcc 5, clang 3.4, apple clang (any), Intel 17, and VS 15.
Currently, you would have to write:
```python
settings = {
    "compiler": {
        "gcc": {"version": ["5", "6", "7", "8", "9", "10"]},
        "clang": {"version": ["4", "5", "6", "7", "8", "9", "10"]},
        "apple-clang": None,
        "intel": {"version": ["17", "18", "19"]},
        "Visual Studio": {"version": ["15", "16"]}
    }
}
```
Or you could remove all the other versions in configure(), as such:
```python
def configure(self):
    self.settings.compiler["gcc"].version.remove("4") # oops, this doesn't do what you expect
    # etc...
```
But the versions are major.minor in settings.yml, so you would have to specify all of them:
```python
def configure(self):
    self.settings.compiler["gcc"].version.remove(["4.1", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9"])
    # etc...
```
Which works, but doesn't feel like it should be the canonical way to restrict compiler versions.

A better solution could be the following:
```python
settings = {
    "compiler": {
        "gcc": {"version": lambda v: tools.Version(v) >= 5 },
        "clang": {"version": lambda v: tools.Version(v) >= 3.4 }
        # etc...
    },
}
```
This will filter the settings from settings.yml based on the given predicate, in this case all gcc versions >= 5.
This solution is future proof, and more closely models compiler support for c++ standards, i.e. gcc has c++14 support in any version >= 5, it is not restricted to specific versions.

Conan could even provide some builtin constraint functions based on [this table](https://en.cppreference.com/w/cpp/compiler_support), something like this:
```python
settings = {
    "compiler": {
        "gcc": {"version": tools.cppstd_support("gcc", "14")},
        "clang": {"version": tools.cppstd_support("clang", "14")}
        # etc ...
    }
}
```
Take a look at my implementation of this feature here: https://github.com/cobalt77/conan/commit/39b250c9950bfa105012d5a8138f89585d4c702f

Related comment by @tjwrona1992: https://github.com/conan-io/conan/issues/7772#issuecomment-703320956

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this was not responded back then.

Declarative constraints of ``settings`` in recipes has been dropped in Conan 2.0 in favor of ``validate()`` methods. Closing as outdated.
