### ISSUE TITLE
[question] - identify export_sources at build time (recipe_revision)

### ISSUE THREAD

**Issue by Nodroc** [conan-io/conan#7819]
Hello, 

For the sake of my project, I would like to know wether there is a way to fetch the recipe_revision at conan package 'build' time.

The reason for that is the following:
- I will release a package with a certain 'version'. that package is delivered in both binary (e.g. through the conan package) and sources (so that the user can actually update the package content up to its need).
- as a developper I want to be sure that for 'complaining' users, there are using the same package as initially distributed.
- my idea was to embed into the binary conan package (binary) the value of the _recipe_version_ so that once the software is running I have some sort of 'help/about' tab that can actually display the _recipe_version_ hash which led to the software actually used by the user. 
I tried multiple stuff like reading the PackageMetadata etc.. but never could get the actual _recipe_version_ which I think is already available at build stage by conan.

thanks for your support.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I don't think this is possible right now, and it is a valid feature request to have this information. This would also apply to dependencies.

**Comment by Nodroc** [comment]
@memsharded thanks for your answer. you indicated 2.0 as possible fixed version. is there a place where the release schedule is official ?

**Comment by memsharded** [comment]
> @memsharded thanks for your answer. you indicated 2.0 as possible fixed version. is there a place where the release schedule is official ?

Nop, we typically plan ahead 1-2 versions, as milestones, a new version is released approx monthly, at the end of the month (1.30 is due today, it was delayed from last week).

2.0 is a long term effort, and will require at least 6 months. We have defined a working group (https://blog.conan.io/2020/07/28/Launching-Conan-2.0-Tribe.html) to discuss changes, scope, etc of Conan 2.0. The "information access" feature, a re-design of what recipes can see from the dependency graph is something we want to improve for Conan 2.0, so it is very likely that this will be addressed there. Depending on the changes, we might want to integrate something in a 1.X release, but it is too early to know.

**Comment by Nodroc** [comment]
thanks for the details. I'll try to workaround this be invoking a conan export during build time of the package. looking to the code, this should actually produce the recipe_revision as I expect

**Comment by sourcedelica** [comment]
Would `conan search —rev ref` not work for you?  Assuming that the version in the cache is the version you are building with.

**Comment by Nodroc** [comment]
@sourcedelica  I am not 100%. 
what is the cache is empty (e.g. you build the package for the first time) or if you have a recipe revision in the cache but with local changes ?
using `conan search -rev ref` would return the recipe revision of the previous built package, not the new one (even more misleading ) am I right ?

**Comment by memsharded** [comment]
Both the ``self.ref`` and ``self.dependencies["mydep"].ref`` attributes are full references, containing the version and the ``recipe_revision``. Closing this as solved (was a target in 2.0, but was made available too in 1.X)
