### ISSUE TITLE
Create an official @conan/stable channel for conan.io

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#782]
Using conan.io has a few problems currently:
* It is not guaranteed that a package really works: #748 
* It is unclear if the package has been compromised, this is a security risk that has been brought up [every now and then](http://blog.conan.io/2016/10/05/New-security-measures-for-conan-C-and-C++-package-manager.html)
* There are often multiple sources, for a new user this can lead to using a bad recipe instead of a well maintained version: #780 
* ...

A solution could be to have official conan packages on `@conan/stable`. These packages will primarily be used when using conan.io. All other packages are still usable, but not shown as prominent as the official packages. Using an official package from conan.io guarantees to the user that the package he's using works as expected. Packages from `@conan/stable` only depend on other packages from the same channel.

It could be as easy as having a conan user that's only used by lasote, memsharded and the likes where recipes are copied to.

It could also be an option to have all other user packages as some kind of "staging area", where packages that fulfill a set of requirements are then converted to `@conan/stable` packages.

This kind of workflow is not very overwhelming (though there's certainly some overhead), though it solves the above mentioned issues.

**Comment by monsdar** [comment]
This feature can be built upon in later stages of conan development. Perhaps it is possible to define default channels per server or to tell conan to only download from certain channels etc pp.

**Comment by lasote** [comment]
I, naturally, like the general idea, but guaranteeing the high quality of the recipes is a hard task. Even my recipes are far to be perfect, so as you point, it will require:

- A LOT of time.
- A great community collaboration, including good workflow/criteria/tools/infrastructure/communication channel. To reach the desired quality, take decisions about what is an official recipe, desired policy of updates of the recipes ....etc. Take into account that the scope for improvement recipes is huge, recently I've been working hard in cross compiling for the new release and I have new versions for Zlib and libpng, recipes that worked pretty well in other scenarios. Also, conan continuously improves with "helpers" and "tools" that make recipes easier and more readable, so a criterion about recipe compatibility will be another thing to define.

I'm not pessimistic, I think soon or later would be able to do it but it's not easy.

If any user wants to outline how it could be achieved this thread is a good place to start!

**Comment by memsharded** [comment]
This is now bintray conan-center. I guess it can be closed.
