### ISSUE TITLE
[bug] intel functions exposed under tools without prefix

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#7820]
Starting with Conan version 1.30.0, the following existing intel-related functions are made public use inside `conanfile.py`. 

- `tools.compilervars()`
- `tools.compilervars_dict()`
- `tools.compilervars_command()`

Physically, these functions live in the `conans.client.tools.intel` package, but are "exposed' to `conanfile.py` under the `tools` package:
`from tools import compilervars`

Unfortunately, exposing them directly under the `tools` package makes the function names ambiguous. For clarity, these function should be renamed to begin with the prefix of `intel_`. 

### Environment Details (include every applicable attribute)
  * Operating System+version: All
  * Compiler+version: Intel all
  * Conan version: 1.30.0
  * Python version: All

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/7821
