### ISSUE TITLE
[bug] jinja2 minimum version required it not correct

### ISSUE THREAD

**Issue by ApatheticsAnonymous** [conan-io/conan#7822]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18
  * Compiler+version: gcc-7
  * Conan version: 1.29.1
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)
While upgrading conan to a recent version, we get error due to an out of date jinja2 version on the system.
Reproducible by forcing jinja2 version < 2.9

`     [exec]   File "/usr/local/lib/python3.7/dist-packages/conans/client/cache/cache.py", line 7, in <module>
     [exec]     from jinja2 import Environment, select_autoescape, FileSystemLoader, ChoiceLoader
     [exec] ImportError: cannot import name 'select_autoescape' from 'jinja2' (/usr/lib/python3/dist-packages/jinja2/__init__.py)
     [exec]     from jinja2 import Environment, select_autoescape, FileSystemLoader, ChoiceLoader
     [exec] ImportError: cannot import name 'select_autoescape' from 'jinja2' (/usr/lib/python3/dist-packages/jinja2/__init__.py)
     [exec] -- Configuring incomplete, errors occurred!
     [exec] See also "/tmp/src/k0/tools/generated/CMakeFiles/CMakeOutput.log".
     [exec] CMake Error at generated/conan.cmake:328 (message):
     [exec]   Conan install failed='1'`

select_autoescape appears to have been added in jinja2 2.9. Conan's requirements.txt only specifies 2.3 as a minimum. 

https://github.com/conan-io/conan/blob/47928cbcd3db1ff05798c5f36fc900412f9fa7c9/conans/requirements.txt#L15

**Comment by memsharded** [comment]
Jinja 2.9 is 3 years old, I think we can set it now as a minimum require.

Thanks @ApatheticsAnonymous for reporting, if you want to submit the  PR yourself, we can include it in next release (otherwise we will do it, just in case you want to contribute it).
