### ISSUE TITLE
[feature] Add OpenBSD support

### ISSUE THREAD

**Issue by Liorst4** [conan-io/conan#7829]
Conan can't work on OpenBSD.

```
ERROR: Invalid setting 'OpenBSD' is not a valid 'settings.os' value.
Possible values are ['AIX', 'Android', 'Arduino', 'Emscripten', 'FreeBSD', 'Linux', 'Macos', 'Neutrino', 'SunOS', 'Windows', 'WindowsCE', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
```

**Comment by memsharded** [comment]
Hi @Liorst4 

Please have a look at https://docs.conan.io/en/latest/extending/custom_settings.html. It is relatively straightforward to enable new OSs:
- Add it to your settings.yml
- Add it to your profiles

It is true that many integrated build helpers like ``CMake`` or ``AutotoolsBuildEnvironment`` might contain logic that will be validated mostly for ``Linux`` systems, so it would be necessary to update them. If you are going to use Conan with OpenBSD, I'd suggest do those first 2 steps and start trying, and report. Implementing your build helpers is also possible, but if things move forward and start working reasonably, we could add ``OpenBSD`` to the existing default settings and start improving the built-in build helpers to account for this OS.

**Comment by memsharded** [comment]
Closing as not staled and not planned (and trivial to add for users that want it, specially in Conan 2 with ``settings_user.yml``).

For deeper integrations, like the ones with ``CMake`` build generators and helpers, it would be necessary to get the reports from someone using that platform, without that feedback, we cannot do much.

So if you still have interest in this, please report at least about the most popular ``CMake`` integration, and we can consider this again. Many thanks!
