### ISSUE TITLE
Do not allow to use certain usernames on conan.io

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#783]
I was just able to snag away the usernames `conan` and `conanio`. If in the wrong hands, usernames like this could be used to indicate offical packages.

Conan.io just has a small size as of now, so overwatching this manually will work for the midterm. Better would be to implement a filter that prohibits using names like this.

I gave the login credentials to @memsharded via Slack.

**Comment by lasote** [comment]
Thanks @monsdar
