### ISSUE TITLE
[bug] Symbolic link is not preserved when using self.copy

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7834]
This behavior was observed while packaging mpdecimal in https://github.com/conan-io/conan-center-index/pull/3116

When using `self.copy` on the built shared libraries + symbolic links, the symbolic links are not preserved.

During `build`, the following files are created:
```
$ ls -al build/2af715f34a7c8c2aeae57b25be0a52c4110dc502/source_subfolder/libmpdec/libmpdec*

lrwxrwxrwx. 1 maarten maarten     17  6 okt 20:47 build/2af715f34a7c8c2aeae57b25be0a52c4110dc502/source_subfolder/libmpdec/libmpdec.so -> libmpdec.so.2.5.0
lrwxrwxrwx. 1 maarten maarten     17  6 okt 20:47 build/2af715f34a7c8c2aeae57b25be0a52c4110dc502/source_subfolder/libmpdec/libmpdec.so.2 -> libmpdec.so.2.5.0
-rwxrwxr-x. 1 maarten maarten 245176  6 okt 20:47 build/2af715f34a7c8c2aeae57b25be0a52c4110dc502/source_subfolder/libmpdec/libmpdec.so.2.5.0
```

During `package`, the following files are copied to the package folder:
```
$ ls -al package/2af715f34a7c8c2aeae57b25be0a52c4110dc502/lib
total 932
drwxrwxr-x. 2 maarten maarten   4096  6 okt 20:47 .
drwxrwxr-x. 5 maarten maarten   4096  6 okt 20:47 ..
-rwxrwxr-x. 1 maarten maarten 245176  6 okt 20:47 libmpdec.so
-rwxrwxr-x. 1 maarten maarten 245176  6 okt 20:47 libmpdec.so.2
-rwxrwxr-x. 1 maarten maarten 245176  6 okt 20:47 libmpdec.so.2.5.0
```

The relative symbolic links should be preserved.

### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora Linux 29
  * Compiler+version: gcc 9
  * Conan version: 1.30.0
  * Python version: 3.7.7

### Steps to reproduce (Include if Applicable)

Execute these steps on Linux, using e.g. gcc

1. Checkout https://github.com/conan-io/conan-center-index/pull/3116
2. 
    Run:
    ```
    conan create . mpdecimal/2.5.0@ -o mpdecimal:shared=True -o mpdecimal:cxx=False
    ```
3. examine the build and package folder...

**Comment by Nocccer** [comment]
self.copy has a option called symlink. Set it to true, and self.copy will copy symlinks. Default it is set to None.
See also https://docs.conan.io/en/latest/reference/conanfile/methods.html#package

Hopefully this fix your issue :).

**Comment by memsharded** [comment]
``self.copy`` dropped in favor of ``copy(self, ``, closing as outdated
