### ISSUE TITLE
Is there any option available to filter the existing issues/bugs in conan by the version?

### ISSUE THREAD

**Issue by kannan-Test** [conan-io/conan#7838]
Is there any option available to filter the existing issues/bugs in conan by the version from the following list other than the Milestones option(which has only three versions 1.31,1.30.1 and 2.0) ?
https://github.com/conan-io/conan/issues

and is it possible to add the status of the issues also like fixed/open?

**Comment by memsharded** [comment]
Hi @kannan-Test 

When issues are fixed, they are closed. You can check closed issues also by previous, closed milestones:  https://github.com/conan-io/conan/milestones?state=closed

Is this what you are looking for?

**Comment by kannan-Test** [comment]
@memsharded This helped. 
Thank you
