### ISSUE TITLE
FreeBSD testing support

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#784]
FreeBSD has some initial support thanks to @mropert , but the test suite is failing. Let's try to work on this and have a green build in FreeBSD, @mropert can help with testing, thanks so much!

Tentatively adding this to 0.18 release.

**Comment by memsharded** [comment]
With #792 changes, the build in FreeBSD should be green.

Added "golang" test attr, so if you want to run the tests skipping those using golang, you can do:

```bash
$ nosetests . -a !golang
```

**Comment by memsharded** [comment]
Hi @mropert , this will be released in next conan 0.18, if you are able to test it (running from develop branch now) in your local freebsd, please tell. Thank you!

**Comment by mropert** [comment]
Yes sorry about that, I've been away for a while.
I'll try to check it out this week.

**Comment by mropert** [comment]
Hello @memsharded, we're almost there, I got only one failure, great work!
Any idea what this is?

`======================================================================
FAIL: reuse_test (conan.conans.test.integration.python_diamond_test.PythonDiamondTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sagara/projects/conan/conans/test/integration/python_diamond_test.py", line 48, in reuse_test
    str(self.client.user_io.out).splitlines()[-6:])
AssertionError: Lists differ: ['Hello Hello4', 'Hello Hello3... != ['Project: Build stuff Hello3'...

First differing element 0:
'Hello Hello4'
'Project: Build stuff Hello3'

- ['Hello Hello4',
-  'Hello Hello3',
-  'Hello Hello1',
-  'Hello Hello0',
-  'Hello Hello2',
-  'Hello Hello0']
+ ['Project: Build stuff Hello3',
+  'Project: Build stuff Hello1',
+  'Project: Build stuff Hello0',
+  'Project: Build stuff Hello2',
+  'Project: Build stuff Hello0',
+  'bash: python: command not found']

----------------------------------------------------------------------
Ran 405 tests in 693.065s

FAILED (failures=1)`

**Comment by memsharded** [comment]
Dont know exactly what is failing, but the clear culprit is: https://github.com/conan-io/conan/blob/develop/conans/test/integration/python_diamond_test.py#L44

```bash
bash -c "source activate.sh && python main.py"
```
This is failing to launch in FreeBSD. If you check the current folder of the test (print before that ``self.client.current_folder``, you can move manually to that folder after the failing test (use ``nosetests conans.test.integration.python_diamond_test``) and check manually why the command is failing.  Something about the shell config, that it cannot find the path to your python installation.

**Comment by memsharded** [comment]
Great! Thanks for telling :)
