### ISSUE TITLE
[feature] outdated build_policy on current package but not it's dependencies 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#7845]
Hello,

Build policy as described here https://docs.conan.io/en/latest/mastering/policies.html is a powerfull feature, but we would like to **only** build current package if outdated but not the dependencies. 

Currently we use `outdated` policy to optimize CI builds avoiding non necessary builds if the package already exist, however sometime this silently triggers rebuilds of the dependencies which is an undesirable behavior.   

If there a way to achieve that right now by only applying `outdated` on the current package but not the dependencies? and is there any plan to add this ability ?

Thanks,
Walid

**Comment by memsharded** [comment]
``outdated`` build policy no longer exists in Conan2, closing as outdated.
