### ISSUE TITLE
[question]  How to add environment variable with paranthesis to self.env_info?

### ISSUE THREAD

**Issue by FramnkRulez** [conan-io/conan#7849]
I need to set the x86 DOTNET_ROOT environment variable, but python complains about this due to parans:

self.env_info.DOTNET_ROOT(x86) = self.package_folder

I also tried:

self.env_info["DOTNET_ROOT(x86)"] = self.package_folder.

Is there a way to do this?

**Comment by memsharded** [comment]
Hi @FramnkRulez 

Maybe setting the attr explicitly:

```python
setattr(self.env_info, "DOTNET_ROOT(x86)", self.package_folder)
```

Please try that and let me know.

**Comment by FramnkRulez** [comment]
Yes, that seemed to work.  Thank you!
