### ISSUE TITLE
Unable to connect to conan.io=https://server.conan.io

### ISSUE THREAD

**Issue by FaTony** [conan-io/conan#785]
I'm getting this error every time I try to launch Conan.

Debian Testing 64 bit. Installed Conan via DEB package.

**Comment by lasote** [comment]
I can connect with the server normally. Are you running any specific command or using any firewall or special configuration?

**Comment by FaTony** [comment]
I have ufw which is set to block incoming connections but I don't think Conan listens on any port. I have no problems with other networking apps.

**Comment by a-teammate** [comment]
https://ci.appveyor.com/project/inexor-game/code/build/0.1475/job/9x20rdvnj5xc0eti#L115 Is this the error you're getting?
It seems to happen randomly in our CI, but this is the first time I noticed it. Dunno if its caused by the same thing, maybe not.

**Comment by memsharded** [comment]
Hi Malte,

No, that error is a somewhat typical connection error of Amazon (AWS) S3 storage which is the backend storage of conan.io.

There is very little we can do about it to avoid the failure, so what we are considering is a retry, please check: https://github.com/conan-io/conan/issues/786

**Comment by memsharded** [comment]
@FaTony ,

Could you please try just pinging the server from your computer?

```bash
$  ping server.conan.io
```

**Comment by FaTony** [comment]
fatony@gnu1:~$ ping server.conan.io
    PING conan.io (188.166.34.211) 56(84) bytes of data.
    64 bytes from 188.166.34.211 (188.166.34.211): icmp_seq=1 ttl=55 time=51.4 ms
    64 bytes from 188.166.34.211 (188.166.34.211): icmp_seq=2 ttl=55 time=51.2 ms
    64 bytes from 188.166.34.211 (188.166.34.211): icmp_seq=3 ttl=55 time=51.3 ms
    64 bytes from 188.166.34.211 (188.166.34.211): icmp_seq=4 ttl=55 time=51.0 ms
    64 bytes from 188.166.34.211 (188.166.34.211): icmp_seq=5 ttl=55 time=51.0 ms`

**Comment by memsharded** [comment]
Hi @FaTony, 
We cannot reproduce the issue here. If you want, we might try to do some more interactive pair-debugging, we are available at freenode, slack, hangouts... write us an email if you are interested.

About your comment, no, conan doesn't listen on any port, it is pure client.

You might try to use the pip package instead of the deb one, just in case is something with the bundling of the app.

**Comment by FaTony** [comment]
Ok, I've uninstalled DEB package and installed Conan via pip and it works. Deb package is definitely broken on Debian Testing.

**Comment by memsharded** [comment]
Good, at least you can have conan running. Probably something in the Deb package is broken, you are right. Most likely could be the SSL, it is always problematic, also in OSX.

This is why we are now always recommending installing conan via pip, it is less problematic, has no limitations (the installers might have limitations, because they are bundled with pyinstaller as standalone apps). We will have a look at this, but I strongly suggest keeping with the pip package. Thanks for your feedback!

**Comment by lasote** [comment]
Hi, the deb package is working fine with Debian jessie 8.6 (latest stable and currently latest version).
I'm closing the issue, without more information we can't do more. Please reopen the issue if you have more information or any other user is experiencing problems with deb package.
Thanks.

**Comment by FaTony** [comment]
Have you tested on Debian Stretch? I stated several times that Stretch is broken, not Jessie.

**Comment by memsharded** [comment]
Just in case. One of the policies with "testing" debian releases is that they do not get security fixes by default in a proper way, so the entries in ``sources.list`` have to be pointed to Jessie ones. I said so, because as I said, it could be some SSL issue.

**Comment by FaTony** [comment]
I do not have Jessie entries in my `sources.list`. Yes, Testing usually gets security fixes a few hours or days after Stable but otherwise it's pretty much the same.

**Comment by memsharded** [comment]
Hi @FaTony,

Sorry for not being able to fix the installer on Debian Stretch. We will follow the same policy we did with recent python 3.6. We were reported failures while it was in beta, but didn't address them until released as stable. 

Maintaining installers for many different OSs and systems takes a lot of time, and it is almost impossible to have 100% working installers for all systems. So as long as the pip installer is working, we will not address these issues for alfa, beta and testing systems. Hope you understand, thanks very much again for your feedback.
