### ISSUE TITLE
[feature] Make virtualenv's activate.sh more robust

### ISSUE THREAD

**Issue by antoine-bussy** [conan-io/conan#7853]
Hi,

While trying to use the virtualenv on Cygwin with Zsh, I stumbled on backslashes problems. After investigating, I discovered it came from the different default handing of backslashes by echo between sh and zsh (see https://stackoverflow.com/questions/16430628/zsh-escape-backslash).

Therefore, I think it might be a good idea to explicit echo's handling of backslashes in the activate.sh script generated by the virtualenv generator, that is changing the following line:
```
LINE="$(eval echo $line)";
```
into
```
LINE="$(eval echo -E $line)";
```
This forces the default behavior of echo:
```
-E     disable interpretation of backslash escapes (default)
```
This is similar to #6301 and #6314, and might explain other behaviors such as mentioned in #6662. It shouldn't change anything for Bash users, while making it work for Zsh users. And explicit is better :)

Note that a possible workaround on Zsh is to set the option BSD_ECHO, but this is cumbersome.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this was not responded back then.

I am closing as outdated, this generator was removed in conan 2, deprecated time ago in Conan 1.

Please open new tickets against new ``VirtualBuild/RunEnv`` generators in Conan 2 if necessary, thanks for your feedback
