### ISSUE TITLE
[bug] deps_cpp_info.get_name returns different results with `create` and `build`

### ISSUE THREAD

**Issue by mvoelkle-cern** [conan-io/conan#7854]
### Environment Details (include every applicable attribute)
  * Operating System+version: CentOS 7
  * Compiler+version: gcc 4.8.5
  * Conan version: 1.30.0
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)

The following conanfile.py

```
import conans

class Package(conans.ConanFile):
	name = 'package-name'
	version = '0.0.1'
	requires = 'gtest/1.10.0'
	generators = 'cmake_find_package'

	def build(self):
		print(self.deps_cpp_info['gtest'].get_name('cmake_find_package'))
```

prints different gtest package name depending on which conan commands I use:

`conan create .` prints `GTest`
`conan install . && conan build .` prints `gtest`

I expect the second command to print `GTest` like the first one.

**Comment by memsharded** [comment]
Thanks @mvoelkle-cern for reporting! Indeed a bug ( a missing thing for this new experimental feature)

I have submitted a fix in https://github.com/conan-io/conan/pull/7867 for next Conan 1.31 release.

**Comment by mvoelkle-cern** [comment]
Great! Thanks for the quick reply, quick fix and awesome product.
