### ISSUE TITLE
[feature] Update Search Help text

### ISSUE THREAD

**Issue by kpiascik** [conan-io/conan#7860]
Update the search help text as follows:
This line: https://github.com/conan-io/conan/blob/30ce7ddca81a76c9fd371c6016cfc06f42f078dd/conans/client/command.py#L1262
should be re-written as:
```
Searches package recipes and binaries in the local cache OR a remote.
Unless a remote is specified only the local cache is searched
```
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @kpiascik 

Wouldn't you like to submit a Pull Request yourself to contribute this? (do not capitalize the OR, not necessary, adding the explanation of the remote is good, thanks!)

**Comment by kpiascik** [comment]
@memsharded done
