### ISSUE TITLE
KEEP_RPATHS does not have any effect

### ISSUE THREAD

**Issue by Jochen0x90h** [conan-io/conan#7866]
(MacOS, Conan 1.30.0, CMake 3.18.4)

Hi!

I added KEEP_RPATHS to the options of conan_basic_setup but without success. I would expect that my executable references the libraries, for example boost, directly in their $HOME/.conan/data directories. But when I do

otool -L myExecutable

I still get something like

@rpath/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)

Therefore, KEEP_RPATHS does not seem to have any effect. Is this a bug in conan?

Jochen

**Comment by memsharded** [comment]
Closing this ticket as outdated, it was referred to the legacy ``cmake`` generator, removed in 2.0. Please update to Conan 2.0 and report if necessary, thanks!
