### ISSUE TITLE
[feature] 'conan download': preserve tarfiles in the cache ('conan upload' to use it)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#7869]
As of Conan v1.30, the command `conan download` does extract the packaged file (`conan_package.tgz`) into the Conan cache to make it ready to use. As a consequence, `conan upload` needs to package the files again before uploading to a remote repository.

This workflow is used as a workaround to _promote_ packages between different remote repositories, but it might modify the _package revision_ if these operations happen in different machines (see https://github.com/conan-io/conan/pull/7760#issuecomment-707041796 for information related to symlinks changes).

The proposal is to keep any file downloaded from a remote repository (whenever Conan downloads a package or install it from a remote) and use the same tarfile if available in the `conan upload` command. Some sentinel should be able to notice if the files in the cache have been modified and the tarfile needs to be invalidated/removed and generated again.

---

Details TBD (maybe 2.0).- Does `conan download` actually extract the files or only when they are going to be used (`conan install` using the package)? 

---

Side effect.- A workflow with `conan download + conan upload` will run much faster

**Comment by SSE4** [comment]
as a user, I don't expect commands like download/upload to extract/archive package contents. the name suggests package should be downloaded (as-is) or uploaded, not extracted.

**Comment by memsharded** [comment]
> as a user, I don't expect commands like download/upload to extract/archive package contents. the name suggests package should be downloaded (as-is) or uploaded, not extracted.

The upload will not extract, but it will need to zip if the package was locally created and has not been zipped yet. 

The download do extract files, because the cache so far didn't define a state that could have a package only downloaded but not usable. I think this cannot be changed now, (not extracting), as it would be breaking, but it would be good to know if we would like this behavior or not in the future.

**Comment by SSE4** [comment]
but we can change for 2.0, right?
if so I would expect `upload` to fail if the package wasn't zipped yet, and new command (don't we already have one like `export_pkg`?) will make an archive from the cached directory. so `upload` will require `export_pkg` first. and similarly you usually would run `import_pkg` after `download`, unless you just need an archive, not cached directory.

**Comment by memsharded** [comment]
> if so I would expect upload to fail if the package wasn't zipped yet, and new command (don't we already have one like export_pkg?) will make an archive from the cached directory. so upload will require export_pkg first. 

I don't think so. The zipping is an internal storage mechanism of Conan, to save space and transfers. The user shouldn't need to be aware of this detail, much less to issue a command to do it. The flow of creating a package should still be ``conan create`` + ``conan upload``, no need to add an intermediate step there that has no value for the user.

**Comment by SSE4** [comment]
I understand that zipping is an internal mechanism, but unzipping and re-package may lead to data loss, as we already know from #7760 - as certain OS or FS may not be able to fully represent packaged information appropriately. and this is also a waste of space and time to unzip data which might not be needed.
also, if I want to get the same .tgz files as conan stores - e.g. to implement my web cache / proxy / mirror / CDN or whatever else, how do I get them if conan unconditionally unzips?

**Comment by memsharded** [comment]
The proposed feature is about this. If the downloaded .tgz is not removed, then no problem, it can be uploaded without any re-zipping. If the ``conan download`` unzips it too or not is not really related, it doesn't matter, as long as the .tgz is not removed, it would be reuse in the upload.

**Comment by memsharded** [comment]
This has been implemented by https://github.com/conan-io/conan/pull/7938 and https://github.com/conan-io/conan/pull/7886, will be released in Conan 1.31
