### ISSUE TITLE
[feature] Identify configuration in remote requests when querying for a packageID

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#7870]
When Conan checks if a package for a given configuration is available in a remote, it sends just the _package ID_. It would be very useful to send the information used to compute that hash:
 * We can send _all_ the configuration: _package ID_ computation is reproducible (needed? desired?)
 * We can send only the information taken into account to compute the _package ID_ (~`conaninfo.txt`)

**Comment by jgsogo** [comment]
I've been having a look at it and it can be very challenging to pass the information about the configuration to the place where the calls to the remote are being done. I would say we need first to store the actual configuration for a package (settings, options, requirements,...) in the `node` object to have it available here https://github.com/conan-io/conan/blob/7f03c1d340eedcf9772722361a42dfb4ba2fc81e/conans/client/graph/graph_binaries.py#L100

Then we can deal with whatever is needed on the RemoteManager side.

**Comment by memsharded** [comment]
> I've been having a look at it and it can be very challenging to pass the information about the configuration to the place where the calls to the remote are being done. I would say we need first to store the actual configuration for a package (settings, options, requirements,...) in the node object to have it available here

That would be accessible in ``node.conanfile.info`` object at that point.
