### ISSUE TITLE
[bug] License files are not copied into the same directory hierarchy when using conanfile.txt over conanfile.py

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [conan-io/conan#7872]
### Environment Details
  * Operating System+version: macOS 10.15.6
  * Compiler+version: AppleClang 11.0.3.11030032
  * Conan version: 1.27.0
  * Python version: 3.8.5

### Steps to reproduce

As per https://docs.conan.io/en/latest/howtos/collect_licenses.html

Have this section in the `conanfile.txt`

```
[imports]
., license* -> ./licenses @ folder=True, ignore_case=True
```

and then running `conan install` will produce a hierarchy with the following contents in the build directory:

```
$ tree licenses                     
licenses
├── boost
│   └── licenses
│       └── LICENSE_1_0.txt
└── qt
    └── licenses
        └── LICENSE.LGPLv3
```

whereas if having `conanfile.py` with 

```
self.copy("license*", dst="licenses", folder=True, ignore_case=True)
```

and then running `conan install` will produce a hierarchy with the following contents in the build directory:

```
$ tree licenses    
licenses
├── boost
│   └── LICENSE_1_0.txt
├── qt
│   └── LICENSE.LGPLv3
```

Is this a bug or should one use another notation to use with `conanfile.txt` to get the license files under the package name directory directly (without having the `licenses` subdirectory)?

It's not critical, but it would be great to have the same directory hierarchy for both conan file types.

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, which dropped the `imports` syntax. If custom behaviour is required, a conanfile python recipe is the recommended go-to

This would probably be a breaking change in Conan 1 and we're not considering any more changes to that version
