### ISSUE TITLE
[Feedback] Conan is using old string formatting style

### ISSUE THREAD

**Issue by itai-huddly** [conan-io/conan#7873]
Currently enjoying the new conan course on JFrog Academy, so far I'm very happy with the content and the exercises.

One thing I've noticed is that some of the Python code generated by conan is using an older Python style for formatting strings.

So instead of 
`self.run(".{}example".format(os.sep))`

an older style is used:
`self.run(".%sexample" % os.sep)`

I would suggest updating the format to the newer style.

**Comment by memsharded** [comment]
Lets see what is the minimum python version supported by Conan 2.0, and from there we will chose between .format() and fstrings

**Comment by itai-huddly** [comment]
I see that currently Conan is supporting Python 3.5, correct? f-strings are supported starting at 3.6, so that would be a good starting point for Conan 2.0. I don't know what are the relevant features that were introduced post 3.6.

**Comment by memsharded** [comment]
Yeah, I would love to, but main problem is that some of our industry users might be stuck at older Python 3.5. These decisions are basically based on the userbase, not technology. We will probably ask for feedback about this (to the Tribe 2.0, to be launched soon).

**Comment by memsharded** [comment]
We have already started to use format() or f-strings. There might be old % in some places, but those will be gradually replaced when we work on that code. I am closing this as done.
