### ISSUE TITLE
[question] How to add dynamically option to recipe

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7874]
Hello,

In https://github.com/conan-io/conan-center-index/pull/2097, I'm attempting to add components support to boost, using extracted data from the boost sources (using yamls).

This means that the options of the boost recipe depend on the contents of a yml.
The yml depends on the version.

This recipe works fine when using as `conan create . boost/1.74.0@`,
but fails when used with conan-package-tools: https://github.com/conan-io/conan-center-index/issues/3159#issuecomment-707779710
c3i/conan-package-tools fails because it cannot find the yml:
`No such file or directory: '/home/conan/w/cci_PR-2097/recipes/boost/all/dependencies/dependencies-None.yml'`

So my question is how to dynamically add options to recipes (in this case extracted from the yml) instead of adding all possible options and removing the ones that are not supported.

**Comment by danimtb** [comment]
So, looking at the code, the only thing missing is the version of the dependency to be able to format the yaml file name?
https://github.com/conan-io/conan-center-index/pull/2097/files#diff-cc14160728d1ad321c1444ffad82615139181e681f4acb7dfd045a005cc8bd66R123

**Comment by madebr** [comment]
It's the version of the package itself that is being initialized too late. The options depend on the version.

I find my approach to adding dynamic options rather hacks (conan package tools don't support it). I was wondering whether there's a better way.

**Comment by danimtb** [comment]
Closing this issue as it seems to be working fine and we didn't found a better way of doing so. If conan-package-tools support is still required, please open a new issue there. Thanks!
