### ISSUE TITLE
[bug] CMAKE_SYSTEM_NAME is set to Darwin on iOS (watch and tv OS) 

### ISSUE THREAD

**Issue by a4z** [conan-io/conan#7875]
Coming from here, https://github.com/conan-io/conan/issues/4550 I can see that the change was not enough.

The `CMAKE_SYSTEM_NAME` is always set to Darwin, even for iOS (cross) builds, what is wrong

please check 
https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos
that clearly specifies what should be used

and for example the help to the cmake IOS variable
https://cmake.org/cmake/help/latest/variable/IOS.html
> Set to 1 when the target system (CMAKE_SYSTEM_NAME) is iOS

clearly, setting this to Darwin for iOS is not good.

### Environment Details (include every applicable attribute)
  * Operating System+version: OSX 10.15.7
  * Compiler+version: apple clang 12
  * Conan version: 1.30.1
  * Python version: 3.8.5

**Comment by jgsogo** [comment]
We modified it here (https://github.com/conan-io/conan/pull/7827) but didn't change the values you are referring to. I think @czoido can help here, he is having to Conan toolchains for iOS.

**Comment by a4z** [comment]
if you want to build for iOS there is also this PR
https://github.com/conan-io/conan-center-index/pull/1137

**Comment by czoido** [comment]
Yes, I think those should be changed to the corresponding platform since CMake 3.14+ has native support setting `CMAKE_SYSTEM_NAME` with `iOS`, `tvOS`, or `watchOS`.

**Comment by memsharded** [comment]
> Yes, I think those should be changed to the corresponding platform since CMake 3.14+ has native support setting CMAKE_SYSTEM_NAME with iOS, tvOS, or watchOS.

Please keep in mind that there are Conan users with versions lower than CMake 3.14, and this change shouldn't break them

**Comment by czoido** [comment]
Hi @a4z,

I have opened a PR to fix this issue assigned to Conan 1.31: https://github.com/conan-io/conan/pull/7924

**Comment by a4z** [comment]
Thanks, looks good!  
Of course, I do not know what happens for cmake > 3.14 users, if they try to use the cmake-ios toolchain, but I think I am not interested to find out, they shall update cmake in this case , what makes sense.
