### ISSUE TITLE
conan remove clarification

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#7879]
Quick question -- `conan remove -f [ref]` vs `conan remove -f -b -s [ref]` -- my understanding is the former will remove everything related to the ref, while `-f -b -s` version will only remove build and source files (preserving the package). Is that correct?

**Comment by AbrilRBS** [comment]
For anyone stumbling upon this old issue - The answer in Conan 1 was no, the first command would not have removed the source folders.
