### ISSUE TITLE
self.run() regression: mishandles output in 1.30.1 vs. 1.29.1

### ISSUE THREAD

**Issue by cszabo2** [conan-io/conan#7888]
I have a recipe which in the deploy() function has this code:

           class Buf:
                def __init__(self):
                    self.buf = []

                def write(self, data):
                    self.buf.append(data)

                def getData(self):
                    return "".join((str(x) for x in self.buf)).strip()

            myBuf = Buf()
            self.run('"python" -c "import sys;sys.stdout.write(\'\\n\'.join((sys.exec_prefix,'
                     'str(sys.version_info[0]), str(sys.version_info[1]))))"',
                     output = myBuf)
            data = myBuf.getData().replace("\r", "").split('\n')
            assert len(data) == 3
This code worked fine, in agreement with the published documentation in version 1.29.1 on Ubuntu 18.04.
In version 1.30.1 the run() command fails because with the error message: **"Buf has no attribute _stream"**.
The documentation: https://docs.conan.io/en/latest/reference/conanfile/other.html#output-and-running
Specifies that the only requirement for the value of the output argument is that it has a write method.
"You can pass **any stream that accepts a write method** like a six.StringIO()" 
As far as I know a stream is not required to have a private member named stream.

**Comment by memsharded** [comment]
Hi @cszabo2 


I am submitting a PR to explore a fix for this in https://github.com/conan-io/conan/pull/7893/files

Meanwhile, a quick question: why aren't you using directly a ``StringIO`` object to capture the output, and then you don't need to provide your own custom class and do custom processing?

**Comment by cszabo2** [comment]
@memsharded I do not have the six package installed and I do not want to bring in a dependency just to save me 10 lines of code.

**Comment by memsharded** [comment]
> @memsharded I do not have the six package installed and I do not want to bring in a dependency just to save me 10 lines of code.

Conan has a transitive dependency to ``six`` so six is already in your dependencies, no need to install anything else. In any case, if you are not using Py2 anymore, you can use Python3 StringIO, not ``six`` one. Have you tried that?

**Comment by cszabo2** [comment]
@memsharded I used subprocess.check_output() instead which returns directly the string without any effort. The only thing nice about self.run() here was that it printed the commandline in case of failure, so I put a log statement before the call so I always have the commandline. That is good enough for me.

**Comment by memsharded** [comment]
Thanks for reporting @cszabo2 great that you managed to workaround. 

I will still keep the PR #7893 to try to fix it, if not very urgent anymore, we might try for next Conan 1.31, instead of doing a patch 1.30.3. The thing is that it is a bit annoying, either the colors in the terminal are lost, or the tests are broken... that part of the code is a bit fragile, we need to improve it.

**Comment by memsharded** [comment]
Hi @cszabo2 

We are fixing it in #7905, if you managed to workaround the issue, then we will target next Conan 1.31 release.

Thanks for reporting!
