### ISSUE TITLE
[bug] Build requirements are not available when building software without conan but with cmake

### ISSUE THREAD

**Issue by a4z** [conan-io/conan#7892]
Given a project that has build requirements that are available via conan. 
When using conan to install all packages and build requirements, build requirements are not available for build that use cmake to build the project.
This is not good, as a user I want to be able to use the `usual cmake make/ninja commands`, since `conan build` is no replacement and IDEs will not care anyway. 

### Environment Details (include every applicable attribute)
  * Operating System+version: any
  * Compiler+version: any
  * Conan version: 1.30.1
  * Python version: 3.8.5 

### Steps to reproduce (Include if Applicable)

create a conanfile.py with build dependencies, or a profile that defines some
use conan install and this file to create a cmake project.

`conan install . --install-folder build/folder --profile:build default --profile:host projectA`

if the conan file has build dependencies that put something into PATH, when you do a 
`cmake --build build/folder`
The things that should be in the path are not there

-- Edit
it would be nice if there would be something so that cmake's `find_program` working so it finds tools packaged and installed via conan

**Comment by Johnnyxy** [comment]
Hi there,
the common approach is to execute ```conan install ...``` (optionally in the build folder if not specified via command line and then continue to work with common CMake commands there. As Conan consumer you normally do not use Conan "build" (but you could).

A common approch is like this (similar to what the Conan docs describe [here](https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#options)):
```
cd build
conan install .. --profile=some_profile -s compiler= ...
cmake -G "Unix Makefile" ..
cmake --build .
```

If you want to use CMake exclusivly and let CMake invoke Conan then you can use the cmake-conan-wrapper. You can find it [here](https://github.com/conan-io/cmake-conan). But I do **not** recommend it as this has several drawbacks.

**Comment by Johnnyxy** [comment]
You have to use virtual environments to get the desired environment modifications.
See [here](https://docs.conan.io/en/latest/mastering/virtualenv.html#virtual-environments).

Essentially you are
- installing dependencies with a Conan ```virtual environment generator```
- activating the environment (sets up PATH etc.)
- working with CMake / Make / ...
- deactivating the environment (optional)

**Comment by a4z** [comment]
Hi @Johnnyxy , your first comment just describes the steps that are done anyway, so this is not a solution

about the virtual env way, I will have to try it,  but  this is in best case a work around. 

Don't forget users working in IDEs. Telling them to open a terminal , sourcing something and then open the IDE from this terminal, and please do not close the terminal because ... ,  or writing wrapper IDE launcher scripts,  that is not how reality works for a lot of people/developer.

so **we need at least a way that cmake's find_program is able to find `build_requirements`** that are in the profile or in the conanfile.py/txt, 

but maybe even more, e.g, having a code generator that is written or makes use of java and that itself requires a java package (antlr anyone?;-) ...

**Comment by Johnnyxy** [comment]
Yes, I agree that "virtual environments" is not a convenient way to use with IDEs.

**Comment by a4z** [comment]
it turns out it is also a problem is you have 2 profiles and the build profile is not the host profiles

say you use cmake as a build dependency. It will create a LD_LIBRARY path entry to the openssl library to the build version of openssl, but if you build for a different OS , like Android or iOS,  I could imagine that such a `DYLD_LIBRARY_PATH` / `LD_LIBRARY_PATH` brings you in troubles. 

So the topic seems to be complex .....

**Comment by Johnnyxy** [comment]
The build profile should define PATHs and so on as this relates to your building system (running Conan/CMake/GCC/Make/MSVC/...). Thus every dependency and its paths you need on the building system have to be set there.

Setting PATH from a host profile does not make sense as the host settings are related to the binaries you are going to build.
At the moment I cannot imagine a scenario where the host profile should set environment variables. But hey, it's Friday, isn't it. :).

Anyway back to the original issue: In the docs I cannot find a generator that does set environment variables except those virtual environment generators. And indeed those are quite inconvenient to use with an IDE.

**Comment by a4z** [comment]
I appreciate you will to help , @Johnnyxy , but you are actually not on the topic, 
And I think you haven't done much cross compiling with 2 profiles, so yo might not understand the problem fully.

I am talking about that the virtualenv set `DYLD_LIBRARY_PATH / LD_LIBRARY_PATH` for build requirements of build profiles, that are most likely x86_64, and your host build, what might be armv8, will also be polluted by this setting. And this is a problem for virtualenv generator for cross compiling

**Comment by a4z** [comment]
it seems I am not the first person having that problem, and there are already people working on solutions
see: https://github.com/conan-io/conan/pull/7324

**Comment by jgsogo** [comment]
HI, @a4z 

Yes, indeed this is a complex problem, and we need to keep in mind the general cross-compiling scenario. I think that any approach needs the environment to be populated with the proper values at the proper time. Even `find_program` needs the executable in the environment, or passing more values in PATH/HINTS (Conan is not modifying the build-system scripts, so the environment looks like the only way to go). 

From the command line, the easiest solution is to use a virtualenv generator, activate it and run the rest of the commands; but from an IDE perspective this is quite inconvenient. The alternative we would love to provide (and IMHO probably the only one) is to build plugins that can trigger some Conan commands at certain points and provide information to other IDE actions: right now you can find a plugin for Visual Studio and another one for CLion, but they need more work to provide all required functionality... and we'd need plugins for other IDE's like VSCode, Android Studio,...

I would love to hear other alternatives closer to the Conan client (it'd be easier for us to maintain/evolve them) that could workaround this IDE problem. Thanks!

**Comment by a4z** [comment]
I think the new `generate` method to make toolchain files can solve that problem, first tests look good
some packages might need to export some environment variables so that can be written into the toolchain file, but thats' fine

so I close that issue, since I think that is solved now. In case of problems I might reopen, or create a new one
