### ISSUE TITLE
[bug] conan install pkgname/version not working when omitting user and channel

### ISSUE THREAD

**Issue by mjb6** [conan-io/conan#7897]
### Environment Details
  * Operating System+version: Ubuntu 18
  * Conan version: 1.30.1
  * Python version: 3.7

### Steps to reproduce
- create a conanfile.py for my-app in version 1.0.0
- `conan create .`  (no user & channel)
- `conan install my-app/1.0.0 -g deploy`

#### expected behavior
- package content deployed

#### observed
- conan interprets my-app/1.0.0 as folder where it can find the conanfile.txt:
 `ERROR: Conanfile not found at /my/workspace/my-app/1.0.0`

#### Hint:
When creating a package with `conan create . foo/bar`, I can afterwards use the conan install (as described in the docs). The error only appears when omitting user&channel:
```
conan install my-app/1.0.0@foo/bar -g deploy
Configuration:
[settings]
..
Generator deploy created deploy_manifest.txt
Generator txt created conanbuildinfo.txt
```

I just found it by accident. For me personally this is not an issue, but it contradicts the docs, so I wanted to report it 👍

**Comment by memsharded** [comment]
Hi @mjb6 

Could you please point where in the docs you found it? The correct syntax is:

```bash
$ conan install my-app/1.0.0@ -g deploy
```

The @ at the end is necessary at the moment to differentiate a package-reference from a local path. Please try that, and if you tell me from the docs, we will fix the docs (transferring the issue to the docs repo).

**Comment by mjb6** [comment]
Hi @memsharded 
thanks for the fast feedback! 
Great, this helped a lot. With trailing @ it worked.

In the docs for [conan install](https://docs.conan.io/en/latest/reference/commands/consumer/install.html) I only found an example for a package with user and channel: `$ conan install opencv/4.1.1@conan/stable`  and no example for a package without user and channel. So the docs are not wrong, but maybe this information is missing

**Comment by memsharded** [comment]
I have done a quick grep in the docs sources, found at least a couple of examples with the right syntax, and none incorrect. 

I haven't found a very evident place to clarify this, but as in any case, we are already working on the new CLI for Conan 2.0, and we will make this way more evident and explicit, hopefully it will not be a problem with the right UI/UX (better than in the docs).

I think this can be closed now, but don't hesitate to create new issues for any further question. Thanks!
