### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#790]
I'm not sure anything can be done about this, but it would be interesting to know the thoughts of others. Right now I'm putting together a nontrivial package where the build for windows vs linux is different. The package is big so it takes a while to build and upload. First I built the package on windows and took my best guess for the linux script. But when I got to linux there were issues and I needed to update the conan file. Then I needed to rebuild my windows package with the updated conan file and upload that again.

I could imagine if I was adding additional platforms this issue compounds. Is there a better way to handle this or is this just the reality?

**Comment by memsharded** [comment]
It is possible to upload binaries from different platforms, or even in the same platform, without regenerating the binaries for other platforms.

It is true, that the "outdated" field will be true for those binaries which recipe has been changed, and they haven't been recompiled. But if you know what you are doing, typically if...else for different OS, it is not a big issue.

In practice, I think that it is very usual to use CI, just push the recipe, and CI will generate the packages for different platforms. This is both the approach we use to generate packages we contribute for conan.io (with travis and appveyor, check e.g.: https://github.com/memsharded/conan-zmq/tree/4.1.5, with the badges for travis and appveyor), but it is also the main use case in companies using conan, as generating the binaries in developer machines is not the best thing.

**Comment by rconde01** [comment]
I've noticed that if you:

- conan install -r myremote pkg/version@user/channel --build=missing
- conan upload -r myremote pkg/version@user/channel --all

the conan_export.tgz get's re-uploaded even though nothing has changed. Is there a reason for that?

**Comment by rconde01** [comment]
On a somewhat related topic, when doing a package build...why isn't the build and/or source directory deleted after it completes? Is there a cleanup command to do so? If not, I think it would be nice to have and will add another issue.

**Comment by memsharded** [comment]
That could be a bug, it shouldnt. Do you want to open an specific issue to get it checked, please? Thanks

**Comment by rconde01** [comment]
Sorry - which issue were you responding too?

**Comment by memsharded** [comment]
Yes, there are reasons:
- It happens sometimes that when developing a package, a ``package()`` or ``package_info()`` mistakes are done. You don't want to rebuild to fix and try it, so you can do it with helpers command as ``conan package``.
- Or you are building different configurations, you don't want to run a slow git clone or download of source.

There are options to ``conan remove``, like ``-s`` and ``-b`` to remove source and build folders.

**Comment by lasote** [comment]
@rconde01 You could make two separate recipes for Linux and Windows and another one "virtual" just requiring the right one depending on the settings in the `configure()` method (few lines). This way if you change the **Linux** recipe you don't have to recompile the windows ones.
