### ISSUE TITLE
Errant, uncontrollable output

### ISSUE THREAD

**Issue by dsoprea** [conan-io/conan#7906]
Occasionally, we get this across our build environments when the version of Conan changes:

```
WARN: Migration: This conan installation doesn't have settings yet
WARN: Nothing to migrate here, settings will be generated automatically
<...>
```

This is printed via `warn()`:

https://github.com/conan-io/conan/blob/f5cfc8caa7c880c48f86fb72f5364c02c325ed1d/conans/client/output.py#L137

It prints just when I'm instantiating an API object because it's wired via the constructor:

```
v1, _, _ = conans.client.conan_api.ConanAPIV1.factory()`
```

There appears to be no way to suppress it. It's inconvenient when we're calling this in contexts where we're expecting to produce machine-readable output but are, instead, getting intermixed garbage verbosity.

Am I missing some way to quiet this?

**Comment by dsoprea** [comment]
Thank you.

**Comment by memsharded** [comment]
> v1, _, _ = conans.client.conan_api.ConanAPIV1.factory()

Yeah, it is unlikely that we can change this now without breaking, so if you are using the (internal, undocumented, you shouldn't be using it 😄  ) python api, then probably you can just capture the warning directly? With python everything is relatively easy to hack, so something like:

```python
stdout_ = sys.stdout #Keep track of the previous value.
stream = StringIO()
sys.stdout = stream
v1, _, _ = conans.client.conan_api.ConanAPIV1.factory()
sys.stdout = stdout_ # restore the previous stdout.
```

**Comment by dsoprea** [comment]
That's what I did (wrapped in a try-finally).

**Comment by czoido** [comment]
Hi @dsoprea,
As it seems that there's a feasible workaround I'll close the issue, please feel free to reopen if you have any more comments.

**Comment by dsoprea** [comment]
The very nature of a workaround validates this issue's existence as a bug. It'll continue being a bug until that rewrite is finished. I'd encourage you to keep this open until it *actually* no longer exists.

**Comment by memsharded** [comment]
> The very nature of a workaround validates this issue's existence as a bug. It'll continue being a bug until that rewrite is finished. I'd encourage you to keep this open until it actually no longer exists.

It is a workaround for your use case, not a workaround around a Conan bug. The python API is internal, undocumented and unsupported. We try as much as possible not to break it if it is not necessary. But we cannot provide a "fix", lets say something  like this:

```python
v1, _, _ = conans.client.conan_api.ConanAPIV1.factory(quiet=True)
```

for something that is not documented, because users aren't allowed to call that method themselves. If there is another problem/issue/bug, that can be reproduced explicitly in terms of the Conan command line, then it would be great to have the issue reformulated in those terms. Can you please provide details for it so we can have a look? Many thanks!

**Comment by dsoprea** [comment]
Fair point, and I expected that might be the case when I used it.

I needed to extract the package name from a conanfile via an automated process in order to do packaging and uploads for specific references and I wouldn't have the package names, only the paths. Is there a CLI way to extract info from a conanfile?
