### ISSUE TITLE
How do export my package to the local and remote repo

### ISSUE THREAD

**Issue by kobi-ca** [conan-io/conan#7909]
hello,

I have a local git repo that is using gtest w/ conan. It has conanfile.py to pull gtest deps.
Now, I'd like to export my package both locally and on my artifactory server.
First, for local export to my ~/.  conan cache.
How exactly do I do this (link to docs should be fine as well).
This is a header only (so in cmake it is lib INTERFACE), but has gtest and an example app that I dont need to export.
I tried running conan install from the cmake build dir
```
conan install name@channel --build=prj-name
```
and it complains that there are no CMakeLists.txt.
do we need any?
How about
```
    exports_sources = "src/*"
```
do I need to add CMakeLists.txt ?

Same question for exporting/uploading to artifactory.

thanks
Kobi

**Comment by memsharded** [comment]
Hi @kobi-ca 

Sorry for the delay in responding.

There is a flow that I would suggest to quickly test things:

```bash
$ conan new hello/0.1 -s -t  # creates a hello world recipe and code
$ conan create . user/channel # locally create the package in the local cache
$ conan upload hello/0.1@user/channel --all -r=myremote  # upload to my server
```

These steps should work and you will end with your package in the server. You can inspect your local cache folders in ``<userhome>/.conan/data`` and see the build folders, the package folders, etc.

Also, in case you haven't done it yet, maybe you might be interested in doing this hands-on free training: https://academy.jfrog.com/path/conan


From the previous example, you can start adapting the recipe: add a ``build_requires = "gtest/..."`` in the recipe, try the ``conan create``. Now add some code that actually use gtest, etc.

please let me know if this helps.

**Comment by kobi-ca** [comment]
thanks @memsharded . I did take some training in the academy and indeed it helped. I managed to create, upload to a local artifactory. all working well. thanks!

**Comment by memsharded** [comment]
Great, happy that it helped!
