### ISSUE TITLE
Is there a way to import gtest package directly from github using a SHA1

### ISSUE THREAD

**Issue by kobi-ca** [conan-io/conan#7914]
Hi,

Might be a long shot but what if I need gtest > 1.10.0 ? Is there a way to import directly from a git remote and specifying SHA1?

thanks,
Kobi

**Comment by memsharded** [comment]
Hi @kobi-ca 

No, I am afraid it is not possible. There is metadata, besides the recipe before export time that is needed to consume a package. As you can guess, just the user/channel part is defined at package creation time, and it is impossible to map that to a git repo. Not to say versions, and how package binaries are resolved, etc. So Conan works in this regard like Maven, it requires a server that hosts the created package.

If you need a more modern gtest, you can:

- Create the package yourself and host it in your own Artifactory server (remember the CE is completely free)
- Contribute the version that you need to conan-center-index repo, so it is available in ConanCenter when it is merged.

Please let me know if this clarifies your question.

**Comment by kobi-ca** [comment]
Hi @memsharded . thanks for your reply. This is what I thought. it makes sense.
thanks a lot!
Kobi
