### ISSUE TITLE
[feature] Adding Group ID and distribution policy to each conan package

### ISSUE THREAD

**Issue by kohei306** [conan-io/conan#7918]
Let's say we have a central server such as Artifactory to upload conan packages from different development teams. Among the uploaded packages, there are some packages that are meant for only internal usages of the specific team A and A team does not want external teams to depend on them (because they are not designed to be used for external use cases etc). However, in current state, other teams can accidentally use those private packages of team A. In order to prevent it, I would like to have "group id" in each package and specify some kind of "distribution policy" in there we can specify the group id of expected consumers. From downstream package, it gets error if the distribution policy of any required package disagrees with the down steam package's group id. The distribution policy can be "any" by default to be consumed by all downsteam packages (current behavior).

- [o] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @rjhcnf 

There are a couple of approaches you can use for this.

All packages can (and for your own use, should) define the "user/channel" part. So when a team A creates a package, they will do:

```bash
conan create conanfile.py team_a/stable
conan upload pkg/version@team_a/stable -r=myremote --all
```

In Artifactory, the "user" part is the first part of the path, different security policies could be defined for them.

Also, if you have very strong separation of packages, then the recommended way is to use different repositories. You can create as many as you want in Artifactory, and different repositories can have different users, with different permissions. This will strongly guarantee not only at the user level, but also at the CI, that packages do not accidentally depend on other packages you don't want to depend on. 

Probably you want a mixture of both, the second approach is a good practice anyway, and the first approach can bring more explicit evidence also at the recipe and user level.

**Comment by kohei306** [comment]
Hi @memsharded, Thanks for the suggestions. I will look into it.

**Comment by memsharded** [comment]
Great @rjhcnf 

I will close this at the moment, don't hesitate to comment or to submit a new issue with any further question.
