### ISSUE TITLE
[bug] ERROR: Generator cmake_find_package(file:None) failed

### ISSUE THREAD

**Issue by maingig** [conan-io/conan#7921]
vsomeip/3.1.16.1@yoda/testing: ERROR: Generator cmake_find_package(file:None) failed
'list' object has no attribute 'replace'
ERROR: 'list' object has no attribute 'replace'

    def requirements(self):
        self.requires("boost/1.71.0@%s/%s" % (self.user, self.channel))
        if self.settings.os != "Android":
            self.requires("gtest/[>=1.8]@%s/%s" % (self.user, self.channel))

If I comment out the boost line, it proceeds up until the CMake find_package(boost) call.
If I replace the boost line with some other package, again it proceeds up until the find_package call.
This works with other profiles.  I'm not sure how to debug this one.
I get the same error with the other cmake generators.

[conanfile.txt](https://github.com/conan-io/conan/files/5419212/conanfile.txt)

### Environment Details (include every applicable attribute)
  * Ubuntu 16.04:
  * Compiler gcc 5.4:
  * Conan version: 1.25.2:
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)
[nio-linux-x86_64-x-qnx-ntoaarch64-release.txt](https://github.com/conan-io/conan/files/5419217/nio-linux-x86_64-x-qnx-ntoaarch64-release.txt)

I can look into reducing this example but I'm not sure what to look for.

### Logs (Executed commands with output) (Include/Attach if Applicable)

`
conan create /home/fmalouf/Dev/gitlab/nio-conan/build/sources/conan-vsomeip.git yoda/testing --test-folder=None --build=missing --build=outdated -pr nio-linux-x86_64-x-qnx-ntoaarch64-release -o shared=True -e BASE_PATH="/tmp" -e ENABLE_SIGNAL_HANDLING=1 -e DIAGNOSIS_ADDRESS="0x10" -e UNICAST_ADDRESS="127.0.0.1"
Exporting package recipe
vsomeip/3.1.16.1@yoda/testing exports: Copied 1 file: .gitignore
vsomeip/3.1.16.1@yoda/testing exports: Copied 1 '.sh' file: conan-create.sh
vsomeip/3.1.16.1@yoda/testing exports: Copied 2 '.py' files: conanfile.py, conanfile.py
vsomeip/3.1.16.1@yoda/testing exports: Copied 1 '.md' file: README.md
vsomeip/3.1.16.1@yoda/testing exports: Copied 1 '.cpp' file: example.cpp
vsomeip/3.1.16.1@yoda/testing exports: Copied 1 '.txt' file: CMakeLists.txt
vsomeip/3.1.16.1@yoda/testing: The stored package has not changed
vsomeip/3.1.16.1@yoda/testing: Using the exported files summary hash as the recipe revision: 622ba055abb8cc7cd364cdb4b8b4c0b2 
vsomeip/3.1.16.1@yoda/testing: Exported revision: 622ba055abb8cc7cd364cdb4b8b4c0b2
Configuration:
[settings]
arch=armv8
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=5.4
cppstd=14
os=QNX
os.version=7.0
os_build=Linux
profile_name=nio-linux-x86_64-x-qnx-ntoaarch64-release
[options]
shared=True
[build_requires]
[env]
AR=ntoaarch64-ar
AS=ntoaarch64-as
BASE_PATH=/tmp
CC=ntoaarch64-gcc
CHOST=ntoaarch64
CONAN_CMAKE_FIND_ROOT_PATH=/opt/toolchains/qnx700/host/linux/x86_64
CXX=ntoaarch64-g++
CXXFLAGS=-I"/opt/toolchains/qnx700/host/linux/x86_64/usr/include"
DIAGNOSIS_ADDRESS=0x10
ENABLE_SIGNAL_HANDLING=1
LD=ntoaarch64-ld
PATH=[/opt/toolchains/qnx700/host/linux/x86_64/usr/bin]
QNX_HOST=/opt/toolchains/qnx700/host/linux/x86_64
QNX_TARGET=/opt/toolchains/qnx700/target/qnx7
RANLIB=ntoaarch64-ranlib
STRIP=ntoaarch64-strip
UNICAST_ADDRESS=127.0.0.1
bzip2/1.0.8@yoda/testing: Package is up to date
gtest/1.8.1@yoda/testing: Package is up to date
zlib/1.2.11@yoda/testing: Package is up to date
boost/1.71.0@yoda/testing: Package is up to date
vsomeip/3.1.16.1@yoda/testing: WARN: Package is corrupted, removing folder: /home/fmalouf/.conan/data/vsomeip/3.1.16.1/yoda/testing/package/63266cf1d378289709a2305e5308ce62d0642e85
Version ranges solved
    Version range '>=1.8' required by 'vsomeip/3.1.16.1@yoda/testing' resolved to 'gtest/1.8.1@yoda/testing' in local cache

Installing package: vsomeip/3.1.16.1@yoda/testing
Requirements
    boost/1.71.0@yoda/testing from local cache - Cache
    bzip2/1.0.8@yoda/testing from local cache - Cache
    gtest/1.8.1@yoda/testing from 'nio-skywalker' - Cache
    vsomeip/3.1.16.1@yoda/testing from local cache - Cache
    zlib/1.2.11@yoda/testing from local cache - Cache
Packages
    boost/1.71.0@yoda/testing:ec0f09e6b22bca09226b94e225b753e88a869995 - Cache
    bzip2/1.0.8@yoda/testing:87afd63b371643cd409045ab5fcc6d750e53b33d - Cache
    gtest/1.8.1@yoda/testing:4b3a864f128a78c34c55d8628c60ec3a3cfbe0e8 - Cache
    vsomeip/3.1.16.1@yoda/testing:63266cf1d378289709a2305e5308ce62d0642e85 - Build
    zlib/1.2.11@yoda/testing:5f8c20a3a585f712dee02657340900bd60f4c9f0 - Cache

Cross-build from 'Linux:x86_64' to 'QNX:armv8'
Installing (downloading, building) binaries...
bzip2/1.0.8@yoda/testing: Already installed!
gtest/1.8.1@yoda/testing: Already installed!
zlib/1.2.11@yoda/testing: Already installed!
boost/1.71.0@yoda/testing: Already installed!
boost/1.71.0@yoda/testing: LIBRARIES: ['boost_wave', 'boost_container', 'boost_contract', 'boost_exception', 'boost_graph', 'boost_iostreams', 'boost_log', 'boost_program_options', 'boost_random', 'boost_regex', 'boost_serialization', 'boost_wserialization', 'boost_timer', 'boost_thread', 'boost_chrono', 'boost_date_time', 'boost_atomic', 'boost_filesystem', 'boost_system', 'boost_type_erasure', 'boost_log_setup', 'boost_math_c99', 'boost_math_c99f', 'boost_math_c99l', 'boost_math_tr1', 'boost_math_tr1f', 'boost_math_tr1l', 'boost_stacktrace_basic', 'boost_stacktrace_noop', 'boost_unit_test_framework']
boost/1.71.0@yoda/testing: Package folder: /home/fmalouf/.conan/data/boost/1.71.0/yoda/testing/package/ec0f09e6b22bca09226b94e225b753e88a869995
vsomeip/3.1.16.1@yoda/testing: WARN: Build folder is dirty, removing it: /home/fmalouf/.conan/data/vsomeip/3.1.16.1/yoda/testing/build/63266cf1d378289709a2305e5308ce62d0642e85
vsomeip/3.1.16.1@yoda/testing: Copying sources to build folder
vsomeip/3.1.16.1@yoda/testing: Building your package in /home/fmalouf/.conan/data/vsomeip/3.1.16.1/yoda/testing/build/63266cf1d378289709a2305e5308ce62d0642e85
vsomeip/3.1.16.1@yoda/testing: ERROR: Generator cmake_find_package(file:None) failed
'list' object has no attribute 'replace'
ERROR: 'list' object has no attribute 'replace'
`

**Comment by memsharded** [comment]
Hi @maingig 

As a quick check, have you tried using the latest Conan 1.30 version? I recall some things might have been fixed.

Could you please try running again, but enabling first env-var ``CONAN_VERBOSE_TRACEBACK``, so we get some more detail (the traceback) of the error? Thanks!

**Comment by maingig** [comment]
```Traceback output:
`vsomeip/3.1.16.1@yoda/testing: ERROR: Traceback (most recent call last):
  File "/home/fmalouf/py37/lib/python3.7/site-packages/conans/client/generators/__init__.py", line 106, in write_generators
    content = generator.content
  File "/home/fmalouf/py37/lib/python3.7/site-packages/conans/client/generators/cmake_find_package.py", line 55, in content
    ret["Find%s.cmake" % depname] = self._find_for_dep(depname, cpp_info)
  File "/home/fmalouf/py37/lib/python3.7/site-packages/conans/client/generators/cmake_find_package.py", line 77, in _find_for_dep
    deps = DepsCppCmake(dep_cpp_info)
  File "/home/fmalouf/py37/lib/python3.7/site-packages/conans/client/generators/cmake.py", line 49, in __init__
    self.defines = join_defines(cpp_info.defines, "-D")
  File "/home/fmalouf/py37/lib/python3.7/site-packages/conans/client/generators/cmake.py", line 29, in join_defines
    for v in values)
  File "/home/fmalouf/py37/lib/python3.7/site-packages/conans/client/generators/cmake.py", line 29, in <genexpr>
    for v in values)
AttributeError: 'list' object has no attribute 'replace'
```

**Comment by memsharded** [comment]
Hi @maingig 

It seems for some reason, Conan is getting in the list of preprocessor definitions from the dependencies a list of lists, instead of a list values. It would be very useful to see the ``package_info()`` of your dependencies, there is one that might contain something unexpected. Maybe you can obtain the same error, installing that package (for that configuration) directly? Something like ``conan install boost/1.71@user/channel -g cmake_find_package``?

**Comment by maingig** [comment]
You are correct. It is this line in my boost conanfile.py
            self.cpp_info.defines.append(["__EXT_BSD", "__QNXNTO__", "_QNX_SOURCE"])
When I print cpp_info.defines, I get this:
['_GLIBCXX_USE_CXX11_ABI=1', ['__EXT_BSD', '__QNXNTO__', '_QNX_SOURCE']]

I should be using extend instead of append.
Sorry to bother you.  I'll make use of this tracing from now on.

**Comment by memsharded** [comment]
That is great!. Yes, you need to use ``defines.extend()`` instead, I guess everything will be fine then.

> Sorry to bother you. I'll make use of this tracing from now on.

No worries, happy to help!

I guess we can close this issue now. Thanks for reporting and following up.
