### ISSUE TITLE
[feature] new helper function tools.comment_lines_in_file

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#7926]
Similar to `tools.replace_in_file()`, it would be very handy to add a helper function that comment or delete lines from a file.

Something like:
```
def comment_lines_in_file(file_path, lines, comment_character, encoding=None)
```

or 
```
def remove_lines_from_file(file_path, lines, encoding=None)
```

**Comment by czoido** [comment]
Hi @boussaffawalid,
Thanks a lot for the suggestion. If you have functions that are useful for you in many recipes, maybe you could use [Conan python requires](https://docs.conan.io/en/latest/extending/python_requires.html#python-requires) to reuse that code in your recipes.

Create the python requires:

```python
from conans import ConanFile

def comment_lines_in_file():
    ...

def remove_lines_from_file():
    ...

class Pkg(ConanFile):
    pass
```
```
$ conan export . pyreq/0.1@user/channel
```

Use it in your recipes:

```python
from conans import ConanFile

class Pkg(ConanFile):
    python_requires = "pyreq/0.1@user/channel"
    def source(self):
        f = self.python_requires["pyreq"].module.comment_lines_in_file(....
```
Hope that helps

**Comment by memsharded** [comment]
Closing as inactive and not planned
