### ISSUE TITLE
[feature] Address repeatable code in recipes to handle fPIC

### ISSUE THREAD

**Issue by klimkin** [conan-io/conan#7931]
I see this boilerplate in almost all packages. Why not to incorporate the logic into the base class? Delete `fPIC` if option exists and:
* Windows OS
* `shared` option exists and set

~~~python
    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            del self.options.fPIC
~~~

Moved from https://github.com/conan-io/conan-center-index/issues/3297

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @klimkin,
Thanks for the feedback. I think that idea is something that we could consider for Conan 2.0 although right now would break the current behaviour.

**Comment by Croydon** [comment]
Why not leaving this issue open as a reminder to look into it?
