### ISSUE TITLE
[question] How to extend virtualenv-generator environment-variables from within a consumer

### ISSUE THREAD

**Issue by mhanitaw** [conan-io/conan#7933]
The provider recipe provides a virtualenv-generator with the needed environment variables. If the consumer recipe requires a package that has environment variables, how can the consumer append these variables to the provided activate.sh ?
- Should he first source activate.sh of the provider than run its own virtual-env generator to get his own environment variables from his dependencies or there is another way for this ?

**Comment by memsharded** [comment]
Hi @mhanitaw 

I am not sure what you mean. A ``virtualenv`` generator will contain variables with values composed for all transitive dependencies that are being installed, not just one package. It is not necessary to run the virtualenv of the dependency, when you do ``conan install <yourconanfile> -g virtualenv``, the virtualenv with variables definitions from the dependencies will be created.

Could you please clarify what you mean?
