### ISSUE TITLE
[question] how to iterate over conanfile.options

### ISSUE THREAD

**Issue by peter-moran** [conan-io/conan#7934]
I am working on a generator that will create a CMake file containing all of the conan option values. To do this, I need to iterate over the conanfile options and get their values.

However, when I do this it seems to iterate infinity.

```python
class CmakeConanOptions(Generator):
    def __init__(self, conanfile):
        self.conanfile = conanfile

    @property
    def filename(self):
        return "conan_options.cmake"

    @property
    def content(self):
        content = "if(NOT CONAN_EXPORTED)\n"

        for option in self.conanfile.options:
            option_name = str(option)
            content += f"set(CONAN_OPTION_{option_name} {self.conanfile.options[option_name]})\n"
        
        content += "endif()"
        return content
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by peter-moran** [comment]
After a bit of digging around in the source, it appears the following is best:

```python
class CmakeConanOptions(Generator):
    def __init__(self, conanfile):
        self.conanfile = conanfile

    @property
    def filename(self):
        return "conan_options.cmake"

    @property
    def content(self):
        content = ""
        for option_name, option_value in self.conanfile.options.values.as_list():
            content += f"set(CONAN_OPTION_{option_name} {option_value})\n"
        return content
```

**Comment by memsharded** [comment]
Hi @peter-moran 

Glad that you found a solution, it looks good.

The only problem is that it is using some internal implementation details, not documented, and as such they might change at some point and break your code. Not likely at all in Conan 1.X versions, but might happen in Conan 2.0. I would recommend opening a new ticket while migrating to Conan 2.0 to make a public interface to iterate the options.

Thanks for sharing your solution!
