### ISSUE TITLE
[suggestion] Keyword target_link_libraries signature for conan_target_link_libaries

### ISSUE THREAD

**Issue by izzyreal** [conan-io/conan#7939]
See https://github.com/conan-io/conan/blob/bd0da4de60b892eb1ea46a0809216a41db085c97/conans/client/generators/cmake_common.py#L668

The macro assumes plain signature is always desired. I would like an option to use keyword signatures, so I can mix usage of Conan's macro with [others that also use keyword signatures](https://github.com/juce-framework/JUCE/blob/06a6619cb87822e40753987a3ad10878b9b447f1/extras/Build/CMake/JUCEUtils.cmake).

Also see https://cmake.org/cmake/help/v3.0/policy/CMP0023.html

**Comment by memsharded** [comment]
Hi @izzyreal 

Not sure what is your use case, but in general, you probably want to start trying the ``cmake_find_package_multi`` generator, this is a more "modern" way to integrate with CMake, using ``find_package()`` calls. We are putting our efforts in this approach, and it will eventually become the only one (Conan 2.0).

**Comment by izzyreal** [comment]
Thanks @memsharded, I will read up on the `cmake_find_package_multi` generator.

For anyone who ran into a similar issue, I've closed the ticket because I found a workaround. I define the below in my consumer's `CMakeLists.txt` and use this macro instead of `conan_target_link_libraries`:
```
macro(conan_target_link_libraries_keyword target)
    if(CONAN_TARGETS)
        target_link_libraries(${target} PUBLIC ${CONAN_TARGETS})
    else()
        target_link_libraries(${target} PUBLIC ${CONAN_LIBS})
        foreach(_LIB ${CONAN_LIBS_RELEASE})
            target_link_libraries(${target} PUBLIC optimized ${_LIB})
        endforeach()
        foreach(_LIB ${CONAN_LIBS_DEBUG})
            target_link_libraries(${target} PUBLIC debug ${_LIB})
        endforeach()
    endif()
endmacro()
```
Not sure if it's doing exactly what I hope it's doing, but everything compiles. I've only tried it in workspace mode so far.
