### ISSUE TITLE
Settings vs. options (question)

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#794]
I'm a bit confused about settings vs. options. Looking at bigger packages on conan.io, I can see that a package corresponds to both settings and options. I found examples of "arch" being a setting and option as well in the docs. So what is the distinction between the two? How do I decide which is which for my project?

**Comment by memsharded** [comment]
The rationale is:

- Settings are mostly project-wide-specific, consumer-defined configuration. So you have a library that can be built in different OS and compilers. But you cannot "default" a setting. It will always be the user who defines: "I am in Windows, and I am working with VS14". Almost always you will use the same settings for the full project and dependencies to be ABI compatible (it is possible to mix in some cases, but not the usual). Architecture is a setting. 

- Options is something that can be defaulted by the package creator, like if a library is static or shared. Options are specific to each package, and each package creator can define their own options "header_only" for example. There is an option that is the most usual, and recommended name ``shared = True/False``

Settings should have a common syntax, which is defined in the ``settings.yml`` file, which should be common for teams of developers. It can be modified, but it is important that devs in same team use the same settings.yml

**Comment by sztomi** [comment]
Can I however set a limit for settings? For example, I have a C++ project that requires at least VS2015 to build on windows. If not specified, cmake will pick VS2013 (which is also installed), but that's wrong. It would be also wrong if the user explicitly picked it. What is the intended way of handling such situations?

**Comment by memsharded** [comment]
Yes, that can be done in different ways:

- You can restrict settings values in the settings declaration of your package recipe. Not very straightforward, but can be done. Basically define a stripped version of settings.yml in the settings field of the recipe

- You can just check the value in the ``configure()`` method, and raise an Exception:

```python
def configure(self):
     if self.settings.compiler == "Visual Studio" and self.settings.compiler.version != "14":
         raise Exception("This package will not compile for !=14")
```

Note that all settings are **strings** so ranges check could be defined as: ``str(self.setttings.compiler.version) not in ["14", "15", "16"]``

**Comment by sztomi** [comment]
Thanks, I didn't know about the `configure` method. Can you point me to a package that contains an example of restricting the settings values?

**Comment by memsharded** [comment]
Check this: https://www.conan.io/source/freetype/2.6.3/lasote/stable

Note also the removal of ``settings.compiler.libcxx``, because it is a C library, so libcxx doesn't affect.

**Comment by sztomi** [comment]
Sorry, I mean the first variant you mentioned:

> define a stripped version of settings.yml in the settings field of the recipe

**Comment by memsharded** [comment]
Sure, there is an example in the docs: http://docs.conan.io/en/latest/reference/conanfile.html#settings

**Comment by sztomi** [comment]
Thank you, I missed that part somehow.
