### ISSUE TITLE
self-dependency of package creates error message that is not an error

### ISSUE THREAD

**Issue by alexanderLinear** [conan-io/conan#7940]
i got hands on a project with a conan invocation the created an error message that is not treated as an error.
i feel like its raised by a glitch from its originator adding the package on the target and on the input side (=a dependency).

on the first run the package is indeed not in any repository so the package is reported as an "ERROR" because its missing as a source.
but... then this supposed ERROR is rather treated as a lower level severity (e.g. an info or a warning) that can be ignored because the package is the build target as well.

can you please avoid indicating ERROR for input items that are optional? (in this case because its also the build target.)
for the given case just **informational** that the package was missing from the package source - as its an **optional** input.

**Comment by memsharded** [comment]
Error messages should be reserved for really bad things, that are very broken. If the thing is informational, indeed shouldn't be an error, but a warning or info.

But is this something that was defined in a recipe of a project? In that case we don't have control over that, and you should probably be reporting to the creator of the recipe. If this is something in the Conan code, please let us know how to reproduce it, so we could improve it. Do you have more details how to get to this ERROR message?

**Comment by alexanderLinear** [comment]
simple explanation - someone probably made it to put the output package name on the list of input dependencies as well.
(it went a one-time item because after the first successful run the result is present before the the next run - at least when calling it repeatedly at development time.)

**Comment by memsharded** [comment]
@alexanderLinear This is why I am asking. I have just tried (just in case) to do that:

```bash
$ conan new hello/0.1 -s
# edit conanfile.py and add ``requires = "hello/0.1"``
$ conan create .
...
ERROR: Loop detected in context host: 'hello/0.1' requires 'hello/0.1' which is an ancestor too
```

There is some protection in place to avoid dependencies cycles, so this shouldn't be just an error message, it should be a hard error, that would require fixing the conanfile.py recipe to proceed, otherwise the error will remain.

**Comment by alexanderLinear** [comment]
i digged it a bit deeper on my side - after some rather different failure case (broken codes in a c file rather than missing input for conan) i finally found that the execution conditions were stacking multiple conan calls into a bash script. the return value might have been determined only by the last command whilst all previous ones were simply ignored. with a "set -e" an abort on the first failure could be enforced.

sorry that the reason was in a quite different area - but definitely thanks on all your responses. i feel like this topic here can be closed now. (hitting button)

**Comment by memsharded** [comment]
No problem, thanks for the feedback and following up!
