### ISSUE TITLE
[feature] Debug prints for CMake commands

### ISSUE THREAD

**Issue by RonaldOlsthoorn** [conan-io/conan#7943]
I'm reading, experimenting and slowly developing a conan build that heavily uses CMake. The CMake handle that conan provides is very helpful. However to make conan truly dance with cmake it would be helpful if there was an option in every python method that runs a cmake command (_cmake.configure(), cmake.build(), cmake.install()_, etc) to carry an option to print out the exact cmake command, just for debugging purposes. 

Right now, the CMake object only does that whenever a non- 0 code is returned (aka, something went wrong). Since cmake itself is unnecessarily complicated, this would help me develop much faster. So, to be concrete, I suggest extending the method signature of:

```
CMake.configure()
CMake.build()
CMake.install()
CMake.test()
```

With an optional argument _debug_, defaulted to False, which, when True would print the _cd + cmake_ command generated by the cmake object.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @RonaldOlsthoorn 

You are probably looking for the ``[log]`` ``run_to_output`` variable in https://docs.conan.io/en/latest/reference/config_files/conan.conf.html **conan.conf** file. That would be printing to output every command that is executed in the build. Can you please try it? Editing **conan.conf** manually. (conan.conf file can be shared and installed automatically with ``conan config install`` command)

Please let us know if this helps.

**Comment by RonaldOlsthoorn** [comment]
Thanks for the quick response. Indeed the `run_to_output` setting works. Found this variable right after going in the source files for developing this feature. Think this is sufficient for debugging purposes. But it would be handy if a hint was given in the docs of the CMake object or in the CMake generate section.
