### ISSUE TITLE
[question] "import module" in conanfile.py of upstream package cascades as requirement to down stream package. 

### ISSUE THREAD

**Issue by kohei306** [conan-io/conan#7955]
Let's say we have an upstream package A. The conanfile.py of the package A specifies
`import some_module`.
Now if downstream package B requires package A, when we execute conan commands (like conan install) with conanfile.py of package B to load the recipe of its upstream packages recursively to check all dependencies, is the _some_module_ need to be installed in the environment?
 

- [o] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @rjhcnf 

Yes, if you are doing a bare `` import some_module`` that assumes that you have that file installed in the system. If what you want to do is to reuse python code from some recipes in other recipes, then this is the ``python_requires`` feature, have a look to: https://docs.conan.io/en/latest/extending/python_requires.html. Is this what you are looking for?

**Comment by kohei306** [comment]
Hi memsharded,

Yes, in my case the some_module is not a conan package but normal python module, in this case is there any way around it so that the environment does not need to install it for the downstream consumer?

**Comment by memsharded** [comment]
Hi @rjhcnf 

Well, there is only 1 running python environment. If you are able to ``import some_module`` in one recipe, it is installed in your python environment, and all recipes downstream will be able to ``import some_module`` if they want, no need to do anything special. They can use it or not, but the module will be installed in the python environment. 

If you are talking about using ``import some_module`` that works in one computer in one python enviroment, and that it can run in another computer, in another python environment that doesn't have the ``some_module`` installed, I am sorry, it is not possible, how would it work? If you are using a python (pip?) package, you need to use it in your different machines, Conan has no control over that, that is completely outside of the Conan scope. To be clear:

Operating System > Python > Conan

Things that you install in the Python context are outside of Conan control.

What Conan offers for your case is the ``python_requires`` feature, as I pointed out. You can put some python code in a Conan package, that can be used in one recipe, and Conan will manage it for you automatically and transparently. But it needs to be a Conan package, it cannot be a pip/python package.

**Comment by kohei306** [comment]
Hi @memsharded,

Yes, that's what I thought (I was talking about the 2nd case, so run load conan recipe in other environment).

I was wondering, since the some_module is not semantically part of 'recipe'  but only needed to be installed  to fulfill a requirement as python script to be run, it is strange that the some_module has to be installed to conan create the downstream package which is not using the some_module in executed overloaded conan functions.

**Comment by memsharded** [comment]
> I was wondering, since the some_module is not semantically part of 'recipe' but only needed to be installed to fulfill a requirement as python script to be run, it is strange that the some_module has to be installed to conan create the downstream package which is not using the some_module in executed overloaded conan functions.

Well, that is like everything in python, if for example you have it like:

```python

class Pkg(ConanFile):
    ...
    def build(self):
         import some_module
         some_module.do_something()

```
Then it is completely possible to consume that recipe in a computer that doesn't have ``some_module`` installed, as long as you are not building that package from sources and the ``build()`` method is not being called at all. This will work. It will be a bit fragile, in the sense that if you try to build from sources with ``--build`` in the consumer machine, it will fail. You can also rely to idioms like:

```python
try:
     import some_module
except ImportError:
    some_module= None

class Pkg(ConanFile):
     def build(self):
         if some_module is not None:
                some_module.do_something()
```

But I wouldn't say it is a good practice. In general ,if you have something installed in your Python environment, you should aim to have a reproducible Python environment everywhere. But if for some limitation you can really only have that python package in one system, then the above might work.

**Comment by kohei306** [comment]
Hi @memsharded,
Thanks for the detail answer. I will definitely look into it.

**Comment by memsharded** [comment]
Good!

I think the question has been addressed, and possibilities described, no action required at the moment, so closing the issue. But feel free to comment or open a new issue for any further question. Thanks!
