### ISSUE TITLE
Use C/C++ ABI define binary compatiblity

### ISSUE THREAD

**Issue by mropert** [conan-io/conan#796]
I think using compiler versions is not good enough to determine whether or not a binary package is compatible.
Here's my example: on my Linux server (a RHEL 6.4) if I try to use packages from the conan repo for gcc-6.2 with libstd++11 (for example zlib/1.2.8@lasote/stable), I get C ABI errors:
> undefined reference to mempcy@GLIBC_2.14

That's because the C ABI (libc type and version) are not taken into account in settings.
Moreover, two compiler may provide binary compatibility (for example Clang and GCC targeting the same C++ standard library).

So I think we might be better off using C/C++ ABI to determine if a binary package is compatible with the current profile or not.
What do you say?

**Comment by memsharded** [comment]
Thats true. But we find it is a tradeoff, achieving GLIBC compatibility is reasonably easy, and most users don't have to bother about it. Adding it to the standard settings would create a combinatoric explosion of binaries that can make it a bit challenging.

I think that some other users that have had this problem just added some subsetting to the Linux OS to account for different RedHats. I will try to find it and check that again.

**Comment by mropert** [comment]
I agree on principle that combinatory explosion is a risk.
Still, downloading a binary package and getting runtime incompatibilities is a bit... unpleasant.

I guess it boils down to one question: is Conan expected to have a "master" repository (like the one hosted at server.conan.io) for C++ package that should "just work" for any given setup?
If the answer is yes, I think we need the libc version to make sure we don't match incompatible package.
If not (users are expected to setup their own server for their company/community), I guess it can be workarounded.

**Comment by memsharded** [comment]
Excellent question.

IMHO it is extremely challenging to expect to have a master repository with any **binary** that will work for any given setup. It would be a bit less challenging that it is able to work building from sources for 9X% of given setups. There are even many binaries that link with system libraries (like video drivers) in which binary portability is extremely challenging too.

But the truth, is (just my personal opinion) is that I don't know the answer, and only time will tell, as the community matures and gets larger. So far, the most heavy users of conan are not very concerned about binary compatibility of packages from conan.io, as they are hosting their own servers, with the full infrastructure under their control. I suspect that this could be the trend, C/C++ developers are wildly different from lets say, web developers that rely on packages from NPM main repository to deploy to production, which in my opinion, is a huge mistake. I think that C/C++ languages are mostly used in areas in which having your own server would be the only way to go. And by no mean those servers will be filled with binaries from other remotes. If any, they fork recipes and build their own binaries.

So in my opinion, the current tradeoff is enough to be able to provide binaries for a good percentage of conan.io (OSS) users without imposing too much work on the (OSS) package creators.

In any case, I am very interested in at least knowing which would be the correct or better settings that could be proposed for this purpose, how many glibc versions should be managed. Which ranges of glibc are mutually compatible?

**Comment by mropert** [comment]
From what I've seen, glibc is usually backward compatible between minor releases (like most software).
But handling that would mean having a notion of "version" in settings (as opposed to simple string) which do not look for strict equality but can accept a more complex relationship.
A few tricky points it raises just on the top of my head:
- We need to distinguish between major, minor and patch revision for each version.
- Semver does not clearly define binary compatiblity (it's too generic to delve into that point), so possibly different project have different rules for that.
- The comparison is not reflexive, if I'm building for glibc 2.14 I can accept packages built for glibc 2.13 but the reverse isn't true.

**Comment by lasote** [comment]
@mropert if you define a glibc setting with the different versions, [2.13, 2.14, 2.15...] you could use the [`conan_info` method](http://conanio.readthedocs.io/en/latest/reference/conanfile.html#conan-info) to keep the backward compatibility. If you are using glibc `2.14` you can do something like:

```
def conan_info(self):
   v = self.settings.glibc
   if  (v == "2.14" or v == "2.13"):
      self.info.settings.glibc = "2.14" # Or any other string
```

This way if someone is using glibc 2.13 will retrieve exactly the same package as a 2.14 user.
I don't know if glibc is strict backward compatible but you can model any compatibility you know using the `conan_info` method.

You could also import a `conans.model.version` Version object and compare the versions.

**Comment by memsharded** [comment]
Hi @mropert ,

Any new thoughts on this issue? a few weeks have passed, still the glibc compatibility doesn't seems like a very relevant issue for conan.io packages.

Users at their private projects can define any settings they want, let it be the distro version (RH6/RH7), or the glibc version, very easily, and define their custom compatibility logic too if they want.

We wrote a new how-to in the docs: http://docs.conan.io/en/latest/howtos/define_abi_compatibility.html

So I would say that at the moment no changes to the current default settings are necessary, and the current approach to compatibility (working for big majority of cases, not being perfect) is a good tradeoff between simplicity for package creators and compatible binaries for consumers. So if no action is necessary, maybe this issue could be closed. WDYT? Thanks!

**Comment by mropert** [comment]
Hello @memsharded,

The page in the docs is pretty thorough.

I agree that the topic is probably too big to tackle now, since a worldwide repository that could work on any system would require lots of settings.
I ran into issue with libc version but it could be something else, such as processor architecture (what if I try to use a binary built with AVX2 instructions on an older x86_64 cpu for example?).
Then there would be a question of doing more than an exact match to leverage on backward compatibility (for example, a binary built for built for a Core 2 would run on an i5 but not the over way around).

In any case, thanks for your answers, I'll close this for the time being.

**Comment by memsharded** [comment]
Great, thanks for the feedback.  Agree, it is still needed some time for edge cases to arise and mature, first being used by developers privately in their projects, then being introduced by consensus in the defaults settings, and increment gradually the binary compatibility of the global repository towards as many 9s as it could be possible.
