### ISSUE TITLE
[question] Reduce disk usage when packaging a prebuilt library

### ISSUE THREAD

**Issue by pakillottk** [conan-io/conan#7961]
Hi, I'm trying to package a huge SDK that comes with prebuilt binaries (.dll for Windows with each visual studio toolset, .so for Android, etc).

I've tried defining the export_sources method in my conanfile.py and then, in the package method, I only copy the files that are relevant to the current settings. At the moment, the package works fine and other consumer projects works as expected. The only issue is: there's a lot of redundancy in the package's folder (because there are copies of the same files in build, each package... and so on) and this is a huge library, so it's taking around 17 GB from disk space when it should take around 2GB.

Is there some way to actually reduce, or totally avoid, this issue?

The ideal setup would be: just having the entire SDK binaries once in the entire package and just give to the consumers the includedirs, libs and binaries that matches their setups from this "main" folder.

Thanks in advance!

- [V] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @pakillottk 

If you have a huge SDK, then, you don't want to use the ``exports`` or ``export_sources``. You can directly use the ``conan export-pkg`` command to create the executable directly from your user folder (where I assume you have your SDK).

Also, if you need the same binary for all configurations, you might want to manage the "settings" to control the resulting ``package_id``:

- If you don't need the settings at all in the recipe to evaluate nothing, you can simply remove the ``settings`` declaration.
- If you need the settings at some point in your recipe, but you are sure that your final binary will always be the same, define in the recipe the ``package_id()`` method that removes the settings. Something like:
```python
def package_id(self):
     self.settings.clear()
    self.options.clear()
```
- You can programmatically define what goes to consumers in the ``package_info()`` method: the include-dirs, library-dirs, library names, even conditioned to the settings and options.

Please let us know if this helps.

**Comment by pakillottk** [comment]
Thank you so much!

The conan export-pkg was the key I was missing. Now I have a single copy of each file and the package_info sets the right paths. Now the size is around 2GB as I've expected.

Problem solved!

**Comment by memsharded** [comment]
Excellent! Happy that it was a solution for your use case.

I think this can be closed now, don't hesitate to open a new issue for any further question. Thanks!
