### ISSUE TITLE
[feature] Handle CONAN_RUN_TESTS together with self.should_test

### ISSUE THREAD

**Issue by klimkin** [conan-io/conan#7965]
Conan already has condition to handle `self.should_test`. Expand the expression to cover `CONAN_RUN_TESTS` environment variable:

Current:
~~~python
    def test(self, args=None, build_dir=None, target=None, output_on_failure=False):
        if not self._conanfile.should_test:
    return
~~~

Proposal:
~~~python
    def test(self, args=None, build_dir=None, target=None, output_on_failure=False):
        if not self._conanfile.should_test and tools.get_env("CONAN_RUN_TESTS", True):
    return
~~~

`CONAN_RUN_TESTS` [documentation](https://docs.conan.io/en/latest/reference/env_vars.html#conan-run-tests).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by klimkin** [comment]
A better solution could be to take `CONAN_RUN_TEST` into account when setting `conan_file.should_test`  in `cmd_build` method.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/8687, will be in Conan 1.35
