### ISSUE TITLE
[question] require dependency only if it was linked dynamically (shared)

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#7971]
Hi there,
when building a package (PkgA) I have a "build_requirement" (DepA).
DepA can be built with ```shared=True``` or ```shared=False```.

When "requiring" PkgA in another package (PkgB) how can I "require" DepA in PkgA only if DepA was used with ```shared=True```?

The following code does not work (see ```requirements``` at PkgA) and should only illustrate what I am trying to do:

DepA
```python
class DepA(ConanFile):
    options = {
        'shared': [True, False]
    }
```

PkgA
```python
class PkgA(ConanFile):
    def build_requirements(self):
        # could be used by the package creator with DepA:shared=True or DepA:shared=False
        self.build_requires('DepA/0.0.0')

    def requirements(self):
        # this will not work as at this point in time the conan graph has not been resolved
        if self.options['DepA'].shared:
            self.requires('DepA/0.0.0')
```
PkgA ```requires``` DepA only if DepA was linked dynamically at build-time of PkgA.

PkgB
```python
class PkgA(ConanFile):
    def build_requirements(self):
        self.build_requires('PkgA/0.0.0')
```

**Comment by memsharded** [comment]
Hi @Johnnyxy 

There is not modeling for requirements of this kind. Please be aware that ``build_requires`` is designed for tools in mind, like CMake. A key point is that build_requires are NOT part of the ``package_id`` (shouldn't affect the binary), and then most of the CI related tooling, build-order, lockfiles and most importantly, the binary compatibility will be useless to manage this dependency.

I'd recommend:
- Use regular requires for library dependencies, no matter if they are shared or static
- Use build_requires only for tools
- Handle the "deployment" or "runtime" in a final step, could be using deploy(), or maybe repackaging, but it is a flow that is separated from the main development flow


We will be investigating and hopefully designing a more advanced graph model that could represent better these relations, in Conan 2.0, but that will take a while.

**Comment by Johnnyxy** [comment]
Ah I see. At the moment is was merely an optimization for later. As the normal flow at the moment is only used with ```DepA:shared=False```. This means I will hardcode the ```DepA:shared=False``` in ```configure(self)``` of my PkgA which ensures that DepA is only used at build time of PkgA with static linking.

Regarding the problem of the ```build_requirements``` and ```package_id```. I have introduced special informations (via options) into the PkgA's package_id about DepA. This ensures that the package_id is unique.

My scenario is that DepA is used only for building of PkgA. And consumers requiring PkgA do not introduce any requirement for DepA.


I will close this as ```answered```.

**Comment by memsharded** [comment]
> Ah I see. At the moment is was merely an optimization for later.

Ok, great, then I understand it is not a great blocker at the moment. We will keep working for Conan 2.0 with this need in mind, thanks for the feedback!
