### ISSUE TITLE
[bug] conan unable to install nor use package installed in local cache

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#7974]
### Environment Details (include every applicable attribute)
  * Operating System+version: redhat6
  * Conan version: 1.28.1
  * Revisions enabled. 

### Steps

Conan prints:
```
   mtf-alert-server/1.8.0.x@user/channel:abae1d0c11f388605b70738d8dfa5d78c5f9e45d - Missing
```

and then prints:
```
ERROR: Missing binary: mtf-alert-server/1.8.0.x@user/channel:abae1d0c11f388605b70738d8dfa5d78c5f9e45d
```
However this particular *hash* does exists in artifactory..
Why conan didnt want to install it?

It seems that the issue is somehow related to overwriting same hash in the remote artifactory, however --update doesnt help...

Whats the solution?
```
 rm  -rf /opt/conan/deploy/.conan/data/mtf-alert-server/
```

And then its happy
```
mtf-alert-server/1.8.0.x@user/channel:abae1d0c11f388605b70738d8dfa5d78c5f9e45d - Download
```
It will download the package then fine.

Apologies but dont have really any aditiona information.

**Comment by memsharded** [comment]
Hi @fulara 

> Conan version: 2.8.1

Doesn't seem right

Which version of the server are you using?

Do you have revisions enabled?

Can you reproduce this consistently? For every package? Can you reproduce with a ``conan new`` + ``conan create`` + ``conan upload`` + ``conan remove`` + ``conan install``?

**Comment by fulara** [comment]
Fixed version apologies, (confused with internal versioning ).

I think we got this twice through the year.. 
Didn't get to reproduction of this yet, apologies.  just wated to report with proof that something like that happened.

**Comment by memsharded** [comment]
Ok, yeah, this could be one of those challenging bugs that are very difficult to reproduce. Maybe next time it happens, you could do a couple of things:

- Capture a zip of the offending package from the Conan client cache. 
- Capture the client conf (conan.conf, settings, etc)
- Capture the files from the Artifactory remote, including the "internal" ones if possible, like the revisions index.

Send them to us in private for inspection.

**Comment by AbrilRBS** [comment]
We didn't hear back from you for a while, closing for now, but please feel free to reopen should anyone find the same issue, thanks!
