### ISSUE TITLE
[bug] 1.31 Regression: conanfile method evaluation order

### ISSUE THREAD

**Issue by jan-grimo** [conan-io/conan#7976]
I've had a regression with the 1.31 release. I have a set of packages that populate some of their dependencies via the `build_requires` and `requires` methods and afterwards edits the options of its dependencies (including the dynamic ones) in the `configure` method, following [the suggested approach from the docs](https://docs.conan.io/en/latest/mastering/conditional.html).

It appears that the method evaluation order has changed with the 1.31 release, so that `configure` is called before `build_requirements`. If the development approach should change to manage conditional dependencies options directly in the relevant methods, this maybe should be indicated in the documentation.

### Environment Details (include every applicable attribute)
  * Conan version: 1.31

### Logs

There are three packages involved here, each of which make output to list their current set of `requires` and `build_requires`. A is the parent, which has B directly in its list of `requires`. A conditional dependency  `C` is added in the `build_requires` method of `A`. I've added a bunch of debug output f-strings to make the behavior apparent.

```
$ conan install [...]
[...]
conanfile.py (A/3.0.0): A configure called
conanfile.py (A/3.0.0): list(self.requires)=['B', 'boost', 'yaml-cpp']
conanfile.py (A/3.0.0): setting B option python
conanfile.py (A/3.0.0): setting B option microarch
conanfile.py (A/3.0.0): A has no build_requires
B/3.0.0: B configure called
B/3.0.0: list(self.requires)=['eigen', 'boost', 'yaml-cpp']
WARN: B/3.0.0: requirement boost/[>1.65.0] overridden by A/3.0.0 to boost/1.74.0
conanfile.py (A/3.0.0): A build_requirements called
```

**Comment by jan-grimo** [comment]
I'm a little surprised something this fundamental has changed, so I'm worried what I've written isn't enough to find the issue. There's a bit more details to mention in case it's relevant. All packages A, B and C all inherit from a common base class that attempts to propagate options from the parent conanfile to all packages matching a common name prefix.

I'll happily minimize a test case if needed.

**Comment by memsharded** [comment]
Hi @jargonzombies 

Yes, this would be very surprising, we haven't changed anything related to that in the latest release.
In any case, I am not sure what you are explained is true. ``build_requirements()`` has always been evaluated after ``configure()``, as it is documented in https://docs.conan.io/en/latest/reference/commands/consumer/install.html,  (and you can go back a lot of versions, for example https://docs.conan.io/en/1.24/reference/commands/consumer/install.html, and you will see the order is the same).

So it might be another thing that you are seeing the effect. Yes, please, if you could reduce and produce a reproducible example, that would be extremely useful to debug and understand what is happening. Thanks!

**Comment by jan-grimo** [comment]
Hi @memsharded, thanks for clearing up my misunderstanding. I should have looked deeper into the documentation before opening this issue. I'm now convinced my base class just uses flawed reasoning to accomplish its task, and this last release has exposed my error. My apologies and thank you for your time!

**Comment by memsharded** [comment]
Hi @jargonzombies 

No problem, don't hesitate to open more issues for any further question or problem you might have. We always prefer to have feedback, even if it is not an issue at the end. Also if you want some more clarification or advice for what you are trying to achieve in your project. Cheers!
