### ISSUE TITLE
[question] Reading package version from conan recipes "conanfile.py"

### ISSUE THREAD

**Issue by sduraisamy** [conan-io/conan#7982]
When we do conan search it will list all package name with pkg/version@user/channel. Is there a conan way to get the package version from the conanfile.py?.

Usecase:
Want to read the version from the conanfile.py. If the package already available "i.e from the version comparison", then package will not be created otherwise it will be created.

**Comment by memsharded** [comment]
Hi @sduraisamy 

It is not clear what you want to achieve. Do you mean a local ``conanfile.py`` that you have in your user folder, before creating the package? For that case ``conan inspect conanfile.py`` could be what you need.

In any case:

> If the package already available "i.e from the version comparison", then package will not be created otherwise it will be created.

I am not sure that is a robust approach. You might not have bumped the version, but there might be changes in the recipe or something, that could create a different revision. For checking when a package needs to be built or not, maybe the ``--build=missing`` together with the right ``default_package_id_mode`` could be a better solution.

**Comment by memsharded** [comment]
Hi @sduraisamy 

Any feedback or clarification on the above comments?

**Comment by sduraisamy** [comment]
Hi @memsharded 

Sorry for delayed reply.

The above comments clarifies the query. Thanks.
