### ISSUE TITLE
[bug] Package not found in cache by conan in container managed by Github Actions

### ISSUE THREAD

**Issue by nheuillet** [conan-io/conan#7984]
I deeply apologize as this issue as nothing to do with conan. I found the problem.

**Comment by memsharded** [comment]
Hi @nheuillet 

No problem. We have found that most times when docker is involved is some kind of permissions issue with mounted volumes. I guess it was something like that.

No need to apologize! Happy that you found the issue. Don't hesitate to open new issues when you have any further questions
