### ISSUE TITLE
[bug] conan install followed by conan install with lockfile fails

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#7991]
This bug report started from this PR which has most relevant information. 

https://github.com/conan-io/conan-center-index/pull/3382

I believe I've identified the root cause of the problem, but could be wrong. 

The user is able to run `conan install` with the profile provided which creates a lockfile. If they run `conan install` again and pass that lockfile as a parameter, it fails with this error. 
```
ERROR: paho-mqtt-c/1.3.1: paho-mqtt-cpp/1.1 tried to change paho-mqtt-c/1.3.1 option shared to False
but it was already defined as True
```

The specific code from the Conanfile in the error is here in `config_options()`. 

https://github.com/conan-io/conan-center-index/blob/master/recipes/paho-mqtt-c/all/conanfile.py#L32-L43

```python
    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
        # Static linking before 1.3.4 isn't supported
        if tools.Version(self.version) < "1.3.4":
            self.options.shared = True
```

So the most obvious explanation is that Conan initializes the whole graph and hard-sets all the values, and then forbids any value-changing operations.  But, I am not confident this is the problem because there would be an obvious problem, in that any recipe that sets any value in `config_options()` would simply be un-usable with lockfiles.  So, it seems like this problem have been encountered and resolved long ago unless it's a regression.  But then again, here's the code that raises the error and it's 2 years old. 

https://github.com/conan-io/conan/blob/f563439d18dacf4e7310c08c07386f95070eccfc/conans/model/options.py#L134-L137

### Environment Details (include every applicable attribute)
  * Operating System+version: All 
  * Compiler+version: All
  * Conan version: 1.31.0
  * Python version: All

### Steps to reproduce (Include if Applicable)

Of note, the original user report provided both a separate profile for host and build, but I'm not sure that's relevant.  

```
conan install . --install-folder build/android3/debug --profile:build native --profile:host nsdk-android-armv8 -g=virtualenv                                   
conan install . --install-folder build/android4/  -l build/android3/conan.lock

```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
conan install . --install-folder build/android3/debug --profile:build native --profile:host nsdk-android-armv8 -g=virtualenv    

Configuration (profile_host):
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=9
os=Android
os.api_level=21
[options]
libcurl:with_ssl=openssl
lua:compile_as_cpp=True
ms-gsl:on_contract_violation=throw
nlohmann_json:multiple_headers=True
paho-mqtt-c:asynchronous=True
paho-mqtt-c:shared=False
paho-mqtt-c:ssl=True
paho-mqtt-cpp:ssl=True
[build_requires]
*: android-ndk/r21d, cmake/3.18.4, ninja/1.10.1
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]


conan install . --install-folder build/android4/  -l build/android3/conan.lock
...
ERROR: paho-mqtt-c/1.3.1: paho-mqtt-cpp/1.1 tried to change paho-mqtt-c/1.3.1 option shared to False
but it was already defined as True

**Comment by memsharded** [comment]
If static linking is not supported and it will fail:

```python
def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
        # Static linking before 1.3.4 isn't supported
        if tools.Version(self.version) < "1.3.4":
            self.options.shared = True
```

Should be ``configure()`` instead. ``config_options`` is used to configure the available options, but strong, non overridable from downstream option definition, should be ``configure()``.

The problem is still the same, I am investigating.

**Comment by Croydon** [comment]
The recipe should be fine. The wording might be confusing. Static linking builds and works for many people on non-Windows platforms. Windows+static on < 1.3.4 throws an `ConanInvalidConfiguration`

The upstream maintainer strongly discourages using static linking for versions older than `1.3.4`, hence we change the **default option value** in  `config_options()`.

I don't want to get too much off-topic, but as a quick site note, the documentation probably has to get more clear about how to change default options values conditionally (without forcing the value). This has raised repeatedly confusion among many core CCI contributors. I guess the current consensus is, that this was impossible in the past, but some Conan version changed the behaviour of  `config_options()` and since then it is possible.
