### ISSUE TITLE
[question] how to force compiler in required packages?

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7997]
some packages such as elfutils does not support clang, but I need to use clang to build most of my other packages. I know I can use `-s elfutils:compiler=gcc -e elfutils:CC=gcc` But I would like programmatically do this in conanfile.py during configure() or requirements() How can I do this?
 
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @braindevices 

The "configuration" cannot be defined in recipes, it needs to be defined in profiles. Using profiles (and not command line arguments) is the recommended approach for using Conan in production. They can be composed and included, in case you don't want to repeat yourself.

**Comment by memsharded** [comment]
This response still holds. Adding settings values for dependencies in recipes is not a good idea, it creates a lot of problems, configuration conflicts, etc. The correct place to define configurations and settings is profile files, not recipes. Profiles have kept improving, they can be composed, included, and now they can also be templatized with jinja2 templates, and make them conditional to the platform, env-vars, etc. 

So I am closing this question as responded, let us know if you have any other question, thanks.
