### ISSUE TITLE
[question] Mapped configs in cmake_find_package_multi.

### ISSUE THREAD

**Issue by p-groarke** [conan-io/conan#7999]
Hello,
I'm hitting a wall trying to consume the GTest conan package from a custom cmake config.

We are using a custom cmake config called Hybrid (Release with asserts). When consuming packages from conan, I try to map the imported configs to Release.

For ex.
```cmake
# Create custom config
set(CMAKE_CONFIGURATION_TYPES Debug Release Hybrid)

# Use release for our imported targets with find_package.
set(CMAKE_MAP_IMPORTED_CONFIG_HYBRID Release)

# Somewhere
set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR} ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR} ${CMAKE_PREFIX_PATH})

# Later
find_package(GTest CONFIG REQUIRED)
target_link_libraries(my_tests PRIVATE GTest::GTest)
```

`find_package` does try to pickup the Release config for GTest::GTest. However, it fails with the error :
```
LINK : fatal error LNK1104: cannot open file 'CONAN_LIB::GTest_gtest_main_gtest_mainRELEASE-NOTFOUND.obj'
```

The build does work in Release and Debug, so I'm guessing something isn't getting picked up when building with our Hybrid config. Any help welcome, thx.

edit :

The conanfile.
```
[requires]
gtest/1.10.0@_/_

[generators]
cmake_find_package_multi

[options]
gtest:build_gmock=False

[imports]
bin, *.pdb -> ./bin
bin, *.pdb -> ./lib
bin, *.dll -> ./bin
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @p-groarke 

Yes, I think you are hitting the limitation of the ``cmake_find_package_multi`` generator that doesn't map custom configurations. This is something that we are trying to improve, check ongoing work here: https://github.com/conan-io/conan/pull/7915/files

**Comment by p-groarke** [comment]
@memsharded Glad to see you are working on it :)

Have a great day!

**Comment by memsharded** [comment]
CMakeDeps has evolved enough now, we did very large and great refactors and improvements, now it is the time to check this possibility. To summarize:

- The goal is to be able to use Release dependencies while developing in Debug mode the consumer. While this does not work in general in Windows VS, it is doable in Linux
- The current configuration management in CMake multi generators, including CMakeDeps assume same build_type for the dependencies as the current package.

Plan for this iteration is understand the problem, and at least try to test the concept, see if possible or what the blockers could be.

**Comment by memsharded** [comment]
I have started to work on this, with this test:

```python

@pytest.mark.tool_cmake
def test_changing_build_type():
    client = TestClient(path_with_spaces=False)
    dep_conanfile = textwrap.dedent(r"""
       from conans import ConanFile
       from conans.tools import save

       class Dep(ConanFile):
           settings = "build_type"
           def build(self):
               save("hello.h",
               '# include <iostream>\n'
               'void hello(){{std::cout<<"BUILD_TYPE={}!!";}}'.format(self.settings.build_type))
           def package(self):
               self.copy("*.h", dst="include")
           """)
    client.save({"conanfile.py": dep_conanfile})
    client.run("create . dep/0.1@ -s build_type=Release")
    client.run("create . dep/0.1@ -s build_type=Debug")

    cmakelists = textwrap.dedent("""
        set(CMAKE_CXX_COMPILER_WORKS 1)
        set(CMAKE_CXX_ABI_COMPILED 1)
        cmake_minimum_required(VERSION 3.15)
        project(App CXX)

        find_package(dep REQUIRED)
        add_executable(app app.cpp)
        target_link_libraries(app PRIVATE dep::dep)
        """)
    app = gen_function_cpp(name="main", includes=["hello"], calls=["hello"])
    pkg_conanfile = GenConanfile("pkg", "0.1").with_requires("dep/0.1").\
        with_generator("CMakeDeps").with_generator("CMakeToolchain").\
        with_settings("os", "compiler", "arch", "build_type")
    client.save({"conanfile.py": pkg_conanfile,
                 "CMakeLists.txt": cmakelists,
                 "app.cpp": app}, clean_first=True)

    # in MSVC multi-config -s pkg:build_type=Debug is not really necesary, toolchain do nothing
    client.run("install . -s pkg:build_type=Debug -s build_type=Release")
    print(client.load("conan_toolchain.cmake"))
    print(client.current_folder)
    client.run_command("cmake . -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake")
    print(client.out)
    client.run_command("cmake --build . --config Debug")
    print(client.out)
    cmd = os.path.join(".", "Debug", "app") if platform.system() == "Windows" else "./app"
    client.run_command(cmd)
    assert "main: Debug!" in client.out
    assert "BUILD_TYPE=Release!!" in client.out
```

This test passes green. As you can see @p-groarke, it achieves the goal of using ``Release`` dependencies while building the current package in ``Debug`` mode. It works because the ``CMakeDeps`` generator writes the files as follows:

- **dep-debug-x86_64-data.cmake**: This is the information of the ``dep`` package that should be used when consumer is in ``Debug`` mode. It doesn't mean that it will be the ``Debug`` library of the ``dep`` package, in this example that file is pointing to the release package, as it was installed with ``install . -s pkg:build_type=Debug -s build_type=Release``
- **depTarget-debug.cmake**: This appends to the ``dep::dep`` target things like ``$<$<CONFIG:Debug>:${dep_INCLUDE_DIRS_DEBUG}> APPEND``, where the ``dep_INCLUDE_DIRS_DEBUG`` is the variable defined in **dep-debug-x86_64-data.cmake** file, that points a release build of ``dep``

Would this current behavior of ``CMakeDeps`` implement the desired behavior @p-groarke ?

**Comment by p-groarke** [comment]
@memsharded Thank you for working on this! I believe so (our case is even simpler, but we do have situations where we build our core in debug and link in release). If any limitations pop up, I'll let you know, but for now this is great.

cheers
