### ISSUE TITLE
Running multiple instances of conan simultaniously

### ISSUE THREAD

**Issue by traceon** [conan-io/conan#800]
Currently, I execute `conan` from the CMake config script (at config-time), and often I run this config simultaneously on the same system. To protect the internal structure of Conan home and data dirs, I decided to use CMake's directory locking mechanism.
I didn't find any info in Conan's doc, so assuming the locking is not implemented, to make such scenarios safe.
Wouldn't this be a potential problem in general (remembering that almost all package managers use repo/db/metadata locking to some extent?)

**Comment by lasote** [comment]
Yes, it could be a problem. We have some advances but it's not fully resolved. For CI environments users are using CONAN_USER_HOME to dynamically change the conan home and run concurrent tasks, but I think it's not your need. I'll add this issue to the backlog.

**Comment by memsharded** [comment]
Some details about concurrent usage of conan:

- Concurrent reading (as any other readers-only problem) from the local cache, is obviously not a problem, the problem only comes when retrieving packages from remotes or building packages locally.
- A typical use case of concurrent usage of the local cache would be the one of building multiple package binaries concurrently. 
  - This use case don't want to lock the full cache, or mutually-exclusive behavior
  - Can be done taking care of executing first the recipe + `` conan source`` invocation, then launching in parallel all package binaries builds.
  - Each binary uses its own independent build and package folders
- Concurrent read and write access to the same package, will surely fail, if some process try to use a package that is currently being retrieved or built, then anything could happen.

Suggestions taking into consideration the above (i.e. a global lock might be undesirable) welcome.

**Comment by traceon** [comment]
@memsharded, Yes, makes sense, only building/installing packages and modifying metadata by Conan itself (different instances of Conan) is a problem. Protecting the packages that are being used (read) by other processes, in general, is not realistic and not needed.

> Concurrent read and write access to the same package, will surely fail, if some process try to use a package that is currently being retrieved or built, then anything could happen.

In my case, I always run Conan before accessing libs, like, making sure that they are there. So for case when two Conans require the same XYZ package, and one acquired the lock and started building/fetching process, the second one have to wait for lock, even though it will only see later that nothing has to be done, and only then allow its consumer to actually read the artifacts.

**Comment by memsharded** [comment]
I think this has been implemented with the Readers/Writer lock, at least for the important use cases, from conan 0.28, improved in conan 0.29. So I think this can be closed, please report otherwise. Thanks!
