### ISSUE TITLE
[question] How can I use conan with node-gyp?

### ISSUE THREAD

**Issue by gprosch** [conan-io/conan#8006]
I use a binding.gyp file to tell node-gyp how to generate visual studio project files.  In the binding.gyp file I need to specify a path to a library.  For example:

C:\MyLibraries\MyLib.lib

But with conan I have some unpredictable path like:

C:\Users\<Me>\.conan\data\MyLib\1.0.0\_\_\package\1d1d3f19ae580642d118dadec748a59f61104d89\lib\MyLib.lib

The only think I can think to do is to generate dummy .props files, parse them, and then create symbolic links to the libraries I need.  Is there a simpler or more elegant way that I have not considered?

Perhaps the best solution would be to submit a request for a node-gyp generator but in the absence of that I am open to suggestions as to how I might hack a solution.

Thanks in advance - Greg

**Comment by memsharded** [comment]
Hi @gprosch 

Yes, I think the best is to do your own generator. Now you don't need it to be built-in, you can create your own generator and put the code in the Conan cache: https://docs.conan.io/en/latest/howtos/custom_generators.html#storing-generators-in-the-conan-local-cache.

I would suggest to develop the first iteration in that way, and once it is a bit stabilized, if it is general enough to be useful for other users, it can be contributed built-in

**Comment by czoido** [comment]
Hi @gprosch,
Here, you can find a minimal implementation of a generator for gyp and an example of a module using it that you may find useful: 
https://github.com/czoido/conan-gyp-generator
https://github.com/czoido/conan-node-module

**Comment by gprosch** [comment]
Thank you @memsharded and @czoido for your helpful suggestions!  That is very much what I needed.  I will have to adapt the gyp generator for my Windows environment but that was very helpful in getting me started.
