### ISSUE TITLE
[question] Download package sources without building

### ISSUE THREAD

**Issue by kralicky** [conan-io/conan#8008]
Currently, to download package sources to the local cache (i.e. for debugging), I'm using the following method:
```
conan install <pkg> --build=<pkg>
# wait for the build to start, then ctrl+c (or just let it build if it's a small package)
conan remove -b='*' <pkg>
```

Is there a better way to do this? `conan source` doesn't seem to support references.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @cobalt77 

In practice, for debugging and correctly finding the sources, the recommended approach is to do that but not stop the build. In many cases the debug artifacts, PDBs, etc contain absolute paths to the source files, which might be a different cache path that the current one. So only downloading the files doesn't help much. Aren't you having this issue? Which OS and compiler/debugger are you using? Will it locate the sources automatically?

**Comment by kralicky** [comment]
Ah yep you're definitely right... it's only been working due to how my environment was set up. Such a use case doesn't really make sense then. Thanks!

**Comment by memsharded** [comment]
> Ah yep you're definitely right... it's only been working due to how my environment was set up. Such a use case doesn't really make sense then. Thanks!

Yeah, we have been trying to figure out ways to re-discover the sources paths, or to patch the PDBs, or something that makes the experience a bit smoother, but so far, building from sources in debug mode locally seems the most pragmatic approach.

**Comment by kralicky** [comment]
For GCC, there's a command -fdebug-prefix-map that looks like it will allow you to change the debug source paths at build time. If it is configured to be relative by replacing /path/to/conan/sources/ with ../../../sources/ or something like that the paths should line up in any conan cache. Might be worth looking into.
