### ISSUE TITLE
[bug] Export corrupts conanfile.py rewriting SCM when used under python 3.8

### ISSUE THREAD

**Issue by vsevolod-fedorov** [conan-io/conan#8010]
When `conan export` is run under python 3.8, SCM rewrite can corrupt conanfile.py.
For file:
```python
from conans import ConanFile

class TestRecipe(ConanFile):
    name = 'test-recipe'
    version = '0.1'
    scm = {
        'type': 'git',
        'url': 'https://github.com/conan-io/conan.git',
        }

    @property
    def _version(self):
        pass
````
it removes `@property` line from exported file.
_scm_to_conandata_ should **not** be turned on.

Under python 3.7 it works fine.

### Environment Details
Conan version: 1.31.0
Python version: 3.8.4
Tested under OS: Debian & Ubuntu.

### Steps to reproduce

- Create conanfile recipe (example is attached).
- run 'conan export .' in it's directory.

Conanfile.py and example output:
[scm-bug.zip](https://github.com/conan-io/conan/files/5492679/scm-bug.zip)

**Comment by memsharded** [comment]
Hi @vsevolod-fedorov 

Yes, the current default of scm processing is fragile. It is totally recommended to use ``scm_to_conandata``, in fact it will be mandatory in Conan 2.0, the current flow of modifying the recipe will be removed.

This test is able to reproduce it:

```python
    def test_wrong_parsing_with_property(self):
        # https://github.com/conan-io/conan/issues/8010
        tmp = textwrap.dedent("""
            from conans import ConanFile

            class TestRecipe(ConanFile):
                scm = {
                    'type': 'git',
                    'url': 'https://github.com/conan-io/conan.git',
                    }

                @property
                def _version(self):
                    pass
                """)
        ref = ConanFileReference.loads("lib/0.1@user/channel")
        client = TestClient()
        create_local_git_repo({"conanfile.py": tmp}, folder=client.current_folder)
        client.run("create . lib/0.1@user/channel")
        folder = client.cache.package_layout(ref).export()
        conanfile = load(os.path.join(folder, "conanfile.py"))
        self.assertIn("@property", conanfile)
```

I am checking the code for a bugfix, but seems quite complicated and risk to break something. I would recommend everyone to move to ``scm_to_conandata`` as soon as possible.

**Comment by memsharded** [comment]
``scm`` deprecated in 1.X, removed in 2.0, closing this ticket as outdated.
