### ISSUE TITLE
[bug] SCM username value is ignored

### ISSUE THREAD

**Issue by vsevolod-fedorov** [conan-io/conan#8011]
Conan ignores `username` SCM attribute.
For file:
```python
from conans import ConanFile

class TestRecipe(ConanFile):
    name = 'test-recipe'
    version = '0.1'
    scm = {
        'type': 'git',
        'url': 'ssh://github.com/conan-io/conan.git',
        'username': 'test-user',
        }
```
When cloning git repository, `test-user` is not used, but current logged-in user is used instead:
```bash
test-recipe/0.1: SCM: Getting sources from url: 'ssh://github.com/conan-io/conan.git'
ERROR: Command 'git -c http.sslVerify=true clone "ssh://github.com/conan-io/conan.git" .   ' returned non-zero exit status 128.
Cloning into '.'...
seva@github.com: Permission denied (publickey).
```
(conan.git repository is used just as example).

### Environment Details
Conan version: 1.31.0
Python version: 3.8.4, 3.7.3

### Steps to reproduce
- Create conanfile recipe (example is attached).
- run 'conan create .' in it's directory.

Conanfile and example output:
[username-bug.zip](https://github.com/conan-io/conan/files/5492773/username-bug.zip)

**Comment by kdsx** [comment]
According to `conans/tools/scm.py` it looks like `username` is not used if `password` is not specified. Not sure if it's OK because somebody would use a username and an SSH key to authenticate.

**Comment by danimtb** [comment]
@kdsx is right and the username value is only considered if the password one is added to scm too. I took a look at the code and maybe it can be changed to support username and password independently.

Could you verify that a command like `git clone ssh://test-user@github.com/conan-io/conan.git` (following the example above) works from your side?

**Comment by vsevolod-fedorov** [comment]
@danimtb I added this command only as example. In my recipe I use another repository. And it works when I explicitly add username to it, as in your example. And this is what in the recipe right now.

**Comment by kdsx** [comment]
However username passed via URL is captured to `conandata.yml` during `conan export`, and that is not nice.
