### ISSUE TITLE
[feature] Enable override of requirements from "conan install" CLI

### ISSUE THREAD

**Issue by klimkin** [conan-io/conan#8017]
When developing upstream packages and building downstream packages it would be convenient to override dependencies from command line.

For example, building `pkgB`, dependent from `pkgA`. `pkgB` depends on version `pkgA/1.0.0`. I am changing `pkgA` and create a new version in local cache `pkgA/1.1.0`. Convenient command to test the new package would be:

    conan install . --require pkgA/1.1.0

The result would be the same as changing the version in `conanfile.py` of `pkgA`.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AbrilRBS** [comment]
Sorry about the original radio silence! I'm closing this as not planned at the moment.

The Conan 1 CLI won't be getting any more changes now that we're fully into Conan 2, and there the overrides are better handled with other approaches (Like explicit overrides in the recipe, or the new [`[replace_requires]`](https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires) functionality for temp fixes
