### ISSUE TITLE
[bug] Option gets set for private requirement of requirement.

### ISSUE THREAD

**Issue by thvdburgt** [conan-io/conan#8019]
When a consumer package sets an option for a requirement which is also used as a private requirement by another of its requirements this options gets also set for that private requirement, leading to possible errors.

This goes against the following statement from https://docs.conan.io/en/latest/reference/conanfile/attributes.html#options:
> a dependency can be declared as private if it is going to be fully embedded and hidden from consumers of the package 

See below for a simple reproduction.

### Environment Details
  * Operating System: Windows 10
  * Conan version: 1.31.0
  * Python version: 3.9.0

### Steps to reproduce:

`common_old/conanfile.py`:
```python
from conans import ConanFile

class CommonConan(ConanFile):
    name = "common"
    version = "1.0"
```

`req/conanfile.py`:
```python
from conans import ConanFile

class ReqConan(ConanFile):
    name = "req"
    version = "1.0"

    requires = [("common/1.0@test/test", "private"), ]
```

`common_new/conanfile.py`:
```python
from conans import ConanFile

class CommonConan(ConanFile):
    name = "common"
    version = "2.0"

    options = {"new_opt": [True, False]}
```

`main/conanfile.py`:
```python
from conans import ConanFile

class MainConan(ConanFile):
    name = "main"
    version = "1.0"

    requires = ["common/2.0@test/test", "req/1.0@test/test"]

    default_options = {"common:new_opt": False}
```

Export packages of the requirements:
```
conan export common_old test/test
conan export req test/test
conan export common_new test/test
```

Try to create the main package:
```
conan create main test/test
```

This fails with the following error:
```
ERROR: common/1.0@test/test: option 'new_opt' doesn't exist
Possible options are []
```

**Comment by memsharded** [comment]
Sorry this was not responded back then @thvdburgt 

Now the ticket is a bit too outdated. Conan 2 has changed how options are computed and propagated, defined new levels of priorities with the ``important`` options using ``!``, etc.

I am closing this ticket as outdated, but please create new tickets against latest Conan if necessary for any further question or issue. Thanks for the feedback!
