### ISSUE TITLE
[bug] Python 3.9 makes different tar files

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#8020]
The test `test_conan_data_as_source` fails in Python 3.9 because the checksums of the files are not the same in Python 3.9.
The change is introduced in Python because there was a "bug" generating tar files reported [here](https://bugs.python.org/issue18819) and fixed [here](https://github.com/python/cpython/commit/674935b8caf33e47c78f1b8e197b1b77a04992d2)
The thing is, even changing the "type" to either `CHRTYPE`,  `BLKTYPE` won't solve the issue because it changes also the file.

So this cannot be solved without patching the python `tarfile.py` module `def _create_header(info, format, encoding, errors):`.

BUT maybe this is not really an issue in Conan and we have just to patch the test.

**Comment by memsharded** [comment]
I have checked a bit the checksum of .tgz:

- It is only retrieved from the servers during the upload using Api V1, but it is not really used there. ApiV2 doesn't retrieve them at all.
- They are not used much in the Conan codebase.  At the moment only for the ``CachedFileDownloader`` for Api V1 only
- The Artifactory de-dup protocol might do an extra upload if simultaneously using Python<3.9 and Python=3.9, but apparently it is only an optimization.

I'd say we are good to go, fixing that test only, and we should start doing 3.9 in CI.
