### ISSUE TITLE
[feature] Add variable to enumerate all required packages

### ISSUE THREAD

**Issue by 0x8000-0000** [conan-io/conan#8023]
Our build/packaging/release process requires that we aggregate in the install directory all the licenses of the packages that we are using.

I would like an officially supported way to enumerate all Conan packages that were used during the specific build configuration.

I see that there is a "CONAN_TARGETS" variable that seems to have the information, but it is not entirely clean (I would need to strip out the CONAN_PKG:: prefix) and not sure if it is part of the public API or if it subject to change without notice.

What would be great is if Conan CMake target at least would produce a variable that contains the list of all referenced packages. I suppose I could iterate through it and use a generator expression to interpolate CONAN_${FOOLIB}_ROOT/licenses to get to the files that I need.

Thank you for the great tool and for considering this feature.
 
- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AbrilRBS** [comment]
Hi, sorry that this did not get much traction in the past. I hope you found a way to solve this on your end, it was not something trivial to do in old Conan 1 versions.

I just wanted to point out that the [custom deployers feature](https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html) should be a nice solution to anyone looking to do something similar. I'll close this one for stalenes, but again, sorry that your question fell thru the cracks :/
