### ISSUE TITLE
[bug] Documentation does not list self.cpp_info.frameworks

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#8028]
The [`cpp_info` documentation](https://docs.conan.io/en/latest/reference/conanfile/methods.html#cpp-info) does not mention `self.cpp_info.frameworks`.
Is this attribute, aimed for Macos, valid and supported?
It's used by some recipes at conan-center-index.

**Comment by AbrilRBS** [comment]
Closed, newest Conan 2 documentation has been properly documenting this for a while now, sorry this took a bit to get noticed and closed :)
