### ISSUE TITLE
[suggestion] failure to auto-detect a compiler for the default profile should not report 'ERROR:'

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8035]
Conan outputs that there has been an error when no compiler is found during auto-detect:

```
conan profile new default --detect 
Profile created with detected settings: C:\Jenkins\workspace\my_job\.conan\profiles\default
ERROR: Unable to find a working compiler
```

This happens often because my compiler is not installed on the machine - I am using a `build_requires` package for my cross-compiler toolchain and `conan config install ...` to get the profile which adds it.  But I do still want to auto-detect to get the correct values for `os`, `arch`, etc. based on the build machine.

I find this message misleading and developers often mistake this for the reason why jobs fail, rather than looking further down the build log...  and it only becomes more confusing when creating a package which does not have a need for the `compiler` setting at all (for example, when packaging `build_requires`).

I would like to see it re-worded or even removed.  I guess any problems would become clear on `conan install` anyway.

Thanks!

**Comment by memsharded** [comment]
Yes, I agree, this shouldn't be reported as an error.
The UX problem that we see here is users not being aware that they don't have a compiler installed, proceeding, and then something fails, and they blame Conan. We will probably make profile detection explicit in Conan 2.0, in the meantime, probably better remove it (convert it to normal/info display)
