### ISSUE TITLE
[question] is profile:build mandatory when using profile:host

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#8037]
Hi there,

I am using the cross-building profiles feature ([Conan doc here](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#using-build-requires)). Is it intentional that one has to provide the ```--profile:host``` and ```--profile:build``` profiles?

I was under the impression that the following command lines should be the same:
- ```conan install abc/0.0.0@ --profile:host=pr_host --profile:build=default```
- ```conan install abc/0.0.0@ --profile:host=pr_host```
- ```conan install abc/0.0.0@ --profile=pr_host```

1. Builds with ```settings``` from ```--profile:host``` and ```settings_build``` from ```--profile:build```
2. and 3. Builds with ```settings``` from ```--profile:host```. Host and build are the same.

The background is that if one is providing a profile it is normally for the host (where the built code should run) with the ```build settings``` from the default profile (if not set otherwise).

I tried building some library that is providing a code generator. The generator hast to run on the build machine (```profile:build```). But if I am running Conan via 2. or 3. command line the code generator gets built for the ```host```. I was expecting that the build settings are always the ```default``` profile if not specified otherwise.

Best regards

**Comment by memsharded** [comment]
Hi @Johnnyxy 

> I was under the impression that the following command lines should be the same:

Not really. The way that you opt-in to use the new contexts is by explicitly defining a host profile at least. So

```
$ conan install abc/0.0.0@ --profile=pr_host
```
Will not use the new feature at all, this is the previous default behavior, no build profile is defined nor used.

**Comment by Johnnyxy** [comment]
ok, this rules out the third (old) one.
What about the second one? ```conan install abc/0.0.0@ --profile:host=pr_host```
What is or should be defined in conan's build context?

**Comment by memsharded** [comment]
The build profile is always used now in Conan 2.0, closing this ticket.
