### ISSUE TITLE
[bug] msbuild generator: setting of LocalDebuggerEnvironment does not work with multiple dependencies

### ISSUE THREAD

**Issue by lieser** [conan-io/conan#8038]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.31.1
  * Python version: 3.8.3

### Steps to reproduce (Include if Applicable)

1. Require at least two dependencies with shared libraries (e.g. boost and sqlite3)
2. Call `conan install . -g msbuild`
3. Include the generated `conan_deps.props`
4. Debug an executable in Visual Studio
5. The executable will fail to load the dlls

The problem is that the `PATH` environment variable set via the `<LocalDebuggerEnvironment>` property set in the props file does not include the directory of all dependencies.

E.g. with:
conan_deps.props:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
	<ImportGroup Label="PropertySheets">
		<Import Project="conan_boost.props"/>
		<Import Project="conan_sqlite3.props"/>
	</ImportGroup>
</Project>
```
conan_boost.props:
```xml
[...]
	<PropertyGroup>
		<LocalDebuggerEnvironment>PATH=%PATH%;$(ConanboostBinaryDirectories)</LocalDebuggerEnvironment>
		<DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>
	</PropertyGroup>
[...]
```
conan_sqlite3.props:
```xml
[...]
	<PropertyGroup>
		<LocalDebuggerEnvironment>PATH=%PATH%;$(Conansqlite3BinaryDirectories)</LocalDebuggerEnvironment>
		<DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>
	</PropertyGroup>
[...]
```

The environment will only contain a modified `PATH` with the last included dependency, here sqlite3. It should hovered include the binary directories of all dependencies, like it is done by the `visual_studio` or `visual_studio_multi` generator.

Note that I myself am unsure how/if the chaining will work if one includes the `conan_boost.props` and `conan_sqlite3.props` separately in the same project (which from my understanding is the main advantage over using `visual_studio_multi`).

But for the use case of including `conan_deps.props` there would be a simple solution/workaround: overwrite the `<LocalDebuggerEnvironment>` property in the `conan_deps.props` file after the other props file are included.

**Comment by memsharded** [comment]
Hi @lieser 

Thanks for reporting this issue. Apparently it is good enough to do the chaining and append the existing ``LocalDebuggerEnvironment``, as it is done with the other properties. I have submitted a https://github.com/conan-io/conan/pull/8040 pull request to fix it, if everything goes well, this might be included in next Conan 1.32. 

If you want to try to run from the source branch of that PR, that would also be very valuable feedback. The goal is to make this generator the default (and only one) for MSBuild in Conan 2.0, hopefully these improvements are possible to implement everything that works with the other generators.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/8040 has been merged, it will be released in next Conan 1.32. Thanks again for the feedback.

**Comment by lieser** [comment]
Just tested the change, and it works for me now. Thanks for the quick fix.

Btw, what was a lite confusing to me was how the msbuild generator behaved regarding existing files. Because the output explicitly stated `Generator msbuild created conan_sqlite3.props`, I assumed the existing file gets overwritten, and was wondering why your change did not apply. Took a while to figure out I had to first delete the existing files.

Maybe consider improving the output here.

**Comment by memsharded** [comment]
> I assumed the existing file gets overwritten, and was wondering why your change did not apply. Took a while to figure out I had to first delete the existing files.

Yes, that is true, files are not overwritten, because they keep appending .props files for different configurations. Otherwise it will not be a multi-configuration generator, and only 1 configuration will work at a given time.

This should be extremely unlikely, and only happen if you upgrade Conan version + the generator templates has changes + you are keeping the previous .props from previous invocations. As the .props files should be considered temporary and local, maybe not a big issue. If something, instead of changing the output, the .props files could be partially overwritten always to guarantee that, that would be a better solution, I'll consider it in future changes, thanks!
