### ISSUE TITLE
[bug] cmake.patch_config_paths() fails with PermissionError

### ISSUE THREAD

**Issue by Yurmusp** [conan-io/conan#8043]
Hi,

I'm building OpenCV 4.3.0 for aarch64.
It's cross build.
It's modified version of https://github.com/conan-community/conan-opencv
Everything compiles, then installs but this last patching step during packaging fails:
506     def package(self):
507         self.copy("LICENSE", dst="licenses", src=self._source_subfolder)
508         cmake = self._configure_cmake()
509         cmake.install()
510         cmake.patch_config_paths()

It fails with:
ERROR: opencv/4.3.0: Error in package() method, line 510
	cmake.patch_config_paths()
	PermissionError: [Errno 13] Permission denied: '/home/vagrant/.conan/data/opencv/4.3.0/_/_/build/8bf6f6dfbecc99ccf819a01821ecfa373bdda90d/build_subfolder/CPackSourceConfig.cmake'

I listed properties of that file and seems problem is that it is readonly:
vagrant@ubuntu-bionic:~/opencv_pkg$ ls -laF /home/vagrant/.conan/data/opencv/4.3.0/_/_/build/8bf6f6dfbecc99ccf819a01821ecfa373bdda90d/build_subfolder/CPackSourceConfig.cmake
-r--r--r-- 1 vagrant vagrant 10215 Nov 11 04:22 /home/vagrant/.conan/data/opencv/4.3.0/_/_/build/8bf6f6dfbecc99ccf819a01821ecfa373bdda90d/build_subfolder/CPackSourceConfig.cmake

I also built this thing for armv7hf target with different toolchain and it had no issues.
Seems it's caused by some difference in configuration, but I'm not sure which.
In any case, this seems like a bug. 
Seems CMake generates CPackSourceConfig.cmake as readonly and patching then fails.
So, either patching tools shall be able to deal with readonly case or there shall be a way to control how
permissions of CPackSourceConfig.cmake are set. However, I did not find how to change those.
If somebody can point it out I will gladly do that and dismiss this issue.
If there is no straight way to change permissions, then the fix would be to account permissions during patching.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04 (under vagrant)
  * Compiler+version: yokto sdk aarch64 gcc 9.2 
  * Conan version: 1.29.2
  * Python version: Python 3.6.9
cmake version 3.10.2
I also tried cmake 3.18.4 and got same output.

### Steps to reproduce (Include if Applicable)
I'm not sure how to formulate those. It's just too big. 
See previous paragraphs for major parts description.

### Logs (Executed commands with output) (Include/Attach if Applicable)
Tail of conan create output:

...
-- Installing: /home/vagrant/.conan/data/opencv/4.3.0/_/_/package/8bf6f6dfbecc99ccf819a01821ecfa373bdda90d/res/lbpcascades/lbpcascade_profileface.xml
-- Installing: /home/vagrant/.conan/data/opencv/4.3.0/_/_/package/8bf6f6dfbecc99ccf819a01821ecfa373bdda90d/res/lbpcascades/lbpcascade_silverware.xml
ERROR: opencv/4.3.0: Error in package() method, line 510
	cmake.patch_config_paths()
	PermissionError: [Errno 13] Permission denied: '/home/vagrant/.conan/data/opencv/4.3.0/_/_/build/8bf6f6dfbecc99ccf819a01821ecfa373bdda90d/build_subfolder/CPackSourceConfig.cmake'
+ return 1

Let me know if you see a possibility to fix. 
I guess I shall be able to workaround in some ugly way, but having a fix would be nicer.

Best regards,

Yuriy

**Comment by memsharded** [comment]
Hi @Yurmusp 

Quick question: are you building it using some kind of shared folder between the host and the vagrant? Because these errors many time are shared folders permissions. It would be useful to retry in a non-shared folder in the vagrant.

**Comment by Yurmusp** [comment]
The folder with code  similar to conan-opencv  is  nfs mounted. However, 
~/.conan is not on any network mount.

I copied sources to not NFS folder and built it again.
It failed same way.
I tried to remove build folder: same thing.

**Comment by Yurmusp** [comment]
I was able to pass the build with adding this hack:
os.system('find $HOME/.conan/data/opencv -name "*.cmake" -print | xargs -n 1 chmod 644')
before
cmake.patch_config_paths()

Somehow build makes many *.cmake files having 444 permission.
I'm not sure how this happens and I'm not sure what to blame.
Is it cmake issue, cmake scripts issue or conan issue.
I was not able to google any other example of such issue.
If you have any other thoughts on more proper fix, let me know.
Thanks.
Yuriy

**Comment by memsharded** [comment]
I am having a look, there are 2 alternatives:

- Make it builtin in Conan, adding ``os.chmod(file_path, os.stat(file_path).st_mode | stat.S_IWRITE)`` inside the ``tools.replace_in_file()``.
- Decide that ``tools.replace_in_file()`` should respect file permissions, and the ``os.chmod()`` should be done by the recipe.

I can see pros & cons from both, lets ask for team feedback to decide, please @SSE4 @uilianries @jgsogo @danimtb @czoido

**Comment by Yurmusp** [comment]
Another option that I see that there can be a parameter to tools.replace_in_file(respect_permissions=True)
So, it will fail by default, but user can override by setting it to True.
Also, another question is if we override, then after patching, do we leave file writable? or restore original permission?
I guess this also can be addressed with a parameter with default value.

**Comment by SSE4** [comment]
having read-only files in a package is pretty common, and it's pretty common to patch them. IMO `replace_in_file` should:
1. remember file metadata (unix permissions, windows read-only flag)
2. temporary add write permission and remove windows read-only flag
3. apply changes
4. restore file metadata

**Comment by jgsogo** [comment]
I agree with @SSE4 and I think we can do it by default (no need to require an extra parameter). In the end, it is the recipe the one writing the file and it is the recipe the one applying the patch
