### ISSUE TITLE
[bug] cmake_find_package_multi: create lowercase config file

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#8048]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Currently, `cmake_find_package_multi` generator seems to create the "case sensitive" version of config files: `NameConfig.cmake`

I would suggest to create instead the lower case version: `name-config.cmake` (maybe only if name is already lower case).

Why?

Because when a file like `name-config.cmake` is available, both `find_package(Name)` and `find_package(name)` work (even `find_package(NAME)` works I guess).

If `nameConfig.cmake` is available, only `find_package(name)` works, not `find_package(Name)`. Therefore this file may not properly mimic official upstream's config file.

**Example with protobuf**:

see those errors in https://github.com/conan-io/conan-center-index/pull/2037#issuecomment-725712839

conanfile:

```python
    def package_info(self):
        ...
        self.cpp_info.filenames["cmake_find_package_multi"] = "protobuf"
        ...
```

CMakeLists.txt of test_package:

```cmake
...
# this should work with official config file, even if find_package(protobuf CONFIG REQUIRED)
# should be prefered (or find_package(Protobuf) if relying on official module file)
find_package(Protobuf CONFIG REQUIRED)
...
```

Generared cmake files, and errors when `find_package(Protobuf CONFIG)` is called:

```
protobuf/3.9.1 (test package): Generator cmake_find_package_multi created protobufConfigVersion.cmake
protobuf/3.9.1 (test package): Generator cmake_find_package_multi created protobufTarget-debug.cmake
protobuf/3.9.1 (test package): Generator cmake_find_package_multi created protobufTargets.cmake
protobuf/3.9.1 (test package): Generator cmake_find_package_multi created protobufConfig.cmake
...
CMake Error at CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake
```

**Comment by memsharded** [comment]
Oh, this is interesting. We added ``self.cpp_info.filenames["cmake_find_package_multi"] = "protobuf"`` explicitly to the model because it seemed necessary to match the upstream casing of the file. If lowercase always work, this isn't necessary anymore for ``cmake_find_package_multi``?

Are you sure it is always case insensitive, for all CMake versions and in all platforms and OSs? Is it possible that it is only case-insensitive in some systems like Windows?

**Comment by SpaceIm** [comment]
> Oh, this is interesting. We added self.cpp_info.filenames["cmake_find_package_multi"] = "protobuf" explicitly to the model because it seemed necessary to match the upstream casing of the file. **If lowercase always work, this isn't necessary anymore for cmake_find_package_multi?**

Sorry I don't understand.

if `self.cpp_info.filenames["cmake_find_package_multi"] = "protobuf"`, with `cmake_find_package_multi` generator, `find_package(protobuf CONFIG)` works, but not `find_package(Protobuf CONFIG)` while it should.

From https://cmake.org/cmake/help/latest/command/find_package.html

> Config mode search attempts to locate a configuration file provided by the package to be found. A cache entry called \<PackageName\>_DIR is created to hold the directory containing the file. By default the command searches for a package with the name \<PackageName\>. If the NAMES option is given the names following it are used instead of \<PackageName\>. **The command searches for a file called \<PackageName\>Config.cmake or \<lower-case-package-name\>-config.cmake for each name specified**. A replacement set of possible configuration file names may be given using the CONFIGS option. The search procedure is specified below. Once found, the configuration file is read and processed by CMake. Since the file is provided by the package it already knows the location of package contents. The full path to the configuration file is stored in the cmake variable \<PackageName\>_CONFIG.

This is why I recommend to create:

- `<PackageName>Config.cmake` if `self.cpp_info.filenames["cmake_find_package_multi"]` has at least one uppercase character.
- `<packagename>-config.cmake` if `self.cpp_info.filenames["cmake_find_package_multi"]` is lowercase.

**Comment by SpaceIm** [comment]
This is why I recommend to create:

- `<PackageName>Config.cmake` if `self.cpp_info.filenames["cmake_find_package_multi"]` has at least one upercase letter.
- `<packagename>-config.cmake` if `self.cpp_info.filenames["cmake_find_package_multi"]` is lowercase.
