### ISSUE TITLE
How to install executable to $HOME/.local

### ISSUE THREAD

**Issue by Jochen0x90h** [conan-io/conan#8049]
Hi!

Is it possible to install a conan package that contains an executable and all its dependent libs to $HOME/.local?

Thanks

**Comment by memsharded** [comment]
Hi @Jochen0x90h 

You might implement the ``deploy()`` method (https://docs.conan.io/en/latest/devtools/running_packages.html#deployable-packages), which contains an absolute path in the ``dst`` argument, getting the env-var, something like:

```python
class Pkg(ConanFile):
     name = "pkg"
     version = "1.0"
     def deploy(self):
        target_folder = os.path.join(os.getenv("HOME"), ".local")
        self.copy("*", dst=target_folder, src="bin")
```

And then install as:

```bash
$ conan install pkg/1.0@myuser/mychannel
```

Without coding the ``deploy()`` method in your recipes, you might also try to move to the folder you want and execute:
```bash
$ conan install pkg/1.0@myuser/mychannel -g deploy
```

**Comment by Jochen0x90h** [comment]
Hi @memsharded 

Thanks for the reply.

The -g deploy method looks promising, but installs into individual directories. Is it possible to let it install everything into one bin/ and lib/ directory? This way all shared libs of the executable in bin/ are in lib/ and can be found at runtime.

Modifying the deploy() method is also interesting, but it seems it would be executed by default as soon as someone does conan install pkg/1.0@myuser/mychannel. So the user who installed it into the conan cache can not decide if and where to install it. You may want to install to $HOME/local, but other locations are possible, maybe even into /usr/local/bin and /usr/local/lib

**Comment by memsharded** [comment]
The ``deploy`` generator kinds of hardcode that behavior, so it cannot be change. But writing your own generator is relatively simple, and you can put it in your cache for reuse (and share and install it with ``conan config install``). We haven't implemented the builtin ``deploy`` generator as that, because there is a risk of collisions at the deploy step, and there might be libraries or executables called the same. Unfortunate, but it can happen, so it is safer to put the artifacts of each package into their own folder.

The ``deploy()`` method could use one or more env-vars to define the target locations. If those are variable and different users want to install things in different places, that might be a possibility, right?

Last, maybe the concept of "virtualenvs" is useful for you (they are also Conan generators, like ``-g virtualenv`` and ``-g virtualrunenv``) With it, no need to install at the system level, but conan generates for you "activate/deactivate" scripts, that will define the environment you need to run something, pointing to the regular Conan cache, where versions and different configurations do not overwrite each other. With this approach you can have as many different execution runtime environments, and you can activate and deactivate them without needing to modify the system at all.

**Comment by Jochen0x90h** [comment]
I will use a generator in .conan/generators for now. There I can find the dependent libs by iterating over self.conanfile.deps_cpp_info[dep_name].lib_paths and also over all binaries (bin_paths).

But is there a way to find out what the currently installed project is? If I do conan install myproject/1.0.0@ -g mydeploy then I'd like to directly access the properties of myproject. This way I could copy only the binary of myproject. Another idea would be to provide a list of "desired" libs and binaries in the conanfile of myproject, for example a list containing all boost libraries that are actually needed. When myproject uses boost, mydeploy copies all boost libs into the target lib folder. This pollutes it, better would be to copy just the 3-4 libs that I need.

**Comment by memsharded** [comment]
Hi @Jochen0x90h 

> But is there a way to find out what the currently installed project is? If I do conan install myproject/1.0.0@ -g mydeploy then I'd like to directly access the properties of myproject. This way I could copy only the binary of myproject.

Isn't that the ``deploy()`` method? I think you can achieve exactly that adding a detailed ``deploy()`` method in the ``myproject`` conanfile.py. Alternatively, if you want to do it without modifying the ``myproject``, you can always write a simple conanfile.txt or conanfile.py with a ``requires="myproject/..."`` and and ``imports()`` to specify exactly what are the files that you want and how you want them to be copied.

**Comment by Jochen0x90h** [comment]
Thing is that there is no distinction between install into the conan cache (`conan install`) and install to some target directory (like `make install` and using CMAKE_INSTALL_PREFIX). If I would put my code into `deploy()` of the conanfile.py of myproject, then `conan install` will execute it in any case. I'd like to have it as a separate step or at least check if a destination directory was set such as `conan install myproject/1.0.0@ --install_prefix=$HOME/.local` and then I can check the presence of the install prefix and copy the contents if it was given. By the way: Is `deploy()` executed if a package gets installed to the conan cache due to dependency resolution? If A requires B and I install A, I assume `depoly()` of A gets called. Is it also called for B?

**Comment by Jochen0x90h** [comment]
Now I added the functionality to deploy() in the conanfile.py of the project that kicks in when CONAN_INSTALL_PREFIX env variable is set. I call conan_basic_setup() with KEEP_RPATHS so that dependent libraries (e.g. boost) are referenced in the conan cache, but when I do `conan install ...` then the rpath gets patched. This way I can install an executable and its dependencies to $HOME/.local or other install directory. The libs to install have to be listed explicitly (libs variable) so that not everything gets installed e.g. for boost, but this does not work yet for Macos and maybe can be removed when using the new components feature. 

    def deploy(self):
        # libs to install (check with otool -L or readelf -d to find out)
        libs = ["libboost_system", "libboost_filesystem"]

        # install if CONAN_INSTALL_PREFIX env variable is set
        prefix = os.getenv("CONAN_INSTALL_PREFIX")
        if prefix == None:
            print(f"set CONAN_INSTALL_PREFIX env variable to install to local directory, e.g.")
            print(f"export CONAN_INSTALL_PREFIX=$HOME/.local")
        else:
            print(f"Installing {self.name} to {prefix}")
            dstBinPath = os.path.join(prefix, "bin")
            if not os.path.exists(dstBinPath):
                os.mkdir(dstBinPath)
                #print(f"dstBinPath: {dstBinPath}")
            dstLibPath = os.path.join(prefix, "lib")
            if not os.path.exists(dstLibPath):
                os.mkdir(dstLibPath)
            #print(f"dstLibPath: {dstLibPath}")

            # copy executables
            for bindir in self.cpp_info.bindirs:
                srcBinPath = os.path.join(self.cpp_info.rootpath, bindir)
                #print(f"srcBinPath {srcBinPath}")
                files = os.listdir(srcBinPath)
                for file in files:
                    #print(f"file: {file}")
                    print(f"install {file}")
                    src = os.path.join(srcBinPath, file)
                    dst = os.path.join(dstBinPath, file)
                    if os.path.isfile(src) and not os.path.exists(dst):
                        shutil.copy2(src, dst, follow_symlinks=False)
                        if tools.detected_os() == "Macos":
                            # set rpath for macos, check with otool -l <executable>, see LC_RPATH commands
                            os.system(f"install_name_tool -add_rpath '@executable_path/../lib' '{dst}'")
                        else:
                            # set rpath for linux, check with readelf -d <executable>
                            os.system(f"patchelf --set-rpath '$ORIGIN/../lib' '{dst}'")

            # copy libs
            # https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-cpp-info
            for depName in self.deps_cpp_info.deps:
                #print(f"depName: {depName}")
                for srcLibPath in self.deps_cpp_info[depName].lib_paths:
                    #print(f"srcLibPath: {srcLibPath}")
                    files = os.listdir(srcLibPath)
                    for file in files:
                        #print(f"file: {file}")
                        m = re.match("(.+)\.(so|dylib)(\.\d+)*", file)
                        if m:
                            if m.group(1) in libs or tools.detected_os() == "Macos": # -dead_strip_dylibs somehow does not work
                                print(f"install {file}")
                                src = os.path.join(srcLibPath, file)
                                dst = os.path.join(dstLibPath, file)
                                if os.path.isfile(src):
                                    try:
                                        os.remove(dst)
                                    except OSError:
                                        pass
                                    shutil.copy2(src, dst, follow_symlinks=False)

**Comment by AbrilRBS** [comment]
Conan 2 introduced the idea of global deployers, which can also be helpful for cases like this https://docs.conan.io/2/reference/extensions/deployers.html

Closing as solved :)
