### ISSUE TITLE
Conan.io website: badges not working when package name contains a dash

### ISSUE THREAD

**Issue by Mikayex** [conan-io/conan#805]
On conan.io website, package badges aren't working when the package name contains a dash `-` (i.e. see https://conan.io/source/libjpeg-turbo/1.4.2/lasote/stable).

This is because shields.io uses dash to split filename into arguments (subject, status and color) and `--` needs to be used to actually put a dash (see http://shields.io/#your-badge).

So the simple fix is to replace `-` in package names to `--` when displaying the badge.

Also you should do the same thing for underscores and spaces (are they allowed in package name ?) : see http://shields.io/#your-badge

**Comment by lasote** [comment]
Will be available at 0.18. Thanks for reporting.
