### ISSUE TITLE
[question] Propagate options to required packages

### ISSUE THREAD

**Issue by stephanvalentan** [conan-io/conan#8060]
Hello!
Say i have a package `A`, depending on `B`. Now both A and B have an option `options = {"shared": [True, False]}`. However, if the option for A is set to true, it also needs to be set true for B.

So it possible to propagate the value of an option to a package it depends on?

Best, Stephan

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @stephanvalentan 

You can try:

```python
def configure(self):
     self.options["PkgB"].shared = self.options.shared
```

**Comment by vallant** [comment]
Oh sweet, cool! Thank you!

**Comment by stephanvalentan** [comment]
Oh sweet, cool! Thank you!
