### ISSUE TITLE
[bug] msbuild generator: warning MSB4011 - conan_<dep>.props cannot be imported again

### ISSUE THREAD

**Issue by lieser** [conan-io/conan#8065]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows
  * Compiler+version: VS 2019
  * Conan version: 1.31.1

### Steps to reproduce (Include if Applicable)

1. Package A requires B
2. App requires A and B
3. In project file for App, include `conan_deps.props` 

### Logs (Executed commands with output) (Include/Attach if Applicable)

`conan_deps.props` :
```xml
[...]
	<ImportGroup Label="PropertySheets">
		<Import Project="conan_A.props"/>
		<Import Project="conan_B.props"/>
	</ImportGroup>
[...]
```

`conan_B.props` :
```xml
[...]
	<ImportGroup Label="TransitiveDependencies">
		<Import Condition="'$(conan_B_props_imported)' != 'True'" Project="conan_B.props"/>
	</ImportGroup>
[...]
```

The problem is that `conan_A.props` already includes `conan_B.props`, so including it again in `conan_deps.props` causes the warning.
It should probably only be included under the condition `Condition="'$(conan_B_props_imported)' != 'True'"`, like it is done in `conan_B.props`.

**Comment by memsharded** [comment]
Thanks @lieser for reporting. Submitted fix in https://github.com/conan-io/conan/pull/8072, will be in next 1.32.
