### ISSUE TITLE
[feature] Suggest changing comments in conan new command

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#8067]
Someone going through the training pointed out that this commentary made no sense to them, and to be honest, it doesn't make much more to me.  I understand what this code does, and why it might be done in some recipes.  However, it's a really old, ugly, and esoteric pattern, and not the only way to achieve the goal.  I recommend promoting virtually any other strategy as template content that users will certainly be copying and pasting into codebases at the start of their work with Conan. However, others are better suited to choose which alternative pattern should replace it. 

https://github.com/conan-io/conan/blob/8ece0c03c661cc7bd2528fd20351e74f2156a177/conans/client/cmd/new.py#L31-L37

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This will be automatically solved when we move to toolchains and the new ``cmake_find_package`` generator. I think it is not worth the effort of changing this at this moment, as this should be done soon enough.
