### ISSUE TITLE
[question] full_version_mode and ConanCenter query

### ISSUE THREAD

**Issue by djeverett** [conan-io/conan#8069]
I want to have the conan.conf setting of `general.default_package_id_mode=full_version_mode`, but I also want profiles that pull in CMake from ConanCenter:
```
[build_requires]
cmake/3.18.4
```  
This does not work as the CMake recipe in ConanCenter specifies:
```
[requires]
openssl/1.Y.Z
```
and so needs either major or semver version modes.

I'd really rather avoid having to set full version mode for every single dependency in every conanfile.py  (with `self.info.requires["the_lib"].full_version_mode()`) just to permit this one build requirement in the profiles.  Can this be achieved?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @djeverett 

The ``default_package_id_mode`` is a global configuration that changes how the ``package_ids`` are computed. ConanCenter uses just the default one, and all the binaries there are built with that mode.

I understand that the problem you are having is that there are no binaries in ConanCenter for your configuration? That is totally expected, it is impossible that we could create all binaries for all possible modes, and it becomes more challenging the more strict the mode is. If you are changing the ``default_package_id_mode`` you should be building from sources the binaries you need and storing them in your Artifactory. It is not an issue of changing it in the ``package_id()`` method of the recipes, if I understood correctly, the problem will remain the same, that there are no binaries available for it in ConanCenter. Could you please confirm this is your question?

**Comment by djeverett** [comment]
There should be binaries for my configuration.  The profile is:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
cmake/3.18.4
[env]
```
The ConanCenter info gives:
```
[settings]
    arch=x86_64
    build_type=Release
    os=Linux
[requires]
    openssl/1.Y.Z
[options]
    with_openssl=True
[full_settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++11
    compiler.version=5
    os=Linux
```
Now the compiler version does not match, but I have found that if I use a default package ID mode of `semver_mode` or `major_mode`, then CMake installs.  If it is `full_version_mode`, CMake does not install.

**Comment by memsharded** [comment]
The ``default_package_id_mode`` also affects the binary ``package_id``, not only the settings + options. If you change the mode, you need to recompile the binaries, because the ``package_id`` will be different.

**Comment by djeverett** [comment]
OK, understood.  I'll have to build from source and upload to our own repos then.  Thanks for the information.
