### ISSUE TITLE
Whats the best way to find conan python function reference?

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#807]
Maybe it's just because I'm a python n00b, but I've found it frustrating to find reference for self.copy for example where in one case I was interested in preserving symlinks and another I was interested in throwing away the path information. I finally found them by searching the repo...but it wasn't very efficient. It would be nice to have a searchable class reference...or maybe I'm "doing it wrong".

**Comment by sourcedelica** [comment]
A lot of things are covered in the user guide, especially the Reference section, but it tends to be scattered around.  I use search a lot to track down information.  Having class and field level documentation would be super.

**Comment by Mikayex** [comment]
I think it should be reported in [Conan-docs](https://github.com/conan-io/docs) instead...

**Comment by rconde01** [comment]
moved to conan docs

https://github.com/conan-io/docs/issues/126
