### ISSUE TITLE
[question] unable to override version of dependency

### ISSUE THREAD

**Issue by Da-LiFe** [conan-io/conan#8071]
I've some questions regarding overriding dependency versions. 

We packaged the [ros stack](https://www.ros.org/) part of it beeing the following packages:
- `ros_perception/1.1.4@3rdparty/unstable`
- `ros_core/1.1.4@3rdparty/unstable`

with ros_perception requiring ros_core.

Additionally we have a pkgA, that requires ros_perception as well as pkgB:
```
requires = ["ros_perception/[~=1.1]@3rdparty/unstable",
                "pkgB/[~=0]@common/unstable"]
```

pkgB also requires ros:
```
requires = ["ros_core/[~=1.1]@3rdparty/unstable"]
```

Alltogether, we have this (simplified) graph:

```
pkgA
|- ros_perception
|  L ros_core
|- pkgB
   L roc_core
```

Now, we want to test a PR to the ros stack in pkgA, so we add an override to all ros packages in pkgA:
```
requires = ["pkgB/[~=0]@common/unstable",
                ("ros_perception/PR-53@3rdparty/snapshot", "override"),
                ("ros_core/PR-53@3rdparty/snapshot", "override")]
```

However, conan install refuses to install the dependencies:

```
[2020-11-10T18:47:27.196Z] WARN: pkgB/0.1.3@common/unstable: requirement ros_core/[~=1.1]@3rdparty/unstable overridden by pkgA/test-pr@myorg/snapshot to ros_core/PR-53@3rdparty/snapshot 
[2020-11-10T18:47:28.621Z] ERROR: Conflict in pkgB/0.1.3@common/unstable
[2020-11-10T18:47:28.621Z]     Requirement ros_core/1.1.4@3rdparty/unstable conflicts with already defined ros_core/PR-53@3rdparty/snapshot
[2020-11-10T18:47:28.621Z]     To change it, override it in your base requirements
```

Setup:
- conan 1.22.2
- open suse leap 15.1

Questions:
- How come there is a conflict in pkgB, although conan reports an override?
- How can we resolve this issue, as we are already overriding the requirement in the base package.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Da-LiFe 

I am trying to reproduce this issue, did https://github.com/conan-io/conan/pull/8084, but it seems to be working fine. Have you tried updating Conan to the latest version? That might solve your issue. Please let me know if possible and how it goes.

**Comment by memsharded** [comment]
Hi @Da-LiFe 

Did you have a chance to have a look to the test in https://github.com/conan-io/conan/pull/8084/files? I'd say it is coding your use case and it is passing (in develop branch)

**Comment by Da-LiFe** [comment]
Hi @memsharded 

Thanks for providing this test! Didn't yet know about this nice feature of creating conanfiles for tests. I think my example was too much abstracting the actual problem, as your test also runs fine in our environment. The actual dependency graph is way more complicated. I've added a bit more of the real complexity to be able to reproduce the error:

```
import unittest
from conans.test.utils.tools import TestClient, GenConanfile

class MyTestCase(unittest.TestCase):
    def test_override(self):
        # https://github.com/conan-io/conan/issues/8071
        t = TestClient()
        t.save({"conanfile.py": GenConanfile()})
        t.run("create . ros_core/1.1.4@3rdparty/unstable")
        t.run("create . ros_core/PR-53@3rdparty/snapshot")
        t.save({"conanfile.py": GenConanfile().with_require_plain("ros_core/1.1.4@3rdparty/unstable")})
        t.run("create . ros_base/1.1.4@3rdparty/unstable")
        t.save({"conanfile.py": GenConanfile().with_require_plain("ros_core/PR-53@3rdparty/snapshot")})
        t.run("create . ros_base/PR-53@3rdparty/snapshot")
        t.save({"conanfile.py": GenConanfile().with_require_plain("ros_base/1.1.4@3rdparty/unstable")})
        t.run("create . ros_robot/1.1.4@3rdparty/unstable")
        t.save({"conanfile.py": GenConanfile().with_require_plain("ros_base/PR-53@3rdparty/snapshot")})
        t.run("create . ros_robot/PR-53@3rdparty/snapshot")
        t.save({"conanfile.py": GenConanfile().with_require_plain("ros_robot/1.1.4@3rdparty/unstable")})
        t.run("create . ros_desktop/1.1.4@3rdparty/unstable")
        t.save({"conanfile.py": GenConanfile().with_require_plain("ros_robot/PR-53@3rdparty/snapshot")})
        t.run("create . ros_desktop/PR-53@3rdparty/snapshot")
        t.run("create . rosparam_handler/0.1.4@3rdparty/unstable")
        t.save({"conanfile.py": GenConanfile().with_require_plain("ros_desktop/1.1.4@3rdparty/unstable")})
        t.run("create . ros_perception/1.1.4@3rdparty/unstable")
        t.save({"conanfile.py": GenConanfile().with_require_plain("ros_desktop/PR-53@3rdparty/snapshot")})
        t.run("create . ros_perception/PR-53@3rdparty/snapshot")

        t.save({"conanfile.py": GenConanfile().with_require_plain("ros_core/[~=1.1]@3rdparty/unstable")})
        t.run("create . pkgB/0.1.3@common/unstable")

        t.save({"conanfile.py": GenConanfile()
               .with_require_plain("ros_perception/[~=1.1]@3rdparty/unstable")
               .with_require_plain("rosparam_handler/0.1.4@3rdparty/unstable")})
        t.run("create . pkgC/0.2.0@common/unstable")

        t.save({"conanfile.py": GenConanfile().with_require_plain("pkgC/[~=0]@common/unstable")
                                              .with_require_plain("pkgB/[~=0]@common/unstable")
                                              .with_require_plain("ros_perception/PR-53@3rdparty/snapshot",
                                                                  override=True)
                                              .with_require_plain("ros_desktop/PR-53@3rdparty/snapshot",
                                                                  override=True)
                                              .with_require_plain("ros_robot/PR-53@3rdparty/snapshot",
                                                                  override=True)
                                              .with_require_plain("ros_base/PR-53@3rdparty/snapshot",
                                                                  override=True)
                                              .with_require_plain("ros_core/PR-53@3rdparty/snapshot",
                                                                  override=True)})

        t.run("create . pkga/0.1@common/unstable --build=missing --build=pkga")
```

Result:

```
E           ERROR: Conflict in rosparam_handler/0.1.4@3rdparty/unstable
E               Requirement ros_robot/PR-53@3rdparty/snapshot conflicts with already defined ros_robot/1.1.4@3rdparty/unstable
E               To change it, override it in your base requirements
```

That's not exactly the same error message, but I assume the root cause is the same. I had to use `with_require_plain` instead of `with_requires` (doesn't exist in conan 1.22?) and `with_require` (gave me an `'str' object has no attribute 'full_str'`). I hope that doesn't matter in this case.

**Comment by memsharded** [comment]
Hi @Da-LiFe 

Thanks for putting it together as a test!

I am checking it, but surprised to find:
```python
t.save({"conanfile.py": GenConanfile().with_require("ros_robot/PR-53@3rdparty/snapshot")})
t.run("create . ros_desktop/PR-53@3rdparty/snapshot")
t.run("create . rosparam_handler/0.1.4@3rdparty/unstable")
```

With this code, you are making the ``rosparam_handler/0.1.4@3rdparty/unstable`` depend on the PR snapshot ``ros_robot/PR-53@3rdparty/snapshot``, which seemed surprising as I am drawing the graph. Is this the intent or is it a mistake in the test?

**Comment by Da-LiFe** [comment]
Hi @memsharded 

Indeed, that is an error in the test. `rosparam_handler/0.1.4@3rdparty/unstable` should depend on `ros_robot/1.1.4@3rdparty/unstable`. So its giving an error, because there is no "override". Having to look further then for a good test :-/

**Comment by Da-LiFe** [comment]
After adding and adding all of the actual dependencies of those ros_* packages to the test I'm still not able to reproduce this issue this way. But what I find interessting is, that `conan info` is working, but `conan create` is not:

```
pkgB/0.1.3@common/unstable
    Required by:
        conanfile.py (pkgA/None)
    Requires:
        ros_core/PR-53@3rdparty/snapshot
```

@memsharded Any further ideas how to takle this issue?

**Comment by memsharded** [comment]
Hi @Da-LiFe 

So ``conan info`` succeeds without raising a conflict and ``conan create`` does conflict? Are you passing exactly the same configuration to both commands (settings, options, etc)? That is the first thing I would try to investigate: if both commands have same inputs. Getting the full output of both commands could be useful, are there differences in the graph?

**Comment by Da-LiFe** [comment]
Hi @memsharded 

> So conan info succeeds without raising a conflict and conan create does conflict?

Yes, for conan v1.22.2 its conan info which succeeds and conan create/install which show conflicts. 

> Are you passing exactly the same configuration to both commands (settings, options, etc)?
> Getting the full output of both commands could be useful, are there differences in the graph?

Yes, both commands are using the same configuration and the graph is also the same as both commands were performed by our CI system on the same export of the conanfile of pkgA. The full output contains some internal details of my company which I cannot post here in public. Is there a way to send you this information by e-mail?

**Comment by memsharded** [comment]
Yes, you can email it to info@conan.io.

**Comment by memsharded** [comment]
Hi @Da-LiFe 

Checking outdated open PRs, I have seen https://github.com/conan-io/conan/pull/8084, intended to address this issue. 
I am not sure if we already followed by email, I don't recall if you managed to find a solution for this.

Otherwise with https://github.com/conan-io/conan/pull/8084, this issue will be closed, but feel free to re-open or create a new ticket. Thanks!

**Comment by Da-LiFe** [comment]
Hi @memsharded 

We did some e-mailing back then but we were not able to reprocude the issue on your side. However, It's fine for me to close this issue, because I didn't see the issue on our side once more in the last two years.
