### ISSUE TITLE
[feature] Qbs build helper

### ISSUE THREAD

**Issue by Psy-Kai** [conan-io/conan#8079]
It would be nice to have a Qbs build helper. Since Qbs has its own profiles it is not possible to just run the qbs command to build an application.  
When building a conan package with qbs first a qbs profile has to be created with the conan profile settings. Adding this manually to every conanfile or build pipeline definition is tedious. A Qbs build helper could setup qbs profiles automatically.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I don't oppose to this feature, but we don't have resources for this now, as we don't have enough experience with Qbs. So we would need some Qbs users to contribute this.

This will require also to do this in the new integration model = using toolchain files for enabling the usage of the build system outside Conan, apart from the Qbs generator.

**Comment by Psy-Kai** [comment]
@memsharded I am currently working on a Qbs Build Helper. But I am not able to run any unittest (running pytest just leads to a huge amount of errors and nothing more).  
What do you mean with "new integration model"?

**Comment by memsharded** [comment]
> What do you mean with "new integration model"?

https://docs.conan.io/en/latest/creating_packages/toolchains.html

This means: the build helper should do as little as possible, basically what the user would do on the command line. All the other configuration should go to files, generated in the ``toolchain()`` method at install time, and both the build helper and the user at command line would use the generated files by the ``QBSToolchain``

Regarding pytest, don't worry too much, just run the tests that you create with the path, something like ``python -m pytest conans\test\unittests\source\merge_directories_test.py``

**Comment by Psy-Kai** [comment]
So toolchains are basically like the output of a generator but with profile values? Do I understand the toolchains correct?  
If yes, should the toolchain file include a possible generators output?

**Comment by memsharded** [comment]
> So toolchains are basically like the output of a generator but with profile values? 

Yes: things related to the **current** package build, belongs to toolchains. They map settings and options from profiles to the specific of the build system. While generators focus on the information from dependencies only, not the current package. The toolchain should not include the generators, the current way of thinking is keeping them as decoupled as possible.

**Comment by Psy-Kai** [comment]
@memsharded In the conanfile function `toolchain` the environment variables defined in a profile are not set. Is this on purpose or just a bug? Because in order to detect a cross-compiler toolchain set in the profile (via `CC=`) my QbsToolchain needs access to these environment variables.

PS: I did not test with the new build_requires & build_profile method yet.

**Comment by Psy-Kai** [comment]
@memsharded Should the toolchain file contain the path to the used compiler and some plattform related flags (like general linker and compiler flags)? If yes the toolchain file would need to env variables from the profile and to cpp_info/env_info/user_info from build requirements. When cross compiling I would prefer to use a build requirement. So in the toolchain method some values defined by the build requirement might end up in the toolchain file (e.g. the sysroot, where to find the compiler, the already mentioned linker and compiler flags).
