### ISSUE TITLE
[bug] Can't use cmake.install() in test_package/conanfile.py

### ISSUE THREAD

**Issue by phi-hae** [conan-io/conan#8080]
When executing "conan create", and the conan package includes a test_package with a call to cmake.install() in its conanfile.py's build() method, the "conan create" step fails with following error message:

 ERROR: test/0.0.1@user/testing (test package): Error in build() method, line 18
        cmake.install()
        TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

This issue makes it impossible to use cmake.install() in test packages.

### Environment Details
  * Operating System+version: Windows 10
  * Compiler+version: MSVC 19.16.27038.0
  * Conan version: 1.28.2
  * Python version: 3.8.6

### Steps to reproduce
Run conan new test/0.0.1 -t
Add cmake.install() to test_package/conanfile.py -> build(self):
```
    def build(self):
        cmake = CMake(self)
        # Current dir is "test_package/build/<build_id>" and CMakeLists.txt is
        # in "test_package"
        cmake.configure()
        cmake.build()
        cmake.install()
```
Run conan create . test/0.0.1@user/testing 

**Note:** The example above was chosen for the sake of simplicity. It is generally expected that cmake.install() would fail in this example because the install target does not exist. However the above mentioned error is also reproducible in more complex examples that actually define an "install" target.

### Workaround
The issue can be worked around by manually setting the required vars:
```
    def build(self):
        cmake = CMake(self)
        # Hack: For some reason when running "conan test" the package_folder
        # and CMAKE_INSTALL_PREFIX are not defined, so we need to set them
        # Manually here. Conan bug?
        cmake._conanfile.package_folder = "package"
        cmake.definitions["CMAKE_INSTALL_PREFIX"] = cmake._conanfile.package_folder
        cmake.configure()
        cmake.build()
        cmake.install()
```

**Comment by uilianries** [comment]
Hi @phi-hae We don't use `cmake.install()` for test_package, all tests are executed under the build folder directly. Please, take a look on Conan Center Index as example: https://github.com/conan-io/conan-center-index/blob/master/recipes/arrow/all/test_package/conanfile.py

**Comment by phi-hae** [comment]
Hi @uilianries, thanks for the answer. I do understand that cmake.install() is generally not required for all cases. However in my case, the tests contained in test_package depend on artifacts that are generated during cmake.install() step.
Also:
calling conan install && conan build on the test_package's conanfile.py works perfectly fine. But when calling conan test on it, the implicitly executed conan build step fails with above mentioned error. So the behaviour of build() is different, depending on the execution method, which shouldn't be the case imho.

**Comment by madebr** [comment]
Having cmake.install work by default is sometimes useful when the output dirs functionality of the cmake generator does not suffice 

Maybe conan should set the package folder of a test_package to a `package` subdirectory of the build folder.

**Comment by memsharded** [comment]
This PR https://github.com/conan-io/conan/pull/8117 defines the ``package_folder`` to be the current build folder of the test_package recipe. I am not sure about naming such folder ``package``, because that is not a package at all, and could be very confusing to many users. Any name would feel a bit arbitrary, isn't it possible to make it install directly in the build folder?

**Comment by madebr** [comment]
It can, but it might clash with the output directories set by the cmake gnerator (and able to disable by `conan_basic_setup(NO_OUTPUT_DIRS)`).

**Comment by phi-hae** [comment]
@memsharded First of all, thanks for looking into this. Imho calling it "package" would make a lot of sense since then we'd get the same behavior inside the test_package build folder when calling "conan create" on the package's conanfile and when running "conan install && conan build" on the test_package's conanfile

**Comment by memsharded** [comment]
I have added ``package`` to my test, but it was reading a bit magical and obscure:

```python
            from conans import ConanFile, CMake, load
            class TestConan(ConanFile):
                def build(self):
                    cmake = CMake(self)
                    cmake.configure()
                    cmake.install()
                def test(self):
                    # WHere the "package" comes from?? Can't I configure it?
                    self.output.info("Content: %s" % load("package/include/header.h"))
```
So instead of adding this, I would recommend at the moment the explict ``package_folder`` definition. @phi-hae your code above can be greatly simplified, and look less like a hack. This works:
```python
            from conans import ConanFile, CMake, load
            class TestConan(ConanFile):
                def build(self):
                    self.package_folder = "package"
                    cmake = CMake(self)
                    cmake.configure()
                    cmake.install()
                def test(self):
                    self.output.info("Content: %s" % load("package/include/header.h"))
```
We will probably be working soon in better modeling of the layouts, but at the moment I think it would be a nice solution, what do you think?

**Comment by phi-hae** [comment]
@memsharded Please correct me if I'm wrong but isn't the first case that you say is reading a bit "magical" the default for "conan build <conanfile>"? Probably self.package_folder defaults to "package" there? I don't understand why it should be different for test_package...

**Comment by phi-hae** [comment]
Thanks also for your suggestion with `self.package_folder = "package"`. That works for me, and yes - it looks way better already :)

**Comment by memsharded** [comment]
>  Probably self.package_folder defaults to "package" there? 

Yes, it is true that the main recipe ``conan build`` is defaulting to the "package" folder. The thing is I don't think it is a good one, and we are doing some work to try to improve this. In any case, as it is used there and is an easy fix that avoid some crash, lets move the PR forward for next 1.33.
