### ISSUE TITLE
[bug] Conan doesn't see requirements headers on build

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8083]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: clang 7.0
  * Conan version: 1.31.0
  * Python version: 3.7.4

I'm trying to make a package from that [repo](https://github.com/JLouis-B/IrrAssimp/tree/aed2cab5505f0164689c2aebdb8d9f6c729066e6)

Here is my `conanfile.py`  
```Python
from conans import ConanFile, CMake, tools


class IrrAssimpConan(ConanFile):
    name = "IrrAssimp"
    version = "1.8.4"
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    options = {
        "shared": [True, False]
    }
    default_options = {
        "shared": True
    }
    source_folder = "source"

    def requirements(self):
        self.requires("irrlicht/1.8.4@mpusz/testing")

    def source(self):
        self.run("git clone --depth 1 https://github.com/JLouis-B/IrrAssimp.git %s" % self.source_folder)

    def _configure_cmake(self):
        cmake = CMake(self)
        cmake.definitions['BUILD_SHARED_LIBS'] = "ON" if bool(self.options.shared) else "OFF"
        cmake.configure(source_folder=self.source_folder)
        return cmake

    def build(self):
        cmake = self._configure_cmake()
        cmake.build()

    def package(self):
        cmake = self._configure_cmake()
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["IrrAssimp"]
```

When I do `conan create . -pr myprofile.debug` I get this  
> fatal error: 'irrlicht.h' file not found
and similar compilation errors

Why doesn't conan include `requires` include dirs when building a package?

**Comment by memsharded** [comment]
> cmake.definitions['BUILD_SHARED_LIBS'] = "ON" if bool(self.options.shared) else "OFF"

This is done automatically, you don't need to include it

> def requirements(self):
>        self.requires("irrlicht/1.8.4@mpusz/testing")

You can do simply
```python
class Pkg(ConanFile):
    requires = "irrlicht/1.8.4@mpusz/testing"
```

How to debug what is happening:

- Check the generated ``conanbuildinfo.cmake``, that it includes the Assimp library. Check the include directories, go to that folder in the disk and check that the files, the headers, actually exist there.

- Check your ``CMakeLists.txt`` that it does ``include($CMAKE_BINARY_DIR}/conanbuildinfo.cmake)`` + ``conan_basic_setup()``

Please try that and let us know.

**Comment by xahon** [comment]
Thanks, @memsharded, i forgot to add `include($CMAKE_BINARY_DIR}/conanbuildinfo.cmake) + conan_basic_setup()` with `tools.replace` but now it fails with some linking errors

> /usr/bin/ld.default: CMakeFiles/IrrAssimpDemo.dir/IrrAssimp/IrrAssimp.cpp.o: in function `IrrAssimp::getExportFormats()':
/home/user/conan/IrrAssimp/1.8.4/_/_/build/b1b469bcd8ddaaea9d2a6b59dfaa77f32e34dcf5/IrrAssimp/IrrAssimp.cpp:68: undefined reference to `Assimp::Exporter::Exporter()'
/usr/bin/ld.default: /home/user/conan/IrrAssimp/1.8.4/_/_/build/b1b469bcd8ddaaea9d2a6b59dfaa77f32e34dcf5/IrrAssimp/IrrAssimp.cpp:69: undefined reference to `Assimp::Exporter::GetExportFormatCount() const'
... etc ...

I made a [repository](https://github.com/xahon/conan-IrrAssimp/tree/0fca3a95c320a794274d7b9ec20ac57c11503762) that contains project submodule, recipe and profiles I use
Command `conan create . -pr profiles/Linux.x86_64.debug --build missing`
What am I doing wrong?

**Comment by memsharded** [comment]
With the ``cmake`` generator you have 2 modes of getting the libraries linked:

- The global one, you get a ``CONAN_LIBS`` variable defined that you can ``target_link_libraries(mytarget PRIVATE ${CONAN_LIBS})``
- The targets one, defining ``conan_basic_setup(TARGETS)`` and then ``target_link_libraries(mytarget PRIVATE CONAN_PKG::mydep)``

Furthermore, you have more modern CMake integrations, like using the ``cmake_find_package_multi`` generator instead, that will generate on the fly ``xxxxConfig.cmake`` for the dependencies one for each dependency, so you can use the dependencies with ``find_package(dependency REQUIRED)`` syntax.
