### ISSUE TITLE
[bug] "conan remove" does not remove the "export" folder from Artifactory

### ISSUE THREAD

**Issue by f18m** [conan-io/conan#8085]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: 
  * Conan version: 1.31.2
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)

We create a lot of Conan packages that make use of the "exports_sources" property (as suggested in "Recipe and Sources in the Same Repo").
We upload such conan packages to a private instance of Artifactory.
We then need to cleanup such repository from time to time (in particualr the "unstable" channel).

To cleanup the packages we currently apply the following logic:
1. conan search --raw --remote $CONAN_REPO "*/*@myuser/unstable"
2. for each result: conan search --remote $CONAN_REPO "$pkg"   where $pkg is a result of step1
3. for each pkg ID we remove it with: conan remove --remote $CONAN_REPO "$pkg" --force --packages "$id"

Note that we cannot use -p alone because of https://www.jfrog.com/jira/browse/RTFACT-16410
The sequence above works in the sense that the binary packages are removed. However if I browse the Artifactory I see that all Conan packages are still there, with an empty "package" folder but a filled "export" folder.
How can I delete the export folder?

**Comment by memsharded** [comment]
Hi @f18m 

This doesn't seem a bug. The export folder is were the recipe is stored, that is, the definition of package itself. If you want to remove it, you need to remove the whole package, so do ``conan remove`` without the ``--packages``. The ``--packages`` is intended for removing only the binaries, not the recipe (which will continue in the export folder)

**Comment by ericriff** [comment]
I saw this in the past and I believe it went away after upgrading artifactory, but I'm not sure.

**Comment by f18m** [comment]
Hi @memsharded , 
I can confirm that indeed removing the --packages option the whole package gets removed from Artifactory, thanks for pointing it out!
Closing this bug!
