### ISSUE TITLE
[feature] allow conan lock create to accept a directory containing a conanfile

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#8086]
I would like to a similar command line for all my conan commands, however the `conan lock` seems to be an exception at the moment.

The current reality is correctly reflected in the documentation. [lock](https://docs.conan.io/en/latest/reference/commands/misc/lock.html) vs [create](https://docs.conan.io/en/latest/reference/commands/creator/create.html)

```sh
$ conan lock create .        
ERROR: Conanfile does not exist in /mnt/c/Users/Chris McArthur/Documents/user-management/backend
```

The displayed error message is also a little misleading.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @prince-chrismc 

This is intended and it will reflect the next Conan 2.0 command line. It will basically be the opposite: we will change the ``conan create``, ``conan install`` and other commands to explicitly require the full path including the filename.

The goal is to remove any ambiguity, that we have learned is confusing to users, for example when there are both a conanfile.txt and a conanfile.py in the same folder. Same will apply to basically everything that requires a file, for example the lockfile commands will always explicitly require the name of the lockfile, and there will not be a default filename that requires passing only the folder. The rule will be based on the python zen: "better explicit than implicit"

**Comment by prince-chrismc** [comment]
Perfect. Since this is a roadmap item I will close the issue
