### ISSUE TITLE
[bug] 1.31.0 breaks building packages in parallel 

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8087]
Since upgrading to 1.31.0 my parallel builds are failing when multiple process try to access the downloaded conan_package.tgz.  Seems to be related to the new feature #7886 to hold this file in the cache.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 64-bit
  * Compiler+version: n/a
  * Conan version: 1.31.0
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
In parallel:
```
conan install pkga/0.1@user/testing#<rref>--build=pkga/0.1@user/testing#<rref> --build=missing --lockfile=locks/app_debug.lock --lockfile-out=locks/app_debug_node1_updated.lock 
conan install pkgb/0.1@user/testing#<rref>--build=pkgb/0.1@user/testing#<rref> --build=missing --lockfile=locks/app_debug.lock --lockfile-out=locks/app_debug_node2_updated.lock 
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
Traceback (most recent call last):

  File "c:\python37\lib\shutil.py", line 398, in _rmtree_unsafe

    os.unlink(fullname)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Jenkins\\workspace\\pkgb\\.conan\\data\\pkgb\\0.1\\user\\testing\\dl\\pkg\\<pkg_id>\\conan_package.tgz'

```

**Comment by memsharded** [comment]
Hi @GordonJess 

Just in case, a reminder: the Conan cache is not concurrent. It is not designed to be used by multiple processes in parallel, and race conditions and other errors might happen. There are some locks provisioned to try to allow some operations (like installing different binaries (debug/release for example) of the same package in parallel, but that is the exception, and other parallel usage of the cache might result in undefined behavior.

If you could please post the full traceback, and also comment is this happens always or almost always, or this is an occasional error, that might help to investigate if something can be improved.

**Comment by DukeOfKirkcaldy** [comment]
Hi @memsharded,

Ah, now I remember that point coming up before for a different issue.  But I haven't had any problems rebuilding dependent package in parallel until now.  It happens every time in 1.31.0, but everything works as expected reverting to 1.30.0. 

I had originally assumed it was possible from the note in [Build order in lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles/build_order.html#build-order-in-lockfiles), not realizing a separate cache is needed for each rebuild.

> Every item in the outer list is a “level” in the graph, a set of packages that needs to be built, and are independent of every other package in the level, so they can be built in parallel

So I guess one solution would be to trigger the Jenkins jobs for these packages in parallel so they create their own cache in their separate workspace... but feels like this will dramatically increase the build time.

**Comment by memsharded** [comment]
Closing as outdated.
