### ISSUE TITLE
[question] Error while consuming recipe with components

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#8090]
Hi Guys!

I'm trying to modify a recipe that relies on boost, since there is a PR open for it to add the components.
My recipe looks like this:
```
    def requirements(self):
        self.requires("boost/1.73.0@eric/dev")
        self.requires("eigen/3.3.7@eric/dev")

     # Build, package and stuff

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
        # This only needs a subset of boost.
        self.cpp_info.requires = ['boost::serialization']
        self.cpp_info.requires = ['boost::filesystem']
        self.cpp_info.requires = ['boost::system']

```

When I try to build I get  the following error 
```
ERROR: 
        ConanException: MyPackage/4.0.2@eric/dev package_info(): Package require 'eigen' not used in components requires
```

If I add ` self.cpp_info.requires = ['eigen::eigen']` to MyPackage recipe it then gives me the same error but about 'boost' not used in components requires.

What am I doing wrong?

Thanks!

**Comment by ericriff** [comment]
I followed the docs to consume the packages like this
https://docs.conan.io/en/latest/creating_packages/package_information.html#using-components

Recipes that require packages that declare components can also take advantage of this granularity, they can declare in the cpp_info.requires attribute the list of components from the requirements they want to link with:
```
class Library(ConanFile):
    name = 'library'
    requires = "openssl/1.0.2u"

    def package_info(self):
        self.cpp_info.requires = ['openssl::ssl']
```
In the previous example, the ‘library’ package and transitively all its consumers will link only with the component ssl from the openssl package.

**Comment by ericriff** [comment]
This looks related to what @jgsogo did here https://github.com/conan-io/conan/pull/7644

**Comment by SpaceIm** [comment]
Because you must append, not assign successively (because it overrides previous assignement). It doesn't work like `self.requires()`

This should work:

```python
    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
        # This only needs a subset of boost.
        self.cpp_info.requires = ['boost::serialization', 'boost::filesystem', 'boost::system', 'eigen::eigen']
```

works also:

```python
    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
        # This only needs a subset of boost.
        self.cpp_info.requires = ['boost::serialization', 'boost::filesystem', 'boost::system']
        self.cpp_info.requires.append('eigen::eigen')
```

**Comment by ericriff** [comment]
duh!
Thanks. That worked. 
Where is my cone of shame? haha
