### ISSUE TITLE
[feature] Add search functionality to see package remote association

### ISSUE THREAD

**Issue by carobins** [conan-io/conan#8092]
My team is running into issues in which a user might remove and then re-add a remote. When this happens, the remote association to any package that was pointing to the remote that was removed is set to `null` (in metadata.json). This has consequences in that the --update flag (for conan install) no longer works since the package association is lost. Since the package has null remote definition, a package fetch simply fails without any indication that the remote definition is missing.

Is it possible to add search functionality that exposes which packages in the local cache have a remote definition of null? Maybe there is a better fix, but at least this would help us quickly discover which packages have lost their remote definition. 

To recreate the problem:
1) Upload a package to artifactory
2) Remove the remote that the package was uploaded to with `conan remote remove ...` 
3) Restore the remote that was just removed `conan remote add ...`
4) Have another user make a change to the package, such as add a new option from another machine and upload the package to artifactory.
5) Try to fetch the package the other user uploaded by specifying the option they added. This will fail because the remote association is lost. Even if you specify `conan install ... --update` it still fails.

I understand that remote association may be moving out of the package eventually, but if possible an intermediate solution could be helpful.

**Comment by memsharded** [comment]
Proposing a --no-remote argument to ``conan remote list_ref`` to list references in cache without remote.
The UI is not great, we certainly want to improve this in the new CLI, lets see if possible to accept this at the moment.

**Comment by memsharded** [comment]
Conan 1.32 adds in https://github.com/conan-io/conan/pull/8094 syntax for listing packages that don't have a remote defined.
