### ISSUE TITLE
[question] How to publish pre-compiled binaries to artifactory for use by non-Conan users?

### ISSUE THREAD

**Issue by dragondive** [conan-io/conan#8095]
My team works with an external company that provides us a library as pre-compiled binaries. We run some tests with this library (using Google Test). We then publish this library to an internal artifactory for use by other teams. They download the package using either the artifactory web interface or curl commands. The below screenshot shows the structure of the package uploaded to artifactory.

![packages_example](https://user-images.githubusercontent.com/2300602/99878033-72b96a00-2c28-11eb-968d-40f15294bb1b.png)

I want to introduce Conan to gradually move away from these manual processes. My first step is to use it for my team's testing mentioned above. As I understand from this document, [Packaging Existing Binaries](https://docs.conan.io/en/latest/creating_packages/existing_binaries.html), I could upload pre-compiled binaries as a Conan package to artifactory, and then consume that package using Conan for my tests. 

However, the binaries would be uploaded with the unique ID, thus the human-readable name for the binary type (Linux_GNU, etc. in above screenshot) is "lost". Thus, the non-Conan users won't be able to use these packages as they do now. Getting everyone to switch to Conan all at once also won't work.

What is a good approach to handle this situation where Conan packages have to be consumed by both Conan users and non-Conan users?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @dragondive 

You can read about the concept of creating generic binaries here: https://docs.conan.io/en/latest/integrations/deployment.html

The basic idea is:

- Collect deployment binaries from Conan packages with generator ``-g deploy`` or with ``imports()`` or ``deploy()`` method
- Package it in any format you would like, with the naming convention you want, a tarball, or create other system packages like debian.
- Upload them to a generic (not a Conan one) Artifactory repo.

Note, however, that some information that is contained in the Conan recipes, like the ``package_info()`` will be lost, and consumers of those artifacts will need to figure out what they need to put in their build systems. For applications is not a problem, but if the consumers need to build and link against a lot of libraries, they might need to manually add them to their build scripts.

Alternatively, the Conan ``conan_package.tgz`` contain the desired binaries for each configuration. You might create a static site or something that just contain redirects with the name you want to the correct Artifactory artifact, building the mapping between your semantic names and the Conan package-ids.

**Comment by dragondive** [comment]
Thanks, @memsharded.

I will go through these two approaches in some more depth and figure out which one is better suited for my requirements.

**Comment by memsharded** [comment]
Ok, as there is no immediate action required from our side at the moment, lets close it, and if there are further questions feel free to open a new issue. Thanks!
