### ISSUE TITLE
Python2-3 recipe checker

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#811]
Recipes themselves might be py2, py23 or py3 only. If possible, a checker that they are py23 compatible would be very useful. Any suggestions of checker?

So far it has not been a big issue, most conan users stick to python2, and in very few occassions py2-3 incompatible syntax is introduced in recipes. But if would be nicer if it could be checked.

cc/ @sztomi

**Comment by sztomi** [comment]
cool, that was fast :)

I think the best would be to look for hashbangs in the file and parse those. It's not trivial because a couple of forms are allowed, like

```
#! /usr/bin/python3
#! python3
#! python3.5
#! python2.7
```

etc. This would allow users to state their preferred version without being obnoxious. However, what should conan do when it detects a mismatching version? Would starting itself in a matching interpeter process be feasable? (maybe only for that single conanfile?)

**Comment by memsharded** [comment]
I was thinking more about doing a syntax check at ``conan export`` time, if there is something incompatible, raise Error, force to fix it.

**Comment by sztomi** [comment]
I might be misunderstanding something, but: you can't know which python version the end user will be running, so it doesn't make sense to detect incompatibilities at export time.

**Comment by memsharded** [comment]
I was thinking if some library existed in the spirit of the 2to3 python tool that allows running upgrades, so running it on the recipe (irrespective if you are in python2 or python3), would be able to detect python2-3 incompatibilities and report them to the package recipe creator, so they will be able to fix it and recipes would be reasonably compatible to both systems. Typically achieving compatibility on recipes is extremely easy: just avoid using print without parenthesis, use ``items()`` instead of ``iteritems()`` and some caution if handling strings.

**Comment by sztomi** [comment]
I see. I'd stay away from heuristics because that would introduce subtle incompatibilities. There is [py_compile](https://docs.python.org/3/library/py_compile.html) that could be used for this, but you'll need to run it with both interpreters. However, seeing that the Python2 EOL is just 3 years away from now, wouldn't it make sense to slowly move to Python 3?

**Comment by memsharded** [comment]
Yes, my vote would be to move to Python3, but unfortunately Python2 is so mainstream yet, and an EOL of 3 years is often disregarded in decisions today. So it will have to be very slowly indeed. But totally in our roadmap.

**Comment by memsharded** [comment]
I have been having another look into this, trying to get some tool that will output information about py2-3 incompatibilities. Seems like a difficult challenge, as for example pylint tools will only run in their respective Py2 or Py3 environments (virtualenvs), and it would be a bad idea imposing end users to have several environments to create packages, even if for example they are only interested in using python 2.7. 

So too much work for a relatively low gain (so far the system is working fine, it is not perfect, but easily manageable)

The rationale would be the same that for the PyPI, users can upload their code, supporting the versions they want (py2, py3 or py2-3), and it doesn't make a lot of sense to restrict them in the supported versions. If users of the library want support for their python versions, they can always contribute with a PR to the library.

So I suggest the same for conan: package creator are responsible to support the python version they want, the can work in py2 or py3, or test their recipes with both py2 and py3. It is up to them. Once they contribute their recipes to conan.io, if some other users want to provide support for other python version, for conan recipes it will typically be a very simple fix (some ``print``, some ``iteritems() => items()``, or some import), so they can collaborate with the package creator easily.

Looking forward to the python community evolving into python 3 only!

**Comment by sztomi** [comment]
After reading your reasoning, I can support this decision. This would indeed be really complex to implement.

**Comment by memsharded** [comment]
Good, thanks for your understanding!
