### ISSUE TITLE
[question] Does conan support Macos on ARM (ARM on Apple desktop) with xcode >=12

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#8113]
Today, we received [this bug report of an Apple developer](https://github.com/conan-io/conan-center-index/issues/3690) creating a x86_64 executable instead of an arm when wanting to natively building an arm application.

I think this is because `clang` builds x86_64 executabled by default and conan does not add the correct `CFLAGS/CXXFLAGS/LDFLAGS`.

I think conan needs to add the correct flags.
After googling a bit I found the following page: https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary

The example shows the following lines:
```
x86_app: main.c
    $(CC) main.c -o x86_app -target x86_64-apple-macos10.12
arm_app: main.c
    $(CC) main.c -o arm_app -target arm64-apple-macos11
```
So maybe `-target {ARCH}-apple-os{VERSION}` must be added (automatically)?

I don't own anything apple, so there's nothing more I can tell or debug.

**Comment by SSE4** [comment]
I think we do automatically adjustments for CMake build helper, but not for the AutoToolsBuildEnvironment helper right now, that's the problem. there are two flags are usually needed for iOS/watchOS/tvsOS : `--isysroot` and `--arch`. I believe that's the same for ARM Macos.

**Comment by theodelrieu** [comment]
I've built our entire project on macOS ARM, and here's the main problem I've encountered:

## No way to differentiate armv8 iPhone / Simulator

Up until now, Conan Apple helpers made the distinction based on `arch`. If there was `x86`, it was a simulator. Simple.

This is over now, because it can also be `armv8`. The workaround I've used is simply providing the `sdk` parameter in `tools.XCRun`.

But it did not help when I tried distributing simulator packages, because there is no setting that models the targeted XCode SDK, thus the package IDs will be the same.

I propose to add a `self.settings.os.sdk` subsetting, when `os == "iOS"`, with values `[None, iPhoneOS, iPhoneSimulator]`.

`None` will be valid only when `arch != "armv8"`.

**Comment by SSE4** [comment]
@theodelrieu are arm64 simulator and arm64 iPhone binaries actually different?
I suspect arm64 simulator might be able to run the exactly same binaries as iPhone runs, so it's very possible they should render into the same package id.
maybe if you could try to build some dummy .a files, we can compare

**Comment by theodelrieu** [comment]
@SSE4 No they are different, you cannot link both together, the error looks like:

>building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

**Comment by theodelrieu** [comment]
Also, when doing a native build, Conan will say that we are cross-building from x86_64 to armv8.

**Comment by rconde01** [comment]
@theodelrieu I saw this but this was before I tried the native m1 conan build that wasn't available until later...which are you using?

**Comment by madebr** [comment]
Have you set `arch=arch_build=armv8` in your profile?

**Comment by theodelrieu** [comment]
@rconde01 

I don't understand, I am using a M1 right now 😅 

@madebr 

I'm trying to use the dual profile approach, and not using/setting `arch_build/os_build`

**Comment by rconde01** [comment]
@theodelrieu but you could be using x86_64 conan emulated, or running natively on m1. I don't know for sure, but i maybe guessed it would think it's cross-building because the conan build architecture was x86_64. But i guess in that case, i'm not sure what the build_arch in the profile is for.

**Comment by theodelrieu** [comment]
@rconde01 

Ah right there's that Rosetta stuff. I'm using arm64 native tools though so I don't know where the `x86_64` comes from in the log output.

By the way, when invoking Conan for the first time, it will detect the arch to be `arm64`, which is not in in the `settings.yml`. I had to manually patch it to `armv8`.

**Comment by SSE4** [comment]
thanks for the information @theodelrieu 
I think now it's clear that conan needs to distinguish iOS arm64 builds and iOS Simulator arm64 builds, as they are really different binaries, thus they should render into different package ids ideally. but unfortunately, with current settings, it's impossible to explain the difference. there are several ways how it could be done, for instance:
- add new OS values, e.g. `[iOSSimulator, tvOSSimulator, watchOSSimulator]`
- add `os.sdk` subsetting matching Xcode naming, e.g. `[iPhoneOS, iPhoneSimulator, Macosx, WatchOs, WatchSimulator, tvOS, tvSimulator]`

the second might be less breaking for the existing packages, if we provide backward binary compatibility for `os.sdk=None`. (e.g. package with `arch=armv7`, `os=iOS` and `os.sdk=None` will match package id for `arch=armv7`, `os=iOS` and `os.sdk=iPhoneOS`).

as a side note, there are a couple of secondary issues, which should be trivial to fix:
1. probably, `detected_architecture` reports the wrong value for `Apple M1`. it would be helpful if M1 users provide their outputs of `uname -a` and `config.guess`
2. probably `get_cross_building_settings` also misdetects the architecture

**Comment by theodelrieu** [comment]
>it would be helpful if M1 users provide their outputs of uname -a

Darwin Marvins-Mac-mini.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64

>and config.guess

How can I find this?

**Comment by theodelrieu** [comment]
Here's the list of all Apple platforms (available at `/Applications/Xcode.app/Contents/Developer/Platforms`):

* AppleTVOS.platform
* AppleTVSimulator.platform
* MacOSX.platform
* WatchOS.platform
* WatchSimulator.platform
* iPhoneOS.platform
* iPhoneSimulator.platform

SDKs bare the same name, with the `.sdk` suffix instead of `.platform`.

**Comment by theodelrieu** [comment]
Another thing, the `apple_deployment_target_flag` tool must return `-mios-simulator-version-min`, otherwise it will fail to link.

**Comment by SSE4** [comment]
> > and config.guess
> 
> How can I find this?

https://raw.githubusercontent.com/gcc-mirror/gcc/master/config.guess

**Comment by theodelrieu** [comment]
@SSE4 Thanks, here it is: aarch64-apple-darwin20.1.0

**Comment by SSE4** [comment]
this probably triggers `arm64` to be incorrectly detected as `x86_64`:
https://github.com/conan-io/conan/blob/58dd8268d94f27f49a50b4f155c45c1c05476d44/conans/client/tools/oss.py#L98
as there is no branch for `arm64`

**Comment by cr-shaharnissinboim** [comment]
Hello guys, sorry for commenting on a closed issue, I also stumbled upon the failure in creation an arm64 package (cross-build on my "intel" macOs)
I was wondering, is there's some workaround to the issue that the created package is x86? and not arm64 (as stated in the conaninfo.txt)? or only waiting for the next conan release? 

Thanks!
