### ISSUE TITLE
[bug] `tools.cross_building` returns true when `arch == arch_build`

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#8119]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 11.0
  * Compiler+version: Xcode 12.2
  * Conan version: 1.31.4
  * Python version: 3.9.0

### Steps to reproduce (Include if Applicable)

I'm updating my build system to support building fat arm64+x86_64 binaries for MacOS. In order to do that, I've created a `macos_fat` architecture in my settings.yml for both `arch` and `arch_build` (I still haven't found time to migrate to new profile:build and profile:host syntax).

Now, when creating a simple profile with contents:

```
[settings]
os=Macos
os_build=Macos
arch=macos_fat
arch_build=macos_fat
compiler=apple-clang
compiler.version=12.0.0
compiler.libcxx=libc++
build_type=Release

[options]

[build_requires]

[env]
CONAN_CMAKE_GENERATOR = Xcode
```

and creating my package with `conan create ./conanfile.py user/testing -pr macos-fat`, I get the following output:

```
Configuration:
[settings]
arch=macos_fat
arch_build=macos_fat
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Xcode
...
**Cross-build from 'Macos:x86_64' to 'Macos:macos_fat'**
```

The package is created correctly (I do have fat binaries there), but check `if tools.cross_building(self.settings):` in my `test_package/conanfile.py` passes, which causes wrong package tests to be executed.

Shouldn't `tools.cross_building` return `False` if `arch == arch_build`?

**Comment by memsharded** [comment]
Hi @DoDoENT 

I am doing some quick unittest, and so far it is working fine:
```python
    def test_custom_architecture(self):
        settings_yml = textwrap.dedent("""
            os_build: [Macos]
            os: [Macos]
            arch: [x86, x86_64, macos_fat]
            arch_build: [x86, x86_64, macos_fat]
            """)
        settings = Settings.loads(settings_yml)
        settings.os = "Macos"
        settings.os_build = "Macos"
        settings.arch = "macos_fat"
        settings.arch_build = "macos_fat"
        self.assertFalse(cross_building(settings))
```

Any suggestion? I might try do something more integration-test, but so far no idea where the bug could come from.

**Comment by DoDoENT** [comment]
It's possible that what I see is the side-effect of some other bug. I'll try creating a reproducible sample during the weekend or next week (I reported this quite in a hurry..., not as I usually do 😉 ). Maybe while creating the sample I'll discover what is causing this. Let's keep this open until then...

**Comment by memsharded** [comment]
> It's possible that what I see is the side-effect of some other bug. I'll try creating a reproducible sample during the weekend or next week (I reported this quite in a hurry..., not as I usually do 😉 ). Maybe while creating the sample I'll discover what is causing this. Let's keep this open until then...

Sure! I will also try to reproduce in my end with an integration test.

**Comment by DoDoENT** [comment]
Here is the reproducible case: [conan-cross-compile.zip](https://github.com/conan-io/conan/files/5615424/conan-cross-compile.zip)

- unzip `conan-cross-compile.zip`
- install provided config `conan config install config.zip`
- create provided conan package with `conan create ./conanfile user/testing -pr macos-xcode-fat-clang-12.0.0`

Package build fails because `tools.cross_building(self.settings)` returns `True` (package build throws exception if that is `True`.

Here is the complete output from my laptop:

```
[dodo@knight-rider: conan-cross-compile]$ export CONAN_USER_HOME=$PWD/tmp
[dodo@knight-rider: conan-cross-compile]$ conan config install ./config.zip 
Unzipping 6.0KB
Unzipping 100 %                                                       
Installing settings.yml
Copying file macos-xcode-fat-clang-12.0.0 to /Users/dodo/Desktop/conan-cross-compile/tmp/.conan/profiles
Copying file macos-generic-xcode-fat to /Users/dodo/Desktop/conan-cross-compile/tmp/.conan/profiles
[dodo@knight-rider: conan-cross-compile]$ conan create ./conanfile.py user/testing -pr macos-xcode-fat-clang-12.0.0
WARN: Remotes registry file missing, creating default one in /Users/dodo/Desktop/conan-cross-compile/tmp/.conan/remotes.json
Auto detecting your dev setup to initialize the default profile (/Users/dodo/Desktop/conan-cross-compile/tmp/.conan/profiles/default)
Found apple-clang 12.0
Default settings
	os=Macos
	os_build=Macos
	arch=x86_64
	arch_build=x86_64
	compiler=apple-clang
	compiler.version=12.0
	compiler.libcxx=libc++
	build_type=Release
*** You can change them in /Users/dodo/Desktop/conan-cross-compile/tmp/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
Test/0.1.1@user/testing: A new conanfile.py version was exported
Test/0.1.1@user/testing: Folder: /Users/dodo/Desktop/conan-cross-compile/tmp/.conan/data/Test/0.1.1/user/testing/export
Test/0.1.1@user/testing: Exported revision: 5d1703778765bdc3263a3ef07d3b4dbc
Configuration:
[settings]
arch=macos_fat
arch_build=macos_fat
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Xcode
Test/0.1.1@user/testing: Forced build from source
Installing package: Test/0.1.1@user/testing
Requirements
    Test/0.1.1@user/testing from local cache - Cache
Packages
    Test/0.1.1@user/testing:66ab9ff2ce24c1402e4dda45bdc593c1eeeb6f2f - Build

Installing (downloading, building) binaries...
Test/0.1.1@user/testing: Configuring sources in /Users/dodo/Desktop/conan-cross-compile/tmp/.conan/data/Test/0.1.1/user/testing/source
Test/0.1.1@user/testing: Building your package in /Users/dodo/Desktop/conan-cross-compile/tmp/.conan/data/Test/0.1.1/user/testing/build/66ab9ff2ce24c1402e4dda45bdc593c1eeeb6f2f
Test/0.1.1@user/testing: Generator cmake created conanbuildinfo.cmake
Test/0.1.1@user/testing: Calling build()
Test/0.1.1@user/testing: 
Test/0.1.1@user/testing: ERROR: Package '66ab9ff2ce24c1402e4dda45bdc593c1eeeb6f2f' build failed
Test/0.1.1@user/testing: WARN: Build folder /Users/dodo/Desktop/conan-cross-compile/tmp/.conan/data/Test/0.1.1/user/testing/build/66ab9ff2ce24c1402e4dda45bdc593c1eeeb6f2f
ERROR: Test/0.1.1@user/testing: Error in build() method, line 12
	raise Exception('Cross building not supported!')
	Exception: Cross building not supported!
```

**Comment by memsharded** [comment]
Hi @DoDoENT!

I have investigated this, and finally understood what is happening!

The ``tools.cross_building()`` take the information from the ``conanfile=self``. As your ``conanfile`` is not declaring settings ``os_build`` or ``arch_build``, those values are being completely ignored, and the helper functions will take the current detected platform. If you want ``tools.cross_building()`` to return False, you need to define:

```python
class Pkg(ConanFile):
    settings = "os", "arch", "os_build", "arch_build", ...

   def package_id(self):
        # remember that ``os_build`` and ``arch_build`` are discarded by default from package_id
```

This will be way more explicit when using the profile-build and profile-host explicitly, as no auto-detection will ever be done. The new tools, prepared for Conan 2.0 (that will soon start to be available in ``from conan.tools....`` (Note it is not "conans", but "conan"), will be ready for using both profile-build and profile-host, and will not process anymore ``os_build`` and ``arch_build``.

**Comment by memsharded** [comment]
Hi @DoDoENT 

As commented above, this is not a bug, the feature requires to define ``settings = "os", "arch", "os_build", "arch_build"``. Either add them or use ``profile:build`` and ``profile:host``. I think this issue can be closed now, do you agree? Thanks!

**Comment by DoDoENT** [comment]
Yes, sorry, I forgot to close that. Your suggestion works flawlessly. Thank you!
