### ISSUE TITLE
Removing an uploaded package?

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#812]
I made a typo in a [package](https://www.conan.io/source/xmlrcp-c/1.39.12/sztomi/testing) and I'd like to remove it from conan.io. I could not find a way to do this. Is there one?

**Comment by memsharded** [comment]
Sure, just:
```bash
$ conan remove Pkg/0.1@user/channel -r=conan.io
```

**Comment by sztomi** [comment]
oh I assumed that was for removing only locally. Thanks!
