### ISSUE TITLE
[feature] conan config install from a conan package

### ISSUE THREAD

**Issue by peter-moran** [conan-io/conan#8120]
[`conan config install` currently supports getting configs from a git repository, local file or folder or zip file (local or http)](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#). I would like to be able to do this from a conan recipe.

Why? Because I would like to use conan to manage my dependencies but find that I am instead using git for my configs. This is particularly annoying with managing credentials in Docker -- I need Docker to have access both to an external git remote and a conan remote. Having everything in the conan remote would be easier and I think it makes some sense to manage the dependencies of my conan project using conan! It would also allow for versioning.

I figure I could probably home-spin this myself by making a conan package for my conan configs, installing them, and then using `conan config install` on the directory they were installed, but that seems more messy.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @peter-moran 

Yes, this totally make sense, and it is not the first time that it has been requested. Surprisingly I have been looking for an existing issue and couldn't find this, so lets use this one.

The only problem I see is that we are starting with Conan 2.0 and the load is very high, and this seems it is a great new feature, but not super critical, I am not sure when it is going to be possible to push it into development. Shouldn't be very difficult too, so I am labeling it, in case some contributor wants to give it a try.

**Comment by solvingj** [comment]
I agree with everything said here, and also want to add some additional points which were not mentioned. 

When working on the general problem of reproducibility of builds with Conan, there are multiple states which all must be reproduced in order for Conan to deliver reproducibility:

- Environment state (IE. docker image, virtual machine image, build machine)
- Conan configuration state (`conan config install`)
- Conan package state (`lockfiles`)

Some people run `conan config install` while building their environment state (for example, as part of `docker build`),  however many others do `conan config install` at the start of every job.  However, this means that while working very hard to guarantee reproducibility and predictability of builds with the `lockfiles` feature, one commit to the configuration repository could potentially introduce a new value into every conan build which follows it, and in such a way that becomes very difficult to track, and undermines the use of lockfiles.   

Stepping back, we can say that the GIT commit hash of the configuration repository represents a piece of state which is fundamental to Conan's ability to reproduce builds.  It can profoundly affect binaries, but is not tracked by the Conan package ID or recipe revision system (although it would produce new binary package revisions, but that's not really what we would want).  

The simple idea of putting this state in a conan package seems logical and straightforward.  As stated, it would allow versioning, and even revisions of configurations, which could then hopefully also propagate that to affected package revisions downstream. 
Obviously, it  would not be feasible to reference it in every package, so then it becomes something like `build_requires` where it's an implicit dependency of all packages in the graph. 

However, fundamental questions start popping up immediately, so to me it doesn't seem simple.  I think it requires some fundamentally new plumbing in the Conan initialization process.  For example, there are numerous bootstrap questions.  `build_requires` are defined in `profiles`, but a `configuration package` might likely aims to provide all the profile, so there's a question there.  Also, `conan config install` is often used to define the remote in `remotes.txt` which Conan will need to install any custom packages at all.  So, how does Conan find and install the package with it's configuration if it doesn't have the configuration needed to find and install them?  There are other similar bootstrapping questions surrounding `conan.conf`. 

I actually think most of the challenges can be overcome, perhaps by limiting this mechanism to installing only `settings.yml` and `profiles` and `hooks`, but not `remotes.txt` and `conan.conf`.  Or maybe it can do everything, but with some significant rework on the Conan client startup.  Or, there might be some pretty counter-intuitive problems related to this which cannot be resolved no matter what.  Like, for example, if in end, if the best solution is to "pre-install" some configs for bootstrapping, and then "runtime-install" the second set of configs... is it worth it or is it just more complex?

Anyway, I agree and support the investigation moving forward, I just wanted to raise questions and suggest a second look at the `complex: low` tag.

**Comment by AbrilRBS** [comment]
https://github.com/conan-io/conan/pull/15748 has now been merged to be released in 2.2.0, which will allow for just the request feature, feel free to explore it and give us feedback! :)
