### ISSUE TITLE
[feature] Separate actions of "resolve graph" and "download sources" from "install"

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#8121]
I'm exploring numerous strategies for performing debugging of applications from Conan packages.  When debugging, debuggers look for sources.  Currently, it's possible to point debuggers to sources in Conan cache (although we would like to improve this experience).  However sources for a given package are only downloaded by Conan when it does a `--build` of that package.  For the debug case, we want to be able to instruct Conan to obtain the sources, without having to actually rebuild the artifact.  So, something like `--fetch-sources ` which probably could have similar behavior as `--build` in terms of supporting `all` or a name of a package or a list.  Ideally, this would support all three SCM strategies (`source()` , `exports_sources`, `scm`)

In summary, when dealing with large numbers of binary packages which have non-trivial build times (`boost`/`qt`/etc), CI can pre-build debug binaries which would be usable, but Conan won't download the sources with them, so users are effectively forced to rebuild all the binaries, or modify the `package()` to capture all the sources as part of every binary package (which again, is highly undesirable for large dependencies like `boost`/`qt`/etc).  

There are definitely a few nuances with this simple request, which is probably why the problem is yet unresolved despite people recognizing and dealing with this inefficiency for a long time.  Currently, it is known that in some recipes, sources are generated or patched or downloaded in the build method. Those modified sources would only be locatable in the `build` directory, which won't exist yet if we simply perform the operations to `fetch-sources`.   Handling this case is certainly more challenging, but the feature should be able to proceed without solving that particular case right away. 

-- Edit - 20210517

Based on comments (https://github.com/conan-io/conan/issues/8121#issuecomment-842386368 and https://github.com/conan-io/conan/issues/8121#issuecomment-842399342) I've changed the title and clarified some details about the request.  In summary, even before fetching sources, we should be able to resolve the graph independently for generators to run, conan info command to work, and for the graph to be rendered into html. None of this requires sources, let alone binaries to be downloaded. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This might be doable, I have checked the code, and seems possible without a huge effort. Let's consider this while developing Conan 2.0.

**Comment by petermbauer** [comment]
I have a different use-case but would also like to just retrieve the sources when using the `scm` attribute, ideally into the user space.

**Comment by solvingj** [comment]
Thanks @petermbauer , if you would be willing to elaborate upon your use case, it might help inform the feature development. Please feel free to add if you like.

**Comment by petermbauer** [comment]
Sure, thanks for the reply. We would just like to make the source files together with some binaries available for the testing departement coming from a Conan Package in the Artifactory.

**Comment by jiladahe1997** [comment]
Same question here, I just want to retrieve source code for debugging.

**Comment by f18m** [comment]
same use case also for me, I would like to have a way to retrieve only source code. I'm going to hack the "package()" function for now but it would be wonderful to have this feature done in the proper way in Conan 2.0

**Comment by KerstinKeller** [comment]
I am not sure if this fits 100% to this issue, but may be related: I would be great to do either a
`conan install --no-binary -g some-generator` 
or a 
`conan lock create conanfile.py -g some-generator`
so that I can run a generator without actually downloading the binaries.

(some of our generators produce information which we need, even if we don't want to build the package). These could be (for example) the system requirements needed to build that package.
However I am not sure if that would work for all generators, since some generators might need to list files of the binary package or similar.

**Comment by solvingj** [comment]
I'm changing the title to be more generic and cover more cases related to the fundamental need. 

I think there's 2 things here:
1.  "resolve a graph" is a useful-enough thing to do to optimize it and expose it as a "discreet operation"
    * Does not necessarily require sources, but does require `exports` for `conandata.yml`
2.  "obtain sources for a graph" is a useful-enough thing to do to optimize it and expose it as a "discreet operation"
    * Depends on item 1

**Comment by solvingj** [comment]
@KerstinKeller after discussion with @memsharded , here is some new information:

1. conan info command resolves the graph completely, and this does not require download of binaries
2. Unfortunately, there's another fundamental issue blocking the generator-without-binaries use-case.  With the current design of Conan, Generators hard-require the binaries to be downloaded, because the `package_info()` method currently requires the package directory to exist for multiple reasons (some non-obvious implementation details).  

The result is that, for generators to run, you must fully install the packages (with binaries), and this will not change any time soon.

**Comment by memsharded** [comment]
Conan 2.0 beta9 is finally getting a new way of getting sources of all dependencies: https://github.com/conan-io/conan/pull/13003

This will allow forcing the source() method even for ``conan graph info`` command.
Gathering the sources will be straightforward with a custom new deployer that iterates dep.source_folder. So I am closing this ticket as implemented for 2.0b9, please try when released, thanks!
