### ISSUE TITLE
[bug] "conan install .." not working in pwsh

### ISSUE THREAD

**Issue by RefusesNames** [conan-io/conan#8123]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Version 2004
  * Compiler+version: 
  * Conan version: 1.31.4 and 1.30.2 (just checked if this problem was from a new version)
  * Python version: ? (used binaries from scoop)

### Steps to reproduce (Include if Applicable)
Follow steps [here](https://docs.conan.io/en/latest/getting_started.html) until `conan install ..`.

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
conan install ..
'[path to my conan.exe]/conan.exe' is not a Conan command. See 'conan --help'.

ERROR: Unknown command '[path to my conan.exe]/conan.exe'
```

### Additional Information
This might not be a problem with Conan, but the Powershell. The problem can be solved via `conan install ./..` (note the `./..` instead of `..`). I just thought this should be documented somewhere.

**Comment by memsharded** [comment]
I am using ``conan install ..`` in a Powershell terminal and seems to work fine. Could it be that binary from scoop?
I am using Conan with ``pip install conan``. Could you try that? Maybe this is something that should be reported to the scoop package maintainers (we don't create that package ourselves)

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you in a while. If anyone thinks that they are facing a similar problem, feel free to create a new issue, we're always happy to help :)
