### ISSUE TITLE
[question] how to have Conan package requires of conanfile.py automatically populated from its own conanfile.txt

### ISSUE THREAD

**Issue by f18m** [conan-io/conan#8128]
Hi,
I'm trying to build a microservice using C++ and Conan.
This microservice needs to link to (shared) libraries transported by Conan packages. Some of these Conan packages have other dependencies as well... E.g. my microservice depends on A,B   and conan package A depends on package C.

My understanding is that the "conan info -g mydeps.html" should be able to draw the chain of A,B,C dependencies for my microservice. However it stops at A,B.
The conanfile.py of package A is indeed missing any "requires" statement or "requirements()" python function. However it's getting its dependency libs from package C via conan, and indeed the package A has its own conanfile.txt file.

My question is: when I generate the Conan package for pkg A, can I tell Conan to list as its dependencies any Conan package written inside the conanfile.txt ?
Or shall I copy-paste the list of requirements inside the conanfile.py of pkg A? Then I need to keep two files in sync... 

Thanks!

**Comment by memsharded** [comment]
Hi @f18m 

Yes, if you are writing a ``conanfile.py`` my recommendation would be to completely forget and remove the ``conanfile.txt``. There is nothing that the conanfile.txt can do that the conanfile.py cannot implement. And you can use ``conanfile.py`` in any ``conan install`` command that you would use the .txt.

The ``conanfile.txt`` file format is intended for very simple consumer-only scenarios. If you are applying more logic (conditionals for example on the configuration), or if you want to create packages for that one too, then a ``conanfile.py`` becomes necessary, and it doesn't make any sense to maintain the ``conanfile.txt`` anymore, actually it is more confusing, so better remove it.

**Comment by f18m** [comment]
Hi @memsharded ,
thanks a lot fo clarifying this point!
Honestly that was not very clear in my opinion from the documentation. In section https://docs.conan.io/en/latest/using_packages/conanfile_txt.html it says "While you can install each of your dependencies individually like that, the recommended approach for handling dependencies is to use a conanfile.txt file." with no mention that you can actually use the conanfile.py to do that :)
Also the conanfile.py of the https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html chapter (https://github.com/memsharded/example_conan_flow/blob/master/conanfile.py) does not use Conan to resolve any dependency. The only reference to the "requires" attribute is perhaps in the example conanfile.py at https://docs.conan.io/en/latest/devtools/running_packages.html ?

My only doubt in removing the conanfile.txt and writing all requirements in the conanfile.py is that then all developers that need to bump dependencies along the tree of packages I have, will need to touch a Python file that whose 99% (basically everything except the requirements list) will not be changed.
I will try to actually have the conanfile.py read the requirements from the conanfile.txt... that would allow me to keep decoupled the required versions and the logic to create the conan package.

Do you think that it should work?

**Comment by memsharded** [comment]
> Honestly that was not very clear in my opinion from the documentation. In section

Yes, you are right. Going over the docs and re-writing some good parts of it, is in our TODO list. It is becoming challenging to put efforts on the docs besides incremental things, and sometimes reviewing and reading it from scratch is necessary.

> My only doubt in removing the conanfile.txt and writing all requirements in the conanfile.py is that then all developers that need to bump dependencies along the tree of packages I have, will need to touch a Python file that whose 99% (basically everything except the requirements list) will not be changed.

Well, if that is the case, and you are very sure nothing else is needed, you might want to use the ``conandata.yml`` associated file, create there are ``requires`` section and use in the recipe ``requirements()`` method. We are already using that file in ConanCenter to define the sources origin, and this could be a valid use case. You have an example here: https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html

**Comment by f18m** [comment]
> > Honestly that was not very clear in my opinion from the documentation. In section
> 
> Yes, you are right. Going over the docs and re-writing some good parts of it, is in our TODO list. It is becoming challenging to put efforts on the docs besides incremental things, and sometimes reviewing and reading it from scratch is necessary.
> 
> > My only doubt in removing the conanfile.txt and writing all requirements in the conanfile.py is that then all developers that need to bump dependencies along the tree of packages I have, will need to touch a Python file that whose 99% (basically everything except the requirements list) will not be changed.
> 
> Well, if that is the case, and you are very sure nothing else is needed, you might want to use the `conandata.yml` associated file, create there are `requires` section and use in the recipe `requirements()` method. We are already using that file in ConanCenter to define the sources origin, and this could be a valid use case. You have an example here: https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html

thanks the conandata.yaml is definitively what I need!

Thanks!
