### ISSUE TITLE
With modern CMake targets linkflags are not propagated correctly

### ISSUE THREAD

**Issue by tru** [conan-io/conan#813]
I have been using the new modern CMake targets and it's very clean and nice. Unfortunately it seems like the linkflags (sharedlinkflags and exelinkflags) are not propagated via this. Googling a bit it seems like CMake doesn't understand `INTERFACE_LINK_FLAGS`. We might need some kind of workaround here.

**Comment by memsharded** [comment]
I see, and yes, that is true, that is a limitation (IMHO an opinionated view) of CMake, that won't allow to define link flags on those targets. I think it could be workarounded adding the flags directly to INTERFACE_LINK_LIBRARIES (https://github.com/conan-io/conan/compare/develop...memsharded:feature/cmake_targets_linkflags?expand=1)

So if you could test my branch: https://github.com/memsharded/conan/tree/feature/cmake_targets_linkflags

@ruipires, @abuszta, @SSE4, if you could please also have a look at this issue, and check if that could be a workaround, that would be great. Thanks!

Another possible workaround could be to GET the INTERFACE_LINK_FLAGS property of the target, and apply it manually on the consumer side.

**Comment by SSE4** [comment]
I suppose it makes sense to fire PR or feature request against CMake to support INTERFACE_LINK_FLAGS

**Comment by tru** [comment]
@SSE4 sure that would be great for the future.

Btw - this ticket can be closed with 0.18.1 since it was fixed there with the workaround.

**Comment by memsharded** [comment]
We also proposed this fix for it here: https://github.com/conan-io/conan/commit/5021e4b0496198c2e7fd427ee03553179e265ee7, so included in the minor 0.18.1. Sorry we haven't managed to release it earlier.

**Comment by memsharded** [comment]
@tru, it is fixed, but not yet released 0.18.1. We have to wait to close the ticket until its release

**Comment by memsharded** [comment]
Released in 0.18.1, please update and re-open and report if necessary.

**Comment by SSE4** [comment]
@memsharded hi, after update to 0.18.1 I've got the following error on Windows:
19>LINK : fatal error LNK1104: cannot open file '\NODEFAULTLIB:LIBCMTD \NODEFAULTLIB:LIBCMT.obj'

digging down suggests that it's most likely from glew package which defines:
```
                if self.settings.compiler.runtime != "MT":
                    self.cpp_info.exelinkflags.append('/NODEFAULTLIB:LIBCMTD')
                    self.cpp_info.exelinkflags.append('/NODEFAULTLIB:LIBCMT')
```
and somehow slash got converted into backslash somewhere. inspecting conanbuildinfo.cmake I can see just the following:

```
set(CONAN_EXE_LINKER_FLAGS_GLEW "/NODEFAULTLIB:LIBCMTD /NODEFAULTLIB:LIBCMT")
```

any ideas?

**Comment by SSE4** [comment]
if anyone will encounter the same issue - I've applied workaround to the glew receipt to use dash rather slash, so it is:
``` 
               if self.settings.compiler.runtime != "MT":
                    self.cpp_info.exelinkflags.append('-NODEFAULTLIB:LIBCMTD')
                    self.cpp_info.exelinkflags.append('-NODEFAULTLIB:LIBCMT')
```

**Comment by memsharded** [comment]
Thanks @SSE4 for hints on this. So it seems then a package issue, not a conan issue, right? There are several ``glew`` packages in conan.io, I guess you are talking about https://www.conan.io/source/glew/2.0.0/coding3d/stable?

Did you submitted a PR or issue to their repo https://github.com/dimi309/conan-glew/issues? Maybe it is a good idea.

Actually I think that having to deal with Windows runtime libs might not be necessary if the settings are properly defined and managed, and the consumer project settings correctly match the dependency settings. Sometimes is a problem that the build system of the package is not handling at all ``self.settings.compiler.runtime``.

**Comment by SSE4** [comment]
@memsharded there is no issue in glew package, as both forms (-NODEFAULTLIB and /NODEFAULTLIB) are valid and accepted by Microsoft linker. I believe there is still an issue that slash converted into backslash somewhere inside Conan or CMake when processing linker flags.
yes, I am using forked version of glew/2.0.0@coding3d/stable.

**Comment by memsharded** [comment]
Thanks @SSE4 for the feedback, will open a new issue to track it.
