### ISSUE TITLE
[rfc] [v2] Managing options of requirements (Conan v2)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#8135]
(Copied from [here](https://github.com/conan-io/conan/pull/7993#pullrequestreview-540996090))

Consider a different approach to the `default_options` for requirements' options. I mean, we are used to recipes like:

```python
        from conans import ConanFile

        class LibC(ConanFile):
            requires = 'LibA/1.0'

            def configure(self):
                self.options['LibA'].myoption = False
```

What is the purpose of this statement (or the similar one `default_options = {'LibA:myoption': False}`)? To _force_ the value of the option of a requirement. What for? Many times it is because `LibC` doesn't compile unless `LibA` uses that value for that option.

What would be the consequences of deprecating the _set value of requirement_ in favor of _validate the final value_ (upcoming PR)?

```python
        from conans import ConanFile

        class LibC(ConanFile):
            requires = 'LibA/1.0'

            def validate(self):
                if self.options['LibA'].myoption == False:
                    raise ConanInvalidConfiguration("LibC requires LibA:myoption=True because ....")
```

The user will need to set the value of `libA:myoption` **explicitly** in the profile/cli or use a lockfile with the required value (like the test that is being modified here), I'm sure that the implementation and the option resolution would be much simpler,...

**Comment by SSE4** [comment]
what will be result of assert? `ConanInvalidConfiguration` or something else?

**Comment by jgsogo** [comment]
I'll change the comment, take that `assert` as a `if .... raise ConanInvalidConfiguration`.
