### ISSUE TITLE
Optionally? capture build log in package

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#814]
when you do:

conan install mypkg/x.x.x@me/stable --build

you potentially get output on standard out showing you the build. For traceability, it might be nice to capture that automatically into the package.

**Comment by memsharded** [comment]
Yes, I think it is a very good idea. Not sure if it should be optional, and how that optionality would be controlled. We also have to define about the capture, might not be possible without opt-in in ``self.run()`` without breaking existing behavior. 

I'd tentatively propose this feature for 0.19, as 0.18 is too close, let`s ask @lasote.

**Comment by lasote** [comment]
Definitely a good idea but not sure about the approach. I'm not sure yet but I think the output capture have to be global and activated/deactivated with an environment variable, maybe creating a log file in an specified directory or something like that. Something that a CI process can control globally.

**Comment by rconde01** [comment]
You could have conan launch another instance of itself and then capture the output from that.

**Comment by lasote** [comment]
Fixed. Merged in PR #884
Will be available in 0.19
