### ISSUE TITLE
[feature] add possibility to download/get conan_package.tgz binaries/artefacts outside conan world

### ISSUE THREAD

**Issue by Viatorus** [conan-io/conan#8146]
We use conan as package manager for your libraries und applications, you believe it?

Our final application contains something like this:

```python
def package(self):
        self.copy("*.elf", keep_path=False)
        self.copy("*.bin", keep_path=False)
```

So after uploading this package to the artifcatory I would like to have an option to download the `conan_package.tgz` to a destination other than the local cache in order to use is outside the conan world.

The nearest command I found is [`conan download`](https://docs.conan.io/en/latest/reference/commands/misc/download.html), but the destination is always local cache.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Viatorus 

You have different options:

- The Artifactory has a download API, you can directly get the URLs there and download them, as a regular file from the internet
- You have the deploy generator, use ``conan install mypkg/version@ -g=deploy`` and you will get a local copy of the artifacts in your local user folder
- Write a consumer ``conanfile.py`` or ``conanfile.txt`` with an ``imports()`` section, specifying exactly what files you want to extract and in which layout. Then execute ``conan install .`` for that file

**Comment by Viatorus** [comment]
Thank you! I didn't know about the deploy generator.
