### ISSUE TITLE
semver_direkt_mode not working as described in documentation

### ISSUE THREAD

**Issue by heili77** [conan-io/conan#8149]
Hi there,

I'm using conan 1.28.2 and I face an unexpected behavior in the package ids of my packages.
I've got multiple packages requiring each other D, E, F, G, H

In version 1.1.1 all packages have no requirements
in version 1.1.2 there are dependecies:
- G requires H/1.1.1
- F requires G/1.1.2
- E requires G/1.1.1
- D requires E/1.1.2 and F/1.1.2

In this constellation I have to resolve a conflict in D regarding G and I resolve to G/1.1.2 with the override flag.

I configured my conan installation with semver_direct_mode as default_package_id_mode.

When running install on Package D I get:
`ERROR: Missing binary: PackageE/1.1.2@*/*:095267f64b3a5d2ca4a99d91fbe6f41524251da4`
...
`- Dependencies: PackageG/1.1.2@*/*`
`- Requirements: PackageG/1.Y.Z`
`- Package ID: 095267f64b3a5d2ca4a99d91fbe6f41524251da4`

I did not find any information about "Dependencies" and how these affect the package id in the documentation of conan. It seem to me that the full version of G affects the package_id of E so conan results the wrong hash.

There is no implementation of the packag_id method in my recipes, so the defaults should be used.

When I set the requirement in E to G/1.1.2 the resulting package id matches and I get the install command working.

Is this behavior correct? This behaves not like I understand the documentation of semver_direct_mode

Edit:
I got this behavior also in version 1.16

**Comment by jgsogo** [comment]
Hi! I think I've reproduced here your graph of dependencies and scenario: https://github.com/jgsogo/conan-issue8149

As you can see, recipe `libD.py` contains your conflict, and it is resolved (using the overrides) in recipe `libDalt.py`.

Here it is the failure for `libD.py`:

```
+ conan info libD.py -n id
ERROR: Conflict in libF/1.1.2:
    'libF/1.1.2' requires 'libG/1.1.2' while 'libE/1.1.2' requires 'libG/1.1.1'.
    To fix this conflict you need to override the package 'libG' in your root package.
```

But, for `libDalt.py` everything is ok, no need to build `libE` again:

```
+ conan create libDalt.py libD/version@
Exporting package recipe
libD/version: The stored package has not changed
libD/version: Using the exported files summary hash as the recipe revision: 4e9b38789ceeea72eae30e29854d2964 
libD/version: Exported revision: 4e9b38789ceeea72eae30e29854d2964
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

WARN: libE/1.1.2: requirement libG/1.1.1 overridden by libD/version to libG/1.1.2 
libD/version: Forced build from source
Installing package: libD/version
Requirements
    libD/version from local cache - Cache
    libE/1.1.2 from local cache - Cache
    libF/1.1.2 from local cache - Cache
    libG/1.1.2 from local cache - Cache
    libH/1.1.1 from local cache - Cache
Packages
    libD/version:247737fc0b82ee67fd3cf1cc89066b2e91eace26 - Build
    libE/1.1.2:158d59d475bbab8f4c928f19615e43f76f1885ce - Cache
    libF/1.1.2:158d59d475bbab8f4c928f19615e43f76f1885ce - Cache
    libG/1.1.2:54bf0a6e5fb0645993d02aa67415ec1d77649eeb - Cache
    libH/1.1.1:f83037eff23ab3a94190d7f3f7b37a2d6d522241 - Cache
```

There must be something else in your recipes. Does it happen also if you use these very simple recipes? Thanks!

**Comment by heili77** [comment]
As I mentioned the conflict resolution is done in my example as you do it in yours. 
As far as I see the difference between your and my example is, that my G has no requirements in version 1.1.1 and a dependency to H/1.1.1 in version 1.1.2.
One cannot get this state without modifying G after version 1.1.1.

Edit:
In your example there is a
`ERROR: Conflict in libF/1.1.2:`
that can be resolved in D.
In my example I get a
`ERROR: Missing binary: PackageE/1.1.2@*/*:095267f64b3a5d2ca4a99d91fbe6f41524251da4`
This should not happen with the semver_direct_mode

**Comment by heili77** [comment]
Hi jgsogo,

I updated your example to get 
`ERROR: Missing binary: libE/1.1.2:...`

Edit:
I tested the adaption of your example with conan 1.32.0

**Comment by jgsogo** [comment]
Hi, @heili77 , I missed the line _"In version 1.1.1 all packages have no requirements"_ and that's the key point. Now I think the repository matches your scenario.

Running `conan create libDalt.py "libD/1.1.2@"` I get your same error. This is a know bug related to options in the transitive requirements (yes it bites even if the packages don't have options). **I'm going to open a PR to the docs documenting this bug**, it is something we cannot fix in Conan v1.x, there are too many users that might consider it breaking 😓

**Comment by heili77** [comment]
will this be fixed in conan 2?
Is there a workaround in conan 1?

**Comment by czoido** [comment]
Closed after merging: https://github.com/conan-io/docs/pull/1956

**Comment by heili77** [comment]
Hi there, 

unfortunately the bug is not only affecting the semver_direct_mode. I tried also with semver-, major- and unrelated_mode. The bug shows in all cases. 

In consequence each change in the count of the dependencies causes a behavior like a major-release and the versions need to be adapted in the whole dependency tree. With a fix of this bug all existing packages will not be found anymore, but in my case the rebuildung of all packages needs to be done once and is automated. Always treating changes in the packages as major-releases causes manual adaption in the whole team on every package change. 

Is there a workaround like excluding the options from the package_id (found nothing about that in the documentation) or an option I could set in may recipes to treat buggy packages differently? 

Is there a way to set the package_id in my recipe, like self.requires(mylib/1.0.0@u/c:<HASH>) or setting a attribute to mylib when configurating, instead of calculating it with the package_id method?

EDIT:
What about new versioning modes with a fix for the option bug. Those modes will change the IDs, but the old behavior is still available
