### ISSUE TITLE
Raise error for wrong build policy

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#815]
```bash
conan install .. --build=adsada
```
This will run without error, not sure of what is doing.

**Comment by lasote** [comment]
Well, it will build the nodes that matches `adsada` I think, so no nodes are being forced to build.

**Comment by memsharded** [comment]
Yes, sure, the problem is when you write a typo, it happened to me, like wrong case (boost instead Boost), and there is a package in the cache you want to rebuild, but it doesn't rebuild because of the typo, and you don't know.
