### ISSUE TITLE
[feature] Print git/svn status after upload failed because of uncommited changes

### ISSUE THREAD

**Issue by Nocccer** [conan-io/conan#8150]
**Feature:** Print out what git/svn status returns, if uploading of a package fails because of uncommited changes.

It happend on our CI (Jenkins) few times now that upload failed because of uncommited changes. 
We clear the whole repository folder after a build process to save storage. So we couldn't check it by ourself after the failed build.
To get the uncommited changes and fix them, we removed the clean workspace line from our Jenkinsfile and build it again. This can take alot of time for big projects. Would be nice if already conan print out which changes prevented the upload.

**Comment by jgsogo** [comment]
Hi! Yes, adding this information to the output can be useful. Nevertheless, I would say that this message belongs to the `conan export` step (it also runs in a `conan create`), it is the moment where the `scm` feature checks if there are local changes in order to substitute the `auto` keywords by the corresponding commit sha (is this your use case?).

This extra bit of information will be useful.

**Comment by Nocccer** [comment]
Yes we use scm with `auto` keywords. Print it in conan export would be fine for us, too.

**Comment by MariaMozgunova** [comment]
Can I take this issue? Is it still relevant to implement?

**Comment by Nocccer** [comment]
I didn't use conan for a while now. Still think it is always good to have more error/output information. Up to you, if this is still a good issue or makes no sense for the current conan version.

**Comment by memsharded** [comment]
The ``scm`` functionality is being superseded by the new (more explicit) tools described in https://docs.conan.io/en/latest/reference/conanfile/tools/scm.html.

I am going to close this issue as wont implement, and I'd recommend the following:
- Upgrading and checking the new tools
- If the new tools still exhibit this behavior, file a new issue describing the usage of the new tool

Thanks!
