### ISSUE TITLE
[feature] Be able to not set dependency option as opposed to setting it to default

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#8152]
Consider this scenario:
- Package `A` requires packages `B` and `C`
- Package `B` requires package `C`
- Package `C` has and option `someOpt`, with default value `val0`
- Package `A` does not care about `C:someOpt`
- Package `B` wants to set `C:someOpt` to some other value, `val1`

In the above scenario I have to set `C:someOpt` to `val1` in `A` in order to avoid building `C` with the default option. However `A` does not care about this option. If later on `B` decides it wants to use `val2`, `A` has to update its recipe to `val2`.

Q) Is my understanding accurate? There is no way currently to say `A` does not care about an option, is there?

My suggestion is to introduce a mechanism for consumers to say they don't care about a particular option (and possibly also to be able to say they don't care about any options not explicitly set).

- [✓] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Conan 2 changed how the ``package_id`` is computed, regarding dependency options.
Now, by default, dependencies options are never factored in into the ``package_id`` of the consumers.
So, for consumers it can be irrelevant the value, when there is no linkage (if there is linkage, the full ``package_id`` of consumers will be embedded, so it will always have some influence).

I am closing this ticket as solved, but please create a new ticket for any further question or issue. Thanks for the feedback.
