### ISSUE TITLE
[bug] Ignoring a CamelCaseFolderName when copying imports does not work

### ISSUE THREAD

**Issue by datalogics-kam** [conan-io/conan#8153]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 10.15.7 (and others)
  * Compiler+version: n/a, this affects imports only
  * Conan version: 1.31.4, 1.32.0, `develop`
  * Python version: 3.6.5

### Steps to reproduce (Include if Applicable)

- Have a project with a folder name with CamelCase
- Exclude the folder in `excludes` in `self.copy()` in `imports()`
- Expect the folder to be excluded; actually it is not.

Redacted example of a statement from our `conanfile.py` in the affected project:

```
    def imports(self):
        ...
        if self.options.include_pkg:
            self.copy('*', src='bin', dst='some/directory/path', root_package='pkg',
                      excludes=['some.files.*', 'somedll.dll', 'CamelCaseDirectoryToExclude'])
```

### Workaround 

Using `ignore_case=False` in the `self.copy` calls works for us.

### Suggested patch

This is a follow on to work done in #8009, and fixes the problem for us.

```diff
diff --git a/conans/client/file_copier.py b/conans/client/file_copier.py
index f4be404b..8fd0e600 100644
--- a/conans/client/file_copier.py
+++ b/conans/client/file_copier.py
@@ -144,7 +144,8 @@ class FileCopier(object):

             relative_path = os.path.relpath(root, src)
             for exclude in excludes:
-                if fnmatch.fnmatch(relative_path, exclude):
+                compare_relative_path = relative_path.lower() if ignore_case else relative_path
+                if fnmatch.fnmatch(compare_relative_path, exclude):
                     subfolders[:] = []
                     files = []
                     break
```

At this point, the `excludes` have all been lower-cased, and no longer match the filenames on the disk.

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/8155 will be released in 1.32.1 soon (maybe tomorrow)
