### ISSUE TITLE
[bug] conan new command overwrites files without warning or confirmation

### ISSUE THREAD

**Issue by dragondive** [conan-io/conan#8156]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux Mint 20
  * Compiler+version: NA [g++ 9.3.0]
  * Conan version: 1.31.1
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)
* Create a subdirectory `src` in any directory, then create a file `CMakeLists.txt` inside the `src` subdirectory and optionally edit it.
* Run the `conan new` command in the directory, for example: `conan new -s -t pkg/0.1@user/testing`
* Now the previous contents of the `CMakeLists.txt` have been overwritten, which may be unexpected behaviour for the user.

### Logs (Executed commands with output) (Include/Attach if Applicable)

File saved: conanfile.py
File saved: src/CMakeLists.txt
File saved: src/hello.cpp
File saved: src/hello.h
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/example.cpp

**Comment by memsharded** [comment]
While I kind of agree, I think now this change would break things like the Academy training, that uses the ``conan new`` command. As this is not critical, I suggest changing the behavior in Conan 2.0.

**Comment by memsharded** [comment]
Conan 2.0 command ``conan new`` will now stop if files are being overwritten, and offer ``--force`` to force it. Already released in latest 2.0 betas
