### ISSUE TITLE
[question] Retrieving package info when installed compiler does not support building it

### ISSUE THREAD

**Issue by JPGygax68** [conan-io/conan#8159]
Is there a way to get the info of a package when the machine you're on cannot build that package ?

For example, I tried to obtain the info of the `gmp` package but got:
`ERROR: gmp/6.1.2@bincrafters/stable: Invalid configuration: The gmp package cannot be deployed on Visual Studio.`

EDIT: the exact command I used was:
`conan info -r conan-center gmp/6.1.2@bincrafters/stable`

EDIT #2: a related question would be how the [conan website](https://conan.io/center/) builds its database?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @JPGygax68 

Yes, not it is possible, we have introduced in Conan 1.32 a new ``validate()`` method with exactly this purpose: if you try to install a package (or build it) it will raise an exception, but ``conan info`` will be able to retrieve the information as "INVALID" package. The main issue with this approach is that it is new, experimental, so recipes in ConanCenter have not started to use it.

To get basic information of any package you can use the ``conan inspect <pkg-ref>`` command, to display the basic recipe information (class members), or the ``conan get`` command to read the recipe.

In the ConanCenter we use the ``conan info`` command, and capture the error return code, which is documented and different to other returns codes (ConanInvalidConfiguration => 6) Is that what you mean?

**Comment by memsharded** [comment]
Also, please take into account that the maintained packages are the ones without user/channel, in this case ``gmp/6.2.0`` in https://conan.io/center/gmp.

**Comment by JPGygax68** [comment]
Thank you very much @memsharded . I wasn't aware of the `inspect` command and will try it tomorrow. (I had already tried `get` but trying to parse the python recipe was unreliable).

What I was trying to do was building my own database of Conan packages by using a combination of `conan search` and `conan info`. I'm going to replace the latter with `conan inspect` now.

**Comment by memsharded** [comment]
Good, the ``conan inspect`` also has a ``json`` output argument that might help for automatic parse. Note, however that this command does not provide a fully evaluated package, just the basic parsing of the recipe and class attributes.  

I'll keep this issue open until you try and report tomorrow if ``inspect`` is good for your case. Thanks!

**Comment by JPGygax68** [comment]
I've now adapted my code to use `conan inspect` and it works; it is exactly what I was looking for.

Two things though:

1. the `--raw` option does not seem to work at all
2. the `--json` option can only output to a file, so there is no OS-independent way of obtaining the data by capturing the comand's output (via `popen()` or something similar). I was able to do it using `>nul --json con`, but that is non-portable. I ended up using the normal output (neither JSON nor "raw").

**Comment by memsharded** [comment]
Sure ``--raw`` doesn't work? Try:
```bash
$conan inspect zlib/1.2.11@ --raw=name
zlib
$ conan inspect zlib/1.2.11@
name: zlib
version: 1.2.11
url: https://github.com/conan-io/conan-center-index
homepage: https://zlib.net
...
```
yes, we are aware of the limitations and inconsistencies of the CLI arguments, and we are trying to improve it. It might need to wait until Conan 2.0, because right now it is very challenging to change the CLI without breaking.

**Comment by JPGygax68** [comment]
Thank you James, I see I misunderstood the way `--raw` is supposed to work. 

Best of luck with the rewrite!
