### ISSUE TITLE
[question] Migration from visual_studio generator to MSBuildDeps

### ISSUE THREAD

**Issue by hdnn** [conan-io/conan#8163]
When I used visual_studio generator, it make very useful property variable `Conan-***-Root` in `conanbuildinfo_***.props` file, but the new generator doesn't make it.
I have some number of `Utitlity` projects, which executes scripts using this variables. 
For example, I need to have path to some binary file to execute it in `Custom Build Step`. 
How I did it before:
```
$(Conan-grpc-Root)/bin/grpc_cpp_plugin.exe
```
How I am forced to do this now:
```
set plugins_bin_dir=$(ConangrpcBinaryDirectories)
set plugins_bin_dir=%plugins_bin_dir:;=%

%plugins_bin_dir%/grpc_cpp_plugin.exe
```
As I have only one variable with path to package with symbol `;` in the end of path, I copy it and remove `;`... looks terrible)

Is there a correct way to get path to a conan package?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I see. While the Root approach is a bit hacky, in the sense that it hardcodes the knowledge that the binary for that package is contained in the "bin" folder (modeled in ``cpp_info.bindirs => ConanxxxBinaryDirectories``), it is true that the solution is a bit more inconvenient, and still not 100% general, in the sense that it there were more than 1 bindirs, it would not be known in which one is the exe). I think the ``Root`` variable can be added to the generator.
