### ISSUE TITLE
[bug] simple validation script does not work anymore

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#8164]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04.1 LTS
  * Compiler+version: gcc 9.3.0
  * Conan version: 1.32.0
  * Python version: 3.7.9

### Steps to reproduce (Include if Applicable)
I have always used this script to validate a docker image creation:

mkdir -p /tmp/mypackage
cd /tmp/mypackage
conan new mypackage/1.0 -t
conan create . demo/testing

now it does not work

### Logs (Executed commands with output) (Include/Attach if Applicable)

+ mkdir -p /tmp/mypackage
+ cd /tmp/mypackage
+ conan new mypackage/1.0 -t
File saved: conanfile.py
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/example.cpp
+ conan create . demo/testing
Exporting package recipe
mypackage/1.0@demo/testing: A new conanfile.py version was exported
mypackage/1.0@demo/testing: Folder: /root/.conan/data/mypackage/1.0/demo/testing/export
mypackage/1.0@demo/testing: Exported revision: 0c385493e8e281a3b8d4c5bcb1adb888
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
*:shared=False
[build_requires]
[env]
mypackage/1.0@demo/testing: Forced build from source
mypackage/1.0@demo/testing (test package): Installing package
Requirements
    mypackage/1.0@demo/testing from local cache - Cache
Packages
    mypackage/1.0@demo/testing:8646734ee3e7fd5a9de3513cba5a40bc700a885d - Build
Installing (downloading, building) binaries...
mypackage/1.0@demo/testing: Configuring sources in /root/.conan/data/mypackage/1.0/demo/testing/source
Cloning into 'hello'...
mypackage/1.0@demo/testing: Copying sources to build folder
mypackage/1.0@demo/testing: Building your package in /root/.conan/data/mypackage/1.0/demo/testing/build/8646734ee3e7fd5a9de3513cba5a40bc700a885d
mypackage/1.0@demo/testing: Generator cmake created conanbuildinfo.cmake
mypackage/1.0@demo/testing: Calling build()
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan setting CPP STANDARD: 17 WITH EXTENSIONS OFF
-- Conan: Adjusting fPIC flag (ON)
-- Conan: Compiler GCC>=5, checking major version 9
-- Conan: Checking correct version: 9
-- Conan: C++ stdlib: libstdc++11
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
-- Build files have been written to: /root/.conan/data/mypackage/1.0/demo/testing/build/8646734ee3e7fd5a9de3513cba5a40bc700a885d
Scanning dependencies of target hello
[ 25%] Building CXX object CMakeFiles/hello.dir/hello.cpp.o
[ 50%] Linking CXX static library lib/libhello.a
[ 50%] Built target hello
Scanning dependencies of target greet
[ 75%] Building CXX object CMakeFiles/greet.dir/main.cpp.o
[100%] Linking CXX executable bin/greet
[100%] Built target greet
mypackage/1.0@demo/testing: Package '8646734ee3e7fd5a9de3513cba5a40bc700a885d' built
mypackage/1.0@demo/testing: Build folder /root/.conan/data/mypackage/1.0/demo/testing/build/8646734ee3e7fd5a9de3513cba5a40bc700a885d
mypackage/1.0@demo/testing: Generated conaninfo.txt
mypackage/1.0@demo/testing: Generated conanbuildinfo.txt
mypackage/1.0@demo/testing: Generating the package
mypackage/1.0@demo/testing: Package folder /root/.conan/data/mypackage/1.0/demo/testing/package/8646734ee3e7fd5a9de3513cba5a40bc700a885d
mypackage/1.0@demo/testing: Calling package()
mypackage/1.0@demo/testing package(): Packaged 1 '.h' file: hello.h
mypackage/1.0@demo/testing package(): Packaged 1 '.a' file: libhello.a
mypackage/1.0@demo/testing: Package '8646734ee3e7fd5a9de3513cba5a40bc700a885d' created
mypackage/1.0@demo/testing: Created package revision 0efe9890b66c95598184cfe79f11e4b8
mypackage/1.0@demo/testing (test package): Generator txt created conanbuildinfo.txt
mypackage/1.0@demo/testing (test package): Generator cmake created conanbuildinfo.cmake
mypackage/1.0@demo/testing (test package): Generated conaninfo.txt
mypackage/1.0@demo/testing (test package): Generated graphinfo
Using lockfile: '/tmp/mypackage/test_package/build/f8a83f7eb829b0aeb1c1e988d1ae973e3aff0a90/conan.lock'
Using cached profile from lockfile
mypackage/1.0@demo/testing (test package): Calling build()
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan setting CPP STANDARD: 17 WITH EXTENSIONS OFF
-- Conan: Compiler GCC>=5, checking major version 9
-- Conan: Checking correct version: 9
-- Conan: C++ stdlib: libstdc++11
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
-- Build files have been written to: /tmp/mypackage/test_package/build/f8a83f7eb829b0aeb1c1e988d1ae973e3aff0a90
Scanning dependencies of target example
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
/tmp/mypackage/test_package/example.cpp:1:10: fatal error: mypackage.h: No such file or directory
    1 | #include "mypackage.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/example.dir/build.make:63: CMakeFiles/example.dir/example.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/example.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
ERROR: mypackage/1.0@demo/testing (test package): Error in build() method, line 15
	cmake.build()
	ConanException: Error 2 while executing cmake --build '/tmp/mypackage/test_package/build/f8a83f7eb829b0aeb1c1e988d1ae973e3aff0a90' '--' '-j2'

**Comment by memsharded** [comment]
Thanks for the report. Indeed a bug, the ``conan new`` was improved to take into account the package name into the code (it helps in creating several packages with different names), but the case of using the hardcoded Github repo with "hello" was left out. It is being fixed in https://github.com/conan-io/conan/pull/8175, and released asap (1.32.1)

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/8175, will be released in 1.32.1 soon
