### ISSUE TITLE
[bug] tools.intel_compilervars_dict() not working

### ISSUE THREAD

**Issue by akleber** [conan-io/conan#8168]
### Environment Details (include every applicable attribute)
  * Operating System+version: CentOS 8
  * Compiler+version: Intel 16
  * Conan version: 1.32.0
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)
When using the tools.intel_compilervars_dict() function, the dict returned does not contain the expected values.
Expected is a dictionary with the environment variables set by the tools.intel_compilervars_command(). However all variable names have a prefix of "export " or "declare -x " (depending on the used shell).
Because the variable names are malformed, this dict cannot be used with tools.environment_append() as intended.

The problem also affects tools.intel_compilervars() which uses tools.intel_compilervars_dict() internally and also the CMake helper when used with a Intel compiler.

I beliefe the root cause is in env.env_diff() and the fix is quiet simple, I will provide a PR.

tools.vcvars_dict() is not affected as it does not use env.env_diff().

**Comment by memsharded** [comment]
Tool is deprecated now, closing this, please report against new tools as necessary.
