### ISSUE TITLE
[bug] cmake_find_package_multi generator does not work for Xcode and other multi config CMake generators on macOS/Linux

### ISSUE THREAD

**Issue by oliora** [conan-io/conan#8174]
CMake Package configs generated by `cmake_find_package_multi` Conan generator can not be used with multi-config CMake generator like Xcode. The generated config files contains only data for Release configuration in a way that makes impossible to build any other configuration.

## Example

My `conanfile.txt`:
```
[requires]
gflags/2.2.2

[generators]
cmake_find_package_multi

[options]
gflags:shared=True
```

After I run `conan install` the following CMake config files are created:
1. `gflagsConfig.cmake` - entry point and main logic, defines the "root" target `gflags::gflags`
2. `gflagsConfigVersion.cmake` - version
3. `gflagsTargets.cmake` - includes all configuration files
3. `gflagsTarget-release.cmake` - release configuration parameters, calls `conan_package_library_targets` to create "subtargets" like `CONAN_LIB::gflags_gflags_nothreads_RELEASE`

After this I can build my CMake-based project that depends on gflags but only in Release configuration. If I try to build it in Debug configuration then I get linker errors because no gflags library is given to the linker. And indeed if I inspect properties and targets that are created by the above CMake config files then I see that out of all four `gflags_LIBRARIES_xxx` properties only `gflags_LIBRARIES_RELEASE` is set and so `gflags::gflags` target property `INTERFACE_LINK_LIBRARIES` has only libraries for Release configuration.

This whole behavior is probably OK on Windows where (as far as I remember) configurations are not mixed because different configurations may be not ABI-compatible. On macOS and Linux the situation is different: it's absolutely normal to mix libraries build in different configuration during developing (E.g. I build my own components in Debug but all the 3rd party libraries in Release).

The possible fix is to utilize [`IMPORTED_LOCATION_<CONFIG>`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_LOCATION_CONFIG.html) and [`IMPORTED_CONFIGURATIONS`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_CONFIGURATIONS.html) target properties instead of the current approach. The benefit of the above properties is that CMake can failback to another configuration when it is applicable. I.e. use `IMPORTED_LOCATION_RELEASE` when `IMPORTED_LOCATION_DEBUG` is not available. I don't know how smart this logic on Windows but on macOS/Linux it works great.

With the proposed approach a set of "subtargets" provided to the `INTERFACE_LINK_LIBRARIES` property of the root target (`gflags::gflags`) is fixed and does not depend on the configuration. `gflagsTarget-<CONFIG>.cmake` does not create targets but just sets `IMPORTED_LOCATION_<CONFIG>`, `IMPORTED_CONFIGURATIONS`, and possibly other properties for each of the subtargets, something like:
```
set_property(TARGET CONAN_LIB::gflags_gflags_nothreads APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CONAN_LIB::gflags_gflags_nothreads PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libgflags_nothreads.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/libgflags_nothreads.dylib"
  )
```

This is the way that CMake uses when it exports targets. One can create a simple project and check what exactly CMake put into generated package config files.

### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 10.14.6
  * Compiler+version: Apple clang version 11.0.0 (clang-1100.0.33.17)
  * Conan version: 1.28.1
  * Python version: python3.8

UPD: I've researched the issue more deeply and have updated the title and description.

**Comment by memsharded** [comment]
Hi @oliora 

We have been using the ``cmake_find_package_multi`` generator in multi-config build systems like Visual Studio, without problems so far. Is this something specific for XCode? What is the error that happens if not specified? Can you please share error output?

If you also have some links or documentation (besides the obvious CMake help, that doesn't clarify much), that explains a bit more about this property? Thanks!

**Comment by oliora** [comment]
@memsharded please check the description - I’ve extended it with more comprehensive explanation of the issue

**Comment by memsharded** [comment]
Hi @oliora 

I am having a look and trying to understand the issue completely.

I am a bit confused about: 

> After this I can build my CMake-based project that depends on gflags but only in Release configuration. If I try to build it in Debug configuration then I get linker errors because no gflags library is given to the linker. And indeed if I inspect properties and targets that are created by the above CMake config files then I see that out of all four gflags_LIBRARIES_xxx properties only gflags_LIBRARIES_RELEASE is set and so gflags::gflags target property INTERFACE_LINK_LIBRARIES has only libraries for Release configuration.

I don't see that you are installing the Debug configuration as well. For as many configurations that you want to use, you need to install those configurations and binaries. That will populate the necessary DEBUG (or other) variables for the targets to start working:

```bash
$ conan install .  # will install Release, the default one
$ conan instal . -s build_type=Debug 
```
With the second call you will get the Debug binaries, as well as ``gflagsTarget-debug.cmake`` file that will contain the information about the Debug configuration, so you can switch from XCode or the build system. 

Is it possible that you are missing that step?

**Comment by oliora** [comment]
That’s quite what I’m telling. On Unix you don’t have to have the same configuration for everything because different configurations still ABI compatible. So all of my dependencies are build as release and it works just fine. And if I build gflags in Release without Conan then it works just fine with any of my configurations. The problem is in cmake multi generator itself. It’s implemented in a way that only make sense in Windows.

If I summarize this: cmake multi generator should allow to use a single package configuration in any build configuration of dependent project. CMake supports it (see my initial post) and so the Conan generator should do. I.e. it should be possible to build gflags in Release configuration and consume it as dependency in a project that is build in any configuration including Debug. That’s a very typical scenario on Linux/macOS.

**Comment by memsharded** [comment]
These generators ``cmake_find_package_[multi]`` are deprecated in 1.X (in favor of CMakeDeps+CMakeToolchain), and removed in Conan 2.0, closing this issue as outdated.

In any case, it is perfectly possible to consume packages built with another build type, just Conan needs to be aware of it, for example, if our current project is Debug, but we want the dependencies in Release mode, it can be done with:

```
conan install . -s build_type=Release -s &:build_type=Debug
cmake ... -DCMAKE_BUILD_TYPE=Debug
```
