### ISSUE TITLE
[bug] private dependencies cannot resolve conflicts

### ISSUE THREAD

**Issue by heili77** [conan-io/conan#8179]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: 
  * Conan version: 1.28.2
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)
In my dependencies I have a conflict in the requirements. As the current recipe results an executable I do not want to propagate the requirements and declared them private. 
When installing, I get a conflict error. When I make the requirement, that solves the conflict, public everything works fine, but I propagate dependencies unnecessarily and the users will have to solve unnecessary conflicts.

**Comment by memsharded** [comment]
> As the current recipe results an executable I do not want to propagate the requirements and declared them private.

Private requirements should be used only in very extreme cases when there is no other alternative. If you would like to understand why it is creating a conflict when it is declared private, then please specify how to reproduce it, copy here the dependency graph, the conanfiles, something so we can understand and reproduce the case.

If you are building an executable that is being used in the graph, shouldn't that be better a build-requires? Build-requires will not propagate information besides the package that uses them. Have you considered that? Why are you depending on an executable and it is not a build-require?

**Comment by heili77** [comment]
In a Constellation like this:

LibH 1.1.1 requires nothing
LibG 1.1.1 requires LibH 1.1.1
LibG 1.1.2 requires LibH 1.1.1
LibE 1.1.2 requires LibG 1.1.1
LibF 1.1.2 requires LibG 1.1.2
LibD generates the executable in requires LibE 1.1.2 and LibF 1.1.2, each with private=True
LibD has a conflict with LibG. This conlict cannot be resolved with  
`self.requires("libG/1.1.2", private=True, override=True)`

> ERROR: Conflict in libF/1.1.2:
    'libF/1.1.2' requires 'libG/1.1.2' while 'libE/1.1.2' requires 'libG/1.1.1'.
    To fix this conflict you need to override the package 'libG' in your root package.

By using build_requirements the conflict can also not be resolved.


The conan documention says:
> a dependency can be declared as private if it is going to be fully embedded and hidden from consumers of the package.

In my opinion in executables all static library dependencies should be set _private_ because they are "fully embedded" and should be "hidden from consumers of the package"  
I think build requirements are not the right way because this does not affect the package id of the resulting package

**Comment by heili77** [comment]
I created a repository for my example that generates the error
https://github.com/heili77/conan_issue_8179.git

**Comment by timblechmann** [comment]
i've been running into this issue, too:

```
    requires = [
        ("boost/1.74.0", "private"),
        ("libiconv/1.16", "private", "override"),
        ("libxml2/2.9.10", "private"),
    ]
```

gives me:
```
ERROR: Conflict in boost/1.74.0:
    'boost/1.74.0' requires 'libiconv/1.16' while 'libxml2/2.9.10' requires 'libiconv/1.15'.
    To fix this conflict you need to override the package 'libiconv' in your root package.
```

> If you are building an executable that is being used in the graph, shouldn't that be better a build-requires? Build-requires will not propagate information besides the package that uses them. 

i could use `build_requires` here (my dependencies are static libs that are implementation detail and not propagated downstream), but the problem persists:

```
ERROR: Conflict in libxml2/2.9.10:
    'libxml2/2.9.10' requires 'libiconv/1.15' while 'conanfile.py' requires 'libiconv/1.16'.
    To fix this conflict you need to override the package 'libiconv' in your root package.
```

i might also be missing something, but afaict `build_requires` simply has no means to `override`

**Comment by klimkin** [comment]
My understanding, that `build_requires` is not for build-only dependencies, but for _build context_. This makes more sense if you thing it from perspective of a cross-platform build:
* _Build context_ (`build_requires`) - machine where the package is compiled on and where build tools are running
* _Host context_ (`requires`) - machine where the package will be used

From this perspective, [Build requirements](https://docs.conan.io/en/latest/devtools/build_requires.html#build-requires) documentation looks misleading:
>  These could be dev tools, compilers, build systems, code analyzers, testing libraries, etc.

If package uses GTest, where to add it? For cross-platform build it will be _host context_, since the tests link with libraries built for _host_. So I would put it in `requires`. But since it's used for build only, I would mark it as `private`. Unfortunately, `private` has some other shortcomings https://github.com/conan-io/conan-center-index/issues/5003.

And yes, if you have conflicting packages in both `requires` and `build_requires`, then Conan is not able to resolve them at current version (1.34.1).

**Comment by heili77** [comment]
Hi @klimkin,

In my opinion GTest is a build requirement because it is static linked to a test executable. You deliver the test executable to the target system and do not link the test there. All other dependencies only used only by the test are also build requirements.

**Comment by klimkin** [comment]
@heili77 "build" profile builds for execution on the build machine. So if you are cross-building on x86 for arm, "build" profile will create x86 code. If GTest is in `build_requirements`, then it will be x86, while target library will be arm.
