### ISSUE TITLE
Conan server backup strategy

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#818]
Hi,

How can I backup the data and configurations of the conan server? Is it possible while conan is running? Or do I need to stop conan, copy/sync the data directory and start conan server again?
I run the server using conan from source and gunicorn.

Thanks!

**Comment by memsharded** [comment]
The configuration of conan_server is read-only, it is not modified by the server, it is not reloaded once the server is running, so it could be copied while the server is running.

The storage of packages is obviously r-w.

So, a bare copy wouldn't be safe, unless you completely stop the server. But I guess that some careful use of rsync could do a nice job without stopping the server (and providing eventual consistency). After all, it is just pure filesystem.

**Comment by claasd** [comment]
Hi, we are switching to artifactory with building backup support.

**Comment by memsharded** [comment]
I think this can be closed, no action required on our side. Thanks!
