### ISSUE TITLE
[bug] `conan info -g` giving three different results depending on order of packages in a recipe

### ISSUE THREAD

**Issue by foundry-markf** [conan-io/conan#8188]
Given a list of package references, I have been experimenting with getting the build order of said package using the Conan commands. I've read a few github issues that have suggested using `conan info -g out.dot` to do so.

Bear in mind that the list of package references could be anything, in particular, probably multiple versions of packages of interest in building.

My initial experiment was to list them in a conanfile.txt, under build requirements (was my first thought, but bear with me), and to my surprise, I got this error:

```
conan info -g out.dot .
ERROR: True
```

With a bit more experimentation, I've encountered two additional results, based on the _order in which I write the packages in the conanfile.txt_. This surprised me as I think of the text file version of recipes as declarative, so a change of behaviour by ordering of data was unexpected.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Pro
  * Conan version: 1.32.0
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
I have put all the repro steps into a public gist with a Windows batch file to run in a Python3 virtual environment: https://gist.github.com/foundry-markf/3441fa19cea9318e7f1bfb14c9658cae

It contains three recipes; one that doesn't give an error producing a dot file (*), one that gives a more meaningful error, and then the error "True" as mentioned above.

The output I see is
```
"Trying one set of ordering which created a dot file, although missing one of the zlib versions"
[build_requires]
zlib/1.2.8@
zlib/1.2.11@
libpng/1.6.37@
digraph {
        "libpng/1.6.37" -> "zlib/1.2.11"
        "createsdot_conanfile.txt" -> "zlib/1.2.11"
        "createsdot_conanfile.txt" -> "libpng/1.6.37"
}

"Trying another set of ordering that gives a reasonable error"
[build_requires]
zlib/1.2.11@
zlib/1.2.8@
libpng/1.6.37@
ERROR: Conflict in libpng/1.6.37:
    'libpng/1.6.37' requires 'zlib/1.2.11' while 'meaningfulerror_conanfile.txt' requires 'zlib/1.2.8'.
    To fix this conflict you need to override the package 'zlib' in your root package.

"Trying another set of ordering that gives a weird error"
[build_requires]
libpng/1.6.37@
zlib/1.2.11@
zlib/1.2.8@
ERROR: True
```

(*) One observation is that given two versions of zlib as input, only one appears in the build order. I suspect this is because Conan's dependency graph only ever wants a single version of a package (which is how I interpret the more meaningful error message).

I debugged Conan and found that the "True" exception is coming from [_conflicting_references](https://github.com/conan-io/conan/blob/develop/conans/client/graph/graph_builder.py#L279-L299) which returns either a bool or a string (or raises), and the exception is raised from [this call point](https://github.com/conan-io/conan/blob/develop/conans/client/graph/graph_builder.py#L247-L249) when a bool is returned as opposed a string message.

My questions are:
1) should I expect package ordering in the recipe to affect behaviour?
2) is it a bug in _conflicting_references that should raise (in both code paths) instead of returning a string?
3) for my initial intent, if I do have a list of packages that includes multiple versions of packages, how _can_ I determine the build order of all packages list through Conan's commands?

Thanks!

**Comment by memsharded** [comment]
Hi @foundry-markf 

> 1.should I expect package ordering in the recipe to affect behaviour?

Yes, the algorithm that computes the graph takes into account the order of declarations of requires. It is depth-first, and it is also greedy, it will not backtrack, nor will try to find a jointly-compatible solution. The order of declares induces a relative order of dependencies that will also be mapped to the order in which include-folders are passed and the order in which libraries are linked.

> 2. is it a bug in _conflicting_references that should raise (in both code paths) instead of returning a string?

Yes, it seems there is a bug, and there is a path that shouldn't happen, "True" should not be printed in the output

> 3. for my initial intent, if I do have a list of packages that includes multiple versions of packages, how can I determine the build order of all packages list through Conan's commands?

It is not fully clear what you are trying to do. What is the build order of zlib/1.2.8 and zlib/1.2.11? None? they are not connected. The build order can only be computed for a dependency graph, computed from one package, but it is not possible to put incompatible versions of the same package in the same dependency graph. If you want to build those packages, why not iterate them and do ``conan create --build=missing``?

**Comment by foundry-markf** [comment]
Hi,

Apologies for the slow reply.

Thanks for clarifying there is one bug at least.

> It is not fully clear what you are trying to do.

Yes, sorry about that. I intentionally left out my requirements, as I felt if I mentioned CI (which it is related to), the questions I wanted to ask might get lost.

So anyway, from our commit hooks, we can figure out paths changed for CI to work on. From that, we can figure out packages changed. From that, we can figure out versions of packages that will need to be be built (from conandata.yml files). However, from this list of packages that need to be rebuilt, if there are dependencies between them, I don't know the order to build them in to satisfy those dependencies.

My input described above was thus the list of package versions (described as references) that need to be built, and my goal was to ask Conan the order in which they needed to be built.

As you have pointed out, the dependency graph cannot cope with multipe versions of the same package. So I have rolled back to just looking at package names (deferring version expansion until after I know an order). But at that point, I don't believe I can use any Conan command to help me figure out a build order (as I at least need a version). Additionally, because I am looking at this from a different perspective to how commands generating a build order work (i.e. I don't have a top-most 'product' consuming packages - just a (potentially random) scattering of packages across the whole diverse package universe), it isn't going to work.

Additionally, I can't use `conan create --build=missing` because I don't want to run this on one machine, or even one OS, but farm it out to a node of build machines.

That's what I am currently. I don't believe there is a current Conan-CLI-centric method I can use to figure this out. Which is fine, I was just hoping there might be something I missed.

**Comment by foundry-markf** [comment]
Hi @RubenRBS, I just wanted to check which version of Conan a change for this has landed in, since it's reported as completed? Since https://github.com/conan-io/conan/issues/8188#issuecomment-743465926 indicates that there was a bug, I'm assuming there was a fix.

I couldn't see anything obvious in the recently closed PRs.

Thanks!
