### ISSUE TITLE
[question] package dependencies

### ISSUE THREAD

**Issue by OlegWorld** [conan-io/conan#8189]
Hello!
I've got the following problem:
Say, i have a package, named "package1", which consists of several components defined according to https://docs.conan.io/en/1.32/creating_packages/package_information.html#using-components
so, if i'm using the cmake_find_package generator, i have the following example components: package1::component1 and package1::component2
Next, i'm creating another package, named "package2" which depends on package1, but not on the whole package, but only on 
package1::component1. How can i tell conan, that my package depends only on package1::component1? I'm linking it in cmake like package1::component1, but the conan dependency is still on the whole package1.
Next, if i create the third package, which depends on package2, it links the whole package1, not only package1::component1, because in the conan-generated Findpackage2.cmake file it is stated something like:
```
set(package2_LIBRARIES_TARGETS "${package2_LIBRARIES_TARGETS};package1::package1")
set(package2_LIBRARIES "${package2_LIBRARIES};package1::package1")
```

What should i do to avoid those two lines in Findpackage2.cmake or to make them like
```
set(package2_LIBRARIES_TARGETS "${package2_LIBRARIES_TARGETS};package1::component1")
set(package2_LIBRARIES "${package2_LIBRARIES};package1::component1")
```
?
I've tried to set
```
def package_info(self):
        self.cpp_info.requires = ['package1::component1']
```
in the package2 conanfile.py, but the resulting Findpackage2.cmake is the same

- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @OlegWorld 

I think what you are posting works fine. There were some tests already, but I have added a new check for transitive dependencies in https://github.com/conan-io/conan/pull/8191, and seems to implement exactly your desired behavior. Please check the test and check again your local setup.

Indeed the key is exactly what you posted:

```python
def package_info(self):
      self.cpp_info.requires = ["top::cmp1"]
```

**Comment by OlegWorld** [comment]
Thank you for your support!
It seams, that i've been using a rather old version of conan. Installing the 1.32 version made everything ok.

**Comment by memsharded** [comment]
Ok, excellent then :)
Thanks for following up, this issue will be closed when the test is merged.
