### ISSUE TITLE
Provide conan windows executable as ZIP file

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#819]
Hi,

while the Windows installer is great for manual installation for users, for CI servers like jenkins it would be beneficial to have the same content as a zip package for automated install on build nodes.
Currently, I download the installer and zip the contents of 
> C:\Program Files (x86)\Conan\conan

Is it possible to provide such a ZIP file directly on release?

Thanks, Claas.

**Comment by memsharded** [comment]
Actually, we try to discourage the use of the installer, and strongly recommend the use of the python Pypi package, which also allows for better CI testing (it can be easily deployed to different virtualenvs with Py27 and Py3.X, inthe same machine). Any specific issue you won't use the pip package?

**Comment by memsharded** [comment]
Hi @claasd ,

Any feedback for this? I think the PyPI package should be used, and Win installer avoided as much as possible, I am more inclined to deprecate the Win installer, than creating new forms of distributing such installer. If PyPI package is not possible, I would just add a few lines to install and run from sources.

**Comment by claasd** [comment]
Hi, 
the main reason for this was that I wanted to deploy conan to our servers using Jenkins tools and keeping the tests servers as clean as possible, without even vcredist packages and without python installed. 

For now I installed python on all our servers. I still need to find a way how to upgrade conan an 20+ servers automatically without interfering with builds. 

but as the windows installer had some other issues (#820), currently this feature request can be closed as wontfix.

**Comment by memsharded** [comment]
Just my personal opinion: Installing python is not difficult and it is fast. I'd probably try to automate the installation of python + conan in the CI job scripts, per job. That would add a small (specially compared with C/C++ build times) increase in time, but could be convenient.

**Comment by memsharded** [comment]
So labeling as wont fix by now, and closing, but please tell or re-open again if necessary.

**Comment by claasd** [comment]
I just wanted to reply that python needs or installs a vcredist packages that we do not want on our testers, but I just found out python bundles the vcruntime.dll. So installing python to the workspace and installing conan via pip on every build might be the key. Keeps the servers clean too.

**Comment by memsharded** [comment]
Yeah, sounds good.
