### ISSUE TITLE
[bug] cmake_find_package(_multi) should do include(FindXXX.cmake) for its dependencies

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#8190]
Currently, the `cmake_find_package` use `find(XXX REQUIRED)` to look for its dependencies.
This clashes with the use of [`CMAKE_DISABLE_FIND_PACKAGE_<PackageName>`](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
This variable is useful for creating minimal packages.

---

A scenario that is impossible now, is the following:

Let's assume the following 2 packages:
- `PackageA`: is free standing. No dependencies.
- `PackageB`: depends on `PackageA`.

Now let's assume a consumer with the following cmake script:

```cmake
...

find_package(PackageA)
if(PackageA_FOUND)
  ...
endif()

find_package(PackageB)
if(PackageB_FOUND)
  ...
endif()

...
```

Because the `cmake_find_package(_multi)` generator uses `find_package(XXX REQUIRED)` internally,
it is impossible to disable finding PackageA, but still keep Package B available.

So running cmake as the following would fail:

```
cmake .. -DCMAKE_DISABLE_FIND_PACKAGE_PackageA=ON
```

---

As a fix, I propose the following:

inside the `cmake_find_package` generators, instead of doing `find_package(XXX REQUIRED)`, do the following:
```cmake
include(FindXXX.cmake)
if(NOT XXX_FOUND)
    message(FATAL_ERROR "PackageB requires XXX but cannot find it.")
endif()

```

/cc'ing @danimtb because he is a major contributor of the cmake generators.

**Comment by danimtb** [comment]
sorry, but I fail to understand the use case. If PacakgeB depends on PacakgeA there is no way you cannot require PackageA but at the same time require PackageB. Maybe you say that all requirements in this case are optional?

**Comment by memsharded** [comment]
I also have a question, what files should be included for ``_multi`` generator?
Because there is the ``xxx-config.cmake``, if you include it what happens with the ``xxx-config-version.cmake``? I guess that will not be used at all?

**Comment by madebr** [comment]
@danimtb 
You're correct in that `PackageA` and `PackageB` needs to be both available.
What I want to do is disable the expensive/big blob of code that is included when `PackageA` is available.

```
if(PackageA_FOUND)
  # expensive code
  target_sources(target ..)
  ...
endif()
```

@memsharded 
`xxx-target.cmake` files, generated by `install(EXPORT)` are mostly nothing more then `add(library STATIC IMPORTED)` and a glob include of `target-config-*cmake`.
So I **think** it can be replaced with a `include(xxx-config.cmake)`.
[If I'm reading the docs correctly](xxx-config-version.cmake), the `xxx-config-version.cmake` files are only used when doing a version selection.
I don't think the conan generator do such a selection?

**Comment by madebr** [comment]
Closing this as `cmake_find_package(_multi)` will get EOL'ed soon.

**Comment by memsharded** [comment]
Thanks for following up @madebr 

Yes, any relevant feedback for the CMake integration should go to CMakeDeps and CMakeToolchain.
BTW, CMakeDeps just got in develop branch a huge refactor, making it orders of magnitude easier to read its code, and that will help to evolve it.
