### ISSUE TITLE
[bug] dpkg-query: command not found

### ISSUE THREAD

**Issue by Da-LiFe** [conan-io/conan#8193]
We are planning to upgrade from conan 1.22.4 to 1.31.4, but we are facing an issue with the detection of the package manager in OSInfo() because the detection mechanism was changed:

https://github.com/conan-io/conan/blob/58dd8268d94f27f49a50b4f155c45c1c05476d44/conans/client/tools/oss.py#L180

We are running opensuse with the `zypper-aptitude` package installed. Therefore, both checks within OSInfo.with_apt() succeed when using the `SystemPackageTool`:

```
> which apt-get
/usr/bin/apt-get
> apt-get moo
   \\\\\
  \\\\\\\__o
__\\\\\\\'/_
```

However, `SystemPackageTool` cannot check for existing packages, because we don't have dpkg-query installed.

### Environment Details (include every applicable attribute)
  * Operating System+version:
PRETTY_NAME="openSUSE Leap 15.1"
  * Compiler+version:
gcc (SUSE Linux) 7.5.0
  * Conan version:
1.31.4
  * Python version:
Python 3.6.8

### Steps to reproduce (Include if Applicable)
call `conan install` for a package using `tools.SystemPackageTool().installed()`

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
> conan install CMake/3.10.3@3rdparty/stable

CMake/3.10.3@3rdparty/stable: Downloaded package revision ca498ea68f017bded5f04fa2a68ac0cd
/bin/sh: dpkg-query: command not found
CMake/3.10.3@3rdparty/stable: ERROR: while executing system_requirements(): required system package 'libcurl-devel' is missing
ERROR: Error in system requirements
```

**Comment by Da-LiFe** [comment]
For now, we are manually patching conan to resolve the issue. Maybe you would like to use this patch, too:

```patch
--- conans/client/tools/oss.py  (date 1607592396298)
+++ conans/client/tools/oss.py  (date 1607592396298)
@@ -182,8 +182,8 @@
             return False
 
         apt_location = which('apt-get')
-
-        if apt_location:
+        dpkg_location = which('dpkg-query')
+        if apt_location and dpkg_location:
             # Check if we actually have the official apt package.
             try:
                 output = check_output_runner([apt_location, 'moo'])
```

**Comment by czoido** [comment]
Hi @Da-LiFe,
I think it would make sense to add some extra checks to make sure that the tool we are using to get the installed packages is available.
Thanks a lot for reporting!

**Comment by Trompettesib** [comment]
Hello,
What is the state of this issue right now ?
I have some trouble on Fedora 30.
Thanks !

**Comment by memsharded** [comment]
Closing this ticket as outdated.
The ``SystemPackageManager`` was fully revamped since then, now it has better control over which system is to be used. If there are still any issues, please report a new ticket referring to the new ``SystemPackageManager`` in Conan 2. Thanks very much!
