### ISSUE TITLE
Bzip2 for Linux fails on download

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#82]
Hi Conaneros :-)

I just re-ran Conan from a different machine whilst trying to build Dogen[1] and got the following error:

```
ERROR: Can't find a 'bzip2/1.0.6@lasote/stable' package for the specified options and settings. 

- Try to build from sources with "--build bzip2" parameter
- If it fails, you could try to contact the package author at 'http://github.com/lasote/conan-bzip2', report your configuration and try to collaborate to support it.

Package configuration:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=5.3, os=Linux
- Options: shared=True
```

This dependency on bzip2 appears to have came about via boost [2] as I am not requiring it directly.

Cheers

Marco
[1] https://github.com/DomainDrivenConsulting/dogenblob/master/conanfile.txt
[2] https://github.com/DomainDrivenConsulting/dogen/

**Comment by lasote** [comment]
Hi Marco!

I haven't built any packages with gcc 5.3 (just from 4.6 to 5.2). I'll try to generate them soon. 
You can try to build yourself with "conan install --build bzip2".

As it's a bzip2 package issue I will open an issue in https://github.com/lasote/conan-bzip2/issues repository, ok?

Cheers

**Comment by lasote** [comment]
Hi again!

Mhh, I was thinking, Boost download will fail too because I don't have any package uploaded with gcc 5.3.
So if you can try to build yourself call to:

    conan install --build missing

Thanks!

**Comment by mcraveiro** [comment]
ah my bad, I didn't even realise I was using a more recent version of GCC! cool I'll back it down to 5.2. Cheers

**Comment by lasote** [comment]
I've uploaded most of my packages with gcc 5.3 
You can use 5.3 now! :)

**Comment by mcraveiro** [comment]
Nice one! :-D thanks!
