### ISSUE TITLE
[question] How to cross-build for Windows target from Linux host using profile + build_requires?

### ISSUE THREAD

**Issue by dragondive** [conan-io/conan#8200]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I want to set up a simple example to demonstrate cross-build using profile + build_requires. By referring to various documents (especially [Cross building](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#cross-building), [Conan Profiles and Build Requires](https://bincrafters.github.io/2017/12/05/Conan-Profiles-and-Build-Requires/)), previous github issues and slack channel, I created a profile (posted below). I get errors with both mingw and msys2.

* I noticed on conan-center, many of the "installer" packages (mingw, msys2, cygwin) are marked as legacy. If this means they are "deprecated", what should be used instead?

* What could I try next to resolve the issues and get a working cross-build example? [I do not need to use a specific compiler for this example.]

**Profile**:

    [settings]
    os=Windows
    os_build=Windows
    arch=x86_64
    arch_build=x86_64
    compiler=gcc
    compiler.libcxx=libstdc++11
    compiler.version=7.1
    compiler.exception=seh
    compiler.threads=posix
    
    [build_requires]
    #mingw_installer/1.0@conan/stable    ## commented out to try with msys2
    msys2_installer/20161025@bincrafters/stable

**Error when building with mingw**:

    CMake Error: Could not create named generator MinGW Makefiles
    
    Generators
    * Unix Makefiles               = Generates standard UNIX makefiles.
      Green Hills MULTI            = Generates Green Hills MULTI files
                                     (experimental, work-in-progress).
      Ninja                        = Generates build.ninja files.
      Ninja Multi-Config           = Generates build-<Config>.ninja files.
      Watcom WMake                 = Generates Watcom WMake makefiles.
      CodeBlocks - Ninja           = Generates CodeBlocks project files.
      CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
      CodeLite - Ninja             = Generates CodeLite project files.
      CodeLite - Unix Makefiles    = Generates CodeLite project files.
      Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
      Sublime Text 2 - Unix Makefiles
                                   = Generates Sublime Text 2 project files.
      Kate - Ninja                 = Generates Kate project files.
      Kate - Unix Makefiles        = Generates Kate project files.
      Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
      Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

**Error when building with msys2**:
    
    CMake Error at /home/aravind/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
      The C compiler
    
        "/usr/bin/cc"
    
      is not able to compile a simple test program.
    
      It fails with the following output:
    
        Change Dir: /home/aravind/.conan/data/gtest/1.10.0/_/_/build/f387ff0abe3f37c7cf59bfb1ffa8567fdbbccce8/CMakeFiles/CMakeTmp
        
        Run Build Command(s):/usr/bin/make cmTC_6e432/fast && /usr/bin/make  -f CMakeFiles/cmTC_6e432.dir/build.make CMakeFiles/cmTC_6e432.dir/build
        make[1]: Entering directory '/home/aravind/.conan/data/gtest/1.10.0/_/_/build/f387ff0abe3f37c7cf59bfb1ffa8567fdbbccce8/CMakeFiles/CMakeTmp'
        Building C object CMakeFiles/cmTC_6e432.dir/testCCompiler.c.obj
        /usr/bin/cc    -o CMakeFiles/cmTC_6e432.dir/testCCompiler.c.obj -c /home/aravind/.conan/data/gtest/1.10.0/_/_/build/f387ff0abe3f37c7cf59bfb1ffa8567fdbbccce8/CMakeFiles/CMakeTmp/testCCompiler.c
        Linking C executable cmTC_6e432.exe
        /home/aravind/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6e432.dir/link.txt --verbose=1
        /home/aravind/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f CMakeFiles/cmTC_6e432.dir/objects.a
        /usr/bin/ar cr CMakeFiles/cmTC_6e432.dir/objects.a @CMakeFiles/cmTC_6e432.dir/objects1.rsp
        /usr/bin/cc -Wl,--whole-archive CMakeFiles/cmTC_6e432.dir/objects.a -Wl,--no-whole-archive -o cmTC_6e432.exe -Wl,--out-implib,libcmTC_6e432.dll.a -Wl,--major-image-version,0,--minor-image-version,0 
        /usr/bin/ld: unrecognized option '--major-image-version'
        /usr/bin/ld: use the --help option for usage information
        collect2: error: ld returned 1 exit status
        make[1]: *** [CMakeFiles/cmTC_6e432.dir/build.make:107: cmTC_6e432.exe] Error 1
        make[1]: Leaving directory '/home/aravind/.conan/data/gtest/1.10.0/_/_/build/f387ff0abe3f37c7cf59bfb1ffa8567fdbbccce8/CMakeFiles/CMakeTmp'
        make: *** [Makefile:140: cmTC_6e432/fast] Error 2
        
        
    
      
    
      CMake will not be able to correctly generate this project.
    Call Stack (most recent call first):
      CMakeLists.txt:2 (project)
    
    
    -- Configuring incomplete, errors occurred!

**Comment by dragondive** [comment]
Hello everyone, 
Does anyone have any hints or suggestions here? Let me know if some more information is needed from my side.

**Comment by memsharded** [comment]
I am sorry @dragondive this was not responded back then. Sometimes the activity is too high and some tickets fall through the cracks.

I am closing this ticket as outdated, tons of things have changed since then, most notably the cross-build model with 2 profiles. Please open new tickets if necessary, thanks!
