### ISSUE TITLE
[feature] New ``cpp_info.set_property("pkg_config_version")`` for ``PkgConfigDeps``

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#8202]
Please add `version` to cpp_info. This would be useful for modeling the rare case where library version and versioning in the build-system file are not the same. For example in `freetype` the versioning used in the `pkg-cfg` file is not the same as the versioning of the library.

- [✓] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by daravi** [comment]
Apparently this already works (e.g. xorg/system) though not documented.

**Comment by madebr** [comment]
@daravi 
Can you reopen this?
Setting the version is currently possible on component level, but not on generator level.

See also https://github.com/conan-io/conan-center-index/pull/3874
libsystemd needs to set a particular version for the pkg_config generator.

**Comment by memsharded** [comment]
Yes, this is in our plans. We are starting to think about a comprehensive and more systematic way to check information from dependencies. I am marking this as Conan 2.0, but it is likely that we will introduce it earlier in Conan 1.X to enable a non-breaking transition for Conan 2.0.

**Comment by memsharded** [comment]
Hi there.

Conan 1.X already introduced a new way to access dependencies information: ``self.dependencies["mydep"].ref.version`` is the way to access the dependencies real package version.
But I am not sure if this is exactly what this is about, I don't fully understand the use case or that difference in versions that you are describing. 

Also, in the general case, adding new information to ``cpp_info``, will not be done via attributes, but via ``cpp_info.set_property()``. Is it that you are requesting a  new property for ``pkg/system`` system recipes to be able to transmit the real version to consumers? What is the effect of not doing that? is that version really necessary downstream? I mean, at the end of the day, it is not actionable at all, it is whatever is installed in the system.

**Comment by prince-chrismc** [comment]
A few packages build with a "source code" version and install an "api/abi". Its possible a downstream project may see a number is does not recognize and fail.

Its something nice to have but I'd expect a patch to be an obvious solution.

If it's easy to override the default when the generators run might be worthwhile?

**Comment by memsharded** [comment]
I am renaming the feature, a ``cpp_info.version`` is not the right approach anymore, but using ``cpp_info.set_property()``, and this seems exclusive for ``pkg_config``. Also, removing it from the 2.0, seems a very niche issue, and can be solved anytime, even in 1.X, not necessarily tied to 2.0.

**Comment by memsharded** [comment]
``PkgConfigDeps`` now listen to properties:
```python
"version": (info.cpp_info.get_property("component_version") or
                            info.cpp_info.get_property("system_package_version") or
```
To define its version (package or component)

Closing the ticket as solved
