### ISSUE TITLE
[question] Install deployments without downloading dependencies

### ISSUE THREAD

**Issue by juba895** [conan-io/conan#8203]
With the [deploy method](https://docs.conan.io/en/latest/devtools/running_packages.html#deployable-packages) and the `conan install` command (e.g. `conan install hello/0.1@user/testing`) it's possible to copy the executable / files which are specified in the `deploy method` to a user space.

How is this possible without downloading the conan dependencies?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Thanks in Advacne,
Julian

**Comment by memsharded** [comment]
Hi @juba895 

It is not possible, when you are installing the package ``hello/0.1...`` it will be installed with its dependencies. The thing is that the dependencies will often contain things like shared libraries or data files, that need to be deployed together with the ``hello`` executables. The collection of artifacts, which can depend on the configuration, can only be computed after the dependencies have been installed, it is not possible to know in advance what will be deployed or not in the general case, as it is often formulated with a ``self.copy`` that in practice gather all the DLLs (or equivalent) from the dependencies.

As the ``deploy()`` method is also executed at the very end of the dev flow, it shouldn't be either a time-critical operation. If you are relying on Conan for production deployment, you might be interested in the "re-package" approach, have you checked?: https://docs.conan.io/en/latest/devtools/running_packages.html#runtime-packages-and-re-packaging

**Comment by juba895** [comment]
Thank a lot, it is working!
