### ISSUE TITLE
[bug] Empty source conandata.yml file gives error with scm_to_conandata during recipe export

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#8209]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS OSX 10.15.6 (Darwin `machine_name` 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64)
  * Compiler+version: `n/a`
  * Conan version: 1.30.2
  * Python version: 3.9.1

### Steps to reproduce (Include if Applicable)

The goal was to have a recipe without (currently) any other data/settings in the `conandata.yml`, but use the [SCM feature](https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm).

1. Simple conan recipe `conanfile.py` but using [SCM feature](https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm) and value of entry `url`, and `revision` both set to `auto`.
2. Add empty `conandata.yml` next to `conanfile.py`
3. update `~/.conan/conan.conf` to set `scm_to_conandata = True`
4. export recipe `conan export . user/testing --ignore-dirty`

**Gives error**:
![image](https://user-images.githubusercontent.com/1384135/102173494-fc92e500-3eff-11eb-9370-9f354a263857.png)

5. Update empty `conandata.yml` to contain a dummy entry, e.g. `dummy:` on first line
6. re-run export  `conan export . user/testing --ignore-dirty`

**Succeeds** with SCM data written to the local conan cache export:
![image](https://user-images.githubusercontent.com/1384135/102174168-ad4db400-3f01-11eb-9755-9bd2d4fe79e2.png)

### Logs (Executed commands with output) (Include/Attach if Applicable)

See above.

**Comment by SeanSnyders** [comment]
As a side note, if there are no `conandata.yml` then the export works fine.
Seems to only be an issue if the `conandata.yml` is empty.

**Comment by memsharded** [comment]
Thanks for the detailed report @SeanSnyders 

Indeed a bug, already submitted #8215, will be in next Conan 1.33
