### ISSUE TITLE
Duplicated requirement while using version ranges

### ISSUE THREAD

**Issue by trybekd** [conan-io/conan#822]
With the following dependency tree:
```
log4cpp/1.1.1@external/testing
     |
LoggerInterface/0.1.1@dtr/testing
(requires: log4cpp/[~1.1]@external/testing)
   |     \
   |    OtherDependency/2.0.11549@dtr/testing
   |    (requires: LoggerInterface/[~0.1]@dtr/testing)
   |     /
MyProject
(requires: LoggerInterface/[~0.1]@dtr/testing, OtherDependency/[~2.0]@dtr/testing)
```
I end up with an error:
`ERROR: LoggerInterface/0.1@dtr/testing: Duplicated requirement log4cpp/1.1.1@external/testing != log4cpp/[~1.1]@external/testing`

I receive error with and without --werror option.
Error does not occur if specific version of log4cpp (1.1.1) is set.
I'm using conan 0.17.2 on windows 10 (installed from windows installer).

**Comment by memsharded** [comment]
I am writing a regression test for this, but cannot make it fail. Here are my conanfiles:

```python

from conans import ConanFile
class Log3cppConan(ConanFile):
    name = "log4cpp"
    version = "1.1.1"

from conans import ConanFile
class LoggerInterfaceConan(ConanFile):
    name = "LoggerInterface"
    version = "0.1.1"
    requires = "log4cpp/[~1.1]@memsharded/testing"

from conans import ConanFile
class OtherConan(ConanFile):
    name = "other"
    version = "2.0.11549"
    requires = "LoggerInterface/[~0.1]@memsharded/testing"

from conans import ConanFile
class Project(ConanFile):
    requires = "LoggerInterface/[~0.1]@memsharded/testing", "other/[~2.0]@memsharded/testing"
```

Do they resemble your dependency graph properly? Can you make sure that you don't have an actual duplicate in the declaration of your requires?

If you can have a quick look, we are just about to release 0.18 if easy to fix, it could be included.

**Comment by trybekd** [comment]
I've started removing pieces of code from conanfiles to find out what's causing error.
Here are conanfiles:

```
from conans import ConanFile
class Log4cppConan(ConanFile):
    name = "log4cpp"
    version = "1.1.1"

from conans import ConanFile
class CCPLoggerConan(ConanFile):
    name = "CCPLogger"
    version = "0.1.1"
    def requirements(self):
        self.requires("log4cpp/[~1.1]@ccp/testing")

from conans import ConanFile
class CSTConan(ConanFile):
    name = "CSTAPI"
    version = "2.0.11549"
    def requirements(self):
        self.requires("CCPLogger/[~0.1]@ccp/testing")

from conans import ConanFile
class ProjectConan(ConanFile):
    def requirements(self):
        self.requires("CSTAPI/[~2.0]@ccp/testing")
        self.requires("CCPLogger/[~0.1]@ccp/testing")
```

Sometimes changing CCPLogger to Logger and CCPLoggerConan to LoggerConan or changing username fixes the problem.

**Comment by memsharded** [comment]
I made it to fail, using ``def requirements()`` method. Previously, I used just ``requires = `` class members, and it didn't fail, if you want to make a quick test. I keep investigating.

**Comment by memsharded** [comment]
Bug spotted. 

That was right, if using normal ``requires = `` dependencies definition, which should be done by default, then everything is fine. The use of ``requirements()`` should be left only for special cases, like conditional logic.

I am proposing a bug fix for the issue when using ``requirements()``, included in #823

**Comment by trybekd** [comment]
Changing `requirements()` to `requires = ` fixes the problem.
Thank you for quick answer.

**Comment by memsharded** [comment]
Great, thanks for telling. We are fixing the issue, and ``requirements()`` will be allowed, but in any case the use of ``requires`` is more common, so still recommended.
