### ISSUE TITLE
[question] Packaging cmake INTERFACE libraries

### ISSUE THREAD

**Issue by GPages** [conan-io/conan#8222]
CMake uses the notion of INTERFACE library : 

> An Interface library does not compile sources and does not produce a library artifact on disk. However, it may have properties set on it and it may be installed and exported

Since i use multiple libraries and multiple projects - all packaged with conan - i'd like to centralize some of the cmake utilities i use for development (e.g warning flags, code coverage) into a conan package. All my libraries and projects will depend on the latest version of this package, probably using  "Build requirements" provided by conan.

Usually i create an INTERFACE library containing the coverage flags, and my target links to it if needed:

```
1 - add_library(my_warnings_flags INTERFACE)

2 - (set the warning flags property of my_warnings_flags )

3 - target_link_libraries(my_lib PRIVATE my_warnings_flags)
```

However when i try to package this INTERFACE library, my project successfully find the package but the warning flags are absent when actually building it. 

Am i completelty wrong with this approach ? Is it a limitation of the conan/cmake interraction ? 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @GPages 

I don't think there is something bad for your use case, just some things to be taken into account:

- If the package you are creating with the flags, etc, directly create a CMake file that can be used by consumers only CMake consumers will be able to use it. If it is ok for your use case then fine, but if you are using more than one build system, you might want to generalize the concept using the ``package_info()`` method of the recipes.
- Depending on the generator that you are using, it will do different things. Are you using the ``cmake_find_package(_multi)`` ones? These one are currently implementing/iterating the concept of "build_modules", that is, build scripts that are automatically included in the "find_package" code. Check in https://docs.conan.io/en/latest/reference/conanfile/attributes.html the ``self.cpp_info.build_modules``.

It can be useful if you share a very minimal (here or in another github repo), Conan recipe + CMake code that defines those flags, and a very basic consumer via build_requires, so we could see how things are defined and reproduce it.

**Comment by GPages** [comment]
Thanks a lot for this quick and precise answer, this is exactly what i needed.

Using _cmake_find_package_multi_ generator and _self.cpp_info.build_modules_ easily solved the problem. If i understand correctly the interface library is now created by the consumer by automatically calling the "build scripts". This is different than what i had before where the library was created when building the package. My mistake was probably to treat this interface library as a regular library.

Here is a simple code example:

```
( conanfile.py )
class MyWarningsConan(ConanFile):
    name = "myWarnings"
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake_find_package_multi"
    exports_sources = "src/*"

    def package(self):
        self.copy("*.cmake", keep_path=False)

    def package_info(self):
        self.cpp_info.build_modules.append("CompilerWarnings.cmake")
```

```
(src/ CMakeLists.txt )
project(myWarnings LANGUAGES CXX VERSION 0.0.1)
include(CompilerWarnings.cmake)
```

```
( src/CompilerWarnings.cmake )
add_library(my_warnings INTERFACE)
set_warnings(my_warnings )  <== my custom CMake function
```

And now i can specify it with my profile:
```
[build_requires]
myWarnings/[>0.0.0]@something/stable
```

And my project can link against the target library:
```
( myProject/CMakeLists.txt )
target_link_libraries(myProject PRIVATE myWarnings)
```

Works like a charm ! Now on the consumer's CMakeLists.txt i should make sure that build does not fail when the library is not there, but this is probably off topic.

**Comment by memsharded** [comment]
Ok, great!!

A few hints:
- ``MyWarningsConan`` probably doesnt need any generator at all, as it doesnt have dependencies, or need further transitive find_packages to build itself
- Keep an eye on next releases changelog on ``build_modules``. As it is experimental and we are aware of some weaknesses, it might get some minor changes to the UI.

I think we can close this ticket now, but feel free to comment or open a new one if you have any further question. Thanks!

**Comment by GPages** [comment]
Just to complete my last comment, if anyone is interested : 
 - There is indeed no need for any generator at all, so i could remove `generators = "cmake_find_package_multi"` from the conanfile.py of the package
 - In the CMakeLists.txt of the consumer, using "debug" keyword of the target_link_library commands is what i needed to successfully build in release mode (hence without my_warnings being defined).
 
```
 target_link_libraries(myProject
        PRIVATE debug my_warnings
        PRIVATE CONAN_PKG::anotherLibrary)
```

So now, when developping i just have to use my dev_profile.txt and all my useful flags are there, while the release config does not use them. Awesome, i love it :)
