### ISSUE TITLE
[bug] Pinned revision still uses old conanfile.py

### ISSUE THREAD

**Issue by gummif** [conan-io/conan#8229]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: MSVC VS 16
  * Conan version: 1.32.1
  * Python version: 3.5.2 (python3) 2.7.12 (python) pip 20.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

### Steps to reproduce (Include if Applicable)

Boost was installed with the latest (or a newer revision) boost/1.74.0. then to avoid a bug in the package it was pinned to boost/1.74.0#3b52fbf45879b8b288e59d454d1c4765, and CONAN_REVISIONS_ENABLED=1 was set (conan was also updated in the process).

Then I was still getting errors as if using the newer revision, but it looked like I had the pinned revision:
```
$ conan search boost/1.74.0 -rev
Existing package recipes:

boost/1.74.0#3b52fbf45879b8b288e59d454d1c4765
```
The error
```
ERROR: boost/1.74.0: Error in package_info() method, line 1164
        assert len(non_used) == 0, "These libraries were not used in conan components: {}".format(non_used)
        AssertionError: These libraries were not used in conan components: {'boost_nowide'}
```
This is not in the recipe [pinned](https://conan.io/center/boost?version=1.74.0&revision=3b52fbf45879b8b288e59d454d1c4765&tab=recipe&os=)  but it is here [newer](https://conan.io/center/boost?version=1.74.0&revision=762204d1a4a3d27eb3d082b371c3cf30&tab=recipe)

I then removed all packages `conan remove "boost*" -f` and executed again
```
conan.exe install ./conanfile.txt -g visual_studio --install-folder .\Release\.conan "-pr=vs16release" -s compiler.cppstd=17 --build=outdated --update`
```
and then it worked.

I did the same thing on linux which worked fine without removing boost.

**Comment by memsharded** [comment]
Hi @gummif 

I have been trying to reproduce this issue, but still not clear how to do it. Was this just a one time thing, or can you still consistently reproduce it? How do you produce the ``ERROR: boost/1.74.0: Error in package_info() method, line 1164`` error? Doing what command? In theory the Conan cache only contain one revision per recipe, it is impossible to get that error message if the recipe in the cache is not that one. Could you please clarify?

**Comment by AbrilRBS** [comment]
Closing now that we're commited to Conan 2 and we didn't hear back from you - if there was an issue, it was not widespread as we didn't get similar reports. Thanks a lot for taking the time to report it in the first place though! :)
