### ISSUE TITLE
[question] source is not called when option restricted with "ANY" changes

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#8231]
Hello,

I'm trying to improve [darwin-toolchain](https://github.com/theodelrieu/conan-darwin-toolchain) by allowing users to use a custom `libcxx` rather than the Xcode bundled one.

I do have a `llvm_version` defined like this: `options = { "llvm_version": "ANY" }`

I use the version in the `source` method, to choose which branch to checkout.

After creating the package with `llvm_version=9`, I tried creating a new one with `llvm_version=11`, but got this output:

```
conan create . -pr macos-armv8 -o darwin-toolchain:llvm_version=11

Exporting package recipe
darwin-toolchain/1.1.0 exports_sources: Copied 1 '.cmake' file: darwin-toolchain.cmake
darwin-toolchain/1.1.0: The stored package has not changed
darwin-toolchain/1.1.0: Using the exported files summary hash as the recipe revision: 48b765ad337130e97804fd92ad64bb1b
darwin-toolchain/1.1.0: Exported revision: 48b765ad337130e97804fd92ad64bb1b
```

It just built the package with LLVM 9.0 sources again...

Is that expected? Should I:

* move `llvm_version` to be the `darwin-toolchain` version?
* always clone `llvm` in the `build` method
* something else (and better)?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @theodelrieu 

This is totally expected. The ``source()`` method is common to all variants, settings, options...  Please read the note in https://docs.conan.io/en/latest/reference/conanfile/methods.html#source

You should be getting the source specific code in ``build()`` method instead. The Conan v2 mode will raise an error if trying to use settings or options in the source() method, so it will be more evident that this is not possible

**Comment by theodelrieu** [comment]
Thanks @memsharded, I consistently forget about this... It might just be me, but I find the `source`/`build` to be quite confusing w.r.t what you can do within them.
