### ISSUE TITLE
Allow manual search/installation from disabled remotes

### ISSUE THREAD

**Issue by kdsx** [conan-io/conan#8233]
Conan allows to disable some remotes. And currently a disabled remote is just a line in `conan remote list` output. User can do nothing with them. Only enable it back. What if allow certain actions on such remotes when user manually specify them via `-r` parameter.

Just an example. We use a recommended package promotion scheme to copy packages from dev to prod repo. When someone builds a package, she would like to test how a local project compiles with an updated package. Currently she has to enable dev repo to download the package. What if she could just run `conan install my_package/1.1@ -r dev` to install it into the local cache and not affect the scope where conan searches new packages? Keeping `dev` repo always on is not good because someone could forget to promote a new package to prod, and the incident won't be noticed immediately because conan will find the package in the dev repo.

**Comment by memsharded** [comment]
Hi @kdsx 

While I understand the request, it seems at first glance that this cannot be done now, as it would be breaking behavior. The semantics and current documented behavior of ``conan remote disable`` is to completely disable that remote, for any usage without removing it. Users might be relying on that behavior for their flows and their development/developers policies.

Also, I think there would be behavior for transitive dependencies for ``conan install my_package/1.1@ -r dev``? It might install other dependencies for ``my_package`` from the ``dev`` remote as well? A lot of things can happen in that ``conan install`` command. If you add it in the command line explicitly, then it becomes fully enabled for that command? Then the behavior starts to be in a grey area, not clearly defined.

While the alternative, even it introduces 2 more commands into the developer flow, as you commented, those are the "exceptional" cases, when a developer want to circumvent the well defined protection about the "dev" repo being disabled:

```bash
$ conan remote enable dev
$ conan install pkg/1.0@user/channel -r=dev
$ conan remote disable dev
```

**Comment by kdsx** [comment]
Hmm, it looks like `conan install` is pretty complex :)

However what about `conan search pkg/1.0@user/channel -r=dev` (or `get`)?

**Comment by AbrilRBS** [comment]
Closing as wont-do. At some point during the Conan 2 beta this same case came up and we decided not to support operations over disabled remotes other than the ones listed under `conan remote -h`
