### ISSUE TITLE
[question] Multiple definition of zlib

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#8234]
I am not sure this is related to conan, but here is what I am trying to understand

Say I have libA and libB, both needs zlib 1.2.11, and both are compiled as static lib. 
my understanding is that static lib just put all .o files together. as such, both libA and libB will have something like `zutil.c.o` in their .a files. 
Now I am trying to build another project that relies on both libA and libB, and that should generate a .so file. so during the linkage, the linker will find both `zutil.c.o` in both libA and libB, will that cause an error of multiple defintions of zlibs functions?

The reason i am asking is that, i got this kind error when trying to build a project. But the weird part is that, with the same conanfile.py, but with different building environment i got different results. I am under ubuntu 18.04, I have conan installed only for system python3. my project uses pybind11, so i have system's own python3 and python3-dev installed (e.g., in `/usr/lib/x86_64-linux-gnu/libpython3.7m.so`), i also installed conda, which has its own python3 and python3-dev installed (e.g., in  `/home/username/anaconda3/lib/libpython3.7m.so`), I have all conan packages that are needed installed, and they are the same for all the following building process, my conan profile sets compiler version of gcc to 9,  and here is what happens. 
1. if i build in conda's python3 env, i can conan build the project without any problem, note that my conda comes with gcc 7.3, so i have to `set(CONAN_DISABLE_CHECK_COMPILER TRUE)` to build.
2. If i build with conda's python3 env, and `export CXX=/usr/lib/ccache/g++` so that system's gcc is used (actually i am using ccache here), i dont need to `set(CONAN_DISABLE_CHECK_COMPILER TRUE)`,  then i got the following error:

> /usr/bin/ld: cannot find /lib/libpthread.so.0
> /usr/bin/ld: cannot find /usr/lib/libpthread_nonshared.a
> collect2: error: ld returned 1 exit status

3. if i build in system's python3 env, and my system has gcc 9.3, i got the following error:

> /home/username/.conan/data/zlib/1.2.11/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib/libz.a(zutil.o): In function `zlibVersion':
> zutil.c:(.text+0x0): multiple definition of `zlibVersion'
> /home/username/.conan/data/pcl/1.11.0/_/_/package/a4ccc62deb773be50caa050a2fb7f7e769a17a54/lib/libpcl_surface.a(zutil.c.o):zutil.c:(.text+0x0): first defined here
> /home/username/.conan/data/zlib/1.2.11/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib/libz.a(zutil.o): In function `zlibCompileFlags':
> zutil.c:(.text+0x10): multiple definition of `zlibCompileFlags'
> /home/username/.conan/data/pcl/1.11.0/_/_/package/a4ccc62deb773be50caa050a2fb7f7e769a17a54/lib/libpcl_surface.a(zutil.c.o):zutil.c:(.text+0x10): first defined here
> /home/username/.conan/data/zlib/1.2.11/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib/libz.a(zutil.o):(.data.rel.ro.local+0x0): multiple definition of `z_errmsg'
> /home/username/.conan/data/pcl/1.11.0/_/_/package/a4ccc62deb773be50caa050a2fb7f7e769a17a54/lib/libpcl_surface.a(zutil.c.o):(.data.rel.ro.local+0x0): first defined here
> collect2: error: ld returned 1 exit status
> 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> Say I have libA and libB, both needs zlib 1.2.11, and both are compiled as static lib.
my understanding is that static lib just put all .o files together. as such, both libA and libB will have something like zutil.c.o in their .a files.

Not really, I am afraid you misunderstood static libraries. LibA and LibB will only contain objects of their own source files, but not their dependencies. A static lib only contain unresolved links to external libs. When the linker builds an executable/shared library, it will link those calls from LibA and LibB with the entry points in zlib library.

**Comment by shelper** [comment]
i think just figured out what causes this multiple definition. I have   this line in my cmakelists.txt file 
`target_link_libraries(${TARGET} PUBLIC ${PYTHON_LIBRARIES})`
and this one looks for python static libs, and thus will link to the zlib dependency for python itself.
this conflict with the one used in conan. 

when building using conda's python, for some reason maybe the version of zlib in conda' python build it uses the same version of zlib? 

@memsharded does this sounds like a reasonable explaination?

**Comment by memsharded** [comment]
Hi @shelper 

Yes, it is very possible that ``${PYTHON_LIBS}`` brings some extra libraries, including zlib. Why don't you print its value and check it? But it is a plausible explanation.

Not sure what you mean about Conda, you mean that in Conda it works, but outside Conda it works? It might also be a possibility that the zlib library provided by Conda is binary compatible with the one provided by Conan too.
