### ISSUE TITLE
[bug] CMake flags Boolean type conversion

### ISSUE THREAD

**Issue by hsuanguo** [conan-io/conan#8235]
It might can't be said as bug, but potentially can cause some issues which will be very difficult to be allocated.

Basically, it is caused by the fact that CMake uses ON/OFF value as the boolean type, but when we set `cmake.definitions` using `True/False` in python,  there could be some issues.

**Description**

In conan we can set boolean CMake flags using:

- `cmake.definitions["MY_CUSTOM_DEFINITION"] = True`, `cmake.definitions["MY_CUSTOM_DEFINITION"] = False`

And it will be converted to CMake flags into string [here](https://github.com/conan-io/conan/blob/develop/conans/client/build/__init__.py#L2): 

For example, the flags above will be converted to : `-D MY_CUSTOM_DEFINITION=True`, and then pass to CMake. In most of the cases it will work, as CMake considers `ON=TRUE=1`,  `OFF=FALSE=0`,  but the following condition will fail, if we use True/False over ON/OFF, when `STREQUAL  `is used.

- `if(XX_OPTION STREQUAL "ON")`

Then this will be false condition if we set `cmake.definitions["XX_OPTION "]=True`.

Of course, those who write  CMake scripts, they should not use `STREQUAL` for boolean types, but unfortunately I found that similar cases are not rare, and you may find many examples in the community.

 And also this can be easily solved by setting the flags using `cmake.definitions["MY_CUSTOM_DEFINITION"] = ON` instead of 'True', but unfortunately I found most of the recipes use `True/False ` in options including [tutorials](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html).

**Proposals**

Personally I think it makes more sense to use `cmake.definitions["MY_CUSTOM_DEFINITION"] = ON/OFF`  over `True/False`, as this will make sure the flags will align with CMake and won't affect the logic in CMake scripts in any case, and we should avoid any value conversions.

Alternatively, we can convert `True/False` to `ON/OFF` when we pass flags to cmake, if  `cmake.definitions[XX]` is boolean type but not string(That's to say, we can still pass cmake.definitions["MY_CUSTOM_DEFINITION"] = 'False').
This would be an easier solution in short time, and we can still keep the current recipes as they are, I have a quick fix [here](https://github.com/hsuanguo/conan/commit/dd30f473fdeccab728a1f583ce0e657e7b487958).

**Comment by memsharded** [comment]
Hi @hsuanguo 

The truth is that ``if(XX_OPTION STREQUAL "ON")`` is a bad practice in CMake, and that might happen, but it is also possible that there are users out there that have in some CMakeLists something like ``if(XX_OPTION STREQUAL "True")``, and if we change this, it will break them. Given the Conan user base is large and growing, we have realized recently that this will probably happen.

As the current behavior, also for settings, options, etc is that the values are always strings, it seems problematic to change this that specifically for cmake helpers and boolean values, implementing some "magic" conversion to ON/OFF

I'd suggest to move this to conan-center-index and use it as a hook, or as a review guideline (to use ON/OFF as values in recipes instead of python booleans)

**Comment by hsuanguo** [comment]
> Hi @hsuanguo
> 
> The truth is that `if(XX_OPTION STREQUAL "ON")` is a bad practice in CMake, and that might happen, but it is also possible that there are users out there that have in some CMakeLists something like `if(XX_OPTION STREQUAL "True")`, and if we change this, it will break them. Given the Conan user base is large and growing, we have realized recently that this will probably happen.

> As the current behavior, also for settings, options, etc is that the values are always strings, it seems problematic to change this that specifically for cmake helpers and boolean values, implementing some "magic" conversion to ON/OFF
> 
> I'd suggest to move this to conan-center-index and use it as a hook, or as a review guideline (to use ON/OFF as values in recipes instead of python booleans)

makes sense,  using strings over python booleans will move this responsibility to users, and it doesn't matter whether ON/OFF or True/False is used in CMake,  recipes can always be aligned with whatever is used in CMake.

**Comment by memsharded** [comment]
Good, updating the docs in https://github.com/conan-io/docs/pull/1969.

Also, asking @uilianries to see if it makes sense to add something in conan-center-index policies or hooks that could check this, or not really a current issue in ConanCenter

**Comment by uilianries** [comment]
We rarely see "ON" "OFF" listed in conanfile.py, and still more rare are the cases where True/False don't work. Usually newbies use "ON"/"OFF", but they don't know about boolean support.

Currently, we have follow projects:

```
./recipes/aruco/3.x.x/conanfile.py:        self._cmake.definitions["ARUCO_DEVINSTALL"] = "ON"
./recipes/corrade/all/test_package/conanfile.py:            cmake.definitions["CORRADE_MSVC2015_COMPATIBILITY"] = "ON" if self.settings.compiler.version == "14" else "OFF"
./recipes/corrade/all/test_package/conanfile.py:            cmake.definitions["CORRADE_MSVC2017_COMPATIBILITY"] = "ON" if self.settings.compiler.version == "15" else "OFF"
./recipes/corrade/all/test_package/conanfile.py:            cmake.definitions["CORRADE_MSVC2019_COMPATIBILITY"] = "ON" if self.settings.compiler.version == "16" else "OFF"
./recipes/corrade/all/conanfile.py:            self._cmake.definitions["WITH_RC"] = "ON"
./recipes/corrade/all/conanfile.py:                self._cmake.definitions["CORRADE_MSVC2015_COMPATIBILITY"] = "ON" if self.settings.compiler.version == "14" else "OFF"
./recipes/corrade/all/conanfile.py:                self._cmake.definitions["CORRADE_MSVC2017_COMPATIBILITY"] = "ON" if self.settings.compiler.version == "15" else "OFF"
./recipes/corrade/all/conanfile.py:                self._cmake.definitions["CORRADE_MSVC2019_COMPATIBILITY"] = "ON" if self.settings.compiler.version == "16" else "OFF"
./recipes/libpng/all/conanfile.py:        cmake.definitions["PNG_DEBUG"] = "OFF" if self.settings.build_type == "Release" else "ON"
./recipes/libpng/all/conanfile.py:            cmake.definitions["PNG_BUILD_ZLIB"] = "ON"
./recipes/benchmark/all/conanfile.py:        self._cmake.definitions["BENCHMARK_ENABLE_LTO"] = "ON" if self.options.enable_lto else "OFF"
./recipes/benchmark/all/conanfile.py:        self._cmake.definitions["BENCHMARK_ENABLE_EXCEPTIONS"] = "ON" if self.options.enable_exceptions else "OFF"
./recipes/benchmark/all/conanfile.py:                self._cmake.definitions["BENCHMARK_BUILD_32_BITS"] = "ON" if "64" not in str(self.settings.arch) else "OFF"
./recipes/benchmark/all/conanfile.py:            self._cmake.definitions["BENCHMARK_USE_LIBCXX"] = "ON" if (str(self.settings.compiler.libcxx) == "libc++") else "OFF"
./recipes/catch2/2.x.x/conanfile.py:        self._cmake.definitions["CATCH_INSTALL_HELPERS"] = "ON"
./recipes/poco/all/conanfile.py:            self._cmake.definitions["POCO_MT"] = "ON" if "MT" in str(self.settings.compiler.runtime) else "OFF"
./recipes/mongo-c-driver/all/conanfile.py:        self._cmake.definitions["ENABLE_STATIC"] = "OFF" if self.options.shared else "ON"
./recipes/mongo-c-driver/all/conanfile.py:        self._cmake.definitions["ENABLE_SRV"] = "ON" if self.options.srv else "OFF"
./recipes/mongo-c-driver/all/conanfile.py:        self._cmake.definitions["ENABLE_AUTOMATIC_INIT_AND_CLEANUP"] = "ON"
./recipes/mongo-c-driver/all/conanfile.py:        self._cmake.definitions["ENABLE_MONGOC"] = "ON"
./recipes/mongo-c-driver/all/conanfile.py:        self._cmake.definitions["ENABLE_BSON"] = "ON"
./recipes/mongo-c-driver/all/conanfile.py:        self._cmake.definitions["ENABLE_SNAPPY"] = "ON" if self.options.with_snappy else "OFF"
./recipes/mongo-c-driver/all/conanfile.py:        self._cmake.definitions["ENABLE_ZSTD"] = "ON" if self.options.with_zstd else "OFF"
./recipes/mongo-c-driver/all/conanfile.py:        self._cmake.definitions["ENABLE_ICU"] = "ON" if self.options.with_icu else "OFF"
./recipes/libnghttp2/all/conanfile.py:        cmake.definitions["ENABLE_SHARED_LIB"] = "ON" if self.options.shared else "OFF"
./recipes/libnghttp2/all/conanfile.py:        cmake.definitions["ENABLE_STATIC_LIB"] = "OFF" if self.options.shared else "ON"
./recipes/libnghttp2/all/conanfile.py:        cmake.definitions["ENABLE_HPACK_TOOLS"] = "ON" if self.options.with_hpack else "OFF"
./recipes/libnghttp2/all/conanfile.py:        cmake.definitions["ENABLE_APP"] = "ON" if self.options.with_app else "OFF"
./recipes/libnghttp2/all/conanfile.py:        cmake.definitions["WITH_JEMALLOC"] = "ON" if self.options.with_jemalloc else "OFF"
./recipes/libnghttp2/all/conanfile.py:        cmake.definitions["ENABLE_ASIO_LIB"] = "ON" if self.options.with_asio else "OFF"
./recipes/mimalloc/all/conanfile.py:        self._cmake.definitions["MI_OVERRIDE"] = "ON" if self.options.override else "OFF"
./recipes/mimalloc/all/conanfile.py:        self._cmake.definitions["MI_SECURE"] = "ON" if self.options.secure else "OFF"
./recipes/bzip2/1.0.8/conanfile.py:        cmake.definitions["BZ2_BUILD_EXE"] = "ON" if self.options.build_executable else "OFF"
./recipes/bzip2/1.0.6/conanfile.py:        cmake.definitions["BZ2_BUILD_EXE"] = "ON" if self.options.build_executable else "OFF"
```

We could use a hook to enforce True/False, but we would need update the whitelist when finding a project which uses string compare for CMake options.

**Comment by memsharded** [comment]
This issue refers to the legacy CMake integration superseded in Conan 1.X by ``from conan.tools.cmake import CMake, CMakeToolchain``, and removed in 2.0. Closing this ticket as outdated, don't hesitate to create new tickets for any further question, thanks!
