### ISSUE TITLE
[bug] conan install --update does not work, manual clearing of cache needed

### ISSUE THREAD

**Issue by chausner-audeering** [conan-io/conan#8239]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 20H2
  * Compiler+version: MSVC 16
  * Conan version: 1.32.1
  * Python version: 3.8.5 64-bit

### Steps to reproduce (Include if Applicable)
We are running Conan builds in GitLab CI using CPT on every push to "master" and uploading packages to Artifactory. We are using "latest" as version specifier in the package reference and the packages get overwritten on every push. Only when we make a release of a package, we change the version specifier to a fixed version.

This generally works fine in CI where every CI job starts with an empty local Conan cache, so on every build all dependencies are always retrieved from the Artifactory remote. But on local dev machines, we quickly ran into issues where cached packages don't match with what is on the remote. A workaround we found was to clear the local cache, after which the latest revision got downloaded from Artifactory. After some time, we found out that there is the dedicated `conan install --update` flag to get the latest revision of packages. At first, we thought this solved all the issues we encountered but I just ran into a case where even specifying `--update` does not help. Only manually deleting the package folder from the cache works.

This is the error I currently get when running `conan install .. --update`:
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MT
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

nlohmann_json/3.9.1: WARN: The package nlohmann_json/3.9.1:d1091b2ed420e6d287293709a907ae824d5de508 doesn't belong to the installed recipe revision, removing folder
conanfile.txt: Installing package
Requirements
    devaice-framework/0.3.0@audeering/stable from 'conan-local' - Cache
    ...
Packages
    devaice-framework/0.3.0@audeering/stable:8b139777a790dce8445d5790e3d4d4257c6e1f3c - Missing
    ...

Installing (downloading, building) binaries...
ERROR: Missing binary: devaice-framework/0.3.0@audeering/stable:8b139777a790dce8445d5790e3d4d4257c6e1f3c

devaice-framework/0.3.0@audeering/stable: WARN: Can't find a 'devaice-framework/0.3.0@audeering/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.cppstd=17, compiler.runtime=MT, compiler.version=16, os=Windows
- Options: shared=False
- Dependencies:
- Requirements:
- Package ID: 8b139777a790dce8445d5790e3d4d4257c6e1f3c

ERROR: Missing prebuilt package for 'devaice-framework/0.3.0@audeering/stable'
Try to build from sources with "--build=devaice-framework"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

When I run `conan search -r conan-local "devaice-framework/0.3.0@audeering/stable"` (`conan-local` is our Artifactory remote) I do see the corresponding entry though:
```
    Package_ID: 8b139777a790dce8445d5790e3d4d4257c6e1f3c
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.cppstd: 17
            compiler.runtime: MT
            compiler.version: 16
            os: Windows
        Outdated from recipe: False
```

Now when I delete the `devaice-framework` folder from the local Conan cache and run `conan install .. --update` again, it can find the package binaries and downloads them from Artifactory:
```
devaice-framework/0.3.0@audeering/stable: Not found in local cache, looking in remotes...
devaice-framework/0.3.0@audeering/stable: Trying with 'conan-center'...
devaice-framework/0.3.0@audeering/stable: Trying with 'conan-local'...
Downloading conanmanifest.txt completed [1.55k]
Downloading conanfile.py completed [1.95k]
devaice-framework/0.3.0@audeering/stable: Downloaded recipe revision db173809abc1b295ceebd307c3bbc440
```

When I delete the newly created directory from the cache and put in the old one again, the issue is back. So I compared the folder contents of the old and new one and checked what the difference is. The essential differences seem to be in the `metadata.json` file: 
[metadata_old.json.txt](https://github.com/conan-io/conan/files/5721290/metadata_old.json.txt)
[metadata_new.json.txt](https://github.com/conan-io/conan/files/5721291/metadata_new.json.txt)
It is enough to copy the `metadata.json` file from the new folder into the old one and `conan install` succeeds. I don't know how to interpret all the details in the manifest but the main difference seems to be that in the old manifest the recipe and package revision is defined as "0" while in the new one there is a non-zero hash.

Is what I am seeing expected behaviour or a bug? If it is expected, what is the proper way to resolve it other than manually deleting packages from the cache?

/cc @Linux13524

**Comment by memsharded** [comment]
Hi @chausner-audeering 

It seems that you are mixing usage with and without revisions. It is not possible to mix or switch using and not using revision in the same cache, is it possible that different jobs are using different configurations?

Just a heads up too, Conan 2.0 will use revisions only: https://github.com/conan-io/tribe/blob/main/design/014-general-revisions.md. It might be good to start adopting revisions earlier than 2.0.

**Comment by chausner-audeering** [comment]
Thanks @memsharded for your quick reply!

You mean the issue could be caused by changing the `general.revisions_enabled` setting locally? I just checked and that setting is enabled on my local machine, and should have been enabled ever since we moved to Conan. What could have happened, though, is that the setting isn't or wasn't always enabled in our CI. We reinstalled some of our runners recently and it might be that the revision setting had not been enabled from the very beginning and some CI jobs ran with the setting disabled. Would that be a possible explanation? But if I am not mistaken, one gets an error when attempting to upload to Artifactory with revisions disabled.

I will check the state of the setting in our CI runner to make sure it is enabled, we might have forgotten to do that when we reinstalled it. I'll report back in this thread as soon as we know more (probably after Christmas in the new year).

In any case, it might make sense for Conan to print a warning or error if it detects that there is a mismatch related to the revisions_enabled setting (assuming there is a way for Conan to detect that condition).

**Comment by Linux13524** [comment]
I can confirm that revisions were not enabled in our recent CI runners. I also would have expected to see an error from conan when uploading to artifactory. At least I saw one in the past on my local machine...

**Comment by memsharded** [comment]
To make sure that you are using the same config everywhere, I would recommend (in case you are not doing it yet), to use ``conan config install`` feature, with a ``conan.conf`` file that defines revisions enabled in it. In this way it would be more difficult to have different configurations in machines, it doesn't depend on the installation. Remember that ``conan.conf`` can also define minimum conan version, so that is a mechanism that can force everyone, developers and CI to upgrade when you want.

**Comment by memsharded** [comment]
> You mean the issue could be caused by changing the general.revisions_enabled setting locally? I just checked and that setting is enabled on my local machine, and should have been enabled ever since we moved to Conan. What could have happened, though, is that the setting isn't or wasn't always enabled in our CI. We reinstalled some of our runners recently and it might be that the revision setting had not been enabled from the very beginning and some CI jobs ran with the setting disabled. Would that be a possible explanation? But if I am not mistaken, one gets an error when attempting to upload to Artifactory with revisions disabled.

@chausner-audeering yes, enabling/disabling revisions on an already populated cache could have some undefined behaviors. It is an important difference in processing and storing the metadata, and it is basically impossible to check and run migrations of that in a populated cache when this value changes. So revisions is something that should be managed and have a consistent value across machines even before starting to use Conan in those caches. It seems this could be the origin of this issue, not a bug per se in the revisions (or not using revisions), but an undefined state in the transition when mixing both, that would be extremely difficult to fix on our side.

Please do try to have everything with the same configuration regarding revisions, cleaning the caches, and if it works, let us know, maybe we could close this issue, as this problem will go away anyway in Conan 2.0 where revisions will always be on

**Comment by Linux13524** [comment]
@memsharded Thanks a lot for your suggestions! I think we will definitely try out using a `conan.conf` for our CI jobs. 

I just checked with our devops team and it seems the `CONAN_REVISIONS_ENABLED` variable was always set throughout all our CI runners. So the revisions should have been enabled and this would explain why there was no error message when uploading to artifactory. But it also means the problem is cause by something else. 

@memsharded Can you confirm, that there is an error message when trying to upload from conan that has revisions disabled to an artifactory instance that has revisions enabled?

**Comment by chausner-audeering** [comment]
I have my local cache cleared now and will see if it happens again in the future. It's still not really clear to me how the current state could have happened because
* if the revisions_enabled setting for a CI runner was disabled, it would not have uploaded the package to Artifactory but printed an error instead
* the last modified time of my local `conan.conf` file where `revisions_enabled=true` is enabled, is 1st of September, while the `metadata.json` file in the `devaice-framework/0.3.0` package in my local cache that contained `revision: "0"` was last modified on 27th of November.

So I did have `revisions_enabled=true` enabled all the time but still somehow that metadata file with disabled revisions got into my cache.

**Comment by chausner-audeering** [comment]
I'll close this issue for now and will reopen if it happens again.

**Comment by sourcedelica** [comment]
Re: mixed revision/non-revision in the cache.  We have seen this too after we moved to using revisions (we needed to upgrade Artifactory first to support revisions).  

A simple fix would be to always replace non-revision packages (indicated by `(No time)` when running `conan search`) when running `conan install --update` with revisions enabled.
