### ISSUE TITLE
[bug] python scripting client.command stopped working 1.32.2

### ISSUE THREAD

**Issue by pgeler** [conan-io/conan#8252]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04LTS
  * Compiler+version: NA
  * Conan version: 1.32.2
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)

after pip3 install conan --upgrade

and installing upgrade from 1.31.0 to 1.32.2 following script stopped working:

```
#!/usr/bin/python

import sys
from conans.client.command import main

main(sys.argv[1:])
```
### Logs (Executed commands with output) (Include/Attach if Applicable)

vagrant@DESKTOP-MSUODIF:/mnt/d/git/qb/linux_build$ ../scripts/conan.py
Traceback (most recent call last):
  File "../scripts/conan.py", line 4, in <module>
    from conans.client.command import main
  File "/home/vagrant/.local/lib/python3.8/site-packages/conans/client/command.py", line 16, in <module>
    from conans.client.conan_api import Conan, default_manifest_folder, _make_abs_path, ProfileData
  File "/home/vagrant/.local/lib/python3.8/site-packages/conans/client/conan_api.py", line 13, in <module>
    from conans.client.cmd.create import create
  File "/home/vagrant/.local/lib/python3.8/site-packages/conans/client/cmd/create.py", line 3, in <module>
    from conans.client.cmd.test import install_build_and_test
  File "/home/vagrant/.local/lib/python3.8/site-packages/conans/client/cmd/test.py", line 6, in <module>
    from conans.client.manager import deps_install
  File "/home/vagrant/.local/lib/python3.8/site-packages/conans/client/manager.py", line 7, in <module>
    from conans.client.installer import BinaryInstaller, call_system_requirements
  File "/home/vagrant/.local/lib/python3.8/site-packages/conans/client/installer.py", line 11, in <module>
    from conans.client.generators import TXTGenerator, write_toolchain
  File "/home/vagrant/.local/lib/python3.8/site-packages/conans/client/generators/__init__.py", line 5, in <module>
    from conan.tools.cmake import CMakeToolchain
  File "/mnt/d/git/qb/scripts/conan.py", line 4, in <module>
    from conans.client.command import main
ImportError: cannot import name 'main' from partially initialized module 'conans.client.command' (most likely due to a circular import) (/home/vagrant/.local/lib/python3.8/site-packages/conans/client/command.py)
v

**Comment by memsharded** [comment]
Hi @pgeler 

It seems you are running Conan using https://docs.conan.io/en/latest/installation.html#install-from-source. I would say this has remain there in the docs for some time even if it is quite outdated.
When running from source, it is good enough to do:

```bash
$ git clone https://github.com/conan-io/conan.git conansrc
$ cd conansrc
$ pip install -e .
```

Can you please try that instead of using a script and let us know if this works? I am going to remove the old way from the docs now

**Comment by memsharded** [comment]
Submitting PR https://github.com/conan-io/docs/pull/1971

**Comment by pgeler** [comment]
Hi @memsharded,

thanks for quick response!

I'm using pip packaging and installing it as Install with pip : https://docs.conan.io/en/latest/installation.html#install-with-pip-recommended:

`pip3 install conan --upgrade`

I was thinking this is some python packaging issue, but after:

`pip3 install conan=1.31.4 --upgrade` problem is gone

same problem after clean re-install:

`rm -rf ~/.local/* && pip3 install conan --upgrade`

**Comment by memsharded** [comment]
Oh, I see. 

Latest Conan 1.32 introduced the ``from conan.tools.xxx`` imports for new toolchains and generators, and it might conflict with some repo or script name, but not with the regular ``pip`` installation.

In this case, it seems there is an external script in ``File "/mnt/d/git/qb/scripts/conan.py", line 4,`` that is causing the issue. What is this is script, why is it there? The ``pip install`` shouldn't be using this, but instead some ``conan`` executable that it creates.

**Comment by pgeler** [comment]
conan.py: scrip was submitted in my original request: 

````
#!/usr/bin/python

import sys
from conans.client.command import main

main(sys.argv[1:])
````
 
and line 4 is exactly `from conans.client.command import main`

unfortunately we cannot use conan binary directly, we need a shared solution across different platforms and setups, this was one of the approaches to avoid problems with different python environments, py executors etc

but I it looks like as a workaround we can import conans.conan and use run()  instead, will it work on windows 🤔?

**Comment by memsharded** [comment]
> unfortunately we cannot use conan binary directly, we need a shared solution across different platforms and setups, this was one of the approaches to avoid problems with different python environments, py executors etc

Regarding this, it would be useful to know which platforms do not support or work with the ``pip install -e .`` and what are the failures and errors, to learn about them and be aware of that, that could help us to support other users with same issues. At least in Windows, Linux and Mac it works pretty well, so in case your proposed workaround doesn't (I guess it should work as well), you could try that.

**Comment by pgeler** [comment]
we are not using conan from sources we are using conan from pip packages.

The problem is that we are using conan modules instead of conan executable, as we found this is most convenient way to do it across different platforms and different setups: dev, VM's, etc...

in Windows most applicable solution we found is to use `py`. For us it all works through `py -m pip install conan` .... and `py conan.py ...`  where `conan.py`(from my previous message), as simple as execute `main()` from `conans..client.command`
, other ways (aka updating PATH variables, use python user env or know where exactly pip installed conan) are more complicated and do not work for all of our use cases

Linux solution I mentioned, was more to keep, a single way of doing things instead of introducing platform dependency across our environments

**Comment by pgeler** [comment]
problem solved by renaming out conan.py to conan_cmd.py ...

**Comment by memsharded** [comment]
Thanks very much @pgeler for the feedback and following up with your solution.
