### ISSUE TITLE
Create package with dependency on boost >=1.69.0 fails

### ISSUE THREAD

**Issue by jarrettchisholm** [conan-io/conan#8265]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 64 bit
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.32.1
  * Python version: 3.9.1

### Steps to reproduce (Include if Applicable)
Attempt to create the package:

    conan create . icebreakersentertainment/stable

I'm getting an issue when I try to create a package on Windows 10 that has a dependency on boost >=1.69.0.

If I already have boost installed, it works fine. If boost is not installed, it will freeze and then error out. If I change the version of boost to be equal to 1.69.0, it works fine.

My conanfile.py looks like this:

```
from conans import ConanFile, CMake, tools


class CtplConan(ConanFile):
    name = "ctpl"
    version = "0.0.2"
    license = "Apache-2.0"
    author = "<Put your name here> <And your email here>"
    url = "https://github.com/icebreakersentertainment/CTPL"
    description = "<Description of Ctpl here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    requires = "boost/[>=1.69.0]"
    exports_sources = "include/*"
    no_copy_source = True

    def source(self):
        self.run("git clone https://github.com/icebreakersentertainment/CTPL.git")

    def package(self):
        self.copy("*.h", dst="include", src="")
        pass

    def package_id(self):
        self.info.header_only()
```

If I change the requires line to `requires = "boost/1.69.0"`, it succeeds.

### Logs (Executed commands with output) (Include/Attach if Applicable)

> \> conan create ..\conan\ctpl\ icebreakersentertainment/stable
> Exporting package recipe
> ctpl/0.0.2@icebreakersentertainment/stable: A new conanfile.py version was exported
> ctpl/0.0.2@icebreakersentertainment/stable: Folder: C:\Users\Jarrett\\.conan\data\ctpl\0.0.2\icebreakersentertainment\stable\export
> ctpl/0.0.2@icebreakersentertainment/stable: Exported revision: bf15afd4333b1f817f7aad5c7824f6f3
> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Release
> compiler=Visual Studio
> compiler.runtime=MD
> compiler.version=16
> os=Windows
> os_build=Windows
> [options]
> [build_requires]
> [env]
> 
> ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search?q=boost%2F%2A&ignorecase=False (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))
> 
> Unable to connect to conan-center=https://conan.bintray.com
> 1. Make sure the remote is reachable or,
> 2. Disable it by using conan remote disable,
> Then try again.

**Comment by czoido** [comment]
Hi @jarrettchisholm,

Thanks a lot for reporting. This issue is he same as the reported behaviour here: https://github.com/conan-io/conan-center-index/issues/950, https://github.com/conan-io/conan/issues/7774, https://github.com/conan-io/conan/issues/7573
Searching with version ranges in bintray repository is a significant bottleneck, the only available temporary workaround right now is increasing the `CONAN_REQUEST_TIMEOUT` or using fixed versions.
We are trying to fix this issue but  as it is a complex issue that requires changes in the backend it will take some time.

**Comment by memsharded** [comment]
It is also very recommended for production to not depend directly on Bintray in production, but cache the used dependencies in your own server. Artifactory CE can set up a remote repository to proxy bintray ConanCenter, or you could "conan download" from ConanCenter + "conan upload" to your server your dependencies. 

This is a general best practice for package management for all platforms and packages, for example now that Dockerhub has some usage limits, it is good to cache the images that you need in production and CI in your own server, to not be affected.

**Comment by utopius** [comment]
Hi @memsharded,
We have such problems as well. Not with bintray but with our internal Artifactory (6.18.1). 
As soon as we use version-ranges sporadic timeout errors occur.

I searched for known issues regarding our Artifactory version or similar reports regarding Conan but this ticket matches our problem exactly except it's Artifactory instead of bintray.

Any hint would be appreciated.

**Comment by czoido** [comment]
Hi @utopius,

There's an issue currently open that degrades the performance of resolution of version-ranges in packages for large amounts of artifacts: https://www.jfrog.com/jira/browse/RTFACT-19531
Also reported in: https://github.com/conan-io/conan/issues/5432 and https://github.com/conan-io/conan/issues/8505

While we are working with the Artifactory team to get this fixed, maybe this could be related to the DB you are using. Maybe the embedded Derby DB won't scale very well, and using a Postgresql could help. Which order of magnitude of artifacts do you have?

**Comment by utopius** [comment]
Hi @czoido,

thanks for linking the issue. Our Artifactory instance is serving roughly 30 million artifacts, Conan packages being a small fraction of the total packages afaik. So, I doubt that an embedded DB is used, but I don't know.

I will try to gather more information on our instance from the responsible team and let you know.

Any idea when https://www.jfrog.com/jira/browse/RTFACT-19531 will be addressed?

**Comment by utopius** [comment]
Hi @czoido,

I got some more details now, not sure if they will help, but I promised to deliver them:

- Artifactory is a 3-node cluster 
- The database is driven by a Oracle 12c cluster
- The binary storage is a shared (nas?) instance with roughly ~50TB NFS available

Our colleagues will get in touch with jFrog regarding Artifactory improvements / bugfixes.

**Comment by memsharded** [comment]
The performance problem for resolving version ranges was solved some time ago, both in Artifactory and ConanCenter, closing this ticket as solved.
