### ISSUE TITLE
[question] Unit tests outside recipe and gtest dependency

### ISSUE THREAD

**Issue by GPages** [conan-io/conan#8268]
Conan documentation suggests following video: 
https://www.youtube.com/watch?v=S4QSKLXdTtA&feature=emb_title&ab_channel=CppCon

I've tried to use the same file hierarchy shown at slide 22 (~19 minutes) 

```
myLibrary/
├── src/
│   ├── CMakeLists.txt
│   └── (...)
├── test/
│   ├── CMakeLists.txt <== standalone (uses find_package(GTest) and include(GoogleTest))
│   └── (...)
├── test_package/
└── conanfile.py         <== (exports_sources="src/*  build_requires="gtest/1.8.1@bincrafters/stable"")
└── CMakeLists.txt     <== dev entry point (add_subdirectory(src) then add_subdirectory(test) )
```

I'm really confused about the unit tests management.
According to Mateusz Pusz the test folder should be a standalone, therefore there is no call to conan function or linking to conan libraries in the CMakeLists.txt (slide 24 ~22minutes).

So if i'm not mistaken this requires gtest to be installed on the system. But in this case what is the use of specying it in "build_requires" (either from profile or in the recipe) ? Ideally i would like to used the conan gtest package rather than installing gtest on the CI server.

The slide 91 (~58 minutes) added even more confusion. Could you please clarify a bit what is going on here ? I'm not sure wether the structure is good but poorly applied by me or if i should simply use another.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @GPages 

In order for tests to be build and run while creating the package, the first important bit is that they should be exported together with the recipe. Let me summarize the high level view:

- test folder should be exported in the same way as the source ``exports_sources = "src/*", "test/*", "CMakeLists.txt"``
- The ``build()`` method will be calling the build system, CMake, and the ``build()`` method is the right place to be building and running the unittests. As the tests shouldn't condition or affect the final library binaries, you could use a mechanism, like an env-var to control if they are actually built and run or not.
- The ``test`` code can use ``find_package(GTest)``, if the *conanfile.py* is using the ``cmake_find_package`` or the ``cmake_find_package_multi`` generator. When using Conan, this generator will create in the build folder Cmake find scripts on the fly.
-  It is necessary to tell cmake to find the generated cmake scripts, typically something like ``set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR} ${CMAKE_MODULE_PATH})`` is good for this.
- Then you don't need to have GTest installed in the system, Conan will find it in the ``build_requires``.

Please let me know if this clarifies the issue a bit or if you have further questions.

**Comment by GPages** [comment]
Thank you for this clear answer, i wasn't sure about the interactions with cmake and CI pipelines (newcomer here) but now it makes sense.

It should be fine now, thanks 👍

**Comment by memsharded** [comment]
Ok, great :)

Then I think this question can be closed now, don't hesitate to open new issues for further questions. Thanks!
