### ISSUE TITLE
[bug] simple typo in error message "contraining"

### ISSUE THREAD

**Issue by andioz** [conan-io/conan#8271]
### Environment Details
  * Operating System+version: all
  * Compiler+version: all
  * Conan version: newest
  * Python version: all

### Steps to reproduce

Don't know how to reproduce, it showed up in issue https://github.com/conan-io/conan-center-index/issues/3996

### Logs

See issue mentioned above

### Actions

I you don't mind I would add a PR for this and change it to `constraining`?

**Comment by memsharded** [comment]
Hi @andioz 

Sure, that PR will be welcome. Please do search for that typo, it happens there is a test checking that typo as well (copy & paste effect).

**Comment by andioz** [comment]
> Hi @andioz
> 
> Sure, that PR will be welcome. Please do search for that typo, it happens there is a test checking that typo as well (copy & paste effect).

Yes I did, found it twice :)

**Comment by andioz** [comment]
~~@conan-io/barbarians shall I wait until staged to "queue" as mentions in contribution guide or just add PR?~~

PR created :) https://github.com/conan-io/conan/pull/8273
