### ISSUE TITLE
[feature] Support resolving conflicts between different packages that provide the same feature

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#8275]
Conan v1.28 introduced the support for [provides attribute](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#provides) which allows for multiple recipes to provide the same functionality and thus avoid ODR violations.

This is a great feature, but currently supports only reporting an error if multiple libraries in the graph provide the same functionality, but does not support resolving that error.

For example, if `conan install` for my package raises the following error:

```
At least two recipes provides the same functionality:
 - 'libjpeg' provided by 'libjpeg/9d', 'libjpeg-turbo/2.0.5'
```

I can only wait for all dependencies of my packages to agree on either using `libjpeg` or `libjpeg-turbo`.

I think it would be great if my package could somehow "override" the dependencies by selecting only one of those packages. In the example above, my package would override to use `libjpeg-turbo/2.0.5` and that should inform conan to replace `libjpeg/9d` in entire graph with `libjpeg-turbo/2.0.5`, just like it does when it encounters a conflict between multiple different versions of the same package.

**Comment by AbrilRBS** [comment]
Closing this as solved in Conan 2.
While most CCI recipes have landed on (somewhat) consistent namings for the options that control the alternative behaviours you mention such as jpeg libs, Conan 2 introduced the `[replace_requires]` ([docs here](https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires)) section in the profiles that allows users to specify graphwide replacements based on simple conditions. We feel that this is enough to tackle most cases, but do let us know if you have any feedback regarding similar cases, we're always happy to listen :)
