### ISSUE TITLE
[question] version.py "from semver import SemVer" errors on SemVer not found

### ISSUE THREAD

**Issue by bdebruyn** [conan-io/conan#8277]
conan/conans/client/tools/version.py has the following import statement: "from semver import SemVer". The only semver.py file I've found is https://pypi.org/search/?q=semver, which does not have a class called "SemVer". Curious to know where you are pulling the semver.py. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @bdebruyn 

Check the ``requirements.txt`` file. The dependency is ``node-semver==0.6.1``

**Comment by bdebruyn** [comment]
resolves #8277  Many thanks for pointing me to the file. Very helpful.

**Comment by ds-trietly** [comment]
Why do I receive the error now for `conan 2.16.1`?

The requirements.txt no longer has this dependency. But when i manually install `node-semver==0.6.1` then it works.

**Comment by memsharded** [comment]
No idea @MinhTriet-Ly, maybe you are using a legacy recipe that has that import directly in the recipe?
please create new tickets to report these kind of things, better than on a closed ticket. Thanks!
