### ISSUE TITLE
[question] Variables in conan.conf?

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#8282]
Can the conan.conf file use variables of any kind? Specifically I'd like to be able to do something like this:

`path = /scratchnobackup/conan_data_${USERNAME}`

That would allow me to have a common Conan configuration in a Conan settings repo for all developers to use, with their username being appended to the Conan data folder.

Thanks

**Comment by czoido** [comment]
Hi @radonish,
Right now is not possible to use that kind of variables, the only workaround is doing a `conan config set storage.path=/scratchnobackup/conan_data_$
USERNAME` after the `conan config install ...` from the git repo.

**Comment by AbrilRBS** [comment]
The new `global.conf` file allows to use Jinja2 template system and provides access to the `platform`and `os` packages for further extension. See https://docs.conan.io/2/reference/config_files/global_conf.html#configuration-file-template for more info, closing as completed :)
