### ISSUE TITLE
Multiple compilers supporting the same ABI on Windows ( MVSC, icl (Intel) and clang-cl)

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#8291]
I have seen a number of issues regarding clang:
 - https://github.com/conan-io/conan/pull/8218
 - https://github.com/conan-io/conan/issues/5896

But Intel also produces ABI compatible compilers ... and they are all FREE under the OneAPI package. 

So now lets say I wanted to use Bincrafters Qt libs built for MSVC, they should work with "Clang-cl" OR "icl". 

I see where there is an experimental feature to me to use a range of versions, but how do I use a range of compilers?

Thanks and regards

**Comment by jgsogo** [comment]
Hi! You can have a look to the `compatible_packages` feature: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=compatible_packages#compatible-packages. Conan will generate different `package_id` for different compilers, but it will fallback to other `package_ids` if some of them is missing. Let me know if this is related to what you are looking for.

Thanks.

**Comment by ShamanTcler** [comment]
It is related, in fact I mentioned it ;)

The questions are:

1) will compatible_packages support different compilers names or is it just limited to compiler versions.
2) compatible_packages is marked "experimental" ... so just how experimental is it? Will if be a standard in version 2?

**Comment by memsharded** [comment]
Hi @ShamanTcler 

Yes, indeed the current implementation of the new ``msvc`` compiler setting is using ``compatible_packages`` to fall back to ``Visual Studio`` binaries: https://github.com/conan-io/conan/pull/8201. The internal management of intel compiler is also a fallback to the gcc or Visual Studio compiler via ``compatible_packages``.

I would say ``compatible_packages`` is here to stay, and will be in Conan 2.0, no plans to deprecate or remove it. It might be possible that it gets some changes in the UI, but nothing planned at the moment, only if necessary.

**Comment by ShamanTcler** [comment]
Thanks EXACTLY what I was looking for

**Comment by jgsogo** [comment]
Good! I'm closing the issue then, but feel free to open it again if you need help defining those compatible packages.

The example in the documentation is modifying the compiler-version, but you can modify whatever you want from the `info` object (settings and options).
