### ISSUE TITLE
Consider allowing .conanfile.txt

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#83]
Hi Conaneros,

More of a request for comments than anything else, really. I find I have a lot of files in the root of my project, for different CI systems, CMake files, etc. It just becomes a bit messy and I'm a bit OCD :-) Due to this I am trying to minimise at least the number of visible files. I'm wondering if you think that conan should support .conanfile.txt in addition to conanfile.txt or if this just makes it harder for users to know that a project uses conan?

Thanks for your time

Marco

**Comment by mcraveiro** [comment]
I'll close this ticket since #115 is sufficient for this. Obrigado!

**Comment by memsharded** [comment]
Included in release 0.7, just in case you want to test it, thanks!

**Comment by mcraveiro** [comment]
Success! [1] You guys rock, thanks! :-D

[1] https://travis-ci.org/DomainDrivenConsulting/dogen/jobs/107194308

**Comment by memsharded** [comment]
:) :) :) :)
