### ISSUE TITLE
[bug] "ERROR: Failed to parse: remote-url/v1/ping" from WSL2

### ISSUE THREAD

**Issue by seflue** [conan-io/conan#8302]
When I try to run conan from WSL2 with Ubuntu 20.04 in Windows 10 it fails, when it tries to ping-check the remote url with:

ERROR: Failed to parse: https://conan.bintray.com/v1/ping

Running the same statement from a virtual machine (also Ubuntu 20.04) works fine.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 with WSL2 running Ubuntu 20.04
  * Conan version: 1.32.1
  * Python version: 3.8.5

### Steps to reproduce

After installing conan via pip3 and enabling conan-center in WSL2:
```
conan search -r all catch2/*
```

But any other command which tries to access https://conan.bintray.com/v1/ping would fail also with the same error message.

### Logs
```
ERROR: Failed to parse: https://conan.bintray.com/v1/ping. [Remote: conan-center]
```

**Comment by memsharded** [comment]
Hi @seflue 

It could be an issue of the dependencies, installed in the WSL2. How did you install Conan, via pip?
Could you compare the Conan dependencies, with something like ``pip list`` in both the WSL and the VM?

Thanks!

**Comment by seflue** [comment]
Yes, I installed it with pip in both environments, WSL2 and in the VM.

And interestingly the dependencies are actually different. I try to compile a short and clear overview of these differences and keep you updated. Thanks already for your help.

**Comment by seflue** [comment]
Ok, I found the issue. The version of the package 'six', which is required by 'fastener' was only on 1.11.0 in WSL2 while it was on 1.14.0 in the VM. When I upgraded it, all worked fine. I did also downgrade 'six' in my VM and got the same error as in WSL2 before. When I upgraded it again, the error vanished.

So maybe the dependencies should be set a bit tighter, because 'fastener' accepts 'six' in any version.

**Comment by jgsogo** [comment]
FYI, I've tried in MacOS and it works with `six==1.11.0` and `fasteners==0.15`.

We are [deprecating Python 2 in Conan v2.0](https://github.com/conan-io/tribe/blob/main/design/003-codebase-python.md), I would expect getting rid of the `six` requirement too. In Conan 2.0 we should probably upgrade `fasteners` requirement to a newer version (likely by that time `>0.16` which drops support for Python 2 as well and removes `six` dependency).

**Comment by memsharded** [comment]
six 1.11.0 also seems to work fine in Windows at least. Seems specific to Linux.

I have labeled this as Conan 2.0, where six will be removed and this will be gone. Not worth to change this now, which could break other users that depend on older six versions.

**Comment by seflue** [comment]
Strange, that the error occurs only in Linux environment. Thank you @memsharded for your help. And at least now the error is googlable. 😉

**Comment by memsharded** [comment]
Six is no longer a direct dependency (still a transitive one):

```
 python-dateutil [required: >=2.7.0,<3, installed: 2.8.2]
    - six [required: >=1.5, installed: 1.16.0]
```
It seems difficult to get rid of it:
- We need dateutil to parse ISO 8061 dates from server (revisions timestamps). This cannot be changed anytime soon
- Dateutil still depends on six, cause it still supports Python 2.7

But as long as we don't use ``six`` anymore, the version shouldn't be an issue anymore, so I think we can close this ticket, nothing we can done on our side, and the solution to a potential problem is to upgrade the dependencies.

**Comment by memsharded** [comment]
In Python 3.7 there is a new integrated parser, but not intended for every ISO date format: https://docs.python.org/3.7/library/datetime.html#datetime.datetime.fromisoformat


> Return a [datetime](https://docs.python.org/3.7/library/datetime.html#module-datetime) corresponding to a date_string in one of the formats emitted by [date.isoformat()](https://docs.python.org/3.7/library/datetime.html#datetime.date.isoformat) and [datetime.isoformat()](https://docs.python.org/3.7/library/datetime.html#datetime.datetime.isoformat). Specifically, this function supports strings in the format(s) YYYY-MM-DD[*HH[:MM[:SS[.fff[fff]]]][+HH:MM[:SS[.ffffff]]]], where * can match any single character.

While our server time is: ``2022-12-02T14:46:04.533+0000``, so seems a viable option once we remove Python 3.6 support.
