### ISSUE TITLE
[feature] compiler.cppstd should be set to the IDE default, if not provided.

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan#8304]
All recent major IDEs (VS, XCode, Clion) pass the **default IDE** c++ language standard **settings** (-std=c++<...>)  to the compiler. [According ](https://docs.conan.io/en/latest/howtos/manage_cpp_standard.html)  Conan will detect the default language standard of compiler, if the compiler.cppstd option not set.  But it will detect the default compiler[ mode](https://github.com/conan-io/conan-center-index/pull/3977#issuecomment-756086528) only, what is not very useful.

@SSE4 

Please follow https://github.com/conan-io/conan-center-index/pull/3977

Visual Studio 2019 (default /std:c++14)
https://docs.microsoft.com/de-de/cpp/build/reference/std-specify-language-standard-version?view=msvc-160

XCode 12 (default /std:c++14)
(man clang )

Clion 2020 (default /std:c++14)
![Clion_cpp_standard](https://user-images.githubusercontent.com/52277783/104003054-34f5ae00-51a2-11eb-8dd1-37ecc55f7ab4.png)

vs. 

 C++98 (C++03) compiler defaults

https://gist.github.com/ax3l/53db9fa8a4f4c21ecc5c4100c0d93c94

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! There are many people using Conan and the compiler in the command line... and many CIs, I'm afraid we cannot change this default (sure we cannot do it in Conan 1.x, it will break behavior) and IMHO it wouldn't be a good idea. Anyway, the default is just the value chosen in the autodetect process and written to the file `<cache>/profiles/default`, you can change that profile and then your _default_ will be different.

In Conan 2.0 (not 100% decided yet, but) it is likely we will stop auto-detecting automatically the default profile and it will be an explicit operation requiring confirmation by the user. So this should no longer be an issue.

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, in which `conan profile detect` must be run before being able to use Conan, which properly shows the detected configuration. Note that also recent improvements over the way profiles are handled (They are Jinja templates now) and the addition of the `detect_api` to be used within the profiles leaves lots of customization for power users :)
