### ISSUE TITLE
Subdirectories matching package name mess up 'conan remove mypkg/*'

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#831]
create the following structure:
```
zazz/
|
---conanfile.py
---zazz/
    |
    --- matazz.txt
```
where conanfile.py contains:

```python
from conans import ConanFile

class zazz(ConanFile):
   name="zazz"
   version="1.0"
   exports = "*"

   def package(self):
      self.copy("*",dst="",src="")
```

then do:
```bash
conan export myname/channel
```
then:
```bash
conan remove zazz/*
```
You get:
WARN: No package recipe reference matches with zazz/matazz.txt pattern

and the zazz package is not removed.

I ran into this with boost.

**Comment by memsharded** [comment]
Depending on the OS, the command line or shell might try differently the user input, not just for conan, but for other commands too. Please try adding quotes to your command:

```bash
$ conan remove "zazz/*"
```

**Comment by rconde01** [comment]
That didn't work unfortunately - same error. However,

`conan remove *`

fails, and 

`conan remove "*"`

works.

**Comment by memsharded** [comment]
Ok, we'll have a look, the thing is that the problem might be that the command line/shell is messing up, so the input to conan is already messed. In which OS are you running, and with which shell?

**Comment by rconde01** [comment]
Windows 10...cmd. I haven't tested on Linux but I can

**Comment by rconde01** [comment]
weird...I can install through pip - no problem
