### ISSUE TITLE
[bug] random assert node.package_id != PACKAGE_ID_UNKNOWN when building project

### ISSUE THREAD

**Issue by tfar** [conan-io/conan#8310]
When trying to build a project from a clean Conan cache, I sometimes receive the following error in conan:

```
package_A/1.2.1-1@something/stable: Unknown binary for package_A/1.2.1-1@something/stable, computing updated ID
package_A/1.2.1-1@something/stable: Updated ID: Package_ID_unknown
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/conans/client/command.py", line 2115, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.9/site-packages/conans/client/command.py", line 495, in install
    info = self._conan.install(path=args.path_or_reference,
  File "/usr/local/lib/python3.9/site-packages/conans/client/conan_api.py", line 94, in wrapper
    return f(api, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/conans/client/conan_api.py", line 598, in install
    deps_install(app=self.app,
  File "/usr/local/lib/python3.9/site-packages/conans/client/manager.py", line 77, in deps_install
    installer.install(deps_graph, remotes, build_modes, update, keep_build=keep_build,
  File "/usr/local/lib/python3.9/site-packages/conans/client/installer.py", line 305, in install
    self._build(nodes_by_level, keep_build, root_node, graph_info, remotes, build_mode, update)
  File "/usr/local/lib/python3.9/site-packages/conans/client/installer.py", lineERROR: 
 433, in _build
    self._binaries_analyzer.reevaluate_node(node, remotes, build_mode, update)
  File "/usr/local/lib/python3.9/site-packages/conans/client/graph/graph_binaries.py", line 401, in reevaluate_node
    assert node.package_id != PACKAGE_ID_UNKNOWN
```

### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 11.1
  * Compiler+version:  AppleClang 12.
  * Conan version: Conan version 1.32.1
  * Python version: Python 3.9.1

I also ran:
`conan config set general.full_transitive_package_id=1`

I wonder why a) this error happens at all and why b) it only happens randomly from a clean conan cache (data) directory.

**Comment by memsharded** [comment]
Hi @tfar 

This error might happen when you have enabled ``default_package_id_mode=package_revision_mode``.
That assert is there to ensure the data is ok, so if hitting that line, there is something indeed not working correctly in Conan.

The only thing is that it shouldn't be random at all, but very reproducible. Specially if it can happen in a clean cache, it should happen always running the same commands with the same recipes.

We would need a bit more information, to try to reproduce the issue. Can you please see if there is some way you can reproduce it that you could share with us? Thanks!

**Comment by tfar** [comment]
All my projects have
```lang=python
    def package_id(self):
        self.info.requires.package_revision_mode()
```
in their `conanfile.py`, which might be the same as `default_package_id_mode=package_revision_mode`. 

> That assert is there to ensure the data is ok, so if hitting that line, there is something indeed not working correctly in Conan.

What could cause the data not being correct?

> The only thing is that it shouldn't be random at all, but very reproducible. Specially if it can happen in a clean cache, it should happen always running the same commands with the same recipes.

Well. Specifically I run `rm -rfd ~/.conan/data/* && rm -rfd build && and make` which runs cmake & conan. Sometimes this succeeds. Sometimes I get the error mentioned in the ticket.

I'm happy to add some `print` debugging output in conan source to debug this if you got recommendations where to add them.

**Comment by tfar** [comment]
@memsharded Any pointers where it would be sensible to continue debugging this issue?

**Comment by memsharded** [comment]
Hi @tfar 

I am trying to reproduce it in a test, but no success so far.
I am interested in what happens before the error trace that you are pasting. The possibility is that there is some other package upstream that didn't succesfully build, or something happen, that they keep their package_id = Unknown. Could you please upload the whole output of the failing command?

**Comment by tfar** [comment]
Hi @memsharded,

i can share this sanitized log of the failing command with you: https://nx4631.your-storageshare.de/s/poEz2biGfM9mkDW 
All the `...` runs where just the successful build log messages. The projects all build successfully.

If you have any questions let me know. If you want I can share sanitized versions of specific `conanfile.py` if you want to.

I'm happy to modify my conan installation with some `print()` debug messages if that helps.

Thanks in advance.

**Comment by memsharded** [comment]
Hi @tfar 

Sure, if you can please run the same from my branch (https://github.com/memsharded/conan/tree/traces/package_id_unknown), that I have added a few prints there (or apply the patch below), and run again, I will have a look at the output, maybe I can find some hint there.

Many thanks for all the feedback!

```diff
diff --git a/conans/client/installer.py b/conans/client/installer.py
index c89fb9189..301087f00 100644
--- a/conans/client/installer.py
+++ b/conans/client/installer.py
@@ -439,6 +439,8 @@ class BinaryInstaller(object):
                     _handle_system_requirements(conan_file, node.pref, self._cache, output)
                     self._handle_node_cache(node, keep_build, processed_package_refs, remotes)

+                print("Installer._build", node.ref, node.package_id, node.prev)
+
         # Finally, propagate information to root node (ref=None)
         self._propagate_info(root_node, using_build_profile)

diff --git a/conans/model/info.py b/conans/model/info.py
index 8eabacdc7..326a857a5 100644
--- a/conans/model/info.py
+++ b/conans/model/info.py
@@ -65,6 +65,7 @@ class RequirementInfo(object):
     @property
     def sha(self):
         if self.package_id == PACKAGE_ID_UNKNOWN or self.package_revision == PREV_UNKNOWN:
+            print("RequirementInfo.sha return None", self.package_id, self.package_revision)
             return None
         if self.package_id == PACKAGE_ID_INVALID:
             return PACKAGE_ID_INVALID
@@ -159,6 +160,7 @@ class RequirementInfo(object):
         self.recipe_revision = self.full_recipe_revision
         # It is requested to use, but not defined (binary not build yet)
         self.package_revision = self.full_package_revision or PREV_UNKNOWN
+        print("RequirementInfo.package_revision ", self.name, self.version, self.package_revision)
```

**Comment by tfar** [comment]
Hi @memsharded

Thanks for creating that branch. I've created the linked log using your branch with commit `commit a6285d90718bac35884714167a601c9926c83f23 (HEAD -> traces/package_id_unknown, origin/traces/package_id_unknown)`.

Here is the log: https://nx4631.your-storageshare.de/s/BWmsGLmMyzpH9bm

Thanks for looking into this. If there is anything else I can do, let me know.

**Comment by memsharded** [comment]
Good info! For a start, I can localize the offending one:
```
Packages
    ProjectGT/1.8.1-2@company/stable:6e2ed8c7b52ccd4fd39d32711bca9003af759961 - Build
Build requirements
    ProjectGT/1.8.1-2@company/stable from 'company' - Cache
    ProjectGT/1.8.1-3@company/stable from 'company' - Downloaded
Build requirements packages
    ProjectGT/1.8.1-2@company/stable:6e2ed8c7b52ccd4fd39d32711bca9003af759961 - Build
    ProjectGT/1.8.1-3@company/stable:6e2ed8c7b52ccd4fd39d32711bca9003af759961 - Build
....
ProjectG/1.2.1-1@company/stable: Unknown binary for ProjectG/1.2.1-1@company/stable, computing updated ID
RequirementInfo.package_revision  ProjectO 1.1.1g-0 b93696cf7dc3aa63edee4dcb9a560b04
RequirementInfo.package_revision  ProjectX 2.9.1-4 eab0c544b3a911997877ec00bd7329e0
RequirementInfo.package_revision  company_cmake 1.0.trunk-4 46e4f3444eb74d289c5f4eb893dbbac9
RequirementInfo.package_revision  ProjectR 1.0.trunk-9 bf30ed8998b33709594813c53605bb30
RequirementInfo.package_revision  ProjectS 5.0.trunk-8 6f248f2514eafa4c28b65c87a41f5c8f
RequirementInfo.package_revision  ProjectIS 1.0.trunk-2 16980844e25dd3246e470e6f30e08ae5
RequirementInfo.package_revision  ProjectGT 1.8.1-2 PREV unknown
RequirementInfo.package_revision  ProjectB 1.69.0-2 9702e2c6b1f464d02dfb369d0e617f08
RequirementInfo.package_revision  ProjectRJ 1.1.trunk-2 155439eb3d508040f75e6aef5d568393
RequirementInfo.sha return None 6e2ed8c7b52ccd4fd39d32711bca9003af759961 PREV unknown
ProjectG/1.2.1-1@company/stable: Updated ID: Package_ID_unknown
```
It seems it could be an issue of having the same package as build_requirement and as a requirement. When it is being updated, only one of them get the package_revision.

I think I can try to reproduce with this new insight, thanks!

**Comment by memsharded** [comment]
Great news!

Thanks to your debugging, I have been able to reproduce and submit a fix in https://github.com/conan-io/conan/pull/8358. I am proposing it for 1.33, but it is about to be closed, not sure if possible, if not, I will try to propose it for next patch release. Thanks very much for all the efforts!

**Comment by tfar** [comment]
@memsharded Thank you. Just verified this with your branch with the fix. #8358 seems to fix the issue for me. Thanks for the quick fix. I did three runs from a clean cache and they all succeeded.
