### ISSUE TITLE
[bug] Inject PIC through CMake helper if shared and fPIC option not exists

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#8316]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

`definitions["CONAN_CMAKE_POSITION_INDEPENDENT_CODE"] = True` should be injected if not Windows, shared option exists but not fPIC option.

Indeed, CMake files of projects might rely on intermediate OBJECT or STATIC targets linked into SHARED targets.

So basically remove this condition: https://github.com/conan-io/conan/blob/41315b6b90a20404665c125dd6ac30d1b30fd6a7/conans/client/build/cmake_flags.py#L371

**Comment by madebr** [comment]
Please don't do this automatically.
Always allow for an override.
How about the following?
```python
class CMake:
    def __init__(self, conanfile):
        self.fpic = conanfile.options.get_safe("fPIC", True)
    def configure(self):
        ...
        if self.fpic:
            defs.append("CONAN_CMAKE_POSITION_INDEPENDENT_CODE=1")
        ...
```

Thanks.

**Comment by SSE4** [comment]
@SpaceIm do you think if this change could be breaking?

**Comment by dvirtz** [comment]
same should be done for autotools:
https://github.com/conan-io/conan/blob/3f90d6e5e24b0bb244fde6edf03a09e7f6c63e32/conans/client/build/autotools_environment.py#L84

**Comment by memsharded** [comment]
Closing as outdated.
