### ISSUE TITLE
[feature] lock files should contain (optional) a remote 

### ISSUE THREAD

**Issue by a4z** [conan-io/conan#8318]
Installing dependencies via a lock file is awesome, the lockfile contains the whole profile information, and package revisions, so when distributing lock files to a project, a project is nearly independent of the config a developer has on their machine.

Back then , I needed to setup everything local
```
conan config set general.revisions_enabled=True
conan config set general.default_package_id_mode=full_version_mode
conan remote add name url
```
publish the config, and make users run `conan config install. ...` 

while `conan config install` solves a lot , it does not solve the problem when things change, and people forget to update the config.

this has some problems, mostly, developers are not perfect, and they forget. 
configurations might change, profiles certainty do, remote url might need an update

lockfiles seem to take most things away, things like revisions_enabled, default_package_id_mode and pofiles should not influence the result when installing dependencies via a lockfile.

But the remote is not part of a lockfile, this comes still from a user.

It would be awesome being able to also add a remote (optional) to a lockfile, so a project can be self containing, and a user just needs to have conan installed ....

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by blackliner** [comment]
> while conan config install solves a lot , it does not solve the problem when things change, and people forget to update the config.

We have this in our build script, to ensure reproducibility:
`conan config install conan/config` with 2 files in that folder:
`conan.conf`:
```
[general]
parallel_download = 8
revisions_enabled = 1
default_package_id_mode = full_version_mode
```
`remotes.txt`:
```
conan-center https://conan.bintray.com true
conan-community https://api.bintray.com/conan/conan-community/conan true
bincrafters https://api.bintray.com/conan/bincrafters/public-conan true
```

**Comment by a4z** [comment]
the basic idea is to not need such work arounds, a user/developer can configure whatever they want, but when working with the_project, they install dependencies via a lockfile, and all the infos are there, in the lockfile.

**Comment by memsharded** [comment]
Closing as not planned, lockfiles in Conan 2 as remote-agnostic, but the recipe-revisions would guarantee getting it from any remote with reproducible guarantees. Also the ``config`` (including remotes definition) can be versioned and locked with ``conan config install-pkg`` mechanism.
