### ISSUE TITLE
Exception thrown, no details in log on CONAN_VERBOSE_TRACEBACK=True, getting "True" on screen only

### ISSUE THREAD

**Issue by mb78** [conan-io/conan#8327]
Hi, I'm not getting details from the exception at this line:
https://github.com/conan-io/conan/blob/2c7dd17388c2c682fca80834726521725509ef1a/conans/client/graph/graph_builder.py#L247

self._conflicting_references() can return True when node.ref==None and previous.ref.copy_clear_rev() != new_ref.copy_clear_rev()

conanfile.txt contained lib/version in build_requires and lib/version@user/channel in requires section

**Comment by jgsogo** [comment]
Hi! Can you share a minimum reproducible example with the inputs you provide to Conan (recipes, profile, command line) and the error you get? I appreciate you digging into sources and finding the line that fails, but I need more context to be able to reproduce the error.

Thanks!

**Comment by mb78** [comment]
Hi Javier, I made a .tgz, please unpack it and
* execute ./run.sh
* first libaaa gets built and exported to conan cache as libaaa/1.0.0@michal/test2, then also as libaaa/1.0.0 (might be the only root cause that leads to throwing bool exception, not string)
* then there's attempt to build executable bbb from another dir
* see comments in run.sh and bbb/conanfile.txt with guesses which circumstances lead to the error

The output is like
------------------------------
+ conan install --generator cmake --build=missing ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: True
-----------------------------
with conan-1.32.1, probably with olders too
It's not a big issue, I found the problem in my conanfile but it took time while I expect conan should provide more details,
at least which package caused that.

Thanks
Michal

**Comment by memsharded** [comment]
Closing this as outdated, Conan 2.0 uses ``-vvvv`` verbose levels, Debug log level will print the traceback too.
