### ISSUE TITLE
[feature] Retry most http requests

### ISSUE THREAD

**Issue by Fefer-Ivan** [conan-io/conan#8330]
Currently our CI builds sometimes fail after conan failed on simple http requests to our artifactory instance despite having reasonable general.retry and general.retry_wait config values.

After inspecting the code, I have learned that retries are implemented for file upload and download queries and
when creating requests.HTTPAdapter:
`            adapter = HTTPAdapter(max_retries=config.retry)`
https://github.com/conan-io/conan/blob/develop/conans/client/rest/conan_requester.py#L28

But requests documentation states:
> Note, this applies only to failed DNS lookups, socket connections and connection timeouts, never to requests where data has made it to the server. By default, Requests does not retry failed connections. If you need granular control over the conditions under which we retry a request, import urllib3’s Retry class and pass that instead.
https://2.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter

So I suggest the following:
1. Configure requests.HTTPAdapter to retry failed http requests with 5xx status codes by passing urllib3.Retry instance instead of int.
2. Maybe, if this is implemented, retry code in file_uploader.py and file_downloader.py is no longer needed because retries will be do by requests lib?

I am ready to contribute this feature myself.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @Fefer-Ivan 

Your proposal is sound and, if we can remove code from our codebase is more than welcome. If you are willing to contribute a pull-request, please, do so. Feel free to contribute a draft first before going into the details if you feel like we need to align on some implementation details.

Take into account that the current Conan v1.x series still work with python2, but if for any reason, the feature works only with Python3, we can accept it in the new branch we are preparing for Conan 2.0 where Python2 will no longer be supported. I mean, do not make the implementation much more complicated than needed.

Feel free to contact any of us with any doubt.

Thanks!
