### ISSUE TITLE
[question] how to lock build-requires in a derived 'partial' lockfile

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8335]
When integrating changes into a product in CI, I rebuild any dependent packages by calculating the build-order.  For each package that is rebuilt I want to have  a 'partial' lockfile for a package which contains all of the settings, options, dependencies, etc. needed to completely reproduce the package again in the future.  I am currently making this file like this (3rd command):

```
// rebuild downstream consumer
conan install ${ref} --build=${ref} --build=missing --lockfile=${product_lockfile} --lockfile-out=${product_lockfile_updated}

// update product lockfile with information about newly built package
conan lock update ${product_lockfile} ${product_lockfile_updated}

// derive a partial lockfile which can be used to reproduce this package later
conan lock create --reference=${ref} --lockfile=${product_lockfile_updated} --lockfile-out=${package_lockfile}
```

But it seems build requirements are missing from this lock causing rebuilding from lockfile to fail:

```conan install ${ref} --build=${ref} --lockfile=${package_lockfile}```

> ERROR: Build-require '<my_build_require>' cannot be found in lockfile

So how can I lock the build-requires of the package?  I tried to force them with a build-policy flag but it raised an error because the reference is already locked:

```
conan lock create --reference=${ref} --build=${ref} --lockfile=${product_lockfile_updated} --lockfile-out=${package_lockfile}
```

> ERROR: Cannot build '<ref>' because it is already locked in the input lockfile

**Comment by memsharded** [comment]
Hi @GordonJess 

I think this was fixed in 1.32, in the changelog:

> BugFix: Allow lockfiles to be relaxed with the –build argument. https://github.com/conan-io/conan/pull/8054 . Docs https://github.com/conan-io/docs/pull/1939/files


Can you please confirm that you are using 1.32? thanks!

**Comment by ytimenkov** [comment]
I get the message `Build-require cannot be found in lockfile` if the same requirement is both in `requires` and `build_requires`.

conanfile.py:
```python
from conans import ConanFile


class ConanTestConan(ConanFile):
    name = "conan-test"
    version = "1.0"

    requires = ["trompeloeil/39"]
    build_requires = ["trompeloeil/39"]
```

```sh
$ conan lock create --lockfile-out=deps.lock conanfile.py
...
Generated lockfile: /home/default/test/conan-repro/deps.lock


$ conan create --lockfile=deps.lock --lockfile-out=conan.lock conanfile.py 
Using lockfile: '/home/default/test/conan-repro/deps.lock'
Exporting package recipe
conan-test/1.0: A new conanfile.py version was exported
conan-test/1.0: Folder: /home/default/.conan/data/conan-test/1.0/_/_/export
conan-test/1.0: Exported revision: 237e5448909979c4438f2f65eeaed8cd
Configuration:
[settings]
[options]
[build_requires]
[env]

conan-test/1.0: Forced build from source
ERROR: Build-require 'trompeloeil' cannot be found in lockfile
```

So far it was legal. I've asked this question in https://github.com/conan-io/conan-center-index/issues/4013

**Comment by memsharded** [comment]
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
