### ISSUE TITLE
Replacing packages

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#834]
Consider this scenario:

- You upload a package
- A client downloads the package
- You realize there's a problem with the package
- You fix and re-upload the package.
- The client runs conan install, but doesn't get the new package because conan thinks they already have it

What's the correct way to deal with this?

**Comment by memsharded** [comment]
The rationale is that a package in the client cache won't be replaced unless stated explicitly by the user. The command ``conan install`` will not hit any remote if all the packages it needs are already cached locally. This is exactly what the ``--update`` optional argument to ``conan install`` does. For CI servers and things like that, it might make sense to completely wipe the cache before starting a job, to use a new temp CONAN_USER_HOME for concurrent jobs.

**Comment by rconde01** [comment]
Seems like --update is what I need. I'll give it a go.

**Comment by memsharded** [comment]
Excellent :)
