### ISSUE TITLE
[feature] conditional requirement in conanfile.txt

### ISSUE THREAD

**Issue by madduci** [conan-io/conan#8346]
I don't know if it is already possible to do, if so, please make it easier to find it in the documentation, since I haven't yet found it.

I know that this might be completely doable with a conanfile.py, but from an user perspective, without starting writing any Python code, it might be really good, especially for newcomers.

I'd like to propose as feature the possibility to specify a dependency requirement based on conditions. As Example, let's say there's a project which might require on a Windows/x86 a library A with version 1.0.0 but on Linux/ARM an additional library B with version 1.0.0 or the same library A but in a different version, let's say 1.1.0.

The conanfile.txt might look like this:

```
[requires]
libraryA/1.0.0

[conditional_requires]
libraryB/1.0.0

[conditional_options]
libraryB:shared=False
libraryB:isLinux=True
libraryB:isARM=True
```

or alternatively:

```
[requires]
libraryA/1.0.0

[conditional_requires]
linux-arm:libraryB/1.0.0

[conditional_options]
libraryB:shared=False
```

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by sourcedelica** [comment]
See https://github.com/conan-io/conan/issues/6177

**Comment by memsharded** [comment]
Hi @madduci 

While I understand the intention, with the experience we have, I can assure this is not the best approach. Inventing your own DSL for implementing conditionals over a wide range of possible conditions, always ends in something less maintainable, understandable and more error prone than the alternative. Do you really think that your conanfile.txt can beat this?

```python
from conans import ConanFile

class Pkg(ConanFile):
  settings = "os", "arch"

  def requirements(self):
    if self.settings.os == "Linux" and self.settings.arch == "arm":
       self.requires("libraryB/1.0.0")
```

In your examples there are already some ambiguities, like, for example, is ``[conditional_options]`` an ``AND`` operation or an ``OR`` one? How do I express that I want a specific requirement for Linux or FreeBSD OSs? What if users now want to condition on the build_type? or on the Compiler? This will inevitably happen and will be requested by users as well.

**Comment by madduci** [comment]
Hi @memsharded 

thanks for making it clear. Yes I know, the conan basecode would be more bloated, if it is going to support such a conanfile.txt and that the conanfile.py can handle it perfectly,  because Python is more flexible.

My whole point was to skip Python entirely, if possible, since not every IDE/Editor imports the ConanFile definitions correctly, thus making it harder to find all the possibilities available through it. Are all the ConanFile definitions/capabilities in the docs.conan.io documented?

**Comment by memsharded** [comment]
> My whole point was to skip Python entirely, if possible, since not every IDE/Editor imports the ConanFile definitions correctly, thus making it harder to find all the possibilities available through it. Are all the ConanFile definitions/capabilities in the docs.conan.io documented?

It is not possible to skip Python entirely. While some methods could be declarative (like ``exports``), the ``build()`` methods and ``package()`` are basically impossible to make it declarative. The high variability of build systems, the peculiarities of many projects make a full scripting language totally necessary, and exploring https://github.com/conan-io/conan-center-index/tree/master/recipes can make this very evident. As Python recipes are not going away and are totally core to Conan, it doesn't make sense to add more custom complex logic to ``conanfile.txt`` if it can be implemented in standard Python in ``conanfile.py``, it is even less effort for users (it is known that +50% of C++ users know some Python) that don't need to learn a custom DSL new syntax that would also be more fragile. So I think this issue can be closed, thanks very much for the feedback!

**Comment by dvirtz** [comment]
since profiles now support jinja, why not let conanfile.txt have it as well?
