### ISSUE TITLE
"Could not initialize local sqlite database" with conan --version

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#835]
Hi,

In the CI server we are using at my company we are starting to see some "locking" issues with conan from time to time. This is the message we got in one of the linux nodes:

```
...
16:56:26 ++ conan --version
16:56:31 Traceback (most recent call last):
16:56:31   File "/usr/local/bin/conan", line 11, in <module>
16:56:31     sys.exit(run())
16:56:31   File "/home/jenkins/envs/conan/local/lib/python2.7/site-packages/conans/conan.py", line 6, in run
16:56:31     main(sys.argv[1:])
16:56:31   File "/home/jenkins/envs/conan/local/lib/python2.7/site-packages/conans/client/command.py", line 1019, in main
16:56:31     command = get_command()
16:56:31   File "/home/jenkins/envs/conan/local/lib/python2.7/site-packages/conans/client/command.py", line 1006, in get_command
16:56:31     remote_manager = instance_remote_manager(client_cache)
16:56:31   File "/home/jenkins/envs/conan/local/lib/python2.7/site-packages/conans/client/command.py", line 980, in instance_remote_manager
16:56:31     localdb = LocalDB(client_cache.localdb)
16:56:31   File "/home/jenkins/envs/conan/local/lib/python2.7/site-packages/conans/client/store/localdb.py", line 13, in __init__
16:56:31     self.init()
16:56:31   File "/home/jenkins/envs/conan/local/lib/python2.7/site-packages/conans/client/store/localdb.py", line 25, in init
16:56:31     raise ConanException(message, e)
16:56:31 conans.errors.ConanException: ('Could not initialize local sqlite database', OperationalError('database is locked',))
...
```

The jenkins slave can be running several processes at the same time, but normally it is a small number. What other information can I provide you to find the root cause of this problem?

**Comment by memsharded** [comment]
Have you already upgraded to conan 0.18? We had the same locking issue that became evident under new python 3.6. Which python are you using?

**Comment by piponazo** [comment]
Yes, we upgraded all the jenkins nodes to conan 0.18. However that particular machine is running Debian Jessie where the python versions are 2.7.9 and 3.4.2.

**Comment by piponazo** [comment]
Something else that could be related with this problem is this error I just got:

```
10:44:08 ++ conan install /home/jenkins/workspace/pix4dmapper_master_branches/compiler/clang/label/linux/mode/release/pix4dmapper --update --build=missing --env EXTERNAL_DIR=/home/jenkins/workspace/pix4dmapper_master_branches/compiler/clang/label/linux/mode/release/external -r conan-server --profile clang
10:44:08 Requirements
10:44:08     Ceres/1.11.0-0@pix4d/testing from conan-server
...
10:44:08 Packages
10:44:08     Ceres/1.11.0-0@pix4d/testing:42e3e27319bddfce94af67d0ceccbc29de59407f
...
10:44:08 Ceres/1.11.0-0@pix4d/testing: WARN: Trying to remove dirty source folder
10:44:08 Ceres/1.11.0-0@pix4d/testing: WARN: This can take a while for big packages
10:44:08 Ceres/1.11.0-0@pix4d/testing: Configuring sources in /home/jenkins/.conan/data/Ceres/1.11.0-0/pix4d/testing/source
10:44:08 Cloning into 'ceres-solver'...
10:44:08 error: could not lock config file /home/jenkins/.conan/data/Ceres/1.11.0-0/pix4d/testing/source/ceres-solver/.git/config: No such file or directory
10:44:08 fatal: Could not set 'remote.origin.fetch' to '+refs/tags/1.11.0:refs/tags/1.11.0'
10:44:08 Ceres/1.11.0-0@pix4d/testing: WARN: Trying to remove dirty source folder
10:44:08 Ceres/1.11.0-0@pix4d/testing: WARN: This can take a while for big packages
10:44:08 ERROR: Ceres/1.11.0-0@pix4d/testing: Error in source() method, line 26
10:44:08 	self.run("git clone --depth 1 --branch 1.11.0 https://ceres-solver.googlesource.com/ceres-solver")
10:44:08 	Error 32768 while executing git clone --depth 1 --branch 1.11.0 https://ceres-solver.googlesource.com/ceres-solver
```

The most relevant message here is:
```
10:44:08 error: could not lock config file /home/jenkins/.conan/data/Ceres/1.11.0-0/pix4d/testing/source/ceres-solver/.git/config: No such file or directory
```

At that point we triggered a job in jenkins that was trying to build the Ceres recipe for different configurations. The same machine was trying to build two packages at the same time and it seems that conan is falling in a race condition.

**Comment by memsharded** [comment]
It might be something related to concurrency, are the multiple concurrent jobs sharing local cache? Or are they using each one their own CONAN_USER_HOME?

**Comment by piponazo** [comment]
Yes, this is what we think. We are sharing the local cache. I noticed that normally you guys use Travis for building packages of a recipe with different options. In our case we are using the same physical machine and it seems that conan is having some issues when it is runned in a parallel way in the same machine.

**Comment by memsharded** [comment]
yes, totally. Conan is not "thread-safe", it cannot be run concurrently without some things to be considered. Making conan fully concurrent could be a bit complex, and most probably very inefficient for concurrent builds, so I would suggest to have a look first at these two options:

- Using separate environments in the server machines, for different jobs/builds, whenever possible. This should be the default, for firing builds for different users, PR, etc. It doesn't make sense to mix environments, so creating a temporary folder for each new job and set it as CONAN_USER_HOME would be the correct approach.

- For concurrent tasks in the **same job** as building different configurations of the same package recipe, it is doable, but making concurrent only the heavy parts, mainly the "build". Getting the source, ``source()`` can't be run concurrently. It is done once for every recipe, so the concurrency for this should be:

```bash
$ conan export user/channel
$ conan source Pkg/0.1@user/channel
# launch concurrently
# for each settings in configurations
$ conan install -s settings
```

If using ``test_package``, it could also be done:
```bash
$ conan export user/channel
$ conan source Pkg/0.1@user/channel
# launch concurrently
# for each settings in configurations
$ conan test_package --not-export --keep-source -s settings
```
Please tell me if those approaches could be fine for your use case.

**Comment by piponazo** [comment]
I think that the first approach you presented is doable for us. We did not considered it because we were trying to minimize the downloads from out conan-server, but since we are having this problem from time to time we will try to have a clean environment for each job execution.

Thanks!

Should I close this issue once I know that conan is not "thread-safe" ?

**Comment by lasote** [comment]
I think we should close it and open another one "Make conan thread safe" to discuss the feature making reference to this issue and others like #245
