### ISSUE TITLE
[feature] Tool: create module official cmake targets

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#8360]
A build helper often used in CCI which could be part of Conan Tools.

First idea [here](https://github.com/conan-io/conan/pull/8338#discussion_r557653422).

Also present in CCI now:
https://github.com/conan-io/conan-center-index/pull/4257
https://github.com/conan-io/conan-center-index/pull/4258

```python
from conans.tools import create_module_official_cmake_targets

...

def package(self):
    create_module_official_cmake_targets(
            os.path.join(self.package_folder, "lib", "cmake", "conan-official-foo-targets.cmake"), 
            [{"official": "foo", "namespaced": "foo::foo"}]
     )
```

/cc @SpaceIm @madebr 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SSE4** [comment]
let's do it! should be safe, and we already have a working implementation, so PR shouldn't take a significant effort.
