### ISSUE TITLE
[question] Is there a way to distinct packages by 'compiler.libcxx'?

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8365]
I need to create a different package targeting libc++ instead of libstdc++. There is a slight difference in headers and library symbols my system provides from packages I already have prebuilt with libstdc++. Now I want to recompile my whole bunch of libraries using libc++'s definitions, is it possible?

**Comment by jgsogo** [comment]
Hi, @xahon 

If your recipe doesn't remove the setting `compiler`, Conan will generate different package-ID for different values of `compiler.libcxx`, for example:

```
conan search boost/1.74.0@ --table=boost.html -r conan-center
```

 As you can see in the table generated, the package-id is different for different values of `compiler.libcxx` (given the same settings for the other columns):

![image](https://user-images.githubusercontent.com/1406456/105364576-9cc5e300-5bfd-11eb-8edb-b3051175e307.png)


This is core Conan functionality: every different setting value generates a different package-id.

**Comment by xahon** [comment]
Thanks
