### ISSUE TITLE
[question] How to build a binary package from reference with self.develop == True

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#8366]
This mostly used for tools packages (like CMake): they need certain settings (namely `compiler` and `build_type`) during the build but not when consuming.

Even looking at the CMakes recipe at CCI it adjusts `package_id` by removing `compiler` setting. However  this is not enough because keeping compiler in `settings` will require specifying it at consume time because otherwise running `conan install cmake/version` will fail if default profile doesn't have any `compiler`. (Otherwise it means "I want CMake build with compiler X", which is not really relevant).

In my case default profile doesn't have compiler because it is not present in the build image by default (and comes as a Conan package) and I prefer to avoid human mistakes when one setting is overridden by different profiles depending on the order on the command line.

I work this around by removing those settings in the `configure()` method:
```python
    def configure(self):
        if not self.develop:
            self.output.info("Consuming package, removing build-time settings")
            del self.settings.build_type
            del self.settings.compiler
```

But `self.develop` is defined only when using `conan create` command.

Building a reference is also widely shown in lockfiles examples in form `conan install libd/0.1@user/testing --build=libd/0.1@user/testing`.

I work this around by always running `conan create --not-export` on a path in the cache (this one returned from `conan info --paths`), but now it starts feeling too hackish (not to mention that requiring a valid set of settings to just get path to the export folder is an overkill).

Another option could be to allow `None` but then I would need to signal that I do need a compiler at build time (which is now handled by throwing `ConanInvalidConfiguration` in methods invoked by `conan info`).

**Comment by jgsogo** [comment]
Hi! I think you found a corner-case that totally makes sense. I've create a PR with this scenario here https://github.com/conan-io/conan/compare/develop...jgsogo:issue/8366-compiler-pkgid?expand=1

Your question is more about a workaround (IMHO yours is probably better than the one I could figure out). As you said, the workflow using `conan install --build` is perfectly valid and useful in many scenarios, IMO we need to provide an answer to this failure.

Thanks for pointing it out.

**Comment by ytimenkov** [comment]
I also thought that "create from reference" command could be a better place for `--lockfile-node-id` option (which as I understand also depends on `--build <ref>` option).

**Comment by memsharded** [comment]
> Another option could be to allow None but then I would need to signal that I do need a compiler at build time (which is now handled by throwing ConanInvalidConfiguration in methods invoked by conan info).

I am considering this option like maybe the best approach, at least to become the default in Conan 2.0:
- Not necessary to define explicitly ``None`` as a possible value in the settings.yml
- But it is not necessary to specify them in profiles and command line, Conan will not raise if they don't have a value defined.
- Conan will only raise if someone is trying to get their values, like in the ``generate()`` or ``build()`` or ``package()`` methods, to get an actual value. It might also raise if accessed in ``requirements()`` for conditional requirements.
- They should still be removed from ``package_id()``, but only they should be managed at this place.
- It is simple, nothing to do, no need to remove from ``configure()`` or raise manually in ``validate()``
- It could still raise automatically if ``package_id()`` doesn't remove them from the package-id computation but they have ``None``=undefined values

The blocker now is that Conan is raising too early if these values are not defined, so if declared, they should get a value or be removed with ``configure()``. If we delay this error until after ``package_id()`` computation, at ``validate()`` stage, then everything might work.

**Comment by ytimenkov** [comment]
Sounds good!

I just assume that there will be a way to check settings in a non-throwing manner.

Another thought is that the could be a compatible packages. Say, I have a compiler of choice to build tools. Then compiler == None should be compatible for consumption.

I don't have any practical experience with compatible packages yet, but it feels that the benefit is that compatibility checked at the moment of downloading package and build policy can still be applied to force build. Therefore for the case of a tool there won't b be any need to look at `self.develop` at all

**Comment by memsharded** [comment]
> I just assume that there will be a way to check settings in a non-throwing manner.

There already is. You can always do ``settings.get_safe("compiler.version")``, will return None if compiler or version are not defined, but will not raise.

> Therefore for the case of a tool there won't b be any need to look at self.develop at all

Yes, I think that the above proposal will not need to check ``develop`` at all, it will do one thing or the other if the ``build()`` requires the settings to have a value, but will continue otherwise. At the moment, just the idea, we need to validate it, but seems it could work.

**Comment by memsharded** [comment]
Ok, so lets go for the above proposed approach (delay the ``settings.validate()``, so undefined settings are possible till the ``validate()`` method). This will be the approach in Conan 2.0, but not possible to do it now, as it will be breaking behavior.

I would suggest a possible very simple workaround to the underlying issue. Even if the packages do not need the compiler/built_type information to be installed, just define that information with any compiler in your profiles. It will not be used as it is discarded by the package_id, but it will certainly be simpler than changing the recipes ``configure()`` method conditioned on the ``self.develop`` variable.

**Comment by ytimenkov** [comment]
> just define that information with any compiler in your profiles

I think I didn't want any implicit actions. Having compiler in configuration will enable "profileless" conan install (whether it's good or bad). Also it will make possible to simply run `conan create .`... In other words quite many side effects I need to think about a bit.

**Comment by snailcatcher** [comment]
After a bit of playing around with my packages I have exactly the same problem described in the first post.
I thought that a sample will help others understand the issue better so I did one myself:
<details>
  <summary>My package conanfile.py</summary>

```py
from conans import ConanFile, CMake

class Pkg(ConanFile):
    name = "my_pack"
    version = "0.0.0"
    settings = "compiler", "build_type"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        ...

    def package_id(self):
        del self.info.settings.compiler
```
</details>
<details>
  <summary>My conanfile.txt for consuming the above package</summary>

```txt
[requires]
my_pack/0.0.1@user/channel
```
</details>
<details>
  <summary>My used profile</summary>

```txt
[settings]
os_build=Windows
os=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
```
</details>
<details>
  <summary>output of conan install</summary>

```sh
PS C:\...> conan install . -u --profile=buildserver
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: my_pack/0.0.0@user/channel: 'settings.compiler' value not defined
```
</details>

If there is any solution for this I will test this, please let me know.

**Comment by snailcatcher** [comment]
So now after playing around a bit, I have implemented a workaround which fits my personal needs:

I do some tweaks to the settings.yml file:
```sh
compiler:
  ...
  v2workaround:
    version: [None]
    libcxx: [None]
```
and use the following as my profile:
```sh
[settings]
os_build=Windows
os=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=v2workaround
```

With these changes everything works for me (even if this is not very good solution, it does the smallest damage to my current setup)

**Comment by ytimenkov** [comment]
If you adjust settings anyway, try adding 
```
compiler:
    ...
    None: ""
```
Or similar. Then you don't need workaround at all. `None` is what you get when nothing is specified.

**Comment by ytimenkov** [comment]
Oh, with new `build_policy = "never"` this makes even more sense! I.e. prevent any automated build of compiler but still (re)use conan to build it on CI (`export-pkg` forces completely different workflow which I'd like to avoid).

**Comment by memsharded** [comment]
this has been made possible in 2.0. The test in https://github.com/conan-io/conan/pull/13161 explicitly proves it.

Not defining settings is no longer an error, unless some build helper decides to raise because it really needs a value to build.

Closing this issue in https://github.com/conan-io/conan/pull/13161.
