### ISSUE TITLE
[question] missing binary error during install

### ISSUE THREAD

**Issue by sduraisamy** [conan-io/conan#8367]
Missing binary Error during the installation of conan package which doesn't have binaries in it.

I created a package(e.g say deploy-test ) which deploy the content from dependent packages. The recipe has only deploy() method. So the deploy-test package will not have any binaries in it.I have upload the deploy-test with "conan upload deploy-test"

When i try to install, its expecting the binary package. Did i miss something?

**Comment by ytimenkov** [comment]
I think you have to create a package, even if it's empty. Only python requirements can be consumed from the export folder.

If you don't want to upload binary package you may create one on the fly via build policy (i.e. add `--build missing` or `--build deploy-test`) when installing it. Also (didn't try it myself) you can set this policy in the recipe to avoid extra command-line parameters: https://docs.conan.io/en/latest/mastering/policies.html

**Comment by jgsogo** [comment]
Hi! Yes, you always have to `conan create` the package (or `conan install --build` if it is already in the cache).

It is true the message is always the same, for actual packages with binaries, package with header-only libraries or assets, Conan doesn't know what is inside the package and the message is always the same.

Let us know if it resolves your question so we can close this issue. Thanks!
