### ISSUE TITLE
[question] Does diamond graphs ``configure()`` methods that remove options shared/fpic could be broken?

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#8375]
It is possible if evaluated more than once, with different branches values.

**Comment by SSE4** [comment]
I spotted a serious issue in `validate` implementation: #8383

**Comment by memsharded** [comment]
This is not an issue at all in the ``validate()``, it is working as expected. It is an issue in the options processing: https://github.com/conan-io/conan/pull/8383#pullrequestreview-574079761

**Comment by memsharded** [comment]
The new graph resolution model in Conan 2.0 will try not to re-evaluate same recipe when diamonds, just check consistency. So that might solve this issue, which is otherwise simply too risky to solve for Conan 1.X

**Comment by memsharded** [comment]
Solved in 2.0, closing.
