### ISSUE TITLE
[feature] Add mirrors to conandata.yml

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#8376]
It would add much stability if it will be possible to specify a mirror in a  conandata.yml file.

Possible usecase:
https://github.com/bincrafters/community/issues/1347#issuecomment-764543932
Qt official download link is down for the last 2 days. If conan would have alternative download links, recipe will not be broken.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! We are already adding mirrors to some recipes using the [`tools.get()`](https://docs.conan.io/en/latest/reference/tools.html#tools-get) tool (it supports a list of URLs). You can check how we add it to this [msys2 recipe](https://github.com/conan-io/conan-center-index/pull/1060): basically it is a list of URLs, all of them with the same checksum.

**Comment by AndreyMlashkin** [comment]
Thanks!
