### ISSUE TITLE
[feature] Implement cached_property

### ISSUE THREAD

**Issue by mathbunnyru** [conan-io/conan#8386]
Right now, we have so many `cmake`s whice are cached in the manual way like this:

```
    _cmake = None
...
    def _configure_cmake(self):
        if self._cmake:
            return self._cmake
        self._cmake = CMake(self)
        # setting some args
        return self._cmake
```

This is also not the only thing, which is cached, for example:
https://github.com/conan-io/conan-center-index/pull/4319

What I would like to have instead:
```
from conans import tools
...
    @tools.cached_property
    def _configure_cmake(self):
        cmake = CMake(self)
        # setting some args
        return cmake
```

There are already existing implementations like this: https://pypi.org/project/cached-property/
But it might make sense to reimplement this in the most simple (non-threaded, without lru, only property) way.

I personally think that it makes the code much more clear, essentially makes the code to do the same thing, more pythonic and if someone didn't cache `cmake` yet, caching it with this decorator makes it only one line change (`tools` are normally included).

I would like to ask the community for the opinion on this idea.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, I have actually wanted to do this for Conan internals for a while, so it would make sense to make available something similar for recipes too.

**Comment by memsharded** [comment]
Closing as not planned, also it is no longer necessary for that ``CMake`` case, as it is not necessary that trick, see the new ``conan new cmake_lib`` templates in Conan2
