### ISSUE TITLE
[bug] Catalyst subsystem setting should be all lowercase

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#8387]
https://github.com/conan-io/conan/pull/8264/files

The new Macos subsystem `Catalyst` in settings should be all lowercase to be consistent with existing subsystems. 

https://github.com/SSE4/conan/blob/ff7de2e5b2551b0cc69970e8bb6edf43b6760ba0/conans/client/conf/__init__.py#L41
` subsystem: [None, "Catalyst"]`

https://github.com/SSE4/conan/blob/ff7de2e5b2551b0cc69970e8bb6edf43b6760ba0/conans/client/conf/__init__.py#L31
` subsystem: [None, cygwin, msys, msys2, wsl]`

**Comment by solvingj** [comment]
I also just noticed it's in quotes and the others are not.  Not sure if that is functionally different, or optional and works either way.

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/8389, will be released in next patch 1.33.1
