### ISSUE TITLE
conan test_package ignores options of the test_package/conanfile.py

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [conan-io/conan#839]
Hi there,

i want to build a recent conan package for the Qt 5.8 libs, which contains a lot of compilations flags for external dependencies. The way i want to go is to use as less as possible external dependencies by default. Each project itself should than specify its qt external dependencies by Qt:dependency=yes.

It seems great so far. But i get problems with the test_package. Calling "conan test_package" builds the Qt libs with the default configuration set and ignores my test_package Qt:option=yes flags. I assumed, that the test_package options are propagated, before the conan package is build. Isn't that a desired behavior?

best,
Christian

**Comment by cguentherTUChemnitz** [comment]
Sorry for the spamming. My described desired behavior is alraidy the current behavior. I had a type in my test_package/conanfile.py options for the Qt lib. So the config value where not matched to the lib.

**Comment by memsharded** [comment]
Not spamming at all :) Thanks Christian for your question, very glad that you already found the issue. Feel free to ask any other issue, here or in other channels. Best!
