### ISSUE TITLE
[bug] conan export performs newline conversion that interferes with recipe revision calculations

### ISSUE THREAD

**Issue by hannahwhy** [conan-io/conan#8391]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 and Ubuntu 20.04; there may be others
  * Compiler+version: N/A
  * Conan version: 1.33.0
  * Python version: 
  ** Windows 10: Python 3.9
  ** Ubuntu 20.04: Python 3.8.5

### Steps to reproduce (Include if Applicable)

You will need a Windows 10 and a UNIX-ish system to reproduce this problem.  I have tested this on Windows 10 and Ubuntu 20.04, but any other OS that defaults to UNIX newlines (e.g. macOS) should also work.

On the UNIX system:

1. Check out conan-center-index commit `0371c44fb15406b8254ed026a590dd4da2ae332d`, which is the tip of `master` as of the filing of this issue.  (I think any recipe with source files will be able to replicate this problem, but conan-center-index is a convenient shared reference point.)
2. `cd recipes/fmt/all`
3. `conan export . fmt/7.1.3@`.
4. Make a note of the recipe revision.  It should be reported as `03b313d29f69ab45fd35d5d98d63a4dd`.

On the Windows system:

1. Check out conan-center-index commit `0371c44fb15406b8254ed026a590dd4da2ae332d`.
2. `cd recipes/fmt/all`
3. `conan export . fmt/7.1.3@`.
4. Make a note of the recipe revision.  It should be reported as `5f54936b4416729a60b11b542afd4c44`.

### Logs (Executed commands with output) (Include/Attach if Applicable)

For both of these runs, I created an empty directory and set `CONAN_USER_HOME` to it.  On the Windows system, I additionally set `CONAN_USE_ALWAYS_SHORT_PATHS` to 0, as my Windows system normally has that set to 1.

UNIX system:

```
~/prj/conan-center-index/recipes/fmt/all$ conan export . fmt/7.1.3@
WARN: Remotes registry file missing, creating default one in /home/yipdw/tmp/ch/.conan/remotes.json
Exporting package recipe
fmt/7.1.3 exports: File 'conandata.yml' found. Exporting it...
fmt/7.1.3 exports: Copied 1 '.yml' file: conandata.yml
fmt/7.1.3 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
fmt/7.1.3 exports_sources: Copied 3 '.patch' files: fix-install-6.0.0.patch, fix-install-5.3.0.patch, fix-mingw-msvc2015-export-assert-fail-6.1.0.patch
fmt/7.1.3: A new conanfile.py version was exported
fmt/7.1.3: Folder: /home/yipdw/tmp/ch/.conan/data/fmt/7.1.3/_/_/export
fmt/7.1.3: Exported revision: 03b313d29f69ab45fd35d5d98d63a4dd
```

Windows system:

```
C:\Users\yipdw\prj\conan-center-index\recipes\fmt\all>conan export . fmt/7.1.3@
WARN: Remotes registry file missing, creating default one in C:\Users\yipdw\tmp\ch\.conan\remotes.json
Exporting package recipe
fmt/7.1.3 exports: File 'conandata.yml' found. Exporting it...
fmt/7.1.3 exports: Copied 1 '.yml' file: conandata.yml
fmt/7.1.3 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
fmt/7.1.3 exports_sources: Copied 3 '.patch' files: fix-install-5.3.0.patch, fix-install-6.0.0.patch, fix-mingw-msvc2015-export-assert-fail-6.1.0.patch
fmt/7.1.3: A new conanfile.py version was exported
fmt/7.1.3: Folder: C:\Users\yipdw\tmp\ch\.conan\data\fmt\7.1.3\_\_\export
fmt/7.1.3: Exported revision: 5f54936b4416729a60b11b542afd4c44
```

### Expected behavior

Given that the recipe contents are the same and the recipe revision is derived from a hash of the recipe's contents, I should get the same revision from both the Windows and UNIX `conan export`s.

### Hypothesized cause of the bug

If we compare the exported contents of the `patches` directory from the Windows and UNIX builds, we find the following:

```
$ ls -l unix/*.patch
-rw-rw-r-- 1 yipdw yipdw 528 Jan 24 20:31 unix/fix-install-5.3.0.patch
-rw-rw-r-- 1 yipdw yipdw 479 Jan 24 20:31 unix/fix-install-6.0.0.patch
-rw-rw-r-- 1 yipdw yipdw 843 Jan 24 20:31 unix/fix-mingw-msvc2015-export-assert-fail-6.1.0.patch

$ ls -l windows/*.patch
-rw-rw-r-- 1 yipdw yipdw 541 Oct 31 01:25 windows/fix-install-5.3.0.patch
-rw-rw-r-- 1 yipdw yipdw 492 Oct 31 01:25 windows/fix-install-6.0.0.patch
-rw-rw-r-- 1 yipdw yipdw 866 Oct 31 01:25 windows/fix-mingw-msvc2015-export-assert-fail-6.1.0.patch
```

The `.patch` files exported from Windows are _larger_.  This suggests that they have been modified in some way:

```
$ hexdump unix/fix-install-5.3.0.patch | grep '0a0d'; echo $?
1
$ hexdump windows/fix-install-5.3.0.patch | grep '0a0d'; echo $?
0000010 742e 7478 0a0d 2b2b 202b 2f62 4d43 6b61
0000020 4c65 7369 7374 742e 7478 0a0d 4040 2d20
0000050 0a0d 0d20 200a 2020 2023 6e49 7473 6c61
0000070 2064 6568 6461 7265 2e73 0a0d 2020 6920
0000110 5f42 4944 7d52 0a0d 202b 2020 2020 2020
0000170 5453 4c41 5f4c 4942 444e 5249 297d 0a0d
00001d0 4944 7d52 4f20 5450 4f49 414e 294c 0a0d
0
```

Further investigation with `vimdiff -b` indicates that newlines have, at some point in the export process, been expanded from UNIX-style 0x0A to Windows-style 0x0A 0x0D.

### Impact of this bug

We run `conan create`s from Windows, Linux, and macOS build agents in a CI environment; revisions are enabled across the board.  All build agents have the ability to upload packages and recipes to a central Artifactory server.

We are aiming for reproducible builds and therefore also use package revision mode for our package IDs.

However, the combination of these two policies plus the above behavior causes the Windows build agent to upload its packages under a _different recipe revision_ than the Linux and macOS build agents, even though the packages were derived from _the same recipe_.

If the Windows build agent uploads its recipe after the Linux and macOS agents upload theirs, then that recipe revision will be the most recent one, and the Windows packages will go under that revision.  The Linux and macOS packages will be under an _older_ recipe revision.

This seems to cause very confusing behavior when combined with e.g. `conan install -u`, where a Conan client may be unable to find a matching package ID, even though one exists in Artifactory.  (It just exists under a _different_ recipe revision that's not the latest one.)

Most packages are small enough that we can eat the cost of spurious binary regeneration.  However, this is not true for packages that contain toolchains (i.e. `android-ndk`), which are often very large.

**Comment by hannahwhy** [comment]
My understanding is that Conan 2.0 will support multiple recipe revisions in the client cache, which may mean that the impact of this behavior goes away.  This behavior is pretty confusing in the 1.x series, though.

Are there known problems with avoiding newline normalization?

**Comment by hannahwhy** [comment]
On further investigation, this might not be Conan's bug: I may have a misconfigured newline setting in my git client on Windows.  I'll investigate and update this report if I find something.

**Comment by hannahwhy** [comment]
Yeah, this definitely looks like a problem with newline conversion in one of my git configurations.  Closing this issue.

**Comment by memsharded** [comment]
Hi @yipdw 

Happy that you found the cause. This has been discussed a few times, and people sometimes confused about packages getting new revisions, and wanting Conan to normalize line endings. But we think this is a bad idea, it is way more complicated than it seems to decide which files need to be normalized and which not, so we strongly believe that this is something that is in the side of the version control system. Cheers!

**Comment by Artalus** [comment]
Just stumbled upon this myself. Do I understand it correctly, that the proposed solution is to use `git config --local core.autocrlf` with `false`/`input` parameter, and then re-checkout the working commit?

Regarding the issue itself: I would consider it an OK compromise if Conan would hash not the raw content of `conanfile.py`, but something like `'\0'.join(open('conanfile.py').readlines())`. Some additional magic like [`python-magic`](https://github.com/ahupp/python-magic) or [`filetype.py`](https://github.com/h2non/filetype.py) to detect text files would also be nice - as well as bold yellow `WARN: you are using git with core.autocrlf=true, which will affect the revisions of your recipe and package`.

**Comment by memsharded** [comment]
Hi @Artalus 

I also believed the same about warnings like: ``WARN: you are using git with core.autocrlf=true, which will affect the revisions of your recipe and package.``. In reality, my experience in support shows that these warnings are rarely effective. Nobody reads them, many times because it is a CI job, but even at the developer level. We could try to add that check, but the effectiveness is very low.

Indeed the proposed solution is having your repos that use the same line endings, always, in all the systems. That might be easier to do with a .gitattributes files inside the repo, than having to remember to do things in user checkouts. The approach to detect text files "some additional magic" is exactly what we want to avoid, as it is always problematic. Magic works fine for 95% of the cases, but that 5% of the cases can drown us in support tickets and maintenance. Let me put an example: 
- Lets say that we detect and normalize text files for Makefiles for hashing.
- Someone creates a package, with a given revision, but it realize it is broken because make will not process correctly some line-endings CRLF.
- User fix the Makefile, use LF only, and tries to create and upload the package. As it gets exactly the same revision, nothing changes and the package is not uploaded, now the user is blocked, and needs a new Conan feature to specify to not normalize the Makefiles hashing.

The other approach might seem less convenient, but it is more clear and robust in the long term: different files => different revision, user always keep 100% of control, they can always make it work exactly the way they want.

**Comment by sourcedelica** [comment]
Here is the incantation we ended up using on one of our projects' CI jobs:
```
git config core.autocrlf input 
git rm --cached -r . 
git reset --hard 
```
