### ISSUE TITLE
[feature] Allow package name length limit to be overriden via environment variable

### ISSUE THREAD

**Issue by Grumpy7** [conan-io/conan#8392]
I've seen this question pop up from time to time among the issues and we're also occasionally running into this problem. I realize that officially relaxing any package name limit might have implications regarding support etc. However, this is similar to the short_paths feature which already can be overriden via environment variables. 
Could it be possible to allow manually overriding the 50 char limit via an environment variable? Doesn't even have to be granular with respect to name/version/user/channel, just a single value for all of them.

**Comment by memsharded** [comment]
Hi @Grumpy7 

The main difference is that the short_paths is a client side only feature, so it was easier to do that. We know that the 50 chars limit of the reference fields (name, version, user, channel) can be in used in the server side DB, as these are typically the main entry  point of DBs for queries, searches, etc., and could be optimized for speed and size. Given that many vendors implement Conan servers, it is a bit too risky, the moment you provide the configuration in a feature and document it, people will inevitably use it, and complain about server side failures. We will most likely change this limit, but that will need to wait until Conan 2.0. Please try to reduce your package references shorter than that in the meantime.

**Comment by memsharded** [comment]
Package names will be allowed to be slightly longer (up to 100 chars), but in any case it is not recommended to have long package names. 

They will also have to be all lowercase.

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/12754 will be in upcoming beta7
