### ISSUE TITLE
[feature] Consider adding a "conan venv" command

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#8393]
Proposal by @SSE4 in https://github.com/conan-io/conan/pull/8306

> I would like to learn a bit better the use case for this PR:
> 
> * What would be some real life use cases for this command
> * User requests that would be satisfied with this feature
> * Why not using virtualenv generators

the use case is the same as `VirtuanEnv` itself, basically. actually, it's more likely a syntax sugar on top of `VirtualEnv`.
right now, to get cmake and execute command with it I need 4 conan commands:
```
conan install cmake/3.19@ -g virtualenv
./activate.sh (or ps1, or bat)
cmake --version
./deactivate.sh (or ps1, or bat)
```
with new feature, it would be just:
```
conan venv cmake/3.19@ -- cmake --version
```
it's easier to remember just one command than 4 commands, right?
also, it is shell-agnostic, so you don't need to always check which script to execute.
further, I can use this command as an alias, or environment variable, like:
```
alias cmake=conan venv cmake/3.19@ --
```
```
export CONAN_CMAKE_PROGRAM=conan venv cmake/3.19@ --
```
so the similar one-liner could be easily used everywhere I need to pass for instance CC/CXX.

**Comment by solvingj** [comment]
I just added the original use-case explanation to this issue for future discussion.

**Comment by memsharded** [comment]
I think this is not worth its own command, and it opens many new UI questions, like if ``venv`` would require all ``install`` arguments (profiles, --build, --update, etc?). And what if the user wants to activate 2 different tools, like cmake and ninja? Should the command display what packages are being downloaded, and show the download progress? (I think so, because it takes a while to be downloaded, it would be super weird to be waiting without any indicator). But on the other hand it will pollute the output, making an ``alias`` and then running ``cmake`` and seeing output of Conan messages is weird.

At the end of the day, ``conan venv cmake/3.15 -- cmake --version`` is not that different from ``conan install cmake/3.15 -g VirtualBuildEnv && activate.bat && cmake --version``

As users have custom commands in 2.0 and it is very easy to build this functionality with those, I am closing this as won't implement, and users wanting this feature will need to create their own custom commands.

**Comment by SSE4** [comment]
there are some important differences:
- `conan install cmake/3.15 -g VirtualBuildEnv && activate.bat && cmake --version` is 3 commands, harder to type, harder to remember
- it's not the same command for all OS

but if there is an easy way to add my own CLI, that's great
