### ISSUE TITLE
[bug] conan_build_info does not raise in event of an error

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8395]
Failure to publish buildinfo in one of our CI jobs went undetected because an error occurred but was not raised.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 64-bit
  * Compiler+version: n/a
  * Conan version: 1.33.0
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
Try to publish erroneous buildinfo to artifactory.  In my case the 'properties' section contained an Ã character from the gerrit-injected env var for commit message (which I wasn't aware is not supported).

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
conan_build_info --v2 publish buildinfo.json --url=<artifactory url> --user=**** --password=**** 
[1m[31mERROR: 'latin-1' codec can't encode character '\u201a' in position 3538: ordinal not in range(256)[0m
```

**Comment by czoido** [comment]
Hi @GordonJess,
Thanks a lot for reporting, you are right the exit code of `conan_build_info` was not correctly applied.
Will be fixed as soon as possible.

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/8408, will be in next 1.34
