### ISSUE TITLE
[question] Why does "conan search boost --remote=conan-center" fail frequently?

### ISSUE THREAD

**Issue by dragondive** [conan-io/conan#8398]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I tried `conan search boost --remote=conan-center` and it failed with a timeout:

    /tmp$ conan search boost --remote=conan-center
    ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search?q=boost (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))

    Unable to connect to conan-center=https://conan.bintray.com
    1. Make sure the remote is reachable or,
    2. Disable it by using conan remote disable,
    Then try again.

After verifying that it was not an issue with my network connection, etc. I thought to try with other libraries (poco, gtest, cmake, ...) and those worked properly. Then I included `boost/1.75.0` in my package recipe anyway and with `conan install`, I could download the boost package. 

On the Slack channel, I saw a few messages related to this issue, but there was no clear solution. What is this issue specifically with the boost library that causes these timeouts? Is there some configuration change or "workaround" to resolve this?

**Comment by memsharded** [comment]
Hi @dragondive 

Thanks for reporting. This is an infrastructure issue we are experiencing with ConanCenter. We are aware of it, it is quite challenging to fix it quickly, but it is in the roadmap. Please use https://conan.io/center to do searches in the meantime

**Comment by dragondive** [comment]
@memsharded Thanks for the confirmation. I was wondering if there was something wrong with my setup, good to know it isn't. This isn't especially urgent (at least for me), so the suggested alternative works for me.

**Comment by memsharded** [comment]
This has been finally fixed. ``conan search zlib* -r=conancenter`` now works fast against ConanCenter

Artifactory 7.41 contains the fixes, so if you are experiencing this in your own instance, please upgrade.
