### ISSUE TITLE
Consider renaming [conf] section to [cfg], or renaming the conan.cfg file.

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#8400]
To be consistent in all places.

Suggested by @grafikrobot, thanks!

**Comment by czoido** [comment]
Closed via: https://github.com/conan-io/conan/pull/8422

**Comment by solvingj** [comment]
To clarify, the resolution in the PR was to change the filename from `config.cfg` to `global.conf` rather than rename `[conf]` section.
