### ISSUE TITLE
[feature] add GCC 11 to settings.yml

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#8404]
Fedora 34 uses GCC 11

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
I think it is not a stable release yet: https://gcc.gnu.org/releases.html

**Comment by SSE4** [comment]
same as #8885
