### ISSUE TITLE
python_requires not available in Grapher object for graph output

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#8405]
Hi,

I like to possibility to visualize all dependencies of my Conan package in a graph and output it either as Dot or HTML file.
However, I would like to see the full dependency graph including `python_requires` dependencies. Unfortunately, as far as I could see, there is no chance to get this information and output it e.g. by using user specific templates.
Could you please enhance the creation of the Grapher object to provide this information too? I don't think it is necessary to modify the default templates for Dot and HTML. However, with this solution, I would be able to visualize the `python_requires` dependencies within my user specific HTML template.

Keep up your excellent work and many thanks for watching this request.

Best regards,
Markus

**Comment by jgsogo** [comment]
Hi, Markus

We are committed to Conan v2 development right now. Conan v2 will have a new implementation of the graph and the visualization will include all the nodes (we expect to provide a much better view). I can tag this issue, but not sure if we can assign resources to it. Anyway, if you feel like contributing it with a pull-request it will be more than welcome.

Thanks!

**Comment by Wonders11** [comment]
I'm beginner to open source. Can anyone please guide me and assign this task to me?

**Comment by memsharded** [comment]
Hi @Wonders11 

Thanks for wanting to contribute. Beginner in open-source or also beginner in coding?

**Comment by Wonders11** [comment]
I'm beginner to open source and I'm intermediate in coding. Thanks for assigning this task. I'll try my best to solve this.

**Comment by Wonders11** [comment]
Can anyone please guide me how to get started? 
Thanks in Advance :)

**Comment by memsharded** [comment]
- Grep for ``format_graph_html`` function, from there:
- The template is ``INFO_GRAPH_HTML``
- In the same file you have practically all logic that feeds the HTML template
- We are using jinja2 library for rendering template, if you don't know it, you'd need to learn the basics

Regarding process, using ``pip install -e .`` to install Conan over the "git clone" of the repo, so it allows to run the code you are writing is very convenient, though soon writing unit tests helps develop faster. You can grep for "--graph=" tests too and add tests there.

Thanks to you!

**Comment by Wonders11** [comment]
Will follow the process.
Thank you!

**Comment by Wonders11** [comment]
Can someone please give me detailed explanation in order to complete this task. I'm unable to get it. Help would be really appreciated. Thank you in advance.

**Comment by memsharded** [comment]
Hi @Wonders11 

I think this has been solved already in ``develop2`` branch, targeted for Conan 2.0.

At the moment all new development, new features, minor ux bugs, etc, should be targeted to 2.0, not to 1.X anymore, which now is under maintenance and migration mode only. Please check develop2, and let us know.

I am closing this as implemented in 2.0, if something fails, please open a new ticket for 2.0. Thanks!
