### ISSUE TITLE
[question] Is there portable conan app?

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#8407]
Is there a portable conan app (that does not require installation)?

**Comment by memsharded** [comment]
We don't distribute one, but running **pyinstaller.py**  in the repo: https://github.com/conan-io/conan/blob/develop/pyinstaller.py, will give you a self contained executable that you could drop in a compatible machine. Please try that and let us know.

**Comment by DmitrySokolov** [comment]
```
conan> py -3 .\pyinstaller.py
pyinstaller does not yet support python 3.8, see: https://github.com/pyinstaller/pyinstaller/issues/4311
```
While https://github.com/pyinstaller/pyinstaller/issues/4311 was fixed in October 2020.

Commened out
```
if __name__ == "__main__":
    #if sys.version_info.major == 3 and sys.version_info.minor >= 8:
    #    print("pyinstaller does not yet support python 3.8, "
    #          "see: https://github.com/pyinstaller/pyinstaller/issues/4311", file=sys.stderr)
    #    exit(1)
    src_folder = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))
    output_folder = pyinstall(src_folder)
    print("\n**************Conan binaries created!******************\n"
          "\nAppend this folder to your system PATH: '%s'\n"
          "Feel free to move the whole folder to another location." % output_folder)
```
It looks like it works
```
**************Conan binaries created!******************

Append this folder to your system PATH: 'C:\Dev\Projects\conan\pyinstaller\dist\conan'
Feel free to move the whole folder to another location.
```

But I wonder, are these modules needed for conan?
```
matplotlib
numpy
PIL
tcl
tcl8
tk
tornado
zope
```

**Comment by DmitrySokolov** [comment]
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-remove-tkinter-tcl

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/8438 removes the 3.8 limit

Regarding the things that are included in the pyinstaller bundle, we do little there, it is mostly the default it is doing, and seems to be working good so far, so we prefer better not to mess with it. The executable is compact enough already, doesn't seem a bottleneck.
