### ISSUE TITLE
[question] conan info --graph builds incomplete graph

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8409]
Is there a way to add transitive dependencies to the graph, i.e. all dependencies of dependencies of dependencies and so on to be rendered in the graph?

https://docs.conan.io/en/1.13/reference/commands/consumer/info.html says that `conan info` creates a complete graph but I don't think "complete" is a right word. I guess "shallow" fits better

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by PengolodhGoedath** [comment]
`conan info --graph` does generate graphs with transitive dependencies (though with a few caveats: `python_requires` aren't included at all, and `build_requires` only for the root package). Sometimes, if the dependencies are used by multiple levels, the html hierarchical ordering gets confused, but you can simply disable that checkbox and drag them into a more organized fashion.

For an example, try `conan info libzippp/4.0@ --graph libzippp.html`, that should show you more than just one level of dependencies.

**Comment by memsharded** [comment]
A note, passing ``--build=missing`` or ``--build`` argument to the ``conan info`` might pull more build_requires into the graph too, besides the root package ones.

**Comment by xahon** [comment]
Try to build a graph for that package

conanfile.txt
```
[requires]
qt/5.12.4@bincrafters/stable
bzip2/1.0.8@conan/stable
```

In my case the graph doesn't show some packages (m4_installer for me)
However i see that line when i call `conan info ...`
```m4_installer/1.4.18@bincrafters/stable: Forced build from source```

Github doesn't allow to attach html files, sorry

**Comment by memsharded** [comment]
Yes, sorry, I did a mistake, the actual argument you need to pass to info is "dry_build". It is the equivalent to --build but it just compute it, doesn't really build. 

```bash
$ conan info poco/1.9.4@ --graph=file.html -db
```

Then open the file.html, you will see build requires of transitive dependencies as ovals. This UX will be improved in Conan 2.0.

**Comment by xahon** [comment]
@memsharded thanks, that is what i looked for :)
