### ISSUE TITLE
[question] In lockfile ci examples, why do we export to capture full recipe revision for libb base but not app1 base?

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#8410]
We are following through the https://docs.conan.io/en/1.33/versioning/lockfiles/ci.html#products-pipeline documentation and the associated lockfiles ci example:

https://github.com/conan-io/examples/blob/14186e8798b540cf0cdafe218b4457fdbdbc3d4a/features/lockfiles/ci/build.py#L73-L100

I understand from the very helpful explanation in https://github.com/conan-io/conan/issues/8205#issuecomment-759659191 what the purpose of the `conan export .` is for the `libb_deps_base.lock`, to capture the full reference to libb/0.2@user/testing, including the recipe revision.

Now I am curious why in the lockfiles example:

```
    # Capture the app1 base lockfile
    run("conan lock create --reference=app1/0.1@user/testing --lockfile=locks/libb_base.lock "
        "--lockfile-out=locks/app1_base.lock --base")
    # And one lockfile per configuration
    run("conan lock create --reference=app1/0.1@user/testing --lockfile=locks/app1_base.lock "
        "--lockfile-out=locks/app1_release.lock")
    run("conan lock create --reference=app1/0.1@user/testing --lockfile=locks/app1_base.lock "
        "--lockfile-out=locks/app1_debug.lock -s build_type=Debug")
```

( https://github.com/conan-io/examples/blob/14186e8798b540cf0cdafe218b4457fdbdbc3d4a/features/lockfiles/ci/build.py#L93 )

the same `conan export .` wasn't performed between `app1_base.lock` and per-profile `locks/app1_release.lock` lock.

Does the same reason for using `conan export .` to capture the full reference and recipe revision not apply here to `app1`?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
