### ISSUE TITLE
[question] How to ensure build_requirement sub-graph is Release

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#8415]
Hello,

I want to be able to ensure that my `build_requirements` (e.g. `cmake`) are built in release mode so that the build time does not suffer. These requirements are rarely used as library dependencies so my first preference would be to be able to tell Conan that I want all build requirement sub-graphs to be built in release mode. This ensures I do not have to manually manage a list of package names that are generally used as `build_requirements`, and that they can be used both as `requirement` and `build_requirement` if needed.

If that is not possible I would like to know if it is possible to manually do this so that whenever a consumer has for example `cmake` as a build requirement, the CMake binary (and all its dependencies) are built in release mode. This is very important since a debug build of the build tool can significantly increase build time.

I have tried adding these lines to my profile:
```
automake:build_type=Release
b2:build_type=Release
cmake:build_type=Release
make:build_type=Release
meson:build_type=Release
msys2:build_type=Release
ninja:build_type=Release
pkgconf:build_type=Release
```
However, this is still not ideal since this only forces the `build_requirement` itself to be `Release`, and not its dependencies. Therefore if I build the consumer project once in `Release` and once in `Debug`, I will end up with two packages for `cmake`. One with a debug build of `openssl` and one with a release build of `openssl`.

- [✓] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @daravi 

Have you tried the new build-context model? Specifying a different ``--profile:build=xxxx`` with a profile that contains "Release", your build-requires in build context will be Release, independently of what build type the host context has. This model will be the one used in Conan 2.0.

**Comment by solvingj** [comment]
@memsharded advice seems like the appropriate approach.

**Comment by daravi** [comment]
@memsharded Thank you that is exactly what I need. Though I realize after using build/host profile that there might be a bug there when generating CMake variables. I have created #8425 for that.

**Comment by daravi** [comment]
@memsharded @solvingj I have setup build and host contexts. Like so:
```
cmake_utils: requires cmake
project: build_requires cmake_utils
host profile: debug
build profile: release
```
I see that CMake is built in Release mode. However CMake's dependency, `openssl`, is built in Debug mode. Is this a bug? From the host/build contexts page my understanding is that the entire sub-graph should have used the build profile and be built in Release mode. I am using `semver_direct_mode` if that matters.

**Comment by ericLemanissier** [comment]
great trick suggested by @solvingj `-s:b *:build_type=Release` !

**Comment by AbrilRBS** [comment]
Closing as solved, thanks everyone for chiming in :)
