### ISSUE TITLE
[bug] artifacts.properties doesn't apply to internal Artifactory files

### ISSUE THREAD

**Issue by klimkin** [conan-io/conan#8418]
`artifacts.properties` doesn't apply to internal Artifactory files. This causes issues for Artifactory tools like cleanup scripts that scan properties for retention indication.

### Environment Details (include every applicable attribute)
  * Operating System+version: any
  * Compiler+version: any
  * Conan version: 1.32.0
  * Python version: 3.7.3

### Steps to reproduce:
1. Create [artifacts.properties](https://docs.conan.io/en/latest/reference/config_files/artifacts.properties.html) and add a property
2. Upload to Artifactory
3. Check `.timestamp` and `index.json` files don't have the property set

### Logs

Conan trace log shows property `retention.days` is part of PUT header:

~~~json
{
  "_action": "REST_API_CALL",
  "duration": 0.004857063293457031,
  "headers": {
    "User-Agent": "Conan/1.32.0 (Python 3.7.3) python-requests/2.25.0",
    "X-Checksum-Deploy": "true",
    "X-Checksum-Sha1": "fc4eb11924fc59e9acdc8dccb94c98d6b0356ee6",
    "artifact_property_retention.days": "3653",
    "retention.days": "3653"
  },
  "method": "PUT",
  "time": 1612151299.8733957,
  "url": "https://something.com/artifactory/api/conan/conan-repo/v1/files/_/libbacktrace/1.0/_/0/package/6af9cc7cb931c5ad942174fd7838eb655717c709/0/conan_package.tgz"
}
~~~

On artifactory, property is set for uploaded files:
![image](https://user-images.githubusercontent.com/409053/106413092-16c84a00-63fe-11eb-8d54-690852ffb8e5.png)

But not for internal files:
![image](https://user-images.githubusercontent.com/409053/106413033-ed0f2300-63fd-11eb-89c5-3fa462b044f0.png)

**Comment by solvingj** [comment]
I believe this is because `index.json` and `.timestamp` are not uploaded, but instead generated server side. The only way to get set a retention policy on these files is with `curl` or `jfrog-cli` after they are known to be created.

**Comment by solvingj** [comment]
@memsharded do you think my assessment is correct?  If so, then the only other course of action possible would be to suggest it as an artifactory feature request.

**Comment by memsharded** [comment]
Yes, correct. Those files are internal implementation details of the server side. They are not downloaded as part of the packages, nor uploaded. They are not known by Conan client at all, it is impossible that it will set properties.

For cleanup policies, maybe another approach is necessary, it depends if those scripts use the JFrog-CLI or they can also use Conan or is pure API based. This (cleanup policies) is something we want to start implementing as a Conan command layer as soon as Conan 2.0 is in beta stage, but that will take some time.

**Comment by klimkin** [comment]
From perspective of Conan API integrity, the question here is: should the properties apply to all relevant Conan repository files? If yes, then this would be Artifactory request (how do you do that?)

**Comment by memsharded** [comment]
Probably not. They are still "metadata", not repository files, and they do not belong to the Conan API. The Conan API only define things at the package level, like  ``conan remove <ref> -r=remote-repo``, and the server side should handle that accordingly.

The fact that they look like files on the server side is an implementation detail. Lets say that you try to use those properties to copy those files to another repository. You cannot copy those files to another repository, they will be generated automatically in the other repository when moving the Conan packages, but probably forcing a copy could be undefined behavior. Those files should most likely not be copied, removed, modified, or uploaded manually to Artifactory.

Maybe Artifactory team could clarify. For Artifactory support and requests, it depends:
- If you are a JFrog customer, then the best is going through official JFrog support
- There is a Jira here: https://www.jfrog.com/jira, but the traffic is massive, maybe it won't get much attention, but maybe worth trying.

Are those scripts client side with JFrog-CLI? Or using the Artifactory API? Or are they Artifactory user plugins server side?

**Comment by solvingj** [comment]
@klimkin are you still working on or around this issue? If so, are you able to answer any of the questions from @memsharded ?

**Comment by memsharded** [comment]
This issue is outdated, closing it.

artifacts.properties file has been removed in Conan 2.0 completely.
The alternative to set properties in Artifactory is an explicit command like the one that can be found in the extensions repo: https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/art
