### ISSUE TITLE
[bug] `conan install` with warm download caches accesses remote repositories

### ISSUE THREAD

**Issue by lukasoyen** [conan-io/conan#8419]
### Environment Details (include every applicable attribute)
  * Ubuntu 20.10
  * Conan version: 1.130.0
  * Python version: 3.7.0

### Steps to reproduce (Include if Applicable)

* set `general.revisions_enabled=1`
* configure a `storage.path` and a `storage.download_cache`
* run `conan install` using a lockfile ensuring correct hashes for everything are available
* delete the directory `storage.path` points to, keep the directory `storage.download_cache` points to
* go offline
* run `conan install` using the same lockfile. This fails

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
XXX/8.0.153@XXX/stable: Not found in local cache, looking in remotes...
XXX/8.0.153@XXX/stable: Trying with 'XXX'...
ERROR: Failed requirement 'XXX/8.0.153@XXX/stable' from 'conanfile.py'
ERROR: HTTPSConnectionPool(host='XXX.XXX.XXX.com', port=443): Max retries exceeded with url: /artifactory/api/conan/conan/v1/ping (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f4cdb38b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Unable to connect to XXX=https://XXX.XXX.XXX.com/artifactory/api/conan/conan
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

I am unsure if this is actually a supported use case and thus a bug. At our company we try to maintain a build that works offline/without VPN connection. This works great when keeping the conan cache arround. But we delete that conan cache during a `make clean` and only maintain the download cache. The download cache seems to contain several manifest/conanfile.py files, so a remote repository lookup might not be necessary?

Somewhat related: https://github.com/conan-io/conan/issues/5575 / https://github.com/conan-io/conan/issues/2924 / https://github.com/conan-io/conan/issues/2197

**Comment by solvingj** [comment]
Thank you for finding the related issues.  @jgsogo is this a supported case?

**Comment by jgsogo** [comment]
The download cache works when Conan is going to download a file, but the remotes can still be used. There are some API calls that return information (not files) and these API calls are not being cached.

**Comment by solvingj** [comment]
Is the use case of "work offline without VPN connection" a use-case we intended to support with the `download cache` feature?  

If so, should we file as something we should try to address?

If not, should we close this as an unsupported use-case of `download cache`?

**Comment by memsharded** [comment]
No, this is not a use case.

The download cache is a "performance" or "optimization" mechanism, trying to reduce big downloads from the server, but doesn't try to implement the full server protocol and serve as a complete, offline repository. That is more or less what the regular cache implements, if things are in the Conan cache, then the server will not be hit. So this is already addressed as today, that is the purpose of the cache. What it is possible is that we will consider to implement a multi-layer cache that could improve its current usage, but I don't think this should be a separate mechanism.

I am closing this now, but please let us know if you have any further question or need some clarification, thanks!
