### ISSUE TITLE
Shorthand `conan i package` for `conan install package`

### ISSUE THREAD

**Issue by alaingalvan** [conan-io/conan#842]
NPM has a shorthand for installing packages:

```bash
npm i package
```
I think conan would benefit from something similar:

```bash
conan i boost/1.60.0@lasote/stable
```

Any thoughts?

**Comment by memsharded** [comment]
Hi Alain,

Thanks for your feedback, but I have to disagree, sorry :)

I quite like the python zen:
- Explicit is better than implicit
- There should be only one way to do one thing

Please consider, for example that there is another conan command, called ``conan import``. Then the ``i`` is ambiguous. Would you use then ``in`` and ``im`` shortcuts instead? A bit weird IMO. 

I thing we are pretty fast typing, and saving a very few key strokes, that are executed just from time to time, is not worth. I am closing it by now, but maybe, once conan reaches 1.0, we could reconsider again if this feature has enough user support.

Cheers!

**Comment by sixten-hilborn** [comment]
Something I'd like more than a shorthand for "conan install" is autocomplete for conan commands, however I don't see it as a high priority issue.
