### ISSUE TITLE
[question] conditional deploy

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#8423]
Hello,

I want to perform a conditional deploy based on an options value.

This is a sample recipe
```
class demo(ConanFile):
    name = 'demo'
    version = '1.0'
    options = {
        'full_deploy': [True, False]
    }
    default_options = {
        "full_deploy": True
    }
    def build(delf):
        # build logic

    def package(delf):
        # package logic

    def deploy(delf):
        if self.options.full_deploy:
            # perform a full deploy
        else:
            # perform a lite deploy

    def package_id(self):
        del self.info.options.full_deploy
```

The conan package itself is independent from the option `full_deploy`,  that is why in the package_id  I delete that option `del self.info.options.full_deploy`

My issue is that I cannot perform a lite deploy by running the command:
`conan install demo/1.0@ -o full_deploy=False`  because conan cannot find any package with the option full_deploy=False

Any suggestions on how to deal with this ?

**Comment by solvingj** [comment]
As you know, Conan options affect the `package_id` by default, so it's not a great choice for what you're achieving. You have to delete the option from `full_deploy` which seems unnecessary. Also, you have the issue you are encountering, which could be worked around as well, but consider an alternative.

In this case, it would be better to use an environment variable: 

    conan install demo/1.0@ -e full_deploy=True

And then in the recipe:

    def deploy(delf):
        if os.getenv("full_deploy", "False"):
            # perform a full deploy
        else:
            # perform a lite deploy

Also, if you have many private packages with this strategy, you can fully qualify the value for each package: 

    conan install demo/1.0@ -e demo:full_deploy=True -e some_other_pkg:full_deploy=True

Let me know if this seems to be a better fit for your use case.

**Comment by boussaffawalid** [comment]
@solvingj I tried ur proposed solution and I got the exact same error.
Passing `-e full_deploy=True` changes the package id and I ended up with an error 
```
ERROR: Missing prebuilt package for ...
```

**Comment by solvingj** [comment]
Environment variables do not affect `package_id`. There is some other reason you're not finding the prebuilt package you're expecting to have.

**Comment by solvingj** [comment]
hi @boussaffawalid , were you able to get past this issue?  If not, is there any new information?

**Comment by boussaffawalid** [comment]
yes, It works. Issue can be closed.

We had one conditional requirement based on the value of `full_deploy`,  so setting full_deploy changed the requirements which changed the package_id.
