### ISSUE TITLE
[bug] Using build/host profiles, Conan does not generate (some?) CMake variables

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#8425]
### Environment Details (include every applicable attribute)
  * Operating System+version: CentOS 8
  * Compiler+version: LLVM 10.1
  * Conan version: 1.33.0
  * Python version: 3.8.6

### Steps to reproduce (Include if Applicable)

I have created this example repo:
https://github.com/daravi/test-conan-profile

When using build/host profiles (at least some) CMake variables seem to not be generated. Specifically in the above example I try to display `conan_<package_name>_root` variable of a `build_requirement`. In the successful test, I just run `conan install` and then `cmake` and see the variable correctly printed out. In the fail case I run `conan install` with build and/or host profiles specified and run `cmake` again and see that the `cmake` variable has not been defined.

### Logs (Executed commands with output) (Include/Attach if Applicable)

See:
https://github.com/daravi/test-conan-profile

**Comment by daravi** [comment]
Any timelines for this? I am wondering if I should invest time doing a some hacks to prevent people from building their build requirements in debug (which means I probably have to maintain my own version of those recipes) or if I should wait for this fix.

**Comment by daravi** [comment]
@solvingj Any timelines for this? I am wondering if I should invest time doing some hacks to prevent people from building their build requirements in debug (which means I probably have to maintain my own version of those recipes) or if I should wait for this fix.

**Comment by solvingj** [comment]
Sorry for the delay. I lost track of this issue and am not sure how. 

Anyway, there are a few bugs in the reproduction repository, but I appreciate you creating it.  I was able to understand what you were trying to show and make it work.  I was able to reproduce the issue you described.  I was also able to look into the Conan source code a bit.  It was pretty simple to find the generator code which iterates over the dependencies and produces the variables here: 

https://github.com/conan-io/conan/blob/develop/conans/client/generators/cmake.py#L81

But it was not immediately obvious to me where the code is different between the cases of using a `build_profile` versus not using one. 

I'd like to keep digging to understand how it works for future reference, but, to get you moving forward as quickly as possible, let me summarize the most pressing question:

"Is this a bug?"
"Is this unexpected behavior?"

Beyond not knowing the implementation details, I don't have an intuitive understanding of the deep implications of cross-building yet.  Does it make sense to have the `build_requirement` variables show up in the scope of a "host profile"?  I don't know, probably not actually.  I remember seeing someone in chat explain something along the lines of: 

>  the PATH variables on the build machine (like `CONAN_XYZ_ROOT` paths for example) should never in-theory be expected to exist in the same exact path on the runtime machine. 

That made sense to me, and this case seems related, but I'm not it's the same.  One needs to actually work with that kind of thing for a while before understanding how it should work versus how it does work, and I haven't had the opportunity. This is my first opportunity to learn about these cross-building nuances. It was helpful for me to reproduce it, and maybe i'll go further with it.

Anyway, to get you moving forward again, maybe @jgsogo or @SSE4 can shed light on what is the "generally expected behavior for cross-compiling" in this situation, and then more specifically, is the current `CMake` generator doing it correctly, or is this an actual bug.

**Comment by daravi** [comment]
@solvingj I don't think that quote is relevant here since the generated CMake is still intended to be run in the build environment. (unlike virtualenvrun for example) Or am I misunderstanding your point?

**Comment by solvingj** [comment]
Yes it's possible my last point is irrelevant to your use case here. That's part of why we still need someone familiar with cross-building here.

**Comment by jgsogo** [comment]
Hi, @daravi 

When you are using two-profiles, the graph is divided into _host_ packages (regular `requires` and `build_requires(..., force_host_context=True)` and _build_ packages (`build_requires`). Here you can find more information: https://docs.conan.io/en/latest/devtools/build_requires.html?highlight=host%20build%20context#build-and-host-contexts

 * Build requirements in the _host_ context will propagate like any other requirement:

    * `cpp_info`: all information will be available in the `deps_cpp_info["xxx"]` object.
    * `env_info`: won’t be propagated.
    * `user_info`: will be available using the `deps_user_info["xxx"]` object.

 * Build requirements in the _build_ context will propagate all the `env_info` and Conan will also populate the environment variables `DYLD_LIBRARY_PATH`, `LD_LIBRARY_PATH` and `PATH` with the corresponding information from the `cpp_info` object. All this information will be available in the `deps_env_info` object.

   Custom information (from build-requirements in the _build_ context) declared in the `user_info` attribute will be available in the `user_info_build["xxx"]` object in the consumer conanfile.


All the logic for this propagation is encoded in the graph, generators _only print_ the information they have available, there is no logic about build/host profiles in the generators, everything is resolved before.

Note.- two-profiles is not a cross-building feature, you can (and should) use two-profiles for native development too. Even if the two-profiles are identical, Conan will split the graph into _host_ and _build_ context and will propagate the right information to consumers.

**Comment by daravi** [comment]
@jgsogo Thank you for the explanation. I am also not using the profiles for cross-building. I am trying to have my `build_requirements` be built in Release mode regardless of the build type of my host profile. From your explanation I understand that `conan_<package_name>_root` is not populated for `build_requirements` because `cpp_info` of `build_requirements` is not meant to be available in the build context (and the CMake generator is in the build context).

My build requirement is a collection of CMake scripts. I use `conan_<package_name>_root` to find where these files are to include them. Do you suggest I use the `PATH` from `env_info` instead? (though I would have preferred not to do this because then I have to use the `virtualenv` generator)

**Comment by jgsogo** [comment]
All the generators operate on all the information that they have available (propagation logic is controlled by the graph). Some generators will use only information from the _host_ context and some others use information from the _build_ context too.

Generators like `cmake`, `cmake_find_package`,... that are used to generate files with information from the dependencies you are going to use to link with your project/library, will generate only those files for packages in the _host_ context. For example, say you are using `protobuf` library and you want to use `protoc` (provided by package `protobuf`) compile in `Release` while you want to build your project in Debug. Here you need:

```python
class YourRecipe(ConanFile):

    def requirements(self):
        self.requires('protobuf/3.6.1')

    def build_requirements(self):
        self.build_requires('protobuf/3.6.1')
```

Given two profiles with Release in the _build_ profile and Debug in the _host_ profile, Conan needs to retrieve the same package twice, one for each configuration, and you will use in you `CMakeLists.txt` to find includes/libraries you want to link your project with:

```cmake
find_package(protobuf)
```

You expect CMake to find the Debug package, which is the one that offers the configuration you are building. This is just an example, but you can realize that we cannot propagate the information from _build_ AND _host_, we can only generate only `FindProtobuf.cmake` file and it will match the configuration from the _host_ profile, which is the one you are linking with.

--- 

That was an example, I hope it explains a bit the problematic we are trying to fix here. Now let's think about you scenario, you have a build-requires that provides some `xxx.cmake` files you want to use in your project. These CMake files can be a toolchain (and the package might be `android_ndk`) or just plain CMake files with utilities, functions and/or macros you need.

**Disclaimer -** We don't have a canonical answer for it, we are designing a new `conf` paradigm to pass information to the new toolchain classes and generators. It will take into account this issue and should provide the solution that will be aligned with Conan 2.0.

Depending on the nature of your package you can use different approaches (I will use `cmake-utils` as the name of your package with CMake scripts):
 * abuse generators built-in functionality. You can declare `self.build_requires('cmake-utils', force_host_context=True)` and Conan will force this build-requires to stay in the _host_ context, Conan will generate the information you expect as with any other requirement. Of course, this will only work if the package doesn't provide binaries you need to run in the _build_ machine.
 * propagate information using `user_info` entry:
 
   ```python
   class CMakeUtils:
       def package_info(self):
          self.user_info.cmake_scripts_path = ['a/path/inside/this/package']
   ```

   and then, in the consumers, get the information via `user_info_build`

   ```python
   class YourConsumer:
      build_requires = 'cmake-utils'

      def build(self):
         path_to_cmake_files = self.user_info_build['cmake_utils'].cmake_scripts_path
         ... copy them to the local folder, pass them to CMake,...
         cmake = CMake(self)
         cmake.definitions['PATH_TO_MY_SCRIPTS']  = path_to_cmake_files
   ```

In the future, we should be able to provide a more integrated way.

**Comment by daravi** [comment]
@jgsogo Thank you for the explanation.

> `find_package(protobuf)`
> You expect CMake to find the Debug package, which is the one that offers the configuration you are building.

Actually we do this exact thing in our CMake and we want to find the binary directory of the build context for `protoc` since in CMake we do:
```
execute_process(COMMAND ${CONAN_BIN_DIRS_PROTOBUF}/protoc ...)
```
I understand it is not possible since we later also link with protobuf libraries and as you said both profiles cannot generate the same variables at the same time with current design. But I am just saying that just because we have listed a requirement in both profiles doesn't mean we would prefer to have the host version of variables generated. I would have preferred if both build and host had variables generated separately e.g. `HOST_CONAN_VAR_NAME` and `BUILD_CONAN_VAR_NAME`. And I think `CONAN_<PKG-NAME>_ROOT` that is now generated for host makes more sense for build context and is not very useful for linking.

> abuse generators built-in functionality. You can declare self.build_requires('cmake-utils', force_host_context=True) and Conan will force this build-requires to stay in the host context

Sorry I forgot to add, our `cmake-utils` package also has the `cmake_minimum_required` version of CMake as a requirement (e.g. `cmake/3.12`). I am guessing `force_host_context` would force the whole sub-graph, and hence also the `cmake` required package to be in host context. Which defeats the purpose for us.

> propagate information using user_info entry

I think this is the right solution for us until Conan 2.0 and your new design (though it would be annoying to have to maintain a patched version of the `protobuf` recipe, so for that one I think we might just use it as a `requirement` instead of `build_requirement`). Do you see any solution that lets me use the path to `protoc` from build context and `protobuf` libraries from host context without patching the `protobuf` recipe to add `protoc` path as `user_info`? Thank you very much for your help!

**Comment by daravi** [comment]
@jgsogo Any thoughts on my last question?
> Do you see any solution that lets me use the path to protoc from build context in my `cmake-utils` (e.g. Relase build), and use protobuf libraries from host context to link against? (e.g. Debug build) (without having to patch the upstream protobuf recipe to add protoc path as user_info)

I just realized I can add protobuf as the requirement of the build_requirement re-export the path to the `protoc` binary as a `user_info` variable from my `cmake-utils` package. However this solution is also not ideal for us since we want to be able to run incremental CMake builds for the end consumer. Whereas the above solution requires us to run:
```
conan build ...
```
Each time we want to build. (even if we just need to run `cmake --build`)

**Comment by jgsogo** [comment]
Hi, @daravi 

Your solution adding `protobuf` as a requirement of your `cmake-utils` (build-requirement) is the way to go... in fact, you require `protoc` in some of your CMake scripts. I agree that the way to propagate the information can be improved, and it will be improved in Conan v2.

Conan provides some _environment_ generator that will generate `.sh/.bat/.ps1` files. If you want to run `cmake --build` in your command line there is information that cannot be in the toolchain and you need environment or command line arguments (for example, the Generator when calling `cmake`). You can use and activate the file provided by `virtualrunenv` generator, it will add the PATH to the `bin` folders of your build-requirements to the environment (same environment you have inside `build()` method).

**Comment by daravi** [comment]
@jgsogo Thank you! For anyone reading the thread it is also possible to use [`CMakeToolchain`](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html#cmaketoolchain) if you don't want to use `virtualrunenv`.
