### ISSUE TITLE
conan config command to read/edit the "conan.conf" file

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#843]
e.g.
conan --storage-path
~/.conan/data

**Comment by memsharded** [comment]
```bash
less ~/.conan/conan.conf
```
;)

Now, no kidding, what do you need that information for, as a command? Typically, such things are a symptom of other underlying issue. If any, maybe it would make sense a ``conan config`` command that would list different conan configuration values (not only the storage-path), or even maybe allow to change them.

**Comment by lasote** [comment]
We have considered it very useful for CI environments especially if you need to automate some changes like the storage path, the default settings, or other new config variables coming in next releases like CONAN_TRACE_FILE, CONAN_LOG_RUN_TO_FILE, CONAN_LOG_RUN_TO_OUTPUT, CONAN_PRINT_RUN_COMMANDS, etc.

**Comment by memsharded** [comment]
Released in 0.20, please try and report if necessary: http://docs.conan.io/en/latest/reference/commands.html#conan-config
