### ISSUE TITLE
build_requires include paths are not added when using cross platform building

### ISSUE THREAD

**Issue by AistisT** [conan-io/conan#8432]
So we recently started using conan and from various source we implemented our cross platform using already deprecated _build suffixes.

Trying to switch to host/build profiles now and I have an issue where our build_require libraries are not being added to conan include dirs. I know build_requires are meant for build tools and only available during compilation, not part of final binary. We are using it for two testing libraries, which are only used for unit tests, not part of final deliverable and not should impact pacakge id.

Is it still possibly to use double profile with build_requires for such thing as testing header only libraries?

**Comment by AistisT** [comment]
ok I discovered force_host_context=True, which seems to fix it. I must say navigating conan documentation is skill of its own. It would be nice if it had more references to other part of documentation that is related.

There are at least 3 pages describing host/build profiles and they don't exactly refer to each other.

**Comment by danimtb** [comment]
Hi @AistisT,

Glad you found the `force_host_context=True`, this was added to support the testing use case. Indeed, we have to improve the documentation on this matter. I have created a new issue in the documentation repo to improve this, so I am closing this issue as solved. Thank you!
