### ISSUE TITLE
[feature] conan imports build_type

### ISSUE THREAD

**Issue by p-groarke** [conan-io/conan#8437]
Importing dlls using a cmake multi config generator may cause issues when the library names are identical for different configurations. It is less common for something like debug, but problems are almost guaranteed when supporting both `Release` and `RelWithDebInfo` configs.

Feature : Add the ability to specify the `conan imports` build config, to import appropriate files from cmake generator expressions.

Ex: `conan imports . -s build_type=RelWithDebInfo`

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi!

`conan imports` belongs to the set of local workflow commands that requires some files in the working directory (or the install directory if provided). As it is stated in the documentation (https://docs.conan.io/en/latest/reference/commands/misc/imports.html), it requires a `conanbuildinfo.txt` which is generated by `conan install`. All these local commands (`source`, `build`, `package`,...) use the same approach to ensure that they are using the same configuration.

So, you need to run `conan install [--profile]` before running `conan imports` and Conan will use the configuration from the install call.

**Comment by p-groarke** [comment]
Yes I am aware. The `multi` generators are meant to be used for multiple `build_types` at the same time. Sometimes you need to run the import step from generator expressions and specify the build_type.

ex:

```
# Dependency libpotato has a potato.dll for release and a potato.dll for relwithdebinfo.
[imports]
bin, *.dll -> ./bin

# Start with empty build folder.
build/
conan install .. --build missing -s build_type=Debug
conan install .. --build missing -s build_type=Release
conan install .. --build missing -s build_type=RelWithDebInfo

# Trivia, which dlls are in build folder? ;)
cmake ..

# Don't need to rerun cmake config step in multi generators.
cmake --build . --config Release
```

**Comment by p-groarke** [comment]
Note, if your answer is the libs shouldn't name their dlls the same thing for different configs, I agree. But some dependencies don't follow that rule.

**Comment by jgsogo** [comment]
Hi, @p-groarke . That's a really good point, `conan install` does execute method `imports` and different configurations might have the same name for DLLs, it is very common (not only debug/release, but switching an option usually creates different binaries with the same name).

This situation makes it impossible to use multi-generators for that recipe. I would say that the bad practice is not to have the binaries with the same name, but to require them to be in the _working folder_. I think that everything from a package should stay in the package folder, and the path to the resource propagated via the generators... then those generator-expressions can use the right path to the resource.

Trying to answer the question: we are moving forward to Conan 2.0, and it will focus on a different experience for the local workflow (we expect it to be better). We cannot add configuration arguments to other local-workflow commands (`source`, `build`, `package`, `imports`,...) as it breaks the core assumption of the local-workflow logic: write the configuration once, and Conan will guarantee that it uses the same configuration for all the local commands.

I think this feature-request would require a different user story for the local workflow and that should wait for Conan 2.0 (we need to define what will be implemented and how this use-case can work there). In the following weeks, we will start to talk about local-workflow with the [Conan tribe](https://conan.io/tribe.html).

**Comment by p-groarke** [comment]
Sounds fair to me. I haven't looked into too much details, it just popped up as a limitation for us. I know you can set an env path for windows to search dlls, but that is system wide so it breaks locality of conan builds. I'm unsure if there is a way to do so "per executable", through cmake for example. I doubt it though.

Anyhow, no rush to figure this out. Take care.

**Comment by jgsogo** [comment]
Conan provides some run-environment-generators, but they are not _multi_, you cannot have more than one written in the same _working directory_ (the same problem, name collision).  

Associated with the new toolchains approach, the `generate` method and the new generators, one suggestion was to be able to provide a name for a configuration and Conan will use it for the files generated by the generators (like `-Debug`, `-Release`, `-ReleaseO3`,... or any other custom name). This approach would be extended to other generators and then the user will have a way to avoid those name collisions (and give meaningful names to configurations). Still, it won't solve the `imports` collision (probably it is not solvable).

Thanks! I'll keep in mind this issue for Conan v2.0

**Comment by memsharded** [comment]
The new ``folders`` feature in Conan 1.37 provides an ``import_folder`` that could be configured to import files from different configurations to different folders without colliding/overwriting., I think this is related to this ticket.

**Comment by memsharded** [comment]
The imports command has been made legacy in Conan 1.X by explicit copy() in generate() and removed in Conan 2.0. Closing this ticket, please create new tickets as necessary, thanks!
