### ISSUE TITLE
[question] Is there a way to skip specific packages from build when calling install --build?

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8442]
I've built a package separately and it took a lot of time. I want to rebuild other main project's dependencies but pass a specific package. Is it possible?

**UPD**: Or even better, an option that will force build packages fetched from remote but skip build if the package has already been built in local cache.
Example: I build qt from sources which takes a lot of time, then it is built and ready in my cache. I run `conan install` in my application project and it fetches another packages and builds it from sources skipping the qt

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @xahon,
If you want to skip building already built packages you should pass the `missing` parameter to `--build` argument when calling `conan install`. If you just call `--build` Conan will try to rebuild all the dependencies from sources. If you already built that package for the same configuration that you are using in the consumer project, then it should not be built but reused from the Conan cache. Please have a look at the [Conan build policies](https://docs.conan.io/en/latest/mastering/policies.html).
Thanks a lot for your question, I hope this helps.

**Comment by czoido** [comment]
Hi @xahon,
I think I misunderstood your question. Do you mean that you want to build everything but an specific package?
Something like: `conan install --build --build=!mypkg`
If that's the case that's not possible currently in Conan but could be a valid feature request.

**Comment by xahon** [comment]
@czoido Hi! Yes, I meant especially this. I want to rebuild "everything" except "something". Could you transform the issue into a feature request?

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/8483, will be available next 1.36
