### ISSUE TITLE
[bug] scm shallow unspecified and scm shallow=None have different behavior with scm_to_conandata=1

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#8449]
if I enable `scm_to_conandata=1`, then `conans/test/functional/scm/test_git_shallow.py` will fail.
the behavior of the following:
```
scm { 'url' : 'something' }
```
and
```
scm {'url': 'something', 'shallow' : None}
```
is no longer identical, in the second case explicit `shallow=None` effectively works as `shallow=False` (while unspecified value works as default `shallow=True`)

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by jgsogo** [comment]
More info, if I understood you well. The problem is that `shallow=None` is not serialized to the `conandata.yml` (we skip None values when writing to it) and the default value for `shallow` is different from `None`.  So, when we read the information from `conandata.yml` we assume `shallow` should take the default value (when the explicit value by the user was `None`) .

**Comment by SSE4** [comment]
by default, we never serialize None scm values:
```
    def as_dict(self):
       ....
       d = {k: v for k, v in d.items() if v is not None}
```

but we use the helper to evaluate effective shallow value:
```
self.shallow = _get_dict_value(data, "shallow", bool, SCMData.SHALLOW_DEFAULT)
```
under the hood it does:
```

def _get_dict_value(data, key, expected_type, default=None, disallowed_type=None):
    if key in data:
        r = data.get(key)
        if r is None:  # None is always a valid value
            return r
        ...
    return default
```

so, if key (`shallow`) is not in the scm data (unspecified), we return default (`SHALLOW_DEFAULT` which is `True`)
if key (`shallow`) is there, but has `None` value, we just return `None` (None is always a valid value, as code says)

then, we just treat `None` as regular boolean value (which effectively acts as a `False`):
```

            if self._data.shallow:
                output += use_shallow()
            else:
                output += use_not_shallow()
```
