### ISSUE TITLE
[feature] preserve lockfile named parameters in the build_order json output

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#8450]
We are following the https://docs.conan.io/en/1.28/versioning/lockfiles/build_order.html documentation along with https://github.com/conan-io/examples/blob/master/features/lockfiles/ci/build.py#L106.

We've generated `artifact/build_order_vs2019_16_v142_Debug.json`:

```
[
 [
  [
   "libd/0.1@conan/stable#7400ebfada85b91f49ad7f4bbb5c0244",
   "0d4135ad3773880e8ae63ed2e7e1581b8358c30d",
   "host",
   "6"
  ]
 ],
 [
  [
   "app1/0.1@conan/stable#e06a1c33b98b1b8db07f9b6b068e8c4f",
   "67286ee7584da0a2a41ebca3a72d2770b05387c2",
   "host",
   "5"
  ]
 ]
]
```

and we are now parsing it (Groovy, not python as in https://github.com/conan-io/examples/blob/master/features/lockfiles/ci/build.py#L106 ).

I see the definition for the items in the build order json file: is in https://docs.conan.io/en/1.28/versioning/lockfiles/build_order.html :

```
[
  # First level liba
  [["liba/0.1@user/testing", "5ab8...1ac9", "host", "4"]],
  # Second level libb and libc
  [["libb/0.1@user/testing", "cfd1...ec23", "host", "3"],
   ["libc/0.1@user/testing", "cfd1...ec23", "host", "5"]],
  # Third level libd
  [["libd/0.1@user/testing", "d075...5b9d", "host", "2"]],
  # Fourth level libd
  [["app1/0.1@user/testing", "3bf2...5188", "host", "1"]]
]
```

Can I ask why named parameters aren't used in this json?

i.e. why not:

```
[
  # First level liba
  [["ref":"liba/0.1@user/testing", package_id:"5ab8...1ac9", context:"host", id:"4"]],
]
```

to match exactly what was in the lockfile?  

It feels brittle to have dropped the labels.

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
