### ISSUE TITLE
[feature] Using [conf] block in profiles to skip running tests as part of build()

### ISSUE THREAD

**Issue by chausner** [conan-io/conan#8454]
The new [[conf] block](https://blog.conan.io/2021/01/27/New-conan-release-1-33.html) added to profiles in Conan 1.33 seems like a great addition that has been missing so far, so thanks a lot for adding this!

I think it might be useful to allow users to skip running tests as part of the build. The official recommendation is to run tests as part of `build()` like this :
```python
def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
    cmake.test()
```

Unfortunately, with larger test suites or tests that take long to run, it can get impractical when you just want to quickly perform a rebuild. Since we wanted to have an easy way of building without running tests, we are currently having our unit tests in test_package but this only works when your tests do not depend on any internal headers/APIs (and it also comes with other issues).

Now with [conf] available, I'd like to give this a try:
```python
def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
    if not self.conf["user:skip_tests"]:
        cmake.test()
```

What might be a problem though: currently these conf values can only be set as part of a profile and not on the CLI. To be really useful for enabling/disabling tests, there would need to be a way to specify these conf values as parameters to `conan build`.

**Comment by chausner** [comment]
Right after posting this issue, I was checking the command-line parameters of `conan build` again and found out about https://docs.conan.io/en/latest/reference/conanfile/attributes.html#should-configure-should-build-should-install-should-test. So it seems there is actually already a nice solution built-in. :)

**Comment by memsharded** [comment]
Hi @chausner 

The truth is that this is a very valid request. The ``should_test`` thing is only for the consumer package, but it is also useful to be able to define run_tests yes/no for all packages in the graph, not only the consumer one. Right now there is one environment variable CONAN_RUN_TESTS, intended for this purpose. This feature request would be to provide a [conf] alternative, that the builtin build helpers can also implement.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/9218 implemented this, will be released next 1.39

**Comment by samuel-emrys** [comment]
Has support for this been dropped in the new `conan.tools.cmake.CMake` build helper?

**Comment by memsharded** [comment]
What do you mean @samuel-emrys 

I still see there:
```python
    def test(self, build_type=None, target=None, cli_args=None, build_tool_args=None):
        if self._conanfile.conf.get("tools.build:skip_test", check_type=bool):
            return
```
So it seems it is ok? can you please be a bit more explicit? Thanks!

**Comment by samuel-emrys** [comment]
Yeah, you're right @memsharded. I must have been doing something else when it wasn't working for me. Just checked though, and everything is working fine. Cheers.
