### ISSUE TITLE
EOL for public binrtray - any plans on what will be picked as an alternative?

### ISSUE THREAD

**Issue by EugenMayer** [conan-io/conan#8460]
JFrog is shutting down bintrag, source https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Are there any plans to relocated, if yes, what are the plans.

Since we need to change all the CI's and all that, or even plan to migrate the current bintray somewhere else (instead of rebuilding) - what are the plans (before all the builds start to fails :)

**Comment by solvingj** [comment]
@EugenMayer we have recently published a blog post on the Conan blog here regarding the Bintray sunset announcement. 

https://blog.conan.io/2021/02/05/JFrog-announces-sunset-bintray.html

There we outline what some of the best options are, depending on how users are currently using Bintray today. 

Please have a look there and let us know if you have additional questions.

**Comment by EugenMayer** [comment]
Thank you a lot, very helpful! 

This issue can be closed IMHO - sure for you to decide
