### ISSUE TITLE
[question] access to profile env values in generate method

### ISSUE THREAD

**Issue by mkacher** [conan-io/conan#8467]
I am using a profile to populate a number of values for the compile such as CC, CXX, etc. I am now experimenting with the new [MakeToolchain](https://docs.conan.io/en/latest/reference/conanfile/tools/gnu.html#maketoolchain). I would like to use the maketoolchain generator to populate conan_toolchain.mak with the values of CC, CXX, etc from the profile so that after the conan install, I can simply call make on my project and it will pick up the toolchain that was identified by the profile of the install. The env values from the profile do not appear to be available in the scope of the generate() method.

Given that profile1 is part of my project, and my makefile is properly configured to utilize conan_toolchain.mak, is this use case possible?:
```
git clone <my project>
conan install . -pr ./profile1
make   # using profile1 toolchain
```
Am I thinking about this the right way, or is there another paradigm to populate the maketoolchain file?

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by solvingj** [comment]
I understand why you would want to do this, and I can see a need for it myself.  However, be aware that in the general case, the generated toolchain file would not be portable (could not safely be committed to SCM for example). It would contain local paths. For this reason, I think this makes sense for a "custom gnu make toolchain" , which you would call on-demand such as `--toolchain=gnu_make_env_vars` . Then you could include the generated toolchain files from both the built-in, and your custom generator. Unfortunately, we still don't have support for on-demand custom toolchains worked out, so you'd have to patch the built-in one to get the behavior you want. 

On that note, it looks like the environment variables are used for the `MesonToolchain`, so they're almost certainly available.  It looks like you can just pull them straight out of `os.environ`. 

https://github.com/conan-io/conan/blob/develop/conan/tools/meson/toolchain.py#L63

```python
    def __init__(self, conanfile, env=os.environ):
        ...
        self._env = env
```

Followed by checking the values and converting them to meson-specific formats. 

https://github.com/conan-io/conan/blob/develop/conan/tools/meson/toolchain.py#L153-L161

```python
            "c": self._to_meson_value(self._env.get("CC", None)),
            "cpp": self._to_meson_value(self._env.get("CXX", None)),
            "c_ld": self._to_meson_value(self._env.get("LD", None)),
            "cpp_ld": self._to_meson_value(self._env.get("LD", None)),
            "ar": self._to_meson_value(self._env.get("AR", None)),
            "strip": self._to_meson_value(self._env.get("STRIP", None)),
            "as": self._to_meson_value(self._env.get("AS", None)),

```

It seems like you could just leave out the to_meson_value conversion and use the raw value to achieve your goal.

**Comment by memsharded** [comment]
> The env values from the profile do not appear to be available in the scope of the generate() method.

Yes, this is a known not-a-feature-yet of ``generate()`` and the generated files. We are already working on it (https://github.com/conan-io/conan/pull/8426), though it is a bit early stage. The idea remains similar, at ``generate()`` time, Conan and the recipe should generate the necessary information to be able to launch the build without calling Conan. Please keep tuned to next releases.

**Comment by mkacher** [comment]
Thank you for the info. I have been able to get the result I was looking for using a different approach. I put the toolchain of interest into its own package. Within `package_info()` I populated env_info with all of the relevant parameters. I also specified `settings = "os_build", "arch_build"` for the package settings and `validate()` them against the version of the toolchain.

```
    def package_info(self):
        _sysroot ="gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc"
        self.env_info.SYSROOT = path.join(self.package_folder, _sysroot)
        _path1 = path.join(self.package_folder, "bin")
        _path2 = path.join(self.package_folder, "aarch64-linux-gnu/bin")
        _path_os = "/usr/sbin:/usr/bin:/sbin:/bin"
        self.env_info.PATH = _path1+":"+_path2+":"+_path_os
        self.env_info.CONAN_CMAKE_FIND_ROOT_PATH = self.env_info.PATH
        _th =  "aarch64-linux-gnu"
        self.env_info.CHOST = _th
        self.env_info.AR=_th+"-ar"
        self.env_info.AS=_th+"-as"
        self.env_info.RANLIB=_th+"-ranlib"
        self.env_info.LD=_th+"-ld"
        self.env_info.STRIP=_th+"-strip"
        self.env_info.CC=_th+"-gcc"
        self.env_info.CXX=_th+"-g++"
        _inc = path.join(self.package_folder, "aarch64-linux-gnu/include")
        self.env_info.CXXFLAGS="-I"+_inc
        self.env_info.CFLAGS="-I"+_inc
        print(self.env_info.__dict__)
```

Within the consumer project I specified my toolchain package as a `build_requires` and was able to populate the toolchain with values from deps_env_info. The resulting conan_toolchain.mak worked exactly as I was hoping for.
```
     def generate(self):
        print("** generate **")
        tc = MakeToolchain(self)
        tc.variables["CONAN_CMAKE_FIND_ROOT_PATH"] = self.deps_env_info["linaro_tc"].CONAN_CMAKE_FIND_ROOT_PATH
        tc.variables["SYSROOT"] = self.deps_env_info["linaro_tc"].SYSROOT
        tc.variables["PATH"] = self.deps_env_info["linaro_tc"].PATH
        tc.variables["CHOST"] = self.deps_env_info["linaro_tc"].CHOST
        tc.variables["AR"] = self.deps_env_info["linaro_tc"].AR
        tc.variables["AS"] = self.deps_env_info["linaro_tc"].AS
        tc.variables["RANLIB"] = self.deps_env_info["linaro_tc"].RANLIB
        tc.variables["LD"] = self.deps_env_info["linaro_tc"].LD
        tc.variables["STRIP"] = self.deps_env_info["linaro_tc"].STRIP
        tc.variables["CC"] = self.deps_env_info["linaro_tc"].CC
        tc.variables["CXX"] = self.deps_env_info["linaro_tc"].CXX
        tc.variables["CXXFLAGS"] = self.deps_env_info["linaro_tc"].CXXFLAGS
        tc.variables["CFLAGS"] = self.deps_env_info["linaro_tc"].CFLAGS
        tc.generate()
```
