### ISSUE TITLE
[feature] Consider a way to specify a lazy 'scm' member

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#8473]
Conan v2.0 will stop rewriting `conanfile.py` after `scm` substitution, it will always use `scm_to_conandata=True`. When the `conanfile.py` is not rewritten, functions that are evaluated when the recipe is loaded are quite inconvenient (these function might use some commands to get information from the SCM, but when the recipe is in the cache the SCM is no longer there).

An alternative for users would be to turn the `scm` member into a property to get some level of laziness:

```python
class Recipe(ConanFile):

    @property
    def scm(self):
        ... computation based on working directory
        return {'type': 'git', ....}
```

But this approach crashes when Conan tries to get the information from the `scm` _member_ and merge it with the information coming from the `conandata.yml`. 

We can support this implementation and control when the `scm` is executed, **at least we can offer a more meaningful error** than the one raised when loading the recipe file.

---

IMO, it is not possible to avoid the source code inside `scm` to raise because Conan **always** needs to evaluate `scm` and then updates the information with the one coming from `conandata.yml`.  It means it is always the responsibility of the user to handle the exceptions when computing scm entries.

**Comment by Saumya-ranjan** [comment]
Is anyone working on this issue?

**Comment by memsharded** [comment]
Hi @Saumya-ranjan 

No, nobody working in this. The ``scm`` feature has actually been deprecated and removed in 2.0. 
It has already a new alternative in 1.X, please check: https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature

I am closing this, please check that docs, and if there is any further question related to the new approach, file a new ticket. Thanks!
