### ISSUE TITLE
[question] defining Document directory in editable layouts 

### ISSUE THREAD

**Issue by markfoodyburton** [conan-io/conan#8477]
Is it possible to define a documents directory in an editable layout file for use in a workspace?
e.g. we have a number of packages that we would like to combine into a single workspace, with the src in src/package/... (or whatever) likewise includes, but equally the documentation (and potentially other files too?)

It seems there is a defined mechanism for source, include and build files, but I dont see other options?
(I can imagine documentation, configuration files, . . . )

Perhaps this is possible using Jinja - but it looks like it could get messy for relatively simple cases?

**Comment by danimtb** [comment]
have you tried using `[resdirs]`? That should map the folders declared in `cpp_info.resdirs` to the editable layout https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info

**Comment by markfoodyburton** [comment]
Ah, thanks for the hint, we'll give this a try !

**Comment by danimtb** [comment]
let me know if that worked for you and I'd add it to the docs for clarification

**Comment by markfoodyburton** [comment]
FYI, this didn't work for us. In the end, unfortunately, we concluded that we were trying to force a square peg into a round hole. What we were trying to get Conan to do isn't really what conan is for. We conclude conan is great for managing 'packages', but we were trying to use it to assemble a package that would then be 'built' using e.g. cmake.

**Comment by danimtb** [comment]
Thanks for writing back @markfoodyburton. I hope the approach you found makes sense for your team and do not hesitate to open another issue if you have further questions. Thank you
