### ISSUE TITLE
[question] msbuild generator: transitive dependency to static lib

### ISSUE THREAD

**Issue by Carsten87** [conan-io/conan#8480]
I've got the following scenario:

lib A (dynamic lib) -> lib B (dynamic lib) -> lib C (static lib).

lib A is a Visual Studio project which uses the property sheets generated by the msbuild generator. It references the property sheet for lib B.

lib B is a dynamic lib which has lib C linked into it. Therefore lib B 'requires' lib C.

Now the property sheets for lib B reference the property sheets for lib C. This leads to lib A also linking against lib C which I would like to avoid since that is not necessary because lib A does not need lib C.

How can I avoid linking lib A with lib C?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @Carsten87 , the current implementation of the Conan graph is not able to manage this situation properly.

You could use in B's `conanfile.py` the statement `self.requires("C", private=True) to achieve what you want, but the implementation of this _private_ is a bit buggy and you might run into unexpected problems (better to avoid). 

Another alternative that you could use (this one works) although it is more like a workaround is to use _components_ to hide C from A. You can declare in `libB` two components, one of them (`cmp1`) declares a dependency on `libC::libC` while the other (`cmp2`) doesn't. Then, in `A` you can declare that it only depends on `libB::cmp2`. This way you get the isolation you are looking for in your scenario, but if you change the dynamic/static configuration of your project the build will fail.

In Conan 2.0 we have plans to tackle this problem specifically and we will provide a more powerful and feature-complete graph.

**Comment by Carsten87** [comment]
Thank you for your answer @jgsogo. I will be looking forward to Conan 2.0 then. In the meantime I will give the component approach a try.

**Comment by jgsogo** [comment]
Can we close this issue, private requirements is something we won't forget about.

**Comment by Carsten87** [comment]
yes of course. My question is answered. Thank you.
