### ISSUE TITLE
[bug] Wrong params when cross compile to iOS (ezored)

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#8494]
### Environment Details (include every applicable attribute)
  * Operating System+version: macos
  * Compiler+version: 12
  * Conan version: 1.13.1
  * Python version: 3

### Steps to reproduce (Include if Applicable)

Hello guys.

I have the project ezored (github.com/ezored/ezored) and im trying now compile for iOS/Macos without my toolchain and use only conan.

When i compile for mac catalyst i got this warning:

```
clang: warning: overriding '-mmacosx-version-min=13.0' option with '--target=x86_64-apple-ios-macabi' [-Woverriding-t-option]
```

The profiles:

```
python make.py target ios_framework prepare && python make.py target ios_framework build && python make.py target ios_framework package
[INFO] Running "prepare" on target "ios_framework"...
[INFO] Building for: x86_64/Release...
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os.subsystem=catalyst
os.version=13.0
os_build=Macos
[options]
ezored_arch=x86_64
ezored_group=ios_catalyst
ezored_name=ezored
ezored_version=1.0.0
darwin-toolchain:enable_arc=None
darwin-toolchain:enable_bitcode=False
darwin-toolchain:enable_visibility=None
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os.version=10.15
os_build=Macos
[options]
[build_requires]
[env]
```

I don't know why the version 13.0 goes to macos min version and don't ios min version (that is required for mac catalyst).

Im executing conan with the params:

```
conan install /Users/paulo/Developer/workspaces/cpp/ezored/files/targets/ios_framework/conan/recipe/conanfile.py -pr:b default -pr:h ezored_catalyst_framework_profile -s:h arch=x86_64 -s:h build_type=Release -s:h os.version=13.0 -s:b os.version=10.15 -o ezored_arch=x86_64 -o ezored_name=ezored -o ezored_version=1.0.0 -o ezored_group=ios_catalyst -o darwin-toolchain:enable_bitcode=False -o darwin-toolchain:enable_arc=None -o darwin-toolchain:enable_visibility=None --build=missing --update
```

The final command for build need be:

```
-miphoneos-version-min=13.0
```

**Comment by paulocoutinhox** [comment]
I tried compile for armv7 normal for iOS and it work nice.

The problem is with mac catalyst.

**Comment by SSE4** [comment]
looking at the conan code, we use `-mios-version-min` for Catalyst:
https://github.com/conan-io/conan/blob/10e7d5b1e534cc665fa4c403cb560e5de20364d6/conans/client/tools/apple.py#L70
is it possible flags were added by `darwin-toolchain`? could you try without it?

**Comment by paulocoutinhox** [comment]
Hi,

I already solve it.

Thanks and i will close.
