### ISSUE TITLE
Consider adding support for Premake as a generator

### ISSUE THREAD

**Issue by pr0g** [conan-io/conan#85]
In the same way that cmake is currently supported as a generator it would be awesome to add support for premake 4/5.

In the same way a cmake file includes these lines

...
INCLUDE(conanbuildinfo.cmake)
CONAN_BASIC_SETUP()
...

it would be fantastic if something similar could exist for premake. So within a premake.lua file there could be something akin to:

...
include "conanbuildinfo.lua"
conan_basic_setup()
...

which would include the relevant conan dependencies when doing a build with premake

**Comment by redi-foran** [comment]
I'm working on Issue #67, which would allow you to directly add support for this.  I'll comment when I'm done with that effort.

**Comment by pr0g** [comment]
Oh awesome! Sounds great, please do! Thanks! :)

**Comment by memsharded** [comment]
I have a working example in: https://github.com/memsharded/conan-premake

Please note that this requires to work also my conan fork branch: https://github.com/memsharded/conan/tree/feature/dynamic_generators

This is an awesome approach, thanks to @skizzay (@redi-foran), as it could allow this premake generator to evolve quickly and independently to the main conan codebase.

I have taken a minimalistic approach to begin, just create some variables and use the variables inside the premake4.lua script. 

I guess this could be released in 0.9, I'd love to have some feedback (can wait to the release if not willing to run from source), cheers!

**Comment by pr0g** [comment]
No way that sounds awesome! Super cool to see! :) :+1:

**Comment by memsharded** [comment]
Support for generator packages that can be uploaded and retrieved dynamically has been released in 0.9.

An initial version for Premake4 generator is in: https://www.conan.io/source/PremakeGen/0.1/memsharded/testing

and the repo: https://github.com/memsharded/conan-premake

Let's close this issue, it is solved, and if necessary, move development, issues, etc., to the package repository. This generator can evolve now very quickly and independently from the conan main codebase, so go ahead, try it and let's improve it together! Thanks!

**Comment by pr0g** [comment]
This is super cool! I will definitely check this out soon! Nice work! 😄 

Also just about to listen to the newest Cpp Cast about Conan! 👍
