### ISSUE TITLE
cmake_multi generator uses same bin directory for all targets

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#851]
Hi,

I've been trying the new `cmake_multi` generator with Visual Studio, and I finally got it to work.
There are however some inconveniences:

- The cmake_multi generator doesn't help to put dependency binaries (.dlls and .dylibs) into different directories for different targets, so I've had to use a **Python** conanfile and do something like this to prevent release and debug binaries to be mixed:

      def imports(self):
          self.copy("*.dll", dst=str(self.settings.build_type), src="bin")
          self.copy("*.dylib", dst=str(self.settings.build_type), src="lib")

- Both release and debug targets use the same output directory, which is configured inside `conanbuildinfo_multi.cmake`:

      macro(conan_output_dirs_setup)
          set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/bin)
          set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
          set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
  This is surprising as Visual Studio would put builds with different configurations into different directories by default. I redefined these variables inside my CMakeLists.txt to fix this.

Am I missing something, or should this be documented/improved?

**Comment by memsharded** [comment]
Yes, this could be improved.

I think that redefining ``conan_output_dirs_setup`` would be a first obvious step. This is copied & pasted from the other single-conf generator, and is not useful here.

Regarding the ``imports`` I guess your solution is quite good. Most conan packages will not define debug/release subfolder for package libs, so importing them according to the consumer layout seems reasonable, specially when the layout can change from package to package (some would use Release64, others just Release, and so on). Other people might like to have all both debug and release artifacts in the same folder, but differentiate by the library names (typically adding a ``d`` suffix to the lib)

**Comment by memsharded** [comment]
Hi @sixten-hilborn, @lasote

Please check: https://github.com/conan-io/conan/pull/880

Basically, disabling the re-definition of output directories works. Of course, the user of the cmake_multi generator has to handle the different output directories, like Debug, Release folders, as the changed tests does.

This could be a breaking change if some users are already using the ``cmake_multi`` generator for **creating packages**, but I think that is definitely not a use case, and should be strongly discourage (in fact it should not work at all and fail). This cmake_multi generator is intended for consumers only.

**Comment by sixten-hilborn** [comment]
Hi @memsharded, thanks for the update! I think your patch looks good for solving the issue with the generated `.cmake` file.

However the `imports` section needs some improvement as well. My solution would work for `cmake_multi` generator and Visual Studio. But if I want to build from makefiles and use the `cmake` "single" generator, the import destination is `build_type` while `conanbuildinfo.cmake` outputs executables to `bin/`.

It would be nice to have a tool which helps setting up the output directory (defaulting to `bin/` for "single" generators and `build_type` for "multi" generators), that could be accessed from both text and Python conanfiles. Settings in such a tool (could be a property of `ConanFile`) can propagate to the generated `.cmake` files so output directories would match.

**Comment by memsharded** [comment]
I am not sure if I get the use case. I think that using both ``cmake_multi`` and ``cmake`` simultaneously doesn't make too much sense, does it? And how do you switch from one to the other, you have to manually edit the ``conanfile`` I guess.
When you are in the consumer side, you might not know at all which is your build system, if it is multi-configuration or single-configuration. Just consider a simple conanfile.txt:

```
[requires]
Pkg/0.2@user/channel

[generators]
cmake

[imports]
# imports for single-conf
```

Maybe for different consumer side options would make sense to have 2 different conanfiles, and use the ``--filename`` command line argument to use one or the other?

**Comment by sixten-hilborn** [comment]
One use case: you want to build your project using both Visual Studio and MinGW. For Visual Studio you can use `cmake_multi`, and `cmake` for MinGW + makefiles.

This should not need multiple conanfiles. For conanfile.txt some variable $default_bin_dir can be introduced, and similarly self.default_bin_dir for conanfile.py.

**Comment by SSE4** [comment]
@memsharded may I ask may be a silly question - why does the conan override global project settings, like CMAKE_XXX_OUTPUT_DIRECTORY, or tries to manage Visual Studio runtime-library related flags like /MT, /MD, etc?

I personally found it a bit surprising and misleading the first time I've encountered the issue my project`s settings of CMAKE_XX_OUTPUT_DIRECTORY were not applied, since conan_basic_setup() call has  overwritten them for some reason. also, I didn't find conan_output_dirs_setup() docummented on http://conanio.readthedocs.io/.

as a consequence, developer has always set 9 CMAKE_XX_OUTPUT_DIRECTORY variables just after conan_basic_setup() call in order to overwrite this behaviour.

**Comment by memsharded** [comment]
No silly question at all, yes, that is a place for improvement. For the recent ``cmake_multi`` generator, I just removed the call to the macro that sets the output paths.

The reason is that we really never expected so much usage of the ``conan_basic_setup()`` macro. The idea of ``conanbuildinfo.cmake`` was to define some variables and let users to what they need with the variables. It was mainly a convenience, but now it is widely used.

So, as a convenience, it was really convenient to have the output dirs always to "bin", and to get rid of the "Debug/Release" folders in VS, for testing, for demos, for examples, for the docs. The truth is that such behavior can be easily changed, as the ``conan_basic_setup()`` is structured just as some calls to other macros, so removing the dirs setup is straightforward.

So I think this deserves better docs: https://github.com/conan-io/docs/issues/141

Regarding the setting of MT/MD, etc. in that case the cmake shouldn't do it globally or automatically, only if dictated by conan settings.

**Comment by memsharded** [comment]
@sixten-hilborn I am not sure that we need to add more variables for this. What about?:

```python
def imports(self):
    if self.settings.compiler == "gcc":
         self.copy("*.dll", dst="bin")
    else:
         self.copy("*.dll", dst=str(self.settings.build_type))
```

**Comment by sixten-hilborn** [comment]
Yeah that code is pretty straightforward, but there are some concerns:

This might be a common pattern for `cmake_multi`, and I think common patterns should be made as simple as possible, by putting the common code in one place (conan). Having to do fewer (or no) changes in conanfile/cmake files to switch over to `cmake_multi` is also good.

There's a case where one project will use both `cmake` and `cmake_multi` for Visual Studio (or any other generator that allows multi-configuration). Example: One developer may want both release and debug dependencies, where someone else just want the debug dependencies to save build time, while CI uses release only.  This case needs some other logic than checking compiler in the conanfile.

**Comment by memsharded** [comment]
I see, now I understand the use case.
What I dont see right now is the proposed solution. Adding a variable to the conanfile, but how would it know that you are using one or the other? If you could outline a bit more what you have in mind, that would help. Thanks!

**Comment by memsharded** [comment]
Hi @sixten-hilborn ,

This issue was planned for 0.19, which is tomorrow, but still pending the ``imports`` issue, any suggestion regarding it? I still can't figure out a good way to address it. Thank you!

**Comment by sixten-hilborn** [comment]
Hi @memsharded, sorry for not answering! Exciting with a new release :)

I don't have a concrete solution yet. Should we postpone `imports` improvements to 0.20? I think I need to experiment more and get a better understanding of conan's core...

**Comment by memsharded** [comment]
Yes, this feature has been partially addressed in 0.19, but the "imports" part is still open. Let's postpone it for 0.20.

**Comment by memsharded** [comment]
Hi @sixten-hilborn,

Next release 0.20 is already huge, unless you have any new idea for this issue, I think we should move it forward to 0.21, what do you think?

**Comment by sixten-hilborn** [comment]
Sounds good! I haven't worked on this issue yet anyway.

**Comment by memsharded** [comment]
I think a valid approach for the missing "imports" part could be:

- Use a profile for each config
- Define an env-var in such profile like ``CONAN_IMPORT_PATH``
- Use the env-var in the recipe `imports()` 

Env-vars are respected in `conan imports` command too

IMHO, there is no generic solution for this issue, as long as users can write:
```bash
$ conan install -g cmake -g cmake_multi
```

Furthermore, it is not strictly necessary that the ``cmake`` generator uses the predefined output folders, as this can be very easily changed, so even knowing that the ``cmake`` or ``cmake_multi`` generator is being used, no assumptions should be made about the folders.

I was not happy about the ``cmake_multi`` generator, as it is something that can be solved with the ``cmake`` generator, just by installing the corresponding ``build_type``, with it is just 3 keystrokes in the terminal. Also, know there are multi-config packages for users wanting to easily have debug-release packages.

As ``imports()`` is something defined by the end-user, I think it is something that can be easily configured by them with some env-vars, it will adapt any flow and folder layout. Trying to do something built-in in conan will add too much extra burden to the conan codebase and will not cover all cases anyway.

So my suggestion is to label this as solved, what do you think?

**Comment by memsharded** [comment]
In any case, moving it to 0.22, it is not something that can be solved for 0.21 release.

**Comment by sixten-hilborn** [comment]
Hi, sorry for my late response. I haven't looked much into this issue as I've been busy with other things.
My general feeling is that profiles are more of a workaround than a proper solution, maybe it's because they don't mix very well with [conan.cmake](https://github.com/conan-io/cmake-conan) (which I prefer over manually invoking `conan`).
Introducing a convention to use `CONAN_IMPORT_PATH` might be good enough:
```
def imports(self):
    dest = os.getenv("CONAN_IMPORT_PATH", "bin")
    self.copy("*.dll", dst=dest, src="bin")
    self.copy("*.dylib*", dst=dest, src="lib")
```
`conan.cmake` can also export `CONAN_IMPORT_PATH` automatically, then it's up to the user to use it or not.

**Comment by memsharded** [comment]
My general feeling is that the workaround is ``conan.cmake``, because I much prefer using profiles, which is the correct solution to me :) :) :)

In an abstract, high-level overview: Project Management/CI > Package Management > Build System > Compiler. 

CMake is clearly more a Build System, so it is not conceptually clean that CMake is being abused to call the package manager. Maybe convenient for cmake users, but definitely not the cleanest approach IMHO.

Besides these opinion discrepancies, I think your approach by convention with ``CONAN_IMPORT_PATH`` might be good enough, indeed. We will try to propose something with it, thanks!

**Comment by memsharded** [comment]
Documented in http://docs.conan.io/en/latest/reference/conanfile/methods.html#imports

Related PR (but not really implementing new features, as they are not required): https://github.com/conan-io/conan/pull/1175

Opened issue in conan.cmake: https://github.com/conan-io/cmake-conan/issues/27

So I think here we are mostly done, thanks!
