### ISSUE TITLE
[question] Private dependencies won't let CMake generator output CONAN_PKG:: variables. Bug or wanted behavior?

### ISSUE THREAD

**Issue by jegabe** [conan-io/conan#8511]
Hello all,

I have the following problem: I want to create a shared library that's fully self-contained and acts as a plug-in. Let's call this shared libary "L". L has some dependencies to header-only and static libraries (lets' call them A and B) that are fully linked into L:

L depends on A
L depends on B

Since A and B are fully linked into the shared library and aren't visible from outside, I don't want my clients that use "L" to get transitive dependencies into A and B because they're hidden.

Now, I have a client (let's call him C) that wants to have a dependency to L. To avoid transitive dependencies, I required "A" and "B" inside the conanfile.py of "L" as "private":

conanfile.py of component "L":
requires = [("A/version@user/channel", "private"), ("B/version@user/channel", "private")]
generators = "cmake"

I use the CMake generator to build "L" and use modern CMake syntax. When I add the "private" for the dependencies "A" and "B", the variables "CONAN_PKG::A" and "CONAN_PKG::B" aren't created any more. But I need them so the targets for "L" can have a target_link_libraries(target CONAN_PKG::A CONAN_PKG::B)

Is this a bug or wanted behavior? If it is wanted: How should I design the L dependencies? If it's a bug: How can I work-around that issue (Only known work-around by me is to use build_requires with force_host_context=True)

**Comment by Carsten87** [comment]
I think this is related to my question #8480

**Comment by danimtb** [comment]
> I think this is related to my question #8480

Indeed, thanks a lot for the link.

@jegabe yes, this was the use case for private requirements but the current implementation is a bit buggy at some points and we try not to encourage their use. Maybe something like adding `--build=L` flag makes the trick for the target if you already have A and B in the cache.

This is something we want to model better in the graph in order to have a similar scheme to the one used by CMake, but we will need to wait for Conan 2.0. Also you can check the solution provided at #8480 as well.

**Comment by SpaceIm** [comment]
I've recently created a recipe in CCI which relies on a private dependency, cmake generator and CONAN_PKG targets:
https://github.com/conan-io/conan-center-index/blob/9f31fd518de2ef8454136aa4cda1ae16b046b14e/recipes/vulkan-validationlayers/all/conanfile.py#L53
https://github.com/conan-io/conan-center-index/blob/9f31fd518de2ef8454136aa4cda1ae16b046b14e/recipes/vulkan-validationlayers/all/CMakeLists.txt#L11

It works as expected in this case.

**Comment by jegabe** [comment]
Hello @SpaceIm, did you use separate host and build profiles with your conanfile.py? That's when the problem arises in our build because we do cross-compiling (embedded)

**Comment by jegabe** [comment]
@danimtb: If usage of "private" dependency is broken, should it then be documented that usage of that should be avoided? The solution provided in #8480 works partially for our company: The linking problem disappears, but the client consuming "L" still gets version conflicts if he needs either A or B in another version that "L" needed. So basically, I need to completely hide that dependency: The dependency is implementation detail of "L". Would you recommend to use build_requires with force_host_context=True in that case? That would work because then, after building "L", the dependencies to "A" and "B" disappear. It would be really great if that could be fixed in conan 2.0 because in a plug-in based system, as we create it now, we intentionally want to "break" transitive dependencies by using shared libraries and make them self-contained (to hide all further dependencies and have the same transitive components linked in different versions by different shared libs)

**Comment by Carsten87** [comment]
I have pretty much the same issue and am also looking forward to a proper solution.

The problem I see with the "build_requires approach" is that your requirement is no longer part of the dependency graph of your product. So you lose the ability to trace what is being delivered as part of the product which could for example be problematic if you would like to collect all licenses automatically or if you need to provide a list of third party components to someone.

**Comment by jegabe** [comment]
I have a good working workaround for the issue: A wrapper conanfile.py that just references the shared library as build_requires with force_host_context=True and then just copying the artifacts of that that build. This way, the dependency tree is fully decoupled and I get what I want. Here's the code I use:

```
from conans import ConanFile

# Conan package to decouple the dependency tree of a plug-in (see _package_to_wrap) from
# the user of the plug-in. By using this wrapper package, the dependencies of the _package_to_wrap are
# isolated from the dependencies of the client, so that the client may require conflicting package versions
# without running into conan trouble
class PluginWrapper(ConanFile):
    _package_to_wrap = "some_conan_package"
    _user_and_channel = "someUser/someChannel"
    _version = "1.0.0"
    name = _package_to_wrap + "_wrapper"
    version = _version
    license = "See wrapped package"
    url = "See wrapped package"
    settings = "os", "compiler", "build_type", "arch"
    keep_imports=True # Important so conan won't discard the .so's/.dll's after build()
    
    # This should be a requirement with private=True, but there is no way with conan to import the .dll's/.so's from a private dependency
    def build_requirements(self):
        self.build_requires(self._package_to_wrap + "/" + self._version + "@" + self._user_and_channel, force_host_context=True)

    # Import build artifacts from the package
    def imports(self):
        self.copy("*.dll", dst="bin", src="bin", root_package=self._package_to_wrap)
        self.copy("lib*.so.*", dst="lib", src="lib", root_package=self._package_to_wrap)

    def build(self):
        pass

    # Re-package the artifacts
    def package(self):
        self.copy("*", dst="bin", src="bin", symlinks=True)
        self.copy("*", dst="lib", src="lib", symlinks=True)
```

**Comment by jegabe** [comment]
@danimtb  If you want to, you can use the workaround in my last comment inside the conan docs as conan < 2.0 work-around for dependency decoupling
