### ISSUE TITLE
Transforming existing header-only library into package

### ISSUE THREAD

**Issue by marcinszumlanski** [conan-io/conan#8522]
I'm trying to create a conan package from existing header-only library. It's not your textbook example with include folder. Structure looks as follows:

```
public/SomeHeader.hpp
public/CHeader.h
public/anotherFolder/AnotherHeader.hpp
```

Here is my **conanfile.py** based on [Documentation](https://docs.conan.io/en/latest/howtos/header_only.html#how-to-package-header-only-libraries) and https://github.com/conan-io/conan/issues/4212.

```
from conans import ConanFile

class MyLibConan(ConanFile):
    name = "MyLib"
    version = "1.0"

def package_info(self):
    self.cpp_info.includedirs = ["public", "public/anotherFolder"]

def package(self):
    self.copy("*.hpp", dst="public", keep_path=False)
    self.copy("*.h", dst="public", keep_path=False)
```
Should I use self.copy in package() method or cpp_info.includedirs? What's the difference?

I export package like this, no errors so far

` export . demo/test`

Then in my main project I have **conanfile.txt** as follows:

```
 [requires]
 MyLib/1.0@demo/test

 [generators]
 cmake
```

My **CMakeLists.txt** previously simply linked exec to MyLib (INTERFACE library) 

```
include_directories(MyLibFolder)
add_executable(someTarget ...)
target_link_libraries(someTarget MyLib)
```

now it is modified like this

```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
...
add_executable(someTarget ...)
target_link_libraries(someTarget ${CONAN_LIBS})
```

After compiling project

```
mkdir build && cd build
conan install ..
cmake .. -G Ninja
cmake --build .
```

I get errors... :(

```
fatal error: anotherFolder/AnotherHeader.hpp: No such file or directory
#include <anotherFolder/AnotherHeader.hpp>
```

I'm super fresh to conan and I cannot for the love of god grasp how to write conanfile.py. I've tried so many different combinations but without much success. I've read documentation and still no clue!

Thanks in advance,

cheers

**Comment by solvingj** [comment]
Your problem is here  `keep_path=False`: 
```
def package(self):
    self.copy("*.hpp", dst="public", keep_path=False)
    self.copy("*.h", dst="public", keep_path=False)
```
`keep_path=False` means that the directory structure containing the files which match the patterns will be discarded, and all matched files will be put directly into the `public` folder.  

Thus, your final package directory will be:

    public/AnotherHeader.hpp

Instead of what you want:

    anotherFolder/AnotherHeader.hpp

```
def package(self):
    self.copy("*.hpp", src="public", keep_path=True)
    self.copy("*.h", src="public", keep_path=True)
```
