### ISSUE TITLE
[bug] Transitive `shared` option is not affecting the package ID (in semver_direct_mode)

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#8523]
### Environment Details (include every applicable attribute)
  * Operating System+version: CentOS 8
  * Compiler+version: Clang 10.0.1
  * Conan version: 1.33.0
  * Python version: 3.8.6

### Steps to reproduce (Include if Applicable)
Create a package with:
```
conan create somepkg:shared=True ...
```

Then try to create the same package as follows:
```
conan create *:shared=True ...
```
The second run returns:
```
The stored package has not changed
```
Due to the package IDs being the same, even though the transitive options are different. (In the first case the requirements have `shared=False`)

### Logs (Executed commands with output) (Include/Attach if Applicable)
Pretty straight forward to test IMO. But if you require more logs please let me know how you prefer I run the test for you.

**Comment by memsharded** [comment]
Sorry for not responding back then.

I am closing this as solved, conan 2 implemented a much better binary model taking this into account.
