### ISSUE TITLE
[question] How to download only recipe and exported sources to the local cache?

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8524]
I wanted to download a recipe and exported sources from artifactory to edit some parts of the recipe but I couldn't find an option, something like `--recipe-only`. Otherwise, I need to cancel downloading process with `ctrl+c` after it downloads something related to my target package because I don't need binaries of that package and its dependencies
How do I see that:
1. sudo rm -rf ~/conan 
2. conan install something/111@ --recipe-only
3. Downloads only recipe and export_sources without package and dependencies
4. ls ~/conan/something/111/_/_/
5. export/ export_sources/ metadata.json metadata.json.lock

Is there an option like that I missed?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by solvingj** [comment]
There's another issue for this. I will post here.

**Comment by solvingj** [comment]
In short, no there's no such feature, but there is an outstanding feature request. If you can explain/show your support in that issue, it might help the feature get attention sooner. 

https://github.com/conan-io/conan/issues/8121

Closing as duplicate.
