### ISSUE TITLE
[question] How to get version passed through refence in the `__init__` constructor of conanfile.py

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8525]
When i building a package without defined version in `conanfile.py` like that: `conan create . something/1.2.3@ -pr ...` i want to get the version `1.2.3` in `__init__` method of the recipe. However, I noticed that it is not initialized in ctor, even after calling `super().__init__()`. Is it initialized in each method separately (build, configure, package, etc...)? Is there a way to get at least full recipe reference in ctor to extract version from that?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
That information is not available in the `__init__`. The version is assigned to the conanfile later. Take into account that there is a method `set_version` that is executed after loading the conanfile whose purpose is to set the value of the attribute you want.

**Comment by jgsogo** [comment]
Maybe, if you share your use-case, we can think about a different alternative to achieve what you want.

**Comment by xahon** [comment]
My company doesn't want to use revisions feature of conan due to a lot of reasons and came out with a simpler solution, to add suffices after version part of package reference. Unfortunately, a lot of recipes are using version part in url, unarchiving, etc.. and i wanted to strip that version suffix in a single point instead of calling that functionality from a bunch of places (source, configure and build are using a brand new instance of recipe class each call)

**Comment by jgsogo** [comment]
From your last comment, I think you don't want to modify the `version` of a reference (which is something a would discourage you from doing), you just need a function to strip the _extra_ components of the version that you don't want. What about a property in your recipe file?

```python

class YourRecipe(ConanFile):

    @property
    def _version(self):
        raw_version = self.version  # Remove whatever you don't need from here
        ... 
        return raw_version

    def source(self):
       tools.get("my-library-{}.tar.gz".format(self._version))
```

You use always `self._version` instead of `self.version` and you only need to write the logic in one single place. That is much better that modifying the actual version of the reference.

**Comment by xahon** [comment]
yes, that was one of the solutions but i didn't want to change original recipe drastically in many places to keep ability to update only the beginning of the recipe if need
