### ISSUE TITLE
[question] Is it possible to override a profile requirement in conanfile

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#8541]
If the profile has

[build_requires]
foo/1.0@com/master

Is it possible to override it with 
self.build_requires("foo/2.0@com/master")

in conanfile?

So far not having much luck with it (seems like conanfile ignores local requirement altogether)

**Comment by solvingj** [comment]
No, the profile will always take precedence over `build_requires` declared in recipes.

**Comment by w3sip** [comment]
Is there a reason for that? IMHO, it'd make sense for profile to establish the defaults, but is there a reason to block recipe-specific overrides?

**Comment by solvingj** [comment]
Yes, there are a vast number of tools where a variable can be specified by multiple mechanisms such as:
- cli
- environment variable
- user config
- system config
- project config
- programmatic runtime conditions
- program default

In the vast majority of tools, the key priority is that caller at the CLI needs to be able to override whatever value might be reconciled from all the other mechanisms.  If the caller wants to accept the reconciled values, the caller just simply needs to NOT specify the value at the CLI. 

The Conan profile is passed via the CLI, and thus, we consider that the `build_requires` is as well.  In your case, the obvious advice would simply be, make a copy of the profile you're using and remove the `build_requires` you don't want, and then use that. I'm guessing you have some reason why you don't want to do that.  I can understand this, however, this is the reason for your dilemma.  

With all that said, I think you would probably agree that it's not a good reason to invert or adjust precedence of this behavior.

**Comment by solvingj** [comment]
Feel free to re-open if you have further questions :)
