### ISSUE TITLE
[bug] activate.sh doesn't set environment variables correctly

### ISSUE THREAD

**Issue by armtir** [conan-io/conan#8545]
### Environment Details (include every applicable attribute)
  * Operating System+version: Debian 10 x86_64 GNU/Linux 
  * Compiler+version: gcc (Debian 8.3.0-6) 8.3.0
  * Conan version: 1.33.1
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)

`activate.sh` sets environment variables under quotes twice.

This is the content of the `environment.sh.env` file:
`mypackagepath="/root/.conan/data/mypackage/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9"`

This is the environment variable after being set by `/bin/sh ./activate.sh` :
`mypackagepath='"/root/.conan/data/mypackage/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9"'`

Due to this quotation, paths can't be accessed. For example: `cd $mypackagepath` doesn't work.
My temporary solution was to remove all quotes in the  `environment.sh.env`  file before I called `activate.sh`

**Comment by danimtb** [comment]
Hi @armtir,

Could you please add a minimal reproducible example so I can give it a go from my side? We have tests covering this in different platforms but I don't know what could be the issue here. Thank you

**Comment by memsharded** [comment]
I am closing this ticket as staled and outdated, this environment integration was deprecated in Conan 1 and removed in Conan 2. Please create new tickets if necessary for any further question, thanks for your feedback.
