### ISSUE TITLE
[question] conanfile.txt support for from-source builds.

### ISSUE THREAD

**Issue by RubyNova** [conan-io/conan#8560]
Hi, I have a `conanfile.txt` that I am trying to make more cross-platform compatible, but the docs didn't really explicitly say if `conanfile.txt` could enable `build_policy` options like `conanfile.py` can.

To clarify, I am currently doing the following:

```
conan install .. --build=bison --build=missing --profile name-of-profile
```

Ideally, I would like to move both build flags into `conanfile.txt` itself, so something (very roughly) like the following:

```
[requires]
doxygen/1.8.20

[generators]
cmake_find_package
cmake_paths

[build_policy]
build:bison=True
build:missing=True
```

So that the command can simply become the following, but with the same behaviour:

```
conan install .. --profile name-of-profile
```

However, outside of using `conanfile.py` there is no other mention of support for this.

Is there just something I am missing in the documentation, or does `conanfile.txt` simply not support this?

Thanks in advance.

**Comment by jgsogo** [comment]
Hi, @RubyNova 

`conanfile.txt` doesn't support those _arguments_ but neither a **consumer `conanfile.py`**. The [attribute `build_policy`](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=build_policy#build-policy) affects only the recipe where it is declared.

**Comment by memsharded** [comment]
Closing this issue as responded, no further feedback or questions.
