### ISSUE TITLE
Conan info prints a debug line on Windows

### ISSUE THREAD

**Issue by asanka424** [conan-io/conan#8562]
Hi, I am trying use `conan info . -j` in a script so  that I can parse json output. However, in windows it prints this additional line which makes my json parser fail. Could you please look into this?

`conan info .`
`<conans.model.options.Options object at 0x0479DFB0>`

Thanks

**Comment by czoido** [comment]
Hi @asanka424,

Could you please detail which conan version are you using?
Also, can you provide an example of the output you are getting? 

Thanks a lot

**Comment by asanka424** [comment]
Hi @czoido ,

Thanks for the quick response, this is my output

``` conan info .
<conans.model.options.Options object at 0x0479DFB0>
conanfile.txt
    ID: 13a952a8192eab4c195f06c99611ecef9e7f45b0
    BuildID: None
....
....
```

**Comment by czoido** [comment]
Thanks for the info @asanka424,
Can you please provide the conan version as well?

**Comment by asanka424** [comment]
conan -v
Conan version 1.33.1

**Comment by czoido** [comment]
Hi @asanka424,
I have checked the code for 1.33.1 and I did not find any lines that could print that output. I think that what is most likely is that the _conanfile.py_ has a `print(self.options)` anywhere in the code, probably in any of these methods: `config_options`, `configure`, `requirements`, `package_id`, `validate`, `build_requirements` or`build_id`.
Could you please check?

**Comment by asanka424** [comment]
Hi @czoido 

Sorry for the delayed reponse. It turns out to be a debug log from one of the custom conan modudles. You can close this ticket.
Thanks for your support
