### ISSUE TITLE
[bug] Recent conan release breaks gsl-lite package from conan-center

### ISSUE THREAD

**Issue by parkertomatoes** [conan-io/conan#8572]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04 (WSL1 on Windows 10 1809)
  * Compiler+version: gcc 8
  * Conan version: 1.34.0
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
In an empty folder, create a conanfile.txt with the following
```
[requires]
gsl-lite/0.34.0
```
Then run `conan install`. This works fine on Conan 1.30.2. On Conan 1.34.0 it fails with:
>```
>ERROR: .../.conan/data/gsl-lite/0.34.0/_/_/export/conanfile.py: Recipe 'description' must be a string.
>```

Sure enough, the description in the package is a tuple of strings:
```python
    description = ("A single-file header-only version of ISO C++ ",
                   "Guideline Support Library (GSL) for C++98, C++11 and later")
```

This seems to be due to this PR:
https://github.com/conan-io/conan/pull/8143

The restriction seems well justified, but this breaks packages on conan-center, which I depend on and have been using for a long time. Is there a way to either except tuple-of-string descriptions, or roll back the change until the packages on conan-center have a chance to update?

I also filed an issue with Conan Center to work around the issue on their end:
https://github.com/conan-io/conan-center-index/issues/4726

**Comment by memsharded** [comment]
Hi @parkertomatoes 

I have just tried and it is working now, the recipe description is a string now:

```python
 description = "A single-file header-only version of ISO C++ " \
                  "Guideline Support Library (GSL) for C++98, C++11 and later"
```

are you sure you have updated to last changes from ConanCenter?

Btw, this doesn't seem a bug in Conan, see (https://github.com/conan-io/conan/pull/8143#issuecomment-787524810),  but basically, the ``description`` field is a string, as documented in https://docs.conan.io/en/latest/reference/conanfile/attributes.html#description. Any other type is a recipe bug, and can raise or produce any undefined behavior.

**Comment by uilianries** [comment]
I'll provide a hotfix for it. There is an issue there in CCI: https://github.com/conan-io/conan-center-index/issues/4726

**Comment by uilianries** [comment]
Looking again, it seems a problem related to old revision, as memshared commented, or a recipe from another repository (Bincrafters, Conan Community ...)

**Comment by memsharded** [comment]
I guess we can close this one? It seems nothing necessary on Conan code. Please confirm @uilianries @parkertomatoes

**Comment by uilianries** [comment]
@memsharded I can confirm, it's a cache/outdated package problem, not a Conan bug.
