### ISSUE TITLE
[feature] let conan export use 'default_user' and 'default_channel' attributes

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8581]
Would be useful if this command also used the defaults, to avoid having to use multiple `conan inspect` to get them.

**Comment by solvingj** [comment]
I will see if this is possible for 1.35 release.

**Comment by memsharded** [comment]
It is already working fine. Those fields are being used for the ``export`` and ``create`` commands.
It is just the output message that is missing the fields, a small UX bug, but the functionality is fine. Could you please double check, just in case?
