### ISSUE TITLE
[bug] smc field is accessed before requirements are resolved in conan 1.34

### ISSUE THREAD

**Issue by sorekz** [conan-io/conan#8584]
### Environment Details (include every applicable attribute)
  * Operating System+version: any
  * Compiler+version: any
  * Conan version: 1.34.0
  * Python version: any

### Steps to reproduce (Include if Applicable)
Hi,
in some of our older conanfiles we used to calculate the scm property with the help of a build_requires recipe.
```python
class Recipe(ConanFile):
    ...
    _scm = None
    @property
    def scm(self):
        if not self._scm:
            self._scm = ... # import and call python method exported by SCMExtension to get scm the scm info
        return self._scm

    def build_requirements(self):
        self.build_requires("SCMExtension/1.0.0@user/stable")
```
Now this is something conan can do by its own now and is not needed anymore. Or could be done with python_requires.

However with #8377 the scm property is accessed before the build_requirements are resolved. The problem we have is that the mentioned recipe is old but used in many other recipes as requirement. As a result this change breaks all those recipes and they can't be built as this also affects transitive dependencies.

Please let me know what you think about it and if it would be possible to call resolve the requirements beforehand as they are resolved in the conan info anyway (but at a later time).

**Comment by solvingj** [comment]
I do not think so. Since SCM is still an experimental feature, please consider updating the old recipes.

**Comment by memsharded** [comment]
``scm`` was replaced in Conan 1 and removed in Conan 2, the current recommendation is https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html

Closing as solved, please create new tickets if necessary, thanks for the feedback.
