### ISSUE TITLE
[question] Cmake: How to automatically link against a dependency's dependency libraries?

### ISSUE THREAD

**Issue by kakashidinho** [conan-io/conan#8588]
I have a `conan` project `exeA` depends on:
- `conan` project `libB` which is a static library. Project `libB` in turn depends on:
  -  `conan` project `libC` which is another static library.

In project `exeA`'s `CMakeList.txt`, I link `exeA` against `libB`. For example:
```
target_link_libraries(exeA ${CONAN_LIBS_LIBB})
```
However, `libC` is not automatically linked, thus symbols required by `libB` are missing.
Is there any option to enforce `exeA` project to automatically link against `libC`? Perhaps an option used when building `libB` package?

**Comment by memsharded** [comment]
Hi @kakashidinho 

It depends on which Conan generator you are using. I assume you are using the ``cmake`` one. It has 2 modes of operation, the "global" one with ``conan_basic_setup()`` and the modern targets one with ``conan_basic_setup(TARGETS)``.

The first one is defining a CONAN_LIBS variable, if you want to link all transitive dependencies you use:

```cmake
target_link_libraries(exeA ${CONAN_LIBS})
```

If you are using the TARGETS:
```cmake
target_link_libraries(exeA ${CONAN_TARGETS})
```

Please let me know if this helps.

**Comment by kakashidinho** [comment]
Yes, using `target_link_libraries(exeA ${CONAN_LIBS})` work for me. Thanks.
