### ISSUE TITLE
[question] Using conan create and cmake on a subfolder

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#8590]
I have a project where we have the releasable code and test code in a single project/repo but package and distribute the main libraries and the test libraries separately. The test libraries are used by tests in downstream projects. For example:

* projectA/
  * include/
  * src/
  * tests/
    * include/
    * src/
    * conanfile.py
    * CMakeLists.txt
  * conanfile.py
  * CMakeLists.txt
* projectB/
  * include/
  * src/
  * tests/
    * include/
    * src/
    * conanfile.py
    * CMakeLists.txt
  * conanfile.py
  * CMakeLists.txt

In the above setup, you would end up with dependencies such as:
* test_A
  * libTestA
    * libA
* test_B
  * libTestB
    * libTestA
      * libA
    * libB
      * libA

The projectX/CMakeLists.txt does not use projectX/tests/CMakeLists.txt so that the tests build independently of the top-level libraries. To build & run the tests, the top-level libraries have to be built & installed first.

I can use conan create to make the top-level packages (libA and libB), which is nice because it means that --build=missing will work. However, I can't get conan create to work to build libTestA (or libTestB). I can use the conan commands (conan install, conan build, etc) and everything will build so it seems like when I manually run the commands I'm doing something different from what conan create does. Because the files are together in the repo, the source step clones all the files (I'm using the scm attribute), even though I don't need the top-level project files, which I'm okay with... but it looks like conan then builds using the top-level project CMakeLists.txt and not the tests/CMakeLists.txt file. I'm using the CMake build helper in the conanfile to do the build.

I've tried a few different things with no luck:
- os.chdir into the tests folder before I call CMake::configure
  - I change into the directory but it seems like the helper still uses the top-level CMakeLists.txt (as this is self.source_folder)
- Specify the source_folder in the CMake::configure call
  - I get a CMake error "... prefixed in the build directory" presumably cause the conan build_folder is the parent to source_folder
- Specify the source_folder and build_folder in the CMake::configure call
  - conan_paths.cmake is not found (I'm using the cmake_paths generator) since it's sitting at the top-level and the tests/CMakeLists.txt file expects it to in CMAKE_CURRENT_BINARY_DIR.

Any thoughts?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Hi @nichmj01,

Do you want to create packages for the tests as well? If not, maybe using your *tests* folder as *test_package* so they are executed at the end of the `conan create` command (Conan uses *test_pacakge* name by default but you can change it with `conan create projectA --test-folder projectA tests`).

Another approach in case you really need to `conan create` the tests would be to specify the folder in the CMake build helper. Try something like `cmake.configure(source_folder=os.path(self.source_folder, "projectA", "test"))` in the *projectA/test/conanfile.py* and it should work.

**Comment by nichmj01** [comment]
Hey @danimtb,
Sorry for the delay in getting back. Yes, I want to create packages for the test libraries as well. 

I tried using `cmake.configure(source_folder=os.path(self.source_folder, "projectA", "test"))` but then I get an error from my CMakeLists.txt file saying that it couldn't find the conan_paths.cmake file.

I have these lines in my CMakeLists to be able to build without conan (and I'm using the cmake_paths generator)
`include(${CMAKE_CURRENT_BINARY_DIR}/conan_paths.cmake)`

It seems like the conan install step is run in the top-level folder but the cmake step is being run the specified subfolder so all the needed conan generated files can't be found.

**Comment by danimtb** [comment]
yeah, I guess you would need to play a little bit with the paths there. Try `include(${CMAKE_BINARY_DIR}/conan_paths.cmake)` instead and maybe that makes the trick.

**Comment by memsharded** [comment]
I am closing this ticket as outdated, ``conan_paths.cmake`` doesn't exist any more, the ``cmake_paths`` generator was deprecated long time ago.

Please, don't hesitate to re-open or create new tickets if necessary for any further question or issue.
