### ISSUE TITLE
Propose ``cpu_count`` alternative in [conf] for build systems paralelism

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#8598]
For build helpers in ``conan.tools.xxxx``, the parallelism should be configurable via [conf] (and not ``cpu_count``).

Please propose a solution, some guidelines:

- No need that recipes specify it, not explicitly, not as arguments, and they can default back to whatever the build system likes.
- All build systems can share a "parallel" value, no need to do one per build-system/helper
- Might be different to concurrent upload/download

**Comment by jgsogo** [comment]
What about following entries in `conf`:
 * `core.build:processes`: number of processes to use for every build-helper
 * `tools.gnu.make:jobs`: argument for the `--jobs` parameter when running `make` (overrides the general `core.build:processes`).
 * `tools.microsoft.msbuild:maxCpuCount`: argument for the `/m` (`/maxCpuCount`) when running `MSBuild` standalone or via CMake (overrides the general `core.build:processes`).
 * `tools.ninja:jobs`: argument for the `--jobs` parameter when running Ninja generator via CMake or Meson. (overrides the general `core.build:processes`). If no-parallel is requested, this will force `-j1`. 

If none of these configuration options is found, it fallback to the old `cpu_count` when parallelization is activated. Alternatively, we could leave the number blank (`-j`, `/m`,..) and the corresponding build-system will run in parallel with its internal defaults (infinite probably).
