### ISSUE TITLE
[feature] Allow referencing package recipes from git

### ISSUE THREAD

**Issue by Renari** [conan-io/conan#8607]
Using NPM you can specify a git repo as remote which a dependency will be retrieved from.

e.g.
```
npm install git://github.com/someuser/somerepo.git#sometag
```

This will add this git repo as a dependency and when you run `npm install` it will checkout the repo build it and export it to your cache.

I'm proposing similar functionality in conan, this would obviously not support prebuilt versions.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
As this question has been done also in the past, we have added a response in our FAQ in https://github.com/conan-io/docs/pull/2076. It will be in https://docs.conan.io/en/latest/faq.html when CI passes. Thanks!
