### ISSUE TITLE
[feature] Upgrade PyJWT

### ISSUE THREAD

**Issue by mekanix** [conan-io/conan#8609]
I noticed PyJWT is pinned to versions below 2. As PyJWT-2.x has breaking changes, it is not just matter of changing "2" to "3" and call it a day. I was wondering if there are any plans to support PyJWT-2? Naturally, I'd like to help.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by solvingj** [comment]
We have no plans to upgrade PyJWT at this time. If a compelling reason to switch arises we would certainly consider it, but arbitrarily bumping dependencies can have adverse impacts on Conan users who often use Conan in conjunction with a bunch of other python tools and scripts. They might share dependencies and have versions of various packages pinned for various reasons in their environments.

**Comment by mekanix** [comment]
I do understand compatibility issues, but upgrade has to happen once as pyjwt-1.x is not maintained, if I understood right. Anyway, if/when you decide to upgrade PyJWT I would be glad to help.

**Comment by memsharded** [comment]
More data: https://pyjwt.readthedocs.io/en/stable/changelog.html

PyJWT is Py>3.6 only. That would restrict its usage for Conan, at least until Conan 2.0, not possible to upgrade it atm

**Comment by solvingj** [comment]
@memsharded thanks for the additional info.  @mekanix , with that, may we close this?

**Comment by mekanix** [comment]
@solvingj yes, thank you!
