### ISSUE TITLE
Backslash convertion in cmake link flags

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#861]
As reported in https://github.com/conan-io/conan/issues/813 by @SSE4

With the glew package:

```
19>LINK : fatal error LNK1104: cannot open file '\NODEFAULTLIB:LIBCMTD \NODEFAULTLIB:LIBCMT.obj'
```

digging down suggests that it's most likely from glew package which defines:

```
                if self.settings.compiler.runtime != "MT":
                    self.cpp_info.exelinkflags.append('/NODEFAULTLIB:LIBCMTD')
                    self.cpp_info.exelinkflags.append('/NODEFAULTLIB:LIBCMT')
```

and somehow slash got converted into backslash somewhere. inspecting conanbuildinfo.cmake I can see just the following:

```
set(CONAN_EXE_LINKER_FLAGS_GLEW "/NODEFAULTLIB:LIBCMTD /NODEFAULTLIB:LIBCMT")
```

if anyone will encounter the same issue - I've applied workaround to the glew receipt to use dash rather slash, so it is:
```
               if self.settings.compiler.runtime != "MT":
                    self.cpp_info.exelinkflags.append('-NODEFAULTLIB:LIBCMTD')
                    self.cpp_info.exelinkflags.append('-NODEFAULTLIB:LIBCMT')
```

**Comment by memsharded** [comment]
@SSE4 follow up: 

> there is no issue in glew package, as both forms (-NODEFAULTLIB and /NODEFAULTLIB) are valid and accepted by Microsoft linker. I believe there is still an issue that slash converted into backslash somewhere inside Conan or CMake when processing linker flags.
yes, I am using forked version of glew/2.0.0@coding3d/stable.

**Comment by memsharded** [comment]
Hi @SSE4 ,

Please I need your feedback here.

I haven't been able to reproduce this issue with the backslash. I am using conan 0.19.1.
I have tried manually in my own project to add the NODEFAULTLIB flags, with the forward slash. I have also tried building the original glew repo: https://github.com/dimi309/conan-glew.

Everything looks good, the forwardslash are not converted to backslash. Any way or further suggestion to reproduce this issue? Do you have one commit in your repo before changing to the "-NODEFAULTLIB" syntax? Thanks very much

**Comment by SSE4** [comment]
@memsharded hi, yeah, I have changes besides -DNODEFAULTLIB. lemme check with conan 0.19.1 and original glew repo, I will reply afterwards.

**Comment by memsharded** [comment]
Hi @SSE4 ,

Sorry I haven't been able to reproduce this yet. As our current release 0.20 is incredibly packed, we have decided to move this to 0.21. Looking forward your feedback for this issue, thanks!

**Comment by SSE4** [comment]
@memsharded sorry for the delay - I have re-checked the issue, and I can confirm that there is no problem as for conan 0.20 - "/NODEFAULTLIB" flags are properly set.

**Comment by memsharded** [comment]
Ok, great, thanks for telling. Then I am labeling as fixed and closing the issue, please re-open if this happens again.
