### ISSUE TITLE
[bug] linker error when using the fmt library from Conan

### ISSUE THREAD

**Issue by alexisfrjp** [conan-io/conan#8611]
* **Centos 7** and the `devtoolset-8` => works
* **Centos8 Stream + Conan** and gcc8 => doesn't work
* **Centos8 Stream + c++ fmt lib header-only (without Conan)** and gcc8 => works

### Conan 1.34.0
```
[requires]
fmt/7.1.3
```
### Error message:

> /home/alexis/.conan/data/fmt/7.1.3/_/_/package/a2582e1f57e524e15d7e84f4c862d0a472d3216f/include/fmt/core.h:2076:
> undefined reference to
> `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>,
> fmt::v7::format_args)' CMakeFiles/app_network.dir/app_network.cpp.o:
> In function `printMacAddress[abi:cxx11](unsigned long)':
> /home/alexis/.conan/data/fmt/7.1.3/_/_/package/a2582e1f57e524e15d7e84f4c862d0a472d3216f/include/fmt/core.h:2076:
> undefined reference to
> `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>,
> fmt::v7::format_args)'

* Is it a fmt problem?
* Is it a Conan problem?

**Comment by uilianries** [comment]
It's seems be a profile problem. Please, make sure your libcxx is configured correctly.

More info: https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html#manage-gcc-abi 
https://docs.conan.io/en/latest/getting_started.html (Step 5)

**Comment by alexisfrjp** [comment]
It works... I forgot to set up that to my new centos 8.
I don't understand why Conan uses the old ABI version by default... I believe the big majority uses gcc >=5.
Thanks @uilianries !

**Comment by uilianries** [comment]
>  I don't understand why Conan uses the old ABI version by default... 

That's well explained on [Manage GCC ABI](https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html#manage-gcc-abi):

> When Conan creates the default profile the first time it runs, it adjusts the compiler.libcxx setting to libstdc++ for backwards compatibility.

It should be changed on Conan 2.0. `libstdc++11` will become the default one.

**Comment by alexisfrjp** [comment]
Thank you @uilianries !
