### ISSUE TITLE
[question] Is there a way to know if the download_cache is working?

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8624]
After enabling the download_cache I don't see that much of a difference in time taken to populate the cache.  I want to be sure it's working but I don't see anything in the output that would indicate this:

```
conan lock create --reference=app1/0.1@user/channel

app1/0.1@user/channel: Not found in local cache, looking in remotes...
app1/0.1@user/channel: Trying with 'conan-release'...
app1/0.1@user/channel: Trying with 'conan-develop'...
app1/0.1@user/channel: Trying with 'ARTBF-tmp'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz

...
```

It would be useful to get a different message when things are copied from the download_cache rather than downloaded from a remote.

**Comment by danimtb** [comment]
Hi @GordonJess,

The implementation is transparent in the code based on the `download_cache` configuration so currently, there is no output difference possible. I'd suggest you to check the logging information of Conan https://docs.conan.io/en/latest/mastering/logging.html#logging-and-debugging and check for the `DOWNLOAD` events to check it is working.

**Comment by danimtb** [comment]
@GordonJess did that work for you? Can we close the issue?

**Comment by DukeOfKirkcaldy** [comment]
Thanks!  Yes, I can confirm that there are fewer `DOWNLOAD` events when the `download_cache` is enabled,
