### ISSUE TITLE
In place test_package

### ISSUE THREAD

**Issue by mropert** [conan-io/conan#863]
Hello,

Is there a way to make "test_package" run in place? As in using building the conan package from my working sources and then consuming that package in the test package?

Today when I run conan test_package it publishes the conanfile and runs the "source()" step.
It's fine when the package exports the sources too, but when it downloads them from a repo or archive, the test_package will consume a package that has the WIP conanfile.py but the release sources and not the current working sources.

This is a problem if I'm using conan as the main build tool for a library I'm developping since I usually tune on the conanfile in the same commit has the other sources.

**Comment by memsharded** [comment]
Yes, I think you might refer to the  ``--build=missing`` and ``-ne, --not-export`` command line arguments:

The ``-ne, --not-export`` does not execute the initial export of the user conanfile.py recipe into the conan local cache. Then, the test will try to use the recipe as it was there, or retrieve it from the remotes to be able to satisfy the test. I think this could be what you are asking for.

The ``--build=missing`` avoids the default behavior of ``test_package`` that is to build from sources the package which is under testing.

Try:
```bash
$ conan test_package -ne --build=missing
```

**Comment by mropert** [comment]
I'm afraid that's not what I need.
`-ne` does not export the local conanfile.py so that the test_package uses the one available in the store or the remotes (and not the working copy).

In my case, i have a project (says, `libxyz`) with a `test_package` subdirectory.
Working on the test conanfile usually helps me finding bugs in my lib conanfile or directly in the sources.
So if I make a fix locally on the sources of `libxyz`, I want to be able to validate it with the `test_package` command, which I can't since the command builds my lib from the repo.
What I'd like is a toggle to have `test_package` build `libxyz` from the local sources and then use that version of the package for the recipe under `test_package/`.

**Comment by mropert** [comment]
Here's another test case that raises the same issues:
I have a project I maintain, which offers both CMake and Conan build files directly under the repo.
Ideally, I want to validate to pull request to make sure no change breaks the build, either with CMake or Conan.
To do that, I'd try to use `test_package` on the pull request branch to see if everything builds cleanly.
The problem is, my recipe doesn't export the sources with conan, if fetches them from the repo using the `source()` method.
Which means `test_package` will not use my local branch to build my project, but will instead fetch from the master.

The root of the problem is that my conanfile resides in the same repo as the sources but does not export the sources, it downloads them.
That may be a bad practice, but then again I wasn't sure exporting all sources with the recipe would be good practice either.
Would you have some insight on this?

**Comment by memsharded** [comment]
Yes, it is what you explained in your latest comment, there are two ways to get the source code for the packages in a consistent way:

- Doing the ``exports`` of the source code into the package recipe, like doing a "snapshot". This is the recommended way when the package recipe is inside the source code repository. For most case, unless the source code repository is very large, it is not a big performance issue.

- Doing the ``source()`` method for fetching the source code is recommended for external sources, like cloning from git remotes (not local repos) or downloading from an URL

The important thing is that the package build from sources process must be repeatable and deterministic for package consumers too, not only for the developer of the package at development time. And there is no way to have packages that would somewhat use code changes that exist only on your local user space: the source code must be into conan, or into another accessible source (like a git repo or download URL).

Said that, the power of using python for package recipes, surely allows to hack the process and adapt it to your needs. Just a possible idea that comes to my mind:

- Define one environment variable, like MYLOCAL_CONAN_DEV. Make the recipe read it to var ``conan_dev``, default it to ``False`` if not defined
- Conditionally define ``exports``, something like ``exports = "*" if conan_dev else None``
- Conditionally define ``source()`` implementation to do nothing if ``conan_dev`` or fetch from the github repo you will commit and push your changes after you are happy with your local tests


Of course, the other possibility, that I would also consider, is to decouple, and store the package recipe in its own repo. Specially if you have alternate CMake and Conan builds, that could result in a smoother flow.

**Comment by mropert** [comment]
No need to hack the process, the recommendations will do fine!
That may be an interesting point to develop in a FAQ or "best practices" documentation.
In any case, thanks for the tip :)
