### ISSUE TITLE
[bug] A slash '/' in artifacts.properties breaks upload if using V2

### ISSUE THREAD

**Issue by DdOtzen** [conan-io/conan#8631]
### Environment Details (include every applicable attribute)
  * Operating System+version: Microsoft Windows [Version 10.0.18363.778]
  * Compiler+version: N/A
  * Conan version: 1.33.1
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)
I have this very simple conanfile.py
``` python
from conans import ConanFile
from conans import tools
import datetime

class LibConan(ConanFile):

    name = "upload_bug"
    version = '0.0.1'

    def build(self) :
        # this is just to ensure we get new hash for the current build and thus a new revision to upload.
        tools.save('dummy.h', str(datetime.datetime.now() ) )

    def package(self):
        self.copy( 'dummy.h' )

```
I run these commands
``` powershell
conan config set general.revisions_enabled=True
conan create . DeleteMe/Experimental
echo "artifact_property_build.test=/a" >  $HOME\.conan\artifacts.properties
conan remote add jfrog https://Myorg.jfrog.io/..... --insert --force
conan user $emv:JFROG_USER -r jfrog -p $env:JFROG_KEY
conan upload  --confirm "*@DeleteMe/Experimental"
```
I obfuscated the upload URL in the code above

And the upload fail.
If I change `revisions_enabled` I can make the upload work
`conan config set general.revisions_enabled=True` The upload fails
`conan config set general.revisions_enabled=False` The upload works

Or if I change What I put in artifacts.properties i can make upload work
`echo "artifact_property_build.test=/a" >  $HOME\.conan\artifacts.properties` upload fails.
`echo "artifact_property_build.test=a" >  $HOME\.conan\artifacts.properties`, upload works
`echo "artifact_property_build.test=a/" >  $HOME\.conan\artifacts.properties` upload works. 

Conclusion, if enabling revisions, and having a slash (except for a trailing slash) in the artifacts.properties the upload breaks.

### Logs (Executed commands with output) (Include/Attach if Applicable)
+ conan upload  --confirm "*@DeleteMe/Experimental"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (DEBUG :conan_ap...7 23:22:58,012]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

DEBUG :tracer.py      [156]: CONAN_API: upload(pattern=*@DeleteMe/Experimental,package=None,query=None,remote_name=Non
e,all_packages=False,policy=None,confirm=True,retry=None,retry_wait=None,integrity_check=False,parallel_upload=False)
[2021-03-07 23:22:58,025]

Uploading to remote 'jfrog':

Uploading upload_bug/0.0.1@DeleteMe/Experimental to remote 'jfrog'
DEBUG :rest_client_common.py[160]: REST: ping: https://myorg.jfrog.io/myorg/api/conan/conan.local/v1/ping [2021-03
-07 23:22:58,064]

DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions
', 'matrix_params'] [2021-03-07 23:22:58,207]

DEBUG :rest_client_common.py[152]: REST: Check credentials: https://myorg.jfrog.io/myorg/api/conan/conan.local/v2/
users/check_credentials [2021-03-07 23:22:58,254]

DEBUG :rest_client_common.py[188]: REST: get: https://myorg.jfrog.io/myorg/api/conan/conan.local/v2/conans/upload_
bug/0.0.1/DeleteMe/Experimental/revisions/32e79db621623c40f04c76476add6085/files [2021-03-07 23:22:58,384]

DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.NotFoundException'> [2021-03-07 23:22:58,433]

Uploading conanfile.py -> upload_bug/0.0.1@DeleteMe/Experimental
Waiting 5 seconds to retry...
Uploading conanmanifest.txt -> upload_bug/0.0.1@DeleteMe/Experimental
Waiting 5 seconds to retry...
ERROR: 404 Client Error: Not Found for url: https://myorg.jfrog.io/myorg/api/conan/conan.local/v2/conans;build.tes
t=%2Fa/upload_bug/0.0.1/DeleteMe/Experimental/revisions/32e79db621623c40f04c76476add6085/files/conanfile.py
ERROR:
Error uploading file: conanfile.py, '404 Client Error: Not Found for url: https://myorg.jfrog.io/myorg/api/conan/c
onan.local/v2/conans;build.test=%2Fa/upload_bug/0.0.1/DeleteMe/Experimental/revisions/32e79db621623c40f04c76476add6085
/files/conanfile.py'
ERROR: 404 Client Error: Not Found for url: https://myorg.jfrog.io/myorg/api/conan/conan.local/v2/conans;build.tes
t=%2Fa/upload_bug/0.0.1/DeleteMe/Experimental/revisions/32e79db621623c40f04c76476add6085/files/conanmanifest.txt
ERROR:
Error uploading file: conanmanifest.txt, '404 Client Error: Not Found for url: https://myorg.jfrog.io/myorg/api/co
nan/conan.local/v2/conans;build.test=%2Fa/upload_bug/0.0.1/DeleteMe/Experimental/revisions/32e79db621623c40f04c76476ad
d6085/files/conanmanifest.txt'
ERROR: upload_bug/0.0.1@DeleteMe/Experimental: Upload recipe to 'jfrog' failed: Execute upload again to retry upload t
he failed files: conanfile.py, conanmanifest.txt. [Remote: jfrog]

ERROR: Errors uploading some packages

**Comment by memsharded** [comment]
Hi @DdOtzen 

I have been trying to reproduce this, but so far without success:

- We already have a test in our test suite that covers for a slash (using the embedded conan server)
- I have manually tested with a local Artifactory 7.15 instance, both with and without revisions, seems to work fine, property appears in server without problems.

Which server version are you using? Is it possible that you have some proxy, nginx on front of the server that would be causing the issue? If you can try downloading a local Artifactory CE (https://conan.io/downloads.html) to try locally too, that would help to triage the issue

**Comment by DdOtzen** [comment]
Hi.

Thanks for the prompt reply, sorry for my delay.
I found that we had commercial support for jfrog (sadly not impressed), but after a lot of waiting and explaining, they found that the URL is wrong.
As you see in my example i use
`url: https://myorg.jfrog.io/myorg/api/`
They found that if i use
```
url: https://myorg.jfrog.io/artifactory/api/
                            ^^^^^^^^^^
```
The error goes away. 
If log level debug selected, it still writes
`DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.NotFoundException'> `
In the output, but the upload completes, so I assume, this is not a real error but just how conan detects if the package is still there, to avoid a re-uoload.

They did mention something about this was the old config (with double org in url), and should still be supported for backwards compatibility. Haven't got a clear answer to this yet, but if this is the case, you might want that added to your test :-)

So when you have decided if this affect your test, and/or don't need more input from me you are welcome to close the issue.

**Comment by memsharded** [comment]
``artifacts.properties`` has been removed in Conan 2.0, in favor of explicit set of properties with https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/art, closing this issue as outdated, thanks!
