### ISSUE TITLE
[feature] allow for non-string configuration-specific preprocesor definitions on CMakeToolchain

### ISSUE THREAD

**Issue by guiserle** [conan-io/conan#8632]
Currently CMakeToolchain only allows for string literal definitions due to quotes included on [this line of jinja template](https://github.com/conan-io/conan/blob/develop/conan/tools/cmake/base.py#L128).
`add_definitions(-D{{ it }}="{{ value }}")`

This limits the hability to declare integer or other definitions on generate() method. I hope this could be easily workaround by removing the quotes from the jinja template and, instead, adding them on python string variable

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @guiserle 

https://github.com/conan-io/conan/pull/8645 should allow it, a bit more tricky than expected, but I think it makes sense, it is a valid request.

**Comment by guiserle** [comment]
Looks like a valid solution to me. Thanks for taking the request into account
