### ISSUE TITLE
[feature] MSBuildDeps generator: CAExcludePath

### ISSUE THREAD

**Issue by lieser** [conan-io/conan#8633]
In most cases if one wants to run the code analysis included in Visual Studio, one is not interested in findings in external code.

This is possible via the (poorly documented) `CAExcludePath` property, see e.g. https://stackoverflow.com/questions/43755499/suppress-warnings-for-external-headers-in-vs2017-code-analysis.

It would be nice if the `MSBuildDeps` generator could populate the `CAExcludePath` with the include paths of the dependencies.

Depending on how well the `visual_studio`/`visual_studio_multi` generators are still maintained, consider adding it there too.

Note that the few examples usages I found on the internet with a quick search seem to have the property under a `<PropertyGroup Condition="'$(Language)'=='C++'">` group.
A quick test suggest this is not needed, e.g. if I manually modify `conan_boost.props` to
```xml
...
<PropertyGroup>
	<LocalDebuggerEnvironment>PATH=%PATH%;$(ConanboostBinaryDirectories)$(LocalDebuggerEnvironment)</LocalDebuggerEnvironment>
	<DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>
	<CAExcludePath>$(ConanboostIncludeDirectories);$(CAExcludePath)</CAExcludePath>
</PropertyGroup>
...
```
the exclude seems to works fine.

**Comment by memsharded** [comment]
That might be relatively easy to add, but I'd like to understand better a few things:

- What is the risk? Is it possible that adding that breaks for some other users? Older VS versions?
- Is it possible that other users will not want it for other reasons?

We could add it as opt-in via some ``[conf]`` configuration.

**Comment by lieser** [comment]
> What is the risk? Is it possible that adding that breaks for some other users? Older VS versions?

Not an expert in VS, but I would be surprised if it did. At least VS 2019 seems to just ignore unknown properties.

> Is it possible that other users will not want it for other reasons?

I guess there is at least the possibility that some do not want it, e.g. for some internal libraries.
From my understanding the code analysis only works as part of the compilation, so you can not start it directly on a header file. So if a header is never used in a project itself (or a separate a test project), it could be that errors are only detected on the consumer site of a package.

> We could add it as opt-in via some [conf] configuration.

From my understanding this would then be a global option?

Another option which I would prefer over a global setting would be to not add the include directory directly to the `CAExcludePath` property, but instead add it to a separate property, e.g. `ConanIncludeDirectories`.
This would make it easy for a user to opt-in to excluding all external code on a project level by just adding `ConanIncludeDirectories` to the `CAExcludePath` himself.
Currently one would have to do it for each dependency, which depending on the number of dependencies can be sup-optimal.

**Comment by memsharded** [comment]
Thanks for the feedback @lieser 

Based on the discussion, the approach should be:

- Lets leave as-is by default. Code-analysis, same as compiler warnings should always be enabled by default. It is clear that there is no unique absolute default, users using Conan mostly for third-parties will want those excluded, but most users using Conan for their own packages, including header-only, will want them included.
- Users can opt-out in recipes:
  ```python
  def generate(self):
        msbuilddeps = MSBuildDeps(self)
        msbuilddeps.exclude_code_analysis = ["*"]  # we could define a ``True`` meaning "all", just the idea
  ```
- This behavior can also be configured downstream by users, overriding the declared behavior
  ```
  [conf]
  tools.msbuild.msbuilddeps:exclude_code_analysis = False  # or True, or different patterns
  ```
  All the ``[conf]`` behavior can also applied selective to particular packages so ``mypkg:tools.msbuild....`` is also possible.

**Comment by lieser** [comment]
Thanks a lot for adding this this fast.

Did a quick test configuring it using profiles, and seems to works as expected. As we currently do not use the `generate` method in our recipes, I did not yet test setting the `exclude_code_analysis` property in a recipe instead of the profile.

Do I see it correctly that the `[conf]` settings can currently not be directly set via an argument then calling e.g. `conan install`, but instead always have to be in a profile or the global config?

**Comment by memsharded** [comment]
> Do I see it correctly that the [conf] settings can currently not be directly set via an argument then calling e.g. conan install, but instead always have to be in a profile or the global config?

Yes, at the moment, only in files, but it is likely it will be added at some point to the command line. But that should be for exceptional cases, the canonical usage is in files.
