### ISSUE TITLE
[question] Passing package_id mode downstream & custom direct mode

### ISSUE THREAD

**Issue by domfellner** [conan-io/conan#8634]
Hi Conan community,

I need some clarification on the package_id concept in case I deviate from semver_direct_mode

Let's assume we have some **app** package which requires a package **libA**, which in turn requires **libB** which again in turn requires **libC**.

If I don't change anything in the conan configuration or **libA**'s package_id method, _semver_direct_mode_ is applied, so ABI compatibility for all minor versions of **libB** is assumed and **libA**'s package_id does only depend on **libB**'s major version, disregarding **libC**'s version. 

Question 0: Is this correct?

---
Problem 1: 

What if **libB** doesn't follow semver (we have this use case in our company)? If I know that **libB** guarantees ABI compatibility for all patch versions, I could set in **libA**'s conanfile:
```
def package_id(self):
    self.info.requires["libB"].minor_mode() 
```

**libA** needs to get the ABI compatibility information somehow. In my example **libA**'s developer must get this information on some other communication channel to implement the the package_id method. It's quite tedious and error prone to keep track and implement this in **libA**'s conanfile in case there are more requirements. From my understanding it would make perfect sense to define the recommended mode in **libB** somehow and automatically apply it in **libA**, but I'm probably missing something.

Question 1: 
Is there any way **libB** can tell its consumers which mode to use / which versions are guaranteed to be ABI compatible (except for following semver)?

---
Problem 2:

Actually, even after overwriting **libB**'s mode in **libA**'s conanfile (see Problem 1), the mode for transitive requirements of **libB** (i.e. **libC**) will not be overwritten causing **libA**'s package_id to possibly change if **libB** changes its requirements (depending on the default package_id_mode of course), even if this was guaranteed to be ABI compatible (otherwise **libB** would increment its version). And I do not want to set **libC**'s mode in **libA**'s conanfile which doesn't even explicitly require **libC**.

I quite like the behavior of the semver_direct_mode in respect to ignoring sub-requirements and assuming they are handled correctly in their respective conanfiles (breaking ABI compatibility with requirements updates will cause an incremented major version). As our regulatory constraints are quite strict, I want to use _package_revision_mode_ as default mode, but only for direct dependencies. I implemented a package_id method with this behavior, I call it _package_revision_direct_mode_. Actually, I think a direct variant would make sense for all modes. I implemented it in **libA**'s package_id method:
```
def package_id(self):
    for dep in self.info.requires.pkg_names:
        if self.info.requires[dep]._indirect:
            self.info.requires[dep].unrelated_mode()
        else:
            self.info.requires[dep].package_revision_mode()
    # referencing problem 1, I might overwrite specific requirements' modes.
    self.info.requires["libB"].minor_mode()
```

That is not clean as I use a private attribute of the RequirementsInfo object and I cannot set this behavior as default in my conan.conf, so all Conan packages in my company must implement it in their conanfiles. 

Feature proposal:
I thought of handling "direct" as a parameter to each mode (like `package_revision_mode(direct=True)`), but I guess this would conflict with the syntax of the conan.conf and envvar settings at the current state.

Question 2:
Does this make sense or am I completely off track? Our internal packages don't follow semver, so I definitely need to alter the default behavior, but I still want my **app** to use any binary of **libA** which was built with the same minor, but different patch versions of **libB** respectively, without needing to rebuild **libA**.

Sorry for all the text, but I guess ABI compatibility is quite a complicated issue :)
I hope this makes sense to you and you can give me some hints. Thanks in advance!

Regards
Dom

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @domfellner 

I think this is very closely related to this previous discussion: https://github.com/conan-io/docs/issues/3153.
Please have a look, and if it is, copy the above there, and lets track it in the other issue.

As you will see in the comments, the problem with this is that counter examples of why the definition of the mode on the dependency doesn't work, as you know the C/C++ compiling and linkage mode makes it very challenging, and it depends a lot how the consumer is linking that library, and not in the library itself. If a static library is being linked by another static library, semver_mode might be ok, but if it is being linked by an executable, then certainly not ok, and better go at least full_mode or some revision mode.

What might make sense, and something we could consider for Conan 2.0 is the possibility to define some versioning schema for a package. Still, the binary effect would be defined downstream, but how versions are interpreted could be defined by recipes, so the total effect would be the aggregation of both things.

**Comment by domfellner** [comment]
Thanks for your answer and sorry for the delay. After reading conan-io/docs#3153 I found that my post would not add any significant value to the discussion there, so I'll leave it as it is.

@memsharded : What do you think about my proposal of introducing _direct_ variants for all package_id modes? I don't even know if it's a good idea as it treats all transitive upstream packages as ABI compatible which will lead to errors if even a single package does not correctly set its package_id method (or follows the default). On the other hand it seems arbitrary to only offer this variant for the semver_mode and we currently have the use case in our company (even though we push for a migration to semver).

**Comment by memsharded** [comment]
> @memsharded : What do you think about my proposal of introducing direct variants for all package_id modes? I don't even know if it's a good idea as it treats all transitive upstream packages as ABI compatible which will lead to errors if even a single package does not correctly set its package_id method (or follows the default). On the other hand it seems arbitrary to only offer this variant for the semver_mode and we currently have the use case in our company (even though we push for a migration to semver).

We are doing very heavy work on new graph model for Conan 2.0, that includes link-dependency, include-dependency, direct-dependency attributes, etc, which will surely contribute to improve the ``package_id`` computation, and will allow users to define their ``package_id`` with more flexibility, including for example filtering the direct dependencies only and assigning them any custom mode.

We haven't started to explore the downstream propagation yet, but the idea is in the backlog, we will have a look later, it is certainly something that we want to consider.

**Comment by memsharded** [comment]
A lot of things have changed since then. Conan 2 provided a completely new package_id computation, with new modes. See the model in https://docs.conan.io/2/reference/binary_model

It also included the capability of defining the default modes for the consumers in https://docs.conan.io/2/reference/binary_model/custom_compatibility.html#custom-package-id-modes-for-recipe-consumers

Closing as solved, please create new tickets if necessary, thanks for the feedback.
