### ISSUE TITLE
[feature] cmake_find_package support Standard Variable Names

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#8636]
`cmake_find_package` generator should set standard variable names as per https://cmake.org/cmake/help/v3.20/manual/cmake-developer.7.html#standard-variable-names:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @SSE4 

yes, this makes sense, but as we are moving to ``CMakeDeps`` generator as the main one, does it make sense to invest this effort? If we are doing it, I would be extra careful not to break anything, not changing existing vars, only adding new ones.
