### ISSUE TITLE
[bug] msvc tries to build with Unix Makefiles

### ISSUE THREAD

**Issue by ChristophStrehle** [conan-io/conan#8637]
When trying to build a library with CMake and msvc compiler conan selects MinGW generator instead of Visual Studio.

See changes here
https://github.com/conan-io/conan/pull/8201

The generator selection in utils.py get_generator looks correct.
The get_generator method from cmake_flags.py will instead return "Unix Makefiles" for msvc.

### Environment Details (include every applicable attribute)
  * Windows
  * msvc 19.28
  * conan 1.34
  * python 3.9.2

### Steps to reproduce (Include if Applicable)
Try to build a CMake lib (for example zlib) with
compiler=msvc
compiler.version=19.28

conan will try to build with MinGW Makefiles instead of Visual Studio 16 2019.

**Comment by memsharded** [comment]
Hi @ChristophStrehle 

Could you please provide more details and how to reproduce it? The experimental ``msvc`` new compiler is only supported in the new toolchains, like ``CMakeToolchain``, and the new build helper imported from ``from conan.tools.cmake import CMake``, but not the previous one. Main reason for this is stability, but also moving forward towards Conan 2.0.

Could you please try with the new tools from https://docs.conan.io/en/latest/reference/conanfile/tools.html?

**Comment by ChristophStrehle** [comment]
Hi James,
I'm sorry but I missed the point that this is only supported with the new build tools. This is of course only reproducible with _from conans import CMake_. I will try the new build tools as soon as possible. 
Thank you for your help
