### ISSUE TITLE
[feature] Consider using CMake's `include_guard()` in `conan_toolchain.cmake`

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#8639]
Right now at the beginning of `conan_toolchain.cmake` `CMakeToolchain` generates:

```cmake
# Avoid including toolchain file several times (bad if appending to variables like
#   CMAKE_CXX_FLAGS. See https://github.com/android/ndk/issues/323
if(CONAN_TOOLCHAIN_INCLUDED)
  return()
endif()
set(CONAN_TOOLCHAIN_INCLUDED TRUE)
```

When minimum version of CMake (3.10) will not be an issue anymore please consider using: https://cmake.org/cmake/help/latest/command/include_guard.html

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @mpusz,

~~Thanks a lot for the suggestion, we will take this into account for 2.0 when CMake will be the lowest supported version.~~

EDIT: In fact we can add it now as we in CMakeToolchain we are already adding some 3.15 CMake features. I'll mark this for the next release.
