### ISSUE TITLE
Add optional verbose logging for conan install

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#864]
Sometimes conan install --update is taking a long time. We have some big packages, but currently it's difficult to tell where the bottleneck is because conan is not giving us much detail on what's happening. A verbose option would let us know what's happening with more detail to potentially help us fix something on our end, or let you know about inefficient steps in the command.

**Comment by memsharded** [comment]
Definitely a good idea. 
We will be re-thinking the whole conan logging soon, likely for the next release, with more detailed, structured logs. I am proposing (still have to be confirmed) it has approved feature and planned for next release. Though it might be done in two iterations, we'll see.

**Comment by lasote** [comment]
Also review if is printed enough information in the output

**Comment by lasote** [comment]
Hi all! We are releasing with 0.19 a feature that will log every api call, very conan command etc to a log file (optional). I've tried to reproduce the big delays with `conan install --update` but it's working pretty fast for me, so I think that the best way to do it is if you can activate the logs setting the CONAN_TRACE_FILE environment variable pointing to a log file:

`export CONAN_TRACE_FILE=/path/to/conan_log.txt` # Linux, OSX
`SET CONAN_TRACE_FILE="c:\path\to\file.txt"` # Windows

Would be great if anybody could send the traces to analyze the bottleneck. 
The log feature is already merged in develop branch in case anybody wants to try before the 0.19 release.

Thanks!

**Comment by memsharded** [comment]
Logging has been improved, both as traces for conan: http://docs.conan.io/en/latest/howtos/logging_and_debugging.html
and for logging and packaging the build process: http://docs.conan.io/en/latest/howtos/logging_and_debugging.html#how-to-log-the-build-process

**Comment by koliyo** [comment]
There is also `CONAN_LOGGING_LEVEL`, and some other settings I noticed in `~/.conan/conan.conf`

**Comment by alexanderLinear** [comment]
> Logging has been improved, both as traces for conan: http://docs.conan.io/en/latest/howtos/logging_and_debugging.html
> and for logging and packaging the build process: http://docs.conan.io/en/latest/howtos/logging_and_debugging.html#how-to-log-the-build-process

the document linked above is gone.
but it might have been moved to this location:
https://docs.conan.io/en/latest/mastering/logging.html
