### ISSUE TITLE
[question] "build_requires" tools from the same package but from different build configuration (settings)?

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#8640]
Hi,

the scenario is the following:

The module (.git repository) can be built for different targets (linux, windows, android, iOS, ...). To cross-compile for e.g. android/iOS certain tools are needed from the host build of the same module. So without Conan one builds and installs the module (cmake) first e.g. for Linux and then for android/iOS using the tools from the host-only build.

I tried to search through [cross-building](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#cross-building) and [build-requirements](https://docs.conan.io/en/latest/devtools/build_requires.html#build-requirements) but didn't find any direct answer so far?

So is it possible to "build_require" the same package but from different settings i.e. from different target build configuration?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @unzap ! Have you read about the two-profiles approach? You can specify two profiles in the command line like `conan install/create <reference> --profile:host=<profile> --profile:build=<build>` and Conan will split the packages in the graph into different context: 
 * _Host_ context will use `profile:host` and it will contain `<reference>` and all its requirements and transitive requirements.
 * _Build_ context will use `profile:build` and it will contain the build-requirements of the packages in the _host_ context.

And yes, you require and build-require the same package and it will appear twice in the graph, one for the _host_ context and another one for the _build_ context.

**Comment by iiknd** [comment]
> Build context will use profile:build and it will contain the build-requirements of the packages **in the host context**.

ok, this was the "trick" I was looking after. Thanks, I will give it a try :)

**Comment by memsharded** [comment]
Closing this ticket as resolved back then.
