### ISSUE TITLE
[bug] 'python_requires' not working when the required packages version was updated

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#8642]
### Environment Details
  * Operating System+version: any
  * Compiler+version: any
  * Conan version: 1.33.1
  * Python version: 3.8+

### Steps to reproduce

The package `TestB` requires some Python  functions from `TestA`, so I add the last one to `python_requires`:

```py
from conans import ConanFile


class TestB(ConanFile):
    python_requires = "TestA/[>=1.0.0]@test/develop"
    name = "TestB"
    version = "1.0.0"
    description = "TestB"
    exports = "*.a"

    def package(self):
        super().package()

        self.copy("*", src=".", dst="lib")

    def package_info(self):
        super().package_info()

        self.cpp_info.libs = ["lib4", "lib3", "lib1"]
```

Then I updated `TestA` (added another function), and `TestA/1.1.0` is backward compatible.

Then I deleted `TestA/1.0.0` from local cache.

Then I tried to install `TestB`.

### Logs

```
conan install .

Version ranges solved
    Version range '>=1.0.0' required by 'py_require' resolved to 'TestA/1.1.0@test/develop' in local cache

conanfile.txt: Installing package
Requirements
    TestB/1.0.0@test/develop from local cache - Cache
Python requires
    TestA/1.1.0@test/develop
Packages
    TestB/1.0.0@test/develop:c9bdb974348d36ea45c47e0861872b0df6b949b1 - Missing

Installing (downloading, building) binaries...
ERROR: Missing binary: TestB/1.0.0@test/develop:c9bdb974348d36ea45c47e0861872b0df6b949b1

TestB/1.0.0@test/develop: WARN: Can't find a 'TestB/1.0.0@test/develop' package for the specified settings, options and dependencies:
- Settings:
- Options:
- Dependencies:
- Requirements:
- Package ID: c9bdb974348d36ea45c47e0861872b0df6b949b1

ERROR: Missing prebuilt package for 'TestB/1.0.0@test/develop'
Try to build from sources with '--build=TestB'
Use 'conan search <reference> --table table.html'
Or read 'http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

### Expected

`TestB` is installed.

### Attachments

[conan_bad_requires.zip](https://github.com/conan-io/conan/files/6134397/conan_bad_requires.zip) - recipes and script to reproduce the issue.

**Comment by memsharded** [comment]
Hi @DmitrySokolov 

This is not a bug, this is designed this way, please have a look at: https://docs.conan.io/en/latest/extending/python_requires.html#packageid

The key is that changing a ``python_requires`` can wildly change the final binary being produced. The new ``python_requires``, introduce ``python_requires_id_mode`` that can be used to control it. By default, it will produce new binaries when the minor or major version changes, but not when the patch version changes, but you can change that both per-recipe or globally in configuration.

**Comment by DmitrySokolov** [comment]
Thank! It's clear now.
