### ISSUE TITLE
[question] Is it possible to use conan with multiple build systems (cmake, gn, Bazel, etc.)

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan#8644]
* I've read the [CONTRIBUTING ](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md) guide.

**I need (as many others) dependency manager that is not tied to a particular C++ build system. Please provide any information about how to use conan with multiple build systems.** 

Can conan be used in scenario below?

* (main project) project A uses CMake
* (dependency) project B uses gn 
* (dependency) project C uses Bazel
* project A depends on project B and project C

CMake can see public definitions (`target_compile_definitions`) and public include directories (`target_include_directories`) created by other CMake dependencies.

Is it possible to use **public definitions and include directories** created by gn/Bazel/etc. project in CMake project?

Maybe conan can be used to store build information parsed from `compile_commands.json`  and generate files per each build system (files with variables that store compile definitions and include directories)?

related to
https://github.com/conan-io/conan/issues/6235#issuecomment-664956687
https://github.com/conan-io/conan/issues/6235#issuecomment-718165124

**Comment by memsharded** [comment]
Hi @blockspacer 

Yes, definitely. Conan is not tied to any build system, you can see it supports many: https://docs.conan.io/en/latest/integrations/build_system.html

The greatest part is that every package can have its own build system, consume dependencies that are using other build systems and be used by others with different build systems. It basically works as follows:

- each package defines in its ``package_info()`` method what it contains. Library names, flags, includedirs, etc.
- There are ``generators`` that can be used to consume packages, if you use the ``cmake`` generator, Conan will generate for you a single ``conanbuildinfo.cmake`` with all the information, if you use ``cmake_find_package_multi`` it will generate ``xxxx-config.cmake`` scripts, one per dependency, if you use ``MSBuildDeps``, it will generate properties .props files to be used by Visual Studio.
- The system is extensible, you can create your own custom generators, check https://docs.conan.io/en/latest/howtos/custom_generators.html for example or https://blog.conan.io/2019/07/24/C++-build-systems-new-integrations-in-Conan-package-manager.html

At the moment there is no Bazel generator, we are aware of some users using Conan for Bazel, but it was not contributed back to open source. If anyone is interested in contributed, we would certainly help in the process

**Comment by memsharded** [comment]
Another good resource is ConanCenter https://conan.io/center (recipes in https://github.com/conan-io/conan-center-index), it contains hundreds of packages, using different build systems.

Please let me know if the above helps, or you have any further questions.
