### ISSUE TITLE
[question] Clearification of the "build/package" autopackaging magic with cmake

### ISSUE THREAD

**Issue by jegabe** [conan-io/conan#8647]
Dear conan experts,

In my company, we're using conan and cmake together. We use cmake also as the packaging tool, as shown in https://docs.conan.io/en/latest/howtos/cmake_install.html#reuse-cmake-install.

This means that the self.copy() step is not needed but the whole content of "[buildfolder]/package" is packaged by conan by some magic.

I just discovered that magic. In my conanfile.py, I had the statement:

        self.copy("**/*", src="package", keep_path=True, symlinks=True)

but that seems to be completely unnecessary.

Could you explain that magic? I wanted to exclude a sub-folder of "[buildfolder]/package" using self.copy() with "excludes" parameter but this doesn't seem to work because conan seems to copy the whole content anyways.

Not that this is a bug, just for clearification (and maybe for putting this into the documentation of the package(self) method"...

**Comment by aleksa2808** [comment]
Hi! Not a Conan dev myself, but I think the only magic that is happening here is that the `CMake` build helper described in the page you linked is setting the `CMAKE_INSTALL_PREFIX` variable to point to the final package output folder (`self.package_folder` from within the recipe). You can see that, along with some other variables that this build helper is setting in the reference [here](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#definitions). What actually ends up in this package folder is probably defined in your CMake files using the [install](https://cmake.org/cmake/help/latest/command/install.html) directives.

If you still need to modify the contents of the package folder after the CMake installation step, you can do that as well with either python or conan-specific utilities. This is often utilized in conan-center-index in situations where packages install unwanted files like documentation, multiple types of the same library (shared + static) etc. You can see an example of that [here](https://github.com/conan-io/conan-center-index/blob/master/recipes/prometheus-cpp/all/conanfile.py#L85).

**Comment by solvingj** [comment]
@aleksa2808 is correct.  It seems likely that the `install()` method of the `CMake` helper class is being called in your recipe.  Would need to see more of the recipe to confirm. 

As @aleksa2808 said, this helper function is designed to leverage the `install` targets that many `CMake` projects already have defined, to copy files from Conan's `build` directory to Conan's `package` directory (so users don't have to re-define the same instructions as `self.copy()` calls in the `package()` method of the recipe).  Conan does this by implicitly setting the `CMAKE_INSTALL_PREFIX` to point to Conan's `package` directory while running `cmake install`.  

> Not that this is a bug, just for clearification (and maybe for putting this into the documentation of the package(self) method"...

As you can now see, there's no implicit copy with the `package()` method. Something in the recipe is doing the copy for you.
