### ISSUE TITLE
[question] how to enforce fPIC transitively

### ISSUE THREAD

**Issue by blackencino** [conan-io/conan#8654]
Hi! 

I'd like to make sure all of my dependencies have -fPIC enabled, on the os's where that's available. I can't just set the *:fPIC option to true, because not all of the dependencies have an fPIC option.

I know that there are fixes underway for how fPIC is propagated: #8185, but in the interim, I think it would be something like this:

```python
def requirements(self):
    for dep in dependencies:
        if dep has option fPIC:
            set dep fPIC option to True
```

Obviously that's mostly pseudocode, but if someone has an example like this, it would be very helpful

- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by blackencino** [comment]
Ideally, it would be helpful to do this to the full tree of dependencies, not just the ones my project explicitly lists.

**Comment by memsharded** [comment]
Hi @blackencino 

Quick question, what is the issue with ``*:fPIC``? It works, as it only applies the option value to those packages that declare it, but it will not fail for packages not declaring the fPIC option.

**Comment by blackencino** [comment]
Hi! What's the syntax for doing this in a conanfile.py, vs a conanfile.txt? Is this correct? 

```python
class USDConan(ConanFile):
   # ...
    options = {
        # ...
        "*:fPIC": True
        }
```

**Comment by blackencino** [comment]
I was able to use this, not sure if this is the recommended way, but seems to do the trick: 

```python
class USDConan(ConanFile):
    # ...
    default_options = {
        # etc ... ,
        "*:fPIC": True
    }
    # etc ...
```

Is this correct?

**Comment by memsharded** [comment]
Yes, ``default_options = {"*:fPIC": True}`` should work, indeed, setting fPIC in your dependencies that declare it.

**Comment by blackencino** [comment]
that's awesome, thank you for the rapid response.

**Comment by AbrilRBS** [comment]
Closing as solved, thanks!
