### ISSUE TITLE
[question] export() method copies files to source_folder?

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#8658]
I have a patch file that I want to apply to some source files that I pull down from a git repo. I don't control the source in the repo so for now I have to apply my patch myself. I don't want to package the patched source with my recipe due to space concerns, especially since the patch is a minor change.

In the conanfile.py, in the source() method I clone the repo and then apply the patch using tools.patch(). After messing around a bit how to get the path to the patch file I ended up getting it to work by referencing the recipe_folder.
```
patch_path = os.path.join(self.recipe_folder, "fixes.patch")
tools.patch(patch_file=patch_path)
```

I then ran into the problem of needing to package the patch file when the recipe is exported to the cache/uploaded.

Reading the document I thought the exports() method would be the solution and indeed it does cause the patch file to be in the export folder in the cache, next to the conanfile.py. However, it looks like export() is also copying the patch file to the source folder when I run `conan create`, even though the documentation seems to say that shouldn't happen?

When I use `conan source -sf test-src .` to test retrieving the sources from the repo the export() method is called. So this looks like the intended behavior?

This causes my clone to fail as git complains that the folder is not empty. I believe I could clone the source into a subfolder to address the not empty folder, but figured I would ask if this is the expected behavior for the export() method and if there is another option other than than doing the subfolder. 

I'm a little hesitant to clone into a subfolder and that seems like it could open up the need to ensure I'm running the cmake configure, build, and install steps on the subfolder instead of on the top-level source_folder.

I'm using version 1.34.1 and saw the same behavior in 1.33.0.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Hi @nichmj01,

I think you might be looking for the `exports_sources` attribute instead as those are files related to the sources. As a general recommendation, patches are applied in the `build()` method. That way the original sources are left untouched and you can apply patches conditionally to the configuration you need (sometimes you only need to patch a windows build). This is general rule we apply to all the conan-center-index recipes for example.

Please give it a go and let me know if that works for you.

**Comment by nichmj01** [comment]
Hi @danimtb,

exports_sources seems to behave the same way as export()/exports in terms of copying the patch file to the source folder? The way I'm understanding the documentation, I believe exports and exports_sources works differently? Am I misunderstanding how these two attributes work?

My interpretation:

exports:
Copy the listed files to be side-by-side with the conanfile.py file in the cache (in the export folder) so that they can be referenced/used by the conanfile.py. These files will not (?) be automatically copied to the source folder. An example may be python script or executable that needs to run as part of the recipe.

exports_sources:
Copy the listed files to the cache (in the export_source) folder so that they can put along side the final source in the source folder. These files shouldn't be referenced/used by the conanfil.py file. These files will be automatically copied to the source folder. For example the actual source files if they are not being pulled from a repo, or a special CMakeLists.txt file.

Where am I going wrong?

From the documentation of exports_sources, it seems like this shouldn't be the right place for the patch file as I'm applying the patch in the conanfile.py (regardless of if I apply the patch in the source step or the build step)?


I guess my main question is around: Am I understanding how these 2 attributes differ?
If I'm not, then maybe the documentation can be improved?
If I am, then is this potentially a bug with the exports attribute?

**Comment by danimtb** [comment]
Files in `export` are uploaded alongside the recipe and should be used to complement the information of the recipe, a good example of this is the *conandata.yml* file.

The files in `exports_sources` are considered just "sources" to build the library and packaged separately from the recipe itself, a good example of this are patches.

**Comment by nichmj01** [comment]
My needs have changed, so this question is no longer relevant to me.
