### ISSUE TITLE
[feature] Only do compression if needed during `conan upload --all`

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#8659]
I am not a 100% sure but I think compression happens regardless of whether the package upstream is up-to-date or not (when running `conan upload --all`). Can we first do the check, and if package is not up-to-date only then try to compress and upload?

- [✓] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Yes, the compression is always run regardless of the existence of the package in the server. I am not sure it is possible to do this as the packages are stored as .tgz and the check is done over that file (and other ones) to see if the md5 matches...

If it is feasible, it could be a nice addition but we will need to check it

**Comment by danimtb** [comment]
yes, as commented above it is not possible because the comparison is done taking into account the md5 of the compressed package, so there is no way to check for an already uploaded package in advance. I am closing the issue, thank you!

**Comment by daravi** [comment]
@danimtb Final question on this. Would it not be possible to change the md5 logic for version 2.0 so that the sha is calculated from the package directory instead of from the archive?

**Comment by memsharded** [comment]
Servers file de-duplication work on the uploaded files. Passing the sha of the package contents instead of the actual .tgz will not work.

In any case, Conan 2.0 will be "always revisions", so that will take into account the revisions to avoid transfers, and that does not require the compression step.

**Comment by daravi** [comment]
@memsharded sounds good thank you
