### ISSUE TITLE
[bug] 'conan download' fails when recipe has a py_requires

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8663]
I want to download a recipe only (without caring about configuration settings or dependencies).  But after download, conan fails because a `py_require` is not in the local cache.

Any workaround would also be appreciated.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 (64-bit)
  * Compiler+version: n/a
  * Conan version: 1.34.1
  * Python version: 1.37

### Steps to reproduce (Include if Applicable)
`conan download libb/0.1@user/channel#rrev-r conan-tmp --recipe`

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
Downloading conanmanifest.txt

Downloading conanfile.py

Downloading conan_export.tgz

ERROR: Error loading conanfile at 'C:\Jenkins\job\workspace\.conan\data\libb\0.1\user\channel\export\conanfile.py': Version range '~1' from requirement 'my_py_requires/[~1]@user/channel' required by 'py_require' could not be resolved in local cache

script returned exit code 1
```

**Comment by jgsogo** [comment]
I think this is a bug (a missing feature of the new python-requires implementation). I cannot imagine any workaround, the python-requires can be providing functionality that is absolutely needed to load the `conanfile.py` of your reference, so the py_req has to be downloaded and available in the Conan cache...

**Comment by AbrilRBS** [comment]
Closing as solved as this is no longer the case with Conan 2 - Although the downloaded recipe would still be broken, the download finishes ok. I've proposed https://github.com/conan-io/conan/pull/16125 to show how to handle situations like this should anyone stumble upon this issue in the future :)
