### ISSUE TITLE
[question] Can revision numbers be updated with "normal" increments?

### ISSUE THREAD

**Issue by dragondive** [conan-io/conan#8667]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I'm now trying to understand the [package revisions](https://docs.conan.io/en/latest/versioning/revisions.html) feature (mainly to teach colleagues -- and myself -- how/when to use it). 

After following the above-linked document and the [exercises on JFrog Academy](https://academy.jfrog.com/path/conan/conan-advanced/598124), I got it working quite easily. As the document says, these revision numbers are either a hash value or picked from the scm. These hexadecimal numbers are unreadable, and specifically, the order of these revisions (which revision is the latest or oldest, etc.) is not clear. 

Is it possible to increment these revision numbers in a "normal" way (0 -> 1 -> 2, etc.) or through some other "user-defined" rule ("a1.1", "a1.2", "b1.0", "b1.1")? [Perhaps I don't understand this concept properly yet, that is, these revision numbers are not meant to be read by humans, but only by continuous integration?]

**Comment by jgsogo** [comment]
Hi, @dragondive 

Revisions are not intended to be human-readable. The order of revisions is assigned by the server the first time they are known by it (the server acts as a centralized authority) and it will assign a timestamp to them. If you have different revisions for the same reference in your remote, you can check their order using

```
conan search <ref> -r <remote> --revisions
```

```
⇒  conan search zlib/1.2.11@ -r conan-center --revisions
Revisions for 'zlib/1.2.11' at remote 'conan-center':
514b772abf9c36ad9be48b84cfc6fdc2 (2021-02-19 14:33:39 UTC)
25dad5342ca50f8d7b9e30f669c7ad37 (2021-02-03 14:33:29 UTC)
1a67b713610ae745694aa4df1725451d (2020-11-19 20:33:54 UTC)
1579680eade7cc27626667ca4b143529 (2020-09-04 14:02:33 UTC)
c39ae6b4e9f752e46539badf1317ec06 (2020-08-20 15:19:39 UTC)
aced1fdf3a0872e757163d023ff0c612 (2020-08-19 17:44:09 UTC)
0df31fd24179543f5720ec7beb2a88d7 (2020-07-31 10:33:08 UTC)
be59e4b426fc4b137e10bf481ef8dc17 (2020-07-02 16:42:05 UTC)
9e0c292b60ce77402bd9be60dd68266f (2020-06-09 17:04:51 UTC)
e69eb26137def0a77953bb0afe1bcb54 (2020-05-18 13:55:58 UTC)
e0df2b44162c49e6d43f59db38e18253 (2020-05-05 16:22:24 UTC)
f3b17fb16cd1b7fbc969400a2ba1bc08 (2020-04-16 10:21:36 UTC)
ddccdddea098293f5202c5e8eb29967b (2020-03-13 17:07:40 UTC)
419994c54789da229ef991be6c2563b3 (2020-01-08 09:12:09 UTC)
0c5984f24444d0e6538433d51fd6b15c (2019-12-26 12:05:56 UTC)
1cd4a227e1b846f961bf91fcb6f3980f (2019-12-19 09:00:49 UTC)
822edf85d3c647748f9e5df4153f3d44 (2019-10-24 12:12:03 UTC)
c9e88c4e6af218eddd574a31b7a200ac (2019-10-24 11:10:58 UTC)
5f4917ce0a630b102f472afd00102d40 (2019-10-10 08:28:51 UTC)
bf8cd01f8b018a3c0871562ae5251bff (2019-09-10 07:54:59 UTC)
c42d82150723a4bb1baca4757fb939ed (2019-08-30 13:32:07 UTC)
``` 

As you said, you can use either the `hash` or the `scm` commit, but, exactly like Git, the commit hash is not intended to be human-readable.

**Comment by dragondive** [comment]
@jgsogo Thanks for this explanation.

[Sorry for the delay in closing the issue. I had been away from this topic for a few months due to personal reasons.]
