### ISSUE TITLE
[question] Creating a lockfile for a test package

### ISSUE THREAD

**Issue by spoofedex** [conan-io/conan#8669]
Hi all,

When building binary packages, we upload them to a private Artifactory server. To do so, we use lockfiles, fetch the build-order, and build/upload each package that requires building.

We have some packages where the test package has some requirements additional to the tested package. When using "conan test" we could pass "--build missing", but then we can't (easily) upload the packages that were built. So we'd like to use lockfiles with test packages as well, which seems to be supported by "conan test", according to its documentation (it has an input and output lockfile).

It seems that we can't just specify an output lockfile for the test package: we need an initial input lockfile. This raises the question: how do we create that lockfile? For regular packages we use "conan lock create", but using this for test packages the lockfile lacks the tested package (as its dependency on the tested package is implicit), which causes errors because the tested package isn't part of the lockfile.

Is there some way to create this lockfile for the test package?

Thanks in advance!

Best regards,
SpoofedEx

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by fanselm** [comment]
We're having same problem now.

We create a lockfile from our main products `conanfile.txt` and then we want to pass this to `conan test`, but if the test package's `conanfile.py` specifies build_requires that aren't used in the main product then it fails with `<REF> ID <ID> not in lockfile`. It would be nice if the build_requirements of the test package were simply ignored when conan test resolved dependencies from the lockfile.

**Comment by memsharded** [comment]
Hi all,

This has been solved in Conan 2.0, which much simplified and powerful lockfiles:

- test_package will not fail if it doesn't find things in the lockfile (non-strict mode)
- Things can be manually added to the lockfiles
- Lockfiles can be merged


Please have a look at https://docs.conan.io/en/2.0/tutorial/consuming_packages/intro_to_versioning.html#lockfiles, and https://github.com/conan-io/tribe/pull/34, testing and feedback very welcome!

**Comment by fanselm** [comment]
That sounds great. We'll make a temporary workaround and add it to the list of things we need to improve when we change to Conan 2.0

**Comment by memsharded** [comment]
We have added explicit tests for this in 2.0: https://github.com/conan-io/conan/blob/f82624b41c41c1f06a47a35cf2a26f82ae337e2f/conans/test/integration/lockfile/test_lock_requires.py#L363, to cover the different potential flows:

Approach 1
--------------
Incrementally capture the main lock and the test_package lock
```
$ conan lock create .  #  the main grpah only
# now append the test_package
$ conan lock create test_package  --lockfile=conan.lock --lockfile-out=conan.lock
```
Approach 2
--------------
Apply lockfile partial without locking test_package
```
$ conan lock create .  # the main graph only
# this wont fail, even if the test_package has other, not locked requirements
$ create . --lockfile=conan.lock --lockfile-partial
```
If want to strictly enforce lockfile in the main graph:
```
$ conan create . --lockfile=conan.lock -tf="" # do not test_package
$ conan test test_package app/1.0 --lockfile=conan.lock --lockfile-partial
```

Approach 3
-------------
Directly locking requires and test_package requires in a single ``create``:
```
# generates test_package requirements too
$ conan create . --lockfile-out=conan.lock
```

I think we can close this ticket as solve in 2.0, thanks!
