### ISSUE TITLE
Generate a debug and release package without discarding any of them

### ISSUE THREAD

**Issue by jlemein** [conan-io/conan#8672]
In my build pipeline I generate packages for debug and release build types after which I want to upload the debug and release packages to the remote server. I tried the following shell script:

    conan install . --install-folder=build_debug -s build_type=Debug
    conan build . --source-folder=. --build-folder=build_debug
    conan package . --source-folder=. --build-folder=build_debug
    conan export-pkg . @mycompany/dev --build-folder=build_debug -s build_type=Debug
    
    conan install . --install-folder=build_release -s build_type=Release
    conan build . --source-folder=. --build-folder=build_release
    conan package . --source-folder=. --build-folder=build_release
    conan export-pkg . @mycompany/dev --build-folder=build_release -s build_type=Release
    
    # next pipeline stage
    conan upload mypackagename/* --all -c -r my_remote

Both packages (Debug and Release) will result in different package hashes as expected. The problem that I have is that export-pkg is deleting my previously generated package in the cache. When I run conan upload, I am not able to upload a debug version and release version to the remote server.

I tried to run `conan upload` after the debug package is generated, and do the same thing after the release package is generated. This also does not work: when running `conan install` for packages that depend on `mypackagename/*` only a debug or release version is found. 

I am a bit confused on how to approach the situation when I want to upload different package versions for debug and release builds. What would be an appropriate way to solve this?

**Comment by memsharded** [comment]
Hi @jeffrey89 

Can you please share your ``conanfile.py``, or part of it? Is it possible that you are not using the ``settings = .... "build_type"``?

It would be good to do ``conan search mypackagename/version@mycomany/dev`` after the last ``export-pkg`` to verify what binaries you have there, can you paste that output?

One note regarding the usage of channels. Please take into account that the ``conan copy`` command or any kind of promotion using channels is not recommended at all anymore. Let me know if you have questions about this. Thanks!

**Comment by jlemein** [comment]
Thanks for your quick reply.

I will take a look into a better approach with channels. The idea behind it is that we have several stages (pull request, development, release branch and master) that ideally would be tagged in a different way so that we can easily fetch the binaries for that stage. I have to consider another approach then. Not sure how to do that now.

The result of conan search is as follows. The end result is that only the release package is left over:

```
$ conan search sensorplugininterface/ABC-167@mycompany/dev
Existing packages for recipe sensorplugininterface/ABC-167@mycompany/dev:

    Package_ID: 66c5327ebdcecae0a01a863939964495fa019a06
        [options]
            fPIC: True
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++11
            compiler.version: 7
            os: Linux
        Outdated from recipe: False
```
My conan version is 1.33.0 and I am running on ubuntu 18.
The conanfile is as follows:

```
from conans import ConanFile, CMake, tools
import re
import os

class SensorplugininterfaceConan(ConanFile):
    name = "sensorplugininterface"
    _version = "0.1.0.0"
    license = "<Put the package license here>"
    author = "<author and author email>"
    url = "<url to repo>"
    description = "description."
    topics = ("sensor", "plugin", "interface")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False],
               "fPIC": [True, False]
    }
    default_options = {
          "gtest:shared": True,
          "shared": False,
          "fPIC": True
    }
    generators = "cmake"
    exports_sources = "*"

    def set_version(self):
        git = tools.Git(folder=".")
        branch = git.get_branch()

        # when running as part of pull request in jenkins
        if (branch.startswith("PR-")):
            branch = os.getenv('CHANGE_BRANCH')

        if branch.startswith(("feature/", "task/", "PR", "bugfix")):
            trimmedBranch = re.sub(r'^.*?/', '', branch)
            issueName = re.match(r'^[a-zA-Z]+-\d+', trimmedBranch)[0]
            self.version = issueName
        else:
            self.version = self._version

    def build(self):
        cmake = CMake(self)
        cmake.definitions["BUILD_TESTING"] = self.settings.build_type == "Debug"
        cmake.definitions["CMAKE_BUILD_TYPE"] = self.settings.build_type
        cmake.configure()
        cmake.build()

    def package(self):
        self.copy("*.h", dst="include", src="src/v0/export")
        self.copy("*.hpp", dst="include", src="src/v0/export")
        self.copy("*.h", dst="include", src="src/base/export")
        self.copy("*.hpp", dst="include", src="src/base/export")
        self.copy("*SensorModelInterfaceV0Lib.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*SensorModelInterfaceV0Lib.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["SensorModelInterfaceV0Lib"]

        # probably not needed, but if it is needed, enable this line
        if self.settings.os == "Windows":
            self.cpp_info.sharedlinkflags = ["-WHOLEARCHIVE:SensorModelInterfaceV0Lib"]
        else:
            if (self.settings.build_type == "Debug"):
                self.cpp_info.libs.append("gcov")

    def imports(self):
        self.copy("*.dll", src="bin", dst="conanlibs", keep_path=False) # copies all dll files from external packages to bin output folder
        self.copy("*.so*", src="lib", dst="conanlibs") # copies all so files from external packages to bin output folder

    def build_requirements(self):
        if (self.settings.build_type == "Debug"):
             self.build_requires("gtest/1.10.0")
```

**Comment by memsharded** [comment]
> I will take a look into a better approach with channels. The idea behind it is that we have several stages (pull request, development, release branch and master) that ideally would be tagged in a different way so that we can easily fetch the binaries for that stage. I have to consider another approach then. Not sure how to do that now.

There is a known best practice in "devops" that is package immutability, and the recommended way to achieve flows is using different binary repos to represent different stages (develop, staging, production) and using binary promotions, copying packages from one repo to another.

It is not clear to me what could be happening, so a couple of things more that could help:
- What is the output of the ``conan export-pkg . @mycompany/dev --build-folder=build_debug -s build_type=Debug`` commands? The two different ones?
- What happens if you do a ``conan create . -s build_type=Debug`` and ``conan create . -s build_type=Release``? Do you still get only one package?

Thanks for the feedback!

**Comment by jlemein** [comment]
> What is the output of the conan export-pkg . @mycompany/dev --build-folder=build_debug -s build_type=Debug commands? The two different ones?

I attached the output of the two commands. The result is two different package hashes.

> What happens if you do a conan create . -s build_type=Debug and conan create . -s build_type=Release? Do you still get only one package?

I do get two packages. It creates them in sensorplugininterface/ABC-167/_/_/build with the hashes: 1a651c5b4129ad794b88522bece2281a7453aee4 (debug) and 66c5327ebdcecae0a01a863939964495fa019a06 (release). These are the same hashes as retrieved by running `conan export-pkg` in the attached log files.

I do observed the following behavior:

When I run `conan export-pkg` after I have built both packages, it works fine and I get two packages in my conan cache: one for debug and one for release. When I package the debug or release version again by running `conan package` and subsequently run `conan export-pkg` again my cache gets removed (even though I did not specify a force overwrite option). 

Example:

```
# ... (assuming debug and release are built and packaged as specified in my previous post)
conan export-pkg . @mycompany/dev -bf=build_debug -s build_type=Debug
conan export-pkg . @mycompany/dev -bf=build_release -s build_type=Release

# now I have two packages with two hashes in my local cache for the respective package name.
conan package . --source-folder=. --build-folder=build_debug

# the result of the following call will remove my debug and release packages from the cache.
# the end result is that the cached release package is removed, debug package is effectively overwritten with the newly created debug package (although I did not specify a -f force overwrite).
conan export-pkg . @mycompany/dev -bf=build_debug -s build_type=Debug

```
[export-pkg-debug.txt](https://github.com/conan-io/conan/files/6180604/export-pkg-debug.txt)
[export-pkg-release.txt](https://github.com/conan-io/conan/files/6180605/export-pkg-release.txt)

**Comment by memsharded** [comment]
Thanks for the feedback! This is really weird, because the ``conan package`` command does not touch the cache. It doesn't have access to it. I have just doubled checked the source code, I have no idea how this could happen. Just in case, which version of Conan are you running? In which OS?

Can you please post the output of that ``conan package`` command that is removing things from the cache? Thanks!

**Comment by jlemein** [comment]
`conan package` is not removing anything from the cache. It only seems to flag or invalidate something, Then when running `conan export-pkg` it removes the previously cached results for the package that I am exporting. The snippet that I have provided in my previous post is the example:
* First build two packages for debug and release.
* Then run `conan export-pkg` for both debug and release. Result is two packages in the cache, which is correct.
* Then run `conan package . --source-folder=. --build-folder=build_debug` again. Nothing happens in the cache yet.
* Then run `conan export-pkg . @mycompany/dev -bf=build_debug -s build_type=Debug` again. Now the release package is removed from the cache. The debug also actually, but is then added again as a result of running this command.

My conan version is 1.33.0 and my OS is Ubuntu 18.04.5 LTS (Bionic Beaver)

**Comment by memsharded** [comment]
Hi @jeffrey89 

I have tried to reproduce with a test:
```python
def test_package_invalidation():
    # https://github.com/conan-io/conan/issues/8672
    client = TestClient()
    client.save({"conanfile.py": GenConanfile().with_settings("build_type"),
                 "build_debug/myfile.txt": "MyDebug",
                 "build_release/myfile.txt": "MyRelease"})
    client.run("install . --install-folder=build_release -s build_type=Release")
    client.run("install . --install-folder=build_debug -s build_type=Debug")
    client.run("build . --build-folder=build_release")
    client.run("build . --build-folder=build_debug")
    client.run("package . --source-folder=. --build-folder=build_debug")
    client.run("package . --source-folder=. --build-folder=build_release")

    client.run("export-pkg . pkg/0.1@user/channel -bf=build_debug -s build_type=Debug")
    client.run("export-pkg . pkg/0.1@user/channel -bf=build_release -s build_type=Release")

    client.run("search pkg/0.1@user/channel")
    assert "Package_ID: 4024617540c4f240a6a5e8911b0de9ef38a11a72" in client.out
    assert "Package_ID: 5a67a79dbc25fd0fa149a0eb7a20715189a0d988" in client.out

    client.run("package . --source-folder=. --build-folder=build_debug")
    client.run("search pkg/0.1@user/channel")
    assert "Package_ID: 4024617540c4f240a6a5e8911b0de9ef38a11a72" in client.out
    assert "Package_ID: 5a67a79dbc25fd0fa149a0eb7a20715189a0d988" in client.out

    client.run("export-pkg . pkg/0.1@user/channel -bf=build_debug -s build_type=Debug --force")
    client.run("search pkg/0.1@user/channel")
    assert "Package_ID: 4024617540c4f240a6a5e8911b0de9ef38a11a72" in client.out
    assert "Package_ID: 5a67a79dbc25fd0fa149a0eb7a20715189a0d988" in client.out
```

This captures the story. I realized that the problem could be in the last ``export-pkg``, that in my case requires a ``--force`` to pass. Otherwise it fails, saying that it cannot overwrite an existing package in the cache. So I suspect that what could be happening is:

- You have a ``exports_sources = "*"`` in your recipe. That means it will package absolutely every file that is there by the ``conanfile.py``.
- If some file change, it is exported, creating a new revision. A new revision needs its own binaries, it is a completely new recipe.
- I think the last ``package . --source-folder=. --build-folder=build_debug`` might be changing something else, so the last ``export-pkg . pkg/0.1@user/channel -bf=build_debug -s build_type=Debug`` is creating that new revision, which in practice removes the binaries, as explained before.

Best solution would be to make sure that only the necessary files are ``exports_sources = ``, and that those files doesn't change as a result of local building and packaging. Please check that and let me know, thanks!

**Comment by jlemein** [comment]
I indeed do not have the problem anymore if I change `export_sources` to only the needed source files.
It sounds tricky though that packages get removed without the --force flag if I set `export_sources` to '*'. But the problem is solved for me now.

Thanks for your time.

**Comment by memsharded** [comment]
> It sounds tricky though that packages get removed without the --force flag if I set export_sources to '*'. But the problem is solved for me now.

Yes, you are right, this is a side effect of an existing limitation of the current Conan cache: It can only host 1 revision at a time. When you are creating a new revision, because ``exports_sources`` modified it, the previous one is replaced. The next iteration of the cache (designed for Conan 2.0) will be able to contain multiple revisions, in that sense the binaries will not be removed, they will remain there in a previous revision, so you could use them if you want (by expliciting the revision or using a lockfile).

Thanks for the feedback!, I think this can be closed now.
