### ISSUE TITLE
[question] How to upload a package to a local registry?

### ISSUE THREAD

**Issue by evandrocoan** [conan-io/conan#8673]
May be related to:
1. https://github.com/conan-io/conan/issues/2247 - How to do local development of a library without commiting
2. https://github.com/conan-io/conan/issues/101 - Define workflow for new versions of already existing packages

I have a local registry which has `libpcap 1.8.1`, but I would like to upload `libpcap 1.9.1` from https://github.com/bincrafters/conan-libpcap because `libpcap 1.8.1` does not compile with newer gcc versions.

I am not interested in uploading any binaries. Just the recipe and the sources. The build should be done by everybody locally with `--build=missing`, i.e., `conan install libpcap/1.9.1@ourremote/testing --build=missing`

The documentation for conan upload only tells me I need to run `conan upload ...`
* https://docs.conan.io/en/latest/reference/commands/creator/upload.html

As far as I understand, the repository https://github.com/bincrafters/conan-libpcap is already created, i.e., it has a recipe, so to upload it to our local registry I should just add its sources to our local git repository and run `conan upload ...`.

So far:
1. I downloaded the local git repository, which our local conan registry uses: 
   * `git clone https://company.corp/conan/conan-libpcap && cd conan-libpcap`
1. Added a new remote for repository on bincrafters: 
   * `git remote add bincrafters https://github.com/bincrafters/conan-libpcap`
1. Created a new branch with `libpcap 1.9.1` code: 
   *  `git checkout -b testing/1.9.1 bincrafters/testing/1.9.1`
1. Uploaded the new branch to our local remote: 
   * `git push --set-upstream origin testing/1.9.1`
1. Then, I tried to upload the recipe to conan remote with: 
   * `conan upload libpcap/1.9.1@ourremote/testing -r=ourremote`
1. But it said `ERROR: Recipe not found: 'libpcap/1.9.1@ourremote/testing'`

What I need to do to upload this new recipe to our local conan registry?

Our local registry already has `libpcap 1.8.1` and I can find it:
```
$  conan search "libpcap/1.8.1@ourremote/stable" -r=ourremote
Existing packages for recipe libpcap/1.8.1@ourremote/stable:

Existing recipe in remote 'ourremote':

    Package_ID: 041253403316354016534651230465213064510
        [options]
            disable_universal: False
            enable_bluetooth: False
            enable_dbus: False
            enable_packet_ring: False
            enable_usb: False
            shared: True
        [settings]
            arch: x86
            build_type: Release
            compiler: gcc
            compiler.version: 5
            os: Linux
        Outdated from recipe: False
...
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @evandrocoan 

Sorry for the delay in responding.

First, an important recommendation about the user/channel. Packages should be immutable. They will be immutable in Conan 2.0. That means that a package will retain its user/channel after creation forever. You should be doing this now too. If you download a package from bincrafters, you will upload that package with the ``bincrafters/stable`` user channel to your repo.

What you are missing in your above steps is the actual creation of ``libpcap/1.9.1@ourremote/testing``. (Btw, please do not use the remote name as the user name. The user name should be the company/team/org name, but packages should be able to live in different remotes without problems, not just one remote.)

After you have checked out the source code of the libpcap recipe, you are missing one ``conan export`` step, that is the command that is getting the conanfile.py from the current folder/repo and creating a Conan package inside the Conan cache. 

Can you please check your step and ensure to do the ``conan export`` (typically you would do a ``conan create``, to make sure that everything works correctly, hopefully supported by a ``test_package`` folder)? Thanks!

**Comment by evandrocoan** [comment]
> First, an important recommendation about the user/channel 

Thanks for explaining. I wonder how you are going to force the user/channel to be immutable in Conan 2.0 because isn't everything text and text can be changed/renamed? 

I ran `conan export` and it is working now.

**Comment by uilianries** [comment]
Hello @evandrocoan ! I expect you are not in trouble with libpcap package in your company, I made it 2 years ago.

I also provided that version for Bincrafters (because we needed for your company), but it's deprecated now. Instead, you should use the package available on Conan Center: https://conan.io/center/libpcap

**Comment by evandrocoan** [comment]
Hi @uilianries ! I was adding a new version of libpcap because version 1.8.1 does not compile with gcc 9.3 due to problem with bison and libpcap 1.9.1 uses a newer enough version of bison. I saw it was deprecated on bincrafters, but I could not find a git repository to checkout and download the source code from the https://conan.io/center/libpcap page. Is there any? If there are none, it means git repositories are not used to track conan/version packages anymore?

> If you download a package from bincrafters, you will upload that package with the bincrafters/stable user channel to your repo

I think we rename things to garante we are not downloading from the wrong remote. To ensure this, we could either rename the remote `libpcap/1.9.1@ourremote/testing` or rename the package itself `libpcap-ourname/1.9.1@bincrafters/testing`. So, if we migrate to conan 2.0, instead of changing the channel name we would have to rename the package itself?

Why adding/enforcing user/channel to be immutable in Conan 2.0?

**Comment by uilianries** [comment]
> but I could not find a git repository to checkout and download the source code from the conan.io/center/libpcap page. Is there any?

All official recipes are now in Conan Center Index: https://github.com/conan-io/conan-center-index

Libpcap is there too: https://github.com/conan-io/conan-center-index/blob/master/recipes/libpcap/all/conanfile.py

> If there are none, it means git repositories are not used to track conan/version packages anymore?

Versions are now in [conandata.yml](https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html), it allows us reusing same recipe for any version, instead of creating a new boring branch for each new release.

Lipcap also has conan data: https://github.com/conan-io/conan-center-index/blob/master/recipes/libpcap/all/conandata.yml

> Why adding/enforcing user/channel to be immutable in Conan 2.0?

For Conan 2.0, we have created [Conan Tribe](https://conan.io/tribe.html), where new features are voted. Package immutability is one of them:

https://github.com/conan-io/tribe/blob/bf96169b19030d9e5c3399bc0649082ac2fbfa64/design/016-package_immutability.md

**Comment by evandrocoan** [comment]
> Package immutability is one of them

This new feature looks nice. I think I misunderstood the problem. Just because the package is immutable it does not mean I cannot download change the remote name and upload it to another remote with another name.

> Versions are now in conandata.yml

This looks nice too, but looks like it breaks most commands I have saved in my conan cheat-sheet:
```
# download a new version
git clone https://company.corp/conan/conan-libpcap && cd conan-libpcap
git remote add bincrafters https://github.com/bincrafters/conan-libpcap
git checkout -b testing/1.9.1 bincrafters/testing/1.9.1
git push --set-upstream origin testing/1.9.1

# tests if the package builds
rm -rf ~/.conan/data/libpcap
rm -rf /tmp/source
conan source . --source-folder=/tmp/source
conan install . --install-folder=/tmp/source
conan build . --source-folder=/tmp/source --build-folder=/tmp/source
conan export-pkg . user/testing --source-folder=/tmp/source --build-folder=/tmp/source
conan test test_package libpcap/1.9.1@user/testing --build=missing
conan install libpcap/1.9.1@user/testing --build=missing

# Sends the package to the remote
conan export . user/channel
conan upload Pkg/version@user/channel -r=myremote

# Tests if the package was correctly sent
rm -rf ~/.conan/data/libpcap
conan install Pkg/version@user/channel --build=missing
```

Is there a tutorial explaining how the workflow for development changes with this new `conandata.yml` feature or the only thing I have to remove from my cheat-sheet would be just not create git branches from the remote for each version?

**Comment by uilianries** [comment]
> This looks nice too, but looks like it breaks most commands I have saved in my conan cheat-sheet:

I remember @danimtb commented about it few days ago, where `conan source` doesn't work with `conandata.yml` when there is no `version` in conanfile.py. I didn't find any issue related, but it should be improved.

Meanwhile, you can use conan [create](https://docs.conan.io/en/latest/reference/commands/creator/create.html) command, which executes all steps in a regular development flow.

As _gambiarra_, you can declared the package version in conanfile.py (e.g version = "1.9.1").
