### ISSUE TITLE
[question] profile search order

### ISSUE THREAD

**Issue by PengolodhGoedath** [conan-io/conan#8678]
From some testing, it seems conan tries to resolve relative paths to profiles in the following order:

1. resolve from `.conan/profiles`
2. resolve from current directory

I'm a bit confused why this order was chosen, as it doesn't seem to be intuitive: Why try the more general solution before the more specific one?

---

I stumbled upon this when developing some profiles to later be shared and used with `conan config install`. One referenced profile from the local directory structure (path scheme: `../profiles/xyz`) caused some confusion, as there was another profile installed at `.conan/profiles/xyz` and the latter was chosen instead.

**Comment by uilianries** [comment]
Hi @PengolodhGoedath 

It's not clear which steps did you use to validate it. Could you please share your steps?

Indeed Conan tries first `.conan/profiles` because it's the default path. As documented, [profiles](https://docs.conan.io/en/latest/reference/profiles.html) can be used as absolute path, and that's the recommended way. You still can set `PROFILE_DIR` env var, if you don't want use default profile folder.

Unfortunately, even if we find it wrong, we could not change that behavior, due Conan 1.0 backward compatibility, but we can think about for Conan 2.0.

**Comment by PengolodhGoedath** [comment]
@uilianries For full context, I've had the following folder structure in a repo:

```
./
    .git/
    system/
        llvm/
             conanfile.py
    profiles/
        msvc2019
```
(I skipped irrelevant parts for demonstration purposes. Yes, I'm using MSVC to build LLVM.) Now, with a terminal in `./system`, I tried to build `conan create llvm -pr ../profiles/msvc2019 -s build_type=Release`. That build failed, because it didn't actually take the profile from `./profiles/msvc2019`, and instead took a profile from `.conan/profiles/msvc2019`. (I mostly noticed because some `build_requires` listed in `./profiles/msvc2019` were missing.)

I expected the relative path to search from the local directory first, before looking in the global one (if at all). To be fair, the documentation you linked only handles relative paths starting with `.`, not `..`, but it really surprised me. I expected all relative paths to be handled equally.

Even worse: After renaming `.conan/profiles/msvc2019`, the command above worked. So it's not like conan is completely unable to handle relative paths starting with `..`, it just prioritizes questionably and looks in `PROFILE_DIR` first.

After some testing, I also found that `include()` inside of a profile has the same behavior.

---

If feel this is a bad user experience. It makes for very brittle automation scripts (e.g. automatically building system library packages, what I was trying), where they might work in one environment, but fail in another. It also goes against common intuition, expecting all relative paths to work alike. It also goes against common practice of looking in more specific (= more local) places first before looking in more general ones.

---

I'm mostly asking whether this was intended, and hopefully an explanation why it was decided this way. If it isn't intended, I might make this into a bug report, but for now I'm just assuming I'm not getting the full picture.

**Comment by uilianries** [comment]
> Now, with a terminal in ./system, I tried to build conan create llvm -pr ../profiles/msvc2019 -s build_type=Release. That build failed, because it didn't actually take the profile from ./profiles/msvc2019, and instead took a profile from .conan/profiles/msvc2019. (I mostly noticed because some build_requires listed in ./profiles/msvc2019 were missing.)

Indeed I can reproduce your behavior running Conan 1.34.1.

It works for absolute path, but as the documentation says:

> Profiles can be located in different folders. For example, the default <userhome>/.conan/profiles, and be referenced by absolute or relative path:

> $ conan install . --profile /abs/path/to/profile  # abs path
> $ conan install . --profile ./relpath/to/profile  # resolved to current dir
> $ conan install . --profile profile  # resolved to user/.conan/profiles/profile

It doesn't mention ../ but, oblivious, it should work too, because ./msvc2019 works. I would consider it a bug. I'll investigate better. Thanks for reporting your case.
