### ISSUE TITLE
[question] Do versioning conflicts between dependencies cause missing packages?

### ISSUE THREAD

**Issue by kakashidinho** [conan-io/conan#8689]
Hi, I'm having some issues with dependencies' versions mismatch between a consumer project and its dependencies.
It forced `conan` to report that the dependencies were missing and requiring building missing packages from source.

Let say I have:
- a project `A` depending on project `B`.
- Both of the projects depend on `C`. 
- However, `A` requires `C` version 1.
- `B` requires `C` version 2.
- B’s package was already built with C version 2.

In this case, when building A’s package, `conan` reported that the prebuilt package of `B` is missing.

Is there a way to mix and match common dependencies between projects like that. It's inconvenient that all projects have to require the same dependencies' versions considering the projects are controlled by different teams.

**Comment by memsharded** [comment]
Hi @kakashidinho 

> Is there a way to mix and match common dependencies between projects like that. It's inconvenient that all projects have to require the same dependencies' versions considering the projects are controlled by different teams.

Not in the general case. In C and C++ projects, building an application that depends on 2 different versions of the same library will be a violation of the ODR, that could become evident as link errors in the best case, but in some worse situations that manage to link (hiding dependencies), it could still cause very difficult to debug runtime errors.

So the Conan graph model raise conflicts whenever the same package is used in two different versions in different branches of the graph. The override model allows to solve conflicts by making the consumer to define which versions is to be used.

Once the version conflict has been resolved, the binary compatibility enters scene. Conan allows a lot of flexibility in this regard, and by configuring the ``package_id_mode`` you can decide if you want to build a new binary when the upstream dependency changes its patch version, its minor version or its major version. Is this probably what you are searching for? What versions are you using that will require a new binary? Have you changed the ``default_package_id_mode``?

**Comment by kakashidinho** [comment]
Thanks. I will try it. This seems to be complicated problem to solve.
I'm just thinking if the 2 projects are shared library and they are statically linked against the same lib but different versions, it shouldn't be an issue.

**Comment by memsharded** [comment]
> I'm just thinking if the 2 projects are shared library and they are statically linked against the same lib but different versions, it shouldn't be an issue.

Yes, that can be problematic as well. Even for shared libraries, depending on the encapsulation and isolation and what is passed in the API, could break things at runtime in ugly ways. As a general rule, the same library, with the same version and configuration must be used to avoid problems.

**Comment by kakashidinho** [comment]
> > I'm just thinking if the 2 projects are shared library and they are statically linked against the same lib but different versions, it shouldn't be an issue.
> 
> Yes, that can be problematic as well. Even for shared libraries, depending on the encapsulation and isolation and what is passed in the API, could break things at runtime in ugly ways. As a general rule, the same library, with the same version and configuration must be used to avoid problems.

I know this. Anw, this enforcement basically causes the same Microsoft VC++ library's compatible hell which requires us to build multiple versions of a static lib, one for each version of Visual studio.

Btw, can I have one more question? Some dependencies' versioning conflicts didn't force source rebuild at all. May I know what is the default binary compatible mode?

**Comment by memsharded** [comment]
> Btw, can I have one more question? Some dependencies' versioning conflicts didn't force source rebuild at all. May I know what is the default binary compatible mode?

Sure, the current default mode is ``semver_direct_mode``. Which means, a new binary will be required if the direct declared dependencies (not the transitive ones) bumps their major version, or if its major version is zero  ``0.X.Y`` and minor or patch changes. It can also fire for dependencies not following semver specification (using letters, or any other non conformant version).  It is not a very good default but it was there since very early in the beginning, and it couldn't be changed without breaking. Most likely Conan 2.0 will use another default. The other modes that can be selected, like ``minor_mode``, ``recipe_revision_mode``, etc., are all transitive, they will include both the direct dependencies and the transitive dependencies.
