### ISSUE TITLE
Implicit project directory on package stage

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#869]
I'm trying to create the libpcap package, using this receipt:

```
from conans import ConanFile, CMake

class LibPcapConan(ConanFile):
    name = "libpcap"
    version = "1.8.1"
    settings = "os", "compiler", "build_type", "arch"
    # No exports necessary

    def source(self):
        self.run('git clone --branch libpcap-1.8.1 https://github.com/the-tcpdump-group/libpcap.git')

    def build(self):
        cmake = CMake(self.settings)
        self.run('cmake %s %s -DBUILD_SHARED_LIBS=OFF' % (self.conanfile_directory, cmake.command_line))
        self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self.copy("*.h", dst="include")
        self.copy("*.a", dst="lib")

    def package_info(self):
        self.cpp_info.libs = ["libpcap"]
```

So, I created this file to test:

```
[requires]
libpcap/1.8.1@demo/testing

[generators]
cmake
```

All works fine, I can export and install without problems.

However, all header files were stored at _/home/uilian/.conan/data/libpcap/1.8.1/demo/testing/package/376ea0804ce8fafcea70f651db612a88f50c6971/include/**libpcap**_

This last additional directory is not correct, my intent is move all header files to _include_, preserving all subdirectories.

Is there some way to preserve the subdirectories in include dir and ignore the project directory?

**Comment by uilianries** [comment]
Okay, now I got.

I just added _src=libpcap_ on package:

`self.copy("*.h", dst="include", src="libpcap")`

**Comment by memsharded** [comment]
If you are creating such a conanfile.txt to test, you should probably appreciate the feature of ``conan test_package``. You can create a sample, working package with:

```bash
$ conan new Pkg/0.1@user/channel -t  # please note the -t for test
$ conan test_package
$ conan search 
$ conan search Pkg/0.1@user/channel
```
Inspect the contents of "test_package" folder, you will see it is nothing weird, just a consuming project, and ``conan test_package`` is equivalent to ``conan export + conan install + conan build (test project) + launch built test app``.

Besides that, glad that you made it work, but I have to say that I prefer all my includes to be prefixed by the lib name:

```cpp
# include "boost/myboostheader.hpp"
# include "libpcap/mylibpcapheader.h"
...
```
So the trailing "libpcap" is not bad IMO, as the include path by default gets to the parent "include" dir. 
Just an style opinion.

Thanks for asking and reporting your solution!

**Comment by uilianries** [comment]
@memsharded  thanks about the report. Your tip was great!

I created my package at [conan-libpcap](https://github.com/uilianries/conan-libpcap), based on your project _conan-gtest_.
Also, I included test_package (It's a useful feature).
ASAP, I will work to change this package as _stable_.

Thanks!
