### ISSUE TITLE
[bug] ConanException: 'settings.os' doesn't exist (with Qt Creator)

### ISSUE THREAD

**Issue by ZXfkSIE** [conan-io/conan#8690]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 7 SP1 x64
  * Compiler+version: 
  * Conan version: 1.34.1
  * Python version: 

### Steps to reproduce (Include if Applicable)

I am trying to compile a Qt project in Qt Creator `4.14.2`.
I want to change compiler to `Visual Studio` since the default compiler in default config file generated by Conan is `gcc`, which is not common on Windows and causes failed pre-build package downloading.

The `conanfile.py`:

```python
from conans import ConanFile

class EQAlertConan(ConanFile):

  def requirements(self):
    self.requires("mosquitto/2.0.7")

  def configure(self):
    if self.settings.os == "Windows":
      settings = {
        "compiler": {"Visual Studio": {"version": [16]}},
        }
```
And here is the error log:

```
20:06:26: Starting: "C:\Program Files (x86)\Conan\conan\conan.exe" install -s "build_type=Debug" C:\QtProject\EQAlert\conanfile.py
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=8
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: conanfile.py: Error in configure() method, line 9
	if self.settings.os == "Windows":
	ConanException: 'settings.os' doesn't exist
'settings' possible configurations are none
20:06:26: The process "C:\Program Files (x86)\Conan\conan\conan.exe" exited with code 1.
Error while building/deploying project EQAlert (kit: Desktop Qt 5.15.2 MinGW 64-bit)
When executing step "Conan install"
```

**Comment by memsharded** [comment]
Hi @ZXfkSIE 

It is not possible to change the settings values in the recipes. Settings are always defined externally to the recipes, either in the command line, or better/recommended, in profile files. Don't try to define the setting value in your ``configure()`` method in the recipe.

If your default profile contains "gcc", not a problem, just edit the ``default`` file there and change it to define your default configuration, if it is "Visual Studio" make sure to define that in the ``default`` file.

Also please know that it is possible and recommended to define and manage your own profiles. You can create and store your different profiles for the platforms you want to control, put them in a git repo or in an zip file in a server and use the ``conan config install`` feature to have them installed and updated in your Conan environment.

Please let me know if this helps

**Comment by ZXfkSIE** [comment]
> Hi @ZXfkSIE
> 
> It is not possible to change the settings values in the recipes. Settings are always defined externally to the recipes, either in the command line, or better/recommended, in profile files. Don't try to define the setting value in your `configure()` method in the recipe.
> 
> If your default profile contains "gcc", not a problem, just edit the `default` file there and change it to define your default configuration, if it is "Visual Studio" make sure to define that in the `default` file.
> 
> Also please know that it is possible and recommended to define and manage your own profiles. You can create and store your different profiles for the platforms you want to control, put them in a git repo or in an zip file in a server and use the `conan config install` feature to have them installed and updated in your Conan environment.
> 
> Please let me know if this helps

Thank you very much. I've given up using `conanfile.py` and am using `conanfile.txt` plus custom profile now.

**Comment by memsharded** [comment]
> Thank you very much. I've given up using conanfile.py and am using conanfile.txt plus custom profile now.

Great, thanks for following up. Just for your info, as long as you define your custom profile, you are still good to use ``conanfile.py``, specially if you need some other logic (like conditional requirements) that cannot be implemented in ``conanfile.txt``
