### ISSUE TITLE
[feature] Implement discoverability for [conf] items

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#8696]
Some usages of the new `[conf]` construct are starting to be instrumented throughout the codebase. Currently, it's primarily in generators and other experimental places. While it's still early for `conf`, I think we should consider providing a good experience for users to print out all available `conf` items , current values, etc.  

Also, I think we should do something different from `conan config get`, which prints the config file and doesn't reflect environment variables, and doesn't show a comprehensive list of settings which can be set. Instead, I suggest doing something similar to `argparse`, where every possible `conf` item within the codebase is declared very early on in the main setup.  Such a strategy presents some significant challenges. For example, the actual values of the variables are reconciled as "instances" per-package during various different times.  Still, perhaps it's possible.  Another strategy might be annotations. 

While I don't know all the options for implementing, I still want to suggest the feature be considered and looked into.  We keep adding new `[conf]` items in each new release of Conan.  I feel that as users get used to adding `conf` items to profiles, it will become increasingly annoying for users to figure out what all the possible `conf` items are.  They'll have to check their Conan version, then go to the specific version of the docs, and then search the docs to find out what `conf` items are available.  Exposing them at the CLI for discovery similar to `conan --help` and `conan install --help` seems a much better pattern if it can be implemented.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Lets implement something very straightforward to start with:

- No magic: direct explicit listing of tools and core configurations in a single, centralized place, with its documentation there, manually added by us.
- The command ``conan config list/get/whatever`` would just list it, in a nice group and order

Lets keep potential validation for later, lets add the definition and help (and list it also in docs.conan.io)

**Comment by uilianries** [comment]
We have two different conf levels, one for profiles and the global.

I think we just need to update profile command to show [conf] section, and for global conf, we can adapt conan config command.

**Comment by memsharded** [comment]
It doesn't matter the origin, user wants to know all the possible configurations that they can apply, and what they mean/do. If they can/need to go in the global conf or in the profile, will be defined by its name, like ``core.xxxx`` or ``tools.xxxx``. So just 1 single command to list all existing possible configurations, not all active/used configuration.

**Comment by uilianries** [comment]
Understood.
