### ISSUE TITLE
[feature] 'clean-modified' command for bundle files

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8698]
Same use case as `conan lock clean-modified`.

When I send a bundle to an agent for building a package, I'd like to be able to remove all `modified` flags (in the bundle file and all lockfiles) to know exactly which nodes were modified by this agent.

Currently need to parse the bundle file and get a list of lockfiles to run `conan lock clean-modified` on each (the parsing is not so clean due to the way it is structured).

**Comment by memsharded** [comment]
Proposing https://github.com/conan-io/conan/pull/8726 for 1.35
