### ISSUE TITLE
[question] version conflict requires and build_requires

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#8699]
We're having an issue with requires, build_requires and version conflicts after upgrading a package.

Scenario:

3 packages, PkgA, PkgB and PkgC. PkgC has been updated from 3.0.0 to 3.1.0 (binary compatible with 3.0.0). Only PkgA cares about the updates to PkgC.

PkgA requires PkgC/3.1.0@dev/dev
PkgA build_requires PkgB/3.0.0@release/stable (required for unit testing only, hence build_requires)
PkgB requires PkgC/3.0.0@release/stable

When trying to create PkgA (after upgrading to new PkgC version) conan complains of a conflict:

```
ERROR: Conflict in PkgB/3.0.0@release/release:
    'PkgB/3.0.0@release/release' requires 'PkgC/3.0.0@release/release' while 'conanfile.py (PkgA/1.0.0)' requires 'PkgC/3.1.0@dev/dev'.
    To fix this conflict you need to override the package 'PkgC' in your root package.
```
    
To fix this issue we found that we had to completely rebuild PkgB against the new PkgC component and create a new PkgB/3.1.0 package, despite the changes to PkgC being entirely binary compatible. To release these components, the PkgB component version would have to increase for no reason.

Is there a simple way to override PkgB's dependency on PkgC through the PkgA component, so the PkgB component does not need updating?

Thank you.

- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this was not responded back then.

This no longer should be an issue in Conan 1 with the 2 profiles build/host and in Conan 2.

Closing this as solved. Please create new tickets for any further question, thanks for the feedback!
