### ISSUE TITLE
[question] Is there a way to split test requirements from application ones?

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8708]
I wanted to add gtest library to my project that already contains some packages needed for work of my application. I realized that my program links to gtest libraries which is not good at all. Can I somehow split these packages needed just for unit testing purposes using built-in conan features? How to manage that the right way?
There is a `build_requires` and I expected something like `test_requires`

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jwillikers** [comment]
There is now `test_requires` which can be added in the `build_requirements` method, see https://docs.conan.io/en/latest/devtools/build_requires.html.

**Comment by AbrilRBS** [comment]
Closing as solved with the `test_requires` functionality that Jordan mentions, thanks! :)
