### ISSUE TITLE
[question] Access full deps packages info in deps_cpp_info

### ISSUE THREAD

**Issue by Forbinn** [conan-io/conan#8709]
I would like to have access to the user / channel information of dependencies in the imports function but its seems like I can only access the name and version of the package by using:
```python
    def imports(self):
        print(self.deps_cpp_info["poco"].name)
        print(self.deps_cpp_info["poco"].version)
```

And this works fine but if a try the following code:
```python
    def imports(self):
        print(self.deps_cpp_info["poco"].user)
        print(self.deps_cpp_info["poco"].channel)
```
Then it print:
```
<conans.model.build_info._CppInfo object at 0x7f5070da80d0>
<conans.model.build_info._CppInfo object at 0x7f5070da8590>
```

I didn't report this as a bug because it may be just normal or I just don't know how to get the info.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Forbinn 

At the moment this is not possible, the information is not there. We are not adding it to ``deps_cpp_info``. Instead, we have started to add a more powerful model in https://github.com/conan-io/conan/pull/8534, if you want to check it. It will expose not only user/channel, but also other data (as package-id, recipe revision etc). This will be in next 1.35, the structure, but not access to that data. Expect it in 1.36 or 1.37, please keep tuned to changelogs and docs.

**Comment by memsharded** [comment]
``deps_cpp_info`` interface deprecated in favor of ``self.dependencies`` more complete one. Closing this ticket as outdated.
