### ISSUE TITLE
[question] Is conan ignoring CONAN_CXX_FLAGS when cross-compiling?

### ISSUE THREAD

**Issue by faulty-me** [conan-io/conan#8710]
Hi, I am cross-compiling to armv8 with Conan (v1.34.0) by means of a profile.

I tried a profile like this:

```
[settings]
os=Linux
arch=armv8
#arch_target=armv8
build_type=Release
compiler=clang
compiler.version=10
compiler.libcxx=libstdc++11

[env]
CONAN_CMAKE_SYSROOT=/usr/aarch64-linux-gnu
CHOST=aarch64-linux-gnu
CONAN_CXX_FLAGS='--target=aarch64-linux-gnu -Wall -Wextra'
CC=clang
CXX=clang++
```

However, it didn't work without setting `CONAN_CXX_FLAGS` (as the suggested cross-compiling example at https://docs.conan.io/en/latest/systems_cross_building/cross_building.html). 

Then I set `CONAN_CXX_FLAGS` (actually I tried with `CMAKE_CXX_FLAGS` as well) to pass the triplet (as shown above). However Conan is ignoring `CONAN_CXX_FLAGS` and it doesn't set `CMAKE_CXX_FLAGS`.

Here is my build function:

```
    def build(self):
        self._initialized_guard()
        cmake = CMake(self, set_cmake_flags=True)
        #args = []
        #cmake.configure(args=args)
        cmake.build()
```

**Comment by memsharded** [comment]
Hi @faulty-me 

The way Conan passes information to build system is with generators (``cmake``, ``cmake_find_package``, etc). You need to define at least one of them. The ``CONAN_CXX_FLAGS`` is not an env-var that you can define to set the compile variables. Please read carefully the documents in https://docs.conan.io/en/latest/reference/generators/cmake.html. It is a CMake variable, not an env-var variable, that some Conan generator will write in a file. 

But there is no generic way to pass arbitrary env-vars to all build systems, there is not convention, or even implementation that will follow that. For example, arbitrary CMakeLists.txt will not read any set of env-vars like Autotools does, to get environment-var definitions.

In the new, experimental tools (https://docs.conan.io/en/latest/reference/conanfile/tools.html) we will try to provide some high level abstractions for flags for the most popular build systems, but this is not easy and will take time.
