### ISSUE TITLE
[bug] ERROR: Incorrect definition of general.config_install_interval: 1s

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#8713]
executing the following command:
```
$ conan config set general.config_install_interval=1s
```
makes conan completely unusable, any conan command will fail:
```
$ conan config set general.config_install_interval=1h
ERROR: Incorrect definition of general.config_install_interval: 1s
$ conan create . stc/1.0.0-rc1@
ERROR: Incorrect definition of general.config_install_interval: 1s
```
and it seems like completely impossible to restore, at least from the command line.

looking at the code: https://github.com/conan-io/conan/blob/8e964922074538899de71bff068bb959fcfae6ac/conans/util/dates.py#L33
it doesn't allow seconds there, but seconds are allowed on `conan config set`, which is inconsistent...

I also don't like usage of in-house bicycle for parsing dates. I suggest to use [isodate](https://pypi.org/project/isodate/) module and its function `parse_duration`. it will be more flexible, as it will allow to use an arbitrary time intervals - e.g. not just an integral values of hours/minutes/seconds, but e.g. `1H30M` (1 hour and 30 minutes).

the new implementation may look like:
```
def timedelta_from_text(interval):
    import isodate
    interval = interval.upper()
    if not interval.startswith("PT"):
        interval = "PT" + interval
    return isodate.parse_duration(interval)
```

I also think `conan config set` command should validate value the same way (via trying `timedelta_from_text`), right now it allows arbitrary strings, e.g. the following is always successful command:
```
$ conan config set general.config_install_interval=xxx
```
(alternatively, read of config could default to 0 or infinity on parse error)
as every command reads the config, it's pretty annoying

/cc @uilianries 

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by memsharded** [comment]
Lets fix this, some inputs:
- Please do not introduce a new external dependency like isodate for just this.
- The validation of ``conan config set`` would be challenging, because different configs can have different validation, and the setting is completely agnostic of contents. Not worth the effort.
- Probably the mitigation is to invalidate the offending config, and remove it from the config file when wrong, so it is not being continuously failing.
