### ISSUE TITLE
[Question] Quotations in .env files generated by virtualrunenv

### ISSUE THREAD

**Issue by aleksa2808** [conan-io/conan#8714]
Hi,
is there a specific reason for quoting every item separately inside the env var lists of .env files generated by the `virtualrunenv` generator? If the possible spacing in paths is the only concern wouldn't adding quotes only at the beginning and the end of a variable value be sufficient?

meaning this:
```
LD_LIBRARY_PATH="/dummy/path:/home/user/test/build/lib:/dummy/path"
```
instead of this (current behavior):
```
LD_LIBRARY_PATH="/dummy/path":"/home/user/test/build/lib":"/dummy/path"
```

I'm asking about this because I'm often debugging binaries that use shared libraries from Conan from the VS Code (with Microsoft's C++ plugin) debugger. In their task configuration it's possible to set the environment variables with an .env file which would mean perfect integration with Conan's `virtualrunenv` generator. Unfortunately, the cpptools plugin loads the variables from the .env file in a way that only strips the outer quotes, which is something I noticed that packages like node's `dotenv` and python's `python-dotenv` do as well (well, the python package just errors out if it the var has any internal quotes). Hence, in my above example, gdb would get the `LD_LIBRARY_PATH` var with value `/dummy/path":"/home/user/test/build/lib":"/dummy/path` which is invalid and it won't be able to find any shared libs. So in the end what I need to do after each `conan install` is to remove these quotes manually before starting the debugger.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @aleksa2808 

Yes, the main reason is to handle path with spaces. If quoting the whole list of paths is enough, this might be changed.

In any case, it would be worth having a look to the new efforts in this direction: https://docs.conan.io/en/latest/reference/conanfile/tools/env/virtualenv.html. This aims to replace all the current environments in the future, and handle better cross-build scenarios and have better configurability.

**Comment by aleksa2808** [comment]
Hey, in my tests quoting the whole variable worked fine for folders with spaces, although I tested it on Linux only.

**Comment by memsharded** [comment]
Closing this ticket as outdated, the ``virtualrunenv`` was deprecated in Conan 1 and removed in Conan 2.
If you have any further question, please create new tickets. Thanks for the feedback.
