### ISSUE TITLE
Error messages when running behind nginx / IPv6

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#872]
Hi,

I had some error messages when running behind nginx:
```
2017/01/17 10:21:10 [error] 6483#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: *****, server: some.server.aaa, request: "GET /v1/conans/... HTTP/1.1", upstream: "http://[::1]:9300/v1/conans/...", host: "some.server.aaa"
``` 

So nginx tries to reach conan over the ipv6 with the default configuration.
The fix is easy, add both to the gunicorn call: `gunicorn -- -b 127.0.0.1:9300 -b [::1]:9300 `

You could add this to the documentation, so that others don't run into these problems.

Best,
Claas

**Comment by memsharded** [comment]
Fixed in http://conanio.readthedocs.io/en/latest/server.html?highlight=IPv6
Thanks!
