### ISSUE TITLE
[bug] Cannot upload from certain machine

### ISSUE THREAD

**Issue by Belpaire** [conan-io/conan#8722]
Hi, I seem to have an issue uploading to our artifactory server from a certain machine(but it works perfectly fine on my own machine).

### Environment Details (include every applicable attribute)
  * Operating System+version:windows 10
  * Compiler+version:N/A
  * Conan version: 1.34.1
  * Python version: (using conan windows installer so I don't think this applies?)

### Steps to reproduce (Include if Applicable)
Basically any conan upload from this specific machine fails. It seems like it is specific to this machine only as my own works perfectly fine, so my guess is it comes from some kind of network/config misconfiguration.
The main thing I find strange is that it retries on port 80, when the specified artifactoryurl is on port 8082, which I verified with 'conan remote list' to be http://\<servername\>:8082/artifactory/api/conan/conan-local. I also verified that the artifactory server was reachable by going to it in a browser on the problematic machine, so it doesn't seem like that is the issue.

### Logs (Executed commands with output) (Include/Attach if Applicable)
note: I obscured some things with \<servername\> \<libname and   \<restofurl\> as I don't really want to give those names away, but they are irrelevant for this bug report anyway.

logging of upload cmd:
conan upload \<libname\> --all -r conanlocalPMS
Are you sure you want to upload '\<libname\>/Version2@\<suffix\>' to 'conanlocalPMS'? (yes/no): yes
Uploading to remote 'conanlocalPMS':
Uploading \<libname\>/Version2@\<suffix\> to remote 'conanlocalPMS'
ERROR:
Error uploading file: conan_sources.tgz, 'HTTPConnectionPool(host='\<servername\>', port=80): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/files/\<restofurl\>/0/export/conan_sources.tgz (Caused by NewConnectionError('\<urllib3.connection.HTTPConnection object at 0x0413F7D0\>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))'
ERROR:
Error uploading file: conanfile.py, 'HTTPConnectionPool(host='\<servername\>', port=80): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/files/\<restofurl\>/0/export/conanfile.py (Caused by NewConnectionError('\<urllib3.connection.HTTPConnection object at 0x0413FBF0\>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))'
ERROR:
Error uploading file: conanmanifest.txt, 'HTTPConnectionPool(host='\<servername\>', port=80): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/files/\<restofurl\>/0/export/conanmanifest.txt (Caused by NewConnectionError('\<urllib3.connection.HTTPConnection object at 0x0413F350\>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))'
ERROR: \<libname\>/Version2@\<suffix\>: Upload recipe to 'conanlocalPMS' failed: Execute upload again to retry upload the failed files: conan_sources.tgz, conanfile.py, conanmanifest.txt. [Remote: conanlocalPMS]

ERROR: Errors uploading some packages

**Comment by solvingj** [comment]
It's hard to think of a way to help troubleshoot this without seeing some raw outputs to be able to look for syntax errors. It does indeed seem like it's not respecting the port on your remote URL, but it seems like you're probably doing the same exact things as you did on the working machine, so I'm not sure what would be different.  Also, if `conan remote list` shows the port properly, then it generally means the `conan remote add` command was parsed properly.  I will think about it some more and get back to you if we can come up with anything else.

**Comment by Belpaire** [comment]
I do have some screenshots lying around still of the raw output that I could mail to you. It is not superconfidential stuff to show the exact names but I'd rather not put it on a github issue.

**Comment by solvingj** [comment]
Ok, please send me a private message via email or slack and we'll arrange something.

**Comment by Belpaire** [comment]
So I found the root cause, apparently our custom url on artifactory did not contain the actual port (so of course it defaulted to port 80). So for some reason it did not fail on my development machine, but all other machines seemed to be confused by the fact that the custom url did not have the same port number as the actual port of the server. Changing this seems to have fixed the issue. Although I don't quite understand why my development machine never had an issue with it.

**Comment by solvingj** [comment]
Thanks for reporting back the solution for future user reference. Really appreciate it!
