### ISSUE TITLE
[question] Get context path of install command in my custom generator

### ISSUE THREAD

**Issue by snailcatcher** [conan-io/conan#8723]
Hi,
I want to build a custom generator for my toolchain and need conan to pass me the "context directory" into my generator.

So in short I type **conan install /some/path/to/my/conanfile** and want to know the property that contains */some/path/to/my/conanfile* inside my generator. e.g. **self.context_path**.

I was searching for all possible terms I can guess in the documentation, but I didn't find something like that.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by solvingj** [comment]
I don't remember if the generators get to know the path off hand, but I'll find out ASAP.

**Comment by solvingj** [comment]
Please try this:
`self._conanfile.recipe_folder`

**Comment by snailcatcher** [comment]
> Please try this:
> `self._conanfile.recipe_folder`

In my generator I can see **self.conanfile**, but there isn't a property named **recipe_folder** or something similar.

**Comment by solvingj** [comment]
Notice the `_` in `_conanfile`. Try that one.

**Comment by snailcatcher** [comment]
With the underscore I will get:
ERROR: 'mygen' object has no attribute '_conanfile'

**Comment by solvingj** [comment]
Ping @memsharded can you think of a reason why this would not work?

**Comment by snailcatcher** [comment]
Is there any update by now?

**Comment by snailcatcher** [comment]
So as I need this Information and feel like I should provide as much information as possible, I made a small code snippet.
So please help me with the information how to implement or fix this.

```python
from conans.model import Generator
from conans import ConanFile

class gen(Generator):

    @property
    def filename(self):
        pass

    @property
    def content(self):
        # I want to print my recipe_folder and my package_folder here, but have no clue how
        files = dict()

        ....

        return files

class Pkg(ConanFile):
    name = 'gen'
    version = "1.0"
    exports = "*"
    ...
    
    def source(self):
        ...

    def package(self):
        ...
```

**Comment by snailcatcher** [comment]
Or is there a better way to provide files via a conan package to the sources of my project (where my conanfile.py/txt with my requires live).
I only get it to work with the build folders, but this is not what I need.

**Comment by memsharded** [comment]
New generators and ``generate()`` in 1.X and 2.0 have made this way more explicit, and using ``self.recipe_folder`` as an argument to your own helpers in ``python_requires`` dependencies in the ``generate()`` method should be the way to go.

I am closing this ticket as outdated, but please create new tickets for any further question you might have. Thanks!
