### ISSUE TITLE
[question] Dependency paths in local cache.

### ISSUE THREAD

**Issue by asanka424** [conan-io/conan#8725]
I want to list the dependent libraries (dlls or so) for a given package or a executable (conanfile.py or conanfile.txt) in the cache with full paths. 

For example lets say package A has a requirement for package B. Package B has B.dll. I want to get the full path to B.dll in the cache.

 conan info <package A> --paths 

This gives me the package folders for each dependency, but doesn't show where the dlls are.

Is it possible to do this? (either in cli or python api)

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @asanka424 

What are you trying to achieve? Are you trying to implement something in recipe A, or are you trying to collect artifacts from the consumer side? If it is the latest, you want to use the ``imports()`` functionality that let you define which files you want to collect, and allows things like ``@bindirs`` origins

**Comment by asanka424** [comment]
Hi @memsharded,

Thanks for your response. 

I am trying to build a service where I can list dependencies for a given conan recipe. For example given the package `xyz/1.0.0@myservice/mychannel`, I get the list of libs (dlls) that xyz is depending on at run time. xyz can have many dependencies where those dependencies can have their own dependecies.

We are using some conan packages from other third parties and we dont have control over `import()` function.

Hope I am clear regarding my requirements.

**Comment by memsharded** [comment]
``conan cache path`` in Conan 2.0 can give all paths in the cache. 
Also external ``--deployer`` deployers can be used to extract and copy files from the cache easily.

Closing this ticket as resolved, but please create new tickets if necessary for any further question, many thanks!
