### ISSUE TITLE
Allow for conan packages to install without sudo, if system requirements are already met

### ISSUE THREAD

**Issue by pacman82** [conan-io/conan#873]
There exist the CONAN_SYSREQUIRES_SUDO that control the required usage of "sudo", for the "SystemPackageTool()". It is used or not depending on the user permissions, but it is not able to just check for existence of the system package and install otherwise.

The question is, why not checking (dpkg -s <packagename>) if the package exists before doing install with sudo?
This could allow users without root permissions to install packages with system dependencies as long as their platform already meets the requirements.

**Comment by memsharded** [comment]
This issue is contained in https://github.com/conan-io/conan/issues/873, second bullet item.

I agree that ``SystemPackageTool`` can be improved, I think this issue can be closed and grouped into #873 and follow conversation there. Thanks!
