### ISSUE TITLE
[bug] conan remove with recipe revision doesn't show revision in confirmation prompt

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#8731]
I wanted to delete a specific, erroneous recipe revision of a package from Artifactory.  I tried:

```
C:\dev\src\nx\platform>conan remove nxas/13.6.7@PORT/stable#41840ec8b4da1240009592d2719bb74b   -r=internal_artifactory_nx_stable
Are you sure you want to delete from 'nxas/13.6.7@PORT/stable' (yes/no)
```

but was filled with doubt about whether this would only delete the desired recipe revision, or whether it would delete all revisions of the package version `13.6.7`.

In testing, it would appear only the desired recipe revision was deleted (phew!) but I think it would be much more reassuring if the full recipe reference including revision was included in the confirmation prompt.

I would also like to suggest that the documentation https://docs.conan.io/en/latest/reference/commands/misc/remove.html be updated to indicate that recipe revisions are also selected, e.g. right now it says:

> positional arguments:
>   pattern_or_reference  Pattern or package recipe reference, e.g., 'boost/*',
>                         'MyPackage/1.2@user/channel'

to be clearer, it should probably say:

> positional arguments:
>   pattern_or_reference  Pattern or package recipe reference, e.g., 'boost/*',
>                         'MyPackage/1.2@user/channel',
>                         'MyPackage/1.2@user/channel#41840ec8b4da1240009592d2719bb74b'

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Version 2004
  * Compiler+version: VisualStudio 2015
  * Conan version: 1.29.0
  * Python version: 3.8.8

**Comment by solvingj** [comment]
I agree, I think we can improve the output message and improve the docs to match.

**Comment by memsharded** [comment]
@RubenRBS reports the actual output in 2.0 released beta is:
```
 $ conan remove "zlib/1.2.13#416618fa04d433c6bd94279ed2e93638"
Remove the recipe and all the packages of 'zlib/1.2.13#416618fa04d433c6bd94279ed2e93638'? (yes/no): no 
```
So this seems addressed. Thanks very much!
