### ISSUE TITLE
[question] when export_sources and scm are both specified, which one is used when building is required?

### ISSUE THREAD

**Issue by kakashidinho** [conan-io/conan#8736]
I have a conan project `A` that has both `export_sources` and `scm` specified.
When a consumer conan project uses the above project, and `--build=missing` policy is used, conan seems to checkout the `A`'s source from `scm` instead of using `export_sources`.

Not sure this should be a bug or a question.

The problem with `scm` source checkout is that on some CI servers, they don't have permission to checkout the code from git.
And this leads to conan's failure. Perhaps there should be a fallback to use `export_sources`

**Comment by memsharded** [comment]
Hi @kakashidinho 

Do you have some example that we can reproduce? When both are defined, both sources origins will be used, sequentially, one after the other (first the scm checkout then the exports_sources will be copied on top). This works and is tested, so there might be some edge case or bug there, but we would need a reproducible example. Thanks!

**Comment by kakashidinho** [comment]
Thanks for the reply,
I cannot give an example, since our projects are quite huge. However, I think I understand the behaviors you described. My problem is that the conan process stopped at `scm` checkout. For example, it reported this error on our CI server:
```
Couldn't checkout SCM: Command 'git -c http.sslVerify=true clone "...git" .   ' returned non-zero exit status 128.
```
And it didn't fallback to use `export_sources`.
However, if I remove `scm` attribute, and keep `export_sources` only the the conan process will successfully proceed.

Is there any point of using `scm`? I need to understand the purposes of `scm`  (besides checking out source code for rebuilding binary)  in order to convince my teammates to remove `scm`.

**Comment by memsharded** [comment]
> I cannot give an example, since our projects are quite huge.

Yes, I didn't mean that you shared your project code, the typical way is to produce a "toy" conanfile.py, with just the bare minimum behavior to prove the points, and that can be easily shared with the maintainers for reproduce.

Regarding your points, the truth is that for most cases ``scm`` and ``exports_sources`` are alternative strategies:

- You use ``scm`` if you don't want to embed a copy of the sources inside the recipes and Conan server, and a more accurate tracking of the sources origin (commit) is desired. There are users interested in having more controlled access to the git repos and sources, and they don't want a copy of those sources inside Conan packages.
- You use ``exports_sources`` if you do prefer to have better reproducibility of builds (it is always possible to --build these recipes), irrespective of what happens with the original git repo.

There is no single response, it is just a trade-off. But yes, in general it would not be necessary to define both.

**Comment by memsharded** [comment]
``scm`` deprecated in 1.X, removed in 2.0, closing this ticket as outdated.
