### ISSUE TITLE
[bug] tools.os_info.with_apt gives false positive on Suse when zypper-aptitude is intalled

### ISSUE THREAD

**Issue by wdobbe** [conan-io/conan#8737]
### Environment Details (include every applicable attribute)
  * Operating System+version: OpenSuse Leap 15.2
  * Compiler+version: gcc 7.5.0 (not relevant for this issue)
  * Conan version: 1.34.1
  * Python version: 3.6.12

### Steps to reproduce (Include if Applicable)
run command:
`conan install opengl/system@`

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
wdobbe@linux-wdobbe:~/build/flownodegui_conan> conan install opengl/system@
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
*: ninja/1.10.2, cmake/3.20.0
[env]

Installing package: opengl/system
Requirements
    opengl/system from 'dynniq-conan-center' - Cache
Packages
    opengl/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
INFO  :runners.py     [85]: Calling command: /usr/bin/apt-get moo > "/tmp/tmp45dq6mnq" [2021-03-30 22:09:26,392]
INFO  :runners.py     [88]: Return code: 0 [2021-03-30 22:09:26,465]
INFO  :runners.py     [96]: Output: in file:   \\\\\
                              \\\\\\\__o
                            __\\\\\\\'/_
                            
                            stdout: None
                            stderr:b'' [2021-03-30 22:09:26,465]
INFO  :runners.py     [85]: Calling command: /usr/bin/apt-get moo > "/tmp/tmp_7xadqe0" [2021-03-30 22:09:26,465]
INFO  :runners.py     [88]: Return code: 0 [2021-03-30 22:09:26,541]
INFO  :runners.py     [96]: Output: in file:   \\\\\
                              \\\\\\\__o
                            __\\\\\\\'/_
                            
                            stdout: None
                            stderr:b'' [2021-03-30 22:09:26,542]
dpkg-query: no packages found matching libgl1-mesa-dev
ERROR: The following packages need to be installed:
 libgl1-mesa-dev
opengl/system: ERROR: while executing system_requirements(): Aborted due to CONAN_SYSREQUIRES_MODE=verify. Some system packages need to be installed
ERROR: Error in system requirements
```

**Comment by wdobbe** [comment]
As you can see in the log above, the opengl package tries to install an Ubuntu package with apt-get.
I traced it down to Conan file conans/client/tools/oss.py. In that file function `with_apt` tries to find the apt-get binary with `apt_location = which('apt-get')`. On my Suse system this check succeeds:

```
wdobbe@linux-wdobbe:~> which apt-get
/usr/bin/apt-get
wdobbe@linux-wdobbe:~> rpm -qf /usr/bin/apt-get
zypper-aptitude-1.14.43-lp152.2.18.1.noarch
```

Wouldn't it be better to check file /etc/os-release to find out what system Conan is running on ?

**Comment by memsharded** [comment]
Hi @wdobbe 

What is your system reporting for the following?

```python
import distro
distro.id()
distro.version()
```

Also another question, is your apt-get operational? It seems so, because not only passes the ``which()``, but also the "moo" test. Does it work in general, but not for the ``libgl1-mesa-dev`` package? Do you use it in a combination with other system package manager?

Probably it would be better to use the system id instead of checking for apt-get, but I am also concerned that by changing this we could be breaking other users that rely on the ``which("apt-get")``.

**Comment by wdobbe** [comment]
Hi,
Here is the output of above commands:
```
wdobbe@linux-wdobbe:~/build> python3
Python 3.6.12 (default, Dec 02 2020, 09:44:23) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distro
>>> distro.id()
'opensuse-leap'
>>> distro.version()
'15.2'
```

I thinks zypper-aptitude maps apt-get commands to zypper. But the problem is that because Conan thinks my system is Debian/Ubuntu system it wants to install the Ubuntu package names which are slightly different from the package names on Suse. For example package opengl/system tries to install (debian) package `libgl1-mesa-dev` while the Suse package name is `Mesa-libGL-devel`. So regardless whether apt-get actually works the Conan operation will never succeed.

**Comment by memsharded** [comment]
Ok, I see, this seems an unfortunate bug not catched before because it only happens if ``zypper-aptitude`` is installed. I have submitted https://github.com/conan-io/conan/pull/8747 to fix it, maybe it can be released in 1.35.1

**Comment by wdobbe** [comment]
Thanks !

**Comment by memsharded** [comment]
``tools.os_info.with_apt`` is legacy, replaced by new tools in 1.X, have been removed in 2.0, closing as outdated
