### ISSUE TITLE
Different generator files when installing exported package vs. calling conan install

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#875]
I have written an example conanfile, to reproduce this issue:

```
from conans import ConanFile

class ConanFileInst(ConanFile):
    name = 'test-package'
    version = '1.0.0'
    generators = 'txt'

    def package_info(self):
        self.deps_cpp_info.defines = ['A=B', 'C=D']
```

Now you run following commands:
```
conan install

conan export demo/demo
conan install test-package/1.0.0@demo/demo --build
```

Now we have generated conanbuildinfo.txt files both in current directory and ".conan\data\test-package\1.0.0\demo\demo\build\\[hash]", but they are different. In current directory conanbuildinfo.txt contains [defines] section with "A=B" and "C=D", but conanbuildinfo.txt from .conan repository have this section empty.

**Comment by memsharded** [comment]
I think it might be a misunderstanding of the concept of ``package_info()`` and the generated files.

``package_info()`` is the method to define flags, paths, etc. to consumers of the package. Think like a .pc file.
Generated files like ``conanbuildinfo.txt`` contains information of the dependencies, the information you need from them to build your own package.

- The ``conanbuildinfo.txt`` file in the conan local cache ``.conan/data...`` is the file generated for "test-package", and contains information of its dependencies. As it has no dependencies, it will be empty.

- The ``conanbuildinfo.txt`` file in your current folder is a file intended to **consume** "test-package", and thus it will contain info about the paths to "test-package", and the definitions defined in its ``package_info()``

Please tell me if this make sense, thanks for your feedback!

**Comment by omicronns** [comment]
Then is there a way to pass some defines to build system for building "test-package", not for consuming it, without doing it manually by passing text options to build system in build() method?

**Comment by memsharded** [comment]
I am not sure what would be your intent for this. Maybe using options?
Options are variables that can be input into packages, from the command line, or by other consuming packages. Then, not necessary to hardcode the values in the ``build()`` method, but use the options.

Besides that, defining options control when a new binary is generated. Change the options, and a new binary package ID will be generated, so you can handle simultaneously many binaries built with different options.

Please check: http://docs.conan.io/en/latest/reference/conanfile.html#options-default-options and tell me if this is what you are looking for.

**Comment by omicronns** [comment]
Let say that I have library sources that depend on some C preprocessor definitions. It will create different library binary when compiled with defined -DA=1, and different binary when compiled with -DA=2. Now I have option in conanfile:

```
options = {'a' : [1, 2]}
default_options = 'a=1'
```

I want to pass A definition to my build system, let say CMake, when compiling 'test-package'. Now in addition to dependencies informations from conanbuildinfo.cmake, I am passing it to CMake via command-line in build() method, and CMake is expecting this definition and passing it to underlying build system eg. Visual Studio solution by add_definitions(). It is not very convenient. Maybe there is some conan mechanism, that I am not aware of and will cover this case.

**Comment by memsharded** [comment]
I think you could try adding your define to the cmake command line to ``CONAN_DEFINES``, something like:

```python
self.run('cmake ..... -DCONAN_DEFINES="A=B C=D" ')
```
Not tested, but this should append your definitions to the ``conanbuildinfo.cmake`` definitions, which will be later passed to ``add_definitions()``.

**Comment by omicronns** [comment]
Then what is the difference between `self.cpp_info` and `self.deps_cpp_info`? I thought that first is for informing consumer of the package about its output and additional informations required for linking with the package, and the latter is for providing additional info for building the package itself.

**Comment by memsharded** [comment]
Yes that is quite right:

``self.cpp_info`` will be defined in the ``package_info()`` method to let consumers know about variables and flags required to build against this package.

``self.deps_cpp_info`` is the information gathered from ``self.cpp_info`` of upstream dependencies, and made available to you in the ``build()`` and other methods. It is also the information used by declared generators to generate files like ``conanbuildinfo.cmake``. The issue is that these files are generated **before** calling the ``conanfile.build()`` method, so adding to it inside the ``build()`` method has no effect on those files.

**Comment by omicronns** [comment]
So creator of conanfile, should not modify deps_cpp_info object at all? I consider strange that we can generate conanbuildinfo with defines coming from requirements self.cpp_info.defines for 'test-package' build, we can add defines from 'test-package' to package consumers conanbuildinfo via self.cpp_info.defines, but there is no mechanism for adding defines to 'test-package' conanbuildinfo from its conanfile for its own build.

**Comment by memsharded** [comment]
Yes, ``deps_cpp_info`` is the information of the dependencies, so should be considered read-only. In most cases, you don't want to even read it, but rather use a generator.

Have you tried setting ``CONAN_DEFINES`` in the cmake invocation? That is a mechanism, isn't it?
If you are talking about a python model, how would you handle it? Imagine:

```def build(self):
    self.my_own_info.defines = ["SOME_DEFINE=Value"]
    cmake = CMake(...)
    self.run("cmake ... %s " % cmake.command_line())
```

Where and when would you generate information for the build? It is totally impossible. The generation of conanbuildinfo can be done, totally decoupled from the current build system, because it is the information of the dependencies, that have already been installed. Note that such dependencies can have other build systems than cmake, and the file needs to be generated before launching ``build()``.

**Comment by omicronns** [comment]
Ok, so conanbuildinfo files, no matter what generator I use, are only for passing information needed for build, bottom up (from requirement to package that requires it), and it should not be used to provide self-build info? All informations concerning building package itself depending on used options, that do not come from requirements should be provided to build system of choice via command-line (for example using your solution), or some other tricky way in build() method?

**Comment by memsharded** [comment]
Yes, that is basically the idea, just a couple of comments:

- We usually call it in reverse, the upstream are the dependencies, and the downstream are the packages that depend on other packages. The "root" node would be the consumer project or package, totally downstream. Just in case you read this in the docs.
- Yes, the rationale is that we traded-off convenience for decoupling and flexibility. Build systems are wildly different, and the way people use them too. Even CMake is used very differently by different people. So we wanted to be the most decoupled from it, so we just provide a wrapper (the ```build()`` method) in which the user/package creator can deal the way they want with their package build. No auto-magic, but full control of the build. No "tricky way", it is just the typical way that developers parameterize their builds (and we know from experience, that it is a good idea to attach as much as possible to current practices)
- The unique intersection with the user build-system, is the minimum we could think of: the information of the dependencies. Conan provides the information for them in a "passive" way, just put some information in a file, that can be used by the user build system.

**Comment by memsharded** [comment]
Hi @omicronns (Konrad),

Any follow up question to this thread, or something else you want to discuss? Could this issue be closed?
Thanks!

**Comment by omicronns** [comment]
Hi,

Thank you for your answers. I have no more questions concerning this thread.

Thanks again.
