### ISSUE TITLE
[bug] The ``conan user`` command does not accept a password that consists of specific characters

### ISSUE THREAD

**Issue by kazunarikudo** [conan-io/conan#8751]
I have an Artifact repository in JFrog and use that as a remote.

I can log in there over the web client. However, the `conan user` command says `ERROR: Wrong user or password. [Remote: my_remote]` if I execute `conan user -p [password] -r my_remote [username]`. However, `conan user -r my_remote [username]` works and the password is accepted during the interactive communication while the Conan is running.

One thing I have learned is `conan user -p [password] -r my_remote [username]` does not work if a password consists of at least the `$` sign but as far as I can recall it was actually working some months ago.

I would highly appreciate it if the team makes sure the issue can be reproducible on your side.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
  * Conan version: 1.35.0
  * Python version: 3.7.5

### Steps to reproduce (Include if Applicable)
 * `conan remote add my_remote https://somewhere.jfrog.io`
 * `conan user -p [password] -r my_remote [username]`

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan user -p [password] -r my_remote [username]
ERROR: Wrong user or password. [Remote: my_remote]
```

**Comment by uilianries** [comment]
Hi @kazunarikudo 

It's not a Conan bug, but a shell feature. You have to skip its interpretation. 

For example, when running Bash:

```
$ echo foo$ar
foo
$ echo foo\$ar
foo$ar
$ echo 'foo\$ar'
foo\$ar
$ echo 'foo$ar'
foo$ar
```

As you can see, if I don't pass `\`, Bash will resolve `$` as subcommand. Thus, you have to add `\` in your password, or, use single quotes. I can confirm it because I also use that character.

**Comment by kazunarikudo** [comment]
@uilianries Ah, I see! Thank you for the explanation.
