### ISSUE TITLE
[question] Is it safe to delete a recipe revision on Artifactory?

### ISSUE THREAD

**Issue by foundry-markf** [conan-io/conan#8752]
Hi,

So I believe this would be a question for the Conan server backend in Artifactory.

If I have a package with N revisions, where the Nth revision is good for all purposes. Then a new revision is erroneously uploaded, so that all unpinned requirements in consumers get this erronous revision. Is it safe to delete that last revision via the Artifactory UI?

This isn't covering the case where there are two good revisions that consumers may want to choose from by pinning to a revision hash. It's that the latest is bad, and it feels wrong to ask consumers to pin back.

Obviously, if someone has already downloaded the erroneous revision to their local cache, they'll need to tidy up, but we can cope with that.

Discussing with peers, there's a concern that this might cause problems on the server, so want to find out if it's a legitmate process with no side-effects.

Thanks,
Mark

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @foundry-markf 

Yes, as far as I can tell, removing a revision directly from the Artifactory UI should have the same effect as removing it with the Conan client with ``conan remove .... -r=myremote``. The revision should be removed from the Artifactory server, and consumers will no longer get that one revisions, but the previous one. 

Have you managed to try that? Any problem that you experienced? If something is failing, it would be worth to report a bug to Artifactory, sounds like this is something that should work.

**Comment by FnGyula** [comment]
Hi @memsharded 

There is something that bothers me about this: in the root of the project there is an index.json that references revisions (listing them, and such, I guess it gets the latest one at index 0). So, my guess is that removing the latest revision might break something...

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

Yes, removing revisions on Artifactory should also automatically update the ``index.json``, so I think we can close the issue. Please create a new one if you observe something different, thanks!
