### ISSUE TITLE
[feature] CONAN_USER_HOME alternative to set custom cache location only

### ISSUE THREAD

**Issue by sd185233** [conan-io/conan#8753]
For some CI builds with downstream jobs, we are using the branch name for the version and channel to indicate a snapshot, example main@us/snapshot.  We pass the -u param to create, but finding Conan will not always pull down the latest package if the same version is already in the cache.  For this reason we would like to set an env var to use a fresh cache. 

We understand this can be achieved by setting CONAN_USER_HOME, but this then means we have to clone our config repo on every job and do a conan config install.  Is there any env var that we can use to override the cache location only?

**Comment by memsharded** [comment]
Hi @sd185233 

Not sure if I understand your request. The ``CONAN_USER_HOME`` is the location of the cache, with all the config files and the packages. If you want, the ``conan.conf`` located in the cache (pointed by that environment variable), can define ``[storage]`` properties to define where to store the packages in disk. This is controlled by the env-var ``CONAN_STORAGE_PATH``.

But I am not sure what would be the issue, specially if the thing is being handled in CI it is just 2 lines, one to define the ``CONAN_USER_HOME`` to point to a fresh directory and another line to ``conan config install <url>`` to install the configuration, which is also very fast. Am I missing something?

**Comment by sd185233** [comment]
Hi @memsharded 

The following steps describe the issue we seen:
-Conan base recipe package created and uploaded, example conanbase/1.0.0.1@us/stable
-Conan base recipe package updated, but the version kept the same and new package created and uploaded.  A new revision should be created in the conan server (in our case jfrog)?
-Another package which has a dependency on conanbase is created with a call to create and passing -u.  conanbase/1.0.0.1@us/stable was already in the local cache.  The changes in the newer revision were not picked.  Can I confirm that by using -u, the newer revision should be pulled down?  From the docs it looks like -u should reach out to the server to see if there are any newer versions matching the range requested and also any new revisions.  Does this apply to Python requires too?  If yes to both of these then it could well have been a one off.  Maybe a CI step for conanbase completed with success when it actually failed or something.

Most of our builds are for four different OS x debug + release x x86 + x64 x each module package.  So while it may be fast to clone the config and run conan config install, it doesn't feel very efficient doing this for the large number of jobs we have given our config rarely changes.  Plus there's the conan user call also to auth the user.  So the question was is there an env var we can specify which would tell conan where to read and write packages from locally?  It sounds like CONAN_STORAGE_PATH may be what we are looking for?

**Comment by PengolodhGoedath** [comment]
`CONAN_STORAGE_PATH` does indeed sound interesting.

But if it's only about the `conan config install` cloning each time, this could also be mitigated by having a local (on the CI server) checkout of the config repository, and then point `conan config install --type dir` there for each downstream job. One checkout for all the builds!

(This was our solution to awkward credential handling with `conan config install`, but might work here as well. As a bonus, since each job has its own cache with its own copy of the config, there is no way for an update of the config happening mid-build.)

**Comment by sd185233** [comment]
We are using Azure Dev ops which I believe caches the source also, so this would possibly be handled already for us.. .there is still then the Conan user step to auth the user with jfrog, meaning a secret variable has to be added to every pipeline to pass the jfrog token.  At the moment when config or profiles change, a job is run on each agent to install the config and auth the user.

Will see how robust things are with the cache going forward and possibly try the storage path, failing that then will have to do config install each time.

**Comment by memsharded** [comment]
> -Another package which has a dependency on conanbase is created with a call to create and passing -u. conanbase/1.0.0.1@us/stable was already in the local cache. The changes in the newer revision were not picked. Can I confirm that by using -u, the newer revision should be pulled down? From the docs it looks like -u should reach out to the server to see if there are any newer versions matching the range requested and also any new revisions. Does this apply to Python requires too? If yes to both of these then it could well have been a one off. Maybe a CI step for conanbase completed with success when it actually failed or something.

Yes, ``--update`` should go to the server and see if there are updates available. If revisions are enabled then it should get the latest revision. It applies to ``python-requires`` too.
