### ISSUE TITLE
[bug] Problems with configuration files generated with `CMakeDeps`

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#8757]
It seems that configuration files generated with `CMakeDeps` do not raise an error when a package is not found.

Because of some unknown reason, Doxygen stopped working with Conan a few days ago:
https://github.com/mpusz/units/actions/workflows/documentation.yml

CMake file requires both Sphinx and Doxygen:
https://github.com/mpusz/units/blob/c4e9ff7f66c0ee34d8d91c0d6598f1befde2dd53/cmake/documentation.cmake#L25-L26

But only Sphinx is found by CMake:
https://github.com/mpusz/units/runs/2253391970?check_suite_focus=true#step:10:34

I cannot reproduce the issue on my local machine. Locally the log looks as follows:
```
[cmake] -- Project documentation generation: True
[cmake] -- Found Doxygen: /home/mpusz/.conan/data/doxygen/1.8.20/_/_/package/b170ec83ff42c70053bd078cb1ed89b94af0307e/bin/doxygen (found version "1.8.20") found components: doxygen dot 
[cmake] -- Found Sphinx: /home/mpusz/.local/bin/sphinx-build  
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /home/mpusz/repos/units_latest/build/GCC 10.2.0
```

which clearly states that the Doxygen was found. This is not the case on the GitHub CI where it fails.

As the generated configuration files did not force CMake to fail on the configuration step (even though `REQUIRED`) is being used in `find_package()` it badly fails during build phase:
https://github.com/mpusz/units/runs/2253391970?check_suite_focus=true#step:11:11.

Configuration files generated by Conan should force an error when the package is not found and `REQUIRED` is being used.

**Comment by memsharded** [comment]
Hi @mpusz 

Sorry this was not managed back then.
This problem should be gone now, closing the ticket, but please re-open or create a new ticket if the problem persists. Thanks!
