### ISSUE TITLE
[question] What is the advocated way to run unit tests

### ISSUE THREAD

**Issue by sd185233** [conan-io/conan#8759]
Our unit tests are being kicked off after building within the build method.  Tests can be disabled using a Conan option which is deleted from the package ID.   

However, we came across the CONAN_RUN_TESTS env var.  From what I understand, this will disable running of the "test" method.  Is the test method designed for running basic tests against a package or is it designed also for running unit tests?

Options for us are:
-Running tests from the build method depending on a custom option + deleting from the package ID.  When using a build policy which causes dependencies to build, it means having to pass *:tests=False.
-Run tests from the build method conditionally based on CONAN_RUN_TESTS 
-Run tests from the test method - which is not run if CONAN_RUN_TESTS  is false?

What is the recommended way to run?

Thanks
Scott

**Comment by at185190** [comment]
Just do add to this we are not using cmake tests and execute test executables directly.
And from what I can understand CONAN_RUN_TESTS  is meant to act as a pass through value directly to cmake.test helper.

If we are not executing unit tests via CMake, are there any benefit of still using -e CONAN_RUN_TESTS which would require quite a bit of boiler plate to process as compared with options.

**Comment by solvingj** [comment]
The variable `CONAN_RUN_TESTS` is meant to be used to control unit tests in the `build()` method.  In the docs, the example shows a recipe using `CMake()` helper, and demonstrates how the variable is implicitly leveraged by the helper for convenience.  In that case, there's no boilerplate conditional logic in the recipe. 

However, for all cases which do not use a build helper with a `test()` method, the variable is intended to be used as a "generally accepted convention" for recipe authors to control unit tests, and to avoid the need to declare a dedicated option in every recipe. In such cases, recipes authors are advised to do something like:

```python
    def build(self):
        self.run("some_build_command")
        if tools.get_env("CONAN_RUN_TESTS"):
           self.run("unit_test_executable")
```
 
Unit tests are a fairly universal concept in build workflows, and in general, should not affect the binary artifacts produced and packaged in a build.  The desire to toggle whether or not tests are run in the build method also fairly universal.  Thus, the Conan team identified `CONAN_RUN_TESTS` it as one of a few "general enough" special cases where a conventional environment variable is officially defined for "general use" with a common purpose by recipe authors.

**Comment by AbrilRBS** [comment]
Closing as addresed in Conan 2 - Built in integrations listen for the `tools.build:skip_test` conf in their `test()` methods, and recipes are free to use that conf's value as necessary too :)
