### ISSUE TITLE
scm attribute revision auto does not work with out of source recipes

### ISSUE THREAD

**Issue by burtonButt** [conan-io/conan#8760]
It seems essential for reproducibility that the code url and revision be associated and saved in the uploaded conan package. Seemingly, the driving concept behind the scm attribute url and revision "auto" feature is to capture the source code url and/or revision and associate that with the conan package via the scm attribute. 

The scm attribute url and/or revision "auto" does not work when using out of source recipes.  Specifying "auto" for the revision in an out of source recipe always results in the export method copying the source tree that contains the out of source recipe and never cloning from the actual source repo specified by the scm url.  

What is the recommended approach for capturing the source url and revision and making it available via the conan info command when working with out of source recipes?  

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by solvingj** [comment]
> It seems essential for reproducibility that the code url and revision be associated and saved in the uploaded conan package. Seemingly, the driving concept behind the scm attribute url and revision "auto" feature is to capture the source code url and/or revision and associate that with the conan package via the scm attribute.

Yes, this is exactly correct. It is an extremely strict and tight association. 

> What is the recommended approach for capturing the source url and revision and making it available via the conan info command when working with out of source recipes?

The equivalent for out-of-source recipes is to use the `scm` IN-ADDITION-TO the `source` method with a hard-coded commit hash for the sources method. The hash can be hard-coded in a few places: 1. the recipe, 2. a text file like `conandata.yml` and then read from disk and used inside the `source()` method.  Both are functionally equivalent.  Sadly, neither method makes the SCM revision used in a `source()` method available to the `conan info` command.  That is uniquely available for `scm` feature. For this reason, among many others, I have proposed the ability to "attach arbitrary metadata to recipes or binary packages":

https://github.com/conan-io/conan/issues/7207

In case it's not clear, the reason you must use both SCM + hard-coding hash for `source` method is this:

The reproducibility of a package build depends on the precise state of the sources, PLUS `conanfile.py`, PLUS any patches or additional files alongside the recipe which are captured via `exports`.  Thus, to attain reproducibility for out-of-source recipes (assuming everything is in `git`), a recipe will always need to capture a minimum of two commit hashes from two repositories.

**Comment by burtonButt** [comment]
Thanks for the feedback and confirmation regarding scm auto and the importance of capturing the complete set of source hashes to ensure reproducibility.  Build integrity and package reproducibility is crucial.  Hopefully it is being architected into Conan 2.0 (regardless of in source or out of source recipe structure, package revisioning enabled/disabled, etc.).

To solve my immediate need to capture the complete set of source hashes for my out of recipe packages, I am using the scm feature without specifying a revision in the scm data (and not using auto for the url).  I introduced a post source method hook that reads the scm data from the generated conandata.yml file, gets the git revision from that extracted git cloned repo, and updates the scm data in the generated conandata.yml file with the revision attribute.

The conan info command correctly reads the proper scm revision hash except for when there are multiple package revisions and the recipe revision has not changed.  However, the package revision exports does correctly contain the conandata.yml that has the correct source revision hash. 

I am utilizing this solution for VDD generation and fetching the source revision hash from conandata.yml file in the revisioned package exports  instead of using the conan info method.

**Comment by solvingj** [comment]
> Build integrity and package reproducibility is crucial. Hopefully it is being architected into Conan 2.0 (regardless of in source or out of source recipe structure, package revisioning enabled/disabled, etc.).

Quite likely not. In fact, my guess is the contrary. Conan will likely/hopefully focus more on providing more flexible building blocks to let users and teams engineer their own guarantees around their own processes. Many of the features Conan has created in the past which try to provide strict guarantees are too inflexible to satisfy real-world scenarios, so users end up hacking them to do clever things without realizing that they're undermining the guarantees. Then, once they're at scale, it's too late to change quickly and easily.  SCM, Lockfiles, Generators... all features users continue to use in clever ways which VERY often land them in undesirable consequences of some sort.

> The conan info command correctly reads the proper scm revision hash except for when there are multiple package revisions and the recipe revision has not changed. However, the package revision exports does correctly contain the conandata.yml that has the correct source revision hash.

I can't easily imagine all the implications and consequences of your custom process, which probably means it's unlikely that anyone else could either without trial and error.  On the surface, it sounds like you've found a clever way to circumvent the strictness and limitation of the SCM feature and make it work in a way that it was not designed to. Maybe it seems like it works so far.  Regardless, it means you'll get behavior that the Conan developers never intended and can't support, and which nobody on your team can easily predict, understand or debug.   Seems like a textbook case of what I described above.

For these reasons, I would keep reconsidering your approach and requirements and looking for a new strategy. 

By far, the number 1 best solution we've found for a large number of problems has been: "Do that in custom scripts/tools outside of Conan".  I'm not sure how it would apply in your case, nonetheless, it's highly likely to be the best advice.

**Comment by burtonButt** [comment]
As usual you are right on point. 

The solution that I came up with is a one off solution that feeds an external custom script outside of conan that grabs the revision information.  Our environment does not currently rely on having conan rebuild using the scm specification encoded in the conandata.yml file. 

So everything will be fine... until it is not!

Thanks for the great input on this topic.
