### ISSUE TITLE
[Error] clang-cl 12 is not supported !!

### ISSUE THREAD

**Issue by redradist** [conan-io/conan#8772]
I got such error:
```
-- Conan executing: C:/Python/CPython39/Scripts/conan.exe install . --remote conan-center --build missing --settings build_type=Debug --settings compiler=clang --settings compiler.version=12 --settings compiler.libcxx=libc++
ERROR: Invalid setting '12' is not a valid 'settings.compiler.version' value.
Possible values are ['3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '4.0', '5.0', '6.0', '7.0', '7.1', '8', '9', '10']
```

Maybe it is not needed to add new version to array each time ?
Maybe we just need some version like '*' ? I think it is better to discuss in conan, but I also mentioned here

**Comment by czoido** [comment]
This is a duplicate of https://github.com/conan-io/conan/issues/8139 and https://github.com/conan-io/conan/issues/8033 
Closing this one, please continue the discussion in https://github.com/conan-io/conan/issues/8033
