### ISSUE TITLE
[feature] install/strip option for cmake.install()

### ISSUE THREAD

**Issue by aleksa2808** [conan-io/conan#8775]
Hi,
for some projects I need to install binaries without symbols present when building in release mode and the usual way to do this would be to build the `install/strip` target. Since these projects were using CMake I was using conan's CMake build helper and my package method just called `cmake.install()`, but, since only `cmake.build()` can define a target to build, I needed to modify this so that it looks kinda like the following:
```python
if self.settings.build_type == "Release":
  cmake.build(target="install/strip")
else:
  cmake.install()
```  
This works OK but it just seems strange to use the `cmake.build()` command inside the package method, and I know these two methods differ in some ways (step skipping logic, install method creating the package folder and such).
For building these types of binaries, the `cmake --install` command supports the `--strip` option, so would it make sense to add a `cmake.install(strip=True)` option to the build helper as well?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @aleksa2808,
We are now focusing in adding new features just to the tools that will be the default for Conan 2.0 and not adding features for the current tools.
`cmake --install` requires CMake 3.15 as the minimum version that will be the minimum version for Conan 2.0. This feature could be a good addition for the [new toolchains](https://docs.conan.io/en/1.35/reference/conanfile/tools/cmake.html) that are available in 1.X and that will provide a smooth transition to 2.0

**Comment by mkmkme** [comment]
Hey @czoido @aleksa2808 ,

It seems that this issue has been resolved with [this commit](https://github.com/conan-io/conan/commit/0966e79776537c02aea630f4380f2d82573abc06).

**Comment by aleksa2808** [comment]
Hey, this seems like it's enabling the strip option through conf settings, so I'm wondering if it's a global-only feature or can be enabled in a conanfile for an individual package? The issue I had originally was dealing with individual packages.

**Comment by mkmkme** [comment]
You can pass it also with conan profiles or via command-line argument (`-c:h`). Would this work for you?

If not, could you elaborate what kind of use-case you have in mind?

**Comment by aleksa2808** [comment]
It would probably work well enough for what I was dealing with in the original post. I don't work with Conan at the moment so I lost my way a bit with the newer features (like the profiles). Because of this, for me this issue is resolved and I'll close it.
