### ISSUE TITLE
Best way to vary build when consumed vs build locally?

### ISSUE THREAD

**Issue by michkrom** [conan-io/conan#8776]
What is the best way to vary (hence detect) the build between when buildubg locally during package development vs when package is build when consumer is installing into local cache?

I suppose an explicit option could be used which would be set during development but unset during normal install build?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @michkrom,
You can use [in_local_cache](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=in_local_cache#in-local-cache) attribute in the conanfile.
Also, if you are using CMake there's a variable [CONAN_IN_LOCAL_CACHE](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html?highlight=conan_in_local_cache#definitions) defined.
Hope this helps.

**Comment by michkrom** [comment]
Awesome, thank you!
