### ISSUE TITLE
[bug] Private requirements missing in conanbuildinfo.cmake when using profile:host and profile:build

### ISSUE THREAD

**Issue by drmacdon** [conan-io/conan#8780]
When using private requirements the generated `conanbuildinfo.cmake` fails to include the requirement target information when installing using both  `profile:build` and `profile:host`.   

My example below is using the same default profile for both contexts, which may seem silly, but I encounter the same problem when trying a proper cross compile and it is less involved to demonstrate the problem.  

If the requirement is not listed as private, it works in both scenarios.

For example, a `conanfile.py` written like so:

```python
from conans import ConanFile
class Fail(ConanFile):
    generators = "cmake"
    def requirements(self):
        self.requires("zlib/1.2.11", private=True)
```

### FAILING (both profiles)
When installed with both profiles will, it will contain no references to zlib in the created `conanbuildinfo.cmake`

```bash
mkdir build && cd build
conan install .. --profile:build default --profile:host default

grep zlib conanbuildinfo.cmake
# RETURNS NOTHING
```

### WORKING (single profile)
While the same test with a single profile returns the expected targets.

```bash
mkdir build && cd build
conan install .. --profile default

grep zlib conanbuildinfo.cmake | head -2

set(CONAN_ZLIB_ROOT "/Volumes/external/conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900")
set(CONAN_INCLUDE_DIRS_ZLIB "/Volumes/external/conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/include")
```

## Environment Details

- Operating System: Macos 10.15.7
- CMake: 3.20.1
- Compiler: apple-clang, 12.0
- Python: 3.9.4
- Conan: 1.35.2

**Comment by drmacdon** [comment]
The install logs also indicate that it is a build-requirement when private=True, but not when private=False even though it is listed as a requirement.

```bash
conanfile.py: Applying build-requirement: zlib/1.2.11
```

The log above from https://github.com/conan-io/conan/blob/develop/conans/client/installer.py#L579. A few lines down will add the zlib reference to cpp_info when *not using_build_profile*, so it works without a build profile. 

```python
 conan_file.deps_cpp_info.add(n.ref.name, dep_cpp_info)
```

However, the else condition when I have a build profile fails to include it (the log already checked that n was not in transitive).

Which being private implies it is not transitive to downstream dependencies, but if it is not injected into the deps_cpp_info, I fail to get a conanbuildinfo.cmake target for zlib which means my package can't link against it when building with a build context, while I can if I don't use a build context.

**Comment by memsharded** [comment]
Sorry this issue was not responded back then, sometimes there are too many things ongoing and some tickets fall through the cracks.

The ``cmake`` generator has been long time superseded in Conan 1.X by CMakeDeps/CMakeToolchain, and completely removed in Conan 2.0, so I am closing this ticket as outdated. Please update to the new generators and open new tickets if necessary, many thanks!
