### ISSUE TITLE
[bug] tgui fails to install because of colon in name ('tgui:texus')

### ISSUE THREAD

**Issue by SamuelMarks** [conan-io/conan#8784]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 11.1 (20C69)
  * Compiler+version: Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
  * Conan version: 1.35.0
  * Python version: 3.9.4

#### `CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.0)
cmake_policy(SET CMP0048 NEW)
project(pp VERSION 0.0.0 LANGUAGES C)

set(src src/main.c)

if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
   message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
   file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/master/conan.cmake"
                  "${CMAKE_BINARY_DIR}/conan.cmake")
endif()

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_run(REQUIRES Catch2/2.6.0@catchorg/stable
                BASIC_SETUP)
conan_cmake_run(REQUIRES tgui/0.7.3  # this line I'm messing with, see log output
                BASIC_SETUP)

add_executable(${PROJECT_NAME} ${src})
target_include_directories(${PROJECT_NAME} PRIVATE ${CONAN_LIBS})
target_link_libraries(${PROJECT_NAME} PRIVATE ${CONAN_LIBS})

```

```sh
$ conan remote add transit https://api.bintray.com/conan/conan/conan-transit
$ mkdir build && cd $_
$ conan install ..
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
texus/0.7.3: Not found in local cache, looking in remotes...
texus/0.7.3: Trying with 'conan-center'...
texus/0.7.3: Trying with 'bintray'...
texus/0.7.3: Trying with 'transit'...
ERROR: Unable to find 'texus/0.7.3' in remotes
```

```
tgui/0.7.3: Not found in local cache, looking in remotes...
tgui/0.7.3: Trying with 'conan-center'...
tgui/0.7.3: Trying with 'bintray'...
tgui/0.7.3: Trying with 'transit'...
```

```
ERROR: Value provided for package name, 'tgui:texus' (type str), is an invalid name. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
```

https://bintray.com/conan/conan-transit/tgui%3Atexus

**Comment by memsharded** [comment]
> conan_cmake_run(REQUIRES Catch2/2.6.0@catchorg/stable
                BASIC_SETUP)
conan_cmake_run(REQUIRES tgui/0.7.3  # this line I'm messing with, see log output
                BASIC_SETUP)

You need to install requirements in one single call, because transitive dependencies could collide against each other, and only resolving them in the same step knows this. If you do it step by step, it will probably fail in the compile or link steps with way more obscure errors. 

Also ``conan-transit`` is fully deprecated. It will dissapear in 20 days. Do not use packages from ``conan-transit`` anymore. 

This is not a Conan client issue, seems just an issue with a very old and not maintained recipe in conan-transit repo, I think this can be closed.

**Comment by danimtb** [comment]
that recipe comes from conan-transit repository which is something quite old and never maintained. Feel free to contribute an update recipe for that library to conan-io/conan-center-index. Thanks!
