### ISSUE TITLE
[feature] Report important messages from server

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#8791]
Hello there;

As well known, Conan provided a [timeline](https://blog.conan.io/2021/03/31/Bintray-sunset-timeline.html) to keep all users tuned about Bintray sunset. However, this information didn't reach all users and we still have difficult to communicate all community.

A possible feature which could improve Conan communication is the ability of fetching messages from server (e.g Conan Center) and printing out when running any Conan client command.

Message request could be scheduled, like [conan config](https://docs.conan.io/en/latest/reference/commands/consumer/config.html) install scheduler, to avoid multiple network usage.

This idea was proposed [here](https://github.com/conan-io/conan/issues/8788#issuecomment-818236034) and by @SSE4 too.

Of course, it requires a change on Artifactory too, but it seems valid. We could post a message for any service maintenance, new Conan release, ... And people no longer need to search on internet.

Some propose:

```
$ conan config set general.message_scheduler_interval=1d # Fetch for new messages every 1 day
$ conan install zlib/1.2.11@
************************* WARNING: CONAN-CENTER REPORT ***********************

April 12, 2021 - Maintenance - All Conan Repositories Affected
For more information, visit https://blog.conan.io/2021/03/31/Bintray-sunset-timeline.html

******************************************************************************
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Closing as not planned
