### ISSUE TITLE
[feature] Option to host/download packages via VCS

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#8798]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I would love to see support for configuring dependencies in terms of git repositories.

This way, we can grandfather in many interesting libraries with less of a burden to involve any artifact servers. Let's make it even easier for developers to publish and use conan packages!

**Comment by memsharded** [comment]
Hi @mcandre 

This has been discussed before, https://github.com/conan-io/conan/issues/6102, https://github.com/conan-io/conan/issues/3669, https://github.com/conan-io/conan/issues/8322.

And more recently https://github.com/conan-io/conan/issues/8607. Please track this one for further information, I will close this one as duplicate. In short, this will not be possible, there are many technical reasons, we will summarize them in the FAQ soon.
