### ISSUE TITLE
[bug] SYSTEM_LIBS not passed via CMake targets (cmake_find_package generator)

### ISSUE THREAD

**Issue by whyman** [conan-io/conan#8799]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: GCC 10
  * Conan version: 1.35.1
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)
Using the cmake_find_package generator, the SQLite3 target does not include the required system libs for linking to work as expected.

### Logs (Executed commands with output) (Include/Attach if Applicable)
Code is simply:

```cmake
target_link_libraries(mylib PUBLIC SQLite::SQLite3)
target_link_libraries(myapp PUBLIC mylib)
```

```
/usr/bin/ld: /home/user/.conan/data/sqlite3/3.35.4/_/_/package/d9f1064aa2f2acf9923d422dfbae3fc448b4d5ab/lib/libsqlite3.a(sqlite3.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
```
As you can see we need to link `dl` here (which is also encoded in the recipe)

Any ideas?

**Comment by uilianries** [comment]
Hi @whyman, this issue should be moved to https://github.com/conan-io/conan-center-index/issues/

It's related to SQLite3 package, not Conan client.

Anyway, `dl` is liked only when `OMIT_LOAD_EXTENSION` is enabled.

https://github.com/conan-io/conan-center-index/blob/master/recipes/sqlite3/all/conanfile.py#L180

**Comment by whyman** [comment]
Hi @uilianries Thanks for replying

I think the `dl` is linked when `OMIT_LOAD_EXTENSION` is disabled (e.g. it is load extensions are enabled), which it is by default:

```python
            if not self.options.omit_load_extension:
                self.cpp_info.components["sqlite"].system_libs.append("dl")
```
The double negation should mean it is added, right?

Can you explain how this is a package specific problem in that case? ( I am new and want to fix it! )

**Comment by uilianries** [comment]
@whyman 

> The double negation should mean it is added, right?

Yes, correct.

> Can you explain how this is a package specific problem in that case?

It's simple, you need sqlite3, consume it, but doesn't work. Besides that, system libs and cmake_find_package are largely used, if it was a Conan bug, we would had many other issues reporting same.

Now we have to investigate Sqlite3 package, but first this issue should be moved and your description should be more detailed (follow [this](https://github.com/conan-io/conan-center-index/issues/new?assignees=&labels=bug&template=package_bug.md&title=%5Bpackage%5D+%3CLIBRARY-NAME%3E%2F%3CLIBRARY-VERSION%3E%3A+SHORT+DESCRIPTION) template).

**Comment by whyman** [comment]
Okay, reported over there instead https://github.com/conan-io/conan-center-index/issues/5221
