### ISSUE TITLE
Allow editable local installs

### ISSUE THREAD

**Issue by bjoernpollex** [conan-io/conan#88]
Similar to [pip editable installs](http://pip.readthedocs.org/en/stable/reference/pip_install/#editable-installs). Consider the case where you are working on an application **A**, and have to make changes to library **L** in order to implement a feature. It would be very useful to simply modify **L** in place, and **A** would pick up the changes when it is compiled next.
For header-only libraries this would merely require linking instead of copying when building the package. For compiled libraries this would be more complicated, because either the user has to take care of compiling them in the right order manually, or the `conan build` command would have to be tweaked to to this.
Either way, I think this would require explicit support in the conanfile of the package, so it would have to be optional, and packages that support it would have to declare that explicitly.

**Comment by skizzay** [comment]
Isn't this the same as running conan install --build Package?  Maybe I'm missing something...

**Comment by lasote** [comment]
@bjoernpollex You can always download a conanfile, modify it, export in the same channel and it will overwrite the previous one. Just invoke conan install --build and it's done!
