### ISSUE TITLE
[bug] find_package(...) succeeds even when requested REQUIRED non-existent components when using cmake_find_package[_multi] generators

### ISSUE THREAD

**Issue by andoalon** [conan-io/conan#8801]
Possibly (partially?) fixed in #8716

## Environment details
* Conan version: 1.35.0
* CMake version: 3.19.20122902-MSVC_2 (version bundled with Visual Studio 2019 16.9.3)

## Steps to reproduce
* Write a conan recipe that uses components, and has different `filename` and `name`:
```py
# ...
def package_info(self):
    self.cpp_info.names["cmake_find_package"] = "Foo"
    self.cpp_info.names["cmake_find_package_multi"] = "Foo"

    self.cpp_info.filenames["cmake_find_package"] = self.name # "foo_api_headers"
    self.cpp_info.filenames["cmake_find_package_multi"] = self.name # "foo_api_headers"

    self.cpp_info.components["FooCApi"].names["cmake_find_package"] = "FooCApi"
    self.cpp_info.components["FooCApi"].names["cmake_find_package_multi"] = "FooCApi"

    self.cpp_info.components["FooCxxApi"].names["cmake_find_package"] = "FooCxxApi"
    self.cpp_info.components["FooCxxApi"].names["cmake_find_package_multi"] = "FooCxxApi"
# ...
```
* Use conan's cmake_find_package or cmake_find_package_multi generator
* Use `REQUIRED COMPONENTS` when using `find_package` in CMake, and require a non-existent component:
```cmake
# ...
find_package(foo_api_headers REQUIRED COMPONENTS this_component_doesnt_exist)
# ...
```
* CMake configuration should fail at `find_package`, but it doesn't

## Cause and possible fix
Current `conans/client/generators/cmake_find_package.py`:
```cmake
if({{ pkg_name }}_FIND_COMPONENTS) # <--------- Issue here
    foreach(_FIND_COMPONENT {{ '${'+pkg_name+'_FIND_COMPONENTS}' }}) # <--------- Issue here
        list(FIND {{ pkg_name }}_COMPONENTS "{{ pkg_name }}::${_FIND_COMPONENT}" _index)
        if(${_index} EQUAL -1)
            conan_message(FATAL_ERROR "Conan: Component '${_FIND_COMPONENT}' NOT found in package '{{ pkg_name }}'")
        else()
            conan_message(STATUS "Conan: Component '${_FIND_COMPONENT}' found in package '{{ pkg_name }}'")
        endif()
    endforeach()
endif()
```
Here `{{ pkg_name }}_FIND_COMPONENTS` is used, but `{{ pkg_filename }}_FIND_COMPONENTS` should have been used. In my particular example, `Foo_FIND_COMPONENTS` is used instead of `foo_api_headers_FIND_COMPONENTS`, and because the former variable does not exist, the loop body never runs and no components' presence is ever checked. The same happens in `conans/client/generators/cmake_find_package_multi.py`. If I manually replace `Foo_FIND_COMPONENTS` with `foo_api_headers_FIND_COMPONENTS` in the file generated by conan, the issue is fixed.

#8716 seems to address the issue in `cmake_find_package.py`, but it doesn't seem to do the same fix in `cmake_find_package_multi.py`, if I understood it correctly. Also, the same issues seems to be present in `conan/tools/cmake/cmakedeps.py` according to what I saw in the PR (although I don't know what that file is responsible for 😅).

**Comment by memsharded** [comment]
Hi @andoalon 

Sorry this wasn't responded back then, sometimes we just can't handle all the incoming tickets.

This issue was reporting the legacy CMake integration, which has been superseded by the new one in Conan 1.X https://docs.conan.io/1/reference/conanfile/tools.html, and removed in Conan 2.0: https://docs.conan.io/2/reference/tools/cmake.html. Closing this ticket as outdated.

Please update to use the modern CMake integration, and please don't hesitate to open new tickets as necessary. Thanks!
