### ISSUE TITLE
[bug] "conan_build_info --v2 pubilish" does not work as expected

### ISSUE THREAD

**Issue by chetz79** [conan-io/conan#8802]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows10 Professional 64Bit
  * Compiler+version: Visual Studio 2017
  * Conan version: 1.24 - 1.35 (at least)
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)
try to publish a build against an Artifactory server, which is availabel under an url, which does not ends on "/artifactory"
please see method "_get_metadata_artifacts(…)" and function "publish_build_info(…)" in file "{pythonroot}\Lib\site-packages\conans\build_info\build_info.py"
the suffix which is automaticaly appended to the url is "/artifactory/api/storage/conan/“ which will result in an invalid rest api call, if your server does not have this "artifactory" string in it's url

**Comment by czoido** [comment]
Hi @chetz79,
Thanks a lot for reporting, 
Could you please specify which Artifactory version are you using?
Also, I presume that your url for the API does not have _artifactory_ in it, so you would need the `artifactory` service context to be removed?

**Comment by chetz79** [comment]
Hi Carlos,

we use "*Artifactory Version 6.19.1*"
And yes, our Artifactory server is available under an address without
artifactory and so the API neither has it in it's address. Since this
probably is not the usual case, perhaps one could spezify by a flag that
this artifactory should be removed - or rather shouldn't be appended.

Best regards
Christoph


Am Do., 15. Apr. 2021 um 09:25 Uhr schrieb Carlos Zoido <
***@***.***>:

**Comment by czoido** [comment]
Hi @chetz79,
Thanks for the information, we can submit a fix to make this work for your Artifactory setup on the Conan side.
Also, please be aware that removing the service context starting in version 7.0 can be problematic as stated in [this blogpost](https://jfrog.com/knowledge-base/how-to-remove-artifactory-from-the-context-url-in-artifactory-7/).

**Comment by memsharded** [comment]
@chetz79 this will be released next 1.36

**Comment by chetz79** [comment]
@all thank you for your support and for keeping me up to date

best regards
Christoph


Am Di., 20. Apr. 2021 um 22:32 Uhr schrieb James ***@***.***>:
