### ISSUE TITLE
[question] How to build for arm64 catalyst  (Apple M1)?

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan#8803]
Unfortunately I can't find a way to build for M1 catalyst or am I missing something?

@SSE4 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Probably @SSE4 can help with this.

**Comment by dmn-star** [comment]
The target for arm64 catalyst is **arm64**-apple-ios13.0-macabi.

**Comment by SSE4** [comment]
@dmn-star seems like you're right
we need to modify a code at: https://github.com/conan-io/conan/blob/f230bf104842c160be6ea377497151fe1ea64c38/conans/client/build/compiler_flags.py#L51
to support other architectures besides x86_64
I'll prepare PR
