### ISSUE TITLE
[question] Conan center search takes ages

### ISSUE THREAD

**Issue by db4** [conan-io/conan#8804]
The request
```
conan search -r conan-center boost
```
takes almost 2 minutes to complete. Why? Probably due to that a dependency `boost/[>=1.66.0]` in my recipe makes the whole recipe failing with a timeout:
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v2/conans/search?q=boost%2F%2A&ignorecase=False (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))
```
I understand the range queries are expensive but should they be expensive THAT much?

**Comment by memsharded** [comment]
Hi @db4 

This is a well known problem of bintray. Once that we are able to migrate ConanCenter off Bintray, which is planned for the next weeks (https://blog.conan.io/2021/03/31/Bintray-sunset-timeline.html) this should be improved.

**Comment by db4** [comment]
@memsharded thanks I lot for a super-fast reply! BTW  are you going to change conan-center URL (conan.bintray.com) after bintray shutdown? I read your blog but didn't find the answer.

**Comment by memsharded** [comment]
conan.bintray.com will keep working after 1st May, and for a few more months.

Then, we will provide a new URL that will replace it, freezing the state of conan.bintray.com, but conan.bintray.com will keep working simultaneously during some months, in order to allow a smooth transition to the new url.
