### ISSUE TITLE
[question] Why is the "run_environment=True" not used as a default?

### ISSUE THREAD

**Issue by akalali** [conan-io/conan#8805]
I just came across the problem that my Conan recipe (specifically the included test_package) does not work on Ubuntu using a shared library.
The problem is that I was missing the `run_environment=True` argument. I was missing this because I created my test_package as explained [here](https://docs.conan.io/en/1.35/creating_packages/getting_started.html#the-test-package-folder).

I find this confusing: For me it seems as this example test_package does only work with static libraries. It is written that shared libraries can be enabled and for this the `imports()`-method is used, such that the required files (depending on the OS) are copied to the bin.directory - so they can be found. However, this is not working for Linux or macOS, as explained [here](https://docs.conan.io/en/1.35/howtos/manage_shared_libraries/env_vars.html#using-shared-libraries-from-dependencies).

So in order to make my recipe and the test_package work on different OS, I needed to change
```
def test(self):
        os.chdir("bin")
        self.run(".%sexample" % os.sep)
```
to
```
def test(self):
        bin_path = os.path.join("bin", "example")
        self.run(bin_path, run_environment=True)
```
(Note: The change in the executable path was out of convenience; the `run_environment=True` is the important part).

Using the first snippet I needed to do
```
def imports(self):
        self.copy("*.dll", dst="bin", src="bin")
        self.copy("*.dylib*", dst="bin", src="lib")
        self.copy('*.so*', dst='bin', src='lib')
```
for Windows to find the *.dll files. But this is not necessary for the second snippet, so I removed the `imports`-method completely.

My questions:
- Why is the example without `run_environment` even given as an example in the "Getting Started" documentation?
- What is the reason for copying the files inside of a test_package, if this has no impact for Linux and macOS?
- What is the recommended way to create a test_package that works on the three different OS?

Maybe it would make sense to alter the example in the "Getting Started" documentation or at least link to the specifics of using shared libraries.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Hello @akalali 

> Why is the "run_environment=True" not used as a default?

Backward compatibility. `self.run(..., run_environment=True)` was introduced in Conan 1.6.0. Conan can't change its behavior, otherwise it can break users. Any new feature should not change Conan default behavior.

Your error is due a documentation error, it will be fixed, thank you for reporting.

> Why is the example without run_environment even given as an example in the "Getting Started" documentation?

*Getting Started* tries to be very simple, we don't consider Python as language well dominated by all developers, also if we introduce one argument more, is one more item to learn/read from documentation, so copying is easier for learning. You can use `run_environment=True` instead of copying dynamic libraries, it was a trick created by Bincrafters and later incorporated by Conan.

> What is the reason for copying the files inside of a test_package, if this has no impact for Linux and macOS?

Not true. Both Unix systems need to know where shared libraries are installed. If they are not installed on current binary directory, your system will look for *LD_LIBRARY_PATH* or *DYLIB_LIBRARY_PATH*. As `run_environment` is not declared, copying is mandatory.

> What is the recommended way to create a test_package that works on the three different OS?

To provide a good Conan recipes it's a different case, I suggest reading Conan Center Index [section](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#how-to-provide-a-good-recipe) where explain about official example which are well supported for any platform (including their test_package).

**Comment by akalali** [comment]
Thank you for your quick reply.

> > Why is the "run_environment=True" not used as a default?
> 
> Backward compatibility. `self.run(..., run_environment=True)` was introduced in Conan 1.6.0. Conan can't change its behavior, otherwise it can break users. Any new feature should not change Conan default behavior.
> 
> Your error is due a documentation error, it will be fixed, thank you for reporting.
> 
> > Why is the example without run_environment even given as an example in the "Getting Started" documentation?
> 
> _Getting Started_ tries to be very simple, we don't consider Python as language well dominated by all developers, also if we introduce one argument more, is one more item to learn/read from documentation, so copying is easier for learning. You can use `run_environment=True` instead of copying dynamic libraries, it was a trick created by Bincrafters and later incorporated by Conan.

That seems reasonable to me, thank you for the clarification.

However, there seems to be a misunderstanding - probably on my side. So let me clarify some things:

The fix that you linked here is relevant, however, this is only a fix for the documentation. If someone is actually following the documentation steps, he or she will be presented with the correct `conanfile.py` (including `self.copy("*.so*", dst="bin", src="lib")`).

However, I did not use the steps from the documentation but I was rather creating my own package recipe and the corresponding test_package. So what I did now to verify things: I followed the documentation steps using Ubuntu and everything works as expected. I was also able to switch to shared libraries with the hello-example.

Now I was wondering why it did not work with my own recipe / test_package so I removed some code from the `conanfile.py` (both the package recipe and the test_package) to see which lines of code are crucial for this to work.
Following are the things that I found out that I would like you to shed light on, if you don't mind:
1. I can remove the `import`-function from the `conanfile.py` inside the test_package completely and everything works as expected (using Ubuntu, both static and shared). So I wonder why this happens. From what I read and what you wrote
> Not true. Both Unix systems need to know where shared libraries are installed. If they are not installed on current binary directory, your system will look for LD_LIBRARY_PATH or DYLIB_LIBRARY_PATH. As run_environment is not declared, copying is mandatory.
this should not work. However, copying is not necessary (the `libhello.so`-file does not exist in the binary directory of the `example` executable). Did I misunderstood something (I'm not familiar with Unix system so I might completely overlook something here).

2. If I remove the copying of the libraries from within the top-level `conanfile.py` (the recipe for HelloConan), the build fails with the following error message:
```
[100%] Linking CXX executable bin/example
/usr/bin/ld: cannot find -lhello
collect2: error: ld returned 1 exit status
...
ERROR: hello/01(test package): Error in build() method, line 15
...
```
However, the error occurs with a static and a shared build. So I wonder how my recipe differs which produces an error only with a shared build.
I will investigate more on this.
I mean, I could just rely on the `run_environment = True` argument and be happy but I'd like to understand the underlying principle.

Also, while we're at it:
The conanfily.py that is created by using `conan new helo/0.1 -t` is different to what is written in the documentation. You already opened an issue for this, fixing the missing `self.copy("*.so*", dst="bin", src="lib")` but two more things are missing (and I'm nitpicking here 😁 ):
1. fPic and `config_options` are missing in the documentation
2. topics and author are missing

**Comment by uilianries** [comment]
> Now I was wondering why it did not work with my own recipe / test_package so I removed some code from the conanfile.py

The Getting Started recommends using [conan new](https://docs.conan.io/en/latest/creating_packages/getting_started.html?highlight=new#creating-the-package-recipe) command to avoid any possible prone error. If you use that command, it should work.

> However, the error occurs with a static and a shared build. So I wonder how my recipe differs which produces an error only with a shared build.

Probably `conanbuildinfo.cmake` is not being consumed. Without it, your CMake will not receive definitions provided by Conan, like BUILD_SHARED_LIBS=ON/OFF, etc.

**Comment by memsharded** [comment]
``run_environment=True`` is legacy (and removed in 2.0) way of managing environment, I am closing this ticket as outdated.
Please update to the new ``VirtualXXXEnv`` generators and create new tickets if necessary, thanks!
