### ISSUE TITLE
[feature] remove corrupt cache files and retry download 3 times

### ISSUE THREAD

**Issue by blackliner** [conan-io/conan#8807]
On CI, we have sometimes corrupted files in the download cache. The current workflow, as it is also recommended with a [comment here](https://github.com/blackliner/conan/blob/538c3550b6102e07739fdc3a0d526200fde6d283/conans/client/downloaders/cached_file_downloader.py#L56-L57), is to manually delete the file. Unfortunately, on CI that is not possible.

I propose a change to the mechanism, and allow up to 3 attempts to download a file, before erroring out: https://github.com/conan-io/conan/pull/8806

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Closed by #8806
