### ISSUE TITLE
[feature] Recognize CMake's "Ninja Multi-Config" generator

### ISSUE THREAD

**Issue by mrjoel** [conan-io/conan#8813]
Add support for the "Ninja Multi-Config" generator of CMake, which was added in CMake 3.17.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/8814
