### ISSUE TITLE
[bug] conan create acts differently as conan build

### ISSUE THREAD

**Issue by snailcatcher** [conan-io/conan#8822]
#### Operating System+version:
Windows 10 1909 

#### Compiler+version: (conan profile)
[build_requires]
cmake/3.20.1
mingw_installer/1.0@conan/stable
msys2/20200517

[settings]
os_build=Windows
os=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8.1
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
build_type=Release

#### Conan version:
Conan version 1.35.1

#### Python version:
Python 3.9.2

### Steps to reproduce (Include if Applicable)
conan create is using the CMakeLists.txt in the buildfolder (.../.conan/data/package/.../build/*guid*/). \
conan build is using the CmakeLists.txt in the source dir of my project.

For me this is a huge issue, because I try to pack my whole toolchain into an conan generator (which is building my CMakeList files form templates)

conan create does everything like I would expect it. \
conan build instead fails with ***CMake Error: The source directory "..." does not appear to contain CMakeLists.txt.***
The source folder has no CMakeLists.txt file, but my build folder does.

And if i understand conan correctly the *create* function should trigger the *build* function, or am I wrong?

**Comment by memsharded** [comment]
Hi @snailcatcher 

Conan provides several folders arguments for the command line in order to specify locations (https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html). It also depends how the ``conanfile.py`` implements the ``build()`` method.  It would be great to have a ``conanfile.py`` and the exact commands you are using, could you please provide them?. Maybe a ``--source-folder=xxxx`` might solve it.

**Comment by snailcatcher** [comment]
Hi @memsharded 

Your link was very helpful, because it shows me that the underlying problem is not exactly what I described. (actual problem is at the bottom of this comment)

I try to do a minimalistic setup:
packgen is a conan generator which generates my CMakeLists.txt Files

structure:
- root
  - build
  - package
    - src
      - source.h
      - source.c
  - conanfile.py

conanfile.py
```
from conans import ConanFile, CMake

import os
import platform

class Pkg(ConanFile):
    name = "paket"
    version = "0.0.0"
    exports_sources = "src/*", "unittest/*"
    settings = "os", "compiler", "arch", "build_type"
    generators = "cmake", "packgen"
    build_requires = "packgen/0.0.1@ci/master"

    def build(self):
        cmake = CMake(self)
        # cmake.verbose = True
        cmake.definitions["CONAN_PROJECT_NAME"] = self.name
        cmake.definitions["CONAN_PROJECT_VERSION"] = self.version
        cmake.configure()
        cmake.build()
        cmake.test()
        cmake.build(target="coverage")
        cmake.build(target="docs")

...
```

CMakeLists.txt (in **build_folder** (packgen/0.0.1 will put it there))
```
cmake_minimum_required(VERSION 3.18)

project(${CONAN_PROJECT_NAME} C CXX)
set(PROJECT_VERSION ${CONAN_PROJECT_VERSION})

include(${CMAKE_CURRENT_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

include_directories(src)

set(LIB_TARGET ${CMAKE_PROJECT_NAME}_lib)

add_subdirectory(src)
```

CMakeLists.txt (in **build_folder/src** (packgen/0.0.1 will put it there))
```
file(GLOB_RECURSE SOURCES LIST_DIRECTORIES false *.c)
file(GLOB_RECURSE HEADERS LIST_DIRECTORIES false *.h)

add_library(${LIB_TARGET}
    STATIC ${SOURCES} ${HEADERS}
)
set_target_properties(${LIB_TARGET} 
    PROPERTIES VERSION ${PROJECT_VERSION}
)
target_include_directories(${LIB_TARGET}
    PUBLIC ${CMAKE_CURRENT_LIST_DIR}
)
```

### actual problem
If I use *--source_folder=.* as you suggest, it solves a part of my problem, because now my CMakeList.txt files will be found. but My sources will not be in that folder because *conan build* does not copy the sources to my build folder.

So the solution for my problem will be either generate the CMakeLists.txt files to my actual source folder, which will be bad, because a package manager should not impact my sources, or to copy my sources from the source to the build folder before cmake will be called. \
Is there a way in conan to do the 2nd one?

can this be made conditionally compared to my source_folder, so it will only copy the sources when it is necessary (When the source_folder is specified and not equal the folder the conanfile is in)

**Comment by memsharded** [comment]
Sorry @snailcatcher this was not followed-up back then.

Conan has improved a lot since then:
- Adding ``layout()`` to describe folders and project structure
- With the ``generate()`` method, it is possible now to achieve identical builds with ``conan install`` + ``cmake``, or using ``conan build`` or using ``conan create``.

Closing this ticket as solved
