### ISSUE TITLE
Package version conflict although a version range exists (diamond problem)

### ISSUE THREAD

**Issue by Viatorus** [conan-io/conan#8824]
Hello,

if two depending packages (B, C) has different version requirements of the same package (A), you have to resolve the conflict in root package:

`To fix this conflict you need to override the package '...' in your root package.`

But I thought or would prefer, if one of them has a version range to A, this could be automatic resolved. But this does not happen.

**lib-a**
```py
class Lib(ConanFile):
    name = "lib-a"
    version = "0.0.2" # Or 0.0.1
```

**lib-b**
```py
class Lib(ConanFile):
    name = "lib-b"
    version = "0.0.1"
    requires = "lib-a/0.0.1"
```

**lib-c**
```py
class Lib(ConanFile):
    name = "lib-c"
    version = "0.0.1"
    requires = "lib-a/[0]"
```

**lib-d**
```py
class Lib(ConanFile):
    name = "lib-d"
    version = "0.0.1"
    requires = "lib-b/0.0.1", "lib-c/0.0.1"
```

See and run create.sh in https://github.com/Viatorus/conan-test-diamond

Runnig conan 1.34.0.

**Comment by solvingj** [comment]
@memsharded the use-case seems fair on the surface.  Is this something that:
1. Should be supported?
2. Could be supported?

I think it depends a lot on how version-range resolution and version-conflict is implemented on the backend, and I don't know who else might recall how that was done.

**Comment by Viatorus** [comment]
@memsharded Any updates on this?

**Comment by Viatorus** [comment]
@solvingj  @memsharded Any updates on this?

**Comment by memsharded** [comment]
The dependency resolution algorithm in Conan is not a full SAT solver over the version ranges, and it will not be.
The thing is such a SAT solver is a NP hard problem, together with the fact that its resolution involves doing tons of http api calls to servers, makes the problem intractable in practice.

So the dependency resolution is greedy, it starts from the consumer, and the resolved versions override the upstream, including version ranges.


The dependency resolution in Conan 2.0 has improved a bit over this aspect. For diamonds it is capable of doing some in-range validations and the above problem might be correctly resolved without conflict and without overriding. But still it will not be a full SAT solver for all cases, and conflicts can eventually appear even if there is some valid version in between all the defined ranges that would satisfy all of them. 
If you want to try the above problem, Conan 2.0.0-alpha.1 is already in PyPI, you can get it and try it (the docs are still mostly missing, but something is already in the 2.0-alpha version in docs.conan.io).

**Comment by memsharded** [comment]
As described in the last comment, Conan 2 provided some improvements regarding version ranges resolution. Still not a full SAT-solver, and it is not planned at the moment to provide one (becomes intractable very quickly, it is NP-hard)

Closing as responded back then, please create new tickets for any further question or issue. Thanks for the feedback.
