### ISSUE TITLE
[question] Git doesn't ask for a password

### ISSUE THREAD

**Issue by isnullxbh** [conan-io/conan#8825]
Is there a way to force Conan to ask for a password on git clone? I'm not sure that is a Conan issue - when I install a package, I got a prompt for a password, when I use the package in a project (via cmake-wrapper for Conan) - I got an error with the following description: 

> fatal: could not read Username for <URL>: No such device or address

Conanfile:

```
def source(self):
    self.run("git clone <URL>")
```

Installation:

```
conan export . user/channel
conan install package/0.1.0@user/channel --build=lmd --build missing --profile=gcc
conan test test_package package/0.1.0@user/channel --profile=gcc
```

CMakeFiles.txt in a target project:

```
include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_configure(REQUIRES package/0.1.0@user/channel
    GENERATORS cmake)

conan_cmake_autodetect(settings)

conan_cmake_install(PATH_OR_REFERENCE .
    SETTINGS ${settings}
    BUILD missing)

include(${CMAKE_CURRENT_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

...
```

P.S:
1. I cannot clone with SSH.
2. I'm not willing to set environment variables (but I can do this as a last resort).
3. I tried to use git tool instead of `ConanFile.run(...)`, but no results.
4. I tried to use popen to run `git clone`, but no results.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
I usually see that error when a git url is wrong. Could you please share the github address? Is it a private repository?

**Comment by isnullxbh** [comment]
@uilianries, yes, it is a private repository. But I'm sure that the URL is valid because it doesn't issue any errors on the installation step (I mean export/install/test).

**Comment by uilianries** [comment]
You can try:

    username = os.getenv("GITHUB_USERNAME")
    password = os.getenv("GITHUB_PASSWORD")
    self.run("git clone https://{}:{}@github.com/username/repository.git".format(username, password))

Both username and password you can be collected from env vars or a file. I believe `self.run` uses a new context and your ~/.ssh/ folder is not used.

**Comment by isnullxbh** [comment]
@uilianries, thanks! It's working.
I'm not sure that access to the .ssh directory is a reason for this error. I execute the following command:

`python -m conans.conan install package/0.1.0@user/channel`

in the terminal and via PyCharm. In the first case (terminal) I didn't get any errors, but in the second (PyCharm) - I got the same error - git return error code 128 with the description "No such device or address".

I modified the run command as following:

`self.run('strace -ff git clone <URL>')`

and execute conan install via PyCharm again. It produces the following output:

```
[pid 107949] openat(AT_FDCWD, "/dev/tty", O_RDONLY) = -1 ENXIO (No such device or address)
[pid 107949] write(2, "fatal: could not read Username f"..., 98fatal: could not read Username for 'https://gitlab.xxx.com': No such device or address
) = 98
```

As you can see, I don't get a prompt for a password because a process cannot access the input stream. It looks like it is an IDE issue (built-in terminal).

**UPD.:** Fixed by enabling "Emulate terminal in output console" in PyCharm. For CLion, I have not found a suitable solution.
