### ISSUE TITLE
[question] how to set dependencies to components

### ISSUE THREAD

**Issue by Jochen0x90h** [conan-io/conan#8842]
Hi!

I have requires = "boost/1.75.0", "glfw/3.3.3" and now want to use only some components of boost. Is this already supported for boost? When I do self.cpp_info.requires = ['boost::asio', 'glfw'] in method package_info then I get this error:
ConanException: roomcontrol/main package_info(): Package require 'glfw' not used in components requires

Any ideas?
Thanks,
Jochen

**Comment by SpaceIm** [comment]
replace by `glfw::glfw`

**Comment by AbrilRBS** [comment]
Sorry for the lack of a proper response in due time - @SpaceIm's suggestion is a valid one: components should be globally referred with the namespace between recipes, and no namespaces when requiring components in the same recipe :)
