### ISSUE TITLE
[bug] Confusing warning message when overriding requirements

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#8844]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18
  * Conan version: 1.32.1
  
I'm building from my internal fork of conan-index 2 libraries, `boost` and `GTSAM` (which depends on `boost`).
On GTSAM's recipe I have:
 ```
 self.requires(boost/1.74.0@projectX/stable)
 ```
  But my app uses both packages, and I have the requirements locked with a recipe revision, like this:
 ``` 
 self.requires(boost/1.74.0@projectX/stable#RREV1)
 self.requires(gtsam/4.0.3@projectX/stable#RREV2)
 ```
 When I build my app I get this warning which says that I'm overriding boost from gtsam with the version listed in my project:
```
  WARN: gtsam/4.0.3@projectX/stable: requirement boost/1.74.0@projectX/stable overridden by projectX/1.0.0 to boost/1.74.0@projectX/stable 
```
The problem is that is says it is overriding with the same version, username and channel so.. it is not doing anything?. My guess is that this happens because on my app I also have the recipe revision. I'm wondering if this message could be a bit clearer, maybe including the RREV if that is what is triggering this warning.

Thanks!

**Comment by memsharded** [comment]
Sorry this was not responded back then @ericriff 

Conan 2.0 has improved massively the reporting of overrides, among many other things, I am closing this ticket as solved, thanks!
