### ISSUE TITLE
[feature] Support local paths in conans.tools.get

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#8846]
Is it possible to allow using file:// URLs as input parameter for tools.get? This might be useful for testing with local archives by changing only conandata.yml

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, it might be possible. It should be added to ``tools.download()`` too.

And it must be added to the ``conan.tools.files`` get() and download().

**Comment by Nekto89** [comment]
I've just noticed that this doesn't work not only with local files but also with SMB shares and mounted folders

**Comment by Nitesh639** [comment]
I want to work on this issue.

**Comment by memsharded** [comment]
Hi @Nitesh639 

Thanks for the offer! I have assigned it to you. Conan 1.38 is due by the end of the month, if it moves forward I'll assign it to the release.

**Comment by H-G-Hristov** [comment]
That would be very useful: https://github.com/conan-io/conan-center-index/issues/10623
I guess no work was done on this one.

**Comment by memsharded** [comment]
This shouldn't be super difficult, maybe @jcar87 wants to do it?

**Comment by H-G-Hristov** [comment]
One suggestion: Please, consider supporting parsing of environment variable for home folder  (for example) in URL or something point to a relative path in the home folder, e.g:

```yaml
sources:
  "1.6.1":
    url: [
         "https://github.com/google/benchmark/archive/v1.6.1.tar.gz",
         "files://$HOME/.conan_sources/google/benchmark/archive/v1.6.1.tar.gz",
         "files://~/.conan_sources/google/benchmark/archive/v1.6.1.tar.gz",
         "files://~/.conan/sources/google/benchmark/archive/v1.6.1.tar.gz",
     ]
         sha256: "6132883bc8c9b0df5375b16ab520fac1a85dc9e4cf5be59480448ece74b278d4"
```

**Comment by memsharded** [comment]
We will not do this parsing, because this is the typical case that will have tons of edge cases, not worth. 
But it is doable directly in the ``source()`` method, like you do `` url = conan_data["sources"][version]["url"].replace("$HOME", os.getenv("HOME"))``

**Comment by H-G-Hristov** [comment]
If you implement this feature maybe you can add this as an example to the docs.

**Comment by jcar87** [comment]
Hi @H-G-Hristov - this feature will be part of release 1.51 as part of the [new file tools](https://docs.conan.io/en/latest/reference/conanfile/tools/files/downloads.html) that will be the default on Conan 2. 

A few notes:
* As per [specification](https://datatracker.ietf.org/doc/html/rfc8089) and convention, using a `file://` uri to refer to a file in the local filesystem typically has a a third slash `/` to imply the current localhost. So in most cases, this will be `file:///path/to/file.zip`, see examples [here](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_uri))
* As @memsharded  mentions, `$HOME` and `~` will not be resolved, and you would have to handle the logic of replacing it yourself. The `HOME` environment variable is not defined on all systems and circumstances, and the `~` is feature specific to shell, and will not be resolved by the python interpreter. While `os.path` provides `os.path.expanduser()` to try and handle these in a portable way, it is not applicable directly to a file URI as these start with `file://`.
