### ISSUE TITLE
[feature] Allow to add a recipe as build_requirement and requirement at the same time

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#8851]
Sometimes it is needed to add a recipe both as a requirement and a build_requirement.
For example, it is needed to add Protobuf as Opencv dependency here:

https://github.com/conan-io/conan-center-index/issues/4016
https://github.com/conan-io/conan-center-index/pull/4435

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This is already possible, if you use the 2 contexts/profiles approach. Have you checked it? Please have a look at https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#using-build-requires
