### ISSUE TITLE
[bug] When specifying an absolute profiles path using pr:h <profile> and the same profile exists in the cache, the one in the cache is chosen

### ISSUE THREAD

**Issue by jegabe** [conan-io/conan#8854]
I have conan 1.34.1 installed on a Windows machine and I'm cross-compiling a project using an ARM GCC compiler. I use splitted host/build profiles.

When specifying an absolute path to the profile, lets say C:\someDir\profile_xy  and the same profile_xy is already stored in the conan cache, let's say C:\<home dir>\.conan\profiles, conan chooses the stored profile in the cache instead of the absolute path, which is surpring since the absolute path was specified.

The conan cache I use was used with different conan versions and was updated from time to time to newer versions.

### Environment Details (include every applicable attribute)
  * Windows 10
  * GCC (details won't matter)
  * conan 1.34.1
  * Python version: 3.8.1

### Steps to reproduce (Include if Applicable)

Create a profile, copy it to the conan cache into profiles/, modify one of them and look what conan chooses

**Comment by memsharded** [comment]
Hi @jegabe 


I think your issue might have already been solved by https://github.com/conan-io/conan/pull/8685, which is scheduled to be released next 1.36 (next week). It is already in develop branch, if you want to test it running from source code (clone + ``pip install -e .``).

Please have a look and let me know, thanks!

**Comment by memsharded** [comment]
Closing this as inactive, most likely was solved long time ago. Please create new tickets if necessary, thanks.
