### ISSUE TITLE
From where did I dowload a package in local cach

### ISSUE THREAD

**Issue by AlfiCode** [conan-io/conan#8855]
We got different download possibilities:
- Released packages
- Developed not yet released but will have the same name when stored in Release
- Test, these package for test only and will never be release with that version

After downloading these packages/versions are in my local cache
These dowloaded packages are used by different project on my PC. That's why I would like to keep them and not delete and download again for the next.

If there would be a possibility (and not the release version - I don't trust) to read from a stored info-file contained in the packeg from where it was downloaded.
Then I could check easy if it's allowed to be used for my current project without deleting all and restart downloading.

Do you know any possibility like that?

**Comment by memsharded** [comment]
Hi @AlfiCode 

It is not very clear what you mean. Maybe you are talking about channels? You know that you can create packages like ``pkg/1.0@myteam/testing`` and ``pkg/1.0@myteam/stable``? They are completely different packages, with its own recipe and binaries. They can be installed at the same time in the cache and they will not overwrite each other. Each project will declare a ``requires = "pkg/1.0@myteam/mychannel"`` as they feel.

Please clarify a bit more what you mean, and if you can put it in Conan concepts, and talk about Conan commands, etc, that would help. If you haven't started to learn about conan, I would suggest doing this free training first: https://academy.jfrog.com/path/conan

**Comment by AlfiCode** [comment]
IHi@memshared
I know that this is possible and I'm creating mine that way.
But many developers do create their and you would't believe what they do (saw aleady packages in test test remote looking like final).

If I installed one package from the test remote site it is for all available in local store and will not be downloaded anymore (untill I delete this package) -> is a good thing for final packages to save download time or even work offline.

Conan is storing so much. I hope there any log- or config-file which tells me from were it came.
To relie on a name or channel somone gave is an option but not the best to find out somthing different.

**Comment by memsharded** [comment]
Still not very clear what is the issue. If you want to know from which remote every package was installed, you can run a ``conan remote list_ref`` command. Is this what you are looking for? 

Also Conan cache is a cache, it is not designed for permanent storage. If it is getting too big overtime, you can simply wipe it completely, and start from a fresh one, the necessary packages will be installed from the server.

**Comment by AlfiCode** [comment]
This would be one possibility.
But has some disadvantages:
1. you need a remote connection even you have the right package already local
2. we have more than one site -> iteration over remotes
3. not possible if you have at this moment no internet access
It would be much faster if I can ask the local package from where it was downloaded.

**Comment by memsharded** [comment]
Hi @AlfiCode 

I am not sure what you mean:
- ``conan remote list_ref`` does not use any remote connection, it stores that data in a local file.
- It will not iterate any remote, it is immediate from local cache
- It works without internet access

**Comment by AlfiCode** [comment]
Thks, this would be perfect.
But "conan remote list_ref" seems to list only the packages of the first one in my list of "conan remote list" (4 remote in list).
In latest docu I see parameter "--no-remote" in lates docu only (my current version 1.31.0 doesn't support it)
Do I miss any parameter?

**Comment by memsharded** [comment]
> But "conan remote list_ref" seems to list only the packages of the first one in my list of "conan remote list" (4 remote in list).

No, if you install recipes from another remote they will be listed there. This seems to be correctly tested, so it seems in this case you installed your recipes all from that remote.

**Comment by AlfiCode** [comment]
There were even not all packages listed I had in conanfile.txt under "[requires]"
After your comment  I removed the complete conan\data and started a new install.
Now I see all packages from conanfile.txt and also with the correct remote in "conan remote list_ref" output.

I don't know why it wasn't working with the existing "conan\data".
I would have expected that it should list all packages found under "conan\data" independent from any conanfile.txt. In case the remote doesn't exist it could list it with none.

Another possibility could be that I cleared the remotes after installing the packages and so the remote had another id. But anyhow I searched for the remote "name" and "url" in the package folder and couldn't find any of them.
I think the handling of this should be better explained in docs.

**Comment by memsharded** [comment]
> Another possibility could be that I cleared the remotes after installing the packages and so the remote had another id. But anyhow I searched for the remote "name" and "url" in the package folder and couldn't find any of them.

Yes, if you remove the remotes, then the association of the packages to the remotes is lost. This is probably what happened in your case.

**Comment by AlfiCode** [comment]
Do you know wherer I can see the association in the packages or an remote list?

**Comment by memsharded** [comment]
It is inside some metadata.json files in the cache, but you shouldn't use them directly, those are internal implementation detail, subject to change at any time.

**Comment by AlfiCode** [comment]
Perfect, I saw in beside metadata.json in package chache beside remote the 'remote name'. 
Can I assume that the relation remains valid as long as the remote name stays the same?
That means if I keep a package of a remote named "alf-test" remove this remote  "alf-test" and later add a remote with name "alf-test" the packege should belong to that remote?
Is there any other validation or mechanism (e.g. deleting meta files) behind it?

I just saw that the old metadata.json had beside remote 'null'. Is it set when this remote gets removed?

**Comment by memsharded** [comment]
I am closing this ticket as outdated.

Conan 2.0 has removed the association between packages in the cache and remotes. In Conan 2.0 the packages have unique identifiers, so it is possible to track and search packages with exactly the same hash in the different remotes. Overall the decentralization works much better in 2.0, the update flows are more intuitive.
