### ISSUE TITLE
SystemPackageTool improvement suggestions

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#886]
Hi,

`SystemPackageTool` is a good tool, however it has some shortcomings:

- Failing to `install` a package (for whatever reason) should raise an exception as an unsatisfied system requirement likely will cause problems later. That would also be more consistent with how most conan commands report errors
- `install` should first check to see if the specified package is installed or not. If it's already installed there's no need to use sudo, so the user doesn't have to type the password
- `update` shouldn't be called if a required package is already installed. `install` could call `update` internally when an installation is required, and also set an internal value `_is_up_to_date=True` to not issue multiple `update`s for multiple calls to `install`
- Sometimes same/similar packages are named different for different package managers/repositories. There should be a way to pass multiple names to `install` with OR logic: only one of the listed packages needs to be installed. Examples: 
`installer.install(["somelib-debian-dev", "somelib-dev"])`
`installer.install(["libfoo-4.4-dev", "libfoo-4.2-dev"]) # Packages are searched left-to-right`
It would be convenient to even support some kind of wildcards, however I think that would be much harder to implement portable with a single interface so I won't suggest that at the moment.

Any thoughts?

**Comment by memsharded** [comment]
Yes, I agree. ``SystemPackageTool`` in its current state was the first approach to this problem, the first iteration, but it is likely that it can be largely improved.

All those suggestions seems good for me.

**Comment by sixten-hilborn** [comment]
I'll start working on these improvements.

**Comment by memsharded** [comment]
Great! I think @rietmann, might be interested in these improvements too.

**Comment by memsharded** [comment]
Thanks very much Sixten for this great job. Merged to develop, will be released in next 0.20
