### ISSUE TITLE
When I upload the conan package to artifactory where i can see the channel in the artifactory conan gui.

### ISSUE THREAD

**Issue by cpenugon** [conan-io/conan#8862]
I  have uploaded  hello/0.1@user/testing  as per the training program present https://academy.jfrog.com/path/conan/conan-essentials/583137

when i see in the local artifactory in conan repo using browser where i can see the channel ie. testing in this case.

its getting created like 
   myconanrepo
      user
        hello
           0.1

where i can the channel -- ie. 'testing' in this case.

when i do conan search "*" -r myconan
its showing the channel. I would like to  know in browser using GUI where i can see the channel.

**Comment by memsharded** [comment]
The standard folder "layout" in the server is:

user/pkgname/version/channel/recipe_revision/export (conanfile.py)
user/pkgname/version/channel/recipe_revision/packages/package_id/package_revision (cona_package.tgz)
