### ISSUE TITLE
[feature] More specific file extension for primary configuration file

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#8865]
Could we deprecate `conanfile.txt` in favor of `conanfile.ini`? This would help text editors to syntax highlight better.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @mcandre 

I am sorry, but I am afraid this is not possible, this would be a massive breakage for thousands of Conan users that would need to rename their files and fix their CI pipelines scripts, for a potential very minor UX improvement (the conanfile.txt is not really a .ini file completely, it looks like it, but it is not, so some parts will not be syntax-highlighted correctly)

You can already use ``conanfile.ini`` if you want, no problem, just give Conan the filename to use:
```bash
$ conan install conanfile.ini 
```
