### ISSUE TITLE
[FR] Integrate better with update-alternatives, cc, c++

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#8866]
On Ubuntu, conan is picking up the wrong compiler by default.

I have configured update-alternatives to use clang and clang++. The `cc` and `c++` binaries already point to clang and clang++. But still, somehow conan's compiler detection system ignores this and defaults to gcc anyway.

I think I can explicitly configure conan to prefer certain toolchains. But I would rather conan do the right thing out of the box.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> On Ubuntu, conan is picking up the wrong compiler by default.

Conan is not a build system, and it is not an environment manager. Conan does not pick any compiler or injects it into the build. It is the responsibility of the build systems and environment to define that. What Conan can do is to define ``[env]`` environment variables in profiles, to help build systems use the intended compiler. 

It is the responsibility of the user to define the correct profiles for the current configuration, and to define the environment correctly.

**Comment by stevenwdv** [comment]
> Conan does not pick any compiler or injects it into the build.

I don't think this is fully correct (at least not anymore). Namely, `conan profile detect` and the `detect_api` both prefer `gcc` over `clang`, even if `cc`/`c++` binaries point to `clang`/`clang++`. Only setting `CC/CXX` envvars works. Could you reconsider this?

**Comment by memsharded** [comment]
We might explore the possibility of processing ``cc`` in the profile detection, see https://github.com/conan-io/conan/pull/16074. Please not that this is exploratory, not guaranteed that it will be merged, it has some risks.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/16074 was merged, it will be in next Conan 2.3
