### ISSUE TITLE
[feature] Automatically fallback onto source builds when binaries are unavailable

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#8867]
Could conan please automatically apply --build missing, so that more packages "just work" without having to fuss with so many flags? Right now conan simply gives up on packages that aren't providing binaries. Not a fun experience for newbies.

UNIX users can work around this limitation by aliasing to force the --build missing flag. However, that would risk divergence between local vs. remote application builds. And such aliasing is often unavailable for Windows users. Ideally, conan simply applied --build missing out of the box.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @mcandre 

Thanks for the suggestion. This is a deliberate design decision. The default is failing when binaries are missing, and it will keep being the default one. Having ``--build=missing`` activated by default could result in CI pipelines building things over and over, and what is worst, hiding problems in the builds upstream, and this is more problematic than the opposite. Even developers at teams should find pre-build binaries for their dependencies most of the time, and if they don't they need to be aware of it.

The error message when binaries are not found is descriptive enough, and it even provide a link to the faq: https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package. Even if not optimal for newbies that should give enough guidelines for them to find their way, and the current default is a good one for the majority of Conan users.

**Comment by memsharded** [comment]
Closing this as responded.
