### ISSUE TITLE
Inconvenient dependency linking in CMake

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#887]
Hi,

The new `cmake_multi` generator adds some boilerplate to `CMakeLists.txt` when linking to the libraries. This is how it is supposed to be done according to the documentation:

```
foreach(_LIB ${CONAN_LIBS_RELEASE})
    target_link_libraries(say_hello optimized ${_LIB})
endforeach()
foreach(_LIB ${CONAN_LIBS_DEBUG})
    target_link_libraries(say_hello debug ${_LIB})
endforeach()
```

However if the same CMake file is supposed to support `cmake` generator as well this code will grow to something like:

```
if(CONAN_LIBS)
    target_link_libraries(say_hello ${CONAN_LIBS})
else()
    foreach(_LIB ${CONAN_LIBS_RELEASE})
        target_link_libraries(say_hello optimized ${_LIB})
    endforeach()
    foreach(_LIB ${CONAN_LIBS_DEBUG})
        target_link_libraries(say_hello debug ${_LIB})
    endforeach()
endif()
```

Things are slowly going out of control. If I use the targets syntax instead (if my cmake version supports it) I still need to list all my dependencies in both CMakeLists.txt and my conanfile:

```
target_link_libraries(say_hello CONAN_PKG::Hello1 CONAN_PKG::SomeLib CONAN_PKG::SomeOtherLib ...)
```

What about having something like this that just links all libraries:
```
conan_target_link_libraries(say_hello)
```
which internally links to all `CONAN_LIBS` or `CONAN_LIBS_RELEASE` or debug etc depending on the generator. If targets are preferred there could be some `CONAN_PKG::ALL` or `CONAN_ALL_PKGS` or `${CONAN_TARGETS}` (both styles can be supported).
Any thoughts?

**Comment by memsharded** [comment]
The first part, the idea and the implementation of the PR, sounds good.

Regarding the use of ``${CONAN_TARGETS}`` I am not sure, precisely the use of targets is because users want to control which targets they are linking and typically not want to link with all. I guess that just creating the variable won't harm, is that the reason why you didn't try to automate ``conan_target_link_libraries()`` to link with the targets too? (that can be done, just checking the existence of ``CONAN_TARGETS``)

**Comment by sixten-hilborn** [comment]
Yes I didn't put `CONAN_TARGETS` in `conan_target_link_libraries()` as it isn't needed there in the same way, but I'll update it for consistency!
Maybe `CONAN_TARGETS` won't be used like you say, but it opens up some possibilities, like linking to most targets except some specific (`list(REMOVE_ITEM ...`).

**Comment by memsharded** [comment]
Yes, sure. So for me, it is good. If you think is better to update ``conan_target_link_libraries()`` for consistency, then I'll wait for the changes to merge it. Thanks!

**Comment by sixten-hilborn** [comment]
Sure, I'll add it later today or tomorrow. :)
