### ISSUE TITLE
[bug] Overridden requirement "cannot be found in lockfile"

### ISSUE THREAD

**Issue by harendt** [conan-io/conan#8870]
When overriding a requirement like this
```python
def requirements(self):
    # libd has a transitive dependency on liba
    self.requires("libd/[>0.0 <1.0]@user/testing")
    # override required version of liba
    self.requires("liba/0.1@user/testing", override=True)
```
and using lockfiles like this
```bash
mkdir build && cd build
conan lock create ../conanfile.py --lockfile-out app1.lock
conan install .. --lockfile app1.lock
```
I get the following error from Conan
```
ERROR: Require 'liba' cannot be found in lockfile
```

The error can be avoided by setting `override=False` (the default value for this argument). But this workaround is not really helpful because it does not work when `general.error_on_override` is set to `True`.

### Environment Details
  * Operating System+version: Ubuntu 20.04.1
  * Compiler+version: GCC 9.3.0
  * Conan version: 1.35.0
  * Python version: 3.8.5

### Steps to reproduce

1. Checkout latest master (I used `51a98d5`) of https://github.com/conan-io/examples.git.
2. Apply the following patch
   ```
   diff --git a/features/lockfiles/ci/app1/conanfile.py b/features/lockfiles/ci/app1/conanfile.py
   index 7b434ce..f51e73e 100644
   --- a/features/lockfiles/ci/app1/conanfile.py
   +++ b/features/lockfiles/ci/app1/conanfile.py
   @@ -5,4 +5,6 @@ required_conan_version = ">=1.28"
   
    class App1Conan(ConanFile):
        settings = "build_type"
   -    requires = "libd/[>0.0 <1.0]@user/testing"
   +    def requirements(self):
   +        self.requires("libd/[>0.0 <1.0]@user/testing")
   +        self.requires("liba/0.1@user/testing", override=True)
   ```
3. Run `python3 ./build.py` in `examples/features/lockfiles/ci`

### Logs

```
$ git clone https://github.com/conan-io/examples.git
$ cd examples
$ git checkout 51a98d5
$ git apply path/to/patch # See "Steps to reproduce"
$ cd features/lockfiles/ci
$ python3 build.py
[...]
*********** Running: conan install app1/0.1@user/testing --build=app1/0.1@user/testing --lockfile=locks/app1_release.lock --lockfile-out=locks/app1_release_updated.lock
Using lockfile: '/home/bharendt/bug-report/examples/features/lockfiles/ci/locks/app1_release.lock'
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: Require 'liba' cannot be found in lockfile
Traceback (most recent call last):
  File "build.py", line 120, in <module>
    ci_pipeline()
  File "build.py", line 110, in ci_pipeline
    run("conan install %s --build=%s --lockfile=locks/app1_release.lock "
  File "build.py", line 12, in run
    raise Exception("Failed command: %s" % cmd)
Exception: Failed command: conan install app1/0.1@user/testing --build=app1/0.1@user/testing --lockfile=locks/app1_release.lock --lockfile-out=locks/app1_release_updated.lock
$ cat locks/app1_release.lock
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "libb/0.2@user/testing",
    "package_id": "39b0b5fad32aaf2a462d27d4282d12c08bd6c818",
    "prev": "0",
    "requires": [
     "1"
    ],
    "context": "host"
   },
   "1": {
    "ref": "liba/0.1@user/testing",
    "package_id": "4024617540c4f240a6a5e8911b0de9ef38a11a72",
    "prev": "0",
    "context": "host"
   },
   "3": {
    "ref": "app1/0.1@user/testing",
    "package_id": "15d2c695ed8d421c0d8932501fc654c8083e6582",
    "requires": [
     "4"
    ],
    "context": "host"
   },
   "4": {
    "ref": "libd/0.1@user/testing",
    "package_id": "b03c813b34cfab7a095fd903f7e8df2114e2b858",
    "prev": "0",
    "modified": true,
    "requires": [
     "0",
     "5"
    ],
    "context": "host"
   },
   "5": {
    "ref": "libc/0.1@user/testing",
    "package_id": "39b0b5fad32aaf2a462d27d4282d12c08bd6c818",
    "prev": "0",
    "requires": [
     "1"
    ],
    "context": "host"
   }
  },
  "revisions_enabled": false
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Release\ncompiler=gcc\ncompiler.libcxx=libstdc++\ncompiler.version=9\nos=Linux\nos_build=Linux\n[options]\n[build_requires]\n[env]\n"
}
```

Note the `requires` field in node `3` (`app1`). `app1` has only node `4` (`libd`, for which `override` is set to `False`) in its `requires` array, but not node `1` (`liba`, for which `override` is set to `True`).

Setting `override` to `False` for `liba` in `features/lockfiles/ci/app1/conanfile.py` will fix the issue (as long as `general.error_on_override` is set to `False`).

**Comment by solvingj** [comment]
@memsharded i thought we did a change a few versions ago where the lockfile is not enforced/applied until the graph is completely resolved, so that options and settings in config/config_options could all resolve successfully. It seems like this would have been fixed by that as well.  I guess not?

**Comment by harendt** [comment]
> i thought we did a change a few versions ago where the lockfile is not enforced/applied until the graph is completely resolved

Are you referring to this change #8054? I think that's unrelated. In this new issue the graph is already complete. And the missing library (`liba`) is actually included in the lockfile. But it is not referenced in the "requires" field of `app1` - probably because it's an overridden dependency (requirement with `override=True`). This causes the issue because the following lines assume that all requirements of a node are listed in the "requires" field of that node: https://github.com/conan-io/conan/blob/1.35.0/conans/model/graph_lock.py#L529-L533.
