### ISSUE TITLE
[feature] User field length increase or specification

### ISSUE THREAD

**Issue by delrizzo** [conan-io/conan#8877]
We are integrating conan into our build flow, using gitlab ci/cd. We have many repos to integrate, so we are attempting to set up an instance-wide conan package repository via gitlab. The issue is that in order to use conan in an 'instance-wide' fashion, gitlab forces one to use the 'user' field as a +-delimited path to the repository within the group. Our group hierarchy can be quite long. As you can imagine, this gets us past 50 characters fairly quickly.

I have seen other issues related to length here, but not this in particular. Do I need to change to setting up a conan package repo for each project individually in gitlab (which will be a pain), or is it possible to configure the allowable length of the user field (which I am sure comes with its own pain).

- [ X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Hi @delrizzo,

Yes, the path limitation is something not configurable and changing that will have other implications in other areas like long paths in the cache and hitting issues especially in windows and so. Currently, the client is not prepared to handle that change and this is a limitation of the Gitlab server implementation regarding the `user` field. I'd suggest contacting them for support as well.

**Comment by delrizzo** [comment]
Thanks for the reply. 
Ironically, gitlab is currently experiencing issues with project-based package registry also, so neither solution works for us at this time. In looking at their forum, it seems they are actively working on a solution, but time will tell.
We've decided to move forward at this time using an external registry... but it sure would be nice to have everything stored together.

**Comment by memsharded** [comment]
One of the reasons that increasing the name, version, user, channel fields limits could be dangerous is server implementations, that besides Artifactory and conan_server, now there are several of them out there. Package registries can become very large soon, we are aware of Conan users with thousands of packages (millions of artifacts), and they typically implement DB for storing the references. Fetching packages, searching, or resolve version ranges requires querying the servers by these fields, and it is very possible that implementors have optimized column sizes and indexes based on knowledge of the 50 chars limits.

This could be a very big pain, I'd prefer to wait until Conan 2.0 to consider modifying this limit.

**Comment by delrizzo** [comment]
That's fair. I think that I wouldn't advocate changing it in light of that
information. We will find a different solution, or inspire gitlab to be
better... thanks.

--
Dave Del Rizzo

**Comment by danimtb** [comment]
I am closing the issue as answered. Thanks!
