### ISSUE TITLE
[feature] Give option to use symlinks instead-of/in-addition to conan_link on windows

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#8882]
Currently when a package uses short_paths the folder in .conan/data contains a .conan_link file containing the shortened path. Windows 10 in developer mode supports symlinks. It would be nice to have a symlink to that folder for easier navigation as an option.

- [ X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @rconde01 

Conan 2.0 will have a cache that is always short, to be able to store multiple revisions. So this will hopefully not be an issue.

**Comment by rconde01** [comment]
hmm...how do you find your package cache then?

**Comment by memsharded** [comment]
> hmm...how do you find your package cache then?

with Conan commands, like "conan info" or other new ones.

**Comment by rconde01** [comment]
Seems like that makes the problem (of navigating) worse. In that case it might be nice to have a second directory maintaining symlinks to packages so you can navigate via command line or file browser.

**Comment by memsharded** [comment]
Having a cache that can store multiple revisions, gives no other option, it is the only way. We will maintain the mappings in a DB, for many cases, navigating will not be that intuitive, because you will get folders with revisions, and it is not intuitive to navigate to the latest one anyway.

**Comment by rconde01** [comment]
why isn't the revision just another sub-folder in the path?

**Comment by memsharded** [comment]
Because there will be 3 subfolders, recipe revision, package id, package revision. If you have a bunch of dependencies, the length of include paths, library paths can overflow the compiler command line length limit, for example. Not to say that this is completely impossible for Windows (not all Windows can enable the long paths), and we want to implement a common solution for all platforms.

**Comment by rconde01** [comment]
But I'm just talking about browsing, not building. So do whatever you want for building, and then have a mirror directory structure with symlinks to the real dirs for browsing purposes.

**Comment by memsharded** [comment]
> But I'm just talking about browsing, not building. So do whatever you want for building, and then have a mirror directory structure with symlinks to the real dirs for browsing purposes.

Well, it is simply too early for even considering this. We are just starting with the design of the cache 2.0, which has some big challenges, not only the structure/layout, but also things like concurrency, cleaning policies based on least recently used or timestamps, etc. Navigating the cache is a secondary debugging use case that can be initially satisfied by some ``conan cache path <ref>`` command that will return the folder to locate that thing.

**Comment by rconde01** [comment]
sure - just keep it in mind i guess.

**Comment by memsharded** [comment]
> sure - just keep it in mind i guess.

Of course. We know this is a problem, so we will need to figure out a reasonable UX for inspecting the cache for the new 2.0 design later down the road before releasing 2.0.

**Comment by memsharded** [comment]
``develop2`` branch already implements a cache without ``short_paths``, because it already uses a hash based approach for folders, so they are always short, so this no longer applies, can be closed.
