### ISSUE TITLE
[bug] Obscure message of compiler mismatch between conan settings and CMake + Visual Studio

### ISSUE THREAD

**Issue by Artalus** [conan-io/conan#8891]
`conanbuildinfo.cmake` file contains this `message()` call, reporting version mismatch between Conan settings and CMake detection:
```cmake
    conan_split_version(${CMAKE_CXX_COMPILER_VERSION} VERSION_MAJOR VERSION_MINOR)
    ...
    message(FATAL_ERROR "Detected a mismatch for the compiler version between your conan profile settings and CMake: \n"
                        "Compiler version specified in your conan profile: ${CONAN_COMPILER_VERSION}\n"
                        "Compiler version detected in CMake: ${VERSION_MAJOR}.${VERSION_MINOR}\n"
```
It works fine the sensible world of compiler versions, but results in obscure nonsense when using Visual Studio:
```
  Detected a mismatch for the compiler version between your conan profile
  settings and CMake:
  Compiler version specified in your conan profile: 15
  Compiler version detected in CMake: 18.0
```
As inexperienced Visual Studio user, one might think that something is clearly broken here, since there is no VS that contains "18" in its name, and we have VS 2017 installed, not VS 2015. However, the realms of Microsoft Visual Studio versioning are grim hellscapes:
- Visual Studio is **named** `2019` (or 2013)
- but its **internal version** is `16.9.4` (or 12.0.40629 update5)
- and it compiles stuff via **toolset** of version `14.2`, often aliased as vc142 (or 120)
- also the `cl.exe`'s **compiler version** is `19.28.29914` (or 18.00.40629)

`~/.conan/settings.yml` contains these possible `compiler.version` options for VS:
```yaml
    Visual Studio: &visual_studio
        version: ["8", "9", "10", "11", "12", "14", "15", "16"]
```
From my understanding, these are based on the "visualstudio.exe version" values - however, cmake bases its `CMAKE_CXX_COMPILER_VERSION` variable on "cl.exe version", which... does not exactly correlate. Note that in the mean time, the _compiler mismatch check itself_ is correct:
```cmake
    if(CMAKE_CXX_COMPILER_ID MATCHES MSVC)
        if(
            # 1920-1929 = VS 16.0 (v142 toolset)
            (CONAN_COMPILER_VERSION STREQUAL "16" AND NOT((MSVC_VERSION GREATER 1919) AND (MSVC_VERSION LESS 1930))) OR
            # 1910-1919 = VS 15.0 (v141 toolset)
            (CONAN_COMPILER_VERSION STREQUAL "15" AND NOT((MSVC_VERSION GREATER 1909) AND (MSVC_VERSION LESS 1920))) OR
            # 1900      = VS 14.0 (v140 toolset)
            (CONAN_COMPILER_VERSION STREQUAL "14" AND NOT(MSVC_VERSION EQUAL 1900)) OR
            # 1800      = VS 12.0 (v120 toolset)
            (CONAN_COMPILER_VERSION STREQUAL "12" AND NOT VERSION_MAJOR STREQUAL "18") OR
...
          )
            conan_error_compiler_version()
        endif()
```
So in the example above the mismatch "Conan requires `visual studio 2017`, but CMake project uses `visual studio 2013` instead" is detected correctly - it is only the report message that confounds unprepared minds. I've consulted several different programmers on this topic in last couple of months, and decided it was probably time to finally report something upstream :)
Please feel free to close this issue if it duplicates something that has already been reported - I checked issues and pull requests for keywords that came to mind, but failed to find anything existing on this topic.

I am planning to provide a PR with fixes in nearby future, but if someone has ideas about what should be printed to the user, I'd be glad to discuss things.

**Comment by memsharded** [comment]
Hi @Artalus 

While it is true this message could be improved, I think maybe it is not worth the effort:

- A new ``msvc`` compiler setting has been added, that model the compiler version, not the IDE version: https://docs.conan.io/en/latest/reference/config_files/settings.yml.html#msvc
- That error is provided only in the old integrations. New integrations that will survive in Conan 2.0 (https://docs.conan.io/en/latest/reference/conanfile/tools.html) doesn't implement this check yet.
- Beware that support for ``msvc`` compiler is only implemented in the new ``conan.tools`` helpers.

If any effort is being done, it probably should be added to the new ``CMakeToolchain`` class. 
So far the ``msvc`` version is added to the toolset in the ``conantoolchain.cmake`` file, so it will be difficult to have a mismatch in this one. Checking what can be done for gcc/clang and other compilers inside the ``CMakeToolchain`` would be great.

**Comment by Artalus** [comment]
The new generator definitely sounds good, but guessing from my experience, people might will be stuck with old one for quite some time after 2.0 released (not even saying about adoption period).
My intention was only to provide more readable data about MSVC in the existing `conanbuildinfo.cmake` creation process. I have absolutely zero experience with `msvc` generator, only seen it once or twice in `settings.yml` from modern installations of Conan.

**Comment by memsharded** [comment]
This generator has been removed in 2.0, launched now 1 year ago, so it will no longer receive updates in the 1.X releases, so I am closing this issue as outdated.

A different story is if we want to try to add the compiler checks in Conan 2.0, but as the integration happens with a toolchain, and a toolchain in CMake doesn't have the compiler defined yet, it becomes impossible to do this. In general it was quite a heavy feature with some rough edges and problems that served exclusively as a protection against some mismatches, so given everything, this is not planned in the short term.
