### ISSUE TITLE
conan test does not run source() in test_package's conanfile.py

### ISSUE THREAD

**Issue by chausner-audeering** [conan-io/conan#8892]
We use the `source()` packaging step to download resources that are required for building some of our libraries. This has been working well so far but now we also have some tests in `test_package` that also need certain resources for the execution of the tests. But it turns out the `source()` method defined in `test_package/conanfile.py` is not executed when running `conan test`. ~~I tried to workaround this by performing the download inside of `build()` but here I encountered another unexpected issue: `self.conan_data` returns the `conandata.yml` from the test target, not the test package. (We use `conandata.yml` for storing URLs to the resources we need to download).~~

Edit: The latter was my mistake, unfortunately. I can confirm `self.conan_data` returns the `conandata.yml` of the test package, as expected.

I guess we could also find workarounds for that but it starts to become obvious that we are trying to do something that was not intended with the current design of test_package. Do you have any suggestions for a better way to download these resources as part of `conan test`?

/cc @Linux13524

**Comment by memsharded** [comment]
> I guess we could also find workarounds for that but it starts to become obvious that we are trying to do something that was not intended with the current design of test_package. Do you have any suggestions for a better way to download these resources as part of conan test?

Hi @chausner-audeering 

You are right, this was never considered as a use case. Because the ``test_package`` functionality is implemented with a single ``main.cpp`` simple file, and the simplest approach by far is to put it directly inside the ``test_package``. Managing it elsewhere is an extra complexity that doesn't add much. Is it possible that you are maybe abusing a bit the ``test_package`` functionality. Recall that these are not unit, functional or integration test, it is designed to be a check that the package is correctly created: the headers are packaged, the libs are packaged, and in the expected folders so they are found and can be used, to avoid typical packaging errors. A very simple ``main.cpp`` will catch most of the possible packaging mistakes.

**Comment by chausner-audeering** [comment]
Hi @memsharded,

thanks for your quick answer! Yes, we are currently running all our unit tests as part of `test_package` and already considered moving them to the main package in the future. That would certainly also fix this issue for us.

We are using the `source()` step not for configuring the source code itself but rather for restoring resources that are needed to run the tests. E.g. we run the tests on larger audio files which we don't want to commit directly. We use `source()` to download them separately and store them in a location where the tests can find them.

**Comment by memsharded** [comment]
Hi @chausner-audeering 

I would like to suggest another alternative: 
- put those resources in a Conan package.
- You can remove ``settings``, if the package resources are multi-platform, or you can have platform specific resources as well. 
- Have your ``test_package/conanfile.py`` have a ``requires`` to that specific package. This will be very efficient if those resources are used in multiple packages to test.
- Several advantage: you can version those resources, they will be stored in the cache automatically, easy to track in the server side too.
- The ``test_package/conanfile.py`` can access those files in different ways, like doing a copy with ``imports``, or with ``self.deps_cpp_info["mydatapkg"].root_path``, for example.

This approach will still be valid (even more useful) if you move the unittest inside the package and not in ``test_package``.

What do you think?

**Comment by chausner-audeering** [comment]
Thanks for that suggestion. I agree this sounds like a good alternative in general, although it does not work in our case because we already have a custom solution for the packaging of these resources which we cannot change. But I will keep your suggestion in mind because we may have also other usecases where we could apply something like what you proposed.

I think for us the best solution is to move the tests into the main package. Thanks a lot for your help and feel free to close this issue or keep it open, as you prefer.

**Comment by memsharded** [comment]
I am going to leave it open, it could be possible to call the source() method, so lets keep it open for a while in case some more users could be interested, and label it as something to consider "look into". Thanks for the feedback!

**Comment by memsharded** [comment]
This doesn't seem to have got more demand or traction, I am going to close it as not planned/inactive.

It is still possible to force the download of things in the test_package ``build()`` method, but local ``source()`` that doesn't execute in the cache is a bit more challenging to manage, doesn't seem worth the complexity.
