### ISSUE TITLE
Consider adding symlinks for "conan latest"

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#89]
Hi,

I ended up having a couple of red builds with the transition from conan 0.5 to 0.6[1],[2]. Which made me wonder: I always want to track "conan latest" in these machines so it would be great to be able to point to a download link that always gives latest when a new release is made. This could be achieved by means of a symlink. 

Let me know if you think this is worthwhile; if so I can help test it.

Cheers

Marco

[1] https://travis-ci.org/DomainDrivenConsulting/dogen/builds/101603081
[2] https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.46

**Comment by lasote** [comment]
Hi, 

Yes, it's too necessary, I'm looking for the best choice.

Thanks!

**Comment by lasote** [comment]
Ready!

You can use those urls, we will point them to the latest installer:

    http://downloads.conan.io/latest_debian
    http://downloads.conan.io/latest_windows
    http://downloads.conan.io/latest_macos

I will update the docs too. (download, travis and appveyor)

Thanks again for your suggestions and test conan! :+1:

**Comment by mcraveiro** [comment]
Thanks a lot for the prompt response! Shipped [1], let you know if I hit any issues - but looks good.

Cheers

[1] https://github.com/DomainDrivenConsulting/dogen/commit/56effb98612c6a67be63806cf23eecddd515dfc0

**Comment by mcraveiro** [comment]
Confirmed - works fine. Cheers
