### ISSUE TITLE
[feature] Loosen CLI parsing restrictions

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#8906]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Could we please setup a slightly more flexible parser? Modern CLI frameworks make the equals sign (`=`) optional for flags, that we can use a space instead. But conan often fails when a space is used.

**Comment by czoido** [comment]
Hi @mcandre,
Thanks for the feedback, currently we are using python's standard argparse module to parse the CLI. It should work with spaces or equals sign, could you please provide an example where it's failing?
We are currently in the middle of the redesign of the CLI for Conan 2.0 so this is something we will take into account.

**Comment by memsharded** [comment]
Closing this as stale. Conan arg-parsing is fully delegated to Python argparse library, there is very little we can do there anyway, and changing cli library would be too much, thanks for the feedback.
