### ISSUE TITLE
NTFS can be case sensitive but conan can't handle this

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8913]
According to [this article](https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/) NTFS offers case-sensitivity option per directory basis but there's a hardcode in conan's codebase on that thing. I turned on case-sensitivity in my conan.storage path to avoid case-sensitivity issues and that didn't help me because of that: 
https://github.com/conan-io/conan/blob/b703156e63f80234dc1fe2d30bd8745f70ee299c/conans/client/cache/cache.py#L38-L40

**Comment by lasote** [comment]
Hi @xahon! Thanks for reporting. I'm checking out that article and seems interesting but it worries me when it says:

- `The case sensitivity flag only affects the specific folder to which you apply it. It isn’t automatically inherited by that folder’s subfolders.`
-  workaround: `As long as you create folders from the Linux environment, they’re created with the proper case sensitivity settings and you never need to touch the fsutil.exe command.`

Looks like Conan thought python won't be able easily to manage the entire cache with case sensitivity, so probably the hardcoded code seems reasonable. 

If you manage to keep an "automatic recursive" Conan cache folder and it is doable, maybe you can help us to debug how it works by removing the hardcoded check.

**Comment by memsharded** [comment]
In any case, 2 important points:

- Conan 2.0 will be lowercase only, that is already approved in the tribe discussion: https://github.com/conan-io/tribe/blob/main/design/017-lowercase-references.md
- The new cache for Conan 2.0 will abstract away the references, to be able to store multiple revisions. So case insensitive filesystems won't be an issue.

**Comment by xahon** [comment]
@lasote 
Ok, NTFS case-sensitivity is a useless feature from Microsoft due to the first statement you wrote
I will wait for conan 2.0 with architectural fix about this
