### ISSUE TITLE
"options.shared" doesn't exist during "conan install"

### ISSUE THREAD

**Issue by dmitry-zakablukov** [conan-io/conan#892]
Good day.

For the following conanfile.txt:
```
[requires]
zlib/1.2.8@lasote/stable

[generators]
visual_studio
```
and for the following command:
```
conan install -o shared=False
```
I get an error:
```
ERROR: 'options.shared' doesn't exist
'options' possible configurations are none
```

If I specify an option in the "options" section like this:
```
[options]
zlib:shared=False
```
then no error occurs for the command `conan install`.

Best regards, Dmitry.

**Comment by memsharded** [comment]
When you are using a ``conanfile.txt``, you cannot define options for it, as there is no ``build()`` or ``package()`` method you could use the options in them. In general trying to set an option to a package or conanfile that doesn't declare them, is an error.

You can do also in the command line:

```bash
$ conan install -o zlib:shared=False
```

which is the correct way to specify that you want zlib as shared library.

**Comment by dmitry-zakablukov** [comment]
Thanks for the explanation!

**Comment by memsharded** [comment]
You are welcome!
