### ISSUE TITLE
[question] Using conan as library inside another python scripts

### ISSUE THREAD

**Issue by jenia90** [conan-io/conan#8925]
Hi all, I would like to write a python script that would extend conan for my own use cases, i.e., import it as a module in my own scripts. Is it something that is supported? If yes, is there any documentation available? Thanks in advance :+1: 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Hi @jenia90,

Currently, Conan client offers a python API but it is not documented and we have no commitment to make it stable so we don't recommend its usage on production. The best way to integrate conan in a script would be to stick to the command line and parse the results using the output in json with `--json` flag.

Anyway, not sure what you mean by "extending", but Conan already offers different ways of customization depending on what you have in mind. To name a few:

- Hooks: Allow users to write small python scripts that can be shared with the Conan configuration to perform pre/post command tasks.
- Generators: Allow users to write a custom generator that can translate the graph information to whatever format you need to integrate your build system of choice.
- Python requires: Allow users to write recipes with python code that can be reused by other recipes to avoid repetition of code.

See the documentation here: https://docs.conan.io/en/latest/extending.html

I'd strongly recommend to use the existing features whenever possible and provide us with feedback for improvement!
Thank you

**Comment by jenia90** [comment]
@danimtb Thank you for you answer! Yeah, I meant that I want to integrate it in my own script. I've been going through the source and nitpicking the functions that might be useful for my use-cases. However, if you say that it is unstable and subject to change then I will indeed try the CLI approach. Thank you again for your detailed explanation. Hope I find ways to contribute to this important project! :)

**Comment by danimtb** [comment]
you are welcome! I hope you find Conan useful and do not hesitate to open an issue with questions or feedback during your process 😄
