### ISSUE TITLE
[question] Recommended way to get binaries for all required packages and transitive dependencies

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#8938]
Given the following scenario:
- We have a project which requires several conan packages, configured in one or more conanfile.py files
- Many of those requirements have non-default options

We want...
- ...all recipes and transitive dependencies to have binary packages on our conan server
- ...to build all those packages on our target platforms so that e.g. GLIBC versioning is not an issue

I see this as a possible way to accomplish this:
1. Configure a machine with the required tools (compilers etc.)
2. Clear the conan cache
3. For each conanfile.py, build the packages via `conan install --build=all --profile my_profile conanfile.py`
4. `conan upload -r my_conan_server --all "*"`

This approach has several problems:
- only want to build binaries not currently in our cache, but this builds everything...so adding 1 new dependency is massively inefficient
- if different conanfile.py use the same package and settings, will needlessly build multiple times
- overwrites binary packages already on the server?

Hopefully there's a better way to do this? I could think of some new commands and switches which could facilitate this, but let me know if there's already something better before I go through explaining those.

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by rconde01** [comment]
Looks like the answer might be with lock files...but still learning

**Comment by memsharded** [comment]
Sorry this was not responded back then.

This might be outdated, now there are ``deployers``, ``lockfiles`` etc.
Closing as outdated, please create new tickets if necessary. Thanks for the feedback.
