### ISSUE TITLE
[question] Setting editable layout directories for find_package components

### ISSUE THREAD

**Issue by jlemein** [conan-io/conan#8940]
I am introducing conan in the company I work for. One of the things to deal with now is that we occasionally need to work in multiple repositories at the same time (previously done using sub-modules). This is needed to update the library API and at the same time update the repository that consumes the library.

According to the conan documentation, this can be achieved using conan editable packages together with layout files. When used with packages that do not make use of components, the editable package include directories are picked up correctly. In this case I link my targets using `CONAN_PKG::mypackage`.

The package that I am working on now is using components. I had to use the find_package generator in order to link the components to the targets. My CMake file will contain the following snippet to link the component:

```
find_package(mypackage REQUIRED COMPONENTS base v0)
target_link_library(mytarget PRIVATE mypackage::base)

```
In this case I would also like to use the conan editable layout file, but it seems that the `[includedirs]` are not taken into account for components. My layout file looks as follows:

```
[includedirs]
src/base/export
src/v0/export
```

How can I set the includedirs per component for use with conan editable packages?

**Comment by wer14** [comment]
Did you put the package to editable mod?

**Comment by memsharded** [comment]
Note for users: Please check the new recipe ``layout()`` method in https://docs.conan.io/en/latest/developing_packages/package_layout.html, introduced in Conan 1.37.

And https://docs.conan.io/en/latest/reference/conanfile/tools/layout.html

It is intended to supersede the layout files, like the one described above with the ``[includedirs]``

**Comment by jlemein** [comment]
@memsharded Thanks, the new recipe layout() more or less seems to work. It can now find my includes and libraries in build directory. I have some issues with an already reported bug, regarding the import-function but I see you already have a fix that is coming soon.

One thing that I still have issues with is that I run find_package(). For that my package generates a cmake config file "MyPackageConfig.cmake", produced as part of cmake install. Conan and cmake usually work nicely together here and can resolve my cmake targets. This package config script resolves my components. 
Now that I put the package in editable mode, I am unable to find the MyPackageConfig.cmake in the other project and receive the following error:

```
CMake Error at .../vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
By not providing "FindMyPackage.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "MyPackage", but CMake did not find one.

  Could not find a package configuration file provided by
  "MyPackage" with any of the following names:

    MyPackageConfig.cmake
    mypackage-config.cmake
```

My package structure is:

- package/conaninfo.txt
- package/conanmanifest.text
- package/include/<include_files>
- package/lib/<libraries>
- package/lib/cmake/MyPackage/MyPackageConfig.cmake

Is there a way to instruct conan so that cmake can find MyPackageConfig.cmake file?

**Comment by memsharded** [comment]
Hi @jeffrey89 

That depends a bit on the generators and other helpers (are you using CMakeToolchain then?) you are using.

The ``cpp_info.builddirs`` is partially intended for this purpose, without editables in the previous way, before ``layout()``, it probably was something like:

```python
def package_info(self):
     self.cpp_info.builddirs = ["lib/cmake/MyPackage/"]
```

But in editables, it seems you want to map the same folder, but for the "build" layout, which when it is in editable, maybe something in the line:
```python
def layout(self):
     self.cpp.build.builddirs = ["package/lib/cmake/MyPackage/"]
```

You probably want to abstract the "package/lib" part with some ``os.path.join(self.folders.build, ``, but I am not sure if I understand your current layout.

Part of the issue is that if you use the Conan automatically generated xxx-config.cmake files with ``CMakeDeps``, this is done mostly automatically for you.

Please let me know if the ``self.cpp.build.builddirs`` in the ``layout()`` method helps.

**Comment by wer14** [comment]
> Please let me know if the self.cpp.build.builddirs in the layout() method helps.

Seems like this is not going to work. [Bug with layout method](https://github.com/conan-io/conan/issues/9246)

**Comment by memsharded** [comment]
@gmikhaile Thanks for reporting, we are going to have a look at the other issue.

However, this might work, as it is using the ``self.cpp.build`` layout, and the issue you are reporting seems connected to ``self.cpp.package`` layout, I would still give it a try, might not be connected.

**Comment by jlemein** [comment]
@memsharded Thanks, it seems to do the trick. When I use `self.cpp.package.builddirs = [os.path.join("package/lib/cmake")` it managed to find my package config cmake script. For this to work I had to add a cmake_paths generator and call `include(${CMAKE_BINARY_DIR}/conan_paths.cmake)`.

What I don't understand is that when I am not using editable packages I didn't have to do this and the `conanbuildinfo.cmake` already contained the right paths.

In general I only use the "cmake" generator. When using "cmake_find_package" generator conan prefers conan generated find package scripts above the config scripts I wrote. I don't know if I can change the precedence of this. Also I wrote my own cmake package scripts to deal with components and cmake interface targets.

**Comment by memsharded** [comment]
> What I don't understand is that when I am not using editable packages I didn't have to do this and the conanbuildinfo.cmake already contained the right paths.

Not sure if I get your question, when not using editable packages, and using the package in the cache, the package information layout is captured in ``package_info()`` method (which defaults to ``self.cpp_info.includedirs = ["include"], self.cpp_info.libdirs = ["lib"]``, etc, and the generators know where they will find things. But when using editable packages the files, headers and libraries to be used they are not in a known location, but on a random one that can change depending on the build system scripts. The aim of ``layout()`` is to be able to represent this specific layout at build time.

In general, for the new ``layout()`` feature, it is strongly recommended to start considering the ``CMakeDeps`` generator and ``CMakeToolchain`` integrations, as the previous ones do not implement all the necessary support for ``layout()`` (too risky, it could easily break other users existing code), they will implement something/partial, but not full support. If using your own config.cmake scripts, then you might drop the ``CMakeDeps`` and use ``CMakeToolchain`` only (and the new ``CMake`` caller too).

**Comment by jlemein** [comment]
I do understand now. I will take a look into CMakeDeps and CMakeToolchain then.
Thanks for the support.
