### ISSUE TITLE
[feature] Use `CMAKE_GENERATOR` to initialize generator in Conan

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#8948]
One of the issues with a manual `conan install` `cmake` flow is that a CMake generator should be consistent between both tools. New CMakeToolchain generates `conanbuild.json` storing this information for future Conan reference. However, this file is not being used by CMake or by users running CMake configure step from the command line. With CMake 3.15 we got an environment variable support to set a default generator. Now we can:

```
export CMAKE_GENERATOR="Ninja Multi-Config"
```

And it will be used in all invocations of CMake as a default generator. It would be great if Conan would also use it to initialize a default value for a generator.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by KerstinKeller** [comment]
This feature could enable a nice workflow for the user. Internally (at our company - I am not part of the Conan team),  I played around with generating a `CMakePresets.json` file to set the CMake generator, but with activation scripts that we are already using it could play together nicely.
I see it also supports, `CMAKE_GENERATOR_PLATFORM` and `CMAKE_GENERATOR_TOOLSET`...

**Comment by memsharded** [comment]
Closing as outdated, solved by new generators.
