### ISSUE TITLE
[feature] Improving install step in the new CMake helper

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#8949]
CMake 3.15 introduced a new `cmake --install` command: https://cmake.org/cmake/help/latest/manual/cmake.1.html#install-a-project. It has several benefits over currently used `cmake --build . --target install`:
- does not involve a build tool (i.e. Ninja) so is faster to execute (especially for a header-only library)
- have additional options like `strip` that could also be exposed in the helper interface.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AbrilRBS** [comment]
I'm closing this as solved in Conan 2, which has been calling `--install` for a while now - sorry that we didn't get back to you sooner though :)
