### ISSUE TITLE
[question] Path of generated artifacts

### ISSUE THREAD

**Issue by domfellner** [conan-io/conan#8967]
Hi all,
a rather basic question:

I have a simple conanfile.py with the cmake_find_package_multi generator like in the examples repo: features\cmake\find_package\find_cmake_multi_generator_targets\bye\conanfile.py

Depending on my used build system, single configuration build systems (make, ninja) will create the library/executable in the root of the build folder, but multi config build systems like msbuild will put them in build/<build_type>/. In the package() method, I just grep for any lib, dll etc. from the root build folder on like
```
self.copy("*name.lib", dst="bin", keep_path=False)
```
so this kind of works.

I then have a test_package which may also be built with either multi or single configuration build systems, depending on the applied profile. I want my test_package to run with make/ninja/msbuild, but it is not clear to me where I can localise the compiled executable for the run() method for all users, no matter which of the mentioned build systems they use.

I used to set

```
if self.settings.os == "Windows":
    test_binary = Path(self.settings.build_type.value) / "test_package.exe"
elif self.settings.os == "Linux":
    test_binary = "test_package"
else:
    raise ConanInvalidConfiguration("Only Windows and Linux supported")
self.run(test_binary, run_environment=True)
```

but this obviously fails when building with Ninja in Windows.

Is there a common practice how this can be solved?
Should I append an "install" step in CMake where the binaries are moved to a common directory?
Should I manually tell CMake where to put the binaries?
Is there some variable I can use in my conanfile to get the used directory?

I hope you can understand my problem and thanks for all comments in advance!
Dom

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi Dom!

Yes, we are aware there are some difficulties in representing the current project and build layout, and we are working on it heavily. Next version 1.37 will release a new experimental way of representing the layout that might help to improve this.

In the meantime, I think there might be some workarounds and possible alternatives:

The ``test_package`` was never meant to try different build systems integrations, just to test the validity of a package (did it package the headers? Did it package the libraries? Does it seems the cpp_info is correct?), so they are designed to always be using the same build system and generator, with the same layout.

You can try defining more than one ``test_package`` folder, like ``test1``, ``test2``, etc, using different integrations, and then test them with ``conan create ..... -tf=test1``

As the CMakeLists or build script there is typically a very simple, custom one, you can try to define there something like:
```cmake
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
...
```
This will ensure the executable is always in the same folder, no matter what generator you use.


Please let me know if this helps.

**Comment by domfellner** [comment]
Hi memsharded,

thanks for your answer. Setting the CMAKE_RUNTIME_OUTPUT_DIRECTORY was an easy solution for my problem 🌈
