### ISSUE TITLE
[feature] globally specify build folder

### ISSUE THREAD

**Issue by Flow-It** [conan-io/conan#8968]
By default (on Linux), conan creates a build folder under `/home/user/.conan/data/package/version/_/_/build/hash/`

In this layout are 3 important sub directories:

- source: Downloaded exactly once per version, read only data, preferred to keep on persistent storage
- package: Create once per version and configuration, then read only. Most expensive to create. Should definitly be kept on persistent storage.
- build: Created once per version and configuration, read once per version and configuration. Potentially many intermediate reads and writes. Can be discarded after a package was created.

This small overview describes the situation when the recipe is "production-ready". When still developing the recipe, some deviation from the above observations are to be expected.

To avoid expensive disk writes and to speed up building (*) I propose adding a configuration switch for specifying a common (base) build directory. The idea here is that users would potentially choose a tmpfs or something similar on other OSes. The current solution to change the build directory with the `-bf` option is too cumbersome when creating many packages.

(*) A benchmark using `conan create` is still missing. I observed speedups up to 50% when compiling large code bases like LLVM having the CMake build directory under /tmp.

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
> A benchmark using conan create is still missing. I observed speedups up to 50% when compiling large code bases like LLVM having the CMake build directory under /tmp.

Very Interesting 🧠

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

Conan allows defining the ``storage_path`` conf to define the folder in which packages are stored, so this can be selected by users, if they want to put it in some faster storage.

Closing as solved/not planned, but please create new tickets for any further question, thanks for the feedback!
