### ISSUE TITLE
[feature] specify test_package folder in conanbuild.py

### ISSUE THREAD

**Issue by Flow-It** [conan-io/conan#8969]
I am keeping the conan recipe in the same repository as my project source code, as well as the code to test the conan package. In my directory layout, there already exists a `test` folder, and using `test_package` additionally for conan makes it harder to understand what each folder is for on first glance.

Conan already provides an option to use a different name for the `test_package` folder, which I decided to use (I opted for `conan_test` but naming is hard...). Now, whenever I call `conan create` (and I want the test package to be built) I have to pass the `-tf` option.

So for all of my own projects, I'd like to specify another folder. But at the same time, for all the recipes I keep to build packages from external projects, I want to keep using the default.

As a result of those two more or less opposing requirements I propose allowing to specify the test package in the recipe itself, something like this:
```
def test(self):
    self.test_folder = "conan_test"
```

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Flow-It 

Sorry this suggestion was not responded back then.
It seems the ecosystem has settled in the ``test_package`` convention quite nicely (no further similar requests to this one) and for other exceptional cases the ``-tf=xxx`` should be good enough. We'd strongly recommend just using the ``test_package`` folder, so far we have not seen a name collision and it is recognized as a Conan thing when close to a conanfile.py.

Closing this as not planned, thanks for your suggestion anyway!
