### ISSUE TITLE
[question] separating build_requirements from normal requirements during build

### ISSUE THREAD

**Issue by Tomeamis** [conan-io/conan#8970]
I am trying to create a generic-ish template that could be mostly reused in several projects, and I would like to include unit tests as part of the project. These will presumably sometimes use a testing framework such as gtest, or perhaps some other convenient packages, which I have gathered should be listed as `build_requirements`.

However, in the `build()` method the build requirements seem indistinguishable from normal requirements.

This is a problem for me, as I do not want the build requirements to influence building of the main project. For example I don't want gtest to be supplied to the linker when building a shared library etc.

My first thought was that maybe I could just filter out the packages listed in `build_requires`, but that falls apart in case any builld requirement has a transitive dependency.

Is there any way I could, in the `build()` method, create a list of non-build requirements, or alternatively some other way of getting this information to the build system?

**Comment by memsharded** [comment]
Hi @Tomeamis 

This depends on the generator that you are using. For example, the ``cmake_find_package``, ``cmake_find_package_multi`` or the new experimental ``CMakeDeps`` and ``MSBuildDeps`` generators, will create a different xxxx-config.cmake file for each dependency. Then your build script can easily select which dependencies are linked to which targets and which dependencies are linked with tests only.

Have you tried that approach? Are you using CMake?

**Comment by Tomeamis** [comment]
Hello and thank you for the prompt reply.

I am using CMake, however the problem is that I don't know which dependencies I should refer to.

For example, suppose that I am building a library depending on `poco`. I also have unit tests, which depend on `boost`. Now, I can specify that the library depends on `poco-config.cmake`, but then I will get errors since I also need to depend on `openssl`, which `poco` depends on. If I specify that the library depends on everything except `boost`, `bzip2` and `libiconv` will be linked to the library, which is not wanted. Basically I need a way to figure out that `libiconv` is only required for build, while `openssl` is also required for the library.

Sure, I could specify the requirements, then see the output of `conan install` and then adjust my scripts accordingly, but not having to explicitly deal with transitive dependencies is pretty much the entire reason I have decided to use conan in the first place.

**Comment by memsharded** [comment]
> specify that the library depends on poco-config.cmake, but then I will get errors since I also need to depend on openssl, which poco depends on

The generated ``poco-config.cmake`` is transitive. It will include the transitive dependencies that it needs, so you shouldn't get errors. It will not include, ``gtest`` of course. Please try it and let us know how it goes.

**Comment by Tomeamis** [comment]
Oh, this is exactly what I needed. Thank you for your help.
