### ISSUE TITLE
[question] CMAKE_BUILD_TYPE and CMAKE_CONFIGURATION_TYPES behaviour

### ISSUE THREAD

**Issue by oleurodecision** [conan-io/conan#8973]
Well, I'll try to be short and clear...

The current steps which conducted me to the problem (and current question) : 
- I'm trying to build an internal project with MSVC, the project has a conanfile.py to manage its dependencies
-  some (well, all) of its requirements are currently missing on my system, thus a call to `conan install . -if build -s build_type=Debug --build=missing` triggers the build of the requirements (soooo cool)
- one of the requirement is REALLY sensitive to the possible build type values (MUST be Release or Debug)
- as the environement is multi-configuration capable (MSVC), the `CMAKE_BUILD_TYPE` is NOT set by conan when calling the build (YES, that's totally accurate)
- BUT the symmetric option `CMAKE_CONFIGURATION_TYPES` is NOT set by conan too
- and thus the requirement is build with a (CMake) default setup of Release,Debug,RelWithDebInfo,MinSizeRel
- which triggers a beautiful (but not expected nor intended) failure ...

So, shouldn't https://github.com/conan-io/conan/blob/develop/conans/client/build/cmake_flags.py
```python3
def build_type_definition(new_build_type, old_build_type, generator, output):
    if new_build_type and new_build_type != old_build_type:
        output.warn("Forced CMake build type ('%s') different from the settings build type ('%s')"
                    % (new_build_type, old_build_type))

    build_type = new_build_type or old_build_type
    if build_type and not is_multi_configuration(generator):
        return {"CMAKE_BUILD_TYPE": build_type}
    return {}
```
be modified as below 
```python3
def build_type_definition(new_build_type, old_build_type, generator, output):
    if new_build_type and new_build_type != old_build_type:
        output.warn("Forced CMake build type ('%s') different from the settings build type ('%s')"
                    % (new_build_type, old_build_type))

    build_type = new_build_type or old_build_type
    if build_type:
        if is_multi_configuration(generator):
            return {"CMAKE_CONFIGURATION_TYPES": build_type}
        else:
            return {"CMAKE_BUILD_TYPE": build_type}
    return {}
```

Can submit a PR later if required, but have no idea how to set up tests for this (haven't look yet). 
(side note : would be great to have a mentor-apprentice system for people who wants to be more implied into the conan/conan-center recipes development process)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by oleurodecision** [comment]
Can submit a PR later if required, but have no idea how to set up tests for this (haven't look yet). 
(side note : would be great to have a mentor-apprentice system for people who wants to be more implied into the conan/conan-center recipes development process)

**Comment by memsharded** [comment]
Sorry this was not responded back then @oleurodecision 

Now this would be outdated, as this was referring to the deprecated CMake integrations, that have been removed in Conan 2.
I am closing this ticket as outdated, but please create new tickets against the latest integrations if necessary. Thanks for the feedback.
