### ISSUE TITLE
[bug] Two completely different configurations

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#8979]
Please merge the two `conanfile.txt` and `conanfile.py` configuration methods into a single, unified system. The latter is verbose, but the former can't even declare a new package.

The divergence requires maintaining twice as much documentation. (And twice as much reading!) Quite the confusing user experience.

For example, deprecate conanfile.txt.

**Comment by czoido** [comment]
Hi @mcandre,
Thanks for the question. The adoption of `conanfile.txt` is already massive, so there is no way we can deprecate it anytime soon. So far, providing a simple declarative format with the `conanfile.txt` has been useful for simple cases where you just want to use conan to consume some packages in your project.

**Comment by memsharded** [comment]
Closing as responded back then, thanks for your feedback.
