### ISSUE TITLE
[feature] Guard against including conanbuildinfo.cmake more than once

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#8980]
I just spent a bunch of time debugging a weird conan issue where the underlying problem was that I was including my conanbuildinfo.cmake more than once. Seems like you could add some code which detects this situation a reports an error....unless there's a legitimate use, but I can't think of one atm.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
Hi @rconde01,

Could you provide us with more information? How did you end up including this file twice? Thank you

**Comment by rconde01** [comment]
So our build is a bit complicated. We need multiple conanfile.py because some of our binaries link to static libraries and some to dynamic libraries. We can successfully do this by including the generated conanbuildinfo.cmake in independent branches of the CMake build tree. But I accidentally left an include in a branch that was not independent from another branch. This meant it was included twice in the lower branch.

I'm certainly not saying this would be a very common concern, but can probably be addressed by looking if a internal variable is already defined when processing conanbuildinfo.cmake. Would perhaps alert to the issue when doing more complex configurations.

**Comment by danimtb** [comment]
Thanks for the clarification. The problem I see is that the _conanbuildinfo.cmake_ provides different variables depending on the dependency tree you install, therefore, having a common guard might not result convenient. I'd say would probably fit your use case but maybe will break other ones using it in a similar fashion. IMO it is a user's choice

**Comment by rconde01** [comment]
Ok - then maybe it's the specific problem i encountered which needs to be fixed. The issue was:
```
set(CONAN_CMD_SHARED_LINKER_FLAGS ${CONAN_SHARED_LINKER_FLAGS})
```

`CONAN_CMD_SHARED_LINKER_FLAGS` is later used to set `CMAKE_SHARED_LINKER_FLAGS`. Normally `CONAN_SHARED_LINKER_FLAGS` is empty when that line is executed. But later the sharedlinkflags from all requirements are added. So the second time you include it, all cmake targets get those flags whether you link to them or not.

Maybe it just needs to be something to be aware of...was just thinking to save someone else some trouble.

**Comment by danimtb** [comment]
AFAIK injecting multiple _conanbuildinfo.cmake_ is not a common practice so yes, that might be an issue in this case. Anyway, thanks a lot for reporting, this will be helpful in case someone has issues with CMake generator and multiple _conanbuidinfo.cmake_ files
