### ISSUE TITLE
[question] custom generator creating multi configuration output

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#8987]
For a project that requires some single configuration packages available in conan, I would like to have a generator that creates a single output file, containing multiple configurations (e.g. Debug, Release) and the individual requirements for that.
However as far as I was able to tell so far, conan install needs to run twice (once with Debug settings/profile, and again with Release).  

If I specify my own custom generator, it will then overwrite the generated file of the first run with those from the second. I do require a single output file, so just adding the build_type setting to the file name won't do.  
It is also possible that the user only ever intends to do one of the two and thus only choses to run conan install once.
Furthermore the order in which the conan install commands are run (if run multiple times) is unspecified and the user might run the same install multiple times as well on accident.  

The generator still needs to work for these cases as well.

Is there any great way for a generator to produce a single output file from a number of conan install runs and if so, how would that be best achieved?

Not limited to any old conan version, so newest and greatest is fine.

**Comment by memsharded** [comment]
Hi @Sil3ntStorm 

Yes, we basically do something similar for the new ``MSBuildDeps`` and ``CMakeDeps``, ``CMakeToolchain`` generators:

- In both cases, the order of ``conan install`` is irrelevant. CMake generator expressions or MSBuild conditionals work irrespective of the order
- The approach is to generate different files for the different configuratons, and then a common file that aggregates them. This common file is the one that is parsed and modified, not overwritten, by the generators. In theory you could have everything in a single file, as long as you introduce some markers that allow to parse it conveniently to allow read-modify-save operations by the generation execution.

**Comment by Sil3ntStorm** [comment]
@memsharded thanks for the answer.

However I have not had much luck with that while previously exploring that approach in the past couple hours. Due to the required file structure it's not exactly an easy merge (that I have found anyway).
Also not exactly sure on how you go about merging the files, since you would need to create two files each generator run? I must've missed that ability.

**Comment by Sil3ntStorm** [comment]
I seem to have found a workable solution. Thanks for the hints.

**Comment by memsharded** [comment]
Thanks for following up @Sil3ntStorm, I am curious, what solution have you found? 
If you have any question or need more detail about the merging we do for the other generators, just let me know, and I'll try to give more details.

**Comment by Sil3ntStorm** [comment]
Sorry for the late reply @memsharded. I am basically extracting the required conan information into a json object with whatever configuration is currently being processed. That then gets saved to disk and loaded at the start of the run, updating the object with the currently processed configuration. At the end of the run that updated json object (now containing all prior processed configurations) is processed again into the actual build system file. Extra work for a single configuration but works fine when running conan multiple times, as then all prior information is retained to be processed into a combined build system file.

**Comment by memsharded** [comment]
Ok, great @Sil3ntStorm, yes that sounds very similar to what we are doing in the other multi generators, basically accumulating the result of multiple calls. Thanks for the feedback!
