### ISSUE TITLE
[bug] Cannot install boost/1.69.0 RelWithDebInfo

### ISSUE THREAD

**Issue by JeremyBorys** [conan-io/conan#8988]
Cannot install boost/1.69.0 RelWithDebInfo, Conan is failing to resolve dependencies and after explicitly trying to resolve the dependency conan is still failing.

This just started happening today. This seemed to work as of May 21 at 7AM and then starting at occuring at 8:30AM. I have no idea why...

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc9
  * Conan version: conan 1.36.0
  * Python version: N/A

### Steps to reproduce (Include if Applicable)
1. install conan 1.36.0 from https://conan.io/downloads.html
2. create a conanfile.txt which contains:
```
[generators]
cmake

[requires]
boost/1.69.0

[options]
boost:shared=False
boost:fPIC=True
```
3. run 
```
/bin/conan install . -s build_type=RelWithDebInfo -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -s boost:compiler=gcc -s boost:compiler.version=9 -s boost:compiler.libcxx=libstdc++11 -g=cmake --build=missing
```
This fails with:

```
ERROR: Conflict in automake/1.16.3:
    'automake/1.16.3' requires 'autoconf/2.71' while 'libbacktrace/cci.20210118' requires 'autoconf/2.69'.
    To fix this conflict you need to override the package 'autoconf' in your root package.
```

4. Update the conanfile.txt to:
```
[generators]
cmake

[requires]
boost/1.69.0
autoconf/2.71

[options]
boost:shared=False
boost:fPIC=True
```

5. This still fails with the error 
```
ERROR: Conflict in automake/1.16.3:
    'automake/1.16.3' requires 'autoconf/2.71' while 'libbacktrace/cci.20210118' requires 'autoconf/2.69'.
    To fix this conflict you need to override the package 'autoconf' in your root package.
```

Note that for whatever reason debug and release build types works fine

**Comment by JeremyBorys** [comment]
Any help here would be great. I do have an explicit requirement on boost 1.69.0 and I can't change that.

**Comment by JeremyBorys** [comment]
I kind of have a non ideal workaround which is to map relwithdebinfo to release configurations... It feels like this is a ticking time bomb though because I don't really understand what/why this is happening. This just feels like it more or less just happens to work :(

**Comment by memsharded** [comment]
Hi @JeremyBorys 

This might not be an issue of Conan client, but an issue of ConanCenter packages, that maybe got some updates to some of those recipes, and that might be affecting your capacity to build from source in RelWithDebInfo.

Lets ask @uilianries @SSE4 for help.

Also, in the meantime I would suggest:

- If you depend on these packages for something serious - production grade, I would recommend to store a copy of the ConanCenter packages that you use in your own ArtifactoryCE. Update it when you want, explicitly, but not automatically, to control that everything is working fine.
- You might also want to try the 2 profiles approach: Define a "build profile" that can be Release (that is for the build-requires), and call it like ``conan install .... --profile:build=myprofilebuild  -s compiler=gcc ....```
- I would also encourage to use profile files for the host configuration as well (gcc, 9, RelWithDebInfo); instead of all in command line parameters.

Using the 2 profiles approach will be the standard in Conan 2.0, and might solve also many issues related to cross-building. Please give it a try too.

**Comment by JeremyBorys** [comment]
Thanks @memsharded, 

Yeah, we are experimenting with conan within an experimental product so that we can incrementally scale out. Literally one of the  next things we are looking at is creating a copy in our own artifactory server for precisely the reason you specified. I just haven't gotten there yet.

To be honest, I am heavily leveraging https://github.com/conan-io/cmake-conan to do a lot of the dirty work for me and this is what conan-cmake spits out as an conan install. I will look at constructing profiles going forward if this is going to be the standard :)

I assume there will be a profile for every build type, release, debug. asan, tsan, etc?

**Comment by memsharded** [comment]
> I assume there will be a profile for every build type, release, debug. asan, tsan, etc?

It depends, it is possible to have profiles for most of the settings, but you can always override individual settings on the command line. So for a profile that has ``build_type=Release`` you can do:

```
conan install . -pr=myprofile  # release
conan install . -pr=myprofile -s build_type=Debug  # debug
```

And that can avoid combinatoric of profile files. You can also do composition and inclusion of profiles if necessary.

**Comment by SSE4** [comment]
yes, this unfortunately happens from time to time on CCI, as we are starting to have more complex dependency graphs and then we need to update some version used in multiple nodes of the graph. right now we don't have an automated process to bump all the graph at once, and we need to submit N PRs to bump versions in N nodes of graph. as an example (simplified):
```
boost
├── libunwind
│   └── autoconf/2.69
└── libbacktrace
    └── autoconf/2.69
```
now, as soon as new version `autoconf/1.71` is available, you have to update two nodes - libunwind and libbacktrace.
unfortunately, we don't have any tool to make such update in one shot for all nodes, so we make two PRs for libunwind and libbacktrace, which are reviewed and merged separately. as a result you may have an inconsistent intermediate graphs like:
```
boost
├── libunwind
│   └── autoconf/2.71
└── libbacktrace
    └── autoconf/2.69
```
which causes some conflicts.

**Comment by JeremyBorys** [comment]
So going back to my original description. All this is fine, that there is conflicts that occur etc. What I was struggling with was resolving the conflict:

```
ERROR: Conflict in automake/1.16.3:
    'automake/1.16.3' requires 'autoconf/2.71' while 'libbacktrace/cci.20210118' requires 'autoconf/2.69'.
    To fix this conflict you need to override the package 'autoconf' in your root package.
```

Simply specifying the version I wanted in the root conanfile.txt isn't enough i.e. from
```
[requires]
boost/1.69.0
```
to
```
[requires]
boost/1.69.0
autoconf/2.71
```
which it sounds like it should be according to:

https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#overriding-requirements

Unless I am misinterpreting / oversimplifying what what was outlined.

I assume the piece I am misunderstanding has to be related to build type (and what is actually going on behind the scenes in either the client or conancenter) because this only occurs for a relwithdebinfo build type and not debug or release buildtypes.

**Comment by SSE4** [comment]
that might be an old issue https://github.com/conan-io/conan/issues/4753 that sometimes build requirements cannot be overridden the same way like normal requirements, and special handling is needed. 
(as `libbacktrace` build-requires `autoconf/2.69`)

**Comment by SSE4** [comment]
why does it happen only for `RelWithDebInfo`? that's another good question.
my theory is because `build requires` are kinda smooth, special - they may appear in graph if you're doing build (e.g. explicit `--build` or just missing packages), but may not appear if you already have pre-built binaries (in remote or in cache). so sometimes for the "same" graph you may or may not experience the conflicts depend if you're doing re-build or not ("same" is in quotes, because graph could be different in conan 1.0 if you're doing rebuilds).
NOTE: there is a proposal to change that a bit in conan 2.0: https://github.com/conan-io/tribe/pull/20, so build requires will be able to always appear in graph, even if they are not really needed.
back to the my theory, in CCI we don't build `RelWithDebInfo`, only `Debug` and `Release`, so for `RelWithDebInfo` you probably had missing pre-built packages, while for `Debug`/`Release` you happen to consume pre-built binaries from conan-center.
so, in the first case (`RelWithDebInfo`) you didn't have `libbacktrace` binary available, and `autoconf` was inserted into the graph as build require, as build is needed. in the second (`Release`/`Debug`) `libbacktrace` binary was already there, so rebuild wasn't needed/requested, and build requirements (`autoconf`) were not inserted into the graph, because it's useless to download them.

**Comment by SSE4** [comment]
if we were able to more or less investigate why does it happen, the next question is what can/should we do?

- short term (conan center): update all `autoconf` requirements in conan center to the latest version (this may take significant time)
- long term (conan center): develop a CI solution to automatically and transactionally update requirements to avoid intermediate graphs with conflicts
- short term (conan client): solve issue #4753
- long term (conan client): implement a model proposed in conan-io/tribe#20
- short term (consumer): use older revision of boost/libbacktrace, and in general avoid using bleeding edge binaries until CI citation improves (lock files may also help)
- short term (consumer): try to use 2 profiles model, that should allow to override both build requirements and regular requirements

**Comment by SpaceIm** [comment]
It happens because libbacktrace must be built (no pre-built binaries for RelWithDebInfo), but can't due to build requirements versions conflict (build requirement graph can't override versions) since https://github.com/conan-io/conan-center-index/pull/5539. It has been fixed today by https://github.com/conan-io/conan-center-index/pull/5575 (we now "build require" libtool only, instead of libtool + autoconf. autoconf comes as a transitive dependency, it avoids versions conflicts).
It would have failed also with Release or Debug and -b option.

**Comment by JeremyBorys** [comment]
thank you @SSE4 and @SpaceIm for the detailed answers :).

>  It would have failed also with Release or Debug and -b option.

This is kind of what I was hoping to hear :) as I didn't understand why the workaround I was doing seemed to work around the problem.

I have/will continue to look at the two profiles approach. I already have the work planned to copy the binaries we use into our own Artifactory service.
