### ISSUE TITLE
Can't connect to conan_server through apache

### ISSUE THREAD

**Issue by lcipolla8** [conan-io/conan#8992]
I've been trying to get conan_server up and running through apache by following the docs here: https://docs.conan.io/en/latest/uploading_packages/running_your_server.html

### Environment Details (include every applicable attribute)
  * Operating System+version: RHEL 7.9
  * Apache version: 2.4.6 with mod_wsgi 4.7.1
  * Conan version: 1.35.2
  * Python version: 3.6

### Steps to reproduce (Include if Applicable)
I have the authentication working, and the conan client makes the initial connection to retrieve the host, port, and URL info, but then it fails to upload any files due to 'connection actively refused' errors. Comparing the apache log file with the output of running conan_server manually (which I'm able to connect to just fine), I noticed that the Bottle server is never getting started. Digging into the python code a bit, it seems the issue is that main() never gets called in server_launcher.py because \_\_name\_\_ isn't "\_\_main\_\_"; it's "_mod_wsgi_XXX". Updating that line to include checking for \_\_name\_\_.startswith('\_mod_wsgi\_') results in the Bottle server starting, but then the conan client will just hang until the request_timeout is reached, at which point it fails with "max retries exceeded." I've tried increasing the timeout to as much as a half an hour with the same result.

Any ideas why the client is never able to connect? Is the main() issue an expected local modification that needs to be made when running with WSGI or is it a symptom of something I have misconfigured? I understand conan_server is mainly used for testing, but I would really like to get this working. Any help would be greatly appreciated.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Apache log (after the .startswith('\_mod_wsgi\_') modification):
```
[wsgi:error] [pid 30791] ***********************
[wsgi:error] [pid 30791] Using config: /usr/share/httpd/.conan_server/server.conf
[wsgi:error] [pid 30791] Storage: /usr/share/httpd/.conan_server/data
[wsgi:error] [pid 30791] Public URL: http://XXX.com:9300/v1
[wsgi:error] [pid 30791] PORT: 9300
[wsgi:error] [pid 30791] ***********************
[wsgi:error] [pid 30791] Bottle v0.12.19 server starting up (using WSGIRefServer())...
[wsgi:error] [pid 30791] Listening on http://0.0.0.0:9300/
[wsgi:error] [pid 30791] Hit Ctrl-C to quit.
```
httpd.conf:
```
<VirtualHost *:80>
        DocumentRoot /var/www/html
        ServerName      XXX.com

        WSGIScriptAlias /conan /usr/local/lib/python3.6/site-packages/conans/server/server_launcher.py
        WSGICallableObject app
        WSGIPassAuthorization On

        <Directory /usr/local/lib/python3.6/site-packages/conans>
                Require all granted
        </Directory>
</VirtualHost>
```

**Comment by memsharded** [comment]
>  I understand conan_server is mainly used for testing, but I would really like to get this working. 

Yes, certainly having free ArtifactoryCE, it is way more recommended as a production server, it will scale better, and have other great things like better permissions, a web UI, etc.

The truth is that we have never setup it through apache, so we cannot help much with it, we have used gunicorn and nginx, but not apache. Up to our knowledge, it has not been necessary to modify the source code to run it, but it is possible that other users are doing it and not reporting back. I am going to add some help needed label, in case someone else from the community knows better.

**Comment by memsharded** [comment]
Closing as inactive.
