### ISSUE TITLE
Prefix library name to output

### ISSUE THREAD

**Issue by bjoernpollex** [conan-io/conan#90]
When using `self.output.info`, it would be useful to prefix the library name to the output. For instance when using [Boost](https://www.conan.io/source/Boost/1.60.0/lasote/stable) with `header_only` option, the build output starts with **HEADER ONLY** without any context.

**Comment by memsharded** [comment]
I thought it was pretty simple, so I added a wrapper around conanfile.output instance (the one generating the HEADER ONLY message), and it works, but I have realized that indeed there are many other messages generated in other places, so I am trying to do something more general now, that will scope messages with the corresponding library name. It is a bit more complex than expected but should be finished soon.

**Comment by memsharded** [comment]
Released in 0.7, I'd say that the output has largely improved, not only by the prefix of the package, but also many other improvements in the output. Could you please check it? I am closing the issue, but re-open it if the output still not good enough, thanks!
