### ISSUE TITLE
[bug] Compatible packages are locked incorrectly

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#9002]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Conan version: develop, 1.33.1, 1.36.0
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)
I've created a test for conan which demonstrate the issue: 
https://github.com/conan-io/conan/compare/develop...ytimenkov:compatible-lock-demo 

1. Create a package with compatible setting.
2. In consumer file create lock `conan lock create` for "compatible" package (one with missing binary). During this conan writes "Main binary package '1fba023b99af36dcb917d3d3ea0ab91fd834c725' missing. Using compatible package '06848324fc74da256b5bd6df5e66fe95399a1494'" (or similar)
3. When I try to consume this lock, for example with `conan info --lockfile` Conan fails with message: "package-id '1fba023b99af36dcb917d3d3ea0ab91fd834c725' doesn't match the locked one '06848324fc74da256b5bd6df5e66fe95399a1494'"

**Comment by memsharded** [comment]
Thanks very much for the test, that was super useful to reproduce.

I have proposed this fix in https://github.com/conan-io/conan/pull/9008, it has some (small) risk, so should be carefully reviewed before merging, lets see how it goes.

**Comment by memsharded** [comment]
Merged https://github.com/conan-io/conan/pull/9008, will be in Conan 1.37 (next Monday/Tuesday hopefully)
