### ISSUE TITLE
[feature] importing from specified requires, not all package deps. 

### ISSUE THREAD

**Issue by lennoncork** [conan-io/conan#9004]
When importing from multiple packages the default for root_package is all package deps. We have a need to limit this to only the specified requires in the conanfile, and not the full dependency tree. 

For example, if you have 3 packages A, B, and C with the following dependencies, 
- A -> B
- B -> C

It looks like the importing from package A results in the content of both B and C packages. In some situation we only want to import B and not import C. We can specify the `root_package=B` which works well for simple imports. But for more complicated ones duplicating the requires and imports is painful. 

A possible solution would be to support something like `root_package=@requires` so that only the content of B is imported for package A when used. This would keep the default behavior intact but provide some flexibility on the import logic. 

Using this page as a reference https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports
_root_package (Optional, Defaulted to all packages in deps): An fnmatch pattern of the package name (“OpenCV”, “Boost”) from which files will be copied._

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @lennoncork 

Seems that this could make sense, but seems something a bit tricky for the value.
Our proposal will be to make the "FileImporter" functionality explicitly available in the recipes, so it is possible to customize behavior in a more direct way.

**Comment by lennoncork** [comment]
For some background, the problem we're trying to solve is similar to #5251 where we want to bring together a collection of different binaries for multiple architectures. The approach right now is to generate a conanfile.txt for each set and run conan install on them. We could have created conanfile.py instead but ended up being less verbose to use a template and generate the text file from a master conanfile.py. The template supports variable replacement which was a bonus as it allowed us to re-use it for multiple architectures and profiles. 

We have a workaround in the template to generate in import string with the appropriate root_package for every require. Wanted to capture the request in case someone else has the same issue. 

Having said that it would be great if the import syntax in the conanfile.txt could support this. 

Alternatively a multi-arch package aggregation solution would be very nice!

**Comment by WernerWessely** [comment]
@lennoncork Hi, I am also struggling with how to elegantly handle a build which aggregates packages with different arch into one custom deployable non-conan package. The solution we currently use is to provide a 'multi_arch' option variant of those packages that need to contain binaries for different archs. Building those variants is a mess, you have to call cmake manually for all needed options in a loop. Have you found any good solution yet? Do you know if Conan 2 will make this easier in any way?

**Comment by memsharded** [comment]
This has changed a lot in Conan 1.X latest versions and 2.0 with:

- Access to ``self.dependencies["mydep"].package_folder`` so you can directly copy things
- This can be done from the  ``generate()`` method
- There are also new ``deployers`` in Conan 2.0 that can be used to gather files from Conan dependencies
- To collect several different architectures, call ``conan install .. -s arch=myarch --deployer=full_deploy --deployer-folder=myarch`` once for each architecture
- If desired an even higher level of automation, Conan 2.0 provides custom commands that can do everything wrapped in a single command.

I am closing this ticket as outdated, please check the new Conan 2.0 features and create new tickets as necessary. Many thanks!
