### ISSUE TITLE
[feature] Add --build parameter to build all packages not in local cache

### ISSUE THREAD

**Issue by wdobbe** [conan-io/conan#9006]
On our Linux CI/CD server I want to prevent that we download binary packages that are built against a newer libc version.
The easiest solution for that seems to build all packages that are not in the local cache from source. However as fas as I can find the `--build` option for conan install, conan create etc doesn't support this build policy yet.

I think it would be useful to allow `conan install .... --build=not_in_cache`. The `not_in_cache` parameter is of course only an example and can be changed as fit.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @wdobbe 

I think the right, long term solution if you want to control, track and manage properly the differences of the new libc version is not this way, but adding a custom sub-setting that will represent this difference: https://docs.conan.io/en/latest/extending/custom_settings.html#adding-new-sub-settings.

This can be very straightforward, only add the subsetting to the settings.yml, then to the profiles that you are using, no need to change the recipes, and if you want to have backward binary package_id compatibility, adding a ``None`` value for the subsetting will make it. Then ``--build=missing`` will always do the right thing, safely and optimally.

**Comment by wdobbe** [comment]
Thanks. I added a setting for my Linux distro in settings.yml and my profiles.
But when I install a newer Conan version that might have additions to settings.yml, will my modified settings.yml automatically merge with the new one, or should I add the distro line again after a Conan update ?

**Comment by wdobbe** [comment]
ps: Apart from avoiding libc issues, a `--build` parameter that only builds packages not in cache can be useful anyway for CI.

**Comment by memsharded** [comment]
> But when I install a newer Conan version that might have additions to settings.yml, will my modified settings.yml automatically merge with the new one, or should I add the distro line again after a Conan update ?

You should put things in a repo, and use ``conan config install <url>`` to get everything: profiles, settings.yml, configured remotes, custom conan.conf, hooks.... It also has memory, so <url> should only be introduced first time.

If the upstream ``settings.yml`` has some settings that you really need, then you should put it in your custom ``settings.yml`` in your repo, to be used by ``conan config install``. At the moment it has to be merged manually, it is not that straightforward to merge yaml files.

**Comment by wdobbe** [comment]
Thanks. We already have a repo for `conan config install`, I will add our settings.yml to it.

**Comment by AbrilRBS** [comment]
Closing this as solved in Conan 2 with the addition of [`settings_user.yml`](https://docs.conan.io/2/reference/config_files/settings.html#settings-user-yml) file that allows to add custom settings on top of the ones provided by Conan, which removes the need to keep the files in sync
