### ISSUE TITLE
[feature] Change default CMakeToolchain to not remove Rpaths

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9007]
Because that should be an opt-in and tools like cmake install already strip the rpaths while installaing.

Behavior in Cmake was likely implemented in Cmake 3.9, so we didn't take that into account while developing generators for older Cmake versions.

**Comment by memsharded** [comment]
https://cmake.org/cmake/help/latest/variable/CMAKE_SKIP_INSTALL_RPATH.html#variable:CMAKE_SKIP_INSTALL_RPATH is not clear if the default is to clean rpaths while installing, it doesn't seem so.

**Comment by SSE4** [comment]
any reason why we should mess with these settings in the first place?
IMO toolchain should work as closely as possible to the vanilla CMake (e.g. many users do build with and without conan and want them to be identical)
while some changes in toolchain are essential to ensure settings are correct, rpath management doesn't seem to be a strict requirement.
