### ISSUE TITLE
[question] MSBuildDeps - Cannot add property sheet due to circular dependency with property sheets

### ISSUE THREAD

**Issue by sd185233** [conan-io/conan#9010]
Trying to ascertain the suitability of the the MSBuildDeps generator over using CMake for legacy projects.  I tried the following steps - 

-Created recipe file with one build_requires and using the MSBuildDeps generator.  Build step is using the MSBuild helper passing an MSBuild .proj file.
-Run Conan install 
-Opened the VS solution and and tried to add the conandeps.props prop sheet to the project.  I get the following error - 

```
---------------------------
Microsoft Visual Studio
---------------------------
Cannot add property sheet 'C:\core\abc\conandeps.props' as it is either an invalid property sheet, or adding it would cause a circular inheritance with one of the selected property sheets.
---------------------------
OK   
---------------------------
```

Also tried adding the actual dep conan_xyz.props file, still get the same error.  This is with VS 2017.  Has this error been seen before?

I did get it working with the older visualstudio and visualstudio_mult generators (well sort of, the property sheets at least loaded, but I did have to tweak the includes outside of the property sheet...didn't look further as I believe MSBuildDeps is the way to go)

Thanks
Scott

**Comment by memsharded** [comment]
Hi @sd185233 

I have not seen this error before. It would be great to understand if you could share a bit more details about:

- Other dependencies that you depend on, if they are regular or not.
- Build-requires behave differently if you are using the 2 build&host profiles, are you? It is suggested to start using this approach, as it will become the default in Conan 2.0
- Can you share the generated files, please? If cannot share them in public, you might send them to info@conan.io too.

**Comment by sd185233** [comment]
Hi @memsharded 

-The only dep we have is a single build_requires, purely for testing how the mechanism for bringing in the include/linker settings are brought in.
-We have only been using build/host profiles for Android where we are cross compiling.  For this we are using a single profile.  Can try with dual profiles.
-I have emailed over the recipe and the generated props files

Thanks
Scott

**Comment by memsharded** [comment]
I am trying this PR here https://github.com/conan-io/conan/pull/9012 to see if that fixes issues with dots in package names.

If you could also try running from source from my branch (ask if you need guidance) in your project, that would be very helpful.

**Comment by sd185233** [comment]
Sure, how do I set this up?

**Comment by memsharded** [comment]
Yes, please, follow https://github.com/conan-io/conan#install-a-development-version. Basically:

-  git clone https://github.com/memsharded/conan.git conanio

NOTE: repository directory name matters, some directories are known to be problematic to run tests (e.g. conan). conanio directory name was tested and guaranteed to be working.

-  cd conanio
-  git checkout fix/msbuildeps_dot_pkgnames
-  pip install -e .

After that, your Conan commands will be using my fork on my branch

**Comment by sd185233** [comment]
How do I revert back to my original Conan install afterwards?

**Comment by memsharded** [comment]
It should be good with:

>  pip uninstall conan

(then reinstalling ``pip install conan`` without the "-e")

**Comment by sd185233** [comment]
Thanks...There is no error now and I can see conandeps loaded, however it isn't loading any of the sub prop files.  Tried adding one of the dep files instead and only it loaded, it did not load the prop files for each config.

On an unrelated note, is there any way to have the cmake configure method do the cmake generation, but no build?  Maybe I need to use invoke the commandlines instead of using the helper?  Considering just converting to cmake to generate the sln/proj files, then using the MSBuild helper to build via the msbuild proj so that a whole load of existing msbuild targets are re-used.
cmake.configure()

**Comment by sd185233** [comment]
Ignore the second part - got it with self.run('cmake "%s" %s' % (self.source_folder, cmake.command_line))

**Comment by memsharded** [comment]
> Thanks...There is no error now and I can see conandeps loaded, however it isn't loading any of the sub prop files. Tried adding one of the dep files instead and only it loaded, it did not load the prop files for each config.

Can you clarify this? I think it is not that the files will be automatically added to the IDE GUI, because they are imported from the ``conandeps.props``, which is the one that is shown. Is this what you mean? If you compile, the transitive dependencies are not found?

**Comment by sd185233** [comment]
I added the conandeps.prop file to the solution, it now loads without error, but there are no child property sheets under them.  From what I understand that top level prop file should then load the dependency prop file and it loads the correct prop file for the configuration?
![image](https://user-images.githubusercontent.com/69502342/119829270-fa8f7200-bef2-11eb-8144-54e4f35ad633.png)

**Comment by sd185233** [comment]
Have also tried just adding a single dep as follows - 
![image](https://user-images.githubusercontent.com/69502342/119830465-324ae980-bef4-11eb-8956-19084b2ee48d.png)

Includes is empty - 

![image](https://user-images.githubusercontent.com/69502342/119830721-750cc180-bef4-11eb-8870-cb335b23ae2a.png)

Expanding additonal includes does show the variables in inherited values and selecting macros shows the value is set OK.  
![image](https://user-images.githubusercontent.com/69502342/119830820-8d7cdc00-bef4-11eb-8030-c10271b9f930.png)

If I actually copy and paste the conan includes variable into additional includes then it works.

**Comment by memsharded** [comment]
I don't think the values load directly in those dialogs, as they are dynamic, and they also have conditions, that need to be evaluated.

I still don't fully get if you are getting build errors or it is that they are not showing in the IDE dialog, could you please tell exactly which build errors are you getting?

I am checking here locally, and things build and link, even if they don't show explicitly in the dialogs.

**Comment by sd185233** [comment]
I was sure when I tried with the visual_studio_multi generator yesterday that child prop sheet nodes were showing.  Just tried again and they don't.  

I am getting a build error from commandline and within the IDE.  It's because the header for the dependency is not found.  If I F12 into the header, I can see none of the Conan cache paths to my deps are in the search paths.

**Comment by memsharded** [comment]
I have done a whole new test in https://github.com/conan-io/conan/pull/9012/commits/f6d2435ca8385ea5cc98e4f19c0c857d4a8fccb3, that includes both the packages with dots, ``build_requires`` with ``force_host_context=True`` and transitive requires of it, and it seems to work fine.

I don't know what else could be failing on your side, if you could try to put together a reproducible case (send it privately, put in a github repo or elsewhere), that would help a lot.

Some other things that might be worth checking:
- Send again the generated files, while running from my new branch
- Send the vcxproj in which the ``conandeps.props`` have been added.
- Revise the test in https://github.com/conan-io/conan/pull/9012/commits/f6d2435ca8385ea5cc98e4f19c0c857d4a8fccb3 and try to make it fail, doing changes.

**Comment by sd185233** [comment]
Looking at the test, one difference I notice is using the MSBuildDeps and MSBuildToolchain generators.  Added both in as follows:

generators = "MSBuildDeps", "MSBuildToolchain"

I see this invalid settings.compiler value error.  setting.compiler is set to Visual Studio, not sure where msvc is coming from?
![image](https://user-images.githubusercontent.com/69502342/119960770-3b43c580-bf9d-11eb-8b2a-8272e035099c.png)

**Comment by memsharded** [comment]
We are closing 1.37 for release tomorrow Monday, so https://github.com/conan-io/conan/pull/9012 has been merged, apparently this issue has been solved. There might be something else, but as https://github.com/conan-io/conan/pull/9012 was fixing some things and was tested as an improvement, it has been merged.

I would suggest to open a new issue with the new feedback, thanks!
