### ISSUE TITLE
[question] Best practice for local developer workflow in a CI environment using lockfiles

### ISSUE THREAD

**Issue by fourbft** [conan-io/conan#9016]
- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

We have an environment with several hundred interdependent C++ components. Each component resides in its own git repository and we automatically build a conan package for each component whenever the source code for the component changes. A commit to the master branch of a component also triggers a chain of rebuilds of dependent downstream components in our CI so that they consume the new version of the changed component. The way, we ensure that downstreams always use the latest version of a component is by use of aliases; for every component we have a "component/LATEST-master@segment/release"-Alias that is made to always point to the latest version of the component built by the CI. That way, we do not need to change the recipes of all downstream components to consume the latest version of an upstream.

As you can imagine, there are quite a few such build chains underway during the day. 

Now, the use case this question is about is that of a developer who wants to make changes to some component somewhere in the middle of the dependency tree. He checks out the source code and tries to build it via `conan create ...`. But oftentimes, the requirements (i. e. upstreams) of his component are currently out of sync, because someone else has changed one of the upstream components and the CI has not yet finished to rebuild a consistent set of versions. So the developer often receives a "conflicting requirements"-error message from Conan for the set of `LATEST-master` versions required by his conanfile.

The way we used to solve that problem was, that we let our CI generate a lockfile whenever it created a consistent set of package versions for all components. So our developers could just grab the latest and greatest lockfile from the CI for their local development and do a `conan create -l lockfile ...` to locally build their component. This worked really well with Conan versions before 1.29. But since conan version 1.29, the lockfile semantics has changed and we cannot use the CI lockfile for this purpose anymore, as the CI creates the lockfile for a conanfile.txt that contains all our components and the developer now needs a lockfile that is specific for the component under development. The recommendation of Conan seems to be to create a new lockfile from the "big" lockfile for the specific component. This would be viable - though there still seems to be a bug in Conan that prevents this from working properly in the context of aliases (see https://github.com/conan-io/conan/issues/9014) - but it is one step more complicated for the developer than it used to be.

So the question is: is there a better way to enable this use case? 
Or would it be possible to change the lockfile concept in conan to make this use case work again. What we would need is only the capability to use a big lock file with many components to lock the build for a component in the middle of the locked tree with erverything upstream of that component locked and the component in the middle itself allowed to have a different/new version.

**Comment by memsharded** [comment]
Sorry @fourbft this was not responded back then.

This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
