### ISSUE TITLE
[question] Requires/build_requires for non-interface static libraries

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#9020]
I've been trying to implement gdcm recipe. I've decided to try experimental components feature in package_info. GDCM uses zlib as PRIVATE dependency. I've tried to copy dependencies from GDCMTargets*.cmake as "requires" in recipe. In shared configuration zlib isn't mentioned anywhere.

But then conan gave me this error. 

> ConanException: gdcm/3.0.9 package_info(): Package require 'zlib' not used in components requires

If zlib is static, then in shared configuration consumers don't need to know anything about zlib. What is the best approach in this case? Is there a way to transfer requirements to build requirements depending on different package options for consumed dependency? Do I need to add zlib::zlib to requires even if it shouldn't always be present in interface for consumers?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Nekto89 

At the moment, Conan is not aware of the different share-static and linkage specifics, so requirements are propagated down. ``private`` requirements have also some issues and are not recommended if possible to avoid them.

It is typically not a problem to have transitive requirements down, linkers are able to discard what is not being used, and impact on time is not very noticeable. I'd suggest to use regular requires for typical libraries dependencies.

The great news is that we have already started to work on this, as you can see in https://github.com/conan-io/conan/pull/8996, this is huge, so it is being develop for Conan 2.0, as it would be too breaking. Please keep tuned for the first 2.0 alpha releases, we would love feedback about it.

**Comment by memsharded** [comment]
This was addressed in Conan 2.0, which will be released very soon.
Check Conan 2.0 beta docs, or watch https://youtu.be/NM-xp3tob2Q for more information about the "requirement traits" that solve this issue. Thanks for the feedback!
