### ISSUE TITLE
[question] Is activate_run recursive ?

### ISSUE THREAD

**Issue by JPGygax68** [conan-io/conan#9029]
(I'm working on Windows)

I'm building an application that uses a shared library that I'm developing at the same time. That shared library depends on GLEW, which it obtains via Conan (`glew/2.2.0`).

I've marked the shared library as editable.

I'm running `activate_run` in the build directory of my application (which uses the `cmake_multi` and `virtualrunenv` generators) to ensure that the shared library will be found by the application.

The problem is that `activate_run` puts my shared library into the path, but not its dependency GLEW.

Am I missing something ?

**Comment by JPGygax68** [comment]
For a bit of extra info, here is the `package_info` method of the shared library:

```python
    def package_info(self):
        # Support consuming this package in "editable" mode.
        # Doing (in this directory):
        #   conan editable add . lsdisplay2/2.1@locsim/dev
        # will allow the consumer to use this library without it being present in the conan cache.
        if not self.in_local_cache:
            if   self.settings.arch == "x86": build_dir = "build32"
            elif self.settings.arch == "x64": build_dir = "build64"
            else: raise Exception("Unsupported architecture (settings.arch): %s" % self.settings.arch)
            # The following seems to work for packages installed to the local cache, but not for Editable packages.
            #self.cpp_info.bindirs = ["%s/bin/%s" % (build_dir, self.settings.build_type)]
            # ... so we try this:
            self.cpp_info.bindirs = ["%s/bin/Debug" % build_dir, "%s/bin/Release" % build_dir]
            self.cpp_info.libdirs = ["%s/src/%s" % (build_dir, self.settings.build_type)]
            self.cpp_info.libs = ["lsdisplay2%s" % ("d" if self.settings.build_type == "Debug" else "")]
```

**Comment by memsharded** [comment]
Hi @JPGygax68 

I am checking your issue. In theory yes, the ``virtualrunenv`` is transitive, it should also put transitive dependencies in the path (or LD_LIBRARY_PATH, DYLD_LIBRARY_PATH in other platforms)

Quick question: does it work correctly if the shared library is not in editable mode, but directly in the cache as a regular package?


Note: You might be interested in the new ``layout()`` feature in Conan 1.37: https://docs.conan.io/en/latest/developing_packages/package_layout.html. It is intended to improve over the "editable" experience. We are also doing many improvements in  the new ``VirtualEnv`` generator, but for those maybe wait till the next release 1.38.

**Comment by JPGygax68** [comment]
Thank you James! I will try this as soon as possible, unfortunately it might take a couple of days.

**Comment by memsharded** [comment]
Closing as staled and outdated, ``activate_run`` no longer exists in Conan 2.
Please create new tickets for any further question, thanks for the feedback!
