### ISSUE TITLE
[question] "requires" and version ranges including pre-releases

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#9035]
```
Class A(ConanFile):
    ...
    def set_version(self):
        self.version = "1.2.1-alpha1"

    def package_id(self):
        self.info.requires.package_revision_mode()
```

`$conan export . A/1.2.1-alpha1@user/channel`

```
Class B(ConanFile):
    ...
    def set_version(self):
        self.version = "2.0.0"

    def requirements(self):
        self.requires(f"A/[>=1.2.0 <1.2.2, include_prerelease=True]@user/channel")
```

`$conan export . B/2.0.0@user/channel`
`$conan install B/2.0.0@user/channel .....`

ERROR: Version range '>=1.2.0 <1.2.2, include_prerelease=True' from requirement 'A/[>=1.2.0 <1.2.2, include_prerelease=True]@user/channel' required by 'B/2.0.0@user/channel' could not be resolved in local cache

If edit the package A version as "1.2.1" (i.e. without the -alpha1) the version range expression and the build works.
Am I doing something wrong here?

The documentation mentions e.g. "-beta" in one example
 https://docs.conan.io/en/latest/versioning/version_ranges.html?highlight=include_prerelease#version-ranges ?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @iiknd 

There might be something else in your side that is missing in your report. I have done this test, and it works correctly:

```python
def test_version_range():
    pkga = textwrap.dedent("""
        from conans import ConanFile

        class A(ConanFile):
            version = "1.2.1-alpha1"
        """)
    pkgb = textwrap.dedent("""
        from conans import ConanFile

        class B(ConanFile):
            version = "2.0.0"
            requires ="pkga/[>=1.2.0 <1.2.2, include_prerelease=True]"
        """)
    client = TestClient()
    client.save({"pkga/conanfile.py": pkga,
                 "pkgb/conanfile.py": pkgb})
    client.run("create pkga pkga/1.2.1-alpha1@")
    client.run("install pkgb")
    assert "pkga/1.2.1-alpha1 from local cache - Cache" in client.out
```



A few hints, just in case:

- You don't need the ``set_version()`` method if you are doing only that (I guess that it is a simplification, but just in case)
- The ``package_revision_mode`` is the strictest one, probably shouldn't be needed for many cases, the idea is that if you are building the same package with same settings and same identical recipe revision again, to create a new package_revision, there is probably something that could be improved.
- It is not necessary to do a ``requirements()`` method, you can declare a plain ``requires=xxx`` too.
- Package names of only 1 letter are not allowed. Please use lowercase letter only for package names, this will be necessary in next Conan 2.0 major version.

The test passes with your methods too, I also did try with your code as well, and also that if fails with include_prereleases=False (as expected). Could you please double check?

**Comment by iiknd** [comment]
Hi @memsharded

> You don't need the set_version() method if you are doing only that (I guess that it is a simplification, but just in case)

> It is not necessary to do a requirements() method, you can declare a plain requires=xxx too.

>Package names of only 1 letter are not allowed. Please use lowercase letter only for package names, this will be necessary in next Conan 2.0 major version.

Yes, the code I provided is a simplification from actual code

> I also did try with your code as well, and also **that if fails with include_prereleases=False (as expected).**

I'm confused, it's supposed to fail? Documentation says:

> >1.1 <2.1, include_prerelease=True]            # Would e.g. accept "2.0.0-**pre.1**" as match

$ conan search
Existing package recipes:

pkga/1.2.1-alpha1@
pkgb/2.0.0@  # requires ="pkga/[>=1.2.0 <1.2.2, include_prerelease=True]"

Shouldn't the build of pkgb resolve the "pkga/1.2.1-alpha1@" as it fits inside the version range and include_prerelease is enabled?

This is what I'm trying to achive, an requires expression that always picks the latest prerelease version from major.minor.patch as our CI produces alpha|beta|rc snapshots on regular basis and I want to declare the requires so that I don't need to explicitly change the prerelease part every time for each dependency.

**Comment by memsharded** [comment]
> I'm confused, it's supposed to fail? Documentation say

Yes, I am saying if the value is ``False``, it will not include pre-releases, as expected. If the value is True, it will allow pre-releases, otherwise they are discarded (by default, not stable, semver doesn't want to resolve to them). The test uses the value ``True`` as you intended, but I was saying that changing the value to False produced a expected failure of not resolving to it.
