### ISSUE TITLE
[bug] tools.get raises AuthenticationException

### ISSUE THREAD

**Issue by Psy-Kai** [conan-io/conan#9036]
### Environment Details (include every applicable attribute)
  * Operating System+version: KUbuntu 21.04
  * Conan version: 1.37.0
  * Python version: 3.9.5

Conan version < 1.37.0 works properly.

### Steps to reproduce (Include if Applicable)
`conanfile.py` with
```
    def build(self):
        tools.get("https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.gz", destination=self._folder_name)
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
conan output
```
        tools.get("https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.gz", destination=self._folder_name)
        AuthenticationException: 403: Forbidden
```

**Comment by Psy-Kai** [comment]
The url got changed from "https://developer.arm.com/...." to "https://armkeil.blob.core.windows.net/..." and conan 1.37.0 cannot resolve the url change. conan < 1.37.0 can resolve the old url.

**Comment by memsharded** [comment]
I have been able to reproduce this, thanks for the report.
I am investigating, so far this is surprising, nothing changed in ``tools.get()`` for the last releases.

**Comment by memsharded** [comment]
Apparently this PR https://github.com/conan-io/conan/pull/8947 is causing this behavior, that server is doing a 403 based on the user agent? 

The change in user agent is:

1.37:  Conan/1.37.0 (Windows 10; Python 3.6.0; AMD64) python-requests/2.25.1
1.36:  Conan/1.36.0 (Python 3.6.0) python-requests/2.25.1

The offending char seems to be the ``;``, without it it works fine. This would be an issue on that specific server, in theory ``;`` can be used here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by memsharded** [comment]
Hi @Psy-Kai 

Is it possible to raise this issue with arm, the owners of ``https://developer.arm.com/``? In this case, it seems their server is misconfigured or something, and throwing 403 for valid user-agent (which in any case, it shouldn't, as not related at all to auth?)

**Comment by Psy-Kai** [comment]
I could try raise this issue with arm. Since I can use the new url directly I am not really affected. Thanks for your investigation. And since its not a conan bug we might be able to close this issue? Or do you want leave it open? Maybe others will get the same error (from wrong configured http servers).

**Comment by memsharded** [comment]
Yes, lets leave this open for a while, so you can reference it too if you will try to raise it to arm.

If no further reports in a few weeks, then we will close it, thanks!

**Comment by Viatorus** [comment]
We have the same issue. @Psy-Kai Did you contact arm already?

**Comment by memsharded** [comment]
As a temporary workaround, besides the other URL that @Psy-Kai pointed, it is possible to pass custom headers to ``tools.get()``, so passing a custom ``User-Agent`` one there might solve the issue.

**Comment by Viatorus** [comment]
I just raised a ticket on ARM.

I investigated further and they are okay with the semicolon but they don't like Python.

If I change the user-agent from:
> 1.37: Conan/1.37.0 (Windows 10; Python 3.6.0; AMD64) python-requests/2.25.1

to:
> 1.37: Conan/1.37.0 (Windows 10; Brainfuck 2.7.1; AMD64) python-requests/2.25.1

Everything works.

So my suggestion: Write conan in Brainfuck. ;)

**Comment by memsharded** [comment]
> 1.37: Conan/1.37.0 (Windows 10; Brainfuck 2.7.1; AMD64) python-requests/2.25.1

That further proves it is something weird on their side.


> So my suggestion: Write conan in Brainfuck. ;)

Seconded!! 🤣

**Comment by Viatorus** [comment]
After some delay, here is the final answer from ARM:

> The change would require changes in firewall settings. 
> We've discussed the issue with our Security team and unfortunately this change was rejected 

So (we) either host the binaries else where or use a custom user agent when using `tool.get`.

**Comment by Poupine** [comment]
Hi, could you post an example on how to change the User-Agent/how to print the one that's being used when tools.get() is called? 
I'm having an issue with tools.get generating a 403 error as well, but only when NOT compiling in Release. 

The URL is correct (https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-0-1/fbx202001_fbxsdk_linux.tar.gz) as I can download from chrome and it also works when I'm compiling in Release.

EDIT: For thos who may be wondering as well how to change the User-Agent:
`tools.get(URL, headers={"User-Agent": "1.37: Conan/1.37.0 (Windows 10; Brainfuck 2.7.1; AMD64) python-requests/2.25.1"})`

And I confirm that Brainfuck seems to be accepted. Guess I will change my recipe to include this change for now!

**Comment by memsharded** [comment]
Quick update: we have plans to remove at least the ``python-requests`` part of the User-Agent, which might help to reduce some of these issues. Still, the Python part is relevant and useful, we wouldn't like to remove it, there is really no reason why a server would accept Brainfuck and not Python.

**Comment by Poupine** [comment]
> Quick update: we have plans to remove at least the `python-requests` part of the User-Agent, which might help to reduce some of these issues. Still, the Python part is relevant and useful, we wouldn't like to remove it, there is really no reason why a server would accept Brainfuck and not Python.

For me, the server accepted Python actually. I ended up using: 
`1.40.3: Conan/1.40.3 (X11; Linux x86_64) python 3.8.5; AMD64) python-requests/2.25.1`

**Comment by elsamuko** [comment]
fwiw: I got a AuthenticationException from github, because I had old credentials in a forgotten `.netrc`. It helped to enable detailed logging with
```
        import logging
        import http.client as http_client
        http_client.HTTPConnection.debuglevel = 1
        logging.basicConfig()
        logging.getLogger().setLevel(logging.DEBUG)
        requests_log = logging.getLogger("requests.packages.urllib3")
        requests_log.setLevel(logging.DEBUG)
        requests_log.propagate = True        
```

**Comment by memsharded** [comment]
Thanks for the comment @elsamuko 

In any case, ``tools.get`` has already been superseded in 1.X by ``from conan.tools.files import get``, and it has been removed in 2.0. I am closing this ticket as outdated.

Also, in Conan 2.0, there is a new ``source_credentials.json`` mechanism to define credentials for sources download which can help: https://docs.conan.io/2/reference/config_files/source_credentials.html

**Comment by elsamuko** [comment]
The new `conan.tools.files.get` is still using `requests`, which is honoring the `.netrc`:  
https://requests.readthedocs.io/en/latest/user/quickstart/#custom-headers

**Comment by memsharded** [comment]
Thanks for the feeback.
I'd say the ``.netrc`` is a different issue than the initially reported one (a specific server rejecting valid user-agents arbitrarily), and my comment above could have helped, as the new ``source_credentials.json`` can inject ``auth`` field to ``requests``, which has higher priority than ``.netrc``, so it might be more convenient to manage at the Conan level.

**Comment by elsamuko** [comment]
Yes, of course. I "seized" this issue for those who search on Google for "conan AuthenticationException".  
The logging and netrc tipps could be useful in a wiki or troubleshooting FAQ, though :)
