### ISSUE TITLE
[feature] Provide [conf] command line support 

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9038]
[conf] items are increasing, and I get more and more user feedback that it would really help to have cli support for this.

So something like:

```
conan install .... -c xxxx.yyyy:var=value
```

Could help in many cases.

**Comment by franramirez688** [comment]
@memsharded @tapia does it make sense if `-c` is available for `conan create` as well?

**Comment by memsharded** [comment]
> @memsharded @tapia does it make sense if -c is available for conan create as well?

Yes, it does. Basically, it might be needed in all install and create commands: create, info, export-pkg, test, install. It might be also necessary later in other commands, even ``download``, for example, if the [conf] contains something like the number of parallel jobs to download.

I suggest starting with the 2 main cases only: create and install. We can add it later to other commands as necessary.

Note this is an experimental feature, there might be some rough edges, specifically the split between ``tools.*`` and ``core.*`` might have some challenge there, we can discuss it anytime if you need.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/9103, will be in 1.38
