### ISSUE TITLE
[question] build_policy attribute options are not exhaustive

### ISSUE THREAD

**Issue by vdsbenoit** [conan-io/conan#9042]
The options of [the `build_policy` attribute](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#build-policy) are `missing` and `always`.

What about the [other build policies](https://docs.conan.io/en/latest/mastering/policies.html) ? Is it intended ?  

Would it be possible to define `outdated` as default build policy in the class attributes ?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @vdsbenoit 

Yes, this is completely intended. The in-recipe build policies should be used for some exceptional cases. The implemented policies are there for:

- Missing: There are packages that always need to be built from sources in the installing machine (like drivers that need to compile with the specific kernel or something in the machine that will make the binary specific to that machine)
- Always: Legacy use case, where it was possible to force re-fetching source code, assuming that it could be outdated. This will probably be removed in Conan 2.0, as we have learned this is not a good practice.


The outdated policy is completely being removed in Conan 2.0, as when using revisions, the outdated cased cannot happen anymore. I recommend start using revisions now, it has always been approved by the tribe and implemented in the develop2 branch, it will be the default in Conan 2.0. So it doesn't make sense to implement this policy in recipes.

**Comment by vdsbenoit** [comment]
Hi @memsharded ,

Thank you very much for the quick reply! 

That makes sense, thank you for the clarification! I'm closing this issue.
