### ISSUE TITLE
add --paths flag to conan search

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan#9048]
My use case:

I want to package clang compiler and populate `CXX` in `[env]` section of conan profile dynamically https://github.com/conan-io/conan-center-index/issues/5724

Because conan profile is not dynamic, i tried to use `conan info`. Unfortunately, `conan info` completely useless - it does not work as intended and produces not-existent package id even if i set `--profile` flag (I want to use existing package!).

```bash
export PROFILE_UPDATE=clang_libcpp ; \
  conan profile update \
    env.CXX=$(conan info llvm_9/master@conan/stable \
             -s build_type=Release \
             --paths \
             --only package_folder \
             --profile $PROFILE_UPDATE \
             | grep package_folder \
             |  cut -d ":" -f2- \
             | xargs echo -n\
           )/bin/clang++ $PROFILE_UPDATE
```

After multiple failed attempts with `conan info` i had to use combination of `conan config` and `conan search`

```bash
export PROFILE_UPDATE=clang9 ; \
  conan profile update \
    env.CXX=$(conan config home)/data/llvm_9/master$llvm_9_BUILD_NUMBER/conan/stable/package/$(conan search llvm_9/master$llvm_9_BUILD_NUMBER@conan/stable --raw \
              | grep Package_ID | cut -d ":" -f2- \
              | xargs echo -n | tail -1\
            )/bin/clang++ $PROFILE_UPDATE
```

Can you see how ugly, unreliable, not cross-platform is that approach? I just want to get `package_folder` of existing package!

Please add `--paths` flag to `conan search`. 

Ideally, add `--only` flag to `conan search` so it will be able to filter data and print only `package_folder`

**Comment by czoido** [comment]
Hi @blockspacer,

I think that the correct way of approaching this is declaring the `env_info` in the `package_info` of the clang recipe and then it will be set for the consumers of the `build_require`.

You can have a look at how other recipes in conan-center-index do this:
- https://github.com/conan-io/conan-center-index/blob/41d4fbb8c218f9d938ccb8b9d888bff52002e62e/recipes/cccl/all/conanfile.py#L76-L81
- https://github.com/conan-io/conan-center-index/blob/cd325616aab3f9373a450f32805fbbcd50f901f3/recipes/android-ndk/all/conanfile.py#L194-L195

We are also working in new tools that will be the standard for Conan 2.0 that make easier handling the environment variables in recipes, you also may want to check that: https://docs.conan.io/en/latest/reference/conanfile/tools/env/environment.html

Does this help you?

**Comment by blockspacer** [comment]
@czoido 
>  declaring the env_info in the package_info of the clang recipe and then it will be set for the consumers of the build_require.

I want to compile code of arbitrary recipes using clang compiler packaged via conan i.e. i want to use clang without need to modify `build_require` in each recipe. 
Is that possible?

UPD: 
Ill try to set `[build_requires]` in conan profile
