### ISSUE TITLE
[question] How to use scm without conan create?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#9049]
Hi,
currently I have a recipe, which defines scm. I don't have source() method defined.
If I use 'conan create', everything is fine, source is downloaded from git.
However if I do separate conan export, conan install, etc. steps source is not downloaded.
How to handle that "elegantly"? Do I have to define something in conanfile.py so that install or 
something else picks it up, or do I have to call 'conan source' manually? How can I achieve
the very same thing that is done by 'conan create'?
Thanks,

**Comment by czoido** [comment]
Hi @harsszegi,

Thanks for your question, if you want to do that with `export` and `install` commands check if this works for you:

- You have a conanfile.py with scm defined to some external repo.
- First doing a conan export of the package (let's call it _mylib/1.0_): `conan export . `
- Now do an install of the just exported conan reference: `conan install mylib/1.0@ --build mylib` (note that using the @ we are referring to the package exported in the local cache)

Please tell me if this helps

**Comment by harsszegi** [comment]
Thanks a lot, it appears working
