### ISSUE TITLE
Environment: Mingw on linux host for windows cross compilation

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [conan-io/conan#905]
Hi there,

i want to use mingw with a linux (arch) host to cross compile windows binaries. I assumed, that i have to set the corresponding compiler with the `-s compiler=mingw` flag during the installation with building, but this is not listed in the ~/.conan/settings.yml.

So what should i do to make conan aware of the mingw cross compiler?

**Comment by memsharded** [comment]
For cross-compiling, you have to make it aware of that, and it is possible that the build helpers (``CMake``, ``ConfigureEnvironment``) are not very well prepared for that yet. Ongoing work is being done: https://github.com/conan-io/conan/pull/874

Some tips:
- The compiler would be ``gcc`` not mingw, that is a distro of the compiler. You will also have to set the ``-s os=Windows`` setting.
- When settings are not listed in ``.conan/settings.yml``, they can be added there. Just take care of sharing/syncing that file with your team.
- The cross-compilation must be instructed inside the recipe ``build()`` method. If using cmake, you can use the ``CMake`` helper to help to translate the conan settings to the matching cmake command line arguments. But remember that that is just a helper, you could code or hardcode it yourself:

```python
def build(self):
    if platform.system() == "Linux" and self.settings.os == "Windows":
        #cross building
        self.run("cmake -DCMAKE_CXX_COMPILER=/hard/code/to/cross-compile-gcc...")
        ....
```

Conan is designed in a way that when it can factor common utilities, like the ones in the ``CMake`` helper, it will do it. But if the provided functionality does not cover cases (in this case, cross-building), it is always possible to "hack" a solution.

In any case, please keep tuned for next releases, as cross-compiling will be one of the things that will be gradually improved.

**Comment by cguentherTUChemnitz** [comment]
First of all i want to thank you for your very fast response times for my questions.

I am going to build a Qt 5.8 package encapsulating their new configuration. My use-case is to provide a package which has by default as less as possible external dependencies and is as most as possible optimized. Further external dependencies and Qt modules can be activated with conan options.

I am now at the point to use this package also for cross compilation from linux to windows. The current state (work in progress) is open sourced here:
https://github.com/cguentherTUChemnitz/conan-Qt/tree/mingw-cross-compilation

Your idea to hack the cross compilation into the conanfile.py is a good point. Nevertheless the Qt build system does not use cmake. Therefore i had to patch a lot of stuff to handle their external deps, etc. Therefore i use the `ConfigureEnvironment(self)` and `command_line_env` statements to generate the prepended environment variables. The problem i am focusing now is that `ConfigureEnvironment(self)` is not aware of possible cross compilation. So it generates a `_conan_env.bat`, when i run `conan test_package -s os=Windows` on a linux host. As a consequence the linux host is not able to provide the prepended env vars and the building crashes with the following output:
`ERROR: Qt: Error 32512 while executing cd qt5 && call _conan_env.bat ./configure ...`

So is there a possibility to produce linux host compatible `command_line_env`, even with `-s os=Windows`?

**Comment by cguentherTUChemnitz** [comment]
Hi there. I solved so far the problem by hacking the decision into my packagebuild.py. I think we should talk about the desired behavior of the `command_line_env`, especially in the scope of cross compilation.

In my use-case the python `platform.system()` defines the build system and the `self.settings.os` defines the target platform to build the package for. 

The [command_line_env platform decision](https://github.com/conan-io/conan/blob/6aff328b6e2e9f56c693926ef3b64a58a6d8cdcc/conans/client/configure_environment.py#L125) is based on the `self.settings.os`. So the command line generator is switched based on the target platform. In my eyes the desired behavior is to choose based on the build platform in contrast to the target platform.

So the way i solved it is by bypassing the linked platform decision and calling directly the `ConfigureEnvironment(self)._gcc_env()` based on `platform.system()`.

best,
Christian

**Comment by lasote** [comment]
Thanks for your detailed feedback. We have pending a ConfigureEnvironment refactor so I add it to the list of things to improve.

**Comment by lasote** [comment]
Hi, ConfigureEnvironment is going to be deprecated in favor of specific build environment classes, so you can choose the better to use in your case. We hope to release 0.20.0 with these improvements today.

https://github.com/conan-io/docs/blob/develop/howtos/migrate_to_new_environment_management.rst
