### ISSUE TITLE
Upload package without authentication

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#906]
I'm running _conan_server_ in my host and I would like allow all users to upload their packages.  
My first idea was uses LDAP to solve the authentication, although, I didn't see some approach on conan.io documents.

So, my workaround was allow a bunch of users, without password.  
At first time, I added some like this, in my _conan_server/server.conf_ :

```
[users]
foobar:
qux:
```

As you can see, the users _foobar_ and _qux_ can upload their packages, without password.

However, when a new user needs upload a package, a new register is necessary.  
So, I would like allow **any** user to upload.  
My idea is add some new rule in users session:

```
[users]
*: *
```

Is it possible to be implemented?

**Comment by memsharded** [comment]
LDAP or other external auth service is not implemented in conan_server, sorry.

I am not sure we want to implement this behavior, it sounds a bit extreme, and can't imagine such scenario in any real conan setup. Can you please tell me a bit more why would you like to do so? I am very curious :) 

In the meantime, "hacking" it would be pretty simple, just go to the conan_server source: https://github.com/conan-io/conan/blob/develop/conans/server/service/authorize.py#L96 in your server, change the logic of that line to ``return True``, and you will get it! Writing a script that does it for you after a conan upgrade or just cloning the repo and running from sources (recommended running with gunicorn) and pulling from the latest master to upgrade, would be also easy.

**Comment by uilianries** [comment]
We are using Gitlab (local) for C/C++ projects. The Gitlab uses LDAP to authenticate all developers, so, we don't need create a new authentication table or something like that.  
I have included Conan server (local) to solve the ancient problem with C/C++ package management (thanks, Conan!). My idea is that each project could be a Conan package.  

The problem is, how authenticate all users, using ~~LDAP~~ or something, without replicates all users in a file?
The second point is, we would not like to expose all passwords in a file, even because we already have LDAP.  
If I put all users in server.conf, I will need "manage" all names (add, update or delete). But our Conan server is local, so, I don't think that is a real problem, allow all users.  
This is my scenario ;)  

My point is a rule that allow any user to upload, but is necessary have a name, by _conan user_.  
I just thought in put this rule in Conan main development, to avoid a "upstream" sequence. Even I could develop this feature and create a MR.

Your hack is very simple and fit very well to the problem. If is not possible put this feature in Conan, I will change the line that you pointed me (by fork).  

Thanks!

**Comment by memsharded** [comment]
OK, now I understand, thanks for the explanation :)

Yes, the truth is that I wouldn't be very confident in merging such PR, as it has a big potential of being misused and cause troubles. Even if conan is MIT, and the AS-IS and all disclaimers, having the possibility of  not controlled write access could produce a disaster and people will get upset. So, by now, I prefer the inconvenience of having to manually edit the ``server.conf`` file and edit there the user names and passwords, and trust the server sysadmin to have proper security on the file.

So my suggestion would be to use the hack, keep working on it, deploying conan, etc. We might encounter other side effects and related issues. Once things are more stable, lets revise all related issues, and think what makes sense for both easy maintenance and security.

If this makes sense, please close the issue, and then reopen or submit a new one when necessary. Thanks very much for your feedback!

**Comment by uilianries** [comment]
Yes, make sense for me.

Thanks a lot!
