### ISSUE TITLE
[feature] Add exclude_root_packages argument to imports().copy

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#9060]
Currently copy has an `excludes` argument, but that is not always convenient. It would be nice if you could just exclude whole packages.
```
def imports(self):
    self.copy("*",src="bin",dst="bin",exclude_root_pacakges=["some_package"])
```

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by taogeng** [comment]
goog suggestion!!!

**Comment by memsharded** [comment]
``imports()`` removed from Conan 2.0, closing this ticket as outdated
