### ISSUE TITLE
[question] Why no system_build_requirements?

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#9061]
It seems there should be a system_build_requirements for system requirements, that you only need when building from source. No such method exists. Is there a reason, or is it just not there because it wasn't considered or hasn't been done yet.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @rconde01 

``system_requirements()`` is not an actual requirement definition, but a helper to call some system package manager to install something in the system. It can be applied equally to something that you need to link with or to a build tool, there is no difference.

``build_requires`` is a requirement definition of a build tool. Whether this tool is contained in the package, or is installed in the system, and the recipe is just a helper or proxy to the system installed tool, is also the same.

So depending on what you mean, either of the two above would do the job, I don't see anything different that would require a different new method or attribute.

**Comment by rconde01** [comment]
I guess it’s weird that it’s “system_requirements” and not “runtime_requirements” or something. But that’s fine.
