### ISSUE TITLE
[feature] Do the CMake build in a different directory than the source when using the CMakeDeps generator

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#9064]
When using the `cmake` generator, I was able to set a CMake build dir with:
```
cmake = CMake(self)
cmake.configure(build_dir=self.build_subfolder)
```
It's not available as of Conan 1.37.0 when using the CMakeDeps generator (`CONAN_V2_MODE` enabled). It gives me this error:
```
TypeError: configure() got an unexpected keyword argument 'build_dir'
```
It's making it harder to build a library such as SDL2 that has a check in CMake that makes sure the source directory does not match the binary directory. Simple fix would be to add `build_dir` to the `configure()` method for CMakeDeps to match the Conan 1.x behavior. I suppose Conan could just build to a subdirectory automatically, if you'd prefer not having an explicit parameter.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @ssrobins 

The definition of source and build folder is becoming explicit in Conan 1.37 with the ``layout()`` method.

- Make sure you are using the ``CMake()`` from ``from conan.tools.cmake import CMake``
- Do not pass arguments to it
- Add a ``layout()`` https://docs.conan.io/en/latest/developing_packages/package_layout.html#package-layout like:
```python
def layout(self):
        self.folders.build = "cmake-build-{}".format(str(self.settings.build_type).lower())
        self.folders.generators = os.path.join(self.folders.build, "generators")
        self.folders.imports = self.folders.build
        self.folders.source = "src"
```

The idea is to centralize the definition of project folders layout, so everyone can benefit from it: from the toolchain and ``CMake()`` to the ``editable`` packages and local flow (all local development commands will work without arguments, only --install-folder is still necessary in Conan 1.X)

**Comment by ssrobins** [comment]
Worked perfectly, thanks! Looks like I need to spend some quality time with the docs, particularly the changelog before I post again :)

**Comment by memsharded** [comment]
Still an experimental feature, so expect progress in the next iterations, and as always, feedback is welcome!
