### ISSUE TITLE
[question] package reproducability on a living branch

### ISSUE THREAD

**Issue by dornbirndevelops** [conan-io/conan#9065]
Hello Y'all!

I have two repositories, one containing the conan receipe, the other providing some source code.
I would like to ensure reproducability if somebody comes to me saying that there was an issue with package revision ####.
Therefore, whenever the package receipe is exported, the revision should be changed to the latest commit that is available at time X. -> `main` should become `fa911e50e6e7ea6ff94f6a323518effd8c9a0af6`
But unfortunately, as soon as the source code repository advances by any commit, upon re-export, conan claims that nothing has changed.

Things I tried so far:
- implementation of the `source` method -> ERROR: Not a valid 'git' repository or 'git' not found.
- `revision_mode = "scm"` based on [documentation](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#revision-mode)-> ERROR: Cannot detect revision using 'scm' mode from repository at '~/receipe': 'None' repository not detected
- `scm.revision = "auto"` based on [documentation](https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm) -> ERROR: Not a valid 'git' repository or 'git' not found.

my `conanfile.py`
```python
from conans import ConanFile, CMake

scm_subfolder = "mylibrary"

class MyLibraryPackage(ConanFile):
    name = "mylibrary_ext"
    version = "1.0"
    settings = "os", "arch", "compiler", "build_type"
    options = {"shared": [True, False]}
    default_options = {"shared": False}
    generators = "cmake_find_package"
    no_copy_source = True

    scm = {
        "type": "git",
        "subfolder": scm_subfolder,
        "url": "https://github.com/dornbirndevelops/conan-example-library.git",
        "revision": "main", # living branch that advances over time
    }

    def requirements(self):
        self.requires("boost/1.75.0@")

    def _get_configured_cmake(self):
        cmake = CMake(self)
        cmake.configure(source_folder=scm_subfolder)
        return cmake

    def build(self):
        self._get_configured_cmake().build()

    def package(self):
        self._get_configured_cmake().install()
    
    def package_info(self):
        self.cpp_info.includedirs = ['include']
        self.cpp_info.libs = ['mylibrary']
        self.cpp_info.libdirs = ['lib']
        self.cpp_info.bindirs = ['bin']

```

What am I doing wrong? Any help appreciated.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by dornbirndevelops** [comment]
## Update
the initial idea of having the source code and the package in a different repository was just to disallow the build of the package to parties that are not authorized to access the source code.

it turns out that the scm feature does not upload a source code snapshot to the conan server, which is what i originally intended.

**Comment by memsharded** [comment]
Hi @dornbirndevelops 

Sorry to come late, but yes, that is the purpose of SCM, to capture only the coordinates of the repo, not the source itself. Happy that you found it and works for you.
