### ISSUE TITLE
[bug] No isolation of source files when building multiple Conan packages in parallel

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#9067]
Hi Conan experts,

at present I don't find a solution to resolve the following isolation issue:

I have a Conan recipe that fetches SCM data from a very large Git repository (> 2 GB). Two Conan packages shall be created from this Conan recipe. In order to create these Conan packages I use a Jenkins job that runs two `conan create` commands in parallel. Unfortunately both command try to clean and pull the source files which causes the following isolation issue for one of the packages:

`package/version@user/channel: SCM: Getting sources from url: 'https://<repo-url>.git'`

Is there any solution to solve that issue (apart from using different conan caches - which is a blocker as some dependencies are also very time consuming to fetch and waste a lot of disk space - or building sequentially?) 

Many thanks and best regards,
Markus

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04.5 LTS
  * Compiler+version: GCC 7.5.0
  * Conan version: 1.33.1
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
  * Create a conanfile.py with scm attribute that fetches a large Git repository (e.g. with LFS files, etc.)
  * Create two packages with different profiles in parallel (via `conan create`)
  * By chance one of the builds will raise an `SCM: Getting sources from url: 'https://<git-repo-url>.git'` error

**Comment by memsharded** [comment]
Hi @gpxricky 

Yes, you are hitting some concurrency issues. The Conan cache is not intended for concurrent usage, though it has some internal mechanisms for some limited cases, it is not the general case. In theory the parallel "create" could work, but maybe the source SCM part of it is not correctly managed, or it got some changes and lost some of the protections (it is difficult to test for race conditions). I have had a look, and the step of fetching sources in the cache for the create seems to be correctly protected:

```python
            with package_layout.conanfile_write_lock(self._output):
                set_dirty(base_build)
                self._prepare_sources(conanfile, pref, package_layout, remotes)  # THIS does the SCM fetch
                self._copy_sources(conanfile, base_source, base_build)
```
But this is difficult to know and reproduce.


The heavy part of the building will probably work fine, as that is done in independent folders, one per package_id. Have you tried launching the 2 jobs with enough time difference to let the first one finish the source fetching? I see that you are using Git LFS, so I guess the cloning time is simply very high?

We are working in a new cache for Conan 2.0, and we will give a try (can't guarantee we will manage to succeed in it) to improve concurrent access. But it is unlikely we will provide this feature in Conan 1.X.

**Comment by gpxricky** [comment]
Thanks for your feedback. So the only chance is to run these two jobs in sequence. Conan 2.0 may improve that situation, but it's unclear. I'll close this issue.
