### ISSUE TITLE
Get only package name and version via conan info

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#907]
Hi,

To upload only the package that is currently build on our CI Server, I would need to get the name and version from the conanfile. As the version number is created from a fixed version and a build number (from environment variables), i can't grep them out of the file.

The conanfile looks something like this:
```python
from conans import ConanFile, CMake, os
build_name = "-build" + os.getenv("BUILD_ID", "-local")

class MyConan(ConanFile):
    name = "MyPackage"
    version_number = "0.1.1-alpha"
    settings = "os", "compiler", "build_type", "arch"
    short_paths=True
    version = version_number + build_name
...
```

I would like something like `conan info --name` resulting in `MyPackage/0.1.1-alpha-build12345`

Is there already a way to do this?

Best,
Claas

**Comment by memsharded** [comment]
Are you asking for a conanfile.py in your user space?

Probably ``conan info`` is not a good candidate, because it outputs the dependency graph of the current conanfile, not just the conanfile. Or you mean the "PROJECT" string of the ``conan info`` command to properly show the package and version?

```bash
conan info --only none
```
will output just the names (including the dependencies, and the creation dates. Probably the creation dates could be hidden too, that seems a bug). Changing the PROJECT => Pkg/version would be good?

**Comment by claasd** [comment]
No, i meant the former.
I have the conanfile in m userspace, and I need to know the correct name and version.

```bash
conan info --none
```
 outputs the following:
```bash
Version range '~0.2' required by 'None' resolved to 'CMakeMacros/0.2-build99@cab/unstable'
Version range '~1.9' required by 'None' resolved to 'BTC.CAB.Commons/1.9.0-alpha-build6@cab/unstable'
Version range '~1.8' required by 'None' resolved to 'BTC.CAB.Logging/1.8.0-alpha-build9@cab/unstable'
Version range '~0.2' required by 'BTC.CAB.Commons/1.9.0-alpha-build6@cab/unstable' resolved to 'CMakeMacros/0.2-build99@cab/unstable'
BTC.CAB.Logging/1.8.0-alpha-build9@cab/unstable requirement BTC.CAB.Commons/[~1.9]@cab/unstable overriden by your conanfile to BTC.CAB.Commons/1.9.0-alpha-build6@cab/unstable 
Version range '~0.2' required by 'BTC.CAB.Logging/1.8.0-alpha-build9@cab/unstable' resolved to 'CMakeMacros/0.2-build99@cab/unstable'
Version range '~1.9' required by 'BTC.CAB.Logging/1.8.0-alpha-build9@cab/unstable' valid for downstream requirement 'BTC.CAB.Commons/1.9.0-alpha-build6@cab/unstable'
Version range '~0.2' required by 'BTC.CAB.Commons/1.9.0-alpha-build6@cab/unstable' valid for downstream requirement 'CMakeMacros/0.2-build99@cab/unstable'
BTC.CAB.Application/1.8.0-alpha-build-local@PROJECT
BTC.CAB.Commons/1.9.0-alpha-build6@cab/unstable
    Creation date: 2017-01-20 09:10:54
BTC.CAB.Logging/1.8.0-alpha-build9@cab/unstable
    Creation date: 2017-01-20 09:42:19
CMakeMacros/0.2-build99@cab/unstable
    Creation date: 2017-01-19 15:53:24
CMakeMacros/0.2-build99@cab/unstable
    Creation date: 2017-01-19 15:53:24
CMakeMacros/0.2-build99@cab/unstable
    Creation date: 2017-01-19 15:53:24
CMakeMacros/0.2-build99@cab/unstable
    Creation date: 2017-01-19 15:53:24
```

If the first 6 lines would not be there, I could capture the first line and remove the @PROJECT, no problem there. But the first lines should not be there ...

**Comment by memsharded** [comment]
Are you using python for the task? That would be one-liner:

```python
re.search('(\S+)@PROJECT', text).group(1)
```

**Comment by claasd** [comment]
I am in groovy, so still a one liner:
```groovy
text.find('(\\S+)@PROJECT') { match, name -> return name; };
```

The --only features is not really well documented. for now, @worksforme @closed. :-)

**Comment by memsharded** [comment]
Submitted issue to docs: https://github.com/conan-io/docs/issues/143

Also, just submitted some improvement here: https://github.com/conan-io/conan/pull/908

**Comment by karelv** [comment]
With conan 1.6.1 I needed to adapt the command line a bit:

    conan info conanfile.py --only None | grep @PROJECT$ | cut -d'@' -f1

**Comment by Mark-Hatch-Bose** [comment]
In 1.8.3 in Jenkins Groovy:
```
 ret = sh(script: 'conan info conanfile.py --only None', returnStdout: true)
 env.PACKAGE_NAME = ret.find('(.*\n){1}@PROJECT') { match, name -> return match[1]; };
```

**Comment by memsharded** [comment]
For reference, now there exist the ``conan inspect .`` command that allows easier retrieval of package name, version and other attributes.
