### ISSUE TITLE
[bug] CMakeDeps generator: component and package with the same name

### ISSUE THREAD

**Issue by alex-700** [conan-io/conan#9071]
Hi!

During refactoring #8971 behavior of `tvalue` [macro](https://github.com/conan-io/conan/blob/80e99ca9a7d730e95adbc8bde5aa33da4f4fbb44/conan/tools/cmake/cmakedeps/templates/target_configuration.py#L35) was changed by adding some special case when `pkg_name` and `comp_name` are the same. 

It accidentally break this case, because `tvalue` macro is inlined in declaration of several variables (see [this](https://github.com/conan-io/conan/blob/80e99ca9a7d730e95adbc8bde5aa33da4f4fbb44/conan/tools/cmake/cmakedeps/templates/target_configuration.py#L98) for example). So these variables have one name (`{pkg_name}_{comp_name}_...`) during setting and the other name (`{comp_name}_...`) during using it in `set_property`.

cc @lasote

**Comment by lasote** [comment]
Thanks so much for reporting. I submitted a PR to the `1.37.2`, what a pity we just released `1.37.1` 😣

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/9073, will be released in 1.37.2
