### ISSUE TITLE
[question] Determine remote recipe version when building locally

### ISSUE THREAD

**Issue by marknva1** [conan-io/conan#9078]
As part of our workflow we are creating RPM during the conan packaging step which use the Jenkins build number as the release label. When the build happens in the local cache the release numbers can get out of sync. Is there an attribute or method that can be used in the conanfile.py to determine the current version of the remote recipe? Thanks.

**Comment by memsharded** [comment]
Hi @marknva1 

Not sure if I fully understood your issue, and what you mean with "When the build happens in the local cache the release numbers can get out of sync."

Regarding the check, recipes are a "definition" of a package, they are completely agnostic about remotes, even their existence, so it is not possible to do such a check from recipes. The way to check if there is some newer recipe in the server is to use the ``--update`` argument in the command line, which might mean different things depending if you have revisions enabled (recommended, as this will be the standard in Conan 2.0) or not.

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you in a while - if anyone has any other question or request, please feel free to create a new issue, we're always happy to help! :)
