### ISSUE TITLE
[bug] conan profile show/update doesn't work with new experimental [conf] section

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#9079]
`conan profile show profile_containing_conf` => fails
`conan profile update conf.whatever` => fails

**Comment by memsharded** [comment]
Agree the ``show`` must be fixed, it cannot fail. The ``profile update`` I am not so sure about this command in particular and in general commands that do basic text edition of text files (thinking UI/UX Conan 2.0)

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/9114, will be in 1.38
