### ISSUE TITLE
include custom .cmake files when using cmake_find_package generator

### ISSUE THREAD

**Issue by Anokhi1994** [conan-io/conan#9086]
I have a package A and package B. 
package B has a requirement of package A in conanfile.py. 

package A is like this:

- cmake
    - helloWorld.cmake (contains a macro hello_world)
- CMakeLists.txt
- conanfile.py
- src

package B is like this:

-CMakeLists.txt( needs to use hello_world macro from helloWorld.cmake file)
-conanfile.py (requires package A,  has generator "cmake", "cmake_find_package)
-src

When I do conan create . usr/channel in package B repository it complains that hello_world macro is not found. 

This only happens if package B uses "cmake_find_package" generator. 

The error does not occur if "cmake" is used as a generator. 

My understanding:
"cmake_find_package" generates its own Find<PKG>.cmake file. and adjusts the CMAKE_MODULE_PATH. 

However, my question is if it is possible to somehow use the other custom .cmake files from the required package? 

I am a newbie in conan and any help is greatly appreciated.

**Comment by memsharded** [comment]
Hi @Anokhi1994 

Have you tried the new ``set_property()`` from cpp_info: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info? You are interested in the ``cmake_build_modules`` properties to point to your module.

Not sure if ``cmake_find_package`` supports it fully, I'd recommend the new ``CMakeDeps`` generator, is there to become the canonical integration with CMake in Conan 2.0.
