### ISSUE TITLE
VS2017 vcvarsall path

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#909]
https://github.com/conan-io/conan-package-tools/pull/42

It has changed:
 "%vs150comntools%../../VC/vcvarsall.bat"

to:
"%vs15'0comntools%../../VC/Auxiliary/Build/vcvarsall.bat"

It should be fixed by conan.tools too.

**Comment by KindDragon** [comment]
JFYI [Finding the location of a VC++2017 install](https://blogs.msdn.microsoft.com/vcblog/2016/10/07/compiler-tools-layout-in-visual-studio-15/)

**Comment by memsharded** [comment]
Trying to fix this, but having the issue https://github.com/conan-io/conan-package-tools/pull/42#issuecomment-278069926. As for using ``%VCInstallDir%``, that is only defined if you already launch a VS prompt, and I want to be able to load any VCvars from a normal prompt.
