### ISSUE TITLE
[bug] Incorrect "lock bundle" help string for "update"

### ISSUE THREAD

**Issue by aleksa2808** [conan-io/conan#9091]
The description for the `update` sub-command of the `conan lock bundle -h` command is the same as for the `update` sub-command in the help string for the `conan lock -h` command. However, this message does not apply to the bundle update arguments and general command meaning.

This is the relevant part of the output from the `conan lock bundle -h` command:
```
    update              Complete missing information in the first lockfile with information defined in the second lockfile. Both lockfiles must represent the
                        same graph, and have the same topology with the same identifiers, i.e. the second lockfile must be an evolution based on the first one
```

### Environment Details
  * Conan version: latest develop

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/9093 fixed this, will be in 1.38, thanks for reporting!
