### ISSUE TITLE
[question] Does conan telemetry?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9094]
`vcpkg.exe` now has the capability of telemetry, only disabled by settings.
What about conan?

**Comment by memsharded** [comment]
Hi @playgithub 

No, Conan does not have any telemetry at all. The truth it that we have considered it a couple of times, it would be really valuable feedback to know a bit more of Conan usage at very large scale, but it didn't get enough priority so far. If sometime we do it, it will be very visible in the docs and very easy to opt-out in configuration, but it is not planned atm.

Any particular reason you are asking this question?

**Comment by playgithub** [comment]
> Any particular reason you are asking this question?

I'm just afraid of the built-in capability of user data collection.
Though it can be opt-out, there might be a backdoor.
So I prefer softwares without the capability.
