### ISSUE TITLE
[question] `conan install` grammar

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9101]
`conan install zlib/1.2.11@` works
`conan install zlib/1.2.11` failed

In `conanfile.txt`, without `@` it works.
```
[requires]
zlib/1.2.11
```

It seems not consistent, if `@` means remote, why not use it in `conanfile.txt`?

**Comment by memsharded** [comment]
It doesn't mean "remote", the package could be installed in the local cache.

It is just a necessary distinction to differentiate between:

```
conan install path/folder
conan install pkg_name/version@
```

So it is just a CLI parsing thing. Conan 2.0 will remove this need by making the argument explicit.
