### ISSUE TITLE
[question] lockfiles and explicit revisions

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#9104]
Hi,
we have dependency graphs with explicit versions set for the given packages, so no version ranges at all.
However from CI perspective we'd like to use the lockfile "merge" feature (--lockfile=foo-in.lock --lockfile-out=foo-out.lock)
so that to be able to override certain elements in the dependency graphs.
However as we use explicit revisions it doesn't work currently. Is it a design decision?
Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

Quick note: the ``.cmake`` extension doesn't make sense for lockfile, I guess that is a typo.

Regarding your question: A lockfile is a snapshot of a dependency graph. What is stored in the snapshot/lockfile is effectively locked, and cannot be changed. Lockfiles are not a versioning mechanism, it is not possible to change something in the lockfiles to construct a new dependency graph, that didn't exist before.

So when a revision is locked, it is locked forever, there is no such ``merge``, but what is possible is to create a new lockfile, using the previous information from a previous lockfile. It is not a merge, but pure adding information to fill empty gaps in the previous lockfile. That can happen for example with the ``--base`` argument, that doesn't lock the ``package_ids``, then it is possible to create a new lockfile, using that base one, to compute and fill the ``package_ids`` for different configurations, but what was locked in the original ``base`` lockfile cannot be changed.

Please let me know if this clarifies a bit the design. It would also be interesting if you could elaborate a bit further on what you are trying to achieve.

**Comment by harsszegi** [comment]
Hi @memsharded ,

yes of course it was a typo :)

Currently we are using a non-semver compliant versioning scheme, practically capturing the git sha in the version number (apart from other things, like -dirty, etc.). So practically it makes next to impossible to create a "OpenSSLVersion"-alike version wrapper which would make our versioning scheme somewhat semver-compatible, comparable.

We don't really want to achieve much, but:
- capture the exact dependency graph + profiles at the time of building a given dependency chain
- replace arbitrary elements in the graph with other versions of the same package.

This is practically a daily bugfixing workflow. 
- We receive a report from the customer indicating that some component/package behaves badly, let's assume the customer uses pkgA, but pkgA depends on pkgB, and the feature the customer is complaining about is implemented in pkgB
- We figure out the exact version of the component/package the customer is using from pkgB, let's assume pkgB/1.0.0-70d087d-58@user/release, where 70d087d is the git sha of the repo where pkgB lives
- We branch off from 70d087d, creating a feature/bugfix branch, we add some extra printfs, etc. whatever is required to reproduce the issue
- We build a pkgB/1.0.0-deadbeef-1-feature_bugfix@user/testing package
- We wish to rebuild the whole dependency chain replacing "pkgB/1.0.0-70d087d-58@user/release" with "pkgB/1.0.0-deadbeef-1-feature_bugfix@user/testing package"

We thought that if we store lockfiles together with packages (whenever a new package is built) we might be able to handle the situation above, but that means we would have to adjust the stored lockfiles.
So that is the background :)

**Comment by memsharded** [comment]
This is the key thing that violates locking assumptions:

> replace arbitrary elements in the graph with other versions of the same package.

This is not doable from a locking point of view. A new version of an existing package can, and often does:

- Remove existing dependencies
- Add new dependencies. This dependencies might or might not be already locked in a different place of the lockfile and it might have transitive dependencies that could or could not be locked. 
- Upgrade or downgrade dependencies. These changes in the upstream versions might also induce new versions of the transitive dependencies.
- Make conditional existing dependencies to some configuration conditions, like settings or options.
- A new version might not fit in the downstream range or version declaration, lets say that you have app->pkg/0.1->dep/0.1. All versions are fixed. If you replace ``dep/0.1`` by ``dep/0.2`` just in the lockfile, you reach an impossible state, a dependency graph that could have never existed in the first place, so the lockfile is no longer locking an existing state, but instead tried to be used a s a version definition mechanism. A mechanism that basically violates the resolution of versions and semantic versioning.
- Changes in versions often change downstream package_ids, completely violating binary locking, if we have app->pkg/0.1->dep/0.1, the lockfile for the app application will lock the package_id of pkg/0.1, but if dep/0.1 is changed, it will produce a new package_id in pkg/0.1 that will conflict with the locked one.

In summary, changing something in the middle of the graph, completely alters the dependency graph, in topology, and also in many of the values locked there (recipe revisions, options, contexts, package ids, package revisions). These changes might create version or configuration conflicts, that can't be resolved in one direction or the other. Should I used the locked value or the just newly evaluated one? This is mostly an intractable problem in any pragmatic way.

The assumption of "yes, but I won't change my dependencies" will not hold, developers will eventually change them, and then, complicated to debug issues will happen.

So the proposed lockfiles strategy is:
- When something is locked, it is locked forever and always be resolved to that, or error. Locked data is immutable.
- When something changes, a new snapshot has to be captured, doing a fresh evaluation of a new dependency graph.
- A previous partial or base lockfile can be used to compute a dependency graph. What is in the lockfile locked will be respected, and new information not locked, as package_ids, or package revisions can be computed and can become part of the newly computed lockfile.

Does this make sense?

**Comment by memsharded** [comment]
To follow with your case, the flow for something like you explained could be something like:

- conan lock install <yourlockfile>
- conan export|create your fixes
- conan lock create <rootapp>  

this will create a new lockfile, that will include your fix if it didn't bump the version. That lockfile will already compute what is necessary to be rebuild, following ``--build=missing`` policies for example, and will tell the order with ``conan lock build-order``.

This flow can be applied in CI to any change in any package, the system will manage to discard version bumps too, as they will not be included in the downstream rootapps (version bumps often require explicit version upgrades in the downstream, as well as code changes due to API changes), or it will detect that some changes that apparently are not breaking actually break downstream.

**Comment by harsszegi** [comment]
Hi @memsharded ,

might be lost on this, but how can I "conan lock create" after my changes are applied?
How can I create a new dependency graph with minimal changes applied to it?
I thought that if the lockfile is created even if --base, the package revision is locked already (but not the package actual revision), so if the given package is not allowing version ranges there is absolutely no way to apply an "alternative package version" via --lockfile "onto" the lockfile generated with --base.

Are you saying that with the current infrastructure, I could still apply changes to the --base lockfiles even if the given recipe doesn't allow version ranges?
Thanks,

**Comment by memsharded** [comment]
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
