### ISSUE TITLE
Extension point for conan python code

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#911]
Besides generators or reusing python code packaged in conan packages, there could be a need for custom conan extensions:

- If packaged as python/pip packages, they will be versioned and installed in the python path, so easy, nothing to do here. But maybe it is not very convenient to create and publish such packages.
- The other way would be to have to code in a repo that can be cloned, and just a conan configuration variable that add such path to the PYTHONPATH. Maybe just syntax for adding to PYTHONPATH in the conan.conf.

**Comment by lasote** [comment]
Some context: Could be useful for a company/organization that implements their private own classes, for example, for a new build system helper (like CMake or ConfigureEnvironment) or a generator without the need to create a conan package for use the generator. 
Share code with the community is always a good thing but developments for adjusting a private company tools/environment could be useful and share those things with the community would be useless.

**Comment by SSE4** [comment]
I think this one is covered by `python_requires` feature

**Comment by memsharded** [comment]
Yes, this is covered  by python_requires and also will be complemented with conan plugins (plugins to be released in 1.8)
