### ISSUE TITLE
[question] Never use binary packages from a specific remote?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#9113]
The subject says all. I would like to use recipes from a remote repository (say, conancenter) and take binaries only from my own private repo (if they are available there). Of course, package revisions are enabled. Is it possible with not too many efforts?

**Comment by memsharded** [comment]
I think this might be possible in Artifactory:

- Have a virtual repo that aggregates a remote to ConanCenter, and your own local repo
- Exclude from the remote the **/package/** path, that should allow to bring only the recipes.

Not sure about it, but might be worth trying.

**Comment by memsharded** [comment]
In any case, I am not sure about the setup. Are you building the binaries from a clone of ``conan-center-index`` repo? If so, it wouldn't make sense to depend on ConanCenter at all, right?

**Comment by db4** [comment]
> I think this might be possible in Artifactory

I'll try to, thanks for the idea.

> In any case, I am not sure about the setup. Are you building the binaries from a clone of `conan-center-index` repo? If so, it wouldn't make sense to depend on ConanCenter at all, right?

Well, I need recipes from `conan-center-index` and don't want to clone CCI repo, replicating all its building infrastructure (CCI build scripts are closed, so one would need to reimplement them from scratch). But I would like to use only locally-built binary packages from a private Artifactory server for security/reproducibility reasons. I'm thinking of a setting that forces Conan to ignore binaries from a specific remote. How do you think, is it hard to implement?

**Comment by memsharded** [comment]
> Well, I need recipes from conan-center-index and don't want to clone CCI repo, replicating all its building infrastructure (CCI build scripts are closed, so one would need to reimplement them from scratch). But I would like to use only locally-built binary packages from a private Artifactory server for security/reproducibility reasons. I'm thinking of a setting that forces Conan to ignore binaries from a specific remote. How do you think, is it hard to implement?

This is now the recommended way, now even documented in https://docs.conan.io/2/devops/using_conancenter.html.
It happens to be fairly simple, basically a simple script that ``conan export`` a list of packages you want, followed by exactly the same ``conan install ... --build=missing`` + ``conan upload`` that you would normally do.

Furthermore, Conan 2.0 provides new tools, like ``conan graph info`` with a conf to download the source, followed by a ``conan remote disable conan-center`` would also easily do the job. We are also preparing to launch in 2.0 some other new features to help with this flow.

I am closing this as not planned at this moment.
