### ISSUE TITLE
Deprecated platform.linux_distribution()

### ISSUE THREAD

**Issue by tivek** [conan-io/conan#912]
Conan uses platform.linux_distribution() to determine the exact flavor of Linux and the system package manager. However, platform.linux_distribution() is [deprecated in Python 3.5](https://docs.python.org/3/whatsnew/3.5.html#deprecated-python-modules-functions-and-methods) and is going to be removed completely in Python 3.7.

Identifying the Linux distribution seems to be complex enough that Python decided to give up on trying to do it in a built-in library and relegated it to a 3rd party library. [It is suggested](http://bugs.python.org/issue1322) to use the [distro](https://pypi.python.org/pypi/distro) package in the future.

Even though using distro would introduce a new dependency for Conan on all Linux systems, that seems preferable to Conan rolling its own home-made heuristics. As a heads-up, I am working on a PR to see how relying on distro would play out. I plan to try it first on a couple of older distributions and then push it here for discussion.

**Comment by memsharded** [comment]
Hi Tomislav,

Thanks for noticing that deprecation, yeah, better address it before it is late. I think that depending on an external package, as long as it is a PyPI package, it is easy to manage, so is not a big problem to add such a dependency. Go ahead, any help or feedback you need with your PR, please tell, thanks very much!

**Comment by memsharded** [comment]
Was released in 0.19.
