### ISSUE TITLE
[question] conan config install + version of installed git/svn repository

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#9120]
Hi,

as Conan scrubs .git after installing a given config repository it is practically impossible to decide whether a configuration repository needs to be "reinstalled" (newer version exists in the remote repo) or not before any given Conan command is executed.
What is the expected behaviour here? How should this situation be handled?
Thanks,

**Comment by memsharded** [comment]
Sorry @harsszegi this was not responded back then.

the ``conan config install`` expects to always download/clone the sources and re-install the configuration. It is not expected to have any optimization or checking here.

If you are interested in smarter ``config install`` please check https://docs.conan.io/2/reference/commands/config.html#conan-config-install-pkg. It allows to use configuration from Conan packages and it is smart to avoid downloading or re-installing when not necessary, plus other features as lockfile-reproducibility and more.

I am closing this ticket as staled, please create new ones if necessary, thanks!
