### ISSUE TITLE
[feature] Add user_info support to cmake_find_package*

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#9127]
package_info/user_info is not currently supported in cmake_find_package* but there doesn't seem to be a reason why it couldn't be, so it would be nice. Would you accept a PR for this?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Both ``user_info`` and ``cmake_find_package`` removed in 2.0, closing this ticket as outdated
