### ISSUE TITLE
[fix] `CONAN_TOOLCHAIN_ARGS_FILE` is not very practical being a json file

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#9130]
The CONAN_TOOLCHAIN_ARGS_FILE will be frequently used to "store" arguments to pass to the build system in the "generate()" method. These arguments can contain paths and other things quoted. One of the principal use cases for the CONAN_TOOLCHAIN_ARGS_FILE is to be able to "cat" the file and paste the contents to call directly the build system in the command line, emulating exactly what Conan does. But the json format escapes the quotes, and you cannot directly copy the contents without editing it and that is a big pain.

Think about another format... ¿yml? ¿txt?...

**Comment by franramirez688** [comment]
@lasote @tapia 
After trying several things, I think a good option could be to use `ConfigParser` (internally) and save a `*.conf` file. I've made some tests and it supports to save any kind of string keeping the original format, for instance:

```
$ cat example.conf
[autotools]
a = my\super\path
b = command --b "option"
```
Anyway, we can discuss the file name...

**Comment by lasote** [comment]
Yep. I cannot think in a better alternative. WDYT @memsharded ?

**Comment by memsharded** [comment]
yes, sounds good, I have had some bad experience in the past (conan.conf, etc), because ConfigParser kind of always want key=value, and that was not the best fit for some cases, so I ended manually parsing things. But yes, lets give it a try.
