### ISSUE TITLE
[bug] While using cmake_find_package* generators <PKG-NAME>_LIBS and <PKG-NAME>_LIBRARIES differ.

### ISSUE THREAD

**Issue by takacsd** [conan-io/conan#9135]
When I use `cmake_find_package` generator I expect to have the `<PKG-NAME>_LIBS` and `<PKG-NAME>_LIBRARIES` variables set to the same value after `find_package(<PKG-NAME>)`. This is also written in the [documentation](https://docs.conan.io/en/latest/reference/generators/cmake_find_package.html#variables-in-find-pkg-name-cmake)

But it doesn't have the same value, because in the generated `Find<PKG-NAME>.cmake` the contents of the `<PKG-NAME>_LIBRARIES` gets copied to `<PKG-NAME>_LIBS` here:
https://github.com/conan-io/conan/blob/80f344c101f892a18104fa12fedc2feeb993fdd1/conans/client/generators/cmake_find_package_common.py#L57

but then it gets altered later here:
https://github.com/conan-io/conan/blob/80f344c101f892a18104fa12fedc2feeb993fdd1/conans/client/generators/cmake_find_package_common.py#L59-L71

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 21.04
  * Compiler+version: gcc 10.3
  * Conan version: 1.37.2
  * Python version: 3.9

Or did I miss something?

**Comment by memsharded** [comment]
Sorry this was not responded back then. These generators have been removed in Conan 2, closing as outdated.
Please create new tickets for any further question, thanks for the feedback.
