### ISSUE TITLE
[bug] Bazel issue when using string value for defines

### ISSUE THREAD

**Issue by fanStefan** [conan-io/conan#9138]
If define is a string value, there is problem in generated build file.
String in string is generated and Bazel can't resolve this.
Here is example from generated boost BUILD file:
`"BOOST_STACKTRACE_ADDR2LINE_LOCATION="/usr/bin/addr2line""`

### Environment Details
  * Operating System+version: Fedora 34
  * Compiler+version: gcc 11.1.1
  * Conan version: 1.37.2
  * Python version: 3.9.5
  * Bazel version: 1.2.1

### Steps to reproduce
Can be reproduces using example [project](https://github.com/conan-io/conan/files/6697662/bazel-string-define-issue.zip) and running:
```
conan install . --build=missing
bazel build //:hello-world 
```

**Comment by natheihei** [comment]
@fanStefan @tapia sorry I'm very new to conan and thus new to conan + bazel.

Supposedly this issue has been fixed by 1.39.0, which I have confirmed by running
```
$ conan --version
Conan version 1.39.0
```

I downloaded the "project" link in the above comment https://github.com/conan-io/conan/issues/9138#issue-927672935, and run

```
$ conan install . --build=missing
bazel-string-define-issue$ conan install . --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (bazel-example/None): Installing package
Requirements
Packages
Build requirements
    boost/1.76.0 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conancenter' - Cache
    libbacktrace/cci.20210118 from 'conancenter' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
Build requirements packages
    boost/1.76.0:adf48b8e4446dcb68f440fe42ff08878d5c7feed - Cache
    bzip2/1.0.8:da606cf731e334010b0bf6e85a2a6f891b9f36b0 - Cache
    libbacktrace/cci.20210118:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache
    zlib/1.2.11:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
bzip2/1.0.8: Appending PATH environment variable: /.../.conan/data/bzip2/1.0.8/_/_/package/da606cf731e334010b0bf6e85a2a6f891b9f36b0/bin
libbacktrace/cci.20210118: Already installed!
zlib/1.2.11: Already installed!
boost/1.76.0: Already installed!
conanfile.py (bazel-example/None): Applying build-requirement: boost/1.76.0
conanfile.py (bazel-example/None): Applying build-requirement: zlib/1.2.11
conanfile.py (bazel-example/None): Applying build-requirement: bzip2/1.0.8
conanfile.py (bazel-example/None): Applying build-requirement: libbacktrace/cci.20210118
conanfile.py (bazel-example/None): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py (bazel-example/None): Generator 'BazelDeps' calling 'generate()'
conanfile.py (bazel-example/None): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py (bazel-example/None): Generator 'BazelToolchain' calling 'generate()'
conanfile.py (bazel-example/None): Generator txt created conanbuildinfo.txt
conanfile.py (bazel-example/None): Aggregating env generators
conanfile.py (bazel-example/None): Generated conaninfo.txt
conanfile.py (bazel-example/None): Generated graphinfo
```

I do see that files including `conandeps/BUILD` and `conandeps/dependencies.bzl` is generated, but the BUILD file is empty, and dependencies.bzl has an `def load_conan_dependencies(): pass`.

Then if I do bazel build, it failed to find the `boost` dep.
```
bazel-string-define-issue$ bazel build //:hello-world
ERROR: /tmp/bazel-string-define-issue/BUILD:3:10: no such package '@boost//': The repository '@boost' could not be resolved and referenced by '//:hello-world'
ERROR: Analysis of target '//:hello-world' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.088s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 4 targets configured)
    Fetching @local_config_cc; fetching
```
 
I feel I must have missed some obvious step, but I can figure it out. Can you please kindly provide some pointers on where I should look at to get conan+bazel to work?

Thanks!

**Comment by ysyyork** [comment]
> @fanStefan @tapia sorry I'm very new to conan and thus new to conan + bazel.
> 
> Supposedly this issue has been fixed by 1.39.0, which I have confirmed by running
> 
> ```
> $ conan --version
> Conan version 1.39.0
> ```
> 
> I downloaded the "project" link in the above comment [#9138 (comment)](https://github.com/conan-io/conan/issues/9138#issue-927672935), and run
> 
> ```
> $ conan install . --build=missing
> bazel-string-define-issue$ conan install . --build=missing
> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Release
> compiler=gcc
> compiler.libcxx=libstdc++
> compiler.version=9
> os=Linux
> os_build=Linux
> [options]
> [build_requires]
> [env]
> 
> conanfile.py (bazel-example/None): Installing package
> Requirements
> Packages
> Build requirements
>     boost/1.76.0 from 'conancenter' - Cache
>     bzip2/1.0.8 from 'conancenter' - Cache
>     libbacktrace/cci.20210118 from 'conancenter' - Cache
>     zlib/1.2.11 from 'conancenter' - Cache
> Build requirements packages
>     boost/1.76.0:adf48b8e4446dcb68f440fe42ff08878d5c7feed - Cache
>     bzip2/1.0.8:da606cf731e334010b0bf6e85a2a6f891b9f36b0 - Cache
>     libbacktrace/cci.20210118:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache
>     zlib/1.2.11:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache
> 
> Installing (downloading, building) binaries...
> bzip2/1.0.8: Already installed!
> bzip2/1.0.8: Appending PATH environment variable: /.../.conan/data/bzip2/1.0.8/_/_/package/da606cf731e334010b0bf6e85a2a6f891b9f36b0/bin
> libbacktrace/cci.20210118: Already installed!
> zlib/1.2.11: Already installed!
> boost/1.76.0: Already installed!
> conanfile.py (bazel-example/None): Applying build-requirement: boost/1.76.0
> conanfile.py (bazel-example/None): Applying build-requirement: zlib/1.2.11
> conanfile.py (bazel-example/None): Applying build-requirement: bzip2/1.0.8
> conanfile.py (bazel-example/None): Applying build-requirement: libbacktrace/cci.20210118
> conanfile.py (bazel-example/None): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
> conanfile.py (bazel-example/None): Generator 'BazelDeps' calling 'generate()'
> conanfile.py (bazel-example/None): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
> conanfile.py (bazel-example/None): Generator 'BazelToolchain' calling 'generate()'
> conanfile.py (bazel-example/None): Generator txt created conanbuildinfo.txt
> conanfile.py (bazel-example/None): Aggregating env generators
> conanfile.py (bazel-example/None): Generated conaninfo.txt
> conanfile.py (bazel-example/None): Generated graphinfo
> ```
> 
> I do see that files including `conandeps/BUILD` and `conandeps/dependencies.bzl` is generated, but the BUILD file is empty, and dependencies.bzl has an `def load_conan_dependencies(): pass`.
> 
> Then if I do bazel build, it failed to find the `boost` dep.
> 
> ```
> bazel-string-define-issue$ bazel build //:hello-world
> ERROR: /tmp/bazel-string-define-issue/BUILD:3:10: no such package '@boost//': The repository '@boost' could not be resolved and referenced by '//:hello-world'
> ERROR: Analysis of target '//:hello-world' failed; build aborted: Analysis failed
> INFO: Elapsed time: 0.088s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (3 packages loaded, 4 targets configured)
>     Fetching @local_config_cc; fetching
> ```
> 
> I feel I must have missed some obvious step, but I can figure it out. Can you please kindly provide some pointers on where I should look at to get conan+bazel to work?
> 
> Thanks!

same issue here

**Comment by fanStefan** [comment]
@blackhogz @ysyyork can you try 1.38.0?

**Comment by memsharded** [comment]
Hi, I have created a new issue in #9354, if you want to report there (as this is closed, we could re-open but it is more convenient to open a new ticket)

**Comment by natheihei** [comment]
Thanks @memsharded , let's move the discussion to #9354.
