### ISSUE TITLE
libstdc++11 ignored in conan.conf

### ISSUE THREAD

**Issue by bschindler** [conan-io/conan#914]
Hi 

I just got started with conan. So may be I'm really doing something wrong. 
In conan.conf, I changed libstdc++ (which was default) to libstdc++11 and reran conan install for my program. Yet, conan insisted on installing libstdc++ version instead of libstdc++11. Only with specifying the compiler by hand (conan install -s .. -s ...) I was able to pull the c++11 version. 
So my question is, why is the setting in conan.conf being ignored? 

@edit: This is latest conan, just installed it today: deb package 0.18.1, kubuntu 16.04 lts

**Comment by memsharded** [comment]
Hi @bschindler ,

Just a minor comment: conan does not install libstdc++ or libstdc++, they come with your compiler. The setting is for helping to define which one to use, not to install it

The settings are cached in conaninfo.txt after the first install. So if you did the first install and it used the "libstdc++" settings, changing it in the conan.conf file might not have effect, but command line has priority over the cached settings. Please try removing the ``conaninfo.txt`` file, and install again without command line arguments.

**Comment by bschindler** [comment]
Hi @memsharded 

Thank you for the very quick response. My question was indeed misleading w.r.t. to installing libstdc++ sorry. Yes, I know that the distro owns libstdc++. 

And yes, conaninfo.txt was indeed the culprit.

**Comment by memsharded** [comment]
Yeah, the caching of options was implemented because it was a bit annoying to type everything again and again, but yes, "there are two difficult problems in SW engineering: naming things and cache invalidation". Here, modifying conan.conf is not able to invalidate the caches of every conan install'ed project 

Good, glad that it worked  :), thanks for telling.
