### ISSUE TITLE
[bug] `ConfigParser: Unrecognized field 'settings'` error on valid(?) conanfile.txt

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#9140]
### Environment Details (include every applicable attribute)
  * Operating System+version: archlinux(kernel 5.12.8)
  * Compiler+version: gcc: 11.1.0
  * Conan version: 1.37.2
  * Python version: 3.9.5

### Steps to reproduce (Include if Applicable)
conanfile.txt
```
[settings]
    build_type=Debug

[generators]
    cmake/3.16.0

[requires]
    qt/6.1.1
```
running the command `conan install .` (in the directory with the conanfile)
### Logs (Executed commands with output) (Include/Attach if Applicable)
`conan install .` output
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: /home/pixtum/Code/amalgam:
ConfigParser: Unrecognized field 'settings'
```

**Comment by wbehrens-on-gh** [comment]
Just thought that I'd mention that I get the same issue even if I use a flag other then `build_type`

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

this is not a bug, it seems you are confusing the conanfile.txt with the profile. The conanfile does not contain a ``[settings]`` definition section, thus Conan is correctly failing and telling that ``settings`` field is not recognized (maybe the error message could be improved, but the behavior of failing is correct).

You need to define the ``[settings]`` in a profile file, then pass it with ``conan install ... -pr=myprofile``

**Comment by wbehrens-on-gh** [comment]
Then how do I changing settings for `conan build`?

**Comment by memsharded** [comment]
> Then how do I changing settings for conan build?

You do:
1. ``conan install . -s os=Windows ... `` or ``conan install . -pr=myprofile``
Then
2. ``conan build .``

In Conan 1.X ``conan build`` does not define configuration, it uses the configuration of the previous ``install`` command, stored in the ``conaninfo.txt`` and ``conanbuildinfo.txt`` that ``conan install`` generates. (Conan 2.0 will change this).
