### ISSUE TITLE
[question] Why does the `hello` sample produce `greet.lib`?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9142]
As the sample at https://github.com/conan-io/docs/blob/master/developing_packages/package_dev_flow.rst,

`greet.exe` and `hello.lib` is expected, but why is there `greet.lib`? `greet.lib` is not expeted, is it ?

**Comment by memsharded** [comment]
``greet.lib`` is not a Conan thing, it is an artifact automatically created by the build system for building greet.exe in Windows.

It happens to be packaged, because the ``package()`` method is packaging "greet", so it matches the pattern, but could be omitted with more detailed and explicit copying patterns.

**Comment by playgithub** [comment]
> `greet.lib` is not a Conan thing, it is an artifact automatically created by the build system for building greet.exe in Windows.
> 
> It happens to be packaged, because the `package()` method is packaging "greet", so it matches the pattern, but could be omitted with more detailed and explicit copying patterns.

But as the cmake file of sample `hello` shows, it should produce `greet.lib`, right?
```cmake
PROJECT(MyHello)
cmake_minimum_required(VERSION 2.8)

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/bin)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_CURRENT_SOURCE_DIR}/bin)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_CURRENT_SOURCE_DIR}/bin)

SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib)
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
    
ADD_LIBRARY(hello hello.cpp)
ADD_EXECUTABLE(greet main.cpp)
TARGET_LINK_LIBRARIES(greet hello)
```

**Comment by memsharded** [comment]
There is no ``ADD_LIBRARY(greet ...)`` in that CMakeLists.txt, so the ``greet.lib`` is some automatic thing of the build system, not a user defined library.

**Comment by playgithub** [comment]
> There is no `ADD_LIBRARY(greet ...)` in that CMakeLists.txt, so the `greet.lib` is some automatic thing of the build system, not a user defined library.

Confirmed by a native VS2019 solution include "greet" as an application and "hello" as a static lib, it also generates `greet.lib`, ok to let it be.

Thanks
