### ISSUE TITLE
[question] Is there a way to limit the maximum cache size?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#9146]
Hi,
because of a dumb Conan recipe (which we don't have control over), our Conan cache grew above 130Gb, which was a problem as our build agent didn't have much more free space. 
Is there a way to limit the maximum amount of cache Conan can consume ? Or purge multiple entries from the cache ?
Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

No, there is no way, this should be something at the OS permissions or configuration level.

To "purge" things from the cache, you can use the ``conan remove`` command, that has some arguments like:
- ``--build`` will remove all the build folders
- ``--packages`` will remove the binary package, but leave recipes
- ``pattern --force`` will remove all packages matching the pattern, without asking for confirmation

**Comment by harsszegi** [comment]
Awesome, thanks a lot @memsharded
