### ISSUE TITLE
[question] How to use a pre-built lib package in conan cache?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9153]
**conanfile.py**
```
from conans import ConanFile, tools


class PreBuiltLibConan(ConanFile):
    name = "pre-built-lib"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    description = "test pre-built-lib"
    url = "test-url"
    license = "MIT"
    author = "abc"
    topics = ("topic-a", "topic-b", "topic-c")
    generators = "cmake"

    def package(self):
        self.copy("*")

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

With `generators` in **conanfile.py**, there is no `conanbuildinfo.cmake` in cache.
So for Visual Studio.
So for downloaded pre-built libs from conon-center, e.g. `poco`.
How can the libs be used by an application.

**Comment by memsharded** [comment]
conanbuildinfo.cmake is not in the cache, it will be part of the consumer of the library. The ``generator`` should be in the ``conanfile`` you are using to install your library, not in the library itself.

The getting started tutorial: https://docs.conan.io/en/latest/getting_started.html shows how to consume a library for an existing package, and build an application using that library. 

Then, I suggest starting with the "creating package" tutorial: https://docs.conan.io/en/latest/creating_packages/getting_started.html#creating-the-package-recipe, and create a package from the predefined template. Then try to add your "hello" package to your consumer application you built in the previous step. Then, only then, start to adapt the package recipe to your own code and libraries.

**Comment by playgithub** [comment]
> conanbuildinfo.cmake is not in the cache, it will be part of the consumer of the library. The `generator` should be in the `conanfile` you are using to install your library, not in the library itself.

Alright

> The getting started tutorial: https://docs.conan.io/en/latest/getting_started.html shows how to consume a library for an existing package, and build an application using that library.
> 
> Then, I suggest starting with the "creating package" tutorial: https://docs.conan.io/en/latest/creating_packages/getting_started.html#creating-the-package-recipe, and create a package from the predefined template. Then try to add your "hello" package to your consumer application you built in the previous step. Then, only then, start to adapt the package recipe to your own code and libraries.

Thanks for you detailed answer, I've read the docs, but forget something, now I understand `conan` better.
