### ISSUE TITLE
Xcode generator puts full hard coded path into xconfig files

### ISSUE THREAD

**Issue by sjames1958gm** [conan-io/conan#9154]
I am wanting to incorporate conan into our Xcode builds. When I use the xcode generator it puts the entire path (including the home folder) into the .xconfig file.

For example:

`HEADER_SEARCH_PATHS = $(inherited) "/Users/sjames/.conan/data/cppunit/1.15.1/_/_/package/6a83d7f783e7ee89a83cf2fe72b5f5f67538e2a6/include"`

This makes it difficult to include this file into our repository. On windows when using visual studio and it puts $(USERPROFILE) in the path making the file more portable.

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @sjames1958gm 

That is true. Many, if not all Conan generators put absolute paths in the generated files. Generated files are not intended to be committed to source control, but to be generated in the computer. The Visual Studio one (I think it was ``visual_studio`` one, actually the newer, recommeded ``MSBuildDeps`` do not implement this) that provides the USERPROFILE is the exception, and as commented, it might be dropped in the future integrations.

The thing is that having those files in the repository, makes it quite confusing in several situations:

- If the packages are not installed in the machine, but the generated files are in the repo, it will be pointing to a non existing location, and giving non evident error messages
- Even if the user home is parameterized, it is possible to configure where the location of the packages are. For example, some developers might want to put it in a faster drive.
- Locations will change for different variants. If you only support one generator always in the same platform, maybe not a big issue, but the general behavior is that files will be generated in multiple platforms, for example, for ``CMakeDeps`` you will get a different ``dep-config.cmake`` file generated, different in Windows, Linux, Mac, etc., so it becomes physically impossible to keep that file in the repo, and it has to be generated at each platform.


If you really want to change the default behavior, it is becoming easier and easier to customize what the generators do, with the ``generate()`` method you might easily run a "search and replace" on the xcode generated files. The XCode generator is still to be modernized into the new ``conan.tools`` namespace, when it is, it will also be easier to do this kind of customizations.

**Comment by sjames1958gm** [comment]
Interesting. Thanks for your quick response and describing the philosophy behind the implementation.
If all of the libraries are already installed on the machine the conan install process is relatively quick. Our concern was running the conan install process on every build adding to the build times.

**Comment by memsharded** [comment]
> If all of the libraries are already installed on the machine the conan install process is relatively quick. 

Yes, that is the intention, if the packages are already in the machine cache, installing even a large graph should only take a very few seconds, so nothing really important, the file generation is very fast.

Take into account for CI that the cache is not intended to be used concurrently, so it is typical that CI define a blank cache for every job. There are mechanisms like the download cache, parallelism, and of course putting the Artifactory server close to the CI agents to help with the times, and we keep working to improve over this, and also making the cache more concurrent. But also for the CI case it might be worth to trade some time for better correctness and ensuring everything is reproducible.
