### ISSUE TITLE
[question] How to install a lib with a remote recipe

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9159]
e.g. to install boost using a remote recipe, the command below doesn't work 
```
conan install boost/1.76.0 -r conan-center
```

**Comment by memsharded** [comment]
Hi @playgithub 

When you report an issue you need to specify:

- The OS you are running, the Conan version, your Python version etc.
- The expected outcome or behavior
- Copy and paste the errors, the output, the logs. It is impossible to know what could be failing if you don't provide this info.

It seems that you might be missing the @ ``conan install boost/1.76.0@``


In any case, this is NOT the recommended flow to install things, but to write a ``conanfile.txt`` or ``conanfile.py`` with your requires, your generators, etc.

**Comment by playgithub** [comment]
Thanks
