### ISSUE TITLE
Private dependencies included in CONAN_LIBS

### ISSUE THREAD

**Issue by mropert** [conan-io/conan#916]
I'm trying to use a private dependencies to require GTest (which is only used to run unit tests during build).
Unfortunately, private deps are still added in the ${CONAN_LIBS} (and other) variables defined by the CMake generator.

Is there a way to require something at build time but not add it to the CONAN_* macros generated by CMake?

**Comment by lasote** [comment]
It will be included in the CONAN_LIBS only in the recipe that requires the Gtest recipe directly.
If any other recipe requires your recipe this require shouldnt be propagated. 

If you only want to include Gtest during the package creation maybe scopes feature is useful for you:
http://conanio.readthedocs.io/en/latest/conanfile_py.html?highlight=scope#dev-scope

I would need to understand better the problem, maybe there are other features or approaches that could help you.

**Comment by mropert** [comment]
Here's a more detailed case:
I want to optionally build/run gtests with my package, so I had a scope "run_tests" like you suggested in the docs.
In the ```requirements()``` method of my package I add gtest as a private requirement if "run_tests" in ```True``` in scopes.
In the ```build()``` method I run a ```make test``` (or call ctest) after the cmake build.
In my CMakeLists.txt, I try to find GTest and if found I build the tests.

All this works but there's a little problem: I use ```${CONAN_LIBS}``` to specify my library LINK_LIBRARIES in CMake, which makes my library link with gtest (since ```$CONAN_LIBS``` contains all the required libraries, even the private ones).
But I don't want my library linked with gtest, I only want gtest to be used for the unit tests.

**Comment by lasote** [comment]
Ok, now I got it, Conan declares a variable for each require with the libraries to link with.
So the variable CONAN_LIBS_GTEST should contain the GTest variables you want to avoid.
I'm not a CMake expert but maybe something like that could work:

```list(REMOVE_ITEM CONAN_LIBS ${CONAN_LIBS_GTEST})```

**Comment by mropert** [comment]
Indeed this works, but I can't help but feel that this is kind of a hack.
One better way to solve this could to have a conan generate a few more variables that correspond to specific categories: ```CONAN_PUBLIC_LIBS``` and ```CONAN_PRIVATE_LIBS``` for example.

**Comment by lasote** [comment]
But you could need to link with `CONAN_PRIVATE_LIBS` in some cases, so it will feel kind of hack too for me.

**Comment by mropert** [comment]
I think in most case you won't, because it would introduce runtime dependencies that will not be installed by clients.
Then again, maybe private deps is not the way to go.
Perhaps we could introduce a new category, like "build" dependencies?

**Comment by lasote** [comment]
To be honest it's not the first time we think about the "build" dependencies but in my opinion, there are not reasons enough to increase the conan complexity with a new dependency type.

**Comment by mropert** [comment]
I understand the concern but as it stands it means there's no clean solution to run tests during a build if they require a private dep (such as GTest).
The only alternative I see would be to stop using ```${CONAN_LIBS}``` altogether and use explicit references to which lib to link.
Maybe that's the way to go, I don't know...

**Comment by memsharded** [comment]
Maybe using the modern cmake with targets, you don't need to use CONAN_LIBS any more, but directly link with the targets?

**Comment by mropert** [comment]
I guess that would indeed be the way to go.
In a more general sense, will that be the way Conan will target in the future? I don't see that method mentioned a lot in the docs, which focus mainly on ```${CONAN_LIBS}```

Oh and by the way I see that we can now require packages with the ```dev``` attribute, how does that compare to the ```private```attribute?

**Comment by memsharded** [comment]
You might check in the last section of: http://docs.conan.io/en/latest/integrations/cmake.html

There is a new helper ``conan_target_link_libraries(say_hello)`` that internally calls either the 
```cmake
foreach(_LIB ${CONAN_LIBS_RELEASE})
    target_link_libraries(say_hello optimized ${_LIB})
endforeach()
```
or the 
```cmake
target_link_libraries(say_hello CONAN_PKG::Hello1)
```
depending on the method used.

``dev`` attribute only activate and use those requirements if the ``dev`` scope is active. They are removed by default from the ``package_id``, those requirements shouldn't affect the resulting package. They are intended for dev tools, like testing libraries, that you don't want to depend when using the package, but you want them if the ``dev`` scope of the package is active and want to do unit testing.

``private`` requirements are different, they are intended for isolating and embedding, and to allow, in certain extreme cases to use different versions of the same library. E.g.: a shared library that is embedding in the internal implementation details, and not exposed in the API, another library (header or static), could declare such dependency private. The dependency will not be retrieved if the binary is available, as being private, it is not required to know about it if the binary is already there.

**Comment by mropert** [comment]
Interesting.
And is there a way with the CMake integration to list only the dev requirements? Like a ```${CONAN_DEV_LIBS}```?

**Comment by memsharded** [comment]
A lot has changed since this issue. Now there are ``build_requires`` specifically intended for this purpose.
There are also modern CMake targets genereated in conanbuildinfo.cmake, so consumers can decide which things they are linking in each target, not requiring to use CONAN_LIBS at all.

So I think this can be closed, if there is something left to discuss, please open a new, specific issue for it, thanks.

**Comment by blackencino** [comment]
Hi - especially @memsharded , I'm running into the Boost/Gtest collision problem mentioned in other issue reports, in which depending on Boost and GTest causes a linker error complaining about missing symbols from boost unit test. Here's an output: 

```
Undefined symbols for architecture x86_64:
  "init_unit_test_suite(int, char**)", referenced from:
      _main in libboost_unit_test_framework.a(unit_test_main.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

I've been trying to figure out, from the comments above in this thread, what the 'build_requires' solution is to this problem. Our conanfile.py looks like this: 

```
from conans import ConanFile, CMake

class DepotConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"

    # options
    options = {"enable_guis": [True, False]}
    default_options = {
        "enable_guis": False,
        "*:fPIC": True,
        "*:fpic": True,
        "fftw:threads": True,
        "fftw:precision": "single",
    }

    # comma-separated list of requirements
    requires = (
        "abseil/20200225.2",
        "benchmark/1.5.0",
        "boost/1.73.0",
        "c-ares/1.15.0",
        "c-blosc/1.18.1",
        "crossguid/06-03-19@inexorgame/testing",
        "date/2.4.1",
        "fftw/3.3.8",
        "fmt/6.1.1",
        "gflags/2.2.2",
        "glm/0.9.9.6",
        "gsl-lite/0.34.0",
        "gtest/1.10.0",
        "hdf5/1.10.6",
        "libuv/1.38.0",
        "nlohmann_json/3.9.0",
        "openexr/2.3.0",
        "openssl/1.1.1g",
        "tbb/2020.0",
        "zstd/1.4.5",
    )

    generators = "cmake_paths", "cmake_find_package"

    def requirements(self):
        if self.options.enable_guis:
            self.requires.add("glfw/3.3.2@bincrafters/stable")
            self.requires.add("imgui/1.76")
            self.requires.add("glad/0.1.33")

            # Glad options
            self.options["glad"].shared = False
            self.options["glad"].fPIC = True
            self.options["glad"].spec = "gl"
            self.options["glad"].no_loader = False
            self.options["glad"].gl_profile = "core"
            self.options["glad"].gl_version = "4.1"
```

The other thread mentioning this problem is here: https://github.com/conan-io/conan-center-index/issues/1245
