### ISSUE TITLE
[question] Accessing installed package and enviourment variables outside of conan

### ISSUE THREAD

**Issue by sduraisamy** [conan-io/conan#9160]
We want to access the environment variables exported to consumer in conan and installed path outside of conan in some scripts.
Is there any way we can access the conan exported variables outside of conan?

**Comment by memsharded** [comment]
Hi @sduraisamy 

Have you tried the ``virtualenv`` generators? Those generate files with information about the env-vars defined by packages. We are also modernizing it with a new ``VirtualEnv`` generator (note the casing), still experimental, but will be the future in 2.0.

**Comment by sduraisamy** [comment]
@memsharded I get it from virtualenv generator. Thanks for the information.
