### ISSUE TITLE
[question] conan package library is hardcoded found

### ISSUE THREAD

**Issue by hbwang15** [conan-io/conan#9163]
hello, guys, i encounter an problem with conan， I create an conan package with an exist shared library in it. and then make another shared library which is link against conan package. but the shared library i created link to conan package with an absoulte path, how can i solve this problem?
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

![eacc411190fdf0cf23f7d9f57b71af2](https://user-images.githubusercontent.com/65098776/123407141-33983080-d5de-11eb-9466-fd0a681fa6b0.png)

**Comment by hbwang15** [comment]
The rpath of this library is remove when run make install .which it is reasonable, but the part in red rectangle is wierd.

**Comment by memsharded** [comment]
Sorry this was not responded back then.

This is probably no longer an issue, specially with the new tools and Conan 2.0, so I am closing this as outdated.

If you still have some questions, please create new ticket providing details to reproduce, like the recipes (``conan new`` command can help to easily create recipes and packages). Thanks!
