### ISSUE TITLE
[bug]  NotSpecified: (installing conan release packages:String) []

### ISSUE THREAD

**Issue by MelisWillem** [conan-io/conan#9169]
Since I updated conan to the most recent version, I get a weird error in my build:

CategoryInfo             : NotSpecified: (installing conan release packages:String) [], RemoteException 
FullyQualifiedErrorId : NativeCommandError

I do not get this error when I do not use jenkins, this looks a lot like these two past bug:
#534 
#583

So I am not sure if this might be Conan, or Jenkins.

I tigger conan from CMake using https://github.com/conan-io/cmake-conan, the cmake build is triggered like this:

cmake .. -G  "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release

### Environment Details (include every applicable attribute)
  * Windows server 2019 (19.0.17763 build 17763)
  * MSVC 19.28.29910
  * Conan version: 1.37.2 binary installer
  * Python version: 

### Steps to reproduce (Include if Applicable)
I can't seem to reproduce it outside of the jenkins build. If I execute the build manually on the server it works. 

### Logs (Executed commands with output) (Include/Attach if Applicable)

branches\master\workspace@tmp\durable-311e9cc5\powershellWrapper.ps1:3 char:1
+ & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (installing conan release packages:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by memsharded** [comment]
Hi @Zilleplus 

Those past bugs are really old bugs, like 5 years old, even before Conan 1.0, I'd say it is unlikely that they are the reason.
Without having any further logs or something, it is really difficult to know what could happen. I would suggest:

- Logging into the CI server, and run there (without CI), just to know if there is some environment different
- Make sure to enable all logs in the CI server, capture them and share them here. Hopefully they have some hint about what is happening.

**Comment by memsharded** [comment]
Closing as inactive.
