### ISSUE TITLE
conflicts of shared and static for the same lib

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9172]
conflicts of shared and static for the same lib

If the project depends on wxwidgets(shared) and zlib(shared), while wxwidgets(shared) depends on zlib(static),
how to write `conanfile.txt` for zlib?

```
...
[options]
wxwidgets:shared=true
zlib:shared=?
...
```

**Comment by memsharded** [comment]
You define the option you want to use if it is shared=True, write ``zlib:shared=True`` have you tried that?

**Comment by playgithub** [comment]
> You define the option you want to use if it is shared=True, write `zlib:shared=True` have you tried that?

The option `shared` is for the lib that is being built.
For example, to control wheather `wxwdigets` should be shared or static, but how to control the libs `wxwdigets` link to?
In `conanfile.py`, the requirements have no info about to link to static or shared libs
```
...
def requirements(self):
        if self.settings.os == 'Linux':
            self.requires('xorg/system')
            self.requires('gtk/system')
            if self.options.opengl:
                self.requires('opengl/system')
        if self.options.png == 'libpng':
            self.requires('libpng/1.6.37')
        if self.options.jpeg == 'libjpeg':
            self.requires('libjpeg/9d')
        elif self.options.jpeg == 'libjpeg-turbo':
            self.requires('libjpeg-turbo/2.0.6')
        elif self.options.jpeg == 'mozjpeg':
            self.requires('mozjpeg/3.3.1')
        if self.options.tiff == 'libtiff':
            self.requires('libtiff/4.0.9')
        if self.options.zlib == 'zlib':
            self.requires('zlib/1.2.11')
        if self.options.expat == 'expat':
            self.requires('expat/2.2.7')
...
```

**Comment by memsharded** [comment]
I don't understand what you mean. As long as you put ``zlib:shared=True`` in your conanfile.txt, it will get that value, no need to put it also in the other ``conanfile.py``. If you want, you can change ``conanfile.py`` to change the default, something like ``default_options = {"zlib:shared": True}``, but this is not necessary, as long as you put it in the ``conanfile.txt``.

**Comment by playgithub** [comment]
Thanks
