### ISSUE TITLE
[bug] compiler = 'msvc' does not work with Ninja generator

### ISSUE THREAD

**Issue by slietzau** [conan-io/conan#9178]
It is currently not use Ninja as generator in combination with the new `msvc` compiler. This combination causes CMake to abort with an error (see below).

The error appears because the generated toolchain file sets `CMAKE_GENERATOR_TOOLSET` (see [cmake docs](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html) which is only supported for `Visual Studio *` generators. Extending this block to set `toolset=None` the CMake stops complaining:
https://github.com/conan-io/conan/blob/9ebc2e4282a35e4d29a7b697d71b85db45c31836/conan/tools/cmake/toolchain.py#L579

However, simply removing the block in the toolchain file does not solve the problem entirely because the generated `conanvcvars.bat` does not configure a specific version of the compiler (as indicated by configuring Visual Studio 16.0 without specifying the v141 toolset).

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 20H2
  * Compiler+version: msvc 19.2
  * Conan version: 1.37.2
  * Python version: Bundled with Conan (I'm using the chocolatey package)

### Steps to reproduce (Include if Applicable)
Here are three files to reproduce this locally:

**conanfile.py**
```python
from conans import ConanFile, tools
from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps


class MWEParser(ConanFile):
    name = "MWE"
    version = "0.0.1"
    settings = "os", "build_type", "compiler", "arch"
    exports_sources = "CMakeLists.txt"

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
        deps = CMakeDeps(self)
        deps.generate()

    def configure_cmake(self):
        cmake = CMake(self)
        cmake.configure()
        return cmake

    def build(self):
        cmake = self.configure_cmake()
        cmake.build()

    def package(self):
        cmake = self.configure_cmake()
        cmake.install()
```

**profile**
```ini
[settings]
os=Windows
arch=x86_64
compiler=msvc
compiler.version=19.1
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.cppstd=17
build_type=Release
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.microsoft.msbuild:vs_version = 16
```

**CMakeLists.txt**
```cmake
project(MWE)
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

`conan create . -pr .\profile`
```log
Installing (downloading, building) binaries...
MWE/0.0.1: Configuring sources in D:\dev\.conan\data\MWE\0.0.1\_\_\source
MWE/0.0.1: Copying sources to build folder
MWE/0.0.1: Building your package in D:\dev\.conan\data\MWE\0.0.1\_\_\build\b7ed69139ab470a06c78efe6528bfbaa5ca4c3bb
MWE/0.0.1: Generator txt created conanbuildinfo.txt
MWE/0.0.1: Calling generate()
MWE/0.0.1: Calling build()
MWE/0.0.1: CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="D:/dev/.conan/data/MWE/0.0.1/_/_/build/b7ed69139ab470a06c78efe6528bfbaa5ca4c3bb/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="D:/dev/.conan/data/MWE/0.0.1/_/_/package/b7ed69139ab470a06c78efe6528bfbaa5ca4c3bb" "D:\dev\.conan\data\MWE\0.0.1\_\_\build\b7ed69139ab470a06c78efe6528bfbaa5ca4c3bb"
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.6.4
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Using Conan toolchain through D:/dev/.conan/data/MWE/0.0.1/_/_/build/b7ed69139ab470a06c78efe6528bfbaa5ca4c3bb/conan_toolchain.cmake.
-- Conan C++ Standard 17 with extensions OFF}
  Generator

    Ninja

  does not support toolset specification, but toolset

    v142

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

Generated `conanvcvars.bat`:
```bat
@echo off
set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio 16.0\VC/Auxiliary/Build/vcvarsall.bat"  amd64
```

**Comment by memsharded** [comment]
Hi @slietzau 

I am having a look at this, it is true, CMAKE_GENERATOR_TOOLSET shouldn't be generated. I am doing a PR to remove it for Ninja.

However this leaves some concerns: who would be defining the toolset to use in this case? If not specified in the toolchain, who is the responsible? You might specifying some toolset on settings, like ``compiler.version=19.0`` would imply using an older toolset, but now nobody is defining it?

**Comment by memsharded** [comment]
Nevermind, I realized it needs to be passed instead to ``vcvars_ver`` I forgot about that arg. Doing a proposal for next 1.39 in https://github.com/conan-io/conan/pull/9187 (if there is a minor 1.38.1, this might be added to it, but don't know yet)
