### ISSUE TITLE
Environment: New conan.conf entries for env variables

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#918]
conan.conf new entries to configure:
- CONAN_TRACE_FILE
- CONAN_LOG_RUN_TO_FILE
- CONAN_LOG_RUN_TO_OUTPUT
- CONAN_PRINT_RUN_COMMANDS 
- ...
- Check docs

NOTE: Will keep the env variables

**Comment by claasd** [comment]
Please keep in mind that the current behavior is very easy for automated settings, (e.g. changing behavior by script). 
If you remove all environment variables and replace them with conan.conf entries, please add a way to modify these options by command line, or by some other "scriptable" means.

**Comment by memsharded** [comment]
No worries, the opposite is true, we want to provide conan.conf support for those environment variables, for those willing to have a file based configuration, but no plan to remove the environment variables.
