### ISSUE TITLE
To discuss: What if we want to modify/add some variable in the environment before generate? what would be the best interface?"

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9181]
It was related to my previous comment: `"To discuss: What if we want to modify/add some variable in the environment before generate? what would be the best interface?"` 
Users might call first to `environment()` then modify something and finally generate, but I'm not convinced, that's why I was asking to discuss it.

_Originally posted by @lasote in https://github.com/conan-io/conan/pull/9131#discussion_r660599238_

**Comment by lasote** [comment]
The PR https://github.com/conan-io/conan/pull/9256 implements a `remove` and `items` methods for the Environment objects. That might be enough. I removed the previous "public" methods that return an _EnvValue object because I think it they should be always private.
