### ISSUE TITLE
[question] conan install + "-if" disregarded?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#9182]
Hello,
I am playing with scm + conan install. As I understand if I use "conan install -if install_folder . package_revision --build=missing", SCM will not be triggered, and source is not downloaded from git/svn, but package is installed into "install_folder". However if I use "conan install -if install_folder package_name/package_revision --build=missing" the sources are downloaded from git/svn, put into Conan's cache, but "-if" is disregarded in this scenario and package is installed into the cache.

Is it an expected behaviour? Meaning "-if" is disregarded if SCM is used
Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

No, I think you misunderstood. Packages are never installed into ``install_folder``, they are always installed in the cache. The ``install_folder`` is to locate generated installation files, like ``conaninfo.txt``, ``conanbuildinfo.txt`` and others. These files will be removed in Conan 2.0, so ``install_folder`` will no longer make sense and be removed.

**Comment by harsszegi** [comment]
Understood, thanks a lot for the clarification! (btw right now if we use (1.37) "-if" during install the package IS installed into the folder we provide after "if"

**Comment by memsharded** [comment]
> Understood, thanks a lot for the clarification! (btw right now if we use (1.37) "-if" during install the package IS installed into the folder we provide after "if"

Can you please check it twice? I don't think this happens. Could you please provide something to reproduce if that is the case? It would be a very surprising bug.

**Comment by harsszegi** [comment]
Oh god, I'm lame, sorry, completely mixed up the outputs for conan install and conan build :( Sorry :(

**Comment by memsharded** [comment]
> Oh god, I'm lame, sorry, completely mixed up the outputs for conan install and conan build :( Sorry :(

No prob! :) :) :)
