### ISSUE TITLE
[feature] Use of self.dependencies within build method

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#9190]
Hi,

the documentation of the new `self.dependencies` feature asks to submit to a GitHub issue if the feature is used outside of the methods `generate()` and `validate()`.

I'm using this feature in the `build` method as it provides the package folder of a build requirement which is otherwise - as far as I know - not possible to get easily (`rootpath` is only available for normal requirements).

It seems that the usage works fine, however, I file this issue for documenting my need so that you don't remove the support in future ;).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @gpxricky 

Thanks for the feedback. My suggestion would be:

- Do that processing in the ``generate()`` method instead. Whatever you are going to use in the ``build()`` method, put it into a file. 
- There is a ``conanbuild.json`` experimental file we are using, but that will be changed, so at the moment better serialize it to your own file
- Then ``build()`` read that information, and use it. ``build()`` method logic remains simpler, part of the complexity has moved to ``generate()``.
- If you can do it in a build-system native way (like generating a myfile.cmake file, then include(myfile.cmake) in your CMakeLists.txt), that is much better.

Doing this has a major advantage over doing things directly in the ``build()`` method: you enable developers flow, and things might be run from user. If you don't do this, your build as a consumer, in user space will always require calling the ``conan build`` command, and make it more difficult to build things from IDEs, or even from the command line.

Please let me know if this makes sense and what you think about it.

**Comment by gpxricky** [comment]
Thanks for the hint and clarification. I will check that and come back later ;)

**Comment by gpxricky** [comment]
Solution works fine. Therefore closing the issue.
