### ISSUE TITLE
[question] How to read host and build profile in the Conan recipe

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#9193]
Hi,

is there a way to read the configured profile (both host and build) in a Conan recipe? I didn't find a property or method to get that information.

Many thanks for your help.
gpxricky

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The profile host is:
- self.settings
- self.options
- self.buildenv
- self.runenv
- self.dependencies

The profile build is only available when you are in a build_require, in the build context. Besides the above, there is:
- self.settings_build
- self.dependencies (it gets requires with build=True, and dependencies with context="build")

**Comment by gpxricky** [comment]
Thank you, that's interesting.

What about if I want to call the `install_references` API method within my Conan recipe to explicitly deploy one of my requirements? How to hand over the identical profile parameters than "I" was called? Or is this the wrong way to do so and there is another mechanism available for that purpose?

Many thanks

**Comment by memsharded** [comment]
``install_references()`` doesn't install one of your requirement, it install the complete dependency graph of that reference that is provided.

I am not sure why you are calling it directly or what you are doing. If you are calling it iteratively for different references, that is dangerous, because it will install different dependency graphs, that could have conflicts if resolved together at once, and the output generated files could overwrite the previous ones.

The method is:
```python
@api_method
    def install_reference(self, reference, settings=None, options=None, env=None,
                          remote_name=None, verify=None, manifests=None,
                          manifests_interactive=None, build=None, profile_names=None,
                          update=False, generators=None, install_folder=None, cwd=None,
                          lockfile=None, lockfile_out=None, profile_build=None,
                          lockfile_node_id=None, is_build_require=False, conf=None):
        profile_host = ProfileData(profiles=profile_names, settings=settings, options=options,
                                   env=env, conf=conf)
```
The ``profile_build`` is already a ProfileData that contains the different profile names, settings, and options, you should compose it before calling the api.

**Comment by gpxricky** [comment]
To be honest, I just want to call the `deploy` method in the recipe of the requirement. I thought I can easily realize that by using the `install_references` method, however I'm missing some information to call it properly or build the `profile_build` parameter (e.g. the profile names, etc.).
E.g. some of my requirements need to be copied to a predefined location instead of the Conan cache (I know that's bad design but at present they are provided to us in that manner).

**Comment by memsharded** [comment]
That is the thing, the ``deploy()`` method deploys for the current package, as well as all its dependencies. So it needs to install the dependencies, and for that it needs to evaluate the graph, and provide the profiles. 

Curious about why you are using the api for this, and not directly ``conan install <ref> -pr=myprofile`` command?
You might not need the ``-pr:build=myprofilebuild``, and likewise in the api, you could probably leave the ``profile_build=None`` in the api

> What about if I want to call the install_references API method within my Conan recipe to explicitly deploy one of my requirements? How to hand over the identical profile parameters than "I" was called?

There is not such a thing of the ``identical profile parameters than "I" was called``. When the package was created it did create multiple binaries, one for each configuration (or profile):

```bash
conan create . mypkg/1.0@ -pr=myprofile1
conan create . mypkg/1.0@ -pr=myprofile2
conan create . mypkg/1.0@ -pr=myprofile3
```

Now you want to deploy one of these, providing the ``profile`` is completely necessary to identify which configuration you want to deploy:
```bash
conan install mypkg/1.0@ -pr=myprofile1
```

Am I missing something of your use case?

**Comment by gpxricky** [comment]
Just for clarification, here is the use case I would like to use:

- Top level Conan recipe for `MyPkg` references some requirements, e.g. `MyDep1` and `MyDep2`
- `MyDep1` needs to be deployed to a well-known path `/opt/mydep1` before running the `build` method, otherwise the build will not work
- No matter if I use `conan install` or the api (I just thought it is more powerful but I can also use the command line of course), I don't know which profile parameters to pass to the `install` command. I would like to hand over the same parameters (as they were used to resolve the correct dependencies)

So, e.g.

```
conan create . MyPkg/1.0@ -pr=myprofile1
```

shall internally call

```
conan install MyDep1/<version>@<user>/<channel> -pr=myprofile1
```

It is no problem to call `conan install`, but I can't figure out how to pass the profile to the command. At present MyDep1 package is downloaded for `myprofile1`, but when running `conan install` internally it uses the default profile in my cache which is `mydefaultprofile` instead of `myprofile1`.

**Comment by gpxricky** [comment]
I'm a little bit closer to what I was searching for. However I'm not really convinced that I'm doing the right thing:

```
options_list = [
    f"{key}={value}" for key, value in self.options["MyDep1"].items()
]

settings_list = [
    f"{key}={value}" for key, value in self.settings.items()
]

self.api.install_reference(reference_of_mydep1,
    options=options_list,
    settings=settings_list,
    install_folder="/opt/mydep1"
)
```

However, I guess that only works if `MyDep1` itself has no dependencies with options, doesn't it? Furthermore how to add the build profile? Something like this?

```
# Just pseudo code
build_settings_list = [
    f"{key}={value}" for key, value in self.settings_build.items()
]

build_profile = ProfileData(profiles=None,
    settings=build_settings_list, options=None,
    env=None, conf=None)
```

**Comment by gpxricky** [comment]
@memsharded 

As the Conan package I want to deploy is already available in the Conan cache and a dependency of my recipe: is there any way to get rid of all the profile, settings and other stuff, just read out the full package reference (including package_id, revisions, etc.) for my dependency and then call the `deploy` generator on it?

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

Conan 2 has now a new API, way more detailed (like a ``profiles`` subapi).
I am closing this ticket as outdated, please create new tickets for any further question or issue, many thanks for your feedback.
