### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#920]
Conan can authenticate only by a raw pair in [users] section. This validation works fine, however, in an integrated solution is a weak point, it's necessary copy all users and passwords in _server.conf_.  

This new feature could improve the integration to others services (Gitlab and Gogs).  

I didn't see a request before, so, I forked to implement this feature.  
I have chosen _python-ldap_ to solve the LDAP client.  
Please, take a look [here](https://github.com/uilianries/conan/tree/feature/ldap)  
Regards,

**Comment by uilianries** [comment]
https://github.com/uilianries/conan-ldap-authentication

**Comment by memsharded** [comment]
Thanks for tracking and closing this!
For interested readers, check general instructions also here: http://conanio.readthedocs.io/en/latest/server.html#authentication
