### ISSUE TITLE
[question] Conan cache + alias package + remote

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#9200]
Hi,
I am having issues with consistency between the Conan cache and the remote.
I am creating a package and I have an alias for it (practically something like "latest").
Whenever I export a new package, I am recreating the "latest" alias ("rolling release").
However it appears that in the clients - which already have an earlier version of "latest" - checking whether the alias package has changed is not done. If the client has a "latest" alias already defined for the package, next time when a new build is done the very same "latest" package is used and not a fresher one - in case I have uploaded a fresher version and updated "latest".
Is it normal?
Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

It is not very clear what is not updating. Are you using the ``--update`` flag and it will not check for new versions in the servers? For the actual ``alias`` package or for the pointed package?

**Comment by harsszegi** [comment]
Ok, it appears I have misunderstood how "conan install" works, I didn't know that by default "--update" is NOT enforced.

**Comment by memsharded** [comment]
> Ok, it appears I have misunderstood how "conan install" works, I didn't know that by default "--update" is NOT enforced.

Yes, the default is to try to be as fast and as offline as possible. Checking servers is slow, so checking for updates is an opt-in.
