### ISSUE TITLE
[suggestion] Usage of custom jinja graph template file

### ISSUE THREAD

**Issue by mh-ka** [conan-io/conan#9205]
Hi there,

I wanted to create a graph with conan info which uses short labels for the nodes. I could achieve to create a custom dot file by checking out the repository and installing the conan dev version (used jinja graph template code is below).

I would like to suggest to make it possible for the user to provide a custom template for the dot file.
- Either by introducing a parameter for the 'conan info' command (e.g. -template='my_info_graph_dot_template.py')
- or by forcing conan to look for a template file in a predefined folder (e.g. in the folder where conanfile is located) and if not found conan takes the standard template file.

What do you think about the suggestion?

Kind Regards,
Mike

```
content = """\
digraph {
node [
  fontsize = "12"
];
{%- for node in graph.nodes|unique|list %}
    "{{ node.short_label }}" [shape="polygon"];
{%- endfor %}
{%- for src, dst in graph.edges %}
    "{{ src.short_label }}" -> "{{ dst.short_label }}"
{%- endfor %}
}

"""
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @mh-ka 

Both the html and the dot files are already templatized. Just change the template in your cache in ``output/info_graph.dot`` file.

Recall that you can install single files in the cache with ``conan config install``, or get it from a git repo, or http zip.

Have a look to https://docs.conan.io/en/latest/extending/template_system/info_graph.html, and let me know if this is what you are looking for.

**Comment by mh-ka** [comment]
Thank you for the quick response! Shame on me, I did not read the documentation properly 🙈

**Comment by memsharded** [comment]
> Thank you for the quick response! Shame on me, I did not read the documentation properly 

No prob, glad to help!
