### ISSUE TITLE
[feature] conan editable could work without explicit package name and version on reference argument

### ISSUE THREAD

**Issue by guiserle** [conan-io/conan#9214]
Currently, `conan editable add` command requires version and package name to be provided on reference argument. If it is not provided the following message is promted:

`ERROR: Name and version from reference (gsl/test) and target conanfile.py (pkg_name/1.0.2) must match`

My proposal is to modify this command to mimic `conan create` command, on which, if package name and version is not provided, conanpacakge.py info is used.

I assume this is straightforward as it is done already on `conan create` and the conanfile.py is also available on this command, but I would inderstand if current implementation of `conan editable add` is done on purpose.

This would make my workflow much easier as currently I generate version dynamically on conanfile.py based on git tag, with dirty and hash flags which makes inconvenient to have to write version on the reference.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @guiserle 

sorry this was not responded back then.

Conan 2 implemented ``conan editable add .`` which doesn't require name and version at all, it will get them from the recipe.

I am closing this as solved, please create new tickets if necessary. Thanks for the feedback.
