### ISSUE TITLE
[QUESTION]Problems creating a package with with .sa library extension

### ISSUE THREAD

**Issue by manape3** [conan-io/conan#9222]
I'm trying to build a package using a private library with .sa extension.

I add it like this:
`self.cpp_info.libs = ['asn-decoder-lib','libosstoed.sa']`

But when I run the conan test for the package it says
`/usr/bin/ld: cannot find -llibosstoed.sa
`
libosstoed.sa is a thirdparty library that is the same as the static one (libosstoed.a) but is built with object code suitable for use in a shared library.)

The link.txt file generated:
`/usr/bin/c++ -O3 -DNDEBUG -rdynamic CMakeFiles/example.dir/example.cpp.o -o bin/example-SOVERSION -ldl /root/.conan/data/asn-decoder-lib/0.1.0/exfo/stable/package/97e1027d2f33d6f3782268dfae4c519b4f10e2e8/lib/libasn-decoder-lib.a -llibosstoed.sa`

**Comment by memsharded** [comment]
Hi @manape3 

Quick question: which generator are you using in the ``test_package``? Is this a Linux?

Still not sure where the failure is, it is possible that some code is handling only known library extensions, either Conan or CMake. Irrespective of a potential fix for this, have you tried to just rename the ``libosstoed.sa`` => ``libosstoead.a`` in the ``package()`` method of the recipe? That would most likely solve your issue. If the difference is that the static library was built with the fPIC, I'd recommend using the ``option.fPIC`` that is some convention that some Conan helpers can also understand.

**Comment by AbrilRBS** [comment]
Closing because we didn't hear back from you in a while. If anyone seems to ace the same issue, please check the proposed solution or create a new issue, we're always happy to help! :)
