### ISSUE TITLE
[question] use jfrog as conan server

### ISSUE THREAD

**Issue by chery1392** [conan-io/conan#9226]
hello,
I used import and export feature of jfrog for move repo to another jfrog artifactory.  after import, conan search can not work on jfrog repo and show "There are no packages" but conan install work and install package.

**Comment by memsharded** [comment]
Hi @chery1392 

There is no information enough to know what could be happening. If you did an Artifactory ugprade from a quite old version, it is possible that you hit a random problem with a migration, we have had a couple of reports in the past.

If your Artifactory is a premium one, probably you can also contact JFrog support, and they could help there, whatever happens in an Artifactory migration from one repo to another is out of the scope of Conan, and we can do nothing there.

**Comment by chery1392** [comment]
we used JFrog Artifactory Community Edition (jfrog-artifactory-cpp-ce-7.21.3-linux). we tested jfrog-artifactory-cpp-ce-7.19.10-windows also.
we import and export from same version JFrog Artifactory Community Edition(7.21.3).

**Comment by memsharded** [comment]
As Conan is not involved in this operation, this would be an Artifactory issue. I'd recommend to file an issue against their JIRA: https://www.jfrog.com/jira/projects/RTFACT/issues. Please:

- Provide detailed instructions, with something to reproduce, including the full import and export commands that you are running. Pay special attentions to the layouts.
- Make sure the ``conan install`` is working fine, not only that the packages are installed, but also that they are usable (try remove the local cache first).
- Link the JIRA ticket here, so we can also track it, and try to help there.

If you would like other possible workarounds the issue, you might try to ``conan download`` + ``conan upload``, it will be probably much slower, but can help to get things working.

**Comment by memsharded** [comment]
Hi @chery1392 

Any update here? Do we have a Jira ticket? Any details to reproduce the issue? 
Thanks!
