### ISSUE TITLE
[question] How to set conan cache path?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9233]
By default the cache path is `/path/to/home/.conan`.
I want to make it somewhere else, anyway?

**Comment by memsharded** [comment]
Define CONAN_USER_HOME env-var to locate it in a different folder.

**Comment by playgithub** [comment]
Thanks

**Comment by playgithub** [comment]
It sets the parent folder path of local cache folder path.
e.g. When `ONAN_USER_HOME=D:\aaa`, the local cache folder path will be `D:\aaa\.conan` instead of `D:\aaa`

**Comment by memsharded** [comment]
Yes, you are right, the .conan folder is always generated inside. Conan 2.0 will change that, it was not possible to change that behavior without breaking at this moment.
