### ISSUE TITLE
[question] How to do case insensitive search on Windows?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9234]
```
λ conan search boost --remote conan-center
Existing package recipes:

boost/1.64.0@conan/stable
boost/1.65.1@conan/stable
boost/1.66.0@conan/stable
boost/1.67.0@conan/stable
boost/1.68.0@conan/stable
boost/1.69.0
boost/1.69.0@conan/stable
boost/1.70.0
boost/1.70.0@conan/stable
boost/1.71.0
boost/1.71.0@conan/stable
boost/1.72.0
boost/1.73.0
boost/1.74.0
boost/1.75.0
boost/1.76.0

C:\Users\alg\Develop
λ conan search BOOST --remote conan-center
There are no packages matching the 'BOOST' pattern
```
```
λ conan --version
Conan version 1.38.0

λ conan search --help
...
--case-sensitive      Make a case-sensitive search. Use it to guarantee case-sensitive search in Windows or other case-insensitive file systems
...
```

How to do case insensitive search on Windows?

**Comment by memsharded** [comment]
By default, it is case insensitive in Windows (in the local cache):

```
conan search ZLIB

zlib/1.2.11
```

Remote search is case sensitive always.

In any case, it was already approved that packages should always be lowercase, this policy has been enforced in ConanCenter for more than 1 year, and Conan 2.0 will allow only lowercase package names, it has already been approved by the tribe.

**Comment by playgithub** [comment]
However the user have to remember the artificial rule (i.e. lowercase only).
If doing search in case sensitive way by default and doing fuzzy search with options,  no implicit rule is needed.

**Comment by playgithub** [comment]
@memsharded 

e.g. there is a lib called `CGridListCtrlEx`

@github
https://github.com/snakefoot/cgridlistctrlex

@codeproject
https://www.codeproject.com/Articles/29064/CGridListCtrlEx-Grid-Control-Based-on-CListCtrl

`cgridlistctrlex` is not as good as `CGridListCtrlEx`.

**Comment by playgithub** [comment]
e.g. there is a lib called `CGridListCtrlEx`
@github
https://github.com/playgithub/cgridlistctrlex
@codeproject
https://www.codeproject.com/Articles/29064/CGridListCtrlEx-Grid-Control-Based-on-CListCtrl

`cgridlistctrlex` is not as good as `CGridListCtrlEx`.

**Comment by memsharded** [comment]
It is so good, that they did the repo name in lowercase too :) https://github.com/snakefoot/cgridlistctrlex.

They even named the project in their readme as lowercase!

So not a big issue. Indeed a very minor issue compared with all the complexities, issues, and even security concerns that mixing casing brings (typo squatting attacks are easier, for example). This is decided and approved by the Tribe Conan 2.0 (https://conan.io/tribe.html) , packages in Conan 2.0 will be only lowercase.

**Comment by playgithub** [comment]
There are all kinds of lib names, when `conan` being lower case only, the original lib name can not be kept.
On the other side, as a pro tool, it's ok.
Thanks
