### ISSUE TITLE
[question] faster way to export lots of recipes?

### ISSUE THREAD

**Issue by tomager** [conan-io/conan#9238]
I have quite a lot of recipes defined in a private repository that I export and upload to local cache and a single conan-server running on localhost. A script does the export/upload by executing "conan export ..." and "conan upload ..." for each recipe.

That takes something like 1-2 seconds per recipe, which adds up to multiple minutes to export the whole set of recipes, which is pretty painful.

Is there a faster way to export/upload groups of recipes? If not, why is it so slow and would a patch to do batch export/upload be welcome?

Thanks!

**Comment by memsharded** [comment]
Hi @tomager 

There are a couple of things that make this not very fast, but the application startup time is relevant here. We have some plans to try to reduce it in Conan 2.0, but probably cannot reduce very much.

What you might try is to use the internal Python ``conans.client.conan_api.py``. It is not documented, it is not stable (it can change in next releases, breaking), but we have been trying not to break it, and there are other users using it at their own risk. So if that is a bottleneck, I would suggest giving it a try. The python api will be released and documented in Conan 2.X, but meanwhile, if something change in a future release (unlikely) ,fixing it is straightforward, so maybe worth it.

If the server you are using is the ``conan_server`` I would also suggest to use the free ArtifactoryCE, it is typically much faster and scales better (for example it has file de-duplication saving a ton of storage and transfers) (not to say it has many other features, like webUI, better permissions, generic repos, etc), you will notice in upload/download operations

**Comment by tomager** [comment]
Thanks-- I will check out the API.

I found ArtifactoryCE quite challenging to set up in a simple self-contained way and anyway much more than what we needed (was hoping for single-line docker set up, but it wanted to install postgres on host machine etc, or in any case wasn't obvious at the time). We are mostly just uploading recipes and not packages, and access is limited to at most a couple dozen users. conan_server is working very well for us.

Anyway the time [1] seems to be dominated by whatever local work the conan scripts are doing, and equal for both export and upload. A quick glance at cProfile output doesn't show a smoking gun, just lots of python bits doing their thing. Maybe running with pypy would help?

```
# time conan export m4/all m4/1.4.18@
Exporting package recipe
m4/1.4.18 exports: File 'conandata.yml' found. Exporting it...
m4/1.4.18 exports: Copied 1 '.yml' file: conandata.yml
m4/1.4.18 exports_sources: Copied 9 '.patch' files
m4/1.4.18: The stored package has not changed
m4/1.4.18: Exported revision: 04354ef837a21a88b09ff00795ba3ae7

real    0m0.743s
user    0m0.619s
sys     0m0.124s

# time conan upload -r remote m4/1.4.18@
Uploading to remote 'remote':
Uploading m4/1.4.18 to remote 'remote'
Compressing conan_export.tgz completed [1 files]
Compressing conan_sources.tgz completed [9 files]
Recipe is up to date, upload skipped

real    0m0.758s
user    0m0.675s
sys     0m0.080s
```

**Comment by tomager** [comment]
Hmm, after install pypy3 and pip + conan within it, it's actually slower than standard python3:

```
# time pypy3 /usr/local/bin/conan export m4/all m4/1.4.18@
Exporting package recipe
m4/1.4.18 exports: File 'conandata.yml' found. Exporting it...
m4/1.4.18 exports: Copied 1 '.yml' file: conandata.yml
m4/1.4.18 exports_sources: Copied 9 '.patch' files
m4/1.4.18: The stored package has not changed
m4/1.4.18: Exported revision: 04354ef837a21a88b09ff00795ba3ae7

real    0m3.091s
user    0m2.897s
sys     0m0.178s

```

**Comment by memsharded** [comment]
> I found ArtifactoryCE quite challenging to set up in a simple self-contained way and anyway much more than what we needed (was hoping for single-line docker set up, but it wanted to install postgres on host machine etc, or in any case wasn't obvious at the time). We are mostly just uploading recipes and not packages, and access is limited to at most a couple dozen users. conan_server is working very well for us.


This is weird, we use docker for running Artifactory for example for training courses (e.g https://github.com/conan-io/training/blob/master/docker_environment/artifactory-training/Dockerfile), and it was relatively straightforward. Feel free to report any installation issues if you give it another try if you start to need a bit more speed and power.



Isn't the loading/import time in the export the dominant thing? I see your export at ``real    0m0.743s``, and up to my knowledge the python and Conan app startup time might be around 0.5 seconds, so this would be it?

**Comment by tomager** [comment]
Using the API directly as you suggested makes a huge difference. The time I'm seeing is mostly in the app startup. Here is the script I'm using to export multiple recipes [2]. The time is much improved for multiple exports in one run [1].

[1]
```
# time ./export2.py m4
args ['m4']

m4
  1.4.18 -> all
Exporting package recipe
m4/1.4.18 exports: File 'conandata.yml' found. Exporting it...
m4/1.4.18 exports: Copied 1 '.yml' file: conandata.yml
m4/1.4.18 exports_sources: Copied 9 '.patch' files
m4/1.4.18: The stored package has not changed
m4/1.4.18: Exported revision: 04354ef837a21a88b09ff00795ba3ae7

real    0m0.748s
user    0m0.664s
sys     0m0.086s

# time ./export2.py m4 m4 m4 m4
args ['m4', 'm4', 'm4', 'm4']

m4
  1.4.18 -> all
Exporting package recipe
m4/1.4.18 exports: File 'conandata.yml' found. Exporting it...
m4/1.4.18 exports: Copied 1 '.yml' file: conandata.yml
m4/1.4.18 exports_sources: Copied 9 '.patch' files
m4/1.4.18: The stored package has not changed
m4/1.4.18: Exported revision: 04354ef837a21a88b09ff00795ba3ae7

m4
  1.4.18 -> all
Exporting package recipe
m4/1.4.18 exports: File 'conandata.yml' found. Exporting it...
m4/1.4.18 exports: Copied 1 '.yml' file: conandata.yml
m4/1.4.18 exports_sources: Copied 9 '.patch' files
m4/1.4.18: The stored package has not changed
m4/1.4.18: Exported revision: 04354ef837a21a88b09ff00795ba3ae7

m4
  1.4.18 -> all
Exporting package recipe
m4/1.4.18 exports: File 'conandata.yml' found. Exporting it...
m4/1.4.18 exports: Copied 1 '.yml' file: conandata.yml
m4/1.4.18 exports_sources: Copied 9 '.patch' files
m4/1.4.18: The stored package has not changed
m4/1.4.18: Exported revision: 04354ef837a21a88b09ff00795ba3ae7

m4
  1.4.18 -> all
Exporting package recipe
m4/1.4.18 exports: File 'conandata.yml' found. Exporting it...
m4/1.4.18 exports: Copied 1 '.yml' file: conandata.yml
m4/1.4.18 exports_sources: Copied 9 '.patch' files
m4/1.4.18: The stored package has not changed
m4/1.4.18: Exported revision: 04354ef837a21a88b09ff00795ba3ae7

real    0m0.881s
user    0m0.759s
sys     0m0.122s

```

[2]
```
#!/usr/bin/env python3

import yaml
import os
import sys

from conans.client.conan_api import ConanAPIV1
conan_api = ConanAPIV1()

args = sys.argv[1:]
if len(args) == 0:
    args = os.listdir(".")
print("args",args)

for f in args:
    if not os.path.isdir(f): continue
    if f == ".git": continue
    if f == ".gitignore": continue
    if not os.path.isfile(f+"/config.yml"): continue

    config = yaml.safe_load(open("%s/config.yml" % f, 'r'))
    print("")
    print(f)
    for version,spec in config["versions"].items():
        folder = spec["folder"]
        print("  %s -> %s" % (version, folder))

        conan_api.export("%s/%s" % (f,folder), f, version, None, None)

```

**Comment by memsharded** [comment]
Good, then I think it would be fair to use the api, beware at each Conan release upgrade, just in case it breaks (unlikely, but possible).

**Comment by tomager** [comment]
Thanks for your help!

**Comment by memsharded** [comment]
Ok, as there is nothing immediate that we need to fix here, lets close this issue, but don't hesitate to re-open of file a new one if you have any further question. Thanks!
