### ISSUE TITLE
[bug] layout() method does not propagate includedirs to clients

### ISSUE THREAD

**Issue by wer14** [conan-io/conan#9246]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.38.0
  * Python version: 3.8.3

I'm trying to use the new [`layout` method](https://docs.conan.io/en/1.38/reference/conanfile/methods.html#layout) but it seems it's not working correctly. After my package is built with `conan create` test package build fails with the error:

`Cannot open include file: 'foo.h': No such file or directory`

In the generated solution file (I'm working with Visual Studio) the `Additional Include Directories` section is empty. It seems that the `layout()` method doesn't propagate include directories to clients. It works neither with components nor without them. At the same time, the libraries, the client should link against, are propagated as intended (generators in use are: `CMakeDeps` and `CMakeToolchain`):

```
def layout(self):
          self.cpp.package.includedirs = ["foo/include"]  # not propagated
          self.cpp.package.libs = ["foo"]  # propagated
          self.cpp.package.components["foo"].includedirs = ["foo/include"]  # not propagated
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @gmikhaile 

I have added a test in https://github.com/conan-io/conan/pull/9297, it seems that this works fine and the information is being propagated correctly to consumers.

Could you please have a look at the test there, it should be relatively easy to follow, and let me know? Any hint to reproduce the behavior you are reporting would help, thanks!

**Comment by memsharded** [comment]
We plan to branch 1.39 to be released next week, this Friday 23 if possible, it would be great to have feedback by then if there is a chance to be included in 1.39.

**Comment by wer14** [comment]
@memsharded We've found out that the `cmake` generator doesn't add directories specified in `self.cpp.package.includedirs` to the `CONAN_INCLUDE_DIRS_FOO` variable when these directories don't exist on the filesystem. The `CMakeDeps` generator populates the `foo_INCLUDE_DIRS_RELEASE` variable with both existent and non-existent directories. Is this behavior for the `cmake` generator intended or not?

**Comment by memsharded** [comment]
Yes, I think this is not properly explained in the docs, we need to fix the documentation. The "legacy" integrations, like ``cmake`` are not going to be upgraded to completely support the new layout feature, as the risk of breaking is high. Only the new integrations in https://docs.conan.io/en/latest/reference/conanfile/tools.html will fully support the ``layout()`` feature. Note that internally we are fully replacing all the infrastructure, from the new ``self.dependencies`` to a new ``self.cpp_info``.

**Comment by memsharded** [comment]
Submitting https://github.com/conan-io/docs/pull/2163 to clarify this in the docs.

**Comment by wer14** [comment]
Thank you for the clarification.
