### ISSUE TITLE
[question] handling pre-compiled binaries in an export-pkg + download in build() method manner

### ISSUE THREAD

**Issue by rthomaskelly** [conan-io/conan#9247]
I read [the docpage about handling pre-compiled binaries](https://docs.conan.io/en/latest/creating_packages/existing_binaries.html) a couple times. The page seems to recommend two things:
0. Use export-pkg as opposed to any conan create/build/install/etc...
1. Download the binary from a static link in the build() method of your conanfile.py. If it is a tarball use tools.get() to unpack it.

I gave this a try but found that the build() method is not called in my pre-compiled binary conan recipe. I found on a different doc page that of the 13 conanfile methods, 5-11 (I think) are not called when using export-pkg. I think build() was 5 on that list so it then makes sense that it was not called.

So how do I rightly package pre-compiled binaries if the steps of export-pkg + download in build() are incompatible?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @rthomaskelly 

Let me clarify:

- There is one method, doing the download of the binaries in the ``build()`` method, and executing a regular ``conan create``, that will run all methods, including the ``build()``. Useful for binaries hosted in a server elsewhere
- The method that package existing binaries that are in the local filesystem, typically besides the ``conanfile.py``. This is done with ``conan export-pkg``, and that doesn't execute the ``build()`` method at all, it directly creates the package calling the ``package()`` method

Let me know if this helps.

**Comment by rthomaskelly** [comment]
Ok thank you. Yes I was certainly confused. To now clarify the second bullet: `conan export-pkg` won't actually upload the binaries, or will it? I'm surprised to hear that it does not require a conanfile. The help menu says "exports a recipe." It actually creates and exports some templated recipe then?

**Comment by memsharded** [comment]
> Yes I was certainly confused. To now clarify the second bullet: conan export-pkg won't actually upload the binaries, or will it?

Yes, it will not upload the binaries to anywhere, it will create a new package binary in the cache, but everything is local (unless the package has dependencies that were not fetch previously, they will need to be downloaded to compute the correct package_id for the current package).

>  I'm surprised to hear that it does not require a conanfile. The help menu says "exports a recipe."

Yes, yes, it does need a ``conanfile.py``. Specially, it typically requires a ``conanfile.py`` with a ``package()`` method to decide what is being exported. If you mean the ``conan export-pkg -h`` output:

```bash
Exports a recipe, then creates a package from local source and build folders.
```
An export-pkg does need a conanfile.py, it first execute the equivalent to running a ``conan export`` to put the current conanfile.py in the cache, then exports the binary files to create the actual package binary for the current configuration. The first ``conan export`` is needed to guarantee there is always a recipe conanfile.py, as there cannot exist a package binary without its container package recipe.

**Comment by memsharded** [comment]
Closing as responded back then, also as outdated, as Conan 2 did some changes, now ``export-pkg`` can for example run ``test_package`` too. Please create new tickets if necessary, thanks for your feedback.
