### ISSUE TITLE
[bug] AutoToolsBuildEnvironment : -arch flag is needed in LDFLAGS as well

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#9252]
`AutoToolsBuildEnvironment` helper currently adds `-arch` flag into CFLAGS: 
https://github.com/conan-io/conan/pull/8118/files#diff-a40e1623c8585581fd34b34ce184bebb85122f57120535d8aee613cfe5a9e766R360

we're doing many M1 builds right now that require `-arch arm64` (at least during cross-compiling).
as result, we have errors for shared builds only:
```
ld: warning: ignoring file /Users/sse4/.conan/data/readline/8.0/_/_/package/33e55c2a33e357d041605e146d6e927f5bb96ecd/lib/libreadline.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64ld: warning: ignoring file /Users/sse4/.conan/data/readline/8.0/_/_/package/33e55c2a33e357d041605e146d6e927f5bb96ecd/lib/libhistory.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```
because of missing `-arch` in `LDFLAGS`.
we currently don't have such a test for shared builds (probably, due to the fact iOS didn't support shared libraries at all, the issue went unnoticed for quite a while).

as result, I had to put ugly workarounds to recipes:
```
diff --git a/recipes/readline/all/conanfile.py b/recipes/readline/all/conanfile.py
index b9645a63b..72ae8ad8c 100644
--- a/recipes/readline/all/conanfile.py
+++ b/recipes/readline/all/conanfile.py
@@ -66,6 +66,10 @@ class ReadLineConan(ConanFile):
             configure_args.append("bash_cv_wcwidth_broken=yes")
         self._autotools = AutoToolsBuildEnvironment(self, win_bash=tools.os_info.is_windows)
+        if self.settings.os == "Macos" and self.settings.arch == "armv8":
+            # this should be really done automatically by the AutoToolsBuildEnvironment helper,
+            # but very unlikely old helper will be fixed any time soon
+            self._autotools.link_flags.extend(["-arch", "arm64"])
         self._autotools.configure(args=configure_args, configure_dir=self._source_subfolder)
         return self._autotools
```
it doesn't scale well, and I would prefer build helper to handle that.
I know the old `AutoToolsBuildEnvironment` is unlikely to be fixed, but rolling new toolchains to conan center might take weeks literally.
the code is fragile and it's easy to make breaking changes while fixing it, so up to you if we want to fix it at all.

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by lasote** [comment]
@memsharded do you think it is ok to add it? I can think we could break if another flag was already specified somehow. But I think this is probay a bug not to add it.

**Comment by memsharded** [comment]
AutoToolsBuildEnvironment  removed in Conan 2.0, closing this ticket as outdated
