### ISSUE TITLE
[bug] Different behaviours depending how 'CMake' is imported in conanfile.py

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#9257]
Using Conan 1.38 on Windows 10.

I just tracked down a _surprising_ problem. 

When `CMake` build helper is imported as

    from conans import CMake

Then, the resulting CMake helper instances do not handle the toolchain file automatically when calling `CMake.build()`. (It also does not output the executed command to the console).

Whereas if it is included via

    from conan.tools.cmake import CMake

Then the toolchain is automatically handled (and there is a nice output of the executed CMake command in the terminal).

Maybe this is intentional, yet I just wanted to make sure you are aware of this difference in behaviour.

**Comment by Adnn** [comment]
Okay, I found the answer, this is exactly as intended:

https://docs.conan.io/en/1.36/reference/conanfile/tools/cmake.html#cmake

(The two classes have very similar roles, but have important behaviour differences. Maybe having them named exactly the same will catch other users by surprise ; )

**Comment by memsharded** [comment]
> (The two classes have very similar roles, but have important behaviour differences. Maybe having them named exactly the same will catch other users by surprise ; )

Yes, we know, but also, as the ``CMake`` helper, even the new one will be the one that will continue to be used in Conan 2.0, we didn't want to name it something ugly like ``CMakeNew``, so we decided to do a replacemente based on import only, not the name. Not the most intuitive, but looking for a nice Conan 2.0 recipe syntax...
