### ISSUE TITLE
[question] search query filter by option

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#9259]
I want to find a qt package with these options:
shared = True
commercial = False
qtmultimedia = True

How can i tell it to the conan? I didn't find it in docs https://docs.conan.io/en/1.36/reference/commands/consumer/search.html

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
With the ``-q`` query argument:

```bash
$ conan search qt/version@ -q "shared =True AND commercial =False AND qtmultimedia=True"
```

**Comment by xahon** [comment]
Looks like it doesn't work
> conan search -r c qt/5.15.2@ -q "qtmultimedia =True AND commercial =False AND shared =True"
>  
> ERROR: Invalid package query: qtmultimedia =True AND commercial =False AND shared =True. Invalid expression: qtmultimedia. [Remote: c]

**Comment by memsharded** [comment]
You have extra spaces:

```
conan search -r conancenter qt/5.15.2@ -q "qtmultimedia=True AND commercial=False AND shared=True"
Existing packages for recipe qt/5.15.2:

Existing recipe in remote 'conancenter':

There are no packages for reference 'qt/5.15.2' matching the query 'qtmultimedia=True AND commercial=False AND shared=True'
```

**Comment by AbrilRBS** [comment]
Closing as solved, thanks!
