### ISSUE TITLE
[bug] KeyError in VSRuntimeBlock caused by undefined compiler.runtime

### ISSUE THREAD

**Issue by bldrvnlw** [conan-io/conan#9260]
Using a conanfile on Windows with the following in generate

```
    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
```
Fails with 
```
ERROR: conanfile.py (Foo/0.2.0): Error in generate() method, line 34
        tc.generate()
        KeyError: None
```

### Environment Details (include every applicable attribute)
  * WIndows 10 
  * Visual Studio 16 
  * Conan version: 1.38.0
  * Python version: 3.7.6

### Steps to reproduce (Include if Applicable)

A conanfile with generate as described above and running install from the command line
`conan install . Foo/0.2.0@ -s build_type=Release -s compiler.runtime=MD -o shared=False -s compiler="Visual Studio"`

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
shared=False
[build_requires]
[env]

......
conanfile.py (Foo/0.2.0): Generator txt created conanbuildinfo.txt
conanfile.py (Foo/0.2.0): Calling generate()
ERROR: conanfile.py (Foo/0.2.0): Error in generate() method, line 34
        tc.generate()
        KeyError: None

```
The error is traced to the following block in VSRuntimeBlock (line 109-114 conan\tools\cmake\toolchain.py)

```
        runtime = settings.get_safe("compiler.runtime")
        if compiler == "Visual Studio":
            config_dict[build_type] = {"MT": "MultiThreaded",
                                       "MTd": "MultiThreadedDebug",
                                       "MD": "MultiThreadedDLL",
                                       "MDd": "MultiThreadedDebugDLL"}[runtime]
```

runtime is None and the dict lookup fails. Although compiler.runtime is defined on the command line and visible in the Configuration in the log it is not present in settings. I've also tried via the profile.

**Comment by memsharded** [comment]
Hi @bldrvnlw 

Something is missing in your report. I have written the following test according to your description and it works without problem:

```python
@pytest.mark.skipif(platform.system() != "Windows", reason="Only for windows")
def test_cmake_toolchain_error_vs_runtime():
    # https://github.com/conan-io/conan/issues/9260
    client = TestClient()
    conanfile = textwrap.dedent("""
        from conans import ConanFile
        from conan.tools.cmake import CMakeToolchain
        class Pkg(ConanFile):
            os = "os", "arch", "compiler", "build_type"
            def generate(self):
                tc = CMakeToolchain(self)
                tc.generate()
        """)

    client.save({"conanfile.py": conanfile})
    client.run('install . -s build_type=Release -s compiler.runtime=MD -s compiler="Visual Studio"')
    print(client.out)
```

**Comment by bldrvnlw** [comment]
You are correct. I forgot that I was manipulating the package_id by removing the compiler.runtime Which was incorrect for two reasons 

1. I should only do that when building the multi-config package
2. package_id() runs before the the rest so the `del self.settings.compiler.runtime` was having this side effect

**Comment by memsharded** [comment]
Also, please notice that to remove from the ``package_id`` you need to remove ``del self.info.settings.compiler.runtime``, not ``del self.settings.compiler.runtime``

**Comment by bldrvnlw** [comment]
Yes that was the mistake I made. 

Perhaps this is already on the planing for Conan 2 but it might be an idea to have a more OO style interface for manipulating package_id, or similar entities. i.e. first get the PackageID instance and then manipulate object properties. The current distinction `self.info.settings` versus `self.settings` is one that is easy to confuse or mistype.

**Comment by memsharded** [comment]
We will see, this is not a high priority, maybe we will at least rename info => package_id or something, and could try to freeze settings at that stage to avoid incorrect removal, but not fully clear.
