### ISSUE TITLE
trying to understand why conan source method returns error: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by shavesha** [conan-io/conan#9266]
Disclaimer: am new to conan. Every time i run the conan command 
``conan source .``
it returns the error message 
``ERROR: conanfile.py (windmill/0.1.0): Error in source() method, line 58
        tools.get(**self.conan_data["sources"][self.version])
        TypeError: 'NoneType' object is not subscriptable``

I was initially calling ``conan create .`` and this is where the message came from. can any one explain to me the meaning of such an error.

**Comment by memsharded** [comment]
HI @shavesha 

It is very likely that you have your ``conandata.yml`` file empty, or missing.
It seems that you are using some recipes from ConanCenter, but not copying the files, or something.

By the way, it is possible that some recipes from ConanCenter and conan-center-index are not well prepared for the "local flow", i.e. the ``conan source``, ``conan build``, commands, and they only work correctly with ``conan create``.

**Comment by robindegen** [comment]
To me it looks like version 0.1.0 is not in the sources entry in the conandata yml, but only other versions. I made that mistake a lot when converting my packages

**Comment by shavesha** [comment]
Thanks for the quick response @memsharded. I it indeed an empty ``conandata.yml``.

**Comment by memsharded** [comment]
@shavesha good to know! I guess the issue is solved and can be closed, but please tell otherwise. Thanks!
