### ISSUE TITLE
[question] asymmetric behavior of conan upload and conan download

### ISSUE THREAD

**Issue by PengolodhGoedath** [conan-io/conan#9270]
Scenario: I have setup conan with two remote repositories `A` and `B`. I use `conan create` to build a package locally using dependencies from `A`, especially a `python_requires`. Then I upload the just built package to `B` using `conan upload --all --remote B name/version@user/channel:package-id`. When I then try to download the package (with a clean conan cache) using `conan download --remote B name/version@user/channel:package-id`, the command fails due to it being unable to find the `python_requires` dependency on `B`.

1) Why is `conan download` checking dependencies at all? Especially since it states that it will not download them? The package has already been built.
2) Why allow the upload of packages which then cannot be downloaded? An uploaded package is useless if it cannot be used.
3) Can this happen for dependencies other than `python_requires`? If not, what is special about `python_requires` for this to happen?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this wasn't responded back then.

Conan 2.0 has completely changed download/upload. I am closing this ticket as solved in 2.0, please check 2.0 commands and create new tickets as necessary, thanks!
