### ISSUE TITLE
[question] Can you download a project as it appears on github?

### ISSUE THREAD

**Issue by Makogan** [conan-io/conan#9271]
Is it possible for conan to download a directory as an identical mirror of the files in the original git repo?

For example take imgui, a very popular UI for c++. This is the result of doing `ls` inside a git cloned version of the project:

```
backends  examples    imgui.cpp       imgui_draw.cpp  imgui_internal.h  imgui_widgets.cpp  imstb_textedit.h  LICENSE.txt
docs      imconfig.h  imgui_demo.cpp  imgui.h         imgui_tables.cpp  imstb_rectpack.h   imstb_truetype.h  misc
```

Notice the pressence of some .cpp files and the `backends` directory.

This is `ls` in the conan installed package under my user: 

```
bin  conaninfo.txt  conanmanifest.txt  include  lib  licenses  res
```

Which is a substantially different directory, with no cpp files.

In a project I am working on I rely on the pressence of the cpp files to get access to some functions that make it easy to integrate with the imgui backend. That is hacky so one could argue this should be discouraged, but there is another issue. Normally you need to `include` the `backends` directory as well if you want to imitate the examples from the original project, for example:

https://github.com/ocornut/imgui/blob/17ec4f1f6fa64a08892d8dcfa61ace684bae53fc/examples/example_glfw_vulkan/main.cpp#L13

If one tries to include files using the conan install the same way, one encounters an include error, because the implementation files are inside the `res` directory, and thus the include path is different.

Imgui is just an example, I encounter this problem with multiple other libraries, where the directory structure of the conan packages is different from the one encountered int he original repository and as such I encounter compilation errors.

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Makogan** [comment]
Some further researching seems to suggest:

```
def source(self):
        git = tools.Git(folder="libraries/imgui")
        git.clone("https://github.com/ocornut/imgui.git", "master")
```

is the way to go.

**Comment by memsharded** [comment]
Hi @Makogan 

A couple of comments:

- You typically want to get an exact version of the sources, not the master branch, or any other branch, as that is a moving target, and for packaging, reproducibility and traceability is key
- You can get a lot of open source recipes in http://github.com/conan-io/conan-center-index, and the precompiled binaries in https://conan.io/center. The imgui library recipe that you are building is already there, you can start from it if you want to customize it
- Conan packages are binaries, what you get in the "include", "lib", "bin" folders that are installed when you install the package are the binary static or shared libraries and the public headers, not the .cpp source code, that is used for building the package, but typically not packaged.

**Comment by Makogan** [comment]
Hello @memsharded, I understand, thank you for the advice, and for most linked libraries, such as shaderc, freetype, harfbuz... 

conan works just fine, it just happens that the low level integration between vulkan and imgui is quite tricky and some "hacks" such as including the orignal cpp file in a bridge file to expose many functions that are used to interoperate with vulkan make things easier.

Essentially since I use imgui as a header only library (once more because it reduces the effort of integrating it with vulkan), I do need the source files. I understand the moving target and I will look into the recipe to see if it is easy to expose the files I need and avoid having a moving target. However compiling code with future dependency problems beats non compiling code, so at least as of right now I have to stick with the sub optimal solution.

**Comment by memsharded** [comment]
> conan works just fine, it just happens that the low level integration between vulkan and imgui is quite tricky and some "hacks" such as including the orignal cpp file in a bridge file to expose many functions that are used to interoperate with vulkan make things easier.

Ok, yes, I see. Then I guess the approach would be to package the sources, and then the consumer can access them directly via the dependency package folder, and integrate the sources directly into their builds. Understood, thanks for the feedback!
