### ISSUE TITLE
[bug] unresolved external symbol in Windows build

### ISSUE THREAD

**Issue by Steback** [conan-io/conan#9278]
I normally work on Linux and Conan work fine, but I want my project run in Windows also. But I get "unresolved external symbol" error in almost all dependencies.

### Conan file and profile:
```
 [requires]
 spdlog/1.8.2
 glfw/3.3.2
 glm/0.9.9.8
 imgui/1.83
 vulkan-headers/1.2.172
 vulkan-loader/1.2.172
 stb/20200203
 entt/3.6.0
 tinygltf/2.5.0
 nlohmann_json/3.9.1
 bullet3/3.17
 sol2/3.2.3

 [generators]
 cmake

 [imports]
 ./res/bindings, imgui_impl_glfw.cpp -> ../bindings
 ./res/bindings, imgui_impl_glfw.h -> ../bindings
 ./res/bindings, imgui_impl_vulkan.cpp -> ../bindings
 ./res/bindings, imgui_impl_vulkan.h -> ../bindings
```
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### CMake file:
```
...

set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/bin)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(NO_OUTPUT_DIRS)

...

message(${CONAN_LIBS})
target_link_libraries(Game core ${CONAN_LIBS})
```

### Output of the CONAN_LIBS:
```
spdlogglfw3imguivulkan-1BulletDynamicsBulletCollisionLinearMathBulletSoftBodyBullet3CommonBulletInverseDynamicsfmtluagdi32opengl32
```

### Error log:
```
...

core.lib(RenderEngine.cpp.obj) : error LNK2001: unresolved external symbol _vkGetDeviceQueue@16

...
```

Also I get this warning with all  dependencies, I don't know if it affect:

```
C:\Users\name\.conan\data\lua\5.3.5\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\lib\lua.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
```

**Comment by memsharded** [comment]
Hi @Steback 

Yes, it is possible that you are doing a 32 bits build? As you can see in the Conan profile output, the dependencies are installed for 64 bits: ``arch=x86_64``.

If you are using CMake, you might want to call it with ``cmake .. -G "Visual Studio 16 Win64"`` to indicate the 64 bits architecture? (depending on the cmake version, it might not be the default).

**Comment by Steback** [comment]
I am using CLion with CMake version 3.19.2. But I add `-G "Visual Studio 16"` to CMake option as you says and it works perfectly. Thank you!

**Comment by memsharded** [comment]
Great, happy to hear that it is solved!

Please keep in mind, that there is no magic between the build system configuration and the Conan dependencies configuration. When Conan do a ``conan install`` it will get the settings, compiler, version, architecture from the ``profile`` file, which might not be the current configuration that the current build system is using. It is the responsibility of the user to use the same configuration.
