### ISSUE TITLE
[feature] Add ability to have multiple named configurations

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#9279]
It's possible that you might work on multiple projects which have:
* Different settings
* Different configurations
* Different Remote list
* etc.

It would be cool if you could create isolated configurations with settings.yml, conan.conf, etc. Each config would have it's own cache as well. Then you would have an optional argument for commands such as:

```
conan install . --config-name myProject1
```

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Adding an extra argument to absolutely every Conan command, like ``--config-name myProject1``, would be cluttering too much the CLI, which already has some commands with lots of options. Also, easy to forget in some command, and then the behavior would be very confusing. The experience in other languages with environments, tell us that it is necessary manage this with state, activate the environment to be used, and then forget about it for all the following commands.

So it seems the current ``set CONAN_USER_HOME=~/myproject1`` would be enough to achieve this. Each project can easily manage its configuration in a git repo with ``conan config install``. So to setup and use a project from scratch in any computer would be:
```
set CONAN_USER_HOME=<path>/myproject1
conan config install <mygitserver>/myproject1
# all conan commands will be using this myproject settings, config, and cache
```

**Comment by rconde01** [comment]
makes sense....when i read "cache location" for CONAN_USER_HOME, I was thinking just the data directory - but if it's the whole .conan directory then that works. although it still seems a bit ripe for confusion...maybe commands should print out the the current user home if not the default. Not sure about the best solution.

**Comment by AbrilRBS** [comment]
Closing with the proposed `CONAN_HOME` env variable - and in Conan 2, with the addition of the `.conanrc` file that can define a custom `conan_home` entry which Conan will recognize when executing from the same folder as the file :)
