### ISSUE TITLE
[question] Is there compiler.ld setting or WIP?

### ISSUE THREAD

**Issue by benet96** [conan-io/conan#9283]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Hi, I am looking through Conan setting rules. There is compiler.libcxx to set standard C++ library to use, but I didn't find any setting item like compiler.ld to set what linker to use. (Though I know there are several methods to set it without Conan involved, such as -fuse-ld=lld for GCC).

Why Conan has no feature like this? Is it obey the Conan design philosophy, or just a feature work in process? Maybe compiler.ld will be a useful feature for those project need to use different linker such as lld or ld.gold.

---

Perhaps try to select different libc is also the same issue, such as set to link musl-lib or llvm-libc(a WIP project) in Conan.

**Comment by memsharded** [comment]
Hi @benet96 

The current ``settings.yml`` are  like a common denominator, a set of settings that work reasonable well for many cases without creating a big explosion of different binaries to create.

The ``libc`` is typically one of the things that has not been worth so far to define as built-in in Conan. The glibc version is also something that defining it for each version would create too many different binaries, so for production usage it can be enough to define the Linux distro: https://docs.conan.io/en/latest/extending/custom_settings.html

The linker so far could be one of this. The vast majority of users use the builtin compiler linker, so no need to define a different one in settings. Also this should be done only if the linker is going to produce different, incompatible binaries, or it is really desired to track and maintain different binaries for different linkers. As even users that decide to use another linker, do not mix and maintain binaries for different linkers, the settings might still not be necessary to be defined by Conan, and just assumed as default.

Please let me know if this makes sense.

**Comment by benet96** [comment]
Thank you, @memsharded, you did resolve my question. Since I used to working on user-mode Linux network stack, occasionally LD_PRELOAD make effects. Maybe it's true as what the designer of musl-libc recommends LLVM not to write llvm-libc, libc improves too few of performance to be rewritten or reinvented. Certainly, conan-io is also not supposed to specify libc for project.

**Comment by memsharded** [comment]
Ok, good, then I think this issue can be closed, thanks for the feedback!
