### ISSUE TITLE
[question] How to control the CMake generator with (newer) conan.tools.cmake.CMake build helper?

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#9298]
We are trying to build with NMAKE makefiles on Windows.

We would like to set the generator used by `conan.tools.cmake.CMake` to `NMake Makefiles`, but it defaults to `Visual Studio xxx`. Can we change the CMake generator?

**Comment by memsharded** [comment]
Hi @Adnn 

yes, this can be controlled by [conf]:

```
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

Since last release, also in cli arg.

Note that ``CMakeToolchain`` define the conanbuild file that the ``CMake`` helper is reading to execute with that generator.
