### ISSUE TITLE
[question] Flags in CMake command line invocation (-D).

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#9299]
Hi,

I was wandering if there were some differences when configuring a CMake project using the 'definitions' attribute of the CMake helper class, or the 'defs' parameter of its 'configure' method.
In other words, I was expecting that the following two approaches would give the same result:
1)
   cmake.definitions["KEY"]  = "VALUE"
   cmake.configure()
   cmake.build()
   print(cmake.command_line)
   print(cmake.flags)
2)
   cmake.configure(defs = { "KEY" : "VALUE" })
   cmake.build()
   print(cmake.command_line)
   print(cmake.flags)

In fact, the result is the same as for the execution of the 'build' method.
But looking at the 'command_line' and 'flags' attributes, in the second case (approach 2) the expected -DKEY="VALUE" command line flag is missing (using Conan version 1.37.1).
I guess I'm missing or misunderstanding some detail given in the reference.

Best regards

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this was not responded back then.

I am closing this ticket as outdated, it refers to legacy tools that have been removed in 2.0
Please create new tickets if necessary for the new tools,  many thanks!
