### ISSUE TITLE
Custom user and channel for conan test_package

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#930]
When I execute _conan test_package_, my package is exported by default to another user name (from requires):

from [command.py:316](https://github.com/conan-io/conan/blob/develop/conans/client/command.py)
```
 # Forcing an export!
 if not args.not_export:
     self._user_io.out.info("Exporting package recipe")
     user_channel = "%s/%s" % (first_dep.user, first_dep.channel)
     self._manager.export(user_channel, root_folder, keep_source=args.keep_source)
```

It's possible to customize the user and channel, by $CONAN_USER and $CONAN_CHANNEL:

```
 # Forcing an export!
 if not args.not_export:
     self._user_io.out.info("Exporting package recipe")
     export_user = self.user if self.user else first_dep.user
     export_channel = self.channel if self.channel else first_dep.channel
     user_channel = "%s/%s" % (export_user, export_channel)
     self._manager.export(user_channel, root_folder, keep_source=args.keep_source)
```

**Comment by lasote** [comment]
Yes, it works. It reads the user and channel from the test_package/conanfile.py but there you can use those environment variables to adjust your defaults. So just use CONAN_USER and CONAN_CHANNEL :+1:

**Comment by uilianries** [comment]
If already works just setting CONAN_USER and CONAN_CHANNEL, it's okay. 

Thanks!
