### ISSUE TITLE
Support for VS 2022

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9300]
Start preparing settings and toolchains to use the new VS versions:

- Only new build system integrations in ``conan.tools``
- Maybe only the ``msvc`` compiler setting? We need to start pushing this soon if we want it for Conan 2.0

_Originally posted by @memsharded in https://github.com/conan-io/conan-vs-extension/issues/194#issuecomment-884073537_

**Comment by SSE4** [comment]
see also : #9362
