### ISSUE TITLE
[feature] exclude some deps from conan dependency graph 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#9303]
Conan dependency graph is a very useful feature but it become very difficult to use when having too many dependencies.  

This is how our current dependency graph looks like, it is almost unreadable and we are adding more dependencies. 

<img width="721" alt="Screen Shot 2021-07-21 at 2 30 38 PM" src="https://user-images.githubusercontent.com/7117696/126497056-6a7695f8-c58b-44c7-b076-1e7ca5c58d59.png">

It would be very handy to add the ability to exclude some dependencies from this graph. For example excluding third party deps that rarely get changed.

**Comment by memsharded** [comment]
Hi @boussaffawalid 

I think the best approach for this at the moment would be to customize the html/javascript template that is used to generate this graph, not to do it from the Conan client side: https://docs.conan.io/en/latest/extending/template_system/info_graph.html

I understand this would be a nice to have, but at the moment this wouldn't be a priority. If someone is willing to contribute an improved html/js template for the graph, with more powerful features, like hiding/showing packages, etc., it will be very welcome.

**Comment by boussaffawalid** [comment]
@memsharded it seems that info_graph.html does the trick! Thanks!. I will try to contribute to the html/js template.

**Comment by Bbox123** [comment]
Hello, me and my UMICH group want to contribute to this issue! I assume this is still available since it has the appropriate milestone mark. Do you happen to have any suggestions on how to start tackling this issue? Thank you!

**Comment by memsharded** [comment]
The html graph got a very major update very recently in https://github.com/conan-io/conan/pull/15846

I think that PR would alleviate most of the problems referenced in this ticket., but the "filtering" one is not.
I suggest adding another textbox that accepts a comma separated list of patters of packages to hide.
If we want to make the functionality equivalent in the search box, it could be done the same, and extend the search to a comma separated list of patterns.

**Comment by Bbox123** [comment]
> The html graph got a very major update very recently in #15846
> 
> I think that PR would alleviate most of the problems referenced in this ticket., but the "filtering" one is not. I suggest adding another textbox that accepts a comma separated list of patters of packages to hide. If we want to make the functionality equivalent in the search box, it could be done the same, and extend the search to a comma separated list of patterns.

Thank you! We will move forward with that implementation in mind.

**Comment by Bbox123** [comment]
Hello again, our group has implemented a solution based on your suggested design and are hoping to open a pull request by this upcoming week. We just had a question about the contribution guidelines. The guideline step 7 is to make a PR to the conan docs. Should we only move onto this step if our implementation PR is approved? Thanks!

**Comment by memsharded** [comment]
Thanks! You can skip the PR to the docs, the html page should be self explanatory, the box should contain a default "Filter packages" or something like that, can have a hover help too.

Just put ``Docs: Omit`` in the PR.
