### ISSUE TITLE
[feature] Support for intel OneApi classic compilers 

### ISSUE THREAD

**Issue by jjaguilarf** [conan-io/conan#9304]
Recently, intel has made their c/c++/Fortran compilers publicly available by means of their [OneApi toolkits](https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html#gs.70oc5a) that include their _classic_ compilers (based on VS for windows and gcc for linux) as well as their new compilers based on LLVM technologies. However, this _classic_ compilers break the compatibility with conan, as their installation path is different and their way of setting the variables is also different.

The changes needed to support this new versions of the compiler would consist on modifying `conans/client/tools/intel.py`, so that function `intel_installation_path` points to the installation path `/opt/intel/oneapi/compiler/latest/linux/` on the OneApi compilers and function `intel_compilervars_command` executes the OneApi compiler variables script in `/opt/intel/oneapi/setvars.sh`. It appears also that the test present in `conan/conans/test/unittests/client/tools/intel/compilervars_test.py` should also be modified.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Connected to #9026, lets have a look together. A couple of guidelines:

- Support for new compilers settings like this one will probably only be provided by the new integrations in ``conan.tools``
- We might consider further decoupling the intel compiler from the "base" ones, and treat it as a separate compilers. It seems the ``compatible_packages`` fallback to the base one is not being used much (something to discuss)

**Comment by ohanar** [comment]
So we are starting to look at the OneAPI toolkits. For the classic compilers, I think it makes sense to keep the existing scheme at least for conan 1.x, that isn't probably as necessary for Intel's new compilers. I can probably write up a pull request for that within the next few days.

@memsharded Regarding `compatible_packages`, we indeed stopped using it. It just isn't ergonomic -- every package that wants to handle it had to opt into it. Fundamentally, to be usable, a better default than the empty set needed to be established. We use the Intel classic compiler for ~10 of the ~140 packages in our dependency graph, and we ended up just handling this by overwriting the compiler for particular packages in the profile. Unfortunately, this is very clunky and consumes 105 lines of our 174 line profile, so mixing compilers is still a very real issue that needs to better addressed by conan.

**Comment by ohanar** [comment]
Okay, looking at it a bit more, there are more differences between the compilervars vs setvars than I initially thought. I'm not sure a simple patch will be sufficient for the classic compilers, and in particular I think that #9026 will need to be addressed because of the way they have structured things.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/9522 implemented this, will be available next week in 1.41, feedback very welcome!
