### ISSUE TITLE
[question] Is there a "wildcard any" syntax for versions in a Conan workspace definition file?

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#9305]
We are trying out [Conan Workspaces](https://docs.conan.io/en/latest/developing_packages/workspaces.html).

We have a well established list of related repositories we want to be editable toghether in the workspace, so we list their recipe references in the `conanws.yml` file.

Is there a way to use a wildcard for the `version` component of the recipe reference?

I.e, having something like:

```
editables:
    myrepo/[*]@adnn/develop:
```

instead of

```
editables:
    myrepo/ab78c1cc78@adnn/develop:
```

Thank you for reading!

**Comment by memsharded** [comment]
The truth is that Workspaces feature is not very matured, and it is a bit on hold, until we finalize improving the base building blocks: the editables. As you might know we are putting a lot of effort into the ``layout()`` feature, and when this is stabilized we will focus again on workspaces (that will probably be after Conan 2.0).

At the moment, it is not possible, the workspaces need the full, exact version of what is being edited there.

**Comment by Adnn** [comment]
Thank you for the insights!

If I am understanding correctly, even though workspace are a low priority at the moment, the feature will not be discarded (i.e. we are not wasting effort building workflows around them).

**Comment by Adnn** [comment]
Side question: should we close the issue in such situation?

**Comment by memsharded** [comment]
Hi @Adnn 

Sorry this was not followed up back then.

Workspaces are been introduced back in Conan 2.10: https://docs.conan.io/2/incubating.html

The new ``conanws.py`` allows logic to dynamically set the version of editable  packages in the workspace. I am closing this ticket as solved, but please create new tickets for any further question or issue. Thanks very much for the feedback!
