### ISSUE TITLE
[question] How can parent enforce children's option?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#9307]
Hi,
I have a dependency between two recipes "A" depends on "B". "B" is usable on its own, has a few build options.
However if "A" consumes it, it must enforce a specific option in "B". I thought that doing this in "A" would solve this, but apparently not:

  default_options = {
    "B:option_name": "option_value"
  }

"option_name" doesn't seem to be set when building A+B together.
What am I doing wrong? Or what is the expected behaviour /approach here?
Thanks,

**Comment by czoido** [comment]
Hi @harsszegi,
If you want to force `option_name` from `B` in `A`, you can do that in the `configure` method of the conanfile of `A` like this:

```
def configure(self):
    self.options['B'].option_name = 'option_value'
```

Here there's more info from the documentation regarding this topic: https://docs.conan.io/en/latest/mastering/conditional.html#conditional-settings-options-and-requirements

Hope this helps.

**Comment by harsszegi** [comment]
Awesome, thanks a lot!

**Comment by harsszegi** [comment]
Sorry, how can I achieve "*:fPIC", meaning, self.options['\*'].fPIC = True?, all transitive dependencies of the package should be forcefully compiled with fPIC?

**Comment by czoido** [comment]
Hi @harsszegi,
I think it's better not to hardcode options in recipes, I would rather pass it through the command line with `-o *: fPIC=True` or set the default value of the requirements to `True` for `fPIC`.

**Comment by harsszegi** [comment]
Understood, thanks
