### ISSUE TITLE
[question] Search package on another remotes after fail on one of them

### ISSUE THREAD

**Issue by lightater** [conan-io/conan#9308]
Hello, we are hosting our version of boost on one of our remotes. This version works only on custom patching arm and when we searching for boost in remotes on another processor type, Conan look to first remote, find this Arm version and says `Missing prebuilt package for 'boost/1.76.0'`. How we can say to Conan to continue searching on another remotes, and fails only if on all of them no packages or packages are incorrect?

**Comment by memsharded** [comment]
This will be possible but only with revisions enabled, did you enable them? Please try that, I am not fully sure it works right now, but that is the intention. In any case, this will be feasible in Conan 2.0 (revisions always enabled)

**Comment by lightater** [comment]
Thanks!
