### ISSUE TITLE
[question] Get package version from a conanfile in Python?

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#9312]
I have a python script that creates a zip file of source code for distribution and I want the version info to be in the zip file name. Currently, we read the version info from a separate file but with the transition to using conan for building internal binaries I would like to pull the version from the conanfile instead of from this separate file as I often forget to update the 2nd file.

I see there is a python API available (with ongoing development) and was wondering if there was a way I could use that to get the version info from the conanfile as I'd rather not parse the file for keywords. 

Alternatively, it seems like I might be able use conan to create this source distribution directly (using conan create) but I'm not sure how I would distinguish between when I want to create this source zip file vs building binaries. I guess this approach would also stick the source distribution package into the cache, which isn't ideal, but manageable.

Any assistance on either option would be appreciated. I'd rather the version be in the conanfile than have the conan pull the version from the 2nd file.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @nichmj01 

I am not fully sure what is your question, it seems there are different issues, maybe some of this hints could help:

- You can read metadata of the conanfile.py recipe with ``conan inspect``. This helps to avoid parsing the conanfile directly, does some kind of basic evaluation (but most of the evaluation of the recipe, that requires settings, options, etc, will not be done, only the python loading and basic attributes).
- You might use an ``options = {"source": [True, False]}`` in your recipe to identify that you will only be packaging the source and not binaries, but that would require to take care of somethings, like removing ``self.info.settings`` and other options when ``source=True``, skipping the build in ``build()`` etc. Not sure about the overall case though.
- You can also have Conan conanfile.py obtain the version from other files (build scripts, the scm, etc) instead of defining it directly, with the ``set_version()`` method.

> I have a python script that creates a zip file of source code for distribution and I want the version info to be in the zip file name.

You can just use the ``self.version`` field in the conanfile.py to name that file? Is that zipping being executed from the conanfile.py? Need to understand better.

Please let me know if these help, and don't hesitate to open more issues, or provide more details, like explaining with an example: "I have a repo in myrepo.git, that contains some source code, and I want to put a conanfile.py in that repo..."

**Comment by nichmj01** [comment]
> I am not fully sure what is your question, it seems there are different issues, maybe some of this hints could help:

Sorry for the confusing question. I wasn't really sure how to express what I was looking for.


> * You can read metadata of the conanfile.py recipe with `conan inspect`. This helps to avoid parsing the conanfile directly, does some kind of basic evaluation (but most of the evaluation of the recipe, that requires settings, options, etc, will not be done, only the python loading and basic attributes).

This was what I was looking for in my original approach idea! I tested it and with this command I can get the version info. I'm thinking to use the [conan python API ](https://github.com/conan-io/conan/blob/develop/conans/client/conan_api.py) to run the inspect command vs using subprocess. Any recommendations one way or the other for inspect specifically?


> * You might use an `options = {"source": [True, False]}` in your recipe to identify that you will only be packaging the source and not binaries, but that would require to take care of somethings, like removing `self.info.settings` and other options when `source=True`, skipping the build in `build()` etc. Not sure about the overall case though.

`options` was the direction I was also thinking of but it seemed like it would be tricky. This seems to confirm my initial intuition.


> * You can also have Conan conanfile.py obtain the version from other files (build scripts, the scm, etc) instead of defining it directly, with the `set_version()` method.

I saw this but for right now I think I'd rather have the version be in the conanfile directly.

> > I have a python script that creates a zip file of source code for distribution and I want the version info to be in the zip file name.
> 
> You can just use the `self.version` field in the conanfile.py to name that file? Is that zipping being executed from the conanfile.py? Need to understand better.

The zipping is not being executed from the conanfile.py. I have a script `PackageSource.py` that takes a directory and creates a zip file. The directory to be packaged contains a conanfile.py with the version specified.

Example:
- MySource/
  - conanfile.py (version = 1.2.3)
  - src/
    - myfile.cpp
  - ...
  - internal/build related files

I want to be able to run `PackageSource.py {path to MySource}` and have it generate a zip file called `MySource_v1.2.3.zip` which contains just the `src` folder. 
If the version in the conanfile.py changes to 1.3.0, then `PackageSource.py {path to MySource}` and will `MySource_v1.3.0.zip`


Your answer helped.. Thanks!

**Comment by memsharded** [comment]
> This was what I was looking for in my original approach idea! I tested it and with this command I can get the version info. I'm thinking to use the conan python API to run the inspect command vs using subprocess. Any recommendations one way or the other for inspect specifically?

You can probably use the ``conan inspect --json`` json output to get something machine readable without needing to use the python API. The API is relatively stable, though no guarantees, as it is not documented yet. Unless you have a bigger problem, I would say using the cli with ``--json`` could be good enough.

> options was the direction I was also thinking of but it seemed like it would be tricky. This seems to confirm my initial intuition.

Maybe you want to consider an alternative approach:

- Create a ``mypkg_src`` Conan package as a pure source package. No settings, no options, just 1 binary storing those sources.
- Now, if you also want to have Conan packages for pre-built binaries, you could create a ``mypkg`` package that contains a ``build_require`` to ``mypkg_src``.

Just a rough idea, but it might be worth checking, depending on your use case: why do you need to distribute the source via Conan packages (vs git repos, for example)?

**Comment by nichmj01** [comment]
> 
> Maybe you want to consider an alternative approach:
> 
> * Create a `mypkg_src` Conan package as a pure source package. No settings, no options, just 1 binary storing those sources.
> * Now, if you also want to have Conan packages for pre-built binaries, you could create a `mypkg` package that contains a `build_require` to `mypkg_src`.
> 
I'll need to think about it some... I'm not sure if I want to maintain 2 different Conan packages but ultimately it may be fine.

> Just a rough idea, but it might be worth checking, depending on your use case: why do you need to distribute the source via Conan packages (vs git repos, for example)?

We release as software to customers as source code but don't provide access to our git repos as the code is not public and we only want users to get official snapshots. Customer accessible releases are also hosted outside of a code repository (like an ftp server, for example). As such I need to package up the code into some format I can post to for customers to download. Currently that format is a simple zip file with all the internal files stripped out (.gitignore, for example).

I don't really need to distribute the source as Conan packages, we just recently started using conan to manage our internal binaries/dependencies and I'm exploring options for using the tooling conan already provides to create our releases. Right now that's mainly around how to pull the version that I'm already maintaining in the conanfile.py for when I create the release zip file.

One thing Conan packages would be useful for is for dependency management as our projects do depend on each other so customers have to understand which versions of the different packages work together and download them separately. Though I haven't put much thought into how that would work as yet.

**Comment by memsharded** [comment]
Hi @nichmj01 

Was the above idea useful finally? Let us know how it goes, and do not hesitate to open a new ticket if you want to keep talking about this. Cheers!

**Comment by nichmj01** [comment]
@memsharded It was! Thanks for the help.
