### ISSUE TITLE
[bug] --build=![pattern] not applicable (conan 1.38.0)

### ISSUE THREAD

**Issue by FlCamB** [conan-io/conan#9314]
Hello,

I tried to use the --build=![pattern] first named in https://docs.conan.io/en/1.36/reference/commands/consumer/install.html. 

### Environment Details (include every applicable attribute)
  * Operating System+version: 20.04.1-Ubuntu
  * Compiler+version: -
  * Conan version: 1.38.0
  * Python version: 2.7.12, Phython3 version: 3.7.10

### Steps to reproduce (Include if Applicable)

1. Open BASH 
2. run `conan install myPackage/0.6.7c@platform/test --build=!googletest* --build`

### Logs (Executed commands with output) (Include/Attach if Applicable)

`conan install myPackage/0.6.7c@platform/test --build=!googletest* --build`
`bash: !googletest*: event not found`

### Additional Information
Installing the packages with parameters --build or --build=missing fetches the recipe and builds the package.
Example:
`conan install myPackage/0.6.7c@platform/test --build=missing`

**Comment by czoido** [comment]
Hi @FlCamB,
I think that the problem could be that `!` is a special character to bash, did you try to escape the character with `\` like this:

`conan install whatever --build=\!package`

Hope this helps

**Comment by FlCamB** [comment]
Thanks a lot, this is the solving hint!
