### ISSUE TITLE
[feature] Add ability to get build requirements for a package + profile + options

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#9322]
I want to upload all packages and requirements to a private server so that I don't rely on CCI. I can do this for regular requirements using lock files, but I don't see any way to get the build requirements. This will be a problem if I need to rebuild the packages sometime in the future (e.g. for a new compiler).

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @rconde01 

You will also get the ``build_requires`` when you create a lockfile, if you pass the ``--build`` argument to it, like:

```bash
$ conan lock create ...  --build
```

**Comment by rconde01** [comment]
Hmm the documentation is:

```
  -b [BUILD], --build [BUILD]
                        Packages to build from source
```

Is that totally wrong? i'm not sure what that means in the context of a lock file.

**Comment by memsharded** [comment]
No, I would say it is fine, the logic is exactly the same as a ``conan install --build=xxxx``: 

- It will apply the build policy and decide which packages need to be built from source.
- Those packages that need to be built from source will expand their ``build_requires``. Those packages with an existing binary, do not require their ``build_requires`` at all, and they are not fetched at all, they simply do not exist in the graph.

The ``conan lock create`` is very similar to a ``conan install`` but it is focused on capturing the lockfile. But the dependency resolution logic is the same one. If you want to include the ``build_requires`` in the lockfile, then, either the packages do not have pre-compiled binaries, or you need to provide a ``--build`` policy to define which packages will pull their transitive ``build_requires``.

**Comment by rconde01** [comment]
thanks that appears to work

**Comment by memsharded** [comment]
Good, then I will close this as a question, don't hesitate to re-open or create a new one if you have further questions.
