### ISSUE TITLE
[question] How does a package indicate that a specific install-folder must be specified in order for a consumer to build the package?

### ISSUE THREAD

**Issue by anderson-dev** [conan-io/conan#9330]
I can build my conan package locally without issue but it fails on linking in Windows Container using VSBuildTools 16. The same error occurs whether the container is run on Windows 10 or Windows Server 2019. I've used BeyondCompare to diff the error vs successful logs (attached) and determined only one difference during the msbuild processing (aside from root project folder locations). An additional parameter `/external:env:EXTERNAL_INCLUDE` is specified in the ClCompile section in the error log. It does not exist in the success log.

### Environment Details (include every applicable attribute)
  * Docker version: engine=20.10.7; client=20.10.7
  * Operating System+version: Docker: Windows Server Core ltsc2019
  * Compiler+version: MSBUILD 16.10.2+857e5a733
  * Conan version: 1.38.0
  * Python version: 3.9.2

### Steps to reproduce (Include if Applicable)
1. Open powershell
1. `git clone https://github.com/anderson-dev/debug-msvc-conan-package.git; cd debug-msvc-conan-package`
1. Ensure Docker Desktop is installed, switched to Windows Containers, and you may need to increase the max container size (in Windows 10) by adding the following key-value to either the daemon.json file or the UI Settings->Docker Engine section : `"storage-opts": [
    "size=120GB"
  ]`
1. `docker build -f docker/sdk/Dockerfile -t "mydocker/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019" docker/sdk`
1. `docker build -f docker/vsbuildtools/Dockerfile -t "mydocker/vsbuildtools:16-windowsservercore-ltsc2019" docker/vsbuildtools`
1. Wait about 20-40 min to build the previously mentioned vsbuildtools image
1. `make compile` (which just runs `conan install .;conan build .` but in the container)
1. Note the error: `LINK : fatal error LNK1181: cannot open input file 'libboost_contract.lib'`
1. `make clean` or `git clean -xdf`
1. `conan install .;conan build .`
1. Note the project builds successfully with no linker errors when run locally

### Logs (Executed commands with output) (Include/Attach if Applicable)

[log-error.txt](https://github.com/conan-io/conan/files/6887555/log-error.txt)
[log-success.txt](https://github.com/conan-io/conan/files/6887560/log-success.txt)

**Comment by anderson-dev** [comment]
I solved the issue by specifying the install-folder parameter for all conan commands to match where the Conan VS Extension set up the initial conanbuildinfo.props (i.e. conan install -if x64/Release/.conan .; conan build -if x64/Release/.conan .)

So now I have a question: if I have to specify the -if param for conan build, in the case that a pre-built binary is not available, would a package consumer not be able to simply conan install --build? How would they specify that my package needs to specify a specific install folder param in order to build from source?

**Comment by anderson-dev** [comment]
The solution seemed to be to copy the x64/Debug/.conan/conanbuildinfo.props file into the package source so msbuild has access to the paths contained within.

Hopefully, this workaround will be different once the VS Conan extension is updated for the new msbuild generator?...

**Comment by memsharded** [comment]
Hi @anderson-dev 

Sorry this issue was not responded when it was first submitted. 
Yes, at the moment the VS Conan extension is put on-hold, until we can resume work, most likely after 2.0, and it will be using the new ``MSBuildDeps`` integration.

I would like to comment to the new ``layout()`` and ``generate()`` methods, just in case you are not aware of it:

- The ``layout()`` method allows defining ``self.folders.generators``, to be the folder where the generated files will be created. The ``--output-folder`` will allow to define a base folder for all the build, output and generators.
- The ``generate()`` method allows customizing generators behaviors, creating new files, etc.

Both are already available in latest Conan 1.4X versions, if you want to try them too.

**Comment by anderson-dev** [comment]
Thanks. I'll start using vs_layout as suggested in #10748

**Comment by memsharded** [comment]
I'd also recommend having a look once 1.47 is released. It got important updates and fixes, and a template ``conan new hello/0.1 --template=msbuild_lib`` that can really help: https://github.com/conan-io/conan/pull/10760
