### ISSUE TITLE
[question] Leakage of package name, versions and ids in a publicly open Artifactory virtual repository 

### ISSUE THREAD

**Issue by db4** [conan-io/conan#9340]
I have a JFrog Artifactory Community Edition for C/C++ instance inside my LAN. The server has no public IP and is used only internally. Now browsing https://bincrafters.jfrog.io/ui/repos/tree/General/public-conan I see a tree of my private recipes/packages. Why???

**Comment by db4** [comment]
More info: the tree contains index.json files (fortunately only them) with `Source Path` attribute starting from `bintray-conan-cache...`. But I never uploaded those recipes/packages to bintray.

**Comment by memsharded** [comment]
No, Artifactory doesn't have any kind of backdor or anything like that. 
This should have been a leak from repos, or someone you gave access to the recipes?

Another possibility is that you set up a virtual and remote repositories in Artifactory, and didn't filter (exclude) your package queries. In that case, the package names (and only the packages names) might be requested to Bintray via the virtual repo. Do you have such a setup?

**Comment by memsharded** [comment]
Please @SSE4 @uilianries @solvingj, this is in the bincrafters repo, any suggestion?

**Comment by solvingj** [comment]
investigating, stand by.

**Comment by db4** [comment]
> Another possibility is that you set up a virtual and remote repositories in Artifactory, and didn't filter (exclude) your package queries.

Yes, I've set up a remote `bincrafters` repo on that server that I planned to use for faster downloads. But I actually do not use it. But I'm querying my internal packages from conancenter/bincrafters first during CI. Looks like these queries are not only cached but also made public? Maybe this leak is related to my conan client, not the server?

> In that case, the package names (and only the packages names) might be requested to Bintray via the virtual repo. Do you have such a setup?

Not only names, but package ids as well.

**Comment by db4** [comment]
@memsharded I was too emotional, sorry for that. Please change the issue title to something more appropriate  :)

**Comment by memsharded** [comment]
No prob @db4 I totally understand, I would also freak out! 😅 

Lets summarize status:
- This is not a general Artifactory server issue
- This is not a client leakage issue
- Exclusively the package names (and package-ids) are being leaked, but not a single bit of code, recipe, source code or binaries.
- The origin is a virtual repo which is open to the public, because virtual repos can somehow cache the requests they get, and it seems they map them to folder layouts.
- The virtual repo is one in the bincrafters org, the awesome bincrafters are already checking it.

I'll rename the issue 😄

**Comment by solvingj** [comment]
We believe we understand the issue to be the default (perhaps un-changeable) behavior of artifactory virtual repositories.  When it receives requests for package names it has not received before, it seems to create these placeholders. This seems extremely unsafe and insecure for any repository technology.  Needless to say, we were unaware of this behavior, and we will escalate with jfrog.

**Comment by SSE4** [comment]
update:
the issue was specific to the one server instance only - this remote has been disconnected and a script was run to clean up the cache repositories.

**Comment by memsharded** [comment]
Ok, this was not a Conan issue, and also not a general issue with Artifactory, but just some configuration of public facing virtual repositories in that specific bincrafters org. Closing this now, thanks all for the help!
