### ISSUE TITLE
[question] ERROR: Invalid setting 'aarch64' is not a valid 'settings.arch' value.

### ISSUE THREAD

**Issue by 88JC** [conan-io/conan#9344]
good day/night I want to ask if canon support aarch64? i want to install cpr in termux but got error ERROR: Invalid setting 'aarch64' is not a valid 'settings.arch' value.

**Comment by memsharded** [comment]
When you see this message, you should see also the list of allowed architectures. Something like:

```
    arch: [x86, x86_64, ppc32be, ppc32, ppc64le, ppc64, armv4, armv4i, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, asm.js, wasm, sh4le, e2k-v2, e2k-v3, e2k-v4, e2k-v5, e2k-v6, e2k-v7]
```

You also need to report the Conan version you are using, etc.

The ``aarch64`` seems to be mapped to the ``armv8`` one in Conan.

**Comment by madebr** [comment]
Note that armv9 is underway.
So `armv8` will no longer be synonymous with `aarch64`.
See https://www.arm.com/company/news/2021/03/arms-answer-to-the-future-of-ai-armv9-architecture

**Comment by AbrilRBS** [comment]
Thanks for the insight, closing as solved.
