### ISSUE TITLE
[feature] Different settings for required packages in conanfile

### ISSUE THREAD

**Issue by kpk-pl** [conan-io/conan#9345]
I recently started migrating my project to C++20 and while doing so found one dependency (namely 'icu', on conan-center-index) that does not compile with the new standard at all. I'm able to successfully compile my project by passing the command line option '-s icu:compiler.cppstd=17 -s compiler.cppstd=20' thus overriding the setting for the broken dependency. Link to https://github.com/conan-io/conan/issues/387

It would be really nice if I would be able to force the setting in the conanfile of my project instead of needing to remember to pass it every time I use conan via commandline

- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @kpk-pl 

We have had a not great experience with conanfile being able to define upstream options values. It makes things very complicated, and it has a ton of edge cases, for example it requires a lot of code to check for configuration conflicts. If we allowed such feature, now we would need to do not only settings propagation upstream, but also conflict checking and resolution for settings too. And that would only be a part of the edge cases. I am afraid that we will not provide this feature, it will most likely bring more pain than the one it aims to solve.

The proposed way to avoid repetition and potential errors in command line arguments is using profiles. Profiles is always the recommended way to work with Conan. Using the default auto-detected profile plus command line arguments should probably be used only in simple cases and testing. In your case I suggest having a cppstd20 profile and adding there the ``icu`` specifics constraints.

**Comment by kpk-pl** [comment]
@memsharded Thanks for the suggestion to use profiles. TBH this solves my case very well and I will stick with that profile.
One more thing if I may. Do you think it makes sense to try to update the icu's recipe in CCI to set max value for the compiler.cppstd to 17 ? Just curious.

**Comment by memsharded** [comment]
> One more thing if I may. Do you think it makes sense to try to update the icu's recipe in CCI to set max value for the compiler.cppstd to 17 ? Just curious.

Sure, do as many questions as you want 😄 

I don't know the constraints of the ICU library right now, but if you mean like defining (hardcoding) compiler.cppstd=17 in the icu package recipe directly, this is not possible either, the settings are always an externally user defined input, cannot be defaulted in recipes. If the request is that ICU could allow a cppstd=20, but current recipe is not allowing that, then definitely, it is more than possible that recipes in conan-center-index could be improved with fixes like this one, if this is the case.
