### ISSUE TITLE
[question] Will the lib hash change when only the the lib's depencies change?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9347]
For example

* lib name: libabc
* lib dependencies: zlib

Same profiles for installing libabc, with only one exception, one link to zlib as a shared lib, one as a static lib.
Will the hashes in installation path be different?

**Comment by memsharded** [comment]
Not by default. You can define it with different approaches:

- Change the ``default_package_id_mode`` to be something that includes the ``package_id``, so the zlib options will be included in the hash
- Define your ``package_id()`` method to consider it:
```python
 def package_id(self):
       self.info.options["zlib"].shared = self.info.full_options["zlib"].shared
```

This will become automatic in Conan 2.0 with the new package types and requirement traits approach.

**Comment by playgithub** [comment]
conan 2.0 seems perfect, when will conan 2.0 release?
