### ISSUE TITLE
os.version still not defining CMAKE_OSX_DEPLOYMENT_TARGET in Macos in CMakeToolchain

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9349]
I have `-s os.version=10.9` in my `conan create` command. I confirmed that everything worked fine when my conanfile.py had `tc.variables["CMAKE_OSX_DEPLOYMENT_TARGET"] = self.settings.os.version`, but when I removed that code, `-version-min` show in the build output. Just tried with the release of 1.39.0 to double check and it's still an issue.

_Originally posted by @ssrobins in https://github.com/conan-io/conan/issues/9282#issuecomment-888075330_

**Comment by franramirez688** [comment]
@memsharded @ssrobins 

I have performed this little test into my local conan repository. It looks like:

```python
def test_cmake_osx_deployment_target():
    profile = textwrap.dedent("""
        [settings]
        arch=x86_64
        arch_build=x86_64
        build_type=Release
        compiler=apple-clang
        compiler.libcxx=libc++
        compiler.version=12.0
        os=Macos
        os.version=10.9
        os_build=Macos
        """)
    client = TestClient(path_with_spaces=False)

    conanfile = GenConanfile().with_settings("os", "arch", "compiler", "build_type")\
        .with_generator("CMakeToolchain")
    client.save({"conanfile.py": conanfile,
                "macos": profile})
    client.run("install . -pr macos")
    toolchain = client.load("conan_toolchain.cmake")
    assert 'set(CMAKE_OSX_DEPLOYMENT_TARGET 10.9)' in toolchain
```

And it's passing ok.
Apart from that, I did not get to reproduce it using the latest conan version. It worked using either `-s os.version=10.9` in CLI or `os.version=10.9` in profile.

@ssrobins is it still failing from your side? Am I missing anything?

**Comment by ssrobins** [comment]
Still failing on my side.

I have a `conan_v2` branch that has the explicit `tc.variables["CMAKE_OSX_DEPLOYMENT_TARGET"] = self.settings.os.version` setting and a `conan_issue_9349` branch that doesn't:
https://github.com/ssrobins/conan-zlib/compare/conan_v2...conan_issue_9349

Here's the compilation output from `conan_issue_9349`, notice `-target` is `x86_64-apple-macos11.1`:
![image](https://user-images.githubusercontent.com/14830765/131288736-c3b3e2bd-1adf-4466-8bbe-1eb36a55501b.png)

Here's the equivalent output from `conan_v2`, notice `-target` is `x86_64-apple-macos10.9`, as I would expect:
![image](https://user-images.githubusercontent.com/14830765/131289301-c3bb7d00-53a7-4f81-8fe5-bc36fd38ee7c.png)

**Comment by franramirez688** [comment]
Thanks for your last report @ssrobins 
It helped me a lot to figure out what was going on 👏

**Comment by ssrobins** [comment]
I see that it's now building correctly with 1.40.0, thanks so much for the fix!
