### ISSUE TITLE
[bug] directories exists after `conan remove *`

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9357]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: msvc
  * Conan version: 1.39.0
  * Python version: 3.9.6

### Steps to reproduce (Include if Applicable)
```
$ conan remove *
# y for confirmation
# empty directories undeleted: `.conan\data\boost\1.76.0\_`, `.conan\data\bzip2\1.0.8\_`
```

### Other Infos
boost is installed as both shared and static, other settings and options are by default.
bzip is installed as static, other settings and options are by default.

**Comment by lasote** [comment]
Is it causing any conan error or just noticed the empty folders? I have observed it sometimes also, I think it is related to the Windows file system.

**Comment by playgithub** [comment]
> Is it causing any conan error or just noticed the empty folders?

no errors

**Comment by memsharded** [comment]
Conan cache is an internal implementation detail, it is not important if there are folders or not. Furthermore Conan 2.0 has completely change the cache folders, closing this ticket as outdated.
