### ISSUE TITLE
[bug] cmake generator does not support Visual Studio 17 2022

### ISSUE THREAD

**Issue by thorbenk** [conan-io/conan#9362]
When using the cmake generator with the new Visual Studio 17 2022 release, conan tries to call cmake with the following generator `Visual Studio UnknownVersion 17 Win64`.

This is because the new version needs to be added to the dictionary in `cmake_flags.py`. I'll open a pull request for this.

**Comment by lasote** [comment]
Thanks!

**Comment by SSE4** [comment]
thanks for letting us know. I've just installed Visual Studio 2022 preview and looking at it.
I believe there are more changes to be made:
- default profile, compiler detection (old and v2)
- new settings (`Visual Studio` and `msvc` compilers)
- cmake build helper (old and toolchain)
- msbuild build helper (old and toolchain)
- vcvars changes, if any
- cppstd and potentially other compiler/linker flags

I'll let you know once I have updates
