### ISSUE TITLE
[bug] CMake generator does not allow multiple namespaces for the exported library.

### ISSUE THREAD

**Issue by tcanabrava** [conan-io/conan#9364]
This affects at least Qt5, Qt6 and most of the libraries on the KDE Frameworks.
I'd assume more libraries use this but those are the ones I have to work on daily.

Qt5 exports `Qt::` and `Qt5::` namespaces, qt6 exports `Qt::` and `Qt6::` namespaces on their original find modules,
and it's important that we can rely on this for the generated find modules, so that code made for both Qt5 and Qt6 works.

I'm new to conan but I'm quite interested in improving it.

my proposal is to add a metadata on the recipe of such modules:

```
lass QtConan(ConanFile):
    generators = "pkg_config", "cmake_find_package", "cmake"
    name = "qt"
    cmake_find_package_namespaces = ["Qt", "Qt6"]
```

and when we run the cmake_find_package generator, we iterate trougth that list, and generate everything for all the cases.

conan-center related issue:
https://github.com/conan-io/conan-center-index/issues/6459

**Comment by lasote** [comment]
Hi @tcanabrava, thanks for reporting.
We are currently only evolving the new generators and toolchains, the `CMakeDeps` and `CMakeToolchain` will be the only generators for cmake in Conan 2.0 and we will start introducing them in the conan center index repository soon.

Here you can find the documentation:
https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html

We are currently using a properties mechanism to configure that kind of customization. For the namespace we have the [`cmake_target_name` property](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#properties), we might consider accepting a list of values in addition to only a string. Then the generator CMakeDeps would generate multiple namespaces according to that. Would you try to implement it?

**Comment by tcanabrava** [comment]
Yes I would.
give me a couple of days to familiarize with the codebase.

**Comment by SpaceIm** [comment]
It requires a lot of boilerplate, but you can provide multiple targets with different namespaces in `cmake_find_*` generators: https://github.com/conan-io/conan-center-index/issues/6459#issuecomment-893921257

Though, if `CMakeDeps` could avoid the flaws of `cmake_find_package*` generators regarding multiple namespaces, non-namespaced targets, multiple config files per recipe, variables casing issues and custom CMake variables, I would be happy 😄

**Comment by SpaceIm** [comment]
@czoido the new `cmake_target_name` logic fixes this issue I think.

**Comment by memsharded** [comment]
Yes, I think so, please @czoido confirm and close it if correct.

**Comment by czoido** [comment]
Hi @tcanabrava, I think that should be no problem to achieve that in the recipe with the [set_property](https://docs.conan.io/en/latest/conan_v2.html#new-properties-model-for-the-cpp-info-in-conan-2-0-generators) model por `CMakeDeps`.
You can set the namespace you want with `cmake_target_name` for example `Qt::` and then make an alias to the `Qt5/6::` target with the [cmake_target_aliases](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html?highlight=cmake_target_aliases#properties) property.
I'm closing this issue as that feature should be covered by this, but please feel free ro reopen if you have any more questions about this.
