### ISSUE TITLE
[bug] Premake generator does not use frameworks

### ISSUE THREAD

**Issue by sheepsteak** [conan-io/conan#9367]
### Environment Details (include every applicable attribute)
  * Operating System+version: MacOS
  * Compiler+version:
  * Conan version: 1.39.0
  * Python version:

### Steps to reproduce (Include if Applicable)

The `premake` generator does not take `frameworks` into account for MacOS. For Premake5, these need to be added as `links` with a `.framework` suffix: https://premake.github.io/docs/links#examples

**Comment by lasote** [comment]
Thanks for reporting. Could I ask how often do you use the premake generator? Are you using premake in your personal/company projects or is it an open-source one? We don't receive much feedback from that generator, I think the last change was about a year ago, so I'm curious. Thanks again!

**Comment by sheepsteak** [comment]
It was my first time using it yesterday. I'm just doing a hobby project (game in C with SDL2).

I'm happy to try and fix this if you want?
