### ISSUE TITLE
[feature+bug] conan.tools.gnu.autotools.Autotools can only configure in root source folder

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#9375]
Some times, configure scripts can be found in subdirectories.
Right now, `ConanFile.source_folder` is hard coded at
https://github.com/conan-io/conan/blob/916cb10b99ed92d319cd0719462708ee0501ecd4/conan/tools/gnu/autotools.py#L25

It would be VERY useful to be able to change this.

### Environment Details (include every applicable attribute)
  * Operating System+version: all
  * Compiler+version: all
  * Conan version: 1.39.0
  * Python version: 3.9.6

**Comment by lasote** [comment]
Sure, let's do it.

Same as the new CMake one:

```
    def configure(self, source_folder=None):
        ...

        source = self._conanfile.source_folder
        if source_folder:
            source = os.path.join(self._conanfile.source_folder, source_folder)
```

**Comment by madebr** [comment]
I'm not properly versed in Conan's layout model,
but should Autotools follow it too?

**Comment by lasote** [comment]
Yes, I meant that the `conan.tools.gnu.autotools.Autotools` should do something similar to the current CMake one.
