### ISSUE TITLE
Is it possible to specify different settings for requirements?

### ISSUE THREAD

**Issue by oranger34** [conan-io/conan#9377]
For example, my project requires poco and openssl. I need a Debug version of poco and a Release version of openssl. I put the settings build_type=Debug/Release in different profiles. It seems we can only use one profile(one setting) for all required packages. Is it possible to use different settings for diferent required packages?
Thanks!

**Comment by madebr** [comment]
Yes, this is possible.
You can override the build type of a dependency using the `-s RECIPE:build_type=Debug` syntax.

It is also possible to override settings in a profile.
See https://docs.conan.io/en/latest/reference/profiles.html#package-settings-and-env-vars

**Comment by franramirez688** [comment]
Thanks for your comment @madebr and sorry for my previous one @oranger34 because it could be confusing.
I should have checked more the documentation 😞 
Then, great! That should solve your problem.

**Comment by oranger34** [comment]
Yes, I tried this and it works!
`-s poco:build_type=Debug `
Thanks!
