### ISSUE TITLE
[bug] Bazel generator dosn't add system libs into the linkopts of cc_library

### ISSUE THREAD

**Issue by fanStefan** [conan-io/conan#9380]
Bazel generator dosn't add system libs into the linkopts of cc_library

### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora 34
  * Compiler+version: gcc 11.1.1
  * Conan version: 1.37.2
  * Python version: 3.9.5
  * Bazel version: 1.2.1

**Comment by tapia** [comment]
#9381  closes this
