### ISSUE TITLE
jenkins ci automation for myproject dependency graph

### ISSUE THREAD

**Issue by ramisetty1** [conan-io/conan#9385]
lockfile bundle: i created two lockfiles for 2 different applications. after that i bundle them then i got build order. which lockfile i have to pass in single build pipeline for common dependencies in two applications

**Comment by memsharded** [comment]
Hi @ramisetty1 

It is not very clear what is your issue. 

In the documentation it is described how to proceed with a bundle, specifically in https://docs.conan.io/en/latest/versioning/lockfiles/bundle.html#using-a-lockfile-bundle-to-build, it describes how to:

- Call ``build-order`` to get which packages need to be built by the pipeline: ``conan lock bundle build-order lock.bundle --json=build_order.json``
- How to call the build for each package, it evens presents some code to do this:

```python
# Get the build order
build_order = json.loads(open("build_order.json").read())

# Read the bundle
bundle = json.loads(open("lock.bundle").read())
bundle = bundle["lock_bundle"]
for level in build_order:  # iterate the build_order
    for ref in level:  # All refs in this level could be built in parallel
        # Now get the package_ids and lockfile information
        package_ids = bundle[ref]["package_id"]
        for pkg_id, info in package_ids.items():
            lockfiles = info["lockfiles"]
            lockfile = next(iter(sorted(lockfiles)))  # Get the first one, all should be valid to build same packag_id

            os.system("conan install {ref} --build={ref} --lockfile={lockfile} "
                      "--lockfile-out={lockfile}".format(ref=ref, lockfile=lockfile))
            os.system("conan lock bundle update lock.bundle")
```


It would be great if you could describe what is the issue with the above steps, if it is failing at some point, or what would be the problem. Thanks!

**Comment by ramisetty1** [comment]
im not getting the build order properly. i have different configurations for my dependencies and some of them have release configuration only. i created base lockfile for both my applications. after that i obtain new lockfile for release and debug configuration. some of the dependencies have only release configuration only. when i run conan lock create conanfile.py --lockfile=app1_base.lock --lockfile-out=app1.lock -s build_type=Debug for this command its showing some of the packages are missing because i dont have debug configuration for them. because of missing i got build order wrong how to solve this problem. please give details

**Comment by memsharded** [comment]
Sorry this was not followed up back then.

I am closing this as outdated.

Conan 2 has created many new tools, simplified a lot lockfiles, etc. There will be a new section ``CI tutorial`` soon on the new docs: https://github.com/conan-io/docs/pull/3799. 

Please check it and open new tickets as necessary, thanks for your feedback.
