### ISSUE TITLE
[bug] conan lock create --base accepts version ranges but subsequent conan lock created doesn't

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#9388]
In a Jenkinsfile we have to perform a 'buildall' CI verification ( https://docs.conan.io/en/latest/versioning/lockfiles/ci.html ) which checks that a package promotion won't break any other packages which depend on it, we must specify the 'universe' or 'distribution' within which to check for downstream breaks.

The workflow describes first creating a `--base` profile-independent lockfile, when using that lockfile as input to create a profile-specific lockfile, which is later used to check all packages in the build DAG against the newly built candidate package.

We found a distribution with a version range expression was supported in the conan lock create --base case, but not in subsequent conan lock create --profile cases.

Is that intentional?

### Environment Details (include every applicable attribute)
  * Operating System+version:  Windows 2012 Server
  * Compiler+version: vs2015_14_v140
  * Conan version: Conan version 1.36.0
  * Python version: Python 3.8.10

### Steps to reproduce (Include if Applicable)

```
conan lock create --reference conan-distribution-nx/[>=0.0.3]@PORT/stable --base
conan lock create --reference=conan-distribution-nx/[>=0.0.3]@PORT/stable --profile vs2015_14_v140_Debug
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

We have a `conan-distribution-nx/0.0.3@PORT/stable` meta-package which represented our 'universe'.  We'd like our CI for any other package promotion to be able to work against the latest version of that meta-package universe that becomes available in our buildall Artifactory repo.

So we tried using a version range:  `conan-distribution-nx/[>=0.0.3]@PORT/stable`.  It seemed to work fine in the `conan lock create --base` case, correctly finding the newest version `0.0.4` of the package:

```
[Pipeline] runConanCommand
16:15:40  [conan_rebuild_everything_from_source] $ cmd.exe /C "conan lock create "--reference=conan-distribution-nx/[>=0.0.3]@PORT/stable" "--build=*" --build=!bde-monolith/3.42.0.4@PORT/stable --build=!phql_lib/0.1@PORT/stable --lockfile-out=base.lock --base && exit %%ERRORLEVEL%%"
16:15:42  conan-distribution-nx/0.0.4@PORT/stable: Not found in local cache, looking in remotes...
16:15:42  conan-distribution-nx/0.0.4@PORT/stable: Trying with '03e8a51d-0a17-45c5-98f5-ed1002b77183'...
16:15:42  Downloading conanmanifest.txt
16:15:42  Downloading conanfile.py
16:15:42  conan-distribution-nx/0.0.4@PORT/stable: Downloaded recipe revision 6e8de3dda8e6658b73dbe3f799cf8b3b
```

but subsequently failed when we tried to create the profile-specific lockfile:

```
[Pipeline] runConanCommand
16:16:18  [conan_rebuild_everything_from_source] $ cmd.exe /C "conan lock create "--reference=conan-distribution-nx/[>=0.0.3]@PORT/stable" "--build=*" --build=!bde-monolith/3.42.0.4@PORT/stable --build=!phql_lib/0.1@PORT/stable --lockfile=base.lock --lockfile-out=per_profile_vs2015_14_v140_Debug.lock --profile vs2015_14_v140_Debug && exit %%ERRORLEVEL%%"
16:16:19  ERROR: Version ranges not allowed in 'conan-distribution-nx/[>=0.0.3]@PORT/stable' when using lockfiles
```

**Comment by memsharded** [comment]
Lockfiles fully revamped in Conan 2, closing this as outdated.
