### ISSUE TITLE
[question] CLion build can not find header

### ISSUE THREAD

**Issue by TuringZhu** [conan-io/conan#9394]
I download the conan example: https://github.com/lasote/clion-conan-consumer/

and I run the command:

```
conan install . -s build_type=Debug -if cmake-build-debug
```

it is ok 

but when I build with CLion, it tell me the following eror:

```
====================[ Build | example_png | Debug ]=============================
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --build /private/tmp/clion-conan-consumer/cmake-build-debug --target example_png -- -j 3
[ 50%] Building CXX object CMakeFiles/example_png.dir/example.cpp.o
/tmp/clion-conan-consumer/example.cpp:1:10: fatal error: 'png.h' file not found
#include "png.h"
         ^~~~~~~
1 error generated.
make[3]: *** [CMakeFiles/example_png.dir/example.cpp.o] Error 1
make[2]: *** [CMakeFiles/example_png.dir/all] Error 2
make[1]: *** [CMakeFiles/example_png.dir/rule] Error 2
make: *** [example_png] Error 2
```

![image](https://user-images.githubusercontent.com/13805470/128488402-66d2a2ea-bc62-48e1-995e-1debab171106.png)

I am a beginner for conan, so who can tell me what should I do for this error

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Hi @Turing-Chu 
Have you followed the CLion integration guide? https://docs.conan.io/en/latest/integrations/ide/clion.html
Asking only to be sure that you applied all the necessary steps 😁

**Comment by TuringZhu** [comment]
@franramirez688  thk for your help.

sometimes i run conan install it tell me the following error:

```
ERROR: apr/1.7.0: Invalid configuration: apr does not (yet) support apple-clang 12
[zxd:cmake-build-debug]$ conan install . -s build_type=Debug -if cmake-build-debug
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libstdc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

ERROR: apr/1.7.0: Invalid configuration: apr does not (yet) support apple-clang 12
[zxd:cmake-build-debug]$ 

```

**Comment by franramirez688** [comment]
@Turing-Chu you're welcome! 😁 

Yeah, that's quite normal when you're consuming any recipes. Each one sometimes has certain configurations which the recipes are not supposed to work for.
For instance, your dependency [apr/1.7.0](https://conan.io/center/apr?tab=recipe) has this piece of code:

```python
    def configure(self):
        if self.options.shared:
            del self.options.fPIC
        del self.settings.compiler.cppstd
        del self.settings.compiler.libcxx
        if (self.settings.compiler == "apple-clang" and
            tools.Version(self.settings.compiler.version) == "12" and
            self.version == "1.7.0"):
            raise ConanInvalidConfiguration("apr does not (yet) support apple-clang 12")
```

As you can see, the `configure` method checks all the invalid configurations and raises those errors.
If you want to go deeper with Conan, I strongly recommend you to see the [Training courses](https://docs.conan.io/en/latest/training_courses.html) 👍

**Comment by TuringZhu** [comment]
I solved this problem for png: reload cmakefile, but conan example poco depend on apr/1.7.0 and can not run
