### ISSUE TITLE
[question] Failed to create package

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9395]
## Env
OS: Windows
conan: 1.39.0
profile:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
shared=True
[build_requires]
[env]
```

## Problem
Following the doc
https://docs.conan.io/en/latest/creating_packages/getting_started.html#creating-and-testing-packages

```
$ conan create .
Exporting package recipe
hello/0.1: The stored package has not changed
hello/0.1: Exported revision: bba8f92abfeb2d792a934d62d408c28d
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
shared=True
[build_requires]
[env]

ERROR: \Path\To\mypkg\test_package\conanfile.py: option 'shared' doesn't exist
Possible options are []
```

**Comment by memsharded** [comment]
Your conanfile.py didn't declare a ``shared`` option.

For some reason, you are not correctly following the instructions you linked. If you read the recipe it will contain:

```python
options = {"shared": [True, False]}
    default_options = {"shared": False}
```
It seems you removed it or something.

**Comment by playgithub** [comment]
> Your conanfile.py didn't declare a `shared` option.
> 
> For some reason, you are not correctly following the instructions you linked. If you read the recipe it will contain:
> 
> ```python
> options = {"shared": [True, False]}
>     default_options = {"shared": False}
> ```
> 
> It seems you removed it or something.

I've follow the doc strictly, it's `test_package/conanfile.py` which doesn't have
```
options = {"shared": [True, False]}
default_options = {"shared": False}
```

After adding the option, it works, but why does a executable must have an option `shared`?

**Comment by memsharded** [comment]
You added ``shared`` to your profile, that applies to the test_package/conanfile.py.

Options need to be prefixed with the package you want to target, in this case: ``hello:shared=True``, otherwise, they will apply to the downstream consumer, in this case the test_package/conanfile.py one, that doesn't define this option and then it fails as expected.

**Comment by playgithub** [comment]
> You added `shared` to your profile, that applies to the test_package/conanfile.py.
> 
> Options need to be prefixed with the package you want to target, in this case: `hello:shared=True`, otherwise, they will apply to the downstream consumer, in this case the test_package/conanfile.py one, that doesn't define this option and then it fails as expected.

If downstream doesn't have an option in upstream, is it better to ignore it?

**Comment by memsharded** [comment]
> If downstream doesn't have an option in upstream, is it better to ignore it?

No, that could be hiding potential problems, like typos, missing options, etc. The policy is better to raise an error to indicate a problem there.

**Comment by playgithub** [comment]
> > If downstream doesn't have an option in upstream, is it better to ignore it?
> 
> No, that could be hiding potential problems, like typos, missing options, etc. The policy is better to raise an error to indicate a problem there.

For a recipe, it knows best what it should be. In this case,  option `shared` doesn't make sense for a recipe of an executable. Generally a recipe can accept help from outside, for example default value in this case, but the outside should not enforce a recipe to be less perfect.

**Comment by memsharded** [comment]
> In this case, option shared doesn't make sense for a recipe of an executable.

If you are packaging an executable, you don't need the ``shared`` option. But the package created with ``conan new`` (following the docs), is not an executable, it is a library, and it makes sense. You are again confusing the ``shared`` option of the package ``conanfile.py`` with the executable that lives in the ``test_package/conanfile.py`` that **is not part of the package**, it is a different thing, an executable. This should have the ``shared`` option, and in fact, when created with ``conan new hello/0.1 -t`` doesn't have the option.

**Comment by playgithub** [comment]
In this case it doesn't make sense for `test_package/conanfile.py` to have an option `shared`.
