### ISSUE TITLE
[feature] Add version() for git scm

### ISSUE THREAD

**Issue by dariusarnold** [conan-io/conan#9396]
My proposal is to add the method version() to tools.Git. Calling this method would return the Major.Minor.Patch of the found git executable (maybe as a named tuple). These can be used to customize the git commands which are used. As an example, partial cloning (cloning only some files/directories from a repo to save time) is available since Git 2.19.0. If the executable is new enough, partial cloning could be used. Otherwise the conanfile.py would fallback to cloning the while repository.
It is possible to do this manually by running "git --version" using git.run() and parsing the output, but this could be said about many of the methods provided by tools.Git.

Is there any interest in this?

- [-] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, I understand the use case, I wouldn't oppose to such a method, sounds relatively low risk, and could help users, specifically those that need to deal with quite older git versions.

**Comment by ghost** [comment]
I'm interested in taking this on, can sb assign me or @dariusarnold  will work on it?

**Comment by dariusarnold** [comment]
You are free to take it. I just suggested it without a concrete plan to start working on it.

For feature parity maybe it would be useful to implement it for svn as well, but I dont know much about it.

**Comment by memsharded** [comment]
> For feature parity maybe it would be useful to implement it for svn as well, but I dont know much about it.

Would be good, but not strictly necessary, only if SVN users demand it. So don't feel obligated if you don't have svn or knowledge about it.

**Comment by aniketh-varma** [comment]
Hi, I would like to work on this issue. Since this is my first open-source contribution, I would be grateful if you can also guide me on doing the same.

**Comment by memsharded** [comment]
@Alzamer had it assigned first. Can you please @Alzamer confirm that you are working on it?

**Comment by ghost** [comment]
@memsharded @aniketh-varma Yes, I'm wrapping my head around it - I have been quite busy lately, hence I've just started

**Comment by memsharded** [comment]
@aniketh-varma please have a look at other "good first issue" in the repo.

**Comment by aniketh-varma** [comment]
> @aniketh-varma please have a look at other "good first issue" in the repo.

Sure!

**Comment by ghost** [comment]
@aniketh-varma Sorry for the confusion, but I won't be able to end this task in a reasonable period of time - take it if you still interested

**Comment by abrousseau001** [comment]
@aniketh-varma are you still looking into this one? I see scm.py has a method in the base class to handle this. The SVN class already does something for a version method. It shouldn't be too difficult to implement the Git class version method. If you are not working on this still, I can go ahead and take care of this.

**Comment by aniketh-varma** [comment]
Sure @abrousseau001, you can go ahead!

**Comment by abrousseau001** [comment]
Appreciate that @aniketh-varma. @memsharded can you please assign this to me?

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/10114
