### ISSUE TITLE
Conan info command with profiles

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#940]
Conan info command has to manage profiles as install does.

**Comment by piponazo** [comment]
I was going to report an issue about this. We really need this feature for our Continuous Integration system.

**Comment by piponazo** [comment]
Do you have an estimation for the 0.20 release ?

**Comment by memsharded** [comment]
Sure, check the milestone date https://github.com/conan-io/conan/milestone/13

 :) :) :)
