### ISSUE TITLE
[feature] Ignore eol while conan upload 

### ISSUE THREAD

**Issue by steffenroeber** [conan-io/conan#9404]
We use Jenkins to create and upload Conan packages on different platforms (Win/Linux).
If in a Jenkins pipe line the recipe is checkout, git changes the line endings depending on the system settings,
If now the recipe is uploaded with different eol on different machines, the former is always outdated.
May it be possible to check the eol while upload and ignore it optionally?

**Comment by memsharded** [comment]
This might be a duplicate or very related to:

- https://github.com/conan-io/conan/issues/8324
- https://github.com/conan-io/conan/issues/8391

In short: Conan will not modify or handle line endings. This can have from annoying behaviors (like changing revisions or not changing revisions when expected) to buggy behaviors (not uploading something that really changed and needed to change with a line ending). The source control systems have mechanisms to do this, and we don't want to duplicate (surely in a worse implementation) what they have already done.
