### ISSUE TITLE
[question] Sharing ~/.conan/data among Docker containers

### ISSUE THREAD

**Issue by Radrik5** [conan-io/conan#9409]
We're going to use Docker containers to provide stable build environments for C++ projects. Third party dependencies are pre-built and packaged into Conan packages. I'd like to share Conan cache among containers in order not to download packages each time new container is started. But I don't want to share Conan settings (profiles, remotes, etc.) as it's a part of build environment.

Is it possible/safe to share `~/.conan/data` among multiple containers having different Conan settings in `~/.conan`?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by benet96** [comment]
Perhaps you could set ~/.conan directory with `-v ~/.conan:~/.conan` in docker parameters. Conan will only check ~/.conan as local cache of remote query and local build. As long as your package is not sensitive with OS distro because docker will probably cause distro-invovled incompatible.

**Comment by czoido** [comment]
Hi @Radrik5,

Conan cache is not concurrent so is not recommended to share the cache between multiple instances (by the way, we are working in a new cache for 2.0 that is concurrent). You may wan to have a look at the downloads cache feature that will prevent downloading again the same packages: https://docs.conan.io/en/latest/configuration/download_cache.html
Also, regarding the cache concurrency and CI, you can have a look here: https://docs.conan.io/en/latest/mastering/custom_cache.html
Hope this helps.

**Comment by Radrik5** [comment]
Hi @czoido,

Thanks for the links!

Concurrency limitations described in https://docs.conan.io/en/latest/mastering/custom_cache.html#concurrency are perfectly acceptable for dev boxes. I don't expect concurrent operations on a regular basis and it's fine if they fail in some rare odd cases.

Download cache is not enough because it won't have binaries built locally with `--build missing`. We are going to build `debug` locally to save disk space on the server and have source code for debugging. It would be nice to share such build artifacts as well.

I would like to share `~/.conan/data` with `-v ~/.conan/data:~/.conan/data` but I don't know if it's somehow coupled with settings in `~/.conan` which could be different in different build environments.

Do you know if it's safe to share `~/.conan/data` without settings (putting aside concurrency concerns)?

**Comment by memsharded** [comment]
A note @czoido, concurrency will only be limited to same computer concurrency. All the synchronization mechanisms that we can use (with a reasonable approach), only works for the same machine (semaphores, mutexes, file locking.... only works at the machine level, not inter machine). So anything that means that the same cache is shared among different containers will not be concurrent safe.

Assuming there is perfect and exclusive sequential access to the cache, in the current cache, yes, there could also be issues (different machines continuoesly overwriting the same package with different revisions, as the cache can only store 1 revision). With the new 2.0 cache, that uses revisions, this might not happen. But the concurrency hypothesis must hold in practice, and I guess it is unlikely to always hold (for CI, almost impossible, for developer boxes, like a developer is not going to switch to another container to test something while the other container is building other thing in the same shared cache...)

**Comment by Radrik5** [comment]
@memsharded thanks for the answer!

Regarding concurrency, Conan uses fasteners which uses file system locks which work across containers on the same machine because they share the same Linux kernel and access the same files via bind mounts. So at least in current implementation such locks should work. Do you mean that I shouldn't rely on this because it's an implementation detail and may change in the future?

**Comment by memsharded** [comment]
Yes, we are exploring other synchronization mechanisms besides fasteners for 2.0. We might keep with fasteners, but this is unknown atm.
