### ISSUE TITLE
[feature] MacOs version shall be a part of package ID

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#9410]
I am getting such errors, when local MacOs machine version does not match to conan CI MacOs version.
To Avoid such situations, it would be good to make MacOs version a part of package ID.
 
[146/2516] Linking CXX executable qtbase/lib/moc
ld: warning: object file (/Users/rr-admin/.conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib/libz.a(compress.o)) was built for newer macOS version (11.0) than being linked (10.14)
ld: warning: object file (/Users/rr-admin/.conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib/libz.a(uncompr.o)) was built for newer macOS version (11.0) than being linked (10.14)
ld: warning: object file (/Users/rr-admin/.conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib/libz.a(deflate.o)) was built for newer macOS version (11.0) than being linked (10.14)
ld: warning: object file (/Users/rr-admin/.conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib/libz.a(inflate.o)) was built for newer macOS version (11.0) than being linked (10.14)
ld: warning: object file (/Users/rr-admin/.conan/data/pcre2/10.37/_/_/package/2d8245d819a6b7543095d62df5d99244060071ba/lib/libpcre2-16.a(pcre2_compile.c.o)) was built for newer macOS version (11.0) than being linked (10.14)
ld: warning: object file (/Users/rr-admin/.conan/data/pcre2/10.37/_/_/package/2d8245d819a6b7543095d62df5d99244060071ba/lib/libpcre2-16.a(pcre2_config.c.o)) was built for newer macOS version (11.0) than being linked (10.14)
ld: warning: object file (/Users/rr-admin/.conan/data/pcre2/10.37/_/_/package/2d8245d819a6b7543095d62df5d99244060071ba/lib/libpcre2-16.a(pcre2_error.c.o)) was built for newer macOS version (11.0) than being linked (10.14)
ld: warning: object file (/Users/rr-admin/.conan/data/pcre2/10.37/_/_/package/2d8245d819a6b7543095d62df5d99244060071ba/lib/libpcre2-16.a(pcre2_match_data.c.o)) was built for newer macOS version (11.0) than being linked (10.14)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
They are already part of the package_id:

```
Macos:
            version: [None, "10.6", "10.7", "10.8", "10.9", "10.10", "10.11", "10.12", "10.13", "10.14", "10.15", "11.0", "13.0"]
            sdk: [None, "macosx"]
            subsystem: [None, catalyst]
```

You only need to define their values in your ``profile`` file, to be taken in the ``package_id`` automatically and generate different package-IDs for different versions.

**Comment by lasote** [comment]
I assume by the "thumbs up" that the issue can be close. Thanks!
