### ISSUE TITLE
Conan remove by package usage frequency

### ISSUE THREAD

**Issue by ChaotX** [conan-io/conan#9413]
I maintain CI agents. On each machine conan cache size grows really fast. I have no clue which packages is used recently, but deleting all the cache wastes a bunch of bandwidth resource, burns out ssd's and lengthen build times.
I'd really like to have a feature to delete packages not used since X days.
More advanced implementation could allow to set a cache size that is automatically deletes the least used packages as @w3sip raised this idea in https://github.com/conan-io/conan/issues/1233#issuecomment-695213196_

**Comment by lasote** [comment]
EDIT:
Conan 2.0 will probably support that, take a look at [this](https://github.com/conan-io/conan/issues/7727) issue. I will close this as a duplicated.

In the meantime, it could be done with a [hook](https://docs.conan.io/en/latest/reference/hooks.html). You could maintain a table of package references with a timestamp and update it on a `post_download_package` call. Then in a separate scheduled process call `conan remove zzz/yyy -p xxxx` for the references not used in a long time or the criteria you need.
