### ISSUE TITLE
[question] CMakeDeps + CmakeToolchain collision with package find modules

### ISSUE THREAD

**Issue by kenfred** [conan-io/conan#9414]
Is there a way to tell `CMakeDeps` to not generate a config file for certain dependencies from the consumer side? Also is there a way to make the `CMakeToolchain` add the package paths to the module path, like `cmake_paths` generator did?

I'm using the package for `pybind11`, which ships its own `pybind11-config.cmake`, which contains useful macros. I'm also seeing a file by the same name generated via the `CMakeDeps`, of course without the macros. The toolchain only appends `CMAKE_BINARY_DIR` to the module path, so the generated one is found when I need to find the one within the package.

More generally:

CMake's `find_package` searches the module path to find `FindFoo.cmake` or `Foo-config.cmake`. In the context of conan (assuming I want to only find conan packages, not system-installed libs), there are a few places such files would normally be found:
- Within the CMakes installation's modules folder 
- Within a conan package folder in the cache. This is the case if:
  - The library itself provides its own `Foo-config.cmake`. Mature libraries based on CMake are advised to provide this.
  - The recipe for `Foo` exports a `FindFoo.cmake`.
- Within `CMAKE_BINARY_DIR` when `CMakeDeps` generator is used

When using `CMakeDeps` + `CMakeToolchain`, only the last one is effectively possible. Other generators, like `cmake_paths` add package folders to the module path, but this is no the case with `CMakeDeps` + `CMakeToolchain`. However, conan intends to sunset `cmake_paths` and other cmake generators in favor of `CMakeDeps`. 

The config files within the package should take precedent because it has been specialized for the particular package and provides necessary macros. To enable this, I believe `CMakeToolchain` needs to add the package folders to the module path, like `cmake_paths` does, and `CMakeDeps` needs a way to be prevented from generating config files for individual packages.

You could consider this partly a bug in the recipe for `Foo`. The recipe should set `self.cpp_info.set_property("skip_deps_file", True)` if it is providing its own config file. However, it would be super convenient to affect this from the consumer side so I don't have to fork the recipe. Even after that, I have to do some manual steps to get the `Foo` package folder in the module path.

Less critically, I'd also expect that the default find-modules in the cmake installation should take precedent over the generated config files. `CMakeToolchain` has defeated this by setting `set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)`. I believe I can override this in my `generate` method, but I'm surprised the default is to take the generated config files over the handcrafted ones.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Hi,

> Is there a way to tell CMakeDeps to not generate a config file for certain dependencies from the consumer side? 

You could remove the config file after calling `CMakeDeps(self).generate()` in your `generate(self)` method.
Otherwise from the dependency recipe it should adjust `self.cpp_info.set_property("skip_deps_file", True)`

> I'm using the package for pybind11, which ships its own pybind11-config.cmake, which contains useful macros.

This could be tricky depending on the macros, but the recipe could package only the macros in a different file and then adjust `.set_property("cmake_build_modules", [os.path.join("path", "to", "pybind11-macros.cmake")])`. 
Declaring the `cmake_build_modules` property will cause the `CMakeDeps` to include the file automatically when finding the `config` file generated by Conan.

> The recipe should set self.cpp_info.set_property("skip_deps_file", True) if it is providing its own config file. 

No, we think that the `config` file to be used should be always the one generated by Conan, based on the solid information of the package manager based on the dependency tree not in any code that the library author might introduce there. If the recipe declares some useful macros they can be exposed to be included as I commented but we really think that Conan has to manage the config files.

FYI the properties allowed by the CMakeDeps:

https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#properties

**Comment by kenfred** [comment]
Thanks @lasote!

> No, we think that the config file to be used should be always the one generated by Conan, based on the solid information of the package manager based on the dependency tree not in any code that the library author might introduce there.

I'd like to explore this further. I'd agree that the config file generated by `CMakeDeps` has an advantage in knowing _where_ the dependencies are located and potentially useful info about transitive dependency locations. However, I'd argue that the strongest config file is the one provided by the library itself, which lives in the package itself and where the library author knew exactly what to export/import. CMake [recommends ](https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-to-create-a-ProjectConfig.cmake-file)that all libraries export a config file. The next strongest is a config file provided by a recipe for that library, since the recipe author has to know details about the library anyway to fill out `package_info`. In both cases, authors can provide library-specific details that the generator can't.

It is problematic that cmake best-practice strongly recommends authors provide their own config file yet conan (which is defacto cmake-focused) circumvents this practice with a more general replacement. Although I see benefit in the `CMakeDeps` generated one, I don't think it's acceptable to indiscriminately prevent the use of the specialized config files provided by the authors. At least, there should be ways to control the generator from the consumer side to elect one or the other.

> Declaring the cmake_build_modules property will cause the CMakeDeps to include the file automatically when finding the config file generated by Conan.
...
> Otherwise from the dependency recipe it should adjust self.cpp_info.set_property("skip_deps_file", True)

Given that `pybind11` is a very well-done cmake library already and its current recipe in conan center is completely adequate, it is a design smell that I would need to fork one or the other in order to consume. I agree, it makes sense that the `pybind11` recipe knows whether or not it exports is own config file and could indicate that, but it seems wrong to force the consumer one way or another. What is generated should be controlled at the consumer level.

> You could remove the config file after calling CMakeDeps(self).generate() in your generate(self) method.
Otherwise from the dependency recipe it should adjust self.cpp_info.set_property("skip_deps_file", True)

I have tried it both ways. Unfortunately these workarounds don't work. In either case, I still have the issue that the path to the config file is not in the prefix path, like it would be if I were using `conan_paths` generator. I could try and force the `CMAKE_PREFIX_PATH` variable in the toolchain from the `generate` method, but there is no way to handle mutli-configuration conan installs from the `generate` method: the toolchain gets regenerated with each individual `conan install`, so I don't have a way to do something like:

```python
tc.variables.debug["CMAKE_PREFIX_PATH"] = <path to debug package>
tc.variables.release["CMAKE_PREFIX_PATH"] = <path to release package>
```

because `conan install` doesn't know both `<path to debug package>` and `<path to release package>` in any single `conan install` invocation. `CMakeDeps` is supposed to be the way forward to handle cmake, including multi-configuration builds. Any suggestions on how to handle this?

**Comment by lasote** [comment]
This is a bit dirty but you could try to include the `XXX-Release-data.cmake` and `XXX-Debug-data.cmake` files generated by `CMakeDeps`, they contain a variable `XXX_PACKAGE_FOLDER_RELEASE` and `XXX_PACKAGE_FOLDER_DEBUG` that points to the package folders. Then adjust the  `CMAKE_PREFIX_PATH` depending on the current build type. Just an idea... I don't know if it could work.

**Comment by lasote** [comment]
Hi, just tell you that we know this is a demanded use case and we are working on it. Still thinking though.

**Comment by lasote** [comment]
Sorry for closing it. Bad click.

**Comment by kenfred** [comment]
> Hi, just tell you that we know this is a demanded use case and we are working on it. Still thinking though.

Ok! I think there are two feature requests here:
- Ability to have the toolchain file point to multiple packages for different build configurations, including setting prefix or module paths. This one is sorely needed in my case.
- Ability to tell `CMakeDeps` generator (or maybe any generator) to include/exclude some dependencies and not others. I can get around this by overriding the `generate` function and manually deleting generated files, but that's pretty bad experience.

**Comment by lasote** [comment]
About the first point, I think that is not doable, the `CMAKE_PREFIX_PATH` or `CMAKE_MODULE_PATH` doesn't support (Afaik) multiconfiguration. One of the benefits of the generated config files by the `CMakeDeps` is that the targets are built adding properties with generator expressions and when you "conan install" different configurations, all the files containing data are included in the targets, but with the official cmake files there is no way to do that.

**Comment by kenfred** [comment]
I would expect that you could conditionally set `CMAKE_PREFIX_PATH` based on `BUILD_TYPE` within cmake. I'll have to try it. 

If that doesn't work, here is one clumsy idea:
Normally cmake has one `foo-config.cmake` that points to one `foo-targets.cmake`, which conditionally points to either`foo-targets-debug.cmake` or `foo-targets-release.cmake`.

On our case, we could still generate `foo-config.cmake` in the build dir as `CMakeDeps` normally does, but have that `foo-config.cmake` conditionally points to the `foo-config.cmake` from package A or package B, which would each point directly to their target. This would have to be a special kind of `CMakeDeps` generator that knows the package ships with its own find-module or config file. It can point to the package's `foo-config.cmake` either with a direct `include` or by calling `find_package` again with the search path narrowly set to the package path.

On a related note, it seems like there is a clear architectural issue here with the `generate` method. All methods of the `conanfile` will use the configuration (defined by `build_type`, `settings`, `options`, etc.) to make conditional choices. The `generate` method breaks with this pattern: it makes you define all possible build configurations within the method itself (defaulting to only `debug` and `release`) and does not obey the `settings` and `options` like other methods in any useful way.

The current design relies on the expectation that the generated toolchain is the same across multiple invocations of `conan install`. This basically only allows you to do debug vs release conditionals. It's difficult or impossible to do any conditional modifications to the toolchain file based on settings/options. The use case I laid out is just one example of this limitation. 

If `CMakeDeps` and `CMakeToolchain` generators are the future, how can we be okay with them being incompatible with the existing paradigm of `settings` and `options`?

The only way I can think to remedy this would be allow the toolchain generator to be above multiple calls to `conan install`. I realize there is currently no mechanism for a generator to function across multiple installs, except for maybe in the `workspaces` paradigm. However, I think this is what you'd need to do to honor `settings`/`options`.

**Comment by jwillikers** [comment]
@kenfred I'm running into your same issue with `CMakeToolchain` and having packages apply settings through the toolchain. It seems like the only way around this for now is to add a bunch of additional settings and use a shared `python_requires` toolchain that correctly implements all the compiler / CMake flags for the various settings because the current CMakeToolchain is extremely minimal. This doesn't work well, of course, for packages you don't control.

**Comment by kenfred** [comment]
@jwillikers Yes, I'm finding the new paradigm of having packages themselves dictate consumer generator behavior to be problematic. Of course, it is certainly necessary for a package to describe its build products and other cpp info. However, it is unfortunate that I have to roll a package based on changing generator behavior, specific consumer requirements, or potentially because of introduction of new generators. Packages should be "open for extension, but closed for modification". Or at least, we need a way to override at the consumer level.

From a software design perspective, one way to accomplish this would be to use something akin to the visitor pattern to extend the functionality of a package from outside its implementation. These companion "adapters" would have the same maintenance cost as the current paradigm, but allow for more flexible extensibility at the consumer level.

**Comment by jwillikers** [comment]
@kenfred Yeah, it does sound like the visitor pattern would be a good paradigm for improving extensibility. A good test is probably whether support for Google Sanitizers can be used across a project and its dependencies without having to reach into dependencies' recipes.

**Comment by harsszegi** [comment]
@lasote @memsharded 
Hey guys, any news on this?

If it really the case currently with Conan 2.x that without cmake_paths, it is impossible to use the stock find_package.cmake files generated by the package maintainer by the CMake scripts as CMakeDeps explicitly overrules with the ones generated by Conan? Or has it changed?

**Comment by memsharded** [comment]
Hi @kenfred 

> If it really the case currently with Conan 2.x that without cmake_paths, it is impossible to use the stock find_package.cmake files generated by the package maintainer by the CMake scripts as CMakeDeps explicitly overrules with the ones generated by Conan? Or has it changed?

It is perfectly possible, and we have explicitly documented this in an example: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html

End user always has control, using ``CMakeDeps.set_property()`` can even override which packages generate or not ``xxx-config.cmake`` files.

**Comment by memsharded** [comment]
This issue reads pretty outdated referring to Conan 1, and I think Conan 2 features would solve the above.
I am closing as solved, if there are pending issues, it would be better to reformulate an update ticket against latest Conan 2.X. Thanks!
