### ISSUE TITLE
[bug] base source folder in "conan build" command

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#9415]
With a project with external sources:

- conanfile.py

I want to create a subfolder "tmp" and build everything locally:

```
mkdir tmp && cd tmp
conan install .. -if=install
conan source .. -if=install
conan build .. -if=install
```

When running the "conan build", the base source folder is the root project and not the "tmp" folder, so it is needed to run:

`conan build .. -if=install -sf=.`

Might be a bug or might be breaking behavior (look tests), anyway, take a look at it for Conan 2.0

**Comment by memsharded** [comment]
Solved with ``layout()``
