### ISSUE TITLE
[Exclude third party dependency from conan]. I am using aws-sdk-cpp/1.8.130 which imports curl with itself but I want to use curl which is available on my system.] 

### ISSUE THREAD

**Issue by lalit-g-deepr** [conan-io/conan#9418]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Renari** [comment]
You can make your own `curl/system` package and override the curl that is being used by `aws-sdk-cpp/1.8.130`.

**Comment by memsharded** [comment]
Hi  @lalit-g-deepr 

To detail a bit more on @Renari response (thanks!). First, it is important to highlight is that there is no possible "magic" replacement of Conan dependencies with system ones. This is not doable, if it was easy to do it, then dependency management for C/C++ would be trivial and not require a package manager.

Said that, there could be different approaches to this:

- You can fork the aws-sdk-cpp recipe, modify it to not depend on the curl Conan package, and create your own package. Host that package in your own server (ArtifactoryCE is completely free). Many Conan users do forks of ConanCenter recipes to adapt them to their very custom needs.
- You can override that curl dependency creating your own ``curl/system`` package recipe as @Renari suggested. You would still need to create that recipe and either host in your own server, or ``conan export`` it to the cache when you are going to need it. To use it, on your consumer, when you do ``requires = "aws-...."``, you add the override to ``curl/system``. I would strongly recommend not to use the binaries for ``aws-sdk-cpp`` package from ConanCenter, but rebuild them (in theory, that override should force it, but just in case, beware that you will need to recompile your own binary for ``aws-sdk-cpp`` and any other that transitively depends on curl). You can also host your own binaries in your own server to avoid needed to rebuild from source again and again.

I would recommend the second approach if you have more dependencies to curl, but maybe the first one could be easier if you only have that dependency to curl, via aws-sdk-cpp.

**Comment by lalit-g-deepr** [comment]
Thanks @memsharded I would try these approach, seems promising.
