### ISSUE TITLE
[bug] Can't set SUDO_ASKPASS environment variable in conan profile 

### ISSUE THREAD

**Issue by Renari** [conan-io/conan#9419]
### Environment Details (include every applicable attribute)
  * Operating System+version: Mint 20
  * Compiler+version: gcc 10
  * Conan version: 1.39.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
Set `SUDO_ASKPASS` in your profile, example: 
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-10
CXX=/usr/bin/g++-10
SUDO_ASKPASS=/home/arimil/.local/bin/pass-pls
```

Attempt to install a package a package that installs system requirements, for example sdl2 from bincrafters in a terminal without tty.
https://bincrafters.jfrog.io/ui/repos/tree/General/conan%2Fbincrafters%2Fsdl2%2F2.0.16

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
sdl2/2.0.16@bincrafters/stable: Applying build-requirement: pkgconf/1.7.3
Package already installed: libgbm-dev
dpkg-query: no packages found matching libjack-dev
Running: sudo -A apt-get update
sudo: no askpass program specified, try setting SUDO_ASKPASS
```

**Comment by lasote** [comment]
The environment variables specified in the profile are not available in all the methods of the recipe, probably only in the `build()` method and some others to interfere only the necessary. You won't be able to use the profile for that.

**Comment by lasote** [comment]
We might consider using `[env]` in profiles at Conan 2.0 to set the global environment while we introduced `[buildenv]` and `[runenv]` as new specific variables for building or runtime.

**Comment by memsharded** [comment]
New system-package-manager, that deprecates the previous one (removed in 2.0) uses the Conan ``conf`` mechanism: https://docs.conan.io/en/latest/reference/conanfile/tools/system/package_manager.html. Please update and report against the new approach if necessary.
