### ISSUE TITLE
How to export definitions to consumer?

### ISSUE THREAD

**Issue by Kidsunbo** [conan-io/conan#9424]
I have a header only library and I would like to write a recipe for it.

It's a web server and can be configured by `ENABLE_SSL` to handler the https request. I would like to make it configurable with `options` so the consumer can configure it in their `conanfile.txt`.

I know how to use options to manage the dependency but I have no idea how to export the definition so that the code wrapped by this definition can be compiled.

 I have checked many recipes for header only libraries but no one does this. Is it possible? And how could I do it if it is.

**Comment by Kidsunbo** [comment]
Oh god, cpp_info is for this purpose. Thank you guys for this wonderful tool.

**Comment by memsharded** [comment]
Hi  @Kidsunbo 

yes, exactly that, I guess you saw that doing something like ``self.cpp_info.defines = ["xxxx"]`` in your ``package_info()`` of your recipe will propagate that definition to consumers of the package.

You are very welcome, happy to hear that you like Conan! 😃
