### ISSUE TITLE
[bug] self.folders.generators does not work with virtualrunenv

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#9425]
I tried the new layout feature to set `self.folders.generators`
```
    def layout(self):
        self.folders.generators = os.path.join(self.folders.build, "generators")
```

* it works as expected with `CMakeDeps`: files are generated in **generators** directory
* it DOES NOT WORK with `virtualrunenv`: files are still generated in the root build directory

### Environment Details (include every applicable attribute)
  * Operating System+version: windows 10
  * Compiler+version: msvc 16.
  * Conan version: 1.39.0
  * Python version: 3.9

**Comment by memsharded** [comment]
Hi @boussaffawalid 

Please check the warning note in the docs: https://docs.conan.io/en/latest/reference/conanfile/tools/layout.html

The legacy generators will not fully support the new ``layout()``.

Then, please try with the new ``VirtualRunEnv`` generator: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html
