### ISSUE TITLE
[question] How to use customed settings.yml I already `conan config install`?

### ISSUE THREAD

**Issue by benet96** [conan-io/conan#9432]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Hello, 
Here, by default, my default ~/.conan/settings.yml didn't have libcxx = libc++ in gcc, but I will provide the tool chain from other place.  What I need is to add a custom settings.yml like 
```
compiler:
  gcc:
    version: [ "8.3.0", "830" ]
    libcxx: [ libstdc++, libstdc++11, libc++ ]
```
to make sure my profile could pass conan check with ~/.conan/settings.yml. I follow the doc to `conan config install my_settings.yml` it, but it still 
```
ERROR: Invalid setting 'libc++' is not a valid 'settings.compiler.libcxx' value.
Possible values are ['libstdc++', 'libstdc++11']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```
I already install the config, but it seems never enabled? I try to delete default settings.yml,
```
~/.conan/my_config/settings.yml
0: {'type': 'dir', 'uri': '~/my_config', 'verify_ssl': True, 'args': None, 'source_folder': '~/my_config, 'target_folder': 'my_config'}
```

 but it appears again. How could I enable my settings.yml? Docs said `conan config install settings.yml` will *Override* default config, but it's not?

**Comment by memsharded** [comment]
Hi @benet96 

Could you post the output of your ``conan config install`` command? There is something there I don't know if it is a typo or what. The command for a single file should be ``conan config install settings.yml``. The name of the file must be ``settings.yml``, as you post later, but initially you typed ``my_settings.yml``. Could you clarify?

**Comment by memsharded** [comment]
A side observation: beware that some of the Conan build helpers, like the CMakeToolchain could have some logic implicit in it:

```python
        elif compiler == "clang":
            if libcxx == "libc++":
                lib = "-stdlib=libc++"
            elif libcxx == "libstdc++" or libcxx == "libstdc++11":
                lib = "-stdlib=libstdc++"
            # FIXME, something to do with the other values? Android c++_shared?
```
Which might be conditioned to the compiler used, and not work out of the box for your unusual combination. Please check it too.

**Comment by benet96** [comment]
Thank you, @memsharded 
Oops, I found my mistake. The first time I type
```
conan config install settings.yml
```
And it hints me conan has copy settings.yml to ~/.conan/. However, I find there's nothing changed in my ~/.conan/settings.yml by default, I thought there might be some protection behavior, so I continuously try some my_settings.yml or --type dir my_config where contains my_settings.yml.
And thanks to you to remind me it must be *settings.yml
```
conan config install --type file settings.yml
```
And it works, just I ignore --type.
Wait... it seems like --type is an extra assurance to remind user what they do. Because in python it's really convenient to check **type** by os.path.isdir or os.path.isfile or some urllib method to check a git url or ftp url?

**Comment by memsharded** [comment]
``--type file`` might be automatically deduced yes, here is an excerpt of the code:
```python
 elif os.path.isdir(uri):
                config.type = "dir"
            elif os.path.isfile(uri):
                config.type = "file"
```
It should be there for extra check and some backward compatibility, as the file support was added later to the feature, and to avoid fallbacks to try to interpret as git or http if you want to ensure a file.

Then, did it work? Can we close the feature now?

**Comment by benet96** [comment]
> A side observation: beware that some of the Conan build helpers, like the CMakeToolchain could have some logic implicit in it:
> 
> ```python
>         elif compiler == "clang":
>             if libcxx == "libc++":
>                 lib = "-stdlib=libc++"
>             elif libcxx == "libstdc++" or libcxx == "libstdc++11":
>                 lib = "-stdlib=libstdc++"
>             # FIXME, something to do with the other values? Android c++_shared?
> ```
> 
> Which might be conditioned to the compiler used, and not work out of the box for your unusual combination. Please check it too.

Perhaps it might need more constraints if we hope compiler' arguments is configured as simple as settings like just compiler.libcxx=libstdc++. Copmilers could take more than just one but a series of options, like clang has a list to find candidate GCC toolchain installed, and make a decision to add which path of stdc++ headers to include in compatible with which libstc++.so to link. If it's gcc with libc++, we have add -nostdxxx and -isystem path/to/clang/c++/headers. But `-isystem` word and CMake `SYSTEM` is rare to see in conan project.

**Comment by benet96** [comment]
> `--type file` might be automatically deduced yes, here is an excerpt of the code:
> 
> ```python
>  elif os.path.isdir(uri):
>                 config.type = "dir"
>             elif os.path.isfile(uri):
>                 config.type = "file"
> ```
> 
> It should be there for extra check and some backward compatibility, as the file support was added later to the feature, and to avoid fallbacks to try to interpret as git or http if you want to ensure a file.
> 
> Then, did it work? Can we close the feature now?

Yes, cannot agree more. Safe check is always necessary. It did work, I will close, and really appreciate for your help, Thank you. @memsharded

**Comment by memsharded** [comment]
> Perhaps it might need more constraints if we hope compiler' arguments is configured as simple as settings like just compiler.libcxx=libstdc++. Copmilers could take more than just one but a series of options, like clang has a list to find candidate GCC toolchain installed, and make a decision to add which path of stdc++ headers to include in compatible with which libstc++.so to link. If it's gcc with libc++, we have add -nostdxxx and -isystem path/to/clang/c++/headers. But -isystem word and CMake SYSTEM is rare to see in conan project.

If you are going to have custom logic for your builds, I'd recommend to consider the extensibility of the CMakeToolchain: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#extending-and-customizing-cmaketoolchain. It is quite powerful, you can create your logic, put it in a ``python_requires`` and use it through your recipes. The CMakeToolchain is still experimental, but it is quickly stabilizing.

**Comment by benet96** [comment]
> > Perhaps it might need more constraints if we hope compiler' arguments is configured as simple as settings like just compiler.libcxx=libstdc++. Copmilers could take more than just one but a series of options, like clang has a list to find candidate GCC toolchain installed, and make a decision to add which path of stdc++ headers to include in compatible with which libstc++.so to link. If it's gcc with libc++, we have add -nostdxxx and -isystem path/to/clang/c++/headers. But -isystem word and CMake SYSTEM is rare to see in conan project.
> 
> If you are going to have custom logic for your builds, I'd recommend to consider the extensibility of the CMakeToolchain: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#extending-and-customizing-cmaketoolchain. It is quite powerful, you can create your logic, put it in a `python_requires` and use it through your recipes. The CMakeToolchain is still experimental, but it is quickly stabilizing.

Yes, CMakeToolchain is really cute... (To write some [RayTracer project](https://zhuanlan.zhihu.com/p/123419161)...)  Because I have already seen how to build toolchain in Bazel by starlark and, I have to say that's really hurt... And I love CMakeToolchain again...
