### ISSUE TITLE
[feature] A possibility to manipulate .dmg from Conan

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan#9433]
> Only a DMG is provided for direct download for macOS because it is required for Catalina and newer. In most cases it will be easier to use the Android SDK manager to install the NDK.

https://developer.android.com/ndk/downloads

https://github.com/conan-io/conan-center-index/issues/6873#issuecomment-899437316

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
As commented in https://github.com/conan-io/conan-center-index/issues/6873, we certainly don't want to add yet another third party dependency for very specific use cases like this one. If it is possible to somehow implement this functionality without much complexity and without relying in some third parties, then, a Conan tool could help, I wouldn't oppose. But if not, the burden of maintenance, support, performance, etc.... probably it is not worth it.

Let's see if they revert that and stop distributing only .dmg for that.

**Comment by dmn-star** [comment]
We had luck this time the zip still exists.
