### ISSUE TITLE
[question] How to support both debug & release on Windows

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9439]
When `conan install` `conanfile.txt` as below
```
[requires]
zlib/1.2.11
[generators]
cmake_multi
```
Will both debug and release versions of `zlib` installed?
If not and only one build type will be installed, how will `cmake_multi` work when lacking of one build type?

**Comment by dornbirndevelops** [comment]
Hello @playgithub!
I'm by far no conan expert.
But the way I understood the `_multi` generators, is that you invoke the install command twice.
One time with the build_type set to Debug, and a second time with the build_type set to Release.

In a later stage, you can then decide which build you want to do. The compiled binary should then be linked against the appropriate binary that matches your build type.

**Comment by playgithub** [comment]
> One time with the build_type set to Debug, and a second time with the build_type set to Release.

so the generator `cmake_multi` results in a template `conanbuildinfo.cmake`, right?

I think a better way is like this
```json
{
    "requires": ["zlib/1.2.11"],
    "settings":
    {
        "build_types": ["debug", "release"]
    },
    "generators": ["cmake"]
}
```

BTW, I think Linux's native package manager is very clear,  easy to install, and overridable by installing a lib in `/usr/local` manually. `conan`'s way to mimic the manual installations is intuitive and flexible, and I don't mind the work to write a recipe.
But I still feel it not clear enough.
