### ISSUE TITLE
[bug] *conan user -p ...* does not authenticate user

### ISSUE THREAD

**Issue by snailcatcher** [conan-io/conan#9442]
### Environment Details (include every applicable attribute)
  docker-container: conanio/gcc10

### Steps to reproduce (Include if Applicable)
1. start conatiner with shell (*docker run -it conanio/gcc10 /bin/bash*)
2. *conan remote clean*
3. *conan remote add repo https://your-private-repository True*
4. *conan user -r repo -p password username*
5. *conan download my-package/1.0.0@user/channel*
6. Then a message follows: "Please enter a password for "username" account:"

This should not happen because I already pass the password in *conan user -p ...*
So it is not possible for me to use conan in any CI usecase with a private repository.

**Edit:**
I played around a bit and found something very interesting. If I cancel *conan download my-package/1.0.0@user/channel* with CTRL+C and then run it again conan will not ask for the password again, but gets me a 404:

```sh
Downloading conanmanifest.txt completed [0.45k]
Downloading conanfile.py completed [1.35k]
Downloading conan_sources.tgz completed [2.96k]
Decompressing conan_sources.tgz completed [0.00k]
my-package/1.0.0@user/channel: Getting the complete package list from 'my-package/1.0.0@user/channel#0'...
ERROR: 404: Not Found. [Remote: repo]
```

**Comment by czoido** [comment]
Hi @snailcatcher,
I'm not able to reproduce the issue. Please, could you give more details on which type of server and repository are you using like conan server, artifactory (local or virtual?)..
Thanks a lot!

**Comment by snailcatcher** [comment]
Hi @czoido,
You could be right. I also updated my repository.
I use Nexus Repository OSS (*docker run -p 80:8081 -d sonatype/nexus3*).
It is possible that the update from 3.32.0 to 3.33.1 broke the conan part because they do changes to it. [release notes](https://help.sonatype.com/repomanager3/release-notes)

How should I/we proceed with this?

**Comment by czoido** [comment]
Then I think we can't do much more on our side and this is something you should report to nexus.
I have already tested this with Artifactory Community Edition for C/C++ and is working fine: (`docker run --name artifactory -d -p 8081:8081 -p 8082:8082 docker.bintray.io/jfrog/artifactory-cpp-ce:latest`) and also with the basic conan_server that comes with Conan installation.

**Comment by memsharded** [comment]
It seems this issue can be closed as responded, it is not a Conan client issue, and should be reported to the server implementer repo. Thanks.

**Comment by snailcatcher** [comment]
Okay, thank you for your efforts.
