### ISSUE TITLE
[bug] find_package: missing or wrongly named variables

### ISSUE THREAD

**Issue by igxactly** [conan-io/conan#9444]
### Environment Details
  * Conan version: 1.39.0

### Steps to reproduce

* combining
  - `conan install`
    - `conanfile.txt`: `boost/1.69.0` + (`cmake_paths`, `cmake_find_package`)
  - `cmake -GNinja -B . -S .. -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake`
    - `link_directories(${Boost_LIBRARY_DIRS})`
    - `target_link_libraries(...... boost_stacktrace_addr2line)`
* --> leads to `cannot find -lboost_stacktrace_addr2line`

### Problem

Conan cmake generator is missing some `find_package()` variables or setting it in wrong name. CMake `Find${something}` is designed to give result variables including `..._LIBRARY_DIRS` and so on.

The list of variables I found missing:
- `*_LIBRARY_DIRS` (only `*_LIB_DIRS exists`)
- `*_<COMPONENT>_LIBRARY` (only `*_<COMPONENT>_LIBS` exists)

Espcially, `_LIBRARY_DIRS` is useful when using CMake `link_directories()`, for legacy library linking env compatibility. (yes, this is my case)

For example, [FindBoost offers](https://cmake.org/cmake/help/latest/module/FindBoost.html#result-variables) `Boost_LIBRARY_DIRS`, `Boost_INCLUDE_DIRS`, `Boost_LIBRARY_DIRS`, `Boost_<COMPONENT>_LIBRARY`(e.g. `Boost_system_LIBRARY`) variables. Conan sets `Boost_INCLUDE_DIRS`, `Boost_LIB_DIRS` but not `Boost_LIBRARY_DIRS`. Same things happen to other parts like `Boost_<COMPONENT>_LIBRARY`, having `Boost_<COMPONENT>_LIBS` instead.

### Related code lines

https://github.com/conan-io/conan/blob/42beaf2a402157f23f11ba5ba8b15030b51c2251/conans/client/generators/cmake_find_package_common.py#L6-L27

https://github.com/conan-io/conan/blob/42beaf2a402157f23f11ba5ba8b15030b51c2251/conans/client/generators/cmake_find_package.py#L97-L116

https://github.com/conan-io/conan/blob/42beaf2a402157f23f11ba5ba8b15030b51c2251/conans/client/generators/cmake_find_package_multi.py#L124-L139

### attachment: CMake FindBoost official documentation

https://cmake.org/cmake/help/latest/module/FindBoost.html#result-variables

```
This module defines the following variables:

Boost_FOUND
    True if headers and requested libraries were found.
Boost_INCLUDE_DIRS
    Boost include directories.
Boost_LIBRARY_DIRS
    Link directories for Boost libraries.
Boost_LIBRARIES
    Boost component libraries to be linked.
Boost_<COMPONENT>_FOUND
    True if component <COMPONENT> was found (<COMPONENT> name is upper-case).
Boost_<COMPONENT>_LIBRARY
    Libraries to link for component <COMPONENT> (may include target_link_libraries() debug/optimized keywords).
```

### attachment: part of generated FindBoost

```
set(Boost_COMPILE_DEFINITIONS "BOOST_STACKTRACE_ADDR2LINE_LOCATION=\"/usr/bin/addr2line\""
                        "BOOST_STACKTRACE_USE_ADDR2LINE"
                        "BOOST_STACKTRACE_USE_BACKTRACE"
                        "BOOST_STACKTRACE_USE_NOOP")
set(Boost_COMPILE_OPTIONS_LIST "" "")
set(Boost_COMPILE_OPTIONS_C "")
set(Boost_COMPILE_OPTIONS_CXX "")
set(Boost_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(Boost_LIBRARIES "") # Will be filled later

# <<<<<<<< `Boost_LIBRARY_DIRS` missing!

set(Boost_LIBS "") # Same as Boost_LIBRARIES
set(Boost_SYSTEM_LIBS dl rt pthread)
set(Boost_FRAMEWORK_DIRS )
set(Boost_FRAMEWORKS )
set(Boost_FRAMEWORKS_FOUND "") # Will be filled later
set(Boost_BUILD_MODULES_PATHS )
```

**Comment by SpaceIm** [comment]
see https://github.com/conan-io/conan/issues/7691

**Comment by cleeland** [comment]
In conan 1.53.1 (latest I have available to me), `conan_find_package.py` is still missing cache variables defined by cmake's FindBoost module.  Specifically, variables like

*  ``Boost_<COMPONENT>_LIBRARY_DEBUG``
  Component ``<COMPONENT>`` library debug variant.

* ``Boost_<COMPONENT>_LIBRARY_RELEASE``
  Component ``<COMPONENT>`` library release variant.

**Comment by memsharded** [comment]
Closing this as outdated, using legacy ``cmake_find_package`` removed from Conan 2 time ago, superseded in Conan 1.X b ythe new ones time ago.
