### ISSUE TITLE
[feature] Tool `check_min_cppstd`: modify behavior/interface in new namespace?

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#9447]
Taken from [this PR](https://github.com/conan-io/docs/pull/2191#), and others in the past.

It is true that whenever we use this tool in conan-center-index, it is prepended by a guard:

```python
    if self.settings.compiler.get_safe("cppstd"):
        tools.check_min_cppstd(self, 14)
```

Why? Because usually, the library files (build system files) contain a statement to set the proper C++ standard version required to build. So, we need to skip the check when `compiler.cppstd` is not explicit in the profile because the tool checks against the default C++ standard for that compiler version... and it would raise.

Some alternatives:
1. Can Conan promote to set always explicitly the `compiler.cppstd` value? This is not suitable for a real scenario where there are different libraries and each one of them requires a different C++ standard. It will force the user to override the value of `compiler.cppstd` for some libraries (`-s fmt:compiler.cppstd=17 -s ctre:compiler.cppstd=20`).
2. Can we patch all the libraries to remove the typical `set(CXX_STANDARD_REQUIRED ...)` and (in CCI) iterate more profiles with different values for `compiler.cppstd`? Probably not something we can afford.

---

(Opinion) What else can we do? Probably CCI will always need that condition, while the check as it is now is more sound. Maybe we just need to add a boolean argument:

```python
def check_min_cppstd(conanfile, cppstd_required, consider_default=False):
    if not conanfile.settings.compiler.cppstd and not consider_default:
       return
    ...
```

For CCI and simplicity, we would want default `consider_default=False`. More controlled scenarios might want a different default.

**Comment by lasote** [comment]
> Can Conan promote to set always explicitly the compiler.cppstd value? 

Yes, we are going that way, with the default cppstd of the compiler (autodetected in profile) For the libraries that require another version the c3i library should play with the `validate` to get the min/[max](https://github.com/conan-io/conan/issues/11080) to be applied. I would say c3i library already does similar tasks, right? I'm closing this, feel free to comment/reopen

**Comment by jgsogo** [comment]
No, c3i doesn't touch anything related to `compiler.cppstd`. This was just about moving those two lines that appear in too many recipes into the tool.
