### ISSUE TITLE
[question] Can I use binaries via `build_requirements()` in `set_version()`?

### ISSUE THREAD

**Issue by AshleighAdams** [conan-io/conan#9449]
I have a binary tool that I have packaged up into a conan package, the tool calculates a version from the git history and would like to consume it in `set_version()`. As it stands though, `set_version()` occurs before `build_requirements()` which, to me, seems like the incorrect order. The recipe and repository being versioned live in the same repository for context.

Code example of what I'm trying to accomplish:

```py
from conans import ConanFile
import subprocess

class Package(ConanFile):
	name = "pkg"
	settings = "os", "arch"
	url = "auto"
	scm = {
		"type": "git",
		"url": "auto",
		"revision": "auto",
		"submodule": "recursive",
	}

	def build_requirements(self):
		self.build_requires("verlite/[>=1 <2]")

	def _run(cmd):
		return subprocess.run(cmd, stdout=subprocess.PIPE).stdout.decode('utf-8').strip()

	def set_version():
		self.version = _run("verlite")
```

The only way I've been able to work around this is to commit the tool binary to the repo, and invoke it via a relative path.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
No, this is not possible. The ``set_version()`` only runs at "export" time, this is much earlier than the requirements or build_requires are evaluated. This is not a missing feature, it is impossible to implement, as it would be a chicken and egg problem (many users rely on the current version to define the requirements and build_requires).

What I would recommend for this case is a double stage process. You can have a ``conanfile_tools.txt`` somewhere, that define requirements to some tools you need installed. Then you do a ``conan install`` with that file and use some of the virtualenv generators (maybe modern ``VirtualRunEnv`` recommended, still experimental, but it is the future). Activate the environment, then run all the Conan commands you need inside that environment, that will find the ``verlite`` executable in it. It requires 2 steps, but at least it is possible to handle the tool inside a Conan package, which can be convenient.

**Comment by AshleighAdams** [comment]
The problem with that approach is we often have many projects at the same time, which could possibly use different versions of the tool. It also introduces an additional human step that can go wrong. I think for now the best workaround for us is to directly add the tool to the repository.

Thanks for your reply!

**Comment by memsharded** [comment]
By the way, have you considered using ``python_requires`` for this? The ``python_requires``, as they are part of the recipe, the Python code, they are evaluated much earlier. It is true that they are not good for packaging binaries, but in case the tool would be pure Python code, it could be a possibility.

**Comment by AshleighAdams** [comment]
Yeah, that's actually what we're already doing in some other repositories, but with a, if I'm being nice, much simpler algorithm. I did also try adding (build) requirements in there in the hopes that the docs were wrong, but they weren't!
