### ISSUE TITLE
[question] Conan python: can't open file "No such file or directory" error when installing or packaging a library on Windows 10

### ISSUE THREAD

**Issue by chenyiliang** [conan-io/conan#9450]
<img width="935" alt="b" src="https://user-images.githubusercontent.com/6761729/130101483-97e26ae9-3f2d-4d21-ad90-637a657095bd.png">
The python open file path  is wrong，how to fix it？

**Comment by memsharded** [comment]
Hi @chenyiliang 

The information you provide is insufficient. Please provide:
- The commands necessary to reproduce the issue.
- The code or conanfile.py (or project/files) to reproduce the issue.
- The full output, as text, not as an image.

Also, the best is to provide the so called "minimal reproducible example", something as small as possible, not a large project.

**Comment by chenyiliang** [comment]
> Hi @chenyiliang
> 
> The information you provide is insufficient. Please provide:
> 
> * The commands necessary to reproduce the issue.
> * The code or conanfile.py (or project/files) to reproduce the issue.
> * The full output, as text, not as an image.
> 
> Also, the best is to provide the so called "minimal reproducible example", something as small as possible, not a large project.

**commands:** conan install .. --profile=mingw64 --build=missing
**os:** windows 10
**mingw64 profile:**
[settings]
os_build=Windows
os=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10.3
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
build_type=Release

[env]
MSYS_ROOT=C:\msys64
MSYS_BIN=C:\msys64\usr\bin
CONAN_CMAKE_GENERATOR="MinGW Makefiles"
CONAN_USE_ALWAYS_SHORT_PATHS=1
CXX=C:\msys64\mingw64\bin\g++.exe
CC=C:\msys64\mingw64\bin\gcc.exe
CONAN_BASH_PATH=C:\msys64\usr\bin\bash.exe
PATH=[C:\msys64\usr\bin, C:\msys64\mingw64\bin]

**minimal reproducible example conanfile.txt:** 

[requires]
pkgconf/1.7.4

[generators]
cmake

**Comment by dmn-star** [comment]
Here is already an Issue https://github.com/conan-io/conan-center-index/issues/6767

__

This happens quite often when you use unix tools on Windows and forget to adjust the paths (mixing / and  \  ).

**Comment by chenyiliang** [comment]
> Here is already an Issue [conan-io/conan-center-index#6767](https://github.com/conan-io/conan-center-index/issues/6767)
> 
> __
> 
> This happens quite often when you use unix tools on Windows and forget to adjust the paths (mixing / and \ ).

I have read related issues but not find the solution, how to adjust the paths?

**Comment by dmn-star** [comment]
The same problem https://github.com/conan-io/conan-center-index/issues/6767#issuecomment-907825364 but easy to fix in your setup. Put C:\msys64\mingw64\bin first.
...
PATH=[ C:\msys64\mingw64\bin, C:\msys64\usr\bin]

**Comment by memsharded** [comment]
Closing this ticket as staled, please create new tickets as necessary for any further question or issue, thanks for the feedback.
