### ISSUE TITLE
[question] How can I specify default dependency options?

### ISSUE THREAD

**Issue by jgcodes2020** [conan-io/conan#9451]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
---
My package (suppose I call it `A`) depends on a package `B`.

Package `B` provides options that disable specific parts of the library. This is super useful because I don't end up pulling in parts I don't need. Can I specify default options for the dependency, or should I not do this in case someone else needs those components further down the dependency tree?

**Comment by memsharded** [comment]
Yes, you can put ``default_options = {"libb:optioninlibb": "value"}`` in the ``liba`` conanfile.
