### ISSUE TITLE
[question] Add optional `reference` parameter for `conan info`?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#9453]
I'm trying to use `conan info` to topologically sort Conan packages by their dependencies in my build scripts. `conan info <path to conanfile.py>` works well until it hits a recipe without version containing something like `if tools.Version(self.version) < "1.9":`. Maybe adding an optional `reference` parameter to `conan info` makes sense?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, actually, the new UI for Conan 2.0 (that ``conan lock`` already implements the style), has specific arguments ``--name``, ``--version`` to be able to pass this information.

What are you exactly trying to achieve? Why needing to call ``info`` on conan packages that you don't control (it seems those are ConanCenter packages, that typically do not define the version in the recipe, but on command line?)

**Comment by db4** [comment]
> What are you exactly trying to achieve? Why needing to call `info` on conan packages that you don't control (it seems those are ConanCenter packages, that typically do not define the version in the recipe, but on command line?)

I have a private git repo with a bunch of internal recipes (with a folder structure very similar to CCI). On each push to the repo CI builds packages for the changed recipes. Since they depend on each other, the order in which they are built is important . Also, I only want to build the packages whose recipes have been changed (and several recipes may be changed in one commit). So CI first runs `conan info` for every recipe, combines all dependencies into one graph, topologically sorts it, checks if the necessary binaries are available, and uses Conan Package Tools to build the missing ones.

This may be not very optimal. When `conan info` fails, I retry with several iterations of `conan export`/`conan info` to build the full dependency graph. Maybe there is a better way? Unfortunately, CCI Jenkins scripts are closed, so it's impossible to borrow some ideas from there...

**Comment by memsharded** [comment]
> I have a private git repo with a bunch of internal recipes (with a folder structure very similar to CCI). On each push to the repo CI builds packages for the changed recipes. Since they depend on each other, the order in which they are built is important . Also, I only want to build the packages whose recipes have been changed (and several recipes may be changed in one commit). So CI first runs conan info for every recipe, combines all dependencies into one graph, topologically sorts it, checks if the necessary binaries are available, and uses Conan Package Tools to build the missing ones.

Have you considered doing a single ``conan info`` over a conanfile.txt that just declares the set of dependencies (first level, the transitive ones will be automatically added. It might require some (I think small) amount of manual updates to that ``conanfile.txt``, but it might be worth, as it can simplify a lot the whole process. 

A different issue is if you want to do that for different versions of the same package, and your dependency graph is not really a dependency graph (couldn't be used in a single consumer), then the problem in general is more challenging. We propose the "products" approach with lockfiles, and the lockfile bundles can provide topologically sorted build orders for combinations of products in which different versions of the same package are involved. Maybe something worth checking if you still havent. Still need the concept of "products".

In any case, the feature request of having ``--version`` in ``conan info`` makes sense, and for sure will be implemented in Conan 2.0. I don't know if we will manage for 1.X.

**Comment by db4** [comment]
> > I have a private git repo with a bunch of internal recipes (with a folder structure very similar to CCI). On each push to the repo CI builds packages for the changed recipes. Since they depend on each other, the order in which they are built is important . Also, I only want to build the packages whose recipes have been changed (and several recipes may be changed in one commit). So CI first runs conan info for every recipe, combines all dependencies into one graph, topologically sorts it, checks if the necessary binaries are available, and uses Conan Package Tools to build the missing ones.
> 
> Have you considered doing a single `conan info` over a conanfile.txt that just declares the set of dependencies (first level, the transitive ones will be automatically added. It might require some (I think small) amount of manual updates to that `conanfile.txt`, but it might be worth, as it can simplify a lot the whole process.

But then I need to `conan export` all recipes first during CI, right? And if done in the wrong order, some `conan export` commands will fail.

> A different issue is if you want to do that for different versions of the same package, and your dependency graph is not really a dependency graph (couldn't be used in a single consumer), then the problem in general is more challenging. We propose the "products" approach with lockfiles, and the lockfile bundles can provide topologically sorted build orders for combinations of products in which different versions of the same package are involved. Maybe something worth checking if you still havent. Still need the concept of "products".

Do you mean https://docs.conan.io/en/latest/versioning/lockfiles/bundle.html?

Again, lockfiles require all recipes to be exported first. Looks like what I actually need is a list of direct dependencies for a given recipe (dependencies names are enough, no full reference resolution is necessary). Can it be obtained somehow (via Conan API?)  having only recipe's `conanfile.py`, reference, and the list of options/settings?

**Comment by memsharded** [comment]
> But then I need to conan export all recipes first during CI, right? And if done in the wrong order, some conan export commands will fail.

Except python_requires that are needed to evaluate recipes, ``conan export`` do not analyze or compute the dependency graph, so it can be done in any random order, for all recipes in your repo.

**Comment by db4** [comment]
> Except python_requires that are needed to evaluate recipes, `conan export` do not analyze or compute the dependency graph, so it can be done in any random order, for all recipes in your repo.

I see, thanks a lot. Since additional parameters are already planned for Conan 2.0, I'm closing the issue.
