### ISSUE TITLE
Rename "SConscript_conan" into "conanbuildinfo.scons"

### ISSUE THREAD

**Issue by dmitry-zakablukov** [conan-io/conan#946]
Good day.

File with build info for SCons should be named "conanbuildinfo.scons" instead of "SConscript_conan", because other names are:
- conanbuildinfo.cmake
- conanbuildinfo.props
- conanbuildinfo.txt

Best regards, Dmitry.

**Comment by memsharded** [comment]
Hi Dmitry,

This was disscussed during https://github.com/conan-io/conan/pull/765, and the final decission was to keep the SCons way. Regarding cmake, props, and txt, those names are fine, but SCons calls by default SConscript those files, so it made sense. 

Please @pepsiman, @bdbaddog, any feedback?

**Comment by pepsiman** [comment]
The filename isn't important, but changing it now would break my deployment.

**Comment by dmitry-zakablukov** [comment]
@memsharded , okey, I don't insist on renaming, just a suggestion.

**Comment by memsharded** [comment]
Sure, thanks very much for it :) I did exactly the same suggestion when I read the initial proposal, then got the feedback of the contributor, and also accepted it. Breaking things as @pepsiman deployment (and could be others) should be avoided when possible, so unless @pepsiman is willing to change it and fix their deployment, I think it is better to leave it as is.

**Comment by pepsiman** [comment]
The current naming allows the scons syntax highlighting for vim to work.
http://www.vim.org/scripts/script.php?script_id=1709
`au BufNewFile,BufRead SCons* set filetype=scons `

**Comment by dmitry-zakablukov** [comment]
@pepsiman , I suppose the following does the same:
```
au BufNewFile,BufRead *.scons set filetype=scons
```

**Comment by pepsiman** [comment]
Yes, but it was nice that it just worked.
