### ISSUE TITLE
[feature] MSVC C++ 14.29

### ISSUE THREAD

**Issue by arttet** [conan-io/conan#9461]
Could you please address a new version of MSVC.
[Visual Studio 2019 version 16.11 Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes)
```
MSVC C++ 14.29.16.10 SxS Toolset updated to match VS 2019 v16.10.4. MSVC Toolset Version for this update is 14.29.30040.0/19.29.30040.0.
```
I think we need to add a piece of https://github.com/conan-io/conan/pull/9370

- [+] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @arttet 

If I understood correctly, this is not the same or a piece of #9370, because that is totally focused on 2022 support, but this would be another feature? Do you mean adding it to the ``msvc`` compiler? Or something else is needed if you are still using the ``Visual Studio`` compiler?

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/9370 implemented this, will be in 1.40

**Comment by arttet** [comment]
Hi @memsharded 

Sorry for my late response. It is good news.
However, I thought the problem was related to the latest version of `MSVC`. But I still have trouble when I use the compiler option as `msvc`. Should I create a new issue?

**Comment by memsharded** [comment]
> However, I thought the problem was related to the latest version of MSVC. But I still have trouble when I use the compiler option as msvc. Should I create a new issue?

Yes, sure, please create a new issue for this. Also, note that ``msvc`` compiler will only be supported in the new build system integrations: https://docs.conan.io/en/latest/reference/conanfile/tools.html, it is not expected that it will be supported in the other, legacy ones.
