### ISSUE TITLE
[bug] Adding PATH to your conan profile prevents build requirements from adding to path

### ISSUE THREAD

**Issue by Renari** [conan-io/conan#9466]
### Environment Details (include every applicable attribute)
  * Operating System+version: CentOS 7
  * Compiler+version: GCC 10
  * Conan version: 1.39.0
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)
Add `PATH` to your conan profile and attempt a build with something that uses a build tool that appends to path.
https://github.com/conan-io/conan-center-index/issues/6982

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
fribidi/1.0.9: Applying build-requirement: meson/0.59.0
fribidi/1.0.9: Applying build-requirement: ninja/1.10.2
Downloading conan_sources.tgz
fribidi/1.0.9: Configuring sources in /home/centos/.conan/data/fribidi/1.0.9/_/_/source
fribidi/1.0.9: Copying sources to build folder
fribidi/1.0.9: Building your package in /home/isb/.conan/data/fribidi/1.0.9/_/_/build/c19b2fcbf393102ff07e49643ac3204114144a72
fribidi/1.0.9: Generator txt created conanbuildinfo.txt
fribidi/1.0.9: Aggregating env generators
fribidi/1.0.9: Calling build()
/bin/sh: meson: command not found
fribidi/1.0.9: ERROR: Package 'c19b2fcbf393102ff07e49643ac3204114144a72' build failed
fribidi/1.0.9: WARN: Build folder /home/centos/.conan/data/fribidi/1.0.9/_/_/build/c19b2fcbf393102ff07e49643ac3204114144a72
```

**Comment by memsharded** [comment]
Hi @Renari 

Have you read the note in https://docs.conan.io/en/latest/reference/profiles.html#package-settings-and-env-vars?

It seems you should define your path like:

```
[env]
PATH=[...]
```

This indicates a "list" type that can be appended, otherwise it is overwritten.

**Comment by Renari** [comment]
I did not see this, looks like this is working as intended.
