### ISSUE TITLE
[question] Pure c libs with a different compiler to what is specified with install params

### ISSUE THREAD

**Issue by ngrodzitski** [conan-io/conan#9470]
Is it possible to specify and use a different compiler for c-language package. So that I specify gcc-11 and all the packages are provided accordingly, except 1 or N packages (which a libs in pure c) for which I want a gcc-9 or gcc-10.

The reason is that I want to use readline/editline packages and they fail to build with latest compilers:
```
editline/3.1: Calling:
 > source_subfolder/configure '--disable-examples' '--enable-static' '--disable-shared' '--prefix=/home/ngrodzitski/.conan/data/editline/3.1/_/_/package/41b9c7c8a67521e8aba38089b95d947947bf64f7' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' 
checking for gcc... gcc-11
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc-11 accepts -g... yes
checking for gcc-11 option to accept ISO C89... none needed
checking whether gcc-11 understands -c and -o together... yes
checking how to run the C preprocessor... g++-11
configure: error: in `/home/ngrodzitski/.conan/data/editline/3.1/_/_/build/41b9c7c8a67521e8aba38089b95d947947bf64f7':
configure: error: C preprocessor "g++-11" fails sanity check
See `config.log' for more details
editline/3.1: 
```
I believe I can use pure c libs compiled with a different version of compiler, at least I can use a package provided by my linux distro itself.

Or any other ideas of how I can get readline or editline package with conan gcc-11/clang12 ?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @ngrodzitski 

Yes, you can define different settings per package, both in command line and profiles, though the later is the recommended:

```
[settings]
compiler = gcc
compiler.version = 11
mypkg:compiler = gcc
mypkg:compiler.version=9
```

This will use 11 for all packages, except those who match "mypkg" that will use 9

**Comment by ngrodzitski** [comment]
Great, it works, thank you!
