### ISSUE TITLE
[feature] Support custom CCI versions with parsing tools.Version

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#9473]
Hello!

Sometimes, upstream doesn't offer a tag or release, and we need to create a [custom cci version](https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases) for the package. Also, depending the version we need to remove/add options, and in case we need to compare versions, the main feature used is [tools.Version](https://docs.conan.io/en/latest/reference/tools.html#tools-version), however, it can't compare when the prefix `cci.` is listed.

As `cci.` prefix is kind "official" for CCI packages and CCI is the official repository to Conan Center, I suggest supporting `cci.<YYMMDD>` on tools.Version:

```python
# True, because cci. is discarded by tools.Version
tools.Version("cci.20210824") > "20210120"

# True, Both have `cci.` discarded
tools.Version("cci.20210824") > "cci.20210120"
```

Related to https://github.com/conan-io/conan-center-index/pull/6951

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SSE4** [comment]
I am not sure it's ideologically right that client itself has a knowledge of a particular CI (even the official one).

**Comment by memsharded** [comment]
Conan 2.0 will probably add explicit versioning schemes (semver, date, semver-alpha...), this is a feature to consider.

**Comment by AbrilRBS** [comment]
Closed by https://github.com/conan-io/conan/pull/15370, this has been supported in Conan 2 forever, the PR is just a test to ensure the correct behvaiour :)
