### ISSUE TITLE
[question] CMakeToolchain with Ninja generator needs manual launch of conanvcvars.bat

### ISSUE THREAD

**Issue by wer14** [conan-io/conan#9474]
I'm using `CMakeDeps` generator and `CMakeToolchain` helper with `Ninja` generator to create a package.
When I call `conan create . 0.0.0@_/_` `CMake` can not find `CXX` compiler unless I manually run `conanvcvars.bat` that was generated by  `CMakeToolchain` #8005.
From [test_ninja.py](https://github.com/conan-io/conan/pull/8005/files#diff-de5ecc7522bb6e0529d04b79a168bee3b1b591b6580b5dc6918e011981590de8R83) file we can see that `conanvcvars.bat` is manually invoked during `conan install`. Makes sense. 
BUT how should I call `conan create` as we can see that [this functionality is missing??](https://github.com/conan-io/conan/pull/8005/files#diff-de5ecc7522bb6e0529d04b79a168bee3b1b591b6580b5dc6918e011981590de8R98)

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @gmikhaile 

Are you sure you are in the latest version? In https://github.com/conan-io/conan/blob/c3ecb9c524aaaaa5d5cdcf64ed9c359e4487ea97/conans/test/functional/toolchains/cmake/test_ninja.py#L112 you can see that the ``conan create`` use case. The PR you are pointing to was later complemented by several others like https://github.com/conan-io/conan/commit/f5b20e13ba54332b9d93d60ce9d3f62d8719a883, and it has been refactorized too, but the test keeps there.

**Comment by wer14** [comment]
> Are you sure you are in the latest version? In

Thank you, that was the problem.
