### ISSUE TITLE
[question] header file contain absolute path to installed data

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9476]
The hard-coded absolute path in header file, make the binary install non-portable, the path is for a config file.
How to solve it?
I think for self developed lib, it's ok to convert the absolute path to relative path that's relative to the header file in `CMakeLists.txt`. But for other libs, a patch is needed, not so good. Any better way?

`configure_file` in `CMakeLists.txt` happens when `cmake.install()`
```python
def build(self):
    cmake = CMake(self)
    cmake.configure(source_folder="cppjieba")
    cmake.build()
    cmake.install()
```

**Comment by memsharded** [comment]
Sorry, but I don't understand your question. Please provide a full reproducible case with your question (code and commands), explain the current behavior  (why it is a problem) and the desired behavior.

**Comment by playgithub** [comment]
`CMakefileLists.txt`
```cmake
...
set(DEFAULT_CONFIG_FILE_PATH  ${CMAKE_INSTALL_FULL_DATADIR}/${PROJECT_NAME}/config/config.json)
configure_file(source/include/cppjieba/config.hpp.in
               ${CONFIGURED_FILES_ROOT}/source/include/cppjieba/config.hpp.for_install
               @ONLY)
install(FILES ${CONFIGURED_FILES_ROOT}/source/include/cppjieba/config.hpp.for_install
        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}
        RENAME config.hpp)
...
```
so `config.hpp` contains a path that's not portable

`conanfile.py`
```python
def build(self):
    cmake = CMake(self)
    cmake.configure(source_folder="cppjieba")
    cmake.build()
    cmake.install()
```
With `cmake.install()`, the installed `config.hpp` contain an absolute path to `config.json`,
so it is not portable for binary installation.

**Comment by memsharded** [comment]
I am not sure this is a Conan question but a CMake one? You want your ``CMakeLists.txt`` to generate the config.json with a relative path, not an absolute one?

**Comment by playgithub** [comment]
> I am not sure this is a Conan question but a CMake one?

For cmake, it's ok, because it always configure, build and install.
The path is always set properly during cmake configure.

For conan, it supports binary install, a fixed path might have a problem.

> You want your `CMakeLists.txt` to generate the config.json with a relative path, not an absolute one?

Both ok, as far as it works.

However better if the original cmake project is untouched.

**Comment by memsharded** [comment]
Conan packages must be relocatables, they cannot contain absolute paths, otherwise they will not work in different machines.
Files inside a package cannot contain absolute paths, your config.json must be generated and work with relative paths, or it cannot be used within the package. This is not Conan specific, you cannot simply build that thing in one machine, move to other machine and expect it to work.

**Comment by playgithub** [comment]
Anyway to mark a conan package as source install only? so that the user has no chance to upload binaries for the pakckage, it'll always be installed from source code.

**Comment by memsharded** [comment]
``build_policy = "always"`` can help, but it will rebuild from source every ``conan install``. More a workaround than a solution.

**Comment by playgithub** [comment]
> `build_policy = "always"` can help, but it will rebuild from source every `conan install`. More a workaround than a solution.

yes

thanks anyway
