### ISSUE TITLE
[question] Overriding renamed requirements

### ISSUE THREAD

**Issue by naggerx** [conan-io/conan#9482]
Is it possible to override the name of an requirement?

There is:
PkgA/1.0
PkgA/1.1
PkgB/1.0 requires PkgA/1.0
MyPkg/1.0 requires PkgB/1.0 and can overwrite PkgB's dependency of PkgA to PkgA/1.1

What if "PkgA" was renamed to "pkg_a" in version 2.0. How can MyPkg overwrite PkgB's dependency for "PkgA/1.0" to the new "pkg_a/2.0"?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @naggerx 

It is not possible, different casing are treated as different packages, so it is not possible to do overrides for this. It is necessary to change the consumer ``requires``.

I would recommend to use a version bump, when PkgA/1.1 -> pkga/1.2, and then when you go down to the consumer to upgrade the dependency, then change the name as well.

**Comment by memsharded** [comment]
Closing as responded back then. Also Conan 2 has new tools like ``[replace_requires]``, so might be worth checking and open a new ticket if necessary. Thanks for the feedback.
