### ISSUE TITLE
[question] Can conan expose a set of libs by CMAKE_PREFIX_PATH?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9485]
So that, for cmake project, it might take advance of CMAKE_PREFIX_PATH for conan, and `find_package` can find libs in `conan`.
Best of all, the original cmake project can keep untouched while using libs in conan.

EDIT
For `Visual Studio` project, `conanbuildinfo.props` is necessary, because a VS project is supposed to have no information about dependencies.
For `cmake` project, it have complete infomations about  what is needs
```
find_package(<PackageName> [version] [EXACT] [QUIET] [MODULE]
             [REQUIRED] [[COMPONENTS] [components...]]
             [OPTIONAL_COMPONENTS components...]
             [NO_POLICY_SCOPE])
```
Why not preparing `CMAKE_PREFIX_PATH` properly and let `find_package` work in its own way.
Again it can keep `CMakeListst.txt` untouched.

**Comment by memsharded** [comment]
This is done by the CMakeToolchain integration (also the legacy ``cmake_paths`` generator).

**Comment by playgithub** [comment]
Great
Thanks

**Comment by playgithub** [comment]
Why does `cmake_paths` generator become legacy?
Is it replaced by `cmake_find_package` generator?

**Comment by memsharded** [comment]
No, by CMakeToolchain
