### ISSUE TITLE
[bug] Can't upload Conan package to Artifactory CE

### ISSUE THREAD

**Issue by yoav-klein** [conan-io/conan#9486]
I run a Artifactory CE instance using the Docker installation on a server.
I create a repository of type Conan, called conan-test

Then I configure my Conan client as such:
```
conan remote add artifactory http://<IP>:8081/artifactory/api/conan/conan-test False
```

When I now try to upload, after successful authentication, I get a timeout
```
RROR: 
Error uploading file: conanfile.py, 'HTTPConnectionPool(host='52.215.203.143', port=80): Max retries exceeded with url: /artifactory/api/conan/conan-test/v1/files/_/hello/0.4/_/0/export/conanfile.py (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f273415f700>, 'Connection to 52.215.203.143 timed out. (connect timeout=60.0)'))'
```

NOTE that there is certainly communication with the server, as conan asks me user & password and only goes on if I enter the correct ones, otherwise it says "authentication failed".

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Conan version: 1.34.0
  * Python version:  3.8

**Comment by memsharded** [comment]
Hi @yoav-klein 

Lets try first to remove possible setup errors, and make sure is nothing related to the client. If you could please:

- Download the zipped ArtifactoryCE, unzip, and launch it manually, in the same machine you are running the client
- Configure the repo and upload a package.

If that works, I would then try to do the same, but running on the different server, to try to rule out network issues. Finally, if that also works, it means that it is some docker configuration probably.

**Comment by yoav-klein** [comment]
Ok, now I'm running conan from the same server, trying to upload a package. I get this:

```
Are you sure you want to upload 'hello/0.1' to 'artifactory'? (yes/no): yes
Uploading to remote 'artifactory':
Uploading hello/0.1 to remote 'artifactory'                                              
ERROR: 
Error uploading file: conanfile.py, 'HTTPConnectionPool(host='172.31.28.172', port=80): Max retries exceeded with url: /artifactory/api/conan/conan-test/v1/files/_/hello/0.1/_/0/export/conanfile.py (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f285f499f40>: Failed to establish a new connection: [Errno 111] Connection refused'))'
ERROR: 
Error uploading file: conanmanifest.txt, 'HTTPConnectionPool(host='172.31.28.172', port=80): Max retries exceeded with url: /artifactory/api/conan/conan-test/v1/files/_/hello/0.1/_/0/export/conanmanifest.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f285d42b700>: Failed to establish a new connection: [Errno 111] Connection refused'))'
ERROR: hello/0.1: Upload recipe to 'artifactory' failed: Execute upload again to retry upload the failed files: conanfile.py, conanmanifest.txt. [Remote: artifactory]

ERROR: Errors uploading some packages
```

May it be an issue with the setting of the "Custom Base URL"? I've set this to the private IP of the server as such:
```
http://<my_server_local_ip>
```

is that ok?

**Comment by memsharded** [comment]
> I've set this to the private IP of the server as such

Did you mean "public"? The Custom Base URL should be the public URL of the server, otherwise clients will not know how to connect.

**Comment by yoav-klein** [comment]
I've set the private IP since I'm running Conan from the same machine, so if the client can find the server on the public IP it most certainly should find it on the private IP, just trying to eliminate some possible problems related to networking. I did try using the public IP when running conan from a machine on another network, that brought me to open this issue.

**Comment by yoav-klein** [comment]
Hi @memsharded , any new?

**Comment by memsharded** [comment]
Hi @yoav-klein 

I am not sure the Custom Base URL is used in that way for the routing when running in localhost. It could be possible that some firewall or other stuff in the server is blocking something?, this is the reason I suggested to try first with a local ArtifactoryCE in the client machine, which requires zero configuration, just unzip and double click to start it, then use the "SetMeUp" button to get the expected remote URL. If that works, I'd try exactly the same setup (zero configuration, no need to ) in the server, and see what happens. From there, I would start configuring it to the outside world, changing the Custom Base URL, etc.

**Comment by lasote** [comment]
Hi, it looks definitely like a network configuration. Check that the port the Artifactory is running is 80 (the default is 8080 and in the traces you pasted looks like the client is trying to connect to 80) doing a curl:

`curl http://localhost/artifactory/api/conan/conan-test`  or `curl http://YOUR_IP:YOUR_PORT/artifactory/api/conan/conan-test`         

It should return a json like:

```
{
  "errors" : [ {
    "status" : 401,
    "message" : "Authentication is required"
  } ]
}%  
````

If it works, the Conan client should work like a charm. Hope it helps!

**Comment by yoav-klein** [comment]
@lasote, where is it documented that you must run Artifactory on port 80? @memsharded

**Comment by yoav-klein** [comment]
@lasote, @memsharded , seems that this was solved by merely deleting the "Custom Base URL" setting in Artifactory. Is that the correct way? What is this setting good for anyway? references please.

**Comment by lasote** [comment]
> @lasote, where is it documented that you must run Artifactory on port 80? @memsharded

Nowhere, you can run it where you want. I was just noticing that the error trace you pasted was using the 80:

`Error uploading file: conanfile.py, 'HTTPConnectionPool(host='52.215.203.143', port=80):`

> seems that this was solved 

Great!!

> What is this setting good for anyway? references please.

Yes, you are good without a "Custom Base URL". Here are some docs: https://www.jfrog.com/confluence/display/RTF6X/Configuring+Artifactory

Just note that we are not experts in Artifactory configuration, much more focused on the Conan tool but if you have any questions we can assist or find a person from another team that will do it.

**Comment by yoav-klein** [comment]
Thanks @lasote @memsharded
