### ISSUE TITLE
[question] When cross-compiling, the find_package function fails

### ISSUE THREAD

**Issue by zuowanbushiwo** [conan-io/conan#9488]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
I try  cross-compile packages for Android platform: [Using toolchain from Android NDK](https://github.com/conan-io/docs/blob/develop/integrations/cross_platform/android.rst#using-toolchain-from-android-ndk) , but In my CMakelist.txt   used  find_package(protobuf  REQUIRED) have follow error:
Error  output:
```
  By not providing "Findprotobuf.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "protobuf",
  but CMake did not find one.

  Could not find a package configuration file provided by "protobuf" with any
  of the following names:

    protobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "protobuf" to CMAKE_PREFIX_PATH or set
  "protobuf_DIR" to a directory containing one of the above files.  If
  "protobuf" provides a separate development package or SDK, be sure it has
  been installed
```
But  I  messaged out   CMAKE_PREFIX_PATH  and CMAKE_BINARY_DIR var，They all look right： 
```
CMAKE_BINARY_DIR:/home/packager/conan_example/test-conan-protobuf/conan-build-cross
CMAKE_PREFIX_PATH is: /home/packager/.conan/data/protobuf/3.15.5/_/_/package/61ae6ac0d2a21a04e6b88db79f28230f495dd81b/;/home/packager/.conan/data/protobuf/3.15.5/_/_/package/61ae6ac0d2a21a04e6b88db79f28230f495dd81b/lib/cmake/protobuf;/home/packager/.conan/data/zlib/1.2.11/_/_/package/2092172cecdd33fe46f17b980acad1e36241cfb6/;/home/packager/conan_example/test-conan-protobuf/conan-build-cross;/opt/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64;/home/packager/conan_example/test-conan-protobuf/conan-build-cross
```
 My /home/packager/conan_example/test-conan-protobuf/conan-build-cross   directory also  have  those file：

![image](https://user-images.githubusercontent.com/3354428/131101789-01a27b84-adf1-43a4-9892-ebff331b3f7a.png)

And When I  set   as follow, it can build successful .
```
set(protobuf_DIR  "${CMAKE_BINARY_DIR}")
set(ZLIB_DIR      "  ${CMAKE_BINARY_DIR}")
```
conanfile.py define generators  as follow:
generators = "cmake", "cmake_find_package_multi","cmake_find_package"

why？ and How to modify？

Thanks！

**Comment by madebr** [comment]
Show us your (host and build) profiles.
Show us the commands you executed.
