### ISSUE TITLE
[feature] Add RISC-V Architectures to default settings.yml

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#9493]
As [RISC-V](https://riscv.org/) is becoming a more popular target for embedded development, it makes sense to add it to Conan's default settings for both `arch_build`  and `arch_target`.
RISC-V is comprised of a base ISA with optional, additional extensions indicated by letters like `m`, `a`, and `c`.
There are 32-bit and 64-bit versions and _technically_ 128-bit, if I understand correctly, but I don't know if the 128-bit version needs to be addressed at the moment.
It's probably easiest to follow Clang's / Rust's platform naming conventions in [Rust's Platform Support Documentation](https://doc.rust-lang.org/beta/rustc/platform-support.html), i.e. `riscv32i`, `riscv32imac`, `riscv64gc`, etc.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
It would make sense, but not for ``arch_build`` and ``arch_target``. They are about to dissapear, and are not necessary with the 2 profiles approach, which is becoming the default. I guess the proposal riscv32i, riscv32imac, riscv64gc sounds good, but it would be good to make sure the extensions do not explode, and besides ``imac``, we can have ``ima``, ``imc``, ``iac``, etc.

**Comment by jwillikers** [comment]
It seems like architectures should incorporate sub-settings to better define specifics, like perhaps the overall architecture is `riscv` but then sub-settings further define `32`, `64`, or `128` bit versions and then various letters can be set as extensions. Is it possible to do that without having to enumerate every possible combination of extensions, i.e. letters?

**Comment by Tobulus** [comment]
Basic Support: https://github.com/conan-io/conan/pull/15053

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/15053 is adding basic support, and defining triplets and flags that seem to work for common cases. I suggest to close this as solved by https://github.com/conan-io/conan/pull/15053. Specific variants of these can be customized by users with custom sub-settings, unless we learn that the triplets or flags need to change to something different. 

So I am closing this ticket, please open a new ticket if compiler flags or triplets need to be changed for other variants, it would be good to know the specific values that should be passed to the compiler. Thanks!
