### ISSUE TITLE
[feature] Adding a run_requirements method?

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#9495]
Hello,

I am wondering how can we distinguish between build-time requirements and run-time requirements in Conan? An example of a runtime requirement would be plugins needed by a library (actually the only example I have in mind). For example, the Qt Multimedia library needs some GStreamer plugins at runtime, which in turn might require some Alsa plugins. But these are not required to build Qt. So adding these to `requirements` means Qt could be unnecessarily rebuilt every time these or anything in their graph is updated. Not adding them to the requirements on the other hand would mean the end consumer would just have to know all the runtime requirements in their dependency graph.

Please let me know if it is possible to distinguish between run/build time dependencies in current Conan. If not then maybe a `run_requirements` method could be added to model these? (which would be brought into cache only at `conan install` I guess)

- [✓] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The Conan 2.0 proposal is adding ``build=True/False, run=True/False`` among others traits to specify qualifiers to the different requirements: https://github.com/conan-io/tribe/pull/26

In Conan 1.X is not possible, and it will not be added, we will need to wait until Conan 2.0. Please stay tuned for the alphas and betas of Conan 2.0 to try things and give feedback.

**Comment by daravi** [comment]
That sounds great @memsharded! Will close as duplicate then.
