### ISSUE TITLE
[feature] Ability for a recipe to modify another package

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#9497]
Hello,

I think it may be better for me to describe my use-case that I think is not currently covered by Conan than give a suggestion.

There are cases when I need to modify a package. For example if I have a Qt installation, I might need to add an additionally purchased module to the installation. (in my case I buy the TreeView for QQC2 and install it in my Qt package in the Conan cache) Another example I have come across is installing plugins for Alsa  (https://github.com/conan-io/conan-center-index/pull/7098#discussion_r697920460).

So I was wondering if there could be a mechanism where a package could somehow be modified by the consumer to produce a new package.

The current workflow:
- Run conan install
- Each developer manually compiles / installs the extra module to the conan installation

- [✓] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I am not sure what kind of modifications you have in mind, but as a general rule, it is not possible to modify packages. Recipes already implement their variability via ``settings`` and ``options`` and might also listen to some configuration items like ``tools.cmake.cmaketoolchain:generator``, and the build might also use some env-vars. But it is not that you can modify the recipe code from the downstream consumers.

**Comment by memsharded** [comment]
Conan 2 added new package configuration capabilities, with ``conf``. Still recipes declare their customization points, it is not possible to directly patch with arbitrary changes dependencies from the consumers, this is done by modifying the recipes of the dependency directly and ``conan create`` it.
