### ISSUE TITLE
[question/bug] MSVC compiler setting

### ISSUE THREAD

**Issue by arttet** [conan-io/conan#9503]
I read about a new [compiler setting](https://docs.conan.io/en/latest/reference/config_files/settings.yml.html?highlight=msvc#msvc). So I was trying to use it. But there are some problems. I have prepared the [branch](https://github.com/arttet/reproduce-bugs/tree/bug/msvc-14.29) with my changes. I used those changes locally, but Conan couldn't find a compiler correctly. Did I use this setting correctly? Is it a bug or not?

P.S. We shouldn't consider the output on Github right now.  

- [+] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @arttet 

I am a bit confused, you are talking about the ``msvc`` compiler, but your install command is:

```bash
conan install . --install-folder build --build=outdated -s arch_target=x86_64 -s build_type=Debug -s compiler.cppstd=17 -s compiler.version=12 -s compiler=clang -s compiler.libcxx=libstdc++11 -e CC=clang-12 -e CXX=clang++-12
```

Which means that you are trying to use clang? Or maybe you didn't update the branch build.sh/readme?

**Comment by memsharded** [comment]
Hi @arttet 

It is possible that some of the legacy integrations haven't fully implemented support for the ``msvc`` compiler. As those integrations are going to be removed in 2.0, we should focus efforts in making sure the new integrations work robustly with this.
I have tried the following:

```bash
$ conan new hello/0.1 --template=cmake_lib
$ conan install . -s build_type=Debug -s arch_target=x86_64 -s compiler.cppstd=17      -s compiler.version=19.29 -s compiler=msvc      -s compiler.runtime=dynamic -s compiler.runtime_type=Debug -c tools.cmake.cmaketoolchain:generator=Ninja
$ conan build .
```

This maps to a ``set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Auxiliary/Build/vcvarsall.bat"  amd64 -vcvars_ver=14.29`` for the compiler version, and seems to be working fine.

**Comment by arttet** [comment]
Hi @memsharded 

Thank you so much. I reproduced your example and got the same result.

**Comment by arttet** [comment]
Hi @memsharded 

I faced the following problem when I used the [msvc](https://github.com/arttet/reproduce-bugs/tree/bug/msvc-14.29) flag:
```
See also "D:/a/reproduce-bugs/reproduce-bugs/build/CMakeFiles/CMakeOutput.log".
  has asked CMake to find a package configuration file provided by
  "benchmark", but CMake did not find one.

  Could not find a package configuration file provided by "benchmark" with
  any of the following names:

    benchmarkConfig.cmake
    benchmark-config.cmake

  Add the installation prefix of "benchmark" to CMAKE_PREFIX_PATH or set
  "benchmark_DIR" to a directory containing one of the above files.  If
  "benchmark" provides a separate development package or SDK, be sure it has
  been installed.
```
What can be wrong?

**Comment by franramirez688** [comment]
I saw that `benchmark` was declared as a `build_require` so this is a special case.

You'll have to add something like the code below into your `conanfile.py`:

```python
from conan.tools.cmake import CMake, CMakeDeps
from conans import ConanFile

class ReproduceBugsConan(ConanFile):
    # ....

    def build_requirements(self):
        self.build_requires("benchmark/1.6.0")

    def generate(self):
        cmake = CMakeDeps(self)
        # generate the config files for the build require
        cmake.build_context_activated = ["benchmark"]
        cmake.generate()

     # ...
```
Now, if you run it again that problem should be solved.

You have more information [here](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#build-context-activated).

**Comment by arttet** [comment]
Hi @franramirez688 

Thank you for an inspiring response. I built my example. However, when I used the following profile:
```
include(default)

[settings]
build_type=RelWithDebInfo
arch_target=x86_64
compiler.cppstd=17

compiler=msvc
compiler.version=19.29
compiler.runtime=static
compiler.runtime_type=Release

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

And I got the following errors:
```
-- Conan: Target declared 'benchmark::benchmark'
CMake Error at build/cmakedeps_macros.cmake:4 (message):
  Library 'benchmark' not found in package.  If 'benchmark' is a system
-- Configuring incomplete, errors occurred!
See also "D:/a/reproduce-bugs/reproduce-bugs/build/CMakeFiles/CMakeOutput.log".
  library, declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  build/cmakedeps_macros.cmake:48 (conan_message)
  build/benchmark-Target-relwithdebinfo.cmake:21 (conan_package_library_targets)
  build/benchmarkTargets.cmake:27 (include)
  build/benchmark-config.cmake:11 (include)
  CMakeLists.txt:9 (find_package)
```

I also noticed the following strange thing:
```
benchmark/1.6.0: Copying sources to build folder
benchmark/1.6.0: Building your package in C:\Users\runneradmin\.conan\data\benchmark\1.6.0\_\_\build\95e822d95404f47048e0e8a6798830912efe2db2
benchmark/1.6.0: Generator cmake created conanbuildinfo.cmake
benchmark/1.6.0: Aggregating env generators
benchmark/1.6.0: Calling build()
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
```

**Comment by memsharded** [comment]
> benchmark/1.6.0: Generator cmake created conanbuildinfo.cmake

This means you are still using the legacy integrations somewhere. You shouldn't be mixing ``CMakeDeps`` with it, they are exclusive.

**Comment by arttet** [comment]
Hi @memsharded 

I think I use only a modern approach.

```
from conan.tools.cmake import CMake, CMakeDeps

    def generate(self):
        cmake = CMakeDeps(self)
        cmake.build_context_activated = ["benchmark"]
        cmake.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

Do I have this problem because of the Conan recipe of benchmark? What can I do?

**Comment by memsharded** [comment]
> Do I have this problem because of the Conan recipe of benchmark? What can I do?

Yes, if what is failing is the ``benchmark`` recipe, it is needed to modernize the ``benchmark`` recipe, so it works with the new ``msvc`` settings. There is a process of modernization of ConanCenter recipes to be prepared for Conan 2.0, but that will take a while.

**Comment by arttet** [comment]
OK, thank you

**Comment by memsharded** [comment]
I am closing this, it doesn't seem a bug so far, just that recipes from ConanCenter are still not using the new integrations, and do not support yet msvc compiler setting (in the general case, some might work)
