### ISSUE TITLE
[question] How to make option `shared` true by default when using conanfile.txt?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9508]
How to make option `shared` true by default?

Because a header only lib doesn't support option `shared`, it can't be set in profile.
For preference, how to make option `shared` true by default?

**Comment by czoido** [comment]
Hi @playgithub,
You can configure the default options [as a dictionary](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=default_options#default-options) like:

```
class MyPkg(ConanFile):
    ...
    options = {"build_tests": [True, False],
               "option1": ["value1", "value2"],
               "option2": "ANY"}
    default_options = {"build_tests": True,
                       "option1": "value1",
                       "option2": 42} 
```
You can also use the [configure() and config_options() methods](https://docs.conan.io/en/latest/reference/conanfile/methods.html#configure-config-options) to adjust the options based on rules, like for example deleting the shared option for a header_only library: 

```
    def configure(self):
        if self.options.header_only:
            del self.options.shared
```
There are multiple recipes in Conan Center Index that are doing this, for example: https://github.com/conan-io/conan-center-index/blob/8acbfa2ff899c4abca0b16bf6c42905a3000e5ac/recipes/scnlib/all/conanfile.py#L40-L44

**Comment by playgithub** [comment]
Sorry, the question is not clear enough.
How to make option `shared` true by default when using conanfile.txt?

**Comment by czoido** [comment]
Hi @playgithub,
You can [set the option in the conanfile.txt](https://docs.conan.io/en/latest/reference/conanfile_txt.html#options) like this:

```
[options]
poco:shared=True
openssl:shared=True
```

**Comment by playgithub** [comment]
> Hi @playgithub,
> You can [set the option in the conanfile.txt](https://docs.conan.io/en/latest/reference/conanfile_txt.html#options) like this:
> 
> ```
> [options]
> poco:shared=True
> openssl:shared=True
> ```

Because I prefer `shared=True`, I'd like the default value to be `True`, any way?

**Comment by czoido** [comment]
Hi @playgithub,
I don't know if I'm understanding your use case. If you want to set the default for a library you have to set that in the library's recipe like [explained in the first comment](https://github.com/conan-io/conan/issues/9508#issuecomment-909881601). If you are [using a conanfile.txt](https://github.com/conan-io/conan/issues/9508#issuecomment-909891347) you can set the shared option to True in the `[options]` section for your specific library or even using a pattern for all of them (`*:shared=True`)
Maybe there's something I'm missing? Can you please provide more details on what you want to do and why this is not solving your case?

**Comment by playgithub** [comment]
`*:shared=True` is ok
Will `*:shared=True` lead to failure if some lib doens't have option `shared`?

**Comment by czoido** [comment]
> `*:shared=True` is ok
> Will `*:shared=True` lead to failure if some lib doens't have option `shared`?

No, the option should be ignored if the recipe does not add it.
I'm closing the issue as the problem seems solved, please feel free to reopen if you have further questions.
