### ISSUE TITLE
[question]  How to pass cmake define parameters to  conan_cmake_toolchian_file

### ISSUE THREAD

**Issue by zuowanbushiwo** [conan-io/conan#9509]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

When cross-compiling, I specify the CONAN_CMAKE_TOOLCHAIN_FILE variable in  iprofile's  [env] . If there are some self-defined parameters in this toolchain file,  how do I pass them, especially when using conan install  command compiling  requirements dependent libraries?

I currently use multiple toolchain files, and each file has different parameter settings.

Thanks!

**Comment by memsharded** [comment]
Hi @zuowanbushiwo 

Just a note, please take into account that there are new integrations for all build systems, specifically for CMake: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html. They way they use toolchain files, is different. The new ``CMakeToolchain`` has a ``variables`` attribute that allows to define arbitrary CMake veriables into the generated toolchain file. User toolchain files can also be included.

Also, can you clarify what you mean with ``If there are some self-defined parameters in this toolchain file``? If I understand it correctly, it is not possible to pass arbitrary parameters to a user toolchain from Conan command line, as it is completely unaware of those parameters, etc. If you could elaborate a bit more on the use case, that could help.

**Comment by zuowanbushiwo** [comment]
Hi  @memsharded 
In cross-compilation scenarios, such as Apple OS (ios, macos, tvos. .) ， able to use this super good [ios.toolchain.cmake](https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake)，A PLATFORM variable is defined in this file, which can take the following range of values。
```
list(APPEND _supported_platforms
        "OS" "OS64" "OS64COMBINED" "SIMULATOR" "SIMULATOR64" "SIMULATORARM64"
        "TVOS" "TVOSCOMBINED" "SIMULATOR_TVOS"
        "WATCHOS" "WATCHOSCOMBINED" "SIMULATOR_WATCHOS"
        "MAC" "MAC_ARM64"
        "MAC_CATALYST" "MAC_CATALYST_ARM64")
```
If I only  use cmake to compile, I can specify it like this: 
`cmake   ..   -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake    -DPLATFORM=MAC`

But when using conan, if I want to compile MAC and write the following profile host,  I don’t know how to pass PLATFORM=MAC  variable。
```
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=11
os=Macos

[build_requires]

[options]

[env]
CONAN_CMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake
CONAN_CMAKE_GENERATOR=Ninja
```
The current temporary way is to create an` ios.toolchain_mac.cmake`, as follow:
```
set(PLATFORM  MAC)
include(ios.toolchain.cmake)
```
And then  set `CONAN_CMAKE_TOOLCHAIN_FILE= ios.toolchain_mac.cmake ` in profile 

In some cases there are other variables ENABLE_BITCODE ，ENABLE_ARC ，ENABLE_VISIBILITY need to be set， so the combination is a bit too much.

In my consumer package recipe (conanfile.py), I can control it through the options variable and `build()  cmake.definitions` . But I still don't know how to control the requirements  packger.

Thanks。

**Comment by memsharded** [comment]
Closing this ticket as outdated, referring to legacy and removed integrations.
Please create new tickets regarding the new integrations as necessary, thanks!
