### ISSUE TITLE
error as compiler not defined for compiler.libcxx 

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#9512]
```
C:\Users\Z0108306\Desktop\ConanExample\build>conan profile show default

Configuration for profile default:

 

[settings]

os=Windows

os_build=Windows

arch=x86_64

arch_build=x86_64

build_type=Release

compiler.libcxx=libstdc++11

compiler=gcc

compiler.version=9

build_requires=cmake

[options]

[conf]

[build_requires]

[env]

CC=C:\MinGW\bin\gcc.exe

CXX=C:\MinGW\bin\g++.exe
```
 

C:\Users\Z0108306\Desktop\ ConanExample\build>conan install ..

ERROR: compiler not defined for compiler.libcxx

Please define compiler value first too

**Comment by ghost** [comment]
tried to update conan gcc and also updated env : CC, C++ ,still getting error as compiler not defined for compiler.libcxx .please , anybody catch me in this issue

**Comment by franramirez688** [comment]
Hi @botla04 
The problem is the order, you have to define the compiler at first:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
[options]
[conf]
[build_requires]
[env]
CC=C:\MinGW\bin\gcc.exe
CXX=C:\MinGW\bin\g++.exe
```
By the way, this `build_requires=cmake` is wrong, please, have a look at [this piece of documentation](https://docs.conan.io/en/latest/reference/profiles.html#profile-composition).

**Comment by ghost** [comment]
thanks @franramirez688  , but how to define compiler at the first

**Comment by franramirez688** [comment]
It's like a put in my previous comment:
```
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
```
Notice the `compiler=gcc` is defined as the first one.

**Comment by ghost** [comment]
@franramirez688 
yes , i gone through that but still facing same issue
error : compiler not defined for compiler.libcxx 
please define compiler value first too

**Comment by memsharded** [comment]
Can you please post your new ``conan profile show default`` result?
It seems there is also something else wrong in your profile with ``build_requires=cmake`` in the settings section.

**Comment by botla04** [comment]
hi @memsharded 

[requires]

[generators]
cmake 


[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
[options]
[conf]
[build_requires]
[env]
CC=C:\MinGW\bin\gcc.exe
CXX=C:\MinGW\bin\g++.exe


this is my conanfile.txt


then run command as >conan install ..
still the errror is same as
compiler not defined for compiler.libcxx
Please define compiler value first too

>conan profile show default




[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler.libcxx=libstdc++11
compiler=gcc
compiler.version=9
build_requires=cmake
[options]
[conf]
[build_requires]
[env]
CC=C:\MinGW\bin\gcc.exe
CXX=C:\MinGW\bin\g++.exe

**Comment by franramirez688** [comment]
@botla04 any news on that?

**Comment by sweavo** [comment]
Hmm, I'm here as a total conan newb having followed the https://docs.conan.io/en/latest/getting_started.html

My default profile has the items in the wrong order, but with conan gatekeeping where the profile is stored, I don't know how to point vim at the file and reorder the items.  I think this is likely the OP's issue too.

**Comment by memsharded** [comment]
Hi @sweavo 

``conan config home`` will give you the Conan home folder (``<userhome>/.conan``), and inside ``profiles`` the ``default`` profile is the one that is used by default.

If you are learning right now, maybe it is worth going for 2.0 directly: https://docs.conan.io/en/2.0/index.html. It is still beta.9, but planned to go final this month.
