### ISSUE TITLE
[bug] Cross-compiling for armv8 but Clang uses --target=armv7-none-linux-androideabi22

### ISSUE THREAD

**Issue by n-eq** [conan-io/conan#9521]
Hello,

I am trying to cross-compile a library to both Android armv7 and armv8 platforms. The first one builds correctly, but when compiling for arch armv8 I noticed clang calls `-march=armv7-a` and `--target=armv7-none-linux-androideabi22` in its command line (see the full log below).

Here's the profile I am using (Android NDK 23.0.7599858, api level 22)
```
include(default)
target_host=aarch64-linux-android
android_ndk=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858
api_level=22

[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=12
os=Android
os.api_level=$api_level
[build_requires]
[options]
[env]
PATH=[$android_ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin]
CHOST=$target_host
AR=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar
AS=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-as
RANLIB=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ranlib
CC=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android22-clang
CXX=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android22-clang++
LD=$target_host-ld
STRIP=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip
CONAN_CMAKE_TOOLCHAIN_FILE=$android_ndk/build/cmake/android.toolchain.cmake
```

### Environment Details (include every applicable attribute)
  * Operating System+version: MacOS Big Sur 11.4 (Darwin 20.5.0)
  * Compiler+version: Clang (aarch64-linux-android22) 12.0.5
  * Conan version: 1.36.0
  * Python version: 3.9.6

### Steps to reproduce (Include if Applicable)
I am using the following command:
`$ conan create . koinbra/android_arm64-v8a -s build_type=Release -o shared=False -o log4c:shared=False --profile android_arm64-v8a -j /Users/n-eq/Dev/akl/log4c/__liv/pkg_info/pkg_info_3.00.09/arm64_Release_static.json  -tf None`

### Logs (Executed commands with output) (Include/Attach if Applicable)

[conan.log](https://github.com/conan-io/conan/files/7096711/conan.log)

Is there something I'm doing wrong? I appreciate your help.

**Comment by dmn-star** [comment]
This happens because ANDROID_ABI is not set and CMake uses a default setting.

```
if(NOT ANDROID_ABI)
  set(ANDROID_ABI armeabi-v7a)
endif()
```

I don't know how to pass cmake parameters to android toolchain. And whether that is even possible with conan. As a workaround, you can create several toolchains files. E.g. arm64-v8a.android.toolchain.cmake
>set(ANDROID_ABI arm64-v8a)
include(path to /android.toolchain.cmake)

 and then use it with conan CONAN_CMAKE_TOOLCHAIN_FILE=arm64-v8a.android.toolchain.cmake

**Comment by dmn-star** [comment]
On the other hand, here's another way you can build for Android. https://github.com/conan-io/conan-center-index/issues/4220#issuecomment-758486060

**Comment by n-eq** [comment]
Hi @dmn-star, many thanks for the comments.
I didn't find the three lines you mention:
```
if(NOT ANDROID_ABI)
  set(ANDROID_ABI armeabi-v7a)
endif()
```

However, I solved the issue by adding `ANDROID_ABI = "arm64-v8a"` to `CMake` class's `definitions` field before building.

**Comment by dmn-star** [comment]
> I didn't find the three lines you mention:

They are  in android.toolchain.cmake.

<img width="879" alt="android_toolchain" src="https://user-images.githubusercontent.com/52277783/132107268-37bbae72-05c9-4003-9884-551056b2439d.png">

**Comment by n-eq** [comment]
> They are in android.toolchain.cmake.


Yes, but apparently they were removed in NDK version 23.0.7599858, which is the one I'm using.
