### ISSUE TITLE
[idea] Enable the creation of package with ``create`` instead of ``export-pkg`` for packages with ``build_policy = "never"``

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9524]
The ``conan_file.build_policy = "never"`` was introduced as experimental in 1.37, to indicate these packages cannot be built from sources, they have their binaries "export-pkg"ed.

- The ``export-pkg`` command does not support ``test_package``, so if testing is desired (why wouldn't it), it is necessary to call ``conan test`` manually.
- It will probably share a bunch of code with the normal ``conan create`` command.
- Less variability on the user side, every repo is ``git clone`` + ``conan create``, even if it is to package some pre-built binaries that someone put directly in a repo (it happens more than desired)

Just an idea to discuss.

**Comment by lasote** [comment]
+1

**Comment by memsharded** [comment]
This is probably not a good idea, if we want to support the flow that can do a ``conan export-pkg`` in the local flow, to make the package quickly available in the cache without rebuilding completely and ``conan create`` to do a full re-build in the cache. In this case we still need 2 separate cli commands to indicate explicitly the intention. So ``export-pkg`` cannot be completely removed, it might be still possible for some cases to make ``conan create`` behave like ``export-pkg`` if the build-policy is checked, but not sure about the value if we still need to keep ``export-pkg``.
