### ISSUE TITLE
[feature] enable offline working

### ISSUE THREAD

**Issue by blackliner** [conan-io/conan#9527]
We use `conan` for automotive SW development, and we need to be able to work offline. Currently if you work offline you get the following error:
```
Unable to connect to luminar=some_rul
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```
When you follow the suggested solution to disable the remote, you get this errormessage:
```
ERROR: Error loading conanfile at '/home/fberchtold/luminar/LumPDK/conanfile.py': Remote 'luminar' is disabled
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @blackliner 

This only happens when the necessary recipes are not in the local cache. If the recipes you need for the command are already installed and you are not trying to ``--update``, you shouldn't get this message, the server shouldn't be hit. There might be some use case, maybe with revisions, that this could happen. Could you please provide a reproducible case, so we could investigate this further?

**Comment by blackliner** [comment]
All the recipes are from the repo (in source recipes) and build seconds before with internet. I will try to come up with an example.

**Comment by tapia** [comment]
Hi, @blackliner! Did you find that example?

**Comment by blackliner** [comment]
My team is working on this topic in this sprint, I will come back if we have something reproducible

**Comment by tapia** [comment]
Please, come back even if you can't reproduce it, so we can close the issue. Thank you! 🙂

**Comment by vchabanenko-luminar** [comment]
Hi, 

Here's a minimal package which cannot be built with `conan create` that illustrates the issue described by @blackliner.

> a_dummy_2/1.0.0: Forced build from source
> ERROR: Failed requirement 'catch2/2.13.4' from 'a_dummy_2/1.0.0'
> ERROR: Remote 'luminar' is disabled
> vlad@VLAD-LT:~/prj/conan_offline$ 
> 
[a_dummy_2.zip](https://github.com/conan-io/conan/files/7255630/a_dummy_2.zip)

The system is Ubuntu 18.04; 
CPU x86-64; 
the package depends on catch2/2.13.4 which exists in local cache
`~/.conan/data/catch2/2.13.4/_/_/package/499dbc5ac153562abd22d8a15e5411b68090ac7d/`
The remotes are disabled.

Please let me know if you're able to reproduce the issue.

**Comment by memsharded** [comment]
Can you please post the output of trying that?
I have just tried the following from your provided example code, and it works offline:

- ``conan remove * -f`` # clean our cache
-  ``conan create . --build=missing`` # necessary as dependency catch2 with_main option doesn't exist in ConanCenter
- ``conan remote disable conancenter``
- ``conan create .`` # successfully build without checking remotes

Could you post the output of trying those steps in your system, just in case there is some difference?

**Comment by vchabanenko** [comment]
Hi @memsharded 

> vlad@VLAD-LT:~/prj/conan_offline/a_dummy_2$ conan remove "*" -f
> vlad@VLAD-LT:~/prj/conan_offline/a_dummy_2$ conan create . --build=missing
> [HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
> Exporting package recipe
> a_dummy_2/1.0.0 exports_sources: Copied 2 '.txt' files: CMakeLists.txt, CMakeLists.txt
> a_dummy_2/1.0.0 exports_sources: Copied 2 '.cpp' files: a_dummy_2.cpp, a_dummy_2_test.cpp
> a_dummy_2/1.0.0 exports_sources: Copied 1 '.h' file: a_dummy_2.h
> a_dummy_2/1.0.0: A new conanfile.py version was exported
> a_dummy_2/1.0.0: Folder: /home/vlad/.conan/data/a_dummy_2/1.0.0/_/_/export
> a_dummy_2/1.0.0: Using the exported files summary hash as the recipe revision: 1841e63aebd0a4d941ef131f8b718dd3 
> a_dummy_2/1.0.0: Exported revision: 1841e63aebd0a4d941ef131f8b718dd3
> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Release
> compiler=gcc
> compiler.libcxx=libstdc++11
> compiler.version=7
> os=Linux
> os_build=Linux
> [options]
> [build_requires]
> [env]
> 
> catch2/2.13.4: Not found in local cache, looking in remotes...
> ERROR: Failed requirement 'catch2/2.13.4' from 'a_dummy_2/1.0.0'
> ERROR: No remote defined
> vlad@VLAD-LT:~/prj/conan_offline/a_dummy_2$ 
>

**Comment by vchabanenko-luminar** [comment]
Hi @memsharded 

here is the log of your commands (with subtle corrections, like `conan-center` and `"*"`)
https://pastebin.com/cchrMxa5

The error message:

> a_dummy_2/1.0.0: Forced build from source
> ERROR: Failed requirement 'catch2/2.13.4' from 'a_dummy_2/1.0.0'
> ERROR: Remote 'conan-center' is disabled
>

**Comment by memsharded** [comment]
Hi @vchabanenko 

Wow, that is really unexpected, I don't know what could be happening. Apparently exactly the same steps, and suddenly, the `catch2` package seems to disappear from your cache. 

Lets try to do the following, to see if I get some further hint of what could be happening. Please run again the same commands, but adding extra `conan search` commands in between, something like:

```bash
conan remove * -f 
conan create . --build=missing 
conan search 
conan search catch2/2.13.4@
conan remote disable conancenter
conan search 
conan search catch2/2.13.4@
conan create .
```

**Comment by vchabanenko-luminar** [comment]
Hi @memsharded 
Unfortunately this is what I'm getting today at my work laptop on `conan create . --build=missing`:

> ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
> 
> Unable to connect to conan-center=https://center.conan.io
> 1. Make sure the remote is reachable or,
> 2. Disable it by using conan remote disable,
> Then try again.
> 

However my private mac runs conan just fine. Need to figure that issue first.. Will update you with the logs as soon as I'll be able to get them.

**Comment by memsharded** [comment]
Unfortunately that is a different issue. A few things broke today in the internet due to an expired certificate, and we were also affected. Please check https://github.com/conan-io/conan/issues/9695. In short:

- upgrade to 1.40.3
- or apply the updated cacert.pem with ``conan config install https://github.com/conan-io/conanclientcert.git``
- or include the updated cacert.pem in your own ``conan config install`` configuration.

**Comment by vchabanenko-luminar** [comment]
@memsharded 
After the upgrade to 1.40.3 all the commands (see below) work fine for my example package. Will do further testing if it has been fixed on the real project...

```
conan remove * -f 
conan create . --build=missing 
conan search 
conan search catch2/2.13.4@
conan remote disable conancenter
conan search 
conan search catch2/2.13.4@
conan create .
```

**Comment by puetzk** [comment]
> This only happens when the necessary recipes are not in the local cache. If the recipes you need for the command are already installed and you are not trying to --update, you shouldn't get this message, the server shouldn't be hit. There might be some use case, maybe with revisions, that this could happen. Could you please provide a reproducible case, so we could investigate this further?

That actually  isn't quite true, as I mentioned (in passing) over in https://github.com/conan-io/conan/issues/8074#issuecomment-846632671 some months back. 

If any recipe is using compatible_packages and you *want* to use that fallback, you have to be online. Because conan will never cache the absence of a binary locally, and will thus insist on checking remotes for its first-choice flavor every time you `conan install`. And in fact, if you have a remote that is unresponsive (i.e. a corporate artifactory where you have to go on VPN to talk to it), it will actually error out on the failed connection and the `conan install` will fail completely.

> ERROR: HTTPSConnectionPool(host='repository.foobar.com', port=443): Max retries exceeded with url: /artifactory/api/conan/foobar-conan-local/v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026F14B248B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
> 
> Unable to connect to artifactory=https://repository.foobar.com/artifactory/api/conan/foobar-conan-local
> 1. Make sure the remote is reachable or,
> 2. Disable it by using conan remote disable,
> Then try again.

Whereas if you were online it would instead figure out that it had a compatible_package alternative already cached locally.

> foo/1.0@foobar/release: Main binary package '3475bd55b91ae904ac96fde0f106a136ab951a5e' missing. Using compatible package '0e383d048e4ad0827af830a842fd83d32f9f8c7d'

**Comment by memsharded** [comment]
> That actually isn't quite true, as I mentioned (in passing) over in #8074 (comment) some months back.

Yes, that is true. In fact, this is one of the things that we are considering moving forward in Conan 2.0, and we will discuss it with the tribe soon. 

but besides that functionality, if you are not using ``compatible_packages``, then working offline should be possible. Please @blackliner clarify if that could be your issue, or if not, let us know if there is some way to reproduce it.

**Comment by blackliner** [comment]
I retried it today and had no issues. I assume its due to another version of conan. I'd get back here once it happens again.
