### ISSUE TITLE
[question] How to add runtime-only environment variables

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#9529]
Hi is it possible to append only to the run environment? Adding to `env_info` results in the environment variable being added to the virtual environment. But I only need the variable at run time so I need it in the virtual run environment.

In my `environment.sh.env` file I see some variables that are required only for runtime and not in compile time. But I don't see a way for the Conan recipe authors to append to `environment_run.sh.env` instead of `environment.sh.env`. My understanding is that former is for runtime and latter is for build time.

- [✓] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The new environment management implements this:

- Add ``self.runenv_info.append("MYVAR", "MYVALUE")`` to your ``package_info()``
- Use the ``VirtualRunEnv`` generator, or better, auto-activate it with the ``auto_use`` [conf]
- Use ``self.run(..., env=["conanrunenv"])`` to run only with the defined run environment. The file is ``conanrunenv.sh``.

It is pending to properly document this, it is experimental, and we wanted to test it internally first.

**Comment by daravi** [comment]
@memsharded Awesome thanks! Is `VirtualRunEnv` different from `virtualrunenv`? Also what do you mean by `auto_use`?

**Comment by memsharded** [comment]
Yes, it is the new one, very different approach.

```bash
$ conan config list
Supported Conan *experimental* conan.conf properties:
core:required_conan_version: Will raise if the current Conan version does not match the defined version range.
...
tools.env.virtualenv:auto_use: Automatically activate virtualenvs when changing into a directory
```
The description is not very good, it will be improved, but it means that it will generate VirtualBuildEnv and VirtualRunEnv if there are enviroment items by default. At the moment it is opt-in to make sure it is not breaking, but it will be enabled by default in Conan 2.0.

**Comment by daravi** [comment]
Got it. Thanks @memsharded !

**Comment by daravi** [comment]
@memsharded Should this syntax be possible similar to `env_info`?
```
self.runenv_info.GST_PLUGIN_PATH.append(gst_plugin_path)
```
(it doesn't seem to work)

**Comment by daravi** [comment]
@memsharded Some follow up questions and feedback:
1) Putting the config in `conan.conf` I don't see any effects. The `global.conf` documentation says it should be in home directory but I think this should be in the Conan directory (`~/.conan`) correct? Also, putting this `global.conf` in my `~/.conan` directory:
```
[conf]
tools.env.virtualenv:auto_use = True # Automatically activate virtualenvs
```
I am getting this error when running conan commands:
```
Error in Conan initialization: Error while parsing conf value '[conf]'
```
Am I missing something or is this a bug?

---
2) It seems redundant (and confusing) to have to add VirtualRunEnv generator if I have self.run(..., env=["conanrunenv"]) in my recipe. (since I didn't have to include any generator if I used self.run(..., run_environment=True))
---
3) An indicator in the prompt could be useful to show that the environment has been activated
---
4) I guess I could open a separate ticket for this but using `prepend_path` I see the environment variable in the middle, even though it should have been at the very end of the list:
```
/opt/conan/gst-plugins-base/1.19.1/3rdparty/stable/package/f5fe3fc092cad9350eaa1b83e67bf9034b7a5d7b/lib/gstreamer-1.0:/opt/conan/gst-plugins-good/1.19.1/3rdparty/stable/package/10574dabbd4926f359886a1e3bdaf3e723fbe1fc/lib/gstreamer-1.0:/opt/conan/gst-libav/1.19.1/3rdparty/stable/package/72c7f31a45487786fb0fc49d7271eb5e5bf2ceac/lib/gstreamer-1.0:$GST_PLUGIN_PATH:/opt/conan/gstreamer/1.19.1/3rdparty/stable/package/343c7cb897991a054238a1804728747e201f5802/lib/gstreamer-1.0
```
In my case I am using `prepend_path` in all 4 recipes above.

**Comment by daravi** [comment]
Also it seems redundant (and confusing) to have to add `VirtualRunEnv` generator if I have `self.run(..., env=["conanrunenv"])` in my recipe. (the same way I didn't have to include any generator if I used `self.run(..., run_environment=True)`)

**Comment by daravi** [comment]
Nit. I guess I could open a separate ticket for these but using prepend_path I sometimes see `::` added between paths. (not just `:`) Specially when I have 2-3 elements in the list. Maybe they are adding the `:` on both sides?

**Comment by tapia** [comment]
Hi, @daravi 

Question 1: That [conf] section works fine for me. Could you please paste the full `conan.conf` file? Looks like you have some kind of syntax error.

Question 2: The default environment is VirtualBuildEnv. If you want to use VirtualRunEnv, you have to do it explicitly. Anyhow, the recommendation is setting the `auto_use` configuration instead of explicitly use the VirtualRunEnv generator

Question 3: What do you mean? Usually virtualenvs do show that prompt

Question 4: Yep, that should be another ticket :-)

**Comment by chausner-audeering** [comment]
> Question 1: That [conf] section works fine for me. Could you please paste the full conan.conf file? Looks like you have some kind of syntax error.

@daravi Did you solve this issue? I am experiencing the same error with a different setting. I created a `global.conf` file in `~/.conan` with the following content:
```
[conf]
core:default_profile=linux-gcc10
```

Running any Conan command only prints:
> Error in Conan initialization: Error while parsing conf value '[conf]'

**Comment by chausner-audeering** [comment]
@daravi I think we have both misinterpreted the docs at https://docs.conan.io/en/latest/reference/config_files/global_conf.html#tools-configurations. The example that is given there refers to profiles but not `global.conf`, I think.

**Comment by memsharded** [comment]
@chausner-audeering 

Yes, the example there refers to ``Profile values ...``, not to the actual ``global.conf`` file. Most likely the docs can be improved, they are a bit rough now.

The ``global.conf`` doesn't contain the ``[conf]`` header, the contents can be the same items that are under the ``[conf]`` section in a profile (except the ``core`` items cannot be defined in the profile so far).

**Comment by tapia** [comment]
Closing the issue as the main question has been answered. @daravi feel free to reopen it if necessary.
