### ISSUE TITLE
Default for new environment files regarding deactivate

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9533]
at the moment by default the "deactivate" files of new environment files is not generated. This was done to simplify and remove possible errors while releasing the feature, as for package creating not necessary.

For user flows it is inconvenient not having the deactivate scripts. Alternatives:

- Make it the default (generate deactivates). Opt-out.
- Make it the default, without opt-out (make it robust, users feedback)
- Make it opt-in with user config for example: ``conan install . -c tools.env:deactivate=True``

**Comment by lasote** [comment]
I would simplify and generate them always without opt-out. We could introduce later the opt-out. About the opt-in, maybe is too hard for someone using conan local commands.
