### ISSUE TITLE
[question] Is there a (good) way to transfer packages into an air-gapped environment as files?

### ISSUE THREAD

**Issue by yoav-klein** [conan-io/conan#9534]
Hello, 
I'm working in an organization in an air-gapped network (no internet connection).
We do have a mechanism of transferring files inside the internal network though.
I was wondering if there's a way of packaging packages into some file format in order for them to be moved around easily
without the use of the Conan CLI?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by yoav-klein** [comment]
??

**Comment by memsharded** [comment]
Hi @yoav-klein sorry for the delay in answering.

There is no such external file format that could be used for this, but if the Conan client can be used, then isn't it a matter of ``conan download`` + ``conan upload``? You could define an empty cache for the job with CONAN_USER_HOME env-var, to make sure that only the packages you want are uploaded, and you can point it to some controlled location, like a drive that serves as bridge between the two areas?

Would this feature be used for your own packages, or are you considering to do that for the ConanCenter packages? Because if it is the second, we would probably recommend that you build your own package binaries, forking ``conan-center-index`` repo, or some of its recipes.

We started recently to have a look at this feature possibility and initiated some refactors towards it, but nothing in the short term.

**Comment by yoav-klein** [comment]
This is more for ConanCenter packages. Why would I want to "build my own package binaries"? I want to use the ones in the conan center...(?)

**Comment by memsharded** [comment]
> This is more for ConanCenter packages. Why would I want to "build my own package binaries"? I want to use the ones in the conan center...(?)

This is one of the most common policy we see in our users. Those that have important security concerns, to the extend of defining air-gapped environments, have strong policies against using binaries downloaded from the internet, and require them to build them locally. Besides security, there are also other reasons, like being able to fully control your dependencies, customize the build, make sure the compilation environment is optimized for your use case, etc. etc. For example, ConanCenter will build binaries with an old glibc, to achieve the best possible binary compatibility. Building packages against a more modern glibc could have some performance and security advantages.

Regarding the transfer, maybe this is something that you can do server side? Setting up remote repositories in Artifactory, you could populate things there in server side directly (calling Conan commands from the client to download the necessary things), and maybe later do a move/copy in the server directly calling Artifactory API?

**Comment by yoav-klein** [comment]
@memsharded , I didn't quite understand the last paragraph, could you specify more on that?
As far as I understand you, your offer is to  have a machine that has access to both environments, and have the client define 2 remotes - conan-center and the air-gapped Artifactory instance. Then use the client to `download`  from conan-center (whether recipes only or even binary packages; In our case we can run some checks on the binaries so it should be ok) and then `upload` them to the air-gapped Artifactory server. Is that correct?

I believe the last paragraph offers a different approach but I didn't quite understand it so if you could specify more on that It'll be great.

**Comment by memsharded** [comment]
Hi @yoav-klein 

Yes, the approaches commented so far were based on a Conan client bridge, packages were being downloaded to a Conan client cache from the internet, and then uploaded from there to the isolated environment.

What  I was suggesting as another possibility is using an Artifactory server as a bridge. Setting up a remote repository, proxying ``conancenter`` repo in Artifactory, will cache there the downloaded packages (requested from a Conan client, but the client won't be used to upload things, just as a trigger). Then using Artifactory features, like replicas, or the API, you could be moving/copying packages from that remote repo to the other in the air-gapped environment. I see now from your last comment that you are running some checks on the binaries, so maybe this suggestion is not good, as this approach is more server based.

**Comment by yoav-klein** [comment]
Thanks !
