### ISSUE TITLE
Add a "latest release" tag to Git

### ISSUE THREAD

**Issue by nesono** [conan-io/conan#954]
As a consumer of conan by source for running it as a server I would like to have a tag to the latest release, which will be updated whenever a new release has been issued so that I can update my git repository with less effort.

Right now, we need to parse the version scheme to find the latest version, which seems brittle and cumbersome since it has to be solved by everybody who wants to consume conan by source and keep it up to date. An updated tag would help a lot here.

**Comment by memsharded** [comment]
We are using git flow, latest release is always master, would that be good for you?

**Comment by nesono** [comment]
Sounds good to me, we can give it a try 👍

**Comment by memsharded** [comment]
Ok, great, lets close it by now, but please comment or re-open if you have any issue or need help. Thanks!
