### ISSUE TITLE
[question] What is the best way to patch cmake project to support conan?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9542]
i.e. inject
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()''')
```

template `conanfile.py` as below
```python
tools.replace_in_file("hello/CMakeLists.txt", "PROJECT(HelloWorld)",
                              '''PROJECT(HelloWorld)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()''')
```

but many project is as below, and the code above not work
```cmake
PROJECT(HelloWorld
        VERSION 1.0.10
        LANGUAGES CXX)
```

I have seen a sample as below, it seems general, any better way?
```cmake
cmake_minimum_required(VERSION 2.8.12)
project(cmake_wrapper)

include(conanbuildinfo.cmake)
conan_basic_setup()

add_subdirectory("source_subfolder")
```

**Comment by sboehmann** [comment]
In my experience, there is no general best way.

However, most of the time I use the last method.  So many times, that I wrote a helper method `create_cmake_wrapper` for that.

But for some projects this won't work. E.g. if they calculate something relative to the CMAKE_SOURCE_DIR. In that case I most often use real patch files (ultimately, I want to use only patches at some point).

**Comment by memsharded** [comment]
All of that is obsolete now with new ``CMakeDeps`` and ``CMakeToolchain`` integration, which can achieve a transparent integration, no need to modify CMakeLists.txt anymore. You can have a look to the recently updated "Getting started": https://docs.conan.io/en/latest/creating_packages/getting_started.html

**Comment by playgithub** [comment]
> All of that is obsolete now with new `CMakeDeps` and `CMakeToolchain` integration, which can achieve a transparent integration, no need to modify CMakeLists.txt anymore. You can have a look to the recently updated "Getting started": https://docs.conan.io/en/latest/creating_packages/getting_started.html

Great!
