### ISSUE TITLE
[question] Can't find rapidjson in conan

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9544]
The code below can find `RapidJSON` in Linux
```cmake
find_package(RapidJSON REQUIRED)
```

But after wrapping for conan as below, it failed to find `rapidjson` in conan (`rapidjson` has been in conan cache)
```cmake
cmake_minimum_required(VERSION 3.20.0)
project(cmake_wrapper)

include(conanbuildinfo.cmake)
conan_basic_setup()

add_subdirectory("source_subfolder")
```
Do I have to patch the original project about `rapidjson` so that `rapidjson` in conan cache can be found?
Is it also true for the way to use `rapidjson` in conan cache?

**Comment by memsharded** [comment]
Provide your ``conanfile.txt``, and your commands to do the install, together with the output of all the steps. Or even better, provide a fully reproducible example. We need more information to reproduce, thanks.

**Comment by playgithub** [comment]
My problem, I have not used `conanfile.txt`, but installed `rapidjson` manually, so no `conanbuildinfo.cmake` for my project.
However the error is that it can't find `rapidjson`, a little misleading.
I'll provide enough info for issues in the future.
Thanks

**Comment by playgithub** [comment]
ways in native project to find and use rapidjson
```cmake
find_package(RapidJSON REQUIRED)
...
target_include_directories(${PROJECT_NAME} PRIVATE ${RAPIDJSON_INCLUDE_DIRS})
```

for conan, `find_package(RapidJSON REQUIRED)` works, but `${RAPIDJSON_INCLUDE_DIRS}` is empty,
`target_link_libraries(${PROJECT_NAME} RapidJSON::RapidJSON)` works.

It seems that the original project still needs to be modified, doesn't it?
