### ISSUE TITLE
[bug] cross-compile visual_studio generator does not use build requirements bin folders

### ISSUE THREAD

**Issue by gdray-dev** [conan-io/conan#9545]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: visual studio (tested on 15 and 16)
  * Conan version: 1.39 (tested pre-release 1.40)
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
os = Windows
Create a host profile with arch  = x86
Create a build profile with arch = x86_64
Both profiles specify the visual studio comiler, other profile settings can be the same.

Create a recipe using visual_studio generator.

In the recipe, list a package (such as protobuf or flatbuffers) as both a requirement and a build requirement.  In this case, the  requirement is needed for package libraries/headers but the build requirement is needed for the package executable (protoc or flatc). The libraries/headers should be the x86 variant and the executables should be the x86_64 variant

Generate visual studio properties using:

conan install . -g visual_studio -pr:h host_profile -pr:b build_profile

On examination of the "props" file created, it will be seen that the property file has a Conan-"pkg"-Root macro pointing to the requirements (x86) build of the two packages but nothing pointing to the build version (x68_64) of the package.

You might say this is no problem because x86 executables can run on an x86_64 build machine but this logic fails to consider the overall cross compile concept and would not work if I were trying to cross build ARM visual studio projects.  While I have not tested yet, I'm also concerned about cmake generators but perhaps that one is correct.

Expected results:

Conan-"pkg"-Root should still exist as it could be used for accessing the dependency package headers/libraries although these are generally already handled automatically.

NEW:
Conan-"pkg"-Build-Root must exist to get access to the bin folder of the build requirement to access protoc and flatc.  Note that in the case of flatbuffers, the package is actually smart enough not to build flatc if it is being used as a compile dependency so attempting to reference the x86 flatc fails as it is not built.

EXTRA CREDIT:
In researching this, I came across feature request #7162 asking to add ExecutablePath to the visual_studio Props file:

<ExecutablePath>D:\.conan\bfef1e\1\bin;$(ExecutablePath)</ExecutablePath>

In the above case, the paths added to the executable path obviously must be the build requires and not the requires package bin paths.  In fact, "requires" paths should not be added as this might cause attempts to execute bad executables in an ARM cross-compile.

**Comment by gdray-dev** [comment]
In my initial description, I failed to mention an even simpler case that shows this defect.  If a package is only listed as a build dependency then no link to the root folder of that package shows up at all in the props file when cross compiling.  This fact pretty much defeats the purpose of having a build requirement that only provides an executable used by the visual studio build (no headers or libraries needed from the package).

**Comment by memsharded** [comment]
Hi @gdray-dev 

It is definitely possible that the ``visual_studio`` generator is not fully implementing the 2 profiles approach. But it has already entered the "legacy" territory, and the new ``MSBuildDeps`` is already more evolved and powerful. We will focus dev efforts in this one from now on.

So far the ``build_requires`` in ``MSBuildDeps`` has not been considered, and it build_requires will become part of the environment (generated by VirtualBuildEnv new generator, for example). If we want to create .props for ``build_requires`` it is possible, and we should follow a scheme similar to what has been done with CMake:

- We can create ``xxx_build.props`` for build_requires to avoid name conflicts with the host requires.
- We would need to know what needs to be added there, it seems that only ``ExecutablePath`` property?
- It would be great if someone could provide an example of how these are actually used from MSBuild. I guess it is necessary to define a Task/Job in MSBuild, but that is outside of my experience. I am thinking of at least implementing some tests in our suite, so the example should be as minimal as possible.

**Comment by gdray-dev** [comment]
We are porting a number of x86 visual studio projects to use conan and build on x86_64 systems.  If at some point you have code that you would like beta tested, I would be willing to use and comment.  I am also looking at trying to code something up myself as this is going to be a blocker for porting some of our packages.  If you could give a high level view of the files and idea for the change, I would try to code/test a temporary change for us to keep moving while we wait.  Thanks for any help you may be able to offer.

**Comment by memsharded** [comment]
I have scheduled a ``look_into`` this for next release, if we are lucky we could get some progress in a few weeks, I'll tell you here if there is a branch to be tested, many thanks for the offer! 

Some tips:

- The right location to start implementing a test is here: https://github.com/conan-io/conan/tree/develop/conans/test/functional/toolchains/microsoft
- Examples can be found in https://github.com/conan-io/conan/blob/develop/conans/test/functional/toolchains/microsoft/test_msbuilddeps.py, the .vcxproj are long as usual

But I think this can be a bit overwhelming initially for someone new to the codebase, so if you could help guiding with the necessary .vxcproj code to launch an executable (or even better, a .bat, so the test is faster, no need to compiler), and make it work with a hardcoded .props file or something, that would already be super helpful.

**Comment by gdray-dev** [comment]
Sorry, I did not see your full response as I was writing my above comments.  We are only beginning with this project so MSBuildDeps or visual_studio is probably a wash. I will look at MSBuildDeps to see how we need to change our scripts.  We have a build team that needs to do command line builds but we also need to support developers using the Visuual Studio IDE.  This seemed doable with the visual_studio generator but if you say MSBuildDeps is already better, that sounds fine as well.  It may take me a little bit of time to come up to speed on the MSBuildDep generator but as I indicated, we are motivated to try something out to get these projects ported.

**Comment by memsharded** [comment]
Yes, some things that the MSBuildDeps can already do that visual_studio cant:

- it is multi-config, can handle Debug/Release switches in the IDE
- It is customizable, it can handle custom configurations (like ``ReleaseDLL``)
- It generates 1 .props per dependency (and one global one), so subprojects can add the specific dependencies they use, no more.
- The internal architecture is better, it will probably allow easier implementation of this feature.

For structured, known output location, I would also recommend the new ``def layout()`` method that can specify, for example, the ``generators`` folder, so all the props file will not pollute the project.

**Comment by gdray-dev** [comment]
Again, I need to look at MSBuildDeps but in the context of the visual_studio generator I imagined:

- In the case of cross build, either the root or bin folder of each build dependency has to be available.  Libs and headers obviously not.  The worst case we have right now is protoc where a plugin has to be specified on the command line and the plugin has to be specified by a full path, protoc will not search the PATH environment variable.  I think that accessing "helper" files is a pretty common feature of build tools so being able to specify a full path into a build requires is needed.
- When also considering ARM or other cross builds, the requires bin folders should not be in any executable search paths or there is risk of attempting to call the wrong executable.  I'm not exactly sure about the LocalDebuggerEnvironment. I think this is the path to search for dlls of the thing being built in order to test it.  In this case the requires bin paths are correct but your mileage will vary in the cross build case.  Some cross builds can execute, others not.  I guess add the paths all the time as if you can't debug then there is no harm defining them anyway. 
- ExecutablePath would be a "nice to have" but since the command line requires specifying a full path elsewhere, it would not be worse to specify the full path to the executable as well.
- In the case where cross compile is not specified, I think it would still be good to honor the build requires rather than add every dependency appending to the bin path.  Maybe if build requires is specified, honor it. But if not specified, add all dependencies that have a bin path.  The idea of adding all dependencies all the time to the build path seems least appealing as if it creates a conflict, I'm not sure how the conflict could get resolved.

Fyi,the separate host and build profiles seems like a really good idea.  I hope it gets taken off the "experimental" list soon. Attempting to get cross compiles without two profiles was causing me nothing but confusion and grief.

**Comment by gdray-dev** [comment]
[conan_issue.zip](https://github.com/conan-io/conan/files/7124764/conan_issue.zip)

This may be more than you asked for but I hope it is useful.

1) The file hello\hello\hello.vcxproj has an example of how we hope to use executables from build requires inside of a vcxproj file. 

For example from the GUI you right click on the file "data.proto" select properties and click on the "Custom Build Tool".  This will show the command line that executes the custom command.  There are other ways to execute custom commands but they are all similar.

You can also right click on the file and select "Compile" to run the custom command.

2) I think there is also an issue with the LocalDebuggerEnvironment macro created by multiple dependencies each appending PATH inside the property sheet for the dependency.  This macro accumulates multiple copies of the system path and was so big in my real package that I could not echo it to the console without error.

I have created a Custom Build Tool that echos the macro "LocalDebuggerEnvironment" to a file and to the console so you can see it grow as you add more dependencies.

3) I have included my version of a patch to msbuilddeps.py in the folder patch that addresses adding prop pages for dependencies and it removes the multiple addition of PATH for LocalDebuggerEnvironment.  The vcxproj file would have to add an additional  LocalDebuggerEnvironment entry to add PATH one time and then append the built up  LocalDebuggerEnvironment from all the prop files.  Even this might not be correct because definition of ExecutablePath adds the executable paths for the dependencies and then it's not clear the requirement bin path should also be there.

The two folders "hello\hello\conaninfo_unpatched" and "hello\hello\conaninfo_patched" show the property files before and after using my patch.

**Comment by memsharded** [comment]
Hi @gdray-dev 

Your zip was super useful. I have managed with it to implement a test and implement the behavior your are suggesting in https://github.com/conan-io/conan/pull/9686. Trying to target next 1.41, lets see how it goes. 
If you would like to run from my source branch and test it, that would be very useful feedback too. 

Thanks!

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/9686 was merged, so this will be available in next 1.41 (next week). If you want to try it now from source, it is available in the ``develop`` branch.
