### ISSUE TITLE
[bug] conan config get doesn't use global.conf

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#9551]
### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora Silverblue 34
  * Compiler+version: GCC 11.2.1-1
  * Conan version: 1.40.0
  * Python version: 3.9.6

### Steps to reproduce (Include if Applicable)

Create a `~/.conan/global.conf` file with the following contents.

```
core:default_build_profile = default
```

Try to get the configuration parameter with `conan config get`.

```
$ conan config get core:default_build_profile
ERROR: 'core:default_build_profile' is not a section of conan.conf
```

```
$ conan config get conf.core:default_build_profile
ERROR: 'conf' is not a section of conan.conf
```

**Comment by memsharded** [comment]
Hi @jwillikers 

Yes, this is known and expected. At the moment there is no CLI interface to the ``global.conf``, at the end of the day it is just a plain key=value file, not sure if we want to provide such interface. Maybe we want a command that just gives the full path to it to be opened in any editor?

**Comment by jwillikers** [comment]
You're probably right that `conan config get` isn't very useful for this, but any easy way to validate / check the settings from `global.conf` that are in effect would be great. I figured that `conan config get` should work with `global.conf` because the documentation mentions listing values with the `conan config list` which is under the same sub-command.

Checking the global values might be more useful in the context of a particular profile, since a profile might overwrite `global.conf` settings. Maybe it would make sense to show `global.conf` values in effect for a particular profile when using the `conan profile` command?

**Comment by gpxricky** [comment]
@memsharded 

Just an additional note: the command may be useful in case template parameters are used - then it is not straight forward to just open the file and check the value.

Is there some plan to support `conan config set` for the `global.conf` file? We deploy the Conan configuration to our Docker images and just change the `default_profile` and `default_build_profile`? Or is the intention to solve that by using Jinja variables?

**Comment by memsharded** [comment]
At the moment there is no plan to implement any command in 2.0 which purpose is to edit a text file. Same applies to ``conan profile update`` for example, it will be removed in 2.0.

Yes, ``global.conf`` got jinja support in latest release, that could be a possibility.

**Comment by memsharded** [comment]
Conan 2.0 got the ``conan config show <pattern>`` to show current ``global.conf`` values.
Setting them in the file with a command is not possible, as the file is a jinja2 template, so round-trip editing is challenging.

Closing this ticket as not planned.
