### ISSUE TITLE
[question] Setting environment variable inside package_info(self)

### ISSUE THREAD

**Issue by YaminoYuki** [conan-io/conan#9554]
I am trying to set an environment variable using conan, so I can have it inside the generated  environment.sh.env 
one of the ways which worked for me is calling 

`conan install . -e env_key = env_value `

but actually I want to do this inside conanfile.py, from my readings I find out that I should add the logic regarding this inside package_info(self):

`self.env_info.env_key=env_value`

but after calling conan install . I do not have this environment  variable inside  environment.sh.env  file, actually , package_info() is not being called at all.

I tried also 

`conan install -g virtualenv`

but didn't work 
I found other issues talking about this:
https://github.com/conan-io/conan/issues/2882

but no solution provided 

also this issue 

https://github.com/conan-io/conan/issues/4493

and they mentioned in it the following:

> package_info() is called, but only in the dependency packages

but to be honest I didn't exactly get what they mean ..

So, what is the correct way to set the environment variable from conanfile.py 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @YaminoYuki 

I think there is a small misunderstanding: The ``package_info()`` contents is NOT used in the current ``conanfile.py``. It is only used in the consumers of that conanfile, other packages that contains a ``requires`` to this package.

If you want to activate an environment variable directly in your conanfile, you can do it in several ways:
- You can set the ``os.environ`` in python, before calling what you need (make sure to clean it after using it)
- You can directly define it in command line, something like ``self.run("export MYVAR=MYVALUE && my command")`` for linux systems.

If you can do it, providing a minimal, complete ``conanfile.py`` that illustrate what you want to achieve, together with the commands, that could clarify better your intention.

**Comment by YaminoYuki** [comment]
Thank you @memsharded  for answering my question, I am very new to conan and I believe that I have misunderstood many things ..  your idea has worked ..but still I want the variable that I have set to be in environment.sh.env .. how can I do that? 
also regarding os.environ why do I need to clear it ?

**Comment by memsharded** [comment]
- ``os.environ``, if you set it, it will remain set, polluting the environment of all recipes, all packages, dependencies, etc. Maybe it is not used by other packages, but better not take the risk. In general this would be a dirty approach.
- You cannot modify the ``environment.sh.env`` from the same recipe, it is not doable, that file is strictly generated from dependencies.

If you want to explore the bleeding edge features, we are creating a new environment model and tools for Conan, so far it is looking great, more powerful and flexible: https://docs.conan.io/en/latest/reference/conanfile/tools/env/environment.html (take it as experimental). Some ideas:

- You can use the ``generate()`` method to create any files you want for your build.
- You can explicitly use an ``Environment()`` object to create these files. These files are also composed in a single one for convenience.
- You can activate its usage with ``self.run(...., env=["conanbuildenv"])`` (or the filename containing the script to be used for environment).
- Profiles contain new ``[buildenv]`` to define environment for the ``conanbuildenv.sh/bat`` scripts

It is very new, and probably documentation is still scarce, but we will continue to invest in this model.

**Comment by YaminoYuki** [comment]
@ memsharded  Thank you  very much ...The general idea  now is  clearer for me ,  regarding your suggested ideas ..very interesting ! I need to go through them

**Comment by YaminoYuki** [comment]
@memsharded , I believe that I can also solve this by creating new profile with [env] correct ?
