### ISSUE TITLE
[question] With `CMakeDeps` and `CMakeToolchain`, the original project still have to be modified

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9555]
find and use rapidjson in native project
```cmake
find_package(RapidJSON REQUIRED)
...
target_include_directories(${PROJECT_NAME} PRIVATE ${RAPIDJSON_INCLUDE_DIRS})
```

for conan, `find_package(RapidJSON REQUIRED)` works, but `${RAPIDJSON_INCLUDE_DIRS}` is empty,
`target_link_libraries(${PROJECT_NAME} RapidJSON::RapidJSON)` works.

So the original project still needs to be modified, doesn't it?

## Example

`CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.20.0)

project(test_conan
        VERSION 1.0
        LANGUAGES CXX)

find_package(RapidJSON REQUIRED)
message${RAPIDJSON_INCLUDE_DIRS})

SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(${PROJECT_NAME} main.cpp)

target_link_libraries(${PROJECT_NAME} RapidJSON::RapidJSON)
```

`main.cpp`
```cpp
#include <iostream>


int main(int argc, char** argv)
{
    std::cout << "aaa" << std::endl;
    return 0;
}
```

`conanfile.txt`
```
[requires]
rapidjson/cci.20200410

[generators]
CMakeDeps
CMakeToolchain
```

configure
```shell
$ mkdir conan && cd conan && install .. && cd ..
$ mkdir out && cd out
$ cmake .. -DCMAKE_TOOLCHAIN_FILE=conan/conan_toolchain.cmake ...
```

**Comment by memsharded** [comment]
Hi @playgithub 

Yes, the integration works transparently if **modern** cmake is being used. So ``target_link_libraries(${PROJECT_NAME} RapidJSON::RapidJSON)`` works, but using bare variables doesn't. It is basically impossible to make it work transparently for every project if such projects do not follow common practices in CMake.

**Comment by playgithub** [comment]
OK, it's clear enough, thanks.
