### ISSUE TITLE
[bug] AWS CPP SDK (aws-sdk-cpp/1.8.130) build is corrupted 

### ISSUE THREAD

**Issue by lalit-g-deepr** [conan-io/conan#9557]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: 19.16.27035.0 MSVC
  * Conan version: 1.33.1
  * Python version: 3.7.1

### Steps to reproduce (Include if Applicable)
When I am using this conanfile.txt for getting aws libs of shared version I am getting error 
C:\.conan\ac901c\1\source_subfolder\aws-cpp-sdk-core\include\aws/core/utils/memory/stl/AWSAllocator.h(53): error C2220: warning treated as error - no 'object' file generated (compiling source file C:\.conan\ac901c\1\source_subfolder\aws-cpp-sdk-core\source\utils\TempFile.cpp) [C:\.conan\ac901c\1\source_subfolder\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]

When I am using conanfile.txt for getting aws libs of static version. In executable there is linking error
error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl Aws::SQS::Model::SendMessageRequest::SetMessageGroupId(char const *)" (__imp_?SetMessageGroupId@SendMessageRequest@Model@SQS@Aws@@QEAAXPEBD@Z) referenced in function "public: class CMS::EC::ErrorCode __cdecl CMS::CMSConnector::AwsConnector::AwsConnector::sendFifoQueueMessage(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?sendFifoQueueMessage@AwsConnector@1CMSConnector@CMS@@QEAA?AVErrorCode@EC@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z)

command:
conan install .. --profile=../winprofile.txt --build=missing -s build_type=Debug -s compiler.runtime=MDd

conanfile.txt
------------------------------------------
[requires]
aws-sdk-cpp/1.8.130

[generators]
cmake

[options]
aws-sdk-cpp:shared=True
aws-sdk-cpp:lambda=True
aws-sdk-cpp:sns=True
aws-sdk-cpp:sqs=True

winprofile.txt
-----------------------------------
[settings]
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
compiler.cppstd=17
compiler.toolset=v141
os=Windows
os_build=Windows

[options]

[build_requires]

[env]
CC=cl.exe
CXX=cl.exe

**Comment by lalit-g-deepr** [comment]
I found a work around for this issue. I tweaked environment variable to suppress that particular warning. The update winprofile with cl variable is solution for me. 

[settings]
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
compiler.cppstd=17
compiler.toolset=v141
os=Windows
os_build=Windows

[options]

[build_requires]

[env]
CC=cl.exe
CXX=cl.exe
CL=-D_SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING

**Comment by memsharded** [comment]
Thanks for reporting your solution @lalit-g-deepr 

However, it would be great if @SSE4 or @uilianries could have a look, maybe it is something that could be improved in the ConanCenter recipe?

**Comment by lalit-g-deepr** [comment]
Thanks @memsharded

**Comment by SSE4** [comment]
it might make sense to either disable `treat warnings as errors` in recipe, or adding `_SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING` definition, since AWS SDK uses deprecated allocator members.

**Comment by SSE4** [comment]
@memsharded issue must be closed. there is no problem in the conan client, only malfunction in recipe.

**Comment by jgsogo** [comment]
I've added the _closes_ keyword to the PR description.

**Comment by jgsogo** [comment]
@lalit-g-deepr , can you check/review the proposed fix for the recipe? https://github.com/conan-io/conan-center-index/pull/7287 
Thanks!

**Comment by lalit-g-deepr** [comment]
@jgsogo I have checked the proposed fix and I approve it. You can close the issue.
