### ISSUE TITLE
[bug] [lockfiles] Option values set by consumers are ignored in some cases

### ISSUE THREAD

**Issue by sduerr** [conan-io/conan#9558]
When a consumer of a build requirement changes the options of its build requirement, Conan does not build the build requirement and exits with an error.

The profile defines:

    [options]
    buildReqA:shared=True

The consumer recipe has:

    def configure(self):
        self.options["buildReqA"].shared=False

When building the buildReqA through the consumer, and build policy `missing`, Conan is able to handle this correctly. However, it does not work if buildReqA is build in an extra command.

See the referenced example for details.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: n/a
  * Conan version: 1.40.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
Find an example in https://github.com/sduerr/conan_options.git

### Logs (Executed commands with output) (Include/Attach if Applicable)

Conan output: 

    ERROR: buildReqA/0.1: Locked options do not match computed options
    Locked options:
    fPIC=True
    shared=False
    Computed options:
    fPIC=True
    shared=True

**Comment by sduerr** [comment]
Any ideas here?

**Comment by franramirez688** [comment]
Thanks for reporting the issue @sduerr 

I'm not sure about it's a bug or a kind of misunderstanding with the use of lock files in Conan.
I think we need @memsharded help to answer your issue.

**Comment by franramirez688** [comment]
I have added only the `[lockfiles]` context to the title to keep it clear that it's related to Conan lock files 😁

**Comment by memsharded** [comment]
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
