### ISSUE TITLE
If patch file fails to be parsed a very confusing message is outputted

### ISSUE THREAD

**Issue by tru** [conan-io/conan#956]
If you use `tools.patch()` with a patch file that is not parsed correctly by patch module conan will try to call `.apply()` on `False` here: https://github.com/conan-io/conan/blob/develop/conans/tools.py#L219

it's because from_file() returns false on error. That error should probably be guarded.

**Comment by memsharded** [comment]
Actually this has not been released, right? If not, it should be left opened, fixed. Adding milestone 0.20, it will be released then.

**Comment by tru** [comment]
Oh that's right. Sorry.
