### ISSUE TITLE
[question] How does `conan` solve version conflicting?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9581]
e.g.

*  Only shared libs are allowed
* `AppA` depnds on `LibA` and `LibB`
* `LibA` depends on `zlib 1.9`
* `LibB` depends on `zlib 2.0`

The problem is generally AppA is unable to link to both `zlib 1.9 (shared)` and `zlib 2.0 (shared)`.
Does it mean I have to upgrade conan recipe of `LibA` to support `zlib 2.0` or override lib version in `conanfile.txt`?
I think it's not convenient for the user to maintain version consistency among many libs, any solution?

**Comment by memsharded** [comment]
This is not a Conan problem
You cannot link an AppA that transitively depends on 2 different versions of the same shared library. This is not how shared libraries work. Yes, you need to update the source code of LibA to support zlib/2.0 if it is not compatible, and then you can use Conan to solve the conflict downstream. If you would like to read more about how Conan can address version conflicts **resolving to the same version when there are conflicts**, then you want to read: https://docs.conan.io/en/latest/versioning/introduction.html#version-and-configuration-conflicts
