### ISSUE TITLE
[question] Can `conan` generate a file structure like that in *nix?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9582]
i.e.
* <prefix>/inlcude
* <prefix>/lib
* <prefix>/bin
* <prefix>/share

With the libs aggregated, benefints:
* easy to be referenced by any build system
* version consistency made explicit
* conan is decoupled from the consuming project

**Comment by puetzk** [comment]
See the [conanfile [imports] section](https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports), and perhaps also [the deploy generator](https://docs.conan.io/en/latest/reference/generators/deploy.html).

But this would be a fairly atypical way to use conan, since you'd be losing all the information from the depenencies package_info, so it would only handle the "traditional unix library" where there's nothing going on except the include and lib paths.

**Comment by memsharded** [comment]
Besides you can lose more information in other situations:

- There are dependency graphs when you can have 2 different versions of the same library (yes, this is now nice, but it happens in real life)
- There are dependency graphs when you can have 2 different variants of the same library (like static/shared), and would be used differently from different consuming packages.
- You cannot handle multi-configuration tools like VS, in which you can switch between Debug and Release in the same project (packages would be forced to do tricky things like rename artifacts to always use a _d suffix or something, but that is very unexpected in linux environments.

If you still want it, the ``imports`` is the feature you are looking for, but note that all the other information generated by conan, including compiler flags, preprocessor definitions, etc, are lost, and that can make correctly consuming what is there more challenging that you would expect.

**Comment by playgithub** [comment]
@puetzk 
> But this would be a fairly atypical way to use conan, since you'd be losing all the information from the depenencies package_info, so it would only handle the "traditional unix library" where there's nothing going on except the include and lib paths.

Is the info from `package_info` critical?
As far as I can see, the way of "traditional unix library" works well.

@memsharded 
> There are dependency graphs when you can have 2 different versions of the same library (yes, this is now nice, but it happens in real life)

Do you mean, e.g. `AppA` can link to `zlib 1.9 (shared)` and `zlib 2.0 (shared)` simultaneously?

> You cannot handle multi-configuration tools like VS, in which you can switch between Debug and Release in the same project (packages would be forced to do tricky things like rename artifacts to always use a _d suffix or something, but that is very unexpected in linux environments.

In *nix, different build types are compatible when linking, usually linking to a release version, when it needs debugging, replace it to a debug version. It's just the unix style, one at a time.

> all the other information generated by conan, including compiler flags, preprocessor definitions, etc, are lost

Is this fnformation critical?
I think for a built lib, compiler flags and preprocessor definitions for building the lib is not useful.
Some libs need preprocessor definitions for using, but it should be documented.
However for some libs, the preprocessor definitions for using are fixed instead of options, in these cases it's better for conan to encapsulate it.

For summary, I can see `conan` can't be decoupled from the consuming projects now.

**Comment by playgithub** [comment]
I have recognized that the best way to use `conan` is to port every lib in using to `conan` with a repice.
