### ISSUE TITLE
[feature] Ignore line endings when calculating checksums

### ISSUE THREAD

**Issue by SuTanTank** [conan-io/conan#9588]
I'm using Conan 1.39.0

I manage the recipes in a git repository and just found out that running ```conan create``` with same recipe file on different os (Windows and macOS) will generate two version of recipes and ```conan upload``` will always make the previous uploaded package outdated. I guess it's because of the line endings difference? 

I'm not familiar with the checksum and not sure how conan determine if a recipe is updated.  I used mac's ```md5``` and windows's ```get-filehash``` and the same recipe file in the same git commit did generate different MD5. 

I can use ```conan download``` and ```install``` to get the remote recipe and build and upload the package, which maybe count as a workaround. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by sboehmann** [comment]
Hi @SuTanTank 

IMO the files are different, so the checksum must be different too.

But there is a simple solution. Create a file in the root directory of the git repository with the name `.gitattributes` and the content:
```
* text=auto eol=lf
```

See also: https://git-scm.com/docs/gitattributes

**Comment by SuTanTank** [comment]
Ah Yes, I saw how conan-center-index handles it. Thanks.

**Comment by memsharded** [comment]
Yes, exactly what @sboehmann said. Specially with some C/C++ build systems, in which blank space, tabs, etc is significant, keeping exactly the original line endings is sometimes important, and if the hash discards them, when some change tries to correct a previous error, it will be systematically (and being confusing for users too) discarded as "nothing changed".
