### ISSUE TITLE
Conan Upload does not take port into account on upload command

### ISSUE THREAD

**Issue by EMCP** [conan-io/conan#9589]
### Environment Details (include every applicable attribute)
  * Operating System+version: `ubuntu 20.04 LTS`
  * Compiler+version: `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`
  * Conan version: `Conan version 1.40.0`
  * Python version: `Python 3.9.6`

### Steps to reproduce (Include if Applicable)

deploy a JFrom Artifactory CE somewhere on LAN, and attempt to add it as a remote via conan CLI

```
conan remote add juju_artifactory_ce http://10.2.1.20:8081/artifactory/api/conan/dev_reg
```

now build a recipe and try to upload it to this new remote.. it will fail and clearly shows it's attempting to use port 80 despite being fed 8081.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
 conan upload "*" --remote=juju_artifactory_ce --all --confirm 
Uploading to remote 'juju_artifactory_ce':
Uploading bison/3.7.1 to remote 'juju_artifactory_ce'                                    
ERROR: 
Error uploading file: conan_export.tgz, 'HTTPConnectionPool(host='10.2.1.20', port=80): Max retries exceeded with url: /artifactory/api/conan/dev_tws/v1/files/_/bison/3.7.1/_/0/export/conan_export.tgz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f286bf05880>: Failed to establish a new connection: [Errno 111] Connection refused'))'
ERROR: 
Error uploading file: conan_sources.tgz, 'HTTPConnectionPool(host='10.2.1.20', port=80): Max retries exceeded with url: /artifactory/api/conan/dev_tws/v1/files/_/bison/3.7.1/_/0/export/conan_sources.tgz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f286bf9a1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))'
ERROR: 

```

**Comment by EMCP** [comment]
rtrying with `ssl_verify` set to False does not fix this issue either

**Comment by memsharded** [comment]
Hi @EMCP 

Is it possible that there is a redirection or something in the server side? Also, is the above URL the one shown by the Artifactory ``SetMeUp`` button?

A quick way to discard a Conan client issue would be to locally download in your computer an ArtifactoryCE, the zip download, unzip, launch manually the server, then setup a Conan repo and SetMeUp.

**Comment by EMCP** [comment]
Hi @memsharded ,

I'd deployed the artifactory Community edition stock.. and installed this simply with a tool called Juju on top of LXD.  Also this is the string that I am being told to setup.. maybe there's some stock direction but.. I can visit the URL myself in browser and it seems to be empty but prompts for credentials as you'd expect.

I'd run it like this in past but.. don't recall this behavior 

when it sets the server name.. I simply put the ip like `http://10.2.1.20` .. perhaps I needed to add the port ?

**Comment by memsharded** [comment]
Hi @EMCP 

Yes, I think this is something that is configuration of the server side, if that didn't work we would be flooded with tickets :) 
I have checked the source code and can't find anything client side that could be causing that change from the SetMeUp URL using port 8081 to port 80, so I guess it should be something while setting up the server. Sorry I don't know about Juju on top of LXD, not sure how to debug this issue, is it possible that Juju changed something in a recent release? I think I'd still start with a non-installed ARtifactoryCE, just the unzip one, to rule out other possible issues, and be 100% it is server side configuration.

**Comment by EMCP** [comment]
it seems gitlab comes with it's own server which IS working.. I close this ticket for now and if I need Artifactory CE again I will review my setup once more

juju is just a orchestrator.. I wrote the charm (scripts) which instantiate artifactory CE myself so.. nothing there.. it's likely this IP setup needing the port to be in the name when you init the server setup

thank you @memsharded
