### ISSUE TITLE
[question] How to find out the name of the package to be tested in test_package?

### ISSUE THREAD

**Issue by sboehmann** [conan-io/conan#9606]
In a `test_package` I can access all dependencies via `self.deps_cpp_info`, but is there any way I can determine which one is the subject under test?

**Comment by sboehmann** [comment]
Oh, I have found a solution!

Looks like I can get the name from `self.display_name`. Something like `self.display_name.split("/")[0]`.

Is this a good _(and stable)_ way to go?

**Comment by memsharded** [comment]
It seems that ``display_name`` is not documented, so it wouldn't be stable.

Why would you have more than 1 require in a ``test_package``? Maybe a ``build_require`` would make sense, but more than 1 ``require``, it would be good to know what is the use case. And why a ``test_package`` doesn't know the name of the package that is testing? As it needs to write code specific for the thing that is testing, it seems that it will always know which package is testing.

**Comment by sboehmann** [comment]
In many cases the `test_package/conanfile.py` looks like this _(this one is from conan-center-index)_:

```
import os
from conans import ConanFile, CMake, tools

class TestPackageConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake_find_package", "cmake"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def test(self):
        if not tools.cross_building(self.settings):
            bin_path = os.path.join("bin","test_package")
            self.run(bin_path, run_environment=True)
```

This code itself does not know the name of the package under test. However, in our case, our `test_package` does a bit more than that. So to avoid copying and duplicating this code everywhere we use a common base class _(via python_requires)_.

But now I wanted to know which package I am testing right now _(inside the common base class)_. `self.deps_cpp_info` doesn't help, since it contains also the indirect dependencies _(if B depends on A and I'm testing B it contains A and B)_.

**Comment by memsharded** [comment]
This will be solved by https://github.com/conan-io/conan/issues/10073, instead of injecting a ``require``, the reference of the tested package will be injected. Then it will be explicit to define the ``require`` and it will be obvious to get the name of the package being tested.
