### ISSUE TITLE
[question] `CMakeDeps` failed on header only libs

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9609]
conanfile.py
```python
requires = ["rapidjson/cci.20200410"]
generators = ["CMakeDeps", "CMakeToolchain"]
```

```shell
$ conan create .
...
ERROR: Error in generator 'CMakeDeps': 'settings.build_type' doesn't exist
```

Does it mean that `CMakeDeps` can not be used if any lib in `requires` has no `build_type` settings?

conafile.py for rapidjson
```python
from conans import ConanFile, tools
import os

required_conan_version = ">=1.33.0"


class RapidjsonConan(ConanFile):
    name = "rapidjson"
    description = "A fast JSON parser/generator for C++ with both SAX/DOM style API"
    topics = ("conan", "rapidjson", "json", "parser", "generator")
    url = "https://github.com/conan-io/conan-center-index"
    homepage = "http://rapidjson.org"
    license = "MIT"
    no_copy_source = True

    @property
    def _source_subfolder(self):
        return "source_subfolder"

    def source(self):
       tools.get(**self.conan_data["sources"][self.version], strip_root=True, destination=self._source_subfolder)

    def package(self):
        self.copy(pattern="license.txt", dst="licenses", src=self._source_subfolder)
        self.copy(pattern="*", dst="include", src=os.path.join(self._source_subfolder, "include"))

    def package_id(self):
        self.info.header_only()

    def package_info(self):
        self.cpp_info.names["cmake_find_package"] = "RapidJSON"
        self.cpp_info.names["cmake_find_package_multi"] = "RapidJSON"
```

**Comment by czoido** [comment]
Hi @playgithub,

I think that you probably removed the `build_type` settings in your consumer conanfile (the one that requires rapidjson). So probably you are missing a line like this: `settings = "os", "compiler", "build_type", "arch"` in the consumer conanfile.
Please check the documentation for more info: https://docs.conan.io/en/latest/mastering/conanfile_py.html
Hope this helps.

**Comment by playgithub** [comment]
- my lib is header only
- rapidjson has no setting for "build_type"

**Comment by czoido** [comment]
> * my lib is header only
> * rapidjson has no setting for "build_type"

Hi, the problem is not in the library's conanfile, it's in the consumer's conanfile. Please can you paste your consumer conanfile here? It's the one that has the rapidjson requirement.

**Comment by playgithub** [comment]
```py
from conans import ConanFile, CMake, tools

class CppjiebaConan(ConanFile):
    name = "cppjieba"
    version = "2.0.0"
    license = "MIT"
    requires = ["rapidjson/cci.20200410"]
    exports_sources = ["CMakeLists.txt"]
    generators = "cmake_find_package"
    
    __source_subfolder = "source_subfolder"
    __build_subfolder = "build_subfolder"

    def source(self):
        git = tools.Git(folder = self.__source_subfolder)
        git.clone("/url/to/cppjieba.git", "master")

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder = self.__source_subfolder,
                        build_folder = self.__build_subfolder,
                        defs = {"CMAKE_MODULE_PATH": "C:/Users/aaa/.conan/data/cppjieba/2.0.0/_/_/build/c70d8a94b14bc249994db519e8564740c87254a1"})

    def package(self):
        cmake = CMake(self)
        cmake.install(build_dir = self.__build_subfolder)

    def package_info(self):
        self.cpp_info.includedirs = ["include"]
```

**Comment by czoido** [comment]
Hi @playgithub,
As I said, you have to add at least the `build_type` setting to the conanfile.  The `CMakeDeps` generator needs that setting information. So please add: `settings = "build_type"` to the consumer's conanfile like this:

```
class CppjiebaConan(ConanFile):
    settings = "build_type"
    ...
```

Some other conan generators may not need this setting.

**Comment by playgithub** [comment]
The error is fixed.
BTW another error occurs #9611

**Comment by playgithub** [comment]
But why a header only lib needs `settings = "build_type"`, this will lead to duplication of the lib in local conan cache unnecessarily, right?

BTW, after fixing #9611, I have tried to delete `settings = "build_type"` and do `conan create .`, it succeeds.
It is not necessary, isn't it?

**Comment by czoido** [comment]
> But why a header only lib needs `settings = "build_type"`, this will lead to duplication of the lib in local conan cache unnecessarily, right?
> 

The lib will not be duplicated because it does not have the build_type setting, it's deleted because it's a header only and will have only one package_id, please read more about this here: https://docs.conan.io/en/latest/howtos/header_only.html

> BTW, after fixing #9611, I have tried to delete `settings = "build_type"` and do `conan create .`, it succeeds.
> It is not necessary, isn't it?

That's because you are using cmake_find_package generator there and will not need it.

**Comment by playgithub** [comment]
> The lib will not be duplicated because it does not have the build_type setting, it's deleted because it's a header only and will have only one package_id, please read more about this here: https://docs.conan.io/en/latest/howtos/header_only.html

Fine

> That's because you are using cmake_find_package generator there and will not need it.

Alright

Thanks
