### ISSUE TITLE
[question] Managing your own dependencies

### ISSUE THREAD

**Issue by Belpaire** [conan-io/conan#9610]
Hi,

I've been wondering how we should handle cascading dependencies? Say for example I have a package A with version 1.0 and B with version 1.0 with a dependency to package A with version 1.0.

Some projects only rely on A and some also use B.
Let's say I upgrade A, to version 1.1, and want to use it in the project, I would need to create a new package for B to also depend on 1.1 (and eventually all packages depending on B if B was recreated). 

Am I right that this is how it should be done?

kind regards,

**Comment by lasote** [comment]
Hi,

How to manage the versions really depends... some users upgrade by hand the versions, some others do not bump ever a version and rely on revisions, other use version ranges...

You can read more information about versioning here: https://docs.conan.io/en/latest/versioning.html

**Comment by Belpaire** [comment]
Question answered so I'll close the issue here.
