### ISSUE TITLE
[question] `cmake.configure` failed but `the output scripts` run successfully in terminal

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9611]
conanfile.py
```py
from conans import ConanFile, CMake, tools

class CppjiebaConan(ConanFile):
    name = "cppjieba"
    version = "2.0.0"
    license = "MIT"
    requires = ["rapidjson/cci.20200410"]
    exports_sources = ["CMakeLists.txt"]
    generators = "cmake_find_package"
    
    __source_subfolder = "source_subfolder"
    __build_subfolder = "build_subfolder"

    def source(self):
        git = tools.Git(folder = self.__source_subfolder)
        git.clone("/url/to/cppjieba.git", "master")

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder = self.__source_subfolder,
                        build_folder = self.__build_subfolder,
                        defs = {"CMAKE_MODULE_PATH": "C:/Users/aaa/.conan/data/cppjieba/2.0.0/_/_/build/c70d8a94b14bc249994db519e8564740c87254a1"})

    def package(self):
        cmake = CMake(self)
        cmake.install(build_dir = self.__build_subfolder)

    def package_info(self):
        self.cpp_info.includedirs = ["include"]
```

`cmake.configure` failed and output the scripts that failed, I copy the scripts to terminal and run, it succeeds.

Error Message
```
ConanException: Error 1 while executing <the scripts>
```

How to fix `conanfile.py`?

**Comment by czoido** [comment]
Hi @playgithub,
Please, we need more information to reproduce the issue. The series of commands you are executing, reproducible recipes, etc...
Thanks!

**Comment by playgithub** [comment]
The lib is private now.
If the problem is not obvious, I'll try to debug it.

To clarify the case:
The scripts generated by `cmake.configure` can run successfully by manually copying into a terminal.
But `cmake.configure` in `conanfile.py` failed.

**Comment by czoido** [comment]
Hi @playgithub,
Maybe some error logs of the fail would help...

**Comment by playgithub** [comment]
Run in `conanfile.py` failed, the error log is
```shell
ConanException: Error 1 while executing <the scripts>
````
I have search the build folder in conan local cache, no log, in fact the folder is empty.

`<the scripts>` here is what runs successfully in terminal , so no error log.

**Comment by playgithub** [comment]
Hi @czoido 

I have found the reason.
Because I open the conan recipe in vscode before installing `cmake`, so `cmake` can't be found in vscode integrated terminal.
