### ISSUE TITLE
[question] What's the better practice for source folder and build folder?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9613]
By defulat, e.g.
- source folder path: `liba/version/_/_/source`
- build folder path: `liba/version/_/_/build/<hash>`

`conan` will clone source  into `liba/version/_/_/build/<hash>`, so the source will be mixed with the build output in this folder. Questions:
- Why another copy of source?
- Is it good to mix the copy of source with build output? Or it's better to seprate source folder and build folder, e.g.
  ```cmake
  git = tools.Git(folder = "some_source_folder")
  ...
  cmake.configure(source_folder = "some_source_folder", build_folder = "some_build_folder")
  ```

**Comment by czoido** [comment]
Hi @playgithub,
The copy is necessary to store a clean copy of the sources for later use to build different packages with different options. Please read the docs for more info: https://docs.conan.io/en/latest/reference/conanfile/methods.html#source
The source_folder is just CMake’s source directory where CMakeLists.txt is located and build_folder is where you want CMake to output the build. Please read more about this here: https://docs.conan.io/en/latest/reference/build_helpers/cmake.html
Hope this helps

**Comment by playgithub** [comment]
`liba/version/_/_/build/<hash>` contain files for both source and build output, and by default they are mixed, is it expected?

**Comment by czoido** [comment]
> `liba/version/_/_/build/<hash>` contain files for both source and build output, and by default they are mixed, is it expected?

Yes, totally expected

**Comment by playgithub** [comment]
OK, thanks.
