### ISSUE TITLE
[bug] 'settings.yml is locally modified, can't be updated' every time I upgrade

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#9614]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 11.5.2, Windows 10 21H1
  * Compiler+version: AppleClang 12, MSVC 19.29.30133.0 (VS2019)
  * Conan version: 1.40.1
  * Python version: Python 3.9.7

### Steps to reproduce (Include if Applicable)
Run:
```
pip3 install conan --upgrade
conan --version
```

I get this warning:
```
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: /Users/steve/.conan/settings.yml.new
WARN: ****************************************
```

I'm not making any changes to this file so I would not expect Conan to consider it locally modified. It used to never happen, but has happened on every release recently. I haven't experienced any downstream impacts, though I usually move settings.yml.new to settings.yml manually just to make sure I have the latest.

**Comment by czoido** [comment]
Hi @ssrobins,
Thanks a lot for reporting.
This should not happen. I think there's some newline in the ___init__.py_ with the default settings or in the _migrations_settings.py_ that's making the comparison fail.
I'll mark this for the next release to be solved.
