### ISSUE TITLE
[question] How to contorl the `build_type` of an indirect dependency?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9617]
For example

`LibA` depends on `zlib (static)`  by default

`conanfile.txt` for `AppA`
```
[requires]
LibA/1.0
[options]
LibA:shared=True
```

What `build_type` of `zlib` will be used by default in the case?
How to control the `build_type` of `zlib` in the case?

**Comment by czoido** [comment]
Hi @playgithub,
The `build_type` used by default is the one of the **default profile** if you don't specify a profile in the command or the setting via an argument. You can read more about [profiles](https://docs.conan.io/en/latest/reference/profiles.html#profiles) and the [default profile](https://docs.conan.io/en/latest/reference/config_files/default_profile.html) in the docs.
If you want to [override the default for libA](https://docs.conan.io/en/latest/faq/using.html#when-to-use-settings-or-options) you can do something like: `conan install .... -s libA:build_type=Release`

**Comment by playgithub** [comment]
Sorry, I've edited the issue, it's about `zlib` in the case, which is an indirect dependecy.

**Comment by czoido** [comment]
It's exactly the same for zlib. Just use `conan install .... -s zlib:build_type=Release`

**Comment by playgithub** [comment]
OK, thank.
I think that explicit settings for an implicitly dependent is a little uneasy to maintain.
