### ISSUE TITLE
[question] How to install a lib when its depencencies are in a different remote server?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9618]
```shell
$ conan install wxwidgets/3.1.5@bincrafters/stable --build -r bc
..
ERROR: Failed requirement 'libpng/1.6.37' from 'wxwidgets/3.1.5@bincrafters/stable'
ERROR: libpng/1.6.37 was not found in remote 'bc'
```
bc = bincrafters

`conancetner` has `libpng/1.6.37`, but  it seems that `conan install` does't support two remotes at the same time.
Do I have to install the dependencies of `wxwidgets` manually?

**Comment by sourcedelica** [comment]
When you use `-r bc` on the install command it will use it for every package that it installs, even dependencies.

First install the dependencies from `conancenter`.  Then install `wxwidgets` from `bc`.

**Comment by czoido** [comment]
Hi @playgithub,
@sourcedelica is right, if you specify a remote in the command line it will **only** take packages from that remote.
You can install libpng from conancenter first or If you don't specify the remote it will look through the different remotes searching for valid requirements as well. So just `conan install wxwidgets/3.1.5@bincrafters/stable` should work

**Comment by playgithub** [comment]
But failed
```
λ conan install wxwidgets/3.1.5@bincrafters/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

libpng/1.6.37: Not found in local cache, looking in remotes...
libpng/1.6.37: Trying with 'cc'...
ERROR: Failed requirement 'libpng/1.6.37' from 'wxwidgets/3.1.5@bincrafters/stable'
ERROR: check_hostname requires server_hostname. [Remote: cc]
```

remotes.json
```json
{
 "remotes": [
  {
   "name": "cc",
   "url": "https://center.conan.io",
   "verify_ssl": true
  },
  {
   "name": "bc",
   "url": "https://bincrafters.jfrog.io/artifactory/api/conan/public-conan",
   "verify_ssl": true
  }
 ]
}
```
