### ISSUE TITLE
Allow starting with python -m conan

### ISSUE THREAD

**Issue by DariusL** [conan-io/conan#962]
We have a problem on our CI that paths are pretty long, so some python utilities run into shebang length limits under virtualenv. In virtualenv `/venv/bin/conan` starts with `#!/home/ubuntu/jenkins/workspace/branchname-7CV5LE2OU4PGM5LUHE5J2N6DPZ5QGCJQRJJJJJHF3U6VUXG723LQ/venv/bin/conan` which exceeds the limit.

For pip the workaround was `python -m pip` instead of `pip`. Could the same be implemented for conan? We'll likely be invoking conan from python, so other workarounds are welcome too. Right now I just installed conan outside virtualenv.

**Comment by memsharded** [comment]
If you  mean that you will be using it from python scripts, it might be very easy, the entry point of the app is : https://github.com/conan-io/conan/blob/develop/conans/conan.py 

This is what we use to run from sources: https://github.com/conan-io/conan#create-a-launcher

Does it make sense?

For the ``-m`` switch, no idea how to implement it, I am having a look, pointers welcome.

**Comment by memsharded** [comment]
It is a package namespace, I have tried running from a virtualenv:
```bash
$ python -m conans.conan remote list
```
and it works

**Comment by DariusL** [comment]
Thanks, `python -m conans.conan` worked.
