### ISSUE TITLE
[bug] Unhelpful error message about conflicting package versions between requires and build_requires

### ISSUE THREAD

**Issue by martin-schulze-vireso** [conan-io/conan#9626]
Having conflicting version overrides for the same package in build_requires and requires results in the following output: `ERROR: True`. This makes the error hard to find. The error message should be more helpful on what is going wrong.

#4753 might be related.

### Environment Details (include every applicable attribute)
  * Operating System+version: Arch Linux Kernel 5.12.12
  * Conan version: 1.40.0
  * Python version: 3.9.5

### Steps to reproduce (Include if Applicable)
Try to `conan install` this example conanfile.txt:

```
[requires]
libdeflate/1.7
[build_requires]
libdeflate/1.8
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```$ conan install conanfile.txt
Configuration:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
[options]
[build_requires]
[env]

ERROR: True
```

**Comment by lasote** [comment]
Thanks for reporting. I've been able to reproduce it. I'll open a PR with a better error trace.
Just to let you know, if you specify a build profile (`--profile:build=default`) it manages better the build requires and won't cause a conflict. You can activate it by default (as it will be at Conan 2.0) using the [global conf](https://docs.conan.io/en/latest/reference/config_files/global_conf.html) `core:default_build_profile=default` (or any other name). You can read more [here](https://docs.conan.io/en/latest/reference/profiles.html#build-profiles-and-host-profiles)

**Comment by martin-schulze-vireso** [comment]
@lasote Have a look at the linked PR #9624. @memsharded  has already done some coding for this issue!

**Comment by lasote** [comment]
Ouch! sorry I didn't see it. I will close it.

**Comment by martin-schulze-vireso** [comment]
No problem, I just wanted to inform you to avoid duplicating effort.

**Comment by lasote** [comment]
Yeah, we forgot to tag it properly to not collide between us.

**Comment by martin-schulze-vireso** [comment]
To be fair: I opened the PR, hit a CI problem and decided to document the original problem with a reproducer as this issue afterwards. So the process might have been a bit confusing.
