### ISSUE TITLE
[question] Why during packaging conan change symbolic link?

### ISSUE THREAD

**Issue by mo-badreldin** [conan-io/conan#9628]
- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Hello,

I am using Conan (version 1.39.0) to create a package for lib and executable files stored in a git repo. 

my recipe does not include build step and I set the variables
exports_sources = "*"
no_copy_source = True

Before packaging a symbolic link file looked like this on git repo (./gcc/version/libgcc.so)
After packaging the file looks different inside the package ( gcc/version/libgcc.so )

I know they are basically the same thing, but why did Conan introduce changes? my understanding packaging step is only copying content not introducing changes.

**Comment by memsharded** [comment]
When conan packages (in the ``package()`` method), it tries to make symlinks relocatable, because packages must be able to be downloaded and used in another machine. So symlinks are processed to make sure they are converted to relative-path symlinks, not absolute paths (that are common as a result of C, C++ build processes).

**Comment by mo-badreldin** [comment]
Thanks for your prompt and clear reply. 

The symlink before packaging was also using relative path. Is there a way to keep symlink unchanged?

**Comment by memsharded** [comment]
Conan replaced the ``self.copy()`` with ``copy()`` some time ago, that no longer changes the symlinks, and the utility to handle symlinks has been extracted to other helpers.

I think we can close this issue as solved, please create new tickets if necessary for ``copy()``, thanks!
