### ISSUE TITLE
[feature] JSON output file lacks sufficient error details

### ISSUE THREAD

**Issue by t7wakim** [conan-io/conan#9638]
Hello,

I would like to address a limitation of the JSON output option (-j). It seems to lack sufficient information especially when an error is faced. For example, running the following command with no internet connection:

```
conan search -r test-repo -j conan_out test_name/test_version@test_user/test_channel
```

Returns the following on standard error:

```
ERROR: HTTPSConnectionPool(host='...', port=443): Max retries exceeded with url: /artifactory/api/conan/test-repo/v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103c44400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Unable to connect to test-repo=https://.../artifactory/api/conan/test-repo
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

However, in the `conan_out` JSON file, only the following is returned:
```
{
  "error": true,
  "results": []
}
```

This is frustrating when trying to interact with Conan through external subprocess calls (since the API is still unreleased) and reading the JSON file for the command result. Also, the previous JSON output (with `error=True`) also is the case when the package is not found, so there is no way of knowing (using only the JSON output) whether a system error occurred or the package was not found.

Would it be possible to add a field in the JSON output that sheds light onto what the error faced actually was? Parsing standard output and standard error doesn't seem like an elegant solution when interacting with Conan using external scripts/tools.

Thank you,
Thomas

**Comment by franramirez688** [comment]
Hi @t7wakim 

Thanks for reporting the issue.
You're right, Conan is not showing any valuable JSON-format information when an error occurs so it would be fine to solve it.

**Comment by franramirez688** [comment]
Hi @t7wakim 

Several points about this issue:

* For Conan `1.x`, there is not such an easy way to solve this issue. 
* For Conan `2.x`, this problem would be already solved.

I think it's worth waiting for Conan 2.0 and checking if it's working as expected.

**Comment by franramirez688** [comment]
I just checked it in Conan 2.0 (`develop2` branch).
For instance:

```bash
(conan) ➜  conan git:(develop2) conan search -r conancenter poco/1.1.x -f json

[
    {
        "remote": "conancenter",
        "error": "HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10f8b5670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))\n\nUnable to connect to conancenter=https://center.conan.io\n1. Make sure the remote is reachable or,\n2. Disable it by using conan remote disable,\nThen try again.",
        "results": {}
    }
]
```

As you can see, we have removed the `-j json_file` argument, so, now, you'll have to save it manually in a file (e.g. `conan search -r conancenter poco/1.1.x -f json >> my_json_file.json`) but the JSON-like output has a piece of valid error information.
