### ISSUE TITLE
[question] test for the existence of an environment variable

### ISSUE THREAD

**Issue by snailcatcher** [conan-io/conan#9639]
Hi there,

My package is build with the following conanfile

```python
from conans import ConanFile


class Pkg(ConanFile):
    name = "bla"
    version = "3.1"
    ...

    def package_info(self):
        self.env_info.BLA_EXECUTABLE = os.path.join(self.package_folder, "bin", "bla.exe")
```

In my test_package I wrote the following conanfile
 
```python
from conans import ConanFile


class Pkg(ConanFile):

    def test(self):
        self.run("%s -v" % self.env_info.BLA_EXECUTABLE )
```

The error I get

```python
ERROR: bla/3.1 (test package): Error in test() method, line 8
        self.run("%s -v" % self.env_info.BLA_EXECUTABLE)
        AttributeError: 'NoneType' object has no attribute 'BLA_EXECUTABLE'
```

I don't get why I can't access the BLA_EXECUTABLE environment variable this way. What is the correct way of testing if the variable is set?

My goal is to verify the environment variable by running the program BLA_EXECUTABLE is pointing to.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
There are 2 mechanisms, you are using the legacy one, I would probably recommend start having a look to the modern one.

With the legacy, it is purely env-base, the env-var should be set

```python
def test(self):
        self.run("%s -v" % os.getenv("BLA_EXECUTABLE" )
```

If you wanted to access it in raw, you might access it from the ``self.deps_env_info["mydep"].BLA_EXECUTABLE``

With the modern approach, the environment is not activated by default. Read: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html

- "buildenv_info" and "runenv_info" generate environment files, that will be used when executing commands
- Environments can be explicitly activated, something like:

```python
def build(self):
          build_env = VirtualBuildEnv(self).environment()
          self.output.warn("Foo: *{}*".format(build_env["Foo"]))
      
          with build_env.apply():
               # my commands
```

**Comment by snailcatcher** [comment]
Hi @memsharded 
Very interesting answer, thanks a lot!

**Comment by memsharded** [comment]
You are welcome! I'll consider it as responded and close it, but feel free to re-open or create a new ticket for further questions.
