### ISSUE TITLE
[feature] Support for Xcode 13

### ISSUE THREAD

**Issue by janosvitok** [conan-io/conan#9641]
Conan 1.40.1 does not support Xcode 13.0. To fix it, "13.0" must be added to the list of apple_clang versions.

OS: macOS 11.6, Xcode: 13.0m, conan --version: 1.40.1, cc --version: "Apple clang version 13.0.0 (clang-1300.0.29.3)"

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by tolstikh** [comment]
It might be a good idea for the community to watch out for beta releases of XCode, and add support for upcoming XCode versions at that time. This will avoid conan being unusable for the hopefully short time between when Apple pushes out the XCode auto-update, and the community putting in the fix.

That said, I appreciate the work on XCode 13!

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/9643 
This change is already in [Conan 1.40.2](https://github.com/conan-io/conan/releases/tag/1.40.2) released a couple of hours ago
