### ISSUE TITLE
Import fails to actually copy any packages

### ISSUE THREAD

**Issue by barcharcraz** [conan-io/conan#965]
On head the import command does not actually copy any packages to the build directory

**Comment by barcharcraz** [comment]
I'm an idiot and didn't realize conan deletes the imported files

**Comment by memsharded** [comment]
No worries :)
Yes, the problem if conan doesn't delete them (after build) is that they are typically repackaged, which is something not intended, as the artifacts are already in the other package, and importing them is usually just a convenience to avoid playing with paths. The other alternative is accessing the dependency path, like ``self.deps_cpp_info["PackageName"].rootpath``.

If you want to actually repackage the artifacts it is simple, just import them, copy them to another place inside the build folder with ``shutil.copy`` or ``shutil.copytree``, make ``package()`` get them too.
