### ISSUE TITLE
[question] Requirements when installing prebuilt end-user app

### ISSUE THREAD

**Issue by max-ag** [conan-io/conan#9658]
When installing/deploying a statically-linked prebuilt end-user application, Conan still installs all the requirements declared in the recipe. However, in this case, those requirements are not necessary, since everything has already been statically linked in the binary.

Is there a way to conditionally declare different requirements when building vs just installing prebuilt packages, so that I don't install unnecessary dependencies when deploying the app on a server.

Thanks.

**Comment by memsharded** [comment]
Hi @max-ag 

yes, this has already been addressed in the ``develop2`` branch for Conan 2.0. It is too much of a change to be implemented in 1.X, so you would need to wait for it. At the moment, the alternative would be to do some repackaging of the executable in a different package just for deployment purposes.

**Comment by memsharded** [comment]
The 2.0.0-alpha1 is already released with support for this feature:

- The dependency graph will always be computed, it is necessary to know the dependencies versions, etc.
- But not necessary artifacts, like static libs, will not be downloaded, and will not be propagated downstream as linkage requirements either.

So I think this can be closed as implemented, feedback over the 2.0 will be welcome, thanks!
