### ISSUE TITLE
[bug] CMakeDeps generates wrong Catch2Targets.cmake

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#9660]
The following 

```python
import os
import sys
from conans import ConanFile, tools, CMake
from conan.tools.cmake import CMakeDeps
from conans.tools import Version

class BaseLibrary(ConanFile):
  name = "base-library"

  generators = "cmake_find_package_multi"
  default_options = {"fmt:shared": True}
  build_policy = "missing"  # if this package is build by default if missing.
  settings = "os", "compiler", "build_type", "arch"

  _cmake = None

  def requirements(self):
      self.requires("fmt/8.0.1")
      self.requires("catch2/2.13.7")

  def generate(self):
    tc = CMakeDeps(self)
    tc.generate()
```

with `conan install /demo --install-folder /demo/conan --build missing --profile default --profile:build default --settings build_type=Release --settings compiler=clang --settings compiler.version=12 --settings compiler.libcxx=libstdc++`

produces **wrong** CMake Scripts: `Catch2Config.cmake` does

```cmake
# Load the debug and release library finders
include(${CMAKE_CURRENT_LIST_DIR}/Catch2Targets.cmake)
  ^ ##############################################  This line already properly sets Catch2::Catch2 by loading "Catch2-Target-release.cmake"
```

The next lines in  `Catch2Config.cmake`  now **overwrite** the target properties with **non existent values**.

```cmake
# Assign target properties
set_property(TARGET Catch2::Catch2
             PROPERTY INTERFACE_LINK_LIBRARIES
             $<$<CONFIG:Debug>:${Catch2_LIBRARIES_TARGETS_DEBUG}
                                    ${Catch2_LINKER_FLAGS_DEBUG_LIST}>
             $<$<CONFIG:Release>:${Catch2_LIBRARIES_TARGETS_RELEASE}
                                    ${Catch2_LINKER_FLAGS_RELEASE_LIST}>
             $<$<CONFIG:RelWithDebInfo>:${Catch2_LIBRARIES_TARGETS_RELWITHDEBINFO}
                                    ${Catch2_LINKER_FLAGS_RELWITHDEBINFO_LIST}>
             $<$<CONFIG:MinSizeRel>:${Catch2_LIBRARIES_TARGETS_MINSIZEREL}
                                    ${Catch2_LINKER_FLAGS_MINSIZEREL_LIST}>)
```

**Comment by memsharded** [comment]
Please remove first the ``generators = "cmake_find_package_multi"``. ``CMakeDeps`` is there to replace it, cannot live together (not sure if that is the cause, but some filenames might conflict)

**Comment by gabyx** [comment]
Ah thanks.

I got confused about the generate() method. Though its for cmake "generate".

Maybe a warning that CMakeDeps should not be used with other cmake generators?
Thanks for the fast reply!!

**Comment by memsharded** [comment]
Yes, the thing is that we had some similar check some time ago, but we have already removed ``cmake_find_package_[multi]`` generators in ``develop2`` branch, that is where we do most of our development now, and we mainly backport things to 1.X, so it seems that check has been lost in the process.

In any case, we are going to start pushing hard for new generators and Conan 2.0, so this shouldn't be a big issue. Thanks for telling!

**Comment by gabyx** [comment]
I already adopted the CMakeDeps generator. Works pretty good.
I am still struggling to get my head around host and build contexts...

**Comment by memsharded** [comment]
Ok, for the build context, it is important to recall that xxxx-config.cmake are not generated by default, need to be activated at: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#build-context-activated

If you have any specific question for the 2 profiles thing, don't hesitate to create a new issue for it.

**Comment by gabyx** [comment]
Thanks a lto for that hint.
