### ISSUE TITLE
[question] Upload recipe failed, permission denied for user

### ISSUE THREAD

**Issue by retifrav** [conan-io/conan#9664]
### Environment details

  * Operating System+version: Windows 10.0.19042.1237 x64
  * Conan version: 1.40.2
  * Python version: 3.9.7

### Steps to reproduce

Follow the steps from [documentation](https://docs.conan.io/en/latest/uploading_packages/uploading_to_remotes.html):

1. Create some package
2. Start local [conan_server](https://docs.conan.io/en/latest/uploading_packages/running_your_server.html) with default parameters and credentials
3. Add a new remote: `conan remote add my_local_server http://localhost:9300`
4. Try to upload the package: `conan upload myPackage --all -r=my_local_server`

#### conan_server

```
$ conan_server
***********************
Using config: C:\Users\someuser\.conan_server\server.conf
Storage: C:\Users\someuser\.conan_server\data
Public URL: http://localhost:9300/v1
PORT: 9300
***********************
Bottle v0.12.19 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:9300/
Hit Ctrl-C to quit.

127.0.0.1 - - [24/Sep/2021 11:22:42] "GET /v1/ping HTTP/1.1" 200 0
127.0.0.1 - - [24/Sep/2021 11:22:44] "GET /v1/conans/myPackage/0.0.1/_/_/digest HTTP/1.1" 404 0
127.0.0.1 - - [24/Sep/2021 11:22:46] "GET /v1/users/check_credentials HTTP/1.1" 401 19
127.0.0.1 - - [24/Sep/2021 11:22:52] "GET /v1/users/authenticate HTTP/1.1" 200 124
127.0.0.1 - - [24/Sep/2021 11:22:54] "GET /v1/users/check_credentials HTTP/1.1" 200 4
127.0.0.1 - - [24/Sep/2021 11:22:56] "GET /v1/conans/myPackage/0.0.1/_/_ HTTP/1.1" 404 0
127.0.0.1 - - [24/Sep/2021 11:22:58] "POST /v1/conans/myPackage/0.0.1/_/_/upload_urls HTTP/1.1" 403 17
```

#### conan

```
$ conan upload myPackage --all -r=my_local_server
Are you sure you want to upload 'myPackage/0.0.1' to 'my_local_server'? (yes/no): yes
Uploading to remote 'my_local_server':
Uploading myPackage/0.0.1 to remote 'my_local_server'
Please log in to "my_local_server" to perform this action. Execute "conan user" command.
Remote 'my_local_server' username: demo
Please enter a password for "demo" account:
ERROR: myPackage/0.0.1: Upload recipe to 'my_local_server' failed: Permission denied for user: 'demo'. [Remote: my_local_server]

ERROR: Errors uploading some packages
```

```
$ conan user
Current user of remote 'conancenter' set to: 'None' (anonymous)
Current user of remote 'my_local_server' set to: 'demo' [Authenticated]
```

```
$ conan remote list
conancenter: https://center.conan.io [Verify SSL: True]
my_local_server: http://127.0.0.1:9300 [Verify SSL: False]
```

```
$ conan search -r=my_local_server
There are no packages
```

### Additional notes

Aside from local server on Windows I also tested this with a remote server on Linux host, and I got the same error. I could reach the server, I could authenticate, but trying to upload a package fails with the same error (`permission denied for user`).

**Comment by memsharded** [comment]
Hi @retifrav 

You need to check the permissions section in https://docs.conan.io/en/latest/uploading_packages/running_your_server.html#server-configuration

As you are creating packages without user/channel, you won't be able to use that part to check permissions for that specific user, you should create packages using the ``user/channel`` part, or relax the permissions.

And in any case, I'd strongly recommend ArtifactoryCE, it is completely free, faster and more scalable and reliable, with much better permissions control and web UI:

**Comment by retifrav** [comment]
That was it, write permissions! Sorry for wasting your time, I should have read documentation and server config comments more carefully.
I've relaxed the permissions (*set it to `*/*@*/*: *`, just for testing*), and could upload the package successfully.

Sure, most likely I'll be using Artifactory, just wanted something simple for a quick test, and `conan_server` looked like a good candidate.

It's all good now, thank you!

**Comment by memsharded** [comment]
> Sorry for wasting your time, I should have read documentation and server config comments more carefully.

Sure, no problem, happy to help! :) 
Don't hesitate to submit new issues if you have further questions.
