### ISSUE TITLE
Installing an editable package that defines layout() causes files from generators to be placed in source directory

### ISSUE THREAD

**Issue by dphoyes** [conan-io/conan#9666]
### Environment Details
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc 9.3.0
  * Conan version: 1.40.2
  * Python version: 3.8.10

### Steps to reproduce
  * Checkout https://github.com/conan-io/examples.git (9a22bcdbe28b070e171ecd05866acc1eeb5169f6)
  * `cd features/editable/cmake`
  * Modify `say/conanfile.py` like this to define a `layout()` method:

```python
import os
from conans import ConanFile, CMake

class Pkg(ConanFile):
    name = "say"
    version = "0.1"
    settings = "os", "compiler", "arch", "build_type"
    generators = "cmake"
    exports_sources = "src/*"

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder="src")
        cmake.build()

    def package(self):
        LayoutPackager(self).package()

    def layout(self):
        self.folders.source = "."
        self.folders.build = os.path.join("build", str(self.settings.build_type))
        self.folders.generators = os.path.join(self.folders.build, "generators")
        self.folders.package = "package"

        self.cpp.source.includedirs = ["src"]
        self.cpp.build.libdirs = ["lib"]
        self.cpp.build.libs = ["say"]
```

  * Run `./build.sh`

Running `git status` now shows that the files `conanbuildinfo.cmake` and `graph_info.json` have been generated directly inside the `say` directory. This happens when `conan install ..` is run from inside `hello/build`. I would have expected the contents of the source directory to be kept clean, and for the generated files to be placed into either `self.folders.build` or `self.folders.generators`.

Arguably we could just gitignore those files and ignore them, but their presence also seems to cause surprising side-effects. For example, if we now run:

  * `cd say`
  * `conan info .`

we get this error message:

```
ERROR: Missing lockfile in: /home/davhoy01/devel/conan-examples/examples/features/editable/cmake/say/conan.lock
```

Alternatively, if the `say` directory already contained a lockfile but it was created via `conan lock create --base conanfile.py --lockfile-out conan.lock`, we get this error instead:

```
Traceback (most recent call last):
  File "/home/davhoy01/.local/pipx/venvs/conan/lib/python3.8/site-packages/conans/client/command.py", line 2232, in run
    method(args[0][1:])
  File "/home/davhoy01/.local/pipx/venvs/conan/lib/python3.8/site-packages/conans/client/command.py", line 779, in info
    data = self._conan.info(args.path_or_reference,
  File "/home/davhoy01/.local/pipx/venvs/conan/lib/python3.8/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/home/davhoy01/.local/pipx/venvs/conan/lib/python3.8/site-packages/conans/client/conan_api.py", line 746, in info
    reference, graph_info = self._info_args(reference_or_path, install_folder, profile_host,
  File "/home/davhoy01/.local/pipx/venvs/conan/lib/python3.8/site-packages/conans/client/conan_api.py", line 706, in _info_args
    graph_info = get_graph_info(profile_host, profile_build, cwd, install_folder,
  File "/home/davhoy01/.local/pipx/venvs/conan/lib/python3.8/site-packages/conans/client/conan_api.py", line 1547, in get_graph_info
    graph_info.profile_host.process_settings(cache, preprocess=False)
AttributeError: 'NoneType' object has no attribute 'process_settings'

ERROR: 'NoneType' object has no attribute 'process_settings'
```

Manually deleting the generated files works around the problem. However, this has to be done on every install, so it would be ideal if these files weren't created in the first place.

Thanks!

**Comment by memsharded** [comment]
Hi @dphoyes 

The ``layout()`` feature will only fully work with the new integrations, like ``CMakeDeps`` and ``CMakeToolchain`` (and ``CMake from ``conan.tools.cmake``). Legacy ones will probably not fully work, might work in some occasions, but in general, they will not follow the defined layout.

Yes, we need to modernize both the examples and the docs to use the new features, it is a pending task.

**Comment by memsharded** [comment]
I am preparing an upgrade to the docs and the examples in https://github.com/conan-io/examples/pull/94

**Comment by dphoyes** [comment]
Thanks for the updated examples. It seems like the main way it's working around this issue is:

- The `generators` attribute is no-longer overridden, so the only generator is the default one that produces conanbuildinfo.txt
- The install folder for `say` is now the same as its source folder, instead of its build folder. ie. `say/` instead of `say/build/Release/`
- All the files generated by `conan install` are now gitignored. ie. conanbuildinfo.txt, graph_info.json, conan.lock, etc.

If we set `--install-folder` for `say` to somewhere else, I notice that the original problem comes back. Does this mean we always have to set the install folder to the same as the source folder? I imagine this could become unwieldly if more generators were enabled.

Also, I probably should have said before, but my real use case doesn't involve CMake, and is based on SCons instead. Is it reasonable to expect the `layout()` feature to be usable in this case? It seems to be working well except for the issue described above, which seems to exist regardless of the build integration.

**Comment by dphoyes** [comment]
Please can this be reopened? The original issue here was that Conan is generating files in a source directory instead of an install directory, and as explained above, this is still reproducible in the updated example as soon as we configure the install directory to be somewhere different from the source directory.

**Comment by memsharded** [comment]
Hi @dphoyes 

I am not sure what is the issue. With the new ``layout()`` and the new integrations the ``--install-folder`` argument shouldn't be necessary, because that is only necessary for ``conan build``, and in the updated examples that is not used at all, because the native build system integration, i.e. calling directly ``cmake ....`` is preferred. The ``--install-folder`` argument will completely disappear in Conan 2.0 too.

Maybe you could clarify from the updated examples repo and using Conan 1.41 what is the issue, like which commands are you changing and why? Maybe a diff of the ``examples`` repo could help.

**Comment by dphoyes** [comment]
I've updated the example and annotated with comments to try and show what's happening: https://github.com/dphoyes/examples/commit/595dc60f50f77eb33cae26e11c6f343227fed883 . Tested with Conan 1.41.0.

**Comment by memsharded** [comment]
Hi @dphoyes 

The example didn't fail for me, specifically the lines:
```bat
PUSHD say
conan info . && echo "*** Conan info worked ***" || echo "*** Conan info failed ***"
rm graph_info.json
conan info . && echo "*** Conan info worked ***" || echo "*** Conan info failed ***"
POPD
```
work fine in both Windows and Linux:

```
*** self.folders.generators = build/conan ***
conanfile.py (say/0.1@user/channel)
    ID: d057732059ea44a47760900cb5e4855d2bea8714
    BuildID: None
    Context: host
    URL: <Package recipe repository url here, for issues about the package>
    License: <Put the package license here>
    Author: <Put your name here> <And your email here>
    Description: <Description of Say here>
    Topics: <Put some tag here>, <here>, <and here>
    Provides: say
+ echo '*** Conan info worked ***'
*** Conan info worked ***
+ rm graph_info.json
+ conan info .
*** self.folders.generators = cmake-build-release/conan ***
conanfile.py (say/0.1)
    ID: 7fa3148f741307b51a958483d8a2d2dd66cf0ac7
    BuildID: None
    Context: host
    URL: <Package recipe repository url here, for issues about the package>
    License: <Put the package license here>
    Author: <Put your name here> <And your email here>
    Description: <Description of Say here>
    Topics: <Put some tag here>, <here>, <and here>
    Provides: say
+ echo '*** Conan info worked ***'
```

In any case, the files that are being created like ``graph_info.json`` are not following the layout, and are not expected to follow. They are not "generators" files. In the general case, only new generators from ``conan.tools`` will understand layouts completely, there is no guarantee that legacy generators like the ``txt`` one will follow the layout either. The files corresponding to ``CMakeToolchain`` and ``CMakeDeps`` I see them in the right generators folders. Please recall that both ``txt`` and ``json`` generators are going to dissapear in Conan 2.0.

**Comment by dphoyes** [comment]
Hi @memsharded

> Please recall that both txt and json generators are going to dissapear in Conan 2.0.

Ok I see - I hadn't realised that "will be fully functional only in the new build system integrations" means that txt, json and friends are deprecated too. I notice there isn't yet a scons integration in the new system - would you suggest we implement our own, or is the API still considered too experimental for that?

> The example didn't fail for me

I'm not sure why that is. I have tried reinstalling Conan (1.41.0), deleting the entire `conan config home` directory, and doing a fresh clone of the the examples repository. I have also tried removing the `generators = ` line, so that the txt and json generators are no longer involved. I still see the error - it looks like this:

```
+ pushd say
~/devel/conan-examples/examples/features/editable/cmake/say ~/devel/conan-examples/examples/features/editable/cmake
+ conan info .
ERROR: Missing lockfile in: /home/davhoy01/devel/conan-examples/examples/features/editable/cmake/say/conan.lock
+ echo '*** Conan info failed ***'
*** Conan info failed ***
+ rm graph_info.json
+ conan info .
*** self.folders.generators = cmake-build-release/conan ***
conanfile.py (say/0.1)
    ID: 50a5030bbbb13ae56bc4be41915ecd48549cb895
    BuildID: None
    Context: host
    URL: <Package recipe repository url here, for issues about the package>
    License: <Put the package license here>
    Author: <Put your name here> <And your email here>
    Description: <Description of Say here>
    Topics: <Put some tag here>, <here>, <and here>
    Provides: say
+ echo '*** Conan info worked ***'
*** Conan info worked ***
+ popd
```

Is it possible you had leftover files from a previous build before running the script? In particular, features/editable/cmake/say/conan.lock.

Thanks for the help.

**Comment by memsharded** [comment]
> I notice there isn't yet a scons integration in the new system - would you suggest we implement our own, or is the API still considered too experimental for that?

We are developing all the new integrations around the new ``self.dependencies`` access. It should be good enough to start implementing other integrations too, still experimental, might still have some changes, but it is becoming more stable the more we build around it. ``Scons`` integration we haven't started yet to migrate to the new ``conan.tools`` place, if you would like to contribute a new integration that would be great.

> Is it possible you had leftover files from a previous build before running the script? In particular, features/editable/cmake/say/conan.lock.

I have doubled checked, and ran it again, no leftover conan.lock file (or any other file), in any folder, project completely clean. I am a bit lost here, not sure why it is failing on your side.

**Comment by dphoyes** [comment]
I got the debugger out, and the `conan info` command seems to be failing at this bit in conans/client/conan_api.py:

```python
    try:
        graph_info = GraphInfo.load(install_folder)
    except IOError:  # Only if file is missing
        if install_folder:
            raise ConanException("Failed to load graphinfo file in install-folder: %s"
                                 % install_folder)
        graph_info = None
    else:
        lockfilename = os.path.join(install_folder, LOCKFILE)
        graph_lock_file = GraphLockFile.load(lockfilename, cache.config.revisions_enabled)
        graph_info.profile_host = graph_lock_file.profile_host
        graph_info.profile_host.process_settings(cache, preprocess=False)
```

This is saying that it's ok for `say/graph_info.json` to not exist, but if it does exist then `say/conan.lock` _must_ also exist. I get an error here, because `say/graph_info.json` exists and `say/conan.lock` does not.

Looking into where the `say/graph_info.json` came from, it was generated during the `conan install` command inside `hello/cmake-build-release`. This is where it happens:

```python
    def _handle_node_editable(self, node, profile_host, profile_build, graph_lock):
        # Get source of information
        conanfile = node.conanfile
        ref = node.ref
        package_layout = self._cache.package_layout(ref)
        base_path = package_layout.base_folder()
        self._call_package_info(conanfile, package_folder=base_path, ref=ref, is_editable=True)

        # New editables mechanism based on Folders
        if hasattr(conanfile, "layout"):
            conanfile.folders.set_base_package(base_path)
            conanfile.folders.set_base_source(base_path)
            conanfile.folders.set_base_build(base_path)
            conanfile.folders.set_base_install(base_path)
            conanfile.folders.set_base_imports(base_path)

            output = conanfile.output
            output.info("Rewriting files of editable package "
                        "'{}' at '{}'".format(conanfile.name, conanfile.generators_folder))
            self._generator_manager.write_generators(conanfile, conanfile.install_folder,
                                                     conanfile.generators_folder, output)
            write_toolchain(conanfile, conanfile.generators_folder, output)
            output.info("Generated toolchain")
            graph_info_node = GraphInfo(profile_host, root_ref=node.ref)
            graph_info_node.options = node.conanfile.options.values
            graph_info_node.graph_lock = graph_lock
            graph_info_node.save(base_path)
            output.info("Generated conan.lock")
            copied_files = run_imports(conanfile)
            report_copied_files(copied_files, output)
            return
```

The `say/graph_info.json` is created by the `graph_info_node.save(base_path)` line. I also see the `"Generated conan.lock"` log message, but I haven't worked out where that is meant to be happening. Is it possible there's some missing code here?

As I mentioned, my workaround for all the above is to just manually delete this `say/graph_info.json` (and the other generated files too like `say/conanbuildinfo.txt`). This doesn't seem to have any bad side-effects, which makes me wonder if it's really necessary to generate these in the source folder? I'm also wondering how this would work for the case where we have both Release and Debug builds, since presumably the files would all be generated in the same `say` source folder, causing them to overwrite each over?
