### ISSUE TITLE
ConfigureEnvironment command_line bug

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#968]
There is a some strangeness in the relationship between `env_info` and ConfigureEnvironment.

It seems that all the items in `env_info` are paths, not just environment variables.  I cannot set,
for instance, 

      self.env_info.FOO = "bar"

, else I will get a ':'-delimited list of characters (`b:a:r`)

I have to set

      self.env_info.FOO.append("bar")

Then, in my consuming package (`test_package`) `build(self):`, I have

      env = ConfigureEnvironment(self)
      self.output.info(env.command_line)

Here's what I get:

```
env LIBS="" LDFLAGS="-L/home/jharris/.conan/data/LocalGcc/6.1/jharris/testing/package/69a91c71dc5109a1d46bbac26bfdf3c779834af1/lib -m64   $LDFLAGS" CFLAGS="$CFLAGS -m64  
-s -DNDEBUG -I/home/jharris/.conan/data/LocalGcc/6.1/jharris/testing/package/69a91c71dc5109a1d46bbac26bfdf3c779834af1/include " CPPFLAGS="$CPPFLAGS -m64  -s -DNDEBUG -I/home/jharris/.conan/data/LocalGcc/6.1/jharris/testing/package/69a91c71dc5109a1d46bbac26bfdf3c779834af1/include " 
C_INCLUDE_PATH=$C_INCLUDE_PATH:"/home/jharris/.conan/data/LocalGcc/6.1/jharris/testing/package/69a91c71dc5109a1d46bbac26bfdf3c779834af1/include" 
CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:"/home/jharris/.conan/data/LocalGcc/6.1/jharris/testing/package/69a91c71dc5109a1d46bbac26bfdf3c779834af1/include"PATH="/home/jharris/.conan/data/LocalGcc/6.1/jharris/testing/package/69a91c71dc5109a1d46bbac26bfdf3c779834af1/bin":$PATH  PATH 
FOO=bar:$FOO  FOO
```

PATH does not have a space before it, and why are "PATH" and "FOO" mentioned alone after the assignment?

Your example of using ConfigureEnvironment in the documentation for installer packages gives:

     self.run("%s && 7z x file.7z" % env.command_line)

Which in this case would try to run the `env` command incorrectly (in a separate shell).  The correct
form of `env` is, I believe, `env var=value ... <command>`.

**Comment by memsharded** [comment]
I think that @lasote would want to check this, he is working in improving all the env-vars related things: https://github.com/conan-io/conan/pull/951

A quick question, just in case: it seems that you are using ``self.run("echo...`` to output things, why? Why not relying on python ``print()`` (better with (), so it is py2-3 compatible), or using ``self.output.info()`` method? Also ``self.ouput.warn(), error(), success()`` for different colors.

**Comment by lasote** [comment]
It's a bug. In the new ConfigureEnvironment refactor the env variables won't be managed by the ConfigureEnvironment, they will be automatically applied before the `build()` `package()` etc conanfile methods. So ConfigureEnvironment will only take care about the Build system environment variables (visual or autotools or gcc). But I'll check to it and see if the bug can affect to the `env_info` propagation.

**Comment by tamboril** [comment]
Good point about the output.  I edited it.  Still, there are spacing errors and the repeated variable-without-value in the resulting string.

All I want is for the path to be updated when I run a dependent package.

**Comment by memsharded** [comment]
Added this issue to the 0.20, as the new ``Environments`` and environment variables have been fully re-done, so this issue should have been already addressed. We will be sharing details for testing new things.
