### ISSUE TITLE
[feature] One directory of dependecies for one project

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9680]
Now local conan cache is global, it's hard to clean.
If one `conanfile.txt` lead to one directory, e.g.
```
/path/to/ProjectA
/path/to/ProjectA/conan/conanfile.txt
/path/to/ProjectA/conan/installed
```
`conan install` for `/path/to/ProjectA/conan/conanfile.txt` can install deps into `/path/to/ProjectA/conan/installed`,
so that after updating `conanfile.txt`, `/path/to/ProjectA/conan/installed` can be cleaned according to `conanfile.txt`.

For efficiency, one or more `conan/installed` directories can be cache when `conan install`.

**Comment by memsharded** [comment]
This is already doable
```
cd /path/to/ProjectA
export CONAN_USER_HOME=/path/to/ProjectA/conan/installed
conan install ... # will put dependencies there.
```

**Comment by playgithub** [comment]
Fine, hope it can be cleaned according to `conanfile.txt` in the future.

Thanks

**Comment by memsharded** [comment]
If you that per project, cleaning it is as simple as removing the folder "installed"

**Comment by playgithub** [comment]
> If you that per project, cleaning it is as simple as removing the folder "installed"

I mean clean the installed packages that are not in `confile.txt`

**Comment by memsharded** [comment]
How did you install them if they are not in the ``conanfile.txt``? If you define a local "installed" folder per project, what is installed there should come from the ``conanfile`` of that project.

**Comment by playgithub** [comment]
> How did you install them if they are not in the `conanfile.txt`?

After modifying settings or options in `conanfile.txt`, old ones that are not in use any more should be cleaned.

**Comment by memsharded** [comment]
You cannot modify settings in conanfile.txt

**Comment by playgithub** [comment]
> You cannot modify settings in conanfile.txt

OK, dependencies may change.

**Comment by memsharded** [comment]
Well, if you change dependencies, remove the ``installed`` folder first, if you want to clean the previous ones.

**Comment by playgithub** [comment]
It's ok when there are binary caches in remote.
If no binary caches, cleaning according to `conanfile.txt` / `conanfile.py` is more efficient.
And the cleaning behavior is more natural for human mind.
