### ISSUE TITLE
[question] How to run `conan_server` on boot as service on Linux?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9681]
I can't find the answer at https://docs.conan.io/en/latest/uploading_packages/running_your_server.html

**Comment by memsharded** [comment]
Because running anything as a service on Linux depends on the specific Linux distro and version. You should check how to do that for your system, this is not a Conan question, but a Linux question.

**Comment by playgithub** [comment]
OK, better if it is also crossplatform.
