### ISSUE TITLE
[question] How to import to different directories for different built types with `conanfile.txt`?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9684]
The example below only support one build type.

conanfile.txt
```
[imports]
bin, *.dll -> ../../out/build/x64-Release/Release
```

**Comment by memsharded** [comment]
``conanfile.txt`` is limited. Use a ``conanfile.py`` with a ``layout()`` definition, including ``imports`` folder:

```python
def layout(self):
        self.folders.imports =
```

**Comment by playgithub** [comment]
Do you mean I can always replace `conanfile.txt` with `conanfile.py`?

**Comment by memsharded** [comment]
https://docs.conan.io/en/latest/mastering/conanfile_py.html

**Comment by playgithub** [comment]
That's great, more consistent and more powerful.

Thanks
