### ISSUE TITLE
[question] How to pass CMAKE_OSX_ARCHITECTURES to required packages

### ISSUE THREAD

**Issue by Zvicii** [conan-io/conan#9689]
I am building for macos armv8 on macox x86_64,
although I specifiled both profile:build and profile:host.
some packages build correctly (openssl 1.1.1l),
while some packages still build for x86_64 (libuv).

since define CMAKE_OSX_ARCHITECTURES in a toolchain file doesn't work (it needs to be defined before the first 'project' statement)
is it possible to provide a enviroment variable CONAN_CMAKE_OSX_ARCHITECTURES to pass it to required packages just like CONAN_CMAKE_TOOLCHAIN_FILE does?

or is there other way to do the trick? many thx!

**Comment by memsharded** [comment]
Hi @Zvicii 

Indeed there is no generic way to pass CMAKE_OSX_ARCHITECTURES, or in fact any other CMake generic variable to upstream dependencies, because those dependencies might not use CMake at all (as it is the case of openssl, for example).

Then, this should be implemented in recipes, most typically using some of the Conan built-in integrations. 
Conan recipes existing in ConanCenter might be or not fully ready for cross compilation, and it is totally possible that some libraries like ``libuv`` is not prepared for this scenario yet. This can be filed as a issue to conan-center-index repository, to request the recipe improved for these scenarios.

What we are doing on the Conan client tool side is to provide new build system integrations that should handle these case with more flexibility and power, like the new ``CMakeToolchain``, that already defines the CMAKE_OSX_ARCHITECTURES variable via the ``-DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake``. Not sure what you mean it cannot be defined in a toolchain file, that is exactly the place it should be defined, isn't it?

**Comment by Zvicii** [comment]
Thanks for replying to me so quickly！
I will create a issue to cci, or try to make a PR.

CMAKE_OSX_ARCHITECTURES can be defined in a toolchain file but it won't work (I tried), 

see here
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html#:~:text=CMAKE_OSX_ARCHITECTURES%20%C2%B6%20Target%20specific%20architectures%20for%20macOS%20and,created.%20See%20that%20target%20property%20for%20additional%20information.

> The value of this variable should be set prior to the first project() or enable_language() command invocation because it may influence configuration of the toolchain and flags. It is intended to be set locally by the user creating a build tree.

**Comment by memsharded** [comment]
> CMAKE_OSX_ARCHITECTURES can be defined in a toolchain file but it won't work (I tried),

We have tests in our test suite that seems to be working fine to cross compile to arm, by using this variable defined in the ``conan_toolchain.cmake``

- https://github.com/conan-io/conan/blob/develop/conans/test/functional/toolchains/ios/test_using_cmake.py
- https://github.com/conan-io/conan/blob/develop/conans/test/functional/toolchains/cmake/test_cmake_toolchain_m1.py

Are you 100% sure it doesn't work? The -DCMAKE_TOOLCHAIN_FILE=.... way is actually defining things *before* the first ``project()`` call, exactly as described in the docs.

**Comment by Zvicii** [comment]
I test it with a simple project on my m1 macbook
this is my CMakelists

```
cmake_minimum_required(VERSION 3.0.0)
project(test_nim VERSION 0.1.0)
set(CMAKE_CXX_STANDARD 17)

add_executable(test_nim main.cpp)

set_target_properties( test_nim
    PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin"
)
```

this is main .cpp

```
int main(int argc, char const* argv[]) {
    /* code */

    return 0;
}
```


if I pass CMAKE_OSX_ARCHITECTURES on the command line, it works fine

```
[main] Configuring folder: Test 
[driver] Removing /Users/zouyiqi/Projects/Test/build/CMakeCache.txt
[driver] Removing /Users/zouyiqi/Projects/Test/build/CMakeFiles
[proc] Executing command: /opt/homebrew/bin/cmake --no-warn-unused-cli -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -H/Users/zouyiqi/Projects/Test -B/Users/zouyiqi/Projects/Test/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is AppleClang 13.0.0.13000029
[cmake] -- The CXX compiler identification is AppleClang 13.0.0.13000029
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: /usr/bin/clang - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: /usr/bin/clang++ - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /Users/zouyiqi/Projects/Test/build

[main] Building folder: Test 
[build] Starting build
[proc] Executing command: /opt/homebrew/bin/cmake --build /Users/zouyiqi/Projects/Test/build --config Debug --target all -j 10 --
[build] [ 50%] Building CXX object CMakeFiles/test_nim.dir/main.cpp.o
[build] [100%] Linking CXX executable bin/test_nim
[build] [100%] Built target test_nim
[build] Build finished with exit code 0

zouyiqi@zouyiqideMacBook-Pro Test % lipo -archs build/bin/test_nim
x86_64
```

but if i use a toolchain file

```
#toolchain.cmake
set(CMAKE_OSX_ARCHITECTURES x86_64)

```
```
[main] Configuring folder: Test 
[driver] Removing /Users/zouyiqi/Projects/Test/build/CMakeCache.txt
[driver] Removing /Users/zouyiqi/Projects/Test/build/CMakeFiles
[proc] Executing command: /opt/homebrew/bin/cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=/Users/zouyiqi/Projects/Test/toolchain.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -H/Users/zouyiqi/Projects/Test -B/Users/zouyiqi/Projects/Test/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is AppleClang 13.0.0.13000029
[cmake] -- The CXX compiler identification is AppleClang 13.0.0.13000029
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: /usr/bin/clang - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: /usr/bin/clang++ - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /Users/zouyiqi/Projects/Test/build

[main] Building folder: Test 
[build] Starting build
[proc] Executing command: /opt/homebrew/bin/cmake --build /Users/zouyiqi/Projects/Test/build --config Debug --target all -j 10 --
[build] [ 50%] Building CXX object CMakeFiles/test_nim.dir/main.cpp.o
[build] [100%] Linking CXX executable bin/test_nim
[build] [100%] Built target test_nim
[build] Build finished with exit code 0

zouyiqi@zouyiqideMacBook-Pro Test % lipo -archs build/bin/test_nim
arm64
```

so I'm guessing define it in a toolchain file doesnt work?

**Comment by memsharded** [comment]
You need to make it CACHE var in your toolchain.cmake file:

```cmake
set(CMAKE_OSX_ARCHITECTURES {{ CMAKE_OSX_ARCHITECTURES }} CACHE STRING "" FORCE)
```

**Comment by Zvicii** [comment]
oops，my bad，it works like a charm.
I'll close the issue now.

**Comment by memsharded** [comment]
> oops，my bad，it works like a charm.

No prob, happy that it is working now :)
