### ISSUE TITLE
[question] How do I enable /std:c++latest on MSVC toolset?

### ISSUE THREAD

**Issue by 0x8000-0000** [conan-io/conan#9693]
I am trying to build a library using C++20 features using MSVC 17 preview.

The compiler is giving out this message:

    The contents of <ranges> are available only in c++latest mode with concepts support;
    see https://github.com/microsoft/STL/issues/1814 for details.

My profile has:

    compiler=Visual Studio
    compiler.version=17
    compiler.cppstd=20

I have tried setting "compiler.cppstd=latest" but "conan install... " errors out with:

    ERROR: The specified 'compiler.cppstd=latest' is not available for 'Visual Studio 17'. Possible values are ['14', '17', '20']'

I have tried adding "latest" to cppstd key in settings.yml, without effect.

How do I compile code using /std:c++latest flag on MSVC?

Thank you!

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @0x8000-0000 

It seems the mapping is already passed, there are already some c++23 features cooking in latest. 
The missing piece in Conan is that the ``cppstd`` is missing the 23 value in settings.yml. We need to fix that, lets do it asap.

In the meantime, please add ``23`` to the available ``cppstd`` settings.yml. Then pass it in your profile. It will map to ``/std:c++latest`` compilation flag. Please let me know if that works, thanks!

**Comment by 0x8000-0000** [comment]
It does work, thank you!

**Comment by memsharded** [comment]
Now I see why it is not added to ``Visual Studio``. It is added to the new compiler setting that will replace it:

```
msvc:
            version: ["19.0",
                      "19.1", "19.10", "19.11", "19.12", "19.13", "19.14", "19.15", "19.16",
                      "19.2", "19.20", "19.21", "19.22", "19.23", "19.24", "19.25", "19.26", "19.27", "19.28", "19.29",
                      "19.3", "19.30"]
            runtime: [static, dynamic]
            runtime_type: [Debug, Release]
            cppstd: [14, 17, 20, 23]
```

As a request of the Tribe, we are moving from the "Visual Studio" setting, that uses the IDE version to the actual ``msvc`` that uses the actual compiler version.

So the ``cppstd`` was no longer updated by default in ``settings.yml``, because it is already in the deprecation path. You can still add it to your settings.yml, but I will label this as a question, and considered it responded if you agree. Keep an eye on release notes and blog posts, to see progress in the moving to the new ``msvc`` model. Thanks!

**Comment by 0x8000-0000** [comment]
This is the current content of my profile file:

    [settings]
    os=Windows
    os_build=Windows
    arch=x86_64
    arch_build=x86_64
    compiler=Visual Studio
    compiler.version=17
    compiler.cppstd=23
    build_type=Debug
    [options]
    [build_requires]
    [env]

What is the recommended profile? Something like this?

    [settings]
    os=Windows
    os_build=Windows
    arch=x86_64
    arch_build=x86_64
    compiler=msvc
    compiler.version=19.30
    compiler.cppstd=23
    build_type=Debug
    [options]
    [build_requires]
    [env]

**Comment by memsharded** [comment]
Actually something like:

```
[settings]
os=Windows
arch=x86_64
compiler=msvc
compiler.version=19.30
compiler.cppstd=23
compiler.runtime=dynamic
build_type=Debug
```

Note the dynamic runtime.
The ``xxx_build`` can be removed, because cross-compiling will be addressed with the build and host profiles approach.

Just take into account that these settings are experimental, designed to replace the others, but still not massively adopted, so the  support in some Conan helpers might vary (typically better in ``conan.tools`` new integrations.

**Comment by 0x8000-0000** [comment]
Thanks again!

**Comment by 0x8000-0000** [comment]
Hi @memsharded ,

I am using the profile as you suggested, but MSVC 17.0.0rc3 reports:

cl : Command line warning D9002 : ignoring unknown option '/dynamic'

     -- The C compiler identification is MSVC 19.30.30705.0
     -- The CXX compiler identification is MSVC 19.30.30705.0
     -- Detecting C compiler ABI info
     -- Detecting C compiler ABI info - done
     -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped

**Comment by memsharded** [comment]
Sorry, the output is not fully clear. Can we reproduce this with a ``conan new hello/0.1 --template=cmake_lib`` and the above profile? What is the full output for that case?

**Comment by 0x8000-0000** [comment]
I'll try that... but here is the output while building the Google benchmark package:

     [1/22] Building CXX object source_subfolder\src\CMakeFiles\benchmark_main.dir\benchmark_main.cc.obj
     cl : Command line warning D9002 : ignoring unknown option '/dynamic'
     [2/22] Building CXX object source_subfolder\src\CMakeFiles\benchmark.dir\benchmark_name.cc.obj
     cl : Command line warning D9002 : ignoring unknown option '/dynamic'
     [3/22] Building CXX object source_subfolder\src\CMakeFiles\benchmark.dir\benchmark_api_internal.cc.obj
     cl : Command line warning D9002 : ignoring unknown option '/dynamic'
     [4/22] Building CXX object source_subfolder\src\CMakeFiles\benchmark.dir\colorprint.cc.obj
     cl : Command line warning D9002 : ignoring unknown option '/dynamic'
     [5/22] Building CXX object source_subfolder\src\CMakeFiles\benchmark.dir\console_reporter.cc.obj
     cl : Command line warning D9002 : ignoring unknown option '/dynamic'

**Comment by 0x8000-0000** [comment]
It seems a new library is using MSBuild as a target, despite me adding "CONAN_CMAKE_GENERATOR=Ninja" to the [env] section of the profile.

Here's the full output:

Exporting package recipe
hello/0.1@hello/0.1 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
hello/0.1@hello/0.1 exports_sources: Copied 1 '.cpp' file: hello.cpp
hello/0.1@hello/0.1 exports_sources: Copied 1 '.h' file: hello.h
hello/0.1@hello/0.1: A new conanfile.py version was exported
hello/0.1@hello/0.1: Folder: C:\Users\fiucha\.conan\data\hello\0.1\hello\0.1\export
hello/0.1@hello/0.1: Using the exported files summary hash as the recipe revision: afa4685e137e7d13f2b9845987c5af77
hello/0.1@hello/0.1: Exported revision: afa4685e137e7d13f2b9845987c5af77
Configuration:
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=23
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=19.30
os=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Ninja
CXXFLAGS=/EHsc
LDFLAGS=/WX
hello/0.1@hello/0.1: Forced build from source
hello/0.1@hello/0.1 (test package): Installing package
Requirements
    hello/0.1@hello/0.1 from local cache - Cache
Packages
    hello/0.1@hello/0.1:e3ae15a6951a83595d0fd0ea22791961db6ff582 - Build

Installing (downloading, building) binaries...
hello/0.1@hello/0.1: Configuring sources in C:\Users\fiucha\.conan\data\hello\0.1\hello\0.1\source
hello/0.1@hello/0.1: Copying sources to build folder
hello/0.1@hello/0.1: Building your package in C:\Users\fiucha\.conan\data\hello\0.1\hello\0.1\build\e3ae15a6951a83595d0fd0ea22791961db6ff582
hello/0.1@hello/0.1: Generator txt created conanbuildinfo.txt
hello/0.1@hello/0.1: Calling generate()
hello/0.1@hello/0.1: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
hello/0.1@hello/0.1: Aggregating env generators
hello/0.1@hello/0.1: Calling build()
hello/0.1@hello/0.1: CMake command: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/fiucha/.conan/data/hello/0.1/hello/0.1/build/e3ae15a6951a83595d0fd0ea22791961db6ff582/build/conan/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/fiucha/.conan/data/hello/0.1/hello/0.1/package/e3ae15a6951a83595d0fd0ea22791961db6ff582" "C:\Users\fiucha\.conan\data\hello\0.1\hello\0.1\build\e3ae15a6951a83595d0fd0ea22791961db6ff582\."
Using Conan toolchain through C:/Users/fiucha/.conan/data/hello/0.1/hello/0.1/build/e3ae15a6951a83595d0fd0ea22791961db6ff582/build/conan/conan_toolchain.cmake.
-- Conan C++ Standard 23 with extensions OFF}
-- Conan toolchain: Setting BUILD_SHARED_LIBS= OFF
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.30.30705.0
-- Detecting CXX compiler ABI info
Using Conan toolchain through .
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/fiucha/.conan/data/hello/0.1/hello/0.1/build/e3ae15a6951a83595d0fd0ea22791961db6ff582/build
hello/0.1@hello/0.1: CMake command: cmake --build C:\Users\fiucha\.conan\data\hello\0.1\hello\0.1\build\e3ae15a6951a83595d0fd0ea22791961db6ff582\build --config Debug
Microsoft (R) Build Engine version 17.0.0-preview-21515-03+d66a44095 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/fiucha/.conan/data/hello/0.1/hello/0.1/build/e3ae15a6951a83595d0fd0ea22791961db6ff582/CMak
  eLists.txt
  hello.cpp
  hello.vcxproj -> C:\Users\fiucha\.conan\data\hello\0.1\hello\0.1\build\e3ae15a6951a83595d0fd0ea22791961db6ff582\build\De
  bug\hello.lib
  Building Custom Rule C:/Users/fiucha/.conan/data/hello/0.1/hello/0.1/build/e3ae15a6951a83595d0fd0ea22791961db6ff582/CMak
  eLists.txt
hello/0.1@hello/0.1: Package 'e3ae15a6951a83595d0fd0ea22791961db6ff582' built
hello/0.1@hello/0.1: Build folder C:\Users\fiucha\.conan\data\hello\0.1\hello\0.1\build\e3ae15a6951a83595d0fd0ea22791961db6ff582\build
hello/0.1@hello/0.1: Generated conaninfo.txt
hello/0.1@hello/0.1: Generated conanbuildinfo.txt
hello/0.1@hello/0.1: Generating the package
hello/0.1@hello/0.1: Package folder C:\Users\fiucha\.conan\data\hello\0.1\hello\0.1\package\e3ae15a6951a83595d0fd0ea22791961db6ff582
hello/0.1@hello/0.1: Calling package()

**Comment by 0x8000-0000** [comment]
The Google Benchmark recipe is not using the new toolchain method:

    from conans import ConanFile, CMake, tools
    from conans.errors import ConanInvalidConfiguration
    import os


    class BenchmarkConan(ConanFile):
        name = "benchmark"
        description = "A microbenchmark support library."
        topics = ("conan", "benchmark", "google", "microbenchmark")
        url = "https://github.com/google/benchmark"
        homepage = "https://github.com/google/benchmark"
        license = "Apache-2.0"
        exports_sources = ["CMakeLists.txt", "patches/**"]
        generators = "cmake"

**Comment by memsharded** [comment]
> The Google Benchmark recipe is not using the new toolchain method:

Yes, this is expected. The legacy integrations will not fully handle ``msvc`` new setting.

**Comment by 0x8000-0000** [comment]
Oh. We only have legacy integrations for now (we have a ticket in place to upgrade.)

So, what should we do? Skip the dynamic for now, or just let the compiler complain about it?

But, furthermore, what to do about the Ninja target? Should we take it out of the profile? I have added it there, because with our legacy integrations, we're observing errors:

      CMake Error: CMake was unable to find a build program
            corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is
            not set.  You probably need to select a different build tool.

So without this variable, building a package using the new profile on Windows tries to use MinGW?

**Comment by memsharded** [comment]
> So, what should we do? Skip the dynamic for now, or just let the compiler complain about it?

Yes, we are mostly not touching the legacy integrations unless we break something in the release. If it is only a warning, then it might be ok for now?

Specifying the Ninja generator will also have a new way in 2.0, the "conf" (you can already have a look to the new ``conf`` items in 1.41 with ``conan config list``, that will list many things including ``tools.cmake.cmaketoolchain:generator: User defined CMake generator to use instead of default``) that new integrations are already using. It can be defined both in profiles and command line, and it is cleaner than env-vars.

**Comment by 0x8000-0000** [comment]
We have encountered problems with the Ninja generator and MSVC 16.11 (2019) toolset (if I remember correctly the .pdb were not generated, or generated in the wrong directory and didn't end up in the package.)  There might be a period of overlap where some engineers use the old profiles with the old MSVC and some engineers need to use both. Setting up Ninja globally might not be a solution that works in all cases. I don't have a good answer here, just providing a data point.

Perhaps some canonical/idiomatic/recommended profile configurations would help. For example, I do read every Conan release note blog, but I would not have known that the MSVC profile has a new recommended format.

**Comment by memsharded** [comment]
> Perhaps some canonical/idiomatic/recommended profile configurations would help. For example, I do read every Conan release note blog, but I would not have known that the MSVC profile has a new recommended format.

This is because the first step is stabilizing, migrating and making more used in general the new integrations, which is the thing that we are heavily advocating now, e.g.: https://blog.conan.io/2021/10/19/New-CMake-Transparent-Integration-Guide.html. Once the new integrations are spread, it will be easier and less painful to use new settings like the ``msvc`` or the new ``intel-cc`` compiler. But until the first happens, we are waiting to advocate for the second.
