### ISSUE TITLE
[question] imports() method does not tolerate package component requirements

### ISSUE THREAD

**Issue by ndopj** [conan-io/conan#9708]
While this issue is opened as a question I think this might be bug.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

|info| value|
|:------------- | -------------:|
|**Conan version**|1.40.2|
|**OS**|Linux, Ubuntu 21.04|
|**Compiler**|gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0|

When using `imports(self)` method from Conan all declared dependencies (direct & transitive) will be imported to the build folder according to `self.copy()` arguments used by mentioned method. This happens even when any upstream dependency declares component requirements (for example it consumes only specific components from its dependencies) within its `package_info()` method. I would expect that `imports(self)` method will only import actually used dependencies according to upstream's `package_info()` components.

You can use simple project serving as a example provided here:
[conan-compdeps.zip](https://github.com/conan-io/conan/files/7268944/conan-compdeps.zip)

```
cd lib-a
conan create .

mkdir ../lib-b/build && cd ../lib-b/build
conan install ..
```

**lib-b**   _---requires--->_  **lib-a**  _---requires--->_  **openssl**
**lib-b** imports all needed shared libraries (liblib-a.so and those provided by openssl)

**lib-b** build folder will contain all _openssl_ shared libraries despite the **lib-a** declaring only 'openssl::crypto' component requirement in its `package_info()` method. Is this expected behavior? This could be easily bypassed by modifying **lib-b** `imports()` method but I would expect only actually used components to be imported by default. Also when looking into **lib-b** build folder, generated _findOpenSSL.cmake_ contains definitions for both _OpenSSL::SSL_ and _OpenSSL::Crypto_ targets while actually only _OpenSSL::Crypto_ should be provided.

**Comment by memsharded** [comment]
The ``imports()`` method has been made legacy in Conan 1.X by explicit ``copy()`` in ``generate()`` and removed in Conan 2.0. Closing this ticket, please create new tickets as necessary, thanks!
