### ISSUE TITLE
[feature] What about linux like?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9709]
In Linux, it's very handy to use a lib, just install from the official repo by `apt`/`pacman`/...

## Pros
- less focus on maintaining the libs, more focus on applications
- no worry about version conflicts, libs upgrade independently

## Cons
- No choice for versions
  `vcpkg` solves the problem by using git, git branch can be used for customization, and even mulitple git repos are allowed.

**Comment by redradist** [comment]
@playgithub
> 
> 
>       `vcpkg` solves the problem by using git, git branch can be used for customization, and even mulitple git repos are allowed.

What do you mean by using git ? vcpkg allow to install package from git by git branch or git tag ??

If yes it looks like my old proposal https://github.com/conan-io/conan/issues/7289, but it was ignored unfortunately

**Comment by playgithub** [comment]
> What do you mean by using git ? vcpkg allow to install package from git by git branch or git tag ??

The source of ports are in git repo, it can be customized in a git branch, for example
- use a specific version of a lib in a git branch instead of the newest one in the master branch
- apply custom patches
- private libs

Extremely, one `vcpkg` git repo for dependencies of one project is possible.

**Comment by redradist** [comment]
@playgithub 
> 
> 
> > What do you mean by using git ? vcpkg allow to install package from git by git branch or git tag ??
> 
> The source of ports are in git repo, it can be customized in a git branch, for example
> 
>     * use a specific version of a lib in a git branch instead of the newest one in the master branch
> 
>     * apply custom patches
> 
>     * private libs
> 
> 
> Extremely, one `vcpkg` git repo for dependencies of one project is possible.

Yeah, it is very cool feature - to install from `github`
Cargo (Rust package manager allow it ) allows to do installation from git:
```cargo
[dependencies]
rand = { git = "https://github.com/rust-lang-nursery/rand", branch = "next" }
```
Unfortunately my request was abandoned ... (

**Comment by memsharded** [comment]
Sorry, this is not a valid feature request:

- Conan install dependencies in a cache, never at the system level, and it will not install packages at the system level.
- Conan manages multiple versions of the same package as necessary, that cannot be managed at the system level.
