### ISSUE TITLE
Missing uppercase username warning

### ISSUE THREAD

**Issue by kolis** [conan-io/conan#971]
If I add a user with uppercase letters, eg
```
[users]
Foo: bar
```
and try logging in
```
conan user -r local -p bar Foo
```
all I get is
```
ERROR: Wrong user or password. [Remote: local]
```
and I get no warning in the server output either
to log in I must use lowercase letters in the username: `foo`

I understand that there might only want to allow lowercase usernames, but then at least provide a warning in the server log when loading a configuration with username violations

Also, I see no mention of this in the documentation?

**Comment by memsharded** [comment]
Yes, indeed seems a bug, thanks for reporting!

**Comment by memsharded** [comment]
I have been trying to reproduce this, but it seems to work fine, not a bug.
Which version of the server and the client are you using? Please try updating if not using the latest.
Make sure to restart the server when you make changes (like adding a user). The server.conf file is not hot re-loaded.

Thanks for your feedback.

**Comment by kolis** [comment]
Yeah, you are right. Sorry for this. It turns out I was using an old server version, I was running conan from this docker image, https://hub.docker.com/r/dkruger/conan-server/

When using an up to date server version I no longer have this problem!

**Comment by memsharded** [comment]
No worries! We are here to help, thanks for telling, also for posting in hub.docker about the obsolete version.
