### ISSUE TITLE
[feature] MesonToolchain: improve cross-compilation workflow on Apple systems

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#9710]
unlike CMake, meson is dumb and doesn't attempt to guess a path to the compiler in case of cross-compiling mode.
it has to be explicitly specified within cross-file

we probably can deduce required things in the conan client, but it's kinda auto-magic...
OTH it makes recipes easier

we may try to populate the contents of the cross-file similar to the examples meson provides:
https://github.com/mesonbuild/meson/blob/master/cross/iphone.txt
https://github.com/mesonbuild/meson/blob/master/cross/tvos.txt

see also:
https://github.com/conan-io/conan-center-index/pull/7360
https://github.com/conan-io/conan-center-index/pull/6678

/cc @ericLemanissier @madebr @SpaceIm

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
I would say that the Toolchain is supposed to do exactly that, gather the settings and write something the build system understands to represent the configuration. 
Said that, I would say we should consider also adjusting the compiler as I commented here: https://github.com/conan-io/conan/issues/9922#issuecomment-970057251
@memsharded

**Comment by lasote** [comment]
I'm assigning as look into for the next release and let's see if we can finally do it for this release, wait to the next or...let's see
