### ISSUE TITLE
[question] self.env_info.path.append doesn't work for me

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#9716]
### Environment Details (include every applicable attribute)
  * Operating System+version: windows 10
  * Compiler+version: msvc 2019
  * Conan version: 1.36.0
  * Python version: 3.9.7

I have this in my recipe
```
def package_info(self):
    self.env_info.path.append(os.getcwd())
```
executable is at the path `os.getcwd()`

I've added a requirement of this package in my root project's conanfile.py and included cmake stuff in my CMakeLists.txt
When I call a target created by
```
add_custom_command(TARGET ${TARGET_NAME}
        COMMAND "myexecutable --help"
        WORKING_DIRECTORY ${TARGET_SOURCE_DIR})
```
it says: `'myexecutable' is not recognized as an internal or external command, operable program or batch file.`
when I use `${CONAN_MYPACKAGE_ROOT}/myexecutable` it works. Why PATH is not updated? When is it updated?

**Comment by memsharded** [comment]
Hi @xahon 

The ``env_info`` information is not mapped to CMake syntax, in any of the generators. It is mapped to env files that can be activated.

Some of the new generators like ``CMakeDeps`` might be able to map ``build_requires`` with the adequate syntax to CMake ``find_package()`` syntax (https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#build-context-activated), but this is not prepared to create targets for executables.

Also, you shouldn't use ``os.getcwd()`` in the expression, as it doesn't necessarily apply to the current package context in all scenarios. You need to use something like ``self.package_folder`` instead.

So the alternatives could be:

- Make sure the environment file is generated (with some virtualenv generator, the modern ones are VirtualBuildEnv and VirtualRunEnv, and require defining ``self.buildenv_info`` and ``self.runenv_info`` instead).
- Activate the environment to put thing in the paths and then execute ``cmake ...`` commands.
- For recipes, nothing is necessary, beyond declaring the right generator (like ``VirtualBuildEnv``), if the file exist, the ``self.run()`` commands will automatically use the environment script.
- If the pure only CMake solutions is desired, then the best way is to create a cmake build_module CMake script in the package containing the ``executable``, so it can be directly invoked by the consumer.

**Comment by memsharded** [comment]
``self.env_info`` superseded some time ago by ``self.buildenv_info``, closing the ticket as outdated.

Please create new tickets referring to the new tools, thanks!
