### ISSUE TITLE
[question] Unable to find conanbuild.conf

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#9717]
I'm working in the current [git repo](https://notabug.org/williambehrens/AllWpilibConan) to create a conan package for a library and when I run `conan create .` I keep getting the error ".../conanbuild.conf does not exist, please make sure it was not generated in other folder" but when I go to the build directory there is not other folder for me to check and even if I did find it I don't know what I'd do from there. Why is my script having trouble finding/building conanbuild.conf?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

You are mixing legacy generators with the new ones, you need to move:

- Check the output of ``conan new hello/0.1 --template=cmake_lib``. That is the base you should be using for the modern stuff.
- Need to use ``CMakeDeps`` and ``CMakeToolchain``, can't use ``cmake_find_package``.
- Very recommended to start using the ``cmake_layout()`` in the ``layout()`` method

If for any reason you don't want to start using the modern integration, then you need to stick with the legacy CMake one in ``from conans import CMake`` not the new one.

**Comment by wbehrens-on-gh** [comment]
got it
