### ISSUE TITLE
[bug] Conan does not import packages from virtual environment

### ISSUE THREAD

**Issue by chausner-audeering** [conan-io/conan#9721]
When a conan build is invoked while a virtual environment is activated, and conan is not installed in the virtual environment, attempts to load any modules from the virtual environment fail.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version:
  * Conan version: 1.40.3
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
1. Install conan system-wide, e.g.
   `pip3 install conan`
2. Create a new virtual environment:
   `virtualenv venv`
3. Activate the virtual environment:
   `source venv/bin/activate`
4. Install package `cowsay` inside the virtual environment:
   `pip install cowsay`
5. Create a dummy `conanfile.py`:
   ```python
   from conans import ConanFile

   class ConantestConan(ConanFile):
       name = "conantest"
       version = "1.0.0"

       def build(self):
           import cowsay
           print("cowsay imported")
   ```
6. Attempt to build the package:
   `mkdir build ; cd build ; conan install .. ; conan build ..`

conan will fail to load the cowsay module:
> ERROR: conanfile.py (conantest/1.0.0): Error in build() method, line 8
>         import cowsay
>         ModuleNotFoundError: No module named 'cowsay'

I already tried passing `--system-site-packages` to the `virtualenv` command but it does not fix the issue. The only workaround is to install conan itself in the virtual environment.

Background:

We are running conan on our CI runners and since the runners are not dockerized, we would like to invoke Conan inside virtual environments in order to ensure pip dependencies of different conanfiles do not lead to conflicts. We found that we currently need to install those dependencies system-wide on the runners, which defeats the whole point of the virtual environments.

**Comment by memsharded** [comment]
Hi @chausner-audeering 

This is not a bug, but this is standard Python behavior?. Conan is a Python application, if you want in your recipes to import and use functionality from other Python packages, then those packages must live in the same environment. Unless you want to create an executable-like wrapper or something like that and you run them like ``self.run("activate && python -m ...")``. Furthermore, all conanfiles that are involved in the same Conan invocation or dependency graph, will share the same environment, it is not possible that the different recipes are evaluated and executed each one in a different virtualenv.

**Comment by chausner-audeering** [comment]
I think I found the cause myself just after posting this issue: when invoking the `conan` command, it loads `/usr/bin/conan` which uses shebang to load `/usr/bin/python3` which is the system Python interpreter, not the interpreter in the virtual environment. A workaround is to call `python /usr/bin/conan build ..` which now loads the proper interpreter and the import works as expected.

**Comment by chausner-audeering** [comment]
> Furthermore, all conanfiles that are involved in the same Conan invocation or dependency graph, will share the same environment, it is not possible that the different recipes are evaluated and executed each one in a different virtualenv.

I was not attempting to use different virtual environments for different conanfiles in the same dependency graph. I was referring to shared CI runners where potentially completely independent CI jobs run on the same system. In this case, I would like to use virtual environments to separate builds of project A from builds of project B, where both projects may require different versions of the same Python library.

**Comment by memsharded** [comment]
I think that such workaround could have some unexpected side effects because if Conan is installed at the system level, then the virtualenv that executes that command could potentially have incompatible dependencies. If you have that controlled and works for you, then great, but please keep an eye on your virtualenv installed dependencies and possible collisions with Conan ones.

**Comment by chausner-audeering** [comment]
> If you have that controlled and works for you, then great, but please keep an eye on your virtualenv installed dependencies and possible collisions with Conan ones.

Good point, will keep it in mind. I'll close this issue as resolved then.
