### ISSUE TITLE
[question] Listing all packages in the Conan Ecosystem for research

### ISSUE THREAD

**Issue by heyjoakim** [conan-io/conan#9722]
Hi, I am trying to collect all the packages in the Conan ecosystem (Public packages in Conan Center). Though, this does not seem possible to me. How would one go around doing that?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've tried with the Conan API `search_packages`, but seems like wildcards are not supported
- [X] I've tried `$ conan search "*" -r=all > out.txt`
  -  Ends up returning unable to connect to conan center
- [X] I've tried `$ conan search -r=all  > out.txt`
  - Returns 502 bad gateways after a long time - I removed the timeout
  - ``` ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/conans/search (Caused by ResponseError('too many 502 error responses')). [Remote: conancenter]```

At [Conan.io](https://conan.io/center/allpackages) it lists 1000 packages, but I would guess that there is more than that.

**Comment by memsharded** [comment]
Hi @heyjoakim 

All the packages in ConanCenter are in the https://github.com/conan-io/conan-center-index repo. You can just fork the repo and count folders (well, if you want to count different versions too, you need to parse the ``conandata.yml`` files)

**Comment by heyjoakim** [comment]
Hi @memsharded,

Thanks for the quick reply! 

By folders do you mean the folders in Recipes/? This tells me that the total number of packages in ConanCenter is 1.080 (not including different versions). Does this sound correct?

**Comment by memsharded** [comment]
Yes, exactly, the ``recipes`` folders. 1080 sounds right, we celebrated last week the 1000 mark. Yes, that is not including versions, there will be possibly 2-3x versions (on average) for every recipe I guess.

**Comment by heyjoakim** [comment]
@memsharded thank you very much!
Cheers on the 1000 mark. I closed this issue.
