### ISSUE TITLE
[feature] How CMakeToolchain could handle multiple user toolchains

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9724]
Lets say that we have 2 different build_requires, one ``sdk`` and one ``compiler``. Building a package could use both, and each one would want to inject their own ``user_toolchain.cmake``. 

Or they want to propagate information to the consumer in other ways. Challenges:

- Passing information like CC/CXX via environment requires using VirtualBuildEnv, and activating env scripts, which is not the most convenient for IDE developers. Env-vars might not be enough for some cases, and still a user toolchain might be necessary.
- Passing information via ``self.conf_info`` to consumer can work, but at the moment can only provide 1 value for ``user_toolchain``. More than one value would require list aggregation or equivalent functionality

cc/ @Blejdfist

**Comment by blejdfist** [comment]
The ability to provide multiple files to be included in the `UserToolchain` block when using the `CMakeToolchain` generator would provide a lot of flexibility.

**Comment by memsharded** [comment]
I am thinking that we might need a bit more of power in the ``Conf`` class to handle some scenarios. So far the ``Conf`` class is a pure ``key=value`` store, very simple and convenient. But there are current ``conan.conf`` cases that might not be covered:

- The list of hooks to apply
- If we want to evolve it and be able to pass general compilation flags, like CXX_FLAGS to the whole build.
- To be able to aggregate information coming from multiple ``build_requires``, in the consumer.

This would mean in practice that ``Conf`` would be an instance of the ``Environment`` class (and kind o makes sense now that we removed the dependency of ``Environment`` to ``conanfile`` instance, becoming fully abstract). Some questions:
- Should we evolve ``Conf`` to be equal or very similar to ``Environment``?
- Should it be an ``Environment`` instance? What is the overlap now with ``[buildenv]`` profile section?
- Does it make sense to have an ``Environment`` with "un-realizable" env-vars, like ``tools.cmake.cmake_toolchain:xxxx``?

Wdyt @lasote?

**Comment by memsharded** [comment]
Lets try this approach of using something like ``Environment`` to extend the capabilities of current ``Conf``

**Comment by memsharded** [comment]
We will try the following approach:

- Make explicit in a generator like ``ConfAggregator`` the behavior of accummulating conf from build-requires
- This generator can be explicitly instantiated to customize priorities and behavior
- The generator will be enabled in 1.X with ``auto_use`` as VirtualBuildEnv and automatic in 2.0
- CMakeToolchain will listen to that property as a potential list (both for profile, and from deps, agnostic in this point, just move the list to a list of ``include(xxxx)``)

**Comment by lasote** [comment]
Implemented at #10178. It will be released on 1.44
