### ISSUE TITLE
Fix `folders.package` or remove it if we really don't want it. 

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9725]
The current behavior for ``folders.package`` is a bit broken for creating package, and cannot be used then for local ``conan package`` command.

> I think we should open an issue to fix `folders.package` or remove it if we really don't want it. But now, being hardcoded is useless.

_Originally posted by @lasote in https://github.com/conan-io/conan/pull/9668#pullrequestreview-770456931_

**Comment by lasote** [comment]
Fail if running "conan package" and have a layout() declared. Saying you have to use "export-pkg"

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/9884
