### ISSUE TITLE
Please update your cert

### ISSUE THREAD

**Issue by fsicre** [conan-io/conan#9726]
DST Root CA X3  did expired
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

```
$ conan search --remote conancenter bitmagic
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
$
```

```
$ curl https://center.conan.io
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
$ 
```

**Comment by memsharded** [comment]
Hi @fsicre 

In the client side, this is duplicated: https://github.com/conan-io/conan/issues/9695. Please see the remediation there:

- update to 1.40.3
- Or ``conan config install https://github.com/conan-io/conanclientcert.git``

The server side is weird, can't reproduce here, and could be a client side issue.

Could we close this one and follow https://github.com/conan-io/conan/issues/9695?

**Comment by lasote** [comment]
The server certificate is ok, you can check here: https://www.sslshopper.com/ssl-checker.html#hostname=center.conan.io
Probably your system is using the expired X3 too, I needed to remove `/etc/ssl/certs/DST_Root_CA_X3.pem` in some old distributions in order to use the new one.

**Comment by fsicre** [comment]
Sur, let's follow #9695.
Many thanks @memsharded & @lasote
