### ISSUE TITLE
[bug] Wrong remote is acceptable

### ISSUE THREAD

**Issue by n-bes** [conan-io/conan#9727]
### Environment Details (include every applicable attribute)
  * Conan version: ```Conan version 1.40.3```
  * Python version: ```Python 3.9.7```

### Steps to reproduce

```
$ conan remote add random_name localhost
WARN: The URL 'localhost' is invalid. It must contain scheme and hostname.
WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
$ conan remote list
conancenter: https://center.conan.io [Verify SSL: True]
random_name: localhost [Verify SSL: True]
```

I think, that the warning should not be ignored.

**Comment by memsharded** [comment]
Hi @n-bes 

This is aligned with some of the Conan design guidelines. We think it is better to not block users and not be over-protective with checks and validation. In our experience, any small bug, or any edge case not considered, etc., results in a frustrated blocked user that they cannot add what for them is a valid remote (in this case). So better not to raise an error and avoid potentially blocking users, specially for something that will be easily detected and reported correctly later if it really fails.

**Comment by n-bes** [comment]
ok, ty for fast reply
