### ISSUE TITLE
[question] Unable to find_package with cmake when cross compiling

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#9735]
I've been creating [this](https://notabug.org/williambehrens/AllWpilibConan) for conan, the package is meant to be used next to a cross compiler for the NI roborio, I have the cross compiler installed on my system and I created a conan profile for it:

### roborio.ini
```
toolchain=/usr/arm-frc2021-linux-gnueabi
target_host=arm-frc2021-linux-gnueabi
cc_compiler=gcc
cxx_compiler=g++

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$toolchain  # Optional, for CMake to find things in that folder
CONAN_CMAKE_SYSROOT=$toolchain  # Optional, if we want to define sysroot
CHOST=$target_host
LD=$target_host-ld
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
STRIP=$target_host-strip
RC=$target_host-windres

[settings]
os=Linux
arch=armv7
compiler=gcc
compiler.version=7.3
compiler.libcxx=libstdc++
build_type=Release
 
[options]
# FIXME: Find a way to enable
allwpilib:with_gui = False # Disabled due to missing Xorg package
```
and a cmake toolchain file that looks like this:
### roborio.cmake
```
set(ARM_PREFIX arm-frc2021-linux-gnueabi)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# In the docker build this folder doesn't exist?
set(CMAKE_SYSROOT /usr/${ARM_PREFIX})

# https://stackoverflow.com/questions/53633705/cmake-the-c-compiler-is-not-able-to-compile-a-simple-test-program
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_C_COMPILER /usr/local/bin/${ARM_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER /usr/local/bin/${ARM_PREFIX}-g++)
set(CMAKE_LINKER /usr/local/bin/${ARM_PREFIX}-ld)

set(CMAKE_CXX_FLAGS "-fuse-ld=${CMAKE_LINKER} -m32")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_MODULE_PATH ${CMAKE_SYSROOT}/usr/share/cmake/Modules)
```
the project itself is stored [here](https://github.com/rr1706/Control2021cpp) in case I missed something important, but after compiling I get a cmake error saying it can't find Findallwpilib.cmake even through it has no trouble finding the files when I'm not cross compiling

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by madebr** [comment]
Your toolchain file contains: [`set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)`](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH_MODE_PACKAGE.html).
This makes `find_package` only look in `CMAKE_FIND_ROOT_PATH`.

You need to either set `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE` to `BOTH`;
or keep `ONLY` and add the root folder of `allwpilib` to `CMAKE_FIND_ROOT_PATH`.


Imho, conan should automatically add the root directory of all requirements to `CMAKE_FIND_ROOT_PATH`.
Perhaps this should be made configurable.

**Comment by wbehrens-on-gh** [comment]
CMake does not appear to reconize `BOTH` as a valid option

**Comment by memsharded** [comment]
> CMake does not appear to reconize BOTH as a valid option

Which CMake version?

Conan ``CMakeToolchain`` will require at least CMake 3.15, and also uses the BOTH internally to find the find_package scripts.

**Comment by wbehrens-on-gh** [comment]
Im using cmake 3.0, ill try newer

**Comment by wbehrens-on-gh** [comment]
I bumped the version to cmake 3.20 and still no luck

**Comment by SpaceIm** [comment]
> Imho, conan should automatically add the root directory of all requirements to CMAKE_FIND_ROOT_PATH.
Perhaps this should be made configurable.

It can't because `find_program()` would grab executables of host context before executales of build context. https://github.com/conan-io/conan/pull/10186 should fix this issue (assuming @WilliamBehrens was using `CMakeToolchain` generator).
