### ISSUE TITLE
[bug] `CONAN_CMAKE_SYSTEM_PROCESSOR` is not applied

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#9736]
The `CONAN_CMAKE_SYSTEM_PROCESSOR` environment variable is not applied to a cmake build,
instead `CMAKE_SYSTEM_PROCESSOR` is set to `self.settings.arch`.

Reading the documentation about [cmake related environment variables](https://docs.conan.io/en/1.7/reference/env_vars.html#cmake-related-variables), it seems to me that by settings the `CONAN_CMAKE_SYSTEM_PROCESSOR`, the cmake variable `CMAKE_SYSTEM_PROCESSOR` will be set automatically.

The following script reproduces my problem/question:
```sh
#!/usr/bin/sh

cd /tmp

cat >buildreq.py <<EOF
from conans import ConanFile

class BuildReq(ConanFile):
    name = "buildreq"
    version = "0.1"
    def package_info(self):
        self.env_info.CONAN_CMAKE_SYSTEM_PROCESSOR = "awesomecpu"
EOF

cat >consumer.py <<EOF
from conans import CMake, ConanFile, tools
import textwrap

class Consumer(ConanFile):
    name = "consumer"
    version = "0.1"
    generators = "cmake"
    def build_requirements(self):
        self.build_requires("buildreq/0.1")
    def build(self):
        tools.save("CMakeLists.txt", textwrap.dedent("""\
            cmake_minimum_required(VERSION 3.0)
            project(consumer C)
            include("\${CMAKE_BINARY_DIR}/conanbuildinfo.cmake")
            conan_basic_setup()
            message(STATUS "CMAKE_SYSTEM_PROCESSOR: \${CMAKE_SYSTEM_PROCESSOR}")
            message(STATUS "CONAN_CMAKE_SYSTEM_PROCESSOR: \$ENV{CONAN_CMAKE_SYSTEM_PROCESSOR}")
        """))
        cmake = CMake(self)
        cmake.configure()
EOF

conan create buildreq.py -tf None
conan create consumer.py -tf None
```

The output of the cmake configure step is:
```
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- CONAN_CMAKE_SYSTEM_PROCESSOR: awesomecpu
```
Where I expect it to contain `awesomecpu` twice.

The Android NDK requires setting `CMAKE_SYSTEM_PROCESSOR` to a known and valid architecture.
I added `CONAN_CMAKE_SYSTEM_PROCESSOR` to the `android-ndk` recipe in https://github.com/conan-io/conan-center-index/pull/7474,
but it looks to me that conan is missing functionality here.

**Comment by martin-schulze-vireso** [comment]
I dug a bit deeper into conan to see where this invalid setting is coming from and I think I found what is described [here](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#cross-building) to be the culprit (emphasis mine):

> If user_toolchain is not defined and Conan detects it is cross-building, because the build and host profiles contain different OS or architecture, it will try to define the following variables:
> [...]
> CMAKE_SYSTEM_PROCESSOR: tools.cmake.cmaketoolchain:system_processor conf if defined, **otherwise arch setting (host) if defined**

https://github.com/conan-io/conan/blob/14d01da610f7850cf95a86ed0f7518af6f9245ee/conan/tools/cmake/toolchain.py#L630-L638

With `_get_cross_build` containing https://github.com/conan-io/conan/blob/14d01da610f7850cf95a86ed0f7518af6f9245ee/conan/tools/cmake/toolchain.py#L581

and `if hasattr(self._conanfile, "settings_build"):`

https://github.com/conan-io/conan/blob/14d01da610f7850cf95a86ed0f7518af6f9245ee/conan/tools/cmake/toolchain.py#L608-L610

so arch (host) is taken.

`CONAN_CMAKE_SYSTEM_PROCESSOR` is used in https://github.com/conan-io/conan/blob/a620e5b7ba6b0d2128edd2056b7391b5fabcd77d/conans/client/build/cmake_flags.py#L226

**Comment by memsharded** [comment]
Closing as outdated, referring to legacy generators removed in 2.0
