### ISSUE TITLE
[feature] Conan meson generator

### ISSUE THREAD

**Issue by n-bes** [conan-io/conan#9737]
Hi. I wanted to create a reproducible binary. It be useful meson support as generator.

https://mesonbuild.com/Reproducible-builds.html

**Comment by memsharded** [comment]
Hi @n-bes 

There is already a Meson integration in Conan. You should have a look https://docs.conan.io/en/latest/reference/conanfile/tools/meson.html, then try it, and report with much more detail what is not working from that starting point and a reproducible case. Thanks.

**Comment by n-bes** [comment]
@memsharded  Could i used it from ```conanfile.txt```?

**Comment by memsharded** [comment]
Yes. To be used together with ``PkgConfigDeps`` for dependencies

**Comment by n-bes** [comment]
ok, i'll test it
@memsharded thank you
