### ISSUE TITLE
[feature] github authenticator

### ISSUE THREAD

**Issue by n-bes** [conan-io/conan#9738]
Hi. Conan github authenticator can be useful for some cases, like https://github.com/conan-io/conan-center-index/issues/4

**Comment by memsharded** [comment]
Github authentication has nothing to do with conan-io/conan-center-index#4. We control specifically which Github users can fire builds, and we have an allow-list for them. It is not enough to be authenticated in Github, and in any case, it is only related to contributing to conan-center-index repo, so this is not a Conan feature.

**Comment by n-bes** [comment]
My bad, anyway the feature can be created

**Comment by memsharded** [comment]
> My bad, anyway the feature can be created

I am sorry, but I don't understand at all what you mean. What feature?

**Comment by n-bes** [comment]
Support a custom github authenticator like this: https://github.com/uilianries/conan-ldap-authentication or https://docs.gitlab.com/ee/user/packages/conan_repository/

**Comment by memsharded** [comment]
If you mean server side, as a feature to the ``conan_server``, please be clear about it. 
Are you using ``conan_server`` anyway? The recommended server for production is ArtifactoryCE, which includes more authentication mechanisms. For ``conan_server`` we prefer not to have to maintain authentication mechanisms, and that is the reason a plugin mechanism is provided and users can provide their own integrations.
