### ISSUE TITLE
[question] How do I package a library for conan when that library didn't use conan originally

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#9743]
As the title says, say I have a library that has some dependancies that are already in the conan center but the project doesn't use conan, how would I go about packaging that library using the dependancies from conan? I've add the `self.requires()` in `def requirements(self):` but that obviously won't link easily, is there a quick an easy way to do this?

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

You would need to be more specific. If the project is still not using Conan, you might go step by step:

- First learn how to use Conan dependencies: https://docs.conan.io/en/latest/getting_started.html. You can run that step by step, is tutorial like.
- Then try to do the same for your own project, just consume the dependencies you need, as pure consumer. I'd probably recommend here to try to use the modern, new generators  "CMakeToolchain" and "CMakeDeps" (if you are using CMake as build system), as they have a more transparent integration.
- Then, if you want to create a Conan package, I'd learn first the basics: https://docs.conan.io/en/latest/creating_packages/getting_started.html.
- And finally adapt that one to your own project

**Comment by wbehrens-on-gh** [comment]
Could you explain a bit what you mean by "new generators" I've used conan for some time but I've just never gone to create a new package that I plan to injest before. on the docs page in the generators sections I only see cmake, cmake_paths, cmake_multi, cmake_find_package, and cmake_find_package_multi

**Comment by memsharded** [comment]
These are the tools that deprecate all the other integrations and will be the only ones that will survive in Conan 2.0: https://docs.conan.io/en/latest/reference/conanfile/tools.html (they are already available since some releases ago)

**Comment by wbehrens-on-gh** [comment]
That makes a lot more sense, I've gotten everything working now

**Comment by memsharded** [comment]
Ok, happy to hear that it is working @WilliamBehrens 
Don't hesitate to open new tickets if you have further questions.
