### ISSUE TITLE
[question] Only allow binary download for Conan package

### ISSUE THREAD

**Issue by NashTools** [conan-io/conan#9757]
We work with a big team and we would like the source code of some sensitive parts of our system not to be accessible to all developers. We have moved those parts of the code to separate libraries, which reside in a Conan package in a self hosted artifactory.
Is there a way to configure the package such, that the developers only have access to the compiled binaries but not to the source code?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @NashTools 

Yes, this is doable, you can use the ``scm`` feature (https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm) to capture the url and commit of the source code into the recipe, but not the actual source code. Only the people with credentials to that source repo will be able to see the code or build the package from sources, while others can only use binary packages.

There is also the ``conan export-pkg`` command to package externally built binaries, but for this use case probably the ``scm`` approach is best.
