### ISSUE TITLE
Response from remote is not json, but 'text/html; charset=utf-8'. [Remote: conanio]

### ISSUE THREAD

**Issue by gazzatav** [conan-io/conan#9759]
* Operating System+version: Ubuntu 18.04
  * Compiler+version: GCC 7 and GCC 11
  * Conan version: Conan version 1.41.0
  * Python version: Python 3.6.9

Since upgrading (due to the certificate problem) using `python3 -m pip install -U conan`, I have version 1.41.0  but when I run the command:
`conan search -r conanio tao*` for example, instead of a listing I get the text of a web page and the final line is:

'Response from remote is not json, but 'text/html; charset=utf-8'. [Remote: conanio]'.

conanio points here:

→ conan remote list
conanio: https://conan.io/center [Verify SSL: True]

(I have searched around for the default path in case it has changed again but cannot find whether this is still or ever was the default).

**Comment by czoido** [comment]
Hi @gazzatav,
Please read: https://github.com/conan-io/cmake-conan/issues/365#issuecomment-937809545
The remote address is: `https://center.conan.io` not `https://conan.io/center`

**Comment by gazzatav** [comment]
Hi @czoido, Thank you - I just could not find that documented anywhere easy to find - and now that I know it I can find it!
