### ISSUE TITLE
Implicit requirement in test_package conanfile

### ISSUE THREAD

**Issue by kolis** [conan-io/conan#976]
Why do I need to explicity list the version of the package to be tested? This means if I have 
```
foo/conanfile.py
foo/test_package/conanfile.py
```
and I update the version in `foo/conanfile.py` I will also have to update `foo/test_package/conanfile.py`? Why would I want to test another version than the one I'm building? And even if there is a valid reason for this, there should be a way of not requiring this.

**Comment by kolis** [comment]
From the documentation
```
It will typically be a project with a single requirement, pointing to the conanfile.py being developed in the current directory.
```

**Comment by memsharded** [comment]
Because there is no magic in it. The project inside ``test_package`` is just a consumer project, the same as if you do it yourself from another folder in your system. It is just a convenience, to be close to the recipe, and just executing export + install + test automatically.  
Probably could be automated, with an environment variable or the like that could be scrapped from the recipe, but the solution could be more obscure than just manually setting the version.

**Comment by kolis** [comment]
Ok, I can understand that.

But how come I can not perform testing in the main `conanfile.py`? eg
```py
def test(self):
  ...
```
in many cases this would be very convenient to have directly in the main conanfile instead of having to setup an additional build script for testing. Epecially for many existing open source projects where the testing is normally part of the build process and can be invoked with `make test` or similar.

**Comment by memsharded** [comment]
You cannot test yourself, as a package. By definition, to really test a package, the package should be already built and packaged, so it has to be tested from the outside.

Please note that they are not unit or functional tests! They are testing the package: basically:
- The headers have been properly copied and packaged, and are in the expected location
- The libraries have been packaged too, to the right location
- You can link with those libraries
- No compatibility mistakes, like debug/release or arch mismatch.

Unit or functional tests can be easily run as part of the package ``build()``. Please note again the difference, conan is not a build system. Building a package could perfectly be composed of building the library + running the unit tests. Only after that is successful, the package will be "packaged".

**Comment by kolis** [comment]
Ok, thank you for detailed answer!
Maybe I missed this in the documentation! If not already there, you should put this information in the package maintainer docs.

**Comment by memsharded** [comment]
You are welcome :)
Yeah, I think http://docs.conan.io/en/latest/packaging/testing.html should be enough to clarify this, but if there is something specific there that you think it can be improved, please tell!
