### ISSUE TITLE
[feature] Remove "requests" from the user-agent

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#9760]
Related to #7526
It might be useful and we really don't need that value in the user-agent.

**Comment by SSE4** [comment]
@danimtb is it used internally to filter/gather statictics for http headers, e.g. to distinguish conan client with other traffic?

**Comment by jgsogo** [comment]
No the `python-requests` part. We get only the Conan version, the Python version, and the OS from the user-agent.
