### ISSUE TITLE
[feature] CMakeDeps : custom variables

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#9764]
might be something similar to #8360

need to think about UX a bit, as some variables need conditions
the usage is pretty common in conan-center
examples:
https://github.com/conan-io/conan-center-index/blob/master/recipes/libxml2/all/conanfile.py#L320
https://github.com/conan-io/conan-center-index/blob/master/recipes/freetype/all/conanfile.py#L183
https://github.com/conan-io/conan-center-index/blob/master/recipes/openal/all/conanfile.py#L130
https://github.com/conan-io/conan-center-index/blob/master/recipes/sqlite3/all/conanfile.py#L152
https://github.com/conan-io/conan-center-index/blob/master/recipes/openssl/1.x.x/conanfile.py#L821

the syntax may look like this:
```
self.cpp_info.set_property("cmake_variables", {"LIBXML2_INCLUDE_DIR":  "LibXml2_INCLUDE_DIR"}, "CMakeDeps")
self.cpp_info.components["buy"].set_property("cmake_variables",  {"LIBXML2_INCLUDE_DIR":  "LibXml2_INCLUDE_DIR"}, "CMakeDeps")
```

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This was implemented in Conan 2 with the ``cmake_additional_variables_prefixes`` properties, closing as solved
