### ISSUE TITLE
[bug] env is erased after deactivating virtual env and virtual run env

### ISSUE THREAD

**Issue by alsora** [conan-io/conan#9766]
Conan virtual env scripts store original env in some variables (e.g. `OLD_CONAN_PATH`).
This way, after deactivating a virtual env, it is possible to restore the original one.
However, this does not work if using multiple virutal environments that act on the same variables.

### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 18.04
  * Compiler+version: N/A
  * Conan version: 1.40
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)

Create a project that uses both `virtualenv` and `virtualrunenv` generators.
Then activate both.
Then deactivate both.

```
source activate.sh
source activate_run.sh
source deactivate.sh
source deactivate_run.sh
```

After the second deactivation, some environment variables will be erased.
This has serious problems because for example, by clearing `PATH`, none of the standard bash utilities will be found anymore.

This is due to the fact that `deactivate` scripts call `unset CONAN_OLD_PATH`.
So, after the first deactivation, the second one will do `PATH=CONAN_OLD_PATH` but the variable is empty.

To fix this, every script should use its own variables (e.g. `CONAN_VENV_OLD_PATH`, `CONAN_VENV_RUN_OLD_PATH`, etc)

**Comment by memsharded** [comment]
Hi @alsora 

We are replacing the generation of env scripts with the new ``VirtualBuildEnv`` and ``VirtualRunEnv`` generators, that intend to completely deprecate the previous ones in Conan 2.0. They use a new approach for avoiding that problem, creating the ``deactivate`` scripts at execution time, not at generation time. Maybe you could give them a try and see if they would solve your issue?

**Comment by alsora** [comment]
Thank you for the quick response.
I just tried to use the generators that you mention.

However, I don't see the scripts for deactivating them.
Looking at `cat conanbuildenv.sh` I see that it exports all the variables but there's nothing related to deactivation there.

**Comment by memsharded** [comment]
That is the point. The deactivate script is actually created when you run the activation. The principle is that the deactivation should restore the environment when the activation occured, not when the activation script was generated, which was what the previous approach was doing.  Please try running the ``activate`` script (maybe it is because the deactivate code is only generated by default in Conan 1.41).

**Comment by alsora** [comment]
I'm currently using Conan 1.40.3.
This is my generators list
```
   generators = ["cmake_find_package", "cmake_find_package_multi", "cmake", "VirtualBuildEnv", "VirtualRunEnv"]
```
I don't have an `activate` script. I see the following files:
 - `conanbuildenv.sh`
 - `conanenv.sh` (this scirpt is a one-liner that sources `conanbuildenv.sh`)
 - `conanrunenv.sh`

I will try with a new version of conan

**Comment by memsharded** [comment]
Yes, the files are:

- conanbuildenv.sh: The environment for building (including build_requires). This is the equivalent of ``activate``, you can source it
- conanrunenv.sh: The environment for running (including LD_LIBRARY_PATH of ``requires`` in the host context with shared libs, for example). You can also source it for things like running tests.
- conanbuild.sh and conanrun.sh are aggregators, they will source multiple "build" or "run" scripts that could be generated from different tools. (maybe there was a rename in 1.41 from conanenv.sh => conanbuild.sh, please double check).

Note the way to use them in recipes has changed, by default is:

```python
self.run(...., env=["conanbuild"])
```
But you can change the ``env`` argument to pass the files that you want (generated in the ``generate()`` method).

**Comment by alsora** [comment]
In my pipeline I'm actually using conan only to fetch dependencies and generate the scripts.
Then I source them "manually" from a bash script and build my application.

Is this any different than using the run method?

**Comment by memsharded** [comment]
No, it is the same. It was just in case you were using it from recipes. The ``self.run(cmd, env=["somefile"]`` basically constructs a command line like ``source somefile.sh && cmd``, so recipe writers don't need to do that manually in recipes.

**Comment by memsharded** [comment]
Closing this ticket as inactive.
