### ISSUE TITLE
[question] Unable to copy files in package method

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#9767]
I have a package method that looks like the following
```
def package(self):
        """Use CMake's built in install functionality to package outputs"""
        _cmake = CMake(self)
        _cmake.configure()
        _cmake.install()
        self.copy(pattern="lib", src=os.path.join(self.package_folder, "wpilib"), dst="lib")
        self.copy(pattern="include", src=os.path.join(self.package_folder, "wpilib"), dst="include")
        self.copy(pattern="LICENSE.md", src=self._source_subfolder, dst="licenses")
        shutil.rmtree(os.path.join(self.package_folder, "share"))
        #shutil.rmtree(os.path.join(self.package_folder, "wpilib"))
```
No matter what I do none of the files I call `self.copy()` on are actually copied to the package directory. what gives? I checked and all the files exist in the places I specified but they don't get copied to where I want.

-  [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by wbehrens-on-gh** [comment]
update: I've been searching for a solution all day and still haven't found one

is there a log of file copies I can check to make sure they're going where they should?

**Comment by tapia** [comment]
Hi, @WilliamBehrens 

That's not how `self.copy()` is supposed to be used. You can check the [Conan documentation](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package), or browse the [Conan Center Index repository](https://github.com/conan-io/conan-center-index/tree/master/recipes) to see how our contributors are using it in their recipes.

Try something like this:

``` 
# This will copy all `.h` files found in the cache's build folder of your package into the `include` dir in the package folder
self.copy("*.h", dst="include")

# This will copy all `.lib`, `.so` and `.a` files found in the build folder into the `lib` folder
self.copy("*.lib", dst="lib", keep_path=False)
self.copy("*.so", dst="lib", keep_path=False)
self.copy("*.a", dst="lib", keep_path=False)
```

**Comment by tapia** [comment]
@WilliamBehrens did the previous answer help you? If it didn't, please provide more info about your specific problem.

**Comment by wbehrens-on-gh** [comment]
Yes that did help
