### ISSUE TITLE
[feature] conditional alias packages

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#9768]
I would like to be able to make conditional aliases. I would like to use them to model system versions, and require them like:

```
from conans import ConanFile

class ConsumerConanfile(ConanFile):
    requires = "protobuf/(system)@"
```

With the current definition, I cannot make aliases depend on settings. 

It would be cool to have a `set_alias()` function (similar to `set_name()`, `set_version()` functions).
Or to be able to set the values in `configure()` instead (which actually also works for the version attribute, instead of using `set_version()`)
```
from conans import ConanFile

class ProtobufSystemConanfile(ConanFile):
    
    def set_alias(self):
        if self.settings.os.distro = Ubuntu16:
            self.alias = "protobuf/3.0.0@heat-rae/stable"
        else self.settings.os.distro = Ubuntu18:
            self.alias = "protobuf/3.6.1@heat-rae/stable"
        else:
           # throw invalidConfigurationException
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This seems to be a duplicate of https://github.com/conan-io/conan/issues/9510

**Comment by KerstinKeller** [comment]
Ah ok, I'll close this in favor of the other issue.
