### ISSUE TITLE
[bug] Libzip option with_openssl not available

### ISSUE THREAD

**Issue by bjoernbahn** [conan-io/conan#9774]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 and Ubuntu 20.04
  * Compiler+version: gcc 9
  * Conan version: 1.40.4
  * Python version: 3.8.6

### Steps to reproduce (Include if Applicable)
I need to have a possibility to get libzip without openssl. I updated my dependency from 1.5.2 to 1.8.0, since the older versions are not available:

[requires]
libzip/1.8.0

[options]
libzip:with_openssl=False

### Logs (Executed commands with output) (Include/Attach if Applicable)

ERROR: libzip/1.8.0: option 'with_openssl' doesn't exist
Possible options are ['shared', 'fPIC', 'with_bzip2', 'with_lzma', 'with_zstd', 'crypto', 'tools']
Conan install failed='1'

**Comment by memsharded** [comment]
This is not a Conan issue, definitely not a bug. Just the new version in ConanCenter repository has changed.
The recipe for new version now contains different options: 

```python
options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "with_bzip2": [True, False],
        "with_lzma": [True, False],
        "with_zstd": [True, False],
        "crypto": [False, "win32", "openssl", "mbedtls", "auto"],
        "tools": [True, False],
    }
    default_options = {
        "shared": False,
        "fPIC": True,
        "with_bzip2": True,
        "with_lzma": True,
        "with_zstd": True,
        "crypto": "openssl",
        "tools": True,
    }
```

It seems that you want to do ``libzip:crypto=False``

**Comment by memsharded** [comment]
There are different ways to see this: 
- https://conan.io/center/libzip
- ``conan inspect <recipe ref like libzip/version@>``
- ``conan get <recipe ref like libzip/version@>``

**Comment by bjoernbahn** [comment]
Thanks, I just got back to this after a long time and want to share.
I now use this option combination:
```
libzip:crypto=False
libzip:with_lzma=False
libzip:with_zstd=False
```
