### ISSUE TITLE
Profiles: cannot set path to env variable in windows

### ISSUE THREAD

**Issue by menzels** [conan-io/conan#978]
hey, 
i am trying to use this profile file:
```
[env]
QTPATH=C:/QtCommercial/5.8/msvc2015_64/bin
```

when i call 
`conan build --profile myprofile`
it tells me
`ERROR: Error reading 'myprofile' profile: Error parsing the profile text file: need more than 1 value to unpack`

i found that it doesn't like the ':'

i had a look into the source code: https://github.com/conan-io/conan/blob/04247290c6f9106aff1e35d55c2008b7abdeb902/conans/model/env_info.py#L35

there it splits on ':' but only in name, not in value.
was there a change since last release? or is something else wrong here?

**Comment by memsharded** [comment]
I guess you are running 0.19.1. And it was working in 0.18? I think we didn't modify anything in this area. Right now a big refactor of environment variables is ongoing, please @lasote have a look at this issue.

**Comment by memsharded** [comment]
Hi!

Thanks for reporting this. Yes, you are right, that was broken. It has already been fixed by recent improvements https://github.com/conan-io/conan/pull/951, but I have just added a test to make sure, in https://github.com/conan-io/conan/pull/999

This will be included in 0.20.

**Comment by memsharded** [comment]
This has been released in 0.20, please try and give feedback or reopen if necessary.
