### ISSUE TITLE
[bug] scm attribute doesn't work correctly with svn 

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#9780]
I've created a conanfile.py for a library I'm working with and I'm pulling it's sources from svn using the scm attribute as follows.
```python
scm = {
  "type": "svn",
  "revision": "HEAD",
  "url": "<svn repo url>"
}
```
and calling conan create on it in Windows 10 everything works as expected and the package builds. But when I switch over to Ubuntu 20.04 and run the same command conan returns saying:
```shell
ERROR: Couldn't checkout SCM: '/home/will/.conan/data/<package name>/<package version>/_/_/source' is not a valid 'svn' repository or 'svn' not found.
```
and I checked and svn is installed at version 1.13.0, What's weird is that if I try and source using the source() method like so:
```python
def source(self):
        svn = tools.SVN(folder=".")
        svn.checkout("<repo url>")
```
I get:
```shell
ERROR: <name>/<version>: Error in source() method, line 39
        svn.checkout("<url>")
        ConanException: '.' is not a valid 'svn' repository or 'svn' not found.
```
The repo is private so my first thought was to add the "username" and "password" options to the scm attribute but then I don't get why it works in windows?

### Environment Details (include every applicable attribute)
  * Windows 10 & Ubuntu 20.04 (lts)
  * Visual Studio 2019, GCC 9.3.0
  * Conan version: 1.41.0
  * Python version: 3.8.10

**Comment by wbehrens-on-gh** [comment]
And just to clarify, I did test adding a username and password to scm and that didn't fix it.

**Comment by wbehrens-on-gh** [comment]
update: I'm now getting the bug on both platforms now

**Comment by memsharded** [comment]
Hi @WilliamBehrens 

It seems the detection of ``svn`` is done with the ``svn info`` command. Could you please try that in the terminal, just in case?

**Comment by wbehrens-on-gh** [comment]
output of svn info:
```
svn: warning: W155010: The node 'path/to/recipes/<package>/all' was not found.

svn: E200009: Could not display info for all targets because some targets don't exist
```

**Comment by franramirez688** [comment]
Hi @WilliamBehrens 

I had the same issue in Ubuntu 20.04 but it's not related to Conan (at least in my case):

* Run `sudo nano /etc/apache2/mods-enabled/dav_svn.conf` and verify that your file is more or less like this one (it does not matter if you have `/var/ib/svn` folder or another one):

```
<Location /svn>
   DAV svn
   SVNParentPath /var/lib/svn

   AuthType Basic
   AuthName "Subversion Repository"
   AuthUserFile /etc/apache2/dav_svn.passwd
   Require valid-user
</Location>
```
If you have a line like this one: `Alias /svn /var/lib/svn`, you have to remove it because it's not working fine and restart the apache2 service.

For the record, I followed [this tutorial](https://meetawaiszafar.medium.com/install-configure-svn-server-on-ubuntu-20-04-with-apache2-6dcd7d9a49e9) to set up the SVN server.

**Comment by wbehrens-on-gh** [comment]
I don't have either of those folders @franramirez688

**Comment by franramirez688** [comment]
Sorry for the delay @WilliamBehrens

I was wondering if you try to run a simple `svn checkout [URL_TO_YOUR_REPOSITORY]` to check that your SVN server is working as expected. If it works you should see this kind of output: `Checked out revision N.`
