### ISSUE TITLE
[bug] creating a package in "shared=True" mode cannot link to another package

### ISSUE THREAD

**Issue by julienalofs** [conan-io/conan#9785]
Hello there,

I have two packages:
- mylib_a: no dependency
- mylib_b: call to mylib_a()

mylib_a package is created in local repo.
When I create a package for mylib_b, everything is fine in "Shared=False" mode but I get unresolved external symbol when "Shared=True".

### Environment Details
  * Operating System+version: Windows 10 Pro 20H2 19042.1237
  * Compiler+version: Visual Studio version 16
  * Conan version: 1.41.0
  * Python version: 3.9.7
  * Cmake version: 3.21.3

### Steps to reproduce
 * mylib_a creation
  `mkdir mylib_a`
  `cd .\mylib_a\`
  `conan new mylib_a/0.1 --template=cmake_lib`
  `conan create . demo/testing`
 * mylib_b creation
  `cd ..`
  `mkdir mylib_b`
  `cd .\mylib_b\`
  `conan new mylib_b/0.1 --template=cmake_lib`
    * add new conanfile.txt
    ` [requires]`
    ` mylib_a/0.1`
    ` [generators]`
    ` cmake`
   * Update CMakeLists.txt: [CMakeLists.txt](https://github.com/conan-io/conan/files/7335394/CMakeLists.txt)
   * Update conanfile.py: [conanfile.py.txt](https://github.com/conan-io/conan/files/7335414/conanfile.py.txt)
  `conan create . demo/testing`
  => sucess
   * Update conanfile.py ("Shared=True"): [conanfile.py.txt](https://github.com/conan-io/conan/files/7335399/conanfile.py.txt)
  `conan create . demo/testing`
  => Error
 

### Logs (Executed commands with output)
PS C:\Users\ja\mylib_b> conan create . demo/testing
Exporting package recipe
mylib_b/0.1@demo/testing exports_sources: Copied 2 '.txt' files: CMakeLists.txt, conanfile.txt
mylib_b/0.1@demo/testing exports_sources: Copied 1 '.cpp' file: mylib_b.cpp
mylib_b/0.1@demo/testing exports_sources: Copied 1 '.h' file: mylib_b.h
mylib_b/0.1@demo/testing: A new conanfile.py version was exported
mylib_b/0.1@demo/testing: Folder: C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\export
mylib_b/0.1@demo/testing: Package recipe modified in export, forcing source folder removal
mylib_b/0.1@demo/testing: Use the --keep-source, -k option to skip it
mylib_b/0.1@demo/testing: Exported revision: 9bd743017b7f9bb8662ed872a24d63f7
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=14
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

mylib_b/0.1@demo/testing: Forced build from source
mylib_b/0.1@demo/testing (test package): Installing package
Requirements
    mylib_a/0.1@demo/testing from local cache - Cache
    mylib_b/0.1@demo/testing from local cache - Cache
Packages
    mylib_a/0.1@demo/testing:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    mylib_b/0.1@demo/testing:6d2b4ae464e3c3c02c2d57557199caad7282112c - Build

Installing (downloading, building) binaries...
mylib_a/0.1@demo/testing: Already installed!
mylib_b/0.1@demo/testing: Configuring sources in C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\source
mylib_b/0.1@demo/testing: Copying sources to build folder
mylib_b/0.1@demo/testing: Building your package in C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\build\6d2b4ae464e3c3c02c2d57557199caad7282112c
mylib_b/0.1@demo/testing: Generator txt created conanbuildinfo.txt
mylib_b/0.1@demo/testing: Calling generate()
mylib_b/0.1@demo/testing: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
mylib_b/0.1@demo/testing: Aggregating env generators
mylib_b/0.1@demo/testing: Calling build()
mylib_b/0.1@demo/testing: CMake command: cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/build/6d2b4ae464e3c3c02c2d57557199caad7282112c/build/conan/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/package/6d2b4ae464e3c3c02c2d57557199caad7282112c" "C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\build\6d2b4ae464e3c3c02c2d57557199caad7282112c\."
Using Conan toolchain through C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/build/6d2b4ae464e3c3c02c2d57557199caad7282112c/build/conan/conan_toolchain.cmake.
-- Conan C++ Standard 14 with extensions OFF}
-- Conan toolchain: Setting BUILD_SHARED_LIBS= ON
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.29.30136.0
-- Detecting CXX compiler ABI info
Using Conan toolchain through .
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
-- Conan: Using cmake-multi generator
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Detected VS runtime: MD
-- Conan: Settings= -s;arch=x86_64;-s;build_type=Release;-s;compiler=Visual Studio;-s;compiler.version=16;-s;compiler.runtime=MD
-- Conan: checking conan executable
-- Conan: Found program C:/Users/ja/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/Scripts/conan.exe
-- Conan: Version found Conan version 1.41.0

-- Conan executing: C:/Users/ja/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/Scripts/conan.exe install C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/build/6d2b4ae464e3c3c02c2d57557199caad7282112c/conanfile.txt -s arch=x86_64 -s build_type=Release -s compiler=Visual Studio -s compiler.version=16 -s compiler.runtime=MD -g=cmake_multi --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=14
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    mylib_a/0.1@demo/testing from local cache - Cache
Packages
    mylib_a/0.1@demo/testing:3fb49604f9c2f729b85ba3115852006824e72cab - Cache

Installing (downloading, building) binaries...
mylib_a/0.1@demo/testing: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generator cmake_multi created conanbuildinfo_release.cmake
conanfile.txt: Generator cmake_multi created conanbuildinfo_multi.cmake
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Detected VS runtime: MDd
-- Conan: Settings= -s;arch=x86_64;-s;build_type=Debug;-s;compiler=Visual Studio;-s;compiler.version=16;-s;compiler.runtime=MDd
-- Conan: checking conan executable
-- Conan: Found program C:/Users/ja/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/Scripts/conan.exe
-- Conan: Version found Conan version 1.41.0

-- Conan executing: C:/Users/ja/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/Scripts/conan.exe install C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/build/6d2b4ae464e3c3c02c2d57557199caad7282112c/conanfile.txt -s arch=x86_64 -s build_type=Debug -s compiler=Visual Studio -s compiler.version=16 -s compiler.runtime=MDd -g=cmake_multi --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.cppstd=14
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    mylib_a/0.1@demo/testing from local cache - Cache
Packages
    mylib_a/0.1@demo/testing:d057732059ea44a47760900cb5e4855d2bea8714 - Cache

Installing (downloading, building) binaries...
mylib_a/0.1@demo/testing: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator cmake_multi created conanbuildinfo_debug.cmake
conanfile.txt: Generator cmake_multi created conanbuildinfo_multi.cmake
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
-- Conan: Loading conanbuildinfo_multi.cmake
-- Conan: Using cmake global configuration
-- Library mylib_a found C:/Users/ja/.conan/data/mylib_a/0.1/demo/testing/package/d057732059ea44a47760900cb5e4855d2bea8714/lib/mylib_a.lib
-- Library mylib_a found C:/Users/ja/.conan/data/mylib_a/0.1/demo/testing/package/3fb49604f9c2f729b85ba3115852006824e72cab/lib/mylib_a.lib
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/build/6d2b4ae464e3c3c02c2d57557199caad7282112c/build
-- Configuring done
-- Build files have been written to: C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/build/6d2b4ae464e3c3c02c2d57557199mylib_b/0.1@demo/testing: CMake command: cmake --build C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\build\6d2b4ae464Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/build/6d2b4ae464e3c3c02c2d57557199caad7282112c/
  CMakeLists.txt
  mylib_b.cpp
     Creating library C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/build/6d2b4ae464e3c3c02c2d57557199caad7282112c/b
  uild/Release/mylib_b.lib and object C:/Users/ja/.conan/data/mylib_b/0.1/demo/testing/build/6d2b4ae464e3c3c02c2d575571
  99caad7282112c/build/Release/mylib_b.exp
mylib_b.obj : error LNK2019: unresolved external symbol "void __cdecl mylib_a(void)" (?mylib_a@@YAXXZ) referenced in fu
nction "void __cdecl mylib_b(void)" (?mylib_b@@YAXXZ) [C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\build\6d2b4ae46
4e3c3c02c2d57557199caad7282112c\build\mylib_b.vcxproj]
C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\build\6d2b4ae464e3c3c02c2d57557199caad7282112c\build\Release\mylib_b.d
ll : fatal error LNK1120: 1 unresolved externals [C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\build\6d2b4ae464e3c3
c02c2d57557199caad7282112c\build\mylib_b.vcxproj]
mylib_b/0.1@demo/testing:
mylib_b/0.1@demo/testing: ERROR: Package '6d2b4ae464e3c3c02c2d57557199caad7282112c' build failed
mylib_b/0.1@demo/testing: WARN: Build folder C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\build\6d2b4ae464e3c3c02c2d57557199caad7282112c\build
ERROR: mylib_b/0.1@demo/testing: Error in build() method, line 40
        cmake.build()
        ConanException: Error 1 while executing cmake --build C:\Users\ja\.conan\data\mylib_b\0.1\demo\testing\build\6d2b4ae464e3c3c02c2d57557199caad7282112c\build --config Release

**Comment by memsharded** [comment]
I am very sorry this was not responded back then, sometimes happen due to high load.

This ticket would be now pretty outdated with Conan 2, and most likely solved, thanks to the better graph model and new build system integrations. Please create any new tickets as necessary for any further question or issue, thanks for the feedback.
