### ISSUE TITLE
[feature] CMakeToolchain support for linker scripts

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#9789]
When building an ELF executable for bare-metal targets it is normal to include a linker script to define the memory layout of the specific target microcontroller.
It is possible to use multiple linker scripts, too.
Each one is passed with the `-T` flag when using GCC.
I don't think this actually needs to be applied to dependencies, only the final executable that will be loaded on the microcontroller.
It would be great if there was an easy way to configure this for the CMakeToolchain generator.
If it only needs to be applied to the consumer, perhaps the CMakeToolchain generator could define a dedicated block for this.
I'm not sure if there should be additional ways to configure linker scripts, but there might be some good ideas out there.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by kammce** [comment]
I'd like to +1 this. It would be great if the linker scripts can be exposed in some way. It would be even better if you can select out of a set of possible linker scripts. For example, my library for LPC40XX mcu has 5 different variants that I'd like to somehow choose at configuration time for my project.

**Comment by jwillikers** [comment]
@kammce If it helps, I currently use a `python_requires` package that provides the linker script as a file which the consumer can than add to their CMakeToolchain. My rough implementation included below adds a new block for the CMakeToolchain generator and copies the linker script directly in to the build directory for easy access.

Linker Script `python_requires` `conanfile.py`:

```python
import os
from pathlib import Path
from shutil import copy2
import textwrap
from conans import ConanFile
from conan.tools.cmake import CMakeToolchain
from conan.tools.cmake.toolchain import Block


LINKER_SCRIPT_FILENAME = "MyLinkerScript.ld"


class LinkerScriptBlock(Block):
    template = textwrap.dedent(
        """
        set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} -T '${CMAKE_CURRENT_LIST_DIR}/MyLinkerScript.ld'")
        """
    )


def add_linker_script(
    tc: CMakeToolchain, module_directory: Path, destination_directory: Path
) -> CMakeToolchain:
    copy2(os.path.join(module_directory, LINKER_SCRIPT_FILENAME), destination_directory)
    tc.blocks["linker_script"] = LinkerScriptBlock
    return tc


class MyLinkerScript(ConanFile):
    name = "my-linker-script"
    description = "My very descriptive description."
    exports = LINKER_SCRIPT_FILENAME
```

Consumer's `conanfile.py`:

```python
import os
from conan.tools.cmake import CMakeToolchain

class MyEmbeddedApp(ConanFile):
    python_requires = 'my-linker-script/1.0.0'

    def generate(self):
        tc = CMakeToolchain(self)
        if self.settings.os == "baremetal":
            linker_script_package_path = self.python_requires["'my-linker-script"].path
            tc = self.python_requires[
                "my-linker-script"
            ].module.add_linker_script(tc, linker_script_package_path, os.getcwd())
        tc.generate()
```

**Comment by memsharded** [comment]
I see, yes, maybe a built-in "LinkerScripts" block in ``CMakeToolchain`` can simplify a bit the above:

- This block would be empty by default
- Only users adding the path to a linker script would activate it
- It should probably define better CONAN_ var than CMAKE_ var
- The definition of the linker script could come from different places, from the current recipe itself, or it could be provided by the python_requires, but for the toolchain, it should be agnostic.

Sounds a relatively easy feature to contribute if anyone wants to give it a try.

In future works we could add some [conf] maybe to define this from profiles too, but probably better develop first this part.

**Comment by jwillikers** [comment]
Just a note that allowing multiple linker scripts would be fantastic.
