### ISSUE TITLE
[bug] CMakeToolchain default BUILD_SHARED_LIBS to OFF when building for bare-metal targets

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#9790]
### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora Silverblue 35
  * Compiler+version: GCC 11
  * Conan version: 1.41.0
  * Python version: 3.10

Bare-metal targets don't usually have the ability to link to shared libraries, so it would probably make sense to default this to OFF in the CMakeToolchain generator when this is the case.

**Comment by AbrilRBS** [comment]
Closing - At least in Conan 2, the CMakeToolchain block that controls shared behaviour looks like this:

```py
    ...
    template = textwrap.dedent("""
        message(STATUS "Conan toolchain: Setting BUILD_SHARED_LIBS = {{ shared_libs }}")
        set(BUILD_SHARED_LIBS {{ shared_libs }} CACHE BOOL "Build shared libraries")
        """)

    def context(self):
        try:
            shared_libs = "ON" if self._conanfile.options.shared else "OFF"
            return {"shared_libs": shared_libs}
        except ConanException:
            return None
```

So it's explicitly left to the recipes to control this behaviour - If a recipe is properly baremetal aware, it will either have logic to control its default value of the option, or have shared = False by default already
