### ISSUE TITLE
[feature] Consider enabling CMAKE_POSITION_INDEPENDENT_CODE in CMakeToolchain explicitly even when building shared

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#9810]
Currently, the CMakeToolchain generator only sets `CMAKE_POSITION_INDEPENDENT_CODE` option when building a project statically when the `shared` option is false.
When the `shared` option is true, `CMAKE_POSITION_INDEPENDENT_CODE` is not configured.
For simple, single library projects this is not an issue because the only library built is shared.
However, for larger, more complex projects containing multiple libraries, some libraries may be configured to be built statically with `add_library(my-lib STATIC)`.
When these are linked in to a final, shared library, Position Independent Code must be enabled, of course.
The linker will error-out if it is not.
To ensure these kinds of projects play well with the CMakeToolchain generator, I think that `CMAKE_POSITION_INDEPENDENT_CODE` should still be enabled by default when building shared libraries.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I think I agree with this.

Current implementation is:

```python
        shared = self._conanfile.options.get_safe("shared")
        if shared:
            self._conanfile.output.warn("Toolchain: Ignoring fPIC option defined "
                                        "for a shared library")
            return None
```
I see no apparent reason why if ``option.fPIC=True`` the CMAKE_POSITION_INDEPENDENT_CODE shouldn't be ON.
