### ISSUE TITLE
[question] How come conan create lock requires access to remotes?

### ISSUE THREAD

**Issue by tolstikh** [conan-io/conan#9812]
I am trying to execute the command `conan lock create conanfile.py -pr=<profile> --base --lockfile-out=<lockfile path>` while my wifi is off, and I get a message saying `Unable to connect to ....` saying that my remotes aren't reachable. Please note that I am not using the `--update` flag.

How come this command needs to be able to access remotes? Assuming all recipes referenced in my `conanfile.py` are in my cache, I would not need to download any recipes. What is this request to the remotes for?

This is on macOS, and my conan version is 1.40.2

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @tolstikh 

Yes, this shouldn't be the case, if everything is locally cached. We have encountered so far that it seems to be an exception (difficult to fix at the moment) when the feature ``compatible_packages`` is being used. Are you using it at the moment?

Otherwise, this shouldn't happen, can you reproduce this in a simple scenario? Thanks!

**Comment by tolstikh** [comment]
Hey @memsharded,

I'm not making use of compatible_packages, here's my repro.

conanfile.txt:
```
[requires]
protobuf/3.17.1
```

steps:
1. `conan download "protobuf/3.17.1@" -re -r conancenter`
2. disconnect from internet
3. `conan lock create conanfile.txt --base --lockfile-out=lock`

Thanks!

**Comment by memsharded** [comment]
Hi @tolstikh 

``protobuf`` has transitive dependency to ``zlib``. A ``conan download`` does not fetch transitive dependencies, only the referenced one. You need to install it, instead of downloading, because otherwise ``zlib`` will not be in the cache.

**Comment by tolstikh** [comment]
@memsharded Apologies, that was a bad example. We can replace `protobuf` here with `zlib/1.2.11` and get the same result.

You can even connect to the internet, lock successfully, disconnect from internet, and be unable to lock.

**Comment by memsharded** [comment]
I think I understand what is happening:

- You are using the ``-re`` argument, which means: "recipe-only". It is not downloading any binary at all, so the package is not fully there.
- You are disconnecting from the internet, but not actually disabling the remote. It is different.
- If Conan is locking something, first it will lock the recipe, fine. Then it will try to resolve the package binary, and unless you explicitly specify that it is being built from sources, it will try to locate a valid binary, and lock it
- If the remote is not disabled, it will try to look for valid binaries to look (same as an ``install`` would do), in the server.
- As the network is down, it will fail. This is expected, Conan doesn't want to hide network or server failures implicitly, users must ``conan remote disable`` those for continuing without failure.

**Comment by tolstikh** [comment]
Thanks for the details.

There still something I don't understand, I am doing a base lock with the `--base` flag, so it seems like only the recipes and not any binaries should be needed for this process. How come there's an expectation of binaries?

Also, even if I build my binaries ahead of time, and even if I add `--build=missing` to the `conan lock create` command, I get the same network error. It seems like no matter what `conan lock` wants to be able to connect to a remote.

**Comment by memsharded** [comment]
> There still something I don't understand, I am doing a base lock with the --base flag, so it seems like only the recipes and not any binaries should be needed for this process. How come there's an expectation of binaries?

Yes, this is true. The ``--base`` flag is a simplification of the principal lockfile, that was implemented later as a variant. The graph is still fully computed, and binaries need to be resolved. This will change in Conan 2.0, but at the moment cannot be changed.

> Also, even if I build my binaries ahead of time, and even if I add --build=missing to the conan lock create command, I get the same network error. It seems like no matter what conan lock wants to be able to connect to a remote.

Because ``--build=missing`` policy still checks for binaries in the servers, if they are found they are not missing and they don't need to be built. It would be necessary to do ``--build`` to force the rebuild of everything to avoid hitting the server looking for binaries.

**Comment by tolstikh** [comment]
>This will change in Conan 2.0, but at the moment cannot be changed.

Great! That will be a welcome change for a decentralized package manager.

>It would be necessary to do --build to force the rebuild of everything to avoid hitting the server looking for binaries.

I can confirm that `--build` allows me to lock when disconnected from the internet. Are there any other consequences to setting that flag? If not, perhaps that should be set as default behaviour. To me it seems that the availability of a binary package is incidental to locking, given that you can determine the needed package ID without actually building anything.

**Comment by memsharded** [comment]
> I can confirm that --build allows me to lock when disconnected from the internet. Are there any other consequences to setting that flag? If not, perhaps that should be set. To me it seems that the availability of a binary package is incidental to locking, given that you can determine the needed package ID without actually building anything.

Not always. There are some corner cases, like when using the ``package_revision_mode`` that without building the upstream packages won't be able to compute the downstream ``package_id``. We would also like to get rid of this case, maybe in 2.0, we will see...

One consequence of using ``--build`` is that the package_revisions will not be locked. That is not a problem if not relying on using different package_revisions, which is not recommended and should only happen in uncontrolled (a bit pathological) environments.

**Comment by tolstikh** [comment]
Thanks @memsharded for answering my questions, its much appreciated. I have a clearer picture of the situation.
