### ISSUE TITLE
[question] Will there be ways to build various configurations in cmake_layout / layouts simultaneously?

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#9814]
The current [cmake_layout](https://docs.conan.io/en/latest/reference/conanfile/tools/layout.html#predefined-layouts) functionality creates unique build directories per `build_type` such as `cmake-build-debug` and `cmake-build-release`.
This integrates very well with CLion, but doesn't allow having build directories based on any of the other configuration settings or options simultaneously.
One common use case I have is to have multiple compiler directories, too, so that I can have both Clang and GCC builds at the same time.
Given the numerous settings and package options, does it make sense to support having more build configurations in more build directories simultaneously for the pre-canned cmake_layout / layouts in general?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jwillikers 

Yes, it should allow it, why you say it doesn't allow it? For example, if you see the built-in layouts in https://github.com/conan-io/conan/blob/develop/conan/tools/layout/__init__.py, they use other settings like the ``compiler`` or the ``arch`` to define build folders. I don't see any specific reason why you couldn't condition the layout on any settings and options (maybe even the ``conf``?).

While possible to define different folders for different compiler versions, what we are trying to do with the built-in layouts, is to reproduce the standard, expected layout that is produced with the most popular tools, CMake, VS, CLion, etc. Take into account that for some part of the local flow, like when you are calling CMake or VS, conan does nothing, so it cannot change or define the folder. The ``layout()`` mostly describe the location of things, but does not necessarily can completely define or force such location for all cases.

**Comment by jwillikers** [comment]
That mostly makes sense. Thanks for the link. The part I'm trying to understand is how layouts differentiate among various options / settings a consumer might impose on them. How does it know, for instance, that the directory `cmake-build-debug` is built `shared=True` vs `shared=False`?

**Comment by memsharded** [comment]
Differentiating builds like shared vs static is something that has typically required custom configurations. Both CMake and Visual Studio have this possibility, and it is typical to find out there projects with custom configurations such ``ReleaseDLL`` (in Visual, for example), that accounts for the Release configuration + shared linkage. Once a custom configuration is defined, the layouts will naturally follow. There is already provision for custom configurations in CMakeDeps and MSBuildDeps. (check for example https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#configurations)

**Comment by jwillikers** [comment]
So, considering other settings / options besides `shared`, individual configurations, i.e. `build_type`s, should be made to enumerate these to integrate with an IDE? So the configurations `ReleaseStaticfPIC` and `ReleaseStatic` might be created to indicate the build type, shared option, and fPIC option? I'm concerned my build configurations will end up being named according to their hash values as they are in the Conan cache :) In practice, there are likely to only be a few primary ones... but considering all the different Google Sanitizers and potential package options... that could be quite a few configurations to enumerate, but perhaps that's outside Conan's scope.

**Comment by memsharded** [comment]
Yes, you are right. Note that the ``layouts`` should mimic the common practice for developers. I think it is very usual to assume the current developer checkout is for a given set of configurations, and only allowing very limited set of variability. Release/Debug in most cases. Maybe adding the ReleaseDLL in some others. But for example to support different compiler versions or compiling with/without fPIC, it has always been typical to have multiple separate checkouts of the project, each one for a different configuration. 

As you well said, Conan provides the capability of implementing automatic folder layout for your desired configurations, but this is still a user decision, that needs to balance between complexity, allowing different flows, supporting the team of developers... Conan doesn't want to take this decision for the user, but instead given them full power to implement what they consider.

**Comment by 0x8000-0000** [comment]
> Yes, you are right. Note that the `layouts` should mimic the common practice for developers. I think it is very usual to assume the current developer checkout is for a given set of configurations, and only allowing very limited set of variability. Release/Debug in most cases. Maybe adding the ReleaseDLL in some others. But for example to support different compiler versions or compiling with/without fPIC, it has always been typical to have multiple separate checkouts of the project, each one for a different configuration.

I am not familiar with the practice indicated above. In our team, it is actually quite typical to have a worktree (git clone) with several parallel build directories.

For example, I'm working on foo project so I have:

     ~/work/foo
     ~/work/foo.clang.13.dbg
     ~/work/foo.clang.13.asan
     ~/work/foo.gcc.11.relinfo

Only the editor touches ~/work/foo - there are no binary artifacts in there, ever. All the binaries are in the foo.$compiler.$extra_topping directories.

The current Conan behavior of creating a ~/work/foo/cmake-build-debug is quite confusing, especially when I'm running "conan install ../foo" from ~/work/foo.clang.13.dbg.

Is there a way to tell Conan to not write anything in the source tree?

**Comment by 0x8000-0000** [comment]
Note that "building in tree" is an old source code management anti-pattern - which many build systems now actively advise against.

**Comment by memsharded** [comment]
Hi @0x8000-0000 

Yes, there are 2 options, depending on how you want to manage it:

- You can encode your ``self.folders.build`` in your ``layout()`` method with something like this:
   ```python
   def layout(self):
        cmake_layout(self)
        self.folders.build = "../{}.{}.{}".format(self.name, self.settings.compiler, 
                                                  self.settings.compiler.version)
        self.folders.generators = os.path.join(self.folders.build, "conan")
   ```
   I have tested, and it seems to do the work, just ``conan install .`` + ``conan build .`` and it will work

- Or you can encode only part of that in the ``layout()`` method, and then use the ``--output-folder=xxx`` argument in the command line to define the root build folder that will be used (composed with the relative ``self.folders.build`` defined in the recipe.


> Note that "building in tree" is an old source code management anti-pattern - which many build systems now actively advise against.

That is partially true, what is really the anti-pattern is building in exactly the same directory as the source. Building in a subdirectory of the source code such as ``build`` or ``cmake-build-debug`` is a common practice even followed by modern IDEs. This is understandable from the maintenance point of view, whatever is cloned and built, remains inside the same repo, and a couple of .gitignore patterns will keep things clean. 

In any case, Conan aims to support both, please try the above and let us know.

**Comment by 0x8000-0000** [comment]
Hi @memsharded 

That seems to work, but where should I run `conan install .` ? In the source tree? It still generates conaninfo.txt which contains the compiler name, compiler version and build_type, in the source directory, and that would be overwritten when I run it with different settings - won't that create problems?

Sorry to bother you, but can you give an example:
1. creating a simple project using `conan new -m cmake_exe foo/1.0`,
2. then modifying the generated `conanfile.py`, with the proposed layout
3. then building for two different compilers (Clang13 and Gcc11) and different build types (Debug and Release)?

I can understand having all the bits in /path/to/source/build/$flavor, but we need to be able to support multiple flavors at the same time, without cloning the repo multiple times.

**Comment by memsharded** [comment]
> It still generates conaninfo.txt which contains the compiler name, compiler version and build_type, in the source directory, and that would be overwritten when I run it with different settings - won't that create problems?

Conan 2.0 will be mostly independent of the cwd, because it will use locations referenced to the conanfile, or specified by ``--output-folder``. All those files (conaninfo.txt, conanbuildinfo.txt, graphinfo.json....) are not generated anymore in 2.0, so they will not be an issue to support multi-configuration setups, including multiple flavors of the compiler. 

In Conan 1.X, that can affect the outcome of ``conan build`` because that uses the information cached in those files from the previous ``conan install`. It will use the ``--install-folder`` for that, you if doing ``conan build`` you need to be consistent with that. If you are building yourself with ``cmake`` or calling directly other build system, you are fine, don't need to worry about those files.

**Comment by 0x8000-0000** [comment]
What is the recommended way? To use `conan build`, `cmake` or `ninja`?

**Comment by memsharded** [comment]
> What is the recommended way? To use conan build, cmake or ninja?

The new integrations aim to be as close as possible to the developer experience, that is, the typical flow should be something like ``conan install`` + ``cmake ...`` (then using Ninja, makefiles, or whatever is users choice). ``conan build`` shouldn't be used as developers, except for debugging of the recipe, at most.

**Comment by memsharded** [comment]
``build_folder_vars`` and ``tools.cmake.cmake_layout:build_folder`` new confs (2.2) seems to be the response to this.

I am closing this as solved and stale (2 years now), please create new tickets reporting against Conan 2 as necessary, thanks!
