### ISSUE TITLE
[question] How to add requirement with custom define?

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#9816]
I want `opencv` with enabled opengl but there is no option for that, however, there's a define `WITH_OPENGL` in the code that toggles this (I guess). I wanted to recompile the package from conan center without altering the recipe. Is there a way to do that?

I've tried this:  
```
def package_info(self):
        self.cpp_info.components["opencv"].defines = ["WITH_OPENGL=1"]
```
it didn't help me

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @xahon 

If you are using the ``opencv`` package from ConanCenter, its behavior is controlled via options. From  what I see in the recipe there in https://conan.io/center/opencv, there is no option related for OpenGL, at least in the latest version. If you think this is a necessary thing, this should be moved as a feature request to conan-center-index repo. You will need to report there which specific versions of OpenCV.

Regarding the ``package_info()`` that is information always for the consumers of the current recipe. If you write it in your ``conanfile.py``, it will never affect the dependencies, it will only affect the consumers of the package that you are creating in that recipe.

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you in a while - if anyone has any other question or request, please feel free to create a new issue, we're always happy to help! :)
