### ISSUE TITLE
Improve search for packages on conan.io web page

### ISSUE THREAD

**Issue by CodingSpiderFox** [conan-io/conan#982]
Hello,

when we were searching for the term "boost 1.62" in the package search on web page, we also had other boost versions in the results.

![conanissue](https://cloud.githubusercontent.com/assets/25173078/22926700/13e6e8a2-f2ae-11e6-83dc-c9ccaf208110.png)

What I was expecting was more like that the search checks the result set to contain each of the single words so that I would only see boost 1.62, not the other versions.

Is it suitable to change to this search behaviour?

Thanks a lot and best regards

**Comment by memsharded** [comment]
I think the best would be to use package reference patterns: "boost/1.6*", or "boost*/1.6*". In that way the engine understand it better and will produce correct result. This is also done for consistency with the search from the command line.

**Comment by CodingSpiderFox** [comment]
I agree that it would be better for the search engine. But I think that the
search is not necessarily only used by developers who are familiar with the
versioning scheme.

For most users it might be easier the way I proposed it.

Let's hear some more opinions.

**Comment by lasote** [comment]
Hi @CodingSpiderFox as I said in #985 we are moving to Bintray. On Bintray we will provide a curated `conan-center` repository with quality and approved recipes, our plan is to involve (as much as we can) to the Open Souce community authors, so you will be able to know better what packages are the good ones. It will take some time to get a good number of curated recipes but it will be the global reference c/c++ repository. So, good news!
