### ISSUE TITLE
Do I need to explicitly pip install configparser?

### ISSUE THREAD

**Issue by kobi-ca** [conan-io/conan#9821]
while running conan install, I was missing configparser. pip install-ed it and re-run it and all good.
Is there a way to make sure it's always brought in as part of the conan env?

**Comment by memsharded** [comment]
Hi this is very weird. ``configparser`` is part of the Python installation, it is not a third party package. There is not entry for it in the ``requirements.txt`` python file. 
Which Python installation are you using and in which platform?

**Comment by kobi-ca** [comment]
I accidently had python 2.x as my python's venv. I think the issue lies there. thanks.
