### ISSUE TITLE
[bug] New PkgConfig generator cannot link shaderc

### ISSUE THREAD

**Issue by Makogan** [conan-io/conan#9822]
I am trying to use the new generator but it fails to link against shaderc, the problem does not occur when using the old generator.

The only differences in my conan.py script is replacing

`generators = "pkg_config"`
for
`generators = "PkgConfigDeps" `

### Environment Details (include every applicable attribute)
  * Ubuntu 21,10
  * Compiler+version: g++ 11
  * Conan version: 14.1
  * Python version: 3.9
  * conan shderc version "shaderc/2019.0"

### Steps to reproduce (Include if Applicable)
Use PkgConfigDeps generator to compile a program depending of shaderc

### Logs (Executed commands with output) (Include/Attach if Applicable)
If I run the new generator I get these errors:
/usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/shaderc/2019.0/_/_/build/9798bdb9f8769b606917015aa186d6cb57ec5f9a/source_subfolder/libshaderc_util/src/spirv_tools_wrapper.cc:137: undefined reference to `spvtools::Optimizer::RegisterPerformancePasses()'
/usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/shaderc/2019.0/_/_/build/9798bdb9f8769b606917015aa186d6cb57ec5f9a/source_subfolder/libshaderc_util/src/spirv_tools_wrapper.cc:140: undefined reference to `spvtools::Optimizer::RegisterSizePasses()'
/usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/shaderc/2019.0/_/_/build/9798bdb9f8769b606917015aa186d6cb57ec5f9a/source_subfolder/libshaderc_util/src/spirv_tools_wrapper.cc:146: undefined reference to `spvtools::CreateStripDebugInfoPass()'
/usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/shaderc/2019.0/_/_/build/9798bdb9f8769b606917015aa186d6cb57ec5f9a/source_subfolder/libshaderc_util/src/spirv_tools_wrapper.cc:146: undefined reference to `spvtools::Optimizer::RegisterPass(spvtools::Optimizer::PassToken&&)'
/usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/shaderc/2019.0/_/_/build/9798bdb9f8769b606917015aa186d6cb57ec5f9a/source_subfolder/libshaderc_util/src/spirv_tools_wrapper.cc:146: undefined reference to `spvtools::Optimizer::PassToken::~PassToken()'
/usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/shaderc/2019.0/_/_/build/9798bdb9f8769b606917015aa186d6cb57ec5f9a/source_subfolder/libshaderc_util/src/spirv_tools_wrapper.cc:149: undefined reference to `spvtools::CreateCompactIdsPass()'
/usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/shaderc/2019.0/_/_/build/9798bdb9f8769b606917015aa186d6cb57ec5f9a/source_subfolder/libshaderc_util/src/spirv_tools_wrapper.cc:149: undefined reference to `spvtools::Optimizer::RegisterPass(spvtools::Optimizer::PassToken&&)'
/usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/shaderc/2019.0/_/_/build/9798bdb9f8769b606917015aa186d6cb57ec5f9a/source_subfolder/libshaderc_util/src/spirv_tools_wrapper.cc:149: undefined reference to `spvtools::Optimizer::PassToken::~PassToken()'
/usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/shaderc/2019.0/_/_/build/9798bdb9f8769b606917015aa186d6cb57ec5f9a/source_subfolder/libshaderc_util/src/spirv_tools_wrapper.cc:154: undefined reference to `spvtools::Optimizer::Run(unsigned int const*, unsigned long, std::vector<unsigned int, std::allocator<unsigned int> >*, spv_optimizer_options_t*) const'

**Comment by franramirez688** [comment]
Hi @Makogan 

It would be great if you provide a simple repository to reproduce the bug, so I'll be able to run it easily. For instance, a simple `test.cpp` and a `conanfile.txt` if it's your case, and all the commands which you ran to see that bug.

**Comment by Makogan** [comment]
This issue seems to have stopped with the current shaderc release.
