### ISSUE TITLE
[question] check for a new package version

### ISSUE THREAD

**Issue by snailcatcher** [conan-io/conan#9823]
Hi,

Is it possible to check for a new version of a package without installing it?

So for example:

available packages on artifactory
```
some_package/0.9.0
some_package/1.0.0
some_package/1.0.2
```

my conanfile.txt
```
[requires]
some_package/1.0.0
```

Now what I looking for is a command which I can see that *some_package/1.0.0* has an update to version *1.0.2* without using wildcard versions.

Is this possible?

If not do you have a suggestion how I can build something like this?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Hi @snailcatcher 

For now, as far as I know, it does not exist such command.
You have `conan info . -u` which is showing if there is a new binary package in the remote but this one is not related to a new version at all but changes in the `conanmanifest.txt`.

**Comment by snailcatcher** [comment]
Hi @franramirez688 
Thank you, but this is not exactly what I'm looking for.
I look for something which implements a versioning standard like [semantic versioning](https://semver.org/lang/de/) or something similar.
Is there a plan for a feature like this in conan 1.x or 2.x?

**Comment by memsharded** [comment]
Semver standard and version ranges are supported and implemented in Conan. You only need to define ``requires = "pkg/[version range]"`` in your conanfile for it to resolve. You can install with ``conan install "zlib/[>1 <2]@"`` Or you can query with ``conan info "zlib/[>0]@"``. What could be missing is a ``conan search`` query that supports the semver syntax, and it is wildcard based.

**Comment by snailcatcher** [comment]
Hi @memsharded 
The definition of a wildcard version in the conanfile is not a good solution in my case (safety levels).
Yeah you kind of get the point.

The best solution I know for a similar problem is [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) for the [NPM (NodeJS Package Manager)](https://www.npmjs.com/).

It basically scans all your dependencies in the conanfile (so the names of your packages) and checks if the repository has a newer (higher version) package available. Then it just prints a list of all available updates and the user can decide himself which of them he wants to update. If you want to update a package *npm-check-updates* rewrites the version of this package in the *conanfile* and you have to do a *conan install .* afterwards.

**Comment by AbrilRBS** [comment]
We're now working on implementing `conan graph outdated` command to help with this process in Conan 2

**Comment by memsharded** [comment]
Conan 2.2 has merged https://github.com/conan-io/conan/pull/15838 that implements the ``conan graph outdated`` command for this purpose.
