### ISSUE TITLE
[question] self.dependencies in build(self)

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#9826]
I just learned about the new `self.dependencies` object, which supposed to replace all usage of self.deps_cpp_info (right?).  What is the migration plan for packages being built by random scripts/executables ?
My use case is qt (who would have guessed ?). Qt 5 build procedure is: call a configure script, then make and make install. Most of the `build(self)` method is defining the command line arguments to pass to `configure` (https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/5.x.x/conanfile.py#L600 and following).
AFAIU, `self.dependencies` object won't be available in `build(self)`. Does it mean that the command line has to be created in the `generate(self)` method, saved in an arbitrary file name (in the build folder I guess), and then the `build(self)` method loads this file and transmits all the arguments to configure ?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> AFAIU, self.dependencies object won't be available in build(self). Does it mean that the command line has to be created in the generate(self) method, saved in an arbitrary file name (in the build folder I guess), and then the build(self) method loads this file and transmits all the arguments to configure ?

``self.dependencies`` is partially available now (will work for ``conan create``, but not for ``conan build``) and it will be fully available in ``build()`` in Conan 2.0. Right now it is not possible, as the ``conan build`` command does not compute the graph. But in any case, you are right, the intent is:

- To completely decouple the logic that decides what is going to be built (the ``generate()`` method), from actually calling the actual build (the ``build()`` method). 
- This enables the developer flow in which any developer can do a ``conan install``, and they will mostly have everything generated in place, so they can reproduce a build locally without using Conan at all. It also allows easier developer understanding of what is happening (in the past a ton of stuff was done in env-vars only at runtime, which is more difficult to follow)
- The ``build()`` method should indeed read the necessary files to do the build. The idea is that what is inside of ``build()`` is the same steps as the developer did, and will reduce typically to a thin wrapper around CLI invocations.
