### ISSUE TITLE
Setting CMAKE_BUILD_TYPE in conan_toolchain.cmake file

### ISSUE THREAD

**Issue by kobi-ca** [conan-io/conan#9835]
currently, when I run conan install with conanfile.txt file, my conan_toolchain always shows as 
```
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Choose the type of build." FORCE)
```
How do I config it to be Debug?
```
... -c tools.cmake.cmaketoolchain:build_type=Debug
```
Does not work (I tried all kinds of options)
what is the correct syntax for this?
thanks.

**Comment by kobi-ca** [comment]
OK. I think I found it https://docs.conan.io/en/latest/using_packages/workflows.html
```
-s build_type=Debug
```
I was so close. closing it for now. 
google please index it for the next gen ;)

**Comment by memsharded** [comment]
Hi @kobi-ca 

The ``CMakeToolchain`` generated file depends on a few things, like the settings. Have you passed ``conan install ... -s build_type=Debug``?

EDIT: Nevermind, you were faster than me by 1 sec 😄 

Also, take into account that this will depend on the system. For example, using Visual Studio, as it is a multi-config generator, it will not define the CMAKE_BUILD_TYPE in the toolchain. It is possible then to switch it from the IDE directly (if you installed first both Release and Debug dependencies)

**Comment by kobi-ca** [comment]
yep. building it now. thanks!

**Comment by kobi-ca** [comment]
I slowly grasping the complexity handled by conan and I'm so scared :) 
thanks. 
I have another question. Will open a new issue if I can't find an answer.
