### ISSUE TITLE
Conan search, download, install not working on virtual Artifactory Conan repository

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#9837]
I am using multiple Artifactory systems to host my Conan packages. For easier read access I have a virtual repository in of these systems that contains a few local and a few remote Conan repositories.

When running a conan search or download command I only get the packages from the local repos but none of the remote ones. 
Also when running a conan install the packages that are only located in the remotes are not found which results in an error message.
Are these commands not supporting virtual repositories?

Strangely in the web ui I can see all packages (from local and remote repositories) in the virtual repository but the client does not seem to see it.

Artifactory version (hosting the virtual repo): 6.18.1

Artifactory version (hosting the local repos to which some of the remotes of above Artifactory are pointing to): 7.25.7

Artifactory version (hosting the local repos to which some of the remotes of the top Artifactory are pointing to): Do not know version it just says JFrog Cloud

Conan client version: 1.39.0

Revisions are enabled in Conan client

What is the problem here? Any settings to be changed in the Artifactory virtual or remote repositories?

Thank you

**Comment by MTomBosch** [comment]
Problem is resolved. The remote repo configuration in Artifactory was not correct. It was missed to use the api/conan URL format for the repository like described here: https://www.jfrog.com/confluence/display/JFROG/Smart+Remote+Repositories

**Comment by memsharded** [comment]
Hi @MTomBosch 

Sorry that this issue was not responded, sometimes with so many issue some might be missed. Don't hesitate to post followups if you don't get responses to re-surface the issue. Happy that you managed to solve it.
