### ISSUE TITLE
[question] conandata.yml, changing a single version source, and consistent recipe revisions

### ISSUE THREAD

**Issue by foundry-markf** [conan-io/conan#9845]
Hi,

We have a single Git repository in a similiar style to Conan Center for our recipes. We also make use of version agnostic recipes, and data drive it through conandata.yml with a url and a SHA. We also use `revision_mode="scm"` in recipe, so that we have a 1-1 relationship with recipe revisions and the git commit that resulted in the change. This is all nice.

An edge case, that I've not found an example of anyone else dealing with yet, is as follows:
* version agnostic recipe, with a number of versions in the conandata.yml
* a patch is made to a _single_ version source tree, so we have to update the conandata.yml for a SHA on that version only
* changing the conandata.yml implies a new recipe revision... but, actually, we only care about that for the version that was changed

Up until now, we've just bitten the bullet and rebuilt all versions mentioned in the conandata.yml. However, we do have some large recipes in the mix (e.g. Qt), and so it's not desirable in terms of compute, storage, or dev time, to rebuild versions that haven't actually changed.

Of course, if the recipe itself changed, we'd have to rebuild everything, so this is a bit of an edge case.

So what we're considering is only building the version that changed. That imples, for the given package, we may have different recipe revisions per version. I don't think I see that as a problem, but some colleagues are not sure. It's lovely having a consistent view of a package with a 1-1 mapping from Git to Artifactory, but the cost of rebuilding unnecessarily is starting to raise it's head.

What was the intent from your point of view when developing Conan that the behaviour should be in this scenario?

- always build all versions so revisions are always consistent
- just build specific versions when their source SHA changes, and can have different recipe revisions across versions of a package

Thanks.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @foundry-markf. Let me share my POV from `conan-center-index` experience.

If you are using `revision_mode="scm"` then you are explicitly requesting that behavior: any commit in your Git repository will result in a different revision for every recipe you export from it. There is very little you can do here as you are opting-in that behavior.

What we do in `conan-center-index` is to leave the default `revision_mode`, so only actual changes will modify the recipe revision. We also prune `conandata.yml` file at the time we export the recipe (we use a hook for that), so only the lines corresponding to each version will contribute to its recipe revision. This way, changes that affect only one version won't generate new revisions for the rest of versions.

With this setup, every recipe revision is different for different versions of the same recipe file... and the revision doesn't match the commit in the repository. Ugly? Not so ugly... What we do to be able to track packages from Artifactory to Git is to add a property to every recipe revision, that property is the `scm_commit` and its value is the commit of the repository when the recipe was exported. Of course, it is not as straightforward as your model, but with a little scripting you can abstract this indirection from your developers. Properties are quite a powerful feature of Artifactory.

Hope this helps.

**Comment by foundry-markf** [comment]
Hi @jgsogo ,

Thanks for that write up. I had no idea you did that in conan-center-index.

We have had some properties added to packages in Artifactory in the past, but the limitation I found with it (which admittedly might be lack of knowledge of the tooling) is that I wasn't able to query those from a shell on my machine, whereas I can get a recipe revision from a local cache.

I imagine what you're saying is that you can script from local shell -> local cache -> Artifactory, and return some properties?


What I had failed to mention is, in our tooling, we can specify a SHA to build against, and we use git commands to determine the last commit touching recipe files (which obviously currently does include the conandata.yml). This was to support being able to include additional binaries (say of new compiler versions) into an existing recipe revision, when nothing else has changed. If we always built against the SHA of HEAD of the repo, then we'd be introducing new revisions all the time, which was not desirable.

I was considering updating that tooling so that both existing git commands were used, and then filtering on any changes to the conandata.yml, so that only touched versions were scheduled to build (except in the cases where all versions do need to be rebuilt, e.g. the conanfile.py changes). In my mind, all versions's recipe revisions still refer to the valid SHA that contains the recipe state that built it. It would just mean breaking the model that all versions sharing a recipe are always at the same revision. For example, you could no longer download v1 to a local cache, and expect to be able to build v2 from its state - not something we do, but it is a caveat of the approach.

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2 with the [`trim_conandata()`](https://docs.conan.io/2/reference/tools/files/basic.html#conan-tools-files-trim-conandata) method, which can be used either in recipe's export method, or a post_export hook to ensure that conandata contents are exported only with the relevant version :)
