### ISSUE TITLE
[question] Auto-detect compiler version

### ISSUE THREAD

**Issue by diggeloid** [conan-io/conan#9846]
Hi, I'm wondering if there's a way to have Conan automatically detect the compiler version for you, instead of having to manually specify it as a `-s` flag or profile entry? It seems like the code for detecting the version already exists in [detect.py](https://github.com/conan-io/conan/blob/develop/conans/client/conf/detect.py)

My use case is that I'm trying to integrate Conan into a project with an existing build system that has existing auto-configuration code. However, since the version strings in the default `settings.yml` file are not in any consistent format, and they have to match *exactly* otherwise you get an error, it's very painful to write a function that converts them. For example, clang.version has entries like `9, 10, 11` whereas apple-clang.version has entries like `9.0, 9.1, 10.0, 11.0`. My existing build system normalizes them all to three numbers, like `9.0.0`, `9.1.0`, etc. This means I need to have some big ugly logic to handle each case.

My goal is to have the existing build system invoke `conan install`. This is useful because the build system currently supports multiple cross-build targets, so it has all the information needed to generate a `profile` file for each one. Getting the compiler version strings right is difficult though, so having Conan auto-detect it would be helpful. I know that I can use a custom settings.yml file, but I would prefer not to in this case.

Note: I'm posting this as a question rather than a feature request in case this is already possible, or someone has a workaround.

Thanks

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @diggeloid 

I am not completely sure what you mean. The ``default`` profile that is automatically generated for you the first time is needed, already does the auto-detect, containing the detected compiler version. If you are in a specific build system, and that build system defines some compiler version, then you can run ``conan new profile xxxx --detect`` to run a profile detection, that you can lately use.

However, I don't think this is good practice. We recommend to define and use profile files. You can write such files for the different configurations that you are maintaining, because it is also possible that you will need some extra things that cannot be fully auto-detected (``[conf], [env], etc``). You then "name" your different configuration and abstract that away. You can easily manage profiles and many other stuff (remotes definitions, config, custom settings.yml, hooks, etc), with ``conan config install`` in an easy way to keep in sync everyone.


Maybe the flow of having the build system invoke ``conan install`` is not the best approach. It is only valid for consumer-only flow, but the moment you create a package for one of your build you have a very ugly recursion "build" calls "conan" and conan in turn calls again the "build" system to build from sources. It can work for cases like the conan.cmake project, but exclusively for 
consumers.

**Comment by diggeloid** [comment]
An alternative solution would be to do the manual configuration with Conan profiles first as you recommend, and then have my build system parse those profile files during configuration to find compilers/toolchains/etc. However, that's effectively the same solution, just backwards (conan configures my build system, instead of my build system configuring conan)

Also, unless I'm getting some concepts mixed up here, using a custom settings.yml file opens me up to compatibility issues with existing conan packages, such as those on conan center, right? If there's a package that checks for clang version "12", but I'm using "12.0.0", it won't work. While not impossible to deal with, it would be much nicer if I didn't have to lose access to conan center recipes.

Note that I'm not necessarily planning to call `conan install` on build. I don't know how most people use Conan, but I'd assume it's something like this:

* clone/download a project
* execute `conan install --profile:build=<target>` once
* execute the project's `configure(<target>)` process once
* execute the build for that target

My intention is to do the same thing, except I combine the configuration and `conan install` steps into one. If my project supports 4 build targets, but the local development machine can only build for two, then `conan install` will be called twice, once for each target. That doesn't seem like such a crazy/weird thing IMO, especially in a cross building **consumer-only** scenario like this.

The only part that feels hacky to me is that I'm generating a file meant to be written by hand. This is required AFAIK because the flags `os_target`, `arch_target`, etc are deprecated, and the only way to activate a cross build going forward is via `--profile:build`. (relevant issue is #9808)

For reference, the build system I'm working with is [waf](https://waf.io). This supports build _variants_, so if properly configured, I can execute a command like `waf build_android_arm64`, or `waf build_host_x86`. Each target potentially has different conanfiles (different dependencies), and during development I need to be able to configure and build multiple targets. This all already works, but I'm only using Conan for host builds at the moment. I'd like to manage all dependencies exclusively with Conan.

Really, the only issue I'm having currently is the difficulty of matching compiler version strings how conan expects them (in the default profile). If I give it a compiler, Conan should be able to detect the version automatically.

I'll be looking into `conan new profile xxxx --detect` to see if it helps me, thanks for the suggestion.

**Comment by memsharded** [comment]
> Also, unless I'm getting some concepts mixed up here, using a custom settings.yml file opens me up to compatibility issues with existing conan packages, such as those on conan center, right? If there's a package that checks for clang version "12", but I'm using "12.0.0", it won't work. While not impossible to deal with, it would be much nicer if I didn't have to lose access to conan center recipes.

Yes, ConanCenter builds binaries with a set of assumptions. You don't need to lose access to conan center recipes, but you can still use them to build your own binaries for your own custom configurations, even incrementing the binary configurations. For example, you can define a ``os.distro`` subsetting like described in https://docs.conan.io/en/latest/extending/custom_settings.html#adding-new-sub-settings, and then you can start maintaining binaries for different linux distros as RH6/Centos and others. Without really needing to modify the recipes. I'd also strongly recommend to store a copy of the packages you use in your own Artifactory (CE edition is completely free), together with your other potential private packages for a fully controlled and robust build.

**Comment by memsharded** [comment]
I am closing this as staled/outdated.

Also, Conan 2 has implemented new capabilities, like ``detect_api`` available in the profiles via ``jinja``, a ``profile.py`` plugin.

Please re-open or create new tickets if there are any further questions, thanks for the feedback!
