### ISSUE TITLE
[feature] Maintenance for meta-conan layer

### ISSUE THREAD

**Issue by mairacanal** [conan-io/conan#9847]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Currently, the meta-conan layer is barely maintained, considering that the issues and pull requests are not answered and Conan is on version 1.35. Beyond that, the example in the website doesn't work at all, because the version of Conan is outdated.

The website example is not working, because it depends on an outdated version of the library fasteners and there is an [issue](https://github.com/conan-io/meta-conan/issues/16) about this problem.

Therefore, I would suggest the attribution of someone from the Conan team to be responsible for the maintenance of the layer and, also, I would like to help in the maintenance of the layer, helping it to stay up to date and answer issues in general.

**Comment by memsharded** [comment]
Hhi @mairacanal 

Yes, it is true that this is not getting enough attention at the moment. But it is also true that we are also overwhelmed with the continous Conan growth, and we are prioritizing now things like ConanCenter and Conan 2.0 development, which first alpha release is very close.

Thanks very much for pointing these issues. Of course it would be fantastic if you could help with support and maintenance of the layer, the truth is that we know there are some Conan users out there that start from it, start evolving and maintaining, but never contribute back, so this is really appreciated.

I am pinging @tapia, maybe @uilianries could keep an eye on this repo issues, and help contributors and other users, if not doing efforts on the dev side, at least reviewing and supporting?

**Comment by uilianries** [comment]
Olá @mairacanal! Saudações tupiniquim!

I'll start to take a look on meta-conan layer. I worked with Buildroot for years, but integrating Conan and Yocto is indeed amazing.

Thank you for pinging us! Até logo!

**Comment by mairacanal** [comment]
I submitted a patch about a month ago into meta-openembedded that fixed the problem with the python3-fasteners library. So, the dunfell branch is probably working now. I believe now the meta-conan layer could be updated to new versions of Yocto to guarantee the support of the layer.

**Comment by uilianries** [comment]
Amazing! Thank you!

**Comment by tapia** [comment]
This issue is about meta-conan / yocto support, and @uilianries has been assigned to this, so I think this can be closed. Please feel free to reopen if you think it's necessary.

**Comment by purplefishies** [comment]
> Author
> ### [<img alt="@mairacanal" width="20" height="20" src="https://avatars.githubusercontent.com/u/61601791?s=60&amp;u=5e33e913898217326d1309e70acff7c139d3f298&amp;v=4">](/mairacanal) ** [mairacanal](/mairacanal) ** commented [on Dec 6, 2021](#issuecomment-986855003)

Was there an open PR for meta-openembedded with this fix  @mairacanal   ? We're blocked by the same problem trying to get conan to build our system.
