### ISSUE TITLE
[feature] introduce alias for PkgConfigDeps

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#9848]
**Issue**: The current PkgConfigDeps scopes the `pc` files with the name of the package, but people, specially from open source and conan-center, want to consume "crypto.pc" not "openssl-crypto.pc", otherwise every consumer would need to modify the build system script.

**Proposal**

1. Keep generating files scoped, always, and a global one that include all the components:

With components:
```
self.cpp_info.components["crypto"] => "openssl-crypto.pc"
self.cpp_info.components["ssl"] => "openssl-ssl.pc"
self.cpp_info.components["tls"] => "openssl-tls.pc"
self.cpp_info.components["openssl"] => "openssl-openssl.pc"
"openssl.pc" => include all components
```
 
Without components:

```
"openssl.pc" => Declares the information using the same template of the components
```

 2. Enable a new property `pkg_config_aliases` similar to `cmake_target_aliases` (@SSE4) only when the user **really want** to declare a `pc` file without scope. This will be done in conan center in very special cases where the `pc` file is kind of a "standard". Any alias to `core` or things like that should be avoided.
 
```
self.cpp_info.components["crypto"].set_property("pkg_config_aliases", ["crypto"]) => "crypto.pc" includes "openssl-crypto.pc"
self.cpp_info.set_property("pkg_config_aliases", ["bar"]) => "bar.pc" includes "openssl.pc"
```

3. There is another special case where the recipe wants to declare a `foo.pc` but including only specific component/s, not to all of them, for example, the "core" component but not some optionals. In that case:

```
self.cpp_info.components["core"] => "foo-core.pc"
self.cpp_info.components["other"] => "foo-other.pc"
self.cpp_info.components["core"].set_property("pkg_config_aliases", ["foo"]) => "foo.pc" include to "foo-core.pc"  

In this case the `foo.pc` overwrite the global `foo.pc`.

**Comment by franramirez688** [comment]
For now, it's blocked by https://github.com/conan-io/conan/pull/9851

**Comment by franramirez688** [comment]
Actually, it was not blocked by that MR. It can be developed without having it merged
