### ISSUE TITLE
Navigation back on conan.io leads to wrong results page when searching for different terms

### ISSUE THREAD

**Issue by CodingSpiderFox** [conan-io/conan#985]
Reproduce:
Go to https://www.conan.io/.
Enter "boost" in the search box at the top

Notice that the url changes to https://www.conan.io/search?q=**boost**

Enter "openssl". Notice that the URL stays the same but the search result is updated correctly

![conanissue2](https://cloud.githubusercontent.com/assets/25173078/22928509/1e4a8098-f2b7-11e6-9d51-70411871998c.png)

Now click on one of the results. You are directed to the packages' page.
Now navigate back in browser (Alt+Left Arrow). You are directed to the results page for "boost"

What I was expecting is that I see the openssl search results. 

Suggested fix: Update URL to search page every time a new search is done.

**Comment by CodingSpiderFox** [comment]
Any news on this one?

**Comment by lasote** [comment]
In our roadmap are important changes to the Conan website so, yes, keep tuned.

**Comment by lasote** [comment]
HI, @CodingSpiderFox  as you can see on the homepage we are moving to Bintray. Bintray offers many many improvements from the current [conan.io](https://www.conan.io/) site, and also there is a great team maintaining it, so we should close this issue and see if Bintray cover better your needs. 

Thanks!
