### ISSUE TITLE
The `--install` command line argument isn't available in the earlier CMake versions

### ISSUE THREAD

**Issue by yowidin** [conan-io/conan#9850]
I'm trying to check out the new and blessed packaging approach and having an issue with the `cmake.install()` call inside the `package()` method on older systems.

My recipe works fine with the `cmake version 3.17.3` and breaks when used with `cmake version 3.13.4`.
Of course replacing the `cmake.install()` call with the `cmake.build(target='install')` call fixes the issue.

The `--install` command line argument isn't available in earlier versions of the CMake, it was probably introduced only in CMake 3.15 please consider changing the call back to a build call with the `install` target.

_Originally posted by @yowidin in https://github.com/conan-io/conan/pull/9668#r734494991_

**Comment by memsharded** [comment]
Hi @yowidin 

yes, this is expected. All the new integrations work with CMake > 3.15, this was discussed and approved by the Tribe: https://github.com/conan-io/tribe/pull/4

We need to set a base version to be able to test and develop correctly, and we settled for 3.15. Please upgrade CMake to use the modern integrations (and also for Conan 2.0) (you might use ``conan install cmake/3.15... -g VirtualRunEnv`` to install it)

**Comment by yowidin** [comment]
Okay, but the documentation is a bit outdated on that front:

https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake.html#install:
> Equivalent to run cmake --build . --target=install

**Comment by yowidin** [comment]
Closing the issue, since the change is intentional.
