### ISSUE TITLE
[question] How to create a lockfile properly

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#9854]
Hi Conan experts,

at present I'm creating a lock file as follows:

```
conan lock create ./path/to/conanfile.py --version 1.0.0 --user user --channel stable --options my_option=True --lockfile-out my.lock
```

However, this is not perfect, as my recipe uses the `self.scm.revision` attribute of my `conanfile.py` as option for another requirement. Using the `lock` method above, just gives me `auto` as value for the `revision` attribute.

I know that I'm also able to use the `reference` attribute as follows:

```
conan create ...
conan lock create --reference my_package/1.0.0@user/stable --options my_option=True --lockfile-out my.lock
```

However, using that provides me the correct `revision` value, but it lacks the `build_requires` information in the lock file. It seems that I'm searching for a mixture of both approaches.

Am I doing something wrong? Is it possible to achieve what I want to do with current version of Conan (I'm using `1.38.0` by the way)?

Many thanks for clarification and your answers.

Best regards,
gpxricky

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by gpxricky** [comment]
@memsharded Sorry to ask you directly, but do you know some recommendations how to solve my problem and properly create a lockfile that provides both, valid options and build dependencies?

**Comment by memsharded** [comment]
Sorry @gpxricky this was not responded back then, sometimes the work load is too high and some tickets fall through the cracks.

This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
