### ISSUE TITLE
[question] Access environment variables in layout.ini

### ISSUE THREAD

**Issue by asanka424** [conan-io/conan#9857]
Hi,
Is it possible to access environment variables in layout.ini? If so how do I do that.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @asanka424 

It is not possible to access env-vars from those ini files. In any case, it seems you are looking at the legacy way of defining editables, which is deprecated and superseded by the new ``layout()`` method, please have a look to https://docs.conan.io/en/latest/developing_packages/editable_packages.html.

**Comment by memsharded** [comment]
``layout.ini`` was deprecated long time ago in favor of ``layout()`` method, closing as outdated
