### ISSUE TITLE
There's an error when I exec conan search 'cro*' --remote=conancenter 

### ISSUE THREAD

**Issue by wxuefei** [conan-io/conan#9863]
### Environment Details (include every applicable attribute)
  * Operating System+version: mac
  * Compiler+version:
  * Conan version: 1.41.0
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
conan search 'cro*' --remote=conancenter

### Logs (Executed commands with output) (Include/Attach if Applicable)
ERROR: Value provided for package version, '0.3 2' (type Version), is an invalid name. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash. [Remote: conancenter]

**Comment by czoido** [comment]
Hi @wxuefei,
I was able to reproduce the issue. Looks like it's caused by recipe for `crowcpp-crow` having version `0.3+2` so `conan search crowcpp-crow -r conancenter` also reproduces that.
We'll check how to fix this, thanks a lot for reporting.

**Comment by tapia** [comment]
It was a package in the Conan Center remote with a wrong version string (`crowcpp-crow 0.3 2`, with a space between the 3 and the 2). It's already fixed.
