### ISSUE TITLE
[bug] hook_manager overrides sys.dont_write_bytecode

### ISSUE THREAD

**Issue by StailGot** [conan-io/conan#9864]
Hi there. 

Im trying make portable conan in windows for seamless setup.
With embedded python it work perfect, but as it part of source code, it must not modify source dir.
When python commands execute, by default generate `__pycache__` dir for optimization.

There some options for disable that.
Run python with -B option or export env PYTHONDONTWRITEBYTECODE=1
Almost works, but conan\tools ignore this settings. After diging, i found that "\conans\client\hook_manager.py" overrides this settings to False

```python
    def _load_module_from_file(hook_path):
     ...
        finally:
            sys.dont_write_bytecode = False
            sys.path.pop()
```

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Pro 20H2 19042.508
  * Conan version: 1.41
  * Python version: 3.10

### Steps to reproduce (Include if Applicable)
1. Disable generation bitecode ( `__pycache__` ) with python -B or export PYTHONDONTWRITEBYTECODE=1
2. Run `conan install` command
3. Dir `conan\tools` contains __pycache__

**Comment by memsharded** [comment]
You are right, seems the previous existing value should be respected. Proposing a fix in https://github.com/conan-io/conan/pull/9865 for next 1.42
