### ISSUE TITLE
[question] How to deal with "-lc++abi" flag when compiling with clang and libc++ on a gcc based linux distro?

### ISSUE THREAD

**Issue by werto87** [conan-io/conan#9867]
I am on arch linux where the gcc toolchain is the default.
I have a clang profile for compiling with clang and libc++
clang
```
[settings]
os=Linux
arch=x86_64
compiler=clang
compiler.version=12
compiler.libcxx=libc++
[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
```
I have problems to create some packages. For example imgui/1.85.
The error I am getting is:
`/usr/bin/ld: /tmp/binary_to_compressed_c-10eaa8.o: undefined reference to symbol '_ZdaPv'
/usr/bin/ld: /usr/local/lib/libc++abi.so.1: error adding symbols: DSO missing from command line
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
`
This can be reproduced without conan by trying to compile this file from [imgui](https://github.com/ocornut/imgui/blob/99552420a259076e6a622ec3f9a1a1be14853198/misc/fonts/binary_to_compressed_c.cpp)
like this:
`clang++ -stdlib=libc++ binary_to_compressed_c.cpp`
The  solution is to add the flag "-lc++abi"
`clang++ -stdlib=libc++ -lc++abi  binary_to_compressed_c.cpp`

**Question**
How to add the flag "-lc++abi"? 
Should I change the recipe for imgui and make a pull request?
Imgui is not the only recipe where this happens. Maybe conan could do something to append "-lc++abi" when "compiler.libcxx=libc++" is set?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @werto87 

It might be that the ``imgui`` recipe in ConanCenter is not prepared to compile with Clang with a different stdlibc++, maybe the build system has hardcoded the standard lib it is using.

So the best to investigate and reproduce this things is with a minimal example. I recommend using the ``conan new hello/0.1 --template=cmake_lib`` to create one and start from there. That template is also using the modern integrations with CMake which are the ones that are being developed now, the previous ones, like the ones used in ConanCenter will be deprecated.

**Comment by werto87** [comment]
Hi @memsharded,
I installed another version of libc++ and now I do not need to specify the flag "-lc++abi" to link.

**Comment by memsharded** [comment]
> I installed another version of libc++ and now I do not need to specify the flag "-lc++abi" to link.

Ok, good to know. If you experience some related issue or have any further question, please file a new issue. In any case, please keep in mind that the new integrations will be better maintained from now on, but ConanCenter recipes haven't started to migrate to the new integrations yet (they will do soon). Thanks for following up!
