### ISSUE TITLE
[question] Managing dependency that is needed for both runtime and build time when cross-compiling

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#9877]
Can a recipe have a dependency that is both runtime, and build time? Take CUDA, for example -- if we are to have a CUDA package we'd need an x86_64 one that contains nvcc and other tools, and then another one, targeting arm64.

So, can we do both 
`self.build_requires("cuda/10.2@org/master")`
and
`self.requires("cuda/10.2@org/master")` ?

How would self.deps_cpp_info for the build environment be accessible?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, it is possible. You might need to use the 2 profiles, build and host profiles, and then you will have 2 different packages of cuda, one for each platform. Then, you need to go with the new integrations ``VirtualBuildEnv``, ``VirtualRunEnv``, and always using ``self.dependencies``, not ``self.deps_cpp_info``: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html

In this video, from this time, this cross-build model is explained: https://youtu.be/VzUJQw89U7o?t=3187

**Comment by memsharded** [comment]
I hope the above answer helped, closing this ticket as solved.

This has been even explicitly documented in Conan 2 docs in https://docs.conan.io/2/examples/graph/tool_requires/using_protobuf.html

Closing, please create new tickets as necessary for any further question, thanks for the feedback!
