### ISSUE TITLE
[bug] Strange error with supposedly missing package

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#9893]
I have a very strange error with a supposedly missing package on the server.
The recipe in choice has a `build_requires` for `cmake`, and our `cmake` recipe has the `os_build` setting only (we haven`t gotten round to using two profiles yet).

```
(.venv) D:\test\_build>conan install ..
conanfile.py (test/None): Installing package
Requirements
Python requires
    conan-stuff/0.0.15@user/stable
    cmake-presets-generator/0.1.0@user/stable
Packages
Build requirements
    cmake/3.16.3@user/stable from local cache - Cache
Build requirements packages
    cmake/3.16.3@user/stable:355ab648bf8c98510260e7d85dd2c3a82b395d3f - Missing

Installing (downloading, building) binaries...
ERROR: Missing binary: cmake/3.16.3@user/stable:355ab648bf8c98510260e7d85dd2c3a82b395d3f

cmake/3.16.3@user/stable: WARN: Can't find a 'cmake/3.16.3@user/stable' package for the specified settings, options and dependencies:
- Settings: os_build=Windows
- Options:
- Dependencies:
- Requirements:
- Package ID: 355ab648bf8c98510260e7d85dd2c3a82b395d3f

ERROR: Missing prebuilt package for 'cmake/3.16.3@user/stable'
Try to build from sources with '--build=cmake'
Use 'conan search <reference> --table table.html'
Or read 'http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

(.venv) D:\test\_build> conan search cmake/3.16.3@user/stable -r artifactory
Existing packages for recipe cmake/3.16.3@user/stable:

Existing recipe in remote 'artifactory':

    Package_ID: 355ab648bf8c98510260e7d85dd2c3a82b395d3f
        [settings]
            os_build: Windows
        Outdated from recipe: False

    Package_ID: e51e0b019543506c55754e1480cc38d504d97497
        [settings]
            os_build: Linux
        Outdated from recipe: False
```

It complains about missing package, also the ID it is looking for does exist on the server. This is the latest Conan Version. Am I missing something? Conan search, that the package, with the correct package ID is there, on the server (and the server is listed in my remotes). Any ideas?

My profile has
```
[settings]
os=Windows
os_build=Windows
```

**Comment by memsharded** [comment]
Can you try removing the local cache ``cmake/3.16.3@user/stable`` recipe, and try again, so we can see what the ``conan install ..`` output is saying? A possibility is that for some reason the local recipe got disconnected from the server, and it is not even checking? Something else to try would be with ``--update``

**Comment by KerstinKeller** [comment]
Ah thanks for the quick reply, `--update` didn`t help, but deleting the recipe did. It must have somehow been different from the server.
What's a good way to find out, in conan commands? I guess then the RREV must have been different.

**Comment by memsharded** [comment]
Maybe ``conan remote list_ref`` can tell you the remotes that were used to install the recipe, and it might not show such remote. I suspect that this is something that can happen if:
- A package recipe is installed from remote
- The remote is removed, the recipe is dissasociated from the remote
- Next install, conan thinks the recipe is local (as created with ``conan export``), and as such, it won't look for it in the server, but expects binaries to be local too?
It could also totally be something related to the specific revision, that was not found in the server (the ``conan search`` returns latest revision results), but the ``conan install`` will look for binaries belonging to that revision.
