### ISSUE TITLE
[bug] Option value None is parsed as string

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#9900]
When an option value is passed as `None`, it's automatically converted to string. Conan client should honor the original type to avoid prone errors. Same behavior when using default option value or passing by parameter.

### Environment Details (include every applicable attribute)
  * Operating System+version: ANY
  * Compiler+version: Doesn't apply
  * Conan version: 1.41
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)

1) Create a recipes where there is an option which its value can be None:

```python
from conans import ConanFile
class FooConan(ConanFile):
    options = {"bar": [None, False, True]}
    options_values = {"bar": None}

    def configure(self):
        if self.options.bar is None:
            self.output.warn("BAR IS NONE.")
```

2) Build the package

    conan create . foo/0.1@user/testing

3) You don't see that message.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Related issue: https://github.com/ezored/conan-darwin-toolchain/pull/31

**Comment by memsharded** [comment]
This will be addressed in https://github.com/conan-io/conan/pull/9840

``None`` will be respected. Still the comparison must be done with ``self.options.bar == None``, as the ``is`` doesn't hold for custom objects, and ``.bar`` is an object around the None value

**Comment by paulocoutinhox** [comment]
Hi @memsharded,

So i need revert this commit:
https://github.com/ezored/conan-darwin-toolchain/commit/62263f0573950ea438ee1f00a11cfd38b1e11397

Correct?

**Comment by memsharded** [comment]
#9840 is for ``develop2`` will be released in 2.0, not now. But yes, your revert seems correct, the ``is`` cannot be used now in Conan 1.X, and it won't be possible either in 2.0. What will change in 2.0 is that ``if self.options.enable_bitcode == "None":`` and ``if self.options.enable_bitcode == None:`` will be different things, as pure Python ``None`` will be different to string text ``"None"``, the former indicating "value not defined", while the string will be allowed. So an option like ``options = {"myoption": [None, "None", "1", "2"]}`` could be valid, the first ``None`` allows the option to not be defined, while the second ``"None"``, means it is defined by user and is the user the responsible of handling that, similar to any other string.

**Comment by paulocoutinhox** [comment]
Hi @memsharded,

There is any option that work for both (v1 and v2)?

So, now, i need change for "is None" or "== None"? Because python None is an object, so it will work with "==" or "is" in the most case.

Thanks.

**Comment by memsharded** [comment]
This was fixed in https://github.com/conan-io/conan/pull/12761, in beta.7, closing the issue.

The recommendation is to use boolean checks ``if self.options.myoption`` in the general case, and have options semantics that not being defined is equivalent to being ``False``. If not possible, then comparisons must be always made with ``==``, not with ``is``.
