### ISSUE TITLE
[question] base lockfile with options

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#9915]
So I have package revisions enabled and would like to follow this example assuming all packages are using the same version, user and channel, and thus I omitted them. 

`app` depends on `pkga` and `pkg01` when `-o app:variant=01`
`app` depends on `pkga` and `pkg02` when `-o app:variant=02`

I want to create a base lock file for `app` because of this paragraph in [Lockfiles -> Multiple Configurations](https://docs.conan.io/en/latest/versioning/lockfiles/configurations.html)

> But, what if a new pkga/0.2@user/testing version was created in the time between both commands? Although this is unlikely to happen in this example, because everything is local. However, it could happen that pkga was in a server and the CI uploads a new pkga/0.2@user/testing version while we are running the above commands.

Now when I try creating the base lockfile without specifying the option, conan understandably wont let me do this, because the dependency graph would be ambiguous. 

But when I create the base lockfile with specifying the option, I run into the same risk again because I would then need to create two base lockfiles sequentially. I.e. the following scenario could happen:

```
conan lock create conanfile.py  -o variant=01 --lockfile-out=app_01_base.lock
// app_01_base.lock now locks pkga#rev01 and pkg01#rev01

*suppose at this point a new revision of pkga is uploaded concurrently*

conan lock create conanfile.py -o variant=02 --lockfile-out=app_02_base.lock
// app_02_base.lock now locks pkga#rev02 and pkg01#rev01
```
And thus I have two base lockfiles with different `pkga` locked.

How do I handle this case?

**Comment by memsharded** [comment]
Hi @altflg 

The ``base`` lockfile can only store a common subset of the dependencies. If you have incompatible dependencies for different configurations, you will need to capture and lock 2 different full lockfiles each one for each configuration.

Conan 2.0 lockfiles will probably improve over this, but it will take a while until GA, it is still under heavy development.

**Comment by Deflaktor** [comment]
Thank you for answering my question. Issue can be closed.

Btw. I really like conan and the work you guys are putting into it. Thanks for creating such an amazing tool. Keep it up!

**Comment by memsharded** [comment]
Thanks @Deflaktor for the feedback and the kind words! :)

If you like Conan already, keep tuned for 2.0, we are really excited about it!
