### ISSUE TITLE
[question] SHORT DESCRIPTION

### ISSUE THREAD

**Issue by rakeshcbpur** [conan-io/conan#9928]
I have read https://docs.conan.io/en/latest/installation.html about conan installation using python pip.

Wanted to know why python/pip is the recommended way to install conan ?

how does this approach solves the problem of automatically adding to the PATH variables the path to conan executable?

what happens when a newer version of python gets installed ?

**Comment by memsharded** [comment]
> Wanted to know why python/pip is the recommended way to install conan ?

- It is the most portable way, use ``pip install conan`` in every different platform
- It is fast, can be more easily automated (like to provision CI servers) than for example the Windows EXE installer
- It can use other tools and libraries in python. Many users have their own utilities, tools and other stuff, and it is easier to integrate if both can be installed in the same Python environment

> how does this approach solves the problem of automatically adding to the PATH variables the path to conan executable?

It is automated in the ``pip install``, for the majority of cases, unless your system configuration doesn't do that, doing ``pip install`` will make the ``conan`` executable available in the path

> what happens when a newer version of python gets installed ?

Conan works in Python>=3.6. Every python has its own environment, so you should do ``pip install conan`` in the environment of the new Python version interpreter. Actually, it is a good practice to use "virtual environments" for any Python related stuff in developer machines, not only related to Conan, but in general.

**Comment by rakeshcbpur** [comment]
thanks @memsharded for your quick response, regarding adding path to the PATH environment variable getting below warning after running python -m pip install conan
 WARNING: The scripts conan.exe, conan_build_info.exe and conan_server.exe are installed in 'C:\python\3.8.1.0.7\python-3.8.1.amd64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location

**Comment by memsharded** [comment]
> thanks @memsharded for your quick response, regarding adding path to the PATH environment variable getting below warning after running python -m pip install conan
WARNING: The scripts conan.exe, conan_build_info.exe and conan_server.exe are installed in 'C:\python\3.8.1.0.7\python-3.8.1.amd64\Scripts' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location

For some reason the "Scripts" folder was not added to the PATH when you installed Python. In Windows, using the Windows installer, I think this should have happened automatically, but in your case for some reason it didnt. You need to add it ``C:\python\3.8.1.0.7\python-3.8.1.amd64\Scripts``) yourself to your PATH env var.
