### ISSUE TITLE
[question] How to set output directory with CMakeDeps

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#9937]
How to set output directory with `CMakeDeps` ?

https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html

I have the following in `conanfile.py`

```python
def generate(self):
    tc = CMakeToolchain(self)
    tc.generate()

    deps = CMakeDeps(self)
    # When you have a build-require, by default,
    # the config files (xxx-config.cmake) files are not generated.
    # https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#build-context-activated
    deps.build_context_activated = ["catch2", "gtest"]
    deps.generate()
```

This will generate the files into the cmake build folder when `conan create ...` is invoked. I would like to specify a subdirectory `conan` under this folder (to not pollute it). How is this possible?

**Comment by memsharded** [comment]
Hi @gabyx 

The relative location of things is defined by the ``layout()`` method. I suggest having a look at: https://docs.conan.io/en/latest/reference/conanfile/methods.html#layout

In your case you might want to use the ``cmake_layout()`` (check https://docs.conan.io/en/latest/reference/conanfile/tools/layout.html too)

**Comment by gabyx** [comment]
Ah thanks a lot. Very much helpful.

**Comment by gabyx** [comment]
Hm, the problem I face now is that when I use `self.folders.generators` the package can get created but now testing the package suddenly fails because the geberated cmake scripts do not find component libs, because strangely lib dirs are empty in `*_data.cmake`. (v1.42). I will update with more information.

Do you know why?

**Comment by memsharded** [comment]
> Hm, the problem I face now is that when I use self.folders.generators the package can get created but now testing the package suddenly fails because the geberated cmake scripts do not find component libs, because strangely lib dirs are empty in *_data.cmake. (v1.42). I will update with more information.

Not very clear what is happening, maybe not connected to the ``layout`` and the output directories? In that case, we might be better closing this one, and open a new one with the details to reproduce it. I guess it is related to a dependency having defined ``components``? If you could provide something that I could reproduce here, that would help.

**Comment by gabyx** [comment]
Yes. I make a follow up. Thanks a lot!
