### ISSUE TITLE
[question] Should syntax `*:shared` be avoided on package creation?

### ISSUE THREAD

**Issue by lucabonifacio** [conan-io/conan#9941]
What are the recommendations / best practices when propagating option values to the requirements?

Is it recommended to use `configure()` to assign the value of the requirements options, like here?

``` python
class MyLibConan(ConanFile):
    name = "MyLib"
    version = "2.5"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}

    def configure(self):
        self.options["boost"].shared = self.options.shared
        self.options["openssl"].shared = self.options.shared
        self.options["zlib"]. shared = False

   def requirements(self):
       self.requires("boost/[1.72]@")
       self.requires("openssl/[2.0]@")
       self.requires("zlib/[3.1]@")
```

And then create the package with `conan create . 1.0.0@ -o MyLib:shared=True`

Or is it common practice to use the syntax `*:shared=<value>`?

``` python
class MyLibConan(ConanFile):
    name = "MyLib"
    version = "2.5"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}

    def configure(self):
        self.options["zlib"]. shared = False

   def requirements(self):
       self.requires("boost/[1.72]@")
       self.requires("openssl/[2.0]@")
       self.requires("zlib/[3.1]@")
```

And then create the package with `conan create . 1.0.0@ -o *:shared=True`

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AbrilRBS** [comment]
Sorry that we dropped the ball on getting back to you on a timely fashion :/

For anyone wondering the same, the recommended approach is to set the options via the CLI/profiles (For shared we mostly recommend the `*:shared=True/False` syntax), and if a recipe  has a strict need for any of its dependencies to have a specific option value, it should check it in the `validate()` method.

Again, sorry for not writing back sooner, this should have been addressed a while back
