### ISSUE TITLE
[bug] XcodeDeps generates bad xcconfig variables with dash-cased pkg and armv8 arch

### ISSUE THREAD

**Issue by jevarg** [conan-io/conan#9949]
# XcodeDeps generates bad xcconfig variables with dash-cased pkg and armv8 arch

### Environment Details (include every applicable attribute)
  * Conan version: 1.42

### Steps to reproduce (Include if Applicable)
- Create  a conanfile with a requirement on a dash-cased package: `requires =  "test-lib/x.y.z"`
- Set the XcodeDeps generator: `generators = "XcodeDeps"`
- Install armv8 deps `conan install . -s arch=armv8`

### Logs (Executed commands with output) (Include/Attach if Applicable)
Here is the content of one of the generated `.xcconfig` file:
![Screenshot 2021-11-04 at 17 05 46](https://user-images.githubusercontent.com/2744572/140375936-d43f1432-aca3-4922-96ff-02e8b12b62da.png)

Possible fixed naming using snake_case:
![Screenshot 2021-11-04 at 17 08 30](https://user-images.githubusercontent.com/2744572/140376161-1ccc0e4c-920e-4b74-8d05-107d26d8f077.png)

On top of that, if I try to build with Xcode with an arm64 iOS target, those variables will never be used as Xcode uses `arm64` instead of `armv8` that is generated by conan with XcodeDeps.

**Comment by czoido** [comment]
Hi @jevarg 
Thanks a lot for reporting, and also thanks a lot for contributing the fix, we'll review it. to be merged ASAP.

**Comment by memsharded** [comment]
Fixed in #9955, will be released soon in 1.42.1
