### ISSUE TITLE
How to build vcpkg/* packages with static runtime?

### ISSUE THREAD

**Issue by akazantsev** [conan-io/conan#995]
Hello,

How can I build vcpkg/* packages with static runtime? It seems that those always builds with `/MD /MDd` and settings like `compiler.runtime=MT` has no effect on those packages.

# Mine solution:

I found simple hack to build  those packages with `/MT[d]` in [vcpkg article](https://blogs.msdn.microsoft.com/vcblog/2016/11/01/vcpkg-updates-static-linking-is-now-available/)

You simply need to add `-DVCPKG_TARGET_TRIPLET=x86-windows-static` triplet to recipe depending on your compiler.runtime

As simple and fast solution I simply replaced those parameters in `_get_triplet(self)` function with static ones.

```python
    def _get_triplet(self):
        tmp = {"x86_64": "x64-windows",
               "x86": "x86-windows"}
        return tmp[str(self.settings.arch)]
```

But I encountered one problem: I found no easy way to download a recipe of the package. I had to use `conan install` and look for path of downloaded recipe and other files in the log then copy it from that folder.

# Questions:

Is there simpler way to build vcpkg packages with /MT?

How to download recipe of packages?

**Comment by memsharded** [comment]
Hi Andrey,

Have you read this entry in the blog? http://blog.conan.io/2016/10/17/Using-Vcpkg-ports-as-Conan-packages.html. It might be useful if you haven't

Basically the recipes are all much the same, so they are automatically generated. You might want to have a look to @lasote vcpkg fork: https://github.com/lasote/vcpkg. I think the way could be to improve those recipes to handle the MT flag (``self.settings.compiler.runtime``), so the ``_get_triplet()`` takes it into account. 

This is an extremely unusual case, in which the recipes are not hosted in a github repo. Most other regular package recipes have the "url" field pointing to the github repo so it can even be navigated to from the conan.io web page. The normal process to edit recipes is not via conan, is via git, like any other source code. Conan package recipes are just code, so the way to fork, modify, and collaborate with them is via github.
