### ISSUE TITLE
[bug] CMakeDeps problem with (transitive) build_requirements (at least for Boost)

### ISSUE THREAD

**Issue by n00b42** [conan-io/conan#9951]
CMakeDeps generator does not generate files for transitive build requirements, but does for (normal) requirements.

At least happening for boost.

### Files

`conanfile.py`
~~~
from conans import ConanFile, CMake
class AbcConan(ConanFile):
	name = "ABC"
	version = "1.0.0"
	settings = { "os", "compiler", "build_type", "arch" }
#	requires = [ "boost/1.77.0" ]
	build_requires = [ "boost/1.77.0" ]
	generators = "CMakeDeps"
	def build(self):
		cmake = CMake(self)
		cmake.configure()
		cmake.build()
	def package(self):
		cmake = CMake(self)
		cmake.install()

~~~
`CMakeLists.txt`
~~~
cmake_minimum_required(VERSION 3.12)
project(ABC VERSION 1.0.0)
set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR} ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR} ${CMAKE_PREFIX_PATH})
find_package(boost REQUIRED)
add_executable(ABC main.cpp)
target_link_libraries(ABC PRIVATE boost::boost)
~~~
`main.cpp`
~~~
#include <iostream>
int main() {
    std::cout << "Hello World!";
    return 0;
}
~~~

### Steps

`conan install .. && cmake .. && make`

Output 1 (with boost in `requires`) 
~~~
[...]
-- Conan: Target declared 'boost::boost'
-- Conan: Target declared 'bzip2::bzip2'
[...]
~~~

Output 2 (with boost in `build_requires`)
~~~
[...]
-- Conan: Target declared 'boost::boost'
CMake Error at /usr/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Could not find a package configuration file provided by "bzip2" with any of
  the following names:

    bzip2Config.cmake
    bzip2-config.cmake

  Add the installation prefix of "bzip2" to CMAKE_PREFIX_PATH or set
  "bzip2_DIR" to a directory containing one of the above files.  If "bzip2"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  build/boost-config.cmake:16 (find_dependency)
  CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
~~~

### Environment Details (include every applicable attribute)
  * Operating System+version: debian/testing (Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux)
  * Compiler+version: gcc 10.3.0
  * Conan version: 1.42.0
  * Python version: 3.9.7

**Comment by memsharded** [comment]
Hi @n00b42 

This is intended, ``build_requires`` are mostly intended for tools, like CMake. By default they don't generate ``xxx-config.cmake`` files, and they do not generate transitive ones either.

What is the meaning of having boost as ``build_requires``. If you plan to use it for testing, then you might want to use a ``self.requires("boost...", force_host_context=True)`` to guarantee it is linked in the host context. But you already have boost in the host context because of the regular ``requires`` so this wouldn't be needed either.

Furthermore, from now on, specially if you are using the new integrations, you are encouraged to define both the host profile and the build profile (use ``--profile:build=default``). This changes how build_requires are evaluated, and if you check your stdout, you will see some warnings that this is recommended and CMakeDeps could fail otherwise.

**Comment by n00b42** [comment]
@memsharded Thanks for the answer.

Actually, boost should not be in "requires" as it is not required to use the library (I just included the requires line to show that switching to it from build_requires made it work for me).  
However, I have some unit tests that require boost which are only needed during build time.

I am aware of the two profiles, and usually use them for creating packages, just tried a minimal setup for the bug report

---
Using the `test_package` actually did mostly what I wanted, a standalone context to test my library. However, I have been told that `test_package` should only be used to test that the packaging itself worked correctly and that unittest might be integrated in the build phase.  
So I added my unit tests using CTest as a seperate target that is only used in the build step (cmake.test()), but now I struggle to exclude boost from the actual ("runtime") requirements of my library.  
Is this possible, and is there a preferred way to achieve it?

**Comment by memsharded** [comment]
Ok, so if it is only a build_require, for testing, then try the mentioned ``force_host_context=True`` above, and let us know if it worked.

**Comment by n00b42** [comment]
Using `force_host_context=True` worked. Thank you.

~~~
	def build_requirements(self):
		self.build_requires("boost/1.77.0", force_host_context=True)
~~~

**Comment by memsharded** [comment]
Thanks for telling. Closing this now (follow up issue in https://github.com/conan-io/conan/issues/9963) to be ready for 2.0
