### ISSUE TITLE
[bug] setting.yml with missing msvc compiler crashes conan create

### ISSUE THREAD

**Issue by simue** [conan-io/conan#9953]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc-10
  * Conan version: 1.42.0
  * Python version:  3.8.10

### Steps to reproduce (Include if Applicable)
Have a fresh conan install, create a demo package like so:
```
mkdir hellopkg && cd hellopkg<br>
conan new hello/0.1 --template=cmake_lib<br>
conan create . demo/testing
```

See that the package is correctly created.

Have a fresh conan install.
Place a settings.yml file in $HOME/.conan/ that has no msvc compiler entry.
Create a demo package like above.
Get the following error:
```
ERROR: hello/0.1@demo/testing (test package): Error in layout() method, line 25
	cmake_layout(self)
	ConanException: Invalid setting 'msvc' is not a valid 'settings.compiler' value.
Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'qcc', 'sun-cc']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

I suspect that this is due to code in `conan/tools/layout/__init__.py`:
In line 11 `cmake_layout()` checks if the current compiler is set to "Visual Studio" or "msvc". But the underlying method (`SettingsItem.__eq__`) is implemented in a way, that only accepts values from `SettingsItem.values_range` (in which all compilers except msvc are, since we deleted it from `settings.yml`).
So the fix would be to get the current compiler's string representation when comparing in `conan/tools/layout/__init__.py` line 11:
```
elif conanfile.settings.compiler.value == "Visual Studio" or conanfile.settings.compiler.value == "msvc":
```
instead of:
```
elif conanfile.settings.compiler == "Visual Studio" or conanfile.settings.compiler == "msvc":
```
OR refactor `SettingsItem.__eq__` s.t. it just checks equality and does not do any additional magic

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
simue@simue-host:~/repos/hellopkg$ conan create . demo/testing
Exporting package recipe
hello/0.1@demo/testing exports_sources: Copied 1 '.txt' file: CMakeLists.txt
hello/0.1@demo/testing exports_sources: Copied 1 '.cpp' file: hello.cpp
hello/0.1@demo/testing exports_sources: Copied 1 '.h' file: hello.h
hello/0.1@demo/testing: The stored package has not changed
hello/0.1@demo/testing: Exported revision: 92f2b6e1978dec56197a54c5ac87a104
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os.glibc=2.31
os_build=Linux
[options]
[build_requires]
[env]
CC=gcc-10
CXX=g++-10
ERROR: hello/0.1@demo/testing (test package): Error in layout() method, line 25
	cmake_layout(self)
	ConanException: Invalid setting 'msvc' is not a valid 'settings.compiler' value.
Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'qcc', 'sun-cc']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

**Comment by memsharded** [comment]
Hi @simue 

Lets fix this quickly for next 1.42.1.

However, please note the ``msvc`` is there to replace ``Visual Studio`` compiler in 2.0. It is still experimental, but please keep an eye on it for the future.

**Comment by memsharded** [comment]
Thanks for your detailed report, it helped to solve the issue quickly. Proposing https://github.com/conan-io/conan/pull/9954 for next patch version 1.42.1 to be released soon.

**Comment by simue** [comment]
Thank you for your quick reaction. Greatly appreciated!

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/9954 will be release in Conan 1.42.1 soon
