### ISSUE TITLE
[question] Calling conan install from WSL shell

### ISSUE THREAD

**Issue by GPages** [conan-io/conan#9971]
Hello,

I have seen posts that seem related to my issue, but i don't understand how to fix my problem.

Conan version: 1.42.0

In a nutshell, following command works fine when run in a bash terminal inside WSL :
`cd /myCode/build && /usr/local/bin/cmake  -G 'CodeBlocks - Unix Makefiles' /myCode`

But the same command fails when called from windows terminal:
`wsl.exe --distribution Ubuntu-20.04 --exec /bin/sh -c "cd /myCode/build && /usr/local/bin/cmake  -G 'CodeBlocks - Unix Makefiles' /myCode"`

```
-- Conan executing: conan install . -g cmake -s build_type=Debug -s os=Linux -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -s os.distro=ubuntu -s os.version=20.04 --build=missing
CMake Error at cmake/conan.cmake:444 (message):
  Conan install failed='No such file or directory'
Call Stack (most recent call first):
  cmake/conan.cmake:523 (conan_cmake_install)
```

I have not worked on our build system, and it seems pretty complicated so it might very well be a bug on our side. However i was not able to get much more information on the issue, even with all logging options enabled (both on conan and cmake).
Could you please help me find the issue ? What is the main difference between the two commands above ?

If needed, i can setup a minimal project to reproduce.
Thank you :)

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @GPages 

It seems a difficult to debug thing. Could you please post the full output? The lines about the error could have some hints of what could be happening.

**Comment by GPages** [comment]
From the command line, this can be fixed by using '-l' option of /bin/sh. This will add "/home/me/.local/bin" to the beginning of the PATH and, for some reason, it fixes the above issue.
In my case the issue is that this command is run by CLion so i can't change it. I fixed it by installing conan globally in WSL.

This question can be closed, sorry for this :)

**Comment by memsharded** [comment]
Thanks for the feedback, don't worry about it, dont hesitate to open new issues if you have any other question :)
