### ISSUE TITLE
[bug] Failed to parse patch for patches created by git

### ISSUE THREAD

**Issue by sboehmann** [conan-io/conan#9972]
When I create a patch using `git diff` and want to apply it with Conan, I get the exception `ConanException: Failed to parse patch: ...`.

The problem is the header of the patch. For me, `git diff` creates a header like:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 052bdb4..5562445 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
```

However, I can fix the problem by replacing `a` and `b` with `i` and `w`, like this:
```
diff --git i/CMakeLists.txt w/CMakeLists.txt
index 052bdb4..5562445 100644
--- i/CMakeLists.txt
+++ w/CMakeLists.txt
```
The problem did not exist in the past, but has existed since a few versions now. Right now I'm using git version 2.33.1. No idea if and when, or under what circumstances git has changed this. Localization maybe?

Anyway, it would be nice if conan would accept pristine git diff patches.

**Comment by memsharded** [comment]
The application of patches is done in an external library, not Conan. While we have forked it (patch-ng) to be able to fix some things, we would prefer not to deviate much from the upstream. 
It would also be good to have some official reference about this change or new behavior in git. At least in the official docs, it seems they are still using ``a`` and ``b``: https://git-scm.com/docs/git-diff

**Comment by evtodorov** [comment]
Was getting a similar error message, traced it down to the git-exported patch being saved with UTF-16LE encoding which `patch-ng` failed to parse properly. My best guess is that whichever editor @sboehmann used changed the encoding of his file on write. For me changing manually to UTF-8 worked a dream.
[may be related](https://stackoverflow.com/questions/13675782/git-shell-in-windows-patchs-default-character-encoding-is-ucs-2-little-endian)

**Comment by es20490446e** [comment]
In my case the text editor was automatically removing end-line spaces.

**Comment by memsharded** [comment]
Thanks for the follow up all.

So it seems that ``a`` and ``b`` markers are accepted (I see they are thoroughly used in conan-center-index recipes), and problems might become from other reasons, like encodings or line endings.

In any case, the patching is done by this external library, not Conan, so not something that can be easily changed anyway in our side.

As the encoding and line endings issues would be a bit outside of the Conan patching scope, I'd suggest closing this issue, but don't hesitate to re-open or create new tickets for any further questions. Thanks all for the feedback!
