### ISSUE TITLE
[Bug] `--install-folder` not honoured when using layout.

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#9978]
When conan install is executed from cmake (with cmake-conan):

```
-- Conan executing: /home/developer/python-envs/default/bin/conan install /cmake-general/tests/project --install-folder /cmake-general/tests/build/conan --build missing --profile:host default --profile:build default --settings build_type=Release --settings compiler=clang --settings compiler.version=12 --settings compiler.libcxx=libstdc++11
```

and with 

```
def layout(self):
    cmake_layout(self)
```

in the `conanfile.py`, the install folder `--install-folder /cmake-general/tests/build/conan` is not honoured, but the generated files go into
`/cmake-general/tests/project/cmake-build-cona/conan`.

Why is that?

**Comment by gabyx** [comment]
Or can we actually gather the CLI argument `--install-folder` ?

**Comment by gabyx** [comment]
Any help in this direction?

The problem is actually that `self.install_folder` which should align with `--install-folder`, is not set during `layout`.
Why is that?

**Comment by AbrilRBS** [comment]
Sorry for the lack of communication, we should haven communicated better that the `--install-folder` would be going away in Conan 2 and thus no prioritization was given to features like this
