### ISSUE TITLE
[question] Removing all packages for specific query from local cache

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#9983]
When issuing command

```
conan remove '*' --builds --packages --query 'os=Emscripten'
```

I get the error

```
ERROR: '-q' and '-p' parameters can't be used at the same time
```

This is also documented, but does it have to be like this? Why am I restricted to deleting packages matching the query only for a single reference and not for the pattern?

**Comment by AbrilRBS** [comment]
Closing as solved in v2, which allows the use of package list as the vehicle for passing info between commands, which works way better than having to support custom syntaxes for commands :)
