### ISSUE TITLE
[bug] imports from symbolic names takes a very long time

### ISSUE THREAD

**Issue by dvirtz** [conan-io/conan#9986]
The `imports` function started taking a very long time in our builds. We tracked it down to the code at https://github.com/conan-io/conan/blob/ea7e87914b7e6cc825321842a615be0c59fe25f6/conans/client/importer.py#L172-L176 which adds `libdirs` (which by default be just `'lib'`), for example, from all components to the list of folders to copy from and so causes the following code to repeatedly copy from the same folder over and over again.

For now, we're working around this by replacing `@libdir` with `'lib'` in our `imports` function, which seems to have the same effect for our dependencies.

### Environment Details (include every applicable attribute)
  * Conan version: 1.41.0

### Steps to reproduce (Include if Applicable)
install the following `conanfile.py`:
```python
from conans import ConanFile
from datetime import datetime

class Bug(ConanFile):
  requires = "boost/1.76.0"
  default_options = {
    "boost:shared": True
  }

  def imports(self):
    self.output.info("starting import at {}".format(datetime.now().isoformat()))
    self.copy("*.so*", dst="lib", src="@libdirs")
    self.output.info("finished import at {}".format(datetime.now().isoformat()))
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
conanfile.py: starting import at 2021-11-08T19:53:44.441408
conanfile.py: finished import at 2021-11-08T19:54:44.498952
```

**Comment by memsharded** [comment]
The ``imports()`` method has been made legacy in Conan 1.X by explicit ``copy()`` in ``generate()`` and removed in Conan 2.0. Closing this ticket, please create new tickets as necessary, thanks!
