### ISSUE TITLE
[feature] how to set build requirement options?

### ISSUE THREAD

**Issue by HaoLiuHust** [conan-io/conan#9987]
I have a build requirements which have different options with host, how to set it ?

**Comment by SpaceIm** [comment]
With 2 profiles, you can set different options for build requirements with `-o:b` in conan install/create command line, or even use different options in each profile I think (options of build requirements in the profile used for `-pr:b`, and options of requirements in the profile used for `-pr:h`).

Example:

```bash
conan install foo/1.0@ -pr:b build-profile -pr:h host-profile -o:b *:shared=False -o:h *:shared=True
```

But I believe that there is currenlty no way to set different options for build requirements and requirements directly in a conanfile.

**Comment by madebr** [comment]
I think having functionality to set options of build requirements in a profile + checking in a recipe would be useful.
It seems [the cci qt recipe](https://github.com/conan-io/conan-center-index/pull/8116#discussion_r753408069) would benefit from such featuer.

**Comment by AbrilRBS** [comment]
Conan 2.0.10 added [`default_build_options`](https://docs.conan.io/2/reference/conanfile/attributes.html?highlight=default_build_options#id31) attribute to be able to add options to tool requires from within recipes.

Closing as solved alongside the explanation above by Spaceim, thanks both!
