### ISSUE TITLE
[bug] Recipes depending on deps_cpp_info -> colliding hashes

### ISSUE THREAD

**Issue by gogoprog** [conan-io/conan#9991]
### Environment Details
  * Operating System+version: all
  * Compiler+version: all
  * Conan version: all
  * Python version: all

### Steps to reproduce 

If a recipe has its build step depending on `deps_cpp_info` then it will generates different packages using the same hash.

Concrete example : `sdl` recipe depends on `pulseaudio:shared` value. But changing this value won't change the `sdl` hash.

Is there something I miss?
Could we add `deps_cpp_info` into the hash computation ?

**Comment by memsharded** [comment]
First, ``deps_cpp_info`` is to be removed. It has already been removed in 2.0. The new access to dependencies information is ``self.dependencies``.

This is not a bug, but expected, by default dependencies options do not affect the consumers ``package_id``. It can be changed, for example, using some of the ``package_id_mode``, like moving to ``full_package_mode``, that means if the dependency ``package_id`` is different, the consumer ``package_id`` will also change. Changing the ``package_id_mode`` can be done per-recipe, in the ``package_id()`` method, or globally in the configuration, changing the ``default_package_id_mode``. If explicit modeling of dependencies options into the package_id is desired, that can also be added in the ``self.info.options`` in the ``package_id()`` method. 

In any case, the management of shared-static libraries, including changes by default in the ``package_id`` computation, is already being improved in 2.0.

**Comment by gogoprog** [comment]
Good to know for 2.0 and thanks for the information!

**Comment by gogoprog** [comment]
@memsharded I did not manage to use it correctly:

I have this in the sdl recipe:
```py
    def package_id(self):
        del self.info.options.sdl2main

        if self.settings.os == "Linux":
            if self.options.alsa:
                self.info.requires["libalsa"].full_version_mode()
            if self.options.esd:
                self.info.requires["esd"].full_version_mode()
            if self.options.pulse:
                self.info.requires["pulseaudio"].full_version_mode()
            if self.options.sndio:
                self.info.requires["sndio"].full_version_mode()
```

And I use the conan option `pulseaudio:shared=True`

But changing this value does not change the sdl package I receive.
