### ISSUE TITLE
[bug] conan imports doesn't work with conan lock install

### ISSUE THREAD

**Issue by SoftwareApe** [conan-io/conan#9996]
We use conan imports to import the installed files to a specific directory. The team that we get the distribution from now uses conan lock install instead of conan install.

Due to the lack of a conanfile.txt or conanfile.py when using lock install we can't use imports anymore.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: GCC 7.5
  * Conan version: 1.42.1
  * Python version: 3.6

### Steps to reproduce (Include if Applicable)
Install something from lock file using conan lock install

try to use conan imports to import.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: Conanfile not found at <path>/conanfile.py or <path>/conanfile.txt
```

**Comment by memsharded** [comment]
The ``imports()`` method has been made legacy in Conan 1.X by explicit ``copy()`` in ``generate()`` and removed in Conan 2.0. Closing this ticket, please create new tickets as necessary, thanks!
