### ISSUE TITLE
[feature] Import package artifacts only from selected package dependencies

### ISSUE THREAD

**Issue by jlemein** [conan-io/conan#9997]
The imports function imports artifacts in the build directory. This results in many different artifacts from dependencies to be imported in the same lib and bin folder. This clutters the build directories with artifacts of many different applications and libraries. It would be nice to specify import statements only for selected package requirements.

So additional to this:
```
self.copy("*", src="bin", dst="bin")
self.copy("*.so*", src="lib", dst="lib")
```
Make it possible to do this as well:
```
self.requirements['toolA'].copy("*", src="bin", dst="toolA/bin")
self.requirements['mygui'].copy("*", src="bin", dst="mygui/bin")
```

The reason that this would be nice is that I am making an installer that can install multiple components (gui tools, apps, config files). Now I need to hardcode the library and executable files to be installed. It would be nice to be able to select all artifacts belonging to packageA, which could contain many different shared libraries and/or data files. Those might change over time for newer releases.

The workaround I am currently doing is to package my dependencies in it's own directory so that I can select them easily by directory.
Is this possible to do in conan?

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Have you checked the ``root_package`` and ``folder`` arguments in ``imports()``? https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports It seems that this is what you are looking for?

**Comment by jlemein** [comment]
I feel stupid to have missed that part. You are right. Thanks.

**Comment by memsharded** [comment]
No prob @jlemein happy to be able to help :) 
Don't hesitate to file new tickets if you have any further questions.
