### ISSUE TITLE
[bug] `Blocks` object not visible / importable

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#9998]
The [documentation](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#extending-and-customizing-cmaketoolchain) suggests, if you want to extend `CMakeToolchain` with custom blocks, you need to inherit from it.
However, it cannot be imported:

```
from conan.tools.cmake import CMakeToolchain, CMake, Block
```
fails with
```
ImportError: cannot import name 'Block' from 'conan.tools.cmake'
```

This can be fixed by adding it to the `__init__.py` (file)[https://github.com/conan-io/conan/blob/1.42.1/conan/tools/cmake/__init__.py].

### Environment Details (include every applicable attribute)
  * Conan 1.42.1:

**Comment by memsharded** [comment]
Yes, this is a bug, unittesting skipped it because of internal import.

For the external interface, probably it deserves a better, specific name, like CMakeToolchainBlock

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/10026, will be in 1.43
